Cataclysm DDA: src/computer_session.cpp File Reference
computer_session.cpp File Reference
#include "computer_session.h"
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <functional>
#include <memory>
#include <optional>
#include <string>
#include <utility>
#include "avatar.h"
#include "calendar.h"
#include "character.h"
#include "character_id.h"
#include "colony.h"
#include "color.h"
#include "computer.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "creature.h"
#include "creature_tracker.h"
#include "debug.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "explosion.h"
#include "field_type.h"
#include "flag.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "input.h"
#include "input_context.h"
#include "input_enums.h"
#include "item.h"
#include "item_location.h"
#include "line.h"
#include "localized_comparator.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "messages.h"
#include "mission.h"
#include "monster.h"
#include "mtype.h"
#include "mutation.h"
#include "npc.h"
#include "omdata.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "overmap_ui.h"
#include "overmapbuffer.h"
#include "pocket_type.h"
#include "point.h"
#include "ret_val.h"
#include "rng.h"
#include "sounds.h"
#include "string_formatter.h"
#include "text_snippets.h"
#include "timed_event.h"
#include "translation.h"
#include "translations.h"
#include "trap.h"
#include "type_id.h"
#include "ui.h"
#include "ui_manager.h"
Functions
static catacurses::window init_window ()
static item * pick_usb ()
static void remove_submap_turrets ()
Variables
static const efftype_id effect_amigara ("amigara")
static const furn_str_id furn_f_centrifuge ("f_centrifuge")
static const furn_str_id furn_f_console_broken ("f_console_broken")
static const furn_str_id furn_f_counter ("f_counter")
static const furn_str_id furn_f_rubble_rock ("f_rubble_rock")
static const itype_id itype_black_box ("black_box")
static const itype_id itype_blood ("blood")
static const itype_id itype_blood_tainted ("blood_tainted")
static const itype_id itype_c4 ("c4")
static const itype_id itype_cobalt_60 ("cobalt_60")
static const itype_id itype_mininuke ("mininuke")
static const itype_id itype_mininuke_act ("mininuke_act")
static const itype_id itype_radio_repeater_mod ("radio_repeater_mod")
static const itype_id itype_sarcophagus_access_code ("sarcophagus_access_code")
static const itype_id itype_sewage ("sewage")
static const itype_id itype_usb_drive ("usb_drive")
static const itype_id itype_vacutainer ("vacutainer")
static const mission_type_id mission_MISSION_OLD_GUARD_NEC_COMMO_2 ("MISSION_OLD_GUARD_NEC_COMMO_2")
static const mission_type_id mission_MISSION_OLD_GUARD_NEC_COMMO_3 ("MISSION_OLD_GUARD_NEC_COMMO_3")
static const mission_type_id mission_MISSION_OLD_GUARD_NEC_COMMO_4 ("MISSION_OLD_GUARD_NEC_COMMO_4")
static const mission_type_id mission_MISSION_OLD_GUARD_REPEATER ("MISSION_OLD_GUARD_REPEATER")
static const mission_type_id mission_MISSION_OLD_GUARD_REPEATER_BEGIN ("MISSION_OLD_GUARD_REPEATER_BEGIN")
static const mission_type_id mission_MISSION_REACH_REFUGEE_CENTER ("MISSION_REACH_REFUGEE_CENTER")
static const mtype_id mon_manhack ("mon_manhack")
static const mtype_id mon_secubot ("mon_secubot")
static const oter_type_str_id oter_type_sewer ("sewer")
static const oter_type_str_id oter_type_subway ("subway")
static const skill_id skill_computer ("computer")
static const species_id species_HUMAN ("HUMAN")
static const species_id species_ZOMBIE ("ZOMBIE")
static const ter_str_id ter_t_concrete ("t_concrete")
static const ter_str_id ter_t_concrete_wall ("t_concrete_wall")
static const ter_str_id ter_t_door_metal_c ("t_door_metal_c")
static const ter_str_id ter_t_door_metal_locked ("t_door_metal_locked")
static const ter_str_id ter_t_elevator ("t_elevator")
static const ter_str_id ter_t_elevator_control ("t_elevator_control")
static const ter_str_id ter_t_elevator_control_off ("t_elevator_control_off")
static const ter_str_id ter_t_floor ("t_floor")
static const ter_str_id ter_t_floor_blue ("t_floor_blue")
static const ter_str_id ter_t_floor_green ("t_floor_green")
static const ter_str_id ter_t_floor_red ("t_floor_red")
static const ter_str_id ter_t_grate ("t_grate")
static const ter_str_id ter_t_hole ("t_hole")
static const ter_str_id ter_t_metal_floor ("t_metal_floor")
static const ter_str_id ter_t_missile ("t_missile")
static const ter_str_id ter_t_rad_platform ("t_rad_platform")
static const ter_str_id ter_t_radio_tower ("t_radio_tower")
static const ter_str_id ter_t_reinforced_glass ("t_reinforced_glass")
static const ter_str_id ter_t_reinforced_glass_shutter ("t_reinforced_glass_shutter")
static const ter_str_id ter_t_reinforced_glass_shutter_open ("t_reinforced_glass_shutter_open")
static const ter_str_id ter_t_sewage ("t_sewage")
static const ter_str_id ter_t_sewage_pipe ("t_sewage_pipe")
static const ter_str_id ter_t_sewage_pump ("t_sewage_pump")
static const ter_str_id ter_t_thconc_floor ("t_thconc_floor")
static const ter_str_id ter_t_vat ("t_vat")
static const ter_str_id ter_t_wall_glass ("t_wall_glass")
static const ter_str_id ter_t_wall_metal ("t_wall_metal")
static const ter_str_id ter_t_water_pool ("t_water_pool")
Function Documentation
init_window()
static catacurses::window init_window () static
Definition at line 141 of file computer_session.cpp.
 {
     const int width = FULL_SCREEN_WIDTH;
     const int height = FULL_SCREEN_HEIGHT;
     const point p( std::max( 0, ( TERMX - width ) / 2 ), std::max( 0, ( TERMY - height ) / 2 ) );
     return catacurses::newwin( height, width, p );
 }
References FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, max(), catacurses::newwin(), TERMX, and TERMY.
Referenced by debug_error_prompt(), draw_item_info(), and scrollable_text().
pick_usb()
static item* pick_usb () static
Definition at line 296 of file computer_session.cpp.
 {
     auto filter = []( const item & it ) {
         return it.typeId() == itype_usb_drive;
     };
     item_location loc = game_menus::inv::titled_filter_menu( filter, get_avatar(),
                         _( "Choose drive:" ) );
     if( loc ) {
         return &*loc;
     }
     return nullptr;
 }
References _, filter, get_avatar(), itype_usb_drive, and game_menus::inv::titled_filter_menu().
Referenced by computer_session::action_blood_anal(), and computer_session::action_download_software().
remove_submap_turrets()
static void remove_submap_turrets () static
Definition at line 310 of file computer_session.cpp.
 {
     Character &player_character = get_player_character();
     map &here = get_map();
     for( monster &critter : g->all_monsters() ) {
         // Check 1) same overmap coords, 2) turret, 3) hostile
         if( ms_to_omt_copy( here.getabs( critter.pos() ) ) == ms_to_omt_copy( here.getabs(
                     player_character.pos() ) ) &&
             critter.has_flag( mon_flag_CONSOLE_DESPAWN ) &&
             critter.attitude_to( player_character ) == Creature::Attitude::HOSTILE ) {
             g->remove_zombie( critter );
         }
     }
 }
References g, get_map(), get_player_character(), map::getabs(), Creature::HOSTILE, mon_flag_CONSOLE_DESPAWN, ms_to_omt_copy(), and Creature::pos().
Referenced by computer_session::action_open_disarm(), computer_session::action_release_disarm(), and computer_session::action_unlock_disarm().
Variable Documentation
effect_amigara
const efftype_id effect_amigara("amigara") ("amigara") static
Referenced by computer_session::failure_amigara().
furn_f_centrifuge
const furn_str_id furn_f_centrifuge("f_centrifuge") ("f_centrifuge") static
Referenced by computer_session::action_blood_anal(), and computer_session::failure_destroy_blood().
furn_f_console_broken
const furn_str_id furn_f_console_broken("f_console_broken") ("f_console_broken") static
Referenced by computer_session::failure_shutdown().
furn_f_counter
const furn_str_id furn_f_counter("f_counter") ("f_counter") static
Referenced by computer_session::action_sample().
furn_f_rubble_rock
const furn_str_id furn_f_rubble_rock("f_rubble_rock") ("f_rubble_rock") static
Referenced by computer_session::action_srcf_seal().
itype_black_box
const itype_id itype_black_box("black_box") ("black_box") static
Referenced by computer_session::action_data_anal().
itype_blood
const itype_id itype_blood("blood") ("blood") static
Referenced by computer_session::action_blood_anal(), and computer_session::failure_destroy_blood().
itype_blood_tainted
const itype_id itype_blood_tainted("blood_tainted") ("blood_tainted") static
Referenced by computer_session::action_blood_anal(), and computer_session::failure_destroy_blood().
itype_c4
const itype_id itype_c4("c4") ("c4") static
Referenced by computer_session::action_irradiator().
itype_cobalt_60
const itype_id itype_cobalt_60("cobalt_60") ("cobalt_60") static
Referenced by computer_session::action_extract_rad_source().
itype_mininuke
const itype_id itype_mininuke("mininuke") ("mininuke") static
Referenced by computer_session::action_irradiator().
itype_mininuke_act
const itype_id itype_mininuke_act("mininuke_act") ("mininuke_act") static
Referenced by computer_session::action_irradiator().
itype_radio_repeater_mod
const itype_id itype_radio_repeater_mod("radio_repeater_mod") ("radio_repeater_mod") static
Referenced by computer_session::action_repeater_mod().
itype_sarcophagus_access_code
const itype_id itype_sarcophagus_access_code("sarcophagus_access_code") ("sarcophagus_access_code") static
Referenced by computer_session::action_srcf_elevator().
itype_sewage
const itype_id itype_sewage("sewage") ("sewage") static
Referenced by computer_session::action_sample().
itype_usb_drive
const itype_id itype_usb_drive("usb_drive") ("usb_drive") static
Referenced by computer_session::action_data_anal(), computer_session::failure_destroy_data(), and pick_usb().
itype_vacutainer
const itype_id itype_vacutainer("vacutainer") ("vacutainer") static
Referenced by computer_session::failure_destroy_blood().
mission_MISSION_OLD_GUARD_NEC_COMMO_2
const mission_type_id mission_MISSION_OLD_GUARD_NEC_COMMO_2("MISSION_OLD_GUARD_NEC_COMMO_2") ("MISSION_OLD_GUARD_NEC_COMMO_2") static
Referenced by computer_session::action_complete_disable_external_power().
mission_MISSION_OLD_GUARD_NEC_COMMO_3
const mission_type_id mission_MISSION_OLD_GUARD_NEC_COMMO_3("MISSION_OLD_GUARD_NEC_COMMO_3") ("MISSION_OLD_GUARD_NEC_COMMO_3") static
Referenced by computer_session::action_repeater_mod().
mission_MISSION_OLD_GUARD_NEC_COMMO_4
const mission_type_id mission_MISSION_OLD_GUARD_NEC_COMMO_4("MISSION_OLD_GUARD_NEC_COMMO_4") ("MISSION_OLD_GUARD_NEC_COMMO_4") static
Referenced by computer_session::action_repeater_mod().
mission_MISSION_OLD_GUARD_REPEATER
const mission_type_id mission_MISSION_OLD_GUARD_REPEATER("MISSION_OLD_GUARD_REPEATER") ("MISSION_OLD_GUARD_REPEATER") static
Referenced by computer_session::action_repeater_mod().
mission_MISSION_OLD_GUARD_REPEATER_BEGIN
const mission_type_id mission_MISSION_OLD_GUARD_REPEATER_BEGIN("MISSION_OLD_GUARD_REPEATER_BEGIN") ("MISSION_OLD_GUARD_REPEATER_BEGIN") static
Referenced by computer_session::action_repeater_mod().
mission_MISSION_REACH_REFUGEE_CENTER
const mission_type_id mission_MISSION_REACH_REFUGEE_CENTER("MISSION_REACH_REFUGEE_CENTER") ("MISSION_REACH_REFUGEE_CENTER") static
Referenced by computer_session::action_emerg_ref_center().
mon_manhack
const mtype_id mon_manhack("mon_manhack") ("mon_manhack") static
Referenced by computer_session::failure_manhacks().
mon_secubot
const mtype_id mon_secubot("mon_secubot") ("mon_secubot") static
Referenced by computer_session::failure_secubots().
oter_type_sewer
const oter_type_str_id oter_type_sewer("sewer") ("sewer") static
Referenced by computer_session::action_map_sewer().
oter_type_subway
const oter_type_str_id oter_type_subway("subway") ("subway") static
Referenced by computer_session::action_map_subway().
skill_computer
const skill_id skill_computer("computer") ("computer") static
Referenced by computer_session::hack_attempt().
species_HUMAN
const species_id species_HUMAN("HUMAN") ("HUMAN") static
Referenced by computer_session::action_blood_anal().
species_ZOMBIE
const species_id species_ZOMBIE("ZOMBIE") ("ZOMBIE") static
Referenced by computer_session::action_blood_anal().
ter_t_concrete
const ter_str_id ter_t_concrete("t_concrete") ("t_concrete") static
Referenced by computer_session::action_extract_rad_source().
ter_t_concrete_wall
const ter_str_id ter_t_concrete_wall("t_concrete_wall") ("t_concrete_wall") static
Referenced by computer_session::action_terminate(), and computer_session::can_activate().
ter_t_door_metal_c
const ter_str_id ter_t_door_metal_c("t_door_metal_c") ("t_door_metal_c") static
Referenced by computer_session::action_lock(), computer_session::action_unlock(), and computer_session::can_activate().
ter_t_door_metal_locked
const ter_str_id ter_t_door_metal_locked("t_door_metal_locked") ("t_door_metal_locked") static
Referenced by computer_session::action_lock(), computer_session::action_open(), computer_session::action_unlock(), and computer_session::can_activate().
ter_t_elevator
const ter_str_id ter_t_elevator("t_elevator") ("t_elevator") static
Referenced by computer_session::action_srcf_seal().
ter_t_elevator_control
const ter_str_id ter_t_elevator_control("t_elevator_control") ("t_elevator_control") static
Referenced by computer_session::action_elevator_on(), and computer_session::action_srcf_elevator().
ter_t_elevator_control_off
const ter_str_id ter_t_elevator_control_off("t_elevator_control_off") ("t_elevator_control_off") static
Referenced by computer_session::action_elevator_on(), and computer_session::action_srcf_elevator().
ter_t_floor
const ter_str_id ter_t_floor("t_floor") ("t_floor") static
Referenced by computer_session::action_open().
ter_t_floor_blue
const ter_str_id ter_t_floor_blue("t_floor_blue") ("t_floor_blue") static
Referenced by computer_session::action_data_anal(), and computer_session::failure_destroy_data().
ter_t_floor_green
const ter_str_id ter_t_floor_green("t_floor_green") ("t_floor_green") static
Referenced by computer_session::action_conveyor().
ter_t_floor_red
const ter_str_id ter_t_floor_red("t_floor_red") ("t_floor_red") static
Referenced by computer_session::action_conveyor().
ter_t_grate
const ter_str_id ter_t_grate("t_grate") ("t_grate") static
Referenced by computer_session::action_srcf_seal().
ter_t_hole
const ter_str_id ter_t_hole("t_hole") ("t_hole") static
Referenced by computer_session::action_miss_launch().
ter_t_metal_floor
const ter_str_id ter_t_metal_floor("t_metal_floor") ("t_metal_floor") static
Referenced by computer_session::action_close_gate(), computer_session::action_miss_launch(), and computer_session::action_open_gate().
ter_t_missile
const ter_str_id ter_t_missile("t_missile") ("t_missile") static
Referenced by computer_session::action_miss_launch().
ter_t_rad_platform
const ter_str_id ter_t_rad_platform("t_rad_platform") ("t_rad_platform") static
Referenced by computer_session::action_conveyor(), computer_session::action_extract_rad_source(), computer_session::action_geiger(), and computer_session::action_irradiator().
ter_t_radio_tower
const ter_str_id ter_t_radio_tower("t_radio_tower") ("t_radio_tower") static
Referenced by computer_session::action_cascade(), and computer_session::action_portal().
ter_t_reinforced_glass
const ter_str_id ter_t_reinforced_glass("t_reinforced_glass") ("t_reinforced_glass") static
Referenced by computer_session::action_release(), computer_session::action_release_bionics(), computer_session::action_terminate(), and computer_session::can_activate().
ter_t_reinforced_glass_shutter
const ter_str_id ter_t_reinforced_glass_shutter("t_reinforced_glass_shutter") ("t_reinforced_glass_shutter") static
Referenced by computer_session::action_shutters().
ter_t_reinforced_glass_shutter_open
const ter_str_id ter_t_reinforced_glass_shutter_open("t_reinforced_glass_shutter_open") ("t_reinforced_glass_shutter_open") static
Referenced by computer_session::action_shutters().
ter_t_sewage
const ter_str_id ter_t_sewage("t_sewage") ("t_sewage") static
Referenced by computer_session::action_irradiator(), computer_session::action_srcf_seal(), and computer_session::failure_pump_leak().
ter_t_sewage_pipe
const ter_str_id ter_t_sewage_pipe("t_sewage_pipe") ("t_sewage_pipe") static
Referenced by computer_session::action_srcf_seal().
ter_t_sewage_pump
const ter_str_id ter_t_sewage_pump("t_sewage_pump") ("t_sewage_pump") static
Referenced by computer_session::action_sample(), computer_session::action_srcf_seal(), computer_session::failure_pump_explode(), and computer_session::failure_pump_leak().
ter_t_thconc_floor
const ter_str_id ter_t_thconc_floor("t_thconc_floor") ("t_thconc_floor") static
Referenced by computer_session::action_release(), and computer_session::action_release_bionics().
ter_t_vat
const ter_str_id ter_t_vat("t_vat") ("t_vat") static
Referenced by computer_session::action_srcf_seal().
ter_t_wall_glass
const ter_str_id ter_t_wall_glass("t_wall_glass") ("t_wall_glass") static
Referenced by computer_session::action_srcf_seal().
ter_t_wall_metal
const ter_str_id ter_t_wall_metal("t_wall_metal") ("t_wall_metal") static
Referenced by computer_session::action_close_gate(), and computer_session::action_open_gate().
ter_t_water_pool
const ter_str_id ter_t_water_pool("t_water_pool") ("t_water_pool") static
Referenced by computer_session::action_irradiator().