Cataclysm DDA: src/condition.cpp File Reference
condition.cpp File Reference
#include "condition.h"
#include <algorithm>
#include <array>
#include <climits>
#include <cmath>
#include <cstddef>
#include <functional>
#include <map>
#include <memory>
#include <optional>
#include <queue>
#include <set>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>
#include "action.h"
#include "avatar.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "coordinates.h"
#include "debug.h"
#include "dialogue.h"
#include "dialogue_helpers.h"
#include "effect.h"
#include "effect_on_condition.h"
#include "enum_conversions.h"
#include "enum_traits.h"
#include "faction.h"
#include "field.h"
#include "flag.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "game.h"
#include "generic_factory.h"
#include "global_vars.h"
#include "item.h"
#include "item_category.h"
#include "item_location.h"
#include "json_error.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "martialarts.h"
#include "math_parser.h"
#include "mission.h"
#include "mtype.h"
#include "mutation.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "point.h"
#include "popup.h"
#include "profession.h"
#include "ranged.h"
#include "recipe_groups.h"
#include "rng.h"
#include "string_formatter.h"
#include "talker.h"
#include "translation.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "vehicle.h"
#include "viewer.h"
#include "vpart_position.h"
#include "weather.h"
#include "widget.h"
#include "worldfactory.h"
Classes
struct anonymous_namespace{condition.cpp}::deferred_math
struct anonymous_namespace{condition.cpp}::condition_parser
Namespaces
anonymous_namespace{condition.cpp}
conditional_fun
conditional_fun::anonymous_namespace{condition.cpp}
Functions
std::queue< deferred_math > & anonymous_namespace{condition.cpp}::get_deferred_math ()
std::shared_ptr< math_exp > & anonymous_namespace{condition.cpp}::defer_math (std::string_view str, bool ass)
std::string get_talk_varname (const JsonObject &jo, std::string_view member, bool check_value, dbl_or_var &default_val)
std::string get_talk_var_basename (const JsonObject &jo, std::string_view member, bool check_value)
dbl_or_var_part get_dbl_or_var_part (const JsonValue &jv, std::string_view member, bool required, double default_val)
dbl_or_var get_dbl_or_var (const JsonObject &jo, std::string_view member, bool required, double default_val)
duration_or_var_part get_duration_or_var_part (const JsonValue &jv, const std::string_view &member, bool required, time_duration default_val)
duration_or_var get_duration_or_var (const JsonObject &jo, const std::string_view &member, bool required, time_duration default_val)
str_or_var get_str_or_var (const JsonValue &jv, std::string_view member, bool required, std::string_view default_val)
str_or_var get_str_or_var (const JsonObject &jo, std::string_view, std::string_view default_val)
static bool json_object_read (const JsonObject &jo, translation &v)
translation_or_var get_translation_or_var (const JsonValue &jv, std::string_view member, bool required, const translation &default_val)
translation_or_var get_translation_or_var (const JsonObject &jo, std::string_view, const translation &default_val)
str_translation_or_var get_str_translation_or_var (const JsonValue &jv, std::string_view member, bool required, std::string_view str_default_val, const translation &translation_default_val)
tripoint_abs_ms get_tripoint_from_var (std::optional< var_info > var, dialogue const &d)
template<class T >
static T abstract_read_var_info_no_translation (std::string &&)
template<>
std::string abstract_read_var_info_no_translation (std::string &&s)
template<class T >
static abstract_var_info< T > abstract_read_var_info (const JsonObject &jo)
var_info read_var_info (const JsonObject &jo)
translation_var_info read_translation_var_info (const JsonObject &jo)
void write_var_value (var_type type, const std::string &name, dialogue *d, const std::string &value, int call_depth)
void write_var_value (var_type type, const std::string &name, dialogue *d, double value)
static bodypart_id get_bp_from_str (const std::string &ctxt)
void read_condition (const JsonObject &jo, const std::string &member_name, conditional_t::func &condition, bool default_val)
void finalize_conditions ()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_any_trait (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_trait (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_visible_trait (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_martial_art (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_flag (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_species (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_bodytype (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_activity (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_activity (const JsonObject &, std::string_view, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_proficiency (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_riding (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_riding (const JsonObject &, std::string_view, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_has_class (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_u_has_mission (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_u_monsters_in_direction (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_u_safe_mode_trigger (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_u_profession (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_strength (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_dexterity (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_intelligence (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_perception (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_part_temp (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_wearing (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_item (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_items (const JsonObject &jo, const std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_item_with_flag (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_item_category (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_bionics (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_any_effect (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_effect (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_need (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_at_om_location (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_near_om_location (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_var (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_expects_vars (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_role_nearby (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_allies (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_allies_global (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_u_has_cash (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_u_are_owed (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_aim_rule (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_engagement_rule (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_cbm_reserve_rule (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_cbm_recharge_rule (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_rule (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_override (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_season (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_mission_goal (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_gender (bool is_male, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_male (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_female (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_alive (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_exists (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_avatar (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_npc (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_character (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_monster (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_item (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_furniture (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_player_see (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_no_assigned_mission ()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_assigned_mission ()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_many_assigned_missions ()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_no_available_mission (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_available_mission (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_many_available_missions (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_mission_complete (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_mission_incomplete (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_mission_failed (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_service (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_available (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_following (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_friend (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_hostile (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_train_skills (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_train_styles (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_train_spells (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_at_safe_space (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_can_stow_weapon (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_can_drop_weapon (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_weapon (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_driving (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_stolen_item (bool)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_day ()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_outside (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_underwater (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_one_in_chance (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_query (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_x_in_y_chance (const JsonObject &jo, const std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_weather (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_with_flag (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_id (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_map_in_city (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_mod_is_loaded (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_faction_trust (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_compare_string (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_get_condition (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_test_eoc (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_ammo ()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_math (const JsonObject &jo, const std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_u_has_camp ()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_pickup_list (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_by_radio ()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_reason ()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_roll_contested (const JsonObject &jo, const std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_u_know_recipe (const JsonObject &jo, std::string_view member)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_mission_has_generic_rewards ()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_worn_with_flag (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_wielded_with_flag (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_wielded_with_weapon_category (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_can_see (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_deaf (bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_on_terrain (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_on_terrain_with_flag (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_in_field (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_move_mode (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_can_see_location (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_using_martial_art (const JsonObject &jo, std::string_view member, bool is_npc)
template<class T >
static std::function< T(const dialogue &)> get_get_str_ (const JsonObject &jo, std::function< T(const std::string &)> ret_func)
template<class T >
static std::function< T(const dialogue &)> get_get_translation_ (const JsonObject &jo, std::function< T(const translation &)> ret_func)
Variables
static const efftype_id effect_currently_busy ("currently_busy")
static const json_character_flag json_flag_MUTATION_THRESHOLD ("MUTATION_THRESHOLD")
std::unordered_map< std::string_view, int(talker::*)() const > const anonymous_namespace{condition.cpp}::f_get_vals
std::unordered_map< std::string_view, void(talker::*)(int)> const anonymous_namespace{condition.cpp}::f_set_vals
static const std::vector< condition_parser > parsers
static const std::vector< condition_parser > parsers_simple
Function Documentation
abstract_read_var_info()
template<class T > static abstract_var_info<T> abstract_read_var_info (const JsonObject & jo) static
Definition at line 402 of file condition.cpp.
 {
     T default_val;
     dbl_or_var empty;
     var_type type;
     std::string name;
     if( jo.has_member( "default_str" ) ) {
         jo.read( "default_str", default_val );
     } else if( jo.has_string( "default" ) ) {
         std::string tmp = std::to_string( to_turns<int>( read_from_json_string<time_duration>
                                           ( jo.get_member( "default" ), time_duration::units ) ) );
         default_val = abstract_read_var_info_no_translation<T>( std::move( tmp ) );
     } else if( jo.has_float( "default" ) ) {
         std::string tmp = std::to_string( jo.get_float( "default" ) );
         default_val = abstract_read_var_info_no_translation<T>( std::move( tmp ) );
     }
     if( jo.has_string( "var_name" ) ) {
         const std::string &type_var = jo.get_string( "type", "" );
         const std::string &var_context = jo.get_string( "context", "" );
         name = "npctalk_var_" + type_var + ( type_var.empty() ? "" : "_" ) + var_context +
                ( var_context.empty() ? "" : "_" )
                + jo.get_string( "var_name" );
     }
     if( jo.has_member( "u_val" ) ) {
         type = var_type::u;
         if( name.empty() ) {
             name = get_talk_varname( jo, "u_val", false, empty );
         }
     } else if( jo.has_member( "npc_val" ) ) {
         type = var_type::npc;
         if( name.empty() ) {
             name = get_talk_varname( jo, "npc_val", false, empty );
         }
     } else if( jo.has_member( "global_val" ) ) {
         type = var_type::global;
         if( name.empty() ) {
             name = get_talk_varname( jo, "global_val", false, empty );
         }
     } else if( jo.has_member( "var_val" ) ) {
         type = var_type::var;
         if( name.empty() ) {
             name = get_talk_varname( jo, "var_val", false, empty );
         }
     } else if( jo.has_member( "context_val" ) ) {
         type = var_type::context;
         if( name.empty() ) {
             name = get_talk_varname( jo, "context_val", false, empty );
         }
     } else if( jo.has_member( "faction_val" ) ) {
         type = var_type::faction;
         if( name.empty() ) {
             name = get_talk_varname( jo, "faction_val", false, empty );
         }
     } else if( jo.has_member( "party_val" ) ) {
         type = var_type::party;
         if( name.empty() ) {
             name = get_talk_varname( jo, "party_val", false, empty );
         }
     } else {
         jo.throw_error( "Invalid variable type." );
     }
     return abstract_var_info<T>( type, name, default_val );
 }
References context, faction, JsonObject::get_float(), JsonObject::get_member(), JsonObject::get_string(), get_talk_varname(), global, JsonObject::has_float(), JsonObject::has_member(), JsonObject::has_string(), om_direction::name(), npc, party, JsonObject::read(), JsonObject::throw_error(), to_string(), u, time_duration::units, and var.
abstract_read_var_info_no_translation() [1/2]
template<class T > static T abstract_read_var_info_no_translation (std::string && s) static
Definition at line 390 of file condition.cpp.
 {
     return std::move( s );
 }
abstract_read_var_info_no_translation() [2/2]
template<> translation abstract_read_var_info_no_translation (std::string && s)
Definition at line 390 of file condition.cpp.
 {
     return std::move( s );
 }
finalize_conditions()
void finalize_conditions ()
Definition at line 572 of file condition.cpp.
 {
     std::queue<deferred_math> &dfr = get_deferred_math();
     while( !dfr.empty() ) {
         deferred_math &math = dfr.front();
         math.exp->parse( math.str, math.assignment );
         dfr.pop();
     }
 }
References anonymous_namespace{condition.cpp}::get_deferred_math().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_bp_from_str()
static bodypart_id get_bp_from_str (const std::string & ctxt) static
Definition at line 534 of file condition.cpp.
 {
     bodypart_id bid = bodypart_str_id::NULL_ID();
     if( !ctxt.empty() ) {
         bid = bodypart_id( ctxt );
         if( !bid.is_valid() ) {
             bid = bodypart_str_id::NULL_ID();
         }
     }
     return bid;
 }
References int_id< T >::is_valid(), and string_id< body_part_type >::NULL_ID().
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_has_any_effect(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_effect(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_part_temp(), and conditional_fun::anonymous_namespace{condition.cpp}::f_has_worn_with_flag().
get_dbl_or_var()
dbl_or_var get_dbl_or_var (const JsonObject & jo, std::string_view member, bool required, double default_val)
Definition at line 206 of file condition.cpp.
 {
     dbl_or_var ret_val;
     if( jo.has_array( member ) ) {
         JsonArray ja = jo.get_array( member );
         ret_val.min = get_dbl_or_var_part( ja.next_value(), member );
         ret_val.max = get_dbl_or_var_part( ja.next_value(), member );
         ret_val.pair = true;
     } else if( required ) {
         ret_val.min = get_dbl_or_var_part( jo.get_member( member ), member, required, default_val );
     } else {
         if( jo.has_member( member ) ) {
             ret_val.min = get_dbl_or_var_part( jo.get_member( member ), member, required, default_val );
         } else {
             ret_val.min.dbl_val = default_val;
         }
     }
     return ret_val;
 }
References JsonObject::get_array(), get_dbl_or_var_part(), JsonObject::get_member(), JsonObject::has_array(), JsonObject::has_member(), member, and JsonArray::next_value().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_faction_trust(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_morale(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_wet(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_attack(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_change_faction_rep(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_consume_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_custom_light_level(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_any_effect(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_dexterity(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_effect(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_faction_trust(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_intelligence(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_items(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_part_temp(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_perception(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_strength(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable_adjust(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_faction_trust(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mod_healthy(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate(), conditional_fun::anonymous_namespace{condition.cpp}::f_near_om_location(), conditional_fun::anonymous_namespace{condition.cpp}::f_need(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_allies(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_allies_global(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_service(), conditional_fun::anonymous_namespace{condition.cpp}::f_one_in_chance(), conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile(), conditional_fun::anonymous_namespace{condition.cpp}::f_roll_contested(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_until(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_switch(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_are_owed(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_monster(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_has_cash(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_spend_cash(), conditional_fun::anonymous_namespace{condition.cpp}::f_x_in_y_chance(), get_talk_varname(), spell_type::load(), enchantment::load(), emit::load_emit(), load_mapgen_function(), and mission_util::parse_mission_om_target().
get_dbl_or_var_part()
dbl_or_var_part get_dbl_or_var_part (const JsonValue & jv, std::string_view member, bool required, double default_val)
Definition at line 183 of file condition.cpp.
 {
     dbl_or_var_part ret_val;
     if( jv.test_float() ) {
         ret_val.dbl_val = jv.get_float();
     } else if( jv.test_object() ) {
         JsonObject jo = jv.get_object();
         if( jo.has_array( "math" ) ) {
             ret_val.math_val.emplace();
             ret_val.math_val->from_json( jo, "math", eoc_math::type_t::ret );
         } else {
             jo.allow_omitted_members();
             ret_val.var_val = read_var_info( jo );
         }
     } else if( required ) {
         jv.throw_error( "No valid value for " + std::string( member ) );
     } else {
         ret_val.dbl_val = default_val;
     }
     return ret_val;
 }
References JsonObject::allow_omitted_members(), JsonValue::get_float(), JsonValue::get_object(), JsonObject::has_array(), member, read_var_info(), eoc_math::ret, JsonValue::test_float(), JsonValue::test_object(), and JsonValue::throw_error().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_weighted_list_eocs(), and get_dbl_or_var().
get_duration_or_var()
duration_or_var get_duration_or_var (const JsonObject & jo, const std::string_view & member, bool required, time_duration default_val)
Definition at line 256 of file condition.cpp.
 {
     duration_or_var ret_val;
     if( jo.has_array( member ) ) {
         JsonArray ja = jo.get_array( member );
         ret_val.min = get_duration_or_var_part( ja.next_value(), member );
         ret_val.max = get_duration_or_var_part( ja.next_value(), member );
         ret_val.pair = true;
     } else if( required ) {
         ret_val.min = get_duration_or_var_part( jo.get_member( member ), member, required, default_val );
     } else {
         if( jo.has_member( member ) ) {
             ret_val.min = get_duration_or_var_part( jo.get_member( member ), member, required, default_val );
         } else {
             ret_val.min.dur_val = default_val;
         }
     }
     return ret_val;
 }
References JsonObject::get_array(), get_duration_or_var_part(), JsonObject::get_member(), JsonObject::has_array(), JsonObject::has_member(), member, and JsonArray::next_value().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_morale(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_alter_timed_events(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_activity(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_custom_light_level(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_place_override(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_turn_cost(), and effect_on_condition::load().
get_duration_or_var_part()
duration_or_var_part get_duration_or_var_part (const JsonValue & jv, const std::string_view & member, bool required, time_duration default_val)
Definition at line 227 of file condition.cpp.
 {
     duration_or_var_part ret_val;
     if( jv.test_string() ) {
         if( jv.get_string() == "infinite" ) {
             ret_val.dur_val = time_duration::from_turns( calendar::INDEFINITELY_LONG );
         } else {
             ret_val.dur_val = read_from_json_string<time_duration>( jv, time_duration::units );
         }
     } else if( jv.test_int() ) {
         ret_val.dur_val = time_duration::from_turns( jv.get_float() );
     } else if( jv.test_object() ) {
         JsonObject jo = jv.get_object();
         if( jo.has_array( "math" ) ) {
             ret_val.math_val.emplace();
             ret_val.math_val->from_json( jo, "math", eoc_math::type_t::ret );
         } else {
             jo.allow_omitted_members();
             ret_val.var_val = read_var_info( jo );
         }
     } else if( required ) {
         jv.throw_error( "No valid value for " + std::string( member ) );
     } else {
         ret_val.dur_val = default_val;
     }
     return ret_val;
 }
References JsonObject::allow_omitted_members(), time_duration::from_turns(), JsonValue::get_float(), JsonValue::get_object(), JsonValue::get_string(), JsonObject::has_array(), calendar::INDEFINITELY_LONG, member, read_var_info(), eoc_math::ret, JsonValue::test_int(), JsonValue::test_object(), JsonValue::test_string(), JsonValue::throw_error(), and time_duration::units.
Referenced by get_duration_or_var().
get_get_str_()
template<class T > static std::function<T(const dialogue &)> get_get_str_ (const JsonObject & jo, std::function< T(const std::string &)> ret_func) static
Definition at line 1918 of file condition.cpp.
 {
     if( jo.get_string( "mutator" ) == "mon_faction" ) {
         str_or_var mtypeid = get_str_or_var( jo.get_member( "mtype_id" ), "mtype_id" );
         return [mtypeid, ret_func]( const dialogue & d ) {
             return ret_func( ( static_cast<mtype_id>( mtypeid.evaluate( d ) ) )->default_faction.str() );
         };
     } else if( jo.get_string( "mutator" ) == "game_option" ) {
         str_or_var option = get_str_or_var( jo.get_member( "option" ), "option" );
         return [option, ret_func]( const dialogue & d ) {
             return ret_func( get_option<std::string>( option.evaluate( d ) ) );
         };
     } else if( jo.get_string( "mutator" ) == "valid_technique" ) {
         std::vector<str_or_var> blacklist;
         if( jo.has_array( "blacklist" ) ) {
             for( const JsonValue &jv : jo.get_array( "blacklist" ) ) {
                 blacklist.push_back( get_str_or_var( jv, "blacklist" ) );
             }
         }
         bool crit = jo.get_bool( "crit", false );
         bool dodge_counter = jo.get_bool( "dodge_counter", false );
         bool block_counter = jo.get_bool( "block_counter", false );
         return [blacklist, crit, dodge_counter, block_counter, ret_func]( const dialogue & d ) {
             std::vector<matec_id> bl;
             bl.reserve( blacklist.size() );
             for( const str_or_var &sv : blacklist ) {
                 bl.emplace_back( sv.evaluate( d ) );
             }
             return ret_func( d.actor( false )->get_random_technique( *d.actor( true )->get_creature(),
                              crit, dodge_counter, block_counter, bl ).str() );
         };
     } else if( jo.get_string( "mutator" ) == "loc_relative_u" ) {
         str_or_var target = get_str_or_var( jo.get_member( "target" ), "target" );
         return [target, ret_func]( const dialogue & d ) {
             tripoint_abs_ms char_pos = get_map().getglobal( d.actor( false )->pos() );
             tripoint_abs_ms target_pos = char_pos + tripoint::from_string( target.evaluate( d ) );
             return ret_func( target_pos.to_string() );
         };
     } else if( jo.get_string( "mutator" ) == "topic_item" ) {
         return [ret_func]( const dialogue & d ) {
             return ret_func( d.cur_item.str() );
         };
     }
     return nullptr;
 }
References abstract_str_or_var< T >::evaluate(), tripoint::from_string(), JsonObject::get_array(), JsonObject::get_bool(), get_map(), JsonObject::get_member(), get_str_or_var(), JsonObject::get_string(), map::getglobal(), JsonObject::has_array(), and coords::coord_point_base< Point >::to_string().
get_get_translation_()
template<class T > static std::function<T(const dialogue &)> get_get_translation_ (const JsonObject & jo, std::function< T(const translation &)> ret_func) static
Definition at line 1969 of file condition.cpp.
 {
     if( jo.get_string( "mutator" ) == "ma_technique_description" ) {
         str_or_var ma = get_str_or_var( jo.get_member( "matec_id" ), "matec_id" );
         return [ma, ret_func]( const dialogue & d ) {
             return ret_func( matec_id( ma.evaluate( d ) )->description );
         };
     } else if( jo.get_string( "mutator" ) == "ma_technique_name" ) {
         str_or_var ma = get_str_or_var( jo.get_member( "matec_id" ), "matec_id" );
         return [ma, ret_func]( const dialogue & d ) {
             return ret_func( matec_id( ma.evaluate( d ) )->name );
         };
     }
     return nullptr;
 }
References ma_technique::description, abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), JsonObject::get_string(), and ma_technique::name.
get_str_or_var() [1/2]
str_or_var get_str_or_var (const JsonObject & jo, std::string_view member, std::string_view default_val)
Definition at line 294 of file condition.cpp.
 {
     str_or_var ret_val;
     if( jo.has_member( "mutator" ) ) {
         // if we have a mutator then process that here.
         ret_val.function = conditional_t::get_get_string( jo );
     } else {
         ret_val.var_val = read_var_info( jo );
         ret_val.default_val = default_val;
     }
     return ret_val;
 }
References conditional_t::get_get_string(), JsonObject::has_member(), and read_var_info().
get_str_or_var() [2/2]
str_or_var get_str_or_var (const JsonValue & jv, std::string_view member, bool required, std::string_view default_val)
Definition at line 278 of file condition.cpp.
 {
     str_or_var ret_val;
     if( jv.test_string() ) {
         ret_val.str_val = jv.get_string();
     } else if( jv.test_object() ) {
         ret_val = get_str_or_var( jv.get_object(), member, default_val );
     } else if( required ) {
         jv.throw_error( "No valid value for " + std::string( member ) );
     } else {
         ret_val.str_val = default_val;
     }
     return ret_val;
 }
References JsonValue::get_object(), JsonValue::get_string(), member, JsonValue::test_object(), JsonValue::test_string(), and JsonValue::throw_error().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate_trait(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_bionic(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_morale(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_trait(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_alter_timed_events(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_activity(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_mission(), conditional_fun::anonymous_namespace{condition.cpp}::f_at_om_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_attack(), conditional_fun::anonymous_namespace{condition.cpp}::f_bodytype(), conditional_fun::anonymous_namespace{condition.cpp}::f_can_see_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_clear_npc_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_companion_mission(), conditional_fun::anonymous_namespace{condition.cpp}::f_compare_string(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_consume_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_custom_light_level(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_deactivate_trait(), conditional_fun::anonymous_namespace{condition.cpp}::f_expects_vars(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_finish_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_forget_martial_art(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_forget_recipe(), conditional_fun::anonymous_namespace{condition.cpp}::f_get_condition(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_achievment(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_any_effect(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_any_trait(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_bionics(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_effect(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_item(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_item_category(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_item_with_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_items(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_martial_art(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_move_mode(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_proficiency(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_species(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_trait(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_visible_trait(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_wielded_with_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_wielded_with_weapon_category(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_worn_with_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_in_field(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_on_terrain(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_on_terrain_with_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_season(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_wearing(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_weather(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_learn_martial_art(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_learn_recipe(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_bionic(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_morale(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_in_city(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_id(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_with_flag(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), conditional_fun::anonymous_namespace{condition.cpp}::f_mission_goal(), conditional_fun::anonymous_namespace{condition.cpp}::f_mod_is_loaded(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate_category(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate_towards(), conditional_fun::anonymous_namespace{condition.cpp}::f_near_om_location(), conditional_fun::anonymous_namespace{condition.cpp}::f_need(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_aim_rule(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_aim_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_cbm_recharge_rule(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_cbm_recharge_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_cbm_reserve_rule(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_cbm_reserve_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_change_class(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_change_faction(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_engagement_rule(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_engagement_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_first_topic(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_has_class(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_override(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_role_nearby(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_place_override(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_active_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_item_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_trait(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_inv_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_condition(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_flag(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_npc_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), conditional_fun::anonymous_namespace{condition.cpp}::f_test_eoc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_toggle_npc_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_line(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_trigger_event(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_monster(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_has_mission(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_know_recipe(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_monsters_in_direction(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_profession(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_safe_mode_trigger(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_unset_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_using_martial_art(), get_get_str_(), get_get_translation_(), get_str_translation_or_var(), emit::load_emit(), load_eoc_vector_id_and_var(), and mission_util::parse_mission_om_target().
get_str_translation_or_var()
str_translation_or_var get_str_translation_or_var (const JsonValue & jv, std::string_view member, bool required, std::string_view str_default_val, const translation & translation_default_val)
Definition at line 356 of file condition.cpp.
 {
     str_translation_or_var ret_val;
     if( jv.test_object() ) {
         const JsonObject &jo = jv.get_object();
         if( jo.get_bool( "i18n", false ) ) {
             ret_val.val = get_translation_or_var( jo, member, translation_default_val );
         } else {
             ret_val.val = get_str_or_var( jo, member, str_default_val );
         }
     } else {
         ret_val.val = get_str_or_var( jv, member, required, str_default_val );
     }
     return ret_val;
 }
References JsonObject::get_bool(), JsonValue::get_object(), get_str_or_var(), get_translation_or_var(), member, JsonValue::test_object(), and ret_val< T >::val.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with().
get_talk_var_basename()
std::string get_talk_var_basename (const JsonObject & jo, std::string_view member, bool check_value)
Definition at line 172 of file condition.cpp.
 {
     if( check_value && !( jo.has_string( "value" ) ||
                           jo.has_array( "possible_values" ) ) ) {
         jo.throw_error( "invalid " + std::string( member ) + " condition in " + jo.str() );
     }
     const std::string &var_basename = jo.get_string( std::string( member ) );
     return var_basename;
 }
References JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_string(), member, JsonObject::str(), and JsonObject::throw_error().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_var().
get_talk_varname()
std::string get_talk_varname (const JsonObject & jo, std::string_view member, bool check_value, dbl_or_var & default_val)
Definition at line 157 of file condition.cpp.
 {
     if( check_value && !( jo.has_string( "value" ) ||
                           jo.has_array( "possible_values" ) ) ) {
         jo.throw_error( "invalid " + std::string( member ) + " condition in " + jo.str() );
     }
     const std::string &var_basename = jo.get_string( std::string( member ) );
     const std::string &type_var = jo.get_string( "type", "" );
     const std::string &var_context = jo.get_string( "context", "" );
     default_val = get_dbl_or_var( jo, "default", false );
     return "npctalk_var" + ( type_var.empty() ? "" : "_" + type_var ) + ( var_context.empty() ? "" : "_"
             + var_context ) + "_" + var_basename;
 }
References get_dbl_or_var(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_string(), member, JsonObject::str(), and JsonObject::throw_error().
Referenced by abstract_read_var_info(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_var(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_var(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_var().
get_translation_or_var() [1/2]
translation_or_var get_translation_or_var (const JsonObject & jo, std::string_view member, const translation & default_val)
Definition at line 337 of file condition.cpp.
 {
     translation_or_var ret_val;
     translation str_val;
     if( json_object_read( jo, str_val ) ) {
         ret_val.str_val = str_val;
     } else {
         if( jo.has_member( "mutator" ) ) {
             // if we have a mutator then process that here.
             ret_val.function = conditional_t::get_get_translation( jo );
         } else {
             ret_val.var_val = read_translation_var_info( jo );
             ret_val.default_val = default_val;
         }
     }
     return ret_val;
 }
References conditional_t::get_get_translation(), JsonObject::has_member(), json_object_read(), and read_translation_var_info().
get_translation_or_var() [2/2]
translation_or_var get_translation_or_var (const JsonValue & jv, std::string_view member, bool required, const translation & default_val)
Definition at line 318 of file condition.cpp.
 {
     translation_or_var ret_val;
     if( jv.test_object() ) {
         ret_val = get_translation_or_var( jv.get_object(), member, default_val );
     } else {
         translation str_val;
         if( jv.read( str_val ) ) {
             ret_val.str_val = str_val;
         } else if( required ) {
             jv.throw_error( "No valid value for " + std::string( member ) );
         } else {
             ret_val.str_val = default_val;
         }
     }
     return ret_val;
 }
References JsonValue::get_object(), member, JsonValue::read(), JsonValue::test_object(), and JsonValue::throw_error().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_place_override(), conditional_fun::anonymous_namespace{condition.cpp}::f_query(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_inv_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_monster(), and get_str_translation_or_var().
get_tripoint_from_var()
tripoint_abs_ms get_tripoint_from_var (std::optional< var_info > var, dialogue const & d)
Definition at line 374 of file condition.cpp.
 {
     tripoint_abs_ms target_pos = get_map().getglobal( d.actor( false )->pos() );
     if( var.has_value() ) {
         std::string value = read_var_value( var.value(), d );
         if( !value.empty() ) {
             target_pos = tripoint_abs_ms( tripoint::from_string( value ) );
         }
     }
     return target_pos;
 }
References dialogue::actor(), tripoint::from_string(), get_map(), map::getglobal(), talker::pos(), and read_var_value().
Referenced by anonymous_namespace{math_parser_diag.cpp}::_characters_nearby_eval(), anonymous_namespace{math_parser_diag.cpp}::_monsters_nearby_eval(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_guard_pos(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable_adjust(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_id(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_with_flag(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_line(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), anonymous_namespace{math_parser_diag.cpp}::field_strength_eval(), and find_or_create_om_terrain().
json_object_read()
static bool json_object_read (const JsonObject & jo, translation & v) static
Definition at line 308 of file condition.cpp.
 {
     try {
         v.deserialize( jo );
         return true;
     } catch( const JsonError & ) {
         return false;
     }
 }
References translation::deserialize().
Referenced by get_translation_or_var().
read_condition()
void read_condition (const JsonObject & jo, const std::string & member_name, conditional_t::func & condition, bool default_val)
Definition at line 546 of file condition.cpp.
 {
     const auto null_function = [default_val]( dialogue const & ) {
         return default_val;
     };
     if( !jo.has_member( member_name ) ) {
         condition = null_function;
     } else if( jo.has_string( member_name ) ) {
         const std::string type = jo.get_string( member_name );
         conditional_t sub_condition( type );
         condition = [sub_condition]( dialogue & d ) {
             return sub_condition( d );
         };
     } else if( jo.has_object( member_name ) ) {
         JsonObject con_obj = jo.get_object( member_name );
         conditional_t sub_condition( con_obj );
         condition = [sub_condition]( dialogue & d ) {
             return sub_condition( d );
         };
     } else {
         jo.throw_error_at( member_name, "invalid condition syntax" );
     }
 }
References JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), and JsonObject::throw_error_at().
Referenced by icg_entry_reader::_part_get_next(), shopkeeper_item_group::deserialize(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_if(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_until(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_condition(), json_dynamic_line_effect::json_dynamic_line_effect(), widget_clause::load(), ma_technique::load(), mission_type::load(), effect_on_condition::load(), weather_type::load(), enchantment::load(), reflex_activation_data::load(), json_talk_response::load_condition(), leap_actor::load_internal(), mon_spellcasting_actor::load_internal(), melee_actor::load_internal(), gun_actor::load_internal(), talk_response::talk_response(), and talk_trial::talk_trial().
read_translation_var_info()
translation_var_info read_translation_var_info (const JsonObject & jo)
Definition at line 472 of file condition.cpp.
 {
     return abstract_read_var_info<translation>( jo );
 }
Referenced by get_translation_or_var().
read_var_info()
var_info read_var_info (const JsonObject & jo)
Definition at line 467 of file condition.cpp.
 {
     return abstract_read_var_info<std::string>( jo );
 }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_guard_pos(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable_adjust(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_id(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_with_flag(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_talker(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_line(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), get_dbl_or_var_part(), get_duration_or_var_part(), get_str_or_var(), and mission_util::parse_mission_om_target().
write_var_value() [1/2]
void write_var_value (var_type type, const std::string & name, dialogue * d, const std::string & value, int call_depth)
Definition at line 477 of file condition.cpp.
 {
     global_variables &globvars = get_globals();
     std::string ret;
     var_info vinfo( var_type::global, "" );
     switch( type ) {
         case var_type::global:
             globvars.set_global_value( name, value );
             break;
         case var_type::var:
             ret = d->get_value( name );
             vinfo = process_variable( ret );
             if( call_depth > 1000 ) {
                 debugmsg( "Possible infinite loop detected: var_val points to itself or forms a cycle.  %s->%s %s",
                           name, vinfo.name, d->get_callstack() );
             } else {
                 write_var_value( vinfo.type, vinfo.name, d, value,
                                  call_depth + 1 );
             }
             break;
         case var_type::u:
             if( d->has_alpha ) {
                 d->actor( false )->set_value( name, value );
             } else {
                 debugmsg( "Tried to use an invalid alpha talker.  %s", d->get_callstack() );
             }
             break;
         case var_type::npc:
             if( d->has_beta ) {
                 d->actor( true )->set_value( name, value );
             } else {
                 debugmsg( "Tried to use an invalid beta talker.  %s", d->get_callstack() );
             }
             break;
         case var_type::faction:
             debugmsg( "Not implemented yet." );
             break;
         case var_type::party:
             debugmsg( "Not implemented yet." );
             break;
         case var_type::context:
             d->set_value( name, value );
             break;
         default:
             debugmsg( "Invalid type." );
             break;
     }
 }
References dialogue::actor(), context, debugmsg, faction, dialogue::get_callstack(), get_globals(), dialogue::get_value(), global, dialogue::has_alpha, dialogue::has_beta, abstract_var_info< T >::name, om_direction::name(), npc, party, process_variable(), cata::hash64_detail::ret, global_variables::set_global_value(), talker::set_value(), dialogue::set_value(), abstract_var_info< T >::type, u, and var.
Referenced by Character::activate_bionic(), math_exp::math_exp_impl::assign(), jmath_func::eval(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable_adjust(), conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_talker(), widget_clause::meets_condition(), effect_on_conditons_actor::use(), and write_var_value().
write_var_value() [2/2]
void write_var_value (var_type type, const std::string & name, dialogue * d, double value)
Definition at line 527 of file condition.cpp.
 {
     // NOLINTNEXTLINE(cata-translate-string-literal)
     write_var_value( type, name, d, string_format( "%g", value ) );
 }
References om_direction::name(), string_format(), and write_var_value().
Variable Documentation
effect_currently_busy
const efftype_id effect_currently_busy("currently_busy") ("currently_busy") static
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_npc_available(), and conditional_fun::anonymous_namespace{condition.cpp}::f_npc_service().
json_flag_MUTATION_THRESHOLD
const json_character_flag json_flag_MUTATION_THRESHOLD("MUTATION_THRESHOLD") ("MUTATION_THRESHOLD") static
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_has_flag().
parsers
const std::vector<condition_parser> parsers static
Definition at line 2366 of file condition.cpp.
Referenced by dialogue_data::complex_conds(), and conditional_t::conditional_t().
parsers_simple
const std::vector<condition_parser> parsers_simple static
Definition at line 2449 of file condition.cpp.
Referenced by conditional_t::conditional_t(), and dialogue_data::simple_string_conds().