Cataclysm DDA: src/construction.cpp File Reference
construction.cpp File Reference
#include "construction.h"
#include <algorithm>
#include <array>
#include <cstddef>
#include <iterator>
#include <memory>
#include <numeric>
#include <utility>
#include "action.h"
#include "activity_type.h"
#include "avatar.h"
#include "build_reqs.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "colony.h"
#include "color.h"
#include "construction_category.h"
#include "construction_group.h"
#include "coordinates.h"
#include "creature.h"
#include "cursesdef.h"
#include "debug.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "game.h"
#include "game_constants.h"
#include "input.h"
#include "input_context.h"
#include "inventory.h"
#include "item.h"
#include "item_group.h"
#include "item_stack.h"
#include "iteminfo_query.h"
#include "iuse.h"
#include "json_error.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "memory_fast.h"
#include "messages.h"
#include "morale_types.h"
#include "mtype.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "player_activity.h"
#include "point.h"
#include "requirements.h"
#include "rng.h"
#include "skill.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translation_cache.h"
#include "translations.h"
#include "trap.h"
#include "ui.h"
#include "ui_manager.h"
#include "uistate.h"
#include "units.h"
#include "veh_appliance.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vpart_position.h"
Namespaces
construct
Functions
static const std::string flag_INITIAL_PART ("INITIAL_PART")
static const std::string flag_WIRING ("WIRING")
static bool construct::check_nothing (const tripoint_bub_ms &)
static bool construct::check_channel (const tripoint_bub_ms &)
static bool construct::check_empty_lite (const tripoint_bub_ms &)
static bool construct::check_empty (const tripoint_bub_ms &)
static bool construct::check_support (const tripoint_bub_ms &)
static bool construct::check_support_below (const tripoint_bub_ms &)
static bool construct::check_single_support (const tripoint_bub_ms &p)
static bool construct::check_stable (const tripoint_bub_ms &)
static bool construct::check_nofloor_above (const tripoint_bub_ms &)
static bool construct::check_deconstruct (const tripoint_bub_ms &)
static bool construct::check_up_OK (const tripoint_bub_ms &)
static bool construct::check_down_OK (const tripoint_bub_ms &)
static bool construct::check_no_trap (const tripoint_bub_ms &)
static bool construct::check_ramp_high (const tripoint_bub_ms &)
static bool construct::check_no_wiring (const tripoint_bub_ms &)
static bool construct::check_matching_down_above (const tripoint_bub_ms &p)
static void construct::done_nothing (const tripoint_bub_ms &, Character &)
static void construct::done_trunk_plank (const tripoint_bub_ms &, Character &)
static void construct::done_grave (const tripoint_bub_ms &, Character &)
static void construct::done_vehicle (const tripoint_bub_ms &, Character &)
static void construct::done_appliance (const tripoint_bub_ms &, Character &)
static void construct::done_wiring (const tripoint_bub_ms &, Character &)
static void construct::done_deconstruct (const tripoint_bub_ms &, Character &)
static void construct::done_digormine_stair (const tripoint_bub_ms &, bool, Character &)
static void construct::done_dig_grave (const tripoint_bub_ms &p, Character &)
static void construct::done_dig_grave_nospawn (const tripoint_bub_ms &p, Character &)
static void construct::done_dig_stair (const tripoint_bub_ms &, Character &)
static void construct::done_mine_downstair (const tripoint_bub_ms &, Character &)
static void construct::done_mine_upstair (const tripoint_bub_ms &, Character &)
static void construct::done_wood_stairs (const tripoint_bub_ms &, Character &)
static void construct::done_window_curtains (const tripoint_bub_ms &, Character &)
static void construct::done_extract_maybe_revert_to_dirt (const tripoint_bub_ms &, Character &)
static void construct::done_mark_firewood (const tripoint_bub_ms &, Character &)
static void construct::done_mark_practice_target (const tripoint_bub_ms &, Character &)
static void construct::done_ramp_low (const tripoint_bub_ms &, Character &)
static void construct::done_ramp_high (const tripoint_bub_ms &, Character &)
static void construct::add_matching_down_above (const tripoint_bub_ms &p, Character &)
static void construct::remove_above (const tripoint_bub_ms &p, Character &)
static void construct::add_roof (const tripoint_bub_ms &p, Character &)
static void construct::do_turn_shovel (const tripoint_bub_ms &, Character &)
static void construct::do_turn_exhume (const tripoint_bub_ms &, Character &)
static void construct::failure_standard (const tripoint_bub_ms &)
static void construct::failure_deconstruct (const tripoint_bub_ms &)
static bool can_construct (const construction &con)
static std::vector< construction * > player_can_build_valid_constructions (Character &you, const read_only_visitable &inv, const construction_group_str_id &group)
static bool player_can_build (Character &you, const read_only_visitable &inv, const construction_group_str_id &group)
static bool player_can_see_to_build (Character &you, const construction_group_str_id &group)
static bool has_pre_terrain (const construction &con, const tripoint_bub_ms &p)
static bool has_pre_terrain (const construction &con)
void standardize_construction_times (const int time)
Set all constructions to take the specified time.
std::vector< construction * > constructions_by_group (const construction_group_str_id &group)
std::vector< construction * > constructions_by_filter (std::function< bool(construction const &)> const &filter)
static void load_available_constructions (std::vector< construction_group_str_id > &available, std::map< construction_category_id, std::vector< construction_group_str_id >> &cat_available, bool hide_unconstructable)
static void draw_grid (const catacurses::window &w, const int list_width)
static nc_color construction_color (const construction_group_str_id &group, bool highlight)
const std::vector< construction > & get_constructions ()
static std::string furniture_qualities_string (const furn_id &fid)
construction_id construction_menu (const bool blueprint)
bool player_can_build (Character &you, const read_only_visitable &inv, const construction &con, const bool can_construct_skip)
bool can_construct_furn_ter (const construction &con, furn_id const &f, ter_id const &t)
bool can_construct (const construction &con, const tripoint_bub_ms &p)
void place_construction (std::vector< construction_group_str_id > const &groups)
void complete_construction (Character *you)
static vpart_id vpart_from_item (const itype_id &item_id)
static void unroll_digging (const int numer_of_2x4s)
template<typename T >
void assign_or_debugmsg (T &dest, const std::string &fun_id, const std::map< std::string, T > &possible)
void load_construction (const JsonObject &jo)
void reset_constructions ()
void check_constructions ()
void finalize_constructions ()
build_reqs get_build_reqs_for_furn_ter_ids (const std::pair< std::map< ter_id, int >, std::map< furn_id, int >> &changed_ids, ter_id const &base_ter)
Variables
static const activity_id ACT_BUILD ("ACT_BUILD")
static const activity_id ACT_MULTIPLE_CONSTRUCTION ("ACT_MULTIPLE_CONSTRUCTION")
static const construction_category_id construction_category_ALL ("ALL")
static const construction_category_id construction_category_APPLIANCE ("APPLIANCE")
static const construction_category_id construction_category_FILTER ("FILTER")
static const construction_category_id construction_category_REPAIR ("REPAIR")
static const construction_str_id construction_constr_veh ("constr_veh")
static const flag_id json_flag_FILTHY ("FILTHY")
static const flag_id json_flag_PIT ("PIT")
static const furn_str_id furn_f_coffin_c ("f_coffin_c")
static const furn_str_id furn_f_coffin_o ("f_coffin_o")
static const item_group_id Item_spawn_data_allclothes ("allclothes")
static const item_group_id Item_spawn_data_grave ("grave")
static const item_group_id Item_spawn_data_jewelry_front ("jewelry_front")
static const itype_id itype_2x4 ("2x4")
static const itype_id itype_bone_human ("bone_human")
static const itype_id itype_nail ("nail")
static const itype_id itype_sheet ("sheet")
static const itype_id itype_stick ("stick")
static const itype_id itype_string_36 ("string_36")
static const itype_id itype_wall_wiring ("wall_wiring")
static const mtype_id mon_skeleton ("mon_skeleton")
static const mtype_id mon_zombie ("mon_zombie")
static const mtype_id mon_zombie_crawler ("mon_zombie_crawler")
static const mtype_id mon_zombie_fat ("mon_zombie_fat")
static const mtype_id mon_zombie_rot ("mon_zombie_rot")
static const quality_id qual_CUT ("CUT")
static const skill_id skill_fabrication ("fabrication")
static const ter_str_id ter_t_clay ("t_clay")
static const ter_str_id ter_t_dirt ("t_dirt")
static const ter_str_id ter_t_hole ("t_hole")
static const ter_str_id ter_t_ladder_up ("t_ladder_up")
static const ter_str_id ter_t_lava ("t_lava")
static const ter_str_id ter_t_open_air ("t_open_air")
static const ter_str_id ter_t_pit ("t_pit")
static const ter_str_id ter_t_ramp_down_high ("t_ramp_down_high")
static const ter_str_id ter_t_ramp_down_low ("t_ramp_down_low")
static const ter_str_id ter_t_rock_floor ("t_rock_floor")
static const ter_str_id ter_t_sand ("t_sand")
static const ter_str_id ter_t_stairs_down ("t_stairs_down")
static const ter_str_id ter_t_stairs_up ("t_stairs_up")
static const ter_str_id ter_t_wood_stairs_down ("t_wood_stairs_down")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
static const trait_id trait_EATDEAD ("EATDEAD")
static const trait_id trait_NUMB ("NUMB")
static const trait_id trait_PAINRESIST_TROGLO ("PAINRESIST_TROGLO")
static const trait_id trait_PSYCHOPATH ("PSYCHOPATH")
static const trait_id trait_SAPROVORE ("SAPROVORE")
static const trait_id trait_SPIRITUAL ("SPIRITUAL")
static const trait_id trait_STOCKY_TROGLO ("STOCKY_TROGLO")
static const trap_str_id tr_firewood_source ("tr_firewood_source")
static const trap_str_id tr_practice_target ("tr_practice_target")
static const vpart_id vpart_frame ("frame")
static const vproto_id vehicle_prototype_none ("none")
static bool finalized = false
static std::vector< construction > constructions
static std::map< construction_str_id, construction_id > construction_id_map
static const deferred_color color_title = def_c_light_red
static const deferred_color color_data = def_c_cyan
static const construction null_construction {}
Function Documentation
assign_or_debugmsg()
template<typename T > void assign_or_debugmsg (T & dest, const std::string & fun_id, const std::map< std::string, T > & possible)
Definition at line 1893 of file construction.cpp.
 {
     const auto iter = possible.find( fun_id );
     if( iter != possible.end() ) {
         dest = iter->second;
     } else {
         dest = possible.find( "" )->second;
         const std::string list_available = enumerate_as_string( possible.begin(), possible.end(),
         []( const std::pair<std::string, T> &pr ) {
             return pr.first;
         } );
         debugmsg( "Unknown function: %s, available values are %s", fun_id.c_str(), list_available );
     }
 }
References debugmsg, enumerate_as_string(), and possible.
Referenced by load_construction().
can_construct() [1/2]
bool can_construct (const construction & con) static
Definition at line 985 of file construction.cpp.
 {
     tripoint_bub_ms avatar_pos = get_player_character().pos_bub();
     for( const tripoint_bub_ms &p : get_map().points_in_radius( avatar_pos, 1 ) ) {
         if( p != avatar_pos && can_construct( con, p ) ) {
             return true;
         }
     }
     return false;
 }
References get_map(), get_player_character(), points_in_radius(), and Creature::pos_bub().
Referenced by anonymous_namespace{activity_item_handling.cpp}::_can_construct(), construction_menu(), find_base_construction(), place_construction(), and player_can_build().
can_construct() [2/2]
bool can_construct (const construction & con, const tripoint_bub_ms & p)
Definition at line 957 of file construction.cpp.
 {
     const map &here = get_map();
     const furn_id f = here.furn( p );
     const ter_id t = here.ter( p );
     if( con.pre_specials.size() > 1 ) { // pre-functions
         for( const auto &special : con.pre_specials ) {
             if( !special( p ) ) {
                 return false;
             }
         }
     } else if( !con.pre_special( p ) ) { // pre-function
         return false;
     }
     if( !has_pre_terrain( con, p ) || // terrain type
         !can_construct_furn_ter( con, f, t ) ) { // flags
         return false;
     }
     if( !con.post_terrain.empty() ) { // make sure the construction would actually do something
         if( con.post_is_furniture ) {
             return f != furn_id( con.post_terrain );
         } else {
             return t != ter_id( con.post_terrain );
         }
     }
     return true;
 }
References can_construct_furn_ter(), map::furn(), get_map(), has_pre_terrain(), construction::post_is_furniture, construction::post_terrain, construction::pre_special, construction::pre_specials, and map::ter().
can_construct_furn_ter()
bool can_construct_furn_ter (const construction & con, furn_id const & f, ter_id const & t)
Definition at line 948 of file construction.cpp.
 {
     return std::all_of( con.pre_flags.begin(), con.pre_flags.end(), [&f, &t]( auto const & flag ) {
         const bool use_ter = flag.second || f == furn_str_id::NULL_ID();
         return ( use_ter || f->has_flag( flag.first ) ) &&
                ( !use_ter || t->has_flag( flag.first ) );
     } );
 }
References construction::pre_flags.
Referenced by anonymous_namespace{activity_item_handling.cpp}::_find_prereq(), and can_construct().
check_constructions()
void check_constructions ()
Definition at line 2107 of file construction.cpp.
 {
     for( size_t i = 0; i < constructions.size(); i++ ) {
         const construction &c = constructions[ i ];
         const std::string display_name = "construction " + c.str_id.str();
         for( const auto &pr : c.required_skills ) {
             if( !pr.first.is_valid() ) {
                 debugmsg( "Unknown skill %s in %s", pr.first.c_str(), display_name );
             }
         }
         if( !c.requirements.is_valid() ) {
             debugmsg( "%s has missing requirement data %s",
                       display_name, c.requirements.c_str() );
         }
         if( !c.pre_terrain.empty() ) {
             if( c.pre_is_furniture ) {
                 if( !furn_str_id( c.pre_terrain ).is_valid() ) {
                     debugmsg( "Unknown pre_terrain (furniture) %s in %s", c.pre_terrain, display_name );
                 }
             } else if( !ter_str_id( c.pre_terrain ).is_valid() ) {
                 debugmsg( "Unknown pre_terrain (terrain) %s in %s", c.pre_terrain, display_name );
             }
         }
         if( !c.post_terrain.empty() ) {
             if( c.post_is_furniture ) {
                 if( !furn_str_id( c.post_terrain ).is_valid() ) {
                     debugmsg( "Unknown post_terrain (furniture) %s in %s", c.post_terrain, display_name );
                 }
             } else if( !ter_str_id( c.post_terrain ).is_valid() ) {
                 debugmsg( "Unknown post_terrain (terrain) %s in %s", c.post_terrain, display_name );
             }
         }
         if( c.id != construction_id( i ) ) {
             debugmsg( "%s has id %u, but should have %u",
                       display_name, c.id.to_i(), i );
         }
         if( construction_id_map.find( c.str_id ) == construction_id_map.end() ) {
             debugmsg( "%s is an invalid string id",
                       display_name );
         } else if( construction_id_map[c.str_id] != construction_id( i ) ) {
             debugmsg( "%s points to int id %u, but should point to %u",
                       display_name, construction_id_map[c.str_id].to_i(), i );
         }
     }
 }
References c, construction_id_map, constructions, debugmsg, and string_id< T >::is_valid().
Referenced by DynamicDataLoader::check_consistency().
complete_construction()
void complete_construction (Character * you)
Definition at line 1076 of file construction.cpp.
 {
     if( !finalized ) {
         debugmsg( "complete_construction called before finalization" );
         return;
     }
     map &here = get_map();
     const tripoint_bub_ms terp = here.bub_from_abs( you->activity.placement );
     partial_con *pc = here.partial_con_at( terp );
     if( !pc ) {
         debugmsg( "No partial construction found at activity placement in complete_construction()" );
         if( you->is_npc() ) {
             npc *guy = dynamic_cast<npc *>( you );
             guy->current_activity_id = activity_id::NULL_ID();
             guy->revert_after_activity();
             guy->set_moves( 0 );
         }
         return;
     }
     const construction &built = pc->id.obj();
     you->activity.str_values.emplace_back( built.str_id );
     const auto award_xp = [&]( Character & practicer ) {
         for( const auto &pr : built.required_skills ) {
             practicer.practice( pr.first, static_cast<int>( ( 10 + 15 * pr.second ) *
                                 ( 1 + built.time / 180000.0 ) ),
                                 static_cast<int>( pr.second * 1.25 ) );
         }
     };
     award_xp( *you );
     // Other friendly Characters gain exp from assisting or watching...
     // TODO: Characters watching other Characters do stuff and learning from it
     if( you->is_avatar() ) {
         for( Character *elem : get_avatar().get_crafting_helpers() ) {
             if( elem->meets_skill_requirements( built ) ) {
                 add_msg( m_info, _( "%s assists you with the work" ), elem->get_name() );
             } else {
                 //NPC near you isn't skilled enough to help
                 add_msg( m_info, _( "%s watches you work" ), elem->get_name() );
             }
             award_xp( *elem );
         }
     }
     // partial_con contains components for vehicle and appliance construction
     // it's removal is handled in done_appliance() / done_vehicle
     if( pc->id->category != construction_category_APPLIANCE &&
         pc->id->str_id != construction_constr_veh ) {
         here.partial_con_remove( terp );
     }
     // Some constructions are allowed to have items left on the tile.
     if( built.post_flags.count( "keep_items" ) == 0 ) {
         // Move any items that have found their way onto the construction site.
         std::vector<tripoint_bub_ms> dump_spots;
         for( const tripoint_bub_ms &pt : here.points_in_radius( terp, 1 ) ) {
             if( here.can_put_items( pt ) && pt != terp ) {
                 dump_spots.push_back( pt );
             }
         }
         if( !dump_spots.empty() ) {
             tripoint_bub_ms dump_spot = random_entry( dump_spots );
             map_stack items = here.i_at( terp );
             for( map_stack::iterator it = items.begin(); it != items.end(); ) {
                 here.add_item_or_charges( dump_spot, *it );
                 it = items.erase( it );
             }
         } else {
             debugmsg( "No space to displace items from construction finishing" );
         }
     }
     // Make the terrain change
     if( !built.post_terrain.empty() ) {
         if( built.post_is_furniture ) {
             here.furn_set( terp, furn_str_id( built.post_terrain ) );
         } else {
             here.ter_set( terp, ter_str_id( built.post_terrain ) );
             // Make a roof if constructed terrain should have it and it's an open space
             if( construct::check_up_OK( terp ) ) {
                 const int_id<ter_t> post_terrain = ter_id( built.post_terrain );
                 if( post_terrain->roof ) {
                     const tripoint_bub_ms top = terp + tripoint_above;
                     if( here.ter( top )->has_flag( "EMPTY_SPACE" ) ) {
                         here.ter_set( top, ter_id( post_terrain->roof ) );
                     }
                 }
             }
             if( ter_id( built.post_terrain )->has_flag( "EMPTY_SPACE" ) ) {
                 const tripoint_bub_ms below = terp + tripoint_below;
                 if( below.z() > -OVERMAP_DEPTH && here.ter( below ).obj().has_flag( "SUPPORTS_ROOF" ) ) {
                     const map_bash_info bash_info = here.ter( below ).obj().bash;
                     // ter_set_bashed_from_above should default to ter_set
                     if( bash_info.ter_set_bashed_from_above.id() == t_null ) {
                         if( below.z() >= -1 ) {
                             // Stupid to set soil at above the ground level, but if they haven't defined
                             // anything for the terrain that's what you'll get.
                             // Trying to get the regional version of soil. There ought to be a sane way to do this...
                             ter_id converted_terrain = ter_t_dirt;
                             regional_settings settings = g->get_cur_om().get_settings();
                             std::map<std::string, int> soil_map =
                                 settings.region_terrain_and_furniture.unfinalized_terrain.find( "t_region_soil" )->second;
                             if( !soil_map.empty() ) {
                                 converted_terrain = ter_id(
                                                         settings.region_terrain_and_furniture.unfinalized_terrain.find( "t_region_soil" )->second.begin()->first );
                             }
                             here.ter_set( below, converted_terrain );
                         } else {
                             // At the time of writing there doesn't seem to be any regional definition of "rock" (which would have to be smashed to get a floor).
                             here.ter_set( below, ter_t_rock_floor );
                         }
                     } else {
                         here.ter_set( below, bash_info.ter_set_bashed_from_above.id() );
                     }
                 }
             }
         }
     }
     // Spawn byproducts
     if( built.byproduct_item_group ) {
         here.spawn_items( you->pos(), item_group::items_from( *built.byproduct_item_group,
                           calendar::turn ) );
     }
     add_msg( m_info, _( "%s finished construction: %s." ), you->disp_name( false, true ),
              built.group->name() );
     // clear the activity
     you->activity.set_to_null();
     you->recoil = MAX_RECOIL;
     // This comes after clearing the activity, in case the function interrupts
     // activities
     if( built.post_specials.size() > 1 ) { // pre-functions
         for( const auto &special : built.post_specials ) {
             special( terp, *you );
         }
     } else {
         built.post_special( terp, *you );
     }
     // Players will not automatically resume backlog, other Characters will.
     if( you->is_avatar() && !you->backlog.empty() &&
         you->backlog.front().id() == ACT_MULTIPLE_CONSTRUCTION ) {
         you->backlog.clear();
         you->assign_activity( ACT_MULTIPLE_CONSTRUCTION );
     }
 }
References _, ACT_MULTIPLE_CONSTRUCTION, Character::activity, map::add_item_or_charges(), add_msg(), Character::assign_activity(), Character::backlog, map_data_common_t::bash, item_stack::begin(), below, map::bub_from_abs(), construction::byproduct_item_group, map::can_put_items(), construction::category, construct::check_up_OK(), construction_category_APPLIANCE, construction_constr_veh, npc::current_activity_id, debugmsg, Character::disp_name(), item_stack::end(), map_stack::erase(), finalized, map::furn_set(), g, get_avatar(), get_map(), construction::group, map_data_common_t::has_flag(), map::i_at(), partial_con::id, string_id< T >::id(), Creature::is_avatar(), Character::is_npc(), item_group::items_from(), m_info, MAX_RECOIL, construction_group::name(), string_id< activity_type >::NULL_ID(), int_id< T >::obj(), OVERMAP_DEPTH, map::partial_con_at(), map::partial_con_remove(), player_activity::placement, map::points_in_radius(), Creature::pos(), construction::post_flags, construction::post_is_furniture, construction::post_special, construction::post_specials, construction::post_terrain, random_entry(), Character::recoil, regional_settings::region_terrain_and_furniture, construction::required_skills, npc::revert_after_activity(), ter_t::roof, Creature::set_moves(), player_activity::set_to_null(), map::spawn_items(), construction::str_id, player_activity::str_values, t_null, map::ter(), map::ter_set(), map_bash_info::ter_set_bashed_from_above, ter_t_dirt, ter_t_rock_floor, construction::time, tripoint_above, tripoint_below, calendar::turn, and region_terrain_and_furniture_settings::unfinalized_terrain.
Referenced by activity_handlers::build_do_turn().
construction_color()
static nc_color construction_color (const construction_group_str_id & group, bool highlight) static
Definition at line 334 of file construction.cpp.
 {
     nc_color col = c_dark_gray;
     Character &player_character = get_player_character();
     if( player_character.has_trait( trait_DEBUG_HS ) ) {
         col = c_white;
     } else {
         std::vector<construction *> cons = player_can_build_valid_constructions( player_character,
                                            player_character.crafting_inventory(), group );
         if( !cons.empty() ) {
             col = c_white;
             for( const auto &pr : cons.front()->required_skills ) {
                 int s_lvl = player_character.get_skill_level( pr.first );
                 if( s_lvl < pr.second ) {
                     col = c_red;
                 } else if( s_lvl < pr.second * 1.25 ) {
                     col = c_light_blue;
                 }
             }
         }
     }
     return highlight ? hilite( col ) : col;
 }
References c_dark_gray, c_light_blue, c_red, c_white, Character::crafting_inventory(), get_player_character(), Character::get_skill_level(), Character::has_trait(), hilite(), player_can_build_valid_constructions(), and trait_DEBUG_HS.
construction_menu()
construction_id construction_menu (const bool blueprint)
Definition at line 385 of file construction.cpp.
 {
     if( !finalized ) {
         debugmsg( "construction_menu called before finalization" );
         return construction_id( -1 );
     }
     static bool hide_unconstructable = false;
     // only display constructions the player can theoretically perform
     std::vector<construction_group_str_id> available;
     std::map<construction_category_id, std::vector<construction_group_str_id>> cat_available;
     load_available_constructions( available, cat_available, hide_unconstructable );
     if( available.empty() ) {
         popup( _( "You can not construct anything here." ) );
         return construction_id( -1 );
     }
     int w_height = 0;
     int w_width = 0;
     catacurses::window w_con;
     int w_list_width = 0;
     int w_list_height = 0;
     const int w_list_x0 = 1;
     catacurses::window w_list;
     std::vector<std::string> notes;
     int pos_x = 0;
     int available_window_width = 0;
     int available_buffer_height = 0;
     construction_id ret( -1 );
     bool update_info = true;
     bool update_cat = true;
     bool isnew = true;
     int tabindex = 0;
     int select = 0;
     int offset = 0;
     bool exit = false;
     construction_category_id category_id;
     std::vector<construction_group_str_id> constructs;
     //storage for the color text so it can be scrolled
     std::vector< std::vector < std::string > > construct_buffers;
     std::vector<std::string> full_construct_buffer;
     std::vector<int> construct_buffer_breakpoints;
     int total_project_breakpoints = 0;
     int current_construct_breakpoint = 0;
     avatar &player_character = get_avatar();
     const inventory &total_inv = player_character.crafting_inventory();
     input_context ctxt( "CONSTRUCTION" );
     ctxt.register_navigate_ui_list();
     ctxt.register_leftright();
     ctxt.register_action( "NEXT_TAB" );
     ctxt.register_action( "PREV_TAB" );
     ctxt.register_action( "SCROLL_STAGE_UP" );
     ctxt.register_action( "SCROLL_STAGE_DOWN" );
     ctxt.register_action( "CONFIRM" );
     ctxt.register_action( "TOGGLE_UNAVAILABLE_CONSTRUCTIONS" );
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     ctxt.register_action( "FILTER" );
     ctxt.register_action( "RESET_FILTER" );
     const std::vector<construction_category> &construct_cat = construction_categories::get_all();
     const int tabcount = static_cast<int>( construction_category::count() );
     std::string filter;
     const nc_color color_stage = c_white;
     ui_adaptor ui;
     const auto recalc_buffer = [&]() {
         //leave room for top and bottom UI text
         available_buffer_height = w_height - 3 - 3 - static_cast<int>( notes.size() );
         if( !constructs.empty() ) {
             if( select >= static_cast<int>( constructs.size() ) ) {
                 select = 0;
             }
             const construction_group_str_id &current_group = constructs[select];
             //construct the project list buffer
             // Print stages and their requirement.
             std::vector<construction *> options = constructions_by_group( current_group );
             construct_buffers.clear();
             current_construct_breakpoint = 0;
             construct_buffer_breakpoints.clear();
             full_construct_buffer.clear();
             int stage_counter = 0;
             for( std::vector<construction *>::iterator it = options.begin();
                  it != options.end(); ++it ) {
                 stage_counter++;
                 construction *current_con = *it;
                 if( hide_unconstructable && !can_construct( *current_con ) ) {
                     continue;
                 }
                 // Update the cached availability of components and tools in the requirement object
                 current_con->requirements->can_make_with_inventory( total_inv, is_crafting_component );
                 std::vector<std::string> current_buffer;
                 const auto add_folded = [&]( const std::vector<std::string> &folded ) {
                     current_buffer.insert( current_buffer.end(), folded.begin(), folded.end() );
                 };
                 const auto add_line = [&]( const std::string & line ) {
                     add_folded( foldstring( line, available_window_width ) );
                 };
                 // display final product name only if more than one step.
                 // Assume single stage constructions should be clear
                 // in their title what their result is.
                 if( !current_con->post_terrain.empty() && options.size() > 1 ) {
                     //also print out stage number when multiple stages are available
                     std::string current_line = string_format( _( "Stage/Variant #%d: " ), stage_counter );
                     // print name of the result of each stage
                     std::string result_string;
                     if( current_con->post_is_furniture ) {
                         result_string = furn_str_id( current_con->post_terrain ).obj().name();
                     } else {
                         result_string = ter_str_id( current_con->post_terrain ).obj().name();
                     }
                     current_line += colorize( result_string, color_title );
                     add_line( current_line );
                     // display description of the result for multi-stages
                     current_line = _( "Result: " );
                     if( current_con->post_is_furniture ) {
                         current_line += colorize(
                                             furn_str_id( current_con->post_terrain ).obj().description,
                                             color_data
                                         );
                         furn_id fid( current_con->post_terrain );
                         if( !fid->crafting_pseudo_item.is_empty() ) {
                             current_line += furniture_qualities_string( fid );
                         }
                     } else {
                         current_line += colorize(
                                             ter_str_id( current_con->post_terrain ).obj().description,
                                             color_data
                                         );
                     }
                     add_line( current_line );
                     // display description of the result for single stages
                 } else if( !current_con->post_terrain.empty() ) {
                     std::string current_line = _( "Result: " );
                     if( current_con->post_is_furniture ) {
                         current_line += colorize(
                                             furn_str_id( current_con->post_terrain ).obj().description,
                                             color_data
                                         );
                         furn_id fid( current_con->post_terrain );
                         if( !fid->crafting_pseudo_item.is_empty() ) {
                             current_line += furniture_qualities_string( fid );
                         }
                     } else {
                         current_line += colorize(
                                             ter_str_id( current_con->post_terrain ).obj().description,
                                             color_data
                                         );
                     }
                     add_line( current_line );
                 }
                 // display required skill and difficulty
                 if( current_con->required_skills.empty() ) {
                     add_line( _( "N/A" ) );
                 } else {
                     std::string current_line = _( "Required skills: " ) + enumerate_as_string(
                                                    current_con->required_skills.begin(), current_con->required_skills.end(),
                     [&player_character]( const std::pair<skill_id, int> &skill ) {
                         nc_color col;
                         int s_lvl = player_character.get_skill_level( skill.first );
                         if( s_lvl < skill.second ) {
                             col = c_red;
                         } else if( s_lvl < skill.second * 1.25 ) {
                             col = c_light_blue;
                         } else {
                             col = c_green;
                         }
                         return colorize( string_format( "%s (%d)", skill.first.obj().name(), skill.second ), col );
                     }, enumeration_conjunction::none );
                     add_line( current_line );
                 }
                 // TODO: Textify pre_flags to provide a bit more information.
                 // Example: First step of dig pit could say something about
                 // requiring diggable ground.
                 if( !current_con->pre_terrain.empty() ) {
                     std::string require_string;
                     if( current_con->pre_is_furniture ) {
                         require_string = furn_str_id( current_con->pre_terrain )->name();
                     } else {
                         require_string = ter_str_id( current_con->pre_terrain )->name();
                     }
                     nc_color pre_color = has_pre_terrain( *current_con ) ? c_green : c_red;
                     add_line( _( "Requires: " ) + colorize( require_string, pre_color ) );
                 }
                 if( !current_con->pre_note.empty() ) {
                     add_line( _( "Annotation: " ) + colorize( current_con->pre_note, color_data ) );
                 }
                 // get pre-folded versions of the rest of the construction project to be displayed later
                 // get time needed
                 add_folded( current_con->get_folded_time_string( available_window_width ) );
                 add_folded( current_con->requirements->get_folded_tools_list( available_window_width, color_stage,
                             total_inv ) );
                 add_folded( current_con->requirements->get_folded_components_list( available_window_width,
                             color_stage, total_inv, is_crafting_component ) );
                 construct_buffers.push_back( current_buffer );
             }
             //determine where the printing starts for each project, so it can be scrolled to those points
             size_t current_buffer_location = 0;
             for( size_t i = 0; i < construct_buffers.size(); i++ ) {
                 construct_buffer_breakpoints.push_back( static_cast<int>( current_buffer_location ) );
                 full_construct_buffer.insert( full_construct_buffer.end(), construct_buffers[i].begin(),
                                               construct_buffers[i].end() );
                 //handle text too large for one screen
                 if( construct_buffers[i].size() > static_cast<size_t>( available_buffer_height ) ) {
                     construct_buffer_breakpoints.push_back( static_cast<int>( current_buffer_location +
                                                             static_cast<size_t>( available_buffer_height ) ) );
                 }
                 current_buffer_location += construct_buffers[i].size();
                 if( i < construct_buffers.size() - 1 ) {
                     full_construct_buffer.emplace_back( );
                     current_buffer_location++;
                 }
             }
             total_project_breakpoints = static_cast<int>( construct_buffer_breakpoints.size() );
         }
     };
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         w_height = TERMY;
         if( static_cast<int>( available.size() ) + 2 < w_height ) {
             w_height = available.size() + 2;
         }
         if( w_height < FULL_SCREEN_HEIGHT ) {
             w_height = FULL_SCREEN_HEIGHT;
         }
         w_width = std::max( FULL_SCREEN_WIDTH, TERMX * 2 / 3 );
         const int w_y0 = ( TERMY > w_height ) ? ( TERMY - w_height ) / 2 : 0;
         const int w_x0 = ( TERMX > w_width ) ? ( TERMX - w_width ) / 2 : 0;
         w_con = catacurses::newwin( w_height, w_width, point( w_x0, w_y0 ) );
         w_list_width = static_cast<int>( .375 * w_width );
         w_list_height = w_height - 4;
         w_list = catacurses::newwin( w_list_height, w_list_width,
                                      point( w_x0 + w_list_x0, w_y0 + 3 ) );
         pos_x = w_list_width + w_list_x0 + 2;
         available_window_width = w_width - pos_x - 1;
         recalc_buffer();
         ui.position_from_window( w_con );
     } );
     ui.mark_resize();
     ui.on_redraw( [&]( ui_adaptor & ui ) {
         draw_grid( w_con, w_list_width + w_list_x0 );
         // Erase existing tab selection & list of constructions
         mvwhline( w_con, point_south_east, ' ', w_list_width );
         werase( w_list );
         // Print new tab listing
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         mvwprintz( w_con, point( 1, 1 ), c_yellow, "<< %s >>", construct_cat[tabindex].name() );
         // Determine where in the master list to start printing
         calcStartPos( offset, select, w_list_height, constructs.size() );
         // Print the constructions between offset and max (or how many will fit)
         for( size_t i = 0; static_cast<int>( i ) < w_list_height &&
              ( i + offset ) < constructs.size(); i++ ) {
             int current = i + offset;
             const construction_group_str_id &group = constructs[current];
             bool highlight = current == select;
             const point print_from( 0, i );
             if( highlight ) {
                 ui.set_cursor( w_list, print_from );
             }
             trim_and_print( w_list, print_from, w_list_width,
                             construction_color( group, highlight ), group->name() );
         }
         // Clear out lines for tools & materials
         for( int i = 1; i < w_height - 1; i++ ) {
             mvwhline( w_con, point( pos_x, i ), ' ', available_window_width );
         }
         // print the hotkeys regardless of if there are constructions
         for( size_t i = 0; i < notes.size(); ++i ) {
             trim_and_print( w_con, point( pos_x,
                                           w_height - 1 - static_cast<int>( notes.size() ) + static_cast<int>( i ) ),
                             available_window_width, c_white, notes[i] );
         }
         if( !constructs.empty() ) {
             if( select >= static_cast<int>( constructs.size() ) ) {
                 select = 0;
             }
             const construction_group_str_id &current_group = constructs[select];
             // Print construction name
             trim_and_print( w_con, point( pos_x, 1 ), available_window_width, c_white, current_group->name() );
             if( current_construct_breakpoint > 0 ) {
                 // Print previous stage indicator if breakpoint is past the beginning
                 trim_and_print( w_con, point( pos_x, 2 ), available_window_width, c_white,
                                 _( "Press [<color_yellow>%s</color>] to show previous stage(s)." ),
                                 ctxt.get_desc( "SCROLL_STAGE_UP" ) );
             }
             if( static_cast<size_t>( construct_buffer_breakpoints[current_construct_breakpoint] ) +
                 available_buffer_height < full_construct_buffer.size() ) {
                 // Print next stage indicator if more breakpoints are remaining after screen height
                 trim_and_print( w_con, point( pos_x, w_height - 2 - static_cast<int>( notes.size() ) ),
                                 available_window_width, c_white,
                                 _( "Press [<color_yellow>%s</color>] to show next stage(s)." ),
                                 ctxt.get_desc( "SCROLL_STAGE_DOWN" ) );
             }
             // Leave room for above/below indicators
             int ypos = 3;
             nc_color stored_color = color_stage;
             for( size_t i = static_cast<size_t>( construct_buffer_breakpoints[current_construct_breakpoint] );
                  i < full_construct_buffer.size(); i++ ) {
                 //the value of 3 is from leaving room at the top of window
                 if( ypos > available_buffer_height + 3 ) {
                     break;
                 }
                 print_colored_text( w_con, point( w_list_width + w_list_x0 + 2, ypos++ ), stored_color, color_stage,
                                     full_construct_buffer[i] );
             }
         }
         draw_scrollbar( w_con, select, w_list_height, constructs.size(), point( 0, 3 ) );
         wnoutrefresh( w_con );
         wnoutrefresh( w_list );
     } );
     do {
         if( update_cat ) {
             update_cat = false;
             construction_group_str_id last_construction = construction_group_str_id::NULL_ID();
             if( isnew ) {
                 filter = uistate.construction_filter;
                 tabindex = uistate.construction_tab.is_valid()
                            ? uistate.construction_tab.id().to_i() : 0;
                 if( uistate.last_construction.is_valid() ) {
                     last_construction = uistate.last_construction;
                 }
             } else if( select >= 0 && static_cast<size_t>( select ) < constructs.size() ) {
                 last_construction = constructs[select];
             }
             category_id = construct_cat[tabindex].id;
             if( category_id == construction_category_ALL ) {
                 constructs = available;
             } else if( category_id == construction_category_FILTER ) {
                 constructs.clear();
                 std::copy_if( available.begin(), available.end(),
                               std::back_inserter( constructs ),
                 [&]( const construction_group_str_id & group ) {
                     return lcmatch( group->name(), filter );
                 } );
             } else {
                 constructs = cat_available[category_id];
             }
             select = 0;
             if( last_construction ) {
                 const auto it = std::find( constructs.begin(), constructs.end(),
                                            last_construction );
                 if( it != constructs.end() ) {
                     select = std::distance( constructs.begin(), it );
                 }
             }
         }
         isnew = false;
         static int lang_version = detail::get_current_language_version();
         //lang check here is needed to redraw the menu when using "Toggle language to English" option
         if( update_info || lang_version != detail::get_current_language_version() ) {
             update_info = false;
             lang_version = detail::get_current_language_version();
             notes.clear();
             if( tabindex == tabcount - 1 && !filter.empty() ) {
                 notes.push_back( string_format( _( "Press [<color_red>%s</color>] to clear filter." ),
                                                 ctxt.get_desc( "RESET_FILTER" ) ) );
             }
             notes.push_back( string_format( _( "Press [<color_yellow>%s or %s</color>] to tab." ),
                                             ctxt.get_desc( "LEFT" ),
                                             ctxt.get_desc( "RIGHT" ) ) );
             notes.push_back( string_format( _( "Press [<color_yellow>%s</color>] to search." ),
                                             ctxt.get_desc( "FILTER" ) ) );
             if( !hide_unconstructable ) {
                 notes.push_back( string_format(
                                      _( "Press [<color_yellow>%s</color>] to hide unavailable constructions." ),
                                      ctxt.get_desc( "TOGGLE_UNAVAILABLE_CONSTRUCTIONS" ) ) );
             } else {
                 notes.push_back( string_format(
                                      _( "Press [<color_red>%s</color>] to show unavailable constructions." ),
                                      ctxt.get_desc( "TOGGLE_UNAVAILABLE_CONSTRUCTIONS" ) ) );
             }
             notes.push_back( string_format(
                                  _( "Press [<color_yellow>%s</color>] to view and edit keybindings." ),
                                  ctxt.get_desc( "HELP_KEYBINDINGS" ) ) );
             recalc_buffer();
         } // Finished updating
         ui_manager::redraw();
         const std::string action = ctxt.handle_input();
         const int recmax = static_cast<int>( constructs.size() );
         const int scroll_rate = recmax > 20 ? 10 : 3;
         if( action == "FILTER" ) {
             string_input_popup popup;
             popup
             .title( _( "Search" ) )
             .width( 50 )
             .description( _( "Filter" ) )
             .max_length( 100 )
             .text( tabindex == tabcount - 1 ? filter : std::string() )
             .query();
             if( popup.confirmed() ) {
                 filter = popup.text();
                 uistate.construction_filter = filter;
                 update_info = true;
                 update_cat = true;
                 tabindex = tabcount - 1;
             }
         } else if( action == "RESET_FILTER" ) {
             if( tabindex == tabcount - 1 && !filter.empty() ) {
                 filter.clear();
                 uistate.construction_filter.clear();
                 update_info = true;
                 update_cat = true;
             }
         } else if( navigate_ui_list( action, select, scroll_rate, recmax, true ) ) {
             update_info = true;
         } else if( action == "LEFT" || action == "PREV_TAB" || action == "RIGHT" || action == "NEXT_TAB" ) {
             update_info = true;
             update_cat = true;
             tabindex = inc_clamp_wrap( tabindex, action == "RIGHT" || action == "NEXT_TAB", tabcount );
         } else if( action == "SCROLL_STAGE_UP" || action == "SCROLL_STAGE_DOWN" ) {
             current_construct_breakpoint = inc_clamp( current_construct_breakpoint,
                                            action == "SCROLL_STAGE_DOWN", total_project_breakpoints - 1 );
         } else if( action == "QUIT" ) {
             exit = true;
         } else if( action == "TOGGLE_UNAVAILABLE_CONSTRUCTIONS" ) {
             update_info = true;
             update_cat = true;
             hide_unconstructable = !hide_unconstructable;
             offset = 0;
             load_available_constructions( available, cat_available, hide_unconstructable );
         } else if( action == "CONFIRM" ) {
             if( constructs.empty() || select >= static_cast<int>( constructs.size() ) ) {
                 // Nothing to be done here
                 continue;
             }
             if( !blueprint ) {
                 if( player_can_build( player_character, total_inv, constructs[select] ) ) {
                     if( !player_can_see_to_build( player_character, constructs[select] ) ) {
                         add_msg( m_info, _( "It is too dark to construct right now." ) );
                     } else {
                         ui.reset();
                         place_construction( { constructs[select] } );
                         uistate.last_construction = constructs[select];
                     }
                     exit = true;
                 } else {
                     popup( _( "You can't build that!" ) );
                     update_info = true;
                 }
             } else {
                 // get the index of the overall constructions list from current_group
                 const std::vector<construction> &list_constructions = get_constructions();
                 for( int i = 0; i < static_cast<int>( list_constructions.size() ); ++i ) {
                     if( constructs[select] == list_constructions[i].group ) {
                         ret = construction_id( i );
                         break;
                     }
                 }
                 exit = true;
             }
         }
     } while( !exit );
     uistate.construction_tab = int_id<construction_category>( tabindex ).id();
     return ret;
 }
References _, available, c_green, c_red, c_white, can_construct(), requirement_data::can_make_with_inventory(), color_data, color_title, colorize(), constructions_by_group(), construction_category::count(), Character::crafting_inventory(), furn_t::crafting_pseudo_item, debugmsg, map_data_common_t::description, enumerate_as_string(), filter, finalized, foldstring(), furniture_qualities_string(), construction_categories::get_all(), get_avatar(), has_pre_terrain(), is_crafting_component(), string_id< T >::is_empty(), line(), load_available_constructions(), map_data_common_t::name(), none, string_id< T >::obj(), PATH_INFO::options(), popup(), construction::post_is_furniture, construction::post_terrain, input_context::register_action(), input_context::register_leftright(), input_context::register_navigate_ui_list(), construction::required_skills, construction::requirements, cata::hash64_detail::ret, om_direction::size, and string_format().
Referenced by game::do_regular_action(), and blueprint_options::query_con().
constructions_by_filter()
std::vector<construction *> constructions_by_filter (std::function< bool(construction const &)> const & filter)
Definition at line 274 of file construction.cpp.
 {
     if( !finalized ) {
         debugmsg( "constructions_by_filter called before finalization" );
         return {};
     }
     std::vector<construction *> result;
     for( construction &constructions_a : constructions ) {
         if( filter( constructions_a ) ) {
             result.push_back( &constructions_a );
         }
     }
     return result;
 }
References constructions, debugmsg, filter, and finalized.
Referenced by anonymous_namespace{activity_item_handling.cpp}::_find_alt_construction(), anonymous_namespace{activity_item_handling.cpp}::_find_prereq(), and constructions_by_group().
constructions_by_group()
std::vector<construction *> constructions_by_group (const construction_group_str_id & group)
Definition at line 265 of file construction.cpp.
 {
     return constructions_by_filter(
     [&group]( construction const & it ) {
         return it.group == group;
     } );
 }
References constructions_by_filter(), and construction::group.
Referenced by construction_menu(), find_base_construction(), place_construction(), player_can_build(), player_can_build_valid_constructions(), and player_can_see_to_build().
draw_grid()
static void draw_grid (const catacurses::window & w, const int list_width) static
Definition at line 318 of file construction.cpp.
 {
     draw_border( w );
     mvwprintz( w, point( 2, 0 ), c_light_red, _( " Construction " ) );
     // draw internal lines
     mvwvline( w, point( list_width, 1 ), LINE_XOXO, getmaxy( w ) - 2 );
     mvwhline( w, point( 1, 2 ), LINE_OXOX, list_width );
     // draw intersections
     mvwputch( w, point( list_width, 0 ), c_light_gray, LINE_OXXX );
     mvwputch( w, point( list_width, getmaxy( w ) - 1 ), c_light_gray, LINE_XXOX );
     mvwputch( w, point( 0, 2 ), c_light_gray, LINE_XXXO );
     mvwputch( w, point( list_width, 2 ), c_light_gray, LINE_XOXX );
     wnoutrefresh( w );
 }
References _, c_light_gray, c_light_red, draw_border(), catacurses::getmaxy(), LINE_OXOX, LINE_OXXX, LINE_XOXO, LINE_XOXX, LINE_XXOX, LINE_XXXO, catacurses::mvwhline(), mvwprintz(), mvwputch(), catacurses::mvwvline(), and catacurses::wnoutrefresh().
finalize_constructions()
void finalize_constructions ()
Definition at line 2207 of file construction.cpp.
 {
     std::vector<item_comp> frame_items;
     for( const vpart_info &vpi : vehicles::parts::get_all() ) {
         if( !vpi.has_flag( flag_INITIAL_PART ) ) {
             continue;
         }
         if( vpi.id == vpart_frame ) {
             frame_items.insert( frame_items.begin(), { vpi.base_item, 1 } );
         } else {
             frame_items.emplace_back( vpi.base_item, 1 );
         }
     }
     if( frame_items.empty() ) {
         debugmsg( "No valid frames detected for vehicle construction" );
     }
     for( construction &con : constructions ) {
         if( !con.group.is_valid() ) {
             debugmsg( "Invalid construction group (%s) defined for construction (%s)",
                       con.group.str(), con.str_id.str() );
         }
         if( con.vehicle_start ) {
             const_cast<requirement_data &>( con.requirements.obj() ).get_components().push_back( frame_items );
         }
         bool is_valid_construction_category = false;
         for( const construction_category &cc : construction_categories::get_all() ) {
             if( con.category == cc.id ) {
                 is_valid_construction_category = true;
                 break;
             }
         }
         if( !is_valid_construction_category ) {
             debugmsg( "Invalid construction category (%s) defined for construction (%s)", con.category.str(),
                       con.str_id.str() );
         }
         requirement_data requirements_ = std::accumulate(
                                              con.reqs_using.begin(), con.reqs_using.end(), *con.requirements );
         requirement_data::save_requirement( requirements_, con.requirements );
         con.reqs_using.clear();
         inp_mngr.pump_events();
     }
     constructions.erase( std::remove_if( constructions.begin(), constructions.end(),
     [&]( const construction & c ) {
         return c.requirements->is_blacklisted();
     } ), constructions.end() );
     construction_id_map.clear();
     for( size_t i = 0; i < constructions.size(); i++ ) {
         constructions[ i ].id = construction_id( i );
         construction_id_map.emplace( constructions[i].str_id, constructions[i].id );
     }
     finalized = true;
 }
References c, construction_id_map, constructions, debugmsg, finalized, flag_INITIAL_PART(), construction_categories::get_all(), vehicles::parts::get_all(), inp_mngr, input_manager::pump_events(), requirement_data::save_requirement(), and vpart_frame.
Referenced by DynamicDataLoader::finalize_loaded_data().
flag_INITIAL_PART()
static const std::string flag_INITIAL_PART ("INITIAL_PART") static
Referenced by finalize_constructions(), and vpart_from_item().
flag_WIRING()
static const std::string flag_WIRING ("WIRING") static
Referenced by construct::check_no_wiring().
furniture_qualities_string()
static std::string furniture_qualities_string (const furn_id & fid) static
Definition at line 368 of file construction.cpp.
 {
     std::string ret = "\n";
     // Make a pseudo item instance so we can use qualities_info later
     const item pseudo( fid->crafting_pseudo_item );
     // Set up iteminfo query to show qualities
     std::vector<iteminfo_parts> quality_part = { iteminfo_parts::QUALITIES };
     const iteminfo_query quality_query( quality_part );
     // Render info into info_vec
     std::vector<iteminfo> info_vec;
     pseudo.qualities_info( info_vec, &quality_query, 1, false );
     // Get a newline-separated string of quality info, then parse and print each line
     ret += format_item_info( info_vec, {} );
     return ret;
 }
References furn_t::crafting_pseudo_item, format_item_info(), QUALITIES, item::qualities_info(), and cata::hash64_detail::ret.
Referenced by construction_menu().
get_build_reqs_for_furn_ter_ids()
build_reqs get_build_reqs_for_furn_ter_ids (const std::pair< std::map< ter_id, int >, std::map< furn_id, int >> & changed_ids, ter_id const & base_ter)
Definition at line 2266 of file construction.cpp.
 {
     build_reqs total_reqs;
     if( !finalized ) {
         debugmsg( "get_build_reqs_for_furn_ter_ids called before finalization" );
         return total_reqs;
     }
     std::map<construction_id, int> total_builds;
     // iteratively recurse through the pre-terrains until the pre-terrain is empty, adding
     // the constructions to the total_builds map
     const auto add_builds = [&total_builds, &base_ter]( const construction & build, int count ) {
         if( total_builds.find( build.id ) == total_builds.end() ) {
             total_builds[build.id] = 0;
         }
         total_builds[build.id] += count;
         std::string build_pre_ter = build.pre_terrain;
         while( !build_pre_ter.empty() ) {
             for( const construction &pre_build : constructions ) {
                 if( pre_build.category == construction_category_REPAIR ) {
                     continue;
                 }
                 if( ( pre_build.post_terrain.empty() ||
                       ( !pre_build.post_is_furniture &&
                         ter_id( pre_build.post_terrain ) != base_ter ) ) &&
                     ( pre_build.pre_terrain.empty() ||
                       ( pre_build.post_is_furniture &&
                         ter_id( pre_build.pre_terrain ) == base_ter ) ) &&
                     pre_build.post_terrain == build_pre_ter &&
                     pre_build.pre_terrain != build.post_terrain ) {
                     if( total_builds.find( pre_build.id ) == total_builds.end() ) {
                         total_builds[pre_build.id] = 0;
                     }
                     total_builds[pre_build.id] += count;
                     build_pre_ter = pre_build.pre_terrain;
                     break;
                 }
             }
             break;
         }
     };
     // go through the list of terrains and add their constructions and any pre-constructions
     // to the map of total builds
     for( const auto &ter_data : changed_ids.first ) {
         for( const construction &build : constructions ) {
             if( build.post_terrain.empty() || build.post_is_furniture ||
                 build.category == construction_category_REPAIR ) {
                 continue;
             }
             if( ter_id( build.post_terrain ) == ter_data.first ) {
                 add_builds( build, ter_data.second );
                 break;
             }
         }
     }
     // same, but for furniture
     for( const auto &furn_data : changed_ids.second ) {
         for( const construction &build : constructions ) {
             if( build.post_terrain.empty() || !build.post_is_furniture ||
                 build.category == construction_category_REPAIR ) {
                 continue;
             }
             if( furn_id( build.post_terrain ) == furn_data.first ) {
                 add_builds( build, furn_data.second );
                 break;
             }
         }
     }
     for( const auto &build_data : total_builds ) {
         const construction &build = build_data.first.obj();
         const int count = build_data.second;
         total_reqs.time += build.time * count;
         total_reqs.raw_reqs[build.requirements] += count;
         for( const auto &req_skill : build.required_skills ) {
             auto it = total_reqs.skills.find( req_skill.first );
             if( it == total_reqs.skills.end() || it->second < req_skill.second ) {
                 total_reqs.skills[req_skill.first] = req_skill.second;
             }
         }
     }
     return total_reqs;
 }
References construction_category_REPAIR, constructions, debugmsg, finalized, build_reqs::raw_reqs, construction::required_skills, construction::requirements, build_reqs::skills, build_reqs::time, and construction::time.
Referenced by calculate_all_blueprint_reqs(), and recipe::check_blueprint_requirements().
get_constructions()
const std::vector<construction>& get_constructions ()
Definition at line 358 of file construction.cpp.
 {
     if( !finalized ) {
         debugmsg( "get_constructions called before finalization" );
         static std::vector<construction> fake_constructions;
         return fake_constructions;
     }
     return constructions;
 }
References constructions, debugmsg, and finalized.
Referenced by iuse::clear_rubble(), iuse::dig(), iuse::dig_channel(), iuse::fill_pit(), and blueprint_options::query_con().
has_pre_terrain() [1/2]
static bool has_pre_terrain (const construction & con) static
Definition at line 243 of file construction.cpp.
 {
     tripoint_bub_ms avatar_pos = get_player_character().pos_bub();
     for( const tripoint_bub_ms &p : get_map().points_in_radius( avatar_pos, 1 ) ) {
         if( p != avatar_pos && has_pre_terrain( con, p ) ) {
             return true;
         }
     }
     return false;
 }
References get_map(), get_player_character(), has_pre_terrain(), points_in_radius(), and Creature::pos_bub().
has_pre_terrain() [2/2]
static bool has_pre_terrain (const construction & con, const tripoint_bub_ms & p) static
Definition at line 227 of file construction.cpp.
 {
     if( con.pre_terrain.empty() ) {
         return true;
     }
     map &here = get_map();
     if( con.pre_is_furniture ) {
         furn_id f = furn_id( con.pre_terrain );
         return here.furn( p ) == f;
     } else {
         ter_id t = ter_id( con.pre_terrain );
         return here.ter( p ) == t;
     }
 }
References map::furn(), get_map(), construction::pre_is_furniture, construction::pre_terrain, and map::ter().
Referenced by can_construct(), construction_menu(), and has_pre_terrain().
load_available_constructions()
static void load_available_constructions (std::vector< construction_group_str_id > & available, std::map< construction_category_id, std::vector< construction_group_str_id >> & cat_available, bool hide_unconstructable) static
Definition at line 289 of file construction.cpp.
 {
     cat_available.clear();
     available.clear();
     if( !finalized ) {
         debugmsg( "load_available_constructions called before finalization" );
         return;
     }
     avatar &player_character = get_avatar();
     for( construction &it : constructions ) {
         if( it.on_display && ( !hide_unconstructable ||
                                player_can_build( player_character, player_character.crafting_inventory(), it ) ) ) {
             bool already_have_it = false;
             for( auto &avail_it : available ) {
                 if( avail_it == it.group ) {
                     already_have_it = true;
                     break;
                 }
             }
             if( !already_have_it ) {
                 available.push_back( it.group );
                 cat_available[it.category].push_back( it.group );
             }
         }
     }
 }
References available, constructions, Character::crafting_inventory(), debugmsg, finalized, get_avatar(), and player_can_build().
Referenced by construction_menu().
load_construction()
void load_construction (const JsonObject & jo)
Definition at line 1909 of file construction.cpp.
 {
     construction con;
     // These ids are only temporary. The actual ids are determined in finalize_construction,
     // after removing blacklisted constructions.
     con.id = construction_id( -1 );
     con.str_id = construction_str_id( jo.get_string( "id" ) );
     if( con.str_id.is_null() ) {
         jo.throw_error_at( "id", "Null construction id specified" );
     } else if( construction_id_map.find( con.str_id ) != construction_id_map.end() ) {
         jo.throw_error_at( "id", "Duplicate construction id" );
     }
     jo.get_member( "group" ).read( con.group );
     if( jo.has_member( "required_skills" ) ) {
         for( JsonArray arr : jo.get_array( "required_skills" ) ) {
             con.required_skills[skill_id( arr.get_string( 0 ) )] = arr.get_int( 1 );
         }
     } else {
         skill_id legacy_skill( jo.get_string( "skill", skill_fabrication.str() ) );
         int legacy_diff = jo.get_int( "difficulty" );
         con.required_skills[ legacy_skill ] = legacy_diff;
     }
     con.category = construction_category_id( jo.get_string( "category", "OTHER" ) );
     if( jo.has_string( "time" ) ) {
         con.time = to_moves<int>( read_from_json_string<time_duration>( jo.get_member( "time" ),
                                   time_duration::units ) );
     }
     const requirement_id req_id( "inline_construction_" + con.str_id.str() );
     requirement_data::load_requirement( jo, req_id );
     con.requirements = req_id;
     if( jo.has_string( "using" ) ) {
         con.reqs_using = { { requirement_id( jo.get_string( "using" ) ), 1} };
     } else if( jo.has_array( "using" ) ) {
         for( JsonArray cur : jo.get_array( "using" ) ) {
             con.reqs_using.emplace_back( requirement_id( cur.get_string( 0 ) ), cur.get_int( 1 ) );
         }
     }
     jo.read( "pre_note", con.pre_note );
     con.pre_terrain = jo.get_string( "pre_terrain", "" );
     if( con.pre_terrain.size() > 1
         && con.pre_terrain[0] == 'f'
         && con.pre_terrain[1] == '_' ) {
         con.pre_is_furniture = true;
     }
     con.post_terrain = jo.get_string( "post_terrain", "" );
     if( con.post_terrain.size() > 1
         && con.post_terrain[0] == 'f'
         && con.post_terrain[1] == '_' ) {
         con.post_is_furniture = true;
     }
     std::string activity_level = jo.get_string( "activity_level", "MODERATE_EXERCISE" );
     const auto activity_it = activity_levels_map.find( activity_level );
     if( activity_it != activity_levels_map.end() ) {
         con.activity_level = activity_it->second;
     } else {
         jo.throw_error( string_format( "Invalid activity level %s in construction %s", activity_level,
                                        con.str_id.str() ) );
     }
     if( jo.has_member( "pre_flags" ) ) {
         con.pre_flags.clear();
         if( jo.has_string( "pre_flags" ) ) {
             con.pre_flags.emplace( jo.get_string( "pre_flags" ), false );
         } else if( jo.has_object( "pre_flags" ) ) {
             JsonObject jflag = jo.get_object( "pre_flags" );
             con.pre_flags.emplace( jflag.get_string( "flag" ), jflag.get_bool( "force_terrain" ) );
         } else if( jo.has_array( "pre_flags" ) ) {
             for( JsonValue jval : jo.get_array( "pre_flags" ) ) {
                 if( jval.test_string() ) {
                     con.pre_flags.emplace( jval.get_string(), false );
                 } else if( jval.test_object() ) {
                     JsonObject jflag = jval.get_object();
                     con.pre_flags.emplace( jflag.get_string( "flag" ), jflag.get_bool( "force_terrain" ) );
                 }
             }
         }
     }
     con.post_flags = jo.get_tags( "post_flags" );
     if( jo.has_member( "byproducts" ) ) {
         con.byproduct_item_group = item_group::load_item_group( jo.get_member( "byproducts" ),
                                    "collection", "byproducts of construction " + con.str_id.str() );
     }
     static const std::map<std::string, bool( * )( const tripoint_bub_ms & )> pre_special_map = {{
             { "", construct::check_nothing },
             { "check_channel", construct::check_channel },
             { "check_empty", construct::check_empty },
             { "check_empty_lite", construct::check_empty_lite },
             { "check_support", construct::check_support },
             { "check_support_below", construct::check_support_below },
             { "check_single_support", construct::check_single_support },
             { "check_stable", construct::check_stable },
             { "check_nofloor_above", construct::check_nofloor_above },
             { "check_deconstruct", construct::check_deconstruct },
             { "check_up_OK", construct::check_up_OK },
             { "check_down_OK", construct::check_down_OK },
             { "check_no_trap", construct::check_no_trap },
             { "check_ramp_high", construct::check_ramp_high },
             { "check_no_wiring", construct::check_no_wiring },
             { "check_matching_down_above", construct::check_matching_down_above }
         }
     };
     static const std::map<std::string, void( * )( const tripoint_bub_ms &, Character & )>
     post_special_map = {{
             { "", construct::done_nothing },
             { "done_trunk_plank", construct::done_trunk_plank },
             { "done_grave", construct::done_grave },
             { "done_vehicle", construct::done_vehicle },
             { "done_appliance", construct::done_appliance },
             { "done_wiring", construct::done_wiring },
             { "done_deconstruct", construct::done_deconstruct },
             { "done_dig_grave", construct::done_dig_grave },
             { "done_dig_grave_nospawn", construct::done_dig_grave_nospawn },
             { "done_dig_stair", construct::done_dig_stair },
             { "done_mine_downstair", construct::done_mine_downstair },
             { "done_mine_upstair", construct::done_mine_upstair },
             { "done_wood_stairs", construct::done_wood_stairs },
             { "done_window_curtains", construct::done_window_curtains },
             { "done_extract_maybe_revert_to_dirt", construct::done_extract_maybe_revert_to_dirt },
             { "done_mark_firewood", construct::done_mark_firewood },
             { "done_mark_practice_target", construct::done_mark_practice_target },
             { "done_ramp_low", construct::done_ramp_low },
             { "done_ramp_high", construct::done_ramp_high },
             { "add_matching_down_above", construct::add_matching_down_above },
             { "remove_above", construct::remove_above },
             { "add_roof", construct::add_roof }
         }
     };
     static const std::map<std::string, void( * )( const tripoint_bub_ms &, Character & )>
     do_turn_special_map = {{
             { "", construct::done_nothing },
             { "do_turn_shovel", construct::do_turn_shovel },
             { "do_turn_exhume", construct::do_turn_exhume },
         }
     };
     static const std::map<std::string, void( * )( const tripoint_bub_ms & )>
     explain_fail_map = {{
             { "standard", construct::failure_standard },
             { "deconstruct", construct::failure_deconstruct },
         }
     };
     std::string failure_fallback = "standard";
     if( jo.has_array( "pre_special" ) ) {
         JsonArray jarr = jo.get_array( "pre_special" );
         for( std::string special : jarr ) {
             if( special == "check_deconstruct" ) {
                 failure_fallback =  "deconstruct";
             }
             assign_or_debugmsg( con.pre_special, special, pre_special_map );
             con.pre_specials.push_back( con.pre_special );
         }
     } else {
         const std::string special = jo.get_string( "pre_special", "" );
         if( special == "check_deconstruct" ) {
             failure_fallback =  "deconstruct";
         }
         assign_or_debugmsg( con.pre_special, special, pre_special_map );
     }
     if( jo.has_array( "post_special" ) ) {
         JsonArray jarr = jo.get_array( "post_special" );
         for( std::string special : jarr ) {
             assign_or_debugmsg( con.post_special, special, post_special_map );
             con.post_specials.push_back( con.post_special );
         }
     } else {
         assign_or_debugmsg( con.post_special, jo.get_string( "post_special", "" ), post_special_map );
     }
     assign_or_debugmsg( con.do_turn_special, jo.get_string( "do_turn_special", "" ),
                         do_turn_special_map );
     assign_or_debugmsg( con.explain_failure, jo.get_string( "explain_failure", failure_fallback ),
                         explain_fail_map );
     con.vehicle_start = jo.get_bool( "vehicle_start", false );
     con.on_display = jo.get_bool( "on_display", true );
     con.dark_craftable = jo.get_bool( "dark_craftable", false );
     con.strict = jo.get_bool( "strict", false );
     constructions.push_back( con );
     construction_id_map.emplace( con.str_id, con.id );
 }
References construction::activity_level, activity_levels_map, construct::add_matching_down_above(), construct::add_roof(), assign_or_debugmsg(), construction::byproduct_item_group, construction::category, construct::check_channel(), construct::check_deconstruct(), construct::check_down_OK(), construct::check_empty(), construct::check_empty_lite(), construct::check_matching_down_above(), construct::check_no_trap(), construct::check_no_wiring(), construct::check_nofloor_above(), construct::check_nothing(), construct::check_ramp_high(), construct::check_single_support(), construct::check_stable(), construct::check_support(), construct::check_support_below(), construct::check_up_OK(), construction_id_map, constructions, construction::dark_craftable, construct::do_turn_exhume(), construct::do_turn_shovel(), construction::do_turn_special, construct::done_appliance(), construct::done_deconstruct(), construct::done_dig_grave(), construct::done_dig_grave_nospawn(), construct::done_dig_stair(), construct::done_extract_maybe_revert_to_dirt(), construct::done_grave(), construct::done_mark_firewood(), construct::done_mark_practice_target(), construct::done_mine_downstair(), construct::done_mine_upstair(), construct::done_nothing(), construct::done_ramp_high(), construct::done_ramp_low(), construct::done_trunk_plank(), construct::done_vehicle(), construct::done_window_curtains(), construct::done_wiring(), construct::done_wood_stairs(), construction::explain_failure, construct::failure_deconstruct(), construct::failure_standard(), JsonObject::get_array(), JsonObject::get_bool(), JsonObject::get_int(), JsonObject::get_member(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::get_tags(), construction::group, JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), construction::id, string_id< T >::is_null(), item_group::load_item_group(), requirement_data::load_requirement(), spell_effect::map(), construction::on_display, construction::post_flags, construction::post_is_furniture, construction::post_special, construction::post_specials, construction::post_terrain, construction::pre_flags, construction::pre_is_furniture, construction::pre_note, construction::pre_special, construction::pre_specials, construction::pre_terrain, JsonValue::read(), JsonObject::read(), construct::remove_above(), construction::reqs_using, construction::required_skills, construction::requirements, skill_fabrication, string_id< T >::str(), construction::str_id, construction::strict, string_format(), JsonObject::throw_error(), JsonObject::throw_error_at(), construction::time, time_duration::units, and construction::vehicle_start.
Referenced by DynamicDataLoader::initialize().
place_construction()
void place_construction (std::vector< construction_group_str_id > const & groups)
Definition at line 996 of file construction.cpp.
 {
     avatar &player_character = get_avatar();
     const inventory &total_inv = player_character.crafting_inventory();
     std::map<tripoint_bub_ms, const construction *> valid;
     std::vector<construction *> cons;
     map &here = get_map();
     for( construction_group_str_id const &group : groups ) {
         std::vector<construction *> const temp = constructions_by_group( group );
         // TODO: fix point types
         for( const tripoint_bub_ms &p : here.points_in_radius( player_character.pos_bub(), 1 ) ) {
             for( const auto *con : temp ) {
                 if( p != player_character.pos_bub() && can_construct( *con, p ) &&
                     player_can_build( player_character, total_inv, *con, true ) ) {
                     valid[ p ] = con;
                 }
             }
         }
         std::move( temp.begin(), temp.end(), std::back_inserter( cons ) );
     }
     shared_ptr_fast<game::draw_callback_t> draw_valid = make_shared_fast<game::draw_callback_t>( [&]() {
         map &here = get_map();
         for( auto &elem : valid ) {
             // TODO: fix point types
             here.drawsq( g->w_terrain, elem.first.raw(),
                          drawsq_params().highlight( true ).show_items( true ) );
         }
     } );
     g->add_draw_callback( draw_valid );
     const std::optional<tripoint> pnt_ = choose_adjacent( _( "Construct where?" ) );
     if( !pnt_ ) {
         return;
     }
     // TODO: fix point types
     const tripoint_bub_ms pnt( *pnt_ );
     if( valid.find( pnt ) == valid.end() ) {
         cons.front()->explain_failure( pnt );
         return;
     }
     // Maybe there is already a partial_con on an existing trap, that isn't caught by the usual trap-checking.
     // because the pre-requisite construction is already a trap anyway.
     // This shouldn't normally happen, unless it's a spike pit being built on a pit for example.
     partial_con *pre_c = here.partial_con_at( pnt );
     if( pre_c ) {
         add_msg( m_info,
                  _( "There is already an unfinished construction there, examine it to continue working on it." ) );
         return;
     }
     std::list<item> used;
     const construction &con = *valid.find( pnt )->second;
     // create the partial construction struct
     partial_con pc;
     pc.id = con.id;
     if( player_character.has_trait( trait_DEBUG_HS ) ) {
         // Gift components
         for( const auto &it : con.requirements->get_components() ) {
             used.emplace_back( it.front().type );
         }
     } else {
         // Use up the components
         for( const std::vector<item_comp> &it : con.requirements->get_components() ) {
             std::list<item> tmp = player_character.consume_items( it, 1, is_crafting_component );
             used.splice( used.end(), tmp );
         }
     }
     pc.components = used;
     here.partial_con_set( pnt, pc );
     for( const auto &it : con.requirements->get_tools() ) {
         player_character.consume_tools( it );
     }
     player_character.invalidate_crafting_inventory();
     player_character.invalidate_weight_carried_cache();
     player_character.assign_activity( ACT_BUILD );
     player_character.activity.placement = here.getglobal( pnt );
 }
References _, ACT_BUILD, Character::activity, add_msg(), Character::assign_activity(), can_construct(), choose_adjacent(), partial_con::components, constructions_by_group(), Character::consume_items(), Character::consume_tools(), Character::crafting_inventory(), map::drawsq(), g, get_avatar(), requirement_data::get_components(), get_map(), requirement_data::get_tools(), map::getglobal(), Character::has_trait(), partial_con::id, construction::id, Character::invalidate_crafting_inventory(), Character::invalidate_weight_carried_cache(), is_crafting_component(), m_info, map::partial_con_at(), map::partial_con_set(), player_activity::placement, player_can_build(), map::points_in_radius(), Creature::pos_bub(), construction::requirements, temp, and trait_DEBUG_HS.
Referenced by iuse::clear_rubble(), iuse::dig(), iuse::dig_channel(), and iuse::fill_pit().
player_can_build() [1/2]
bool player_can_build (Character & you, const read_only_visitable & inv, const construction & con, const bool can_construct_skip)
Definition at line 918 of file construction.cpp.
 {
     if( you.has_trait( trait_DEBUG_HS ) ) {
         return true;
     }
     if( !you.meets_skill_requirements( con ) ) {
         return false;
     }
     // check for construction spot can be skipped by using can_construct_skip
     return con.requirements->can_make_with_inventory( inv, is_crafting_component ) &&
            ( can_construct_skip || can_construct( con ) );
 }
References can_construct(), requirement_data::can_make_with_inventory(), Character::has_trait(), is_crafting_component(), Character::meets_skill_requirements(), construction::requirements, and trait_DEBUG_HS.
player_can_build() [2/2]
bool player_can_build (Character & you, const read_only_visitable & inv, const construction_group_str_id & group) static
Definition at line 905 of file construction.cpp.
 {
     // check all with the same group to see if player can build any
     std::vector<construction *> cons = constructions_by_group( group );
     for( construction *&con : cons ) {
         if( player_can_build( you, inv, *con ) ) {
             return true;
         }
     }
     return false;
 }
References constructions_by_group().
Referenced by find_base_construction(), load_available_constructions(), place_construction(), and player_can_build_valid_constructions().
player_can_build_valid_constructions()
static std::vector< construction * > player_can_build_valid_constructions (Character & you, const read_only_visitable & inv, const construction_group_str_id & group) static
Definition at line 888 of file construction.cpp.
 {
     std::vector<construction *> result;
     // check all with the same group to see if player can build any
     // if so, it will be added to the result
     std::vector<construction *> cons = constructions_by_group( group );
     for( construction *&con : cons ) {
         if( player_can_build( you, inv, *con ) ) {
             result.push_back( con );
         }
     }
     return result;
 }
References constructions_by_group(), and player_can_build().
Referenced by construction_color().
player_can_see_to_build()
bool player_can_see_to_build (Character & you, const construction_group_str_id & group) static
Definition at line 934 of file construction.cpp.
 {
     if( you.fine_detail_vision_mod() < 4 || you.has_trait( trait_DEBUG_HS ) ) {
         return true;
     }
     std::vector<construction *> cons = constructions_by_group( group );
     for( construction *&con : cons ) {
         if( con->dark_craftable ) {
             return true;
         }
     }
     return false;
 }
References constructions_by_group(), Character::fine_detail_vision_mod(), Character::has_trait(), and trait_DEBUG_HS.
reset_constructions()
void reset_constructions ()
Definition at line 2100 of file construction.cpp.
 {
     constructions.clear();
     construction_id_map.clear();
     finalized = false;
 }
References construction_id_map, constructions, and finalized.
Referenced by DynamicDataLoader::unload_data().
standardize_construction_times()
void standardize_construction_times (const int time)
Set all constructions to take the specified time.
Definition at line 254 of file construction.cpp.
 {
     if( !finalized ) {
         debugmsg( "standardize_construction_times called before finalization" );
         return;
     }
     for( construction &c : constructions ) {
         c.time = time;
     }
 }
References c, constructions, debugmsg, and finalized.
unroll_digging()
static void unroll_digging (const int numer_of_2x4s) static
Definition at line 1618 of file construction.cpp.
 {
     // refund components!
     item rope( "rope_30" );
     map &here = get_map();
     tripoint avatar_pos = get_player_character().pos();
     here.add_item_or_charges( avatar_pos, rope );
     // presuming 2x4 to conserve lumber.
     here.spawn_item( avatar_pos, itype_2x4, numer_of_2x4s );
 }
References map::add_item_or_charges(), get_map(), get_player_character(), itype_2x4, Creature::pos(), and map::spawn_item().
Referenced by construct::done_digormine_stair(), and construct::done_mine_upstair().
vpart_from_item()
static vpart_id vpart_from_item (const itype_id & item_id) static
Definition at line 1450 of file construction.cpp.
 {
     for( const vpart_info &vpi : vehicles::parts::get_all() ) {
         if( vpi.base_item == item_id && vpi.has_flag( flag_INITIAL_PART ) ) {
             return vpi.id;
         }
     }
     // The INITIAL_PART flag is optional, if no part (based on the given item) has it, just use the
     // first part that is based in the given item (this is fine for example if there is only one
     // such type anyway).
     for( const vpart_info &vpi : vehicles::parts::get_all() ) {
         if( vpi.base_item == item_id ) {
             return vpi.id;
         }
     }
     debugmsg( "item %s used by construction is not base item of any vehicle part!", item_id.c_str() );
     return vpart_frame;
 }
References string_id< T >::c_str(), debugmsg, flag_INITIAL_PART(), vehicles::parts::get_all(), string_id< T >::id(), and vpart_frame.
Referenced by construct::done_vehicle(), and construct::done_wiring().
Variable Documentation
ACT_BUILD
const activity_id ACT_BUILD("ACT_BUILD") ("ACT_BUILD") static
Referenced by place_construction().
ACT_MULTIPLE_CONSTRUCTION
const activity_id ACT_MULTIPLE_CONSTRUCTION("ACT_MULTIPLE_CONSTRUCTION") ("ACT_MULTIPLE_CONSTRUCTION") static
Referenced by complete_construction().
color_data
const deferred_color color_data = def_c_cyan static
Definition at line 225 of file construction.cpp.
Referenced by construction_menu(), and construction::get_time_string().
color_title
const deferred_color color_title = def_c_light_red static
Definition at line 224 of file construction.cpp.
Referenced by construction_menu().
construction_category_ALL
const construction_category_id construction_category_ALL("ALL") ("ALL") static
construction_category_APPLIANCE
const construction_category_id construction_category_APPLIANCE("APPLIANCE") ("APPLIANCE") static
Referenced by complete_construction().
construction_category_FILTER
const construction_category_id construction_category_FILTER("FILTER") ("FILTER") static
construction_category_REPAIR
const construction_category_id construction_category_REPAIR("REPAIR") ("REPAIR") static
Referenced by get_build_reqs_for_furn_ter_ids().
construction_constr_veh
const construction_str_id construction_constr_veh("constr_veh") ("constr_veh") static
Referenced by complete_construction().
construction_id_map
std::map<construction_str_id, construction_id> construction_id_map static
Definition at line 213 of file construction.cpp.
Referenced by check_constructions(), finalize_constructions(), load_construction(), and reset_constructions().
constructions
std::vector<construction> constructions static
Definition at line 212 of file construction.cpp.
Referenced by check_constructions(), constructions_by_filter(), finalize_constructions(), get_build_reqs_for_furn_ter_ids(), get_constructions(), load_available_constructions(), load_construction(), reset_constructions(), and standardize_construction_times().
finalized
bool finalized = false static
Definition at line 147 of file construction.cpp.
Referenced by complete_construction(), construction_menu(), constructions_by_filter(), finalize_constructions(), get_build_reqs_for_furn_ter_ids(), get_constructions(), load_available_constructions(), reset_constructions(), and standardize_construction_times().
furn_f_coffin_c
const furn_str_id furn_f_coffin_c("f_coffin_c") ("f_coffin_c") static
Referenced by construct::done_dig_grave(), and construct::done_dig_grave_nospawn().
furn_f_coffin_o
const furn_str_id furn_f_coffin_o("f_coffin_o") ("f_coffin_o") static
Referenced by construct::done_dig_grave().
Item_spawn_data_allclothes
const item_group_id Item_spawn_data_allclothes("allclothes") ("allclothes") static
Referenced by construct::done_dig_grave().
Item_spawn_data_grave
const item_group_id Item_spawn_data_grave("grave") ("grave") static
Referenced by construct::done_dig_grave().
Item_spawn_data_jewelry_front
const item_group_id Item_spawn_data_jewelry_front("jewelry_front") ("jewelry_front") static
Referenced by construct::done_dig_grave().
itype_2x4
const itype_id itype_2x4("2x4") ("2x4") static
Referenced by unroll_digging().
itype_bone_human
const itype_id itype_bone_human("bone_human") ("bone_human") static
Referenced by construct::done_dig_grave().
itype_nail
const itype_id itype_nail("nail") ("nail") static
Referenced by construct::done_window_curtains().
itype_sheet
const itype_id itype_sheet("sheet") ("sheet") static
Referenced by construct::done_window_curtains().
itype_stick
const itype_id itype_stick("stick") ("stick") static
Referenced by construct::done_window_curtains().
itype_string_36
const itype_id itype_string_36("string_36") ("string_36") static
Referenced by construct::done_window_curtains().
itype_wall_wiring
const itype_id itype_wall_wiring("wall_wiring") ("wall_wiring") static
Referenced by construct::done_wiring().
json_flag_FILTHY
const flag_id json_flag_FILTHY("FILTHY") ("FILTHY") static
Referenced by construct::done_dig_grave().
json_flag_PIT
const flag_id json_flag_PIT("PIT") ("PIT") static
Referenced by construct::check_support_below().
mon_skeleton
const mtype_id mon_skeleton("mon_skeleton") ("mon_skeleton") static
Referenced by construct::done_dig_grave().
mon_zombie
const mtype_id mon_zombie("mon_zombie") ("mon_zombie") static
Referenced by construct::done_dig_grave().
mon_zombie_crawler
const mtype_id mon_zombie_crawler("mon_zombie_crawler") ("mon_zombie_crawler") static
Referenced by construct::done_dig_grave().
mon_zombie_fat
const mtype_id mon_zombie_fat("mon_zombie_fat") ("mon_zombie_fat") static
Referenced by construct::done_dig_grave().
mon_zombie_rot
const mtype_id mon_zombie_rot("mon_zombie_rot") ("mon_zombie_rot") static
Referenced by construct::done_dig_grave().
null_construction
const construction null_construction {} static
Definition at line 2355 of file construction.cpp.
qual_CUT
const quality_id qual_CUT("CUT") ("CUT") static
Referenced by construct::done_grave().
skill_fabrication
const skill_id skill_fabrication("fabrication") ("fabrication") static
Referenced by load_construction().
ter_t_clay
const ter_str_id ter_t_clay("t_clay") ("t_clay") static
Referenced by construct::done_extract_maybe_revert_to_dirt().
ter_t_dirt
const ter_str_id ter_t_dirt("t_dirt") ("t_dirt") static
Referenced by complete_construction(), and construct::done_extract_maybe_revert_to_dirt().
ter_t_hole
const ter_str_id ter_t_hole("t_hole") ("t_hole") static
Referenced by construct::done_digormine_stair().
ter_t_ladder_up
const ter_str_id ter_t_ladder_up("t_ladder_up") ("t_ladder_up") static
Referenced by construct::done_digormine_stair().
ter_t_lava
const ter_str_id ter_t_lava("t_lava") ("t_lava") static
Referenced by construct::done_digormine_stair(), and construct::done_mine_upstair().
ter_t_open_air
const ter_str_id ter_t_open_air("t_open_air") ("t_open_air") static
Referenced by construct::remove_above().
ter_t_pit
const ter_str_id ter_t_pit("t_pit") ("t_pit") static
Referenced by construct::done_digormine_stair().
ter_t_ramp_down_high
const ter_str_id ter_t_ramp_down_high("t_ramp_down_high") ("t_ramp_down_high") static
Referenced by construct::done_ramp_high().
ter_t_ramp_down_low
const ter_str_id ter_t_ramp_down_low("t_ramp_down_low") ("t_ramp_down_low") static
Referenced by construct::done_ramp_low().
ter_t_rock_floor
const ter_str_id ter_t_rock_floor("t_rock_floor") ("t_rock_floor") static
Referenced by complete_construction(), and construct::done_mine_upstair().
ter_t_sand
const ter_str_id ter_t_sand("t_sand") ("t_sand") static
Referenced by construct::done_extract_maybe_revert_to_dirt().
ter_t_stairs_down
const ter_str_id ter_t_stairs_down("t_stairs_down") ("t_stairs_down") static
Referenced by construct::done_digormine_stair(), and construct::done_mine_upstair().
ter_t_stairs_up
const ter_str_id ter_t_stairs_up("t_stairs_up") ("t_stairs_up") static
Referenced by construct::done_digormine_stair(), and construct::done_mine_upstair().
ter_t_wood_stairs_down
const ter_str_id ter_t_wood_stairs_down("t_wood_stairs_down") ("t_wood_stairs_down") static
Referenced by construct::done_wood_stairs().
tr_firewood_source
const trap_str_id tr_firewood_source("tr_firewood_source") ("tr_firewood_source") static
Referenced by construct::done_mark_firewood().
tr_practice_target
const trap_str_id tr_practice_target("tr_practice_target") ("tr_practice_target") static
Referenced by construct::done_mark_practice_target().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by construction_color(), place_construction(), player_can_build(), and player_can_see_to_build().
trait_EATDEAD
const trait_id trait_EATDEAD("EATDEAD") ("EATDEAD") static
Referenced by construct::do_turn_exhume().
trait_NUMB
const trait_id trait_NUMB("NUMB") ("NUMB") static
Referenced by construct::do_turn_exhume().
trait_PAINRESIST_TROGLO
const trait_id trait_PAINRESIST_TROGLO("PAINRESIST_TROGLO") ("PAINRESIST_TROGLO") static
Referenced by construct::done_digormine_stair(), and construct::done_mine_upstair().
trait_PSYCHOPATH
const trait_id trait_PSYCHOPATH("PSYCHOPATH") ("PSYCHOPATH") static
Referenced by construct::do_turn_exhume().
trait_SAPROVORE
const trait_id trait_SAPROVORE("SAPROVORE") ("SAPROVORE") static
Referenced by construct::do_turn_exhume().
trait_SPIRITUAL
const trait_id trait_SPIRITUAL("SPIRITUAL") ("SPIRITUAL") static
Referenced by construct::do_turn_exhume(), and construct::done_grave().
trait_STOCKY_TROGLO
const trait_id trait_STOCKY_TROGLO("STOCKY_TROGLO") ("STOCKY_TROGLO") static
Referenced by construct::done_digormine_stair(), and construct::done_mine_upstair().
vehicle_prototype_none
const vproto_id vehicle_prototype_none("none") ("none") static
Referenced by construct::done_vehicle().
vpart_frame
const vpart_id vpart_frame("frame") ("frame") static
Referenced by finalize_constructions(), and vpart_from_item().