Cataclysm DDA: src/consumption.cpp File Reference
consumption.cpp File Reference
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdlib>
#include <cstdint>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "addiction.h"
#include "avatar.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "color.h"
#include "contents_change_handler.h"
#include "creature.h"
#include "debug.h"
#include "dialogue.h"
#include "effect.h"
#include "effect_on_condition.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "flag.h"
#include "flat_set.h"
#include "game.h"
#include "game_constants.h"
#include "item.h"
#include "item_category.h"
#include "item_components.h"
#include "item_location.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "line.h"
#include "magic_enchantment.h"
#include "make_static.h"
#include "map.h"
#include "material.h"
#include "messages.h"
#include "monster.h"
#include "morale_types.h"
#include "mutation.h"
#include "npc.h"
#include "options.h"
#include "pickup.h"
#include "pimpl.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "requirements.h"
#include "ret_val.h"
#include "rng.h"
#include "stomach.h"
#include "string_formatter.h"
#include "text_snippets.h"
#include "translation.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "value_ptr.h"
#include "visitable.h"
#include "vitamin.h"
Functions
static const std::string comesttype_DRINK ("DRINK")
static const std::string comesttype_FOOD ("FOOD")
static int compute_default_effective_kcal (const item &comest, const Character &you, const cata::flat_set< flag_id > &extra_flags={})
static std::map< vitamin_id, int > compute_default_effective_vitamins (const item &it, const Character &you)
static nutrients compute_default_effective_nutrients (const item &comest, const Character &you, const cata::flat_set< flag_id > &extra_flags={})
static bool eat (item &food, Character &you, bool force)
Eat a comestible.
static void activate_consume_eocs (Character &you, item &target)
static bool query_consume_ownership (item &target, Character &p)
static bool consume_med (item &target, Character &you)
Consume medication.
Variables
static const bionic_id bio_faulty_grossfood ("bio_faulty_grossfood")
static const bionic_id bio_syringe ("bio_syringe")
static const bionic_id bio_taste_blocker ("bio_taste_blocker")
static const efftype_id effect_bloodworms ("bloodworms")
static const efftype_id effect_brainworms ("brainworms")
static const efftype_id effect_common_cold ("common_cold")
static const efftype_id effect_flu ("flu")
static const efftype_id effect_foodpoison ("foodpoison")
static const efftype_id effect_fungus ("fungus")
static const efftype_id effect_hallu ("hallu")
static const efftype_id effect_hunger_engorged ("hunger_engorged")
static const efftype_id effect_hunger_famished ("hunger_famished")
static const efftype_id effect_hunger_full ("hunger_full")
static const efftype_id effect_hunger_near_starving ("hunger_near_starving")
static const efftype_id effect_hunger_starving ("hunger_starving")
static const efftype_id effect_nausea ("nausea")
static const efftype_id effect_paincysts ("paincysts")
static const efftype_id effect_poison ("poison")
static const efftype_id effect_tapeworm ("tapeworm")
static const efftype_id effect_took_thorazine ("took_thorazine")
static const efftype_id effect_visuals ("visuals")
static const flag_id json_flag_ALLERGEN_BREAD ("ALLERGEN_BREAD")
static const flag_id json_flag_ALLERGEN_CHEESE ("ALLERGEN_CHEESE")
static const flag_id json_flag_ALLERGEN_DRIED_VEGETABLE ("ALLERGEN_DRIED_VEGETABLE")
static const flag_id json_flag_ALLERGEN_EGG ("ALLERGEN_EGG")
static const flag_id json_flag_ALLERGEN_FRUIT ("ALLERGEN_FRUIT")
static const flag_id json_flag_ALLERGEN_MEAT ("ALLERGEN_MEAT")
static const flag_id json_flag_ALLERGEN_MILK ("ALLERGEN_MILK")
static const flag_id json_flag_ALLERGEN_NUT ("ALLERGEN_NUT")
static const flag_id json_flag_ALLERGEN_VEGGY ("ALLERGEN_VEGGY")
static const flag_id json_flag_ALLERGEN_WHEAT ("ALLERGEN_WHEAT")
static const flag_id json_flag_ANIMAL_PRODUCT ("ANIMAL_PRODUCT")
static const item_category_id item_category_chems ("chems")
static const itype_id itype_apparatus ("apparatus")
static const itype_id itype_dab_pen_on ("dab_pen_on")
static const itype_id itype_syringe ("syringe")
static const json_character_flag json_flag_BLOODFEEDER ("BLOODFEEDER")
static const json_character_flag json_flag_CANNIBAL ("CANNIBAL")
static const json_character_flag json_flag_HEMOVORE ("HEMOVORE")
static const json_character_flag json_flag_IMMUNE_SPOIL ("IMMUNE_SPOIL")
static const json_character_flag json_flag_NUMB ("NUMB")
static const json_character_flag json_flag_PARAIMMUNE ("PARAIMMUNE")
static const json_character_flag json_flag_PRED1 ("PRED1")
static const json_character_flag json_flag_PRED2 ("PRED2")
static const json_character_flag json_flag_PRED3 ("PRED3")
static const json_character_flag json_flag_PRED4 ("PRED4")
static const json_character_flag json_flag_PSYCHOPATH ("PSYCHOPATH")
static const json_character_flag json_flag_SAPIOVORE ("SAPIOVORE")
static const json_character_flag json_flag_SPIRITUAL ("SPIRITUAL")
static const json_character_flag json_flag_STRICT_HUMANITARIAN ("STRICT_HUMANITARIAN")
static const material_id material_all ("all")
static const mtype_id mon_player_blob ("mon_player_blob")
static const mutation_category_id mutation_category_URSINE ("URSINE")
static const skill_id skill_cooking ("cooking")
static const skill_id skill_survival ("survival")
static const trait_id trait_ACIDBLOOD ("ACIDBLOOD")
static const trait_id trait_AMORPHOUS ("AMORPHOUS")
static const trait_id trait_ANTIFRUIT ("ANTIFRUIT")
static const trait_id trait_ANTIJUNK ("ANTIJUNK")
static const trait_id trait_ANTIWHEAT ("ANTIWHEAT")
static const trait_id trait_CARNIVORE ("CARNIVORE")
static const trait_id trait_EATDEAD ("EATDEAD")
static const trait_id trait_EATHEALTH ("EATHEALTH")
static const trait_id trait_GOURMAND ("GOURMAND")
static const trait_id trait_HERBIVORE ("HERBIVORE")
static const trait_id trait_HIBERNATE ("HIBERNATE")
static const trait_id trait_LACTOSE ("LACTOSE")
static const trait_id trait_MEATARIAN ("MEATARIAN")
static const trait_id trait_M_DEPENDENT ("M_DEPENDENT")
static const trait_id trait_M_IMMUNE ("M_IMMUNE")
static const trait_id trait_PICKYEATER ("PICKYEATER")
static const trait_id trait_PROBOSCIS ("PROBOSCIS")
static const trait_id trait_PROJUNK ("PROJUNK")
static const trait_id trait_PROJUNK2 ("PROJUNK2")
static const trait_id trait_RUMINANT ("RUMINANT")
static const trait_id trait_SAPROPHAGE ("SAPROPHAGE")
static const trait_id trait_SAPROVORE ("SAPROVORE")
static const trait_id trait_SCHIZOPHRENIC ("SCHIZOPHRENIC")
static const trait_id trait_SLIMESPAWNER ("SLIMESPAWNER")
static const trait_id trait_SPIRITUAL ("SPIRITUAL")
static const trait_id trait_STIMBOOST ("STIMBOOST")
static const trait_id trait_TABLEMANNERS ("TABLEMANNERS")
static const trait_id trait_THRESH_BIRD ("THRESH_BIRD")
static const trait_id trait_THRESH_CATTLE ("THRESH_CATTLE")
static const trait_id trait_THRESH_FELINE ("THRESH_FELINE")
static const trait_id trait_THRESH_LUPINE ("THRESH_LUPINE")
static const trait_id trait_THRESH_MOUSE ("THRESH_MOUSE")
static const trait_id trait_THRESH_PLANT ("THRESH_PLANT")
static const trait_id trait_THRESH_RABBIT ("THRESH_RABBIT")
static const trait_id trait_THRESH_RAT ("THRESH_RAT")
static const trait_id trait_THRESH_URSINE ("THRESH_URSINE")
static const trait_id trait_UNDINE_SLEEP_WATER ("UNDINE_SLEEP_WATER")
static const trait_id trait_VEGAN ("VEGAN")
static const trait_id trait_VEGETARIAN ("VEGETARIAN")
static const trait_id trait_WATERSLEEP ("WATERSLEEP")
static const vitamin_id vitamin_human_flesh_vitamin ("human_flesh_vitamin")
static const std::array< flag_id, 6 > carnivore_blacklist
static const std::array< flag_id, 2 > herbivore_blacklist
Function Documentation
activate_consume_eocs()
static void activate_consume_eocs (Character & you, item & target) static
Definition at line 1518 of file consumption.cpp.
 {
     Character *char_ptr = nullptr;
     if( avatar *u = you.as_avatar() ) {
         char_ptr = u;
     } else if( npc *n = you.as_npc() ) {
         char_ptr = n;
     }
     item_location loc( you, &target );
     dialogue d( get_talker_for( char_ptr ), get_talker_for( loc ) );
     const islot_comestible &comest = *target.get_comestible();
     for( const effect_on_condition_id &eoc : comest.consumption_eocs ) {
         eoc->activate( d );
     }
 }
References Creature::as_avatar(), Creature::as_npc(), islot_comestible::consumption_eocs, eoc, item::get_comestible(), get_talker_for(), and u.
Referenced by Character::consume_effects(), and consume_med().
comesttype_DRINK()
static const std::string comesttype_DRINK ("DRINK") static
Referenced by Character::can_eat(), eat(), Character::modify_morale(), and Character::will_eat().
comesttype_FOOD()
static const std::string comesttype_FOOD ("FOOD") static
Referenced by Character::can_eat(), eat(), Character::modify_morale(), and Character::will_eat().
compute_default_effective_kcal()
static int compute_default_effective_kcal (const item & comest, const Character & you, const cata::flat_set< flag_id > & extra_flags = {}) static
Definition at line 197 of file consumption.cpp.
                                                    {} )
 {
     if( !comest.get_comestible() ) {
         return 0;
     }
     // As float to avoid rounding too many times
     float kcal = comest.get_comestible()->default_nutrition.kcal();
     // Many raw foods give less calories, as your body has expends more energy digesting them.
     bool cooked = comest.has_flag( flag_COOKED ) || extra_flags.count( flag_COOKED );
     if( comest.has_flag( flag_RAW ) && !cooked ) {
         kcal *= 0.75f;
     }
     if( you.has_trait( trait_CARNIVORE ) && comest.has_flag( flag_CARNIVORE_OK ) &&
         comest.has_any_flag( carnivore_blacklist ) ) {
         // TODO: Comment pizza scrapping
         kcal *= 0.5f;
     }
     const float relative_rot = comest.get_relative_rot();
     // Saprophages get full nutrition from rotting food
     if( relative_rot > 1.0f && !you.has_trait( trait_SAPROPHAGE ) ) {
         // everyone else only gets a portion of the nutrition
         // Scaling linearly from 100% at just-rotten to 0 at halfway-rotten-away
         const float rottedness = clamp( 2 * relative_rot - 2.0f, 0.1f, 1.0f );
         kcal *= ( 1.0f - rottedness );
     }
     kcal = you.enchantment_cache->modify_value( enchant_vals::mod::KCAL, kcal );
     return static_cast<int>( kcal );
 }
compute_default_effective_nutrients()
static nutrients compute_default_effective_nutrients (const item & comest, const Character & you, const cata::flat_set< flag_id > & extra_flags = {}) static
Definition at line 278 of file consumption.cpp.
                                                                          {} )
 {
     nutrients ret;
     // Multiply by 1000 to get it in calories
     ret.calories = compute_default_effective_kcal( comest, you, extra_flags ) * 1000;
     for( const std::pair<const vitamin_id, int> &vit :  compute_default_effective_vitamins( comest,
             you ) ) {
         ret.set_vitamin( vit.first, vit.second );
     }
     return ret;
 }
Referenced by Character::compute_effective_nutrients(), and Character::compute_nutrient_range().
compute_default_effective_vitamins()
static std::map<vitamin_id, int> compute_default_effective_vitamins (const item & it, const Character & you) static
Definition at line 235 of file consumption.cpp.
 {
     if( !it.get_comestible() ) {
         return {};
     }
     std::map<vitamin_id, int> res = it.get_comestible()->default_nutrition.vitamins();
     // for actual vitamins convert RDA to a internal value
     for( std::pair<const vitamin_id, int> &vit : res ) {
         if( vit.first->type() != vitamin_type::VITAMIN ) {
             continue;
         }
         vit.second = vit.first->RDA_to_default( vit.second );
     }
     for( const trait_id &trait : you.get_mutations() ) {
         const mutation_branch &mut = trait.obj();
         // make sure to iterate over every material defined for vitamin absorption
         // TODO: put this loop into a function and utilize it again for bionics
         for( const auto &mat : mut.vitamin_absorb_multi ) {
             // this is where we are able to check if the food actually is changed by the trait
             if( mat.first == material_all || it.made_of( mat.first ) ) {
                 const std::map<vitamin_id, double> &mat_vit_map = mat.second;
                 for( auto &vit : res ) {
                     auto vit_factor = mat_vit_map.find( vit.first );
                     if( vit_factor != mat_vit_map.end() ) {
                         vit.second *= vit_factor->second;
                     }
                 }
             }
         }
     }
     for( std::pair<const vitamin_id, int> &vit : res ) {
         vit.second = you.enchantment_cache->modify_value( enchant_vals::mod::VITAMIN_ABSORB_MOD,
                      vit.second );
     }
     return res;
 }
References Character::enchantment_cache, item::get_comestible(), Character::get_mutations(), item::made_of(), material_all, VITAMIN, enchant_vals::VITAMIN_ABSORB_MOD, and mutation_branch::vitamin_absorb_multi.
consume_med()
static bool consume_med (item & target, Character & you) static
Consume medication.
Returns
true if item consumed.
Definition at line 1807 of file consumption.cpp.
 {
     if( !target.is_medication() ) {
         return false;
     }
     const itype_id tool_type = target.get_comestible()->tool;
     const itype *req_tool = item::find_type( tool_type );
     if( req_tool->tool ) {
         if( !( you.has_amount( tool_type, 1 ) &&
                you.has_charges( tool_type, req_tool->tool->charges_per_use ) ) ) {
             you.add_msg_if_player( m_info, _( "You need a %s to consume that!" ), req_tool->nname( 1 ) );
             return false;
         }
         you.use_charges( tool_type, req_tool->tool->charges_per_use );
     }
     int amount_used = 1;
     if( target.type->has_use() ) {
         amount_used = target.type->invoke( &you, target, you.pos() ).value_or( 0 );
         if( amount_used <= 0 ) {
             return false;
         }
     }
     // TODO: Get the target it was used on
     // Otherwise injecting someone will give us addictions etc.
     if( target.has_flag( flag_NO_INGEST ) ) {
         const islot_comestible &comest = *target.get_comestible();
         // Assume that parenteral meds don't spoil, so don't apply rot
         you.modify_health( comest );
         you.modify_stimulation( comest );
         you.modify_sleepiness( comest );
         you.modify_addiction( comest );
         you.modify_morale( target );
         activate_consume_eocs( you, target );
     } else {
         // Take by mouth
         if( !you.consume_effects( target ) ) {
             activate_consume_eocs( you, target );
         }
     }
     if( target.count_by_charges() ) {
         target.mod_charges( -amount_used );
     }
     return true;
 }
References _, activate_consume_eocs(), Character::add_msg_if_player(), Character::consume_effects(), item::count_by_charges(), item::find_type(), flag_NO_INGEST, item::get_comestible(), visitable::has_amount(), Character::has_charges(), item::has_flag(), itype::has_use(), itype::invoke(), item::is_medication(), m_info, item::mod_charges(), Character::modify_addiction(), Character::modify_health(), Character::modify_morale(), Character::modify_sleepiness(), Character::modify_stimulation(), itype::nname(), Creature::pos(), itype::tool, item::type, and Character::use_charges().
Referenced by Character::consume().
eat()
static bool eat (item & food, Character & you, bool force) static
Eat a comestible.
Returns
true if item consumed.
Definition at line 1031 of file consumption.cpp.
 {
     if( !food.is_food() ) {
         return false;
     }
     const auto ret = force ? you.can_eat( food ) : you.will_eat( food, you.is_avatar() );
     if( !ret.success() ) {
         return false;
     }
     int charges_used = 0;
     if( food.type->has_use() ) {
         if( !food.type->can_use( "PETFOOD" ) ) {
             charges_used = food.type->invoke( &you, food, you.pos() ).value_or( 0 );
             if( charges_used <= 0 ) {
                 return false;
             }
         }
     }
     // Note: the block below assumes we decided to eat it
     // No coming back from here
     if( food.is_container() ) {
         food.spill_contents( you );
     }
     const bool hibernate = you.has_active_mutation( trait_HIBERNATE );
     const int nutr = you.nutrition_for( food );
     const int quench = food.get_comestible()->quench;
     const bool spoiled = food.rotten();
     // The item is solid food
     const bool chew = food.get_comestible()->comesttype == comesttype_FOOD ||
                       food.has_flag( flag_USE_EAT_VERB );
     // This item is a drink and not a solid food (and not a thick soup)
     const bool drinkable = !chew && food.get_comestible()->comesttype == comesttype_DRINK;
     // If neither of the above is true then it's a drug and shouldn't get mealtime penalty/bonus
     if( hibernate &&
         ( you.get_hunger() > -60 && you.get_thirst() > -60 ) &&
         ( you.get_hunger() - nutr < -60 || you.get_thirst() - quench < -60 ) ) {
         you.add_msg_if_player(
             _( "You've begun stockpiling calories and liquid for hibernation.  You get the feeling that you should prepare for bed, just in case, but you're hungry again, and you could eat a whole week's worth of food RIGHT NOW." ) );
     }
     const bool will_vomit = you.stomach.stomach_remaining( you ) < food.volume() &&
                             rng( units::to_milliliter( you.stomach.capacity( you ) ) / 2,
                                  units::to_milliliter( you.stomach.contains() ) ) > units::to_milliliter(
                                 you.stomach.capacity( you ) );
     const bool saprophage = you.has_trait( trait_SAPROPHAGE );
     if( spoiled && !saprophage ) {
         you.add_msg_if_player( m_bad, _( "Ick, this %s doesn't taste so good" ), food.tname() );
         if( !you.has_flag( json_flag_IMMUNE_SPOIL ) ) {
             you.add_effect( effect_foodpoison, rng( 6_minutes, ( nutr + 1 ) * 6_minutes ) );
         }
     } else if( spoiled && saprophage ) {
         you.add_msg_if_player( m_good, _( "Mmm, this %s tastes delicious" ), food.tname() );
     }
     if( !you.consume_effects( food ) ) {
         // Already consumed by using `food.type->invoke`?
         if( charges_used > 0 ) {
             if( food.count_by_charges() ) {
                 food.mod_charges( -charges_used );
             }
             return true;
         }
         return false;
     }
     if( food.count_by_charges() ) {
         food.mod_charges( -1 );
     }
     const bool amorphous = you.has_trait( trait_AMORPHOUS );
     // If it's poisonous... poison us.
     // TODO: Move this to a flag
     if( food.poison > 0 &&
         !you.has_trait( trait_EATDEAD ) ) {
         if( food.poison >= rng( 2, 4 ) ) {
             you.add_effect( effect_poison, food.poison * 10_minutes );
         }
         you.add_effect( effect_foodpoison, food.poison * 30_minutes );
     }
     if( food.has_flag( flag_HIDDEN_HALLU ) ) {
         if( !you.has_effect( effect_hallu ) ) {
             you.add_effect( effect_hallu, 6_hours );
         }
     }
     if( amorphous ) {
         you.add_msg_player_or_npc( _( "You assimilate your %s." ), _( "<npcname> assimilates a %s." ),
                                    food.tname() );
     } else if( drinkable ) {
         if( you.has_trait( trait_SCHIZOPHRENIC ) &&
             !you.has_effect( effect_took_thorazine ) && one_in( 50 ) && !spoiled && food.goes_bad() &&
             you.is_avatar() ) {
             add_msg( m_bad, _( "Ick, this %s (rotten) doesn't taste so good" ), food.tname() );
             add_msg( _( "You drink your %s (rotten)." ), food.tname() );
         } else {
             you.add_msg_player_or_npc( _( "You drink your %s." ), _( "<npcname> drinks a %s." ),
                                        food.tname() );
         }
     } else if( chew ) {
         if( you.has_trait( trait_SCHIZOPHRENIC ) &&
             !you.has_effect( effect_took_thorazine ) && one_in( 50 ) && !spoiled && food.goes_bad() &&
             you.is_avatar() ) {
             add_msg( m_bad, _( "Ick, this %s (rotten) doesn't taste so good" ), food.tname() );
             add_msg( _( "You eat your %s (rotten)." ), food.tname() );
         } else {
             you.add_msg_player_or_npc( _( "You eat your %s." ), _( "<npcname> eats a %s." ),
                                        food.tname() );
         }
     }
     if( item::find_type( food.get_comestible()->tool )->tool ) {
         // Tools like lighters get used
         you.use_charges( food.get_comestible()->tool, 1 );
     }
     if( you.has_active_bionic( bio_taste_blocker ) && food.get_comestible_fun() < 0 &&
         you.get_power_level() > units::from_kilojoule( static_cast<std::int64_t>( std::abs(
                     food.get_comestible_fun() ) ) ) ) {
         you.mod_power_level( units::from_kilojoule( static_cast<std::int64_t>
                              ( food.get_comestible_fun() ) ) );
     }
     if( food.has_flag( flag_FUNGAL_VECTOR ) && !you.has_trait( trait_M_IMMUNE ) ) {
         you.add_effect( effect_fungus, 1_turns, true );
     }
     // The fun changes for these effects are applied in fun_for().
     if( food.has_flag( flag_MUSHY ) ) {
         you.add_msg_if_player( m_bad,
                                _( "You try to ignore its mushy texture, but it leaves you with an awful aftertaste." ) );
     }
     if( food.get_comestible_fun() > 0 ) {
         if( you.has_effect( effect_common_cold ) ) {
             you.add_msg_if_player( m_bad, _( "You can't taste much of anything with this cold." ) );
         }
         if( you.has_effect( effect_flu ) ) {
             you.add_msg_if_player( m_bad, _( "You can't taste much of anything with this flu." ) );
         }
     }
     // Chance to become parasitised
     if( !will_vomit && !you.has_flag( json_flag_PARAIMMUNE ) ) {
         if( food.get_comestible()->parasites > 0 && !food.has_flag( flag_NO_PARASITES ) &&
             one_in( food.get_comestible()->parasites ) && ( !food.has_flag( flag_HEMOVORE_FUN ) ||
                     ( !you.has_flag( json_flag_HEMOVORE ) && !you.has_flag( json_flag_BLOODFEEDER ) ) ) ) {
             switch( rng( 0, 3 ) ) {
                 case 0:
                     if( !you.has_trait( trait_EATHEALTH ) ) {
                         you.add_effect( effect_tapeworm, 1_turns, true );
                     }
                     break;
                 case 1:
                     if( !you.has_trait( trait_ACIDBLOOD ) ) {
                         you.add_effect( effect_bloodworms, 1_turns, true );
                     }
                     break;
                 case 2:
                     you.add_effect( effect_brainworms, 1_turns, true );
                     break;
                 case 3:
                     you.add_effect( effect_paincysts, 1_turns, true );
             }
         }
     }
     for( const std::pair<const diseasetype_id, int> &elem : food.get_comestible()->contamination ) {
         if( rng( 1, 100 ) <= elem.second ) {
             you.expose_to_disease( elem.first );
         }
     }
     get_event_bus().send<event_type::character_eats_item>( you.getID(), food.typeId() );
     if( will_vomit ) {
         you.vomit();
     }
     you.consumption_history.emplace_back( food );
     // Clean out consumption_history so it doesn't get bigger than needed.
     while( you.consumption_history.front().time < calendar::turn - 2_days ) {
         you.consumption_history.pop_front();
     }
     you.recoil = MAX_RECOIL;
     return true;
 }
References _, abs(), Creature::add_effect(), add_msg(), Character::add_msg_if_player(), Character::add_msg_player_or_npc(), bio_taste_blocker, Character::can_eat(), itype::can_use(), stomach_contents::capacity(), character_eats_item, iuse::chew(), comesttype_DRINK(), comesttype_FOOD(), Character::consume_effects(), Character::consumption_history, stomach_contents::contains(), item::count_by_charges(), effect_bloodworms, effect_brainworms, effect_common_cold, effect_flu, effect_foodpoison, effect_fungus, effect_hallu, effect_paincysts, effect_poison, effect_tapeworm, effect_took_thorazine, Character::expose_to_disease(), item::find_type(), flag_FUNGAL_VECTOR, flag_HEMOVORE_FUN, flag_HIDDEN_HALLU, flag_MUSHY, flag_NO_PARASITES, flag_USE_EAT_VERB, force, units::from_kilojoule(), item::get_comestible(), item::get_comestible_fun(), get_event_bus(), Character::get_hunger(), Character::get_power_level(), Character::get_thirst(), Character::getID(), item::goes_bad(), Character::has_active_bionic(), Character::has_active_mutation(), Creature::has_effect(), item::has_flag(), Character::has_flag(), Character::has_trait(), itype::has_use(), itype::invoke(), Creature::is_avatar(), item::is_container(), item::is_food(), json_flag_BLOODFEEDER, json_flag_HEMOVORE, json_flag_IMMUNE_SPOIL, json_flag_PARAIMMUNE, m_bad, m_good, MAX_RECOIL, item::mod_charges(), Character::mod_power_level(), Character::nutrition_for(), one_in(), item::poison, Creature::pos(), Character::recoil, cata::hash64_detail::ret, rng(), item::rotten(), event_bus::send(), item::spill_contents(), Character::stomach, stomach_contents::stomach_remaining(), item::tname(), units::to_milliliter(), itype::tool, trait_ACIDBLOOD, trait_AMORPHOUS, trait_EATDEAD, trait_EATHEALTH, trait_HIBERNATE, trait_M_IMMUNE, trait_SAPROPHAGE, trait_SCHIZOPHRENIC, calendar::turn, item::type, item::typeId(), Character::use_charges(), item::volume(), Character::vomit(), and Character::will_eat().
Referenced by Character::consume().
query_consume_ownership()
static bool query_consume_ownership (item & target, Character & p) static
Definition at line 1774 of file consumption.cpp.
 {
     if( !target.is_owned_by( p, true ) ) {
         bool choice = true;
         if( p.get_value( "THIEF_MODE" ) == "THIEF_ASK" ) {
             choice = Pickup::query_thief();
         }
         if( p.get_value( "THIEF_MODE" ) == "THIEF_HONEST" || !choice ) {
             return false;
         }
         std::vector<npc *> witnesses;
         for( npc &elem : g->all_npcs() ) {
             if( rl_dist( elem.pos(), p.pos() ) < MAX_VIEW_DISTANCE && elem.sees( p.pos() ) ) {
                 witnesses.push_back( &elem );
             }
         }
         for( npc *elem : witnesses ) {
             elem->say( "<witnessed_thievery>", 7 );
         }
         if( !witnesses.empty() && target.is_owned_by( p, true ) ) {
             if( p.add_faction_warning( target.get_owner() ) ) {
                 for( npc *elem : witnesses ) {
                     elem->make_angry();
                 }
             }
         }
     }
     return true;
 }
References Character::add_faction_warning(), g, item::get_owner(), Creature::get_value(), item::is_owned_by(), MAX_VIEW_DISTANCE, Creature::pos(), Pickup::query_thief(), and rl_dist().
Referenced by Character::consume().
Variable Documentation
bio_faulty_grossfood
const bionic_id bio_faulty_grossfood("bio_faulty_grossfood") ("bio_faulty_grossfood") static
Referenced by Character::fun_for().
bio_syringe
const bionic_id bio_syringe("bio_syringe") ("bio_syringe") static
Referenced by Character::get_consume_time().
bio_taste_blocker
const bionic_id bio_taste_blocker("bio_taste_blocker") ("bio_taste_blocker") static
Referenced by eat(), and Character::fun_for().
carnivore_blacklist
const std::array<flag_id, 6> carnivore_blacklist static
Initial value:
{{
        json_flag_ALLERGEN_VEGGY, json_flag_ALLERGEN_FRUIT,
        json_flag_ALLERGEN_WHEAT, json_flag_ALLERGEN_NUT,
        json_flag_ALLERGEN_BREAD, json_flag_ALLERGEN_DRIED_VEGETABLE
    }}
Definition at line 186 of file consumption.cpp.
Referenced by Character::can_eat().
effect_bloodworms
const efftype_id effect_bloodworms("bloodworms") ("bloodworms") static
Referenced by eat().
effect_brainworms
const efftype_id effect_brainworms("brainworms") ("brainworms") static
Referenced by eat().
effect_common_cold
const efftype_id effect_common_cold("common_cold") ("common_cold") static
Referenced by eat(), and Character::fun_for().
effect_flu
const efftype_id effect_flu("flu") ("flu") static
Referenced by eat(), and Character::fun_for().
effect_foodpoison
const efftype_id effect_foodpoison("foodpoison") ("foodpoison") static
Referenced by eat().
effect_fungus
const efftype_id effect_fungus("fungus") ("fungus") static
Referenced by eat().
effect_hallu
const efftype_id effect_hallu("hallu") ("hallu") static
Referenced by eat().
effect_hunger_engorged
const efftype_id effect_hunger_engorged("hunger_engorged") ("hunger_engorged") static
Referenced by Character::will_eat().
effect_hunger_famished
const efftype_id effect_hunger_famished("hunger_famished") ("hunger_famished") static
Referenced by Character::can_eat().
effect_hunger_full
const efftype_id effect_hunger_full("hunger_full") ("hunger_full") static
Referenced by Character::will_eat().
effect_hunger_near_starving
const efftype_id effect_hunger_near_starving("hunger_near_starving") ("hunger_near_starving") static
Referenced by Character::can_eat().
effect_hunger_starving
const efftype_id effect_hunger_starving("hunger_starving") ("hunger_starving") static
Referenced by Character::can_eat().
effect_nausea
const efftype_id effect_nausea("nausea") ("nausea") static
Referenced by Character::will_eat().
effect_paincysts
const efftype_id effect_paincysts("paincysts") ("paincysts") static
Referenced by eat().
effect_poison
const efftype_id effect_poison("poison") ("poison") static
Referenced by eat().
effect_tapeworm
const efftype_id effect_tapeworm("tapeworm") ("tapeworm") static
Referenced by Character::consume_effects(), and eat().
effect_took_thorazine
const efftype_id effect_took_thorazine("took_thorazine") ("took_thorazine") static
Referenced by eat().
effect_visuals
const efftype_id effect_visuals("visuals") ("visuals") static
Referenced by Character::modify_stimulation().
herbivore_blacklist
const std::array<flag_id, 2> herbivore_blacklist static
Initial value:
{{
        json_flag_ALLERGEN_MEAT, json_flag_ALLERGEN_EGG
    }}
Definition at line 192 of file consumption.cpp.
Referenced by Character::can_eat(), and Character::consume_effects().
item_category_chems
const item_category_id item_category_chems("chems") ("chems") static
Referenced by Character::get_consume_time().
itype_apparatus
const itype_id itype_apparatus("apparatus") ("apparatus") static
Referenced by Character::get_consume_time().
itype_dab_pen_on
const itype_id itype_dab_pen_on("dab_pen_on") ("dab_pen_on") static
Referenced by Character::get_consume_time().
itype_syringe
const itype_id itype_syringe("syringe") ("syringe") static
Referenced by Character::get_consume_time().
json_flag_ALLERGEN_BREAD
const flag_id json_flag_ALLERGEN_BREAD("ALLERGEN_BREAD") ("ALLERGEN_BREAD") static
json_flag_ALLERGEN_CHEESE
const flag_id json_flag_ALLERGEN_CHEESE("ALLERGEN_CHEESE") ("ALLERGEN_CHEESE") static
Referenced by Character::can_eat().
json_flag_ALLERGEN_DRIED_VEGETABLE
const flag_id json_flag_ALLERGEN_DRIED_VEGETABLE("ALLERGEN_DRIED_VEGETABLE") ("ALLERGEN_DRIED_VEGETABLE") static
json_flag_ALLERGEN_EGG
const flag_id json_flag_ALLERGEN_EGG("ALLERGEN_EGG") ("ALLERGEN_EGG") static
Referenced by Character::can_eat().
json_flag_ALLERGEN_FRUIT
const flag_id json_flag_ALLERGEN_FRUIT("ALLERGEN_FRUIT") ("ALLERGEN_FRUIT") static
json_flag_ALLERGEN_MEAT
const flag_id json_flag_ALLERGEN_MEAT("ALLERGEN_MEAT") ("ALLERGEN_MEAT") static
Referenced by Character::can_eat().
json_flag_ALLERGEN_MILK
const flag_id json_flag_ALLERGEN_MILK("ALLERGEN_MILK") ("ALLERGEN_MILK") static
Referenced by Character::can_eat().
json_flag_ALLERGEN_NUT
const flag_id json_flag_ALLERGEN_NUT("ALLERGEN_NUT") ("ALLERGEN_NUT") static
json_flag_ALLERGEN_VEGGY
const flag_id json_flag_ALLERGEN_VEGGY("ALLERGEN_VEGGY") ("ALLERGEN_VEGGY") static
json_flag_ALLERGEN_WHEAT
const flag_id json_flag_ALLERGEN_WHEAT("ALLERGEN_WHEAT") ("ALLERGEN_WHEAT") static
json_flag_ANIMAL_PRODUCT
const flag_id json_flag_ANIMAL_PRODUCT("ANIMAL_PRODUCT") ("ANIMAL_PRODUCT") static
Referenced by Character::can_eat().
json_flag_BLOODFEEDER
const json_character_flag json_flag_BLOODFEEDER("BLOODFEEDER") ("BLOODFEEDER") static
Referenced by eat(), Character::fun_for(), Character::modify_morale(), and Character::will_eat().
json_flag_CANNIBAL
const json_character_flag json_flag_CANNIBAL("CANNIBAL") ("CANNIBAL") static
Referenced by Character::modify_morale().
json_flag_HEMOVORE
const json_character_flag json_flag_HEMOVORE("HEMOVORE") ("HEMOVORE") static
Referenced by eat(), Character::fun_for(), Character::modify_morale(), and Character::will_eat().
json_flag_IMMUNE_SPOIL
const json_character_flag json_flag_IMMUNE_SPOIL("IMMUNE_SPOIL") ("IMMUNE_SPOIL") static
Referenced by Character::consume_effects(), and eat().
json_flag_NUMB
const json_character_flag json_flag_NUMB("NUMB") ("NUMB") static
Referenced by Character::modify_morale().
json_flag_PARAIMMUNE
const json_character_flag json_flag_PARAIMMUNE("PARAIMMUNE") ("PARAIMMUNE") static
Referenced by eat(), and Character::will_eat().
json_flag_PRED1
const json_character_flag json_flag_PRED1("PRED1") ("PRED1") static
Referenced by Character::modify_morale().
json_flag_PRED2
const json_character_flag json_flag_PRED2("PRED2") ("PRED2") static
Referenced by Character::modify_morale().
json_flag_PRED3
const json_character_flag json_flag_PRED3("PRED3") ("PRED3") static
Referenced by Character::modify_morale().
json_flag_PRED4
const json_character_flag json_flag_PRED4("PRED4") ("PRED4") static
Referenced by Character::modify_morale().
json_flag_PSYCHOPATH
const json_character_flag json_flag_PSYCHOPATH("PSYCHOPATH") ("PSYCHOPATH") static
Referenced by Character::modify_morale(), and Character::will_eat().
json_flag_SAPIOVORE
const json_character_flag json_flag_SAPIOVORE("SAPIOVORE") ("SAPIOVORE") static
Referenced by Character::modify_morale(), and Character::will_eat().
json_flag_SPIRITUAL
const json_character_flag json_flag_SPIRITUAL("SPIRITUAL") ("SPIRITUAL") static
Referenced by Character::modify_morale().
json_flag_STRICT_HUMANITARIAN
const json_character_flag json_flag_STRICT_HUMANITARIAN("STRICT_HUMANITARIAN") ("STRICT_HUMANITARIAN") static
Referenced by Character::modify_morale(), and Character::will_eat().
material_all
const material_id material_all("all") ("all") static
Referenced by compute_default_effective_vitamins().
mon_player_blob
const mtype_id mon_player_blob("mon_player_blob") ("mon_player_blob") static
Referenced by Character::consume_effects().
mutation_category_URSINE
const mutation_category_id mutation_category_URSINE("URSINE") ("URSINE") static
Referenced by Character::modify_morale().
skill_cooking
const skill_id skill_cooking("cooking") ("cooking") static
Referenced by Character::can_estimate_rot().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by Character::can_estimate_rot().
trait_ACIDBLOOD
const trait_id trait_ACIDBLOOD("ACIDBLOOD") ("ACIDBLOOD") static
Referenced by eat().
trait_AMORPHOUS
const trait_id trait_AMORPHOUS("AMORPHOUS") ("AMORPHOUS") static
Referenced by eat().
trait_ANTIFRUIT
const trait_id trait_ANTIFRUIT("ANTIFRUIT") ("ANTIFRUIT") static
Referenced by Character::allergy_type().
trait_ANTIJUNK
const trait_id trait_ANTIJUNK("ANTIJUNK") ("ANTIJUNK") static
Referenced by Character::allergy_type().
trait_ANTIWHEAT
const trait_id trait_ANTIWHEAT("ANTIWHEAT") ("ANTIWHEAT") static
Referenced by Character::allergy_type().
trait_CARNIVORE
const trait_id trait_CARNIVORE("CARNIVORE") ("CARNIVORE") static
Referenced by Character::can_eat(), Character::modify_morale(), and Character::will_eat().
trait_EATDEAD
const trait_id trait_EATDEAD("EATDEAD") ("EATDEAD") static
Referenced by eat().
trait_EATHEALTH
const trait_id trait_EATHEALTH("EATHEALTH") ("EATHEALTH") static
Referenced by eat().
trait_GOURMAND
const trait_id trait_GOURMAND("GOURMAND") ("GOURMAND") static
Referenced by Character::fun_for().
trait_HERBIVORE
const trait_id trait_HERBIVORE("HERBIVORE") ("HERBIVORE") static
Referenced by Character::can_eat(), and Character::consume_effects().
trait_HIBERNATE
const trait_id trait_HIBERNATE("HIBERNATE") ("HIBERNATE") static
Referenced by Character::consume_effects(), and eat().
trait_LACTOSE
const trait_id trait_LACTOSE("LACTOSE") ("LACTOSE") static
Referenced by Character::allergy_type().
trait_M_DEPENDENT
const trait_id trait_M_DEPENDENT("M_DEPENDENT") ("M_DEPENDENT") static
Referenced by Character::can_eat().
trait_M_IMMUNE
const trait_id trait_M_IMMUNE("M_IMMUNE") ("M_IMMUNE") static
Referenced by eat().
trait_MEATARIAN
const trait_id trait_MEATARIAN("MEATARIAN") ("MEATARIAN") static
Referenced by Character::allergy_type().
trait_PICKYEATER
const trait_id trait_PICKYEATER("PICKYEATER") ("PICKYEATER") static
Referenced by Character::can_eat().
trait_PROBOSCIS
const trait_id trait_PROBOSCIS("PROBOSCIS") ("PROBOSCIS") static
Referenced by Character::can_eat().
trait_PROJUNK
const trait_id trait_PROJUNK("PROJUNK") ("PROJUNK") static
Referenced by Character::modify_morale().
trait_PROJUNK2
const trait_id trait_PROJUNK2("PROJUNK2") ("PROJUNK2") static
Referenced by Character::consume_effects(), and Character::modify_morale().
trait_RUMINANT
const trait_id trait_RUMINANT("RUMINANT") ("RUMINANT") static
Referenced by Character::can_eat(), and Character::consume_effects().
trait_SAPROPHAGE
const trait_id trait_SAPROPHAGE("SAPROPHAGE") ("SAPROPHAGE") static
Referenced by eat(), Character::fun_for(), Character::modify_morale(), and Character::will_eat().
trait_SAPROVORE
const trait_id trait_SAPROVORE("SAPROVORE") ("SAPROVORE") static
Referenced by Character::fun_for(), and Character::will_eat().
trait_SCHIZOPHRENIC
const trait_id trait_SCHIZOPHRENIC("SCHIZOPHRENIC") ("SCHIZOPHRENIC") static
Referenced by eat().
trait_SLIMESPAWNER
const trait_id trait_SLIMESPAWNER("SLIMESPAWNER") ("SLIMESPAWNER") static
Referenced by Character::consume_effects().
trait_SPIRITUAL
const trait_id trait_SPIRITUAL("SPIRITUAL") ("SPIRITUAL") static
Referenced by Character::modify_morale().
trait_STIMBOOST
const trait_id trait_STIMBOOST("STIMBOOST") ("STIMBOOST") static
Referenced by Character::modify_stimulation().
trait_TABLEMANNERS
const trait_id trait_TABLEMANNERS("TABLEMANNERS") ("TABLEMANNERS") static
Referenced by Character::modify_morale().
trait_THRESH_BIRD
const trait_id trait_THRESH_BIRD("THRESH_BIRD") ("THRESH_BIRD") static
Referenced by Character::can_eat().
trait_THRESH_CATTLE
const trait_id trait_THRESH_CATTLE("THRESH_CATTLE") ("THRESH_CATTLE") static
Referenced by Character::can_eat().
trait_THRESH_FELINE
const trait_id trait_THRESH_FELINE("THRESH_FELINE") ("THRESH_FELINE") static
Referenced by Character::can_eat(), and Character::fun_for().
trait_THRESH_LUPINE
const trait_id trait_THRESH_LUPINE("THRESH_LUPINE") ("THRESH_LUPINE") static
Referenced by Character::can_eat(), and Character::fun_for().
trait_THRESH_MOUSE
const trait_id trait_THRESH_MOUSE("THRESH_MOUSE") ("THRESH_MOUSE") static
Referenced by Character::can_eat().
trait_THRESH_PLANT
const trait_id trait_THRESH_PLANT("THRESH_PLANT") ("THRESH_PLANT") static
Referenced by Character::consume_effects().
trait_THRESH_RABBIT
const trait_id trait_THRESH_RABBIT("THRESH_RABBIT") ("THRESH_RABBIT") static
Referenced by Character::can_eat().
trait_THRESH_RAT
const trait_id trait_THRESH_RAT("THRESH_RAT") ("THRESH_RAT") static
Referenced by Character::can_eat().
trait_THRESH_URSINE
const trait_id trait_THRESH_URSINE("THRESH_URSINE") ("THRESH_URSINE") static
Referenced by Character::modify_morale().
trait_UNDINE_SLEEP_WATER
const trait_id trait_UNDINE_SLEEP_WATER("UNDINE_SLEEP_WATER") ("UNDINE_SLEEP_WATER") static
Referenced by Character::can_eat(), and Character::consume().
trait_VEGAN
const trait_id trait_VEGAN("VEGAN") ("VEGAN") static
Referenced by Character::can_eat().
trait_VEGETARIAN
const trait_id trait_VEGETARIAN("VEGETARIAN") ("VEGETARIAN") static
Referenced by Character::allergy_type().
trait_WATERSLEEP
const trait_id trait_WATERSLEEP("WATERSLEEP") ("WATERSLEEP") static
Referenced by Character::can_eat(), and Character::consume().
vitamin_human_flesh_vitamin
const vitamin_id vitamin_human_flesh_vitamin("human_flesh_vitamin") ("human_flesh_vitamin") static
Referenced by Character::modify_morale(), and Character::will_eat().