Cataclysm DDA: src/coordinates.cpp File Reference
coordinates.cpp File Reference
#include "coordinates.h"
#include <cstdlib>
Functions
point_rel_ms rebase_rel (point_omt_ms p)
point_omt_ms rebase_omt (point_rel_ms p)
point_bub_ms rebase_bub (point_rel_ms p)
Function Documentation
rebase_bub()
tripoint_bub_ms rebase_bub (point_rel_ms p)
Definition at line 49 of file coordinates.cpp.
 {
     return point_bub_ms( p.raw() );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
Referenced by tinymap::add_spawn(), and tinymap::place_spawns().
rebase_omt()
tripoint_omt_ms rebase_omt (point_rel_ms p)
Definition at line 45 of file coordinates.cpp.
 {
     return point_omt_ms( p.raw() );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
rebase_rel()
tripoint_rel_ms rebase_rel (point_omt_ms p)
Definition at line 37 of file coordinates.cpp.
 {
     return point_rel_ms( p.raw() );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().