Cataclysm DDA: src/coordinates.h File Reference
coordinates.h File Reference
#include <functional>
#include <iosfwd>
#include <iterator>
#include <string>
#include <tuple>
#include <type_traits>
#include <utility>
#include <vector>
#include "coordinate_conversions.h"
#include "cuboid_rectangle.h"
#include "debug.h"
#include "game_constants.h"
#include "line.h"
#include "point.h"
Classes
class coords::coord_point_base< Point >
A generic coordinate-type-safe point.
class coords::coord_point_mut< Point, Subpoint, InBounds >
class coords::coord_point_mut< Point, Subpoint, true >
class coords::coord_point< Point, Origin, Scale, InBounds >
struct coords::project_to_impl< ScaleUp, 0, ResultScale, InBounds >
struct coords::project_to_impl< 0, ScaleDown, ResultScale, false >
struct coords::project_to_impl< 0, ScaleDown, ResultScale, true >
struct coords::remainder_inbounds< Point, RemainderOrigin, SourceScale, InBounds >
struct coords::remainder_inbounds< Point, origin::submap, scale::map_square, InBounds >
struct coords::quotient_remainder_helper< Origin, CoarseScale, FineScale, InBounds >
struct coords::quotient_remainder_point< Origin, CoarseScale, FineScale, InBounds >
struct coords::quotient_remainder_tripoint< Origin, CoarseScale, FineScale, InBounds >
struct std::hash< coords::coord_point< Point, Origin, Scale, InBounds > >
struct real_coords
Namespaces
coords
Macros
#define CATA_SRC_COORDINATES_H
Typedefs
template<typename Point , origin RemainderOrigin, scale SourceScale, bool InBounds>
using coords::remainder_inbounds_t = typename remainder_inbounds< Point, RemainderOrigin, SourceScale, InBounds >::type
using point_rel_ms = coords::coord_point< point, coords::origin::relative, coords::ms >
Typedefs for point types with coordinate mnemonics.
using point_abs_ms = coords::coord_point< point, coords::origin::abs, coords::ms >
using point_sm_ms = coords::coord_point< point, coords::origin::submap, coords::ms >
using point_sm_ms_ib = coords::coord_point< point, coords::origin::submap, coords::ms, true >
using point_omt_ms = coords::coord_point< point, coords::origin::overmap_terrain, coords::ms >
using point_bub_ms = coords::coord_point< point, coords::origin::reality_bubble, coords::ms >
using point_bub_ms_ib = coords::coord_point< point, coords::origin::reality_bubble, coords::ms, true >
using point_rel_sm = coords::coord_point< point, coords::origin::relative, coords::sm >
using point_abs_sm = coords::coord_point< point, coords::origin::abs, coords::sm >
using point_omt_sm = coords::coord_point< point, coords::origin::overmap_terrain, coords::sm >
using point_om_sm = coords::coord_point< point, coords::origin::overmap, coords::sm >
using point_bub_sm = coords::coord_point< point, coords::origin::reality_bubble, coords::sm >
using point_bub_sm_ib = coords::coord_point< point, coords::origin::reality_bubble, coords::sm, true >
using point_rel_omt = coords::coord_point< point, coords::origin::relative, coords::omt >
using point_abs_omt = coords::coord_point< point, coords::origin::abs, coords::omt >
using point_om_omt = coords::coord_point< point, coords::origin::overmap, coords::omt >
using point_abs_seg = coords::coord_point< point, coords::origin::abs, coords::seg >
using point_rel_om = coords::coord_point< point, coords::origin::relative, coords::om >
using point_abs_om = coords::coord_point< point, coords::origin::abs, coords::om >
using tripoint_rel_ms = coords::coord_point< tripoint, coords::origin::relative, coords::ms >
using tripoint_abs_ms = coords::coord_point< tripoint, coords::origin::abs, coords::ms >
using tripoint_sm_ms = coords::coord_point< tripoint, coords::origin::submap, coords::ms >
using tripoint_sm_ms_ib = coords::coord_point< tripoint, coords::origin::submap, coords::ms, true >
using tripoint_omt_ms = coords::coord_point< tripoint, coords::origin::overmap_terrain, coords::ms >
using tripoint_bub_ms = coords::coord_point< tripoint, coords::origin::reality_bubble, coords::ms >
using tripoint_bub_ms_ib = coords::coord_point< tripoint, coords::origin::reality_bubble, coords::ms, true >
using tripoint_rel_sm = coords::coord_point< tripoint, coords::origin::relative, coords::sm >
using tripoint_abs_sm = coords::coord_point< tripoint, coords::origin::abs, coords::sm >
using tripoint_om_sm = coords::coord_point< tripoint, coords::origin::overmap, coords::sm >
using tripoint_bub_sm = coords::coord_point< tripoint, coords::origin::reality_bubble, coords::sm >
using tripoint_bub_sm_ib = coords::coord_point< tripoint, coords::origin::reality_bubble, coords::sm, true >
using tripoint_rel_omt = coords::coord_point< tripoint, coords::origin::relative, coords::omt >
using tripoint_abs_omt = coords::coord_point< tripoint, coords::origin::abs, coords::omt >
using tripoint_om_omt = coords::coord_point< tripoint, coords::origin::overmap, coords::omt >
using tripoint_abs_seg = coords::coord_point< tripoint, coords::origin::abs, coords::seg >
using tripoint_abs_om = coords::coord_point< tripoint, coords::origin::abs, coords::om >
Enumerations
enum class coords::scale {
coords::map_square , coords::submap , coords::overmap_terrain , coords::segment ,
coords::overmap , coords::vehicle
}
enum class coords::origin {
coords::relative , coords::abs , coords::submap , coords::overmap_terrain ,
coords::overmap , coords::reality_bubble
}
Functions
constexpr int coords::map_squares_per (scale s)
constexpr origin coords::origin_from_scale (scale s)
constexpr scale coords::scale_from_origin (origin o)
template<typename Point , origin Origin, scale Scale>
constexpr coord_point< Point, Origin, Scale > & coords::operator+= (coord_point< Point, Origin, Scale > &me, const coord_point< Point, origin::relative, Scale > &r)
template<typename Point , origin Origin, scale Scale>
constexpr coord_point< Point, Origin, Scale > & coords::operator-= (coord_point< Point, Origin, Scale > &me, const coord_point< Point, origin::relative, Scale > &r)
template<typename Point , origin Origin, scale Scale>
constexpr coord_point< Point, Origin, Scale > & coords::operator+= (coord_point< Point, Origin, Scale > &me, const point &r)
template<typename Point , origin Origin, scale Scale>
constexpr coord_point< Point, Origin, Scale > & coords::operator-= (coord_point< Point, Origin, Scale > &me, const point &r)
template<typename Point , origin Origin, scale Scale>
constexpr coord_point< Point, Origin, Scale > & coords::operator+= (coord_point< Point, Origin, Scale > &me, const tripoint &r)
template<typename Point , origin Origin, scale Scale>
constexpr coord_point< Point, Origin, Scale > & coords::operator-= (coord_point< Point, Origin, Scale > &me, const tripoint &r)
template<typename Point , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds>
constexpr bool coords::operator== (const coord_point< Point, Origin, Scale, LhsInBounds > &l, const coord_point< Point, Origin, Scale, RhsInBounds > &r)
template<typename Point , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds>
constexpr bool coords::operator!= (const coord_point< Point, Origin, Scale, LhsInBounds > &l, const coord_point< Point, Origin, Scale, RhsInBounds > &r)
template<typename Point , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds>
constexpr bool coords::operator< (const coord_point< Point, Origin, Scale, LhsInBounds > &l, const coord_point< Point, Origin, Scale, RhsInBounds > &r)
template<typename PointL , typename PointR , origin OriginL, scale Scale, bool InBounds>
constexpr auto coords::operator+ (const coord_point< PointL, OriginL, Scale, InBounds > &l, const coord_point< PointR, origin::relative, Scale > &r)
template<typename PointL , typename PointR , origin OriginR, scale Scale, bool InBounds, typename = std::enable_if_t < OriginR != origin::relative >>
constexpr auto coords::operator+ (const coord_point< PointL, origin::relative, Scale > &l, const coord_point< PointR, OriginR, Scale, InBounds > &r)
template<typename PointL , typename PointR , origin OriginL, scale Scale, bool InBounds>
constexpr auto coords::operator- (const coord_point< PointL, OriginL, Scale, InBounds > &l, const coord_point< PointR, origin::relative, Scale > &r)
template<typename PointL , typename PointR , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds, typename = std::enable_if_t < Origin != origin::relative >>
constexpr auto coords::operator- (const coord_point< PointL, Origin, Scale, LhsInBounds > &l, const coord_point< PointR, Origin, Scale, RhsInBounds > &r)
template<typename Point , scale Scale>
constexpr coord_point< Point, origin::relative, Scale > coords::operator* (int l, const coord_point< Point, origin::relative, Scale > &r)
template<typename Point , scale Scale>
constexpr coord_point< Point, origin::relative, Scale > coords::operator* (const coord_point< Point, origin::relative, Scale > &r, int l)
template<typename Point , origin Origin, scale Scale, bool InBounds>
std::ostream & coords::operator<< (std::ostream &os, const coord_point< Point, Origin, Scale, InBounds > &p)
template<typename Point , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds>
constexpr coord_point< Point, Origin, Scale, LhsInBounds &&RhsInBounds > coords::coord_min (const coord_point< Point, Origin, Scale, LhsInBounds > &l, const coord_point< Point, Origin, Scale, RhsInBounds > &r)
template<typename Point , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds>
constexpr coord_point< Point, Origin, Scale, LhsInBounds &&RhsInBounds > coords::coord_max (const coord_point< Point, Origin, Scale, LhsInBounds > &l, const coord_point< Point, Origin, Scale, RhsInBounds > &r)
template<scale ResultScale, typename Point , origin Origin, scale SourceScale, bool InBounds>
auto coords::project_to (const coord_point< Point, Origin, SourceScale, InBounds > &src)
template<scale ResultScale, origin Origin, scale SourceScale, bool InBounds>
quotient_remainder_point< Origin, ResultScale, SourceScale, InBounds > coords::project_remain (const coord_point< point, Origin, SourceScale, InBounds > &src)
template<scale ResultScale, origin Origin, scale SourceScale, bool InBounds>
quotient_remainder_tripoint< Origin, ResultScale, SourceScale, InBounds > coords::project_remain (const coord_point< tripoint, Origin, SourceScale, InBounds > &src)
template<typename PointL , typename PointR , origin CoarseOrigin, scale CoarseScale, origin FineOrigin, scale FineScale, bool CoarseInBounds, bool FineInBounds>
auto coords::project_combine (const coord_point< PointL, CoarseOrigin, CoarseScale, CoarseInBounds > &coarse, const coord_point< PointR, FineOrigin, FineScale, FineInBounds > &fine)
template<scale FineScale, origin Origin, scale CoarseScale, bool InBounds>
auto coords::project_bounds (const coord_point< point, Origin, CoarseScale, InBounds > &coarse)
template<scale FineScale, origin Origin, scale CoarseScale, bool InBounds>
auto coords::project_bounds (const coord_point< tripoint, Origin, CoarseScale, InBounds > &coarse)
point_rel_ms rebase_rel (point_omt_ms p)
point_omt_ms rebase_omt (point_rel_ms p)
point_bub_ms rebase_bub (point_rel_ms p)
template<typename Point , coords::origin Origin, coords::scale Scale, bool LhsInBounds, bool RhsInBounds>
int square_dist (const coords::coord_point< Point, Origin, Scale, LhsInBounds > &loc1, const coords::coord_point< Point, Origin, Scale, RhsInBounds > &loc2)
template<typename Point , coords::origin Origin, coords::scale Scale, bool LhsInBounds, bool RhsInBounds>
int trig_dist (const coords::coord_point< Point, Origin, Scale, LhsInBounds > &loc1, const coords::coord_point< Point, Origin, Scale, RhsInBounds > &loc2)
template<typename Point , coords::origin Origin, coords::scale Scale, bool LhsInBounds, bool RhsInBounds>
int rl_dist (const coords::coord_point< Point, Origin, Scale, LhsInBounds > &loc1, const coords::coord_point< Point, Origin, Scale, RhsInBounds > &loc2)
template<typename Point , coords::origin Origin, coords::scale Scale, bool LhsInBounds, bool RhsInBounds>
int manhattan_dist (const coords::coord_point< Point, Origin, Scale, LhsInBounds > &loc1, const coords::coord_point< Point, Origin, Scale, RhsInBounds > &loc2)
template<typename Point , coords::origin Origin, coords::scale Scale, bool LhsInBounds, bool RhsInBounds>
int octile_dist (const coords::coord_point< Point, Origin, Scale, LhsInBounds > &loc1, const coords::coord_point< Point, Origin, Scale, RhsInBounds > &loc2, int multiplier=1)
template<typename Point , coords::origin Origin, coords::scale Scale, bool LhsInBounds, bool RhsInBounds>
direction direction_from (const coords::coord_point< Point, Origin, Scale, LhsInBounds > &loc1, const coords::coord_point< Point, Origin, Scale, RhsInBounds > &loc2)
template<typename Point , coords::origin Origin, coords::scale Scale, bool LhsInBounds, bool RhsInBounds>
std::vector< coords::coord_point< Point, Origin, Scale, LhsInBounds &&RhsInBounds > > line_to (const coords::coord_point< Point, Origin, Scale, LhsInBounds > &loc1, const coords::coord_point< Point, Origin, Scale, RhsInBounds > &loc2)
template<typename Point , coords::origin Origin, coords::scale Scale, bool LhsInBounds, bool RhsInBounds>
coords::coord_point< Point, Origin, Scale, LhsInBounds &&RhsInBounds > midpoint (const coords::coord_point< Point, Origin, Scale, LhsInBounds > &loc1, const coords::coord_point< Point, Origin, Scale, RhsInBounds > &loc2)
template<typename Point >
Point midpoint (const inclusive_rectangle< Point > &box)
template<typename Point >
Point midpoint (const half_open_rectangle< Point > &box)
template<typename Tripoint >
Tripoint midpoint (const inclusive_cuboid< Tripoint > &box)
template<typename Tripoint >
Tripoint midpoint (const half_open_cuboid< Tripoint > &box)
template<typename Point , coords::origin Origin, coords::scale Scale>
std::vector< coords::coord_point< Point, Origin, Scale > > closest_points_first (const coords::coord_point< Point, Origin, Scale > &loc, int min_dist, int max_dist)
template<typename Point , coords::origin Origin, coords::scale Scale, bool InBounds>
std::vector< coords::coord_point< Point, Origin, Scale > > closest_points_first (const coords::coord_point< Point, Origin, Scale, InBounds > &loc, int max_dist)
Variables
constexpr scale coords::ms = scale::map_square
constexpr scale coords::sm = scale::submap
constexpr scale coords::omt = scale::overmap_terrain
constexpr scale coords::seg = scale::segment
constexpr scale coords::om = scale::overmap
Macro Definition Documentation
CATA_SRC_COORDINATES_H
#define CATA_SRC_COORDINATES_H
Definition at line 3 of file coordinates.h.
Typedef Documentation
point_abs_ms
using point_abs_ms = coords::coord_point<point, coords::origin::abs, coords::ms>
Definition at line 690 of file coordinates.h.
point_abs_om
using point_abs_om = coords::coord_point<point, coords::origin::abs, coords::om>
Definition at line 709 of file coordinates.h.
point_abs_omt
using point_abs_omt = coords::coord_point<point, coords::origin::abs, coords::omt>
Definition at line 705 of file coordinates.h.
point_abs_seg
using point_abs_seg = coords::coord_point<point, coords::origin::abs, coords::seg>
Definition at line 707 of file coordinates.h.
point_abs_sm
using point_abs_sm = coords::coord_point<point, coords::origin::abs, coords::sm>
Definition at line 698 of file coordinates.h.
point_bub_ms
using point_bub_ms = coords::coord_point<point, coords::origin::reality_bubble, coords::ms>
Definition at line 694 of file coordinates.h.
point_bub_ms_ib
using point_bub_ms_ib = coords::coord_point<point, coords::origin::reality_bubble, coords::ms, true>
Definition at line 695 of file coordinates.h.
point_bub_sm
using point_bub_sm = coords::coord_point<point, coords::origin::reality_bubble, coords::sm>
Definition at line 701 of file coordinates.h.
point_bub_sm_ib
using point_bub_sm_ib = coords::coord_point<point, coords::origin::reality_bubble, coords::sm, true>
Definition at line 702 of file coordinates.h.
point_om_omt
using point_om_omt = coords::coord_point<point, coords::origin::overmap, coords::omt>
Definition at line 706 of file coordinates.h.
point_om_sm
using point_om_sm = coords::coord_point<point, coords::origin::overmap, coords::sm>
Definition at line 700 of file coordinates.h.
point_omt_ms
using point_omt_ms = coords::coord_point<point, coords::origin::overmap_terrain, coords::ms>
Definition at line 693 of file coordinates.h.
point_omt_sm
using point_omt_sm = coords::coord_point<point, coords::origin::overmap_terrain, coords::sm>
Definition at line 699 of file coordinates.h.
point_rel_ms
using point_rel_ms = coords::coord_point<point, coords::origin::relative, coords::ms>
Typedefs for point types with coordinate mnemonics.
Each name is of the form (tri)point_<origin>_<scale>(_ib) where <origin> tells you the context in which the point has meaning, and <scale> tells you what one unit of the point means. The optional "_ib" suffix denotes that the type is guaranteed to be inbounds.
For example: point_omt_ms is the position of a map square within an overmap terrain. tripoint_rel_sm is a relative tripoint submap offset.
For more details see doc/POINTS_COORDINATES.md.
Definition at line 689 of file coordinates.h.
point_rel_om
using point_rel_om = coords::coord_point<point, coords::origin::relative, coords::om>
Definition at line 708 of file coordinates.h.
point_rel_omt
using point_rel_omt = coords::coord_point<point, coords::origin::relative, coords::omt>
Definition at line 704 of file coordinates.h.
point_rel_sm
using point_rel_sm = coords::coord_point<point, coords::origin::relative, coords::sm>
Definition at line 697 of file coordinates.h.
point_sm_ms
using point_sm_ms = coords::coord_point<point, coords::origin::submap, coords::ms>
Definition at line 691 of file coordinates.h.
point_sm_ms_ib
using point_sm_ms_ib = coords::coord_point<point, coords::origin::submap, coords::ms, true>
Definition at line 692 of file coordinates.h.
tripoint_abs_ms
using tripoint_abs_ms = coords::coord_point<tripoint, coords::origin::abs, coords::ms>
Definition at line 712 of file coordinates.h.
tripoint_abs_om
using tripoint_abs_om = coords::coord_point<tripoint, coords::origin::abs, coords::om>
Definition at line 729 of file coordinates.h.
tripoint_abs_omt
using tripoint_abs_omt = coords::coord_point<tripoint, coords::origin::abs, coords::omt>
Definition at line 726 of file coordinates.h.
tripoint_abs_seg
using tripoint_abs_seg = coords::coord_point<tripoint, coords::origin::abs, coords::seg>
Definition at line 728 of file coordinates.h.
tripoint_abs_sm
using tripoint_abs_sm = coords::coord_point<tripoint, coords::origin::abs, coords::sm>
Definition at line 720 of file coordinates.h.
tripoint_bub_ms
using tripoint_bub_ms = coords::coord_point<tripoint, coords::origin::reality_bubble, coords::ms>
Definition at line 716 of file coordinates.h.
tripoint_bub_ms_ib
using tripoint_bub_ms_ib = coords::coord_point<tripoint, coords::origin::reality_bubble, coords::ms, true>
Definition at line 717 of file coordinates.h.
tripoint_bub_sm
using tripoint_bub_sm = coords::coord_point<tripoint, coords::origin::reality_bubble, coords::sm>
Definition at line 722 of file coordinates.h.
tripoint_bub_sm_ib
using tripoint_bub_sm_ib = coords::coord_point<tripoint, coords::origin::reality_bubble, coords::sm, true>
Definition at line 723 of file coordinates.h.
tripoint_om_omt
using tripoint_om_omt = coords::coord_point<tripoint, coords::origin::overmap, coords::omt>
Definition at line 727 of file coordinates.h.
tripoint_om_sm
using tripoint_om_sm = coords::coord_point<tripoint, coords::origin::overmap, coords::sm>
Definition at line 721 of file coordinates.h.
tripoint_omt_ms
using tripoint_omt_ms = coords::coord_point<tripoint, coords::origin::overmap_terrain, coords::ms>
Definition at line 715 of file coordinates.h.
tripoint_rel_ms
using tripoint_rel_ms = coords::coord_point<tripoint, coords::origin::relative, coords::ms>
Definition at line 711 of file coordinates.h.
tripoint_rel_omt
using tripoint_rel_omt = coords::coord_point<tripoint, coords::origin::relative, coords::omt>
Definition at line 725 of file coordinates.h.
tripoint_rel_sm
using tripoint_rel_sm = coords::coord_point<tripoint, coords::origin::relative, coords::sm>
Definition at line 719 of file coordinates.h.
tripoint_sm_ms
using tripoint_sm_ms = coords::coord_point<tripoint, coords::origin::submap, coords::ms>
Definition at line 713 of file coordinates.h.
tripoint_sm_ms_ib
using tripoint_sm_ms_ib = coords::coord_point<tripoint, coords::origin::submap, coords::ms, true>
Definition at line 714 of file coordinates.h.
Function Documentation
closest_points_first() [1/2]
template<typename Point , coords::origin Origin, coords::scale Scale> std::vector<coords::coord_point<Point, Origin, Scale> > closest_points_first (const coords::coord_point< Point, Origin, Scale > & loc, int min_dist, int max_dist)
Definition at line 848 of file coordinates.h.
 {
     std::vector<Point> raw_result = closest_points_first( loc.raw(), min_dist, max_dist );
     std::vector<coords::coord_point<Point, Origin, Scale>> result;
     result.reserve( raw_result.size() );
     std::transform( raw_result.begin(), raw_result.end(), std::back_inserter( result ),
     []( const Point & p ) {
         return coords::coord_point<Point, Origin, Scale>( p );
     } );
     return result;
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
Referenced by map::_add_item_or_charges(), mdefense::acidsplash(), add_fallback_zone(), inventory_selector::add_nearby_items(), npc::avoid_friendly_fire(), mattack::callblobs(), target_ui::choose_initial_target(), closest_points_first(), cycle_action(), iexamine::elevator(), iuse::emf_passive_on(), npc::execute_action(), overmapbuffer::find_all(), overmapbuffer::find_closest(), find_closest_stair(), npc::find_item(), game::find_nearby_items(), start_location::find_player_initial_location(), iexamine::fireplace(), mattack::formblob(), map::get_dir_circle(), Character::get_eligible_containers_for_crafting(), mattack::jackson(), vehicle::leak_fuel(), map_selector::map_selector(), mapgen_lake_shore(), mapgen_ocean_shore(), nearest_passable(), minesweeper_game::new_level(), fixed_overmap_special_data::place(), mutable_overmap_special_data::place(), overmap::place_forest_trailheads(), npc::place_on_map(), overmap::place_specials(), overmap::place_swamps(), points_for_gas_cloud(), npc::see_item_say_smth(), set_item_map(), spell_effect::slime_split_on_death(), spawn_spores(), minesweeper_game::start_game(), try_fuel_fire(), vehicle_selector::vehicle_selector(), vertical_move_destination(), and debug_menu::wishmonster().
closest_points_first() [2/2]
template<typename Point , coords::origin Origin, coords::scale Scale, bool InBounds> std::vector<coords::coord_point<Point, Origin, Scale> > closest_points_first (const coords::coord_point< Point, Origin, Scale, InBounds > & loc, int max_dist)
Definition at line 862 of file coordinates.h.
 {
     return closest_points_first( loc, 0, max_dist );
 }
References closest_points_first().
direction_from()
template<typename Point , coords::origin Origin, coords::scale Scale, bool LhsInBounds, bool RhsInBounds> direction direction_from (const coords::coord_point< Point, Origin, Scale, LhsInBounds > & loc1, const coords::coord_point< Point, Origin, Scale, RhsInBounds > & loc2)
Definition at line 790 of file coordinates.h.
 {
     return direction_from( loc1.raw(), loc2.raw() );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
Referenced by computer_session::action_emerg_ref_center(), npc::assess_danger(), fixed_overmap_special_data::check(), game::check_safe_mode_allowed(), Character::deal_damage(), iuse::directional_antenna(), overmap_ui::draw_ascii(), Character::echo_pulse(), basecamp::faction_display(), npc::faction_display(), fixed_overmap_special_data::finalize(), overmapbuffer::get_description_at(), liquid_handler::get_liquid_target(), vehicle::handle_trap(), game::list_items(), game::list_monsters(), game::mon_info_update(), player_hit_message(), game::point_selection_menu(), sounds::process_sound_markers(), pf::anonymous_namespace{simple_pathfinding.cpp}::reverse_direction(), overmap_ui::search(), Character::search_surroundings(), npc::warn_about(), and game::zones_manager().
line_to()
template<typename Point , coords::origin Origin, coords::scale Scale, bool LhsInBounds, bool RhsInBounds> std::vector< coords::coord_point < Point, Origin, Scale, LhsInBounds &&RhsInBounds > > line_to (const coords::coord_point< Point, Origin, Scale, LhsInBounds > & loc1, const coords::coord_point< Point, Origin, Scale, RhsInBounds > & loc2)
Definition at line 798 of file coordinates.h.
 {
     std::vector<Point> raw_result = line_to( loc1.raw(), loc2.raw() );
     std::vector < coords::coord_point < Point, Origin, Scale, LhsInBounds &&RhsInBounds >> result;
     std::transform( raw_result.begin(), raw_result.end(), std::back_inserter( result ),
     []( const Point & p ) {
         return coords::coord_point < Point, Origin, Scale, LhsInBounds &&
                RhsInBounds >::make_unchecked( p );
     } );
     return result;
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
Referenced by map::add_splatter_trail(), jmapgen_setmap::apply(), Creature::auto_find_hostile_target(), calculate_spell_effect_area(), iuse::camera(), clear_shot_reach(), companion_travel_time_calc(), map::cut_down_tree(), spell_effect::dash(), spell_effect::directed_push(), vehicle::do_towing_move(), draw_line(), draw_trail(), map::find_clear_path(), chop_tree_activity_actor::finish(), map::get_dir_circle(), iuse::grenade_inc_act(), monster::group_bash_skill(), has_obstruction(), vehicle::immediate_path(), in_spell_aoe(), game::knockback(), Creature::longpull(), mapgen_lake_shore(), mapgen_ocean_shore(), MapExtras::mx_casings(), MapExtras::mx_minefield(), MapExtras::mx_portal_in(), om_companion_path(), om_line_mark(), Character::overmap_los(), display::overmap_tile_symbol_color(), MapExtras::place_fumarole(), Character::reach_attack(), editmap::recalc_target(), mattack::riotbot(), scatter_chunks(), mattack::shockstorm(), Messages::dialog::show(), spell_effect_cone_range_override(), spell_effect::spell_effect_line(), basecamp::start_fortifications(), map::straight_route(), spell::targetable_locations(), map::transform_line(), editmap::uber_draw_ter(), game::update_overmap_seen(), target_ui::update_turrets_in_range(), and npc_attack_melee::use().
manhattan_dist()
template<typename Point , coords::origin Origin, coords::scale Scale, bool LhsInBounds, bool RhsInBounds> int manhattan_dist (const coords::coord_point< Point, Origin, Scale, LhsInBounds > & loc1, const coords::coord_point< Point, Origin, Scale, RhsInBounds > & loc2) inline
Definition at line 776 of file coordinates.h.
 {
     return manhattan_dist( loc1.raw(), loc2.raw() );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
Referenced by overmap::build_lab(), overmap::lay_out_connection(), and overmapbuffer::reveal_route().
midpoint() [1/5]
template<typename Point , coords::origin Origin, coords::scale Scale, bool LhsInBounds, bool RhsInBounds> coords::coord_point< Point, Origin, Scale, LhsInBounds &&RhsInBounds > midpoint (const coords::coord_point< Point, Origin, Scale, LhsInBounds > & loc1, const coords::coord_point< Point, Origin, Scale, RhsInBounds > & loc2)
Definition at line 813 of file coordinates.h.
 {
     return coords::coord_point < Point, Origin, Scale, LhsInBounds &&
            RhsInBounds >::make_unchecked( ( loc1.raw() + loc2.raw() ) / 2 );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
Referenced by zone_data::get_center_point(), mapgen_lake_shore(), mapgen_ocean_shore(), midpoint(), start_location::place_player(), overmap::signal_hordes(), activity_handlers::travel_do_turn(), and map::valid_move().
midpoint() [2/5]
template<typename Tripoint > Tripoint midpoint (const half_open_cuboid< Tripoint > & box)
Definition at line 841 of file coordinates.h.
 {
     return midpoint( box.p_min, box.p_max );
 }
References midpoint(), half_open_cuboid< Tripoint, >::p_max, and half_open_cuboid< Tripoint, >::p_min.
midpoint() [3/5]
template<typename Point > Point midpoint (const half_open_rectangle< Point > & box)
Definition at line 828 of file coordinates.h.
 {
     return midpoint( box.p_min, box.p_max );
 }
References midpoint(), half_open_rectangle< Point, >::p_max, and half_open_rectangle< Point, >::p_min.
midpoint() [4/5]
template<typename Tripoint > Tripoint midpoint (const inclusive_cuboid< Tripoint > & box)
Definition at line 834 of file coordinates.h.
 {
     constexpr tripoint one( 1, 1, 1 );
     return midpoint( box.p_min, box.p_max + one );
 }
References midpoint(), inclusive_cuboid< Tripoint, >::p_max, and inclusive_cuboid< Tripoint, >::p_min.
midpoint() [5/5]
template<typename Point > Point midpoint (const inclusive_rectangle< Point > & box)
Definition at line 821 of file coordinates.h.
 {
     constexpr point one( 1, 1 ); // NOLINT(cata-use-named-point-constants)
     return midpoint( box.p_min, box.p_max + one );
 }
References midpoint(), inclusive_rectangle< Point, >::p_max, and inclusive_rectangle< Point, >::p_min.
octile_dist()
template<typename Point , coords::origin Origin, coords::scale Scale, bool LhsInBounds, bool RhsInBounds> int octile_dist (const coords::coord_point< Point, Origin, Scale, LhsInBounds > & loc1, const coords::coord_point< Point, Origin, Scale, RhsInBounds > & loc2, int multiplier = 1) inline
Definition at line 783 of file coordinates.h.
 {
     return octile_dist( loc1.raw(), loc2.raw(), multiplier );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
Referenced by pf::find_overmap_path().
rebase_bub()
point_bub_ms rebase_bub (point_rel_ms p)
Definition at line 49 of file coordinates.cpp.
 {
     return point_bub_ms( p.raw() );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
Referenced by tinymap::add_spawn(), and tinymap::place_spawns().
rebase_omt()
point_omt_ms rebase_omt (point_rel_ms p)
Definition at line 45 of file coordinates.cpp.
 {
     return point_omt_ms( p.raw() );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
rebase_rel()
point_rel_ms rebase_rel (point_omt_ms p)
Definition at line 37 of file coordinates.cpp.
 {
     return point_rel_ms( p.raw() );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
rl_dist()
template<typename Point , coords::origin Origin, coords::scale Scale, bool LhsInBounds, bool RhsInBounds> int rl_dist (const coords::coord_point< Point, Origin, Scale, LhsInBounds > & loc1, const coords::coord_point< Point, Origin, Scale, RhsInBounds > & loc2) inline
Definition at line 769 of file coordinates.h.
 {
     return rl_dist( loc1.raw(), loc2.raw() );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
Referenced by anonymous_namespace{math_parser_diag.cpp}::_filter_character(), anonymous_namespace{math_parser_diag.cpp}::_filter_monster(), anonymous_namespace{item.cpp}::_stacks_location_hint(), mattack::acid_accurate(), npc::act_on_danger_assessment(), computer_session::action_emerg_ref_center(), computer_session::action_irradiator(), Character::activate_bionic(), timed_event::actualize(), inventory_selector::add_nearby_items(), npc::address_player(), npc::alt_attack(), map::apparent_light_at(), map::apparent_light_helper(), map::apply_light_ray(), Character::apply_persistent_morale(), npc::assess_danger(), monster::attitude(), Creature::auto_find_hostile_target(), vehicle::autopilot_patrol(), mattack::boomer(), mattack::boomer_glow(), mattack::browse(), map::build_seen_cache(), calculate_aim_cap(), leap_actor::call(), mon_spellcasting_actor::call(), gun_actor::call(), iuse::camera(), npc::can_do_pulp(), Character::can_hear(), npc::can_move_to(), talk_function::caravan_dist(), cast_horizontal_zlight_segment(), cast_vertical_zlight_segment(), castLight(), game::chat(), Character::check_mount_is_spooked(), Character::check_mount_will_move(), game::check_safe_mode_allowed(), mattack::chickenbot(), map::clear_path(), npc_short_term_cache::closest_enemy_to_friendly_distance(), talk_function::companion_choose(), npc::consume_food_from_camp(), craft_command::continue_prompt_liquids(), mattack::copbot(), map::create_anomaly(), create_radio_tower_reference(), mattack::darkman(), Character::deal_damage(), trap::detect_trap(), spell_effect::directed_push(), Character::disassemble(), anonymous_namespace{math_parser_diag.cpp}::distance_eval(), talker_npc::distance_to_goal(), melee_actor::do_grab(), game::do_regular_action(), vehicle::do_towing_move(), move_items_activity_actor::do_turn(), mattack::doot(), overmap_ui::draw_notes(), overmap_ui::draw_om_sidebar(), draw_throw_aim(), vehicle::drive_to_local_target(), Character::drop(), mattack::dsa_drone_scan(), mattack::eat_carrion(), mattack::eat_food(), eff_fun_fake_common_cold(), eff_fun_fake_flu(), iuse::emf_passive_on(), npc::enough_time_to_reload(), enumerate_objects_around_point(), npc_attack_throw::evaluate(), npc::evaluate_character(), npc_attack_melee::evaluate_critter(), npc_attack_spell::evaluate_tripoint(), npc_attack_gun::evaluate_tripoint(), npc_attack_throw::evaluate_tripoint(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_in_city(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_role_nearby(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), npc::faction_display(), field_processor_fd_acid_vent(), map::find_clear_path(), npc::find_corpse_to_pulp(), npc::find_dangerous_explosives(), npc::find_item(), activity_handlers::find_mount_do_turn(), game::find_nearby_spawn_point(), game::find_or_make_stairs(), Character::fire_gun(), mattack::flame(), explosion_handler::flashbang(), mattack::flesh_golem(), mattack::flesh_tendril(), monster::footsteps(), mattack::fungus(), mattack::fungus_fortify(), mattack::fungus_inject(), map::get_active_items_in_radius(), Character::get_active_moncams(), get_auto_consume_moves(), cardreader_examine_actor::get_cards(), Character::get_crafting_group(), Character::get_crafting_helpers(), map::get_moving_vehicle_targets(), Character::get_mutation_visibility_cap(), get_sorted_tiles_by_distance(), get_stagger_adjust(), Character::get_visible_creatures(), iexamine::getNearFilledGasTank(), talk_function::give_all_aid(), npc::good_escape_direction(), mattack::graze(), monster::group_bash_skill(), mattack::grow_vine(), item::handle_pickup_ownership(), vehicle::handle_potential_theft(), npc::handle_sound(), npc::heal_player(), mattack::howl(), spell::in_aoe(), turret_data::in_range(), in_spell_aoe(), npc::indoor_voice(), iexamine::intercom(), Creature::is_adjacent(), mission::is_complete(), monster::is_fleeing(), overmap::is_marked_dangerous(), spell::is_target_in_range(), Character::is_visible_in_range(), talk_function::lesser_give_all_aid(), item::link_to(), game::list_items(), game::list_monsters(), anonymous_namespace{item_tname.cpp}::location_hint(), mattack::lunge(), mapgen_lake_shore(), mapgen_ocean_shore(), target_handler::mode_turrets(), game::mon_info_update(), mattack::mon_leech_evolution(), anonymous_namespace{do_turn.cpp}::monmove(), monster::move(), npc::move(), avatar_action::move(), npc::move_away_from(), activity_handlers::move_cost_cart(), activity_handlers::move_cost_inv(), npc::move_to(), npc::mug_player(), mattack::multi_robot(), inventory_selector::naturalize_category(), vehicle::no_towing_slack(), mattack::nurse_assist(), mattack::nurse_check_up(), mattack::nurse_operate(), monster::nursebot_operate(), item_location::impl::item_on_map::obtain_cost(), item_location::impl::item_on_vehicle::obtain_cost(), om_companion_path(), om_target_tile(), vehicle::open_or_close(), anonymous_namespace{do_turn.cpp}::overmap_npc_move(), photo_def_for_camera_point(), npc::pick_up_item(), pickveh(), monster::plan(), item::process_link(), monster::process_one_effect(), projectile_attack(), map::propagate_field(), mattack::pull_metal_weapon(), monster::push_to(), query_consume_ownership(), avatar_action::ramp_move(), mattack::ratking(), mattack::rattle(), npc::reach_omt_destination(), item::ready_to_revive(), avatar::rebuild_aim_cache(), editmap::recalc_target(), teleporter_callback::refresh(), vehicle::remote_controlled(), mdefense::return_fire(), mattack::riotbot(), iuse::robotcontrol_can_target(), map::route(), area_expander::run(), game::safe_route_to(), sane_consume_items(), mattack::science(), mattack::searchlight(), Creature::sees(), map::sees(), Character::sees(), monster::set_dest(), vehicle::shed_loose_parts(), mattack::shockstorm(), explosion_handler::shockwave(), explosion_handler::shrapnel(), mattack::shriek(), mattack::shriek_alert(), mattack::shriek_stun(), overmap::signal_hordes(), mattack::slimespring(), outfit::sort_armor(), sound_distance(), map::spawn_monsters_submap_group(), spawn_spores(), mattack::spit_sap(), basecamp::start_clearcut(), basecamp::start_cut_logs(), basecamp::start_fortifications(), game::start_game(), basecamp::start_relay_hide_site(), basecamp::start_setup_hide_site(), vehicle::static_drag(), sting_get_target(), mattack::stretch_attack(), basecamp::survey_field_return(), basecamp::survey_return(), mattack::tankgun(), Target_attributes::Target_attributes(), Character::throw_item(), Character::throwing_dispersion(), mattack::tindalos_teleport(), too_close(), vehicle::tow_cable_too_far(), mattack::triffid_heartbeat(), npc::update_path(), editmap::update_view_with_help(), npc_attack_melee::use(), npc_attack_gun::use(), game::vertical_move(), mattack::vine(), mongroup::wander(), monster::will_reach(), within_target_range(), within_visual_range(), npc::wont_hit_friend(), and game::zones_manager().
square_dist()
template<typename Point , coords::origin Origin, coords::scale Scale, bool LhsInBounds, bool RhsInBounds> int square_dist (const coords::coord_point< Point, Origin, Scale, LhsInBounds > & loc1, const coords::coord_point< Point, Origin, Scale, RhsInBounds > & loc2) inline
Definition at line 755 of file coordinates.h.
 {
     return square_dist( loc1.raw(), loc2.raw() );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
Referenced by activity_on_turn_move_loot(), map::apply_light_ray(), map::build_seen_cache(), overmap::build_slimepit(), leap_actor::call(), can_do_activity_there(), craft_activity_actor::check_if_craft_okay(), deploy_tent_actor::check_intact(), vehicle::autodrive_controller::compute_next_step(), vehicle::damage_all(), Character::defer_move(), direction_suffix(), unload_loot_activity_actor::do_turn(), npc::faction_display(), overmapbuffer::find_closest(), npc::find_corpse_to_pulp(), generic_multi_activity_handler(), generic_multi_activity_locations(), get_best_fire(), get_heat_radiation(), zone_manager::get_near(), zone_manager::get_near_zones(), zone_manager::get_nearest(), overmapbuffer::get_npcs_near(), overmapbuffer::get_npcs_near_omt(), zone_manager::get_point_set_loot(), zone_manager::has_near(), line_to(), aim_activity_actor::load_RAS_weapon(), game::look_around(), map_item_stack::map_item_stack_sort(), Character::on_dodge(), npc_dist_to_player::operator()(), map::pl_sees(), overmap::place_lakes(), overmap::place_oceans(), overmap::place_specials(), rl_dist_exact(), target_ui::set_cursor_pos(), spell_effect::spell_effect_line(), mission_util::target_closest_lab_entrance(), and game::try_get_right_click_action().
trig_dist()
template<typename Point , coords::origin Origin, coords::scale Scale, bool LhsInBounds, bool RhsInBounds> int trig_dist (const coords::coord_point< Point, Origin, Scale, LhsInBounds > & loc1, const coords::coord_point< Point, Origin, Scale, RhsInBounds > & loc2) inline
Definition at line 762 of file coordinates.h.
 {
     return trig_dist( loc1.raw(), loc2.raw() );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
Referenced by overmap::add_mon_group(), map::add_splash(), leap_actor::call(), overmap::connect_closest_points(), draw_circle(), draw_rough_circle(), city::get_distance_from(), get_stagger_adjust(), overmap::lay_out_connection(), monster::move(), MapExtras::mx_portal_in(), overmap::place_building(), overmap::place_mongroups(), points_in_radius_circ(), points_on_radius_circ(), explosion_handler::resonance_cascade(), rl_dist_exact(), area_expander::run(), overmap_ui::search(), slope_of(), vehicle::smash(), map::transform_radius(), map::translate_radius(), and game::zones_manager().