Cataclysm DDA: src/crafting.cpp File Reference
crafting.cpp File Reference
#include "crafting.h"
#include <algorithm>
#include <climits>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <functional>
#include <iterator>
#include <limits>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <utility>
#include <vector>
#include "activity_actor_definitions.h"
#include "activity_handlers.h"
#include "activity_type.h"
#include "avatar.h"
#include "calendar.h"
#include "cata_assert.h"
#include "cata_utility.h"
#include "character.h"
#include "character_attire.h"
#include "character_id.h"
#include "colony.h"
#include "color.h"
#include "coordinates.h"
#include "craft_command.h"
#include "crafting_gui.h"
#include "creature.h"
#include "debug.h"
#include "dialogue.h"
#include "effect_on_condition.h"
#include "enum_traits.h"
#include "enums.h"
#include "faction.h"
#include "flag.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "handle_liquid.h"
#include "inventory.h"
#include "item.h"
#include "item_components.h"
#include "item_location.h"
#include "item_stack.h"
#include "itype.h"
#include "iuse.h"
#include "line.h"
#include "magic_enchantment.h"
#include "map.h"
#include "map_iterator.h"
#include "map_selector.h"
#include "mapdata.h"
#include "messages.h"
#include "morale_types.h"
#include "mutation.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "pimpl.h"
#include "player_activity.h"
#include "pocket_type.h"
#include "point.h"
#include "proficiency.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "requirements.h"
#include "ret_val.h"
#include "rng.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "talker.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vehicle_selector.h"
#include "visitable.h"
#include "vpart_position.h"
#include "weather.h"
Functions
static const std::string flag_AFFECTED_BY_PAIN ("AFFECTED_BY_PAIN")
static const std::string flag_BLIND_EASY ("BLIND_EASY")
static const std::string flag_BLIND_HARD ("BLIND_HARD")
static const std::string flag_FULL_MAGAZINE ("FULL_MAGAZINE")
static const std::string flag_NO_BENCH ("NO_BENCH")
static const std::string flag_NO_ENCHANTMENT ("NO_ENCHANTMENT")
static const std::string flag_NO_MANIP ("NO_MANIP")
static const std::string flag_NO_RESIZE ("NO_RESIZE")
static bool crafting_allowed (const Character &p, const recipe &rec)
template<typename T >
static float lerped_multiplier (const T &value, const T &low, const T &high)
static bool is_container_eligible_for_crafting (const item &cont, bool allow_bucket)
static std::vector< const item * > get_eligible_containers_recursive (const item &cont, bool allow_bucket)
static std::optional< item_location > wield_craft (Character &p, item &craft)
static item_location set_item_inventory (Character &p, item &newit)
static item_location set_item_map (const tripoint &loc, item &newit)
Helper for set_item_map_or_vehicle This is needed to still get a valid item_location if overflow occurs.
static item_location set_item_map_or_vehicle (const Character &p, const tripoint &loc, item &newit)
Set an item on the map or in a vehicle and return the new location.
static item_location place_craft_or_disassembly (Character &ch, item &craft, std::optional< tripoint > target)
static void destroy_random_component (item &craft, const Character &crafter)
static void set_temp_rot (item &newit, const double relative_rot, const bool should_heat)
static void spawn_items (Character &guy, std::vector< item > &results, const std::optional< tripoint > &loc, const double relative_rot, const bool should_heat, bool allow_wield=false)
static void empty_buckets (Character &p)
void remove_ammo (std::list< item > &dis_items, Character &p)
void drop_or_handle (const item &newit, Character &p)
void remove_ammo (item &dis_item, Character &p)
static bool is_anyone_crafting (const item_location &itm, const Character *you=nullptr)
Variables
static const activity_id ACT_CRAFT ("ACT_CRAFT")
static const activity_id ACT_DISASSEMBLE ("ACT_DISASSEMBLE")
static const activity_id ACT_MULTIPLE_CRAFT ("ACT_MULTIPLE_CRAFT")
static const efftype_id effect_contacts ("contacts")
static const efftype_id effect_transition_contacts ("transition_contacts")
static const itype_id itype_disassembly ("disassembly")
static const itype_id itype_plut_cell ("plut_cell")
static const json_character_flag json_flag_HYPEROPIC ("HYPEROPIC")
static const limb_score_id limb_score_manip ("manip")
static const quality_id qual_BOIL ("BOIL")
static const skill_id skill_electronics ("electronics")
static const skill_id skill_tailor ("tailor")
static const string_id< struct furn_t > furn_f_fake_bench_hands ("f_fake_bench_hands")
static const string_id< struct furn_t > furn_f_ground_crafting_spot ("f_ground_crafting_spot")
static const trait_id trait_BURROW ("BURROW")
static const trait_id trait_BURROWLARGE ("BURROWLARGE")
static const trait_id trait_DEBUG_CNF ("DEBUG_CNF")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
static const trait_id trait_INT_ALPHA ("INT_ALPHA")
Function Documentation
crafting_allowed()
static bool crafting_allowed (const Character & p, const recipe & rec) static
Definition at line 129 of file crafting.cpp.
 {
     if( p.morale_crafting_speed_multiplier( rec ) <= 0.0f ) {
         if( p.is_avatar() ) {
             add_msg( m_info, _( "Your morale is too low to craft such a difficult thing…" ) );
         } else {
             add_msg_if_player_sees( p.pos(), m_info,
                                     _( "%s's morale is too low to craft such a difficult thing…" ),
                                     p.get_name() );
         }
         return false;
     }
     if( p.lighting_craft_speed_multiplier( rec ) <= 0.0f ) {
         if( p.is_avatar() ) {
             add_msg( m_info, _( "You can't see to craft!" ) );
         } else {
             add_msg_if_player_sees( p.pos(), m_info, _( "%s can't see to craft!" ),
                                     p.get_name() );
         }
         return false;
     }
     if( p.is_driving() ) {
         // One day, NPCs may be able to drive.
         p.add_msg_player_or_npc( m_info,
                                  _( "You can't craft while driving!" ),
                                  _( "<npcname> refuses to violate road safety guidelines by crafting while driving!" ) );
         return false;
     }
     if( rec.category == "CC_BUILDING" ) {
         add_msg( m_info, _( "Overmap terrain building recipes are not implemented yet!" ) );
         return false;
     }
     return true;
 }
References _, add_msg(), add_msg_if_player_sees(), Character::add_msg_player_or_npc(), recipe::category, Character::get_name(), Creature::is_avatar(), Character::is_driving(), Character::lighting_craft_speed_multiplier(), m_info, Character::morale_crafting_speed_multiplier(), and Creature::pos().
Referenced by Character::craft(), Character::long_craft(), and Character::making_would_work().
destroy_random_component()
static void destroy_random_component (item & craft, const Character & crafter) static
Definition at line 1313 of file crafting.cpp.
 {
     if( craft.components.empty() ) {
         debugmsg( "destroy_random_component() called on craft with no components!  Aborting" );
         return;
     }
     item destroyed = craft.components.get_and_remove_random_entry();
     crafter.add_msg_player_or_npc( game_message_params( game_message_type::m_bad ),
                                    _( "You mess up and destroy the %s." ),
                                    _( "<npcname> messes up and destroys the %s" ), destroyed.tname() );
 }
References _, Character::add_msg_player_or_npc(), anonymous_namespace{item_tname.cpp}::craft(), debugmsg, m_bad, and item::tname().
Referenced by item::handle_craft_failure().
drop_or_handle()
void drop_or_handle (const item & newit, Character & p)
Definition at line 3010 of file crafting.cpp.
 {
     if( newit.made_of( phase_id::LIQUID ) && p.is_avatar() ) { // TODO: what about NPCs?
         liquid_handler::handle_all_liquid( newit, PICKUP_RANGE );
     } else {
         item tmp( newit );
         p.i_add_or_drop( tmp );
     }
 }
References liquid_handler::handle_all_liquid(), Character::i_add_or_drop(), Creature::is_avatar(), LIQUID, item::made_of(), and PICKUP_RANGE.
Referenced by empty_buckets(), item_pocket::remove_all_ammo(), and remove_ammo().
empty_buckets()
static void empty_buckets (Character & p) static
Definition at line 2013 of file crafting.cpp.
 {
     // First grab (remove) all items that are non-empty buckets and not wielded
     auto buckets = p.remove_items_with( [&p]( const item & it ) {
         return it.is_bucket_nonempty() && ( !p.get_wielded_item() || &it != &*p.get_wielded_item() );
     }, INT_MAX );
     for( item &it : buckets ) {
         for( const item *in : it.all_items_top() ) {
             drop_or_handle( *in, p );
         }
         it.clear_items();
         drop_or_handle( it, p );
     }
 }
References item::all_items_top(), item::clear_items(), drop_or_handle(), Character::get_wielded_item(), item::is_bucket_nonempty(), and Character::remove_items_with().
Referenced by Character::consume_items().
flag_AFFECTED_BY_PAIN()
static const std::string flag_AFFECTED_BY_PAIN ("AFFECTED_BY_PAIN") static
Referenced by Character::crafting_speed_multiplier().
flag_BLIND_EASY()
static const std::string flag_BLIND_EASY ("BLIND_EASY") static
Referenced by Character::lighting_craft_speed_multiplier().
flag_BLIND_HARD()
static const std::string flag_BLIND_HARD ("BLIND_HARD") static
Referenced by Character::lighting_craft_speed_multiplier().
flag_FULL_MAGAZINE()
static const std::string flag_FULL_MAGAZINE ("FULL_MAGAZINE") static
Referenced by Character::complete_disassemble().
flag_NO_BENCH()
static const std::string flag_NO_BENCH ("NO_BENCH") static
Referenced by Character::crafting_speed_multiplier().
flag_NO_ENCHANTMENT()
static const std::string flag_NO_ENCHANTMENT ("NO_ENCHANTMENT") static
Referenced by Character::crafting_speed_multiplier().
flag_NO_MANIP()
static const std::string flag_NO_MANIP ("NO_MANIP") static
Referenced by Character::crafting_speed_multiplier().
flag_NO_RESIZE()
static const std::string flag_NO_RESIZE ("NO_RESIZE") static
Referenced by item::inherit_flags().
get_eligible_containers_recursive()
static std::vector<const item *> get_eligible_containers_recursive (const item & cont, bool allow_bucket) static
Definition at line 538 of file crafting.cpp.
 {
     std::vector<const item *> ret;
     if( is_container_eligible_for_crafting( cont, allow_bucket ) ) {
         ret.push_back( &cont );
     }
     for( const item *it : cont.all_items_top( pocket_type::CONTAINER ) ) {
         //buckets are never allowed when inside another container
         std::vector<const item *> inside = get_eligible_containers_recursive( *it, false );
         ret.insert( ret.end(), inside.begin(), inside.end() );
     }
     return ret;
 }
References item::all_items_top(), CONTAINER, is_container_eligible_for_crafting(), and cata::hash64_detail::ret.
Referenced by Character::get_eligible_containers_for_crafting(), and outfit::get_eligible_containers_for_crafting().
is_anyone_crafting()
static bool is_anyone_crafting (const item_location & itm, const Character * you = nullptr) static
Definition at line 3073 of file crafting.cpp.
 {
     for( const npc &guy : g->all_npcs() ) {
         if( !( you && you->getID() == guy.getID() ) &&
             guy.activity.id() == ACT_CRAFT ) {
             item_location target = guy.activity.targets.back();
             if( target == itm ) {
                 return true;
             }
         }
     }
     return false;
 }
References ACT_CRAFT, and g.
is_container_eligible_for_crafting()
static bool is_container_eligible_for_crafting (const item & cont, bool allow_bucket) static
Definition at line 529 of file crafting.cpp.
 {
     if( cont.is_watertight_container() && cont.num_item_stacks() <= 1 && ( allow_bucket ||
             !cont.will_spill() ) ) {
         return !cont.is_container_full( allow_bucket );
     }
     return false;
 }
References item::is_container_full(), item::is_watertight_container(), item::num_item_stacks(), and item::will_spill().
Referenced by get_eligible_containers_recursive().
lerped_multiplier()
template<typename T > static float lerped_multiplier (const T & value, const T & low, const T & high) static
Definition at line 228 of file crafting.cpp.
 {
     // No effect if less than allowed value
     if( value <= low ) {
         return 1.0f;
     }
     // Bottom out at 25% speed
     if( value >= high ) {
         return 0.25f;
     }
     // Linear interpolation between high and low
     // y = y0 + ( x - x0 ) * ( y1 - y0 ) / ( x1 - x0 )
     return 1.0f + ( value - low ) * ( 0.25f - 1.0f ) / ( high - low );
 }
References irradiance::high, and irradiance::low.
Referenced by Character::workbench_crafting_speed_multiplier().
place_craft_or_disassembly()
static item_location place_craft_or_disassembly (Character & ch, item & craft, std::optional< tripoint > target) static
Definition at line 822 of file crafting.cpp.
 {
     item_location craft_in_world;
     // Check if we are standing next to a workbench. If so, just use that.
     float best_bench_multi = 0.0f;
     map &here = get_map();
     for( const tripoint &adj : here.points_in_radius( ch.pos(), 1 ) ) {
         if( here.dangerous_field_at( adj ) ) {
             continue;
         }
         if( const cata::value_ptr<furn_workbench_info> &wb = here.furn( adj ).obj().workbench ) {
             if( wb->multiplier > best_bench_multi ) {
                 best_bench_multi = wb->multiplier;
                 target = adj;
             }
         } else if( const std::optional<vpart_reference> vp = here.veh_at(
                        adj ).part_with_feature( "WORKBENCH", true ) ) {
             if( const std::optional<vpslot_workbench> &wb_info = vp->part().info().workbench_info ) {
                 if( wb_info->multiplier > best_bench_multi ) {
                     best_bench_multi = wb_info->multiplier;
                     target = adj;
                 }
             } else {
                 debugmsg( "part '%s' with WORKBENCH flag has no workbench info", vp->part().name() );
             }
         }
     }
     // Crafting without a workbench
     if( !target ) {
         if( !ch.has_two_arms_lifting() ) {
             craft_in_world = set_item_map_or_vehicle( ch, ch.pos(), craft );
         } else if( !ch.has_wield_conflicts( craft ) || ch.is_npc() ) {
             // NPC always tries wield craft first
             if( std::optional<item_location> it_loc = wield_craft( ch, craft ) ) {
                 craft_in_world = *it_loc;
             }  else {
                 // This almost certainly shouldn't happen
                 put_into_vehicle_or_drop( ch, item_drop_reason::tumbling, {craft} );
             }
         } else {
             enum option : int {
                 WIELD_CRAFT = 0,
                 DROP_CRAFT,
                 STASH,
                 DROP
             };
             uilist amenu;
             amenu.text = string_format( pgettext( "in progress craft", "What to do with the %s?" ),
                                         craft.display_name() );
             amenu.addentry( WIELD_CRAFT, ch.can_unwield( *ch.get_wielded_item() ).success(),
                             '1', _( "Dispose of your wielded %s and start working." ), ch.get_wielded_item()->tname() );
             amenu.addentry( DROP_CRAFT, true, '2', _( "Put it down and start working." ) );
             const bool can_stash = ch.can_pickVolume( craft ) &&
                                    ch.can_pickWeight( craft, !get_option<bool>( "DANGEROUS_PICKUPS" ) );
             amenu.addentry( STASH, can_stash, '3', _( "Store it in your inventory." ) );
             amenu.addentry( DROP, true, '4', _( "Drop it on the ground." ) );
             amenu.query();
             const option choice = amenu.ret == UILIST_CANCEL ? DROP : static_cast<option>( amenu.ret );
             switch( choice ) {
                 case WIELD_CRAFT: {
                     if( std::optional<item_location> it_loc = wield_craft( ch, craft ) ) {
                         craft_in_world = *it_loc;
                     } else {
                         // This almost certainly shouldn't happen
                         put_into_vehicle_or_drop( ch, item_drop_reason::tumbling, {craft} );
                     }
                     break;
                 }
                 case DROP_CRAFT: {
                     craft_in_world = set_item_map_or_vehicle( ch, ch.pos(), craft );
                     break;
                 }
                 case STASH: {
                     set_item_inventory( ch, craft );
                     break;
                 }
                 case DROP: {
                     put_into_vehicle_or_drop( ch, item_drop_reason::deliberate, {craft} );
                     break;
                 }
             }
         }
     } else {
         // We have a workbench, put the item there.
         craft_in_world = set_item_map_or_vehicle( ch, *target, craft );
     }
     if( !craft_in_world ) {
         ch.add_msg_if_player( _( "Wield and activate the %s to start working." ), craft.tname() );
     }
     return craft_in_world;
 }
References _, Character::add_msg_if_player(), uilist::addentry(), Character::can_pickVolume(), Character::can_pickWeight(), Character::can_unwield(), anonymous_namespace{item_tname.cpp}::craft(), map::dangerous_field_at(), debugmsg, deliberate, map::furn(), get_map(), Character::get_wielded_item(), Character::has_two_arms_lifting(), Character::has_wield_conflicts(), Character::is_npc(), int_id< T >::obj(), optional_vpart_position::part_with_feature(), pgettext, map::points_in_radius(), Creature::pos(), put_into_vehicle_or_drop(), uilist::query(), uilist::ret, set_item_inventory(), set_item_map_or_vehicle(), STASH, string_format(), ret_val_common::success(), uilist::text, item::tname(), tumbling, UILIST_CANCEL, map::veh_at(), wield_craft(), and furn_t::workbench.
Referenced by Character::create_in_progress_disassembly(), and Character::start_craft().
remove_ammo() [1/2]
void remove_ammo (item & dis_item, Character & p)
Definition at line 3020 of file crafting.cpp.
 {
     dis_item.remove_items_with( [&p]( const item & it ) {
         if( it.is_irremovable() || !( it.is_gunmod() || it.is_toolmod() || ( it.is_magazine() &&
                                       !it.is_tool() ) ) ) {
             return false;
         }
         drop_or_handle( it, p );
         return true;
     } );
     if( dis_item.has_flag( flag_NO_UNLOAD ) ) {
         return;
     }
     if( dis_item.is_gun() && !dis_item.ammo_current().is_null() ) {
         item ammodrop( dis_item.ammo_current(), calendar::turn );
         ammodrop.charges = dis_item.charges;
         drop_or_handle( ammodrop, p );
         dis_item.charges = 0;
     }
     if( dis_item.is_tool() && dis_item.charges > 0 && !dis_item.ammo_current().is_null() ) {
         item ammodrop( dis_item.ammo_current(), calendar::turn );
         ammodrop.charges = dis_item.charges;
         if( dis_item.ammo_current() == itype_plut_cell ) {
             ammodrop.charges /= PLUTONIUM_CHARGES;
         }
         drop_or_handle( ammodrop, p );
         dis_item.charges = 0;
     }
 }
References item::ammo_current(), item::charges, drop_or_handle(), flag_NO_UNLOAD, item::has_flag(), item::is_gun(), item::is_gunmod(), item::is_irremovable(), item::is_magazine(), string_id< T >::is_null(), item::is_tool(), item::is_toolmod(), itype_plut_cell, PLUTONIUM_CHARGES, item::remove_items_with(), and calendar::turn.
remove_ammo() [2/2]
void remove_ammo (std::list< item > & dis_items, Character & p)
Definition at line 3003 of file crafting.cpp.
 {
     for( item &dis_item : dis_items ) {
         remove_ammo( dis_item, p );
     }
 }
Referenced by Character::consume_items(), Character::create_in_progress_disassembly(), and salvage_actor::cut_up().
set_item_inventory()
static item_location set_item_inventory (Character & p, item & newit) static
Definition at line 737 of file crafting.cpp.
 {
     item_location ret_val = item_location::nowhere;
     if( newit.made_of( phase_id::LIQUID ) ) {
         liquid_handler::handle_all_liquid( newit, PICKUP_RANGE );
     } else {
         p.inv->assign_empty_invlet( newit, p );
         // We might not have space for the item
         if( !p.can_pickVolume( newit ) ) { //Accounts for result_mult
             put_into_vehicle_or_drop( p, item_drop_reason::too_large, { newit } );
         } else if( !p.can_pickWeight( newit, !get_option<bool>( "DANGEROUS_PICKUPS" ) ) ) {
             put_into_vehicle_or_drop( p, item_drop_reason::too_heavy, { newit } );
         } else {
             ret_val = p.i_add( newit );
             add_msg( m_info, "%c - %s", ret_val->invlet == 0 ? ' ' : ret_val->invlet,
                      ret_val->tname() );
         }
     }
     return ret_val;
 }
References add_msg(), Character::can_pickVolume(), Character::can_pickWeight(), liquid_handler::handle_all_liquid(), Character::i_add(), Character::inv, LIQUID, m_info, item::made_of(), item_location::nowhere, PICKUP_RANGE, put_into_vehicle_or_drop(), too_heavy, and too_large.
Referenced by place_craft_or_disassembly(), and spawn_items().
set_item_map()
static item_location set_item_map (const tripoint & loc, item & newit) static
Helper for set_item_map_or_vehicle This is needed to still get a valid item_location if overflow occurs.
Definition at line 762 of file crafting.cpp.
 {
     // Includes loc
     for( const tripoint &tile : closest_points_first( loc, 2 ) ) {
         // Pass false to disallow overflow, null_item_reference indicates failure.
         item *it_on_map = &get_map().add_item_or_charges( tile, newit, false );
         if( it_on_map != &null_item_reference() ) {
             return item_location( map_cursor( tile ), it_on_map );
         }
     }
     debugmsg( "Could not place %s on map near (%d, %d, %d)", newit.tname(), loc.x, loc.y, loc.z );
     return item_location();
 }
References map::add_item_or_charges(), closest_points_first(), debugmsg, get_map(), null_item_reference(), item::tname(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by set_item_map_or_vehicle().
set_item_map_or_vehicle()
static item_location set_item_map_or_vehicle (const Character & p, const tripoint & loc, item & newit) static
Set an item on the map or in a vehicle and return the new location.
Definition at line 779 of file crafting.cpp.
 {
     map &here = get_map();
     if( const std::optional<vpart_reference> vp = here.veh_at( loc ).cargo() ) {
         vehicle &veh = vp->vehicle();
         if( const std::optional<vehicle_stack::iterator> it = veh.add_item( vp->part(), newit ) ) {
             p.add_msg_player_or_npc(
                 //~ %1$s: name of item being placed, %2$s: vehicle part name
                 pgettext( "item, furniture", "You put the %1$s on the %2$s." ),
                 pgettext( "item, furniture", "<npcname> puts the %1$s on the %2$s." ),
                 ( *it )->tname(), vp->part().name() );
             return item_location( vehicle_cursor( veh, vp->part_index() ), & **it );
         }
         // Couldn't add the in progress craft to the target part, so drop it to the map.
         p.add_msg_player_or_npc(
             //~ %1$s: vehicle part name, %2$s: name of the item being placed
             pgettext( "furniture, item", "Not enough space on the %1$s. You drop the %2$s on the ground." ),
             pgettext( "furniture, item",
                       "Not enough space on the %1$s. <npcname> drops the %2$s on the ground." ),
             vp->part().name(), newit.tname() );
         return set_item_map( loc, newit );
     } else {
         if( here.has_furn( loc ) ) {
             const furn_t &workbench = here.furn( loc ).obj();
             p.add_msg_player_or_npc(
                 //~ %1$s: name of item being placed, %2$s: vehicle part name
                 pgettext( "item, furniture", "You put the %1$s on the %2$s." ),
                 pgettext( "item, furniture", "<npcname> puts the %1$s on the %2$s." ),
                 newit.tname(), workbench.name() );
         } else {
             p.add_msg_player_or_npc(
                 pgettext( "item", "You put the %s on the ground." ),
                 pgettext( "item", "<npcname> puts the %s on the ground." ),
                 newit.tname() );
         }
         return set_item_map( loc, newit );
     }
 }
References vehicle::add_item(), Character::add_msg_player_or_npc(), optional_vpart_position::cargo(), map::furn(), get_map(), map::has_furn(), int_id< T >::obj(), pgettext, set_item_map(), item::tname(), map::veh_at(), vehicle::vehicle(), and iexamine::workbench().
Referenced by place_craft_or_disassembly(), and spawn_items().
set_temp_rot()
static void set_temp_rot (item & newit, const double relative_rot, const bool should_heat) static
Definition at line 1429 of file crafting.cpp.
 {
     if( newit.has_temperature() ) {
         if( newit.goes_bad() ) {
             newit.set_relative_rot( relative_rot );
         }
         if( should_heat ) {
             newit.heat_up();
         } else {
             // Really what we should be doing is averaging the temperatures
             // between the recipe components if we don't have a heat tool, but
             // that's kind of hard.  For now just set the item to 20 C
             // and reset the temperature.
             //
             // Temperature is not functional for non-foods
             newit.set_item_temperature( units::from_celsius( 20 ) );
         }
     }
 }
References units::from_celsius(), item::goes_bad(), item::has_temperature(), item::heat_up(), item::set_item_temperature(), and item::set_relative_rot().
Referenced by spawn_items().
spawn_items()
static void spawn_items (Character & guy, std::vector< item > & results, const std::optional< tripoint > & loc, const double relative_rot, const bool should_heat, bool allow_wield = false) static
Definition at line 1449 of file crafting.cpp.
 {
     for( item &newit : results ) {
         // todo: set this up recursively, who knows what kinda crafts will need it
         if( !newit.empty() ) {
             for( item *new_content : newit.all_items_top() ) {
                 set_temp_rot( *new_content, relative_rot, should_heat );
             }
         }
         set_temp_rot( newit, relative_rot, should_heat );
         newit.set_owner( guy.get_faction()->id );
         if( newit.made_of( phase_id::LIQUID ) ) {
             liquid_handler::handle_all_liquid( newit, PICKUP_RANGE );
         } else if( !loc && allow_wield && !guy.has_wield_conflicts( newit ) &&
                    guy.can_wield( newit ).success() ) {
             wield_craft( guy, newit );
         } else if( !loc ) {
             set_item_inventory( guy, newit );
         } else {
             set_item_map_or_vehicle( guy, loc.value_or( guy.pos() ), newit );
         }
     }
 }
References item::all_items_top(), Character::can_wield(), Character::get_faction(), liquid_handler::handle_all_liquid(), Character::has_wield_conflicts(), faction_template::id, LIQUID, PICKUP_RANGE, Creature::pos(), set_item_inventory(), set_item_map_or_vehicle(), set_temp_rot(), ret_val_common::success(), and wield_craft().
Referenced by Character::complete_craft(), and map::put_items_from_loc().
wield_craft()
static std::optional<item_location> wield_craft (Character & p, item & craft) static
Definition at line 723 of file crafting.cpp.
 {
     if( p.wield( craft ) ) {
         item_location weapon = p.get_wielded_item();
         if( weapon->invlet ) {
             p.add_msg_if_player( m_info, _( "Wielding %c - %s" ), weapon->invlet, weapon->display_name() );
         } else {
             p.add_msg_if_player( m_info, _( "Wielding - %s" ), weapon->display_name() );
         }
         return weapon;
     }
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), anonymous_namespace{item_tname.cpp}::craft(), item::display_name(), Character::get_wielded_item(), item::invlet, m_info, and Character::wield().
Referenced by place_craft_or_disassembly(), and spawn_items().
Variable Documentation
ACT_CRAFT
const activity_id ACT_CRAFT("ACT_CRAFT") ("ACT_CRAFT") static
Referenced by is_anyone_crafting().
ACT_DISASSEMBLE
const activity_id ACT_DISASSEMBLE("ACT_DISASSEMBLE") ("ACT_DISASSEMBLE") static
Referenced by Character::disassemble().
ACT_MULTIPLE_CRAFT
const activity_id ACT_MULTIPLE_CRAFT("ACT_MULTIPLE_CRAFT") ("ACT_MULTIPLE_CRAFT") static
Referenced by Character::start_craft().
effect_contacts
const efftype_id effect_contacts("contacts") ("contacts") static
Referenced by Character::get_recipe_weighted_skill_average().
effect_transition_contacts
const efftype_id effect_transition_contacts("transition_contacts") ("transition_contacts") static
Referenced by Character::get_recipe_weighted_skill_average().
furn_f_fake_bench_hands
const string_id<struct furn_t> furn_f_fake_bench_hands("f_fake_bench_hands") ("f_fake_bench_hands") static
Referenced by Character::workbench_crafting_speed_multiplier().
furn_f_ground_crafting_spot
const string_id<struct furn_t> furn_f_ground_crafting_spot("f_ground_crafting_spot") ("f_ground_crafting_spot") static
Referenced by Character::workbench_crafting_speed_multiplier().
itype_disassembly
const itype_id itype_disassembly("disassembly") ("disassembly") static
Referenced by Character::can_disassemble(), Character::complete_disassemble(), Character::create_in_progress_disassembly(), and Character::disassemble().
itype_plut_cell
const itype_id itype_plut_cell("plut_cell") ("plut_cell") static
Referenced by remove_ammo().
json_flag_HYPEROPIC
const json_character_flag json_flag_HYPEROPIC("HYPEROPIC") ("HYPEROPIC") static
Referenced by Character::get_recipe_weighted_skill_average().
limb_score_manip
const limb_score_id limb_score_manip("manip") ("manip") static
Referenced by Character::crafting_speed_multiplier().
qual_BOIL
const quality_id qual_BOIL("BOIL") ("BOIL") static
Referenced by Character::crafting_inventory().
skill_electronics
const skill_id skill_electronics("electronics") ("electronics") static
Referenced by Character::get_recipe_weighted_skill_average().
skill_tailor
const skill_id skill_tailor("tailor") ("tailor") static
Referenced by Character::get_recipe_weighted_skill_average().
trait_BURROW
const trait_id trait_BURROW("BURROW") ("BURROW") static
Referenced by Character::crafting_inventory().
trait_BURROWLARGE
const trait_id trait_BURROWLARGE("BURROWLARGE") ("BURROWLARGE") static
Referenced by Character::crafting_inventory().
trait_DEBUG_CNF
const trait_id trait_DEBUG_CNF("DEBUG_CNF") ("DEBUG_CNF") static
Referenced by Character::recipe_success_roll_data().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by Character::consume_items(), Character::consume_tools(), Character::craft_consume_tools(), and Character::select_item_component().
trait_INT_ALPHA
const trait_id trait_INT_ALPHA("INT_ALPHA") ("INT_ALPHA") static
Referenced by item::handle_craft_failure().