Cataclysm DDA: src/craft_command.cpp File Reference
craft_command.cpp File Reference
#include "craft_command.h"
#include <algorithm>
#include <climits>
#include <cstdlib>
#include <functional>
#include <limits>
#include <list>
#include <string>
#include <utility>
#include "activity_actor_definitions.h"
#include "character.h"
#include "crafting.h"
#include "debug.h"
#include "enum_conversions.h"
#include "enum_traits.h"
#include "flag.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "game_constants.h"
#include "inventory.h"
#include "item.h"
#include "item_components.h"
#include "item_contents.h"
#include "item_location.h"
#include "item_pocket.h"
#include "itype.h"
#include "json.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "output.h"
#include "pocket_type.h"
#include "recipe.h"
#include "requirements.h"
#include "translations.h"
#include "type_id.h"
#include "uistate.h"
#include "vehicle.h"
#include "visitable.h"
#include "vpart_position.h"
Namespaces
io
Functions
template<>
std::string io::enum_to_string< usage_from > (usage_from data)
template<typename T >
static std::string component_list_string (const std::vector< comp_selection< T >> &components)
Does a string join with ', ' of the components in the passed vector and inserts into 'str'.
static std::list< item > sane_consume_items (const comp_selection< item_comp > &it, Character *crafter, int batch, const std::function< bool(const item &)> &filter)
Variables
static const itype_id itype_candle ("candle")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
Function Documentation
component_list_string()
template<typename T > static std::string component_list_string (const std::vector< comp_selection< T >> & components) static
Does a string join with ', ' of the components in the passed vector and inserts into 'str'.
Definition at line 234 of file craft_command.cpp.
 {
     return enumerate_as_string( components.begin(), components.end(),
     []( const comp_selection<T> &comp ) {
         return comp.nname();
     } );
 }
References enumerate_as_string().
Referenced by craft_command::query_continue().
sane_consume_items()
static std::list<item> sane_consume_items (const comp_selection< item_comp > & it, Character * crafter, int batch, const std::function< bool(const item &)> & filter) static
Definition at line 355 of file craft_command.cpp.
 {
     map &m = get_map();
     const std::vector<pocket_data> it_pkt = it.comp.type->pockets;
     if( ( item::count_by_charges( it.comp.type ) && it.comp.count > 0 ) ||
     !std::any_of( it_pkt.begin(), it_pkt.end(), []( const pocket_data & p ) {
     return p.type == pocket_type::CONTAINER && p.watertight;
 } ) ) {
         std::list<item> consumed = crafter->consume_items( it, batch, filter );
         return consumed;
     }
     // Everything below only occurs for item components that are liquid containers
     std::function<bool( const item & )> empty_filter = [&filter]( const item & it ) {
         return it.empty_container() && filter( it );
     };
     int real_count = ( it.comp.count > 0 ) ? it.comp.count * batch : std::abs( it.comp.count );
     std::list<item> ret;
     for( int i = 0; i < 2 && real_count > 0; i++ ) {
         if( it.use_from & usage_from::map ) {
             const tripoint &loc = crafter->pos();
             for( int radius = 0; radius <= PICKUP_RANGE && real_count > 0; radius++ ) {
                 for( const tripoint &p : m.points_in_radius( loc, radius ) ) {
                     if( rl_dist( loc, p ) >= radius ) {
                         std::list<item> tmp = m.use_amount_square( p, it.comp.type, real_count,
                                               i == 0 ? empty_filter : filter );
                         ret.insert( ret.end(), tmp.begin(), tmp.end() );
                     }
                 }
             }
         }
         if( it.use_from & usage_from::player && real_count > 0 ) {
             std::list<item> tmp = crafter->use_amount( it.comp.type, real_count,
                                   i == 0 ? empty_filter : filter );
             real_count -= tmp.size();
             ret.insert( ret.end(), tmp.begin(), tmp.end() );
         }
     }
     return ret;
 }
References abs(), comp_selection< CompType >::comp, Character::consume_items(), component::count, item::count_by_charges(), filter, get_map(), map, player, itype::pockets, map::points_in_radius(), Creature::pos(), cata::hash64_detail::ret, rl_dist(), component::type, Character::use_amount(), map::use_amount_square(), and comp_selection< CompType >::use_from.
Referenced by craft_command::create_in_progress_craft().
Variable Documentation
itype_candle
const itype_id itype_candle("candle") ("candle") static
Referenced by craft_command::safe_to_unload_comp().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by craft_command::create_in_progress_craft().