Cataclysm DDA: src/crafting_gui.h File Reference
crafting_gui.h File Reference
#include <string>
#include <utility>
#include <vector>
#include "type_id.h"
Macros
#define CATA_SRC_CRAFTING_GUI_H
Functions
std::pair< Character *, const recipe * > select_crafter_and_crafting_recipe (int &batch_size_out, const recipe_id &goto_recipe, Character *crafter, std::string filterstring="")
Open crafting menu where user selects who will craft what (the crafter & the recipe).
void load_recipe_category (const JsonObject &jsobj)
void reset_recipe_categories ()
const std::vector< std::string > * subcategories_for_category (const std::string &category)
Macro Definition Documentation
CATA_SRC_CRAFTING_GUI_H
#define CATA_SRC_CRAFTING_GUI_H
Definition at line 3 of file crafting_gui.h.
Function Documentation
load_recipe_category()
void load_recipe_category (const JsonObject & jsobj)
Definition at line 130 of file crafting_gui.cpp.
 {
     const std::string category = jsobj.get_string( "id" );
     const bool is_hidden = jsobj.get_bool( "is_hidden", false );
     if( category.find( "CC_" ) != 0 ) {
         jsobj.throw_error( "Crafting category id has to be prefixed with 'CC_'" );
     }
     if( !is_hidden
         && std::find( craft_cat_list.begin(), craft_cat_list.end(), category ) == craft_cat_list.end()
       ) {
         craft_cat_list.push_back( category );
     }
     const std::string cat_name = get_cat_unprefixed( category );
     craft_subcat_list[category].clear();
     for( const std::string subcat_id : jsobj.get_array( "recipe_subcategories" ) ) {
         if( subcat_id.find( "CSC_" + cat_name + "_" ) != 0 && subcat_id != "CSC_ALL" ) {
             jsobj.throw_error( "Crafting sub-category id has to be prefixed with CSC_<category_name>_" );
         }
         if( find( craft_subcat_list[category].begin(), craft_subcat_list[category].end(),
                   subcat_id ) == craft_subcat_list[category].end() ) {
             craft_subcat_list[category].push_back( subcat_id );
         }
     }
 }
References anonymous_namespace{item_tname.cpp}::category(), craft_cat_list, craft_subcat_list, keycode::end, JsonObject::get_array(), JsonObject::get_bool(), get_cat_unprefixed(), JsonObject::get_string(), and JsonObject::throw_error().
Referenced by DynamicDataLoader::initialize().
reset_recipe_categories()
void reset_recipe_categories ()
Definition at line 171 of file crafting_gui.cpp.
 {
     craft_cat_list.clear();
     craft_subcat_list.clear();
 }
References craft_cat_list, and craft_subcat_list.
Referenced by DynamicDataLoader::unload_data().
select_crafter_and_crafting_recipe()
std::pair<Character *, const recipe *> select_crafter_and_crafting_recipe (int & batch_size_out, const recipe_id & goto_recipe, Character * crafter, std::string filterstring = "")
Open crafting menu where user selects who will craft what (the crafter & the recipe).
Parameters
crafter who opened the menu - the initial crafter
filterstring initial filter to execute
Return: if recipe * is not nullptr, then Character * is not nullptr either.
Definition at line 1186 of file crafting_gui.cpp.
 {
     if( crafter == nullptr ) {
         return {nullptr, nullptr};
     }
     recipe_result_info_cache result_info( *crafter );
     recipe_info_cache r_info_cache;
     int line_recipe_info = 0;
     int line_item_info = 0;
     int line_item_info_popup = 0;
     const int headHeight = 3;
     const int subHeadHeight = 2;
     bool isWide = false;
     int width = 0;
     int dataLines = 0;
     int dataHalfLines = 0;
     int dataHeight = 0;
     int item_info_width = 0;
     const bool highlight_unread_recipes = get_option<bool>( "HIGHLIGHT_UNREAD_RECIPES" );
     input_context ctxt = make_crafting_context( highlight_unread_recipes );
     catacurses::window w_head_tabs; //For the recipe category tabs on the left
     catacurses::window w_head_info; //For the new/hidden/status information on the right
     catacurses::window w_subhead;
     catacurses::window w_data;
     catacurses::window w_iteminfo;
     inclusive_rectangle<point> mouseover_area_list;
     inclusive_rectangle<point> mouseover_area_recipe;
     std::vector<std::string> keybinding_tips;
     int keybinding_x = 0;
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         const int freeWidth = TERMX - FULL_SCREEN_WIDTH;
         isWide = ( TERMX > FULL_SCREEN_WIDTH && freeWidth > 15 );
         width = isWide ? ( freeWidth > FULL_SCREEN_WIDTH ? FULL_SCREEN_WIDTH * 2 : TERMX ) :
                 FULL_SCREEN_WIDTH;
         const unsigned int header_info_width = std::max( width / 4, width - FULL_SCREEN_WIDTH - 1 );
         const int wStart = ( TERMX - width ) / 2;
         std::vector<std::string> act_descs;
         const auto add_action_desc = [&]( const std::string & act, const std::string & txt ) {
             act_descs.emplace_back(
                 ctxt.get_desc( act, txt, input_context::allow_all_keys ) );
         };
         add_action_desc( "CONFIRM", pgettext( "crafting gui", "Craft" ) );
         add_action_desc( "HELP_RECIPE", pgettext( "crafting gui", "Describe" ) );
         add_action_desc( "FILTER", pgettext( "crafting gui", "Filter" ) );
         add_action_desc( "RESET_FILTER", pgettext( "crafting gui", "Reset filter" ) );
         if( highlight_unread_recipes ) {
             add_action_desc( "TOGGLE_RECIPE_UNREAD", pgettext( "crafting gui", "Read/unread" ) );
             add_action_desc( "MARK_ALL_RECIPES_READ", pgettext( "crafting gui", "Mark all as read" ) );
             add_action_desc( "TOGGLE_UNREAD_RECIPES_FIRST",
                              pgettext( "crafting gui", "Show unread recipes first" ) );
         }
         add_action_desc( "HIDE_SHOW_RECIPE", pgettext( "crafting gui", "Show/hide" ) );
         add_action_desc( "RELATED_RECIPES", pgettext( "crafting gui", "Related" ) );
         add_action_desc( "TOGGLE_FAVORITE", pgettext( "crafting gui", "Favorite" ) );
         add_action_desc( "CYCLE_BATCH", pgettext( "crafting gui", "Batch" ) );
         add_action_desc( "CHOOSE_CRAFTER", pgettext( "crafting gui", "Choose crafter" ) );
         add_action_desc( "HELP_KEYBINDINGS", pgettext( "crafting gui", "Keybindings" ) );
         keybinding_x = isWide ? 5 : 2;
         keybinding_tips = foldstring( enumerate_as_string( act_descs, enumeration_conjunction::none ),
                                       width - keybinding_x * 2 );
         const int tailHeight = keybinding_tips.size() + 2;
         dataLines = TERMY - ( headHeight + subHeadHeight ) - tailHeight;
         dataHalfLines = dataLines / 2;
         dataHeight = TERMY - ( headHeight + subHeadHeight );
         w_head_tabs = catacurses::newwin( headHeight, ( width - header_info_width ), point( wStart, 0 ) );
         w_head_info = catacurses::newwin( headHeight, header_info_width,
                                           point( wStart + ( width - header_info_width ), 0 ) );
         w_subhead = catacurses::newwin( subHeadHeight, width, point( wStart, 3 ) );
         w_data = catacurses::newwin( dataHeight, width, point( wStart,
                                      headHeight + subHeadHeight ) );
         if( isWide ) {
             item_info_width = width - FULL_SCREEN_WIDTH - 1;
             const int item_info_height = dataHeight - tailHeight;
             const point item_info( wStart + width - item_info_width, headHeight + subHeadHeight );
             w_iteminfo = catacurses::newwin( item_info_height, item_info_width,
                                              item_info );
         } else {
             item_info_width = 0;
             w_iteminfo = {};
         }
         ui.position( point( wStart, 0 ), point( width, TERMY ) );
     } );
     ui.mark_resize();
     bool is_filtered_unread = false;
     std::map<std::string, bool> is_cat_unread;
     std::map<std::string, std::map<std::string, bool>> is_subcat_unread;
     tab_list tab( craft_cat_list );
     tab_list subtab( craft_subcat_list[tab.cur()] );
     std::map<size_t, inclusive_rectangle<point>> translated_tab_map;
     std::map<size_t, inclusive_rectangle<point>> translated_subtab_map;
     std::map<size_t, inclusive_rectangle<point>> list_map;
     // List of all recipes to show, to choose from
     std::vector<const recipe *> current;
     // how much to indent any item
     std::vector<int> indent;
     std::vector<availability> available;
     int line = 0;
     bool unread_recipes_first = false;
     bool user_moved_line = false;
     bool recalc = true;
     bool recalc_unread = highlight_unread_recipes;
     bool keepline = false;
     bool done = false;
     bool batch = false;
     bool show_hidden = false;
     size_t num_hidden = 0;
     int num_recipe = 0;
     int batch_line = 0;
     const recipe *chosen = nullptr;
     int last_line = -1;
     bool just_toggled_unread = false;
     const std::vector<Character *> crafting_group = crafter->get_crafting_group();
     int crafter_i = find( crafting_group.begin(), crafting_group.end(),
                           crafter ) - crafting_group.begin();
     // Get everyone's recipes
     const recipe_subset &available_recipes = crafter->get_group_available_recipes();
     std::map<character_id, std::map<const recipe *, availability>> guy_availability_cache;
     // next line also inserts empty cache for crafter->getID()
     std::map<const recipe *, availability> *availability_cache =
         &guy_availability_cache[crafter->getID()];
     const std::string new_recipe_str = pgettext( "crafting gui", "NEW!" );
     const nc_color new_recipe_str_col = c_light_green;
     const int new_recipe_str_width = utf8_width( new_recipe_str );
     if( goto_recipe.is_valid() ) {
         const std::vector<const recipe *> &gotocat = available_recipes.in_category( goto_recipe->category );
         if( !gotocat.empty() ) {
             const auto gotorec = std::find_if( gotocat.begin(),
             gotocat.end(), [&goto_recipe]( const recipe * r ) {
                 return r && r->ident() == goto_recipe;
             } );
             if( gotorec != gotocat.end() &&
                 std::find( craft_cat_list.begin(), craft_cat_list.end(),
                            goto_recipe->category ) != craft_cat_list.end() ) {
                 while( tab.cur() != goto_recipe->category ) {
                     tab.next();
                 }
                 subtab = tab_list( craft_subcat_list[tab.cur()] );
                 chosen = *gotorec;
                 show_hidden = true;
                 keepline = true;
                 current = gotocat;
                 line = gotorec - gotocat.begin();
             }
         }
     }
     ui.on_redraw( [&]( ui_adaptor & ui ) {
         if( highlight_unread_recipes && recalc_unread ) {
             if( filterstring.empty() ) {
                 for( const std::string &cat : craft_cat_list ) {
                     is_cat_unread[cat] = false;
                     for( const std::string &subcat : craft_subcat_list[cat] ) {
                         is_subcat_unread[cat][subcat] = false;
                         const std::pair<std::vector<const recipe *>, bool> result = recipes_from_cat( available_recipes,
                                 cat, subcat );
                         const std::vector<const recipe *> &recipes = result.first;
                         const bool include_hidden = result.second;
                         for( const recipe *const rcp : recipes ) {
                             const recipe_id &rcp_id = rcp->ident();
                             if( !include_hidden && uistate.hidden_recipes.count( rcp_id ) ) {
                                 continue;
                             }
                             if( uistate.read_recipes.count( rcp_id ) ) {
                                 continue;
                             }
                             is_cat_unread[cat] = true;
                             is_subcat_unread[cat][subcat] = true;
                             break;
                         }
                     }
                 }
             } else {
                 is_filtered_unread = false;
                 for( const recipe *const rcp : current ) {
                     const recipe_id &rcp_id = rcp->ident();
                     if( uistate.hidden_recipes.count( rcp_id ) ) {
                         continue;
                     }
                     if( uistate.read_recipes.count( rcp_id ) ) {
                         continue;
                     }
                     is_filtered_unread = true;
                     break;
                 }
             }
             recalc_unread = false;
         }
         const TAB_MODE m = batch ? BATCH : filterstring.empty() ? NORMAL : FILTERED;
         translated_tab_map = draw_recipe_tabs( w_head_tabs, tab, m, is_filtered_unread, is_cat_unread );
         translated_subtab_map = draw_recipe_subtabs( w_subhead, tab.cur(), subtab.cur_index(),
                                 available_recipes, m,
                                 is_subcat_unread[tab.cur()] );
         //Clear the crafting info panel, since that can change on a per-recipe basis
         werase( w_head_info );
         if( !show_hidden ) {
             draw_hidden_amount( w_head_info, num_hidden, num_recipe );
         }
         // Clear the screen of recipe data, and draw it anew
         werase( w_data );
         for( size_t i = 0; i < keybinding_tips.size(); ++i ) {
             nc_color dummy = c_white;
             print_colored_text( w_data, point( keybinding_x, dataLines + 1 + i ),
                                 dummy, c_white, keybinding_tips[i] );
         }
         // Draw borders
         for( int i = 1; i < width - 1; ++i ) { // -
             mvwputch( w_data, point( i, dataHeight - 1 ), BORDER_COLOR, LINE_OXOX );
         }
         for( int i = 0; i < dataHeight - 1; ++i ) { // |
             mvwputch( w_data, point( 0, i ), BORDER_COLOR, LINE_XOXO );
             mvwputch( w_data, point( width - 1, i ), BORDER_COLOR, LINE_XOXO );
         }
         mvwputch( w_data, point( 0, dataHeight - 1 ), BORDER_COLOR, LINE_XXOO ); // |_
         mvwputch( w_data, point( width - 1, dataHeight - 1 ), BORDER_COLOR, LINE_XOOX ); // _|
         const int max_recipe_name_width = 27;
         const int recmax = current.size();
         // pair<int, int>
         const auto& [istart, iend] = subindex_around_cursor( recmax, dataLines, line );
         list_map.clear();
         for( int i = istart; i < iend; ++i ) {
             if( i >= static_cast<int>( indent.size() ) || indent[i] < 0 ) {
                 indent.assign( current.size(), 0 );
                 debugmsg( _( "Indent for line %i not set correctly.  Indents reset to 0." ), i );
             }
             std::string tmp_name = std::string( indent[i],
                                                 ' ' ) + current[i]->result_name( /*decorated=*/true );
             if( batch ) {
                 tmp_name = string_format( _( "%2dx %s" ), i + 1, tmp_name );
             }
             const bool rcp_read = !highlight_unread_recipes ||
                                   uistate.read_recipes.count( current[i]->ident() );
             const bool highlight = i == line;
             nc_color col = highlight ? available[i].selected_color() : available[i].color();
             const point print_from( 2, i - istart );
             if( highlight ) {
                 ui.set_cursor( w_data, print_from );
             }
             int rcp_name_trim_width = max_recipe_name_width;
             if( !rcp_read ) {
                 const point offset( max_recipe_name_width - new_recipe_str_width, 0 );
                 mvwprintz( w_data, print_from + offset, new_recipe_str_col, "%s", new_recipe_str );
                 rcp_name_trim_width -= new_recipe_str_width + 1;
             }
             mvwprintz( w_data, print_from, col, "%s", trim_by_length( tmp_name, rcp_name_trim_width ) );
             list_map.emplace( i, inclusive_rectangle<point>( print_from, point( 2 + max_recipe_name_width,
                               i - istart ) ) );
         }
         const int batch_size = batch ? line + 1 : 1;
         if( !current.empty() ) {
             const recipe &recp = *current[line];
             draw_can_craft_indicator( w_head_info, recp, *crafter );
             const availability &avail = available[line];
             // border + padding + name + padding
             const int xpos = 1 + 1 + max_recipe_name_width + 3;
             const int fold_width = FULL_SCREEN_WIDTH - xpos - 2;
             const int w_left = getbegx( w_data );
             mouseover_area_list = inclusive_rectangle<point>( point( 1 + w_left, headHeight + subHeadHeight ),
                                   point( w_left + xpos - 1, headHeight + subHeadHeight + dataLines ) );
             mouseover_area_recipe = inclusive_rectangle<point>( point( xpos + w_left,
                                     headHeight + subHeadHeight ), point( xpos + w_left + fold_width + 1,
                                             headHeight + subHeadHeight + dataLines ) );
             const nc_color color = avail.color( true );
             const std::string qry = trim( filterstring );
             std::string qry_comps;
             if( qry.compare( 0, 2, "c:" ) == 0 ) {
                 qry_comps = qry.substr( 2 );
             }
             const std::vector<std::string> &info = cached_recipe_info( r_info_cache,
                                                    recp, avail, *crafter, qry_comps, batch_size, fold_width, color, crafting_group );
             const int total_lines = info.size();
             line_recipe_info = clamp( line_recipe_info, 0, total_lines - dataLines );
             for( int i = line_recipe_info; i < std::min( line_recipe_info + dataLines, total_lines ); ++i ) {
                 nc_color dummy = color;
                 print_colored_text( w_data, point( xpos, i - line_recipe_info ), dummy, color, info[i] );
             }
             if( total_lines > dataLines ) {
                 scrollbar()
                 .offset_x( xpos + fold_width + 1 )
                 .content_size( total_lines )
                 .viewport_pos( line_recipe_info )
                 .viewport_size( dataLines )
                 .apply( w_data );
             }
         }
         scrollbar()
         .offset_x( 0 )
         .offset_y( 0 )
         .content_size( recmax )
         .viewport_pos( istart )
         .viewport_size( dataLines )
         .apply( w_data );
         wnoutrefresh( w_data );
         if( isWide && !current.empty() ) {
             const recipe *cur_recipe = current[line];
             werase( w_iteminfo );
             if( cur_recipe->is_practice() ) {
                 const std::string desc = practice_recipe_description( *cur_recipe, *crafter );
                 fold_and_print( w_iteminfo, point_zero, item_info_width, c_light_gray, desc );
                 scrollbar().offset_x( item_info_width - 1 ).offset_y( 0 ).content_size( 1 ).viewport_size( getmaxy(
                             w_iteminfo ) ).apply( w_iteminfo );
                 wnoutrefresh( w_iteminfo );
             } else if( cur_recipe->is_nested() ) {
                 std::string desc = cur_recipe->description.translated() + "\n\n";;
                 desc += list_nested( *crafter, cur_recipe, available_recipes );
                 fold_and_print( w_iteminfo, point_zero, item_info_width, c_light_gray, desc );
                 scrollbar().offset_x( item_info_width - 1 ).offset_y( 0 ).content_size( 1 ).viewport_size( getmaxy(
                             w_iteminfo ) ).apply( w_iteminfo );
                 wnoutrefresh( w_iteminfo );
             } else {
                 item_info_data data = result_info.get_result_data( cur_recipe, batch_size, line_item_info,
                                       w_iteminfo );
                 data.without_getch = true;
                 data.without_border = true;
                 data.scrollbar_left = false;
                 data.use_full_win = true;
                 data.padding = 0;
                 draw_item_info( w_iteminfo, data );
             }
         }
     } );
     do {
         if( recalc ) {
             // When we switch tabs, redraw the header
             recalc = false;
             const recipe *prev_rcp = nullptr;
             if( keepline && line >= 0 && static_cast<size_t>( line ) < current.size() ) {
                 prev_rcp = current[line];
             }
             show_hidden = false;
             available.clear();
             if( batch ) {
                 current.clear();
                 for( int i = 1; i <= 50; i++ ) {
                     current.push_back( chosen );
                     available.emplace_back( *crafter, chosen, i );
                 }
                 indent.assign( current.size(), 0 );
             } else {
                 static_popup popup;
                 std::chrono::steady_clock::time_point last_update = std::chrono::steady_clock::now();
                 static constexpr std::chrono::milliseconds update_interval( 500 );
                 std::function<void( size_t, size_t )> progress_callback =
                 [&]( size_t at, size_t out_of ) {
                     std::chrono::steady_clock::time_point now = std::chrono::steady_clock::now();
                     if( now - last_update < update_interval ) {
                         return;
                     }
                     last_update = now;
                     double percent = 100.0 * at / out_of;
                     popup.message( _( "Searching %3.0f%%\n" ), percent );
                     ui_manager::redraw();
                     refresh_display();
                     inp_mngr.pump_events();
                 };
                 std::vector<const recipe *> picking;
                 if( !filterstring.empty() ) {
                     std::string qry = trim( filterstring );
                     recipe_subset filtered_recipes =
                         filter_recipes( available_recipes, qry, *crafter, progress_callback );
                     picking.insert( picking.end(), filtered_recipes.begin(), filtered_recipes.end() );
                 } else {
                     const std::pair<std::vector<const recipe *>, bool> result = recipes_from_cat( available_recipes,
                             tab.cur(), subtab.cur() );
                     show_hidden = result.second;
                     if( show_hidden ) {
                         current = result.first;
                     } else {
                         picking = result.first;
                     }
                 }
                 if( !show_hidden ) {
                     current.clear();
                     for( const recipe *i : picking ) {
                         if( uistate.hidden_recipes.find( i->ident() ) == uistate.hidden_recipes.end() ) {
                             current.push_back( i );
                         }
                     }
                     num_hidden = picking.size() - current.size();
                     num_recipe = picking.size();
                 }
                 available.reserve( current.size() );
                 // cache recipe availability on first display
                 for( const recipe *e : current ) {
                     if( !availability_cache->count( e ) ) {
                         availability_cache->emplace( e, availability( *crafter, e ) );
                     }
                 }
                 if( subtab.cur() != "CSC_*_RECENT" ) {
                     std::stable_sort( current.begin(), current.end(), [
                        crafter, &availability_cache, unread_recipes_first,
                        highlight_unread_recipes
                     ]( const recipe * const a, const recipe * const b ) {
                         if( highlight_unread_recipes && unread_recipes_first ) {
                             const bool a_read = uistate.read_recipes.count( a->ident() );
                             const bool b_read = uistate.read_recipes.count( b->ident() );
                             if( a_read != b_read ) {
                                 return !a_read;
                             }
                         }
                         const bool can_craft_a = availability_cache->at( a ).can_craft;
                         const bool can_craft_b = availability_cache->at( b ).can_craft;
                         if( can_craft_a != can_craft_b ) {
                             return can_craft_a;
                         }
                         if( b->difficulty != a->difficulty ) {
                             return b->difficulty < a->difficulty;
                         }
                         const std::string a_name = a->result_name();
                         const std::string b_name = b->result_name();
                         if( a_name != b_name ) {
                             return localized_compare( a_name, b_name );
                         }
                         return b->time_to_craft( *crafter ) <
                                a->time_to_craft( *crafter );
                     } );
                 }
                 // set up indents and append the expanded entries
                 // have to do this after we sort the list
                 indent.assign( current.size(), 0 );
                 expand_recipes( current, indent, *availability_cache, *crafter, unread_recipes_first,
                                 highlight_unread_recipes, available_recipes, uistate.hidden_recipes );
                 std::transform( current.begin(), current.end(),
                 std::back_inserter( available ), [&]( const recipe * e ) {
                     return availability_cache->at( e );
                 } );
             }
             line = 0;
             if( keepline && prev_rcp ) {
                 // point to previously selected recipe
                 int rcp_idx = 0;
                 for( const recipe *const rcp : current ) {
                     if( rcp == prev_rcp ) {
                         line = rcp_idx;
                         break;
                     }
                     ++rcp_idx;
                 }
             }
         }
         keepline = false;
         if( highlight_unread_recipes && !current.empty() && user_moved_line ) {
             // only automatically mark as read when moving cursor up or down by
             // one line, which means that the user is likely reading through the
             // list.
             user_moved_line = false;
             uistate.read_recipes.insert( current[line]->ident() );
             if( last_line != -1 ) {
                 uistate.read_recipes.insert( current[last_line]->ident() );
                 last_line = -1;
             }
             recalc_unread = true;
         }
         const bool previously_toggled_unread = just_toggled_unread;
         just_toggled_unread = false;
         ui_manager::redraw();
         const int scroll_item_info_lines = catacurses::getmaxy( w_iteminfo ) - 4;
         std::string action = ctxt.handle_input();
         const int recmax = static_cast<int>( current.size() );
         const int scroll_rate = recmax > 20 ? 10 : 3;
         std::optional<point> coord = ctxt.get_coordinates_text( catacurses::stdscr );
         const bool mouse_in_list = coord.has_value() && mouseover_area_list.contains( coord.value() );
         const bool mouse_in_recipe = coord.has_value() && mouseover_area_recipe.contains( coord.value() );
         // Check mouse selection of recipes separately so that selecting an already-selected recipe
         // can go straight to "CONFIRM"
         if( action == "SELECT" ) {
             if( coord.has_value() ) {
                 point local_coord = coord.value() - point( getbegx( w_data ), getbegy( w_data ) );
                 for( const auto &entry : list_map ) {
                     if( entry.second.contains( local_coord ) ) {
                         if( line == static_cast<int>( entry.first ) ) {
                             action = "CONFIRM";
                         } else {
                             if( !previously_toggled_unread ) {
                                 last_line = line;
                             }
                             line = entry.first;
                             user_moved_line = highlight_unread_recipes;
                         }
                     }
                 }
             }
         }
         if( action == "SELECT" ) {
             bool handled = false;
             if( coord.has_value() ) {
                 point local_coord = coord.value() - point( getbegx( w_head_tabs ), getbegy( w_head_tabs ) );
                 for( const auto &entry : translated_tab_map ) {
                     if( entry.second.contains( local_coord ) ) {
                         tab.set_index( entry.first );
                         recalc = true;
                         subtab = tab_list( craft_subcat_list[tab.cur()] );
                         handled = true;
                     }
                 }
                 local_coord = coord.value() - point( getbegx( w_subhead ), getbegy( w_subhead ) );
                 if( !handled && !batch && filterstring.empty() ) {
                     for( const auto &entry : translated_subtab_map ) {
                         if( entry.second.contains( local_coord ) ) {
                             subtab.set_index( entry.first );
                             recalc = true;
                         }
                     }
                 }
             }
         } else if( action == "SCROLL_RECIPE_INFO_UP" ) {
             line_recipe_info -= dataLines;
         } else if( action == "SCROLL_UP" && mouse_in_recipe ) {
             --line_recipe_info;
         } else if( action == "SCROLL_RECIPE_INFO_DOWN" ) {
             line_recipe_info += dataLines;
         } else if( action == "SCROLL_DOWN" && mouse_in_recipe ) {
             ++line_recipe_info;
         } else if( action == "LEFT" || ( action == "SCROLL_UP" && mouse_in_window( coord, w_subhead ) ) ) {
             if( batch || !filterstring.empty() ) {
                 continue;
             }
             std::string start = subtab.cur();
             do {
                 subtab.prev();
             } while( subtab.cur() != start && available_recipes.empty_category( tab.cur(),
                      subtab.cur() != "CSC_ALL" ? subtab.cur() : "" ) );
             recalc = true;
         } else if( action == "SCROLL_ITEM_INFO_UP" ) {
             line_item_info -= scroll_item_info_lines;
         } else if( action == "SCROLL_UP" && mouse_in_window( coord, w_iteminfo ) ) {
             --line_item_info;
         } else if( action == "SCROLL_ITEM_INFO_DOWN" ) {
             line_item_info += scroll_item_info_lines;
         } else if( action == "SCROLL_DOWN" && mouse_in_window( coord, w_iteminfo ) ) {
             ++line_item_info;
         } else if( action == "PREV_TAB" || ( action == "SCROLL_UP" &&
                                              mouse_in_window( coord, w_head_tabs ) ) ) {
             tab.prev();
             // Default ALL
             subtab = tab_list( craft_subcat_list[tab.cur()] );
             recalc = true;
         } else if( action == "RIGHT" || ( action == "SCROLL_DOWN" &&
                                           mouse_in_window( coord, w_subhead ) ) ) {
             if( batch || !filterstring.empty() ) {
                 continue;
             }
             std::string start = subtab.cur();
             do {
                 subtab.next();
             } while( subtab.cur() != start && available_recipes.empty_category( tab.cur(),
                      subtab.cur() != "CSC_ALL" ? subtab.cur() : "" ) );
             recalc = true;
         } else if( action == "NEXT_TAB" || ( action == "SCROLL_DOWN" &&
                                              mouse_in_window( coord, w_head_tabs ) ) ) {
             tab.next();
             // Default ALL
             subtab = tab_list( craft_subcat_list[tab.cur()] );
             recalc = true;
         } else if( action == "DOWN" ) {
             if( !previously_toggled_unread ) {
                 last_line = line;
             }
             line++;
             user_moved_line = highlight_unread_recipes;
         } else if( action == "SCROLL_DOWN" && mouse_in_list ) {
             line = std::min( recmax - 1, line + 1 );
         } else if( action == "UP" ) {
             if( !previously_toggled_unread ) {
                 last_line = line;
             }
             line--;
             user_moved_line = highlight_unread_recipes;
         } else if( action == "SCROLL_UP" && mouse_in_list ) {
             line = std::max( 0, line - 1 );
         } else if( action == "PAGE_UP" || action == "PAGE_DOWN" ) {
             line = inc_clamp( line, action == "PAGE_UP" ? -scroll_rate : scroll_rate, recmax );
         } else if( action == "HOME" ) {
             line = 0;
             user_moved_line = highlight_unread_recipes;
         } else if( action == "END" ) {
             line = -1;
             user_moved_line = highlight_unread_recipes;
         } else if( action == "CONFIRM" ) {
             if( available.empty() ) {
                 popup( _( "Nothing selected!" ) );
             } else if( current[line]->is_nested() ) {
                 nested_toggle( current[line]->ident(), recalc, keepline );
             } else if( !available[line].can_craft ||
                        !available[line].crafter_has_primary_skill ) {
                 popup( _( "Crafter can't craft that!" ) );
             } else if( !crafter->check_eligible_containers_for_crafting( *current[line],
                        batch ? line + 1 : 1 ) ) {
                 // popup is already inside check
             } else if( crafter->lighting_craft_speed_multiplier( *current[line] ) <= 0.0f ) {
                 popup( _( "Crafter can't see!" ) );
             } else {
                 chosen = current[line];
                 batch_size_out = batch ? line + 1 : 1;
                 done = true;
                 uistate.read_recipes.insert( chosen->ident() );
             }
         } else if( action == "HELP_RECIPE" && selection_ok( current, line, false ) ) {
             uistate.read_recipes.insert( current[line]->ident() );
             recalc_unread = highlight_unread_recipes;
             ui.invalidate_ui();
             item_info_data data = result_info.get_result_data( current[line], 1, line_item_info_popup,
                                   w_iteminfo );
             data.handle_scrolling = true;
             draw_item_info( []() -> catacurses::window {
                 const int width = std::min( TERMX, FULL_SCREEN_WIDTH );
                 const int height = std::min( TERMY, FULL_SCREEN_HEIGHT );
                 return catacurses::newwin( height, width, point( ( TERMX - width ) / 2, ( TERMY - height ) / 2 ) );
             }, data );
         } else if( action == "FILTER" ) {
             int max_example_length = 0;
             for( const auto &prefix : prefixes ) {
                 max_example_length = std::max( max_example_length, utf8_width( prefix.example.translated() ) );
             }
             std::string spaces( max_example_length, ' ' );
             std::string description = filter_help_start.translated();
             {
                 std::string example_name = _( "shirt" );
                 int padding = max_example_length - utf8_width( example_name );
                 description += string_format(
                                    _( "  <color_white>%s</color>%.*s    %s\n" ),
                                    example_name, padding, spaces,
                                    _( "<color_cyan>name</color> of resulting item" ) );
                 std::string example_exclude = _( "clean" );
                 padding = max_example_length - utf8_width( example_exclude );
                 description += string_format(
                                    _( "  <color_yellow>-</color><color_white>%s</color>%.*s   %s\n" ),
                                    example_exclude, padding, spaces,
                                    _( "<color_cyan>names</color> to exclude" ) );
             }
             for( const auto &prefix : prefixes ) {
                 int padding = max_example_length - utf8_width( prefix.example.translated() );
                 description += string_format(
                                    _( "  <color_yellow>%c</color><color_white>:%s</color>%.*s  %s\n" ),
                                    prefix.key, prefix.example, padding, spaces, prefix.description );
             }
             description +=
                 _( "\nUse <color_red>up/down arrow</color> to go through your search history." );
             string_input_popup popup;
             popup
             .title( _( "Search:" ) )
             .width( 85 )
             .description( description )
             .desc_color( c_light_gray )
             .identifier( "craft_recipe_filter" )
             .hist_use_uilist( false )
             .edit( filterstring );
             if( popup.confirmed() ) {
                 recalc = true;
                 recalc_unread = highlight_unread_recipes;
                 if( batch ) {
                     // exit from batch selection
                     batch = false;
                     line = batch_line;
                 }
             }
         } else if( action == "QUIT" ) {
             chosen = nullptr;
             done = true;
         } else if( action == "RESET_FILTER" ) {
             filterstring.clear();
             recalc = true;
             recalc_unread = highlight_unread_recipes;
         } else if( action == "CYCLE_BATCH" && selection_ok( current, line, false ) ) {
             batch = !batch;
             if( batch ) {
                 batch_line = line;
                 chosen = current[batch_line];
                 uistate.read_recipes.insert( chosen->ident() );
                 recalc_unread = highlight_unread_recipes;
             } else {
                 keepline = true;
             }
             recalc = true;
         } else if( action == "CHOOSE_CRAFTER" ) {
             // allow for switching crafter when no recipes are shown (e.g. filter)
             bool rec_valid = !current.empty();
             const recipe *rec = rec_valid ? current[line] : nullptr;
             int new_crafter_i = choose_crafter( crafting_group, crafter_i, rec, rec_valid );
             if( new_crafter_i >= 0 && new_crafter_i != crafter_i ) {
                 crafter_i = new_crafter_i;
                 crafter = crafting_group[crafter_i];
                 // next line also inserts empty cache for crafter->getID() if non existant
                 availability_cache = &guy_availability_cache[crafter->getID()];
                 recalc = true;
                 keepline = true;
             }
         } else if( action == "TOGGLE_FAVORITE" && selection_ok( current, line, true ) ) {
             keepline = true;
             recalc = filterstring.empty() && subtab.cur() == "CSC_*_FAVORITE";
             if( uistate.favorite_recipes.find( current[line]->ident() ) != uistate.favorite_recipes.end() ) {
                 uistate.favorite_recipes.erase( current[line]->ident() );
                 if( recalc ) {
                     if( static_cast<size_t>( line ) + 1 < current.size() ) {
                         line++;
                     } else {
                         line--;
                     }
                 }
             } else {
                 uistate.favorite_recipes.insert( current[line]->ident() );
                 uistate.read_recipes.insert( current[line]->ident() );
             }
             recalc_unread = highlight_unread_recipes;
         } else if( action == "HIDE_SHOW_RECIPE" && selection_ok( current, line, true ) ) {
             if( show_hidden ) {
                 uistate.hidden_recipes.erase( current[line]->ident() );
             } else {
                 uistate.hidden_recipes.insert( current[line]->ident() );
                 uistate.read_recipes.insert( current[line]->ident() );
             }
             recalc = true;
             recalc_unread = highlight_unread_recipes;
             keepline = true;
             if( static_cast<size_t>( line ) + 1 < current.size() ) {
                 line++;
             } else {
                 line--;
             }
         } else if( action == "TOGGLE_RECIPE_UNREAD" && selection_ok( current, line, true ) ) {
             const recipe_id rcp = current[line]->ident();
             if( uistate.read_recipes.count( rcp ) ) {
                 uistate.read_recipes.erase( rcp );
             } else {
                 uistate.read_recipes.insert( rcp );
             }
             recalc_unread = highlight_unread_recipes;
             just_toggled_unread = true;
         } else if( action == "MARK_ALL_RECIPES_READ" ) {
             bool current_list_has_unread = false;
             for( const recipe *const rcp : current ) {
                 if( !uistate.read_recipes.count( rcp->ident() ) ) {
                     current_list_has_unread = true;
                     break;
                 }
             }
             std::string query_str;
             if( !current_list_has_unread ) {
                 query_str = _( "<color_yellow>/!\\</color> Mark all recipes as read?  "
                                // NOLINTNEXTLINE(cata-text-style): single spaced for symmetry
                                "This cannot be undone. <color_yellow>/!\\</color>" );
             } else if( filterstring.empty() ) {
                 query_str = string_format( _( "Mark recipes in this tab as read?  This cannot be undone.  "
                                               "You can mark all recipes by choosing yes and pressing %s again." ),
                                            ctxt.get_desc( "MARK_ALL_RECIPES_READ" ) );
             } else {
                 query_str = string_format( _( "Mark filtered recipes as read?  This cannot be undone.  "
                                               "You can mark all recipes by choosing yes and pressing %s again." ),
                                            ctxt.get_desc( "MARK_ALL_RECIPES_READ" ) );
             }
             if( query_yn( query_str ) ) {
                 if( current_list_has_unread ) {
                     for( const recipe *const rcp : current ) {
                         uistate.read_recipes.insert( rcp->ident() );
                     }
                 } else {
                     for( const recipe *const rcp : available_recipes ) {
                         uistate.read_recipes.insert( rcp->ident() );
                     }
                 }
             }
             recalc_unread = highlight_unread_recipes;
         } else if( action == "TOGGLE_UNREAD_RECIPES_FIRST" ) {
             unread_recipes_first = !unread_recipes_first;
             recalc = true;
             keepline = true;
         } else if( action == "RELATED_RECIPES" && selection_ok( current, line, false ) ) {
             uistate.read_recipes.insert( current[line]->ident() );
             recalc_unread = highlight_unread_recipes;
             ui.invalidate_ui();
             std::string recipe_name = peek_related_recipe( current[line], available_recipes, *crafter );
             if( !recipe_name.empty() ) {
                 filterstring = recipe_name;
                 recalc = true;
                 recalc_unread = highlight_unread_recipes;
             }
         } else if( action == "COMPARE" && selection_ok( current, line, false ) ) {
             const item recipe_result = get_recipe_result_item( *current[line], *crafter );
             compare_recipe_with_item( recipe_result, *crafter );
         } else if( action == "HELP_KEYBINDINGS" ) {
             // Regenerate keybinding tips
             ui.mark_resize();
         }
         if( line < 0 ) {
             line = current.size() - 1;
         } else if( line >= static_cast<int>( current.size() ) ) {
             line = 0;
         }
     } while( !done );
     return { crafter, chosen };
 }
References _, act, input_context::allow_all_keys(), scrollbar::apply(), available, BATCH, BORDER_COLOR, c_light_gray, c_light_green, c_white, cached_recipe_info(), recipe::category, clamp(), color(), scrollbar::content_size(), craft_cat_list, craft_subcat_list, tab_list::cur_index(), debugmsg, recipe::description, draw_can_craft_indicator(), draw_hidden_amount(), draw_item_info(), draw_recipe_subtabs(), draw_recipe_tabs(), enumerate_as_string(), FILTERED, fold_and_print(), foldstring(), FULL_SCREEN_WIDTH, Character::get_crafting_group(), input_context::get_desc(), Character::get_group_available_recipes(), recipe_result_info_cache::get_result_data(), catacurses::getbegx(), Character::getID(), catacurses::getmaxy(), uistatedata::hidden_recipes, recipe::ident(), recipe_subset::in_category(), recipe::is_nested(), recipe::is_practice(), string_id< T >::is_valid(), isWide, line(), LINE_OXOX, LINE_XOOX, LINE_XOXO, LINE_XXOO, list_nested(), make_crafting_context(), max(), min(), mvwprintz(), mvwputch(), catacurses::newwin(), none, NORMAL, scrollbar::offset_x(), scrollbar::offset_y(), item_info_data::padding, pgettext, point_zero, practice_recipe_description(), print_colored_text(), uistatedata::read_recipes, item_info_data::scrollbar_left, string_format(), subindex_around_cursor(), keycode::tab, TERMX, TERMY, translation::translated(), trim(), trim_by_length(), uistate, item_info_data::use_full_win, utf8_width(), scrollbar::viewport_pos(), scrollbar::viewport_size(), catacurses::werase(), item_info_data::without_border, item_info_data::without_getch, and catacurses::wnoutrefresh().
Referenced by Character::craft(), and Character::long_craft().
subcategories_for_category()
const std::vector<std::string>* subcategories_for_category (const std::string & category)
Definition at line 2441 of file crafting_gui.cpp.
 {
     auto it = craft_subcat_list.find( category );
     if( it != craft_subcat_list.end() ) {
         return &it->second;
     }
     return nullptr;
 }
References anonymous_namespace{item_tname.cpp}::category(), and craft_subcat_list.
Referenced by recipe_dictionary::check_consistency().