Cataclysm DDA: src/crafting.h File Reference
crafting.h File Reference
#include <list>
Classes
struct enum_traits< craft_flags >
Macros
#define CATA_SRC_CRAFTING_H
Enumerations
enum class craft_flags : int { none = 0 , start_only = 1 }
Functions
void remove_ammo (item &dis_item, Character &p)
void remove_ammo (std::list< item > &dis_items, Character &p)
void drop_or_handle (const item &newit, Character &p)
Macro Definition Documentation
CATA_SRC_CRAFTING_H
#define CATA_SRC_CRAFTING_H
Definition at line 3 of file crafting.h.
Enumeration Type Documentation
craft_flags
enum craft_flags : int strong
Enumerator
none
start_only
Definition at line 11 of file crafting.h.
                        : int {
     none = 0,
     start_only = 1, // Only require 5% (plus remainder) of tool charges
 };
Function Documentation
drop_or_handle()
void drop_or_handle (const item & newit, Character & p)
Definition at line 3010 of file crafting.cpp.
 {
     if( newit.made_of( phase_id::LIQUID ) && p.is_avatar() ) { // TODO: what about NPCs?
         liquid_handler::handle_all_liquid( newit, PICKUP_RANGE );
     } else {
         item tmp( newit );
         p.i_add_or_drop( tmp );
     }
 }
References liquid_handler::handle_all_liquid(), Character::i_add_or_drop(), Creature::is_avatar(), LIQUID, item::made_of(), and PICKUP_RANGE.
Referenced by empty_buckets(), item_pocket::remove_all_ammo(), and remove_ammo().
remove_ammo() [1/2]
void remove_ammo (item & dis_item, Character & p)
Definition at line 3020 of file crafting.cpp.
 {
     dis_item.remove_items_with( [&p]( const item & it ) {
         if( it.is_irremovable() || !( it.is_gunmod() || it.is_toolmod() || ( it.is_magazine() &&
                                       !it.is_tool() ) ) ) {
             return false;
         }
         drop_or_handle( it, p );
         return true;
     } );
     if( dis_item.has_flag( flag_NO_UNLOAD ) ) {
         return;
     }
     if( dis_item.is_gun() && !dis_item.ammo_current().is_null() ) {
         item ammodrop( dis_item.ammo_current(), calendar::turn );
         ammodrop.charges = dis_item.charges;
         drop_or_handle( ammodrop, p );
         dis_item.charges = 0;
     }
     if( dis_item.is_tool() && dis_item.charges > 0 && !dis_item.ammo_current().is_null() ) {
         item ammodrop( dis_item.ammo_current(), calendar::turn );
         ammodrop.charges = dis_item.charges;
         if( dis_item.ammo_current() == itype_plut_cell ) {
             ammodrop.charges /= PLUTONIUM_CHARGES;
         }
         drop_or_handle( ammodrop, p );
         dis_item.charges = 0;
     }
 }
References item::ammo_current(), item::charges, drop_or_handle(), flag_NO_UNLOAD, item::has_flag(), item::is_gun(), item::is_gunmod(), item::is_irremovable(), item::is_magazine(), string_id< T >::is_null(), item::is_tool(), item::is_toolmod(), itype_plut_cell, PLUTONIUM_CHARGES, item::remove_items_with(), and calendar::turn.
remove_ammo() [2/2]
void remove_ammo (std::list< item > & dis_items, Character & p)
Definition at line 3003 of file crafting.cpp.
 {
     for( item &dis_item : dis_items ) {
         remove_ammo( dis_item, p );
     }
 }
Referenced by Character::consume_items(), Character::create_in_progress_disassembly(), and salvage_actor::cut_up().