Cataclysm DDA: src/creature.cpp File Reference
creature.cpp File Reference
#include "creature.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdlib>
#include <functional>
#include <map>
#include <memory>
#include <optional>
#include <stack>
#include <string>
#include <tuple>
#include "anatomy.h"
#include "body_part_set.h"
#include "cached_options.h"
#include "calendar.h"
#include "cata_assert.h"
#include "cata_utility.h"
#include "cata_variant.h"
#include "character.h"
#include "character_attire.h"
#include "character_id.h"
#include "color.h"
#include "creature_tracker.h"
#include "cursesdef.h"
#include "damage.h"
#include "debug.h"
#include "effect.h"
#include "enum_traits.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "explosion.h"
#include "field.h"
#include "flat_set.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "game.h"
#include "game_constants.h"
#include "item.h"
#include "item_location.h"
#include "json_error.h"
#include "level_cache.h"
#include "lightmap.h"
#include "line.h"
#include "localized_comparator.h"
#include "magic_enchantment.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "mattack_common.h"
#include "mdarray.h"
#include "messages.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "point.h"
#include "projectile.h"
#include "rng.h"
#include "sounds.h"
#include "talker.h"
#include "talker_avatar.h"
#include "talker_character.h"
#include "talker_monster.h"
#include "talker_npc.h"
#include "translation.h"
#include "translations.h"
#include "units.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "vpart_position.h"
Classes
struct projectile_attack_results
class anonymous_namespace{creature.cpp}::type_identity< T >
Namespaces
anonymous_namespace{creature.cpp}
Functions
static bool majority_rule (const bool a_vote, const bool b_vote, const bool c_vote)
static bool overlaps_vehicle (const std::set< tripoint > &veh_area, const tripoint &pos, const int area)
template<typename T >
static T get_part_helper (const Creature &c, const bodypart_id &id, T(bodypart::*get)() const)
template<typename T >
static void set_part_helper (Creature &c, const bodypart_id &id, void(bodypart::*set)(T), typename type_identity< T >::type val)
static void sort_body_parts (std::vector< bodypart_id > &bps, const Creature *c)
std::unique_ptr< talker > get_talker_for (Creature &me)
std::unique_ptr< talker > get_talker_for (const Creature &me)
std::unique_ptr< talker > get_talker_for (Creature *me)
Variables
static const anatomy_id anatomy_human_anatomy ("human_anatomy")
static const damage_type_id damage_acid ("acid")
static const damage_type_id damage_bash ("bash")
static const damage_type_id damage_electric ("electric")
static const damage_type_id damage_heat ("heat")
static const efftype_id effect_all_fours ("all_fours")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_bounced ("bounced")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_foamcrete_slow ("foamcrete_slow")
static const efftype_id effect_invisibility ("invisibility")
static const efftype_id effect_knockdown ("knockdown")
static const efftype_id effect_lying_down ("lying_down")
static const efftype_id effect_no_sight ("no_sight")
static const efftype_id effect_npc_suspend ("npc_suspend")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_paralyzepoison ("paralyzepoison")
static const efftype_id effect_ridden ("ridden")
static const efftype_id effect_riding ("riding")
static const efftype_id effect_sap ("sap")
static const efftype_id effect_sensor_stun ("sensor_stun")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_stumbled_into_invisible ("stumbled_into_invisible")
static const efftype_id effect_stunned ("stunned")
static const efftype_id effect_telepathic_ignorance ("telepathic_ignorance")
static const efftype_id effect_telepathic_ignorance_self ("telepathic_ignorance_self")
static const efftype_id effect_tied ("tied")
static const efftype_id effect_zapped ("zapped")
static const field_type_str_id field_fd_last_known ("fd_last_known")
static const json_character_flag json_flag_BIONIC_LIMB ("BIONIC_LIMB")
static const json_character_flag json_flag_IGNORE_TEMP ("IGNORE_TEMP")
static const json_character_flag json_flag_LIMB_LOWER ("LIMB_LOWER")
static const json_character_flag json_flag_LIMB_UPPER ("LIMB_UPPER")
static const material_id material_cotton ("cotton")
static const material_id material_flesh ("flesh")
static const material_id material_iflesh ("iflesh")
static const material_id material_kevlar ("kevlar")
static const material_id material_paper ("paper")
static const material_id material_powder ("powder")
static const material_id material_steel ("steel")
static const material_id material_stone ("stone")
static const material_id material_veggy ("veggy")
static const material_id material_wood ("wood")
static const material_id material_wool ("wool")
static const species_id species_ROBOT ("ROBOT")
static const trait_id trait_DEBUG_CLOAK ("DEBUG_CLOAK")
static const trait_id trait_PYROMANIA ("PYROMANIA")
Function Documentation
get_part_helper()
template<typename T > static T get_part_helper (const Creature & c, const bodypart_id & id, T(bodypart::*)() const get) static
Definition at line 2206 of file creature.cpp.
 {
     const bodypart *const part = c.get_part( id );
     if( part ) {
         return ( part->*get )();
     } else {
         // If the bodypart doesn't exist, return the appropriate accessor on the null bodypart.
         // Static null bodypart variable, otherwise the compiler notes the possible return of local variable address (#42798).
         static const bodypart bp_null;
         return ( bp_null.*get )();
     }
 }
References c, and rotatable_symbols::get().
Referenced by Creature::get_part_damage_bandaged(), Creature::get_part_damage_disinfected(), Creature::get_part_drench_capacity(), Creature::get_part_encumbrance_data(), Creature::get_part_frostbite_timer(), Creature::get_part_healed_total(), Creature::get_part_hp_cur(), Creature::get_part_hp_max(), Creature::get_part_mut_drench(), Creature::get_part_temp_conv(), Creature::get_part_temp_cur(), Creature::get_part_wetness(), Creature::get_part_wetness_percentage(), and Creature::is_part_at_max_hp().
get_talker_for() [1/3]
std::unique_ptr<talker> get_talker_for (const Creature & me)
Definition at line 3261 of file creature.cpp.
 {
     if( !me.is_monster() ) {
         return std::make_unique<talker_character_const>( me.as_character() );
     } else if( me.is_monster() ) {
         return std::make_unique<talker_monster_const>( me.as_monster() );
     } else {
         debugmsg( "Invalid creature type %s.", me.get_name() );
         return std::make_unique<talker>();
     }
 }
References Creature::as_character(), Creature::as_monster(), debugmsg, Creature::get_name(), and Creature::is_monster().
get_talker_for() [2/3]
std::unique_ptr<talker> get_talker_for (Creature & me)
Definition at line 3247 of file creature.cpp.
 {
     if( me.is_monster() ) {
         return std::make_unique<talker_monster>( me.as_monster() );
     } else if( me.is_npc() ) {
         return std::make_unique<talker_npc>( me.as_npc() );
     } else if( me.is_avatar() ) {
         return std::make_unique<talker_avatar>( me.as_avatar() );
     } else {
         debugmsg( "Invalid creature type %s.", me.get_name() );
         return std::make_unique<talker>();
     }
 }
References Creature::as_avatar(), Creature::as_monster(), Creature::as_npc(), debugmsg, Creature::get_name(), Creature::is_avatar(), Creature::is_monster(), and Creature::is_npc().
get_talker_for() [3/3]
std::unique_ptr<talker> get_talker_for (Creature * me)
Definition at line 3273 of file creature.cpp.
 {
     if( !me ) {
         debugmsg( "Null creature type." );
         return std::make_unique<talker>();
     } else if( me->is_monster() ) {
         return std::make_unique<talker_monster>( me->as_monster() );
     } else if( me->is_npc() ) {
         return std::make_unique<talker_npc>( me->as_npc() );
     } else if( me->is_avatar() ) {
         return std::make_unique<talker_avatar>( me->as_avatar() );
     } else {
         debugmsg( "Invalid creature type %s.", me->get_name() );
         return std::make_unique<talker>();
     }
 }
References Creature::as_avatar(), Creature::as_monster(), Creature::as_npc(), debugmsg, Creature::get_name(), Creature::is_avatar(), Creature::is_monster(), and Creature::is_npc().
majority_rule()
static bool majority_rule (const bool a_vote, const bool b_vote, const bool c_vote) static
Definition at line 352 of file creature.cpp.
 {
     // Helper function suggested on discord by jbtw
     return ( a_vote + b_vote + c_vote ) > 1;
 }
Referenced by Creature::sees().
overlaps_vehicle()
static bool overlaps_vehicle (const std::set< tripoint > & veh_area, const tripoint & pos, const int area) static
Definition at line 541 of file creature.cpp.
 {
     for( const tripoint &tmp : tripoint_range<tripoint>( pos - tripoint( area, area, 0 ),
             pos + tripoint( area - 1, area - 1, 0 ) ) ) {
         if( veh_area.count( tmp ) > 0 ) {
             return true;
         }
     }
     return false;
 }
References math_opers::pos(), and tripoint.
Referenced by Creature::auto_find_hostile_target().
set_part_helper()
template<typename T > static void set_part_helper (Creature & c, const bodypart_id & id, void(bodypart::*)(T) set, typename type_identity< T >::type val) static
Definition at line 2231 of file creature.cpp.
 {
     bodypart *const part = c.get_part( id );
     if( part ) {
         ( part->*set )( val );
     }
 }
References c.
Referenced by Creature::mod_part_damage_bandaged(), Creature::mod_part_damage_disinfected(), Creature::mod_part_frostbite_timer(), Creature::mod_part_healed_total(), Creature::mod_part_hp_cur(), Creature::mod_part_hp_max(), Creature::mod_part_temp_conv(), Creature::mod_part_temp_cur(), Creature::mod_part_wetness(), Creature::set_part_damage_bandaged(), Creature::set_part_damage_disinfected(), Creature::set_part_encumbrance_data(), Creature::set_part_frostbite_timer(), Creature::set_part_healed_total(), Creature::set_part_hp_cur(), Creature::set_part_hp_max(), Creature::set_part_mut_drench(), Creature::set_part_temp_conv(), Creature::set_part_temp_cur(), and Creature::set_part_wetness().
sort_body_parts()
static void sort_body_parts (std::vector< bodypart_id > & bps, const Creature * c) static
Definition at line 2513 of file creature.cpp.
 {
     // We want to dynamically sort the parts based on their connections as
     // defined in json.
     // The goal is to performa a pre-order depth-first traversal starting
     // with the root part (the head) and prioritising children with fewest
     // descendants.
     // First build a map with the reverse connections
     std::unordered_map<bodypart_id, cata::flat_set<bodypart_id>> parts_connected_to;
     bodypart_id root_part;
     for( const bodypart_id &bp : bps ) {
         bodypart_id conn = c->get_part_id( bp->connected_to );
         if( conn == bp ) {
             root_part = bp;
         } else {
             parts_connected_to[conn].insert( bp );
         }
     }
     if( root_part == bodypart_id() ) {
         debugmsg( "No root part in body" );
         return;
     }
     // Topo-sort the parts from the extremities towards the head
     std::unordered_map<bodypart_id, cata::flat_set<bodypart_id>> unaccounted_parts =
                 parts_connected_to;
     cata::flat_set<bodypart_id> parts_with_no_connections;
     for( const bodypart_id &bp : bps ) {
         if( unaccounted_parts[bp].empty() ) {
             parts_with_no_connections.insert( bp );
         }
     }
     std::vector<bodypart_id> topo_sorted_parts;
     while( !parts_with_no_connections.empty() ) {
         auto last = parts_with_no_connections.end();
         --last;
         bodypart_id bp = *last;
         parts_with_no_connections.erase( last );
         unaccounted_parts.erase( bp );
         topo_sorted_parts.push_back( bp );
         bodypart_id conn = c->get_part_id( bp->connected_to );
         if( conn == bp ) {
             break;
         }
         auto conn_it = unaccounted_parts.find( conn );
         cata_assert( conn_it != unaccounted_parts.end() );
         conn_it->second.erase( bp );
         if( conn_it->second.empty() ) {
             parts_with_no_connections.insert( conn );
         }
     }
     if( !unaccounted_parts.empty() || !parts_with_no_connections.empty() ) {
         debugmsg( "Error in topo-sorting bodyparts: unaccounted_parts.size() == %d; "
                   "parts_with_no_connections.size() == %d", unaccounted_parts.size(),
                   parts_with_no_connections.size() );
         return;
     }
     // Using the topo-sorted parts, we can count the descendants of each
     // part
     std::unordered_map<bodypart_id, int> num_descendants;
     for( const bodypart_id &bp : topo_sorted_parts ) {
         int this_num_descendants = 1;
         for( const bodypart_id &child : parts_connected_to[bp] ) {
             this_num_descendants += num_descendants[child];
         }
         num_descendants[bp] = this_num_descendants;
     }
     // Finally, we can do the depth-first traversal:
     std::vector<bodypart_id> result;
     std::stack<bodypart_id> pending;
     pending.push( root_part );
     const auto compare_children = [&]( const bodypart_id & l, const bodypart_id & r ) {
         std::string l_name = l->name.translated();
         std::string r_name = r->name.translated();
         bodypart_id l_opp = l->opposite_part;
         bodypart_id r_opp = r->opposite_part;
         // Sorting first on the min of the name and opposite's name ensures
         // that we put pairs together in the list.
         std::string l_min_name = std::min( l_name, l_opp->name.translated(), localized_compare );
         std::string r_min_name = std::min( r_name, r_opp->name.translated(), localized_compare );
         // We delibarately reverse the comparison because the elements get
         // reversed below when they are transferred from the vector to the
         // stack.
         return localized_compare(
                    std::make_tuple( num_descendants[r], r_min_name, r_name ),
                    std::make_tuple( num_descendants[l], l_min_name, l_name ) );
     };
     while( !pending.empty() ) {
         bodypart_id next = pending.top();
         pending.pop();
         result.push_back( next );
         const cata::flat_set<bodypart_id> children_set = parts_connected_to.at( next );
         std::vector<bodypart_id> children( children_set.begin(), children_set.end() );
         std::sort( children.begin(), children.end(), compare_children );
         for( const bodypart_id &child : children ) {
             pending.push( child );
         }
     }
     cata_assert( bps.size() == result.size() );
     bps = result;
 }
References cata::flat_set< T, Compare, Data >::begin(), bp, c, cata_assert, body_part_type::connected_to, debugmsg, cata::flat_set< T, Compare, Data >::end(), cata::flat_set< T, Compare, Data >::erase(), cata::flat_set< T, Compare, Data >::insert(), last, localized_compare, min(), body_part_type::name, body_part_type::opposite_part, pending, and translation::translated().
Referenced by Creature::get_all_body_parts(), and Creature::get_all_body_parts_of_type().
Variable Documentation
anatomy_human_anatomy
const anatomy_id anatomy_human_anatomy("human_anatomy") ("human_anatomy") static
Referenced by Creature::deal_melee_hit().
damage_acid
const damage_type_id damage_acid("acid") ("acid") static
Referenced by Creature::deal_damage_handle_type().
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by Creature::deal_damage_handle_type().
damage_electric
const damage_type_id damage_electric("electric") ("electric") static
Referenced by Creature::deal_damage_handle_type().
damage_heat
const damage_type_id damage_heat("heat") ("heat") static
Referenced by Creature::deal_damage_handle_type().
effect_all_fours
const efftype_id effect_all_fours("all_fours") ("all_fours") static
Referenced by Creature::sees().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
effect_bounced
const efftype_id effect_bounced("bounced") ("bounced") static
Referenced by projectile::apply_effects_nodamage().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by projectile::apply_effects_damage().
effect_foamcrete_slow
const efftype_id effect_foamcrete_slow("foamcrete_slow") ("foamcrete_slow") static
effect_invisibility
const efftype_id effect_invisibility("invisibility") ("invisibility") static
Referenced by Creature::sees().
effect_knockdown
const efftype_id effect_knockdown("knockdown") ("knockdown") static
Referenced by Creature::add_effect().
effect_lying_down
const efftype_id effect_lying_down("lying_down") ("lying_down") static
Referenced by Creature::in_sleep_state().
effect_no_sight
const efftype_id effect_no_sight("no_sight") ("no_sight") static
Referenced by Creature::sees().
effect_npc_suspend
const efftype_id effect_npc_suspend("npc_suspend") ("npc_suspend") static
Referenced by Creature::in_sleep_state().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by projectile::apply_effects_damage(), and Creature::deal_damage_handle_type().
effect_paralyzepoison
const efftype_id effect_paralyzepoison("paralyzepoison") ("paralyzepoison") static
effect_ridden
const efftype_id effect_ridden("ridden") ("ridden") static
Referenced by Creature::add_effect(), Character::add_msg_player_or_say(), Creature::deal_melee_hit(), and Creature::process_turn().
effect_riding
const efftype_id effect_riding("riding") ("riding") static
Referenced by Creature::add_effect().
effect_sap
const efftype_id effect_sap("sap") ("sap") static
effect_sensor_stun
const efftype_id effect_sensor_stun("sensor_stun") ("sensor_stun") static
Referenced by Character::mod_speed_bonus().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by Creature::in_sleep_state().
effect_stumbled_into_invisible
const efftype_id effect_stumbled_into_invisible("stumbled_into_invisible") ("stumbled_into_invisible") static
Referenced by Creature::sees(), and Creature::stumble_invis().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by projectile::apply_effects_damage(), Creature::longpull(), and Character::mod_speed_bonus().
effect_telepathic_ignorance
const efftype_id effect_telepathic_ignorance("telepathic_ignorance") ("telepathic_ignorance") static
Referenced by Creature::sees().
effect_telepathic_ignorance_self
const efftype_id effect_telepathic_ignorance_self("telepathic_ignorance_self") ("telepathic_ignorance_self") static
Referenced by Creature::sees().
effect_tied
const efftype_id effect_tied("tied") ("tied") static
Referenced by projectile::apply_effects_damage().
effect_zapped
const efftype_id effect_zapped("zapped") ("zapped") static
Referenced by Creature::deal_damage_handle_type().
field_fd_last_known
const field_type_str_id field_fd_last_known("fd_last_known") ("fd_last_known") static
Referenced by Creature::attack_air(), Creature::sees(), and Creature::stumble_invis().
json_flag_BIONIC_LIMB
const json_character_flag json_flag_BIONIC_LIMB("BIONIC_LIMB") ("BIONIC_LIMB") static
Referenced by Creature::deal_damage().
json_flag_IGNORE_TEMP
const json_character_flag json_flag_IGNORE_TEMP("IGNORE_TEMP") ("IGNORE_TEMP") static
Referenced by Creature::set_all_parts_temp_conv(), and Creature::set_all_parts_temp_cur().
json_flag_LIMB_LOWER
const json_character_flag json_flag_LIMB_LOWER("LIMB_LOWER") ("LIMB_LOWER") static
Referenced by Creature::get_drenching_body_parts().
json_flag_LIMB_UPPER
const json_character_flag json_flag_LIMB_UPPER("LIMB_UPPER") ("LIMB_UPPER") static
Referenced by Creature::get_drenching_body_parts().
material_cotton
const material_id material_cotton("cotton") ("cotton") static
material_flesh
const material_id material_flesh("flesh") ("flesh") static
material_iflesh
const material_id material_iflesh("iflesh") ("iflesh") static
material_kevlar
const material_id material_kevlar("kevlar") ("kevlar") static
material_paper
const material_id material_paper("paper") ("paper") static
material_powder
const material_id material_powder("powder") ("powder") static
material_steel
const material_id material_steel("steel") ("steel") static
material_stone
const material_id material_stone("stone") ("stone") static
material_veggy
const material_id material_veggy("veggy") ("veggy") static
Referenced by projectile::apply_effects_damage().
material_wood
const material_id material_wood("wood") ("wood") static
material_wool
const material_id material_wool("wool") ("wool") static
species_ROBOT
const species_id species_ROBOT("ROBOT") ("ROBOT") static
Referenced by Character::mod_speed_bonus().
trait_DEBUG_CLOAK
const trait_id trait_DEBUG_CLOAK("DEBUG_CLOAK") ("DEBUG_CLOAK") static
Referenced by Creature::stumble_invis().
trait_PYROMANIA
const trait_id trait_PYROMANIA("PYROMANIA") ("PYROMANIA") static
Referenced by projectile::apply_effects_damage(), and Creature::deal_damage_handle_type().