Cataclysm DDA: src/creature_tracker.h File Reference
creature_tracker.h File Reference
#include <cstddef>
#include <list>
#include <memory>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "coordinates.h"
#include "creature.h"
#include "type_id.h"
Classes
class creature_tracker
Macros
#define CATA_SRC_CREATURE_TRACKER_H
Functions
creature_tracker & get_creature_tracker ()
Macro Definition Documentation
CATA_SRC_CREATURE_TRACKER_H
#define CATA_SRC_CREATURE_TRACKER_H
Definition at line 3 of file creature_tracker.h.
Function Documentation
get_creature_tracker()
creature_tracker& get_creature_tracker ()
Definition at line 13827 of file game.cpp.
 {
     return *g->critter_tracker;
 }
Referenced by target_ui::action_aim_and_shoot(), computer_session::action_terminate(), add_effect_to_target(), Character::adjacent_tile(), npc_attack_melee::all_evaluations(), npc_attack_gun::all_evaluations(), npc_attack_throw::all_evaluations(), npc::alt_attack(), jmapgen_setmap::apply(), monster::attack_at(), monster::attack_target(), spell_effect::banishment(), monster::bash_at(), mattack::breathe(), calculate_aim_cap(), mon_spellcasting_actor::call(), melee_actor::call(), iuse::camera(), computer_session::can_activate(), vehicle::can_close(), can_examine_at(), iuse::can_goo(), shearing_activity_actor::canceled(), iuse::capture_monster_act(), debug_menu::character_edit_menu(), character_push_effects(), spell_effect::charm_monster(), vehicle::autodrive_controller::check_drivable(), vehicle::check_heli_ascend(), vehicle::check_heli_descend(), clear_shot_reach(), doors::close_door(), map::collapse_at(), veh_interact::complete_vehicle(), item::contain_monster(), map::crush(), damage_targets(), spell_effect::dash(), monster::die(), spell_effect::directed_push(), map::displace_vehicle(), explosion_handler::do_blast(), milk_activity_actor::do_turn(), disable_activity_actor::do_turn(), stash_activity_actor::do_turn(), glide_activity_actor::do_turn(), editmap_hilight::draw(), anonymous_namespace{animation.cpp}::draw_line_curses(), editmap::draw_main_ui_overlay(), draw_throw_aim(), map::drop_furniture(), map::drop_items(), Character::echo_pulse(), editmap::edit(), eff_fun_teleglow(), spell_effect::effect_on_condition(), effects_description_for_creature(), iuse::emf_passive_on(), explosion_handler::emp_blast(), npc_attack_melee::evaluate(), npc_attack_gun::evaluate(), npc_attack_throw::evaluate(), npc_attack_spell::evaluate_tripoint(), npc_attack_gun::evaluate_tripoint(), npc_attack_throw::evaluate_tripoint(), iuse::extinguisher(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), climbing_aid::fall_scan::fall_scan(), field_processor_fd_electricity(), field_processor_fd_last_known(), field_processor_fd_push_items(), activity_handlers::fill_liquid_do_turn(), milk_activity_actor::finish(), shearing_activity_actor::finish(), chop_tree_activity_actor::finish(), disable_activity_actor::finish(), mattack::formblob(), fungal_effects::fungalize(), iuse::fungicide(), map::furn_set(), iuse::geiger(), map::get_creatures_in_radius(), vehicle::get_monster(), get_patient(), vehicle::get_riders(), iuse::granade_act(), monster::group_bash_skill(), mattack::growplants(), spell_effect::guilt(), npc::handle_sound(), Character::hardcoded_effects(), has_obstruction(), has_vine_parent(), spell::heal(), spell::ignore_by_species_id(), Character::impact(), npc::is_active(), spell::is_valid_target(), Character::knock_back_to(), monster::knock_back_to(), iexamine::ledge(), trapfunc::ledge(), target_ui::list_friendlies_in_lof(), Creature::longpull(), talk_function::loot_building(), iuse::mace(), spell_effect::mod_moves(), spell_effect::morale(), monster::move(), avatar_action::move(), veh_interact::move_cursor(), monster::move_effects(), monster::move_to(), npc::move_to(), mtrap_set(), spell_effect::mutate(), monster::nursebot_operate(), npc::on_load(), mattack::parrot_at_danger(), vehicle::part_collision(), iuse::petfood(), photo_def_for_camera_point(), monster::plan(), vehicle::precollision_check(), monster::process_effects(), monster::process_turn(), projectile_attack(), monster::push_to(), spell::random_valid_target(), Character::reach_attack(), spell_effect::recover_energy(), npc::regen_ai_cache(), spell_effect::remove_effect(), mattack::resurrect(), map::rotten_item_spawn(), route_best_workbench(), iexamine::rubble(), explosion_handler::scrambler_blast(), mattack::searchlight(), seen_critter(), lockpick_activity_actor::select_location(), target_ui::set_cursor_pos(), map::set_transparency_cache_dirty(), explosion_handler::shrapnel(), mattack::shriek_stun(), iexamine::shrub_wildveggies(), spell_effect::slime_split_on_death(), map::spawn_monsters_submap(), map::spawn_monsters_submap_group(), spawn_spores(), spell_move(), Character::stagger(), shearing_activity_actor::start(), disable_activity_actor::start(), monster::stumble(), swap_pos(), Target_attributes::Target_attributes(), spell::target_by_monster_id(), spell::target_by_species_id(), spell_effect::targeted_polymorph(), iuse::tazer(), teleport::teleport_to_point(), map::ter_set(), Character::throw_item(), teleporter_list::translocate(), mattack::triffid_heartbeat(), target_ui::try_reacquire_target(), Character::try_remove_grab(), editmap::uber_draw_ter(), map::unboard_vehicle(), editmap::update_view_with_help(), spell_effect::upgrade(), place_npc_iuse::use(), deploy_tent_actor::use(), npc_attack_melee::use(), vehicle::use_harness(), Character::valid_aoe_technique(), mattack::vine(), spell_effect::vomit(), suffer::while_grabbed(), npc::worker_downtime(), and mattack::zombie_fuse().