Cataclysm DDA: src/cube_direction.h File Reference
cube_direction.h File Reference
#include <functional>
#include "enum_traits.h"
Classes
struct enum_traits< cube_direction >
struct std::hash< cube_direction >
Namespaces
om_direction
Direction on the overmap.
Macros
#define CATA_SRC_CUBE_DIRECTION_H
Enumerations
enum class cube_direction : int {
north , east , south , west ,
above , below , last
}
Functions
cube_direction operator+ (cube_direction, om_direction::type)
cube_direction operator+ (cube_direction, int i)
cube_direction operator- (cube_direction, om_direction::type)
cube_direction operator- (cube_direction, int i)
tripoint displace (cube_direction d)
Macro Definition Documentation
CATA_SRC_CUBE_DIRECTION_H
#define CATA_SRC_CUBE_DIRECTION_H
Definition at line 3 of file cube_direction.h.
Enumeration Type Documentation
cube_direction
enum cube_direction : int strong
Enumerator
north
east
south
west
above
below
last
Definition at line 19 of file cube_direction.h.
                           : int {
     north,
     east,
     south,
     west,
     above,
     below,
     last
 };
Function Documentation
displace()
tripoint displace (cube_direction d)
Definition at line 1161 of file overmap.cpp.
 {
     switch( d ) {
         case cube_direction::north:
             return tripoint_north;
         case cube_direction::east:
             return tripoint_east;
         case cube_direction::south:
             return tripoint_south;
         case cube_direction::west:
             return tripoint_west;
         case cube_direction::above:
             return tripoint_above;
         case cube_direction::below:
             return tripoint_below;
         case cube_direction::last:
             break;
     }
     cata_fatal( "Invalid cube_direction" );
 }
References above, below, cata_fatal, east, last, north, south, tripoint_above, tripoint_below, tripoint_east, tripoint_north, tripoint_south, tripoint_west, and west.
Referenced by mutable_overmap_phase_remainder::can_place(), mapgendata::mapgendata(), mutable_overmap_special_data::place(), and game::vertical_move().
operator+() [1/2]
cube_direction operator+ (cube_direction d, int i)
Definition at line 1122 of file overmap.cpp.
 {
     switch( d ) {
         case cube_direction::north:
         case cube_direction::east:
         case cube_direction::south:
         case cube_direction::west:
             return static_cast<cube_direction>( ( static_cast<int>( d ) + i ) % 4 );
         case cube_direction::above:
         case cube_direction::below:
             return d;
         case cube_direction::last:
             break;
     }
     constexpr_fatal( cube_direction::last, "Invalid cube_direction" );
 }
References above, below, constexpr_fatal, east, last, north, south, and west.
operator+() [2/2]
cube_direction operator+ (cube_direction l, om_direction::type r)
Definition at line 1117 of file overmap.cpp.
 {
     return l + static_cast<int>( r );
 }
operator-() [1/2]
cube_direction operator- (cube_direction d, int i)
Definition at line 1144 of file overmap.cpp.
 {
     switch( d ) {
         case cube_direction::north:
         case cube_direction::east:
         case cube_direction::south:
         case cube_direction::west:
             return static_cast<cube_direction>( ( static_cast<int>( d ) - i + 4 ) % 4 );
         case cube_direction::above:
         case cube_direction::below:
             return d;
         case cube_direction::last:
             break;
     }
     constexpr_fatal( cube_direction::last, "Invalid cube_direction" );
 }
References above, below, constexpr_fatal, east, last, north, south, and west.
operator-() [2/2]
cube_direction operator- (cube_direction l, om_direction::type r)
Definition at line 1139 of file overmap.cpp.
 {
     return l - static_cast<int>( r );
 }