Cataclysm DDA: src/cuboid_rectangle.h File Reference
cuboid_rectangle.h File Reference
#include "cata_utility.h"
#include "point.h"
#include "point_traits.h"
Classes
struct rectangle< Point, >
struct half_open_rectangle< Point, >
struct inclusive_rectangle< Point, >
struct cuboid< Tripoint, >
struct half_open_cuboid< Tripoint, >
struct inclusive_cuboid< Tripoint, >
Macros
#define CATA_SRC_CUBOID_RECTANGLE_H
Functions
template<typename Point >
Point clamp (const Point &p, const half_open_rectangle< Point > &r)
template<typename Point >
Point clamp (const Point &p, const inclusive_rectangle< Point > &r)
template<typename Tripoint >
Tripoint clamp (const Tripoint &p, const half_open_cuboid< Tripoint > &c)
template<typename Tripoint >
Tripoint clamp (const Tripoint &p, const inclusive_cuboid< Tripoint > &c)
template<typename Index , typename Point >
int run_for_point_in (const std::map< Index, half_open_rectangle< Point >> &m, const Point &p, const std::function< void(const std::pair< Index, half_open_rectangle< Point >> &)> &func, bool first_only=true)
template<typename Index , typename Point >
int run_for_point_in (const std::map< Index, inclusive_rectangle< Point >> &m, const Point &p, const std::function< void(const std::pair< Index, inclusive_rectangle< Point >> &)> &func, bool first_only=true)
constexpr rectangle< point > rectangle_zero (point_zero, point_zero)
constexpr cuboid< tripoint > cuboid_zero (tripoint_zero, tripoint_zero)
Macro Definition Documentation
CATA_SRC_CUBOID_RECTANGLE_H
#define CATA_SRC_CUBOID_RECTANGLE_H
Definition at line 3 of file cuboid_rectangle.h.
Function Documentation
clamp() [1/4]
template<typename Point > Point clamp (const Point & p, const half_open_rectangle< Point > & r)
Definition at line 125 of file cuboid_rectangle.h.
 {
     using Traits = point_traits<Point>;
     return Point( clamp( Traits::x( p ), Traits::x( r.p_min ), Traits::x( r.p_max ) - 1 ),
                   clamp( Traits::y( p ), Traits::y( r.p_min ), Traits::y( r.p_max ) - 1 ) );
 }
References half_open_rectangle< Point, >::p_max, and half_open_rectangle< Point, >::p_min.
Referenced by clamp().
clamp() [2/4]
template<typename Point > Point clamp (const Point & p, const inclusive_rectangle< Point > & r)
Definition at line 133 of file cuboid_rectangle.h.
 {
     using Traits = point_traits<Point>;
     return Point( clamp( Traits::x( p ), Traits::x( r.p_min ), Traits::x( r.p_max ) ),
                   clamp( Traits::y( p ), Traits::y( r.p_min ), Traits::y( r.p_max ) ) );
 }
References clamp(), inclusive_rectangle< Point, >::p_max, and inclusive_rectangle< Point, >::p_min.
clamp() [3/4]
template<typename Tripoint > Tripoint clamp (const Tripoint & p, const half_open_cuboid< Tripoint > & c)
Definition at line 141 of file cuboid_rectangle.h.
 {
     using Traits = point_traits<Tripoint>;
     return Tripoint( clamp( Traits::x( p ), Traits::x( c.p_min ), Traits::x( c.p_max ) - 1 ),
                      clamp( Traits::y( p ), Traits::y( c.p_min ), Traits::y( c.p_max ) - 1 ),
                      clamp( Traits::z( p ), Traits::z( c.p_min ), Traits::z( c.p_max ) - 1 ) );
 }
References c, and clamp().
clamp() [4/4]
template<typename Tripoint > Tripoint clamp (const Tripoint & p, const inclusive_cuboid< Tripoint > & c)
Definition at line 150 of file cuboid_rectangle.h.
 {
     using Traits = point_traits<Tripoint>;
     return Tripoint( clamp( Traits::x( p ), Traits::x( c.p_min ), Traits::x( c.p_max ) ),
                      clamp( Traits::y( p ), Traits::y( c.p_min ), Traits::y( c.p_max ) ),
                      clamp( Traits::z( p ), Traits::z( c.p_min ), Traits::z( c.p_max ) ) );
 }
References c, and clamp().
cuboid_zero()
constexpr cuboid<tripoint> cuboid_zero (tripoint_zero , tripoint_zero) inline constexpr
rectangle_zero()
constexpr rectangle<point> rectangle_zero (point_zero , point_zero) inline constexpr
run_for_point_in() [1/2]
template<typename Index , typename Point > int run_for_point_in (const std::map< Index, half_open_rectangle< Point >> & m, const Point & p, const std::function< void(const std::pair< Index, half_open_rectangle< Point >> &)> & func, bool first_only = true)
Definition at line 159 of file cuboid_rectangle.h.
 {
     int cnt = 0;
     for( const std::pair<const Index, half_open_rectangle<Point>> &mp : m ) {
         if( mp.second.contains( p ) ) {
             func( mp );
             cnt++;
             if( first_only ) {
                 break;
             }
         }
     }
     return cnt;
 }
run_for_point_in() [2/2]
template<typename Index , typename Point > int run_for_point_in (const std::map< Index, inclusive_rectangle< Point >> & m, const Point & p, const std::function< void(const std::pair< Index, inclusive_rectangle< Point >> &)> & func, bool first_only = true)
Definition at line 177 of file cuboid_rectangle.h.
 {
     int cnt = 0;
     for( const std::pair<const Index, inclusive_rectangle<Point>> &mp : m ) {
         if( mp.second.contains( p ) ) {
             func( mp );
             cnt++;
             if( first_only ) {
                 break;
             }
         }
     }
     return cnt;
 }