Cataclysm DDA: src/damage.cpp File Reference
damage.cpp File Reference
#include "damage.h"
#include <algorithm>
#include <map>
#include <memory>
#include <numeric>
#include <string>
#include <utility>
#include "bodypart.h"
#include "cata_utility.h"
#include "creature.h"
#include "debug.h"
#include "dialogue.h"
#include "effect_on_condition.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "generic_factory.h"
#include "init.h"
#include "item.h"
#include "json.h"
#include "json_error.h"
#include "make_static.h"
#include "monster.h"
#include "mtype.h"
#include "subbodypart.h"
#include "talker.h"
#include "units.h"
Namespaces
anonymous_namespace{damage.cpp}
Functions
static damage_info_order::info_disp read_info_disp (const std::string &s)
static void prepare_sorted_lists (std::vector< damage_info_order > &list, damage_info_order::info_type sb)
static damage_unit load_damage_unit (const JsonObject &curr)
static damage_unit load_damage_unit_inherit (const JsonObject &curr, const damage_instance &parent)
static damage_instance blank_damage_instance ()
damage_instance load_damage_instance (const JsonObject &jo)
damage_instance load_damage_instance (const JsonArray &jarr)
damage_instance load_damage_instance_inherit (const JsonObject &jo, const damage_instance &parent)
damage_instance load_damage_instance_inherit (const JsonArray &jarr, const damage_instance &parent)
std::unordered_map< damage_type_id, float > load_damage_map (const JsonObject &jo, const std::set< std::string > &ignored_keys)
void finalize_damage_map (std::unordered_map< damage_type_id, float > &damage_map, bool force_derive, float default_value)
resistances extend_resistances_instance (resistances ret, const JsonObject &jo)
resistances load_resistances_instance (const JsonObject &jo, const std::set< std::string > &ignored_keys)
Variables
static std::map< damage_info_order::info_type, std::vector< damage_info_order > > sorted_order_lists
generic_factory< damage_type > anonymous_namespace{damage.cpp}::damage_type_factory ("damage type")
generic_factory< damage_info_order > anonymous_namespace{damage.cpp}::damage_info_order_factory ("damage info order")
Function Documentation
blank_damage_instance()
static damage_instance blank_damage_instance () static
Definition at line 723 of file damage.cpp.
 {
     damage_instance ret;
     for( const damage_type &dam : damage_type::get_all() ) {
         ret.add_damage( dam.id, 0.0f );
     }
     return ret;
 }
References damage_type::get_all(), and cata::hash64_detail::ret.
Referenced by load_damage_instance().
extend_resistances_instance()
resistances extend_resistances_instance (resistances ret, const JsonObject & jo)
Definition at line 823 of file damage.cpp.
 {
     resistances ext;
     ext.resist_vals = load_damage_map( jo );
     for( const std::pair<const damage_type_id, float> &damage_pair : ext.resist_vals ) {
         ret.resist_vals[damage_pair.first] += damage_pair.second;
     }
     return ret;
 }
References load_damage_map(), resistances::resist_vals, and cata::hash64_detail::ret.
Referenced by mtype::load().
finalize_damage_map()
void finalize_damage_map (std::unordered_map< damage_type_id, float > & damage_map, bool force_derive, float default_value)
Definition at line 781 of file damage.cpp.
 {
     const std::vector<damage_type> &dams = damage_type::get_all();
     if( dams.empty() ) {
         debugmsg( "called before damage_types have been loaded." );
         return;
     }
     auto get_and_erase = [&damage_map]( const damage_type_id & did, float def_val ) {
         auto iter = damage_map.find( did );
         if( iter == damage_map.end() ) {
             return def_val;
         }
         float val = iter->second;
         damage_map.erase( iter );
         return val;
     };
     const float all = get_and_erase( STATIC( damage_type_id( "all" ) ), default_value );
     const float physical = get_and_erase( STATIC( damage_type_id( "physical" ) ), all );
     const float non_phys = get_and_erase( STATIC( damage_type_id( "non_physical" ) ), all );
     std::vector<damage_type_id> to_derive;
     for( const damage_type &dam : dams ) {
         float val = dam.physical ? physical : non_phys;
         if( damage_map.count( dam.id ) > 0 ) {
             val = damage_map.at( dam.id );
         } else if( force_derive && !dam.derived_from.first.is_null() ) {
             to_derive.emplace_back( dam.id );
             continue;
         }
         damage_map[dam.id] = val;
     }
     for( auto &td : to_derive ) {
         auto iter = damage_map.find( td->derived_from.first );
         damage_map[td] = iter == damage_map.end() ? ( td->physical ? physical : non_phys ) :
                          iter->second * td->derived_from.second;
     }
 }
References om_direction::all, debugmsg, damage_type::get_all(), and STATIC.
Referenced by bionic_data::finalize(), body_part_type::finalize(), mutation_branch::finalize(), vpart_info::finalize(), weakpoints::finalize(), material_type::finalize_all(), MonsterGenerator::finalize_mtypes(), and Item_factory::finalize_pre().
load_damage_instance() [1/2]
damage_instance load_damage_instance (const JsonArray & jarr)
Definition at line 739 of file damage.cpp.
 {
     return load_damage_instance_inherit( jarr, blank_damage_instance() );
 }
References blank_damage_instance(), and load_damage_instance_inherit().
load_damage_instance() [2/2]
damage_instance load_damage_instance (const JsonObject & jo)
Definition at line 734 of file damage.cpp.
 {
     return load_damage_instance_inherit( jo, blank_damage_instance() );
 }
References blank_damage_instance(), and load_damage_instance_inherit().
Referenced by assign(), damage_instance::deserialize(), mtype::load(), body_part_type::load(), Item_factory::load_basic_info(), melee_actor::load_internal(), and load_mutation_attack().
load_damage_instance_inherit() [1/2]
damage_instance load_damage_instance_inherit (const JsonArray & jarr, const damage_instance & parent)
Definition at line 758 of file damage.cpp.
 {
     damage_instance di;
     for( const JsonObject curr : jarr ) {
         di.damage_units.push_back( load_damage_unit_inherit( curr, parent ) );
     }
     return di;
 }
References damage_instance::damage_units, and load_damage_unit_inherit().
load_damage_instance_inherit() [2/2]
damage_instance load_damage_instance_inherit (const JsonObject & jo, const damage_instance & parent)
Definition at line 744 of file damage.cpp.
 {
     damage_instance di;
     if( jo.has_array( "values" ) ) {
         for( const JsonObject curr : jo.get_array( "values" ) ) {
             di.damage_units.push_back( load_damage_unit_inherit( curr, parent ) );
         }
     } else if( jo.has_string( "damage_type" ) ) {
         di.damage_units.push_back( load_damage_unit_inherit( jo, parent ) );
     }
     return di;
 }
References damage_instance::damage_units, JsonObject::get_array(), JsonObject::has_array(), JsonObject::has_string(), and load_damage_unit_inherit().
Referenced by assign(), and load_damage_instance().
load_damage_map()
std::unordered_map<damage_type_id, float> load_damage_map (const JsonObject & jo, const std::set< std::string > & ignored_keys)
Definition at line 768 of file damage.cpp.
 {
     std::unordered_map<damage_type_id, float> ret;
     for( const JsonMember &jmemb : jo ) {
         if( !ignored_keys.empty() && ignored_keys.count( jmemb.name() ) > 0 ) {
             continue;
         }
         ret[damage_type_id( jmemb.name() )] = jmemb.get_float();
     }
     return ret;
 }
References cata::hash64_detail::ret.
Referenced by extend_resistances_instance(), weakpoint::load(), vpart_info::load(), Item_factory::load_basic_info(), and load_resistances_instance().
load_damage_unit()
static damage_unit load_damage_unit (const JsonObject & curr) static
Definition at line 662 of file damage.cpp.
 {
     damage_type_id dt( curr.get_string( "damage_type" ) );
     float amount = curr.get_float( "amount", 0 );
     float arpen = curr.get_float( "armor_penetration", 0 );
     float armor_mul = curr.get_float( "armor_multiplier", 1.0f );
     float damage_mul = curr.get_float( "damage_multiplier", 1.0f );
     float unc_armor_mul = curr.get_float( "constant_armor_multiplier", 1.0f );
     float unc_damage_mul = curr.get_float( "constant_damage_multiplier", 1.0f );
     damage_unit du( dt, amount, arpen, armor_mul, damage_mul, unc_armor_mul,
                     unc_damage_mul );
     optional( curr, false, "barrels", du.barrels );
     return du;
 }
References damage_unit::barrels, JsonObject::get_float(), JsonObject::get_string(), and optional().
Referenced by load_damage_unit_inherit().
load_damage_unit_inherit()
static damage_unit load_damage_unit_inherit (const JsonObject & curr, const damage_instance & parent) static
Definition at line 682 of file damage.cpp.
 {
     damage_unit ret = load_damage_unit( curr );
     const std::vector<damage_unit> &parent_damage = parent.damage_units;
     auto du_iter = std::find_if( parent_damage.begin(),
     parent_damage.end(), [&ret]( const damage_unit & dmg ) {
         return dmg.type == ret.type;
     } );
     if( du_iter == parent_damage.end() ) {
         return ret;
     }
     const damage_unit &parent_du = *du_iter;
     if( !curr.has_float( "amount" ) ) {
         ret.amount = parent_du.amount;
     }
     if( !curr.has_float( "armor_penetration" ) ) {
         ret.res_pen = parent_du.res_pen;
     }
     if( !curr.has_float( "armor_multiplier" ) ) {
         ret.res_mult = parent_du.res_mult;
     }
     if( !curr.has_float( "damage_multiplier" ) ) {
         ret.damage_multiplier = parent_du.damage_multiplier;
     }
     if( !curr.has_float( "constant_armor_multiplier" ) ) {
         ret.unconditional_res_mult = parent_du.unconditional_res_mult;
     }
     if( !curr.has_float( "constant_damage_multiplier" ) ) {
         ret.unconditional_damage_mult = parent_du.unconditional_damage_mult;
     }
     if( !curr.has_array( "barrels" ) ) {
         ret.barrels = parent_du.barrels;
     }
     return ret;
 }
References damage_unit::amount, damage_unit::barrels, damage_unit::damage_multiplier, damage_instance::damage_units, JsonObject::has_array(), JsonObject::has_float(), load_damage_unit(), damage_unit::res_mult, damage_unit::res_pen, cata::hash64_detail::ret, damage_unit::unconditional_damage_mult, and damage_unit::unconditional_res_mult.
Referenced by load_damage_instance_inherit().
load_resistances_instance()
resistances load_resistances_instance (const JsonObject & jo, const std::set< std::string > & ignored_keys)
Definition at line 833 of file damage.cpp.
 {
     resistances ret;
     ret.resist_vals = load_damage_map( jo, ignored_keys );
     return ret;
 }
References load_damage_map(), and cata::hash64_detail::ret.
Referenced by mtype::load(), mutation_branch::load(), body_part_type::load(), material_type::load(), and bionic_data::load().
prepare_sorted_lists()
static void prepare_sorted_lists (std::vector< damage_info_order > & list, damage_info_order::info_type sb) static
Definition at line 209 of file damage.cpp.
 {
     for( auto iter = list.begin(); iter != list.end(); ) {
         bool erase = false;
         switch( sb ) {
             case damage_info_order::info_type::BIO:
                 if( !iter->bionic_info.show_type ) {
                     erase = true;
                 }
                 break;
             case damage_info_order::info_type::PROT:
                 if( !iter->protection_info.show_type ) {
                     erase = true;
                 }
                 break;
             case damage_info_order::info_type::PET:
                 if( !iter->pet_prot_info.show_type ) {
                     erase = true;
                 }
                 break;
             case damage_info_order::info_type::MELEE:
                 if( !iter->melee_combat_info.show_type ) {
                     erase = true;
                 }
                 break;
             case damage_info_order::info_type::ABLATE:
                 if( !iter->ablative_info.show_type ) {
                     erase = true;
                 }
                 break;
             case damage_info_order::info_type::NONE:
             default:
                 break;
         }
         if( erase ) {
             iter = list.erase( iter );
         } else {
             iter++;
         }
     }
     if( sb == damage_info_order::info_type::NONE ) {
         return;
     }
     std::sort( list.begin(), list.end(),
     [sb]( const damage_info_order & a, const damage_info_order & b ) {
         switch( sb ) {
             case damage_info_order::info_type::BIO:
                 return a.bionic_info.order < b.bionic_info.order;
             case damage_info_order::info_type::PROT:
                 return a.protection_info.order < b.protection_info.order;
             case damage_info_order::info_type::PET:
                 return a.pet_prot_info.order < b.pet_prot_info.order;
             case damage_info_order::info_type::MELEE:
                 return a.melee_combat_info.order < b.melee_combat_info.order;
             case damage_info_order::info_type::ABLATE:
                 return a.ablative_info.order < b.ablative_info.order;
             case damage_info_order::info_type::NONE:
             default:
                 return false;
         }
     } );
 }
References a, damage_info_order::ABLATE, b, damage_info_order::BIO, catacurses::erase(), damage_info_order::MELEE, damage_info_order::NONE, damage_info_order::PET, and damage_info_order::PROT.
Referenced by damage_info_order::finalize_all().
read_info_disp()
static damage_info_order::info_disp read_info_disp (const std::string & s) static
Definition at line 104 of file damage.cpp.
 {
     if( s == "detailed" ) {
         return damage_info_order::info_disp::DETAILED;
     } else if( s == "basic" ) {
         return damage_info_order::info_disp::BASIC;
     } else {
         return damage_info_order::info_disp::NONE;
     }
 }
References damage_info_order::BASIC, damage_info_order::DETAILED, and damage_info_order::NONE.
Referenced by damage_info_order::load().
Variable Documentation
sorted_order_lists
std::map<damage_info_order::info_type, std::vector<damage_info_order> > sorted_order_lists static
Definition at line 30 of file damage.cpp.
Referenced by damage_info_order::finalize_all(), damage_info_order::get_all(), and damage_info_order::reset().