Cataclysm DDA: src/debug_menu.cpp File Reference
debug_menu.cpp File Reference
#include "debug_menu.h"
#include <algorithm>
#include <chrono>
#include <csignal>
#include <cstdint>
#include <exception>
#include <filesystem>
#include <functional>
#include <iostream>
#include <iterator>
#include <list>
#include <locale>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "achievement.h"
#include "action.h"
#include "activity_tracker.h"
#include "avatar.h"
#include "bionics.h"
#include "bodypart.h"
#include "calendar.h"
#include "calendar_ui.h"
#include "cata_assert.h"
#include "cata_path.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "character_attire.h"
#include "character_id.h"
#include "character_martial_arts.h"
#include "city.h"
#include "clzones.h"
#include "color.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "creature.h"
#include "creature_tracker.h"
#include "cursesdef.h"
#include "debug.h"
#include "dialogue.h"
#include "dialogue_chatbin.h"
#include "dialogue_helpers.h"
#include "display.h"
#include "effect.h"
#include "effect_on_condition.h"
#include "enum_conversions.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "faction.h"
#include "filesystem.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "global_vars.h"
#include "input.h"
#include "input_context.h"
#include "inventory.h"
#include "item.h"
#include "item_group.h"
#include "item_location.h"
#include "itype.h"
#include "json.h"
#include "localized_comparator.h"
#include "magic.h"
#include "map.h"
#include "map_extras.h"
#include "map_iterator.h"
#include "mapgen.h"
#include "mapgendata.h"
#include "martialarts.h"
#include "memory_fast.h"
#include "messages.h"
#include "mission.h"
#include "mongroup.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "mutation.h"
#include "npc.h"
#include "npc_class.h"
#include "omdata.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "overmap_ui.h"
#include "overmapbuffer.h"
#include "path_info.h"
#include "pimpl.h"
#include "point.h"
#include "popup.h"
#include "recipe_dictionary.h"
#include "relic.h"
#include "requirements.h"
#include "ret_val.h"
#include "skill.h"
#include "sounds.h"
#include "stomach.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "talker.h"
#include "tgz_archiver.h"
#include "timed_event.h"
#include "trait_group.h"
#include "translation.h"
#include "translations.h"
#include "try_parse_integer.h"
#include "type_id.h"
#include "ui.h"
#include "uistate.h"
#include "ui_manager.h"
#include "units.h"
#include "units_utility.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vitamin.h"
#include "vpart_position.h"
#include "weather.h"
#include "weather_gen.h"
#include "weather_type.h"
#include "weighted_list.h"
#include "worldfactory.h"
Classes
struct anonymous_namespace{debug_menu.cpp}::fake_tripoint
struct anonymous_namespace{debug_menu.cpp}::OM_point
class debug_menu::mission_debug
Namespaces
io
anonymous_namespace{debug_menu.cpp}
debug_menu
Macros
#define dbg(x) DebugLog((x),D_GAME) << __FILE__ << ":" << __LINE__ << ": "
Typedefs
using anonymous_namespace{debug_menu.cpp}::rdi_t = fs::recursive_directory_iterator
using anonymous_namespace{debug_menu.cpp}::f_validate_t = std::function< bool(fs::path const &dep, rdi_t &iter)>
Functions
template<>
std::string io::enum_to_string< debug_menu::debug_menu_index > (debug_menu::debug_menu_index v)
std::istream & anonymous_namespace{debug_menu.cpp}::operator>> (std::istream &is, fake_tripoint &pos)
std::istream & anonymous_namespace{debug_menu.cpp}::operator>> (std::istream &is, OM_point &pos)
template<typename T >
T anonymous_namespace{debug_menu.cpp}::_from_fs_string (std::string const &s)
tripoint anonymous_namespace{debug_menu.cpp}::_from_map_string (std::string const &s)
tripoint anonymous_namespace{debug_menu.cpp}::_from_OM_string (std::string const &s)
bool anonymous_namespace{debug_menu.cpp}::_add_dir (tgz_archiver &tgz, fs::path const &root, f_validate_t const &validate={})
bool anonymous_namespace{debug_menu.cpp}::_trim_mapbuffer (fs::path const &dep, rdi_t &iter, tripoint_range< tripoint > const &segs, tripoint_range< tripoint > const &regs)
bool anonymous_namespace{debug_menu.cpp}::_trim_overmapbuffer (fs::path const &dep, tripoint_range< tripoint > const &oms)
bool anonymous_namespace{debug_menu.cpp}::_discard_temporary (fs::path const &dep)
void anonymous_namespace{debug_menu.cpp}::write_min_archive ()
static std::string debug_menu::first_word (const std::string &str)
static bool debug_menu::is_debug_character ()
static int debug_menu::player_uilist ()
static int debug_menu::info_uilist (bool display_all_entries=true)
static int debug_menu::game_uilist ()
static int debug_menu::vehicle_uilist ()
static int debug_menu::teleport_uilist ()
static int debug_menu::spawning_uilist ()
static int debug_menu::map_uilist ()
static int debug_menu::quick_setup_uilist ()
static int debug_menu::faction_uilist ()
static std::optional< debug_menu_index > debug_menu::debug_menu_uilist (bool display_all_entries=true)
Create the debug menu UI list.
static void debug_menu::spell_description (std::tuple< spell_type, int, std::string > &spl_data, int width, Character &chrc)
static void debug_menu::change_spells (Character &character)
static void debug_menu::spawn_artifact ()
static void debug_menu::teleport_short ()
static void debug_menu::teleport_long ()
static void debug_menu::teleport_overmap (bool specific_coordinates=false)
static void debug_menu::teleport_city ()
static void debug_menu::spawn_nested_mapgen ()
static void debug_menu::control_npc_menu ()
static void debug_menu::character_edit_stats_menu (Character &you)
static void debug_menu::character_edit_needs_menu (Character &you)
static void debug_menu::character_edit_hp_menu (Character &you)
static void debug_menu::character_edit_opinion_menu (npc *np)
static void debug_menu::character_edit_personality_menu (npc *np)
static void debug_menu::character_edit_desc_menu (Character &you)
static faction * debug_menu::select_faction ()
static void debug_menu::character_edit_menu ()
static void debug_menu::faction_edit_opinion_menu (faction *fac)
static void debug_menu::faction_edit_larder_menu (faction *fac)
static void debug_menu::faction_edit_menu ()
static std::string debug_menu::mission_status_string (mission::mission_status status)
static void debug_menu::add_header (uilist &mmenu, const std::string &str)
static bool debug_menu::remove_from_vec (std::vector< mission * > &vec, mission *m)
static void debug_menu::draw_benchmark (const int max_difference)
static void debug_menu::debug_menu_game_state ()
static void debug_menu::debug_menu_spawn_vehicle ()
static void debug_menu::debug_menu_force_temperature ()
static npc * debug_menu::select_follower_to_export ()
static cata_path debug_menu::prepare_export_dir_and_find_unused_name (const std::string &character_name)
static void debug_menu::normalize_body ()
static void debug_menu::bleed_self ()
static void debug_menu::change_weather ()
static void debug_menu::damage_self ()
static void debug_menu::edit_global_vars ()
static void debug_menu::game_report ()
static void debug_menu::generate_effect_list ()
static void debug_menu::gen_sound ()
static void debug_menu::import_folower ()
static void debug_menu::kill_area ()
static void debug_menu::map_extra ()
static void debug_menu::print_npc_magic ()
static void debug_menu::show_sound ()
static void debug_menu::set_automove ()
static void debug_menu::spawn_npc ()
static void debug_menu::unlock_all ()
static void debug_menu::vehicle_battery_charge ()
static void debug_menu::vehicle_export ()
static void debug_menu::wind_direction ()
static void debug_menu::wind_speed ()
static void debug_menu::write_city_list ()
static void debug_menu::write_global_vars ()
void debug_menu::debug ()
Variables
static const achievement_id achievement_achievement_arcade_mode ("achievement_arcade_mode")
static const bodypart_str_id body_part_no_a_real_part ("no_a_real_part")
static const efftype_id effect_asthma ("asthma")
static const efftype_id effect_bleed ("bleed")
static const faction_id faction_no_faction ("no_faction")
static const faction_id faction_your_followers ("your_followers")
static const matype_id style_none ("style_none")
static const mtype_id mon_generator ("mon_generator")
static const trait_id trait_ASTHMA ("ASTHMA")
static const trait_id trait_DEBUG_BIONICS ("DEBUG_BIONICS")
static const trait_id trait_DEBUG_CLAIRVOYANCE ("DEBUG_CLAIRVOYANCE")
static const trait_id trait_DEBUG_CLOAK ("DEBUG_CLOAK")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
static const trait_id trait_DEBUG_LIGHT ("DEBUG_LIGHT")
static const trait_id trait_DEBUG_LS ("DEBUG_LS")
static const trait_id trait_DEBUG_MANA ("DEBUG_MANA")
static const trait_id trait_DEBUG_MIND_CONTROL ("DEBUG_MIND_CONTROL")
static const trait_id trait_DEBUG_NODMG ("DEBUG_NODMG")
static const trait_id trait_DEBUG_NOTEMP ("DEBUG_NOTEMP")
static const trait_id trait_DEBUG_SPEED ("DEBUG_SPEED")
static const trait_id trait_DEBUG_STAMINA ("DEBUG_STAMINA")
static const trait_id trait_NONE ("NONE")
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x),D_GAME) << __FILE__ << ":" << __LINE__ << ": "
Definition at line 168 of file debug_menu.cpp.
Variable Documentation
achievement_achievement_arcade_mode
const achievement_id achievement_achievement_arcade_mode("achievement_arcade_mode") ("achievement_arcade_mode") static
Referenced by debug_menu::unlock_all().
body_part_no_a_real_part
const bodypart_str_id body_part_no_a_real_part("no_a_real_part") ("no_a_real_part") static
Referenced by debug_menu::character_edit_hp_menu().
effect_asthma
const efftype_id effect_asthma("asthma") ("asthma") static
Referenced by debug_menu::character_edit_menu().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by debug_menu::bleed_self().
faction_no_faction
const faction_id faction_no_faction("no_faction") ("no_faction") static
Referenced by debug_menu::spawn_npc().
faction_your_followers
const faction_id faction_your_followers("your_followers") ("your_followers") static
Referenced by debug_menu::import_folower().
mon_generator
const mtype_id mon_generator("mon_generator") ("mon_generator") static
Referenced by debug_menu::debug().
style_none
const matype_id style_none("style_none") ("style_none") static
Referenced by debug_menu::debug().
trait_ASTHMA
const trait_id trait_ASTHMA("ASTHMA") ("ASTHMA") static
Referenced by debug_menu::character_edit_menu().
trait_DEBUG_BIONICS
const trait_id trait_DEBUG_BIONICS("DEBUG_BIONICS") ("DEBUG_BIONICS") static
Referenced by debug_menu::debug().
trait_DEBUG_CLAIRVOYANCE
const trait_id trait_DEBUG_CLAIRVOYANCE("DEBUG_CLAIRVOYANCE") ("DEBUG_CLAIRVOYANCE") static
Referenced by debug_menu::debug().
trait_DEBUG_CLOAK
const trait_id trait_DEBUG_CLOAK("DEBUG_CLOAK") ("DEBUG_CLOAK") static
Referenced by debug_menu::debug().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by debug_menu::debug().
trait_DEBUG_LIGHT
const trait_id trait_DEBUG_LIGHT("DEBUG_LIGHT") ("DEBUG_LIGHT") static
Referenced by debug_menu::debug().
trait_DEBUG_LS
const trait_id trait_DEBUG_LS("DEBUG_LS") ("DEBUG_LS") static
Referenced by debug_menu::debug().
trait_DEBUG_MANA
const trait_id trait_DEBUG_MANA("DEBUG_MANA") ("DEBUG_MANA") static
Referenced by debug_menu::debug().
trait_DEBUG_MIND_CONTROL
const trait_id trait_DEBUG_MIND_CONTROL("DEBUG_MIND_CONTROL") ("DEBUG_MIND_CONTROL") static
Referenced by debug_menu::debug().
trait_DEBUG_NODMG
const trait_id trait_DEBUG_NODMG("DEBUG_NODMG") ("DEBUG_NODMG") static
Referenced by debug_menu::debug().
trait_DEBUG_NOTEMP
const trait_id trait_DEBUG_NOTEMP("DEBUG_NOTEMP") ("DEBUG_NOTEMP") static
Referenced by debug_menu::debug().
trait_DEBUG_SPEED
const trait_id trait_DEBUG_SPEED("DEBUG_SPEED") ("DEBUG_SPEED") static
Referenced by debug_menu::debug().
trait_DEBUG_STAMINA
const trait_id trait_DEBUG_STAMINA("DEBUG_STAMINA") ("DEBUG_STAMINA") static
Referenced by debug_menu::debug().
trait_NONE
const trait_id trait_NONE("NONE") ("NONE") static
Referenced by debug_menu::spell_description().