Cataclysm DDA: src/debug.cpp File Reference
debug.cpp File Reference
#include "debug.h"
#include <cctype>
#include <sys/stat.h>
#include <clocale>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <iomanip>
#include <iterator>
#include <map>
#include <memory>
#include <new>
#include <optional>
#include <regex>
#include <set>
#include <sstream>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>
#include "cached_options.h"
#include "cata_assert.h"
#include "cata_scope_helpers.h"
#include "cata_utility.h"
#include "color.h"
#include "cursesdef.h"
#include "filesystem.h"
#include "get_version.h"
#include "input.h"
#include "mod_manager.h"
#include "options.h"
#include "output.h"
#include "path_info.h"
#include "point.h"
#include "translations.h"
#include "type_id.h"
#include "ui_manager.h"
#include "worldfactory.h"
#include <sys/time.h>
Classes
class capture_debugmsg
Class for capturing debugmsg, used by capture_debugmsg_during.
struct buffered_prompt_info
struct time_info
struct repetition_folder
class NullStream
struct DebugFile
Namespaces
debugmode
anonymous_namespace{debug.cpp}
Functions
std::string capture_debugmsg_during (const std::function< void()> &func)
Capturing debug messages during func execution, used to test debugmsg calls in the unit tests.
bool debug_has_error_been_observed ()
std::string debugmode::filter_name (debug_filter value)
static std::vector< buffered_prompt_info > & buffered_prompts ()
static void debug_error_prompt (const char *filename, const char *line, const char *funcname, const char *text, bool force)
void replay_buffered_debugmsg_prompts ()
Should be called after catacurses::stdscr is initialized.
static time_info get_time () noexcept
static void output_repetitions (std::ostream &out)
void realDebugmsg (const char *filename, const char *line, const char *funcname, const std::string &text)
void limitDebugLevel (int level_bitmask)
Set debug levels that should be logged.
void limitDebugClass (int class_bitmask)
Set the debug classes should be logged.
static DebugFile & debugFile ()
void setupDebug (DebugOutput output_mode)
Initializes the debugging system, called exactly once from main()
void deinitDebug ()
Opposite of setupDebug, shuts the debugging system down.
static std::ostream & operator<< (std::ostream &out, DebugLevel lev)
static std::ostream & operator<< (std::ostream &out, DebugClass cl)
std::ostream & DebugLog (DebugLevel lev, DebugClass cl)
bool isDebuggerActive ()
Variables
static int debugLevel = D_ERROR
static int debugClass = D_MAIN
static bool error_observed = false
Set to true when any error is logged.
static bool capturing = false
If true, debug messages will be captured, used to test debugmsg calls in the unit tests.
static std::string captured
сaptured debug messages.
bool debug_mode = false
Extended debugging mode, can be toggled during game.
std::unordered_set< debug_filter > debugmode::enabled_filters
std::set< std::string > anonymous_namespace{debug.cpp}::ignored_messages
static repetition_folder rep_folder
Function Documentation
buffered_prompts()
static std::vector<buffered_prompt_info>& buffered_prompts () static
Definition at line 288 of file debug.cpp.
 {
     static std::vector<buffered_prompt_info> buffered_prompts;
     return buffered_prompts;
 }
Referenced by realDebugmsg(), and replay_buffered_debugmsg_prompts().
capture_debugmsg_during()
std::string capture_debugmsg_during (const std::function< void()> & func)
Capturing debug messages during func execution, used to test debugmsg calls in the unit tests.
Returns
std::string debugmsg
Definition at line 181 of file debug.cpp.
 {
     capture_debugmsg capture;
     func();
     return capture.dmsg();
 }
References capture_debugmsg::dmsg().
debug_error_prompt()
static void debug_error_prompt (const char * filename, const char * line, const char * funcname, const char * text, bool force) static
Definition at line 294 of file debug.cpp.
 {
     cata_assert( catacurses::stdscr );
     cata_assert( filename != nullptr );
     cata_assert( line != nullptr );
     cata_assert( funcname != nullptr );
     cata_assert( text != nullptr );
     std::string msg_key( filename );
     msg_key += line;
     if( !force && ignored_messages.count( msg_key ) > 0 ) {
         return;
     }
     std::string formatted_report =
         string_format( // developer-facing error report. INTENTIONALLY UNTRANSLATED!
             " DEBUG    : %s\n\n"
             " FUNCTION : %s\n"
             " FILE     : %s\n"
             " LINE     : %s\n"
             " VERSION  : %s\n",
             text, funcname, filename, line, getVersionString()
         );
 #if defined(BACKTRACE)
     std::string backtrace_instructions =
         string_format(
             _( "See %s for a full stack backtrace" ),
             PATH_INFO::debug()
         );
 #endif
     // Create a special debug message UI that does various things to ensure
     // the graphics are correct when the debug message is displayed during a
     // redraw callback.
     ui_adaptor ui( ui_adaptor::debug_message_ui {} );
     const auto init_window = []( ui_adaptor & ui ) {
         ui.position_from_window( catacurses::stdscr );
     };
     init_window( ui );
     ui.on_screen_resize( init_window );
     const std::string message = string_format(
                                     "\n\n" // Looks nicer with some space
                                     " %s\n" // translated user string: error notification
                                     " -----------------------------------------------------------\n"
                                     "%s"
                                     " -----------------------------------------------------------\n"
 #if defined(BACKTRACE)
                                     " %s\n" // translated user string: where to find backtrace
 #endif
                                     " %s\n" // translated user string: space to continue
                                     " %s\n" // translated user string: ignore key
 #if defined(TILES)
                                     " %s\n" // translated user string: copy
 #endif // TILES
                                     , _( "An error has occurred!  Written below is the error report:" ),
                                     formatted_report,
 #if defined(BACKTRACE)
                                     backtrace_instructions,
 #endif
                                     _( "Press <color_white>space bar</color> to continue the game." ),
                                     _( "Press <color_white>I</color> (or <color_white>i</color>) to also ignore this particular message in the future." )
 #if defined(TILES)
                                     , _( "Press <color_white>C</color> (or <color_white>c</color>) to copy this message to the clipboard." )
 #endif // TILES
                                 );
     ui.on_redraw( [&]( const ui_adaptor & ) {
         catacurses::erase();
         fold_and_print( catacurses::stdscr, point_zero, getmaxx( catacurses::stdscr ), c_light_red,
                         "%s", message );
         wnoutrefresh( catacurses::stdscr );
     } );
 #if defined(__ANDROID__)
     input_context ctxt( "DEBUG_MSG", keyboard_mode::keycode );
     ctxt.register_manual_key( 'C' );
     ctxt.register_manual_key( 'I' );
     ctxt.register_manual_key( ' ' );
 #endif
     for( bool stop = false; !stop; ) {
         ui_manager::redraw();
         switch( inp_mngr.get_input_event().get_first_input() ) {
 #if defined(TILES)
             case 'c':
             case 'C':
                 SDL_SetClipboardText( formatted_report.c_str() );
                 break;
 #endif // TILES
             case 'i':
             case 'I':
                 ignored_messages.insert( msg_key );
             /* fallthrough */
             case ' ':
                 stop = true;
                 break;
         }
     }
 }
References _, c_light_red, cata_assert, PATH_INFO::debug(), catacurses::erase(), fold_and_print(), force, input_event::get_first_input(), input_manager::get_input_event(), catacurses::getmaxx(), getVersionString(), anonymous_namespace{debug.cpp}::ignored_messages, init_window(), inp_mngr, keycode, line(), mapgen_defer::message, point_zero, ui_manager::redraw(), catacurses::stdscr, string_format(), and catacurses::wnoutrefresh().
Referenced by realDebugmsg(), and replay_buffered_debugmsg_prompts().
debug_has_error_been_observed()
bool debug_has_error_been_observed ()
Returns
true if any error has been logged in this run.
Definition at line 205 of file debug.cpp.
 {
     return error_observed;
 }
References error_observed.
Referenced by main().
debugFile()
static DebugFile& debugFile () static
Definition at line 653 of file debug.cpp.
 {
     static DebugFile debugFile;
     return debugFile;
 }
Referenced by DebugLog(), deinitDebug(), and setupDebug().
DebugLog()
std::ostream& DebugLog (DebugLevel lev, DebugClass cl)
Definition at line 1438 of file debug.cpp.
 {
     if( lev & D_ERROR ) {
         error_observed = true;
     }
     // Error are always logged, they are important,
     // Messages from D_MAIN come from debugmsg and are equally important.
     if( ( lev & debugLevel && cl & debugClass ) || lev & D_ERROR || cl & D_MAIN ) {
         std::ostream &out = debugFile().get_file();
         output_repetitions( out );
         out << std::endl;
         out << get_time() << " ";
         out << lev;
         if( cl != debugClass ) {
             out << cl;
         }
         out << ": ";
         // Backtrace on error.
 #if defined(BACKTRACE)
         // Push the first retrieved value back by a second so it won't match.
         static time_t next_backtrace = time( nullptr ) - 1;
         time_t now = time( nullptr );
         if( lev == D_ERROR && now >= next_backtrace ) {
             out << "(error message will follow backtrace)";
             debug_write_backtrace( out );
             time_t after = time( nullptr );
             // Cool down for 60s between backtrace emissions.
             next_backtrace = after + 60;
             out << "Backtrace emission took " << after - now << " seconds." << std::endl;
             out << "(continued from above) " << lev << ": ";
         }
 #endif
         return out;
     }
     static NullStream null_stream;
     return null_stream;
 }
References D_ERROR, D_MAIN, debugClass, debugFile(), debugLevel, error_observed, DebugFile::get_file(), get_time(), and output_repetitions().
Referenced by add_fallback_zone(), tgz_archiver::add_file(), overmap::add_mon_group(), talk_function::assign_mission(), map::bash_rating(), mod_tracker::check_duplicate_entries(), dependency_tree::check_for_strongly_connected_components(), mod_manager::copy_mod_contents(), vehicle_part::deserialize(), stomach_contents::deserialize(), item::craft_data::deserialize(), deserialize(), debug_menu::draw_benchmark(), io::enum_to_string< time_accuracy >(), prof_window::filter(), anonymous_namespace{filesystem.cpp}::for_each_dir_entry(), debug_menu::game_report(), map::generate(), get_diary_time_since_str(), get_diary_time_str(), item::get_saved_recipes(), DebugFile::init(), Character::invlet_to_item(), map::is_bashable(), anonymous_namespace{filesystem.cpp}::is_directory(), SystemLocale::Language(), limitDebugClass(), limitDebugLevel(), monster::load(), overmap_land_use_code::load(), oter_type_t::load(), recipe_dictionary::load(), profession_blacklist::load(), scen_blacklist::load(), map::load(), worldfactory::load_last_world_info(), main(), migrate_bionic_id(), overmap::migrate_oter_ids(), item_location::impl::item_in_container::obtain(), realDebugmsg(), WORLD::save(), mattack::science(), set_language(), npc::set_omt_destination(), fungal_effects::spread_fungus_one_tile(), npc_trading::transfer_items(), options_manager::update_global_locale(), and write_to_file().
deinitDebug()
void deinitDebug ()
Opposite of setupDebug, shuts the debugging system down.
Definition at line 779 of file debug.cpp.
 {
     debugFile().deinit();
 }
References debugFile(), and DebugFile::deinit().
Referenced by anonymous_namespace{main.cpp}::exit_handler().
get_time()
static time_info get_time () static noexcept
Definition at line 617 of file debug.cpp.
 {
     timeval tv;
     gettimeofday( &tv, nullptr );
     const time_t tt      = time_t {tv.tv_sec};
     tm current;
     localtime_r( &tt, &current );
     return time_info { current.tm_hour, current.tm_min, current.tm_sec,
                        static_cast<int>( std::lround( tv.tv_usec / 1000.0 ) )
                      };
 }
Referenced by DebugLog(), DebugFile::deinit(), DebugFile::init(), repetition_folder::set_time(), and repetition_folder::timed_out().
isDebuggerActive()
bool isDebuggerActive ()
Definition at line 1482 of file debug.cpp.
 {
 #if defined(_WIN32)
     // From catch.hpp: both _MSVC_VER and __MINGW32__
     return IsDebuggerPresent() != 0;
 #elif defined(__linux__)
     // From catch.hpp:
     // The standard POSIX way of detecting a debugger is to attempt to
     // ptrace() the process, but this needs to be done from a child and not
     // this process itself to still allow attaching to this process later
     // if wanted, so is rather heavy. Under Linux we have the PID of the
     // "debugger" (which doesn't need to be gdb, of course, it could also
     // be strace, for example) in /proc/$PID/status, so just get it from
     // there instead.
     std::ifstream in( "/proc/self/status" );
     for( std::string line; std::getline( in, line ); ) {
         static const int PREFIX_LEN = 11;
         //NOLINTNEXTLINE(cata-text-style)
         if( line.compare( 0, PREFIX_LEN, "TracerPid:\t" ) == 0 ) {
             // We're traced if the PID is not 0 and no other PID starts
             // with 0 digit, so it's enough to check for just a single
             // character.
             return line.length() > PREFIX_LEN && line[PREFIX_LEN] != '0';
         }
     }
     return false;
 #else
     return false;
 #endif
 }
References line().
Referenced by debug_menu::debug_menu_game_state(), and realDebugmsg().
limitDebugClass()
void limitDebugClass (int class_bitmask)
Set the debug classes should be logged.
bitmask is a OR-combined set of DebugClass values. Use 0 to disable all. Note that D_UNSPECIFIC is always logged.
Definition at line 579 of file debug.cpp.
 {
     DebugLog( DL_ALL, DC_ALL ) << "Set debug class to: " << class_bitmask;
     debugClass = class_bitmask;
 }
References DC_ALL, debugClass, DebugLog(), and DL_ALL.
Referenced by setupDebug().
limitDebugLevel()
void limitDebugLevel (int level_bitmask)
Set debug levels that should be logged.
bitmask is a OR-combined set of DebugLevel values. Use 0 to disable all. Note that D_ERROR is always logged.
Definition at line 573 of file debug.cpp.
 {
     DebugLog( DL_ALL, DC_ALL ) << "Set debug level to: " << level_bitmask;
     debugLevel = level_bitmask;
 }
References DC_ALL, debugLevel, DebugLog(), and DL_ALL.
Referenced by setupDebug().
operator<<() [1/2]
static std::ostream& operator<< (std::ostream & out, DebugClass cl) static
Definition at line 806 of file debug.cpp.
 {
     if( cl != DC_ALL ) {
         if( cl & D_MAIN ) {
             out << "MAIN ";
         }
         if( cl & D_MAP ) {
             out << "MAP ";
         }
         if( cl & D_MAP_GEN ) {
             out << "MAP_GEN ";
         }
         if( cl & D_NPC ) {
             out << "NPC ";
         }
         if( cl & D_GAME ) {
             out << "GAME ";
         }
         if( cl & D_SDL ) {
             out << "SDL ";
         }
         if( cl & D_MMAP ) {
             out << "MMAP ";
         }
     }
     return out;
 }
References D_GAME, D_MAIN, D_MAP, D_MAP_GEN, D_MMAP, D_NPC, D_SDL, and DC_ALL.
operator<<() [2/2]
static std::ostream& operator<< (std::ostream & out, DebugLevel lev) static
Definition at line 787 of file debug.cpp.
 {
     if( lev != DL_ALL ) {
         if( lev & D_INFO ) {
             out << "INFO ";
         }
         if( lev & D_WARNING ) {
             out << "WARNING ";
         }
         if( lev & D_ERROR ) {
             out << "ERROR ";
         }
         if( lev & D_PEDANTIC_INFO ) {
             out << "PEDANTIC ";
         }
     }
     return out;
 }
References D_ERROR, D_INFO, D_PEDANTIC_INFO, D_WARNING, and DL_ALL.
output_repetitions()
void output_repetitions (std::ostream & out) static
Definition at line 1419 of file debug.cpp.
 {
     // Need to complete the folding
     if( rep_folder.repeat_count > 0 ) {
         if( rep_folder.repeat_count > 1 ) {
             out << std::endl;
             out << "[ Previous repeated " << ( rep_folder.repeat_count - 1 ) << " times ]";
         }
         out << std::endl;
         out << rep_folder.m_time << " ";
         // repetition folding is only done through DebugLog( D_ERROR, D_MAIN )
         out << D_ERROR;
         out << ": ";
         out << rep_folder.m_filename << ":" << rep_folder.m_line << " [" << rep_folder.m_funcname << "] " <<
             rep_folder.m_text << std::flush;
         rep_folder.reset();
     }
 }
References D_ERROR, repetition_folder::m_filename, repetition_folder::m_funcname, repetition_folder::m_line, repetition_folder::m_text, repetition_folder::m_time, rep_folder, repetition_folder::repeat_count, and repetition_folder::reset().
Referenced by DebugLog(), and DebugFile::deinit().
realDebugmsg()
void realDebugmsg (const char * filename, const char * line, const char * funcname, const std::string & text)
Definition at line 503 of file debug.cpp.
 {
     cata_assert( filename != nullptr );
     cata_assert( line != nullptr );
     cata_assert( funcname != nullptr );
     if( capturing ) {
         captured += text;
     } else {
         if( !rep_folder.test( filename, line, funcname, text ) ) {
             DebugLog( D_ERROR, D_MAIN ) << filename << ":" << line << " [" << funcname << "] " << text <<
                                         std::flush;
             rep_folder.set( filename, line, funcname, text );
         } else {
             rep_folder.increment_count();
         }
     }
     if( test_mode ) {
         return;
     }
     // Enable the following to step in debug messages with a debugger
 #if 0
     if( isDebuggerActive() ) {
 #if defined(_WIN32)
         DebugBreak();
         return;
 #elif defined( __linux__ )
         raise( SIGTRAP );
         return;
 #endif
     }
 #endif //
     // Show excessive repetition prompt once per excessive set
     bool excess_repetition = rep_folder.repeat_count == repetition_folder::repetition_threshold;
     if( !catacurses::stdscr ) {
         buffered_prompts().push_back( {filename, line, funcname, text, false } );
         if( excess_repetition ) {
             // prepend excessive error repetition to original text then prompt
             std::string rep_err =
                 "Excessive error repetition detected.  Please file a bug report at https://github.com/CleverRaven/Cataclysm-DDA/issues\n            "
                 + text;
             buffered_prompts().push_back( {filename, line, funcname, rep_err, true } );
         }
         return;
     }
     debug_error_prompt( filename, line, funcname, text.c_str(), false );
     if( excess_repetition ) {
         // prepend excessive error repetition to original text then prompt
         std::string rep_err =
             "Excessive error repetition detected.  Please file a bug report at https://github.com/CleverRaven/Cataclysm-DDA/issues\n            "
             + text;
         debug_error_prompt( filename, line, funcname, rep_err.c_str(), true );
         // Do not count this prompt when considering repetition folding
         // Might look weird in the log if the repetitions end exactly after this prompt is displayed.
         rep_folder.set_time();
     }
 }
References buffered_prompts(), captured, capturing, cata_assert, D_ERROR, D_MAIN, debug_error_prompt(), DebugLog(), repetition_folder::increment_count(), isDebuggerActive(), line(), rep_folder, repetition_folder::repeat_count, repetition_folder::repetition_threshold, repetition_folder::set(), repetition_folder::set_time(), catacurses::stdscr, repetition_folder::test(), and test_mode.
Referenced by realDebugmsg().
replay_buffered_debugmsg_prompts()
void replay_buffered_debugmsg_prompts ()
Should be called after catacurses::stdscr is initialized.
If catacurses::stdscr is available, shows all buffered debugmsg prompts.
Definition at line 399 of file debug.cpp.
 {
     if( buffered_prompts().empty() || !catacurses::stdscr ) {
         return;
     }
     for( const buffered_prompt_info &prompt : buffered_prompts() ) {
         debug_error_prompt(
             prompt.filename.c_str(),
             prompt.line.c_str(),
             prompt.funcname.c_str(),
             prompt.text.c_str(),
             prompt.forced
         );
     }
     buffered_prompts().clear();
 }
References buffered_prompts(), debug_error_prompt(), Pickup::prompt, and catacurses::stdscr.
Referenced by main().
setupDebug()
void setupDebug (DebugOutput output_mode)
Initializes the debugging system, called exactly once from main()
Definition at line 730 of file debug.cpp.
 {
     int level = 0;
 #if defined(DEBUG_INFO)
     level |= D_INFO;
 #endif
 #if defined(DEBUG_WARNING)
     level |= D_WARNING;
 #endif
 #if defined(DEBUG_ERROR)
     level |= D_ERROR;
 #endif
 #if defined(DEBUG_PEDANTIC_INFO)
     level |= D_PEDANTIC_INFO;
 #endif
     if( level != 0 ) {
         limitDebugLevel( level );
     }
     int cl = 0;
 #if defined(DEBUG_ENABLE_MAIN)
     cl |= D_MAIN;
 #endif
 #if defined(DEBUG_ENABLE_MAP)
     cl |= D_MAP;
 #endif
 #if defined(DEBUG_ENABLE_MAP_GEN)
     cl |= D_MAP_GEN;
 #endif
 #if defined(DEBUG_ENABLE_GAME)
     cl |= D_GAME;
 #endif
     if( cl != 0 ) {
         limitDebugClass( cl );
     }
     debugFile().init( output_mode, PATH_INFO::debug() );
 }
References D_ERROR, D_GAME, D_INFO, D_MAIN, D_MAP, D_MAP_GEN, D_PEDANTIC_INFO, D_WARNING, PATH_INFO::debug(), debugFile(), DebugFile::init(), limitDebugClass(), and limitDebugLevel().
Referenced by main().
Variable Documentation
captured
std::string captured static
сaptured debug messages.
Definition at line 110 of file debug.cpp.
Referenced by capture_debugmsg::capture_debugmsg(), capture_debugmsg::dmsg(), and realDebugmsg().
capturing
bool capturing = false static
If true, debug messages will be captured, used to test debugmsg calls in the unit tests.
Definition at line 108 of file debug.cpp.
Referenced by capture_debugmsg::capture_debugmsg(), capture_debugmsg::dmsg(), realDebugmsg(), and capture_debugmsg::~capture_debugmsg().
debug_mode
bool debug_mode = false
Extended debugging mode, can be toggled during game.
If enabled some debug message in the normal player message log are shown, and other windows might have verbose display (e.g. vehicle window).
Definition at line 210 of file debug.cpp.
Referenced by add_msg(), Creature::add_msg_if_npc(), Creature::add_msg_if_player(), add_msg_if_player_sees(), Creature::add_msg_player_or_npc(), Creature::add_msg_player_or_say(), anonymous_namespace{messages.cpp}::messages_impl::add_msg_string(), debug_drop_list(), effect::disp_desc(), Character::disp_info(), veh_interact::display_veh(), game::draw_critter(), draw_proficiencies_info(), monster::extended_description(), Messages::dialog::filter_help_text(), handle_debug_mode(), Messages::has_debug_filter(), hp_description(), item::info(), item::melee_combat_info(), vehicle_part::name(), game::npc_menu(), print_damage_info(), vehicle::print_fuel_indicator(), monster::print_info(), item::process_link(), iuse::sextant(), smash(), game::zones_manager(), and zones_manager_shortcuts().
debugClass
int debugClass = D_MAIN static
Definition at line 99 of file debug.cpp.
Referenced by DebugLog(), and limitDebugClass().
debugLevel
int debugLevel = D_ERROR static
Definition at line 98 of file debug.cpp.
Referenced by DebugLog(), and limitDebugLevel().
error_observed
bool error_observed = false static
Set to true when any error is logged.
Definition at line 103 of file debug.cpp.
Referenced by debug_has_error_been_observed(), and DebugLog().
rep_folder
repetition_folder rep_folder static
Definition at line 500 of file debug.cpp.
Referenced by output_repetitions(), and realDebugmsg().