Cataclysm DDA: src/debug.h File Reference
debug.h File Reference
#include "string_formatter.h"
#include <unordered_set>
#include <functional>
#include <iostream>
#include <type_traits>
Namespaces
game_info
Used to generate game report information.
debugmode
Macros
#define CATA_SRC_DEBUG_H
#define STRING2(x) #x
#define STRING(x) STRING2(x)
#define CATA_FUNCTION_NAME __func__
#define debugmsg(...) realDebugmsg(__FILE__, STRING(__LINE__), CATA_FUNCTION_NAME, __VA_ARGS__)
Debug message of level D_ERROR and class D_MAIN, also includes the source file name and line, uses varg style arguments, the first argument must be a printf style format string.
#define cata_fatal(...)
#define constexpr_fatal(ret, ...) do { debugmsg(__VA_ARGS__); abort(); } while(false)
Enumerations
enum DebugLevel {
D_INFO = 1 , D_WARNING = 1 << 2 , D_ERROR = 1 << 3 , D_PEDANTIC_INFO = 1 << 4 ,
DL_ALL = (1 << 5) - 1
}
If you add an entry, add an entry in that function: std::ostream &operator<<(std::ostream &out, DebugLevel lev)
enum DebugClass {
D_MAIN = 1 , D_MAP = 1 << 2 , D_MAP_GEN = 1 << 3 , D_GAME = 1 << 4 ,
D_NPC = 1 << 5 , D_SDL = 1 << 6 , D_MMAP = 1 << 7 , DC_ALL = (1 << 30) - 1
}
Debugging areas can be enabled for each of those areas separately.
enum class DebugOutput : int { std_err , file }
enum debugmode::debug_filter : int {
debugmode::DF_ACT_BUTCHER = 0 , debugmode::DF_ACT_EBOOK , debugmode::DF_ACT_HARVEST , debugmode::DF_ACT_LOCKPICK ,
debugmode::DF_ACT_READ , debugmode::DF_ACT_SAFECRACKING , debugmode::DF_ACT_SHEARING , debugmode::DF_ACT_WORKOUT ,
debugmode::DF_ACTIVITY , debugmode::DF_ANATOMY_BP , debugmode::DF_AVATAR , debugmode::DF_BALLISTIC ,
debugmode::DF_CHARACTER , debugmode::DF_CHAR_CALORIES , debugmode::DF_CHAR_HEALTH , debugmode::DF_CRAFTING ,
debugmode::DF_CREATURE , debugmode::DF_EFFECT , debugmode::DF_EXPLOSION , debugmode::DF_FOOD ,
debugmode::DF_GAME , debugmode::DF_IEXAMINE , debugmode::DF_IUSE , debugmode::DF_MAP ,
debugmode::DF_MATTACK , debugmode::DF_MELEE , debugmode::DF_MONMOVE , debugmode::DF_MONSTER ,
debugmode::DF_MUTATION , debugmode::DF_NPC , debugmode::DF_NPC_COMBATAI , debugmode::DF_NPC_ITEMAI ,
debugmode::DF_NPC_MOVEAI , debugmode::DF_OVERMAP , debugmode::DF_RADIO , debugmode::DF_RANGED ,
debugmode::DF_REQUIREMENTS_MAP , debugmode::DF_SOUND , debugmode::DF_TALKER , debugmode::DF_VEHICLE ,
debugmode::DF_VEHICLE_DRAG , debugmode::DF_VEHICLE_MOVE , debugmode::DF_LAST
}
Functions
void realDebugmsg (const char *filename, const char *line, const char *funcname, const std::string &text)
template<typename ... Args>
void realDebugmsg (const char *const filename, const char *const line, const char *const funcname, const char *const mes, Args &&... args)
std::string game_info::operating_system ()
Return the name of the current operating system.
std::string game_info::operating_system_version ()
Return a detailed version of the operating system; e.g.
std::string game_info::bitness ()
Return the "bitness" of the game (not necessarily of the operating system); either: 64-bit, 32-bit or Unknown.
std::string game_info::game_version ()
Return the game version, as in the entry screen.
std::string game_info::graphics_version ()
Return the underlying graphics version used by the game; either Tiles or Curses.
std::string game_info::mods_loaded ()
Return a list of the loaded mods, including the mod full name and its id name in brackets, e.g.
std::string game_info::game_report ()
Generate a game report, including the information returned by all of the other functions.
DebugLevel operator| (DebugLevel l, DebugLevel r)
void setupDebug (DebugOutput)
Initializes the debugging system, called exactly once from main()
void deinitDebug ()
Opposite of setupDebug, shuts the debugging system down.
void limitDebugLevel (int)
Set debug levels that should be logged.
void limitDebugClass (int)
Set the debug classes should be logged.
bool debug_has_error_been_observed ()
std::string capture_debugmsg_during (const std::function< void()> &func)
Capturing debug messages during func execution, used to test debugmsg calls in the unit tests.
void replay_buffered_debugmsg_prompts ()
Should be called after catacurses::stdscr is initialized.
std::ostream & DebugLog (DebugLevel, DebugClass)
std::string debugmode::filter_name (debug_filter value)
bool isDebuggerActive ()
Variables
bool debug_mode
Extended debugging mode, can be toggled during game.
Macro Definition Documentation
cata_fatal
#define cata_fatal (...)
Value:
    do { \
        debugmsg(__VA_ARGS__); \
        std::abort(); \
    } while( false )
Definition at line 83 of file debug.h.
CATA_FUNCTION_NAME
#define CATA_FUNCTION_NAME __func__
Definition at line 60 of file debug.h.
CATA_SRC_DEBUG_H
#define CATA_SRC_DEBUG_H
Definition at line 3 of file debug.h.
constexpr_fatal
#define constexpr_fatal (ret, ...) do { debugmsg(__VA_ARGS__); abort(); } while(false)
Definition at line 100 of file debug.h.
debugmsg
#define debugmsg (...) realDebugmsg(__FILE__, STRING(__LINE__), CATA_FUNCTION_NAME, __VA_ARGS__)
Debug message of level D_ERROR and class D_MAIN, also includes the source file name and line, uses varg style arguments, the first argument must be a printf style format string.
Definition at line 69 of file debug.h.
STRING
#define STRING (x) STRING2(x)
Definition at line 55 of file debug.h.
STRING2
#define STRING2 (x) #x
    debugmsg(msg, ...)
varg-style functions: the first argument is the format (see printf), the other optional arguments must match that format. The message is formatted and printed on screen to player, they must acknowledge the message by pressing SPACE. This can be quite annoying, so avoid this function if possible. The message is also logged with DebugLog, a separate call to DebugLog is not needed.
 DebugLog
The main debugging system. It uses debug levels (how critical/important the message is) and debug classes (which part of the code it comes from, e.g. mapgen, SDL, npcs). This allows disabling debug classes and levels (e.g. only write SDL messages, but no npc or map related ones). It returns a reference to an outputs stream. Simply write your message into that stream (using the << operators). DebugLog always returns a stream that starts on a new line. Don't add a newline at the end of your debug message. If the specific debug level or class have been disabled, the message is actually discarded, otherwise it is written to a log file. If a single source file contains mostly messages for the same debug class (e.g. mapgen.cpp), create and use the macro dbg.
 dbg
Usually a single source contains only debug messages for a single debug class (e.g. mapgen.cpp contains only messages for D_MAP_GEN, npcmove.cpp only D_NPC). Those files contain a macro at top:
#define dbg(x) DebugLog((x), D_NPC) << __FILE__ << ":" << __LINE__ << ": "
It allows to call the debug system and just supply the debug level, the debug class is automatically inserted as it is the same for the whole file. Also this adds the file name and the line of the statement to the debug message. This can be replicated in any source file, just copy the above macro and change D_NPC to the debug class to use. Don't add this macro to a header file as the debug class is source file specific. As dbg calls DebugLog, it returns the stream, its usage is the same.
Definition at line 54 of file debug.h.
Enumeration Type Documentation
DebugClass
enum DebugClass
Debugging areas can be enabled for each of those areas separately.
If you add an entry, add an entry in that function: std::ostream &operator<<(std::ostream &out, DebugClass cl)
Enumerator
D_MAIN
Messages from realDebugmsg.
D_MAP
Related to map and mapbuffer (map.cpp, mapbuffer.cpp)
D_MAP_GEN
Mapgen (mapgen*.cpp), also overmap.cpp.
D_GAME
Main game class.
D_NPC
npcs*.cpp
D_SDL
SDL & tiles & anything graphical.
D_MMAP
Related to tile memory (map_memory.cpp)
DC_ALL
Definition at line 159 of file debug.h.
                 {
     /** Messages from realDebugmsg */
     D_MAIN    = 1,
     /** Related to map and mapbuffer (map.cpp, mapbuffer.cpp) */
     D_MAP     = 1 << 2,
     /** Mapgen (mapgen*.cpp), also overmap.cpp */
     D_MAP_GEN = 1 << 3,
     /** Main game class */
     D_GAME    = 1 << 4,
     /** npcs*.cpp */
     D_NPC     = 1 << 5,
     /** SDL & tiles & anything graphical */
     D_SDL     = 1 << 6,
     /** Related to tile memory (map_memory.cpp) */
     D_MMAP    = 1 << 7,
     DC_ALL    = ( 1 << 30 ) - 1
 };
DebugLevel
enum DebugLevel
If you add an entry, add an entry in that function: std::ostream &operator<<(std::ostream &out, DebugLevel lev)
Enumerator
D_INFO
D_WARNING
D_ERROR
D_PEDANTIC_INFO
DL_ALL
Definition at line 139 of file debug.h.
                 {
     D_INFO          = 1,
     D_WARNING       = 1 << 2,
     D_ERROR         = 1 << 3,
     D_PEDANTIC_INFO = 1 << 4,
     DL_ALL = ( 1 << 5 ) - 1
 };
DebugOutput
enum DebugOutput : int strong
Enumerator
std_err
file
Definition at line 178 of file debug.h.
                        : int {
     std_err,
     file,
 };
Function Documentation
capture_debugmsg_during()
std::string capture_debugmsg_during (const std::function< void()> & func)
Capturing debug messages during func execution, used to test debugmsg calls in the unit tests.
Returns
std::string debugmsg
Definition at line 181 of file debug.cpp.
 {
     capture_debugmsg capture;
     func();
     return capture.dmsg();
 }
References capture_debugmsg::dmsg().
debug_has_error_been_observed()
bool debug_has_error_been_observed ()
Returns
true if any error has been logged in this run.
Definition at line 205 of file debug.cpp.
 {
     return error_observed;
 }
References error_observed.
Referenced by main().
DebugLog()
std::ostream& DebugLog (DebugLevel lev, DebugClass cl)
Definition at line 1438 of file debug.cpp.
 {
     if( lev & D_ERROR ) {
         error_observed = true;
     }
     // Error are always logged, they are important,
     // Messages from D_MAIN come from debugmsg and are equally important.
     if( ( lev & debugLevel && cl & debugClass ) || lev & D_ERROR || cl & D_MAIN ) {
         std::ostream &out = debugFile().get_file();
         output_repetitions( out );
         out << std::endl;
         out << get_time() << " ";
         out << lev;
         if( cl != debugClass ) {
             out << cl;
         }
         out << ": ";
         // Backtrace on error.
 #if defined(BACKTRACE)
         // Push the first retrieved value back by a second so it won't match.
         static time_t next_backtrace = time( nullptr ) - 1;
         time_t now = time( nullptr );
         if( lev == D_ERROR && now >= next_backtrace ) {
             out << "(error message will follow backtrace)";
             debug_write_backtrace( out );
             time_t after = time( nullptr );
             // Cool down for 60s between backtrace emissions.
             next_backtrace = after + 60;
             out << "Backtrace emission took " << after - now << " seconds." << std::endl;
             out << "(continued from above) " << lev << ": ";
         }
 #endif
         return out;
     }
     static NullStream null_stream;
     return null_stream;
 }
References D_ERROR, D_MAIN, debugClass, debugFile(), debugLevel, error_observed, DebugFile::get_file(), get_time(), and output_repetitions().
Referenced by add_fallback_zone(), tgz_archiver::add_file(), overmap::add_mon_group(), talk_function::assign_mission(), map::bash_rating(), mod_tracker::check_duplicate_entries(), dependency_tree::check_for_strongly_connected_components(), mod_manager::copy_mod_contents(), vehicle_part::deserialize(), stomach_contents::deserialize(), item::craft_data::deserialize(), deserialize(), debug_menu::draw_benchmark(), io::enum_to_string< time_accuracy >(), prof_window::filter(), anonymous_namespace{filesystem.cpp}::for_each_dir_entry(), debug_menu::game_report(), map::generate(), get_diary_time_since_str(), get_diary_time_str(), item::get_saved_recipes(), DebugFile::init(), Character::invlet_to_item(), map::is_bashable(), anonymous_namespace{filesystem.cpp}::is_directory(), SystemLocale::Language(), limitDebugClass(), limitDebugLevel(), monster::load(), overmap_land_use_code::load(), oter_type_t::load(), recipe_dictionary::load(), profession_blacklist::load(), scen_blacklist::load(), map::load(), worldfactory::load_last_world_info(), main(), migrate_bionic_id(), overmap::migrate_oter_ids(), item_location::impl::item_in_container::obtain(), realDebugmsg(), WORLD::save(), mattack::science(), set_language(), npc::set_omt_destination(), fungal_effects::spread_fungus_one_tile(), npc_trading::transfer_items(), options_manager::update_global_locale(), and write_to_file().
deinitDebug()
void deinitDebug ()
Opposite of setupDebug, shuts the debugging system down.
Definition at line 779 of file debug.cpp.
 {
     debugFile().deinit();
 }
References debugFile(), and DebugFile::deinit().
Referenced by anonymous_namespace{main.cpp}::exit_handler().
isDebuggerActive()
bool isDebuggerActive ()
Definition at line 1482 of file debug.cpp.
 {
 #if defined(_WIN32)
     // From catch.hpp: both _MSVC_VER and __MINGW32__
     return IsDebuggerPresent() != 0;
 #elif defined(__linux__)
     // From catch.hpp:
     // The standard POSIX way of detecting a debugger is to attempt to
     // ptrace() the process, but this needs to be done from a child and not
     // this process itself to still allow attaching to this process later
     // if wanted, so is rather heavy. Under Linux we have the PID of the
     // "debugger" (which doesn't need to be gdb, of course, it could also
     // be strace, for example) in /proc/$PID/status, so just get it from
     // there instead.
     std::ifstream in( "/proc/self/status" );
     for( std::string line; std::getline( in, line ); ) {
         static const int PREFIX_LEN = 11;
         //NOLINTNEXTLINE(cata-text-style)
         if( line.compare( 0, PREFIX_LEN, "TracerPid:\t" ) == 0 ) {
             // We're traced if the PID is not 0 and no other PID starts
             // with 0 digit, so it's enough to check for just a single
             // character.
             return line.length() > PREFIX_LEN && line[PREFIX_LEN] != '0';
         }
     }
     return false;
 #else
     return false;
 #endif
 }
References line().
Referenced by debug_menu::debug_menu_game_state(), and realDebugmsg().
limitDebugClass()
void limitDebugClass (int class_bitmask)
Set the debug classes should be logged.
bitmask is a OR-combined set of DebugClass values. Use 0 to disable all. Note that D_UNSPECIFIC is always logged.
Definition at line 579 of file debug.cpp.
 {
     DebugLog( DL_ALL, DC_ALL ) << "Set debug class to: " << class_bitmask;
     debugClass = class_bitmask;
 }
References DC_ALL, debugClass, DebugLog(), and DL_ALL.
Referenced by setupDebug().
limitDebugLevel()
void limitDebugLevel (int level_bitmask)
Set debug levels that should be logged.
bitmask is a OR-combined set of DebugLevel values. Use 0 to disable all. Note that D_ERROR is always logged.
Definition at line 573 of file debug.cpp.
 {
     DebugLog( DL_ALL, DC_ALL ) << "Set debug level to: " << level_bitmask;
     debugLevel = level_bitmask;
 }
References DC_ALL, debugLevel, DebugLog(), and DL_ALL.
Referenced by setupDebug().
operator|()
DebugLevel operator| (DebugLevel l, DebugLevel r) inline
Definition at line 148 of file debug.h.
 {
     return static_cast<DebugLevel>(
                static_cast<std::underlying_type_t<DebugLevel>>( l ) | r );
 }
realDebugmsg() [1/2]
template<typename ... Args> void realDebugmsg (const char *const filename, const char *const line, const char *const funcname, const char *const mes, Args &&... args) inline
Definition at line 75 of file debug.h.
 {
     return realDebugmsg( filename, line, funcname, string_format( mes,
                          std::forward<Args>( args )... ) );
 }
References line(), realDebugmsg(), and string_format().
realDebugmsg() [2/2]
void realDebugmsg (const char * filename, const char * line, const char * funcname, const std::string & text)
Definition at line 503 of file debug.cpp.
 {
     cata_assert( filename != nullptr );
     cata_assert( line != nullptr );
     cata_assert( funcname != nullptr );
     if( capturing ) {
         captured += text;
     } else {
         if( !rep_folder.test( filename, line, funcname, text ) ) {
             DebugLog( D_ERROR, D_MAIN ) << filename << ":" << line << " [" << funcname << "] " << text <<
                                         std::flush;
             rep_folder.set( filename, line, funcname, text );
         } else {
             rep_folder.increment_count();
         }
     }
     if( test_mode ) {
         return;
     }
     // Enable the following to step in debug messages with a debugger
 #if 0
     if( isDebuggerActive() ) {
 #if defined(_WIN32)
         DebugBreak();
         return;
 #elif defined( __linux__ )
         raise( SIGTRAP );
         return;
 #endif
     }
 #endif //
     // Show excessive repetition prompt once per excessive set
     bool excess_repetition = rep_folder.repeat_count == repetition_folder::repetition_threshold;
     if( !catacurses::stdscr ) {
         buffered_prompts().push_back( {filename, line, funcname, text, false } );
         if( excess_repetition ) {
             // prepend excessive error repetition to original text then prompt
             std::string rep_err =
                 "Excessive error repetition detected.  Please file a bug report at https://github.com/CleverRaven/Cataclysm-DDA/issues\n            "
                 + text;
             buffered_prompts().push_back( {filename, line, funcname, rep_err, true } );
         }
         return;
     }
     debug_error_prompt( filename, line, funcname, text.c_str(), false );
     if( excess_repetition ) {
         // prepend excessive error repetition to original text then prompt
         std::string rep_err =
             "Excessive error repetition detected.  Please file a bug report at https://github.com/CleverRaven/Cataclysm-DDA/issues\n            "
             + text;
         debug_error_prompt( filename, line, funcname, rep_err.c_str(), true );
         // Do not count this prompt when considering repetition folding
         // Might look weird in the log if the repetitions end exactly after this prompt is displayed.
         rep_folder.set_time();
     }
 }
References buffered_prompts(), captured, capturing, cata_assert, D_ERROR, D_MAIN, debug_error_prompt(), DebugLog(), repetition_folder::increment_count(), isDebuggerActive(), line(), rep_folder, repetition_folder::repeat_count, repetition_folder::repetition_threshold, repetition_folder::set(), repetition_folder::set_time(), catacurses::stdscr, repetition_folder::test(), and test_mode.
Referenced by realDebugmsg().
replay_buffered_debugmsg_prompts()
void replay_buffered_debugmsg_prompts ()
Should be called after catacurses::stdscr is initialized.
If catacurses::stdscr is available, shows all buffered debugmsg prompts.
Definition at line 399 of file debug.cpp.
 {
     if( buffered_prompts().empty() || !catacurses::stdscr ) {
         return;
     }
     for( const buffered_prompt_info &prompt : buffered_prompts() ) {
         debug_error_prompt(
             prompt.filename.c_str(),
             prompt.line.c_str(),
             prompt.funcname.c_str(),
             prompt.text.c_str(),
             prompt.forced
         );
     }
     buffered_prompts().clear();
 }
References buffered_prompts(), debug_error_prompt(), Pickup::prompt, and catacurses::stdscr.
Referenced by main().
setupDebug()
void setupDebug (DebugOutput output_mode)
Initializes the debugging system, called exactly once from main()
Definition at line 730 of file debug.cpp.
 {
     int level = 0;
 #if defined(DEBUG_INFO)
     level |= D_INFO;
 #endif
 #if defined(DEBUG_WARNING)
     level |= D_WARNING;
 #endif
 #if defined(DEBUG_ERROR)
     level |= D_ERROR;
 #endif
 #if defined(DEBUG_PEDANTIC_INFO)
     level |= D_PEDANTIC_INFO;
 #endif
     if( level != 0 ) {
         limitDebugLevel( level );
     }
     int cl = 0;
 #if defined(DEBUG_ENABLE_MAIN)
     cl |= D_MAIN;
 #endif
 #if defined(DEBUG_ENABLE_MAP)
     cl |= D_MAP;
 #endif
 #if defined(DEBUG_ENABLE_MAP_GEN)
     cl |= D_MAP_GEN;
 #endif
 #if defined(DEBUG_ENABLE_GAME)
     cl |= D_GAME;
 #endif
     if( cl != 0 ) {
         limitDebugClass( cl );
     }
     debugFile().init( output_mode, PATH_INFO::debug() );
 }
References D_ERROR, D_GAME, D_INFO, D_MAIN, D_MAP, D_MAP_GEN, D_PEDANTIC_INFO, D_WARNING, PATH_INFO::debug(), debugFile(), DebugFile::init(), limitDebugClass(), and limitDebugLevel().
Referenced by main().
Variable Documentation
debug_mode
bool debug_mode extern
Extended debugging mode, can be toggled during game.
If enabled some debug message in the normal player message log are shown, and other windows might have verbose display (e.g. vehicle window).
Definition at line 210 of file debug.cpp.
Referenced by add_msg(), Creature::add_msg_if_npc(), Creature::add_msg_if_player(), add_msg_if_player_sees(), Creature::add_msg_player_or_npc(), Creature::add_msg_player_or_say(), anonymous_namespace{messages.cpp}::messages_impl::add_msg_string(), debug_drop_list(), effect::disp_desc(), Character::disp_info(), veh_interact::display_veh(), game::draw_critter(), draw_proficiencies_info(), monster::extended_description(), Messages::dialog::filter_help_text(), handle_debug_mode(), Messages::has_debug_filter(), hp_description(), item::info(), item::melee_combat_info(), vehicle_part::name(), game::npc_menu(), print_damage_info(), vehicle::print_fuel_indicator(), monster::print_info(), item::process_link(), iuse::sextant(), smash(), game::zones_manager(), and zones_manager_shortcuts().