Cataclysm DDA: src/demangle.h File Reference
demangle.h File Reference
#include <string>
Macros
#define CATA_SRC_DEMANGLE_H
Functions
std::string demangle (const char *symbol)
Demangles a C++ symbol.
Macro Definition Documentation
CATA_SRC_DEMANGLE_H
#define CATA_SRC_DEMANGLE_H
Definition at line 3 of file demangle.h.
Function Documentation
demangle()
std::string demangle (const char * symbol)
Demangles a C++ symbol.
Definition at line 7 of file demangle.cpp.
 {
 #if defined(_MSC_VER)
     // TODO: implement demangling on MSVC
 #elif defined(__GNUC__) || defined(__clang__)
     int status = -1;
     char *demangled = abi::__cxa_demangle( symbol, nullptr, nullptr, &status );
     if( status == 0 ) {
         std::string demangled_str( demangled );
         free( demangled );
         return demangled_str;
     }
 #if defined(_WIN32)
     // https://stackoverflow.com/questions/54333608/boost-stacktrace-not-demangling-names-when-cross-compiled
     // libbacktrace may strip leading underscore character in the symbol name returned
     // so if demangling failed, try again with an underscore prepended
     std::string prepend_underscore( "_" );
     prepend_underscore = prepend_underscore + symbol;
     demangled = abi::__cxa_demangle( prepend_underscore.c_str(), nullptr, nullptr, &status );
     if( status == 0 ) {
         std::string demangled_str( demangled );
         free( demangled );
         return demangled_str;
     }
 #endif // defined(_WIN32)
 #endif // compiler macros
     return std::string( symbol );
 }
References status, and symbol().
Referenced by mod_tracker::check_duplicate_entries(), cata::convert(), generic_typed_reader< Derived >::do_relative(), editmap::edit_feature(), handle_proportional(), handle_relative(), and io::string_to_enum_look_up().