Cataclysm DDA: src/dialogue.h File Reference
dialogue.h File Reference
#include <functional>
#include <iosfwd>
#include <memory>
#include <set>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>
#include "cata_lazy.h"
#include "dialogue_win.h"
#include "global_vars.h"
#include "npc.h"
#include "talker.h"
#include "translations.h"
#include "type_id.h"
Classes
struct talk_trial
If not TALK_TRIAL_NONE, it defines how to decide whether the responses succeeds (e.g.
struct talk_topic
struct talk_effect_t
Defines what happens when the trial succeeds or fails.
struct talk_response
This defines possible responses from the player character.
struct dialogue
struct dynamic_line_t
A dynamically generated line, spoken by the NPC.
class json_talk_response
An extended response.
class json_talk_repeat_response
A structure for generating repeated responses.
class json_dynamic_line_effect
class json_talk_topic
Talk topic definitions load from json.
Macros
#define CATA_SRC_DIALOGUE_H
Typedefs
using talkfunction_ptr = std::add_pointer_t< void(npc &)>
using dialogue_fun_ptr = std::add_pointer_t< void(npc &)>
using trial_mod = std::pair< std::string, int >
Enumerations
enum talk_trial_type : unsigned char {
TALK_TRIAL_NONE , TALK_TRIAL_LIE , TALK_TRIAL_PERSUADE , TALK_TRIAL_INTIMIDATE ,
TALK_TRIAL_SKILL_CHECK , TALK_TRIAL_CONDITION , NUM_TALK_TRIALS
}
enum dialogue_consequence : unsigned char { none = 0 , hostile , helpless , action }
Functions
void unload_talk_topics ()
void load_talk_topic (const JsonObject &jo)
Macro Definition Documentation
CATA_SRC_DIALOGUE_H
#define CATA_SRC_DIALOGUE_H
Definition at line 3 of file dialogue.h.
Typedef Documentation
dialogue_fun_ptr
using dialogue_fun_ptr = std::add_pointer_t<void(npc &)>
Definition at line 47 of file dialogue.h.
talkfunction_ptr
using talkfunction_ptr = std::add_pointer_t<void (npc &)>
Definition at line 46 of file dialogue.h.
trial_mod
using trial_mod = std::pair<std::string, int>
Definition at line 49 of file dialogue.h.
Enumeration Type Documentation
dialogue_consequence
enum dialogue_consequence : unsigned char
Enumerator
none
hostile
helpless
action
Definition at line 39 of file dialogue.h.
                           : unsigned char {
     none = 0,
     hostile,
     helpless,
     action
 };
talk_trial_type
enum talk_trial_type : unsigned char
Enumerator
TALK_TRIAL_NONE
TALK_TRIAL_LIE
TALK_TRIAL_PERSUADE
TALK_TRIAL_INTIMIDATE
TALK_TRIAL_SKILL_CHECK
TALK_TRIAL_CONDITION
NUM_TALK_TRIALS
Definition at line 29 of file dialogue.h.
                      : unsigned char {
     TALK_TRIAL_NONE, // No challenge here!
     TALK_TRIAL_LIE, // Straight up lying
     TALK_TRIAL_PERSUADE, // Convince them
     TALK_TRIAL_INTIMIDATE, // Physical intimidation
     TALK_TRIAL_SKILL_CHECK, // Check a skill's current level against the difficulty
     TALK_TRIAL_CONDITION, // Some other condition
     NUM_TALK_TRIALS
 };
Function Documentation
load_talk_topic()
void load_talk_topic (const JsonObject & jo)
Definition at line 7147 of file npctalk.cpp.
 {
     if( jo.has_array( "id" ) ) {
         for( auto &id : jo.get_string_array( "id" ) ) {
             json_talk_topics[id].load( jo );
         }
     } else {
         const std::string id = jo.get_string( "id" );
         json_talk_topics[id].load( jo );
     }
 }
References JsonObject::get_string(), JsonObject::get_string_array(), JsonObject::has_array(), int_id< T >::id(), and json_talk_topics.
Referenced by DynamicDataLoader::initialize().
unload_talk_topics()
void unload_talk_topics ()
Definition at line 7142 of file npctalk.cpp.
 {
     json_talk_topics.clear();
 }
References json_talk_topics.
Referenced by DynamicDataLoader::unload_data().