Cataclysm DDA: src/dialogue_helpers.cpp File Reference
dialogue_helpers.cpp File Reference
#include "dialogue_helpers.h"
#include <string>
#include "dialogue.h"
#include "rng.h"
#include "talker.h"
Functions
template<class T >
std::optional< std::string > maybe_read_var_value (const abstract_var_info< T > &info, const dialogue &d, int call_depth)
template std::optional< std::string > maybe_read_var_value (const var_info &, const dialogue &, int call_depth)
template std::optional< std::string > maybe_read_var_value (const translation_var_info &, const dialogue &, int call_depth)
template<>
std::string read_var_value (const var_info &info, const dialogue &d)
template<>
std::string read_var_value (const translation_var_info &info, const dialogue &d)
var_info process_variable (const std::string &type)
Function Documentation
maybe_read_var_value() [1/3]
template<class T > std::optional<std::string> maybe_read_var_value (const abstract_var_info< T > & info, const dialogue & d, int call_depth)
Definition at line 10 of file dialogue_helpers.cpp.
 {
     global_variables &globvars = get_globals();
     switch( info.type ) {
         case var_type::global:
             return globvars.maybe_get_global_value( info.name );
         case var_type::context:
             return d.maybe_get_value( info.name );
         case var_type::u:
             return d.actor( false )->maybe_get_value( info.name );
         case var_type::npc:
             return d.actor( true )->maybe_get_value( info.name );
         case var_type::var: {
             std::optional<std::string> const var_val = d.maybe_get_value( info.name );
             if( call_depth > 1000 && var_val ) {
                 debugmsg( "Possible infinite loop detected: var_val points to itself or forms a cycle.  %s->%s %s",
                           info.name, var_val.value(), d.get_callstack() );
                 return std::nullopt;
             } else {
                 return var_val ? maybe_read_var_value( process_variable( *var_val ), d,
                                                        call_depth + 1 ) : std::nullopt;
             }
         }
         case var_type::faction:
         case var_type::party:
         case var_type::last:
             return std::nullopt;
     }
     return std::nullopt;
 }
References dialogue::actor(), context, debugmsg, faction, dialogue::get_callstack(), get_globals(), global, last, global_variables::maybe_get_global_value(), talker::maybe_get_value(), dialogue::maybe_get_value(), abstract_var_info< T >::name, npc, party, process_variable(), abstract_var_info< T >::type, u, and var.
Referenced by anonymous_namespace{math_parser_diag.cpp}::has_var_eval(), read_var_value(), anonymous_namespace{math_parser_diag.cpp}::time_since_eval(), anonymous_namespace{math_parser_diag.cpp}::time_until_eval(), and anonymous_namespace{math_parser_diag.cpp}::value_or_eval().
maybe_read_var_value() [2/3]
template std::optional<std::string> maybe_read_var_value (const translation_var_info & , const dialogue & , int call_depth)
maybe_read_var_value() [3/3]
template std::optional<std::string> maybe_read_var_value (const var_info & , const dialogue & , int call_depth)
process_variable()
var_info process_variable (const std::string & type)
Definition at line 61 of file dialogue_helpers.cpp.
 {
     var_type vt = var_type::global;
     std::string ret_str = type;
     if( type.compare( 0, 2, "u_" ) == 0 ) {
         vt = var_type::u;
         ret_str = type.substr( 2, type.size() - 2 );
     } else if( type.compare( 0, 4, "npc_" ) == 0 ) {
         vt = var_type::npc;
         ret_str = type.substr( 4, type.size() - 4 );
     } else if( type.compare( 0, 2, "n_" ) == 0 ) {
         vt = var_type::npc;
         ret_str = type.substr( 2, type.size() - 2 );
     } else if( type.compare( 0, 7, "global_" ) == 0 ) {
         vt = var_type::global;
         ret_str = type.substr( 7, type.size() - 7 );
     } else if( type.compare( 0, 2, "g_" ) == 0 ) {
         vt = var_type::global;
         ret_str = type.substr( 2, type.size() - 2 );
     } else if( type.compare( 0, 2, "v_" ) == 0 ) {
         vt = var_type::var;
         ret_str = type.substr( 2, type.size() - 2 );
     } else if( type.compare( 0, 8, "context_" ) == 0 ) {
         vt = var_type::context;
         ret_str = type.substr( 8, type.size() - 8 );
     } else if( type.compare( 0, 1, "_" ) == 0 ) {
         vt = var_type::context;
         ret_str = type.substr( 1, type.size() - 1 );
     }
     return var_info( vt, "npctalk_var_" + ret_str );
 }
References context, global, npc, u, and var.
Referenced by maybe_read_var_value(), and write_var_value().
read_var_value() [1/2]
template<> std::string read_var_value (const translation_var_info & info, const dialogue & d)
Definition at line 56 of file dialogue_helpers.cpp.
 {
     return maybe_read_var_value( info, d ).value_or( info.default_val.translated() );
 }
References abstract_var_info< T >::default_val, and maybe_read_var_value().
read_var_value() [2/2]
template<> std::string read_var_value (const var_info & info, const dialogue & d)
Definition at line 50 of file dialogue_helpers.cpp.
 {
     return maybe_read_var_value( info, d ).value_or( info.default_val );
 }
References abstract_var_info< T >::default_val, and maybe_read_var_value().
Referenced by diag_value::dbl(), var::eval(), dbl_or_var_part::evaluate(), duration_or_var_part::evaluate(), abstract_str_or_var< T >::evaluate(), get_tripoint_from_var(), and diag_value::str().