Cataclysm DDA: src/display.cpp File Reference
display.cpp File Reference
#include "display.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdlib>
#include <memory>
#include <tuple>
#include <type_traits>
#include <vector>
#include "avatar.h"
#include "bodygraph.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "creature.h"
#include "debug.h"
#include "effect.h"
#include "game.h"
#include "game_constants.h"
#include "make_static.h"
#include "map.h"
#include "mood_face.h"
#include "move_mode.h"
#include "mtype.h"
#include "npc.h"
#include "omdata.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "string_formatter.h"
#include "subbodypart.h"
#include "tileray.h"
#include "timed_event.h"
#include "translation.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "units_utility.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "weather.h"
#include "weather_type.h"
Functions
static std::pair< bodypart_id, bodypart_id > temp_delta (const Character &u)
static std::string get_compass_for_direction (const cardinal_direction dir, int max_width)
static std::pair< std::string, nc_color > get_bodygraph_bp_sym_color (const Character &u, const bodygraph_part &bgp, const bodygraph_var var)
Variables
static const efftype_id effect_bite ("bite")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_got_checked ("got_checked")
static const efftype_id effect_hunger_blank ("hunger_blank")
static const efftype_id effect_hunger_engorged ("hunger_engorged")
static const efftype_id effect_hunger_famished ("hunger_famished")
static const efftype_id effect_hunger_full ("hunger_full")
static const efftype_id effect_hunger_hungry ("hunger_hungry")
static const efftype_id effect_hunger_near_starving ("hunger_near_starving")
static const efftype_id effect_hunger_satisfied ("hunger_satisfied")
static const efftype_id effect_hunger_starving ("hunger_starving")
static const efftype_id effect_hunger_very_hungry ("hunger_very_hungry")
static const efftype_id effect_infected ("infected")
static const flag_id json_flag_THERMOMETER ("THERMOMETER")
static const itype_id fuel_type_muscle ("muscle")
static disp_overmap_cache disp_om_cache
static std::array< disp_bodygraph_cache, 5 > disp_bg_cache
Function Documentation
get_bodygraph_bp_sym_color()
static std::pair<std::string, nc_color> get_bodygraph_bp_sym_color (const Character & u, const bodygraph_part & bgp, const bodygraph_var var) static
Definition at line 1387 of file display.cpp.
 {
     const bodypart_id &bid = bgp.sub_bodyparts.empty() ?
                              bgp.bodyparts.front() : bgp.sub_bodyparts.front()->parent.id();
     return { bgp.sym, display::get_bodygraph_bp_color( u, bid, var ) };
 }
References bodygraph_part::bodyparts, display::get_bodygraph_bp_color(), bodygraph_part::sub_bodyparts, bodygraph_part::sym, and u.
Referenced by display::colorized_bodygraph_text().
get_compass_for_direction()
static std::string get_compass_for_direction (const cardinal_direction dir, int max_width) static
Definition at line 1299 of file display.cpp.
 {
     const int d = static_cast<int>( dir );
     const monster_visible_info &mon_visible = get_avatar().get_mon_visible();
     std::vector<std::pair<std::string, nc_color>> syms;
     for( npc *n : mon_visible.unique_types[d] ) {
         switch( n->get_attitude() ) {
             case NPCATT_KILL:
                 syms.emplace_back( "@", c_red );
                 break;
             case NPCATT_FOLLOW:
                 syms.emplace_back( "@", c_light_green );
                 break;
             default:
                 syms.emplace_back( "@", c_pink );
                 break;
         }
     }
     for( const std::pair<const mtype *, int> &m : mon_visible.unique_mons[d] ) {
         syms.emplace_back( m.first->sym, m.first->color );
     }
     std::string ret;
     for( int i = 0; i < static_cast<int>( syms.size() ); i++ ) {
         if( i >= max_width - 1 ) {
             ret += colorize( "+", c_white );
             break;
         }
         ret += colorize( syms[i].first, syms[i].second );
     }
     return ret;
 }
References c_light_green, c_pink, c_red, c_white, colorize(), get_avatar(), avatar::get_mon_visible(), NPCATT_FOLLOW, NPCATT_KILL, cata::hash64_detail::ret, second, monster_visible_info::unique_mons, and monster_visible_info::unique_types.
Referenced by display::colorized_compass_text().
temp_delta()
static std::pair<bodypart_id, bodypart_id> temp_delta (const Character & u) static
Definition at line 297 of file display.cpp.
 {
     bodypart_id current_bp_extreme = u.get_all_body_parts().front();
     bodypart_id conv_bp_extreme = current_bp_extreme;
     for( const bodypart_id &bp : u.get_all_body_parts() ) {
         if( units::abs( u.get_part_temp_cur( bp ) - BODYTEMP_NORM ) >
             units::abs( u.get_part_temp_cur( current_bp_extreme ) - BODYTEMP_NORM ) ) {
             current_bp_extreme = bp;
         }
         if( units::abs( u.get_part_temp_conv( bp ) - BODYTEMP_NORM ) >
             units::abs( u.get_part_temp_conv( conv_bp_extreme ) - BODYTEMP_NORM ) ) {
             conv_bp_extreme = bp;
         }
     }
     return std::make_pair( current_bp_extreme, conv_bp_extreme );
 }
References units::abs(), BODYTEMP_NORM, bp, and u.
Referenced by display::temp_text_color().
Variable Documentation
disp_bg_cache
std::array<disp_bodygraph_cache, 5> disp_bg_cache static
Initial value:
= { {
        disp_bodygraph_cache( bodygraph_var::hp ),
        disp_bodygraph_cache( bodygraph_var::temp ),
        disp_bodygraph_cache( bodygraph_var::encumb ),
        disp_bodygraph_cache( bodygraph_var::status ),
        disp_bodygraph_cache( bodygraph_var::wet )
    }
}
Definition at line 68 of file display.cpp.
Referenced by display::colorized_bodygraph_text().
disp_om_cache
disp_overmap_cache disp_om_cache static
Definition at line 66 of file display.cpp.
Referenced by display::colorized_overmap_text().
effect_bite
const efftype_id effect_bite("bite") ("bite") static
Referenced by display::limb_color().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by display::limb_color().
effect_got_checked
const efftype_id effect_got_checked("got_checked") ("got_checked") static
Referenced by display::pain_text_color().
effect_hunger_blank
const efftype_id effect_hunger_blank("hunger_blank") ("hunger_blank") static
Referenced by display::hunger_text_color().
effect_hunger_engorged
const efftype_id effect_hunger_engorged("hunger_engorged") ("hunger_engorged") static
Referenced by display::hunger_text_color().
effect_hunger_famished
const efftype_id effect_hunger_famished("hunger_famished") ("hunger_famished") static
Referenced by display::hunger_text_color().
effect_hunger_full
const efftype_id effect_hunger_full("hunger_full") ("hunger_full") static
Referenced by display::hunger_text_color().
effect_hunger_hungry
const efftype_id effect_hunger_hungry("hunger_hungry") ("hunger_hungry") static
Referenced by display::hunger_text_color().
effect_hunger_near_starving
const efftype_id effect_hunger_near_starving("hunger_near_starving") ("hunger_near_starving") static
Referenced by display::hunger_text_color().
effect_hunger_satisfied
const efftype_id effect_hunger_satisfied("hunger_satisfied") ("hunger_satisfied") static
Referenced by display::hunger_text_color().
effect_hunger_starving
const efftype_id effect_hunger_starving("hunger_starving") ("hunger_starving") static
Referenced by display::hunger_text_color().
effect_hunger_very_hungry
const efftype_id effect_hunger_very_hungry("hunger_very_hungry") ("hunger_very_hungry") static
Referenced by display::hunger_text_color().
effect_infected
const efftype_id effect_infected("infected") ("infected") static
Referenced by display::limb_color().
fuel_type_muscle
const itype_id fuel_type_muscle("muscle") ("muscle") static
Referenced by display::vehicle_fuel_percent_text_color().
json_flag_THERMOMETER
const flag_id json_flag_THERMOMETER("THERMOMETER") ("THERMOMETER") static
Referenced by display::get_temp().