Cataclysm DDA: src/do_turn.h File Reference
do_turn.h File Reference
Macros
#define CATA_SRC_DO_TURN_H
Functions
bool do_turn ()
MAIN GAME LOOP.
void handle_key_blocking_activity ()
Macro Definition Documentation
CATA_SRC_DO_TURN_H
#define CATA_SRC_DO_TURN_H
Definition at line 3 of file do_turn.h.
Function Documentation
do_turn()
bool do_turn ()
MAIN GAME LOOP.
Returns true if game is over (death, saved, quit, etc.).
Definition at line 162 of file do_turn.cpp.
 {
     if( g->is_game_over() ) {
         return turn_handler::cleanup_at_end();
     }
     weather_manager &weather = get_weather();
     // Actual stuff
     if( g->new_game ) {
         g->new_game = false;
         if( get_option<std::string>( "ETERNAL_WEATHER" ) != "normal" ) {
             weather.weather_override = static_cast<weather_type_id>
                                        ( get_option<std::string>( "ETERNAL_WEATHER" ) );
             weather.set_nextweather( calendar::turn );
         } else {
             weather.weather_override = WEATHER_NULL;
             weather.set_nextweather( calendar::turn );
         }
     } else {
         g->gamemode->per_turn();
         calendar::turn += 1_turns;
     }
     play_music( music::get_music_id_string() );
     // starting a new turn, clear out temperature cache
     weather.temperature_cache.clear();
     if( g->npcs_dirty ) {
         g->load_npcs();
     }
     timed_event_manager &timed_events = get_timed_events();
     timed_events.process();
     mission::process_all();
     avatar &u = get_avatar();
     map &m = get_map();
     // If controlling a vehicle that is owned by someone else
     if( u.in_vehicle && u.controlling_vehicle ) {
         vehicle *veh = veh_pointer_or_null( m.veh_at( u.pos() ) );
         if( veh && !veh->handle_potential_theft( u, true ) ) {
             veh->handle_potential_theft( u, false, false );
         }
     }
     // Make sure players cant defy gravity by standing still, Looney tunes style.
     u.gravity_check();
     // If you're inside a wall or something and haven't been telefragged, let's get you out.
     if( m.impassable( u.pos() ) && !m.has_flag( ter_furn_flag::TFLAG_CLIMBABLE, u.pos() ) ) {
         u.stagger();
     }
     // If riding a horse - chance to spook
     if( u.is_mounted() ) {
         u.check_mount_is_spooked();
     }
     if( calendar::once_every( 1_days ) ) {
         overmap_buffer.process_mongroups();
     }
     // Move hordes every 2.5 min
     if( calendar::once_every( time_duration::from_minutes( 2.5 ) ) ) {
         if( get_option<bool>( "WANDER_SPAWNS" ) ) {
             overmap_buffer.move_hordes();
         }
         if( u.has_trait( trait_HAS_NEMESIS ) ) {
             overmap_buffer.move_nemesis();
         }
         // Hordes that reached the reality bubble need to spawn,
         // make them spawn in invisible areas only.
         m.spawn_monsters( false );
     }
     g->debug_hour_timer.print_time();
     u.update_body();
     // Auto-save if autosave is enabled
     if( get_option<bool>( "AUTOSAVE" ) &&
         calendar::once_every( 1_turns * get_option<int>( "AUTOSAVE_TURNS" ) ) &&
         !u.is_dead_state() ) {
         g->autosave();
     }
     weather.update_weather();
     g->reset_light_level();
     g->perhaps_add_random_npc( /* ignore_spawn_timers_and_rates = */ false );
     while( u.get_moves() > 0 && u.activity ) {
         u.activity.do_turn( u );
     }
     // FIXME: hack needed due to the legacy code in advanced_inventory::move_all_items()
     if( !u.activity ) {
         kill_advanced_inv();
     }
     // Process NPC sound events before they move or they hear themselves talking
     for( npc &guy : g->all_npcs() ) {
         if( rl_dist( guy.pos(), u.pos() ) < MAX_VIEW_DISTANCE ) {
             sounds::process_sound_markers( &guy );
         }
     }
     music::deactivate_music_id( music::music_id::sound );
     // Process sound events into sound markers for display to the player.
     sounds::process_sound_markers( &u );
     if( u.is_deaf() ) {
         sfx::do_hearing_loss();
     }
     if( !u.has_effect( effect_sleep ) || g->uquit == QUIT_WATCH ) {
         if( u.get_moves() > 0 || g->uquit == QUIT_WATCH ) {
             while( u.get_moves() > 0 || g->uquit == QUIT_WATCH ) {
                 g->cleanup_dead();
                 g->mon_info_update();
                 // Process any new sounds the player caused during their turn.
                 for( npc &guy : g->all_npcs() ) {
                     if( rl_dist( guy.pos(), u.pos() ) < MAX_VIEW_DISTANCE ) {
                         sounds::process_sound_markers( &guy );
                     }
                 }
                 explosion_handler::process_explosions();
                 sounds::process_sound_markers( &u );
                 if( !u.activity && g->uquit != QUIT_WATCH
                     && ( !u.has_distant_destination() || calendar::once_every( 10_seconds ) ) ) {
                     g->wait_popup.reset();
                     ui_manager::redraw();
                 }
                 if( g->queue_screenshot ) {
                     g->take_screenshot();
                     g->queue_screenshot = false;
                 }
                 if( g->handle_action() ) {
                     ++g->moves_since_last_save;
                     u.action_taken();
                 }
                 if( g->is_game_over() ) {
                     return turn_handler::cleanup_at_end();
                 }
                 if( g->uquit == QUIT_WATCH ) {
                     break;
                 }
                 while( u.get_moves() > 0 && u.activity ) {
                     u.activity.do_turn( u );
                 }
             }
             // Reset displayed sound markers now that the turn is over.
             // We only want this to happen if the player had a chance to examine the sounds.
             sounds::reset_markers();
         } else {
             // Rate limit key polling to 10 times a second.
             static auto start = std::chrono::time_point_cast<std::chrono::milliseconds>(
                                     std::chrono::steady_clock::now() );
             const auto now = std::chrono::time_point_cast<std::chrono::milliseconds>(
                                  std::chrono::steady_clock::now() );
             if( ( now - start ).count() > 100 ) {
                 handle_key_blocking_activity();
                 start = now;
             }
             g->mon_info_update();
             // If player is performing a task, a monster is dangerously close,
             // and monster can reach to the player or it has some sort of a ranged attack,
             // warn them regardless of previous safemode warnings
             if( u.activity ) {
                 for( std::pair<const distraction_type, std::string> &dist : u.activity.get_distractions() ) {
                     if( g->cancel_activity_or_ignore_query( dist.first, dist.second ) ) {
                         break;
                     }
                 }
             }
         }
     }
     if( g->driving_view_offset.x != 0 || g->driving_view_offset.y != 0 ) {
         // Still have a view offset, but might not be driving anymore,
         // or the option has been deactivated,
         // might also happen when someone dives from a moving car.
         // or when using the handbrake.
         vehicle *veh = veh_pointer_or_null( m.veh_at( u.pos() ) );
         g->calc_driving_offset( veh );
     }
     scent_map &scent = get_scent();
     // No-scent debug mutation has to be processed here or else it takes time to start working
     if( !u.has_flag( STATIC( json_character_flag( "NO_SCENT" ) ) ) ) {
         scent.set( u.pos(), u.scent, u.get_type_of_scent() );
         overmap_buffer.set_scent( u.global_omt_location(),  u.scent );
     }
     scent.update( u.pos(), m );
     // We need floor cache before checking falling 'n stuff
     m.build_floor_caches();
     m.process_falling();
     m.vehmove();
     m.process_fields();
     m.process_items();
     explosion_handler::process_explosions();
     m.creature_in_field( u );
     // Apply sounds from previous turn to monster and NPC AI.
     sounds::process_sounds();
     const int levz = m.get_abs_sub().z();
     // Update vision caches for monsters. If this turns out to be expensive,
     // consider a stripped down cache just for monsters.
     m.build_map_cache( levz, true );
     monmove();
     if( calendar::once_every( 5_minutes ) ) {
         overmap_npc_move();
     }
     if( calendar::once_every( 10_seconds ) ) {
         for( const tripoint &elem : m.get_furn_field_locations() ) {
             const furn_t &furn = *m.furn( elem );
             for( const emit_id &e : furn.emissions ) {
                 m.emit_field( elem, e );
             }
         }
         for( const tripoint &elem : m.get_ter_field_locations() ) {
             const ter_t &ter = *m.ter( elem );
             for( const emit_id &e : ter.emissions ) {
                 m.emit_field( elem, e );
             }
         }
     }
     g->mon_info_update();
     u.process_turn();
     if( u.get_moves() < 0 && get_option<bool>( "FORCE_REDRAW" ) ) {
         ui_manager::redraw();
         refresh_display();
     }
     if( levz >= 0 && !u.is_underwater() ) {
         handle_weather_effects( weather.weather_id );
     }
     const bool player_is_sleeping = u.has_effect( effect_sleep );
     bool wait_redraw = false;
     std::string wait_message;
     time_duration wait_refresh_rate;
     if( player_is_sleeping ) {
         wait_redraw = true;
         wait_message = _( "Wait till you wake up" );
         wait_refresh_rate = 30_minutes;
     } else if( const std::optional<std::string> progress = u.activity.get_progress_message( u ) ) {
         wait_redraw = true;
         wait_message = *progress;
         if( u.activity.is_interruptible() && u.activity.interruptable_with_kb ) {
             wait_message += string_format( _( "\n%s to interrupt" ), press_x( ACTION_PAUSE ) );
         }
         if( u.activity.id() == ACT_AUTODRIVE ) {
             wait_refresh_rate = 1_turns;
         } else if( u.activity.id() == ACT_FIRSTAID ) {
             wait_refresh_rate = 5_turns;
         } else {
             wait_refresh_rate = 5_minutes;
         }
     }
     if( wait_redraw ) {
         if( g->first_redraw_since_waiting_started ||
             calendar::once_every( std::min( 1_minutes, wait_refresh_rate ) ) ) {
             if( g->first_redraw_since_waiting_started || calendar::once_every( wait_refresh_rate ) ) {
                 ui_manager::redraw();
             }
             // Avoid redrawing the main UI every time due to invalidation
             ui_adaptor dummy( ui_adaptor::disable_uis_below {} );
             g->wait_popup = std::make_unique<static_popup>();
             g->wait_popup->on_top( true ).wait_message( "%s", wait_message );
             ui_manager::redraw();
             refresh_display();
             g->first_redraw_since_waiting_started = false;
         }
     } else {
         // Nothing to wait for now
         g->wait_popup.reset();
         g->first_redraw_since_waiting_started = true;
     }
     m.invalidate_visibility_cache();
     u.update_bodytemp();
     u.update_body_wetness( *weather.weather_precise );
     u.apply_wetness_morale( weather.temperature );
     if( calendar::once_every( 1_minutes ) ) {
         u.update_morale();
         for( npc &guy : g->all_npcs() ) {
             guy.update_morale();
             guy.check_and_recover_morale();
         }
     }
     if( calendar::once_every( 9_turns ) ) {
         u.check_and_recover_morale();
     }
     if( !u.is_deaf() ) {
         sfx::remove_hearing_loss();
     }
     sfx::do_danger_music();
     sfx::do_vehicle_engine_sfx();
     sfx::do_vehicle_exterior_engine_sfx();
     sfx::do_sleepiness();
     // reset player noise
     u.volume = 0;
     // Calculate bionic power balance
     u.power_balance = u.get_power_level() - u.power_prev_turn;
     u.power_prev_turn = u.get_power_level();
 #if defined(EMSCRIPTEN)
     // This will cause a prompt to be shown if the window is closed, until the
     // game is saved.
     EM_ASM( window.game_unsaved = true; );
 #endif
     return false;
 }
References query_yn().
Referenced by main().
handle_key_blocking_activity()
void handle_key_blocking_activity ()
Definition at line 225 of file do_turn.cpp.
 {
     if( test_mode ) {
         return;
     }
     avatar &u = get_avatar();
     const bool has_unfinished_activity = u.activity && (
             u.activity.id()->based_on() == based_on_type::NEITHER
             || u.activity.moves_left > 0 );
     if( has_unfinished_activity || u.has_destination() ) {
         input_context ctxt = get_default_mode_input_context();
         const std::string action = ctxt.handle_input( 0 );
         bool refresh = true;
         if( action == "pause" ) {
             if( u.activity.is_interruptible_with_kb() ) {
                 g->cancel_activity_query( _( "Confirm:" ) );
             }
         } else if( action == "player_data" ) {
             u.disp_info( true );
         } else if( action == "messages" ) {
             Messages::display_messages();
         } else if( action == "help" ) {
             get_help().display_help();
         } else if( action != "HELP_KEYBINDINGS" ) {
             refresh = false;
         }
         if( refresh ) {
             ui_manager::redraw();
             refresh_display();
         }
     } else {
         refresh_display();
         inp_mngr.pump_events();
     }
 }
References _, action, help::display_help(), Messages::display_messages(), g, get_avatar(), get_default_mode_input_context(), get_help(), input_context::handle_input(), inp_mngr, NEITHER, input_manager::pump_events(), ui_manager::redraw(), catacurses::refresh(), refresh_display(), test_mode, and u.
Referenced by game::handle_action(), and map::move_vehicle().