Cataclysm DDA: src/effect_on_condition.cpp File Reference
effect_on_condition.cpp File Reference
#include "effect_on_condition.h"
#include <algorithm>
#include <cstddef>
#include <list>
#include <ostream>
#include <queue>
#include <set>
#include "avatar.h"
#include "calendar.h"
#include "cata_utility.h"
#include "cata_variant.h"
#include "character.h"
#include "character_id.h"
#include "condition.h"
#include "creature.h"
#include "debug.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "game.h"
#include "generic_factory.h"
#include "init.h"
#include "mod_tracker.h"
#include "npc.h"
#include "output.h"
#include "scenario.h"
#include "string_formatter.h"
#include "talker.h"
#include "translations.h"
#include "type_id.h"
Namespaces
io
anonymous_namespace{effect_on_condition.cpp}
Functions
template<>
std::string io::enum_to_string< eoc_type > (eoc_type data)
static time_duration next_recurrence (const effect_on_condition_id &eoc, dialogue &d)
static void process_new_eocs (queued_eocs &eoc_queue, std::vector< effect_on_condition_id > &eoc_vector, std::map< effect_on_condition_id, bool > &new_eocs, bool global_queue)
static void process_eocs (queued_eocs &eoc_queue, std::vector< effect_on_condition_id > &eoc_vector, dialogue &d)
static void process_reactivation (std::vector< effect_on_condition_id > &inactive_effect_on_condition_vector, queued_eocs &queued_effect_on_conditions, dialogue &d)
Variables
generic_factory< effect_on_condition > anonymous_namespace{effect_on_condition.cpp}::effect_on_condition_factory ("effect_on_condition")
Function Documentation
next_recurrence()
static time_duration next_recurrence (const effect_on_condition_id & eoc, dialogue & d) static
Definition at line 135 of file effect_on_condition.cpp.
 {
     return eoc->recurrence.evaluate( d );
 }
References eoc.
Referenced by effect_on_conditions::load_existing_character(), effect_on_conditions::load_new_character(), process_eocs(), and process_reactivation().
process_eocs()
static void process_eocs (queued_eocs & eoc_queue, std::vector< effect_on_condition_id > & eoc_vector, dialogue & d) static
Definition at line 232 of file effect_on_condition.cpp.
 {
     static std::vector<queued_eocs::storage_iter> eocs_to_queue;
     eocs_to_queue.clear();
     while( !eoc_queue.empty() &&
            eoc_queue.top().time <= calendar::turn ) {
         queued_eocs::storage_iter it = eoc_queue.queue.top();
         queued_eoc &top = *it;
         eoc_queue.queue.pop();
         dialogue nested_d{ d };
         for( const auto &val : top.context ) {
             nested_d.set_value( val.first, val.second );
         }
         bool activated = top.eoc->activate( nested_d );
         if( top.eoc->type == eoc_type::RECURRING ) {
             if( activated ) { // It worked so add it back
                 it->time = calendar::turn + next_recurrence( top.eoc, d );
                 eocs_to_queue.emplace_back( it );
             } else {
                 if( !top.eoc->check_deactivate(
                         nested_d ) ) { // It failed but shouldn't be deactivated so add it back
                     it->time = calendar::turn + next_recurrence( top.eoc, d );
                     eocs_to_queue.emplace_back( it );
                 } else { // It failed and should be deactivated for now
                     eoc_vector.push_back( top.eoc );
                     eoc_queue.list.erase( it );
                 }
             }
         } else {
             eoc_queue.list.erase( it );
         }
     }
     for( queued_eocs::storage_iter &q_eoc : eocs_to_queue ) {
         eoc_queue.queue.emplace( q_eoc );
     }
 }
References effect_on_condition::activate(), effect_on_condition::check_deactivate(), queued_eoc::context, queued_eocs::empty(), queued_eoc::eoc, queued_eocs::list, next_recurrence(), queued_eocs::queue, RECURRING, dialogue::set_value(), queued_eoc::time, queued_eocs::top(), calendar::turn, and effect_on_condition::type.
Referenced by effect_on_conditions::process_effect_on_conditions().
process_new_eocs()
static void process_new_eocs (queued_eocs & eoc_queue, std::vector< effect_on_condition_id > & eoc_vector, std::map< effect_on_condition_id, bool > & new_eocs, bool global_queue) static
Definition at line 165 of file effect_on_condition.cpp.
 {
     queued_eocs temp_queued_eocs;
     while( !eoc_queue.empty() ) {
         // Check if EoC is moved from global to local, or vice versa
         if( global_queue == eoc_queue.top().eoc->global ) {
             if( eoc_queue.top().eoc.is_valid() ) {
                 temp_queued_eocs.push( eoc_queue.top() );
             }
             new_eocs[eoc_queue.top().eoc] = false;
         }
         eoc_queue.pop();
     }
     eoc_queue = std::move( temp_queued_eocs );
     for( auto eoc = eoc_vector.begin();
          eoc != eoc_vector.end(); ) {
         // Check if EoC is moved from global to local, or vice versa
         if( !eoc->is_valid() || global_queue != ( *eoc )->global ) {
             eoc = eoc_vector.erase( eoc );
         } else {
             new_eocs[*eoc] = false;
             eoc++;
         }
     }
 }
References queued_eocs::empty(), queued_eoc::eoc, eoc, effect_on_condition::global, string_id< T >::is_valid(), queued_eocs::pop(), queued_eocs::push(), and queued_eocs::top().
Referenced by effect_on_conditions::load_existing_character().
process_reactivation()
static void process_reactivation (std::vector< effect_on_condition_id > & inactive_effect_on_condition_vector, queued_eocs & queued_effect_on_conditions, dialogue & d) static
Definition at line 283 of file effect_on_condition.cpp.
 {
     std::vector<effect_on_condition_id> ids_to_reactivate;
     for( const effect_on_condition_id &eoc : inactive_effect_on_condition_vector ) {
         if( !eoc->check_deactivate( d ) ) {
             ids_to_reactivate.push_back( eoc );
         }
     }
     for( const effect_on_condition_id &eoc : ids_to_reactivate ) {
         queued_effect_on_conditions.push( queued_eoc{ eoc, calendar::turn + next_recurrence( eoc, d ), d.get_context() } );
         inactive_effect_on_condition_vector.erase( std::remove(
                     inactive_effect_on_condition_vector.begin(), inactive_effect_on_condition_vector.end(),
                     eoc ), inactive_effect_on_condition_vector.end() );
     }
 }
References eoc, dialogue::get_context(), next_recurrence(), queued_eocs::push(), and calendar::turn.
Referenced by effect_on_conditions::process_reactivate().