Cataclysm DDA: src/effect.cpp File Reference
effect.cpp File Reference
#include "effect.h"
#include <algorithm>
#include <map>
#include <memory>
#include <optional>
#include <type_traits>
#include <unordered_set>
#include "bodypart.h"
#include "cata_assert.h"
#include "cata_variant.h"
#include "character.h"
#include "color.h"
#include "debug.h"
#include "effect_source.h"
#include "enum_conversions.h"
#include "enums.h"
#include "event.h"
#include "flag.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "generic_factory.h"
#include "json.h"
#include "json_error.h"
#include "magic_enchantment.h"
#include "messages.h"
#include "output.h"
#include "rng.h"
#include "string_formatter.h"
#include "text_snippets.h"
#include "translations.h"
#include "units.h"
Classes
struct desc_freq
Namespaces
anonymous_namespace{effect.cpp}
Functions
void weed_msg (Character &p)
Handles the large variety of weed messages.
static std::optional< game_message_type > process_rating (const std::string &r)
static void load_msg_help (const JsonArray &ja, std::vector< std::pair< translation, game_message_type >> &apply_msgs)
static bool effect_is_blocked (const efftype_id &e, const effects_map &eff_map)
static int cap_to_size (const int max, int attempt)
static vitamin_applied_effect applied_from_rate (const bool reduced, const int intensity, const vitamin_rate_effect &vreff)
void load_effect_type (const JsonObject &jo)
void reset_effect_types ()
const std::map< efftype_id, effect_type > & get_effect_types ()
std::string texitify_base_healing_power (const int power)
std::string texitify_healing_power (const int power)
std::string texitify_bandage_power (const int power)
nc_color colorize_bleeding_intensity (const int intensity)
Variables
static const efftype_id effect_bandaged ("bandaged")
static const efftype_id effect_beartrap ("beartrap")
static const efftype_id effect_crushed ("crushed")
static const efftype_id effect_disinfected ("disinfected")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_grabbed ("grabbed")
static const efftype_id effect_heavysnare ("heavysnare")
static const efftype_id effect_in_pit ("in_pit")
static const efftype_id effect_lightsnare ("lightsnare")
static const efftype_id effect_tied ("tied")
static const efftype_id effect_webbed ("webbed")
static const efftype_id effect_weed_high ("weed_high")
static const efftype_id effect_worked_on ("worked_on")
static const itype_id itype_holybook_bible ("holybook_bible")
static const itype_id itype_money_one ("money_one")
static const trait_id trait_LACTOSE ("LACTOSE")
static const trait_id trait_VEGETARIAN ("VEGETARIAN")
std::array< double, static_cast< size_t > mod_type::MAX)> default_modifier_values = { 0, 0 }
std::map< efftype_id, effect_type > anonymous_namespace{effect.cpp}::effect_types
static std::array< const char *, static_cast< size_t > mod_type::MAX)> MOD_TYPE_STRINGS
static const std::unordered_set< efftype_id > hardcoded_movement_impairing
Function Documentation
applied_from_rate()
static vitamin_applied_effect applied_from_rate (const bool reduced, const int intensity, const vitamin_rate_effect & vreff) static
Definition at line 1113 of file effect.cpp.
 {
     vitamin_applied_effect added;
     added.vitamin = vreff.vitamin;
     if( reduced ) {
         if( !vreff.red_rate.empty() ) {
             const int idx = cap_to_size( vreff.red_rate.size(), intensity );
             added.rate = vreff.red_rate[idx];
         }
         if( !vreff.red_absorb_mult.empty() ) {
             const int idx = cap_to_size( vreff.red_absorb_mult.size(), intensity );
             added.absorb_mult = vreff.red_absorb_mult[idx];
         }
         if( !vreff.red_tick.empty() ) {
             const int idx = cap_to_size( vreff.red_tick.size(), intensity );
             added.tick = vreff.red_tick[idx];
         }
     } else {
         if( !vreff.rate.empty() ) {
             const int idx = cap_to_size( vreff.rate.size(), intensity );
             added.rate = vreff.rate[idx];
         }
         if( !vreff.absorb_mult.empty() ) {
             const int idx = cap_to_size( vreff.absorb_mult.size(), intensity );
             added.absorb_mult = vreff.absorb_mult[idx];
         }
         if( !vreff.tick.empty() ) {
             const int idx = cap_to_size( vreff.tick.size(), intensity );
             added.tick = vreff.tick[idx];
         }
     }
     return added;
 }
References vitamin_rate_effect::absorb_mult, vitamin_applied_effect::absorb_mult, cap_to_size(), intensity, vitamin_rate_effect::rate, vitamin_applied_effect::rate, vitamin_rate_effect::red_absorb_mult, vitamin_rate_effect::red_rate, vitamin_rate_effect::red_tick, vitamin_rate_effect::tick, vitamin_applied_effect::tick, vitamin_rate_effect::vitamin, and vitamin_applied_effect::vitamin.
Referenced by effect::vit_effects().
cap_to_size()
static int cap_to_size (const int max, int attempt) static
Definition at line 1102 of file effect.cpp.
 {
     // Intensities start at 1, indexes at 0
     attempt -= 1;
     if( attempt >= max ) {
         return max - 1;
     } else {
         return attempt;
     }
 }
References max().
Referenced by applied_from_rate(), and effect::kill_roll().
colorize_bleeding_intensity()
nc_color colorize_bleeding_intensity (const int intensity)
Definition at line 1779 of file effect.cpp.
 {
     if( intensity == 0 ) {
         return c_unset;
     } else if( intensity < 11 ) {
         return c_light_red;
     } else if( intensity < 21 ) {
         return c_red;
     } else {
         return c_red_red;
     }
 }
References c_light_red, c_red, c_red_red, c_unset, and intensity.
Referenced by Character::body_window(), draw_health_summary(), and display::limb_color().
effect_is_blocked()
static bool effect_is_blocked (const efftype_id & e, const effects_map & eff_map) static
Definition at line 1023 of file effect.cpp.
 {
     for( const auto &eff_grp : eff_map ) {
         for( const auto &eff : eff_grp.second ) {
             for( const efftype_id &block : eff.second.get_blocks_effects() ) {
                 if( block == e ) {
                     return true;
                 }
             }
         }
     }
     return false;
 }
Referenced by effect::decay().
get_effect_types()
const std::map<efftype_id, effect_type>& get_effect_types ()
Definition at line 1661 of file effect.cpp.
 {
     return effect_types;
 }
References anonymous_namespace{effect.cpp}::effect_types.
Referenced by debug_menu::wisheffect().
load_effect_type()
void load_effect_type (const JsonObject & jo)
Definition at line 1506 of file effect.cpp.
 {
     effect_type new_etype;
     new_etype.id = efftype_id( jo.get_string( "id" ) );
     if( jo.has_member( "name" ) ) {
         for( const JsonValue entry : jo.get_array( "name" ) ) {
             translation name;
             if( !entry.read( name ) ) {
                 entry.throw_error( "Error reading effect names" );
             }
             new_etype.name.emplace_back( name );
         }
     } else {
         new_etype.name.emplace_back();
     }
     jo.read( "speed_name", new_etype.speed_mod_name );
     if( jo.has_member( "desc" ) ) {
         jo.read( "desc", new_etype.desc );
     } else {
         new_etype.desc.emplace_back();
     }
     if( jo.has_member( "reduced_desc" ) ) {
         jo.read( "reduced_desc", new_etype.reduced_desc );
     } else {
         new_etype.reduced_desc = new_etype.desc;
     }
     new_etype.part_descs = jo.get_bool( "part_descs", false );
     jo.read( "remove_message", new_etype.remove_message );
     optional( jo, false, "apply_memorial_log", new_etype.apply_memorial_log,
               text_style_check_reader() );
     optional( jo, false, "remove_memorial_log", new_etype.remove_memorial_log,
               text_style_check_reader() );
     jo.read( "blood_analysis_description", new_etype.blood_analysis_description );
     for( auto &&f : jo.get_string_array( "resist_traits" ) ) { // *NOPAD*
         new_etype.resist_traits.emplace_back( f );
     }
     for( auto &&f : jo.get_string_array( "resist_effects" ) ) { // *NOPAD*
         new_etype.resist_effects.emplace_back( f );
     }
     optional( jo, false, "immune_flags", new_etype.immune_flags );
     optional( jo, false, "immune_bp_flags", new_etype.immune_bp_flags );
     for( auto &&f : jo.get_string_array( "removes_effects" ) ) { // *NOPAD*
         new_etype.removes_effects.emplace_back( f );
     }
     for( auto &&f : jo.get_string_array( "blocks_effects" ) ) { // *NOPAD*
         new_etype.blocks_effects.emplace_back( f );
     }
     optional( jo, false, "max_duration", new_etype.max_duration, 365_days );
     if( jo.has_string( "int_dur_factor" ) ) {
         new_etype.int_dur_factor = read_from_json_string<time_duration>( jo.get_member( "int_dur_factor" ),
                                    time_duration::units );
     } else {
         new_etype.int_dur_factor = time_duration::from_turns( jo.get_int( "int_dur_factor", 0 ) );
     }
     optional( jo, false, "vitamins", new_etype.vitamin_data );
     optional( jo, false, "limb_score_mods", new_etype.limb_score_data );
     optional( jo, false, "effect_dur_scaling", new_etype.effect_dur_scaling );
     optional( jo, false, "chance_kill", new_etype.kill_chance );
     optional( jo, false, "chance_kill_resist", new_etype.red_kill_chance );
     optional( jo, false, "death_msg", new_etype.death_msg, to_translation( "You died." ) );
     optional( jo, false, "death_event", new_etype.death_event,
               enum_flags_reader<event_type>( "event_type" ), std::nullopt );
     new_etype.max_intensity = jo.get_int( "max_intensity", 1 );
     new_etype.dur_add_perc = jo.get_int( "dur_add_perc", 100 );
     new_etype.int_add_val = jo.get_int( "int_add_val", 0 );
     new_etype.int_decay_step = jo.get_int( "int_decay_step", -1 );
     new_etype.int_decay_tick = jo.get_int( "int_decay_tick", 0 );
     optional( jo, false, "int_decay_remove", new_etype.int_decay_remove, false );
     new_etype.load_miss_msgs( jo, "miss_messages" );
     new_etype.load_decay_msgs( jo, "decay_messages" );
     new_etype.load_apply_msgs( jo, "apply_message" );
     new_etype.main_parts_only = jo.get_bool( "main_parts_only", false );
     new_etype.show_in_info = jo.get_bool( "show_in_info", false );
     new_etype.show_intensity = jo.get_bool( "show_intensity", true );
     new_etype.pkill_addict_reduces = jo.get_bool( "pkill_addict_reduces", false );
     new_etype.pain_sizing = jo.get_bool( "pain_sizing", false );
     new_etype.hurt_sizing = jo.get_bool( "hurt_sizing", false );
     new_etype.harmful_cough = jo.get_bool( "harmful_cough", false );
     new_etype.max_effective_intensity = jo.get_int( "max_effective_intensity", 0 );
     new_etype.load_mod_data( jo );
     new_etype.impairs_movement = hardcoded_movement_impairing.count( new_etype.id ) > 0;
     new_etype.flags = jo.get_tags<flag_id>( "flags" );
     int enchant_num = 0;
     for( JsonValue jv : jo.get_array( "enchantments" ) ) {
         std::string enchant_name = "INLINE_ENCH_" + new_etype.id.str() + "_" + std::to_string(
                                        enchant_num++ );
         new_etype.enchantments.push_back( enchantment::load_inline_enchantment( jv, "", enchant_name ) );
     }
     effect_types[new_etype.id] = new_etype;
 }
Referenced by DynamicDataLoader::initialize().
load_msg_help()
static void load_msg_help (const JsonArray & ja, std::vector< std::pair< translation, game_message_type >> & apply_msgs) static
Definition at line 717 of file effect.cpp.
 {
     translation msg;
     ja.read( 0, msg );
     std::string r = ja.get_string( 1 );
     std::optional<game_message_type> rate = process_rating( r );
     if( !rate.has_value() ) {
         ja.throw_error(
             1, string_format( "Unexpected message type \"%s\"; expected \"good\", "
                               "\"neutral\", " "\"bad\", or \"mixed\"", r ) );
         rate = m_neutral;
     }
     apply_msgs.emplace_back( msg, rate.value() );
 }
References JsonArray::get_string(), m_neutral, process_rating(), JsonArray::read(), string_format(), and JsonArray::throw_error().
Referenced by effect_type::load_apply_msgs(), and effect_type::load_decay_msgs().
process_rating()
static std::optional<game_message_type> process_rating (const std::string & r) static
Definition at line 700 of file effect.cpp.
 {
     if( r == "good" ) {
         return m_good;
     } else if( r == "neutral" ) {
         return m_neutral;
     } else if( r == "bad" ) {
         return m_bad;
     } else if( r == "mixed" ) {
         return m_mixed;
     } else {
         // handle errors for returning nothing above
         return {};
     }
 }
References m_bad, m_good, m_mixed, and m_neutral.
Referenced by effect_type::load_apply_msgs(), and load_msg_help().
reset_effect_types()
void reset_effect_types ()
Definition at line 1656 of file effect.cpp.
 {
     effect_types.clear();
 }
References anonymous_namespace{effect.cpp}::effect_types.
Referenced by DynamicDataLoader::unload_data().
texitify_bandage_power()
std::string texitify_bandage_power (const int power)
Definition at line 1760 of file effect.cpp.
 {
     if( power < 5 ) {
         return colorize( _( "minuscule" ), c_red );
     } else if( power < 10 ) {
         return colorize( _( "small" ), c_light_red );
     } else if( power < 15 ) {
         return colorize( _( "moderate" ), c_yellow );
     } else if( power < 20 ) {
         return colorize( _( "good" ), c_light_green );
     } else if( power < 30 ) {
         return colorize( _( "excellent" ), c_light_green );
     } else if( power < 51 ) {
         return colorize( _( "outstanding" ), c_green );
     } else {
         debugmsg( "Converted value out of bounds." );
     }
     return "";
 }
References _, c_green, c_light_green, c_light_red, c_red, c_yellow, colorize(), and debugmsg.
Referenced by heal_actor::info().
texitify_base_healing_power()
std::string texitify_base_healing_power (const int power)
Definition at line 1715 of file effect.cpp.
 {
     if( power == 1 ) {
         return colorize( _( "very poor" ), c_red );
     } else if( power == 2 ) {
         return colorize( _( "poor" ), c_light_red );
     } else if( power == 3 ) {
         return colorize( _( "average" ), c_yellow );
     } else if( power == 4 ) {
         return colorize( _( "good" ), c_light_green );
     } else if( power >= 5 ) {
         return colorize( _( "great" ), c_green );
     }
     if( power < 1 ) {
         debugmsg( "Tried to convert zero or negative value." );
     }
     return "";
 }
References _, c_green, c_light_green, c_light_red, c_red, c_yellow, colorize(), and debugmsg.
Referenced by heal_actor::info().
texitify_healing_power()
std::string texitify_healing_power (const int power)
Definition at line 1734 of file effect.cpp.
 {
     if( power == 0 ) {
         return colorize( _( "none" ), c_dark_gray );
     } else if( power >= 1 && power <= 2 ) {
         return colorize( _( "very poor" ), c_red );
     } else if( power >= 3 && power <= 4 ) {
         return colorize( _( "poor" ), c_light_red );
     } else if( power >= 5 && power <= 6 ) {
         return colorize( _( "average" ), c_yellow );
     } else if( power >= 7 && power <= 8 ) {
         return colorize( _( "good" ), c_yellow );
     } else if( power >= 9 && power <= 10 ) {
         return colorize( _( "very good" ), c_light_green );
     } else if( power >= 11 && power <= 12 ) {
         return colorize( _( "great" ), c_light_green );
     } else if( power >= 13 && power <= 14 ) {
         return colorize( _( "outstanding" ), c_green );
     } else if( power >= 15 ) {
         return colorize( _( "perfect" ), c_green );
     }
     if( power < 0 ) {
         debugmsg( "Converted value out of bounds." );
     }
     return "";
 }
References _, c_dark_gray, c_green, c_light_green, c_light_red, c_red, c_yellow, colorize(), and debugmsg.
Referenced by Character::body_window(), effect::disp_name(), and heal_actor::info().
weed_msg()
void weed_msg (Character & p)
Handles the large variety of weed messages.
Intelligence changes messages when smoking weed
Definition at line 129 of file effect.cpp.
 {
     const time_duration howhigh = p.get_effect_dur( effect_weed_high );
     ///\EFFECT_INT changes messages when smoking weed
     int smarts = p.get_int();
     if( howhigh > 12_minutes && one_in( 7 ) ) {
         int msg = rng( 0, 5 );
         switch( msg ) {
             case 0:
                 p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Freakazoid_1" ).value_or(
                                          translation() ) );
                 return;
             case 1:
                 p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Simpsons_1" ).value_or(
                                          translation() ) );
                 p.mod_hunger( 2 );
                 return;
             case 2:
                 if( smarts > 8 ) {
                     p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Timothy_Leary" ).value_or(
                                              translation() ) );
                 } else if( smarts < 3 ) {
                     p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_IASIF" ).value_or( translation() ) );
                 } else {
                     p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Durr" ).value_or( translation() ) );
                 }
                 return;
             case 3:
                 p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Dazed_and_Confused_1" ).value_or(
                                          translation() ) );
                 if( one_in( 2 ) ) {
                     p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Dazed_and_Confused_2" ).value_or(
                                              translation() ) );
                     if( one_in( 2 ) ) {
                         p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Dazed_and_Confused_3" ).value_or(
                                                  translation() ) );
                     }
                 }
                 return;
             case 4:
                 if( p.has_amount( itype_money_one, 1 ) ) { // Half Baked
                     p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Half_Baked_1" ).value_or(
                                              translation() ) );
                     if( one_in( 2 ) ) {
                         p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Half_Baked_2" ).value_or(
                                                  translation() ) );
                         if( one_in( 3 ) ) {
                             p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Half_Baked_3" ).value_or(
                                                      translation() ) );
                         }
                     }
                 } else if( p.has_amount( itype_holybook_bible, 1 ) ) {
                     p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Bible" ).value_or( translation() ) );
                 } else {
                     p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Big_Lebowski" ).value_or(
                                              translation() ) );
                 }
                 return;
             case 5:
                 p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Mitch_Hedberg" ).value_or(
                                          translation() ) );
             default:
                 return;
         }
     } else if( howhigh > 10_minutes && one_in( 5 ) ) {
         int msg = rng( 0, 5 );
         switch( msg ) {
             case 0:
                 p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Bob_Marley" ).value_or(
                                          translation() ) );
                 return;
             case 1:
                 p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Freakazoid_2" ).value_or(
                                          translation() ) );
                 return;
             case 2:
                 p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Simpsons_2" ).value_or(
                                          translation() ) );
                 if( smarts > 2 && one_in( 2 ) ) {
                     p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Simpsons_3" ).value_or(
                                              translation() ) );
                 }
                 return;
             case 3:
                 p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Bill_Hicks" ).value_or(
                                          translation() ) );
                 return;
             case 4:
                 p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Steve_Martin_1" ).value_or(
                                          translation() ) );
                 if( one_in( 4 ) ) {
                     p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Steve_Martin_2" ).value_or(
                                              translation() ) );
                 }
                 if( one_in( 4 ) ) {
                     p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Steve_Martin_3" ).value_or(
                                              translation() ) );
                 }
                 if( one_in( 4 ) ) {
                     p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Steve_Martin_4" ).value_or(
                                              translation() ) );
                 }
                 if( one_in( 4 ) ) {
                     p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Steve_Martin_5" ).value_or(
                                              translation() ) );
                 }
                 if( smarts > 2 ) {
                     p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Steve_Martin_6" ).value_or(
                                              translation() ) );
                 }
                 return;
             case 5:
             default:
                 return;
         }
     } else if( howhigh > 5_minutes && one_in( 3 ) ) {
         int msg = rng( 0, 5 );
         switch( msg ) {
             case 0:
                 p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Cheech_and_Chong" ).value_or(
                                          translation() ) );
                 return;
             case 1:
                 p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Real_Life_1" ).value_or(
                                          translation() ) );
                 p.mod_hunger( 4 );
                 if( p.has_trait( trait_VEGETARIAN ) ) {
                     p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Real_Life_2" ).value_or(
                                              translation() ) );
                 } else if( p.has_trait( trait_LACTOSE ) ) {
                     p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Real_Life_3" ).value_or(
                                              translation() ) );
                 }
                 return;
             case 2:
                 p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Dazed_and_Confused_4" ).value_or(
                                          translation() ) );
                 return;
             case 3:
                 p.add_msg_if_player( "%s", SNIPPET.random_from_category( "weed_Half_Baked_4" ).value_or(
                                          translation() ) );
                 return;
             case 4:
                 // re-roll
                 weed_msg( p );
             case 5:
             default:
                 return;
         }
     }
 }
References Character::add_msg_if_player(), effect_weed_high, Creature::get_effect_dur(), Character::get_int(), visitable::has_amount(), Character::has_trait(), itype_holybook_bible, itype_money_one, Character::mod_hunger(), one_in(), snippet_library::random_from_category(), rng(), SNIPPET, trait_LACTOSE, and trait_VEGETARIAN.
Referenced by item::process_litcig(), iuse::smoking(), and iuse::weed_cake().
Variable Documentation
default_modifier_values
std::array<double, static_cast<size_t> mod_type::MAX)> default_modifier_values = { 0, 0 }
Definition at line 55 of file effect.cpp.
Referenced by effect_type::extract_effect().
effect_bandaged
const efftype_id effect_bandaged("bandaged") ("bandaged") static
Referenced by effect::disp_name().
effect_beartrap
const efftype_id effect_beartrap("beartrap") ("beartrap") static
effect_crushed
const efftype_id effect_crushed("crushed") ("crushed") static
effect_disinfected
const efftype_id effect_disinfected("disinfected") ("disinfected") static
Referenced by effect::disp_name().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
effect_grabbed
const efftype_id effect_grabbed("grabbed") ("grabbed") static
effect_heavysnare
const efftype_id effect_heavysnare("heavysnare") ("heavysnare") static
effect_in_pit
const efftype_id effect_in_pit("in_pit") ("in_pit") static
effect_lightsnare
const efftype_id effect_lightsnare("lightsnare") ("lightsnare") static
effect_tied
const efftype_id effect_tied("tied") ("tied") static
effect_webbed
const efftype_id effect_webbed("webbed") ("webbed") static
effect_weed_high
const efftype_id effect_weed_high("weed_high") ("weed_high") static
Referenced by weed_msg().
effect_worked_on
const efftype_id effect_worked_on("worked_on") ("worked_on") static
hardcoded_movement_impairing
const std::unordered_set<efftype_id> hardcoded_movement_impairing static
Initial value:
= {{
        effect_beartrap,
        effect_crushed,
        effect_downed,
        effect_grabbed,
        effect_heavysnare,
        effect_in_pit,
        effect_lightsnare,
        effect_tied,
        effect_webbed,
        effect_worked_on,
    }
}
Definition at line 1492 of file effect.cpp.
itype_holybook_bible
const itype_id itype_holybook_bible("holybook_bible") ("holybook_bible") static
Referenced by weed_msg().
itype_money_one
const itype_id itype_money_one("money_one") ("money_one") static
Referenced by weed_msg().
MOD_TYPE_STRINGS
std::array<const char *, static_cast<size_t> mod_type::MAX)> MOD_TYPE_STRINGS static
Initial value:
{
    "base_mods",
    "scaling_mods",
}
Definition at line 281 of file effect.cpp.
Referenced by effect_type::load_mod_data().
trait_LACTOSE
const trait_id trait_LACTOSE("LACTOSE") ("LACTOSE") static
Referenced by weed_msg().
trait_VEGETARIAN
const trait_id trait_VEGETARIAN("VEGETARIAN") ("VEGETARIAN") static
Referenced by weed_msg().