Cataclysm DDA: src/enums.h File Reference
enums.h File Reference
#include <type_traits>
Classes
struct enum_traits< aim_exit >
struct enum_traits< aim_entry >
struct enum_traits< bionic_ui_sort_mode >
struct enum_traits< holiday >
struct enum_traits< ot_match_type >
struct enum_traits< art_effect_passive >
struct enum_traits< phase_id >
struct enum_traits< layer_level >
struct enum_traits< distraction_type >
struct enum_traits< game_message_type >
struct game_message_params
Structure allowing a combination of game_message_type and game_message_flags.
struct social_modifiers
struct enum_traits< reachability_cache_quadrant >
struct enum_traits< aggregate_type >
struct enum_traits< link_state >
Macros
#define CATA_SRC_ENUMS_H
Typedefs
using I = std::underlying_type_t< aim_entry >
Enumerations
enum class aim_exit : int { none = 0 , okay , re_entry , last }
enum class aim_entry : int {
START = 0 , VEHICLE = 1 , MAP = 2 , RESET = 3 ,
last
}
enum class bionic_ui_sort_mode : int {
NONE = 0 , POWER = 1 , NAME = 2 , INVLET = 3 ,
nsort = 4
}
enum class trinary : int { NONE = 0 , SOME = 1 , ALL = 2 }
enum class holiday : int {
none = 0 , new_year , easter , independence_day ,
halloween , thanksgiving , christmas , num_holiday
}
enum class temperature_flag : int {
NORMAL = 0 , HEATER , FRIDGE , FREEZER ,
ROOT_CELLAR
}
enum class rule_state : int { NONE , WHITELISTED , BLACKLISTED }
enum class visibility_type : int {
HIDDEN , CLEAR , LIT , BOOMER ,
DARK , BOOMER_DARK
}
enum class ot_match_type : int {
exact , type , subtype , prefix ,
contains , num_ot_match_type
}
enum class special_game_type : int { NONE = 0 , TUTORIAL , NUM_SPECIAL_GAME_TYPES }
enum art_effect_passive : int {
AEP_NULL = 0 , AEP_STR_UP , AEP_DEX_UP , AEP_PER_UP ,
AEP_INT_UP , AEP_ALL_UP , AEP_SPEED_UP , AEP_PBLUE ,
AEP_SNAKES , AEP_INVISIBLE , AEP_CLAIRVOYANCE , AEP_SUPER_CLAIRVOYANCE ,
AEP_STEALTH , AEP_EXTINGUISH , AEP_GLOW , AEP_PSYSHIELD ,
AEP_RESIST_ELECTRICITY , AEP_CARRY_MORE , AEP_SAP_LIFE , AEP_FUN ,
AEP_SPLIT , AEP_HUNGER , AEP_THIRST , AEP_SMOKE ,
AEP_EVIL , AEP_SCHIZO , AEP_RADIOACTIVE , AEP_MUTAGENIC ,
AEP_ATTENTION , AEP_STR_DOWN , AEP_DEX_DOWN , AEP_PER_DOWN ,
AEP_INT_DOWN , AEP_ALL_DOWN , AEP_SPEED_DOWN , AEP_FORCE_TELEPORT ,
AEP_MOVEMENT_NOISE , AEP_BAD_WEATHER , AEP_SICK , AEP_CLAIRVOYANCE_PLUS ,
NUM_AEPS
}
enum artifact_natural_property {
ARTPROP_NULL , ARTPROP_WRIGGLING , ARTPROP_GLOWING , ARTPROP_HUMMING ,
ARTPROP_MOVING , ARTPROP_WHISPERING , ARTPROP_BREATHING , ARTPROP_DEAD ,
ARTPROP_ITCHY , ARTPROP_GLITTERING , ARTPROP_ELECTRIC , ARTPROP_SLIMY ,
ARTPROP_ENGRAVED , ARTPROP_CRACKLING , ARTPROP_WARM , ARTPROP_RATTLING ,
ARTPROP_SCALED , ARTPROP_FRACTAL , ARTPROP_MAX
}
enum class phase_id : int {
PNULL , SOLID , LIQUID , GAS ,
PLASMA , num_phases
}
enum class object_type : int {
NONE , ITEM , ACTOR , PLAYER ,
NPC , MONSTER , VEHICLE , TRAP ,
FIELD , TERRAIN , FURNITURE , NUM_OBJECT_TYPES
}
enum class liquid_source_type : int { INFINITE_MAP = 1 , MAP_ITEM = 2 , VEHICLE = 3 , MONSTER = 4 }
enum class liquid_target_type : int { CONTAINER = 1 , VEHICLE = 2 , MAP = 3 , MONSTER = 4 }
enum class layer_level : int {
PERSONAL = 0 , SKINTIGHT , NORMAL , WAIST ,
OUTER , BELTED , AURA , NUM_LAYER_LEVELS
}
Possible layers that a piece of clothing/armor can occupy.
enum class distraction_type : int {
noise , pain , attacked , hostile_spotted_far ,
hostile_spotted_near , talked_to , asthma , motion_alarm ,
weather_change , portal_storm_popup , eoc , dangerous_field ,
hunger , thirst , temperature , mutation ,
oxygen , last
}
Possible reasons to interrupt an activity.
enum game_message_type : int {
m_good , m_bad , m_mixed , m_warning ,
m_info , m_neutral , m_debug , m_headshot ,
m_critical , m_grazing , num_game_message_type
}
enum game_message_flags { gmf_none = 0 , gmf_bypass_cooldown = 1 }
enum MULTITILE_TYPE {
center , corner , edge , t_connection ,
end_piece , unconnected , open_ , broken ,
num_multitile_types
}
enum class reachability_cache_quadrant : int { NE , SE , NW , SW }
enum class monotonically : int { constant , increasing , decreasing , unknown }
enum class character_type : int {
CUSTOM , RANDOM , TEMPLATE , NOW ,
FULL_RANDOM
}
enum class aggregate_type : int {
FIRST , LAST , MIN , MAX ,
SUM , AVERAGE , num_aggregate_types
}
enum class link_state : int {
no_link = 0 , needs_reeling , ups , solarpack ,
vehicle_port , vehicle_battery , bio_cable , vehicle_tow ,
automatic , last
}
Functions
template<typename T >
constexpr int sgn (const T x)
constexpr aim_entry & operator++ (aim_entry &lhs)
constexpr aim_entry & operator-- (aim_entry &lhs)
constexpr aim_entry operator+ (const aim_entry &lhs, const I &rhs)
constexpr aim_entry operator- (const aim_entry &lhs, const I &rhs)
layer_level & operator++ (layer_level &l)
constexpr bool is_increasing (monotonically m)
constexpr bool is_decreasing (monotonically m)
Macro Definition Documentation
CATA_SRC_ENUMS_H
#define CATA_SRC_ENUMS_H
Definition at line 3 of file enums.h.
Typedef Documentation
I
using I = std::underlying_type_t<aim_entry>
Definition at line 41 of file enums.h.
Enumeration Type Documentation
aggregate_type
enum aggregate_type : int strong
Enumerator
FIRST
LAST
MIN
MAX
SUM
AVERAGE
num_aggregate_types
Definition at line 462 of file enums.h.
                           : int {
     FIRST,
     LAST,
     MIN,
     MAX,
     SUM,
     AVERAGE,
     num_aggregate_types
 };
aim_entry
enum aim_entry : int strong
Enumerator
START
VEHICLE
MAP
RESET
last
Definition at line 28 of file enums.h.
                      : int {
     START     = 0,
     VEHICLE   = 1,
     MAP       = 2,
     RESET     = 3,
     last
 };
aim_exit
enum aim_exit : int strong
Enumerator
none
okay
re_entry
last
Definition at line 15 of file enums.h.
                     : int {
     none = 0,
     okay,
     re_entry,
     last
 };
art_effect_passive
enum art_effect_passive : int
Enumerator
AEP_NULL
AEP_STR_UP
AEP_DEX_UP
AEP_PER_UP
AEP_INT_UP
AEP_ALL_UP
AEP_SPEED_UP
AEP_PBLUE
AEP_SNAKES
AEP_INVISIBLE
AEP_CLAIRVOYANCE
AEP_SUPER_CLAIRVOYANCE
AEP_STEALTH
AEP_EXTINGUISH
AEP_GLOW
AEP_PSYSHIELD
AEP_RESIST_ELECTRICITY
AEP_CARRY_MORE
AEP_SAP_LIFE
AEP_FUN
AEP_SPLIT
AEP_HUNGER
AEP_THIRST
AEP_SMOKE
AEP_EVIL
AEP_SCHIZO
AEP_RADIOACTIVE
AEP_MUTAGENIC
AEP_ATTENTION
AEP_STR_DOWN
AEP_DEX_DOWN
AEP_PER_DOWN
AEP_INT_DOWN
AEP_ALL_DOWN
AEP_SPEED_DOWN
AEP_FORCE_TELEPORT
AEP_MOVEMENT_NOISE
AEP_BAD_WEATHER
AEP_SICK
AEP_CLAIRVOYANCE_PLUS
NUM_AEPS
Definition at line 159 of file enums.h.
                         : int {
     AEP_NULL = 0,
     // Good
     AEP_STR_UP, // Strength + 4
     AEP_DEX_UP, // Dexterity + 4
     AEP_PER_UP, // Perception + 4
     AEP_INT_UP, // Intelligence + 4
     AEP_ALL_UP, // All stats + 2
     AEP_SPEED_UP, // +20 speed
     AEP_PBLUE, // Reduces radiation
     AEP_SNAKES, // Summons friendly snakes when you're hit
     AEP_INVISIBLE, // Makes you invisible
     AEP_CLAIRVOYANCE, // See through walls
     AEP_SUPER_CLAIRVOYANCE, // See through walls to a great distance
     AEP_STEALTH, // Your steps are quieted
     AEP_EXTINGUISH, // May extinguish nearby flames
     AEP_GLOW, // Four-tile light source
     AEP_PSYSHIELD, // Protection from fear paralyze attack
     AEP_RESIST_ELECTRICITY, // Protection from electricity
     AEP_CARRY_MORE, // Increases carrying capacity by 200
     AEP_SAP_LIFE, // Killing non-zombie monsters may heal you
     AEP_FUN, // Slight passive morale
     // Splits good from bad
     AEP_SPLIT,
     // Bad
     AEP_HUNGER, // Increases hunger
     AEP_THIRST, // Increases thirst
     AEP_SMOKE, // Emits smoke occasionally
     AEP_EVIL, // Addiction to the power
     AEP_SCHIZO, // Mimicks schizophrenia
     AEP_RADIOACTIVE, // Increases your radiation
     AEP_MUTAGENIC, // Mutates you slowly
     AEP_ATTENTION, // Draws netherworld attention slowly
     AEP_STR_DOWN, // Strength - 3
     AEP_DEX_DOWN, // Dex - 3
     AEP_PER_DOWN, // Per - 3
     AEP_INT_DOWN, // Int - 3
     AEP_ALL_DOWN, // All stats - 2
     AEP_SPEED_DOWN, // -20 speed
     AEP_FORCE_TELEPORT, // Occasionally force a teleport
     AEP_MOVEMENT_NOISE, // Makes noise when you move
     AEP_BAD_WEATHER, // More likely to experience bad weather
     AEP_SICK, // Decreases health over time
     AEP_CLAIRVOYANCE_PLUS, // See through walls to a larger distance; not bad effect, placement to preserve old saves.
     NUM_AEPS
 };
artifact_natural_property
enum artifact_natural_property
Enumerator
ARTPROP_NULL
ARTPROP_WRIGGLING
ARTPROP_GLOWING
ARTPROP_HUMMING
ARTPROP_MOVING
ARTPROP_WHISPERING
ARTPROP_BREATHING
ARTPROP_DEAD
ARTPROP_ITCHY
ARTPROP_GLITTERING
ARTPROP_ELECTRIC
ARTPROP_SLIMY
ARTPROP_ENGRAVED
ARTPROP_CRACKLING
ARTPROP_WARM
ARTPROP_RATTLING
ARTPROP_SCALED
ARTPROP_FRACTAL
ARTPROP_MAX
Definition at line 212 of file enums.h.
{
     ARTPROP_NULL,
     ARTPROP_WRIGGLING, //
     ARTPROP_GLOWING, //
     ARTPROP_HUMMING, //
     ARTPROP_MOVING, //
     ARTPROP_WHISPERING, //
     ARTPROP_BREATHING, //
     ARTPROP_DEAD, //
     ARTPROP_ITCHY, //
     ARTPROP_GLITTERING, //
     ARTPROP_ELECTRIC, //
     ARTPROP_SLIMY, //
     ARTPROP_ENGRAVED, //
     ARTPROP_CRACKLING, //
     ARTPROP_WARM, //
     ARTPROP_RATTLING, //
     ARTPROP_SCALED,
     ARTPROP_FRACTAL,
     ARTPROP_MAX
 };
bionic_ui_sort_mode
enum bionic_ui_sort_mode : int strong
Enumerator
NONE
POWER
NAME
INVLET
nsort
Definition at line 64 of file enums.h.
                                : int {
     NONE   = 0,
     POWER  = 1,
     NAME   = 2,
     INVLET = 3,
     nsort  = 4,
 };
character_type
enum character_type : int strong
Enumerator
CUSTOM
RANDOM
TEMPLATE
NOW
FULL_RANDOM
Definition at line 454 of file enums.h.
                           : int {
     CUSTOM,
     RANDOM,
     TEMPLATE,
     NOW,
     FULL_RANDOM,
 };
distraction_type
enum distraction_type : int strong
Possible reasons to interrupt an activity.
Enumerator
noise
pain
attacked
hostile_spotted_far
hostile_spotted_near
talked_to
asthma
motion_alarm
weather_change
portal_storm_popup
eoc
dangerous_field
hunger
thirst
temperature
mutation
oxygen
last
Definition at line 320 of file enums.h.
                             : int {
     noise,
     pain,
     attacked,
     hostile_spotted_far,
     hostile_spotted_near,
     talked_to,
     asthma,
     motion_alarm,
     weather_change,
     portal_storm_popup,
     eoc,
     dangerous_field,
     hunger,
     thirst,
     temperature,
     mutation,
     oxygen,
     last,
 };
game_message_flags
enum game_message_flags
Enumerator
gmf_none
gmf_bypass_cooldown
Definition at line 371 of file enums.h.
{
     /* No specific game message flags */
     gmf_none = 0,
     /* Allow the message to bypass message cooldown. */
     gmf_bypass_cooldown = 1,
 };
game_message_type
enum game_message_type : int
Enumerator
m_good
m_bad
m_mixed
m_warning
m_info
m_neutral
m_debug
m_headshot
m_critical
m_grazing
num_game_message_type
Definition at line 346 of file enums.h.
                        : int {
     m_good,    /* something good happened to the player character, e.g. health boost, increasing in skill */
     m_bad,      /* something bad happened to the player character, e.g. damage, decreasing in skill */
     m_mixed,   /* something happened to the player character which is mixed (has good and bad parts),
                   e.g. gaining a mutation with mixed effect*/
     m_warning, /* warns the player about a danger. e.g. enemy appeared, an alarm sounds, noise heard. */
     m_info,    /* informs the player about something, e.g. on examination, seeing an item,
                   about how to use a certain function, etc. */
     m_neutral,  /* neutral or indifferent events which aren't informational or nothing really happened e.g.
                   a miss, a non-critical failure. May also effect for good or bad effects which are
                   just very slight to be notable. This is the default message type. */
     m_debug, /* only shown when debug_mode is true */
     /* custom SCT colors */
     m_headshot,
     m_critical,
     m_grazing,
     num_game_message_type
 };
holiday
enum holiday : int strong
Enumerator
none
new_year
easter
independence_day
halloween
thanksgiving
christmas
num_holiday
Definition at line 84 of file enums.h.
                    : int {
     none = 0,
     new_year,
     easter,
     independence_day,
     halloween,
     thanksgiving,
     christmas,
     num_holiday
 };
layer_level
enum layer_level : int strong
Possible layers that a piece of clothing/armor can occupy.
Every piece of clothing occupies one distinct layer on the body-part that it covers. This is used for example by Character to calculate encumbrance values, player to calculate time to wear/remove the item, and by profession to place the characters' clothing in a sane order when starting the game.
Enumerator
PERSONAL
SKINTIGHT
NORMAL
WAIST
OUTER
BELTED
AURA
NUM_LAYER_LEVELS
Definition at line 289 of file enums.h.
                        : int {
     /* "Personal effects" layer, corresponds to PERSONAL flag */
     PERSONAL = 0,
     /* "Close to skin" layer, corresponds to SKINTIGHT flag. */
     SKINTIGHT,
     /* "Normal" layer, default if no flags set, also if NORMAL flag is used*/
     NORMAL,
     /* "Waist" layer, corresponds to WAIST flag. */
     WAIST,
     /* "Outer" layer, corresponds to OUTER flag. */
     OUTER,
     /* "Strapped" layer, corresponds to BELTED flag */
     BELTED,
     /* "Aura" layer, corresponds to AURA flag */
     AURA,
     /* Not a valid layer; used for C-style iteration through this enum */
     NUM_LAYER_LEVELS
 };
link_state
enum link_state : int strong
Enumerator
no_link
needs_reeling
ups
solarpack
vehicle_port
vehicle_battery
bio_cable
vehicle_tow
automatic
last
Definition at line 477 of file enums.h.
                       : int {
     no_link = 0,     // No connection, the default state
     needs_reeling,   // Cable has been disconnected and needs to be manually reeled in before it can be used again
     ups,             // Linked to a UPS the cable holder is holding
     solarpack,       // Linked to a solarpack the cable holder is wearing
     vehicle_port,    // Linked to a vehicle's cable ports / electrical controls or an appliance
     vehicle_battery, // Linked to a vehicle's battery or an appliance
     bio_cable,       // Linked to the cable holder's cable system bionic - source if connected to a vehicle, target otherwise
     vehicle_tow,     // Linked to a valid tow point on a vehicle - source if it's the towing vehicle, target if the towed one
     automatic,       // Use in link_to() to automatically set the type of connection based on the connected vehicle part. Is always true as a link_has_states() parameter.
     last
 };
liquid_source_type
enum liquid_source_type : int strong
Enumerator
INFINITE_MAP
MAP_ITEM
VEHICLE
MONSTER
Definition at line 266 of file enums.h.
                               : int {
     INFINITE_MAP = 1,
     MAP_ITEM = 2,
     VEHICLE = 3,
     MONSTER = 4
 };
liquid_target_type
enum liquid_target_type : int strong
Enumerator
CONTAINER
VEHICLE
MAP
MONSTER
Definition at line 273 of file enums.h.
                               : int {
     CONTAINER = 1,
     VEHICLE = 2,
     MAP = 3,
     MONSTER = 4
 };
monotonically
enum monotonically : int strong
Enumerator
constant
increasing
decreasing
unknown
Definition at line 437 of file enums.h.
                          : int {
     constant,
     increasing,
     decreasing,
     unknown,
 };
MULTITILE_TYPE
enum MULTITILE_TYPE
Enumerator
center
corner
edge
t_connection
end_piece
unconnected
open_
broken
num_multitile_types
Definition at line 409 of file enums.h.
                     {
     center,
     corner,
     edge,
     t_connection,
     end_piece,
     unconnected,
     open_,
     broken,
     num_multitile_types
 };
object_type
enum object_type : int strong
Enumerator
NONE
ITEM
ACTOR
PLAYER
NPC
MONSTER
VEHICLE
TRAP
FIELD
TERRAIN
FURNITURE
NUM_OBJECT_TYPES
Definition at line 251 of file enums.h.
                        : int {
     NONE,      // Nothing, invalid.
     ITEM,      // item.h
     ACTOR,     // potential virtual base class, get_object_type() would return one of the types below
     PLAYER,  // player.h, npc.h
     NPC,   // nph.h
     MONSTER, // monster.h
     VEHICLE,   // vehicle.h
     TRAP,      // trap.h
     FIELD,     // field.h; field_entry
     TERRAIN,   // Not a real object
     FURNITURE, // Not a real object
     NUM_OBJECT_TYPES,
 };
ot_match_type
enum ot_match_type : int strong
Enumerator
exact
type
subtype
prefix
contains
num_ot_match_type
Definition at line 125 of file enums.h.
                          : int {
     // The provided string must completely match the overmap terrain id, including
     // linear direction suffixes for linear terrain types or rotation suffixes
     // for rotated terrain types.
     exact,
     // The provided string must completely match the base type id of the overmap
     // terrain id, which means that suffixes for rotation and linear terrain types
     // are ignored.
     type,
     // The provided string must completely match the base type id of the overmap
     // terrain id as well as the linear subtype.
     subtype,
     // The provided string must be a complete prefix (with additional parts delimited
     // by an underscore) of the overmap terrain id. For example, "forest" will match
     // "forest" or "forest_thick" but not "forestcabin".
     prefix,
     // The provided string must be contained within the overmap terrain id, but may
     // occur at the beginning, end, or middle and does not have any rules about
     // underscore delimiting.
     contains,
     num_ot_match_type
 };
phase_id
enum phase_id : int strong
Enumerator
PNULL
SOLID
LIQUID
GAS
PLASMA
num_phases
Definition at line 234 of file enums.h.
                     : int {
     PNULL,
     SOLID,
     LIQUID,
     GAS,
     PLASMA,
     num_phases
 };
reachability_cache_quadrant
enum reachability_cache_quadrant : int strong
Enumerator
NE
SE
NW
SW
Definition at line 421 of file enums.h.
                                        : int {
     NE, SE, NW, SW
 };
rule_state
enum rule_state : int strong
Enumerator
NONE
WHITELISTED
BLACKLISTED
Definition at line 109 of file enums.h.
                       : int {
     NONE,
     WHITELISTED,
     BLACKLISTED
 };
special_game_type
enum special_game_type : int strong
Enumerator
NONE
TUTORIAL
NUM_SPECIAL_GAME_TYPES
Definition at line 153 of file enums.h.
                              : int {
     NONE = 0,
     TUTORIAL,
     NUM_SPECIAL_GAME_TYPES
 };
temperature_flag
enum temperature_flag : int strong
Enumerator
NORMAL
HEATER
FRIDGE
FREEZER
ROOT_CELLAR
Definition at line 100 of file enums.h.
                             : int {
     NORMAL = 0,
     HEATER,
     FRIDGE,
     FREEZER,
     ROOT_CELLAR
 };
trinary
enum trinary : int strong
Enumerator
NONE
SOME
ALL
Definition at line 78 of file enums.h.
                    : int {
     NONE = 0,
     SOME = 1,
     ALL  = 2
 };
visibility_type
enum visibility_type : int strong
Enumerator
HIDDEN
CLEAR
LIT
BOOMER
DARK
BOOMER_DARK
Definition at line 115 of file enums.h.
                            : int {
     HIDDEN,
     CLEAR,
     LIT,
     BOOMER,
     DARK,
     BOOMER_DARK
 };
Function Documentation
is_decreasing()
constexpr bool is_decreasing (monotonically m) constexpr
Definition at line 449 of file enums.h.
 {
     return m == monotonically::constant || m == monotonically::decreasing;
 }
References constant, and decreasing.
Referenced by achievement_requirement::finalize().
is_increasing()
constexpr bool is_increasing (monotonically m) constexpr
Definition at line 444 of file enums.h.
 {
     return m == monotonically::constant || m == monotonically::increasing;
 }
References constant, and increasing.
Referenced by achievement_requirement::finalize(), and event_statistic_minimum::monotonicity().
operator+()
constexpr aim_entry operator+ (const aim_entry & lhs, const I & rhs) inline constexpr
Definition at line 54 of file enums.h.
 {
     return static_cast<aim_entry>( static_cast<I>( lhs ) + rhs );
 }
operator++() [1/2]
constexpr aim_entry& operator++ (aim_entry & lhs) inline constexpr
Definition at line 42 of file enums.h.
 {
     lhs = static_cast<aim_entry>( static_cast<I>( lhs ) + 1 );
     return lhs;
 }
operator++() [2/2]
layer_level& operator++ (layer_level & l) inline
Definition at line 313 of file enums.h.
 {
     l = static_cast<layer_level>( static_cast<int>( l ) + 1 );
     return l;
 }
operator-()
constexpr aim_entry operator- (const aim_entry & lhs, const I & rhs) inline constexpr
Definition at line 59 of file enums.h.
 {
     return static_cast<aim_entry>( static_cast<I>( lhs ) - rhs );
 }
operator--()
constexpr aim_entry& operator-- (aim_entry & lhs) inline constexpr
Definition at line 48 of file enums.h.
 {
     lhs = static_cast<aim_entry>( static_cast<I>( lhs ) - 1 );
     return lhs;
 }
sgn()
template<typename T > constexpr int sgn (const T x) inline constexpr
Definition at line 10 of file enums.h.
 {
     return x < 0 ? -1 : ( x > 0 ? 1 : 0 );
 }
Referenced by player_morale::morale_point::add(), bresenham(), vehicle::collision(), handbrake(), iexamine::ledge(), map::move_vehicle(), vehicle::part_collision(), game::phasing_move(), projectile_attack(), spell_effect::spell_effect_line(), squares_closer_to(), and vehicle::thrust().