Cataclysm DDA: src/event_field_transformations.cpp File Reference
event_field_transformations.cpp File Reference
#include "event_field_transformations.h"
#include <cmath>
#include <cstdlib>
#include <optional>
#include <set>
#include <string>
#include "coordinates.h"
#include "itype.h"
#include "mapdata.h"
#include "mtype.h"
#include "omdata.h"
#include "overmapbuffer.h"
#include "point.h"
#include "type_id.h"
Functions
static std::vector< cata_variant > flags_of_itype (const cata_variant &v)
static std::vector< cata_variant > flags_of_terrain (const cata_variant &v)
static std::vector< cata_variant > is_mounted (const cata_variant &v)
static std::vector< cata_variant > is_swimming_terrain (const cata_variant &v)
static std::vector< cata_variant > math_abs (const cata_variant &v)
static std::vector< cata_variant > oter_type_of_oter (const cata_variant &v)
static std::vector< cata_variant > overmap_special_at (const cata_variant &v)
static std::vector< cata_variant > species_of_monster (const cata_variant &v)
Variables
const std::unordered_map< std::string, event_field_transformation > event_field_transformations
Function Documentation
flags_of_itype()
static std::vector<cata_variant> flags_of_itype (const cata_variant & v) static
Definition at line 18 of file event_field_transformations.cpp.
 {
     const itype::FlagsSetType &flags = v.get<itype_id>()->get_flags();
     std::vector<cata_variant> result;
     result.reserve( flags.size() );
     for( const flag_id &s : flags ) {
         result.push_back( cata_variant::make<cata_variant_type::flag_id>( s ) );
     }
     return result;
 }
References cata_variant::get().
flags_of_terrain()
static std::vector<cata_variant> flags_of_terrain (const cata_variant & v) static
Definition at line 29 of file event_field_transformations.cpp.
 {
     const std::set<std::string> &flags = v.get<ter_id>()->get_flags();
     std::vector<cata_variant> result;
     result.reserve( flags.size() );
     for( const std::string &s : flags ) {
         result.push_back( cata_variant::make<cata_variant_type::string>( s ) );
     }
     return result;
 }
References cata_variant::get().
is_mounted()
static std::vector<cata_variant> is_mounted (const cata_variant & v) static
Definition at line 40 of file event_field_transformations.cpp.
 {
     const mtype_id mount = v.get<mtype_id>();
     std::vector<cata_variant> result = { cata_variant( !mount.is_empty() ) };
     return result;
 }
References cata_variant::get(), and string_id< T >::is_empty().
Referenced by Character::store().
is_swimming_terrain()
static std::vector<cata_variant> is_swimming_terrain (const cata_variant & v) static
Definition at line 47 of file event_field_transformations.cpp.
 {
     const ter_id ter = v.get<ter_id>();
     const bool swimming = ter->has_flag( ter_furn_flag::TFLAG_DEEP_WATER ) &&
                           ter->has_flag( ter_furn_flag::TFLAG_SWIMMABLE );
     std::vector<cata_variant> result = { cata_variant( swimming ) };
     return result;
 }
References cata_variant::get(), map_data_common_t::has_flag(), TFLAG_DEEP_WATER, and TFLAG_SWIMMABLE.
math_abs()
static std::vector<cata_variant> math_abs (const cata_variant & v) static
Definition at line 56 of file event_field_transformations.cpp.
 {
     std::vector<cata_variant> result = { cata_variant( std::abs( v.get<int>() ) ) };
     return result;
 }
References abs(), and cata_variant::get().
oter_type_of_oter()
static std::vector<cata_variant> oter_type_of_oter (const cata_variant & v) static
Definition at line 62 of file event_field_transformations.cpp.
 {
     const oter_id oter = v.get<oter_id>();
     std::vector<cata_variant> result = { cata_variant( oter->get_type_id() ) };
     return result;
 }
References cata_variant::get(), and oter_t::get_type_id().
overmap_special_at()
static std::vector<cata_variant> overmap_special_at (const cata_variant & v) static
Definition at line 69 of file event_field_transformations.cpp.
 {
     const tripoint_abs_omt p( v.get<tripoint>() );
     std::optional<overmap_special_id> special = overmap_buffer.overmap_special_at( p );
     if( special ) {
         return { cata_variant( *special ) };
     } else {
         return {};
     }
 }
References cata_variant::get(), overmap_buffer, and overmapbuffer::overmap_special_at().
species_of_monster()
static std::vector<cata_variant> species_of_monster (const cata_variant & v) static
Definition at line 80 of file event_field_transformations.cpp.
 {
     const std::set<species_id> &species = v.get<mtype_id>()->species;
     std::vector<cata_variant> result;
     result.reserve( species.size() );
     for( const species_id &s : species ) {
         result.emplace_back( s );
     }
     return result;
 }
References cata_variant::get().
Variable Documentation
event_field_transformations
const std::unordered_map<std::string, event_field_transformation> event_field_transformations
Definition at line 91 of file event_field_transformations.cpp.
Referenced by new_field::deserialize().