Cataclysm DDA: src/event_bus.h File Reference
event_bus.h File Reference
#include <utility>
#include <vector>
#include "event.h"
Classes
class event_bus
Macros
#define CATA_SRC_EVENT_BUS_H
Functions
event_bus & get_event_bus ()
Macro Definition Documentation
CATA_SRC_EVENT_BUS_H
#define CATA_SRC_EVENT_BUS_H
Definition at line 3 of file event_bus.h.
Function Documentation
get_event_bus()
event_bus& get_event_bus ()
Definition at line 13832 of file game.cpp.
 {
     return g->events();
 }
Referenced by achievement_attained(), achievement_failed(), computer_session::action_cascade(), computer_session::action_miss_disarm(), computer_session::action_portal(), computer_session::action_release(), computer_session::action_srcf_seal(), computer_session::action_terminate(), timed_event::actualize(), Character::add_addiction(), Creature::add_effect(), Character::apply_damage(), Character::bionics_install_failure(), activity_handlers::butcher_finish(), player_activity::canceled(), cast_spell(), spell::cast_spell_effect(), debug_menu::character_edit_menu(), Character::check_needs_extremes(), turn_handler::cleanup_at_end(), Character::consume(), avatar::control_npc(), debug_menu::debug(), mattack::dermatik(), stats_tracker::deserialize(), monster::die(), npc::die(), player_activity::do_turn(), construct::done_dig_grave(), construct::done_dig_grave_nospawn(), construct::done_digormine_stair(), construct::done_grave(), eat(), eff_fun_datura(), eff_fun_hypovolemia(), eff_fun_redcells_anemia(), eff_fun_teleglow(), npc::evaluate_best_attack(), vehicle::explode_fuel(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_trigger_event(), computer_session::failure_alarm(), Character::fall_asleep(), hacking_activity_actor::finish(), read_activity_actor::finish(), chop_tree_activity_actor::finish(), Character::fire_gun(), known_magic::forget_spell(), spell::gain_exp(), prying_activity_actor::handle_prying(), Character::hardcoded_effects(), Character::heal(), talk_function::hostile(), Character::hurtall(), known_magic::learn_spell(), main(), iuse::marloss(), marloss_common(), iuse::marloss_gel(), iuse::marloss_seed(), Character::melee_attack_abstract(), Character::mend(), iuse::mininuke(), Creature::mod_part_hp_cur(), Character::mutate_towards(), iuse::mycus(), read_activity_actor::npc_read(), vehicle::on_move(), iexamine::pedestal_wyrm(), Character::perform_install(), Character::perform_uninstall(), read_activity_actor::player_read(), Character::practice(), Character::practice_proficiency(), Creature::process_effects(), iuse::purify_smart(), avatar::read(), Character::rem_addiction(), Creature::remove_effect(), Character::remove_mutation(), Character::remove_weapon(), Creature::set_part_hp_cur(), known_magic::set_spell_exp(), known_magic::set_spell_level(), iuse::sewage(), smash(), activity_handlers::spellcasting_finish(), try_sleep_activity_actor::start(), player_activity::start_or_resume(), npc::starting_weapon(), teleport::teleport_to_point(), Character::test_crossing_threshold(), Character::throw_item(), Character::toggle_trait(), trap::trigger(), Character::unset_all_mutations(), Character::vomit(), Character::wake_up(), Character::wear(), outfit::wear_item(), npc::wield(), avatar::wield(), and Character::wield_contents().