Cataclysm DDA: src/explosion.h File Reference
explosion.h File Reference
#include <map>
#include <optional>
#include <string>
#include <vector>
#include "coordinates.h"
#include "type_id.h"
Classes
struct shrapnel_data
struct explosion_data
struct explosion_handler::queued_explosion
Namespaces
explosion_handler
Macros
#define CATA_SRC_EXPLOSION_H
Functions
void explosion_handler::explosion (const Creature *source, const tripoint &p, float power, float factor=0.8f, bool fire=false, int casing_mass=0, float frag_mass=0.05)
Queue an explosion at p of intensity (power) with (shrapnel) chunks of shrapnel.
void explosion_handler::explosion (const Creature *source, const tripoint &p, const explosion_data &ex)
void explosion_handler::_make_explosion (const Creature *source, const tripoint &p, const explosion_data &ex)
void explosion_handler::flashbang (const tripoint &p, bool player_immune=false)
Triggers a flashbang explosion at p.
void explosion_handler::resonance_cascade (const tripoint &p)
Triggers a resonance cascade at p.
void explosion_handler::scrambler_blast (const tripoint &p)
Triggers a scrambler blast at p.
void explosion_handler::emp_blast (const tripoint &p)
Triggers an EMP blast at p.
void explosion_handler::nuke (const tripoint_abs_omt &p)
Nuke the area at p - global overmap terrain coordinates!
void explosion_handler::shockwave (const tripoint &p, int radius, int force, int stun, int dam_mult, bool ignore_player)
void explosion_handler::draw_explosion (const tripoint &p, int radius, const nc_color &col)
void explosion_handler::draw_custom_explosion (const tripoint &p, const std::map< tripoint, nc_color > &area, const std::optional< std::string > &tile_id=std::nullopt)
int explosion_handler::ballistic_damage (float velocity, float mass)
float explosion_handler::gurney_spherical (const double charge, const double mass)
void explosion_handler::process_explosions ()
shrapnel_data load_shrapnel_data (const JsonObject &jo)
explosion_data load_explosion_data (const JsonObject &jo)
Variables
std::vector< queued_explosion > explosion_handler::_explosions
Macro Definition Documentation
CATA_SRC_EXPLOSION_H
#define CATA_SRC_EXPLOSION_H
Definition at line 3 of file explosion.h.
Function Documentation
load_explosion_data()
explosion_data load_explosion_data (const JsonObject & jo)
Definition at line 114 of file explosion.cpp.
 {
     explosion_data ret;
     // Power is mandatory
     jo.read( "power", ret.power );
     // Rest isn't
     ret.distance_factor = jo.get_float( "distance_factor", 0.75f );
     ret.max_noise = jo.get_int( "max_noise", 90000000 );
     ret.fire = jo.get_bool( "fire", false );
     if( jo.has_int( "shrapnel" ) ) {
         ret.shrapnel.casing_mass = jo.get_int( "shrapnel" );
         ret.shrapnel.recovery = 0;
         ret.shrapnel.drop = fuel_type_none;
     } else if( jo.has_object( "shrapnel" ) ) {
         JsonObject shr = jo.get_object( "shrapnel" );
         ret.shrapnel = load_shrapnel_data( shr );
     }
     return ret;
 }
References fuel_type_none, JsonObject::get_bool(), JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_object(), JsonObject::has_int(), JsonObject::has_object(), load_shrapnel_data(), JsonObject::read(), and cata::hash64_detail::ret.
Referenced by ammo_effect::load(), explosion_iuse::load(), and Item_factory::load_basic_info().
load_shrapnel_data()
shrapnel_data load_shrapnel_data (const JsonObject & jo)
Definition at line 135 of file explosion.cpp.
 {
     shrapnel_data ret;
     // Casing mass is mandatory
     jo.read( "casing_mass", ret.casing_mass );
     // Rest isn't
     ret.fragment_mass = jo.get_float( "fragment_mass", 0.08 );
     ret.recovery = jo.get_int( "recovery", 0 );
     ret.drop = itype_id( jo.get_string( "drop", "null" ) );
     return ret;
 }
References JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::read(), and cata::hash64_detail::ret.
Referenced by load_explosion_data().