Cataclysm DDA: src/explosion.cpp File Reference
explosion.cpp File Reference
#include "explosion.h"
#include "fragment_cloud.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <list>
#include <map>
#include <memory>
#include <optional>
#include <queue>
#include <random>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "color.h"
#include "creature.h"
#include "creature_tracker.h"
#include "damage.h"
#include "debug.h"
#include "enums.h"
#include "fault.h"
#include "field_type.h"
#include "flag.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "game.h"
#include "game_constants.h"
#include "item.h"
#include "item_factory.h"
#include "item_location.h"
#include "itype.h"
#include "line.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "math_defines.h"
#include "mdarray.h"
#include "messages.h"
#include "mongroup.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "options.h"
#include "point.h"
#include "projectile.h"
#include "rng.h"
#include "shadowcasting.h"
#include "sounds.h"
#include "translations.h"
#include "trap.h"
#include "type_id.h"
#include "units.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "vpart_position.h"
Namespaces
explosion_handler
Functions
explosion_data load_explosion_data (const JsonObject &jo)
shrapnel_data load_shrapnel_data (const JsonObject &jo)
int explosion_handler::ballistic_damage (float velocity, float mass)
static float explosion_handler::mass_to_area (const float mass)
float explosion_handler::gurney_spherical (const double charge, const double mass)
static void explosion_handler::do_blast (const Creature *source, const tripoint &p, const float power, const float distance_factor, const bool fire)
static std::vector< tripoint > explosion_handler::shrapnel (const Creature *source, const tripoint &src, int power, int casing_mass, float per_fragment_mass, int range=-1)
void explosion_handler::explosion (const Creature *source, const tripoint &p, float power, float factor=0.8f, bool fire=false, int casing_mass=0, float frag_mass=0.05)
Queue an explosion at p of intensity (power) with (shrapnel) chunks of shrapnel.
void explosion_handler::explosion (const Creature *source, const tripoint &p, const explosion_data &ex)
void explosion_handler::_make_explosion (const Creature *source, const tripoint &p, const explosion_data &ex)
void explosion_handler::flashbang (const tripoint &p, bool player_immune=false)
Triggers a flashbang explosion at p.
void explosion_handler::shockwave (const tripoint &p, int radius, int force, int stun, int dam_mult, bool ignore_player)
void explosion_handler::scrambler_blast (const tripoint &p)
Triggers a scrambler blast at p.
void explosion_handler::emp_blast (const tripoint &p)
Triggers an EMP blast at p.
void explosion_handler::nuke (const tripoint_abs_omt &p)
Nuke the area at p - global overmap terrain coordinates!
void explosion_handler::resonance_cascade (const tripoint &p)
Triggers a resonance cascade at p.
void explosion_handler::process_explosions ()
bool operator< (const fragment_cloud &us, const fragment_cloud &them)
fragment_cloud shrapnel_calc (const fragment_cloud &initial, const fragment_cloud &cloud, const int &distance)
bool shrapnel_check (const fragment_cloud &cloud, const fragment_cloud &intensity)
void update_fragment_cloud (fragment_cloud &update, const fragment_cloud &new_value, quadrant)
fragment_cloud accumulate_fragment_cloud (const fragment_cloud &cumulative_cloud, const fragment_cloud &current_cloud, const int &distance)
Variables
static const damage_type_id damage_bash ("bash")
static const damage_type_id damage_bullet ("bullet")
static const damage_type_id damage_heat ("heat")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_deaf ("deaf")
static const efftype_id effect_emp ("emp")
static const efftype_id effect_stunned ("stunned")
static const efftype_id effect_teleglow ("teleglow")
static const flag_id json_flag_ACTIVATE_ON_PLACE ("ACTIVATE_ON_PLACE")
static const furn_str_id furn_f_machinery_electronic ("f_machinery_electronic")
static const itype_id fuel_type_none ("null")
static const itype_id itype_e_handcuffs ("e_handcuffs")
static const itype_id itype_mininuke_act ("mininuke_act")
static const itype_id itype_rm13_armor_on ("rm13_armor_on")
static const json_character_flag json_flag_EMP_IMMUNE ("EMP_IMMUNE")
static const json_character_flag json_flag_GLARE_RESIST ("GLARE_RESIST")
static const mongroup_id GROUP_NETHER ("GROUP_NETHER")
static const species_id species_ROBOT ("ROBOT")
static const ter_str_id ter_t_card_industrial ("t_card_industrial")
static const ter_str_id ter_t_card_military ("t_card_military")
static const ter_str_id ter_t_card_reader_broken ("t_card_reader_broken")
static const ter_str_id ter_t_card_science ("t_card_science")
static const ter_str_id ter_t_door_metal_locked ("t_door_metal_locked")
static const ter_str_id ter_t_floor ("t_floor")
static const trait_id trait_LEG_TENT_BRACE ("LEG_TENT_BRACE")
static const trait_id trait_PER_SLIME ("PER_SLIME")
static const trait_id trait_PER_SLIME_OK ("PER_SLIME_OK")
static float fragment_mass = 0.0001f
static float fragment_area = 0.00001f
static constexpr float MIN_EFFECTIVE_VELOCITY = 70.0f
static constexpr float MIN_FRAGMENT_DENSITY = 0.001f
static constexpr double explosion_handler::TYPICAL_GURNEY_CONSTANT = 2700.0
Function Documentation
accumulate_fragment_cloud()
fragment_cloud accumulate_fragment_cloud (const fragment_cloud & cumulative_cloud, const fragment_cloud & current_cloud, const int & distance)
Definition at line 969 of file explosion.cpp.
 {
     // Velocity is the cumulative and continuous decay of speed,
     // so it is accumulated the same way as light attenuation.
     // Density is the accumulation of discrete attenuation events encountered in the traversed squares,
     // so each term is added to the series via multiplication.
     return fragment_cloud( ( ( distance - 1 ) * cumulative_cloud.velocity + current_cloud.velocity ) /
                            distance,
                            cumulative_cloud.density * current_cloud.density );
 }
References fragment_cloud::density, and fragment_cloud::velocity.
Referenced by explosion_handler::shrapnel().
load_explosion_data()
explosion_data load_explosion_data (const JsonObject & jo)
Definition at line 114 of file explosion.cpp.
 {
     explosion_data ret;
     // Power is mandatory
     jo.read( "power", ret.power );
     // Rest isn't
     ret.distance_factor = jo.get_float( "distance_factor", 0.75f );
     ret.max_noise = jo.get_int( "max_noise", 90000000 );
     ret.fire = jo.get_bool( "fire", false );
     if( jo.has_int( "shrapnel" ) ) {
         ret.shrapnel.casing_mass = jo.get_int( "shrapnel" );
         ret.shrapnel.recovery = 0;
         ret.shrapnel.drop = fuel_type_none;
     } else if( jo.has_object( "shrapnel" ) ) {
         JsonObject shr = jo.get_object( "shrapnel" );
         ret.shrapnel = load_shrapnel_data( shr );
     }
     return ret;
 }
References fuel_type_none, JsonObject::get_bool(), JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_object(), JsonObject::has_int(), JsonObject::has_object(), load_shrapnel_data(), JsonObject::read(), and cata::hash64_detail::ret.
Referenced by ammo_effect::load(), explosion_iuse::load(), and Item_factory::load_basic_info().
load_shrapnel_data()
shrapnel_data load_shrapnel_data (const JsonObject & jo)
Definition at line 135 of file explosion.cpp.
 {
     shrapnel_data ret;
     // Casing mass is mandatory
     jo.read( "casing_mass", ret.casing_mass );
     // Rest isn't
     ret.fragment_mass = jo.get_float( "fragment_mass", 0.08 );
     ret.recovery = jo.get_int( "recovery", 0 );
     ret.drop = itype_id( jo.get_string( "drop", "null" ) );
     return ret;
 }
References JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::read(), and cata::hash64_detail::ret.
Referenced by load_explosion_data().
operator<()
bool operator< (const fragment_cloud & us, const fragment_cloud & them)
Definition at line 936 of file explosion.cpp.
 {
     return us.density < them.density && us.velocity < them.velocity;
 }
References fragment_cloud::density, and fragment_cloud::velocity.
shrapnel_calc()
fragment_cloud shrapnel_calc (const fragment_cloud & initial, const fragment_cloud & cloud, const int & distance)
Definition at line 943 of file explosion.cpp.
 {
     // SWAG coefficient of drag.
     constexpr float Cd = 1.5f;
     fragment_cloud new_cloud;
     new_cloud.velocity = initial.velocity * std::exp( -cloud.velocity * ( (
                              Cd * fragment_area * distance ) /
                          ( 2.0f * fragment_mass ) ) );
     // Two effects, the accumulated proportion of blocked fragments,
     // and the inverse-square dilution of fragments with distance.
     new_cloud.density = ( initial.density * cloud.density ) / ( distance * distance );
     return new_cloud;
 }
References fragment_cloud::density, fragment_area, fragment_mass, and fragment_cloud::velocity.
Referenced by explosion_handler::shrapnel().
shrapnel_check()
bool shrapnel_check (const fragment_cloud & cloud, const fragment_cloud & intensity)
Definition at line 958 of file explosion.cpp.
 {
     return cloud.density > 0.0 && intensity.velocity > MIN_EFFECTIVE_VELOCITY &&
            intensity.density > MIN_FRAGMENT_DENSITY;
 }
References fragment_cloud::density, intensity, MIN_EFFECTIVE_VELOCITY, and MIN_FRAGMENT_DENSITY.
Referenced by explosion_handler::shrapnel().
update_fragment_cloud()
void update_fragment_cloud (fragment_cloud & update, const fragment_cloud & new_value, quadrant)
Definition at line 964 of file explosion.cpp.
 {
     update = std::max( update, new_value );
 }
References max().
Referenced by explosion_handler::shrapnel().
Variable Documentation
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by explosion_handler::do_blast().
damage_bullet
const damage_type_id damage_bullet("bullet") ("bullet") static
Referenced by explosion_handler::shrapnel().
damage_heat
const damage_type_id damage_heat("heat") ("heat") static
Referenced by explosion_handler::do_blast().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
Referenced by explosion_handler::flashbang().
effect_deaf
const efftype_id effect_deaf("deaf") ("deaf") static
Referenced by explosion_handler::flashbang().
effect_emp
const efftype_id effect_emp("emp") ("emp") static
Referenced by explosion_handler::emp_blast().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by explosion_handler::flashbang().
effect_teleglow
const efftype_id effect_teleglow("teleglow") ("teleglow") static
Referenced by explosion_handler::resonance_cascade().
fragment_area
float fragment_area = 0.00001f static
Definition at line 108 of file explosion.cpp.
Referenced by explosion_handler::shrapnel(), and shrapnel_calc().
fragment_mass
float fragment_mass = 0.0001f static
Definition at line 106 of file explosion.cpp.
Referenced by explosion_handler::shrapnel(), and shrapnel_calc().
fuel_type_none
const itype_id fuel_type_none("null") ("null") static
Referenced by load_explosion_data().
furn_f_machinery_electronic
const furn_str_id furn_f_machinery_electronic("f_machinery_electronic") ("f_machinery_electronic") static
Referenced by explosion_handler::emp_blast().
GROUP_NETHER
const mongroup_id GROUP_NETHER("GROUP_NETHER") ("GROUP_NETHER") static
Referenced by explosion_handler::resonance_cascade().
itype_e_handcuffs
const itype_id itype_e_handcuffs("e_handcuffs") ("e_handcuffs") static
Referenced by explosion_handler::emp_blast().
itype_mininuke_act
const itype_id itype_mininuke_act("mininuke_act") ("mininuke_act") static
Referenced by explosion_handler::nuke().
itype_rm13_armor_on
const itype_id itype_rm13_armor_on("rm13_armor_on") ("rm13_armor_on") static
Referenced by explosion_handler::flashbang().
json_flag_ACTIVATE_ON_PLACE
const flag_id json_flag_ACTIVATE_ON_PLACE("ACTIVATE_ON_PLACE") ("ACTIVATE_ON_PLACE") static
Referenced by explosion_handler::nuke().
json_flag_EMP_IMMUNE
const json_character_flag json_flag_EMP_IMMUNE("EMP_IMMUNE") ("EMP_IMMUNE") static
Referenced by explosion_handler::emp_blast().
json_flag_GLARE_RESIST
const json_character_flag json_flag_GLARE_RESIST("GLARE_RESIST") ("GLARE_RESIST") static
Referenced by explosion_handler::flashbang().
MIN_EFFECTIVE_VELOCITY
constexpr float MIN_EFFECTIVE_VELOCITY = 70.0f static constexpr
Definition at line 110 of file explosion.cpp.
Referenced by explosion_handler::shrapnel(), and shrapnel_check().
MIN_FRAGMENT_DENSITY
constexpr float MIN_FRAGMENT_DENSITY = 0.001f static constexpr
Definition at line 112 of file explosion.cpp.
Referenced by explosion_handler::shrapnel(), and shrapnel_check().
species_ROBOT
const species_id species_ROBOT("ROBOT") ("ROBOT") static
Referenced by explosion_handler::flashbang().
ter_t_card_industrial
const ter_str_id ter_t_card_industrial("t_card_industrial") ("t_card_industrial") static
Referenced by explosion_handler::emp_blast().
ter_t_card_military
const ter_str_id ter_t_card_military("t_card_military") ("t_card_military") static
Referenced by explosion_handler::emp_blast().
ter_t_card_reader_broken
const ter_str_id ter_t_card_reader_broken("t_card_reader_broken") ("t_card_reader_broken") static
Referenced by explosion_handler::emp_blast().
ter_t_card_science
const ter_str_id ter_t_card_science("t_card_science") ("t_card_science") static
Referenced by explosion_handler::emp_blast().
ter_t_door_metal_locked
const ter_str_id ter_t_door_metal_locked("t_door_metal_locked") ("t_door_metal_locked") static
Referenced by explosion_handler::emp_blast().
ter_t_floor
const ter_str_id ter_t_floor("t_floor") ("t_floor") static
Referenced by explosion_handler::emp_blast().
trait_LEG_TENT_BRACE
const trait_id trait_LEG_TENT_BRACE("LEG_TENT_BRACE") ("LEG_TENT_BRACE") static
Referenced by explosion_handler::shockwave().
trait_PER_SLIME
const trait_id trait_PER_SLIME("PER_SLIME") ("PER_SLIME") static
Referenced by explosion_handler::flashbang().
trait_PER_SLIME_OK
const trait_id trait_PER_SLIME_OK("PER_SLIME_OK") ("PER_SLIME_OK") static
Referenced by explosion_handler::flashbang().