Cataclysm DDA: src/faction.cpp File Reference
faction.cpp File Reference
#include "faction.h"
#include <algorithm>
#include <bitset>
#include <cstdlib>
#include <limits>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <utility>
#include "avatar.h"
#include "basecamp.h"
#include "calendar.h"
#include "catacharset.h"
#include "character.h"
#include "coordinates.h"
#include "cursesdef.h"
#include "debug.h"
#include "display.h"
#include "faction_camp.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "game.h"
#include "game_constants.h"
#include "input_context.h"
#include "json_error.h"
#include "line.h"
#include "localized_comparator.h"
#include "mission_companion.h"
#include "mtype.h"
#include "npc.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "point.h"
#include "skill.h"
#include "string_formatter.h"
#include "text_snippets.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "ui_manager.h"
Namespaces
npc_factions
Functions
std::string fac_ranking_text (int val)
std::string fac_respect_text (int val)
std::string fac_wealth_text (int val, int size)
std::string fac_combat_ability_text (int val)
Variables
static const faction_id faction_no_faction ("no_faction")
static const faction_id faction_your_followers ("your_followers")
static const flag_id json_flag_TWO_WAY_RADIO ("TWO_WAY_RADIO")
static std::vector< faction_template > npc_factions::all_templates
Function Documentation
fac_combat_ability_text()
std::string fac_combat_ability_text (int val)
Definition at line 429 of file faction.cpp.
 {
     if( val >= 150 ) {
         return pgettext( "Faction combat lvl", "Legendary" );
     }
     if( val >= 130 ) {
         return pgettext( "Faction combat lvl", "Expert" );
     }
     if( val >= 115 ) {
         return pgettext( "Faction combat lvl", "Veteran" );
     }
     if( val >= 105 ) {
         return pgettext( "Faction combat lvl", "Skilled" );
     }
     if( val >= 95 ) {
         return pgettext( "Faction combat lvl", "Competent" );
     }
     if( val >= 85 ) {
         return pgettext( "Faction combat lvl", "Untrained" );
     }
     if( val >= 75 ) {
         return pgettext( "Faction combat lvl", "Crippled" );
     }
     if( val >= 50 ) {
         return pgettext( "Faction combat lvl", "Feeble" );
     }
     return pgettext( "Faction combat lvl", "Worthless" );
 }
References pgettext.
fac_ranking_text()
std::string fac_ranking_text (int val)
Definition at line 198 of file faction.cpp.
 {
     if( val <= -100 ) {
         return _( "Archenemy" );
     }
     if( val <= -80 ) {
         return _( "Wanted Dead" );
     }
     if( val <= -60 ) {
         return _( "Enemy of the People" );
     }
     if( val <= -40 ) {
         return _( "Wanted Criminal" );
     }
     if( val <= -20 ) {
         return _( "Not Welcome" );
     }
     if( val <= -10 ) {
         return _( "Pariah" );
     }
     if( val <= -5 ) {
         return _( "Disliked" );
     }
     if( val >= 100 ) {
         return _( "Hero" );
     }
     if( val >= 80 ) {
         return _( "Idol" );
     }
     if( val >= 60 ) {
         return _( "Beloved" );
     }
     if( val >= 40 ) {
         return _( "Highly Valued" );
     }
     if( val >= 20 ) {
         return _( "Valued" );
     }
     if( val >= 10 ) {
         return _( "Well-Liked" );
     }
     if( val >= 5 ) {
         return _( "Liked" );
     }
     return _( "Neutral" );
 }
References _.
Referenced by faction::faction_display().
fac_respect_text()
std::string fac_respect_text (int val)
Definition at line 247 of file faction.cpp.
 {
     // Respected, feared, etc.
     if( val >= 100 ) {
         return pgettext( "Faction respect", "Legendary" );
     }
     if( val >= 80 ) {
         return pgettext( "Faction respect", "Unchallenged" );
     }
     if( val >= 60 ) {
         return pgettext( "Faction respect", "Mighty" );
     }
     if( val >= 40 ) {
         return pgettext( "Faction respect", "Famous" );
     }
     if( val >= 20 ) {
         return pgettext( "Faction respect", "Well-Known" );
     }
     if( val >= 10 ) {
         return pgettext( "Faction respect", "Spoken Of" );
     }
     // Disrespected, laughed at, etc.
     if( val <= -100 ) {
         return pgettext( "Faction respect", "Worthless Scum" );
     }
     if( val <= -80 ) {
         return pgettext( "Faction respect", "Vermin" );
     }
     if( val <= -60 ) {
         return pgettext( "Faction respect", "Despicable" );
     }
     if( val <= -40 ) {
         return pgettext( "Faction respect", "Parasite" );
     }
     if( val <= -20 ) {
         return pgettext( "Faction respect", "Leech" );
     }
     if( val <= -10 ) {
         return pgettext( "Faction respect", "Laughingstock" );
     }
     return pgettext( "Faction respect", "Neutral" );
 }
References pgettext.
fac_wealth_text()
std::string fac_wealth_text (int val, int size)
Definition at line 292 of file faction.cpp.
 {
     //Wealth per person
     val = val / size;
     if( val >= 1000000 ) {
         return pgettext( "Faction wealth", "Filthy rich" );
     }
     if( val >= 750000 ) {
         return pgettext( "Faction wealth", "Affluent" );
     }
     if( val >= 500000 ) {
         return pgettext( "Faction wealth", "Prosperous" );
     }
     if( val >= 250000 ) {
         return pgettext( "Faction wealth", "Well-Off" );
     }
     if( val >= 100000 ) {
         return pgettext( "Faction wealth", "Comfortable" );
     }
     if( val >= 85000 ) {
         return pgettext( "Faction wealth", "Wanting" );
     }
     if( val >= 70000 ) {
         return pgettext( "Faction wealth", "Failing" );
     }
     if( val >= 50000 ) {
         return pgettext( "Faction wealth", "Impoverished" );
     }
     return pgettext( "Faction wealth", "Destitute" );
 }
References pgettext, and om_direction::size.
Variable Documentation
faction_no_faction
const faction_id faction_no_faction("no_faction") ("no_faction") static
Referenced by faction_manager::get(), and faction_manager::remove_faction().
faction_your_followers
const faction_id faction_your_followers("your_followers") ("your_followers") static
Referenced by faction_manager::display().
json_flag_TWO_WAY_RADIO
const flag_id json_flag_TWO_WAY_RADIO("TWO_WAY_RADIO") ("TWO_WAY_RADIO") static
Referenced by npc::faction_display().