Cataclysm DDA: src/faction_camp.cpp File Reference
faction_camp.cpp File Reference
#include "faction_camp.h"
#include <algorithm>
#include <cstddef>
#include <list>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <unordered_set>
#include <vector>
#include "activity_actor_definitions.h"
#include "activity_type.h"
#include "avatar.h"
#include "basecamp.h"
#include "calendar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "clzones.h"
#include "colony.h"
#include "color.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "cursesdef.h"
#include "debug.h"
#include "enums.h"
#include "faction.h"
#include "flag.h"
#include "game.h"
#include "game_inventory.h"
#include "iexamine.h"
#include "input_context.h"
#include "inventory.h"
#include "inventory_ui.h"
#include "item.h"
#include "item_group.h"
#include "item_pocket.h"
#include "item_stack.h"
#include "itype.h"
#include "kill_tracker.h"
#include "line.h"
#include "localized_comparator.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "mapgen_functions.h"
#include "memory_fast.h"
#include "messages.h"
#include "mission.h"
#include "mission_companion.h"
#include "mongroup.h"
#include "npc.h"
#include "npctalk.h"
#include "omdata.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "overmap_ui.h"
#include "overmapbuffer.h"
#include "player_activity.h"
#include "point.h"
#include "recipe.h"
#include "recipe_groups.h"
#include "requirements.h"
#include "rng.h"
#include "skill.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "ui_manager.h"
#include "units.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "visitable.h"
#include "vpart_position.h"
#include "weather.h"
#include "weighted_list.h"
Classes
struct mass_volume
Namespaces
base_camps
Typedefs
using PathMap = cata::mdarray< double, point, path_map_size, path_map_size >
Functions
static const update_mapgen_id update_mapgen_faction_wall_level_N_1 (faction_wall_level_n_1_string.c_str())
static recipe_id base_camps::select_camp_option (const std::map< recipe_id, translation > &pos_options, const std::string &option)
static int om_harvest_ter (npc &comp, const tripoint_abs_omt &omt_tgt, const ter_id &t, int chance=100, bool estimate=false, bool bring_back=true)
Counts or destroys and drops the bash items of all terrain that matches t in the map tile.
static int om_harvest_ter_est (npc &comp, const tripoint_abs_omt &omt_tgt, const ter_id &t, int chance=100)
static int om_harvest_ter_break (npc &comp, const tripoint_abs_omt &omt_tgt, const ter_id &t, int chance=100)
static mass_volume om_harvest_itm (const npc_ptr &comp, const tripoint_abs_omt &omt_tgt, int chance=100, bool take=true)
Collects all items in omt_tgt with a chance between 0 - 1.0, returns total mass and volume take, whether you take the item or count it.
static void apply_camp_ownership (map &here, const tripoint &camp_pos, int radius)
static int om_cutdown_trees (const tripoint_abs_omt &omt_tgt, int chance=100, bool estimate=false, bool force_cut_trunk=true)
static int om_cutdown_trees_est (const tripoint_abs_omt &omt_tgt, int chance=100)
static int om_cutdown_trees_logs (const tripoint_abs_omt &omt_tgt, int chance=100)
static int om_cutdown_trees_trunks (const tripoint_abs_omt &omt_tgt, int chance=100)
static bool om_set_hide_site (npc &comp, const tripoint_abs_omt &omt_tgt, const drop_locations &itms, const drop_locations &itms_rem={})
Creates an improvised shelter at omt_tgt and dumps the itms into the building.
static tripoint_abs_omt om_target_tile (const tripoint_abs_omt &omt_pos, int min_range=1, int range=1, const std::vector< std::string > &possible_om_types={}, ot_match_type match_type=ot_match_type::exact, bool must_see=true, bool popup_notice=true, const tripoint_abs_omt &source=tripoint_abs_omt(-999, -999, -999), bool bounce=false)
Opens the overmap so that you can select points for missions or constructions.
static void om_range_mark (const tripoint_abs_omt &origin, int range, bool add_notes=true, const std::string &message="Y;X: MAX RANGE")
static void om_line_mark (const tripoint_abs_omt &origin, const tripoint_abs_omt &dest, bool add_notes=true, const std::string &message="R;X: PATH")
static std::vector< tripoint_abs_omt > om_companion_path (const tripoint_abs_omt &start, int range_start=90, bool bounce=true)
static time_duration companion_travel_time_calc (const tripoint_abs_omt &pos, const tripoint_abs_omt &tgt, time_duration work, int trips=1, int haulage=0)
Can be used to calculate total trip time for an NPC mission or just the traveling portion.
static time_duration companion_travel_time_calc (const std::vector< tripoint_abs_omt > &journey, time_duration work, int trips=1, int haulage=0)
static int om_carry_weight_to_trips (const units::mass &total_mass, const units::volume &total_volume, const npc_ptr &comp=nullptr)
Determines how many trips it takes to move mass and volume of items with carry_mass and carry_volume moved per trip.
static int om_carry_weight_to_trips (const units::mass &mass, const units::volume &volume, const units::mass &carry_mass, const units::volume &carry_volume)
static std::string camp_trip_description (const time_duration &total_time, const time_duration &working_time, const time_duration &travel_time, int distance, int trips, int need_food)
Formats the variables into a standard looking description to be displayed in a ynquery window.
static bool survive_random_encounter (npc &comp, std::string &situation, int favor, int threat)
static std::string mission_ui_activity_of (const mission_id &miss_id)
static std::map< std::string, comp_list > companion_per_recipe_building_type (comp_list &npc_list)
static bool update_time_left (std::string &entry, const comp_list &npc_list)
static bool update_time_fixed (std::string &entry, const comp_list &npc_list, const time_duration &duration)
static bool update_emergency_recall (std::string &entry, const comp_list &npc_list, const time_duration &duration)
static bool extract_and_check_orientation_flags (const recipe_id &recipe, const point &dir, bool &mirror_horizontal, bool &mirror_vertical, int &rotation, const std::string_view base_error_message, const std::string &actor)
static std::optional< basecamp * > get_basecamp (npc &p, const std::string_view camp_type="default")
static void change_cleared_terrain (tripoint_abs_omt forest)
static void apply_fortifications (const mission_id &miss_id, const npc_ptr *comp, bool start)
static point check_salt_pipe_neighbors (PathMap &path_map, point pt)
static int salt_water_pipe_segment_of (const recipe &making)
static point connection_direction_of (const point &dir, const recipe &making)
static void salt_water_pipe_orientation_adjustment (const point &dir, bool &orthogonal, bool &mirror_vertical, bool &mirror_horizontal, int &rotation)
static bool farm_valid_seed (const item &itm)
static std::pair< size_t, std::string > farm_action (const tripoint_abs_omt &omt_tgt, farm_ops op, const npc_ptr &comp=nullptr)
static const npc & getAverageJoe ()
Variables
static const activity_id ACT_MOVE_LOOT ("ACT_MOVE_LOOT")
static const furn_str_id furn_f_plant_harvest ("f_plant_harvest")
static const furn_str_id furn_f_plant_seed ("f_plant_seed")
static const item_group_id Item_spawn_data_foraging_faction_camp_autumn ("foraging_faction_camp_autumn")
static const item_group_id Item_spawn_data_foraging_faction_camp_spring ("foraging_faction_camp_spring")
static const item_group_id Item_spawn_data_foraging_faction_camp_summer ("foraging_faction_camp_summer")
static const item_group_id Item_spawn_data_foraging_faction_camp_winter ("foraging_faction_camp_winter")
static const item_group_id Item_spawn_data_forest ("forest")
static const item_group_id Item_spawn_data_gathering_faction_camp_firewood ("gathering_faction_camp_firewood")
static const itype_id itype_duffelbag ("duffelbag")
static const itype_id itype_fungal_seeds ("fungal_seeds")
static const itype_id itype_log ("log")
static const itype_id itype_marloss_seed ("marloss_seed")
static const mongroup_id GROUP_CAMP_HUNTING ("GROUP_CAMP_HUNTING")
static const mongroup_id GROUP_CAMP_HUNTING_LARGE ("GROUP_CAMP_HUNTING_LARGE")
static const mongroup_id GROUP_CAMP_TRAPPING ("GROUP_CAMP_TRAPPING")
static const oter_str_id oter_dirt_road_3way_forest_east ("dirt_road_3way_forest_east")
static const oter_str_id oter_dirt_road_3way_forest_north ("dirt_road_3way_forest_north")
static const oter_str_id oter_dirt_road_3way_forest_south ("dirt_road_3way_forest_south")
static const oter_str_id oter_dirt_road_3way_forest_west ("dirt_road_3way_forest_west")
static const oter_str_id oter_dirt_road_forest_east ("dirt_road_forest_east")
static const oter_str_id oter_dirt_road_forest_north ("dirt_road_forest_north")
static const oter_str_id oter_dirt_road_forest_south ("dirt_road_forest_south")
static const oter_str_id oter_dirt_road_forest_west ("dirt_road_forest_west")
static const oter_str_id oter_dirt_road_turn_forest_east ("dirt_road_turn_forest_east")
static const oter_str_id oter_dirt_road_turn_forest_north ("dirt_road_turn_forest_north")
static const oter_str_id oter_dirt_road_turn_forest_south ("dirt_road_turn_forest_south")
static const oter_str_id oter_dirt_road_turn_forest_west ("dirt_road_turn_forest_west")
static const oter_str_id oter_forest ("forest")
static const oter_str_id oter_forest_thick ("forest_thick")
static const oter_str_id oter_rural_road_3way_forest_east ("rural_road_3way_forest_east")
static const oter_str_id oter_rural_road_3way_forest_north ("rural_road_3way_forest_north")
static const oter_str_id oter_rural_road_3way_forest_south ("rural_road_3way_forest_south")
static const oter_str_id oter_rural_road_3way_forest_west ("rural_road_3way_forest_west")
static const oter_str_id oter_rural_road_forest_east ("rural_road_forest_east")
static const oter_str_id oter_rural_road_forest_north ("rural_road_forest_north")
static const oter_str_id oter_rural_road_forest_south ("rural_road_forest_south")
static const oter_str_id oter_rural_road_forest_west ("rural_road_forest_west")
static const oter_str_id oter_rural_road_turn1_forest_east ("rural_road_turn1_forest_east")
static const oter_str_id oter_rural_road_turn1_forest_north ("rural_road_turn1_forest_north")
static const oter_str_id oter_rural_road_turn1_forest_south ("rural_road_turn1_forest_south")
static const oter_str_id oter_rural_road_turn1_forest_west ("rural_road_turn1_forest_west")
static const oter_str_id oter_rural_road_turn_forest_east ("rural_road_turn_forest_east")
static const oter_str_id oter_rural_road_turn_forest_north ("rural_road_turn_forest_north")
static const oter_str_id oter_rural_road_turn_forest_south ("rural_road_turn_forest_south")
static const oter_str_id oter_rural_road_turn_forest_west ("rural_road_turn_forest_west")
static const oter_str_id oter_special_forest ("special_forest")
static const oter_str_id oter_special_forest_thick ("special_forest_thick")
static const oter_type_str_id oter_type_forest_trail ("forest_trail")
static const skill_id skill_bashing ("bashing")
static const skill_id skill_combat ("combat")
static const skill_id skill_construction ("construction")
static const skill_id skill_cutting ("cutting")
static const skill_id skill_dodge ("dodge")
static const skill_id skill_fabrication ("fabrication")
static const skill_id skill_gun ("gun")
static const skill_id skill_melee ("melee")
static const skill_id skill_menial ("menial")
static const skill_id skill_recruiting ("recruiting")
static const skill_id skill_speech ("speech")
static const skill_id skill_stabbing ("stabbing")
static const skill_id skill_survival ("survival")
static const skill_id skill_swimming ("swimming")
static const skill_id skill_traps ("traps")
static const skill_id skill_unarmed ("unarmed")
static const ter_str_id ter_t_clay ("t_clay")
static const ter_str_id ter_t_dirt ("t_dirt")
static const ter_str_id ter_t_dirtmound ("t_dirtmound")
static const ter_str_id ter_t_grass ("t_grass")
static const ter_str_id ter_t_grass_dead ("t_grass_dead")
static const ter_str_id ter_t_grass_golf ("t_grass_golf")
static const ter_str_id ter_t_grass_long ("t_grass_long")
static const ter_str_id ter_t_grass_tall ("t_grass_tall")
static const ter_str_id ter_t_improvised_shelter ("t_improvised_shelter")
static const ter_str_id ter_t_moss ("t_moss")
static const ter_str_id ter_t_sand ("t_sand")
static const ter_str_id ter_t_stump ("t_stump")
static const ter_str_id ter_t_tree_young ("t_tree_young")
static const ter_str_id ter_t_trunk ("t_trunk")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
static const update_mapgen_id update_mapgen_faction_wall_level_E_1 ("faction_wall_level_E_1")
static const update_mapgen_id update_mapgen_faction_wall_level_S_1 ("faction_wall_level_S_1")
static const update_mapgen_id update_mapgen_faction_wall_level_W_1 ("faction_wall_level_W_1")
static const zone_type_id zone_type_CAMP_FOOD ("CAMP_FOOD")
static const zone_type_id zone_type_CAMP_STORAGE ("CAMP_STORAGE")
static const std::string faction_wall_level_n_0_string = "faction_wall_level_N_0"
static const std::string faction_wall_level_n_1_string = "faction_wall_level_N_1"
static const std::string faction_hide_site_0_string = "faction_hide_site_0"
static const oter_str_id oter_faction_hide_site_0 (faction_hide_site_0_string)
static const std::string camp_om_fortifications_trench_parameter = faction_wall_level_n_0_string
static const std::string camp_om_fortifications_spiked_trench_parameter
static const std::string var_time_between_succession
static const std::string var_timer_time_of_last_succession
static const std::string base_recipe_group_string = "BASE"
static const std::string cook_recipe_group_string = "COOK"
static const std::string farm_recipe_group_string = "FARM"
static const std::string smith_recipe_group_string = "SMITH"
static const translation base_camps::recover_ally_string = to_translation("Recover Ally, ")
static const translation base_camps::expansion_string = to_translation(" Expansion")
static const std::string faction_expansion_salt_water_pipe_swamp_base
static const std::string faction_expansion_salt_water_pipe_swamp_N
static const std::string faction_expansion_salt_water_pipe_swamp_NE
static const std::string faction_expansion_salt_water_pipe_base
static const std::string faction_expansion_salt_water_pipe_N
static const std::string faction_expansion_salt_water_pipe_NE
static const tripoint relay_site_stash = tripoint(11, 10, 0)
static const int max_salt_water_pipe_distance = 10
static const int max_salt_water_pipe_length
static const std::string salt_water_pipe_string_base = "salt_water_pipe_"
static const std::string salt_water_pipe_string_suffix = "_scheduled"
static const double diagonal_salt_pipe_cost = std::sqrt(2.0)
static const double salt_pipe_legal = 0.0
static const double salt_pipe_illegal = -0.1
static const double salt_pipe_swamp = -0.2
static constexpr size_t path_map_size = 2 * max_salt_water_pipe_distance + 1
Typedef Documentation
PathMap
using PathMap = cata::mdarray<double, point, path_map_size, path_map_size>
Definition at line 2925 of file faction_camp.cpp.
Function Documentation
apply_camp_ownership()
void apply_camp_ownership (map & here, const tripoint & camp_pos, int radius) static
Definition at line 5992 of file faction_camp.cpp.
 {
     for( const tripoint &p : here.points_in_rectangle( camp_pos + point( -radius, -radius ),
             camp_pos + point( radius, radius ) ) ) {
         map_stack items = here.i_at( p.xy() );
         for( item &elem : items ) {
             elem.set_owner( get_player_character() );
         }
     }
 }
References get_player_character(), map::i_at(), and map::points_in_rectangle().
Referenced by basecamp::place_results().
apply_fortifications()
static void apply_fortifications (const mission_id & miss_id, const npc_ptr * comp, bool start) static
Definition at line 2755 of file faction_camp.cpp.
 {
     update_mapgen_id build_n{ faction_wall_level_n_0_string };
     update_mapgen_id build_e{ "faction_wall_level_E_0" };
     update_mapgen_id build_s{ "faction_wall_level_S_0" };
     update_mapgen_id build_w{ "faction_wall_level_W_0" };
     if( miss_id.parameters == faction_wall_level_n_1_string ||
         //  Handling of old format (changed mid 0.F) below
         ( miss_id.parameters.empty() &&
           comp[0]->companion_mission_role_id == faction_wall_level_n_1_string ) ) {
         build_n = update_mapgen_faction_wall_level_N_1;
         build_e = update_mapgen_faction_wall_level_E_1;
         build_s = update_mapgen_faction_wall_level_S_1;
         build_w = update_mapgen_faction_wall_level_W_1;
     }
     update_mapgen_id build_first = build_e;
     update_mapgen_id build_second = build_w;
     bool build_dir_NS = comp[0]->companion_mission_points[0].y() !=
                         comp[0]->companion_mission_points[1].y();
     if( build_dir_NS ) {
         build_first = build_s;
         build_second = build_n;
     }
     //Add fences
     auto &build_point = comp[0]->companion_mission_points;
     for( size_t pt = 0; pt < build_point.size(); pt++ ) {
         //First point is always at top or west since they are built in a line and sorted
         if( pt == 0 ) {
             if( !start ) {
                 run_mapgen_update_func( build_first, build_point[pt], {} );
             }
             apply_construction_marker( build_first, build_point[pt],
                                        miss_id.mapgen_args, false,
                                        false, false, start );
         } else if( pt == build_point.size() - 1 ) {
             if( !start ) {
                 run_mapgen_update_func( build_second, build_point[pt], {} );
             }
             apply_construction_marker( build_second, build_point[pt],
                                        miss_id.mapgen_args, false,
                                        false, false, start );
         } else {
             if( !start ) {
                 run_mapgen_update_func( build_first, build_point[pt], {} );
                 run_mapgen_update_func( build_second, build_point[pt], {} );
             }
             apply_construction_marker( build_first, build_point[pt],
                                        miss_id.mapgen_args, false,
                                        false, false, start );
             apply_construction_marker( build_second, build_point[pt],
                                        miss_id.mapgen_args, false,
                                        false, false, start );
         }
     }
 }
References apply_construction_marker(), faction_wall_level_n_0_string, faction_wall_level_n_1_string, mission_id::mapgen_args, mission_id::parameters, run_mapgen_update_func(), update_mapgen_faction_wall_level_E_1, update_mapgen_faction_wall_level_N_1(), update_mapgen_faction_wall_level_S_1, and update_mapgen_faction_wall_level_W_1.
Referenced by basecamp::fortifications_return(), and basecamp::start_fortifications().
camp_trip_description()
std::string camp_trip_description (const time_duration & total_time, const time_duration & working_time, const time_duration & travel_time, int distance, int trips, int need_food) static
Formats the variables into a standard looking description to be displayed in a ynquery window.
Definition at line 5339 of file faction_camp.cpp.
 {
     std::string entry = "\n";
     //A square is roughly 3 m
     int dist_m = distance * SEEX * 2 * 3;
     if( dist_m > 1000 ) {
         entry += string_format( _( ">Distance:%15.2f (km)\n" ), dist_m / 1000.0 );
         entry += string_format( _( ">One Way: %15d (trips)\n" ), trips );
         entry += string_format( _( ">Covered: %15.2f (km)\n" ), dist_m / 1000.0 * trips );
     } else {
         entry += string_format( _( ">Distance:%15d (m)\n" ), dist_m );
         entry += string_format( _( ">One Way: %15d (trips)\n" ), trips );
         entry += string_format( _( ">Covered: %15d (m)\n" ), dist_m * trips );
     }
     entry += string_format( _( ">Travel:  %s\n" ), right_justify( to_string( travel_time ), 23 ) );
     entry += string_format( _( ">Working: %s\n" ), right_justify( to_string( working_time ), 23 ) );
     entry += "----                   ----\n";
     entry += string_format( _( "Total:    %s\n" ), right_justify( to_string( total_time ), 23 ) );
     entry += string_format( _( "Food:     %15d (kcal)\n\n" ), need_food );
     return entry;
 }
References _, need_food, right_justify(), SEEX, string_format(), and to_string().
Referenced by basecamp::start_clearcut(), basecamp::start_combat_mission(), basecamp::start_cut_logs(), basecamp::start_fortifications(), basecamp::start_relay_hide_site(), and basecamp::start_setup_hide_site().
change_cleared_terrain()
static void change_cleared_terrain (tripoint_abs_omt forest) static
Definition at line 2484 of file faction_camp.cpp.
 {
     if( om_cutdown_trees_est( forest ) < 5 ) {
         const oter_id &omt_trees = overmap_buffer.ter( forest );
         const std::string omt_trees_string = static_cast<std::string>( omt_trees.id() );
         if( omt_trees_string.find( "dirt_road" ) != std::string::npos ) {}
         if( omt_trees.id() == oter_dirt_road_forest_north ) {
             overmap_buffer.ter_set( forest, oter_id( "dirt_road_north" ) );
         } else if( omt_trees.id() == oter_dirt_road_forest_east ) {
             overmap_buffer.ter_set( forest, oter_id( "dirt_road_east" ) );
         } else if( omt_trees.id() == oter_dirt_road_forest_south ) {
             overmap_buffer.ter_set( forest, oter_id( "dirt_road_south" ) );
         } else if( omt_trees.id() == oter_dirt_road_forest_west ) {
             overmap_buffer.ter_set( forest, oter_id( "dirt_road_west" ) );
         } else if( omt_trees.id() == oter_dirt_road_3way_forest_north ) {
             overmap_buffer.ter_set( forest, oter_id( "dirt_road_3way_north" ) );
         } else if( omt_trees.id() == oter_dirt_road_3way_forest_east ) {
             overmap_buffer.ter_set( forest, oter_id( "dirt_road_3way_east" ) );
         } else if( omt_trees.id() == oter_dirt_road_3way_forest_south ) {
             overmap_buffer.ter_set( forest, oter_id( "dirt_road_3way_south" ) );
         } else if( omt_trees.id() == oter_dirt_road_3way_forest_west ) {
             overmap_buffer.ter_set( forest, oter_id( "dirt_road_3way_west" ) );
         } else if( omt_trees.id() == oter_dirt_road_turn_forest_north ) {
             overmap_buffer.ter_set( forest, oter_id( "dirt_road_turn_north" ) );
         } else if( omt_trees.id() == oter_dirt_road_turn_forest_east ) {
             overmap_buffer.ter_set( forest, oter_id( "dirt_road_turn_east" ) );
         } else if( omt_trees.id() == oter_dirt_road_turn_forest_south ) {
             overmap_buffer.ter_set( forest, oter_id( "dirt_road_turn_south" ) );
         } else if( omt_trees.id() == oter_dirt_road_turn_forest_west ) {
             overmap_buffer.ter_set( forest, oter_id( "dirt_road_turn_west" ) );
         }
         else if( omt_trees.id() == oter_forest || omt_trees.id() == oter_forest_thick ||
                  omt_trees.id() == oter_special_forest || omt_trees.id() == oter_special_forest_thick ||
                  omt_trees_string.find( "forest_trail" ) != std::string::npos ) {
             overmap_buffer.ter_set( forest, oter_id( "field" ) );
         } else if( omt_trees.id() == oter_rural_road_forest_north ) {
             overmap_buffer.ter_set( forest, oter_id( "rural_road_north" ) );
         } else if( omt_trees.id() == oter_rural_road_forest_east ) {
             overmap_buffer.ter_set( forest, oter_id( "rural_road_east" ) );
         } else if( omt_trees.id() == oter_rural_road_forest_south ) {
             overmap_buffer.ter_set( forest, oter_id( "rural_road_south" ) );
         } else if( omt_trees.id() == oter_rural_road_forest_west ) {
             overmap_buffer.ter_set( forest, oter_id( "rural_road_west" ) );
         } else if( omt_trees.id() == oter_rural_road_3way_forest_north ) {
             overmap_buffer.ter_set( forest, oter_id( "rural_road_3way_north" ) );
         } else if( omt_trees.id() == oter_rural_road_3way_forest_east ) {
             overmap_buffer.ter_set( forest, oter_id( "rural_road_3way_east" ) );
         } else if( omt_trees.id() == oter_rural_road_3way_forest_south ) {
             overmap_buffer.ter_set( forest, oter_id( "rural_road_3way_south" ) );
         } else if( omt_trees.id() == oter_rural_road_3way_forest_west ) {
             overmap_buffer.ter_set( forest, oter_id( "rural_road_3way_west" ) );
         } else if( omt_trees.id() == oter_rural_road_turn_forest_north ) {
             overmap_buffer.ter_set( forest, oter_id( "rural_road_turn_north" ) );
         } else if( omt_trees.id() == oter_rural_road_turn_forest_east ) {
             overmap_buffer.ter_set( forest, oter_id( "rural_road_turn_east" ) );
         } else if( omt_trees.id() == oter_rural_road_turn_forest_south ) {
             overmap_buffer.ter_set( forest, oter_id( "rural_road_turn_south" ) );
         } else if( omt_trees.id() == oter_rural_road_turn_forest_west ) {
             overmap_buffer.ter_set( forest, oter_id( "rural_road_turn_west" ) );
         } else if( omt_trees.id() == oter_rural_road_turn1_forest_north ) {
             overmap_buffer.ter_set( forest, oter_id( "rural_road_turn1_north" ) );
         } else if( omt_trees.id() == oter_rural_road_turn1_forest_east ) {
             overmap_buffer.ter_set( forest, oter_id( "rural_road_turn1_east" ) );
         } else if( omt_trees.id() == oter_rural_road_turn1_forest_south ) {
             overmap_buffer.ter_set( forest, oter_id( "rural_road_turn1_south" ) );
         } else if( omt_trees.id() == oter_rural_road_turn1_forest_west ) {
             overmap_buffer.ter_set( forest, oter_id( "rural_road_turn1_west" ) );
         } else {
             popup( _( "%s isn't a recognized terrain.  Please file a bug report." ), omt_trees.id().c_str() );
             return;
         }
         popup( _( "The logged tile has been cleared and cannot be logged further after this mission." ),
                omt_trees.id().c_str() );
     }
 }
References _, string_id< T >::c_str(), forest, int_id< T >::id(), om_cutdown_trees_est(), oter_dirt_road_3way_forest_east, oter_dirt_road_3way_forest_north, oter_dirt_road_3way_forest_south, oter_dirt_road_3way_forest_west, oter_dirt_road_forest_east, oter_dirt_road_forest_north, oter_dirt_road_forest_south, oter_dirt_road_forest_west, oter_dirt_road_turn_forest_east, oter_dirt_road_turn_forest_north, oter_dirt_road_turn_forest_south, oter_dirt_road_turn_forest_west, oter_forest, oter_forest_thick, oter_rural_road_3way_forest_east, oter_rural_road_3way_forest_north, oter_rural_road_3way_forest_south, oter_rural_road_3way_forest_west, oter_rural_road_forest_east, oter_rural_road_forest_north, oter_rural_road_forest_south, oter_rural_road_forest_west, oter_rural_road_turn1_forest_east, oter_rural_road_turn1_forest_north, oter_rural_road_turn1_forest_south, oter_rural_road_turn1_forest_west, oter_rural_road_turn_forest_east, oter_rural_road_turn_forest_north, oter_rural_road_turn_forest_south, oter_rural_road_turn_forest_west, oter_special_forest, oter_special_forest_thick, overmap_buffer, popup(), overmapbuffer::ter(), and overmapbuffer::ter_set().
Referenced by basecamp::start_clearcut(), and basecamp::start_cut_logs().
check_salt_pipe_neighbors()
static point check_salt_pipe_neighbors (PathMap & path_map, point pt) static
Definition at line 2932 of file faction_camp.cpp.
 {
     point found = { -999, -999 };
     double lowest_found = -10000.0;
     double cost;
     for( int i = -1; i <= 1; i++ ) {
         for( int k = -1; k <= 1; k++ ) {
             if( pt.x + i > -max_salt_water_pipe_distance &&
                 pt.x + i < max_salt_water_pipe_distance &&
                 pt.y + k > -max_salt_water_pipe_distance &&
                 pt.y + k < max_salt_water_pipe_distance ) {
                 if( i != 0 && k != 0 ) {
                     cost = diagonal_salt_pipe_cost;
                 } else {
                     cost = 1.0;
                 }
                 if( path_map[max_salt_water_pipe_distance + pt.x + i][max_salt_water_pipe_distance + pt.y + k] ==
                     salt_pipe_legal ||
                     ( path_map[max_salt_water_pipe_distance + pt.x + i][max_salt_water_pipe_distance + pt.y + k] >
                       0.0 &&
                       path_map[max_salt_water_pipe_distance + pt.x + i][max_salt_water_pipe_distance + pt.y + k] >
                       path_map[max_salt_water_pipe_distance + pt.x][max_salt_water_pipe_distance + pt.y] + cost ) ) {
                     path_map[max_salt_water_pipe_distance + pt.x + i][max_salt_water_pipe_distance + pt.y + k] =
                         path_map[max_salt_water_pipe_distance + pt.x][max_salt_water_pipe_distance + pt.y] + cost;
                 } else if( path_map[max_salt_water_pipe_distance + pt.x + i][max_salt_water_pipe_distance + pt.y +
                            k] <=
                            salt_pipe_swamp ) {
                     if( path_map[max_salt_water_pipe_distance + pt.x + i][max_salt_water_pipe_distance + pt.y + k] ==
                         salt_pipe_swamp ||
                         path_map[max_salt_water_pipe_distance + pt.x + i][max_salt_water_pipe_distance + pt.y + k] < -
                         ( path_map[max_salt_water_pipe_distance + pt.x][max_salt_water_pipe_distance + pt.y] + cost ) ) {
                         path_map[max_salt_water_pipe_distance + pt.x + i][max_salt_water_pipe_distance + pt.y + k] = -
                                 ( path_map[max_salt_water_pipe_distance + pt.x][max_salt_water_pipe_distance + pt.y] + cost );
                         if( path_map[max_salt_water_pipe_distance + pt.x + i][max_salt_water_pipe_distance + pt.y + k] >
                             lowest_found ) {
                             lowest_found = path_map[max_salt_water_pipe_distance + pt.x + i][max_salt_water_pipe_distance + pt.y
                                            + k];
                             found = pt + point( i, k );
                         }
                     }
                 }
             }
         }
     }
     return found;
 }
References diagonal_salt_pipe_cost, max_salt_water_pipe_distance, salt_pipe_legal, salt_pipe_swamp, point::x, and point::y.
Referenced by basecamp::start_salt_water_pipe().
companion_per_recipe_building_type()
static std::map<std::string, comp_list> companion_per_recipe_building_type (comp_list & npc_list) static
Definition at line 469 of file faction_camp.cpp.
 {
     std::map<std::string, comp_list> result;
     for( const npc_ptr &comp : npc_list ) {
         const mission_id miss_id = comp->get_companion_mission().miss_id;
         const std::string bldg = recipe_group::get_building_of_recipe( miss_id.parameters );
         if( result[bldg].empty() ) {
             comp_list temp;
             result.insert( std::pair<std::string, comp_list>( bldg, temp ) );
         }
         result[bldg].emplace_back( comp );
     }
     return result;
 }
References recipe_group::get_building_of_recipe(), npc::get_companion_mission(), npc_companion_mission::miss_id, mission_id::parameters, and temp.
Referenced by basecamp::companion_crafting_choose_return(), and basecamp::get_available_missions_by_dir().
companion_travel_time_calc() [1/2]
static time_duration companion_travel_time_calc (const std::vector< tripoint_abs_omt > & journey, time_duration work, int trips = 1, int haulage = 0) static
Definition at line 5094 of file faction_camp.cpp.
 {
     int one_way = 0;
     for( const tripoint_abs_omt &om : journey ) {
         const oter_id &omt_ref = overmap_buffer.ter( om );
         std::string om_id = omt_ref.id().c_str();
         // Player walks 1 om in roughly 30 seconds
         if( om_id == "field" ) {
             one_way += 30 + ( 30 + haulage );
         } else if( omt_ref->get_type_id() == oter_type_forest_trail ) {
             one_way += 35 + ( 30 + haulage );
         } else if( om_id == "forest_thick" ) {
             one_way += 50 + ( 30 + haulage );
         } else if( om_id == "forest_water" ) {
             one_way += 60 + ( 30 + haulage );
         } else if( is_river( omt_ref ) ) {
             // hauling stuff over a river is slow, because you have to portage most items
             one_way += 200 + ( 40 + haulage );
         } else {
             one_way += 40 + ( 30 + haulage );
         }
     }
     return work + one_way * trips * 1_seconds;
 }
References string_id< T >::c_str(), oter_t::get_type_id(), int_id< T >::id(), is_river(), coords::om, oter_type_forest_trail, overmap_buffer, and overmapbuffer::ter().
companion_travel_time_calc() [2/2]
static time_duration companion_travel_time_calc (const tripoint_abs_omt & pos, const tripoint_abs_omt & tgt, time_duration work, int trips = 1, int haulage = 0) static
Can be used to calculate total trip time for an NPC mission or just the traveling portion.
Doesn't use the pathingalgorithms yet.
Parameters
omt_pos start point
omt_tgt target point
work how much time the NPC will stay at the target
trips how many trips back and forth the NPC will make
Definition at line 5087 of file faction_camp.cpp.
 {
     std::vector<tripoint_abs_omt> journey = line_to( omt_pos, omt_tgt );
     return companion_travel_time_calc( journey, work, trips, haulage );
 }
References line_to().
Referenced by basecamp::start_clearcut(), basecamp::start_combat_mission(), basecamp::start_cut_logs(), basecamp::start_fortifications(), basecamp::start_relay_hide_site(), and basecamp::start_setup_hide_site().
connection_direction_of()
point connection_direction_of (const point & dir, const recipe & making) static
Definition at line 3033 of file faction_camp.cpp.
 {
     point connection_dir = point_north;
     const std::string suffix = base_camps::all_directions.at( dir ).id.substr( 1,
                                base_camps::all_directions.at( dir ).id.length() - 2 );
     int count = 0;
     if( making.has_flag( "MAP_ROTATE_90_IF_" + suffix ) ) {
         connection_dir = point_east;
         count++;
     }
     if( making.has_flag( "MAP_ROTATE_180_IF_" + suffix ) ) {
         connection_dir = point_south;
         count++;
     }
     if( making.has_flag( "MAP_ROTATE_270_IF_" + suffix ) ) {
         connection_dir = point_west;
         count++;
     }
     if( count > 1 ) {
         popup( _( "Bug, Incorrect recipe: More than one rotation per orientation isn't valid" ) );
         return {-999, -999};
     }
     if( making.has_flag( "MAP_MIRROR_HORIZONTAL_IF_" + suffix ) ) {
         connection_dir.x = -connection_dir.x;
     }
     if( making.has_flag( "MAP_MIRROR_VERTICALL_IF_" + suffix ) ) {
         connection_dir.y = -connection_dir.y;
     }
     return connection_dir;
 }
References _, base_camps::all_directions, recipe::has_flag(), length, point_east, point_north, point_south, point_west, popup(), point::x, and point::y.
Referenced by basecamp::start_salt_water_pipe().
extract_and_check_orientation_flags()
static bool extract_and_check_orientation_flags (const recipe_id & recipe, const point & dir, bool & mirror_horizontal, bool & mirror_vertical, int & rotation, const std::string_view base_error_message, const std::string & actor) static
Definition at line 542 of file faction_camp.cpp.
 {
     mirror_horizontal = recipe->has_flag( "MAP_MIRROR_HORIZONTAL" );
     mirror_vertical = recipe->has_flag( "MAP_MIRROR_VERTICAL" );
     rotation = 0;
     std::string dir_string;
     const auto check_rotation = [&]( const std::string & flag, int rotation_value ) {
         if( recipe->has_flag( flag ) ) {
             if( rotation != 0 ) {
                 debugmsg(
                     "%s, the blueprint specifies multiple concurrent rotations, which is not "
                     "supported",
                     string_format( base_error_message, actor, recipe->get_blueprint().str() ) );
                 return false;
             }
             rotation = rotation_value;
         }
         return true;
     };
     if( !check_rotation( "MAP_ROTATE_90", 1 ) ) {
         return false;
     }
     if( !check_rotation( "MAP_ROTATE_180", 2 ) ) {
         return false;
     }
     if( !check_rotation( "MAP_ROTATE_270", 3 ) ) {
         return false;
     }
     if( dir == point_north_west ) {
         dir_string = "NW";
     } else if( dir == point_north ) {
         dir_string = "N";
     } else if( dir == point_north_east ) {
         dir_string = "NE";
     } else if( dir == point_west ) {
         dir_string = "W";
     } else if( dir == point_zero ) {
         dir_string.clear();  //  Will result in "hidden" flags that can actually affect the core.
     } else if( dir == point_east ) {
         dir_string = "E";
     } else if( dir == point_south_west ) {
         dir_string = "SW";
     } else if( dir == point_south ) {
         dir_string = "S";
     } else if( dir == point_south_east ) {
         dir_string = "SE";
     }
     if( recipe->has_flag( "MAP_MIRROR_HORIZONTAL_IF_" + dir_string ) ) {
         if( mirror_horizontal ) {
             debugmsg(
                 "%s, the blueprint specifies multiple concurrent horizontal mirroring, which is "
                 "not supported",
                 string_format( base_error_message, actor, recipe->get_blueprint().str() ) );
             return false;
         }
         mirror_horizontal = true;
     }
     if( recipe->has_flag( "MAP_MIRROR_VERTICAL_IF_" + dir_string ) ) {
         if( mirror_vertical ) {
             debugmsg(
                 "%s, the blueprint specifies multiple concurrent vertical mirroring, which is not "
                 "supported",
                 string_format( base_error_message, actor, recipe->get_blueprint().str() ) );
             return false;
         }
         mirror_vertical = true;
     }
     if( !check_rotation( "MAP_ROTATE_90_IF_" + dir_string, 1 ) ) {
         return false;
     }
     if( !check_rotation( "MAP_ROTATE_180_IF_" + dir_string, 2 ) ) {
         return false;
     }
     if( !check_rotation( "MAP_ROTATE_270_IF_" + dir_string, 3 ) ) {
         return false;
     }
     return true;
 }
References debugmsg, recipe::get_blueprint(), recipe::has_flag(), point_east, point_north, point_north_east, point_north_west, point_south, point_south_east, point_south_west, point_west, point_zero, string_id< T >::str(), and string_format().
Referenced by basecamp::start_upgrade(), basecamp::survey_return(), and basecamp::upgrade_return().
farm_action()
static std::pair<size_t, std::string> farm_action (const tripoint_abs_omt & omt_tgt, farm_ops op, const npc_ptr & comp = nullptr) static
Survival increases number of plants harvested from a seed
Definition at line 3547 of file faction_camp.cpp.
 {
     size_t plots_cnt = 0;
     std::string crops;
     const auto is_dirtmound = []( const tripoint & pos, tinymap & bay1, tinymap & bay2 ) {
         return ( bay1.ter( pos ) == ter_t_dirtmound ) && ( !bay2.has_furn( pos ) );
     };
     const auto is_unplowed = []( const tripoint & pos, tinymap & farm_map ) {
         const ter_id &farm_ter = farm_map.ter( pos );
         return farm_ter->has_flag( ter_furn_flag::TFLAG_PLOWABLE );
     };
     std::set<std::string> plant_names;
     std::vector<item *> seed_inv;
     if( comp ) {
         seed_inv = comp->companion_mission_inv.items_with( farm_valid_seed );
     }
     // farm_map is what the area actually looks like
     tinymap farm_map;
     farm_map.load( omt_tgt, false );
     // farm_json is what the area should look like according to jsons (loaded on demand)
     std::unique_ptr<fake_map> farm_json;
     tripoint mapmin = tripoint( 0, 0, omt_tgt.z() );
     tripoint mapmax = tripoint( 2 * SEEX - 1, 2 * SEEY - 1, omt_tgt.z() );
     bool done_planting = false;
     Character &player_character = get_player_character();
     map &here = get_map();
     for( const tripoint &pos : farm_map.points_in_rectangle( mapmin, mapmax ) ) {
         if( done_planting ) {
             break;
         }
         switch( op ) {
             case farm_ops::plow: {
                 if( !farm_json ) {
                     farm_json = std::make_unique<fake_map>();
                     mapgendata dat( omt_tgt, *farm_json->cast_to_map(), 0, calendar::turn, nullptr );
                     if( !run_mapgen_func( dat.terrain_type()->get_mapgen_id(), dat ) ) {
                         debugmsg( "Failed to run mapgen for farm map" );
                         break;
                     }
                 }
                 // Needs to be plowed to match json
                 if( is_dirtmound( pos, *farm_json, farm_map ) && is_unplowed( pos, farm_map ) ) {
                     plots_cnt += 1;
                     if( comp ) {
                         farm_map.ter_set( pos, ter_t_dirtmound );
                     }
                 }
                 break;
             }
             case farm_ops::plant:
                 if( is_dirtmound( pos, farm_map, farm_map ) ) {
                     plots_cnt += 1;
                     if( comp ) {
                         if( seed_inv.empty() ) {
                             done_planting = true;
                             break;
                         }
                         item *tmp_seed = seed_inv.back();
                         seed_inv.pop_back();
                         std::list<item> used_seed;
                         used_seed.push_back( *tmp_seed );
                         if( tmp_seed->count_by_charges() ) {
                             tmp_seed->charges -= 1;
                             if( tmp_seed->charges > 0 ) {
                                 seed_inv.push_back( tmp_seed );
                             }
                         }
                         used_seed.front().set_age( 0_turns );
                         farm_map.add_item_or_charges( pos, used_seed.front() );
                         farm_map.set( pos, ter_t_dirt, furn_f_plant_seed );
                         if( !tmp_seed->count_by_charges() ) {
                             comp->companion_mission_inv.remove_item( tmp_seed );
                         }
                     }
                 }
                 break;
             case farm_ops::harvest:
                 if( farm_map.furn( pos ) == furn_f_plant_harvest ) {
                     // Can't use item_stack::only_item() since there might be fertilizer
                     map_stack items = farm_map.i_at( pos );
                     const map_stack::iterator seed = std::find_if( items.begin(), items.end(), []( const item & it ) {
                         return it.is_seed();
                     } );
                     if( seed != items.end() && farm_valid_seed( *seed ) ) {
                         plots_cnt += 1;
                         if( comp ) {
                             int skillLevel = round( comp->get_skill_level( skill_survival ) );
                             ///\EFFECT_SURVIVAL increases number of plants harvested from a seed
                             int plant_count = rng( skillLevel / 2, skillLevel );
                             plant_count *= farm_map.furn( pos )->plant->harvest_multiplier;
                             plant_count = std::min( std::max( plant_count, 1 ), 12 );
                             int seed_cnt = std::max( 1, rng( plant_count / 4, plant_count / 2 ) );
                             for( item &i : iexamine::get_harvest_items( *seed->type, plant_count,
                                     seed_cnt, true ) ) {
                                 here.add_item_or_charges( player_character.pos(), i );
                             }
                             farm_map.i_clear( pos );
                             farm_map.furn_set( pos, furn_str_id::NULL_ID() );
                             farm_map.ter_set( pos, ter_t_dirt );
                         } else {
                             plant_names.insert( item::nname( itype_id( seed->type->seed->fruit_id ) ) );
                         }
                     }
                 }
                 break;
             default:
                 // let the callers handle no op argument
                 break;
         }
     }
     if( comp ) {
         farm_map.save();
     }
     int total_c = 0;
     for( const std::string &i : plant_names ) {
         if( total_c < 5 ) {
             crops += "    " + i + "\n";
             total_c++;
         } else if( total_c == 5 ) {
             crops += _( "+ more\n" );
             break;
         }
     }
     return std::make_pair( plots_cnt, crops );
 }
References _, tinymap::add_item_or_charges(), map::add_item_or_charges(), item_stack::begin(), item::charges, npc::companion_mission_inv, item::count_by_charges(), debugmsg, item_stack::end(), farm_valid_seed(), tinymap::furn(), furn_f_plant_harvest, furn_f_plant_seed, tinymap::furn_set(), iexamine::get_harvest_items(), get_map(), oter_t::get_mapgen_id(), get_player_character(), Character::get_skill_level(), harvest, map_data_common_t::has_flag(), tinymap::i_at(), tinymap::i_clear(), visitable::items_with(), tinymap::load(), max(), min(), item::nname(), string_id< furn_t >::NULL_ID(), plant, furn_t::plant, plow, tinymap::points_in_rectangle(), Creature::pos(), math_opers::pos(), inventory::remove_item(), rng(), round(), run_mapgen_func(), tinymap::save(), iuse::seed(), SEEX, SEEY, tinymap::set(), skill_survival, tinymap::ter_set(), ter_t_dirt, ter_t_dirtmound, mapgendata::terrain_type(), TFLAG_PLOWABLE, calendar::turn, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by basecamp::farm_description(), basecamp::farm_return(), and basecamp::start_farm_op().
farm_valid_seed()
static bool farm_valid_seed (const item & itm) static
Definition at line 3542 of file faction_camp.cpp.
 {
     return itm.is_seed() && itm.typeId() != itype_marloss_seed && itm.typeId() != itype_fungal_seeds;
 }
References item::is_seed(), itype_fungal_seeds, itype_marloss_seed, and item::typeId().
Referenced by farm_action().
get_basecamp()
static std::optional<basecamp *> get_basecamp (npc & p, const std::string_view camp_type = "default") static
Definition at line 638 of file faction_camp.cpp.
 {
     tripoint_abs_omt omt_pos = p.global_omt_location();
     std::optional<basecamp *> bcp = overmap_buffer.find_camp( omt_pos.xy() );
     if( bcp ) {
         return bcp;
     }
     get_map().add_camp( omt_pos, "faction_camp" );
     bcp = overmap_buffer.find_camp( omt_pos.xy() );
     if( !bcp ) {
         return std::nullopt;
     }
     basecamp *temp_camp = *bcp;
     temp_camp->set_owner( p.get_fac_id() );
     temp_camp->define_camp( omt_pos, camp_type );
     return temp_camp;
 }
References map::add_camp(), basecamp::define_camp(), overmapbuffer::find_camp(), npc::get_fac_id(), get_map(), Creature::global_omt_location(), overmap_buffer, basecamp::set_owner(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by talk_function::basecamp_mission(), and talk_function::start_camp().
getAverageJoe()
static const npc& getAverageJoe () static
Definition at line 5669 of file faction_camp.cpp.
 {
     static npc averageJoe;
     return averageJoe;
 }
Referenced by basecamp::distribute_food().
mission_ui_activity_of()
static std::string mission_ui_activity_of (const mission_id & miss_id) static
Definition at line 351 of file faction_camp.cpp.
 {
     const std::string dir_abbr = base_camps::all_directions.at(
                                      miss_id.dir.value() ).bracket_abbr.translated();
     switch( miss_id.id ) {
         case No_Mission:
             //  Should only happen for the unhiding functionality
             return _( "Obsolete mission" );
         case Camp_Distribute_Food:
             return _( "Distribute Food" );
         case Camp_Determine_Leadership:
             return _( "Choose New Leader" );
         case Camp_Have_Meal:
             return _( "Have A Meal" );
         case Camp_Hide_Mission:
             return _( "Hide Mission(s)" );
         case Camp_Reveal_Mission:
             return _( "Reveal Hidden Mission(s)" );
         case Camp_Assign_Jobs:
             return _( "Assign Jobs" );
         case Camp_Assign_Workers:
             return _( "Assign Workers" );
         case Camp_Abandon:
             return _( "Abandon Camp" );
         case Camp_Upgrade:
             return dir_abbr + _( " Upgrade Camp " );
         case Camp_Crafting:
             return dir_abbr + _( " Crafting" );
         case Camp_Gather_Materials:
             return dir_abbr + _( " Gather Materials" );
         case Camp_Collect_Firewood:
             return dir_abbr + _( " Collect Firewood" );
         case Camp_Menial:
             return dir_abbr + _( " Menial Labor" );
         case Camp_Survey_Field:
             return _( "Survey terrain and try to convert it to Field" );
         case Camp_Survey_Expansion:
             return _( "Expand Base" );
         case Camp_Cut_Logs:
             return dir_abbr + _( " Cut Logs" );
         case Camp_Clearcut:
             return dir_abbr + _( " Clear a forest" );
         case Camp_Setup_Hide_Site:
             return dir_abbr + _( " Setup Hide Site" );
         case Camp_Relay_Hide_Site:
             return dir_abbr + _( " Relay Hide Site" );
         case Camp_Foraging:
             return dir_abbr + _( " Forage for plants" );
         case Camp_Trapping:
             return dir_abbr + _( " Trap Small Game" );
         case Camp_Hunting:
             return dir_abbr + _( " Hunt Large Animals" );
         case Camp_OM_Fortifications:
             if( miss_id.parameters == camp_om_fortifications_trench_parameter ) {
                 return dir_abbr + _( " Construct Map Fortifications" );
             } else {
                 return dir_abbr + _( " Construct Spiked Trench" );
             }
         case Camp_Recruiting:
             return dir_abbr + _( " Recruit Companions" );
         case Camp_Scouting:
             return dir_abbr + _( " Scout Mission" );
         case Camp_Combat_Patrol:
             return dir_abbr + _( " Combat Patrol" );
         case Camp_Plow:
             return dir_abbr + _( " Plow Fields" );
         case Camp_Plant:
             return dir_abbr + _( " Plant Fields" );
         case Camp_Harvest:
             return dir_abbr + _( " Harvest Fields" );
         case Camp_Chop_Shop:  //  Obsolete removed during 0.E
             return _( " Chop Shop.  Obsolete.  Can only be recalled" );
         //  Actions that won't be used here
         case Scavenging_Patrol_Job:
         case Scavenging_Raid_Job:
         case Menial_Job:
         case Carpentry_Job:
         case Forage_Job:
         case Caravan_Commune_Center_Job:
         case Camp_Emergency_Recall:
         default:
             return "";
     }
 }
References _, base_camps::all_directions, Camp_Abandon, Camp_Assign_Jobs, Camp_Assign_Workers, Camp_Chop_Shop, Camp_Clearcut, Camp_Collect_Firewood, Camp_Combat_Patrol, Camp_Crafting, Camp_Cut_Logs, Camp_Determine_Leadership, Camp_Distribute_Food, Camp_Emergency_Recall, Camp_Foraging, Camp_Gather_Materials, Camp_Harvest, Camp_Have_Meal, Camp_Hide_Mission, Camp_Hunting, Camp_Menial, Camp_OM_Fortifications, camp_om_fortifications_trench_parameter, Camp_Plant, Camp_Plow, Camp_Recruiting, Camp_Relay_Hide_Site, Camp_Reveal_Mission, Camp_Scouting, Camp_Setup_Hide_Site, Camp_Survey_Expansion, Camp_Survey_Field, Camp_Trapping, Camp_Upgrade, Caravan_Commune_Center_Job, Carpentry_Job, mission_id::dir, Forage_Job, mission_id::id, Menial_Job, No_Mission, mission_id::parameters, Scavenging_Patrol_Job, and Scavenging_Raid_Job.
Referenced by basecamp::name_display_of(), and update_emergency_recall().
om_carry_weight_to_trips() [1/2]
int om_carry_weight_to_trips (const units::mass & mass, const units::volume & volume, const units::mass & carry_mass, const units::volume & carry_volume) static
Definition at line 5120 of file faction_camp.cpp.
 {
     int trips_m = 1 + mass / carry_mass;
     int trips_v = 1 + volume / carry_volume;
     // return the number of round trips
     return 2 * std::max( trips_m, trips_v );
 }
References max().
om_carry_weight_to_trips() [2/2]
int om_carry_weight_to_trips (const units::mass & total_mass, const units::volume & total_volume, const npc_ptr & comp = nullptr) static
Determines how many trips it takes to move mass and volume of items with carry_mass and carry_volume moved per trip.
Definition at line 5129 of file faction_camp.cpp.
 {
     units::mass max_m = comp ? comp->weight_capacity() - comp->weight_carried() : 60_kilogram;
     //Assume an additional pack will be carried in addition to normal gear
     units::volume sack_v = item( itype_duffelbag ).get_total_capacity();
     units::volume max_v = comp ? comp->free_space() : sack_v;
     max_v += sack_v;
     return om_carry_weight_to_trips( total_mass, total_volume, max_m, max_v );
 }
References item::get_total_capacity(), and itype_duffelbag.
Referenced by basecamp::start_relay_hide_site(), and basecamp::start_setup_hide_site().
om_companion_path()
static std::vector<tripoint_abs_omt> om_companion_path (const tripoint_abs_omt & start, int range_start = 90, bool bounce = true) static
Definition at line 5140 of file faction_camp.cpp.
 {
     std::vector<tripoint_abs_omt> scout_points;
     tripoint_abs_omt last = start;
     int range = range_start;
     int def_range = range_start;
     while( range > 3 ) {
         tripoint_abs_omt spt = om_target_tile( last, 0, range, {}, ot_match_type::exact, false, true, last,
                                                false );
         if( spt == tripoint_abs_omt( -999, -999, -999 ) ) {
             scout_points.clear();
             return scout_points;
         }
         if( last == spt ) {
             break;
         }
         std::vector<tripoint_abs_omt> note_pts = line_to( last, spt );
         scout_points.insert( scout_points.end(), note_pts.begin(), note_pts.end() );
         om_line_mark( last, spt );
         range -= rl_dist( spt.xy(), last.xy() );
         last = spt;
         const oter_id &omt_ref = overmap_buffer.ter( last );
         if( bounce && omt_ref.id() == oter_faction_hide_site_0 ) {
             range = def_range * .75;
             def_range = range;
         }
     }
     for( tripoint_abs_omt &pt : scout_points ) {
         om_line_mark( pt, pt, false );
     }
     return scout_points;
 }
References exact, int_id< T >::id(), last, line_to(), om_line_mark(), om_target_tile(), oter_faction_hide_site_0, overmap_buffer, rl_dist(), overmapbuffer::ter(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by basecamp::start_combat_mission().
om_cutdown_trees()
static int om_cutdown_trees (const tripoint_abs_omt & omt_tgt, int chance = 100, bool estimate = false, bool force_cut_trunk = true) static
Definition at line 4820 of file faction_camp.cpp.
 {
     smallmap target_bay;
     target_bay.load( omt_tgt, false );
     int harvested = 0;
     int total = 0;
     tripoint mapmin = tripoint( 0, 0, omt_tgt.z() );
     tripoint mapmax = tripoint( 2 * SEEX - 1, 2 * SEEY - 1, omt_tgt.z() + 1 );
     for( const tripoint &p : target_bay.points_in_rectangle( mapmin, mapmax ) ) {
         if( target_bay.ter( p ).obj().has_flag( ter_furn_flag::TFLAG_TREE ) && rng( 0, 100 ) < chance ) {
             total++;
             if( estimate ) {
                 continue;
             }
             // get a random number that is either 1 or -1
             point dir( 3 * ( 2 * rng( 0, 1 ) - 1 ) + rng( -1, 1 ), 3 * rng( -1, 1 ) + rng( -1, 1 ) );
             target_bay.cut_down_tree( tripoint_omt_ms( p ), dir );
             target_bay.collapse_at( p, true, true, false );
             harvested++;
         }
     }
     if( estimate ) {
         return total;
     }
     if( !force_cut_trunk ) {
         target_bay.save();
         return harvested;
     }
     // having cut down the trees, cut the trunks into logs
     for( const tripoint &p : target_bay.points_in_rectangle( mapmin, mapmax ) ) {
         if( target_bay.ter( p ) == ter_t_trunk || target_bay.ter( p ) == ter_t_stump ) {
             target_bay.ter_set( p, ter_t_dirt );
             target_bay.spawn_item( p, itype_log, rng( 2, 3 ), 0, calendar::turn );
             harvested++;
         }
     }
     target_bay.save();
     return harvested;
 }
References tinymap::collapse_at(), smallmap::cut_down_tree(), map_data_common_t::has_flag(), itype_log, tinymap::load(), int_id< T >::obj(), tinymap::points_in_rectangle(), rng(), tinymap::save(), SEEX, SEEY, tinymap::spawn_item(), tinymap::ter(), tinymap::ter_set(), ter_t_dirt, ter_t_stump, ter_t_trunk, TFLAG_TREE, calendar::turn, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by om_cutdown_trees_est(), om_cutdown_trees_logs(), and om_cutdown_trees_trunks().
om_cutdown_trees_est()
static int om_cutdown_trees_est (const tripoint_abs_omt & omt_tgt, int chance = 100) static
Definition at line 4808 of file faction_camp.cpp.
 {
     return om_cutdown_trees( omt_tgt, chance, true, false );
 }
References om_cutdown_trees().
Referenced by change_cleared_terrain(), basecamp::start_clearcut(), and basecamp::start_cut_logs().
om_cutdown_trees_logs()
static int om_cutdown_trees_logs (const tripoint_abs_omt & omt_tgt, int chance = 100) static
Definition at line 4812 of file faction_camp.cpp.
 {
     return om_cutdown_trees( omt_tgt, chance, false, true );
 }
References om_cutdown_trees().
Referenced by basecamp::start_cut_logs().
om_cutdown_trees_trunks()
static int om_cutdown_trees_trunks (const tripoint_abs_omt & omt_tgt, int chance = 100) static
Definition at line 4816 of file faction_camp.cpp.
 {
     return om_cutdown_trees( omt_tgt, chance, false, false );
 }
References om_cutdown_trees().
Referenced by basecamp::start_clearcut().
om_harvest_itm()
static mass_volume om_harvest_itm (const npc_ptr & comp, const tripoint_abs_omt & omt_tgt, int chance = 100, bool take = true) static
Collects all items in omt_tgt with a chance between 0 - 1.0, returns total mass and volume take, whether you take the item or count it.
Definition at line 4862 of file faction_camp.cpp.
 {
     tinymap target_bay;
     target_bay.load( omt_tgt, false );
     units::mass harvested_m = 0_gram;
     units::volume harvested_v = 0_ml;
     units::mass total_m = 0_gram;
     units::volume total_v = 0_ml;
     int total_num = 0;
     int harvested_num = 0;
     tripoint mapmin = tripoint( 0, 0, omt_tgt.z() );
     tripoint mapmax = tripoint( 2 * SEEX - 1, 2 * SEEY - 1, omt_tgt.z() );
     for( const tripoint &p : target_bay.points_in_rectangle( mapmin, mapmax ) ) {
         for( const item &i : target_bay.i_at( p ) ) {
             if( !i.made_of_from_type( phase_id::LIQUID ) ) {
                 total_m += i.weight( true );
                 total_v += i.volume( true );
                 total_num += 1;
                 if( take && x_in_y( chance, 100 ) ) {
                     if( comp ) {
                         comp->companion_mission_inv.push_back( i );
                     }
                     harvested_m += i.weight( true );
                     harvested_v += i.volume( true );
                     harvested_num += 1;
                 }
             }
         }
         if( take ) {
             target_bay.i_clear( p );
         }
     }
     target_bay.save();
     mass_volume results;
     if( take ) {
         results.wgt = harvested_m;
         results.vol = harvested_v;
         results.count = harvested_num;
     } else {
         results.wgt = total_m;
         results.vol = total_v;
         results.count = total_num;
     }
     return results;
 }
References mass_volume::count, tinymap::i_at(), tinymap::i_clear(), LIQUID, tinymap::load(), tinymap::points_in_rectangle(), tinymap::save(), SEEX, SEEY, mass_volume::vol, mass_volume::wgt, x_in_y(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by basecamp::start_cut_logs().
om_harvest_ter()
static int om_harvest_ter (npc & comp, const tripoint_abs_omt & omt_tgt, const ter_id & t, int chance = 100, bool estimate = false, bool bring_back = true) static
Counts or destroys and drops the bash items of all terrain that matches t in the map tile.
Parameters
comp NPC companion
omt_tgt the targeted OM tile
t terrain you are looking for
chance chance of destruction, 0 to 100
estimate if true, non-destructive count of the furniture
bring_back force the destruction of the furniture and bring back the drop items
Definition at line 4775 of file faction_camp.cpp.
 {
     const ter_t &ter_tgt = t.obj();
     tinymap target_bay;
     target_bay.load( omt_tgt, false );
     int harvested = 0;
     int total = 0;
     tripoint mapmin = tripoint( 0, 0, omt_tgt.z() );
     tripoint mapmax = tripoint( 2 * SEEX - 1, 2 * SEEY - 1, omt_tgt.z() );
     for( const tripoint &p : target_bay.points_in_rectangle( mapmin, mapmax ) ) {
         if( target_bay.ter( p ) == t && x_in_y( chance, 100 ) ) {
             total++;
             if( estimate ) {
                 continue;
             }
             if( bring_back ) {
                 for( const item &itm : item_group::items_from( ter_tgt.bash.drop_group,
                         calendar::turn ) ) {
                     comp.companion_mission_inv.push_back( itm );
                 }
                 harvested++;
                 target_bay.ter_set( p, ter_tgt.bash.ter_set );
             }
         }
     }
     target_bay.save();
     if( bring_back ) {
         return harvested;
     }
     return total;
 }
References map_data_common_t::bash, npc::companion_mission_inv, map_bash_info::drop_group, item_group::items_from(), tinymap::load(), int_id< T >::obj(), tinymap::points_in_rectangle(), inventory::push_back(), tinymap::save(), SEEX, SEEY, tinymap::ter(), tinymap::ter_set(), map_bash_info::ter_set, calendar::turn, x_in_y(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by om_harvest_ter_break(), om_harvest_ter_est(), and basecamp::start_cut_logs().
om_harvest_ter_break()
static int om_harvest_ter_break (npc & comp, const tripoint_abs_omt & omt_tgt, const ter_id & t, int chance = 100) static
Definition at line 4771 of file faction_camp.cpp.
 {
     return om_harvest_ter( comp, omt_tgt, t, chance, false, false );
 }
References om_harvest_ter().
Referenced by basecamp::start_clearcut().
om_harvest_ter_est()
static int om_harvest_ter_est (npc & comp, const tripoint_abs_omt & omt_tgt, const ter_id & t, int chance = 100) static
Definition at line 4767 of file faction_camp.cpp.
 {
     return om_harvest_ter( comp, omt_tgt, t, chance, true, false );
 }
References om_harvest_ter().
Referenced by basecamp::start_clearcut(), and basecamp::start_cut_logs().
om_line_mark()
static void om_line_mark (const tripoint_abs_omt & origin, const tripoint_abs_omt & dest, bool add_notes = true, const std::string & message = "R;X: PATH") static
Definition at line 5019 of file faction_camp.cpp.
 {
     std::vector<tripoint_abs_omt> note_pts = line_to( origin, dest );
     for( tripoint_abs_omt &pt : note_pts ) {
         if( add_notes ) {
             if( !overmap_buffer.has_note( pt ) ) {
                 overmap_buffer.add_note( pt, message );
             }
         } else {
             if( overmap_buffer.has_note( pt ) && overmap_buffer.note( pt ) == message ) {
                 overmap_buffer.delete_note( pt );
             }
         }
     }
 }
References overmapbuffer::add_note(), overmapbuffer::delete_note(), overmapbuffer::has_note(), line_to(), mapgen_defer::message, overmapbuffer::note(), and overmap_buffer.
Referenced by om_companion_path(), and om_target_tile().
om_range_mark()
static void om_range_mark (const tripoint_abs_omt & origin, int range, bool add_notes = true, const std::string & message = "Y;X: MAX RANGE") static
Definition at line 4978 of file faction_camp.cpp.
 {
     std::vector<tripoint_abs_omt> note_pts;
     if( trigdist ) {
         for( const tripoint_abs_omt &pos : points_on_radius_circ( origin, range ) ) {
             note_pts.emplace_back( pos );
         }
     } else {
         //North Limit
         for( int x = origin.x() - range; x < origin.x() + range + 1; x++ ) {
             note_pts.emplace_back( x, origin.y() - range, origin.z() );
         }
         //South
         for( int x = origin.x() - range; x < origin.x() + range + 1; x++ ) {
             note_pts.emplace_back( x, origin.y() + range, origin.z() );
         }
         //West
         for( int y = origin.y() - range; y < origin.y() + range + 1; y++ ) {
             note_pts.emplace_back( origin.x() - range, y, origin.z() );
         }
         //East
         for( int y = origin.y() - range; y < origin.y() + range + 1; y++ ) {
             note_pts.emplace_back( origin.x() + range, y, origin.z() );
         }
     }
     for( tripoint_abs_omt &pt : note_pts ) {
         if( add_notes ) {
             if( !overmap_buffer.has_note( pt ) ) {
                 overmap_buffer.add_note( pt, message );
             }
         } else {
             if( overmap_buffer.has_note( pt ) && overmap_buffer.note( pt ) == message ) {
                 overmap_buffer.delete_note( pt );
             }
         }
     }
 }
References overmapbuffer::add_note(), overmapbuffer::delete_note(), overmapbuffer::has_note(), mapgen_defer::message, overmapbuffer::note(), overmap_buffer, points_on_radius_circ(), math_opers::pos(), and trigdist.
Referenced by om_target_tile().
om_set_hide_site()
static bool om_set_hide_site (npc & comp, const tripoint_abs_omt & omt_tgt, const drop_locations & itms, const drop_locations & itms_rem = {}) static
Creates an improvised shelter at omt_tgt and dumps the itms into the building.
Definition at line 5037 of file faction_camp.cpp.
 {
     tinymap target_bay;
     target_bay.load( omt_tgt, false );
     target_bay.ter_set( relay_site_stash, ter_t_improvised_shelter );
     for( drop_location it : itms_rem ) {
         item *i = it.first.get_item();
         item split_item;
         if( i->count() != it.second ) { //  We're not moving the whole stack, and so have to split it.
             split_item = i->split( it.second );
         }
         if( split_item.is_null() ) {
             comp.companion_mission_inv.add_item( *i );
             target_bay.i_rem( relay_site_stash, i );
         } else {
             comp.companion_mission_inv.add_item( split_item );
         }
     }
     for( drop_location it : itms ) {
         item *i = it.first.get_item();
         item split_item;
         if( i->count() != it.second ) { //  We're not moving the whole stack, and so have to split it.
             split_item = i->split( it.second );
         }
         if( split_item.is_null() ) {
             split_item = *i;  // create a copy of the original item, move that, and then destroy the original,
             // as drop_location knows how to do that so we don't have to search the ground and inventory for it.
             target_bay.add_item_or_charges( relay_site_stash, split_item );
             it.first.remove_item();
         } else {
             target_bay.add_item_or_charges( relay_site_stash, split_item );
         }
     }
     target_bay.save();
     overmap_buffer.ter_set( omt_tgt, oter_id( faction_hide_site_0_string ) );
     overmap_buffer.reveal( omt_tgt.xy(), 3, 0 );
     return true;
 }
References inventory::add_item(), tinymap::add_item_or_charges(), npc::companion_mission_inv, item::count(), faction_hide_site_0_string, tinymap::i_rem(), item::is_null(), tinymap::load(), overmap_buffer, relay_site_stash, visitable::remove_item(), overmapbuffer::reveal(), tinymap::save(), item::split(), tinymap::ter_set(), overmapbuffer::ter_set(), ter_t_improvised_shelter, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by basecamp::start_relay_hide_site(), and basecamp::start_setup_hide_site().
om_target_tile()
static tripoint_abs_omt om_target_tile (const tripoint_abs_omt & omt_pos, int min_range = 1, int range = 1, const std::vector< std::string > & possible_om_types = {}, ot_match_type match_type = ot_match_type::exact, bool must_see = true, bool popup_notice = true, const tripoint_abs_omt & source = tripoint_abs_omt(-999, -999, -999), bool bounce = false) static
Opens the overmap so that you can select points for missions or constructions.
Parameters
omt_pos where your camp is, used for calculating travel distances
min_range
range max number of OM tiles the user can select
possible_om_types requires the user to reselect if the OM picked isn't in the list
must_see whether the user can select points in the unknown/fog of war
popup_notice toggles if the user should be shown ranges before being allowed to pick
source if you are selecting multiple points this is where the OM is centered to start
bounce
Definition at line 4909 of file faction_camp.cpp.
 {
     bool errors = false;
     if( popup_notice ) {
         popup( _( "Select a location between  %d and  %d tiles away." ), min_range, range );
     }
     std::vector<std::string> bounce_locations = { faction_hide_site_0_string };
     tripoint_abs_omt where;
     om_range_mark( omt_pos, range );
     om_range_mark( omt_pos, min_range, true, "Y;X: MIN RANGE" );
     if( source == tripoint_abs_omt( -999, -999, -999 ) ) {
         where = ui::omap::choose_point();
     } else {
         where = ui::omap::choose_point( source );
     }
     om_range_mark( omt_pos, range, false );
     om_range_mark( omt_pos, min_range, false, "Y;X: MIN RANGE" );
     if( where == overmap::invalid_tripoint ) {
         return tripoint_abs_omt( -999, -999, -999 );
     }
     int dist = rl_dist( where.xy(), omt_pos.xy() );
     if( dist > range || dist < min_range ) {
         popup( _( "You must select a target between %d and %d range from the base.  Range: %d" ),
                min_range, range, dist );
         errors = true;
     }
     tripoint_abs_omt omt_tgt = where;
     const oter_id &omt_ref = overmap_buffer.ter( omt_tgt );
     if( must_see && !overmap_buffer.seen( omt_tgt ) ) {
         errors = true;
         popup( _( "You must be able to see the target that you select." ) );
     }
     if( !errors ) {
         for( const std::string &pos_om : bounce_locations ) {
             if( bounce && omt_ref.id().c_str() == pos_om && range > 5 ) {
                 if( query_yn( _( "Do you want to bounce off this location to extend range?" ) ) ) {
                     om_line_mark( omt_pos, omt_tgt );
                     tripoint_abs_omt dest =
                         om_target_tile( omt_tgt, 2, range * .75, possible_om_types, match_type, true, false,
                                         omt_tgt, true );
                     om_line_mark( omt_pos, omt_tgt, false );
                     return dest;
                 }
             }
         }
         if( possible_om_types.empty() ) {
             return omt_tgt;
         }
         for( const std::string &pos_om : possible_om_types ) {
             if( is_ot_match( pos_om, omt_ref, match_type ) ) {
                 return omt_tgt;
             }
         }
     }
     return om_target_tile( omt_pos, min_range, range, possible_om_types, match_type );
 }
References _, string_id< T >::c_str(), ui::omap::choose_point(), faction_hide_site_0_string, int_id< T >::id(), overmap::invalid_tripoint, is_ot_match(), om_line_mark(), om_range_mark(), overmap_buffer, popup(), query_yn(), rl_dist(), overmapbuffer::seen(), overmapbuffer::ter(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by om_companion_path(), basecamp::start_clearcut(), basecamp::start_cut_logs(), basecamp::start_fortifications(), basecamp::start_relay_hide_site(), and basecamp::start_setup_hide_site().
salt_water_pipe_orientation_adjustment()
static void salt_water_pipe_orientation_adjustment (const point & dir, bool & orthogonal, bool & mirror_vertical, bool & mirror_horizontal, int & rotation) static
Definition at line 3067 of file faction_camp.cpp.
 {
     orthogonal = true;
     mirror_horizontal = false;
     mirror_vertical = false;
     rotation = 0;
     switch( base_camps::all_directions.at( dir ).tab_order ) {
         case base_camps::tab_mode::TAB_MAIN: //  Should not happen. We would have had to define the same point twice.
         case base_camps::tab_mode::TAB_N:    //  This is the reference direction for orthogonal orientations.
             break;
         case base_camps::tab_mode::TAB_NE:
             orthogonal = false;
             break;  //  This is the reference direction for diagonal orientations.
         case base_camps::tab_mode::TAB_E:
             rotation = 1;
             break;
         case base_camps::tab_mode::TAB_SE:
             orthogonal = false;
             rotation = 1;
             break;
         case base_camps::tab_mode::TAB_S:
             mirror_vertical = true;
             break;
         case base_camps::tab_mode::TAB_SW:
             orthogonal = false;
             rotation = 2;
             break;
         case base_camps::tab_mode::TAB_W:
             rotation = 1;
             mirror_vertical = true;
             break;
         case base_camps::tab_mode::TAB_NW:
             orthogonal = false;
             rotation = 3;
             break;
     }
 }
References base_camps::all_directions, base_camps::TAB_E, base_camps::TAB_MAIN, base_camps::TAB_N, base_camps::TAB_NE, base_camps::TAB_NW, base_camps::TAB_S, base_camps::TAB_SE, base_camps::TAB_SW, and base_camps::TAB_W.
Referenced by basecamp::common_salt_water_pipe_construction(), basecamp::salt_water_pipe_return(), and basecamp::salt_water_pipe_swamp_return().
salt_water_pipe_segment_of()
int salt_water_pipe_segment_of (const recipe & making) static
Definition at line 2985 of file faction_camp.cpp.
 {
     int segment_number = -1;
     const auto &requirements = making.blueprint_requires();
     for( auto const &element : requirements ) {
         if( element.first.substr( 0, salt_water_pipe_string_base.length() ) == salt_water_pipe_string_base
             &&
             element.first.substr( element.first.length() - salt_water_pipe_string_suffix.length(),
                                   salt_water_pipe_string_suffix.length() ) == salt_water_pipe_string_suffix ) {
             try {
                 segment_number = stoi( element.first.substr( salt_water_pipe_string_base.length(),
                                        element.first.length() - salt_water_pipe_string_suffix.length() - 1 ) );
             } catch( ... ) {
                 std::string msg = "Recipe 'blueprint_requires' that matches the hard coded '";
                 msg += salt_water_pipe_string_base;
                 msg += "#";
                 msg += salt_water_pipe_string_suffix;
                 msg += "' pattern without having a number in the # position";
                 debugmsg( msg );
                 return -1;
             }
             if( segment_number < 1 || segment_number >= max_salt_water_pipe_length ) {
                 std::string msg = "Recipe 'blueprint_requires' that matches the hard coded '";
                 msg += salt_water_pipe_string_base;
                 msg += "#";
                 msg += salt_water_pipe_string_suffix;
                 msg += "' pattern with a number outside the ones supported and generated by the code";
                 debugmsg( msg );
                 return -1;
             }
         }
     }
     if( segment_number == -1 ) {
         debugmsg( "Failed to find recipe 'blueprint_requires' that matches the hard coded '" +
                   salt_water_pipe_string_base + "#" + salt_water_pipe_string_suffix + "' pattern" );
     }
     return segment_number;
 }
References recipe::blueprint_requires(), debugmsg, max_salt_water_pipe_length, salt_water_pipe_string_base, and salt_water_pipe_string_suffix.
Referenced by basecamp::continue_salt_water_pipe(), and basecamp::salt_water_pipe_return().
survive_random_encounter()
bool survive_random_encounter (npc & comp, std::string & situation, int favor, int threat) static
Definition at line 6005 of file faction_camp.cpp.
 {
     popup( _( "While %s, a silent specter approaches %s" ), situation, comp.get_name() );
     float skill_1 = comp.get_skill_level( skill_survival );
     float skill_2 = comp.get_skill_level( skill_speech );
     if( skill_1 + favor > rng( 0, 10 ) ) {
         popup( _( "%s notices the antlered horror and slips away before it gets too close." ),
                comp.get_name() );
         talk_function::companion_skill_trainer( comp, "gathering", 10_minutes, 10 - favor );
     } else if( skill_2 + favor > rng( 0, 10 ) ) {
         popup( _( "Another survivor approaches %s asking for directions." ), comp.get_name() );
         popup( _( "Fearful that he may be an agent of some hostile faction, "
                   "%s doesn't mention the camp." ), comp.get_name() );
         popup( _( "The two part on friendly terms and the survivor isn't seen again." ) );
         talk_function::companion_skill_trainer( comp, skill_recruiting, 10_minutes, 10 - favor );
     } else {
         popup( _( "%s didn't detect the ambush until it was too late!" ), comp.get_name() );
         float skill = comp.get_skill_level( skill_melee ) +
                       0.5 * comp.get_skill_level( skill_survival ) +
                       comp.get_skill_level( skill_bashing ) +
                       comp.get_skill_level( skill_cutting ) +
                       comp.get_skill_level( skill_stabbing ) +
                       comp.get_skill_level( skill_unarmed ) + comp.get_skill_level( skill_dodge );
         int monsters = rng( 0, threat );
         if( skill * rng( 8, 12 ) > ( monsters * rng( 8, 12 ) ) ) {
             if( one_in( 2 ) ) {
                 popup( _( "The bull moose charged %s from the tree line" ), comp.get_name() );
                 popup( _( "Despite being caught off guard %s was able to run away until the "
                           "moose gave up pursuit." ), comp.get_name() );
             } else {
                 popup( _( "The jabberwock grabbed %s by the arm from behind and "
                           "began to scream." ), comp.get_name() );
                 popup( _( "Terrified, %s spun around and delivered a massive kick "
                           "to the creature's torso" ), comp.get_name() );
                 popup( _( "Collapsing into a pile of gore, %s walked away unscathed" ),
                        comp.get_name() );
                 popup( _( "(Sounds like bullshit, you wonder what really happened.)" ) );
             }
             talk_function::companion_skill_trainer( comp, skill_combat, 10_minutes, 10 - favor );
         } else {
             if( one_in( 2 ) ) {
                 popup( _( "%s turned to find the hideous black eyes of a giant wasp "
                           "staring back from only a few feet away" ), comp.get_name() );
                 popup( _( "The screams were terrifying, there was nothing anyone could do." ) );
             } else {
                 popup( _( "Pieces of %s were found strewn across a few bushes." ), comp.get_name() );
                 popup( _( "(You wonder if your companions are fit to work on their own)" ) );
             }
             overmap_buffer.remove_npc( comp.getID() );
             return false;
         }
     }
     return true;
 }
References _, talk_function::companion_skill_trainer(), Character::get_name(), Character::get_skill_level(), Character::getID(), one_in(), overmap_buffer, popup(), overmapbuffer::remove_npc(), rng(), skill_bashing, skill_combat, skill_cutting, skill_dodge, skill_melee, skill_recruiting, skill_speech, skill_stabbing, skill_survival, and skill_unarmed.
Referenced by basecamp::gathering_return().
update_emergency_recall()
static bool update_emergency_recall (std::string & entry, const comp_list & npc_list, const time_duration & duration) static
Definition at line 524 of file faction_camp.cpp.
 {
     bool avail = false;
     for( const auto &comp : npc_list ) {
         const time_duration elapsed = calendar::turn - comp->companion_mission_time;
         const mission_id miss_id = comp->get_companion_mission().miss_id;
         entry += "\n  " + comp->get_name() + " [" + to_string( elapsed ) + " / " +
                  to_string( duration ) + "] " + mission_ui_activity_of( miss_id );
         avail |= elapsed >= duration;
     }
     if( avail ) {
         entry += _( "\n\nDo you wish to bring your allies back into your party?" );
     }
     return avail;
 }
References _, npc::companion_mission_time, npc::get_companion_mission(), Character::get_name(), npc_companion_mission::miss_id, mission_ui_activity_of(), to_string(), and calendar::turn.
Referenced by basecamp::get_available_missions().
update_mapgen_faction_wall_level_N_1()
static const update_mapgen_id update_mapgen_faction_wall_level_N_1 (faction_wall_level_n_1_string. c_str()) static
Referenced by apply_fortifications().
update_time_fixed()
static bool update_time_fixed (std::string & entry, const comp_list & npc_list, const time_duration & duration) static
Definition at line 508 of file faction_camp.cpp.
 {
     bool avail = false;
     for( const auto &comp : npc_list ) {
         const time_duration elapsed = calendar::turn - comp->companion_mission_time;
         entry += "\n  " +  comp->get_name() + " [" + to_string( elapsed ) + " / " +
                  to_string( duration ) + "]";
         avail |= elapsed >= duration;
     }
     if( avail ) {
         entry += _( "\n\nDo you wish to bring your allies back into your party?" );
     }
     return avail;
 }
References _, npc::companion_mission_time, Character::get_name(), to_string(), and calendar::turn.
Referenced by basecamp::get_available_missions_by_dir().
update_time_left()
static bool update_time_left (std::string & entry, const comp_list & npc_list) static
Definition at line 486 of file faction_camp.cpp.
 {
     bool avail = false;
     Character &player_character = get_player_character();
     for( const auto &comp : npc_list ) {
         entry += comp->get_name();
         if( comp->companion_mission_time_ret < calendar::turn ) {
             entry +=  _( " [DONE]\n" );
             avail = true;
         } else {
             entry += " [" +
                      to_string( comp->companion_mission_time_ret - calendar::turn ) +
                      _( " left]\n" );
             avail = player_character.has_trait( trait_DEBUG_HS );
         }
     }
     if( avail ) {
         entry += _( "\n\nDo you wish to bring your allies back into your party?" );
     }
     return avail;
 }
References _, npc::companion_mission_time_ret, Character::get_name(), get_player_character(), Character::has_trait(), to_string(), trait_DEBUG_HS, and calendar::turn.
Referenced by basecamp::get_available_missions(), and basecamp::get_available_missions_by_dir().
Variable Documentation
ACT_MOVE_LOOT
const activity_id ACT_MOVE_LOOT("ACT_MOVE_LOOT") ("ACT_MOVE_LOOT") static
Referenced by basecamp::start_menial_labor().
base_recipe_group_string
const std::string base_recipe_group_string = "BASE" static
Definition at line 211 of file faction_camp.cpp.
Referenced by basecamp::get_available_missions_by_dir(), and basecamp::handle_mission().
camp_om_fortifications_spiked_trench_parameter
const std::string camp_om_fortifications_spiked_trench_parameter static
Initial value:
=
    faction_wall_level_n_1_string
Definition at line 200 of file faction_camp.cpp.
Referenced by basecamp::get_available_missions_by_dir().
camp_om_fortifications_trench_parameter
const std::string camp_om_fortifications_trench_parameter = faction_wall_level_n_0_string static
Definition at line 199 of file faction_camp.cpp.
Referenced by basecamp::get_available_missions_by_dir(), and mission_ui_activity_of().
cook_recipe_group_string
const std::string cook_recipe_group_string = "COOK" static
Definition at line 212 of file faction_camp.cpp.
Referenced by basecamp::get_available_missions_by_dir(), and basecamp::handle_mission().
diagonal_salt_pipe_cost
const double diagonal_salt_pipe_cost = std::sqrt(2.0) static
Definition at line 2920 of file faction_camp.cpp.
Referenced by check_salt_pipe_neighbors().
faction_expansion_salt_water_pipe_base
const std::string faction_expansion_salt_water_pipe_base static
Initial value:
=
    "faction_expansion_salt_water_pipe_"
Definition at line 342 of file faction_camp.cpp.
faction_expansion_salt_water_pipe_N
const std::string faction_expansion_salt_water_pipe_N static
Initial value:
=
    faction_expansion_salt_water_pipe_base +
    "N"
Definition at line 344 of file faction_camp.cpp.
Referenced by basecamp::common_salt_water_pipe_construction(), basecamp::salt_water_pipe_return(), basecamp::start_upgrade(), and basecamp::upgrade_return().
faction_expansion_salt_water_pipe_NE
const std::string faction_expansion_salt_water_pipe_NE static
Initial value:
=
    faction_expansion_salt_water_pipe_base +
    "NE"
Definition at line 347 of file faction_camp.cpp.
Referenced by basecamp::common_salt_water_pipe_construction(), and basecamp::salt_water_pipe_return().
faction_expansion_salt_water_pipe_swamp_base
const std::string faction_expansion_salt_water_pipe_swamp_base static
Initial value:
=
    "faction_expansion_salt_water_pipe_swamp_"
Definition at line 336 of file faction_camp.cpp.
faction_expansion_salt_water_pipe_swamp_N
const std::string faction_expansion_salt_water_pipe_swamp_N static
Initial value:
=
    faction_expansion_salt_water_pipe_swamp_base + "N"
Definition at line 338 of file faction_camp.cpp.
Referenced by basecamp::common_salt_water_pipe_construction(), basecamp::salt_water_pipe_swamp_return(), basecamp::start_upgrade(), and basecamp::upgrade_return().
faction_expansion_salt_water_pipe_swamp_NE
const std::string faction_expansion_salt_water_pipe_swamp_NE static
Initial value:
=
    faction_expansion_salt_water_pipe_swamp_base + "NE"
Definition at line 340 of file faction_camp.cpp.
Referenced by basecamp::common_salt_water_pipe_construction(), and basecamp::salt_water_pipe_swamp_return().
faction_hide_site_0_string
const std::string faction_hide_site_0_string = "faction_hide_site_0" static
Definition at line 194 of file faction_camp.cpp.
Referenced by om_set_hide_site(), om_target_tile(), and basecamp::start_relay_hide_site().
faction_wall_level_n_0_string
const std::string faction_wall_level_n_0_string = "faction_wall_level_N_0" static
Definition at line 192 of file faction_camp.cpp.
Referenced by apply_fortifications(), basecamp::fortifications_return(), and basecamp::get_available_missions_by_dir().
faction_wall_level_n_1_string
const std::string faction_wall_level_n_1_string = "faction_wall_level_N_1" static
Definition at line 193 of file faction_camp.cpp.
Referenced by apply_fortifications(), basecamp::get_available_missions_by_dir(), and basecamp::start_fortifications().
farm_recipe_group_string
const std::string farm_recipe_group_string = "FARM" static
Definition at line 213 of file faction_camp.cpp.
Referenced by basecamp::get_available_missions_by_dir(), and basecamp::handle_mission().
furn_f_plant_harvest
const furn_str_id furn_f_plant_harvest("f_plant_harvest") ("f_plant_harvest") static
Referenced by farm_action().
furn_f_plant_seed
const furn_str_id furn_f_plant_seed("f_plant_seed") ("f_plant_seed") static
Referenced by farm_action().
GROUP_CAMP_HUNTING
const mongroup_id GROUP_CAMP_HUNTING("GROUP_CAMP_HUNTING") ("GROUP_CAMP_HUNTING") static
Referenced by basecamp::hunting_results().
GROUP_CAMP_HUNTING_LARGE
const mongroup_id GROUP_CAMP_HUNTING_LARGE("GROUP_CAMP_HUNTING_LARGE") ("GROUP_CAMP_HUNTING_LARGE") static
Referenced by basecamp::hunting_results().
GROUP_CAMP_TRAPPING
const mongroup_id GROUP_CAMP_TRAPPING("GROUP_CAMP_TRAPPING") ("GROUP_CAMP_TRAPPING") static
Referenced by basecamp::hunting_results().
Item_spawn_data_foraging_faction_camp_autumn
const item_group_id Item_spawn_data_foraging_faction_camp_autumn("foraging_faction_camp_autumn") ("foraging_faction_camp_autumn") static
Referenced by basecamp::gathering_return().
Item_spawn_data_foraging_faction_camp_spring
const item_group_id Item_spawn_data_foraging_faction_camp_spring("foraging_faction_camp_spring") ("foraging_faction_camp_spring") static
Referenced by basecamp::gathering_return().
Item_spawn_data_foraging_faction_camp_summer
const item_group_id Item_spawn_data_foraging_faction_camp_summer("foraging_faction_camp_summer") ("foraging_faction_camp_summer") static
Referenced by basecamp::gathering_return().
Item_spawn_data_foraging_faction_camp_winter
const item_group_id Item_spawn_data_foraging_faction_camp_winter("foraging_faction_camp_winter") ("foraging_faction_camp_winter") static
Referenced by basecamp::gathering_return().
Item_spawn_data_forest
const item_group_id Item_spawn_data_forest("forest") ("forest") static
Referenced by basecamp::gathering_description(), and basecamp::gathering_return().
Item_spawn_data_gathering_faction_camp_firewood
const item_group_id Item_spawn_data_gathering_faction_camp_firewood("gathering_faction_camp_firewood") ("gathering_faction_camp_firewood") static
Referenced by basecamp::gathering_return().
itype_duffelbag
const itype_id itype_duffelbag("duffelbag") ("duffelbag") static
Referenced by om_carry_weight_to_trips().
itype_fungal_seeds
const itype_id itype_fungal_seeds("fungal_seeds") ("fungal_seeds") static
Referenced by farm_valid_seed(), and basecamp::start_farm_op().
itype_log
const itype_id itype_log("log") ("log") static
Referenced by om_cutdown_trees().
itype_marloss_seed
const itype_id itype_marloss_seed("marloss_seed") ("marloss_seed") static
Referenced by farm_valid_seed(), and basecamp::start_farm_op().
max_salt_water_pipe_distance
const int max_salt_water_pipe_distance = 10 static
Definition at line 2913 of file faction_camp.cpp.
Referenced by check_salt_pipe_neighbors(), and basecamp::start_salt_water_pipe().
max_salt_water_pipe_length
const int max_salt_water_pipe_length static
Initial value:
=
    20
Definition at line 2914 of file faction_camp.cpp.
Referenced by salt_water_pipe_segment_of(), and basecamp::start_salt_water_pipe().
oter_dirt_road_3way_forest_east
const oter_str_id oter_dirt_road_3way_forest_east("dirt_road_3way_forest_east") ("dirt_road_3way_forest_east") static
Referenced by change_cleared_terrain().
oter_dirt_road_3way_forest_north
const oter_str_id oter_dirt_road_3way_forest_north("dirt_road_3way_forest_north") ("dirt_road_3way_forest_north") static
Referenced by change_cleared_terrain().
oter_dirt_road_3way_forest_south
const oter_str_id oter_dirt_road_3way_forest_south("dirt_road_3way_forest_south") ("dirt_road_3way_forest_south") static
Referenced by change_cleared_terrain().
oter_dirt_road_3way_forest_west
const oter_str_id oter_dirt_road_3way_forest_west("dirt_road_3way_forest_west") ("dirt_road_3way_forest_west") static
Referenced by change_cleared_terrain().
oter_dirt_road_forest_east
const oter_str_id oter_dirt_road_forest_east("dirt_road_forest_east") ("dirt_road_forest_east") static
Referenced by change_cleared_terrain().
oter_dirt_road_forest_north
const oter_str_id oter_dirt_road_forest_north("dirt_road_forest_north") ("dirt_road_forest_north") static
Referenced by change_cleared_terrain().
oter_dirt_road_forest_south
const oter_str_id oter_dirt_road_forest_south("dirt_road_forest_south") ("dirt_road_forest_south") static
Referenced by change_cleared_terrain().
oter_dirt_road_forest_west
const oter_str_id oter_dirt_road_forest_west("dirt_road_forest_west") ("dirt_road_forest_west") static
Referenced by change_cleared_terrain().
oter_dirt_road_turn_forest_east
const oter_str_id oter_dirt_road_turn_forest_east("dirt_road_turn_forest_east") ("dirt_road_turn_forest_east") static
Referenced by change_cleared_terrain().
oter_dirt_road_turn_forest_north
const oter_str_id oter_dirt_road_turn_forest_north("dirt_road_turn_forest_north") ("dirt_road_turn_forest_north") static
Referenced by change_cleared_terrain().
oter_dirt_road_turn_forest_south
const oter_str_id oter_dirt_road_turn_forest_south("dirt_road_turn_forest_south") ("dirt_road_turn_forest_south") static
Referenced by change_cleared_terrain().
oter_dirt_road_turn_forest_west
const oter_str_id oter_dirt_road_turn_forest_west("dirt_road_turn_forest_west") ("dirt_road_turn_forest_west") static
Referenced by change_cleared_terrain().
oter_faction_hide_site_0
const oter_str_id oter_faction_hide_site_0(faction_hide_site_0_string) (faction_hide_site_0_string) static
Referenced by om_companion_path().
oter_forest
const oter_str_id oter_forest("forest") ("forest") static
Referenced by change_cleared_terrain().
oter_forest_thick
const oter_str_id oter_forest_thick("forest_thick") ("forest_thick") static
Referenced by change_cleared_terrain().
oter_rural_road_3way_forest_east
const oter_str_id oter_rural_road_3way_forest_east("rural_road_3way_forest_east") ("rural_road_3way_forest_east") static
Referenced by change_cleared_terrain().
oter_rural_road_3way_forest_north
const oter_str_id oter_rural_road_3way_forest_north("rural_road_3way_forest_north") ("rural_road_3way_forest_north") static
Referenced by change_cleared_terrain().
oter_rural_road_3way_forest_south
const oter_str_id oter_rural_road_3way_forest_south("rural_road_3way_forest_south") ("rural_road_3way_forest_south") static
Referenced by change_cleared_terrain().
oter_rural_road_3way_forest_west
const oter_str_id oter_rural_road_3way_forest_west("rural_road_3way_forest_west") ("rural_road_3way_forest_west") static
Referenced by change_cleared_terrain().
oter_rural_road_forest_east
const oter_str_id oter_rural_road_forest_east("rural_road_forest_east") ("rural_road_forest_east") static
Referenced by change_cleared_terrain().
oter_rural_road_forest_north
const oter_str_id oter_rural_road_forest_north("rural_road_forest_north") ("rural_road_forest_north") static
Referenced by change_cleared_terrain().
oter_rural_road_forest_south
const oter_str_id oter_rural_road_forest_south("rural_road_forest_south") ("rural_road_forest_south") static
Referenced by change_cleared_terrain().
oter_rural_road_forest_west
const oter_str_id oter_rural_road_forest_west("rural_road_forest_west") ("rural_road_forest_west") static
Referenced by change_cleared_terrain().
oter_rural_road_turn1_forest_east
const oter_str_id oter_rural_road_turn1_forest_east("rural_road_turn1_forest_east") ("rural_road_turn1_forest_east") static
Referenced by change_cleared_terrain().
oter_rural_road_turn1_forest_north
const oter_str_id oter_rural_road_turn1_forest_north("rural_road_turn1_forest_north") ("rural_road_turn1_forest_north") static
Referenced by change_cleared_terrain().
oter_rural_road_turn1_forest_south
const oter_str_id oter_rural_road_turn1_forest_south("rural_road_turn1_forest_south") ("rural_road_turn1_forest_south") static
Referenced by change_cleared_terrain().
oter_rural_road_turn1_forest_west
const oter_str_id oter_rural_road_turn1_forest_west("rural_road_turn1_forest_west") ("rural_road_turn1_forest_west") static
Referenced by change_cleared_terrain().
oter_rural_road_turn_forest_east
const oter_str_id oter_rural_road_turn_forest_east("rural_road_turn_forest_east") ("rural_road_turn_forest_east") static
Referenced by change_cleared_terrain().
oter_rural_road_turn_forest_north
const oter_str_id oter_rural_road_turn_forest_north("rural_road_turn_forest_north") ("rural_road_turn_forest_north") static
Referenced by change_cleared_terrain().
oter_rural_road_turn_forest_south
const oter_str_id oter_rural_road_turn_forest_south("rural_road_turn_forest_south") ("rural_road_turn_forest_south") static
Referenced by change_cleared_terrain().
oter_rural_road_turn_forest_west
const oter_str_id oter_rural_road_turn_forest_west("rural_road_turn_forest_west") ("rural_road_turn_forest_west") static
Referenced by change_cleared_terrain().
oter_special_forest
const oter_str_id oter_special_forest("special_forest") ("special_forest") static
Referenced by change_cleared_terrain().
oter_special_forest_thick
const oter_str_id oter_special_forest_thick("special_forest_thick") ("special_forest_thick") static
Referenced by change_cleared_terrain().
oter_type_forest_trail
const oter_type_str_id oter_type_forest_trail("forest_trail") ("forest_trail") static
Referenced by companion_travel_time_calc().
path_map_size
constexpr size_t path_map_size = 2 * max_salt_water_pipe_distance + 1 static constexpr
Definition at line 2924 of file faction_camp.cpp.
relay_site_stash
const tripoint relay_site_stash = tripoint(11, 10, 0) static
Definition at line 2684 of file faction_camp.cpp.
Referenced by om_set_hide_site(), and basecamp::start_relay_hide_site().
salt_pipe_illegal
const double salt_pipe_illegal = -0.1 static
Definition at line 2922 of file faction_camp.cpp.
Referenced by basecamp::start_salt_water_pipe().
salt_pipe_legal
const double salt_pipe_legal = 0.0 static
Definition at line 2921 of file faction_camp.cpp.
Referenced by check_salt_pipe_neighbors(), and basecamp::start_salt_water_pipe().
salt_pipe_swamp
const double salt_pipe_swamp = -0.2 static
Definition at line 2923 of file faction_camp.cpp.
Referenced by check_salt_pipe_neighbors(), and basecamp::start_salt_water_pipe().
salt_water_pipe_string_base
const std::string salt_water_pipe_string_base = "salt_water_pipe_" static
Definition at line 2918 of file faction_camp.cpp.
Referenced by basecamp::salt_water_pipe_return(), salt_water_pipe_segment_of(), basecamp::salt_water_pipe_swamp_return(), and basecamp::start_salt_water_pipe().
salt_water_pipe_string_suffix
const std::string salt_water_pipe_string_suffix = "_scheduled" static
Definition at line 2919 of file faction_camp.cpp.
Referenced by basecamp::salt_water_pipe_return(), salt_water_pipe_segment_of(), basecamp::salt_water_pipe_swamp_return(), and basecamp::start_salt_water_pipe().
skill_bashing
const skill_id skill_bashing("bashing") ("bashing") static
Referenced by survive_random_encounter().
skill_combat
const skill_id skill_combat("combat") ("combat") static
Referenced by basecamp::combat_mission_return(), and survive_random_encounter().
skill_construction
const skill_id skill_construction("construction") ("construction") static
Referenced by basecamp::fortifications_return(), basecamp::handle_mission(), basecamp::survey_field_return(), and basecamp::survey_return().
skill_cutting
const skill_id skill_cutting("cutting") ("cutting") static
Referenced by survive_random_encounter().
skill_dodge
const skill_id skill_dodge("dodge") ("dodge") static
Referenced by survive_random_encounter().
skill_fabrication
const skill_id skill_fabrication("fabrication") ("fabrication") static
Referenced by basecamp::start_clearcut(), and basecamp::start_cut_logs().
skill_gun
const skill_id skill_gun("gun") ("gun") static
Referenced by basecamp::gathering_return(), and basecamp::handle_mission().
skill_melee
const skill_id skill_melee("melee") ("melee") static
Referenced by survive_random_encounter().
skill_menial
const skill_id skill_menial("menial") ("menial") static
Referenced by basecamp::abandon_camp(), basecamp::emergency_recall(), and basecamp::menial_return().
skill_recruiting
const skill_id skill_recruiting("recruiting") ("recruiting") static
Referenced by basecamp::recruit_return(), and survive_random_encounter().
skill_speech
const skill_id skill_speech("speech") ("speech") static
Referenced by basecamp::choose_new_leader(), basecamp::recruit_return(), and survive_random_encounter().
skill_stabbing
const skill_id skill_stabbing("stabbing") ("stabbing") static
Referenced by survive_random_encounter().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by farm_action(), basecamp::farm_return(), basecamp::gathering_return(), basecamp::handle_mission(), basecamp::recruit_return(), basecamp::start_combat_mission(), basecamp::start_farm_op(), basecamp::start_relay_hide_site(), basecamp::start_setup_hide_site(), and survive_random_encounter().
skill_swimming
const skill_id skill_swimming("swimming") ("swimming") static
Referenced by basecamp::combat_mission_return().
skill_traps
const skill_id skill_traps("traps") ("traps") static
Referenced by basecamp::gathering_return(), and basecamp::handle_mission().
skill_unarmed
const skill_id skill_unarmed("unarmed") ("unarmed") static
Referenced by survive_random_encounter().
smith_recipe_group_string
const std::string smith_recipe_group_string = "SMITH" static
Definition at line 214 of file faction_camp.cpp.
Referenced by basecamp::get_available_missions_by_dir(), and basecamp::handle_mission().
ter_t_clay
const ter_str_id ter_t_clay("t_clay") ("t_clay") static
Referenced by basecamp::survey_field_return().
ter_t_dirt
const ter_str_id ter_t_dirt("t_dirt") ("t_dirt") static
Referenced by farm_action(), om_cutdown_trees(), and basecamp::survey_field_return().
ter_t_dirtmound
const ter_str_id ter_t_dirtmound("t_dirtmound") ("t_dirtmound") static
Referenced by farm_action(), and basecamp::survey_field_return().
ter_t_grass
const ter_str_id ter_t_grass("t_grass") ("t_grass") static
Referenced by basecamp::survey_field_return().
ter_t_grass_dead
const ter_str_id ter_t_grass_dead("t_grass_dead") ("t_grass_dead") static
Referenced by basecamp::survey_field_return().
ter_t_grass_golf
const ter_str_id ter_t_grass_golf("t_grass_golf") ("t_grass_golf") static
Referenced by basecamp::survey_field_return().
ter_t_grass_long
const ter_str_id ter_t_grass_long("t_grass_long") ("t_grass_long") static
Referenced by basecamp::survey_field_return().
ter_t_grass_tall
const ter_str_id ter_t_grass_tall("t_grass_tall") ("t_grass_tall") static
Referenced by basecamp::survey_field_return().
ter_t_improvised_shelter
const ter_str_id ter_t_improvised_shelter("t_improvised_shelter") ("t_improvised_shelter") static
Referenced by om_set_hide_site().
ter_t_moss
const ter_str_id ter_t_moss("t_moss") ("t_moss") static
Referenced by basecamp::survey_field_return().
ter_t_sand
const ter_str_id ter_t_sand("t_sand") ("t_sand") static
Referenced by basecamp::survey_field_return().
ter_t_stump
const ter_str_id ter_t_stump("t_stump") ("t_stump") static
Referenced by om_cutdown_trees().
ter_t_tree_young
const ter_str_id ter_t_tree_young("t_tree_young") ("t_tree_young") static
Referenced by basecamp::start_clearcut(), and basecamp::start_cut_logs().
ter_t_trunk
const ter_str_id ter_t_trunk("t_trunk") ("t_trunk") static
Referenced by om_cutdown_trees().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by update_time_left().
update_mapgen_faction_wall_level_E_1
const update_mapgen_id update_mapgen_faction_wall_level_E_1("faction_wall_level_E_1") ("faction_wall_level_E_1") static
Referenced by apply_fortifications().
update_mapgen_faction_wall_level_S_1
const update_mapgen_id update_mapgen_faction_wall_level_S_1("faction_wall_level_S_1") ("faction_wall_level_S_1") static
Referenced by apply_fortifications().
update_mapgen_faction_wall_level_W_1
const update_mapgen_id update_mapgen_faction_wall_level_W_1("faction_wall_level_W_1") ("faction_wall_level_W_1") static
Referenced by apply_fortifications().
var_time_between_succession
const std::string var_time_between_succession static
Initial value:
=
    "npctalk_var_time_between_succession"
Definition at line 203 of file faction_camp.cpp.
Referenced by basecamp::choose_new_leader().
var_timer_time_of_last_succession
const std::string var_timer_time_of_last_succession static
Initial value:
=
    "npctalk_var_timer_time_of_last_succession"
Definition at line 206 of file faction_camp.cpp.
Referenced by basecamp::choose_new_leader().
zone_type_CAMP_FOOD
const zone_type_id zone_type_CAMP_FOOD("CAMP_FOOD") ("CAMP_FOOD") static
Referenced by basecamp::distribute_food(), and basecamp::validate_sort_points().
zone_type_CAMP_STORAGE
const zone_type_id zone_type_CAMP_STORAGE("CAMP_STORAGE") ("CAMP_STORAGE") static
Referenced by basecamp::validate_sort_points().