Cataclysm DDA: src/field_type.h File Reference
field_type.h File Reference
#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <iosfwd>
#include <set>
#include <string>
#include <tuple>
#include <unordered_map>
#include <utility>
#include <vector>
#include "bodypart.h"
#include "calendar.h"
#include "catacharset.h"
#include "color.h"
#include "effect.h"
#include "effect_source.h"
#include "enums.h"
#include "mapdata.h"
#include "map_field.h"
#include "translations.h"
#include "type_id.h"
Classes
struct std::hash< description_affix >
struct enum_traits< description_affix >
struct field_immunity_data
struct field_effect
struct field_intensity_level
struct field_type
Namespaces
field_types
Macros
#define CATA_SRC_FIELD_TYPE_H
Enumerations
enum class description_affix : int {
DESCRIPTION_AFFIX_IN , DESCRIPTION_AFFIX_COVERED_IN , DESCRIPTION_AFFIX_ON , DESCRIPTION_AFFIX_UNDER ,
DESCRIPTION_AFFIX_ILLUMINATED_BY , DESCRIPTION_AFFIX_NUM
}
Functions
generic_factory< field_type > & get_all_field_types ()
void field_types::load (const JsonObject &jo, const std::string &src)
void field_types::finalize_all ()
void field_types::check_consistency ()
void field_types::reset ()
void field_types::load_immunity (const JsonObject &jid, field_immunity_data &fd)
const std::vector< field_type > & field_types::get_all ()
field_type field_types::get_field_type_by_legacy_enum (int legacy_enum_id)
Variables
const field_type_id INVALID_FIELD_TYPE_ID = field_type_id(-1)
const field_type_str_id fd_null
const field_type_str_id fd_acid
const field_type_str_id fd_acid_vent
const field_type_str_id fd_bile
const field_type_str_id fd_blood
const field_type_str_id fd_blood_insect
const field_type_str_id fd_blood_invertebrate
const field_type_str_id fd_blood_veggy
const field_type_str_id fd_churned_earth
const field_type_str_id fd_construction_site
const field_type_str_id fd_cold_air2
const field_type_str_id fd_cold_air3
const field_type_str_id fd_cold_air4
const field_type_str_id fd_dazzling
const field_type_str_id fd_electricity
const field_type_str_id fd_electricity_unlit
const field_type_str_id fd_extinguisher
const field_type_str_id fd_reality_tear
const field_type_str_id fd_fire
const field_type_str_id fd_fire_vent
const field_type_str_id fd_flame_burst
const field_type_str_id fd_fungal_haze
const field_type_str_id fd_fungicidal_gas
const field_type_str_id fd_gas_vent
const field_type_str_id fd_gibs_flesh
const field_type_str_id fd_gibs_insect
const field_type_str_id fd_gibs_invertebrate
const field_type_str_id fd_gibs_veggy
const field_type_str_id fd_hot_air1
const field_type_str_id fd_hot_air2
const field_type_str_id fd_hot_air3
const field_type_str_id fd_hot_air4
const field_type_str_id fd_incendiary
const field_type_str_id fd_insecticidal_gas
const field_type_str_id fd_laser
const field_type_str_id fd_last_known
const field_type_str_id fd_nuke_gas
const field_type_str_id fd_plasma
const field_type_str_id fd_push_items
const field_type_str_id fd_relax_gas
const field_type_str_id fd_sap
const field_type_str_id fd_shock_vent
const field_type_str_id fd_slime
const field_type_str_id fd_sludge
const field_type_str_id fd_smoke
const field_type_str_id fd_smoke_vent
const field_type_str_id fd_tear_gas
const field_type_str_id fd_tindalos_rift
const field_type_str_id fd_toxic_gas
const field_type_str_id fd_web
Macro Definition Documentation
CATA_SRC_FIELD_TYPE_H
#define CATA_SRC_FIELD_TYPE_H
Definition at line 3 of file field_type.h.
Enumeration Type Documentation
description_affix
enum description_affix : int strong
Enumerator
DESCRIPTION_AFFIX_IN
DESCRIPTION_AFFIX_COVERED_IN
DESCRIPTION_AFFIX_ON
DESCRIPTION_AFFIX_UNDER
DESCRIPTION_AFFIX_ILLUMINATED_BY
DESCRIPTION_AFFIX_NUM
Definition at line 34 of file field_type.h.
                              : int {
     DESCRIPTION_AFFIX_IN,
     DESCRIPTION_AFFIX_COVERED_IN,
     DESCRIPTION_AFFIX_ON,
     DESCRIPTION_AFFIX_UNDER,
     DESCRIPTION_AFFIX_ILLUMINATED_BY,
     DESCRIPTION_AFFIX_NUM
 };
Function Documentation
get_all_field_types()
generic_factory<field_type>& get_all_field_types ()
Definition at line 107 of file field_type.cpp.
 {
     static generic_factory<field_type> all_field_types( "field types" );
     return all_field_types;
 }
Referenced by field_types::check_consistency(), field_type::count(), field_types::finalize_all(), field_types::get_all(), field_types::get_field_type_by_legacy_enum(), string_id< T >::id(), int_id< T >::is_valid(), string_id< T >::is_valid(), field_types::load(), int_id< T >::obj(), string_id< T >::obj(), ordered_static_globals(), and field_types::reset().
Variable Documentation
fd_acid
const field_type_str_id fd_acid extern
fd_acid_vent
const field_type_str_id fd_acid_vent extern
fd_bile
const field_type_str_id fd_bile extern
fd_blood
const field_type_str_id fd_blood extern
fd_blood_insect
const field_type_str_id fd_blood_insect extern
fd_blood_invertebrate
const field_type_str_id fd_blood_invertebrate extern
fd_blood_veggy
const field_type_str_id fd_blood_veggy extern
fd_churned_earth
const field_type_str_id fd_churned_earth extern
fd_cold_air2
const field_type_str_id fd_cold_air2 extern
fd_cold_air3
const field_type_str_id fd_cold_air3 extern
fd_cold_air4
const field_type_str_id fd_cold_air4 extern
fd_construction_site
const field_type_str_id fd_construction_site extern
fd_dazzling
const field_type_str_id fd_dazzling extern
fd_electricity
const field_type_str_id fd_electricity extern
fd_electricity_unlit
const field_type_str_id fd_electricity_unlit extern
fd_extinguisher
const field_type_str_id fd_extinguisher extern
fd_fire
const field_type_str_id fd_fire extern
fd_fire_vent
const field_type_str_id fd_fire_vent extern
fd_flame_burst
const field_type_str_id fd_flame_burst extern
fd_fungal_haze
const field_type_str_id fd_fungal_haze extern
fd_fungicidal_gas
const field_type_str_id fd_fungicidal_gas extern
fd_gas_vent
const field_type_str_id fd_gas_vent extern
fd_gibs_flesh
const field_type_str_id fd_gibs_flesh extern
fd_gibs_insect
const field_type_str_id fd_gibs_insect extern
fd_gibs_invertebrate
const field_type_str_id fd_gibs_invertebrate extern
fd_gibs_veggy
const field_type_str_id fd_gibs_veggy extern
fd_hot_air1
const field_type_str_id fd_hot_air1 extern
fd_hot_air2
const field_type_str_id fd_hot_air2 extern
fd_hot_air3
const field_type_str_id fd_hot_air3 extern
fd_hot_air4
const field_type_str_id fd_hot_air4 extern
fd_incendiary
const field_type_str_id fd_incendiary extern
fd_insecticidal_gas
const field_type_str_id fd_insecticidal_gas extern
fd_laser
const field_type_str_id fd_laser extern
fd_last_known
const field_type_str_id fd_last_known extern
fd_nuke_gas
const field_type_str_id fd_nuke_gas extern
fd_null
const field_type_str_id fd_null extern
Definition at line 11 of file field_type.cpp.
Referenced by monster::bloodType(), field::clear(), field_type::finalize(), mtype::get_bleed_type(), mtype::gibType(), monster::gibType(), string_id< T >::id(), monster::is_immune_effect(), species_type::load(), map::process_fields_in_submap(), zone_data::refresh_display(), field::remove_field(), explosion_handler::resonance_cascade(), and map::smash_items().
fd_plasma
const field_type_str_id fd_plasma extern
fd_push_items
const field_type_str_id fd_push_items extern
fd_reality_tear
const field_type_str_id fd_reality_tear extern
fd_relax_gas
const field_type_str_id fd_relax_gas extern
fd_sap
const field_type_str_id fd_sap extern
fd_shock_vent
const field_type_str_id fd_shock_vent extern
fd_slime
const field_type_str_id fd_slime extern
fd_sludge
const field_type_str_id fd_sludge extern
fd_smoke
const field_type_str_id fd_smoke extern
fd_smoke_vent
const field_type_str_id fd_smoke_vent extern
fd_tear_gas
const field_type_str_id fd_tear_gas extern
fd_tindalos_rift
const field_type_str_id fd_tindalos_rift extern
fd_toxic_gas
const field_type_str_id fd_toxic_gas extern
fd_web
const field_type_str_id fd_web extern
INVALID_FIELD_TYPE_ID
const field_type_id INVALID_FIELD_TYPE_ID = field_type_id(-1)
Definition at line 128 of file field_type.h.