Cataclysm DDA: src/field_type.cpp File Reference
field_type.cpp File Reference
#include "field_type.h"
#include <cstdlib>
#include "debug.h"
#include "enum_conversions.h"
#include "enums.h"
#include "generic_factory.h"
#include "json.h"
Namespaces
io
Functions
template<>
std::string io::enum_to_string< game_message_type > (game_message_type data)
template<>
std::string io::enum_to_string< description_affix > (description_affix data)
generic_factory< field_type > & get_all_field_types ()
Variables
const field_type_str_id fd_null = field_type_str_id::NULL_ID()
const field_type_str_id fd_acid ("fd_acid")
const field_type_str_id fd_acid_vent ("fd_acid_vent")
const field_type_str_id fd_bile ("fd_bile")
const field_type_str_id fd_blood ("fd_blood")
const field_type_str_id fd_blood_insect ("fd_blood_insect")
const field_type_str_id fd_blood_invertebrate ("fd_blood_invertebrate")
const field_type_str_id fd_blood_veggy ("fd_blood_veggy")
const field_type_str_id fd_churned_earth ("fd_churned_earth")
const field_type_str_id fd_cold_air2 ("fd_cold_air2")
const field_type_str_id fd_cold_air3 ("fd_cold_air3")
const field_type_str_id fd_cold_air4 ("fd_cold_air4")
const field_type_str_id fd_construction_site ("fd_construction_site")
const field_type_str_id fd_dazzling ("fd_dazzling")
const field_type_str_id fd_electricity ("fd_electricity")
const field_type_str_id fd_electricity_unlit ("fd_electricity_unlit")
const field_type_str_id fd_extinguisher ("fd_extinguisher")
const field_type_str_id fd_fire ("fd_fire")
const field_type_str_id fd_fire_vent ("fd_fire_vent")
const field_type_str_id fd_flame_burst ("fd_flame_burst")
const field_type_str_id fd_fungal_haze ("fd_fungal_haze")
const field_type_str_id fd_fungicidal_gas ("fd_fungicidal_gas")
const field_type_str_id fd_gas_vent ("fd_gas_vent")
const field_type_str_id fd_gibs_flesh ("fd_gibs_flesh")
const field_type_str_id fd_gibs_insect ("fd_gibs_insect")
const field_type_str_id fd_gibs_invertebrate ("fd_gibs_invertebrate")
const field_type_str_id fd_gibs_veggy ("fd_gibs_veggy")
const field_type_str_id fd_hot_air1 ("fd_hot_air1")
const field_type_str_id fd_hot_air2 ("fd_hot_air2")
const field_type_str_id fd_hot_air3 ("fd_hot_air3")
const field_type_str_id fd_hot_air4 ("fd_hot_air4")
const field_type_str_id fd_incendiary ("fd_incendiary")
const field_type_str_id fd_insecticidal_gas ("fd_insecticidal_gas")
const field_type_str_id fd_laser ("fd_laser")
const field_type_str_id fd_last_known ("fd_last_known")
const field_type_str_id fd_nuke_gas ("fd_nuke_gas")
const field_type_str_id fd_plasma ("fd_plasma")
const field_type_str_id fd_push_items ("fd_push_items")
const field_type_str_id fd_reality_tear ("fd_reality_tear")
const field_type_str_id fd_relax_gas ("fd_relax_gas")
const field_type_str_id fd_sap ("fd_sap")
const field_type_str_id fd_shock_vent ("fd_shock_vent")
const field_type_str_id fd_slime ("fd_slime")
const field_type_str_id fd_sludge ("fd_sludge")
const field_type_str_id fd_smoke ("fd_smoke")
const field_type_str_id fd_smoke_vent ("fd_smoke_vent")
const field_type_str_id fd_tear_gas ("fd_tear_gas")
const field_type_str_id fd_tindalos_rift ("fd_tindalos_rift")
const field_type_str_id fd_toxic_gas ("fd_toxic_gas")
const field_type_str_id fd_web ("fd_web")
Function Documentation
get_all_field_types()
generic_factory<field_type>& get_all_field_types ()
Definition at line 107 of file field_type.cpp.
 {
     static generic_factory<field_type> all_field_types( "field types" );
     return all_field_types;
 }
Referenced by field_types::check_consistency(), field_type::count(), field_types::finalize_all(), field_types::get_all(), field_types::get_field_type_by_legacy_enum(), string_id< T >::id(), int_id< T >::is_valid(), string_id< T >::is_valid(), field_types::load(), int_id< T >::obj(), string_id< T >::obj(), ordered_static_globals(), and field_types::reset().
Variable Documentation
fd_acid
const field_type_str_id fd_acid("fd_acid") ("fd_acid")
Referenced by mattack::acid(), mattack::acid_barf(), iuse::acidbomb_act(), mtype::bloodType(), field_processor_fd_acid(), field_processor_fd_acid_vent(), map::monster_in_field(), monster::move_to(), game::place_player(), map::player_in_field(), map_field_processing::processors_for_type(), activity_handlers::pulp_do_turn(), mattack::science(), and smash().
fd_acid_vent
const field_type_str_id fd_acid_vent("fd_acid_vent") ("fd_acid_vent")
Referenced by map::create_anomaly(), map::player_in_field(), and map_field_processing::processors_for_type().
fd_bile
const field_type_str_id fd_bile("fd_bile") ("fd_bile")
Referenced by mtype::bloodType(), mattack::boomer(), mattack::boomer_glow(), explosion_handler::resonance_cascade(), and Character::vomit().
fd_blood
const field_type_str_id fd_blood("fd_blood") ("fd_blood")
Referenced by mtype::bloodType(), MapExtras::mx_casings(), MapExtras::mx_corpses(), MapExtras::mx_looters(), MapExtras::mx_minefield(), and explosion_handler::resonance_cascade().
fd_blood_insect
const field_type_str_id fd_blood_insect("fd_blood_insect") ("fd_blood_insect")
Referenced by mtype::bloodType().
fd_blood_invertebrate
const field_type_str_id fd_blood_invertebrate("fd_blood_invertebrate") ("fd_blood_invertebrate")
Referenced by mtype::bloodType().
fd_blood_veggy
const field_type_str_id fd_blood_veggy("fd_blood_veggy") ("fd_blood_veggy")
Referenced by npc::add_msg_player_or_npc(), and mtype::bloodType().
fd_churned_earth
const field_type_str_id fd_churned_earth("fd_churned_earth") ("fd_churned_earth")
Referenced by monster::move_to().
fd_cold_air2
const field_type_str_id fd_cold_air2("fd_cold_air2") ("fd_cold_air2")
fd_cold_air3
const field_type_str_id fd_cold_air3("fd_cold_air3") ("fd_cold_air3")
fd_cold_air4
const field_type_str_id fd_cold_air4("fd_cold_air4") ("fd_cold_air4")
fd_construction_site
const field_type_str_id fd_construction_site("fd_construction_site") ("fd_construction_site")
Referenced by apply_construction_marker().
fd_dazzling
const field_type_str_id fd_dazzling("fd_dazzling") ("fd_dazzling")
Referenced by map::monster_in_field(), and mattack::riotbot().
fd_electricity
const field_type_str_id fd_electricity("fd_electricity") ("fd_electricity")
Referenced by map::add_field(), field_processor_fd_shock_vent(), map::get_applicable_electricity_field(), monster::know_danger_at(), map::monster_in_field(), map::player_in_field(), map_field_processing::processors_for_type(), and mattack::shockstorm().
fd_electricity_unlit
const field_type_str_id fd_electricity_unlit("fd_electricity_unlit") ("fd_electricity_unlit")
Referenced by map::add_field(), map::get_applicable_electricity_field(), and map_field_processing::processors_for_type().
fd_extinguisher
const field_type_str_id fd_extinguisher("fd_extinguisher") ("fd_extinguisher")
Referenced by iuse::extinguisher(), and map_field_processing::processors_for_type().
fd_fire
const field_type_str_id fd_fire("fd_fire") ("fd_fire")
Referenced by Character::activate_bionic(), activity_on_turn_move_loot(), map::add_item(), npc::assess_danger(), start_location::burn(), damage_targets(), explosion_handler::do_blast(), unload_loot_activity_actor::do_turn(), iuse::extinguisher(), field_processor_fd_extinguisher(), find_best_fire(), oxytorch_activity_actor::finish(), iexamine::fireplace(), mattack::flame(), mattack::fungus_big_blossom(), get_best_fire(), get_convection_temperature(), get_fire_fuel_string(), get_heat_radiation(), game::grabbed_furn_move(), iuse::grenade_inc_act(), map::has_nearby_fire(), map::hit_with_fire(), monster::know_danger_at(), iuse::molotov_lit(), map::monster_in_field(), MapExtras::mx_portal_in(), map::player_in_field(), firestarter_actor::prep_firestarter_use(), item::process_litcig(), monster::process_triggers(), monster::process_turn(), map_field_processing::processors_for_type(), firestarter_actor::resolve_firestarter_use(), explosion_handler::resonance_cascade(), mattack::resurrect(), map::shoot(), try_fuel_fire(), and game::walk_move().
fd_fire_vent
const field_type_str_id fd_fire_vent("fd_fire_vent") ("fd_fire_vent")
Referenced by map::create_anomaly(), and map_field_processing::processors_for_type().
fd_flame_burst
const field_type_str_id fd_flame_burst("fd_flame_burst") ("fd_flame_burst")
Referenced by map::monster_in_field(), map::player_in_field(), and map_field_processing::processors_for_type().
fd_fungal_haze
const field_type_str_id fd_fungal_haze("fd_fungal_haze") ("fd_fungal_haze")
Referenced by Character::blossoms(), mattack::fungus_big_blossom(), mattack::fungus_haze(), monster::is_immune_field(), map::monster_in_field(), map::player_in_field(), map_field_processing::processors_for_type(), and fungal_effects::spread_fungus_one_tile().
fd_fungicidal_gas
const field_type_str_id fd_fungicidal_gas("fd_fungicidal_gas") ("fd_fungicidal_gas")
Referenced by monster::is_immune_field(), map::monster_in_field(), map::player_in_field(), and map_field_processing::processors_for_type().
fd_gas_vent
const field_type_str_id fd_gas_vent("fd_gas_vent") ("fd_gas_vent")
Referenced by map::draw_lab().
fd_gibs_flesh
const field_type_str_id fd_gibs_flesh("fd_gibs_flesh") ("fd_gibs_flesh")
Referenced by mattack::flesh_tendril(), mtype::gibType(), Character::gibType(), MapExtras::mx_corpses(), and MapExtras::mx_minefield().
fd_gibs_insect
const field_type_str_id fd_gibs_insect("fd_gibs_insect") ("fd_gibs_insect")
Referenced by mtype::gibType().
fd_gibs_invertebrate
const field_type_str_id fd_gibs_invertebrate("fd_gibs_invertebrate") ("fd_gibs_invertebrate")
Referenced by mtype::gibType().
fd_gibs_veggy
const field_type_str_id fd_gibs_veggy("fd_gibs_veggy") ("fd_gibs_veggy")
Referenced by mtype::gibType().
fd_hot_air1
const field_type_str_id fd_hot_air1("fd_hot_air1") ("fd_hot_air1")
Referenced by map::create_hot_air().
fd_hot_air2
const field_type_str_id fd_hot_air2("fd_hot_air2") ("fd_hot_air2")
Referenced by map::create_hot_air().
fd_hot_air3
const field_type_str_id fd_hot_air3("fd_hot_air3") ("fd_hot_air3")
Referenced by map::create_hot_air().
fd_hot_air4
const field_type_str_id fd_hot_air4("fd_hot_air4") ("fd_hot_air4")
Referenced by map::create_hot_air().
fd_incendiary
const field_type_str_id fd_incendiary("fd_incendiary") ("fd_incendiary")
Referenced by iuse::grenade_inc_act(), map::monster_in_field(), map::player_in_field(), and map_field_processing::processors_for_type().
fd_insecticidal_gas
const field_type_str_id fd_insecticidal_gas("fd_insecticidal_gas") ("fd_insecticidal_gas")
Referenced by monster::is_immune_field(), map::monster_in_field(), and map::player_in_field().
fd_laser
const field_type_str_id fd_laser("fd_laser") ("fd_laser")
fd_last_known
const field_type_str_id fd_last_known("fd_last_known") ("fd_last_known")
Referenced by map_field_processing::processors_for_type().
fd_nuke_gas
const field_type_str_id fd_nuke_gas("fd_nuke_gas") ("fd_nuke_gas")
Referenced by computer_session::action_irradiator(), map::monster_in_field(), and explosion_handler::resonance_cascade().
fd_null
const field_type_str_id fd_null = field_type_str_id::NULL_ID()
Definition at line 11 of file field_type.cpp.
Referenced by monster::bloodType(), field::clear(), field_type::finalize(), mtype::get_bleed_type(), mtype::gibType(), monster::gibType(), string_id< T >::id(), monster::is_immune_effect(), species_type::load(), map::process_fields_in_submap(), zone_data::refresh_display(), field::remove_field(), explosion_handler::resonance_cascade(), and map::smash_items().
fd_plasma
const field_type_str_id fd_plasma("fd_plasma") ("fd_plasma")
fd_push_items
const field_type_str_id fd_push_items("fd_push_items") ("fd_push_items")
Referenced by map::create_anomaly(), field_processor_fd_push_items(), and map_field_processing::processors_for_type().
fd_reality_tear
const field_type_str_id fd_reality_tear("fd_reality_tear") ("fd_reality_tear")
Referenced by suffer::from_artifact_resonance(), map::monster_in_field(), MapExtras::mx_portal_in(), map::player_in_field(), and spell_effect::remove_field().
fd_relax_gas
const field_type_str_id fd_relax_gas("fd_relax_gas") ("fd_relax_gas")
Referenced by map::monster_in_field(), and mattack::riotbot().
fd_sap
const field_type_str_id fd_sap("fd_sap") ("fd_sap")
Referenced by monster::is_immune_field(), map::monster_in_field(), and map::player_in_field().
fd_shock_vent
const field_type_str_id fd_shock_vent("fd_shock_vent") ("fd_shock_vent")
Referenced by computer_session::action_deactivate_shock_vent(), map::create_anomaly(), map::player_in_field(), and map_field_processing::processors_for_type().
fd_slime
const field_type_str_id fd_slime("fd_slime") ("fd_slime")
Referenced by explosion_handler::resonance_cascade().
fd_sludge
const field_type_str_id fd_sludge("fd_sludge") ("fd_sludge")
Referenced by Character::activate_mutation(), suffer::from_other_mutations(), monster::is_immune_field(), map::monster_in_field(), monster::move_to(), and map::player_in_field().
fd_smoke
const field_type_str_id fd_smoke("fd_smoke") ("fd_smoke")
Referenced by computer_session::action_miss_launch(), mattack::fungus_big_blossom(), map::monster_in_field(), and vehicle::noise_and_smoke().
fd_smoke_vent
const field_type_str_id fd_smoke_vent("fd_smoke_vent") ("fd_smoke_vent")
Referenced by map::draw_lab().
fd_tear_gas
const field_type_str_id fd_tear_gas("fd_tear_gas") ("fd_tear_gas")
Referenced by iuse::mace(), map::monster_in_field(), map::player_in_field(), and mattack::riotbot().
fd_tindalos_rift
const field_type_str_id fd_tindalos_rift("fd_tindalos_rift") ("fd_tindalos_rift")
Referenced by iuse::call_of_tindalos(), suffer::from_artifact_resonance(), Character::hardcoded_effects(), and mattack::tindalos_teleport().
fd_toxic_gas
const field_type_str_id fd_toxic_gas("fd_toxic_gas") ("fd_toxic_gas")
Referenced by map::monster_in_field().
fd_web
const field_type_str_id fd_web("fd_web") ("fd_web")
Referenced by Character::activate_mutation(), Character::base_comfort_value(), suffer::from_other_mutations(), map::is_flammable(), monster::is_immune_field(), and avatar::try_to_sleep().