Cataclysm DDA: src/filesystem.cpp File Reference
filesystem.cpp File Reference
#include "filesystem.h"
#include <algorithm>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <functional>
#include <iterator>
#include <string>
#include <type_traits>
#include <vector>
#include "cata_utility.h"
#include "debug.h"
Namespaces
anonymous_namespace{filesystem.cpp}
Functions
static void setFsNeedsSync ()
bool assure_dir_exist (const std::string &path)
bool assure_dir_exist (const cata_path &path)
bool assure_dir_exist (const fs::path &path)
bool dir_exist (const std::string &path)
bool dir_exist (const fs::path &path)
bool file_exist (const std::string &path)
bool file_exist (const fs::path &path)
bool file_exist (const cata_path &path)
std::string as_norm_dir (const std::string &path)
std::string as_norm_dir (const fs::path &path)
bool remove_file (const std::string &path)
bool remove_file (const fs::path &path)
bool rename_file (const std::string &old_path, const std::string &new_path)
bool rename_file (const fs::path &old_path, const fs::path &new_path)
std::string abs_path (const std::string &path)
fs::path abs_path (const fs::path &path)
bool remove_directory (const std::string &path)
bool remove_directory (const fs::path &path)
std::string read_entire_file (const std::string &path)
std::string read_entire_file (const fs::path &path)
template<typename Function >
void anonymous_namespace{filesystem.cpp}::for_each_dir_entry (const fs::path &path, Function &&function)
bool anonymous_namespace{filesystem.cpp}::is_directory (const fs::directory_entry &entry, const std::string &full_path)
bool anonymous_namespace{filesystem.cpp}::is_directory (const fs::directory_entry &entry)
bool anonymous_namespace{filesystem.cpp}::name_contains (const fs::directory_entry &entry, const std::string &match, const bool at_end)
template<typename Predicate >
std::vector< std::string > anonymous_namespace{filesystem.cpp}::find_file_if_bfs (const std::string &root_path, const bool recursive_search, Predicate predicate)
template<typename Predicate >
std::vector< cata_path > anonymous_namespace{filesystem.cpp}::find_file_if_bfs (const cata_path &root_path, const bool recursive_search, Predicate predicate)
std::vector< std::string > get_files_from_path (const std::string &pattern, const std::string &root_path, const bool recursive_search, const bool match_extension)
Returns a vector of files or directories matching pattern at root_path.
std::vector< cata_path > get_files_from_path (const std::string &pattern, const cata_path &root_path, const bool recursive_search, const bool match_extension)
std::vector< std::string > get_directories_with (const std::string &pattern, const std::string &root_path, const bool recursive_search)
Find directories which containing pattern.
std::vector< cata_path > get_directories_with (const std::string &pattern, const cata_path &root_path, const bool recursive_search)
std::vector< std::string > get_directories_with (const std::vector< std::string > &patterns, const std::string &root_path, const bool recursive_search)
Find directories which containing pattern.
std::vector< cata_path > get_directories_with (const std::vector< std::string > &patterns, const cata_path &root_path, const bool recursive_search)
bool copy_file (const std::string &source_path, const std::string &dest_path)
bool copy_file (const cata_path &source_path, const cata_path &dest_path)
std::string ensure_valid_file_name (const std::string &file_name)
Replace invalid characters in a string with a default character; can be used to ensure that a file name is compliant with most file systems.
Variables
static const std::string invalid_chars = "\\/:?\"<>|"
Function Documentation
abs_path() [1/2]
fs::path abs_path (const fs::path & path)
Definition at line 177 of file filesystem.cpp.
 {
     return fs::absolute( path );
 }
abs_path() [2/2]
std::string abs_path (const std::string & path)
Definition at line 172 of file filesystem.cpp.
 {
     return abs_path( fs::u8path( path ) ).generic_u8string();
 }
as_norm_dir() [1/2]
std::string as_norm_dir (const fs::path & path)
Definition at line 142 of file filesystem.cpp.
 {
     return as_norm_dir( path.u8string() );
 }
References as_norm_dir().
as_norm_dir() [2/2]
std::string as_norm_dir (const std::string & path)
Definition at line 131 of file filesystem.cpp.
 {
     fs::path dir = fs::u8path( path ) / fs::path{};
     fs::path norm = dir.lexically_normal();
     std::string ret = norm.generic_u8string();
     if( "." == ret ) {
         ret = "./"; // TODO Change the many places that use strings instead of paths
     }
     return ret;
 }
References cata::hash64_detail::ret.
Referenced by as_norm_dir(), assure_dir_exist(), PATH_INFO::init_base_path(), and PATH_INFO::init_user_dir().
assure_dir_exist() [1/3]
bool assure_dir_exist (const cata_path & path)
Definition at line 73 of file filesystem.cpp.
 {
     return assure_dir_exist( path.get_unrelative_path() );
 }
References assure_dir_exist(), and cata_path::get_unrelative_path().
assure_dir_exist() [2/3]
bool assure_dir_exist (const fs::path & path)
Definition at line 78 of file filesystem.cpp.
 {
     setFsNeedsSync();
     std::error_code ec;
     bool exists{false};
     bool created{false};
     const fs::path p = fs::u8path( as_norm_dir( path ) );
     bool is_dir{ fs::is_directory( p, ec ) };
     if( !is_dir ) {
         exists = fs::exists( p, ec );
         if( !exists ) {
             if( !is_lexically_valid( p ) ) {
                 return false;
             }
             created = fs::create_directories( p, ec );
             if( !created ) {
                 // TEMPORARY until we drop VS2019 support
                 // VS2019 std::filesystem doesn't handle trailing slashes well in this
                 // situation.  We think this is a bug.  Work around it by checking again
                 created = fs::exists( p, ec );
             }
         }
     }
     bool ret = is_dir || ( !exists && created );
     return !ec && ret;
 }
References as_norm_dir(), anonymous_namespace{filesystem.cpp}::is_directory(), is_lexically_valid(), cata::hash64_detail::ret, and setFsNeedsSync().
assure_dir_exist() [3/3]
bool assure_dir_exist (const std::string & path)
Definition at line 68 of file filesystem.cpp.
 {
     return assure_dir_exist( fs::u8path( path ) );
 }
Referenced by assure_dir_exist(), anonymous_namespace{main.cpp}::assure_essential_dirs_exist(), mod_manager::copy_mod_contents(), past_games_info::ensure_loaded(), past_achievements_info::load(), color_loader< ColorType >::load(), main(), game::move_save_to_graveyard(), debug_menu::prepare_export_dir_and_find_unused_name(), mapbuffer::save(), WORLD::save(), map_memory::save(), game::save_achievements(), mapbuffer::save_quad(), flexbuffer_disk_cache::save_to_disk(), debug_menu::vehicle_export(), and game::write_memorial_file().
copy_file() [1/2]
bool copy_file (const cata_path & source_path, const cata_path & dest_path)
Definition at line 562 of file filesystem.cpp.
 {
     std::ifstream source_stream( source_path.get_unrelative_path(),
                                  std::ifstream::in | std::ifstream::binary );
     if( !source_stream ) {
         return false;
     }
     return write_to_file( dest_path, [&]( std::ostream & dest_stream ) {
         dest_stream << source_stream.rdbuf();
     }, nullptr ) &&source_stream;
 }
References cata_path::get_unrelative_path(), and write_to_file().
copy_file() [2/2]
bool copy_file (const std::string & source_path, const std::string & dest_path)
Definition at line 550 of file filesystem.cpp.
 {
     std::ifstream source_stream( fs::u8path( source_path ),
                                  std::ifstream::in | std::ifstream::binary );
     if( !source_stream ) {
         return false;
     }
     return write_to_file( dest_path, [&]( std::ostream & dest_stream ) {
         dest_stream << source_stream.rdbuf();
     }, nullptr ) &&source_stream;
 }
References write_to_file().
Referenced by mod_manager::copy_mod_contents(), color_loader< ColorType >::load(), and color_manager::show_gui().
dir_exist() [1/2]
bool dir_exist (const fs::path & path)
Definition at line 110 of file filesystem.cpp.
 {
     return fs::is_directory( path );
 }
References anonymous_namespace{filesystem.cpp}::is_directory().
dir_exist() [2/2]
bool dir_exist (const std::string & path)
Definition at line 105 of file filesystem.cpp.
 {
     return dir_exist( fs::u8path( path ) );
 }
Referenced by build_resource_list(), DynamicDataLoader::load_data_from_path(), mod_manager::load_mods_from(), and main().
ensure_valid_file_name()
std::string ensure_valid_file_name (const std::string & file_name)
Replace invalid characters in a string with a default character; can be used to ensure that a file name is compliant with most file systems.
Parameters
file_name Name of the file to check.
Returns
A string with all invalid characters replaced with the replacement character, if any change was made.
Note
The default replacement character is space (0x20) and the invalid characters are "\\/:?\"<>|".
Definition at line 574 of file filesystem.cpp.
 {
     const char replacement_char = ' ';
     // do any replacement in the file name, if needed.
     std::string new_file_name = file_name;
     std::transform( new_file_name.begin(), new_file_name.end(),
     new_file_name.begin(), [&]( const char c ) {
         if( invalid_chars.find( c ) != std::string::npos ) {
             return replacement_char;
         }
         return c;
     } );
     return new_file_name;
 }
References c.
file_exist() [1/3]
bool file_exist (const cata_path & path)
Definition at line 125 of file filesystem.cpp.
 {
     const fs::path unrelative_path = path.get_unrelative_path();
     return fs::exists( unrelative_path ) && !fs::is_directory( unrelative_path );
 }
References cata_path::get_unrelative_path(), and anonymous_namespace{filesystem.cpp}::is_directory().
file_exist() [2/3]
bool file_exist (const fs::path & path)
Definition at line 120 of file filesystem.cpp.
 {
     return fs::exists( path ) && !fs::is_directory( path );
 }
References anonymous_namespace{filesystem.cpp}::is_directory().
file_exist() [3/3]
bool file_exist (const std::string & path)
Definition at line 115 of file filesystem.cpp.
 {
     return file_exist( fs::u8path( path ) );
 }
Referenced by find_translated_file(), json_loader::from_path_at_offset(), json_loader::from_path_at_offset_opt(), overmapbuffer::get_existing(), get_playtime_from_save(), worldfactory::init(), diary::load(), game::load(), color_loader< ColorType >::load(), DynamicDataLoader::load_data_from_path(), worldfactory::load_last_world_info(), debug_menu::prepare_export_dir_and_find_unused_name(), read_from_file_optional(), read_from_file_optional_json(), mod_manager::refresh_mod_list(), auto_notes::auto_note_settings::save(), auto_pickup::player_settings::save(), safemode::save(), and mapbuffer::unserialize_submaps().
get_directories_with() [1/4]
std::vector<cata_path> get_directories_with (const std::string & pattern, const cata_path & root_path, const bool recursive_search)
Definition at line 465 of file filesystem.cpp.
 {
     if( pattern.empty() ) {
         return {};
     }
     auto files = find_file_if_bfs( root_path, recursive_search, [&]( const fs::directory_entry & entry,
     bool ) {
         return name_contains( entry, pattern, true );
     } );
     // Chop off the file names. Dir path MUST be splitted by '/'
     for( cata_path &file : files ) {
         file = file.parent_path();
     }
     files.erase( std::unique( std::begin( files ), std::end( files ) ), std::end( files ) );
     return files;
 }
References keycode::end, file, anonymous_namespace{filesystem.cpp}::find_file_if_bfs(), and anonymous_namespace{filesystem.cpp}::name_contains().
get_directories_with() [2/4]
std::vector<std::string> get_directories_with (const std::string & pattern, const std::string & root_path, const bool recursive_search)
Find directories which containing pattern.
Parameters
pattern Search pattern.
root_path Search root.
recursive_search Be recurse or not.
Returns
vector or directories without pattern filename at end.
Definition at line 443 of file filesystem.cpp.
 {
     if( pattern.empty() ) {
         return std::vector<std::string>();
     }
     auto files = find_file_if_bfs( root_path, recursive_search, [&]( const fs::directory_entry & entry,
     bool ) {
         return name_contains( entry, pattern, true );
     } );
     // Chop off the file names. Dir path MUST be splitted by '/'
     for( auto &file : files ) {
         file.erase( file.rfind( '/' ), std::string::npos );
     }
     files.erase( std::unique( std::begin( files ), std::end( files ) ), std::end( files ) );
     return files;
 }
References keycode::end, file, anonymous_namespace{filesystem.cpp}::find_file_if_bfs(), and anonymous_namespace{filesystem.cpp}::name_contains().
Referenced by build_resource_list(), mod_manager::copy_mod_contents(), and options_manager::get_langs_with_translation_files().
get_directories_with() [3/4]
std::vector<cata_path> get_directories_with (const std::vector< std::string > & patterns, const cata_path & root_path, const bool recursive_search)
Definition at line 522 of file filesystem.cpp.
 {
     if( patterns.empty() ) {
         return {};
     }
     const auto ext_beg = std::begin( patterns );
     const auto ext_end = std::end( patterns );
     auto files = find_file_if_bfs( root_path, recursive_search, [&]( const fs::directory_entry & entry,
     bool ) {
         return std::any_of( ext_beg, ext_end, [&]( const std::string & ext ) {
             return name_contains( entry, ext, true );
         } );
     } );
     //chop off the file names
     for( cata_path &file : files ) {
         file = cata_path{ file.get_logical_root(), file.get_relative_path().parent_path() };
     }
     //remove resulting duplicates
     files.erase( std::unique( std::begin( files ), std::end( files ) ), std::end( files ) );
     return files;
 }
References keycode::end, file, anonymous_namespace{filesystem.cpp}::find_file_if_bfs(), and anonymous_namespace{filesystem.cpp}::name_contains().
get_directories_with() [4/4]
std::vector<std::string> get_directories_with (const std::vector< std::string > & patterns, const std::string & root_path, const bool recursive_search)
Find directories which containing pattern.
Returns a vector of directories which contain files matching any of patterns.
Parameters
patterns Search patterns.
root_path Search root.
recursive_search Be recurse or not.
Returns
vector or directories without pattern filename at end.
Definition at line 494 of file filesystem.cpp.
 {
     if( patterns.empty() ) {
         return std::vector<std::string>();
     }
     const auto ext_beg = std::begin( patterns );
     const auto ext_end = std::end( patterns );
     auto files = find_file_if_bfs( root_path, recursive_search, [&]( const fs::directory_entry & entry,
     bool ) {
         return std::any_of( ext_beg, ext_end, [&]( const std::string & ext ) {
             return name_contains( entry, ext, true );
         } );
     } );
     //chop off the file names
     for( auto &file : files ) {
         file.erase( file.rfind( '/' ), std::string::npos );
     }
     //remove resulting duplicates
     files.erase( std::unique( std::begin( files ), std::end( files ) ), std::end( files ) );
     return files;
 }
References keycode::end, file, anonymous_namespace{filesystem.cpp}::find_file_if_bfs(), and anonymous_namespace{filesystem.cpp}::name_contains().
get_files_from_path() [1/2]
std::vector<cata_path> get_files_from_path (const std::string & pattern, const cata_path & root_path, const bool recursive_search, const bool match_extension)
Definition at line 427 of file filesystem.cpp.
 {
     return find_file_if_bfs( root_path, recursive_search, [&]( const fs::directory_entry & entry,
     bool ) {
         return name_contains( entry, pattern, match_extension );
     } );
 }
References anonymous_namespace{filesystem.cpp}::find_file_if_bfs(), and anonymous_namespace{filesystem.cpp}::name_contains().
get_files_from_path() [2/2]
std::vector<std::string> get_files_from_path (const std::string & pattern, const std::string & root_path = "", bool recursive_search = false, bool match_extension = false)
Returns a vector of files or directories matching pattern at root_path.
Searches through the directory tree breadth-first. Directories are searched in lexical order. Matching files within in each directory are also ordered lexically.
Parameters
pattern The sub-string to match.
root_path The path relative to the current working directory to search; empty means ".".
recursive_search Whether to recursively search sub directories.
match_extension If true, match pattern at the end of file names. Otherwise, match anywhere in the file name.
Definition at line 419 of file filesystem.cpp.
 {
     return find_file_if_bfs( root_path, recursive_search, [&]( const fs::directory_entry & entry,
     bool ) {
         return name_contains( entry, pattern, match_extension );
     } );
 }
References anonymous_namespace{filesystem.cpp}::find_file_if_bfs(), and anonymous_namespace{filesystem.cpp}::name_contains().
Referenced by mod_manager::copy_mod_contents(), worldfactory::delete_world(), past_games_info::ensure_loaded(), debug_menu::import_folower(), worldfactory::init(), flexbuffer_disk_cache::init_from_folder(), past_achievements_info::load(), main_menu::load_char_templates(), DynamicDataLoader::load_data_from_path(), mod_manager::load_mods_from(), game::move_save_to_graveyard(), and color_manager::show_gui().
read_entire_file() [1/2]
std::string read_entire_file (const fs::path & path)
Definition at line 214 of file filesystem.cpp.
 {
     std::ifstream infile( path, std::ifstream::in | std::ifstream::binary );
     return std::string( std::istreambuf_iterator<char>( infile ),
                         std::istreambuf_iterator<char>() );
 }
read_entire_file() [2/2]
std::string read_entire_file (const std::string & path)
Definition at line 207 of file filesystem.cpp.
 {
     std::ifstream infile( fs::u8path( path ), std::ifstream::in | std::ifstream::binary );
     return std::string( std::istreambuf_iterator<char>( infile ),
                         std::istreambuf_iterator<char>() );
 }
Referenced by DynamicDataLoader::get_cached_stream().
remove_directory() [1/2]
bool remove_directory (const fs::path & path)
Definition at line 187 of file filesystem.cpp.
 {
     std::error_code ec;
     setFsNeedsSync();
     return fs::remove( path, ec );
 }
References setFsNeedsSync().
remove_directory() [2/2]
bool remove_directory (const std::string & path)
Definition at line 182 of file filesystem.cpp.
 {
     return remove_directory( fs::u8path( path ) );
 }
Referenced by worldfactory::delete_world().
remove_file() [1/2]
bool remove_file (const fs::path & path)
Definition at line 152 of file filesystem.cpp.
 {
     setFsNeedsSync();
     std::error_code ec;
     return fs::remove( path, ec );
 }
References setFsNeedsSync().
remove_file() [2/2]
bool remove_file (const std::string & path)
Definition at line 147 of file filesystem.cpp.
 {
     return remove_file( fs::u8path( path ) );
 }
Referenced by worldfactory::delete_world(), input_manager::init(), flexbuffer_disk_cache::init_from_folder(), flexbuffer_disk_cache::load_flexbuffer_if_not_stale(), game::move_save_to_graveyard(), main_menu::new_character_tab(), and mod_manager::save_mods_list().
rename_file() [1/2]
bool rename_file (const fs::path & old_path, const fs::path & new_path)
Definition at line 164 of file filesystem.cpp.
 {
     setFsNeedsSync();
     std::error_code ec;
     fs::rename( old_path, new_path, ec );
     return !ec;
 }
References setFsNeedsSync().
rename_file() [2/2]
bool rename_file (const std::string & old_path, const std::string & new_path)
Definition at line 159 of file filesystem.cpp.
 {
     return rename_file( fs::u8path( old_path ), fs::u8path( new_path ) );
 }
Referenced by worldfactory::init(), DebugFile::init(), and game::move_save_to_graveyard().
setFsNeedsSync()
static void setFsNeedsSync () static
Definition at line 59 of file filesystem.cpp.
 {
 #if defined(EMSCRIPTEN)
     EM_ASM( window.setFsNeedsSync(); );
 #endif
 }
Referenced by assure_dir_exist(), remove_directory(), remove_file(), and rename_file().
Variable Documentation
invalid_chars
const std::string invalid_chars = "\\/:?\"<>|" static
Definition at line 66 of file filesystem.cpp.