Cataclysm DDA: src/flag.cpp File Reference
flag.cpp File Reference
#include "flag.h"
#include "debug.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "generic_factory.h"
#include "init.h"
#include "json_error.h"
#include "type_id.h"
Namespaces
anonymous_namespace{flag.cpp}
Variables
const flag_id flag_ABLATIVE_LARGE ("ABLATIVE_LARGE")
const flag_id flag_ABLATIVE_MEDIUM ("ABLATIVE_MEDIUM")
const flag_id flag_ACID ("ACID")
const flag_id flag_ACID_IMMUNE ("ACID_IMMUNE")
const flag_id flag_ACTIVATE_ON_PLACE ("ACTIVATE_ON_PLACE")
const flag_id flag_ACTIVE_CLOAKING ("ACTIVE_CLOAKING")
const flag_id flag_ACTIVE_GENERATOR ("ACTIVE_GENERATOR")
const flag_id flag_ACT_IN_FIRE ("ACT_IN_FIRE")
const flag_id flag_ACT_ON_RANGED_HIT ("ACT_ON_RANGED_HIT")
const flag_id flag_ALARMCLOCK ("ALARMCLOCK")
const flag_id flag_ALLERGEN_BREAD ("ALLERGEN_BREAD")
const flag_id flag_ALLERGEN_CHEESE ("ALLERGEN_CHEESE")
const flag_id flag_ALLERGEN_DRIED_VEGETABLE ("ALLERGEN_DRIED_VEGETABLE")
const flag_id flag_ALLERGEN_EGG ("ALLERGEN_EGG")
const flag_id flag_ALLERGEN_FRUIT ("ALLERGEN_FRUIT")
const flag_id flag_ALLERGEN_JUNK ("ALLERGEN_JUNK")
const flag_id flag_ALLERGEN_MEAT ("ALLERGEN_MEAT")
const flag_id flag_ALLERGEN_MILK ("ALLERGEN_MILK")
const flag_id flag_ALLERGEN_NUT ("ALLERGEN_NUT")
const flag_id flag_ALLERGEN_VEGGY ("ALLERGEN_VEGGY")
const flag_id flag_ALLERGEN_WHEAT ("ALLERGEN_WHEAT")
const flag_id flag_ALLERGEN_WOOL ("ALLERGEN_WOOL")
const flag_id flag_ALLOWS_BODY_BLOCK ("ALLOWS_BODY_BLOCK")
const flag_id flag_ALLOWS_NATURAL_ATTACKS ("ALLOWS_NATURAL_ATTACKS")
const flag_id flag_ALLOWS_REMOTE_USE ("ALLOWS_REMOTE_USE")
const flag_id flag_ALWAYS_TWOHAND ("ALWAYS_TWOHAND")
const flag_id flag_ANIMAL_PRODUCT ("ANIMAL_PRODUCT")
const flag_id flag_AURA ("AURA")
const flag_id flag_BAROMETER ("BAROMETER")
const flag_id flag_BASH_IMMUNE ("BASH_IMMUNE")
const flag_id flag_BELTED ("BELTED")
const flag_id flag_BELT_CLIP ("BELT_CLIP")
const flag_id flag_BIONIC_FUEL_SOURCE ("BIONIC_FUEL_SOURCE")
const flag_id flag_BIONIC_GUN ("BIONIC_GUN")
const flag_id flag_BIONIC_INSTALLATION_DATA ("BIONIC_INSTALLATION_DATA")
const flag_id flag_BIONIC_TOGGLED ("BIONIC_TOGGLED")
const flag_id flag_BIONIC_WEAPON ("BIONIC_WEAPON")
const flag_id flag_BIO_IMMUNE ("BIO_IMMUNE")
const flag_id flag_BIPOD ("BIPOD")
const flag_id flag_BIRD ("BIRD")
const flag_id flag_BLED ("BLED")
const flag_id flag_BLIND ("BLIND")
const flag_id flag_BLOCK_WHILE_WORN ("BLOCK_WHILE_WORN")
const flag_id flag_BOMB ("BOMB")
const flag_id flag_BRASS_CATCHER ("BRASS_CATCHER")
const flag_id flag_BULLET_IMMUNE ("BULLET_IMMUNE")
const flag_id flag_BURNOUT ("BURNOUT")
const flag_id flag_BYPRODUCT ("BYPRODUCT")
const flag_id flag_CABLE_SPOOL ("CABLE_SPOOL")
const flag_id flag_CAMERA_PRO ("CAMERA_PRO")
const flag_id flag_CANNIBAL ("CANNIBAL")
const flag_id flag_CANT_HEAL_EVERYONE ("CANT_HEAL_EVERYONE")
const flag_id flag_CANT_WEAR ("CANT_WEAR")
const flag_id flag_CARNIVORE_OK ("CARNIVORE_OK")
const flag_id flag_CASING ("CASING")
const flag_id flag_CATTLE ("CATTLE")
const flag_id flag_CHALLENGE ("CHALLENGE")
const flag_id flag_CHARGEDIM ("CHARGEDIM")
const flag_id flag_CHOKE ("CHOKE")
const flag_id flag_CITY_START ("CITY_START")
const flag_id flag_COLD ("COLD")
const flag_id flag_COLD_IMMUNE ("COLD_IMMUNE")
const flag_id flag_COLLAPSED_STOCK ("COLLAPSED_STOCK")
const flag_id flag_COLLAPSE_CONTENTS ("COLLAPSE_CONTENTS")
const flag_id flag_COLLAPSIBLE_STOCK ("COLLAPSIBLE_STOCK")
const flag_id flag_COLLAR ("COLLAR")
const flag_id flag_COMBAT_TOGGLEABLE ("COMBAT_TOGGLEABLE")
const flag_id flag_CONDUCTIVE ("CONDUCTIVE")
const flag_id flag_CONSUMABLE ("CONSUMABLE")
const flag_id flag_COOKED ("COOKED")
const flag_id flag_CORPSE ("CORPSE")
const flag_id flag_CORROSIVE ("CORROSIVE")
const flag_id flag_CRUTCHES ("CRUTCHES")
const flag_id flag_CUSTOM_EXPLOSION ("CUSTOM_EXPLOSION")
const flag_id flag_CUT_HARVEST ("CUT_HARVEST")
const flag_id flag_CUT_IMMUNE ("CUT_IMMUNE")
const flag_id flag_DANGEROUS ("DANGEROUS")
const flag_id flag_DEAF ("DEAF")
const flag_id flag_DIAMOND ("DIAMOND")
const flag_id flag_DIG_TOOL ("DIG_TOOL")
const flag_id flag_DIMENSIONAL_ANCHOR ("DIMENSIONAL_ANCHOR")
const flag_id flag_DIRTY ("DIRTY")
const flag_id flag_DISABLE_SIGHTS ("DISABLE_SIGHTS")
const flag_id flag_DROP_ACTION_ONLY_IF_LIQUID ("DROP_ACTION_ONLY_IF_LIQUID")
const flag_id flag_DURABLE_MELEE ("DURABLE_MELEE")
const flag_id flag_EATEN_COLD ("EATEN_COLD")
const flag_id flag_EATEN_HOT ("EATEN_HOT")
const flag_id flag_EDIBLE_FROZEN ("EDIBLE_FROZEN")
const flag_id flag_EFFECT_IMPEDING ("EFFECT_IMPEDING")
const flag_id flag_EFFECT_LIMB_DISABLE_CONDITIONAL_FLAGS ("EFFECT_LIMB_DISABLE_CONDITIONAL_FLAGS")
const flag_id flag_EFFECT_LIMB_SCORE_MOD ("EFFECT_LIMB_SCORE_MOD")
const flag_id flag_EFFECT_LIMB_SCORE_MOD_LOCAL ("EFFECT_LIMB_SCORE_MOD_LOCAL")
const flag_id flag_ELECTRIC_IMMUNE ("ELECTRIC_IMMUNE")
const flag_id flag_ELECTRONIC ("ELECTRONIC")
const flag_id flag_ETHEREAL_ITEM ("ETHEREAL_ITEM")
const flag_id flag_EXO_ARM_PLATE ("EXO_ARM_PLATE")
const flag_id flag_EXO_BOOT_PLATE ("EXO_BOOT_PLATE")
const flag_id flag_EXO_GLOVE_PLATE ("EXO_GLOVE_PLATE")
const flag_id flag_EXO_HELMET_GADGET ("EXO_HELMET_GADGET")
const flag_id flag_EXO_HELMET_PLATE ("EXO_HELMET_PLATE")
const flag_id flag_EXO_LARGE_GADGET ("EXO_LARGE_GADGET")
const flag_id flag_EXO_LEG_PLATE ("EXO_LEG_PLATE")
const flag_id flag_EXO_MEDIUM_GADGET ("EXO_MEDIUM_GADGET")
const flag_id flag_EXO_PSU ("EXO_PSU")
const flag_id flag_EXO_PSU_PLATE ("EXO_PSU_PLATE")
const flag_id flag_EXO_SMALL_GADGET ("EXO_SMALL_GADGET")
const flag_id flag_EXO_TORSO_PLATE ("EXO_TORSO_PLATE")
const flag_id flag_EXO_UNDERLAYER ("EXO_UNDERLAYER")
const flag_id flag_FAKE_MILL ("FAKE_MILL")
const flag_id flag_FAKE_SMOKE ("FAKE_SMOKE")
const flag_id flag_FANCY ("FANCY")
const flag_id flag_FELINE ("FELINE")
const flag_id flag_FERTILIZER ("FERTILIZER")
const flag_id flag_FIELD_DRESS ("FIELD_DRESS")
const flag_id flag_FIELD_DRESS_FAILED ("FIELD_DRESS_FAILED")
const flag_id flag_FILTHY ("FILTHY")
const flag_id flag_FIN ("FIN")
const flag_id flag_FIRE ("FIRE")
const flag_id flag_FIRESTARTER ("FIRESTARTER")
const flag_id flag_FIREWOOD ("FIREWOOD")
const flag_id flag_FIRE_100 ("FIRE_100")
const flag_id flag_FIRE_20 ("FIRE_20")
const flag_id flag_FIRE_50 ("FIRE_50")
const flag_id flag_FIRE_TWOHAND ("FIRE_TWOHAND")
const flag_id flag_FIT ("FIT")
const flag_id flag_FIX_FARSIGHT ("FIX_FARSIGHT")
const flag_id flag_FIX_NEARSIGHT ("FIX_NEARSIGHT")
const flag_id flag_FLAMING ("FLAMING")
const flag_id flag_FLASH_PROTECTION ("FLASH_PROTECTION")
const flag_id flag_FLOTATION ("FLOTATION")
const flag_id flag_FOLDED_STOCK ("FOLDED_STOCK")
const flag_id flag_FORAGE_HALLU ("FORAGE_HALLU")
const flag_id flag_FORAGE_POISON ("FORAGE_POISON")
const flag_id flag_FRAGILE ("FRAGILE")
const flag_id flag_FRAGILE_MELEE ("FRAGILE_MELEE")
const flag_id flag_FREEZERBURN ("FREEZERBURN")
const flag_id flag_FRESH_GRAIN ("FRESH_GRAIN")
const flag_id flag_FROM_FROZEN_LIQUID ("FROM_FROZEN_LIQUID")
const flag_id flag_FROZEN ("FROZEN")
const flag_id flag_FUNGAL_VECTOR ("FUNGAL_VECTOR")
const flag_id flag_GAS_DISCOUNT ("GAS_DISCOUNT")
const flag_id flag_GAS_PROOF ("GAS_PROOF")
const flag_id flag_GIBBED ("GIBBED")
const flag_id flag_GNV_EFFECT ("GNV_EFFECT")
const flag_id flag_HARD ("HARD")
const flag_id flag_HEAT_IMMUNE ("HEAT_IMMUNE")
const flag_id flag_HEMOVORE_FUN ("HEMOVORE_FUN")
const flag_id flag_HIDDEN_HALLU ("HIDDEN_HALLU")
const flag_id flag_HIDDEN_POISON ("HIDDEN_POISON")
const flag_id flag_HOOD ("HOOD")
const flag_id flag_HOT ("HOT")
const flag_id flag_HURT_WHEN_WIELDED ("HURT_WHEN_WIELDED")
const flag_id flag_HYGROMETER ("HYGROMETER")
const flag_id flag_INEDIBLE ("INEDIBLE")
const flag_id flag_INITIAL_PART ("INITIAL_PART")
const flag_id flag_INSPIRATIONAL ("INSPIRATIONAL")
const flag_id flag_INSTALL_DIFFICULT ("INSTALL_DIFFICULT")
const flag_id flag_INTEGRATED ("INTEGRATED")
const flag_id flag_IN_CBM ("IN_CBM")
const flag_id flag_IRRADIATED ("IRRADIATED")
const flag_id flag_IRREMOVABLE ("IRREMOVABLE")
const flag_id flag_IR_EFFECT ("IR_EFFECT")
const flag_id flag_IS_ARMOR ("IS_ARMOR")
const flag_id flag_IS_PET_ARMOR ("IS_PET_ARMOR")
const flag_id flag_IS_UPS ("IS_UPS")
const flag_id flag_ITEM_BROKEN ("ITEM_BROKEN")
const flag_id flag_LASER_SIGHT ("LASER_SIGHT")
const flag_id flag_LEAK_ALWAYS ("LEAK_ALWAYS")
const flag_id flag_LEAK_DAM ("LEAK_DAM")
const flag_id flag_LITCIG ("LITCIG")
const flag_id flag_LUPINE ("LUPINE")
const flag_id flag_MAGICAL ("MAGICAL")
const flag_id flag_MAGIC_FOCUS ("MAGIC_FOCUS")
const flag_id flag_MAG_BELT ("MAG_BELT")
const flag_id flag_MAG_BULKY ("MAG_BULKY")
const flag_id flag_MAG_DESTROY ("MAG_DESTROY")
const flag_id flag_MAG_EJECT ("MAG_EJECT")
const flag_id flag_MC_HAS_DATA ("MC_HAS_DATA")
const flag_id flag_MC_MOBILE ("MC_MOBILE")
const flag_id flag_MECH_BAT ("MECH_BAT")
const flag_id flag_MELTS ("MELTS")
const flag_id flag_MESSY ("MESSY")
const flag_id flag_MISSION_ITEM ("MISSION_ITEM")
const flag_id flag_MOUNTED_GUN ("MOUNTED_GUN")
const flag_id flag_MOUSE ("MOUSE")
const flag_id flag_MUNDANE ("MUNDANE")
const flag_id flag_MUSHY ("MUSHY")
const flag_id flag_MUTE ("MUTE")
const flag_id flag_MYCUS_OK ("MYCUS_OK")
const flag_id flag_NANOFAB_REPAIR ("NANOFAB_REPAIR")
const flag_id flag_NANOFAB_TEMPLATE ("NANOFAB_TEMPLATE")
const flag_id flag_NANOFAB_TEMPLATE_SINGLE_USE ("NANOFAB_TEMPLATE_SINGLE_USE")
const flag_id flag_NATURAL_WEAPON ("NATURAL_WEAPON")
const flag_id flag_NEEDS_NO_LUBE ("NEEDS_NO_LUBE")
const flag_id flag_NEEDS_UNFOLD ("NEEDS_UNFOLD")
const flag_id flag_NEGATIVE_MONOTONY_OK ("NEGATIVE_MONOTONY_OK")
const flag_id flag_NEVER_JAMS ("NEVER_JAMS")
const flag_id flag_NONCONDUCTIVE ("NONCONDUCTIVE")
const flag_id flag_NON_FOULING ("NON_FOULING")
const flag_id flag_NORMAL ("NORMAL")
const flag_id flag_NO_CLEAN ("NO_CLEAN")
const flag_id flag_NO_CVD ("NO_CVD")
const flag_id flag_NO_DROP ("NO_DROP")
const flag_id flag_NO_INGEST ("NO_INGEST")
const flag_id flag_NO_PACKED ("NO_PACKED")
const flag_id flag_NO_PARASITES ("NO_PARASITES")
const flag_id flag_NO_RELOAD ("NO_RELOAD")
const flag_id flag_NO_REPAIR ("NO_REPAIR")
const flag_id flag_NO_SALVAGE ("NO_SALVAGE")
const flag_id flag_NO_STERILE ("NO_STERILE")
const flag_id flag_NO_TAKEOFF ("NO_TAKEOFF")
const flag_id flag_NO_TURRET ("NO_TURRET")
const flag_id flag_NO_UNLOAD ("NO_UNLOAD")
const flag_id flag_NO_UNWIELD ("NO_UNWIELD")
const flag_id flag_NO_WEAR_EFFECT ("NO_WEAR_EFFECT")
const flag_id flag_NPC_ACTIVATE ("NPC_ACTIVATE")
const flag_id flag_NPC_ALT_ATTACK ("NPC_ALT_ATTACK")
const flag_id flag_NPC_SAFE ("NPC_SAFE")
const flag_id flag_NPC_THROWN ("NPC_THROWN")
const flag_id flag_NPC_THROW_NOW ("NPC_THROW_NOW")
const flag_id flag_NUTRIENT_OVERRIDE ("NUTRIENT_OVERRIDE")
const flag_id flag_OLD_CURRENCY ("OLD_CURRENCY")
const flag_id flag_ONLY_ONE ("ONLY_ONE")
const flag_id flag_ORGANIC ("ORGANIC")
const flag_id flag_OUTER ("OUTER")
const flag_id flag_OVERSIZE ("OVERSIZE")
const flag_id flag_PADDED ("PADDED")
const flag_id flag_PAIN_IMMUNE ("PAIN_IMMUNE")
const flag_id flag_PALS_LARGE ("PALS_LARGE")
const flag_id flag_PALS_MEDIUM ("PALS_MEDIUM")
const flag_id flag_PALS_SMALL ("PALS_SMALL")
const flag_id flag_PARTIAL_DEAF ("PARTIAL_DEAF")
const flag_id flag_PERFECT_LOCKPICK ("PERFECT_LOCKPICK")
const flag_id flag_PERPETUAL ("PERPETUAL")
const flag_id flag_PERSONAL ("PERSONAL")
const flag_id flag_PLACE_RANDOMLY ("PLACE_RANDOMLY")
const flag_id flag_POCKETS ("POCKETS")
const flag_id flag_POLEARM ("POLEARM")
const flag_id flag_POWERARMOR_COMPATIBLE ("POWERARMOR_COMPATIBLE")
const flag_id flag_POWERED ("POWERED")
const flag_id flag_PREDATOR_FUN ("PREDATOR_FUN")
const flag_id flag_PRIMITIVE_RANGED_WEAPON ("PRIMITIVE_RANGED_WEAPON")
const flag_id flag_PROCESSING ("PROCESSING")
const flag_id flag_PROCESSING_RESULT ("PROCESSING_RESULT")
const flag_id flag_PSEUDO ("PSEUDO")
const flag_id flag_PSEUDOPOD_GRASP ("PSEUDOPOD_GRASP")
const flag_id flag_PSYSHIELD_PARTIAL ("PSYSHIELD_PARTIAL")
const flag_id flag_PULPED ("PULPED")
const flag_id flag_PUMP_ACTION ("PUMP_ACTION")
const flag_id flag_PUMP_RAIL_COMPATIBLE ("PUMP_RAIL_COMPATIBLE")
const flag_id flag_QUARTERED ("QUARTERED")
const flag_id flag_RABBIT ("RABBIT")
const flag_id flag_RADIOACTIVE ("RADIOACTIVE")
const flag_id flag_RADIOCAR ("RADIOCAR")
const flag_id flag_RADIOCARITEM ("RADIOCARITEM")
const flag_id flag_RADIOSIGNAL_1 ("RADIOSIGNAL_1")
const flag_id flag_RADIOSIGNAL_2 ("RADIOSIGNAL_2")
const flag_id flag_RADIOSIGNAL_3 ("RADIOSIGNAL_3")
const flag_id flag_RADIO_ACTIVATION ("RADIO_ACTIVATION")
const flag_id flag_RADIO_CONTAINER ("RADIO_CONTAINER")
const flag_id flag_RADIO_INVOKE_PROC ("RADIO_INVOKE_PROC")
const flag_id flag_RADIO_MOD ("RADIO_MOD")
const flag_id flag_RADIO_MODABLE ("RADIO_MODABLE")
const flag_id flag_RAD_PROOF ("RAD_PROOF")
const flag_id flag_RAD_RESIST ("RAD_RESIST")
const flag_id flag_RAINPROOF ("RAINPROOF")
const flag_id flag_RAIN_PROTECT ("RAIN_PROTECT")
const flag_id flag_RAT ("RAT")
const flag_id flag_RAW ("RAW")
const flag_id flag_REACH ("REACH")
const flag_id flag_REACH3 ("REACH3")
const flag_id flag_REACH_ATTACK ("REACH_ATTACK")
const flag_id flag_REBREATHER ("REBREATHER")
const flag_id flag_RECHARGE ("RECHARGE")
const flag_id flag_REDUCED_BASHING ("REDUCED_BASHING")
const flag_id flag_REDUCED_WEIGHT ("REDUCED_WEIGHT")
const flag_id flag_RELOAD_AND_SHOOT ("RELOAD_AND_SHOOT")
const flag_id flag_RELOAD_EJECT ("RELOAD_EJECT")
const flag_id flag_RELOAD_ONE ("RELOAD_ONE")
const flag_id flag_REMOVED_STOCK ("REMOVED_STOCK")
const flag_id flag_REQUIRES_BALANCE ("REQUIRES_BALANCE")
const flag_id flag_REQUIRES_TINDER ("REQUIRES_TINDER")
const flag_id flag_RESTRICT_HANDS ("RESTRICT_HANDS")
const flag_id flag_REVIVE_SPECIAL ("REVIVE_SPECIAL")
const flag_id flag_ROLLER_INLINE ("ROLLER_INLINE")
const flag_id flag_ROLLER_ONE ("ROLLER_ONE")
const flag_id flag_ROLLER_QUAD ("ROLLER_QUAD")
const flag_id flag_SAFECRACK ("SAFECRACK")
const flag_id flag_SEED_HARVEST ("SEED_HARVEST")
const flag_id flag_SEMITANGIBLE ("SEMITANGIBLE")
const flag_id flag_SHREDDED ("SHREDDED")
const flag_id flag_SHRUB ("SHRUB")
const flag_id flag_SINGLE_USE ("SINGLE_USE")
const flag_id flag_SKINNED ("SKINNED")
const flag_id flag_SKINTIGHT ("SKINTIGHT")
const flag_id flag_SLEEP_AID ("SLEEP_AID")
const flag_id flag_SLEEP_AID_CONTAINER ("SLEEP_AID_CONTAINER")
const flag_id flag_SLEEP_IGNORE ("SLEEP_IGNORE")
const flag_id flag_SLOW_WIELD ("SLOW_WIELD")
const flag_id flag_SMOKABLE ("SMOKABLE")
const flag_id flag_SMOKED ("SMOKED")
const flag_id flag_SOFT ("SOFT")
const flag_id flag_SOLARPACK ("SOLARPACK")
const flag_id flag_SOLARPACK_ON ("SOLARPACK_ON")
const flag_id flag_SPAWN_ACTIVE ("SPAWN_ACTIVE")
const flag_id flag_SPEAR ("SPEAR")
const flag_id flag_SPEEDLOADER ("SPEEDLOADER")
const flag_id flag_SPEEDLOADER_CLIP ("SPEEDLOADER_CLIP")
const flag_id flag_SPLINT ("SPLINT")
const flag_id flag_STAB ("STAB")
const flag_id flag_STAB_IMMUNE ("STAB_IMMUNE")
const flag_id flag_STRICT_HUMANITARIANISM ("STRICT_HUMANITARIANISM")
const flag_id flag_STR_DRAW ("STR_DRAW")
const flag_id flag_STR_RELOAD ("STR_RELOAD")
const flag_id flag_STURDY ("STURDY")
const flag_id flag_SUN_GLASSES ("SUN_GLASSES")
const flag_id flag_SUPER_FANCY ("SUPER_FANCY")
const flag_id flag_SWIM_GOGGLES ("SWIM_GOGGLES")
const flag_id flag_TACK ("TACK")
const flag_id flag_TANGLE ("TANGLE")
const flag_id flag_TARDIS ("TARDIS")
const flag_id flag_THERMOMETER ("THERMOMETER")
const flag_id flag_TIE_UP ("TIE_UP")
const flag_id flag_TINDER ("TINDER")
const flag_id flag_TOBACCO ("TOBACCO")
const flag_id flag_TOUGH_FEET ("TOUGH_FEET")
const flag_id flag_TOURNIQUET ("TOURNIQUET")
const flag_id flag_TOW_CABLE ("TOW_CABLE")
const flag_id flag_TRADER_AVOID ("TRADER_AVOID")
const flag_id flag_TRADER_KEEP ("TRADER_KEEP")
const flag_id flag_TRADER_KEEP_EQUIPPED ("TRADER_KEEP_EQUIPPED")
const flag_id flag_TWO_WAY_RADIO ("TWO_WAY_RADIO")
const flag_id flag_UNBREAKABLE ("UNBREAKABLE")
const flag_id flag_UNBREAKABLE_MELEE ("UNBREAKABLE_MELEE")
const flag_id flag_UNDERFED ("UNDERFED")
const flag_id flag_UNDERSIZE ("UNDERSIZE")
const flag_id flag_UNDERWATER_GUN ("UNDERWATER_GUN")
const flag_id flag_UNRECOVERABLE ("UNRECOVERABLE")
const flag_id flag_UNRESTRICTED ("UNRESTRICTED")
const flag_id flag_URSINE_HONEY ("URSINE_HONEY")
const flag_id flag_USES_BIONIC_POWER ("USES_BIONIC_POWER")
const flag_id flag_USE_EAT_VERB ("USE_EAT_VERB")
const flag_id flag_USE_PLAYER_ENERGY ("USE_PLAYER_ENERGY")
const flag_id flag_USE_POWER_WHEN_HIT ("USE_POWER_WHEN_HIT")
const flag_id flag_USE_UPS ("USE_UPS")
const flag_id flag_VARSIZE ("VARSIZE")
const flag_id flag_VEHICLE ("VEHICLE")
const flag_id flag_WAIST ("WAIST")
const flag_id flag_WATCH ("WATCH")
const flag_id flag_WATERPROOF ("WATERPROOF")
const flag_id flag_WATERPROOF_GUN ("WATERPROOF_GUN")
const flag_id flag_WATER_BREAK ("WATER_BREAK")
const flag_id flag_WATER_BREAK_ACTIVE ("WATER_BREAK_ACTIVE")
const flag_id flag_WATER_DISSOLVE ("WATER_DISSOLVE")
const flag_id flag_WATER_EXTINGUISH ("WATER_EXTINGUISH")
const flag_id flag_WATER_FRIENDLY ("WATER_FRIENDLY")
const flag_id flag_WET ("WET")
const flag_id flag_WHIP ("WHIP")
const flag_id flag_WIND_EXTINGUISH ("WIND_EXTINGUISH")
const flag_id flag_WONT_TRAIN_MARKSMANSHIP ("WONT_TRAIN_MARKSMANSHIP")
const flag_id flag_WRITE_MESSAGE ("WRITE_MESSAGE")
const flag_id flag_ZERO_WEIGHT ("ZERO_WEIGHT")
const flag_id flag_ZOOM ("ZOOM")
const flag_id flag_wooled ("wooled")
const flag_id json_flag_HIDDEN_ITEM ("HIDDEN_ITEM")
static const flag_id json_flag_null ("null")
const flag_id flag_NULL = json_flag_null
generic_factory< json_flag > anonymous_namespace{flag.cpp}::json_flags_all ("json_flags")
Variable Documentation
flag_ABLATIVE_LARGE
const flag_id flag_ABLATIVE_LARGE("ABLATIVE_LARGE") ("ABLATIVE_LARGE")
flag_ABLATIVE_MEDIUM
const flag_id flag_ABLATIVE_MEDIUM("ABLATIVE_MEDIUM") ("ABLATIVE_MEDIUM")
flag_ACID
const flag_id flag_ACID("ACID") ("ACID")
Referenced by iuse::blech().
flag_ACID_IMMUNE
const flag_id flag_ACID_IMMUNE("ACID_IMMUNE") ("ACID_IMMUNE")
flag_ACT_IN_FIRE
const flag_id flag_ACT_IN_FIRE("ACT_IN_FIRE") ("ACT_IN_FIRE")
Referenced by map::add_item().
flag_ACT_ON_RANGED_HIT
const flag_id flag_ACT_ON_RANGED_HIT("ACT_ON_RANGED_HIT") ("ACT_ON_RANGED_HIT")
Referenced by Character::throw_item().
flag_ACTIVATE_ON_PLACE
const flag_id flag_ACTIVATE_ON_PLACE("ACTIVATE_ON_PLACE") ("ACTIVATE_ON_PLACE")
Referenced by map::add_item().
flag_ACTIVE_CLOAKING
const flag_id flag_ACTIVE_CLOAKING("ACTIVE_CLOAKING") ("ACTIVE_CLOAKING")
Referenced by outfit::is_wearing_active_optcloak().
flag_ACTIVE_GENERATOR
const flag_id flag_ACTIVE_GENERATOR("ACTIVE_GENERATOR") ("ACTIVE_GENERATOR")
flag_ALARMCLOCK
const flag_id flag_ALARMCLOCK("ALARMCLOCK") ("ALARMCLOCK")
Referenced by Character::has_alarm_clock().
flag_ALLERGEN_BREAD
const flag_id flag_ALLERGEN_BREAD("ALLERGEN_BREAD") ("ALLERGEN_BREAD")
Referenced by Item_factory::set_allergy_flags().
flag_ALLERGEN_CHEESE
const flag_id flag_ALLERGEN_CHEESE("ALLERGEN_CHEESE") ("ALLERGEN_CHEESE")
Referenced by Item_factory::set_allergy_flags().
flag_ALLERGEN_DRIED_VEGETABLE
const flag_id flag_ALLERGEN_DRIED_VEGETABLE("ALLERGEN_DRIED_VEGETABLE") ("ALLERGEN_DRIED_VEGETABLE")
Referenced by Item_factory::set_allergy_flags().
flag_ALLERGEN_EGG
const flag_id flag_ALLERGEN_EGG("ALLERGEN_EGG") ("ALLERGEN_EGG")
Referenced by Item_factory::set_allergy_flags().
flag_ALLERGEN_FRUIT
const flag_id flag_ALLERGEN_FRUIT("ALLERGEN_FRUIT") ("ALLERGEN_FRUIT")
Referenced by Character::allergy_type(), and Item_factory::set_allergy_flags().
flag_ALLERGEN_JUNK
const flag_id flag_ALLERGEN_JUNK("ALLERGEN_JUNK") ("ALLERGEN_JUNK")
Referenced by Character::allergy_type(), Character::modify_morale(), Item_factory::set_allergy_flags(), and Character::will_eat().
flag_ALLERGEN_MEAT
const flag_id flag_ALLERGEN_MEAT("ALLERGEN_MEAT") ("ALLERGEN_MEAT")
Referenced by Character::allergy_type(), and Item_factory::set_allergy_flags().
flag_ALLERGEN_MILK
const flag_id flag_ALLERGEN_MILK("ALLERGEN_MILK") ("ALLERGEN_MILK")
Referenced by Character::allergy_type(), and Item_factory::set_allergy_flags().
flag_ALLERGEN_NUT
const flag_id flag_ALLERGEN_NUT("ALLERGEN_NUT") ("ALLERGEN_NUT")
Referenced by Item_factory::set_allergy_flags().
flag_ALLERGEN_VEGGY
const flag_id flag_ALLERGEN_VEGGY("ALLERGEN_VEGGY") ("ALLERGEN_VEGGY")
Referenced by Character::allergy_type(), and Item_factory::set_allergy_flags().
flag_ALLERGEN_WHEAT
const flag_id flag_ALLERGEN_WHEAT("ALLERGEN_WHEAT") ("ALLERGEN_WHEAT")
Referenced by Character::allergy_type(), and Item_factory::set_allergy_flags().
flag_ALLERGEN_WOOL
const flag_id flag_ALLERGEN_WOOL("ALLERGEN_WOOL") ("ALLERGEN_WOOL")
Referenced by Item_factory::set_allergy_flags().
flag_ALLOWS_BODY_BLOCK
const flag_id flag_ALLOWS_BODY_BLOCK("ALLOWS_BODY_BLOCK") ("ALLOWS_BODY_BLOCK")
Referenced by Character::block_hit().
flag_ALLOWS_NATURAL_ATTACKS
const flag_id flag_ALLOWS_NATURAL_ATTACKS("ALLOWS_NATURAL_ATTACKS") ("ALLOWS_NATURAL_ATTACKS")
Referenced by Character::active_light(), check_natural_attack_restricted_on_worn(), Character::mutation_attacks(), and Character::swim_speed().
flag_ALLOWS_REMOTE_USE
const flag_id flag_ALLOWS_REMOTE_USE("ALLOWS_REMOTE_USE") ("ALLOWS_REMOTE_USE")
Referenced by activatable_inventory_preset::get_denial(), ereader_inventory_preset::get_denial(), game::reload(), basecamp::scan_pseudo_items(), and avatar_action::use_item().
flag_ALWAYS_TWOHAND
const flag_id flag_ALWAYS_TWOHAND("ALWAYS_TWOHAND") ("ALWAYS_TWOHAND")
Referenced by Character::can_wield(), and item::is_two_handed().
flag_ANIMAL_PRODUCT
const flag_id flag_ANIMAL_PRODUCT("ANIMAL_PRODUCT") ("ANIMAL_PRODUCT")
Referenced by Character::can_wear().
flag_AURA
const flag_id flag_AURA("AURA") ("AURA")
Referenced by check_natural_attack_restricted_on_worn(), anonymous_namespace{armor_layers.cpp}::clothing_layer(), Item_factory::finalize_post_armor(), is_physical(), outfit::is_wearing_shoes(), and outfit::power_armor_conflicts().
flag_BAROMETER
const flag_id flag_BAROMETER("BAROMETER") ("BAROMETER")
Referenced by iuse::weather_tool().
flag_BASH_IMMUNE
const flag_id flag_BASH_IMMUNE("BASH_IMMUNE") ("BASH_IMMUNE")
flag_BELT_CLIP
const flag_id flag_BELT_CLIP("BELT_CLIP") ("BELT_CLIP")
flag_BELTED
const flag_id flag_BELTED("BELTED") ("BELTED")
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_layer(), Item_factory::finalize_post_armor(), and outfit::is_wearing_shoes().
flag_BIO_IMMUNE
const flag_id flag_BIO_IMMUNE("BIO_IMMUNE") ("BIO_IMMUNE")
flag_BIONIC_FUEL_SOURCE
const flag_id flag_BIONIC_FUEL_SOURCE("BIONIC_FUEL_SOURCE") ("BIONIC_FUEL_SOURCE")
Referenced by Character::get_bionic_fuels(), and anonymous_namespace{inventory_ui.cpp}::wielded_worn_category().
flag_BIONIC_GUN
const flag_id flag_BIONIC_GUN("BIONIC_GUN") ("BIONIC_GUN")
Referenced by Character::load().
flag_BIONIC_INSTALLATION_DATA
const flag_id flag_BIONIC_INSTALLATION_DATA("BIONIC_INSTALLATION_DATA") ("BIONIC_INSTALLATION_DATA")
Referenced by autodoc_internal().
flag_BIONIC_TOGGLED
const flag_id flag_BIONIC_TOGGLED("BIONIC_TOGGLED") ("BIONIC_TOGGLED")
Referenced by bionic_data::check_bionic_consistency(), and bionic::get_available_pseudo_items().
flag_BIONIC_WEAPON
const flag_id flag_BIONIC_WEAPON("BIONIC_WEAPON") ("BIONIC_WEAPON")
Referenced by Character::can_wield(), Character::load(), and mountable_gun_filter().
flag_BIPOD
const flag_id flag_BIPOD("BIPOD") ("BIPOD")
Referenced by item::gun_info(), and item::gun_recoil().
flag_BIRD
const flag_id flag_BIRD("BIRD") ("BIRD")
Referenced by Character::can_eat().
flag_BLED
const flag_id flag_BLED("BLED") ("BLED")
Referenced by activity_handlers::butcher_finish(), butcher_submenu(), and set_up_butchery().
flag_BLIND
const flag_id flag_BLIND("BLIND") ("BLIND")
Referenced by suffer::from_sunburn(), Character::is_blind(), and game::print_items_info().
flag_BLOCK_WHILE_WORN
const flag_id flag_BLOCK_WHILE_WORN("BLOCK_WHILE_WORN") ("BLOCK_WHILE_WORN")
Referenced by outfit::best_shield(), Character::block_hit(), melee::blocking_ability(), and anatomy::select_blocking_part().
flag_BOMB
const flag_id flag_BOMB("BOMB") ("BOMB")
Referenced by map::add_item(), iuse_transform::do_transform(), Item_factory::npc_implied_flags(), item::properties_info(), iuse::radiocontrol(), npc::value(), and npc::wants_to_buy().
flag_BRASS_CATCHER
const flag_id flag_BRASS_CATCHER("BRASS_CATCHER") ("BRASS_CATCHER")
Referenced by cycle_action(), gunmod_remove_activity_actor::gunmod_unload(), Character::rate_action_unload(), and Character::unload().
flag_BULLET_IMMUNE
const flag_id flag_BULLET_IMMUNE("BULLET_IMMUNE") ("BULLET_IMMUNE")
flag_BURNOUT
const flag_id flag_BURNOUT("BURNOUT") ("BURNOUT")
Referenced by item::tool_info().
flag_BYPRODUCT
const flag_id flag_BYPRODUCT("BYPRODUCT") ("BYPRODUCT")
Referenced by item::components_to_string(), and Character::compute_effective_nutrients().
flag_CABLE_SPOOL
const flag_id flag_CABLE_SPOOL("CABLE_SPOOL") ("CABLE_SPOOL")
Referenced by Character::activate_bionic(), Character::get_cable_solar(), Character::get_cable_ups(), Character::get_cable_vehicle(), item_pocket::is_compatible(), link_up_actor::link_extend_cable(), item::link_name(), vehicle::part_to_item(), item::process_internal(), item::process_link(), link_up_actor::remove_extensions(), and link_up_actor::use().
flag_CAMERA_PRO
const flag_id flag_CAMERA_PRO("CAMERA_PRO") ("CAMERA_PRO")
Referenced by iuse::camera().
flag_CANNIBAL
const flag_id flag_CANNIBAL("CANNIBAL") ("CANNIBAL")
flag_CANT_HEAL_EVERYONE
const flag_id flag_CANT_HEAL_EVERYONE("CANT_HEAL_EVERYONE") ("CANT_HEAL_EVERYONE")
flag_CANT_WEAR
const flag_id flag_CANT_WEAR("CANT_WEAR") ("CANT_WEAR")
Referenced by Character::can_wear(), and outfit::is_worn_module().
flag_CARNIVORE_OK
const flag_id flag_CARNIVORE_OK("CARNIVORE_OK") ("CARNIVORE_OK")
Referenced by Character::can_eat(), Character::modify_morale(), Item_factory::set_allergy_flags(), and Character::will_eat().
flag_CASING
const flag_id flag_CASING("CASING") ("CASING")
Referenced by item_pocket::_can_contain(), item_pocket::ammo_consume(), item_pocket::can_reload_with(), item_pocket::casings_handle(), cycle_action(), item_pocket::full(), Character::perform_technique(), and item_pocket::remaining_ammo_capacity().
flag_CATTLE
const flag_id flag_CATTLE("CATTLE") ("CATTLE")
Referenced by Character::can_eat(), and mattack::eat_crop().
flag_CHALLENGE
const flag_id flag_CHALLENGE("CHALLENGE") ("CHALLENGE")
Referenced by avatar::randomize().
flag_CHARGEDIM
const flag_id flag_CHARGEDIM("CHARGEDIM") ("CHARGEDIM")
Referenced by item::getlight_emit().
flag_CHOKE
const flag_id flag_CHOKE("CHOKE") ("CHOKE")
Referenced by Character::fire_gun().
flag_CITY_START
const flag_id flag_CITY_START("CITY_START") ("CITY_START")
Referenced by avatar::randomize().
flag_COLD
const flag_id flag_COLD("COLD") ("COLD")
Referenced by item::calc_rot(), item::cold_up(), Character::fun_for(), item::heat_up(), item::io(), item::is_same_temperature(), item::set_temp_flags(), item::stacks_with(), and anonymous_namespace{item_tname.cpp}::temperature().
flag_COLD_IMMUNE
const flag_id flag_COLD_IMMUNE("COLD_IMMUNE") ("COLD_IMMUNE")
flag_COLLAPSE_CONTENTS
const flag_id flag_COLLAPSE_CONTENTS("COLLAPSE_CONTENTS") ("COLLAPSE_CONTENTS")
Referenced by item::item().
flag_COLLAPSED_STOCK
const flag_id flag_COLLAPSED_STOCK("COLLAPSED_STOCK") ("COLLAPSED_STOCK")
Referenced by item::collapsed_volume_delta(), item::length(), and anonymous_namespace{item_tname.cpp}::tags().
flag_COLLAPSIBLE_STOCK
const flag_id flag_COLLAPSIBLE_STOCK("COLLAPSIBLE_STOCK") ("COLLAPSIBLE_STOCK")
Referenced by Character::aim_factor_from_volume(), and item::collapsed_volume_delta().
flag_COLLAR
const flag_id flag_COLLAR("COLLAR") ("COLLAR")
Referenced by outfit::collar_warmth(), suffer::from_sunburn(), and outfit::prepare_bodymap_info().
flag_COMBAT_TOGGLEABLE
const flag_id flag_COMBAT_TOGGLEABLE("COMBAT_TOGGLEABLE") ("COMBAT_TOGGLEABLE")
Referenced by outfit::activate_combat_items(), and outfit::deactivate_combat_items().
flag_CONDUCTIVE
const flag_id flag_CONDUCTIVE("CONDUCTIVE") ("CONDUCTIVE")
Referenced by item::conductive(), and item::properties_info().
flag_CONSUMABLE
const flag_id flag_CONSUMABLE("CONSUMABLE") ("CONSUMABLE")
Referenced by item::gunmod_info(), and Character::handle_gun_damage().
flag_COOKED
const flag_id flag_COOKED("COOKED") ("COOKED")
Referenced by adjust_new_comp(), Character::compute_nutrient_range(), and smoker_finalize().
flag_CORPSE
const flag_id flag_CORPSE("CORPSE") ("CORPSE")
Referenced by Item_factory::add_special_pockets(), item::durability_indicator(), mattack::eat_carrion(), item::is_corpse(), is_physical(), item::item(), and item::type_name().
flag_CORROSIVE
const flag_id flag_CORROSIVE("CORROSIVE") ("CORROSIVE")
Referenced by iuse::blech().
flag_CRUTCHES
const flag_id flag_CRUTCHES("CRUTCHES") ("CRUTCHES")
Referenced by Character::is_on_ground(), and avatar_action::move().
flag_CUSTOM_EXPLOSION
const flag_id flag_CUSTOM_EXPLOSION("CUSTOM_EXPLOSION") ("CUSTOM_EXPLOSION")
Referenced by Character::throw_item().
flag_CUT_HARVEST
const flag_id flag_CUT_HARVEST("CUT_HARVEST") ("CUT_HARVEST")
Referenced by iexamine::harvest_plant().
flag_CUT_IMMUNE
const flag_id flag_CUT_IMMUNE("CUT_IMMUNE") ("CUT_IMMUNE")
flag_DANGEROUS
const flag_id flag_DANGEROUS("DANGEROUS") ("DANGEROUS")
Referenced by item::is_dangerous(), Item_factory::npc_implied_flags(), and npc::wants_to_buy().
flag_DEAF
const flag_id flag_DEAF("DEAF") ("DEAF")
Referenced by Character::is_deaf(), and Character::is_immune_effect().
flag_DIAMOND
const flag_id flag_DIAMOND("DIAMOND") ("DIAMOND")
Referenced by anonymous_namespace{item.cpp}::_stacks_weapon_mods(), iexamine::cvdmachine(), item::damage_melee(), and anonymous_namespace{item_tname.cpp}::weapon_mods().
flag_DIG_TOOL
const flag_id flag_DIG_TOOL("DIG_TOOL") ("DIG_TOOL")
Referenced by can_do_activity_there(), mine_activity(), and avatar_action::move().
flag_DIMENSIONAL_ANCHOR
const flag_id flag_DIMENSIONAL_ANCHOR("DIMENSIONAL_ANCHOR") ("DIMENSIONAL_ANCHOR")
Referenced by trap::examine(), and game::phasing_move().
flag_DIRTY
const flag_id flag_DIRTY("DIRTY") ("DIRTY")
Referenced by anonymous_namespace{item.cpp}::_stacks_mushy_dirty(), Character::can_eat(), item::color_in_inventory(), anonymous_namespace{item_tname.cpp}::food_status(), and item::on_drop().
flag_DISABLE_SIGHTS
const flag_id flag_DISABLE_SIGHTS("DISABLE_SIGHTS") ("DISABLE_SIGHTS")
Referenced by Character::fastest_aiming_method_speed(), item::gunmod_info(), Character::most_accurate_aiming_method_limit(), and item::sight_dispersion().
flag_DROP_ACTION_ONLY_IF_LIQUID
const flag_id flag_DROP_ACTION_ONLY_IF_LIQUID("DROP_ACTION_ONLY_IF_LIQUID") ("DROP_ACTION_ONLY_IF_LIQUID")
Referenced by map::_add_item_or_charges().
flag_DURABLE_MELEE
const flag_id flag_DURABLE_MELEE("DURABLE_MELEE") ("DURABLE_MELEE")
Referenced by Character::handle_melee_wear().
flag_EATEN_COLD
const flag_id flag_EATEN_COLD("EATEN_COLD") ("EATEN_COLD")
Referenced by Character::fun_for(), heat_item(), and activity_handlers::heat_item_finish().
flag_EATEN_HOT
const flag_id flag_EATEN_HOT("EATEN_HOT") ("EATEN_HOT")
Referenced by Character::modify_morale(), and iuse::multicooker().
flag_EDIBLE_FROZEN
const flag_id flag_EDIBLE_FROZEN("EDIBLE_FROZEN") ("EDIBLE_FROZEN")
Referenced by Character::can_consume_as_is(), Character::can_eat(), and recipe::get_component_filter().
flag_EFFECT_IMPEDING
const flag_id flag_EFFECT_IMPEDING("EFFECT_IMPEDING") ("EFFECT_IMPEDING")
Referenced by Character::move_effects(), Character::try_remove_impeding_effect(), and Character::wait_effects().
flag_EFFECT_LIMB_DISABLE_CONDITIONAL_FLAGS
const flag_id flag_EFFECT_LIMB_DISABLE_CONDITIONAL_FLAGS("EFFECT_LIMB_DISABLE_CONDITIONAL_FLAGS") ("EFFECT_LIMB_DISABLE_CONDITIONAL_FLAGS")
Referenced by Character::count_bodypart_with_flag(), and Character::has_bodypart_with_flag().
flag_EFFECT_LIMB_SCORE_MOD
const flag_id flag_EFFECT_LIMB_SCORE_MOD("EFFECT_LIMB_SCORE_MOD") ("EFFECT_LIMB_SCORE_MOD")
Referenced by effect::disp_desc(), get_encumbrance_description(), and Character::get_limb_score().
flag_EFFECT_LIMB_SCORE_MOD_LOCAL
const flag_id flag_EFFECT_LIMB_SCORE_MOD_LOCAL("EFFECT_LIMB_SCORE_MOD_LOCAL") ("EFFECT_LIMB_SCORE_MOD_LOCAL")
Referenced by effect::disp_desc(), get_encumbrance_description(), Character::get_limb_score(), and Character::manipulator_score().
flag_ELECTRIC_IMMUNE
const flag_id flag_ELECTRIC_IMMUNE("ELECTRIC_IMMUNE") ("ELECTRIC_IMMUNE")
flag_ELECTRONIC
const flag_id flag_ELECTRONIC("ELECTRONIC") ("ELECTRONIC")
Referenced by explosion_handler::emp_blast(), item::process_internal(), avatar_action::use_item(), and game::water_affect_items().
flag_ETHEREAL_ITEM
const flag_id flag_ETHEREAL_ITEM("ETHEREAL_ITEM") ("ETHEREAL_ITEM")
Referenced by item::io().
flag_EXO_ARM_PLATE
const flag_id flag_EXO_ARM_PLATE("EXO_ARM_PLATE") ("EXO_ARM_PLATE")
flag_EXO_BOOT_PLATE
const flag_id flag_EXO_BOOT_PLATE("EXO_BOOT_PLATE") ("EXO_BOOT_PLATE")
flag_EXO_GLOVE_PLATE
const flag_id flag_EXO_GLOVE_PLATE("EXO_GLOVE_PLATE") ("EXO_GLOVE_PLATE")
flag_EXO_HELMET_GADGET
const flag_id flag_EXO_HELMET_GADGET("EXO_HELMET_GADGET") ("EXO_HELMET_GADGET")
flag_EXO_HELMET_PLATE
const flag_id flag_EXO_HELMET_PLATE("EXO_HELMET_PLATE") ("EXO_HELMET_PLATE")
flag_EXO_LARGE_GADGET
const flag_id flag_EXO_LARGE_GADGET("EXO_LARGE_GADGET") ("EXO_LARGE_GADGET")
flag_EXO_LEG_PLATE
const flag_id flag_EXO_LEG_PLATE("EXO_LEG_PLATE") ("EXO_LEG_PLATE")
flag_EXO_MEDIUM_GADGET
const flag_id flag_EXO_MEDIUM_GADGET("EXO_MEDIUM_GADGET") ("EXO_MEDIUM_GADGET")
flag_EXO_PSU
const flag_id flag_EXO_PSU("EXO_PSU") ("EXO_PSU")
flag_EXO_PSU_PLATE
const flag_id flag_EXO_PSU_PLATE("EXO_PSU_PLATE") ("EXO_PSU_PLATE")
flag_EXO_SMALL_GADGET
const flag_id flag_EXO_SMALL_GADGET("EXO_SMALL_GADGET") ("EXO_SMALL_GADGET")
flag_EXO_TORSO_PLATE
const flag_id flag_EXO_TORSO_PLATE("EXO_TORSO_PLATE") ("EXO_TORSO_PLATE")
flag_EXO_UNDERLAYER
const flag_id flag_EXO_UNDERLAYER("EXO_UNDERLAYER") ("EXO_UNDERLAYER")
flag_FAKE_MILL
const flag_id flag_FAKE_MILL("FAKE_MILL") ("FAKE_MILL")
Referenced by item::process_internal().
flag_FAKE_SMOKE
const flag_id flag_FAKE_SMOKE("FAKE_SMOKE") ("FAKE_SMOKE")
Referenced by item::process_internal().
flag_FANCY
const flag_id flag_FANCY("FANCY") ("FANCY")
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description().
flag_FELINE
const flag_id flag_FELINE("FELINE") ("FELINE")
Referenced by Character::can_eat(), and Character::fun_for().
flag_FERTILIZER
const flag_id flag_FERTILIZER("FERTILIZER") ("FERTILIZER")
Referenced by iexamine::choose_fertilizer(), loot(), and Character::will_eat().
flag_FIELD_DRESS
const flag_id flag_FIELD_DRESS("FIELD_DRESS") ("FIELD_DRESS")
Referenced by activity_handlers::butcher_finish(), butcher_submenu(), butcher_time_to_cut(), butchery_drops_harvest(), item::calc_rot(), item::can_revive(), item::corpse_volume(), game::revive_corpse(), set_up_butchery(), and item::weight().
flag_FIELD_DRESS_FAILED
const flag_id flag_FIELD_DRESS_FAILED("FIELD_DRESS_FAILED") ("FIELD_DRESS_FAILED")
Referenced by activity_handlers::butcher_finish(), butcher_submenu(), butcher_time_to_cut(), butchery_drops_harvest(), item::can_revive(), item::corpse_volume(), game::revive_corpse(), set_up_butchery(), and item::weight().
flag_FILTHY
const flag_id flag_FILTHY("FILTHY") ("FILTHY")
Referenced by install_bionic_actor::can_use(), Character::complete_disassemble(), salvage_actor::cut_up(), wash_activity_actor::finish(), reload_activity_actor::finish(), item::is_filthy(), Character::is_installable(), Character::perform_uninstall(), Character::place_corpse(), process_vehicle_items(), iuse::towel_common(), Character::uninstall_bionic(), Character::unload(), unpack_actor::use(), and iuse::wash_items().
flag_FIN
const flag_id flag_FIN("FIN") ("FIN")
Referenced by Character::run_cost_effects(), and Character::swim_speed().
flag_FIRE
const flag_id flag_FIRE("FIRE") ("FIRE")
Referenced by iexamine::fireplace(), Character::has_fire(), and Character::use_fire().
flag_FIRE_100
const flag_id flag_FIRE_100("FIRE_100") ("FIRE_100")
flag_FIRE_20
const flag_id flag_FIRE_20("FIRE_20") ("FIRE_20")
flag_FIRE_50
const flag_id flag_FIRE_50("FIRE_50") ("FIRE_50")
flag_FIRE_TWOHAND
const flag_id flag_FIRE_TWOHAND("FIRE_TWOHAND") ("FIRE_TWOHAND")
Referenced by item::gun_info(), and gunmode_checks_common().
flag_FIRESTARTER
const flag_id flag_FIRESTARTER("FIRESTARTER") ("FIRESTARTER")
Referenced by Character::find_firestarter_with_charges(), and iexamine::fireplace().
flag_FIREWOOD
const flag_id flag_FIREWOOD("FIREWOOD") ("FIREWOOD")
flag_FIT
const flag_id flag_FIT("FIT") ("FIT")
Referenced by anonymous_namespace{item.cpp}::_stacks_clothing_size(), armor_encumb_header_info(), item::armor_fit_info(), repair_item_actor::can_repair_target(), anonymous_namespace{armor_layers.cpp}::clothing_flags_description(), anonymous_namespace{item_tname.cpp}::clothing_size(), Character::complete_disassemble(), create_byproducts_legacy(), recipe::create_result(), Single_item_creator::create_single_without_container(), repair_item_actor::default_action(), item::get_encumber(), recipe_result_info_cache::get_item_header(), get_recipe_result_item(), iuse_transform::info(), item::inherit_flags(), profession::items(), iexamine::nanofab(), repair_item_actor::repair(), repair_item_finish(), outfit::set_fitted(), map::spawn_item(), starting_clothes(), starting_inv(), and unpack_actor::use().
flag_FIX_FARSIGHT
const flag_id flag_FIX_FARSIGHT("FIX_FARSIGHT") ("FIX_FARSIGHT")
Referenced by iuse::ebookread(), iuse::ebooksave(), iuse::einktabletpc(), iuse::electricstorage(), Character::get_miss_reason(), Character::get_recipe_weighted_skill_average(), Character::hit_roll(), iuse::multicooker(), iuse::robotcontrol(), and game::use_computer().
flag_FIX_NEARSIGHT
const flag_id flag_FIX_NEARSIGHT("FIX_NEARSIGHT") ("FIX_NEARSIGHT")
Referenced by Character::recalc_sight_limits(), and Character::sight_impaired().
flag_FLAMING
const flag_id flag_FLAMING("FLAMING") ("FLAMING")
Referenced by Character::melee_special_effects().
flag_FLASH_PROTECTION
const flag_id flag_FLASH_PROTECTION("FLASH_PROTECTION") ("FLASH_PROTECTION")
flag_FLOTATION
const flag_id flag_FLOTATION("FLOTATION") ("FLOTATION")
Referenced by can_move_vertical_at(), anonymous_namespace{armor_layers.cpp}::clothing_flags_description(), Character::swim_speed(), and game::vertical_move().
flag_FOLDED_STOCK
const flag_id flag_FOLDED_STOCK("FOLDED_STOCK") ("FOLDED_STOCK")
Referenced by item::length(), and anonymous_namespace{item_tname.cpp}::tags().
flag_FORAGE_HALLU
const flag_id flag_FORAGE_HALLU("FORAGE_HALLU") ("FORAGE_HALLU")
Referenced by forage_activity_actor::finish().
flag_FORAGE_POISON
const flag_id flag_FORAGE_POISON("FORAGE_POISON") ("FORAGE_POISON")
Referenced by forage_activity_actor::finish().
flag_FRAGILE
const flag_id flag_FRAGILE("FRAGILE") ("FRAGILE")
Referenced by item::damage_armor_durability().
flag_FRAGILE_MELEE
const flag_id flag_FRAGILE_MELEE("FRAGILE_MELEE") ("FRAGILE_MELEE")
Referenced by Character::handle_melee_wear().
flag_FREEZERBURN
const flag_id flag_FREEZERBURN("FREEZERBURN") ("FREEZERBURN")
Referenced by item::apply_freezerburn(), and item::rot_info().
flag_FRESH_GRAIN
const flag_id flag_FRESH_GRAIN("FRESH_GRAIN") ("FRESH_GRAIN")
Referenced by iexamine::stook_empty().
flag_FROM_FROZEN_LIQUID
const flag_id flag_FROM_FROZEN_LIQUID("FROM_FROZEN_LIQUID") ("FROM_FROZEN_LIQUID")
Referenced by item_pocket::is_compatible(), item::leak(), item_pocket::leak(), item::set_temp_flags(), and item::stacks_with().
flag_FROZEN
const flag_id flag_FROZEN("FROZEN") ("FROZEN")
Referenced by veh_interact::calc_overview(), item::calc_rot(), Character::can_consume_as_is(), Character::can_eat(), item::cold_up(), Character::fun_for(), recipe::get_component_filter(), heat_item(), activity_handlers::heat_item_finish(), item::heat_up(), item::io(), item::is_same_temperature(), iuse::multicooker(), item::set_temp_flags(), item::stacks_with(), and anonymous_namespace{item_tname.cpp}::temperature().
flag_FUNGAL_VECTOR
const flag_id flag_FUNGAL_VECTOR("FUNGAL_VECTOR") ("FUNGAL_VECTOR")
Referenced by eat().
flag_GAS_DISCOUNT
const flag_id flag_GAS_DISCOUNT("GAS_DISCOUNT") ("GAS_DISCOUNT")
Referenced by findBestGasDiscount().
flag_GAS_PROOF
const flag_id flag_GAS_PROOF("GAS_PROOF") ("GAS_PROOF")
flag_GIBBED
const flag_id flag_GIBBED("GIBBED") ("GIBBED")
Referenced by butchery_drops_harvest(), item::corpse_volume(), and item::weight().
flag_GNV_EFFECT
const flag_id flag_GNV_EFFECT("GNV_EFFECT") ("GNV_EFFECT")
Referenced by Character::has_nv().
flag_HARD
const flag_id flag_HARD("HARD") ("HARD")
Referenced by item::is_bp_comfortable(), item::is_bp_rigid(), item::is_bp_rigid_selective(), item::is_comfortable(), item::is_rigid(), and item::is_soft().
flag_HEAT_IMMUNE
const flag_id flag_HEAT_IMMUNE("HEAT_IMMUNE") ("HEAT_IMMUNE")
flag_HEMOVORE_FUN
const flag_id flag_HEMOVORE_FUN("HEMOVORE_FUN") ("HEMOVORE_FUN")
Referenced by eat(), Character::fun_for(), Character::modify_morale(), Item_factory::set_allergy_flags(), and Character::will_eat().
flag_HIDDEN_HALLU
const flag_id flag_HIDDEN_HALLU("HIDDEN_HALLU") ("HIDDEN_HALLU")
Referenced by anonymous_namespace{item.cpp}::_stacks_food_traits(), eat(), forage_activity_actor::finish(), item::food_info(), anonymous_namespace{item_tname.cpp}::food_traits(), is_preferred_component(), Character::modify_morale(), and inventory::must_use_hallu_poison().
flag_HIDDEN_POISON
const flag_id flag_HIDDEN_POISON("HIDDEN_POISON") ("HIDDEN_POISON")
Referenced by anonymous_namespace{item.cpp}::_stacks_food_traits(), forage_activity_actor::finish(), item::food_info(), anonymous_namespace{item_tname.cpp}::food_traits(), item::inherit_flags(), is_preferred_component(), inventory::must_use_hallu_poison(), and iuse::poison().
flag_HOOD
const flag_id flag_HOOD("HOOD") ("HOOD")
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description(), suffer::from_sunburn(), outfit::hood_warmth(), and outfit::prepare_bodymap_info().
flag_HOT
const flag_id flag_HOT("HOT") ("HOT")
Referenced by item::cold_up(), heat_item(), item::heat_up(), item::io(), item::is_same_temperature(), Character::modify_morale(), iuse::multicooker(), item::set_temp_flags(), item::stacks_with(), and anonymous_namespace{item_tname.cpp}::temperature().
flag_HURT_WHEN_WIELDED
const flag_id flag_HURT_WHEN_WIELDED("HURT_WHEN_WIELDED") ("HURT_WHEN_WIELDED")
Referenced by Character::melee_special_effects().
flag_HYGROMETER
const flag_id flag_HYGROMETER("HYGROMETER") ("HYGROMETER")
Referenced by iuse::weather_tool().
flag_IN_CBM
const flag_id flag_IN_CBM("IN_CBM") ("IN_CBM")
flag_INEDIBLE
const flag_id flag_INEDIBLE("INEDIBLE") ("INEDIBLE")
Referenced by anonymous_namespace{item.cpp}::_stacks_food_perishable(), Character::can_eat(), basecamp::distribute_food(), and mattack::eat_food().
flag_INITIAL_PART
const flag_id flag_INITIAL_PART("INITIAL_PART") ("INITIAL_PART")
Referenced by finalize_constructions(), and vpart_from_item().
flag_INSPIRATIONAL
const flag_id flag_INSPIRATIONAL("INSPIRATIONAL") ("INSPIRATIONAL")
Referenced by Character::book_fun_for().
flag_INSTALL_DIFFICULT
const flag_id flag_INSTALL_DIFFICULT("INSTALL_DIFFICULT") ("INSTALL_DIFFICULT")
Referenced by Character::gunmod_installation_odds().
flag_INTEGRATED
const flag_id flag_INTEGRATED("INTEGRATED") ("INTEGRATED")
Referenced by outfit::absorb_damage(), Character::add_bionic(), anonymous_namespace{monexamine.cpp}::attach_bag_to(), Character::can_drop(), Character::can_takeoff(), Character::can_wear(), avatar::disarm(), suffer::from_item_dropping(), item::get_sizing(), bionic::initialize_pseudo_items(), outfit::inv_dump(), outfit::is_barefoot(), Character::load(), Item_factory::npc_implied_flags(), outfit::power_armor_conflicts(), rate_action_take_off(), rigid_test(), outfit::sort_armor(), sew_advanced_actor::use(), outfit::wearing_fitting_on(), outfit::wearing_something_on(), and anonymous_namespace{inventory_ui.cpp}::wielded_worn_category().
flag_IR_EFFECT
const flag_id flag_IR_EFFECT("IR_EFFECT") ("IR_EFFECT")
Referenced by Character::recalc_sight_limits().
flag_IRRADIATED
const flag_id flag_IRRADIATED("IRRADIATED") ("IRRADIATED")
Referenced by anonymous_namespace{item.cpp}::_stacks_food_irradiated(), computer_session::action_irradiator(), item::calc_rot(), and anonymous_namespace{item_tname.cpp}::food_irradiated().
flag_IRREMOVABLE
const flag_id flag_IRREMOVABLE("IRREMOVABLE") ("IRREMOVABLE")
Referenced by item::ammo_set(), item_pocket::is_compatible(), item::is_irremovable(), is_physical(), item::item(), and activity_handlers::toolmod_add_finish().
flag_IS_ARMOR
const flag_id flag_IS_ARMOR("IS_ARMOR") ("IS_ARMOR")
Referenced by item::armor_full_protection_info(), and item::is_armor().
flag_IS_PET_ARMOR
const flag_id flag_IS_PET_ARMOR("IS_PET_ARMOR") ("IS_PET_ARMOR")
Referenced by item::is_pet_armor().
flag_IS_UPS
const flag_id flag_IS_UPS("IS_UPS") ("IS_UPS")
Referenced by Character::available_ups(), charges_of_internal(), map::consume_ups(), Character::consume_ups(), Character::get_cable_ups(), item::process_internal(), item::process_link(), iuse::toolmod_attach(), link_up_actor::use(), and anonymous_namespace{item_tname.cpp}::vars().
flag_ITEM_BROKEN
const flag_id flag_ITEM_BROKEN("ITEM_BROKEN") ("ITEM_BROKEN")
Referenced by item::is_broken(), and item::is_broken_on_active().
flag_LASER_SIGHT
const flag_id flag_LASER_SIGHT("LASER_SIGHT") ("LASER_SIGHT")
Referenced by Character::fastest_aiming_method_speed().
flag_LEAK_ALWAYS
const flag_id flag_LEAK_ALWAYS("LEAK_ALWAYS") ("LEAK_ALWAYS")
Referenced by Character::calculate_leak_level(), and item::final_info().
flag_LEAK_DAM
const flag_id flag_LEAK_DAM("LEAK_DAM") ("LEAK_DAM")
Referenced by Character::calculate_leak_level(), item::color_in_inventory(), and item::final_info().
flag_LITCIG
const flag_id flag_LITCIG("LITCIG") ("LITCIG")
Referenced by iuse::can_smoke(), item::color_in_inventory(), item::process_extinguish(), item::process_internal(), sleep(), and anonymous_namespace{item_tname.cpp}::tags().
flag_LUPINE
const flag_id flag_LUPINE("LUPINE") ("LUPINE")
Referenced by Character::can_eat(), and Character::fun_for().
flag_MAG_BELT
const flag_id flag_MAG_BELT("MAG_BELT") ("MAG_BELT")
Referenced by item::is_ammo_belt().
flag_MAG_BULKY
const flag_id flag_MAG_BULKY("MAG_BULKY") ("MAG_BULKY")
Referenced by Character::item_reload_cost().
flag_MAG_DESTROY
const flag_id flag_MAG_DESTROY("MAG_DESTROY") ("MAG_DESTROY")
Referenced by activity_on_turn_move_loot(), unload_loot_activity_actor::do_turn(), unload_activity_actor::unload(), and Character::unload().
flag_MAG_EJECT
const flag_id flag_MAG_EJECT("MAG_EJECT") ("MAG_EJECT")
flag_MAGIC_FOCUS
const flag_id flag_MAGIC_FOCUS("MAGIC_FOCUS") ("MAGIC_FOCUS")
Referenced by npc_attack_spell::base_time_penalty(), item::basic_info(), Character::cast_spell(), and npc_attack_spell::use().
flag_MAGICAL
const flag_id flag_MAGICAL("MAGICAL") ("MAGICAL")
Referenced by iuse::robotcontrol().
flag_MC_HAS_DATA
const flag_id flag_MC_HAS_DATA("MC_HAS_DATA") ("MC_HAS_DATA")
Referenced by iuse::camera(), and iuse::einktabletpc().
flag_MC_MOBILE
const flag_id flag_MC_MOBILE("MC_MOBILE") ("MC_MOBILE")
Referenced by iuse::camera().
flag_MECH_BAT
const flag_id flag_MECH_BAT("MECH_BAT") ("MECH_BAT")
flag_MELTS
const flag_id flag_MELTS("MELTS") ("MELTS")
Referenced by Character::can_consume_as_is(), Character::can_eat(), Character::fun_for(), item::is_same_temperature(), and anonymous_namespace{item_tname.cpp}::temperature().
flag_MESSY
const flag_id flag_MESSY("MESSY") ("MESSY")
Referenced by activity_handlers::pulp_do_turn().
flag_MISSION_ITEM
const flag_id flag_MISSION_ITEM("MISSION_ITEM") ("MISSION_ITEM")
flag_MOUNTED_GUN
const flag_id flag_MOUNTED_GUN("MOUNTED_GUN") ("MOUNTED_GUN")
Referenced by gunmode_checks_weapon().
flag_MOUSE
const flag_id flag_MOUSE("MOUSE") ("MOUSE")
Referenced by Character::can_eat().
flag_MUNDANE
const flag_id flag_MUNDANE("MUNDANE") ("MUNDANE")
Referenced by item::color_in_inventory().
flag_MUSHY
const flag_id flag_MUSHY("MUSHY") ("MUSHY")
Referenced by anonymous_namespace{item.cpp}::_stacks_mushy_dirty(), item::apply_freezerburn(), item::calc_rot(), comestible_inventory_preset::comestible_inventory_preset(), eat(), anonymous_namespace{item_tname.cpp}::food_status(), item::get_comestible_fun(), and item::rot_info().
flag_MUTE
const flag_id flag_MUTE("MUTE") ("MUTE")
Referenced by Character::is_mute().
flag_MYCUS_OK
const flag_id flag_MYCUS_OK("MYCUS_OK") ("MYCUS_OK")
Referenced by Character::can_eat().
flag_NANOFAB_REPAIR
const flag_id flag_NANOFAB_REPAIR("NANOFAB_REPAIR") ("NANOFAB_REPAIR")
Referenced by iexamine::nanofab().
flag_NANOFAB_TEMPLATE
const flag_id flag_NANOFAB_TEMPLATE("NANOFAB_TEMPLATE") ("NANOFAB_TEMPLATE")
Referenced by item::item().
flag_NANOFAB_TEMPLATE_SINGLE_USE
const flag_id flag_NANOFAB_TEMPLATE_SINGLE_USE("NANOFAB_TEMPLATE_SINGLE_USE") ("NANOFAB_TEMPLATE_SINGLE_USE")
Referenced by iexamine::nanofab(), and anonymous_namespace{item_tname.cpp}::vars().
flag_NATURAL_WEAPON
const flag_id flag_NATURAL_WEAPON("NATURAL_WEAPON") ("NATURAL_WEAPON")
flag_NEEDS_NO_LUBE
const flag_id flag_NEEDS_NO_LUBE("NEEDS_NO_LUBE") ("NEEDS_NO_LUBE")
Referenced by Item_modifier::modify().
flag_NEEDS_UNFOLD
const flag_id flag_NEEDS_UNFOLD("NEEDS_UNFOLD") ("NEEDS_UNFOLD")
Referenced by item::on_wield_cost().
flag_NEGATIVE_MONOTONY_OK
const flag_id flag_NEGATIVE_MONOTONY_OK("NEGATIVE_MONOTONY_OK") ("NEGATIVE_MONOTONY_OK")
Referenced by Character::fun_for().
flag_NEVER_JAMS
const flag_id flag_NEVER_JAMS("NEVER_JAMS") ("NEVER_JAMS")
Referenced by Character::handle_gun_damage(), and item::is_gunmod_compatible().
flag_NO_CLEAN
const flag_id flag_NO_CLEAN("NO_CLEAN") ("NO_CLEAN")
Referenced by iuse::wash_items().
flag_NO_CVD
const flag_id flag_NO_CVD("NO_CVD") ("NO_CVD")
Referenced by iexamine::cvdmachine().
flag_NO_DROP
const flag_id flag_NO_DROP("NO_DROP") ("NO_DROP")
Referenced by map::_add_item_or_charges(), item::ammo_set(), damage_item(), reel_cable_activity_actor::finish(), vehicle::invalidate_towing(), item_pocket::is_compatible(), is_physical(), vehicle::part_to_item(), item::process_link(), item::reset_link(), craft_command::safe_to_unload_comp(), vehicle::unlink_cables(), item::weight(), and within_autopickup_limits().
flag_NO_INGEST
const flag_id flag_NO_INGEST("NO_INGEST") ("NO_INGEST")
Referenced by consume_med(), and Character::modify_morale().
flag_NO_PACKED
const flag_id flag_NO_PACKED("NO_PACKED") ("NO_PACKED")
Referenced by anonymous_namespace{item.cpp}::_stacks_cbm_status(), iexamine::autoclave_full(), Character::bionics_install_failure(), anonymous_namespace{item_tname.cpp}::cbm_status(), iuse::pack_cbm(), Character::perform_uninstall(), Character::place_corpse(), process_vehicle_items(), and Character::uninstall_bionic().
flag_NO_PARASITES
const flag_id flag_NO_PARASITES("NO_PARASITES") ("NO_PARASITES")
Referenced by item::combine(), eat(), rate_food(), item::rot_info(), item::set_temp_flags(), item::stacks_with(), and Character::will_eat().
flag_NO_RELOAD
const flag_id flag_NO_RELOAD("NO_RELOAD") ("NO_RELOAD")
Referenced by item::can_reload_with(), Character::has_magazine_for_ammo(), item::is_reloadable(), item::magazine_info(), and item::tool_info().
flag_NO_REPAIR
const flag_id flag_NO_REPAIR("NO_REPAIR") ("NO_REPAIR")
Referenced by repair_item_actor::can_repair_target(), Item_factory::finalize_pre(), iuse::gun_repair(), and item::repaired_with().
flag_NO_SALVAGE
const flag_id flag_NO_SALVAGE("NO_SALVAGE") ("NO_SALVAGE")
Referenced by item::is_salvageable().
flag_NO_STERILE
const flag_id flag_NO_STERILE("NO_STERILE") ("NO_STERILE")
Referenced by anonymous_namespace{item.cpp}::_stacks_cbm_status(), iexamine::autoclave_full(), item::bionic_info(), Character::bionics_install_failure(), install_bionic_actor::can_use(), anonymous_namespace{item_tname.cpp}::cbm_status(), item::color_in_inventory(), Character::is_installable(), Character::perform_uninstall(), Character::place_corpse(), process_vehicle_items(), and Character::uninstall_bionic().
flag_NO_TAKEOFF
const flag_id flag_NO_TAKEOFF("NO_TAKEOFF") ("NO_TAKEOFF")
Referenced by Character::can_takeoff(), suffer::from_item_dropping(), and rate_action_take_off().
flag_NO_TURRET
const flag_id flag_NO_TURRET("NO_TURRET") ("NO_TURRET")
Referenced by mountable_gun_filter().
flag_NO_UNLOAD
const flag_id flag_NO_UNLOAD("NO_UNLOAD") ("NO_UNLOAD")
Referenced by item::ammo_set(), item::can_unload_liquid(), outfit::get_AIM_inventory(), Character::rate_action_unload(), remove_ammo(), Character::unload(), and valid_unload_container().
flag_NO_UNWIELD
const flag_id flag_NO_UNWIELD("NO_UNWIELD") ("NO_UNWIELD")
Referenced by Character::activate_bionic(), mattack::bio_op_disarm(), Character::can_drop(), Character::can_unwield(), Character::can_wield(), npc::check_or_use_weapon_cbm(), iuse::ehandcuffs_tick(), npc::evaluate_best_attack(), conditional_fun::anonymous_namespace{condition.cpp}::f_can_drop_weapon(), suffer::from_item_dropping(), Character::handle_melee_wear(), game::inventory_item_menu(), item_pocket::is_compatible(), is_physical(), Character::load(), mountable_gun_filter(), avatar_action::plthrow(), Character::process_bionic(), mattack::pull_metal_weapon(), mattack::riotbot(), bionic::uninstall_weapon(), Character::unwield(), bionic::update_weapon_flags(), and holster_actor::use().
flag_NO_WEAR_EFFECT
const flag_id flag_NO_WEAR_EFFECT("NO_WEAR_EFFECT") ("NO_WEAR_EFFECT")
Referenced by item::is_bp_comfortable(), and item::is_comfortable().
flag_NON_FOULING
const flag_id flag_NON_FOULING("NON_FOULING") ("NON_FOULING")
Referenced by Character::handle_gun_damage(), and Item_modifier::modify().
flag_NONCONDUCTIVE
const flag_id flag_NONCONDUCTIVE("NONCONDUCTIVE") ("NONCONDUCTIVE")
Referenced by item::conductive().
flag_NORMAL
const flag_id flag_NORMAL("NORMAL") ("NORMAL")
Referenced by Item_factory::finalize_post_armor().
flag_NPC_ACTIVATE
const flag_id flag_NPC_ACTIVATE("NPC_ACTIVATE") ("NPC_ACTIVATE")
Referenced by npc::alt_attack(), npc_attack_throw::can_use(), npc_attack_activate_item::can_use(), and Item_factory::npc_implied_flags().
flag_NPC_ALT_ATTACK
const flag_id flag_NPC_ALT_ATTACK("NPC_ALT_ATTACK") ("NPC_ALT_ATTACK")
Referenced by npc::alt_attack(), and Item_factory::npc_implied_flags().
flag_NPC_SAFE
const flag_id flag_NPC_SAFE("NPC_SAFE") ("NPC_SAFE")
Referenced by npc::will_accept_from_player().
flag_NPC_THROW_NOW
const flag_id flag_NPC_THROW_NOW("NPC_THROW_NOW") ("NPC_THROW_NOW")
Referenced by npc::alt_attack(), npc_attack_throw::can_use(), npc_attack_throw::evaluate(), and Item_factory::npc_implied_flags().
flag_NPC_THROWN
const flag_id flag_NPC_THROWN("NPC_THROWN") ("NPC_THROWN")
Referenced by npc_attack_throw::can_use(), npc_attack_throw::evaluate_tripoint(), and Item_factory::npc_implied_flags().
flag_NULL
const flag_id flag_NULL = json_flag_null
Definition at line 378 of file flag.cpp.
flag_NUTRIENT_OVERRIDE
const flag_id flag_NUTRIENT_OVERRIDE("NUTRIENT_OVERRIDE") ("NUTRIENT_OVERRIDE")
Referenced by Character::compute_effective_nutrients(), Character::compute_nutrient_range(), recipe::create_results(), smoker_finalize(), and iexamine::stook_full().
flag_OLD_CURRENCY
const flag_id flag_OLD_CURRENCY("OLD_CURRENCY") ("OLD_CURRENCY")
Referenced by anonymous_namespace{iexamine.cpp}::atm_menu::do_exchange_cash(), and anonymous_namespace{iexamine.cpp}::atm_menu::reset().
flag_ONLY_ONE
const flag_id flag_ONLY_ONE("ONLY_ONE") ("ONLY_ONE")
Referenced by test_only_one_conflicts().
flag_ORGANIC
const flag_id flag_ORGANIC("ORGANIC") ("ORGANIC")
flag_OUTER
const flag_id flag_OUTER("OUTER") ("OUTER")
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_layer(), and Item_factory::finalize_post_armor().
flag_OVERSIZE
const flag_id flag_OVERSIZE("OVERSIZE") ("OVERSIZE")
Referenced by iuse_transform::can_use(), Character::can_wear(), anonymous_namespace{armor_layers.cpp}::clothing_flags_description(), repair_item_actor::default_action(), item::get_sizing(), and outfit::wearing_fitting_on().
flag_PADDED
const flag_id flag_PADDED("PADDED") ("PADDED")
Referenced by item::is_bp_comfortable(), and item::is_comfortable().
flag_PAIN_IMMUNE
const flag_id flag_PAIN_IMMUNE("PAIN_IMMUNE") ("PAIN_IMMUNE")
flag_PALS_LARGE
const flag_id flag_PALS_LARGE("PALS_LARGE") ("PALS_LARGE")
Referenced by item::can_attach_as_pocket().
flag_PALS_MEDIUM
const flag_id flag_PALS_MEDIUM("PALS_MEDIUM") ("PALS_MEDIUM")
Referenced by item::can_attach_as_pocket(), and item::get_pocket_size().
flag_PALS_SMALL
const flag_id flag_PALS_SMALL("PALS_SMALL") ("PALS_SMALL")
Referenced by item::can_attach_as_pocket(), and item::get_pocket_size().
flag_PARTIAL_DEAF
const flag_id flag_PARTIAL_DEAF("PARTIAL_DEAF") ("PARTIAL_DEAF")
Referenced by Character::is_immune_effect().
flag_PERFECT_LOCKPICK
const flag_id flag_PERFECT_LOCKPICK("PERFECT_LOCKPICK") ("PERFECT_LOCKPICK")
Referenced by lockpick_activity_actor::finish(), and iuse::pick_lock().
flag_PERPETUAL
const flag_id flag_PERPETUAL("PERPETUAL") ("PERPETUAL")
Referenced by vehicle::consumption_per_hour(), vehicle::fuel_left(), and vehicle::is_perpetual_type().
flag_PERSONAL
const flag_id flag_PERSONAL("PERSONAL") ("PERSONAL")
Referenced by Character::active_light(), check_natural_attack_restricted_on_worn(), anonymous_namespace{armor_layers.cpp}::clothing_layer(), Item_factory::finalize_post_armor(), is_physical(), outfit::is_wearing_shoes(), and layer_item().
flag_PLACE_RANDOMLY
const flag_id flag_PLACE_RANDOMLY("PLACE_RANDOMLY") ("PLACE_RANDOMLY")
Referenced by iuse::capture_monster_act().
flag_POCKETS
const flag_id flag_POCKETS("POCKETS") ("POCKETS")
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description(), suffer::from_sunburn(), outfit::pocket_warmth(), and outfit::prepare_bodymap_info().
flag_POLEARM
const flag_id flag_POLEARM("POLEARM") ("POLEARM")
Referenced by Character::melee_attack_abstract(), and Character::melee_value().
flag_POWERARMOR_COMPATIBLE
const flag_id flag_POWERARMOR_COMPATIBLE("POWERARMOR_COMPATIBLE") ("POWERARMOR_COMPATIBLE")
Referenced by outfit::power_armor_conflicts().
flag_POWERED
const flag_id flag_POWERED("POWERED") ("POWERED")
Referenced by chop_moves().
flag_PREDATOR_FUN
const flag_id flag_PREDATOR_FUN("PREDATOR_FUN") ("PREDATOR_FUN")
Referenced by Character::modify_morale().
flag_PRIMITIVE_RANGED_WEAPON
const flag_id flag_PRIMITIVE_RANGED_WEAPON("PRIMITIVE_RANGED_WEAPON") ("PRIMITIVE_RANGED_WEAPON")
Referenced by npc::get_opinion_values(), Character::handle_gun_damage(), item::is_firearm(), and Item_modifier::modify().
flag_PROCESSING
const flag_id flag_PROCESSING("PROCESSING") ("PROCESSING")
Referenced by item::calc_rot_while_processing(), item::goes_bad(), mill_activate(), smoker_activate(), and smoker_finalize().
flag_PROCESSING_RESULT
const flag_id flag_PROCESSING_RESULT("PROCESSING_RESULT") ("PROCESSING_RESULT")
Referenced by item::set_relative_rot(), and smoker_finalize().
flag_PSEUDO
const flag_id flag_PSEUDO("PSEUDO") ("PSEUDO")
Referenced by item::allow_crafting_component(), are_requirements_nearby(), item::display_name(), bionic::initialize_pseudo_items(), is_physical(), mountable_gun_filter(), Item_factory::npc_implied_flags(), inventory::provide_pseudo_item(), and basecamp::scan_pseudo_items().
flag_PSEUDOPOD_GRASP
const flag_id flag_PSEUDOPOD_GRASP("PSEUDOPOD_GRASP") ("PSEUDOPOD_GRASP")
flag_PSYSHIELD_PARTIAL
const flag_id flag_PSYSHIELD_PARTIAL("PSYSHIELD_PARTIAL") ("PSYSHIELD_PARTIAL")
flag_PULPED
const flag_id flag_PULPED("PULPED") ("PULPED")
Referenced by item::can_revive(), mattack::eat_carrion(), and activity_handlers::pulp_do_turn().
flag_PUMP_ACTION
const flag_id flag_PUMP_ACTION("PUMP_ACTION") ("PUMP_ACTION")
Referenced by item::is_gunmod_compatible().
flag_PUMP_RAIL_COMPATIBLE
const flag_id flag_PUMP_RAIL_COMPATIBLE("PUMP_RAIL_COMPATIBLE") ("PUMP_RAIL_COMPATIBLE")
Referenced by item::is_gunmod_compatible().
flag_QUARTERED
const flag_id flag_QUARTERED("QUARTERED") ("QUARTERED")
Referenced by butcher_submenu(), butcher_time_to_cut(), butchery_drops_harvest(), butchery_quarter(), item::can_revive(), item::corpse_volume(), game::revive_corpse(), set_up_butchery(), and item::weight().
flag_RABBIT
const flag_id flag_RABBIT("RABBIT") ("RABBIT")
Referenced by Character::can_eat().
flag_RAD_PROOF
const flag_id flag_RAD_PROOF("RAD_PROOF") ("RAD_PROOF")
Referenced by Character::is_rad_immune().
flag_RAD_RESIST
const flag_id flag_RAD_RESIST("RAD_RESIST") ("RAD_RESIST")
Referenced by suffer::from_radiation(), and Character::irradiate().
flag_RADIO_ACTIVATION
const flag_id flag_RADIO_ACTIVATION("RADIO_ACTIVATION") ("RADIO_ACTIVATION")
Referenced by iuse_transform::do_transform(), map::get_rc_items(), item::processing_speed(), item::properties_info(), iuse::radio_mod(), remove_radio_mod(), and sendRadioSignal().
flag_RADIO_CONTAINER
const flag_id flag_RADIO_CONTAINER("RADIO_CONTAINER") ("RADIO_CONTAINER")
Referenced by map::get_rc_items(), and iuse::radiocontrol().
flag_RADIO_INVOKE_PROC
const flag_id flag_RADIO_INVOKE_PROC("RADIO_INVOKE_PROC") ("RADIO_INVOKE_PROC")
Referenced by item::properties_info(), and sendRadioSignal().
flag_RADIO_MOD
const flag_id flag_RADIO_MOD("RADIO_MOD") ("RADIO_MOD")
Referenced by item::properties_info(), iuse::radio_mod(), remove_radio_mod(), and anonymous_namespace{item_tname.cpp}::tags().
flag_RADIO_MODABLE
const flag_id flag_RADIO_MODABLE("RADIO_MODABLE") ("RADIO_MODABLE")
Referenced by iuse::radio_mod().
flag_RADIOACTIVE
const flag_id flag_RADIOACTIVE("RADIOACTIVE") ("RADIOACTIVE")
Referenced by Character::calculate_leak_level(), item::color_in_inventory(), and item::final_info().
flag_RADIOCAR
const flag_id flag_RADIOCAR("RADIOCAR") ("RADIOCAR")
Referenced by iuse::radiocontrol(), and rcdrive().
flag_RADIOCARITEM
const flag_id flag_RADIOCARITEM("RADIOCARITEM") ("RADIOCARITEM")
Referenced by iuse::radio_mod(), iuse::radiocar(), and remove_radio_mod().
flag_RADIOSIGNAL_1
const flag_id flag_RADIOSIGNAL_1("RADIOSIGNAL_1") ("RADIOSIGNAL_1")
Referenced by item::properties_info(), iuse::radio_mod(), remove_radio_mod(), and anonymous_namespace{item_tname.cpp}::tags().
flag_RADIOSIGNAL_2
const flag_id flag_RADIOSIGNAL_2("RADIOSIGNAL_2") ("RADIOSIGNAL_2")
Referenced by item::properties_info(), iuse::radio_mod(), remove_radio_mod(), and anonymous_namespace{item_tname.cpp}::tags().
flag_RADIOSIGNAL_3
const flag_id flag_RADIOSIGNAL_3("RADIOSIGNAL_3") ("RADIOSIGNAL_3")
Referenced by item::properties_info(), iuse::radio_mod(), remove_radio_mod(), and anonymous_namespace{item_tname.cpp}::tags().
flag_RAIN_PROTECT
const flag_id flag_RAIN_PROTECT("RAIN_PROTECT") ("RAIN_PROTECT")
Referenced by suffer::from_sunburn(), and item::process_extinguish().
flag_RAINPROOF
const flag_id flag_RAINPROOF("RAINPROOF") ("RAINPROOF")
flag_RAT
const flag_id flag_RAT("RAT") ("RAT")
Referenced by Character::can_eat().
flag_RAW
const flag_id flag_RAW("RAW") ("RAW")
Referenced by recipe::removes_raw(), and Character::select_item_component().
flag_REACH
const flag_id flag_REACH("REACH") ("REACH")
flag_REACH3
const flag_id flag_REACH3("REACH3") ("REACH3")
Referenced by item::current_reach_range(), item::melee_combat_info(), and item::reach_range().
flag_REACH_ATTACK
const flag_id flag_REACH_ATTACK("REACH_ATTACK") ("REACH_ATTACK")
Referenced by item::current_reach_range(), Item_factory::finalize_pre(), item::gunmod_info(), handle_action_menu(), item::melee_combat_info(), and item::reach_range().
flag_REBREATHER
const flag_id flag_REBREATHER("REBREATHER") ("REBREATHER")
Referenced by suffer::while_underwater().
flag_RECHARGE
const flag_id flag_RECHARGE("RECHARGE") ("RECHARGE")
Referenced by item::charge_linked_batteries(), iuse::hand_crank(), process_vehicle_items(), item::tool_info(), and Character::unload().
flag_REDUCED_BASHING
const flag_id flag_REDUCED_BASHING("REDUCED_BASHING") ("REDUCED_BASHING")
Referenced by item::damage_melee().
flag_REDUCED_WEIGHT
const flag_id flag_REDUCED_WEIGHT("REDUCED_WEIGHT") ("REDUCED_WEIGHT")
Referenced by item::weight().
flag_RELOAD_AND_SHOOT
const flag_id flag_RELOAD_AND_SHOOT("RELOAD_AND_SHOOT") ("RELOAD_AND_SHOOT")
Referenced by Item_factory::check_definitions(), item::display_name(), game::do_regular_action(), aim_activity_actor::do_turn(), aim_activity_actor::finish(), Character::fire_gun(), gunmode_checks_weapon(), mountable_gun_filter(), game::reload(), game_menus::inv::select_ammo(), and aim_activity_actor::unload_RAS_weapon().
flag_RELOAD_EJECT
const flag_id flag_RELOAD_EJECT("RELOAD_EJECT") ("RELOAD_EJECT")
Referenced by cycle_action(), item::is_gunmod_compatible(), and Character::perform_technique().
flag_RELOAD_ONE
const flag_id flag_RELOAD_ONE("RELOAD_ONE") ("RELOAD_ONE")
Referenced by game::do_regular_action(), Item_factory::finalize_pre(), reload_activity_actor::finish(), item::gun_info(), and item::reload_option::qty().
flag_REMOVED_STOCK
const flag_id flag_REMOVED_STOCK("REMOVED_STOCK") ("REMOVED_STOCK")
Referenced by anonymous_namespace{item.cpp}::_stacks_weapon_mods(), item::collapsed_volume_delta(), item::length(), and anonymous_namespace{item_tname.cpp}::weapon_mods().
flag_REQUIRES_BALANCE
const flag_id flag_REQUIRES_BALANCE("REQUIRES_BALANCE") ("REQUIRES_BALANCE")
Referenced by Character::on_hit().
flag_REQUIRES_TINDER
const flag_id flag_REQUIRES_TINDER("REQUIRES_TINDER") ("REQUIRES_TINDER")
Referenced by activity_handlers::start_fire_do_turn().
flag_RESTRICT_HANDS
const flag_id flag_RESTRICT_HANDS("RESTRICT_HANDS") ("RESTRICT_HANDS")
Referenced by Character::can_wear(), Character::can_wield(), gunmode_checks_common(), and hardcoded_mutation_attack().
flag_REVIVE_SPECIAL
const flag_id flag_REVIVE_SPECIAL("REVIVE_SPECIAL") ("REVIVE_SPECIAL")
Referenced by map::add_corpse(), item::make_corpse(), and item::ready_to_revive().
flag_ROLLER_INLINE
const flag_id flag_ROLLER_INLINE("ROLLER_INLINE") ("ROLLER_INLINE")
Referenced by Character::get_dodge(), and Character::run_cost_effects().
flag_ROLLER_ONE
const flag_id flag_ROLLER_ONE("ROLLER_ONE") ("ROLLER_ONE")
Referenced by Character::get_dodge(), Character::on_hit(), and Character::run_cost_effects().
flag_ROLLER_QUAD
const flag_id flag_ROLLER_QUAD("ROLLER_QUAD") ("ROLLER_QUAD")
Referenced by Character::get_dodge(), and Character::run_cost_effects().
flag_SAFECRACK
const flag_id flag_SAFECRACK("SAFECRACK") ("SAFECRACK")
Referenced by safecracking_activity_actor::do_turn(), and iexamine::safe().
flag_SEED_HARVEST
const flag_id flag_SEED_HARVEST("SEED_HARVEST") ("SEED_HARVEST")
flag_SEMITANGIBLE
const flag_id flag_SEMITANGIBLE("SEMITANGIBLE") ("SEMITANGIBLE")
Referenced by Character::active_light(), iuse_transform::can_use(), Character::can_wear(), check_natural_attack_restricted_on_worn(), anonymous_namespace{armor_layers.cpp}::clothing_flags_description(), outfit::is_wearing_shoes(), and layer_item().
flag_SHREDDED
const flag_id flag_SHREDDED("SHREDDED") ("SHREDDED")
Referenced by Character::can_wield(), item::cold_up(), pickup_inventory_preset::get_denial(), item::heat_up(), game_menus::inv::multidrop(), and item::set_temp_flags().
flag_SHRUB
const flag_id flag_SHRUB("SHRUB") ("SHRUB")
flag_SINGLE_USE
const flag_id flag_SINGLE_USE("SINGLE_USE") ("SINGLE_USE")
Referenced by firstaid_activity_actor::finish(), and Character::invoke_item().
flag_SKINNED
const flag_id flag_SKINNED("SKINNED") ("SKINNED")
Referenced by activity_handlers::butcher_finish(), butcher_submenu(), butchery_drops_harvest(), item::can_revive(), item::corpse_volume(), set_up_butchery(), and item::weight().
flag_SKINTIGHT
const flag_id flag_SKINTIGHT("SKINTIGHT") ("SKINTIGHT")
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_layer(), Item_factory::finalize_post_armor(), and outfit::is_wearing_shoes().
flag_SLEEP_AID
const flag_id flag_SLEEP_AID("SLEEP_AID") ("SLEEP_AID")
Referenced by Character::base_comfort_value().
flag_SLEEP_AID_CONTAINER
const flag_id flag_SLEEP_AID_CONTAINER("SLEEP_AID_CONTAINER") ("SLEEP_AID_CONTAINER")
Referenced by Character::base_comfort_value().
flag_SLEEP_IGNORE
const flag_id flag_SLEEP_IGNORE("SLEEP_IGNORE") ("SLEEP_IGNORE")
Referenced by sleep().
flag_SLOW_WIELD
const flag_id flag_SLOW_WIELD("SLOW_WIELD") ("SLOW_WIELD")
Referenced by item::on_wield_cost().
flag_SMOKABLE
const flag_id flag_SMOKABLE("SMOKABLE") ("SMOKABLE")
Referenced by smokable_selector_preset::is_shown(), smoker_activate(), smoker_finalize(), and iexamine::stook_full().
flag_SMOKED
const flag_id flag_SMOKED("SMOKED") ("SMOKED")
Referenced by smoker_activate().
flag_SOFT
const flag_id flag_SOFT("SOFT") ("SOFT")
Referenced by item::is_bp_comfortable(), item::is_bp_rigid(), item::is_bp_rigid_selective(), item::is_comfortable(), item::is_rigid(), and item::is_soft().
flag_SOLARPACK
const flag_id flag_SOLARPACK("SOLARPACK") ("SOLARPACK")
Referenced by item::process_internal(), and link_up_actor::use().
flag_SOLARPACK_ON
const flag_id flag_SOLARPACK_ON("SOLARPACK_ON") ("SOLARPACK_ON")
Referenced by Character::get_cable_solar(), item::process_internal(), item::process_link(), iuse::solarpack(), and link_up_actor::use().
flag_SPAWN_ACTIVE
const flag_id flag_SPAWN_ACTIVE("SPAWN_ACTIVE") ("SPAWN_ACTIVE")
Referenced by item::item().
flag_SPEAR
const flag_id flag_SPEAR("SPEAR") ("SPEAR")
Referenced by Character::get_targetable_creatures(), and Character::reach_attack().
flag_SPEEDLOADER
const flag_id flag_SPEEDLOADER("SPEEDLOADER") ("SPEEDLOADER")
Referenced by item_pocket::can_reload_with(), Item_factory::check_definitions(), find_ammo_helper(), reload_activity_actor::finish(), select_ammo_inventory_preset::is_shown(), Character::list_ammo(), item::reload_option::qty(), item::reload(), and ammo_inventory_selector::set_all_entries_chosen_count().
flag_SPEEDLOADER_CLIP
const flag_id flag_SPEEDLOADER_CLIP("SPEEDLOADER_CLIP") ("SPEEDLOADER_CLIP")
Referenced by item_pocket::can_reload_with(), reload_activity_actor::finish(), Character::list_ammo(), item::reload_option::qty(), item::reload(), and ammo_inventory_selector::set_all_entries_chosen_count().
flag_SPLINT
const flag_id flag_SPLINT("SPLINT") ("SPLINT")
Referenced by outfit::adjust_worn(), iexamine::autodoc(), Character::body_window(), Character::can_wear(), draw_health_summary(), Character::mend(), item::on_wear(), rigid_test(), Character::use(), and npc::wear_if_wanted().
flag_STAB
const flag_id flag_STAB("STAB") ("STAB")
Referenced by Item_factory::finalize_pre().
flag_STAB_IMMUNE
const flag_id flag_STAB_IMMUNE("STAB_IMMUNE") ("STAB_IMMUNE")
flag_STR_DRAW
const flag_id flag_STR_DRAW("STR_DRAW") ("STR_DRAW")
Referenced by item::gun_range(), and mountable_gun_filter().
flag_STR_RELOAD
const flag_id flag_STR_RELOAD("STR_RELOAD") ("STR_RELOAD")
Referenced by Character::item_reload_cost().
flag_STRICT_HUMANITARIANISM
const flag_id flag_STRICT_HUMANITARIANISM("STRICT_HUMANITARIANISM") ("STRICT_HUMANITARIANISM")
Referenced by Character::modify_morale(), and Character::will_eat().
flag_STURDY
const flag_id flag_STURDY("STURDY") ("STURDY")
Referenced by item::damage_armor_durability().
flag_SUN_GLASSES
const flag_id flag_SUN_GLASSES("SUN_GLASSES") ("SUN_GLASSES")
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description(), and suffer::from_sunburn().
flag_SUPER_FANCY
const flag_id flag_SUPER_FANCY("SUPER_FANCY") ("SUPER_FANCY")
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description().
flag_SWIM_GOGGLES
const flag_id flag_SWIM_GOGGLES("SWIM_GOGGLES") ("SWIM_GOGGLES")
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description(), Character::recalc_sight_limits(), and Character::sight_impaired().
flag_TACK
const flag_id flag_TACK("TACK") ("TACK")
flag_TANGLE
const flag_id flag_TANGLE("TANGLE") ("TANGLE")
Referenced by Character::throw_item().
flag_TARDIS
const flag_id flag_TARDIS("TARDIS") ("TARDIS")
Referenced by Item_factory::check_definitions().
flag_THERMOMETER
const flag_id flag_THERMOMETER("THERMOMETER") ("THERMOMETER")
Referenced by iuse::weather_tool().
flag_TIE_UP
const flag_id flag_TIE_UP("TIE_UP") ("TIE_UP")
flag_TINDER
const flag_id flag_TINDER("TINDER") ("TINDER")
Referenced by activity_handlers::start_fire_do_turn(), and map::tinder_at().
flag_TOBACCO
const flag_id flag_TOBACCO("TOBACCO") ("TOBACCO")
Referenced by item::process_litcig().
flag_TOUGH_FEET
const flag_id flag_TOUGH_FEET("TOUGH_FEET") ("TOUGH_FEET")
Referenced by Character::run_cost_effects().
flag_TOURNIQUET
const flag_id flag_TOURNIQUET("TOURNIQUET") ("TOURNIQUET")
Referenced by Character::can_wear(), heal_actor::finish_using(), suffer::from_tourniquet(), Character::most_staunchable_bp(), and item::on_wear().
flag_TOW_CABLE
const flag_id flag_TOW_CABLE("TOW_CABLE") ("TOW_CABLE")
Referenced by vehicle::part_to_item().
flag_TRADER_AVOID
const flag_id flag_TRADER_AVOID("TRADER_AVOID") ("TRADER_AVOID")
Referenced by Item_factory::npc_implied_flags(), and npc::wants_to_buy().
flag_TRADER_KEEP
const flag_id flag_TRADER_KEEP("TRADER_KEEP") ("TRADER_KEEP")
Referenced by npc::wants_to_sell().
flag_TRADER_KEEP_EQUIPPED
const flag_id flag_TRADER_KEEP_EQUIPPED("TRADER_KEEP_EQUIPPED") ("TRADER_KEEP_EQUIPPED")
Referenced by npc::wants_to_sell().
flag_TWO_WAY_RADIO
const flag_id flag_TWO_WAY_RADIO("TWO_WAY_RADIO") ("TWO_WAY_RADIO")
Referenced by npc::reach_omt_destination().
flag_UNBREAKABLE
const flag_id flag_UNBREAKABLE("UNBREAKABLE") ("UNBREAKABLE")
Referenced by item::burn(), item::damage_armor_durability(), Character::handle_melee_wear(), and item::mod_damage().
flag_UNBREAKABLE_MELEE
const flag_id flag_UNBREAKABLE_MELEE("UNBREAKABLE_MELEE") ("UNBREAKABLE_MELEE")
Referenced by Character::handle_melee_wear().
flag_UNDERFED
const flag_id flag_UNDERFED("UNDERFED") ("UNDERFED")
Referenced by butchery_drops_harvest().
flag_UNDERSIZE
const flag_id flag_UNDERSIZE("UNDERSIZE") ("UNDERSIZE")
Referenced by repair_item_actor::can_repair_target(), repair_item_actor::default_action(), item::get_sizing(), repair_item_actor::repair(), and outfit::wear_item().
flag_UNDERWATER_GUN
const flag_id flag_UNDERWATER_GUN("UNDERWATER_GUN") ("UNDERWATER_GUN")
Referenced by Character::get_weapon_dispersion().
flag_UNRECOVERABLE
const flag_id flag_UNRECOVERABLE("UNRECOVERABLE") ("UNRECOVERABLE")
Referenced by Character::complete_disassemble(), vehicle_part::get_salvageable(), item::get_uncraft_components(), and vehicle_part::vehicle_part().
flag_UNRESTRICTED
const flag_id flag_UNRESTRICTED("UNRESTRICTED") ("UNRESTRICTED")
Referenced by Character::can_wear(), and outfit::wearing_fitting_on().
flag_URSINE_HONEY
const flag_id flag_URSINE_HONEY("URSINE_HONEY") ("URSINE_HONEY")
Referenced by Character::can_eat(), Character::modify_morale(), and Item_factory::set_allergy_flags().
flag_USE_EAT_VERB
const flag_id flag_USE_EAT_VERB("USE_EAT_VERB") ("USE_EAT_VERB")
Referenced by Character::can_eat(), game_menus::inv::consume_drink(), game_menus::inv::consume_food(), eat(), Character::get_consume_time(), Character::modify_morale(), and Character::will_eat().
flag_USE_PLAYER_ENERGY
const flag_id flag_USE_PLAYER_ENERGY("USE_PLAYER_ENERGY") ("USE_PLAYER_ENERGY")
Referenced by activity_handlers::spellcasting_finish(), and cast_spell_actor::use().
flag_USE_POWER_WHEN_HIT
const flag_id flag_USE_POWER_WHEN_HIT("USE_POWER_WHEN_HIT") ("USE_POWER_WHEN_HIT")
Referenced by Character::armor_absorb().
flag_USE_UPS
const flag_id flag_USE_UPS("USE_UPS") ("USE_UPS")
Referenced by anonymous_namespace{item.cpp}::_stacks_ups(), outfit::activate_combat_items(), item::ammo_consume(), item::ammo_remaining(), item::energy_consume(), item::energy_remaining(), item::get_gun_ups_drain(), item::getlight_emit(), gunmode_checks_weapon(), Character::invoke_item(), Character::process_items(), item::process_tool(), process_vehicle_items(), repair_item_finish(), item::tool_info(), iuse::toolmod_attach(), Character::unload(), anonymous_namespace{item_tname.cpp}::ups(), and Character::use_charges().
flag_USES_BIONIC_POWER
const flag_id flag_USES_BIONIC_POWER("USES_BIONIC_POWER") ("USES_BIONIC_POWER")
Referenced by item::ammo_capacity(), item::ammo_consume(), item::ammo_remaining(), item::ammo_set(), Character::available_ups(), Character::consume_ups(), item::energy_consume(), item::energy_remaining(), item::get_gun_bionic_drain(), item::getlight_emit(), gunmode_checks_weapon(), bionic::initialize_pseudo_items(), Character::invoke_item(), item::print_ammo(), repair_item_finish(), item::tool_info(), iuse::toolmod_attach(), bionic::uninstall_weapon(), bionic::update_weapon_flags(), and Character::use_fire().
flag_VARSIZE
const flag_id flag_VARSIZE("VARSIZE") ("VARSIZE")
Referenced by anonymous_namespace{item.cpp}::_stacks_clothing_size(), armor_encumb_header_info(), item::armor_fit_info(), repair_item_actor::can_repair_target(), anonymous_namespace{armor_layers.cpp}::clothing_flags_description(), anonymous_namespace{item_tname.cpp}::clothing_size(), Character::complete_disassemble(), create_byproducts_legacy(), recipe::create_result(), Single_item_creator::create_single_without_container(), repair_item_actor::default_action(), Item_factory::finalize_post_armor(), item::get_encumber(), recipe_result_info_cache::get_item_header(), get_recipe_result_item(), item::inherit_flags(), profession::items(), iexamine::nanofab(), repair_item_actor::repair(), repair_item_finish(), outfit::set_fitted(), map::spawn_item(), starting_clothes(), and starting_inv().
flag_VEHICLE
const flag_id flag_VEHICLE("VEHICLE") ("VEHICLE")
Referenced by item::can_reload_with(), iuse::capture_monster_veh(), cycle_action(), Character::fire_gun(), item::is_reloadable(), vehicle::part_to_item(), and vehicle_part::set_base().
flag_WAIST
const flag_id flag_WAIST("WAIST") ("WAIST")
Referenced by Item_factory::check_definitions(), anonymous_namespace{armor_layers.cpp}::clothing_layer(), and Item_factory::finalize_post_armor().
flag_WATCH
const flag_id flag_WATCH("WATCH") ("WATCH")
Referenced by Character::has_watch().
flag_WATER_BREAK
const flag_id flag_WATER_BREAK("WATER_BREAK") ("WATER_BREAK")
Referenced by check_water_affect_items(), item::process_internal(), and game::water_affect_items().
flag_WATER_BREAK_ACTIVE
const flag_id flag_WATER_BREAK_ACTIVE("WATER_BREAK_ACTIVE") ("WATER_BREAK_ACTIVE")
Referenced by check_water_affect_items(), item::is_broken_on_active(), avatar_action::use_item(), and game::water_affect_items().
flag_WATER_DISSOLVE
const flag_id flag_WATER_DISSOLVE("WATER_DISSOLVE") ("WATER_DISSOLVE")
Referenced by check_water_affect_items(), and game::water_affect_items().
flag_WATER_EXTINGUISH
const flag_id flag_WATER_EXTINGUISH("WATER_EXTINGUISH") ("WATER_EXTINGUISH")
Referenced by item::process_internal(), and anonymous_namespace{item_tname.cpp}::tags().
flag_WATER_FRIENDLY
const flag_id flag_WATER_FRIENDLY("WATER_FRIENDLY") ("WATER_FRIENDLY")
Referenced by Character::apply_wetness_morale(), and anonymous_namespace{armor_layers.cpp}::clothing_flags_description().
flag_WATERPROOF
const flag_id flag_WATERPROOF("WATERPROOF") ("WATERPROOF")
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_flags_description(), Character::is_waterproof(), and inventory::rust_iron_items().
flag_WATERPROOF_GUN
const flag_id flag_WATERPROOF_GUN("WATERPROOF_GUN") ("WATERPROOF_GUN")
Referenced by Character::handle_gun_damage(), item::is_gunmod_compatible(), and inventory::rust_iron_items().
flag_WET
const flag_id flag_WET("WET") ("WET")
Referenced by item::color_in_inventory(), item::io(), item::process_internal(), item::process_wet(), iuse::towel_common(), and anonymous_namespace{item_tname.cpp}::wetness().
flag_WHIP
const flag_id flag_WHIP("WHIP") ("WHIP")
Referenced by Character::reach_attack().
flag_WIND_EXTINGUISH
const flag_id flag_WIND_EXTINGUISH("WIND_EXTINGUISH") ("WIND_EXTINGUISH")
Referenced by item::process_extinguish(), and item::process_internal().
flag_WONT_TRAIN_MARKSMANSHIP
const flag_id flag_WONT_TRAIN_MARKSMANSHIP("WONT_TRAIN_MARKSMANSHIP") ("WONT_TRAIN_MARKSMANSHIP")
Referenced by Character::fire_gun().
flag_wooled
const flag_id flag_wooled("wooled") ("wooled")
Referenced by Character::can_wear(), and item::color_in_inventory().
flag_WRITE_MESSAGE
const flag_id flag_WRITE_MESSAGE("WRITE_MESSAGE") ("WRITE_MESSAGE")
Referenced by iuse::binder_add_recipe(), bookbinder_copy_activity_actor::finish(), and iexamine::sign().
flag_ZERO_WEIGHT
const flag_id flag_ZERO_WEIGHT("ZERO_WEIGHT") ("ZERO_WEIGHT")
Referenced by is_physical(), craft_command::safe_to_unload_comp(), and within_autopickup_limits().
flag_ZOOM
const flag_id flag_ZOOM("ZOOM") ("ZOOM")
Referenced by Character::fastest_aiming_method_speed(), Character::most_accurate_aiming_method_limit(), Character::on_item_acquire(), Character::overmap_sight_range(), and item::sight_dispersion().
json_flag_HIDDEN_ITEM
const flag_id json_flag_HIDDEN_ITEM("HIDDEN_ITEM") ("HIDDEN_ITEM")
Referenced by activity_handlers::plant_seed_finish().
json_flag_null
const flag_id json_flag_null("null") ("null") static