Cataclysm DDA: src/flexbuffer_json.h File Reference
flexbuffer_json.h File Reference
#include <optional>
#include <string>
#include <type_traits>
#include <flatbuffers/flexbuffers.h>
#include "cata_bitset.h"
#include "cata_small_literal_vector.h"
#include "cata_utility.h"
#include "flexbuffer_cache.h"
#include "json.h"
#include "json_error.h"
#include "int_id.h"
#include "memory_fast.h"
#include "string_id.h"
#include "flexbuffer_json-inl.h"
Classes
struct JsonPath
class Json
class JsonWithPath
class JsonValue
class JsonArray
class JsonMember
class JsonObject
Macros
#define CATA_SRC_FLEXBUFFER_JSON_H
Functions
flexbuffers::Reference flexbuffer_root_from_storage (const std::shared_ptr< flexbuffer_storage > &storage)
void add_array_to_set (std::set< std::string > &s, const JsonObject &json, std::string_view name)
Macro Definition Documentation
CATA_SRC_FLEXBUFFER_JSON_H
#define CATA_SRC_FLEXBUFFER_JSON_H
Definition at line 3 of file flexbuffer_json.h.
Function Documentation
add_array_to_set()
void add_array_to_set (std::set< std::string > & s, const JsonObject & json, std::string_view name) inline
Definition at line 1110 of file flexbuffer_json-inl.h.
 {
     for( const std::string line : json.get_array( name ) ) {
         s.insert( line );
     }
 }
References JsonObject::get_array(), line(), and om_direction::name().
Referenced by MonsterGroupManager::LoadMonsterBlacklist(), and MonsterGroupManager::LoadMonsterWhitelist().
flexbuffer_root_from_storage()
flexbuffers::Reference flexbuffer_root_from_storage (const std::shared_ptr< flexbuffer_storage > & storage) inline
Definition at line 84 of file flexbuffer_json.h.
 {
     return flexbuffers::GetRoot( storage->data(), storage->size() );
 }
Referenced by JsonObject::error_no_member(), JsonObject::error_skipped_members(), anonymous_namespace{json_loader.cpp}::from_path_at_offset_opt_impl(), json_loader::from_string(), Json::string_error(), and Json::throw_error_after().