Cataclysm DDA: src/flexbuffer_json.cpp File Reference
flexbuffer_json.cpp File Reference
#include "flexbuffer_json.h"
#include <atomic>
#include <cstring>
#include <istream>
#include <optional>
#include "cata_unreachable.h"
#include "filesystem.h"
#include "json.h"
Namespaces
anonymous_namespace{flexbuffer_json.cpp}
Functions
static void advance_jsin (TextJsonIn *jsin, flexbuffers::Reference root, const JsonPath &path)
Variables
std::atomic_bool anonymous_namespace{flexbuffer_json.cpp}::report_unvisited_members {true}
Function Documentation
advance_jsin()
static void advance_jsin (TextJsonIn * jsin, flexbuffers::Reference root, const JsonPath & path) static
Definition at line 59 of file flexbuffer_json.cpp.
 {
     for( JsonPath::index_type idx : path ) {
         if( root.IsMap() ) {
             std::string member = root.AsMap().Keys()[ idx ].AsString().str();
             jsin->start_object();
             while( !jsin->end_object() ) {
                 if( jsin->get_member_name() == member ) {
                     break;
                 }
                 jsin->skip_value();
             }
             root = root.AsVector()[ idx ];
         } else if( root.IsVector() ) {
             jsin->start_array();
             for( size_t i = 0; i < idx && !jsin->end_array(); ++i ) {
                 jsin->skip_value();
             }
             root = root.AsVector()[ idx ];
         } else {
             cata_unreachable();
         }
     }
 }
References cata_unreachable(), TextJsonIn::end_array(), TextJsonIn::end_object(), TextJsonIn::get_member_name(), member, TextJsonIn::skip_value(), TextJsonIn::start_array(), and TextJsonIn::start_object().
Referenced by JsonObject::error_no_member(), JsonObject::error_skipped_members(), Json::string_error(), and Json::throw_error_after().