Cataclysm DDA: src/flexbuffer_json-inl.h File Reference
flexbuffer_json-inl.h File Reference
#include <optional>
#include <string>
#include <type_traits>
#include <flatbuffers/flexbuffers.h>
#include "cata_bitset.h"
#include "cata_small_literal_vector.h"
#include "filesystem.h"
#include "flexbuffer_cache.h"
#include "json.h"
#include "json_error.h"
#include "int_id.h"
#include "memory_fast.h"
#include "string_id.h"
Classes
class JsonArray::const_iterator
class JsonObject::const_iterator
Macros
#define CATA_SRC_FLEXBUFFER_JSON_INL_H
Functions
template<typename T >
void deserialize (std::optional< T > &obj, const JsonValue &jsin)
void add_array_to_set (std::set< std::string > &s, const JsonObject &json, const std::string_view name)
Macro Definition Documentation
CATA_SRC_FLEXBUFFER_JSON_INL_H
#define CATA_SRC_FLEXBUFFER_JSON_INL_H
Definition at line 3 of file flexbuffer_json-inl.h.
Function Documentation
add_array_to_set()
void add_array_to_set (std::set< std::string > & s, const JsonObject & json, const std::string_view name) inline
Definition at line 1110 of file flexbuffer_json-inl.h.
 {
     for( const std::string line : json.get_array( name ) ) {
         s.insert( line );
     }
 }
References JsonObject::get_array(), line(), and om_direction::name().
Referenced by MonsterGroupManager::LoadMonsterBlacklist(), and MonsterGroupManager::LoadMonsterWhitelist().
deserialize()
template<typename T > void deserialize (std::optional< T > & obj, const JsonValue & jsin)
Definition at line 1100 of file flexbuffer_json-inl.h.
 {
     if( jsin.test_null() ) {
         obj.reset();
     } else {
         obj.emplace( T{} );
         jsin.read( *obj, true );
     }
 }
References int_id< T >::obj(), JsonValue::read(), and JsonValue::test_null().
Referenced by JsonValue::read().