Cataclysm DDA: src/fragment_cloud.h File Reference
fragment_cloud.h File Reference
Classes
struct fragment_cloud
Macros
#define CATA_SRC_FRAGMENT_CLOUD_H
Functions
bool operator< (const fragment_cloud &us, const fragment_cloud &them)
fragment_cloud shrapnel_calc (const fragment_cloud &initial, const fragment_cloud &cloud, const int &distance)
bool shrapnel_check (const fragment_cloud &cloud, const fragment_cloud &intensity)
void update_fragment_cloud (fragment_cloud &update, const fragment_cloud &new_value, quadrant)
fragment_cloud accumulate_fragment_cloud (const fragment_cloud &cumulative_cloud, const fragment_cloud &current_cloud, const int &distance)
Macro Definition Documentation
CATA_SRC_FRAGMENT_CLOUD_H
#define CATA_SRC_FRAGMENT_CLOUD_H
Definition at line 3 of file fragment_cloud.h.
Function Documentation
accumulate_fragment_cloud()
fragment_cloud accumulate_fragment_cloud (const fragment_cloud & cumulative_cloud, const fragment_cloud & current_cloud, const int & distance)
Definition at line 969 of file explosion.cpp.
 {
     // Velocity is the cumulative and continuous decay of speed,
     // so it is accumulated the same way as light attenuation.
     // Density is the accumulation of discrete attenuation events encountered in the traversed squares,
     // so each term is added to the series via multiplication.
     return fragment_cloud( ( ( distance - 1 ) * cumulative_cloud.velocity + current_cloud.velocity ) /
                            distance,
                            cumulative_cloud.density * current_cloud.density );
 }
References fragment_cloud::density, and fragment_cloud::velocity.
Referenced by explosion_handler::shrapnel().
operator<()
bool operator< (const fragment_cloud & us, const fragment_cloud & them)
Definition at line 936 of file explosion.cpp.
 {
     return us.density < them.density && us.velocity < them.velocity;
 }
References fragment_cloud::density, and fragment_cloud::velocity.
shrapnel_calc()
fragment_cloud shrapnel_calc (const fragment_cloud & initial, const fragment_cloud & cloud, const int & distance)
Definition at line 943 of file explosion.cpp.
 {
     // SWAG coefficient of drag.
     constexpr float Cd = 1.5f;
     fragment_cloud new_cloud;
     new_cloud.velocity = initial.velocity * std::exp( -cloud.velocity * ( (
                              Cd * fragment_area * distance ) /
                          ( 2.0f * fragment_mass ) ) );
     // Two effects, the accumulated proportion of blocked fragments,
     // and the inverse-square dilution of fragments with distance.
     new_cloud.density = ( initial.density * cloud.density ) / ( distance * distance );
     return new_cloud;
 }
References fragment_cloud::density, fragment_area, fragment_mass, and fragment_cloud::velocity.
Referenced by explosion_handler::shrapnel().
shrapnel_check()
bool shrapnel_check (const fragment_cloud & cloud, const fragment_cloud & intensity)
Definition at line 958 of file explosion.cpp.
 {
     return cloud.density > 0.0 && intensity.velocity > MIN_EFFECTIVE_VELOCITY &&
            intensity.density > MIN_FRAGMENT_DENSITY;
 }
References fragment_cloud::density, intensity, MIN_EFFECTIVE_VELOCITY, and MIN_FRAGMENT_DENSITY.
Referenced by explosion_handler::shrapnel().
update_fragment_cloud()
void update_fragment_cloud (fragment_cloud & update, const fragment_cloud & new_value, quadrant)
Definition at line 964 of file explosion.cpp.
 {
     update = std::max( update, new_value );
 }
References max().
Referenced by explosion_handler::shrapnel().