Cataclysm DDA: src/fungal_effects.cpp File Reference
fungal_effects.cpp File Reference
#include "fungal_effects.h"
#include <algorithm>
#include <memory>
#include <ostream>
#include "calendar.h"
#include "character.h"
#include "creature.h"
#include "creature_tracker.h"
#include "debug.h"
#include "enums.h"
#include "field_type.h"
#include "game.h"
#include "item.h"
#include "item_stack.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "messages.h"
#include "monster.h"
#include "mtype.h"
#include "point.h"
#include "rng.h"
#include "string_formatter.h"
#include "translations.h"
#include "type_id.h"
Variables
static const efftype_id effect_spores ("spores")
static const efftype_id effect_stunned ("stunned")
static const furn_str_id furn_f_flower_fungal ("f_flower_fungal")
static const furn_str_id furn_f_fungal_clump ("f_fungal_clump")
static const furn_str_id furn_f_fungal_mass ("f_fungal_mass")
static const mtype_id mon_fungal_blossom ("mon_fungal_blossom")
static const mtype_id mon_spore ("mon_spore")
static const skill_id skill_melee ("melee")
static const species_id species_FUNGUS ("FUNGUS")
static const ter_str_id ter_t_fungus ("t_fungus")
static const ter_str_id ter_t_fungus_floor_in ("t_fungus_floor_in")
static const ter_str_id ter_t_fungus_floor_out ("t_fungus_floor_out")
static const ter_str_id ter_t_fungus_floor_sup ("t_fungus_floor_sup")
static const ter_str_id ter_t_fungus_mound ("t_fungus_mound")
static const ter_str_id ter_t_fungus_wall ("t_fungus_wall")
static const ter_str_id ter_t_marloss ("t_marloss")
static const ter_str_id ter_t_marloss_tree ("t_marloss_tree")
static const ter_str_id ter_t_shrub_fungal ("t_shrub_fungal")
static const ter_str_id ter_t_tree_fungal ("t_tree_fungal")
static const ter_str_id ter_t_tree_fungal_young ("t_tree_fungal_young")
static const trait_id trait_TAIL_CATTLE ("TAIL_CATTLE")
static const trait_id trait_THRESH_MYCUS ("THRESH_MYCUS")
Variable Documentation
effect_spores
const efftype_id effect_spores("spores") ("spores") static
Referenced by fungal_effects::fungalize().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by fungal_effects::fungalize().
furn_f_flower_fungal
const furn_str_id furn_f_flower_fungal("f_flower_fungal") ("f_flower_fungal") static
Referenced by fungal_effects::spread_fungus_one_tile().
furn_f_fungal_clump
const furn_str_id furn_f_fungal_clump("f_fungal_clump") ("f_fungal_clump") static
Referenced by fungal_effects::spread_fungus_one_tile().
furn_f_fungal_mass
const furn_str_id furn_f_fungal_mass("f_fungal_mass") ("f_fungal_mass") static
Referenced by fungal_effects::spread_fungus_one_tile().
mon_fungal_blossom
const mtype_id mon_fungal_blossom("mon_fungal_blossom") ("mon_fungal_blossom") static
Referenced by fungal_effects::spread_fungus_one_tile().
mon_spore
const mtype_id mon_spore("mon_spore") ("mon_spore") static
Referenced by fungal_effects::fungalize().
skill_melee
const skill_id skill_melee("melee") ("melee") static
Referenced by fungal_effects::fungalize().
species_FUNGUS
const species_id species_FUNGUS("FUNGUS") ("FUNGUS") static
Referenced by fungal_effects::fungalize().
ter_t_fungus
const ter_str_id ter_t_fungus("t_fungus") ("t_fungus") static
Referenced by fungal_effects::spread_fungus_one_tile().
ter_t_fungus_floor_in
const ter_str_id ter_t_fungus_floor_in("t_fungus_floor_in") ("t_fungus_floor_in") static
Referenced by fungal_effects::spread_fungus_one_tile().
ter_t_fungus_floor_out
const ter_str_id ter_t_fungus_floor_out("t_fungus_floor_out") ("t_fungus_floor_out") static
Referenced by fungal_effects::spread_fungus_one_tile().
ter_t_fungus_floor_sup
const ter_str_id ter_t_fungus_floor_sup("t_fungus_floor_sup") ("t_fungus_floor_sup") static
Referenced by fungal_effects::spread_fungus_one_tile().
ter_t_fungus_mound
const ter_str_id ter_t_fungus_mound("t_fungus_mound") ("t_fungus_mound") static
Referenced by fungal_effects::spread_fungus_one_tile().
ter_t_fungus_wall
const ter_str_id ter_t_fungus_wall("t_fungus_wall") ("t_fungus_wall") static
Referenced by fungal_effects::spread_fungus_one_tile().
ter_t_marloss
const ter_str_id ter_t_marloss("t_marloss") ("t_marloss") static
Referenced by fungal_effects::marlossify(), and fungal_effects::spread_fungus_one_tile().
ter_t_marloss_tree
const ter_str_id ter_t_marloss_tree("t_marloss_tree") ("t_marloss_tree") static
Referenced by fungal_effects::spread_fungus_one_tile().
ter_t_shrub_fungal
const ter_str_id ter_t_shrub_fungal("t_shrub_fungal") ("t_shrub_fungal") static
Referenced by fungal_effects::spread_fungus_one_tile().
ter_t_tree_fungal
const ter_str_id ter_t_tree_fungal("t_tree_fungal") ("t_tree_fungal") static
Referenced by fungal_effects::spread_fungus_one_tile().
ter_t_tree_fungal_young
const ter_str_id ter_t_tree_fungal_young("t_tree_fungal_young") ("t_tree_fungal_young") static
Referenced by fungal_effects::spread_fungus_one_tile().
trait_TAIL_CATTLE
const trait_id trait_TAIL_CATTLE("TAIL_CATTLE") ("TAIL_CATTLE") static
Referenced by fungal_effects::fungalize().
trait_THRESH_MYCUS
const trait_id trait_THRESH_MYCUS("THRESH_MYCUS") ("THRESH_MYCUS") static
Referenced by fungal_effects::fungalize().