Cataclysm DDA: src/game.cpp File Reference
game.cpp File Reference
#include "game.h"
#include <algorithm>
#include <bitset>
#include <chrono>
#include <climits>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <cwctype>
#include <exception>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <locale>
#include <map>
#include <memory>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <string>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "achievement.h"
#include "action.h"
#include "activity_actor_definitions.h"
#include "activity_handlers.h"
#include "activity_type.h"
#include "auto_note.h"
#include "auto_pickup.h"
#include "avatar.h"
#include "avatar_action.h"
#include "basecamp.h"
#include "bionics.h"
#include "body_part_set.h"
#include "bodygraph.h"
#include "bodypart.h"
#include "butchery_requirements.h"
#include "cached_options.h"
#include "cata_path.h"
#include "cata_scope_helpers.h"
#include "cata_utility.h"
#include "cata_variant.h"
#include "catacharset.h"
#include "character.h"
#include "character_attire.h"
#include "character_martial_arts.h"
#include "city.h"
#include "climbing.h"
#include "clzones.h"
#include "colony.h"
#include "color.h"
#include "computer.h"
#include "computer_session.h"
#include "construction.h"
#include "construction_group.h"
#include "contents_change_handler.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "creature_tracker.h"
#include "cuboid_rectangle.h"
#include "cursesport.h"
#include "damage.h"
#include "debug.h"
#include "dependency_tree.h"
#include "dialogue.h"
#include "dialogue_chatbin.h"
#include "diary.h"
#include "distraction_manager.h"
#include "editmap.h"
#include "effect.h"
#include "effect_on_condition.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "faction.h"
#include "fault.h"
#include "field.h"
#include "field_type.h"
#include "filesystem.h"
#include "flag.h"
#include "flexbuffer_json-inl.h"
#include "flexbuffer_json.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "game_ui.h"
#include "gamemode.h"
#include "gates.h"
#include "get_version.h"
#include "harvest.h"
#include "iexamine.h"
#include "init.h"
#include "input.h"
#include "input_context.h"
#include "input_enums.h"
#include "inventory.h"
#include "item.h"
#include "item_category.h"
#include "item_contents.h"
#include "item_location.h"
#include "item_pocket.h"
#include "item_search.h"
#include "item_stack.h"
#include "iteminfo_query.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "json.h"
#include "kill_tracker.h"
#include "level_cache.h"
#include "lightmap.h"
#include "line.h"
#include "live_view.h"
#include "loading_ui.h"
#include "magic.h"
#include "magic_enchantment.h"
#include "main_menu.h"
#include "make_static.h"
#include "map.h"
#include "map_item_stack.h"
#include "map_iterator.h"
#include "map_selector.h"
#include "mapbuffer.h"
#include "mapdata.h"
#include "mapsharing.h"
#include "maptile_fwd.h"
#include "memorial_logger.h"
#include "messages.h"
#include "mission.h"
#include "mod_manager.h"
#include "monexamine.h"
#include "mongroup.h"
#include "monster.h"
#include "monstergenerator.h"
#include "move_mode.h"
#include "mtype.h"
#include "npc.h"
#include "npc_class.h"
#include "npctrade.h"
#include "omdata.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "overmap_ui.h"
#include "overmapbuffer.h"
#include "panels.h"
#include "past_achievements_info.h"
#include "path_info.h"
#include "pathfinding.h"
#include "pickup.h"
#include "player_activity.h"
#include "popup.h"
#include "profession.h"
#include "proficiency.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "ret_val.h"
#include "rng.h"
#include "safemode_ui.h"
#include "scenario.h"
#include "scent_map.h"
#include "scores_ui.h"
#include "sdltiles.h"
#include "sounds.h"
#include "start_location.h"
#include "stats_tracker.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "talker.h"
#include "text_snippets.h"
#include "tileray.h"
#include "timed_event.h"
#include "translation.h"
#include "translation_cache.h"
#include "translations.h"
#include "trap.h"
#include "ui.h"
#include "ui_manager.h"
#include "uistate.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_appliance.h"
#include "veh_interact.h"
#include "veh_type.h"
#include "vehicle.h"
#include "viewer.h"
#include "visitable.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "wcwidth.h"
#include "weakpoint.h"
#include "weather.h"
#include "weather_type.h"
#include "worldfactory.h"
Classes
struct npc_dist_to_player
Namespaces
cata_event_dispatch
Macros
#define dbg(x) DebugLog((x),D_GAME) << __FILE__ << ":" << __LINE__ << ": "
Functions
bool is_valid_in_w_terrain (const point &p)
static void achievement_attained (const achievement *a, bool achievements_enabled)
static void achievement_failed (const achievement *a, bool achievements_enabled)
void check_encoding ()
void ensure_term_size ()
static int veh_lumi (vehicle &veh)
static bool cancel_auto_move (Character &you, const std::string &text)
static int maptile_field_intensity (maptile &mt, field_type_id fld)
units::temperature_delta get_heat_radiation (const tripoint &location)
int get_best_fire (const tripoint &location)
units::temperature_delta get_convection_temperature (const tripoint &location)
static void update_faction_api (npc *guy)
static hint_rating rate_action_change_side (const avatar &you, const item &it)
static hint_rating rate_action_disassemble (avatar &you, const item &it)
static hint_rating rate_action_view_recipe (avatar &you, const item &it)
static hint_rating rate_action_eat (const avatar &you, const item &it)
static hint_rating rate_action_collapse (const item &it)
static hint_rating rate_action_expand (const item &it)
static hint_rating rate_action_mend (const avatar &, const item &it)
static hint_rating rate_action_read (const avatar &you, const item &it)
static hint_rating rate_action_take_off (const avatar &you, const item &it)
static hint_rating rate_action_use (const avatar &you, const item &it)
static hint_rating rate_action_wear (const avatar &you, const item &it)
static hint_rating rate_action_wield (const avatar &you, const item &it)
static hint_rating rate_action_insert (const avatar &you, const item_location &loc)
input_context get_default_mode_input_context ()
static std::string timestamp_now ()
static void draw_footsteps (const catacurses::window &window, const tripoint &offset)
static void draw_trail (const tripoint &start, const tripoint &end, bool bDrawX)
static shared_ptr_fast< game::draw_callback_t > create_zone_callback (const std::optional< tripoint > &zone_start, const std::optional< tripoint > &zone_end, const bool &zone_blink, const bool &zone_cursor, const bool &is_moving_zone=false)
static shared_ptr_fast< game::draw_callback_t > create_trail_callback (const std::optional< tripoint > &trail_start, const std::optional< tripoint > &trail_end, const bool &trail_end_x)
static bool can_place_monster (const monster &mon, const tripoint &p)
static bool can_place_npc (const tripoint &p)
static std::optional< tripoint > choose_where_to_place_monster (const monster &mon, const tripoint_range< tripoint > &range)
static std::string get_fire_fuel_string (const tripoint &examp)
static void add_visible_items_recursive (std::map< std::string, std::pair< int, nc_color >> &item_names, const item &it)
static void zones_manager_shortcuts (const catacurses::window &w_info, faction_id const &faction)
static void zones_manager_draw_borders (const catacurses::window &w_border, const catacurses::window &w_info_border, const int iInfoHeight, const int width)
static void add_item_recursive (std::vector< std::string > &item_order, std::map< std::string, map_item_stack > &temp_items, const item *it, const tripoint &relative_pos)
static void centerlistview (const tripoint &active_item_position, int ui_width)
static std::string list_items_filter_history_help ()
static content_newness check_items_newness (const item *itm)
return content_newness based on if item is known and nested items are known
static void mark_items_read_rec (const item *itm)
add item and all visible nested items inside to known items
static std::optional< input_event > get_initial_hotkey (const size_t menu_index)
static std::vector< std::pair< map_stack::iterator, int > > generate_butcher_stack_display (const std::vector< map_stack::iterator > &its)
static void add_corpses (uilist &menu, const std::vector< map_stack::iterator > &its, size_t &menu_index)
static void add_salvagables (uilist &menu, const std::vector< std::pair< map_stack::iterator, int >> &stacks, size_t &menu_index, const salvage_actor &salvage_iuse)
static void add_disassemblables (uilist &menu, const std::vector< std::pair< map_stack::iterator, int >> &stacks, size_t &menu_index)
static void butcher_submenu (const std::vector< map_stack::iterator > &corpses, int index=-1)
static item::reload_option favorite_ammo_or_select (avatar &u, item_location &loc, bool empty, bool prompt)
static std::optional< tripoint > find_empty_spot_nearby (const tripoint &pos)
static int climb_affordance_menu_encode (const climbing_aid_id &aid_id)
static bool climb_affordance_menu_decode (int retval, climbing_aid_id &aid_id)
void cata_event_dispatch::avatar_moves (const tripoint &old_abs_pos, const avatar &u, const map &m)
achievements_tracker & get_achievements ()
Character & get_player_character ()
viewer & get_player_view ()
avatar & get_avatar ()
map & get_map ()
creature_tracker & get_creature_tracker ()
event_bus & get_event_bus ()
memorial_logger & get_memorial ()
const scenario * get_scenario ()
void set_scenario (const scenario *new_scenario)
scent_map & get_scent ()
stats_tracker & get_stats ()
timed_event_manager & get_timed_events ()
weather_manager & get_weather ()
global_variables & get_globals ()
Variables
static const activity_id ACT_BLEED ("ACT_BLEED")
static const activity_id ACT_BUTCHER ("ACT_BUTCHER")
static const activity_id ACT_BUTCHER_FULL ("ACT_BUTCHER_FULL")
static const activity_id ACT_DISMEMBER ("ACT_DISMEMBER")
static const activity_id ACT_DISSECT ("ACT_DISSECT")
static const activity_id ACT_FIELD_DRESS ("ACT_FIELD_DRESS")
static const activity_id ACT_PULP ("ACT_PULP")
static const activity_id ACT_QUARTER ("ACT_QUARTER")
static const activity_id ACT_SKIN ("ACT_SKIN")
static const activity_id ACT_TRAIN ("ACT_TRAIN")
static const activity_id ACT_TRAIN_TEACHER ("ACT_TRAIN_TEACHER")
static const activity_id ACT_TRAVELLING ("ACT_TRAVELLING")
static const activity_id ACT_VIEW_RECIPE ("ACT_VIEW_RECIPE")
static const bionic_id bio_jointservo ("bio_jointservo")
static const bionic_id bio_probability_travel ("bio_probability_travel")
static const bionic_id bio_remote ("bio_remote")
static const character_modifier_id character_modifier_slip_prevent_mod ("slip_prevent_mod")
static const climbing_aid_id climbing_aid_ability_WALL_CLING ("ability_WALL_CLING")
static const climbing_aid_id climbing_aid_default ("default")
static const climbing_aid_id climbing_aid_furn_CLIMBABLE ("furn_CLIMBABLE")
static const damage_type_id damage_acid ("acid")
static const damage_type_id damage_bash ("bash")
static const damage_type_id damage_cut ("cut")
static const efftype_id effect_adrenaline_mycus ("adrenaline_mycus")
static const efftype_id effect_asked_to_train ("asked_to_train")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_bouldering ("bouldering")
static const efftype_id effect_contacts ("contacts")
static const efftype_id effect_docile ("docile")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_fake_common_cold ("fake_common_cold")
static const efftype_id effect_fake_flu ("fake_flu")
static const efftype_id effect_gliding ("gliding")
static const efftype_id effect_laserlocked ("laserlocked")
static const efftype_id effect_led_by_leash ("led_by_leash")
static const efftype_id effect_no_sight ("no_sight")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_psi_stunned ("psi_stunned")
static const efftype_id effect_ridden ("ridden")
static const efftype_id effect_riding ("riding")
static const efftype_id effect_stunned ("stunned")
static const efftype_id effect_tetanus ("tetanus")
static const efftype_id effect_tied ("tied")
static const efftype_id effect_took_xanax ("took_xanax")
static const efftype_id effect_transition_contacts ("transition_contacts")
static const efftype_id effect_winded ("winded")
static const faction_id faction_no_faction ("no_faction")
static const faction_id faction_your_followers ("your_followers")
static const flag_id json_flag_CONVECTS_TEMPERATURE ("CONVECTS_TEMPERATURE")
static const flag_id json_flag_LEVITATION ("LEVITATION")
static const flag_id json_flag_NO_RELOAD ("NO_RELOAD")
static const flag_id json_flag_SPLINT ("SPLINT")
static const furn_str_id furn_f_rope_up ("f_rope_up")
static const furn_str_id furn_f_web_up ("f_web_up")
static const harvest_drop_type_id harvest_drop_blood ("blood")
static const harvest_drop_type_id harvest_drop_offal ("offal")
static const harvest_drop_type_id harvest_drop_skin ("skin")
static const itype_id fuel_type_animal ("animal")
static const itype_id itype_battery ("battery")
static const itype_id itype_disassembly ("disassembly")
static const itype_id itype_grapnel ("grapnel")
static const itype_id itype_holybook_bible1 ("holybook_bible1")
static const itype_id itype_holybook_bible2 ("holybook_bible2")
static const itype_id itype_holybook_bible3 ("holybook_bible3")
static const itype_id itype_manhole_cover ("manhole_cover")
static const itype_id itype_remotevehcontrol ("remotevehcontrol")
static const itype_id itype_rope_30 ("rope_30")
static const itype_id itype_swim_fins ("swim_fins")
static const itype_id itype_towel ("towel")
static const itype_id itype_towel_wet ("towel_wet")
static const json_character_flag json_flag_CLIMB_NO_LADDER ("CLIMB_NO_LADDER")
static const json_character_flag json_flag_GRAB ("GRAB")
static const json_character_flag json_flag_HYPEROPIC ("HYPEROPIC")
static const json_character_flag json_flag_INFECTION_IMMUNE ("INFECTION_IMMUNE")
static const json_character_flag json_flag_NYCTOPHOBIA ("NYCTOPHOBIA")
static const json_character_flag json_flag_WALL_CLING ("WALL_CLING")
static const json_character_flag json_flag_WEB_RAPPEL ("WEB_RAPPEL")
static const material_id material_glass ("glass")
static const mod_id MOD_INFORMATION_dda ("dda")
static const mongroup_id GROUP_BLACK_ROAD ("GROUP_BLACK_ROAD")
static const mtype_id mon_manhack ("mon_manhack")
static const overmap_special_id overmap_special_world ("world")
static const proficiency_id proficiency_prof_parkour ("prof_parkour")
static const proficiency_id proficiency_prof_wound_care ("prof_wound_care")
static const proficiency_id proficiency_prof_wound_care_expert ("prof_wound_care_expert")
static const quality_id qual_BUTCHER ("BUTCHER")
static const quality_id qual_CUT_FINE ("CUT_FINE")
static const skill_id skill_dodge ("dodge")
static const skill_id skill_firstaid ("firstaid")
static const skill_id skill_gun ("gun")
static const skill_id skill_survival ("survival")
static const species_id species_PLANT ("PLANT")
static const string_id< npc_template > npc_template_cyborg_rescued ("cyborg_rescued")
static const ter_str_id ter_t_elevator ("t_elevator")
static const ter_str_id ter_t_grave_new ("t_grave_new")
static const ter_str_id ter_t_lava ("t_lava")
static const ter_str_id ter_t_manhole ("t_manhole")
static const ter_str_id ter_t_manhole_cover ("t_manhole_cover")
static const ter_str_id ter_t_pit ("t_pit")
static const ter_str_id ter_t_pit_shallow ("t_pit_shallow")
static const trait_id trait_BADKNEES ("BADKNEES")
static const trait_id trait_CANNIBAL ("CANNIBAL")
static const trait_id trait_CENOBITE ("CENOBITE")
static const trait_id trait_ILLITERATE ("ILLITERATE")
static const trait_id trait_INATTENTIVE ("INATTENTIVE")
static const trait_id trait_INFRESIST ("INFRESIST")
static const trait_id trait_LEG_TENT_BRACE ("LEG_TENT_BRACE")
static const trait_id trait_MASOCHIST ("MASOCHIST")
static const trait_id trait_MASOCHIST_MED ("MASOCHIST_MED")
static const trait_id trait_M_DEFENDER ("M_DEFENDER")
static const trait_id trait_M_IMMUNE ("M_IMMUNE")
static const trait_id trait_NPC_STARTING_NPC ("NPC_STARTING_NPC")
static const trait_id trait_NPC_STATIC_NPC ("NPC_STATIC_NPC")
static const trait_id trait_PROF_CHURL ("PROF_CHURL")
static const trait_id trait_PSYCHOPATH ("PSYCHOPATH")
static const trait_id trait_THICKSKIN ("THICKSKIN")
static const trait_id trait_VINES2 ("VINES2")
static const trait_id trait_VINES3 ("VINES3")
static const trait_id trait_WAYFARER ("WAYFARER")
static const zone_type_id zone_type_LOOT_CUSTOM ("LOOT_CUSTOM")
static const zone_type_id zone_type_NO_AUTO_PICKUP ("NO_AUTO_PICKUP")
static constexpr int DANGEROUS_PROXIMITY = 5
std::unique_ptr< game > g
uistatedata uistate
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x),D_GAME) << __FILE__ << ":" << __LINE__ << ": "
Definition at line 373 of file game.cpp.
Function Documentation
achievement_attained()
static void achievement_attained (const achievement * a, bool achievements_enabled) static
Definition at line 392 of file game.cpp.
 {
     if( achievements_enabled ) {
         add_msg( m_good, _( "You completed the achievement \"%s\"." ),
                  a->name() );
         std::string popup_option = get_option<std::string>( "ACHIEVEMENT_COMPLETED_POPUP" );
         bool show_popup;
         if( test_mode || popup_option == "never" ) {
             show_popup = false;
         } else if( popup_option == "always" ) {
             show_popup = true;
         } else if( popup_option == "first" ) {
             show_popup = !get_past_achievements().is_completed( a->id );
         } else {
             debugmsg( "Unexpected ACHIEVEMENT_COMPLETED_POPUP option value %s", popup_option );
             show_popup = false;
         }
         if( show_popup ) {
             std::string message = colorize( _( "Achievement completed!" ), c_light_green );
             message += "\n\n";
             message += get_achievements().ui_text_for( a );
             message += "\n";
             message += colorize( _( "Achievement completion popups can be\nconfigured via the "
                                     "Interface options" ), c_dark_gray );
             popup( message );
         }
     }
     get_event_bus().send<event_type::player_gets_achievement>( a->id, achievements_enabled );
 }
References _, a, add_msg(), c_dark_gray, c_light_green, colorize(), debugmsg, get_achievements(), get_event_bus(), get_past_achievements(), past_achievements_info::is_completed(), m_good, mapgen_defer::message, player_gets_achievement, popup(), event_bus::send(), test_mode, and achievements_tracker::ui_text_for().
achievement_failed()
static void achievement_failed (const achievement * a, bool achievements_enabled) static
Definition at line 423 of file game.cpp.
 {
     if( !a->is_conduct() ) {
         return;
     }
     if( achievements_enabled ) {
         add_msg( m_bad, _( "You lost the conduct \"%s\"." ), a->name() );
     }
     get_event_bus().send<event_type::player_fails_conduct>( a->id, achievements_enabled );
 }
References _, a, add_msg(), get_event_bus(), m_bad, player_fails_conduct, and event_bus::send().
add_corpses()
static void add_corpses (uilist & menu, const std::vector< map_stack::iterator > & its, size_t & menu_index) static
Definition at line 9388 of file game.cpp.
 {
     std::optional<input_event> hotkey = get_initial_hotkey( menu_index );
     for( const map_stack::iterator &it : its ) {
         menu.addentry( menu_index++, true, hotkey, it->get_mtype()->nname() );
         hotkey = std::nullopt;
     }
 }
References uilist::addentry(), and get_initial_hotkey().
Referenced by game::butcher().
add_disassemblables()
static void add_disassemblables (uilist & menu, const std::vector< std::pair< map_stack::iterator, int >> & stacks, size_t & menu_index) static
Definition at line 9421 of file game.cpp.
 {
     if( !stacks.empty() ) {
         std::optional<input_event> hotkey = get_initial_hotkey( menu_index );
         for( const auto &stack : stacks ) {
             const item &it = *stack.first;
             //~ Name, number of items and time to complete disassembling
             const std::string &msg = string_format( pgettext( "butchery menu", "Disassemble %s (%d)" ),
                                                     it.tname(), stack.second );
             recipe uncraft_recipe;
             if( it.typeId() == itype_disassembly ) {
                 uncraft_recipe = it.get_making();
             } else {
                 uncraft_recipe = recipe_dictionary::get_uncraft( it.typeId() );
             }
             menu.addentry_col( menu_index++, true, hotkey, msg,
                                to_string_clipped( uncraft_recipe.time_to_craft( get_player_character(),
                                                   recipe_time_flag::ignore_proficiencies ) ) );
             hotkey = std::nullopt;
         }
     }
 }
References uilist::addentry_col(), get_initial_hotkey(), item::get_making(), game::get_player_character, recipe_dictionary::get_uncraft(), ignore_proficiencies, itype_disassembly, pgettext, string_format(), recipe::time_to_craft(), item::tname(), to_string_clipped(), and item::typeId().
Referenced by game::butcher().
add_item_recursive()
static void add_item_recursive (std::vector< std::string > & item_order, std::map< std::string, map_item_stack > & temp_items, const item * it, const tripoint & relative_pos) static
Definition at line 8018 of file game.cpp.
 {
     const std::string name = it->tname();
     if( std::find( item_order.begin(), item_order.end(), name ) == item_order.end() ) {
         item_order.push_back( name );
         temp_items[name] = map_item_stack( it, relative_pos );
     } else {
         temp_items[name].add_at_pos( it, relative_pos );
     }
     for( const item *content : it->all_known_contents() ) {
         add_item_recursive( item_order, temp_items, content, relative_pos );
     }
 }
References item::all_known_contents(), om_direction::name(), and item::tname().
Referenced by game::find_nearby_items().
add_salvagables()
static void add_salvagables (uilist & menu, const std::vector< std::pair< map_stack::iterator, int >> & stacks, size_t & menu_index, const salvage_actor & salvage_iuse) static
Definition at line 9400 of file game.cpp.
 {
     if( !stacks.empty() ) {
         std::optional<input_event> hotkey = get_initial_hotkey( menu_index );
         for( const auto &stack : stacks ) {
             const item &it = *stack.first;
             //~ Name and number of items listed for cutting up
             const std::string &msg = string_format( pgettext( "butchery menu", "Cut up %s (%d)" ),
                                                     it.tname(), stack.second );
             menu.addentry_col( menu_index++, true, hotkey, msg,
                                to_string_clipped( time_duration::from_turns( salvage_iuse.time_to_cut_up( it ) / 100 ) ) );
             hotkey = std::nullopt;
         }
     }
 }
References uilist::addentry_col(), time_duration::from_turns(), get_initial_hotkey(), pgettext, string_format(), salvage_actor::time_to_cut_up(), item::tname(), and to_string_clipped().
Referenced by game::butcher().
add_visible_items_recursive()
static void add_visible_items_recursive (std::map< std::string, std::pair< int, nc_color >> & item_names, const item & it) static
Definition at line 6782 of file game.cpp.
 {
     ++item_names[it.tname()].first;
     item_names[it.tname()].second = it.color_in_inventory();
     for( const item *content : it.all_known_contents() ) {
         add_visible_items_recursive( item_names, *content );
     }
 }
References item::all_known_contents(), item::color_in_inventory(), and item::tname().
Referenced by game::print_items_info().
butcher_submenu()
static void butcher_submenu (const std::vector< map_stack::iterator > & corpses, int index = -1) static
Definition at line 9448 of file game.cpp.
 {
     avatar &player_character = get_avatar();
     auto cut_time = [&]( butcher_type bt ) {
         int time_to_cut = 0;
         if( index != -1 ) {
             const mtype &corpse = *corpses[index]->get_mtype();
             const float factor = corpse.harvest->get_butchery_requirements().get_fastest_requirements(
                                      player_character.crafting_inventory(),
                                      corpse.size, bt ).first;
             time_to_cut = butcher_time_to_cut( player_character, *corpses[index], bt ) * factor;
         } else {
             for( const map_stack::iterator &it : corpses ) {
                 const mtype &corpse = *it->get_mtype();
                 const float factor = corpse.harvest->get_butchery_requirements().get_fastest_requirements(
                                          player_character.crafting_inventory(),
                                          corpse.size, bt ).first;
                 time_to_cut += butcher_time_to_cut( player_character, *it, bt ) * factor;
             }
         }
         return to_string_clipped( time_duration::from_moves( time_to_cut ) );
     };
     const bool enough_light = player_character.fine_detail_vision_mod() <= 4;
     const int factor = player_character.max_quality( qual_BUTCHER, PICKUP_RANGE );
     const std::string msgFactor = factor > INT_MIN
                                   ? string_format( _( "Your best tool has <color_cyan>%d butchering</color>." ), factor )
                                   :  _( "You have no butchering tool." );
     const int factorD = player_character.max_quality( qual_CUT_FINE, PICKUP_RANGE );
     const std::string msgFactorD = factorD > INT_MIN
                                    ? string_format( _( "Your best tool has <color_cyan>%d fine cutting</color>." ), factorD )
                                    :  _( "You have no fine cutting tool." );
     bool has_blood = false;
     bool has_skin = false;
     bool has_organs = false;
     std::string dissect_wp_hint; // dissection weakpoint proficiencies training hint
     int dissect_wp_hint_lines = 0; // track hint lines so menu width doesn't change
     if( index != -1 ) {
         const mtype *dead_mon = corpses[index]->get_mtype();
         if( dead_mon ) {
             for( const harvest_entry &entry : dead_mon->harvest.obj() ) {
                 if( entry.type == harvest_drop_skin && !corpses[index]->has_flag( flag_SKINNED ) ) {
                     has_skin = true;
                 }
                 if( entry.type == harvest_drop_offal && !( corpses[index]->has_flag( flag_QUARTERED ) ||
                         corpses[index]->has_flag( flag_FIELD_DRESS ) ||
                         corpses[index]->has_flag( flag_FIELD_DRESS_FAILED ) ) ) {
                     has_organs = true;
                 }
                 if( entry.type == harvest_drop_blood && dead_mon->bleed_rate > 0 &&
                     !( corpses[index]->has_flag( flag_QUARTERED ) ||
                        corpses[index]->has_flag( flag_FIELD_DRESS ) ||
                        corpses[index]->has_flag( flag_FIELD_DRESS_FAILED ) || corpses[index]->has_flag( flag_BLED ) ) ) {
                     has_blood = true;
                 }
             }
             if( !dead_mon->families.families.empty() ) {
                 dissect_wp_hint += std::string( "\n\n" ) + _( "Dissecting may yield knowledge of:" );
                 dissect_wp_hint_lines += 2;
                 for( const weakpoint_family &wf : dead_mon->families.families ) {
                     std::string prof_status;
                     if( !player_character.has_prof_prereqs( wf.proficiency ) ) {
                         prof_status += colorize( string_format( " (%s)", _( "missing proficiencies" ) ), c_red );
                     } else if( player_character.has_proficiency( wf.proficiency ) ) {
                         prof_status += colorize( string_format( " (%s)", _( "already known" ) ), c_dark_gray );
                     }
                     dissect_wp_hint += string_format( "\n  %s%s", wf.proficiency->name(), prof_status );
                     dissect_wp_hint_lines++;
                 }
             }
         }
     }
     uilist smenu;
     smenu.desc_enabled = true;
     smenu.desc_lines_hint += dissect_wp_hint_lines;
     smenu.text = _( "Choose type of butchery:" );
     const std::string cannot_see = colorize( _( "can't see!" ), c_red );
     smenu.addentry_col( static_cast<int>( butcher_type::QUICK ), enough_light,
                         'B', _( "Quick butchery" ),
                         enough_light ? cut_time( butcher_type::QUICK ) : cannot_see,
                         string_format( "%s  %s",
                                        _( "This technique is used when you are in a hurry, "
                                           "but still want to harvest something from the corpse. "
                                           " Yields are lower as you don't try to be precise, "
                                           "but it's useful if you don't want to set up a workshop.  "
                                           "Prevents zombies from raising." ),
                                        msgFactor ) );
     smenu.addentry_col( static_cast<int>( butcher_type::FULL ), enough_light,
                         'b', _( "Full butchery" ),
                         enough_light ? cut_time( butcher_type::FULL ) : cannot_see,
                         string_format( "%s  %s",
                                        _( "This technique is used to properly butcher a corpse, "
                                           "and requires a rope & a tree or a butchering rack, "
                                           "a flat surface (for ex. a table, a leather tarp, etc.) "
                                           "and good tools.  Yields are plentiful and varied, "
                                           "but it is time consuming." ),
                                        msgFactor ) );
     smenu.addentry_col( static_cast<int>( butcher_type::FIELD_DRESS ), enough_light && has_organs,
                         'f', _( "Field dress corpse" ),
                         enough_light ? ( has_organs ? cut_time( butcher_type::FIELD_DRESS ) :
                                          colorize( _( "has no organs" ), c_red ) ) : cannot_see,
                         string_format( "%s  %s",
                                        _( "Technique that involves removing internal organs and "
                                           "viscera to protect the corpse from rotting from inside.  "
                                           "Yields internal organs.  Carcass will be lighter and will "
                                           "stay fresh longer.  Can be combined with other methods for "
                                           "better effects." ),
                                        msgFactor ) );
     smenu.addentry_col( static_cast<int>( butcher_type::SKIN ), enough_light && has_skin,
                         's', _( "Skin corpse" ),
                         enough_light ? ( has_skin ? cut_time( butcher_type::SKIN ) : colorize( _( "has no skin" ),
                                          c_red ) ) : cannot_see,
                         string_format( "%s  %s",
                                        _( "Skinning a corpse is an involved and careful process that "
                                           "usually takes some time.  You need skill and an appropriately "
                                           "sharp and precise knife to do a good job.  Some corpses are "
                                           "too small to yield a full-sized hide and will instead produce "
                                           "scraps that can be used in other ways." ),
                                        msgFactor ) );
     smenu.addentry_col( static_cast<int>( butcher_type::BLEED ), enough_light && has_blood,
                         'l', _( "Bleed corpse" ),
                         enough_light ? ( has_blood ? cut_time( butcher_type::BLEED ) : colorize( _( "has no blood" ),
                                          c_red ) ) : cannot_see,
                         string_format( "%s  %s",
                                        _( "Bleeding involves severing the carotid arteries and jugular "
                                           "veins, or the blood vessels from which they arise.  "
                                           "You need skill and an appropriately sharp and precise knife "
                                           "to do a good job." ),
                                        msgFactor ) );
     smenu.addentry_col( static_cast<int>( butcher_type::QUARTER ), enough_light,
                         'k', _( "Quarter corpse" ),
                         enough_light ? cut_time( butcher_type::QUARTER ) : cannot_see,
                         string_format( "%s  %s",
                                        _( "By quartering a previously field dressed corpse you will "
                                           "acquire four parts with reduced weight and volume.  It "
                                           "may help in transporting large game.  This action destroys "
                                           "skin, hide, pelt, etc., so don't use it if you want to "
                                           "harvest them later." ),
                                        msgFactor ) );
     smenu.addentry_col( static_cast<int>( butcher_type::DISMEMBER ), true,
                         'm', _( "Dismember corpse" ),
                         cut_time( butcher_type::DISMEMBER ),
                         string_format( "%s  %s",
                                        _( "If you're aiming to just destroy a body outright and don't "
                                           "care about harvesting it, dismembering it will hack it apart "
                                           "in a very short amount of time but yields little to no usable flesh." ),
                                        msgFactor ) );
     smenu.addentry_col( static_cast<int>( butcher_type::DISSECT ), enough_light,
                         'd', _( "Dissect corpse" ),
                         enough_light ? cut_time( butcher_type::DISSECT ) : cannot_see,
                         string_format( "%s  %s%s",
                                        _( "By careful dissection of the corpse, you will examine it for "
                                           "possible bionic implants, or discrete organs and harvest them "
                                           "if possible.  Requires scalpel-grade cutting tools, ruins "
                                           "corpse, and consumes a lot of time.  Your medical knowledge "
                                           "is most useful here." ),
                                        msgFactorD, dissect_wp_hint ) );
     smenu.query();
     switch( smenu.ret ) {
         case static_cast<int>( butcher_type::QUICK ):
             player_character.assign_activity( ACT_BUTCHER, 0, true );
             break;
         case static_cast<int>( butcher_type::FULL ):
             player_character.assign_activity( ACT_BUTCHER_FULL, 0, true );
             break;
         case static_cast<int>( butcher_type::FIELD_DRESS ):
             player_character.assign_activity( ACT_FIELD_DRESS, 0, true );
             break;
         case static_cast<int>( butcher_type::SKIN ):
             player_character.assign_activity( ACT_SKIN, 0, true );
             break;
         case static_cast<int>( butcher_type::BLEED ) :
             player_character.assign_activity( ACT_BLEED, 0, true );
             break;
         case static_cast<int>( butcher_type::QUARTER ):
             player_character.assign_activity( ACT_QUARTER, 0, true );
             break;
         case static_cast<int>( butcher_type::DISMEMBER ):
             player_character.assign_activity( ACT_DISMEMBER, 0, true );
             break;
         case static_cast<int>( butcher_type::DISSECT ):
             player_character.assign_activity( ACT_DISSECT, 0, true );
             break;
         default:
             return;
     }
 }
References _, ACT_BLEED, ACT_BUTCHER, ACT_BUTCHER_FULL, ACT_DISMEMBER, ACT_DISSECT, ACT_FIELD_DRESS, ACT_QUARTER, ACT_SKIN, uilist::addentry_col(), Character::assign_activity(), BLEED, mtype::bleed_rate, butcher_time_to_cut(), c_dark_gray, c_red, colorize(), corpse, Character::crafting_inventory(), uilist::desc_enabled, uilist::desc_lines_hint, DISMEMBER, DISSECT, mtype::families, weakpoint_families::families, FIELD_DRESS, Character::fine_detail_vision_mod(), flag_BLED, flag_FIELD_DRESS, flag_FIELD_DRESS_FAILED, flag_QUARTERED, flag_SKINNED, time_duration::from_moves(), FULL, game::get_avatar, mtype::harvest, harvest_drop_blood, harvest_drop_offal, harvest_drop_skin, Character::has_prof_prereqs(), Character::has_proficiency(), Character::max_quality(), proficiency::name(), string_id< T >::obj(), PICKUP_RANGE, weakpoint_family::proficiency, qual_BUTCHER, qual_CUT_FINE, QUARTER, uilist::query(), QUICK, uilist::ret, SKIN, string_format(), uilist::text, and to_string_clipped().
Referenced by game::butcher().
can_place_monster()
static bool can_place_monster (const monster & mon, const tripoint & p) static
Definition at line 5169 of file game.cpp.
 {
     creature_tracker &creatures = get_creature_tracker();
     if( const monster *const critter = creatures.creature_at<monster>( p ) ) {
         // creature_tracker handles this. The hallucination monster will simply vanish
         if( !critter->is_hallucination() ) {
             return false;
         }
     }
     // Although monsters can sometimes exist on the same place as a Character (e.g. ridden horse),
     // it is usually wrong. So don't allow it.
     if( creatures.creature_at<Character>( p ) ) {
         return false;
     }
     return mon.will_move_to( p ) && mon.know_danger_at( p );
 }
References creature_tracker::creature_at(), game::get_creature_tracker, monster::know_danger_at(), and monster::will_move_to().
Referenced by choose_where_to_place_monster(), game::find_nearby_spawn_point(), and game::place_critter_around().
can_place_npc()
static bool can_place_npc (const tripoint & p) static
Definition at line 5186 of file game.cpp.
 {
     creature_tracker &creatures = get_creature_tracker();
     if( const monster *const critter = creatures.creature_at<monster>( p ) ) {
         // creature_tracker handles this. The hallucination monster will simply vanish
         if( !critter->is_hallucination() ) {
             return false;
         }
     }
     if( creatures.creature_at<Character>( p ) ) {
         return false;
     }
     return !g->is_dangerous_tile( p );
 }
References creature_tracker::creature_at(), g, and game::get_creature_tracker.
Referenced by game::find_nearby_spawn_point().
cancel_auto_move()
static bool cancel_auto_move (Character & you, const std::string & text) static
Definition at line 1441 of file game.cpp.
 {
     if( !you.has_destination() ) {
         return false;
     }
     g->invalidate_main_ui_adaptor();
     if( query_yn( _( "%s Cancel auto move?" ), text ) )  {
         add_msg( m_warning, _( "%s Auto move canceled." ), text );
         you.clear_destination();
         return true;
     }
     return false;
 }
References _, add_msg(), Character::clear_destination(), g, Character::has_destination(), m_warning, and query_yn().
Referenced by game::cancel_activity_or_ignore_query(), game::cancel_activity_query(), and game::portal_storm_query().
centerlistview()
static void centerlistview (const tripoint & active_item_position, int ui_width) static
Definition at line 8101 of file game.cpp.
 {
     Character &u = get_avatar();
     if( get_option<std::string>( "SHIFT_LIST_ITEM_VIEW" ) != "false" ) {
         u.view_offset.z = active_item_position.z;
         if( get_option<std::string>( "SHIFT_LIST_ITEM_VIEW" ) == "centered" ) {
             u.view_offset.x = active_item_position.x;
             u.view_offset.y = active_item_position.y;
         } else {
             point pos( active_item_position.xy() + point( POSX, POSY ) );
             // item/monster list UI is on the right, so get the difference between its width
             // and the width of the sidebar on the right (if any)
             int sidebar_right_adjusted = ui_width - panel_manager::get_manager().get_width_right();
             // if and only if that difference is greater than zero, use that as offset
             int right_offset = sidebar_right_adjusted > 0 ? sidebar_right_adjusted : 0;
             // Convert offset to tile counts, calculate adjusted terrain window width
             // This lets us account for possible differences in terrain width between
             // the normal sidebar and the list-all-whatever display.
             to_map_font_dim_width( right_offset );
             int terrain_width = TERRAIN_WINDOW_WIDTH - right_offset;
             if( pos.x < 0 ) {
                 u.view_offset.x = pos.x;
             } else if( pos.x >= terrain_width ) {
                 u.view_offset.x = pos.x - ( terrain_width - 1 );
             } else {
                 u.view_offset.x = 0;
             }
             if( pos.y < 0 ) {
                 u.view_offset.y = pos.y;
             } else if( pos.y >= TERRAIN_WINDOW_HEIGHT ) {
                 u.view_offset.y = pos.y - ( TERRAIN_WINDOW_HEIGHT - 1 );
             } else {
                 u.view_offset.y = 0;
             }
         }
     }
 }
References game::get_avatar, panel_manager::get_manager(), panel_manager::get_width_right(), math_opers::pos(), POSX, POSY, TERRAIN_WINDOW_HEIGHT, TERRAIN_WINDOW_WIDTH, to_map_font_dim_width(), game::u, Character::view_offset, tripoint::x, tripoint::xy(), tripoint::y, and tripoint::z.
Referenced by game::list_items(), and game::list_monsters().
check_encoding()
void check_encoding ()
Definition at line 571 of file ncurses_def.cpp.
 {
     // Check whether LC_CTYPE supports the UTF-8 encoding
     // and show a warning if it doesn't
     if( std::strcmp( nl_langinfo( CODESET ), "UTF-8" ) != 0 ) {
         // do not use ui_adaptor here to avoid re-entry
         int key = ERR;
         do {
             const char *unicode_error_msg =
                 _( "You don't seem to have a valid Unicode locale. You may see some weird "
                    "characters (e.g. empty boxes or question marks). You have been warned." );
             catacurses::erase();
             const int maxx = getmaxx( catacurses::stdscr );
             fold_and_print( catacurses::stdscr, point_zero, maxx, c_white, unicode_error_msg );
             catacurses::refresh();
             // do not use input_manager or input_context here to avoid re-entry
             key = getch();
         } while( key == KEY_RESIZE || key == KEY_MOUSE );
     }
 }
References _, c_white, catacurses::erase(), fold_and_print(), catacurses::getmaxx(), point_zero, catacurses::refresh(), and catacurses::stdscr.
Referenced by game_ui::init_ui().
check_items_newness()
static content_newness check_items_newness (const item * itm) static
return content_newness based on if item is known and nested items are known
Definition at line 8404 of file game.cpp.
 {
     if( !uistate.read_items.count( itm->typeId() ) ) {
         return content_newness::NEW;
     }
     return itm->get_contents().get_content_newness( uistate.read_items );
 }
References item_contents::get_content_newness(), item::get_contents(), NEW, uistatedata::read_items, item::typeId(), and uistate.
Referenced by game::list_items().
choose_where_to_place_monster()
static std::optional<tripoint> choose_where_to_place_monster (const monster & mon, const tripoint_range< tripoint > & range) static
Definition at line 5201 of file game.cpp.
 {
     return random_point( range, [&]( const tripoint & p ) {
         return can_place_monster( mon, p );
     } );
 }
References can_place_monster(), and random_point().
Referenced by game::place_critter_around(), and game::place_critter_within().
climb_affordance_menu_decode()
static bool climb_affordance_menu_decode (int retval, climbing_aid_id & aid_id) static
Definition at line 13442 of file game.cpp.
 {
     int_id< climbing_aid > as_int_id( retval - 0x1000 );
     if( as_int_id.is_valid() ) {
         aid_id = as_int_id.id();
         return true;
     }
     return false;
 }
References int_id< T >::id(), and int_id< T >::is_valid().
Referenced by game::climb_down_menu_pick().
climb_affordance_menu_encode()
static int climb_affordance_menu_encode (const climbing_aid_id & aid_id) static
Definition at line 13438 of file game.cpp.
 {
     return 0x1000 + int_id<climbing_aid>( aid_id ).to_i();
 }
References int_id< T >::to_i().
Referenced by game::climb_down_menu_gen().
create_trail_callback()
static shared_ptr_fast<game::draw_callback_t> create_trail_callback (const std::optional< tripoint > & trail_start, const std::optional< tripoint > & trail_end, const bool & trail_end_x) static
Definition at line 3898 of file game.cpp.
 {
     return make_shared_fast<game::draw_callback_t>(
     [&]() {
         if( trail_start && trail_end ) {
             draw_trail( trail_start.value(), trail_end.value(), trail_end_x );
         }
     } );
 }
References draw_trail().
Referenced by game::list_items(), and game::list_monsters().
create_zone_callback()
static shared_ptr_fast<game::draw_callback_t> create_zone_callback (const std::optional< tripoint > & zone_start, const std::optional< tripoint > & zone_end, const bool & zone_blink, const bool & zone_cursor, const bool & is_moving_zone = false) static
Definition at line 3849 of file game.cpp.
 {
     return make_shared_fast<game::draw_callback_t>(
     [&]() {
         if( zone_cursor ) {
             if( is_moving_zone ) {
                 g->draw_cursor( ( zone_start.value() + zone_end.value() ) / 2 );
             } else {
                 if( zone_end ) {
                     g->draw_cursor( zone_end.value() );
                 } else if( zone_start ) {
                     g->draw_cursor( zone_start.value() );
                 }
             }
         }
         if( zone_blink && zone_start && zone_end ) {
             avatar &player_character = get_avatar();
             const point offset2( player_character.view_offset.xy() +
                                  point( player_character.posx() - getmaxx( g->w_terrain ) / 2,
                                         player_character.posy() - getmaxy( g->w_terrain ) / 2 ) );
             tripoint offset;
 #if defined(TILES)
             if( use_tiles ) {
                 offset = tripoint_zero; //TILES
             } else {
 #endif
                 offset = tripoint( offset2, 0 ); //CURSES
 #if defined(TILES)
             }
 #endif
             const tripoint start( std::min( zone_start->x, zone_end->x ),
                                   std::min( zone_start->y, zone_end->y ),
                                   zone_end->z );
             const tripoint end( std::max( zone_start->x, zone_end->x ),
                                 std::max( zone_start->y, zone_end->y ),
                                 zone_end->z );
             g->draw_zones( start, end, offset );
         }
     } );
 }
References keycode::end, g, game::get_avatar, catacurses::getmaxx(), catacurses::getmaxy(), max(), min(), Creature::posx(), Creature::posy(), tripoint, tripoint_zero, use_tiles, Character::view_offset, and tripoint::xy().
Referenced by game::look_around(), and game::zones_manager().
draw_footsteps()
static void draw_footsteps (const catacurses::window & window, const tripoint & offset) static
Definition at line 3723 of file game.cpp.
 {
     for( const tripoint &footstep : sounds::get_footstep_markers() ) {
         char glyph = '?';
         if( footstep.z != offset.z ) { // Here z isn't an offset, but a coordinate
             glyph = footstep.z > offset.z ? '^' : 'v';
         }
         mvwputch( window, footstep.xy() + offset.xy(), c_yellow, glyph );
     }
 }
References c_yellow, sounds::get_footstep_markers(), mvwputch(), tripoint::xy(), and tripoint::z.
Referenced by game::draw_ter().
draw_trail()
void draw_trail (const tripoint & start, const tripoint & end, bool bDrawX) static
Definition at line 8065 of file game.cpp.
 {
     std::vector<tripoint> pts;
     avatar &player_character = get_avatar();
     tripoint center = player_character.pos() + player_character.view_offset;
     if( start != end ) {
         //Draw trail
         pts = line_to( start, end, 0, 0 );
     } else {
         //Draw point
         pts.emplace_back( start );
     }
     g->draw_line( end, center, pts );
     if( bDrawX ) {
         char sym = 'X';
         if( end.z > center.z ) {
             sym = '^';
         } else if( end.z < center.z ) {
             sym = 'v';
         }
         if( pts.empty() ) {
             mvwputch( g->w_terrain, point( POSX, POSY ), c_white, sym );
         } else {
             mvwputch( g->w_terrain, pts.back().xy() - player_character.view_offset.xy() +
                       point( POSX - player_character.posx(), POSY - player_character.posy() ),
                       c_white, sym );
         }
     }
 }
References c_white, center, keycode::end, g, game::get_avatar, line_to(), mvwputch(), Creature::pos(), Creature::posx(), POSX, Creature::posy(), POSY, Character::view_offset, and tripoint::xy().
Referenced by create_trail_callback(), and game::draw_trail_to_square().
ensure_term_size()
void ensure_term_size ()
Definition at line 536 of file ncurses_def.cpp.
 {
     // do not use ui_adaptor here to avoid re-entry
     const int minHeight = EVEN_MINIMUM_TERM_HEIGHT;
     const int minWidth = EVEN_MINIMUM_TERM_WIDTH;
     while( TERMY < minHeight || TERMX < minWidth ) {
         catacurses::erase();
         if( TERMY < minHeight && TERMX < minWidth ) {
             fold_and_print( catacurses::stdscr, point_zero, TERMX, c_white,
                             _( "Whoa!  Your terminal is tiny!  This game requires a minimum terminal size of "
                                "%dx%d to work properly.  %dx%d just won't do.  Maybe a smaller font would help?" ),
                             minWidth, minHeight, TERMX, TERMY );
         } else if( TERMX < minWidth ) {
             fold_and_print( catacurses::stdscr, point_zero, TERMX, c_white,
                             _( "Oh!  Hey, look at that.  Your terminal is just a little too narrow.  This game "
                                "requires a minimum terminal size of %dx%d to function.  It just won't work "
                                "with only %dx%d.  Can you stretch it out sideways a bit?" ),
                             minWidth, minHeight, TERMX, TERMY );
         } else {
             fold_and_print( catacurses::stdscr, point_zero, TERMX, c_white,
                             _( "Woah, woah, we're just a little short on space here.  The game requires a "
                                "minimum terminal size of %dx%d to run.  %dx%d isn't quite enough!  Can you "
                                "make the terminal just a smidgen taller?" ),
                             minWidth, minHeight, TERMX, TERMY );
         }
         catacurses::refresh();
         // do not use input_manager or input_context here to avoid re-entry
         getch();
         TERMY = getmaxy( catacurses::stdscr );
         TERMX = getmaxx( catacurses::stdscr );
     }
 }
References _, c_white, catacurses::erase(), EVEN_MINIMUM_TERM_HEIGHT, EVEN_MINIMUM_TERM_WIDTH, fold_and_print(), catacurses::getmaxx(), catacurses::getmaxy(), point_zero, catacurses::refresh(), catacurses::stdscr, TERMX, and TERMY.
Referenced by game_ui::init_ui().
favorite_ammo_or_select()
static item::reload_option favorite_ammo_or_select (avatar & u, item_location & loc, bool empty, bool prompt) static
Definition at line 9916 of file game.cpp.
 {
     if( u.ammo_location ) {
         std::vector<item::reload_option> ammo_list;
         if( u.list_ammo( loc, ammo_list, false ) ) {
             const auto is_favorite_and_compatible = [&loc, &u]( const item::reload_option & opt ) {
                 return opt.ammo == u.ammo_location && loc->can_reload_with( *u.ammo_location.get_item(), false );
             };
             auto it = std::find_if( ammo_list.begin(), ammo_list.end(), is_favorite_and_compatible );
             if( it != ammo_list.end() ) {
                 return *it;
             }
         }
     } else {
         const_cast<item_location &>( u.ammo_location ) = item_location();
     }
     return u.select_ammo( loc, prompt, empty );
 }
References item::reload_option::ammo, Character::ammo_location, item::can_reload_with(), item_location::get_item(), Character::list_ammo(), Pickup::prompt, avatar::select_ammo(), and game::u.
Referenced by game::reload().
find_empty_spot_nearby()
static std::optional<tripoint> find_empty_spot_nearby (const tripoint & pos) static
Definition at line 11947 of file game.cpp.
 {
     map &here = get_map();
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &p : here.points_in_radius( pos, 1 ) ) {
         if( p == pos ) {
             continue;
         }
         if( here.impassable( p ) ) {
             continue;
         }
         if( creatures.creature_at( p ) ) {
             continue;
         }
         return p;
     }
     return std::nullopt;
 }
References creature_tracker::creature_at(), game::get_creature_tracker, game::get_map, map::impassable(), map::points_in_radius(), and math_opers::pos().
Referenced by game::vertical_move().
generate_butcher_stack_display()
static std::vector<std::pair<map_stack::iterator, int> > generate_butcher_stack_display (const std::vector< map_stack::iterator > & its) static
Definition at line 9354 of file game.cpp.
 {
     std::vector<std::pair<map_stack::iterator, int>> result;
     std::vector<std::string> result_strings;
     result.reserve( its.size() );
     result_strings.reserve( its.size() );
     for( const map_stack::iterator &it : its ) {
         const std::string tname = it->tname();
         size_t s = 0;
         // Search for the index with a string equivalent to tname
         for( ; s < result_strings.size(); ++s ) {
             if( result_strings[s] == tname ) {
                 break;
             }
         }
         // If none is found, this is a unique tname so we need to add
         // the tname to string vector, and make an empty result pair.
         // Has the side effect of making 's' a valid index
         if( s == result_strings.size() ) {
             // make a new entry
             result.emplace_back( it, 0 );
             // Also push new entry string
             result_strings.push_back( tname );
         }
         result[s].second += it->count_by_charges() ? it->charges : 1;
     }
     return result;
 }
Referenced by game::butcher().
get_achievements()
achievements_tracker& get_achievements ()
Definition at line 13802 of file game.cpp.
 {
     return g->achievements();
 }
Referenced by achievement_attained(), debug_menu::debug(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_achievment(), debug_menu::unlock_all(), and memorial_logger::write_json_memorial().
get_avatar()
avatar& get_avatar ()
Definition at line 13817 of file game.cpp.
 {
     return g->u;
 }
Referenced by anonymous_namespace{item.cpp}::_stacks_clothing_size(), computer_session::action_complete_disable_external_power(), computer_session::action_emerg_ref_center(), advanced_inventory::action_examine(), advanced_inventory::action_move_item(), computer_session::action_repeater_mod(), Character::activate_bionic(), timed_event::actualize(), advanced_inventory_pane::add_items_from_area(), talker_npc::add_mission(), Character::add_traits(), construction::adjusted_time(), aim_activity_actor::aim_activity_actor(), map::apparent_light_helper(), jmapgen_remove_npcs::apply(), item::armor_full_protection_info(), inventory::assign_empty_invlet(), talk_function::assign_mission(), anonymous_namespace{monexamine.cpp}::attach_bag_to(), effect_on_conditions::avatar_death(), talk_function::basecamp_mission(), item::basic_info(), basic_item_filter(), best_installer(), debug_menu::bleed_self(), item::book_info(), vehicle::build_electronics_menu(), map::build_map_cache(), zone_manager::cache_avatar_location(), zone_manager::cache_data(), veh_interact::calc_lift_requirements(), disable_activity_actor::can_disable_or_reprogram(), can_interact_at(), overmap::can_place_special(), veh_interact::can_remove_part(), shopkeeper_item_group::can_sell(), move_furniture_activity_actor::canceled(), veh_interact::cant_do(), anonymous_namespace{item_tname.cpp}::category(), drawsq_params::center(), debug_menu::change_weather(), debug_menu::character_edit_desc_menu(), debug_menu::character_edit_menu(), check_deploy_square(), choose_adjacent_highlight(), basecamp_action_components::choose_components(), basecamp::choose_new_leader(), turn_handler::cleanup_at_end(), doors::close_door(), anonymous_namespace{item_tname.cpp}::clothing_size(), display::colorized_compass_legend_text(), complete_construction(), construction_menu(), basecamp_action_components::consume_components(), activity_handlers::consume_drink_menu_do_turn(), Character::consume_effects(), activity_handlers::consume_food_menu_do_turn(), activity_handlers::consume_meds_menu_do_turn(), avatar::control_npc(), debug_menu::control_npc_menu(), avatar::control_npc_menu(), create_advanced_inv(), creature_tracker::creature_at(), creature_select_menu(), debug_menu::damage_self(), debug_menu::debug(), debug_menu::debug_menu_game_state(), debug_menu::debug_menu_spawn_vehicle(), stats_tracker::deserialize(), map::detach_vehicle(), diary::diary(), spell_effect::directed_push(), Character::disassemble(), Character::dismount(), advanced_inventory::display(), faction_manager::display(), overmap_ui::display(), item::display_name(), veh_interact::do_install(), veh_interact::do_mend(), veh_interact::do_remove(), veh_interact::do_repair(), aim_activity_actor::do_turn(), editmap::do_ui_invalidation(), item::dps(), map::draw(), overmap_ui::draw_ascii(), anonymous_namespace{animation.cpp}::draw_bullet_curses(), mission_ui_impl::draw_controls(), explosion_handler::draw_custom_explosion(), anonymous_namespace{animation.cpp}::draw_custom_explosion_curses(), anonymous_namespace{animation.cpp}::draw_explosion_curses(), anonymous_namespace{animation.cpp}::draw_hit_player_curses(), anonymous_namespace{animation.cpp}::draw_line_curses(), map::draw_maptile(), mission_ui_impl::draw_mission_names(), overmap_ui::draw_om_sidebar(), anonymous_namespace{animation.cpp}::draw_sct_curses(), mission_ui_impl::draw_selected_description(), dummy_wgt_render(), dialogue::dynamic_line(), activity_handlers::eat_menu_do_turn(), editmap::edit(), debug_menu::mission_debug::edit_player(), eff_fun_fake_common_cold(), eff_fun_fake_flu(), map::emit_field(), trap::examine(), npc::execute_action(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_finish_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_active_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_take_control(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_take_control_menu(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_has_mission(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_monsters_in_direction(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_safe_mode_trigger(), mission::fail(), item::final_info(), Character::fine_detail_vision_mod(), consume_activity_actor::finish(), firstaid_activity_actor::finish(), fire(), iuse::fish_trap_tick(), anonymous_namespace{item_tname.cpp}::food_traits(), Character::forced_dismount(), map::furn_set(), iuse::geiger_active(), mapgen_basic_container::generate(), Character::get_active_moncams(), get_character_from_id(), get_compass_for_direction(), disable_activity_actor::get_disable_turns(), player_activity::get_distractions(), kill_tracker::get_kills_text(), map::get_known_connections(), get_memory_at(), talker_npc::get_topics(), weather_generator::get_weather_conditions(), talker_npc::give_item_to(), anonymous_namespace{monexamine.cpp}::give_items_to(), grab(), iuse::granade_act(), iuse::grenade_inc_act(), item::gun_info(), iuse::gun_repair(), handle_key_blocking_activity(), vehicle::handle_potential_theft(), haul_toggle(), game_menus::inv::holster(), pointmenu_cb::impl_t::impl_t(), debug_menu::import_folower(), learn_spell_actor::info(), advanced_inv_area::init(), tutorial_game::init(), exosuit_interact::insert_replace_activate_mod(), iexamine::intercom(), mission::is_complete(), read_inventory_preset::is_known(), debug_menu::kill_area(), Character::knock_back_to(), talk_function::lead_to_safety(), diary::load(), load_available_constructions(), main_menu::load_game(), aim_activity_actor::load_RAS_weapon(), anonymous_namespace{item_tname.cpp}::location_hint(), icg_entry::matches(), widget_clause::meets_condition(), map::memory_clear_vehicle_points(), vehicle::merge_appliance_into_grid(), monexamine::mfriend_menu(), iuse::molotov_lit(), anonymous_namespace{do_turn.cpp}::monmove(), Character::mount_creature(), avatar_action::move(), activity_handlers::move_cost(), pocket_favorite_callback::move_item(), iuse::multicooker(), iuse::multicooker_tick(), Character::needs_food(), main_menu::new_character_tab(), diary::new_page(), debug_menu::normalize_body(), memorial_logger::notify(), eoc_events::notify(), npc_select_menu(), effect_on_conditions::om_move(), mission::on_creature_death(), item::on_drop(), iexamine::on_smoke_out(), open(), open_movement_mode_menu(), main_menu::opening_screen(), orient_part(), anonymous_namespace{do_turn.cpp}::overmap_npc_move(), mission_type::parse_funcs(), map::partial_con_remove(), Character::perform_technique(), anonymous_namespace{monexamine.cpp}::pet_armor_loc(), monexamine::pet_menu(), photo_def_for_camera_point(), pick_usb(), overmap_special::place(), place_construction(), pldrive(), Character::pour_into(), effect_on_conditions::prevent_death(), item::process_fake_mill(), monster::process_one_effect(), effect_on_conditions::process_reactivate(), iuse::radiocontrol_tick(), rate_location(), read(), advanced_inventory::recalc_pane(), basecamp::recruit_return(), teleporter_callback::refresh(), iuse::remoteveh(), debug_menu::mission_debug::remove_mission(), map::remove_trap(), DefaultRemovePartHandler::removed(), aim_activity_actor::restore_view(), mission_start::reveal_refugee_center(), reveal_map_actor::reveal_targets(), target_ui::run(), pointmenu_cb::impl_t::select(), veh_interact::serialize_activity(), mission_util::set_assign_om_target(), debug_menu::set_automove(), advanced_inv_area::set_container_position(), debug_menu::show_sound(), sleep(), smash(), spell_effect::spawn_ethereal_item(), debug_menu::spawn_npc(), monster::speed_description(), diary::spell_changes(), Character::stagger(), diary::store(), anonymous_namespace{monexamine.cpp}::tack_loc(), takeoff(), map::ter_set(), item::tool_info(), npc_trading::trade(), ter_furn_transform::transform(), iexamine::translocator(), map::trap_set(), vehicle::turrets_aim(), aim_activity_actor::unload_RAS_weapon(), update_mapgen_function_json::update_map(), veh_interact::update_part_requirements(), computer_session::use(), inscribe_actor::use(), vehicle::use_dishwasher(), vehicle::use_monster_capture(), vehicle::use_washing_machine(), anonymous_namespace{item_tname.cpp}::vars(), debug_menu::vehicle_battery_charge(), debug_menu::vehicle_export(), map::vehicle_vehicle_collision(), wear(), main_menu::world_tab(), mission::wrap_up(), anonymous_namespace{debug_menu.cpp}::write_min_archive(), memorial_logger::write_text_memorial(), and pointmenu_cb::impl_t::~impl_t().
get_best_fire()
int get_best_fire (const tripoint & location)
Definition at line 1650 of file game.cpp.
 {
     int best_fire = 0;
     Character &player_character = get_player_character();
     map &here = get_map();
     // Convert it to an int id once, instead of 139 times per turn
     const field_type_id fd_fire_int = fd_fire.id();
     for( const tripoint &dest : here.points_in_radius( location, 6 ) ) {
         int heat_intensity = 0;
         maptile mt = here.maptile_at( dest );
         int ffire = maptile_field_intensity( mt, fd_fire_int );
         if( ffire > 0 ) {
             heat_intensity = ffire;
         } else  {
             heat_intensity = mt.get_ter()->heat_radiation;
         }
         if( heat_intensity == 0 ) {
             // No heat source here
             continue;
         }
         if( player_character.pos() == location ) {
             if( !here.clear_path( dest, location, -1, 1, 100 ) ) {
                 continue;
             }
         } else if( !here.sees( location, dest, -1 ) ) {
             continue;
         }
         if( square_dist( dest, location ) <= 1 ) {
             // Extend limbs/lean over a single adjacent fire to warm up
             best_fire = std::max( best_fire, heat_intensity );
         }
     }
     return best_fire;
 }
References map::clear_path(), fd_fire, get_map(), get_player_character(), maptile_impl< Submap >::get_ter(), map_data_common_t::heat_radiation, string_id< T >::id(), location, map::maptile_at(), maptile_field_intensity(), max(), map::points_in_radius(), Creature::pos(), map::sees(), and square_dist().
Referenced by Character::update_bodytemp().
get_convection_temperature()
units::temperature_delta get_convection_temperature (const tripoint & location)
Definition at line 1687 of file game.cpp.
 {
     units::temperature_delta temp_mod = units::from_kelvin_delta( 0 );
     map &here = get_map();
     // Directly on lava tiles
     units::temperature_delta lava_mod = here.tr_at( location ).has_flag(
                                             json_flag_CONVECTS_TEMPERATURE ) ?
                                         units::from_fahrenheit_delta( fd_fire->get_intensity_level().convection_temperature_mod ) :
                                         units::from_kelvin_delta( 0 );
     // Modifier from fields
     for( auto fd : here.field_at( location ) ) {
         // Nullify lava modifier when there is open fire
         if( fd.first.obj().has_fire ) {
             lava_mod = units::from_kelvin_delta( 0 );
         }
         temp_mod += units::from_fahrenheit_delta(
                         fd.second.get_intensity_level().convection_temperature_mod );
     }
     return temp_mod + lava_mod;
 }
References field_intensity_level::convection_temperature_mod, fd_fire, map::field_at(), units::from_fahrenheit_delta(), units::from_kelvin_delta(), field_type::get_intensity_level(), get_map(), trap::has_flag(), json_flag_CONVECTS_TEMPERATURE, location, and map::tr_at().
Referenced by weather_manager::get_temperature(), and item::process_temperature_rot().
get_creature_tracker()
creature_tracker& get_creature_tracker ()
Definition at line 13827 of file game.cpp.
 {
     return *g->critter_tracker;
 }
Referenced by target_ui::action_aim_and_shoot(), computer_session::action_terminate(), add_effect_to_target(), Character::adjacent_tile(), npc_attack_melee::all_evaluations(), npc_attack_gun::all_evaluations(), npc_attack_throw::all_evaluations(), npc::alt_attack(), jmapgen_setmap::apply(), monster::attack_at(), monster::attack_target(), spell_effect::banishment(), monster::bash_at(), mattack::breathe(), calculate_aim_cap(), mon_spellcasting_actor::call(), melee_actor::call(), iuse::camera(), computer_session::can_activate(), vehicle::can_close(), can_examine_at(), iuse::can_goo(), shearing_activity_actor::canceled(), iuse::capture_monster_act(), debug_menu::character_edit_menu(), character_push_effects(), spell_effect::charm_monster(), vehicle::autodrive_controller::check_drivable(), vehicle::check_heli_ascend(), vehicle::check_heli_descend(), clear_shot_reach(), doors::close_door(), map::collapse_at(), veh_interact::complete_vehicle(), item::contain_monster(), map::crush(), damage_targets(), spell_effect::dash(), monster::die(), spell_effect::directed_push(), map::displace_vehicle(), explosion_handler::do_blast(), milk_activity_actor::do_turn(), disable_activity_actor::do_turn(), stash_activity_actor::do_turn(), glide_activity_actor::do_turn(), editmap_hilight::draw(), anonymous_namespace{animation.cpp}::draw_line_curses(), editmap::draw_main_ui_overlay(), draw_throw_aim(), map::drop_furniture(), map::drop_items(), Character::echo_pulse(), editmap::edit(), eff_fun_teleglow(), spell_effect::effect_on_condition(), effects_description_for_creature(), iuse::emf_passive_on(), explosion_handler::emp_blast(), npc_attack_melee::evaluate(), npc_attack_gun::evaluate(), npc_attack_throw::evaluate(), npc_attack_spell::evaluate_tripoint(), npc_attack_gun::evaluate_tripoint(), npc_attack_throw::evaluate_tripoint(), iuse::extinguisher(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), climbing_aid::fall_scan::fall_scan(), field_processor_fd_electricity(), field_processor_fd_last_known(), field_processor_fd_push_items(), activity_handlers::fill_liquid_do_turn(), milk_activity_actor::finish(), shearing_activity_actor::finish(), chop_tree_activity_actor::finish(), disable_activity_actor::finish(), mattack::formblob(), fungal_effects::fungalize(), iuse::fungicide(), map::furn_set(), iuse::geiger(), map::get_creatures_in_radius(), vehicle::get_monster(), get_patient(), vehicle::get_riders(), iuse::granade_act(), monster::group_bash_skill(), mattack::growplants(), spell_effect::guilt(), npc::handle_sound(), Character::hardcoded_effects(), has_obstruction(), has_vine_parent(), spell::heal(), spell::ignore_by_species_id(), Character::impact(), npc::is_active(), spell::is_valid_target(), Character::knock_back_to(), monster::knock_back_to(), iexamine::ledge(), trapfunc::ledge(), target_ui::list_friendlies_in_lof(), Creature::longpull(), talk_function::loot_building(), iuse::mace(), spell_effect::mod_moves(), spell_effect::morale(), monster::move(), avatar_action::move(), veh_interact::move_cursor(), monster::move_effects(), monster::move_to(), npc::move_to(), mtrap_set(), spell_effect::mutate(), monster::nursebot_operate(), npc::on_load(), mattack::parrot_at_danger(), vehicle::part_collision(), iuse::petfood(), photo_def_for_camera_point(), monster::plan(), vehicle::precollision_check(), monster::process_effects(), monster::process_turn(), projectile_attack(), monster::push_to(), spell::random_valid_target(), Character::reach_attack(), spell_effect::recover_energy(), npc::regen_ai_cache(), spell_effect::remove_effect(), mattack::resurrect(), map::rotten_item_spawn(), route_best_workbench(), iexamine::rubble(), explosion_handler::scrambler_blast(), mattack::searchlight(), seen_critter(), lockpick_activity_actor::select_location(), target_ui::set_cursor_pos(), map::set_transparency_cache_dirty(), explosion_handler::shrapnel(), mattack::shriek_stun(), iexamine::shrub_wildveggies(), spell_effect::slime_split_on_death(), map::spawn_monsters_submap(), map::spawn_monsters_submap_group(), spawn_spores(), spell_move(), Character::stagger(), shearing_activity_actor::start(), disable_activity_actor::start(), monster::stumble(), swap_pos(), Target_attributes::Target_attributes(), spell::target_by_monster_id(), spell::target_by_species_id(), spell_effect::targeted_polymorph(), iuse::tazer(), teleport::teleport_to_point(), map::ter_set(), Character::throw_item(), teleporter_list::translocate(), mattack::triffid_heartbeat(), target_ui::try_reacquire_target(), Character::try_remove_grab(), editmap::uber_draw_ter(), map::unboard_vehicle(), editmap::update_view_with_help(), spell_effect::upgrade(), place_npc_iuse::use(), deploy_tent_actor::use(), npc_attack_melee::use(), vehicle::use_harness(), Character::valid_aoe_technique(), mattack::vine(), spell_effect::vomit(), suffer::while_grabbed(), npc::worker_downtime(), and mattack::zombie_fuse().
get_default_mode_input_context()
input_context get_default_mode_input_context ()
Definition at line 2455 of file game.cpp.
 {
     input_context ctxt( "DEFAULTMODE", keyboard_mode::keycode );
     // Because those keys move the character, they don't pan, as their original name says
     ctxt.set_iso( true );
     ctxt.register_action( "UP", to_translation( "Move north" ) );
     ctxt.register_action( "RIGHTUP", to_translation( "Move northeast" ) );
     ctxt.register_action( "RIGHT", to_translation( "Move east" ) );
     ctxt.register_action( "RIGHTDOWN", to_translation( "Move southeast" ) );
     ctxt.register_action( "DOWN", to_translation( "Move south" ) );
     ctxt.register_action( "LEFTDOWN", to_translation( "Move southwest" ) );
     ctxt.register_action( "LEFT", to_translation( "Move west" ) );
     ctxt.register_action( "LEFTUP", to_translation( "Move northwest" ) );
     ctxt.register_action( "pause" );
     ctxt.register_action( "LEVEL_DOWN", to_translation( "Descend stairs" ) );
     ctxt.register_action( "LEVEL_UP", to_translation( "Ascend stairs" ) );
     ctxt.register_action( "toggle_map_memory" );
     ctxt.register_action( "center" );
     ctxt.register_action( "shift_n" );
     ctxt.register_action( "shift_ne" );
     ctxt.register_action( "shift_e" );
     ctxt.register_action( "shift_se" );
     ctxt.register_action( "shift_s" );
     ctxt.register_action( "shift_sw" );
     ctxt.register_action( "shift_w" );
     ctxt.register_action( "shift_nw" );
     ctxt.register_action( "cycle_move" );
     ctxt.register_action( "cycle_move_reverse" );
     ctxt.register_action( "reset_move" );
     ctxt.register_action( "toggle_run" );
     ctxt.register_action( "toggle_crouch" );
     ctxt.register_action( "toggle_prone" );
     ctxt.register_action( "open_movement" );
     ctxt.register_action( "open" );
     ctxt.register_action( "close" );
     ctxt.register_action( "smash" );
     ctxt.register_action( "loot" );
     ctxt.register_action( "examine" );
     ctxt.register_action( "examine_and_pickup" );
     ctxt.register_action( "advinv" );
     ctxt.register_action( "pickup" );
     ctxt.register_action( "pickup_all" );
     ctxt.register_action( "grab" );
     ctxt.register_action( "haul" );
     ctxt.register_action( "haul_toggle" );
     ctxt.register_action( "butcher" );
     ctxt.register_action( "chat" );
     ctxt.register_action( "look" );
     ctxt.register_action( "peek" );
     ctxt.register_action( "listitems" );
     ctxt.register_action( "zones" );
     ctxt.register_action( "inventory" );
     ctxt.register_action( "compare" );
     ctxt.register_action( "organize" );
     ctxt.register_action( "apply" );
     ctxt.register_action( "apply_wielded" );
     ctxt.register_action( "wear" );
     ctxt.register_action( "take_off" );
     ctxt.register_action( "eat" );
     ctxt.register_action( "open_consume" );
     ctxt.register_action( "read" );
     ctxt.register_action( "wield" );
     ctxt.register_action( "pick_style" );
     ctxt.register_action( "reload_item" );
     ctxt.register_action( "reload_weapon" );
     ctxt.register_action( "reload_wielded" );
     ctxt.register_action( "insert" );
     ctxt.register_action( "unload" );
     ctxt.register_action( "throw" );
     ctxt.register_action( "fire" );
     ctxt.register_action( "cast_spell" );
     ctxt.register_action( "fire_burst" );
     ctxt.register_action( "select_fire_mode" );
     ctxt.register_action( "select_default_ammo" );
     ctxt.register_action( "drop" );
     ctxt.register_action( "unload_container" );
     ctxt.register_action( "drop_adj" );
     ctxt.register_action( "bionics" );
     ctxt.register_action( "mutations" );
     ctxt.register_action( "medical" );
     ctxt.register_action( "bodystatus" );
     ctxt.register_action( "sort_armor" );
     ctxt.register_action( "wait" );
     ctxt.register_action( "craft" );
     ctxt.register_action( "recraft" );
     ctxt.register_action( "long_craft" );
     ctxt.register_action( "construct" );
     ctxt.register_action( "disassemble" );
     ctxt.register_action( "sleep" );
     ctxt.register_action( "control_vehicle" );
     ctxt.register_action( "auto_travel_mode" );
     ctxt.register_action( "safemode" );
     ctxt.register_action( "autosafe" );
     ctxt.register_action( "autoattack" );
     ctxt.register_action( "ignore_enemy" );
     ctxt.register_action( "whitelist_enemy" );
     ctxt.register_action( "workout" );
     ctxt.register_action( "save" );
     ctxt.register_action( "quicksave" );
 #if !defined(RELEASE)
     ctxt.register_action( "quickload" );
 #endif
     ctxt.register_action( "SUICIDE" );
     ctxt.register_action( "player_data" );
     ctxt.register_action( "map" );
     ctxt.register_action( "sky" );
     ctxt.register_action( "missions" );
     ctxt.register_action( "factions" );
     ctxt.register_action( "morale" );
     ctxt.register_action( "messages" );
     ctxt.register_action( "help" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     ctxt.register_action( "open_options" );
     ctxt.register_action( "open_autopickup" );
     ctxt.register_action( "open_autonotes" );
     ctxt.register_action( "open_safemode" );
     ctxt.register_action( "open_distraction_manager" );
     ctxt.register_action( "open_color" );
     ctxt.register_action( "open_world_mods" );
     ctxt.register_action( "debug" );
     ctxt.register_action( "debug_scent" );
     ctxt.register_action( "debug_scent_type" );
     ctxt.register_action( "debug_temp" );
     ctxt.register_action( "debug_visibility" );
     ctxt.register_action( "debug_lighting" );
     ctxt.register_action( "debug_radiation" );
     ctxt.register_action( "debug_hour_timer" );
     ctxt.register_action( "debug_mode" );
     ctxt.register_action( "zoom_out" );
     ctxt.register_action( "zoom_in" );
 #if !defined(__ANDROID__) && !defined(EMSCRIPTEN)
     ctxt.register_action( "toggle_fullscreen" );
 #endif
     ctxt.register_action( "toggle_pixel_minimap" );
     ctxt.register_action( "toggle_panel_adm" );
     ctxt.register_action( "reload_tileset" );
     ctxt.register_action( "toggle_auto_features" );
     ctxt.register_action( "toggle_auto_pulp_butcher" );
     ctxt.register_action( "toggle_auto_mining" );
     ctxt.register_action( "toggle_auto_foraging" );
     ctxt.register_action( "toggle_auto_pickup" );
     ctxt.register_action( "toggle_thief_mode" );
     ctxt.register_action( "toggle_prevent_occlusion" );
     ctxt.register_action( "diary" );
     ctxt.register_action( "action_menu" );
     ctxt.register_action( "main_menu" );
     ctxt.register_action( "item_action_menu" );
     ctxt.register_action( "ANY_INPUT" );
     ctxt.register_action( "COORDINATE" );
     ctxt.register_action( "MOUSE_MOVE" );
     ctxt.register_action( "SELECT" );
     ctxt.register_action( "CLICK_AND_DRAG" );
     ctxt.register_action( "SEC_SELECT" );
     return ctxt;
 }
References keycode, input_context::register_action(), input_context::set_iso(), and to_translation().
Referenced by game::get_player_input(), handle_action_menu(), handle_key_blocking_activity(), handle_main_menu(), haul(), keys_bound_to(), main_menu::opening_screen(), press_x(), and press_x_if_bound().
get_event_bus()
event_bus& get_event_bus ()
Definition at line 13832 of file game.cpp.
 {
     return g->events();
 }
Referenced by achievement_attained(), achievement_failed(), computer_session::action_cascade(), computer_session::action_miss_disarm(), computer_session::action_portal(), computer_session::action_release(), computer_session::action_srcf_seal(), computer_session::action_terminate(), timed_event::actualize(), Character::add_addiction(), Creature::add_effect(), Character::apply_damage(), Character::bionics_install_failure(), activity_handlers::butcher_finish(), player_activity::canceled(), cast_spell(), spell::cast_spell_effect(), debug_menu::character_edit_menu(), Character::check_needs_extremes(), turn_handler::cleanup_at_end(), Character::consume(), avatar::control_npc(), debug_menu::debug(), mattack::dermatik(), stats_tracker::deserialize(), monster::die(), npc::die(), player_activity::do_turn(), construct::done_dig_grave(), construct::done_dig_grave_nospawn(), construct::done_digormine_stair(), construct::done_grave(), eat(), eff_fun_datura(), eff_fun_hypovolemia(), eff_fun_redcells_anemia(), eff_fun_teleglow(), npc::evaluate_best_attack(), vehicle::explode_fuel(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_trigger_event(), computer_session::failure_alarm(), Character::fall_asleep(), hacking_activity_actor::finish(), read_activity_actor::finish(), chop_tree_activity_actor::finish(), Character::fire_gun(), known_magic::forget_spell(), spell::gain_exp(), prying_activity_actor::handle_prying(), Character::hardcoded_effects(), Character::heal(), talk_function::hostile(), Character::hurtall(), known_magic::learn_spell(), main(), iuse::marloss(), marloss_common(), iuse::marloss_gel(), iuse::marloss_seed(), Character::melee_attack_abstract(), Character::mend(), iuse::mininuke(), Creature::mod_part_hp_cur(), Character::mutate_towards(), iuse::mycus(), read_activity_actor::npc_read(), vehicle::on_move(), iexamine::pedestal_wyrm(), Character::perform_install(), Character::perform_uninstall(), read_activity_actor::player_read(), Character::practice(), Character::practice_proficiency(), Creature::process_effects(), iuse::purify_smart(), avatar::read(), Character::rem_addiction(), Creature::remove_effect(), Character::remove_mutation(), Character::remove_weapon(), Creature::set_part_hp_cur(), known_magic::set_spell_exp(), known_magic::set_spell_level(), iuse::sewage(), smash(), activity_handlers::spellcasting_finish(), try_sleep_activity_actor::start(), player_activity::start_or_resume(), npc::starting_weapon(), teleport::teleport_to_point(), Character::test_crossing_threshold(), Character::throw_item(), Character::toggle_trait(), trap::trigger(), Character::unset_all_mutations(), Character::vomit(), Character::wake_up(), Character::wear(), outfit::wear_item(), npc::wield(), avatar::wield(), and Character::wield_contents().
get_fire_fuel_string()
static std::string get_fire_fuel_string (const tripoint & examp) static
Definition at line 6121 of file game.cpp.
 {
     map &here = get_map();
     if( here.has_flag( ter_furn_flag::TFLAG_FIRE_CONTAINER, examp ) ) {
         field_entry *fire = here.get_field( examp, fd_fire );
         if( fire ) {
             std::string ss;
             ss += _( "There is a fire here." );
             ss += " ";
             if( fire->get_field_intensity() > 1 ) {
                 ss += _( "It's too big and unpredictable to evaluate how long it will last." );
                 return ss;
             }
             time_duration fire_age = fire->get_field_age();
             // half-life inclusion
             int mod = 5 - get_player_character().get_skill_level( skill_survival );
             mod = std::max( mod, 0 );
             if( fire_age >= 0_turns ) {
                 if( mod >= 4 ) { // = survival level 0-1
                     ss += _( "It's going to go out soon without extra fuel." );
                     return ss;
                 } else {
                     fire_age = 30_minutes - fire_age;
                     if( to_string_approx( fire_age - fire_age * mod / 5 ) == to_string_approx(
                             fire_age + fire_age * mod / 5 ) ) {
                         ss += string_format(
                                   _( "Without extra fuel it might burn yet for maybe %s, but might also go out sooner." ),
                                   to_string_approx( fire_age - fire_age * mod / 5 ) );
                     } else {
                         ss += string_format(
                                   _( "Without extra fuel it might burn yet for between %s to %s, but might also go out sooner." ),
                                   to_string_approx( fire_age - fire_age * mod / 5 ),
                                   to_string_approx( fire_age + fire_age * mod / 5 ) );
                     }
                     return ss;
                 }
             } else {
                 fire_age = fire_age * -1 + 30_minutes;
                 if( mod >= 4 ) { // = survival level 0-1
                     if( fire_age <= 1_hours ) {
                         ss += _( "It's quite decent and looks like it'll burn for a bit without extra fuel." );
                         return ss;
                     } else if( fire_age <= 3_hours ) {
                         ss += _( "It looks solid, and will burn for a few hours without extra fuel." );
                         return ss;
                     } else {
                         ss += _( "It's very well supplied and even without extra fuel might burn for at least a part of a day." );
                         return ss;
                     }
                 } else {
                     if( to_string_approx( fire_age - fire_age * mod / 5 ) == to_string_approx(
                             fire_age + fire_age * mod / 5 ) ) {
                         ss += string_format( _( "Without extra fuel it will burn for %s." ),
                                              to_string_approx( fire_age - fire_age * mod / 5 ) );
                     } else {
                         ss += string_format( _( "Without extra fuel it will burn for between %s to %s." ),
                                              to_string_approx( fire_age - fire_age * mod / 5 ),
                                              to_string_approx( fire_age + fire_age * mod / 5 ) );
                     }
                     return ss;
                 }
             }
         }
     }
     return {};
 }
References _, fd_fire, fire(), map::get_field(), game::get_map, game::get_player_character, Character::get_skill_level(), map::has_flag(), max(), skill_survival, string_format(), TFLAG_FIRE_CONTAINER, and to_string_approx().
Referenced by game::examine(), and game::print_fields_info().
get_globals()
global_variables& get_globals ()
Definition at line 13871 of file game.cpp.
 {
     return g->global_variables_instance;
 }
Referenced by basecamp::choose_new_leader(), debug_menu::edit_global_vars(), Creature::load(), global_variables::load_migrations(), maybe_read_var_value(), parse_tags(), set_queued_points(), debug_menu::write_global_vars(), and write_var_value().
get_heat_radiation()
units::temperature_delta get_heat_radiation (const tripoint & location)
Definition at line 1614 of file game.cpp.
 {
     units::temperature_delta temp_mod = units::from_kelvin_delta( 0 );
     Character &player_character = get_player_character();
     map &here = get_map();
     // Convert it to an int id once, instead of 139 times per turn
     const field_type_id fd_fire_int = fd_fire.id();
     for( const tripoint &dest : here.points_in_radius( location, 6 ) ) {
         int heat_intensity = 0;
         maptile mt = here.maptile_at( dest );
         int ffire = maptile_field_intensity( mt, fd_fire_int );
         if( ffire > 0 ) {
             heat_intensity = ffire;
         } else  {
             heat_intensity = mt.get_ter()->heat_radiation;
         }
         if( heat_intensity == 0 ) {
             // No heat source here
             continue;
         }
         if( player_character.pos() == location ) {
             if( !here.clear_path( dest, location, -1, 1, 100 ) ) {
                 continue;
             }
         } else if( !here.sees( location, dest, -1 ) ) {
             continue;
         }
         // Ensure fire_dist >= 1 to avoid divide-by-zero errors.
         const int fire_dist = std::max( 1, square_dist( dest, location ) );
         temp_mod += units::from_fahrenheit_delta( 6.f * heat_intensity * heat_intensity / fire_dist );
     }
     return temp_mod;
 }
References map::clear_path(), fd_fire, units::from_fahrenheit_delta(), units::from_kelvin_delta(), get_map(), get_player_character(), maptile_impl< Submap >::get_ter(), map_data_common_t::heat_radiation, string_id< T >::id(), location, map::maptile_at(), maptile_field_intensity(), max(), map::points_in_radius(), Creature::pos(), map::sees(), and square_dist().
Referenced by weather_manager::get_temperature(), item::process_temperature_rot(), and Character::update_bodytemp().
get_initial_hotkey()
static std::optional<input_event> get_initial_hotkey (const size_t menu_index) static
Definition at line 9342 of file game.cpp.
 {
     return menu_index == 0
            ? hotkey_for_action( ACTION_BUTCHER, /*maximum_modifier_count=*/1 )
            : std::nullopt;
 }
References ACTION_BUTCHER, and hotkey_for_action().
Referenced by add_corpses(), add_disassemblables(), and add_salvagables().
get_map()
map& get_map ()
Definition at line 13822 of file game.cpp.
 {
     return g->m;
 }
Referenced by anonymous_namespace{iexamine.cpp}::_choose_elevator_destz(), anonymous_namespace{iexamine.cpp}::_get_vehicles_on_elevator(), explosion_handler::_make_explosion(), anonymous_namespace{item.cpp}::_stacks_location_hint(), basecamp::abandon_camp(), Character::absorb_hit(), mattack::absorb_items(), mattack::absorb_meat(), mattack::acid(), mattack::acid_barf(), iuse::acidbomb_act(), vehicle::act_on_map(), computer_session::action_amigara_log(), computer_session::action_blood_anal(), computer_session::action_cascade(), computer_session::action_close_gate(), computer_session::action_conveyor(), computer_session::action_data_anal(), computer_session::action_deactivate_shock_vent(), computer_session::action_elevator_on(), computer_session::action_extract_rad_source(), computer_session::action_geiger(), computer_session::action_irradiator(), computer_session::action_list_bionics(), computer_session::action_lock(), computer_session::action_miss_launch(), computer_session::action_open(), computer_session::action_open_gate(), computer_session::action_portal(), computer_session::action_release(), computer_session::action_release_bionics(), computer_session::action_research(), computer_session::action_sample(), computer_session::action_shutters(), computer_session::action_srcf_elevator(), computer_session::action_srcf_seal(), computer_session::action_terminate(), computer_session::action_unlock(), Character::activate_bionic(), Character::activate_mutation(), enchant_cache::activate_passive(), activity_on_turn_move_loot(), timed_event::actualize(), zone_manager::add(), inventory_selector::add_basecamp_items(), add_basecamp_storage_to_loot_zone_list(), add_fallback_zone(), map::add_field(), map::add_item(), DefaultRemovePartHandler::add_item_or_charges(), advanced_inventory_pane::add_items_from_area(), Character::add_known_trap(), inventory_selector::add_map_items(), construct::add_matching_down_above(), inventory_selector::add_nearby_items(), construct::add_roof(), spell_effect::add_trap(), inventory_selector::add_vehicle_items(), map::add_vehicle_to_map(), behavior::monster_oracle_t::adjacent_plants(), Character::adjacent_tile(), vehicle::advance_precalc_mounts(), iuse::afs_translocator(), iexamine::aggie_plant(), anonymous_namespace{activity_item_handling.cpp}::already_done(), npc::alt_attack(), item::ammo_consume(), item_contents::ammo_consume(), item::ammo_remaining(), jmapgen_remove_npcs::apply(), jmapgen_npc::apply(), jmapgen_vehicle::apply(), jmapgen_remove_vehicles::apply(), jmapgen_remove_all::apply(), cardreader_examine_actor::apply(), apply< furn_t >(), apply< ter_t >(), apply< trap >(), apply_ammo_effects(), iexamine::arcfurnace_empty(), iexamine::arcfurnace_full(), are_requirements_nearby(), npc::assess_danger(), assign_veh_to_follow(), Creature::attack_air(), monster::attack_at(), Creature::auto_find_hostile_target(), iexamine::autoclave_empty(), iexamine::autoclave_full(), iexamine::autodoc(), Pickup::autopickup(), vehicle::autopilot_patrol(), iexamine::bars(), Character::base_comfort_value(), spell_effect::bash(), monster::bash_at(), trapfunc::beartrap(), mattack::bio_op_disarm(), Character::bionics_install_failure(), Creature::bleed(), iuse::blood_draw(), Character::blossoms(), iuse::boltcutters(), trapfunc::boobytrap(), mattack::boomer(), mattack::boomer_glow(), vehicle::break_off(), iuse::break_stick(), mattack::breathe(), mdeath::broken(), mattack::browse(), trapfunc::bubble(), activity_handlers::build_do_turn(), vehicle::build_interact_menu(), iexamine::bulletin_board(), Character::burn_fuel(), Character::burn_move_stamina(), butcher_corpse_activity(), butcher_dissect_item(), activity_handlers::butcher_finish(), butchery_drops_harvest(), butchery_quarter(), zone_manager::cache_vzones(), monster::calc_climb_cost(), monster::calc_movecost(), calculate_spell_effect_area(), appliance_convert_examine_actor::call(), cardreader_examine_actor::call(), eoc_examine_actor::call(), leap_actor::call(), melee_actor::call(), gun_actor::call(), iuse::call_of_tindalos(), trapfunc::caltrops_glass(), iuse::camera(), computer_session::can_activate(), can_butcher_at(), can_construct(), can_do_activity_there(), can_examine_at(), iexamine::can_fertilize(), iuse::can_goo(), can_interact_at(), Character::can_mount(), npc::can_move_to(), can_move_vertical_at(), npc::can_open_door(), can_pickup_at(), monster::can_reach_to(), can_recharge_lunar(), can_recharge_solar(), vehicle::can_use_rails(), cancel_pickup(), tent_placement_activity_actor::canceled(), vehicle_unfolding_activity_actor::canceled(), iexamine::cardreader_foodplace(), iexamine::cardreader_robofac(), trapfunc::cast_spell(), Character::cast_spell(), iexamine::chainfence(), advanced_inventory::change_square(), character_push_effects(), construct::check_channel(), construct::check_deconstruct(), check_deploy_square(), construct::check_down_OK(), vehicle::autodrive_controller::check_drivable(), Character::check_eligible_containers_for_crafting(), construct::check_empty(), construct::check_empty_lite(), vehicle::check_falling_or_floating(), vehicle::check_heli_ascend(), vehicle::check_heli_descend(), deploy_tent_actor::check_intact(), vehicle::check_is_heli_landed(), construct::check_matching_down_above(), mattack::check_money_left(), construct::check_no_trap(), construct::check_no_wiring(), construct::check_nofloor_above(), Character::check_outbounds_activity(), construct::check_ramp_high(), Character::check_read_condition(), construct::check_single_support(), construct::check_stable(), construct::check_support(), construct::check_support_below(), construct::check_up_OK(), choose_adjacent_highlight(), target_ui::choose_initial_target(), iuse::chop_logs(), chop_plank_activity(), chop_single_do_turn(), iuse::chop_tree(), chop_tree_activity(), cleanup_tiles(), mapbuffer::clear_outside_reality_bubble(), iexamine::clear_overgrown(), clear_shot_reach(), Character::climate_control_strength(), Character::climbing_cost(), close(), vehicle::collision(), colorized_feature_description_at(), colorized_field_description_at(), display::colorized_overmap_text(), colorized_ter_name_flags_at(), colorized_trap_name_at(), talk_function::companion_return(), complete_construction(), veh_interact::complete_vehicle(), iexamine::compost_empty(), iexamine::compost_full(), compost_set_empty(), compost_set_full(), vehicle::autodrive_controller::compute_obstacles(), vehicle::connect(), construction_activity(), Character::consume_charges(), Character::consume_items(), consume_items_in_zones(), Character::consume_tools(), Character::consume_ups(), craft_command::continue_prompt_liquids(), iexamine::controls_gate(), npc::could_move_onto(), vehicle::crash_terrain_around(), spell::create_field(), fungal_effects::create_spores(), zone_manager::create_vehicle_loot_zone(), creature_tracker::creature_at(), trapfunc::crossbow(), iuse::crowbar(), Character::crush_frozen_liquid(), iexamine::curtains(), iuse::cut_log_into_planks(), salvage_actor::cut_up(), cyborg_on_couch(), cycle_action(), vehicle::damage_all(), vehicle::damage_direct(), damage_targets(), spell_effect::dash(), iuse::dbg_lux_meter(), debug_menu::debug(), debug_menu::debug_menu_game_state(), debug_menu::debug_menu_spawn_vehicle(), vehicle::decrement_summon_timer(), mattack::depart(), iexamine::deployed_furniture(), item_location::impl::item_on_map::describe(), item_location::deserialize(), climbing_aid::detect_conditions(), monster::die(), npc::die(), dig_tool(), spell_effect::directed_push(), iuse::directional_antenna(), iexamine::dirtmound(), avatar::disarm(), Character::disassemble_all(), displace_items_except_one_liquid(), overmap_ui::display(), veh_interact::display_veh(), basecamp::distribute_food(), distribute_items_to_npc_zones(), explosion_handler::do_blast(), vehicle::do_engine_damage(), vehicle::do_environmental_effects(), melee_actor::do_grab(), vehicle::do_remove_part_actual(), vehicle::do_towing_move(), hotwire_car_activity_actor::do_turn(), milk_activity_actor::do_turn(), hacksaw_activity_actor::do_turn(), aim_activity_actor::do_turn(), move_items_activity_actor::do_turn(), glide_activity_actor::do_turn(), unload_loot_activity_actor::do_turn(), construct::do_turn_shovel(), mattack::dogthing(), construct::done_appliance(), construct::done_deconstruct(), construct::done_dig_grave(), construct::done_dig_grave_nospawn(), construct::done_digormine_stair(), construct::done_extract_maybe_revert_to_dirt(), construct::done_grave(), construct::done_mark_firewood(), construct::done_mark_practice_target(), construct::done_mine_upstair(), construct::done_ramp_high(), construct::done_ramp_low(), construct::done_vehicle(), construct::done_window_curtains(), construct::done_wiring(), construct::done_wood_stairs(), iexamine::door_peephole(), mattack::doot(), editmap_hilight::draw(), anonymous_namespace{animation.cpp}::draw_line_curses(), editmap::draw_main_ui_overlay(), advanced_inventory::draw_minimap(), overmap_ui::draw_om_sidebar(), overmap_ui::draw_overmap_chunk(), target_ui::draw_terrain_overlay(), draw_throw_aim(), vehicle::drive_to_local_target(), Character::drop(), Character::drop_invalid_inventory(), monster::drop_items_on_death(), drop_on_map(), drop_or_embed_projectile(), talk_function::drop_stolen_item(), talk_function::drop_weapon(), anonymous_namespace{monexamine.cpp}::dump_items(), mattack::eat_carrion(), mattack::eat_crop(), mattack::eat_food(), avatar_action::eat_here(), Character::echo_pulse(), editmap::edit_fld(), editmap::edit_itm(), editmap::edit_mapgen(), eff_fun_fungus(), eff_fun_sleep(), eff_fun_teleglow(), iuse::ehandcuffs_tick(), iexamine::elevator(), iuse::emf_passive_on(), spell_effect::emit(), explosion_handler::emp_blast(), empty_autopickup_target(), enumerate_objects_around_point(), Character::env_surgery_bonus(), Character::evaluate_techniques(), trap::examine(), npc::execute_action(), explosion_handler::explosion(), iuse::extinguisher(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate(), conditional_fun::anonymous_namespace{condition.cpp}::f_can_see_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_driving(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_in_field(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_on_terrain(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_on_terrain_with_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_underwater(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_id(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_with_flag(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), computer_session::failure_amigara(), computer_session::failure_destroy_blood(), computer_session::failure_destroy_data(), computer_session::failure_manhacks(), computer_session::failure_pump_explode(), computer_session::failure_pump_leak(), computer_session::failure_secubots(), computer_session::failure_shutdown(), climbing_aid::fall_scan::fall_scan(), iexamine::false_and_debugmsg(), farm_action(), feature< furn_id >(), feature< ter_id >(), feature< trap_id >(), iexamine::fertilize_plant(), fetch_activity(), anonymous_namespace{math_parser_diag.cpp}::field_strength_eval(), fill_funnels(), activity_handlers::fill_liquid_do_turn(), find_best_fire(), find_closest_stair(), npc::find_corpse_to_pulp(), npc::find_dangerous_explosives(), find_empty_neighbors(), npc::find_item(), find_refuel_spot_zone(), melee_actor::find_target(), vehicle::find_vehicle(), vehicle::find_vehicles_to_rack(), Character::fine_detail_vision_mod(), bikerack_racking_activity_actor::finish(), bikerack_unracking_activity_actor::finish(), tent_deconstruct_activity_actor::finish(), tent_placement_activity_actor::finish(), hacksaw_activity_actor::finish(), hacking_activity_actor::finish(), hotwire_car_activity_actor::finish(), boltcutting_activity_actor::finish(), lockpick_activity_actor::finish(), safecracking_activity_actor::finish(), harvest_activity_actor::finish(), reload_activity_actor::finish(), milk_activity_actor::finish(), shearing_activity_actor::finish(), oxytorch_activity_actor::finish(), chop_logs_activity_actor::finish(), chop_planks_activity_actor::finish(), chop_tree_activity_actor::finish(), churn_activity_actor::finish(), clear_rubble_activity_actor::finish(), disable_activity_actor::finish(), forage_activity_actor::finish(), longsalvage_activity_actor::finish(), mop_activity_actor::finish(), iexamine::finite_water_source(), fire(), Character::fire_gun(), iexamine::fireplace(), iuse::fish_trap(), iuse::fish_trap_tick(), iuse::fishing_rod(), mattack::flame(), explosion_handler::flashbang(), mattack::flesh_tendril(), creature_tracker::flood_fill_zone(), Character::floor_bedding_warmth(), Character::floor_item_warmth(), iexamine::flower_cactus(), iexamine::flower_dahlia(), iexamine::flower_marloss(), iexamine::flower_poppy(), foamcrete_build(), vehicle_folding_activity_actor::fold_vehicle(), npc::follow_distance(), Character::forced_dismount(), basecamp::form_crafting_inventory(), inventory::form_from_map(), form_loc(), basecamp::form_storage_zones(), advanced_inventory_pane::free_volume(), suffer::from_artifact_resonance(), suffer::from_asthma(), suffer::from_nyctophobia(), suffer::from_other_mutations(), suffer::from_radiation(), fromPumpFuel(), iexamine::fswitch(), vehicle::fuel_left(), iuse::fungicide(), iexamine::fungus(), mattack::fungus(), mattack::fungus_big_blossom(), mattack::fungus_corporate(), mattack::fungus_fortify(), mattack::fungus_haze(), mattack::fungus_sprout(), iexamine::fvat_empty(), iexamine::fvat_full(), fvat_set_empty(), fvat_set_full(), iuse::gasmask(), iexamine::gaspump(), iuse::geiger(), iuse::geiger_active(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), generic_multi_activity_handler(), generic_multi_activity_locations(), get_auto_consume_moves(), get_basecamp(), get_best_fire(), zone_manager::get_bottom_zone(), Character::get_cable_vehicle(), basecamp::get_camp_map(), cardreader_examine_actor::get_cards(), get_convection_temperature(), input_context::get_coordinates(), Character::get_crafting_group(), Character::get_crafting_helpers(), comestible_inventory_preset::get_denial(), Character::get_eligible_containers_for_crafting(), anonymous_namespace{gates.cpp}::get_gate_id(), get_get_str_(), get_hack_type(), get_heat_radiation(), advanced_inv_area::get_item_count(), get_item_location(), get_keg_capacity(), liquid_handler::get_liquid_target(), get_local_windpower(), DefaultRemovePartHandler::get_map_ref(), get_memory_at(), zone_manager::get_near_zones(), overmap_ui::get_overmap_path_to(), monster::get_path_avoid(), npc::get_path_avoid(), zone_manager::get_point_set_loot(), player_activity::get_progress_message(), vehicle::get_remote_part(), Character::get_targetable_creatures(), weather_manager::get_temperature(), get_top_item_at_point(), get_tripoint_from_var(), scent_map::get_unsafe(), zone_manager::get_zone_at(), get_zone_for_act(), zone_manager::get_zones(), zone_manager::get_zones_at(), iexamine::getGasPumpByNumber(), iexamine::getNearFilledGasTank(), getNearPumpCount(), trapfunc::glass(), talker_furniture::global_pos(), talker_item_const::global_pos(), vehicle::global_square_location(), npc::go_to_omt_destination(), trapfunc::goo(), npc::good_escape_direction(), good_fishing_spot(), grab(), avatar::grab(), iuse::granade_act(), Character::gravity_check(), mattack::graze(), iuse::grenade_inc_act(), mattack::growplants(), iuse::hacksaw(), handbrake(), handle_action_menu(), Character::handle_contents_changed(), iuse::handle_ground_graffiti(), Character::handle_gun_overheat(), iexamine_helper::handle_harvest(), liquid_handler::handle_liquid_from_ground(), Character::handle_melee_wear(), prying_activity_actor::handle_prying(), prying_activity_actor::handle_prying_nails(), npc::handle_sound(), vehicle::handle_trap(), handle_weather_effects(), vehicle::handling_difficulty(), Character::hardcoded_effects(), iexamine::harvest_plant(), iexamine::harvest_plant_ex(), iexamine::harvestable_now(), Character::has_alarm_clock(), has_clear_path_to_pickup_items(), Character::has_destination_activity(), Character::has_fire(), has_neighbor(), has_obstruction(), has_pre_terrain(), has_vehicle_control(), has_vine_parent(), Character::has_watch(), haul(), monster::hear_sound(), Character::heat_emission(), iuse::heat_food(), heat_item(), iuse::honeycomb(), Character::i_add(), Character::i_add_or_drop(), Character::i_add_or_fill(), Character::i_drop_at(), vehicle::idle(), vehicle::immediate_path(), Character::impact(), monster::impact(), in_spell_aoe(), scent_map::inbounds(), talk_function::individual_mission(), advanced_inv_area::init(), weldrig_hack::init(), exosuit_interact::insert_replace_activate_mod(), vehicle::interact_with(), iexamine::invalid(), vehicle::invalidate_towing(), item::io(), Creature::is_adjacent(), place_trap_actor::is_allowed(), monster::is_aquatic_danger(), mission::is_complete(), is_creature_outside(), Character::is_deaf(), Character::is_driving(), vehicle::is_external_part(), Creature::is_likely_underwater(), is_obstacle(), pickup_inventory_preset::is_shown(), select_ammo_inventory_preset::is_shown(), Character::is_snuggling(), is_solid_neighbor(), anonymous_namespace{gates.cpp}::gate_data::is_suitable_wall(), ma_requirements::is_valid_character(), is_wind_blocker(), behavior::monster_oracle_t::items_available(), activity_handlers::jackhammer_do_turn(), activity_handlers::jackhammer_finish(), mattack::kamikaze(), iexamine::keg(), debug_menu::kill_area(), iexamine::kiln_empty(), iexamine::kiln_full(), Character::knock_back_to(), monster::knock_back_to(), monster::know_danger_at(), Character::knows_trap(), trapfunc::landmine(), trapfunc::lava(), vehicle::leak_fuel(), Character::leak_items(), iexamine::ledge(), trapfunc::ledge(), vehicle::level_vehicle(), link_up_actor::link_extend_cable(), item::link_to(), link_up_actor::link_to_veh_app(), link_up_actor::link_tow_cable(), avatar::load(), monster::load(), map::load(), avatar::load_map_memory(), advanced_inventory_pane::load_settings(), map::loadn(), anonymous_namespace{item_tname.cpp}::location_hint(), iexamine::locked_object(), iexamine::locked_object_pickable(), Creature::longpull(), iuse::lumber(), iuse::mace(), item_location::make_active(), map::make_active(), make_mon_corpse(), iuse::makemound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::map_add_item(), debug_menu::map_extra(), trapfunc::map_regen(), map_selector::map_selector(), editmap::mapgen_preview(), editmap::mapgen_retarget(), editmap::mapgen_veh_destroy(), marloss_common(), fungal_effects::marlossify(), vehicle::merge_appliance_into_grid(), vehicle::merge_rackable_vehicle(), vehicle::merge_vehicle_parts(), iuse::meth(), anonymous_namespace{monexamine.cpp}::milk_source(), mill_activate(), iexamine::mill_finalize(), mill_load_food(), mine_activity(), Character::modify_morale(), iuse::molotov_lit(), anonymous_namespace{do_turn.cpp}::monmove(), monster::monster_move_in_vehicle(), iuse::mop(), mop_activity(), monster::move(), npc::move(), avatar_action::move(), npc::move_away_from(), activity_handlers::move_cost(), veh_interact::move_cursor(), monster::move_effects(), Character::move_in_vehicle(), move_item(), monster::move_to(), npc::move_to(), move_to_parent_pocket_recursive(), firestarter_actor::moves_cost_by_fuel(), multicooker_hallu(), iuse::mycus(), iexamine::nanofab(), nearest_passable(), vehicle::no_towing_slack(), iexamine::none(), npc::npc_dismount(), mattack::nurse_assist(), mattack::nurse_check_up(), mattack::nurse_operate(), monster::nursebot_operate(), item::on_drop(), Character::on_hit(), monster::on_hit(), npc::on_load(), Character::on_move(), iexamine::on_smoke_out(), open(), gates::open_gate(), vehicle::open_or_close(), iexamine::open_safe(), vehicle::operate_planter(), vehicle::operate_reaper(), vehicle::operate_scoop(), activity_handlers::operation_do_turn(), activity_handlers::operation_finish(), operator_present(), Character::overmap_sight_range(), iuse::oxytorch(), parse_tags(), vehicle::part_collision(), iexamine::part_con(), vehicle::part_removal_cleanup(), Character::pause(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), timed_event::per_turn(), tutorial_game::per_turn(), Character::perform_install(), liquid_handler::perform_liquid_transfer(), Character::perform_technique(), Character::perform_uninstall(), perform_zone_activity_turn(), photo_def_for_camera_point(), iuse::pick_lock(), pick_plant(), npc::pick_up_item(), npc::pick_up_item_map(), activity_handlers::pickaxe_do_turn(), activity_handlers::pickaxe_finish(), pickveh(), iexamine::pit(), iexamine::pit_covered(), pit_effectiveness(), trapfunc::pit_glass(), trapfunc::pit_spikes(), map::pl_sees(), place_and_add_as_known(), place_appliance(), place_construction(), Character::place_corpse(), place_craft_or_disassembly(), start_location::place_player(), monster::plan(), mattack::plant(), iexamine::plant_seed(), activity_handlers::plant_seed_finish(), vehicle::player_in_control(), player_on_couch(), pldrive(), points_for_gas_cloud(), veh_app_interact::populate_app_actions(), iexamine::portable_structure(), iuse::portal(), Creature::pos(), map_cursor::pos(), Creature::pos_bub(), iexamine::pour_into_keg(), vehicle::precalculate_vehicle_turning(), firestarter_actor::prep_firestarter_use(), advanced_inventory::print_items(), Character::process_effects(), monster::process_effects(), explosion_handler::process_explosions(), Character::process_items(), sounds::process_sound_markers(), sounds::process_sounds(), monster::process_triggers(), monster::process_turn(), projectile_attack(), activity_handlers::pull_creature_finish(), mattack::pull_metal_weapon(), activity_handlers::pulp_do_turn(), monster::push_to(), put_into_vehicle(), put_into_vehicle_or_drop(), iexamine::quern_examine(), veh_menu::query(), query_pick(), plot_options::query_seed(), map::queue_main_cleanup(), iuse::radiocontrol(), rcdrive(), Character::reach_attack(), npc::reach_omt_destination(), avatar::rebuild_aim_cache(), target_ui::recalc_aim_turning_penalty(), Character::recalc_sight_limits(), editmap::recalc_target(), spell_effect::recharge_vehicle(), Character::recoil_vehicle(), veh_app_interact::refill(), vehicle::refresh_zones(), npc::regen_ai_cache(), reload_furniture(), veh_app_interact::remove(), zone_manager::remove(), construct::remove_above(), anonymous_namespace{monexamine.cpp}::remove_armor(), anonymous_namespace{monexamine.cpp}::remove_bag_from(), anonymous_namespace{monexamine.cpp}::remove_battery(), vehicle::remove_carried_vehicle(), link_up_actor::remove_extensions(), vehicle::remove_remote_part(), remove_submap_turrets(), map::remove_trap(), DefaultRemovePartHandler::removed(), veh_utils::repair_part(), requirements_map(), firestarter_actor::resolve_firestarter_use(), explosion_handler::resonance_cascade(), Character::rest_quality(), aim_activity_actor::restore_view(), mattack::resurrect(), zone_manager::revert_vzones(), spell_effect::revive(), spell_effect::revive_dormant(), mattack::riotbot(), rod_fish(), Character::rooted(), Character::rooted_message(), map::rotate(), map::route(), route_adjacent(), route_best_workbench(), iexamine::rubble(), target_ui::run(), area_expander::run(), Character::run_cost_effects(), inventory::rust_iron_items(), iexamine::safe(), sane_consume_items(), mapbuffer::save(), avatar::save_map_memory(), npc::saw_player_recently(), scatter_chunks(), monster::scent_move(), mattack::science(), Character::search_surroundings(), mattack::searchlight(), npc::see_item_say_smth(), Creature::sees(), Character::sees(), npc::sees_dangerous_field(), Character::sees_with_infrared(), lockpick_activity_actor::select_location(), sendRadioSignal(), vehicle::separate_from_grid(), veh_interact::serialize_activity(), serialize_liquid_source(), debug_menu::set_automove(), advanced_inv_area::set_container_position(), target_ui::set_cursor_pos(), Character::set_destination(), DefaultRemovePartHandler::set_floor_cache_dirty(), set_item_map(), set_item_map_or_vehicle(), target_ui::set_last_target(), avatar::set_movement_mode(), Creature::set_pos_only(), DefaultRemovePartHandler::set_transparency_cache_dirty(), target_ui::set_view_offset(), editmap::setup_fmenu(), trapfunc::shadow(), vehicle::shed_loose_parts(), mattack::shockstorm(), trapfunc::shotgun(), monster::shove_vehicle(), live_view::show(), explosion_handler::shrapnel(), mattack::shriek_stun(), iexamine::shrub_marloss(), iexamine::shrub_wildveggies(), Character::sight_impaired(), Character::sight_range(), iexamine::sign(), trapfunc::sinkhole(), sinkhole_safety_roll(), iuse::siphon(), sleep(), Character::sleep_spot(), vehicle::slow_leak(), vehicle::smart_controller_handle_turn(), smash(), vehicle::smash(), vehicle::smash_security_system(), smoker_activate(), smoker_finalize(), smoker_load_food(), iexamine::smoker_options(), trapfunc::snake(), trapfunc::snare_heavy(), trapfunc::snare_light(), debug_menu::spawn_artifact(), monster::spawn_dissectables_on_death(), map::spawn_monsters_submap(), map::spawn_monsters_submap_group(), debug_menu::spawn_nested_mapgen(), spawn_spores(), spell_effect::spawn_summoned_vehicle(), spell_effect::spell_effect_blast(), spell_effect_cone_range_override(), spell_move(), spell_remove_field(), activity_handlers::spellcasting_finish(), vehicle::spew_field(), item_pocket::spill_contents(), mdeath::splatter(), Character::spores(), fungal_effects::spread_fungus(), fungal_effects::spread_fungus_one_tile(), Character::stagger(), harvest_activity_actor::start(), boltcutting_activity_actor::start(), vehicle_folding_activity_actor::start(), hacksaw_activity_actor::start(), workout_activity_actor::start(), oxytorch_activity_actor::start(), prying_activity_actor::start(), activity_handlers::start_engines_finish(), activity_handlers::start_fire_do_turn(), activity_handlers::start_fire_finish(), stash_on_pet(), vehicle::static_drag(), sting_get_target(), iexamine::stook_empty(), iexamine::stook_full(), vehicle::stop(), npc::stow_item(), mattack::stretch_attack(), monster::stumble(), Creature::stumble_invis(), swap_pos(), Character::symbol_color(), Target_attributes::Target_attributes(), spell::targetable_locations(), npc_attack_melee::targetable_points(), npc_attack_gun::targetable_points(), npc_attack_throw::targetable_points(), teleport::teleport(), teleport::teleport_to_point(), tell_magic_veh_stop_following(), tell_magic_veh_to_follow(), tell_veh_stop_following(), trapfunc::temple_flood(), trapfunc::temple_toggle(), terrain_collision_data(), test_passable(), vehicle::thrust(), tidy_activity(), mattack::tindalos_teleport(), auto_navigation_data::to_view(), Character::toggle_hauling(), iexamine::toPumpFuel(), vehicle::total_solar_epower(), vehicle::total_water_wheel_epower(), vehicle::total_wind_epower(), vehicle::tow_cable_too_far(), spell_effect::transform_blast(), vehicle::transform_terrain(), iexamine::translocator(), activity_handlers::travel_do_turn(), iexamine::tree_hickory(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), iexamine::tree_marloss(), mattack::triffid_heartbeat(), trapfunc::tripwire(), monster::try_biosignature(), try_fuel_fire(), target_ui::try_reacquire_target(), Character::try_remove_grab(), Character::try_remove_heavysnare(), monster::try_reproduce(), iexamine::try_start_hacking(), avatar::try_to_sleep(), turnOnSelectedPump(), monster::turns_to_reach(), editmap::uber_draw_ter(), DefaultRemovePartHandler::unboard(), vehicle::unboard_all(), Character::uncanny_dodge(), vehicle_unfolding_activity_actor::unfold_vehicle(), Character::uninstall_bionic(), unroll_digging(), Character::update_bodytemp(), update_lum(), update_mapgen_function_json::update_map(), npc::update_path(), map::update_pathfinding_cache(), autodrive_activity_actor::update_player_vehicle(), target_ui::update_status(), vehicle::update_time(), editmap::update_view_with_help(), weather_manager::update_weather(), explosion_iuse::use(), consume_drug_iuse::use(), place_npc_iuse::use(), deploy_furn_actor::use(), firestarter_actor::use(), fireweapon_on_actor::use(), place_trap_actor::use(), emit_actor::use(), deploy_tent_actor::use(), unpack_actor::use(), link_up_actor::use(), item_stack::use_charges(), Character::use_charges(), Character::use_fire(), Character::valid_aoe_technique(), basecamp::validate_sort_points(), vehicle_activity(), debug_menu::vehicle_battery_charge(), npc::vehicle_danger(), display::vehicle_driven(), debug_menu::vehicle_export(), activity_handlers::vehicle_finish(), vehicle_selector::vehicle_selector(), iexamine::vending(), mattack::vine(), iuse::voltmeter(), item_location::impl::item_on_map::volume_capacity(), Character::vomit(), wait(), map::water_from(), iexamine::water_source(), weather_sound(), iuse::weather_tool(), suffer::while_grabbed(), suffer::while_underwater(), monster::will_join_horde(), monster::will_move_to(), monster::will_reach(), debug_menu::wishitem(), iexamine::workbench(), Character::workbench_crafting_speed_multiplier(), iexamine::workbench_internal(), npc::worker_downtime(), iexamine::workout(), mattack::zombie_fuse(), and map::~map().
get_memorial()
memorial_logger& get_memorial ()
Definition at line 13837 of file game.cpp.
 {
     return g->memorial();
 }
Referenced by timed_event::actualize(), turn_handler::cleanup_at_end(), destroyed_armor_msg(), Character::fall_asleep(), Character::forced_dismount(), mattack::fungus_fortify(), and marloss_common().
get_player_character()
Character& get_player_character ()
Definition at line 13807 of file game.cpp.
 {
     return g->u;
 }
Referenced by anonymous_namespace{item.cpp}::_stacks_location_hint(), mattack::absorb_meat(), npc::act_on_danger_assessment(), vehicle::act_on_map(), act_vehicle_unload_fuel(), computer_session::action_amigara_log(), computer_session::action_blood_anal(), computer_session::action_cascade(), computer_session::action_close_gate(), computer_session::action_conveyor(), computer_session::action_data_anal(), computer_session::action_deactivate_shock_vent(), computer_session::action_download_software(), computer_session::action_extract_rad_source(), computer_session::action_geiger(), computer_session::action_irradiator(), computer_session::action_list_bionics(), computer_session::action_lock(), computer_session::action_map_sewer(), computer_session::action_map_subway(), computer_session::action_maps(), computer_session::action_miss_launch(), computer_session::action_open(), computer_session::action_open_gate(), computer_session::action_radio_archive(), computer_session::action_release(), computer_session::action_release_bionics(), computer_session::action_research(), computer_session::action_sample(), computer_session::action_shutters(), computer_session::action_srcf_elevator(), computer_session::action_srcf_seal(), computer_session::action_terminate(), computer_session::action_toll(), computer_session::action_unlock(), computer_session::activate_function(), mission_data::add(), memorial_logger::add(), timed_event_manager::add(), anonymous_namespace{monexamine.cpp}::add_armor(), map::add_camp(), talker_character::add_effect(), map::add_field(), inventory::add_item(), anonymous_namespace{monexamine.cpp}::add_leash(), npc::address_needs(), npc::address_player(), item::ammo_capacity(), veh_app_interact::app_loop(), map::apparent_light_at(), apply_ammo_effects(), apply_camp_ownership(), projectile::apply_effects_damage(), armor_encumb_header_info(), item::armor_fit_info(), item::armor_info(), npc::assess_danger(), assign_veh_to_follow(), monster::attack_at(), npc::attitude_to(), Creature::auto_find_hostile_target(), vehicle::automatic_fire_turret(), Pickup::autopickup(), talk_function::bionic_install(), talk_function::bionic_install_allies(), bionic_manip_cos(), talk_function::bionic_remove(), mattack::blow_whistle(), trapfunc::board(), board_up(), mattack::boomer(), mattack::boomer_glow(), mattack::brandish(), mattack::browse(), vehicle::build_bike_rack_menu(), vehicle::build_interact_menu(), map::build_map_cache(), map::build_vision_transparency_cache(), start_location::burn(), butcher_time_to_cut(), talk_function::buy_haircut(), talk_function::buy_shave(), veh_interact::cache_tool_availability(), veh_interact::cache_tool_availability_update_lifting(), melee_actor::call(), mattack::callblobs(), trapfunc::caltrops(), basecamp::camp_food_supply(), computer_session::can_activate(), can_butcher_at(), can_construct(), can_do_activity_there(), vehicle::can_enable(), can_examine_at(), Character::can_install_bionics(), can_interact_at(), requirement_data::can_make_with_inventory(), can_move_vertical_at(), veh_interact::can_potentially_install(), veh_app_interact::can_siphon(), Character::can_uninstall_bionic(), talk_function::caravan_dist(), talk_function::caravan_return(), talk_function::carpenter_return(), cast_spell(), trapfunc::cast_spell(), iexamine::chainfence(), change_armor_sprite(), debug_menu::change_spells(), mattack::chickenbot(), choose_adjacent(), choose_direction(), choose_direction_rel_ms(), basecamp::choose_new_leader(), ui::omap::choose_point(), close(), item::color_in_inventory(), colorized_trap_name_at(), comestible_inventory_preset::comestible_inventory_preset(), talk_function::companion_choose(), talk_function::companion_choose_return(), talk_function::companion_mission(), talk_function::companion_return(), npc::complain(), npc::complain_about(), construction_color(), npc::consume_food_from_camp(), vehicle::consume_fuel(), vehicle::control_doors(), vehicle::control_engines(), Character::count_trait_flag(), basecamp::craft_description(), mission_start::create_hidden_lab_console(), mission_start::create_ice_lab_console(), mission_start::create_lab_console(), anonymous_namespace{monexamine.cpp}::cull(), damage_targets(), mattack::darkman(), Character::deal_damage(), Creature::deal_damage_handle_type(), repair_item_actor::default_action(), mattack::dermatik(), item_location::deserialize(), item::detonate(), npc::die(), iuse::directional_hologram(), iexamine::dirtmound(), disassemble_inventory_preset::disassemble_inventory_preset(), item::disassembly_info(), veh_app_interact::disconnect(), map::displace_vehicle(), ui::omap::display(), overmap_ui::display(), ui::omap::display_editor(), ui::omap::display_hordes(), veh_interact::display_name(), ui::omap::display_scents(), ui::omap::display_visible_weather(), ui::omap::display_weather(), explosion_handler::do_blast(), melee_actor::do_grab(), veh_interact::do_main_loop(), Pickup::do_pickup(), advanced_inventory::do_return_entry(), construct::done_trunk_plank(), map::draw_from_above(), editmap::draw_main_ui_overlay(), advanced_inventory::draw_minimap(), overmap_ui::draw_notes(), overmap_ui::draw_om_sidebar(), mission_ui_impl::draw_selected_description(), draw_spellbook_info(), vehicle::drive_to_local_target(), talk_function::drop_stolen_item(), mattack::dsa_drone_scan(), anonymous_namespace{monexamine.cpp}::dump_items(), mattack::eat_carrion(), mattack::eat_food(), eff_fun_teleglow(), editmap::eget_direction(), explosion_handler::emp_blast(), talker_item_const::encumbrance_at(), known_magic::evaluate_opens_spellbook_data(), mattack::evolve_kill_strike(), npc::execute_action(), map_data_common_t::extended_description(), monster::extended_description(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lightning(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_friend(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_has_camp(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_know_recipe(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_profession(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_wants_to_talk(), basecamp::faction_display(), npc::faction_display(), computer_session::failure_alarm(), computer_session::failure_amigara(), computer_session::failure_damage(), computer_session::failure_destroy_blood(), computer_session::failure_destroy_data(), computer_session::failure_manhacks(), computer_session::failure_pump_explode(), computer_session::failure_secubots(), computer_session::failure_shutdown(), farm_action(), basecamp::farm_return(), talk_function::field_harvest(), talk_function::field_plant(), overmapbuffer::find_all_radio_stations(), npc::find_corpse_to_pulp(), overmapbuffer::find_radio_station(), mission_start::find_safety(), inventory::find_usable_cached_invlet(), heal_actor::finish_using(), mattack::flame(), mattack::flamethrower(), explosion_handler::flashbang(), talk_function::follow(), npc::follow_distance(), item::food_info(), monster::footsteps(), talk_function::forage_return(), known_magic::forget_spell(), veh_interact::format_reqs(), mattack::frag(), advanced_inventory_pane::free_volume(), advanced_inventory_pane::free_weight_capacity(), suffer::from_bad_bionics(), vehicle::fuel_left(), fungal_effects::fungalize(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), mattack::fungus_sprout(), vehicle::gain_moves(), dialogue::gen_responses(), debug_menu::generate_effect_list(), map::generate_lightmap(), generic_barber(), monster::get_attitude(), get_autopickup_items(), get_avatar_or_follower(), get_best_fire(), quality_requirement::get_color(), selection_column_preset::get_color(), bionic_install_preset::get_failure_chance(), bionic_install_surgeon_preset::get_failure_chance(), get_freshness_description(), sfx::get_heard_angle(), sfx::get_heard_volume(), get_heat_radiation(), inventory_entry::get_invlet_color(), advanced_inv_area::get_item_count(), liquid_handler::get_liquid_target(), item::get_min_str(), get_mission_om_origin(), veh_interact::get_most_repairable_part(), overmapbuffer::get_npcs_near_player(), npc::get_opinion_values(), overmap_ui::get_overmap_neighbors(), overmap_ui::get_overmap_path_to(), npc::get_path_avoid(), read_activity_actor::get_progress_message(), item::get_quality_nonrecursive(), Creature::get_summoner(), aim_activity_actor::get_weapon(), talk_function::give_aid(), talk_function::give_all_aid(), basecamp::give_basecamp_equipment(), talk_function::give_equipment_allowance(), talker_npc::give_item_to(), glare(), talker_furniture::global_omt_location(), talker_item_const::global_omt_location(), trapfunc::glow(), trapfunc::goo(), npc::good_escape_direction(), talk_function::goto_location(), grab(), mattack::graze(), mattack::grenadier(), mattack::grenadier_elite(), mattack::grow_vine(), gunmode_checks_weapon(), handbrake(), handle_action_menu(), talk_function::handle_outpost_mission(), handle_problematic_pickup(), npc::handle_sound(), vehicle::handle_trap(), handle_weather_effects(), Character::hardcoded_effects(), tool_comp::has(), item_comp::has(), quality_requirement::has(), player_morale::has_flag(), has_pre_terrain(), Character::has_trait_flag(), haul(), monster::hear_sound(), talk_function::hospital_raid(), talk_function::hospital_raid_return(), talk_function::hostile(), vehicle::idle(), npc::indoor_voice(), consume_drug_iuse::info(), heal_actor::info(), anonymous_namespace{monexamine.cpp}::insert_battery(), exosuit_interact::insert_replace_activate_mod(), exosuit_interact::interact_loop(), npc::is_ally(), debug_menu::is_debug_character(), npc::is_player_ally(), vehicle::is_rotorcraft(), item::is_worn_by_player(), iexamine::keg(), pocket_favorite_callback::key(), spellcasting_callback::key(), ma_style_callback::key(), mission_start::kill_nemesis(), monster::know_danger_at(), talk_function::labor_return(), talk_function::lesser_give_aid(), talk_function::lesser_give_all_aid(), loot(), monexamine::mech_hack(), item::med_info(), monster::melee_attack(), Character::melee_attack_abstract(), item::melee_combat_info(), monexamine::mfriend_menu(), anonymous_namespace{monexamine.cpp}::milk_source(), anonymous_namespace{messages.cpp}::messages_impl::modify_msg_with_exclamations(), talk_function::morale_chat(), talk_function::morale_chat_activity(), anonymous_namespace{monexamine.cpp}::mount_pet(), monster::move(), npc::move(), advanced_inventory::move_all_items(), npc::move_away_from(), activity_handlers::move_cost_cart(), activity_handlers::move_cost_inv(), overmapbuffer::move_hordes(), npc::move_to(), map::move_vehicle(), npc::mug_player(), multi_projectile_hit_message(), mattack::multi_robot(), spell_events::notify(), memorial_logger::notify(), read_activity_actor::npc_read(), npc_temp_orders_menu(), mattack::nurse_operate(), monster::nursebot_operate(), basecamp::om_upgrade_description(), melee_actor::on_damage(), vehicle::on_move(), item::on_pickup(), item::on_wear(), item::on_wield(), player_morale::on_worn_item_washed(), vehicle::open_or_close(), activity_handlers::operation_do_turn(), advanced_inv_sorter::operator()(), target_ui::panel_spell_info(), vehicle::part_collision(), vehicle::part_displayed_at(), monexamine::pay_bot(), timed_event::per_turn(), tutorial_game::per_turn(), liquid_handler::perform_liquid_transfer(), monexamine::pet_menu(), mattack::photograph(), pick_one_up(), activity_handlers::pickaxe_finish(), trapfunc::pit(), trapfunc::pit_glass(), trapfunc::pit_spikes(), pl_sees(), map::pl_sees(), mission_start::place_npc_software(), monster::plan(), vehicle::play_music(), anonymous_namespace{monexamine.cpp}::play_with(), basecamp::player_eats_meal(), player_hit_message(), talk_function::player_weapon_away(), talk_function::player_weapon_drop(), pldrive(), avatar_action::plthrow(), veh_app_interact::plug(), iuse::portable_game(), tutorial_game::post_action(), vehicle::power_parts(), vehicle::precollision_check(), npc::print_info(), monster::print_info(), advanced_inventory::print_items(), monster::process_effects(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::process_eoc(), map::process_fields_in_submap(), overmapbuffer::process_mongroups(), sounds::process_sound_markers(), monster::process_turn(), anonymous_namespace{monexamine.cpp}::push(), monster::push_to(), item::qualities_info(), veh_menu::query(), advanced_inventory::query_charges(), plot_options::query_seed(), Pickup::query_thief(), mission_util::random_house_in_closest_city(), mattack::ratking(), mattack::rattle(), rcdrive(), Character::reach_attack(), npc::reach_omt_destination(), item::ready_to_revive(), basecamp::recipe_batch_max(), basecamp::recruit_evaluation(), advanced_inventory::redraw_sidebar(), reflesh_favorite(), npc::regen_ai_cache(), vehicle::reload_seeds(), veh_app_interact::remove(), anonymous_namespace{monexamine.cpp}::remove_armor(), anonymous_namespace{monexamine.cpp}::remove_bag_from(), anonymous_namespace{monexamine.cpp}::remove_battery(), talker_character::remove_effect(), talker_monster::remove_effect(), anonymous_namespace{monexamine.cpp}::remove_leash(), anonymous_namespace{monexamine.cpp}::remove_saddle_from(), remove_submap_turrets(), effect_source::resolve_creature(), explosion_handler::resonance_cascade(), mattack::resurrect(), reveal_destination(), mission_util::reveal_om_ter(), mission_start::reveal_refugee_center(), reveal_route(), item::rot_info(), run_item_eocs(), inventory::rust_iron_items(), npc::say(), talk_function::scavenging_patrol_return(), talk_function::scavenging_raid_return(), monster::scent_move(), mattack::searchlight(), map::seen_cache_process_ledges(), Creature::sees(), select_ammo_inventory_preset::select_ammo_inventory_preset(), Character::select_item_component(), auto_pickup::select_items(), vehicle::separate_from_grid(), target_ui::set_cursor_pos(), set_up_butchery(), player_morale::set_worn(), anonymous_namespace{monexamine.cpp}::shear_animal(), mattack::shockstorm(), explosion_handler::shockwave(), auto_pickup::user_interface::show(), auto_pickup::player_settings::show(), safemode::show(), trapfunc::sinkhole(), mattack::slimespring(), vehicle::smart_controller_handle_turn(), vehicle::smash_security_system(), outfit::sort_armor(), inventory_column::sort_compare(), map::spawn_monsters_submap_group(), spell_effect_area(), spellcasting_callback::spell_info_text(), spell_move(), consume_activity_actor::start(), advanced_inventory::start_activity(), basecamp::start_crafting(), vehicle::start_engine(), vehicle::start_engines(), activity_handlers::start_engines_finish(), basecamp::start_fortifications(), basecamp::start_relay_hide_site(), basecamp::start_setup_hide_site(), talk_function::start_training(), talk_function::start_training_gen(), talk_function::start_training_npc(), talk_function::start_training_seminar(), str_to_illiterate_str(), anonymous_namespace{monexamine.cpp}::swap(), swap_pos(), widget::sym_text_cond(), mission_util::target_om_ter_random(), mattack::taze(), debug_menu::teleport_overmap(), debug_menu::teleport_short(), tell_magic_veh_to_follow(), tell_veh_stop_following(), safemode::test_pattern(), widget::text_cond(), vehicle::thrust(), activity_handlers::train_finish(), mattack::triffid_heartbeat(), trapfunc::tripwire(), try_consume(), try_set_alarm(), Character::unload(), unroll_digging(), inventory::update_invlet(), update_time_left(), editmap::update_view_with_help(), map::update_visibility_cache(), weather_manager::update_weather(), deploy_tent_actor::use(), npc_attack_melee::use(), vehicle::use_harness(), vehicle::use_vehicle_tool(), basecamp::validate_sort_points(), map::vehmove(), wait(), weather_sound(), npc::will_accept_from_player(), monster::will_reach(), talker_npc::will_talk_to_u(), within_visual_range(), npc::would_take_that(), and advanced_inventory::~advanced_inventory().
get_player_view()
viewer& get_player_view ()
Definition at line 13812 of file game.cpp.
 {
     return g->u;
 }
Referenced by Character::ablative_armor_absorb(), outfit::absorb_damage(), mdefense::acidsplash(), add_msg_if_player_sees(), npc::add_msg_player_or_npc(), Character::add_msg_player_or_say(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), leap_actor::call(), trapfunc::caltrops_glass(), npc::complain(), trapfunc::crossbow(), mattack::dance(), Character::deactivate_bionic(), Character::deal_damage(), trapfunc::dissector(), npc::do_reload(), iuse::dog_whistle(), mattack::dogthing(), iuse::extinguisher(), conditional_fun::anonymous_namespace{condition.cpp}::f_player_see(), mattack::fungus_big_blossom(), mattack::fungus_corporate(), grenade_helper(), npc::heal_player(), anonymous_namespace{animation.cpp}::is_point_visible(), monster::knock_back_to(), mattack::leech_spawner(), mattack::lunge(), iuse::mace(), Creature::messaging_projectile_attack(), monster::move_effects(), npc::mutiny(), mattack::nurse_assist(), Character::on_hit(), gates::open_gate(), pick_follower(), npc::pick_up_item(), map::rotten_item_spawn(), seen_critter(), npc::set_attitude(), map::shoot(), trapfunc::shotgun(), npc::stow_item(), teleport::teleport_to_point(), Character::uncanny_dodge(), Character::uninstall_bionic(), mattack::upgrade(), outfit::wear_item(), npc::wield(), npc::would_take_that(), and mdefense::zapback().
get_scenario()
const scenario* get_scenario ()
Definition at line 13842 of file game.cpp.
 {
     return g->scen;
 }
Referenced by Character::add_traits(), char_creation::draw_age(), char_creation::draw_location(), Character::get_random_trait(), avatar::initialize(), avatar::load(), effect_on_conditions::load_new_character(), main_menu::opening_screen(), avatar::randomize(), avatar::randomize_hobbies(), set_description(), set_hobbies(), set_profession(), set_scenario(), set_traits(), skill_points_used(), avatar::store(), and trait_points_used().
get_scent()
scent_map& get_scent ()
Definition at line 13851 of file game.cpp.
 {
     return g->scent;
 }
Referenced by map::decay_fields_and_scent(), tutorial_game::init(), map::process_fields_in_submap(), monster::scent_move(), Character::update_type_of_scent(), editmap::update_view_with_help(), and monster::will_reach().
get_stats()
stats_tracker& get_stats ()
Definition at line 13856 of file game.cpp.
 {
     return g->stats();
 }
Referenced by memorial_logger::write_json_memorial(), and memorial_logger::write_text_memorial().
get_timed_events()
timed_event_manager& get_timed_events ()
Definition at line 13861 of file game.cpp.
 {
     return g->timed_events;
 }
Referenced by computer_session::action_amigara_log(), computer_session::action_amigara_start(), timed_event::actualize(), display::current_position_text(), debug_menu::debug(), mattack::dsa_drone_scan(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_alter_timed_events(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_custom_light_level(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_place_override(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), computer_session::failure_amigara(), iexamine::fswitch(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), mattack::photograph(), timed_event_manager::serialize_all(), avatar::should_show_map_memory(), trapfunc::temple_flood(), spell_effect::timed_event(), and timed_event_manager::unserialize_all().
get_weather()
weather_manager& get_weather ()
Definition at line 13866 of file game.cpp.
 {
     return g->weather;
 }
Referenced by Character::activate_bionic(), map::build_sunlight_cache(), map::build_transparency_cache(), Character::burn_fuel(), Character::calc_needs_rates(), Character::can_hear(), debug_menu::change_weather(), Character::complete_disassemble(), current_weather(), debug_menu::debug(), debug_menu::debug_menu_force_temperature(), Character::disp_info(), vehicle::do_environmental_effects(), draw_effects_summary(), eff_fun_sleep(), iuse::emf_passive_on(), vehicle::engine_cold_factor(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_weather(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lightning(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_next_weather(), activity_handlers::fill_liquid_do_turn(), get_bad_weather(), get_signal_for_hordes(), display::get_temp(), get_weather_const(), iexamine_helper::handle_harvest(), handle_weather_effects(), suffer::in_sunlight(), tutorial_game::init(), iexamine::ledge(), firestarter_actor::light_mod(), iuse::multicooker_tick(), vehicle::part_vpower_w(), photo_def_for_camera_point(), Character::process_bionic(), item::process_extinguish(), sounds::process_sound_markers(), sounds::process_sounds(), item::process_temperature_rot(), monster::process_turn(), map::produce_sap(), weather_manager::serialize_all(), map::spread_gas(), sum_conditions(), vehicle::total_wind_epower(), relic::try_recharge(), weather_manager::unserialize_all(), Character::update_bodytemp(), Character::update_frostbite(), Character::update_heartrate_index(), warm_enough_to_plant(), map::water_from(), anonymous_namespace{math_parser_diag.cpp}::weather_ass(), anonymous_namespace{math_parser_diag.cpp}::weather_eval(), weather_forecast(), display::weather_text_color(), iuse::weather_tool(), debug_menu::wind_direction(), debug_menu::wind_speed(), and display::wind_text_color().
is_valid_in_w_terrain()
bool is_valid_in_w_terrain (const point & p)
Definition at line 387 of file game.cpp.
 {
     return p.x >= 0 && p.x < TERRAIN_WINDOW_WIDTH && p.y >= 0 && p.y < TERRAIN_WINDOW_HEIGHT;
 }
References TERRAIN_WINDOW_HEIGHT, TERRAIN_WINDOW_WIDTH, point::x, and point::y.
Referenced by game::draw_critter(), anonymous_namespace{animation.cpp}::draw_sct_curses(), anonymous_namespace{animation.cpp}::hit_animation(), and game::mon_info_update().
list_items_filter_history_help()
static std::string list_items_filter_history_help () static
Definition at line 8398 of file game.cpp.
 {
     return colorize( _( "UP: history, CTRL-U: clear line, ESC: abort, ENTER: save" ), c_green );
 }
References _, c_green, and colorize().
Referenced by game::list_items().
maptile_field_intensity()
static int maptile_field_intensity (maptile & mt, field_type_id fld) static
Definition at line 1607 of file game.cpp.
 {
     const field_entry *field_ptr = mt.find_field( fld );
     return field_ptr == nullptr ? 0 : field_ptr->get_field_intensity();
 }
References maptile_impl< Submap >::find_field(), and field_entry::get_field_intensity().
Referenced by get_best_fire(), and get_heat_radiation().
mark_items_read_rec()
static void mark_items_read_rec (const item * itm) static
add item and all visible nested items inside to known items
Definition at line 8413 of file game.cpp.
 {
     uistate.read_items.insert( itm->typeId() );
     for( const item *child : itm->all_known_contents() ) {
         mark_items_read_rec( child );
     }
 }
References item::all_known_contents(), uistatedata::read_items, item::typeId(), and uistate.
Referenced by game::list_items().
rate_action_change_side()
static hint_rating rate_action_change_side (const avatar & you, const item & it) static
Definition at line 1822 of file game.cpp.
 {
     if( !it.is_sided() ) {
         return hint_rating::cant;
     }
     return you.is_worn( it ) ? hint_rating::good : hint_rating::iffy;
 }
References cant, good, iffy, item::is_sided(), and Character::is_worn().
Referenced by game::inventory_item_menu().
rate_action_collapse()
static hint_rating rate_action_collapse (const item & it) static
Definition at line 1911 of file game.cpp.
 {
     for( const item_pocket *pocket : it.get_all_standard_pockets() ) {
         if( !pocket->settings.is_collapsed() ) {
             return hint_rating::good;
         }
     }
     return hint_rating::cant;
 }
References cant, item::get_all_standard_pockets(), and good.
Referenced by game::inventory_item_menu().
rate_action_disassemble()
static hint_rating rate_action_disassemble (avatar & you, const item & it) static
Definition at line 1831 of file game.cpp.
 {
     if( you.can_disassemble( it, you.crafting_inventory() ).success() ) {
         // Possible right now
         return hint_rating::good;
     } else if( it.is_disassemblable() ) {
         // Potentially possible, but we currently lack requirements
         return hint_rating::iffy;
     } else {
         // Never possible
         return hint_rating::cant;
     }
 }
References Character::can_disassemble(), cant, Character::crafting_inventory(), good, iffy, item::is_disassemblable(), and ret_val_common::success().
Referenced by game::inventory_item_menu().
rate_action_eat()
static hint_rating rate_action_eat (const avatar & you, const item & it) static
Definition at line 1878 of file game.cpp.
 {
     if( it.is_container() ) {
         hint_rating best_rate = hint_rating::cant;
         it.visit_items( [&you, &best_rate]( item * node, item * ) {
             if( you.can_consume_as_is( *node ) )  {
                 ret_val<edible_rating> rate = you.will_eat( *node );
                 if( rate.success() ) {
                     best_rate = hint_rating::good;
                     return VisitResponse::ABORT;
                 } else if( rate.value() != INEDIBLE || rate.value() != INEDIBLE_MUTATION ) {
                     best_rate = hint_rating::iffy;
                 }
             }
             return VisitResponse::NEXT;
         } );
         return best_rate;
     }
     if( !you.can_consume_as_is( it ) ) {
         return hint_rating::cant;
     }
     const auto rating = you.will_eat( it );
     if( rating.success() ) {
         return hint_rating::good;
     } else if( rating.value() == INEDIBLE || rating.value() == INEDIBLE_MUTATION ) {
         return hint_rating::cant;
     }
     return hint_rating::iffy;
 }
References Character::can_consume_as_is(), cant, INEDIBLE, INEDIBLE_MUTATION, item::is_container(), NEXT, and item::visit_items().
Referenced by game::inventory_item_menu().
rate_action_expand()
static hint_rating rate_action_expand (const item & it) static
Definition at line 1921 of file game.cpp.
 {
     for( const item_pocket *pocket : it.get_all_standard_pockets() ) {
         if( pocket->settings.is_collapsed() ) {
             return hint_rating::good;
         }
     }
     return hint_rating::cant;
 }
References cant, item::get_all_standard_pockets(), and good.
Referenced by game::inventory_item_menu().
rate_action_insert()
static hint_rating rate_action_insert (const avatar & you, const item_location & loc) static
Definition at line 2013 of file game.cpp.
 {
     if( loc->will_spill_if_unsealed()
         && loc.where() != item_location::type::map
         && !you.is_wielding( *loc ) ) {
         return hint_rating::cant;
     }
     if( loc.get_item()->has_flag( json_flag_NO_RELOAD ) ) {
         return hint_rating::cant;
     }
     return hint_rating::good;
 }
References cant, item_location::get_item(), good, item::has_flag(), Character::is_wielding(), json_flag_NO_RELOAD, item_location::map, item_location::where(), and item::will_spill_if_unsealed().
Referenced by game::insert_item(), and game::inventory_item_menu().
rate_action_mend()
static hint_rating rate_action_mend (const avatar & , const item & it) static
Definition at line 1931 of file game.cpp.
 {
     // TODO: check also if item damage could be repaired via a tool
     if( !it.faults.empty() ) {
         return hint_rating::good;
     }
     return it.faults_potential().empty() ? hint_rating::cant : hint_rating::iffy;
 }
References cant, item::faults, item::faults_potential(), good, and iffy.
Referenced by game::inventory_item_menu().
rate_action_read()
static hint_rating rate_action_read (const avatar & you, const item & it) static
Definition at line 1940 of file game.cpp.
 {
     if( !it.is_book() ) {
         return hint_rating::cant;
     }
     std::vector<std::string> dummy;
     return you.get_book_reader( it, dummy ) ? hint_rating::good : hint_rating::iffy;
 }
References cant, Character::get_book_reader(), good, iffy, and item::is_book().
Referenced by game::inventory_item_menu().
rate_action_take_off()
static hint_rating rate_action_take_off (const avatar & you, const item & it) static
Definition at line 1950 of file game.cpp.
 {
     if( !it.is_armor() || it.has_flag( flag_NO_TAKEOFF ) || it.has_flag( flag_INTEGRATED ) ) {
         return hint_rating::cant;
     }
     if( you.is_worn( it ) ) {
         return hint_rating::good;
     }
     return hint_rating::iffy;
 }
References cant, flag_INTEGRATED, flag_NO_TAKEOFF, good, item::has_flag(), iffy, item::is_armor(), and Character::is_worn().
Referenced by game::inventory_item_menu().
rate_action_use()
static hint_rating rate_action_use (const avatar & you, const item & it) static
Gun >0 allows rating estimates for gun modifications
Definition at line 1963 of file game.cpp.
 {
     if( it.is_container() && it.item_has_uses_recursive() ) {
         return hint_rating::good;
     }
     if( it.is_broken() ) {
         return hint_rating::iffy;
     } else if( it.is_tool() ) {
         return it.ammo_sufficient( &you ) ? hint_rating::good : hint_rating::iffy;
     } else if( it.is_gunmod() ) {
         /** @EFFECT_GUN >0 allows rating estimates for gun modifications */
         if( static_cast<int>( you.get_skill_level( skill_gun ) ) == 0 ) {
             return hint_rating::iffy;
         } else {
             return hint_rating::good;
         }
     } else if( it.is_food() || it.is_medication() || it.is_book() || it.is_armor() ) {
         if( it.is_medication() && !you.can_use_heal_item( it ) ) {
             return hint_rating::cant;
         }
         if( it.is_comestible() && it.is_frozen_liquid() ) {
             return hint_rating::cant;
         }
         // The rating is subjective, could be argued as hint_rating::cant or hint_rating::good as well
         return hint_rating::iffy;
     } else if( it.type->has_use() ) {
         return hint_rating::good;
     }
     return hint_rating::cant;
 }
References item::ammo_sufficient(), Character::can_use_heal_item(), cant, Character::get_skill_level(), good, itype::has_use(), iffy, item::is_armor(), item::is_book(), item::is_broken(), item::is_comestible(), item::is_container(), item::is_food(), item::is_frozen_liquid(), item::is_gunmod(), item::is_medication(), item::is_tool(), item::item_has_uses_recursive(), skill_gun, and item::type.
Referenced by game::inventory_item_menu().
rate_action_view_recipe()
static hint_rating rate_action_view_recipe (avatar & you, const item & it) static
Definition at line 1845 of file game.cpp.
 {
     if( it.is_craft() ) {
         const recipe &craft_recipe = it.get_making();
         if( craft_recipe.is_null() || !craft_recipe.ident().is_valid() ) {
             return hint_rating::cant;
         } else if( you.get_group_available_recipes().contains( &craft_recipe ) ) {
             return hint_rating::good;
         }
     } else {
         itype_id item = it.typeId();
         bool is_byproduct = false;  // product or byproduct
         bool can_craft = false;
         // Does a recipe for the item exist?
         for( const auto& [_, r] : recipe_dict ) {
             if( !r.obsolete && ( item == r.result() || r.in_byproducts( item ) ) ) {
                 is_byproduct = true;
                 // If a recipe exists, does my group know it?
                 if( you.get_group_available_recipes().contains( &r ) ) {
                     can_craft = true;
                     break;
                 }
             }
         }
         if( !is_byproduct ) {
             return hint_rating::cant;
         } else if( can_craft ) {
             return hint_rating::good;
         }
     }
     return hint_rating::iffy;
 }
References _, cant, recipe_subset::contains(), Character::get_group_available_recipes(), item::get_making(), good, recipe::ident(), iffy, item::is_craft(), recipe::is_null(), string_id< T >::is_valid(), recipe_dict, and item::typeId().
Referenced by game::inventory_item_menu().
rate_action_wear()
static hint_rating rate_action_wear (const avatar & you, const item & it) static
Definition at line 1995 of file game.cpp.
 {
     if( !it.is_armor() ) {
         return hint_rating::cant;
     }
     if( you.is_worn( it ) ) {
         return hint_rating::iffy;
     }
     return you.can_wear( it ).success() ? hint_rating::good : hint_rating::iffy;
 }
References Character::can_wear(), cant, good, iffy, item::is_armor(), Character::is_worn(), and ret_val_common::success().
Referenced by game::inventory_item_menu().
rate_action_wield()
static hint_rating rate_action_wield (const avatar & you, const item & it) static
Definition at line 2008 of file game.cpp.
 {
     return you.can_wield( it ).success() ? hint_rating::good : hint_rating::iffy;
 }
References Character::can_wield(), good, iffy, and ret_val_common::success().
Referenced by game::inventory_item_menu().
set_scenario()
void set_scenario (const scenario * new_scenario)
Definition at line 13846 of file game.cpp.
 {
     g->scen = new_scenario;
 }
Referenced by avatar::load().
timestamp_now()
static std::string timestamp_now () static
Definition at line 2997 of file game.cpp.
 {
     std::time_t time = std::time( nullptr );
     std::stringstream date_buffer;
     date_buffer << std::put_time( std::localtime( &time ), "%Y-%m-%dT%H-%M-%S" );
     return date_buffer.str();
 }
Referenced by game::move_save_to_graveyard().
update_faction_api()
static void update_faction_api (npc * guy) static
Definition at line 1737 of file game.cpp.
 {
     if( guy->get_faction_ver() < 2 ) {
         guy->set_fac( faction_your_followers );
         guy->set_faction_ver( 2 );
     }
 }
References faction_your_followers, npc::get_faction_ver(), npc::set_fac(), and npc::set_faction_ver().
Referenced by game::validate_npc_followers().
veh_lumi()
static int veh_lumi (vehicle & veh) static
Definition at line 1304 of file game.cpp.
 {
     float veh_luminance = 0.0f;
     float iteration = 1.0f;
     auto lights = veh.lights();
     for( const vehicle_part *pt : lights ) {
         const vpart_info &vp = pt->info();
         if( vp.has_flag( VPFLAG_CONE_LIGHT ) ||
             vp.has_flag( VPFLAG_WIDE_CONE_LIGHT ) ) {
             veh_luminance += vp.bonus / iteration;
             iteration = iteration * 1.1f;
         }
     }
     // Calculation: see lightmap.cpp
     return LIGHT_RANGE( ( veh_luminance * 3 ) );
 }
References vpart_info::bonus, vpart_info::has_flag(), LIGHT_RANGE(), vehicle::lights(), VPFLAG_CONE_LIGHT, and VPFLAG_WIDE_CONE_LIGHT.
Referenced by game::calc_driving_offset().
zones_manager_draw_borders()
static void zones_manager_draw_borders (const catacurses::window & w_border, const catacurses::window & w_info_border, const int iInfoHeight, const int width) static
Definition at line 6900 of file game.cpp.
 {
     for( int i = 1; i < TERMX; ++i ) {
         if( i < width ) {
             mvwputch( w_border, point( i, 0 ), c_light_gray, LINE_OXOX ); // -
             mvwputch( w_border, point( i, TERMY - iInfoHeight - 1 ), c_light_gray,
                       LINE_OXOX ); // -
         }
         if( i < TERMY - iInfoHeight ) {
             mvwputch( w_border, point( 0, i ), c_light_gray, LINE_XOXO ); // |
             mvwputch( w_border, point( width - 1, i ), c_light_gray, LINE_XOXO ); // |
         }
     }
     mvwputch( w_border, point_zero, c_light_gray, LINE_OXXO ); // |^
     mvwputch( w_border, point( width - 1, 0 ), c_light_gray, LINE_OOXX ); // ^|
     mvwputch( w_border, point( 0, TERMY - iInfoHeight - 1 ), c_light_gray,
               LINE_XXXO ); // |-
     mvwputch( w_border, point( width - 1, TERMY - iInfoHeight - 1 ), c_light_gray,
               LINE_XOXX ); // -|
     mvwprintz( w_border, point( 2, 0 ), c_white, _( "Zones manager" ) );
     wnoutrefresh( w_border );
     for( int j = 0; j < iInfoHeight - 1; ++j ) {
         mvwputch( w_info_border, point( 0, j ), c_light_gray, LINE_XOXO );
         mvwputch( w_info_border, point( width - 1, j ), c_light_gray, LINE_XOXO );
     }
     for( int j = 0; j < width - 1; ++j ) {
         mvwputch( w_info_border, point( j, iInfoHeight - 1 ), c_light_gray, LINE_OXOX );
     }
     mvwputch( w_info_border, point( 0, iInfoHeight - 1 ), c_light_gray, LINE_XXOO );
     mvwputch( w_info_border, point( width - 1, iInfoHeight - 1 ), c_light_gray, LINE_XOOX );
     wnoutrefresh( w_info_border );
 }
References _, c_light_gray, c_white, LINE_OOXX, LINE_OXOX, LINE_OXXO, LINE_XOOX, LINE_XOXO, LINE_XOXX, LINE_XXOO, LINE_XXXO, mvwprintz(), mvwputch(), point, point_zero, TERMX, TERMY, and catacurses::wnoutrefresh().
Referenced by game::zones_manager().
zones_manager_shortcuts()
static void zones_manager_shortcuts (const catacurses::window & w_info, faction_id const & faction) static
Definition at line 6862 of file game.cpp.
 {
     werase( w_info );
     int tmpx = 1;
     tmpx += shortcut_print( w_info, point( tmpx, 1 ), c_white, c_light_green, _( "<A>dd" ) ) + 2;
     tmpx += shortcut_print( w_info, point( tmpx, 1 ), c_white, c_light_green, _( "<P>ersonal" ) ) + 2;
     tmpx += shortcut_print( w_info, point( tmpx, 1 ), c_white, c_light_green, _( "<R>emove" ) ) + 2;
     tmpx += shortcut_print( w_info, point( tmpx, 1 ), c_white, c_light_green, _( "<E>nable" ) ) + 2;
     shortcut_print( w_info, point( tmpx, 1 ), c_white, c_light_green, _( "<D>isable" ) );
     tmpx = 1;
     shortcut_print( w_info, point( tmpx, 2 ), c_white, c_light_green,
                     _( "<T>-Toggle zone display" ) );
     tmpx += shortcut_print( w_info, point( tmpx, 3 ), c_white, c_light_green,
                             _( "<Z>-Enable personal" ) ) + 2;
     shortcut_print( w_info, point( tmpx, 3 ), c_white, c_light_green,
                     _( "<X>-Disable personal" ) );
     tmpx = 1;
     tmpx += shortcut_print( w_info, point( tmpx, 4 ), c_white, c_light_green,
                             _( "<+-> Move up/down" ) ) + 2;
     shortcut_print( w_info, point( tmpx, 4 ), c_white, c_light_green, _( "<Enter>-Edit" ) );
     tmpx = 1;
     tmpx += shortcut_print( w_info, point( tmpx, 5 ), c_white, c_light_green,
                             _( "<S>how all / hide distant" ) ) + 2;
     shortcut_print( w_info, point( tmpx, 5 ), c_white, c_light_green, _( "<M>ap" ) );
     if( debug_mode ) {
         shortcut_print( w_info, point( 1, 6 ), c_light_red, c_light_green,
                         string_format( _( "Shown <F>action: %s" ), faction.str() ) );
     }
     wnoutrefresh( w_info );
 }
References _, c_light_green, c_light_red, c_white, debug_mode, point, shortcut_print(), string_format(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by game::zones_manager().
Variable Documentation
ACT_BLEED
const activity_id ACT_BLEED("ACT_BLEED") ("ACT_BLEED") static
Referenced by butcher_submenu().
ACT_BUTCHER
const activity_id ACT_BUTCHER("ACT_BUTCHER") ("ACT_BUTCHER") static
Referenced by butcher_submenu(), and game::place_player().
ACT_BUTCHER_FULL
const activity_id ACT_BUTCHER_FULL("ACT_BUTCHER_FULL") ("ACT_BUTCHER_FULL") static
Referenced by butcher_submenu().
ACT_DISMEMBER
const activity_id ACT_DISMEMBER("ACT_DISMEMBER") ("ACT_DISMEMBER") static
Referenced by butcher_submenu().
ACT_DISSECT
const activity_id ACT_DISSECT("ACT_DISSECT") ("ACT_DISSECT") static
Referenced by butcher_submenu().
ACT_FIELD_DRESS
const activity_id ACT_FIELD_DRESS("ACT_FIELD_DRESS") ("ACT_FIELD_DRESS") static
Referenced by butcher_submenu().
ACT_PULP
const activity_id ACT_PULP("ACT_PULP") ("ACT_PULP") static
Referenced by game::place_player().
ACT_QUARTER
const activity_id ACT_QUARTER("ACT_QUARTER") ("ACT_QUARTER") static
Referenced by butcher_submenu().
ACT_SKIN
const activity_id ACT_SKIN("ACT_SKIN") ("ACT_SKIN") static
Referenced by butcher_submenu().
ACT_TRAIN
const activity_id ACT_TRAIN("ACT_TRAIN") ("ACT_TRAIN") static
Referenced by game::cancel_activity_query().
ACT_TRAIN_TEACHER
const activity_id ACT_TRAIN_TEACHER("ACT_TRAIN_TEACHER") ("ACT_TRAIN_TEACHER") static
Referenced by game::cancel_activity_query().
ACT_TRAVELLING
const activity_id ACT_TRAVELLING("ACT_TRAVELLING") ("ACT_TRAVELLING") static
Referenced by game::cancel_activity_or_ignore_query(), game::cancel_activity_query(), and game::portal_storm_query().
ACT_VIEW_RECIPE
const activity_id ACT_VIEW_RECIPE("ACT_VIEW_RECIPE") ("ACT_VIEW_RECIPE") static
Referenced by game::inventory_item_menu().
bio_jointservo
const bionic_id bio_jointservo("bio_jointservo") ("bio_jointservo") static
Referenced by game::on_move_effects().
bio_probability_travel
const bionic_id bio_probability_travel("bio_probability_travel") ("bio_probability_travel") static
Referenced by game::phasing_move().
bio_remote
const bionic_id bio_remote("bio_remote") ("bio_remote") static
Referenced by game::remoteveh(), and game::setremoteveh().
character_modifier_slip_prevent_mod
const character_modifier_id character_modifier_slip_prevent_mod("slip_prevent_mod") ("slip_prevent_mod") static
Referenced by game::slip_down_chance().
climbing_aid_ability_WALL_CLING
const climbing_aid_id climbing_aid_ability_WALL_CLING("ability_WALL_CLING") ("ability_WALL_CLING") static
Referenced by game::vertical_move().
climbing_aid_default
const climbing_aid_id climbing_aid_default("default") ("default") static
Referenced by game::climb_down_menu_pick(), game::slip_down_chance(), and game::vertical_move().
climbing_aid_furn_CLIMBABLE
const climbing_aid_id climbing_aid_furn_CLIMBABLE("furn_CLIMBABLE") ("furn_CLIMBABLE") static
Referenced by game::vertical_move().
damage_acid
const damage_type_id damage_acid("acid") ("acid") static
Referenced by game::place_player().
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by game::fling_creature(), game::get_dangerous_tile(), game::knockback(), and game::place_player().
damage_cut
const damage_type_id damage_cut("cut") ("cut") static
Referenced by game::get_dangerous_tile(), and game::place_player().
DANGEROUS_PROXIMITY
constexpr int DANGEROUS_PROXIMITY = 5 static constexpr
Definition at line 375 of file game.cpp.
Referenced by game::is_hostile_very_close().
effect_adrenaline_mycus
const efftype_id effect_adrenaline_mycus("adrenaline_mycus") ("adrenaline_mycus") static
Referenced by game::mon_info_update().
effect_asked_to_train
const efftype_id effect_asked_to_train("asked_to_train") ("asked_to_train") static
Referenced by game::cancel_activity_query().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
Referenced by game::print_items_info().
effect_bouldering
const efftype_id effect_bouldering("bouldering") ("bouldering") static
Referenced by game::place_player().
effect_contacts
const efftype_id effect_contacts("contacts") ("contacts") static
Referenced by game::use_computer().
effect_docile
const efftype_id effect_docile("docile") ("docile") static
Referenced by game::disable_robot().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by game::revive_corpse(), and game::save_cyborg().
effect_fake_common_cold
const efftype_id effect_fake_common_cold("fake_common_cold") ("fake_common_cold") static
Referenced by game::perhaps_add_random_npc().
effect_fake_flu
const efftype_id effect_fake_flu("fake_flu") ("fake_flu") static
Referenced by game::perhaps_add_random_npc().
effect_gliding
const efftype_id effect_gliding("gliding") ("gliding") static
Referenced by game::find_or_make_stairs(), and game::vertical_move().
effect_laserlocked
const efftype_id effect_laserlocked("laserlocked") ("laserlocked") static
Referenced by game::check_safe_mode_allowed().
effect_led_by_leash
const efftype_id effect_led_by_leash("led_by_leash") ("led_by_leash") static
Referenced by game::vertical_move().
effect_no_sight
const efftype_id effect_no_sight("no_sight") ("no_sight") static
Referenced by game::place_player().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by game::place_player().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by game::examine(), and game::start_game().
effect_psi_stunned
const efftype_id effect_psi_stunned("psi_stunned") ("psi_stunned") static
Referenced by game::prompt_dangerous_tile().
effect_ridden
const efftype_id effect_ridden("ridden") ("ridden") static
Referenced by game::place_player(), game::place_player_overmap(), game::validate_mounted_npcs(), and game::vertical_move().
effect_riding
const efftype_id effect_riding("riding") ("riding") static
Referenced by game::place_player(), game::place_player_overmap(), and game::validate_mounted_npcs().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by game::knockback(), and game::prompt_dangerous_tile().
effect_tetanus
const efftype_id effect_tetanus("tetanus") ("tetanus") static
Referenced by game::place_player().
effect_tied
const efftype_id effect_tied("tied") ("tied") static
Referenced by game::vertical_move().
effect_took_xanax
const efftype_id effect_took_xanax("took_xanax") ("took_xanax") static
Referenced by game::walk_move().
effect_transition_contacts
const efftype_id effect_transition_contacts("transition_contacts") ("transition_contacts") static
Referenced by game::use_computer().
effect_winded
const efftype_id effect_winded("winded") ("winded") static
Referenced by game::on_move_effects().
faction_no_faction
const faction_id faction_no_faction("no_faction") ("no_faction") static
Referenced by game::create_starting_npcs(), game::perhaps_add_random_npc(), and game::reset_npc_dispositions().
faction_your_followers
const faction_id faction_your_followers("your_followers") ("your_followers") static
Referenced by update_faction_api().
fuel_type_animal
const itype_id fuel_type_animal("animal") ("animal") static
Referenced by game::control_vehicle().
furn_f_rope_up
const furn_str_id furn_f_rope_up("f_rope_up") ("f_rope_up") static
Referenced by game::vertical_move().
furn_f_web_up
const furn_str_id furn_f_web_up("f_web_up") ("f_web_up") static
Referenced by game::vertical_move().
g
std::unique_ptr<game> g
Definition at line 382 of file game.cpp.
Referenced by anonymous_namespace{math_parser_diag.cpp}::_characters_nearby_eval(), anonymous_namespace{math_parser_diag.cpp}::_monsters_nearby_eval(), vehicle::act_on_map(), advanced_inventory::action_examine(), effect_on_condition::activate(), Character::activate_bionic(), Character::activate_mutation(), activity_on_turn_move_loot(), timed_event::actualize(), scrollingcombattext::add(), Character::add_bionic(), map::add_camp(), Character::add_faction_warning(), map::add_field(), tutorial_game::add_message(), options_manager::add_option_group(), add_summoned_mon(), map::add_vehicle_to_map(), npc::address_needs(), npc::alt_attack(), monster::anger_cub_threatened(), jmapgen_remove_npcs::apply(), jmapgen_npc::apply(), npc::assess_danger(), mission::assign(), Creature::auto_find_hostile_target(), iexamine::autodoc(), Pickup::autopickup(), vehicle::autopilot_patrol_check(), effect_on_conditions::avatar_death(), mongroup::avg_speed(), best_installer(), map::board_vehicle(), vehicle::break_off(), mattack::breathe(), vehicle::build_interact_menu(), map::build_obstacle_cache(), map::build_sunlight_cache(), iexamine::bulletin_board(), Character::burn_fuel(), game::bury_screen(), talker_avatar::buy_monster(), cardreader_examine_actor::call(), leap_actor::call(), melee_actor::call(), mattack::callblobs(), iuse::camera(), can_do_activity_there(), iuse::can_goo(), npc::can_move_to(), can_place_npc(), game::cancel_activity_query(), cancel_auto_move(), veh_interact::cant_do(), iexamine::chainfence(), Character::Character(), debug_menu::character_edit_menu(), construct::check_empty(), construct::check_empty_lite(), check_group_def(), Character::check_mount_is_spooked(), Character::check_mount_will_move(), construct::check_support_below(), choose_adjacent_highlight(), basecamp::choose_new_leader(), turn_handler::cleanup_at_end(), effect_on_conditions::clear(), game::climb_down_using(), anonymous_namespace{messages.cpp}::messages_impl::coalesce_messages(), game_menus::inv::common(), talk_function::companion_choose(), talk_function::companion_return(), complete_construction(), Character::conduct_blood_analysis(), Character::consume_effects(), item::contain_monster(), avatar::control_npc(), avatar::control_npc_menu(), iexamine::controls_gate(), mission_type::create(), editmap::game_draw_callback_t_container::create_or_get(), game::create_or_get_main_ui_adaptor(), editmap::create_or_get_ui_adaptor(), create_zone_callback(), vehicle_part::crew(), scrollingcombattext::cSCT::cSCT(), current_weather(), iexamine::curtains(), iexamine::cvdmachine(), vehicle::damage_direct(), mattack::darkman(), spell_effect::dash(), iuse::dbg_lux_meter(), Character::deactivate_bionic(), Character::deal_damage(), debug_menu::debug(), item::debug_info(), debug_menu::debug_menu_game_state(), deserialize(), game::despawn_nonlocal_monsters(), monster::die(), Character::die(), iuse::directional_hologram(), Character::disassemble(), Character::dismount(), Character::disp_info(), map::displace_vehicle(), advanced_inventory::display(), faction_manager::display(), overmap_ui::display(), game::display_lighting(), game::display_scent(), game::display_visibility(), veh_interact::do_assign_crew(), do_deathcam_action(), melee_actor::do_grab(), veh_interact::do_main_loop(), veh_interact::do_refill(), aim_activity_actor::do_turn(), glide_activity_actor::do_turn(), unload_loot_activity_actor::do_turn(), editmap::do_ui_invalidation(), iuse::dog_whistle(), construct::done_dig_grave(), iexamine::door_peephole(), mattack::doot(), dot(), anonymous_namespace{animation.cpp}::basic_animation::draw(), map::draw(), editmap_hilight::draw(), overmap_ui::draw(), overmap_ui::draw_ascii(), game::draw_async_anim(), debug_menu::draw_benchmark(), anonymous_namespace{animation.cpp}::draw_bullet_curses(), explosion_handler::draw_custom_explosion(), anonymous_namespace{animation.cpp}::draw_custom_explosion_curses(), draw_effects_summary(), explosion_handler::draw_explosion(), anonymous_namespace{animation.cpp}::draw_explosion_curses(), anonymous_namespace{animation.cpp}::draw_line_curses(), editmap::draw_main_ui_overlay(), game::draw_minimap(), overmap_ui::draw_om_sidebar(), overmap_ui::draw_overmap_chunk(), draw_override< furn_id >(), draw_override< ter_id >(), draw_override< trap_id >(), anonymous_namespace{animation.cpp}::draw_sct_curses(), mission_ui_impl::draw_selected_description(), draw_stats_summary(), target_ui::draw_terrain_overlay(), draw_trail(), map::drawsq(), mattack::dsa_drone_scan(), editmap::edit_fld(), eff_fun_hallu(), eff_fun_sleep(), eff_fun_teleglow(), explosion_handler::emp_blast(), talker_npc::enslave_mind(), item_location::impl::item_on_person::ensure_who_unpacked(), overmap::erase_npc(), mattack::evolve_kill_strike(), game::examine(), npc::execute_action(), anonymous_namespace{main.cpp}::exit_handler(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_allies(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_role_nearby(), conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), basecamp::fac(), anonymous_namespace{math_parser_diag.cpp}::faction_like_ass(), anonymous_namespace{math_parser_diag.cpp}::faction_like_eval(), anonymous_namespace{math_parser_diag.cpp}::faction_respect_ass(), anonymous_namespace{math_parser_diag.cpp}::faction_respect_eval(), anonymous_namespace{math_parser_diag.cpp}::faction_trust_ass(), anonymous_namespace{math_parser_diag.cpp}::faction_trust_eval(), computer_session::failure_manhacks(), computer_session::failure_secubots(), npc_factions::finalize(), Item_factory::finalize_item_blacklist(), monster::find_dragged_foe(), find_empty_neighbors(), options_manager::find_group(), npc::find_item(), talk_function::find_mount(), overmapbuffer::find_npc_by_unique_id(), aim_activity_actor::finish(), move_furniture_activity_actor::finish(), insert_item_activity_actor::finish(), disable_activity_actor::finish(), firstaid_activity_actor::finish(), glide_activity_actor::finish(), basecamp::finish_return(), avatar_action::fire_turret_manual(), iexamine::fireplace(), activity_handlers::fish_do_turn(), iuse::fish_trap_tick(), iuse::fishing_rod(), explosion_handler::flashbang(), mattack::flesh_tendril(), talk_function::follow(), item::food_info(), Character::forced_dismount(), game::forced_door_closing(), mattack::formblob(), suffer::from_asthma(), color_loader< ColorType >::from_rgb(), fungal_effects::fungalize(), iuse::fungicide(), mattack::fungus(), mattack::fungus_fortify(), mattack::fungus_sprout(), debug_menu::gen_sound(), map::generate(), map::generate_lightmap(), generic_multi_activity_do(), generic_multi_activity_handler(), generic_multi_activity_locations(), Character::get_active_moncams(), get_avatar_or_follower(), get_character_from_id(), Character::get_crafting_group(), Character::get_crafting_helpers(), weather_manager::get_cur_weather_gen(), get_delta_from_movement_action(), input_context::get_direction(), input_context::get_direction_rel_ms(), player_activity::get_distractions(), avatar::get_faction(), npc::get_faction(), conditional_t::get_get_dbl(), Character::get_hostile_creatures(), get_mission_om_origin(), get_movement_action_from_delta(), overmap::get_npcs(), item::get_old_owner_name(), item::get_owner_name(), vehicle::get_owner_name(), vehicle::get_passenger(), Character::get_path_avoid(), npc::get_path_avoid(), game::get_player_input(), Creature::get_summoner(), Character::get_targetable_creatures(), weather_manager::get_temperature(), overmapbuffer::get_travel_path(), Character::get_visible_creatures(), overmap_ui::get_weather_at_point(), MonsterGroupManager::GetMonsterGroup(), MonsterGroupManager::GetMonstersFromGroup(), talk_function::give_all_aid(), glare(), good_fishing_spot(), grenade_helper(), mattack::grow_vine(), spell_effect::guilt(), game::handle_action(), target_ui::handle_cursor_movement(), input_context::handle_input(), handle_key_blocking_activity(), item::handle_pickup_ownership(), vehicle::handle_potential_theft(), Character::hardcoded_effects(), iexamine::harvest_plant(), profession::has_initialized(), has_vehicle_control(), heat_item(), anonymous_namespace{animation.cpp}::hit_animation(), mattack::howl(), pointmenu_cb::impl_t::impl_t(), npc::import_and_clean(), debug_menu::import_folower(), suffer::in_sunlight(), talk_function::individual_mission(), heal_actor::info(), item::info(), tutorial_game::init(), main_menu::init_strings(), overmap::insert_npc(), exosuit_interact::insert_replace_activate_mod(), iexamine::intercom(), is_anyone_crafting(), mission::is_complete(), item::is_owned_by(), anonymous_namespace{animation.cpp}::is_point_visible(), mattack::jackson(), debug_menu::kill_area(), talk_function::leave(), iexamine::ledge(), trapfunc::ledge(), mattack::leech_spawner(), talk_function::lesser_give_all_aid(), firestarter_actor::light_mod(), target_ui::list_friendlies_in_lof(), avatar::load(), Character::load(), game::load(), effect_on_conditions::load_existing_character(), main_menu::load_game(), effect_on_conditions::load_new_character(), MonsterGroupManager::LoadMonsterGroup(), map::loadn(), avatar::longpull(), loot(), iuse::lux_meter(), main(), debug_menu::map_extra(), maple_tree_sap_container(), anonymous_namespace{messages.cpp}::message_exceeds_ttl(), mattack::mon_leech_evolution(), anonymous_namespace{do_turn.cpp}::monmove(), MonsterGroupManager::Monster2Group(), Character::mount_creature(), game::mouse_edge_scrolling_terrain(), monster::move(), npc::move(), avatar_action::move(), map::move_vehicle(), multicooker_hallu(), Character::mutate_towards(), npc::mutiny(), iuse::mycus(), iexamine::nanofab(), main_menu::new_character_tab(), diary::new_page(), eoc_events::notify(), npc::npc_dismount(), Character::on_hit(), monster::on_hit(), Character::on_hurt(), Character::on_item_acquire(), npc::on_load(), monster::on_move(), npc::on_move(), map::open_door(), gates::open_gate(), main_menu::opening_screen(), operator_present(), orient_part(), anonymous_namespace{do_turn.cpp}::overmap_npc_move(), display::overmap_tile_symbol_color(), iuse::pack_cbm(), mission_type::parse_funcs(), vehicle::part_collision(), iexamine::pedestal_wyrm(), tutorial_game::per_turn(), Character::perform_technique(), pick_follower(), npc::pick_up_item(), teleporter_list::place_avatar_overmap(), place_construction(), mission_start::place_deposit_box(), overmap::place_forests(), overmap::place_lakes(), overmap::place_mongroups(), mission_start::place_npc_software(), overmap::place_oceans(), npc::place_on_map(), overmap::place_swamps(), monster::plan(), mattack::plant(), iuse::play_game(), player_on_couch(), pldrive(), avatar_action::plthrow(), iuse::portable_game(), map_cursor::pos(), avatar::power_bionics(), debug_menu::print_npc_magic(), Character::process_bionic(), item::process_corpse(), effect_on_conditions::process_effect_on_conditions(), Character::process_effects(), monster::process_effects(), item::process_extinguish(), effect_on_conditions::process_reactivate(), sounds::process_sound_markers(), sounds::process_sounds(), item::process_temperature_rot(), projectile_attack(), monster::push_to(), iexamine::quern_examine(), query_consume_ownership(), effect_on_conditions::queue_effect_on_condition(), npc::randomize(), reach_attack(), Character::react_to_felt_pain(), Character::recalc_speed_bonus(), basecamp::recruit_evaluation(), basecamp::recruit_return(), veh_app_interact::refill(), anonymous_namespace{animation.cpp}::relative_view_pos(), item::release_monster(), game::reload_tileset(), vehicle::remote_controlled(), iuse::remoteveh(), iuse::remoteveh_tick(), iuse::remove_all_mods(), faction::remove_member(), debug_menu::mission_debug::remove_mission(), Character::remove_mutation(), remove_submap_turrets(), map::remove_trap(), effect_source::resolve_creature(), explosion_handler::resonance_cascade(), aim_activity_actor::restore_view(), mattack::resurrect(), reveal_route(), reveal_target(), spell_effect::revive(), game::revive_corpse(), spell_effect::revive_dormant(), iuse::robotcontrol(), rod_fish(), map::route(), target_ui::run(), display::safe_mode_text_color(), vehicle_prototype::save_vehicle_as_prototype(), mattack::science(), advanced_inventory::screen_relative_location(), pointmenu_cb::impl_t::select(), debug_menu::select_faction(), debug_menu::select_follower_to_export(), debug_menu::set_automove(), target_ui::set_cursor_pos(), npc::set_fac(), target_ui::set_last_target(), basecamp::set_owner(), basecamp::set_sort_points(), mission::set_target_to_mission_giver(), npc::set_unique_id(), iuse::sextant(), trapfunc::shadow(), map::shake_vehicle(), map::shift(), explosion_handler::shockwave(), options_manager::show(), live_view::show(), panel_manager::show_adm(), diary::show_diary_ui(), debug_menu::show_sound(), sinkhole_safety_roll(), sleep(), spell_effect::slime_split_on_death(), smash(), vehicle::smash(), mattack::smash(), trapfunc::snake(), spawn_animal(), debug_menu::spawn_artifact(), overmapbuffer::spawn_monster(), map::spawn_monsters_submap(), map::spawn_monsters_submap_group(), debug_menu::spawn_nested_mapgen(), debug_menu::spawn_npc(), game::spawn_npc(), spawn_spores(), mattack::split(), fungal_effects::spread_fungus_one_tile(), map::spread_gas(), standard_npc::standard_npc(), move_furniture_activity_actor::start(), activity_handlers::start_engines_finish(), talk_function::start_training_seminar(), Character::store(), display::sundial_text_color(), anonymous_namespace{monexamine.cpp}::swap(), swap_pos(), avatar_action::swim(), avatar::talk_to(), debug_menu::teleport_city(), debug_menu::teleport_long(), debug_menu::teleport_overmap(), debug_menu::teleport_short(), teleport::teleport_to_point(), anonymous_namespace{math_parser_diag.cpp}::time_until_eoc_eval(), mattack::tindalos_teleport(), iuse::toolmod_attach(), activity_handlers::train_finish(), iexamine::tree_maple(), mattack::triffid_heartbeat(), trapfunc::tripwire(), gun_actor::try_target(), monster::try_upgrade(), editmap::uber_draw_ter(), avatar_action::unload(), Character::update_bodytemp(), update_mapgen_function_json::update_map(), Character::update_needs(), editmap::update_view_with_help(), map::update_visibility_cache(), weather_manager::update_weather(), mattack::upgrade(), place_monster_iuse::use(), firestarter_actor::use(), vehicle::use_harness(), basecamp::validate_assignees(), game::validate_mounted_npcs(), item::validate_ownership(), display::vehicle_driven(), activity_handlers::vehicle_finish(), mattack::vine(), iuse::vortex(), iuse::water_purifier(), weather_forecast(), iuse::weather_tool(), Character::weight_carried_with_tweaks(), suffer::while_grabbed(), monster::will_move_to(), display::wind_text_color(), debug_menu::wishmonster(), monster::witness_thievery(), iexamine::workbench(), iexamine::workbench_internal(), basecamp::worker_assignment_ui(), npc::worker_downtime(), npc::would_take_that(), mission::wrap_up(), debug_menu::write_city_list(), effect_on_conditions::write_global_eocs_to_file(), memorial_logger::write_text_memorial(), game::draw_callback_t::~draw_callback_t(), and map::~map().
GROUP_BLACK_ROAD
const mongroup_id GROUP_BLACK_ROAD("GROUP_BLACK_ROAD") ("GROUP_BLACK_ROAD") static
Referenced by game::start_game().
harvest_drop_blood
const harvest_drop_type_id harvest_drop_blood("blood") ("blood") static
Referenced by butcher_submenu().
harvest_drop_offal
const harvest_drop_type_id harvest_drop_offal("offal") ("offal") static
Referenced by butcher_submenu().
harvest_drop_skin
const harvest_drop_type_id harvest_drop_skin("skin") ("skin") static
Referenced by butcher_submenu().
itype_battery
const itype_id itype_battery("battery") ("battery") static
Referenced by game::remoteveh().
itype_disassembly
const itype_id itype_disassembly("disassembly") ("disassembly") static
Referenced by add_disassemblables(), and game::butcher().
itype_grapnel
const itype_id itype_grapnel("grapnel") ("grapnel") static
Referenced by game::find_or_make_stairs().
itype_holybook_bible1
const itype_id itype_holybook_bible1("holybook_bible1") ("holybook_bible1") static
Referenced by game::bury_screen().
itype_holybook_bible2
const itype_id itype_holybook_bible2("holybook_bible2") ("holybook_bible2") static
Referenced by game::bury_screen().
itype_holybook_bible3
const itype_id itype_holybook_bible3("holybook_bible3") ("holybook_bible3") static
Referenced by game::bury_screen().
itype_manhole_cover
const itype_id itype_manhole_cover("manhole_cover") ("manhole_cover") static
Referenced by game::vertical_move().
itype_remotevehcontrol
const itype_id itype_remotevehcontrol("remotevehcontrol") ("remotevehcontrol") static
Referenced by game::remoteveh(), and game::setremoteveh().
itype_rope_30
const itype_id itype_rope_30("rope_30") ("rope_30") static
Referenced by game::find_or_make_stairs().
itype_swim_fins
const itype_id itype_swim_fins("swim_fins") ("swim_fins") static
Referenced by game::vertical_move().
itype_towel
const itype_id itype_towel("towel") ("towel") static
Referenced by game::water_affect_items().
itype_towel_wet
const itype_id itype_towel_wet("towel_wet") ("towel_wet") static
Referenced by game::water_affect_items().
json_flag_CLIMB_NO_LADDER
const json_character_flag json_flag_CLIMB_NO_LADDER("CLIMB_NO_LADDER") ("CLIMB_NO_LADDER") static
Referenced by game::vertical_move().
json_flag_CONVECTS_TEMPERATURE
const flag_id json_flag_CONVECTS_TEMPERATURE("CONVECTS_TEMPERATURE") ("CONVECTS_TEMPERATURE") static
Referenced by get_convection_temperature().
json_flag_GRAB
const json_character_flag json_flag_GRAB("GRAB") ("GRAB") static
Referenced by game::fling_creature().
json_flag_HYPEROPIC
const json_character_flag json_flag_HYPEROPIC("HYPEROPIC") ("HYPEROPIC") static
Referenced by game::use_computer().
json_flag_INFECTION_IMMUNE
const json_character_flag json_flag_INFECTION_IMMUNE("INFECTION_IMMUNE") ("INFECTION_IMMUNE") static
Referenced by game::place_player().
json_flag_LEVITATION
const flag_id json_flag_LEVITATION("LEVITATION") ("LEVITATION") static
Referenced by game::get_dangerous_tile().
json_flag_NO_RELOAD
const flag_id json_flag_NO_RELOAD("NO_RELOAD") ("NO_RELOAD") static
Referenced by rate_action_insert().
json_flag_NYCTOPHOBIA
const json_character_flag json_flag_NYCTOPHOBIA("NYCTOPHOBIA") ("NYCTOPHOBIA") static
Referenced by game::walk_move().
json_flag_SPLINT
const flag_id json_flag_SPLINT("SPLINT") ("SPLINT") static
Referenced by game::npc_menu().
json_flag_WALL_CLING
const json_character_flag json_flag_WALL_CLING("WALL_CLING") ("WALL_CLING") static
Referenced by game::vertical_move().
json_flag_WEB_RAPPEL
const json_character_flag json_flag_WEB_RAPPEL("WEB_RAPPEL") ("WEB_RAPPEL") static
Referenced by game::find_or_make_stairs(), and game::vertical_move().
material_glass
const material_id material_glass("glass") ("glass") static
Referenced by game::forced_door_closing().
MOD_INFORMATION_dda
const mod_id MOD_INFORMATION_dda("dda") ("dda") static
mon_manhack
const mtype_id mon_manhack("mon_manhack") ("mon_manhack") static
Referenced by game::disable_robot().
npc_template_cyborg_rescued
const string_id<npc_template> npc_template_cyborg_rescued("cyborg_rescued") ("cyborg_rescued") static
Referenced by game::save_cyborg().
overmap_special_world
const overmap_special_id overmap_special_world("world") ("world") static
Referenced by game::start_game().
proficiency_prof_parkour
const proficiency_id proficiency_prof_parkour("prof_parkour") ("prof_parkour") static
Referenced by game::place_player(), game::slip_down_chance(), and game::walk_move().
proficiency_prof_wound_care
const proficiency_id proficiency_prof_wound_care("prof_wound_care") ("prof_wound_care") static
Referenced by game::npc_menu().
proficiency_prof_wound_care_expert
const proficiency_id proficiency_prof_wound_care_expert("prof_wound_care_expert") ("prof_wound_care_expert") static
Referenced by game::npc_menu().
qual_BUTCHER
const quality_id qual_BUTCHER("BUTCHER") ("BUTCHER") static
Referenced by game::butcher(), butcher_submenu(), and game::place_player().
qual_CUT_FINE
const quality_id qual_CUT_FINE("CUT_FINE") ("CUT_FINE") static
Referenced by game::butcher(), and butcher_submenu().
skill_dodge
const skill_id skill_dodge("dodge") ("dodge") static
Referenced by game::find_or_make_stairs().
skill_firstaid
const skill_id skill_firstaid("firstaid") ("firstaid") static
Referenced by game::npc_menu().
skill_gun
const skill_id skill_gun("gun") ("gun") static
Referenced by rate_action_use().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by get_fire_fuel_string().
species_PLANT
const species_id species_PLANT("PLANT") ("PLANT") static
Referenced by game::mon_info_update().
ter_t_elevator
const ter_str_id ter_t_elevator("t_elevator") ("t_elevator") static
Referenced by game::find_or_make_stairs().
ter_t_grave_new
const ter_str_id ter_t_grave_new("t_grave_new") ("t_grave_new") static
Referenced by game::print_graffiti_info().
ter_t_lava
const ter_str_id ter_t_lava("t_lava") ("t_lava") static
Referenced by game::find_or_make_stairs().
ter_t_manhole
const ter_str_id ter_t_manhole("t_manhole") ("t_manhole") static
Referenced by game::vertical_move().
ter_t_manhole_cover
const ter_str_id ter_t_manhole_cover("t_manhole_cover") ("t_manhole_cover") static
Referenced by game::find_or_make_stairs(), and game::vertical_move().
ter_t_pit
const ter_str_id ter_t_pit("t_pit") ("t_pit") static
Referenced by game::print_fields_info().
ter_t_pit_shallow
const ter_str_id ter_t_pit_shallow("t_pit_shallow") ("t_pit_shallow") static
Referenced by game::print_fields_info().
trait_BADKNEES
const trait_id trait_BADKNEES("BADKNEES") ("BADKNEES") static
Referenced by game::slip_down_chance().
trait_CANNIBAL
const trait_id trait_CANNIBAL("CANNIBAL") ("CANNIBAL") static
Referenced by game::bury_screen().
trait_CENOBITE
const trait_id trait_CENOBITE("CENOBITE") ("CENOBITE") static
Referenced by game::grabbed_furn_move().
trait_ILLITERATE
const trait_id trait_ILLITERATE("ILLITERATE") ("ILLITERATE") static
Referenced by game::place_player(), game::print_terrain_info(), and game::use_computer().
trait_INATTENTIVE
const trait_id trait_INATTENTIVE("INATTENTIVE") ("INATTENTIVE") static
Referenced by game::list_monsters().
trait_INFRESIST
const trait_id trait_INFRESIST("INFRESIST") ("INFRESIST") static
Referenced by game::place_player().
trait_LEG_TENT_BRACE
const trait_id trait_LEG_TENT_BRACE("LEG_TENT_BRACE") ("LEG_TENT_BRACE") static
Referenced by game::knockback(), and game::walk_move().
trait_M_DEFENDER
const trait_id trait_M_DEFENDER("M_DEFENDER") ("M_DEFENDER") static
Referenced by game::mon_info_update().
trait_M_IMMUNE
const trait_id trait_M_IMMUNE("M_IMMUNE") ("M_IMMUNE") static
Referenced by game::walk_move().
trait_MASOCHIST
const trait_id trait_MASOCHIST("MASOCHIST") ("MASOCHIST") static
Referenced by game::grabbed_furn_move().
trait_MASOCHIST_MED
const trait_id trait_MASOCHIST_MED("MASOCHIST_MED") ("MASOCHIST_MED") static
Referenced by game::grabbed_furn_move().
trait_NPC_STARTING_NPC
const trait_id trait_NPC_STARTING_NPC("NPC_STARTING_NPC") ("NPC_STARTING_NPC") static
Referenced by game::create_starting_npcs(), game::disp_NPCs(), and game::perhaps_add_random_npc().
trait_NPC_STATIC_NPC
const trait_id trait_NPC_STATIC_NPC("NPC_STATIC_NPC") ("NPC_STATIC_NPC") static
Referenced by game::disp_NPCs(), and game::perhaps_add_random_npc().
trait_PROF_CHURL
const trait_id trait_PROF_CHURL("PROF_CHURL") ("PROF_CHURL") static
Referenced by game::check_safe_mode_allowed().
trait_PSYCHOPATH
const trait_id trait_PSYCHOPATH("PSYCHOPATH") ("PSYCHOPATH") static
Referenced by game::bury_screen().
trait_THICKSKIN
const trait_id trait_THICKSKIN("THICKSKIN") ("THICKSKIN") static
Referenced by game::place_player().
trait_VINES2
const trait_id trait_VINES2("VINES2") ("VINES2") static
Referenced by game::find_or_make_stairs().
trait_VINES3
const trait_id trait_VINES3("VINES3") ("VINES3") static
Referenced by game::find_or_make_stairs().
trait_WAYFARER
const trait_id trait_WAYFARER("WAYFARER") ("WAYFARER") static
Referenced by game::place_player().
uistate
uistatedata uistate
Definition at line 385 of file game.cpp.
Referenced by advanced_inventory::action_examine(), string_input_popup::add_to_history(), cancel_aim_processing(), check_items_newness(), anonymous_namespace{iexamine.cpp}::atm_menu::choose_option(), create_advanced_inv(), inventory_column::cycle_hide_override(), debug_menu::debug(), overmap_ui::display(), ui::omap::display_hordes(), ui::omap::display_visible_weather(), ui::omap::display_weather(), game::do_regular_action(), overmap_ui::draw_ascii(), draw_bionics_titlebar(), inventory_selector::draw_header(), overmap_ui::draw_om_sidebar(), editmap::edit(), eff_fun_teleglow(), recipe_subset::empty_category(), unload_selector::execute(), craft_command::execute(), expand_recipes(), recipe_subset::expanded(), recipe_subset::favorite(), hacking_activity_actor::finish(), suffer::from_asthma(), distraction_manager::get_configurable_distractions(), player_activity::get_distractions(), Character::hardcoded_effects(), recipe_subset::hidden(), unload_selector::hint_string(), inventory_column::inventory_column(), game::list_items(), game::load(), mark_items_read_rec(), game::mon_info_update(), Character::mutate_towards(), nested_toggle(), Character::on_hurt(), inventory_selector::on_input(), inventory_multiselector::on_input(), anonymous_namespace{bionics_ui.cpp}::bionic_sort_less::operator()(), iexamine::pay_gas(), overmap_ui::place_ter_or_special(), avatar::power_bionics(), sounds::process_sound_markers(), Character::react_to_felt_pain(), inventory_selector::reassign_custom_invlets(), recipe_subset::recent(), Character::remove_mutation(), anonymous_namespace{iexamine.cpp}::atm_menu::reset(), recipe::result_name(), game::save(), overmap_ui::search(), select_crafter_and_crafting_recipe(), advanced_inv_area::set_container_position(), string_input_popup::show_history(), avatar::talk_to(), string_input_popup::update_input_history(), weather_manager::update_weather(), suffer::while_grabbed(), debug_menu::wishitem(), debug_menu::wishmonster(), and debug_menu::wishmutate().
zone_type_LOOT_CUSTOM
const zone_type_id zone_type_LOOT_CUSTOM("LOOT_CUSTOM") ("LOOT_CUSTOM") static
Referenced by game::zones_manager().
zone_type_NO_AUTO_PICKUP
const zone_type_id zone_type_NO_AUTO_PICKUP("NO_AUTO_PICKUP") ("NO_AUTO_PICKUP") static
Referenced by game::place_player().