Cataclysm DDA: src/game_inventory.cpp File Reference
game_inventory.cpp File Reference
#include "game_inventory.h"
#include <algorithm>
#include <bitset>
#include <cstddef>
#include <functional>
#include <iterator>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <vector>
#include "activity_type.h"
#include "activity_actor_definitions.h"
#include "avatar.h"
#include "bionics.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "color.h"
#include "cursesdef.h"
#include "damage.h"
#include "debug.h"
#include "display.h"
#include "enums.h"
#include "flag.h"
#include "game.h"
#include "input.h"
#include "input_context.h"
#include "inventory.h"
#include "inventory_ui.h"
#include "item.h"
#include "item_location.h"
#include "item_pocket.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "npctrade.h"
#include "options.h"
#include "output.h"
#include "pimpl.h"
#include "point.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "requirements.h"
#include "ret_val.h"
#include "skill.h"
#include "stomach.h"
#include "string_formatter.h"
#include "translations.h"
#include "type_id.h"
#include "ui_manager.h"
#include "units.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "vitamin.h"
Classes
class armor_inventory_preset
class wear_inventory_preset
class take_off_inventory_preset
class liquid_inventory_selector_preset
class pickup_inventory_preset
class disassemble_inventory_preset
class comestible_inventory_preset
class comestible_filtered_inventory_preset
class activatable_inventory_preset
class gunmod_inventory_preset
class gunmod_remove_inventory_preset
class ereader_inventory_preset
class read_inventory_preset
class ebookread_inventory_preset
class steal_inventory_preset
class weapon_inventory_preset
class holster_inventory_preset
class saw_barrel_inventory_preset
class saw_stock_inventory_preset
class attach_molle_inventory_preset
class attach_veh_tool_inventory_preset
class salvage_inventory_preset
class repair_inventory_preset
class smokable_selector_preset
class bionic_install_preset
class bionic_install_surgeon_preset
class change_sprite_inventory_preset
class select_ammo_inventory_preset
Namespaces
anonymous_namespace{game_inventory.cpp}
Typedefs
using item_filter = std::function< bool(const item &)>
using item_location_filter = std::function< bool(const item_location &)>
Functions
std::string anonymous_namespace{game_inventory.cpp}::good_bad_none (int value)
std::string anonymous_namespace{game_inventory.cpp}::highlight_good_bad_none (int value)
static item_location_filter convert_filter (const item_filter &filter)
static item_location inv_internal (Character &u, const inventory_selector_preset &preset, const std::string &title, int radius, const std::string &none_message, const std::string &hint=std::string(), item_location container=item_location())
static drop_locations inv_internal_multi (Character &u, const inventory_selector_preset &preset, const std::string &title, int radius, const std::string &none_message, const std::string &hint=std::string(), item_location container=item_location())
static std::string get_consume_needs_hint (Character &you)
static bool valid_unload_container (const item_location &container)
static std::string get_repair_hint (const Character &you, const repair_item_actor *actor, const item *main_tool)
static item_location autodoc_internal (Character &you, Character &patient, const inventory_selector_preset &preset, int radius, bool surgeon=false)
Variables
static const activity_id ACT_CONSUME_DRINK_MENU ("ACT_CONSUME_DRINK_MENU")
static const activity_id ACT_CONSUME_FOOD_MENU ("ACT_CONSUME_FOOD_MENU")
static const activity_id ACT_CONSUME_MEDS_MENU ("ACT_CONSUME_MEDS_MENU")
static const activity_id ACT_EAT_MENU ("ACT_EAT_MENU")
static const bionic_id bio_fitnessband ("bio_fitnessband")
static const bionic_id bio_painkiller ("bio_painkiller")
static const flag_id json_flag_CALORIES_INTAKE ("CALORIES_INTAKE")
static const itype_id itype_fitness_band ("fitness_band")
static const json_character_flag json_flag_MANUAL_CBM_INSTALLATION ("MANUAL_CBM_INSTALLATION")
static const json_character_flag json_flag_PAIN_IMMUNE ("PAIN_IMMUNE")
static const quality_id qual_ANESTHESIA ("ANESTHESIA")
static const requirement_id requirement_data_anesthetic ("anesthetic")
static const trait_id trait_DEBUG_BIONICS ("DEBUG_BIONICS")
static const trait_id trait_SAPROPHAGE ("SAPROPHAGE")
static const trait_id trait_SAPROVORE ("SAPROVORE")
Typedef Documentation
item_filter
using item_filter = std::function<bool (const item &)>
Definition at line 84 of file game_inventory.cpp.
item_location_filter
using item_location_filter = std::function<bool (const item_location &)>
Definition at line 85 of file game_inventory.cpp.
Function Documentation
autodoc_internal()
static item_location autodoc_internal (Character & you, Character & patient, const inventory_selector_preset & preset, int radius, bool surgeon = false) static
Definition at line 2490 of file game_inventory.cpp.
 {
     inventory_pick_selector inv_s( you, preset );
     std::string hint;
     int drug_count = 0;
     if( !surgeon ) {//surgeon use their own anesthetic, player just need money
         if( patient.has_flag( json_flag_PAIN_IMMUNE ) ) {
             hint = _( "<color_yellow>Patient has deadened nerves.  Anesthesia unneeded.</color>" );
         } else if( patient.has_bionic( bio_painkiller ) ) {
             hint = _( "<color_yellow>Patient has Sensory Dulling CBM installed.  Anesthesia unneeded.</color>" );
         } else {
             const inventory &crafting_inv = you.crafting_inventory();
             std::vector<const item *> a_filter = crafting_inv.items_with( []( const item & it ) {
                 return it.has_quality( qual_ANESTHESIA );
             } );
             for( const item *anesthesia_item : a_filter ) {
                 if( anesthesia_item->ammo_remaining() >= 1 ) {
                     drug_count += anesthesia_item->ammo_remaining();
                 }
             }
             hint = string_format( _( "<color_yellow>Available anesthetic: %i mL</color>" ), drug_count );
         }
     }
     std::vector<const item *> install_programs = patient.crafting_inventory().items_with( [](
                 const item & it ) -> bool { return it.has_flag( flag_BIONIC_INSTALLATION_DATA ); } );
     if( !install_programs.empty() ) {
         hint += string_format(
                     _( "\n<color_light_green>Found bionic installation data.  Affected CBMs are marked with an asterisk.</color>" ) );
     }
     inv_s.set_title( string_format( _( "Bionic installation patient: %s" ), patient.get_name() ) );
     inv_s.set_hint( hint );
     inv_s.set_display_stats( false );
     do {
         you.inv->restack( you );
         inv_s.clear_items();
         inv_s.add_character_items( you );
         if( you.getID() != patient.getID() ) {
             inv_s.add_character_items( patient );
         }
         inv_s.add_nearby_items( radius );
         if( inv_s.empty() ) {
             popup( _( "You don't have any bionics to install." ), PF_GET_KEY );
             return item_location();
         }
         item_location location = inv_s.execute();
         return location;
     } while( true );
 }
References _, inventory_selector::add_character_items(), inventory_selector::add_nearby_items(), bio_painkiller, inventory_selector::clear_items(), Character::crafting_inventory(), inventory_selector::empty(), inventory_pick_selector::execute(), flag_BIONIC_INSTALLATION_DATA, Character::get_name(), Character::getID(), Character::has_bionic(), item::has_flag(), Character::has_flag(), visitable::has_quality(), Character::inv, visitable::items_with(), json_flag_PAIN_IMMUNE, location, PF_GET_KEY, popup(), qual_ANESTHESIA, inventory_selector::set_display_stats(), inventory_selector::set_hint(), inventory_selector::set_title(), and string_format().
Referenced by game_menus::inv::install_bionic().
convert_filter()
static item_location_filter convert_filter (const item_filter & filter) static
Definition at line 121 of file game_inventory.cpp.
 {
     return [ &filter ]( const item_location & loc ) {
         return filter( *loc );
     };
 }
References filter.
Referenced by game::inv_map_splice(), and game_menus::inv::titled_filter_menu().
get_consume_needs_hint()
static std::string get_consume_needs_hint (Character & you) static
Definition at line 896 of file game_inventory.cpp.
 {
     std::string hint = std::string();
     auto desc = display::hunger_text_color( you );
     hint.append( string_format( "%s %s", _( "Food:" ), colorize( desc.first, desc.second ) ) );
     hint.append( string_format( " %s ", LINE_XOXO_S ) );
     desc = display::thirst_text_color( you );
     hint.append( string_format( "%s %s", pgettext( "inventory", "Drink:" ),
                                 colorize( desc.first, desc.second ) ) );
     hint.append( string_format( " %s ", LINE_XOXO_S ) );
     desc = display::pain_text_color( you );
     hint.append( string_format( "%s %s", _( "Pain:" ), colorize( desc.first, desc.second ) ) );
     hint.append( string_format( " %s ", LINE_XOXO_S ) );
     desc = display::sleepiness_text_color( you );
     hint.append( string_format( "%s %s", _( "Rest:" ), colorize( desc.first, desc.second ) ) );
     hint.append( string_format( " %s ", LINE_XOXO_S ) );
     hint.append( string_format( "%s %s", _( "Weight:" ), display::weight_string( you ) ) );
     hint.append( string_format( " %s ", LINE_XOXO_S ) );
     int kcal_ingested_today = you.as_avatar()->get_daily_ingested_kcal( false );
     int kcal_ingested_yesterday = you.as_avatar()->get_daily_ingested_kcal( true );
     int kcal_spent_today = you.as_avatar()->get_daily_spent_kcal( false );
     int kcal_spent_yesterday = you.as_avatar()->get_daily_spent_kcal( true );
     bool has_fitness_band =  you.is_wearing( itype_fitness_band ) || you.has_bionic( bio_fitnessband );
     bool has_tracker = has_fitness_band || you.cache_has_item_with( json_flag_CALORIES_INTAKE );
     std::string kcal_estimated_intake;
     if( kcal_ingested_today == 0 ) {
         //~ kcal_estimated_intake
         kcal_estimated_intake = _( "none " );
     } else if( kcal_ingested_today < 0.2 * you.base_bmr() ) {
         //~ kcal_estimated_intake
         kcal_estimated_intake = _( "minimal " );
     } else if( kcal_ingested_today < 0.5 * you.base_bmr() ) {
         //~ kcal_estimated_intake
         kcal_estimated_intake = _( "low " );
     } else if( kcal_ingested_today < 1.0 * you.base_bmr() ) {
         //~ kcal_estimated_intake
         kcal_estimated_intake = _( "moderate " );
     } else if( kcal_ingested_today < 1.5 * you.base_bmr() ) {
         //~ kcal_estimated_intake
         kcal_estimated_intake = _( "high " );
     } else if( kcal_ingested_today < 2.0 * you.base_bmr() ) {
         //~ kcal_estimated_intake
         kcal_estimated_intake = _( "very high " );
     } else {
         //~ kcal_estimated_intake
         kcal_estimated_intake = _( "huge " );
     }
     hint.append( "\n" );
     if( has_tracker ) {
         hint.append( _( "Consumed: " ) );
         desc = std::make_pair( string_format( _( "%d kcal " ), kcal_ingested_today ), c_white );
         hint.append( string_format( "%s %s", _( "Today:" ), colorize( desc.first, desc.second ) ) );
         desc = std::make_pair( string_format( _( "%d kcal " ), kcal_ingested_yesterday ), c_white );
         hint.append( string_format( "%s %s", _( "Yesterday:" ), colorize( desc.first, desc.second ) ) );
     } else {
         hint.append( _( "Consumed today (kcal): " ) );
         hint.append( colorize( kcal_estimated_intake, c_white ) );
     }
     if( has_fitness_band ) {
         hint.append( string_format( " %s ", LINE_XOXO_S ) );
         hint.append( _( "Spent: " ) );
         desc = std::make_pair( string_format( _( "%d kcal " ), kcal_spent_today ), c_white );
         hint.append( string_format( "%s %s", _( "Today:" ), colorize( desc.first, desc.second ) ) );
         desc = std::make_pair( string_format( _( "%d kcal " ), kcal_spent_yesterday ), c_white );
         hint.append( string_format( "%s %s", _( "Yesterday:" ), colorize( desc.first, desc.second ) ) );
     }
     // add info about vitamins as well
     hint.append( _( "Vitamin Intake: " ) );
     for( const auto &v : vitamin::all() ) {
         if( v.first->type() != vitamin_type::VITAMIN || v.first->has_flag( "OBSOLETE" ) ) {
             //skip non vitamins
             continue;
         }
         const int &guessed_daily_vit_quantity = you.get_daily_vitamin( v.first, false );
         const int &vit_percent = you.vitamin_RDA( v.first, guessed_daily_vit_quantity );
         if( has_tracker ) {
             desc = std::make_pair( string_format( _( "%s: %d%%.  " ), v.second.name(), vit_percent ), c_white );
         } else {
             if( vit_percent >= 90 ) {
                 desc = std::make_pair( string_format( _( "%s: %s.  " ), v.second.name(), _( "plenty" ) ), c_white );
             } else if( vit_percent >= 50 ) {
                 desc = std::make_pair( string_format( _( "%s: %s.  " ), v.second.name(), _( "some" ) ), c_white );
             } else if( vit_percent > 0 ) {
                 desc = std::make_pair( string_format( _( "%s: %s.  " ), v.second.name(), _( "little" ) ), c_white );
             } else {
                 desc = std::make_pair( string_format( _( "%s: %s.  " ), v.second.name(), _( "none" ) ), c_white );
             }
         }
         hint.append( colorize( desc.first, desc.second ) );
     }
     return hint;
 }
References _, vitamin::all(), Creature::as_avatar(), Character::base_bmr(), bio_fitnessband, c_white, Character::cache_has_item_with(), colorize(), avatar::get_daily_ingested_kcal(), avatar::get_daily_spent_kcal(), Character::get_daily_vitamin(), Character::has_bionic(), display::hunger_text_color(), Character::is_wearing(), itype_fitness_band, json_flag_CALORIES_INTAKE, LINE_XOXO_S, display::pain_text_color(), pgettext, display::sleepiness_text_color(), string_format(), display::thirst_text_color(), VITAMIN, Character::vitamin_RDA(), and display::weight_string().
Referenced by game_menus::inv::consume(), game_menus::inv::consume_drink(), game_menus::inv::consume_food(), and game_menus::inv::consume_meds().
get_repair_hint()
static std::string get_repair_hint (const Character & you, const repair_item_actor * actor, const item * main_tool) static
Definition at line 2095 of file game_inventory.cpp.
 {
     std::string hint = std::string();
     hint.append( string_format( _( "Tool: <color_cyan>%s</color>" ), main_tool->display_name() ) );
     hint.append( string_format( " | " ) );
     hint.append( string_format( _( "Skill used: <color_cyan>%s (%d)</color>" ),
                                 actor->used_skill.obj().name(), static_cast<int>( you.get_skill_level( actor->used_skill ) ) ) );
     return hint;
 }
References _, item::display_name(), Character::get_skill_level(), Skill::name(), string_id< T >::obj(), string_format(), and repair_item_actor::used_skill.
Referenced by game_menus::inv::repair().
inv_internal()
static item_location inv_internal (Character & u, const inventory_selector_preset & preset, const std::string & title, int radius, const std::string & none_message, const std::string & hint = std::string(), item_location container = item_location()) static
Definition at line 128 of file game_inventory.cpp.
 {
     inventory_pick_selector inv_s( u, preset );
     inv_s.set_title( title );
     inv_s.set_hint( hint );
     inv_s.set_display_stats( false );
     const std::vector<activity_id> consuming {
         ACT_EAT_MENU,
         ACT_CONSUME_FOOD_MENU,
         ACT_CONSUME_DRINK_MENU,
         ACT_CONSUME_MEDS_MENU };
     u.inv->restack( u );
     inv_s.clear_items();
     if( container ) {
         // Only look inside the container.
         inv_s.add_contained_items( container );
     } else {
         // Default behavior.
         inv_s.add_character_items( u );
         inv_s.add_nearby_items( radius );
     }
     if( u.has_activity( consuming ) ) {
         if( !u.activity.str_values.empty() ) {
             inv_s.set_filter( u.activity.str_values[0] );
         }
         // Set position after filter to keep cursor at the right position
         bool position_set = false;
         if( !u.activity.targets.empty() ) {
             bool const hidden = u.activity.values.size() >= 3 && static_cast<bool>( u.activity.values[2] );
             position_set = inv_s.highlight_one_of( u.activity.targets, hidden );
             if( !position_set && hidden ) {
                 position_set = inv_s.highlight_one_of( u.activity.targets );
             }
         }
         if( !position_set && u.activity.values.size() >= 2 ) {
             inv_s.highlight_position( std::make_pair( u.activity.values[0], u.activity.values[1] ) );
         }
     }
     if( inv_s.empty() ) {
         const std::string msg = none_message.empty()
                                 ? _( "You don't have the necessary item at hand." )
                                 : none_message;
         popup( msg, PF_GET_KEY );
         return item_location();
     }
     item_location location = inv_s.execute();
     if( u.has_activity( consuming ) ) {
         inventory_entry const &e = inv_s.get_highlighted();
         bool const collated = e.is_collation_entry();
         u.activity.values.clear();
         const auto init_pair = inv_s.get_highlighted_position();
         u.activity.values.push_back( init_pair.first );
         u.activity.values.push_back( init_pair.second );
         u.activity.values.push_back( collated );
         u.activity.str_values.clear();
         u.activity.str_values.emplace_back( inv_s.get_filter() );
         u.activity.targets = collated ? std::vector<item_location> { location, inv_s.get_collation_next() }
                              :
                              inv_s.get_highlighted().locations;
     }
     return location;
 }
References _, ACT_CONSUME_DRINK_MENU, ACT_CONSUME_FOOD_MENU, ACT_CONSUME_MEDS_MENU, ACT_EAT_MENU, inventory_selector::add_character_items(), inventory_selector::add_contained_items(), inventory_selector::add_nearby_items(), inventory_selector::clear_items(), inventory_selector::empty(), inventory_pick_selector::execute(), inventory_selector::get_collation_next(), inventory_selector::get_filter(), inventory_selector::get_highlighted(), inventory_selector::get_highlighted_position(), inventory_selector::highlight_one_of(), inventory_selector::highlight_position(), cataimgui::init_pair(), inventory_entry::is_collation_entry(), location, inventory_entry::locations, PF_GET_KEY, popup(), inventory_selector::set_display_stats(), inventory_selector::set_filter(), inventory_selector::set_hint(), inventory_selector::set_title(), music::title, and u.
Referenced by game_menus::inv::change_sprite(), game_menus::inv::consume(), game_menus::inv::consume_drink(), game_menus::inv::consume_food(), game_menus::inv::consume_meds(), game_menus::inv::container_for(), game_menus::inv::disassemble(), game_menus::inv::ereader_to_use(), game_menus::inv::gun_to_modify(), game::inv_map_splice(), game_menus::inv::molle_attach(), game_menus::inv::read(), game_menus::inv::repair(), game_menus::inv::salvage(), game_menus::inv::saw_barrel(), game_menus::inv::saw_stock(), game_menus::inv::steal(), game_menus::inv::take_off(), game_menus::inv::titled_filter_menu(), game_menus::inv::titled_menu(), game_menus::inv::use(), game_menus::inv::veh_tool_attach(), game_menus::inv::wear(), and game_menus::inv::wield().
inv_internal_multi()
static drop_locations inv_internal_multi (Character & u, const inventory_selector_preset & preset, const std::string & title, int radius, const std::string & none_message, const std::string & hint = std::string(), item_location container = item_location()) static
Definition at line 205 of file game_inventory.cpp.
 {
     inventory_multiselector inv_s( u, preset );
     inv_s.set_title( title );
     inv_s.set_hint( hint );
     inv_s.set_display_stats( false );
     u.inv->restack( u );
     inv_s.clear_items();
     if( container ) {
         // Only look inside the container.
         inv_s.add_contained_items( container );
     } else {
         // Default behavior.
         inv_s.add_character_items( u );
         inv_s.add_nearby_items( radius );
     }
     if( inv_s.empty() ) {
         const std::string msg = none_message.empty()
                                 ? _( "You don't have the necessary item at hand." )
                                 : none_message;
         popup( msg, PF_GET_KEY );
         return drop_locations();
     }
     return inv_s.execute();
 }
References _, inventory_selector::add_character_items(), inventory_selector::add_contained_items(), inventory_selector::add_nearby_items(), inventory_selector::clear_items(), inventory_selector::empty(), inventory_multiselector::execute(), PF_GET_KEY, popup(), inventory_selector::set_display_stats(), inventory_selector::set_hint(), inventory_selector::set_title(), music::title, and u.
Referenced by game_menus::inv::titled_multi_filter_menu().
valid_unload_container()
static bool valid_unload_container (const item_location & container) static
Definition at line 1832 of file game_inventory.cpp.
 {
     // Item must be a container.
     if( !container->is_container() ) {
         return false;
     }
     // Item must be able to be unloaded
     if( container->has_flag( flag_NO_UNLOAD ) ) {
         return false;
     }
     // Container must contain at least one item
     if( container->empty_container() ) {
         return false;
     }
     // Not all contents should not be liquid, gas or plasma
     if( container->contains_no_solids() ) {
         return false;
     }
     return true;
 }
References item::contains_no_solids(), item::empty_container(), flag_NO_UNLOAD, item::has_flag(), and item::is_container().
Referenced by game_menus::inv::unload_container().
Variable Documentation
ACT_CONSUME_DRINK_MENU
const activity_id ACT_CONSUME_DRINK_MENU("ACT_CONSUME_DRINK_MENU") ("ACT_CONSUME_DRINK_MENU") static
Referenced by game_menus::inv::consume_drink(), and inv_internal().
ACT_CONSUME_FOOD_MENU
const activity_id ACT_CONSUME_FOOD_MENU("ACT_CONSUME_FOOD_MENU") ("ACT_CONSUME_FOOD_MENU") static
Referenced by game_menus::inv::consume_food(), and inv_internal().
ACT_CONSUME_MEDS_MENU
const activity_id ACT_CONSUME_MEDS_MENU("ACT_CONSUME_MEDS_MENU") ("ACT_CONSUME_MEDS_MENU") static
Referenced by game_menus::inv::consume_meds(), and inv_internal().
ACT_EAT_MENU
const activity_id ACT_EAT_MENU("ACT_EAT_MENU") ("ACT_EAT_MENU") static
Referenced by game_menus::inv::consume(), and inv_internal().
bio_fitnessband
const bionic_id bio_fitnessband("bio_fitnessband") ("bio_fitnessband") static
Referenced by get_consume_needs_hint().
bio_painkiller
const bionic_id bio_painkiller("bio_painkiller") ("bio_painkiller") static
Referenced by autodoc_internal().
itype_fitness_band
const itype_id itype_fitness_band("fitness_band") ("fitness_band") static
Referenced by get_consume_needs_hint().
json_flag_CALORIES_INTAKE
const flag_id json_flag_CALORIES_INTAKE("CALORIES_INTAKE") ("CALORIES_INTAKE") static
Referenced by get_consume_needs_hint().
json_flag_MANUAL_CBM_INSTALLATION
const json_character_flag json_flag_MANUAL_CBM_INSTALLATION("MANUAL_CBM_INSTALLATION") ("MANUAL_CBM_INSTALLATION") static
Referenced by bionic_install_preset::get_failure_chance(), and bionic_install_surgeon_preset::get_failure_chance().
json_flag_PAIN_IMMUNE
const json_character_flag json_flag_PAIN_IMMUNE("PAIN_IMMUNE") ("PAIN_IMMUNE") static
Referenced by autodoc_internal().
qual_ANESTHESIA
const quality_id qual_ANESTHESIA("ANESTHESIA") ("ANESTHESIA") static
Referenced by autodoc_internal().
requirement_data_anesthetic
const requirement_id requirement_data_anesthetic("anesthetic") ("anesthetic") static
Referenced by bionic_install_preset::get_anesth_amount(), and bionic_install_preset::get_denial().
trait_DEBUG_BIONICS
const trait_id trait_DEBUG_BIONICS("DEBUG_BIONICS") ("DEBUG_BIONICS") static
Referenced by bionic_install_preset::get_failure_chance(), and bionic_install_surgeon_preset::get_failure_chance().
trait_SAPROPHAGE
const trait_id trait_SAPROPHAGE("SAPROPHAGE") ("SAPROPHAGE") static
Referenced by comestible_inventory_preset::get_order().
trait_SAPROVORE
const trait_id trait_SAPROVORE("SAPROVORE") ("SAPROVORE") static
Referenced by comestible_inventory_preset::get_order().