Cataclysm DDA: src/game.h File Reference
game.h File Reference
#include <array>
#include <chrono>
#include <ctime>
#include <functional>
#include <iosfwd>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "calendar.h"
#include "character.h"
#include "character_id.h"
#include "color.h"
#include "coordinates.h"
#include "creature.h"
#include "cursesdef.h"
#include "enums.h"
#include "game_constants.h"
#include "global_vars.h"
#include "item_location.h"
#include "memory_fast.h"
#include "pimpl.h"
#include "point.h"
#include "type_id.h"
#include "units_fwd.h"
#include "weather.h"
Classes
struct look_around_result
struct look_around_params
struct w_map
class game
class game::draw_callback_t
class game::non_dead_range< T >
class game::non_dead_range< T >::iterator
class game::monster_range
class game::npc_range
class game::Creature_range
class game::debug_hour_timer
Namespaces
turn_handler
cata_event_dispatch
Macros
#define CATA_SRC_GAME_H
Typedefs
using item_filter = std::function< bool(const item &)>
using item_location_filter = std::function< bool(const item_location &)>
Enumerations
enum quit_status {
QUIT_NO = 0 , QUIT_SUICIDE , QUIT_SAVED , QUIT_NOSAVED ,
QUIT_DIED , QUIT_WATCH
}
enum safe_mode_type { SAFE_MODE_OFF = 0 , SAFE_MODE_ON = 1 , SAFE_MODE_STOP = 2 }
enum peek_act : int { PA_BLIND_THROW }
Functions
input_context get_default_mode_input_context ()
bool is_valid_in_w_terrain (const point &p)
bool turn_handler::cleanup_at_end ()
units::temperature_delta get_heat_radiation (const tripoint &location)
int get_best_fire (const tripoint &location)
units::temperature_delta get_convection_temperature (const tripoint &location)
void cata_event_dispatch::avatar_moves (const tripoint &old_abs_pos, const avatar &u, const map &m)
Variables
constexpr int DEFAULT_TILESET_ZOOM = 16
std::unique_ptr< game > g
const int savegame_version
int savegame_loading_version
Macro Definition Documentation
CATA_SRC_GAME_H
#define CATA_SRC_GAME_H
Definition at line 3 of file game.h.
Typedef Documentation
item_filter
using item_filter = std::function<bool (const item &)>
Definition at line 104 of file game.h.
item_location_filter
using item_location_filter = std::function<bool (const item_location &)>
Definition at line 105 of file game.h.
Enumeration Type Documentation
peek_act
enum peek_act : int
Enumerator
PA_BLIND_THROW
Definition at line 107 of file game.h.
               : int {
     PA_BLIND_THROW
     // obvious future additional value is PA_BLIND_FIRE
 };
quit_status
enum quit_status
Enumerator
QUIT_NO
QUIT_SUICIDE
QUIT_SAVED
QUIT_NOSAVED
QUIT_DIED
QUIT_WATCH
Definition at line 52 of file game.h.
                  {
     QUIT_NO = 0,    // Still playing
     QUIT_SUICIDE,   // Quit with 'Q'
     QUIT_SAVED,     // Saved and quit
     QUIT_NOSAVED,   // Quit without saving
     QUIT_DIED,      // Actual death
     QUIT_WATCH,     // Died, and watching aftermath
 };
safe_mode_type
enum safe_mode_type
Enumerator
SAFE_MODE_OFF
SAFE_MODE_ON
SAFE_MODE_STOP
Definition at line 61 of file game.h.
                     {
     SAFE_MODE_OFF = 0, // Moving always allowed
     SAFE_MODE_ON = 1, // Moving allowed, but if a new monsters spawns, go to SAFE_MODE_STOP
     SAFE_MODE_STOP = 2, // New monsters spotted, no movement allowed
 };
Function Documentation
get_best_fire()
int get_best_fire (const tripoint & location)
Definition at line 1650 of file game.cpp.
 {
     int best_fire = 0;
     Character &player_character = get_player_character();
     map &here = get_map();
     // Convert it to an int id once, instead of 139 times per turn
     const field_type_id fd_fire_int = fd_fire.id();
     for( const tripoint &dest : here.points_in_radius( location, 6 ) ) {
         int heat_intensity = 0;
         maptile mt = here.maptile_at( dest );
         int ffire = maptile_field_intensity( mt, fd_fire_int );
         if( ffire > 0 ) {
             heat_intensity = ffire;
         } else  {
             heat_intensity = mt.get_ter()->heat_radiation;
         }
         if( heat_intensity == 0 ) {
             // No heat source here
             continue;
         }
         if( player_character.pos() == location ) {
             if( !here.clear_path( dest, location, -1, 1, 100 ) ) {
                 continue;
             }
         } else if( !here.sees( location, dest, -1 ) ) {
             continue;
         }
         if( square_dist( dest, location ) <= 1 ) {
             // Extend limbs/lean over a single adjacent fire to warm up
             best_fire = std::max( best_fire, heat_intensity );
         }
     }
     return best_fire;
 }
References map::clear_path(), fd_fire, get_map(), get_player_character(), maptile_impl< Submap >::get_ter(), map_data_common_t::heat_radiation, string_id< T >::id(), location, map::maptile_at(), maptile_field_intensity(), max(), map::points_in_radius(), Creature::pos(), map::sees(), and square_dist().
Referenced by Character::update_bodytemp().
get_convection_temperature()
units::temperature_delta get_convection_temperature (const tripoint & location)
Definition at line 1687 of file game.cpp.
 {
     units::temperature_delta temp_mod = units::from_kelvin_delta( 0 );
     map &here = get_map();
     // Directly on lava tiles
     units::temperature_delta lava_mod = here.tr_at( location ).has_flag(
                                             json_flag_CONVECTS_TEMPERATURE ) ?
                                         units::from_fahrenheit_delta( fd_fire->get_intensity_level().convection_temperature_mod ) :
                                         units::from_kelvin_delta( 0 );
     // Modifier from fields
     for( auto fd : here.field_at( location ) ) {
         // Nullify lava modifier when there is open fire
         if( fd.first.obj().has_fire ) {
             lava_mod = units::from_kelvin_delta( 0 );
         }
         temp_mod += units::from_fahrenheit_delta(
                         fd.second.get_intensity_level().convection_temperature_mod );
     }
     return temp_mod + lava_mod;
 }
References field_intensity_level::convection_temperature_mod, fd_fire, map::field_at(), units::from_fahrenheit_delta(), units::from_kelvin_delta(), field_type::get_intensity_level(), get_map(), trap::has_flag(), json_flag_CONVECTS_TEMPERATURE, location, and map::tr_at().
Referenced by weather_manager::get_temperature(), and item::process_temperature_rot().
get_default_mode_input_context()
input_context get_default_mode_input_context ()
Definition at line 2455 of file game.cpp.
 {
     input_context ctxt( "DEFAULTMODE", keyboard_mode::keycode );
     // Because those keys move the character, they don't pan, as their original name says
     ctxt.set_iso( true );
     ctxt.register_action( "UP", to_translation( "Move north" ) );
     ctxt.register_action( "RIGHTUP", to_translation( "Move northeast" ) );
     ctxt.register_action( "RIGHT", to_translation( "Move east" ) );
     ctxt.register_action( "RIGHTDOWN", to_translation( "Move southeast" ) );
     ctxt.register_action( "DOWN", to_translation( "Move south" ) );
     ctxt.register_action( "LEFTDOWN", to_translation( "Move southwest" ) );
     ctxt.register_action( "LEFT", to_translation( "Move west" ) );
     ctxt.register_action( "LEFTUP", to_translation( "Move northwest" ) );
     ctxt.register_action( "pause" );
     ctxt.register_action( "LEVEL_DOWN", to_translation( "Descend stairs" ) );
     ctxt.register_action( "LEVEL_UP", to_translation( "Ascend stairs" ) );
     ctxt.register_action( "toggle_map_memory" );
     ctxt.register_action( "center" );
     ctxt.register_action( "shift_n" );
     ctxt.register_action( "shift_ne" );
     ctxt.register_action( "shift_e" );
     ctxt.register_action( "shift_se" );
     ctxt.register_action( "shift_s" );
     ctxt.register_action( "shift_sw" );
     ctxt.register_action( "shift_w" );
     ctxt.register_action( "shift_nw" );
     ctxt.register_action( "cycle_move" );
     ctxt.register_action( "cycle_move_reverse" );
     ctxt.register_action( "reset_move" );
     ctxt.register_action( "toggle_run" );
     ctxt.register_action( "toggle_crouch" );
     ctxt.register_action( "toggle_prone" );
     ctxt.register_action( "open_movement" );
     ctxt.register_action( "open" );
     ctxt.register_action( "close" );
     ctxt.register_action( "smash" );
     ctxt.register_action( "loot" );
     ctxt.register_action( "examine" );
     ctxt.register_action( "examine_and_pickup" );
     ctxt.register_action( "advinv" );
     ctxt.register_action( "pickup" );
     ctxt.register_action( "pickup_all" );
     ctxt.register_action( "grab" );
     ctxt.register_action( "haul" );
     ctxt.register_action( "haul_toggle" );
     ctxt.register_action( "butcher" );
     ctxt.register_action( "chat" );
     ctxt.register_action( "look" );
     ctxt.register_action( "peek" );
     ctxt.register_action( "listitems" );
     ctxt.register_action( "zones" );
     ctxt.register_action( "inventory" );
     ctxt.register_action( "compare" );
     ctxt.register_action( "organize" );
     ctxt.register_action( "apply" );
     ctxt.register_action( "apply_wielded" );
     ctxt.register_action( "wear" );
     ctxt.register_action( "take_off" );
     ctxt.register_action( "eat" );
     ctxt.register_action( "open_consume" );
     ctxt.register_action( "read" );
     ctxt.register_action( "wield" );
     ctxt.register_action( "pick_style" );
     ctxt.register_action( "reload_item" );
     ctxt.register_action( "reload_weapon" );
     ctxt.register_action( "reload_wielded" );
     ctxt.register_action( "insert" );
     ctxt.register_action( "unload" );
     ctxt.register_action( "throw" );
     ctxt.register_action( "fire" );
     ctxt.register_action( "cast_spell" );
     ctxt.register_action( "fire_burst" );
     ctxt.register_action( "select_fire_mode" );
     ctxt.register_action( "select_default_ammo" );
     ctxt.register_action( "drop" );
     ctxt.register_action( "unload_container" );
     ctxt.register_action( "drop_adj" );
     ctxt.register_action( "bionics" );
     ctxt.register_action( "mutations" );
     ctxt.register_action( "medical" );
     ctxt.register_action( "bodystatus" );
     ctxt.register_action( "sort_armor" );
     ctxt.register_action( "wait" );
     ctxt.register_action( "craft" );
     ctxt.register_action( "recraft" );
     ctxt.register_action( "long_craft" );
     ctxt.register_action( "construct" );
     ctxt.register_action( "disassemble" );
     ctxt.register_action( "sleep" );
     ctxt.register_action( "control_vehicle" );
     ctxt.register_action( "auto_travel_mode" );
     ctxt.register_action( "safemode" );
     ctxt.register_action( "autosafe" );
     ctxt.register_action( "autoattack" );
     ctxt.register_action( "ignore_enemy" );
     ctxt.register_action( "whitelist_enemy" );
     ctxt.register_action( "workout" );
     ctxt.register_action( "save" );
     ctxt.register_action( "quicksave" );
 #if !defined(RELEASE)
     ctxt.register_action( "quickload" );
 #endif
     ctxt.register_action( "SUICIDE" );
     ctxt.register_action( "player_data" );
     ctxt.register_action( "map" );
     ctxt.register_action( "sky" );
     ctxt.register_action( "missions" );
     ctxt.register_action( "factions" );
     ctxt.register_action( "morale" );
     ctxt.register_action( "messages" );
     ctxt.register_action( "help" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     ctxt.register_action( "open_options" );
     ctxt.register_action( "open_autopickup" );
     ctxt.register_action( "open_autonotes" );
     ctxt.register_action( "open_safemode" );
     ctxt.register_action( "open_distraction_manager" );
     ctxt.register_action( "open_color" );
     ctxt.register_action( "open_world_mods" );
     ctxt.register_action( "debug" );
     ctxt.register_action( "debug_scent" );
     ctxt.register_action( "debug_scent_type" );
     ctxt.register_action( "debug_temp" );
     ctxt.register_action( "debug_visibility" );
     ctxt.register_action( "debug_lighting" );
     ctxt.register_action( "debug_radiation" );
     ctxt.register_action( "debug_hour_timer" );
     ctxt.register_action( "debug_mode" );
     ctxt.register_action( "zoom_out" );
     ctxt.register_action( "zoom_in" );
 #if !defined(__ANDROID__) && !defined(EMSCRIPTEN)
     ctxt.register_action( "toggle_fullscreen" );
 #endif
     ctxt.register_action( "toggle_pixel_minimap" );
     ctxt.register_action( "toggle_panel_adm" );
     ctxt.register_action( "reload_tileset" );
     ctxt.register_action( "toggle_auto_features" );
     ctxt.register_action( "toggle_auto_pulp_butcher" );
     ctxt.register_action( "toggle_auto_mining" );
     ctxt.register_action( "toggle_auto_foraging" );
     ctxt.register_action( "toggle_auto_pickup" );
     ctxt.register_action( "toggle_thief_mode" );
     ctxt.register_action( "toggle_prevent_occlusion" );
     ctxt.register_action( "diary" );
     ctxt.register_action( "action_menu" );
     ctxt.register_action( "main_menu" );
     ctxt.register_action( "item_action_menu" );
     ctxt.register_action( "ANY_INPUT" );
     ctxt.register_action( "COORDINATE" );
     ctxt.register_action( "MOUSE_MOVE" );
     ctxt.register_action( "SELECT" );
     ctxt.register_action( "CLICK_AND_DRAG" );
     ctxt.register_action( "SEC_SELECT" );
     return ctxt;
 }
References keycode, input_context::register_action(), input_context::set_iso(), and to_translation().
Referenced by game::get_player_input(), handle_action_menu(), handle_key_blocking_activity(), handle_main_menu(), haul(), keys_bound_to(), main_menu::opening_screen(), press_x(), and press_x_if_bound().
get_heat_radiation()
units::temperature_delta get_heat_radiation (const tripoint & location)
Definition at line 1614 of file game.cpp.
 {
     units::temperature_delta temp_mod = units::from_kelvin_delta( 0 );
     Character &player_character = get_player_character();
     map &here = get_map();
     // Convert it to an int id once, instead of 139 times per turn
     const field_type_id fd_fire_int = fd_fire.id();
     for( const tripoint &dest : here.points_in_radius( location, 6 ) ) {
         int heat_intensity = 0;
         maptile mt = here.maptile_at( dest );
         int ffire = maptile_field_intensity( mt, fd_fire_int );
         if( ffire > 0 ) {
             heat_intensity = ffire;
         } else  {
             heat_intensity = mt.get_ter()->heat_radiation;
         }
         if( heat_intensity == 0 ) {
             // No heat source here
             continue;
         }
         if( player_character.pos() == location ) {
             if( !here.clear_path( dest, location, -1, 1, 100 ) ) {
                 continue;
             }
         } else if( !here.sees( location, dest, -1 ) ) {
             continue;
         }
         // Ensure fire_dist >= 1 to avoid divide-by-zero errors.
         const int fire_dist = std::max( 1, square_dist( dest, location ) );
         temp_mod += units::from_fahrenheit_delta( 6.f * heat_intensity * heat_intensity / fire_dist );
     }
     return temp_mod;
 }
References map::clear_path(), fd_fire, units::from_fahrenheit_delta(), units::from_kelvin_delta(), get_map(), get_player_character(), maptile_impl< Submap >::get_ter(), map_data_common_t::heat_radiation, string_id< T >::id(), location, map::maptile_at(), maptile_field_intensity(), max(), map::points_in_radius(), Creature::pos(), map::sees(), and square_dist().
Referenced by weather_manager::get_temperature(), item::process_temperature_rot(), and Character::update_bodytemp().
is_valid_in_w_terrain()
bool is_valid_in_w_terrain (const point & p)
Definition at line 387 of file game.cpp.
 {
     return p.x >= 0 && p.x < TERRAIN_WINDOW_WIDTH && p.y >= 0 && p.y < TERRAIN_WINDOW_HEIGHT;
 }
References TERRAIN_WINDOW_HEIGHT, TERRAIN_WINDOW_WIDTH, point::x, and point::y.
Referenced by game::draw_critter(), anonymous_namespace{animation.cpp}::draw_sct_curses(), anonymous_namespace{animation.cpp}::hit_animation(), and game::mon_info_update().
Variable Documentation
DEFAULT_TILESET_ZOOM
constexpr int DEFAULT_TILESET_ZOOM = 16 constexpr
Definition at line 38 of file game.h.
Referenced by game::get_zoom(), game::mouse_edge_scrolling_terrain(), and game::reset_zoom().
g
std::unique_ptr<game> g extern
Definition at line 382 of file game.cpp.
savegame_loading_version
int savegame_loading_version extern
Definition at line 78 of file savegame.cpp.
Referenced by chkversion(), Character::load(), Creature::load(), and game::unserialize_master().
savegame_version
const int savegame_version extern
Definition at line 71 of file savegame.cpp.