Cataclysm DDA: src/generic_factory.h File Reference
generic_factory.h File Reference
Helper for loading from JSON.
#include <algorithm>
#include <bitset>
#include <set>
#include <unordered_map>
#include <vector>
#include "assign.h"
#include "cached_options.h"
#include "catacharset.h"
#include "cata_scope_helpers.h"
#include "cata_type_traits.h"
#include "debug.h"
#include "enum_bitset.h"
#include "init.h"
#include "int_id.h"
#include "json.h"
#include "mod_tracker.h"
#include "output.h"
#include "string_id.h"
#include "units.h"
#include "wcwidth.h"
Classes
class generic_factory< T >
struct generic_factory< T >::T_has_handle_inheritance< U, typename >
struct generic_factory< T >::T_has_handle_inheritance< U, std::void_t< T_has_handle_inheritance_t< U > > >
class generic_factory< T >::Version
Wrapper around generic_factory::version.
struct supports_proportional< T, typename >
struct supports_proportional< T, std::void_t< decltype(std::declval< T & >() *=std::declval< float >())> >
struct supports_relative< T, typename >
struct supports_relative< T, std::void_t< decltype(std::declval< T & >()+=std::declval< T & >())> >
struct supports_proportional< bool >
struct supports_relative< bool >
struct supports_relative< std::string >
struct reader_detail::handler< T >
struct reader_detail::handler< std::set< T > >
struct reader_detail::handler< std::bitset< N > >
struct reader_detail::handler< enum_bitset< E > >
struct reader_detail::handler< std::vector< T > >
class generic_typed_reader< Derived >
Base class for reading generic objects from JSON.
class auto_flags_reader< FlagType >
Converts the JSON string to some type that must be construable from a std::string, e.g.
class volume_reader
class mass_reader
class money_reader
class typed_flag_reader< T >
Uses a map (unordered or standard) to convert strings from JSON to some other type (the mapped type of the map: C::mapped_type).
class enum_flags_reader< E >
Uses io::string_to_enum to convert the string from JSON to a C++ enum.
class string_id_reader< T >
A generic class to store objects identified by a string_id.
class text_style_check_reader
Only for external use in legacy code where migrating to class translation is impractical.
Namespaces
reader_detail
Macros
#define CATA_SRC_GENERIC_FACTORY_H
Typedefs
using string_reader = auto_flags_reader<>
Functions
bool one_char_symbol_reader (const JsonObject &jo, std::string_view member_name, int &sym, bool)
Reads a string and stores the first byte of it in sym.
bool unicode_codepoint_from_symbol_reader (const JsonObject &jo, std::string_view member_name, uint32_t &member, bool)
Reads a UTF-8 string (or int as legacy fallback) and stores Unicode codepoint of it in symbol.
template<typename T >
typed_flag_reader< T > make_flag_reader (const std::unordered_map< std::string, T > &m, const std::string_view e)
bool legacy_volume_reader (const JsonObject &jo, const std::string_view member_name, units::volume &value, bool)
Reads a volume value from legacy format: JSON contains a integer which represents multiples of units::legacy_volume_factor (250 ml).
Implementation of <tt>mandatory</tt> and <tt>optional</tt>.
template<typename MemberType >
void mandatory (const JsonObject &jo, const bool was_loaded, const std::string_view name, MemberType &member)
template<typename MemberType , typename ReaderType >
void mandatory (const JsonObject &jo, const bool was_loaded, const std::string_view name, MemberType &member, const ReaderType &reader)
template<typename MemberType , std::enable_if_t< !supports_proportional< MemberType >::value > * = nullptr>
bool handle_proportional (const JsonObject &jo, const std::string_view name, MemberType &)
template<typename MemberType , std::enable_if_t< !supports_relative< MemberType >::value > * = nullptr>
bool handle_relative (const JsonObject &jo, const std::string_view name, MemberType &)
template<typename MemberType >
void optional (const JsonObject &jo, const bool was_loaded, const std::string_view name, MemberType &member)
template<typename MemberType , typename DefaultType = MemberType, typename = std::enable_if_t<std::is_constructible_v<MemberType, const DefaultType &>>>
void optional (const JsonObject &jo, const bool was_loaded, const std::string_view name, MemberType &member, const DefaultType &default_value)
template<typename MemberType , typename ReaderType , typename DefaultType = MemberType, typename = std::enable_if_t < !std::is_constructible_v<MemberType, const ReaderType &> >>
void optional (const JsonObject &jo, const bool was_loaded, const std::string_view name, MemberType &member, const ReaderType &reader)
template<typename MemberType , typename ReaderType , typename DefaultType = MemberType>
void optional (const JsonObject &jo, const bool was_loaded, const std::string_view name, MemberType &member, const ReaderType &reader, const DefaultType &default_value)
Detailed Description
Helper for loading from JSON.
Loading (inside a T::load(JsonObject &jo) function) can be done with two functions (defined here):
mandatory loads required data and throws an error if the JSON data does not contain the required data.
optional is for optional data, it has the same parameters and an additional default value that will be used if the JSON data does not contain the requested data. It may throw an error if the existing data is not valid (e.g. string instead of requested int).
The functions are designed to work with the generic_factory and therefore support the was_loaded parameter (set by generic_factory::load). If that parameter is true, it is assumed the object has already been loaded and missing JSON data is simply ignored (the default value is not applied and no error is thrown upon missing mandatory data).
The parameters are this:
JsonObject jo the object to load from.
bool was_loaded whether the object had already been loaded completely.
std::string member_name the name of the JSON member to load from.
T &member a reference to the C++ object to store the loaded data.
(for optional) a default value of any type that can be assigned to member.
Both functions use the native read functions of JsonIn (see there) to load the value.
Example:
class Dummy {
    bool was_loaded = false;
    int a;
    std::string b;
    void load(JsonObject &jo) {
        mandatory(jo, was_loaded, "a", a);
        optional(jo, was_loaded, "b", b, "default value of b");
    }
};
This only works if there is function with the matching type defined in JsonIn. For other types, or if the loaded value needs to be converted (e.g. to nc_color), one can use the reader classes/functions. mandatory and optional have an overload that requires the same parameters and an additional reference to such a reader object.
class Dummy2 {
    bool was_loaded = false;
    int b;
    nc_color c;
    void load(JsonObject &jo) {
        mandatory(jo, was_loaded, "b", b); // uses JsonIn::read(int&)
    }
};
Both versions of optional have yet another overload that does not require an explicit default value, a default initialized object of the member type will be used instead.
Readers must provide the following function: `bool operator()(const JsonObject &jo, const std::string &member_name, T &member, bool was_loaded) const
(This can be implemented as free function or as operator in a class.)
The parameters are the same as the for the mandatory function (see above). The function shall returntrueif the loading was done, orfalse` if the JSON data did not contain the requested member. If loading fails because of invalid data (but not missing data), it should throw.
Definition in file generic_factory.h.
Macro Definition Documentation
CATA_SRC_GENERIC_FACTORY_H
#define CATA_SRC_GENERIC_FACTORY_H
Definition at line 3 of file generic_factory.h.
Typedef Documentation
string_reader
using string_reader = auto_flags_reader<>
Definition at line 1187 of file generic_factory.h.
Function Documentation
handle_proportional()
template<typename MemberType , std::enable_if_t< !supports_proportional< MemberType >::value > * = nullptr> bool handle_proportional (const JsonObject & jo, const std::string_view name, MemberType & member) inline
Definition at line 738 of file generic_factory.h.
 {
     if( jo.has_object( "proportional" ) ) {
         JsonObject proportional = jo.get_object( "proportional" );
         proportional.allow_omitted_members();
         if( proportional.has_member( name ) ) {
             debugmsg( "Member %s of type %s does not support proportional", name,
                       demangle( typeid( MemberType ).name() ) );
         }
     }
     return false;
 }
References JsonObject::allow_omitted_members(), debugmsg, demangle(), JsonObject::get_object(), JsonObject::has_member(), JsonObject::has_object(), and om_direction::name().
Referenced by generic_typed_reader< Derived >::operator()(), and optional().
handle_relative()
template<typename MemberType , std::enable_if_t< !supports_relative< MemberType >::value > * = nullptr> bool handle_relative (const JsonObject & jo, const std::string_view name, MemberType & member) inline
Definition at line 788 of file generic_factory.h.
 {
     if( jo.has_object( "relative" ) ) {
         JsonObject relative = jo.get_object( "relative" );
         relative.allow_omitted_members();
         if( !relative.has_member( name ) ) {
             return false;
         }
         debugmsg( "Member %s of type %s does not support relative", name,
                   demangle( typeid( MemberType ).name() ) );
     }
     return false;
 }
References debugmsg, demangle(), JsonObject::get_object(), JsonObject::has_object(), and om_direction::name().
Referenced by optional().
legacy_volume_reader()
bool legacy_volume_reader (const JsonObject & jo, const std::string_view member_name, units::volume & value, bool) inline
Reads a volume value from legacy format: JSON contains a integer which represents multiples of units::legacy_volume_factor (250 ml).
Definition at line 1329 of file generic_factory.h.
 {
     int legacy_value;
     if( !jo.read( member_name, legacy_value ) ) {
         return false;
     }
     value = legacy_value * units::legacy_volume_factor;
     return true;
 }
References units::legacy_volume_factor, and JsonObject::read().
Referenced by furn_t::load().
make_flag_reader()
template<typename T > typed_flag_reader<T> make_flag_reader (const std::unordered_map< std::string, T > & m, const std::string_view e)
Definition at line 1283 of file generic_factory.h.
 {
     return typed_flag_reader<T>( m, e );
 }
Referenced by overmap_connection::subtype::load(), mtype::load(), and move_mode::load().
mandatory() [1/2]
template<typename MemberType > void mandatory (const JsonObject & jo, const bool was_loaded, const std::string_view name, MemberType & member) inline
Definition at line 633 of file generic_factory.h.
 {
     if( !jo.read( name, member ) ) {
         if( !was_loaded ) {
             if( jo.has_member( name ) ) {
                 jo.throw_error( str_cat( "failed to read mandatory member \"", name, "\"" ) );
             } else {
                 jo.throw_error( str_cat( "missing mandatory member \"", name, "\"" ) );
             }
         }
     }
 }
References JsonObject::has_member(), member, om_direction::name(), JsonObject::read(), str_cat(), and JsonObject::throw_error().
Referenced by add_if_exists(), relic_procgen_data::enchantment_value_passive< T >::load(), rotatable_symbols::load(), anonymous_namespace{gates.cpp}::gate_data::load(), load_float_or_maxmovecost(), and load_region_settings().
mandatory() [2/2]
template<typename MemberType , typename ReaderType > void mandatory (const JsonObject & jo, const bool was_loaded, const std::string_view name, MemberType & member, const ReaderType & reader) inline
Definition at line 647 of file generic_factory.h.
 {
     if( !reader( jo, name, member, was_loaded ) ) {
         if( !was_loaded ) {
             if( jo.has_member( name ) ) {
                 jo.throw_error( str_cat( "failed to read mandatory member \"", name, "\"" ) );
             } else {
                 jo.throw_error( str_cat( "missing mandatory member \"", name, "\"" ) );
             }
         }
     }
 }
References JsonObject::has_member(), member, om_direction::name(), str_cat(), and JsonObject::throw_error().
one_char_symbol_reader()
bool one_char_symbol_reader (const JsonObject & jo, std::string_view member_name, int & sym, bool)
Reads a string and stores the first byte of it in sym.
Throws if the input contains more or less than one byte.
Definition at line 3 of file generic_factory.cpp.
 {
     std::string sym_as_string;
     if( !jo.read( member_name, sym_as_string ) ) {
         return false;
     }
     if( sym_as_string.size() != 1 ) {
         jo.throw_error_at(
             member_name,
             string_format( "%s must be exactly one ASCII character but was %zu bytes",
                            member_name, sym_as_string.size() ) );
     }
     uint8_t c = sym_as_string.front();
     if( c > 127 ) {
         jo.throw_error_at(
             member_name,
             string_format( "%s must be exactly one ASCII character but was non-ASCII (%u)",
                            member_name, c ) );
     }
     sym = c;
     return true;
 }
References c, JsonObject::read(), string_format(), and JsonObject::throw_error_at().
Referenced by trap::load().
optional() [1/4]
template<typename MemberType > void optional (const JsonObject & jo, const bool was_loaded, const std::string_view name, MemberType & member) inline
Definition at line 829 of file generic_factory.h.
 {
     if( !jo.read( name, member ) && !handle_proportional( jo, name, member ) &&
         !handle_relative( jo, name, member ) ) {
         if( !was_loaded ) {
             member = MemberType();
         }
     }
 }
References handle_proportional(), handle_relative(), member, om_direction::name(), and JsonObject::read().
Referenced by icg_entry_reader::_part_get_next(), snippet_library::add_snippet_from_json(), climbing_aid::condition::deserialize(), climbing_aid::climb_cost::deserialize(), climbing_aid::down_t::deserialize(), part_material::deserialize(), armor_portion_data::deserialize(), mapgen_parameter::deserialize(), shopkeeper_item_group::deserialize(), option_slider::option_slider_level::deserialize(), book_proficiency_bonus::deserialize(), bash_test_loadout::deserialize(), single_bash_test::deserialize(), bash_test_set::deserialize(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_part_temp(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_worn_with_flag(), faction_template::faction_template(), faction_price_rules_reader::get_next(), get_optional(), jmapgen_remove_npcs::jmapgen_remove_npcs(), jmapgen_sign::jmapgen_sign(), achievement::load(), city::load(), event_transformation::load(), event_statistic::load(), score::load(), activity_type::load(), bp_onhit_effect::load(), vitamin_rate_effect::load(), limb_score_effect::load(), effect_dur_mod::load(), fault::load(), harvest_entry::load(), zone_priority_data::load(), io::acc_data::load(), sealable_data::load(), pocket_noise::load(), pocket_data::load(), islot_brewable::load(), islot_compostable::load(), islot_armor::load(), islot_pet_armor::load(), islot_book::load(), islot_engine::load(), islot_wheel::load(), itype_variant_data::load(), islot_ammo::load(), islot_seed::load(), islot_milling::load(), fake_spell::load(), enchantment::bodypart_changes::load(), pry_data::load(), activity_data_common::load(), activity_data_furn::load(), ter_furn_migrations::load(), mon_effect_data::load(), pet_food_data::load(), monster_death_effect::load(), mutation_variant::load(), overmap_connection::subtype::load(), relic_procgen_data::enchantment_value_passive< T >::load(), relic_procgen_data::enchantment_active::load(), relic_procgen_data::generation_rules::load(), shearing_entry::load(), speed_description_value::load(), test_data::load(), vpart_migration::load(), widget_clause::load(), appliance_convert_examine_actor::load(), cardreader_examine_actor::load(), vpart_variant::load(), map_data_common_t::load(), ma_technique::load(), martialart::load(), mission_type::load(), mtype::load(), mutation_branch::load(), overmap_land_use_code::load(), oter_type_t::load(), overmap_special::load(), recipe::load(), start_location::load(), vpart_info::load(), ter_t::load(), furn_t::load(), damage_info_order::damage_info_order_entry::load(), add_type::load(), ammo_effect::load(), behavior::node_t::load(), bodygraph::load(), limb_score::load(), body_part_type::load(), character_modifier::load(), clothing_mod::load(), damage_info_order::load(), effect_on_condition::load(), field_type::load(), json_flag::load(), anonymous_namespace{gates.cpp}::gate_data::load(), harvest_drop_type::load(), spell_type::load(), map_extra::load(), weapon_category::load(), ma_requirements::load(), ma_buff::load(), jmath_func::load(), monfaction::load(), species_type::load(), morale_type_data::load(), move_mode::load(), npc_class::load(), overmap_special_migration::load(), option_slider::load(), overmap_location::load(), profession::load(), proficiency::load(), scenario::load(), shopkeeper_cons_rates::load(), shopkeeper_blacklist::load(), speed_description::load(), sub_body_part_type::load(), trap::load(), vehicle_prototype::load(), weather_type::load(), widget::load(), enchantment::load(), climbing_aid::load(), zone_type::load(), damage_type::load(), disease_type::load(), item_category::load(), stat_hp_mods::load(), fuel_explosion_data::load(), fuel_data::load(), reflex_activation_data::load(), mutation_category_trait::load(), mut_transform::load(), mut_personality_score::load(), map_shoot_info::load(), material_type::load(), consume_drug_iuse::load(), bionic_data::load(), harvest_list::load(), Item_factory::load(), effect_type::load_apply_msgs(), Item_factory::load_basic_info(), json_talk_response::load_condition(), load_damage_unit(), grab::load_grab(), leap_actor::load_internal(), mon_spellcasting_actor::load_internal(), melee_actor::load_internal(), bite_actor::load_internal(), gun_actor::load_internal(), jmapgen_nested::neighbor_flag_any_check::neighbor_flag_any_check(), jmapgen_nested::neighbor_flag_check::neighbor_flag_check(), parse_vp_control_reqs(), overmap_ui::place_ter_or_special(), and game::zones_manager().
optional() [2/4]
template<typename MemberType , typename DefaultType = MemberType, typename = std::enable_if_t<std::is_constructible_v<MemberType, const DefaultType &>>> void optional (const JsonObject & jo, const bool was_loaded, const std::string_view name, MemberType & member, const DefaultType & default_value) inline
Definition at line 851 of file generic_factory.h.
 {
     if( !jo.read( name, member ) && !handle_proportional( jo, name, member ) &&
         !handle_relative( jo, name, member ) ) {
         if( !was_loaded ) {
             member = default_value;
         }
     }
 }
References handle_proportional(), handle_relative(), member, om_direction::name(), and JsonObject::read().
optional() [3/4]
template<typename MemberType , typename ReaderType , typename DefaultType = MemberType, typename = std::enable_if_t < !std::is_constructible_v<MemberType, const ReaderType &> >> void optional (const JsonObject & jo, const bool was_loaded, const std::string_view name, MemberType & member, const ReaderType & reader) inline
Definition at line 864 of file generic_factory.h.
 {
     if( !reader( jo, name, member, was_loaded ) ) {
         if( !was_loaded ) {
             member = MemberType();
         }
     }
 }
References member, and om_direction::name().
optional() [4/4]
template<typename MemberType , typename ReaderType , typename DefaultType = MemberType> void optional (const JsonObject & jo, const bool was_loaded, const std::string_view name, MemberType & member, const ReaderType & reader, const DefaultType & default_value) inline
Definition at line 874 of file generic_factory.h.
 {
     if( !reader( jo, name, member, was_loaded ) ) {
         if( !was_loaded ) {
             member = default_value;
         }
     }
 }
References member, and om_direction::name().
unicode_codepoint_from_symbol_reader()
bool unicode_codepoint_from_symbol_reader (const JsonObject & jo, std::string_view member_name, uint32_t & member, bool)
Reads a UTF-8 string (or int as legacy fallback) and stores Unicode codepoint of it in symbol.
Throws if the inputs width is more than one console cell wide.
Definition at line 27 of file generic_factory.cpp.
 {
     int sym_as_int;
     std::string sym_as_string;
     if( !jo.read( member_name, sym_as_string, false ) ) {
         // Legacy fallback to integer `sym`.
         if( !jo.read( member_name, sym_as_int ) ) {
             return false;
         } else {
             sym_as_string = string_from_int( sym_as_int );
         }
     }
     uint32_t sym_as_codepoint = UTF8_getch( sym_as_string );
     if( mk_wcwidth( sym_as_codepoint ) != 1 ) {
         jo.throw_error_at(
             member_name, str_cat( member_name, " must be exactly one console cell wide" ) );
     }
     member = sym_as_codepoint;
     return true;
 }
References member, mk_wcwidth(), JsonObject::read(), str_cat(), string_from_int(), JsonObject::throw_error_at(), and UTF8_getch().
Referenced by overmap_land_use_code::load(), oter_type_t::load(), field_type::load(), map_extra::load(), move_mode::load(), and weather_type::load().