Cataclysm DDA: src/generic_factory.cpp File Reference
generic_factory.cpp File Reference
#include "generic_factory.h"
Functions
bool one_char_symbol_reader (const JsonObject &jo, const std::string_view member_name, int &sym, bool)
Reads a string and stores the first byte of it in sym.
bool unicode_codepoint_from_symbol_reader (const JsonObject &jo, const std::string_view member_name, uint32_t &member, bool)
Reads a UTF-8 string (or int as legacy fallback) and stores Unicode codepoint of it in symbol.
Function Documentation
one_char_symbol_reader()
bool one_char_symbol_reader (const JsonObject & jo, std::string_view member_name, int & sym, bool)
Reads a string and stores the first byte of it in sym.
Throws if the input contains more or less than one byte.
Definition at line 3 of file generic_factory.cpp.
 {
     std::string sym_as_string;
     if( !jo.read( member_name, sym_as_string ) ) {
         return false;
     }
     if( sym_as_string.size() != 1 ) {
         jo.throw_error_at(
             member_name,
             string_format( "%s must be exactly one ASCII character but was %zu bytes",
                            member_name, sym_as_string.size() ) );
     }
     uint8_t c = sym_as_string.front();
     if( c > 127 ) {
         jo.throw_error_at(
             member_name,
             string_format( "%s must be exactly one ASCII character but was non-ASCII (%u)",
                            member_name, c ) );
     }
     sym = c;
     return true;
 }
References c, JsonObject::read(), string_format(), and JsonObject::throw_error_at().
Referenced by trap::load().
unicode_codepoint_from_symbol_reader()
bool unicode_codepoint_from_symbol_reader (const JsonObject & jo, std::string_view member_name, uint32_t & member, bool)
Reads a UTF-8 string (or int as legacy fallback) and stores Unicode codepoint of it in symbol.
Throws if the inputs width is more than one console cell wide.
Definition at line 27 of file generic_factory.cpp.
 {
     int sym_as_int;
     std::string sym_as_string;
     if( !jo.read( member_name, sym_as_string, false ) ) {
         // Legacy fallback to integer `sym`.
         if( !jo.read( member_name, sym_as_int ) ) {
             return false;
         } else {
             sym_as_string = string_from_int( sym_as_int );
         }
     }
     uint32_t sym_as_codepoint = UTF8_getch( sym_as_string );
     if( mk_wcwidth( sym_as_codepoint ) != 1 ) {
         jo.throw_error_at(
             member_name, str_cat( member_name, " must be exactly one console cell wide" ) );
     }
     member = sym_as_codepoint;
     return true;
 }
References member, mk_wcwidth(), JsonObject::read(), str_cat(), string_from_int(), JsonObject::throw_error_at(), and UTF8_getch().
Referenced by overmap_land_use_code::load(), oter_type_t::load(), field_type::load(), map_extra::load(), move_mode::load(), and weather_type::load().