Cataclysm DDA: src/get_version.h File Reference
get_version.h File Reference
Macros
#define CATA_SRC_GET_VERSION_H
Functions
const char * getVersionString ()
Macro Definition Documentation
CATA_SRC_GET_VERSION_H
#define CATA_SRC_GET_VERSION_H
Definition at line 3 of file get_version.h.
Function Documentation
getVersionString()
const char* getVersionString ()
Definition at line 15 of file version.cpp.
 {
     return VERSION;
 }
Referenced by debug_error_prompt(), game_info::game_version(), DebugFile::init(), game::load(), main(), main_menu::print_menu(), anonymous_namespace{main.cpp}::printVersionMessage(), set_language(), game::start_game(), and memorial_logger::write_text_memorial().