Cataclysm DDA: src/global_vars.h File Reference
global_vars.h File Reference
#include <utility>
#include "json.h"
Classes
class global_variables
Macros
#define CATA_SRC_GLOBAL_VARS_H
Enumerations
enum class var_type : int {
u , npc , global , faction ,
party , context , var , last
}
Functions
global_variables & get_globals ()
Macro Definition Documentation
CATA_SRC_GLOBAL_VARS_H
#define CATA_SRC_GLOBAL_VARS_H
Definition at line 3 of file global_vars.h.
Enumeration Type Documentation
var_type
enum var_type : int strong
Enumerator
u
npc
global
faction
party
context
var
last
Definition at line 8 of file global_vars.h.
                     : int {
     u,
     npc,
     global,
     faction,
     party,
     context,
     var,
     last
 };
Function Documentation
get_globals()
global_variables& get_globals ()
Definition at line 164 of file game.cpp.
 {
     return g->global_variables_instance;
 }
Referenced by basecamp::choose_new_leader(), debug_menu::edit_global_vars(), Creature::load(), global_variables::load_migrations(), maybe_read_var_value(), parse_tags(), set_queued_points(), debug_menu::write_global_vars(), and write_var_value().