Cataclysm DDA: Convert functions for @ref string_formatter
Convert functions for @ref string_formatter
The convert functions here are used to convert the input value of string_formatter::parse into the requested type, as defined by the format specifiers.
Functions
template<typename RT , typename T >
std::enable_if_t< is_integer< RT > &&is_integer< T >, RT > cata::convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
RT cata::convert (RT *, const string_formatter &sf, T &&,...)
Variables
template<typename T >
constexpr bool cata::is_numeric
template<typename T >
constexpr bool cata::is_integer
template<typename T >
constexpr bool cata::is_char = std::is_same_v<std::decay_t<T>, char>
template<typename T >
constexpr bool cata::is_string = std::is_same_v<std::decay_t<T>, std::string>
template<typename T >
constexpr bool cata::is_string_view = std::is_same_v<std::decay_t<T>, std::string_view>
template<typename T >
constexpr bool cata::is_cstring
template<typename T >
constexpr bool cata::is_translation = std::is_same_v<std::decay_t<T>, translation>
Detailed Description
The convert functions here are used to convert the input value of string_formatter::parse into the requested type, as defined by the format specifiers.
Template Parameters
T the input type, as given by the call to string_format.
RT the requested type. The convert functions return such a value or they throw an exception via throw_error.
Each function has the same parameters: First parameter defined the requested type. The value of the pointer is ignored, callers should use a (properly casted) nullptr. It is required to "simulate" overloading the return value. E.g. long convert(long*, int) and short convert(short*, int) both convert a input value of type int, but the first converts to long and the second converts to short. Without the first parameters their signature would be identical. The second parameter is used to call throw_error / string_formatter_set_temp_buffer. The third parameter is the input value that is to be converted. The fourth parameter is a dummy value, it is always ignored, callers should use 0 here. It is used so the fallback with the variadic arguments is only chosen when no other overload matches.
Function Documentation
convert() [1/2]
template<typename RT , typename T > std::enable_if_t< is_integer<RT> &&is_integer<T>, RT > cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 81 of file string_formatter.h.
 {
     return value;
 }
Referenced by item_contents::combine(), cata::string_formatter::get_nth_arg_as(), get_option(), item::io(), Item_factory::migrate_item(), options_manager::cOpt::value_as< std::string >(), and options_manager::cOpt::value_as().
convert() [2/2]
template<typename RT , typename T > RT cata::convert (RT * , const string_formatter & sf, T && , ...) inline
Definition at line 149 of file string_formatter.h.
 {
     static_assert( std::is_pointer_v<std::decay_t<T>> ||
                    is_numeric<T> || is_string<T> || is_string_view<T> ||
                    is_char<T> || std::is_enum_v<std::decay_t<T>> ||
                    is_cstring<T> || is_translation<T>, "Unsupported argument type" );
     throw_error( sf, "Tried to convert argument of type " +
                  demangle( typeid( T ).name() ) + " to " +
                  demangle( typeid( RT ).name() ) + ", which is not possible" );
 }
References demangle(), om_direction::name(), and cata::throw_error().
Variable Documentation
is_char
template<typename T > constexpr bool cata::is_char = std::is_same_v<std::decay_t<T>, char> constexpr
Definition at line 64 of file string_formatter.h.
is_cstring
template<typename T > constexpr bool cata::is_cstring constexpr
Initial value:
=
    std::is_same_v<std::decay_t<T>, const char *> || std::is_same_v<std::decay_t<T>, char *>
Definition at line 73 of file string_formatter.h.
is_integer
template<typename T > constexpr bool cata::is_integer constexpr
Initial value:
=
    is_numeric<T>
    && !std::is_floating_point_v<std::decay_t<T>>
Definition at line 60 of file string_formatter.h.
Referenced by cata::colony< element_type, element_allocator_type, element_skipfield_type >::colony(), and cata::colony< element_type, element_allocator_type, element_skipfield_type >::get_iterator_from_index().
is_numeric
template<typename T > constexpr bool cata::is_numeric constexpr
Initial value:
=
    std::is_arithmetic_v<std::decay_t<T>>
    && !std::is_same_v<std::decay_t<T>, bool>
Definition at line 55 of file string_formatter.h.
is_string
template<typename T > constexpr bool cata::is_string = std::is_same_v<std::decay_t<T>, std::string> constexpr
Definition at line 67 of file string_formatter.h.
is_string_view
template<typename T > constexpr bool cata::is_string_view = std::is_same_v<std::decay_t<T>, std::string_view> constexpr
Definition at line 70 of file string_formatter.h.
is_translation
template<typename T > constexpr bool cata::is_translation = std::is_same_v<std::decay_t<T>, translation> constexpr
Definition at line 77 of file string_formatter.h.