Cataclysm DDA: src/handle_liquid.cpp File Reference
handle_liquid.cpp File Reference
#include "handle_liquid.h"
#include <algorithm>
#include <cstddef>
#include <functional>
#include <iterator>
#include <list>
#include <new>
#include <optional>
#include <ostream>
#include <set>
#include <vector>
#include "action.h"
#include "activity_actor_definitions.h"
#include "activity_type.h"
#include "cached_options.h"
#include "cata_utility.h"
#include "character.h"
#include "colony.h"
#include "color.h"
#include "debug.h"
#include "enums.h"
#include "game_inventory.h"
#include "iexamine.h"
#include "item.h"
#include "itype.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "messages.h"
#include "monster.h"
#include "player_activity.h"
#include "string_formatter.h"
#include "translations.h"
#include "ui.h"
#include "units.h"
#include "veh_interact.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "vpart_range.h"
Namespaces
liquid_handler
Macros
#define dbg(x) DebugLog((x),D_GAME) << __FILE__ << ":" << __LINE__ << ": "
Functions
static void serialize_liquid_source (player_activity &act, const vehicle &veh, const int part_num, const item &liquid)
static void serialize_liquid_source (player_activity &act, const tripoint &pos, const item &liquid)
static void serialize_liquid_target (player_activity &act, const vpart_reference &vp)
static void serialize_liquid_target (player_activity &act, const item_location &container_item)
static void serialize_liquid_target (player_activity &act, const tripoint &pos)
void liquid_handler::handle_all_liquid (item liquid, int radius, const item *avoid=nullptr)
Consume / handle all of the liquid.
bool liquid_handler::consume_liquid (item &liquid, int radius=0, const item *avoid=nullptr)
Consume / handle as much of the liquid as possible in varying ways.
bool liquid_handler::handle_liquid_from_ground (const map_stack::iterator &on_ground, const tripoint &pos, int radius=0)
Handle finite liquid from ground.
bool liquid_handler::handle_liquid_from_container (item *in_container, item &container, int radius=0)
Handle liquid from inside a container item.
bool liquid_handler::handle_liquid_from_container (item &container, int radius=0)
Shortcut to the above: handles the first item in the container.
static bool liquid_handler::get_liquid_target (item &liquid, const item *const source, const int radius, const tripoint *const source_pos, const vehicle *const source_veh, const monster *const source_mon, liquid_dest_opt &target)
bool liquid_handler::perform_liquid_transfer (item &liquid, const tripoint *const source_pos, const vehicle *const source_veh, const int part_num, const monster *const, liquid_dest_opt &target)
bool liquid_handler::can_handle_liquid (const item &liquid)
bool liquid_handler::handle_liquid (item &liquid, const item *source=nullptr, int radius=0, const tripoint *source_pos=nullptr, const vehicle *source_veh=nullptr, int part_num=-1, const monster *source_mon=nullptr)
This may start a player activity if either source_pos or source_veh is not null.
Variables
static const activity_id ACT_FILL_LIQUID ("ACT_FILL_LIQUID")
static const flag_id json_flag_FROM_FROZEN_LIQUID ("FROM_FROZEN_LIQUID")
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x),D_GAME) << __FILE__ << ":" << __LINE__ << ": "
Definition at line 43 of file handle_liquid.cpp.
Function Documentation
serialize_liquid_source() [1/2]
static void serialize_liquid_source (player_activity & act, const tripoint & pos, const item & liquid) static
Definition at line 63 of file handle_liquid.cpp.
 {
     const map_stack stack = get_map().i_at( pos );
     // Need to store the *index* of the item on the ground, but it may be a virtual item from
     // an infinite liquid source.
     const auto iter = std::find_if( stack.begin(), stack.end(), [&]( const item & i ) {
         return &i == &liquid;
     } );
     if( iter == stack.end() ) {
         act.values.push_back( static_cast<int>( liquid_source_type::INFINITE_MAP ) );
         act.values.push_back( 0 ); // dummy
     } else {
         act.values.push_back( static_cast<int>( liquid_source_type::MAP_ITEM ) );
         act.values.push_back( std::distance( stack.begin(), iter ) );
     }
     act.coords.push_back( pos );
     act.str_values.push_back( serialize( liquid ) );
 }
References act, item_stack::begin(), item_stack::end(), get_map(), map::i_at(), INFINITE_MAP, MAP_ITEM, math_opers::pos(), and serialize().
serialize_liquid_source() [2/2]
static void serialize_liquid_source (player_activity & act, const vehicle & veh, const int part_num, const item & liquid) static
Definition at line 50 of file handle_liquid.cpp.
 {
     act.values.push_back( static_cast<int>( liquid_source_type::VEHICLE ) );
     act.values.push_back( part_num );
     if( part_num != -1 ) {
         act.coords.push_back( veh.global_part_pos3( part_num ) );
     } else {
         act.coords.push_back( veh.global_pos3() );
     }
     act.str_values.push_back( serialize( liquid ) );
 }
References act, vehicle::global_part_pos3(), vehicle::global_pos3(), serialize(), and VEHICLE.
Referenced by liquid_handler::perform_liquid_transfer().
serialize_liquid_target() [1/3]
static void serialize_liquid_target (player_activity & act, const item_location & container_item) static
Definition at line 90 of file handle_liquid.cpp.
 {
     act.values.push_back( static_cast<int>( liquid_target_type::CONTAINER ) );
     act.values.push_back( 0 ); // dummy
     act.targets.push_back( container_item );
     act.coords.emplace_back( ); // dummy
 }
References act, and CONTAINER.
serialize_liquid_target() [2/3]
static void serialize_liquid_target (player_activity & act, const tripoint & pos) static
Definition at line 98 of file handle_liquid.cpp.
 {
     act.values.push_back( static_cast<int>( liquid_target_type::MAP ) );
     act.values.push_back( 0 ); // dummy
     act.coords.push_back( pos );
 }
References act, MAP, and math_opers::pos().
serialize_liquid_target() [3/3]
static void serialize_liquid_target (player_activity & act, const vpart_reference & vp) static
Definition at line 82 of file handle_liquid.cpp.
 {
     act.values.push_back( static_cast<int>( liquid_target_type::VEHICLE ) );
     act.values.push_back( 0 ); // dummy
     act.coords.push_back( vp.vehicle().global_part_pos3( 0 ) );
     act.values.push_back( vp.part_index() ); // tank part index
 }
References act, vehicle::global_part_pos3(), vpart_position::part_index(), VEHICLE, and vpart_reference::vehicle().
Referenced by liquid_handler::perform_liquid_transfer().
Variable Documentation
ACT_FILL_LIQUID
const activity_id ACT_FILL_LIQUID("ACT_FILL_LIQUID") ("ACT_FILL_LIQUID") static
Referenced by liquid_handler::perform_liquid_transfer().
json_flag_FROM_FROZEN_LIQUID
const flag_id json_flag_FROM_FROZEN_LIQUID("FROM_FROZEN_LIQUID") ("FROM_FROZEN_LIQUID") static
Referenced by liquid_handler::handle_liquid().