Cataclysm DDA: src/handle_action.cpp File Reference
handle_action.cpp File Reference
#include "game.h"
#include <chrono>
#include <cmath>
#include <initializer_list>
#include <list>
#include <map>
#include <sstream>
#include <string>
#include <utility>
#include "action.h"
#include "activity_actor_definitions.h"
#include "activity_type.h"
#include "advanced_inv.h"
#include "auto_note.h"
#include "auto_pickup.h"
#include "avatar.h"
#include "avatar_action.h"
#include "bionics.h"
#include "bodygraph.h"
#include "bodypart.h"
#include "cached_options.h"
#include "calendar.h"
#include "catacharset.h"
#include "character.h"
#include "character_attire.h"
#include "character_martial_arts.h"
#include "clzones.h"
#include "color.h"
#include "construction.h"
#include "creature_tracker.h"
#include "cursesdef.h"
#include "damage.h"
#include "debug.h"
#include "debug_menu.h"
#include "diary.h"
#include "distraction_manager.h"
#include "do_turn.h"
#include "event.h"
#include "event_bus.h"
#include "faction.h"
#include "field.h"
#include "field_type.h"
#include "flag.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "gamemode.h"
#include "gates.h"
#include "gun_mode.h"
#include "help.h"
#include "input_context.h"
#include "input_enums.h"
#include "inventory_ui.h"
#include "item.h"
#include "item_group.h"
#include "itype.h"
#include "iuse.h"
#include "level_cache.h"
#include "line.h"
#include "magic.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "mapsharing.h"
#include "mdarray.h"
#include "messages.h"
#include "monster.h"
#include "move_mode.h"
#include "mtype.h"
#include "mutation.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "overmap_ui.h"
#include "panels.h"
#include "player_activity.h"
#include "popup.h"
#include "ranged.h"
#include "rng.h"
#include "safemode_ui.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "timed_event.h"
#include "translation.h"
#include "translations.h"
#include "ui.h"
#include "ui_manager.h"
#include "uistate.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "weather.h"
#include "weather_type.h"
#include "worldfactory.h"
Classes
class user_turn
Macros
#define dbg(x) DebugLog((x),D_GAME) << __FILE__ << ":" << __LINE__ << ": "
Functions
static void rcdrive (const point &d)
static void pldrive (const tripoint &p)
static void pldrive (point d)
static void open ()
static void close ()
static void grab ()
static void haul ()
static void haul_toggle ()
static void smash ()
static int try_set_alarm ()
static void wait ()
static void sleep ()
static void loot ()
static void wear ()
static void takeoff ()
static void read ()
static void reach_attack (avatar &you)
static void fire ()
static void open_movement_mode_menu ()
static void cast_spell ()
static void handle_debug_mode ()
static bool has_vehicle_control (avatar &player_character)
static void do_deathcam_action (const action_id &act, avatar &player_character)
static std::map< action_id, std::string > get_actions_disabled_in_shell ()
static std::map< action_id, std::string > get_actions_disabled_mounted ()
Variables
static const activity_id ACT_FERTILIZE_PLOT ("ACT_FERTILIZE_PLOT")
static const activity_id ACT_MOVE_LOOT ("ACT_MOVE_LOOT")
static const activity_id ACT_MULTIPLE_BUTCHER ("ACT_MULTIPLE_BUTCHER")
static const activity_id ACT_MULTIPLE_CHOP_PLANKS ("ACT_MULTIPLE_CHOP_PLANKS")
static const activity_id ACT_MULTIPLE_CHOP_TREES ("ACT_MULTIPLE_CHOP_TREES")
static const activity_id ACT_MULTIPLE_CONSTRUCTION ("ACT_MULTIPLE_CONSTRUCTION")
static const activity_id ACT_MULTIPLE_DIS ("ACT_MULTIPLE_DIS")
static const activity_id ACT_MULTIPLE_FARM ("ACT_MULTIPLE_FARM")
static const activity_id ACT_MULTIPLE_MINE ("ACT_MULTIPLE_MINE")
static const activity_id ACT_MULTIPLE_MOP ("ACT_MULTIPLE_MOP")
static const activity_id ACT_PULP ("ACT_PULP")
static const activity_id ACT_SPELLCASTING ("ACT_SPELLCASTING")
static const activity_id ACT_VEHICLE_DECONSTRUCTION ("ACT_VEHICLE_DECONSTRUCTION")
static const activity_id ACT_VEHICLE_REPAIR ("ACT_VEHICLE_REPAIR")
static const activity_id ACT_WAIT ("ACT_WAIT")
static const activity_id ACT_WAIT_STAMINA ("ACT_WAIT_STAMINA")
static const activity_id ACT_WAIT_WEATHER ("ACT_WAIT_WEATHER")
static const bionic_id bio_remote ("bio_remote")
static const damage_type_id damage_cut ("cut")
static const efftype_id effect_alarm_clock ("alarm_clock")
static const efftype_id effect_incorporeal ("incorporeal")
static const efftype_id effect_laserlocked ("laserlocked")
static const efftype_id effect_stunned ("stunned")
static const flag_id json_flag_MOP ("MOP")
static const gun_mode_id gun_mode_AUTO ("AUTO")
static const itype_id fuel_type_animal ("animal")
static const itype_id itype_radiocontrol ("radiocontrol")
static const json_character_flag json_flag_ALARMCLOCK ("ALARMCLOCK")
static const json_character_flag json_flag_NO_PSIONICS ("NO_PSIONICS")
static const json_character_flag json_flag_NO_SPELLCASTING ("NO_SPELLCASTING")
static const json_character_flag json_flag_SUBTLE_SPELL ("SUBTLE_SPELL")
static const material_id material_glass ("glass")
static const quality_id qual_CUT ("CUT")
static const skill_id skill_melee ("melee")
static const trait_id trait_BRAWLER ("BRAWLER")
static const trait_id trait_HIBERNATE ("HIBERNATE")
static const trait_id trait_PROF_CHURL ("PROF_CHURL")
static const trait_id trait_SHELL2 ("SHELL2")
static const trait_id trait_SHELL3 ("SHELL3")
static const trait_id trait_UNDINE_SLEEP_WATER ("UNDINE_SLEEP_WATER")
static const trait_id trait_WATERSLEEP ("WATERSLEEP")
static const trait_id trait_WATERSLEEPER ("WATERSLEEPER")
static const trait_id trait_WAYFARER ("WAYFARER")
static const zone_type_id zone_type_CHOP_TREES ("CHOP_TREES")
static const zone_type_id zone_type_CONSTRUCTION_BLUEPRINT ("CONSTRUCTION_BLUEPRINT")
static const zone_type_id zone_type_DISASSEMBLE ("DISASSEMBLE")
static const zone_type_id zone_type_FARM_PLOT ("FARM_PLOT")
static const zone_type_id zone_type_LOOT_CORPSE ("LOOT_CORPSE")
static const zone_type_id zone_type_LOOT_UNSORTED ("LOOT_UNSORTED")
static const zone_type_id zone_type_LOOT_WOOD ("LOOT_WOOD")
static const zone_type_id zone_type_MINING ("MINING")
static const zone_type_id zone_type_MOPPING ("MOPPING")
static const zone_type_id zone_type_STRIP_CORPSES ("STRIP_CORPSES")
static const zone_type_id zone_type_UNLOAD_ALL ("UNLOAD_ALL")
static const zone_type_id zone_type_VEHICLE_DECONSTRUCT ("VEHICLE_DECONSTRUCT")
static const zone_type_id zone_type_VEHICLE_REPAIR ("VEHICLE_REPAIR")
static const std::set< action_id > actions_disabled_in_incorporeal
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x),D_GAME) << __FILE__ << ":" << __LINE__ << ": "
Definition at line 176 of file handle_action.cpp.
Function Documentation
cast_spell()
static void cast_spell () static
Definition at line 1717 of file handle_action.cpp.
 {
     Character &player_character = get_player_character();
     player_character.magic->clear_opens_spellbook_data();
     get_event_bus().send<event_type::opens_spellbook>( player_character.getID() ); // trigger EoC
     player_character.magic->evaluate_opens_spellbook_data();
     std::vector<spell_id> spells = player_character.magic->spells();
     if( spells.empty() ) {
         add_msg( game_message_params{ m_bad, gmf_bypass_cooldown },
                  _( "You don't know any spells to cast." ) );
         return;
     }
     bool can_cast_spells = false;
     for( const spell_id &sp : spells ) {
         spell &temp_spell = player_character.magic->get_spell( sp );
         if( temp_spell.can_cast( player_character ) ) {
             can_cast_spells = true;
         }
     }
     if( !can_cast_spells ) {
         if( player_character.has_flag( json_flag_NO_SPELLCASTING ) &&
             !player_character.has_flag( json_flag_NO_PSIONICS ) ) {
             add_msg( game_message_params{ m_bad, gmf_bypass_cooldown },
                      _( "You can't cast any of the spells you know!" ) );
         } else if( !player_character.has_flag( json_flag_NO_SPELLCASTING ) &&
                    player_character.has_flag( json_flag_NO_PSIONICS ) ) {
             add_msg( game_message_params{ m_bad, gmf_bypass_cooldown },
                      _( "You can't channel any of the powers you know!" ) );
         } else {
             add_msg( game_message_params{ m_bad, gmf_bypass_cooldown },
                      _( "You can't use any of your powers!" ) );
         }
     }
     const int spell_index = player_character.magic->select_spell( player_character );
     if( spell_index < 0 ) {
         return;
     }
     spell &sp = *player_character.magic->get_spells()[spell_index];
     player_character.cast_spell( sp, false, std::nullopt );
 }
References _, add_msg(), spell::can_cast(), Character::cast_spell(), get_event_bus(), get_player_character(), Character::getID(), gmf_bypass_cooldown, Character::has_flag(), json_flag_NO_PSIONICS, json_flag_NO_SPELLCASTING, m_bad, Character::magic, opens_spellbook, and event_bus::send().
Referenced by game::do_regular_action(), and cast_spell_actor::use().
close()
static void close () static
Definition at line 659 of file handle_action.cpp.
 {
     if( const std::optional<tripoint_bub_ms> pnt = choose_adjacent_highlight_bub_ms(
                 _( "Close where?" ),
                 pgettext( "no door, gate, etc.", "There is nothing that can be closed nearby." ),
                 ACTION_CLOSE, false ) ) {
         doors::close_door( get_map(), get_player_character(), *pnt );
     }
 }
References _, ACTION_CLOSE, choose_adjacent_highlight_bub_ms(), doors::close_door(), get_map(), get_player_character(), and pgettext.
Referenced by game::do_regular_action(), mmap_file::map_file(), gates::open_gate(), and overmap::place_forest_trailheads().
do_deathcam_action()
static void do_deathcam_action (const action_id & act, avatar & player_character) static
Definition at line 1999 of file handle_action.cpp.
 {
     switch( act ) {
         case ACTION_TOGGLE_MAP_MEMORY:
             player_character.toggle_map_memory();
             break;
         case ACTION_CENTER:
             player_character.view_offset.x = g->driving_view_offset.x;
             player_character.view_offset.y = g->driving_view_offset.y;
             break;
         case ACTION_SHIFT_N:
         case ACTION_SHIFT_NE:
         case ACTION_SHIFT_E:
         case ACTION_SHIFT_SE:
         case ACTION_SHIFT_S:
         case ACTION_SHIFT_SW:
         case ACTION_SHIFT_W:
         case ACTION_SHIFT_NW: {
             static const std::map<action_id, std::pair<point, point>> shift_delta = {
                 { ACTION_SHIFT_N, { point_north, point_north_east } },
                 { ACTION_SHIFT_NE, { point_north_east, point_east } },
                 { ACTION_SHIFT_E, { point_east, point_south_east } },
                 { ACTION_SHIFT_SE, { point_south_east, point_south } },
                 { ACTION_SHIFT_S, { point_south, point_south_west } },
                 { ACTION_SHIFT_SW, { point_south_west, point_west } },
                 { ACTION_SHIFT_W, { point_west, point_north_west } },
                 { ACTION_SHIFT_NW, { point_north_west, point_north } },
             };
             int soffset = get_option<int>( "MOVE_VIEW_OFFSET" );
             player_character.view_offset += g->is_tileset_isometric()
                                             ? shift_delta.at( act ).second * soffset
                                             : shift_delta.at( act ).first * soffset;
         }
         break;
         case ACTION_LOOK:
             g->look_around();
             break;
         case ACTION_KEYBINDINGS: // already handled by input context
         default:
             break;
     }
 }
References act, ACTION_CENTER, ACTION_KEYBINDINGS, ACTION_LOOK, ACTION_SHIFT_E, ACTION_SHIFT_N, ACTION_SHIFT_NE, ACTION_SHIFT_NW, ACTION_SHIFT_S, ACTION_SHIFT_SE, ACTION_SHIFT_SW, ACTION_SHIFT_W, ACTION_TOGGLE_MAP_MEMORY, g, point_east, point_north, point_north_east, point_north_west, point_south, point_south_east, point_south_west, point_west, avatar::toggle_map_memory(), Character::view_offset, tripoint::x, and tripoint::y.
Referenced by game::handle_action().
fire()
static void fire () static
Definition at line 1635 of file handle_action.cpp.
 {
     avatar &you = get_avatar();
     map &here = get_map();
     if( !you.try_break_relax_gas( _( "Your willpower asserts itself, and so do you!" ),
                                   _( "You're too pacified to strike anything" ) ) ) {
         return;
     }
     const item_location weapon = you.get_wielded_item();
     // try reach weapon
     if( weapon && !weapon->is_gun() && weapon->current_reach_range( you ) > 1 ) {
         reach_attack( you );
         return;
     }
     if( you.has_trait( trait_BRAWLER ) ) {
         add_msg( m_bad, _( "You refuse to use ranged weapons." ) );
         return;
     }
     // try firing gun
     if( weapon && weapon->is_gun() && !weapon->gun_current_mode().melee() ) {
         avatar_action::fire_wielded_weapon( you );
         return;
     }
     // try firing turrets
     if( const optional_vpart_position ovp = here.veh_at( you.pos() ) ) {
         if( turret_data turret_here = ovp->vehicle().turret_query( you.pos() ) ) {
             if( avatar_action::fire_turret_manual( you, here, turret_here ) ) {
                 return;
             }
         } else if( ovp.part_with_feature( VPFLAG_CONTROLS, true ) ) {
             if( ovp->vehicle().turrets_aim_and_fire_all_manual() ) {
                 return;
             }
         }
     }
     // offer to draw a gun from worn holster
     std::vector<std::string> options;
     std::vector<std::function<void()>> actions;
     you.worn.fire_options( you, options, actions );
     if( !options.empty() ) {
         int sel = uilist( _( "Draw what?" ), options );
         if( sel >= 0 ) {
             actions[sel]();
             return;
         }
     }
 }
References _, add_msg(), item::current_reach_range(), cata_path::empty(), outfit::fire_options(), avatar_action::fire_turret_manual(), avatar_action::fire_wielded_weapon(), get_avatar(), get_map(), Character::get_wielded_item(), item::gun_current_mode(), Character::has_trait(), item::is_gun(), m_bad, gun_mode::melee(), PATH_INFO::options(), Creature::pos(), reach_attack(), trait_BRAWLER, avatar::try_break_relax_gas(), map::veh_at(), turret_data::vehicle, VPFLAG_CONTROLS, and Character::worn.
Referenced by explosion_handler::do_blast(), game::do_regular_action(), target_ui::draw_controls_list(), explosion_handler::explosion(), find_best_fire(), inventory::form_from_map(), and get_fire_fuel_string().
get_actions_disabled_in_shell()
static std::map<action_id, std::string> get_actions_disabled_in_shell () static
Definition at line 2046 of file handle_action.cpp.
 {
     return std::map<action_id, std::string> {
         { ACTION_OPEN,               _( "You can't open things while you're in your shell." ) },
         { ACTION_CLOSE,              _( "You can't close things while you're in your shell." ) },
         { ACTION_SMASH,              _( "You can't smash things while you're in your shell." ) },
         { ACTION_EXAMINE,            _( "You can't examine your surroundings while you're in your shell." ) },
         { ACTION_EXAMINE_AND_PICKUP, _( "You can't examine your surroundings while you're in your shell." ) },
         { ACTION_ADVANCEDINV,        _( "You can't move mass quantities while you're in your shell." ) },
         { ACTION_PICKUP,             _( "You can't pick anything up while you're in your shell." ) },
         { ACTION_PICKUP_ALL,         _( "You can't pick anything up while you're in your shell." ) },
         { ACTION_GRAB,               _( "You can't grab things while you're in your shell." ) },
         { ACTION_HAUL,               _( "You can't haul things while you're in your shell." ) },
         { ACTION_HAUL_TOGGLE,        _( "You can't haul things while you're in your shell." ) },
         { ACTION_BUTCHER,            _( "You can't butcher while you're in your shell." ) },
         { ACTION_PEEK,               _( "You can't peek around corners while you're in your shell." ) },
         { ACTION_DROP,               _( "You can't drop things while you're in your shell." ) },
         { ACTION_CRAFT,              _( "You can't craft while you're in your shell." ) },
         { ACTION_RECRAFT,            _( "You can't craft while you're in your shell." ) },
         { ACTION_LONGCRAFT,          _( "You can't craft while you're in your shell." ) },
         { ACTION_DISASSEMBLE,        _( "You can't disassemble while you're in your shell." ) },
         { ACTION_CONSTRUCT,          _( "You can't construct while you're in your shell." ) },
         { ACTION_CONTROL_VEHICLE,    _( "You can't operate a vehicle while you're in your shell." ) },
     };
 }
References _, ACTION_ADVANCEDINV, ACTION_BUTCHER, ACTION_CLOSE, ACTION_CONSTRUCT, ACTION_CONTROL_VEHICLE, ACTION_CRAFT, ACTION_DISASSEMBLE, ACTION_DROP, ACTION_EXAMINE, ACTION_EXAMINE_AND_PICKUP, ACTION_GRAB, ACTION_HAUL, ACTION_HAUL_TOGGLE, ACTION_LONGCRAFT, ACTION_OPEN, ACTION_PEEK, ACTION_PICKUP, ACTION_PICKUP_ALL, ACTION_RECRAFT, and ACTION_SMASH.
Referenced by game::do_regular_action().
get_actions_disabled_mounted()
static std::map<action_id, std::string> get_actions_disabled_mounted () static
Definition at line 2091 of file handle_action.cpp.
 {
     return std::map<action_id, std::string> {
         { ACTION_DISASSEMBLE,        _( "You can't disassemble items while you're riding." ) },
         { ACTION_CONSTRUCT,          _( "You can't construct while you're riding." ) },
         { ACTION_OPEN,               _( "You can't open things while you're riding." ) },
         { ACTION_ADVANCEDINV,        _( "You can't move mass quantities while you're riding." ) },
         { ACTION_PICKUP,             _( "You can't pick anything up while you're riding." ) },
         { ACTION_PICKUP_ALL,         _( "You can't pick anything up while you're riding." ) },
         { ACTION_GRAB,               _( "You can't grab things while you're riding." ) },
         { ACTION_HAUL,               _( "You can't haul things while you're riding." ) },
         { ACTION_HAUL_TOGGLE,        _( "You can't haul things while you're riding." ) },
         { ACTION_BUTCHER,            _( "You can't butcher while you're riding." ) },
         { ACTION_PEEK,               _( "You can't peek around corners while you're riding." ) },
         { ACTION_CRAFT,              _( "You can't craft while you're riding." ) },
         { ACTION_RECRAFT,            _( "You can't craft while you're riding." ) },
         { ACTION_LONGCRAFT,          _( "You can't craft while you're riding." ) },
     };
 }
References _, ACTION_ADVANCEDINV, ACTION_BUTCHER, ACTION_CONSTRUCT, ACTION_CRAFT, ACTION_DISASSEMBLE, ACTION_GRAB, ACTION_HAUL, ACTION_HAUL_TOGGLE, ACTION_LONGCRAFT, ACTION_OPEN, ACTION_PEEK, ACTION_PICKUP, ACTION_PICKUP_ALL, and ACTION_RECRAFT.
Referenced by game::do_regular_action().
grab()
static void grab () static
Definition at line 670 of file handle_action.cpp.
 {
     avatar &you = get_avatar();
     map &here = get_map();
     if( you.get_grab_type() != object_type::NONE ) {
         if( const optional_vpart_position vp = here.veh_at( you.pos() + you.grab_point ) ) {
             add_msg( _( "You release the %s." ), vp->vehicle().name );
         } else if( here.has_furn( you.pos() + you.grab_point ) ) {
             add_msg( _( "You release the %s." ), here.furnname( you.pos() + you.grab_point ) );
         }
         you.grab( object_type::NONE );
         return;
     }
     const std::optional<tripoint> grabp_ = choose_adjacent( _( "Grab where?" ) );
     if( !grabp_ ) {
         add_msg( _( "Never mind." ) );
         return;
     }
     tripoint grabp = *grabp_;
     if( grabp == you.pos() ) {
         add_msg( _( "You get a hold of yourself." ) );
         you.grab( object_type::NONE );
         return;
     }
     // Object might not be on the same z level if on a ramp.
     if( !( here.veh_at( grabp ) || here.has_furn( grabp ) ) ) {
         if( here.has_flag( ter_furn_flag::TFLAG_RAMP_UP, grabp ) ||
             here.has_flag( ter_furn_flag::TFLAG_RAMP_UP, you.pos() ) ) {
             grabp.z += 1;
         } else if( here.has_flag( ter_furn_flag::TFLAG_RAMP_DOWN, grabp ) ||
                    here.has_flag( ter_furn_flag::TFLAG_RAMP_DOWN, you.pos() ) ) {
             grabp.z -= 1;
         }
     }
     if( const optional_vpart_position vp = here.veh_at( grabp ) ) {
         std::string veh_name = vp->vehicle().name;
         if( !vp->vehicle().handle_potential_theft( you ) ) {
             return;
         }
         if( vp.part_with_feature( VPFLAG_WALL_MOUNTED, false ) ) {
             add_msg( m_info, _( "You can't move that, it's attached to the wall." ) );
             return;
         }
         // Powergrids with more than one part are undraggable.
         // Offer to split the targeted part off onto its own, making it draggable.
         if( vp->vehicle().is_powergrid() && vp->vehicle().part_count() > 1 ) {
             if( !query_yn(
                     _( "That's part of a power grid.  Separate it from the grid so you can move it?" ) ) ) {
                 return;
             }
             get_player_character().pause();
             vp->vehicle().separate_from_grid( vp.value().mount() );
             if( const optional_vpart_position split_vp = here.veh_at( grabp ) ) {
                 veh_name = split_vp->vehicle().name;
             } else {
                 debugmsg( "Lost the part to drag after splitting power grid!" );
                 return;
             }
         }
         you.grab( object_type::VEHICLE, grabp - you.pos() );
         add_msg( _( "You grab the %s." ), veh_name );
     } else if( here.has_furn( grabp ) ) { // If not, grab furniture if present
         if( !here.furn( grabp ).obj().is_movable() ) {
             add_msg( _( "You can not grab the %s." ), here.furnname( grabp ) );
             return;
         }
         you.grab( object_type::FURNITURE, grabp - you.pos() );
         if( !here.can_move_furniture( grabp, &you ) ) {
             add_msg( _( "You grab the %s. It feels really heavy." ), here.furnname( grabp ) );
         } else {
             add_msg( _( "You grab the %s." ), here.furnname( grabp ) );
         }
     } else { // TODO: grab mob? Captured squirrel = pet (or meat that stays fresh longer).
         add_msg( m_info, _( "There's nothing to grab there!" ) );
     }
 }
References _, add_msg(), map::can_move_furniture(), choose_adjacent(), debugmsg, map::furn(), FURNITURE, map::furnname(), get_avatar(), avatar::get_grab_type(), get_map(), get_player_character(), avatar::grab(), Character::grab_point, map::has_flag(), map::has_furn(), furn_t::is_movable(), m_info, NONE, int_id< T >::obj(), Character::pause(), Creature::pos(), query_yn(), TFLAG_RAMP_DOWN, TFLAG_RAMP_UP, map::veh_at(), VEHICLE, VPFLAG_WALL_MOUNTED, and tripoint::z.
Referenced by game::do_regular_action(), and avatar::load().
handle_debug_mode()
static void handle_debug_mode () static
Definition at line 1873 of file handle_action.cpp.
 {
     auto debug_mode_setup = []( uilist_entry & entry ) -> void {
         entry.txt = string_format( _( "Debug Mode (%1$s)" ), debug_mode ? _( "ON" ) : _( "OFF" ) );
         entry.text_color = debug_mode ? c_green : c_light_gray;
     };
     // returns if entry became active
     auto debugmode_entry_setup = []( uilist_entry & entry, bool active ) -> void {
         if( active )
         {
             entry.extratxt.txt = _( "A" );
             entry.extratxt.color = c_white_green;
             entry.text_color = c_green;
         } else
         {
             entry.extratxt.txt = " ";
             entry.extratxt.color = c_unset;
             entry.text_color = c_light_gray;
         }
     };
     static bool first_time = true;
     if( first_time ) {
         first_time = false;
         debugmode::enabled_filters.clear();
         for( int i = 0; i < debugmode::DF_LAST; ++i ) {
             debugmode::enabled_filters.emplace( static_cast<debugmode::debug_filter>( i ) );
         }
     }
     input_context ctxt( "DEFAULTMODE" );
     ctxt.register_action( "debug_mode" );
     uilist dbmenu;
     dbmenu.allow_anykey = true;
     dbmenu.title = _( "Debug Mode Filters" );
     dbmenu.text = string_format( _( "Press [%1$s] to quickly toggle debug mode." ),
                                  ctxt.get_desc( "debug_mode" ) );
     dbmenu.entries.reserve( 1 + debugmode::DF_LAST );
     dbmenu.addentry( 0, true, 'd', " " );
     debug_mode_setup( dbmenu.entries[0] );
     dbmenu.addentry( 1, true, 't', _( "Toggle all filters" ) );
     bool toggle_value = true;
     for( int i = 0; i < debugmode::DF_LAST; ++i ) {
         uilist_entry entry( i + 2, true, 0,
                             debugmode::filter_name( static_cast<debugmode::debug_filter>( i ) ) );
         entry.extratxt.left = 1;
         const bool active = debugmode::enabled_filters.count( static_cast<debugmode::debug_filter>
                             ( i ) ) == 1;
         if( toggle_value && active ) {
             toggle_value = false;
         }
         debugmode_entry_setup( entry, active );
         dbmenu.entries.push_back( entry );
     }
     do {
         dbmenu.query();
         if( ctxt.input_to_action( dbmenu.ret_evt ) == "debug_mode" ) {
             debug_mode = !debug_mode;
             if( debug_mode ) {
                 add_msg( m_info, _( "Debug mode ON!" ) );
             } else {
                 add_msg( m_info, _( "Debug mode OFF!" ) );
             }
             break;
         }
         if( dbmenu.ret == 0 ) {
             debug_mode = !debug_mode;
             debug_mode_setup( dbmenu.entries[0] );
         } else if( dbmenu.ret == 1 ) {
             debugmode::enabled_filters.clear();
             for( int i = 0; i < debugmode::DF_LAST; ++i ) {
                 debugmode_entry_setup( dbmenu.entries[i + 2], toggle_value );
                 if( toggle_value ) {
                     debugmode::enabled_filters.emplace( static_cast<debugmode::debug_filter>( i ) );
                 }
             }
             toggle_value = !toggle_value;
         } else if( dbmenu.ret > 1 ) {
             uilist_entry &entry = dbmenu.entries[dbmenu.ret];
             const auto filter_iter = debugmode::enabled_filters.find( static_cast<debugmode::debug_filter>
                                      ( dbmenu.ret - 2 ) );
             const bool active = filter_iter != debugmode::enabled_filters.end();
             debugmode_entry_setup( entry, !active );
             if( active ) {
                 debugmode::enabled_filters.erase( filter_iter );
             } else {
                 debugmode::enabled_filters.emplace(
                     static_cast<debugmode::debug_filter>( dbmenu.ret - 2 ) );
             }
         }
     } while( dbmenu.ret != UILIST_CANCEL );
 }
References _, add_msg(), uilist::addentry(), uilist::allow_anykey, c_green, c_light_gray, c_unset, c_white_green, mvwzstr::color, debug_mode, debugmode::DF_LAST, debugmode::enabled_filters, uilist::entries, uilist_entry::extratxt, debugmode::filter_name(), input_context::get_desc(), input_context::input_to_action(), mvwzstr::left, m_info, uilist::query(), input_context::register_action(), uilist::ret, uilist::ret_evt, string_format(), uilist::text, uilist_entry::text_color, uilist::title, mvwzstr::txt, and UILIST_CANCEL.
Referenced by game::do_regular_action().
has_vehicle_control()
static bool has_vehicle_control (avatar & player_character) static
Definition at line 1987 of file handle_action.cpp.
 {
     if( player_character.is_dead_state() ) {
         return false;
     }
     const optional_vpart_position vp = get_map().veh_at( player_character.pos() );
     if( vp && vp->vehicle().player_in_control( player_character ) ) {
         return true;
     }
     return g->remoteveh() != nullptr;
 }
References g, get_map(), Character::is_dead_state(), Creature::pos(), and map::veh_at().
Referenced by game::do_regular_action(), and game::handle_action().
haul()
static void haul () static
Definition at line 753 of file handle_action.cpp.
 {
     Character &player_character = get_player_character();
     uilist menu;
     bool hauling = player_character.is_hauling();
     bool autohaul = player_character.is_autohauling();
     std::vector<item_location> &haul_list = player_character.haul_list;
     std::vector<item_location> haulable_items = get_map().get_haulable_items( player_character.pos() );
     int haul_qty = haul_list.size();
     std::string &haul_filter = player_character.hauling_filter;
     std::string help_header =
         _( "Select items on current tile to haul with you as you move.\nIf autohaul is enabled, you will automatically add encountered items to the haul.\nYou can set a filter to limit which items are automatically added." );
     std::string status_header;
     if( hauling && autohaul ) {
         if( haul_qty == 0 ) {
             status_header =
                 _( "You are currently not hauling any items, but autohaul is enabled, so any new items encountered on the ground will be hauled." );
         } else {
             status_header = string_format(
                                 _( "You are currently hauling %d items.\nAutohaul is enabled, so any new items encountered on the ground will be hauled." ),
                                 haul_qty );
         }
     }
     if( hauling && !autohaul ) {
         if( haul_qty == 0 ) {
             debugmsg( "Invalid hauling state: hauling enabled, nothing is being hauled, autohaul is off." );
         } else {
             status_header = string_format( _( "You are currently hauling %d items.\nAutohaul is disabled." ),
                                            haul_qty );
         }
     }
     if( !hauling ) {
         status_header =
             _( "You are currently not hauling.  Select items to haul or enable autohaul to start." );
     }
     if( status_header.empty() ) {
         debugmsg( "Failed to construct status header for haul interface" );
     }
     status_header += haul_filter.empty() ? _( "\nAutohaul filter not set." ) : string_format(
                          _( "\nAutohaul filter: %s" ), haul_filter );
     menu.text = help_header + "\n\n" + status_header;
     input_context ctxt = get_default_mode_input_context();
     std::vector<input_event> haul_keys = ctxt.keys_bound_to( "haul" );
     int haul_key = haul_keys.empty() ? '\\' : haul_keys.front().sequence.front();
     menu.entries.emplace_back( 0, hauling, hauling ? haul_key : 'h', _( "Stop hauling" ) );
     menu.entries.emplace_back( 1, !haulable_items.empty(), !hauling ? haul_key : 'h',
                                _( "Haul everything here" ) );
     menu.entries.emplace_back( 2, !haulable_items.empty(), 'p', _( "Choose items to haul" ) );
     menu.entries.emplace_back( 3, true, 'a',
                                autohaul ? _( "Disable autohaul" ) : _( "Enable autohaul" ) );
     menu.entries.emplace_back( 4, true, 'f', _( "Edit autohaul filter" ) );
     menu.entries.emplace_back( 9, true, 'c', _( "Cancel" ) );
     menu.query();
     switch( menu.ret ) {
         case 0:
             player_character.stop_hauling();
             break;
         case 1:
             player_character.start_hauling( haulable_items );
             break;
         case 2: {
             inventory_haul_selector selector( player_character );
             selector.add_map_items( player_character.pos() );
             selector.apply_selection( player_character.haul_list );
             selector.set_title( _( "Select items to haul" ) );
             selector.set_hint( _( "To select x items, type a number before selecting." ) );
             drop_locations result = selector.execute( true );
             haulable_items.clear();
             for( const drop_location &dl : result ) {
                 haulable_items.push_back( dl.first );
             }
             if( haulable_items != player_character.haul_list ) {
                 player_character.suppress_autohaul = true;
             }
             player_character.start_hauling( haulable_items );
         }
         break;
         case 3:
             autohaul ? player_character.stop_autohaul() : player_character.start_autohaul();
             break;
         case 4:
             string_input_popup()
             .title( _( "Filter:" ) )
             .width( 55 )
             .description( item_filter_rule_string( item_filter_type::FILTER ) )
             .desc_color( c_white )
             .identifier( "item_filter" )
             .max_length( 256 )
             .edit( player_character.hauling_filter );
             break;
         case 9:
         default:
             break;
     }
 }
References _, inventory_selector::add_map_items(), inventory_haul_selector::apply_selection(), c_white, debugmsg, string_input_popup::desc_color(), string_input_popup::description(), string_input_popup::edit(), uilist::entries, inventory_multiselector::execute(), FILTER, get_default_mode_input_context(), map::get_haulable_items(), get_map(), get_player_character(), Character::haul_list, Character::hauling_filter, string_input_popup::identifier(), Character::is_autohauling(), Character::is_hauling(), item_filter_rule_string(), input_context::keys_bound_to(), string_input_popup::max_length(), Creature::pos(), uilist::query(), uilist::ret, inventory_selector::set_hint(), inventory_selector::set_title(), Character::start_autohaul(), Character::start_hauling(), Character::stop_autohaul(), Character::stop_hauling(), string_format(), Character::suppress_autohaul, uilist::text, string_input_popup::title(), and string_input_popup::width().
Referenced by game::do_regular_action().
haul_toggle()
static void haul_toggle () static
Definition at line 863 of file handle_action.cpp.
 {
     get_avatar().toggle_hauling();
 }
References get_avatar(), and Character::toggle_hauling().
Referenced by game::do_regular_action().
loot()
static void loot () static
Definition at line 1358 of file handle_action.cpp.
 {
     enum ZoneFlags {
         None = 1,
         SortLoot = 2,
         SortLootStatic = 4,
         SortLootPersonal = 8,
         FertilizePlots = 16,
         ConstructPlots = 64,
         MultiFarmPlots = 128,
         Multichoptrees = 256,
         Multichopplanks = 512,
         Multideconvehicle = 1024,
         Multirepairvehicle = 2048,
         MultiButchery = 4096,
         MultiMining = 8192,
         MultiDis = 16384,
         MultiMopping = 32768,
         UnloadLoot = 65536
     };
     Character &player_character = get_player_character();
     int flags = 0;
     zone_manager &mgr = zone_manager::get_manager();
     const bool has_fertilizer = player_character.cache_has_item_with( flag_FERTILIZER );
     // reset any potentially disabled zones from a past activity
     mgr.reset_disabled();
     // cache should only happen if we have personal zones defined
     if( mgr.has_personal_zones() ) {
         mgr.cache_data();
     }
     // Manually update vehicle cache.
     // In theory this would be handled by the related activity (activity_on_turn_move_loot())
     // but with a stale cache we never get that far.
     mgr.cache_vzones();
     flags |= g->check_near_zone( zone_type_LOOT_UNSORTED,
                                  player_character.pos() ) ? SortLoot : 0;
     flags |= g->check_near_zone( zone_type_UNLOAD_ALL, player_character.pos() ) ||
              g->check_near_zone( zone_type_STRIP_CORPSES, player_character.pos() ) ? UnloadLoot : 0;
     if( g->check_near_zone( zone_type_FARM_PLOT, player_character.pos() ) ) {
         flags |= FertilizePlots;
         flags |= MultiFarmPlots;
     }
     flags |= g->check_near_zone( zone_type_CONSTRUCTION_BLUEPRINT,
                                  player_character.pos() ) ? ConstructPlots : 0;
     flags |= g->check_near_zone( zone_type_CHOP_TREES,
                                  player_character.pos() ) ? Multichoptrees : 0;
     flags |= g->check_near_zone( zone_type_LOOT_WOOD,
                                  player_character.pos() ) ? Multichopplanks : 0;
     flags |= g->check_near_zone( zone_type_VEHICLE_DECONSTRUCT,
                                  player_character.pos() ) ? Multideconvehicle : 0;
     flags |= g->check_near_zone( zone_type_VEHICLE_REPAIR,
                                  player_character.pos() ) ? Multirepairvehicle : 0;
     flags |= g->check_near_zone( zone_type_LOOT_CORPSE,
                                  player_character.pos() ) ? MultiButchery : 0;
     flags |= g->check_near_zone( zone_type_MINING, player_character.pos() ) ? MultiMining : 0;
     flags |= g->check_near_zone( zone_type_DISASSEMBLE,
                                  player_character.pos() ) ? MultiDis : 0;
     flags |= g->check_near_zone( zone_type_MOPPING, player_character.pos() ) ? MultiMopping : 0;
     if( flags == 0 ) {
         add_msg( m_info, _( "There is no compatible zone nearby." ) );
         add_msg( m_info, _( "Compatible zones are %s and %s" ),
                  mgr.get_name_from_type( zone_type_LOOT_UNSORTED ),
                  mgr.get_name_from_type( zone_type_FARM_PLOT ) );
         return;
     }
     uilist menu;
     menu.text = _( "Pick action:" );
     menu.desc_enabled = true;
     if( flags & SortLoot ) {
         menu.addentry_desc( SortLootStatic, true, 'o', _( "Sort out my loot (static zones only)" ),
                             _( "Sorts out the loot from Loot: Unsorted zone to nearby appropriate Loot zones ignoring personal zones.  Uses empty space in your inventory or utilizes a cart, if you are holding one." ) );
         menu.addentry_desc( SortLootPersonal, true, 'O', _( "Sort out my loot (personal zones only)" ),
                             _( "Sorts out the loot from Loot: Unsorted zone to nearby appropriate Loot zones ignoring static zones.  Uses empty space in your inventory or utilizes a cart, if you are holding one." ) );
         menu.addentry_desc( SortLoot, true, 'I', _( "Sort out my loot (all)" ),
                             _( "Sorts out the loot from Loot: Unsorted zone to nearby appropriate Loot zones.  Uses empty space in your inventory or utilizes a cart, if you are holding one." ) );
     }
     if( flags & UnloadLoot ) {
         menu.addentry_desc( UnloadLoot, true, 'U', _( "Unload nearby containers" ),
                             _( "Unloads any corpses or containers that are in their respective zones." ) );
     }
     if( flags & FertilizePlots ) {
         menu.addentry_desc( FertilizePlots, has_fertilizer, 'f',
                             !has_fertilizer ? _( "Fertilize plots you don't have any fertilizer" ) : _( "Fertilize plots" ),
                             _( "Fertilize any nearby Farm: Plot zones." ) );
     }
     if( flags & ConstructPlots ) {
         menu.addentry_desc( ConstructPlots, true, 'c', _( "Construct plots" ),
                             _( "Work on any nearby Blueprint: construction zones." ) );
     }
     if( flags & MultiFarmPlots ) {
         menu.addentry_desc( MultiFarmPlots, true, 'm', _( "Farm plots" ),
                             _( "Till and plant on any nearby farm plots - auto-fetch seeds and tools." ) );
     }
     if( flags & Multichoptrees ) {
         menu.addentry_desc( Multichoptrees, true, 'C', _( "Chop trees" ),
                             _( "Chop down any trees in the designated zone - auto-fetch tools." ) );
     }
     if( flags & Multichopplanks ) {
         menu.addentry_desc( Multichopplanks, true, 'P', _( "Chop planks" ),
                             _( "Auto-chop logs in wood loot zones into planks - auto-fetch tools." ) );
     }
     if( flags & Multideconvehicle ) {
         menu.addentry_desc( Multideconvehicle, true, 'v', _( "Deconstruct vehicle" ),
                             _( "Auto-deconstruct vehicle in designated zone - auto-fetch tools." ) );
     }
     if( flags & Multirepairvehicle ) {
         menu.addentry_desc( Multirepairvehicle, true, 'V', _( "Repair vehicle" ),
                             _( "Auto-repair vehicle in designated zone - auto-fetch tools." ) );
     }
     if( flags & MultiButchery ) {
         menu.addentry_desc( MultiButchery, true, 'B', _( "Butcher corpses" ),
                             _( "Auto-butcher anything in corpse loot zones - auto-fetch tools." ) );
     }
     if( flags & MultiMining ) {
         menu.addentry_desc( MultiMining, true, 'M', _( "Mine Area" ),
                             _( "Auto-mine anything in mining zone - auto-fetch tools." ) );
     }
     if( flags & MultiDis ) {
         menu.addentry_desc( MultiDis, true, 'D', _( "Disassemble items" ),
                             _( "Auto-disassemble anything in disassembly zone - auto-fetch tools." ) );
     }
     if( flags & MultiMopping ) {
         menu.addentry_desc( MultiMopping, true, 'p', _( "Mop area" ), _( "Mop clean the area." ) );
     }
     menu.query();
     flags = ( menu.ret >= 0 ) ? menu.ret : None;
     bool recache = false;
     switch( flags ) {
         case None:
             add_msg( _( "Never mind." ) );
             break;
         case SortLoot:
             player_character.assign_activity( ACT_MOVE_LOOT );
             break;
         case SortLootStatic:
             //temporarily disable personal zones
             for( const auto &i : mgr.get_zones() ) {
                 zone_data &zone = i.get();
                 if( zone.get_is_personal() && zone.get_enabled() ) {
                     zone.set_enabled( false );
                     zone.set_temporary_disabled( true );
                     recache = true;
                 }
             }
             if( recache ) {
                 mgr.cache_data();
             }
             player_character.assign_activity( ACT_MOVE_LOOT );
             break;
         case SortLootPersonal:
             //temporarily disable non personal zones
             for( const auto &i : mgr.get_zones() ) {
                 zone_data &zone = i.get();
                 if( !zone.get_is_personal() && zone.get_enabled() ) {
                     zone.set_enabled( false );
                     zone.set_temporary_disabled( true );
                     recache = true;
                 }
             }
             if( recache ) {
                 mgr.cache_data();
             }
             player_character.assign_activity( ACT_MOVE_LOOT );
             break;
         case UnloadLoot:
             player_character.assign_activity( unload_loot_activity_actor() );
             break;
         case FertilizePlots:
             player_character.assign_activity( ACT_FERTILIZE_PLOT );
             break;
         case ConstructPlots:
             player_character.assign_activity( ACT_MULTIPLE_CONSTRUCTION );
             break;
         case MultiFarmPlots:
             player_character.assign_activity( ACT_MULTIPLE_FARM );
             break;
         case Multichoptrees:
             player_character.assign_activity( ACT_MULTIPLE_CHOP_TREES );
             break;
         case Multichopplanks:
             player_character.assign_activity( ACT_MULTIPLE_CHOP_PLANKS );
             break;
         case Multideconvehicle:
             player_character.assign_activity( ACT_VEHICLE_DECONSTRUCTION );
             break;
         case Multirepairvehicle:
             player_character.assign_activity( ACT_VEHICLE_REPAIR );
             break;
         case MultiButchery:
             player_character.assign_activity( ACT_MULTIPLE_BUTCHER );
             break;
         case MultiMining:
             player_character.assign_activity( ACT_MULTIPLE_MINE );
             break;
         case MultiDis:
             player_character.assign_activity( ACT_MULTIPLE_DIS );
             break;
         case MultiMopping:
             player_character.assign_activity( ACT_MULTIPLE_MOP );
             break;
         default:
             debugmsg( "Unsupported flag" );
             break;
     }
 }
References _, ACT_FERTILIZE_PLOT, ACT_MOVE_LOOT, ACT_MULTIPLE_BUTCHER, ACT_MULTIPLE_CHOP_PLANKS, ACT_MULTIPLE_CHOP_TREES, ACT_MULTIPLE_CONSTRUCTION, ACT_MULTIPLE_DIS, ACT_MULTIPLE_FARM, ACT_MULTIPLE_MINE, ACT_MULTIPLE_MOP, ACT_VEHICLE_DECONSTRUCTION, ACT_VEHICLE_REPAIR, add_msg(), uilist::addentry_desc(), Character::assign_activity(), zone_manager::cache_data(), Character::cache_has_item_with(), zone_manager::cache_vzones(), debugmsg, uilist::desc_enabled, flag_FERTILIZER, g, zone_data::get_enabled(), zone_data::get_is_personal(), zone_manager::get_manager(), zone_manager::get_name_from_type(), get_player_character(), zone_manager::get_zones(), zone_manager::has_personal_zones(), m_info, Creature::pos(), uilist::query(), zone_manager::reset_disabled(), uilist::ret, zone_data::set_enabled(), zone_data::set_temporary_disabled(), uilist::text, zone_type_CHOP_TREES, zone_type_CONSTRUCTION_BLUEPRINT, zone_type_DISASSEMBLE, zone_type_FARM_PLOT, zone_type_LOOT_CORPSE, zone_type_LOOT_UNSORTED, zone_type_LOOT_WOOD, zone_type_MINING, zone_type_MOPPING, zone_type_STRIP_CORPSES, zone_type_UNLOAD_ALL, zone_type_VEHICLE_DECONSTRUCT, and zone_type_VEHICLE_REPAIR.
Referenced by advanced_inventory_pane::add_items_from_area(), game::do_regular_action(), and jmapgen_objects::load_objects().
open()
static void open () static
Definition at line 574 of file handle_action.cpp.
 {
     avatar &player_character = get_avatar();
     const std::optional<tripoint> openp_ = choose_adjacent_highlight( _( "Open where?" ),
                                            pgettext( "no door, gate, curtain, etc.", "There is nothing that can be opened nearby." ),
                                            ACTION_OPEN, false );
     if( !openp_ ) {
         return;
     }
     const tripoint openp = *openp_;
     map &here = get_map();
     player_character.mod_moves( -to_moves<int>( 1_seconds ) );
     // Is a vehicle part here?
     if( const optional_vpart_position vp = here.veh_at( openp ) ) {
         vehicle *const veh = &vp->vehicle();
         // Check for potential thievery, and restore moves if action is canceled
         if( !veh->handle_potential_theft( player_character ) ) {
             player_character.mod_moves( to_moves<int>( 1_seconds ) );
             return;
         }
         // Check if vehicle has a part here that can be opened
         int openable = veh->next_part_to_open( vp->part_index() );
         if( openable >= 0 ) {
             // If player is inside vehicle, open the door/window/curtain
             const vehicle *player_veh = veh_pointer_or_null( here.veh_at( player_character.pos() ) );
             const std::string part_name = veh->part( openable ).name();
             bool outside = !player_veh || player_veh != veh;
             if( !outside ) {
                 veh->open( openable );
                 //~ %1$s - vehicle name, %2$s - part name
                 player_character.add_msg_if_player( _( "You open the %1$s's %2$s." ), veh->name, part_name );
             } else {
                 // Outside means we check if there's anything in that tile outside-openable.
                 // If there is, we open everything on tile. This means opening a closed,
                 // curtained door from outside is possible, but it will magically open the
                 // curtains as well.
                 int outside_openable = veh->next_part_to_open( vp->part_index(), true );
                 if( outside_openable == -1 ) {
                     add_msg( m_info, _( "That %s can only be opened from the inside." ), part_name );
                     player_character.mod_moves( to_moves<int>( 1_seconds ) );
                 } else {
                     veh->open_all_at( openable );
                     //~ %1$s - vehicle name, %2$s - part name
                     player_character.add_msg_if_player( _( "You open the %1$s's %2$s." ), veh->name, part_name );
                 }
             }
         } else {
             // If there are any OPENABLE parts here, they must be already open or locked
             if( const std::optional<vpart_reference> openable_part = vp.part_with_feature( "OPENABLE",
                     true ); openable_part.has_value() ) {
                 const std::string name = openable_part->info().name();
                 if( vp->vehicle().part( openable_part->part_index() ).locked ) {
                     add_msg( m_info, _( "That %s is locked." ), name );
                 } else {
                     add_msg( m_info, _( "That %s is already open." ), name );
                 }
             }
             player_character.mod_moves( to_moves<int>( 1_seconds ) );
         }
         return;
     }
     // Not a vehicle part, just a regular door
     bool didit = here.open_door( player_character, openp, !here.is_outside( player_character.pos() ) );
     if( didit ) {
         player_character.add_msg_if_player( _( "You open the %s." ), here.name( openp ) );
     } else {
         const ter_str_id tid = here.ter( openp ).id();
         if( here.has_flag( ter_furn_flag::TFLAG_LOCKED, openp ) ) {
             add_msg( m_info, _( "The door is locked!" ) );
             return;
         } else if( tid.obj().close ) {
             // if the following message appears unexpectedly, the prior check was for t_door_o
             add_msg( m_info, _( "That door is already open." ) );
             player_character.mod_moves( to_moves<int>( 1_seconds ) );
             return;
         }
         add_msg( m_info, _( "No door there." ) );
         player_character.mod_moves( to_moves<int>( 1_seconds ) );
     }
 }
References _, ACTION_OPEN, add_msg(), Character::add_msg_if_player(), choose_adjacent_highlight(), ter_t::close, get_avatar(), get_map(), vehicle::handle_potential_theft(), map::has_flag(), int_id< T >::id(), map::is_outside(), m_info, Creature::mod_moves(), vehicle_part::name(), map::name(), om_direction::name(), vehicle::name, vehicle::next_part_to_open(), string_id< T >::obj(), vehicle::open(), vehicle::open_all_at(), map::open_door(), vehicle::part(), pgettext, Creature::pos(), map::ter(), TFLAG_LOCKED, map::veh_at(), veh_pointer_or_null(), and vehicle::vehicle().
Referenced by cardreader_examine_actor::apply(), cardreader_examine_actor::call(), iexamine::cardreader_foodplace(), vehicle_part::deserialize(), explosion_handler::do_blast(), game::do_regular_action(), pf::greedy_path(), mmap_file::map_file(), gates::open_gate(), map::propagate_field(), vehicle_part::serialize(), and vehicle_caching_internal().
open_movement_mode_menu()
static void open_movement_mode_menu () static
Definition at line 1685 of file handle_action.cpp.
 {
     avatar &player_character = get_avatar();
     const std::vector<move_mode_id> &modes = move_modes_by_speed();
     const int cycle = 1027;
     uilist as_m;
     as_m.text = _( "Change to which movement mode?" );
     for( size_t i = 0; i < modes.size(); ++i ) {
         const move_mode_id &curr = modes[i];
         as_m.entries.emplace_back( static_cast<int>( i ), player_character.can_switch_to( curr ),
                                    curr->letter(),
                                    curr->name() );
     }
     as_m.entries.emplace_back( cycle,
                                player_character.can_switch_to( player_character.current_movement_mode()->cycle() ),
                                hotkey_for_action( ACTION_OPEN_MOVEMENT, /*maximum_modifier_count=*/1 ),
                                _( "Cycle move mode" ) );
     // This should select the middle move mode
     as_m.selected = std::floor( modes.size() / 2 );
     as_m.query();
     if( as_m.ret != UILIST_CANCEL ) {
         if( as_m.ret == cycle ) {
             player_character.cycle_move_mode();
         } else {
             player_character.set_movement_mode( modes[as_m.ret] );
         }
     }
 }
References _, ACTION_OPEN_MOVEMENT, Character::can_switch_to(), Character::current_movement_mode(), move_mode::cycle(), avatar::cycle_move_mode(), uilist::entries, floor(), get_avatar(), hotkey_for_action(), move_mode::letter(), move_modes_by_speed(), move_mode::name(), uilist::query(), uilist::ret, uilist::selected, avatar::set_movement_mode(), uilist::text, and UILIST_CANCEL.
Referenced by game::do_regular_action().
pldrive() [1/2]
static void pldrive (const tripoint & p) static
Definition at line 489 of file handle_action.cpp.
 {
     if( !g->check_safe_mode_allowed() ) {
         return;
     }
     vehicle *veh = g->remoteveh();
     bool remote = true;
     int part = -1;
     Character &player_character = get_player_character();
     map &here = get_map();
     if( !veh ) {
         if( const optional_vpart_position vp = here.veh_at( player_character.pos() ) ) {
             veh = &vp->vehicle();
             part = vp->part_index();
         }
         remote = false;
     }
     if( !veh ) {
         dbg( D_ERROR ) << "game::pldrive: can't find vehicle!  Drive mode is now off.";
         debugmsg( "game::pldrive error: can't find vehicle!  Drive mode is now off." );
         player_character.in_vehicle = false;
         return;
     }
     if( veh->is_on_ramp && p.x != 0 ) {
         add_msg( m_bad, _( "You can't turn the vehicle while on a ramp." ) );
         return;
     }
     if( !remote ) {
         const vehicle_part &vp = veh->part( part );
         const bool has_animal_controls = veh->part_with_feature( vp.mount, "CONTROL_ANIMAL", true ) >= 0;
         const bool has_controls = veh->part_with_feature( vp.mount, "CONTROLS", true ) >= 0;
         const bool has_animal = veh->has_engine_type( fuel_type_animal, false ) &&
                                 veh->get_harnessed_animal();
         if( !has_controls && !has_animal_controls ) {
             add_msg( m_info, _( "You can't drive the vehicle from here.  You need controls!" ) );
             player_character.controlling_vehicle = false;
             return;
         } else if( !has_controls && has_animal_controls && !has_animal ) {
             add_msg( m_info, _( "You can't drive this vehicle without an animal to pull it." ) );
             player_character.controlling_vehicle = false;
             return;
         }
     } else {
         if( empty( veh->get_avail_parts( "REMOTE_CONTROLS" ) ) ) {
             add_msg( m_info, _( "Can't drive this vehicle remotely.  It has no working controls." ) );
             return;
         }
     }
     if( p.z != 0 ) {
         if( !veh->can_control_in_air( player_character ) ) {
             player_character.add_msg_if_player( m_info, _( "You have no idea how to make the vehicle fly." ) );
             return;
         }
         if( !veh->is_flyable() ) {
             player_character.add_msg_if_player( m_info, _( "This vehicle doesn't look very airworthy." ) );
             return;
         }
     }
     if( p.z == -1 ) {
         if( veh->check_heli_descend( player_character ) ) {
             player_character.add_msg_if_player( m_info, _( "You steer the vehicle into a descent." ) );
         } else {
             return;
         }
     } else if( p.z == 1 ) {
         if( veh->check_heli_ascend( player_character ) ) {
             player_character.add_msg_if_player( m_info, _( "You steer the vehicle into an ascent." ) );
         } else {
             return;
         }
     }
     if( !veh->is_flying_in_air() ) {
         if( !veh->can_control_on_land( player_character ) ) {
             player_character.add_msg_if_player( m_info, _( "You have no idea how to make the vehicle move." ) );
             return;
         }
     }
     veh->pldrive( get_avatar(), p.xy(), p.z );
 }
References _, add_msg(), Character::add_msg_if_player(), vehicle::can_control_in_air(), vehicle::can_control_on_land(), vehicle::check_heli_ascend(), vehicle::check_heli_descend(), Character::controlling_vehicle, D_ERROR, dbg, debugmsg, fuel_type_animal, g, vehicle::get_avail_parts(), get_avatar(), vehicle::get_harnessed_animal(), get_map(), get_player_character(), vehicle::has_engine_type(), Character::in_vehicle, vehicle::is_flyable(), vehicle::is_flying_in_air(), vehicle::is_on_ramp, m_bad, m_info, vehicle_part::mount, vehicle::part(), vehicle::part_with_feature(), vehicle::pldrive(), Creature::pos(), map::veh_at(), vehicle::vehicle(), tripoint::x, tripoint::xy(), and tripoint::z.
Referenced by game::do_regular_action(), and pldrive().
pldrive() [2/2]
static void pldrive (point d) static
Definition at line 569 of file handle_action.cpp.
 {
     return pldrive( tripoint( d, 0 ) );
 }
References pldrive().
rcdrive()
static void rcdrive (const point & d) static
Definition at line 442 of file handle_action.cpp.
 {
     Character &player_character = get_player_character();
     map &here = get_map();
     std::stringstream car_location_string( player_character.get_value( "remote_controlling" ) );
     if( car_location_string.str().empty() ) {
         //no turned radio car found
         add_msg( m_warning, _( "No radio car connected." ) );
         return;
     }
     tripoint c;
     car_location_string >> c.x >> c.y >> c.z;
     auto rc_pairs = here.get_rc_items( c );
     auto rc_pair = rc_pairs.begin();
     for( ; rc_pair != rc_pairs.end(); ++rc_pair ) {
         if( rc_pair->second->has_flag( flag_RADIOCAR ) && rc_pair->second->active ) {
             break;
         }
     }
     if( rc_pair == rc_pairs.end() ) {
         add_msg( m_warning, _( "No radio car connected." ) );
         player_character.remove_value( "remote_controlling" );
         return;
     }
     item *rc_car = rc_pair->second;
     tripoint dest( c + d );
     if( here.impassable( dest ) || !here.can_put_items_ter_furn( dest ) ||
         here.has_furn( dest ) ) {
         sounds::sound( dest, 7, sounds::sound_t::combat,
                        _( "sound of a collision with an obstacle." ), true, "misc", "rc_car_hits_obstacle" );
         return;
     } else if( !here.add_item_or_charges( dest, *rc_car ).is_null() ) {
         tripoint src( c );
         //~ Sound of moving a remote controlled car
         sounds::sound( src, 6, sounds::sound_t::movement, _( "zzz" ), true, "misc", "rc_car_drives" );
         player_character.mod_moves( -to_moves<int>( 1_seconds ) * 0.5 );
         here.i_rem( src, rc_car );
         car_location_string.clear();
         car_location_string << dest.x << ' ' << dest.y << ' ' << dest.z;
         player_character.set_value( "remote_controlling", car_location_string.str() );
         return;
     }
 }
References _, map::add_item_or_charges(), add_msg(), c, map::can_put_items_ter_furn(), sounds::combat, flag_RADIOCAR, get_map(), get_player_character(), map::get_rc_items(), Creature::get_value(), map::has_furn(), map::i_rem(), map::impassable(), item::is_null(), m_warning, Creature::mod_moves(), sounds::movement, Creature::remove_value(), Creature::set_value(), sounds::sound(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by game::do_regular_action().
reach_attack()
static void reach_attack (avatar & you) static
Definition at line 1623 of file handle_action.cpp.
 {
     g->temp_exit_fullscreen();
     target_handler::trajectory traj = target_handler::mode_reach( you, you.get_wielded_item() );
     if( !traj.empty() ) {
         you.reach_attack( traj.back() );
     }
     g->reenter_fullscreen();
 }
References g, Character::get_wielded_item(), target_handler::mode_reach(), and Character::reach_attack().
Referenced by fire().
read()
static void read () static
Definition at line 1602 of file handle_action.cpp.
 {
     avatar &player_character = get_avatar();
     // Can read items from inventory or within one tile (including in vehicles)
     item_location loc = game_menus::inv::read( player_character );
     if( loc ) {
         if( loc->type->can_use( "learn_spell" ) ) {
             item spell_book = *loc.get_item();
             spell_book.get_use( "learn_spell" )->call( &player_character, spell_book,
                     player_character.pos() );
         } else {
             loc = loc.obtain( player_character );
             player_character.read( loc );
         }
     } else {
         add_msg( _( "Never mind." ) );
     }
 }
References _, add_msg(), use_function::call(), itype::can_use(), get_avatar(), item_location::get_item(), item::get_use(), item_location::obtain(), Creature::pos(), game_menus::inv::read(), avatar::read(), and item::type.
Referenced by game::do_regular_action(), and JsonValue::read().
sleep()
static void sleep () static
Definition at line 1223 of file handle_action.cpp.
 {
     avatar &player_character = get_avatar();
     if( player_character.is_mounted() ) {
         add_msg( m_info, _( "You cannot sleep while mounted." ) );
         return;
     }
     vehicle *const boat = veh_pointer_or_null( get_map().veh_at( player_character.pos() ) );
     if( get_map().has_flag( ter_furn_flag::TFLAG_DEEP_WATER, player_character.pos() ) &&
         !player_character.has_trait( trait_WATERSLEEPER ) &&
         !player_character.has_trait( trait_WATERSLEEP ) &&
         !player_character.has_trait( trait_UNDINE_SLEEP_WATER ) &&
         boat == nullptr ) {
         add_msg( m_info, _( "You cannot sleep while swimming." ) );
         return;
     }
     uilist as_m;
     as_m.text = _( "<color_white>Are you sure you want to sleep?</color>" );
     // (Y)es/(S)ave before sleeping/(N)o
     as_m.entries.emplace_back( 0, true,
                                get_option<bool>( "FORCE_CAPITAL_YN" ) ? 'Y' : 'y',
                                _( "Yes." ) );
     as_m.entries.emplace_back( 1, g->get_moves_since_last_save(),
                                get_option<bool>( "FORCE_CAPITAL_YN" ) ? 'S' : 's',
                                _( "Yes, and save game before sleeping." ) );
     as_m.entries.emplace_back( 2, true,
                                get_option<bool>( "FORCE_CAPITAL_YN" ) ? 'N' : 'n',
                                _( "No." ) );
     // List all active items, bionics or mutations so player can deactivate them
     std::vector<std::string> active;
     for( item_location &it : player_character.all_items_loc() ) {
         if( it->has_flag( flag_LITCIG ) || ( it->active && it->ammo_sufficient( &player_character ) &&
                                              it->is_tool() && !it->has_flag( flag_SLEEP_IGNORE ) ) ) {
             active.push_back( it->tname() );
         }
     }
     for( int i = 0; i < player_character.num_bionics(); i++ ) {
         const bionic &bio = player_character.bionic_at_index( i );
         if( !bio.powered ) {
             continue;
         }
         // some bionics
         // bio_alarm is useful for waking up during sleeping
         if( bio.info().has_flag( STATIC( json_character_flag( "BIONIC_SLEEP_FRIENDLY" ) ) ) ) {
             continue;
         }
         const bionic_data &info = bio.info();
         if( info.power_over_time > 0_kJ ) {
             active.push_back( info.name.translated() );
         }
     }
     for( auto &mut : player_character.get_mutations() ) {
         const mutation_branch &mdata = mut.obj();
         if( mdata.cost > 0 && player_character.has_active_mutation( mut ) ) {
             active.push_back( player_character.mutation_name( mut ) );
         }
     }
     // check for deactivating any currently played music instrument.
     for( item *&item : player_character.inv_dump() ) {
         if( item->active && item->get_use( "musical_instrument" ) != nullptr ) {
             player_character.add_msg_if_player( _( "You stop playing your %s before trying to sleep." ),
                                                 item->tname() );
             // deactivate instrument
             item->active = false;
         }
     }
     // ask for deactivation
     std::stringstream data;
     if( !active.empty() ) {
         as_m.selected = 2;
         data << as_m.text << std::endl;
         data << _( "You may want to extinguish or turn off:" ) << std::endl;
         data << " " << std::endl;
         for( auto &a : active ) {
             data << "<color_red>" << a << "</color>" << std::endl;
         }
         as_m.text = data.str();
     }
     /* Calculate key and window variables, generate window,
        and loop until we get a valid answer. */
     as_m.query();
     if( as_m.ret == 1 ) {
         g->quicksave();
     } else if( as_m.ret == 2 || as_m.ret < 0 ) {
         return;
     }
     time_duration try_sleep_dur = 24_hours;
     std::string deaf_text;
     if( player_character.is_deaf() && !player_character.has_flag( json_flag_ALARMCLOCK ) ) {
         deaf_text = _( "<color_c_red> (DEAF!)</color>" );
     }
     if( player_character.has_alarm_clock() ) {
         /* Reuse menu to ask player whether they want to set an alarm. */
         bool can_hibernate = player_character.get_hunger() < -60 &&
                              player_character.has_active_mutation( trait_HIBERNATE );
         as_m.reset();
         as_m.text = can_hibernate ?
                     _( "You're engorged to hibernate.  The alarm would only attract attention.  "
                        "Set an alarm anyway?" ) :
                     _( "You have an alarm clock.  Set an alarm?" );
         as_m.text += deaf_text;
         as_m.entries.emplace_back( 0, true,
                                    get_option<bool>( "FORCE_CAPITAL_YN" ) ? 'N' : 'n',
                                    _( "No, don't set an alarm." ) );
         for( int i = 3; i <= 9; ++i ) {
             as_m.entries.emplace_back( i, true, '0' + i,
                                        string_format( _( "Set alarm to wake up in %i hours." ), i ) + deaf_text );
         }
         as_m.query();
         if( as_m.ret >= 3 && as_m.ret <= 9 ) {
             player_character.add_effect( effect_alarm_clock, 1_hours * as_m.ret );
             try_sleep_dur = 1_hours * as_m.ret + 1_turns;
         } else if( as_m.ret < 0 ) {
             return;
         }
     }
     player_character.set_moves( 0 );
     player_character.try_to_sleep( try_sleep_dur );
 }
References _, a, item::active, Creature::add_effect(), add_msg(), Character::add_msg_if_player(), Character::all_items_loc(), Character::bionic_at_index(), mutation_branch::cost, effect_alarm_clock, uilist::entries, flag_LITCIG, flag_SLEEP_IGNORE, g, get_avatar(), Character::get_hunger(), get_map(), Character::get_mutations(), item::get_use(), Character::has_active_mutation(), Character::has_alarm_clock(), bionic_data::has_flag(), Character::has_flag(), Character::has_trait(), bionic::info(), Character::inv_dump(), Character::is_deaf(), Character::is_mounted(), json_flag_ALARMCLOCK, m_info, Character::mutation_name(), bionic_data::name, Character::num_bionics(), Creature::pos(), bionic_data::power_over_time, bionic::powered, uilist::query(), uilist::reset(), uilist::ret, uilist::selected, Creature::set_moves(), STATIC, string_format(), uilist::text, TFLAG_DEEP_WATER, item::tname(), trait_HIBERNATE, trait_UNDINE_SLEEP_WATER, trait_WATERSLEEP, trait_WATERSLEEPER, translation::translated(), avatar::try_to_sleep(), and veh_pointer_or_null().
Referenced by Character::calc_needs_rates(), Character::calc_sleep_recovery_rate(), game::do_regular_action(), and Character::update_needs().
smash()
static void smash () static
Definition at line 868 of file handle_action.cpp.
 {
     avatar &player_character = get_avatar();
     map &here = get_map();
     if( player_character.is_mounted() ) {
         auto *mons = player_character.mounted_creature.get();
         if( mons->has_flag( mon_flag_RIDEABLE_MECH ) ) {
             if( !mons->check_mech_powered() ) {
                 add_msg( m_bad, _( "Your %s refuses to move as its batteries have been drained." ),
                          mons->get_name() );
                 return;
             }
         }
     }
     const int move_cost = !player_character.is_armed() ? 80 :
                           player_character.get_wielded_item()->attack_time( player_character ) *
                           0.8;
     bool mech_smash = false;
     int smashskill = player_character.smash_ability();
     if( player_character.is_mounted() ) {
         mech_smash = true;
     }
     const bool allow_floor_bash = debug_mode; // Should later become "true"
     const std::optional<tripoint> smashp_ = choose_adjacent( _( "Smash where?" ), allow_floor_bash );
     if( !smashp_ ) {
         return;
     }
     tripoint smashp = *smashp_;
     bool smash_floor = false;
     if( smashp.z != player_character.posz() ) {
         if( smashp.z > player_character.posz() ) {
             // TODO: Knock on the ceiling
             return;
         }
         smashp.z = player_character.posz();
         smash_floor = true;
     }
     get_event_bus().send<event_type::character_smashes_tile>(
         player_character.getID(), here.ter( smashp ).id(), here.furn( smashp ).id() );
     if( player_character.is_mounted() ) {
         monster *crit = player_character.mounted_creature.get();
         if( crit->has_flag( mon_flag_RIDEABLE_MECH ) ) {
             crit->use_mech_power( 3_kJ );
         }
     }
     for( std::pair<const field_type_id, field_entry> &fd_to_smsh : here.field_at( smashp ) ) {
         const map_bash_info &bash_info = fd_to_smsh.first->bash_info;
         if( bash_info.str_min == -1 ) {
             continue;
         }
         if( smashskill < bash_info.str_min && one_in( 10 ) ) {
             add_msg( m_neutral, _( "You don't seem to be damaging the %s." ), fd_to_smsh.first->get_name() );
             return;
         } else if( smashskill >= rng( bash_info.str_min, bash_info.str_max ) ) {
             sounds::sound( smashp, bash_info.sound_vol, sounds::sound_t::combat, bash_info.sound, true, "smash",
                            "field" );
             here.remove_field( smashp, fd_to_smsh.first );
             here.spawn_items( smashp, item_group::items_from( bash_info.drop_group, calendar::turn ) );
             player_character.mod_moves( - bash_info.fd_bash_move_cost );
             add_msg( m_info, bash_info.field_bash_msg_success.translated() );
             return;
         } else {
             sounds::sound( smashp, bash_info.sound_fail_vol, sounds::sound_t::combat, bash_info.sound_fail,
                            true, "smash",
                            "field" );
             return;
         }
     }
     bool should_pulp = false;
     for( const item &maybe_corpse : here.i_at( smashp ) ) {
         if( maybe_corpse.is_corpse() && maybe_corpse.damage() < maybe_corpse.max_damage() &&
             maybe_corpse.can_revive() ) {
             if( maybe_corpse.get_mtype()->bloodType()->has_acid &&
                 !player_character.is_immune_field( fd_acid ) ) {
                 if( !query_yn( _( "Are you sure you want to pulp an acid filled corpse?" ) ) ) {
                     return; // Player doesn't want an acid bath
                 }
             }
             should_pulp = true; // There is at least one corpse to pulp
         }
     }
     if( should_pulp ) {
         // do activity forever. ACT_PULP stops itself
         player_character.assign_activity( ACT_PULP, calendar::INDEFINITELY_LONG, 0 );
         player_character.activity.placement = here.getglobal( smashp );
         return; // don't smash terrain if we've smashed a corpse
     }
     vehicle *veh = veh_pointer_or_null( here.veh_at( smashp ) );
     if( veh != nullptr ) {
         if( !veh->handle_potential_theft( player_character ) ) {
             return;
         }
     }
     if( !player_character.has_weapon() ) {
         const bodypart_id bp_null( "bp_null" );
         std::pair<bodypart_id, int> best_part_to_smash = player_character.best_part_to_smash();
         if( best_part_to_smash.first != bp_null && here.is_bashable( smashp ) ) {
             std::string name_to_bash = _( "thing" );
             if( here.is_bashable_furn( smashp ) ) {
                 name_to_bash = here.furnname( smashp );
             } else if( here.is_bashable_ter( smashp ) ) {
                 name_to_bash = here.tername( smashp );
             }
             if( !best_part_to_smash.first->smash_message.empty() ) {
                 add_msg( best_part_to_smash.first->smash_message, name_to_bash );
             } else {
                 add_msg( _( "You use your %s to smash the %s." ),
                          body_part_name_accusative( best_part_to_smash.first ), name_to_bash );
             }
         }
     }
     const bash_params bash_result = here.bash( smashp, smashskill, false, false, smash_floor );
     // Weariness scaling
     float weary_mult = 1.0f;
     item_location weapon = player_character.used_weapon();
     if( bash_result.did_bash ) {
         if( !mech_smash ) {
             player_character.set_activity_level( MODERATE_EXERCISE );
             player_character.handle_melee_wear( weapon );
             weary_mult = 1.0f / player_character.exertion_adjusted_move_multiplier( MODERATE_EXERCISE );
             const int mod_sta = 2 * player_character.get_standard_stamina_cost();
             player_character.burn_energy_arms( mod_sta );
             if( static_cast<int>( player_character.get_skill_level( skill_melee ) ) == 0 ) {
                 player_character.practice( skill_melee, rng( 0, 1 ) * rng( 0, 1 ) );
             }
             if( weapon ) {
                 const int glass_portion = weapon->made_of( material_glass );
                 float glass_fraction = glass_portion / static_cast<float>( weapon->type->mat_portion_total );
                 if( std::isnan( glass_fraction ) || glass_fraction > 1.f ) {
                     glass_fraction = 0.f;
                 }
                 const int vol = weapon->volume() * glass_fraction / units::legacy_volume_factor;
                 if( glass_portion && rng( 0, vol + 3 ) < vol ) {
                     add_msg( m_bad, _( "Your %s shatters!" ), weapon->tname() );
                     weapon->spill_contents( player_character.pos() );
                     sounds::sound( player_character.pos(), 24, sounds::sound_t::combat, "CRACK!", true, "smash",
                                    "glass" );
                     player_character.deal_damage( nullptr, bodypart_id( "hand_r" ), damage_instance( damage_cut,
                                                   rng( 0,
                                                        vol ) ) );
                     if( vol > 20 ) {
                         // Hurt left arm too, if it was big
                         player_character.deal_damage( nullptr, bodypart_id( "hand_l" ), damage_instance( damage_cut,
                                                       rng( 0,
                                                            static_cast<int>( vol * .5 ) ) ) );
                     }
                     player_character.remove_weapon();
                     player_character.check_dead_state();
                 }
             }
         }
         player_character.mod_moves( -move_cost * weary_mult );
         player_character.recoil = MAX_RECOIL;
         if( bash_result.success ) {
             // Bash results in destruction of target
             g->draw_async_anim( smashp, "bash_complete", "X", c_light_gray );
         } else if( smashskill >= here.bash_resistance( smashp ) ) {
             // Bash effective but target not yet destroyed
             g->draw_async_anim( smashp, "bash_effective", "/", c_light_gray );
         } else {
             // Bash not effective
             g->draw_async_anim( smashp, "bash_ineffective" );
             if( one_in( 10 ) ) {
                 if( here.has_furn( smashp ) && here.furn( smashp ).obj().bash.str_min != -1 ) {
                     // %s is the smashed furniture
                     add_msg( m_neutral, _( "You don't seem to be damaging the %s." ), here.furnname( smashp ) );
                 } else {
                     // %s is the smashed terrain
                     add_msg( m_neutral, _( "You don't seem to be damaging the %s." ), here.tername( smashp ) );
                 }
             }
         }
     } else {
         add_msg( _( "There's nothing there to smash!" ) );
     }
 }
References _, ACT_PULP, Character::activity, add_msg(), Character::assign_activity(), item::attack_time(), map::bash(), map_data_common_t::bash, map::bash_resistance(), Character::best_part_to_smash(), body_part_name_accusative(), Character::burn_energy_arms(), c_light_gray, character_smashes_tile, Creature::check_dead_state(), choose_adjacent(), sounds::combat, damage_cut, Character::deal_damage(), debug_mode, bash_params::did_bash, map_bash_info::drop_group, Character::exertion_adjusted_move_multiplier(), fd_acid, map_bash_info::fd_bash_move_cost, map::field_at(), map_bash_info::field_bash_msg_success, map::furn(), map::furnname(), g, get_avatar(), get_event_bus(), get_map(), Character::get_skill_level(), Character::get_standard_stamina_cost(), Character::get_wielded_item(), map::getglobal(), Character::getID(), Character::handle_melee_wear(), vehicle::handle_potential_theft(), monster::has_flag(), map::has_furn(), Character::has_weapon(), map::i_at(), int_id< T >::id(), calendar::INDEFINITELY_LONG, Character::is_armed(), map::is_bashable(), map::is_bashable_furn(), map::is_bashable_ter(), Character::is_immune_field(), Character::is_mounted(), item_group::items_from(), units::legacy_volume_factor, m_bad, m_info, m_neutral, item::made_of(), itype::mat_portion_total, material_glass, MAX_RECOIL, Creature::mod_moves(), MODERATE_EXERCISE, mon_flag_RIDEABLE_MECH, Character::mounted_creature, int_id< T >::obj(), one_in(), player_activity::placement, Creature::pos(), Creature::posz(), Character::practice(), query_yn(), Character::recoil, map::remove_field(), Character::remove_weapon(), rng(), event_bus::send(), Character::set_activity_level(), skill_melee, Character::smash_ability(), map_bash_info::sound, sounds::sound(), map_bash_info::sound_fail, map_bash_info::sound_fail_vol, map_bash_info::sound_vol, map::spawn_items(), item::spill_contents(), map_bash_info::str_max, map_bash_info::str_min, bash_params::success, map::ter(), map::tername(), item::tname(), translation::translated(), calendar::turn, item::type, monster::use_mech_power(), Character::used_weapon(), map::veh_at(), veh_pointer_or_null(), item::volume(), and tripoint::z.
Referenced by game::do_regular_action(), and mattack::smash_specific().
takeoff()
static void takeoff () static
Definition at line 1590 of file handle_action.cpp.
 {
     avatar &player_character = get_avatar();
     item_location loc = game_menus::inv::take_off( player_character );
     if( loc ) {
         player_character.takeoff( loc.obtain( player_character ) );
     } else {
         add_msg( _( "Never mind." ) );
     }
 }
References _, add_msg(), get_avatar(), item_location::obtain(), game_menus::inv::take_off(), and Character::takeoff().
Referenced by game::do_regular_action().
try_set_alarm()
static int try_set_alarm () static
Definition at line 1057 of file handle_action.cpp.
 {
     uilist as_m;
     const bool already_set = get_player_character().has_effect( effect_alarm_clock );
     as_m.text = already_set ?
                 _( "You already have an alarm set.  What do you want to do?" ) :
                 _( "You have an alarm clock.  What do you want to do?" );
     as_m.entries.emplace_back( 0, true, 'w', already_set ?
                                _( "Keep the alarm and wait a while" ) :
                                _( "Wait a while" ) );
     as_m.entries.emplace_back( 1, true, 'a', already_set ?
                                _( "Change your alarm" ) :
                                _( "Set an alarm for later" ) );
     as_m.query();
     return as_m.ret;
 }
References _, effect_alarm_clock, uilist::entries, get_player_character(), Creature::has_effect(), uilist::query(), uilist::ret, and uilist::text.
Referenced by wait().
wait()
static void wait () static
Definition at line 1077 of file handle_action.cpp.
 {
     std::map<int, time_duration> durations;
     uilist as_m;
     Character &player_character = get_player_character();
     bool setting_alarm = false;
     map &here = get_map();
     if( player_character.controlling_vehicle ) {
         const vehicle &veh = here.veh_at( player_character.pos() )->vehicle();
         if( !veh.can_use_rails() && (   // control optional if on rails
                 veh.is_flying_in_air() ||   // control required: fuel is consumed even at hover
                 veh.is_falling ||           // *not* vertical_velocity, which is only used for collisions
                 veh.velocity ||             // is moving
                 ( veh.cruise_velocity && (  // would move if it could
                       ( veh.is_watercraft() && veh.can_float() ) || // is viable watercraft floating on water
                       veh.sufficient_wheel_config() // is viable land vehicle on ground or fording shallow water
                   ) ) ||
                 ( veh.is_in_water( true ) && !veh.can_float() ) // is sinking in deep water
             ) ) {
             popup( _( "You can't pass time while controlling a moving vehicle." ) );
             return;
         }
     }
     if( player_character.has_alarm_clock() ) {
         int alarm_query = try_set_alarm();
         if( alarm_query == UILIST_CANCEL ) {
             return;
         }
         setting_alarm = alarm_query == 1;
     }
     const bool has_watch = player_character.has_watch() || setting_alarm;
     const auto add_menu_item = [ &as_m, &durations, has_watch ]
                                ( int retval, int hotkey, const std::string &caption = "",
     const time_duration &duration = time_duration::from_turns( calendar::INDEFINITELY_LONG ) ) {
         std::string text( caption );
         if( has_watch && duration != time_duration::from_turns( calendar::INDEFINITELY_LONG ) ) {
             const std::string dur_str( to_string( duration ) );
             text += ( text.empty() ? dur_str : string_format( " (%s)", dur_str ) );
         }
         as_m.addentry( retval, true, hotkey, text );
         durations.emplace( retval, duration );
     };
     if( setting_alarm ) {
         add_menu_item( 0, '0', "", 30_minutes );
         for( int i = 1; i <= 9; ++i ) {
             add_menu_item( i, '0' + i, "", i * 1_hours );
         }
     } else {
         if( player_character.get_stamina() < player_character.get_stamina_max() ) {
             as_m.addentry( 14, true, 'w', _( "Wait until you catch your breath" ) );
             durations.emplace( 14, 15_minutes ); // to hide it from showing
         }
         add_menu_item( 1, '1', !has_watch ? _( "Wait 20 heartbeats" ) : "", 20_seconds );
         add_menu_item( 2, '2', !has_watch ? _( "Wait 60 heartbeats" ) : "", 1_minutes );
         add_menu_item( 3, '3', !has_watch ? _( "Wait 300 heartbeats" ) : "", 5_minutes );
         add_menu_item( 4, '4', !has_watch ? _( "Wait 1800 heartbeats" ) : "", 30_minutes );
         if( has_watch ) {
             add_menu_item( 5, '5', "", 1_hours );
             add_menu_item( 6, '6', "", 2_hours );
             add_menu_item( 7, '7', "", 3_hours );
             add_menu_item( 8, '8', "", 6_hours );
         }
     }
     if( here.get_abs_sub().z() >= 0 || has_watch ) {
         const time_point last_midnight = calendar::turn - time_past_midnight( calendar::turn );
         const auto diurnal_time_before = []( const time_point & p ) {
             // Either the given time is in the future (e.g. waiting for sunset while it's early morning),
             // than use it directly. Otherwise (in the past), add a single day to get the same time tomorrow
             // (e.g. waiting for sunrise while it's noon).
             const time_point target_time = p > calendar::turn ? p : p + 1_days;
             return target_time - calendar::turn;
         };
         add_menu_item( 9,  'd',
                        setting_alarm ? _( "Set alarm for dawn" ) : _( "Wait till daylight" ),
                        diurnal_time_before( daylight_time( calendar::turn ) ) );
         add_menu_item( 10,  'n',
                        setting_alarm ? _( "Set alarm for noon" ) : _( "Wait till noon" ),
                        diurnal_time_before( last_midnight + 12_hours ) );
         add_menu_item( 11,  'k',
                        setting_alarm ? _( "Set alarm for dusk" ) : _( "Wait till night" ),
                        diurnal_time_before( night_time( calendar::turn ) ) );
         add_menu_item( 12, 'm',
                        setting_alarm ? _( "Set alarm for midnight" ) : _( "Wait till midnight" ),
                        diurnal_time_before( last_midnight ) );
         if( setting_alarm ) {
             if( player_character.has_effect( effect_alarm_clock ) ) {
                 add_menu_item( 13, 'x', _( "Cancel the currently set alarm." ),
                                0_turns );
             }
         } else {
             add_menu_item( 13, 'W', _( "Wait till weather changes" ) );
         }
     }
     // NOLINTNEXTLINE(cata-text-style): spaces required for concatenation
     as_m.text = has_watch ? string_format( _( "It's %s now.  " ),
                                            to_string_time_of_day( calendar::turn ) ) : "";
     as_m.text += setting_alarm ? _( "Set alarm for when?" ) : _( "Wait for how long?" );
     as_m.query(); /* calculate key and window variables, generate window, and loop until we get a valid answer */
     const auto dur_iter = durations.find( as_m.ret );
     if( dur_iter == durations.end() ) {
         return;
     }
     const time_duration time_to_wait = dur_iter->second;
     if( setting_alarm ) {
         // Setting alarm
         player_character.remove_effect( effect_alarm_clock );
         if( as_m.ret == 13 ) {
             add_msg( _( "You cancel your alarm." ) );
         } else {
             player_character.add_effect( effect_alarm_clock, time_to_wait );
             add_msg( _( "You set your alarm." ) );
         }
     } else {
         // Waiting
         activity_id actType;
         if( as_m.ret == 13 ) {
             actType = ACT_WAIT_WEATHER;
         } else if( as_m.ret == 14 ) {
             actType = ACT_WAIT_STAMINA;
         } else {
             actType = ACT_WAIT;
         }
         player_activity new_act( actType, 100 * to_turns<int>( time_to_wait ), 0 );
         player_character.assign_activity( new_act );
     }
 }
References _, ACT_WAIT, ACT_WAIT_STAMINA, ACT_WAIT_WEATHER, Creature::add_effect(), add_msg(), uilist::addentry(), Character::assign_activity(), vehicle::can_float(), vehicle::can_use_rails(), Character::controlling_vehicle, vehicle::cruise_velocity, daylight_time(), effect_alarm_clock, time_duration::from_turns(), map::get_abs_sub(), get_map(), get_player_character(), Character::get_stamina(), Character::get_stamina_max(), Character::has_alarm_clock(), Creature::has_effect(), Character::has_watch(), calendar::INDEFINITELY_LONG, vehicle::is_falling, vehicle::is_flying_in_air(), vehicle::is_in_water(), vehicle::is_watercraft(), night_time(), popup(), Creature::pos(), uilist::query(), Creature::remove_effect(), uilist::ret, string_format(), vehicle::sufficient_wheel_config(), uilist::text, time_past_midnight(), to_string(), to_string_time_of_day(), try_set_alarm(), calendar::turn, UILIST_CANCEL, map::veh_at(), vehicle::velocity, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by game::do_regular_action().
wear()
static void wear () static
Definition at line 1578 of file handle_action.cpp.
 {
     avatar &player_character = get_avatar();
     item_location loc = game_menus::inv::wear( player_character );
     if( loc ) {
         player_character.wear( loc );
     } else {
         add_msg( _( "Never mind." ) );
     }
 }
References _, add_msg(), get_avatar(), game_menus::inv::wear(), and Character::wear().
Referenced by game::do_regular_action().
Variable Documentation
ACT_FERTILIZE_PLOT
const activity_id ACT_FERTILIZE_PLOT("ACT_FERTILIZE_PLOT") ("ACT_FERTILIZE_PLOT") static
Referenced by loot().
ACT_MOVE_LOOT
const activity_id ACT_MOVE_LOOT("ACT_MOVE_LOOT") ("ACT_MOVE_LOOT") static
Referenced by loot().
ACT_MULTIPLE_BUTCHER
const activity_id ACT_MULTIPLE_BUTCHER("ACT_MULTIPLE_BUTCHER") ("ACT_MULTIPLE_BUTCHER") static
Referenced by loot().
ACT_MULTIPLE_CHOP_PLANKS
const activity_id ACT_MULTIPLE_CHOP_PLANKS("ACT_MULTIPLE_CHOP_PLANKS") ("ACT_MULTIPLE_CHOP_PLANKS") static
Referenced by loot().
ACT_MULTIPLE_CHOP_TREES
const activity_id ACT_MULTIPLE_CHOP_TREES("ACT_MULTIPLE_CHOP_TREES") ("ACT_MULTIPLE_CHOP_TREES") static
Referenced by loot().
ACT_MULTIPLE_CONSTRUCTION
const activity_id ACT_MULTIPLE_CONSTRUCTION("ACT_MULTIPLE_CONSTRUCTION") ("ACT_MULTIPLE_CONSTRUCTION") static
Referenced by loot().
ACT_MULTIPLE_DIS
const activity_id ACT_MULTIPLE_DIS("ACT_MULTIPLE_DIS") ("ACT_MULTIPLE_DIS") static
Referenced by loot().
ACT_MULTIPLE_FARM
const activity_id ACT_MULTIPLE_FARM("ACT_MULTIPLE_FARM") ("ACT_MULTIPLE_FARM") static
Referenced by loot().
ACT_MULTIPLE_MINE
const activity_id ACT_MULTIPLE_MINE("ACT_MULTIPLE_MINE") ("ACT_MULTIPLE_MINE") static
Referenced by loot().
ACT_MULTIPLE_MOP
const activity_id ACT_MULTIPLE_MOP("ACT_MULTIPLE_MOP") ("ACT_MULTIPLE_MOP") static
Referenced by loot().
ACT_PULP
const activity_id ACT_PULP("ACT_PULP") ("ACT_PULP") static
Referenced by smash().
ACT_SPELLCASTING
const activity_id ACT_SPELLCASTING("ACT_SPELLCASTING") ("ACT_SPELLCASTING") static
Referenced by Character::cast_spell().
ACT_VEHICLE_DECONSTRUCTION
const activity_id ACT_VEHICLE_DECONSTRUCTION("ACT_VEHICLE_DECONSTRUCTION") ("ACT_VEHICLE_DECONSTRUCTION") static
Referenced by loot().
ACT_VEHICLE_REPAIR
const activity_id ACT_VEHICLE_REPAIR("ACT_VEHICLE_REPAIR") ("ACT_VEHICLE_REPAIR") static
Referenced by loot().
ACT_WAIT
const activity_id ACT_WAIT("ACT_WAIT") ("ACT_WAIT") static
Referenced by wait().
ACT_WAIT_STAMINA
const activity_id ACT_WAIT_STAMINA("ACT_WAIT_STAMINA") ("ACT_WAIT_STAMINA") static
Referenced by wait().
ACT_WAIT_WEATHER
const activity_id ACT_WAIT_WEATHER("ACT_WAIT_WEATHER") ("ACT_WAIT_WEATHER") static
Referenced by wait().
actions_disabled_in_incorporeal
const std::set<action_id> actions_disabled_in_incorporeal static
Initial value:
{
    ACTION_OPEN,
    ACTION_CLOSE,
    ACTION_SMASH,
    ACTION_ADVANCEDINV,
    ACTION_PICKUP,
    ACTION_PICKUP_ALL,
    ACTION_GRAB,
    ACTION_HAUL,
    ACTION_HAUL_TOGGLE,
    ACTION_BUTCHER,
    ACTION_CRAFT,
    ACTION_RECRAFT,
    ACTION_LONGCRAFT,
    ACTION_DISASSEMBLE,
    ACTION_CONSTRUCT,
    ACTION_CONTROL_VEHICLE,
}
Definition at line 2072 of file handle_action.cpp.
Referenced by game::do_regular_action().
bio_remote
const bionic_id bio_remote("bio_remote") ("bio_remote") static
Referenced by game::do_regular_action().
damage_cut
const damage_type_id damage_cut("cut") ("cut") static
Referenced by smash().
effect_alarm_clock
const efftype_id effect_alarm_clock("alarm_clock") ("alarm_clock") static
Referenced by sleep(), try_set_alarm(), and wait().
effect_incorporeal
const efftype_id effect_incorporeal("incorporeal") ("incorporeal") static
Referenced by game::do_regular_action().
effect_laserlocked
const efftype_id effect_laserlocked("laserlocked") ("laserlocked") static
Referenced by game::do_regular_action().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by Character::cast_spell().
fuel_type_animal
const itype_id fuel_type_animal("animal") ("animal") static
Referenced by pldrive().
gun_mode_AUTO
const gun_mode_id gun_mode_AUTO("AUTO") ("AUTO") static
Referenced by game::do_regular_action().
itype_radiocontrol
const itype_id itype_radiocontrol("radiocontrol") ("radiocontrol") static
Referenced by game::do_regular_action().
json_flag_ALARMCLOCK
const json_character_flag json_flag_ALARMCLOCK("ALARMCLOCK") ("ALARMCLOCK") static
Referenced by sleep().
json_flag_MOP
const flag_id json_flag_MOP("MOP") ("MOP") static
Referenced by game::do_regular_action().
json_flag_NO_PSIONICS
const json_character_flag json_flag_NO_PSIONICS("NO_PSIONICS") ("NO_PSIONICS") static
Referenced by cast_spell().
json_flag_NO_SPELLCASTING
const json_character_flag json_flag_NO_SPELLCASTING("NO_SPELLCASTING") ("NO_SPELLCASTING") static
Referenced by cast_spell().
json_flag_SUBTLE_SPELL
const json_character_flag json_flag_SUBTLE_SPELL("SUBTLE_SPELL") ("SUBTLE_SPELL") static
Referenced by Character::cast_spell().
material_glass
const material_id material_glass("glass") ("glass") static
Referenced by smash().
qual_CUT
const quality_id qual_CUT("CUT") ("CUT") static
Referenced by Character::cast_spell().
skill_melee
const skill_id skill_melee("melee") ("melee") static
Referenced by smash().
trait_BRAWLER
const trait_id trait_BRAWLER("BRAWLER") ("BRAWLER") static
Referenced by fire().
trait_HIBERNATE
const trait_id trait_HIBERNATE("HIBERNATE") ("HIBERNATE") static
Referenced by sleep().
trait_PROF_CHURL
const trait_id trait_PROF_CHURL("PROF_CHURL") ("PROF_CHURL") static
Referenced by game::do_regular_action().
trait_SHELL2
const trait_id trait_SHELL2("SHELL2") ("SHELL2") static
Referenced by game::do_regular_action().
trait_SHELL3
const trait_id trait_SHELL3("SHELL3") ("SHELL3") static
Referenced by game::do_regular_action().
trait_UNDINE_SLEEP_WATER
const trait_id trait_UNDINE_SLEEP_WATER("UNDINE_SLEEP_WATER") ("UNDINE_SLEEP_WATER") static
Referenced by sleep().
trait_WATERSLEEP
const trait_id trait_WATERSLEEP("WATERSLEEP") ("WATERSLEEP") static
Referenced by sleep().
trait_WATERSLEEPER
const trait_id trait_WATERSLEEPER("WATERSLEEPER") ("WATERSLEEPER") static
Referenced by sleep().
trait_WAYFARER
const trait_id trait_WAYFARER("WAYFARER") ("WAYFARER") static
Referenced by game::do_regular_action().
zone_type_CHOP_TREES
const zone_type_id zone_type_CHOP_TREES("CHOP_TREES") ("CHOP_TREES") static
Referenced by loot().
zone_type_CONSTRUCTION_BLUEPRINT
const zone_type_id zone_type_CONSTRUCTION_BLUEPRINT("CONSTRUCTION_BLUEPRINT") ("CONSTRUCTION_BLUEPRINT") static
Referenced by loot().
zone_type_DISASSEMBLE
const zone_type_id zone_type_DISASSEMBLE("DISASSEMBLE") ("DISASSEMBLE") static
Referenced by loot().
zone_type_FARM_PLOT
const zone_type_id zone_type_FARM_PLOT("FARM_PLOT") ("FARM_PLOT") static
Referenced by loot().
zone_type_LOOT_CORPSE
const zone_type_id zone_type_LOOT_CORPSE("LOOT_CORPSE") ("LOOT_CORPSE") static
Referenced by loot().
zone_type_LOOT_UNSORTED
const zone_type_id zone_type_LOOT_UNSORTED("LOOT_UNSORTED") ("LOOT_UNSORTED") static
Referenced by loot().
zone_type_LOOT_WOOD
const zone_type_id zone_type_LOOT_WOOD("LOOT_WOOD") ("LOOT_WOOD") static
Referenced by loot().
zone_type_MINING
const zone_type_id zone_type_MINING("MINING") ("MINING") static
Referenced by loot().
zone_type_MOPPING
const zone_type_id zone_type_MOPPING("MOPPING") ("MOPPING") static
Referenced by loot().
zone_type_STRIP_CORPSES
const zone_type_id zone_type_STRIP_CORPSES("STRIP_CORPSES") ("STRIP_CORPSES") static
Referenced by loot().
zone_type_UNLOAD_ALL
const zone_type_id zone_type_UNLOAD_ALL("UNLOAD_ALL") ("UNLOAD_ALL") static
Referenced by loot().
zone_type_VEHICLE_DECONSTRUCT
const zone_type_id zone_type_VEHICLE_DECONSTRUCT("VEHICLE_DECONSTRUCT") ("VEHICLE_DECONSTRUCT") static
Referenced by loot().
zone_type_VEHICLE_REPAIR
const zone_type_id zone_type_VEHICLE_REPAIR("VEHICLE_REPAIR") ("VEHICLE_REPAIR") static
Referenced by loot().