Cataclysm DDA: src/harvest.cpp File Reference
harvest.cpp File Reference
#include "harvest.h"
#include <algorithm>
#include <cmath>
#include <iterator>
#include <string>
#include "assign.h"
#include "debug.h"
#include "generic_factory.h"
#include "item.h"
#include "item_group.h"
#include "json.h"
#include "output.h"
#include "string_formatter.h"
#include "text_snippets.h"
Namespaces
anonymous_namespace{harvest.cpp}
Variables
static const butchery_requirements_id butchery_requirements_default ("default")
static const itype_id itype_ruined_chunks ("ruined_chunks")
static const skill_id skill_survival ("survival")
generic_factory< harvest_drop_type > anonymous_namespace{harvest.cpp}::harvest_drop_type_factory ("harvest_drop_type")
generic_factory< harvest_list > anonymous_namespace{harvest.cpp}::harvest_list_factory ("harvest_list")
Variable Documentation
butchery_requirements_default
const butchery_requirements_id butchery_requirements_default("default") ("default") static
Referenced by harvest_list::load().
itype_ruined_chunks
const itype_id itype_ruined_chunks("ruined_chunks") ("ruined_chunks") static
Referenced by harvest_list::load().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by harvest_drop_type::load().