Cataclysm DDA: src/help.h File Reference
help.h File Reference
#include <iosfwd>
#include <map>
#include <string>
#include <utility>
#include <vector>
#include "cuboid_rectangle.h"
Classes
class help
Namespaces
catacurses
Contains the curses interface used by the whole game.
Macros
#define CATA_SRC_HELP_H
Functions
help & get_help ()
std::string get_hint ()
Macro Definition Documentation
CATA_SRC_HELP_H
#define CATA_SRC_HELP_H
Definition at line 3 of file help.h.
Function Documentation
get_help()
help& get_help ()
Definition at line 28 of file help.cpp.
 {
     static help single_instance;
     return single_instance;
 }
Referenced by input_context::display_menu(), game::do_regular_action(), handle_key_blocking_activity(), main(), and main_menu::opening_screen().
get_hint()
std::string get_hint ()
Definition at line 269 of file help.cpp.
 {
     return SNIPPET.random_from_category( "hint" ).value_or( translation() ).translated();
 }
References snippet_library::random_from_category(), and SNIPPET.
Referenced by dynamic_line_t::dynamic_line_t(), and avatar::read().