Cataclysm DDA: src/help.cpp File Reference
help.cpp File Reference
#include "help.h"
#include <algorithm>
#include <array>
#include <cstddef>
#include <iterator>
#include <numeric>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>
#include "action.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "color.h"
#include "cursesdef.h"
#include "debug.h"
#include "input_context.h"
#include "output.h"
#include "path_info.h"
#include "point.h"
#include "string_formatter.h"
#include "text_snippets.h"
#include "translations.h"
#include "ui_manager.h"
Functions
help & get_help ()
std::string get_hint ()
Function Documentation
get_help()
help& get_help ()
Definition at line 28 of file help.cpp.
 {
     static help single_instance;
     return single_instance;
 }
Referenced by input_context::display_menu(), game::do_regular_action(), handle_key_blocking_activity(), main(), and main_menu::opening_screen().
get_hint()
std::string get_hint ()
Definition at line 269 of file help.cpp.
 {
     return SNIPPET.random_from_category( "hint" ).value_or( translation() ).translated();
 }
References snippet_library::random_from_category(), and SNIPPET.
Referenced by dynamic_line_t::dynamic_line_t(), and avatar::read().