Cataclysm DDA: src/iexamine.cpp File Reference
iexamine.cpp File Reference
#include "iexamine.h"
#include <algorithm>
#include <climits>
#include <cmath>
#include <cstdio>
#include <iterator>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <utility>
#include "activity_actor_definitions.h"
#include "activity_type.h"
#include "ammo.h"
#include "avatar.h"
#include "basecamp.h"
#include "bionics.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "colony.h"
#include "color.h"
#include "construction.h"
#include "construction_group.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "craft_command.h"
#include "creature.h"
#include "creature_tracker.h"
#include "cursesdef.h"
#include "debug.h"
#include "effect.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "field_type.h"
#include "flag.h"
#include "fungal_effects.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "handle_liquid.h"
#include "harvest.h"
#include "input_context.h"
#include "inventory.h"
#include "item.h"
#include "item_location.h"
#include "item_stack.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "line.h"
#include "magic.h"
#include "magic_teleporter_list.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "map_selector.h"
#include "mapdata.h"
#include "messages.h"
#include "mission_companion.h"
#include "morale_types.h"
#include "mtype.h"
#include "mutation.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "player_activity.h"
#include "point.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "requirements.h"
#include "rng.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "timed_event.h"
#include "translations.h"
#include "trap.h"
#include "try_parse_integer.h"
#include "ui.h"
#include "ui_manager.h"
#include "uistate.h"
#include "units.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "vehicle_selector.h"
#include "visitable.h"
#include "vpart_position.h"
#include "weather.h"
Classes
class anonymous_namespace{iexamine.cpp}::atm_menu
Implements iexamine::atm(...)
struct anonymous_namespace{iexamine.cpp}::elevator_vehicles
Namespaces
anonymous_namespace{iexamine.cpp}
sm_rack
Functions
static bool has_attunement_spell_prereqs (Character &you, const trait_id &attunement)
int anonymous_namespace{iexamine.cpp}::_get_rot_delta (tripoint_abs_omt const &this_omt, tripoint_abs_omt const &that_omt)
tripoint anonymous_namespace{iexamine.cpp}::_rotate_point_sm (tripoint const &p, int erot, tripoint const &orig)
int anonymous_namespace{iexamine.cpp}::_choose_elevator_destz (tripoint const &examp, tripoint_abs_omt const &this_omt, tripoint const &sm_orig)
elevator_vehicles anonymous_namespace{iexamine.cpp}::_get_vehicles_on_elevator (std::vector< tripoint > const &elevator)
static std::pair< itype_id, const deploy_tent_actor * > find_tent_itype (const furn_str_id &id)
static bool dead_plant (bool flower, Character &you, const tripoint &examp)
If it's winter: show msg and return true.
static bool can_drink_nectar (const Character &you)
Helper method to see if player has traits, hunger and mouthwear for drinking nectar.
static bool query_pick (Character &who, const tripoint &target)
static void add_firestarter (item *it, std::multimap< int, item * > &firestarters, Character &you, const tripoint &examp)
static void fvat_set_empty (const tripoint &pos)
static void fvat_set_full (const tripoint &pos)
static void compost_set_empty (const tripoint &pos)
static void compost_set_full (const tripoint &pos)
static units::volume get_keg_capacity (const tripoint &pos)
static void displace_items_except_one_liquid (const tripoint &examp)
static void pick_plant (Character &you, const tripoint &examp, const itype_id &itemType, ter_id new_ter, bool seeds=false)
static item_location maple_tree_sap_container ()
static int count_charges_in_list (const itype *type, const map_stack &items)
Finds the number of charges of the first item that matches type.
static int count_charges_in_list (const ammotype *ammotype, const map_stack &items, itype_id &item_type)
Finds the number of charges of the first item that matches ammotype.
static void reload_furniture (Character &you, const tripoint &examp, bool allow_unload)
static int getNearPumpCount (const tripoint &p, fuel_station_fuel_type &fuel_type)
static int getGasDiscountCardQuality (const item &it)
static int findBestGasDiscount (Character &you)
static std::string str_to_illiterate_str (std::string s)
static std::string getGasDiscountName (int discount)
static int getGasPricePerLiter (int discount)
static int fromPumpFuel (const tripoint &dst, const tripoint &src)
static void turnOnSelectedPump (const tripoint &p, int number, fuel_station_fuel_type &fuel_type)
static Character & player_on_couch (Character &you, const tripoint &autodoc_loc, Character &null_patient, bool &adjacent_couch, tripoint &couch_pos)
static Character & operator_present (Character &you, const tripoint &autodoc_loc, Character &null_patient)
static item & cyborg_on_couch (const tripoint &couch_pos, item &null_cyborg)
static Character & best_installer (Character &you, Character &null_player, int difficulty)
template<typename ... Args>
void popup_player_or_npc (Character &you, const char *player_mes, const char *npc_mes, Args &&... args)
static int get_charcoal_charges (units::volume food)
static bool is_non_rotten_crafting_component (const item &it)
static void mill_activate (Character &you, const tripoint &examp)
static void smoker_activate (Character &you, const tripoint &examp)
static void smoker_finalize (Character &, const tripoint &examp, const time_point &start_time)
static void smoker_load_food (Character &you, const tripoint &examp, const units::volume &remaining_capacity)
static void mill_load_food (Character &you, const tripoint &examp, const units::volume &remaining_capacity)
iexamine_functions iexamine_functions_from_string (const std::string &function_name)
Given then name of one of the above functions, returns the matching function pointer.
Variables
static const activity_id ACT_ATM ("ACT_ATM")
static const activity_id ACT_BUILD ("ACT_BUILD")
static const activity_id ACT_HARVEST ("ACT_HARVEST")
static const activity_id ACT_OPERATION ("ACT_OPERATION")
static const activity_id ACT_PLANT_SEED ("ACT_PLANT_SEED")
static const ammotype ammo_money ("money")
static const bionic_id bio_lighter ("bio_lighter")
static const bionic_id bio_lockpick ("bio_lockpick")
static const bionic_id bio_painkiller ("bio_painkiller")
static const character_modifier_id character_modifier_obstacle_climb_mod ("obstacle_climb_mod")
static const climbing_aid_id climbing_aid_furn_CLIMBABLE ("furn_CLIMBABLE")
static const efftype_id effect_antibiotic ("antibiotic")
static const efftype_id effect_bite ("bite")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_bouldering ("bouldering")
static const efftype_id effect_disinfected ("disinfected")
static const efftype_id effect_earphones ("earphones")
static const efftype_id effect_gliding ("gliding")
static const efftype_id effect_incorporeal ("incorporeal")
static const efftype_id effect_infected ("infected")
static const efftype_id effect_mending ("mending")
static const efftype_id effect_pblue ("pblue")
static const efftype_id effect_pkill2 ("pkill2")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_slow_descent ("slow_descent")
static const efftype_id effect_strong_antibiotic ("strong_antibiotic")
static const efftype_id effect_strong_antibiotic_visible ("strong_antibiotic_visible")
static const efftype_id effect_teleglow ("teleglow")
static const efftype_id effect_tetanus ("tetanus")
static const efftype_id effect_weak_antibiotic ("weak_antibiotic")
static const furn_str_id furn_f_arcfurnace_empty ("f_arcfurnace_empty")
static const furn_str_id furn_f_arcfurnace_full ("f_arcfurnace_full")
static const furn_str_id furn_f_compost_empty ("f_compost_empty")
static const furn_str_id furn_f_compost_full ("f_compost_full")
static const furn_str_id furn_f_diesel_tank ("f_diesel_tank")
static const furn_str_id furn_f_flower_fungal ("f_flower_fungal")
static const furn_str_id furn_f_flower_marloss ("f_flower_marloss")
static const furn_str_id furn_f_fvat_empty ("f_fvat_empty")
static const furn_str_id furn_f_fvat_full ("f_fvat_full")
static const furn_str_id furn_f_fvat_wood_empty ("f_fvat_wood_empty")
static const furn_str_id furn_f_fvat_wood_full ("f_fvat_wood_full")
static const furn_str_id furn_f_gas_tank ("f_gas_tank")
static const furn_str_id furn_f_kiln_empty ("f_kiln_empty")
static const furn_str_id furn_f_kiln_full ("f_kiln_full")
static const furn_str_id furn_f_kiln_metal_empty ("f_kiln_metal_empty")
static const furn_str_id furn_f_kiln_metal_full ("f_kiln_metal_full")
static const furn_str_id furn_f_metal_smoking_rack ("f_metal_smoking_rack")
static const furn_str_id furn_f_metal_smoking_rack_active ("f_metal_smoking_rack_active")
static const furn_str_id furn_f_safe_o ("f_safe_o")
static const furn_str_id furn_f_smoking_rack ("f_smoking_rack")
static const furn_str_id furn_f_smoking_rack_active ("f_smoking_rack_active")
static const furn_str_id furn_f_stook_empty ("f_stook_empty")
static const furn_str_id furn_f_stook_full ("f_stook_full")
static const furn_str_id furn_f_water_mill ("f_water_mill")
static const furn_str_id furn_f_water_mill_active ("f_water_mill_active")
static const furn_str_id furn_f_wind_mill ("f_wind_mill")
static const furn_str_id furn_f_wind_mill_active ("f_wind_mill_active")
static const itype_id itype_2x4 ("2x4")
static const itype_id itype_arm_splint ("arm_splint")
static const itype_id itype_bot_broken_cyborg ("bot_broken_cyborg")
static const itype_id itype_bot_prototype_cyborg ("bot_prototype_cyborg")
static const itype_id itype_cash_card ("cash_card")
static const itype_id itype_charcoal ("charcoal")
static const itype_id itype_chem_carbide ("chem_carbide")
static const itype_id itype_corpse ("corpse")
static const itype_id itype_disassembly ("disassembly")
static const itype_id itype_fake_milling_item ("fake_milling_item")
static const itype_id itype_fake_smoke_plume ("fake_smoke_plume")
static const itype_id itype_fertilizer ("fertilizer")
static const itype_id itype_fire ("fire")
static const itype_id itype_foodperson_mask ("foodperson_mask")
static const itype_id itype_foodperson_mask_on ("foodperson_mask_on")
static const itype_id itype_fungal_seeds ("fungal_seeds")
static const itype_id itype_hickory_root ("hickory_root")
static const itype_id itype_id_science ("id_science")
static const itype_id itype_leg_splint ("leg_splint")
static const itype_id itype_maple_sap ("maple_sap")
static const itype_id itype_marloss_berry ("marloss_berry")
static const itype_id itype_marloss_seed ("marloss_seed")
static const itype_id itype_mycus_fruit ("mycus_fruit")
static const itype_id itype_nail ("nail")
static const itype_id itype_nanomaterial ("nanomaterial")
static const itype_id itype_petrified_eye ("petrified_eye")
static const itype_id itype_sheet ("sheet")
static const itype_id itype_stick ("stick")
static const itype_id itype_string_36 ("string_36")
static const itype_id itype_unfinished_cac2 ("unfinished_cac2")
static const itype_id itype_unfinished_charcoal ("unfinished_charcoal")
static const json_character_flag json_flag_ATTUNEMENT ("ATTUNEMENT")
static const json_character_flag json_flag_GLIDE ("GLIDE")
static const json_character_flag json_flag_LEVITATION ("LEVITATION")
static const json_character_flag json_flag_PAIN_IMMUNE ("PAIN_IMMUNE")
static const json_character_flag json_flag_SAFECRACK_NO_TOOL ("SAFECRACK_NO_TOOL")
static const json_character_flag json_flag_WING_ARM ("WING_ARM")
static const json_character_flag json_flag_WING_GLIDE ("WING_GLIDE")
static const material_id material_bone ("bone")
static const material_id material_cac2powder ("cac2powder")
static const material_id material_ch_steel ("ch_steel")
static const material_id material_hc_steel ("hc_steel")
static const material_id material_lc_steel ("lc_steel")
static const material_id material_mc_steel ("mc_steel")
static const material_id material_qt_steel ("qt_steel")
static const material_id material_steel ("steel")
static const material_id material_wood ("wood")
static const mtype_id mon_broken_cyborg ("mon_broken_cyborg")
static const mtype_id mon_dark_wyrm ("mon_dark_wyrm")
static const mtype_id mon_fungal_blossom ("mon_fungal_blossom")
static const mtype_id mon_prototype_cyborg ("mon_prototype_cyborg")
static const npc_class_id NC_ROBOFAC_INTERCOM ("NC_ROBOFAC_INTERCOM")
static const proficiency_id proficiency_prof_disarming ("prof_disarming")
static const proficiency_id proficiency_prof_parkour ("prof_parkour")
static const proficiency_id proficiency_prof_traps ("prof_traps")
static const proficiency_id proficiency_prof_trapsetting ("prof_trapsetting")
static const quality_id qual_ANESTHESIA ("ANESTHESIA")
static const quality_id qual_DIG ("DIG")
static const quality_id qual_DRILL ("DRILL")
static const quality_id qual_GRASS_CUT ("GRASS_CUT")
static const quality_id qual_HACK ("HACK")
static const quality_id qual_HAMMER ("HAMMER")
static const quality_id qual_LOCKPICK ("LOCKPICK")
static const quality_id qual_PRY ("PRY")
static const quality_id qual_TREE_TAP ("TREE_TAP")
static const requirement_id requirement_data_anesthetic ("anesthetic")
static const requirement_id requirement_data_autoclave ("autoclave")
static const requirement_id requirement_data_cvd_diamond ("cvd_diamond")
static const skill_id skill_chemistry ("chemistry")
static const skill_id skill_cooking ("cooking")
static const skill_id skill_fabrication ("fabrication")
static const skill_id skill_survival ("survival")
static const skill_id skill_traps ("traps")
static const ter_str_id ter_t_card_reader_broken ("t_card_reader_broken")
static const ter_str_id ter_t_diesel_pump ("t_diesel_pump")
static const ter_str_id ter_t_diesel_pump_a ("t_diesel_pump_a")
static const ter_str_id ter_t_dirt ("t_dirt")
static const ter_str_id ter_t_door_metal_c ("t_door_metal_c")
static const ter_str_id ter_t_door_metal_locked ("t_door_metal_locked")
static const ter_str_id ter_t_door_metal_o ("t_door_metal_o")
static const ter_str_id ter_t_floor_blue ("t_floor_blue")
static const ter_str_id ter_t_floor_green ("t_floor_green")
static const ter_str_id ter_t_floor_red ("t_floor_red")
static const ter_str_id ter_t_fungus ("t_fungus")
static const ter_str_id ter_t_gas_pump ("t_gas_pump")
static const ter_str_id ter_t_gas_pump_a ("t_gas_pump_a")
static const ter_str_id ter_t_marloss ("t_marloss")
static const ter_str_id ter_t_marloss_tree ("t_marloss_tree")
static const ter_str_id ter_t_orifice ("t_orifice")
static const ter_str_id ter_t_pit ("t_pit")
static const ter_str_id ter_t_pit_covered ("t_pit_covered")
static const ter_str_id ter_t_pit_glass ("t_pit_glass")
static const ter_str_id ter_t_pit_glass_covered ("t_pit_glass_covered")
static const ter_str_id ter_t_pit_spiked ("t_pit_spiked")
static const ter_str_id ter_t_pit_spiked_covered ("t_pit_spiked_covered")
static const ter_str_id ter_t_rock_blue ("t_rock_blue")
static const ter_str_id ter_t_rock_floor ("t_rock_floor")
static const ter_str_id ter_t_rock_green ("t_rock_green")
static const ter_str_id ter_t_rock_red ("t_rock_red")
static const ter_str_id ter_t_shrub_fungal ("t_shrub_fungal")
static const ter_str_id ter_t_switch_even ("t_switch_even")
static const ter_str_id ter_t_switch_gb ("t_switch_gb")
static const ter_str_id ter_t_switch_rb ("t_switch_rb")
static const ter_str_id ter_t_switch_rg ("t_switch_rg")
static const ter_str_id ter_t_tree_fungal ("t_tree_fungal")
static const ter_str_id ter_t_tree_hickory_dead ("t_tree_hickory_dead")
static const ter_str_id ter_t_tree_maple ("t_tree_maple")
static const ter_str_id ter_t_tree_maple_tapped ("t_tree_maple_tapped")
static const trait_id trait_AMORPHOUS ("AMORPHOUS")
static const trait_id trait_ARACHNID_ARMS_OK ("ARACHNID_ARMS_OK")
static const trait_id trait_BADKNEES ("BADKNEES")
static const trait_id trait_BEAK_HUM ("BEAK_HUM")
static const trait_id trait_BURROW ("BURROW")
static const trait_id trait_BURROWLARGE ("BURROWLARGE")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
static const trait_id trait_ILLITERATE ("ILLITERATE")
static const trait_id trait_INSECT_ARMS_OK ("INSECT_ARMS_OK")
static const trait_id trait_M_DEFENDER ("M_DEFENDER")
static const trait_id trait_M_DEPENDENT ("M_DEPENDENT")
static const trait_id trait_M_FERTILE ("M_FERTILE")
static const trait_id trait_M_SPORES ("M_SPORES")
static const trait_id trait_PROBOSCIS ("PROBOSCIS")
static const trait_id trait_PYROMANIA ("PYROMANIA")
static const trait_id trait_SHELL2 ("SHELL2")
static const trait_id trait_SHELL3 ("SHELL3")
static const trait_id trait_THRESH_MARLOSS ("THRESH_MARLOSS")
static const trait_id trait_THRESH_MYCUS ("THRESH_MYCUS")
static const time_duration milling_time = 6_hours
constexpr int anonymous_namespace{iexamine.cpp}::uilist_positive = 10000
static const int sm_rack::MIN_CHARCOAL = 1200
static const int sm_rack::CHARCOAL_PER_LITER = 600
static const units::volume sm_rack::MAX_FOOD_VOLUME = units::from_liter(20)
static const units::volume sm_rack::MAX_FOOD_VOLUME_PORTABLE = units::from_liter(15)
Function Documentation
add_firestarter()
static void add_firestarter (item * it, std::multimap< int, item * > & firestarters, Character & you, const tripoint & examp) static
Definition at line 3375 of file iexamine.cpp.
 {
     const use_function *usef = it->type->get_use( "firestarter" );
     if( usef != nullptr && usef->get_actor_ptr() != nullptr ) {
         const firestarter_actor *actor = dynamic_cast<const firestarter_actor *>( usef->get_actor_ptr() );
         if( actor->can_use( you, *it, examp ).success() ) {
             firestarters.insert( std::pair<int, item *>( actor->moves_cost_fast, it ) );
         }
     }
 }
References firestarter_actor::can_use(), use_function::get_actor_ptr(), itype::get_use(), firestarter_actor::moves_cost_fast, ret_val_common::success(), and item::type.
Referenced by iexamine::fireplace().
best_installer()
static Character& best_installer (Character & you, Character & null_player, int difficulty) static
Definition at line 5628 of file iexamine.cpp.
 {
     std::vector< std::pair<int, int>> ally_chances;
     ally_chances.reserve( g->allies().size() );
     for( size_t i = 0; i < g->allies().size() ; i ++ ) {
         std::pair<int, int> ally_skill;
         const npc *e = g->allies()[ i ];
         Character &ally = *g->critter_by_id<Character>( e->getID() );
         ally_skill.second = i;
         ally_skill.first = bionic_success_chance( true, -1, difficulty, ally );
         ally_chances.push_back( ally_skill );
     }
     std::sort( ally_chances.begin(), ally_chances.end(), [&]( const std::pair<int, int> &lhs,
     const std::pair<int, int> &rhs ) {
         return rhs.first < lhs.first;
     } );
     int player_cos = bionic_success_chance( true, -1, difficulty, you );
     avatar &player_character = get_avatar();
     for( size_t i = 0; i < g->allies().size() ; i ++ ) {
         if( ally_chances[ i ].first > player_cos ) {
             const npc *e = g->allies()[ ally_chances[ i ].second ];
             Character &ally = *g->critter_by_id<Character>( e->getID() );
             if( e->has_effect( effect_sleep ) ) {
                 if( !player_character.query_yn(
                         //~ %1$s is the name of the ally
                         _( "<color_white>%1$s is asleep, but has a <color_green>%2$d<color_white> chance of success compared to your <color_red>%3$d<color_white> chance of success.  Continue with a higher risk of failure?</color>" ),
                         ally.disp_name(), ally_chances[i].first, player_cos ) ) {
                     return null_player;
                 } else {
                     continue;
                 }
             }
             //~ %1$s is the name of the ally
             add_msg( _( "%1$s will perform the operation with a %2$d chance of success." ), ally.disp_name(),
                      ally_chances[i].first );
             return ally;
         } else {
             break;
         }
     }
     return you;
 }
References _, add_msg(), ally, bionic_success_chance(), effect_sleep, g, get_avatar(), Character::getID(), Creature::has_effect(), avatar::query_yn(), and om_direction::size.
Referenced by iexamine::autodoc().
can_drink_nectar()
static bool can_drink_nectar (const Character & you) static
Helper method to see if player has traits, hunger and mouthwear for drinking nectar.
Definition at line 2182 of file iexamine.cpp.
 {
     return ( you.has_active_mutation( trait_PROBOSCIS )  ||
              you.has_active_mutation( trait_BEAK_HUM ) ) &&
            ( you.get_hunger() > 0 ) && ( !you.wearing_something_on( bodypart_id( "mouth" ) ) );
 }
References Character::get_hunger(), Character::has_active_mutation(), trait_BEAK_HUM, trait_PROBOSCIS, and Character::wearing_something_on().
Referenced by iexamine_helper::drink_nectar(), iexamine::flower_marloss(), and iexamine::flower_poppy().
compost_set_empty()
static void compost_set_empty (const tripoint & pos) static
Definition at line 3738 of file iexamine.cpp.
 {
     map &here = get_map();
     furn_id furn = here.furn( pos );
     if( furn == furn_f_compost_empty || furn == furn_f_compost_full ) {
         here.furn_set( pos, furn_f_compost_empty );
     }
 }
References map::furn(), furn_f_compost_empty, furn_f_compost_full, map::furn_set(), get_map(), and math_opers::pos().
Referenced by iexamine::compost_full().
compost_set_full()
static void compost_set_full (const tripoint & pos) static
Definition at line 3747 of file iexamine.cpp.
 {
     map &here = get_map();
     furn_id furn = here.furn( pos );
     if( furn == furn_f_compost_empty || furn == furn_f_compost_full ) {
         here.furn_set( pos, furn_f_compost_full );
     }
 }
References map::furn(), furn_f_compost_empty, furn_f_compost_full, map::furn_set(), get_map(), and math_opers::pos().
Referenced by iexamine::compost_empty().
count_charges_in_list() [1/2]
static int count_charges_in_list (const ammotype * ammotype, const map_stack & items, itype_id & item_type) static
Finds the number of charges of the first item that matches ammotype.
Parameters
ammotype Search target.
items Stack of items. Search stops at first match.
[out] item_type Matching type.
Returns
Number of charges.
Definition at line 4726 of file iexamine.cpp.
 {
     for( const item &candidate : items ) {
         if( candidate.is_ammo() && candidate.type->ammo->type == *ammotype ) {
             item_type = candidate.typeId();
             return candidate.charges;
         }
     }
     return 0;
 }
count_charges_in_list() [2/2]
static int count_charges_in_list (const itype * type, const map_stack & items) static
Finds the number of charges of the first item that matches type.
Parameters
type Search target.
items Stack of items. Search stops at first match.
Returns
Number of charges.
Definition at line 4707 of file iexamine.cpp.
 {
     for( const item &candidate : items ) {
         if( candidate.type == type ) {
             return candidate.charges;
         }
     }
     return 0;
 }
Referenced by reload_furniture(), smoker_activate(), and iexamine::smoker_options().
cyborg_on_couch()
static item& cyborg_on_couch (const tripoint & couch_pos, item & null_cyborg) static
Definition at line 5613 of file iexamine.cpp.
 {
     for( item &it : get_map().i_at( couch_pos ) ) {
         if( it.typeId() == itype_bot_broken_cyborg || it.typeId() == itype_bot_prototype_cyborg ) {
             return it;
         }
         if( it.typeId() == itype_corpse ) {
             if( it.get_mtype()->id == mon_broken_cyborg || it.get_mtype()->id == mon_prototype_cyborg ) {
                 return it;
             }
         }
     }
     return null_cyborg;
 }
References get_map(), mtype::id, itype_bot_broken_cyborg, itype_bot_prototype_cyborg, itype_corpse, mon_broken_cyborg, and mon_prototype_cyborg.
Referenced by iexamine::autodoc().
dead_plant()
static bool dead_plant (bool flower, Character & you, const tripoint & examp) static
If it's winter: show msg and return true.
Otherwise return false
Definition at line 2163 of file iexamine.cpp.
 {
     if( season_of_year( calendar::turn ) == WINTER ) {
         if( flower ) {
             add_msg( m_info, _( "This flower is dead.  You can't get it." ) );
         } else {
             add_msg( m_info, _( "This plant is dead.  You can't get it." ) );
         }
         iexamine::none( you, examp );
         return true;
     }
     return false;
 }
References _, add_msg(), m_info, iexamine::none(), season_of_year(), calendar::turn, and WINTER.
Referenced by iexamine::flower_cactus(), iexamine::flower_dahlia(), and iexamine::flower_poppy().
displace_items_except_one_liquid()
static void displace_items_except_one_liquid (const tripoint & examp) static
Definition at line 4032 of file iexamine.cpp.
 {
     map &here = get_map();
     // Temporarily replace the real furniture with a fake furniture with NOITEM
     const furn_id previous_furn = here.furn( examp );
     here.furn_set( examp, furn_id( "f_no_item" ) );
     bool liquid_present = false;
     map_stack items = here.i_at( examp );
     for( map_stack::iterator it = items.begin(); it != items.end(); ) {
         if( !it->made_of_from_type( phase_id::LIQUID ) || liquid_present ) {
             // This isn't a liquid or there was already another kind of liquid inside,
             // so this has to be moved.
             // This will add items to a space near the vat, because it's flagged as NOITEM.
             items.insert( *it );
             it = items.erase( it );
         } else {
             it++;
             liquid_present = true;
         }
     }
     // Replace the real furniture
     here.furn_set( examp, previous_furn );
 }
References item_stack::begin(), item_stack::end(), map_stack::erase(), map::furn(), map::furn_set(), get_map(), map::i_at(), map_stack::insert(), and LIQUID.
Referenced by iexamine::keg().
find_tent_itype()
static std::pair<itype_id, const deploy_tent_actor *> find_tent_itype (const furn_str_id & id) static
Definition at line 1651 of file iexamine.cpp.
 {
     const itype_id &iid = id->deployed_item;
     if( item::type_is_defined( iid ) ) {
         const itype &type = *item::find_type( iid );
         for( const auto &pair : type.use_methods ) {
             const deploy_tent_actor *actor = dynamic_cast<const deploy_tent_actor *>
                                              ( pair.second.get_actor_ptr() );
             if( !actor ) {
                 continue;
             }
             if( ( actor->floor_center && *actor->floor_center == id ) || ( !actor->floor_center &&
                     actor->floor == id ) ) {
                 return std::make_pair( iid, actor );
             }
         }
     }
     return std::make_pair( iid, nullptr );
 }
References item::find_type(), deploy_tent_actor::floor, deploy_tent_actor::floor_center, int_id< T >::id(), and item::type_is_defined().
Referenced by iexamine::portable_structure().
findBestGasDiscount()
static int findBestGasDiscount (Character & you) static
Definition at line 5037 of file iexamine.cpp.
 {
     int discount = 0;
     you.cache_visit_items_with( flag_GAS_DISCOUNT, [&discount]( const item & it ) {
         discount = std::max( discount, getGasDiscountCardQuality( it ) );
     } );
     return discount;
 }
References Character::cache_visit_items_with(), flag_GAS_DISCOUNT, getGasDiscountCardQuality(), and max().
Referenced by iexamine::pay_gas().
fromPumpFuel()
static int fromPumpFuel (const tripoint & dst, const tripoint & src) static
Definition at line 5132 of file iexamine.cpp.
 {
     map &here = get_map();
     map_stack items = here.i_at( src );
     for( auto item_it = items.begin(); item_it != items.end(); ++item_it ) {
         if( item_it->made_of( phase_id::LIQUID ) ) {
             // how much do we have in the pump?
             const int amount = item_it->charges;
             item liq_d( item_it->type, calendar::turn, amount );
             // add the charges to the destination
             const ter_id backup_ter = here.ter( dst );
             const furn_id backup_furn = here.furn( dst );
             here.ter_set( dst, ter_str_id::NULL_ID() );
             here.furn_set( dst, furn_str_id::NULL_ID() );
             here.add_item_or_charges( dst, liq_d );
             here.ter_set( dst, backup_ter );
             here.furn_set( dst, backup_furn );
             // remove the liquid from the pump
             items.erase( item_it );
             return amount;
         }
     }
     return -1;
 }
References map::add_item_or_charges(), item_stack::begin(), item_stack::end(), map_stack::erase(), map::furn(), map::furn_set(), get_map(), map::i_at(), LIQUID, string_id< furn_t >::NULL_ID(), string_id< ter_t >::NULL_ID(), map::ter(), map::ter_set(), and calendar::turn.
Referenced by iexamine::pay_gas().
fvat_set_empty()
static void fvat_set_empty (const tripoint & pos) static
Definition at line 3507 of file iexamine.cpp.
 {
     map &here = get_map();
     furn_id furn = here.furn( pos );
     if( furn == furn_f_fvat_wood_empty || furn == furn_f_fvat_wood_full ) {
         here.furn_set( pos, furn_f_fvat_wood_empty );
     } else {
         here.furn_set( pos, furn_f_fvat_empty );
     }
 }
References map::furn(), furn_f_fvat_empty, furn_f_fvat_wood_empty, furn_f_fvat_wood_full, map::furn_set(), get_map(), and math_opers::pos().
Referenced by iexamine::fvat_full().
fvat_set_full()
static void fvat_set_full (const tripoint & pos) static
Definition at line 3518 of file iexamine.cpp.
 {
     map &here = get_map();
     furn_id furn = here.furn( pos );
     if( furn == furn_f_fvat_wood_empty || furn == furn_f_fvat_wood_full ) {
         here.furn_set( pos, furn_f_fvat_wood_full );
     } else {
         here.furn_set( pos, furn_f_fvat_full );
     }
 }
References map::furn(), furn_f_fvat_full, furn_f_fvat_wood_empty, furn_f_fvat_wood_full, map::furn_set(), get_map(), and math_opers::pos().
Referenced by iexamine::fvat_empty().
get_charcoal_charges()
static int get_charcoal_charges (units::volume food) static
Definition at line 6086 of file iexamine.cpp.
 {
     const int charcoal = to_liter( food ) * sm_rack::CHARCOAL_PER_LITER;
     return  std::max( charcoal, sm_rack::MIN_CHARCOAL );
 }
References sm_rack::CHARCOAL_PER_LITER, max(), sm_rack::MIN_CHARCOAL, and units::to_liter().
Referenced by smoker_activate(), and iexamine::smoker_options().
get_keg_capacity()
static units::volume get_keg_capacity (const tripoint & pos) static
Definition at line 4018 of file iexamine.cpp.
 {
     const furn_t &furn = get_map().furn( pos ).obj();
     return furn.keg_capacity;
 }
References map::furn(), get_map(), furn_t::keg_capacity, int_id< T >::obj(), and math_opers::pos().
Referenced by iexamine::has_keg(), iexamine::keg(), and iexamine::pour_into_keg().
getGasDiscountCardQuality()
static int getGasDiscountCardQuality (const item & it) static
Definition at line 5021 of file iexamine.cpp.
 {
     for( const flag_id &tag : it.type->get_flags() ) {
         if( string_starts_with( tag->id.str(), "DISCOUNT_VALUE_" ) ) {
             ret_val<int> discount_value =
                 try_parse_integer<int>( tag->id.str().substr( 15 ), false );
             if( discount_value.success() ) {
                 return discount_value.value();
             } else {
                 debugmsg( "Error parsing ammo DISCOUNT_VALUE_ suffix: %s", discount_value.str() );
             }
         }
     }
     return 0;
 }
References debugmsg, itype::get_flags(), ret_val_common::str(), string_starts_with(), ret_val_common::success(), try_parse_integer< int >(), item::type, and ret_val< T >::value().
Referenced by findBestGasDiscount().
getGasDiscountName()
static std::string getGasDiscountName (int discount) static
Definition at line 5067 of file iexamine.cpp.
 {
     if( discount == 3 ) {
         return str_to_illiterate_str( _( "Platinum member" ) );
     } else if( discount == 2 ) {
         return str_to_illiterate_str( _( "Gold member" ) );
     } else if( discount == 1 ) {
         return str_to_illiterate_str( _( "Silver member" ) );
     } else {
         return str_to_illiterate_str( _( "Beloved customer" ) );
     }
 }
References _, and str_to_illiterate_str().
Referenced by iexamine::pay_gas().
getGasPricePerLiter()
static int getGasPricePerLiter (int discount) static
Definition at line 5080 of file iexamine.cpp.
 {
     // Those prices are in cents
     static constexpr std::array<int, 4> prices = { 1400, 1320, 1200, 1000 };
     if( discount < 0 || discount > 3 ) {
         return prices[0];
     } else {
         return prices[discount];
     }
 }
Referenced by iexamine::pay_gas().
getNearPumpCount()
static int getNearPumpCount (const tripoint & p, fuel_station_fuel_type & fuel_type) static
Definition at line 4966 of file iexamine.cpp.
 {
     int result = 0;
     map &here = get_map();
     for( const tripoint &tmp : here.points_in_radius( p, 12 ) ) {
         const ter_id t = here.ter( tmp );
         if( t == ter_t_gas_pump || t == ter_t_gas_pump_a ) {
             result++;
             fuel_type = FUEL_TYPE_GASOLINE;
         } else if( t == ter_t_diesel_pump || t == ter_t_diesel_pump_a ) {
             result++;
             fuel_type = FUEL_TYPE_DIESEL;
         }
     }
     return result;
 }
References FUEL_TYPE_DIESEL, FUEL_TYPE_GASOLINE, get_map(), map::points_in_radius(), map::ter(), ter_t_diesel_pump, ter_t_diesel_pump_a, ter_t_gas_pump, and ter_t_gas_pump_a.
Referenced by iexamine::pay_gas().
has_attunement_spell_prereqs()
static bool has_attunement_spell_prereqs (Character & you, const trait_id & attunement) static
Definition at line 559 of file iexamine.cpp.
 {
     // for each prereq we need to check that the player has 2 level 15 spells
     for( const trait_id &prereq : attunement->prereqs ) {
         int spells_known = 0;
         for( const spell &sp : you.spells_known_of_class( prereq ) ) {
             if( sp.get_level() >= 15 ) {
                 spells_known++;
             }
         }
         if( spells_known < 2 ) {
             return false;
         }
     }
     return true;
 }
References mutation_branch::prereqs, and Character::spells_known_of_class().
Referenced by iexamine::attunement_altar().
iexamine_functions_from_string()
iexamine_functions iexamine_functions_from_string (const std::string & function_name)
Given then name of one of the above functions, returns the matching function pointer.
If no match is found, defaults to iexamine::none but prints out a debug message as a warning.
Parameters
function_name The name of the function to get.
Returns
A function pointer to the specified function.
Definition at line 7334 of file iexamine.cpp.
 {
     static const std::map<std::string, iexamine_examine_function> function_map = {{
             { "none", &iexamine::none },
             { "attunement_altar", &iexamine::attunement_altar },
             { "deployed_furniture", &iexamine::deployed_furniture },
             { "cvdmachine", &iexamine::cvdmachine },
             { "change_appearance", &iexamine::change_appearance },
             { "nanofab", &iexamine::nanofab },
             { "gaspump", &iexamine::gaspump },
             { "atm", &iexamine::atm },
             { "vending", &iexamine::vending },
             { "elevator", &iexamine::elevator },
             { "controls_gate", &iexamine::controls_gate },
             { "cardreader_robofac", &iexamine::cardreader_robofac },
             { "cardreader_fp", &iexamine::cardreader_foodplace },
             { "intercom", &iexamine::intercom },
             { "rubble", &iexamine::rubble },
             { "chainfence", &iexamine::chainfence },
             { "bars", &iexamine::bars },
             { "portable_structure", &iexamine::portable_structure },
             { "pit", &iexamine::pit },
             { "pit_covered", &iexamine::pit_covered },
             { "safe", &iexamine::safe },
             { "bulletin_board", &iexamine::bulletin_board },
             { "pedestal_wyrm", &iexamine::pedestal_wyrm },
             { "pedestal_temple", &iexamine::pedestal_temple },
             { "door_peephole", &iexamine::door_peephole },
             { "fswitch", &iexamine::fswitch },
             { "flower_poppy", &iexamine::flower_poppy },
             { "flower_cactus", &iexamine::flower_cactus },
             { "fungus", &iexamine::fungus },
             { "flower_dahlia", &iexamine::flower_dahlia },
             { "flower_marloss", &iexamine::flower_marloss },
             { "dirtmound", &iexamine::dirtmound },
             { "aggie_plant", &iexamine::aggie_plant },
             { "fvat_empty", &iexamine::fvat_empty },
             { "fvat_full", &iexamine::fvat_full },
             { "compost_empty", &iexamine::compost_empty },
             { "compost_full", &iexamine::compost_full },
             { "keg", &iexamine::keg },
             { "harvest_furn_nectar", &iexamine::harvest_furn_nectar },
             { "harvest_furn", &iexamine::harvest_furn },
             { "harvest_ter_nectar", &iexamine::harvest_ter_nectar },
             { "harvest_ter", &iexamine::harvest_ter },
             { "clear_overgrown", &iexamine::clear_overgrown },
             { "harvest_plant_ex", &iexamine::harvest_plant_ex },
             { "harvested_plant", &iexamine::harvested_plant },
             { "shrub_marloss", &iexamine::shrub_marloss },
             { "translocator", &iexamine::translocator },
             { "tree_marloss", &iexamine::tree_marloss },
             { "tree_hickory", &iexamine::tree_hickory },
             { "tree_maple", &iexamine::tree_maple },
             { "tree_maple_tapped", &iexamine::tree_maple_tapped },
             { "shrub_wildveggies", &iexamine::shrub_wildveggies },
             { "water_source", &iexamine::water_source },
             { "finite_water_source", &iexamine::finite_water_source },
             { "reload_furniture", &iexamine::reload_furniture },
             { "curtains", &iexamine::curtains },
             { "sign", &iexamine::sign },
             { "pay_gas", &iexamine::pay_gas },
             { "gunsafe_el", &iexamine::gunsafe_el },
             { "locked_object", &iexamine::locked_object },
             { "locked_object_pickable", &iexamine::locked_object_pickable },
             { "kiln_empty", &iexamine::kiln_empty },
             { "kiln_full", &iexamine::kiln_full },
             { "stook_empty", &iexamine::stook_empty },
             { "stook_full", &iexamine::stook_full },
             { "arcfurnace_empty", &iexamine::arcfurnace_empty },
             { "arcfurnace_full", &iexamine::arcfurnace_full },
             { "autoclave_empty", &iexamine::autoclave_empty },
             { "autoclave_full", &iexamine::autoclave_full },
             { "fireplace", &iexamine::fireplace },
             { "ledge", &iexamine::ledge },
             { "autodoc", &iexamine::autodoc },
             { "quern_examine", &iexamine::quern_examine },
             { "smoker_options", &iexamine::smoker_options },
             { "open_safe", &iexamine::open_safe },
             { "workbench", &iexamine::workbench },
             { "workout", &iexamine::workout },
             { "invalid", &iexamine::invalid },
         }
     };
     static const std::set<std::string> harvestable_functions = {
         "harvest_furn_nectar",
         "harvest_furn",
         "harvest_ter_nectar",
         "harvest_ter",
         "harvest_plant",
     };
     auto iter = function_map.find( function_name );
     if( iter != function_map.end() ) {
         iexamine_examine_function func = iter->second;
         if( function_name == "none" ) {
             return iexamine_functions{&iexamine::always_false, func};
         } else if( function_name == "invalid" ) {
             return iexamine_functions{&iexamine::false_and_debugmsg, func};
         } else if( harvestable_functions.find( function_name ) != harvestable_functions.end() ) {
             return iexamine_functions{&iexamine::harvestable_now, func};
         } else {
             return iexamine_functions{&iexamine::always_true, func};
         }
     }
     //No match found
     debugmsg( "Could not find an iexamine function matching '%s'!", function_name );
     return iexamine_functions{&iexamine::always_false, &iexamine::none};
 }
References iexamine::aggie_plant(), iexamine::always_false(), iexamine::always_true(), iexamine::arcfurnace_empty(), iexamine::arcfurnace_full(), iexamine::atm(), iexamine::attunement_altar(), iexamine::autoclave_empty(), iexamine::autoclave_full(), iexamine::autodoc(), iexamine::bars(), iexamine::bulletin_board(), iexamine::cardreader_foodplace(), iexamine::cardreader_robofac(), iexamine::chainfence(), iexamine::change_appearance(), iexamine::clear_overgrown(), iexamine::compost_empty(), iexamine::compost_full(), iexamine::controls_gate(), iexamine::curtains(), iexamine::cvdmachine(), debugmsg, iexamine::deployed_furniture(), iexamine::dirtmound(), iexamine::door_peephole(), iexamine::elevator(), iexamine::false_and_debugmsg(), iexamine::finite_water_source(), iexamine::fireplace(), iexamine::flower_cactus(), iexamine::flower_dahlia(), iexamine::flower_marloss(), iexamine::flower_poppy(), iexamine::fswitch(), iexamine::fungus(), iexamine::fvat_empty(), iexamine::fvat_full(), iexamine::gaspump(), iexamine::gunsafe_el(), iexamine::harvest_furn(), iexamine::harvest_furn_nectar(), iexamine::harvest_plant_ex(), iexamine::harvest_ter(), iexamine::harvest_ter_nectar(), iexamine::harvestable_now(), iexamine::harvested_plant(), iexamine::intercom(), iexamine::invalid(), iexamine::keg(), iexamine::kiln_empty(), iexamine::kiln_full(), iexamine::ledge(), iexamine::locked_object(), iexamine::locked_object_pickable(), iexamine::nanofab(), iexamine::none(), iexamine::open_safe(), iexamine::pay_gas(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), iexamine::pit(), iexamine::pit_covered(), iexamine::portable_structure(), iexamine::quern_examine(), iexamine::reload_furniture(), iexamine::rubble(), iexamine::safe(), iexamine::shrub_marloss(), iexamine::shrub_wildveggies(), iexamine::sign(), iexamine::smoker_options(), iexamine::stook_empty(), iexamine::stook_full(), iexamine::translocator(), iexamine::tree_hickory(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), iexamine::tree_marloss(), iexamine::vending(), iexamine::water_source(), iexamine::workbench(), and iexamine::workout().
Referenced by map_data_common_t::load().
is_non_rotten_crafting_component()
static bool is_non_rotten_crafting_component (const item & it) static
Definition at line 6093 of file iexamine.cpp.
 {
     return is_crafting_component( it ) && !it.rotten();
 }
References is_crafting_component(), and item::rotten().
maple_tree_sap_container()
static item_location maple_tree_sap_container () static
Definition at line 4317 of file iexamine.cpp.
 {
     const item maple_sap = item( "maple_sap", calendar::turn_zero );
     return g->inv_map_splice( [&]( const item & it ) {
         return it.get_remaining_capacity_for_liquid( maple_sap, true ) > 0;
     }, _( "Use which container to collect sap?" ), PICKUP_RANGE,
     _( "You don't have a container at hand." ) );
 }
References _, g, item::get_remaining_capacity_for_liquid(), PICKUP_RANGE, and calendar::turn_zero.
Referenced by iexamine::tree_maple(), and iexamine::tree_maple_tapped().
mill_activate()
static void mill_activate (Character & you, const tripoint & examp) static
Definition at line 6098 of file iexamine.cpp.
 {
     map &here = get_map();
     const furn_id cur_mill_type = here.furn( examp );
     furn_id next_mill_type = furn_str_id::NULL_ID();
     if( cur_mill_type == furn_f_wind_mill ) {
         next_mill_type = furn_f_wind_mill_active;
     } else if( cur_mill_type == furn_f_water_mill ) {
         next_mill_type = furn_f_water_mill_active;
     } else {
         debugmsg( "Examined furniture has action mill_activate, but is of type %s",
                   here.furn( examp ).id().c_str() );
         return;
     }
     bool food_present = false;
     map_stack items = here.i_at( examp );
     units::volume food_volume = 0_ml;
     std::map<itype_id, int> millable_counts;
     for( const item &iter : items ) {
         if( iter.type->milling_data && !iter.type->milling_data->into_.is_null() ) {
             if( millable_counts.find( iter.typeId() ) == millable_counts.end() ) {
                 millable_counts.emplace( iter.typeId(), 1 );
             } else {
                 millable_counts[iter.typeId()]++;
             }
         }
     }
     for( std::pair<const string_id<itype>, int> mill_type_count : millable_counts ) {
         item source( mill_type_count.first );
         const item product( source.type->milling_data->into_ );
         const recipe rec = *source.type->milling_data->recipe_;
         if( rec.is_null() ) {
             debugmsg( _( "Failed to find milling recipe for %s." ),
                       source.tname( 1, false ) );
             add_msg( m_bad, _( "This mill contains %s, which can't be milled!" ), source.tname( 1, false ) );
             add_msg( _( "You remove the %s from the mill." ), source.tname() );
             for( int i = 0; i < mill_type_count.second; i++ ) {
                 here.add_item_or_charges( you.pos(), source );
                 you.mod_moves( -you.item_handling_cost( source ) );
                 for( item &iter : items ) {
                     if( iter.typeId() == source.typeId() ) {
                         here.i_rem( examp, &iter );
                         break;
                     }
                 }
             }
         } else {
             const requirement_data::alter_item_comp_vector &components =
                 rec.simple_requirements().get_components();
             int lot_size = 0;
             // Making the assumption that milling only uses a single type of input product. Support for mixed products would require additional logic.
             // We also make the assumption that this is the only relevant input, so if lubricants etc. was to be added more logic would be needed.
             for( const std::vector<item_comp> &component : components ) {
                 for( const item_comp &comp : component ) {
                     if( comp.type == mill_type_count.first ) {
                         lot_size = comp.count;
                         break;
                     }
                 }
                 if( lot_size > 0 ) {
                     break;
                 }
             }
             if( lot_size == 0 ) {
                 debugmsg( _( "Failed to find milling recipe for %s. It can't be milled." ),
                           source.display_name().c_str() );
                 add_msg( m_bad, _( "This mill contains %s, which can't be milled!" ), source.tname( 1, false ) );
                 add_msg( _( "You remove the %s from the mill." ), source.tname() );
                 for( int i = 0; i < mill_type_count.second; i++ ) {
                     here.add_item_or_charges( you.pos(), source );
                     you.mod_moves( -you.item_handling_cost( source ) );
                     for( item &iter : items ) {
                         if( iter.typeId() == source.typeId() ) {
                             here.i_rem( examp, &iter );
                             break;
                         }
                     }
                 }
             } else {
                 const int batches = mill_type_count.second / lot_size;
                 const int process_count = batches * lot_size;
                 if( batches == 0 ) {
                     add_msg( m_bad, _( "This mill contains too little of %s, which requires a batch size of %d." ),
                              source.tname( 1, false ), lot_size );
                     add_msg( _( "You remove the %s from the mill." ), source.tname() );
                     for( int i = 0; i < mill_type_count.second; i++ ) {
                         here.add_item_or_charges( you.pos(), source );
                         you.mod_moves( -you.item_handling_cost( source ) );
                         for( item &iter : items ) {
                             if( iter.typeId() == source.typeId() ) {
                                 here.i_rem( examp, &iter );
                                 break;
                             }
                         }
                     }
                 } else if( process_count != mill_type_count.second ) {
                     add_msg( m_bad,
                              _( "This mill doesn't contain a full last batch of %s, which requires a batch size of %d." ),
                              source.tname( 1, false ), lot_size );
                     add_msg( _( "You remove the excess %s from the mill." ), source.tname() );
                     for( int i = 0; i < mill_type_count.second - process_count; i++ ) {
                         here.add_item_or_charges( you.pos(), source );
                         you.mod_moves( -you.item_handling_cost( source ) );
                         for( item &iter : items ) {
                             if( iter.typeId() == source.typeId() ) {
                                 here.i_rem( examp, &iter );
                                 break;
                             }
                         }
                     }
                 }
             }
         }
     }
     for( item &it : items ) {
         if( it.type->milling_data && !it.type->milling_data->into_.is_null() ) {
             food_present = true;
             food_volume += it.volume();
             continue;
         } else {
             add_msg( m_bad, _( "This mill contains %s, which can't be milled!" ), it.tname( 1, false ) );
             add_msg( _( "You remove the %s from the mill." ), it.tname() );
             here.add_item_or_charges( you.pos(), it );
             you.mod_moves( -you.item_handling_cost( it ) );
             here.i_rem( examp, &it );
             return;
         }
     }
     if( !food_present ) {
         add_msg( _( "This mill is empty.  Fill it with starchy products such as wheat, barley or oats and try again." ) );
         return;
     }
     // TODO: currently mill just uses sm_rack defined max volume
     if( food_volume > sm_rack::MAX_FOOD_VOLUME ) {
         add_msg( _( "This mill is overloaded with products, and the millstone can't turn.  Remove some and try again." ) );
         add_msg( pgettext( "volume units", "You think that you can load about %s %s in it." ),
                  format_volume( sm_rack::MAX_FOOD_VOLUME ), volume_units_long() );
         return;
     }
     for( item &it : here.i_at( examp ) ) {
         if( it.type->milling_data && !it.type->milling_data->into_.is_null() ) {
             // Do one final rot check before milling, then apply the PROCESSING flag to prevent further checks.
             it.process_temperature_rot( 1, examp, get_map(), nullptr );
             it.set_flag( flag_PROCESSING );
         }
     }
     here.furn_set( examp, next_mill_type );
     item result( "fake_milling_item", calendar::turn );
     result.item_counter = to_turns<int>( milling_time );
     result.activate();
     here.add_item( examp, result );
     add_msg( _( "You remove the brake on the millstone and it slowly starts to turn." ) );
 }
References _, item::activate(), map::add_item(), map::add_item_or_charges(), add_msg(), string_id< T >::c_str(), debugmsg, item::display_name(), flag_PROCESSING, format_volume(), map::furn(), furn_f_water_mill, furn_f_water_mill_active, furn_f_wind_mill, furn_f_wind_mill_active, map::furn_set(), requirement_data::get_components(), get_map(), map::i_at(), map::i_rem(), int_id< T >::id(), recipe::is_null(), item::item_counter, Character::item_handling_cost(), m_bad, sm_rack::MAX_FOOD_VOLUME, itype::milling_data, milling_time, Creature::mod_moves(), string_id< furn_t >::NULL_ID(), pgettext, Creature::pos(), recipe::simple_requirements(), item::tname(), calendar::turn, item::type, item::typeId(), and volume_units_long().
Referenced by iexamine::quern_examine().
mill_load_food()
static void mill_load_food (Character & you, const tripoint & examp, const units::volume & remaining_capacity) static
Definition at line 6600 of file iexamine.cpp.
 {
     std::vector<item_comp> comps;
     map &here = get_map();
     if( here.furn( examp ) == furn_f_wind_mill_active ||
         here.furn( examp ) == furn_f_water_mill_active ) {
         you.add_msg_if_player( _( "You can't place more food while it's milling." ) );
         return;
     }
     // filter millable food
     inventory inv = you.crafting_inventory();
     inv.remove_items_with( []( const item & it ) {
         return it.rotten();
     } );
     std::vector<const item *> filtered = you.crafting_inventory().items_with( []( const item & it ) {
         if( !it.type->milling_data || it.type->milling_data->into_.is_null() ) {
             return false;
         }
         const item product( it.type->milling_data->into_ );
         const recipe rec = *it.type->milling_data->recipe_;
         if( rec.is_null() ) {
             debugmsg( _( "Failed to find milling recipe for %s. It can't be inserted into the mill." ),
                       it.display_name().c_str() );
             return false;
         }
         const requirement_data::alter_item_comp_vector &components =
             rec.simple_requirements().get_components();
         // Making the assumption that milling only uses a single type of input product. Support for mixed products would require additional logic.
         // We also make the assumption that this is the only relevant input, so if lubricants etc. was to be added more logic would be needed.
         for( const std::vector<item_comp> &component : components ) {
             for( const item_comp &comp : component ) {
                 if( comp.type == it.typeId() ) {
                     return true;
                 }
             }
         }
         debugmsg( _( "Failed to find milling recipe for %s. Cannot be placed into the mill." ),
                   it.display_name().c_str() );
         return false;
     } );
     uilist smenu;
     smenu.text = _( "Load mill with what kind of product?" );
     // count and ask for item to be placed ...
     std::list<std::string> names;
     std::vector<const item *> entries;
     for( const item *millable_item : filtered ) {
         int count;
         if( millable_item->count_by_charges() ) {
             count = inv.charges_of( millable_item->typeId() );
         } else {
             count = inv.amount_of( millable_item->typeId() );
         }
         if( count != 0 ) {
             auto on_list = std::find( names.begin(), names.end(), item::nname( millable_item->typeId(), 1 ) );
             if( on_list == names.end() ) {
                 smenu.addentry( item::nname( millable_item->typeId(), 1 ) );
                 entries.push_back( millable_item );
             }
             names.push_back( item::nname( millable_item->typeId(), 1 ) );
             comps.emplace_back( millable_item->typeId(), count );
         }
     }
     if( comps.empty() ) {
         you.add_msg_if_player( _( "You don't have any products that can be milled." ) );
         return;
     }
     smenu.query();
     if( smenu.ret < 0 || static_cast<size_t>( smenu.ret ) >= entries.size() ) {
         add_msg( m_info, _( "Never mind." ) );
         return;
     }
     int count = 0;
     const item *what = entries[smenu.ret];
     for( const item_comp &c : comps ) {
         if( c.type == what->typeId() ) {
             count = c.count;
         }
     }
     const int max_count_for_capacity = remaining_capacity / what->base_volume();
     const int max_count = std::min( count, max_count_for_capacity );
     // ... then ask how many to put it
     const std::string popupmsg = string_format( _( "Insert how many %s into the mill?" ),
                                  item::nname( what->typeId(), count ) );
     int amount = string_input_popup()
                  .title( popupmsg )
                  .width( 20 )
                  .text( std::to_string( max_count ) )
                  .only_digits( true )
                  .query_int();
     if( amount == 0 ) {
         add_msg( m_info, _( "Never mind." ) );
         return;
     } else if( amount > count ) {
         add_msg( m_info, _( "You don't have that many." ) );
         return;
     } else if( amount > max_count_for_capacity ) {
         add_msg( m_info, _( "You can't place that many." ) );
         return;
     }
     // reload comps with chosen items and quantity
     comps.clear();
     comps.emplace_back( what->typeId(), amount );
     Character &player_character = get_player_character();
     // select from where to get the items from and place them
     inv.form_from_map( player_character.pos(), PICKUP_RANGE, &player_character );
     inv.remove_items_with( []( const item & it ) {
         return it.rotten();
     } );
     comp_selection<item_comp> selected = you.select_item_component( comps, 1, inv, true,
                                          is_non_rotten_crafting_component );
     std::list<item> moved = you.consume_items( selected, 1, is_non_rotten_crafting_component );
     for( const item &m : moved ) {
         here.add_item( examp, m );
         you.mod_moves( -you.item_handling_cost( m ) );
         add_msg( m_info, _( "You carefully place %1$d %2$s in the mill." ), m.count(),
                  m.tname( m.count() ) );
     }
     you.invalidate_crafting_inventory();
 }
References _, Character::add_msg_if_player(), Character::crafting_inventory(), debugmsg, item::display_name(), map::furn(), furn_f_water_mill_active, furn_f_wind_mill_active, get_map(), visitable::items_with(), itype::milling_data, inventory::remove_items_with(), item::rotten(), and item::type.
Referenced by iexamine::quern_examine().
operator_present()
static Character& operator_present (Character & you, const tripoint & autodoc_loc, Character & null_patient) static
Definition at line 5594 of file iexamine.cpp.
 {
     map &here = get_map();
     for( const tripoint &loc : here.points_in_radius( autodoc_loc, 1 ) ) {
         if( !here.has_flag_furn( ter_furn_flag::TFLAG_AUTODOC_COUCH, loc ) ) {
             if( you.pos() == loc ) {
                 return you;
             }
             for( const npc *e : g->allies() ) {
                 if( e->pos() == loc ) {
                     return  *g->critter_by_id<Character>( e->getID() );
                 }
             }
         }
     }
     return null_patient;
 }
References g, get_map(), map::has_flag_furn(), map::points_in_radius(), Creature::pos(), and TFLAG_AUTODOC_COUCH.
Referenced by iexamine::autodoc().
pick_plant()
static void pick_plant (Character & you, const tripoint & examp, const itype_id & itemType, ter_id new_ter, bool seeds = false) static
Survival increases number of plants harvested
Definition at line 4253 of file iexamine.cpp.
 {
     map &here = get_map();
     bool auto_forage = get_option<bool>( "AUTO_FEATURES" ) &&
                        get_option<std::string>( "AUTO_FORAGING" ) != "off";
     if( you.is_avatar() && !auto_forage &&
         !query_yn( _( "Harvest the %s?" ), here.tername( examp ) ) ) {
         iexamine::none( you, examp );
         return;
     }
     const float survival = you.get_skill_level( skill_survival );
     you.practice( skill_survival, 6 );
     int plantBase = rng( 2, 5 );
     ///\EFFECT_SURVIVAL increases number of plants harvested
     int plantCount = rng( plantBase, round( plantBase + survival / 2 ) );
     plantCount = std::min( plantCount, 12 );
     here.spawn_item( you.pos(), itemType, plantCount, 0, calendar::turn );
     if( seeds ) {
         // FIXME: shouldn't derive seed type by string manipulation
         here.spawn_item( you.pos(), itype_id( "seed_" + itemType.str() ), 1,
                          rng( plantCount / 4, plantCount / 2 ), calendar::turn );
     }
     here.ter_set( examp, new_ter );
 }
References _, get_map(), Character::get_skill_level(), Creature::is_avatar(), min(), iexamine::none(), Creature::pos(), Character::practice(), query_yn(), rng(), round(), skill_survival, map::spawn_item(), string_id< T >::str(), map::ter_set(), map::tername(), and calendar::turn.
Referenced by iexamine::shrub_marloss(), and iexamine::tree_marloss().
player_on_couch()
static Character& player_on_couch (Character & you, const tripoint & autodoc_loc, Character & null_patient, bool & adjacent_couch, tripoint & couch_pos) static
Definition at line 5572 of file iexamine.cpp.
 {
     map &here = get_map();
     for( const tripoint &couch_loc : here.points_in_radius( autodoc_loc, 1 ) ) {
         if( here.has_flag_furn( ter_furn_flag::TFLAG_AUTODOC_COUCH, couch_loc ) ) {
             adjacent_couch = true;
             couch_pos = couch_loc;
             if( you.pos() == couch_loc ) {
                 return you;
             }
             for( const npc *e : g->allies() ) {
                 if( e->pos() == couch_loc ) {
                     return  *g->critter_by_id<Character>( e->getID() );
                 }
             }
         }
     }
     return null_patient;
 }
References g, get_map(), map::has_flag_furn(), map::points_in_radius(), Creature::pos(), and TFLAG_AUTODOC_COUCH.
Referenced by iexamine::autodoc().
popup_player_or_npc()
template<typename ... Args> void popup_player_or_npc (Character & you, const char * player_mes, const char * npc_mes, Args &&... args) inline
Definition at line 5674 of file iexamine.cpp.
 {
     if( you.is_avatar() ) {
         popup( player_mes, std::forward<Args>( args )... );
     } else {
         popup( you.replace_with_npc_name( string_format( npc_mes, std::forward<Args>( args )... ) ) );
     }
 }
References Creature::is_avatar(), popup(), Creature::replace_with_npc_name(), and string_format().
Referenced by iexamine::autodoc().
query_pick()
static bool query_pick (Character & who, const tripoint & target) static
Definition at line 2353 of file iexamine.cpp.
 {
     if( !who.is_avatar() ) {
         return false;
     }
     map &here = get_map();
     const harvest_id harvest = here.get_harvest( target );
     if( harvest.is_null() || harvest->empty() ) {
         who.add_msg_if_player( m_info,
                                _( "Nothing can be harvested from this plant in current season." ) );
         iexamine::none( who, target );
         return false;
     }
     std::string query_string;
     if( here.has_furn( target ) ) {
         query_string = string_format( _( "Pick %1$s?" ), here.furnname( target ) );
     } else {
         query_string = string_format( _( "Pick %1$s?" ), here.tername( target ) );
     }
     if( who.is_avatar() && !query_yn( query_string ) ) {
         iexamine::none( who, target );
         return false;
     }
     return true;
 }
References _, Character::add_msg_if_player(), map::furnname(), map::get_harvest(), get_map(), harvest, map::has_furn(), Creature::is_avatar(), m_info, iexamine::none(), query_yn(), string_format(), and map::tername().
Referenced by iexamine::harvest_furn(), iexamine::harvest_furn_nectar(), iexamine::harvest_ter(), iexamine::harvest_ter_nectar(), and iexamine::tree_hickory().
reload_furniture()
static void reload_furniture (Character & you, const tripoint & examp, bool allow_unload) static
Definition at line 4738 of file iexamine.cpp.
 {
     map &here = get_map();
     const furn_t &f = here.furn( examp ).obj();
     const itype *pseudo_type = f.crafting_pseudo_item_type();
     const std::vector<const itype *> ammo_list = f.crafting_ammo_item_types();
     bool use_ammotype = f.has_flag( ter_furn_flag::TFLAG_AMMOTYPE_RELOAD );
     auto can_be_reloaded = []( const std::vector<const itype *> &lst ) {
         for( const itype *atype : lst ) {
             if( atype != nullptr && atype->ammo ) {
                 return true;
             }
         }
         return false;
     };
     if( pseudo_type == nullptr || !can_be_reloaded( ammo_list ) ) {
         add_msg( m_info, _( "This %s can not be reloaded!" ), f.name() );
         return;
     }
     const itype *ammo_loaded = nullptr;
     int amount_in_furn = 0;
     for( const itype *ammo : ammo_list ) {
         itype_id ammo_itypeID( ammo->get_id() );
         int amount_tmp = use_ammotype ?
                          count_charges_in_list( &ammo->ammo->type, here.i_at( examp ), ammo_itypeID ) :
                          count_charges_in_list( ammo, here.i_at( examp ) );
         if( allow_unload && amount_tmp > 0 ) {
             ammo_loaded = ammo;
             amount_in_furn = amount_tmp;
             if( you.query_yn( _( "The %1$s contains %2$d %3$s.  Unload?" ), f.name(), amount_in_furn,
                               ammo_itypeID->nname( amount_in_furn ) ) ) {
                 map_stack items = here.i_at( examp );
                 for( map_stack::iterator itm = items.begin(); itm != items.end(); ) {
                     if( itm->typeId() == ammo_itypeID ) {
                         if( you.can_stash( *itm ) ) {
                             std::vector<item_location> target_items{ item_location( map_cursor( examp ), &*itm ) };
                             you.assign_activity( pickup_activity_actor( target_items, { 0 }, you.pos(), false ) );
                             return;
                         } else {
                             // get handling cost before the item reference is invalidated
                             const int handling_cost = -you.item_handling_cost( *itm );
                             add_msg( _( "You remove %1$s from the %2$s." ), itm->tname(), f.name() );
                             here.add_item_or_charges( you.pos(), *itm );
                             itm = items.erase( itm );
                             you.mod_moves( handling_cost );
                             return;
                         }
                     } else {
                         itm++;
                     }
                 }
             }
         }
     }
     if( ammo_loaded ) {
         const int max_amount_in_furn = item( pseudo_type ).ammo_capacity( ammo_loaded->ammo->type );
         if( amount_in_furn >= max_amount_in_furn ) {
             add_msg( m_info, _( "The %s is full, cannot reload." ), f.name() );
             return;
         }
     }
     item pseudo( pseudo_type );
     // maybe at some point we need a pseudo item_location or something
     // but for now this should at least work as intended
     item_location pseudo_loc( map_cursor( examp ), &pseudo );
     // used to only allow one type of ammo, changed with move to inventory_selector
     // todo: use furniture name instead of pseudo item name
     item::reload_option opt = game_menus::inv::select_ammo( you, pseudo_loc );
     if( !opt ) {
         return;
     }
     if( ammo_loaded && opt.ammo->type != ammo_loaded ) {
         add_msg( m_info, _( "This %s is already loaded with %s!" ), f.name(), ammo_loaded->nname( 0 ) );
         return;
     }
     const int max_reload_amount = item( pseudo_type ).ammo_capacity(
                                       opt.ammo->ammo_type() ) - amount_in_furn;
     const itype *opt_type = opt.ammo->type;
     const int max_amount = std::min( opt.qty(), max_reload_amount );
     const std::string popupmsg = string_format( _( "Put how many of the %1$s into the %2$s?" ),
                                  opt_type->nname( max_amount ), f.name() );
     int amount = string_input_popup()
                  .title( popupmsg )
                  .width( 20 )
                  .text( std::to_string( max_amount ) )
                  .only_digits( true )
                  .query_int();
     if( amount <= 0 || amount > max_amount ) {
         return;
     }
     auto place_item = [&here, &examp]( const item & it ) {
         for( item &e : here.i_at( examp ) ) {
             if( e.merge_charges( it ) ) {
                 return;
             }
         }
         here.add_item( examp, it );
     };
     item moved( opt_type, opt.ammo.get_item()->birthday(), amount );
     place_item( moved );
     you.mod_moves( -you.item_handling_cost( moved ) );
     std::list<item>used;
     if( opt.ammo.get_item()->use_charges( opt_type->get_id(), amount, used,
                                           opt.ammo.position() ) ) {
         opt.ammo.remove_item();
     }
     const int amount_in_furn_after_placing = count_charges_in_list( opt_type,
             here.i_at( examp ) );
     //~ %1$s - furniture, %2$d - number, %3$s items.
     add_msg( _( "The %1$s contains %2$d %3$s." ), f.name(), amount_in_furn_after_placing,
              opt_type->nname( amount_in_furn_after_placing ) );
     add_msg( _( "You reload the %s." ), here.furnname( examp ) );
     you.invalidate_crafting_inventory();
 }
References _, map::add_item(), map::add_item_or_charges(), add_msg(), item::reload_option::ammo, itype::ammo, item::ammo_capacity(), item::ammo_type(), Character::assign_activity(), item_stack::begin(), item::birthday(), Character::can_stash(), count_charges_in_list(), furn_t::crafting_ammo_item_types(), furn_t::crafting_pseudo_item_type(), item_stack::end(), map_stack::erase(), map::furn(), map::furnname(), itype::get_id(), item_location::get_item(), get_map(), map_data_common_t::has_flag(), map::i_at(), Character::invalidate_crafting_inventory(), Character::item_handling_cost(), m_info, min(), Creature::mod_moves(), map_data_common_t::name(), itype::nname(), int_id< T >::obj(), string_input_popup::only_digits(), Creature::pos(), item_location::position(), item::reload_option::qty(), string_input_popup::query_int(), Character::query_yn(), item_location::remove_item(), game_menus::inv::select_ammo(), string_format(), string_input_popup::text(), TFLAG_AMMOTYPE_RELOAD, string_input_popup::title(), to_string(), item::type, item::use_charges(), and string_input_popup::width().
Referenced by iexamine::reload_furniture(), and iexamine::smoker_options().
smoker_activate()
static void smoker_activate (Character & you, const tripoint & examp) static
Definition at line 6265 of file iexamine.cpp.
 {
     map &here = get_map();
     furn_id cur_smoker_type = here.furn( examp );
     furn_id next_smoker_type = furn_str_id::NULL_ID();
     const bool portable = here.furn( examp ) == furn_f_metal_smoking_rack ||
                           here.furn( examp ) == furn_f_metal_smoking_rack_active;
     if( cur_smoker_type == furn_f_smoking_rack ) {
         next_smoker_type = furn_f_smoking_rack_active;
     } else if( cur_smoker_type == furn_f_metal_smoking_rack ) {
         next_smoker_type = furn_f_metal_smoking_rack_active;
     } else {
         debugmsg( "Examined furniture has action smoker_activate, but is of type %s",
                   here.furn( examp ).id().c_str() );
         return;
     }
     bool food_present = false;
     bool charcoal_present = false;
     map_stack items = here.i_at( examp );
     units::volume food_volume = 0_ml;
     item *charcoal = nullptr;
     for( item &it : items ) {
         if( it.has_flag( flag_SMOKED ) && !it.has_flag( flag_SMOKABLE ) ) {
             add_msg( _( "This rack already contains smoked food." ) );
             add_msg( _( "Remove it before firing the smoking rack again." ) );
             return;
         }
         if( it.has_flag( flag_SMOKABLE ) ) {
             food_present = true;
             food_volume += it.volume();
             continue;
         }
         if( it.typeId() == itype_charcoal ) {
             charcoal_present = true;
             charcoal = &it;
         }
         if( it.typeId() != itype_charcoal && !it.has_flag( flag_SMOKABLE ) ) {
             add_msg( m_bad, _( "This rack contains %s, which can't be smoked!" ), it.tname( 1,
                      false ) );
             add_msg( _( "You remove %s from the rack." ), it.tname() );
             here.add_item_or_charges( you.pos(), it );
             you.mod_moves( -you.item_handling_cost( it ) );
             here.i_rem( examp, &it );
             return;
         }
         if( it.has_flag( flag_SMOKED ) && it.has_flag( flag_SMOKABLE ) ) {
             add_msg( _( "This rack has some smoked food that might be dehydrated by smoking it again." ) );
         }
     }
     if( !food_present ) {
         add_msg( _( "This rack is empty.  Fill it with raw meat, fish or sausages and try again." ) );
         return;
     }
     if( !charcoal_present ) {
         add_msg( _( "There is no charcoal in the rack." ) );
         return;
     }
     if( portable && food_volume > sm_rack::MAX_FOOD_VOLUME_PORTABLE ) {
         add_msg( _( "This rack is overloaded with food, and it blocks the flow of smoke.  Remove some and try again." ) );
         add_msg( _( "You think that you can load about %s %s in it." ),
                  format_volume( sm_rack::MAX_FOOD_VOLUME_PORTABLE ), volume_units_long() );
         return;
     } else if( food_volume > sm_rack::MAX_FOOD_VOLUME ) {
         add_msg( _( "This rack is overloaded with food, and it blocks the flow of smoke.  Remove some and try again." ) );
         add_msg( _( "You think that you can load about %s %s in it." ),
                  format_volume( sm_rack::MAX_FOOD_VOLUME ), volume_units_long() );
         return;
     }
     int char_charges = get_charcoal_charges( food_volume );
     if( count_charges_in_list( charcoal->type, here.i_at( examp ) ) < char_charges ) {
         add_msg( _( "There is not enough charcoal in the rack to smoke this much food." ) );
         add_msg( _( "You need at least %1$s pieces of charcoal, and the smoking rack has %2$s inside." ),
                  char_charges, count_charges_in_list( charcoal->type, here.i_at( examp ) ) );
         return;
     }
     if( !you.has_charges( itype_fire, 1 ) ) {
         add_msg( _( "This smoking rack is ready to be fired, but you have no fire source." ) );
         return;
     } else if( !query_yn( _( "Fire the smoking rack?" ) ) ) {
         return;
     }
     you.use_charges( itype_fire, 1 );
     for( item &it : here.i_at( examp ) ) {
         if( it.has_flag( flag_SMOKABLE ) ) {
             it.process_temperature_rot( 1, examp, get_map(), nullptr );
             it.set_flag( flag_PROCESSING );
         }
     }
     here.furn_set( examp, next_smoker_type );
     if( charcoal->charges == char_charges ) {
         here.i_rem( examp, charcoal );
     } else {
         charcoal->charges -= char_charges;
     }
     item result( "fake_smoke_plume", calendar::turn );
     result.item_counter = to_turns<int>( 6_hours );
     result.activate();
     here.add_item( examp, result );
     if( you.has_trait( trait_PYROMANIA ) ) {
         you.add_morale( MORALE_PYROMANIA_STARTFIRE, 5, 10, 3_hours, 2_hours );
         you.rem_morale( MORALE_PYROMANIA_NOFIRE );
         you.add_msg_if_player( m_good,
                                _( "You happily light a small fire under the rack and it starts to smoke." ) );
     } else {
         add_msg( _( "You light a small fire under the rack and it starts to smoke." ) );
     }
 }
References _, item::activate(), map::add_item(), map::add_item_or_charges(), Character::add_morale(), add_msg(), Character::add_msg_if_player(), string_id< T >::c_str(), item::charges, count_charges_in_list(), debugmsg, flag_PROCESSING, flag_SMOKABLE, flag_SMOKED, format_volume(), map::furn(), furn_f_metal_smoking_rack, furn_f_metal_smoking_rack_active, furn_f_smoking_rack, furn_f_smoking_rack_active, map::furn_set(), get_charcoal_charges(), get_map(), Character::has_charges(), Character::has_trait(), map::i_at(), map::i_rem(), int_id< T >::id(), item::item_counter, Character::item_handling_cost(), itype_charcoal, itype_fire, m_bad, m_good, sm_rack::MAX_FOOD_VOLUME, sm_rack::MAX_FOOD_VOLUME_PORTABLE, Creature::mod_moves(), MORALE_PYROMANIA_NOFIRE, MORALE_PYROMANIA_STARTFIRE, string_id< furn_t >::NULL_ID(), Creature::pos(), query_yn(), Character::rem_morale(), trait_PYROMANIA, calendar::turn, item::type, Character::use_charges(), and volume_units_long().
Referenced by iexamine::smoker_options().
smoker_finalize()
static void smoker_finalize (Character & , const tripoint & examp, const time_point & start_time) static
Definition at line 6495 of file iexamine.cpp.
 {
     map &here = get_map();
     furn_id cur_smoker_type = here.furn( examp );
     furn_id next_smoker_type = furn_str_id::NULL_ID();
     if( cur_smoker_type == furn_f_smoking_rack_active ) {
         next_smoker_type = furn_f_smoking_rack;
     } else if( cur_smoker_type == furn_f_metal_smoking_rack_active ) {
         next_smoker_type = furn_f_metal_smoking_rack;
     } else {
         debugmsg( "Furniture executed action smoker_finalize, but is of type %s",
                   here.furn( examp ).id().c_str() );
         return;
     }
     map_stack items = here.i_at( examp );
     if( items.empty() ) {
         here.furn_set( examp, next_smoker_type );
         return;
     }
     for( item &it : items ) {
         if( it.has_flag( flag_SMOKABLE ) && it.get_comestible() ) {
             if( it.get_comestible()->smoking_result.is_empty() ) {
                 it.unset_flag( flag_PROCESSING );
             } else {
                 it.calc_rot_while_processing( 6_hours );
                 item result( it.get_comestible()->smoking_result, start_time + 6_hours );
                 if( it.count_by_charges() ) {
                     result.charges = it.charges;
                 }
                 // Set flag to tell set_relative_rot() to calc from bday not now
                 result.set_flag( flag_PROCESSING_RESULT );
                 result.set_relative_rot( it.get_relative_rot() );
                 result.unset_flag( flag_PROCESSING_RESULT );
                 recipe rec;
                 result.inherit_flags( it, rec );
                 if( !result.has_flag( flag_NUTRIENT_OVERRIDE ) ) {
                     // If the item has "cooks_like" it will be replaced by that item as a component.
                     if( !it.get_comestible()->cooks_like.is_empty() ) {
                         // Set charges to 1 for stacking purposes.
                         it = item( it.get_comestible()->cooks_like, it.birthday(), 1 );
                     }
                     result.components.add( it );
                     // Smoking is always 1:1, so these must be equal for correct kcal/vitamin calculation.
                     result.recipe_charges = it.count();
                     result.set_flag_recursive( flag_COOKED );
                 }
                 it = result;
             }
         }
     }
     here.furn_set( examp, next_smoker_type );
 }
References item_components::add(), string_id< T >::c_str(), item::charges, item::components, debugmsg, item_stack::empty(), flag_COOKED, flag_NUTRIENT_OVERRIDE, flag_PROCESSING, flag_PROCESSING_RESULT, flag_SMOKABLE, map::furn(), furn_f_metal_smoking_rack, furn_f_metal_smoking_rack_active, furn_f_smoking_rack, furn_f_smoking_rack_active, map::furn_set(), get_map(), item::has_flag(), map::i_at(), int_id< T >::id(), item::inherit_flags(), string_id< furn_t >::NULL_ID(), item::recipe_charges, item::set_flag(), item::set_flag_recursive(), item::set_relative_rot(), and item::unset_flag().
Referenced by iexamine::on_smoke_out().
smoker_load_food()
static void smoker_load_food (Character & you, const tripoint & examp, const units::volume & remaining_capacity) static
Definition at line 6554 of file iexamine.cpp.
 {
     map &here = get_map();
     if( here.furn( examp ) == furn_f_smoking_rack_active ||
         here.furn( examp ) == furn_f_metal_smoking_rack_active ) {
         you.add_msg_if_player( _( "You can't place more food while it's smoking." ) );
         return;
     }
     furn_id rack = here.furn( examp );
     units::volume total_capacity = rack == furn_f_metal_smoking_rack ?
                                    sm_rack::MAX_FOOD_VOLUME_PORTABLE :
                                    sm_rack::MAX_FOOD_VOLUME;
     units::volume used_capacity = total_capacity - remaining_capacity;
     drop_locations locs = game_menus::inv::smoke_food( you, total_capacity, used_capacity );
     units::volume vol = remaining_capacity;
     for( const drop_location &dloc : locs ) {
         item_location original = dloc.first;
         original.overflow();
         item copy( *original );
         if( copy.count_by_charges() ) {
             copy.charges = clamp( copy.charges_per_volume( vol ), 1, dloc.second );
         }
         if( vol < copy.volume() ) {
             add_msg( m_info, _( "The %s doesn't fit in the rack." ), copy.tname( copy.count() ) );
             continue;
         }
         here.add_item( examp, copy );
         you.mod_moves( -you.item_handling_cost( copy ) );
         add_msg( m_info, _( "You carefully place %1$d %2$s in the rack." ), copy.count(),
                  copy.tname( copy.count() ) );
         vol -= copy.volume();
         if( !copy.count_by_charges() || original->charges == copy.charges ) {
             original.remove_item();
         } else {
             original->charges -= copy.charges;
         }
     }
 }
References _, map::add_item(), add_msg(), Character::add_msg_if_player(), item::charges, item::charges_per_volume(), clamp(), item::count(), item::count_by_charges(), map::furn(), furn_f_metal_smoking_rack, furn_f_metal_smoking_rack_active, furn_f_smoking_rack_active, get_map(), Character::item_handling_cost(), m_info, sm_rack::MAX_FOOD_VOLUME, sm_rack::MAX_FOOD_VOLUME_PORTABLE, Creature::mod_moves(), item_location::overflow(), item_location::remove_item(), game_menus::inv::smoke_food(), item::tname(), and item::volume().
Referenced by iexamine::smoker_options().
str_to_illiterate_str()
static std::string str_to_illiterate_str (std::string s) static
Definition at line 5048 of file iexamine.cpp.
 {
     if( !get_player_character().has_trait( trait_ILLITERATE ) ) {
         return s;
     } else {
         for( char &i : s ) {
             i = i + rng( 0, 5 ) - rng( 0, 5 );
             if( i < ' ' ) {
                 // some control character, most likely not handled correctly be the print functions
                 i = ' ';
             } else if( i == '%' ) {
                 // avoid characters that trigger formatting in the various print functions
                 i++;
             }
         }
         return s;
     }
 }
References get_player_character(), rng(), and trait_ILLITERATE.
Referenced by getGasDiscountName(), and iexamine::pay_gas().
turnOnSelectedPump()
static void turnOnSelectedPump (const tripoint & p, int number, fuel_station_fuel_type & fuel_type) static
Definition at line 5159 of file iexamine.cpp.
 {
     int k = 0;
     map &here = get_map();
     for( const tripoint &tmp : here.points_in_radius( p, 12 ) ) {
         const ter_id t = here.ter( tmp );
         if( fuel_type == FUEL_TYPE_GASOLINE ) {
             if( t == ter_t_gas_pump || t == ter_t_gas_pump_a ) {
                 if( number == k++ ) {
                     here.ter_set( tmp, ter_t_gas_pump_a );
                 } else {
                     here.ter_set( tmp, ter_t_gas_pump );
                 }
             }
         } else if( fuel_type == FUEL_TYPE_DIESEL ) {
             if( t == ter_t_diesel_pump || t == ter_t_diesel_pump_a ) {
                 if( number == k++ ) {
                     here.ter_set( tmp, ter_t_diesel_pump_a );
                 } else {
                     here.ter_set( tmp, ter_t_diesel_pump );
                 }
             }
         }
     }
 }
References FUEL_TYPE_DIESEL, FUEL_TYPE_GASOLINE, get_map(), map::points_in_radius(), map::ter(), map::ter_set(), ter_t_diesel_pump, ter_t_diesel_pump_a, ter_t_gas_pump, and ter_t_gas_pump_a.
Referenced by iexamine::pay_gas().
Variable Documentation
ACT_ATM
const activity_id ACT_ATM("ACT_ATM") ("ACT_ATM") static
Referenced by anonymous_namespace{iexamine.cpp}::atm_menu::choose_option(), anonymous_namespace{iexamine.cpp}::atm_menu::do_exchange_cash(), and anonymous_namespace{iexamine.cpp}::atm_menu::do_transfer_all_money().
ACT_BUILD
const activity_id ACT_BUILD("ACT_BUILD") ("ACT_BUILD") static
Referenced by iexamine::part_con().
ACT_HARVEST
const activity_id ACT_HARVEST("ACT_HARVEST") ("ACT_HARVEST") static
Referenced by iexamine::clear_overgrown(), and iexamine::harvest_plant().
ACT_OPERATION
const activity_id ACT_OPERATION("ACT_OPERATION") ("ACT_OPERATION") static
Referenced by iexamine::autodoc().
ACT_PLANT_SEED
const activity_id ACT_PLANT_SEED("ACT_PLANT_SEED") ("ACT_PLANT_SEED") static
Referenced by iexamine::plant_seed().
ammo_money
const ammotype ammo_money("money") ("money") static
Referenced by anonymous_namespace{iexamine.cpp}::atm_menu::do_exchange_cash(), anonymous_namespace{iexamine.cpp}::atm_menu::do_transfer_all_money(), and anonymous_namespace{iexamine.cpp}::atm_menu::do_withdraw_money().
bio_lighter
const bionic_id bio_lighter("bio_lighter") ("bio_lighter") static
Referenced by iexamine::fireplace().
bio_lockpick
const bionic_id bio_lockpick("bio_lockpick") ("bio_lockpick") static
Referenced by iexamine::locked_object(), and iexamine::locked_object_pickable().
bio_painkiller
const bionic_id bio_painkiller("bio_painkiller") ("bio_painkiller") static
Referenced by iexamine::autodoc().
character_modifier_obstacle_climb_mod
const character_modifier_id character_modifier_obstacle_climb_mod("obstacle_climb_mod") ("obstacle_climb_mod") static
Referenced by iexamine::chainfence().
climbing_aid_furn_CLIMBABLE
const climbing_aid_id climbing_aid_furn_CLIMBABLE("furn_CLIMBABLE") ("furn_CLIMBABLE") static
Referenced by iexamine::chainfence().
effect_antibiotic
const efftype_id effect_antibiotic("antibiotic") ("antibiotic") static
Referenced by iexamine::autodoc().
effect_bite
const efftype_id effect_bite("bite") ("bite") static
Referenced by iexamine::autodoc().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by iexamine::autodoc().
effect_bouldering
const efftype_id effect_bouldering("bouldering") ("bouldering") static
Referenced by iexamine::ledge().
effect_disinfected
const efftype_id effect_disinfected("disinfected") ("disinfected") static
Referenced by iexamine::autodoc().
effect_earphones
const efftype_id effect_earphones("earphones") ("earphones") static
Referenced by iexamine::safe().
effect_gliding
const efftype_id effect_gliding("gliding") ("gliding") static
Referenced by iexamine::ledge().
effect_incorporeal
const efftype_id effect_incorporeal("incorporeal") ("incorporeal") static
Referenced by iexamine::workbench_internal().
effect_infected
const efftype_id effect_infected("infected") ("infected") static
Referenced by iexamine::autodoc().
effect_mending
const efftype_id effect_mending("mending") ("mending") static
Referenced by iexamine::autodoc().
effect_pblue
const efftype_id effect_pblue("pblue") ("pblue") static
Referenced by iexamine::autodoc().
effect_pkill2
const efftype_id effect_pkill2("pkill2") ("pkill2") static
Referenced by iexamine::flower_poppy().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by best_installer().
effect_slow_descent
const efftype_id effect_slow_descent("slow_descent") ("slow_descent") static
Referenced by iexamine::ledge().
effect_strong_antibiotic
const efftype_id effect_strong_antibiotic("strong_antibiotic") ("strong_antibiotic") static
Referenced by iexamine::autodoc().
effect_strong_antibiotic_visible
const efftype_id effect_strong_antibiotic_visible("strong_antibiotic_visible") ("strong_antibiotic_visible") static
Referenced by iexamine::autodoc().
effect_teleglow
const efftype_id effect_teleglow("teleglow") ("teleglow") static
Referenced by iexamine::flower_marloss().
effect_tetanus
const efftype_id effect_tetanus("tetanus") ("tetanus") static
Referenced by iexamine::autodoc().
effect_weak_antibiotic
const efftype_id effect_weak_antibiotic("weak_antibiotic") ("weak_antibiotic") static
Referenced by iexamine::autodoc().
furn_f_arcfurnace_empty
const furn_str_id furn_f_arcfurnace_empty("f_arcfurnace_empty") ("f_arcfurnace_empty") static
Referenced by iexamine::arcfurnace_empty(), and iexamine::arcfurnace_full().
furn_f_arcfurnace_full
const furn_str_id furn_f_arcfurnace_full("f_arcfurnace_full") ("f_arcfurnace_full") static
Referenced by iexamine::arcfurnace_empty(), and iexamine::arcfurnace_full().
furn_f_compost_empty
const furn_str_id furn_f_compost_empty("f_compost_empty") ("f_compost_empty") static
Referenced by compost_set_empty(), and compost_set_full().
furn_f_compost_full
const furn_str_id furn_f_compost_full("f_compost_full") ("f_compost_full") static
Referenced by compost_set_empty(), and compost_set_full().
furn_f_diesel_tank
const furn_str_id furn_f_diesel_tank("f_diesel_tank") ("f_diesel_tank") static
Referenced by iexamine::getNearFilledGasTank().
furn_f_flower_fungal
const furn_str_id furn_f_flower_fungal("f_flower_fungal") ("f_flower_fungal") static
Referenced by iexamine::harvest_plant().
furn_f_flower_marloss
const furn_str_id furn_f_flower_marloss("f_flower_marloss") ("f_flower_marloss") static
Referenced by iexamine::harvest_plant().
furn_f_fvat_empty
const furn_str_id furn_f_fvat_empty("f_fvat_empty") ("f_fvat_empty") static
Referenced by fvat_set_empty().
furn_f_fvat_full
const furn_str_id furn_f_fvat_full("f_fvat_full") ("f_fvat_full") static
Referenced by fvat_set_full().
furn_f_fvat_wood_empty
const furn_str_id furn_f_fvat_wood_empty("f_fvat_wood_empty") ("f_fvat_wood_empty") static
Referenced by fvat_set_empty(), and fvat_set_full().
furn_f_fvat_wood_full
const furn_str_id furn_f_fvat_wood_full("f_fvat_wood_full") ("f_fvat_wood_full") static
Referenced by fvat_set_empty(), and fvat_set_full().
furn_f_gas_tank
const furn_str_id furn_f_gas_tank("f_gas_tank") ("f_gas_tank") static
Referenced by iexamine::getNearFilledGasTank().
furn_f_kiln_empty
const furn_str_id furn_f_kiln_empty("f_kiln_empty") ("f_kiln_empty") static
Referenced by iexamine::kiln_empty(), and iexamine::kiln_full().
furn_f_kiln_full
const furn_str_id furn_f_kiln_full("f_kiln_full") ("f_kiln_full") static
Referenced by iexamine::kiln_empty(), and iexamine::kiln_full().
furn_f_kiln_metal_empty
const furn_str_id furn_f_kiln_metal_empty("f_kiln_metal_empty") ("f_kiln_metal_empty") static
Referenced by iexamine::kiln_empty(), and iexamine::kiln_full().
furn_f_kiln_metal_full
const furn_str_id furn_f_kiln_metal_full("f_kiln_metal_full") ("f_kiln_metal_full") static
Referenced by iexamine::kiln_empty(), and iexamine::kiln_full().
furn_f_metal_smoking_rack
const furn_str_id furn_f_metal_smoking_rack("f_metal_smoking_rack") ("f_metal_smoking_rack") static
Referenced by smoker_activate(), smoker_finalize(), smoker_load_food(), and iexamine::smoker_options().
furn_f_metal_smoking_rack_active
const furn_str_id furn_f_metal_smoking_rack_active("f_metal_smoking_rack_active") ("f_metal_smoking_rack_active") static
Referenced by iexamine::on_smoke_out(), smoker_activate(), smoker_finalize(), smoker_load_food(), and iexamine::smoker_options().
furn_f_safe_o
const furn_str_id furn_f_safe_o("f_safe_o") ("f_safe_o") static
Referenced by iexamine::open_safe(), and iexamine::safe().
furn_f_smoking_rack
const furn_str_id furn_f_smoking_rack("f_smoking_rack") ("f_smoking_rack") static
Referenced by smoker_activate(), smoker_finalize(), and iexamine::smoker_options().
furn_f_smoking_rack_active
const furn_str_id furn_f_smoking_rack_active("f_smoking_rack_active") ("f_smoking_rack_active") static
Referenced by iexamine::on_smoke_out(), smoker_activate(), smoker_finalize(), smoker_load_food(), and iexamine::smoker_options().
furn_f_stook_empty
const furn_str_id furn_f_stook_empty("f_stook_empty") ("f_stook_empty") static
Referenced by iexamine::stook_empty().
furn_f_stook_full
const furn_str_id furn_f_stook_full("f_stook_full") ("f_stook_full") static
Referenced by iexamine::stook_empty(), and iexamine::stook_full().
furn_f_water_mill
const furn_str_id furn_f_water_mill("f_water_mill") ("f_water_mill") static
Referenced by mill_activate(), iexamine::mill_finalize(), and iexamine::quern_examine().
furn_f_water_mill_active
const furn_str_id furn_f_water_mill_active("f_water_mill_active") ("f_water_mill_active") static
Referenced by mill_activate(), iexamine::mill_finalize(), mill_load_food(), and iexamine::quern_examine().
furn_f_wind_mill
const furn_str_id furn_f_wind_mill("f_wind_mill") ("f_wind_mill") static
Referenced by mill_activate(), iexamine::mill_finalize(), and iexamine::quern_examine().
furn_f_wind_mill_active
const furn_str_id furn_f_wind_mill_active("f_wind_mill_active") ("f_wind_mill_active") static
Referenced by mill_activate(), iexamine::mill_finalize(), mill_load_food(), and iexamine::quern_examine().
itype_2x4
const itype_id itype_2x4("2x4") ("2x4") static
Referenced by iexamine::pit().
itype_arm_splint
const itype_id itype_arm_splint("arm_splint") ("arm_splint") static
Referenced by iexamine::autodoc().
itype_bot_broken_cyborg
const itype_id itype_bot_broken_cyborg("bot_broken_cyborg") ("bot_broken_cyborg") static
Referenced by iexamine::autodoc(), and cyborg_on_couch().
itype_bot_prototype_cyborg
const itype_id itype_bot_prototype_cyborg("bot_prototype_cyborg") ("bot_prototype_cyborg") static
Referenced by cyborg_on_couch().
itype_cash_card
const itype_id itype_cash_card("cash_card") ("cash_card") static
Referenced by anonymous_namespace{iexamine.cpp}::atm_menu::do_deposit_money(), anonymous_namespace{iexamine.cpp}::atm_menu::do_exchange_cash(), anonymous_namespace{iexamine.cpp}::atm_menu::do_transfer_all_money(), iexamine::pay_gas(), anonymous_namespace{iexamine.cpp}::atm_menu::reset(), and iexamine::vending().
itype_charcoal
const itype_id itype_charcoal("charcoal") ("charcoal") static
Referenced by iexamine::kiln_empty(), iexamine::kiln_full(), smoker_activate(), and iexamine::smoker_options().
itype_chem_carbide
const itype_id itype_chem_carbide("chem_carbide") ("chem_carbide") static
Referenced by iexamine::arcfurnace_empty(), and iexamine::arcfurnace_full().
itype_corpse
const itype_id itype_corpse("corpse") ("corpse") static
Referenced by iexamine::autodoc(), and cyborg_on_couch().
itype_disassembly
const itype_id itype_disassembly("disassembly") ("disassembly") static
Referenced by iexamine::workbench_internal().
itype_fake_milling_item
const itype_id itype_fake_milling_item("fake_milling_item") ("fake_milling_item") static
Referenced by iexamine::quern_examine().
itype_fake_smoke_plume
const itype_id itype_fake_smoke_plume("fake_smoke_plume") ("fake_smoke_plume") static
Referenced by iexamine::smoker_options().
itype_fertilizer
const itype_id itype_fertilizer("fertilizer") ("fertilizer") static
Referenced by iexamine::fertilize_plant().
itype_fire
const itype_id itype_fire("fire") ("fire") static
Referenced by iexamine::kiln_empty(), and smoker_activate().
itype_foodperson_mask
const itype_id itype_foodperson_mask("foodperson_mask") ("foodperson_mask") static
Referenced by iexamine::cardreader_foodplace().
itype_foodperson_mask_on
const itype_id itype_foodperson_mask_on("foodperson_mask_on") ("foodperson_mask_on") static
Referenced by iexamine::cardreader_foodplace().
itype_fungal_seeds
const itype_id itype_fungal_seeds("fungal_seeds") ("fungal_seeds") static
Referenced by iexamine::harvest_plant().
itype_hickory_root
const itype_id itype_hickory_root("hickory_root") ("hickory_root") static
Referenced by iexamine::tree_hickory().
itype_id_science
const itype_id itype_id_science("id_science") ("id_science") static
Referenced by iexamine::cardreader_robofac().
itype_leg_splint
const itype_id itype_leg_splint("leg_splint") ("leg_splint") static
Referenced by iexamine::autodoc().
itype_maple_sap
const itype_id itype_maple_sap("maple_sap") ("maple_sap") static
Referenced by iexamine::tree_maple_tapped().
itype_marloss_berry
const itype_id itype_marloss_berry("marloss_berry") ("marloss_berry") static
Referenced by iexamine::shrub_marloss(), and iexamine::tree_marloss().
itype_marloss_seed
const itype_id itype_marloss_seed("marloss_seed") ("marloss_seed") static
Referenced by iexamine::flower_marloss(), and iexamine::harvest_plant().
itype_mycus_fruit
const itype_id itype_mycus_fruit("mycus_fruit") ("mycus_fruit") static
Referenced by iexamine::shrub_marloss(), and iexamine::tree_marloss().
itype_nail
const itype_id itype_nail("nail") ("nail") static
Referenced by iexamine::curtains().
itype_nanomaterial
const itype_id itype_nanomaterial("nanomaterial") ("nanomaterial") static
Referenced by iexamine::nanofab().
itype_petrified_eye
const itype_id itype_petrified_eye("petrified_eye") ("petrified_eye") static
Referenced by iexamine::pedestal_temple(), and iexamine::pedestal_wyrm().
itype_sheet
const itype_id itype_sheet("sheet") ("sheet") static
Referenced by iexamine::curtains().
itype_stick
const itype_id itype_stick("stick") ("stick") static
Referenced by iexamine::curtains().
itype_string_36
const itype_id itype_string_36("string_36") ("string_36") static
Referenced by iexamine::curtains().
itype_unfinished_cac2
const itype_id itype_unfinished_cac2("unfinished_cac2") ("unfinished_cac2") static
Referenced by iexamine::arcfurnace_empty(), and iexamine::arcfurnace_full().
itype_unfinished_charcoal
const itype_id itype_unfinished_charcoal("unfinished_charcoal") ("unfinished_charcoal") static
Referenced by iexamine::kiln_empty(), and iexamine::kiln_full().
json_flag_ATTUNEMENT
const json_character_flag json_flag_ATTUNEMENT("ATTUNEMENT") ("ATTUNEMENT") static
Referenced by iexamine::attunement_altar().
json_flag_GLIDE
const json_character_flag json_flag_GLIDE("GLIDE") ("GLIDE") static
Referenced by iexamine::ledge().
json_flag_LEVITATION
const json_character_flag json_flag_LEVITATION("LEVITATION") ("LEVITATION") static
Referenced by iexamine::ledge().
json_flag_PAIN_IMMUNE
const json_character_flag json_flag_PAIN_IMMUNE("PAIN_IMMUNE") ("PAIN_IMMUNE") static
Referenced by iexamine::autodoc().
json_flag_SAFECRACK_NO_TOOL
const json_character_flag json_flag_SAFECRACK_NO_TOOL("SAFECRACK_NO_TOOL") ("SAFECRACK_NO_TOOL") static
Referenced by iexamine::safe().
json_flag_WING_ARM
const json_character_flag json_flag_WING_ARM("WING_ARM") ("WING_ARM") static
Referenced by iexamine::ledge().
json_flag_WING_GLIDE
const json_character_flag json_flag_WING_GLIDE("WING_GLIDE") ("WING_GLIDE") static
Referenced by iexamine::ledge().
material_bone
const material_id material_bone("bone") ("bone") static
Referenced by iexamine::kiln_empty().
material_cac2powder
const material_id material_cac2powder("cac2powder") ("cac2powder") static
Referenced by iexamine::arcfurnace_empty().
material_ch_steel
const material_id material_ch_steel("ch_steel") ("ch_steel") static
Referenced by iexamine::cvdmachine().
material_hc_steel
const material_id material_hc_steel("hc_steel") ("hc_steel") static
Referenced by iexamine::cvdmachine().
material_lc_steel
const material_id material_lc_steel("lc_steel") ("lc_steel") static
Referenced by iexamine::cvdmachine().
material_mc_steel
const material_id material_mc_steel("mc_steel") ("mc_steel") static
Referenced by iexamine::cvdmachine().
material_qt_steel
const material_id material_qt_steel("qt_steel") ("qt_steel") static
Referenced by iexamine::cvdmachine().
material_steel
const material_id material_steel("steel") ("steel") static
Referenced by iexamine::cvdmachine().
material_wood
const material_id material_wood("wood") ("wood") static
Referenced by iexamine::kiln_empty().
milling_time
const time_duration milling_time = 6_hours static
Definition at line 301 of file iexamine.cpp.
Referenced by mill_activate(), and iexamine::quern_examine().
mon_broken_cyborg
const mtype_id mon_broken_cyborg("mon_broken_cyborg") ("mon_broken_cyborg") static
Referenced by cyborg_on_couch().
mon_dark_wyrm
const mtype_id mon_dark_wyrm("mon_dark_wyrm") ("mon_dark_wyrm") static
Referenced by iexamine::pedestal_wyrm().
mon_fungal_blossom
const mtype_id mon_fungal_blossom("mon_fungal_blossom") ("mon_fungal_blossom") static
Referenced by iexamine::harvest_plant().
mon_prototype_cyborg
const mtype_id mon_prototype_cyborg("mon_prototype_cyborg") ("mon_prototype_cyborg") static
Referenced by cyborg_on_couch().
NC_ROBOFAC_INTERCOM
const npc_class_id NC_ROBOFAC_INTERCOM("NC_ROBOFAC_INTERCOM") ("NC_ROBOFAC_INTERCOM") static
Referenced by iexamine::intercom().
proficiency_prof_disarming
const proficiency_id proficiency_prof_disarming("prof_disarming") ("prof_disarming") static
Referenced by trap::examine().
proficiency_prof_parkour
const proficiency_id proficiency_prof_parkour("prof_parkour") ("prof_parkour") static
Referenced by iexamine::chainfence().
proficiency_prof_traps
const proficiency_id proficiency_prof_traps("prof_traps") ("prof_traps") static
Referenced by trap::examine().
proficiency_prof_trapsetting
const proficiency_id proficiency_prof_trapsetting("prof_trapsetting") ("prof_trapsetting") static
Referenced by trap::examine().
qual_ANESTHESIA
const quality_id qual_ANESTHESIA("ANESTHESIA") ("ANESTHESIA") static
Referenced by iexamine::autodoc().
qual_DIG
const quality_id qual_DIG("DIG") ("DIG") static
Referenced by iexamine::flower_dahlia(), iexamine::rubble(), and iexamine::tree_hickory().
qual_DRILL
const quality_id qual_DRILL("DRILL") ("DRILL") static
Referenced by iexamine::tree_maple().
qual_GRASS_CUT
const quality_id qual_GRASS_CUT("GRASS_CUT") ("GRASS_CUT") static
Referenced by iexamine::harvest_plant().
qual_HACK
const quality_id qual_HACK("HACK") ("HACK") static
Referenced by iexamine::can_hack(), and iexamine::try_start_hacking().
qual_HAMMER
const quality_id qual_HAMMER("HAMMER") ("HAMMER") static
Referenced by iexamine::tree_maple(), and iexamine::tree_maple_tapped().
qual_LOCKPICK
const quality_id qual_LOCKPICK("LOCKPICK") ("LOCKPICK") static
Referenced by iexamine::locked_object().
qual_PRY
const quality_id qual_PRY("PRY") ("PRY") static
Referenced by iexamine::locked_object().
qual_TREE_TAP
const quality_id qual_TREE_TAP("TREE_TAP") ("TREE_TAP") static
Referenced by iexamine::tree_maple(), and iexamine::tree_maple_tapped().
requirement_data_anesthetic
const requirement_id requirement_data_anesthetic("anesthetic") ("anesthetic") static
Referenced by iexamine::autodoc().
requirement_data_autoclave
const requirement_id requirement_data_autoclave("autoclave") ("autoclave") static
Referenced by iexamine::autoclave_empty().
requirement_data_cvd_diamond
const requirement_id requirement_data_cvd_diamond("cvd_diamond") ("cvd_diamond") static
Referenced by iexamine::cvdmachine().
skill_chemistry
const skill_id skill_chemistry("chemistry") ("chemistry") static
Referenced by iexamine::compost_full().
skill_cooking
const skill_id skill_cooking("cooking") ("cooking") static
Referenced by iexamine::fvat_full().
skill_fabrication
const skill_id skill_fabrication("fabrication") ("fabrication") static
Referenced by iexamine::arcfurnace_empty(), and iexamine::kiln_empty().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by iexamine::harvest_plant(), pick_plant(), iexamine::practice_survival_while_foraging(), iexamine::shrub_wildveggies(), and iexamine::tree_hickory().
skill_traps
const skill_id skill_traps("traps") ("traps") static
Referenced by trap::examine().
ter_t_card_reader_broken
const ter_str_id ter_t_card_reader_broken("t_card_reader_broken") ("t_card_reader_broken") static
Referenced by iexamine::cardreader_robofac().
ter_t_diesel_pump
const ter_str_id ter_t_diesel_pump("t_diesel_pump") ("t_diesel_pump") static
Referenced by iexamine::getGasPumpByNumber(), getNearPumpCount(), and turnOnSelectedPump().
ter_t_diesel_pump_a
const ter_str_id ter_t_diesel_pump_a("t_diesel_pump_a") ("t_diesel_pump_a") static
Referenced by iexamine::getGasPumpByNumber(), getNearPumpCount(), and turnOnSelectedPump().
ter_t_dirt
const ter_str_id ter_t_dirt("t_dirt") ("t_dirt") static
Referenced by iexamine::pedestal_temple().
ter_t_door_metal_c
const ter_str_id ter_t_door_metal_c("t_door_metal_c") ("t_door_metal_c") static
Referenced by iexamine::cardreader_foodplace().
ter_t_door_metal_locked
const ter_str_id ter_t_door_metal_locked("t_door_metal_locked") ("t_door_metal_locked") static
Referenced by iexamine::cardreader_foodplace().
ter_t_door_metal_o
const ter_str_id ter_t_door_metal_o("t_door_metal_o") ("t_door_metal_o") static
Referenced by iexamine::cardreader_foodplace().
ter_t_floor_blue
const ter_str_id ter_t_floor_blue("t_floor_blue") ("t_floor_blue") static
Referenced by iexamine::fswitch().
ter_t_floor_green
const ter_str_id ter_t_floor_green("t_floor_green") ("t_floor_green") static
Referenced by iexamine::fswitch().
ter_t_floor_red
const ter_str_id ter_t_floor_red("t_floor_red") ("t_floor_red") static
Referenced by iexamine::fswitch().
ter_t_fungus
const ter_str_id ter_t_fungus("t_fungus") ("t_fungus") static
Referenced by iexamine::shrub_marloss().
ter_t_gas_pump
const ter_str_id ter_t_gas_pump("t_gas_pump") ("t_gas_pump") static
Referenced by iexamine::getGasPumpByNumber(), getNearPumpCount(), and turnOnSelectedPump().
ter_t_gas_pump_a
const ter_str_id ter_t_gas_pump_a("t_gas_pump_a") ("t_gas_pump_a") static
Referenced by iexamine::getGasPumpByNumber(), getNearPumpCount(), and turnOnSelectedPump().
ter_t_marloss
const ter_str_id ter_t_marloss("t_marloss") ("t_marloss") static
Referenced by iexamine::harvest_plant().
ter_t_marloss_tree
const ter_str_id ter_t_marloss_tree("t_marloss_tree") ("t_marloss_tree") static
Referenced by iexamine::tree_marloss().
ter_t_orifice
const ter_str_id ter_t_orifice("t_orifice") ("t_orifice") static
Referenced by iexamine::pedestal_wyrm().
ter_t_pit
const ter_str_id ter_t_pit("t_pit") ("t_pit") static
Referenced by iexamine::pit(), and iexamine::pit_covered().
ter_t_pit_covered
const ter_str_id ter_t_pit_covered("t_pit_covered") ("t_pit_covered") static
Referenced by iexamine::pit(), and iexamine::pit_covered().
ter_t_pit_glass
const ter_str_id ter_t_pit_glass("t_pit_glass") ("t_pit_glass") static
Referenced by iexamine::pit(), and iexamine::pit_covered().
ter_t_pit_glass_covered
const ter_str_id ter_t_pit_glass_covered("t_pit_glass_covered") ("t_pit_glass_covered") static
Referenced by iexamine::pit(), and iexamine::pit_covered().
ter_t_pit_spiked
const ter_str_id ter_t_pit_spiked("t_pit_spiked") ("t_pit_spiked") static
Referenced by iexamine::pit(), and iexamine::pit_covered().
ter_t_pit_spiked_covered
const ter_str_id ter_t_pit_spiked_covered("t_pit_spiked_covered") ("t_pit_spiked_covered") static
Referenced by iexamine::pit(), and iexamine::pit_covered().
ter_t_rock_blue
const ter_str_id ter_t_rock_blue("t_rock_blue") ("t_rock_blue") static
Referenced by iexamine::fswitch().
ter_t_rock_floor
const ter_str_id ter_t_rock_floor("t_rock_floor") ("t_rock_floor") static
Referenced by iexamine::pedestal_wyrm().
ter_t_rock_green
const ter_str_id ter_t_rock_green("t_rock_green") ("t_rock_green") static
Referenced by iexamine::fswitch().
ter_t_rock_red
const ter_str_id ter_t_rock_red("t_rock_red") ("t_rock_red") static
Referenced by iexamine::fswitch().
ter_t_shrub_fungal
const ter_str_id ter_t_shrub_fungal("t_shrub_fungal") ("t_shrub_fungal") static
Referenced by iexamine::shrub_marloss().
ter_t_switch_even
const ter_str_id ter_t_switch_even("t_switch_even") ("t_switch_even") static
Referenced by iexamine::fswitch().
ter_t_switch_gb
const ter_str_id ter_t_switch_gb("t_switch_gb") ("t_switch_gb") static
Referenced by iexamine::fswitch().
ter_t_switch_rb
const ter_str_id ter_t_switch_rb("t_switch_rb") ("t_switch_rb") static
Referenced by iexamine::fswitch().
ter_t_switch_rg
const ter_str_id ter_t_switch_rg("t_switch_rg") ("t_switch_rg") static
Referenced by iexamine::fswitch().
ter_t_tree_fungal
const ter_str_id ter_t_tree_fungal("t_tree_fungal") ("t_tree_fungal") static
Referenced by iexamine::tree_marloss().
ter_t_tree_hickory_dead
const ter_str_id ter_t_tree_hickory_dead("t_tree_hickory_dead") ("t_tree_hickory_dead") static
Referenced by iexamine::tree_hickory().
ter_t_tree_maple
const ter_str_id ter_t_tree_maple("t_tree_maple") ("t_tree_maple") static
Referenced by iexamine::tree_maple_tapped().
ter_t_tree_maple_tapped
const ter_str_id ter_t_tree_maple_tapped("t_tree_maple_tapped") ("t_tree_maple_tapped") static
Referenced by iexamine::tree_maple().
trait_AMORPHOUS
const trait_id trait_AMORPHOUS("AMORPHOUS") ("AMORPHOUS") static
Referenced by iexamine::bars().
trait_ARACHNID_ARMS_OK
const trait_id trait_ARACHNID_ARMS_OK("ARACHNID_ARMS_OK") ("ARACHNID_ARMS_OK") static
Referenced by iexamine::chainfence().
trait_BADKNEES
const trait_id trait_BADKNEES("BADKNEES") ("BADKNEES") static
Referenced by iexamine::chainfence().
trait_BEAK_HUM
const trait_id trait_BEAK_HUM("BEAK_HUM") ("BEAK_HUM") static
Referenced by can_drink_nectar().
trait_BURROW
const trait_id trait_BURROW("BURROW") ("BURROW") static
Referenced by iexamine::flower_dahlia(), and iexamine::rubble().
trait_BURROWLARGE
const trait_id trait_BURROWLARGE("BURROWLARGE") ("BURROWLARGE") static
Referenced by iexamine::flower_dahlia(), and iexamine::rubble().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by iexamine::part_con().
trait_ILLITERATE
const trait_id trait_ILLITERATE("ILLITERATE") ("ILLITERATE") static
Referenced by iexamine::can_hack(), iexamine::pay_gas(), iexamine::sign(), and str_to_illiterate_str().
trait_INSECT_ARMS_OK
const trait_id trait_INSECT_ARMS_OK("INSECT_ARMS_OK") ("INSECT_ARMS_OK") static
Referenced by iexamine::chainfence().
trait_M_DEFENDER
const trait_id trait_M_DEFENDER("M_DEFENDER") ("M_DEFENDER") static
Referenced by iexamine::harvest_plant().
trait_M_DEPENDENT
const trait_id trait_M_DEPENDENT("M_DEPENDENT") ("M_DEPENDENT") static
Referenced by iexamine::harvest_plant(), and iexamine::tree_marloss().
trait_M_FERTILE
const trait_id trait_M_FERTILE("M_FERTILE") ("M_FERTILE") static
Referenced by iexamine::harvest_plant().
trait_M_SPORES
const trait_id trait_M_SPORES("M_SPORES") ("M_SPORES") static
Referenced by iexamine::harvest_plant().
trait_PROBOSCIS
const trait_id trait_PROBOSCIS("PROBOSCIS") ("PROBOSCIS") static
Referenced by can_drink_nectar().
trait_PYROMANIA
const trait_id trait_PYROMANIA("PYROMANIA") ("PYROMANIA") static
Referenced by iexamine::kiln_empty(), and smoker_activate().
trait_SHELL2
const trait_id trait_SHELL2("SHELL2") ("SHELL2") static
Referenced by iexamine::workbench_internal().
trait_SHELL3
const trait_id trait_SHELL3("SHELL3") ("SHELL3") static
Referenced by iexamine::workbench_internal().
trait_THRESH_MARLOSS
const trait_id trait_THRESH_MARLOSS("THRESH_MARLOSS") ("THRESH_MARLOSS") static
Referenced by iexamine::shrub_marloss(), and iexamine::tree_marloss().
trait_THRESH_MYCUS
const trait_id trait_THRESH_MYCUS("THRESH_MYCUS") ("THRESH_MYCUS") static
Referenced by iexamine::harvest_plant(), iexamine::shrub_marloss(), and iexamine::tree_marloss().