Cataclysm DDA: src/iexamine.h File Reference
iexamine.h File Reference
#include <iosfwd>
#include <list>
#include <memory>
#include <optional>
#include <set>
#include <tuple>
#include <vector>
#include "ret_val.h"
#include "type_id.h"
Classes
struct iexamine_actor
struct iexamine_functions
Namespaces
iexamine
iexamine_helper
Macros
#define CATA_SRC_IEXAMINE_H
Typedefs
using seed_tuple = std::tuple< itype_id, std::string, int >
using iexamine_examine_function = void(*)(Character &, const tripoint &)
using iexamine_can_examine_function = bool(*)(const tripoint &)
Enumerations
enum fuel_station_fuel_type { FUEL_TYPE_NONE , FUEL_TYPE_GASOLINE , FUEL_TYPE_DIESEL }
Functions
bool iexamine::can_hack (Character &you)
bool iexamine::try_start_hacking (Character &you, const tripoint &examp)
void iexamine::egg_sack_generic (Character &you, const tripoint &examp, const mtype_id &montype)
void iexamine::none (Character &you, const tripoint &examp)
Nothing player can interact with here.
bool iexamine::always_false (const tripoint &examp)
bool iexamine::false_and_debugmsg (const tripoint &examp)
bool iexamine::always_true (const tripoint &examp)
bool iexamine::harvestable_now (const tripoint &examp)
void iexamine::gaspump (Character &you, const tripoint &examp)
Use "gas pump.".
void iexamine::atm (Character &you, const tripoint &examp)
launches the atm menu class which then handles all the atm interactions.
void iexamine::vending (Character &you, const tripoint &examp)
Generates vending machine UI and allows players to purchase contained items with a cash card.
void iexamine::elevator (Character &you, const tripoint &examp)
void iexamine::nanofab (Character &you, const tripoint &examp)
TEMPLATE FABRICATORS Generate items from found blueprints.
void iexamine::controls_gate (Character &you, const tripoint &examp)
Open gate.
void iexamine::cardreader (Character &you, const tripoint &examp)
void iexamine::cardreader_robofac (Character &you, const tripoint &examp)
void iexamine::cardreader_foodplace (Character &you, const tripoint &examp)
void iexamine::intercom (Character &you, const tripoint &examp)
void iexamine::cvdmachine (Character &you, const tripoint &examp)
Pick an appropriate item and apply diamond coating if possible.
void iexamine::change_appearance (Character &you, const tripoint &examp)
Change player eye and skin color.
void iexamine::rubble (Character &you, const tripoint &examp)
Prompt removal of rubble.
void iexamine::chainfence (Character &you, const tripoint &examp)
Prompt climbing over fence.
void iexamine::bars (Character &you, const tripoint &examp)
If player has amorphous trait, slip through the bars.
void iexamine::deployed_furniture (Character &you, const tripoint &pos)
void iexamine::portable_structure (Character &you, const tripoint &examp)
Determine structure's type and prompts its removal.
void iexamine::pit (Character &you, const tripoint &examp)
If there is a 2x4 around, prompt placing it across pit.
void iexamine::pit_covered (Character &you, const tripoint &examp)
Prompt removing the 2x4 placed across the pit.
void iexamine::safe (Character &you, const tripoint &examp)
Attempt to crack safe through audio-feedback manual lock manipulation.
void iexamine::gunsafe_el (Character &you, const tripoint &examp)
Attempt to "hack" the gunsafe's electronic lock and open it.
void iexamine::harvest_furn_nectar (Character &you, const tripoint &examp)
void iexamine::harvest_furn (Character &you, const tripoint &examp)
void iexamine::harvest_ter_nectar (Character &you, const tripoint &examp)
void iexamine::harvest_ter (Character &you, const tripoint &examp)
void iexamine::harvested_plant (Character &you, const tripoint &examp)
Only harvest a plant once per season.
void iexamine::locked_object (Character &you, const tripoint &examp)
Checks whether PC has a crowbar then calls iuse.crowbar.
void iexamine::locked_object_pickable (Character &you, const tripoint &examp)
Checks whether PC has picklocks then calls pick_lock iuse function OR assigns ACT_LOCKPICK.
void iexamine::bulletin_board (Character &you, const tripoint &examp)
void iexamine::pedestal_wyrm (Character &you, const tripoint &examp)
Spawn 1d4 wyrms and sink pedestal into ground.
void iexamine::pedestal_temple (Character &you, const tripoint &examp)
Put petrified eye on pedestal causing it to sink into ground and open temple.
void iexamine::door_peephole (Character &you, const tripoint &examp)
Unlock/open door or attempt to peek through peephole.
void iexamine::fswitch (Character &you, const tripoint &examp)
void iexamine::flower_tulip (Character &you, const tripoint &examp)
void iexamine::flower_spurge (Character &you, const tripoint &examp)
void iexamine::flower_poppy (Character &you, const tripoint &examp)
Prompt pick (or drink nectar if able) poppy bud.
void iexamine::flower_cactus (Character &you, const tripoint &examp)
Prompt pick cactus pad.
void iexamine::flower_bluebell (Character &you, const tripoint &examp)
void iexamine::flower_dahlia (Character &you, const tripoint &examp)
Dig up its roots or drink its nectar if you can.
void iexamine::flower_marloss (Character &you, const tripoint &examp)
void iexamine::fungus (Character &you, const tripoint &examp)
Remove furniture.
void iexamine::dirtmound (Character &you, const tripoint &examp)
If it's warm enough, pick one of the player's seeds and plant it.
void iexamine::aggie_plant (Character &you, const tripoint &examp)
void iexamine::tree_hickory (Character &you, const tripoint &examp)
void iexamine::tree_maple (Character &you, const tripoint &examp)
void iexamine::tree_maple_tapped (Character &you, const tripoint &examp)
void iexamine::shrub_marloss (Character &you, const tripoint &examp)
void iexamine::tree_marloss (Character &you, const tripoint &examp)
void iexamine::shrub_wildveggies (Character &you, const tripoint &examp)
void iexamine::part_con (Character &you, const tripoint &examp)
void iexamine::water_source (Character &, const tripoint &examp)
void iexamine::finite_water_source (Character &, const tripoint &examp)
void iexamine::kiln_empty (Character &you, const tripoint &examp)
void iexamine::kiln_full (Character &you, const tripoint &examp)
void iexamine::stook_empty (Character &, const tripoint &examp)
void iexamine::stook_full (Character &, const tripoint &examp)
void iexamine::arcfurnace_empty (Character &you, const tripoint &examp)
void iexamine::arcfurnace_full (Character &you, const tripoint &examp)
void iexamine::autoclave_empty (Character &you, const tripoint &examp)
void iexamine::autoclave_full (Character &, const tripoint &examp)
void iexamine::fireplace (Character &you, const tripoint &examp)
void iexamine::fvat_empty (Character &you, const tripoint &examp)
void iexamine::fvat_full (Character &you, const tripoint &examp)
void iexamine::compost_empty (Character &you, const tripoint &examp)
void iexamine::compost_full (Character &you, const tripoint &examp)
void iexamine::keg (Character &you, const tripoint &examp)
void iexamine::reload_furniture (Character &you, const tripoint &examp)
void iexamine::curtains (Character &you, const tripoint &examp)
void iexamine::sign (Character &you, const tripoint &examp)
void iexamine::pay_gas (Character &you, const tripoint &examp)
void iexamine::ledge (Character &you, const tripoint &examp)
void iexamine::autodoc (Character &you, const tripoint &examp)
void iexamine::attunement_altar (Character &you, const tripoint &examp)
void iexamine::translocator (Character &you, const tripoint &examp)
void iexamine::on_smoke_out (const tripoint &examp, const time_point &start_time)
void iexamine::mill_finalize (Character &, const tripoint &examp)
void iexamine::quern_examine (Character &you, const tripoint &examp)
void iexamine::smoker_options (Character &you, const tripoint &examp)
void iexamine::open_safe (Character &you, const tripoint &examp)
void iexamine::workbench (Character &you, const tripoint &examp)
void iexamine::workbench_internal (Character &you, const tripoint &examp, const std::optional< vpart_reference > &part)
void iexamine::workout (Character &you, const tripoint &examp)
void iexamine::invalid (Character &you, const tripoint &examp)
bool iexamine::pour_into_keg (const tripoint &pos, item &liquid)
Pour liquid into a keg (furniture) on the map.
std::optional< tripoint > iexamine::getGasPumpByNumber (const tripoint &p, int number)
bool iexamine::toPumpFuel (const tripoint &src, const tripoint &dst, int units)
std::optional< tripoint > iexamine::getNearFilledGasTank (const tripoint &center, int &fuel_units, fuel_station_fuel_type &fuel_type)
bool iexamine::has_keg (const tripoint &pos)
Check whether there is a keg on the map that can be filled via pour_into_keg.
std::list< item > iexamine::get_harvest_items (const itype &type, int plant_count, int seed_count, bool byproducts)
Items that appear when a generic plant is harvested.
std::vector< seed_tuple > iexamine::get_seed_entries (const std::vector< item * > &seed_inv)
Make lists of unique seed types and names for the menu(no multiple hemp seeds etc)
int iexamine::query_seed (const std::vector< seed_tuple > &seed_entries)
Choose seed for planting.
void iexamine::plant_seed (Character &you, const tripoint &examp, const itype_id &seed_id)
Actual planting of selected seed.
void iexamine::clear_overgrown (Character &you, const tripoint &examp)
void iexamine::harvest_plant_ex (Character &you, const tripoint &examp)
void iexamine::harvest_plant (Character &you, const tripoint &examp, bool from_activity)
Actual harvesting of selected plant.
void iexamine::fertilize_plant (Character &you, const tripoint &tile, const itype_id &fertilizer)
itype_id iexamine::choose_fertilizer (Character &you, const std::string &pname, bool ask_player)
ret_val< void > iexamine::can_fertilize (Character &you, const tripoint &tile, const itype_id &fertilizer)
void iexamine::practice_survival_while_foraging (Character &who)
bool iexamine_helper::drink_nectar (Character &you)
Consume Nectar.
void iexamine_helper::handle_harvest (Character &you, const std::string &itemid, bool force_drop)
Spawn an item after harvesting the plant.
iexamine_functions iexamine_functions_from_string (const std::string &function_name)
Given then name of one of the above functions, returns the matching function pointer.
Macro Definition Documentation
CATA_SRC_IEXAMINE_H
#define CATA_SRC_IEXAMINE_H
Definition at line 3 of file iexamine.h.
Typedef Documentation
iexamine_can_examine_function
using iexamine_can_examine_function = bool (*)(const tripoint &)
Definition at line 182 of file iexamine.h.
iexamine_examine_function
using iexamine_examine_function = void (*)(Character &, const tripoint &)
Definition at line 181 of file iexamine.h.
seed_tuple
using seed_tuple = std::tuple<itype_id, std::string, int>
Definition at line 24 of file iexamine.h.
Enumeration Type Documentation
fuel_station_fuel_type
enum fuel_station_fuel_type
Enumerator
FUEL_TYPE_NONE
FUEL_TYPE_GASOLINE
FUEL_TYPE_DIESEL
Definition at line 40 of file iexamine.h.
{
     FUEL_TYPE_NONE,
     FUEL_TYPE_GASOLINE,
     FUEL_TYPE_DIESEL
 };
Function Documentation
iexamine_functions_from_string()
iexamine_functions iexamine_functions_from_string (const std::string & function_name)
Given then name of one of the above functions, returns the matching function pointer.
If no match is found, defaults to iexamine::none but prints out a debug message as a warning.
Parameters
function_name The name of the function to get.
Returns
A function pointer to the specified function.
Definition at line 7334 of file iexamine.cpp.
 {
     static const std::map<std::string, iexamine_examine_function> function_map = {{
             { "none", &iexamine::none },
             { "attunement_altar", &iexamine::attunement_altar },
             { "deployed_furniture", &iexamine::deployed_furniture },
             { "cvdmachine", &iexamine::cvdmachine },
             { "change_appearance", &iexamine::change_appearance },
             { "nanofab", &iexamine::nanofab },
             { "gaspump", &iexamine::gaspump },
             { "atm", &iexamine::atm },
             { "vending", &iexamine::vending },
             { "elevator", &iexamine::elevator },
             { "controls_gate", &iexamine::controls_gate },
             { "cardreader_robofac", &iexamine::cardreader_robofac },
             { "cardreader_fp", &iexamine::cardreader_foodplace },
             { "intercom", &iexamine::intercom },
             { "rubble", &iexamine::rubble },
             { "chainfence", &iexamine::chainfence },
             { "bars", &iexamine::bars },
             { "portable_structure", &iexamine::portable_structure },
             { "pit", &iexamine::pit },
             { "pit_covered", &iexamine::pit_covered },
             { "safe", &iexamine::safe },
             { "bulletin_board", &iexamine::bulletin_board },
             { "pedestal_wyrm", &iexamine::pedestal_wyrm },
             { "pedestal_temple", &iexamine::pedestal_temple },
             { "door_peephole", &iexamine::door_peephole },
             { "fswitch", &iexamine::fswitch },
             { "flower_poppy", &iexamine::flower_poppy },
             { "flower_cactus", &iexamine::flower_cactus },
             { "fungus", &iexamine::fungus },
             { "flower_dahlia", &iexamine::flower_dahlia },
             { "flower_marloss", &iexamine::flower_marloss },
             { "dirtmound", &iexamine::dirtmound },
             { "aggie_plant", &iexamine::aggie_plant },
             { "fvat_empty", &iexamine::fvat_empty },
             { "fvat_full", &iexamine::fvat_full },
             { "compost_empty", &iexamine::compost_empty },
             { "compost_full", &iexamine::compost_full },
             { "keg", &iexamine::keg },
             { "harvest_furn_nectar", &iexamine::harvest_furn_nectar },
             { "harvest_furn", &iexamine::harvest_furn },
             { "harvest_ter_nectar", &iexamine::harvest_ter_nectar },
             { "harvest_ter", &iexamine::harvest_ter },
             { "clear_overgrown", &iexamine::clear_overgrown },
             { "harvest_plant_ex", &iexamine::harvest_plant_ex },
             { "harvested_plant", &iexamine::harvested_plant },
             { "shrub_marloss", &iexamine::shrub_marloss },
             { "translocator", &iexamine::translocator },
             { "tree_marloss", &iexamine::tree_marloss },
             { "tree_hickory", &iexamine::tree_hickory },
             { "tree_maple", &iexamine::tree_maple },
             { "tree_maple_tapped", &iexamine::tree_maple_tapped },
             { "shrub_wildveggies", &iexamine::shrub_wildveggies },
             { "water_source", &iexamine::water_source },
             { "finite_water_source", &iexamine::finite_water_source },
             { "reload_furniture", &iexamine::reload_furniture },
             { "curtains", &iexamine::curtains },
             { "sign", &iexamine::sign },
             { "pay_gas", &iexamine::pay_gas },
             { "gunsafe_el", &iexamine::gunsafe_el },
             { "locked_object", &iexamine::locked_object },
             { "locked_object_pickable", &iexamine::locked_object_pickable },
             { "kiln_empty", &iexamine::kiln_empty },
             { "kiln_full", &iexamine::kiln_full },
             { "stook_empty", &iexamine::stook_empty },
             { "stook_full", &iexamine::stook_full },
             { "arcfurnace_empty", &iexamine::arcfurnace_empty },
             { "arcfurnace_full", &iexamine::arcfurnace_full },
             { "autoclave_empty", &iexamine::autoclave_empty },
             { "autoclave_full", &iexamine::autoclave_full },
             { "fireplace", &iexamine::fireplace },
             { "ledge", &iexamine::ledge },
             { "autodoc", &iexamine::autodoc },
             { "quern_examine", &iexamine::quern_examine },
             { "smoker_options", &iexamine::smoker_options },
             { "open_safe", &iexamine::open_safe },
             { "workbench", &iexamine::workbench },
             { "workout", &iexamine::workout },
             { "invalid", &iexamine::invalid },
         }
     };
     static const std::set<std::string> harvestable_functions = {
         "harvest_furn_nectar",
         "harvest_furn",
         "harvest_ter_nectar",
         "harvest_ter",
         "harvest_plant",
     };
     auto iter = function_map.find( function_name );
     if( iter != function_map.end() ) {
         iexamine_examine_function func = iter->second;
         if( function_name == "none" ) {
             return iexamine_functions{&iexamine::always_false, func};
         } else if( function_name == "invalid" ) {
             return iexamine_functions{&iexamine::false_and_debugmsg, func};
         } else if( harvestable_functions.find( function_name ) != harvestable_functions.end() ) {
             return iexamine_functions{&iexamine::harvestable_now, func};
         } else {
             return iexamine_functions{&iexamine::always_true, func};
         }
     }
     //No match found
     debugmsg( "Could not find an iexamine function matching '%s'!", function_name );
     return iexamine_functions{&iexamine::always_false, &iexamine::none};
 }
References iexamine::aggie_plant(), iexamine::always_false(), iexamine::always_true(), iexamine::arcfurnace_empty(), iexamine::arcfurnace_full(), iexamine::atm(), iexamine::attunement_altar(), iexamine::autoclave_empty(), iexamine::autoclave_full(), iexamine::autodoc(), iexamine::bars(), iexamine::bulletin_board(), iexamine::cardreader_foodplace(), iexamine::cardreader_robofac(), iexamine::chainfence(), iexamine::change_appearance(), iexamine::clear_overgrown(), iexamine::compost_empty(), iexamine::compost_full(), iexamine::controls_gate(), iexamine::curtains(), iexamine::cvdmachine(), debugmsg, iexamine::deployed_furniture(), iexamine::dirtmound(), iexamine::door_peephole(), iexamine::elevator(), iexamine::false_and_debugmsg(), iexamine::finite_water_source(), iexamine::fireplace(), iexamine::flower_cactus(), iexamine::flower_dahlia(), iexamine::flower_marloss(), iexamine::flower_poppy(), iexamine::fswitch(), iexamine::fungus(), iexamine::fvat_empty(), iexamine::fvat_full(), iexamine::gaspump(), iexamine::gunsafe_el(), iexamine::harvest_furn(), iexamine::harvest_furn_nectar(), iexamine::harvest_plant_ex(), iexamine::harvest_ter(), iexamine::harvest_ter_nectar(), iexamine::harvestable_now(), iexamine::harvested_plant(), iexamine::intercom(), iexamine::invalid(), iexamine::keg(), iexamine::kiln_empty(), iexamine::kiln_full(), iexamine::ledge(), iexamine::locked_object(), iexamine::locked_object_pickable(), iexamine::nanofab(), iexamine::none(), iexamine::open_safe(), iexamine::pay_gas(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), iexamine::pit(), iexamine::pit_covered(), iexamine::portable_structure(), iexamine::quern_examine(), iexamine::reload_furniture(), iexamine::rubble(), iexamine::safe(), iexamine::shrub_marloss(), iexamine::shrub_wildveggies(), iexamine::sign(), iexamine::smoker_options(), iexamine::stook_empty(), iexamine::stook_full(), iexamine::translocator(), iexamine::tree_hickory(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), iexamine::tree_marloss(), iexamine::vending(), iexamine::water_source(), iexamine::workbench(), and iexamine::workout().
Referenced by map_data_common_t::load().