Cataclysm DDA: src/input_context.cpp File Reference
input_context.cpp File Reference
#include "input_context.h"
#include <algorithm>
#include <array>
#include <cctype>
#include <cstddef>
#include <exception>
#include <iterator>
#include <memory>
#include <optional>
#include <set>
#include <utility>
#include "action.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "color.h"
#include "coordinates.h"
#include "cuboid_rectangle.h"
#include "cursesdef.h"
#include "game.h"
#include "help.h"
#include "input.h"
#include "map.h"
#include "options.h"
#include "output.h"
#include "point.h"
#include "popup.h"
#include "sdltiles.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "ui_manager.h"
#include "cata_imgui.h"
#include "imgui/imgui.h"
Classes
class keybindings_ui
struct ContainsPredicate< T1, T2 >
Namespaces
anonymous_namespace{input_context.cpp}
Enumerations
enum class kb_menu_status {
remove , reset , add , add_global ,
execute , show , filter
}
enum class anonymous_namespace{input_context.cpp}::fallback_action {
anonymous_namespace{input_context.cpp}::add_local , anonymous_namespace{input_context.cpp}::add_global , anonymous_namespace{input_context.cpp}::remove , anonymous_namespace{input_context.cpp}::reset ,
anonymous_namespace{input_context.cpp}::execute
}
Functions
static const std::string default_context_id ("default")
static void rotate_direction_cw (int &dx, int &dy)
bool gamepad_available ()
Check whether a gamepad is plugged in/available.
Variables
static const std::string CATA_ERROR = "ERROR"
static const std::string ANY_INPUT = "ANY_INPUT"
static const std::string HELP_KEYBINDINGS = "HELP_KEYBINDINGS"
static const std::string COORDINATE = "COORDINATE"
static const std::string TIMEOUT = "TIMEOUT"
static const std::string display_help_hotkeys
static const std::map< fallback_action, int > fallback_keys
Enumeration Type Documentation
kb_menu_status
enum kb_menu_status strong
Enumerator
remove
reset
add
add_global
execute
show
filter
Definition at line 37 of file input_context.cpp.
{
     remove, reset, add, add_global, execute, show, filter
 };
Function Documentation
default_context_id()
static const std::string default_context_id ("default") static
Referenced by input_context::action_add(), input_context::action_remove(), input_context::action_reset(), input_context::clear_conflicting_keybindings(), and input_context::get_action_name().
gamepad_available()
bool gamepad_available ()
Check whether a gamepad is plugged in/available.
Always false in non-SDL versions.
Definition at line 1139 of file input_context.cpp.
 {
     return false;
 }
Referenced by input_context::is_event_type_enabled().
rotate_direction_cw()
static void rotate_direction_cw (int & dx, int & dy) static
Definition at line 533 of file input_context.cpp.
 {
     // convert to
     // 0 1 2
     // 3 4 5
     // 6 7 8
     int dir_num = ( dy + 1 ) * 3 + dx + 1;
     // rotate to
     // 1 2 5
     // 0 4 8
     // 3 6 7
     static const std::array<int, 9> rotate_direction_vec = {{ 1, 2, 5, 0, 4, 8, 3, 6, 7 }};
     dir_num = rotate_direction_vec[dir_num];
     // convert back to -1,0,+1
     dx = dir_num % 3 - 1;
     dy = dir_num / 3 - 1;
 }
Referenced by input_context::get_direction(), and input_context::get_direction_rel_ms().
Variable Documentation
ANY_INPUT
const std::string ANY_INPUT = "ANY_INPUT" static
Definition at line 133 of file input_context.cpp.
Referenced by input_context::handle_input().
CATA_ERROR
const std::string CATA_ERROR = "ERROR" static
Definition at line 132 of file input_context.cpp.
Referenced by input_context::first_unassigned_hotkey(), input_context::handle_input(), input_context::input_to_action(), and input_context::next_unassigned_hotkey().
COORDINATE
const std::string COORDINATE = "COORDINATE" static
Definition at line 135 of file input_context.cpp.
display_help_hotkeys
const std::string display_help_hotkeys static
Initial value:
=
    "abcdefghijkpqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789:;'\",/<>?!@#$%^&*()_[]\\{}|`~"
Definition at line 621 of file input_context.cpp.
Referenced by input_context::display_menu().
fallback_keys
const std::map<fallback_action, int> fallback_keys static
Initial value:
= {
    { fallback_action::add_local, '+' },
    { fallback_action::add_global, '=' },
    { fallback_action::remove, '-' },
    { fallback_action::reset, '*' },
    { fallback_action::execute, '.' },
}
Definition at line 634 of file input_context.cpp.
Referenced by input_context::display_menu(), and keybindings_ui::keybindings_ui().
HELP_KEYBINDINGS
const std::string HELP_KEYBINDINGS = "HELP_KEYBINDINGS" static
Definition at line 134 of file input_context.cpp.
Referenced by input_context::handle_input().
TIMEOUT
const std::string TIMEOUT = "TIMEOUT" static
Definition at line 136 of file input_context.cpp.
Referenced by input_context::handle_input().