Cataclysm DDA: src/inventory_ui.h File Reference
inventory_ui.h File Reference
#include <array>
#include <climits>
#include <cstddef>
#include <functional>
#include <limits>
#include <list>
#include <memory>
#include <optional>
#include <string>
#include <utility>
#include <vector>
#include "color.h"
#include "cuboid_rectangle.h"
#include "cursesdef.h"
#include "debug.h"
#include "input_context.h"
#include "item_category.h"
#include "item_location.h"
#include "pocket_type.h"
#include "pimpl.h"
#include "translations.h"
#include "units_fwd.h"
Classes
struct collation_meta_t
class inventory_entry
struct inventory_entry::entry_cell_cache_t
class inventory_selector_preset
class inventory_selector_preset::cell_t
class inventory_holster_preset
class inventory_column
struct inventory_column::cell_t
class selection_column
class inventory_selector
struct enum_traits< inventory_selector::uimode >
class inventory_pick_selector
class container_inventory_selector
class ammo_inventory_selector
class inventory_multiselector
class inventory_haul_selector
class haul_selector_preset
class inventory_compare_selector
class inventory_drop_selector
class inventory_insert_selector
class pickup_selector
class unload_selector
class inventory_examiner
struct inventory_selector_save_state
Macros
#define CATA_SRC_INVENTORY_UI_H
#define EXAMINED_CONTENTS_UNCHANGED 0
Class for opening a container and quickly examining the items contained within.
#define EXAMINED_CONTENTS_WITH_CHANGES 1
#define NO_CONTENTS_TO_EXAMINE 2
Typedefs
using drop_location = std::pair< item_location, int >
using drop_locations = std::list< drop_location >
Enumerations
enum class navigation_mode : int { ITEM = 0 , CATEGORY }
enum class scroll_direction : int { FORWARD = 1 , BACKWARD = -1 }
enum class toggle_mode : int { SELECTED = 0 , NON_FAVORITE_NON_WORN }
Functions
inventory_selector::stat display_stat (const std::string &caption, int cur_value, int max_value, const std::function< std::string(int)> &disp_func)
std::vector< item_location > get_possible_reload_targets (const item_location &target)
bool is_worn_ablative (item_location const &container, item_location const &child)
Variables
const inventory_selector_preset default_preset
inventory_selector_save_state inventory_ui_default_state
inventory_selector_save_state pickup_sel_default_state
inventory_selector_save_state pickup_ui_default_state
Macro Definition Documentation
CATA_SRC_INVENTORY_UI_H
#define CATA_SRC_INVENTORY_UI_H
Definition at line 3 of file inventory_ui.h.
EXAMINED_CONTENTS_UNCHANGED
#define EXAMINED_CONTENTS_UNCHANGED 0
Class for opening a container and quickly examining the items contained within.
Class that lists inventory entries in a pane on the left, and shows the results of 'e'xamining the selected item on the right. To use, create it, add_contained_items(), then execute(). TODO: Ideally, add_contained_items could be done automatically on creation without duplicating that code from inventory_selector.
Definition at line 1079 of file inventory_ui.h.
EXAMINED_CONTENTS_WITH_CHANGES
#define EXAMINED_CONTENTS_WITH_CHANGES 1
Definition at line 1080 of file inventory_ui.h.
NO_CONTENTS_TO_EXAMINE
#define NO_CONTENTS_TO_EXAMINE 2
Definition at line 1081 of file inventory_ui.h.
Typedef Documentation
drop_location
using drop_location = std::pair<item_location, int>
Definition at line 56 of file inventory_ui.h.
drop_locations
using drop_locations = std::list<drop_location>
Definition at line 57 of file inventory_ui.h.
Enumeration Type Documentation
navigation_mode
enum navigation_mode : int strong
Enumerator
ITEM
CATEGORY
Definition at line 38 of file inventory_ui.h.
                            : int {
     ITEM = 0,
     CATEGORY
 };
scroll_direction
enum scroll_direction : int strong
Enumerator
FORWARD
BACKWARD
Definition at line 43 of file inventory_ui.h.
                             : int {
     FORWARD = 1,
     BACKWARD = -1
 };
toggle_mode
enum toggle_mode : int strong
Enumerator
SELECTED
NON_FAVORITE_NON_WORN
Definition at line 48 of file inventory_ui.h.
                        : int {
     SELECTED = 0,
     NON_FAVORITE_NON_WORN
 };
Function Documentation
display_stat()
inventory_selector::stat display_stat (const std::string & caption, int cur_value, int max_value, const std::function< std::string(int)> & disp_func)
Definition at line 2509 of file inventory_ui.cpp.
 {
     const nc_color color = cur_value > max_value ? c_red : c_light_gray;
     return {{
             caption,
             colorize( disp_func( cur_value ), color ), "/",
             colorize( disp_func( max_value ), c_light_gray )
         }};
 }
References c_light_gray, c_red, color(), and colorize().
Referenced by draw_stats_tab(), game_menus::inv::ebooksave(), basecamp::get_equipment(), inventory_selector::get_holster_stat(), inventory_selector::get_volume_stat(), inventory_selector::get_weight_and_length_stat(), basecamp::give_equipment(), game_menus::inv::smoke_food(), and iuse::wash_items().
get_possible_reload_targets()
std::vector<item_location> get_possible_reload_targets (const item_location & target)
Definition at line 3357 of file inventory_ui.cpp.
 {
     std::vector<item_location> opts;
     opts.emplace_back( target );
     if( target->magazine_current() ) {
         opts.emplace_back( target, const_cast<item *>( target->magazine_current() ) );
     }
     for( const item *mod : target->gunmods() ) {
         item_location mod_loc( target, const_cast<item *>( mod ) );
         opts.emplace_back( mod_loc );
         if( mod->magazine_current() ) {
             opts.emplace_back( mod_loc, const_cast<item *>( mod->magazine_current() ) );
         }
     }
     return opts;
 }
References item::gunmods(), and item::magazine_current().
Referenced by select_ammo_inventory_preset::is_shown(), ammo_inventory_selector::mod_chosen_count(), game_menus::inv::select_ammo(), select_ammo_inventory_preset::select_ammo_inventory_preset(), and ammo_inventory_selector::set_all_entries_chosen_count().
is_worn_ablative()
bool is_worn_ablative (item_location const & container, item_location const & child)
Definition at line 183 of file inventory_ui.cpp.
 {
     // if the item is in an ablative pocket then put it with the item it is in
     // first do a short circuit test if the parent has ablative pockets at all
     return container->is_ablative() && container->is_worn_by_player() &&
            child.parent_pocket()->get_pocket_data()->ablative;
 }
References pocket_data::ablative, item_pocket::get_pocket_data(), item::is_ablative(), item::is_worn_by_player(), and item_location::parent_pocket().
Referenced by inventory_selector::add_contained_items(), wear_inventory_preset::is_shown(), inventory_selector::toggle_categorize_contained(), and anonymous_namespace{inventory_ui.cpp}::wielded_worn_category().
Variable Documentation
default_preset
const inventory_selector_preset default_preset
Definition at line 335 of file inventory_ui.h.
Referenced by game_menus::inv::common().
inventory_ui_default_state
inventory_selector_save_state inventory_ui_default_state extern
Definition at line 320 of file inventory_ui.cpp.
Referenced by game_menus::inv::common(), load_inv_state(), save_inv_state(), and trade_preset::trade_preset().
pickup_sel_default_state
inventory_selector_save_state pickup_sel_default_state extern
Definition at line 321 of file inventory_ui.cpp.
Referenced by load_inv_state(), pickup_inventory_preset::pickup_inventory_preset(), and save_inv_state().
pickup_ui_default_state
inventory_selector_save_state pickup_ui_default_state extern
Definition at line 322 of file inventory_ui.cpp.
Referenced by load_inv_state(), game_menus::inv::pickup(), and save_inv_state().