Cataclysm DDA: src/inventory.cpp File Reference
inventory.cpp File Reference
#include "inventory.h"
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <optional>
#include <string>
#include <type_traits>
#include "avatar.h"
#include "calendar.h"
#include "character.h"
#include "colony.h"
#include "damage.h"
#include "debug.h"
#include "enums.h"
#include "flag.h"
#include "iexamine.h"
#include "inventory_ui.h"
#include "item_stack.h"
#include "itype.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "messages.h"
#include "npc.h"
#include "options.h"
#include "pocket_type.h"
#include "point.h"
#include "proficiency.h"
#include "ret_val.h"
#include "rng.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "vpart_position.h"
Functions
const invlet_wrapper inv_chars ("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!\"#&()+.:;=@[\\]^_{|}")
static bool stack_compare (const std::list< item > &lhs, const std::list< item > &rhs)
static int count_charges_in_list (const itype *type, const map_stack &items)
static int count_charges_in_list (const ammotype *ammotype, const map_stack &items, itype_id &item_type)
Finds the number of charges of the first item that matches ammotype.
template<typename F >
void for_each_item_in_both (const invstack &items, const std::map< const item *, int > &other, const F &f)
Variables
static const itype_id itype_acetaminophen ("acetaminophen")
static const itype_id itype_aspirin ("aspirin")
static const itype_id itype_brick_oven_pseudo ("brick_oven_pseudo")
static const itype_id itype_butchery_tree_pseudo ("butchery_tree_pseudo")
static const itype_id itype_codeine ("codeine")
static const itype_id itype_fire ("fire")
static const itype_id itype_heroin ("heroin")
static const itype_id itype_ibuprofen ("ibuprofen")
static const itype_id itype_oxycodone ("oxycodone")
static const itype_id itype_salt_water ("salt_water")
static const itype_id itype_tramadol ("tramadol")
static const material_id material_iron ("iron")
Function Documentation
count_charges_in_list() [1/2]
static int count_charges_in_list (const ammotype * ammotype, const map_stack & items, itype_id & item_type) static
Finds the number of charges of the first item that matches ammotype.
Parameters
ammotype Search target.
items Stack of items. Search stops at first match.
[out] item_type Matching type.
Returns
Number of charges.
Definition at line 471 of file inventory.cpp.
 {
     for( const item &candidate : items ) {
         if( candidate.is_ammo() && candidate.type->ammo->type == *ammotype ) {
             item_type = candidate.typeId();
             return candidate.charges;
         }
     }
     return 0;
 }
count_charges_in_list() [2/2]
static int count_charges_in_list (const itype * type, const map_stack & items) static
Definition at line 452 of file inventory.cpp.
 {
     for( const item &candidate : items ) {
         if( candidate.type == type ) {
             return candidate.charges;
         }
     }
     return 0;
 }
References type.
Referenced by inventory::form_from_map().
for_each_item_in_both()
template<typename F > void for_each_item_in_both (const invstack & items, const std::map< const item *, int > & other, const F & f)
Definition at line 892 of file inventory.cpp.
 {
     // Shortcut the logic in the common case where other is empty
     if( other.empty() ) {
         return;
     }
     for( const auto &elem : items ) {
         const item &representative = elem.front();
         auto other_it = other.find( &representative );
         if( other_it == other.end() ) {
             continue;
         }
         int num_to_count = other_it->second;
         if( representative.count_by_charges() ) {
             item copy = representative;
             copy.charges = std::min( copy.charges, num_to_count );
             f( copy );
         } else {
             for( const item &elem_stack_iter : elem ) {
                 f( elem_stack_iter );
                 if( --num_to_count <= 0 ) {
                     break;
                 }
             }
         }
     }
 }
References item::charges, item::count_by_charges(), min(), and other.
Referenced by inventory::volume_without(), and inventory::weight_without().
inv_chars()
const invlet_wrapper inv_chars ()
Referenced by inventory::assign_empty_invlet(), and inventory::restack().
stack_compare()
static bool stack_compare (const std::list< item > & lhs, const std::list< item > & rhs) static
Definition at line 246 of file inventory.cpp.
 {
     return lhs.front() < rhs.front();
 }
Referenced by inventory::restack(), and inventory::use_amount().
Variable Documentation
itype_acetaminophen
const itype_id itype_acetaminophen("acetaminophen") ("acetaminophen") static
Referenced by inventory::has_enough_painkiller(), and inventory::most_appropriate_painkiller().
itype_aspirin
const itype_id itype_aspirin("aspirin") ("aspirin") static
Referenced by inventory::has_enough_painkiller(), and inventory::most_appropriate_painkiller().
itype_brick_oven_pseudo
const itype_id itype_brick_oven_pseudo("brick_oven_pseudo") ("brick_oven_pseudo") static
Referenced by inventory::form_from_map().
itype_butchery_tree_pseudo
const itype_id itype_butchery_tree_pseudo("butchery_tree_pseudo") ("butchery_tree_pseudo") static
Referenced by inventory::form_from_map().
itype_codeine
const itype_id itype_codeine("codeine") ("codeine") static
Referenced by inventory::has_enough_painkiller(), and inventory::most_appropriate_painkiller().
itype_fire
const itype_id itype_fire("fire") ("fire") static
Referenced by inventory::form_from_map().
itype_heroin
const itype_id itype_heroin("heroin") ("heroin") static
Referenced by inventory::most_appropriate_painkiller().
itype_ibuprofen
const itype_id itype_ibuprofen("ibuprofen") ("ibuprofen") static
Referenced by inventory::has_enough_painkiller(), and inventory::most_appropriate_painkiller().
itype_oxycodone
const itype_id itype_oxycodone("oxycodone") ("oxycodone") static
Referenced by inventory::has_enough_painkiller(), and inventory::most_appropriate_painkiller().
itype_salt_water
const itype_id itype_salt_water("salt_water") ("salt_water") static
Referenced by inventory::rust_iron_items().
itype_tramadol
const itype_id itype_tramadol("tramadol") ("tramadol") static
Referenced by inventory::has_enough_painkiller(), and inventory::most_appropriate_painkiller().
material_iron
const material_id material_iron("iron") ("iron") static
Referenced by inventory::rust_iron_items().