Cataclysm DDA: src/inventory_ui.cpp File Reference
inventory_ui.cpp File Reference
#include "inventory_ui.h"
#include <cstdint>
#include <optional>
#include "activity_actor_definitions.h"
#include "basecamp.h"
#include "cata_assert.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "cuboid_rectangle.h"
#include "debug.h"
#include "enums.h"
#include "flag.h"
#include "inventory.h"
#include "input.h"
#include "item.h"
#include "item_category.h"
#include "item_pocket.h"
#include "item_search.h"
#include "item_stack.h"
#include "item_tname.h"
#include "line.h"
#include "make_static.h"
#include "map.h"
#include "map_selector.h"
#include "memory_fast.h"
#include "messages.h"
#include "options.h"
#include "output.h"
#include "point.h"
#include "popup.h"
#include "ret_val.h"
#include "sdltiles.h"
#include "localized_comparator.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "trade_ui.h"
#include "translations.h"
#include "type_id.h"
#include "uistate.h"
#include "ui_manager.h"
#include "units.h"
#include "units_utility.h"
#include "vehicle.h"
#include "vehicle_selector.h"
#include "vpart_position.h"
#include <algorithm>
#include <iterator>
#include <limits>
#include <map>
#include <numeric>
#include <set>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <vector>
Classes
struct anonymous_namespace{inventory_ui.cpp}::item_name_t
struct navigation_mode_data
struct inventory_input
struct container_data
class selection_column_preset
Namespaces
anonymous_namespace{inventory_ui.cpp}
io
Typedefs
using anonymous_namespace{inventory_ui.cpp}::startup_timer = std::chrono::time_point< std::chrono::steady_clock, std::chrono::milliseconds >
using anonymous_namespace{inventory_ui.cpp}::name_cache_t = std::unordered_map< item const *, item_name_t >
using anonymous_namespace{inventory_ui.cpp}::parent_path_t = std::vector< item_location >
using anonymous_namespace{inventory_ui.cpp}::pred_t = std::function< bool(inventory_entry const &)>
Functions
void anonymous_namespace{inventory_ui.cpp}::debug_print_timer (startup_timer const &tp, std::string const &msg="inv_ui setup took")
item_name_t & anonymous_namespace{inventory_ui.cpp}::get_cached_name (item const *it)
item_location anonymous_namespace{inventory_ui.cpp}::get_topmost_parent (item_location const &topmost, item_location const &loc, inventory_selector_preset const &preset)
parent_path_t anonymous_namespace{inventory_ui.cpp}::path_to_top (inventory_entry const &e, inventory_selector_preset const &pr)
void anonymous_namespace{inventory_ui.cpp}::move_if (std::vector< inventory_entry > &src, std::vector< inventory_entry > &dst, pred_t const &pred)
bool anonymous_namespace{inventory_ui.cpp}::always_yes (const inventory_entry &)
bool anonymous_namespace{inventory_ui.cpp}::return_item (const inventory_entry &entry)
bool anonymous_namespace{inventory_ui.cpp}::is_container (const item_location &loc)
bool anonymous_namespace{inventory_ui.cpp}::is_worn_id (item_category_id const &id)
item_category const * anonymous_namespace{inventory_ui.cpp}::wielded_worn_category (item_location const &loc, Character const &u)
bool is_worn_ablative (item_location const &container, item_location const &child)
template<>
std::string io::enum_to_string< inventory_selector::uimode > (inventory_selector::uimode mode)
void save_inv_state (JsonOut &json)
void load_inv_state (const JsonObject &jo)
inventory_selector::stat display_stat (const std::string &caption, int cur_value, int max_value, const std::function< std::string(int)> &disp_func)
std::vector< item_location > get_possible_reload_targets (const item_location &target)
Variables
static const item_category_id item_category_BIONIC_FUEL_SOURCE ("BIONIC_FUEL_SOURCE")
static const item_category_id item_category_INTEGRATED ("INTEGRATED")
static const item_category_id item_category_ITEMS_WORN ("ITEMS_WORN")
static const item_category_id item_category_WEAPON_HELD ("WEAPON_HELD")
startup_timer anonymous_namespace{inventory_ui.cpp}::tp_start
name_cache_t anonymous_namespace{inventory_ui.cpp}::item_name_cache
int anonymous_namespace{inventory_ui.cpp}::item_name_cache_users = 0
static const size_t max_win_snap_distance = 4
The maximum distance from the screen edge, to snap a window to it.
static const int min_cell_gap = 2
The minimal gap between two cells.
static const int normal_cell_gap = 4
The gap between two cells when screen space is limited.
static const int min_denial_gap = 2
The minimal gap between the first cell and denial.
static const int min_column_gap = 2
The minimal gap between two columns.
static const int normal_column_gap = 8
The gap between two columns when there's enough space, but they are not centered.
static const double min_ratio_to_center = 0.85
The minimal occupancy ratio to align columns to the center.
static inventory_selector_save_state inventory_sel_default_state { inventory_selector::uimode::categories }
inventory_selector_save_state inventory_ui_default_state { inventory_selector::uimode::categories }
inventory_selector_save_state pickup_sel_default_state { inventory_selector::uimode::categories }
inventory_selector_save_state pickup_ui_default_state { inventory_selector::uimode::hierarchy }
static const selection_column_preset selection_preset {}
static const haul_selector_preset haul_preset {}
Function Documentation
display_stat()
inventory_selector::stat display_stat (const std::string & caption, int cur_value, int max_value, const std::function< std::string(int)> & disp_func)
Definition at line 2509 of file inventory_ui.cpp.
 {
     const nc_color color = cur_value > max_value ? c_red : c_light_gray;
     return {{
             caption,
             colorize( disp_func( cur_value ), color ), "/",
             colorize( disp_func( max_value ), c_light_gray )
         }};
 }
References c_light_gray, c_red, color(), and colorize().
Referenced by draw_stats_tab(), game_menus::inv::ebooksave(), basecamp::get_equipment(), inventory_selector::get_holster_stat(), inventory_selector::get_volume_stat(), inventory_selector::get_weight_and_length_stat(), basecamp::give_equipment(), game_menus::inv::smoke_food(), and iuse::wash_items().
get_possible_reload_targets()
std::vector<item_location> get_possible_reload_targets (const item_location & target)
Definition at line 3357 of file inventory_ui.cpp.
 {
     std::vector<item_location> opts;
     opts.emplace_back( target );
     if( target->magazine_current() ) {
         opts.emplace_back( target, const_cast<item *>( target->magazine_current() ) );
     }
     for( const item *mod : target->gunmods() ) {
         item_location mod_loc( target, const_cast<item *>( mod ) );
         opts.emplace_back( mod_loc );
         if( mod->magazine_current() ) {
             opts.emplace_back( mod_loc, const_cast<item *>( mod->magazine_current() ) );
         }
     }
     return opts;
 }
References item::gunmods(), and item::magazine_current().
Referenced by select_ammo_inventory_preset::is_shown(), ammo_inventory_selector::mod_chosen_count(), game_menus::inv::select_ammo(), select_ammo_inventory_preset::select_ammo_inventory_preset(), and ammo_inventory_selector::set_all_entries_chosen_count().
is_worn_ablative()
bool is_worn_ablative (item_location const & container, item_location const & child)
Definition at line 183 of file inventory_ui.cpp.
 {
     // if the item is in an ablative pocket then put it with the item it is in
     // first do a short circuit test if the parent has ablative pockets at all
     return container->is_ablative() && container->is_worn_by_player() &&
            child.parent_pocket()->get_pocket_data()->ablative;
 }
References pocket_data::ablative, item_pocket::get_pocket_data(), item::is_ablative(), item::is_worn_by_player(), and item_location::parent_pocket().
Referenced by inventory_selector::add_contained_items(), wear_inventory_preset::is_shown(), inventory_selector::toggle_categorize_contained(), and anonymous_namespace{inventory_ui.cpp}::wielded_worn_category().
load_inv_state()
void load_inv_state (const JsonObject & jo)
Definition at line 332 of file inventory_ui.cpp.
 {
     jo.read( "inventory_sel_default_state", inventory_sel_default_state );
     jo.read( "inventory_ui_state", inventory_ui_default_state );
     jo.read( "pickup_sel_state", pickup_sel_default_state );
     jo.read( "pickup_ui_state", pickup_ui_default_state );
 }
References inventory_sel_default_state, inventory_ui_default_state, pickup_sel_default_state, pickup_ui_default_state, and JsonObject::read().
Referenced by uistatedata::deserialize().
save_inv_state()
void save_inv_state (JsonOut & json)
Definition at line 324 of file inventory_ui.cpp.
 {
     json.member( "inventory_sel_default_state", inventory_sel_default_state );
     json.member( "inventory_ui_state", inventory_ui_default_state );
     json.member( "pickup_sel_state", pickup_sel_default_state );
     json.member( "pickup_ui_state", pickup_ui_default_state );
 }
References inventory_sel_default_state, inventory_ui_default_state, JsonOut::member(), pickup_sel_default_state, and pickup_ui_default_state.
Referenced by uistatedata::serialize().
Variable Documentation
haul_preset
const haul_selector_preset haul_preset {} static
Definition at line 3948 of file inventory_ui.cpp.
inventory_sel_default_state
inventory_selector_save_state inventory_sel_default_state { inventory_selector::uimode::categories } static
Definition at line 319 of file inventory_ui.cpp.
Referenced by load_inv_state(), save_inv_state(), and inventory_selector::~inventory_selector().
inventory_ui_default_state
inventory_selector_save_state inventory_ui_default_state { inventory_selector::uimode::categories }
Definition at line 320 of file inventory_ui.cpp.
Referenced by game_menus::inv::common(), load_inv_state(), save_inv_state(), and trade_preset::trade_preset().
item_category_BIONIC_FUEL_SOURCE
const item_category_id item_category_BIONIC_FUEL_SOURCE("BIONIC_FUEL_SOURCE") ("BIONIC_FUEL_SOURCE") static
Referenced by anonymous_namespace{inventory_ui.cpp}::is_worn_id(), and anonymous_namespace{inventory_ui.cpp}::wielded_worn_category().
item_category_INTEGRATED
const item_category_id item_category_INTEGRATED("INTEGRATED") ("INTEGRATED") static
Referenced by anonymous_namespace{inventory_ui.cpp}::is_worn_id(), and anonymous_namespace{inventory_ui.cpp}::wielded_worn_category().
item_category_ITEMS_WORN
const item_category_id item_category_ITEMS_WORN("ITEMS_WORN") ("ITEMS_WORN") static
Referenced by inventory_selector::add_contained_items(), anonymous_namespace{inventory_ui.cpp}::is_worn_id(), and anonymous_namespace{inventory_ui.cpp}::wielded_worn_category().
item_category_WEAPON_HELD
const item_category_id item_category_WEAPON_HELD("WEAPON_HELD") ("WEAPON_HELD") static
Referenced by inventory_selector::add_character_items(), and anonymous_namespace{inventory_ui.cpp}::wielded_worn_category().
max_win_snap_distance
const size_t max_win_snap_distance = 4 static
The maximum distance from the screen edge, to snap a window to it.
Definition at line 192 of file inventory_ui.cpp.
Referenced by inventory_selector::prepare_layout().
min_cell_gap
const int min_cell_gap = 2 static
The minimal gap between two cells.
Definition at line 194 of file inventory_ui.cpp.
Referenced by inventory_column::draw(), and inventory_column::set_width().
min_column_gap
const int min_column_gap = 2 static
The minimal gap between two columns.
Definition at line 200 of file inventory_ui.cpp.
Referenced by inventory_selector::get_columns_occupancy_ratio().
min_denial_gap
const int min_denial_gap = 2 static
The minimal gap between the first cell and denial.
Definition at line 198 of file inventory_ui.cpp.
Referenced by inventory_column::draw(), and inventory_column::expand_to_fit().
min_ratio_to_center
const double min_ratio_to_center = 0.85 static
The minimal occupancy ratio to align columns to the center.
See also
inventory_selector::get_columns_occupancy_ratio()
Definition at line 207 of file inventory_ui.cpp.
Referenced by inventory_selector::are_columns_centered().
normal_cell_gap
const int normal_cell_gap = 4 static
The gap between two cells when screen space is limited.
Definition at line 196 of file inventory_ui.cpp.
Referenced by inventory_column::expand_to_fit().
normal_column_gap
const int normal_column_gap = 8 static
The gap between two columns when there's enough space, but they are not centered.
Definition at line 202 of file inventory_ui.cpp.
Referenced by inventory_selector::draw_columns(), and inventory_selector::get_layout_width().
pickup_sel_default_state
inventory_selector_save_state pickup_sel_default_state { inventory_selector::uimode::categories }
Definition at line 321 of file inventory_ui.cpp.
Referenced by load_inv_state(), pickup_inventory_preset::pickup_inventory_preset(), and save_inv_state().
pickup_ui_default_state
inventory_selector_save_state pickup_ui_default_state { inventory_selector::uimode::hierarchy }
Definition at line 322 of file inventory_ui.cpp.
Referenced by load_inv_state(), game_menus::inv::pickup(), and save_inv_state().
selection_preset
const selection_column_preset selection_preset {} static
Definition at line 510 of file inventory_ui.cpp.