Cataclysm DDA: src/item_pocket.cpp File Reference
item_pocket.cpp File Reference
#include "item_pocket.h"
#include <algorithm>
#include <cstdlib>
#include <memory>
#include <string>
#include <utility>
#include "ammo.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "color.h"
#include "crafting.h"
#include "creature_tracker.h"
#include "debug.h"
#include "enums.h"
#include "flag.h"
#include "generic_factory.h"
#include "handle_liquid.h"
#include "item.h"
#include "item_category.h"
#include "item_factory.h"
#include "item_location.h"
#include "itype.h"
#include "json.h"
#include "json_loader.h"
#include "localized_comparator.h"
#include "map.h"
#include "math_defines.h"
#include "messages.h"
#include "output.h"
#include "string_formatter.h"
#include "translations.h"
#include "units.h"
#include "units_utility.h"
Namespaces
io
Functions
template<>
std::string io::enum_to_string< pocket_type > (pocket_type data)
static void insert_separation_line (std::vector< iteminfo > &info)
static int charges_per_volume_recursive (const units::volume &max_item_volume, const item &it)
static void move_to_parent_pocket_recursive (const tripoint &pos, item &it, const item_location &loc, Character *carrier)
template<typename T >
std::string enumerate (cata::flat_set< T > container)
Function Documentation
charges_per_volume_recursive()
static int charges_per_volume_recursive (const units::volume & max_item_volume, const item & it) static
Definition at line 1313 of file item_pocket.cpp.
 {
     int min_charges = item::INFINITE_CHARGES;
     if( !it.is_soft() ) {
         return it.charges_per_volume( max_item_volume );
     }
     for( const item *content : it.all_items_top() ) {
         min_charges = std::min( min_charges, charges_per_volume_recursive( max_item_volume, *content ) );
         if( min_charges == 0 ) {
             return 0;
         }
     }
     return min_charges;
 }
References item::all_items_top(), item::charges_per_volume(), item::INFINITE_CHARGES, item::is_soft(), and min().
Referenced by item_pocket::is_compatible().
enumerate()
template<typename T > std::string enumerate (cata::flat_set< T > container)
Definition at line 2719 of file item_pocket.cpp.
 {
     std::vector<std::string> output;
     for( const T &id : container ) {
         output.push_back( id.c_str() );
     }
     return enumerate_as_string( output );
 }
References enumerate_as_string().
Referenced by item_pocket::favorite_settings::info().
insert_separation_line()
static void insert_separation_line (std::vector< iteminfo > & info) static
Definition at line 964 of file item_pocket.cpp.
 {
     if( info.empty() || info.back().sName != "--" ) {
         info.emplace_back( "DESCRIPTION", "--" );
     }
 }
Referenced by item_pocket::contents_info().
move_to_parent_pocket_recursive()
static void move_to_parent_pocket_recursive (const tripoint & pos, item & it, const item_location & loc, Character * carrier) static
Definition at line 1776 of file item_pocket.cpp.
 {
     if( loc ) {
         item_pocket *parent_pocket = loc.parent_pocket();
         if( parent_pocket && parent_pocket->can_contain( it ).success() ) {
             if( carrier ) {
                 carrier->add_msg_if_player( m_bad, _( "Your %1$s falls into your %2$s." ),
                                             it.display_name(), loc.parent_item()->label( 1 ) );
             }
             parent_pocket->insert_item( it );
             return;
         }
         if( loc.where() == item_location::type::container ) {
             move_to_parent_pocket_recursive( pos, it, loc.parent_item(), carrier );
             return;
         }
     }
     map &here = get_map();
     if( carrier ) {
         carrier->invalidate_weight_carried_cache();
         carrier->add_msg_player_or_npc( m_bad, _( "Your %s falls to the ground." ),
                                         _( "<npcname>'s %s falls to the ground." ), it.display_name() );
     } else {
         add_msg_if_player_sees( pos, m_bad, _( "The %s falls to the ground." ), it.display_name() );
     }
     here.add_item_or_charges( pos, it );
 }
References _, map::add_item_or_charges(), Character::add_msg_if_player(), add_msg_if_player_sees(), Character::add_msg_player_or_npc(), item_pocket::can_contain(), item_location::container, item::display_name(), get_map(), item_pocket::insert_item(), Character::invalidate_weight_carried_cache(), item::label(), m_bad, item_location::parent_item(), item_location::parent_pocket(), math_opers::pos(), and item_location::where().
Referenced by item_pocket::overflow().