Cataclysm DDA: src/item_location.cpp File Reference
item_location.cpp File Reference
#include "item_location.h"
#include <algorithm>
#include <cstddef>
#include <functional>
#include <iosfwd>
#include <iterator>
#include <list>
#include <optional>
#include <string>
#include <vector>
#include "character.h"
#include "character_id.h"
#include "color.h"
#include "creature_tracker.h"
#include "debug.h"
#include "game.h"
#include "game_constants.h"
#include "item.h"
#include "item_pocket.h"
#include "json.h"
#include "line.h"
#include "map.h"
#include "map_selector.h"
#include "point.h"
#include "ret_val.h"
#include "safe_reference.h"
#include "string_formatter.h"
#include "talker_item.h"
#include "translations.h"
#include "units.h"
#include "vehicle.h"
#include "vehicle_selector.h"
#include "visitable.h"
#include "vpart_position.h"
Classes
class item_location::impl
class item_location::impl::nowhere
class item_location::impl::item_on_map
class item_location::impl::item_on_person
class item_location::impl::item_on_vehicle
class item_location::impl::item_in_container
Functions
template<typename T >
static int find_index (const T &sel, const item *obj)
template<typename T >
static item * retrieve_index (const T &sel, int idx)
std::unique_ptr< talker > get_talker_for (item_location &it)
std::unique_ptr< talker > get_talker_for (const item_location &it)
std::unique_ptr< talker > get_talker_for (item_location *it)
Function Documentation
find_index()
template<typename T > static int find_index (const T & sel, const item * obj) static
Definition at line 39 of file item_location.cpp.
 {
     int idx = -1;
     sel.visit_items( [&idx, &obj]( const item * e, item * ) {
         idx++;
         if( e == obj ) {
             return VisitResponse::ABORT;
         }
         return VisitResponse::NEXT;
     } );
     return idx;
 }
References ABORT, NEXT, and int_id< T >::obj().
Referenced by item_location::impl::item_on_map::serialize(), item_location::impl::item_on_person::serialize(), and item_location::impl::item_on_vehicle::serialize().
get_talker_for() [1/3]
std::unique_ptr<talker> get_talker_for (const item_location & it)
Definition at line 1151 of file item_location.cpp.
 {
     return std::make_unique<talker_item_const>( &it );
 }
get_talker_for() [2/3]
std::unique_ptr<talker> get_talker_for (item_location & it)
Definition at line 1147 of file item_location.cpp.
 {
     return std::make_unique<talker_item>( &it );
 }
get_talker_for() [3/3]
std::unique_ptr<talker> get_talker_for (item_location * it)
Definition at line 1155 of file item_location.cpp.
 {
     return std::make_unique<talker_item>( it );
 }
retrieve_index()
template<typename T > static item* retrieve_index (const T & sel, int idx) static
Definition at line 53 of file item_location.cpp.
 {
     item *obj = nullptr;
     sel.visit_items( [&idx, &obj]( const item * e, item * ) {
         if( idx-- == 0 ) {
             obj = const_cast<item *>( e );
             return VisitResponse::ABORT;
         }
         return VisitResponse::NEXT;
     } );
     return obj;
 }
References ABORT, NEXT, and int_id< T >::obj().
Referenced by item_location::impl::item_on_map::unpack(), item_location::impl::item_on_person::unpack(), and item_location::impl::item_on_vehicle::unpack().