Cataclysm DDA: src/item_group.cpp File Reference
item_group.cpp File Reference
#include "item_group.h"
#include <algorithm>
#include <cstdlib>
#include <new>
#include <set>
#include <string>
#include <type_traits>
#include <unordered_map>
#include "calendar.h"
#include "cata_assert.h"
#include "cata_utility.h"
#include "debug.h"
#include "enum_traits.h"
#include "enums.h"
#include "flag.h"
#include "generic_factory.h"
#include "item.h"
#include "item_factory.h"
#include "itype.h"
#include "iuse_actor.h"
#include "json.h"
#include "make_static.h"
#include "options.h"
#include "pocket_type.h"
#include "relic.h"
#include "ret_val.h"
#include "rng.h"
#include "type_id.h"
#include "units.h"
Namespaces
io
Functions
static const std::string null_item_id ("null")
template<>
std::string io::enum_to_string< Item_spawn_data::overflow_behaviour > (Item_spawn_data::overflow_behaviour data)
static pocket_type guess_pocket_for (const item &container, const item &payload)
static void put_into_container (Item_spawn_data::ItemList &items, std::size_t num_items, const std::optional< itype_id > &container_type, const std::optional< std::string > &container_variant, const bool sealed, time_point birthday, Item_spawn_data::overflow_behaviour on_overflow, const std::string &context)
static item_group_id get_unique_group_id ()
Variables
static const itype_id itype_corpse ("corpse")
Function Documentation
get_unique_group_id()
static item_group_id get_unique_group_id () static
Definition at line 1040 of file item_group.cpp.
 {
     // This is just a hint what id to use next. Overflow of it is defined and if the group
     // name is already used, we simply go the next id.
     static unsigned int next_id = 0;
     // Prefixing with a character outside the ASCII range, so it is hopefully unique and
     // (if actually printed somewhere) stands out. Theoretically those auto-generated group
     // names should not be seen anywhere.
     static const std::string unique_prefix = "\u01F7 ";
     while( true ) {
         item_group_id new_group( unique_prefix + std::to_string( next_id++ ) );
         if( !item_group::group_is_defined( new_group ) ) {
             return new_group;
         }
     }
 }
References item_group::group_is_defined(), and to_string().
Referenced by item_group::load_item_group().
guess_pocket_for()
static pocket_type guess_pocket_for (const item & container, const item & payload) static
Definition at line 94 of file item_group.cpp.
 {
     if( ( container.is_gun() && payload.is_gunmod() ) || ( container.is_tool() &&
             payload.is_toolmod() ) ) {
         return pocket_type::MOD;
     }
     if( container.is_software_storage() && payload.is_software() ) {
         return pocket_type::SOFTWARE;
     }
     if( ( container.is_gun() || container.is_tool() ) && payload.is_magazine() ) {
         return pocket_type::MAGAZINE_WELL;
     } else if( container.is_magazine() && payload.is_ammo() ) {
         return pocket_type::MAGAZINE;
     }
     return pocket_type::CONTAINER;
 }
References CONTAINER, item::is_ammo(), item::is_gun(), item::is_gunmod(), item::is_magazine(), item::is_software(), item::is_software_storage(), item::is_tool(), item::is_toolmod(), MAGAZINE, MAGAZINE_WELL, MOD, and SOFTWARE.
Referenced by Item_modifier::modify(), and put_into_container().
null_item_id()
static const std::string null_item_id ("null") static
Referenced by Item_group::create_single(), and Single_item_creator::create_single_without_container().
put_into_container()
static void put_into_container (Item_spawn_data::ItemList & items, std::size_t num_items, const std::optional< itype_id > & container_type, const std::optional< std::string > & container_variant, const bool sealed, time_point birthday, Item_spawn_data::overflow_behaviour on_overflow, const std::string & context) static
Definition at line 111 of file item_group.cpp.
 {
     if( !container_type ) {
         return;
     }
     // Randomly permute the list of items so that when some don't fit it's
     // not always the ones at the end which are rejected.
     cata_assert( items.size() >= num_items );
     std::shuffle( items.end() - num_items, items.end(), rng_get_engine() );
     item ctr( *container_type, birthday );
     if( container_variant ) {
         ctr.set_itype_variant( *container_variant );
     }
     Item_spawn_data::ItemList excess;
     for( auto it = items.end() - num_items; it != items.end(); ++it ) {
         ret_val<void> ret = ctr.can_contain_directly( *it );
         if( ret.success() ) {
             const pocket_type pk_type = guess_pocket_for( ctr, *it );
             ctr.put_in( *it, pk_type );
         } else if( ctr.is_corpse() ) {
             const pocket_type pk_type = guess_pocket_for( ctr, *it );
             ctr.force_insert_item( *it, pk_type );
         } else {
             switch( on_overflow ) {
                 case Item_spawn_data::overflow_behaviour::none:
                     debugmsg( "item %s could not be put in container %s when spawning item group %s: %s.  "
                               "This can be resolved either by changing the container or contents "
                               "to ensure that they fit, or by specifying an overflow behaviour via "
                               "\"on_overflow\" on the item group.",
                               it->typeId().str(), container_type->str(), context, ret.str() );
                     break;
                 case Item_spawn_data::overflow_behaviour::spill:
                     excess.push_back( *it );
                     break;
                 case Item_spawn_data::overflow_behaviour::discard:
                     break;
                 case Item_spawn_data::overflow_behaviour::last:
                     debugmsg( "Invalid overflow_behaviour" );
                     break;
             }
         }
     }
     ctr.add_automatic_whitelist();
     if( sealed ) {
         ctr.seal();
     }
     items.erase( items.end() - num_items, items.end() );
     items.reserve( items.size() + excess.size() + 1 );
     items.insert( items.end(), std::make_move_iterator( excess.begin() ),
                   std::make_move_iterator( excess.end() ) );
     items.emplace_back( std::move( ctr ) );
 }
References item::add_automatic_whitelist(), item::can_contain_directly(), cata_assert, Item_spawn_data::context(), debugmsg, Item_spawn_data::discard, item::force_insert_item(), guess_pocket_for(), item::is_corpse(), Item_spawn_data::last, Item_spawn_data::none, Item_spawn_data::on_overflow, item::put_in(), cata::hash64_detail::ret, rng_get_engine(), item::seal(), Item_spawn_data::sealed, item::set_itype_variant(), and Item_spawn_data::spill.
Referenced by Single_item_creator::create(), and Item_group::create().
Variable Documentation
itype_corpse
const itype_id itype_corpse("corpse") ("corpse") static
Referenced by Single_item_creator::finalize().