Cataclysm DDA: src/item.cpp File Reference
item.cpp File Reference
#include "item.h"
#include <algorithm>
#include <array>
#include <cctype>
#include <clocale>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <iomanip>
#include <iterator>
#include <limits>
#include <memory>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <tuple>
#include <unordered_set>
#include <utility>
#include "ammo.h"
#include "ascii_art.h"
#include "avatar.h"
#include "bionics.h"
#include "bodygraph.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_assert.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "character_id.h"
#include "character_martial_arts.h"
#include "city.h"
#include "clothing_mod.h"
#include "clzones.h"
#include "color.h"
#include "coordinates.h"
#include "craft_command.h"
#include "creature.h"
#include "damage.h"
#include "debug.h"
#include "dispersion.h"
#include "display.h"
#include "effect.h"
#include "effect_source.h"
#include "enum_traits.h"
#include "enums.h"
#include "explosion.h"
#include "faction.h"
#include "fault.h"
#include "field_type.h"
#include "fire.h"
#include "flag.h"
#include "game.h"
#include "game_constants.h"
#include "gun_mode.h"
#include "iexamine.h"
#include "inventory.h"
#include "item_category.h"
#include "item_factory.h"
#include "item_group.h"
#include "item_tname.h"
#include "iteminfo_query.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "line.h"
#include "localized_comparator.h"
#include "magic.h"
#include "magic_enchantment.h"
#include "make_static.h"
#include "map.h"
#include "martialarts.h"
#include "material.h"
#include "messages.h"
#include "mod_manager.h"
#include "monster.h"
#include "mtype.h"
#include "mutation.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "pocket_type.h"
#include "point.h"
#include "proficiency.h"
#include "projectile.h"
#include "ranged.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "relic.h"
#include "requirements.h"
#include "ret_val.h"
#include "rng.h"
#include "skill.h"
#include "stomach.h"
#include "string_formatter.h"
#include "string_id.h"
#include "string_id_utils.h"
#include "text_snippets.h"
#include "translations.h"
#include "trap.h"
#include "try_parse_integer.h"
#include "units.h"
#include "units_fwd.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "vitamin.h"
#include "veh_type.h"
#include "vpart_position.h"
#include "weather.h"
#include "weather_gen.h"
#include "weather_type.h"
Classes
struct item_internal::scoped_goes_bad_cache
struct dps_comp_data
struct armor_encumb_data
Namespaces
item_internal
anonymous_namespace{item.cpp}
Typedefs
using npc_class_id = string_id< npc_class >
Functions
static const std::string GUN_MODE_VAR_NAME ("item::mode")
static const std::string CLOTHING_MOD_VAR_PREFIX ("clothing_mod_")
static const std::string flag_NO_DISPLAY ("NO_DISPLAY")
static const std::string flag_BLACKPOWDER_FOULING_DAMAGE ("BLACKPOWDER_FOULING_DAMAGE")
static const itype * nullitem ()
item & null_item_reference ()
Returns a reference to a null item (see item::is_null).
static bool item_internal::goes_bad_cache_fetch ()
static void item_internal::goes_bad_cache_set (const item *i)
static void item_internal::goes_bad_cache_unset ()
static bool item_internal::goes_bad_cache_is_for (const item *i)
static const item * get_most_rotten_component (const item &craft)
static std::string enumerate_lcsorted_with_limit (const std::vector< std::string > &v, const int max=5)
static time_duration get_shortest_lifespan_from_components (const item &craft)
static bool shelf_life_less_than_each_component (const item &craft)
static void inherit_rot_from_components (item &it)
const std::array< bodypart_str_id, 4 > & anonymous_namespace{item.cpp}::left_side_parts ()
const std::array< bodypart_str_id, 4 > & anonymous_namespace{item.cpp}::right_side_parts ()
static void iterate_helper_sbp (const item *i, const side s, const std::function< void(const sub_bodypart_str_id &)> &cb)
static void iterate_helper (const item *i, const side s, const std::function< void(const bodypart_str_id &)> &cb)
bool anonymous_namespace{item.cpp}::_stacks_whiteblacklist (item const &lhs, item const &rhs)
bool anonymous_namespace{item.cpp}::_stacks_weapon_mods (item const &lhs, item const &rhs)
bool anonymous_namespace{item.cpp}::_stacks_location_hint (item const &lhs, item const &rhs)
bool anonymous_namespace{item.cpp}::_stacks_rot (item const &lhs, item const &rhs, bool combine_liquid)
bool anonymous_namespace{item.cpp}::_stacks_mushy_dirty (item const &lhs, item const &rhs)
bool anonymous_namespace{item.cpp}::_stacks_food_status (item const &lhs, item const &rhs)
bool anonymous_namespace{item.cpp}::_stacks_food_traits (item const &lhs, item const &rhs)
bool anonymous_namespace{item.cpp}::_stacks_food_irradiated (item const &lhs, item const &rhs)
bool anonymous_namespace{item.cpp}::_stacks_food_perishable (item const &lhs, item const &rhs, bool check_cat)
bool anonymous_namespace{item.cpp}::_stacks_clothing_size (item const &lhs, item const &rhs)
bool anonymous_namespace{item.cpp}::_stacks_wetness (item const &lhs, item const &rhs, bool precise)
bool anonymous_namespace{item.cpp}::_stacks_cbm_status (item const &lhs, item const &rhs)
bool anonymous_namespace{item.cpp}::_stacks_ethereal (item const &lhs, item const &rhs)
bool anonymous_namespace{item.cpp}::_stacks_ups (item const &lhs, item const &rhs)
bool anonymous_namespace{item.cpp}::_stacks_mods (item const &lhs, item const &rhs)
bool anonymous_namespace{item.cpp}::_stacks_variant (item const &lhs, item const &rhs)
bool anonymous_namespace{item.cpp}::_stacks_components (item const &lhs, item const &rhs, bool check_components)
static int get_ranged_pierce (const common_ranged_data &ranged)
static std::string get_freshness_description (const item &food_item)
static int get_base_env_resist (const item &it)
static void insert_separation_line (std::vector< iteminfo > &info)
static bool armor_encumb_header_info (const item &it, std::vector< iteminfo > &info)
static void armor_protect_dmg_info (int dmg, std::vector< iteminfo > &info)
static bool operator< (const armor_encumb_data &lhs, const armor_encumb_data &rhs)
static void enchantment_info_helper (const item &it, enchantment::has type, std::vector< std::string > &always, std::vector< std::string > &active, std::vector< std::string > &inactive)
static void enchantment_info_printer (std::vector< iteminfo > &info, std::vector< std::string > &always, std::vector< std::string > &active, std::vector< std::string > &inactive)
static units::length sawn_off_reduction (const itype *type)
static void get_layer_helper (const item *i, bodypart_id bp, std::set< layer_level > &layers)
static int get_degrade_amount (const item &it, int dmgNow_, int dmgPrev)
iteminfo vol_to_info (const std::string &type, const std::string &left, const units::volume &vol, int decimal_places, bool lower_is_better)
iteminfo weight_to_info (const std::string &type, const std::string &left, const units::mass &weight, int, bool lower_is_better)
bool item_ptr_compare_by_charges (const item *left, const item *right)
bool item_compare_by_charges (const item &left, const item &right)
static const std::string USED_BY_IDS ("USED_BY_IDS")
static const std::string & get_clothing_mod_val_key (clothing_mod_type type)
template<class C >
void anonymous_namespace{item.cpp}::_aggregate (C &container, typename C::key_type const &key, item const *it, item::aggregate_t *&running_max, item::aggregate_t *&max_type, int depth, int maxdepth)
bool is_preferred_component (const item &component)
Filter for crafting components first pass searches excluding undesirable properties.
Variables
static const ammotype ammo_battery ("battery")
static const ammotype ammo_bolt ("bolt")
static const ammotype ammo_money ("money")
static const ammotype ammo_plutonium ("plutonium")
static const bionic_id bio_digestion ("bio_digestion")
static const bodygraph_id bodygraph_full_body_iteminfo ("full_body_iteminfo")
static const damage_type_id damage_acid ("acid")
static const damage_type_id damage_bash ("bash")
static const damage_type_id damage_bullet ("bullet")
static const damage_type_id damage_cut ("cut")
static const damage_type_id damage_heat ("heat")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_cig ("cig")
static const efftype_id effect_shakes ("shakes")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_weed_high ("weed_high")
static const fault_id fault_overheat_safety ("fault_overheat_safety")
static const furn_str_id furn_f_metal_smoking_rack_active ("f_metal_smoking_rack_active")
static const furn_str_id furn_f_smoking_rack_active ("f_smoking_rack_active")
static const furn_str_id furn_f_water_mill_active ("f_water_mill_active")
static const furn_str_id furn_f_wind_mill_active ("f_wind_mill_active")
static const gun_mode_id gun_mode_REACH ("REACH")
static const item_category_id item_category_container ("container")
static const item_category_id item_category_drugs ("drugs")
static const item_category_id item_category_food ("food")
static const item_category_id item_category_maps ("maps")
static const item_category_id item_category_spare_parts ("spare_parts")
static const item_category_id item_category_tools ("tools")
static const item_category_id item_category_weapons ("weapons")
static const itype_id itype_arredondo_chute ("arredondo_chute")
static const itype_id itype_barrel_small ("barrel_small")
static const itype_id itype_battery ("battery")
static const itype_id itype_blood ("blood")
static const itype_id itype_brass_catcher ("brass_catcher")
static const itype_id itype_bullet_crossbow ("bullet_crossbow")
static const itype_id itype_cash_card ("cash_card")
static const itype_id itype_cig_butt ("cig_butt")
static const itype_id itype_cig_lit ("cig_lit")
static const itype_id itype_cigar_butt ("cigar_butt")
static const itype_id itype_cigar_lit ("cigar_lit")
static const itype_id itype_disassembly ("disassembly")
static const itype_id itype_hand_crossbow ("hand_crossbow")
static const itype_id itype_joint_roach ("joint_roach")
static const itype_id itype_null ("null")
static const itype_id itype_power_cord ("power_cord")
static const itype_id itype_rad_badge ("rad_badge")
static const itype_id itype_rm13_armor ("rm13_armor")
static const itype_id itype_stock_none ("stock_none")
static const itype_id itype_tuned_mechanism ("tuned_mechanism")
static const itype_id itype_water ("water")
static const itype_id itype_water_clean ("water_clean")
static const itype_id itype_waterproof_gunmod ("waterproof_gunmod")
static const json_character_flag json_flag_CANNIBAL ("CANNIBAL")
static const json_character_flag json_flag_IMMUNE_SPOIL ("IMMUNE_SPOIL")
static const json_character_flag json_flag_PSYCHOPATH ("PSYCHOPATH")
static const json_character_flag json_flag_SAPIOVORE ("SAPIOVORE")
static const matec_id RAPID ("RAPID")
static const material_id material_wool ("wool")
static const morale_type morale_null ("morale_null")
static const mtype_id mon_human ("mon_human")
static const mtype_id mon_zombie_smoker ("mon_zombie_smoker")
static const mtype_id mon_zombie_soldier_no_weakpoints ("mon_zombie_soldier_no_weakpoints")
static const mtype_id mon_zombie_survivor_no_weakpoints ("mon_zombie_survivor_no_weakpoints")
static const mtype_id pseudo_debug_mon ("pseudo_debug_mon")
static const quality_id qual_BOIL ("BOIL")
static const quality_id qual_JACK ("JACK")
static const quality_id qual_LIFT ("LIFT")
static const skill_id skill_cooking ("cooking")
static const skill_id skill_melee ("melee")
static const skill_id skill_survival ("survival")
static const skill_id skill_weapon ("weapon")
static const species_id species_ROBOT ("ROBOT")
static const sub_bodypart_str_id sub_body_part_torso_lower ("torso_lower")
static const sub_bodypart_str_id sub_body_part_torso_upper ("torso_upper")
static const trait_id trait_CARNIVORE ("CARNIVORE")
static const trait_id trait_JITTERY ("JITTERY")
static const trait_id trait_LIGHTWEIGHT ("LIGHTWEIGHT")
static const trait_id trait_TOLERANCE ("TOLERANCE")
static const trait_id trait_WOOLALLERGY ("WOOLALLERGY")
static const vitamin_id vitamin_human_flesh_vitamin ("human_flesh_vitamin")
static const int PRICE_FILTHY_MALUS = 100
static constexpr float MIN_LINK_EFFICIENCY = 0.001f
light_emission nolight = {0, 0, 0}
static bool item_internal::goes_bad_temp_cache = false
static const item * item_internal::goes_bad_temp_cache_for = nullptr
static constexpr std::array< double, 41 > hits_by_accuracy
static const std::vector< std::pair< translation, dps_comp_data > > dps_comp_monsters
Typedef Documentation
npc_class_id
using npc_class_id = string_id<npc_class>
Definition at line 236 of file item.cpp.
Function Documentation
armor_encumb_header_info()
static bool armor_encumb_header_info (const item & it, std::vector< iteminfo > & info) static
Definition at line 3700 of file item.cpp.
 {
     std::string format;
     Character &player_character = get_player_character();
     const bool sizing_matters = it.get_sizing( player_character ) != item::sizing::ignore;
     if( it.has_flag( flag_FIT ) ) {
         format = _( " <info>(fits)</info>" );
     } else if( it.has_flag( flag_VARSIZE ) && sizing_matters ) {
         format = _( " <bad>(poor fit)</bad>" );
     }
     if( sizing_matters ) {
         const item::sizing sizing_level = it.get_sizing( player_character );
         //If we have the wrong size, we do not fit so alert the player
         if( sizing_level == item::sizing::human_sized_small_char ) {
             format = _( " <bad>(too big)</bad>" );
         } else if( sizing_level == item::sizing::big_sized_small_char ) {
             format = _( " <bad>(huge!)</bad>" );
         } else if( sizing_level == item::sizing::small_sized_human_char ||
                    sizing_level == item::sizing::human_sized_big_char ) {
             format = _( " <bad>(too small)</bad>" );
         } else if( sizing_level == item::sizing::small_sized_big_char ) {
             format = _( " <bad>(tiny!)</bad>" );
         }
     }
     if( format.empty() ) {
         return false;
     }
     //~ The size or fit of an article of clothing (fits / poor fit)
     info.emplace_back( "ARMOR", _( "<bold>Size/Fit</bold>:" ) + format );
     return true;
 }
References _, item::big_sized_small_char, flag_FIT, flag_VARSIZE, get_player_character(), item::get_sizing(), item::has_flag(), item::human_sized_big_char, item::human_sized_small_char, item::ignore, item::small_sized_big_char, and item::small_sized_human_char.
Referenced by item::armor_info().
armor_protect_dmg_info()
static void armor_protect_dmg_info (int dmg, std::vector< iteminfo > & info) static
Definition at line 3797 of file item.cpp.
 {
     if( dmg > 0 ) {
         info.emplace_back( "ARMOR", _( "Protection values are <bad>reduced by damage</bad> and "
                                        "you may be able to <info>improve them by repairing this "
                                        "item</info>." ) );
     }
 }
References _.
Referenced by item::armor_info(), and item::armor_protection_info().
CLOTHING_MOD_VAR_PREFIX()
static const std::string CLOTHING_MOD_VAR_PREFIX ("clothing_mod_") static
Referenced by get_clothing_mod_val_key().
enchantment_info_helper()
static void enchantment_info_helper (const item & it, enchantment::has type, std::vector< std::string > & always, std::vector< std::string > & active, std::vector< std::string > & inactive) static
Definition at line 5061 of file item.cpp.
 {
     for( const enchantment &ench : it.get_defined_enchantments() ) {
         // only check conditions matching the given type
         if( ench.active_conditions.first == type ) {
             // if a description is provided use that
             if( !ench.description.empty() ) {
                 std::string info;
                 if( !ench.name.empty() ) {
                     info = string_format( "<info>%s</info>: %s", ench.name.translated(),
                                           ench.description.translated() );
                 } else {
                     info = string_format( _( "<info>Description</info>: %s" ), ench.description.translated() );
                 }
                 switch( ench.active_conditions.second ) {
                     case enchantment::condition::ALWAYS:
                         always.push_back( info );
                         break;
                     case enchantment::condition::ACTIVE:
                         active.push_back( info );
                         break;
                     case enchantment::condition::INACTIVE:
                         inactive.push_back( info );
                         break;
                     case enchantment::condition::DIALOG_CONDITION:
                     case enchantment::condition::NUM_CONDITION:
                         // skip for dialog conditions
                         break;
                 }
             }
         }
     }
     for( const enchant_cache &ench : it.get_proc_enchantments() ) {
         // only check conditions matching the given type
         if( ench.active_conditions.first == type ) {
             // if a description is provided use that
             if( !ench.description.empty() ) {
                 std::string info;
                 if( !ench.name.empty() ) {
                     info = string_format( "<info>%s</info>: %s", ench.name.translated(),
                                           ench.description.translated() );
                 } else {
                     info = string_format( _( "<info>Description</info>: %s" ), ench.description.translated() );
                 }
                 switch( ench.active_conditions.second ) {
                     case enchantment::condition::ALWAYS:
                         always.push_back( info );
                         break;
                     case enchantment::condition::ACTIVE:
                         active.push_back( info );
                         break;
                     case enchantment::condition::INACTIVE:
                         inactive.push_back( info );
                         break;
                     case enchantment::condition::DIALOG_CONDITION:
                     case enchantment::condition::NUM_CONDITION:
                         // skip for dialog conditions
                         break;
                 }
             }
         }
     }
 }
References _, always, item::get_defined_enchantments(), item::get_proc_enchantments(), and string_format().
Referenced by item::enchantment_info().
enchantment_info_printer()
static void enchantment_info_printer (std::vector< iteminfo > & info, std::vector< std::string > & always, std::vector< std::string > & active, std::vector< std::string > & inactive) static
Definition at line 5129 of file item.cpp.
 {
     if( !always.empty() ) {
         info.emplace_back( "DESCRIPTION", string_format( _( "<bold>Always</bold>:" ) ) );
         for( const std::string &entry : always ) {
             info.emplace_back( "DESCRIPTION", string_format( "* %s", entry ) );
         }
     }
     if( !active.empty() ) {
         info.emplace_back( "DESCRIPTION", string_format( _( "<bold>When Active</bold>:" ) ) );
         for( const std::string &entry : active ) {
             info.emplace_back( "DESCRIPTION", string_format( "* %s", entry ) );
         }
     }
     if( !inactive.empty() ) {
         info.emplace_back( "DESCRIPTION", string_format( _( "<bold>When Inactive</bold>:" ) ) );
         for( const std::string &entry : inactive ) {
             info.emplace_back( "DESCRIPTION", string_format( "* %s", entry ) );
         }
     }
 }
References _, always, and string_format().
Referenced by item::enchantment_info().
enumerate_lcsorted_with_limit()
static std::string enumerate_lcsorted_with_limit (const std::vector< std::string > & v, const int max = 5) static
Definition at line 447 of file item.cpp.
 {
     if( max < 1 ) {
         debugmsg( "Expected max to be 1 or more" );
         return std::string();
     }
     std::vector<std::string> c( std::min<size_t>( max, v.size() ) );
     std::partial_sort_copy( v.begin(), v.end(), c.begin(), c.end(), localized_compare );
     const int more = static_cast<int>( v.size() - c.size() );
     if( more == 0 ) {
         return enumerate_as_string( c );
     }
     const std::string res = enumerate_as_string( c, enumeration_conjunction::none );
     return string_format( max == 1 ? _( "%s and %d more" ) : _( "%s, and %d more" ), res, more );
 }
References _, c, debugmsg, enumerate_as_string(), localized_compare, max(), none, and string_format().
Referenced by item::book_info(), item::final_info(), and item::tool_info().
flag_BLACKPOWDER_FOULING_DAMAGE()
static const std::string flag_BLACKPOWDER_FOULING_DAMAGE ("BLACKPOWDER_FOULING_DAMAGE") static
Referenced by item::process_internal(), and item::processing_speed().
flag_NO_DISPLAY()
static const std::string flag_NO_DISPLAY ("NO_DISPLAY") static
Referenced by item::food_info().
get_base_env_resist()
static int get_base_env_resist (const item & it) static
Definition at line 2102 of file item.cpp.
 {
     const islot_armor *t = it.find_armor_data();
     if( t == nullptr ) {
         if( it.is_pet_armor() ) {
             return it.type->pet_armor->env_resist * it.get_relative_health();
         } else {
             return 0;
         }
     }
     return t->avg_env_resist() * it.get_relative_health();
 }
References islot_armor::avg_env_resist(), item::find_armor_data(), item::get_relative_health(), item::is_pet_armor(), itype::pet_armor, and item::type.
Referenced by item::armor_protection_info(), and item::pet_armor_protection_info().
get_clothing_mod_val_key()
static const std::string& get_clothing_mod_val_key (clothing_mod_type type) static
Definition at line 14822 of file item.cpp.
 {
     const static auto cache = ( []() {
         std::array<std::string, clothing_mods::all_clothing_mod_types.size()> res;
         for( const clothing_mod_type &type : clothing_mods::all_clothing_mod_types ) {
             res[type] = CLOTHING_MOD_VAR_PREFIX + clothing_mods::string_from_clothing_mod_type(
                             clothing_mods::all_clothing_mod_types[type]
                         );
         }
         return res;
     } )();
     return cache[ type ];
 }
References clothing_mods::all_clothing_mod_types, CLOTHING_MOD_VAR_PREFIX(), and clothing_mods::string_from_clothing_mod_type().
Referenced by item::get_clothing_mod_val(), and item::update_clothing_mod_val().
get_degrade_amount()
static int get_degrade_amount (const item & it, int dmgNow_, int dmgPrev) static
Definition at line 8914 of file item.cpp.
 {
     const int max_dmg = it.max_damage();
     const int degrade_increments = it.type->degrade_increments();
     if( max_dmg == 0 || degrade_increments == 0 ) {
         return 0; // count by charges
     }
     const int facNow_ = dmgNow_ == 0 ? -1 : ( dmgNow_ - 1 ) * 5 / max_dmg;
     const int facPrev = dmgPrev == 0 ? -1 : ( dmgPrev - 1 ) * 5 / max_dmg;
     return std::max( facNow_ - facPrev, 0 ) * max_dmg / degrade_increments;
 }
References itype::degrade_increments(), max(), item::max_damage(), and item::type.
Referenced by item::mod_damage().
get_freshness_description()
static std::string get_freshness_description (const item & food_item) static
Definition at line 1971 of file item.cpp.
 {
     // So, skilled characters looking at food that is neither super-fresh nor about to rot
     // can guess its age as one of {quite fresh,midlife,past midlife,old soon}, and also
     // guess about how long until it spoils.
     const double rot_progress = food_item.get_relative_rot();
     const time_duration shelf_life = food_item.get_shelf_life();
     time_duration time_left = shelf_life - ( shelf_life * rot_progress );
     // Correct for an estimate that exceeds shelf life -- this happens especially with
     // fresh items.
     if( time_left > shelf_life ) {
         time_left = shelf_life;
     }
     Character &player_character = get_player_character();
     if( food_item.is_fresh() ) {
         // Fresh food is assumed to be obviously so regardless of skill.
         if( player_character.can_estimate_rot() ) {
             return string_format( _( "* This food looks as <good>fresh</good> as it can be.  "
                                      "It still has <info>%s</info> until it spoils." ),
                                   to_string_approx( time_left ) );
         } else {
             return _( "* This food looks as <good>fresh</good> as it can be." );
         }
     } else if( food_item.is_going_bad() ) {
         // Old food likewise is assumed to be fairly obvious.
         if( player_character.can_estimate_rot() ) {
             return string_format( _( "* This food looks <bad>old</bad>.  "
                                      "It's just <info>%s</info> from becoming inedible." ),
                                   to_string_approx( time_left ) );
         } else {
             return _( "* This food looks <bad>old</bad>.  "
                       "It's on the brink of becoming inedible." );
         }
     }
     if( !player_character.can_estimate_rot() ) {
         // Unskilled characters only get a hint that more information exists...
         return _( "* This food looks <info>fine</info>.  If you were more skilled in "
                   "cooking or survival, you might be able to make a better estimation." );
     }
     // Otherwise, a skilled character can determine the below options:
     if( rot_progress < 0.3 ) {
         //~ here, %s is an approximate time span, e.g., "over 2 weeks" or "about 1 season"
         return string_format( _( "* This food looks <good>quite fresh</good>.  "
                                  "It has <info>%s</info> until it spoils." ),
                               to_string_approx( time_left ) );
     } else if( rot_progress < 0.5 ) {
         //~ here, %s is an approximate time span, e.g., "over 2 weeks" or "about 1 season"
         return string_format( _( "* This food looks like it is reaching its <neutral>midlife</neutral>.  "
                                  "There's <info>%s</info> before it spoils." ),
                               to_string_approx( time_left ) );
     } else if( rot_progress < 0.7 ) {
         //~ here, %s is an approximate time span, e.g., "over 2 weeks" or "about 1 season"
         return string_format( _( "* This food looks like it has <neutral>passed its midlife</neutral>.  "
                                  "Edible, but will go bad in <info>%s</info>." ),
                               to_string_approx( time_left ) );
     } else {
         //~ here, %s is an approximate time span, e.g., "over 2 weeks" or "about 1 season"
         return string_format( _( "* This food looks like it <bad>will be old soon</bad>.  "
                                  "It has <info>%s</info>, so if you plan to use it, it's now or never." ),
                               to_string_approx( time_left ) );
     }
 }
References _, Character::can_estimate_rot(), get_player_character(), item::get_relative_rot(), item::get_shelf_life(), item::is_fresh(), item::is_going_bad(), string_format(), and to_string_approx().
Referenced by item::rot_info().
get_layer_helper()
static void get_layer_helper (const item * i, bodypart_id bp, std::set< layer_level > & layers) static
Definition at line 8173 of file item.cpp.
 {
     const islot_armor *t = i->find_armor_data();
     if( t == nullptr ) {
         return;
     }
     for( const armor_portion_data &data : t->data ) {
         if( !data.covers.has_value() ) {
             continue;
         }
         for( const bodypart_str_id &bpid : data.covers.value() ) {
             if( bp == bpid ) {
                 layers.insert( data.layers.begin(), data.layers.end() );
             }
         }
     }
 }
References bp, armor_portion_data::covers, islot_armor::data, item::find_armor_data(), and armor_portion_data::layers.
Referenced by item::get_layer().
get_most_rotten_component()
static const item* get_most_rotten_component (const item & craft) static
Definition at line 428 of file item.cpp.
 {
     const item *most_rotten = nullptr;
     for( const item_components::type_vector_pair &tvp : craft.components ) {
         if( !tvp.second.front().goes_bad() ) {
             // they're all the same type, so this should be the same for all
             continue;
         }
         for( const item &it : tvp.second ) {
             if( !most_rotten || it.get_relative_rot() > most_rotten->get_relative_rot() ) {
                 most_rotten = &it;
             }
         }
     }
     return most_rotten;
 }
References anonymous_namespace{item_tname.cpp}::craft(), and item::get_relative_rot().
Referenced by inherit_rot_from_components().
get_ranged_pierce()
static int get_ranged_pierce (const common_ranged_data & ranged) static
Definition at line 1944 of file item.cpp.
 {
     if( ranged.damage.empty() ) {
         return 0;
     }
     return ranged.damage.damage_units.front().res_pen;
 }
References common_ranged_data::damage, damage_instance::damage_units, and damage_instance::empty().
Referenced by item::ammo_info(), item::gun_info(), and item::gunmod_info().
get_shortest_lifespan_from_components()
static time_duration get_shortest_lifespan_from_components (const item & craft) static
Definition at line 464 of file item.cpp.
 {
     const item *shortest_lifespan_component = nullptr;
     time_duration shortest_lifespan = 0_turns;
     for( const item_components::type_vector_pair &tvp : craft.components ) {
         if( !tvp.second.front().goes_bad() ) {
             // they're all the same type, so this should be the same for all
             continue;
         }
         for( const item &it : tvp.second ) {
             time_duration lifespan = it.get_shelf_life() - it.get_rot();
             if( !shortest_lifespan_component || ( lifespan < shortest_lifespan ) ) {
                 shortest_lifespan_component = &it;
                 shortest_lifespan = shortest_lifespan_component->get_shelf_life() -
                                     shortest_lifespan_component->get_rot();
             }
         }
     }
     return shortest_lifespan;
 }
References anonymous_namespace{item_tname.cpp}::craft(), item::get_rot(), and item::get_shelf_life().
Referenced by inherit_rot_from_components().
GUN_MODE_VAR_NAME()
static const std::string GUN_MODE_VAR_NAME ("item::mode") static
Referenced by item::gun_get_mode_id(), and item::gun_set_mode().
inherit_rot_from_components()
static void inherit_rot_from_components (item & it) static
Definition at line 512 of file item.cpp.
 {
     if( shelf_life_less_than_each_component( it ) ) {
         const time_duration shortest_lifespan = get_shortest_lifespan_from_components( it );
         if( shortest_lifespan > 0_turns && shortest_lifespan < it.get_shelf_life() ) {
             it.set_rot( it.get_shelf_life() - shortest_lifespan );
             return;
         }
         // Fallthrough: shortest_lifespan <= 0_turns (all components are rotten)
     }
     const item *most_rotten = get_most_rotten_component( it );
     if( most_rotten ) {
         it.set_relative_rot( most_rotten->get_relative_rot() );
     }
 }
References get_most_rotten_component(), item::get_relative_rot(), item::get_shelf_life(), get_shortest_lifespan_from_components(), item::set_relative_rot(), item::set_rot(), and shelf_life_less_than_each_component().
Referenced by item::item().
insert_separation_line()
static void insert_separation_line (std::vector< iteminfo > & info) static
Definition at line 2217 of file item.cpp.
 {
     if( info.empty() || info.back().sName != "--" ) {
         info.emplace_back( "DESCRIPTION", "--" );
     }
 }
Referenced by item::actions_info(), item::ammo_info(), item::armor_full_protection_info(), item::armor_info(), item::ascii_art_info(), item::basic_info(), item::battery_info(), item::bionic_info(), item::book_info(), item::contents_info(), item::disassembly_info(), item::enchantment_info(), item::final_info(), item::food_info(), item::gun_info(), item::gunmod_info(), item::info(), item::magazine_info(), item::melee_combat_info(), item::properties_info(), item::qualities_info(), item::repair_info(), and item::tool_info().
is_preferred_component()
bool is_preferred_component (const item & component)
Filter for crafting components first pass searches excluding undesirable properties.
Definition at line 15190 of file item.cpp.
 {
     return component.is_container_empty() && !component.has_flag( flag_HIDDEN_POISON ) &&
            !component.has_flag( flag_HIDDEN_HALLU );
 }
References flag_HIDDEN_HALLU, and flag_HIDDEN_POISON.
Referenced by Character::consume_items(), and Character::select_item_component().
item_compare_by_charges()
bool item_compare_by_charges (const item & left, const item & right)
Definition at line 12512 of file item.cpp.
 {
     return item_ptr_compare_by_charges( &left, &right );
 }
References item_ptr_compare_by_charges(), keycode::left, and keycode::right.
item_ptr_compare_by_charges()
bool item_ptr_compare_by_charges (const item * left, const item * right)
Definition at line 12501 of file item.cpp.
 {
     if( left->empty() ) {
         return false;
     } else if( right->empty() ) {
         return true;
     } else {
         return right->only_item().charges < left->only_item().charges;
     }
 }
References keycode::left, and keycode::right.
Referenced by Character::check_eligible_containers_for_crafting(), and item_compare_by_charges().
iterate_helper()
static void iterate_helper (const item * i, const side s, const std::function< void(const bodypart_str_id &)> & cb) static
Definition at line 1115 of file item.cpp.
 {
     const islot_armor *armor = i->find_armor_data();
     if( armor == nullptr ) {
         return;
     }
     // If we are querying for only one side of the body, we ignore coverage
     // for parts on the opposite side of the body.
     const auto &opposite_side_parts = s == side::LEFT ? right_side_parts() : left_side_parts();
     for( const armor_portion_data &data : armor->data ) {
         if( data.covers.has_value() ) {
             if( !armor->sided || s == side::BOTH || s == side::num_sides ) {
                 for( const bodypart_str_id &bpid : data.covers.value() ) {
                     cb( bpid );
                 }
                 continue;
             }
             for( const bodypart_str_id &bpid : data.covers.value() ) {
                 if( std::find( opposite_side_parts.begin(), opposite_side_parts.end(),
                                bpid ) == opposite_side_parts.end() ) {
                     cb( bpid );
                 }
             }
         }
     }
 }
References BOTH, armor_portion_data::covers, islot_armor::data, item::find_armor_data(), LEFT, anonymous_namespace{item.cpp}::left_side_parts(), num_sides, anonymous_namespace{item.cpp}::right_side_parts(), and islot_armor::sided.
Referenced by item::iterate_covered_body_parts_internal().
iterate_helper_sbp()
static void iterate_helper_sbp (const item * i, const side s, const std::function< void(const sub_bodypart_str_id &)> & cb) static
Definition at line 1072 of file item.cpp.
 {
     const islot_armor *armor = i->find_armor_data();
     if( armor == nullptr ) {
         return;
     }
     for( const armor_portion_data &data : armor->sub_data ) {
         if( !data.sub_coverage.empty() ) {
             if( !armor->sided || s == side::BOTH || s == side::num_sides ) {
                 for( const sub_bodypart_str_id &bpid : data.sub_coverage ) {
                     cb( bpid );
                 }
                 continue;
             }
             for( const sub_bodypart_str_id &bpid : data.sub_coverage ) {
                 if( bpid->part_side == s || bpid->part_side == side::BOTH ) {
                     cb( bpid );
                 }
             }
         }
     }
 }
References BOTH, item::find_armor_data(), num_sides, sub_body_part_type::part_side, islot_armor::sided, armor_portion_data::sub_coverage, and islot_armor::sub_data.
Referenced by item::iterate_covered_sub_body_parts_internal().
null_item_reference()
item& null_item_reference ()
Returns a reference to a null item (see item::is_null).
The reference is always valid and stays valid until the program ends.
Definition at line 248 of file item.cpp.
 {
     static item result{};
     // reset it, in case a previous caller has changed it
     result = item();
     return result;
 }
References item.
Referenced by map::_add_item_or_charges(), target_ui::action_aim_and_shoot(), map::add_item(), Creature::attack_air(), talker_character_const::attack_speed(), npc::average_damage_dealt(), Character::best_item_with_quality(), npc::check_or_use_weapon_cbm(), relic_procgen_data::create_item(), outfit::current_unarmed_weapon(), npc::decide_needs(), avatar::disarm(), construct::done_deconstruct(), npc::evaluate_best_attack(), npc::evaluate_best_weapon(), npc::evaluate_character(), Character::evaluate_techniques(), inventory::find_item(), item_contents::first_ammo(), item_contents::first_item(), npc::get_healing_item(), weldrig_hack::get_item(), Character::get_melee_hit_base(), Character::get_standard_stamina_cost(), talker_npc::give_item_to(), Character::hit_roll(), outfit::i_at(), item_contents::legacy_front(), item::loaded_ammo(), Character::melee_attack_abstract(), inventory::most_appropriate_painkiller(), item_contents::only_item(), item_stack::only_item(), avatar::rebuild_aim_cache(), npc::regen_ai_cache(), set_item_map(), Character::store(), stumble(), npc::value(), npc::wants_take_that(), npc::wield_better_weapon(), and memorial_logger::write_text_memorial().
nullitem()
static const itype* nullitem () static
Definition at line 242 of file item.cpp.
 {
     static itype nullitem_m;
     return &nullitem_m;
 }
Referenced by item::is_null(), item::item(), and item::reload().
operator<()
static bool operator< (const armor_encumb_data & lhs, const armor_encumb_data & rhs) static
Definition at line 4054 of file item.cpp.
 {
     return lhs.encumb < rhs.encumb;
 }
References armor_encumb_data::encumb.
sawn_off_reduction()
static units::length sawn_off_reduction (const itype * type) static
Definition at line 7186 of file item.cpp.
 {
     int barrel_percentage = type->gun->barrel_volume / ( type->volume / 100 );
     return ( type->longest_side / 100 ) * barrel_percentage;
 }
Referenced by item::barrel_length(), and item::length().
shelf_life_less_than_each_component()
static bool shelf_life_less_than_each_component (const item & craft) static
Definition at line 485 of file item.cpp.
 {
     for( const item_components::type_vector_pair &tvp : craft.components ) {
         if( !tvp.second.front().goes_bad() || !tvp.second.front().is_comestible() ) {
             // they're all the same type, so this should be the same for all
             continue;
         }
         for( const item &it : tvp.second ) {
             if( it.get_shelf_life() < craft.get_shelf_life() ) {
                 return false;
             }
         }
     }
     return true;
 }
References anonymous_namespace{item_tname.cpp}::craft(), and item::get_shelf_life().
Referenced by inherit_rot_from_components().
USED_BY_IDS()
static const std::string USED_BY_IDS ("USED_BY_IDS") static
Referenced by item::already_used_by_player(), and item::mark_as_used_by_player().
vol_to_info()
iteminfo vol_to_info (const std::string & type, const std::string & left, const units::volume & vol, int decimal_places, bool lower_is_better)
Definition at line 12417 of file item.cpp.
 {
     iteminfo::flags f = iteminfo::no_newline;
     if( lower_is_better ) {
         f |= iteminfo::lower_is_better;
     }
     int converted_volume_scale = 0;
     const double converted_volume =
         round_up( convert_volume( vol.value(), &converted_volume_scale ), decimal_places );
     if( converted_volume_scale != 0 ) {
         f |= iteminfo::is_decimal;
     }
     return iteminfo( type, left, string_format( "<num> %s", volume_units_abbr() ), f,
                      converted_volume );
 }
References convert_volume(), iteminfo::is_decimal, keycode::left, iteminfo::lower_is_better, iteminfo::no_newline, round_up(), string_format(), units::quantity< V, U >::value(), and volume_units_abbr().
Referenced by pocket_favorite_callback::add_pockets(), item::basic_info(), item::contents_info(), item_pocket::contents_info(), inventory_selector::drag_drop_item(), item_pocket::general_info(), and item_contents::info().
weight_to_info()
iteminfo weight_to_info (const std::string & type, const std::string & left, const units::mass & weight, int decimal_places, bool lower_is_better)
Definition at line 12434 of file item.cpp.
 {
     iteminfo::flags f = iteminfo::no_newline;
     if( lower_is_better ) {
         f |= iteminfo::lower_is_better;
     }
     const double converted_weight = convert_weight( weight );
     f |= iteminfo::is_decimal;
     return iteminfo( type, left, string_format( "<num> %s", weight_units() ), f,
                      converted_weight );
 }
References convert_weight(), iteminfo::is_decimal, keycode::left, iteminfo::lower_is_better, iteminfo::no_newline, string_format(), and weight_units().
Referenced by item::basic_info(), item_pocket::contents_info(), item_pocket::general_info(), and item_contents::info().
Variable Documentation
ammo_battery
const ammotype ammo_battery("battery") ("battery") static
Referenced by item::allow_crafting_component(), item::ammo_consume(), item::charge_linked_batteries(), item::getlight_emit(), and item::is_battery().
ammo_bolt
const ammotype ammo_bolt("bolt") ("bolt") static
Referenced by item::gun_type().
ammo_money
const ammotype ammo_money("money") ("money") static
Referenced by item::is_money().
ammo_plutonium
const ammotype ammo_plutonium("plutonium") ("plutonium") static
Referenced by item::reload_option::qty(), and item::reload().
bio_digestion
const bionic_id bio_digestion("bio_digestion") ("bio_digestion") static
Referenced by item::rot_info().
bodygraph_full_body_iteminfo
const bodygraph_id bodygraph_full_body_iteminfo("full_body_iteminfo") ("full_body_iteminfo") static
Referenced by item::armor_info().
damage_acid
const damage_type_id damage_acid("acid") ("acid") static
Referenced by item::armor_protection_info(), and item::get_clothing_mod_val_for_damage_type().
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by item::damage_melee(), and item::get_clothing_mod_val_for_damage_type().
damage_bullet
const damage_type_id damage_bullet("bullet") ("bullet") static
Referenced by item::get_clothing_mod_val_for_damage_type().
damage_cut
const damage_type_id damage_cut("cut") ("cut") static
Referenced by item::get_clothing_mod_val_for_damage_type().
damage_heat
const damage_type_id damage_heat("heat") ("heat") static
Referenced by item::armor_protection_info(), and item::get_clothing_mod_val_for_damage_type().
dps_comp_monsters
const std::vector<std::pair<translation, dps_comp_data> > dps_comp_monsters static
Initial value:
= {
    { to_translation( "Best" ), { pseudo_debug_mon, true, false } },
    { to_translation( "Vs. Agile" ), { mon_zombie_smoker, true, true } },
    { to_translation( "Vs. Armored" ), { mon_zombie_soldier_no_weakpoints, true, true } },
    { to_translation( "Vs. Mixed" ), { mon_zombie_survivor_no_weakpoints, false, true } },
}
Definition at line 2350 of file item.cpp.
Referenced by item::dps().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by item::on_wear().
effect_cig
const efftype_id effect_cig("cig") ("cig") static
Referenced by item::process_litcig().
effect_shakes
const efftype_id effect_shakes("shakes") ("shakes") static
Referenced by item::process_litcig().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by item::process_litcig().
effect_weed_high
const efftype_id effect_weed_high("weed_high") ("weed_high") static
Referenced by item::process_litcig().
fault_overheat_safety
const fault_id fault_overheat_safety("fault_overheat_safety") ("fault_overheat_safety") static
Referenced by item::overheat_symbol(), and item::process_gun_cooling().
furn_f_metal_smoking_rack_active
const furn_str_id furn_f_metal_smoking_rack_active("f_metal_smoking_rack_active") ("f_metal_smoking_rack_active") static
Referenced by item::process_fake_smoke().
furn_f_smoking_rack_active
const furn_str_id furn_f_smoking_rack_active("f_smoking_rack_active") ("f_smoking_rack_active") static
Referenced by item::process_fake_smoke().
furn_f_water_mill_active
const furn_str_id furn_f_water_mill_active("f_water_mill_active") ("f_water_mill_active") static
Referenced by item::process_fake_mill().
furn_f_wind_mill_active
const furn_str_id furn_f_wind_mill_active("f_wind_mill_active") ("f_wind_mill_active") static
Referenced by item::process_fake_mill().
gun_mode_REACH
const gun_mode_id gun_mode_REACH("REACH") ("REACH") static
Referenced by item::gun_all_modes().
hits_by_accuracy
constexpr std::array<double, 41> hits_by_accuracy static constexpr
Initial value:
= {
    0,    1,   2,   3,   7,
    13,   26,  47,   82,  139,
    228,   359,  548,  808, 1151,
    1587, 2119, 2743, 3446, 4207,
    5000,
    5793, 6554, 7257, 7881, 8413,
    8849, 9192, 9452, 9641, 9772,
    9861, 9918, 9953, 9974, 9987,
    9993, 9997, 9998, 9999, 10000
}
Definition at line 2229 of file item.cpp.
Referenced by item::effective_dps().
item_category_container
const item_category_id item_category_container("container") ("container") static
Referenced by item::aggregated_contents(), item::get_category_of_contents(), item::info(), and item::this_or_single_content().
item_category_drugs
const item_category_id item_category_drugs("drugs") ("drugs") static
item_category_food
const item_category_id item_category_food("food") ("food") static
item_category_maps
const item_category_id item_category_maps("maps") ("maps") static
Referenced by item::is_map().
item_category_spare_parts
const item_category_id item_category_spare_parts("spare_parts") ("spare_parts") static
Referenced by item::is_maybe_melee_weapon().
item_category_tools
const item_category_id item_category_tools("tools") ("tools") static
Referenced by item::is_maybe_melee_weapon().
item_category_weapons
const item_category_id item_category_weapons("weapons") ("weapons") static
Referenced by item::is_maybe_melee_weapon().
itype_arredondo_chute
const itype_id itype_arredondo_chute("arredondo_chute") ("arredondo_chute") static
Referenced by item::is_gunmod_compatible().
itype_barrel_small
const itype_id itype_barrel_small("barrel_small") ("barrel_small") static
Referenced by anonymous_namespace{item.cpp}::_stacks_weapon_mods(), item::barrel_length(), item::length(), item::volume(), and item::weight().
itype_battery
const itype_id itype_battery("battery") ("battery") static
Referenced by item::charge_linked_batteries(), and item::energy_remaining().
itype_blood
const itype_id itype_blood("blood") ("blood") static
Referenced by item::type_name().
itype_brass_catcher
const itype_id itype_brass_catcher("brass_catcher") ("brass_catcher") static
Referenced by item::is_gunmod_compatible().
itype_bullet_crossbow
const itype_id itype_bullet_crossbow("bullet_crossbow") ("bullet_crossbow") static
Referenced by item::gun_type().
itype_cash_card
const itype_id itype_cash_card("cash_card") ("cash_card") static
Referenced by item::is_cash_card().
itype_cig_butt
const itype_id itype_cig_butt("cig_butt") ("cig_butt") static
Referenced by item::process_extinguish(), and item::process_litcig().
itype_cig_lit
const itype_id itype_cig_lit("cig_lit") ("cig_lit") static
Referenced by item::process_extinguish(), and item::process_litcig().
itype_cigar_butt
const itype_id itype_cigar_butt("cigar_butt") ("cigar_butt") static
Referenced by item::process_extinguish(), and item::process_litcig().
itype_cigar_lit
const itype_id itype_cigar_lit("cigar_lit") ("cigar_lit") static
Referenced by item::process_extinguish(), and item::process_litcig().
itype_disassembly
const itype_id itype_disassembly("disassembly") ("disassembly") static
Referenced by item::basic_info(), item::disassembly_info(), and item::is_disassemblable().
itype_hand_crossbow
const itype_id itype_hand_crossbow("hand_crossbow") ("hand_crossbow") static
Referenced by item::is_gunmod_compatible().
itype_joint_roach
const itype_id itype_joint_roach("joint_roach") ("joint_roach") static
Referenced by item::process_extinguish(), and item::process_litcig().
itype_null
const itype_id itype_null("null") ("null") static
Referenced by item::in_its_container().
itype_power_cord
const itype_id itype_power_cord("power_cord") ("power_cord") static
Referenced by item::link_to().
itype_rad_badge
const itype_id itype_rad_badge("rad_badge") ("rad_badge") static
Referenced by item::armor_fit_info().
itype_rm13_armor
const itype_id itype_rm13_armor("rm13_armor") ("rm13_armor") static
Referenced by item::armor_info().
itype_stock_none
const itype_id itype_stock_none("stock_none") ("stock_none") static
Referenced by item::is_gunmod_compatible(), and item::weight().
itype_tuned_mechanism
const itype_id itype_tuned_mechanism("tuned_mechanism") ("tuned_mechanism") static
Referenced by item::is_gunmod_compatible().
itype_water
const itype_id itype_water("water") ("water") static
Referenced by item::set_temp_flags().
itype_water_clean
const itype_id itype_water_clean("water_clean") ("water_clean") static
Referenced by item::set_temp_flags().
itype_waterproof_gunmod
const itype_id itype_waterproof_gunmod("waterproof_gunmod") ("waterproof_gunmod") static
Referenced by item::is_gunmod_compatible().
json_flag_CANNIBAL
const json_character_flag json_flag_CANNIBAL("CANNIBAL") ("CANNIBAL") static
Referenced by item::food_info().
json_flag_IMMUNE_SPOIL
const json_character_flag json_flag_IMMUNE_SPOIL("IMMUNE_SPOIL") ("IMMUNE_SPOIL") static
Referenced by item::rot_info().
json_flag_PSYCHOPATH
const json_character_flag json_flag_PSYCHOPATH("PSYCHOPATH") ("PSYCHOPATH") static
Referenced by item::food_info().
json_flag_SAPIOVORE
const json_character_flag json_flag_SAPIOVORE("SAPIOVORE") ("SAPIOVORE") static
Referenced by item::food_info().
material_wool
const material_id material_wool("wool") ("wool") static
Referenced by item::color_in_inventory().
MIN_LINK_EFFICIENCY
constexpr float MIN_LINK_EFFICIENCY = 0.001f static constexpr
Definition at line 232 of file item.cpp.
Referenced by item::ammo_consume(), item::ammo_remaining(), item::process_link(), and item::update_link_traits().
mon_human
const mtype_id mon_human("mon_human") ("mon_human") static
Referenced by item::process_corpse().
mon_zombie_smoker
const mtype_id mon_zombie_smoker("mon_zombie_smoker") ("mon_zombie_smoker") static
mon_zombie_soldier_no_weakpoints
const mtype_id mon_zombie_soldier_no_weakpoints("mon_zombie_soldier_no_weakpoints") ("mon_zombie_soldier_no_weakpoints") static
mon_zombie_survivor_no_weakpoints
const mtype_id mon_zombie_survivor_no_weakpoints("mon_zombie_survivor_no_weakpoints") ("mon_zombie_survivor_no_weakpoints") static
morale_null
const morale_type morale_null("morale_null") ("morale_null") static
Referenced by item::color_in_inventory(), and item::food_info().
nolight
light_emission nolight = {0, 0, 0}
Definition at line 238 of file item.cpp.
Referenced by item::io().
PRICE_FILTHY_MALUS
const int PRICE_FILTHY_MALUS = 100 static
Definition at line 230 of file item.cpp.
Referenced by item::price_no_contents().
pseudo_debug_mon
const mtype_id pseudo_debug_mon("pseudo_debug_mon") ("pseudo_debug_mon") static
qual_BOIL
const quality_id qual_BOIL("BOIL") ("BOIL") static
Referenced by item::get_quality(), and item::get_quality_nonrecursive().
qual_JACK
const quality_id qual_JACK("JACK") ("JACK") static
Referenced by item::qualities_info().
qual_LIFT
const quality_id qual_LIFT("LIFT") ("LIFT") static
Referenced by item::qualities_info().
RAPID
const matec_id RAPID("RAPID") ("RAPID") static
Referenced by item::effective_dps().
skill_cooking
const skill_id skill_cooking("cooking") ("cooking") static
Referenced by item::rot_info().
skill_melee
const skill_id skill_melee("melee") ("melee") static
Referenced by item::melee_combat_info().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by item::food_info().
skill_weapon
const skill_id skill_weapon("weapon") ("weapon") static
Referenced by item::contextualize_skill().
species_ROBOT
const species_id species_ROBOT("ROBOT") ("ROBOT") static
Referenced by item::process_corpse().
sub_body_part_torso_lower
const sub_bodypart_str_id sub_body_part_torso_lower("torso_lower") ("torso_lower") static
Referenced by item::get_layer().
sub_body_part_torso_upper
const sub_bodypart_str_id sub_body_part_torso_upper("torso_upper") ("torso_upper") static
Referenced by item::get_layer().
trait_CARNIVORE
const trait_id trait_CARNIVORE("CARNIVORE") ("CARNIVORE") static
Referenced by item::food_info().
trait_JITTERY
const trait_id trait_JITTERY("JITTERY") ("JITTERY") static
Referenced by item::process_litcig().
trait_LIGHTWEIGHT
const trait_id trait_LIGHTWEIGHT("LIGHTWEIGHT") ("LIGHTWEIGHT") static
Referenced by item::process_litcig().
trait_TOLERANCE
const trait_id trait_TOLERANCE("TOLERANCE") ("TOLERANCE") static
Referenced by item::process_litcig().
trait_WOOLALLERGY
const trait_id trait_WOOLALLERGY("WOOLALLERGY") ("WOOLALLERGY") static
Referenced by item::color_in_inventory().
vitamin_human_flesh_vitamin
const vitamin_id vitamin_human_flesh_vitamin("human_flesh_vitamin") ("human_flesh_vitamin") static
Referenced by item::food_info().