Cataclysm DDA: src/item_tname.cpp File Reference
item_tname.cpp File Reference
#include "item_tname.h"
#include <set>
#include <string>
#include <vector>
#include "avatar.h"
#include "cata_utility.h"
#include "color.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "debug.h"
#include "enums.h"
#include "fault.h"
#include "flag.h"
#include "flat_set.h"
#include "item.h"
#include "item_category.h"
#include "item_contents.h"
#include "item_pocket.h"
#include "itype.h"
#include "map.h"
#include "options.h"
#include "point.h"
#include "recipe.h"
#include "relic.h"
#include "string_formatter.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
Namespaces
anonymous_namespace{item_tname.cpp}
tname
Typedefs
using segment_bitset = tname::segment_bitset
using anonymous_namespace{item_tname.cpp}::decl_f_print_segment = std::string(item const &it, unsigned int quantity, segment_bitset const &segments)
Functions
std::string anonymous_namespace{item_tname.cpp}::noop (item const &, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::faults (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::dirt_symbol (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::overheat_symbol (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::pre_asterisk (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::durability (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::wheel_diameter (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::burn (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::custom_item_prefix (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::custom_item_suffix (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::label (item const &it, unsigned int quantity, segment_bitset const &segments)
std::string anonymous_namespace{item_tname.cpp}::mods (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::craft (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::wbl_mark (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::contents (item const &it, unsigned int, segment_bitset const &segments)
std::string anonymous_namespace{item_tname.cpp}::food_traits (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::location_hint (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::ethereal (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::food_status (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::food_irradiated (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::temperature (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::clothing_size (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::filthy (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::tags (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::vars (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::segment_broken (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::cbm_status (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::ups (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::wetness (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::active (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::sealed (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::post_asterisk (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::weapon_mods (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::relic_charges (item const &it, unsigned int, segment_bitset const &)
std::string anonymous_namespace{item_tname.cpp}::category (item const &it, unsigned int quantity, segment_bitset const &segments)
constexpr std::array< decl_f_print_segment *, num_segments > anonymous_namespace{item_tname.cpp}::get_segs_array ()
constexpr bool anonymous_namespace{item_tname.cpp}::all_segments_have_printers ()
std::string tname::print_segment (tname::segments segment, item const &it, unsigned int quantity, segment_bitset const &segments)
Variables
static const itype_id itype_barrel_small ("barrel_small")
static const itype_id itype_disassembly ("disassembly")
static const skill_id skill_survival ("survival")
constexpr size_t anonymous_namespace{item_tname.cpp}::num_segments = static_cast<size_t>(tname::segments::last_segment)
Typedef Documentation
segment_bitset
using segment_bitset = tname::segment_bitset
Definition at line 38 of file item_tname.cpp.
Variable Documentation
itype_barrel_small
const itype_id itype_barrel_small("barrel_small") ("barrel_small") static
Referenced by anonymous_namespace{item_tname.cpp}::weapon_mods().
itype_disassembly
const itype_id itype_disassembly("disassembly") ("disassembly") static
Referenced by anonymous_namespace{item_tname.cpp}::craft().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by anonymous_namespace{item_tname.cpp}::food_traits().