Cataclysm DDA: src/item_components.cpp File Reference
item_components.cpp File Reference
#include "item_components.h"
#include "flag.h"
#include "item.h"
#include "itype.h"
#include "type_id.h"
Functions
static void adjust_new_comp (item &new_comp, bool is_cooked)
Function Documentation
adjust_new_comp()
static void adjust_new_comp (item & new_comp, bool is_cooked) static
Definition at line 111 of file item_components.cpp.
 {
     if( new_comp.is_comestible() && !new_comp.get_comestible()->cooks_like.is_empty() ) {
         const double relative_rot = new_comp.get_relative_rot();
         new_comp = item( new_comp.get_comestible()->cooks_like, new_comp.birthday(), new_comp.charges );
         new_comp.set_relative_rot( relative_rot );
     }
     if( is_cooked ) {
         new_comp.set_flag_recursive( flag_COOKED );
     }
 }
References item::birthday(), item::charges, flag_COOKED, item::get_comestible(), item::get_relative_rot(), item::is_comestible(), item::set_flag_recursive(), and item::set_relative_rot().
Referenced by item_components::split().