Cataclysm DDA: src/item_factory.cpp File Reference
item_factory.cpp File Reference
#include "item_factory.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdio>
#include <iterator>
#include <limits>
#include <memory>
#include <optional>
#include <stdexcept>
#include <unordered_set>
#include "ammo.h"
#include "assign.h"
#include "bodypart.h"
#include "cached_options.h"
#include "calendar.h"
#include "cata_assert.h"
#include "cata_scope_helpers.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "color.h"
#include "damage.h"
#include "debug.h"
#include "effect_on_condition.h"
#include "enum_conversions.h"
#include "enums.h"
#include "explosion.h"
#include "flag.h"
#include "flat_set.h"
#include "game_constants.h"
#include "generic_factory.h"
#include "init.h"
#include "input.h"
#include "item.h"
#include "item_contents.h"
#include "item_group.h"
#include "iuse_actor.h"
#include "material.h"
#include "options.h"
#include "pocket_type.h"
#include "proficiency.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "relic.h"
#include "requirements.h"
#include "ret_val.h"
#include "stomach.h"
#include "string_formatter.h"
#include "text_snippets.h"
#include "translations.h"
#include "try_parse_integer.h"
#include "ui.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vitamin.h"
Classes
class iuse_function_wrapper
class iuse_function_wrapper_with_info
struct enum_traits< grip_val >
struct enum_traits< length_val >
struct enum_traits< surface_val >
struct enum_traits< balance_val >
struct io::acc_data
Namespaces
io
Enumerations
enum class grip_val : int {
BAD = 0 , NONE = 1 , SOLID = 2 , WEAPON = 3 ,
LAST = 4
}
enum class length_val : int { HAND = 0 , SHORT = 1 , LONG = 2 , LAST = 3 }
enum class surface_val : int {
POINT = 0 , LINE = 1 , ANY = 2 , EVERY = 3 ,
LAST = 4
}
enum class balance_val : int {
CLUMSY = 0 , UNEVEN = 1 , NEUTRAL = 2 , GOOD = 3 ,
LAST = 4
}
Functions
static item_category_id calc_category (const itype &obj)
static void hflesh_to_flesh (itype &item_template)
bool item_is_blacklisted (const itype_id &id)
static void assign (const JsonObject &jo, const std::string_view name, std::map< gun_mode_id, gun_modifier_data > &mods)
static bool assign_coverage_from_json (const JsonObject &jo, const std::string &key, body_part_set &parts)
static bool assign_coverage_from_json (const JsonObject &jo, const std::string &key, std::optional< body_part_set > &parts)
static bool is_physical (const itype &type)
static void load_memory_card_data (memory_card_info &mcd, const JsonObject &jo)
template<>
std::string io::enum_to_string< layer_level > (layer_level data)
template<typename T >
static void apply_optional (T &value, const std::optional< T > &applied)
template<typename T >
static void get_optional (const JsonObject &jo, bool was_loaded, const std::string &member, std::optional< T > &value)
template<typename T >
static void get_relative (const JsonObject &jo, const std::string_view member, std::optional< T > &value, T default_val)
template<typename T >
static void get_proportional (const JsonObject &jo, const std::string_view member, std::optional< T > &value, T default_val)
static bool has_pocket_type (const std::vector< pocket_data > &data, pocket_type pk)
static bool has_only_special_pockets (const itype &def)
template<>
std::string io::enum_to_string< encumbrance_modifier > (encumbrance_modifier data)
template<>
std::string io::enum_to_string< link_state > (link_state data)
template<>
std::string io::enum_to_string< grip_val > (grip_val val)
template<>
std::string io::enum_to_string< length_val > (length_val val)
template<>
std::string io::enum_to_string< surface_val > (surface_val val)
template<>
std::string io::enum_to_string< balance_val > (balance_val val)
static void migrate_mag_from_pockets (itype &def)
static void replace_materials (const JsonObject &jo, itype &def)
static void apply_migration (const migration *migrant, item &obj)
static std::string to_string (Item_group::Type t)
static Item_group * make_group_or_throw (const item_group_id &group_id, std::unique_ptr< Item_spawn_data > &isd, Item_group::Type t, int ammo_chance, int magazine_chance, const std::string &context)
template<typename T >
bool load_min_max (std::pair< T, T > &pa, const JsonObject &obj, const std::string &name)
template<typename T >
bool load_str_arr (std::vector< T > &arr, const JsonObject &obj, const std::string_view name)
template<>
std::string io::enum_to_string< phase_id > (phase_id data)
Variables
static const ammotype ammo_NULL ("NULL")
static const damage_type_id damage_bash ("bash")
static const damage_type_id damage_bullet ("bullet")
static const flag_id json_flag_NO_RELOAD ("NO_RELOAD")
static const flag_id json_flag_NO_UNLOAD ("NO_UNLOAD")
static const gun_mode_id gun_mode_DEFAULT ("DEFAULT")
static const gun_mode_id gun_mode_MELEE ("MELEE")
static const item_category_id item_category_ammo ("ammo")
static const item_category_id item_category_bionics ("bionics")
static const item_category_id item_category_books ("books")
static const item_category_id item_category_clothing ("clothing")
static const item_category_id item_category_drugs ("drugs")
static const item_category_id item_category_food ("food")
static const item_category_id item_category_guns ("guns")
static const item_category_id item_category_magazines ("magazines")
static const item_category_id item_category_mods ("mods")
static const item_category_id item_category_other ("other")
static const item_category_id item_category_tools ("tools")
static const item_category_id item_category_veh_parts ("veh_parts")
static const item_category_id item_category_weapons ("weapons")
static const item_group_id Item_spawn_data_EMPTY_GROUP ("EMPTY_GROUP")
static const material_id material_bean ("bean")
static const material_id material_blood ("blood")
static const material_id material_bone ("bone")
static const material_id material_bread ("bread")
static const material_id material_cheese ("cheese")
static const material_id material_dried_vegetable ("dried_vegetable")
static const material_id material_egg ("egg")
static const material_id material_flesh ("flesh")
static const material_id material_fruit ("fruit")
static const material_id material_garlic ("garlic")
static const material_id material_hblood ("hblood")
static const material_id material_hflesh ("hflesh")
static const material_id material_honey ("honey")
static const material_id material_hydrocarbons ("hydrocarbons")
static const material_id material_iflesh ("iflesh")
static const material_id material_junk ("junk")
static const material_id material_milk ("milk")
static const material_id material_mushroom ("mushroom")
static const material_id material_nut ("nut")
static const material_id material_oil ("oil")
static const material_id material_tomato ("tomato")
static const material_id material_veggy ("veggy")
static const material_id material_wheat ("wheat")
static const material_id material_wool ("wool")
static const quality_id qual_GUN ("GUN")
static const skill_id skill_pistol ("pistol")
static const skill_id skill_rifle ("rifle")
static const skill_id skill_shotgun ("shotgun")
static const skill_id skill_smg ("smg")
static item_blacklist_t item_blacklist
static DynamicDataLoader::deferred_json deferred
std::unique_ptr< Item_factory > item_controller = std::make_unique<Item_factory>()
Enumeration Type Documentation
balance_val
enum balance_val : int strong
Enumerator
CLUMSY
UNEVEN
NEUTRAL
GOOD
LAST
Definition at line 3907 of file item_factory.cpp.
                        : int {
     CLUMSY = 0,
     UNEVEN = 1,
     NEUTRAL = 2,
     GOOD = 3,
     LAST = 4
 };
grip_val
enum grip_val : int strong
Enumerator
BAD
NONE
SOLID
WEAPON
LAST
Definition at line 3875 of file item_factory.cpp.
                     : int {
     BAD = 0,
     NONE = 1,
     SOLID = 2,
     WEAPON = 3,
     LAST = 4
 };
length_val
enum length_val : int strong
Enumerator
HAND
SHORT
LONG
LAST
Definition at line 3886 of file item_factory.cpp.
                       : int {
     HAND = 0,
     SHORT = 1,
     LONG = 2,
     LAST = 3
 };
surface_val
enum surface_val : int strong
Enumerator
POINT
LINE
ANY
EVERY
LAST
Definition at line 3896 of file item_factory.cpp.
                        : int {
     POINT = 0,
     LINE = 1,
     ANY = 2,
     EVERY = 3,
     LAST = 4
 };
Function Documentation
apply_migration()
static void apply_migration (const migration * migrant, item & obj) static
Definition at line 4600 of file item_factory.cpp.
 {
     if( migrant->reset_item_vars ) {
         obj.clear_vars();
         for( const auto &pair : migrant->replace.obj().item_variables ) {
             obj.set_var( pair.first, pair.second ) ;
         }
     }
     for( const std::string &f : migrant->flags ) {
         obj.set_flag( flag_id( f ) );
     }
     if( migrant->charges > 0 ) {
         obj.charges = migrant->charges;
     }
     if( migrant->from_variant ) {
         obj.clear_itype_variant();
     }
     obj.set_itype_variant( migrant->variant );
     for( const migration::content &it : migrant->contents ) {
         int count = it.count;
         item content( it.id, obj.birthday(), 1 );
         if( content.count_by_charges() ) {
             content.charges = count;
             count = 1;
         }
         for( ; count > 0; --count ) {
             if( !obj.put_in( content, pocket_type::CONTAINER ).success() ) {
                 obj.put_in( content, pocket_type::MIGRATION );
             }
         }
     }
     if( !migrant->contents.empty() && migrant->sealed ) {
         obj.seal();
     }
 }
References item::birthday(), item::charges, migration::charges, item::clear_itype_variant(), item::clear_vars(), CONTAINER, migration::contents, migration::content::count, item::count_by_charges(), flag_id, migration::flags, migration::from_variant, migration::content::id, itype::item_variables, MIGRATION, string_id< T >::obj(), item::put_in(), migration::replace, migration::reset_item_vars, item::seal(), migration::sealed, item::set_flag(), item::set_itype_variant(), item::set_var(), ret_val_common::success(), and migration::variant.
Referenced by Item_factory::migrate_item(), and Item_factory::migrate_item_from_variant().
apply_optional()
template<typename T > static void apply_optional (T & value, const std::optional< T > & applied) static
Definition at line 2986 of file item_factory.cpp.
 {
     if( applied ) {
         value = *applied;
     }
 }
Referenced by islot_armor::load().
assign()
static void assign (const JsonObject & jo, const std::string_view name, std::map< gun_mode_id, gun_modifier_data > & mods) static
Definition at line 159 of file item_factory.cpp.
 {
     if( !jo.has_array( name ) ) {
         return;
     }
     mods.clear();
     for( JsonArray curr : jo.get_array( name ) ) {
         translation text;
         curr.read( 1, text );
         mods.emplace( gun_mode_id( curr.get_string( 0 ) ), gun_modifier_data( text,
                       curr.get_int( 2 ), curr.size() >= 4 ? curr.get_tags( 3 ) : std::set<std::string>() ) );
     }
 }
References JsonObject::get_array(), JsonObject::has_array(), anonymous_namespace{item_tname.cpp}::mods(), and om_direction::name().
Referenced by islot_ammo::load(), islot_seed::load(), Item_factory::load(), Item_factory::load_ammo(), Item_factory::load_basic_info(), Item_factory::load_comestible(), and Item_factory::load_migration().
assign_coverage_from_json() [1/2]
static bool assign_coverage_from_json (const JsonObject & jo, const std::string & key, body_part_set & parts) static
Definition at line 174 of file item_factory.cpp.
 {
     auto parse = [&parts]( const std::string & val ) {
         parts.set( bodypart_str_id( val ) );
     };
     if( jo.has_array( key ) ) {
         for( const std::string line : jo.get_array( key ) ) {
             parse( line );
         }
         return true;
     } else if( jo.has_string( key ) ) {
         parse( jo.get_string( key ) );
         return true;
     } else {
         return false;
     }
 }
References JsonObject::get_array(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_string(), line(), and body_part_set::set().
Referenced by assign_coverage_from_json(), armor_portion_data::deserialize(), and islot_armor::load().
assign_coverage_from_json() [2/2]
static bool assign_coverage_from_json (const JsonObject & jo, const std::string & key, std::optional< body_part_set > & parts) static
Definition at line 196 of file item_factory.cpp.
 {
     body_part_set temp;
     if( assign_coverage_from_json( jo, key, temp ) ) {
         parts = temp;
         return true;
     }
     return false;
 }
References assign_coverage_from_json(), and temp.
calc_category()
item_category_id calc_category (const itype & obj) static
Definition at line 5308 of file item_factory.cpp.
 {
     if( obj.gun && !obj.gunmod ) {
         return item_category_guns;
     }
     if( obj.magazine ) {
         return item_category_magazines;
     }
     if( obj.ammo ) {
         return item_category_ammo;
     }
     if( obj.tool ) {
         return item_category_tools;
     }
     if( obj.armor ) {
         return item_category_clothing;
     }
     if( obj.comestible ) {
         return obj.comestible->comesttype == "MED" ?
                item_category_drugs : item_category_food;
     }
     if( obj.book ) {
         return item_category_books;
     }
     if( obj.gunmod ) {
         return item_category_mods;
     }
     if( obj.bionic ) {
         return item_category_bionics;
     }
     bool weap = std::any_of( obj.melee.begin(), obj.melee.end(),
     []( const std::pair<const damage_type_id, float> &qty ) {
         return qty.second > MELEE_STAT;
     } );
     return weap ? item_category_weapons : item_category_other;
 }
References itype::ammo, itype::armor, itype::bionic, itype::book, itype::comestible, itype::gun, itype::gunmod, item_category_ammo, item_category_bionics, item_category_books, item_category_clothing, item_category_drugs, item_category_food, item_category_guns, item_category_magazines, item_category_mods, item_category_other, item_category_tools, item_category_weapons, itype::magazine, itype::melee, and itype::tool.
Referenced by Item_factory::finalize_pre().
get_optional()
template<typename T > static void get_optional (const JsonObject & jo, bool was_loaded, const std::string & member, std::optional< T > & value) static
Definition at line 2996 of file item_factory.cpp.
 {
     T tmp;
     if( value ) {
         tmp = *value;
     }
     optional( jo, was_loaded, member, tmp );
     if( jo.has_member( member ) ) {
         value = tmp;
     }
 }
References JsonObject::has_member(), member, and optional().
Referenced by islot_armor::load().
get_proportional()
template<typename T > static void get_proportional (const JsonObject & jo, const std::string_view member, std::optional< T > & value, T default_val) static
Definition at line 3020 of file item_factory.cpp.
 {
     if( jo.has_member( member ) ) {
         value = static_cast<T>( value.value_or( default_val ) * jo.get_float( member ) );
     }
 }
References JsonObject::get_float(), JsonObject::has_member(), and member.
Referenced by islot_armor::load().
get_relative()
template<typename T > static void get_relative (const JsonObject & jo, const std::string_view member, std::optional< T > & value, T default_val) static
Definition at line 3010 of file item_factory.cpp.
 {
     if( jo.has_member( member ) ) {
         value = static_cast<T>( value.value_or( default_val ) + jo.get_float( member ) );
     }
 }
References JsonObject::get_float(), JsonObject::has_member(), and member.
Referenced by islot_armor::load().
has_only_special_pockets()
static bool has_only_special_pockets (const itype & def) static
Definition at line 3752 of file item_factory.cpp.
 {
     // There are some places where we need to know whether any non-special
     // pockets have been added.  There might be no pockets, or there might be
     // just the special ones, depending on whether the definition is
     // copied-from another or not.
     if( def.pockets.empty() ) {
         return true;
     }
     const std::vector<pocket_type> special_pockets = { pocket_type::CORPSE, pocket_type::MOD, pocket_type::MIGRATION };
     for( const pocket_data &pocket : def.pockets ) {
         if( std::find( special_pockets.begin(), special_pockets.end(),
                        pocket.type ) == special_pockets.end() ) {
             return false;
         }
     }
     return true;
 }
References CORPSE, MIGRATION, MOD, itype::pockets, and pocket_data::type.
Referenced by Item_factory::check_and_create_magazine_pockets().
has_pocket_type()
static bool has_pocket_type (const std::vector< pocket_data > & data, pocket_type pk) static
Definition at line 3742 of file item_factory.cpp.
 {
     for( const pocket_data &pocket : data ) {
         if( pocket.type == pk ) {
             return true;
         }
     }
     return false;
 }
References pocket_data::type.
Referenced by Item_factory::add_special_pockets().
hflesh_to_flesh()
void hflesh_to_flesh (itype & item_template) static
Definition at line 3693 of file item_factory.cpp.
 {
     auto &mats = item_template.materials;
     const size_t old_size = mats.size();
     int ports = 0;
     for( auto mat = mats.begin(); mat != mats.end(); ) {
         if( mat->first == material_hflesh ) {
             ports += mat->second;
             mat = mats.erase( mat );
         } else {
             mat++;
         }
     }
     // Only add "flesh" material if not already present
     if( old_size != mats.size() &&
         mats.find( material_flesh ) == mats.end() ) {
         mats.emplace( "flesh", ports );
     }
 }
References material_flesh, material_hflesh, and itype::materials.
Referenced by Item_factory::finalize_pre().
is_physical()
static bool is_physical (const itype & type) static
Definition at line 208 of file item_factory.cpp.
 {
     return !type.has_flag( flag_AURA ) &&
            !type.has_flag( flag_CORPSE ) &&
            !type.has_flag( flag_IRREMOVABLE ) &&
            !type.has_flag( flag_NO_DROP ) &&
            !type.has_flag( flag_NO_UNWIELD ) &&
            !type.has_flag( flag_PERSONAL ) &&
            !type.has_flag( flag_PSEUDO ) &&
            !type.has_flag( flag_ZERO_WEIGHT );
 }
References flag_AURA, flag_CORPSE, flag_IRREMOVABLE, flag_NO_DROP, flag_NO_UNWIELD, flag_PERSONAL, flag_PSEUDO, flag_ZERO_WEIGHT, and type.
Referenced by Item_factory::check_definitions(), and Item_factory::finalize_pre().
item_is_blacklisted()
bool item_is_blacklisted (const itype_id & id)
Definition at line 154 of file item_factory.cpp.
 {
     return item_blacklist.blacklist.count( id );
 }
References item_blacklist_t::blacklist, and item_blacklist.
Referenced by map::_add_item_or_charges(), map::add_item(), Item_factory::check_definitions(), item::final_info(), vehicles::parts::finalize(), Item_factory::finalize_item_blacklist(), Item_factory::finalize_pre(), item_contents::magazine_compatible(), and map::spawn_item().
load_memory_card_data()
static void load_memory_card_data (memory_card_info & mcd, const JsonObject & jo) static
Definition at line 2644 of file item_factory.cpp.
 {
     mcd.data_chance = jo.get_float( "data_chance", 1.0f );
     mcd.on_read_convert_to = itype_id( jo.get_string( "on_read_convert_to" ) );
     mcd.photos_chance = jo.get_float( "photos_chance", 0.0f );
     mcd.photos_amount = jo.get_int( "photos_amount", 0 );
     mcd.songs_chance = jo.get_float( "songs_chance", 0.0f );
     mcd.songs_amount = jo.get_int( "songs_amount", 0 );
     mcd.recipes_chance = jo.get_float( "recipes_chance", 0.0f );
     mcd.recipes_amount = jo.get_int( "recipes_amount", 0 );
     mcd.recipes_level_min = jo.get_int( "recipes_level_min", 0 );
     mcd.recipes_level_max = jo.get_int( "recipes_level_max", 10 );
     mcd.recipes_categories.clear();
     if( jo.has_array( "recipes_categories" ) ) {
         for( const std::string &cat : jo.get_string_array( "recipes_categories" ) ) {
             mcd.recipes_categories.emplace( cat );
         }
     } else {
         mcd.recipes_categories = { "CC_FOOD" };
     }
     if( jo.has_member( "secret_recipes" ) ) {
         mcd.secret_recipes = jo.get_bool( "secret_recipes" );
     }
 }
References memory_card_info::data_chance, JsonObject::get_bool(), JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::get_string_array(), JsonObject::has_array(), JsonObject::has_member(), memory_card_info::on_read_convert_to, memory_card_info::photos_amount, memory_card_info::photos_chance, memory_card_info::recipes_amount, memory_card_info::recipes_categories, memory_card_info::recipes_chance, memory_card_info::recipes_level_max, memory_card_info::recipes_level_min, memory_card_info::secret_recipes, memory_card_info::songs_amount, and memory_card_info::songs_chance.
Referenced by Item_factory::load_basic_info().
load_min_max()
template<typename T > bool load_min_max (std::pair< T, T > & pa, const JsonObject & obj, const std::string & name)
Definition at line 4845 of file item_factory.cpp.
 {
     bool result = false;
     if( obj.has_array( name ) ) {
         // An array means first is min, second entry is max. Both are mandatory.
         JsonArray arr = obj.get_array( name );
         result |= arr.read_next( pa.first );
         result |= arr.read_next( pa.second );
     } else {
         // Not an array, should be a single numeric value, which is set as min and max.
         result |= obj.read( name, pa.first );
         result |= obj.read( name, pa.second );
     }
     result |= obj.read( name + "-min", pa.first );
     result |= obj.read( name + "-max", pa.second );
     return result;
 }
References JsonObject::get_array(), JsonObject::has_array(), om_direction::name(), JsonObject::read(), and JsonArray::read_next().
Referenced by Item_factory::add_entry().
load_str_arr()
template<typename T > bool load_str_arr (std::vector< T > & arr, const JsonObject & obj, const std::string_view name)
Definition at line 4864 of file item_factory.cpp.
 {
     if( obj.has_array( name ) ) {
         for( const std::string str : obj.get_array( name ) ) {
             arr.emplace_back( str );
         }
         return true;
     }
     return false;
 }
References JsonObject::get_array(), JsonObject::has_array(), and om_direction::name().
Referenced by Item_factory::add_entry().
make_group_or_throw()
static Item_group* make_group_or_throw (const item_group_id & group_id, std::unique_ptr< Item_spawn_data > & isd, Item_group::Type t, int ammo_chance, int magazine_chance, const std::string & context) static
Definition at line 4829 of file item_factory.cpp.
 {
     Item_group *ig = dynamic_cast<Item_group *>( isd.get() );
     if( ig == nullptr ) {
         isd.reset( ig = new Item_group( t, 100, ammo_chance, magazine_chance, context ) );
     } else if( ig->type != t ) {
         throw std::runtime_error(
             "item group \"" + group_id.str() + "\" already defined with type \"" +
             to_string( ig->type ) + "\"" );
     }
     return ig;
 }
References context, string_id< T >::str(), to_string(), and Item_group::type.
Referenced by Item_factory::load_item_group().
migrate_mag_from_pockets()
static void migrate_mag_from_pockets (itype & def) static
Definition at line 4067 of file item_factory.cpp.
 {
     for( const pocket_data &pocket : def.pockets ) {
         if( pocket.type == pocket_type::MAGAZINE_WELL ) {
             if( def.gun ) {
                 for( const ammotype &atype : def.gun->ammo ) {
                     def.magazine_default.emplace( atype, pocket.default_magazine );
                 }
             }
             if( def.magazine ) {
                 for( const ammotype &atype : def.magazine->type ) {
                     def.magazine_default.emplace( atype, pocket.default_magazine );
                 }
             }
             if( def.tool ) {
                 for( const ammotype &atype : def.tool->ammo_id ) {
                     def.magazine_default.emplace( atype, pocket.default_magazine );
                 }
             }
         }
     }
 }
References pocket_data::default_magazine, itype::gun, itype::magazine, itype::magazine_default, MAGAZINE_WELL, itype::pockets, itype::tool, and pocket_data::type.
Referenced by Item_factory::load_basic_info().
replace_materials()
static void replace_materials (const JsonObject & jo, itype & def) static
Definition at line 4090 of file item_factory.cpp.
 {
     // itterate through material replacements
     for( JsonMember jv : jo ) {
         material_id to_replace = material_id( jv.name() );
         material_id replacement = material_id( jv.get_string() );
         units::mass original_weight = def.weight;
         int mat_portion = def.materials[to_replace];
         // make repairs_with act the same way
         if( !def.repairs_with.empty() ) {
             const auto iter = def.repairs_with.find( to_replace );
             if( iter != def.repairs_with.end() ) {
                 def.repairs_with.erase( iter );
                 def.repairs_with.insert( replacement );
             }
         }
         // material is defined
         if( mat_portion != 0 ) {
             double mat_percent = static_cast<double>( mat_portion ) / static_cast<double>
                                  ( def.mat_portion_total );
             float density_percent = replacement->density() / to_replace->density();
             // add the portion for the replaced material
             def.materials[replacement] += mat_portion;
             // delete the old data
             def.materials.erase( to_replace );
             // change the weight relative
             units::mass material_weight = original_weight * mat_percent;
             units::mass weight_dif = material_weight * density_percent - material_weight;
             def.weight += weight_dif;
         }
         // update the armor defs
         if( def.armor ) {
             for( armor_portion_data &data : def.armor->sub_data ) {
                 std::vector<part_material>::iterator entry;
                 do {
                     entry = std::find_if( data.materials.begin(),
                     data.materials.end(), [to_replace]( const part_material & pm ) {
                         return pm.id == to_replace;
                     } );
                     if( entry != data.materials.end() ) {
                         entry->id = replacement;
                     }
                 } while( entry != data.materials.end() );
             }
         }
     }
 }
References itype::armor, material_type::density(), itype::mat_portion_total, armor_portion_data::materials, itype::materials, itype::repairs_with, replacement, and itype::weight.
Referenced by Item_factory::load_basic_info().
to_string()
static std::string to_string (Item_group::Type t) static
Definition at line 4817 of file item_factory.cpp.
 {
     switch( t ) {
         case Item_group::Type::G_COLLECTION:
             return "collection";
         case Item_group::Type::G_DISTRIBUTION:
             return "distribution";
     }
     return "BUGGED";
 }
Referenced by make_group_or_throw().
Variable Documentation
ammo_NULL
const ammotype ammo_NULL("NULL") ("NULL") static
Referenced by Item_factory::check_definitions().
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by Item_factory::load_basic_info().
damage_bullet
const damage_type_id damage_bullet("bullet") ("bullet") static
Referenced by Item_factory::finalize_pre().
deferred
DynamicDataLoader::deferred_json deferred static
Definition at line 124 of file item_factory.cpp.
Referenced by Item_factory::clear(), Item_factory::finalize(), and Item_factory::load_definition().
gun_mode_DEFAULT
const gun_mode_id gun_mode_DEFAULT("DEFAULT") ("DEFAULT") static
Referenced by Item_factory::finalize_pre().
gun_mode_MELEE
const gun_mode_id gun_mode_MELEE("MELEE") ("MELEE") static
Referenced by Item_factory::finalize_pre().
item_blacklist
item_blacklist_t item_blacklist static
Definition at line 122 of file item_factory.cpp.
Referenced by item_pocket::favorite_settings::accepts_item(), item_pocket::favorite_settings::blacklist_item(), Item_factory::clear(), item_pocket::favorite_settings::clear_item(), item_pocket::favorite_settings::deserialize(), Item_factory::finalize_item_blacklist(), item_pocket::favorite_settings::get_item_blacklist(), item_pocket::favorite_settings::info(), item_pocket::favorite_settings::is_null(), item_is_blacklisted(), Item_factory::load_item_blacklist(), and item_pocket::favorite_settings::whitelist_item().
item_category_ammo
const item_category_id item_category_ammo("ammo") ("ammo") static
Referenced by calc_category().
item_category_bionics
const item_category_id item_category_bionics("bionics") ("bionics") static
Referenced by calc_category().
item_category_books
const item_category_id item_category_books("books") ("books") static
Referenced by calc_category().
item_category_clothing
const item_category_id item_category_clothing("clothing") ("clothing") static
Referenced by calc_category().
item_category_drugs
const item_category_id item_category_drugs("drugs") ("drugs") static
Referenced by calc_category().
item_category_food
const item_category_id item_category_food("food") ("food") static
Referenced by calc_category().
item_category_guns
const item_category_id item_category_guns("guns") ("guns") static
Referenced by calc_category().
item_category_magazines
const item_category_id item_category_magazines("magazines") ("magazines") static
Referenced by calc_category().
item_category_mods
const item_category_id item_category_mods("mods") ("mods") static
Referenced by calc_category().
item_category_other
const item_category_id item_category_other("other") ("other") static
Referenced by calc_category().
item_category_tools
const item_category_id item_category_tools("tools") ("tools") static
Referenced by calc_category().
item_category_veh_parts
const item_category_id item_category_veh_parts("veh_parts") ("veh_parts") static
Referenced by Item_factory::load_basic_info().
item_category_weapons
const item_category_id item_category_weapons("weapons") ("weapons") static
Referenced by calc_category().
item_controller
std::unique_ptr<Item_factory> item_controller = std::make_unique<Item_factory>()
Definition at line 126 of file item_factory.cpp.
Referenced by explosion_handler::_make_explosion(), item::ammo_data(), jmapgen_liquid_item::apply(), jmapgen_spawn_item::apply(), item_action_generator::check_consistency(), DynamicDataLoader::check_consistency(), Single_item_creator::create(), Single_item_creator::create_single_without_container(), item_group::debug_spawn(), item::display_name(), npc::enough_time_to_reload(), Single_item_creator::every_item(), item_group::every_possible_item_from(), filter_recipes(), item::final_info(), recipe_dictionary::finalize(), requirement_data::finalize(), vehicles::parts::finalize(), DynamicDataLoader::finalize_loaded_data(), vehicles::finalize_prototypes(), Item_factory::find(), recipe_dictionary::find_items_on_loops(), item::find_type(), item_group::group_contains_item(), item_group::group_is_defined(), Single_item_creator::has_item(), DynamicDataLoader::initialize(), item::io(), item_group::item_from(), item_group::items_from(), jmapgen_loot::jmapgen_loot(), ma_style_callback::key(), item_group::load_item_group(), Item_modifier::modify(), memorial_logger::notify(), auto_pickup::rule_list::refresh_map_items(), repair_item_finish(), item_pocket::set_item_defaults(), gun_actor::shoot(), map::spawn_item(), auto_pickup::rule::test_pattern(), item::type_is_defined(), DynamicDataLoader::unload_data(), debug_menu::wishbionics(), and debug_menu::wishitem().
Item_spawn_data_EMPTY_GROUP
const item_group_id Item_spawn_data_EMPTY_GROUP("EMPTY_GROUP") ("EMPTY_GROUP") static
Referenced by Item_factory::init().
json_flag_NO_RELOAD
const flag_id json_flag_NO_RELOAD("NO_RELOAD") ("NO_RELOAD") static
json_flag_NO_UNLOAD
const flag_id json_flag_NO_UNLOAD("NO_UNLOAD") ("NO_UNLOAD") static
material_bean
const material_id material_bean("bean") ("bean") static
Referenced by Item_factory::set_allergy_flags().
material_blood
const material_id material_blood("blood") ("blood") static
Referenced by Item_factory::set_allergy_flags().
material_bone
const material_id material_bone("bone") ("bone") static
Referenced by Item_factory::set_allergy_flags().
material_bread
const material_id material_bread("bread") ("bread") static
Referenced by Item_factory::set_allergy_flags().
material_cheese
const material_id material_cheese("cheese") ("cheese") static
Referenced by Item_factory::set_allergy_flags().
material_dried_vegetable
const material_id material_dried_vegetable("dried_vegetable") ("dried_vegetable") static
Referenced by Item_factory::set_allergy_flags().
material_egg
const material_id material_egg("egg") ("egg") static
Referenced by Item_factory::set_allergy_flags().
material_flesh
const material_id material_flesh("flesh") ("flesh") static
Referenced by hflesh_to_flesh(), and Item_factory::set_allergy_flags().
material_fruit
const material_id material_fruit("fruit") ("fruit") static
Referenced by Item_factory::set_allergy_flags().
material_garlic
const material_id material_garlic("garlic") ("garlic") static
Referenced by Item_factory::set_allergy_flags().
material_hblood
const material_id material_hblood("hblood") ("hblood") static
Referenced by Item_factory::set_allergy_flags().
material_hflesh
const material_id material_hflesh("hflesh") ("hflesh") static
Referenced by hflesh_to_flesh(), and Item_factory::set_allergy_flags().
material_honey
const material_id material_honey("honey") ("honey") static
Referenced by Item_factory::set_allergy_flags().
material_hydrocarbons
const material_id material_hydrocarbons("hydrocarbons") ("hydrocarbons") static
Referenced by Item_factory::finalize_pre().
material_iflesh
const material_id material_iflesh("iflesh") ("iflesh") static
Referenced by Item_factory::set_allergy_flags().
material_junk
const material_id material_junk("junk") ("junk") static
Referenced by Item_factory::finalize_pre(), and Item_factory::set_allergy_flags().
material_milk
const material_id material_milk("milk") ("milk") static
Referenced by Item_factory::set_allergy_flags().
material_mushroom
const material_id material_mushroom("mushroom") ("mushroom") static
Referenced by Item_factory::set_allergy_flags().
material_nut
const material_id material_nut("nut") ("nut") static
Referenced by Item_factory::set_allergy_flags().
material_oil
const material_id material_oil("oil") ("oil") static
Referenced by Item_factory::finalize_pre().
material_tomato
const material_id material_tomato("tomato") ("tomato") static
Referenced by Item_factory::set_allergy_flags().
material_veggy
const material_id material_veggy("veggy") ("veggy") static
Referenced by Item_factory::set_allergy_flags().
material_wheat
const material_id material_wheat("wheat") ("wheat") static
Referenced by Item_factory::set_allergy_flags().
material_wool
const material_id material_wool("wool") ("wool") static
Referenced by Item_factory::set_allergy_flags().
qual_GUN
const quality_id qual_GUN("GUN") ("GUN") static
skill_pistol
const skill_id skill_pistol("pistol") ("pistol") static
Referenced by Item_factory::finalize_pre().
skill_rifle
const skill_id skill_rifle("rifle") ("rifle") static
Referenced by Item_factory::finalize_pre().
skill_shotgun
const skill_id skill_shotgun("shotgun") ("shotgun") static
Referenced by Item_factory::finalize_pre().
skill_smg
const skill_id skill_smg("smg") ("smg") static
Referenced by Item_factory::finalize_pre().