Cataclysm DDA: src/item.h File Reference
item.h File Reference
#include <algorithm>
#include <climits>
#include <cstdint>
#include <functional>
#include <iosfwd>
#include <list>
#include <map>
#include <new>
#include <optional>
#include <set>
#include <type_traits>
#include <utility>
#include <vector>
#include "calendar.h"
#include "cata_lazy.h"
#include "cata_utility.h"
#include "compatibility.h"
#include "enums.h"
#include "gun_mode.h"
#include "io_tags.h"
#include "item_components.h"
#include "item_contents.h"
#include "item_location.h"
#include "item_tname.h"
#include "material.h"
#include "requirements.h"
#include "safe_reference.h"
#include "type_id.h"
#include "units.h"
#include "value_ptr.h"
#include "visitable.h"
#include "vpart_position.h"
#include "rng.h"
Classes
struct light_emission
struct iteminfo
Value and metadata for one property of an item.
struct enum_traits< iteminfo::flags >
struct stacking_info
class item
struct item::default_charges_tag
Suppress randomization and always start with default quantity of charges.
struct item::solitary_tag
Default (or randomized) charges except if counted by charges then only one charge.
class item::reload_option
struct item::link_data
struct item::extended_photo_def
struct item::sound_data
struct item::aggregate_t
class item::craft_data
Data for items that represent in-progress crafts.
struct item::cat_cache
struct enum_traits< item::encumber_flags >
struct disp_mod_by_barrel
Namespaces
enchant_vals
Macros
#define CATA_SRC_ITEM_H
Typedefs
using bodytype_id = std::string
using faction_id = string_id< faction >
Enumerations
enum class hint_rating { good , iffy , cant }
Hint value used for item examination screen and filtering items by action.
Functions
iteminfo vol_to_info (const std::string &type, const std::string &left, const units::volume &vol, int decimal_places=2, bool lower_is_better=true)
iteminfo weight_to_info (const std::string &type, const std::string &left, const units::mass &weight, int decimal_places=2, bool lower_is_better=true)
bool is_crafting_component (const item &component)
Default filter for crafting component searches.
bool item_compare_by_charges (const item &left, const item &right)
bool item_ptr_compare_by_charges (const item *left, const item *right)
units::mass lifting_quality_to_mass (int quality_level)
item & null_item_reference ()
Returns a reference to a null item (see item::is_null).
bool is_preferred_component (const item &component)
Filter for crafting components first pass searches excluding undesirable properties.
Variables
light_emission nolight
constexpr units::mass TOOL_LIFT_FACTOR = 500_kilogram
Macro Definition Documentation
CATA_SRC_ITEM_H
#define CATA_SRC_ITEM_H
Definition at line 3 of file item.h.
Typedef Documentation
bodytype_id
using bodytype_id = std::string
Definition at line 78 of file item.h.
faction_id
using faction_id = string_id<faction>
Definition at line 79 of file item.h.
Enumeration Type Documentation
hint_rating
enum hint_rating strong
Hint value used for item examination screen and filtering items by action.
Represents whether an item permits given action (reload, wear, read, etc.).
Enumerator
good
Item permits this action.
iffy
Item permits this action, but circumstances don't.
cant
Item does not permit this action.
Definition at line 3241 of file item.h.
{
     /** Item permits this action */
     good,
     /** Item permits this action, but circumstances don't */
     iffy,
     /** Item does not permit this action */
     cant
 };
Function Documentation
is_crafting_component()
bool is_crafting_component (const item & component) inline
Default filter for crafting component searches.
Definition at line 3267 of file item.h.
 {
     return ( component.allow_crafting_component() || component.count_by_charges() ) &&
            !component.is_filthy();
 }
Referenced by are_requirements_nearby(), iexamine::autoclave_empty(), iexamine::autodoc(), iuse::break_stick(), can_do_activity_there(), veh_interact::can_potentially_install(), basecamp_action_components::choose_components(), veh_interact::complete_vehicle(), construction_activity(), construction_menu(), Character::consume_anesth_requirement(), basecamp_action_components::consume_components(), Character::consume_installation_requirement(), iexamine::cvdmachine(), wash_activity_actor::finish(), veh_interact::format_reqs(), recipe::get_component_filter(), butchery_requirements::get_fastest_requirements(), repair_item_actor::handle_components(), Character::has_enough_anesth(), Character::has_installation_requirement(), is_non_rotten_crafting_component(), Character::mend_item(), activity_handlers::mend_item_finish(), veh_utils::most_repairable_part(), iuse::multicooker(), iexamine::nanofab(), iuse::pack_cbm(), iexamine::pit(), place_construction(), player_can_build(), veh_app_interact::remove(), repair_inventory_preset::repair_inventory_preset(), repair_item_finish(), veh_utils::repair_part(), set_up_butchery(), sew_advanced_actor::use(), vehicle::use_dishwasher(), and vehicle::use_washing_machine().
is_preferred_component()
bool is_preferred_component (const item & component)
Filter for crafting components first pass searches excluding undesirable properties.
Definition at line 15190 of file item.cpp.
 {
     return component.is_container_empty() && !component.has_flag( flag_HIDDEN_POISON ) &&
            !component.has_flag( flag_HIDDEN_HALLU );
 }
References flag_HIDDEN_HALLU, and flag_HIDDEN_POISON.
Referenced by Character::consume_items(), and Character::select_item_component().
item_compare_by_charges()
bool item_compare_by_charges (const item & left, const item & right)
Definition at line 12512 of file item.cpp.
 {
     return item_ptr_compare_by_charges( &left, &right );
 }
References item_ptr_compare_by_charges(), keycode::left, and keycode::right.
item_ptr_compare_by_charges()
bool item_ptr_compare_by_charges (const item * left, const item * right)
Definition at line 12501 of file item.cpp.
 {
     if( left->empty() ) {
         return false;
     } else if( right->empty() ) {
         return true;
     } else {
         return right->only_item().charges < left->only_item().charges;
     }
 }
References keycode::left, and keycode::right.
Referenced by Character::check_eligible_containers_for_crafting(), and item_compare_by_charges().
lifting_quality_to_mass()
units::mass lifting_quality_to_mass (int quality_level) inline
Definition at line 3253 of file item.h.
 {
     return TOOL_LIFT_FACTOR * quality_level;
 }
References TOOL_LIFT_FACTOR.
Referenced by Character::best_nearby_lifting_assist(), veh_interact::cache_tool_availability(), veh_interact::calc_lift_requirements(), vpart_info::format_description(), jack_quality(), and item::qualities_info().
null_item_reference()
item& null_item_reference ()
Returns a reference to a null item (see item::is_null).
The reference is always valid and stays valid until the program ends.
Definition at line 248 of file item.cpp.
 {
     static item result{};
     // reset it, in case a previous caller has changed it
     result = item();
     return result;
 }
References item.
Referenced by map::_add_item_or_charges(), target_ui::action_aim_and_shoot(), map::add_item(), Creature::attack_air(), talker_character_const::attack_speed(), npc::average_damage_dealt(), Character::best_item_with_quality(), npc::check_or_use_weapon_cbm(), relic_procgen_data::create_item(), outfit::current_unarmed_weapon(), npc::decide_needs(), avatar::disarm(), construct::done_deconstruct(), npc::evaluate_best_attack(), npc::evaluate_best_weapon(), npc::evaluate_character(), Character::evaluate_techniques(), inventory::find_item(), item_contents::first_ammo(), item_contents::first_item(), npc::get_healing_item(), weldrig_hack::get_item(), Character::get_melee_hit_base(), Character::get_standard_stamina_cost(), talker_npc::give_item_to(), Character::hit_roll(), outfit::i_at(), item_contents::legacy_front(), item::loaded_ammo(), Character::melee_attack_abstract(), inventory::most_appropriate_painkiller(), item_contents::only_item(), item_stack::only_item(), avatar::rebuild_aim_cache(), npc::regen_ai_cache(), set_item_map(), Character::store(), stumble(), npc::value(), npc::wants_take_that(), npc::wield_better_weapon(), and memorial_logger::write_text_memorial().
vol_to_info()
iteminfo vol_to_info (const std::string & type, const std::string & left, const units::volume & vol, int decimal_places = 2, bool lower_is_better = true)
Definition at line 12417 of file item.cpp.
 {
     iteminfo::flags f = iteminfo::no_newline;
     if( lower_is_better ) {
         f |= iteminfo::lower_is_better;
     }
     int converted_volume_scale = 0;
     const double converted_volume =
         round_up( convert_volume( vol.value(), &converted_volume_scale ), decimal_places );
     if( converted_volume_scale != 0 ) {
         f |= iteminfo::is_decimal;
     }
     return iteminfo( type, left, string_format( "<num> %s", volume_units_abbr() ), f,
                      converted_volume );
 }
References convert_volume(), iteminfo::is_decimal, keycode::left, iteminfo::lower_is_better, iteminfo::no_newline, round_up(), string_format(), units::quantity< V, U >::value(), and volume_units_abbr().
Referenced by pocket_favorite_callback::add_pockets(), item::basic_info(), item::contents_info(), item_pocket::contents_info(), inventory_selector::drag_drop_item(), item_pocket::general_info(), and item_contents::info().
weight_to_info()
iteminfo weight_to_info (const std::string & type, const std::string & left, const units::mass & weight, int decimal_places = 2, bool lower_is_better = true)
Definition at line 12434 of file item.cpp.
 {
     iteminfo::flags f = iteminfo::no_newline;
     if( lower_is_better ) {
         f |= iteminfo::lower_is_better;
     }
     const double converted_weight = convert_weight( weight );
     f |= iteminfo::is_decimal;
     return iteminfo( type, left, string_format( "<num> %s", weight_units() ), f,
                      converted_weight );
 }
References convert_weight(), iteminfo::is_decimal, keycode::left, iteminfo::lower_is_better, iteminfo::no_newline, string_format(), and weight_units().
Referenced by item::basic_info(), item_pocket::contents_info(), item_pocket::general_info(), and item_contents::info().
Variable Documentation
nolight
light_emission nolight extern
Definition at line 238 of file item.cpp.
Referenced by item::io().
TOOL_LIFT_FACTOR
constexpr units::mass TOOL_LIFT_FACTOR = 500_kilogram constexpr
Definition at line 3251 of file item.h.
Referenced by lifting_quality_to_mass().