Cataclysm DDA: src/item_contents.cpp File Reference
item_contents.cpp File Reference
#include "item_contents.h"
#include <algorithm>
#include <iterator>
#include <map>
#include <string>
#include <type_traits>
#include "avatar.h"
#include "character.h"
#include "color.h"
#include "cursesdef.h"
#include "debug.h"
#include "enum_conversions.h"
#include "enums.h"
#include "flat_set.h"
#include "input.h"
#include "input_context.h"
#include "inventory.h"
#include "item.h"
#include "item_category.h"
#include "item_factory.h"
#include "item_location.h"
#include "item_pocket.h"
#include "iteminfo_query.h"
#include "itype.h"
#include "localized_comparator.h"
#include "make_static.h"
#include "map.h"
#include "output.h"
#include "point.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "ui.h"
#include "units.h"
Classes
class pocket_favorite_callback
struct item_contents::item_contents_helper
Functions
static void insert_separation_line (std::vector< iteminfo > &info)
void pocket_management_menu (const std::string &title, const std::vector< item * > &to_organize)
Variables
static const flag_id json_flag_CASING ("CASING")
Function Documentation
insert_separation_line()
static void insert_separation_line (std::vector< iteminfo > & info) static
Definition at line 2605 of file item_contents.cpp.
 {
     if( info.empty() || info.back().sName != "--" ) {
         info.emplace_back( "DESCRIPTION", "--" );
     }
 }
Referenced by item_contents::info().
pocket_management_menu()
void pocket_management_menu (const std::string & title, const std::vector< item * > & to_organize)
Definition at line 2696 of file item_contents.cpp.
 {
     static const std::string input_category = "INVENTORY";
     input_context ctxt( input_category );
     const std::string uilist_text = string_format(
                                         _( "Modify pocket settings and move items between pockets.  [<color_yellow>%s</color>] Context menu" ),
                                         ctxt.get_desc( "FAV_CONTEXT_MENU", 1 ) );
     uilist pocket_selector;
     pocket_favorite_callback cb( uilist_text, to_organize, pocket_selector );
     pocket_selector.title = title;
     pocket_selector.text = uilist_text;
     pocket_selector.callback = &cb;
     pocket_selector.w_x_setup = 0;
     pocket_selector.w_width_setup = []() {
         return TERMX;
     };
     pocket_selector.pad_right_setup = []() {
         return std::max( TERMX / 2, TERMX - 50 );
     };
     pocket_selector.w_y_setup = 0;
     pocket_selector.w_height_setup = []() {
         return TERMY;
     };
     pocket_selector.input_category = input_category;
     pocket_selector.additional_actions = {
         { "FAV_PRIORITY", translation() },
         { "FAV_AUTO_PICKUP", translation() },
         { "FAV_AUTO_UNLOAD", translation() },
         { "FAV_ITEM", translation() },
         { "FAV_CATEGORY", translation() },
         { "FAV_WHITELIST", translation() },
         { "FAV_BLACKLIST", translation() },
         { "FAV_CLEAR", translation() },
         { "FAV_MOVE_ITEM", translation() },
         { "FAV_CONTEXT_MENU", translation() },
         { "FAV_SAVE_PRESET", translation() },
         { "FAV_APPLY_PRESET", translation() },
         { "FAV_DEL_PRESET", translation() }
     };
     // Override CONFIRM with FAV_CONTEXT_MENU
     pocket_selector.allow_confirm = false;
     pocket_selector.allow_additional = true;
     pocket_selector.query();
 }
References _, uilist::additional_actions, uilist::allow_additional, uilist::allow_confirm, uilist::callback, input_context::get_desc(), uilist::input_category, max(), uilist::pad_right_setup, uilist::query(), string_format(), TERMX, TERMY, uilist::text, music::title, uilist::title, uilist::w_height_setup, uilist::w_width_setup, uilist::w_x_setup, and uilist::w_y_setup.
Referenced by item_contents::favorite_settings_menu(), and outfit::organize_items_menu().
Variable Documentation
json_flag_CASING
const flag_id json_flag_CASING("CASING") ("CASING") static
Referenced by item_contents::first_ammo().