Cataclysm DDA: src/item_contents.h File Reference
item_contents.h File Reference
#include <cstddef>
#include <functional>
#include <iosfwd>
#include <list>
#include <map>
#include <optional>
#include <set>
#include <utility>
#include <vector>
#include "enums.h"
#include "item_pocket.h"
#include "ret_val.h"
#include "type_id.h"
#include "units_fwd.h"
#include "visitable.h"
Classes
class item_contents
Macros
#define CATA_SRC_ITEM_CONTENTS_H
Enumerations
enum class content_newness { NEW , MIGHT_BE_HIDDEN , SEEN }
NEW!ness to player, if they seen such item already.
Functions
void pocket_management_menu (const std::string &title, const std::vector< item * > &to_organize)
Macro Definition Documentation
CATA_SRC_ITEM_CONTENTS_H
#define CATA_SRC_ITEM_CONTENTS_H
Definition at line 3 of file item_contents.h.
Enumeration Type Documentation
content_newness
enum content_newness strong
NEW!ness to player, if they seen such item already.
Enumerator
NEW
MIGHT_BE_HIDDEN
SEEN
Definition at line 31 of file item_contents.h.
{
     NEW,  // at least one item is new
     MIGHT_BE_HIDDEN,  // at least one item might be hidden and none are NEW
     SEEN
 };
Function Documentation
pocket_management_menu()
void pocket_management_menu (const std::string & title, const std::vector< item * > & to_organize)
Definition at line 2696 of file item_contents.cpp.
 {
     static const std::string input_category = "INVENTORY";
     input_context ctxt( input_category );
     const std::string uilist_text = string_format(
                                         _( "Modify pocket settings and move items between pockets.  [<color_yellow>%s</color>] Context menu" ),
                                         ctxt.get_desc( "FAV_CONTEXT_MENU", 1 ) );
     uilist pocket_selector;
     pocket_favorite_callback cb( uilist_text, to_organize, pocket_selector );
     pocket_selector.title = title;
     pocket_selector.text = uilist_text;
     pocket_selector.callback = &cb;
     pocket_selector.w_x_setup = 0;
     pocket_selector.w_width_setup = []() {
         return TERMX;
     };
     pocket_selector.pad_right_setup = []() {
         return std::max( TERMX / 2, TERMX - 50 );
     };
     pocket_selector.w_y_setup = 0;
     pocket_selector.w_height_setup = []() {
         return TERMY;
     };
     pocket_selector.input_category = input_category;
     pocket_selector.additional_actions = {
         { "FAV_PRIORITY", translation() },
         { "FAV_AUTO_PICKUP", translation() },
         { "FAV_AUTO_UNLOAD", translation() },
         { "FAV_ITEM", translation() },
         { "FAV_CATEGORY", translation() },
         { "FAV_WHITELIST", translation() },
         { "FAV_BLACKLIST", translation() },
         { "FAV_CLEAR", translation() },
         { "FAV_MOVE_ITEM", translation() },
         { "FAV_CONTEXT_MENU", translation() },
         { "FAV_SAVE_PRESET", translation() },
         { "FAV_APPLY_PRESET", translation() },
         { "FAV_DEL_PRESET", translation() }
     };
     // Override CONFIRM with FAV_CONTEXT_MENU
     pocket_selector.allow_confirm = false;
     pocket_selector.allow_additional = true;
     pocket_selector.query();
 }
References _, uilist::additional_actions, uilist::allow_additional, uilist::allow_confirm, uilist::callback, input_context::get_desc(), uilist::input_category, max(), uilist::pad_right_setup, uilist::query(), string_format(), TERMX, TERMY, uilist::text, music::title, uilist::title, uilist::w_height_setup, uilist::w_width_setup, uilist::w_x_setup, and uilist::w_y_setup.
Referenced by item_contents::favorite_settings_menu(), and outfit::organize_items_menu().