Cataclysm DDA: src/itype.h File Reference
itype.h File Reference
#include <array>
#include <cstddef>
#include <iosfwd>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <unordered_set>
#include <vector>
#include "bodypart.h"
#include "calendar.h"
#include "color.h"
#include "damage.h"
#include "enums.h"
#include "explosion.h"
#include "game_constants.h"
#include "item_pocket.h"
#include "iuse.h"
#include "mapdata.h"
#include "proficiency.h"
#include "relic.h"
#include "stomach.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "value_ptr.h"
Classes
class gun_modifier_data
class gunmod_location
struct islot_tool
struct islot_comestible
struct islot_brewable
struct islot_compostable
struct part_material
Material data for individual armor body parts.
struct enum_traits< encumbrance_modifier >
struct armor_portion_data
struct islot_armor
struct islot_pet_armor
struct islot_book
struct islot_book::recipe_with_description_t
What recipes can be learned from this book.
struct islot_mod
struct common_ranged_data
Common data for ranged things: guns, gunmods and ammo.
struct islot_engine
struct islot_wheel
struct enum_traits< itype_variant_kind >
struct itype_variant_data
struct islot_gun
class gun_type_type
The type of gun. The second "_type" suffix is only to distinguish it from item::gun_type.
struct std::hash< gun_type_type >
struct islot_gunmod
struct islot_magazine
struct islot_battery
struct islot_ammo
struct islot_bionic
struct islot_seed
struct enum_traits< condition_type >
struct conditional_name
class islot_milling
struct memory_card_info
struct itype
Macros
#define CATA_SRC_ITYPE_H
Enumerations
enum class encumbrance_modifier : int {
IMBALANCED = 0 , RESTRICTS_NECK , WELL_SUPPORTED , NONE ,
last
}
enum class encumbrance_modifier_type : int { MULT = 0 , FLAT , last }
enum class itype_variant_kind : int { gun , generic , drug , last }
enum condition_type {
FLAG , VITAMIN , COMPONENT_ID , COMPONENT_ID_SUBSTRING ,
VAR , SNIPPET_ID , num_condition_types
}
Functions
void load_charge_removal_blacklist (const JsonObject &jo, std::string_view src)
void load_temperature_removal_blacklist (const JsonObject &jo, std::string_view src)
Variables
constexpr float base_metabolic_rate
Macro Definition Documentation
CATA_SRC_ITYPE_H
#define CATA_SRC_ITYPE_H
Definition at line 3 of file itype.h.
Enumeration Type Documentation
condition_type
enum condition_type
Enumerator
FLAG
VITAMIN
COMPONENT_ID
COMPONENT_ID_SUBSTRING
VAR
SNIPPET_ID
num_condition_types
Definition at line 1128 of file itype.h.
                     {
     FLAG,
     VITAMIN,
     COMPONENT_ID,
     COMPONENT_ID_SUBSTRING,
     VAR,
     SNIPPET_ID,
     num_condition_types
 };
encumbrance_modifier
enum encumbrance_modifier : int strong
Enumerator
IMBALANCED
RESTRICTS_NECK
WELL_SUPPORTED
NONE
last
Definition at line 257 of file itype.h.
                                 : int {
     IMBALANCED = 0,
     RESTRICTS_NECK,
     WELL_SUPPORTED,
     NONE,
     last
 };
encumbrance_modifier_type
enum encumbrance_modifier_type : int strong
Enumerator
MULT
FLAT
last
Definition at line 271 of file itype.h.
                                      : int {
     MULT = 0,
     FLAT,
     last
 };
itype_variant_kind
enum itype_variant_kind : int strong
Enumerator
gun
generic
drug
last
Definition at line 655 of file itype.h.
                               : int {
     gun,
     generic,
     drug,
     last
 };
Function Documentation
load_charge_removal_blacklist()
void load_charge_removal_blacklist (const JsonObject & jo, std::string_view src)
Definition at line 2793 of file savegame_json.cpp.
 {
     jo.allow_omitted_members();
     std::set<itype_id> new_blacklist;
     jo.read( "list", new_blacklist );
     charge_removal_blacklist.insert( new_blacklist.begin(), new_blacklist.end() );
 }
References JsonObject::allow_omitted_members(), charge_removal_blacklist, and JsonObject::read().
Referenced by DynamicDataLoader::initialize().
load_temperature_removal_blacklist()
void load_temperature_removal_blacklist (const JsonObject & jo, std::string_view src)
Definition at line 2803 of file savegame_json.cpp.
 {
     jo.allow_omitted_members();
     std::set<itype_id> new_blacklist;
     jo.read( "list", new_blacklist );
     temperature_removal_blacklist.insert( new_blacklist.begin(), new_blacklist.end() );
 }
References JsonObject::allow_omitted_members(), JsonObject::read(), and temperature_removal_blacklist.
Referenced by DynamicDataLoader::initialize().
Variable Documentation
base_metabolic_rate
constexpr float base_metabolic_rate constexpr
Initial value:
=
    2500.0f
Definition at line 117 of file itype.h.
Referenced by npc::consume_food_from_camp(), stomach_contents::mod_nutr(), behavior::character_oracle_t::needs_food_badly(), and basecamp::time_to_food().