Cataclysm DDA: src/iuse_actor.cpp File Reference
iuse_actor.cpp File Reference
#include "iuse_actor.h"
#include <cctype>
#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <functional>
#include <iterator>
#include <limits>
#include <list>
#include <memory>
#include <numeric>
#include <sstream>
#include <type_traits>
#include "action.h"
#include "activity_actor_definitions.h"
#include "activity_handlers.h"
#include "activity_type.h"
#include "assign.h"
#include "avatar.h"
#include "bionics.h"
#include "bodypart.h"
#include "calendar.h"
#include "character.h"
#include "character_id.h"
#include "clothing_mod.h"
#include "clzones.h"
#include "colony.h"
#include "crafting.h"
#include "creature.h"
#include "creature_tracker.h"
#include "damage.h"
#include "debug.h"
#include "effect.h"
#include "effect_on_condition.h"
#include "enum_conversions.h"
#include "enums.h"
#include "explosion.h"
#include "field_type.h"
#include "flag.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "generic_factory.h"
#include "inventory.h"
#include "item.h"
#include "item_group.h"
#include "item_location.h"
#include "item_pocket.h"
#include "itype.h"
#include "json.h"
#include "json_loader.h"
#include "line.h"
#include "magic.h"
#include "map.h"
#include "map_iterator.h"
#include "map_selector.h"
#include "mapdata.h"
#include "material.h"
#include "memory_fast.h"
#include "messages.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "music.h"
#include "mutation.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "player_activity.h"
#include "point.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "requirements.h"
#include "rng.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "talker.h"
#include "translations.h"
#include "trap.h"
#include "ui.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "veh_appliance.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vehicle_selector.h"
#include "visitable.h"
#include "vitamin.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "weather.h"
#include "weather_type.h"
Functions
static std::vector< tripoint > points_for_gas_cloud (const tripoint &center, int radius)
static effect_data load_effect_data (const JsonObject &e)
static ret_val< tripoint > check_deploy_square (Character *p, item &it, const tripoint &pos)
static void visit_salvage_products (const item &it, const std::function< void(const item &)> &func)
static units::mass proportional_weight (const item &it, int material_portions)
static bool can_produce_results (const item &it)
static std::optional< recipe > find_uncraft_recipe (const item &x)
template<typename T >
static item_location form_loc_recursive (T &loc, item &it)
static item_location form_loc (Character &you, const tripoint &p, item &it)
static item_location get_item_location (Character &p, item &it, const tripoint &pos)
static std::pair< int, bool > find_repair_difficulty (const itype &it)
static bool damage_item (Character &pl, item_location &fix)
static Character & get_patient (Character &healer, const tripoint &pos)
static bodypart_id pick_part_to_heal (const Character &healer, const Character &patient, const std::string &menu_header, int limb_power, int head_bonus, int torso_bonus, int bleed_stop, float bite_chance, float infect_chance, bool force, float bandage_power, float disinfectant_power)
static bool is_solid_neighbor (const tripoint &pos, const point &offset)
static bool has_neighbor (const tripoint &pos, const ter_id &terrain_id)
static void place_and_add_as_known (Character &p, const tripoint &pos, const trap_str_id &id)
Variables
static const activity_id ACT_FIRSTAID ("ACT_FIRSTAID")
static const activity_id ACT_REPAIR_ITEM ("ACT_REPAIR_ITEM")
static const activity_id ACT_SPELLCASTING ("ACT_SPELLCASTING")
static const activity_id ACT_START_FIRE ("ACT_START_FIRE")
static const activity_id ACT_STUDY_SPELL ("ACT_STUDY_SPELL")
static const damage_type_id damage_acid ("acid")
static const damage_type_id damage_bash ("bash")
static const damage_type_id damage_bullet ("bullet")
static const damage_type_id damage_cut ("cut")
static const damage_type_id damage_heat ("heat")
static const efftype_id effect_asthma ("asthma")
static const efftype_id effect_bandaged ("bandaged")
static const efftype_id effect_bite ("bite")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_disinfected ("disinfected")
static const efftype_id effect_incorporeal ("incorporeal")
static const efftype_id effect_infected ("infected")
static const efftype_id effect_masked_scent ("masked_scent")
static const efftype_id effect_music ("music")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_playing_instrument ("playing_instrument")
static const efftype_id effect_recover ("recover")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_stunned ("stunned")
static const fault_id fault_bionic_salvaged ("fault_bionic_salvaged")
static const gun_mode_id gun_mode_DEFAULT ("DEFAULT")
static const itype_id itype_barrel_small ("barrel_small")
static const itype_id itype_brazier ("brazier")
static const itype_id itype_char_smoker ("char_smoker")
static const itype_id itype_fire ("fire")
static const itype_id itype_power_cord ("power_cord")
static const itype_id itype_stock_none ("stock_none")
static const itype_id itype_syringe ("syringe")
static const json_character_flag json_flag_BIONIC_LIMB ("BIONIC_LIMB")
static const json_character_flag json_flag_MANUAL_CBM_INSTALLATION ("MANUAL_CBM_INSTALLATION")
static const proficiency_id proficiency_prof_traps ("prof_traps")
static const proficiency_id proficiency_prof_trapsetting ("prof_trapsetting")
static const proficiency_id proficiency_prof_wound_care ("prof_wound_care")
static const proficiency_id proficiency_prof_wound_care_expert ("prof_wound_care_expert")
static const quality_id qual_DIG ("DIG")
static const quality_id qual_MOP ("MOP")
static const skill_id skill_fabrication ("fabrication")
static const skill_id skill_firstaid ("firstaid")
static const skill_id skill_survival ("survival")
static const skill_id skill_traps ("traps")
static const trait_id trait_DEBUG_BIONICS ("DEBUG_BIONICS")
static const trait_id trait_ILLITERATE ("ILLITERATE")
static const trait_id trait_LIGHTWEIGHT ("LIGHTWEIGHT")
static const trait_id trait_PYROMANIA ("PYROMANIA")
static const trait_id trait_TOLERANCE ("TOLERANCE")
static const trap_str_id tr_firewood_source ("tr_firewood_source")
static const zone_type_id zone_type_SOURCE_FIREWOOD ("SOURCE_FIREWOOD")
Function Documentation
can_produce_results()
static bool can_produce_results (const item & it) static
Definition at line 1521 of file iuse_actor.cpp.
 {
     for( const std::pair<const material_id, int> &mat : it.made_of() ) {
         if( const std::optional<itype_id> mat_id = mat.first->salvaged_into() ) {
             item material( *mat_id );
             if( material.count_by_charges() ) {
                 material.charges = 1;
             }
             if( material.weight() <= proportional_weight( it, mat.second ) ) {
                 return true;
             }
         }
     }
     return false;
 }
References item::charges, item::count_by_charges(), item::made_of(), proportional_weight(), and item::weight().
Referenced by salvage_actor::valid_to_cut_up().
check_deploy_square()
static ret_val<tripoint> check_deploy_square (Character * p, item & it, const tripoint & pos) static
Definition at line 1074 of file iuse_actor.cpp.
 {
     if( p->cant_do_mounted() ) {
         return ret_val<tripoint>::make_failure( pos );
     }
     tripoint pnt = pos;
     if( pos == p->pos() ) {
         if( const std::optional<tripoint> pnt_ = choose_adjacent( _( "Deploy where?" ) ) ) {
             pnt = *pnt_;
         } else {
             return ret_val<tripoint>::make_failure( pos );
         }
     }
     if( pnt == p->pos() ) {
         return ret_val<tripoint>::make_failure( pos,
                                                 _( "You attempt to become one with the %s.  It doesn't work." ), it.tname() );
     }
     map &here = get_map();
     optional_vpart_position veh_there = here.veh_at( pnt );
     if( veh_there.has_value() ) {
         // TODO: check for protrusion+short furniture, wheels+tiny furniture, NOCOLLIDE flag, etc.
         // and/or integrate furniture deployment with construction (which already seems to perform these checks sometimes?)
         return ret_val<tripoint>::make_failure( pos,
                                                 _( "The space under %s is too cramped to deploy a %s in." ),
                                                 veh_there.value().vehicle().disp_name(), it.tname() );
     }
     // For example: dirt = 2, long grass = 3
     if( here.move_cost( pnt ) != 2 && here.move_cost( pnt ) != 3 ) {
         return ret_val<tripoint>::make_failure( pos, _( "You can't deploy a %s there." ), it.tname() );
     }
     if( here.has_furn( pnt ) ) {
         return ret_val<tripoint>::make_failure( pos, _( "The %s at that location is blocking the %s." ),
                                                 here.furnname( pnt ), it.tname() );
     }
     if( here.has_items( pnt ) ) {
         // Check that there are no other people's belongings in the place where the furniture is placed.
         // Avoid easy theft of NPC items (e.g. carton theft).
         map &temp = get_map();
         for( item &i : temp.i_at( pnt ) ) {
             if( !i.is_owned_by( *p, true ) ) {
                 return ret_val<tripoint>::make_failure( pos,
                                                         _( "You can't deploy the %s on other people's belongings!" ), it.tname() );
             }
         }
         // Check that there is no liquid on the floor.
         // If there is, it needs to be mopped dry with a mop.
         if( here.terrain_moppable( tripoint_bub_ms( pnt ) ) ) {
             if( get_avatar().crafting_inventory().has_quality( qual_MOP ) ) {
                 here.mop_spills( tripoint_bub_ms( pnt ) );
                 p->add_msg_if_player( m_info, _( "You mopped up the spill with a nearby mop when deploying a %s." ),
                                       it.tname() );
                 p->mod_moves( -to_moves<int>( 15_seconds ) );
             } else {
                 return ret_val<tripoint>::make_failure( pos,
                                                         _( "You need a mop to clean up liquids before deploying the %s." ), it.tname() );
             }
         }
     }
     return ret_val<tripoint>::make_success( pnt );
 }
References _, Character::add_msg_if_player(), Character::cant_do_mounted(), choose_adjacent(), map::furnname(), get_avatar(), get_map(), map::has_furn(), map::has_items(), visitable::has_quality(), m_info, ret_val< T >::make_failure(), ret_val< T >::make_success(), Creature::mod_moves(), map::mop_spills(), map::move_cost(), Creature::pos(), math_opers::pos(), qual_MOP, temp, map::terrain_moppable(), item::tname(), and map::veh_at().
Referenced by deploy_furn_actor::use(), and deploy_appliance_actor::use().
damage_item()
static bool damage_item (Character & pl, item_location & fix) static
Definition at line 3064 of file iuse_actor.cpp.
 {
     const std::string startdurability = fix->durability_indicator( true );
     const bool destroyed = fix->inc_damage();
     const std::string resultdurability = fix->durability_indicator( true );
     pl.add_msg_if_player( m_bad, _( "You damage your %s!  ( %s-> %s)" ), fix->tname( 1, false ),
                           startdurability, resultdurability );
     if( destroyed ) {
         pl.add_msg_if_player( m_bad, _( "You destroy it!" ) );
         if( fix.where() == item_location::type::character ) {
             pl.i_rem_keep_contents( fix.get_item() );
         } else {
             for( const item *it : fix->all_items_top() ) {
                 if( it->has_flag( flag_NO_DROP ) ) {
                     continue;
                 }
                 put_into_vehicle_or_drop( pl, item_drop_reason::tumbling, { *it }, fix.pos_bub() );
             }
             fix.remove_item();
         }
         pl.calc_encumbrance();
         pl.calc_discomfort();
         return true;
     }
     return false;
 }
References _, Character::add_msg_if_player(), item::all_items_top(), Character::calc_discomfort(), Character::calc_encumbrance(), item_location::character, item::durability_indicator(), flag_NO_DROP, item_location::get_item(), item::has_flag(), Character::i_rem_keep_contents(), item::inc_damage(), m_bad, item_location::pos_bub(), put_into_vehicle_or_drop(), item_location::remove_item(), item::tname(), tumbling, and item_location::where().
Referenced by repair_item_actor::repair().
find_repair_difficulty()
static std::pair<int, bool> find_repair_difficulty (const itype & it) static
Definition at line 2865 of file iuse_actor.cpp.
 {
     int difficulty = -1;
     bool difficulty_defined = false;
     if( !it.materials.empty() ) {
         for( const auto &mats : it.materials ) {
             if( difficulty < mats.first->repair_difficulty() ) {
                 difficulty = mats.first->repair_difficulty();
                 difficulty_defined = true;
             }
         }
     }
     return { difficulty, difficulty_defined };
 }
References itype::materials.
Referenced by repair_item_actor::repair_recipe_difficulty().
find_uncraft_recipe()
static std::optional<recipe> find_uncraft_recipe (const item & x) static
Definition at line 1596 of file iuse_actor.cpp.
 {
     auto is_valid_uncraft = [&x]( const recipe & curr ) -> bool {
         return !( curr.obsolete || curr.result() != x.typeId()
                   || curr.makes_amount() > 1 || curr.is_null() );
     };
     // Check uncraft first, then crafting recipes if none was found
     recipe uncraft = recipe_dictionary::get_uncraft( x.typeId() );
     if( is_valid_uncraft( uncraft ) ) {
         return uncraft;
     }
     auto iter = std::find_if( recipe_dict.begin(), recipe_dict.end(),
     [&]( const std::pair<const recipe_id, recipe> &curr ) {
         return is_valid_uncraft( curr.second );
     } );
     if( iter != recipe_dict.end() ) {
         return iter->second;
     }
     return std::nullopt;
 }
References recipe_dictionary::begin(), recipe_dictionary::end(), recipe_dictionary::get_uncraft(), string_id< T >::is_null(), recipe_dict, and item::typeId().
Referenced by salvage_actor::cut_up().
form_loc()
static item_location form_loc (Character & you, const tripoint & p, item & it) static
Definition at line 2524 of file iuse_actor.cpp.
 {
     if( you.has_item( it ) ) {
         return form_loc_recursive( you, it );
     }
     map_cursor mc( p );
     if( mc.has_item( it ) ) {
         return form_loc_recursive( mc, it );
     }
     map &here = get_map();
     const optional_vpart_position vp = here.veh_at( p );
     if( vp ) {
         vehicle_cursor vc( vp->vehicle(), vp->part_index() );
         if( vc.has_item( it ) ) {
             return form_loc_recursive( vc, it );
         }
     }
     debugmsg( "Couldn't find item %s to form item_location, forming dummy location to ensure minimum functionality",
               it.display_name() );
     return item_location( you, &it );
 }
References debugmsg, item::display_name(), form_loc_recursive(), get_map(), visitable::has_item(), and map::veh_at().
Referenced by link_up_actor::link_extend_cable(), and holster_actor::use().
form_loc_recursive()
template<typename T > static item_location form_loc_recursive (T & loc, item & it) static
Definition at line 2514 of file iuse_actor.cpp.
 {
     item *parent = loc.find_parent( it );
     if( parent != nullptr ) {
         return item_location( form_loc_recursive( loc, *parent ), &it );
     }
     return item_location( loc, &it );
 }
References visitable::find_parent().
Referenced by form_loc().
get_item_location()
static item_location get_item_location (Character & p, item & it, const tripoint & pos) static
Definition at line 2716 of file iuse_actor.cpp.
 {
     // Item on a character
     if( p.has_item( it ) ) {
         return item_location( p, &it );
     }
     // Item in a vehicle
     if( const optional_vpart_position &vp = get_map().veh_at( pos ) ) {
         vehicle_cursor vc( vp->vehicle(), vp->part_index() );
         bool found_in_vehicle = false;
         vc.visit_items( [&]( const item * e, item * ) {
             if( e == &it ) {
                 found_in_vehicle = true;
                 return VisitResponse::ABORT;
             }
             return VisitResponse::NEXT;
         } );
         if( found_in_vehicle ) {
             return item_location( vc, &it );
         }
     }
     // Item on the map
     return item_location( map_cursor( pos ), &it );
 }
References ABORT, get_map(), visitable::has_item(), NEXT, math_opers::pos(), and vehicle_cursor::visit_items().
Referenced by repair_item_actor::use().
get_patient()
static Character& get_patient (Character & healer, const tripoint & pos) static
Definition at line 3299 of file iuse_actor.cpp.
 {
     if( healer.pos() == pos ) {
         return healer;
     }
     Character *const person = get_creature_tracker().creature_at<Character>( pos );
     if( !person ) {
         // Default to heal self on failure not to break old functionality
         add_msg_debug( debugmode::DF_IUSE, "No heal target at position %d,%d,%d", pos.x, pos.y, pos.z );
         return healer;
     }
     return *person;
 }
References add_msg_debug, creature_tracker::creature_at(), debugmode::DF_IUSE, get_creature_tracker(), Creature::pos(), and math_opers::pos().
Referenced by heal_actor::use().
has_neighbor()
static bool has_neighbor (const tripoint & pos, const ter_id & terrain_id) static
Definition at line 3796 of file iuse_actor.cpp.
 {
     map &here = get_map();
     for( const tripoint &t : here.points_in_radius( pos, 1, 0 ) ) {
         if( here.ter( t ) == terrain_id ) {
             return true;
         }
     }
     return false;
 }
References get_map(), map::points_in_radius(), math_opers::pos(), and map::ter().
Referenced by place_trap_actor::is_allowed().
is_solid_neighbor()
static bool is_solid_neighbor (const tripoint & pos, const point & offset) static
Definition at line 3788 of file iuse_actor.cpp.
 {
     map &here = get_map();
     const tripoint a = pos + tripoint( offset, 0 );
     const tripoint b = pos - tripoint( offset, 0 );
     return here.move_cost( a ) != 2 && here.move_cost( b ) != 2;
 }
References a, b, get_map(), map::move_cost(), math_opers::pos(), and tripoint.
Referenced by place_trap_actor::is_allowed().
load_effect_data()
static effect_data load_effect_data (const JsonObject & e) static
Definition at line 704 of file iuse_actor.cpp.
 {
     time_duration time;
     if( e.has_string( "duration" ) ) {
         time = read_from_json_string<time_duration>( e.get_member( "duration" ), time_duration::units );
     } else {
         time = time_duration::from_turns( e.get_int( "duration", 0 ) );
     }
     return effect_data( efftype_id( e.get_string( "id" ) ), time,
                         bodypart_id( e.get_string( "bp", "bp_null" ) ), e.get_bool( "permanent", false ) );
 }
References time_duration::from_turns(), JsonObject::get_bool(), JsonObject::get_int(), JsonObject::get_member(), JsonObject::get_string(), JsonObject::has_string(), and time_duration::units.
Referenced by consume_drug_iuse::load(), change_scent_iuse::load(), and heal_actor::load().
pick_part_to_heal()
static bodypart_id pick_part_to_heal (const Character & healer, const Character & patient, const std::string & menu_header, int limb_power, int head_bonus, int torso_bonus, int bleed_stop, float bite_chance, float infect_chance, bool force, float bandage_power, float disinfectant_power) static
Perception slightly increases precision when using first aid on someone else Firstaid increases precision when using first aid on someone else
Definition at line 3570 of file iuse_actor.cpp.
 {
     const bool bleed = bleed_stop > 0;
     const bool bite = bite_chance > 0.0f;
     const bool infect = infect_chance > 0.0f;
     const bool precise = &healer == &patient ? false :
                          /** @EFFECT_PER slightly increases precision when using first aid on someone else */
                          /** @EFFECT_FIRSTAID increases precision when using first aid on someone else */
                          ( ( healer.get_skill_level( skill_firstaid ) +
                              ( healer.has_proficiency( proficiency_prof_wound_care ) ? 0 : 1 ) +
                              ( healer.has_proficiency( proficiency_prof_wound_care ) ? 0 : 2 ) ) * 4 +
                            healer.per_cur >= 20 );
     while( true ) {
         bodypart_id healed_part = patient.body_window( menu_header, force, precise,
                                   limb_power, head_bonus, torso_bonus,
                                   bleed_stop, bite_chance, infect_chance, bandage_power, disinfectant_power );
         if( healed_part == bodypart_id( "bp_null" ) ) {
             return bodypart_id( "bp_null" );
         }
         if( healed_part->has_flag( json_flag_BIONIC_LIMB ) ) {
             add_msg( m_info, _( "You can't use first aid on a bionic limb." ) );
             continue;
         }
         if( ( infect && patient.has_effect( effect_infected, healed_part ) ) ||
             ( bite && patient.has_effect( effect_bite, healed_part ) ) ||
             ( bleed && patient.has_effect( effect_bleed, healed_part ) ) ) {
             return healed_part;
         }
         if( patient.is_limb_broken( healed_part ) ) {
             if( healed_part == bodypart_id( "arm_l" ) || healed_part == bodypart_id( "arm_r" ) ) {
                 add_msg( m_info, _( "That arm is broken.  It needs surgical attention or a splint." ) );
             } else if( healed_part == bodypart_id( "leg_l" ) || healed_part == bodypart_id( "leg_r" ) ) {
                 add_msg( m_info, _( "That leg is broken.  It needs surgical attention or a splint." ) );
             } else {
                 debugmsg( "That body part is bugged.  It needs developer's attention." );
             }
             continue;
         }
         if( force || patient.get_part_hp_cur( healed_part ) < patient.get_part_hp_max( healed_part ) ) {
             return healed_part;
         }
     }
 }
References _, add_msg(), Character::body_window(), debugmsg, effect_bite, effect_bleed, effect_infected, force, Creature::get_part_hp_cur(), Creature::get_part_hp_max(), Character::get_skill_level(), Creature::has_effect(), body_part_type::has_flag(), Character::has_proficiency(), Character::is_limb_broken(), json_flag_BIONIC_LIMB, m_info, Character::per_cur, proficiency_prof_wound_care, and skill_firstaid.
Referenced by heal_actor::use_healing_item().
place_and_add_as_known()
static void place_and_add_as_known (Character & p, const tripoint & pos, const trap_str_id & id) static
Definition at line 3849 of file iuse_actor.cpp.
 {
     map &here = get_map();
     here.trap_set( pos, id );
     const trap &tr = here.tr_at( pos );
     if( !tr.can_see( pos, p ) ) {
         p.add_known_trap( pos, tr );
     }
 }
References Character::add_known_trap(), trap::can_see(), get_map(), math_opers::pos(), map::tr_at(), and map::trap_set().
Referenced by place_trap_actor::use().
points_for_gas_cloud()
static std::vector<tripoint> points_for_gas_cloud (const tripoint & center, int radius) static
Definition at line 605 of file iuse_actor.cpp.
 {
     map &here = get_map();
     std::vector<tripoint> result;
     for( const tripoint &p : closest_points_first( center, radius ) ) {
         if( here.impassable( p ) ) {
             continue;
         }
         if( p != center ) {
             if( !here.clear_path( center, p, radius, 1, 100 ) ) {
                 // Can not splatter gas from center to that point, something is in the way
                 continue;
             }
         }
         result.push_back( p );
     }
     return result;
 }
References center, map::clear_path(), closest_points_first(), get_map(), and map::impassable().
Referenced by explosion_iuse::use().
proportional_weight()
static units::mass proportional_weight (const item & it, int material_portions) static
Definition at line 1514 of file iuse_actor.cpp.
 {
     int total_portions = std::max( 1, it.type->mat_portion_total );
     return it.weight() * material_portions / total_portions;
 }
References itype::mat_portion_total, max(), item::type, and item::weight().
Referenced by can_produce_results(), and salvage_actor::cut_up().
visit_salvage_products()
static void visit_salvage_products (const item & it, const std::function< void(const item &)> & func) static
Definition at line 1503 of file iuse_actor.cpp.
 {
     for( const auto &material : it.made_of() ) {
         if( const std::optional<itype_id> id = material.first->salvaged_into() ) {
             item exemplar( *id );
             func( exemplar );
         }
     }
 }
References item::made_of().
Referenced by salvage_actor::time_to_cut_up().
Variable Documentation
ACT_FIRSTAID
const activity_id ACT_FIRSTAID("ACT_FIRSTAID") ("ACT_FIRSTAID") static
Referenced by heal_actor::use_healing_item().
ACT_REPAIR_ITEM
const activity_id ACT_REPAIR_ITEM("ACT_REPAIR_ITEM") ("ACT_REPAIR_ITEM") static
Referenced by repair_item_actor::use().
ACT_SPELLCASTING
const activity_id ACT_SPELLCASTING("ACT_SPELLCASTING") ("ACT_SPELLCASTING") static
Referenced by cast_spell_actor::use().
ACT_START_FIRE
const activity_id ACT_START_FIRE("ACT_START_FIRE") ("ACT_START_FIRE") static
Referenced by firestarter_actor::use().
ACT_STUDY_SPELL
const activity_id ACT_STUDY_SPELL("ACT_STUDY_SPELL") ("ACT_STUDY_SPELL") static
Referenced by learn_spell_actor::use().
damage_acid
const damage_type_id damage_acid("acid") ("acid") static
Referenced by sew_advanced_actor::use().
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by sew_advanced_actor::use().
damage_bullet
const damage_type_id damage_bullet("bullet") ("bullet") static
Referenced by sew_advanced_actor::use().
damage_cut
const damage_type_id damage_cut("cut") ("cut") static
Referenced by sew_advanced_actor::use().
damage_heat
const damage_type_id damage_heat("heat") ("heat") static
Referenced by sew_advanced_actor::use().
effect_asthma
const efftype_id effect_asthma("asthma") ("asthma") static
Referenced by musical_instrument_actor::use().
effect_bandaged
const efftype_id effect_bandaged("bandaged") ("bandaged") static
Referenced by heal_actor::finish_using(), and heal_actor::use_healing_item().
effect_bite
const efftype_id effect_bite("bite") ("bite") static
Referenced by heal_actor::finish_using(), pick_part_to_heal(), and heal_actor::use_healing_item().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by heal_actor::finish_using(), pick_part_to_heal(), and heal_actor::use_healing_item().
effect_disinfected
const efftype_id effect_disinfected("disinfected") ("disinfected") static
Referenced by heal_actor::finish_using(), and heal_actor::use_healing_item().
effect_incorporeal
const efftype_id effect_incorporeal("incorporeal") ("incorporeal") static
Referenced by repair_item_actor::can_use_tool().
effect_infected
const efftype_id effect_infected("infected") ("infected") static
Referenced by heal_actor::finish_using(), pick_part_to_heal(), and heal_actor::use_healing_item().
effect_masked_scent
const efftype_id effect_masked_scent("masked_scent") ("masked_scent") static
Referenced by change_scent_iuse::use().
effect_music
const efftype_id effect_music("music") ("music") static
Referenced by musical_instrument_actor::use().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by place_monster_iuse::use().
effect_playing_instrument
const efftype_id effect_playing_instrument("playing_instrument") ("playing_instrument") static
Referenced by musical_instrument_actor::use().
effect_recover
const efftype_id effect_recover("recover") ("recover") static
Referenced by heal_actor::finish_using().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by musical_instrument_actor::use().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by musical_instrument_actor::use().
fault_bionic_salvaged
const fault_id fault_bionic_salvaged("fault_bionic_salvaged") ("fault_bionic_salvaged") static
Referenced by install_bionic_actor::can_use().
gun_mode_DEFAULT
const gun_mode_id gun_mode_DEFAULT("DEFAULT") ("DEFAULT") static
Referenced by modify_gunmods_actor::use().
itype_barrel_small
const itype_id itype_barrel_small("barrel_small") ("barrel_small") static
Referenced by saw_barrel_actor::can_use_on().
itype_brazier
const itype_id itype_brazier("brazier") ("brazier") static
Referenced by firestarter_actor::prep_firestarter_use().
itype_char_smoker
const itype_id itype_char_smoker("char_smoker") ("char_smoker") static
Referenced by deploy_furn_actor::info().
itype_fire
const itype_id itype_fire("fire") ("fire") static
Referenced by iuse_transform::use().
itype_power_cord
const itype_id itype_power_cord("power_cord") ("power_cord") static
Referenced by link_up_actor::link_to_veh_app().
itype_stock_none
const itype_id itype_stock_none("stock_none") ("stock_none") static
Referenced by saw_stock_actor::can_use_on().
itype_syringe
const itype_id itype_syringe("syringe") ("syringe") static
Referenced by consume_drug_iuse::info().
json_flag_BIONIC_LIMB
const json_character_flag json_flag_BIONIC_LIMB("BIONIC_LIMB") ("BIONIC_LIMB") static
Referenced by pick_part_to_heal().
json_flag_MANUAL_CBM_INSTALLATION
const json_character_flag json_flag_MANUAL_CBM_INSTALLATION("MANUAL_CBM_INSTALLATION") ("MANUAL_CBM_INSTALLATION") static
Referenced by install_bionic_actor::can_use(), and install_bionic_actor::use().
proficiency_prof_traps
const proficiency_id proficiency_prof_traps("prof_traps") ("prof_traps") static
Referenced by place_trap_actor::use().
proficiency_prof_trapsetting
const proficiency_id proficiency_prof_trapsetting("prof_trapsetting") ("prof_trapsetting") static
Referenced by place_trap_actor::use().
proficiency_prof_wound_care
const proficiency_id proficiency_prof_wound_care("prof_wound_care") ("prof_wound_care") static
Referenced by heal_actor::finish_using(), heal_actor::get_bandaged_level(), heal_actor::get_disinfected_level(), heal_actor::get_stopbleed_level(), pick_part_to_heal(), and heal_actor::use().
proficiency_prof_wound_care_expert
const proficiency_id proficiency_prof_wound_care_expert("prof_wound_care_expert") ("prof_wound_care_expert") static
Referenced by heal_actor::finish_using(), heal_actor::get_bandaged_level(), heal_actor::get_disinfected_level(), heal_actor::get_stopbleed_level(), and heal_actor::use().
qual_DIG
const quality_id qual_DIG("DIG") ("DIG") static
Referenced by place_trap_actor::use().
qual_MOP
const quality_id qual_MOP("MOP") ("MOP") static
Referenced by check_deploy_square().
skill_fabrication
const skill_id skill_fabrication("fabrication") ("fabrication") static
Referenced by salvage_actor::cut_up().
skill_firstaid
const skill_id skill_firstaid("firstaid") ("firstaid") static
Referenced by heal_actor::finish_using(), heal_actor::get_bandaged_level(), heal_actor::get_disinfected_level(), heal_actor::get_heal_value(), heal_actor::get_stopbleed_level(), and pick_part_to_heal().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by firestarter_actor::use().
skill_traps
const skill_id skill_traps("traps") ("traps") static
Referenced by place_trap_actor::use().
tr_firewood_source
const trap_str_id tr_firewood_source("tr_firewood_source") ("tr_firewood_source") static
Referenced by firestarter_actor::prep_firestarter_use().
trait_DEBUG_BIONICS
const trait_id trait_DEBUG_BIONICS("DEBUG_BIONICS") ("DEBUG_BIONICS") static
Referenced by install_bionic_actor::can_use(), and install_bionic_actor::use().
trait_ILLITERATE
const trait_id trait_ILLITERATE("ILLITERATE") ("ILLITERATE") static
Referenced by learn_spell_actor::info(), and learn_spell_actor::use().
trait_LIGHTWEIGHT
const trait_id trait_LIGHTWEIGHT("LIGHTWEIGHT") ("LIGHTWEIGHT") static
Referenced by consume_drug_iuse::use().
trait_PYROMANIA
const trait_id trait_PYROMANIA("PYROMANIA") ("PYROMANIA") static
Referenced by firestarter_actor::resolve_firestarter_use(), and iuse_transform::use().
trait_TOLERANCE
const trait_id trait_TOLERANCE("TOLERANCE") ("TOLERANCE") static
Referenced by consume_drug_iuse::use().
zone_type_SOURCE_FIREWOOD
const zone_type_id zone_type_SOURCE_FIREWOOD("SOURCE_FIREWOOD") ("SOURCE_FIREWOOD") static
Referenced by firestarter_actor::prep_firestarter_use().