Cataclysm DDA: src/iuse_software.h File Reference
iuse_software.h File Reference
#include <map>
#include <string>
Macros
#define CATA_SRC_IUSE_SOFTWARE_H
Functions
bool play_videogame (const std::string &function_name, std::map< std::string, std::string > &game_data, int &score)
Macro Definition Documentation
CATA_SRC_IUSE_SOFTWARE_H
#define CATA_SRC_IUSE_SOFTWARE_H
Definition at line 3 of file iuse_software.h.
Function Documentation
play_videogame()
bool play_videogame (const std::string & function_name, std::map< std::string, std::string > & game_data, int & score)
Definition at line 15 of file iuse_software.cpp.
 {
     if( function_name.empty() ) {
         score = 15;
         return true; // generic game
     }
     if( function_name == "robot_finds_kitten" ) {
         robot_finds_kitten findkitten;
         bool foundkitten = findkitten.ret;
         if( foundkitten ) {
             game_data["end_message"] = _( "You found kitten!" );
             game_data["moraletype"] = "MORALE_GAME_FOUND_KITTEN";
             score = 15;
         }
         return foundkitten;
     } else if( function_name == "snake_game" ) {
         snake_game sg;
         int iScore = sg.start_game();
         if( iScore >= 10000 ) {
             score = 30;
         } else if( iScore >= 5000 ) {
             score = 15;
         } else {
             score = 5;
         }
         return true;
     } else if( function_name == "sokoban_game" ) {
         sokoban_game sg;
         int iScore = sg.start_game();
         if( iScore >= 5000 ) {
             score = 30;
         } else if( iScore >= 1000 ) {
             score = 15;
         } else {
             score = 5;
         }
         return true;
     } else if( function_name == "minesweeper_game" ) {
         minesweeper_game mg;
         score = mg.start_game();
         return true;
     } else if( function_name == "lightson_game" ) {
         lightson_game lg;
         int iScore = lg.start_game();
         score = std::min( 15, iScore * 3 );
         return true;
     } else {
         score = -5;
         /* morale/activity workaround >.> */
         game_data["end_message"] = string_format(
                                        _( "You struggle to get '%s' working, and finally give up to play minesweeper." ),
                                        function_name );
         // TODO: better messages in morale system //  game_data["moraletype"]="MORALE_GAME_SOFTWARE_PROBLEM";
         return false;
     }
 }
References _, min(), robot_finds_kitten::ret, lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), and string_format().
Referenced by iuse::portable_game().