Cataclysm DDA: src/iuse.h File Reference
iuse.h File Reference
#include <iosfwd>
#include <memory>
#include <optional>
#include <type_traits>
#include <vector>
#include "clone_ptr.h"
#include "item_location.h"
#include "type_id.h"
#include "units_fwd.h"
Classes
struct washing_requirements
class iuse_actor
struct use_function
Namespaces
iuse
Macros
#define CATA_SRC_IUSE_H
Typedefs
using use_function_pointer = std::optional< int >(*)(Character *, item *, const tripoint &)
Functions
std::optional< int > iuse::alcohol_medium (Character *, item *, const tripoint &)
std::optional< int > iuse::alcohol_strong (Character *, item *, const tripoint &)
std::optional< int > iuse::alcohol_weak (Character *, item *, const tripoint &)
std::optional< int > iuse::antibiotic (Character *, item *, const tripoint &)
std::optional< int > iuse::anticonvulsant (Character *, item *, const tripoint &)
std::optional< int > iuse::antifungal (Character *, item *, const tripoint &)
std::optional< int > iuse::antiparasitic (Character *, item *, const tripoint &)
std::optional< int > iuse::blech (Character *, item *, const tripoint &)
std::optional< int > iuse::blech_because_unclean (Character *, item *, const tripoint &)
std::optional< int > iuse::chew (Character *, item *, const tripoint &)
std::optional< int > iuse::coke (Character *, item *, const tripoint &)
std::optional< int > iuse::datura (Character *, item *, const tripoint &)
std::optional< int > iuse::ecig (Character *, item *, const tripoint &)
std::optional< int > iuse::eyedrops (Character *, item *, const tripoint &)
std::optional< int > iuse::flu_vaccine (Character *, item *, const tripoint &)
std::optional< int > iuse::flumed (Character *, item *, const tripoint &)
std::optional< int > iuse::flusleep (Character *, item *, const tripoint &)
std::optional< int > iuse::fungicide (Character *, item *, const tripoint &)
std::optional< int > iuse::honeycomb (Character *, item *, const tripoint &)
std::optional< int > iuse::inhaler (Character *, item *, const tripoint &)
std::optional< int > iuse::marloss (Character *, item *, const tripoint &)
std::optional< int > iuse::marloss_gel (Character *, item *, const tripoint &)
std::optional< int > iuse::marloss_seed (Character *, item *, const tripoint &)
std::optional< int > iuse::meditate (Character *, item *, const tripoint &)
std::optional< int > iuse::meth (Character *, item *, const tripoint &)
std::optional< int > iuse::mycus (Character *, item *, const tripoint &)
std::optional< int > iuse::petfood (Character *p, item *it, const tripoint &)
std::optional< int > iuse::plantblech (Character *, item *, const tripoint &)
std::optional< int > iuse::poison (Character *, item *, const tripoint &)
std::optional< int > iuse::prozac (Character *, item *, const tripoint &)
std::optional< int > iuse::purify_smart (Character *, item *, const tripoint &)
std::optional< int > iuse::sewage (Character *, item *, const tripoint &)
std::optional< int > iuse::smoking (Character *, item *, const tripoint &)
Entry point for intentional bodily intake of smoke via paper wrapped one time use items: cigars, cigarettes, etc.
std::optional< int > iuse::thorazine (Character *, item *, const tripoint &)
std::optional< int > iuse::weed_cake (Character *, item *, const tripoint &)
std::optional< int > iuse::xanax (Character *, item *, const tripoint &)
std::optional< int > iuse::acidbomb_act (Character *, item *, const tripoint &)
std::optional< int > iuse::adrenaline_injector (Character *, item *, const tripoint &)
std::optional< int > iuse::afs_translocator (Character *, item *, const tripoint &)
std::optional< int > iuse::bell (Character *, item *, const tripoint &)
std::optional< int > iuse::blood_draw (Character *, item *, const tripoint &)
std::optional< int > iuse::boltcutters (Character *, item *, const tripoint &)
std::optional< int > iuse::break_stick (Character *, item *, const tripoint &)
std::optional< int > iuse::c4 (Character *, item *, const tripoint &)
std::optional< int > iuse::call_of_tindalos (Character *, item *, const tripoint &)
std::optional< int > iuse::camera (Character *, item *, const tripoint &)
std::optional< int > iuse::can_goo (Character *, item *, const tripoint &)
std::optional< int > iuse::capture_monster_act (Character *, item *, const tripoint &)
std::optional< int > iuse::capture_monster_veh (Character *, item *, const tripoint &)
std::optional< int > iuse::change_eyes (Character *, item *, const tripoint &)
std::optional< int > iuse::change_skin (Character *, item *, const tripoint &)
std::optional< int > iuse::chop_logs (Character *, item *, const tripoint &)
std::optional< int > iuse::chop_tree (Character *, item *, const tripoint &)
std::optional< int > iuse::clear_rubble (Character *, item *, const tripoint &)
std::optional< int > iuse::coin_flip (Character *, item *, const tripoint &)
std::optional< int > iuse::contacts (Character *, item *, const tripoint &)
std::optional< int > iuse::crowbar (Character *, item *, const tripoint &)
std::optional< int > iuse::crowbar_weak (Character *, item *, const tripoint &)
std::optional< int > iuse::dig (Character *, item *, const tripoint &)
std::optional< int > iuse::dig_channel (Character *, item *, const tripoint &)
std::optional< int > iuse::directional_antenna (Character *, item *, const tripoint &)
std::optional< int > iuse::directional_hologram (Character *, item *, const tripoint &)
std::optional< int > iuse::dive_tank_activate (Character *, item *, const tripoint &)
std::optional< int > iuse::dive_tank (Character *, item *, const tripoint &)
std::optional< int > iuse::dog_whistle (Character *, item *, const tripoint &)
std::optional< int > iuse::ehandcuffs (Character *, item *, const tripoint &)
std::optional< int > iuse::ehandcuffs_tick (Character *, item *, const tripoint &)
std::optional< int > iuse::epic_music (Character *, item *, const tripoint &)
std::optional< int > iuse::einktabletpc (Character *, item *, const tripoint &)
std::optional< int > iuse::emf_passive_on (Character *, item *, const tripoint &)
std::optional< int > iuse::extinguisher (Character *, item *, const tripoint &)
std::optional< int > iuse::fill_pit (Character *, item *, const tripoint &)
std::optional< int > iuse::firecracker (Character *, item *, const tripoint &)
std::optional< int > iuse::firecracker_pack (Character *, item *, const tripoint &)
std::optional< int > iuse::firecracker_pack_act (Character *, item *, const tripoint &)
std::optional< int > iuse::fish_trap (Character *, item *, const tripoint &)
std::optional< int > iuse::fish_trap_tick (Character *, item *, const tripoint &)
std::optional< int > iuse::fishing_rod (Character *, item *, const tripoint &)
std::optional< int > iuse::fitness_check (Character *p, item *it, const tripoint &)
std::optional< int > iuse::foodperson (Character *, item *, const tripoint &)
std::optional< int > iuse::foodperson_voice (Character *, item *, const tripoint &)
std::optional< int > iuse::gasmask (Character *, item *, const tripoint &)
std::optional< int > iuse::gasmask_activate (Character *, item *, const tripoint &)
std::optional< int > iuse::geiger (Character *, item *, const tripoint &)
std::optional< int > iuse::geiger_active (Character *, item *, const tripoint &)
std::optional< int > iuse::granade_act (Character *, item *, const tripoint &)
std::optional< int > iuse::grenade_inc_act (Character *, item *, const tripoint &)
std::optional< int > iuse::gun_repair (Character *, item *, const tripoint &)
std::optional< int > iuse::gunmod_attach (Character *, item *, const tripoint &)
std::optional< int > iuse::hacksaw (Character *, item *, const tripoint &it_pnt)
std::optional< int > iuse::hairkit (Character *, item *, const tripoint &)
std::optional< int > iuse::hammer (Character *, item *, const tripoint &)
std::optional< int > iuse::hand_crank (Character *, item *, const tripoint &)
std::optional< int > iuse::heat_food (Character *, item *, const tripoint &)
std::optional< int > iuse::heatpack (Character *, item *, const tripoint &)
std::optional< int > iuse::hotplate (Character *, item *, const tripoint &)
std::optional< int > iuse::hotplate_atomic (Character *, item *, const tripoint &)
std::optional< int > iuse::jackhammer (Character *, item *, const tripoint &)
std::optional< int > iuse::jet_injector (Character *, item *, const tripoint &)
std::optional< int > iuse::lumber (Character *, item *, const tripoint &)
std::optional< int > iuse::ma_manual (Character *, item *, const tripoint &)
std::optional< int > iuse::magic_8_ball (Character *, item *, const tripoint &)
std::optional< int > iuse::measure_resonance (Character *, item *, const tripoint &)
std::optional< int > iuse::electricstorage (Character *, item *, const tripoint &)
std::optional< int > iuse::ebooksave (Character *, item *, const tripoint &)
std::optional< int > iuse::ebookread (Character *, item *, const tripoint &)
std::optional< int > iuse::makemound (Character *, item *, const tripoint &)
std::optional< int > iuse::mace (Character *, item *, const tripoint &)
std::optional< int > iuse::manage_exosuit (Character *, item *, const tripoint &)
std::optional< int > iuse::melatonin_tablet (Character *, item *, const tripoint &)
std::optional< int > iuse::mininuke (Character *, item *, const tripoint &)
std::optional< int > iuse::molotov_lit (Character *, item *, const tripoint &)
std::optional< int > iuse::mop (Character *, item *, const tripoint &)
std::optional< int > iuse::mp3 (Character *, item *, const tripoint &)
std::optional< int > iuse::mp3_on (Character *, item *, const tripoint &)
std::optional< int > iuse::mp3_deactivate (Character *, item *, const tripoint &)
std::optional< int > iuse::noise_emitter_on (Character *, item *, const tripoint &)
std::optional< int > iuse::oxygen_bottle (Character *, item *, const tripoint &)
std::optional< int > iuse::oxytorch (Character *, item *, const tripoint &)
std::optional< int > iuse::binder_add_recipe (Character *, item *, const tripoint &)
std::optional< int > iuse::binder_manage_recipe (Character *, item *, const tripoint &)
std::optional< int > iuse::pack_cbm (Character *p, item *it, const tripoint &)
std::optional< int > iuse::pack_item (Character *, item *, const tripoint &)
std::optional< int > iuse::pick_lock (Character *p, item *it, const tripoint &pos)
std::optional< int > iuse::pickaxe (Character *, item *, const tripoint &)
std::optional< int > iuse::play_game (Character *, item *, const tripoint &)
std::optional< int > iuse::portable_game (Character *, item *, const tripoint &)
std::optional< int > iuse::portal (Character *, item *, const tripoint &)
std::optional< int > iuse::radglove (Character *, item *, const tripoint &)
std::optional< int > iuse::radio_mod (Character *, item *, const tripoint &)
std::optional< int > iuse::radio_off (Character *, item *, const tripoint &)
std::optional< int > iuse::radio_on (Character *, item *, const tripoint &)
std::optional< int > iuse::radio_tick (Character *, item *, const tripoint &)
std::optional< int > iuse::remove_all_mods (Character *, item *, const tripoint &)
std::optional< int > iuse::robotcontrol (Character *, item *, const tripoint &)
std::optional< int > iuse::rpgdie (Character *, item *, const tripoint &)
std::optional< int > iuse::seed (Character *, item *, const tripoint &)
std::optional< int > iuse::shavekit (Character *, item *, const tripoint &)
std::optional< int > iuse::shocktonfa_off (Character *, item *, const tripoint &)
std::optional< int > iuse::shocktonfa_on (Character *, item *, const tripoint &)
std::optional< int > iuse::siphon (Character *, item *, const tripoint &)
std::optional< int > iuse::solarpack (Character *, item *, const tripoint &)
std::optional< int > iuse::solarpack_off (Character *, item *, const tripoint &)
std::optional< int > iuse::spray_can (Character *, item *, const tripoint &)
std::optional< int > iuse::stimpack (Character *, item *, const tripoint &)
std::optional< int > iuse::strong_antibiotic (Character *, item *, const tripoint &)
std::optional< int > iuse::talking_doll (Character *, item *, const tripoint &)
std::optional< int > iuse::tazer (Character *, item *, const tripoint &)
std::optional< int > iuse::tazer2 (Character *, item *, const tripoint &)
std::optional< int > iuse::teleport (Character *, item *, const tripoint &)
std::optional< int > iuse::toolmod_attach (Character *, item *, const tripoint &)
std::optional< int > iuse::towel (Character *, item *, const tripoint &)
std::optional< int > iuse::unfold_generic (Character *, item *, const tripoint &)
std::optional< int > iuse::unpack_item (Character *, item *, const tripoint &)
std::optional< int > iuse::vibe (Character *, item *, const tripoint &)
std::optional< int > iuse::voltmeter (Character *p, item *it, const tripoint &)
std::optional< int > iuse::vortex (Character *, item *, const tripoint &)
std::optional< int > iuse::wash_all_items (Character *, item *, const tripoint &)
std::optional< int > iuse::wash_hard_items (Character *, item *, const tripoint &)
std::optional< int > iuse::wash_items (Character *p, bool soft_items, bool hard_items)
std::optional< int > iuse::wash_soft_items (Character *, item *, const tripoint &)
std::optional< int > iuse::water_purifier (Character *, item *, const tripoint &)
std::optional< int > iuse::weak_antibiotic (Character *, item *, const tripoint &)
std::optional< int > iuse::weather_tool (Character *, item *, const tripoint &)
std::optional< int > iuse::sextant (Character *, item *, const tripoint &)
std::optional< int > iuse::lux_meter (Character *, item *, const tripoint &)
std::optional< int > iuse::dbg_lux_meter (Character *, item *, const tripoint &)
std::optional< int > iuse::calories_intake_tracker (Character *p, item *, const tripoint &)
std::optional< int > iuse::radiocar (Character *, item *, const tripoint &)
std::optional< int > iuse::radiocaron (Character *, item *, const tripoint &)
std::optional< int > iuse::radiocontrol (Character *, item *, const tripoint &)
std::optional< int > iuse::radiocontrol_tick (Character *, item *, const tripoint &)
std::optional< int > iuse::multicooker (Character *, item *, const tripoint &)
std::optional< int > iuse::multicooker_tick (Character *, item *, const tripoint &)
std::optional< int > iuse::remoteveh (Character *, item *, const tripoint &)
std::optional< int > iuse::remoteveh_tick (Character *, item *, const tripoint &)
std::optional< int > iuse::craft (Character *, item *, const tripoint &)
std::optional< int > iuse::disassemble (Character *, item *, const tripoint &)
void iuse::cut_log_into_planks (Character &)
void iuse::play_music (Character *p, const tripoint &source, int volume, int max_morale)
int iuse::towel_common (Character *, item *, bool)
bool iuse::robotcontrol_can_target (Character *, const monster &)
std::optional< int > iuse::handle_ground_graffiti (Character &p, item *it, const std::string &prefix, const tripoint &where)
std::optional< std::string > iuse::can_smoke (const Character &you)
void remove_radio_mod (item &it, Character &p)
std::optional< int > gun_repair (Character *p, item *it, item_location &loc)
washing_requirements washing_requirements_for_volume (const units::volume &)
Macro Definition Documentation
CATA_SRC_IUSE_H
#define CATA_SRC_IUSE_H
Definition at line 3 of file iuse.h.
Typedef Documentation
use_function_pointer
using use_function_pointer = std::optional<int> (*)(Character *, item *, const tripoint &)
Definition at line 249 of file iuse.h.
Function Documentation
gun_repair()
std::optional<int> gun_repair (Character * p, item * it, item_location & loc)
Definition at line 5165 of file iuse.cpp.
 {
     item &fix = *loc;
     if( p->fine_detail_vision_mod() > 4 ) {
         p->add_msg_if_player( m_info, _( "You can't see to do that!" ) );
         return std::nullopt;
     }
     if( fix.damage() <= fix.degradation() ) {
         const char *msg = fix.damage_level() > 0 ?
                           _( "You can't improve your %s any more, considering the degradation." ) :
                           _( "You can't improve your %s any more this way." );
         p->add_msg_if_player( m_info, msg, fix.tname() );
         return std::nullopt;
     }
     const std::string startdurability = fix.durability_indicator( true );
     sounds::sound( p->pos(), 8, sounds::sound_t::activity, "crunch", true, "tool", "repair_kit" );
     p->practice( skill_mechanics, 10 );
     p->mod_moves( -to_moves<int>( 20_seconds ) );
     fix.mod_damage( -itype::damage_scale );
     const std::string msg = fix.damage_level() == 0
                             ? _( "You repair your %s completely!  ( %s-> %s)" )
                             : _( "You repair your %s!  ( %s-> %s)" );
     p->add_msg_if_player( m_good, msg, fix.tname( 1, false ), startdurability,
                           fix.durability_indicator( true ) );
     return 1;
 }
References _, sounds::activity, Character::add_msg_if_player(), item::damage(), item::damage_level(), itype::damage_scale, item::degradation(), item::durability_indicator(), Character::fine_detail_vision_mod(), m_good, m_info, item::mod_damage(), Creature::mod_moves(), Creature::pos(), Character::practice(), skill_mechanics, sounds::sound(), and item::tname().
Referenced by iuse::gun_repair().
remove_radio_mod()
void remove_radio_mod (item & it, Character & p)
Definition at line 434 of file iuse.cpp.
 {
     if( !it.has_flag( flag_RADIO_MOD ) ) {
         return;
     }
     p.add_msg_if_player( _( "You remove the radio modification from your %s." ), it.tname() );
     item mod( "radio_mod" );
     p.i_add_or_drop( mod, 1 );
     it.unset_flag( flag_RADIO_ACTIVATION );
     it.unset_flag( flag_RADIO_MOD );
     it.unset_flag( flag_RADIOSIGNAL_1 );
     it.unset_flag( flag_RADIOSIGNAL_2 );
     it.unset_flag( flag_RADIOSIGNAL_3 );
     it.unset_flag( flag_RADIOCARITEM );
 }
References _, Character::add_msg_if_player(), flag_RADIO_ACTIVATION, flag_RADIO_MOD, flag_RADIOCARITEM, flag_RADIOSIGNAL_1, flag_RADIOSIGNAL_2, flag_RADIOSIGNAL_3, item::has_flag(), Character::i_add_or_drop(), item::tname(), and item::unset_flag().
Referenced by Character::create_in_progress_disassembly(), and iuse::radio_mod().
washing_requirements_for_volume()
washing_requirements washing_requirements_for_volume (const units::volume & vol)
Definition at line 8086 of file iuse.cpp.
 {
     int water = divide_round_up( vol, 125_ml );
     int cleanser = divide_round_up( vol, 1_liter );
     int time = to_moves<int>( 10_seconds * ( vol / 250_ml ) );
     return { water, cleanser, time };
 }
References divide_round_up(), and water.
Referenced by iuse::wash_items().