Cataclysm DDA: src/json.h File Reference
json.h File Reference
#include <array>
#include <bitset>
#include <cstddef>
#include <cstdint>
#include <iostream>
#include <iterator>
#include <map>
#include <set>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>
#include "colony.h"
#include "enum_conversions.h"
#include "json_error.h"
#include "int_id.h"
#include "memory_fast.h"
#include "string_id.h"
#include "flexbuffer_json.h"
Classes
struct is_string_like< class, class >
struct is_string_like< T, std::void_t< decltype(std::declval< T & >().substr())> >
struct key_from_json_string< std::string, void >
struct key_from_json_string< string_id< T >, void >
struct key_from_json_string< int_id< T >, void >
struct key_from_json_string< Enum, std::enable_if_t< std::is_enum_v< Enum > > >
struct number_sci_notation
struct json_source_location
class TextJsonValue
class TextJsonIn
class JsonOut
class TextJsonObject
class TextJsonArray
class TextJsonArray::const_iterator
class TextJsonMember
Represents a member of a TextJsonObject.
class TextJsonObject::const_iterator
Macros
#define CATA_SRC_JSON_H
Enumerations
enum class json_error_output_colors_t : int32_t { unset = 0 , no_colors = 1 , color_tags = 2 , ansi_escapes = 3 }
Functions
void add_array_to_set (std::set< std::string > &, const TextJsonObject &json, std::string_view name)
Get an array member from json with name name.
std::ostream & operator<< (std::ostream &stream, const JsonError &err)
template<typename T >
void serialize (const std::optional< T > &obj, JsonOut &jsout)
template<typename T >
void deserialize (std::optional< T > &obj, const TextJsonValue &jsin)
Variables
json_error_output_colors_t json_error_output_colors
Macro Definition Documentation
CATA_SRC_JSON_H
#define CATA_SRC_JSON_H
Definition at line 3 of file json.h.
Enumeration Type Documentation
json_error_output_colors_t
enum json_error_output_colors_t : int32_t strong
Enumerator
unset
no_colors
color_tags
ansi_escapes
Definition at line 101 of file json.h.
                                       : int32_t {
     unset = 0,        // default value, will print a warning
     no_colors = 1,    // use when error output is a redirected pipe
     color_tags = 2,   // use when debugmsg will handle the errors in either SDL or curses mode
     ansi_escapes = 3, // use when error output will end up in stdout: in tooling, formatters or CI
 };
Function Documentation
add_array_to_set()
void add_array_to_set (std::set< std::string > & s, const TextJsonObject & json, std::string_view name)
Get an array member from json with name name.
For each element of that array (which should be a string) add it to the given set.
Definition at line 801 of file json.cpp.
 {
     for( const std::string line : json.get_array( name ) ) {
         s.insert( line );
     }
 }
References TextJsonObject::get_array(), line(), and om_direction::name().
deserialize()
template<typename T > void deserialize (std::optional< T > & obj, const TextJsonValue & jsin)
Definition at line 1611 of file json.h.
 {
     if( jsin.test_null() ) {
         obj.reset();
         // Temporary to manage internal mutable state correctly.
         jsin.get_null();
     } else {
         obj.emplace();
         jsin.read( *obj, true );
     }
 }
References TextJsonValue::get_null(), int_id< T >::obj(), TextJsonValue::read(), and TextJsonValue::test_null().
Referenced by TextJsonIn::read().
operator<<()
std::ostream& operator<< (std::ostream & stream, const JsonError & err)
Definition at line 2439 of file json.cpp.
 {
     return stream << err.what();
 }
serialize()
template<typename T > void serialize (const std::optional< T > & obj, JsonOut & jsout)
Definition at line 1601 of file json.h.
 {
     if( obj ) {
         jsout.write( *obj );
     } else {
         jsout.write_null();
     }
 }
References int_id< T >::obj(), JsonOut::write(), and JsonOut::write_null().
Referenced by JsonOut::write().
Variable Documentation
json_error_output_colors
json_error_output_colors_t json_error_output_colors extern
Definition at line 29 of file json.cpp.
Referenced by TextJsonIn::error(), and main().