Cataclysm DDA: src/json.cpp File Reference
json.cpp File Reference
#include "json.h"
#include <clocale>
#include <algorithm>
#include <bitset>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <exception>
#include <functional>
#include <iterator>
#include <limits>
#include <memory>
#include <set>
#include <sstream>
#include <string>
#include <utility>
#include <vector>
#include "cached_options.h"
#include "cata_scope_helpers.h"
#include "cata_utility.h"
#include "wcwidth.h"
#include "debug.h"
#include "output.h"
#include "string_formatter.h"
Functions
static bool is_whitespace (char ch)
std::string utf32_to_utf8 (uint32_t ch)
void add_array_to_set (std::set< std::string > &s, const TextJsonObject &json, const std::string_view name)
Get an array member from json with name name.
static bool get_escaped_or_unicode (std::istream &stream, std::string &s, std::string &err)
constexpr static uint64_t neg_INT_MIN ()
constexpr static uint64_t neg_INT64_MIN ()
static std::string normalize_relative_path (const std::string &path)
Get the normal form of a relative path.
static std::string escape_property (std::string str)
Escape special chars in github action command properties.
static std::string escape_data (std::string str)
Escape special chars in github action command messages.
static uint32_t UTF8_getch_raw (const char **src, int *srclen)
static int utf8_width_raw (const std::string_view s)
std::ostream & operator<< (std::ostream &stream, const JsonError &err)
Variables
json_error_output_colors_t json_error_output_colors = json_error_output_colors_t::unset
Function Documentation
add_array_to_set()
void add_array_to_set (std::set< std::string > & s, const TextJsonObject & json, std::string_view name)
Get an array member from json with name name.
For each element of that array (which should be a string) add it to the given set.
Definition at line 801 of file json.cpp.
 {
     for( const std::string line : json.get_array( name ) ) {
         s.insert( line );
     }
 }
References TextJsonObject::get_array(), line(), and om_direction::name().
escape_data()
static std::string escape_data (std::string str) static
Escape special chars in github action command messages.
See https://github.com/actions/toolkit/blob/main/packages/core/src/command.ts
Definition at line 1828 of file json.cpp.
 {
     switch( error_log_format ) {
         case error_log_format_t::human_readable:
             break;
         case error_log_format_t::github_action:
             replace_substring( str, "%", "%25", true );
             replace_substring( str, "\r", "%0D", true ); // NOLINT(cata-text-style)
             replace_substring( str, "\n", "%0A", true );
             break;
     }
     return str;
 }
References error_log_format, github_action, human_readable, and replace_substring().
Referenced by TextJsonIn::error().
escape_property()
static std::string escape_property (std::string str) static
Escape special chars in github action command properties.
See https://github.com/actions/toolkit/blob/main/packages/core/src/command.ts
Definition at line 1808 of file json.cpp.
 {
     switch( error_log_format ) {
         case error_log_format_t::human_readable:
             break;
         case error_log_format_t::github_action:
             replace_substring( str, "%", "%25", true );
             replace_substring( str, "\r", "%0D", true ); // NOLINT(cata-text-style)
             replace_substring( str, "\n", "%0A", true );
             replace_substring( str, ":", "%3A", true );
             replace_substring( str, ",", "%2C", true );
             break;
     }
     return str;
 }
References error_log_format, github_action, human_readable, and replace_substring().
Referenced by TextJsonIn::line_number().
get_escaped_or_unicode()
static bool get_escaped_or_unicode (std::istream & stream, std::string & s, std::string & err) static
Definition at line 1073 of file json.cpp.
 {
     if( !stream.good() ) {
         err = "stream not good";
         return false;
     }
     char ch;
     stream.get( ch );
     if( !stream.good() ) {
         err = "read operation failed";
         return false;
     }
     if( ch == '\\' ) {
         // converting \", \\, \/, \b, \f, \n, \r, \t and \uxxxx according to JSON spec.
         stream.get( ch );
         if( !stream.good() ) {
             err = "read operation failed";
             return false;
         }
         switch( ch ) {
             case '\\':
                 s += '\\';
                 break;
             case '"':
                 s += '"';
                 break;
             case '/':
                 s += '/';
                 break;
             case 'b':
                 s += '\b';
                 break;
             case 'f':
                 s += '\f';
                 break;
             case 'n':
                 s += '\n';
                 break;
             case 'r':
                 s += '\r';
                 break;
             case 't':
                 s += '\t';
                 break;
             case 'u': {
                     uint32_t u = 0;
                     for( int i = 0; i < 4; ++i ) {
                         stream.get( ch );
                         if( !stream.good() ) {
                             err = "read operation failed";
                             return false;
                         }
                         if( ch >= '0' && ch <= '9' ) {
                             u = ( u << 4 ) | ( ch - '0' );
                         } else if( ch >= 'a' && ch <= 'f' ) {
                             u = ( u << 4 ) | ( ch - 'a' + 10 );
                         } else if( ch >= 'A' && ch <= 'F' ) {
                             u = ( u << 4 ) | ( ch - 'A' + 10 );
                         } else {
                             err = "expected hex digit";
                             return false;
                         }
                     }
                     s += utf32_to_utf8( u );
                 }
                 break;
             default:
                 err = "invalid escape sequence";
                 return false;
         }
     } else if( ch == '\r' || ch == '\n' ) {
         err = "reached end of line without closing string";
         return false;
     } else if( ch == '"' ) {
         // the caller is supposed to handle the ending quote
         err = "unexpected ending quote";
         return false;
     } else if( static_cast<unsigned char>( ch ) < 0x20 ) {
         err = "invalid character inside string";
         return false;
     } else {
         unsigned char uc = static_cast<unsigned char>( ch );
         uint32_t unicode = 0;
         int n = 0;
         if( uc >= 0xFC ) {
             unicode = uc & 0x01;
             n = 5;
         } else if( uc >= 0xF8 ) {
             unicode = uc & 0x03;
             n = 4;
         } else if( uc >= 0xF0 ) {
             unicode = uc & 0x07;
             n = 3;
         } else if( uc >= 0xE0 ) {
             unicode = uc & 0x0f;
             n = 2;
         } else if( uc >= 0xC0 ) {
             unicode = uc & 0x1f;
             n = 1;
         } else if( uc >= 0x80 ) {
             err = "invalid utf8 sequence";
             return false;
         } else {
             unicode = uc;
             n = 0;
         }
         s += ch;
         for( ; n > 0; --n ) {
             stream.get( ch );
             if( !stream.good() ) {
                 err = "read operation failed";
                 return false;
             }
             uc = static_cast<unsigned char>( ch );
             if( uc < 0x80 || uc >= 0xC0 ) {
                 err = "invalid utf8 sequence";
                 return false;
             }
             unicode = ( unicode << 6 ) | ( uc & 0x3f );
             s += ch;
         }
         if( unicode > 0x10FFFF ) {
             err = "invalid unicode codepoint";
             return false;
         }
     }
     return true;
 }
References u, and utf32_to_utf8().
Referenced by TextJsonIn::get_string(), and TextJsonIn::string_error().
is_whitespace()
static bool is_whitespace (char ch) static
Definition at line 34 of file json.cpp.
 {
     // These are all the valid whitespace characters allowed by RFC 4627.
     return ch == ' ' || ch == '\n' || ch == '\t' || ch == '\r';
 }
Referenced by TextJsonIn::eat_whitespace(), and TextJsonIn::uneat_whitespace().
neg_INT64_MIN()
constexpr static uint64_t neg_INT64_MIN () static constexpr
Definition at line 1264 of file json.cpp.
 {
     constexpr int64_t x = std::numeric_limits<int64_t>::min() + std::numeric_limits<int64_t>::max();
     static_assert( x >= 0 || x + std::numeric_limits<int64_t>::max() >= 0,
                    "neg_INT64_MIN assumed INT64_MIN + INT64_MAX >= -INT64_MAX" );
     if( x < 0 ) {
         return static_cast<uint64_t>( std::numeric_limits<int64_t>::max() ) + static_cast<uint64_t>( -x );
     } else {
         return static_cast<uint64_t>( std::numeric_limits<int64_t>::max() ) - static_cast<uint64_t>( x );
     }
 }
References max(), and min().
Referenced by TextJsonIn::get_int64().
neg_INT_MIN()
constexpr static uint64_t neg_INT_MIN () static constexpr
Definition at line 1251 of file json.cpp.
 {
     static_assert( sizeof( int ) <= sizeof( int64_t ),
                    "neg_INT_MIN() assumed sizeof( int ) <= sizeof( int64_t )" );
     constexpr int x = std::numeric_limits<int>::min() + std::numeric_limits<int>::max();
     static_assert( x >= 0 || x + std::numeric_limits<int>::max() >= 0,
                    "neg_INT_MIN assumed INT_MIN + INT_MAX >= -INT_MAX" );
     if( x < 0 ) {
         return static_cast<uint64_t>( std::numeric_limits<int>::max() ) + static_cast<uint64_t>( -x );
     } else {
         return static_cast<uint64_t>( std::numeric_limits<int>::max() ) - static_cast<uint64_t>( x );
     }
 }
References max(), and min().
Referenced by TextJsonIn::get_int().
normalize_relative_path()
static std::string normalize_relative_path (const std::string & path) static
Get the normal form of a relative path.
Does not work on absolute paths. Slash and backslash are both treated as path separators and replaced with slash. Trailing slashes are always removed.
Definition at line 1763 of file json.cpp.
 {
     if( path.empty() ) {
         // normal form of an empty path is an empty path
         return path;
     }
     std::vector<std::string> names;
     for( size_t name_start = 0; name_start < path.size(); ) {
         const size_t name_end = std::min( path.find_first_of( "\\/", name_start ),
                                           path.size() );
         if( name_start < name_end ) {
             const std::string name = path.substr( name_start, name_end - name_start );
             if( name == "." ) {
                 // do nothing
             } else if( name == ".." ) {
                 if( names.empty() || names.back() == ".." ) {
                     names.emplace_back( name );
                 } else {
                     names.pop_back();
                 }
             } else {
                 names.emplace_back( name );
             }
         }
         name_start = std::min( path.find_first_not_of( "\\/", name_end ),
                                path.size() );
     }
     if( names.empty() ) {
         return ".";
     } else {
         std::string normpath;
         for( auto it = names.begin(); it != names.end(); ++it ) {
             if( it != names.begin() ) {
                 normpath += "/";
             }
             normpath += *it;
         }
         return normpath;
     }
 }
References cata_path::empty(), min(), om_direction::name(), and PATH_INFO::names().
Referenced by TextJsonIn::line_number().
operator<<()
std::ostream& operator<< (std::ostream & stream, const JsonError & err)
Definition at line 2439 of file json.cpp.
 {
     return stream << err.what();
 }
utf32_to_utf8()
std::string utf32_to_utf8 (uint32_t ch)
Definition at line 43 of file json.cpp.
 {
     std::array<char, 5> out;
     char *buf = out.data();
     static constexpr std::array<unsigned char, 7> utf8FirstByte = {
         0x00, 0x00, 0xC0, 0xE0, 0xF0, 0xF8, 0xFC
     };
     int utf8Bytes;
     if( ch < 0x80 ) {
         utf8Bytes = 1;
     } else if( ch < 0x800 ) {
         utf8Bytes = 2;
     } else if( ch < 0x10000 ) {
         utf8Bytes = 3;
     } else if( ch <= 0x10FFFF ) {
         utf8Bytes = 4;
     } else {
         utf8Bytes = 3;
         ch = UNKNOWN_UNICODE;
     }
     buf += utf8Bytes;
     switch( utf8Bytes ) {
         case 4: // NOLINT(bugprone-branch-clone)
             *--buf = ( ch | 0x80 ) & 0xBF;
             ch >>= 6;
         /* fallthrough */
         case 3:
             *--buf = ( ch | 0x80 ) & 0xBF;
             ch >>= 6;
         /* fallthrough */
         case 2:
             *--buf = ( ch | 0x80 ) & 0xBF;
             ch >>= 6;
         /* fallthrough */
         case 1:
             *--buf = ch | utf8FirstByte[utf8Bytes];
     }
     out[utf8Bytes] = '\0';
     return out.data();
 }
References UNKNOWN_UNICODE.
Referenced by get_escaped_or_unicode().
UTF8_getch_raw()
static uint32_t UTF8_getch_raw (const char ** src, int * srclen) static
Definition at line 1903 of file json.cpp.
 {
     const unsigned char *p = *reinterpret_cast<const unsigned char **>( src );
     int left = 0;
     bool overlong = false;
     bool underflow = false;
     uint32_t ch = UNKNOWN_UNICODE;
     if( *srclen == 0 ) {
         return UNKNOWN_UNICODE;
     }
     if( p[0] >= 0xFC ) {
         if( ( p[0] & 0xFE ) == 0xFC ) {
             if( p[0] == 0xFC && ( p[1] & 0xFC ) == 0x80 ) {
                 overlong = true;
             }
             ch = static_cast<uint32_t>( p[0] & 0x01 );
             left = 5;
         }
     } else if( p[0] >= 0xF8 ) {
         if( ( p[0] & 0xFC ) == 0xF8 ) {
             if( p[0] == 0xF8 && ( p[1] & 0xF8 ) == 0x80 ) {
                 overlong = true;
             }
             ch = static_cast<uint32_t>( p[0] & 0x03 );
             left = 4;
         }
     } else if( p[0] >= 0xF0 ) {
         if( ( p[0] & 0xF8 ) == 0xF0 ) {
             if( p[0] == 0xF0 && ( p[1] & 0xF0 ) == 0x80 ) {
                 overlong = true;
             }
             ch = static_cast<uint32_t>( p[0] & 0x07 );
             left = 3;
         }
     } else if( p[0] >= 0xE0 ) {
         if( ( p[0] & 0xF0 ) == 0xE0 ) {
             if( p[0] == 0xE0 && ( p[1] & 0xE0 ) == 0x80 ) {
                 overlong = true;
             }
             ch = static_cast<uint32_t>( p[0] & 0x0F );
             left = 2;
         }
     } else if( p[0] >= 0xC0 ) {
         if( ( p[0] & 0xE0 ) == 0xC0 ) {
             if( ( p[0] & 0xDE ) == 0xC0 ) {
                 overlong = true;
             }
             ch = static_cast<uint32_t>( p[0] & 0x1F );
             left = 1;
         }
     } else {
         if( ( p[0] & 0x80 ) == 0x00 ) {
             ch = static_cast<uint32_t>( p[0] );
         }
     }
     ++*src;
     --*srclen;
     while( left > 0 && *srclen > 0 ) {
         ++p;
         if( ( p[0] & 0xC0 ) != 0x80 ) {
             ch = UNKNOWN_UNICODE;
             break;
         }
         ch <<= 6;
         ch |= ( p[0] & 0x3F );
         ++*src;
         --*srclen;
         --left;
     }
     if( left > 0 ) {
         underflow = true;
     }
     if( overlong || underflow ||
         ( ch >= 0xD800 && ch <= 0xDFFF ) ||
         ( ch == 0xFFFE || ch == 0xFFFF ) || ch > 0x10FFFF ) {
         ch = UNKNOWN_UNICODE;
     }
     return ch;
 }
References keycode::left, and UNKNOWN_UNICODE.
Referenced by utf8_width_raw().
utf8_width_raw()
static int utf8_width_raw (const std::string_view s) static
Definition at line 1990 of file json.cpp.
 {
     int len = s.size();
     const char *ptr = s.data();
     int w = 0;
     while( len > 0 ) {
         uint32_t ch = UTF8_getch_raw( &ptr, &len );
         if( ch == UNKNOWN_UNICODE ) {
             continue;
         }
         w += mk_wcwidth( ch );
     }
     return w;
 }
References mk_wcwidth(), UNKNOWN_UNICODE, and UTF8_getch_raw().
Referenced by TextJsonIn::error().
Variable Documentation
json_error_output_colors
json_error_output_colors_t json_error_output_colors = json_error_output_colors_t::unset
Definition at line 29 of file json.cpp.
Referenced by TextJsonIn::error(), and main().