Cataclysm DDA: src/lightmap.cpp File Reference
lightmap.cpp File Reference
#include "lightmap.h"
#include "shadowcasting.h"
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <cstring>
#include <map>
#include <memory>
#include <optional>
#include <tuple>
#include <utility>
#include <vector>
#include "avatar.h"
#include "cached_options.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "colony.h"
#include "coordinate_conversions.h"
#include "cuboid_rectangle.h"
#include "debug.h"
#include "field.h"
#include "fragment_cloud.h"
#include "game.h"
#include "item.h"
#include "item_stack.h"
#include "level_cache.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "math_defines.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "point.h"
#include "string_formatter.h"
#include "submap.h"
#include "tileray.h"
#include "type_id.h"
#include "units.h"
#include "units_utility.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "weather.h"
#include "weather_type.h"
Functions
static constexpr point lightmap_boundary_max (LIGHTMAP_CACHE_X, LIGHTMAP_CACHE_Y)
static constexpr quadrant quadrant_from_x_y (int x, int y)
template<int xx, int xy, int yx, int yy, typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate>
void castLight (cata::mdarray< Out, point_bub_ms > &output_cache, const cata::mdarray< T, point_bub_ms > &input_array, const point &offset, int offsetDistance, T numerator=VISIBILITY_FULL, int row=1, float start=1.0f, float end=0.0f, T cumulative_transparency=T(LIGHT_TRANSPARENCY_OPEN_AIR))
template<typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate>
void castLightAll (cata::mdarray< Out, point_bub_ms > &output_cache, const cata::mdarray< T, point_bub_ms > &input_array, const point &offset, int offsetDistance, T numerator)
template void castLightAll< float, four_quadrants, sight_calc, sight_check, update_light_quadrants, accumulate_transparency > (cata::mdarray< four_quadrants, point_bub_ms > &output_cache, const cata::mdarray< float, point_bub_ms > &input_array, const point &offset, int offsetDistance, float numerator)
template void castLightAll< fragment_cloud, fragment_cloud, shrapnel_calc, shrapnel_check, update_fragment_cloud, accumulate_fragment_cloud > (cata::mdarray< fragment_cloud, point_bub_ms > &output_cache, const cata::mdarray< fragment_cloud, point_bub_ms > &input_array, const point &offset, int offsetDistance, fragment_cloud numerator)
static float fastexp (float x)
static float light_calc (const float &numerator, const float &transparency, const int &distance)
static bool light_check (const float &transparency, const float &intensity)
Variables
static const efftype_id effect_haslight ("haslight")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_quadruped_full ("quadruped_full")
static constexpr int LIGHTMAP_CACHE_X = MAPSIZE_X
static constexpr int LIGHTMAP_CACHE_Y = MAPSIZE_Y
static constexpr point lightmap_boundary_min {}
static const half_open_rectangle< point > lightmap_boundaries (lightmap_boundary_min, lightmap_boundary_max)
Function Documentation
castLight()
template<int xx, int xy, int yx, int yy, typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate> void castLight (cata::mdarray< Out, point_bub_ms > & output_cache, const cata::mdarray< T, point_bub_ms > & input_array, const point & offset, int offsetDistance, T numerator = VISIBILITY_FULL, int row = 1, float start = 1.0f, float end = 0.0f, T cumulative_transparency = T(LIGHT_TRANSPARENCY_OPEN_AIR))
Definition at line 838 of file lightmap.cpp.
 {
     constexpr quadrant quad = quadrant_from_x_y( -xx - xy, -yx - yy );
     float newStart = 0.0f;
     float radius = 60.0f - offsetDistance;
     if( start < end ) {
         return;
     }
     T last_intensity( 0.0 );
     tripoint delta;
     for( int distance = row; distance <= radius; distance++ ) {
         delta.y = -distance;
         bool started_row = false;
         T current_transparency( 0.0 );
         float away = start - ( -distance + 0.5f ) / ( -distance -
                      0.5f ); //The distance between our first leadingEdge and start
         //We initialize delta.x to -distance adjusted so that the commented start < leadingEdge condition below is never false
         delta.x = -distance + std::max( static_cast<int>( std::ceil( away * ( -distance - 0.5f ) ) ), 0 );
         for( ; delta.x <= 0; delta.x++ ) {
             point current( offset.x + delta.x * xx + delta.y * xy, offset.y + delta.x * yx + delta.y * yy );
             float trailingEdge = ( delta.x - 0.5f ) / ( delta.y + 0.5f );
             float leadingEdge = ( delta.x + 0.5f ) / ( delta.y - 0.5f );
             if( !( current.x >= 0 && current.y >= 0 && current.x < MAPSIZE_X &&
                    current.y < MAPSIZE_Y ) /* || start < leadingEdge */ ) {
                 continue;
             } else if( end > trailingEdge ) {
                 break;
             }
             if( !started_row ) {
                 started_row = true;
                 current_transparency = input_array[ current.x ][ current.y ];
             }
             const int dist = rl_dist( tripoint_zero, delta ) + offsetDistance;
             last_intensity = calc( numerator, cumulative_transparency, dist );
             T new_transparency = input_array[ current.x ][ current.y ];
             if( check( new_transparency, last_intensity ) ) {
                 update_output( output_cache[current.x][current.y], last_intensity,
                                quadrant::default_ );
             } else {
                 update_output( output_cache[current.x][current.y], last_intensity, quad );
             }
             if( new_transparency == current_transparency ) {
                 newStart = leadingEdge;
                 continue;
             }
             // Only cast recursively if previous span was not opaque.
             if( check( current_transparency, last_intensity ) ) {
                 castLight<xx, xy, yx, yy, T, Out, calc, check, update_output, accumulate>(
                     output_cache, input_array, offset, offsetDistance,
                     numerator, distance + 1, start, trailingEdge,
                     accumulate( cumulative_transparency, current_transparency, distance ) );
             }
             // The new span starts at the leading edge of the previous square if it is opaque,
             // and at the trailing edge of the current square if it is transparent.
             if( !check( current_transparency, last_intensity ) ) {
                 start = newStart;
             } else {
                 // Note this is the same slope as the recursive call we just made.
                 start = trailingEdge;
             }
             // Trailing edge ahead of leading edge means this span is fully processed.
             if( start < end ) {
                 return;
             }
             current_transparency = new_transparency;
             newStart = leadingEdge;
         }
         if( !check( current_transparency, last_intensity ) ) {
             // If we reach the end of the span with terrain being opaque, we don't iterate further.
             break;
         }
         // Cumulative average of the transparency values encountered.
         cumulative_transparency = accumulate( cumulative_transparency, current_transparency, distance );
     }
 }
References ceil(), check(), default_, keycode::end, MAPSIZE_X, MAPSIZE_Y, max(), quadrant_from_x_y(), rl_dist(), tripoint_zero, point::x, tripoint::x, point::y, and tripoint::y.
Referenced by map::apply_directional_light(), map::apply_light_arc(), map::apply_light_source(), and castLightAll().
castLightAll()
template<typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate> void castLightAll (cata::mdarray< Out, point_bub_ms > & output_cache, const cata::mdarray< T, point_bub_ms > & input_array, const point & offset, int offsetDistance, T numerator)
Definition at line 928 of file lightmap.cpp.
 {
     castLight<0, 1, 1, 0, T, Out, calc, check, update_output, accumulate>(
         output_cache, input_array, offset, offsetDistance, numerator );
     castLight<1, 0, 0, 1, T, Out, calc, check, update_output, accumulate>(
         output_cache, input_array, offset, offsetDistance, numerator );
     castLight < 0, -1, 1, 0, T, Out, calc, check, update_output, accumulate > (
         output_cache, input_array, offset, offsetDistance, numerator );
     castLight < -1, 0, 0, 1, T, Out, calc, check, update_output, accumulate > (
         output_cache, input_array, offset, offsetDistance, numerator );
     castLight < 0, 1, -1, 0, T, Out, calc, check, update_output, accumulate > (
         output_cache, input_array, offset, offsetDistance, numerator );
     castLight < 1, 0, 0, -1, T, Out, calc, check, update_output, accumulate > (
         output_cache, input_array, offset, offsetDistance, numerator );
     castLight < 0, -1, -1, 0, T, Out, calc, check, update_output, accumulate > (
         output_cache, input_array, offset, offsetDistance, numerator );
     castLight < -1, 0, 0, -1, T, Out, calc, check, update_output, accumulate > (
         output_cache, input_array, offset, offsetDistance, numerator );
 }
References castLight(), and check().
Referenced by explosion_handler::shrapnel().
castLightAll< float, four_quadrants, sight_calc, sight_check, update_light_quadrants, accumulate_transparency >()
template void castLightAll< float, four_quadrants, sight_calc, sight_check, update_light_quadrants, accumulate_transparency > (cata::mdarray< four_quadrants, point_bub_ms > & output_cache, const cata::mdarray< float, point_bub_ms > & input_array, const point & offset, int offsetDistance, float numerator)
castLightAll< fragment_cloud, fragment_cloud, shrapnel_calc, shrapnel_check, update_fragment_cloud, accumulate_fragment_cloud >()
template void castLightAll< fragment_cloud, fragment_cloud, shrapnel_calc, shrapnel_check, update_fragment_cloud, accumulate_fragment_cloud > (cata::mdarray< fragment_cloud, point_bub_ms > & output_cache, const cata::mdarray< fragment_cloud, point_bub_ms > & input_array, const point & offset, int offsetDistance, fragment_cloud numerator)
fastexp()
static float fastexp (float x) static
Definition at line 1126 of file lightmap.cpp.
 {
     union {
         float f;
         int i;
     } u, v;
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wunknown-pragmas"
 #pragma GCC diagnostic ignored "-Wpragmas"
 #pragma GCC diagnostic ignored "-Wunknown-warning-option"
 #pragma GCC diagnostic ignored "-Wimplicit-int-float-conversion"
     u.i = static_cast<long long>( 6051102 * x + 1056478197 );
     v.i = static_cast<long long>( 1056478197 - 6051102 * x );
 #pragma GCC diagnostic pop
     return u.f / v.f;
 }
References u.
Referenced by map::apply_light_ray(), and light_calc().
light_calc()
static float light_calc (const float & numerator, const float & transparency, const int & distance) static
Definition at line 1143 of file lightmap.cpp.
 {
     // Light needs inverse square falloff in addition to attenuation.
     return numerator  / ( fastexp( transparency * distance ) * distance );
 }
References fastexp().
Referenced by map::apply_directional_light(), map::apply_light_arc(), and map::apply_light_source().
light_check()
static bool light_check (const float & transparency, const float & intensity) static
Definition at line 1150 of file lightmap.cpp.
 {
     return transparency > LIGHT_TRANSPARENCY_SOLID && intensity > LIGHT_AMBIENT_LOW;
 }
References intensity, LIGHT_AMBIENT_LOW, and LIGHT_TRANSPARENCY_SOLID.
Referenced by map::apply_directional_light(), map::apply_light_arc(), and map::apply_light_source().
lightmap_boundary_max()
static constexpr point lightmap_boundary_max (LIGHTMAP_CACHE_X , LIGHTMAP_CACHE_Y) static constexpr
quadrant_from_x_y()
static constexpr quadrant quadrant_from_x_y (int x, int y) static constexpr
Definition at line 814 of file lightmap.cpp.
 {
     return ( x > 0 ) ?
            ( ( y > 0 ) ? quadrant::NW : quadrant::SW ) :
            ( ( y > 0 ) ? quadrant::NE : quadrant::SE );
 }
References NE, NW, SE, and SW.
Referenced by map::apply_light_ray(), and castLight().
Variable Documentation
effect_haslight
const efftype_id effect_haslight("haslight") ("haslight") static
Referenced by map::apply_character_light().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by map::apply_character_light(), and map::generate_lightmap().
effect_quadruped_full
const efftype_id effect_quadruped_full("quadruped_full") ("quadruped_full") static
Referenced by map::build_vision_transparency_cache().
lightmap_boundaries
const half_open_rectangle<point> lightmap_boundaries(lightmap_boundary_min, lightmap_boundary_max) (lightmap_boundary_min , lightmap_boundary_max) static
Referenced by map::apparent_light_helper(), map::apply_light_ray(), and map::generate_lightmap().
lightmap_boundary_min
constexpr point lightmap_boundary_min {} static constexpr
Definition at line 59 of file lightmap.cpp.
LIGHTMAP_CACHE_X
constexpr int LIGHTMAP_CACHE_X = MAPSIZE_X static constexpr
Definition at line 56 of file lightmap.cpp.
Referenced by map::apply_light_source(), and map::generate_lightmap().
LIGHTMAP_CACHE_Y
constexpr int LIGHTMAP_CACHE_Y = MAPSIZE_Y static constexpr
Definition at line 57 of file lightmap.cpp.
Referenced by map::generate_lightmap().