Cataclysm DDA: src/line.h File Reference
line.h File Reference
#include <algorithm>
#include <cmath>
#include <functional>
#include <iosfwd>
#include <vector>
#include "point.h"
#include "units_fwd.h"
Classes
struct enum_traits< direction >
struct std::hash< direction >
struct FastDistanceApproximation
Helper type for the return value of dist_fast().
struct rl_vec2d
struct rl_vec3d
Macros
#define CATA_SRC_LINE_H
Enumerations
enum class direction : unsigned {
ABOVENORTHWEST = make_xyz_unit(tripoint_above + tripoint_north_west) , NORTHWEST = make_xyz_unit(tripoint_north_west) , BELOWNORTHWEST = make_xyz_unit(tripoint_below + tripoint_north_west) , ABOVENORTH = make_xyz_unit(tripoint_above + tripoint_north) ,
NORTH = make_xyz_unit(tripoint_north) , BELOWNORTH = make_xyz_unit(tripoint_below + tripoint_north) , ABOVENORTHEAST = make_xyz_unit(tripoint_above + tripoint_north_east) , NORTHEAST = make_xyz_unit(tripoint_north_east) ,
BELOWNORTHEAST = make_xyz_unit(tripoint_below + tripoint_north_east) , ABOVEWEST = make_xyz_unit(tripoint_above + tripoint_west) , WEST = make_xyz_unit(tripoint_west) , BELOWWEST = make_xyz_unit(tripoint_below + tripoint_west) ,
ABOVECENTER = make_xyz_unit(tripoint_above) , CENTER = make_xyz_unit(tripoint_zero) , BELOWCENTER = make_xyz_unit(tripoint_below) , ABOVEEAST = make_xyz_unit(tripoint_above + tripoint_east) ,
EAST = make_xyz_unit(tripoint_east) , BELOWEAST = make_xyz_unit(tripoint_below + tripoint_east) , ABOVESOUTHWEST = make_xyz_unit(tripoint_above + tripoint_south_west) , SOUTHWEST = make_xyz_unit(tripoint_south_west) ,
BELOWSOUTHWEST = make_xyz_unit(tripoint_below + tripoint_south_west) , ABOVESOUTH = make_xyz_unit(tripoint_above + tripoint_south) , SOUTH = make_xyz_unit(tripoint_south) , BELOWSOUTH = make_xyz_unit(tripoint_below + tripoint_south) ,
ABOVESOUTHEAST = make_xyz_unit(tripoint_above + tripoint_south_east) , SOUTHEAST = make_xyz_unit(tripoint_south_east) , BELOWSOUTHEAST = make_xyz_unit(tripoint_below + tripoint_south_east) , last = 27
}
Functions
double iso_tangent (double distance, const units::angle &vertex)
Calculate base of an isosceles triangle.
constexpr unsigned make_xyz_unit (const tripoint &p) noexcept
This compile-time usable function combines the sign of each (x, y, z) component into a single integer to allow simple runtime and compile-time mapping of (x, y, z) tuples to direction enumerators.
unsigned make_xyz (const tripoint &)
template<class T >
constexpr direction operator% (const direction &lhs, const T &rhs)
template<class T >
constexpr T operator+ (const direction &lhs, const T &rhs)
template<class T >
constexpr bool operator== (const direction &lhs, const T &rhs)
template<class T >
constexpr bool operator== (const T &lhs, const direction &rhs)
template<class T >
constexpr bool operator!= (const T &lhs, const direction &rhs)
template<class T >
constexpr bool operator!= (const direction &lhs, const T &rhs)
direction direction_from (const point &p) noexcept
direction direction_from (const tripoint &p) noexcept
direction direction_from (const point &p1, const point &p2) noexcept
direction direction_from (const tripoint &p, const tripoint &q)
tripoint displace (direction dir)
point displace_XY (direction dir)
std::string direction_name (direction dir)
std::string direction_name_short (direction dir)
std::string direction_arrow (direction dir)
std::string direction_suffix (const tripoint &p, const tripoint &q)
void bresenham (const point &p1, const point &p2, int t, const std::function< bool(const point &)> &interact)
The actual Bresenham algorithm in 2D and 3D, everything else should call these and pass in an interact functor to iterate across a line between two points.
void bresenham (const tripoint &loc1, const tripoint &loc2, int t, int t2, const std::function< bool(const tripoint &)> &interact)
tripoint move_along_line (const tripoint &loc, const std::vector< tripoint > &line, int distance)
std::vector< point > line_to (const point &p1, const point &p2, int t=0)
std::vector< tripoint > line_to (const tripoint &loc1, const tripoint &loc2, int t=0, int t2=0)
float trig_dist (const tripoint &loc1, const tripoint &loc2)
float trig_dist (const point &loc1, const point &loc2)
int square_dist (const tripoint &loc1, const tripoint &loc2)
int square_dist (const point &loc1, const point &loc2)
int rl_dist (const tripoint &loc1, const tripoint &loc2)
int rl_dist (const point &a, const point &b)
FastDistanceApproximation trig_dist_fast (const tripoint &loc1, const tripoint &loc2)
FastDistanceApproximation square_dist_fast (const tripoint &loc1, const tripoint &loc2)
FastDistanceApproximation rl_dist_fast (const tripoint &loc1, const tripoint &loc2)
FastDistanceApproximation rl_dist_fast (const point &a, const point &b)
float rl_dist_exact (const tripoint &loc1, const tripoint &loc2)
int manhattan_dist (const point &loc1, const point &loc2)
int octile_dist (const point &loc1, const point &loc2, int multiplier=1)
float octile_dist_exact (const point &loc1, const point &loc2)
units::angle atan2 (const point &)
units::angle atan2 (const rl_vec2d &)
float get_normalized_angle (const point &start, const point &end)
std::vector< tripoint > continue_line (const std::vector< tripoint > &line, int distance)
std::vector< point > squares_in_direction (const point &p1, const point &p2)
std::vector< tripoint > squares_closer_to (const tripoint &from, const tripoint &to)
void calc_ray_end (units::angle, int range, const tripoint &p, tripoint &out)
units::angle coord_to_angle (const tripoint &a, const tripoint &b)
Calculates the horizontal angle between the lines from (0,0,0) to a and the line from (0,0,0) to b.
Variables
bool trigdist
Macro Definition Documentation
CATA_SRC_LINE_H
#define CATA_SRC_LINE_H
Definition at line 3 of file line.h.
Enumeration Type Documentation
direction
enum direction : unsigned strong
Enumerator
ABOVENORTHWEST
NORTHWEST
BELOWNORTHWEST
ABOVENORTH
NORTH
BELOWNORTH
ABOVENORTHEAST
NORTHEAST
BELOWNORTHEAST
ABOVEWEST
WEST
BELOWWEST
ABOVECENTER
CENTER
BELOWCENTER
ABOVEEAST
EAST
BELOWEAST
ABOVESOUTHWEST
SOUTHWEST
BELOWSOUTHWEST
ABOVESOUTH
SOUTH
BELOWSOUTH
ABOVESOUTHEAST
SOUTHEAST
BELOWSOUTHEAST
last
Definition at line 42 of file line.h.
                      : unsigned {
     ABOVENORTHWEST = make_xyz_unit( tripoint_above + tripoint_north_west ),
     NORTHWEST      = make_xyz_unit( tripoint_north_west ),
     BELOWNORTHWEST = make_xyz_unit( tripoint_below + tripoint_north_west ),
     ABOVENORTH     = make_xyz_unit( tripoint_above + tripoint_north ),
     NORTH          = make_xyz_unit( tripoint_north ),
     BELOWNORTH     = make_xyz_unit( tripoint_below + tripoint_north ),
     ABOVENORTHEAST = make_xyz_unit( tripoint_above + tripoint_north_east ),
     NORTHEAST      = make_xyz_unit( tripoint_north_east ),
     BELOWNORTHEAST = make_xyz_unit( tripoint_below + tripoint_north_east ),
     ABOVEWEST      = make_xyz_unit( tripoint_above + tripoint_west ),
     WEST           = make_xyz_unit( tripoint_west ),
     BELOWWEST      = make_xyz_unit( tripoint_below + tripoint_west ),
     ABOVECENTER    = make_xyz_unit( tripoint_above ),
     CENTER         = make_xyz_unit( tripoint_zero ),
     BELOWCENTER    = make_xyz_unit( tripoint_below ),
     ABOVEEAST      = make_xyz_unit( tripoint_above + tripoint_east ),
     EAST           = make_xyz_unit( tripoint_east ),
     BELOWEAST      = make_xyz_unit( tripoint_below + tripoint_east ),
     ABOVESOUTHWEST = make_xyz_unit( tripoint_above + tripoint_south_west ),
     SOUTHWEST      = make_xyz_unit( tripoint_south_west ),
     BELOWSOUTHWEST = make_xyz_unit( tripoint_below + tripoint_south_west ),
     ABOVESOUTH     = make_xyz_unit( tripoint_above + tripoint_south ),
     SOUTH          = make_xyz_unit( tripoint_south ),
     BELOWSOUTH     = make_xyz_unit( tripoint_below + tripoint_south ),
     ABOVESOUTHEAST = make_xyz_unit( tripoint_above + tripoint_south_east ),
     SOUTHEAST      = make_xyz_unit( tripoint_south_east ),
     BELOWSOUTHEAST = make_xyz_unit( tripoint_below + tripoint_south_east ),
     last = 27
 };
Function Documentation
atan2() [1/2]
units::angle atan2 (const point & p)
Definition at line 288 of file line.cpp.
 {
     return units::atan2( p.y, p.x );
 }
References units::atan2(), point::x, and point::y.
Referenced by calculate_aim_cap(), tileray::init(), make_xyz(), orient_part(), sun_azimuth_altitude(), sun_ra_declination(), and target_size_in_moa().
atan2() [2/2]
units::angle atan2 (const rl_vec2d & p)
Definition at line 293 of file line.cpp.
 {
     return units::atan2( p.y, p.x );
 }
References units::atan2(), rl_vec2d::x, and rl_vec2d::y.
bresenham() [1/2]
void bresenham (const point & p1, const point & p2, int t, const std::function< bool(const point &)> & interact)
The actual Bresenham algorithm in 2D and 3D, everything else should call these and pass in an interact functor to iterate across a line between two points.
Definition at line 25 of file line.cpp.
 {
     // The slope components.
     const point d = p2 - p1;
     // Signs of slope values.
     const point s( ( d.x == 0 ) ? 0 : sgn( d.x ), ( d.y == 0 ) ? 0 : sgn( d.y ) );
     // Absolute values of slopes x2 to avoid rounding errors.
     const point a = d.abs() * 2;
     point cur = p1;
     if( a.x == a.y ) {
         while( cur.x != p2.x ) {
             cur.y += s.y;
             cur.x += s.x;
             if( !interact( cur ) ) {
                 break;
             }
         }
     } else if( a.x > a.y ) {
         while( cur.x != p2.x ) {
             if( t > 0 ) {
                 cur.y += s.y;
                 t -= a.x;
             }
             cur.x += s.x;
             t += a.y;
             if( !interact( cur ) ) {
                 break;
             }
         }
     } else {
         while( cur.y != p2.y ) {
             if( t > 0 ) {
                 cur.x += s.x;
                 t -= a.y;
             }
             cur.y += s.y;
             t += a.x;
             if( !interact( cur ) ) {
                 break;
             }
         }
     }
 }
References a, point::abs(), sgn(), point::x, and point::y.
Referenced by map::clear_path(), map::ledge_coverage(), line_to(), map::obstacle_coverage(), and map::sees().
bresenham() [2/2]
void bresenham (const tripoint & loc1, const tripoint & loc2, int t, int t2, const std::function< bool(const tripoint &)> & interact)
Definition at line 72 of file line.cpp.
 {
     // The slope components.
     const tripoint d( -loc1 + loc2 );
     // The signs of the slopes.
     const tripoint s( ( d.x == 0 ? 0 : sgn( d.x ) ), ( d.y == 0 ? 0 : sgn( d.y ) ),
                       ( d.z == 0 ? 0 : sgn( d.z ) ) );
     // Absolute values of slope components, x2 to avoid rounding errors.
     const tripoint a( std::abs( d.x ) * 2, std::abs( d.y ) * 2, std::abs( d.z ) * 2 );
     tripoint cur( loc1 );
     if( a.z == 0 ) {
         if( a.x == a.y ) {
             while( cur.x != loc2.x ) {
                 cur.y += s.y;
                 cur.x += s.x;
                 if( !interact( cur ) ) {
                     break;
                 }
             }
         } else if( a.x > a.y ) {
             while( cur.x != loc2.x ) {
                 if( t > 0 ) {
                     cur.y += s.y;
                     t -= a.x;
                 }
                 cur.x += s.x;
                 t += a.y;
                 if( !interact( cur ) ) {
                     break;
                 }
             }
         } else {
             while( cur.y != loc2.y ) {
                 if( t > 0 ) {
                     cur.x += s.x;
                     t -= a.y;
                 }
                 cur.y += s.y;
                 t += a.x;
                 if( !interact( cur ) ) {
                     break;
                 }
             }
         }
     } else {
         if( a.x == a.y && a.y == a.z ) {
             while( cur.x != loc2.x ) {
                 cur.z += s.z;
                 cur.y += s.y;
                 cur.x += s.x;
                 if( !interact( cur ) ) {
                     break;
                 }
             }
         } else if( ( a.z > a.x ) && ( a.z > a.y ) ) {
             while( cur.z != loc2.z ) {
                 if( t > 0 ) {
                     cur.x += s.x;
                     t -= a.z;
                 }
                 if( t2 > 0 ) {
                     cur.y += s.y;
                     t2 -= a.z;
                 }
                 cur.z += s.z;
                 t += a.x;
                 t2 += a.y;
                 if( !interact( cur ) ) {
                     break;
                 }
             }
         } else if( a.x == a.y ) {
             while( cur.x != loc2.x ) {
                 if( t > 0 ) {
                     cur.z += s.z;
                     t -= a.x;
                 }
                 cur.y += s.y;
                 cur.x += s.x;
                 t += a.z;
                 if( !interact( cur ) ) {
                     break;
                 }
             }
         } else if( a.x == a.z ) {
             while( cur.x != loc2.x ) {
                 if( t > 0 ) {
                     cur.y += s.y;
                     t -= a.x;
                 }
                 cur.z += s.z;
                 cur.x += s.x;
                 t += a.y;
                 if( !interact( cur ) ) {
                     break;
                 }
             }
         } else if( a.y == a.z ) {
             while( cur.y != loc2.y ) {
                 if( t > 0 ) {
                     cur.x += s.x;
                     t -= a.z;
                 }
                 cur.y += s.y;
                 cur.z += s.z;
                 t += a.x;
                 if( !interact( cur ) ) {
                     break;
                 }
             }
         } else if( a.x > a.y ) {
             while( cur.x != loc2.x ) {
                 if( t > 0 ) {
                     cur.y += s.y;
                     t -= a.x;
                 }
                 if( t2 > 0 ) {
                     cur.z += s.z;
                     t2 -= a.x;
                 }
                 cur.x += s.x;
                 t += a.y;
                 t2 += a.z;
                 if( !interact( cur ) ) {
                     break;
                 }
             }
         } else { //dy > dx >= dz
             while( cur.y != loc2.y ) {
                 if( t > 0 ) {
                     cur.x += s.x;
                     t -= a.y;
                 }
                 if( t2 > 0 ) {
                     cur.z += s.z;
                     t2 -= a.y;
                 }
                 cur.y += s.y;
                 t += a.x;
                 t2 += a.z;
                 if( !interact( cur ) ) {
                     break;
                 }
             }
         }
     }
 }
References a, abs(), sgn(), tripoint::x, tripoint::y, and tripoint::z.
calc_ray_end()
void calc_ray_end (units::angle angle, int range, const tripoint & p, tripoint & out)
Definition at line 910 of file line.cpp.
 {
     // forces input angle to be between 0 and 360, calculated from actual input
     angle = fmod( angle, 360_degrees );
     if( angle < 0_degrees ) {
         angle += 360_degrees;
     }
     out.z = p.z;
     if( trigdist ) {
         out.x = p.x + range * cos( angle );
         out.y = p.y + range * sin( angle );
     } else {
         int mult = 0;
         if( angle >= 135_degrees && angle <= 315_degrees ) {
             mult = -1;
         } else {
             mult = 1;
         }
         if( angle <= 45_degrees || ( 135_degrees <= angle && angle <= 215_degrees ) ||
             315_degrees < angle ) {
             out.x = p.x + range * mult;
             out.y = p.y + range * tan( angle ) * mult;
         } else {
             out.x = p.x + range * 1 / tan( angle ) * mult;
             out.y = p.y + range * mult;
         }
     }
 }
References cos(), units::fmod(), sin(), tan(), trigdist, tripoint::x, tripoint::y, and tripoint::z.
Referenced by spell_effect::dash(), spell_effect::directed_push(), vehicle::part_collision(), and spell_effect_cone_range_override().
continue_line()
std::vector<tripoint> continue_line (const std::vector< tripoint > & line, int distance)
Definition at line 380 of file line.cpp.
 {
     return line_to( line.back(), move_along_line( line.back(), line, distance ) );
 }
References line(), line_to(), and move_along_line().
Referenced by get_bashing_zone(), game::knockback(), and projectile_attack().
coord_to_angle()
units::angle coord_to_angle (const tripoint & a, const tripoint & b)
Calculates the horizontal angle between the lines from (0,0,0) to a and the line from (0,0,0) to b.
Returned value is in degree and in the range 0....360. Example: if a is (0,1) and b is (1,0), the result will 90 degree The function currently ignores the z component.
Definition at line 940 of file line.cpp.
 {
     units::angle rad = units::atan2( b.y - a.y, b.x - a.x );
     if( rad < 0_degrees ) {
         rad += 2_pi_radians;
     }
     return rad;
 }
References a, units::atan2(), and b.
Referenced by Creature::auto_find_hostile_target(), melee_actor::call(), spell_effect::dash(), spell_effect::directed_push(), melee_actor::do_grab(), mattack::flesh_tendril(), mattack::fungus_fortify(), mattack::fungus_sprout(), sfx::get_heard_angle(), target_ui::recalc_aim_turning_penalty(), mattack::shriek_stun(), mattack::smash(), spell_effect_cone_range_override(), and npc::wont_hit_friend().
direction_arrow()
std::string direction_arrow (direction dir)
Definition at line 622 of file line.cpp.
 {
     std::string arrow;
     if( dir == direction::NORTH ) {
         arrow = "\u21D1";
     } else if( dir == direction::NORTHEAST ) {
         arrow = "\u21D7";
     } else if( dir == direction::EAST ) {
         arrow = "\u21D2";
     } else if( dir == direction::SOUTHEAST ) {
         arrow = "\u21D8";
     } else if( dir == direction::SOUTH ) {
         arrow = "\u21D3";
     } else if( dir == direction::SOUTHWEST ) {
         arrow = "\u21D9";
     } else if( dir == direction::WEST ) {
         arrow = "\u21D0";
     } else if( dir == direction::NORTHWEST ) {
         arrow = "\u21D6";
     }
     return arrow;
 }
References arrow, EAST, NORTH, NORTHEAST, NORTHWEST, SOUTH, SOUTHEAST, SOUTHWEST, and WEST.
Referenced by game::point_selection_menu().
direction_from() [1/4]
direction direction_from (const point & p) noexcept
Definition at line 431 of file line.cpp.
 {
     return static_cast<direction>( make_xyz( tripoint( p, 0 ) ) );
 }
References make_xyz().
Referenced by direction_from(), and direction_suffix().
direction_from() [2/4]
direction direction_from (const point & p1, const point & p2) noexcept
Definition at line 441 of file line.cpp.
 {
     return direction_from( p2 - p1 );
 }
References direction_from().
direction_from() [3/4]
direction direction_from (const tripoint & p) noexcept
Definition at line 436 of file line.cpp.
 {
     return static_cast<direction>( make_xyz( p ) );
 }
References make_xyz().
direction_from() [4/4]
direction direction_from (const tripoint & p, const tripoint & q)
Definition at line 446 of file line.cpp.
 {
     return direction_from( q - p );
 }
References direction_from().
direction_name()
std::string direction_name (direction dir)
Definition at line 612 of file line.cpp.
 {
     return direction_name_impl( dir, false );
 }
References anonymous_namespace{line.cpp}::direction_name_impl().
Referenced by game::check_safe_mode_allowed(), iuse::directional_antenna(), Character::echo_pulse(), basecamp::faction_display(), npc::faction_display(), overmapbuffer::get_description_at(), liquid_handler::get_liquid_target(), vehicle::handle_trap(), game::point_selection_menu(), sounds::process_sound_markers(), Character::search_surroundings(), and npc::warn_about().
direction_name_short()
std::string direction_name_short (direction dir)
Definition at line 617 of file line.cpp.
 {
     return direction_name_impl( dir, true );
 }
References anonymous_namespace{line.cpp}::direction_name_impl().
Referenced by computer_session::action_emerg_ref_center(), direction_suffix(), game::list_items(), game::list_monsters(), overmap_ui::search(), and game::zones_manager().
direction_suffix()
std::string direction_suffix (const tripoint & p, const tripoint & q)
Definition at line 645 of file line.cpp.
 {
     int dist = square_dist( p, q );
     if( dist <= 0 ) {
         return std::string();
     }
     return string_format( "%d%s", dist, trim( direction_name_short( direction_from( p, q ) ) ) );
 }
References direction_from(), direction_name_short(), square_dist(), string_format(), and trim().
Referenced by item_location::impl::item_on_map::describe(), item_location::impl::item_on_vehicle::describe(), and inventory_selector::naturalize_category().
displace()
tripoint displace (direction dir)
Definition at line 451 of file line.cpp.
 {
     switch( dir ) {
         case direction::NORTHWEST:
             return tripoint_north_west;
         case direction::ABOVENORTHWEST:
             return point_north_west + tripoint_above;
         case direction::BELOWNORTHWEST:
             return point_north_west + tripoint_below;
         case direction::NORTH:
             return tripoint_north;
         case direction::ABOVENORTH:
             return point_north + tripoint_above;
         case direction::BELOWNORTH:
             return point_north + tripoint_below;
         case direction::NORTHEAST:
             return tripoint_north_east;
         case direction::ABOVENORTHEAST:
             return point_north_east + tripoint_above;
         case direction::BELOWNORTHEAST:
             return point_north_east + tripoint_below;
         case direction::WEST:
             return tripoint_west;
         case direction::ABOVEWEST:
             return point_west + tripoint_above;
         case direction::BELOWWEST:
             return point_west + tripoint_below;
         case direction::CENTER:
             return tripoint_zero;
         case direction::ABOVECENTER:
             return tripoint_above;
         case direction::BELOWCENTER:
             return tripoint_below;
         case direction::EAST:
             return tripoint_east;
         case direction::ABOVEEAST:
             return point_east + tripoint_above;
         case direction::BELOWEAST:
             return point_east + tripoint_below;
         case direction::SOUTHWEST:
             return tripoint_south_west;
         case direction::ABOVESOUTHWEST:
             return point_south_west + tripoint_above;
         case direction::BELOWSOUTHWEST:
             return point_south_west + tripoint_below;
         case direction::SOUTH:
             return tripoint_south;
         case direction::ABOVESOUTH:
             return point_south + tripoint_above;
         case direction::BELOWSOUTH:
             return point_south + tripoint_below;
         case direction::SOUTHEAST:
             return tripoint_south_east;
         case direction::ABOVESOUTHEAST:
             return point_south_east + tripoint_above;
         case direction::BELOWSOUTHEAST:
             return point_south_east + tripoint_below;
         case direction::last:
             cata_fatal( "Invalid direction" );
     }
     return tripoint_zero;
 }
References ABOVECENTER, ABOVEEAST, ABOVENORTH, ABOVENORTHEAST, ABOVENORTHWEST, ABOVESOUTH, ABOVESOUTHEAST, ABOVESOUTHWEST, ABOVEWEST, BELOWCENTER, BELOWEAST, BELOWNORTH, BELOWNORTHEAST, BELOWNORTHWEST, BELOWSOUTH, BELOWSOUTHEAST, BELOWSOUTHWEST, BELOWWEST, cata_fatal, CENTER, EAST, last, NORTH, NORTHEAST, NORTHWEST, point_east, point_north, point_north_east, point_north_west, point_south, point_south_east, point_south_west, point_west, SOUTH, SOUTHEAST, SOUTHWEST, tripoint_above, tripoint_below, tripoint_east, tripoint_north, tripoint_north_east, tripoint_north_west, tripoint_south, tripoint_south_east, tripoint_south_west, tripoint_west, tripoint_zero, and WEST.
displace_XY()
point displace_XY (direction dir)
Definition at line 515 of file line.cpp.
 {
     switch( dir % 9 ) {
         case direction::NORTHWEST:
         case direction::ABOVENORTHWEST:
         case direction::BELOWNORTHWEST:
             return point_north_west;
         case direction::NORTH:
         case direction::ABOVENORTH:
         case direction::BELOWNORTH:
             return point_north;
         case direction::NORTHEAST:
         case direction::ABOVENORTHEAST:
         case direction::BELOWNORTHEAST:
             return point_north_east;
         case direction::WEST:
         case direction::ABOVEWEST:
         case direction::BELOWWEST:
             return point_west;
         case direction::CENTER:
         case direction::ABOVECENTER:
         case direction::BELOWCENTER:
             return point_zero;
         case direction::EAST:
         case direction::ABOVEEAST:
         case direction::BELOWEAST:
             return point_east;
         case direction::SOUTHWEST:
         case direction::ABOVESOUTHWEST:
         case direction::BELOWSOUTHWEST:
             return point_south_west;
         case direction::SOUTH:
         case direction::ABOVESOUTH:
         case direction::BELOWSOUTH:
             return point_south;
         case direction::SOUTHEAST:
         case direction::ABOVESOUTHEAST:
         case direction::BELOWSOUTHEAST:
             return point_south_east;
         case direction::last:
             cata_fatal( "Invalid direction" );
     }
     return point_zero;
 }
References ABOVECENTER, ABOVEEAST, ABOVENORTH, ABOVENORTHEAST, ABOVENORTHWEST, ABOVESOUTH, ABOVESOUTHEAST, ABOVESOUTHWEST, ABOVEWEST, BELOWCENTER, BELOWEAST, BELOWNORTH, BELOWNORTHEAST, BELOWNORTHWEST, BELOWSOUTH, BELOWSOUTHEAST, BELOWSOUTHWEST, BELOWWEST, cata_fatal, CENTER, EAST, last, NORTH, NORTHEAST, NORTHWEST, point_east, point_north, point_north_east, point_north_west, point_south, point_south_east, point_south_west, point_west, point_zero, SOUTH, SOUTHEAST, SOUTHWEST, and WEST.
Referenced by Pickup::autopickup(), scrollingcombattext::cSCT::cSCT(), npc::good_escape_direction(), and game::place_player().
get_normalized_angle()
float get_normalized_angle (const point & start, const point & end)
Definition at line 354 of file line.cpp.
 {
     // Taking the abs value of the difference puts the values in the first quadrant.
     const float absx = std::abs( std::max( start.x, end.x ) - std::min( start.x, end.x ) );
     const float absy = std::abs( std::max( start.y, end.y ) - std::min( start.y, end.y ) );
     const float max = std::max( absx, absy );
     if( max == 0 ) {
         return 0;
     }
     const float min = std::min( absx, absy );
     return min / max;
 }
References abs(), keycode::end, max(), min(), point::x, and point::y.
iso_tangent()
double iso_tangent (double distance, const units::angle & vertex)
Calculate base of an isosceles triangle.
Parameters
distance one of the equal lengths
vertex the unequal angle
Returns
base in equivalent units to distance
Definition at line 20 of file line.cpp.
 {
     return tan( vertex / 2 )  * distance * 2;
 }
References tan().
Referenced by confidence_estimate(), and projectile_attack_roll().
line_to() [1/2]
std::vector<point> line_to (const point & p1, const point & p2, int t = 0)
Definition at line 225 of file line.cpp.
 {
     std::vector<point> line;
     // Preallocate the number of cells we need instead of allocating them piecewise.
     const int numCells = square_dist( p1, p2 );
     if( numCells == 0 ) {
         line.push_back( p1 );
     } else {
         line.reserve( numCells );
         bresenham( p1, p2, t, [&line]( const point & new_point ) {
             line.push_back( new_point );
             return true;
         } );
     }
     return line;
 }
References bresenham(), line(), and square_dist().
Referenced by continue_line(), and squares_in_direction().
line_to() [2/2]
std::vector<tripoint> line_to (const tripoint & loc1, const tripoint & loc2, int t = 0, int t2 = 0)
Definition at line 242 of file line.cpp.
 {
     std::vector<tripoint> line;
     // Preallocate the number of cells we need instead of allocating them piecewise.
     const int numCells = square_dist( loc1, loc2 );
     if( numCells == 0 ) {
         line.push_back( loc1 );
     } else {
         line.reserve( numCells );
         bresenham( loc1, loc2, t, t2, [&line]( const tripoint & new_point ) {
             line.push_back( new_point );
             return true;
         } );
     }
     return line;
 }
References bresenham(), line(), and square_dist().
make_xyz()
unsigned make_xyz (const tripoint & p)
Definition at line 299 of file line.cpp.
 {
     static constexpr double sixteenth_arc = M_PI / 8;
     int vertical_position = ( ( p.z > 0 ) ? 2u : ( p.z < 0 ) ? 1u : 0u ) * 9u;
     if( p.xy() == point_zero ) {
         return vertical_position;
     }
     // Get the arctan of the angle and divide by approximately 22.5 deg to get the octant.
     // the angle is in, then truncate it and map to the right direction.
     // You can read 'octant' as being "number of 22.5 degree sections away from due south".
     // FIXME: atan2 normally takes arguments in ( y, x ) order.  This is
     // passing ( x, y ).
     int octant = atan2( p.x, p.y ) / sixteenth_arc;
     switch( octant ) {
         case 0:
             return direction::SOUTH + vertical_position;
         case 1:
         case 2:
             return direction::SOUTHEAST + vertical_position;
         case 3:
         case 4:
             return direction::EAST + vertical_position;
         case 5:
         case 6:
             return direction::NORTHEAST + vertical_position;
         case -1:
         case -2:
             return direction::SOUTHWEST + vertical_position;
         case -3:
         case -4:
             return direction::WEST + vertical_position;
         case -5:
         case -6:
             return direction::NORTHWEST + vertical_position;
         case 7:
         case 8:
         case -7:
         case -8:
         default:
             return direction::NORTH + vertical_position;
     }
 }
References atan2(), EAST, M_PI, NORTH, NORTHEAST, NORTHWEST, point_zero, SOUTH, SOUTHEAST, SOUTHWEST, u, WEST, tripoint::x, tripoint::xy(), tripoint::y, and tripoint::z.
Referenced by direction_from().
make_xyz_unit()
constexpr unsigned make_xyz_unit (const tripoint & p) inline constexpr noexcept
This compile-time usable function combines the sign of each (x, y, z) component into a single integer to allow simple runtime and compile-time mapping of (x, y, z) tuples to direction enumerators.
Specifically, (0, -, +) => (0, 1, 2); a base-3 number. This only works correctly for inputs between -1,-1,-1 and 1,1,1. For numbers outside that range, use make_xyz().
Definition at line 32 of file line.h.
 {
     return ( ( p.x > 0 ) ? 2u : ( p.x < 0 ) ? 1u : 0u ) * 1u +
            ( ( p.y > 0 ) ? 2u : ( p.y < 0 ) ? 1u : 0u ) * 3u +
            ( ( p.z > 0 ) ? 2u : ( p.z < 0 ) ? 1u : 0u ) * 9u;
 }
References u.
manhattan_dist()
int manhattan_dist (const point & loc1, const point & loc2)
Definition at line 267 of file line.cpp.
 {
     const point d = ( loc1 - loc2 ).abs();
     return d.x + d.y;
 }
References abs(), point::x, and point::y.
move_along_line()
tripoint move_along_line (const tripoint & loc, const std::vector< tripoint > & line, int distance)
Definition at line 367 of file line.cpp.
 {
     // May want to optimize this, but it's called fairly infrequently as part of specific attack
     // routines, erring on the side of readability.
     tripoint res( loc );
     const auto slope = slope_of( line );
     res.x += distance * std::get<0>( slope );
     res.y += distance * std::get<1>( slope );
     res.z += distance * std::get<2>( slope );
     return res;
 }
References line(), slope_of(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by continue_line(), and projectile_attack().
octile_dist()
int octile_dist (const point & loc1, const point & loc2, int multiplier = 1)
Definition at line 273 of file line.cpp.
 {
     const point d = ( loc1 - loc2 ).abs();
     const int mind = std::min( d.x, d.y );
     // sqrt(2) is approximately 99 / 70
     return ( d.x + d.y - 2 * mind ) * multiplier + mind * multiplier * 99 / 70;
 }
References abs(), min(), point::x, and point::y.
octile_dist_exact()
float octile_dist_exact (const point & loc1, const point & loc2)
Definition at line 281 of file line.cpp.
 {
     const point d = ( loc1 - loc2 ).abs();
     const int mind = std::min( d.x, d.y );
     return d.x + d.y - 2 * mind + mind * M_SQRT2;
 }
References abs(), M_SQRT2, min(), point::x, and point::y.
operator!=() [1/2]
template<class T > constexpr bool operator!= (const direction & lhs, const T & rhs) inline constexpr
Definition at line 121 of file line.h.
 {
     return !operator==( lhs, rhs );
 }
References operator==().
operator!=() [2/2]
template<class T > constexpr bool operator!= (const T & lhs, const direction & rhs) inline constexpr
Definition at line 115 of file line.h.
 {
     return !operator==( rhs, lhs );
 }
References operator==().
operator%()
template<class T > constexpr direction operator% (const direction & lhs, const T & rhs) inline constexpr
Definition at line 91 of file line.h.
 {
     return static_cast<direction>( static_cast<T>( lhs ) % rhs );
 }
operator+()
template<class T > constexpr T operator+ (const direction & lhs, const T & rhs) inline constexpr
Definition at line 97 of file line.h.
 {
     return static_cast<T>( lhs ) + rhs;
 }
operator==() [1/2]
template<class T > constexpr bool operator== (const direction & lhs, const T & rhs) inline constexpr
Definition at line 103 of file line.h.
 {
     return static_cast<T>( lhs ) == rhs;
 }
Referenced by operator!=(), and operator==().
operator==() [2/2]
template<class T > constexpr bool operator== (const T & lhs, const direction & rhs) inline constexpr
Definition at line 109 of file line.h.
 {
     return operator==( rhs, lhs );
 }
References operator==().
rl_dist() [1/2]
int rl_dist (const point & a, const point & b) inline
Definition at line 188 of file line.h.
 {
     return rl_dist( tripoint( a, 0 ), tripoint( b, 0 ) );
 }
References a, b, and rl_dist().
rl_dist() [2/2]
int rl_dist (const tripoint & loc1, const tripoint & loc2) inline
Definition at line 181 of file line.h.
 {
     if( trigdist ) {
         return trig_dist( loc1, loc2 );
     }
     return square_dist( loc1, loc2 );
 }
References square_dist(), trig_dist(), and trigdist.
Referenced by rl_dist().
rl_dist_exact()
float rl_dist_exact (const tripoint & loc1, const tripoint & loc2)
Definition at line 259 of file line.cpp.
 {
     if( trigdist ) {
         return trig_dist( loc1, loc2 );
     }
     return square_dist( loc1, loc2 );
 }
References square_dist(), trig_dist(), and trigdist.
Referenced by target_ui::dist_fn(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), Character::get_hostile_creatures(), Character::get_targetable_creatures(), game::safe_route_to(), and Character::sees_with_specials().
rl_dist_fast() [1/2]
FastDistanceApproximation rl_dist_fast (const point & a, const point & b) inline
Definition at line 244 of file line.h.
 {
     return rl_dist_fast( tripoint( a, 0 ), tripoint( b, 0 ) );
 }
References a, b, and rl_dist_fast().
rl_dist_fast() [2/2]
FastDistanceApproximation rl_dist_fast (const tripoint & loc1, const tripoint & loc2) inline
Definition at line 237 of file line.h.
 {
     if( trigdist ) {
         return trig_dist_fast( loc1, loc2 );
     }
     return square_dist_fast( loc1, loc2 );
 }
References square_dist_fast(), trig_dist_fast(), and trigdist.
Referenced by monster::rate_target(), and rl_dist_fast().
square_dist() [1/2]
int square_dist (const point & loc1, const point & loc2) inline
Definition at line 174 of file line.h.
 {
     const point d = ( loc1 - loc2 ).abs();
     return std::max( d.x, d.y );
 }
References abs(), max(), point::x, and point::y.
square_dist() [2/2]
int square_dist (const tripoint & loc1, const tripoint & loc2) inline
Definition at line 169 of file line.h.
 {
     const tripoint d = ( loc1 - loc2 ).abs();
     return std::max( { d.x, d.y, d.z } );
 }
References abs(), max(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by rl_dist().
square_dist_fast()
FastDistanceApproximation square_dist_fast (const tripoint & loc1, const tripoint & loc2) inline
Definition at line 232 of file line.h.
 {
     const tripoint d = ( loc1 - loc2 ).abs();
     return FastDistanceApproximation( std::max( { d.x, d.y, d.z } ) );
 }
References abs(), max(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by rl_dist_fast().
squares_closer_to()
std::vector<tripoint> squares_closer_to (const tripoint & from, const tripoint & to)
Definition at line 659 of file line.cpp.
 {
     std::vector<tripoint> adjacent_closer_squares;
     adjacent_closer_squares.reserve( 5 );
     const tripoint d( -from + to );
     const point a( std::abs( d.x ), std::abs( d.y ) );
     if( d.z != 0 ) {
         adjacent_closer_squares.push_back( from + tripoint( sgn( d.x ), sgn( d.y ), sgn( d.z ) ) );
     }
     if( a.x > a.y ) {
         // X dominant.
         adjacent_closer_squares.push_back( from + point( sgn( d.x ), 0 ) );
         adjacent_closer_squares.push_back( from + point( sgn( d.x ), 1 ) );
         adjacent_closer_squares.push_back( from + point( sgn( d.x ), -1 ) );
         if( d.y != 0 ) {
             adjacent_closer_squares.push_back( from + point( 0, sgn( d.y ) ) );
         }
     } else if( a.x < a.y ) {
         // Y dominant.
         adjacent_closer_squares.push_back( from + point( 0, sgn( d.y ) ) );
         adjacent_closer_squares.push_back( from + point( 1, sgn( d.y ) ) );
         adjacent_closer_squares.push_back( from + point( -1, sgn( d.y ) ) );
         if( d.x != 0 ) {
             adjacent_closer_squares.push_back( from + point( sgn( d.x ), 0 ) );
         }
     } else if( d.x != 0 ) {
         // Pure diagonal.
         adjacent_closer_squares.push_back( from + point( sgn( d.x ), sgn( d.y ) ) );
         adjacent_closer_squares.push_back( from + point( sgn( d.x ), 0 ) );
         adjacent_closer_squares.push_back( from + point( 0, sgn( d.y ) ) );
     }
     return adjacent_closer_squares;
 }
References a, abs(), sgn(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by monster::move().
squares_in_direction()
std::vector<point> squares_in_direction (const point & p1, const point & p2)
Definition at line 696 of file line.cpp.
 {
     int junk = 0;
     point center_square = line_to( p1, p2, junk )[0];
     std::vector<point> adjacent_squares;
     adjacent_squares.reserve( 3 );
     adjacent_squares.push_back( center_square );
     if( p1.x == center_square.x ) {
         // Horizontally adjacent.
         adjacent_squares.emplace_back( p1.x + 1, center_square.y );
         adjacent_squares.emplace_back( p1.x - 1, center_square.y );
     } else if( p1.y == center_square.y ) {
         // Vertically adjacent.
         adjacent_squares.emplace_back( center_square.x, p1.y + 1 );
         adjacent_squares.emplace_back( center_square.x, p1.y - 1 );
     } else {
         // Diagonally adjacent.
         adjacent_squares.emplace_back( p1.x, center_square.y );
         adjacent_squares.emplace_back( center_square.x, p1.y );
     }
     return adjacent_squares;
 }
References line_to(), point::x, and point::y.
Referenced by get_bashing_zone(), and MapExtras::mx_minefield().
trig_dist() [1/2]
float trig_dist (const point & loc1, const point & loc2) inline
Definition at line 163 of file line.h.
 {
     return trig_dist( tripoint( loc1, 0 ), tripoint( loc2, 0 ) );
 }
References trig_dist().
trig_dist() [2/2]
float trig_dist (const tripoint & loc1, const tripoint & loc2) inline
Definition at line 157 of file line.h.
 {
     return std::sqrt( static_cast<double>( ( loc1.x - loc2.x ) * ( loc1.x - loc2.x ) ) +
                       ( ( loc1.y - loc2.y ) * ( loc1.y - loc2.y ) ) +
                       ( ( loc1.z - loc2.z ) * ( loc1.z - loc2.z ) ) );
 }
References sqrt(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by rl_dist(), and trig_dist().
trig_dist_fast()
FastDistanceApproximation trig_dist_fast (const tripoint & loc1, const tripoint & loc2) inline
Definition at line 225 of file line.h.
 {
     return FastDistanceApproximation(
                ( loc1.x - loc2.x ) * ( loc1.x - loc2.x ) +
                ( loc1.y - loc2.y ) * ( loc1.y - loc2.y ) +
                ( loc1.z - loc2.z ) * ( loc1.z - loc2.z ) );
 }
References tripoint::x, tripoint::y, and tripoint::z.
Referenced by rl_dist_fast().
Variable Documentation
trigdist
bool trigdist extern
Definition at line 18 of file line.cpp.
Referenced by calc_ray_end(), leap_actor::call(), map::combined_movecost(), explosion_handler::do_blast(), get_stagger_adjust(), npc::move_to(), om_range_mark(), FastDistanceApproximation::operator int(), FastDistanceApproximation::operator<=(), FastDistanceApproximation::operator>=(), overmapbuffer::reveal(), rl_dist(), rl_dist_exact(), rl_dist_fast(), target_ui::set_cursor_pos(), spell_effect::spell_effect_line(), avatar_action::swim(), options_manager::update_options_cache(), game::update_overmap_seen(), and game::walk_move().