Cataclysm DDA: src/magic_teleporter_list.cpp File Reference
magic_teleporter_list.cpp File Reference
#include "magic_teleporter_list.h"
#include <algorithm>
#include <cstddef>
#include <map>
#include <memory>
#include <new>
#include <string>
#include <utility>
#include "avatar.h"
#include "calendar.h"
#include "catacharset.h"
#include "character.h"
#include "color.h"
#include "coordinates.h"
#include "creature_tracker.h"
#include "cursesdef.h"
#include "enums.h"
#include "game.h"
#include "json.h"
#include "map.h"
#include "map_iterator.h"
#include "messages.h"
#include "output.h"
#include "panels.h"
#include "point.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
Classes
class teleporter_callback
Functions
static bool popup_string (std::string &result, std::string &title)
static std::optional< tripoint > find_valid_teleporters_omt (const tripoint_abs_omt &omt_pt)
Variables
static const efftype_id effect_ignore_fall_damage ("ignore_fall_damage")
Function Documentation
find_valid_teleporters_omt()
static std::optional<tripoint> find_valid_teleporters_omt (const tripoint_abs_omt & omt_pt) static
Definition at line 64 of file magic_teleporter_list.cpp.
 {
     // this is the top left hand square of the global absolute coordinate
     // of the overmap terrain we want to try to teleport to.
     // an OMT is (2 * SEEX) * (2 * SEEY) in size
     tinymap checker;
     checker.load( omt_pt, true );
     for( const tripoint &p : checker.points_on_zlevel() ) {
         if( checker.has_flag_furn( ter_furn_flag::TFLAG_TRANSLOCATOR, p ) ) {
             return checker.getabs( p );
         }
     }
     return std::nullopt;
 }
References tinymap::getabs(), tinymap::has_flag_furn(), tinymap::load(), tinymap::points_on_zlevel(), and TFLAG_TRANSLOCATOR.
Referenced by teleporter_list::place_avatar_overmap().
popup_string()
static bool popup_string (std::string & result, std::string & title) static
Definition at line 36 of file magic_teleporter_list.cpp.
 {
     string_input_popup popup;
     popup.title( title );
     popup.text( "" ).only_digits( false );
     popup.query();
     if( popup.canceled() ) {
         return false;
     }
     result = popup.text();
     return true;
 }
References popup(), and music::title.
Referenced by teleporter_list::activate_teleporter().
Variable Documentation
effect_ignore_fall_damage
const efftype_id effect_ignore_fall_damage("ignore_fall_damage") ("ignore_fall_damage") static
Referenced by teleporter_list::place_avatar_overmap().