Cataclysm DDA: src/magic_spell_effect_helpers.h File Reference
magic_spell_effect_helpers.h File Reference
#include <functional>
#include <set>
Macros
#define CATA_SRC_MAGIC_SPELL_EFFECT_HELPERS_H
Functions
std::set< tripoint > calculate_spell_effect_area (const spell &sp, const tripoint &target, const Creature &caster)
Macro Definition Documentation
CATA_SRC_MAGIC_SPELL_EFFECT_HELPERS_H
#define CATA_SRC_MAGIC_SPELL_EFFECT_HELPERS_H
Definition at line 3 of file magic_spell_effect_helpers.h.
Function Documentation
calculate_spell_effect_area()
std::set<tripoint> calculate_spell_effect_area (const spell & sp, const tripoint & target, const Creature & caster)
Definition at line 426 of file magic_spell_effect.cpp.
 {
     // the actual target that the spell will hit.
     tripoint epicenter( target );
     // stop short if we hit a wall, if the spell has a projectile
     if( sp.shape() == spell_shape::blast && !sp.has_flag( spell_flag::NO_PROJECTILE ) ) {
         std::vector<tripoint> trajectory = line_to( caster.pos(), target );
         for( std::vector<tripoint>::iterator iter = trajectory.begin(); iter != trajectory.end(); iter++ ) {
             if( get_map().impassable( *iter ) ) {
                 if( iter != trajectory.begin() ) {
                     epicenter = *( iter - 1 );
                 } else {
                     epicenter = *iter;
                 }
                 break;
             }
         }
     }
     std::set<tripoint> targets = { epicenter }; // initialize with epicenter
     if( sp.aoe( caster ) < 1 && sp.shape() != spell_shape::line ) {
         return targets;
     }
     targets = sp.effect_area( caster.pos(), target, caster );
     for( std::set<tripoint>::iterator it = targets.begin(); it != targets.end(); ) {
         if( !sp.is_valid_target( caster, *it ) ) {
             it = targets.erase( it );
         } else {
             ++it;
         }
     }
     return targets;
 }
References spell::aoe(), blast, spell::effect_area(), get_map(), spell::has_flag(), impassable, spell::is_valid_target(), line, line_to(), NO_PROJECTILE, Creature::pos(), and spell::shape().
Referenced by npc_attack_spell::evaluate_tripoint(), spell_effect::short_range_teleport(), and spell_effect_area().