Cataclysm DDA: src/magic_spell_effect.cpp File Reference
magic_spell_effect.cpp File Reference
#include <algorithm>
#include <array>
#include <climits>
#include <cmath>
#include <cstddef>
#include <cstdlib>
#include <iosfwd>
#include <iterator>
#include <map>
#include <memory>
#include <new>
#include <optional>
#include <queue>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "avatar.h"
#include "bodypart.h"
#include "calendar.h"
#include "character.h"
#include "character_martial_arts.h"
#include "colony.h"
#include "color.h"
#include "coordinates.h"
#include "creature.h"
#include "creature_tracker.h"
#include "damage.h"
#include "debug.h"
#include "effect_on_condition.h"
#include "enums.h"
#include "explosion.h"
#include "field.h"
#include "field_type.h"
#include "fungal_effects.h"
#include "game.h"
#include "item.h"
#include "kill_tracker.h"
#include "line.h"
#include "magic.h"
#include "magic_spell_effect_helpers.h"
#include "magic_teleporter_list.h"
#include "magic_ter_furn_transform.h"
#include "map.h"
#include "map_iterator.h"
#include "messages.h"
#include "mongroup.h"
#include "monster.h"
#include "monstergenerator.h"
#include "morale.h"
#include "morale_types.h"
#include "mtype.h"
#include "npc.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "point.h"
#include "projectile.h"
#include "ret_val.h"
#include "rng.h"
#include "string_formatter.h"
#include "teleport.h"
#include "timed_event.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "vehicle.h"
#include "vpart_position.h"
Classes
struct spell_detail::line_iterable
Namespaces
spell_detail
Functions
static int spell_detail::side_of (const point &a, const point &b, const point &c)
static bool spell_detail::between_or_on (const point &a0, const point &a1, const point &d, const point &c)
static void spell_detail::build_line (spell_detail::line_iterable line, const tripoint &source, const point &delta, const point &delta_perp, bool(*test)(const tripoint &), std::set< tripoint > &result)
static void swap_pos (Creature &caster, const tripoint &target)
static bool in_spell_aoe (const tripoint &start, const tripoint &end, const int &radius, const bool ignore_walls)
static std::set< tripoint > spell_effect_cone_range_override (const spell_effect::override_parameters &params, const tripoint &source, const tripoint &target)
static bool test_always_true (const tripoint &)
static bool test_passable (const tripoint &p)
std::set< tripoint > calculate_spell_effect_area (const spell &sp, const tripoint &target, const Creature &caster)
static std::set< tripoint > spell_effect_area (const spell &sp, const tripoint &target, const Creature &caster)
static void add_effect_to_target (const tripoint &target, const spell &sp, Creature &caster)
static void damage_targets (const spell &sp, Creature &caster, const std::set< tripoint > &targets)
static void magical_polymorph (monster &victim, Creature &caster, const spell &sp)
static void move_items (map &here, const tripoint &from, const tripoint &to)
static void move_field (map &here, const tripoint &from, const tripoint &to)
static void spell_move (const spell &sp, const Creature &caster, const tripoint &from, const tripoint &to)
static std::pair< field, tripoint > spell_remove_field (const spell &sp, const field_type_id &target_field_type_id, const tripoint &center, const Creature &caster)
static void handle_remove_fd_reality_tear_field (const std::pair< field, tripoint > &fd_reality_tear_field, Creature &caster)
static void character_push_effects (Creature *caster, Character &guy, tripoint &push_dest, const int push_distance, const std::vector< tripoint > &push_vec)
static bool is_summon_friendly (const spell &sp)
static bool add_summoned_mon (const tripoint &pos, const time_duration &time, const spell &sp, Creature &caster)
Variables
static const efftype_id effect_teleglow ("teleglow")
static const flag_id json_flag_FIT ("FIT")
static const json_character_flag json_flag_PRED1 ("PRED1")
static const json_character_flag json_flag_PRED2 ("PRED2")
static const json_character_flag json_flag_PRED3 ("PRED3")
static const json_character_flag json_flag_PRED4 ("PRED4")
static const mtype_id mon_blob ("mon_blob")
static const mtype_id mon_blob_brain ("mon_blob_brain")
static const mtype_id mon_blob_large ("mon_blob_large")
static const mtype_id mon_blob_small ("mon_blob_small")
static const mtype_id mon_generator ("mon_generator")
static const species_id species_HALLUCINATION ("HALLUCINATION")
static const species_id species_SLIME ("SLIME")
static const trait_id trait_KILLER ("KILLER")
static const trait_id trait_PACIFIST ("PACIFIST")
static const trait_id trait_PSYCHOPATH ("PSYCHOPATH")
static const trait_id trait_PYROMANIA ("PYROMANIA")
Function Documentation
add_effect_to_target()
static void add_effect_to_target (const tripoint & target, const spell & sp, Creature & caster) static
Definition at line 485 of file magic_spell_effect.cpp.
 {
     const int dur_moves = sp.duration( caster );
     const time_duration dur_td = time_duration::from_moves( dur_moves );
     creature_tracker &creatures = get_creature_tracker();
     Creature *const critter = creatures.creature_at<Creature>( target );
     Character *const guy = creatures.creature_at<Character>( target );
     efftype_id spell_effect( sp.effect_data() );
     bool bodypart_effected = false;
     if( guy ) {
         for( const bodypart_id &bp : guy->get_all_body_parts() ) {
             if( sp.bp_is_affected( bp.id() ) ) {
                 guy->add_effect( spell_effect, dur_td, bp, sp.has_flag( spell_flag::PERMANENT ) );
                 bodypart_effected = true;
             }
         }
     }
     if( !bodypart_effected ) {
         critter->add_effect( spell_effect, dur_td );
     }
 }
References Creature::add_effect(), bp, spell::bp_is_affected(), creature_tracker::creature_at(), spell::duration(), spell::effect_data(), time_duration::from_moves(), get_creature_tracker(), spell::has_flag(), int_id< T >::id(), and PERMANENT.
Referenced by damage_targets().
add_summoned_mon()
static bool add_summoned_mon (const tripoint & pos, const time_duration & time, const spell & sp, Creature & caster) static
Definition at line 1200 of file magic_spell_effect.cpp.
 {
     std::string monster_id = sp.effect_data();
     // Spawn a monster from a group, or a specific monster ID
     if( sp.has_flag( spell_flag::SPAWN_GROUP ) ) {
         const mongroup_id group_id( sp.effect_data() );
         monster_id = MonsterGroupManager::GetRandomMonsterFromGroup( group_id ).str();
     }
     const mtype_id mon_id( monster_id );
     monster *const mon_ptr = g->place_critter_at( mon_id, pos );
     if( !mon_ptr ) {
         return false;
     }
     const bool permanent = sp.has_flag( spell_flag::PERMANENT );
     monster &spawned_mon = *mon_ptr;
     if( is_summon_friendly( sp ) ) {
         spawned_mon.friendly = INT_MAX;
     } else {
         spawned_mon.friendly = 0;
     }
     if( !permanent ) {
         spawned_mon.set_summon_time( time );
     }
     spawned_mon.no_extra_death_drops = !sp.has_flag( spell_flag::SPAWN_WITH_DEATH_DROPS );
     spawned_mon.no_corpse_quiet = sp.has_flag( spell_flag::NO_CORPSE_QUIET );
     spawned_mon.set_summoner( &caster );
     return true;
 }
References spell::effect_data(), monster::friendly, g, MonsterGroupManager::GetRandomMonsterFromGroup(), spell::has_flag(), is_summon_friendly(), NO_CORPSE_QUIET, monster::no_corpse_quiet, monster::no_extra_death_drops, permanent, PERMANENT, math_opers::pos(), Creature::set_summon_time(), Creature::set_summoner(), SPAWN_GROUP, SPAWN_WITH_DEATH_DROPS, and string_id< T >::str().
Referenced by spell_effect::spawn_summoned_monster().
calculate_spell_effect_area()
std::set<tripoint> calculate_spell_effect_area (const spell & sp, const tripoint & target, const Creature & caster)
Definition at line 426 of file magic_spell_effect.cpp.
 {
     // the actual target that the spell will hit.
     tripoint epicenter( target );
     // stop short if we hit a wall, if the spell has a projectile
     if( sp.shape() == spell_shape::blast && !sp.has_flag( spell_flag::NO_PROJECTILE ) ) {
         std::vector<tripoint> trajectory = line_to( caster.pos(), target );
         for( std::vector<tripoint>::iterator iter = trajectory.begin(); iter != trajectory.end(); iter++ ) {
             if( get_map().impassable( *iter ) ) {
                 if( iter != trajectory.begin() ) {
                     epicenter = *( iter - 1 );
                 } else {
                     epicenter = *iter;
                 }
                 break;
             }
         }
     }
     std::set<tripoint> targets = { epicenter }; // initialize with epicenter
     if( sp.aoe( caster ) < 1 && sp.shape() != spell_shape::line ) {
         return targets;
     }
     targets = sp.effect_area( caster.pos(), target, caster );
     for( std::set<tripoint>::iterator it = targets.begin(); it != targets.end(); ) {
         if( !sp.is_valid_target( caster, *it ) ) {
             it = targets.erase( it );
         } else {
             ++it;
         }
     }
     return targets;
 }
References spell::aoe(), blast, spell::effect_area(), get_map(), spell::has_flag(), impassable, spell::is_valid_target(), line, line_to(), NO_PROJECTILE, Creature::pos(), and spell::shape().
Referenced by npc_attack_spell::evaluate_tripoint(), spell_effect::short_range_teleport(), and spell_effect_area().
character_push_effects()
static void character_push_effects (Creature * caster, Character & guy, tripoint & push_dest, const int push_distance, const std::vector< tripoint > & push_vec) static
Definition at line 961 of file magic_spell_effect.cpp.
 {
     int dist_left = std::abs( push_distance );
     tripoint old_pushed_point = guy.pos();
     for( const tripoint &pushed_point : push_vec ) {
         if( get_map().impassable( pushed_point ) ) {
             guy.hurtall( dist_left * 4, caster );
             push_dest = old_pushed_point;
             break;
         } else if( get_creature_tracker().creature_at( pushed_point ) ) {
             push_dest = old_pushed_point;
             break;
         } else {
             dist_left--;
             old_pushed_point = pushed_point;
         }
     }
     guy.setpos( push_dest );
 }
References abs(), get_creature_tracker(), get_map(), Character::hurtall(), impassable, Creature::pos(), and Creature::setpos().
Referenced by spell_effect::directed_push().
damage_targets()
static void damage_targets (const spell & sp, Creature & caster, const std::set< tripoint > & targets) static
Definition at line 508 of file magic_spell_effect.cpp.
 {
     map &here = get_map();
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &target : targets ) {
         if( !sp.is_valid_target( caster, target ) ) {
             continue;
         }
         sp.make_sound( target, caster );
         sp.create_field( target, caster );
         if( sp.has_flag( spell_flag::IGNITE_FLAMMABLE ) && here.is_flammable( target ) ) {
             here.add_field( target, fd_fire, 1, 10_minutes );
             Character &player_character = get_player_character();
             if( player_character.has_trait( trait_PYROMANIA ) &&
                 !player_character.has_morale( MORALE_PYROMANIA_STARTFIRE ) ) {
                 player_character.add_msg_if_player( m_good,
                                                     _( "You feel a surge of euphoria as flames burst out!" ) );
                 player_character.add_morale( MORALE_PYROMANIA_STARTFIRE, 15, 15, 8_hours, 6_hours );
                 player_character.rem_morale( MORALE_PYROMANIA_NOFIRE );
             }
         }
         Creature *const cr = creatures.creature_at<Creature>( target );
         if( !cr ) {
             continue;
         }
         dealt_projectile_attack atk = sp.get_projectile_attack( target, *cr, caster );
         const int spell_accuracy = sp.accuracy( caster );
         if( !sp.effect_data().empty() ) {
             add_effect_to_target( target, sp, caster );
         }
         if( sp.damage( caster ) > 0 ) {
             // calculate damage mitigation from various sources
             // 5% per point (linear) ranging from 0-33%, capped at block score
             double damage_mitigation_multiplier = 1.0;
             if( const int spell_block = cr->get_block_bonus() - spell_accuracy > 0 ) {
                 const int roll = std::round( rng( 1, 20 ) );
                 damage_mitigation_multiplier -= ( 1 - 0.05 * std::max( roll, spell_block ) ) / 3.0;
             }
             if( cr->dodge_check( spell_accuracy ) ) {
                 const int spell_dodge = cr->get_dodge() - spell_accuracy;
                 const int roll = std::round( rng( 1, 20 ) );
                 damage_mitigation_multiplier -= ( 1 - 0.05 * std::max( roll, spell_dodge ) ) / 3.0;
             }
             if( const int spell_resist = cr->get_spell_resist() - spell_accuracy > 0 &&
                                          !sp.has_flag( spell_flag::NON_MAGICAL ) ) {
                 const int roll = std::round( rng( 1, 20 ) );
                 damage_mitigation_multiplier -= ( 1 - 0.05 * std::max( roll, spell_resist ) ) / 3.0;
             }
             for( damage_unit &val : atk.proj.impact.damage_units ) {
                 if( sp.has_flag( spell_flag::PERCENTAGE_DAMAGE ) ) {
                     // TODO: Change once spells don't always target get_max_hitsize_bodypart(). Should target each bodypart with it's respecive %
                     val.amount = cr->get_hp( cr->get_max_hitsize_bodypart() ) * sp.damage( caster ) / 100.0;
                 }
                 val.amount *= damage_mitigation_multiplier;
             }
             cr->deal_projectile_attack( &caster, atk, true );
         } else if( sp.damage( caster ) < 0 ) {
             sp.heal( target, caster );
             add_msg_if_player_sees( cr->pos(), m_good, _( "%s wounds are closing up!" ),
                                     cr->disp_name( true ) );
         }
         // TODO: randomize hit location
         cr->add_damage_over_time( sp.damage_over_time( { body_part_torso }, caster ) );
     }
 }
References _, spell::accuracy(), Creature::add_damage_over_time(), add_effect_to_target(), map::add_field(), Character::add_morale(), Character::add_msg_if_player(), add_msg_if_player_sees(), damage_unit::amount, spell::create_field(), creature_tracker::creature_at(), spell::damage(), spell::damage_over_time(), damage_instance::damage_units, Creature::deal_projectile_attack(), Creature::disp_name(), Creature::dodge_check(), spell::effect_data(), fd_fire, Creature::get_block_bonus(), get_creature_tracker(), Creature::get_dodge(), Creature::get_hp(), get_map(), Creature::get_max_hitsize_bodypart(), get_player_character(), spell::get_projectile_attack(), Creature::get_spell_resist(), spell::has_flag(), Character::has_morale(), Character::has_trait(), spell::heal(), IGNITE_FLAMMABLE, projectile::impact, map::is_flammable(), spell::is_valid_target(), m_good, spell::make_sound(), max(), MORALE_PYROMANIA_NOFIRE, MORALE_PYROMANIA_STARTFIRE, NON_MAGICAL, PERCENTAGE_DAMAGE, Creature::pos(), dealt_projectile_attack::proj, Character::rem_morale(), rng(), round(), and trait_PYROMANIA.
Referenced by spell_effect::attack(), and spell_effect::dash().
handle_remove_fd_reality_tear_field()
static void handle_remove_fd_reality_tear_field (const std::pair< field, tripoint > & fd_reality_tear_field, Creature & caster) static
Definition at line 855 of file magic_spell_effect.cpp.
 {
     for( const std::pair<const field_type_id, field_entry> &fd : std::get<0>
          ( fd_reality_tear_field ) ) {
         const int &intensity = fd.second.get_field_intensity();
         const translation &intensity_name = fd.second.get_intensity_level().name;
         const tripoint &field_position = std::get<1>( fd_reality_tear_field );
         const bool sees_field = caster.sees( field_position );
         switch( intensity ) {
             case 1:
                 if( sees_field ) {
                     caster.add_msg_if_player( m_neutral, _( "The %s fades.  You feel strange." ), intensity_name );
                 } else {
                     caster.add_msg_if_player( m_neutral, _( "You suddenly feel strange." ) );
                 }
                 caster.add_effect( effect_teleglow, 1_hours );
                 break;
             case 2:
                 if( sees_field ) {
                     caster.add_msg_if_player( m_neutral, _( "The %s dissipates.  You feel strange." ), intensity_name );
                 } else {
                     caster.add_msg_if_player( m_neutral, _( "You suddenly feel strange." ) );
                 }
                 caster.add_effect( effect_teleglow, 5_hours );
                 break;
             case 3:
                 std::string message_prefix = "A nearby";
                 if( caster.sees( field_position ) ) {
                     message_prefix = "The";
                 }
                 caster.add_msg_if_player( m_bad,
                                           _( "%s %s pulls you in as it closes and ejects you violently!" ),
                                           message_prefix, intensity_name );
                 caster.as_character()->hurtall( 10, nullptr );
                 caster.add_effect( effect_teleglow, 630_minutes );
                 teleport::teleport( caster );
                 break;
         }
         break;
     }
 }
References _, Creature::add_effect(), Creature::add_msg_if_player(), Creature::as_character(), effect_teleglow, Character::hurtall(), intensity, m_bad, m_neutral, Creature::sees(), and teleport::teleport().
Referenced by spell_effect::remove_field().
in_spell_aoe()
static bool in_spell_aoe (const tripoint & start, const tripoint & end, const int & radius, const bool ignore_walls) static
Definition at line 206 of file magic_spell_effect.cpp.
 {
     if( rl_dist( start, end ) > radius ) {
         return false;
     }
     if( ignore_walls ) {
         return true;
     }
     map &here = get_map();
     const std::vector<tripoint> trajectory = line_to( start, end );
     for( const tripoint &pt : trajectory ) {
         if( here.impassable( pt ) ) {
             return false;
         }
     }
     return true;
 }
References keycode::end, get_map(), map::impassable(), line_to(), and rl_dist().
Referenced by spell_effect::spell_effect_blast().
is_summon_friendly()
static bool is_summon_friendly (const spell & sp) static
Definition at line 1190 of file magic_spell_effect.cpp.
 {
     const bool hostile = sp.has_flag( spell_flag::HOSTILE_SUMMON );
     bool friendly = !hostile;
     if( sp.has_flag( spell_flag::HOSTILE_50 ) ) {
         friendly = friendly && rng( 0, 1000 ) < 500;
     }
     return friendly;
 }
References friendly, spell::has_flag(), hostile, HOSTILE_50, HOSTILE_SUMMON, and rng().
Referenced by add_summoned_mon().
magical_polymorph()
static void magical_polymorph (monster & victim, Creature & caster, const spell & sp) static
Definition at line 590 of file magic_spell_effect.cpp.
 {
     mtype_id new_id = mtype_id( sp.effect_data() );
     if( sp.has_flag( spell_flag::POLYMORPH_GROUP ) ) {
         const mongroup_id group_id( sp.effect_data() );
         new_id = MonsterGroupManager::GetRandomMonsterFromGroup( group_id );
     }
     // if effect_str is empty, we become a random monster of close difficulty
     if( new_id.is_empty() ) {
         int victim_diff = victim.type->difficulty;
         const std::vector<mtype> &mtypes = MonsterGenerator::generator().get_all_mtypes();
         for( int difficulty_variance = 1; difficulty_variance < 2048; difficulty_variance *= 2 ) {
             unsigned int random_entry = rng( 0, mtypes.size() );
             unsigned int iter = random_entry + 1;
             while( iter != random_entry && new_id.is_empty() ) {
                 if( iter >= mtypes.size() ) {
                     iter = 0;
                 }
                 if( ( mtypes[iter].id != victim.type->id ) && ( std::abs( mtypes[iter].difficulty - victim_diff )
                         <= difficulty_variance ) ) {
                     if( !mtypes[iter].in_species( species_HALLUCINATION ) &&
                         mtypes[iter].id != mon_generator ) {
                         new_id = mtypes[iter].id;
                         break;
                     }
                 }
                 iter++;
             }
         }
     }
     if( !new_id.is_valid() ) {
         debugmsg( "magical_polymorph called with an invalid monster id" );
         return;
     }
     add_msg_if_player_sees( victim, _( "The %s transforms into a %s." ),
                             victim.type->nname(), new_id->nname() );
     victim.poly( new_id );
     if( sp.has_flag( spell_flag::FRIENDLY_POLY ) ) {
         if( caster.as_character() ) {
             victim.friendly = -1;
         } else {
             victim.make_ally( *caster.as_monster() );
         }
     }
 }
References _, abs(), add_msg_if_player_sees(), Creature::as_character(), Creature::as_monster(), debugmsg, mtype::difficulty, spell::effect_data(), monster::friendly, FRIENDLY_POLY, MonsterGenerator::generator(), MonsterGenerator::get_all_mtypes(), MonsterGroupManager::GetRandomMonsterFromGroup(), spell::has_flag(), mtype::id, string_id< T >::id(), string_id< T >::is_empty(), string_id< T >::is_valid(), monster::make_ally(), mon_generator, mtype::nname(), monster::poly(), POLYMORPH_GROUP, random_entry(), rng(), species_HALLUCINATION, and monster::type.
Referenced by spell_effect::targeted_polymorph().
move_field()
static void move_field (map & here, const tripoint & from, const tripoint & to) static
Definition at line 756 of file magic_spell_effect.cpp.
 {
     field &src_field = here.field_at( from );
     std::map<field_type_id, int> moving_fields;
     for( const std::pair<const field_type_id, field_entry> &fd : src_field ) {
         if( fd.first.is_valid() && !fd.first.id().is_null() ) {
             const int intensity = fd.second.get_field_intensity();
             moving_fields.emplace( fd.first, intensity );
         }
     }
     for( const std::pair<const field_type_id, int> &fd : moving_fields ) {
         here.remove_field( from, fd.first );
         here.set_field_intensity( to, fd.first, fd.second );
     }
 }
References map::field_at(), intensity, map::remove_field(), and map::set_field_intensity().
Referenced by spell_effect::directed_push(), and spell_move().
move_items()
static void move_items (map & here, const tripoint & from, const tripoint & to) static
Definition at line 748 of file magic_spell_effect.cpp.
 {
     for( const item &it : here.i_at( from ) ) {
         here.add_item( to, it );
     }
     here.i_clear( from );
 }
References map::add_item(), map::i_at(), and map::i_clear().
Referenced by spell_effect::directed_push(), and spell_move().
spell_effect_area()
static std::set<tripoint> spell_effect_area (const spell & sp, const tripoint & target, const Creature & caster) static
Definition at line 465 of file magic_spell_effect.cpp.
 {
     // calculate spell's effect area
     std::set<tripoint> targets = calculate_spell_effect_area( sp, target, caster );
     if( !sp.has_flag( spell_flag::NO_EXPLOSION_SFX ) ) {
         // Draw the explosion
         std::map<tripoint, nc_color> explosion_colors;
         for( const tripoint &pt : targets ) {
             explosion_colors[pt] = sp.damage_type_color();
         }
         std::string exp_name = "explosion_" + sp.id().str();
         explosion_handler::draw_custom_explosion( get_player_character().pos(), explosion_colors,
                 exp_name );
     }
     return targets;
 }
References calculate_spell_effect_area(), spell::damage_type_color(), explosion_handler::draw_custom_explosion(), get_player_character(), spell::has_flag(), spell::id(), NO_EXPLOSION_SFX, math_opers::pos(), and string_id< T >::str().
Referenced by spell_effect::attack(), spell_effect::banishment(), spell_effect::bash(), spell_effect::charm_monster(), spell_effect::directed_push(), spell_effect::effect_on_condition(), spell_effect::emit(), spell_effect::fungalize(), spell_effect::guilt(), spell_effect::mod_moves(), spell_effect::morale(), spell_effect::mutate(), spell_effect::remove_effect(), spell_effect::revive(), spell_effect::revive_dormant(), spell_effect::spawn_summoned_monster(), spell_effect::transform_blast(), spell_effect::translocate(), spell_effect::upgrade(), and spell_effect::vomit().
spell_effect_cone_range_override()
static std::set<tripoint> spell_effect_cone_range_override (const spell_effect::override_parameters & params, const tripoint & source, const tripoint & target) static
Definition at line 239 of file magic_spell_effect.cpp.
 {
     std::set<tripoint> targets;
     const units::angle initial_angle = coord_to_angle( source, target );
     const units::angle half_width = units::from_degrees( params.aoe_radius / 2.0 );
     const units::angle start_angle = initial_angle - half_width;
     const units::angle end_angle = initial_angle + half_width;
     std::set<tripoint> end_points;
     for( units::angle angle = start_angle; angle <= end_angle; angle += 1_degrees ) {
         for( int range = 1; range <= params.range; range++ ) {
             tripoint potential;
             calc_ray_end( angle, range, source, potential );
             if( params.ignore_walls ) {
                 targets.emplace( potential );
             } else {
                 end_points.emplace( potential );
             }
         }
     }
     if( !params.ignore_walls ) {
         map &here = get_map();
         for( const tripoint &ep : end_points ) {
             std::vector<tripoint> trajectory = line_to( source, ep );
             for( const tripoint &tp : trajectory ) {
                 if( here.passable( tp ) ) {
                     targets.emplace( tp );
                 } else {
                     break;
                 }
             }
         }
     }
     // we don't want to hit ourselves in the blast!
     targets.erase( source );
     return targets;
 }
References spell_effect::override_parameters::aoe_radius, calc_ray_end(), coord_to_angle(), units::from_degrees(), get_map(), spell_effect::override_parameters::ignore_walls, line_to(), map::passable(), and spell_effect::override_parameters::range.
Referenced by spell_effect::dash(), and spell_effect::spell_effect_cone().
spell_move()
static void spell_move (const spell & sp, const Creature & caster, const tripoint & from, const tripoint & to) static
Definition at line 773 of file magic_spell_effect.cpp.
 {
     if( from == to ) {
         return;
     }
     // Moving creatures
     const bool can_target_self = sp.is_valid_target( spell_target::self );
     const bool can_target_ally = sp.is_valid_target( spell_target::ally );
     const bool can_target_hostile = sp.is_valid_target( spell_target::hostile );
     const bool can_target_creature = can_target_self || can_target_ally || can_target_hostile;
     if( can_target_creature ) {
         if( Creature *victim = get_creature_tracker().creature_at<Creature>( from ) ) {
             Creature::Attitude cr_att = victim->attitude_to( get_player_character() );
             bool valid = cr_att != Creature::Attitude::FRIENDLY && can_target_hostile;
             if( victim == &caster ) {
                 valid = can_target_self;
             } else {
                 valid |= cr_att == Creature::Attitude::FRIENDLY && can_target_ally;
                 valid |= victim == &caster && can_target_self;
             }
             if( valid ) {
                 victim->knock_back_to( to );
             }
         }
     }
     // Moving items
     if( sp.is_valid_target( spell_target::item ) ) {
         move_items( get_map(), from, to );
     }
     // Moving fields.
     if( sp.is_valid_target( spell_target::field ) ) {
         move_field( get_map(), from, to );
     }
 }
References ally, field, Creature::FRIENDLY, get_creature_tracker(), get_map(), get_player_character(), hostile, spell::is_valid_target(), item, Creature::knock_back_to(), move_field(), move_items(), and self.
Referenced by spell_effect::area_pull(), and spell_effect::area_push().
spell_remove_field()
static std::pair<field, tripoint> spell_remove_field (const spell & sp, const field_type_id & target_field_type_id, const tripoint & center, const Creature & caster) static
Definition at line 813 of file magic_spell_effect.cpp.
 {
     ::map &here = get_map();
     area_expander expander;
     expander.max_range = sp.aoe( caster );
     expander.run( center );
     expander.sort_ascending();
     field field_removed = field();
     tripoint field_position = tripoint();
     bool did_field_removal = false;
     for( const area_expander::node &node : expander.area ) {
         if( node.from == node.position ) {
             continue;
         }
         field &target_field = here.field_at( node.position );
         for( const std::pair<const field_type_id, field_entry> &fd : target_field ) {
             if( fd.first.is_valid() && !fd.first.id().is_null() &&
                 fd.second.get_field_type() == target_field_type_id ) {
                 field_removed = target_field;
                 field_position = node.position;
                 here.remove_field( node.position, target_field_type_id );
                 did_field_removal = true;
             }
         }
         if( did_field_removal ) {
             // only remove one field in case of multiple
             break;
         }
     }
     return std::pair<field, tripoint> {field_removed, field_position};
 }
References spell::aoe(), area_expander::area, center, map::field_at(), area_expander::node::from, get_map(), area_expander::max_range, area_expander::node::position, map::remove_field(), area_expander::run(), and area_expander::sort_ascending().
Referenced by spell_effect::remove_field().
swap_pos()
static void swap_pos (Creature & caster, const tripoint & target) static
Definition at line 172 of file magic_spell_effect.cpp.
 {
     Creature *const critter = get_creature_tracker().creature_at<Creature>( target );
     critter->setpos( caster.pos() );
     caster.setpos( target );
     //update map in case a monster swapped positions with the player
     Character &you = get_player_character();
     get_map().vertical_shift( you.posz() );
     g->update_map( you );
 }
References creature_tracker::creature_at(), g, get_creature_tracker(), get_map(), get_player_character(), Creature::pos(), Creature::posz(), Creature::setpos(), and map::vertical_shift().
Referenced by spell_effect::attack(), monexamine::mfriend_menu(), game::npc_menu(), and monexamine::pet_menu().
test_always_true()
static bool test_always_true (const tripoint &) static
Definition at line 286 of file magic_spell_effect.cpp.
 {
     return true;
 }
Referenced by spell_effect::spell_effect_line().
test_passable()
static bool test_passable (const tripoint & p) static
Definition at line 290 of file magic_spell_effect.cpp.
 {
     return get_map().passable( p );
 }
References get_map(), and map::passable().
Referenced by spell_effect::spell_effect_line().
Variable Documentation
effect_teleglow
const efftype_id effect_teleglow("teleglow") ("teleglow") static
Referenced by handle_remove_fd_reality_tear_field().
json_flag_FIT
const flag_id json_flag_FIT("FIT") ("FIT") static
Referenced by spell_effect::spawn_ethereal_item().
json_flag_PRED1
const json_character_flag json_flag_PRED1("PRED1") ("PRED1") static
Referenced by spell_effect::guilt().
json_flag_PRED2
const json_character_flag json_flag_PRED2("PRED2") ("PRED2") static
Referenced by spell_effect::guilt().
json_flag_PRED3
const json_character_flag json_flag_PRED3("PRED3") ("PRED3") static
Referenced by spell_effect::guilt().
json_flag_PRED4
const json_character_flag json_flag_PRED4("PRED4") ("PRED4") static
Referenced by spell_effect::guilt().
mon_blob
const mtype_id mon_blob("mon_blob") ("mon_blob") static
Referenced by spell_effect::slime_split_on_death().
mon_blob_brain
const mtype_id mon_blob_brain("mon_blob_brain") ("mon_blob_brain") static
Referenced by spell_effect::slime_split_on_death().
mon_blob_large
const mtype_id mon_blob_large("mon_blob_large") ("mon_blob_large") static
Referenced by spell_effect::slime_split_on_death().
mon_blob_small
const mtype_id mon_blob_small("mon_blob_small") ("mon_blob_small") static
Referenced by spell_effect::slime_split_on_death().
mon_generator
const mtype_id mon_generator("mon_generator") ("mon_generator") static
Referenced by magical_polymorph().
species_HALLUCINATION
const species_id species_HALLUCINATION("HALLUCINATION") ("HALLUCINATION") static
Referenced by magical_polymorph().
species_SLIME
const species_id species_SLIME("SLIME") ("SLIME") static
Referenced by spell_effect::slime_split_on_death().
trait_KILLER
const trait_id trait_KILLER("KILLER") ("KILLER") static
Referenced by spell_effect::guilt().
trait_PACIFIST
const trait_id trait_PACIFIST("PACIFIST") ("PACIFIST") static
Referenced by spell_effect::guilt().
trait_PSYCHOPATH
const trait_id trait_PSYCHOPATH("PSYCHOPATH") ("PSYCHOPATH") static
Referenced by spell_effect::guilt().
trait_PYROMANIA
const trait_id trait_PYROMANIA("PYROMANIA") ("PYROMANIA") static
Referenced by damage_targets().