Cataclysm DDA: src/main.cpp File Reference
main.cpp File Reference
#include <algorithm>
#include <array>
#include <clocale>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <exception>
#include <functional>
#include <iostream>
#include <map>
#include <memory>
#include <string>
#include <utility>
#include <vector>
#include <csignal>
#include <flatbuffers/util.h>
#include "cached_options.h"
#include "cata_path.h"
#include "color.h"
#include "compatibility.h"
#include "crash.h"
#include "cursesdef.h"
#include "debug.h"
#include "do_turn.h"
#include "event.h"
#include "event_bus.h"
#include "filesystem.h"
#include "game.h"
#include "game_constants.h"
#include "game_ui.h"
#include "get_version.h"
#include "help.h"
#include "input.h"
#include "loading_ui.h"
#include "main_menu.h"
#include "mapsharing.h"
#include "memory_fast.h"
#include "options.h"
#include "ordered_static_globals.h"
#include "output.h"
#include "path_info.h"
#include "rng.h"
#include "system_locale.h"
#include "translations.h"
#include "type_id.h"
#include "ui_manager.h"
#include "cata_imgui.h"
Classes
struct anonymous_namespace{main.cpp}::arg_handler
struct anonymous_namespace{main.cpp}::cli_opts
Namespaces
anonymous_namespace{main.cpp}
Functions
void anonymous_namespace{main.cpp}::exit_handler (int s)
template<typename FirstPassArgs , typename SecondPassArgs >
void anonymous_namespace{main.cpp}::printHelpMessage (const FirstPassArgs &first_pass_arguments, const SecondPassArgs &second_pass_arguments)
void anonymous_namespace{main.cpp}::printVersionMessage ()
Displays current application version and compile options values.
void anonymous_namespace{main.cpp}::process_args (const char **argv, int argc, const std::vector< arg_handler > &arg_handlers)
cli_opts anonymous_namespace{main.cpp}::parse_commandline (int argc, const char **argv)
bool anonymous_namespace{main.cpp}::assure_essential_dirs_exist ()
int main (int argc, const char *argv[])
Function Documentation
main()
int main (int argc, const char * argv[])
OS X does not populate locale env vars correctly (they usually default to "C") so don't bother trying to set the locale based on them.
Definition at line 636 of file main.cpp.
 {
 #endif
     ordered_static_globals();
     init_crash_handlers();
     reset_floating_point_mode();
 #if defined(FLATBUFFERS_LOCALE_INDEPENDENT) && (FLATBUFFERS_LOCALE_INDEPENDENT > 0)
     flatbuffers::ClassicLocale::Get();
 #endif
 #if defined(EMSCRIPTEN)
     mount_idbfs();
 #endif
     on_out_of_scope json_member_reporting_guard{ [] {
             // Disable reporting unvisited members if stack unwinding leaves main early.
             Json::globally_report_unvisited_members( false );
         } };
 #if defined(_WIN32) and defined(TILES)
     const HANDLE std_output { GetStdHandle( STD_OUTPUT_HANDLE ) }, std_error { GetStdHandle( STD_ERROR_HANDLE ) };
     if( std_output != INVALID_HANDLE_VALUE and std_error != INVALID_HANDLE_VALUE ) {
         if( AttachConsole( ATTACH_PARENT_PROCESS ) ) {
             if( std_output == nullptr ) {
                 freopen_s( &CONOUT, "CONOUT$", "w", stdout );
             }
             if( std_error == nullptr ) {
                 freopen_s( &CONOUT, "CONOUT$", "w", stderr );
             }
         }
     }
 #endif
 #if defined(__ANDROID__)
     // Start the standard output logging redirector
     start_logger( "cdda" );
     // On Android first launch, we copy all data files from the APK into the app's writeable folder so std::io stuff works.
     // Use the external storage so it's publicly modifiable data (so users can mess with installed data, save games etc.)
     std::string external_storage_path( SDL_AndroidGetExternalStoragePath() );
     PATH_INFO::init_base_path( external_storage_path );
 #else
     // Set default file paths
 #if defined(PREFIX)
     PATH_INFO::init_base_path( std::string( PREFIX ) );
 #else
     PATH_INFO::init_base_path( "" );
 #endif
 #endif
 #if defined(__ANDROID__)
     PATH_INFO::init_user_dir( external_storage_path );
 #else
 #   if defined(USE_HOME_DIR) || defined(USE_XDG_DIR) || defined(EMSCRIPTEN)
     PATH_INFO::init_user_dir( "" );
 #   else
     PATH_INFO::init_user_dir( "." );
 #   endif
 #endif
     PATH_INFO::set_standard_filenames();
     MAP_SHARING::setDefaults();
     cli_opts cli = parse_commandline( argc, const_cast<const char **>( argv ) );
     if( !dir_exist( PATH_INFO::datadir() ) ) {
         printf( "Fatal: Can't find data directory \"%s\"\nPlease ensure the current working directory is correct or specify data directory with --datadir.  Perhaps you meant to start \"cataclysm-launcher\"?\n",
                 PATH_INFO::datadir().c_str() );
         exit( 1 );
     }
     if( !assure_dir_exist( PATH_INFO::user_dir() ) ) {
         printf( "Can't open or create %s. Check permissions.\n",
                 PATH_INFO::user_dir().c_str() );
         exit( 1 );
     }
 #if defined(EMSCRIPTEN)
     setupDebug( DebugOutput::std_err );
 #else
     setupDebug( DebugOutput::file );
 #endif
     // NOLINTNEXTLINE(cata-tests-must-restore-global-state)
     json_error_output_colors = json_error_output_colors_t::color_tags;
     /**
      * OS X does not populate locale env vars correctly (they usually default to
      * "C") so don't bother trying to set the locale based on them.
      */
 #if !defined(MACOSX)
     if( setlocale( LC_ALL, "" ) == nullptr ) {
         DebugLog( D_WARNING, D_MAIN ) << "Error while setlocale(LC_ALL, '').";
     } else {
 #endif
         try {
             std::locale::global( std::locale( "" ) );
         } catch( const std::exception & ) {
             // if user default locale retrieval isn't implemented by system
             try {
                 // default to basic C locale
                 std::locale::global( std::locale::classic() );
             } catch( const std::exception &err ) {
                 debugmsg( "%s", err.what() );
                 exit_handler( -999 );
             }
         }
 #if !defined(MACOSX)
     }
 #endif
     DebugLog( D_INFO, DC_ALL ) << "[main] C locale set to " << setlocale( LC_ALL, nullptr );
     DebugLog( D_INFO, DC_ALL ) << "[main] C++ locale set to " << std::locale().name();
 #if defined(TILES)
     SDL_version compiled;
     SDL_VERSION( &compiled );
     DebugLog( D_INFO, DC_ALL ) << "SDL version used during compile is "
                                << static_cast<int>( compiled.major ) << "."
                                << static_cast<int>( compiled.minor ) << "."
                                << static_cast<int>( compiled.patch );
     SDL_version linked;
     SDL_GetVersion( &linked );
     DebugLog( D_INFO, DC_ALL ) << "SDL version used during linking and in runtime is "
                                << static_cast<int>( linked.major ) << "."
                                << static_cast<int>( linked.minor ) << "."
                                << static_cast<int>( linked.patch );
 #endif
 #if !defined(TILES)
     get_options().init();
     get_options().load();
 #endif
     // in test mode don't initialize curses to avoid escape sequences being inserted into output stream
     if( !test_mode ) {
         try {
             // set minimum FULL_SCREEN sizes
             FULL_SCREEN_WIDTH = EVEN_MINIMUM_TERM_WIDTH;
             FULL_SCREEN_HEIGHT = EVEN_MINIMUM_TERM_HEIGHT;
             catacurses::init_interface();
         } catch( const std::exception &err ) {
             // can't use any curses function as it has not been initialized
             std::cerr << "Error while initializing the interface: " << err.what() << std::endl;
             DebugLog( D_ERROR, DC_ALL ) << "Error while initializing the interface: " << err.what() << "\n";
             return 1;
         }
     } else if( cli.check_mods ) {
         get_options().init();
         get_options().load();
     }
     set_language_from_options();
     rng_set_engine_seed( cli.seed );
     game_ui::init_ui();
     g = std::make_unique<game>();
     // First load and initialize everything that does not
     // depend on the mods.
     try {
         g->load_static_data();
         if( cli.verifyexit ) {
             exit_handler( 0 );
         }
         if( cli.check_mods ) {
             init_colors();
             loading_ui ui( false );
             const std::vector<mod_id> mods( cli.opts.begin(), cli.opts.end() );
             exit( g->check_mod_data( mods, ui ) && !debug_has_error_been_observed() ? 0 : 1 );
         }
     } catch( const std::exception &err ) {
         debugmsg( "%s", err.what() );
         exit_handler( -999 );
     }
     // Override existing settings from cli  options
     if( cli.disable_ascii_art ) {
         get_options().get_option( "ENABLE_ASCII_ART" ).setValue( "false" );
         get_options().get_option( "ENABLE_ASCII_TITLE" ).setValue( "false" );
     }
     if( cli.noverify ) {
         get_options().get_option( "SKIP_VERIFICATION" ).setValue( "true" );
     }
     // Now we do the actual game.
 #if defined(DEBUG_CURSES_CURSOR)
     catacurses::curs_set( 2 );
 #else
     // I have no clue what this comment is on about
     // Any value works well enough for debugging at least
     catacurses::curs_set( 0 ); // Invisible cursor here, because MAPBUFFER.load() is crash-prone
 #endif
 #if !defined(_WIN32)
     struct sigaction sigIntHandler;
     sigIntHandler.sa_handler = exit_handler;
     sigemptyset( &sigIntHandler.sa_mask );
     sigIntHandler.sa_flags = 0;
     sigaction( SIGINT, &sigIntHandler, nullptr );
 #endif
     if( !assure_essential_dirs_exist() ) {
         exit_handler( -999 );
         return 0;
     }
 #if defined(LOCALIZE)
     if( get_option<std::string>( "USE_LANG" ).empty() && !SystemLocale::Language().has_value() ) {
         const std::string lang = select_language();
         get_options().get_option( "USE_LANG" ).setValue( lang );
         set_language_from_options();
     }
 #endif
     replay_buffered_debugmsg_prompts();
     main_menu::queued_world_to_load = std::move( cli.world );
     get_help().load();
     while( true ) {
         main_menu menu;
         if( !menu.opening_screen() ) {
             break;
         }
         shared_ptr_fast<ui_adaptor> ui = g->create_or_get_main_ui_adaptor();
         get_event_bus().send<event_type::game_begin>( getVersionString() );
         while( !do_turn() ) {}
     }
     exit_handler( -999 );
     return 0;
 }
References assure_dir_exist(), anonymous_namespace{main.cpp}::assure_essential_dirs_exist(), color_tags, catacurses::curs_set(), D_ERROR, D_INFO, D_MAIN, D_WARNING, PATH_INFO::datadir(), DC_ALL, debug_has_error_been_observed(), DebugLog(), debugmsg, dir_exist(), do_turn(), EVEN_MINIMUM_TERM_HEIGHT, EVEN_MINIMUM_TERM_WIDTH, anonymous_namespace{main.cpp}::exit_handler(), file, FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, g, game_begin, get_event_bus(), get_help(), options_manager::get_option(), get_options(), getVersionString(), Json::globally_report_unvisited_members(), options_manager::init(), PATH_INFO::init_base_path(), init_colors(), init_crash_handlers(), catacurses::init_interface(), game_ui::init_ui(), PATH_INFO::init_user_dir(), json_error_output_colors, SystemLocale::Language(), help::load(), options_manager::load(), anonymous_namespace{item_tname.cpp}::mods(), main_menu::opening_screen(), ordered_static_globals(), anonymous_namespace{main.cpp}::parse_commandline(), main_menu::queued_world_to_load, replay_buffered_debugmsg_prompts(), reset_floating_point_mode(), rng_set_engine_seed(), event_bus::send(), set_language_from_options(), PATH_INFO::set_standard_filenames(), MAP_SHARING::setDefaults(), setupDebug(), options_manager::cOpt::setValue(), std_err, test_mode, and PATH_INFO::user_dir().
Referenced by Creature::get_random_body_part(), and main_menu::print_menu_items().