Cataclysm DDA: src/main_menu.cpp File Reference
main_menu.cpp File Reference
#include "main_menu.h"
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <ctime>
#include <exception>
#include <functional>
#include <istream>
#include <memory>
#include <optional>
#include <string>
#include "auto_pickup.h"
#include "avatar.h"
#include "cata_scope_helpers.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character_id.h"
#include "color.h"
#include "debug.h"
#include "enums.h"
#include "filesystem.h"
#include "game.h"
#include "gamemode.h"
#include "get_version.h"
#include "help.h"
#include "loading_ui.h"
#include "localized_comparator.h"
#include "mapbuffer.h"
#include "mapsharing.h"
#include "messages.h"
#include "music.h"
#include "options.h"
#include "output.h"
#include "overmapbuffer.h"
#include "path_info.h"
#include "popup.h"
#include "safemode_ui.h"
#include "scenario.h"
#include "sdlsound.h"
#include "sounds.h"
#include "string_formatter.h"
#include "text_snippets.h"
#include "translations.h"
#include "ui_manager.h"
#include "wcwidth.h"
#include "worldfactory.h"
#include "cata_imgui.h"
#include "imgui/imgui.h"
Classes
class demo_ui
Enumerations
enum class main_menu_opts : int {
MOTD = 0 , NEWCHAR , LOADCHAR , WORLD ,
TUTORIAL , SETTINGS , HELP , CREDITS ,
QUIT , NUM_MENU_OPTS
}
Functions
static int getopt (main_menu_opts o)
static int utf8_width_notags (const char *s)
static std::optional< std::chrono::seconds > get_playtime_from_save (const WORLD *world, const save_t &save)
Variables
static const mod_id MOD_INFORMATION_dda ("dda")
Enumeration Type Documentation
main_menu_opts
enum main_menu_opts : int strong
Enumerator
MOTD
NEWCHAR
LOADCHAR
WORLD
TUTORIAL
SETTINGS
HELP
CREDITS
QUIT
NUM_MENU_OPTS
Definition at line 119 of file main_menu.cpp.
                           : int {
     MOTD = 0,
     NEWCHAR,
     LOADCHAR,
     WORLD,
     TUTORIAL,
     SETTINGS,
     HELP,
     CREDITS,
     QUIT,
     NUM_MENU_OPTS,
 };
Function Documentation
get_playtime_from_save()
static std::optional<std::chrono::seconds> get_playtime_from_save (const WORLD * world, const save_t & save) static
Definition at line 1115 of file main_menu.cpp.
 {
     cata_path playtime_file = world->folder_path_path() / ( save.base_path() + ".pt" );
     std::optional<std::chrono::seconds> pt_seconds;
     if( file_exist( playtime_file ) ) {
         read_from_file( playtime_file, [&pt_seconds]( std::istream & fin ) {
             if( fin.eof() ) {
                 return;
             }
             std::chrono::seconds::rep dur_seconds = 0;
             fin.imbue( std::locale::classic() );
             fin >> dur_seconds;
             pt_seconds = std::chrono::seconds( dur_seconds );
         } );
     }
     return pt_seconds;
 }
References save_t::base_path(), file_exist(), WORLD::folder_path_path(), and read_from_file().
Referenced by main_menu::load_character_tab().
getopt()
static int getopt (main_menu_opts o) static
Definition at line 135 of file main_menu.cpp.
 {
     return static_cast<int>( o );
 }
Referenced by main_menu::display_sub_menu(), main_menu::opening_screen(), and main_menu::print_menu().
utf8_width_notags()
static int utf8_width_notags (const char * s) static
Definition at line 151 of file main_menu.cpp.
 {
     int len = strlen( s );
     const char *ptr = s;
     int w = 0;
     bool inside_tag = false;
     while( len > 0 ) {
         uint32_t ch = UTF8_getch( &ptr, &len );
         if( ch == UNKNOWN_UNICODE ) {
             continue;
         }
         if( ch == '<' ) {
             inside_tag = true;
         } else if( ch == '>' ) {
             inside_tag = false;
             continue;
         }
         if( inside_tag ) {
             continue;
         }
         w += mk_wcwidth( ch );
     }
     return w;
 }
References mk_wcwidth(), UNKNOWN_UNICODE, and UTF8_getch().
Referenced by main_menu::print_menu(), and main_menu::print_menu_items().
Variable Documentation
MOD_INFORMATION_dda
const mod_id MOD_INFORMATION_dda("dda") ("dda") static
Referenced by main_menu::opening_screen().