Cataclysm DDA: src/map.cpp File Reference
map.cpp File Reference
#include "map.h"
#include <algorithm>
#include <array>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <optional>
#include <ostream>
#include <queue>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include "active_item_cache.h"
#include "ammo.h"
#include "ammo_effect.h"
#include "avatar.h"
#include "basecamp.h"
#include "bodypart.h"
#include "cached_options.h"
#include "calendar.h"
#include "cata_assert.h"
#include "cata_type_traits.h"
#include "character.h"
#include "character_id.h"
#include "clzones.h"
#include "colony.h"
#include "color.h"
#include "construction.h"
#include "coordinate_conversions.h"
#include "creature.h"
#include "creature_tracker.h"
#include "cuboid_rectangle.h"
#include "cursesdef.h"
#include "damage.h"
#include "debug.h"
#include "do_turn.h"
#include "drawing_primitives.h"
#include "enums.h"
#include "explosion.h"
#include "field.h"
#include "field_type.h"
#include "flag.h"
#include "fragment_cloud.h"
#include "fungal_effects.h"
#include "game.h"
#include "harvest.h"
#include "iexamine.h"
#include "input.h"
#include "item.h"
#include "item_category.h"
#include "item_factory.h"
#include "item_group.h"
#include "item_location.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "lightmap.h"
#include "line.h"
#include "magic_ter_furn_transform.h"
#include "map_iterator.h"
#include "map_memory.h"
#include "map_selector.h"
#include "mapbuffer.h"
#include "mapdata.h"
#include "mapgen.h"
#include "material.h"
#include "math_defines.h"
#include "mission.h"
#include "memory_fast.h"
#include "messages.h"
#include "mongroup.h"
#include "monster.h"
#include "mtype.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pathfinding.h"
#include "pocket_type.h"
#include "projectile.h"
#include "ranged.h"
#include "relic.h"
#include "ret_val.h"
#include "rng.h"
#include "safe_reference.h"
#include "scent_map.h"
#include "shadowcasting.h"
#include "sounds.h"
#include "string_formatter.h"
#include "submap.h"
#include "tileray.h"
#include "translations.h"
#include "trap.h"
#include "ui_manager.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vehicle_selector.h"
#include "viewer.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "weather.h"
#include "weighted_list.h"
Namespaces
anonymous_namespace{map.cpp}
Macros
#define dbg(x) DebugLog((x),D_MAP) << __FILE__ << ":" << __LINE__ << ": "
Functions
void anonymous_namespace{map.cpp}::_add_vehicle_to_list (level_cache &ch, vehicle *veh)
static bool sees_veh (const Creature &c, vehicle &veh, bool force_recalc)
static bool furn_is_supported (const map &m, const tripoint &p)
static bool process_map_items (map &here, item_stack &items, safe_reference< item > &item_ref, item *parent, const tripoint &location, const float insulation, const temperature_flag flag, const float spoil_multiplier)
static void process_vehicle_items (vehicle &cur_veh, int part)
template<typename Stack >
std::list< item > use_amount_stack (Stack stack, const itype_id &type, int &quantity, const std::function< bool(const item &)> &filter)
static void use_charges_from_furn (const furn_t &f, const itype_id &type, int &quantity, map *m, const tripoint &p, std::list< item > &ret, const std::function< bool(const item &)> &filter, bool in_tools)
static std::optional< char32_t > get_memory_at (const tripoint &p)
template<int SIZE, int MULTIPLIER>
void shift_bitset_cache (std::bitset< SIZE *SIZE > &cache, const point &s)
template void shift_bitset_cache< MAPSIZE_X, SEEX > (std::bitset< MAPSIZE_X *MAPSIZE_X > &cache, const point &s)
template void shift_bitset_cache< MAPSIZE, 1 > (std::bitset< MAPSIZE *MAPSIZE > &cache, const point &s)
bool generate_uniform (const tripoint_abs_sm &p, const oter_id &oter)
bool generate_uniform_omt (const tripoint_abs_sm &p, const oter_id &terrain_type)
static void vehicle_caching_internal (level_cache &zch, const vpart_reference &vp, vehicle *v)
static void vehicle_caching_internal_above (level_cache &zch_above, const vpart_reference &vp, vehicle *v)
template<typename Array >
static cata::copy_const< Array, submap > * getsubmap_helper (const Array &grid, const size_t grididx)
static bool is_haulable (const item &it)
Variables
static const ammotype ammo_battery ("battery")
static const damage_type_id damage_bash ("bash")
static const diseasetype_id disease_bad_food ("bad_food")
static const efftype_id effect_boomered ("boomered")
static const efftype_id effect_crushed ("crushed")
static const efftype_id effect_fake_common_cold ("fake_common_cold")
static const efftype_id effect_fake_flu ("fake_flu")
static const efftype_id effect_gliding ("gliding")
static const efftype_id effect_incorporeal ("incorporeal")
static const efftype_id effect_pet ("pet")
static const field_type_str_id field_fd_clairvoyant ("fd_clairvoyant")
static const flag_id json_flag_AVATAR_ONLY ("AVATAR_ONLY")
static const flag_id json_flag_LEVITATION ("LEVITATION")
static const flag_id json_flag_PRESERVE_SPAWN_OMT ("PRESERVE_SPAWN_OMT")
static const flag_id json_flag_PROXIMITY ("PROXIMITY")
static const flag_id json_flag_UNDODGEABLE ("UNDODGEABLE")
static const furn_str_id furn_f_clear ("f_clear")
static const furn_str_id furn_f_rubble ("f_rubble")
static const furn_str_id furn_f_rubble_rock ("f_rubble_rock")
static const furn_str_id furn_f_wreckage ("f_wreckage")
static const item_group_id Item_spawn_data_default_zombie_clothes ("default_zombie_clothes")
static const item_group_id Item_spawn_data_default_zombie_items ("default_zombie_items")
static const itype_id itype_battery ("battery")
static const itype_id itype_nail ("nail")
static const material_id material_glass ("glass")
static const mtype_id mon_zombie ("mon_zombie")
static const oter_str_id oter_deep_rock ("deep_rock")
static const oter_str_id oter_empty_rock ("empty_rock")
static const oter_str_id oter_open_air ("open_air")
static const oter_str_id oter_solid_earth ("solid_earth")
static const species_id species_FERAL ("FERAL")
static const ter_str_id ter_t_bars ("t_bars")
static const ter_str_id ter_t_card_industrial ("t_card_industrial")
static const ter_str_id ter_t_card_military ("t_card_military")
static const ter_str_id ter_t_card_reader_broken ("t_card_reader_broken")
static const ter_str_id ter_t_card_science ("t_card_science")
static const ter_str_id ter_t_dirt ("t_dirt")
static const ter_str_id ter_t_dirtmound ("t_dirtmound")
static const ter_str_id ter_t_door_b ("t_door_b")
static const ter_str_id ter_t_door_bar_c ("t_door_bar_c")
static const ter_str_id ter_t_door_bar_locked ("t_door_bar_locked")
static const ter_str_id ter_t_door_bar_o ("t_door_bar_o")
static const ter_str_id ter_t_door_c ("t_door_c")
static const ter_str_id ter_t_door_frame ("t_door_frame")
static const ter_str_id ter_t_door_locked ("t_door_locked")
static const ter_str_id ter_t_door_locked_alarm ("t_door_locked_alarm")
static const ter_str_id ter_t_door_locked_peep ("t_door_locked_peep")
static const ter_str_id ter_t_floor ("t_floor")
static const ter_str_id ter_t_floor_wax ("t_floor_wax")
static const ter_str_id ter_t_gas_pump ("t_gas_pump")
static const ter_str_id ter_t_gas_pump_smashed ("t_gas_pump_smashed")
static const ter_str_id ter_t_grass ("t_grass")
static const ter_str_id ter_t_open_air ("t_open_air")
static const ter_str_id ter_t_reb_cage ("t_reb_cage")
static const ter_str_id ter_t_rock ("t_rock")
static const ter_str_id ter_t_rock_floor ("t_rock_floor")
static const ter_str_id ter_t_rootcellar ("t_rootcellar")
static const ter_str_id ter_t_sewage ("t_sewage")
static const ter_str_id ter_t_soil ("t_soil")
static const ter_str_id ter_t_stump ("t_stump")
static const ter_str_id ter_t_tree_birch ("t_tree_birch")
static const ter_str_id ter_t_tree_birch_harvested ("t_tree_birch_harvested")
static const ter_str_id ter_t_tree_dead ("t_tree_dead")
static const ter_str_id ter_t_tree_deadpine ("t_tree_deadpine")
static const ter_str_id ter_t_tree_hickory ("t_tree_hickory")
static const ter_str_id ter_t_tree_hickory_dead ("t_tree_hickory_dead")
static const ter_str_id ter_t_tree_hickory_harvested ("t_tree_hickory_harvested")
static const ter_str_id ter_t_tree_maple_tapped ("t_tree_maple_tapped")
static const ter_str_id ter_t_tree_pine ("t_tree_pine")
static const ter_str_id ter_t_tree_willow ("t_tree_willow")
static const ter_str_id ter_t_tree_willow_harvested ("t_tree_willow_harvested")
static const ter_str_id ter_t_tree_young ("t_tree_young")
static const ter_str_id ter_t_trunk ("t_trunk")
static const ter_str_id ter_t_vat ("t_vat")
static const ter_str_id ter_t_wall_glass ("t_wall_glass")
static const ter_str_id ter_t_wall_glass_alarm ("t_wall_glass_alarm")
static const ter_str_id ter_t_water_sh ("t_water_sh")
static const ter_str_id ter_t_wax ("t_wax")
static const ter_str_id ter_t_window ("t_window")
static const ter_str_id ter_t_window_alarm ("t_window_alarm")
static const ter_str_id ter_t_window_empty ("t_window_empty")
static const ter_str_id ter_t_window_no_curtains ("t_window_no_curtains")
static const trait_id trait_SCHIZOPHRENIC ("SCHIZOPHRENIC")
static const trap_str_id tr_unfinished_construction ("tr_unfinished_construction")
static cata::colony< item > nulitems
static field nulfield
static level_cache nullcache
static submap null_submap
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x),D_MAP) << __FILE__ << ":" << __LINE__ << ": "
Definition at line 212 of file map.cpp.
Function Documentation
furn_is_supported()
static bool furn_is_supported (const map & m, const tripoint & p) static
Definition at line 4008 of file map.cpp.
 {
     static constexpr std::array<int8_t, 4> cx = { 0, -1, 0, 1};
     static constexpr std::array<int8_t, 4> cy = { -1,  0, 1, 0};
     for( int i = 0; i < 4; i++ ) {
         const point adj( p.xy() + point( cx[i], cy[i] ) );
         if( m.has_furn( tripoint( adj, p.z ) ) &&
             m.furn( tripoint( adj, p.z ) ).obj().has_flag( ter_furn_flag::TFLAG_BLOCKSDOOR ) ) {
             return true;
         }
     }
     return false;
 }
References map::furn(), map_data_common_t::has_flag(), map::has_furn(), int_id< T >::obj(), TFLAG_BLOCKSDOOR, tripoint::xy(), and tripoint::z.
Referenced by map::bash_ter_furn().
generate_uniform()
bool generate_uniform (const tripoint_abs_sm & p, const oter_id & oter)
Definition at line 8176 of file map.cpp.
 {
     std::unique_ptr<submap> sm = std::make_unique<submap>();
     if( oter == oter_open_air ) {
         sm->set_all_ter( ter_t_open_air, true );
     } else if( oter == oter_empty_rock || oter == oter_deep_rock ) {
         sm->set_all_ter( ter_t_rock, true );
     } else if( oter == oter_solid_earth ) {
         sm->set_all_ter( ter_t_soil, true );
     } else {
         return false;
     }
     sm->last_touched = calendar::turn;
     return MAPBUFFER.add_submap( p, sm );
 }
References mapbuffer::add_submap(), MAPBUFFER, oter_deep_rock, oter_empty_rock, oter_open_air, oter_solid_earth, coords::sm, ter_t_open_air, ter_t_rock, ter_t_soil, and calendar::turn.
Referenced by generate_uniform_omt().
generate_uniform_omt()
bool generate_uniform_omt (const tripoint_abs_sm & p, const oter_id & terrain_type)
Definition at line 8192 of file map.cpp.
 {
     dbg( D_INFO ) << "generate_uniform p: " << p
                   << "  terrain_type: " << terrain_type.id().str();
     bool ret = true;
     for( int xd = 0; xd <= 1; xd++ ) {
         for( int yd = 0; yd <= 1; yd++ ) {
             ret &= generate_uniform( p + point( xd, yd ), terrain_type );
         }
     }
     return ret;
 }
References D_INFO, dbg, generate_uniform(), int_id< T >::id(), cata::hash64_detail::ret, and string_id< T >::str().
Referenced by map::loadn(), and mapbuffer::unserialize_submaps().
get_memory_at()
static std::optional<char32_t> get_memory_at (const tripoint & p) static
Definition at line 6921 of file map.cpp.
 {
     const memorized_tile &mt = get_avatar().get_memorized_tile( get_map().getglobal( p ) );
     if( mt.symbol != 0 ) {
         return mt.symbol;
     }
     return std::nullopt;
 }
References get_avatar(), get_map(), avatar::get_memorized_tile(), and memorized_tile::symbol.
Referenced by map::draw().
getsubmap_helper()
template<typename Array > static cata::copy_const<Array, submap>* getsubmap_helper (const Array & grid, const size_t grididx) static
Definition at line 9669 of file map.cpp.
 {
     if( grididx >= grid.size() ) {
         debugmsg( "Tried to access invalid grid index %d. Grid size: %d", grididx, grid.size() );
         return nullptr;
     }
     return grid[grididx];
 }
References debugmsg.
Referenced by map::getsubmap().
is_haulable()
static bool is_haulable (const item & it) static
Definition at line 10519 of file map.cpp.
 {
     // Liquid cannot be picked up
     return !it.made_of_from_type( phase_id::LIQUID );
 }
References LIQUID, and item::made_of_from_type().
Referenced by map::get_haulable_items(), and map::has_haulable_items().
process_map_items()
static bool process_map_items (map & here, item_stack & items, safe_reference< item > & item_ref, item * parent, const tripoint & location, const float insulation, const temperature_flag flag, const float spoil_multiplier) static
Definition at line 5547 of file map.cpp.
 {
     if( item_ref->process( here, nullptr, location, insulation, flag, spoil_multiplier, false ) ) {
         // Item is to be destroyed so erase it from the map stack
         // unless it was already destroyed by processing.
         if( item_ref ) {
             item_ref->spill_contents( location );
             if( parent != nullptr ) {
                 parent->remove_item( *item_ref );
             } else {
                 items.erase( items.get_iterator_from_pointer( item_ref.get() ) );
             }
         }
         if( parent != nullptr ) {
             parent->on_contents_changed();
         }
         return true;
     }
     // Item not destroyed
     return false;
 }
References item_stack::erase(), safe_reference< T >::get(), item_stack::get_iterator_from_pointer(), location, item::on_contents_changed(), item::process(), visitable::remove_item(), and item::spill_contents().
Referenced by map::process_items_in_submap(), and map::process_items_in_vehicle().
process_vehicle_items()
static void process_vehicle_items (vehicle & cur_veh, int part) static
Definition at line 5571 of file map.cpp.
 {
     vehicle_part &vp = cur_veh.part( part );
     const vpart_info &vpi = vp.info();
     const bool washer_here = vp.enabled &&
                              ( vpi.has_flag( VPFLAG_WASHING_MACHINE ) ||
                                vpi.has_flag( VPFLAG_DISHWASHER ) );
     if( washer_here ) {
         bool washing_machine_finished = false;
         for( item &n : cur_veh.get_items( vp ) ) {
             const time_duration washing_time = 90_minutes;
             const time_duration time_left = washing_time - n.age();
             if( time_left <= 0_turns ) {
                 n.unset_flag( flag_FILTHY );
                 washing_machine_finished = true;
                 vp.enabled = false;
             } else if( calendar::once_every( 15_minutes ) ) {
                 //~ %1$d: Number of minutes remaining, %2$s: Name of the vehicle
                 add_msg( _( "It should take %1$d minutes to finish washing items in the %2$s." ),
                          to_minutes<int>( time_left ) + 1, cur_veh.name );
                 break;
             }
         }
         if( washing_machine_finished && !vpi.has_flag( VPFLAG_APPLIANCE ) ) {
             //~ %1$s: Cleaner, %2$s: Name of the vehicle
             add_msg( _( "The %1$s in the %2$s has finished washing." ), vp.name( false ), cur_veh.name );
         } else if( washing_machine_finished ) {
             add_msg( _( "The %1$s has finished washing." ), vp.name( false ) );
         }
     }
     const bool autoclave_here = vpi.has_flag( VPFLAG_AUTOCLAVE ) && vp.enabled;
     if( autoclave_here ) {
         bool autoclave_finished = false;
         for( item &n : cur_veh.get_items( vp ) ) {
             const time_duration cycle_time = 90_minutes;
             const time_duration time_left = cycle_time - n.age();
             if( time_left <= 0_turns ) {
                 if( !n.has_flag( flag_NO_PACKED ) ) {
                     n.unset_flag( flag_NO_STERILE );
                 }
                 autoclave_finished = true;
                 vp.enabled = false;
             } else if( calendar::once_every( 15_minutes ) ) {
                 const int minutes = to_minutes<int>( time_left ) + 1;
                 //~ %1$d: Number of minutes remaining, %2$s: Name of the vehicle
                 add_msg( n_gettext( "It should take %1$d minute to finish sterilizing items in the %2$s.",
                                     "It should take %1$d minutes to finish sterilizing items in the %2$s.", minutes ),
                          minutes, cur_veh.name );
                 break;
             }
         }
         if( autoclave_finished && !vpi.has_flag( VPFLAG_APPLIANCE ) ) {
             add_msg( _( "The autoclave in the %s has finished its cycle." ), cur_veh.name );
         } else if( autoclave_finished ) {
             add_msg( _( "The autoclave has finished its cycle." ) );
         }
     }
     const int recharge_part_idx = cur_veh.part_with_feature( part, VPFLAG_RECHARGE, true );
     if( recharge_part_idx >= 0 ) {
         const vehicle_part &recharge_part = cur_veh.part( recharge_part_idx );
         if( !recharge_part.removed && recharge_part.enabled ) {
             for( item &n : cur_veh.get_items( vp ) ) {
                 if( !n.has_flag( flag_RECHARGE ) && !n.has_flag( flag_USE_UPS ) ) {
                     continue;
                 }
                 // TODO: BATTERIES this should be rewritten when vehicle power and items both use energy quantities
                 if( n.ammo_capacity( ammo_battery ) > n.ammo_remaining() ||
                     ( n.type->battery && n.type->battery->max_capacity > n.energy_remaining( nullptr ) ) ) {
                     int power = recharge_part.info().bonus;
                     while( power >= 1000 || x_in_y( power, 1000 ) ) {
                         const int missing = cur_veh.discharge_battery( 1 );
                         // Around 85% efficient; a few of the discharges don't actually recharge
                         if( missing == 0 && !one_in( 7 ) ) {
                             if( n.is_vehicle_battery() ) {
                                 n.mod_energy( 1_kJ );
                             } else {
                                 n.ammo_set( itype_battery, n.ammo_remaining() + 1 );
                             }
                         }
                         power -= 1000;
                     }
                     break;
                 }
             }
         }
     }
 }
References _, add_msg(), ammo_battery, vpart_info::bonus, vehicle::discharge_battery(), vehicle_part::enabled, flag_FILTHY, flag_NO_PACKED, flag_NO_STERILE, flag_RECHARGE, flag_USE_UPS, vehicle::get_items(), vpart_info::has_flag(), vehicle_part::info(), itype_battery, n_gettext, vehicle_part::name(), vehicle::name, calendar::once_every(), one_in(), vehicle::part(), vehicle::part_with_feature(), vehicle_part::removed, VPFLAG_APPLIANCE, VPFLAG_AUTOCLAVE, VPFLAG_DISHWASHER, VPFLAG_RECHARGE, VPFLAG_WASHING_MACHINE, and x_in_y().
Referenced by map::process_items_in_vehicle().
sees_veh()
static bool sees_veh (const Creature & c, vehicle & veh, bool force_recalc) static
Definition at line 744 of file map.cpp.
 {
     const auto &veh_points = veh.get_points( force_recalc );
     return std::any_of( veh_points.begin(), veh_points.end(), [&c]( const tripoint & pt ) {
         return c.sees( pt );
     } );
 }
References c, and vehicle::get_points().
Referenced by map::move_vehicle().
shift_bitset_cache()
template<int SIZE, int MULTIPLIER> void shift_bitset_cache (std::bitset< SIZE *SIZE > & cache, const point & s)
Definition at line 7979 of file map.cpp.
 {
     // sx shifts by MULTIPLIER rows, sy shifts by MULTIPLIER columns.
     int shift_amount = s.x * MULTIPLIER + s.y * SIZE * MULTIPLIER;
     if( shift_amount > 0 ) {
         cache >>= static_cast<size_t>( shift_amount );
     } else if( shift_amount < 0 ) {
         cache <<= static_cast<size_t>( -shift_amount );
     }
     // Shifting in the y direction shifted in 0 values, no no additional clearing is necessary, but
     // a shift in the x direction makes values "wrap" to the next row, and they need to be zeroed.
     if( s.x == 0 ) {
         return;
     }
     const size_t x_offset = s.x > 0 ? SIZE - MULTIPLIER : 0;
     for( size_t y = 0; y < SIZE; ++y ) {
         size_t y_offset = y * SIZE;
         for( size_t x = 0; x < MULTIPLIER; ++x ) {
             cache.reset( y_offset + x_offset + x );
         }
     }
 }
References point::x, and point::y.
shift_bitset_cache< MAPSIZE, 1 >()
template void shift_bitset_cache< MAPSIZE, 1 > (std::bitset< MAPSIZE *MAPSIZE > & cache, const point & s)
Referenced by map::shift().
shift_bitset_cache< MAPSIZE_X, SEEX >()
template void shift_bitset_cache< MAPSIZE_X, SEEX > (std::bitset< MAPSIZE_X *MAPSIZE_X > & cache, const point & s)
Referenced by map::shift().
use_amount_stack()
template<typename Stack > std::list<item> use_amount_stack (Stack stack, const itype_id & type, int & quantity, const std::function< bool(const item &)> & filter)
Definition at line 5925 of file map.cpp.
 {
     std::list<item> ret;
     for( auto a = stack.begin(); a != stack.end() && quantity > 0; ) {
         if( a->use_amount( type, quantity, ret, filter ) ) {
             a = stack.erase( a );
         } else {
             ++a;
         }
     }
     return ret;
 }
References a, filter, cata::hash64_detail::ret, and type.
Referenced by map::use_amount_square().
use_charges_from_furn()
static void use_charges_from_furn (const furn_t & f, const itype_id & type, int & quantity, map * m, const tripoint & p, std::list< item > & ret, const std::function< bool(const item &)> & filter, bool in_tools) static
Definition at line 6022 of file map.cpp.
 {
     if( m->has_flag( ter_furn_flag::TFLAG_LIQUIDCONT, p ) ) {
         map_stack item_list = m->i_at( p );
         auto current_item = item_list.begin();
         for( ; current_item != item_list.end(); ++current_item ) {
             // looking for a liquid that matches
             if( filter( *current_item ) && current_item->made_of( phase_id::LIQUID ) &&
                 type == current_item->typeId() ) {
                 ret.push_back( *current_item );
                 if( current_item->charges - quantity > 0 ) {
                     // Update the returned liquid amount to match the requested amount
                     ret.back().charges = quantity;
                     // Update the liquid item in the world to contain the leftover liquid
                     current_item->charges -= quantity;
                     // All the liquid needed was found, no other sources will be needed
                     quantity = 0;
                 } else {
                     // The liquid copy in ret already contains how much was available
                     // The leftover quantity returned will check other sources
                     quantity -= current_item->charges;
                     // Remove liquid item from the world
                     item_list.erase( current_item );
                 }
                 return;
             }
         }
     }
     const itype *itt = f.crafting_pseudo_item_type();
     if( itt != nullptr && itt->tool && !itt->tool->ammo_id.empty() ) {
         const bool using_ammotype = f.has_flag( ter_furn_flag::TFLAG_AMMOTYPE_RELOAD );
         map_stack stack = m->i_at( p );
         for( const itype *ammo_itype : f.crafting_ammo_item_types() ) {
             itype_id ammo = ammo_itype->get_id();
             auto iter = std::find_if( stack.begin(), stack.end(),
             [ammo, using_ammotype]( const item & i ) {
                 if( using_ammotype && i.type->ammo && ammo->ammo ) {
                     return i.type->ammo->type == ammo->ammo->type;
                 } else {
                     return i.typeId() == ammo;
                 }
             } );
             if( iter != stack.end() ) {
                 item furn_item( itt, calendar::turn_zero );
                 furn_item.ammo_set( ammo, iter->charges );
                 if( !filter( furn_item ) ) {
                     return;
                 }
                 if( furn_item.use_charges( type, quantity, ret, p, return_true<item>, nullptr, in_tools ) ) {
                     stack.erase( iter );
                 } else {
                     iter->charges = furn_item.ammo_remaining();
                 }
             }
         }
     }
 }
References item::ammo_remaining(), item::ammo_set(), item_stack::begin(), furn_t::crafting_ammo_item_types(), furn_t::crafting_pseudo_item_type(), item_stack::end(), map_stack::erase(), filter, itype::get_id(), map_data_common_t::has_flag(), map::has_flag(), map::i_at(), LIQUID, cata::hash64_detail::ret, TFLAG_AMMOTYPE_RELOAD, TFLAG_LIQUIDCONT, itype::tool, calendar::turn_zero, type, and item::use_charges().
Referenced by map::use_charges().
vehicle_caching_internal()
static void vehicle_caching_internal (level_cache & zch, const vpart_reference & vp, vehicle * v) static
Definition at line 9484 of file map.cpp.
 {
     auto &outside_cache = zch.outside_cache;
     auto &transparency_cache = zch.transparency_cache;
     auto &floor_cache = zch.floor_cache;
     const size_t part = vp.part_index();
     const tripoint part_pos =  v->global_part_pos3( vp.part() );
     bool vehicle_is_opaque = vp.has_feature( VPFLAG_OPAQUE ) && !vp.part().is_broken();
     if( vehicle_is_opaque ) {
         int dpart = v->part_with_feature( part, VPFLAG_OPENABLE, true );
         if( dpart < 0 || !v->part( dpart ).open ) {
             transparency_cache[part_pos.x][part_pos.y] = LIGHT_TRANSPARENCY_SOLID;
         } else {
             vehicle_is_opaque = false;
         }
     }
     if( vehicle_is_opaque || vp.is_inside() ) {
         outside_cache[part_pos.x][part_pos.y] = false;
     }
     if( vp.has_feature( VPFLAG_BOARDABLE ) && !vp.part().is_broken() ) {
         floor_cache[part_pos.x][part_pos.y] = true;
     }
 }
References level_cache::floor_cache, vehicle::global_part_pos3(), vpart_reference::has_feature(), vehicle_part::is_broken(), vpart_position::is_inside(), LIGHT_TRANSPARENCY_SOLID, open(), level_cache::outside_cache, vpart_reference::part(), vpart_position::part_index(), vehicle::part_with_feature(), level_cache::transparency_cache, VPFLAG_BOARDABLE, VPFLAG_OPAQUE, VPFLAG_OPENABLE, tripoint::x, and tripoint::y.
Referenced by map::do_vehicle_caching().
vehicle_caching_internal_above()
static void vehicle_caching_internal_above (level_cache & zch_above, const vpart_reference & vp, vehicle * v) static
Definition at line 9513 of file map.cpp.
 {
     if( vp.has_feature( VPFLAG_ROOF ) || vp.has_feature( VPFLAG_OPAQUE ) ) {
         const tripoint part_pos = v->global_part_pos3( vp.part() );
         zch_above.floor_cache[part_pos.x][part_pos.y] = true;
     }
 }
References level_cache::floor_cache, vehicle::global_part_pos3(), vpart_reference::has_feature(), vpart_reference::part(), VPFLAG_OPAQUE, VPFLAG_ROOF, tripoint::x, and tripoint::y.
Referenced by map::do_vehicle_caching().
Variable Documentation
ammo_battery
const ammotype ammo_battery("battery") ("battery") static
Referenced by process_vehicle_items().
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by map::bash_vehicle(), map::crush(), map::drop_furniture(), map::drop_items(), map::move_vehicle(), and map::vehicle_vehicle_collision().
disease_bad_food
const diseasetype_id disease_bad_food("bad_food") ("bad_food") static
Referenced by map::ter_set(), and map::water_from().
effect_boomered
const efftype_id effect_boomered("boomered") ("boomered") static
Referenced by map::update_visibility_cache().
effect_crushed
const efftype_id effect_crushed("crushed") ("crushed") static
Referenced by map::crush(), and map::furn_set().
effect_fake_common_cold
const efftype_id effect_fake_common_cold("fake_common_cold") ("fake_common_cold") static
Referenced by map::spawn_monsters_submap().
effect_fake_flu
const efftype_id effect_fake_flu("fake_flu") ("fake_flu") static
Referenced by map::spawn_monsters_submap().
effect_gliding
const efftype_id effect_gliding("gliding") ("gliding") static
Referenced by map::creature_on_trap().
effect_incorporeal
const efftype_id effect_incorporeal("incorporeal") ("incorporeal") static
Referenced by map::open_door().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by map::spawn_monsters_submap().
field_fd_clairvoyant
const field_type_str_id field_fd_clairvoyant("fd_clairvoyant") ("fd_clairvoyant") static
Referenced by map::update_visibility_cache().
furn_f_clear
const furn_str_id furn_f_clear("f_clear") ("f_clear") static
Referenced by map::furn_set().
furn_f_rubble
const furn_str_id furn_f_rubble("f_rubble") ("f_rubble") static
Referenced by map::furn_set(), and map::make_rubble().
furn_f_rubble_rock
const furn_str_id furn_f_rubble_rock("f_rubble_rock") ("f_rubble_rock") static
Referenced by map::make_rubble().
furn_f_wreckage
const furn_str_id furn_f_wreckage("f_wreckage") ("f_wreckage") static
Referenced by map::make_rubble().
Item_spawn_data_default_zombie_clothes
const item_group_id Item_spawn_data_default_zombie_clothes("default_zombie_clothes") ("default_zombie_clothes") static
Referenced by map::add_corpse().
Item_spawn_data_default_zombie_items
const item_group_id Item_spawn_data_default_zombie_items("default_zombie_items") ("default_zombie_items") static
Referenced by map::add_corpse().
itype_battery
const itype_id itype_battery("battery") ("battery") static
Referenced by process_vehicle_items().
itype_nail
const itype_id itype_nail("nail") ("nail") static
Referenced by map::make_rubble().
json_flag_AVATAR_ONLY
const flag_id json_flag_AVATAR_ONLY("AVATAR_ONLY") ("AVATAR_ONLY") static
Referenced by map::maybe_trigger_prox_trap(), and map::maybe_trigger_trap().
json_flag_LEVITATION
const flag_id json_flag_LEVITATION("LEVITATION") ("LEVITATION") static
Referenced by map::maybe_trigger_prox_trap(), and map::maybe_trigger_trap().
json_flag_PRESERVE_SPAWN_OMT
const flag_id json_flag_PRESERVE_SPAWN_OMT("PRESERVE_SPAWN_OMT") ("PRESERVE_SPAWN_OMT") static
Referenced by map::add_item().
json_flag_PROXIMITY
const flag_id json_flag_PROXIMITY("PROXIMITY") ("PROXIMITY") static
Referenced by map::creature_on_trap().
json_flag_UNDODGEABLE
const flag_id json_flag_UNDODGEABLE("UNDODGEABLE") ("UNDODGEABLE") static
Referenced by map::maybe_trigger_prox_trap(), and map::maybe_trigger_trap().
material_glass
const material_id material_glass("glass") ("glass") static
Referenced by map::bash_items().
mon_zombie
const mtype_id mon_zombie("mon_zombie") ("mon_zombie") static
Referenced by map::add_corpse().
nulfield
field nulfield static
Definition at line 215 of file map.cpp.
Referenced by map::field_at().
nulitems
cata::colony<item> nulitems static
Definition at line 214 of file map.cpp.
Referenced by map::i_at(), and map::i_rem().
null_submap
submap null_submap static
Definition at line 271 of file map.cpp.
Referenced by map::maptile_at().
nullcache
level_cache nullcache static
Definition at line 216 of file map.cpp.
Referenced by map::access_cache().
oter_deep_rock
const oter_str_id oter_deep_rock("deep_rock") ("deep_rock") static
Referenced by generate_uniform().
oter_empty_rock
const oter_str_id oter_empty_rock("empty_rock") ("empty_rock") static
Referenced by generate_uniform().
oter_open_air
const oter_str_id oter_open_air("open_air") ("open_air") static
Referenced by generate_uniform().
oter_solid_earth
const oter_str_id oter_solid_earth("solid_earth") ("solid_earth") static
Referenced by generate_uniform().
species_FERAL
const species_id species_FERAL("FERAL") ("FERAL") static
Referenced by map::spawn_monsters_submap().
ter_t_bars
const ter_str_id ter_t_bars("t_bars") ("t_bars") static
Referenced by map::hit_with_acid().
ter_t_card_industrial
const ter_str_id ter_t_card_industrial("t_card_industrial") ("t_card_industrial") static
Referenced by map::hit_with_acid().
ter_t_card_military
const ter_str_id ter_t_card_military("t_card_military") ("t_card_military") static
Referenced by map::hit_with_acid().
ter_t_card_reader_broken
const ter_str_id ter_t_card_reader_broken("t_card_reader_broken") ("t_card_reader_broken") static
Referenced by map::hit_with_acid().
ter_t_card_science
const ter_str_id ter_t_card_science("t_card_science") ("t_card_science") static
Referenced by map::hit_with_acid().
ter_t_dirt
const ter_str_id ter_t_dirt("t_dirt") ("t_dirt") static
Referenced by map::bash_ter_furn(), map::displace_water(), map::furn_set(), map::get_roof(), map::move_vehicle(), and map::rad_scorch().
ter_t_dirtmound
const ter_str_id ter_t_dirtmound("t_dirtmound") ("t_dirtmound") static
Referenced by map::furn_set(), and map::move_vehicle().
ter_t_door_b
const ter_str_id ter_t_door_b("t_door_b") ("t_door_b") static
Referenced by map::hit_with_acid().
ter_t_door_bar_c
const ter_str_id ter_t_door_bar_c("t_door_bar_c") ("t_door_bar_c") static
Referenced by map::hit_with_acid().
ter_t_door_bar_locked
const ter_str_id ter_t_door_bar_locked("t_door_bar_locked") ("t_door_bar_locked") static
Referenced by map::hit_with_acid().
ter_t_door_bar_o
const ter_str_id ter_t_door_bar_o("t_door_bar_o") ("t_door_bar_o") static
Referenced by map::hit_with_acid().
ter_t_door_c
const ter_str_id ter_t_door_c("t_door_c") ("t_door_c") static
Referenced by map::hit_with_acid().
ter_t_door_frame
const ter_str_id ter_t_door_frame("t_door_frame") ("t_door_frame") static
Referenced by map::hit_with_acid().
ter_t_door_locked
const ter_str_id ter_t_door_locked("t_door_locked") ("t_door_locked") static
Referenced by map::hit_with_acid().
ter_t_door_locked_alarm
const ter_str_id ter_t_door_locked_alarm("t_door_locked_alarm") ("t_door_locked_alarm") static
Referenced by map::hit_with_acid().
ter_t_door_locked_peep
const ter_str_id ter_t_door_locked_peep("t_door_locked_peep") ("t_door_locked_peep") static
Referenced by map::hit_with_acid().
ter_t_floor
const ter_str_id ter_t_floor("t_floor") ("t_floor") static
Referenced by map::hit_with_acid().
ter_t_floor_wax
const ter_str_id ter_t_floor_wax("t_floor_wax") ("t_floor_wax") static
Referenced by map::hit_with_acid().
ter_t_gas_pump
const ter_str_id ter_t_gas_pump("t_gas_pump") ("t_gas_pump") static
Referenced by map::hit_with_acid().
ter_t_gas_pump_smashed
const ter_str_id ter_t_gas_pump_smashed("t_gas_pump_smashed") ("t_gas_pump_smashed") static
Referenced by map::hit_with_acid().
ter_t_grass
const ter_str_id ter_t_grass("t_grass") ("t_grass") static
Referenced by map::move_vehicle(), and map::rad_scorch().
ter_t_open_air
const ter_str_id ter_t_open_air("t_open_air") ("t_open_air") static
Referenced by map::add_roofs(), map::bash_ter_furn(), map::collapse_at(), generate_uniform(), and map::get_roof().
ter_t_reb_cage
const ter_str_id ter_t_reb_cage("t_reb_cage") ("t_reb_cage") static
Referenced by map::hit_with_acid().
ter_t_rock
const ter_str_id ter_t_rock("t_rock") ("t_rock") static
Referenced by generate_uniform().
ter_t_rock_floor
const ter_str_id ter_t_rock_floor("t_rock_floor") ("t_rock_floor") static
Referenced by map::add_roofs(), and map::get_roof().
ter_t_rootcellar
const ter_str_id ter_t_rootcellar("t_rootcellar") ("t_rootcellar") static
Referenced by map::process_items_in_submap().
ter_t_sewage
const ter_str_id ter_t_sewage("t_sewage") ("t_sewage") static
Referenced by map::water_from().
ter_t_soil
const ter_str_id ter_t_soil("t_soil") ("t_soil") static
Referenced by generate_uniform().
ter_t_stump
const ter_str_id ter_t_stump("t_stump") ("t_stump") static
Referenced by map::cut_down_tree().
ter_t_tree_birch
const ter_str_id ter_t_tree_birch("t_tree_birch") ("t_tree_birch") static
Referenced by map::rad_scorch().
ter_t_tree_birch_harvested
const ter_str_id ter_t_tree_birch_harvested("t_tree_birch_harvested") ("t_tree_birch_harvested") static
Referenced by map::rad_scorch().
ter_t_tree_dead
const ter_str_id ter_t_tree_dead("t_tree_dead") ("t_tree_dead") static
Referenced by map::rad_scorch().
ter_t_tree_deadpine
const ter_str_id ter_t_tree_deadpine("t_tree_deadpine") ("t_tree_deadpine") static
Referenced by map::rad_scorch().
ter_t_tree_hickory
const ter_str_id ter_t_tree_hickory("t_tree_hickory") ("t_tree_hickory") static
Referenced by map::rad_scorch().
ter_t_tree_hickory_dead
const ter_str_id ter_t_tree_hickory_dead("t_tree_hickory_dead") ("t_tree_hickory_dead") static
Referenced by map::rad_scorch().
ter_t_tree_hickory_harvested
const ter_str_id ter_t_tree_hickory_harvested("t_tree_hickory_harvested") ("t_tree_hickory_harvested") static
Referenced by map::rad_scorch().
ter_t_tree_maple_tapped
const ter_str_id ter_t_tree_maple_tapped("t_tree_maple_tapped") ("t_tree_maple_tapped") static
Referenced by map::produce_sap().
ter_t_tree_pine
const ter_str_id ter_t_tree_pine("t_tree_pine") ("t_tree_pine") static
Referenced by map::rad_scorch().
ter_t_tree_willow
const ter_str_id ter_t_tree_willow("t_tree_willow") ("t_tree_willow") static
Referenced by map::rad_scorch().
ter_t_tree_willow_harvested
const ter_str_id ter_t_tree_willow_harvested("t_tree_willow_harvested") ("t_tree_willow_harvested") static
Referenced by map::rad_scorch().
ter_t_tree_young
const ter_str_id ter_t_tree_young("t_tree_young") ("t_tree_young") static
Referenced by map::rad_scorch().
ter_t_trunk
const ter_str_id ter_t_trunk("t_trunk") ("t_trunk") static
Referenced by map::cut_down_tree().
ter_t_vat
const ter_str_id ter_t_vat("t_vat") ("t_vat") static
Referenced by map::hit_with_acid().
ter_t_wall_glass
const ter_str_id ter_t_wall_glass("t_wall_glass") ("t_wall_glass") static
Referenced by map::hit_with_acid().
ter_t_wall_glass_alarm
const ter_str_id ter_t_wall_glass_alarm("t_wall_glass_alarm") ("t_wall_glass_alarm") static
Referenced by map::hit_with_acid().
ter_t_water_sh
const ter_str_id ter_t_water_sh("t_water_sh") ("t_water_sh") static
Referenced by map::displace_water().
ter_t_wax
const ter_str_id ter_t_wax("t_wax") ("t_wax") static
Referenced by map::hit_with_acid().
ter_t_window
const ter_str_id ter_t_window("t_window") ("t_window") static
Referenced by map::hit_with_acid().
ter_t_window_alarm
const ter_str_id ter_t_window_alarm("t_window_alarm") ("t_window_alarm") static
Referenced by map::hit_with_acid().
ter_t_window_empty
const ter_str_id ter_t_window_empty("t_window_empty") ("t_window_empty") static
Referenced by map::hit_with_acid().
ter_t_window_no_curtains
const ter_str_id ter_t_window_no_curtains("t_window_no_curtains") ("t_window_no_curtains") static
Referenced by map::hit_with_acid().
tr_unfinished_construction
const trap_str_id tr_unfinished_construction("tr_unfinished_construction") ("tr_unfinished_construction") static
Referenced by map::draw_maptile().
trait_SCHIZOPHRENIC
const trait_id trait_SCHIZOPHRENIC("SCHIZOPHRENIC") ("SCHIZOPHRENIC") static
Referenced by map::open_door().