Cataclysm DDA: src/map_item_stack.h File Reference
map_item_stack.h File Reference
#include <iosfwd>
#include <vector>
#include "point.h"
Classes
class map_item_stack
class map_item_stack::item_group
Macros
#define CATA_SRC_MAP_ITEM_STACK_H
Functions
std::vector< map_item_stack > filter_item_stacks (const std::vector< map_item_stack > &stack, const std::string &filter)
int list_filter_high_priority (std::vector< map_item_stack > &stack, const std::string &priorities)
int list_filter_low_priority (std::vector< map_item_stack > &stack, int start, const std::string &priorities)
Macro Definition Documentation
CATA_SRC_MAP_ITEM_STACK_H
#define CATA_SRC_MAP_ITEM_STACK_H
Definition at line 3 of file map_item_stack.h.
Function Documentation
filter_item_stacks()
std::vector<map_item_stack> filter_item_stacks (const std::vector< map_item_stack > & stack, const std::string & filter)
Definition at line 59 of file map_item_stack.cpp.
 {
     std::vector<map_item_stack> ret;
     auto z = item_filter_from_string( filter );
     std::copy_if( stack.begin(), stack.end(),
     std::back_inserter( ret ), [z]( const map_item_stack & a ) {
         if( a.example != nullptr ) {
             return z( *a.example );
         }
         return false;
     } );
     return ret;
 }
References a, filter, item_filter_from_string(), and cata::hash64_detail::ret.
Referenced by game::list_items().
list_filter_high_priority()
int list_filter_high_priority (std::vector< map_item_stack > & stack, const std::string & priorities)
Definition at line 77 of file map_item_stack.cpp.
 {
     // TODO:optimize if necessary
     std::vector<map_item_stack> tempstack;
     const auto filter_fn = item_filter_from_string( priorities );
     for( auto it = stack.begin(); it != stack.end(); ) {
         if( priorities.empty() || ( it->example != nullptr && !filter_fn( *it->example ) ) ) {
             tempstack.push_back( *it );
             it = stack.erase( it );
         } else {
             it++;
         }
     }
     int id = stack.size();
     for( map_item_stack &elem : tempstack ) {
         stack.push_back( elem );
     }
     return id;
 }
References int_id< T >::id(), and item_filter_from_string().
Referenced by game::list_items().
list_filter_low_priority()
int list_filter_low_priority (std::vector< map_item_stack > & stack, int start, const std::string & priorities)
Definition at line 98 of file map_item_stack.cpp.
 {
     // TODO:optimize if necessary
     std::vector<map_item_stack> tempstack;
     const auto filter_fn = item_filter_from_string( priorities );
     for( auto it = stack.begin() + start; it != stack.end(); ) {
         if( !priorities.empty() && it->example != nullptr && filter_fn( *it->example ) ) {
             tempstack.push_back( *it );
             it = stack.erase( it );
         } else {
             it++;
         }
     }
     int id = stack.size();
     for( map_item_stack &elem : tempstack ) {
         stack.push_back( elem );
     }
     return id;
 }
References int_id< T >::id(), and item_filter_from_string().
Referenced by game::list_items().