Cataclysm DDA: src/map_field.cpp File Reference
map_field.cpp File Reference
#include <algorithm>
#include <array>
#include <bitset>
#include <cmath>
#include <cstddef>
#include <functional>
#include <iosfwd>
#include <list>
#include <map>
#include <memory>
#include <new>
#include <optional>
#include <queue>
#include <set>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "avatar.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "colony.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "creature.h"
#include "creature_tracker.h"
#include "damage.h"
#include "debug.h"
#include "effect.h"
#include "emit.h"
#include "enums.h"
#include "field.h"
#include "field_type.h"
#include "fire.h"
#include "fungal_effects.h"
#include "game.h"
#include "game_constants.h"
#include "item.h"
#include "itype.h"
#include "level_cache.h"
#include "line.h"
#include "make_static.h"
#include "map.h"
#include "map_field.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "material.h"
#include "messages.h"
#include "mongroup.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "overmapbuffer.h"
#include "point.h"
#include "rng.h"
#include "scent_block.h"
#include "scent_map.h"
#include "submap.h"
#include "teleport.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "weather.h"
Classes
struct field_proc_data
Common field processing data: shared per submap and field_type.
Functions
bool ter_furn_has_flag (const ter_t &ter, const furn_t &furn, const ter_furn_flag flag)
static int ter_furn_movecost (const ter_t &ter, const furn_t &furn)
static void field_processor_upgrade_intensity (const tripoint &, field_entry &cur, field_proc_data &)
static void field_processor_underwater_dissipation (const tripoint &, field_entry &cur, field_proc_data &pd)
static void field_processor_fd_acid (const tripoint &p, field_entry &cur, field_proc_data &pd)
static void field_processor_fd_extinguisher (const tripoint &p, field_entry &cur, field_proc_data &pd)
static void field_processor_apply_slime (const tripoint &p, field_entry &cur, field_proc_data &pd)
void field_processor_spread_gas (const tripoint &p, field_entry &cur, field_proc_data &pd)
static void field_processor_fd_fungal_haze (const tripoint &p, field_entry &cur, field_proc_data &)
static void field_processor_extra_radiation (const tripoint &p, field_entry &cur, field_proc_data &pd)
void field_processor_wandering_field (const tripoint &p, field_entry &cur, field_proc_data &pd)
void field_processor_fd_fire_vent (const tripoint &p, field_entry &cur, field_proc_data &pd)
void field_processor_fd_flame_burst (const tripoint &p, field_entry &cur, field_proc_data &pd)
static void field_processor_fd_electricity (const tripoint &p, field_entry &cur, field_proc_data &pd)
static void field_processor_monster_spawn (const tripoint &p, field_entry &cur, field_proc_data &pd)
static void field_processor_fd_push_items (const tripoint &p, field_entry &, field_proc_data &pd)
static void field_processor_fd_shock_vent (const tripoint &p, field_entry &cur, field_proc_data &pd)
static void field_processor_fd_acid_vent (const tripoint &p, field_entry &cur, field_proc_data &pd)
void field_processor_fd_incendiary (const tripoint &p, field_entry &cur, field_proc_data &pd)
static void field_processor_make_rubble (const tripoint &p, field_entry &, field_proc_data &pd)
static void field_processor_fd_fungicidal_gas (const tripoint &p, field_entry &cur, field_proc_data &pd)
void field_processor_fd_fire (const tripoint &p, field_entry &cur, field_proc_data &pd)
static void field_processor_fd_last_known (const tripoint &p, field_entry &cur, field_proc_data &pd)
Variables
static const damage_type_id damage_acid ("acid")
static const damage_type_id damage_bash ("bash")
static const damage_type_id damage_electric ("electric")
static const damage_type_id damage_heat ("heat")
static const efftype_id effect_badpoison ("badpoison")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_corroding ("corroding")
static const efftype_id effect_fungus ("fungus")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_poison ("poison")
static const efftype_id effect_stunned ("stunned")
static const efftype_id effect_teargas ("teargas")
static const flag_id json_flag_NO_UNLOAD ("NO_UNLOAD")
static const furn_str_id furn_f_ash ("f_ash")
static const itype_id itype_rm13_armor_on ("rm13_armor_on")
static const itype_id itype_rock ("rock")
static const json_character_flag json_flag_HEATSINK ("HEATSINK")
static const material_id material_iflesh ("iflesh")
static const material_id material_veggy ("veggy")
static const species_id species_FUNGUS ("FUNGUS")
static const ter_str_id ter_t_dirt ("t_dirt")
static const ter_str_id ter_t_open_air ("t_open_air")
static const ter_str_id ter_t_pit ("t_pit")
static const ter_str_id ter_t_rock_floor ("t_rock_floor")
static const trait_id trait_ACIDPROOF ("ACIDPROOF")
static const trait_id trait_GASTROPOD_FOOT ("GASTROPOD_FOOT")
static const trait_id trait_M_IMMUNE ("M_IMMUNE")
static const trait_id trait_M_SKIN2 ("M_SKIN2")
static const trait_id trait_M_SKIN3 ("M_SKIN3")
static const trait_id trait_THRESH_INSECT ("THRESH_INSECT")
static const trait_id trait_THRESH_MARLOSS ("THRESH_MARLOSS")
static const trait_id trait_THRESH_MYCUS ("THRESH_MYCUS")
static const trait_id trait_THRESH_SPIDER ("THRESH_SPIDER")
Function Documentation
field_processor_apply_slime()
static void field_processor_apply_slime (const tripoint & p, field_entry & cur, field_proc_data & pd) static
Definition at line 567 of file map_field.cpp.
 {
     // if( cur_fd_type.apply_slime_factor > 0 )
     pd.sblk.apply_slime( p, cur.get_field_intensity() * pd.cur_fd_type->apply_slime_factor );
 }
References scent_block::apply_slime(), field_type::apply_slime_factor, field_proc_data::cur_fd_type, field_entry::get_field_intensity(), and field_proc_data::sblk.
Referenced by map_field_processing::processors_for_type().
field_processor_extra_radiation()
static void field_processor_extra_radiation (const tripoint & p, field_entry & cur, field_proc_data & pd) static
Definition at line 593 of file map_field.cpp.
 {
     // Apply radiation
     const field_intensity_level &ilevel = cur.get_intensity_level();
     if( ilevel.extra_radiation_max > 0 ) {
         int extra_radiation = rng( ilevel.extra_radiation_min, ilevel.extra_radiation_max );
         pd.here.adjust_radiation( p, extra_radiation );
     }
 }
References map::adjust_radiation(), field_intensity_level::extra_radiation_max, field_intensity_level::extra_radiation_min, field_entry::get_intensity_level(), field_proc_data::here, and rng().
Referenced by map_field_processing::processors_for_type().
field_processor_fd_acid()
static void field_processor_fd_acid (const tripoint & p, field_entry & cur, field_proc_data & pd) static
Definition at line 522 of file map_field.cpp.
 {
     //cur_fd_type_id == fd_acid
     if( p.z <= -OVERMAP_DEPTH ) {
         return;
     }
     // Try to fall by a z-level
     tripoint dst{ p.xy(), p.z - 1 };
     if( pd.here.valid_move( p, dst, true, true ) ) {
         field_entry *acid_there = pd.here.get_field( dst, fd_acid );
         if( !acid_there ) {
             pd.here.add_field( dst, fd_acid, cur.get_field_intensity(), cur.get_field_age() );
         } else {
             // Math can be a bit off,
             // but "boiling" falling acid can be allowed to be stronger
             // than acid that just lies there
             const int sum_intensity = cur.get_field_intensity() + acid_there->get_field_intensity();
             const int new_intensity = std::min( 3, sum_intensity );
             // No way to get precise elapsed time, let's always reset
             // Allow falling acid to last longer than regular acid to show it off
             const time_duration new_age = -1_minutes * ( sum_intensity - new_intensity );
             acid_there->set_field_intensity( new_intensity );
             acid_there->set_field_age( new_age );
         }
         // Set ourselves up for removal
         cur.set_field_intensity( 0 );
     }
     // TODO: Allow spreading to the sides if age < 0 && intensity == 3
 }
References map::add_field(), fd_acid, map::get_field(), field_entry::get_field_age(), field_entry::get_field_intensity(), field_proc_data::here, min(), OVERMAP_DEPTH, field_entry::set_field_age(), field_entry::set_field_intensity(), map::valid_move(), tripoint::xy(), and tripoint::z.
Referenced by map_field_processing::processors_for_type().
field_processor_fd_acid_vent()
static void field_processor_fd_acid_vent (const tripoint & p, field_entry & cur, field_proc_data & pd) static
Definition at line 867 of file map_field.cpp.
 {
     if( cur.get_field_intensity() > 1 ) {
         if( cur.get_field_age() >= 1_minutes ) {
             cur.set_field_intensity( cur.get_field_intensity() - 1 );
             cur.set_field_age( 0_turns );
         }
     } else {
         cur.set_field_intensity( 3 );
         for( const tripoint &t : points_in_radius( p, 5 ) ) {
             const field_entry *acid = pd.here.get_field( t, fd_acid );
             if( acid && acid->get_field_intensity() == 0 ) {
                 int new_intensity = 3 - rl_dist( p, t ) / 2 + ( one_in( 3 ) ? 1 : 0 );
                 if( new_intensity > 3 ) {
                     new_intensity = 3;
                 }
                 if( new_intensity > 0 ) {
                     pd.here.add_field( t, fd_acid, new_intensity );
                 }
             }
         }
     }
 }
References mattack::acid(), map::add_field(), fd_acid, map::get_field(), field_entry::get_field_age(), field_entry::get_field_intensity(), field_proc_data::here, one_in(), points_in_radius(), rl_dist(), field_entry::set_field_age(), and field_entry::set_field_intensity().
Referenced by map_field_processing::processors_for_type().
field_processor_fd_electricity()
static void field_processor_fd_electricity (const tripoint & p, field_entry & cur, field_proc_data & pd) static
Definition at line 644 of file map_field.cpp.
 {
     // Higher chance of spreading for intense fields
     int current_intensity = cur.get_field_intensity();
     if( one_in( current_intensity * 2 ) ) {
         return;
     }
     const int spread_intensity_cap = 3 + std::max( ( current_intensity - 3 ) / 2, 0 );
     std::vector<tripoint> grounded_tiles;
     std::vector<tripoint> tiles_with_creatures;
     std::vector<tripoint> other_tiles;
     bool valid_candidates = false;
     for( const tripoint &dst : points_in_radius( p, 1 ) ) {
         if( !pd.here.inbounds( dst ) ) {
             continue;
         }
         // Skip tiles with intense fields
         const field_type_str_id &field_type = pd.here.get_applicable_electricity_field( dst );
         if( field_entry *field = pd.here.get_field( dst, field_type ) ) {
             if( field->get_field_intensity() >= spread_intensity_cap ) {
                 continue;
             }
         }
         if( pd.here.impassable( dst ) ) {
             grounded_tiles.push_back( dst );
         } else {
             if( get_creature_tracker().creature_at( dst ) ) {
                 tiles_with_creatures.push_back( dst );
             } else {
                 other_tiles.push_back( dst );
             }
         }
         valid_candidates = true;
     }
     if( !valid_candidates ) {
         return;
     }
     const bool here_impassable = pd.here.impassable( p );
     int grounded_weight = here_impassable ? 1 : 6;
     int creature_weight = here_impassable ? 5 : 6;
     int other_weight = here_impassable ? 0 : 1;
     std::vector<tripoint> *target_vector = nullptr;
     while( current_intensity > 0 ) {
         if( here_impassable && one_in( 3 ) ) {
             // Electricity in impassable tiles will find a way to the ground sometimes
             cur.set_field_intensity( --current_intensity );
             continue;
         }
         const int vector_choice = bucket_index_from_weight_list( std::vector<int>( {
             grounded_tiles.empty() ? 0 : grounded_weight,
             tiles_with_creatures.empty() ? 0 : creature_weight,
             other_tiles.empty() ? 0 : other_weight
         } ) );
         switch( vector_choice ) {
             default:
             case 0:
                 if( here_impassable && !one_in( 5 ) ) {
                     return;
                 }
                 target_vector = &grounded_tiles;
                 break;
             case 1:
                 target_vector = &tiles_with_creatures;
                 break;
             case 2:
                 target_vector = &other_tiles;
                 break;
         }
         if( target_vector->empty() ) {
             return;
         }
         int vector_index = rng( 0, target_vector->size() - 1 );
         auto target_it = target_vector->begin() + vector_index;
         tripoint target_point = *target_it;
         const field_type_str_id &field_type = pd.here.get_applicable_electricity_field( target_point );
         // Intensify target field if it exists, create a new one otherwise
         if( field_entry *target_field = pd.here.get_field( target_point, field_type ) ) {
             int target_field_intensity = target_field->get_field_intensity();
             target_field->set_field_intensity( ++target_field_intensity );
             if( target_field_intensity >= spread_intensity_cap ) {
                 target_vector->erase( target_it );
             }
         } else {
             pd.here.add_field( target_point, field_type, 1, cur.get_field_age() + 1_turns );
         }
         cur.set_field_intensity( --current_intensity );
         if( one_in( current_intensity * 2 ) ) {
             // Weaker fields have a harder time spreading
             break;
         }
     }
 }
References map::add_field(), bucket_index_from_weight_list(), map::get_applicable_electricity_field(), get_creature_tracker(), map::get_field(), field_entry::get_field_age(), field_entry::get_field_intensity(), field_proc_data::here, map::impassable(), map::inbounds(), max(), one_in(), points_in_radius(), rng(), and field_entry::set_field_intensity().
Referenced by map_field_processing::processors_for_type().
field_processor_fd_extinguisher()
static void field_processor_fd_extinguisher (const tripoint & p, field_entry & cur, field_proc_data & pd) static
Definition at line 555 of file map_field.cpp.
 {
     //  if( cur_fd_type_id == fd_extinguisher )
     if( field_entry *fire_here = pd.map_tile.find_field( fd_fire ) ) {
         // extinguisher fights fire in 1:1 ratio
         const int min_int = std::min( fire_here->get_field_intensity(), cur.get_field_intensity() );
         pd.here.mod_field_intensity( p, fd_fire, -min_int );
         cur.mod_field_intensity( -min_int );
     }
 }
References fd_fire, maptile_impl< Submap >::find_field(), field_entry::get_field_intensity(), field_proc_data::here, field_proc_data::map_tile, min(), map::mod_field_intensity(), and field_entry::mod_field_intensity().
Referenced by map_field_processing::processors_for_type().
field_processor_fd_fire()
void field_processor_fd_fire (const tripoint & p, field_entry & cur, field_proc_data & pd)
Definition at line 932 of file map_field.cpp.
 {
     const field_type_id fd_fire = ::fd_fire;
     map &here = pd.here;
     maptile &map_tile = pd.map_tile;
     const oter_id om_ter = pd.om_ter;
     cur.set_field_age( std::max( -24_hours, cur.get_field_age() ) );
     // Entire objects for ter/frn for flags
     bool sheltered = g->is_sheltered( p );
     weather_manager &weather = get_weather();
     int winddirection = weather.winddirection;
     int windpower = get_local_windpower( weather.windspeed, om_ter, tripoint_abs_ms( p ), winddirection,
                                          sheltered );
     const ter_t &ter = map_tile.get_ter_t();
     const furn_t &frn = map_tile.get_furn_t();
     // We've got ter/furn cached, so let's use that
     const bool is_sealed = ter_furn_has_flag( ter, frn, ter_furn_flag::TFLAG_SEALED ) &&
                            !ter_furn_has_flag( ter, frn, ter_furn_flag::TFLAG_ALLOW_FIELD_EFFECT );
     // Smoke generation probability, consumed items count
     int smoke = 0;
     int consumed = 0;
     // How much time to add to the fire's life due to burned items/terrain/furniture
     time_duration time_added = 0_turns;
     // Checks if the fire can spread
     const bool can_spread = !ter_furn_has_flag( ter, frn, ter_furn_flag::TFLAG_FIRE_CONTAINER );
     // If the flames are in furniture with fire_container flag like brazier or oven,
     // they're fully contained, so skip consuming terrain
     const bool can_burn = ( ter.is_flammable() || frn.is_flammable() ) &&
                           !ter_furn_has_flag( ter, frn, ter_furn_flag::TFLAG_FIRE_CONTAINER );
     // The huge indent below should probably be somehow moved away from here
     // without forcing the function to use i_at( p ) for fires without items
     if( !is_sealed && map_tile.get_item_count() > 0 ) {
         map_stack items_here = here.i_at( p );
         std::vector<item> new_content;
         for( auto it = items_here.begin(); it != items_here.end(); ) {
             if( it->will_explode_in_fire() ) {
                 // We need to make a copy because the iterator validity is not predictable
                 item copy = *it;
                 it = items_here.erase( it );
                 if( copy.detonate( p, new_content ) ) {
                     // Need to restart, iterators may not be valid
                     it = items_here.begin();
                 }
             } else {
                 ++it;
             }
         }
         fire_data frd( cur.get_field_intensity(), !can_spread );
         // The highest # of items this fire can remove in one turn
         int max_consume = cur.get_field_intensity() * 2;
         for( auto fuel = items_here.begin(); fuel != items_here.end() && consumed < max_consume; ) {
             // `item::burn` modifies the charges in order to simulate some of them getting
             // destroyed by the fire, this changes the item weight, but may not actually
             // destroy it. We need to spawn products anyway.
             const units::mass old_weight = fuel->weight( false );
             bool destroyed = fuel->burn( frd );
             // If the item is considered destroyed, it may have negative charge count,
             // see `item::burn?. This in turn means `item::weight` returns a negative value,
             // which we can not use, so only call `weight` when it's still an existing item.
             const units::mass new_weight = destroyed ? 0_gram : fuel->weight( false );
             if( old_weight != new_weight ) {
                 here.create_burnproducts( p, *fuel, old_weight - new_weight );
             }
             if( destroyed ) {
                 // If we decided the item was destroyed by fire, remove it.
                 // But remember its contents, except for irremovable stuff, if any
                 if( !fuel->has_flag( json_flag_NO_UNLOAD ) ) {
                     const std::list<item *> content_list = fuel->all_items_top();
                     for( item *it : content_list ) {
                         if( !it->is_irremovable() ) {
                             new_content.emplace_back( *it );
                         }
                     }
                 }
                 fuel = items_here.erase( fuel );
                 consumed++;
             } else {
                 ++fuel;
             }
         }
         here.spawn_items( p, new_content );
         smoke = roll_remainder( frd.smoke_produced );
         time_added = 1_turns * roll_remainder( frd.fuel_produced );
     }
     int part;
     // Get the part of the vehicle in the fire (_internal skips the boundary check)
     vehicle *veh = here.veh_at_internal( p, part );
     if( veh != nullptr ) {
         veh->damage( here, part, cur.get_field_intensity() * 10, damage_heat, true );
         // Damage the vehicle in the fire.
     }
     if( can_burn ) {
         if( ter.has_flag( ter_furn_flag::TFLAG_SWIMMABLE ) ) {
             // Flames die quickly on water
             cur.set_field_age( cur.get_field_age() + 4_minutes );
         }
         // Consume the terrain we're on
         if( ter_furn_has_flag( ter, frn, ter_furn_flag::TFLAG_FLAMMABLE ) ) {
             // The fire feeds on the ground itself until max intensity.
             time_added += 1_turns * ( 5 - cur.get_field_intensity() );
             smoke += 2;
             smoke += static_cast<int>( windpower / 5 );
             if( cur.get_field_intensity() > 1 &&
                 one_in( 200 - cur.get_field_intensity() * 50 ) ) {
                 here.destroy( p, false );
             }
         } else if( ter_furn_has_flag( ter, frn, ter_furn_flag::TFLAG_FLAMMABLE_HARD ) &&
                    one_in( 3 ) ) {
             // The fire feeds on the ground itself until max intensity.
             time_added += 1_turns * ( 4 - cur.get_field_intensity() );
             smoke += 2;
             smoke += static_cast<int>( windpower / 5 );
             if( cur.get_field_intensity() > 1 &&
                 one_in( 200 - cur.get_field_intensity() * 50 ) ) {
                 here.destroy( p, false );
             }
         } else if( ter.has_flag( ter_furn_flag::TFLAG_FLAMMABLE_ASH ) ) {
             // The fire feeds on the ground itself until max intensity.
             time_added += 1_turns * ( 5 - cur.get_field_intensity() );
             smoke += 2;
             smoke += static_cast<int>( windpower / 5 );
             if( cur.get_field_intensity() > 1 &&
                 one_in( 200 - cur.get_field_intensity() * 50 ) ) {
                 here.spawn_item( p, "ash", 1, rng( 10, 1000 ) );
                 if( p.z > 0 ) {
                     // We're in the air. Need to invalidate the furniture otherwise it'll cause problems
                     here.furn_set( p, furn_str_id::NULL_ID() );
                     here.ter_set( p, ter_t_open_air );
                 } else if( p.z < -1 ) {
                     // We're deep underground, in bedrock. Whatever terrain was here is burned to the ground, leaving only the carved out rock (including ceiling)
                     here.ter_set( p, ter_t_rock_floor );
                 } else {
                     // Need to invalidate the furniture otherwise it'll cause problems when supporting terrain collapses
                     here.furn_set( p, furn_str_id::NULL_ID() );
                     here.ter_set( p, ter_t_dirt );
                 }
             }
         } else if( frn.has_flag( ter_furn_flag::TFLAG_FLAMMABLE_ASH ) ) {
             // The fire feeds on the ground itself until max intensity.
             time_added += 1_turns * ( 5 - cur.get_field_intensity() );
             smoke += 2;
             smoke += static_cast<int>( windpower / 5 );
             if( cur.get_field_intensity() > 1 &&
                 one_in( 200 - cur.get_field_intensity() * 50 ) ) {
                 here.furn_set( p, furn_f_ash );
                 here.add_item_or_charges( p, item( "ash" ) );
             }
         } else if( ter.has_flag( ter_furn_flag::TFLAG_NO_FLOOR ) && p.z > -OVERMAP_DEPTH ) {
             // We're hanging in the air - let's fall down
             tripoint dst{ p.xy(), p.z - 1 };
             if( here.valid_move( p, dst, true, true ) ) {
                 maptile dst_tile = here.maptile_at_internal( dst );
                 field_entry *fire_there = dst_tile.find_field( fd_fire );
                 if( !fire_there ) {
                     here.add_field( dst, fd_fire, 1, 0_turns, false );
                     cur.mod_field_intensity( -1 );
                 } else {
                     // Don't fuel raging fires or they'll burn forever
                     // as they can produce small fires above themselves
                     int new_intensity = std::max( cur.get_field_intensity(),
                                                   fire_there->get_field_intensity() );
                     // Allow smaller fires to combine
                     if( new_intensity < 3 &&
                         cur.get_field_intensity() == fire_there->get_field_intensity() ) {
                         new_intensity++;
                     }
                     // A raging fire below us can support us for a while
                     // Otherwise decay and decay fast
                     if( fire_there->get_field_intensity() < 3 || one_in( 10 ) ) {
                         cur.set_field_intensity( cur.get_field_intensity() - 1 );
                     }
                     fire_there->set_field_intensity( new_intensity );
                 }
                 return;
             }
         }
     }
     // Lower age is a longer lasting fire
     if( time_added != 0_turns ) {
         cur.set_field_age( cur.get_field_age() - time_added );
     } else if( can_burn ) {
         // Nothing to burn = fire should be dying out faster
         // Drain more power from big fires, so that they stop raging over nothing
         // Except for fires on stoves and fireplaces, those are made to keep the fire alive
         cur.mod_field_age( 10_seconds * cur.get_field_intensity() );
     }
     // Below we will access our nearest 8 neighbors, so let's cache them now
     // This should probably be done more globally, because large fires will re-do it a lot
     auto neighs = here.get_neighbors( p );
     // Get the neighbours that are allowed due to wind direction
     auto maptiles = here.get_wind_blockers( winddirection, p );
     maptile remove_tile = std::get<0>( maptiles );
     maptile remove_tile2 = std::get<1>( maptiles );
     maptile remove_tile3 = std::get<2>( maptiles );
     std::vector<size_t> neighbour_vec;
     neighbour_vec.reserve( neighs.size() );
     size_t end_it = static_cast<size_t>( rng( 0, neighs.size() - 1 ) );
     // Start at end_it + 1, then wrap around until all elements have been processed
     for( size_t i = ( end_it + 1 ) % neighs.size(), count = 0;
          count != neighs.size();
          i = ( i + 1 ) % neighs.size(), count++ ) {
         const maptile &neigh = neighs[i].second;
         if( ( neigh.pos().x != remove_tile.pos().x && neigh.pos().y != remove_tile.pos().y ) ||
             ( neigh.pos().x != remove_tile2.pos().x && neigh.pos().y != remove_tile2.pos().y ) ||
             ( neigh.pos().x != remove_tile3.pos().x && neigh.pos().y != remove_tile3.pos().y ) ||
             x_in_y( 1, std::max( 2, windpower ) ) ) {
             neighbour_vec.push_back( i );
         }
     }
     // If the flames are in a pit, it can't spread to non-pit
     const bool in_pit = ter.id.id() == ter_t_pit;
     // Count adjacent fires, to optimize out needless smoke and hot air
     int adjacent_fires = 0;
     // If the flames are big, they contribute to adjacent flames
     if( can_spread ) {
         if( cur.get_field_intensity() > 1 && one_in( 3 ) ) {
             // Basically: Scan around for a spot,
             // if there is more fire there, make it bigger and give it some fuel.
             // This is how big fires spend their excess age:
             // making other fires bigger. Flashpoint.
             if( sheltered || windpower < 5 ) {
                 end_it = static_cast<size_t>( rng( 0, neighs.size() - 1 ) );
                 for( size_t i = ( end_it + 1 ) % neighs.size(), count = 0;
                      count != neighs.size() && cur.get_field_age() < 0_turns;
                      i = ( i + 1 ) % neighs.size(), count++ ) {
                     maptile &dst = neighs[i].second;
                     field_entry *dstfld = dst.find_field( fd_fire );
                     // If the fire exists and is weaker than ours, boost it
                     if( dstfld &&
                         ( dstfld->get_field_intensity() <= cur.get_field_intensity() ||
                           dstfld->get_field_age() > cur.get_field_age() ) &&
                         ( in_pit == ( dst.get_ter() == ter_t_pit ) ) ) {
                         if( dstfld->get_field_intensity() < 2 ) {
                             // HACK: ignoring all map field caches, since field already exists
                             // and intensity is increased, not decreased
                             dstfld->mod_field_intensity( 1 );
                         }
                         dstfld->mod_field_age( -5_minutes );
                         cur.set_field_age( cur.get_field_age() + 5_minutes );
                     }
                     if( dstfld ) {
                         adjacent_fires++;
                     }
                 }
             } else {
                 end_it = static_cast<size_t>( rng( 0, neighbour_vec.size() - 1 ) );
                 for( size_t i = ( end_it + 1 ) % neighbour_vec.size(), count = 0;
                      count != neighbour_vec.size() && cur.get_field_age() < 0_turns;
                      i = ( i + 1 ) % neighbour_vec.size(), count++ ) {
                     maptile &dst = neighs[neighbour_vec[i]].second;
                     field_entry *dstfld = dst.find_field( fd_fire );
                     // If the fire exists and is weaker than ours, boost it
                     if( dstfld &&
                         ( dstfld->get_field_intensity() <= cur.get_field_intensity() ||
                           dstfld->get_field_age() > cur.get_field_age() ) &&
                         ( in_pit == ( dst.get_ter() == ter_t_pit ) ) ) {
                         if( dstfld->get_field_intensity() < 2 ) {
                             // HACK: ignoring all map field caches, since field already exists
                             // and intensity is increased, not decreased
                             dstfld->mod_field_intensity( 1 );
                         }
                         dstfld->set_field_age( dstfld->get_field_age() - 5_minutes );
                         cur.set_field_age( cur.get_field_age() + 5_minutes );
                     }
                     if( dstfld ) {
                         adjacent_fires++;
                     }
                 }
             }
         } else if( cur.get_field_age() < 0_turns && cur.get_field_intensity() < 3 ) {
             // See if we can grow into a stage 2/3 fire, for this
             // burning neighbors are necessary in addition to
             // field age < 0, or alternatively, a LOT of fuel.
             // The maximum fire intensity is 1 for a lone fire, 2 for at least 1 neighbor,
             // 3 for at least 2 neighbors.
             int maximum_intensity = 1;
             // The following logic looks a bit complex due to optimization concerns, so here are the semantics:
             // 1. Calculate maximum field intensity based on fuel, -50 minutes is 2(medium), -500 minutes is 3(raging)
             // 2. Calculate maximum field intensity based on neighbors, 3 neighbors is 2(medium), 7 or more neighbors is 3(raging)
             // 3. Pick the higher maximum between 1. and 2.
             if( cur.get_field_age() < -500_minutes ) {
                 maximum_intensity = 3;
             } else {
                 for( auto &neigh : neighs ) {
                     if( neigh.second.get_field().find_field( fd_fire ) ) {
                         adjacent_fires++;
                     }
                 }
                 maximum_intensity = 1 + ( adjacent_fires >= 3 ) + ( adjacent_fires >= 7 );
                 if( maximum_intensity < 2 && cur.get_field_age() < -50_minutes ) {
                     maximum_intensity = 2;
                 }
             }
             // If we consumed a lot, the flames grow higher
             if( cur.get_field_intensity() < maximum_intensity && cur.get_field_age() < 0_turns ) {
                 // Fires under 0 age grow in size. Level 3 fires under 0 spread later on.
                 // Weaken the newly-grown fire
                 cur.set_field_intensity( cur.get_field_intensity() + 1 );
                 cur.set_field_age( cur.get_field_age() + 10_minutes * cur.get_field_intensity() );
             }
         }
     }
     // Consume adjacent fuel / terrain / webs to spread.
     // Allow raging fires (and only raging fires) to spread up
     // Spreading down is achieved by wrecking the walls/floor and then falling
     if( cur.get_field_intensity() == 3 && p.z < OVERMAP_HEIGHT ) {
         const tripoint dst_p = tripoint( p.xy(), p.z + 1 );
         // Let it burn through the floor
         maptile dst = here.maptile_at_internal( dst_p );
         const ter_t &dst_ter = dst.get_ter_t();
         if( dst_ter.has_flag( ter_furn_flag::TFLAG_NO_FLOOR ) ||
             dst_ter.has_flag( ter_furn_flag::TFLAG_FLAMMABLE ) ||
             dst_ter.has_flag( ter_furn_flag::TFLAG_FLAMMABLE_ASH ) ||
             dst_ter.has_flag( ter_furn_flag::TFLAG_FLAMMABLE_HARD ) ) {
             field_entry *nearfire = dst.find_field( fd_fire );
             if( nearfire != nullptr ) {
                 nearfire->mod_field_age( -2_turns );
             } else {
                 here.add_field( dst_p, fd_fire, 1, 0_turns, false );
             }
             // Fueling fires above doesn't cost fuel
         }
     }
     // Our iterator will start at end_i + 1 and increment from there and then wrap around.
     // This guarantees it will check all neighbors, starting from a random one
     if( sheltered || windpower < 5 ) {
         const size_t end_i = static_cast<size_t>( rng( 0, neighs.size() - 1 ) );
         for( size_t i = ( end_i + 1 ) % neighs.size(), count = 0;
              count != neighs.size();
              i = ( i + 1 ) % neighs.size(), count++ ) {
             if( one_in( cur.get_field_intensity() * 2 ) ) {
                 // Skip some processing to save on CPU
                 continue;
             }
             tripoint &dst_p = neighs[i].first;
             maptile &dst = neighs[i].second;
             // No bounds checking here: we'll treat the invalid neighbors as valid.
             // We're using the map tile wrapper, so we can treat invalid tiles as sentinels.
             // This will create small oddities on map edges, but nothing more noticeable than
             // "cut-off" that happens with bounds checks.
             if( dst.find_field( fd_fire ) ) {
                 // We handled supporting fires in the section above, no need to do it here
                 continue;
             }
             field_entry *nearwebfld = dst.find_field( fd_web );
             int spread_chance = 25 * ( cur.get_field_intensity() - 1 );
             if( nearwebfld ) {
                 spread_chance = 50 + spread_chance / 2;
             }
             const ter_t &dster = dst.get_ter_t();
             const furn_t &dsfrn = dst.get_furn_t();
             // Allow weaker fires to spread occasionally
             const int power = cur.get_field_intensity() + one_in( 5 );
             if( can_spread && rng( 1, 100 ) < spread_chance &&
                 ( in_pit == ( dster.id.id() == ter_t_pit ) ) &&
                 (
                     ( power >= 2 && ( ter_furn_has_flag( dster, dsfrn, ter_furn_flag::TFLAG_FLAMMABLE ) &&
                                       one_in( 2 ) ) ) ||
                     ( power >= 2 && ( ter_furn_has_flag( dster, dsfrn, ter_furn_flag::TFLAG_FLAMMABLE_ASH ) &&
                                       one_in( 2 ) ) ) ||
                     ( power >= 3 && ( ter_furn_has_flag( dster, dsfrn, ter_furn_flag::TFLAG_FLAMMABLE_HARD ) &&
                                       one_in( 5 ) ) ) ||
                     nearwebfld ||
                     ( one_in( 5 ) && dst.get_item_count() > 0 &&
                       here.flammable_items_at( p + eight_horizontal_neighbors[i] ) )
                 ) ) {
                 // Nearby open flammable ground? Set it on fire.
                 // Make the new fire quite weak, so that it doesn't start jumping around instantly
                 if( here.add_field( dst_p, fd_fire, 1, 2_minutes, false ) ) {
                     // Consume a bit of our fuel
                     cur.set_field_age( cur.get_field_age() + 1_minutes );
                 }
                 if( nearwebfld ) {
                     nearwebfld->set_field_intensity( 0 );
                 }
             }
         }
     } else {
         const size_t end_i = static_cast<size_t>( rng( 0, neighbour_vec.size() - 1 ) );
         for( size_t i = ( end_i + 1 ) % neighbour_vec.size(), count = 0;
              count != neighbour_vec.size();
              i = ( i + 1 ) % neighbour_vec.size(), count++ ) {
             if( one_in( cur.get_field_intensity() * 2 ) ) {
                 // Skip some processing to save on CPU
                 continue;
             }
             if( neighbour_vec.empty() ) {
                 continue;
             }
             tripoint &dst_p = neighs[neighbour_vec[i]].first;
             maptile &dst = neighs[neighbour_vec[i]].second;
             // No bounds checking here: we'll treat the invalid neighbors as valid.
             // We're using the map tile wrapper, so we can treat invalid tiles as sentinels.
             // This will create small oddities on map edges, but nothing more noticeable than
             // "cut-off" that happens with bounds checks.
             if( dst.find_field( fd_fire ) ) {
                 // We handled supporting fires in the section above, no need to do it here
                 continue;
             }
             field_entry *nearwebfld = dst.find_field( fd_web );
             int spread_chance = 25 * ( cur.get_field_intensity() - 1 );
             if( nearwebfld ) {
                 spread_chance = 50 + spread_chance / 2;
             }
             const ter_t &dster = dst.get_ter_t();
             const furn_t &dsfrn = dst.get_furn_t();
             // Allow weaker fires to spread occasionally
             const int power = cur.get_field_intensity() + one_in( 5 );
             if( can_spread && rng( 1, 100 ) < spread_chance &&
                 ( in_pit == ( dster.id.id() == ter_t_pit ) ) &&
                 (
                     ( power >= 2 && ( ter_furn_has_flag( dster, dsfrn, ter_furn_flag::TFLAG_FLAMMABLE ) &&
                                       one_in( 2 ) ) ) ||
                     ( power >= 2 && ( ter_furn_has_flag( dster, dsfrn, ter_furn_flag::TFLAG_FLAMMABLE_ASH ) &&
                                       one_in( 2 ) ) ) ||
                     ( power >= 3 && ( ter_furn_has_flag( dster, dsfrn, ter_furn_flag::TFLAG_FLAMMABLE_HARD ) &&
                                       one_in( 5 ) ) ) ||
                     nearwebfld ||
                     ( one_in( 5 ) && dst.get_item_count() > 0 &&
                       here.flammable_items_at( p + eight_horizontal_neighbors[i] ) )
                 ) ) {
                 // Nearby open flammable ground? Set it on fire.
                 // Make the new fire quite weak, so that it doesn't start jumping around instantly
                 if( here.add_field( dst_p, fd_fire, 1, 2_minutes, false ) ) {
                     // Consume a bit of our fuel
                     cur.set_field_age( cur.get_field_age() + 1_minutes );
                 }
                 if( nearwebfld ) {
                     nearwebfld->set_field_intensity( 0 );
                 }
             }
         }
     }
     // Create smoke once - above us if possible, at us otherwise
     if( !ter_furn_has_flag( ter, frn, ter_furn_flag::TFLAG_SUPPRESS_SMOKE ) &&
         rng( 0, 100 - windpower ) <= smoke &&
         rng( 3, 35 ) < cur.get_field_intensity() * 10 ) {
         bool smoke_up = p.z < OVERMAP_HEIGHT;
         if( smoke_up ) {
             tripoint up{p.xy(), p.z + 1};
             if( here.has_flag_ter( ter_furn_flag::TFLAG_NO_FLOOR, up ) ) {
                 here.add_field( up, fd_smoke, rng( 1, cur.get_field_intensity() ), 0_turns, false );
             } else {
                 // Can't create smoke above
                 smoke_up = false;
             }
         }
         if( !smoke_up ) {
             // Create thicker smoke
             here.add_field( p, fd_smoke, cur.get_field_intensity(), 0_turns, false );
         }
     }
     // Hot air is a load on the CPU
     // Don't produce too much of it if we have a lot fires nearby, they produce
     // radiant heat which does what hot air would do anyway
     if( adjacent_fires < 5 && rng( 0, 4 - adjacent_fires ) ) {
         here.create_hot_air( p, cur.get_field_intensity() );
     }
 }
Referenced by map_field_processing::processors_for_type().
field_processor_fd_fire_vent()
void field_processor_fd_fire_vent (const tripoint & p, field_entry & cur, field_proc_data & pd)
Definition at line 619 of file map_field.cpp.
 {
     if( cur.get_field_intensity() > 1 ) {
         if( one_in( 3 ) ) {
             cur.set_field_intensity( cur.get_field_intensity() - 1 );
         }
         pd.here.create_hot_air( p, cur.get_field_intensity() );
     } else {
         pd.here.add_field( p, fd_flame_burst, 3, cur.get_field_age() );
         cur.set_field_intensity( 0 );
     }
 }
Referenced by map_field_processing::processors_for_type().
field_processor_fd_flame_burst()
void field_processor_fd_flame_burst (const tripoint & p, field_entry & cur, field_proc_data & pd)
Definition at line 633 of file map_field.cpp.
 {
     if( cur.get_field_intensity() > 1 ) {
         cur.set_field_intensity( cur.get_field_intensity() - 1 );
         pd.here.create_hot_air( p, cur.get_field_intensity() );
     } else {
         pd.here.add_field( p, fd_fire_vent, 3, cur.get_field_age() );
         cur.set_field_intensity( 0 );
     }
 }
Referenced by map_field_processing::processors_for_type().
field_processor_fd_fungal_haze()
static void field_processor_fd_fungal_haze (const tripoint & p, field_entry & cur, field_proc_data &) static
Definition at line 581 of file map_field.cpp.
 {
     // if( cur_fd_type_id == fd_fungal_haze ) {
     if( one_in( 10 - 2 * cur.get_field_intensity() ) ) {
         // Haze'd terrain
         fungal_effects().spread_fungus( p );
     }
 }
References field_entry::get_field_intensity(), one_in(), and fungal_effects::spread_fungus().
Referenced by map_field_processing::processors_for_type().
field_processor_fd_fungicidal_gas()
static void field_processor_fd_fungicidal_gas (const tripoint & p, field_entry & cur, field_proc_data & pd) static
Definition at line 917 of file map_field.cpp.
 {
     // Check the terrain and replace it accordingly to simulate the fungus dieing off
     const ter_t &ter = pd.map_tile.get_ter_t();
     const furn_t &frn = pd.map_tile.get_furn_t();
     const int intensity = cur.get_field_intensity();
     if( ter.has_flag( ter_furn_flag::TFLAG_FUNGUS ) && one_in( 10 / intensity ) ) {
         pd.here.ter_set( p, ter_t_dirt );
     }
     if( frn.has_flag( ter_furn_flag::TFLAG_FUNGUS ) && one_in( 10 / intensity ) ) {
         pd.here.furn_set( p, furn_str_id::NULL_ID() );
     }
 }
References map::furn_set(), field_entry::get_field_intensity(), maptile_impl< Submap >::get_furn_t(), maptile_impl< Submap >::get_ter_t(), map_data_common_t::has_flag(), field_proc_data::here, intensity, field_proc_data::map_tile, string_id< furn_t >::NULL_ID(), one_in(), map::ter_set(), ter_t_dirt, and TFLAG_FUNGUS.
Referenced by map_field_processing::processors_for_type().
field_processor_fd_incendiary()
void field_processor_fd_incendiary (const tripoint & p, field_entry & cur, field_proc_data & pd)
Definition at line 891 of file map_field.cpp.
 {
     // Needed for variable scope
     tripoint dst( p + point( rng( -1, 1 ), rng( -1, 1 ) ) );
     if( pd.here.has_flag( ter_furn_flag::TFLAG_FLAMMABLE, dst ) ||
         pd.here.has_flag( ter_furn_flag::TFLAG_FLAMMABLE_ASH, dst ) ||
         pd.here.has_flag( ter_furn_flag::TFLAG_FLAMMABLE_HARD, dst ) ) {
         pd.here.add_field( dst, fd_fire, 1 );
     }
     // Check piles for flammable items and set those on fire
     if( pd.here.flammable_items_at( dst ) ) {
         pd.here.add_field( dst, fd_fire, 1 );
     }
     pd.here.create_hot_air( p, cur.get_field_intensity() );
 }
Referenced by map_field_processing::processors_for_type().
field_processor_fd_last_known()
static void field_processor_fd_last_known (const tripoint & p, field_entry & cur, field_proc_data & pd) static
Definition at line 1425 of file map_field.cpp.
 {
     ( void )pd;
     Creature *const loc_creature = get_creature_tracker().creature_at( p, false );
     // Remove field when duration expires or non-player creature enters
     if( cur.get_field_age() > 5_seconds || ( loc_creature != nullptr && !loc_creature->is_avatar() ) ) {
         cur.set_field_intensity( 0 );
     }
 }
References creature_tracker::creature_at(), get_creature_tracker(), field_entry::get_field_age(), Creature::is_avatar(), and field_entry::set_field_intensity().
Referenced by map_field_processing::processors_for_type().
field_processor_fd_push_items()
static void field_processor_fd_push_items (const tripoint & p, field_entry & , field_proc_data & pd) static
Definition at line 781 of file map_field.cpp.
 {
     map_stack items = pd.here.i_at( p );
     creature_tracker &creatures = get_creature_tracker();
     for( auto pushee = items.begin(); pushee != items.end(); ) {
         if( pushee->typeId() != itype_rock ||
             pushee->age() < 1_turns ) {
             pushee++;
         } else {
             std::vector<tripoint> valid;
             for( const tripoint &dst : points_in_radius( p, 1 ) ) {
                 if( dst != p && pd.here.get_field( dst, fd_push_items ) ) {
                     valid.push_back( dst );
                 }
             }
             if( !valid.empty() ) {
                 item tmp = *pushee;
                 tmp.set_age( 0_turns );
                 pushee = items.erase( pushee );
                 tripoint newp = random_entry( valid );
                 pd.here.add_item_or_charges( newp, tmp );
                 if( pd.player_character.pos() == newp ) {
                     add_msg( m_bad, _( "A %s hits you!" ), tmp.tname() );
                     const bodypart_id hit = pd.player_character.get_random_body_part();
                     pd.player_character.deal_damage( nullptr, hit, damage_instance( damage_bash, 6 ) );
                     pd.player_character.check_dead_state();
                 }
                 if( npc *const n = creatures.creature_at<npc>( newp ) ) {
                     // TODO: combine with player character code above
                     const bodypart_id hit = pd.player_character.get_random_body_part();
                     n->deal_damage( nullptr, hit, damage_instance( damage_bash, 6 ) );
                     add_msg_if_player_sees( newp, _( "A %1$s hits %2$s!" ), tmp.tname(), n->get_name() );
                     n->check_dead_state();
                 } else if( monster *const mon = creatures.creature_at<monster>( newp ) ) {
                     mon->apply_damage( nullptr, bodypart_id( "torso" ),
                                        6 - mon->get_armor_type( damage_bash, bodypart_id( "torso" ) ) );
                     add_msg_if_player_sees( newp, _( "A %1$s hits the %2$s!" ), tmp.tname(), mon->name() );
                     mon->check_dead_state();
                 }
             } else {
                 pushee++;
             }
         }
     }
 }
References _, map::add_item_or_charges(), add_msg(), add_msg_if_player_sees(), item_stack::begin(), Creature::check_dead_state(), creature_tracker::creature_at(), damage_bash, Character::deal_damage(), item_stack::end(), map_stack::erase(), fd_push_items, get_creature_tracker(), map::get_field(), Creature::get_random_body_part(), field_proc_data::here, map::i_at(), itype_rock, m_bad, field_proc_data::player_character, points_in_radius(), Creature::pos(), random_entry(), item::set_age(), and item::tname().
Referenced by map_field_processing::processors_for_type().
field_processor_fd_shock_vent()
static void field_processor_fd_shock_vent (const tripoint & p, field_entry & cur, field_proc_data & pd) static
Definition at line 828 of file map_field.cpp.
 {
     if( cur.get_field_intensity() > 1 ) {
         if( one_in( 5 ) ) {
             cur.set_field_intensity( cur.get_field_intensity() - 1 );
         }
     } else {
         cur.set_field_intensity( 3 );
         int num_bolts = rng( 3, 6 );
         for( int i = 0; i < num_bolts; i++ ) {
             point dir;
             while( dir == point_zero ) {
                 dir = { rng( -1, 1 ), rng( -1, 1 ) };
             }
             int dist = rng( 4, 12 );
             point bolt = p.xy();
             for( int n = 0; n < dist; n++ ) {
                 bolt += dir;
                 pd.here.add_field( tripoint( bolt, p.z ), fd_electricity, rng( 2, 3 ) );
                 if( one_in( 4 ) ) {
                     if( dir.x == 0 ) {
                         dir.x = rng( 0, 1 ) * 2 - 1;
                     } else {
                         dir.x = 0;
                     }
                 }
                 if( one_in( 4 ) ) {
                     if( dir.y == 0 ) {
                         dir.y = rng( 0, 1 ) * 2 - 1;
                     } else {
                         dir.y = 0;
                     }
                 }
             }
         }
     }
 }
References map::add_field(), fd_electricity, field_entry::get_field_intensity(), field_proc_data::here, one_in(), point_zero, rng(), field_entry::set_field_intensity(), point::x, tripoint::xy(), point::y, and tripoint::z.
Referenced by map_field_processing::processors_for_type().
field_processor_make_rubble()
static void field_processor_make_rubble (const tripoint & p, field_entry & , field_proc_data & pd) static
Definition at line 910 of file map_field.cpp.
 {
     // if( cur_fd_type.legacy_make_rubble )
     // Legacy Stuff
     pd.here.make_rubble( p );
 }
References field_proc_data::here, and map::make_rubble().
Referenced by map_field_processing::processors_for_type().
field_processor_monster_spawn()
static void field_processor_monster_spawn (const tripoint & p, field_entry & cur, field_proc_data & pd) static
Definition at line 754 of file map_field.cpp.
 {
     const field_intensity_level &int_level = cur.get_intensity_level();
     int monster_spawn_chance = int_level.monster_spawn_chance;
     int monster_spawn_count = int_level.monster_spawn_count;
     if( monster_spawn_count > 0 && monster_spawn_chance > 0 && one_in( monster_spawn_chance ) ) {
         for( ; monster_spawn_count > 0; monster_spawn_count-- ) {
             std::vector<MonsterGroupResult> spawn_details =
                 MonsterGroupManager::GetResultFromGroup( int_level.monster_spawn_group, &monster_spawn_count );
             for( const MonsterGroupResult &mgr : spawn_details ) {
                 if( !mgr.name ) {
                     continue;
                 }
                 if( const std::optional<tripoint> spawn_point =
                         random_point( points_in_radius( p, int_level.monster_spawn_radius ),
                 [&pd]( const tripoint & n ) {
                 return pd.here.passable( n );
                 } ) ) {
                     const tripoint_bub_ms pt = tripoint_bub_ms( spawn_point.value() );
                     pd.here.add_spawn( mgr, pt );
                 }
             }
         }
     }
 }
References map::add_spawn(), field_entry::get_intensity_level(), MonsterGroupManager::GetResultFromGroup(), field_proc_data::here, field_intensity_level::monster_spawn_chance, field_intensity_level::monster_spawn_count, field_intensity_level::monster_spawn_group, field_intensity_level::monster_spawn_radius, one_in(), points_in_radius(), and random_point().
Referenced by map_field_processing::processors_for_type().
field_processor_spread_gas()
void field_processor_spread_gas (const tripoint & p, field_entry & cur, field_proc_data & pd)
Definition at line 574 of file map_field.cpp.
 {
     // if( cur.gas_can_spread() )
     pd.here.spread_gas( cur, p, pd.cur_fd_type->percent_spread, pd.cur_fd_type->outdoor_age_speedup,
                         pd.sblk, pd.om_ter );
 }
Referenced by map_field_processing::processors_for_type().
field_processor_underwater_dissipation()
static void field_processor_underwater_dissipation (const tripoint & , field_entry & cur, field_proc_data & pd) static
Definition at line 513 of file map_field.cpp.
 {
     // Dissipate faster in water
     if( pd.map_tile.get_ter_t().has_flag( ter_furn_flag::TFLAG_SWIMMABLE ) ) {
         cur.mod_field_age( pd.cur_fd_type->underwater_age_speedup );
     }
 }
References field_proc_data::cur_fd_type, maptile_impl< Submap >::get_ter_t(), map_data_common_t::has_flag(), field_proc_data::map_tile, field_entry::mod_field_age(), TFLAG_SWIMMABLE, and field_type::underwater_age_speedup.
Referenced by map_field_processing::processors_for_type().
field_processor_upgrade_intensity()
static void field_processor_upgrade_intensity (const tripoint & , field_entry & cur, field_proc_data &) static
Definition at line 500 of file map_field.cpp.
 {
     // Upgrade field intensity
     const field_intensity_level &int_level = cur.get_intensity_level();
     if( int_level.intensity_upgrade_chance > 0 &&
         int_level.intensity_upgrade_duration > 0_turns &&
         calendar::once_every( int_level.intensity_upgrade_duration ) &&
         one_in( int_level.intensity_upgrade_chance ) ) {
         cur.mod_field_intensity( 1 );
     }
 }
References field_entry::get_intensity_level(), field_intensity_level::intensity_upgrade_chance, field_intensity_level::intensity_upgrade_duration, field_entry::mod_field_intensity(), calendar::once_every(), and one_in().
Referenced by map_field_processing::processors_for_type().
field_processor_wandering_field()
void field_processor_wandering_field (const tripoint & p, field_entry & cur, field_proc_data & pd)
Definition at line 604 of file map_field.cpp.
 {
     // Apply wandering fields from vents
     const field_type_id wandering_field_type_id = pd.cur_fd_type->wandering_field;
     for( const tripoint &pnt : points_in_radius( p, cur.get_field_intensity() - 1 ) ) {
         field &wandering_field = pd.here.get_field( pnt );
         field_entry *tmpfld = wandering_field.find_field( wandering_field_type_id );
         if( tmpfld && tmpfld->get_field_intensity() < cur.get_field_intensity() ) {
             pd.here.mod_field_intensity( pnt, wandering_field_type_id, 1 );
         } else {
             pd.here.add_field( pnt, wandering_field_type_id, cur.get_field_intensity() );
         }
     }
 }
Referenced by map_field_processing::processors_for_type().
ter_furn_has_flag()
bool ter_furn_has_flag (const ter_t & ter, const furn_t & furn, const ter_furn_flag flag)
Definition at line 184 of file map_field.cpp.
 {
     return ter.has_flag( flag ) || furn.has_flag( flag );
 }
References map_data_common_t::has_flag().
Referenced by MapExtras::burned_ground_parser(), and map::gas_can_spread_to().
ter_furn_movecost()
static int ter_furn_movecost (const ter_t & ter, const furn_t & furn) static
Definition at line 189 of file map_field.cpp.
 {
     if( ter.movecost == 0 ) {
         return 0;
     }
     if( furn.movecost < 0 ) {
         return 0;
     }
     return ter.movecost + furn.movecost;
 }
References map_data_common_t::movecost.
Referenced by map::gas_can_spread_to().
Variable Documentation
damage_acid
const damage_type_id damage_acid("acid") ("acid") static
Referenced by map::burn_body_part(), and map::monster_in_field().
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by field_processor_fd_push_items().
damage_electric
const damage_type_id damage_electric("electric") ("electric") static
Referenced by map::monster_in_field(), and map::player_in_field().
damage_heat
const damage_type_id damage_heat("heat") ("heat") static
Referenced by map::monster_in_field(), and map::player_in_field().
effect_badpoison
const efftype_id effect_badpoison("badpoison") ("badpoison") static
Referenced by map::player_in_field().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
Referenced by map::monster_in_field(), and map::player_in_field().
effect_corroding
const efftype_id effect_corroding("corroding") ("corroding") static
Referenced by map::burn_body_part().
effect_fungus
const efftype_id effect_fungus("fungus") ("fungus") static
Referenced by map::player_in_field().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by map::monster_in_field(), and map::player_in_field().
effect_poison
const efftype_id effect_poison("poison") ("poison") static
Referenced by map::player_in_field().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by map::monster_in_field().
effect_teargas
const efftype_id effect_teargas("teargas") ("teargas") static
Referenced by map::player_in_field().
furn_f_ash
const furn_str_id furn_f_ash("f_ash") ("f_ash") static
itype_rm13_armor_on
const itype_id itype_rm13_armor_on("rm13_armor_on") ("rm13_armor_on") static
Referenced by map::player_in_field().
itype_rock
const itype_id itype_rock("rock") ("rock") static
Referenced by field_processor_fd_push_items().
json_flag_HEATSINK
const json_character_flag json_flag_HEATSINK("HEATSINK") ("HEATSINK") static
Referenced by map::player_in_field().
json_flag_NO_UNLOAD
const flag_id json_flag_NO_UNLOAD("NO_UNLOAD") ("NO_UNLOAD") static
material_iflesh
const material_id material_iflesh("iflesh") ("iflesh") static
Referenced by map::monster_in_field().
material_veggy
const material_id material_veggy("veggy") ("veggy") static
Referenced by map::monster_in_field().
species_FUNGUS
const species_id species_FUNGUS("FUNGUS") ("FUNGUS") static
Referenced by map::monster_in_field().
ter_t_dirt
const ter_str_id ter_t_dirt("t_dirt") ("t_dirt") static
Referenced by field_processor_fd_fungicidal_gas().
ter_t_open_air
const ter_str_id ter_t_open_air("t_open_air") ("t_open_air") static
ter_t_pit
const ter_str_id ter_t_pit("t_pit") ("t_pit") static
ter_t_rock_floor
const ter_str_id ter_t_rock_floor("t_rock_floor") ("t_rock_floor") static
trait_ACIDPROOF
const trait_id trait_ACIDPROOF("ACIDPROOF") ("ACIDPROOF") static
Referenced by map::player_in_field().
trait_GASTROPOD_FOOT
const trait_id trait_GASTROPOD_FOOT("GASTROPOD_FOOT") ("GASTROPOD_FOOT") static
Referenced by map::player_in_field().
trait_M_IMMUNE
const trait_id trait_M_IMMUNE("M_IMMUNE") ("M_IMMUNE") static
Referenced by map::player_in_field().
trait_M_SKIN2
const trait_id trait_M_SKIN2("M_SKIN2") ("M_SKIN2") static
Referenced by map::player_in_field().
trait_M_SKIN3
const trait_id trait_M_SKIN3("M_SKIN3") ("M_SKIN3") static
Referenced by map::player_in_field().
trait_THRESH_INSECT
const trait_id trait_THRESH_INSECT("THRESH_INSECT") ("THRESH_INSECT") static
Referenced by map::player_in_field().
trait_THRESH_MARLOSS
const trait_id trait_THRESH_MARLOSS("THRESH_MARLOSS") ("THRESH_MARLOSS") static
Referenced by map::player_in_field().
trait_THRESH_MYCUS
const trait_id trait_THRESH_MYCUS("THRESH_MYCUS") ("THRESH_MYCUS") static
Referenced by map::player_in_field().
trait_THRESH_SPIDER
const trait_id trait_THRESH_SPIDER("THRESH_SPIDER") ("THRESH_SPIDER") static
Referenced by map::player_in_field().