Cataclysm DDA: src/map_iterator.h File Reference
map_iterator.h File Reference
#include <cstddef>
#include "enums.h"
#include "point.h"
#include "point_traits.h"
Classes
class tripoint_range< Tripoint >
class tripoint_range< Tripoint >::point_generator
Generates points in a rectangle.
struct tripoint_predicate_fun< T >
Macros
#define CATA_SRC_MAP_ITERATOR_H
Functions
template<typename Tripoint >
tripoint_range< Tripoint > points_in_radius (const Tripoint &center, const int radius, const int radiusz=0)
template<typename Tripoint >
tripoint_range< Tripoint > points_in_radius_circ (const Tripoint &center, const int radius, const int radiusz=0)
template<typename Tripoint >
tripoint_range< Tripoint > points_on_radius_circ (const Tripoint &center, const int radius, const int radiusz=0)
template<typename Tripoint >
tripoint_range< Tripoint > points_in_radius_where (const Tripoint &center, const int radius, const typename tripoint_predicate_fun< std::function< bool(const Tripoint &pt)>>::type &func, const int radiusz=0)
Macro Definition Documentation
CATA_SRC_MAP_ITERATOR_H
#define CATA_SRC_MAP_ITERATOR_H
Definition at line 3 of file map_iterator.h.
Function Documentation
points_in_radius()
template<typename Tripoint > tripoint_range<Tripoint> points_in_radius (const Tripoint & center, const int radius, const int radiusz = 0) inline
Definition at line 154 of file map_iterator.h.
 {
     static_assert( Tripoint::dimension == 3, "Requires tripoint type" );
     const tripoint offset( radius, radius, radiusz );
     return tripoint_range<Tripoint>( center - offset, center + offset );
 }
References center.
Referenced by computer_session::action_miss_launch(), timed_event::actualize(), behavior::monster_oracle_t::adjacent_plants(), Character::apply_persistent_morale(), board_up(), mattack::breathe(), overmap::build_slimepit(), can_construct(), vehicle::autodrive_controller::compute_profile(), fungal_effects::create_spores(), monster::die(), mattack::doot(), Character::echo_pulse(), enumerate_objects_around_point(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), conditional_fun::anonymous_namespace{condition.cpp}::f_near_om_location(), field_processor_fd_acid_vent(), field_processor_fd_electricity(), field_processor_fd_push_items(), field_processor_monster_spawn(), Character::forced_dismount(), mattack::fungus_sprout(), has_pre_terrain(), multicooker_hallu(), MapExtras::mx_city_trap(), npc::npc_dismount(), talk_function::om_building_region(), overmap::place_mongroups(), overmap::place_railroads(), map::place_vending(), sounds::process_sound_markers(), random_house_in_city(), game::safe_route_to(), overmap_ui::search(), spell_effect::spell_effect_blast(), map::spread_gas(), start_location::surround_with_monsters(), teleport::teleport_to_point(), activity_handlers::tree_communion_do_turn(), game::update_overmap_seen(), place_npc_iuse::use(), game::vertical_notes(), anonymous_namespace{debug_menu.cpp}::write_min_archive(), and mattack::zombie_fuse().
points_in_radius_circ()
template<typename Tripoint > tripoint_range<Tripoint> points_in_radius_circ (const Tripoint & center, const int radius, const int radiusz = 0) inline
Definition at line 163 of file map_iterator.h.
 {
     static_assert( Tripoint::dimension == 3, "Requires tripoint type" );
     const tripoint offset( radius, radius, radiusz );
     return tripoint_range<Tripoint>( center - offset,
     center + offset, [center, radius]( const Tripoint & pt ) {
         return trig_dist( center, pt ) < radius + 0.5f;
     } );
 }
References center, and trig_dist().
points_in_radius_where()
template<typename Tripoint > tripoint_range<Tripoint> points_in_radius_where (const Tripoint & center, const int radius, const typename tripoint_predicate_fun< std::function< bool(const Tripoint &pt)>>::type & func, const int radiusz = 0) inline
Definition at line 197 of file map_iterator.h.
 {
     static_assert( Tripoint::dimension == 3, "Requires tripoint type" );
     const tripoint offset( radius, radius, radiusz );
     return tripoint_range<Tripoint>( center - offset, center + offset, func );
 }
References center.
points_on_radius_circ()
template<typename Tripoint > tripoint_range<Tripoint> points_on_radius_circ (const Tripoint & center, const int radius, const int radiusz = 0) inline
Definition at line 175 of file map_iterator.h.
 {
     static_assert( Tripoint::dimension == 3, "Requires tripoint type" );
     const tripoint offset( radius, radius, radiusz );
     return tripoint_range<Tripoint>( center - offset,
     center + offset, [center, radius]( const Tripoint & pt ) {
         float r = trig_dist( center, pt );
         return radius - 0.5f < r && r < radius + 0.5f;
     } );
 }
References center, and trig_dist().
Referenced by om_range_mark().