Cataclysm DDA: src/map_memory.cpp File Reference
map_memory.cpp File Reference
#include "cata_assert.h"
#include "cached_options.h"
#include "cata_utility.h"
#include "coordinate_conversions.h"
#include "cuboid_rectangle.h"
#include "debug.h"
#include "filesystem.h"
#include "line.h"
#include "map_memory.h"
#include "path_info.h"
#include "string_formatter.h"
#include "translations.h"
Classes
struct reg_coord_pair
Helper class for converting global sm coord into global mm_region coord + sm coord within the region.
Macros
#define dbg(x) DebugLog((x),D_MMAP) << __FILE__ << ":" << __LINE__ << ": "
Functions
static cata_path find_mm_dir ()
static cata_path find_region_path (const cata_path &dirname, const tripoint &p)
Variables
static constexpr int MM_SIZE = MAPSIZE * 2
static mm_submap null_mz_submap
static mm_submap invalid_mz_submap { false }
static const tripoint_abs_sm invalid_cache_pos (tripoint_min)
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x),D_MMAP) << __FILE__ << ":" << __LINE__ << ": "
Definition at line 18 of file map_memory.cpp.
Function Documentation
find_mm_dir()
static cata_path find_mm_dir () static
Definition at line 20 of file map_memory.cpp.
 {
     return PATH_INFO::player_base_save_path_path() + ".mm1";
 }
References PATH_INFO::player_base_save_path_path().
Referenced by map_memory::load_submap(), and map_memory::save().
find_region_path()
static cata_path find_region_path (const cata_path & dirname, const tripoint & p) static
Definition at line 25 of file map_memory.cpp.
 {
     return dirname / string_format( "%d.%d.%d.mmr", p.x, p.y, p.z );
 }
References string_format(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by map_memory::load_submap(), and map_memory::save().
Variable Documentation
invalid_cache_pos
const tripoint_abs_sm invalid_cache_pos(tripoint_min) (tripoint_min) static
Referenced by map_memory::clear_cache(), and map_memory::is_valid().
invalid_mz_submap
mm_submap invalid_mz_submap { false } static
Definition at line 387 of file map_memory.cpp.
Referenced by map_memory::get_submap().
MM_SIZE
constexpr int MM_SIZE = MAPSIZE * 2 static constexpr
Definition at line 16 of file map_memory.cpp.
Referenced by map_memory::load(), and map_memory::save().
null_mz_submap
mm_submap null_mz_submap static
Definition at line 386 of file map_memory.cpp.
Referenced by map_memory::get_submap().