Cataclysm DDA: src/map.h File Reference
map.h File Reference
#include <array>
#include <bitset>
#include <climits>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <iosfwd>
#include <list>
#include <map>
#include <memory>
#include <new>
#include <optional>
#include <set>
#include <tuple>
#include <utility>
#include <variant>
#include <vector>
#include "calendar.h"
#include "cata_assert.h"
#include "cata_type_traits.h"
#include "cata_utility.h"
#include "colony.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "creature.h"
#include "enums.h"
#include "game_constants.h"
#include "item.h"
#include "item_stack.h"
#include "level_cache.h"
#include "lightmap.h"
#include "line.h"
#include "lru_cache.h"
#include "map_selector.h"
#include "mapdata.h"
#include "maptile_fwd.h"
#include "point.h"
#include "rng.h"
#include "type_id.h"
#include "units.h"
#include "value_ptr.h"
Classes
struct wrapped_vehicle
class map_stack
struct visibility_variables
struct bash_params
struct drawsq_params
Draw parameters used by map::drawsq() and similar methods.
struct tile_render_info
struct tile_render_info::common
struct tile_render_info::vision_effect
struct tile_render_info::sprite
class map
Manage and cache data about a part of the map.
struct map::apparent_light_info
class tinymap
Tinymap is a small version of the map which covers a single overmap terrain (OMT) tile, which corresponds to 2 * 2 submaps, or 24 * 24 map tiles.
class fake_map
class smallmap
Smallmap is similar to tinymap in that it covers a single overmap terrain (OMT) tile, but differs from it in that it covers all Z levels, not just a single one.
Namespaces
catacurses
Contains the curses interface used by the whole game.
Macros
#define CATA_SRC_MAP_H
Typedefs
using VehicleList = std::vector< wrapped_vehicle >
using relic_procgen_id = string_id< relic_procgen_data >
Functions
map & get_map ()
template<int SIZE, int MULTIPLIER>
void shift_bitset_cache (std::bitset< SIZE *SIZE > &cache, const point &s)
bool ter_furn_has_flag (const ter_t &ter, const furn_t &furn, ter_furn_flag flag)
bool generate_uniform (const tripoint_abs_sm &p, const oter_id &oter)
bool generate_uniform_omt (const tripoint_abs_sm &p, const oter_id &terrain_type)
Macro Definition Documentation
CATA_SRC_MAP_H
#define CATA_SRC_MAP_H
Definition at line 3 of file map.h.
Typedef Documentation
relic_procgen_id
using relic_procgen_id = string_id<relic_procgen_data>
Definition at line 104 of file map.h.
VehicleList
using VehicleList = std::vector<wrapped_vehicle>
Definition at line 94 of file map.h.
Function Documentation
generate_uniform()
bool generate_uniform (const tripoint_abs_sm & p, const oter_id & oter)
Definition at line 8176 of file map.cpp.
 {
     std::unique_ptr<submap> sm = std::make_unique<submap>();
     if( oter == oter_open_air ) {
         sm->set_all_ter( ter_t_open_air, true );
     } else if( oter == oter_empty_rock || oter == oter_deep_rock ) {
         sm->set_all_ter( ter_t_rock, true );
     } else if( oter == oter_solid_earth ) {
         sm->set_all_ter( ter_t_soil, true );
     } else {
         return false;
     }
     sm->last_touched = calendar::turn;
     return MAPBUFFER.add_submap( p, sm );
 }
References mapbuffer::add_submap(), MAPBUFFER, oter_deep_rock, oter_empty_rock, oter_open_air, oter_solid_earth, coords::sm, ter_t_open_air, ter_t_rock, ter_t_soil, and calendar::turn.
Referenced by generate_uniform_omt().
generate_uniform_omt()
bool generate_uniform_omt (const tripoint_abs_sm & p, const oter_id & terrain_type)
Definition at line 8192 of file map.cpp.
 {
     dbg( D_INFO ) << "generate_uniform p: " << p
                   << "  terrain_type: " << terrain_type.id().str();
     bool ret = true;
     for( int xd = 0; xd <= 1; xd++ ) {
         for( int yd = 0; yd <= 1; yd++ ) {
             ret &= generate_uniform( p + point( xd, yd ), terrain_type );
         }
     }
     return ret;
 }
References D_INFO, dbg, generate_uniform(), int_id< T >::id(), cata::hash64_detail::ret, and string_id< T >::str().
Referenced by map::loadn(), and mapbuffer::unserialize_submaps().
get_map()
map& get_map ()
Definition at line 150 of file game.cpp.
 {
     return g->m;
 }
Referenced by anonymous_namespace{iexamine.cpp}::_choose_elevator_destz(), anonymous_namespace{iexamine.cpp}::_get_vehicles_on_elevator(), explosion_handler::_make_explosion(), anonymous_namespace{item.cpp}::_stacks_location_hint(), basecamp::abandon_camp(), Character::absorb_hit(), mattack::absorb_items(), mattack::absorb_meat(), mattack::acid(), mattack::acid_barf(), iuse::acidbomb_act(), vehicle::act_on_map(), computer_session::action_amigara_log(), computer_session::action_blood_anal(), computer_session::action_cascade(), computer_session::action_close_gate(), computer_session::action_conveyor(), computer_session::action_data_anal(), computer_session::action_deactivate_shock_vent(), computer_session::action_elevator_on(), computer_session::action_extract_rad_source(), computer_session::action_geiger(), computer_session::action_irradiator(), computer_session::action_list_bionics(), computer_session::action_lock(), computer_session::action_miss_launch(), computer_session::action_open(), computer_session::action_open_gate(), computer_session::action_portal(), computer_session::action_release(), computer_session::action_release_bionics(), computer_session::action_research(), computer_session::action_sample(), computer_session::action_shutters(), computer_session::action_srcf_elevator(), computer_session::action_srcf_seal(), computer_session::action_terminate(), computer_session::action_unlock(), Character::activate_bionic(), Character::activate_mutation(), enchant_cache::activate_passive(), activity_on_turn_move_loot(), timed_event::actualize(), zone_manager::add(), inventory_selector::add_basecamp_items(), add_basecamp_storage_to_loot_zone_list(), add_fallback_zone(), map::add_field(), map::add_item(), DefaultRemovePartHandler::add_item_or_charges(), advanced_inventory_pane::add_items_from_area(), Character::add_known_trap(), inventory_selector::add_map_items(), construct::add_matching_down_above(), inventory_selector::add_nearby_items(), construct::add_roof(), spell_effect::add_trap(), inventory_selector::add_vehicle_items(), map::add_vehicle_to_map(), behavior::monster_oracle_t::adjacent_plants(), Character::adjacent_tile(), vehicle::advance_precalc_mounts(), iuse::afs_translocator(), iexamine::aggie_plant(), anonymous_namespace{activity_item_handling.cpp}::already_done(), npc::alt_attack(), item::ammo_consume(), item_contents::ammo_consume(), item::ammo_remaining(), jmapgen_remove_npcs::apply(), jmapgen_npc::apply(), jmapgen_vehicle::apply(), jmapgen_remove_vehicles::apply(), jmapgen_remove_all::apply(), cardreader_examine_actor::apply(), apply< furn_t >(), apply< ter_t >(), apply< trap >(), apply_ammo_effects(), iexamine::arcfurnace_empty(), iexamine::arcfurnace_full(), are_requirements_nearby(), npc::assess_danger(), assign_veh_to_follow(), Creature::attack_air(), monster::attack_at(), Creature::auto_find_hostile_target(), iexamine::autoclave_empty(), iexamine::autoclave_full(), iexamine::autodoc(), Pickup::autopickup(), vehicle::autopilot_patrol(), iexamine::bars(), Character::base_comfort_value(), spell_effect::bash(), monster::bash_at(), trapfunc::beartrap(), mattack::bio_op_disarm(), Character::bionics_install_failure(), Creature::bleed(), iuse::blood_draw(), Character::blossoms(), iuse::boltcutters(), trapfunc::boobytrap(), mattack::boomer(), mattack::boomer_glow(), vehicle::break_off(), iuse::break_stick(), mattack::breathe(), mdeath::broken(), mattack::browse(), trapfunc::bubble(), activity_handlers::build_do_turn(), vehicle::build_interact_menu(), iexamine::bulletin_board(), Character::burn_fuel(), Character::burn_move_stamina(), butcher_corpse_activity(), butcher_dissect_item(), activity_handlers::butcher_finish(), butchery_drops_harvest(), butchery_quarter(), zone_manager::cache_vzones(), monster::calc_climb_cost(), monster::calc_movecost(), calculate_spell_effect_area(), appliance_convert_examine_actor::call(), cardreader_examine_actor::call(), eoc_examine_actor::call(), leap_actor::call(), melee_actor::call(), gun_actor::call(), iuse::call_of_tindalos(), trapfunc::caltrops_glass(), iuse::camera(), computer_session::can_activate(), can_butcher_at(), can_construct(), can_do_activity_there(), can_examine_at(), iexamine::can_fertilize(), iuse::can_goo(), can_interact_at(), Character::can_mount(), npc::can_move_to(), can_move_vertical_at(), npc::can_open_door(), can_pickup_at(), monster::can_reach_to(), can_recharge_lunar(), can_recharge_solar(), vehicle::can_use_rails(), cancel_pickup(), tent_placement_activity_actor::canceled(), vehicle_unfolding_activity_actor::canceled(), iexamine::cardreader_foodplace(), iexamine::cardreader_robofac(), trapfunc::cast_spell(), Character::cast_spell(), iexamine::chainfence(), advanced_inventory::change_square(), character_push_effects(), construct::check_channel(), construct::check_deconstruct(), check_deploy_square(), construct::check_down_OK(), vehicle::autodrive_controller::check_drivable(), Character::check_eligible_containers_for_crafting(), construct::check_empty(), construct::check_empty_lite(), vehicle::check_falling_or_floating(), vehicle::check_heli_ascend(), vehicle::check_heli_descend(), deploy_tent_actor::check_intact(), vehicle::check_is_heli_landed(), construct::check_matching_down_above(), mattack::check_money_left(), construct::check_no_trap(), construct::check_no_wiring(), construct::check_nofloor_above(), Character::check_outbounds_activity(), construct::check_ramp_high(), Character::check_read_condition(), construct::check_single_support(), construct::check_stable(), construct::check_support(), construct::check_support_below(), construct::check_up_OK(), choose_adjacent_highlight(), target_ui::choose_initial_target(), iuse::chop_logs(), chop_plank_activity(), chop_single_do_turn(), iuse::chop_tree(), chop_tree_activity(), cleanup_tiles(), mapbuffer::clear_outside_reality_bubble(), iexamine::clear_overgrown(), clear_shot_reach(), Character::climate_control_strength(), Character::climbing_cost(), close(), vehicle::collision(), colorized_feature_description_at(), colorized_field_description_at(), display::colorized_overmap_text(), colorized_ter_name_flags_at(), colorized_trap_name_at(), talk_function::companion_return(), complete_construction(), veh_interact::complete_vehicle(), iexamine::compost_empty(), iexamine::compost_full(), compost_set_empty(), compost_set_full(), vehicle::autodrive_controller::compute_obstacles(), vehicle::connect(), construction_activity(), Character::consume_charges(), Character::consume_items(), consume_items_in_zones(), Character::consume_tools(), Character::consume_ups(), craft_command::continue_prompt_liquids(), iexamine::controls_gate(), npc::could_move_onto(), vehicle::crash_terrain_around(), spell::create_field(), fungal_effects::create_spores(), zone_manager::create_vehicle_loot_zone(), creature_tracker::creature_at(), trapfunc::crossbow(), iuse::crowbar(), Character::crush_frozen_liquid(), iexamine::curtains(), iuse::cut_log_into_planks(), salvage_actor::cut_up(), cyborg_on_couch(), cycle_action(), vehicle::damage_all(), vehicle::damage_direct(), damage_targets(), spell_effect::dash(), iuse::dbg_lux_meter(), debug_menu::debug(), debug_menu::debug_menu_game_state(), debug_menu::debug_menu_spawn_vehicle(), vehicle::decrement_summon_timer(), mattack::depart(), iexamine::deployed_furniture(), item_location::impl::item_on_map::describe(), item_location::deserialize(), climbing_aid::detect_conditions(), monster::die(), npc::die(), dig_tool(), spell_effect::directed_push(), iuse::directional_antenna(), iexamine::dirtmound(), avatar::disarm(), Character::disassemble_all(), displace_items_except_one_liquid(), overmap_ui::display(), veh_interact::display_veh(), basecamp::distribute_food(), distribute_items_to_npc_zones(), explosion_handler::do_blast(), vehicle::do_engine_damage(), vehicle::do_environmental_effects(), melee_actor::do_grab(), vehicle::do_remove_part_actual(), vehicle::do_towing_move(), hotwire_car_activity_actor::do_turn(), milk_activity_actor::do_turn(), hacksaw_activity_actor::do_turn(), aim_activity_actor::do_turn(), move_items_activity_actor::do_turn(), glide_activity_actor::do_turn(), unload_loot_activity_actor::do_turn(), construct::do_turn_shovel(), mattack::dogthing(), construct::done_appliance(), construct::done_deconstruct(), construct::done_dig_grave(), construct::done_dig_grave_nospawn(), construct::done_digormine_stair(), construct::done_extract_maybe_revert_to_dirt(), construct::done_grave(), construct::done_mark_firewood(), construct::done_mark_practice_target(), construct::done_mine_upstair(), construct::done_ramp_high(), construct::done_ramp_low(), construct::done_vehicle(), construct::done_window_curtains(), construct::done_wiring(), construct::done_wood_stairs(), iexamine::door_peephole(), mattack::doot(), editmap_hilight::draw(), anonymous_namespace{animation.cpp}::draw_line_curses(), editmap::draw_main_ui_overlay(), advanced_inventory::draw_minimap(), overmap_ui::draw_om_sidebar(), overmap_ui::draw_overmap_chunk(), target_ui::draw_terrain_overlay(), draw_throw_aim(), vehicle::drive_to_local_target(), Character::drop(), Character::drop_invalid_inventory(), monster::drop_items_on_death(), drop_on_map(), drop_or_embed_projectile(), talk_function::drop_stolen_item(), talk_function::drop_weapon(), anonymous_namespace{monexamine.cpp}::dump_items(), mattack::eat_carrion(), mattack::eat_crop(), mattack::eat_food(), avatar_action::eat_here(), Character::echo_pulse(), editmap::edit_fld(), editmap::edit_itm(), editmap::edit_mapgen(), eff_fun_fungus(), eff_fun_sleep(), eff_fun_teleglow(), iuse::ehandcuffs_tick(), iexamine::elevator(), iuse::emf_passive_on(), spell_effect::emit(), explosion_handler::emp_blast(), empty_autopickup_target(), enumerate_objects_around_point(), Character::env_surgery_bonus(), Character::evaluate_techniques(), trap::examine(), npc::execute_action(), explosion_handler::explosion(), iuse::extinguisher(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate(), conditional_fun::anonymous_namespace{condition.cpp}::f_can_see_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_driving(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_in_field(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_on_terrain(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_on_terrain_with_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_underwater(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_id(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_with_flag(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), computer_session::failure_amigara(), computer_session::failure_destroy_blood(), computer_session::failure_destroy_data(), computer_session::failure_manhacks(), computer_session::failure_pump_explode(), computer_session::failure_pump_leak(), computer_session::failure_secubots(), computer_session::failure_shutdown(), climbing_aid::fall_scan::fall_scan(), iexamine::false_and_debugmsg(), farm_action(), feature< furn_id >(), feature< ter_id >(), feature< trap_id >(), iexamine::fertilize_plant(), fetch_activity(), anonymous_namespace{math_parser_diag.cpp}::field_strength_eval(), fill_funnels(), activity_handlers::fill_liquid_do_turn(), find_best_fire(), find_closest_stair(), npc::find_corpse_to_pulp(), npc::find_dangerous_explosives(), find_empty_neighbors(), npc::find_item(), find_refuel_spot_zone(), melee_actor::find_target(), vehicle::find_vehicle(), vehicle::find_vehicles_to_rack(), Character::fine_detail_vision_mod(), bikerack_racking_activity_actor::finish(), bikerack_unracking_activity_actor::finish(), tent_deconstruct_activity_actor::finish(), tent_placement_activity_actor::finish(), hacksaw_activity_actor::finish(), hacking_activity_actor::finish(), hotwire_car_activity_actor::finish(), boltcutting_activity_actor::finish(), lockpick_activity_actor::finish(), safecracking_activity_actor::finish(), harvest_activity_actor::finish(), reload_activity_actor::finish(), milk_activity_actor::finish(), shearing_activity_actor::finish(), oxytorch_activity_actor::finish(), chop_logs_activity_actor::finish(), chop_planks_activity_actor::finish(), chop_tree_activity_actor::finish(), churn_activity_actor::finish(), clear_rubble_activity_actor::finish(), disable_activity_actor::finish(), forage_activity_actor::finish(), longsalvage_activity_actor::finish(), mop_activity_actor::finish(), iexamine::finite_water_source(), fire(), Character::fire_gun(), iexamine::fireplace(), iuse::fish_trap(), iuse::fish_trap_tick(), iuse::fishing_rod(), mattack::flame(), explosion_handler::flashbang(), mattack::flesh_tendril(), creature_tracker::flood_fill_zone(), Character::floor_bedding_warmth(), Character::floor_item_warmth(), iexamine::flower_cactus(), iexamine::flower_dahlia(), iexamine::flower_marloss(), iexamine::flower_poppy(), foamcrete_build(), vehicle_folding_activity_actor::fold_vehicle(), npc::follow_distance(), Character::forced_dismount(), basecamp::form_crafting_inventory(), inventory::form_from_map(), form_loc(), basecamp::form_storage_zones(), advanced_inventory_pane::free_volume(), suffer::from_artifact_resonance(), suffer::from_asthma(), suffer::from_nyctophobia(), suffer::from_other_mutations(), suffer::from_radiation(), fromPumpFuel(), iexamine::fswitch(), vehicle::fuel_left(), iuse::fungicide(), iexamine::fungus(), mattack::fungus(), mattack::fungus_big_blossom(), mattack::fungus_corporate(), mattack::fungus_fortify(), mattack::fungus_haze(), mattack::fungus_sprout(), iexamine::fvat_empty(), iexamine::fvat_full(), fvat_set_empty(), fvat_set_full(), iuse::gasmask(), iexamine::gaspump(), iuse::geiger(), iuse::geiger_active(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), generic_multi_activity_handler(), generic_multi_activity_locations(), get_auto_consume_moves(), get_basecamp(), get_best_fire(), zone_manager::get_bottom_zone(), Character::get_cable_vehicle(), basecamp::get_camp_map(), cardreader_examine_actor::get_cards(), get_convection_temperature(), input_context::get_coordinates(), Character::get_crafting_group(), Character::get_crafting_helpers(), comestible_inventory_preset::get_denial(), Character::get_eligible_containers_for_crafting(), anonymous_namespace{gates.cpp}::get_gate_id(), get_get_str_(), get_hack_type(), get_heat_radiation(), advanced_inv_area::get_item_count(), get_item_location(), get_keg_capacity(), liquid_handler::get_liquid_target(), get_local_windpower(), DefaultRemovePartHandler::get_map_ref(), get_memory_at(), zone_manager::get_near_zones(), overmap_ui::get_overmap_path_to(), monster::get_path_avoid(), npc::get_path_avoid(), zone_manager::get_point_set_loot(), player_activity::get_progress_message(), vehicle::get_remote_part(), Character::get_targetable_creatures(), weather_manager::get_temperature(), get_top_item_at_point(), get_tripoint_from_var(), scent_map::get_unsafe(), zone_manager::get_zone_at(), get_zone_for_act(), zone_manager::get_zones(), zone_manager::get_zones_at(), iexamine::getGasPumpByNumber(), iexamine::getNearFilledGasTank(), getNearPumpCount(), trapfunc::glass(), talker_furniture::global_pos(), talker_item_const::global_pos(), vehicle::global_square_location(), npc::go_to_omt_destination(), trapfunc::goo(), npc::good_escape_direction(), good_fishing_spot(), grab(), avatar::grab(), iuse::granade_act(), Character::gravity_check(), mattack::graze(), iuse::grenade_inc_act(), mattack::growplants(), iuse::hacksaw(), handbrake(), handle_action_menu(), Character::handle_contents_changed(), iuse::handle_ground_graffiti(), Character::handle_gun_overheat(), iexamine_helper::handle_harvest(), liquid_handler::handle_liquid_from_ground(), Character::handle_melee_wear(), prying_activity_actor::handle_prying(), prying_activity_actor::handle_prying_nails(), npc::handle_sound(), vehicle::handle_trap(), handle_weather_effects(), vehicle::handling_difficulty(), Character::hardcoded_effects(), iexamine::harvest_plant(), iexamine::harvest_plant_ex(), iexamine::harvestable_now(), Character::has_alarm_clock(), has_clear_path_to_pickup_items(), Character::has_destination_activity(), Character::has_fire(), has_neighbor(), has_obstruction(), has_pre_terrain(), has_vehicle_control(), has_vine_parent(), Character::has_watch(), haul(), monster::hear_sound(), Character::heat_emission(), iuse::heat_food(), heat_item(), iuse::honeycomb(), Character::i_add(), Character::i_add_or_drop(), Character::i_add_or_fill(), Character::i_drop_at(), vehicle::idle(), vehicle::immediate_path(), Character::impact(), monster::impact(), in_spell_aoe(), scent_map::inbounds(), talk_function::individual_mission(), advanced_inv_area::init(), weldrig_hack::init(), exosuit_interact::insert_replace_activate_mod(), vehicle::interact_with(), iexamine::invalid(), vehicle::invalidate_towing(), item::io(), Creature::is_adjacent(), place_trap_actor::is_allowed(), monster::is_aquatic_danger(), mission::is_complete(), is_creature_outside(), Character::is_deaf(), Character::is_driving(), vehicle::is_external_part(), Creature::is_likely_underwater(), is_obstacle(), pickup_inventory_preset::is_shown(), select_ammo_inventory_preset::is_shown(), Character::is_snuggling(), is_solid_neighbor(), anonymous_namespace{gates.cpp}::gate_data::is_suitable_wall(), ma_requirements::is_valid_character(), is_wind_blocker(), behavior::monster_oracle_t::items_available(), activity_handlers::jackhammer_do_turn(), activity_handlers::jackhammer_finish(), mattack::kamikaze(), iexamine::keg(), debug_menu::kill_area(), iexamine::kiln_empty(), iexamine::kiln_full(), Character::knock_back_to(), monster::knock_back_to(), monster::know_danger_at(), Character::knows_trap(), trapfunc::landmine(), trapfunc::lava(), vehicle::leak_fuel(), Character::leak_items(), iexamine::ledge(), trapfunc::ledge(), vehicle::level_vehicle(), link_up_actor::link_extend_cable(), item::link_to(), link_up_actor::link_to_veh_app(), link_up_actor::link_tow_cable(), avatar::load(), monster::load(), map::load(), avatar::load_map_memory(), advanced_inventory_pane::load_settings(), map::loadn(), anonymous_namespace{item_tname.cpp}::location_hint(), iexamine::locked_object(), iexamine::locked_object_pickable(), Creature::longpull(), iuse::lumber(), iuse::mace(), item_location::make_active(), map::make_active(), make_mon_corpse(), iuse::makemound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::map_add_item(), debug_menu::map_extra(), trapfunc::map_regen(), map_selector::map_selector(), editmap::mapgen_preview(), editmap::mapgen_retarget(), editmap::mapgen_veh_destroy(), marloss_common(), fungal_effects::marlossify(), vehicle::merge_appliance_into_grid(), vehicle::merge_rackable_vehicle(), vehicle::merge_vehicle_parts(), iuse::meth(), anonymous_namespace{monexamine.cpp}::milk_source(), mill_activate(), iexamine::mill_finalize(), mill_load_food(), mine_activity(), Character::modify_morale(), iuse::molotov_lit(), anonymous_namespace{do_turn.cpp}::monmove(), monster::monster_move_in_vehicle(), iuse::mop(), mop_activity(), monster::move(), npc::move(), avatar_action::move(), npc::move_away_from(), activity_handlers::move_cost(), veh_interact::move_cursor(), monster::move_effects(), Character::move_in_vehicle(), move_item(), monster::move_to(), npc::move_to(), move_to_parent_pocket_recursive(), firestarter_actor::moves_cost_by_fuel(), multicooker_hallu(), iuse::mycus(), iexamine::nanofab(), nearest_passable(), vehicle::no_towing_slack(), iexamine::none(), npc::npc_dismount(), mattack::nurse_assist(), mattack::nurse_check_up(), mattack::nurse_operate(), monster::nursebot_operate(), item::on_drop(), Character::on_hit(), monster::on_hit(), npc::on_load(), Character::on_move(), iexamine::on_smoke_out(), open(), gates::open_gate(), vehicle::open_or_close(), iexamine::open_safe(), vehicle::operate_planter(), vehicle::operate_reaper(), vehicle::operate_scoop(), activity_handlers::operation_do_turn(), activity_handlers::operation_finish(), operator_present(), Character::overmap_sight_range(), iuse::oxytorch(), parse_tags(), vehicle::part_collision(), iexamine::part_con(), vehicle::part_removal_cleanup(), Character::pause(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), timed_event::per_turn(), tutorial_game::per_turn(), Character::perform_install(), liquid_handler::perform_liquid_transfer(), Character::perform_technique(), Character::perform_uninstall(), perform_zone_activity_turn(), photo_def_for_camera_point(), iuse::pick_lock(), pick_plant(), npc::pick_up_item(), npc::pick_up_item_map(), activity_handlers::pickaxe_do_turn(), activity_handlers::pickaxe_finish(), pickveh(), iexamine::pit(), iexamine::pit_covered(), pit_effectiveness(), trapfunc::pit_glass(), trapfunc::pit_spikes(), map::pl_sees(), place_and_add_as_known(), place_appliance(), place_construction(), Character::place_corpse(), place_craft_or_disassembly(), start_location::place_player(), monster::plan(), mattack::plant(), iexamine::plant_seed(), activity_handlers::plant_seed_finish(), vehicle::player_in_control(), player_on_couch(), pldrive(), points_for_gas_cloud(), veh_app_interact::populate_app_actions(), iexamine::portable_structure(), iuse::portal(), Creature::pos(), map_cursor::pos(), Creature::pos_bub(), iexamine::pour_into_keg(), vehicle::precalculate_vehicle_turning(), firestarter_actor::prep_firestarter_use(), advanced_inventory::print_items(), Character::process_effects(), monster::process_effects(), explosion_handler::process_explosions(), Character::process_items(), sounds::process_sound_markers(), sounds::process_sounds(), monster::process_triggers(), monster::process_turn(), projectile_attack(), activity_handlers::pull_creature_finish(), mattack::pull_metal_weapon(), activity_handlers::pulp_do_turn(), monster::push_to(), put_into_vehicle(), put_into_vehicle_or_drop(), iexamine::quern_examine(), veh_menu::query(), query_pick(), plot_options::query_seed(), map::queue_main_cleanup(), iuse::radiocontrol(), rcdrive(), Character::reach_attack(), npc::reach_omt_destination(), avatar::rebuild_aim_cache(), target_ui::recalc_aim_turning_penalty(), Character::recalc_sight_limits(), editmap::recalc_target(), spell_effect::recharge_vehicle(), Character::recoil_vehicle(), veh_app_interact::refill(), vehicle::refresh_zones(), npc::regen_ai_cache(), reload_furniture(), veh_app_interact::remove(), zone_manager::remove(), construct::remove_above(), anonymous_namespace{monexamine.cpp}::remove_armor(), anonymous_namespace{monexamine.cpp}::remove_bag_from(), anonymous_namespace{monexamine.cpp}::remove_battery(), vehicle::remove_carried_vehicle(), link_up_actor::remove_extensions(), vehicle::remove_remote_part(), remove_submap_turrets(), map::remove_trap(), DefaultRemovePartHandler::removed(), veh_utils::repair_part(), requirements_map(), firestarter_actor::resolve_firestarter_use(), explosion_handler::resonance_cascade(), Character::rest_quality(), aim_activity_actor::restore_view(), mattack::resurrect(), zone_manager::revert_vzones(), spell_effect::revive(), spell_effect::revive_dormant(), mattack::riotbot(), rod_fish(), Character::rooted(), Character::rooted_message(), map::rotate(), map::route(), route_adjacent(), route_best_workbench(), iexamine::rubble(), target_ui::run(), area_expander::run(), Character::run_cost_effects(), inventory::rust_iron_items(), iexamine::safe(), sane_consume_items(), mapbuffer::save(), avatar::save_map_memory(), npc::saw_player_recently(), scatter_chunks(), monster::scent_move(), mattack::science(), Character::search_surroundings(), mattack::searchlight(), npc::see_item_say_smth(), Creature::sees(), Character::sees(), npc::sees_dangerous_field(), Character::sees_with_infrared(), lockpick_activity_actor::select_location(), sendRadioSignal(), vehicle::separate_from_grid(), veh_interact::serialize_activity(), serialize_liquid_source(), debug_menu::set_automove(), advanced_inv_area::set_container_position(), target_ui::set_cursor_pos(), Character::set_destination(), DefaultRemovePartHandler::set_floor_cache_dirty(), set_item_map(), set_item_map_or_vehicle(), target_ui::set_last_target(), avatar::set_movement_mode(), Creature::set_pos_only(), DefaultRemovePartHandler::set_transparency_cache_dirty(), target_ui::set_view_offset(), editmap::setup_fmenu(), trapfunc::shadow(), vehicle::shed_loose_parts(), mattack::shockstorm(), trapfunc::shotgun(), monster::shove_vehicle(), live_view::show(), explosion_handler::shrapnel(), mattack::shriek_stun(), iexamine::shrub_marloss(), iexamine::shrub_wildveggies(), Character::sight_impaired(), Character::sight_range(), iexamine::sign(), trapfunc::sinkhole(), sinkhole_safety_roll(), iuse::siphon(), sleep(), Character::sleep_spot(), vehicle::slow_leak(), vehicle::smart_controller_handle_turn(), smash(), vehicle::smash(), vehicle::smash_security_system(), smoker_activate(), smoker_finalize(), smoker_load_food(), iexamine::smoker_options(), trapfunc::snake(), trapfunc::snare_heavy(), trapfunc::snare_light(), debug_menu::spawn_artifact(), monster::spawn_dissectables_on_death(), map::spawn_monsters_submap(), map::spawn_monsters_submap_group(), debug_menu::spawn_nested_mapgen(), spawn_spores(), spell_effect::spawn_summoned_vehicle(), spell_effect::spell_effect_blast(), spell_effect_cone_range_override(), spell_move(), spell_remove_field(), activity_handlers::spellcasting_finish(), vehicle::spew_field(), item_pocket::spill_contents(), mdeath::splatter(), Character::spores(), fungal_effects::spread_fungus(), fungal_effects::spread_fungus_one_tile(), Character::stagger(), harvest_activity_actor::start(), boltcutting_activity_actor::start(), vehicle_folding_activity_actor::start(), hacksaw_activity_actor::start(), workout_activity_actor::start(), oxytorch_activity_actor::start(), prying_activity_actor::start(), activity_handlers::start_engines_finish(), activity_handlers::start_fire_do_turn(), activity_handlers::start_fire_finish(), stash_on_pet(), vehicle::static_drag(), sting_get_target(), iexamine::stook_empty(), iexamine::stook_full(), vehicle::stop(), npc::stow_item(), mattack::stretch_attack(), monster::stumble(), Creature::stumble_invis(), swap_pos(), Character::symbol_color(), Target_attributes::Target_attributes(), spell::targetable_locations(), npc_attack_melee::targetable_points(), npc_attack_gun::targetable_points(), npc_attack_throw::targetable_points(), teleport::teleport(), teleport::teleport_to_point(), tell_magic_veh_stop_following(), tell_magic_veh_to_follow(), tell_veh_stop_following(), trapfunc::temple_flood(), trapfunc::temple_toggle(), terrain_collision_data(), test_passable(), vehicle::thrust(), tidy_activity(), mattack::tindalos_teleport(), auto_navigation_data::to_view(), Character::toggle_hauling(), iexamine::toPumpFuel(), vehicle::total_solar_epower(), vehicle::total_water_wheel_epower(), vehicle::total_wind_epower(), vehicle::tow_cable_too_far(), spell_effect::transform_blast(), vehicle::transform_terrain(), iexamine::translocator(), activity_handlers::travel_do_turn(), iexamine::tree_hickory(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), iexamine::tree_marloss(), mattack::triffid_heartbeat(), trapfunc::tripwire(), monster::try_biosignature(), try_fuel_fire(), target_ui::try_reacquire_target(), Character::try_remove_grab(), Character::try_remove_heavysnare(), monster::try_reproduce(), iexamine::try_start_hacking(), avatar::try_to_sleep(), turnOnSelectedPump(), monster::turns_to_reach(), editmap::uber_draw_ter(), DefaultRemovePartHandler::unboard(), vehicle::unboard_all(), Character::uncanny_dodge(), vehicle_unfolding_activity_actor::unfold_vehicle(), Character::uninstall_bionic(), unroll_digging(), Character::update_bodytemp(), update_lum(), update_mapgen_function_json::update_map(), npc::update_path(), map::update_pathfinding_cache(), autodrive_activity_actor::update_player_vehicle(), target_ui::update_status(), vehicle::update_time(), editmap::update_view_with_help(), weather_manager::update_weather(), explosion_iuse::use(), consume_drug_iuse::use(), place_npc_iuse::use(), deploy_furn_actor::use(), firestarter_actor::use(), fireweapon_on_actor::use(), place_trap_actor::use(), emit_actor::use(), deploy_tent_actor::use(), unpack_actor::use(), link_up_actor::use(), item_stack::use_charges(), Character::use_charges(), Character::use_fire(), Character::valid_aoe_technique(), basecamp::validate_sort_points(), vehicle_activity(), debug_menu::vehicle_battery_charge(), npc::vehicle_danger(), display::vehicle_driven(), debug_menu::vehicle_export(), activity_handlers::vehicle_finish(), vehicle_selector::vehicle_selector(), iexamine::vending(), mattack::vine(), iuse::voltmeter(), item_location::impl::item_on_map::volume_capacity(), Character::vomit(), wait(), map::water_from(), iexamine::water_source(), weather_sound(), iuse::weather_tool(), suffer::while_grabbed(), suffer::while_underwater(), monster::will_join_horde(), monster::will_move_to(), monster::will_reach(), debug_menu::wishitem(), iexamine::workbench(), Character::workbench_crafting_speed_multiplier(), iexamine::workbench_internal(), npc::worker_downtime(), iexamine::workout(), mattack::zombie_fuse(), and map::~map().
shift_bitset_cache()
template<int SIZE, int MULTIPLIER> void shift_bitset_cache (std::bitset< SIZE *SIZE > & cache, const point & s)
Definition at line 7979 of file map.cpp.
 {
     // sx shifts by MULTIPLIER rows, sy shifts by MULTIPLIER columns.
     int shift_amount = s.x * MULTIPLIER + s.y * SIZE * MULTIPLIER;
     if( shift_amount > 0 ) {
         cache >>= static_cast<size_t>( shift_amount );
     } else if( shift_amount < 0 ) {
         cache <<= static_cast<size_t>( -shift_amount );
     }
     // Shifting in the y direction shifted in 0 values, no no additional clearing is necessary, but
     // a shift in the x direction makes values "wrap" to the next row, and they need to be zeroed.
     if( s.x == 0 ) {
         return;
     }
     const size_t x_offset = s.x > 0 ? SIZE - MULTIPLIER : 0;
     for( size_t y = 0; y < SIZE; ++y ) {
         size_t y_offset = y * SIZE;
         for( size_t x = 0; x < MULTIPLIER; ++x ) {
             cache.reset( y_offset + x_offset + x );
         }
     }
 }
References point::x, and point::y.
ter_furn_has_flag()
bool ter_furn_has_flag (const ter_t & ter, const furn_t & furn, ter_furn_flag flag)
Definition at line 184 of file map_field.cpp.
 {
     return ter.has_flag( flag ) || furn.has_flag( flag );
 }
References map_data_common_t::has_flag().
Referenced by MapExtras::burned_ground_parser(), and map::gas_can_spread_to().