Cataclysm DDA: src/map_extras.cpp File Reference
map_extras.cpp File Reference
#include "map_extras.h"
#include <algorithm>
#include <array>
#include <cstdlib>
#include <functional>
#include <map>
#include <memory>
#include <new>
#include <optional>
#include <set>
#include <unordered_map>
#include <utility>
#include <vector>
#include "auto_note.h"
#include "calendar.h"
#include "cata_utility.h"
#include "cellular_automata.h"
#include "character_id.h"
#include "city.h"
#include "colony.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "creature_tracker.h"
#include "debug.h"
#include "enum_conversions.h"
#include "enums.h"
#include "field_type.h"
#include "fungal_effects.h"
#include "game.h"
#include "game_constants.h"
#include "generic_factory.h"
#include "item.h"
#include "item_group.h"
#include "json.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "mapgen.h"
#include "mapgen_functions.h"
#include "mapgendata.h"
#include "mongroup.h"
#include "options.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "point.h"
#include "regional_settings.h"
#include "rng.h"
#include "sets_intersect.h"
#include "string_formatter.h"
#include "string_id.h"
#include "text_snippets.h"
#include "translations.h"
#include "trap.h"
#include "type_id.h"
#include "ui.h"
#include "units.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vehicle_group.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "weighted_list.h"
Namespaces
io
anonymous_namespace{map_extras.cpp}
MapExtras
Functions
template<>
std::string io::enum_to_string< map_extra_method > (map_extra_method data)
const generic_factory< map_extra > & MapExtras::mapExtraFactory ()
This function provides access to all loaded map extras.
void MapExtras::clear ()
static bool MapExtras::mx_null (map &, const tripoint &)
static void MapExtras::dead_vegetation_parser (map &m, const tripoint &loc)
static void MapExtras::delete_items_at_mount (vehicle &veh, const point &pt)
static bool MapExtras::mx_helicopter (map &m, const tripoint &abs_sub)
static void MapExtras::place_trap_if_clear (tinymap &m, const point &target, trap_id trap_type)
static bool MapExtras::mx_minefield (map &, const tripoint &abs_sub)
static void MapExtras::place_fumarole (map &m, const point &p1, const point &p2, std::set< point > &ignited)
static bool MapExtras::mx_portal_in (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_jabberwock (map &m, const tripoint &)
static bool MapExtras::mx_grove (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_shrubbery (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_pond (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_clay_deposit (map &m, const tripoint &abs_sub)
static void MapExtras::burned_ground_parser (map &m, const tripoint &loc)
static bool MapExtras::mx_point_burned_ground (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_burned_ground (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_reed (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_roadworks (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_casings (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_looters (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_corpses (map &m, const tripoint &abs_sub)
static bool MapExtras::mx_city_trap (map &, const tripoint &abs_sub)
static bool MapExtras::mx_fungal_zone (map &m, const tripoint &abs_sub)
map_extra_pointer MapExtras::get_function (const map_extra_id &name)
std::vector< map_extra_id > MapExtras::get_all_function_names ()
void MapExtras::apply_function (const map_extra_id &id, map &m, const tripoint_abs_sm &abs_sub)
void MapExtras::apply_function (const map_extra_id &id, tinymap &m, const tripoint_abs_omt &abs_omt)
FunctionMap MapExtras::all_functions ()
void MapExtras::load (const JsonObject &jo, const std::string &src)
void MapExtras::check_consistency ()
void MapExtras::debug_spawn_test ()
Variables
static const flag_id json_flag_FILTHY ("FILTHY")
static const furn_str_id furn_f_ash ("f_ash")
static const furn_str_id furn_f_barricade_road ("f_barricade_road")
static const furn_str_id furn_f_bench ("f_bench")
static const furn_str_id furn_f_camp_chair ("f_camp_chair")
static const furn_str_id furn_f_canvas_door ("f_canvas_door")
static const furn_str_id furn_f_canvas_wall ("f_canvas_wall")
static const furn_str_id furn_f_cattails ("f_cattails")
static const furn_str_id furn_f_chair ("f_chair")
static const furn_str_id furn_f_crate_c ("f_crate_c")
static const furn_str_id furn_f_crate_o ("f_crate_o")
static const furn_str_id furn_f_desk ("f_desk")
static const furn_str_id furn_f_fema_groundsheet ("f_fema_groundsheet")
static const furn_str_id furn_f_firering ("f_firering")
static const furn_str_id furn_f_lilypad ("f_lilypad")
static const furn_str_id furn_f_lotus ("f_lotus")
static const furn_str_id furn_f_makeshift_bed ("f_makeshift_bed")
static const furn_str_id furn_f_sandbag_half ("f_sandbag_half")
static const furn_str_id furn_f_sign_warning ("f_sign_warning")
static const furn_str_id furn_f_tourist_table ("f_tourist_table")
static const furn_str_id furn_f_wreckage ("f_wreckage")
static const item_group_id Item_spawn_data_ammo_casings ("ammo_casings")
static const item_group_id Item_spawn_data_army_bed ("army_bed")
static const item_group_id Item_spawn_data_everyday_corpse ("everyday_corpse")
static const item_group_id Item_spawn_data_map_extra_casings ("map_extra_casings")
static const item_group_id Item_spawn_data_mine_equipment ("mine_equipment")
static const item_group_id Item_spawn_data_mon_zombie_soldier_death_drops ("mon_zombie_soldier_death_drops")
static const item_group_id Item_spawn_data_remains_human_generic ("remains_human_generic")
static const item_group_id Item_spawn_data_trash_cart ("trash_cart")
static const itype_id itype_223_casing ("223_casing")
static const itype_id itype_762_51_casing ("762_51_casing")
static const itype_id itype_acoustic_guitar ("acoustic_guitar")
static const itype_id itype_ash ("ash")
static const itype_id itype_bag_canvas ("bag_canvas")
static const itype_id itype_bottle_glass ("bottle_glass")
static const itype_id itype_chunk_sulfur ("chunk_sulfur")
static const itype_id itype_hatchet ("hatchet")
static const itype_id itype_landmine ("landmine")
static const itype_id itype_material_sand ("material_sand")
static const itype_id itype_material_soil ("material_soil")
static const itype_id itype_sheet_cotton ("sheet_cotton")
static const itype_id itype_splinter ("splinter")
static const itype_id itype_stanag30 ("stanag30")
static const itype_id itype_stick ("stick")
static const itype_id itype_stick_long ("stick_long")
static const itype_id itype_vodka ("vodka")
static const itype_id itype_withered ("withered")
static const map_extra_id map_extra_mx_burned_ground ("mx_burned_ground")
static const map_extra_id map_extra_mx_casings ("mx_casings")
static const map_extra_id map_extra_mx_city_trap ("mx_city_trap")
static const map_extra_id map_extra_mx_clay_deposit ("mx_clay_deposit")
static const map_extra_id map_extra_mx_corpses ("mx_corpses")
static const map_extra_id map_extra_mx_fungal_zone ("mx_fungal_zone")
static const map_extra_id map_extra_mx_grove ("mx_grove")
static const map_extra_id map_extra_mx_helicopter ("mx_helicopter")
static const map_extra_id map_extra_mx_jabberwock ("mx_jabberwock")
static const map_extra_id map_extra_mx_looters ("mx_looters")
static const map_extra_id map_extra_mx_minefield ("mx_minefield")
static const map_extra_id map_extra_mx_null ("mx_null")
static const map_extra_id map_extra_mx_point_burned_ground ("mx_point_burned_ground")
static const map_extra_id map_extra_mx_pond ("mx_pond")
static const map_extra_id map_extra_mx_portal_in ("mx_portal_in")
static const map_extra_id map_extra_mx_reed ("mx_reed")
static const map_extra_id map_extra_mx_roadworks ("mx_roadworks")
static const map_extra_id map_extra_mx_shrubbery ("mx_shrubbery")
static const mongroup_id GROUP_FISH ("GROUP_FISH")
static const mongroup_id GROUP_FUNGI_FUNGALOID ("GROUP_FUNGI_FUNGALOID")
static const mongroup_id GROUP_JABBERWOCK ("GROUP_JABBERWOCK")
static const mongroup_id GROUP_MIL_PASSENGER ("GROUP_MIL_PASSENGER")
static const mongroup_id GROUP_MIL_PILOT ("GROUP_MIL_PILOT")
static const mongroup_id GROUP_MIL_WEAK ("GROUP_MIL_WEAK")
static const mongroup_id GROUP_NETHER_PORTAL ("GROUP_NETHER_PORTAL")
static const mongroup_id GROUP_STRAY_DOGS ("GROUP_STRAY_DOGS")
static const mongroup_id GROUP_TURRET_SPEAKER ("GROUP_TURRET_SPEAKER")
static const mtype_id mon_fungaloid_queen ("mon_fungaloid_queen")
static const oter_type_str_id oter_type_bridge ("bridge")
static const oter_type_str_id oter_type_bridgehead_ground ("bridgehead_ground")
static const oter_type_str_id oter_type_road ("road")
static const relic_procgen_id relic_procgen_data_alien_reality ("alien_reality")
static const ter_str_id ter_t_clay ("t_clay")
static const ter_str_id ter_t_dirt ("t_dirt")
static const ter_str_id ter_t_dirtmound ("t_dirtmound")
static const ter_str_id ter_t_fence_barbed ("t_fence_barbed")
static const ter_str_id ter_t_fungus ("t_fungus")
static const ter_str_id ter_t_grass ("t_grass")
static const ter_str_id ter_t_grass_dead ("t_grass_dead")
static const ter_str_id ter_t_grass_golf ("t_grass_golf")
static const ter_str_id ter_t_grass_long ("t_grass_long")
static const ter_str_id ter_t_grass_tall ("t_grass_tall")
static const ter_str_id ter_t_grass_white ("t_grass_white")
static const ter_str_id ter_t_lava ("t_lava")
static const ter_str_id ter_t_moss ("t_moss")
static const ter_str_id ter_t_pavement ("t_pavement")
static const ter_str_id ter_t_pavement_y ("t_pavement_y")
static const ter_str_id ter_t_pit ("t_pit")
static const ter_str_id ter_t_pit_shallow ("t_pit_shallow")
static const ter_str_id ter_t_stump ("t_stump")
static const ter_str_id ter_t_tree_birch ("t_tree_birch")
static const ter_str_id ter_t_tree_birch_harvested ("t_tree_birch_harvested")
static const ter_str_id ter_t_tree_dead ("t_tree_dead")
static const ter_str_id ter_t_tree_deadpine ("t_tree_deadpine")
static const ter_str_id ter_t_tree_hickory ("t_tree_hickory")
static const ter_str_id ter_t_tree_hickory_dead ("t_tree_hickory_dead")
static const ter_str_id ter_t_tree_hickory_harvested ("t_tree_hickory_harvested")
static const ter_str_id ter_t_tree_pine ("t_tree_pine")
static const ter_str_id ter_t_tree_willow ("t_tree_willow")
static const ter_str_id ter_t_trunk ("t_trunk")
static const ter_str_id ter_t_water_dp ("t_water_dp")
static const ter_str_id ter_t_water_moving_dp ("t_water_moving_dp")
static const ter_str_id ter_t_water_moving_sh ("t_water_moving_sh")
static const ter_str_id ter_t_water_sh ("t_water_sh")
static const trap_str_id tr_engine ("tr_engine")
static const vgroup_id VehicleGroup_crashed_helicopters ("crashed_helicopters")
static const vproto_id vehicle_prototype_car_fbi ("car_fbi")
static const vproto_id vehicle_prototype_excavator ("excavator")
static const vproto_id vehicle_prototype_humvee ("humvee")
static const vproto_id vehicle_prototype_military_cargo_truck ("military_cargo_truck")
static const vproto_id vehicle_prototype_road_roller ("road_roller")
generic_factory< map_extra > anonymous_namespace{map_extras.cpp}::extras ("map extra")
static FunctionMap MapExtras::builtin_functions
static std::vector< map_extra_id > MapExtras::all_function_names
Variable Documentation
furn_f_ash
const furn_str_id furn_f_ash("f_ash") ("f_ash") static
Referenced by MapExtras::burned_ground_parser().
furn_f_barricade_road
const furn_str_id furn_f_barricade_road("f_barricade_road") ("f_barricade_road") static
Referenced by MapExtras::mx_roadworks().
furn_f_bench
const furn_str_id furn_f_bench("f_bench") ("f_bench") static
Referenced by MapExtras::mx_minefield().
furn_f_camp_chair
const furn_str_id furn_f_camp_chair("f_camp_chair") ("f_camp_chair") static
Referenced by MapExtras::mx_minefield().
furn_f_canvas_door
const furn_str_id furn_f_canvas_door("f_canvas_door") ("f_canvas_door") static
Referenced by MapExtras::mx_minefield().
furn_f_canvas_wall
const furn_str_id furn_f_canvas_wall("f_canvas_wall") ("f_canvas_wall") static
Referenced by MapExtras::mx_minefield().
furn_f_cattails
const furn_str_id furn_f_cattails("f_cattails") ("f_cattails") static
Referenced by MapExtras::mx_reed().
furn_f_chair
const furn_str_id furn_f_chair("f_chair") ("f_chair") static
Referenced by MapExtras::mx_minefield().
furn_f_crate_c
const furn_str_id furn_f_crate_c("f_crate_c") ("f_crate_c") static
Referenced by MapExtras::mx_minefield(), and MapExtras::mx_roadworks().
furn_f_crate_o
const furn_str_id furn_f_crate_o("f_crate_o") ("f_crate_o") static
Referenced by MapExtras::mx_minefield().
furn_f_desk
const furn_str_id furn_f_desk("f_desk") ("f_desk") static
Referenced by MapExtras::mx_minefield().
furn_f_fema_groundsheet
const furn_str_id furn_f_fema_groundsheet("f_fema_groundsheet") ("f_fema_groundsheet") static
Referenced by MapExtras::mx_minefield().
furn_f_firering
const furn_str_id furn_f_firering("f_firering") ("f_firering") static
Referenced by MapExtras::mx_minefield().
furn_f_lilypad
const furn_str_id furn_f_lilypad("f_lilypad") ("f_lilypad") static
Referenced by MapExtras::mx_reed().
furn_f_lotus
const furn_str_id furn_f_lotus("f_lotus") ("f_lotus") static
Referenced by MapExtras::mx_reed().
furn_f_makeshift_bed
const furn_str_id furn_f_makeshift_bed("f_makeshift_bed") ("f_makeshift_bed") static
Referenced by MapExtras::mx_minefield().
furn_f_sandbag_half
const furn_str_id furn_f_sandbag_half("f_sandbag_half") ("f_sandbag_half") static
Referenced by MapExtras::mx_minefield().
furn_f_sign_warning
const furn_str_id furn_f_sign_warning("f_sign_warning") ("f_sign_warning") static
Referenced by MapExtras::mx_minefield().
furn_f_tourist_table
const furn_str_id furn_f_tourist_table("f_tourist_table") ("f_tourist_table") static
Referenced by MapExtras::mx_minefield().
furn_f_wreckage
const furn_str_id furn_f_wreckage("f_wreckage") ("f_wreckage") static
Referenced by MapExtras::burned_ground_parser(), MapExtras::mx_burned_ground(), and MapExtras::mx_helicopter().
GROUP_FISH
const mongroup_id GROUP_FISH("GROUP_FISH") ("GROUP_FISH") static
Referenced by MapExtras::mx_pond().
GROUP_FUNGI_FUNGALOID
const mongroup_id GROUP_FUNGI_FUNGALOID("GROUP_FUNGI_FUNGALOID") ("GROUP_FUNGI_FUNGALOID") static
Referenced by MapExtras::mx_fungal_zone(), and MapExtras::mx_portal_in().
GROUP_JABBERWOCK
const mongroup_id GROUP_JABBERWOCK("GROUP_JABBERWOCK") ("GROUP_JABBERWOCK") static
Referenced by MapExtras::mx_jabberwock().
GROUP_MIL_PASSENGER
const mongroup_id GROUP_MIL_PASSENGER("GROUP_MIL_PASSENGER") ("GROUP_MIL_PASSENGER") static
Referenced by MapExtras::mx_helicopter().
GROUP_MIL_PILOT
const mongroup_id GROUP_MIL_PILOT("GROUP_MIL_PILOT") ("GROUP_MIL_PILOT") static
Referenced by MapExtras::mx_helicopter().
GROUP_MIL_WEAK
const mongroup_id GROUP_MIL_WEAK("GROUP_MIL_WEAK") ("GROUP_MIL_WEAK") static
Referenced by MapExtras::mx_helicopter().
GROUP_NETHER_PORTAL
const mongroup_id GROUP_NETHER_PORTAL("GROUP_NETHER_PORTAL") ("GROUP_NETHER_PORTAL") static
Referenced by MapExtras::mx_portal_in().
GROUP_STRAY_DOGS
const mongroup_id GROUP_STRAY_DOGS("GROUP_STRAY_DOGS") ("GROUP_STRAY_DOGS") static
Referenced by MapExtras::mx_corpses().
GROUP_TURRET_SPEAKER
const mongroup_id GROUP_TURRET_SPEAKER("GROUP_TURRET_SPEAKER") ("GROUP_TURRET_SPEAKER") static
Referenced by MapExtras::mx_city_trap().
Item_spawn_data_ammo_casings
const item_group_id Item_spawn_data_ammo_casings("ammo_casings") ("ammo_casings") static
Referenced by MapExtras::mx_casings().
Item_spawn_data_army_bed
const item_group_id Item_spawn_data_army_bed("army_bed") ("army_bed") static
Referenced by MapExtras::mx_minefield().
Item_spawn_data_everyday_corpse
const item_group_id Item_spawn_data_everyday_corpse("everyday_corpse") ("everyday_corpse") static
Referenced by MapExtras::mx_corpses().
Item_spawn_data_map_extra_casings
const item_group_id Item_spawn_data_map_extra_casings("map_extra_casings") ("map_extra_casings") static
Referenced by MapExtras::mx_casings().
Item_spawn_data_mine_equipment
const item_group_id Item_spawn_data_mine_equipment("mine_equipment") ("mine_equipment") static
Referenced by MapExtras::mx_roadworks().
Item_spawn_data_mon_zombie_soldier_death_drops
const item_group_id Item_spawn_data_mon_zombie_soldier_death_drops("mon_zombie_soldier_death_drops") ("mon_zombie_soldier_death_drops") static
Referenced by MapExtras::mx_minefield().
Item_spawn_data_remains_human_generic
const item_group_id Item_spawn_data_remains_human_generic("remains_human_generic") ("remains_human_generic") static
Referenced by MapExtras::mx_corpses().
Item_spawn_data_trash_cart
const item_group_id Item_spawn_data_trash_cart("trash_cart") ("trash_cart") static
Referenced by MapExtras::mx_minefield().
itype_223_casing
const itype_id itype_223_casing("223_casing") ("223_casing") static
Referenced by MapExtras::mx_minefield().
itype_762_51_casing
const itype_id itype_762_51_casing("762_51_casing") ("762_51_casing") static
Referenced by MapExtras::mx_minefield().
itype_acoustic_guitar
const itype_id itype_acoustic_guitar("acoustic_guitar") ("acoustic_guitar") static
Referenced by MapExtras::mx_minefield().
itype_ash
const itype_id itype_ash("ash") ("ash") static
Referenced by MapExtras::burned_ground_parser().
itype_bag_canvas
const itype_id itype_bag_canvas("bag_canvas") ("bag_canvas") static
Referenced by MapExtras::mx_minefield().
itype_bottle_glass
const itype_id itype_bottle_glass("bottle_glass") ("bottle_glass") static
Referenced by MapExtras::mx_minefield().
itype_chunk_sulfur
const itype_id itype_chunk_sulfur("chunk_sulfur") ("chunk_sulfur") static
Referenced by MapExtras::place_fumarole().
itype_hatchet
const itype_id itype_hatchet("hatchet") ("hatchet") static
Referenced by MapExtras::mx_minefield().
itype_landmine
const itype_id itype_landmine("landmine") ("landmine") static
Referenced by MapExtras::mx_minefield().
itype_material_sand
const itype_id itype_material_sand("material_sand") ("material_sand") static
Referenced by MapExtras::mx_minefield().
itype_material_soil
const itype_id itype_material_soil("material_soil") ("material_soil") static
Referenced by MapExtras::mx_roadworks().
itype_sheet_cotton
const itype_id itype_sheet_cotton("sheet_cotton") ("sheet_cotton") static
Referenced by MapExtras::mx_casings().
itype_splinter
const itype_id itype_splinter("splinter") ("splinter") static
Referenced by MapExtras::mx_minefield().
itype_stanag30
const itype_id itype_stanag30("stanag30") ("stanag30") static
Referenced by MapExtras::mx_minefield().
itype_stick
const itype_id itype_stick("stick") ("stick") static
Referenced by MapExtras::dead_vegetation_parser().
itype_stick_long
const itype_id itype_stick_long("stick_long") ("stick_long") static
Referenced by MapExtras::dead_vegetation_parser().
itype_vodka
const itype_id itype_vodka("vodka") ("vodka") static
Referenced by MapExtras::mx_minefield().
itype_withered
const itype_id itype_withered("withered") ("withered") static
Referenced by MapExtras::dead_vegetation_parser().
json_flag_FILTHY
const flag_id json_flag_FILTHY("FILTHY") ("FILTHY") static
Referenced by MapExtras::mx_casings().
map_extra_mx_burned_ground
const map_extra_id map_extra_mx_burned_ground("mx_burned_ground") ("mx_burned_ground") static
map_extra_mx_casings
const map_extra_id map_extra_mx_casings("mx_casings") ("mx_casings") static
map_extra_mx_city_trap
const map_extra_id map_extra_mx_city_trap("mx_city_trap") ("mx_city_trap") static
map_extra_mx_clay_deposit
const map_extra_id map_extra_mx_clay_deposit("mx_clay_deposit") ("mx_clay_deposit") static
map_extra_mx_corpses
const map_extra_id map_extra_mx_corpses("mx_corpses") ("mx_corpses") static
map_extra_mx_fungal_zone
const map_extra_id map_extra_mx_fungal_zone("mx_fungal_zone") ("mx_fungal_zone") static
map_extra_mx_grove
const map_extra_id map_extra_mx_grove("mx_grove") ("mx_grove") static
map_extra_mx_helicopter
const map_extra_id map_extra_mx_helicopter("mx_helicopter") ("mx_helicopter") static
map_extra_mx_jabberwock
const map_extra_id map_extra_mx_jabberwock("mx_jabberwock") ("mx_jabberwock") static
map_extra_mx_looters
const map_extra_id map_extra_mx_looters("mx_looters") ("mx_looters") static
map_extra_mx_minefield
const map_extra_id map_extra_mx_minefield("mx_minefield") ("mx_minefield") static
map_extra_mx_null
const map_extra_id map_extra_mx_null("mx_null") ("mx_null") static
map_extra_mx_point_burned_ground
const map_extra_id map_extra_mx_point_burned_ground("mx_point_burned_ground") ("mx_point_burned_ground") static
map_extra_mx_pond
const map_extra_id map_extra_mx_pond("mx_pond") ("mx_pond") static
map_extra_mx_portal_in
const map_extra_id map_extra_mx_portal_in("mx_portal_in") ("mx_portal_in") static
map_extra_mx_reed
const map_extra_id map_extra_mx_reed("mx_reed") ("mx_reed") static
map_extra_mx_roadworks
const map_extra_id map_extra_mx_roadworks("mx_roadworks") ("mx_roadworks") static
map_extra_mx_shrubbery
const map_extra_id map_extra_mx_shrubbery("mx_shrubbery") ("mx_shrubbery") static
mon_fungaloid_queen
const mtype_id mon_fungaloid_queen("mon_fungaloid_queen") ("mon_fungaloid_queen") static
Referenced by MapExtras::mx_fungal_zone().
oter_type_bridge
const oter_type_str_id oter_type_bridge("bridge") ("bridge") static
Referenced by MapExtras::mx_minefield().
oter_type_bridgehead_ground
const oter_type_str_id oter_type_bridgehead_ground("bridgehead_ground") ("bridgehead_ground") static
Referenced by MapExtras::mx_minefield().
oter_type_road
const oter_type_str_id oter_type_road("road") ("road") static
Referenced by MapExtras::mx_minefield(), and MapExtras::mx_roadworks().
relic_procgen_data_alien_reality
const relic_procgen_id relic_procgen_data_alien_reality("alien_reality") ("alien_reality") static
Referenced by MapExtras::mx_portal_in().
ter_t_clay
const ter_str_id ter_t_clay("t_clay") ("t_clay") static
Referenced by MapExtras::mx_clay_deposit().
ter_t_dirt
const ter_str_id ter_t_dirt("t_dirt") ("t_dirt") static
Referenced by MapExtras::burned_ground_parser(), MapExtras::dead_vegetation_parser(), MapExtras::mx_reed(), and MapExtras::mx_roadworks().
ter_t_dirtmound
const ter_str_id ter_t_dirtmound("t_dirtmound") ("t_dirtmound") static
Referenced by MapExtras::mx_helicopter(), and MapExtras::mx_roadworks().
ter_t_fence_barbed
const ter_str_id ter_t_fence_barbed("t_fence_barbed") ("t_fence_barbed") static
Referenced by MapExtras::mx_minefield().
ter_t_fungus
const ter_str_id ter_t_fungus("t_fungus") ("t_fungus") static
Referenced by MapExtras::burned_ground_parser().
ter_t_grass
const ter_str_id ter_t_grass("t_grass") ("t_grass") static
Referenced by MapExtras::burned_ground_parser(), MapExtras::dead_vegetation_parser(), and MapExtras::mx_reed().
ter_t_grass_dead
const ter_str_id ter_t_grass_dead("t_grass_dead") ("t_grass_dead") static
Referenced by MapExtras::burned_ground_parser(), and MapExtras::dead_vegetation_parser().
ter_t_grass_golf
const ter_str_id ter_t_grass_golf("t_grass_golf") ("t_grass_golf") static
Referenced by MapExtras::burned_ground_parser(), and MapExtras::dead_vegetation_parser().
ter_t_grass_long
const ter_str_id ter_t_grass_long("t_grass_long") ("t_grass_long") static
Referenced by MapExtras::burned_ground_parser(), and MapExtras::dead_vegetation_parser().
ter_t_grass_tall
const ter_str_id ter_t_grass_tall("t_grass_tall") ("t_grass_tall") static
Referenced by MapExtras::burned_ground_parser(), MapExtras::dead_vegetation_parser(), and MapExtras::mx_reed().
ter_t_grass_white
const ter_str_id ter_t_grass_white("t_grass_white") ("t_grass_white") static
Referenced by MapExtras::burned_ground_parser(), and MapExtras::dead_vegetation_parser().
ter_t_lava
const ter_str_id ter_t_lava("t_lava") ("t_lava") static
Referenced by MapExtras::mx_portal_in(), and MapExtras::place_fumarole().
ter_t_moss
const ter_str_id ter_t_moss("t_moss") ("t_moss") static
Referenced by MapExtras::burned_ground_parser(), and MapExtras::dead_vegetation_parser().
ter_t_pavement
const ter_str_id ter_t_pavement("t_pavement") ("t_pavement") static
Referenced by MapExtras::mx_city_trap(), and MapExtras::mx_roadworks().
ter_t_pavement_y
const ter_str_id ter_t_pavement_y("t_pavement_y") ("t_pavement_y") static
Referenced by MapExtras::mx_city_trap().
ter_t_pit
const ter_str_id ter_t_pit("t_pit") ("t_pit") static
Referenced by MapExtras::mx_portal_in().
ter_t_pit_shallow
const ter_str_id ter_t_pit_shallow("t_pit_shallow") ("t_pit_shallow") static
Referenced by MapExtras::mx_roadworks().
ter_t_stump
const ter_str_id ter_t_stump("t_stump") ("t_stump") static
Referenced by MapExtras::burned_ground_parser(), and MapExtras::dead_vegetation_parser().
ter_t_tree_birch
const ter_str_id ter_t_tree_birch("t_tree_birch") ("t_tree_birch") static
Referenced by MapExtras::dead_vegetation_parser().
ter_t_tree_birch_harvested
const ter_str_id ter_t_tree_birch_harvested("t_tree_birch_harvested") ("t_tree_birch_harvested") static
Referenced by MapExtras::dead_vegetation_parser().
ter_t_tree_dead
const ter_str_id ter_t_tree_dead("t_tree_dead") ("t_tree_dead") static
Referenced by MapExtras::burned_ground_parser(), and MapExtras::dead_vegetation_parser().
ter_t_tree_deadpine
const ter_str_id ter_t_tree_deadpine("t_tree_deadpine") ("t_tree_deadpine") static
Referenced by MapExtras::dead_vegetation_parser().
ter_t_tree_hickory
const ter_str_id ter_t_tree_hickory("t_tree_hickory") ("t_tree_hickory") static
Referenced by MapExtras::dead_vegetation_parser().
ter_t_tree_hickory_dead
const ter_str_id ter_t_tree_hickory_dead("t_tree_hickory_dead") ("t_tree_hickory_dead") static
Referenced by MapExtras::dead_vegetation_parser().
ter_t_tree_hickory_harvested
const ter_str_id ter_t_tree_hickory_harvested("t_tree_hickory_harvested") ("t_tree_hickory_harvested") static
Referenced by MapExtras::dead_vegetation_parser().
ter_t_tree_pine
const ter_str_id ter_t_tree_pine("t_tree_pine") ("t_tree_pine") static
Referenced by MapExtras::dead_vegetation_parser().
ter_t_tree_willow
const ter_str_id ter_t_tree_willow("t_tree_willow") ("t_tree_willow") static
Referenced by MapExtras::dead_vegetation_parser().
ter_t_trunk
const ter_str_id ter_t_trunk("t_trunk") ("t_trunk") static
Referenced by MapExtras::burned_ground_parser(), and MapExtras::dead_vegetation_parser().
ter_t_water_dp
const ter_str_id ter_t_water_dp("t_water_dp") ("t_water_dp") static
Referenced by MapExtras::mx_pond(), and MapExtras::mx_reed().
ter_t_water_moving_dp
const ter_str_id ter_t_water_moving_dp("t_water_moving_dp") ("t_water_moving_dp") static
Referenced by MapExtras::mx_reed().
ter_t_water_moving_sh
const ter_str_id ter_t_water_moving_sh("t_water_moving_sh") ("t_water_moving_sh") static
Referenced by MapExtras::mx_reed().
ter_t_water_sh
const ter_str_id ter_t_water_sh("t_water_sh") ("t_water_sh") static
Referenced by MapExtras::mx_pond(), and MapExtras::mx_reed().
tr_engine
const trap_str_id tr_engine("tr_engine") ("tr_engine") static
Referenced by MapExtras::mx_city_trap().
vehicle_prototype_car_fbi
const vproto_id vehicle_prototype_car_fbi("car_fbi") ("car_fbi") static
Referenced by MapExtras::mx_minefield().
vehicle_prototype_excavator
const vproto_id vehicle_prototype_excavator("excavator") ("excavator") static
Referenced by MapExtras::mx_roadworks().
vehicle_prototype_humvee
const vproto_id vehicle_prototype_humvee("humvee") ("humvee") static
Referenced by MapExtras::mx_minefield().
vehicle_prototype_military_cargo_truck
const vproto_id vehicle_prototype_military_cargo_truck("military_cargo_truck") ("military_cargo_truck") static
Referenced by MapExtras::mx_minefield().
vehicle_prototype_road_roller
const vproto_id vehicle_prototype_road_roller("road_roller") ("road_roller") static
Referenced by MapExtras::mx_roadworks().
VehicleGroup_crashed_helicopters
const vgroup_id VehicleGroup_crashed_helicopters("crashed_helicopters") ("crashed_helicopters") static
Referenced by MapExtras::mx_helicopter().