Cataclysm DDA: src/mapdata.cpp File Reference
mapdata.cpp File Reference
#include "mapdata.h"
#include <algorithm>
#include <cstdlib>
#include <iterator>
#include <map>
#include <memory>
#include <unordered_map>
#include <utility>
#include "assign.h"
#include "calendar.h"
#include "color.h"
#include "debug.h"
#include "enum_conversions.h"
#include "generic_factory.h"
#include "harvest.h"
#include "iexamine.h"
#include "iexamine_actors.h"
#include "item_group.h"
#include "json.h"
#include "output.h"
#include "rng.h"
#include "string_formatter.h"
#include "translations.h"
#include "trap.h"
#include "type_id.h"
Namespaces
anonymous_namespace{mapdata.cpp}
io
Functions
template<>
std::string io::enum_to_string< ter_furn_flag > (ter_furn_flag data)
connect_group get_connect_group (const std::string &name)
static void load_map_bash_tent_centers (const JsonArray &ja, std::vector< furn_str_id > &centers)
furn_t null_furniture_t ()
ter_t null_terrain_t ()
template<typename C , typename F >
void load_season_array (const JsonObject &jo, const std::string &key, const std::string &context, C &container, F load_func)
void load_furniture (const JsonObject &jo, const std::string &src)
void load_terrain (const JsonObject &jo, const std::string &src)
void set_ter_ids ()
void reset_furn_ter ()
void set_furn_ids ()
template<>
std::string io::enum_to_string< season_type > (season_type data)
static void add_actor (std::unique_ptr< iexamine_actor > ptr)
static cata::clone_ptr< iexamine_actor > iexamine_actor_from_jsobj (const JsonObject &jo)
void init_mapdata ()
static void check_bash_items (const map_bash_info &mbi, const std::string &id, bool is_terrain)
static void check_decon_items (const map_deconstruct_info &mbi, const std::string &id, bool is_terrain)
void check_furniture_and_terrain ()
Variables
static furn_id f_null
static const item_group_id Item_spawn_data_EMPTY_GROUP ("EMPTY_GROUP")
generic_factory< ter_t > anonymous_namespace{mapdata.cpp}::terrain_data ("terrain")
generic_factory< furn_t > anonymous_namespace{mapdata.cpp}::furniture_data ("furniture")
static std::unordered_map< std::string, connect_group > ter_connects_map
ter_id t_null
static std::map< std::string, cata::clone_ptr< iexamine_actor > > examine_actors
Function Documentation
add_actor()
static void add_actor (std::unique_ptr< iexamine_actor > ptr) static
Definition at line 801 of file mapdata.cpp.
 {
     std::string type = ptr->type;
     examine_actors[type] = cata::clone_ptr<iexamine_actor>( std::move( ptr ) );
 }
References examine_actors.
Referenced by init_mapdata(), and Item_factory::usage_from_object().
check_bash_items()
static void check_bash_items (const map_bash_info & mbi, const std::string & id, bool is_terrain) static
Definition at line 944 of file mapdata.cpp.
 {
     if( !item_group::group_is_defined( mbi.drop_group ) ) {
         debugmsg( "%s: bash result item group %s does not exist", id.c_str(), mbi.drop_group.c_str() );
     }
     if( mbi.str_max != -1 ) {
         if( is_terrain && mbi.ter_set.is_empty() ) { // Some tiles specify t_null explicitly
             debugmsg( "bash result terrain of %s is undefined/empty", id.c_str() );
         }
         if( !mbi.ter_set.is_valid() ) {
             debugmsg( "bash result terrain %s of %s does not exist", mbi.ter_set.c_str(), id.c_str() );
         }
         if( !mbi.furn_set.is_valid() ) {
             debugmsg( "bash result furniture %s of %s does not exist", mbi.furn_set.c_str(), id.c_str() );
         }
     }
 }
References string_id< T >::c_str(), debugmsg, map_bash_info::drop_group, map_bash_info::furn_set, item_group::group_is_defined(), string_id< T >::is_empty(), string_id< T >::is_valid(), map_bash_info::str_max, and map_bash_info::ter_set.
Referenced by ter_t::check(), and furn_t::check().
check_decon_items()
static void check_decon_items (const map_deconstruct_info & mbi, const std::string & id, bool is_terrain) static
Definition at line 962 of file mapdata.cpp.
 {
     if( !mbi.can_do ) {
         return;
     }
     if( !item_group::group_is_defined( mbi.drop_group ) ) {
         debugmsg( "%s: deconstruct result item group %s does not exist", id.c_str(),
                   mbi.drop_group.c_str() );
     }
     if( is_terrain && mbi.ter_set.is_empty() ) { // Some tiles specify t_null explicitly
         debugmsg( "deconstruct result terrain of %s is undefined/empty", id.c_str() );
     }
     if( !mbi.ter_set.is_valid() ) {
         debugmsg( "deconstruct result terrain %s of %s does not exist", mbi.ter_set.c_str(), id.c_str() );
     }
     if( !mbi.furn_set.is_valid() ) {
         debugmsg( "deconstruct result furniture %s of %s does not exist", mbi.furn_set.c_str(),
                   id.c_str() );
     }
 }
References string_id< T >::c_str(), map_deconstruct_info::can_do, debugmsg, map_deconstruct_info::drop_group, map_deconstruct_info::furn_set, item_group::group_is_defined(), string_id< T >::is_empty(), string_id< T >::is_valid(), and map_deconstruct_info::ter_set.
Referenced by ter_t::check(), and furn_t::check().
check_furniture_and_terrain()
void check_furniture_and_terrain ()
Definition at line 1222 of file mapdata.cpp.
 {
     terrain_data.check();
     furniture_data.check();
 }
References anonymous_namespace{mapdata.cpp}::furniture_data, and anonymous_namespace{mapdata.cpp}::terrain_data.
Referenced by DynamicDataLoader::check_consistency().
get_connect_group()
connect_group get_connect_group (const std::string & name)
Definition at line 283 of file mapdata.cpp.
 {
     return ter_connects_map[name];
 }
References om_direction::name(), and ter_connects_map.
iexamine_actor_from_jsobj()
static cata::clone_ptr<iexamine_actor> iexamine_actor_from_jsobj (const JsonObject & jo) static
Definition at line 807 of file mapdata.cpp.
 {
     std::string type = jo.get_string( "type" );
     try {
         return examine_actors.at( type );
     } catch( const std::exception & ) {
         jo.throw_error( string_format( "Invalid iexamine actor %s", type ) );
     }
 }
References examine_actors, JsonObject::get_string(), string_format(), and JsonObject::throw_error().
Referenced by map_data_common_t::load().
init_mapdata()
void init_mapdata ()
Definition at line 817 of file mapdata.cpp.
 {
     add_actor( std::make_unique<appliance_convert_examine_actor>() );
     add_actor( std::make_unique<cardreader_examine_actor>() );
     add_actor( std::make_unique<eoc_examine_actor>() );
 }
References add_actor().
Referenced by DynamicDataLoader::initialize().
load_furniture()
void load_furniture (const JsonObject & jo, const std::string & src)
Definition at line 653 of file mapdata.cpp.
 {
     if( furniture_data.empty() ) {
         furniture_data.insert( null_furniture_t() );
     }
     furniture_data.load( jo, src );
 }
References anonymous_namespace{mapdata.cpp}::furniture_data, and null_furniture_t().
Referenced by DynamicDataLoader::initialize().
load_map_bash_tent_centers()
static void load_map_bash_tent_centers (const JsonArray & ja, std::vector< furn_str_id > & centers) static
Definition at line 335 of file mapdata.cpp.
 {
     for( const std::string line : ja ) {
         centers.emplace_back( line );
     }
 }
References line().
Referenced by map_bash_info::load().
load_season_array()
template<typename C , typename F > void load_season_array (const JsonObject & jo, const std::string & key, const std::string & context, C & container, F load_func)
Definition at line 534 of file mapdata.cpp.
 {
     if( jo.has_string( key ) ) {
         container.fill( load_func( jo.get_string( key ) ) );
     } else if( jo.has_array( key ) ) {
         JsonArray arr = jo.get_array( key );
         if( arr.size() == 1 ) {
             container.fill( load_func( arr.get_string( 0 ) ) );
         } else if( arr.size() == container.size() ) {
             for( auto &e : container ) {
                 e = load_func( arr.next_string() );
             }
         } else {
             jo.throw_error_at( key, "Incorrect number of entries" );
         }
     } else if( jo.has_member( key ) ) {
         jo.throw_error_at(
             key, string_format( "Expected '%s' member to be string or array", key ) );
     } else {
         jo.throw_error(
             string_format( "Expected '%s' member in %s but none was found", key, context ) );
     }
 }
References context, JsonObject::get_array(), JsonObject::get_string(), JsonArray::get_string(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_string(), JsonArray::next_string(), JsonArray::size(), string_format(), JsonObject::throw_error(), and JsonObject::throw_error_at().
Referenced by map_data_common_t::load_symbol().
load_terrain()
void load_terrain (const JsonObject & jo, const std::string & src)
Definition at line 661 of file mapdata.cpp.
 {
     if( terrain_data.empty() ) { // TODO: This shouldn't live here
         terrain_data.insert( null_terrain_t() );
     }
     terrain_data.load( jo, src );
 }
References null_terrain_t(), and anonymous_namespace{mapdata.cpp}::terrain_data.
Referenced by DynamicDataLoader::initialize().
null_furniture_t()
furn_t null_furniture_t ()
Definition at line 494 of file mapdata.cpp.
 {
     furn_t new_furniture;
     new_furniture.id = furn_str_id::NULL_ID();
     new_furniture.name_ = to_translation( "nothing" );
     new_furniture.symbol_.fill( ' ' );
     new_furniture.color_.fill( c_white );
     new_furniture.light_emitted = 0;
     new_furniture.movecost = 0;
     new_furniture.move_str_req = -1;
     new_furniture.transparent = true;
     new_furniture.set_flag( ter_furn_flag::TFLAG_TRANSPARENT );
     new_furniture.examine_func = iexamine_functions_from_string( "none" );
     new_furniture.max_volume = DEFAULT_TILE_VOLUME;
     return new_furniture;
 }
Referenced by load_furniture().
null_terrain_t()
ter_t null_terrain_t ()
Definition at line 515 of file mapdata.cpp.
 {
     ter_t new_terrain;
     new_terrain.id = ter_str_id::NULL_ID();
     new_terrain.name_ = to_translation( "nothing" );
     new_terrain.symbol_.fill( ' ' );
     new_terrain.color_.fill( c_white );
     new_terrain.light_emitted = 0;
     new_terrain.movecost = 0;
     new_terrain.transparent = true;
     new_terrain.set_flag( ter_furn_flag::TFLAG_TRANSPARENT );
     new_terrain.set_flag( ter_furn_flag::TFLAG_DIGGABLE );
     new_terrain.examine_func = iexamine_functions_from_string( "none" );
     new_terrain.max_volume = DEFAULT_TILE_VOLUME;
     return new_terrain;
 }
Referenced by load_terrain().
reset_furn_ter()
void reset_furn_ter ()
Definition at line 764 of file mapdata.cpp.
 {
     terrain_data.reset();
     furniture_data.reset();
 }
References anonymous_namespace{mapdata.cpp}::furniture_data, and anonymous_namespace{mapdata.cpp}::terrain_data.
Referenced by DynamicDataLoader::unload_data().
set_furn_ids()
void set_furn_ids ()
Definition at line 770 of file mapdata.cpp.
 {
     f_null = furn_id( "f_null" );
 }
References f_null.
Referenced by DynamicDataLoader::finalize_loaded_data().
set_ter_ids()
void set_ter_ids ()
Definition at line 750 of file mapdata.cpp.
 {
     t_null = ter_id( "t_null" );
     for( const ter_t &elem : terrain_data.get_all() ) {
         ter_t &ter = const_cast<ter_t &>( elem );
         if( ter.trap_id_str.empty() ) {
             ter.trap = tr_null;
         } else {
             ter.trap = trap_str_id( ter.trap_id_str );
         }
     }
 }
References t_null, anonymous_namespace{mapdata.cpp}::terrain_data, tr_null, ter_t::trap, and ter_t::trap_id_str.
Referenced by DynamicDataLoader::finalize_loaded_data().
Variable Documentation
examine_actors
std::map<std::string, cata::clone_ptr<iexamine_actor> > examine_actors static
Definition at line 799 of file mapdata.cpp.
Referenced by add_actor(), and iexamine_actor_from_jsobj().
f_null
furn_id f_null static
Definition at line 29 of file mapdata.cpp.
Referenced by string_id< T >::id(), and set_furn_ids().
Item_spawn_data_EMPTY_GROUP
const item_group_id Item_spawn_data_EMPTY_GROUP("EMPTY_GROUP") ("EMPTY_GROUP") static
Referenced by map_bash_info::load().
t_null
ter_id t_null
Definition at line 748 of file mapdata.cpp.
Referenced by complete_construction(), mapgen_function_json::generate(), regional_settings::regional_settings(), set_ter_ids(), update_mapgen_function_json::setup_internal(), and mapgen_function_json::setup_internal().
ter_connects_map
std::unordered_map<std::string, connect_group> ter_connects_map static
Definition at line 281 of file mapdata.cpp.
Referenced by map_data_common_t::extraprocess_flags(), get_connect_group(), connect_group::load(), connect_group::reset(), and map_data_common_t::set_groups().