Cataclysm DDA: src/mapdata.h File Reference
mapdata.h File Reference
#include <array>
#include <bitset>
#include <cstddef>
#include <iosfwd>
#include <set>
#include <string>
#include <vector>
#include "calendar.h"
#include "clone_ptr.h"
#include "color.h"
#include "enum_bitset.h"
#include "game_constants.h"
#include "iexamine.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "value_ptr.h"
Classes
struct map_bash_info
struct map_deconstruct_skill
struct map_deconstruct_info
struct map_shoot_info
struct furn_workbench_info
struct plant_data
struct enum_traits< ter_furn_flag >
struct connect_group
struct activity_byproduct
struct pry_data
class activity_data_common
class activity_data_ter
class activity_data_furn
struct map_data_common_t
struct ter_t
struct furn_t
class ter_furn_migrations
Macros
#define CATA_SRC_MAPDATA_H
Typedefs
using ter_str_id = string_id< ter_t >
Enumerations
enum class ter_furn_flag : int {
TFLAG_TRANSPARENT , TFLAG_FLAMMABLE , TFLAG_REDUCE_SCENT , TFLAG_SWIMMABLE ,
TFLAG_SUPPORTS_ROOF , TFLAG_MINEABLE , TFLAG_NOITEM , TFLAG_NO_SIGHT ,
TFLAG_NO_SCENT , TFLAG_SEALED , TFLAG_ALLOW_FIELD_EFFECT , TFLAG_LIQUID ,
TFLAG_COLLAPSES , TFLAG_FLAMMABLE_ASH , TFLAG_DESTROY_ITEM , TFLAG_INDOORS ,
TFLAG_LIQUIDCONT , TFLAG_FIRE_CONTAINER , TFLAG_FLAMMABLE_HARD , TFLAG_SUPPRESS_SMOKE ,
TFLAG_SHARP , TFLAG_DIGGABLE , TFLAG_ROUGH , TFLAG_UNSTABLE ,
TFLAG_WALL , TFLAG_DEEP_WATER , TFLAG_SHALLOW_WATER , TFLAG_WATER_CUBE ,
TFLAG_CURRENT , TFLAG_HARVESTED , TFLAG_PERMEABLE , TFLAG_AUTO_WALL_SYMBOL ,
TFLAG_CONNECT_WITH_WALL , TFLAG_CLIMBABLE , TFLAG_GOES_DOWN , TFLAG_GOES_UP ,
TFLAG_NO_FLOOR , TFLAG_ALLOW_ON_OPEN_AIR , TFLAG_SEEN_FROM_ABOVE , TFLAG_RAMP_DOWN ,
TFLAG_RAMP_UP , TFLAG_RAMP , TFLAG_HIDE_PLACE , TFLAG_BLOCK_WIND ,
TFLAG_FLAT , TFLAG_RAIL , TFLAG_THIN_OBSTACLE , TFLAG_SMALL_PASSAGE ,
TFLAG_Z_TRANSPARENT , TFLAG_SUN_ROOF_ABOVE , TFLAG_FUNGUS , TFLAG_LOCKED ,
TFLAG_PICKABLE , TFLAG_WINDOW , TFLAG_DOOR , TFLAG_SHRUB ,
TFLAG_YOUNG , TFLAG_PLANT , TFLAG_FISHABLE , TFLAG_GRAZABLE ,
TFLAG_GRAZER_INEDIBLE , TFLAG_BROWSABLE , TFLAG_TREE , TFLAG_PLOWABLE ,
TFLAG_ORGANIC , TFLAG_CONSOLE , TFLAG_PLANTABLE , TFLAG_GROWTH_HARVEST ,
TFLAG_GROWTH_OVERGROWN , TFLAG_MOUNTABLE , TFLAG_RAMP_END , TFLAG_FLOWER ,
TFLAG_CAN_SIT , TFLAG_FLAT_SURF , TFLAG_BUTCHER_EQ , TFLAG_GROWTH_SEEDLING ,
TFLAG_GROWTH_MATURE , TFLAG_WORKOUT_ARMS , TFLAG_WORKOUT_LEGS , TFLAG_TRANSLOCATOR ,
TFLAG_AUTODOC , TFLAG_AUTODOC_COUCH , TFLAG_OPENCLOSE_INSIDE , TFLAG_SALT_WATER ,
TFLAG_PLACE_ITEM , TFLAG_BARRICADABLE_WINDOW_CURTAINS , TFLAG_CLIMB_SIMPLE , TFLAG_NANOFAB_TABLE ,
TFLAG_ROAD , TFLAG_TINY , TFLAG_SHORT , TFLAG_NOCOLLIDE ,
TFLAG_BARRICADABLE_DOOR , TFLAG_BARRICADABLE_DOOR_DAMAGED , TFLAG_BARRICADABLE_DOOR_REINFORCED , TFLAG_USABLE_FIRE ,
TFLAG_CONTAINER , TFLAG_NO_PICKUP_ON_EXAMINE , TFLAG_RUBBLE , TFLAG_DIGGABLE_CAN_DEEPEN ,
TFLAG_PIT_FILLABLE , TFLAG_DIFFICULT_Z , TFLAG_ALIGN_WORKBENCH , TFLAG_NO_SPOIL ,
TFLAG_EASY_DECONSTRUCT , TFLAG_LADDER , TFLAG_ALARMED , TFLAG_CHOCOLATE ,
TFLAG_SIGN , TFLAG_SIGN_ALWAYS , TFLAG_DONT_REMOVE_ROTTEN , TFLAG_BLOCKSDOOR ,
TFLAG_NO_SELF_CONNECT , TFLAG_BURROWABLE , TFLAG_MURKY , TFLAG_AMMOTYPE_RELOAD ,
TFLAG_TRANSPARENT_FLOOR , TFLAG_TOILET_WATER , TFLAG_ELEVATOR , TFLAG_ACTIVE_GENERATOR ,
TFLAG_SMALL_HIDE , TFLAG_NO_FLOOR_WATER , TFLAG_SINGLE_SUPPORT , TFLAG_CLIMB_ADJACENT ,
TFLAG_FLOATS_IN_AIR , NUM_TFLAG_FLAGS
}
Functions
connect_group get_connect_group (const std::string &name)
void init_mapdata ()
void set_ter_ids ()
void set_furn_ids ()
void reset_furn_ter ()
void load_furniture (const JsonObject &jo, const std::string &src)
void load_terrain (const JsonObject &jo, const std::string &src)
void verify_furniture ()
void verify_terrain ()
void check_furniture_and_terrain ()
void finalize_furniture_and_terrain ()
Variables
const int NUM_TERCONN = 32
ter_id t_null
Macro Definition Documentation
CATA_SRC_MAPDATA_H
#define CATA_SRC_MAPDATA_H
Definition at line 3 of file mapdata.h.
Typedef Documentation
ter_str_id
using ter_str_id = string_id<ter_t>
Definition at line 26 of file mapdata.h.
Enumeration Type Documentation
ter_furn_flag
enum ter_furn_flag : int strong
Enumerator
TFLAG_TRANSPARENT
TFLAG_FLAMMABLE
TFLAG_REDUCE_SCENT
TFLAG_SWIMMABLE
TFLAG_SUPPORTS_ROOF
TFLAG_MINEABLE
TFLAG_NOITEM
TFLAG_NO_SIGHT
TFLAG_NO_SCENT
TFLAG_SEALED
TFLAG_ALLOW_FIELD_EFFECT
TFLAG_LIQUID
TFLAG_COLLAPSES
TFLAG_FLAMMABLE_ASH
TFLAG_DESTROY_ITEM
TFLAG_INDOORS
TFLAG_LIQUIDCONT
TFLAG_FIRE_CONTAINER
TFLAG_FLAMMABLE_HARD
TFLAG_SUPPRESS_SMOKE
TFLAG_SHARP
TFLAG_DIGGABLE
TFLAG_ROUGH
TFLAG_UNSTABLE
TFLAG_WALL
TFLAG_DEEP_WATER
TFLAG_SHALLOW_WATER
TFLAG_WATER_CUBE
TFLAG_CURRENT
TFLAG_HARVESTED
TFLAG_PERMEABLE
TFLAG_AUTO_WALL_SYMBOL
TFLAG_CONNECT_WITH_WALL
TFLAG_CLIMBABLE
TFLAG_GOES_DOWN
TFLAG_GOES_UP
TFLAG_NO_FLOOR
TFLAG_ALLOW_ON_OPEN_AIR
TFLAG_SEEN_FROM_ABOVE
TFLAG_RAMP_DOWN
TFLAG_RAMP_UP
TFLAG_RAMP
TFLAG_HIDE_PLACE
TFLAG_BLOCK_WIND
TFLAG_FLAT
TFLAG_RAIL
TFLAG_THIN_OBSTACLE
TFLAG_SMALL_PASSAGE
TFLAG_Z_TRANSPARENT
TFLAG_SUN_ROOF_ABOVE
TFLAG_FUNGUS
TFLAG_LOCKED
TFLAG_PICKABLE
TFLAG_WINDOW
TFLAG_DOOR
TFLAG_SHRUB
TFLAG_YOUNG
TFLAG_PLANT
TFLAG_FISHABLE
TFLAG_GRAZABLE
TFLAG_GRAZER_INEDIBLE
TFLAG_BROWSABLE
TFLAG_TREE
TFLAG_PLOWABLE
TFLAG_ORGANIC
TFLAG_CONSOLE
TFLAG_PLANTABLE
TFLAG_GROWTH_HARVEST
TFLAG_GROWTH_OVERGROWN
TFLAG_MOUNTABLE
TFLAG_RAMP_END
TFLAG_FLOWER
TFLAG_CAN_SIT
TFLAG_FLAT_SURF
TFLAG_BUTCHER_EQ
TFLAG_GROWTH_SEEDLING
TFLAG_GROWTH_MATURE
TFLAG_WORKOUT_ARMS
TFLAG_WORKOUT_LEGS
TFLAG_TRANSLOCATOR
TFLAG_AUTODOC
TFLAG_AUTODOC_COUCH
TFLAG_OPENCLOSE_INSIDE
TFLAG_SALT_WATER
TFLAG_PLACE_ITEM
TFLAG_BARRICADABLE_WINDOW_CURTAINS
TFLAG_CLIMB_SIMPLE
TFLAG_NANOFAB_TABLE
TFLAG_ROAD
TFLAG_TINY
TFLAG_SHORT
TFLAG_NOCOLLIDE
TFLAG_BARRICADABLE_DOOR
TFLAG_BARRICADABLE_DOOR_DAMAGED
TFLAG_BARRICADABLE_DOOR_REINFORCED
TFLAG_USABLE_FIRE
TFLAG_CONTAINER
TFLAG_NO_PICKUP_ON_EXAMINE
TFLAG_RUBBLE
TFLAG_DIGGABLE_CAN_DEEPEN
TFLAG_PIT_FILLABLE
TFLAG_DIFFICULT_Z
TFLAG_ALIGN_WORKBENCH
TFLAG_NO_SPOIL
TFLAG_EASY_DECONSTRUCT
TFLAG_LADDER
TFLAG_ALARMED
TFLAG_CHOCOLATE
TFLAG_SIGN
TFLAG_SIGN_ALWAYS
TFLAG_DONT_REMOVE_ROTTEN
TFLAG_BLOCKSDOOR
TFLAG_NO_SELF_CONNECT
TFLAG_BURROWABLE
TFLAG_MURKY
TFLAG_AMMOTYPE_RELOAD
TFLAG_TRANSPARENT_FLOOR
TFLAG_TOILET_WATER
TFLAG_ELEVATOR
TFLAG_ACTIVE_GENERATOR
TFLAG_SMALL_HIDE
TFLAG_NO_FLOOR_WATER
TFLAG_SINGLE_SUPPORT
TFLAG_CLIMB_ADJACENT
TFLAG_FLOATS_IN_AIR
NUM_TFLAG_FLAGS
Definition at line 202 of file mapdata.h.
                          : int {
     TFLAG_TRANSPARENT,
     TFLAG_FLAMMABLE,
     TFLAG_REDUCE_SCENT,
     TFLAG_SWIMMABLE,
     TFLAG_SUPPORTS_ROOF,
     TFLAG_MINEABLE,
     TFLAG_NOITEM,
     TFLAG_NO_SIGHT,
     TFLAG_NO_SCENT,
     TFLAG_SEALED,
     TFLAG_ALLOW_FIELD_EFFECT,
     TFLAG_LIQUID,
     TFLAG_COLLAPSES,
     TFLAG_FLAMMABLE_ASH,
     TFLAG_DESTROY_ITEM,
     TFLAG_INDOORS,
     TFLAG_LIQUIDCONT,
     TFLAG_FIRE_CONTAINER,
     TFLAG_FLAMMABLE_HARD,
     TFLAG_SUPPRESS_SMOKE,
     TFLAG_SHARP,
     TFLAG_DIGGABLE,
     TFLAG_ROUGH,
     TFLAG_UNSTABLE,
     TFLAG_WALL,
     TFLAG_DEEP_WATER,
     TFLAG_SHALLOW_WATER,
     TFLAG_WATER_CUBE,
     TFLAG_CURRENT,
     TFLAG_HARVESTED,
     TFLAG_PERMEABLE,
     TFLAG_AUTO_WALL_SYMBOL,
     TFLAG_CONNECT_WITH_WALL,
     TFLAG_CLIMBABLE,
     TFLAG_GOES_DOWN,
     TFLAG_GOES_UP,
     TFLAG_NO_FLOOR,
     TFLAG_ALLOW_ON_OPEN_AIR,
     TFLAG_SEEN_FROM_ABOVE,
     TFLAG_RAMP_DOWN,
     TFLAG_RAMP_UP,
     TFLAG_RAMP,
     TFLAG_HIDE_PLACE,
     TFLAG_BLOCK_WIND,
     TFLAG_FLAT,
     TFLAG_RAIL,
     TFLAG_THIN_OBSTACLE,
     TFLAG_SMALL_PASSAGE,
     TFLAG_Z_TRANSPARENT,
     TFLAG_SUN_ROOF_ABOVE,
     TFLAG_FUNGUS,
     TFLAG_LOCKED,
     TFLAG_PICKABLE,
     TFLAG_WINDOW,
     TFLAG_DOOR,
     TFLAG_SHRUB,
     TFLAG_YOUNG,
     TFLAG_PLANT,
     TFLAG_FISHABLE,
     TFLAG_GRAZABLE,
     TFLAG_GRAZER_INEDIBLE,
     TFLAG_BROWSABLE,
     TFLAG_TREE,
     TFLAG_PLOWABLE,
     TFLAG_ORGANIC,
     TFLAG_CONSOLE,
     TFLAG_PLANTABLE,
     TFLAG_GROWTH_HARVEST,
     TFLAG_GROWTH_OVERGROWN,
     TFLAG_MOUNTABLE,
     TFLAG_RAMP_END,
     TFLAG_FLOWER,
     TFLAG_CAN_SIT,
     TFLAG_FLAT_SURF,
     TFLAG_BUTCHER_EQ,
     TFLAG_GROWTH_SEEDLING,
     TFLAG_GROWTH_MATURE,
     TFLAG_WORKOUT_ARMS,
     TFLAG_WORKOUT_LEGS,
     TFLAG_TRANSLOCATOR,
     TFLAG_AUTODOC,
     TFLAG_AUTODOC_COUCH,
     TFLAG_OPENCLOSE_INSIDE,
     TFLAG_SALT_WATER,
     TFLAG_PLACE_ITEM,
     TFLAG_BARRICADABLE_WINDOW_CURTAINS,
     TFLAG_CLIMB_SIMPLE,
     TFLAG_NANOFAB_TABLE,
     TFLAG_ROAD,
     TFLAG_TINY,
     TFLAG_SHORT,
     TFLAG_NOCOLLIDE,
     TFLAG_BARRICADABLE_DOOR,
     TFLAG_BARRICADABLE_DOOR_DAMAGED,
     TFLAG_BARRICADABLE_DOOR_REINFORCED,
     TFLAG_USABLE_FIRE,
     TFLAG_CONTAINER,
     TFLAG_NO_PICKUP_ON_EXAMINE,
     TFLAG_RUBBLE,
     TFLAG_DIGGABLE_CAN_DEEPEN,
     TFLAG_PIT_FILLABLE,
     TFLAG_DIFFICULT_Z,
     TFLAG_ALIGN_WORKBENCH,
     TFLAG_NO_SPOIL,
     TFLAG_EASY_DECONSTRUCT,
     TFLAG_LADDER,
     TFLAG_ALARMED,
     TFLAG_CHOCOLATE,
     TFLAG_SIGN,
     TFLAG_SIGN_ALWAYS,
     TFLAG_DONT_REMOVE_ROTTEN,
     TFLAG_BLOCKSDOOR,
     TFLAG_NO_SELF_CONNECT,
     TFLAG_BURROWABLE,
     TFLAG_MURKY,
     TFLAG_AMMOTYPE_RELOAD,
     TFLAG_TRANSPARENT_FLOOR,
     TFLAG_TOILET_WATER,
     TFLAG_ELEVATOR,
     TFLAG_ACTIVE_GENERATOR,
     TFLAG_SMALL_HIDE,
     TFLAG_NO_FLOOR_WATER,
     TFLAG_SINGLE_SUPPORT,
     TFLAG_CLIMB_ADJACENT,
     TFLAG_FLOATS_IN_AIR,
     NUM_TFLAG_FLAGS
 };
Function Documentation
check_furniture_and_terrain()
void check_furniture_and_terrain ()
Definition at line 1222 of file mapdata.cpp.
 {
     terrain_data.check();
     furniture_data.check();
 }
References anonymous_namespace{mapdata.cpp}::furniture_data, and anonymous_namespace{mapdata.cpp}::terrain_data.
Referenced by DynamicDataLoader::check_consistency().
finalize_furniture_and_terrain()
void finalize_furniture_and_terrain ()
get_connect_group()
connect_group get_connect_group (const std::string & name)
Definition at line 283 of file mapdata.cpp.
 {
     return ter_connects_map[name];
 }
References om_direction::name(), and ter_connects_map.
init_mapdata()
void init_mapdata ()
Definition at line 817 of file mapdata.cpp.
 {
     add_actor( std::make_unique<appliance_convert_examine_actor>() );
     add_actor( std::make_unique<cardreader_examine_actor>() );
     add_actor( std::make_unique<eoc_examine_actor>() );
 }
References add_actor().
Referenced by DynamicDataLoader::initialize().
load_furniture()
void load_furniture (const JsonObject & jo, const std::string & src)
Definition at line 653 of file mapdata.cpp.
 {
     if( furniture_data.empty() ) {
         furniture_data.insert( null_furniture_t() );
     }
     furniture_data.load( jo, src );
 }
References anonymous_namespace{mapdata.cpp}::furniture_data, and null_furniture_t().
Referenced by DynamicDataLoader::initialize().
load_terrain()
void load_terrain (const JsonObject & jo, const std::string & src)
Definition at line 661 of file mapdata.cpp.
 {
     if( terrain_data.empty() ) { // TODO: This shouldn't live here
         terrain_data.insert( null_terrain_t() );
     }
     terrain_data.load( jo, src );
 }
References null_terrain_t(), and anonymous_namespace{mapdata.cpp}::terrain_data.
Referenced by DynamicDataLoader::initialize().
reset_furn_ter()
void reset_furn_ter ()
Definition at line 764 of file mapdata.cpp.
 {
     terrain_data.reset();
     furniture_data.reset();
 }
References anonymous_namespace{mapdata.cpp}::furniture_data, and anonymous_namespace{mapdata.cpp}::terrain_data.
Referenced by DynamicDataLoader::unload_data().
set_furn_ids()
void set_furn_ids ()
Definition at line 770 of file mapdata.cpp.
 {
     f_null = furn_id( "f_null" );
 }
References f_null.
Referenced by DynamicDataLoader::finalize_loaded_data().
set_ter_ids()
void set_ter_ids ()
Definition at line 750 of file mapdata.cpp.
 {
     t_null = ter_id( "t_null" );
     for( const ter_t &elem : terrain_data.get_all() ) {
         ter_t &ter = const_cast<ter_t &>( elem );
         if( ter.trap_id_str.empty() ) {
             ter.trap = tr_null;
         } else {
             ter.trap = trap_str_id( ter.trap_id_str );
         }
     }
 }
References t_null, anonymous_namespace{mapdata.cpp}::terrain_data, tr_null, ter_t::trap, and ter_t::trap_id_str.
Referenced by DynamicDataLoader::finalize_loaded_data().
verify_furniture()
void verify_furniture ()
verify_terrain()
void verify_terrain ()
Variable Documentation
NUM_TERCONN
const int NUM_TERCONN = 32
Definition at line 36 of file mapdata.h.
Referenced by connect_group::load().
t_null
ter_id t_null extern
Definition at line 748 of file mapdata.cpp.
Referenced by complete_construction(), mapgen_function_json::generate(), regional_settings::regional_settings(), set_ter_ids(), update_mapgen_function_json::setup_internal(), and mapgen_function_json::setup_internal().