Cataclysm DDA: src/mapgen.h File Reference
mapgen.h File Reference
#include <cstddef>
#include <iosfwd>
#include <map>
#include <memory>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "cata_variant.h"
#include "coordinates.h"
#include "dialogue_helpers.h"
#include "jmapgen_flags.h"
#include "json.h"
#include "memory_fast.h"
#include "point.h"
#include "regional_settings.h"
#include "type_id.h"
#include "weighted_list.h"
Classes
class mapgen_function
class mapgen_function_builtin
struct jmapgen_int
struct enum_traits< mapgen_phase >
struct jmapgen_setmap
struct spawn_data
class jmapgen_piece
Basic mapgen object.
class jmapgen_place
Where to place something on a map.
class map_key
struct std::hash< map_key >
struct mapgen_constraint< T >
class mapgen_palette
struct mapgen_palette::add_palette_context
struct jmapgen_objects
class mapgen_function_json_base
class mapgen_function_json
class update_mapgen_function_json
class mapgen_function_json_nested
class nested_mapgen
class update_mapgen
Macros
#define CATA_SRC_MAPGEN_H
Typedefs
using building_gen_pointer = void(*)(mapgendata &)
Enumerations
enum class mapgen_phase {
removal , terrain , furniture , default_ ,
nested_mapgen , transform , faction_ownership , zones ,
last
}
Mapgen pieces will be applied in order of phases.
enum jmapgen_setmap_op {
JMAPGEN_SETMAP_OPTYPE_POINT = 0 , JMAPGEN_SETMAP_TER , JMAPGEN_SETMAP_FURN , JMAPGEN_SETMAP_TRAP ,
JMAPGEN_SETMAP_RADIATION , JMAPGEN_SETMAP_TRAP_REMOVE , JMAPGEN_SETMAP_CREATURE_REMOVE , JMAPGEN_SETMAP_ITEM_REMOVE ,
JMAPGEN_SETMAP_FIELD_REMOVE , JMAPGEN_SETMAP_BASH , JMAPGEN_SETMAP_VARIABLE , JMAPGEN_SETMAP_OPTYPE_LINE = 100 ,
JMAPGEN_SETMAP_LINE_TER , JMAPGEN_SETMAP_LINE_FURN , JMAPGEN_SETMAP_LINE_TRAP , JMAPGEN_SETMAP_LINE_RADIATION ,
JMAPGEN_SETMAP_LINE_TRAP_REMOVE , JMAPGEN_SETMAP_LINE_CREATURE_REMOVE , JMAPGEN_SETMAP_LINE_ITEM_REMOVE , JMAPGEN_SETMAP_LINE_FIELD_REMOVE ,
JMAPGEN_SETMAP_OPTYPE_SQUARE = 200 , JMAPGEN_SETMAP_SQUARE_TER , JMAPGEN_SETMAP_SQUARE_FURN , JMAPGEN_SETMAP_SQUARE_TRAP ,
JMAPGEN_SETMAP_SQUARE_RADIATION , JMAPGEN_SETMAP_SQUARE_TRAP_REMOVE , JMAPGEN_SETMAP_SQUARE_CREATURE_REMOVE , JMAPGEN_SETMAP_SQUARE_ITEM_REMOVE ,
JMAPGEN_SETMAP_SQUARE_FIELD_REMOVE
}
enum room_type {
room_null , room_closet , room_lobby , room_chemistry ,
room_teleport , room_goo , room_cloning , room_vivisect ,
room_bionics , room_dorm , room_living , room_bathroom ,
room_kitchen , room_bedroom , room_backyard , room_study ,
room_split
}
move to building_generation
Functions
bool operator< (const mapgen_phase l, const mapgen_phase r)
std::shared_ptr< mapgen_function > load_mapgen_function (const JsonObject &jio, const std::string &id_base, const point &offset, const point &total)
void load_and_add_mapgen_function (const JsonObject &jio, const std::string &id_base, const point &offset, const point &total)
void load_mapgen (const JsonObject &jo)
void reset_mapgens ()
int register_mapgen_function (const std::string &key)
Attempts to register the built-in function key as mapgen for the overmap terrain key.
bool has_mapgen_for (const std::string &key)
Check that key is present in oter_mapgen.
void check_mapgen_consistent_with (const std::string &key, const oter_t &)
Verify that the properties of a particular mapgen match the properties of its overmap_terrain.
bool has_update_mapgen_for (const update_mapgen_id &)
Check whether key is a valid update_mapgen id.
void calculate_mapgen_weights ()
void check_mapgen_definitions ()
bool connects_to (const oter_id &there, int dir)
void line (map *m, const ter_id &type, const point &p1, const point &p2, int z)
void line (tinymap *m, const ter_id &type, const point &p1, const point &p2)
void line_furn (map *m, const furn_id &type, const point &p1, const point &p2, int z)
void line_furn (tinymap *m, const furn_id &type, const point &p1, const point &p2)
void fill_background (map *m, const ter_id &type)
void fill_background (map *m, ter_id(*f)())
void square (map *m, const ter_id &type, const point &p1, const point &p2)
void square (map *m, ter_id(*f)(), const point &p1, const point &p2)
void square (map *m, const weighted_int_list< ter_id > &f, const point &p1, const point &p2)
void square_furn (map *m, const furn_id &type, const point &p1, const point &p2)
void square_furn (tinymap *m, const furn_id &type, const point &p1, const point &p2)
void rough_circle (map *m, const ter_id &type, const point &, int rad)
void rough_circle_furn (map *m, const furn_id &type, const point &, int rad)
void circle (map *m, const ter_id &type, double x, double y, double rad)
void circle (map *m, const ter_id &type, const point &, int rad)
void circle_furn (map *m, const furn_id &type, const point &, int rad)
void add_corpse (map *m, const point &)
Variables
std::map< nested_mapgen_id, nested_mapgen > nested_mapgens
std::map< update_mapgen_id, update_mapgen > update_mapgens
Macro Definition Documentation
CATA_SRC_MAPGEN_H
#define CATA_SRC_MAPGEN_H
Definition at line 3 of file mapgen.h.
Typedef Documentation
building_gen_pointer
using building_gen_pointer = void (*)(mapgendata &)
Definition at line 33 of file mapgen.h.
Enumeration Type Documentation
jmapgen_setmap_op
enum jmapgen_setmap_op
Enumerator
JMAPGEN_SETMAP_OPTYPE_POINT
JMAPGEN_SETMAP_TER
JMAPGEN_SETMAP_FURN
JMAPGEN_SETMAP_TRAP
JMAPGEN_SETMAP_RADIATION
JMAPGEN_SETMAP_TRAP_REMOVE
JMAPGEN_SETMAP_CREATURE_REMOVE
JMAPGEN_SETMAP_ITEM_REMOVE
JMAPGEN_SETMAP_FIELD_REMOVE
JMAPGEN_SETMAP_BASH
JMAPGEN_SETMAP_VARIABLE
JMAPGEN_SETMAP_OPTYPE_LINE
JMAPGEN_SETMAP_LINE_TER
JMAPGEN_SETMAP_LINE_FURN
JMAPGEN_SETMAP_LINE_TRAP
JMAPGEN_SETMAP_LINE_RADIATION
JMAPGEN_SETMAP_LINE_TRAP_REMOVE
JMAPGEN_SETMAP_LINE_CREATURE_REMOVE
JMAPGEN_SETMAP_LINE_ITEM_REMOVE
JMAPGEN_SETMAP_LINE_FIELD_REMOVE
JMAPGEN_SETMAP_OPTYPE_SQUARE
JMAPGEN_SETMAP_SQUARE_TER
JMAPGEN_SETMAP_SQUARE_FURN
JMAPGEN_SETMAP_SQUARE_TRAP
JMAPGEN_SETMAP_SQUARE_RADIATION
JMAPGEN_SETMAP_SQUARE_TRAP_REMOVE
JMAPGEN_SETMAP_SQUARE_CREATURE_REMOVE
JMAPGEN_SETMAP_SQUARE_ITEM_REMOVE
JMAPGEN_SETMAP_SQUARE_FIELD_REMOVE
Definition at line 130 of file mapgen.h.
{
     JMAPGEN_SETMAP_OPTYPE_POINT = 0,
     JMAPGEN_SETMAP_TER,
     JMAPGEN_SETMAP_FURN,
     JMAPGEN_SETMAP_TRAP,
     JMAPGEN_SETMAP_RADIATION,
     JMAPGEN_SETMAP_TRAP_REMOVE,
     JMAPGEN_SETMAP_CREATURE_REMOVE,
     JMAPGEN_SETMAP_ITEM_REMOVE,
     JMAPGEN_SETMAP_FIELD_REMOVE,
     JMAPGEN_SETMAP_BASH,
     JMAPGEN_SETMAP_VARIABLE,
     JMAPGEN_SETMAP_OPTYPE_LINE = 100,
     JMAPGEN_SETMAP_LINE_TER,
     JMAPGEN_SETMAP_LINE_FURN,
     JMAPGEN_SETMAP_LINE_TRAP,
     JMAPGEN_SETMAP_LINE_RADIATION,
     JMAPGEN_SETMAP_LINE_TRAP_REMOVE,
     JMAPGEN_SETMAP_LINE_CREATURE_REMOVE,
     JMAPGEN_SETMAP_LINE_ITEM_REMOVE,
     JMAPGEN_SETMAP_LINE_FIELD_REMOVE,
     JMAPGEN_SETMAP_OPTYPE_SQUARE = 200,
     JMAPGEN_SETMAP_SQUARE_TER,
     JMAPGEN_SETMAP_SQUARE_FURN,
     JMAPGEN_SETMAP_SQUARE_TRAP,
     JMAPGEN_SETMAP_SQUARE_RADIATION,
     JMAPGEN_SETMAP_SQUARE_TRAP_REMOVE,
     JMAPGEN_SETMAP_SQUARE_CREATURE_REMOVE,
     JMAPGEN_SETMAP_SQUARE_ITEM_REMOVE,
     JMAPGEN_SETMAP_SQUARE_FIELD_REMOVE
 };
mapgen_phase
enum mapgen_phase strong
Mapgen pieces will be applied in order of phases.
The phases are as follows:
Enumerator
removal
terrain
furniture
default_
nested_mapgen
transform
faction_ownership
zones
last
Definition at line 108 of file mapgen.h.
{
     removal,
     terrain,
     furniture,
     default_,
     nested_mapgen,
     transform,
     faction_ownership,
     zones,
     last
 };
room_type
enum room_type
move to building_generation
Enumerator
room_null
room_closet
room_lobby
room_chemistry
room_teleport
room_goo
room_cloning
room_vivisect
room_bionics
room_dorm
room_living
room_bathroom
room_kitchen
room_bedroom
room_backyard
room_study
room_split
Definition at line 628 of file mapgen.h.
                {
     room_null,
     room_closet,
     room_lobby,
     room_chemistry,
     room_teleport,
     room_goo,
     room_cloning,
     room_vivisect,
     room_bionics,
     room_dorm,
     room_living,
     room_bathroom,
     room_kitchen,
     room_bedroom,
     room_backyard,
     room_study,
     room_split
 };
Function Documentation
add_corpse()
void add_corpse (map * m, const point & p)
Definition at line 7785 of file mapgen.cpp.
 {
     m->add_corpse( tripoint( p, m->get_abs_sub().z() ) );
 }
References map::add_corpse(), map::get_abs_sub(), tripoint, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
calculate_mapgen_weights()
void calculate_mapgen_weights ()
Definition at line 572 of file mapgen.cpp.
 {
     oter_mapgen.setup();
     // Not really calculate weights, but let's keep it here for now
     for( auto &pr : nested_mapgens ) {
         for( const weighted_object<int, std::shared_ptr<mapgen_function_json_nested>> &ptr :
              pr.second.funcs() ) {
             ptr.obj->setup();
             inp_mngr.pump_events();
         }
     }
     for( auto &pr : update_mapgens ) {
         for( const auto &ptr : pr.second.funcs() ) {
             ptr->setup();
             inp_mngr.pump_events();
         }
     }
     // Having set up all the mapgens we can now perform a second
     // pass of finalizing their parameters
     oter_mapgen.finalize_parameters();
     for( auto &pr : nested_mapgens ) {
         for( const weighted_object<int, std::shared_ptr<mapgen_function_json_nested>> &ptr :
              pr.second.funcs() ) {
             ptr.obj->finalize_parameters();
             inp_mngr.pump_events();
         }
     }
     for( auto &pr : update_mapgens ) {
         for( const auto &ptr : pr.second.funcs() ) {
             ptr->finalize_parameters();
             inp_mngr.pump_events();
         }
     }
 }
References mapgen_factory::finalize_parameters(), inp_mngr, nested_mapgens, oter_mapgen, input_manager::pump_events(), mapgen_factory::setup(), and update_mapgens.
Referenced by DynamicDataLoader::finalize_loaded_data().
check_mapgen_consistent_with()
void check_mapgen_consistent_with (const std::string & key, const oter_t & ter)
Verify that the properties of a particular mapgen match the properties of its overmap_terrain.
Definition at line 7802 of file mapgen.cpp.
 {
     if( const mapgen_basic_container *container = oter_mapgen.find( key ) ) {
         container->check_consistency_with( ter );
     }
 }
References mapgen_factory::find(), and oter_mapgen.
Referenced by overmap_terrains::check_consistency().
check_mapgen_definitions()
void check_mapgen_definitions ()
Definition at line 607 of file mapgen.cpp.
 {
     oter_mapgen.check_consistency();
     for( const auto &oter_definition : nested_mapgens ) {
         for( const auto &mapgen_function_ptr : oter_definition.second.funcs() ) {
             mapgen_function_ptr.obj->check();
         }
     }
     for( const auto &oter_definition : update_mapgens ) {
         for( const auto &mapgen_function_ptr : oter_definition.second.funcs() ) {
             mapgen_function_ptr->check();
         }
     }
 }
References mapgen_factory::check_consistency(), nested_mapgens, oter_mapgen, and update_mapgens.
Referenced by DynamicDataLoader::check_consistency().
circle() [1/2]
void circle (map * m, const ter_id & type, const point & p, int rad)
Definition at line 7777 of file mapgen.cpp.
 {
     m->draw_circle_ter( type, p, rad );
 }
References map::draw_circle_ter(), and type.
circle() [2/2]
void circle (map * m, const ter_id & type, double x, double y, double rad)
Definition at line 7773 of file mapgen.cpp.
 {
     m->draw_circle_ter( type, rl_vec2d( x, y ), rad );
 }
References map::draw_circle_ter(), and type.
Referenced by chop_tree_activity_actor::finish(), map::get_dir_circle(), and MapExtras::mx_roadworks().
circle_furn()
void circle_furn (map * m, const furn_id & type, const point & p, int rad)
Definition at line 7781 of file mapgen.cpp.
 {
     m->draw_circle_furn( type, p, rad );
 }
References map::draw_circle_furn(), and type.
connects_to()
bool connects_to (const oter_id & there, int dir)
Definition at line 7154 of file mapgen.cpp.
 {
     switch( dir ) {
         // South
         case 2:
             if( there == oter_ants_ns || there == oter_ants_es ||
                 there == oter_ants_sw || there == oter_ants_nes || there == oter_ants_nsw ||
                 there == oter_ants_esw || there == oter_ants_nesw ) {
                 return true;
             }
             return false;
         // West
         case 3:
             if( there == oter_ants_ew || there == oter_ants_sw ||
                 there == oter_ants_wn || there == oter_ants_new || there == oter_ants_nsw ||
                 there == oter_ants_esw || there == oter_ants_nesw ) {
                 return true;
             }
             return false;
         // North
         case 0:
             if( there == oter_ants_ns || there == oter_ants_ne ||
                 there == oter_ants_wn || there == oter_ants_nes || there == oter_ants_new ||
                 there == oter_ants_nsw || there == oter_ants_nesw ) {
                 return true;
             }
             return false;
         // East
         case 1:
             if( there == oter_ants_ew || there == oter_ants_ne ||
                 there == oter_ants_es || there == oter_ants_nes || there == oter_ants_new ||
                 there == oter_ants_esw || there == oter_ants_nesw ) {
                 return true;
             }
             return false;
         default:
             debugmsg( "Connects_to with dir of %d", dir );
             return false;
     }
 }
References debugmsg, oter_ants_es, oter_ants_esw, oter_ants_ew, oter_ants_ne, oter_ants_nes, oter_ants_nesw, oter_ants_new, oter_ants_ns, oter_ants_nsw, oter_ants_sw, and oter_ants_wn.
Referenced by map::draw_lab(), and targeting_graph< T, Wrapper >::generate().
fill_background() [1/2]
void fill_background (map * m, const ter_id & type)
Definition at line 7737 of file mapgen.cpp.
 {
     m->draw_fill_background( type );
 }
References map::draw_fill_background(), and type.
Referenced by map::draw_map(), mapgen_river_center(), mapgen_river_curved(), mapgen_river_curved_not(), mapgen_river_straight(), and mapgen_rock_partial().
fill_background() [2/2]
void fill_background (map * m, ter_id(*)() f)
Definition at line 7741 of file mapgen.cpp.
 {
     m->draw_fill_background( f );
 }
References map::draw_fill_background().
has_mapgen_for()
bool has_mapgen_for (const std::string & key)
Check that key is present in oter_mapgen.
Definition at line 8068 of file mapgen.cpp.
 {
     return oter_mapgen.has( key );
 }
References mapgen_factory::has(), and oter_mapgen.
Referenced by overmap_terrains::check_consistency().
has_update_mapgen_for()
bool has_update_mapgen_for (const update_mapgen_id & key)
Check whether key is a valid update_mapgen id.
Definition at line 8073 of file mapgen.cpp.
 {
     return update_mapgens.count( key );
 }
References update_mapgens.
Referenced by recipe_dictionary::check_consistency().
line() [1/2]
void line (map * m, const ter_id & type, const point & p1, const point & p2, int z)
Definition at line 7721 of file mapgen.cpp.
 {
     m->draw_line_ter( type, p1, p2, z );
 }
References map::draw_line_ter(), and type.
Referenced by add_array_to_set(), append_line(), assign_coverage_from_json(), mattack::boomer(), mattack::boomer_glow(), spell_detail::build_line(), talk_function::commune_refuge_caravan(), construction_menu(), continue_line(), cursorx_to_position(), debug_error_prompt(), Messages::display_messages(), overmap_ui::draw_ascii(), draw_bionics_info(), draw_bionics_tab(), cataimgui::window::draw_colored_text(), draw_effects_info(), draw_effects_tab(), draw_encumbrance_info(), draw_encumbrance_tab(), draw_health_summary(), draw_info_window(), draw_line(), draw_messages(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), draw_proficiencies_info(), draw_proficiencies_tab(), draw_skills_info(), draw_skills_tab(), draw_speed_info(), draw_speed_tab(), draw_spellbook_info(), draw_stats_info(), draw_stats_tab(), draw_traits_info(), draw_traits_tab(), anonymous_namespace{animation.cpp}::draw_zones_curses(), handle_player_display_action(), has_obstruction(), om_lines::has_segment(), insert_table(), om_lines::is_straight(), isDebuggerActive(), line_to(), npc_template::load(), load_map_bash_tent_centers(), load_mapgen(), load_overmap_feature_flag_settings(), load_world_option(), mapgen_ravine_edge(), mapgen_river_curved(), mapgen_river_straight(), move_along_line(), MapExtras::mx_minefield(), anonymous_namespace{flexbuffer_cache.cpp}::parse_json_to_flexbuffer_(), print_ranged_chance(), realDebugmsg(), right_print(), om_lines::rotate(), scrollable_text(), select_crafter_and_crafting_recipe(), repetition_folder::set(), set_description(), om_lines::set_segment(), Messages::dialog::show(), skip_skill_headers(), slope_of(), repetition_folder::test(), translate_gendered_line(), and iexamine::vending().
line() [2/2]
void line (tinymap * m, const ter_id & type, const point & p1, const point & p2)
Definition at line 7725 of file mapgen.cpp.
 {
     m->draw_line_ter( type, p1, p2 );
 }
References tinymap::draw_line_ter(), and type.
line_furn() [1/2]
void line_furn (map * m, const furn_id & type, const point & p1, const point & p2, int z)
Definition at line 7729 of file mapgen.cpp.
 {
     m->draw_line_furn( type, p1, p2, z );
 }
References map::draw_line_furn(), and type.
Referenced by MapExtras::mx_minefield(), and MapExtras::mx_roadworks().
line_furn() [2/2]
void line_furn (tinymap * m, const furn_id & type, const point & p1, const point & p2)
Definition at line 7733 of file mapgen.cpp.
 {
     m->draw_line_furn( type, p1, p2 );
 }
References tinymap::draw_line_furn(), and type.
load_and_add_mapgen_function()
void load_and_add_mapgen_function (const JsonObject & jio, const std::string & id_base, const point & offset, const point & total)
Definition at line 679 of file mapgen.cpp.
 {
     std::shared_ptr<mapgen_function> f = load_mapgen_function( jio, id_base, offset, total );
     if( f ) {
         oter_mapgen.add( id_base, f );
     }
 }
References mapgen_factory::add(), load_mapgen_function(), and oter_mapgen.
Referenced by load_mapgen(), and load_overmap_terrain_mapgens().
load_mapgen()
void load_mapgen (const JsonObject & jo)
Definition at line 732 of file mapgen.cpp.
 {
     // NOLINTNEXTLINE(cata-use-named-point-constants)
     static constexpr point point_one( 1, 1 );
     if( jo.has_array( "om_terrain" ) ) {
         JsonArray ja = jo.get_array( "om_terrain" );
         if( ja.test_array() ) {
             point offset;
             point total( ja.get_array( 0 ).size(), ja.size() );
             for( JsonArray row_items : ja ) {
                 for( const std::string mapgenid : row_items ) {
                     load_and_add_mapgen_function( jo, mapgenid, offset, total );
                     offset.x++;
                 }
                 offset.y++;
                 offset.x = 0;
             }
         } else {
             std::vector<std::string> mapgenid_list;
             for( const std::string line : ja ) {
                 mapgenid_list.push_back( line );
             }
             if( !mapgenid_list.empty() ) {
                 const std::string mapgenid = mapgenid_list[0];
                 const auto mgfunc = load_mapgen_function( jo, mapgenid, point_zero, point_one );
                 if( mgfunc ) {
                     for( auto &i : mapgenid_list ) {
                         oter_mapgen.add( i, mgfunc );
                     }
                 }
             }
         }
     } else if( jo.has_string( "om_terrain" ) ) {
         load_and_add_mapgen_function( jo, jo.get_string( "om_terrain" ), point_zero, point_one );
     } else if( jo.has_string( "nested_mapgen_id" ) ) {
         load_nested_mapgen( jo, nested_mapgen_id( jo.get_string( "nested_mapgen_id" ) ) );
     } else if( jo.has_string( "update_mapgen_id" ) ) {
         load_update_mapgen( jo, update_mapgen_id( jo.get_string( "update_mapgen_id" ) ) );
     } else {
         debugmsg( "mapgen entry requires \"om_terrain\" or \"nested_mapgen_id\"(string, array of strings, or array of array of strings)\n%s\n",
                   jo.str() );
     }
 }
References mapgen_factory::add(), debugmsg, JsonArray::get_array(), JsonObject::get_array(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_string(), line(), load_and_add_mapgen_function(), load_mapgen_function(), load_nested_mapgen(), load_update_mapgen(), oter_mapgen, point_zero, JsonArray::size(), JsonObject::str(), JsonArray::test_array(), point::x, and point::y.
Referenced by DynamicDataLoader::initialize().
load_mapgen_function()
std::shared_ptr<mapgen_function> load_mapgen_function (const JsonObject & jio, const std::string & id_base, const point & offset, const point & total)
Definition at line 650 of file mapgen.cpp.
 {
     dbl_or_var weight = get_dbl_or_var( jio, "weight", false,  1000 );
     if( jio.get_bool( "disabled", false ) ) {
         jio.allow_omitted_members();
         return nullptr; // nothing
     }
     const std::string mgtype = jio.get_string( "method" );
     if( mgtype == "builtin" ) {
         if( const building_gen_pointer ptr = get_mapgen_cfunction( jio.get_string( "name" ) ) ) {
             return std::make_shared<mapgen_function_builtin>( ptr, std::move( weight ) );
         } else {
             jio.throw_error_at( "name", "function does not exist" );
         }
     } else if( mgtype == "json" ) {
         if( !jio.has_object( "object" ) ) {
             jio.throw_error( R"(mapgen with method "json" must define key "object")" );
         }
         JsonObject jo = jio.get_object( "object" );
         jo.allow_omitted_members();
         return std::make_shared<mapgen_function_json>(
                    jo, std::move( weight ), "mapgen " + id_base, offset, total );
     } else {
         jio.throw_error_at( "method", R"(invalid value: must be "builtin" or "json")" );
     }
 }
References JsonObject::allow_omitted_members(), JsonObject::get_bool(), get_dbl_or_var(), get_mapgen_cfunction(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_object(), JsonObject::throw_error(), and JsonObject::throw_error_at().
Referenced by load_and_add_mapgen_function(), and load_mapgen().
operator<()
bool operator< (const mapgen_phase l, const mapgen_phase r) inline
Definition at line 125 of file mapgen.h.
 {
     return static_cast<int>( l ) < static_cast<int>( r );
 }
register_mapgen_function()
int register_mapgen_function (const std::string & key)
Attempts to register the built-in function key as mapgen for the overmap terrain key.
If there is no matching function, it does nothing (no error message) and returns -1. Otherwise it returns the index of the added entry in the vector of oter_mapgen.
Definition at line 8060 of file mapgen.cpp.
 {
     if( const building_gen_pointer ptr = get_mapgen_cfunction( key ) ) {
         return oter_mapgen.add( key, std::make_shared<mapgen_function_builtin>( ptr ) );
     }
     return -1;
 }
References mapgen_factory::add(), get_mapgen_cfunction(), and oter_mapgen.
Referenced by load_overmap_terrain_mapgens().
reset_mapgens()
void reset_mapgens ()
Definition at line 777 of file mapgen.cpp.
 {
     oter_mapgen.reset();
     nested_mapgens.clear();
     update_mapgens.clear();
 }
References nested_mapgens, oter_mapgen, mapgen_factory::reset(), and update_mapgens.
Referenced by DynamicDataLoader::unload_data().
rough_circle()
void rough_circle (map * m, const ter_id & type, const point & p, int rad)
Definition at line 7765 of file mapgen.cpp.
 {
     m->draw_rough_circle_ter( type, p, rad );
 }
References map::draw_rough_circle_ter(), and type.
Referenced by map::create_anomaly(), and MapExtras::mx_roadworks().
rough_circle_furn()
void rough_circle_furn (map * m, const furn_id & type, const point & p, int rad)
Definition at line 7769 of file mapgen.cpp.
 {
     m->draw_rough_circle_furn( type, p, rad );
 }
References map::draw_rough_circle_furn(), and type.
Referenced by map::create_anomaly().
square() [1/3]
void square (map * m, const ter_id & type, const point & p1, const point & p2)
Definition at line 7745 of file mapgen.cpp.
 {
     m->draw_square_ter( type, p1, p2, m->get_abs_sub().z() );
 }
References map::draw_square_ter(), map::get_abs_sub(), type, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by outfit::add_AIM_items_from_area(), advanced_inventory_pane::add_items_from_area(), query_destination_callback::draw_squares(), advanced_inventory_pane::free_volume(), avatar::get_AIM_inventory(), outfit::get_AIM_inventory(), advanced_inventory::init(), advanced_inventory_pane::load_settings(), MapExtras::mx_roadworks(), advanced_inventory::redraw_pane(), and advanced_inventory_pane::set_area().
square() [2/3]
void square (map * m, const weighted_int_list< ter_id > & f, const point & p1, const point & p2)
Definition at line 7761 of file mapgen.cpp.
 {
     m->draw_square_ter( f, p1, p2 );
 }
References map::draw_square_ter().
square() [3/3]
void square (map * m, ter_id(*)() f, const point & p1, const point & p2)
Definition at line 7757 of file mapgen.cpp.
 {
     m->draw_square_ter( f, p1, p2 );
 }
References map::draw_square_ter().
square_furn() [1/2]
void square_furn (map * m, const furn_id & type, const point & p1, const point & p2)
Definition at line 7749 of file mapgen.cpp.
 {
     m->draw_square_furn( type, p1, p2, m->get_abs_sub().z() );
 }
References map::draw_square_furn(), map::get_abs_sub(), type, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by map::draw_lab(), and MapExtras::mx_minefield().
square_furn() [2/2]
void square_furn (tinymap * m, const furn_id & type, const point & p1, const point & p2)
Definition at line 7753 of file mapgen.cpp.
 {
     m->draw_square_furn( type, p1, p2 );
 }
References tinymap::draw_square_furn(), and type.
Variable Documentation
nested_mapgens
std::map<nested_mapgen_id, nested_mapgen> nested_mapgens extern
Definition at line 529 of file mapgen.cpp.
Referenced by jmapgen_nested::apply(), calculate_mapgen_weights(), check_mapgen_definitions(), jmapgen_nested::has_vehicle_collision(), string_id< T >::is_valid(), load_nested_mapgen(), jmapgen_nested::merge_parameters_into(), string_id< T >::obj(), reset_mapgens(), and debug_menu::spawn_nested_mapgen().
update_mapgens
std::map<update_mapgen_id, update_mapgen> update_mapgens extern
Definition at line 530 of file mapgen.cpp.
Referenced by apply_construction_marker(), calculate_mapgen_weights(), map_extra::check(), check_mapgen_definitions(), get_changed_ids_from_update(), has_update_mapgen_for(), load_update_mapgen(), reset_mapgens(), and run_mapgen_update_func().