Cataclysm DDA: src/mapgen.cpp File Reference
mapgen.cpp File Reference
#include "mapgen.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdlib>
#include <map>
#include <memory>
#include <optional>
#include <ostream>
#include <set>
#include <stdexcept>
#include <type_traits>
#include <unordered_map>
#include "all_enum_values.h"
#include "avatar.h"
#include "calendar.h"
#include "cata_assert.h"
#include "catacharset.h"
#include "character_id.h"
#include "city.h"
#include "clzones.h"
#include "colony.h"
#include "common_types.h"
#include "computer.h"
#include "condition.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "cuboid_rectangle.h"
#include "debug.h"
#include "drawing_primitives.h"
#include "enum_conversions.h"
#include "enums.h"
#include "field_type.h"
#include "game.h"
#include "game_constants.h"
#include "generic_factory.h"
#include "global_vars.h"
#include "input.h"
#include "item.h"
#include "item_factory.h"
#include "item_group.h"
#include "itype.h"
#include "level_cache.h"
#include "line.h"
#include "magic_ter_furn_transform.h"
#include "map.h"
#include "map_extras.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "mapgen_functions.h"
#include "mapgendata.h"
#include "mapgenformat.h"
#include "memory_fast.h"
#include "mission.h"
#include "mongroup.h"
#include "npc.h"
#include "omdata.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "pocket_type.h"
#include "point.h"
#include "ret_val.h"
#include "rng.h"
#include "string_formatter.h"
#include "submap.h"
#include "text_snippets.h"
#include "tileray.h"
#include "to_string_id.h"
#include "translations.h"
#include "trap.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vehicle_group.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "weighted_list.h"
#include "creature_tracker.h"
Classes
class mapgen_basic_container
class mapgen_factory
struct make_null_helper< std::string >
struct make_null_helper< string_id< T > >
struct make_null_helper< int_id< T > >
class mapgen_value< Id >
struct mapgen_value< Id >::value_source
struct mapgen_value< Id >::null_source
struct mapgen_value< Id >::id_source
struct mapgen_value< Id >::param_source
struct mapgen_value< Id >::distribution_source
struct mapgen_value< Id >::switch_source
class jmapgen_alternatively< PieceType >
This is a generic mapgen piece, the template parameter PieceType should be another specific type of jmapgen_piece.
class jmapgen_constrained< Value >
class jmapgen_field
Places fields on the map.
class jmapgen_npc
Place an NPC.
class jmapgen_faction
Place ownership area.
class jmapgen_sign
Place a sign with some text.
class jmapgen_graffiti
Place graffiti with some text or a snippet.
class jmapgen_vending_machine
Place a vending machine with content.
class jmapgen_toilet
Place a toilet with (dirty) water in it.
class jmapgen_gaspump
Place a gas pump with fuel in it.
class jmapgen_liquid_item
Place a specific liquid into the map.
class jmapgen_corpse
Place a corpse of a random monster from a monster group into the map.
class jmapgen_item_group
Place items from an item group.
class jmapgen_loot
Place items from an item group.
class jmapgen_monster_group
Place spawn points for a monster group (actual monster spawning is done later).
class jmapgen_monster
Place spawn points for a specific monster.
class jmapgen_vehicle
Place a vehicle.
class jmapgen_spawn_item
Place a specific item.
class jmapgen_trap
Place a trap.
class jmapgen_furniture
Place a furniture.
class jmapgen_terrain
Place terrain.
class jmapgen_ter_furn_transform
Run a transformation.
class jmapgen_make_rubble
Calls map::make_rubble to create rubble and destroy the existing terrain/furniture.
class jmapgen_computer
Place a computer (console) with given stats and effects.
class jmapgen_sealed_item
Place an item in furniture (expected to be used with NOITEM SEALED furniture like plants).
class jmapgen_zone
Place a zone.
class jmapgen_variable
Place a variable.
class jmapgen_remove_vehicles
Removes vehicles.
class jmapgen_remove_npcs
class jmapgen_remove_all
class jmapgen_nested
Calls another mapgen call inside the current one.
class jmapgen_nested::neighbor_oter_check
class jmapgen_nested::neighbor_join_check
class jmapgen_nested::neighbor_flag_check
class jmapgen_nested::neighbor_flag_any_check
class jmapgen_nested::predecessor_oter_check
class jmapgen_nested::correct_z_level_check
struct phase_comparator
class rotation_guard
Namespaces
mapgen_defer
Tiny little namespace to hold error messages.
io
Macros
#define dbg(x) DebugLog((x),D_MAP_GEN) << __FILE__ << ":" << __LINE__ << ": "
Functions
static void science_room (map *m, const point &p1, const point &p2, int z, int rotate)
void calculate_mapgen_weights ()
void check_mapgen_definitions ()
static void set_mapgen_defer (const JsonObject &jsi, const std::string &member, const std::string &message)
std::shared_ptr< mapgen_function > load_mapgen_function (const JsonObject &jio, const std::string &id_base, const point &offset, const point &total)
void load_and_add_mapgen_function (const JsonObject &jio, const std::string &id_base, const point &offset, const point &total)
static void load_nested_mapgen (const JsonObject &jio, const nested_mapgen_id &id_base)
static void load_update_mapgen (const JsonObject &jio, const update_mapgen_id &id_base)
void load_mapgen (const JsonObject &jo)
void reset_mapgens ()
static bool common_check_bounds (const jmapgen_int &x, const jmapgen_int &y, const jmapgen_int &z, const point &mapgensize, const JsonObject &jso)
template<typename T >
static bool is_null_helper (const string_id< T > &id)
template<typename T >
static bool is_null_helper (const int_id< T > &id)
static bool is_null_helper (const std::string_view)
template<typename T >
static string_id< T > to_string_id_helper (const string_id< T > &id)
template<typename T >
static string_id< T > to_string_id_helper (const int_id< T > &id)
static std::string to_string_id_helper (const std::string &s)
template<typename T >
static bool is_valid_helper (const string_id< T > &id)
template<typename T >
static bool is_valid_helper (const int_id< T > &)
static bool is_valid_helper (const std::string_view)
template<>
std::string io::enum_to_string< jmapgen_flags > (jmapgen_flags v)
template<>
std::string io::enum_to_string< mapgen_parameter_scope > (mapgen_parameter_scope v)
static inclusive_rectangle< point > vehicle_bounds (const vehicle_prototype &vp)
template<typename PieceType >
void load_place_mapings (const JsonObject &jobj, mapgen_palette::placing_map::mapped_type &vect, const std::string &context)
template<typename PieceType >
void load_place_mapings (const JsonValue &value, mapgen_palette::placing_map::mapped_type &vect, const std::string &context)
template<typename PieceType >
void load_place_mapings_string (const JsonValue &value, mapgen_palette::placing_map::mapped_type &vect, const std::string &context)
template<typename PieceType >
void load_place_mapings_alternatively (const JsonValue &value, mapgen_palette::placing_map::mapped_type &vect, const std::string &context)
template<>
void load_place_mapings< jmapgen_trap > (const JsonValue &value, mapgen_palette::placing_map::mapped_type &vect, const std::string &context)
template<>
void load_place_mapings< jmapgen_furniture > (const JsonValue &value, mapgen_palette::placing_map::mapped_type &vect, const std::string &context)
template<>
void load_place_mapings< jmapgen_terrain > (const JsonValue &value, mapgen_palette::placing_map::mapped_type &vect, const std::string &context)
static bool check_furn (const furn_id &id, const std::string &context)
static bool apply_mapgen_in_phases (const mapgendata &md, const std::vector< jmapgen_setmap > &setmap_points, const jmapgen_objects &objects, const tripoint_rel_ms &offset, const std::string &context, bool verify=false)
bool connects_to (const oter_id &there, int dir)
void line (map *m, const ter_id &type, const point &p1, const point &p2, int z)
void line (tinymap *m, const ter_id &type, const point &p1, const point &p2)
void line_furn (map *m, const furn_id &type, const point &p1, const point &p2, int z)
void line_furn (tinymap *m, const furn_id &type, const point &p1, const point &p2)
void fill_background (map *m, const ter_id &type)
void fill_background (map *m, ter_id(*f)())
void square (map *m, const ter_id &type, const point &p1, const point &p2)
void square_furn (map *m, const furn_id &type, const point &p1, const point &p2)
void square_furn (tinymap *m, const furn_id &type, const point &p1, const point &p2)
void square (map *m, ter_id(*f)(), const point &p1, const point &p2)
void square (map *m, const weighted_int_list< ter_id > &f, const point &p1, const point &p2)
void rough_circle (map *m, const ter_id &type, const point &p, int rad)
void rough_circle_furn (map *m, const furn_id &type, const point &p, int rad)
void circle (map *m, const ter_id &type, double x, double y, double rad)
void circle (map *m, const ter_id &type, const point &p, int rad)
void circle_furn (map *m, const furn_id &type, const point &p, int rad)
void add_corpse (map *m, const point &p)
void check_mapgen_consistent_with (const std::string &key, const oter_t &ter)
Verify that the properties of a particular mapgen match the properties of its overmap_terrain.
mapgen_update_func add_mapgen_update_func (const JsonObject &jo, bool &defer)
bool run_mapgen_update_func (const update_mapgen_id &update_mapgen_id, const tripoint_abs_omt &omt_pos, const mapgen_arguments &args, mission *miss, bool cancel_on_collision, bool mirror_horizontal, bool mirror_vertical, int rotation)
bool run_mapgen_update_func (const update_mapgen_id &update_mapgen_id, mapgendata &dat, const bool cancel_on_collision)
void set_queued_points ()
bool apply_construction_marker (const update_mapgen_id &update_mapgen_id, const tripoint_abs_omt &omt_pos, const mapgen_arguments &args, bool mirror_horizontal, bool mirror_vertical, int rotation, bool apply)
std::pair< std::map< ter_id, int >, std::map< furn_id, int > > get_changed_ids_from_update (const update_mapgen_id &update_mapgen_id, const mapgen_arguments &mapgen_args, ter_id const &base_ter)
bool run_mapgen_func (const std::string &mapgen_id, mapgendata &dat)
mapgen_parameters get_map_special_params (const std::string &mapgen_id)
int register_mapgen_function (const std::string &key)
Attempts to register the built-in function key as mapgen for the overmap terrain key.
bool has_mapgen_for (const std::string &key)
Check that key is present in oter_mapgen.
bool has_update_mapgen_for (const update_mapgen_id &key)
Check whether key is a valid update_mapgen id.
Variables
static const furn_str_id furn_f_bed ("f_bed")
static const furn_str_id furn_f_console ("f_console")
static const furn_str_id furn_f_counter ("f_counter")
static const furn_str_id furn_f_dresser ("f_dresser")
static const furn_str_id furn_f_flower_fungal ("f_flower_fungal")
static const furn_str_id furn_f_fridge ("f_fridge")
static const furn_str_id furn_f_fungal_clump ("f_fungal_clump")
static const furn_str_id furn_f_rack ("f_rack")
static const furn_str_id furn_f_rubble ("f_rubble")
static const furn_str_id furn_f_rubble_rock ("f_rubble_rock")
static const furn_str_id furn_f_sign ("f_sign")
static const furn_str_id furn_f_table ("f_table")
static const furn_str_id furn_f_toilet ("f_toilet")
static const furn_str_id furn_f_vending_c ("f_vending_c")
static const furn_str_id furn_f_vending_o ("f_vending_o")
static const furn_str_id furn_f_vending_reinforced ("f_vending_reinforced")
static const item_group_id Item_spawn_data_ammo_rare ("ammo_rare")
static const item_group_id Item_spawn_data_bed ("bed")
static const item_group_id Item_spawn_data_bionics ("bionics")
static const item_group_id Item_spawn_data_bionics_common ("bionics_common")
static const item_group_id Item_spawn_data_chem_lab ("chem_lab")
static const item_group_id Item_spawn_data_cleaning ("cleaning")
static const item_group_id Item_spawn_data_cloning_vat ("cloning_vat")
static const item_group_id Item_spawn_data_dissection ("dissection")
static const item_group_id Item_spawn_data_dresser ("dresser")
static const item_group_id Item_spawn_data_goo ("goo")
static const item_group_id Item_spawn_data_guns_rare ("guns_rare")
static const item_group_id Item_spawn_data_lab_dorm ("lab_dorm")
static const item_group_id Item_spawn_data_mut_lab ("mut_lab")
static const item_group_id Item_spawn_data_sewer ("sewer")
static const item_group_id Item_spawn_data_teleport ("teleport")
static const itype_id itype_avgas ("avgas")
static const itype_id itype_diesel ("diesel")
static const itype_id itype_gasoline ("gasoline")
static const itype_id itype_jp8 ("jp8")
static const mongroup_id GROUP_BREATHER ("GROUP_BREATHER")
static const mongroup_id GROUP_BREATHER_HUB ("GROUP_BREATHER_HUB")
static const mongroup_id GROUP_FUNGI_FUNGALOID ("GROUP_FUNGI_FUNGALOID")
static const mongroup_id GROUP_LAB ("GROUP_LAB")
static const mongroup_id GROUP_LAB_CYBORG ("GROUP_LAB_CYBORG")
static const mongroup_id GROUP_LAB_SECURITY ("GROUP_LAB_SECURITY")
static const mongroup_id GROUP_NETHER ("GROUP_NETHER")
static const mongroup_id GROUP_ROBOT_SECUBOT ("GROUP_ROBOT_SECUBOT")
static const mongroup_id GROUP_SLIME ("GROUP_SLIME")
static const mongroup_id GROUP_TURRET ("GROUP_TURRET")
static const oter_str_id oter_ants_es ("ants_es")
static const oter_str_id oter_ants_esw ("ants_esw")
static const oter_str_id oter_ants_ew ("ants_ew")
static const oter_str_id oter_ants_lab ("ants_lab")
static const oter_str_id oter_ants_lab_stairs ("ants_lab_stairs")
static const oter_str_id oter_ants_ne ("ants_ne")
static const oter_str_id oter_ants_nes ("ants_nes")
static const oter_str_id oter_ants_nesw ("ants_nesw")
static const oter_str_id oter_ants_new ("ants_new")
static const oter_str_id oter_ants_ns ("ants_ns")
static const oter_str_id oter_ants_nsw ("ants_nsw")
static const oter_str_id oter_ants_sw ("ants_sw")
static const oter_str_id oter_ants_wn ("ants_wn")
static const oter_str_id oter_central_lab ("central_lab")
static const oter_str_id oter_central_lab_core ("central_lab_core")
static const oter_str_id oter_central_lab_finale ("central_lab_finale")
static const oter_str_id oter_central_lab_stairs ("central_lab_stairs")
static const oter_str_id oter_ice_lab ("ice_lab")
static const oter_str_id oter_ice_lab_core ("ice_lab_core")
static const oter_str_id oter_ice_lab_finale ("ice_lab_finale")
static const oter_str_id oter_ice_lab_stairs ("ice_lab_stairs")
static const oter_str_id oter_lab ("lab")
static const oter_str_id oter_lab_core ("lab_core")
static const oter_str_id oter_lab_finale ("lab_finale")
static const oter_str_id oter_lab_stairs ("lab_stairs")
static const oter_str_id oter_slimepit ("slimepit")
static const oter_str_id oter_slimepit_bottom ("slimepit_bottom")
static const oter_str_id oter_slimepit_down ("slimepit_down")
static const oter_str_id oter_tower_lab ("tower_lab")
static const oter_str_id oter_tower_lab_finale ("tower_lab_finale")
static const oter_str_id oter_tower_lab_stairs ("tower_lab_stairs")
static const oter_type_str_id oter_type_road ("road")
static const oter_type_str_id oter_type_sewer ("sewer")
static const ter_str_id ter_t_bars ("t_bars")
static const ter_str_id ter_t_card_science ("t_card_science")
static const ter_str_id ter_t_concrete_wall ("t_concrete_wall")
static const ter_str_id ter_t_cvdbody ("t_cvdbody")
static const ter_str_id ter_t_cvdmachine ("t_cvdmachine")
static const ter_str_id ter_t_dirt ("t_dirt")
static const ter_str_id ter_t_door_glass_frosted_c ("t_door_glass_frosted_c")
static const ter_str_id ter_t_door_metal_c ("t_door_metal_c")
static const ter_str_id ter_t_door_metal_locked ("t_door_metal_locked")
static const ter_str_id ter_t_floor ("t_floor")
static const ter_str_id ter_t_fungus_floor_in ("t_fungus_floor_in")
static const ter_str_id ter_t_fungus_wall ("t_fungus_wall")
static const ter_str_id ter_t_grass ("t_grass")
static const ter_str_id ter_t_marloss ("t_marloss")
static const ter_str_id ter_t_radio_tower ("t_radio_tower")
static const ter_str_id ter_t_reinforced_door_glass_c ("t_reinforced_door_glass_c")
static const ter_str_id ter_t_reinforced_glass ("t_reinforced_glass")
static const ter_str_id ter_t_rock_floor ("t_rock_floor")
static const ter_str_id ter_t_sewage ("t_sewage")
static const ter_str_id ter_t_slime ("t_slime")
static const ter_str_id ter_t_slope_down ("t_slope_down")
static const ter_str_id ter_t_slope_up ("t_slope_up")
static const ter_str_id ter_t_stairs_down ("t_stairs_down")
static const ter_str_id ter_t_stairs_up ("t_stairs_up")
static const ter_str_id ter_t_strconc_floor ("t_strconc_floor")
static const ter_str_id ter_t_thconc_floor ("t_thconc_floor")
static const ter_str_id ter_t_thconc_floor_olight ("t_thconc_floor_olight")
static const ter_str_id ter_t_vat ("t_vat")
static const ter_str_id ter_t_water_sh ("t_water_sh")
static const trait_id trait_NPC_STATIC_NPC ("NPC_STATIC_NPC")
static const vproto_id vehicle_prototype_shopping_cart ("shopping_cart")
static constexpr int MON_RADIUS = 3
static mapgen_factory oter_mapgen
std::map< nested_mapgen_id, nested_mapgen > nested_mapgens
std::map< update_mapgen_id, update_mapgen > update_mapgens
static std::unordered_map< std::string, tripoint_abs_ms > queued_points
static std::string mapgen_defer::member
static std::string mapgen_defer::message
static bool mapgen_defer::defer
static JsonObject mapgen_defer::jsi
static std::map< palette_id, mapgen_palette > palettes
static const phase_comparator compare_phases {}
static const int SOUTH_EDGE = 2 * SEEY - 1
static const int EAST_EDGE = 2 * SEEX - 1
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x),D_MAP_GEN) << __FILE__ << ":" << __LINE__ << ": "
Definition at line 203 of file mapgen.cpp.
Function Documentation
add_corpse()
void add_corpse (map * m, const point & p)
Definition at line 7785 of file mapgen.cpp.
 {
     m->add_corpse( tripoint( p, m->get_abs_sub().z() ) );
 }
References map::add_corpse(), map::get_abs_sub(), tripoint, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
add_mapgen_update_func()
mapgen_update_func add_mapgen_update_func (const JsonObject & jo, bool & defer)
Definition at line 7898 of file mapgen.cpp.
 {
     if( jo.has_string( "mapgen_update_id" ) ) {
         const update_mapgen_id mapgen_update_id{ jo.get_string( "mapgen_update_id" ) };
         const auto update_function = [mapgen_update_id]( const tripoint_abs_omt & omt_pos,
         mission * miss ) {
             run_mapgen_update_func( mapgen_update_id, omt_pos, {}, miss, false );
         };
         return update_function;
     }
     update_mapgen_function_json json_data( {},
                                            "unknown object in add_mapgen_update_func" );
     mapgen_defer::defer = defer;
     if( !json_data.setup_update( jo ) ) {
         const auto null_function = []( const tripoint_abs_omt &, mission * ) {
         };
         return null_function;
     }
     const auto update_function = [json_data]( const tripoint_abs_omt & omt_pos, mission * miss ) {
         json_data.update_map( omt_pos, {}, tripoint_rel_ms( tripoint_zero ), miss );
     };
     defer = mapgen_defer::defer;
     mapgen_defer::jsi = JsonObject();
     return update_function;
 }
References mapgen_defer::defer, JsonObject::get_string(), JsonObject::has_string(), mapgen_defer::jsi, run_mapgen_update_func(), and tripoint_zero.
Referenced by mission_util::set_update_mapgen().
apply_construction_marker()
bool apply_construction_marker (const update_mapgen_id & update_mapgen_id, const tripoint_abs_omt & omt_pos, const mapgen_arguments & args, bool mirror_horizontal, bool mirror_vertical, int rotation, bool apply)
Definition at line 7960 of file mapgen.cpp.
 {
     const auto update_function = update_mapgens.find( update_mapgen_id );
     if( update_function == update_mapgens.end() || update_function->second.funcs().empty() ) {
         return false;
     }
     fake_map tmp_map( ter_t_grass );
     mapgendata base_fake_md( *tmp_map.cast_to_map(), mapgendata::dummy_settings );
     mapgendata fake_md( base_fake_md, args );
     fake_md.skip = { mapgen_phase::zones };
     std::unique_ptr<tinymap> p_update_tmap = std::make_unique<tinymap>();
     tinymap &update_tmap = *p_update_tmap;
     update_tmap.load( omt_pos, true );
     update_tmap.rotate( 4 - rotation );
     update_tmap.mirror( mirror_horizontal, mirror_vertical );
     {
         // Make sure rot goes out of scope and its destructor restores the map before the
         // "outer scope" mirroring/rotation is undone. It's unlikely inherent map rotation will
         // be present at the same time as construction rotation/mirroring is, but better safe than sorry.
         mapgendata md_base( omt_pos, *update_tmap.cast_to_map(), 0.0f, calendar::start_of_cataclysm,
                             nullptr );
         mapgendata md( md_base, args );
         rotation_guard rot( md );
         if( update_function->second.funcs()[0]->update_map( fake_md ) ) {
             for( const tripoint &pos : tmp_map.points_on_zlevel( fake_map::fake_map_z ) ) {
                 const tripoint level_pos = tripoint( pos.xy(), omt_pos.z() );
                 if( tmp_map.ter( pos ) != ter_t_grass || tmp_map.has_furn( level_pos ) ) {
                     if( apply ) {
                         update_tmap.add_field( level_pos, fd_construction_site, 1, time_duration::from_turns( 0 ), false );
                     } else {
                         update_tmap.delete_field( level_pos, fd_construction_site );
                     }
                 }
             }
         }
     }
     update_tmap.mirror( mirror_horizontal, mirror_vertical );
     update_tmap.rotate( rotation );
     return true;
 }
References tinymap::add_field(), apply(), tinymap::cast_to_map(), tinymap::delete_field(), mapgendata::dummy_settings, fake_map::fake_map_z, fd_construction_site, time_duration::from_turns(), tinymap::has_furn(), tinymap::load(), tinymap::mirror(), tinymap::points_on_zlevel(), math_opers::pos(), tinymap::rotate(), mapgendata::skip, calendar::start_of_cataclysm, tinymap::ter(), ter_t_grass, update_mapgens, coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and zones.
Referenced by apply_fortifications(), basecamp::common_salt_water_pipe_construction(), basecamp::salt_water_pipe_return(), basecamp::salt_water_pipe_swamp_return(), basecamp::start_upgrade(), and basecamp::upgrade_return().
apply_mapgen_in_phases()
static bool apply_mapgen_in_phases (const mapgendata & md, const std::vector< jmapgen_setmap > & setmap_points, const jmapgen_objects & objects, const tripoint_rel_ms & offset, const std::string & context, bool verify = false) static
Definition at line 5174 of file mapgen.cpp.
 {
     if( verify && objects.has_vehicle_collision( md, offset ) ) {
         return false;
     }
     // We must apply all the mapgen in phases, but the mapgen is split between
     // setmap_points and objects.  So we have to make an outer loop over
     // phases, and apply each type restricted to each phase.
     auto setmap_point = setmap_points.begin();
     for( mapgen_phase phase : all_enum_values<mapgen_phase>() ) {
         if( std::find( md.skip.begin(), md.skip.end(), phase ) != md.skip.end() ) {
             continue;
         }
         for( ; setmap_point != setmap_points.end(); ++setmap_point ) {
             const jmapgen_setmap &elem = *setmap_point;
             if( elem.phase() != phase ) {
                 break;
             }
             if( verify && elem.has_vehicle_collision( md, offset ) ) {
                 return false;
             }
             elem.apply( md, offset );
         }
         objects.apply( md, phase, offset, context );
     }
     cata_assert( setmap_point == setmap_points.end() );
     resolve_regional_terrain_and_furniture( md );
     return true;
 }
References jmapgen_setmap::apply(), jmapgen_objects::apply(), cata_assert, context, jmapgen_setmap::has_vehicle_collision(), jmapgen_objects::has_vehicle_collision(), jmapgen_setmap::phase(), resolve_regional_terrain_and_furniture(), and mapgendata::skip.
Referenced by mapgen_function_json::generate(), mapgen_function_json_nested::nest(), and update_mapgen_function_json::update_map().
calculate_mapgen_weights()
void calculate_mapgen_weights ()
Definition at line 572 of file mapgen.cpp.
 {
     oter_mapgen.setup();
     // Not really calculate weights, but let's keep it here for now
     for( auto &pr : nested_mapgens ) {
         for( const weighted_object<int, std::shared_ptr<mapgen_function_json_nested>> &ptr :
              pr.second.funcs() ) {
             ptr.obj->setup();
             inp_mngr.pump_events();
         }
     }
     for( auto &pr : update_mapgens ) {
         for( const auto &ptr : pr.second.funcs() ) {
             ptr->setup();
             inp_mngr.pump_events();
         }
     }
     // Having set up all the mapgens we can now perform a second
     // pass of finalizing their parameters
     oter_mapgen.finalize_parameters();
     for( auto &pr : nested_mapgens ) {
         for( const weighted_object<int, std::shared_ptr<mapgen_function_json_nested>> &ptr :
              pr.second.funcs() ) {
             ptr.obj->finalize_parameters();
             inp_mngr.pump_events();
         }
     }
     for( auto &pr : update_mapgens ) {
         for( const auto &ptr : pr.second.funcs() ) {
             ptr->finalize_parameters();
             inp_mngr.pump_events();
         }
     }
 }
References mapgen_factory::finalize_parameters(), inp_mngr, nested_mapgens, oter_mapgen, input_manager::pump_events(), mapgen_factory::setup(), and update_mapgens.
Referenced by DynamicDataLoader::finalize_loaded_data().
check_furn()
static bool check_furn (const furn_id & id, const std::string & context) static
Definition at line 4704 of file mapgen.cpp.
 {
     const furn_t &furn = id.obj();
     if( furn.has_flag( ter_furn_flag::TFLAG_PLANT ) ) {
         debugmsg( "json mapgen for %s specifies furniture %s, which has flag "
                   "PLANT.  Such furniture must be specified in a \"sealed_item\" special.",
                   context, furn.id.str() );
         // Only report once per mapgen object, otherwise the reports are
         // very repetitive
         return true;
     }
     return false;
 }
References context, debugmsg, map_data_common_t::has_flag(), furn_t::id, string_id< T >::str(), and TFLAG_PLANT.
Referenced by mapgen_function_json_base::check_common().
check_mapgen_consistent_with()
void check_mapgen_consistent_with (const std::string & key, const oter_t & ter)
Verify that the properties of a particular mapgen match the properties of its overmap_terrain.
Definition at line 7802 of file mapgen.cpp.
 {
     if( const mapgen_basic_container *container = oter_mapgen.find( key ) ) {
         container->check_consistency_with( ter );
     }
 }
References mapgen_factory::find(), and oter_mapgen.
Referenced by overmap_terrains::check_consistency().
check_mapgen_definitions()
void check_mapgen_definitions ()
Definition at line 607 of file mapgen.cpp.
 {
     oter_mapgen.check_consistency();
     for( const auto &oter_definition : nested_mapgens ) {
         for( const auto &mapgen_function_ptr : oter_definition.second.funcs() ) {
             mapgen_function_ptr.obj->check();
         }
     }
     for( const auto &oter_definition : update_mapgens ) {
         for( const auto &mapgen_function_ptr : oter_definition.second.funcs() ) {
             mapgen_function_ptr->check();
         }
     }
 }
References mapgen_factory::check_consistency(), nested_mapgens, oter_mapgen, and update_mapgens.
Referenced by DynamicDataLoader::check_consistency().
circle() [1/2]
void circle (map * m, const ter_id & type, const point & p, int rad)
Definition at line 7777 of file mapgen.cpp.
 {
     m->draw_circle_ter( type, p, rad );
 }
References map::draw_circle_ter(), and type.
circle() [2/2]
void circle (map * m, const ter_id & type, double x, double y, double rad)
Definition at line 7773 of file mapgen.cpp.
 {
     m->draw_circle_ter( type, rl_vec2d( x, y ), rad );
 }
References map::draw_circle_ter(), and type.
Referenced by chop_tree_activity_actor::finish(), map::get_dir_circle(), and MapExtras::mx_roadworks().
circle_furn()
void circle_furn (map * m, const furn_id & type, const point & p, int rad)
Definition at line 7781 of file mapgen.cpp.
 {
     m->draw_circle_furn( type, p, rad );
 }
References map::draw_circle_furn(), and type.
common_check_bounds()
static bool common_check_bounds (const jmapgen_int & x, const jmapgen_int & y, const jmapgen_int & z, const point & mapgensize, const JsonObject & jso) static
Definition at line 799 of file mapgen.cpp.
 {
     half_open_rectangle<point> bounds( point_zero, mapgensize );
     if( !bounds.contains( point( x.val, y.val ) ) ) {
         return false;
     }
     if( x.valmax < x.val ) {
         jso.throw_error( "x maximum is less than x minimum" );
     }
     if( y.valmax < y.val ) {
         jso.throw_error( "y maximum is less than y minimum" );
     }
     if( z.valmax != z.val ) {
         jso.throw_error( "z maximum has to be identical to z minimum" );
     }
     if( x.valmax > mapgensize.x - 1 ) {
         jso.throw_error_at( "x", "coordinate range cannot cross grid boundaries" );
     }
     if( y.valmax > mapgensize.y - 1 ) {
         jso.throw_error_at( "y", "coordinate range cannot cross grid boundaries" );
     }
     return true;
 }
References half_open_rectangle< Point, >::contains(), point_zero, JsonObject::throw_error(), JsonObject::throw_error_at(), jmapgen_int::val, jmapgen_int::valmax, point::x, and point::y.
Referenced by jmapgen_objects::check_bounds(), and mapgen_function_json_base::check_inbounds().
connects_to()
bool connects_to (const oter_id & there, int dir)
Definition at line 7154 of file mapgen.cpp.
 {
     switch( dir ) {
         // South
         case 2:
             if( there == oter_ants_ns || there == oter_ants_es ||
                 there == oter_ants_sw || there == oter_ants_nes || there == oter_ants_nsw ||
                 there == oter_ants_esw || there == oter_ants_nesw ) {
                 return true;
             }
             return false;
         // West
         case 3:
             if( there == oter_ants_ew || there == oter_ants_sw ||
                 there == oter_ants_wn || there == oter_ants_new || there == oter_ants_nsw ||
                 there == oter_ants_esw || there == oter_ants_nesw ) {
                 return true;
             }
             return false;
         // North
         case 0:
             if( there == oter_ants_ns || there == oter_ants_ne ||
                 there == oter_ants_wn || there == oter_ants_nes || there == oter_ants_new ||
                 there == oter_ants_nsw || there == oter_ants_nesw ) {
                 return true;
             }
             return false;
         // East
         case 1:
             if( there == oter_ants_ew || there == oter_ants_ne ||
                 there == oter_ants_es || there == oter_ants_nes || there == oter_ants_new ||
                 there == oter_ants_esw || there == oter_ants_nesw ) {
                 return true;
             }
             return false;
         default:
             debugmsg( "Connects_to with dir of %d", dir );
             return false;
     }
 }
References debugmsg, oter_ants_es, oter_ants_esw, oter_ants_ew, oter_ants_ne, oter_ants_nes, oter_ants_nesw, oter_ants_new, oter_ants_ns, oter_ants_nsw, oter_ants_sw, and oter_ants_wn.
Referenced by map::draw_lab(), and targeting_graph< T, Wrapper >::generate().
fill_background() [1/2]
void fill_background (map * m, const ter_id & type)
Definition at line 7737 of file mapgen.cpp.
 {
     m->draw_fill_background( type );
 }
References map::draw_fill_background(), and type.
Referenced by map::draw_map(), mapgen_river_center(), mapgen_river_curved(), mapgen_river_curved_not(), mapgen_river_straight(), and mapgen_rock_partial().
fill_background() [2/2]
void fill_background (map * m, ter_id(*)() f)
Definition at line 7741 of file mapgen.cpp.
 {
     m->draw_fill_background( f );
 }
References map::draw_fill_background().
get_changed_ids_from_update()
std::pair<std::map<ter_id, int>, std::map<furn_id, int> > get_changed_ids_from_update (const update_mapgen_id & update_mapgen_id, const mapgen_arguments & mapgen_args, ter_id const & base_ter)
Definition at line 8016 of file mapgen.cpp.
 {
     std::map<ter_id, int> terrains;
     std::map<furn_id, int> furnitures;
     const auto update_function = update_mapgens.find( update_mapgen_id );
     if( update_function == update_mapgens.end() || update_function->second.funcs().empty() ) {
         return std::make_pair( terrains, furnitures );
     }
     fake_map tmp_map( base_ter );
     mapgendata base_fake_md( *tmp_map.cast_to_map(), mapgendata::dummy_settings );
     mapgendata fake_md( base_fake_md, mapgen_args );
     fake_md.skip = { mapgen_phase::zones };
     if( update_function->second.funcs()[0]->update_map( fake_md ) ) {
         for( const tripoint &pos : tmp_map.points_on_zlevel( fake_map::fake_map_z ) ) {
             ter_id ter_at_pos = tmp_map.ter( pos );
             if( ter_at_pos != base_ter ) {
                 terrains[ter_at_pos] += 1;
             }
             if( tmp_map.has_furn( pos ) ) {
                 furn_id furn_at_pos = tmp_map.furn( pos );
                 furnitures[furn_at_pos] += 1;
             }
         }
     }
     return std::make_pair( terrains, furnitures );
 }
References tinymap::cast_to_map(), mapgendata::dummy_settings, fake_map::fake_map_z, tinymap::furn(), tinymap::has_furn(), tinymap::points_on_zlevel(), math_opers::pos(), mapgendata::skip, tinymap::ter(), anonymous_namespace{overmap.cpp}::terrains, update_mapgens, and zones.
Referenced by calculate_all_blueprint_reqs(), and recipe::check_blueprint_requirements().
get_map_special_params()
mapgen_parameters get_map_special_params (const std::string & mapgen_id)
Definition at line 8055 of file mapgen.cpp.
 {
     return oter_mapgen.get_map_special_params( mapgen_id );
 }
References mapgen_factory::get_map_special_params(), and oter_mapgen.
Referenced by fixed_overmap_special_data::finalize_mapgen_parameters(), and mutable_overmap_special_data::finalize_mapgen_parameters().
has_mapgen_for()
bool has_mapgen_for (const std::string & key)
Check that key is present in oter_mapgen.
Definition at line 8068 of file mapgen.cpp.
 {
     return oter_mapgen.has( key );
 }
References mapgen_factory::has(), and oter_mapgen.
Referenced by overmap_terrains::check_consistency().
has_update_mapgen_for()
bool has_update_mapgen_for (const update_mapgen_id & key)
Check whether key is a valid update_mapgen id.
Definition at line 8073 of file mapgen.cpp.
 {
     return update_mapgens.count( key );
 }
References update_mapgens.
Referenced by recipe_dictionary::check_consistency().
is_null_helper() [1/3]
template<typename T > static bool is_null_helper (const int_id< T > & id) static
Definition at line 1132 of file mapgen.cpp.
 {
     return id.id().is_null();
 }
is_null_helper() [2/3]
static bool is_null_helper (const std::string_view) static
Definition at line 1137 of file mapgen.cpp.
 {
     return false;
 }
is_null_helper() [3/3]
template<typename T > static bool is_null_helper (const string_id< T > & id) static
Definition at line 1126 of file mapgen.cpp.
 {
     return id.is_null();
 }
Referenced by mapgen_value< Id >::init_string().
is_valid_helper() [1/3]
template<typename T > static bool is_valid_helper (const int_id< T > &) static
Definition at line 1190 of file mapgen.cpp.
 {
     return true;
 }
is_valid_helper() [2/3]
static bool is_valid_helper (const std::string_view) static
Definition at line 1195 of file mapgen.cpp.
 {
     return true;
 }
is_valid_helper() [3/3]
template<typename T > static bool is_valid_helper (const string_id< T > & id) static
Definition at line 1184 of file mapgen.cpp.
 {
     return id.is_valid();
 }
Referenced by mapgen_value< Id >::id_source::check(), mapgen_value< Id >::distribution_source::check(), and mapgen_value< Id >::switch_source::check().
line() [1/2]
void line (map * m, const ter_id & type, const point & p1, const point & p2, int z)
Definition at line 7721 of file mapgen.cpp.
 {
     m->draw_line_ter( type, p1, p2, z );
 }
References map::draw_line_ter(), and type.
Referenced by add_array_to_set(), append_line(), assign_coverage_from_json(), mattack::boomer(), mattack::boomer_glow(), spell_detail::build_line(), talk_function::commune_refuge_caravan(), construction_menu(), continue_line(), cursorx_to_position(), debug_error_prompt(), Messages::display_messages(), overmap_ui::draw_ascii(), draw_bionics_info(), draw_bionics_tab(), cataimgui::window::draw_colored_text(), draw_effects_info(), draw_effects_tab(), draw_encumbrance_info(), draw_encumbrance_tab(), draw_health_summary(), draw_info_window(), draw_line(), draw_messages(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), draw_proficiencies_info(), draw_proficiencies_tab(), draw_skills_info(), draw_skills_tab(), draw_speed_info(), draw_speed_tab(), draw_spellbook_info(), draw_stats_info(), draw_stats_tab(), draw_traits_info(), draw_traits_tab(), anonymous_namespace{animation.cpp}::draw_zones_curses(), handle_player_display_action(), has_obstruction(), om_lines::has_segment(), insert_table(), om_lines::is_straight(), isDebuggerActive(), line_to(), npc_template::load(), load_map_bash_tent_centers(), load_mapgen(), load_overmap_feature_flag_settings(), load_world_option(), mapgen_ravine_edge(), mapgen_river_curved(), mapgen_river_straight(), move_along_line(), MapExtras::mx_minefield(), anonymous_namespace{flexbuffer_cache.cpp}::parse_json_to_flexbuffer_(), print_ranged_chance(), realDebugmsg(), right_print(), om_lines::rotate(), scrollable_text(), select_crafter_and_crafting_recipe(), repetition_folder::set(), set_description(), om_lines::set_segment(), Messages::dialog::show(), skip_skill_headers(), slope_of(), repetition_folder::test(), translate_gendered_line(), and iexamine::vending().
line() [2/2]
void line (tinymap * m, const ter_id & type, const point & p1, const point & p2)
Definition at line 7725 of file mapgen.cpp.
 {
     m->draw_line_ter( type, p1, p2 );
 }
References tinymap::draw_line_ter(), and type.
line_furn() [1/2]
void line_furn (map * m, const furn_id & type, const point & p1, const point & p2, int z)
Definition at line 7729 of file mapgen.cpp.
 {
     m->draw_line_furn( type, p1, p2, z );
 }
References map::draw_line_furn(), and type.
Referenced by MapExtras::mx_minefield(), and MapExtras::mx_roadworks().
line_furn() [2/2]
void line_furn (tinymap * m, const furn_id & type, const point & p1, const point & p2)
Definition at line 7733 of file mapgen.cpp.
 {
     m->draw_line_furn( type, p1, p2 );
 }
References tinymap::draw_line_furn(), and type.
load_and_add_mapgen_function()
void load_and_add_mapgen_function (const JsonObject & jio, const std::string & id_base, const point & offset, const point & total)
Definition at line 679 of file mapgen.cpp.
 {
     std::shared_ptr<mapgen_function> f = load_mapgen_function( jio, id_base, offset, total );
     if( f ) {
         oter_mapgen.add( id_base, f );
     }
 }
References mapgen_factory::add(), load_mapgen_function(), and oter_mapgen.
Referenced by load_mapgen(), and load_overmap_terrain_mapgens().
load_mapgen()
void load_mapgen (const JsonObject & jo)
Definition at line 732 of file mapgen.cpp.
 {
     // NOLINTNEXTLINE(cata-use-named-point-constants)
     static constexpr point point_one( 1, 1 );
     if( jo.has_array( "om_terrain" ) ) {
         JsonArray ja = jo.get_array( "om_terrain" );
         if( ja.test_array() ) {
             point offset;
             point total( ja.get_array( 0 ).size(), ja.size() );
             for( JsonArray row_items : ja ) {
                 for( const std::string mapgenid : row_items ) {
                     load_and_add_mapgen_function( jo, mapgenid, offset, total );
                     offset.x++;
                 }
                 offset.y++;
                 offset.x = 0;
             }
         } else {
             std::vector<std::string> mapgenid_list;
             for( const std::string line : ja ) {
                 mapgenid_list.push_back( line );
             }
             if( !mapgenid_list.empty() ) {
                 const std::string mapgenid = mapgenid_list[0];
                 const auto mgfunc = load_mapgen_function( jo, mapgenid, point_zero, point_one );
                 if( mgfunc ) {
                     for( auto &i : mapgenid_list ) {
                         oter_mapgen.add( i, mgfunc );
                     }
                 }
             }
         }
     } else if( jo.has_string( "om_terrain" ) ) {
         load_and_add_mapgen_function( jo, jo.get_string( "om_terrain" ), point_zero, point_one );
     } else if( jo.has_string( "nested_mapgen_id" ) ) {
         load_nested_mapgen( jo, nested_mapgen_id( jo.get_string( "nested_mapgen_id" ) ) );
     } else if( jo.has_string( "update_mapgen_id" ) ) {
         load_update_mapgen( jo, update_mapgen_id( jo.get_string( "update_mapgen_id" ) ) );
     } else {
         debugmsg( "mapgen entry requires \"om_terrain\" or \"nested_mapgen_id\"(string, array of strings, or array of array of strings)\n%s\n",
                   jo.str() );
     }
 }
References mapgen_factory::add(), debugmsg, JsonArray::get_array(), JsonObject::get_array(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_string(), line(), load_and_add_mapgen_function(), load_mapgen_function(), load_nested_mapgen(), load_update_mapgen(), oter_mapgen, point_zero, JsonArray::size(), JsonObject::str(), JsonArray::test_array(), point::x, and point::y.
Referenced by DynamicDataLoader::initialize().
load_mapgen_function()
std::shared_ptr<mapgen_function> load_mapgen_function (const JsonObject & jio, const std::string & id_base, const point & offset, const point & total)
Definition at line 650 of file mapgen.cpp.
 {
     dbl_or_var weight = get_dbl_or_var( jio, "weight", false,  1000 );
     if( jio.get_bool( "disabled", false ) ) {
         jio.allow_omitted_members();
         return nullptr; // nothing
     }
     const std::string mgtype = jio.get_string( "method" );
     if( mgtype == "builtin" ) {
         if( const building_gen_pointer ptr = get_mapgen_cfunction( jio.get_string( "name" ) ) ) {
             return std::make_shared<mapgen_function_builtin>( ptr, std::move( weight ) );
         } else {
             jio.throw_error_at( "name", "function does not exist" );
         }
     } else if( mgtype == "json" ) {
         if( !jio.has_object( "object" ) ) {
             jio.throw_error( R"(mapgen with method "json" must define key "object")" );
         }
         JsonObject jo = jio.get_object( "object" );
         jo.allow_omitted_members();
         return std::make_shared<mapgen_function_json>(
                    jo, std::move( weight ), "mapgen " + id_base, offset, total );
     } else {
         jio.throw_error_at( "method", R"(invalid value: must be "builtin" or "json")" );
     }
 }
References JsonObject::allow_omitted_members(), JsonObject::get_bool(), get_dbl_or_var(), get_mapgen_cfunction(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_object(), JsonObject::throw_error(), and JsonObject::throw_error_at().
Referenced by load_and_add_mapgen_function(), and load_mapgen().
load_nested_mapgen()
static void load_nested_mapgen (const JsonObject & jio, const nested_mapgen_id & id_base) static
Definition at line 688 of file mapgen.cpp.
 {
     const std::string mgtype = jio.get_string( "method" );
     if( mgtype == "json" ) {
         if( jio.has_object( "object" ) ) {
             int weight = jio.get_int( "weight", 1000 );
             JsonObject jo = jio.get_object( "object" );
             jo.allow_omitted_members();
             nested_mapgens[id_base].add(
                 std::make_shared<mapgen_function_json_nested>(
                     jo, "nested mapgen " + id_base.str() ),
                 weight );
         } else {
             debugmsg( "Nested mapgen: Invalid mapgen function (missing \"object\" object)", id_base.c_str() );
         }
     } else {
         debugmsg( "Nested mapgen: type for id %s was %s, but nested mapgen only supports \"json\"",
                   id_base.c_str(), mgtype.c_str() );
     }
 }
References JsonObject::allow_omitted_members(), string_id< T >::c_str(), debugmsg, JsonObject::get_int(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_object(), nested_mapgens, and string_id< T >::str().
Referenced by load_mapgen().
load_place_mapings() [1/2]
template<typename PieceType > void load_place_mapings (const JsonObject & jobj, mapgen_palette::placing_map::mapped_type & vect, const std::string & context)
Definition at line 3994 of file mapgen.cpp.
 {
     vect.push_back( make_shared_fast<PieceType>( jobj, context ) );
 }
References context.
load_place_mapings() [2/2]
template<typename PieceType > void load_place_mapings (const JsonValue & value, mapgen_palette::placing_map::mapped_type & vect, const std::string & context)
Definition at line 4009 of file mapgen.cpp.
 {
     if( value.test_object() ) {
         load_place_mapings<PieceType>( value.get_object(), vect, context );
     } else {
         for( JsonObject jo : value.get_array() ) {
             load_place_mapings<PieceType>( jo, vect, context );
             jo.allow_omitted_members();
         }
     }
 }
References context, JsonValue::get_array(), JsonValue::get_object(), and JsonValue::test_object().
load_place_mapings< jmapgen_furniture >()
template<> void load_place_mapings< jmapgen_furniture > (const JsonValue & value, mapgen_palette::placing_map::mapped_type & vect, const std::string & context)
Definition at line 4120 of file mapgen.cpp.
 {
     load_place_mapings_alternatively<jmapgen_furniture>( value, vect, context );
 }
References context.
load_place_mapings< jmapgen_terrain >()
template<> void load_place_mapings< jmapgen_terrain > (const JsonValue & value, mapgen_palette::placing_map::mapped_type & vect, const std::string & context)
Definition at line 4127 of file mapgen.cpp.
 {
     load_place_mapings_alternatively<jmapgen_terrain>( value, vect, context );
 }
References context.
load_place_mapings< jmapgen_trap >()
template<> void load_place_mapings< jmapgen_trap > (const JsonValue & value, mapgen_palette::placing_map::mapped_type & vect, const std::string & context)
Definition at line 4112 of file mapgen.cpp.
 {
     load_place_mapings_alternatively<jmapgen_trap>( value, vect, context );
 }
References context.
load_place_mapings_alternatively()
template<typename PieceType > void load_place_mapings_alternatively (const JsonValue & value, mapgen_palette::placing_map::mapped_type & vect, const std::string & context)
Definition at line 4058 of file mapgen.cpp.
 {
     if( !value.test_array() ) {
         load_place_mapings_string<PieceType>( value, vect, context );
     } else {
         auto alter = make_shared_fast< jmapgen_alternatively<PieceType> >();
         for( const JsonValue entry : value.get_array() ) {
             if( entry.test_string() ) {
                 try {
                     alter->alternatives.emplace_back( entry );
                 } catch( const std::runtime_error &err ) {
                     // Using the json object here adds nice formatting and context information
                     entry.throw_error( err.what() );
                 }
             } else if( entry.test_object() ) {
                 JsonObject jsi = entry.get_object();
                 alter->alternatives.emplace_back( jsi, context );
             } else if( entry.test_array() ) {
                 // If this is an array, it means it is an entry followed by a desired total count of instances.
                 JsonArray piece_and_count_jarr = entry.get_array();
                 if( piece_and_count_jarr.size() != 2 ) {
                     piece_and_count_jarr.throw_error( "Array must have exactly two entries: the object, then the count." );
                 }
                 // Test if this is a string or object, and then just emplace it.
                 if( piece_and_count_jarr.test_string() || piece_and_count_jarr.test_object() ) {
                     try {
                         alter->alternatives.emplace_back( piece_and_count_jarr.next_value() );
                     } catch( const std::runtime_error &err ) {
                         piece_and_count_jarr.throw_error( err.what() );
                     }
                 } else {
                     piece_and_count_jarr.throw_error( "First entry must be a string or object." );
                 }
                 if( piece_and_count_jarr.test_int() ) {
                     // We already emplaced the first instance, so do one less.
                     int repeat = std::max( 0, piece_and_count_jarr.next_int() - 1 );
                     PieceType piece_to_repeat = alter->alternatives.back();
                     for( int i = 0; i < repeat; i++ ) {
                         alter->alternatives.emplace_back( piece_to_repeat );
                     }
                 } else {
                     piece_and_count_jarr.throw_error( "Second entry must be an integer." );
                 }
             }
         }
         vect.push_back( alter );
     }
 }
References context, JsonValue::get_array(), JsonArray::get_array(), JsonObject::get_object(), mapgen_defer::jsi, max(), JsonArray::next_int(), JsonArray::next_value(), JsonArray::size(), JsonValue::test_array(), JsonArray::test_int(), JsonArray::test_object(), JsonArray::test_string(), and JsonArray::throw_error().
load_place_mapings_string()
template<typename PieceType > void load_place_mapings_string (const JsonValue & value, mapgen_palette::placing_map::mapped_type & vect, const std::string & context)
Definition at line 4026 of file mapgen.cpp.
 {
     if( value.test_string() || value.test_object() ) {
         try {
             vect.push_back( make_shared_fast<PieceType>( value ) );
         } catch( const std::runtime_error &err ) {
             // Using the json object here adds nice formatting and context information
             value.throw_error( err.what() );
         }
     } else {
         for( const JsonValue entry : value.get_array() ) {
             if( entry.test_string() ) {
                 try {
                     vect.push_back( make_shared_fast<PieceType>( entry ) );
                 } catch( const std::runtime_error &err ) {
                     // Using the json object here adds nice formatting and context information
                     entry.throw_error( err.what() );
                 }
             } else {
                 load_place_mapings<PieceType>( entry.get_object(), vect, context );
             }
         }
     }
 }
References context, JsonValue::get_array(), JsonValue::test_object(), JsonValue::test_string(), and JsonValue::throw_error().
load_update_mapgen()
static void load_update_mapgen (const JsonObject & jio, const update_mapgen_id & id_base) static
Definition at line 709 of file mapgen.cpp.
 {
     const std::string mgtype = jio.get_string( "method" );
     if( mgtype == "json" ) {
         if( jio.has_object( "object" ) ) {
             JsonObject jo = jio.get_object( "object" );
             jo.allow_omitted_members();
             update_mapgens[id_base].add(
                 std::make_unique<update_mapgen_function_json>(
                     jo, "update mapgen " + id_base.str() ) );
         } else {
             debugmsg( "Update mapgen: Invalid mapgen function (missing \"object\" object)",
                       id_base.c_str() );
         }
     } else {
         debugmsg( "Update mapgen: type for id %s was %s, but update mapgen only supports \"json\"",
                   id_base.c_str(), mgtype.c_str() );
     }
 }
References JsonObject::allow_omitted_members(), string_id< T >::c_str(), debugmsg, JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_object(), string_id< T >::str(), and update_mapgens.
Referenced by load_mapgen().
register_mapgen_function()
int register_mapgen_function (const std::string & key)
Attempts to register the built-in function key as mapgen for the overmap terrain key.
If there is no matching function, it does nothing (no error message) and returns -1. Otherwise it returns the index of the added entry in the vector of oter_mapgen.
Definition at line 8060 of file mapgen.cpp.
 {
     if( const building_gen_pointer ptr = get_mapgen_cfunction( key ) ) {
         return oter_mapgen.add( key, std::make_shared<mapgen_function_builtin>( ptr ) );
     }
     return -1;
 }
References mapgen_factory::add(), get_mapgen_cfunction(), and oter_mapgen.
Referenced by load_overmap_terrain_mapgens().
reset_mapgens()
void reset_mapgens ()
Definition at line 777 of file mapgen.cpp.
 {
     oter_mapgen.reset();
     nested_mapgens.clear();
     update_mapgens.clear();
 }
References nested_mapgens, oter_mapgen, mapgen_factory::reset(), and update_mapgens.
Referenced by DynamicDataLoader::unload_data().
rough_circle()
void rough_circle (map * m, const ter_id & type, const point & p, int rad)
Definition at line 7765 of file mapgen.cpp.
 {
     m->draw_rough_circle_ter( type, p, rad );
 }
References map::draw_rough_circle_ter(), and type.
Referenced by map::create_anomaly(), and MapExtras::mx_roadworks().
rough_circle_furn()
void rough_circle_furn (map * m, const furn_id & type, const point & p, int rad)
Definition at line 7769 of file mapgen.cpp.
 {
     m->draw_rough_circle_furn( type, p, rad );
 }
References map::draw_rough_circle_furn(), and type.
Referenced by map::create_anomaly().
run_mapgen_func()
bool run_mapgen_func (const std::string & mapgen_id, mapgendata & dat)
Definition at line 8050 of file mapgen.cpp.
 {
     return oter_mapgen.generate( dat, mapgen_id );
 }
References mapgen_factory::generate(), and oter_mapgen.
Referenced by MapExtras::apply_function(), map::draw_map(), farm_action(), mapgen_function_json::generate(), mapgen_lake_shore(), mapgen_ocean_shore(), and mapgen_ravine_edge().
run_mapgen_update_func() [1/2]
bool run_mapgen_update_func (const update_mapgen_id & update_mapgen_id, const tripoint_abs_omt & omt_pos, const mapgen_arguments & args, mission * miss, bool cancel_on_collision, bool mirror_horizontal, bool mirror_vertical, int rotation)
Definition at line 7925 of file mapgen.cpp.
 {
     const auto update_function = update_mapgens.find( update_mapgen_id );
     if( update_function == update_mapgens.end() || update_function->second.funcs().empty() ) {
         return false;
     }
     return update_function->second.funcs()[0]->update_map(
                omt_pos, args, tripoint_rel_ms( tripoint_zero ), miss, cancel_on_collision, mirror_horizontal,
                mirror_vertical, rotation );
 }
References tripoint_zero, and update_mapgens.
Referenced by timed_event::actualize(), add_mapgen_update_func(), cardreader_examine_actor::apply(), apply_fortifications(), MapExtras::apply_function(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), trapfunc::map_regen(), basecamp::salt_water_pipe_return(), basecamp::salt_water_pipe_swamp_return(), talk_function::start_camp(), basecamp::survey_return(), and basecamp::upgrade_return().
run_mapgen_update_func() [2/2]
bool run_mapgen_update_func (const update_mapgen_id & update_mapgen_id, mapgendata & dat, const bool cancel_on_collision)
Definition at line 7940 of file mapgen.cpp.
 {
     const auto update_function = update_mapgens.find( update_mapgen_id );
     if( update_function == update_mapgens.end() || update_function->second.funcs().empty() ) {
         return false;
     }
     return update_function->second.funcs()[0]->update_map( dat, tripoint_rel_ms( tripoint_zero ),
             cancel_on_collision );
 }
References tripoint_zero, and update_mapgens.
science_room()
void science_room (map * m, const point & p1, const point & p2, int z, int rotate) static
Definition at line 7195 of file mapgen.cpp.
 {
     int height = p2.y - p1.y;
     int width  = p2.x - p1.x;
     if( rotate % 2 == 1 ) { // Swap width & height if we're a lateral room
         int tmp = height;
         height  = width;
         width   = tmp;
     }
     for( int i = p1.x; i <= p2.x; i++ ) {
         for( int j = p1.y; j <= p2.y; j++ ) {
             m->ter_set( point( i, j ), ter_t_thconc_floor );
         }
     }
     int area = height * width;
     std::vector<room_type> valid_rooms;
     if( height < 5 && width < 5 ) {
         valid_rooms.push_back( room_closet );
     }
     if( height > 6 && width > 3 ) {
         valid_rooms.push_back( room_lobby );
     }
     if( height > 4 || width > 4 ) {
         valid_rooms.push_back( room_chemistry );
         valid_rooms.push_back( room_goo );
     }
     if( z != 0 && ( height > 7 || width > 7 ) && height > 2 && width > 2 ) {
         valid_rooms.push_back( room_teleport );
     }
     if( height > 7 && width > 7 ) {
         valid_rooms.push_back( room_bionics );
         valid_rooms.push_back( room_cloning );
     }
     if( area >= 9 ) {
         valid_rooms.push_back( room_vivisect );
     }
     if( height > 5 && width > 4 ) {
         valid_rooms.push_back( room_dorm );
     }
     if( width > 8 ) {
         for( int i = 8; i < width; i += rng( 1, 2 ) ) {
             valid_rooms.push_back( room_split );
         }
     }
     tripoint_bub_ms trap( rng( p1.x + 1, p2.x - 1 ), rng( p1.y + 1, p2.y - 1 ), z );
     switch( random_entry( valid_rooms ) ) {
         case room_closet:
             m->place_items( Item_spawn_data_cleaning, 80, p1, p2, z, false,
                             calendar::start_of_cataclysm );
             break;
         case room_lobby:
             if( rotate % 2 == 0 ) { // Vertical
                 int desk = p1.y + rng( static_cast<int>( height / 2 ) - static_cast<int>( height / 4 ),
                                        static_cast<int>( height / 2 ) + 1 );
                 for( int x = p1.x + static_cast<int>( width / 4 ); x < p2.x - static_cast<int>( width / 4 ); x++ ) {
                     m->furn_set( point( x, desk ), furn_f_counter );
                 }
                 computer *tmpcomp = m->add_computer( tripoint( p2.x - static_cast<int>( width / 4 ), desk, z ),
                                                      _( "Log Console" ), 3 );
                 tmpcomp->add_option( _( "View Research Logs" ), COMPACT_RESEARCH, 0 );
                 tmpcomp->add_option( _( "Download Map Data" ), COMPACT_MAPS, 0 );
                 tmpcomp->add_failure( COMPFAIL_SHUTDOWN );
                 tmpcomp->add_failure( COMPFAIL_ALARM );
                 tmpcomp->add_failure( COMPFAIL_DAMAGE );
                 m->place_spawns( GROUP_LAB_SECURITY, 1,
                                  point_bub_ms( static_cast<int>( ( p1.x + p2.x ) / 2 ), desk ),
                                  point_bub_ms( static_cast<int>( ( p1.x + p2.x ) / 2 ), desk ), z, 1, true );
             } else {
                 int desk = p1.x + rng( static_cast<int>( height / 2 ) - static_cast<int>( height / 4 ),
                                        static_cast<int>( height / 2 ) + 1 );
                 for( int y = p1.y + static_cast<int>( width / 4 ); y < p2.y - static_cast<int>( width / 4 ); y++ ) {
                     m->furn_set( point( desk, y ), furn_f_counter );
                 }
                 computer *tmpcomp = m->add_computer( tripoint( desk, p2.y - static_cast<int>( width / 4 ), z ),
                                                      _( "Log Console" ), 3 );
                 tmpcomp->add_option( _( "View Research Logs" ), COMPACT_RESEARCH, 0 );
                 tmpcomp->add_option( _( "Download Map Data" ), COMPACT_MAPS, 0 );
                 tmpcomp->add_failure( COMPFAIL_SHUTDOWN );
                 tmpcomp->add_failure( COMPFAIL_ALARM );
                 tmpcomp->add_failure( COMPFAIL_DAMAGE );
                 m->place_spawns( GROUP_LAB_SECURITY, 1,
                                  point_bub_ms( desk, static_cast<int>( ( p1.y + p2.y ) / 2 ) ),
                                  point_bub_ms( desk, static_cast<int>( ( p1.y + p2.y ) / 2 ) ), z, 1, true );
             }
             break;
         case room_chemistry:
             if( rotate % 2 == 0 ) { // Vertical
                 for( int x = p1.x; x <= p2.x; x++ ) {
                     if( x % 3 == 0 ) {
                         for( int y = p1.y + 1; y <= p2.y - 1; y++ ) {
                             m->furn_set( point( x, y ), furn_f_counter );
                         }
                         if( one_in( 3 ) ) {
                             m->place_items( Item_spawn_data_mut_lab, 35, point( x, p1.y + 1 ),
                                             point( x, p2.y - 1 ), z, false,
                                             calendar::start_of_cataclysm );
                         } else {
                             m->place_items( Item_spawn_data_chem_lab, 70, point( x, p1.y + 1 ),
                                             point( x, p2.y - 1 ), z, false,
                                             calendar::start_of_cataclysm );
                         }
                     }
                 }
             } else {
                 for( int y = p1.y; y <= p2.y; y++ ) {
                     if( y % 3 == 0 ) {
                         for( int x = p1.x + 1; x <= p2.x - 1; x++ ) {
                             m->furn_set( point( x, y ), furn_f_counter );
                         }
                         if( one_in( 3 ) ) {
                             m->place_items( Item_spawn_data_mut_lab, 35, point( p1.x + 1, y ),
                                             point( p2.x - 1, y ), z, false,
                                             calendar::start_of_cataclysm );
                         } else {
                             m->place_items( Item_spawn_data_chem_lab, 70, point( p1.x + 1, y ),
                                             point( p2.x - 1, y ), z, false,
                                             calendar::start_of_cataclysm );
                         }
                     }
                 }
             }
             break;
         case room_teleport:
             m->furn_set( point( ( p1.x + p2.x ) / 2, static_cast<int>( ( p1.y + p2.y ) / 2 ) ),
                          furn_f_counter );
             m->furn_set( point( static_cast<int>( ( p1.x + p2.x ) / 2 ) + 1,
                                 static_cast<int>( ( p1.y + p2.y ) / 2 ) ),
                          furn_f_counter );
             m->furn_set( point( ( p1.x + p2.x ) / 2, static_cast<int>( ( p1.y + p2.y ) / 2 ) + 1 ),
                          furn_f_counter );
             m->furn_set( point( static_cast<int>( ( p1.x + p2.x ) / 2 ) + 1,
                                 static_cast<int>( ( p1.y + p2.y ) / 2 ) + 1 ),
                          furn_f_counter );
             mtrap_set( m, trap, tr_telepad );
             m->place_items( Item_spawn_data_teleport, 70, point( ( p1.x + p2.x ) / 2,
                             static_cast<int>( ( p1.y + p2.y ) / 2 ) ),
                             point( static_cast<int>( ( p1.x + p2.x ) / 2 ) + 1, static_cast<int>( ( p1.y + p2.y ) / 2 ) + 1 ),
                             z,
                             false,
                             calendar::start_of_cataclysm );
             break;
         case room_goo:
             do {
                 mtrap_set( m, trap, tr_goo );
                 trap.x() = rng( p1.x + 1, p2.x - 1 );
                 trap.y() = rng( p1.y + 1, p2.y - 1 );
             } while( !one_in( 5 ) );
             if( rotate == 0 ) {
                 mremove_trap( m, tripoint_bub_ms( p1.x, p2.y, z ), tr_null );
                 m->furn_set( tripoint_bub_ms( p1.x, p2.y, z ), furn_f_fridge );
                 m->place_items( Item_spawn_data_goo, 60, point( p1.x, p2.y ), point( p1.x, p2.y ), z,
                                 false, calendar::start_of_cataclysm );
             } else if( rotate == 1 ) {
                 mremove_trap( m, tripoint_bub_ms( p1.x, p1.y, z ), tr_null );
                 m->furn_set( tripoint_bub_ms( p1.x, p1.y, z ), furn_f_fridge );
                 m->place_items( Item_spawn_data_goo, 60, p1, p1, z, false,
                                 calendar::start_of_cataclysm );
             } else if( rotate == 2 ) {
                 mremove_trap( m, tripoint_bub_ms( p2.x, p1.y, z ), tr_null );
                 m->furn_set( tripoint_bub_ms( p2.x, p1.y, z ), furn_f_fridge );
                 m->place_items( Item_spawn_data_goo, 60, point( p2.x, p1.y ), point( p2.x, p1.y ), z,
                                 false, calendar::start_of_cataclysm );
             } else {
                 mremove_trap( m, tripoint_bub_ms( p2.x, p2.y, z ), tr_null );
                 m->furn_set( tripoint_bub_ms( p2.x, p2.y, z ), furn_f_fridge );
                 m->place_items( Item_spawn_data_goo, 60, p2, p2, z, false,
                                 calendar::start_of_cataclysm );
             }
             break;
         case room_cloning:
             for( int x = p1.x + 1; x <= p2.x - 1; x++ ) {
                 for( int y = p1.y + 1; y <= p2.y - 1; y++ ) {
                     if( x % 3 == 0 && y % 3 == 0 ) {
                         m->ter_set( tripoint_bub_ms( x, y, z ), ter_t_vat );
                         m->place_items( Item_spawn_data_cloning_vat, 20, point( x, y ),
                                         point( x, y ), z, false, calendar::start_of_cataclysm );
                     }
                 }
             }
             break;
         case room_vivisect:
             if( rotate == 0 ) {
                 for( int x = p1.x; x <= p2.x; x++ ) {
                     m->furn_set( tripoint_bub_ms( x, p2.y - 1, z ), furn_f_counter );
                 }
                 m->place_items( Item_spawn_data_dissection, 80, point( p1.x, p2.y - 1 ),
                                 p2 + point_north, z, false, calendar::start_of_cataclysm );
             } else if( rotate == 1 ) {
                 for( int y = p1.y; y <= p2.y; y++ ) {
                     m->furn_set( tripoint_bub_ms( p1.x + 1, y, z ), furn_f_counter );
                 }
                 m->place_items( Item_spawn_data_dissection, 80, p1 + point_east,
                                 point( p1.x + 1, p2.y ), z, false, calendar::start_of_cataclysm );
             } else if( rotate == 2 ) {
                 for( int x = p1.x; x <= p2.x; x++ ) {
                     m->furn_set( tripoint_bub_ms( x, p1.y + 1, z ), furn_f_counter );
                 }
                 m->place_items( Item_spawn_data_dissection, 80, p1 + point_south,
                                 point( p2.x, p1.y + 1 ), z, false, calendar::start_of_cataclysm );
             } else if( rotate == 3 ) {
                 for( int y = p1.y; y <= p2.y; y++ ) {
                     m->furn_set( tripoint_bub_ms( p2.x - 1, y, z ), furn_f_counter );
                 }
                 m->place_items( Item_spawn_data_dissection, 80, point( p2.x - 1, p1.y ),
                                 p2 + point_west, z, false, calendar::start_of_cataclysm );
             }
             mtrap_set( m, tripoint_bub_ms( ( p1.x + p2.x ) / 2, static_cast<int>( ( p1.y + p2.y ) / 2 ), z ),
                        tr_dissector );
             m->place_spawns( GROUP_LAB_CYBORG, 10,
                              point_bub_ms( static_cast<int>( ( ( p1.x + p2.x ) / 2 ) + 1 ),
                                            static_cast<int>( ( ( p1.y + p2.y ) / 2 ) + 1 ) ),
                              point_bub_ms( static_cast<int>( ( ( p1.x + p2.x ) / 2 ) + 1 ),
                                            static_cast<int>( ( ( p1.y + p2.y ) / 2 ) + 1 ) ), z, 1, true );
             break;
         case room_bionics:
             if( rotate % 2 == 0 ) {
                 point bio( p1.x + 2, static_cast<int>( ( p1.y + p2.y ) / 2 ) );
                 mapf::formatted_set_simple( m, bio + point_north_west,
                                             "---\n"
                                             "|c|\n"
                                             "-=-\n",
                                             mapf::ter_bind( "- | =", ter_t_concrete_wall, ter_t_concrete_wall, ter_t_reinforced_glass ),
                                             mapf::furn_bind( "c", furn_f_counter ) );
                 m->place_items( Item_spawn_data_bionics_common, 70, bio,
                                 bio, z, false, calendar::start_of_cataclysm );
                 m->furn_set( tripoint_bub_ms( bio.x, bio.y + 2, z ), furn_f_console );
                 computer *tmpcomp = m->add_computer( tripoint( bio.x,  bio.y + 2, z ), _( "Bionic access" ), 2 );
                 tmpcomp->add_option( _( "Manifest" ), COMPACT_LIST_BIONICS, 0 );
                 tmpcomp->add_option( _( "Open Chambers" ), COMPACT_RELEASE_BIONICS, 3 );
                 tmpcomp->add_failure( COMPFAIL_MANHACKS );
                 tmpcomp->add_failure( COMPFAIL_SECUBOTS );
                 tmpcomp->set_access_denied_msg(
                     _( "ERROR!  Access denied!  Unauthorized access will be met with lethal force!" ) );
                 bio.x = p2.x - 2;
                 mapf::formatted_set_simple( m, bio + point_north_west,
                                             "-=-\n"
                                             "|c|\n"
                                             "---\n",
                                             mapf::ter_bind( "- | =", ter_t_concrete_wall, ter_t_concrete_wall, ter_t_reinforced_glass ),
                                             mapf::furn_bind( "c", furn_f_counter ) );
                 m->place_items( Item_spawn_data_bionics_common, 70, bio,
                                 bio, z, false, calendar::start_of_cataclysm );
                 m->furn_set( tripoint_bub_ms( bio.x, bio.y - 2, z ), furn_f_console );
                 computer *tmpcomp2 = m->add_computer( tripoint( bio.x,  bio.y - 2, z ), _( "Bionic access" ), 2 );
                 tmpcomp2->add_option( _( "Manifest" ), COMPACT_LIST_BIONICS, 0 );
                 tmpcomp2->add_option( _( "Open Chambers" ), COMPACT_RELEASE_BIONICS, 3 );
                 tmpcomp2->add_failure( COMPFAIL_MANHACKS );
                 tmpcomp2->add_failure( COMPFAIL_SECUBOTS );
                 tmpcomp2->set_access_denied_msg(
                     _( "ERROR!  Access denied!  Unauthorized access will be met with lethal force!" ) );
             } else {
                 int bioy = p1.y + 2;
                 int biox = static_cast<int>( ( p1.x + p2.x ) / 2 );
                 mapf::formatted_set_simple( m, point( biox - 1, bioy - 1 ),
                                             "|-|\n"
                                             "|c=\n"
                                             "|-|\n",
                                             mapf::ter_bind( "- | =", ter_t_concrete_wall, ter_t_concrete_wall, ter_t_reinforced_glass ),
                                             mapf::furn_bind( "c", furn_f_counter ) );
                 m->place_items( Item_spawn_data_bionics_common, 70, point( biox, bioy ),
                                 point( biox, bioy ), z, false, calendar::start_of_cataclysm );
                 m->furn_set( tripoint_bub_ms( biox + 2, bioy, z ), furn_f_console );
                 computer *tmpcomp = m->add_computer( tripoint( biox + 2,  bioy, z ), _( "Bionic access" ), 2 );
                 tmpcomp->add_option( _( "Manifest" ), COMPACT_LIST_BIONICS, 0 );
                 tmpcomp->add_option( _( "Open Chambers" ), COMPACT_RELEASE_BIONICS, 3 );
                 tmpcomp->add_failure( COMPFAIL_MANHACKS );
                 tmpcomp->add_failure( COMPFAIL_SECUBOTS );
                 tmpcomp->set_access_denied_msg(
                     _( "ERROR!  Access denied!  Unauthorized access will be met with lethal force!" ) );
                 bioy = p2.y - 2;
                 mapf::formatted_set_simple( m, point( biox - 1, bioy - 1 ),
                                             "|-|\n"
                                             "=c|\n"
                                             "|-|\n",
                                             mapf::ter_bind( "- | =", ter_t_concrete_wall, ter_t_concrete_wall, ter_t_reinforced_glass ),
                                             mapf::furn_bind( "c", furn_f_counter ) );
                 m->place_items( Item_spawn_data_bionics_common, 70, point( biox, bioy ),
                                 point( biox, bioy ), z, false, calendar::turn_zero );
                 m->furn_set( tripoint_bub_ms( biox - 2, bioy, z ), furn_f_console );
                 computer *tmpcomp2 = m->add_computer( tripoint( biox - 2,  bioy, z ), _( "Bionic access" ), 2 );
                 tmpcomp2->add_option( _( "Manifest" ), COMPACT_LIST_BIONICS, 0 );
                 tmpcomp2->add_option( _( "Open Chambers" ), COMPACT_RELEASE_BIONICS, 3 );
                 tmpcomp2->add_failure( COMPFAIL_MANHACKS );
                 tmpcomp2->add_failure( COMPFAIL_SECUBOTS );
                 tmpcomp2->set_access_denied_msg(
                     _( "ERROR!  Access denied!  Unauthorized access will be met with lethal force!" ) );
             }
             break;
         case room_dorm:
             if( rotate % 2 == 0 ) {
                 for( int y = p1.y + 1; y <= p2.y - 1; y += 3 ) {
                     m->furn_set( tripoint_bub_ms( p1.x, y, z ), furn_f_bed );
                     m->place_items( Item_spawn_data_bed, 60, point( p1.x, y ), point( p1.x, y ), z,
                                     false, calendar::start_of_cataclysm );
                     m->furn_set( tripoint_bub_ms( p1.x + 1, y, z ), furn_f_bed );
                     m->place_items( Item_spawn_data_bed, 60, point( p1.x + 1, y ),
                                     point( p1.x + 1, y ), z, false, calendar::start_of_cataclysm );
                     m->furn_set( tripoint_bub_ms( p2.x, y, z ), furn_f_bed );
                     m->place_items( Item_spawn_data_bed, 60, point( p2.x, y ), point( p2.x, y ), z,
                                     false, calendar::start_of_cataclysm );
                     m->furn_set( tripoint_bub_ms( p2.x - 1, y, z ), furn_f_bed );
                     m->place_items( Item_spawn_data_bed, 60, point( p2.x - 1, y ),
                                     point( p2.x - 1, y ), z, false, calendar::start_of_cataclysm );
                     m->furn_set( tripoint_bub_ms( p1.x, y + 1, z ), furn_f_dresser );
                     m->furn_set( tripoint_bub_ms( p2.x, y + 1, z ), furn_f_dresser );
                     m->place_items( Item_spawn_data_dresser, 70, point( p1.x, y + 1 ),
                                     point( p1.x, y + 1 ), z, false, calendar::start_of_cataclysm );
                     m->place_items( Item_spawn_data_dresser, 70, point( p2.x, y + 1 ),
                                     point( p2.x, y + 1 ), z, false, calendar::start_of_cataclysm );
                 }
             } else if( rotate % 2 == 1 ) {
                 for( int x = p1.x + 1; x <= p2.x - 1; x += 3 ) {
                     m->furn_set( tripoint_bub_ms( x, p1.y, z ), furn_f_bed );
                     m->place_items( Item_spawn_data_bed, 60, point( x, p1.y ), point( x, p1.y ), z,
                                     false, calendar::start_of_cataclysm );
                     m->furn_set( tripoint_bub_ms( x, p1.y + 1, z ), furn_f_bed );
                     m->place_items( Item_spawn_data_bed, 60, point( x, p1.y + 1 ),
                                     point( x, p1.y + 1 ), z, false, calendar::start_of_cataclysm );
                     m->furn_set( tripoint_bub_ms( x, p2.y, z ), furn_f_bed );
                     m->place_items( Item_spawn_data_bed, 60, point( x, p2.y ), point( x, p2.y ), z,
                                     false, calendar::start_of_cataclysm );
                     m->furn_set( tripoint_bub_ms( x, p2.y - 1, z ), furn_f_bed );
                     m->place_items( Item_spawn_data_bed, 60, point( x, p2.y - 1 ),
                                     point( x, p2.y - 1 ), z, false, calendar::start_of_cataclysm );
                     m->furn_set( tripoint_bub_ms( x + 1, p1.y, z ), furn_f_dresser );
                     m->furn_set( tripoint_bub_ms( x + 1, p2.y, z ), furn_f_dresser );
                     m->place_items( Item_spawn_data_dresser, 70, point( x + 1, p1.y ),
                                     point( x + 1, p1.y ), z, false, calendar::start_of_cataclysm );
                     m->place_items( Item_spawn_data_dresser, 70, point( x + 1, p2.y ),
                                     point( x + 1, p2.y ), z, false, calendar::start_of_cataclysm );
                 }
             }
             m->place_items( Item_spawn_data_lab_dorm, 84, p1, p2, z, false,
                             calendar::start_of_cataclysm );
             break;
         case room_split:
             if( rotate % 2 == 0 ) {
                 int w1 = static_cast<int>( ( p1.x + p2.x ) / 2 ) - 2;
                 int w2 = static_cast<int>( ( p1.x + p2.x ) / 2 ) + 2;
                 for( int y = p1.y; y <= p2.y; y++ ) {
                     m->ter_set( tripoint_bub_ms( w1, y, z ), ter_t_concrete_wall );
                     m->ter_set( tripoint_bub_ms( w2, y, z ), ter_t_concrete_wall );
                 }
                 m->ter_set( tripoint_bub_ms( w1, static_cast<int>( ( p1.y + p2.y ) / 2 ), z ),
                             ter_t_door_glass_frosted_c );
                 m->ter_set( tripoint_bub_ms( w2, static_cast<int>( ( p1.y + p2.y ) / 2 ), z ),
                             ter_t_door_glass_frosted_c );
                 science_room( m, p1, point( w1 - 1, p2.y ), z, 1 );
                 science_room( m, point( w2 + 1, p1.y ), p2, z, 3 );
             } else {
                 int w1 = static_cast<int>( ( p1.y + p2.y ) / 2 ) - 2;
                 int w2 = static_cast<int>( ( p1.y + p2.y ) / 2 ) + 2;
                 for( int x = p1.x; x <= p2.x; x++ ) {
                     m->ter_set( tripoint_bub_ms( x, w1, z ), ter_t_concrete_wall );
                     m->ter_set( tripoint_bub_ms( x, w2, z ), ter_t_concrete_wall );
                 }
                 m->ter_set( tripoint_bub_ms( ( p1.x + p2.x ) / 2, w1, z ), ter_t_door_glass_frosted_c );
                 m->ter_set( tripoint_bub_ms( ( p1.x + p2.x ) / 2, w2, z ), ter_t_door_glass_frosted_c );
                 science_room( m, p1, point( p2.x, w1 - 1 ), z, 2 );
                 science_room( m, point( p1.x, w2 + 1 ), p2, z, 0 );
             }
             break;
         default:
             break;
     }
 }
References _, map::add_computer(), computer::add_failure(), computer::add_option(), COMPACT_LIST_BIONICS, COMPACT_MAPS, COMPACT_RELEASE_BIONICS, COMPACT_RESEARCH, COMPFAIL_ALARM, COMPFAIL_DAMAGE, COMPFAIL_MANHACKS, COMPFAIL_SECUBOTS, COMPFAIL_SHUTDOWN, mapf::formatted_set_simple(), mapf::furn_bind(), furn_f_bed, furn_f_console, furn_f_counter, furn_f_dresser, furn_f_fridge, map::furn_set(), GROUP_LAB_CYBORG, GROUP_LAB_SECURITY, Item_spawn_data_bed, Item_spawn_data_bionics_common, Item_spawn_data_chem_lab, Item_spawn_data_cleaning, Item_spawn_data_cloning_vat, Item_spawn_data_dissection, Item_spawn_data_dresser, Item_spawn_data_goo, Item_spawn_data_lab_dorm, Item_spawn_data_mut_lab, Item_spawn_data_teleport, mremove_trap(), mtrap_set(), one_in(), map::place_items(), map::place_spawns(), point, point_east, point_north, point_north_west, point_south, point_west, random_entry(), rng(), room_bionics, room_chemistry, room_cloning, room_closet, room_dorm, room_goo, room_lobby, room_split, room_teleport, room_vivisect, rotate(), computer::set_access_denied_msg(), calendar::start_of_cataclysm, mapf::ter_bind(), map::ter_set(), ter_t_concrete_wall, ter_t_door_glass_frosted_c, ter_t_reinforced_glass, ter_t_thconc_floor, ter_t_vat, tr_dissector, tr_goo, tr_null, tr_telepad, tripoint, calendar::turn_zero, point::x, and point::y.
Referenced by map::draw_lab().
set_mapgen_defer()
static void set_mapgen_defer (const JsonObject & jsi, const std::string & member, const std::string & message) static
Definition at line 637 of file mapgen.cpp.
 {
     mapgen_defer::defer = true;
     mapgen_defer::jsi = jsi;
     mapgen_defer::member = member;
     mapgen_defer::message = message;
 }
References mapgen_defer::defer, mapgen_defer::jsi, mapgen_defer::member, and mapgen_defer::message.
Referenced by jmapgen_loot::jmapgen_loot(), and mapgen_function_json_base::setup_setmap().
set_queued_points()
void set_queued_points ()
Definition at line 7951 of file mapgen.cpp.
 {
     global_variables &globvars = get_globals();
     for( std::pair<const std::string, tripoint_abs_ms> &queued_point : queued_points ) {
         globvars.set_global_value( "npctalk_var_" + queued_point.first, queued_point.second.to_string() );
     }
     queued_points.clear();
 }
References get_globals(), queued_points, and global_variables::set_global_value().
Referenced by timed_event::actualize(), cardreader_examine_actor::apply(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), mapgen_function_json::generate(), and trapfunc::map_regen().
square() [1/3]
void square (map * m, const ter_id & type, const point & p1, const point & p2)
Definition at line 7745 of file mapgen.cpp.
 {
     m->draw_square_ter( type, p1, p2, m->get_abs_sub().z() );
 }
References map::draw_square_ter(), map::get_abs_sub(), type, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by outfit::add_AIM_items_from_area(), advanced_inventory_pane::add_items_from_area(), query_destination_callback::draw_squares(), advanced_inventory_pane::free_volume(), avatar::get_AIM_inventory(), outfit::get_AIM_inventory(), advanced_inventory::init(), advanced_inventory_pane::load_settings(), MapExtras::mx_roadworks(), advanced_inventory::redraw_pane(), and advanced_inventory_pane::set_area().
square() [2/3]
void square (map * m, const weighted_int_list< ter_id > & f, const point & p1, const point & p2)
Definition at line 7761 of file mapgen.cpp.
 {
     m->draw_square_ter( f, p1, p2 );
 }
References map::draw_square_ter().
square() [3/3]
void square (map * m, ter_id(*)() f, const point & p1, const point & p2)
Definition at line 7757 of file mapgen.cpp.
 {
     m->draw_square_ter( f, p1, p2 );
 }
References map::draw_square_ter().
square_furn() [1/2]
void square_furn (map * m, const furn_id & type, const point & p1, const point & p2)
Definition at line 7749 of file mapgen.cpp.
 {
     m->draw_square_furn( type, p1, p2, m->get_abs_sub().z() );
 }
References map::draw_square_furn(), map::get_abs_sub(), type, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by map::draw_lab(), and MapExtras::mx_minefield().
square_furn() [2/2]
void square_furn (tinymap * m, const furn_id & type, const point & p1, const point & p2)
Definition at line 7753 of file mapgen.cpp.
 {
     m->draw_square_furn( type, p1, p2 );
 }
References tinymap::draw_square_furn(), and type.
to_string_id_helper() [1/3]
template<typename T > static string_id<T> to_string_id_helper (const int_id< T > & id) static
Definition at line 1173 of file mapgen.cpp.
 {
     return id.id();
 }
to_string_id_helper() [2/3]
static std::string to_string_id_helper (const std::string & s) static
Definition at line 1178 of file mapgen.cpp.
 {
     return s;
 }
to_string_id_helper() [3/3]
template<typename T > static string_id<T> to_string_id_helper (const string_id< T > & id) static
Definition at line 1167 of file mapgen.cpp.
 {
     return id;
 }
References int_id< T >::id().
Referenced by mapgen_value< Id >::id_source::all_possible_results().
vehicle_bounds()
static inclusive_rectangle<point> vehicle_bounds (const vehicle_prototype & vp) static
Definition at line 2556 of file mapgen.cpp.
 {
     point min( INT_MAX, INT_MAX );
     point max( INT_MIN, INT_MIN );
     cata_assert( !vp.parts.empty() );
     for( const vehicle_prototype::part_def &part : vp.parts ) {
         min.x = std::min( min.x, part.pos.x );
         max.x = std::max( max.x, part.pos.x );
         min.y = std::min( min.y, part.pos.y );
         max.y = std::max( max.y, part.pos.y );
     }
     return { min, max };
 }
References cata_assert, max(), min(), vehicle_prototype::parts, vehicle_prototype::part_def::pos, point::x, and point::y.
Referenced by jmapgen_vehicle::check().
Variable Documentation
compare_phases
const phase_comparator compare_phases {} static
Definition at line 4509 of file mapgen.cpp.
Referenced by jmapgen_objects::apply(), jmapgen_objects::finalize(), and mapgen_function_json_base::setup_common().
EAST_EDGE
const int EAST_EDGE = 2 * SEEX - 1 static
Definition at line 5386 of file mapgen.cpp.
Referenced by map::draw_lab(), and map::draw_slimepit().
furn_f_bed
const furn_str_id furn_f_bed("f_bed") ("f_bed") static
Referenced by science_room().
furn_f_console
const furn_str_id furn_f_console("f_console") ("f_console") static
Referenced by map::add_computer(), jmapgen_computer::apply(), map::draw_lab(), and science_room().
furn_f_counter
const furn_str_id furn_f_counter("f_counter") ("f_counter") static
Referenced by map::draw_lab(), and science_room().
furn_f_dresser
const furn_str_id furn_f_dresser("f_dresser") ("f_dresser") static
Referenced by science_room().
furn_f_flower_fungal
const furn_str_id furn_f_flower_fungal("f_flower_fungal") ("f_flower_fungal") static
Referenced by map::draw_lab().
furn_f_fridge
const furn_str_id furn_f_fridge("f_fridge") ("f_fridge") static
Referenced by science_room().
furn_f_fungal_clump
const furn_str_id furn_f_fungal_clump("f_fungal_clump") ("f_fungal_clump") static
Referenced by map::draw_lab().
furn_f_rack
const furn_str_id furn_f_rack("f_rack") ("f_rack") static
Referenced by map::draw_lab().
furn_f_rubble
const furn_str_id furn_f_rubble("f_rubble") ("f_rubble") static
Referenced by map::create_anomaly().
furn_f_rubble_rock
const furn_str_id furn_f_rubble_rock("f_rubble_rock") ("f_rubble_rock") static
Referenced by map::draw_lab().
furn_f_sign
const furn_str_id furn_f_sign("f_sign") ("f_sign") static
Referenced by jmapgen_sign::jmapgen_sign().
furn_f_table
const furn_str_id furn_f_table("f_table") ("f_table") static
Referenced by map::draw_lab().
furn_f_toilet
const furn_str_id furn_f_toilet("f_toilet") ("f_toilet") static
Referenced by map::place_toilet().
furn_f_vending_c
const furn_str_id furn_f_vending_c("f_vending_c") ("f_vending_c") static
Referenced by map::place_vending().
furn_f_vending_o
const furn_str_id furn_f_vending_o("f_vending_o") ("f_vending_o") static
Referenced by map::place_vending().
furn_f_vending_reinforced
const furn_str_id furn_f_vending_reinforced("f_vending_reinforced") ("f_vending_reinforced") static
Referenced by map::place_vending().
GROUP_BREATHER
const mongroup_id GROUP_BREATHER("GROUP_BREATHER") ("GROUP_BREATHER") static
Referenced by map::create_anomaly().
GROUP_BREATHER_HUB
const mongroup_id GROUP_BREATHER_HUB("GROUP_BREATHER_HUB") ("GROUP_BREATHER_HUB") static
Referenced by map::create_anomaly().
GROUP_FUNGI_FUNGALOID
const mongroup_id GROUP_FUNGI_FUNGALOID("GROUP_FUNGI_FUNGALOID") ("GROUP_FUNGI_FUNGALOID") static
Referenced by map::draw_lab().
GROUP_LAB
const mongroup_id GROUP_LAB("GROUP_LAB") ("GROUP_LAB") static
Referenced by map::draw_lab().
GROUP_LAB_CYBORG
const mongroup_id GROUP_LAB_CYBORG("GROUP_LAB_CYBORG") ("GROUP_LAB_CYBORG") static
Referenced by science_room().
GROUP_LAB_SECURITY
const mongroup_id GROUP_LAB_SECURITY("GROUP_LAB_SECURITY") ("GROUP_LAB_SECURITY") static
Referenced by science_room().
GROUP_NETHER
const mongroup_id GROUP_NETHER("GROUP_NETHER") ("GROUP_NETHER") static
Referenced by map::draw_lab().
GROUP_ROBOT_SECUBOT
const mongroup_id GROUP_ROBOT_SECUBOT("GROUP_ROBOT_SECUBOT") ("GROUP_ROBOT_SECUBOT") static
Referenced by map::draw_lab().
GROUP_SLIME
const mongroup_id GROUP_SLIME("GROUP_SLIME") ("GROUP_SLIME") static
Referenced by map::draw_slimepit().
GROUP_TURRET
const mongroup_id GROUP_TURRET("GROUP_TURRET") ("GROUP_TURRET") static
Referenced by map::draw_lab().
Item_spawn_data_ammo_rare
const item_group_id Item_spawn_data_ammo_rare("ammo_rare") ("ammo_rare") static
Referenced by map::draw_lab().
Item_spawn_data_bed
const item_group_id Item_spawn_data_bed("bed") ("bed") static
Referenced by science_room().
Item_spawn_data_bionics
const item_group_id Item_spawn_data_bionics("bionics") ("bionics") static
Referenced by map::draw_lab().
Item_spawn_data_bionics_common
const item_group_id Item_spawn_data_bionics_common("bionics_common") ("bionics_common") static
Referenced by science_room().
Item_spawn_data_chem_lab
const item_group_id Item_spawn_data_chem_lab("chem_lab") ("chem_lab") static
Referenced by science_room().
Item_spawn_data_cleaning
const item_group_id Item_spawn_data_cleaning("cleaning") ("cleaning") static
Referenced by science_room().
Item_spawn_data_cloning_vat
const item_group_id Item_spawn_data_cloning_vat("cloning_vat") ("cloning_vat") static
Referenced by science_room().
Item_spawn_data_dissection
const item_group_id Item_spawn_data_dissection("dissection") ("dissection") static
Referenced by science_room().
Item_spawn_data_dresser
const item_group_id Item_spawn_data_dresser("dresser") ("dresser") static
Referenced by science_room().
Item_spawn_data_goo
const item_group_id Item_spawn_data_goo("goo") ("goo") static
Referenced by science_room().
Item_spawn_data_guns_rare
const item_group_id Item_spawn_data_guns_rare("guns_rare") ("guns_rare") static
Referenced by map::draw_lab().
Item_spawn_data_lab_dorm
const item_group_id Item_spawn_data_lab_dorm("lab_dorm") ("lab_dorm") static
Referenced by science_room().
Item_spawn_data_mut_lab
const item_group_id Item_spawn_data_mut_lab("mut_lab") ("mut_lab") static
Referenced by science_room().
Item_spawn_data_sewer
const item_group_id Item_spawn_data_sewer("sewer") ("sewer") static
Referenced by map::draw_slimepit().
Item_spawn_data_teleport
const item_group_id Item_spawn_data_teleport("teleport") ("teleport") static
Referenced by science_room().
itype_avgas
const itype_id itype_avgas("avgas") ("avgas") static
Referenced by jmapgen_liquid_item::apply(), and jmapgen_gaspump::check().
itype_diesel
const itype_id itype_diesel("diesel") ("diesel") static
Referenced by jmapgen_liquid_item::apply(), jmapgen_gaspump::check(), and map::place_gas_pump().
itype_gasoline
const itype_id itype_gasoline("gasoline") ("gasoline") static
Referenced by jmapgen_liquid_item::apply(), jmapgen_gaspump::check(), and map::place_gas_pump().
itype_jp8
const itype_id itype_jp8("jp8") ("jp8") static
Referenced by jmapgen_liquid_item::apply(), and jmapgen_gaspump::check().
MON_RADIUS
constexpr int MON_RADIUS = 3 static constexpr
Definition at line 205 of file mapgen.cpp.
Referenced by map::generate().
nested_mapgens
std::map<nested_mapgen_id, nested_mapgen> nested_mapgens
Definition at line 529 of file mapgen.cpp.
Referenced by jmapgen_nested::apply(), calculate_mapgen_weights(), check_mapgen_definitions(), jmapgen_nested::has_vehicle_collision(), string_id< T >::is_valid(), load_nested_mapgen(), jmapgen_nested::merge_parameters_into(), string_id< T >::obj(), reset_mapgens(), and debug_menu::spawn_nested_mapgen().
oter_ants_es
const oter_str_id oter_ants_es("ants_es") ("ants_es") static
Referenced by connects_to().
oter_ants_esw
const oter_str_id oter_ants_esw("ants_esw") ("ants_esw") static
Referenced by connects_to().
oter_ants_ew
const oter_str_id oter_ants_ew("ants_ew") ("ants_ew") static
Referenced by connects_to().
oter_ants_lab
const oter_str_id oter_ants_lab("ants_lab") ("ants_lab") static
Referenced by map::draw_lab().
oter_ants_lab_stairs
const oter_str_id oter_ants_lab_stairs("ants_lab_stairs") ("ants_lab_stairs") static
Referenced by map::draw_lab().
oter_ants_ne
const oter_str_id oter_ants_ne("ants_ne") ("ants_ne") static
Referenced by connects_to().
oter_ants_nes
const oter_str_id oter_ants_nes("ants_nes") ("ants_nes") static
Referenced by connects_to().
oter_ants_nesw
const oter_str_id oter_ants_nesw("ants_nesw") ("ants_nesw") static
Referenced by connects_to().
oter_ants_new
const oter_str_id oter_ants_new("ants_new") ("ants_new") static
Referenced by connects_to().
oter_ants_ns
const oter_str_id oter_ants_ns("ants_ns") ("ants_ns") static
Referenced by connects_to().
oter_ants_nsw
const oter_str_id oter_ants_nsw("ants_nsw") ("ants_nsw") static
Referenced by connects_to().
oter_ants_sw
const oter_str_id oter_ants_sw("ants_sw") ("ants_sw") static
Referenced by connects_to().
oter_ants_wn
const oter_str_id oter_ants_wn("ants_wn") ("ants_wn") static
Referenced by connects_to().
oter_central_lab
const oter_str_id oter_central_lab("central_lab") ("central_lab") static
Referenced by map::draw_lab().
oter_central_lab_core
const oter_str_id oter_central_lab_core("central_lab_core") ("central_lab_core") static
Referenced by map::draw_lab().
oter_central_lab_finale
const oter_str_id oter_central_lab_finale("central_lab_finale") ("central_lab_finale") static
Referenced by map::draw_lab().
oter_central_lab_stairs
const oter_str_id oter_central_lab_stairs("central_lab_stairs") ("central_lab_stairs") static
Referenced by map::draw_lab().
oter_ice_lab
const oter_str_id oter_ice_lab("ice_lab") ("ice_lab") static
Referenced by map::draw_lab().
oter_ice_lab_core
const oter_str_id oter_ice_lab_core("ice_lab_core") ("ice_lab_core") static
Referenced by map::draw_lab().
oter_ice_lab_finale
const oter_str_id oter_ice_lab_finale("ice_lab_finale") ("ice_lab_finale") static
Referenced by map::draw_lab().
oter_ice_lab_stairs
const oter_str_id oter_ice_lab_stairs("ice_lab_stairs") ("ice_lab_stairs") static
Referenced by map::draw_lab().
oter_lab
const oter_str_id oter_lab("lab") ("lab") static
Referenced by map::draw_lab().
oter_lab_core
const oter_str_id oter_lab_core("lab_core") ("lab_core") static
Referenced by map::draw_lab().
oter_lab_finale
const oter_str_id oter_lab_finale("lab_finale") ("lab_finale") static
Referenced by map::draw_lab().
oter_lab_stairs
const oter_str_id oter_lab_stairs("lab_stairs") ("lab_stairs") static
Referenced by map::draw_lab().
oter_mapgen
mapgen_factory oter_mapgen static
Definition at line 527 of file mapgen.cpp.
Referenced by calculate_mapgen_weights(), check_mapgen_consistent_with(), check_mapgen_definitions(), map::draw_lab(), get_map_special_params(), has_mapgen_for(), load_and_add_mapgen_function(), load_mapgen(), register_mapgen_function(), reset_mapgens(), and run_mapgen_func().
oter_slimepit
const oter_str_id oter_slimepit("slimepit") ("slimepit") static
Referenced by map::draw_lab().
oter_slimepit_bottom
const oter_str_id oter_slimepit_bottom("slimepit_bottom") ("slimepit_bottom") static
Referenced by map::draw_slimepit().
oter_slimepit_down
const oter_str_id oter_slimepit_down("slimepit_down") ("slimepit_down") static
Referenced by map::draw_slimepit().
oter_tower_lab
const oter_str_id oter_tower_lab("tower_lab") ("tower_lab") static
Referenced by map::draw_lab().
oter_tower_lab_finale
const oter_str_id oter_tower_lab_finale("tower_lab_finale") ("tower_lab_finale") static
Referenced by map::draw_lab().
oter_tower_lab_stairs
const oter_str_id oter_tower_lab_stairs("tower_lab_stairs") ("tower_lab_stairs") static
Referenced by map::draw_lab().
oter_type_road
const oter_type_str_id oter_type_road("road") ("road") static
Referenced by map::draw_lab().
oter_type_sewer
const oter_type_str_id oter_type_sewer("sewer") ("sewer") static
Referenced by map::draw_lab().
palettes
std::map<palette_id, mapgen_palette> palettes static
Definition at line 4164 of file mapgen.cpp.
Referenced by mapgen_palette::check_definitions(), mapgen_palette::get(), mapgen_palette::load(), and mapgen_palette::reset().
queued_points
std::unordered_map<std::string, tripoint_abs_ms> queued_points static
Definition at line 531 of file mapgen.cpp.
Referenced by jmapgen_variable::apply(), jmapgen_setmap::apply(), map::rotate(), and set_queued_points().
SOUTH_EDGE
const int SOUTH_EDGE = 2 * SEEY - 1 static
Definition at line 5385 of file mapgen.cpp.
Referenced by map::draw_lab(), and map::draw_slimepit().
ter_t_bars
const ter_str_id ter_t_bars("t_bars") ("t_bars") static
Referenced by map::draw_lab().
ter_t_card_science
const ter_str_id ter_t_card_science("t_card_science") ("t_card_science") static
Referenced by map::draw_lab().
ter_t_concrete_wall
const ter_str_id ter_t_concrete_wall("t_concrete_wall") ("t_concrete_wall") static
Referenced by map::draw_lab(), and science_room().
ter_t_cvdbody
const ter_str_id ter_t_cvdbody("t_cvdbody") ("t_cvdbody") static
Referenced by map::draw_lab().
ter_t_cvdmachine
const ter_str_id ter_t_cvdmachine("t_cvdmachine") ("t_cvdmachine") static
Referenced by map::draw_lab().
ter_t_dirt
const ter_str_id ter_t_dirt("t_dirt") ("t_dirt") static
Referenced by jmapgen_make_rubble::apply(), map::create_anomaly(), map::draw_lab(), and map::draw_slimepit().
ter_t_door_glass_frosted_c
const ter_str_id ter_t_door_glass_frosted_c("t_door_glass_frosted_c") ("t_door_glass_frosted_c") static
Referenced by map::draw_lab(), and science_room().
ter_t_door_metal_c
const ter_str_id ter_t_door_metal_c("t_door_metal_c") ("t_door_metal_c") static
Referenced by map::draw_lab().
ter_t_door_metal_locked
const ter_str_id ter_t_door_metal_locked("t_door_metal_locked") ("t_door_metal_locked") static
Referenced by map::draw_lab().
ter_t_floor
const ter_str_id ter_t_floor("t_floor") ("t_floor") static
Referenced by map::draw_lab(), and map::draw_map().
ter_t_fungus_floor_in
const ter_str_id ter_t_fungus_floor_in("t_fungus_floor_in") ("t_fungus_floor_in") static
Referenced by map::draw_lab().
ter_t_fungus_wall
const ter_str_id ter_t_fungus_wall("t_fungus_wall") ("t_fungus_wall") static
Referenced by map::draw_lab().
ter_t_grass
const ter_str_id ter_t_grass("t_grass") ("t_grass") static
Referenced by apply_construction_marker().
ter_t_marloss
const ter_str_id ter_t_marloss("t_marloss") ("t_marloss") static
Referenced by map::draw_lab().
ter_t_radio_tower
const ter_str_id ter_t_radio_tower("t_radio_tower") ("t_radio_tower") static
Referenced by map::draw_lab().
ter_t_reinforced_door_glass_c
const ter_str_id ter_t_reinforced_door_glass_c("t_reinforced_door_glass_c") ("t_reinforced_door_glass_c") static
Referenced by map::draw_lab().
ter_t_reinforced_glass
const ter_str_id ter_t_reinforced_glass("t_reinforced_glass") ("t_reinforced_glass") static
Referenced by map::draw_lab(), and science_room().
ter_t_rock_floor
const ter_str_id ter_t_rock_floor("t_rock_floor") ("t_rock_floor") static
Referenced by map::draw_lab(), and map::draw_slimepit().
ter_t_sewage
const ter_str_id ter_t_sewage("t_sewage") ("t_sewage") static
Referenced by map::draw_lab().
ter_t_slime
const ter_str_id ter_t_slime("t_slime") ("t_slime") static
Referenced by map::draw_lab(), and map::draw_slimepit().
ter_t_slope_down
const ter_str_id ter_t_slope_down("t_slope_down") ("t_slope_down") static
Referenced by map::draw_slimepit().
ter_t_slope_up
const ter_str_id ter_t_slope_up("t_slope_up") ("t_slope_up") static
Referenced by map::draw_slimepit().
ter_t_stairs_down
const ter_str_id ter_t_stairs_down("t_stairs_down") ("t_stairs_down") static
Referenced by map::draw_lab().
ter_t_stairs_up
const ter_str_id ter_t_stairs_up("t_stairs_up") ("t_stairs_up") static
Referenced by map::draw_lab().
ter_t_strconc_floor
const ter_str_id ter_t_strconc_floor("t_strconc_floor") ("t_strconc_floor") static
Referenced by map::draw_lab().
ter_t_thconc_floor
const ter_str_id ter_t_thconc_floor("t_thconc_floor") ("t_thconc_floor") static
Referenced by map::draw_lab(), and science_room().
ter_t_thconc_floor_olight
const ter_str_id ter_t_thconc_floor_olight("t_thconc_floor_olight") ("t_thconc_floor_olight") static
Referenced by map::draw_lab().
ter_t_vat
const ter_str_id ter_t_vat("t_vat") ("t_vat") static
Referenced by science_room().
ter_t_water_sh
const ter_str_id ter_t_water_sh("t_water_sh") ("t_water_sh") static
Referenced by map::draw_lab().
trait_NPC_STATIC_NPC
const trait_id trait_NPC_STATIC_NPC("NPC_STATIC_NPC") ("NPC_STATIC_NPC") static
Referenced by map::place_npc().
update_mapgens
std::map<update_mapgen_id, update_mapgen> update_mapgens
Definition at line 530 of file mapgen.cpp.
Referenced by apply_construction_marker(), calculate_mapgen_weights(), map_extra::check(), check_mapgen_definitions(), get_changed_ids_from_update(), has_update_mapgen_for(), load_update_mapgen(), reset_mapgens(), and run_mapgen_update_func().
vehicle_prototype_shopping_cart
const vproto_id vehicle_prototype_shopping_cart("shopping_cart") ("shopping_cart") static
Referenced by map::add_vehicle_to_map().