Cataclysm DDA: src/martialarts.cpp File Reference
martialarts.cpp File Reference
#include "martialarts.h"
#include <algorithm>
#include <cstdlib>
#include <iterator>
#include <map>
#include <memory>
#include <string>
#include <utility>
#include "bodypart.h"
#include "character.h"
#include "character_martial_arts.h"
#include "color.h"
#include "condition.h"
#include "cursesdef.h"
#include "damage.h"
#include "debug.h"
#include "effect.h"
#include "enums.h"
#include "game_constants.h"
#include "generic_factory.h"
#include "input_context.h"
#include "item.h"
#include "item_factory.h"
#include "itype.h"
#include "localized_comparator.h"
#include "map.h"
#include "output.h"
#include "pimpl.h"
#include "point.h"
#include "skill.h"
#include "string_formatter.h"
#include "translations.h"
#include "ui_manager.h"
#include "value_ptr.h"
Classes
class ma_skill_reader
class ma_weapon_damage_reader
class tech_effect_reader
class ma_buff_reader
class ma_buff_effect_type
This is a wrapper class to get access to the protected members of effect_type, it creates the effect_type that is used to store a ma_buff in the creatures effect map.
Namespaces
anonymous_namespace{martialarts.cpp}
Functions
matype_id martial_art_learned_from (const itype &type)
void load_technique (const JsonObject &jo, const std::string &src)
template<typename Container >
void add_if_exists (const JsonObject &jo, Container &cont, bool was_loaded, const std::string &json_key, const typename Container::key_type &id)
tech_effect_data load_tech_effect_data (const JsonObject &e)
void load_martial_art (const JsonObject &jo, const std::string &src)
std::vector< matype_id > all_martialart_types ()
std::vector< matype_id > autolearn_martialart_types ()
static void check (const ma_requirements &req, const std::string &display_text)
void check_martialarts ()
void finalize_martial_arts ()
std::string martialart_difficulty (const matype_id &mstyle)
void clear_techniques_and_martial_arts ()
static void simultaneous_add (Character &u, const std::vector< mabuff_id > &buffs)
static ma_technique get_valid_technique (const Character &owner, bool ma_technique::*purpose)
template<typename C , typename F >
static void accumulate_ma_buff_effects (const C &container, F f)
template<typename C , typename F >
static bool search_ma_buff_effect (const C &container, F f)
Variables
static const bionic_id bio_armor_arms ("bio_armor_arms")
static const bionic_id bio_armor_legs ("bio_armor_legs")
static const bionic_id bio_cqb ("bio_cqb")
static const flag_id json_flag_PROVIDES_TECHNIQUES ("PROVIDES_TECHNIQUES")
static const json_character_flag json_flag_ALWAYS_BLOCK ("ALWAYS_BLOCK")
static const json_character_flag json_flag_NONSTANDARD_BLOCK ("NONSTANDARD_BLOCK")
static const limb_score_id limb_score_block ("block")
static const skill_id skill_unarmed ("unarmed")
static const weapon_category_id weapon_category_OTHER_INVALID_WEAP_CAT ("OTHER_INVALID_WEAP_CAT")
generic_factory< weapon_category > anonymous_namespace{martialarts.cpp}::weapon_category_factory ("weapon category")
generic_factory< ma_technique > anonymous_namespace{martialarts.cpp}::ma_techniques ("martial art technique")
generic_factory< martialart > anonymous_namespace{martialarts.cpp}::martialarts ("martial art style")
generic_factory< ma_buff > anonymous_namespace{martialarts.cpp}::ma_buffs ("martial art buff")
Function Documentation
accumulate_ma_buff_effects()
template<typename C , typename F > static void accumulate_ma_buff_effects (const C & container, F f) static
Definition at line 1587 of file martialarts.cpp.
 {
     for( auto &elem : container ) {
         for( auto &eff : elem.second ) {
             if( auto buff = ma_buff::from_effect( eff.second ) ) {
                 f( *buff, eff.second );
             }
         }
     }
 }
References ma_buff::from_effect().
Referenced by Character::count_mabuff_flag(), Character::mabuff_armor_bonus(), Character::mabuff_arpen_bonus(), Character::mabuff_attack_cost_mult(), Character::mabuff_attack_cost_penalty(), Character::mabuff_block_bonus(), Character::mabuff_block_effectiveness_bonus(), Character::mabuff_critical_hit_chance_bonus(), Character::mabuff_damage_bonus(), Character::mabuff_damage_mult(), Character::mabuff_dodge_bonus(), Character::mabuff_speed_bonus(), and Character::mabuff_tohit_bonus().
add_if_exists()
template<typename Container > void add_if_exists (const JsonObject & jo, Container & cont, bool was_loaded, const std::string & json_key, const typename Container::key_type & id)
Definition at line 131 of file martialarts.cpp.
 {
     if( jo.has_member( json_key ) ) {
         mandatory( jo, was_loaded, json_key, cont[id] );
     }
 }
References JsonObject::has_member(), and mandatory().
all_martialart_types()
std::vector<matype_id> all_martialart_types ()
Definition at line 454 of file martialarts.cpp.
 {
     std::vector<matype_id> result;
     for( const martialart &ma : martialarts.get_all() ) {
         result.push_back( ma.id );
     }
     return result;
 }
References anonymous_namespace{martialarts.cpp}::martialarts.
Referenced by debug_menu::debug().
autolearn_martialart_types()
std::vector<matype_id> autolearn_martialart_types ()
Definition at line 463 of file martialarts.cpp.
 {
     std::vector<matype_id> result;
     for( const martialart &ma : martialarts.get_all() ) {
         if( ma.autolearn_skills.empty() ) {
             continue;
         }
         result.push_back( ma.id );
     }
     return result;
 }
References anonymous_namespace{martialarts.cpp}::martialarts.
Referenced by Character::process_turn().
check()
static void check (const ma_requirements & req, const std::string & display_text) static
Definition at line 475 of file martialarts.cpp.
 {
     for( const mabuff_id &r : req.req_buffs_all ) {
         if( !r.is_valid() ) {
             debugmsg( "ma buff %s of %s does not exist", r.c_str(), display_text );
         }
     }
     for( const mabuff_id &r : req.req_buffs_any ) {
         if( !r.is_valid() ) {
             debugmsg( "ma buff %s of %s does not exist", r.c_str(), display_text );
         }
     }
     for( const mabuff_id &r : req.forbid_buffs_all ) {
         if( !r.is_valid() ) {
             debugmsg( "ma buff %s of %s does not exist", r.c_str(), display_text );
         }
     }
     for( const mabuff_id &r : req.forbid_buffs_any ) {
         if( !r.is_valid() ) {
             debugmsg( "ma buff %s of %s does not exist", r.c_str(), display_text );
         }
     }
 }
References string_id< T >::c_str(), debugmsg, ma_requirements::forbid_buffs_all, ma_requirements::forbid_buffs_any, string_id< T >::is_valid(), ma_requirements::req_buffs_all, and ma_requirements::req_buffs_any.
Referenced by anonymous_namespace{activity_item_handling.cpp}::_can_construct(), castLight(), castLightAll(), effect_type::check_consistency(), dependency_node::check_cyclicity(), check_martialarts(), game::check_mod_data(), talk_function::field_harvest(), mission_start::find_safety(), ff::flood_fill_visit_10_connected(), dependency_node::get_dependencies_as_nodes(), dependency_node::get_dependents_as_nodes(), zone_manager::get_zone_at(), dependency_node::inherit_errors(), robot_finds_kitten::process_input(), and text_style_check().
check_martialarts()
void check_martialarts ()
Definition at line 502 of file martialarts.cpp.
 {
     for( const martialart &ma : martialarts.get_all() ) {
         for( auto technique = ma.techniques.cbegin();
              technique != ma.techniques.cend(); ++technique ) {
             if( !technique->is_valid() ) {
                 debugmsg( "Technique with id %s in style %s doesn't exist.",
                           technique->c_str(), ma.name );
             }
         }
         for( auto weapon = ma.weapons.cbegin();
              weapon != ma.weapons.cend(); ++weapon ) {
             if( !item::type_is_defined( *weapon ) ) {
                 debugmsg( "Weapon %s in style %s doesn't exist.",
                           weapon->c_str(), ma.name );
             }
         }
     }
     for( const ma_technique &t : ma_techniques.get_all() ) {
         ::check( t.reqs, string_format( "technique %s", t.id.c_str() ) );
     }
     for( const ma_buff &b : ma_buffs.get_all() ) {
         ::check( b.reqs, string_format( "buff %s", b.id.c_str() ) );
     }
 }
References b, check(), debugmsg, anonymous_namespace{martialarts.cpp}::ma_buffs, anonymous_namespace{martialarts.cpp}::ma_techniques, anonymous_namespace{martialarts.cpp}::martialarts, string_format(), and item::type_is_defined().
Referenced by DynamicDataLoader::check_consistency().
clear_techniques_and_martial_arts()
void clear_techniques_and_martial_arts ()
Definition at line 587 of file martialarts.cpp.
 {
     martialarts.reset();
     ma_buffs.reset();
     ma_techniques.reset();
 }
References anonymous_namespace{martialarts.cpp}::ma_buffs, anonymous_namespace{martialarts.cpp}::ma_techniques, and anonymous_namespace{martialarts.cpp}::martialarts.
Referenced by DynamicDataLoader::unload_data().
finalize_martial_arts()
void finalize_martial_arts ()
Definition at line 558 of file martialarts.cpp.
 {
     // This adds an effect type for each ma_buff, so we can later refer to it and don't need a
     // redundant definition of those effects in json.
     for( const ma_buff &buff : ma_buffs.get_all() ) {
         const ma_buff_effect_type new_eff( buff );
         // Note the slicing here: new_eff is converted to a plain effect_type, but this doesn't
         // bother us because ma_buff_effect_type does not have any members that can be sliced.
         effect_type::register_ma_buff_effect( new_eff );
     }
 }
References anonymous_namespace{martialarts.cpp}::ma_buffs, and effect_type::register_ma_buff_effect().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_valid_technique()
static ma_technique get_valid_technique (const Character & owner, bool ma_technique::* purpose) static
Definition at line 1349 of file martialarts.cpp.
 {
     const auto &ma_data = owner.martial_arts_data;
     for( const matec_id &candidate_id : ma_data->get_all_techniques( owner.get_wielded_item(),
             owner ) ) {
         ma_technique candidate = candidate_id.obj();
         if( candidate.*purpose && candidate.is_valid_character( owner ) ) {
             return candidate;
         }
     }
     return tec_none.obj();
 }
References Character::get_wielded_item(), ma_technique::is_valid_character(), Character::martial_arts_data, string_id< T >::obj(), and tec_none.
Referenced by character_martial_arts::get_grab_break(), and character_martial_arts::get_miss_recovery().
load_martial_art()
void load_martial_art (const JsonObject & jo, const std::string & src)
Definition at line 340 of file martialarts.cpp.
 {
     martialarts.load( jo, src );
 }
References anonymous_namespace{martialarts.cpp}::martialarts.
Referenced by DynamicDataLoader::initialize().
load_tech_effect_data()
tech_effect_data load_tech_effect_data (const JsonObject & e)
Definition at line 170 of file martialarts.cpp.
 {
     return tech_effect_data( efftype_id( e.get_string( "id" ) ), e.get_int( "duration", 0 ),
                              e.get_bool( "permanent", false ), e.get_bool( "on_damage", true ),
                              e.get_int( "chance", 100 ), e.get_string( "message", "" ),
                              json_character_flag( e.get_string( "req_flag", "NULL" ) ) );
 }
References JsonObject::get_bool(), JsonObject::get_int(), and JsonObject::get_string().
Referenced by tech_effect_reader::get_next().
load_technique()
void load_technique (const JsonObject & jo, const std::string & src)
Definition at line 124 of file martialarts.cpp.
 {
     ma_techniques.load( jo, src );
 }
References anonymous_namespace{martialarts.cpp}::ma_techniques.
Referenced by DynamicDataLoader::initialize().
martial_art_learned_from()
matype_id martial_art_learned_from (const itype & type)
Definition at line 109 of file martialarts.cpp.
 {
     if( !type.can_use( "MA_MANUAL" ) ) {
         return {};
     }
     if( !type.book || type.book->martial_art.is_null() ) {
         debugmsg( "Item '%s' which claims to teach a martial art is missing martial_art",
                   type.get_id().str() );
         return {};
     }
     return type.book->martial_art;
 }
References debugmsg.
Referenced by item::book_info(), item::color_in_inventory(), avatar::identify(), iuse::ma_manual(), read_activity_actor::player_readma(), and avatar::read().
martialart_difficulty()
std::string martialart_difficulty (const matype_id & mstyle)
Definition at line 570 of file martialarts.cpp.
 {
     std::string diff;
     if( mstyle->learn_difficulty <= 2 ) {
         diff = _( "easy" );
     } else if( mstyle->learn_difficulty <= 4 ) {
         diff = _( "moderately hard" );
     } else if( mstyle->learn_difficulty <= 6 ) {
         diff = _( "hard" );
     } else if( mstyle->learn_difficulty <= 8 ) {
         diff = _( "very hard" );
     } else {
         diff = _( "extremely hard" );
     }
     return diff;
 }
References _, and martialart::learn_difficulty.
Referenced by item::book_info(), and avatar::identify().
search_ma_buff_effect()
template<typename C , typename F > static bool search_ma_buff_effect (const C & container, F f) static
Definition at line 1599 of file martialarts.cpp.
 {
     for( auto &elem : container ) {
         for( auto &eff : elem.second ) {
             if( auto buff = ma_buff::from_effect( eff.second ) ) {
                 if( f( *buff, eff.second ) ) {
                     return true;
                 }
             }
         }
     }
     return false;
 }
References ma_buff::from_effect().
Referenced by Character::can_melee(), Character::has_mabuff(), Character::has_mabuff_flag(), Character::is_melee_bash_damage_cap_bonus(), Character::is_quiet(), and Character::is_stealthy().
simultaneous_add()
static void simultaneous_add (Character & u, const std::vector< mabuff_id > & buffs) static
Definition at line 1043 of file martialarts.cpp.
 {
     std::vector<const ma_buff *> buffer; // hey get it because it's for buffs????
     for( const mabuff_id &buffid : buffs ) {
         const ma_buff &buff = buffid.obj();
         if( buff.is_valid_character( u ) ) {
             buffer.push_back( &buff );
         }
     }
     for( const ma_buff *&elem : buffer ) {
         elem->apply_buff( u );
     }
 }
References ma_buff::apply_buff(), ma_buff::is_valid_character(), and u.
Referenced by martialart::apply_onattack_buffs(), martialart::apply_onblock_buffs(), martialart::apply_oncrit_buffs(), martialart::apply_ondodge_buffs(), martialart::apply_ongethit_buffs(), martialart::apply_onhit_buffs(), martialart::apply_onkill_buffs(), martialart::apply_onmiss_buffs(), martialart::apply_onmove_buffs(), martialart::apply_onpause_buffs(), and martialart::apply_static_buffs().
Variable Documentation
bio_armor_arms
const bionic_id bio_armor_arms("bio_armor_arms") ("bio_armor_arms") static
Referenced by character_martial_arts::can_arm_block().
bio_armor_legs
const bionic_id bio_armor_legs("bio_armor_legs") ("bio_armor_legs") static
Referenced by character_martial_arts::can_leg_block().
bio_cqb
const bionic_id bio_cqb("bio_cqb") ("bio_cqb") static
Referenced by character_martial_arts::can_arm_block(), character_martial_arts::can_leg_block(), ma_requirements::is_valid_character(), and ma_style_callback::key().
json_flag_ALWAYS_BLOCK
const json_character_flag json_flag_ALWAYS_BLOCK("ALWAYS_BLOCK") ("ALWAYS_BLOCK") static
Referenced by character_martial_arts::can_nonstandard_block().
json_flag_NONSTANDARD_BLOCK
const json_character_flag json_flag_NONSTANDARD_BLOCK("NONSTANDARD_BLOCK") ("NONSTANDARD_BLOCK") static
Referenced by character_martial_arts::can_arm_block(), character_martial_arts::can_leg_block(), and character_martial_arts::can_nonstandard_block().
json_flag_PROVIDES_TECHNIQUES
const flag_id json_flag_PROVIDES_TECHNIQUES("PROVIDES_TECHNIQUES") ("PROVIDES_TECHNIQUES") static
Referenced by character_martial_arts::get_all_techniques().
limb_score_block
const limb_score_id limb_score_block("block") ("block") static
Referenced by character_martial_arts::can_arm_block(), character_martial_arts::can_leg_block(), and character_martial_arts::can_nonstandard_block().
skill_unarmed
const skill_id skill_unarmed("unarmed") ("unarmed") static
Referenced by character_martial_arts::can_arm_block(), character_martial_arts::can_leg_block(), character_martial_arts::can_nonstandard_block(), ma_style_callback::key(), and martialart::load().
weapon_category_OTHER_INVALID_WEAP_CAT
const weapon_category_id weapon_category_OTHER_INVALID_WEAP_CAT("OTHER_INVALID_WEAP_CAT") ("OTHER_INVALID_WEAP_CAT") static
Referenced by ma_style_callback::key().