Cataclysm DDA: src/martialarts.h File Reference
martialarts.h File Reference
#include <cstddef>
#include <iosfwd>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "bonuses.h"
#include "effect_on_condition.h"
#include "calendar.h"
#include "flat_set.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
Classes
class weapon_category
struct ma_requirements
struct tech_effect_data
class ma_technique
class ma_buff
class martialart
class ma_style_callback
Macros
#define CATA_SRC_MARTIALARTS_H
Functions
matype_id martial_art_learned_from (const itype &)
tech_effect_data load_tech_effect_data (const JsonObject &e)
void load_technique (const JsonObject &jo, const std::string &src)
void load_martial_art (const JsonObject &jo, const std::string &src)
void check_martialarts ()
void clear_techniques_and_martial_arts ()
void finalize_martial_arts ()
std::string martialart_difficulty (const matype_id &mstyle)
std::vector< matype_id > all_martialart_types ()
std::vector< matype_id > autolearn_martialart_types ()
Variables
const matec_id tec_none
Macro Definition Documentation
CATA_SRC_MARTIALARTS_H
#define CATA_SRC_MARTIALARTS_H
Definition at line 3 of file martialarts.h.
Function Documentation
all_martialart_types()
std::vector<matype_id> all_martialart_types ()
Definition at line 454 of file martialarts.cpp.
 {
     std::vector<matype_id> result;
     for( const martialart &ma : martialarts.get_all() ) {
         result.push_back( ma.id );
     }
     return result;
 }
References anonymous_namespace{martialarts.cpp}::martialarts.
Referenced by debug_menu::debug().
autolearn_martialart_types()
std::vector<matype_id> autolearn_martialart_types ()
Definition at line 463 of file martialarts.cpp.
 {
     std::vector<matype_id> result;
     for( const martialart &ma : martialarts.get_all() ) {
         if( ma.autolearn_skills.empty() ) {
             continue;
         }
         result.push_back( ma.id );
     }
     return result;
 }
References anonymous_namespace{martialarts.cpp}::martialarts.
Referenced by Character::process_turn().
check_martialarts()
void check_martialarts ()
Definition at line 502 of file martialarts.cpp.
 {
     for( const martialart &ma : martialarts.get_all() ) {
         for( auto technique = ma.techniques.cbegin();
              technique != ma.techniques.cend(); ++technique ) {
             if( !technique->is_valid() ) {
                 debugmsg( "Technique with id %s in style %s doesn't exist.",
                           technique->c_str(), ma.name );
             }
         }
         for( auto weapon = ma.weapons.cbegin();
              weapon != ma.weapons.cend(); ++weapon ) {
             if( !item::type_is_defined( *weapon ) ) {
                 debugmsg( "Weapon %s in style %s doesn't exist.",
                           weapon->c_str(), ma.name );
             }
         }
     }
     for( const ma_technique &t : ma_techniques.get_all() ) {
         ::check( t.reqs, string_format( "technique %s", t.id.c_str() ) );
     }
     for( const ma_buff &b : ma_buffs.get_all() ) {
         ::check( b.reqs, string_format( "buff %s", b.id.c_str() ) );
     }
 }
References b, check(), debugmsg, anonymous_namespace{martialarts.cpp}::ma_buffs, anonymous_namespace{martialarts.cpp}::ma_techniques, anonymous_namespace{martialarts.cpp}::martialarts, string_format(), and item::type_is_defined().
Referenced by DynamicDataLoader::check_consistency().
clear_techniques_and_martial_arts()
void clear_techniques_and_martial_arts ()
Definition at line 587 of file martialarts.cpp.
 {
     martialarts.reset();
     ma_buffs.reset();
     ma_techniques.reset();
 }
References anonymous_namespace{martialarts.cpp}::ma_buffs, anonymous_namespace{martialarts.cpp}::ma_techniques, and anonymous_namespace{martialarts.cpp}::martialarts.
Referenced by DynamicDataLoader::unload_data().
finalize_martial_arts()
void finalize_martial_arts ()
Definition at line 558 of file martialarts.cpp.
 {
     // This adds an effect type for each ma_buff, so we can later refer to it and don't need a
     // redundant definition of those effects in json.
     for( const ma_buff &buff : ma_buffs.get_all() ) {
         const ma_buff_effect_type new_eff( buff );
         // Note the slicing here: new_eff is converted to a plain effect_type, but this doesn't
         // bother us because ma_buff_effect_type does not have any members that can be sliced.
         effect_type::register_ma_buff_effect( new_eff );
     }
 }
References anonymous_namespace{martialarts.cpp}::ma_buffs, and effect_type::register_ma_buff_effect().
Referenced by DynamicDataLoader::finalize_loaded_data().
load_martial_art()
void load_martial_art (const JsonObject & jo, const std::string & src)
Definition at line 340 of file martialarts.cpp.
 {
     martialarts.load( jo, src );
 }
References anonymous_namespace{martialarts.cpp}::martialarts.
Referenced by DynamicDataLoader::initialize().
load_tech_effect_data()
tech_effect_data load_tech_effect_data (const JsonObject & e)
Definition at line 170 of file martialarts.cpp.
 {
     return tech_effect_data( efftype_id( e.get_string( "id" ) ), e.get_int( "duration", 0 ),
                              e.get_bool( "permanent", false ), e.get_bool( "on_damage", true ),
                              e.get_int( "chance", 100 ), e.get_string( "message", "" ),
                              json_character_flag( e.get_string( "req_flag", "NULL" ) ) );
 }
References JsonObject::get_bool(), JsonObject::get_int(), and JsonObject::get_string().
Referenced by tech_effect_reader::get_next().
load_technique()
void load_technique (const JsonObject & jo, const std::string & src)
Definition at line 124 of file martialarts.cpp.
 {
     ma_techniques.load( jo, src );
 }
References anonymous_namespace{martialarts.cpp}::ma_techniques.
Referenced by DynamicDataLoader::initialize().
martial_art_learned_from()
matype_id martial_art_learned_from (const itype & type)
Definition at line 109 of file martialarts.cpp.
 {
     if( !type.can_use( "MA_MANUAL" ) ) {
         return {};
     }
     if( !type.book || type.book->martial_art.is_null() ) {
         debugmsg( "Item '%s' which claims to teach a martial art is missing martial_art",
                   type.get_id().str() );
         return {};
     }
     return type.book->martial_art;
 }
References debugmsg.
Referenced by item::book_info(), item::color_in_inventory(), avatar::identify(), iuse::ma_manual(), read_activity_actor::player_readma(), and avatar::read().
martialart_difficulty()
std::string martialart_difficulty (const matype_id & mstyle)
Definition at line 570 of file martialarts.cpp.
 {
     std::string diff;
     if( mstyle->learn_difficulty <= 2 ) {
         diff = _( "easy" );
     } else if( mstyle->learn_difficulty <= 4 ) {
         diff = _( "moderately hard" );
     } else if( mstyle->learn_difficulty <= 6 ) {
         diff = _( "hard" );
     } else if( mstyle->learn_difficulty <= 8 ) {
         diff = _( "very hard" );
     } else {
         diff = _( "extremely hard" );
     }
     return diff;
 }
References _, and martialart::learn_difficulty.
Referenced by item::book_info(), and avatar::identify().
Variable Documentation
tec_none
const matec_id tec_none extern