Cataclysm DDA: src/material.cpp File Reference
material.cpp File Reference
#include "material.h"
#include <algorithm>
#include <iterator>
#include <map>
#include <set>
#include "assign.h"
#include "calendar.h"
#include "debug.h"
#include "generic_factory.h"
#include "item.h"
#include "json.h"
#include "make_static.h"
Namespaces
anonymous_namespace{material.cpp}
io
Functions
template<>
std::string io::enum_to_string< breathability_rating > (breathability_rating data)
static mat_burn_data load_mat_burn_data (const JsonObject &jsobj)
Variables
generic_factory< material_type > anonymous_namespace{material.cpp}::material_data ("material")
Function Documentation
load_mat_burn_data()
static mat_burn_data load_mat_burn_data (const JsonObject & jsobj) static
Definition at line 70 of file material.cpp.
 {
     mat_burn_data bd;
     assign( jsobj, "immune", bd.immune );
     assign( jsobj, "volume_per_turn", bd.volume_per_turn );
     jsobj.read( "fuel", bd.fuel );
     jsobj.read( "smoke", bd.smoke );
     jsobj.read( "burn", bd.burn );
     return bd;
 }
References assign(), mat_burn_data::burn, mat_burn_data::fuel, mat_burn_data::immune, JsonObject::read(), mat_burn_data::smoke, and mat_burn_data::volume_per_turn.
Referenced by material_type::load().