Cataclysm DDA: src/math_parser_diag.cpp File Reference
math_parser_diag.cpp File Reference
#include "math_parser_diag.h"
#include <functional>
#include <string>
#include <vector>
#include "calendar.h"
#include "condition.h"
#include "dialogue.h"
#include "field.h"
#include "game.h"
#include "magic.h"
#include "map.h"
#include "math_parser_diag_value.h"
#include "mongroup.h"
#include "mtype.h"
#include "options.h"
#include "string_input_popup.h"
#include "units.h"
#include "weather.h"
#include "worldfactory.h"
Namespaces
anonymous_namespace{math_parser_diag.cpp}
Typedefs
template<class ID >
using anonymous_namespace{math_parser_diag.cpp}::f_monster_match = bool(*)(Creature const &critter, ID const &id)
Enumerations
enum class anonymous_namespace{math_parser_diag.cpp}::character_filter : int { anonymous_namespace{math_parser_diag.cpp}::allies = 0 , anonymous_namespace{math_parser_diag.cpp}::not_allies , anonymous_namespace{math_parser_diag.cpp}::hostile , anonymous_namespace{math_parser_diag.cpp}::any }
enum class anonymous_namespace{math_parser_diag.cpp}::mon_filter : int { anonymous_namespace{math_parser_diag.cpp}::enemies = 0 , anonymous_namespace{math_parser_diag.cpp}::friends , anonymous_namespace{math_parser_diag.cpp}::both }
Functions
bool anonymous_namespace{math_parser_diag.cpp}::is_beta (char scope)
constexpr bool anonymous_namespace{math_parser_diag.cpp}::is_true (double dbl)
template<typename T >
constexpr std::string_view anonymous_namespace{math_parser_diag.cpp}::_str_type_of ()
template<typename T >
T anonymous_namespace{math_parser_diag.cpp}::_read_from_string (std::string_view s, const std::vector< std::pair< std::string, T >> &units)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::u_val (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::u_val_ass (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::option_eval (char, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::addiction_intensity_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::addiction_turns_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::addiction_turns_ass (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::armor_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::charge_count_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::coverage_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::distance_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::damage_level_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::effect_intensity_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::encumbrance_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::faction_like_eval (char, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::faction_like_ass (char, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::faction_respect_eval (char, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::faction_respect_ass (char, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::faction_trust_eval (char, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::faction_trust_ass (char, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::field_strength_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::gun_damage_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::has_trait_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::has_flag_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::has_var_eval (char, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::knows_proficiency_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::hp_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::hp_ass (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::spellcasting_adjustment_ass (char scope, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::hp_max_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::item_count_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::item_rad_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::num_input_eval (char, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::attack_speed_eval (char scope, std::vector< diag_value > const &, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::melee_damage_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::mod_order_eval (char, std::vector< diag_value > const &params, diag_kwargs const &)
bool anonymous_namespace{math_parser_diag.cpp}::_friend_match_filter_character (Character const &beta, Character const &guy, character_filter filter)
bool anonymous_namespace{math_parser_diag.cpp}::_filter_character (Character const *beta, Character const &guy, int radius, tripoint_abs_ms const &loc, character_filter filter, bool allow_hallucinations)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::_characters_nearby_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::characters_nearby_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
bool anonymous_namespace{math_parser_diag.cpp}::mon_check_id (Creature const &critter, mtype_id const &id)
bool anonymous_namespace{math_parser_diag.cpp}::mon_check_species (Creature const &critter, species_id const &id)
bool anonymous_namespace{math_parser_diag.cpp}::mon_check_group (Creature const &critter, mongroup_id const &id)
bool anonymous_namespace{math_parser_diag.cpp}::_matches_attitude_filter (Creature const &critter, mon_filter filter)
template<class ID >
bool anonymous_namespace{math_parser_diag.cpp}::_filter_monster (Creature const &critter, std::vector< ID > const &ids, int radius, tripoint_abs_ms const &loc, f_monster_match< ID > f, mon_filter filter)
template<class ID >
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::_monsters_nearby_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &kwargs, f_monster_match< ID > f)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::monsters_nearby_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::monster_species_nearby_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::monster_groups_nearby_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::moon_phase_eval (char, std::vector< diag_value > const &, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::pain_eval (char scope, std::vector< diag_value > const &, diag_kwargs const &kwargs)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::pain_ass (char scope, std::vector< diag_value > const &, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::energy_eval (char, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::school_level_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::school_level_adjustment_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::school_level_adjustment_ass (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::skill_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::skill_ass (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::skill_exp_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::skill_exp_ass (char scope, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::spell_count_eval (char scope, std::vector< diag_value > const &, diag_kwargs const &kwargs)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::spell_sum_eval (char scope, std::vector< diag_value > const &, diag_kwargs const &kwargs)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::spell_exp_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::spell_exp_for_level_eval (char, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::spell_exp_ass (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::spell_level_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::spell_level_ass (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::spell_level_adjustment_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::spell_level_adjustment_ass (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
double anonymous_namespace{math_parser_diag.cpp}::_time_in_unit (double time, std::string_view unit)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::time_eval (char, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::time_ass (char, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::time_since_eval (char, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::time_until_eval (char, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::time_until_eoc_eval (char, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::proficiency_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::proficiency_ass (char scope, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
double anonymous_namespace{math_parser_diag.cpp}::_test_add (diag_value const &v, dialogue const &d)
double anonymous_namespace{math_parser_diag.cpp}::_test_len (diag_value const &v, dialogue const &d)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::_test_func (std::vector< diag_value > const &params, diag_kwargs const &kwargs, double(*f)(diag_value const &v, dialogue const &d))
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::test_diag (char, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::test_str_len (char, std::vector< diag_value > const &params, diag_kwargs const &kwargs)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::value_or_eval (char, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::vision_range_eval (char scope, std::vector< diag_value > const &, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::calories_eval (char scope, std::vector< diag_value > const &, diag_kwargs const &kwargs)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::calories_ass (char scope, std::vector< diag_value > const &, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::vitamin_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::vitamin_ass (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::warmth_eval (char scope, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::weather_eval (char, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< void(dialogue &, double)> anonymous_namespace{math_parser_diag.cpp}::weather_ass (char, std::vector< diag_value > const &params, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::climate_control_str_heat_eval (char scope, std::vector< diag_value > const &, diag_kwargs const &)
std::function< double(dialogue &)> anonymous_namespace{math_parser_diag.cpp}::climate_control_str_chill_eval (char scope, std::vector< diag_value > const &, diag_kwargs const &)
std::map< std::string_view, dialogue_func_eval > const & get_all_diag_eval_funcs ()
std::map< std::string_view, dialogue_func_ass > const & get_all_diag_ass_funcs ()
Variables
static const json_character_flag json_flag_MUTATION_THRESHOLD ("MUTATION_THRESHOLD")
std::map< std::string_view, dialogue_func_eval > const anonymous_namespace{math_parser_diag.cpp}::dialogue_eval_f
std::map< std::string_view, dialogue_func_ass > const anonymous_namespace{math_parser_diag.cpp}::dialogue_assign_f
Function Documentation
get_all_diag_ass_funcs()
std::map<std::string_view, dialogue_func_ass> const& get_all_diag_ass_funcs ()
Definition at line 1615 of file math_parser_diag.cpp.
 {
     return dialogue_assign_f;
 }
References anonymous_namespace{math_parser_diag.cpp}::dialogue_assign_f.
Referenced by anonymous_namespace{math_parser.cpp}::get_dialogue_ass().
get_all_diag_eval_funcs()
std::map<std::string_view, dialogue_func_eval> const& get_all_diag_eval_funcs ()
Definition at line 1611 of file math_parser_diag.cpp.
 {
     return dialogue_eval_f;
 }
References anonymous_namespace{math_parser_diag.cpp}::dialogue_eval_f.
Referenced by anonymous_namespace{math_parser.cpp}::get_dialogue_eval(), and jmath_func::load().
Variable Documentation
json_flag_MUTATION_THRESHOLD
const json_character_flag json_flag_MUTATION_THRESHOLD("MUTATION_THRESHOLD") ("MUTATION_THRESHOLD") static
Referenced by anonymous_namespace{math_parser_diag.cpp}::has_flag_eval().