Cataclysm DDA: src/math_parser_diag.h File Reference
math_parser_diag.h File Reference
#include <functional>
#include <map>
#include <string_view>
#include <vector>
Classes
struct dialogue_func
struct dialogue_func_eval
struct dialogue_func_ass
Macros
#define CATA_SRC_MATH_PARSER_DIAG_H
Typedefs
using diag_kwargs = std::map< std::string, deref_diag_value >
using pdiag_func_eval = dialogue_func_eval const *
using pdiag_func_ass = dialogue_func_ass const *
Functions
std::map< std::string_view, dialogue_func_eval > const & get_all_diag_eval_funcs ()
std::map< std::string_view, dialogue_func_ass > const & get_all_diag_ass_funcs ()
Macro Definition Documentation
CATA_SRC_MATH_PARSER_DIAG_H
#define CATA_SRC_MATH_PARSER_DIAG_H
Definition at line 3 of file math_parser_diag.h.
Typedef Documentation
diag_kwargs
using diag_kwargs = std::map<std::string, deref_diag_value>
Definition at line 12 of file math_parser_diag.h.
pdiag_func_ass
using pdiag_func_ass = dialogue_func_ass const *
Definition at line 42 of file math_parser_diag.h.
pdiag_func_eval
using pdiag_func_eval = dialogue_func_eval const *
Definition at line 41 of file math_parser_diag.h.
Function Documentation
get_all_diag_ass_funcs()
std::map<std::string_view, dialogue_func_ass> const& get_all_diag_ass_funcs ()
Definition at line 1615 of file math_parser_diag.cpp.
 {
     return dialogue_assign_f;
 }
References anonymous_namespace{math_parser_diag.cpp}::dialogue_assign_f.
Referenced by anonymous_namespace{math_parser.cpp}::get_dialogue_ass().
get_all_diag_eval_funcs()
std::map<std::string_view, dialogue_func_eval> const& get_all_diag_eval_funcs ()
Definition at line 1611 of file math_parser_diag.cpp.
 {
     return dialogue_eval_f;
 }
References anonymous_namespace{math_parser_diag.cpp}::dialogue_eval_f.
Referenced by anonymous_namespace{math_parser.cpp}::get_dialogue_eval(), and jmath_func::load().