Cataclysm DDA: src/math_parser_func.h File Reference
math_parser_func.h File Reference
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdlib>
#include <string>
#include <string_view>
#include <vector>
#include "rng.h"
#include "units.h"
Classes
struct math_func
struct math_const
Namespaces
math_constants
Macros
#define CATA_SRC_MATH_PARSER_FUNC_H
Typedefs
using pmath_func = math_func const *
using pmath_const = math_const const *
Functions
double abs (std::vector< double > const &params)
double max (std::vector< double > const &params)
double min (std::vector< double > const &params)
double math_rng (std::vector< double > const &params)
double rand (std::vector< double > const &params)
double sqrt (std::vector< double > const &params)
double log (std::vector< double > const &params)
double sin (std::vector< double > const &params)
double cos (std::vector< double > const &params)
double tan (std::vector< double > const &params)
double clamp (std::vector< double > const &params)
double floor (std::vector< double > const &params)
double ceil (std::vector< double > const &params)
double trunc (std::vector< double > const &params)
double round (std::vector< double > const &params)
constexpr double test_ (std::vector< double > const &)
double celsius_from_kelvin (std::vector< double > const &params)
double fahrenheit_from_kelvin (std::vector< double > const &params)
double celsius_to_kelvin (std::vector< double > const &params)
double fahrenheit_to_kelvin (std::vector< double > const &params)
std::vector< std::string_view > tokenize (std::string_view str, std::string_view separators, bool include_seps=true)
Variables
constexpr std::array< math_func, 20 > functions
constexpr double math_constants::pi_v = 3.14159265358979323846
constexpr double math_constants::e_v = 2.7182818284590452354
constexpr std::array< math_const, 5 > constants
Macro Definition Documentation
CATA_SRC_MATH_PARSER_FUNC_H
#define CATA_SRC_MATH_PARSER_FUNC_H
Definition at line 3 of file math_parser_func.h.
Typedef Documentation
pmath_const
using pmath_const = math_const const *
Definition at line 28 of file math_parser_func.h.
pmath_func
using pmath_func = math_func const *
Definition at line 22 of file math_parser_func.h.
Function Documentation
abs()
double abs (std::vector< double > const & params) inline
Definition at line 30 of file math_parser_func.h.
 {
     return std::abs( params[0] );
 }
Referenced by trade_ui::_draw_header(), point::abs(), tripoint::abs(), units::abs(), mattack::acid(), vehicle::act_on_map(), computer_session::action_amigara_log(), Character::activate_bionic(), tileray::advance(), alcohol(), map::apply_light_ray(), assemble_stat_details(), Character::bionics_install_failure(), Character::bionics_uninstall_failure(), Character::book_fun_for(), bresenham(), Character::burn_fuel(), game::calc_driving_offset(), item::calc_temp(), overmap::calculate_ocean_gradient(), basecamp::camp_food_supply(), can_do_activity_there(), spell::cast_all_effects(), character_push_effects(), requirement_data::check_enough_materials(), craft_command::check_item_components_missing(), map::clear_path(), talk_function::commune_refuge_caravan(), vehicle::autodrive_controller::compute_next_nodes(), vehicle::autodrive_controller::compute_node_score(), Character::consume_items(), craft_command::continue_prompt_liquids(), map::could_see_items(), vehicle::cruise_thrust(), vehicle::current_acceleration(), spell::damage_string(), vehicle_part::deserialize(), spell_effect::directed_push(), point::distance_manhattan(), vehicle::do_autodrive(), map::draw_lab(), draw_points(), map::draw_slimepit(), draw_speed_info(), draw_speed_tab(), draw_stats_info(), draw_stats_summary(), draw_x_info(), eat(), eff_fun_sleep(), Character::evaluate_techniques(), npc_attack_spell::evaluate_tripoint(), map::find_clear_path(), vehicle::find_lines_of_parts(), pf::find_overmap_path(), item::food_info(), format_volume(), suffer::from_other_mutations(), real_coords::fromabs(), Character::fun_for(), vehicle::gain_moves(), rotatable_symbols::get(), get_collision_factor(), ma_technique::get_description(), map::get_moving_vehicle_targets(), Character::get_next_auto_move_direction(), get_normalized_angle(), get_score_text(), get_signal_for_hordes(), scent_map::get_unsafe(), widget::get_var_value(), overmapbuffer::get_vehicle_ter_sym(), overmapbuffer::get_vehicle_tile_id(), game::grabbed_furn_move(), game::grabbed_veh_move(), item::gun_recoil(), handbrake(), tool_comp::has(), item_comp::has(), Character::healing_rate(), scent_map::inbounds(), game::is_in_viewport(), vehicle::is_wheel_state_correct_to_turn_on_rails(), iexamine::ledge(), character_modifier::load(), magical_polymorph(), manhattan_dist(), mapgen_forest(), math_abs(), item::med_info(), vehicle::merge_appliance_into_grid(), Character::modify_stimulation(), inventory::most_appropriate_painkiller(), avatar_action::move(), npc::move_away_from(), monster::move_to(), map::move_vehicle(), MapExtras::mx_helicopter(), npc_trading::net_price_adjustment(), player_morale::morale_point::normalize_bonus(), map::obstacle_coverage(), octile_dist(), octile_dist_exact(), offset_to_sun_altitude(), monster::on_load(), coords::origin_from_scale(), display::overmap_tile_symbol_color(), vehicle::part_collision(), Character::pause(), Character::perform_technique(), fixed_overmap_special_data::place(), overmap::place_mongroups(), overmap::place_river(), pools_to_string(), display::power_balance_text_color(), avatar::power_mutations(), vehicle::power_parts(), vehicle::precalculate_vehicle_turning(), price_adjustment(), vehicle::print_fuel_indicator(), vehicle::print_speed_gauge(), monster::process_triggers(), monster::push_to(), advanced_inventory::recalc_pane(), Character::recoil_vehicle(), map::route(), sane_consume_items(), game::save_cyborg(), map::saven(), scatter_chunks(), monster::scent_move(), Character::sees(), Creature::sees(), map::sees(), Character::select_item_component(), vehicle::selfdrive(), multiline_list::set_entry_pos(), vehicle::set_tow_directions(), map::shake_vehicle(), map::shift(), vehicle::should_enable_fake(), slope::slope(), vehicle::slowdown(), vehicle::smart_controller_handle_turn(), spell::sound_volume(), spell_effect::spawn_summoned_monster(), square_dist(), square_dist_fast(), squares_closer_to(), vehicle::strain(), display::sundial_text_color(), vehicle::thrust(), tool_comp::to_string(), item_comp::to_string(), vehicle::transform_terrain(), vehicle::update_alternator_load(), Character::update_bodytemp(), player_morale::update_bodytemp_penalty(), item::update_link_traits(), map::valid_move(), npc::vehicle_danger(), map::vehicle_vehicle_collision(), game::vertical_move(), Character::vitamin_mod(), suffer::water_damage(), Character::weariness_transition_level(), Character::weariness_transition_progress(), iuse::weather_tool(), scenario::weighted_random(), and scenario::weighted_random_profession().
ceil()
double ceil (std::vector< double > const & params) inline
Definition at line 100 of file math_parser_func.h.
 {
     return std::ceil( params[0] );
 }
Referenced by tgz_archiver::add_file(), npc_trading::adjusted_price(), item_contents::ammo_consume(), map::apply_light_arc(), Character::apply_persistent_morale(), trade_ui::autobalance(), spell_effect::banishment(), butchery_drops_harvest(), Character::calc_all_parts_hp(), veh_interact::calc_lift_requirements(), veh_utils::calc_xp_gain(), castLight(), spell::exp_for_level(), vehicles::parts::finalize(), Item_factory::finalize_pre(), activity_handlers::generic_game_turn_handler(), Character::get_bmr(), item::get_encumber(), talker_character_const::get_fine_detail_vision_mod(), get_light_level(), clothing_mod::get_mod_val(), get_signal_for_hordes(), spell_effect::guilt(), hack_attempt(), repair_item_actor::handle_components(), jack_quality(), SkillLevel::knowledge_train(), melee_train(), monster::move_to(), npc::move_to(), monster::on_load(), overmap::place_mongroups(), main_menu::print_menu_items(), repair_inventory_preset::repair_inventory_preset(), round_up(), activity_tracker::try_reduce_weariness(), Character::update_stamina(), and game::walk_move().
celsius_from_kelvin()
double celsius_from_kelvin (std::vector< double > const & params) inline
Definition at line 120 of file math_parser_func.h.
 {
     return units::to_celsius( units::from_kelvin( params[0] ) );
 }
References units::from_kelvin(), and units::to_celsius().
celsius_to_kelvin()
double celsius_to_kelvin (std::vector< double > const & params) inline
Definition at line 130 of file math_parser_func.h.
 {
     return units::to_kelvin( units::from_celsius( params[0] ) );
 }
References units::from_celsius(), and units::to_kelvin().
clamp()
double clamp (std::vector< double > const & params) inline
Definition at line 86 of file math_parser_func.h.
 {
     if( params[2] < params[1] ) {
         debugmsg( "clamp called with hi < lo (%f < %f)", params[2], params[1] );
         return params[0];
     }
     return std::clamp( params[0], params[1], params[2] );
 }
References debugmsg.
cos()
double cos (std::vector< double > const & params) inline
Definition at line 76 of file math_parser_func.h.
 {
     return std::cos( params[0] );
 }
Referenced by calc_ray_end(), units::cos(), get_common_data(), mapgen_forest(), offset_to_sun_altitude(), vehicle::part_vpower_w(), proficiency_time_malus(), projectile_attack(), rl_vec2d::rotated(), rl_vec3d::rotated(), sun_azimuth_altitude(), sun_ra_declination(), sunlight_angle(), teleport::teleport(), and weather_temperature_from_common_data().
fahrenheit_from_kelvin()
double fahrenheit_from_kelvin (std::vector< double > const & params) inline
Definition at line 125 of file math_parser_func.h.
 {
     return units::to_fahrenheit( units::from_kelvin( params[0] ) );
 }
References units::from_kelvin(), and units::to_fahrenheit().
fahrenheit_to_kelvin()
double fahrenheit_to_kelvin (std::vector< double > const & params) inline
Definition at line 135 of file math_parser_func.h.
 {
     return units::to_kelvin( units::from_fahrenheit( params[0] ) );
 }
References units::from_fahrenheit(), and units::to_kelvin().
floor()
double floor (std::vector< double > const & params) inline
Definition at line 95 of file math_parser_func.h.
 {
     return std::floor( params[0] );
 }
Referenced by Character::activity_level_index(), display::activity_level_str(), overmap::add_mon_group(), item::aggregated_contents(), map::apply_light_arc(), trade_ui::autobalance(), Character::best_part_to_smash(), Character::body_window(), mdeath::broken(), Character::calc_bmi_encumb(), skill_boost::calc_bonus(), anonymous_namespace{gates.cpp}::gate_data::check(), deploy_tent_actor::check_intact(), map::create_burnproducts(), Character::disp_info(), draw_proficiencies_tab(), drop_or_embed_projectile(), Item_factory::finalize_pre(), suffer::from_artifact_resonance(), get_bar(), Character::get_bmi_lean(), stomach_contents::get_digest_rates(), Character::get_healthy_kcal(), spell::get_level(), Character::height_string(), Character::initialize(), anonymous_namespace{gates.cpp}::gate_data::load(), deploy_tent_actor::load(), mdeath::normal(), Character::on_try_dodge(), open_movement_mode_menu(), tileray::quadrant(), avatar::reset_stats(), Creature::sees(), Character::set_stored_calories(), mdeath::splatter(), activity_tracker::try_reduce_weariness(), item::update_link_traits(), known_magic::update_mana(), Character::update_stomach(), deploy_tent_actor::use(), and widget::value_color().
log()
double log (std::vector< double > const & params) inline
Definition at line 66 of file math_parser_func.h.
 {
     return std::log( params[0] );
 }
Referenced by computer_session::action_research(), item::calc_temp(), cluster_sounds(), explosion_data::expected_range(), book_proficiency_bonuses::fail_factor(), spell::get_level(), LIGHT_RANGE(), mapgen_forest(), vehicle::part_collision(), Character::sight_range(), and book_proficiency_bonuses::time_factor().
math_rng()
double math_rng (std::vector< double > const & params) inline
Definition at line 51 of file math_parser_func.h.
 {
     return rng_float( params[0], params[1] );
 }
References rng_float().
max()
double max (std::vector< double > const & params) inline
Definition at line 35 of file math_parser_func.h.
 {
     if( params.empty() ) {
         return 0;
     }
     return *std::max_element( params.begin(), params.end() );
 }
Referenced by item_pocket::_can_contain(), item::_environmental_resist(), anonymous_namespace{clzones.cpp}::_rotate_zone(), anonymous_namespace{item.cpp}::_stacks_rot(), Character::absorb_hit(), mattack::absorb_items(), spell::accuracy(), Creature::accuracy_projectile_attack(), npc::act_on_danger_assessment(), Character::active_light(), Character::activity_level(), activity_on_turn_move_loot(), event_summary::add(), player_morale::morale_point::add(), map::add_light_source(), overmap::add_mon_group(), Character::add_msg_player_or_say(), ff::add_span(), Character::adjust_for_focus(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::advance(), npc::aim(), Character::aim_factor_from_length(), Character::aim_factor_from_volume(), Character::aim_per_move(), item_contents::ammo_consume(), item_stack::amount_can_fit(), spell::aoe(), map::apparent_light_helper(), scrollbar::apply(), jmapgen_corpse::apply(), jmapgen_monster::apply(), jmapgen_objects::apply(), scent_block::apply_gas(), map::apply_light_ray(), map::apply_light_source(), scent_block::apply_slime(), Character::apply_wetness_morale(), armor_enchantment_adjust(), npc::assess_danger(), Character::attack_speed(), vehicle::autopilot_patrol(), vehicle::balanced_wheel_config(), trade_ui::bank_balance(), map::bash_rating_internal(), map::bash_ter_furn(), Character::best_nearby_lifting_assist(), item_contents::best_quality(), item_pocket::best_quality(), Character::beyond_final_warning(), mattack::bio_op_takedown(), Character::bionic_fuel_check(), bisearch(), blood_magic(), Character::body_window(), bound_mod_to_vals(), mdeath::broken(), vehicle::build_bike_rack_menu(), activity_handlers::build_do_turn(), io::build_enum_lookup_map(), vehicle::build_interact_menu(), map::build_map_cache(), map::build_obstacle_cache(), Character::burn_move_stamina(), butcher_time_to_cut(), butchery_drops_harvest(), veh_interact::cache_tool_availability(), Character::calc_all_parts_hp(), Character::calc_bmi_encumb(), skill_boost::calc_bonus(), talk_trial::calc_chance(), uilist::calc_data(), player_difficulty::calc_dps_value(), game::calc_driving_offset(), armor_portion_data::calc_encumbrance(), npc_trading::calc_npc_owes_you(), player_difficulty::calc_social_value(), calc_spell_training_cost_gen(), calc_steadiness(), veh_utils::calc_xp_gain(), overmap::calculate_ocean_gradient(), overmap::calculate_urbanity(), leap_actor::call(), Character::can_continue_craft(), install_bionic_actor::can_use(), cap_to_size(), cast_horizontal_zlight_segment(), cast_vertical_zlight_segment(), spell::casting_time(), spell::casting_time_encumbered(), castLight(), center_print(), debug_menu::change_spells(), jmapgen_vehicle::check(), jmapgen_nested::check(), small_literal_vector< T, kInlineCount, SizeT >::check_capacity(), craft_command::check_item_components_missing(), Character::check_mount_is_spooked(), game::check_safe_mode_allowed(), item::chip_resistance(), teleporter_list::choose_teleport_location(), clamp(), map::climb_difficulty(), closest_points_first(), outfit::clothing_wetness_mult(), cluster_sounds(), folded_text::codepoint_coordinates(), vehicle::coeff_air_drag(), vehicle::coeff_water_drag(), outfit::collar_warmth(), vehicle::collision(), item::combine(), comestible_inventory_preset::comestible_inventory_preset(), scent_block::commit_modifications(), talk_function::companion_skill_trainer(), npc::complain(), Character::complete_craft(), Character::compute_effective_food_volume_ratio(), vehicle::autodrive_controller::compute_next_nodes(), vehicle::autodrive_controller::compute_node_score(), vehicle::autodrive_controller::compute_profile(), npc::confident_shoot_range(), requirement_data::consolidate(), npc::consume_food(), npc::consume_food_from_camp(), vehicle::consume_fuel(), smart_controller_ui::control(), coords::coord_max(), Pickup::cost_to_move_item(), Character::crafting_failure_roll(), Character::crafting_speed_multiplier(), Character::crafting_success_roll(), string_input_popup::create_window(), create_zone_callback(), Character::crit_chance(), item::current_reach_range(), Character::current_warnings_fac(), salvage_actor::cut_up(), iexamine::cvdmachine(), spell::damage(), item::damage_adjusted_armor_resist(), item::damage_adjusted_gun_damage(), item::damage_adjusted_melee_weapon_damage(), vehicle::damage_all(), vehicle::damage_direct(), spell::damage_dot(), item::damage_melee(), damage_targets(), Creature::deal_damage(), Creature::deal_damage_handle_type(), Creature::deal_melee_hit(), scent_map::decay(), harvest_list::describe(), numeric_interval< T, typename >::deserialize(), spell_effect::directed_push(), avatar::disp_medical(), game::disp_NPC_epilogues(), advanced_inventory::display(), player_morale::display(), game::display_faction_epilogues(), veh_interact::display_stats(), Character::dispose_item(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::distance(), do_aim(), explosion_handler::do_blast(), anonymous_namespace{iexamine.cpp}::atm_menu::do_exchange_cash(), veh_interact::do_install(), npc::do_reload(), iuse_transform::do_transform(), craft_activity_actor::do_turn(), move_items_activity_actor::do_turn(), safecracking_activity_actor::do_turn(), Character::dodge_roll(), map::draw(), inventory_column::draw(), scent_map::draw(), string_input_popup::draw(), overmap_ui::draw_ascii(), overmap_ui::draw_camp_labels(), draw_can_craft_indicator(), overmap_ui::draw_city_labels(), draw_connectors(), anonymous_namespace{diary_ui.cpp}::draw_diary_border(), inventory_selector::draw_footer(), help::draw_menu(), worldfactory::draw_modselection_borders(), game::draw_panels(), draw_skills_info(), draw_spellbook_info(), draw_stats_tab(), drop_or_embed_projectile(), spell::duration(), Character::echo_pulse(), eff_fun_fungus(), eff_fun_hot(), item::effective_dps(), iuse::emf_passive_on(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::emplace(), bodypart::encumb_adjusted_limb_value(), spell::energy_cost(), spell::energy_cost_encumbered(), vehicle::engine_cold_factor(), small_literal_vector< T, kInlineCount, SizeT >::ensure_capacity_for(), enumerate_lcsorted_with_limit(), Character::env_surgery_bonus(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::erase(), TextJsonIn::error(), Character::estimate_effect_dur(), npc::evaluate_character(), npc::evaluate_monster(), npc::evaluate_self(), npc::evaluate_weapon(), event_statistic_maximum::state::event_added(), Character::exertion_adjusted_move_multiplier(), exosuit_interact::exosuit_interact(), spell::exp_progress(), inventory_column::expand_to_fit(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), faction_template::faction_template(), Character::fall_damage_mod(), farm_action(), Character::fastest_aiming_method_speed(), talk_function::field_harvest(), field_processor_fd_electricity(), activity_handlers::fill_liquid_do_turn(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::fill_skipblock(), recipe_dictionary::finalize(), Single_item_creator::finalize(), uimenu::finalize_addentries(), MonsterGenerator::finalize_mtypes(), Item_factory::finalize_post_armor(), Item_factory::finalize_pre(), map::find_clear_path(), overmapbuffer::find_closest(), find_minimum_fold_width(), findBestGasDiscount(), Character::fine_detail_vision_mod(), heal_actor::finish_using(), game::fling_creature(), Character::floor_warmth(), folded_text::folded_text(), Character::forced_dismount(), game::forced_door_closing(), mattack::frag(), suffer::from_asthma(), units::from_joule(), units::from_kilojoule(), units::from_kilowatt(), units::from_watt(), map::function_over(), iexamine::gaspump(), relic_procgen_data::generate(), overmap::generate_sub(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), map::get_active_items_in_radius(), effect::get_addict_mod(), get_aided_proficiency_level(), TextJsonIn::get_any_int(), get_auto_consume_moves(), effect::get_avg_mod(), get_bar(), get_best_fire(), Character::get_character_parallax(), get_charcoal_charges(), inventory_selector::get_columns_occupancy_ratio(), Character::get_consume_time(), get_corners(), get_degrade_amount(), Character::get_dex(), disable_activity_actor::get_disable_turns(), city::get_distance_from(), Character::get_dodge(), resistances::get_effective_resist(), item::get_encumber(), item::get_env_resist(), get_fire_fuel_string(), Character::get_focus(), inventory_selector::get_footer_min_width(), player_difficulty::get_genetics_difficulty(), inventory_selector::get_header_min_width(), get_heat_radiation(), talker_character_const::get_highest_spell_level(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::get_index_from_iterator(), Character::get_instant_thirst(), TextJsonIn::get_int(), Character::get_int(), TextJsonIn::get_int64(), get_labeled_bar(), inventory_selector::get_layout_width(), spell::get_level(), Character::get_lifestyle(), Character::get_limb_score(), effect::get_limb_score_mod(), Character::get_max_healthy(), gun_actor::get_max_range(), effect::get_mod(), bonus_container::get_mult(), get_normalized_angle(), Character::get_num_crafting_helpers(), get_opt_slider(), Character::get_pain_penalty(), Character::get_per(), Character::get_perceived_pain(), item::get_quality(), item::get_quality_nonrecursive(), Character::get_recipe_weighted_skill_average(), Character::get_shout_volume(), get_signal_for_hordes(), Character::get_speed(), get_speedydex_bonus(), fake_spell::get_spell(), talker_character_const::get_spell_level(), known_magic::get_spellname_max_width(), get_stagger_adjust(), Character::get_str(), json_item_substitution::get_substitution(), TextJsonIn::get_uint(), overmapbuffer::get_vehicle_ter_sym(), overmapbuffer::get_vehicle_tile_id(), map::get_vehicles(), Character::get_vision_threshold(), Character::get_weapon_dispersion(), weather_generator::get_weather(), inventory_column::get_width(), Character::get_wind_resistance(), MonsterGroupManager::GetResultFromGroup(), trapfunc::glass(), game::grabbed_furn_move(), game::grabbed_furn_move_time(), game::grabbed_veh_move(), iuse::granade_act(), pf::greedy_path(), vehicle::ground_acceleration(), gun_battery_mags_drain(), item::gun_dispersion(), item::gun_noise(), item::gun_range(), item::gun_shot_spread_multiplier(), Character::gun_value(), Character::gunmod_installation_odds(), computer_session::hack_attempt(), Character::handle_gun_overheat(), Character::handle_melee_wear(), vehicle::handling_difficulty(), hardcoded_mutation_attack(), iexamine::harvest_plant(), requirement_data::has_comps(), Character::healing_rate_medicine(), Character::heat_emission(), outfit::hood_warmth(), monster::impact(), inc_clamp(), recipe::incorporate_build_reqs(), iuse_transform::info(), Messages::dialog::init(), monster::init_from_item(), vehicle::init_state(), init_window(), initialize_default_custom_panels(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::insert(), inventory_multiselector::inventory_multiselector(), inverse_lerp(), Character::invlet_to_item(), item::io(), map::is_last_ter_wall(), tinymap::is_last_ter_wall(), item_armor_enchantment_adjust(), outfit::item_encumb(), item_filter_rule_string(), Character::item_handling_cost(), item_contents::item_length_modifier(), item_pocket::item_length_modifier(), item_move_cost(), Character::item_reload_cost(), item_pocket::item_size_modifier(), Character::item_wear_cost(), jmapgen_int::jmapgen_int(), vehicle::k_traction(), mattack::kamikaze(), iexamine::keg(), wish_item_callback::key(), layer_item(), vehicle::leak_fuel(), trapfunc::ledge(), item::length(), lerp(), lerp_clamped(), item::lift_strength(), Character::lighting_craft_speed_multiplier(), limit_probability(), limited_shift(), game::list_items(), islot_armor::load(), activity_byproduct::load(), shearing_entry::load(), vehicle_prototype::load(), iuse_transform::load(), place_monster_iuse::load(), Item_factory::load_basic_info(), main_menu::load_character_tab(), jmapgen_objects::load_objects(), load_place_mapings_alternatively(), activity_tracker::log_activity(), logarithmic_range(), overmap_special::longest_side(), game::look_around(), Character::manipulator_score(), mapgen_place_zone(), item::mark_chapter_as_read(), marloss_common(), Character::masticated_volume(), max_aoe_size(), pocket_data::max_contains_volume(), armor_portion_data::max_coverage(), npc::max_credit_extended(), nutrients::max_in_place(), known_magic::max_mana(), scrolling_text_view::max_offset(), visitable::max_quality(), Character::max_quality(), max_quality_from_vpart(), max_quality_internal(), Character::max_single_item_length(), Character::max_single_item_volume(), base_camps::max_upgrade_by_type(), npc::max_willing_to_owe(), melee_train(), Character::melee_value(), vehicle::merge_appliance_into_grid(), Character::metabolic_rate(), display::mission_arrow_offset(), item::mitigate_damage(), Character::mod_daily_health(), Character::mod_dex_bonus(), Character::mod_focus(), Character::mod_int_bonus(), Character::mod_livestyle(), Character::mod_pain(), Character::mod_per_bonus(), Character::mod_rad(), Character::mod_stored_calories(), Character::mod_str_bonus(), Character::mod_thirst(), target_handler::mode_turrets(), character_modifier::modifier(), Item_modifier::modify(), Character::modify_morale(), Character::modify_stimulation(), anonymous_namespace{do_turn.cpp}::monmove(), map::monster_in_field(), monster_plan::monster_plan(), Character::morale_crafting_speed_multiplier(), Character::most_staunchable_bp(), game::mouse_edge_scrolling_terrain(), npc::move_away_from(), map::move_cost_internal(), veh_interact::move_fuel_cursor(), veh_interact::move_overview_line(), multi_projectile_hit_message(), iuse::multicooker_tick(), Character::mutation_height(), npc::mutiny(), iexamine::nanofab(), game::natural_light_level(), neg_INT64_MIN(), neg_INT_MIN(), vehicle::noise_and_smoke(), om_noise::om_noise_layer_forest::noise_at(), mdeath::normal(), map::obstacle_coverage(), obtain_activity_items(), om_carry_weight_to_trips(), Character::on_damage_of_type(), Character::on_dodge(), inventory_multiselector::on_input(), monster::on_load(), query_popup_impl::on_resized(), item::on_wield_cost(), advanced_inv_sorter::operator()(), requirement_data::operator*(), item::overheat_symbol(), Character::overmap_sight_range(), scrolling_text_view::page_up(), ebooksave_activity_actor::pages_in_book(), target_ui::panel_gun_info(), anonymous_namespace{flexbuffer_cache.cpp}::parse_json_to_flexbuffer_(), talker_npc::parse_mod(), vehicle::part_collision(), vehicle::part_vpower_w(), Character::passive_absorb_hit(), Character::pause(), iuse::pick_lock(), pick_one_up(), overmap::pick_random_building_to_place(), worldfactory::pick_world(), activity_handlers::pickaxe_finish(), pit_effectiveness(), overmap::place_building(), overmap::place_cities(), map::place_items(), overmap::place_river(), overmap::place_rivers(), vehicle::place_spawn_items(), overmap::place_specials(), map::place_vending(), map::player_in_field(), read_activity_actor::player_readma(), vehicle::pldrive(), pocket_management_menu(), outfit::pocket_warmth(), map::points_in_radius(), map::points_in_rectangle(), iexamine::portable_structure(), post_absorbed_damage_enchantment_adjust(), avatar::power_bionics(), avatar::power_mutations(), vehicle::power_parts(), proficiency_set::practice(), Character::practice(), Character::practice_proficiency(), predict_recoil(), map_memory::prepare_region(), item::price_no_contents(), string_editor_window::print_editor(), Character::print_encumbrance(), main_menu::print_menu(), game::print_terrain_info(), vehicle::print_vparts_descs(), Character::process_bionic(), item::process_gun_cooling(), sounds::process_sound_markers(), item::process_temperature_rot(), item::process_tool(), monster::process_triggers(), Character::process_turn(), npc::process_turn(), projectile_attack(), anonymous_namespace{iexamine.cpp}::atm_menu::prompt_for_amount(), prompt_for_amount(), proportional_weight(), prying_activity_actor::prying_time(), mattack::pull_metal_weapon(), activity_handlers::pulp_do_turn(), JsonPath::push_back(), monster::push_to(), item::reload_option::qty(), string_input_popup::query_string(), npc::randomize(), spell::range(), Character::ranged_dex_mod(), Character::ranged_per_mod(), rate_food(), item::reach_range(), read_activity_actor::read_book(), target_ui::recalc_aim_turning_penalty(), Character::recipe_success_roll_data(), advanced_inventory::redraw_pane(), smart_controller_ui::refresh(), vehicle::refresh(), Character::regen(), repair_item_actor::repair_chance(), requirements_map(), overmap_special::requires_city(), start_location::requires_city(), game::reset_light_level(), item::resist(), explosion_handler::resonance_cascade(), Character::rest_quality(), mattack::rifle(), right_print(), iuse::robotcontrol(), map::route(), SkillLevel::rust(), inventory::rust_iron_items(), safecracking_activity_actor::safecracking_time(), binomial_distribution::sample(), poisson_distribution::sample(), scatter_chunks(), map::scent_blockers(), scrollable_text(), calendar::season_length(), map::seen_cache_process_ledges(), Creature::sees(), map::sees_cache_key(), select_crafter_and_crafting_recipe(), Character::select_item_component(), known_magic::select_spell(), calendar_ui::select_time_point(), Character::select_tool_component(), weakpoints::select_weakpoint(), item::set_birthday(), memorized_tile::set_dec_rotation(), memorized_tile::set_dec_subtile(), Character::set_dex_bonus(), talk_effect_t::set_effect(), talk_effect_t::set_effect_consequence(), field_entry::set_field_intensity(), vehicle::set_hp(), Character::set_int_bonus(), effect::set_intensity(), Creature::set_pain(), Character::set_painkiller(), Character::set_per_bonus(), Character::set_sleep_deprivation(), Character::set_sleepiness(), set_stats(), Character::set_str_bonus(), memorized_tile::set_ter_rotation(), memorized_tile::set_ter_subtile(), set_traits(), map::shake_vehicle(), map::shoot(), monster::shove_vehicle(), options_manager::show(), safemode::show(), live_view::show(), uilist::show(), worldfactory::show_active_world_mods(), diary::show_diary_ui(), string_input_popup::show_history(), worldfactory::show_worldgen_advanced(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), iexamine::shrub_wildveggies(), overmap::signal_hordes(), tripoint_range< Tripoint >::size(), skill_increment_cost(), game::slip_down_chance(), vehicle::slow_leak(), vehicle::slowdown(), vehicle::smart_controller_handle_turn(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::sort(), outfit::sort_armor(), sound_distance(), spell::sound_volume(), spell_effect::spawn_ethereal_item(), spell::spell_fail(), vehicle::spew_field(), mdeath::splatter(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::splice(), split_span(), item::spoilage_sort_order(), map::spread_gas(), square_dist(), square_dist_fast(), standard_npc::standard_npc(), hacksaw_activity_actor::start(), vehicle::start_engines(), sokoban_game::start_game(), basecamp::start_relay_hide_site(), talk_function::start_training_gen(), stat_points_used(), Character::store(), subindex_around_cursor(), sum_no_wrap(), Character::swim_speed(), mattack::tankgun(), Character::temp_corrected_by_climate_control(), throw_cost(), Character::throw_dispersion_per_dodge(), Character::throwing_dispersion(), throwing_skill_adjusted(), vehicle::thrust(), time_to_attack(), npc::time_to_read(), Character::time_to_read(), monster::to_item(), zone_data::toggle_display(), vehicle::tool_ammo_available(), item::tool_info(), vehicle::total_power(), SkillLevel::train(), avatar::try_break_relax_gas(), try_fuel_fire(), activity_tracker::try_reduce_weariness(), Character::try_remove_grab(), Character::unload(), Character::update_body(), Character::update_body_wetness(), Character::update_bodytemp(), update_fragment_cloud(), update_light(), update_light_quadrants(), item::update_link_traits(), Character::update_needs(), game::update_overmap_seen(), Character::update_stamina(), computer_session::use(), invlet_wrapper::valid(), Character::valid_aoe_technique(), widget::value_color(), vehicle_bounds(), npc::vehicle_danger(), iexamine::vending(), Character::vitamin_mod(), item::volume(), Character::vomit(), game::walk_move(), iuse::wash_items(), vehicle::water_acceleration(), map::water_from(), Character::weapon_value(), Character::weary_threshold(), weather_forecast(), weather_sound(), debug_menu::wishitem(), debug_menu::wishskill(), and game::zones_manager().
min()
double min (std::vector< double > const & params) inline
Definition at line 43 of file math_parser_func.h.
 {
     if( params.empty() ) {
         return 0;
     }
     return *std::min_element( params.begin(), params.end() );
 }
Referenced by map::_add_item_or_charges(), item_pocket::_can_contain(), explosion_handler::_make_explosion(), anonymous_namespace{clzones.cpp}::_rotate_zone(), monster::absorb_hit(), mattack::absorb_meat(), spell::accuracy(), Creature::accuracy_projectile_attack(), npc::act_on_danger_assessment(), advanced_inventory::action_move_item(), computer_session::action_sample(), vehicle::active_reactor_epower(), Character::activity_level(), event_summary::add(), Item_group::add_entry(), Trait_group_collection::add_entry(), map::add_field(), item::add_rain_to_container(), ff::add_span(), map::add_splatter(), outfit::add_stash(), Character::aim_factor_from_length(), Character::aim_per_move(), aim_speed_skill_modifier(), alcohol_effect(), vehicle_part::ammo_capacity(), vehicle_part::ammo_consume(), item::ammo_consume(), Character::ammo_count_for(), item::ammo_set(), vehicle_part::ammo_set(), item_stack::amount_can_fit(), amphetamine_effect(), spell::aoe(), jmapgen_monster::apply(), Character::apply_damage(), weakpoint_effect::apply_to(), Character::apply_wetness_morale(), npc::assess_danger(), trade_ui::autobalance(), vehicle::automatic_fire_turret(), vehicle::autopilot_patrol(), vehicle::balanced_wheel_config(), trade_ui::bank_balance(), map::bash_ter_furn(), iuse::bell(), Character::bionics_adjusted_skill(), Character::bionics_uninstall_failure(), bisearch(), Character::block_hit(), Character::body_window(), bound_mod_to_vals(), mdeath::broken(), activity_handlers::build_do_turn(), map::build_obstacle_cache(), map::build_sunlight_cache(), start_location::burn(), Character::burn_fuel(), butchery_drops_harvest(), Character::calc_all_parts_hp(), talk_trial::calc_chance(), uilist::calc_data(), game::calc_driving_offset(), calc_proficiency_training_time(), item::calc_rot(), overmap::calculate_forestosity(), calculate_shared_column_win_height(), mattack::callblobs(), spell::casting_time(), debug_menu::change_spells(), charges_per_volume_recursive(), jmapgen_vehicle::check(), vehicle::autodrive_controller::check_collision_zone(), game::check_safe_mode_allowed(), item::chip_resistance(), clamp(), map::climb_difficulty(), game::climb_down_menu_gen(), clipped_time(), doors::close_door(), npc_short_term_cache::closest_enemy_to_friendly_distance(), outfit::clothing_wetness_mult(), cluster_sounds(), cocaine_effect(), vehicle::coeff_air_drag(), inventory_column::collate(), vehicle::collision(), companion_combat_rank(), companion_industry_rank(), companion_survival_rank(), Character::complete_disassemble(), iexamine::compost_full(), vehicle::autodrive_controller::compute_next_nodes(), vehicle::autodrive_controller::compute_node_score(), vehicle::autodrive_controller::compute_obstacles_from_enqueued_ramp_points(), vehicle::autodrive_controller::compute_profile(), Character::conduct_blood_analysis(), vehicle_part::consume_energy(), npc::consume_food_from_camp(), Character::consume_ups(), smart_controller_ui::control(), coords::coord_min(), Pickup::cost_to_move_item(), crack_effect(), create_charge_items(), talk_response::create_option_line(), string_input_popup::create_window(), create_zone_callback(), salvage_actor::cut_up(), spell::damage(), vehicle::damage_direct(), spell::damage_dot(), Character::deal_damage(), harvest_list::describe(), diazepam_effect(), npc::die(), stomach_contents::digest(), Character::disassemble(), avatar::disp_medical(), player_morale::display(), talk_function::display_and_choose_opts(), distribute_charge_evenly(), vehicle::do_engine_damage(), melee_actor::do_grab(), do_purify(), npc::do_reload(), disassemble_activity_actor::do_turn(), craft_activity_actor::do_turn(), move_items_activity_actor::do_turn(), anonymous_namespace{iexamine.cpp}::atm_menu::do_withdraw_money(), map::draw(), inventory_column::draw(), scrolling_text_view::draw(), overmap_ui::draw_ascii(), draw_connectors(), target_ui::draw_help_notice(), game::draw_panels(), draw_spellbook_info(), Character::drench(), vehicle::drive_to_local_target(), spell::duration(), eff_fun_hot(), item::effective_dps(), iuse::einktabletpc(), item::energy_consume(), spell::energy_cost(), vehicle::engine_cold_factor(), vehicle::engine_start_time(), iuse::epic_music(), npc::evaluate_character(), npc::evaluate_monster(), npc::evaluate_self(), npc_attack_throw::evaluate_tripoint(), event_statistic_minimum::state::event_added(), SkillLevelMap::exceeds_recipe_requirements(), exosuit_interact::exosuit_interact(), iuse::extinguisher(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), faction_template::faction_template(), farm_action(), Character::fastest_aiming_method_speed(), talk_function::field_harvest(), spell::field_intensity(), field_processor_fd_acid(), field_processor_fd_extinguisher(), activity_handlers::fill_liquid_do_turn(), item_pocket::fill_with(), item::fill_with(), vehicles::parts::finalize(), Single_item_creator::finalize(), uimenu::finalize_addentries(), Item_factory::finalize_post_armor(), map::find_clear_path(), Character::fine_detail_vision_mod(), chop_planks_activity_actor::finish(), Character::fire_gun(), iuse::firecracker_pack_act(), activity_handlers::fish_do_turn(), for_each_item_in_both(), overmap_path_params::for_land_vehicle(), mattack::formblob(), map::function_over(), iexamine::fvat_full(), relic_charge_template::generate(), map::generate_lightmap(), map::get_active_items_in_radius(), effect::get_avg_mod(), Character::get_base_melee_stamina_cost(), item::get_comestible_fun(), get_corners(), monster::get_eff_per(), effect::get_effective_intensity(), inventory_column::get_height(), TextJsonIn::get_int(), TextJsonIn::get_int64(), get_labeled_bar(), get_local_windpower(), effect::get_mod(), get_normalized_angle(), Character::get_num_crafting_helpers(), Character::get_pain_penalty(), monster::get_path_avoid(), npc::get_pathfinding_settings(), player_activity::get_progress_message(), item::get_remaining_capacity_for_liquid(), Character::get_sick(), get_signal_for_hordes(), map::get_vehicles(), Character::get_vision_threshold(), Character::get_weapon_dispersion(), weather_generator::get_weather(), mutable_overmap_placement_rule_remainder::get_weight(), game::grabbed_veh_move(), iuse::granade_act(), item::gun_range(), item::gun_recoil(), Character::gunmod_add(), Character::gunmod_installation_odds(), Character::handle_gun_damage(), Character::hardcoded_effects(), iexamine::harvest_plant(), tool_comp::has(), Character::has_active_bionic(), requirement_data::has_comps(), has_quality_from_vpart(), Character::heal(), Character::heat_emission(), Character::hurtall(), suffer::in_sunlight(), inc_clamp(), monster::increment_pathfinding_cd(), inventory_column::indented_sort_compare(), prof_window::init_ui_windows(), inline_requirements(), inverse_lerp(), Character::invlet_to_item(), vehicle_part::item_capacity(), Character::item_handling_cost(), Character::item_reload_cost(), jack_quality(), mattack::jackson(), vehicle::k_traction(), SkillLevel::knowledgeLevel(), iexamine::ledge(), lerp(), lerp_clamped(), SkillLevel::level(), limit_probability(), limited_shift(), game::list_items(), Character::load(), mtype::load(), vehicle_prototype::load(), jmapgen_objects::load_objects(), logarithmic_range(), game::look_around(), npc::make_angry(), Character::manipulator_score(), mapgen_place_zone(), item_location::max_charges_by_parent_recursive(), vehicle::max_rotor_velocity(), vehicle_stack::max_volume(), Character::melee_attack_abstract(), vehicle::merge_appliance_into_grid(), nutrients::min_in_place(), mine_activity(), display::mission_arrow_offset(), talk_function::mission_success(), Character::mod_daily_health(), item::mod_damage(), Character::mod_livestyle(), character_modifier::modifier(), Item_modifier::modify(), Character::modify_morale(), Character::modify_stimulation(), Character::most_accurate_aiming_method_limit(), npc::move_away_from(), activity_handlers::move_cost_cart(), activity_handlers::move_cost_inv(), monster::move_effects(), veh_interact::move_overview_line(), npc::move_pause(), MapExtras::mx_helicopter(), neg_INT64_MIN(), neg_INT_MIN(), npc_trading::net_price_adjustment(), new_centered_win(), activity_tracker::new_turn(), nicotine_effect(), vehicle::noise_and_smoke(), normalize_relative_path(), monster::nursebot_operate(), map::obstacle_coverage(), octile_dist(), octile_dist_exact(), Character::on_dodge(), monster::on_load(), npc::on_load(), query_popup_impl::on_resized(), opiate_effect(), item::overheat_symbol(), scrolling_text_view::page_down(), vehicle::part_collision(), npc::patient_assessment(), iexamine::pay_gas(), Character::perform_install(), Character::perform_uninstall(), pick_plant(), iuse::pickaxe(), overmap::place_cities(), overmap::place_forest_trails(), overmapbuffer::place_special(), overmap::place_specials(), monster::plan(), play_videogame(), vehicle::pldrive(), Character::point_shooting_limit(), map::points_in_radius(), map::points_in_rectangle(), climbing_aid::fall_scan::pos_furniture_or_floor(), Character::pour_into(), avatar::power_bionics(), avatar::power_mutations(), vehicle::power_parts(), Character::practice(), vehicle::autodrive_controller::precompute_data(), turret_data::prepare_fire(), map_memory::prepare_region(), vehicle::prepare_tool(), price_adjustment(), string_editor_window::print_editor(), vehicle::print_fuel_indicators(), advanced_inventory::print_header(), vehicle::print_vparts_descs(), item_pocket::process(), Character::process_bionic(), monster::process_effects(), robot_finds_kitten::process_input(), sounds::process_sound_markers(), item::process_temperature_rot(), monster::process_triggers(), Character::process_turn(), map::produce_sap(), anonymous_namespace{animation.cpp}::basic_animation::progress(), projectile_attack(), projectile_attack_roll(), map::propagate_field(), activity_handlers::pulp_do_turn(), item::reload_option::qty(), advanced_inventory::query_charges(), string_input_popup::query_string(), npc::randomize(), spell::range(), Character::reach_attack(), avatar::read(), target_ui::recalc_aim_turning_penalty(), anonymous_namespace{messages.cpp}::messages_impl::recent_messages(), Character::recipe_success_roll_data(), basecamp::recruit_evaluation(), basecamp::recruit_return(), vehicle::refresh(), wish_item_callback::refresh(), item::reload(), reload_furniture(), vehicle::reload_seeds(), item_pocket::remaining_capacity_for_item(), repair_item_actor::repair_chance(), vehicle::restore_folded_parts(), mattack::resurrect(), rng_exponential(), Character::roll_bad_mutation(), roll_butchery_dissect(), roll_melee_damage_internal(), map::route(), SkillLevel::rust(), vehicle::safe_rotor_velocity(), binomial_distribution::sample(), poisson_distribution::sample(), game::save_cyborg(), scale_time(), scatter_chunks(), map::scent_blockers(), scrollable_text(), Character::sees(), Creature::sees(), map::sees_cache_key(), select_crafter_and_crafting_recipe(), Character::select_item_component(), calendar_ui::select_time_point(), Character::set_activity_level(), inventory_multiselector::set_chosen_count(), memorized_tile::set_dec_rotation(), memorized_tile::set_dec_subtile(), field_entry::set_field_intensity(), set_hobbies(), Character::set_hunger(), effect::set_intensity(), set_profession(), set_scenario(), Character::set_sleep_deprivation(), set_stats(), memorized_tile::set_ter_rotation(), memorized_tile::set_ter_subtile(), set_traits(), map::shake_vehicle(), shortcut_text(), item::shots_remaining(), Messages::dialog::show(), robot_finds_kitten::show(), safemode::show(), live_view::show(), color_manager::show_gui(), bodypart::skill_adjusted_limb_value(), spell_effect::slime_split_on_death(), vehicle::smart_controller_handle_turn(), Character::smash_ability(), outfit::sort_armor(), sort_body_parts(), sound_distance(), map::spawn_monsters_submap_group(), mdeath::splatter(), split_span(), sokoban_game::start_game(), string_view_cmp(), dependency_tree::strong_connect(), subindex_around_cursor(), Character::swim_speed(), Character::temp_corrected_by_climate_control(), safemode::test_pattern(), throw_cost(), Character::throw_item(), Character::throwing_dispersion(), throwing_skill_adjusted(), Character::thrown_item_adjusted_damage(), Character::thrown_item_total_damage_raw(), vehicle::thrust(), npc::time_to_read(), Character::time_to_read(), zone_data::toggle_display(), item_contents::total_container_capacity(), Character::try_add(), try_fuel_fire(), try_insert(), activity_tracker::try_reduce_weariness(), Character::try_remove_grab(), vehicle::turrets_aim(), Character::unimpaired_range(), Character::update_body(), Character::update_bodytemp(), player_morale::update_constrained_penalty(), player_morale::update_masochist_bonus(), Character::update_needs(), player_morale::update_squeamish_penalty(), Character::update_stamina(), player_morale::update_stylish_bonus(), place_monster_iuse::use(), firestarter_actor::use(), place_trap_actor::use(), basecamp::use_charges(), monster::use_mech_power(), invlet_wrapper::valid(), Character::valid_aoe_technique(), map::valid_move(), npc::value(), vehicle_bounds(), iexamine::vending(), Character::vitamin_mod(), game::water_affect_items(), Character::weapon_value(), weather_forecast(), item::weight(), pickup_selector::wield(), npc::wont_hit_friend(), mattack::zombie_fuse(), and game::zones_manager().
rand()
double rand (std::vector< double > const & params) inline
Definition at line 56 of file math_parser_func.h.
 {
     return rng( 0, static_cast<int>( std::round( params[0] ) ) );
 }
References rng(), and round().
Referenced by vehicle::init_state(), and vehicle::smash_security_system().
round()
double round (std::vector< double > const & params) inline
Definition at line 110 of file math_parser_func.h.
 {
     return std::round( params[0] );
 }
Referenced by npc::act_on_danger_assessment(), rl_vec2d::as_point(), rl_vec3d::as_point(), Character::attack_speed(), Character::avg_encumb_of_limb_type(), npc::avoid_friendly_fire(), Character::avoid_trap(), npc_attack_spell::base_time_penalty(), mattack::bio_op_disarm(), Character::bionics_pl_skill(), Character::block_hit(), activity_handlers::build_do_turn(), activity_handlers::butcher_finish(), butchery_dissect_skill_level(), butchery_drops_harvest(), vehicle::calc_mass_center(), relic_procgen_data::enchantment_active::calc_power(), relic_procgen_data::enchantment_value_passive< T >::calc_power(), item::calculate_by_enchantment(), Character::calculate_by_enchantment(), monster::calculate_by_enchantment(), item::calculate_by_enchantment_wield(), spell::casting_exp(), spell::casting_time(), outfit::clatter_sound(), vehicle::collision(), Character::complete_disassemble(), Character::compute_calories_per_effective_volume(), corpse_damage_effect(), salvage_actor::cut_up(), damage_targets(), units::default_length_from_volume(), harvest_list::describe(), trap::detect_trap(), avatar::disarm(), target_ui::dist_fn(), disassemble_activity_actor::do_turn(), craft_activity_actor::do_turn(), spell::energy_cost(), npc_attack_melee::evaluate_critter(), npc_attack_spell::evaluate_tripoint(), npc_attack_gun::evaluate_tripoint(), npc_attack_throw::evaluate_tripoint(), trap::examine(), spell::exp_progress(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), farm_action(), spell::field_intensity(), Item_factory::finalize_post_armor(), hotwire_car_activity_actor::finish(), lockpick_activity_actor::finish(), harvest_activity_actor::finish(), forage_activity_actor::finish(), iuse::fish_trap_tick(), Character::footstep_sound(), basecamp::gathering_return(), Character::get_all_skills(), Creature::get_armor_res_bonus(), heal_actor::get_bandaged_level(), talker_character_const::get_bmi_permil(), Character::get_character_parallax(), stomach_contents::get_digest_rates(), heal_actor::get_disinfected_level(), heal_actor::get_heal_value(), Character::get_hostile_creatures(), Character::get_lifestyle(), Character::get_limb_score(), Character::get_max_healthy(), get_moon_phase(), Character::get_mutation_visibility_cap(), get_opt_slider(), Character::get_spell_resist(), Character::get_starvation(), heal_actor::get_stopbleed_level(), json_item_substitution::get_substitution(), Character::get_targetable_creatures(), Character::get_total_melee_stamina_cost(), item::get_warmth(), item::gun_dispersion(), computer_session::hack_attempt(), hack_level(), hackveh(), prying_activity_actor::handle_prying(), iexamine::harvest_plant(), Character::height(), Character::height_string(), Character::item_reload_cost(), Character::kcal_speed_penalty(), iexamine::ledge(), Character::lie_skill(), Item_factory::load_basic_info(), mapgen_forest(), known_magic::max_mana(), spell::min_leveled_accuracy(), spell::min_leveled_aoe(), spell::min_leveled_damage(), spell::min_leveled_dot(), spell::min_leveled_duration(), stomach_contents::mod_nutr(), anonymous_namespace{messages.cpp}::messages_impl::modify_msg_with_exclamations(), npc_trading::net_price_adjustment(), Character::overmap_sight_range(), iuse::pack_cbm(), Character::persuade_skill(), pick_plant(), overmap::place_mongroups(), monster::process_triggers(), rand(), npc::randomize(), Character::randomize_height(), spell::range(), Character::recalc_speed_bonus(), vehicle::refresh_pivot(), roll_butchery_dissect(), round_with_places(), sinkhole_safety_roll(), mdeath::splatter(), display::sundial_text_color(), Character::swim_speed(), Character::throw_item(), Character::throw_range(), Character::thrown_item_projectile(), time_to_attack(), iexamine::tree_hickory(), place_trap_actor::use(), sew_advanced_actor::use(), and npc::value().
sin()
double sin (std::vector< double > const & params) inline
Definition at line 71 of file math_parser_func.h.
 {
     return std::sin( params[0] );
 }
Referenced by calc_ray_end(), weather_generator::get_water_temperature(), mapgen_forest(), offset_to_sun_altitude(), vehicle::part_vpower_w(), projectile_attack(), rl_vec2d::rotated(), rl_vec3d::rotated(), units::sin(), sun_azimuth_altitude(), sun_irradiance(), sun_ra_declination(), sunlight_angle(), and teleport::teleport().
sqrt()
double sqrt (std::vector< double > const & params) inline
Definition at line 61 of file math_parser_func.h.
 {
     return std::sqrt( params[0] );
 }
Referenced by vehicle::act_on_map(), player_morale::morale_point::add(), explosion_handler::ballistic_damage(), bionic_manip_cos(), Character::bionics_install_failure(), Character::bionics_uninstall_failure(), npc_trading::cash_to_favor(), Character::compute_effective_food_volume_ratio(), point::distance(), map::drop_items(), book_proficiency_bonuses::fail_factor(), activity_handlers::generic_game_turn_handler(), player_morale::get_level(), player_morale::get_total_negative_value(), player_morale::get_total_positive_value(), weakpoint::hit_chance(), mattack::kamikaze(), rl_vec2d::magnitude(), rl_vec3d::magnitude(), mapgen_forest(), vehicle::max_rotor_velocity(), Character::melee_value(), Character::mend(), map::move_vehicle(), normal_roll_chance(), FastDistanceApproximation::operator int(), vehicle::part_collision(), projectile_attack(), activity_handlers::pulp_do_turn(), raw_noise_2d(), raw_noise_4d(), Character::recipe_success_roll_data(), mattack::resurrect(), SkillLevel::rust(), vehicle::safe_rotor_velocity(), satiety_bar(), game::save_cyborg(), Creature::select_body_part_projectile_attack(), map::shake_vehicle(), simple_cubic_solution(), Character::throw_item(), book_proficiency_bonuses::time_factor(), trig_dist(), Character::update_bodytemp(), avatar::update_cardio_acc(), game::update_overmap_seen(), firestarter_actor::use(), and npc::vehicle_danger().
tan()
double tan (std::vector< double > const & params) inline
Definition at line 81 of file math_parser_func.h.
 {
     return std::tan( params[0] );
 }
Referenced by map::apply_light_arc(), calc_ray_end(), units::cot(), iso_tangent(), and units::tan().
test_()
constexpr double test_ (std::vector< double > const &) constexpr
Definition at line 115 of file math_parser_func.h.
 {
     return 42;
 }
tokenize()
std::vector<std::string_view> tokenize (std::string_view str, std::string_view separators, bool include_seps = true)
Definition at line 7 of file math_parser_func.cpp.
 {
     std::vector<std::string_view> ret;
     std::string_view::size_type start = 0;
     std::string_view::size_type pos = 0;
     std::string_view last;
     while( pos != std::string_view::npos ) {
         pos = str.find_first_of( separators, start );
         if( pos != start ) {
             std::string_view const ts = str.substr( start, pos - start );
             if( std::string_view::size_type const unpad = ts.find_first_not_of( ' ' );
                 unpad != std::string_view::npos ) {
                 std::string_view::size_type const unpad_e = ts.find_last_not_of( ' ' );
                 ret.emplace_back(
                     ts.substr( unpad, unpad_e - unpad + 1 ) );
             }
         }
         if( pos != std::string_view::npos && include_seps ) {
             if( str[pos] == '=' && start > 0 &&
                 ( last == "=" || last == ">" || last == "<" || last == "!" ) ) {
                 ret.pop_back();
                 ret.emplace_back( str.substr( pos - 1, 2 ) );
             } else {
                 ret.emplace_back( &str[pos], 1 );
             }
         }
         if( !ret.empty() ) {
             last = ret.back();
         }
         start = pos + 1;
     }
     return ret;
 }
References last, math_opers::pos(), and cata::hash64_detail::ret.
Referenced by math_exp::math_exp_impl::_parse().
trunc()
double trunc (std::vector< double > const & params) inline
Definition at line 105 of file math_parser_func.h.
 {
     return std::trunc( params[0] );
 }
Referenced by get_speedlist_entries(), basecamp::om_upgrade_description(), and trunc_ellipse().
Variable Documentation
constants
constexpr std::array<math_const, 5> constants constexpr
Initial value:
{
    math_const{ "", math_constants::pi_v },
    math_const{ "pi", math_constants::pi_v },
    math_const{ "e", math_constants::e_v },
    math_const{ "true", 1 },
    math_const{ "false", 0 },
}
Definition at line 174 of file math_parser_func.h.
Referenced by anonymous_namespace{math_parser.cpp}::get_constant().
functions
constexpr std::array<math_func, 20> functions constexpr
Initial value:
{
    math_func{ "abs", 1, abs },
    math_func{ "max", -1, max },
    math_func{ "min", -1, min },
    math_func{ "clamp", 3, clamp },
    math_func{ "floor", 1, floor },
    math_func{ "trunc", 1, trunc },
    math_func{ "ceil", 1, ceil },
    math_func{ "round", 1, round },
    math_func{ "rng", 2, math_rng },
    math_func{ "rand", 1, rand },
    math_func{ "sqrt", 1, sqrt },
    math_func{ "log", 1, log },
    math_func{ "sin", 1, sin },
    math_func{ "cos", 1, cos },
    math_func{ "tan", 1, tan },
    math_func{ "_test_", 0, test_ },
    math_func{ "celsius", 1, celsius_from_kelvin },
    math_func{ "fahrenheit", 1, fahrenheit_from_kelvin },
    math_func{ "from_celsius", 1, celsius_to_kelvin },
    math_func{ "from_fahrenheit", 1, fahrenheit_to_kelvin },
}
Definition at line 140 of file math_parser_func.h.
Referenced by filter_from_string(), and anonymous_namespace{math_parser.cpp}::get_function().