Cataclysm DDA: src/medical_ui.cpp File Reference
medical_ui.cpp File Reference
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <string>
#include <utility>
#include "addiction.h"
#include "avatar_action.h"
#include "creature.h"
#include "character.h"
#include "character_modifier.h"
#include "display.h"
#include "effect.h"
#include "flag.h"
#include "game.h"
#include "input_context.h"
#include "output.h"
#include "ui_manager.h"
#include "weather.h"
Classes
class selection_line
class medical_column
Enumerations
enum class medical_tab_mode { TAB_SUMMARY }
Functions
static std::string coloured_stat_display (int statCur, int statMax)
static void draw_medical_titlebar (const catacurses::window &window, avatar *player, const int WIDTH)
static medical_column draw_health_summary (const int column_count, avatar *player, const point &COLUMN_START, const std::pair< int, int > &COLUMN_BOUNDS)
static medical_column draw_effects_summary (const int column_count, avatar *player, const point &COLUMN_START, const std::pair< int, int > &COLUMN_BOUNDS)
static medical_column draw_stats_summary (const int column_count, avatar *player, const point &COLUMN_START, const std::pair< int, int > &COLUMN_BOUNDS)
Variables
static const efftype_id effect_bite ("bite")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_infected ("infected")
static const efftype_id effect_mending ("mending")
static const json_character_flag json_flag_PAIN_IMMUNE ("PAIN_IMMUNE")
static const trait_id trait_SUNLIGHT_DEPENDENT ("SUNLIGHT_DEPENDENT")
static const trait_id trait_TROGLO ("TROGLO")
static const trait_id trait_TROGLO2 ("TROGLO2")
static const trait_id trait_TROGLO3 ("TROGLO3")
Enumeration Type Documentation
medical_tab_mode
enum medical_tab_mode strong
Enumerator
TAB_SUMMARY
Definition at line 33 of file medical_ui.cpp.
{
     TAB_SUMMARY
 };
Function Documentation
coloured_stat_display()
static std::string coloured_stat_display (int statCur, int statMax) static
Definition at line 195 of file medical_ui.cpp.
 {
     nc_color cstatus;
     if( statCur <= 0 ) {
         cstatus = c_dark_gray;
     } else if( statCur < statMax / 2 ) {
         cstatus = c_red;
     } else if( statCur < statMax ) {
         cstatus = c_light_red;
     } else if( statCur == statMax ) {
         cstatus = c_white;
     } else if( statCur < statMax * 1.5 ) {
         cstatus = c_light_green;
     } else {
         cstatus = c_green;
     }
     std::string cur = colorize( string_format( _( "%2d" ), statCur ), cstatus );
     return string_format( _( "%s (%s)" ), cur, statMax );
 }
References _, c_dark_gray, c_green, c_light_green, c_light_red, c_red, c_white, colorize(), and string_format().
Referenced by draw_stats_summary().
draw_effects_summary()
static medical_column draw_effects_summary (const int column_count, avatar * player, const point & COLUMN_START, const std::pair< int, int > & COLUMN_BOUNDS) static
Definition at line 499 of file medical_ui.cpp.
 {
     medical_column effects_column = medical_column( column_count, COLUMN_START, COLUMN_BOUNDS );
     const int max_width = effects_column.max_width();
     for( const effect &eff : player->get_effects() ) {
         const std::string name = eff.disp_name();
         if( name.empty() ) {
             continue;
         }
         effects_column.add_column_line( selection_line( name, eff.disp_desc(), max_width ) );
     }
     const float bmi = player->get_bmi_fat();
     if( bmi < character_weight_category::underweight ) {
         std::string starvation_name;
         std::string starvation_text;
         if( bmi < character_weight_category::emaciated ) {
             starvation_name = _( "Severely Malnourished" );
             starvation_text =
                 _( "Your body is severely weakened by starvation.  You might die if you don't start eating regular meals!\n\n" );
         } else {
             starvation_name = _( "Malnourished" );
             starvation_text =
                 _( "Your body is weakened by starvation.  Only time and regular meals will help you recover.\n\n" );
         }
         if( bmi < character_weight_category::underweight ) {
             const float str_penalty = 1.0f - ( ( bmi - 13.0f ) / 3.0f );
             starvation_text += std::string( _( "Strength" ) ) + " -" + string_format( "%2.0f%%\n",
                                str_penalty * 100.0f );
             starvation_text += std::string( _( "Dexterity" ) ) + " -" + string_format( "%2.0f%%\n",
                                str_penalty * 50.0f );
             starvation_text += std::string( _( "Intelligence" ) ) + " -" + string_format( "%2.0f%%",
                                str_penalty * 50.0f );
         }
         effects_column.add_column_line( selection_line( starvation_name, starvation_text, max_width ) );
     }
     if( player->has_trait( trait_TROGLO3 ) && g->is_in_sunlight( player->pos() ) ) {
         effects_column.add_column_line( selection_line( "In Sunlight",
                                         "The sunlight irritates you terribly.\n", max_width ) );
     } else if( player->has_trait( trait_TROGLO2 ) && g->is_in_sunlight( player->pos() ) &&
                incident_sun_irradiance( get_weather().weather_id, calendar::turn ) > irradiance::low ) {
         effects_column.add_column_line( selection_line( "In Sunlight",
                                         "The sunlight irritates you badly.\n", max_width ) );
     } else if( ( player->has_trait( trait_TROGLO ) || player->has_trait( trait_TROGLO2 ) ) &&
                g->is_in_sunlight( player->pos() ) &&
                incident_sun_irradiance( get_weather().weather_id, calendar::turn ) > irradiance::moderate ) {
         effects_column.add_column_line( selection_line( "In Sunlight", "The sunlight irritates you.\n",
                                         max_width ) );
     }
     for( addiction &elem : player->addictions ) {
         if( elem.sated < 0_turns && elem.intensity >= MIN_ADDICTION_LEVEL ) {
             effects_column.add_column_line( selection_line( elem.type->get_name().translated(),
                                             elem.type->get_description().translated(), max_width ) );
         }
     }
     if( effects_column.empty() ) {
         effects_column.add_column_line( selection_line( colorize( "None", c_dark_gray ), "", max_width ) );
     }
     return effects_column;
 }
References _, medical_column::add_column_line(), c_dark_gray, colorize(), character_weight_category::emaciated, medical_column::empty(), g, add_type::get_description(), add_type::get_name(), get_weather(), incident_sun_irradiance(), addiction::intensity, irradiance::low, medical_column::max_width(), MIN_ADDICTION_LEVEL, irradiance::moderate, om_direction::name(), player, addiction::sated, string_format(), trait_TROGLO, trait_TROGLO2, trait_TROGLO3, translation::translated(), calendar::turn, addiction::type, and character_weight_category::underweight.
Referenced by avatar::disp_medical().
draw_health_summary()
static medical_column draw_health_summary (const int column_count, avatar * player, const point & COLUMN_START, const std::pair< int, int > & COLUMN_BOUNDS) static
Definition at line 335 of file medical_ui.cpp.
 {
     medical_column health_column = medical_column( column_count, COLUMN_START, COLUMN_BOUNDS );
     const int max_width = health_column.max_width();
     for( const bodypart_id &part : player->get_all_body_parts( get_body_part_flags::sorted ) ) {
         std::string header; // Bodypart Title
         std::string hp_str; // Bodypart HP
         std::string detail;
         std::string description;
         const int bleed_intensity = player->get_effect_int( effect_bleed, part );
         const bool bleeding = bleed_intensity > 0;
         const bool bitten = player->has_effect( effect_bite, part.id() );
         const bool infected = player->has_effect( effect_infected, part.id() );
         const bool no_feeling = player->has_flag( json_flag_PAIN_IMMUNE );
         const int maximal_hp = player->get_part_hp_max( part );
         const int current_hp = player->get_part_hp_cur( part );
         const bool limb_is_broken = player->is_limb_broken( part );
         const bool limb_is_mending = player->worn_with_flag( flag_SPLINT, part );
         if( limb_is_mending ) {
             detail += string_format( _( "[ %s ]" ), colorize( _( "SPLINTED" ), c_yellow ) );
             if( no_feeling ) {
                 hp_str = colorize( "==%==", c_blue );
             } else {
                 const effect &eff = player->get_effect( effect_mending, part );
                 const int mend_perc = eff.is_null() ? 0.0 : 100 * eff.get_duration() / eff.get_max_duration();
                 const int num = mend_perc / 20;
                 hp_str = colorize( std::string( num, '#' ) + std::string( 5 - num, '=' ), c_blue );
             }
         } else if( limb_is_broken ) {
             detail += string_format( _( "[ %s ]" ), colorize( _( "BROKEN" ), c_red ) );
             hp_str = "==%==";
         } else if( no_feeling ) {
             const float cur_hp_pcnt = current_hp / static_cast<float>( maximal_hp );
             if( cur_hp_pcnt < 0.125f ) {
                 hp_str = colorize( _( "Very Bad" ), c_red );
             } else if( cur_hp_pcnt < 0.375f ) {
                 hp_str = colorize( _( "Bad" ), c_light_red );
             } else if( cur_hp_pcnt < 0.625f ) {
                 hp_str = colorize( _( "So-so" ), c_yellow );
             } else if( cur_hp_pcnt < 0.875f ) {
                 hp_str = colorize( _( "Okay" ), c_light_green );
             } else {
                 hp_str = colorize( _( "Good" ), c_green );
             }
         } else {
             std::pair<std::string, nc_color> h_bar = get_hp_bar( current_hp, maximal_hp, false );
             hp_str = colorize( h_bar.first, h_bar.second ) +
                      colorize( std::string( 5 - utf8_width( h_bar.first ), '.' ), c_white );
         }
         const std::string bp_name = uppercase_first_letter( body_part_name( part, 1 ) );
         header += colorize( bp_name,
                             display::limb_color( *player,
                                     part, true, true, true ) ) + " " + hp_str;
         // BLEEDING block
         if( bleeding ) {
             const effect bleed_effect = player->get_effect( effect_bleed, part );
             const nc_color bleeding_color = colorize_bleeding_intensity( bleed_intensity );
             detail += string_format( _( "[ %s ]" ), colorize( _( "BLEEDING" ), bleeding_color ) );
             description += string_format( "[ %s ] - %s\n",
                                           colorize( bleed_effect.get_speed_name(),  bleeding_color ),
                                           bleed_effect.disp_short_desc() );
         }
         // BITTEN block
         if( bitten ) {
             const effect bite_effect = player->get_effect( effect_bite, part );
             detail += string_format( _( "[ %s ]" ), colorize( _( "BITTEN" ), c_yellow ) );
             description += string_format( "[ %s ] - %s\n",
                                           colorize( bite_effect.get_speed_name(), c_yellow ),
                                           bite_effect.disp_short_desc() );
         }
         // INFECTED block
         if( infected ) {
             const effect infected_effect = player->get_effect( effect_infected, part );
             detail += string_format( _( "[ %s ]" ), colorize( _( "INFECTED" ), c_pink ) );
             description += string_format( "[ %s ] - %s\n",
                                           colorize( infected_effect.get_speed_name(), c_pink ),
                                           infected_effect.disp_short_desc() );
         }
         selection_line line;
         if( !detail.empty() ) {
             line = selection_line( string_format( "[%s] - %s", header, detail ), description, max_width );
         } else {
             line = selection_line( string_format( "[%s]", header ), description, max_width );
         }
         const bodypart *bp = player->get_part( part );
         std::string detail_str;
         for( const limb_score &sc : limb_score::get_all() ) {
             if( !part->has_limb_score( sc.getId() ) ) {
                 continue;
             }
             float injury_score = bp->get_limb_score( sc.getId(), 0, 0, 1 );
             float max_score = part->get_limb_score( sc.getId() );
             if( injury_score < max_score ) {
                 const float injury_modifier = 100 * ( max_score - injury_score ) / max_score;
                 std::pair<std::string, nc_color> score_c;
                 if( injury_score < max_score * 0.4f ) {
                     score_c.first = string_format( _( "Crippled (-%.f%%)" ), injury_modifier );
                     score_c.second = c_red;
                 } else if( injury_score < max_score * 0.6f ) {
                     score_c.first = string_format( _( "Impaired (-%.f%%)" ), injury_modifier );
                     score_c.second = c_light_red;
                 } else if( injury_score < max_score * 0.75f ) {
                     score_c.first = string_format( _( "Weakened (-%.f%%)" ), injury_modifier );
                     score_c.second = c_yellow;
                 } else if( injury_score < max_score * 0.9f ) {
                     score_c.first = string_format( _( "Weakened (-%.f%%)" ), injury_modifier );
                     score_c.second = c_dark_gray;
                 } else {
                     score_c.first = string_format( _( "OK (-%.f%%)" ), injury_modifier );
                     score_c.second = c_dark_gray;
                 }
                 detail_str += string_format( _( "%s: %s\n" ), sc.name().translated(), colorize( score_c.first,
                                              score_c.second ) );
             } else {
                 detail_str += string_format( _( "%s: %s\n" ), sc.name().translated(), colorize( "OK", c_green ) );
             }
         }
         for( const character_modifier &mod : character_modifier::get_all() ) {
             for( const auto &sc : mod.use_limb_scores() ) {
                 if( sc.first.is_null() || !part->has_limb_score( sc.first ) ) {
                     continue;
                 }
                 std::string desc = mod.description().translated();
                 float injury_score = bp->get_limb_score( sc.first, 0, 0, 1 );
                 float max_score = part->get_limb_score( sc.first );
                 nc_color score_c;
                 if( injury_score < max_score * 0.4f ) {
                     score_c = c_red;
                 } else if( injury_score < max_score * 0.6f ) {
                     score_c = c_light_red;
                 } else if( injury_score < max_score * 0.75f ) {
                     score_c = c_yellow;
                 } else {
                     score_c = c_white;
                 }
                 std::string valstr = colorize( string_format( "%.2f", mod.modifier( *player->as_character() ) ),
                                                score_c );
                 detail_str += string_format( "%s: %s%s\n", desc, mod.mod_type_str(), valstr );
             }
         }
         line.set_detail( string_format( _( "%s STATS" ), to_upper_case( bp_name ) ), detail_str );
         health_column.add_column_line( line );
     }
     return health_column;
 }
References _, medical_column::add_column_line(), body_part_name(), bp, c_blue, c_dark_gray, c_green, c_light_green, c_light_red, c_pink, c_red, c_white, c_yellow, colorize(), colorize_bleeding_intensity(), effect::disp_short_desc(), effect_bite, effect_bleed, effect_infected, effect_mending, flag_SPLINT, limb_score::get_all(), character_modifier::get_all(), effect::get_duration(), get_hp_bar(), body_part_type::get_limb_score(), effect::get_max_duration(), effect::get_speed_name(), string_id< T >::id(), effect::is_null(), json_flag_PAIN_IMMUNE, display::limb_color(), line(), medical_column::max_width(), player, sorted, string_format(), to_upper_case(), uppercase_first_letter(), and utf8_width().
Referenced by avatar::disp_medical().
draw_medical_titlebar()
static void draw_medical_titlebar (const catacurses::window & window, avatar * player, const int WIDTH) static
Definition at line 215 of file medical_ui.cpp.
 {
     input_context ctxt( "MEDICAL", keyboard_mode::keychar );
     const Character &you = *player->as_character();
     werase( window );
     draw_border( window, BORDER_COLOR, _( " MEDICAL " ) );
     // Tabs
     const std::vector<std::pair<medical_tab_mode, std::string>> tabs = {
         { medical_tab_mode::TAB_SUMMARY, string_format( _( "SUMMARY" ) ) }
     };
     draw_tabs( window, tabs, medical_tab_mode::TAB_SUMMARY );
     const int TAB_WIDTH = 12;
     // Draw symbols to connect additional lines to border
     int width = getmaxx( window );
     int height = getmaxy( window );
     for( int i = 1; i < height - 1; ++i ) {
         // |
         mvwputch( window, point( 0, i ), BORDER_COLOR, LINE_XOXO );
         // |
         mvwputch( window, point( width - 1, i ), BORDER_COLOR, LINE_XOXO );
     }
     // |-
     mvwputch( window, point( 0, height - 1 ), BORDER_COLOR, LINE_XXXO );
     // -|
     mvwputch( window, point( width - 1, height - 1 ), BORDER_COLOR, LINE_XOXX );
     int right_indent = 2;
     int cur_str_pos = 0;
     // Pain Indicator
     auto pain_descriptor = display::pain_text_color( *player );
     if( !pain_descriptor.first.empty() ) {
         const std::string pain_str = string_format( _( "In %s" ), pain_descriptor.first );
         cur_str_pos = right_print( window, 1, right_indent, pain_descriptor.second, pain_str );
         // Borders
         for( int i = 1; i < getmaxy( window ) - 1; i++ ) {
             mvwputch( window, point( cur_str_pos - 2, i ), BORDER_COLOR, LINE_XOXO ); // |
         }
         mvwputch( window, point( cur_str_pos - 2, 0 ), BORDER_COLOR, LINE_OXXX ); // ^|^
         mvwputch( window, point( cur_str_pos - 2, 2 ), BORDER_COLOR, LINE_XXOX ); // _|_
         right_indent += utf8_width( remove_color_tags( pain_str ) ) + 3;
     }
     const std::pair<std::string, nc_color> hunger_pair = display::hunger_text_color( you );
     const std::pair<std::string, nc_color> thirst_pair = display::thirst_text_color( you );
     const std::pair<std::string, nc_color> sleepiness_pair = display::sleepiness_text_color( you );
     // Hunger
     if( !hunger_pair.first.empty() ) {
         cur_str_pos = right_print( window, 1, right_indent, hunger_pair.second, hunger_pair.first );
         // Borders
         for( int i = 1; i < getmaxy( window ) - 1; i++ ) {
             mvwputch( window, point( cur_str_pos - 2, i ), BORDER_COLOR, LINE_XOXO ); // |
         }
         mvwputch( window, point( cur_str_pos - 2, 0 ), BORDER_COLOR, LINE_OXXX ); // ^|^
         mvwputch( window, point( cur_str_pos - 2, 2 ), BORDER_COLOR, LINE_XXOX ); // _|_
         right_indent += utf8_width( hunger_pair.first ) + 3;
     }
     // Thirst
     if( !thirst_pair.first.empty() ) {
         cur_str_pos = right_print( window, 1, right_indent, thirst_pair.second, thirst_pair.first );
         // Borders
         for( int i = 1; i < getmaxy( window ) - 1; i++ ) {
             mvwputch( window, point( cur_str_pos - 2, i ), BORDER_COLOR, LINE_XOXO ); // |
         }
         mvwputch( window, point( cur_str_pos - 2, 0 ), BORDER_COLOR, LINE_OXXX ); // ^|^
         mvwputch( window, point( cur_str_pos - 2, 2 ), BORDER_COLOR, LINE_XXOX ); // _|_
         right_indent += utf8_width( thirst_pair.first ) + 3;
     }
     // Sleepiness
     if( !sleepiness_pair.first.empty() ) {
         cur_str_pos = right_print( window, 1, right_indent, sleepiness_pair.second, sleepiness_pair.first );
         // Borders
         for( int i = 1; i < getmaxy( window ) - 1; i++ ) {
             mvwputch( window, point( cur_str_pos - 2, i ), BORDER_COLOR, LINE_XOXO ); // |
         }
         mvwputch( window, point( cur_str_pos - 2, 0 ), BORDER_COLOR, LINE_OXXX ); // ^|^
         mvwputch( window, point( cur_str_pos - 2, 2 ), BORDER_COLOR, LINE_XXOX ); // _|_
         right_indent += utf8_width( sleepiness_pair.first ) + 3;
     }
     // Hotkey Helper
     std::string desc;
     desc = string_format( _(
                               "[<color_yellow>%s/%s</color>] Scroll info [<color_yellow>%s</color>] Use item [<color_yellow>%s</color>] Keybindings" ),
                           ctxt.get_desc( "SCROLL_INFOBOX_UP" ), ctxt.get_desc( "SCROLL_INFOBOX_DOWN" ),
                           ctxt.get_desc( "APPLY" ), ctxt.get_desc( "HELP_KEYBINDINGS" ) );
     const int details_width = utf8_width( remove_color_tags( desc ) ) + 3;
     const int max_width = right_indent + TAB_WIDTH;
     if( WIDTH - max_width > details_width ) {
         // If the window runs out of room, we won't print keybindings.
         right_print( window, 1, right_indent, c_white, desc );
     }
     const std::string TITLE_STR = "Medical";
     // Window Title
     if( WIDTH - details_width - utf8_width( TITLE_STR ) > WIDTH / 2 ) {
         center_print( window, 0, c_blue, _( TITLE_STR ) );
     }
 }
References _, BORDER_COLOR, c_blue, c_white, center_print(), draw_border(), draw_tabs(), input_context::get_desc(), catacurses::getmaxx(), catacurses::getmaxy(), display::hunger_text_color(), keychar, LINE_OXXX, LINE_XOXO, LINE_XOXX, LINE_XXOX, LINE_XXXO, mvwputch(), display::pain_text_color(), player, remove_color_tags(), right_print(), display::sleepiness_text_color(), string_format(), TAB_SUMMARY, display::thirst_text_color(), utf8_width(), and catacurses::werase().
Referenced by avatar::disp_medical().
draw_stats_summary()
static medical_column draw_stats_summary (const int column_count, avatar * player, const point & COLUMN_START, const std::pair< int, int > & COLUMN_BOUNDS) static
Definition at line 572 of file medical_ui.cpp.
 {
     medical_column stats_column = medical_column( column_count, COLUMN_START, COLUMN_BOUNDS );
     const int max_width = stats_column.max_width();
     std::string speed_detail_str;
     int runcost = player->run_cost( 100 );
     int newmoves = player->get_speed();
     std::string coloured_str = colorize( string_format( _( "%d" ), runcost ),
                                          ( runcost <= 100 ? c_green : c_red ) );
     selection_line runcost_line = selection_line( string_format( _( "Base Move Cost: %s" ),
                                   coloured_str ),
                                   colorize( _( "Base move cost is the final modified movement cost taken to traverse flat ground." ),
                                             c_light_blue ),
                                   max_width );
     coloured_str = colorize( string_format( _( "%d" ), newmoves ),
                              ( newmoves >= 100 ? c_green : c_red ) );
     selection_line movecost_line = selection_line( string_format( _( "Current Speed: %s" ),
                                    coloured_str ),
                                    colorize( _( "Speed determines the amount of actions or movement points you can perform in a turn." ),
                                            c_light_blue ),
                                    max_width );
     const int speed_modifier = player->get_enchantment_speed_bonus();
     std::string pge_str;
     if( speed_modifier != 0 ) {
         pge_str = pgettext( "speed bonus", "Bio/Mut/Effects " );
         speed_detail_str += colorize( string_format( _( "%s    -%2d%%\n" ), pge_str, speed_modifier ),
                                       c_green );
     }
     int pen = 0;
     if( player->weight_carried() > player->weight_capacity() ) {
         pen = 25 * ( player->weight_carried() - player->weight_capacity() ) / player->weight_capacity();
         pge_str = pgettext( "speed penalty", "Overburdened " );
         speed_detail_str += colorize( string_format( _( "%s    -%2d%%\n" ), pge_str, pen ), c_red );
     }
     pen = player->get_pain_penalty().speed;
     if( pen >= 1 ) {
         pge_str = pgettext( "speed penalty", "Pain " );
         speed_detail_str += colorize( string_format( _( "%s    -%2d%%\n" ), pge_str, pen ), c_red );
     }
     if( player->get_thirst() > 40 ) {
         pen = std::abs( Character::thirst_speed_penalty( player->get_thirst() ) );
         pge_str = pgettext( "speed penalty", "Thirst " );
         speed_detail_str += colorize( string_format( _( "%s    -%2d%%\n" ), pge_str, pen ), c_red );
     }
     if( player->kcal_speed_penalty() < 0 ) {
         pen = std::abs( player->kcal_speed_penalty() );
         pge_str = pgettext( "speed penalty", player->get_bmi() < character_weight_category::underweight ?
                             "Starving" : "Underfed" );
         speed_detail_str += colorize( string_format( _( "%s    -%2d%%\n" ), pge_str, pen ), c_red );
     }
     if( player->has_trait( trait_SUNLIGHT_DEPENDENT ) && !g->is_in_sunlight( player->pos() ) ) {
         pen = ( g->light_level( player->posz() ) >= 12 ? 5 : 10 );
         pge_str = pgettext( "speed penalty", "Out of Sunlight " );
         speed_detail_str += colorize( string_format( _( "%s     -%2d%%\n" ), pge_str, pen ), c_red );
     }
     std::map<std::string, int> speed_effects;
     for( const effect &elem : player->get_effects() ) {
         bool reduced = player->resists_effect( elem );
         int move_adjust = elem.get_mod( "SPEED", reduced );
         if( move_adjust != 0 ) {
             const std::string dis_text = elem.get_speed_name();
             speed_effects[dis_text] += move_adjust;
         }
     }
     for( const std::pair<const std::string, int> &speed_effect : speed_effects ) {
         nc_color col = speed_effect.second > 0 ? c_green : c_red;
         speed_detail_str += colorize( string_format( _( "%s    %s%d%%\n" ), speed_effect.first,
                                       ( speed_effect.second > 0 ? "+" : "-" ),
                                       std::abs( speed_effect.second ) ), col );
     }
     runcost_line.set_detail( _( "SPEED" ), speed_detail_str );
     movecost_line.set_detail( _( "SPEED" ), speed_detail_str );
     stats_column.add_column_line( runcost_line );
     stats_column.add_column_line( movecost_line );
     std::string strength_str = coloured_stat_display( player->get_str(), player->get_str_base() );
     stats_column.add_column_line(
         selection_line( string_format( _( "Strength: %s" ), strength_str ),
                         _( "Strength affects your melee damage, the amount of weight you can carry, your total HP, "
                            "your resistance to many diseases, and the effectiveness of actions which require brute force." ),
                         max_width ) );
     std::string dexterity_str = coloured_stat_display( player->get_dex(), player->get_dex_base() );
     stats_column.add_column_line(
         selection_line( string_format( _( "Dexterity: %s" ), dexterity_str ),
                         _( "Dexterity affects your chance to hit in melee combat, helps you steady your "
                            "gun for ranged combat, and enhances many actions that require finesse." ),
                         max_width ) );
     std::string intelligence_str = coloured_stat_display( player->get_int(), player->get_int_base() );
     stats_column.add_column_line(
         selection_line( string_format( _( "Intelligence: %s" ), intelligence_str ),
                         _( "Intelligence is less important in most situations, but it is vital for more complex tasks like "
                            "electronics crafting.  It also affects how much skill you can pick up from reading a book." ),
                         max_width ) );
     std::string perception_str = coloured_stat_display( player->get_per(), player->get_per_base() );
     stats_column.add_column_line(
         selection_line( string_format( _( "Perception: %s" ), perception_str ),
                         _( "Perception is the most important stat for ranged combat.  It's also used for "
                            "detecting traps and other things of interest." ),
                         max_width ) );
     return stats_column;
 }
References _, abs(), medical_column::add_column_line(), c_green, c_light_blue, c_red, colorize(), coloured_stat_display(), g, medical_column::max_width(), pgettext, player, selection_line::set_detail(), string_format(), Character::thirst_speed_penalty(), trait_SUNLIGHT_DEPENDENT, and character_weight_category::underweight.
Referenced by avatar::disp_medical().
Variable Documentation
effect_bite
const efftype_id effect_bite("bite") ("bite") static
Referenced by draw_health_summary().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by draw_health_summary().
effect_infected
const efftype_id effect_infected("infected") ("infected") static
Referenced by draw_health_summary().
effect_mending
const efftype_id effect_mending("mending") ("mending") static
Referenced by draw_health_summary().
json_flag_PAIN_IMMUNE
const json_character_flag json_flag_PAIN_IMMUNE("PAIN_IMMUNE") ("PAIN_IMMUNE") static
Referenced by draw_health_summary().
trait_SUNLIGHT_DEPENDENT
const trait_id trait_SUNLIGHT_DEPENDENT("SUNLIGHT_DEPENDENT") ("SUNLIGHT_DEPENDENT") static
Referenced by draw_stats_summary().
trait_TROGLO
const trait_id trait_TROGLO("TROGLO") ("TROGLO") static
Referenced by draw_effects_summary().
trait_TROGLO2
const trait_id trait_TROGLO2("TROGLO2") ("TROGLO2") static
Referenced by draw_effects_summary().
trait_TROGLO3
const trait_id trait_TROGLO3("TROGLO3") ("TROGLO3") static
Referenced by draw_effects_summary().