Cataclysm DDA: src/melee.cpp File Reference
melee.cpp File Reference
#include "melee.h"
#include <algorithm>
#include <array>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <iosfwd>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "avatar.h"
#include "anatomy.h"
#include "bodypart.h"
#include "bionics.h"
#include "cached_options.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "character_martial_arts.h"
#include "creature.h"
#include "creature_tracker.h"
#include "damage.h"
#include "debug.h"
#include "effect_on_condition.h"
#include "enum_bitset.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "flag.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "item.h"
#include "item_location.h"
#include "itype.h"
#include "line.h"
#include "magic_enchantment.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "martialarts.h"
#include "memory_fast.h"
#include "messages.h"
#include "monattack.h"
#include "monster.h"
#include "mtype.h"
#include "mutation.h"
#include "npc.h"
#include "output.h"
#include "pimpl.h"
#include "point.h"
#include "popup.h"
#include "projectile.h"
#include "rng.h"
#include "sounds.h"
#include "string_formatter.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "weakpoint.h"
#include "weighted_list.h"
Namespaces
melee
Functions
static void player_hit_message (Character *attacker, const std::string &message, Creature &t, int dam, bool crit=false, bool technique=false, const std::string &wp_hit={})
static int stumble (Character &u, const item_location &weap)
static std::string melee_message (const ma_technique &tec, Character &p, const dealt_damage_instance &ddi)
static void melee_train (Character &you, int lo, int hi, const item &weap, const std::string &attack_vector)
static const std::set< weapon_category_id > & wielded_weapon_categories (const Character &c)
static double limit_probability (double unbounded_probability)
Limits a probability to be between 0.0 and 1.0.
static void roll_melee_damage_internal (const Character &u, const damage_type_id &dt, bool crit, damage_instance &di, bool average, const item &weap, const std::string &attack_vector, float crit_mod)
static damage_unit & get_damage_unit (std::vector< damage_unit > &di, const damage_type_id &dt)
static void print_damage_info (const damage_instance &di)
static damage_instance hardcoded_mutation_attack (const Character &u, const trait_id &id)
Variables
static const anatomy_id anatomy_human_anatomy ("human_anatomy")
static const bionic_id bio_cqb ("bio_cqb")
static const bionic_id bio_heat_absorb ("bio_heat_absorb")
static const bionic_id bio_razors ("bio_razors")
static const bionic_id bio_shock ("bio_shock")
static const character_modifier_id character_modifier_limb_dodge_mod ("limb_dodge_mod")
static const character_modifier_id character_modifier_melee_attack_roll_mod ("melee_attack_roll_mod")
static const character_modifier_id character_modifier_melee_thrown_move_balance_mod ("melee_thrown_move_balance_mod")
static const character_modifier_id character_modifier_melee_thrown_move_lift_mod ("melee_thrown_move_lift_mod")
static const damage_type_id damage_bash ("bash")
static const damage_type_id damage_cut ("cut")
static const damage_type_id damage_stab ("stab")
static const efftype_id effect_amigara ("amigara")
static const efftype_id effect_beartrap ("beartrap")
static const efftype_id effect_contacts ("contacts")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_fearparalyze ("fearparalyze")
static const efftype_id effect_heavysnare ("heavysnare")
static const efftype_id effect_hit_by_player ("hit_by_player")
static const efftype_id effect_incorporeal ("incorporeal")
static const efftype_id effect_lightsnare ("lightsnare")
static const efftype_id effect_narcosis ("narcosis")
static const efftype_id effect_natural_stance ("natural_stance")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_stunned ("stunned")
static const efftype_id effect_transition_contacts ("transition_contacts")
static const efftype_id effect_venom_dmg ("venom_dmg")
static const efftype_id effect_venom_player1 ("venom_player1")
static const efftype_id effect_venom_player2 ("venom_player2")
static const efftype_id effect_venom_weaken ("venom_weaken")
static const efftype_id effect_winded ("winded")
static const itype_id itype_fur ("fur")
static const itype_id itype_leather ("leather")
static const itype_id itype_sheet_cotton ("sheet_cotton")
static const json_character_flag json_flag_CBQ_LEARN_BONUS ("CBQ_LEARN_BONUS")
static const json_character_flag json_flag_GRAB ("GRAB")
static const json_character_flag json_flag_GRAB_FILTER ("GRAB_FILTER")
static const json_character_flag json_flag_HARDTOHIT ("HARDTOHIT")
static const json_character_flag json_flag_HYPEROPIC ("HYPEROPIC")
static const json_character_flag json_flag_NEED_ACTIVE_TO_MELEE ("NEED_ACTIVE_TO_MELEE")
static const json_character_flag json_flag_NULL ("NULL")
static const json_character_flag json_flag_PSEUDOPOD_GRASP ("PSEUDOPOD_GRASP")
static const json_character_flag json_flag_UNARMED_BONUS ("UNARMED_BONUS")
static const limb_score_id limb_score_block ("block")
static const limb_score_id limb_score_grip ("grip")
static const limb_score_id limb_score_reaction ("reaction")
static const matec_id WBLOCK_1 ("WBLOCK_1")
static const matec_id WBLOCK_2 ("WBLOCK_2")
static const matec_id WBLOCK_3 ("WBLOCK_3")
static const matec_id WHIP_DISARM ("WHIP_DISARM")
static const material_id material_glass ("glass")
static const material_id material_steel ("steel")
static const move_mode_id move_mode_prone ("prone")
static const skill_id skill_melee ("melee")
static const skill_id skill_spellcraft ("spellcraft")
static const skill_id skill_unarmed ("unarmed")
static const trait_id trait_ARM_TENTACLES ("ARM_TENTACLES")
static const trait_id trait_ARM_TENTACLES_4 ("ARM_TENTACLES_4")
static const trait_id trait_ARM_TENTACLES_8 ("ARM_TENTACLES_8")
static const trait_id trait_BEAK_PECK ("BEAK_PECK")
static const trait_id trait_CLAWS_TENTACLE ("CLAWS_TENTACLE")
static const trait_id trait_CLUMSY ("CLUMSY")
static const trait_id trait_DEBUG_NIGHTVISION ("DEBUG_NIGHTVISION")
static const trait_id trait_DEFT ("DEFT")
static const trait_id trait_POISONOUS ("POISONOUS")
static const trait_id trait_POISONOUS2 ("POISONOUS2")
static const trait_id trait_PROF_SKATER ("PROF_SKATER")
static const trait_id trait_VINES2 ("VINES2")
static const trait_id trait_VINES3 ("VINES3")
static const weapon_category_id weapon_category_UNARMED ("UNARMED")
melee_statistic_data melee::melee_stats
Function Documentation
get_damage_unit()
static damage_unit& get_damage_unit (std::vector< damage_unit > & di, const damage_type_id & dt) static
Definition at line 1772 of file melee.cpp.
 {
     static damage_unit nullunit( damage_type_id::NULL_ID(), 0, 0, 0, 0 );
     for( damage_unit &du : di ) {
         if( du.type == dt && du.amount > 0 ) {
             return du;
         }
     }
     return nullunit;
 }
References string_id< damage_type >::NULL_ID().
Referenced by Character::perform_technique().
hardcoded_mutation_attack()
static damage_instance hardcoded_mutation_attack (const Character & u, const trait_id & id) static
Dexterity increases number of hits with BEAK_PECK Unarmed increases number of hits with BEAK_PECK Strength increases damage with ARM_TENTACLES* Strength increases damage with VINES*
Definition at line 2399 of file melee.cpp.
 {
     if( id == trait_BEAK_PECK ) {
         // method open to improvement, please feel free to suggest
         // a better way to simulate target's anti-peck efforts
         /** @EFFECT_DEX increases number of hits with BEAK_PECK */
         /** @EFFECT_UNARMED increases number of hits with BEAK_PECK */
         int num_hits = std::max( 1, std::min<int>( 6,
                                  u.get_dex() + u.get_skill_level( skill_unarmed ) - rng( 4, 10 ) ) );
         damage_instance di = damage_instance();
         di.add_damage( damage_stab, num_hits * 10 );
         return di;
     }
     if( id == trait_ARM_TENTACLES || id == trait_ARM_TENTACLES_4 || id == trait_ARM_TENTACLES_8 ) {
         int num_attacks = 1;
         if( id == trait_ARM_TENTACLES_4 ) {
             num_attacks = 3;
         } else if( id == trait_ARM_TENTACLES_8 ) {
             num_attacks = 7;
         }
         // Note: we're counting arms, so we want wielded item here, not weapon used for attack
         if( ( u.get_wielded_item() && u.get_wielded_item()->is_two_handed( u ) ) ||
             !u.has_two_arms_lifting() || u.worn_with_flag( flag_RESTRICT_HANDS ) ) {
             num_attacks--;
         }
         if( num_attacks <= 0 ) {
             return damage_instance();
         }
         const bool rake = u.has_trait( trait_CLAWS_TENTACLE );
         /** @EFFECT_STR increases damage with ARM_TENTACLES* */
         damage_instance ret;
         if( rake ) {
             ret.add_damage( damage_cut, u.get_str() / 2.0f + 1.0f, 0, 1.0f, num_attacks );
         } else {
             ret.add_damage( damage_bash, u.get_str() / 3.0f + 1.0f, 0, 1.0f, num_attacks );
         }
         return ret;
     }
     if( id == trait_VINES2 || id == trait_VINES3 ) {
         const int num_attacks = id == trait_VINES2 ? 2 : 3;
         /** @EFFECT_STR increases damage with VINES* */
         damage_instance ret;
         ret.add_damage( damage_bash, u.get_str() / 2.0f, 0, 1.0f, num_attacks );
         return ret;
     }
     debugmsg( "Invalid hardcoded mutation id: %s", id.c_str() );
     return damage_instance();
 }
References damage_instance::add_damage(), damage_bash, damage_cut, damage_stab, debugmsg, flag_RESTRICT_HANDS, max(), cata::hash64_detail::ret, rng(), skill_unarmed, trait_ARM_TENTACLES, trait_ARM_TENTACLES_4, trait_ARM_TENTACLES_8, trait_BEAK_PECK, trait_CLAWS_TENTACLE, trait_VINES2, trait_VINES3, and u.
Referenced by Character::mutation_attacks().
limit_probability()
static double limit_probability (double unbounded_probability) static
Limits a probability to be between 0.0 and 1.0.
Definition at line 1125 of file melee.cpp.
 {
     return std::max( std::min( unbounded_probability, 1.0 ), 0.0 );
 }
References max(), and min().
Referenced by Character::crit_chance().
melee_message()
std::string melee_message (const ma_technique & tec, Character & p, const dealt_damage_instance & ddi) static
Definition at line 2536 of file melee.cpp.
 {
     // Those could be extracted to a json
     // Three last values are for low damage
     static const std::array<std::string, 6> player_stab = {{
             translate_marker( "You impale %s" ),
             translate_marker( "You gouge %s" ),
             translate_marker( "You run %s through" ),
             translate_marker( "You puncture %s" ),
             translate_marker( "You pierce %s" ),
             translate_marker( "You poke %s" )
         }
     };
     static const std::array<std::string, 6> npc_stab = {{
             translate_marker( "<npcname> impales %s" ),
             translate_marker( "<npcname> gouges %s" ),
             translate_marker( "<npcname> runs %s through" ),
             translate_marker( "<npcname> punctures %s" ),
             translate_marker( "<npcname> pierces %s" ),
             translate_marker( "<npcname> pokes %s" )
         }
     };
     // First 5 are for high damage, next 2 for medium, then for low and then for v. low
     static const std::array<std::string, 9> player_cut = {{
             translate_marker( "You gut %s" ),
             translate_marker( "You chop %s" ),
             translate_marker( "You slash %s" ),
             translate_marker( "You mutilate %s" ),
             translate_marker( "You maim %s" ),
             translate_marker( "You stab %s" ),
             translate_marker( "You slice %s" ),
             translate_marker( "You cut %s" ),
             translate_marker( "You nick %s" )
         }
     };
     static const std::array<std::string, 9> npc_cut = {{
             translate_marker( "<npcname> guts %s" ),
             translate_marker( "<npcname> chops %s" ),
             translate_marker( "<npcname> slashes %s" ),
             translate_marker( "<npcname> mutilates %s" ),
             translate_marker( "<npcname> maims %s" ),
             translate_marker( "<npcname> stabs %s" ),
             translate_marker( "<npcname> slices %s" ),
             translate_marker( "<npcname> cuts %s" ),
             translate_marker( "<npcname> nicks %s" )
         }
     };
     // Three last values are for low damage
     static const std::array<std::string, 6> player_bash = {{
             translate_marker( "You clobber %s" ),
             translate_marker( "You smash %s" ),
             translate_marker( "You thrash %s" ),
             translate_marker( "You batter %s" ),
             translate_marker( "You whack %s" ),
             translate_marker( "You hit %s" )
         }
     };
     static const std::array<std::string, 6> npc_bash = {{
             translate_marker( "<npcname> clobbers %s" ),
             translate_marker( "<npcname> smashes %s" ),
             translate_marker( "<npcname> thrashes %s" ),
             translate_marker( "<npcname> batters %s" ),
             translate_marker( "<npcname> whacks %s" ),
             translate_marker( "<npcname> hits %s" )
         }
     };
     int total_dam = 0;
     std::pair<damage_type_id, int> dominant_type = { damage_bash, 0 };
     for( const damage_type &dt : damage_type::get_all() ) {
         if( dt.melee_only ) {
             int dmg = ddi.type_damage( dt.id );
             total_dam += dmg;
             if( dominant_type.second < dmg ) {
                 dominant_type = { dt.id, dmg };
             }
         }
     }
     if( tec.id != tec_none ) {
         std::string message;
         if( p.is_npc() ) {
             message = tec.npc_message.translated();
         } else {
             message = tec.avatar_message.translated();
         }
         if( !message.empty() ) {
             return message;
         }
     }
     const bool npc = p.is_npc();
     // Cutting has more messages and so needs different handling
     const bool cutting = dominant_type.first == damage_cut;
     size_t index;
     if( total_dam > 30 ) {
         index = cutting ? rng( 0, 4 ) : rng( 0, 2 );
     } else if( total_dam > 20 ) {
         index = cutting ? rng( 5, 6 ) : 3;
     } else if( total_dam > 10 ) {
         index = cutting ? 7 : 4;
     } else {
         index = cutting ? 8 : 5;
     }
     std::string message;
     // FIXME: Hardcoded damage type messages
     if( dominant_type.first == damage_stab ) {
         message = npc ? _( npc_stab[index] ) : _( player_stab[index] );
     } else if( dominant_type.first == damage_cut ) {
         message = npc ? _( npc_cut[index] ) : _( player_cut[index] );
     } else if( dominant_type.first == damage_bash ) {
         message = npc ? _( npc_bash[index] ) : _( player_bash[index] );
     }
     if( ddi.wp_hit.empty() ) {
         return message;
     } else {
         //~ %1$s: "Somone hit something", %2$s: the weakpoint that was hit
         return string_format( _( "%1$s in %2$s" ), message, ddi.wp_hit );
     }
     return _( "The bugs attack %s" );
 }
References _, ma_technique::avatar_message, damage_bash, damage_cut, damage_stab, damage_type::get_all(), ma_technique::id, Character::is_npc(), mapgen_defer::message, ma_technique::npc_message, rng(), string_format(), tec_none, translate_marker, translation::translated(), dealt_damage_instance::type_damage(), and dealt_damage_instance::wp_hit.
Referenced by Character::melee_attack_abstract().
melee_train()
static void melee_train (Character & you, int lo, int hi, const item & weap, const std::string & attack_vector) static
Definition at line 455 of file melee.cpp.
 {
     you.practice( skill_melee, std::ceil( rng( lo, hi ) / 2.0 ), hi );
     float total = 0.f;
     // allocate XP proportional to damage stats
     // Pure unarmed needs a special case because it has 0 weapon damage
     std::map<damage_type_id, int> dmg_vals;
     for( const damage_type &dt : damage_type::get_all() ) {
         if( !dt.melee_only ) {
             continue;
         }
         int dmg = weap.damage_melee( dt.id );
         if( weap.is_null() && dt.id == damage_bash ) {
             dmg++;
         }
         dmg_vals[dt.id] = dmg;
         total += dmg;
     }
     total = std::max( total, 1.f );
     // Unarmed may deal cut, stab, and bash damage depending on the weapon
     if( attack_vector != "WEAPON" ) {
         you.practice( skill_unarmed, std::ceil( 1 * rng( lo, hi ) ), hi );
     } else {
         for( const std::pair<const damage_type_id, int> &dmg : dmg_vals ) {
             if( !dmg.first->skill.is_null() ) {
                 you.practice( dmg.first->skill, std::ceil( dmg.second / total * rng( lo, hi ) ), hi );
             }
         }
     }
 }
References ceil(), damage_bash, item::damage_melee(), damage_type::get_all(), item::is_null(), cata::hash64_detail::lo, max(), Character::practice(), rng(), skill_melee, and skill_unarmed.
Referenced by Character::melee_attack_abstract().
player_hit_message()
void player_hit_message (Character * attacker, const std::string & message, Creature & t, int dam, bool crit = false, bool technique = false, const std::string & wp_hit = {}) static
Definition at line 2665 of file melee.cpp.
 {
     std::string msg;
     game_message_type msgtype = m_good;
     std::string sSCTmod;
     game_message_type gmtSCTcolor = m_good;
     Character &player_character = get_player_character();
     if( dam <= 0 ) {
         if( attacker->is_npc() ) {
             //~ NPC hits something but does no damage
             msg = string_format( _( "%s but does no damage." ), message );
         } else {
             //~ someone hits something but do no damage
             msg = string_format( _( "%s but do no damage." ), message );
         }
         msgtype = m_neutral;
     } else if( crit ) {
         //Player won't see exact numbers of damage dealt by NPC unless player has DEBUG_NIGHTVISION trait
         if( attacker->is_npc() && !player_character.has_trait( trait_DEBUG_NIGHTVISION ) ) {
             //~ NPC hits something (critical)
             msg = string_format( _( "%s.  Critical!" ), message );
         } else if( technique && !wp_hit.empty() ) {
             //~ %1$s: "someone hits something", %2$d: damage dealt, %3$s: the weakpoint hit
             msg = string_format( _( "%1$s for %2$d damage, and hit it in %3$s.  Critical!" ), message, dam,
                                  wp_hit );
         } else {
             //~ someone hits something for %d damage (critical)
             msg = string_format( _( "%s for %d damage.  Critical!" ), message, dam );
         }
         sSCTmod = _( "Critical!" );
         gmtSCTcolor = m_critical;
     } else {
         if( attacker->is_npc() && !player_character.has_trait( trait_DEBUG_NIGHTVISION ) ) {
             //~ NPC hits something
             msg = string_format( _( "%s." ), message );
         } else if( technique && !wp_hit.empty() ) {
             //~ %1$s: "someone hits something", %2$d: damage dealt, %3$s: the weakpoint hit
             msg = string_format( _( "%1$s for %2$d damage, and hit it in %3$s." ), message, dam, wp_hit );
         } else {
             //~ someone hits something for %d damage
             msg = string_format( _( "%s for %d damage." ), message, dam );
         }
     }
     if( dam > 0 && attacker->is_avatar() ) {
         //player hits monster melee
         SCT.add( point( t.posx(), t.posy() ),
                  direction_from( point_zero, point( t.posx() - attacker->posx(), t.posy() - attacker->posy() ) ),
                  get_hp_bar( dam, t.get_hp_max(), true ).first, m_good,
                  sSCTmod, gmtSCTcolor );
         if( t.get_hp() > 0 ) {
             SCT.add( point( t.posx(), t.posy() ),
                      direction_from( point_zero, point( t.posx() - attacker->posx(), t.posy() - attacker->posy() ) ),
                      get_hp_bar( t.get_hp(), t.get_hp_max(), true ).first, m_good,
                      //~ "hit points", used in scrolling combat text
                      _( "HP" ), m_neutral,
                      "hp" );
         } else {
             SCT.removeCreatureHP();
         }
     }
     // same message is used for player and npc,
     // just using this for the <npcname> substitution.
     attacker->add_msg_player_or_npc( msgtype, msg, msg, t.disp_name() );
 }
References _, scrollingcombattext::add(), Character::add_msg_player_or_npc(), direction_from(), Creature::disp_name(), Creature::get_hp(), get_hp_bar(), Creature::get_hp_max(), get_player_character(), Character::has_trait(), Creature::is_avatar(), Character::is_npc(), m_critical, m_good, m_neutral, mapgen_defer::message, point_zero, Creature::posx(), Creature::posy(), scrollingcombattext::removeCreatureHP(), SCT, string_format(), and trait_DEBUG_NIGHTVISION.
Referenced by Character::melee_attack_abstract(), and Character::perform_special_attacks().
print_damage_info()
static void print_damage_info (const damage_instance & di) static
Definition at line 1784 of file melee.cpp.
 {
     if( !debug_mode ) {
         return;
     }
     int total = 0;
     std::string ss;
     for( const damage_unit &du : di.damage_units ) {
         int amount = di.type_damage( du.type );
         total += amount;
         ss += du.type->name.translated() + ":" + std::to_string( amount ) + ",";
     }
     add_msg_debug( debugmode::DF_MELEE, "%stotal: %d", ss, total );
 }
References add_msg_debug, damage_instance::damage_units, debug_mode, debugmode::DF_MELEE, damage_type::name, to_string(), translation::translated(), damage_unit::type, and damage_instance::type_damage().
Referenced by Character::perform_technique().
roll_melee_damage_internal()
static void roll_melee_damage_internal (const Character & u, const damage_type_id & dt, bool crit, damage_instance & di, bool average, const item & weap, const std::string & attack_vector, float crit_mod) static
@ARM_STR increases bashing damage
Strength increases bashing damage Bashing caps bash damage with bashing weapons Unarmed caps bash damage with unarmed weapons Stabbing increases stabbing damage multiplier
@ARM_STR boosts low cap on bashing damage
Definition at line 1285 of file melee.cpp.
 {
     // FIXME: Hardcoded damage type
     float dmg = dt == damage_bash ? 0.f : u.mabuff_damage_bonus( dt ) + weap.damage_melee( dt );
     bool unarmed = attack_vector != "WEAPON";
     int arpen = 0;
     float skill = u.get_skill_level( unarmed ? skill_unarmed : dt->skill );
     if( u.has_active_bionic( bio_cqb ) ) {
         skill = BIO_CQB_LEVEL;
     }
     if( unarmed ) {
         bool bp_unrestricted;
         if( attack_vector == "ARM" ) {
             bp_unrestricted = !u.natural_attack_restricted_on( bodypart_id( "arm_l" ) ) ||
                               ( !u.natural_attack_restricted_on( bodypart_id( "arm_r" ) ) );
         } else if( attack_vector == "ELBOW" ) {
             bp_unrestricted = !u.natural_attack_restricted_on( sub_bodypart_id( "arm_elbow_l" ) ) ||
                               ( !u.natural_attack_restricted_on( sub_bodypart_id( "arm_elbow_r" ) ) );
         } else if( attack_vector == "WRIST" ) {
             bp_unrestricted = !u.natural_attack_restricted_on( sub_bodypart_id( "hand_wrist_l" ) ) ||
                               ( !u.natural_attack_restricted_on( sub_bodypart_id( "hand_wrist_r" ) ) );
         } else if( attack_vector == "SHOULDER" ) {
             bp_unrestricted = !u.natural_attack_restricted_on( sub_bodypart_id( "arm_shoulder_l" ) ) ||
                               ( !u.natural_attack_restricted_on( sub_bodypart_id( "arm_shoulder_r" ) ) );
         } else if( attack_vector == "FOOT" ) {
             bp_unrestricted = !u.natural_attack_restricted_on( bodypart_id( "foot_l" ) ) ||
                               ( !u.natural_attack_restricted_on( bodypart_id( "foot_r" ) ) );
         } else if( attack_vector == "LOWER_LEG" ) {
             bp_unrestricted = !u.natural_attack_restricted_on( sub_bodypart_id( "leg_lower_l" ) ) ||
                               ( !u.natural_attack_restricted_on( sub_bodypart_id( "leg_lower_r" ) ) );
         } else if( attack_vector == "KNEE" ) {
             bp_unrestricted = !u.natural_attack_restricted_on( sub_bodypart_id( "leg_knee_l" ) ) ||
                               ( !u.natural_attack_restricted_on( sub_bodypart_id( "leg_knee_r" ) ) );
         } else if( attack_vector == "HIP" ) {
             bp_unrestricted = !u.natural_attack_restricted_on( sub_bodypart_id( "leg_hip_l" ) ) ||
                               ( !u.natural_attack_restricted_on( sub_bodypart_id( "leg_hip_r" ) ) );
         } else if( attack_vector == "HEAD" ) {
             bp_unrestricted = !u.natural_attack_restricted_on( bodypart_id( "head" ) );
         } else if( attack_vector == "MOUTH" ) {
             bp_unrestricted = !u.natural_attack_restricted_on( bodypart_id( "mouth" ) );
         } else if( attack_vector == "TORSO" ) {
             bp_unrestricted = !u.natural_attack_restricted_on( bodypart_id( "torso" ) );
         } else {
             bp_unrestricted = !u.natural_attack_restricted_on( bodypart_id( "hand_l" ) ) ||
                               ( !u.natural_attack_restricted_on( bodypart_id( "hand_r" ) ) && weap.is_null() );
         }
         if( bp_unrestricted ) {
             float extra_damage = 0.0f;
             for( const trait_id &mut : u.get_mutations() ) {
                 if( mut->flags.count( json_flag_NEED_ACTIVE_TO_MELEE ) > 0 && !u.has_active_mutation( mut ) ) {
                     continue;
                 }
                 float unarmed_bonus = 0.0f;
                 int bonus_dmg = 0;
                 std::pair<int, int> bonus_rand = { 0, 0 };
                 if( mut->flags.count( json_flag_UNARMED_BONUS ) > 0 && bonus_dmg > 0 ) {
                     unarmed_bonus += std::min( u.get_skill_level( skill_unarmed ) / 2, 4.0f );
                 }
                 extra_damage += bonus_dmg + unarmed_bonus;
                 extra_damage += average ? ( bonus_rand.first + bonus_rand.second ) / 2.0f :
                                 rng( bonus_rand.first, bonus_rand.second );
             }
             // FIXME: Hardcoded damage type effect (stab)
             if( attack_vector == "HAND" && dt == damage_stab && u.has_bionic( bio_razors ) ) {
                 extra_damage += 2;
             }
             dmg += extra_damage;
         }
         float dam = 0.0f;
         float ap = 0.0f;
         for( const bodypart_id &bp : u.get_all_body_parts() ) {
             if( bp->unarmed_bonus && !u.natural_attack_restricted_on( bp ) ) {
                 dam += bp->unarmed_damage( dt );
                 ap += bp->unarmed_arpen( dt );
             }
         }
         dmg += dam;
         arpen += ap;
     }
     /** @ARM_STR increases bashing damage */
     float stat_bonus = u.bonus_damage( !average );
     stat_bonus += u.mabuff_damage_bonus( dt );
     /** @EFFECT_STR increases bashing damage */
     float weap_dam = weap.damage_melee( dt ) + stat_bonus;
     /** @EFFECT_BASHING caps bash damage with bashing weapons */
     float bash_cap = 2 * u.get_arm_str() + 2 * skill;
     // FIXME: Hardcoded damage type effects (bash)
     if( dt != damage_bash && dmg <= 0 ) {
         return; // No negative damage!
     } else if( dt == damage_bash ) {
         float melee_bonus = u.get_skill_level( skill_melee );
         /** @EFFECT_UNARMED caps bash damage with unarmed weapons */
         if( u.is_melee_bash_damage_cap_bonus() ) {
             bash_cap += melee_bonus;
         }
     }
     float dmg_mul = 1.0f;
     // FIXME: Hardcoded damage type effects (stab)
     if( dt == damage_stab ) {
         // 66%, 76%, 86%, 96%, 106%, 116%, 122%, 128%, 134%, 140%
         /** @EFFECT_STABBING increases stabbing damage multiplier */
         if( skill <= 5 ) {
             dmg_mul = 0.66 + 0.1 * skill;
         } else {
             dmg_mul = 0.86 + 0.06 * skill;
         }
     } else {
         // 80%, 88%, 96%, 104%, 112%, 116%, 120%, 124%, 128%, 132%
         if( skill < 5 ) {
             dmg_mul *= 0.8 + 0.08 * skill;
         } else {
             dmg_mul *= 0.96 + 0.04 * skill;
         }
     }
     // FIXME: Hardcoded damage type effects (bash)
     if( dt == damage_bash ) {
         if( bash_cap < weap_dam && !weap.is_null() ) {
             // If damage goes over cap due to low stats/skills,
             // scale the post-armor damage down halfway between damage and cap
             dmg_mul *= ( 1.0f + ( bash_cap / weap_dam ) ) / 2.0f;
         }
         /** @ARM_STR boosts low cap on bashing damage */
         const float low_cap = std::min( 1.0f, u.get_arm_str() / 20.0f );
         const float bash_min = low_cap * weap_dam;
         weap_dam = average ? ( bash_min + weap_dam ) * 0.5f : rng_float( bash_min, weap_dam );
         dmg += weap_dam;
     }
     dmg_mul *= u.mabuff_damage_mult( dt );
     arpen += u.mabuff_arpen_bonus( dt );
     float armor_mult = 1.0f;
     if( crit ) {
         // FIXME: Hardcoded damage type effects (stab, cut, bash)
         if( dt == damage_stab ) {
             // Critical damage bonus for stabbing scales with skill
             dmg_mul *= 1.0 + ( skill / 10.0 ) * crit_mod;
             // Stab criticals have extra %arpen
             armor_mult = 1.f - 0.34f * crit_mod;
         } else if( dt == damage_cut ) {
             dmg_mul *= 1.f + 0.25f * crit_mod;
             arpen += static_cast<int>( 5.f * crit_mod );
             // 25% armor penetration
             armor_mult = 1.f - 0.25f * crit_mod;
         } else if( dt == damage_bash ) {
             dmg_mul *= 1.f + 0.5f * crit_mod;
             // 50% armor penetration
             armor_mult = 0.5f * crit_mod;
         }
     }
     di.add_damage( dt, dmg, arpen, armor_mult, dmg_mul );
 }
References damage_instance::add_damage(), bio_cqb, BIO_CQB_LEVEL, bio_razors, bp, damage_bash, damage_cut, item::damage_melee(), damage_stab, item::is_null(), json_flag_NEED_ACTIVE_TO_MELEE, json_flag_UNARMED_BONUS, min(), rng(), rng_float(), damage_type::skill, skill_melee, skill_unarmed, u, body_part_type::unarmed_arpen(), body_part_type::unarmed_bonus, and body_part_type::unarmed_damage().
Referenced by Character::roll_damage().
stumble()
int stumble (Character & u, const item_location & weap) static
Strength reduces chance of stumbling with heavier weapons
Definition at line 1092 of file melee.cpp.
 {
     if( !weap || u.has_trait( trait_DEFT ) ) {
         return 0;
     }
     item cur_weap = weap ? *weap : null_item_reference();
     units::mass str_mod = u.get_arm_str() * 10_gram;
     // Ceph and Slime mutants still need good posture to prevent stumbling
     if( u.is_on_ground() ) {
         str_mod /= 4;
         // but quadrupeds fight naturally on all fours
     } else if( u.is_crouching() && ( !u.has_effect( effect_natural_stance ) && !u.unarmed_attack() ) ) {
         str_mod /= 2;
     }
     // Examples:
     // 10 str with a hatchet: 4 + 8 = 12
     // 5 str with a battle axe: 26 + 49 = 75
     // Fist: 0
     /** @EFFECT_STR reduces chance of stumbling with heavier weapons */
     return ( weap->volume() / 125_ml ) +
            ( weap->weight() / ( str_mod + 13.0_gram ) );
 }
References effect_natural_stance, null_item_reference(), trait_DEFT, u, item::volume(), and item::weight().
Referenced by avatar::disarm(), and Character::melee_attack_abstract().
wielded_weapon_categories()
static const std::set<weapon_category_id>& wielded_weapon_categories (const Character & c) static
Definition at line 581 of file melee.cpp.
 {
     static const std::set<weapon_category_id> unarmed{ weapon_category_UNARMED };
     if( c.get_wielded_item() ) {
         return c.get_wielded_item()->typeId()->weapon_category;
     }
     return unarmed;
 }
References c, and weapon_category_UNARMED.
Referenced by Character::get_total_melee_stamina_cost(), and Character::melee_attack_abstract().
Variable Documentation
anatomy_human_anatomy
const anatomy_id anatomy_human_anatomy("human_anatomy") ("human_anatomy") static
Referenced by Character::get_dodge().
bio_cqb
const bionic_id bio_cqb("bio_cqb") ("bio_cqb") static
Referenced by Character::attack_speed(), Character::block_hit(), Character::crit_chance(), Character::get_hit_weapon(), Character::melee_attack_abstract(), and roll_melee_damage_internal().
bio_heat_absorb
const bionic_id bio_heat_absorb("bio_heat_absorb") ("bio_heat_absorb") static
Referenced by Character::melee_special_effects().
bio_razors
const bionic_id bio_razors("bio_razors") ("bio_razors") static
Referenced by roll_melee_damage_internal().
bio_shock
const bionic_id bio_shock("bio_shock") ("bio_shock") static
Referenced by Character::melee_special_effects().
character_modifier_limb_dodge_mod
const character_modifier_id character_modifier_limb_dodge_mod("limb_dodge_mod") ("limb_dodge_mod") static
Referenced by Character::get_dodge().
character_modifier_melee_attack_roll_mod
const character_modifier_id character_modifier_melee_attack_roll_mod("melee_attack_roll_mod") ("melee_attack_roll_mod") static
Referenced by Character::hit_roll().
character_modifier_melee_thrown_move_balance_mod
const character_modifier_id character_modifier_melee_thrown_move_balance_mod("melee_thrown_move_balance_mod") ("melee_thrown_move_balance_mod") static
Referenced by Character::attack_speed().
character_modifier_melee_thrown_move_lift_mod
const character_modifier_id character_modifier_melee_thrown_move_lift_mod("melee_thrown_move_lift_mod") ("melee_thrown_move_lift_mod") static
Referenced by Character::attack_speed().
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by hardcoded_mutation_attack(), melee_message(), melee_train(), Character::perform_technique(), Character::reach_attack(), and roll_melee_damage_internal().
damage_cut
const damage_type_id damage_cut("cut") ("cut") static
Referenced by hardcoded_mutation_attack(), melee_message(), Character::melee_special_effects(), and roll_melee_damage_internal().
damage_stab
const damage_type_id damage_stab("stab") ("stab") static
Referenced by hardcoded_mutation_attack(), melee_message(), and roll_melee_damage_internal().
effect_amigara
const efftype_id effect_amigara("amigara") ("amigara") static
Referenced by Character::perform_technique().
effect_beartrap
const efftype_id effect_beartrap("beartrap") ("beartrap") static
Referenced by Character::get_dodge().
effect_contacts
const efftype_id effect_contacts("contacts") ("contacts") static
Referenced by Character::get_miss_reason(), and Character::hit_roll().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by Character::perform_technique().
effect_fearparalyze
const efftype_id effect_fearparalyze("fearparalyze") ("fearparalyze") static
Referenced by Character::block_hit().
effect_heavysnare
const efftype_id effect_heavysnare("heavysnare") ("heavysnare") static
Referenced by Character::get_dodge().
effect_hit_by_player
const efftype_id effect_hit_by_player("hit_by_player") ("hit_by_player") static
Referenced by Character::melee_attack_abstract().
effect_incorporeal
const efftype_id effect_incorporeal("incorporeal") ("incorporeal") static
Referenced by Character::melee_attack().
effect_lightsnare
const efftype_id effect_lightsnare("lightsnare") ("lightsnare") static
Referenced by Character::get_dodge().
effect_narcosis
const efftype_id effect_narcosis("narcosis") ("narcosis") static
Referenced by Character::block_hit().
effect_natural_stance
const efftype_id effect_natural_stance("natural_stance") ("natural_stance") static
Referenced by Character::attack_speed(), Character::get_total_melee_stamina_cost(), Character::hit_roll(), Character::melee_attack_abstract(), and stumble().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by Character::reach_attack().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by Character::melee_attack_abstract(), and Character::perform_technique().
effect_transition_contacts
const efftype_id effect_transition_contacts("transition_contacts") ("transition_contacts") static
Referenced by Character::get_miss_reason(), and Character::hit_roll().
effect_venom_dmg
const efftype_id effect_venom_dmg("venom_dmg") ("venom_dmg") static
Referenced by Character::melee_attack_abstract().
effect_venom_player1
const efftype_id effect_venom_player1("venom_player1") ("venom_player1") static
Referenced by Character::melee_attack_abstract().
effect_venom_player2
const efftype_id effect_venom_player2("venom_player2") ("venom_player2") static
Referenced by Character::melee_attack_abstract().
effect_venom_weaken
const efftype_id effect_venom_weaken("venom_weaken") ("venom_weaken") static
Referenced by Character::melee_attack_abstract().
effect_winded
const efftype_id effect_winded("winded") ("winded") static
Referenced by Character::block_hit().
itype_fur
const itype_id itype_fur("fur") ("fur") static
Referenced by Character::handle_melee_wear().
itype_leather
const itype_id itype_leather("leather") ("leather") static
Referenced by Character::handle_melee_wear().
itype_sheet_cotton
const itype_id itype_sheet_cotton("sheet_cotton") ("sheet_cotton") static
Referenced by Character::handle_melee_wear().
json_flag_CBQ_LEARN_BONUS
const json_character_flag json_flag_CBQ_LEARN_BONUS("CBQ_LEARN_BONUS") ("CBQ_LEARN_BONUS") static
Referenced by Character::melee_attack_abstract().
json_flag_GRAB
const json_character_flag json_flag_GRAB("GRAB") ("GRAB") static
Referenced by Character::perform_technique().
json_flag_GRAB_FILTER
const json_character_flag json_flag_GRAB_FILTER("GRAB_FILTER") ("GRAB_FILTER") static
Referenced by Character::perform_technique().
json_flag_HARDTOHIT
const json_character_flag json_flag_HARDTOHIT("HARDTOHIT") ("HARDTOHIT") static
Referenced by Character::dodge_roll().
json_flag_HYPEROPIC
const json_character_flag json_flag_HYPEROPIC("HYPEROPIC") ("HYPEROPIC") static
Referenced by Character::get_miss_reason(), and Character::hit_roll().
json_flag_NEED_ACTIVE_TO_MELEE
const json_character_flag json_flag_NEED_ACTIVE_TO_MELEE("NEED_ACTIVE_TO_MELEE") ("NEED_ACTIVE_TO_MELEE") static
Referenced by roll_melee_damage_internal().
json_flag_NULL
const json_character_flag json_flag_NULL("NULL") ("NULL") static
Referenced by Character::perform_technique().
json_flag_PSEUDOPOD_GRASP
const json_character_flag json_flag_PSEUDOPOD_GRASP("PSEUDOPOD_GRASP") ("PSEUDOPOD_GRASP") static
Referenced by Character::attack_speed(), Character::get_total_melee_stamina_cost(), Character::hit_roll(), and Character::melee_attack_abstract().
json_flag_UNARMED_BONUS
const json_character_flag json_flag_UNARMED_BONUS("UNARMED_BONUS") ("UNARMED_BONUS") static
Referenced by roll_melee_damage_internal().
limb_score_block
const limb_score_id limb_score_block("block") ("block") static
Referenced by Character::block_hit().
limb_score_grip
const limb_score_id limb_score_grip("grip") ("grip") static
Referenced by avatar::disarm().
limb_score_reaction
const limb_score_id limb_score_reaction("reaction") ("reaction") static
Referenced by Character::block_hit(), avatar::disarm(), and Character::get_dodge().
material_glass
const material_id material_glass("glass") ("glass") static
Referenced by Character::block_hit(), and Character::melee_special_effects().
material_steel
const material_id material_steel("steel") ("steel") static
Referenced by Character::melee_attack_abstract().
move_mode_prone
const move_mode_id move_mode_prone("prone") ("prone") static
Referenced by Character::melee_attack_abstract().
skill_melee
const skill_id skill_melee("melee") ("melee") static
Referenced by Character::attack_speed(), Character::block_hit(), Character::crit_chance(), avatar::disarm(), Character::get_hit_weapon(), Character::get_total_melee_stamina_cost(), Character::handle_melee_wear(), melee_train(), Character::reach_attack(), and roll_melee_damage_internal().
skill_spellcraft
const skill_id skill_spellcraft("spellcraft") ("spellcraft") static
Referenced by Character::get_spell_resist().
skill_unarmed
const skill_id skill_unarmed("unarmed") ("unarmed") static
Referenced by Character::block_hit(), Character::crit_chance(), avatar::disarm(), hardcoded_mutation_attack(), melee_train(), Character::mutation_attacks(), Character::perform_special_attacks(), and roll_melee_damage_internal().
trait_ARM_TENTACLES
const trait_id trait_ARM_TENTACLES("ARM_TENTACLES") ("ARM_TENTACLES") static
Referenced by hardcoded_mutation_attack().
trait_ARM_TENTACLES_4
const trait_id trait_ARM_TENTACLES_4("ARM_TENTACLES_4") ("ARM_TENTACLES_4") static
Referenced by hardcoded_mutation_attack().
trait_ARM_TENTACLES_8
const trait_id trait_ARM_TENTACLES_8("ARM_TENTACLES_8") ("ARM_TENTACLES_8") static
Referenced by hardcoded_mutation_attack().
trait_BEAK_PECK
const trait_id trait_BEAK_PECK("BEAK_PECK") ("BEAK_PECK") static
Referenced by hardcoded_mutation_attack().
trait_CLAWS_TENTACLE
const trait_id trait_CLAWS_TENTACLE("CLAWS_TENTACLE") ("CLAWS_TENTACLE") static
Referenced by hardcoded_mutation_attack().
trait_CLUMSY
const trait_id trait_CLUMSY("CLUMSY") ("CLUMSY") static
Referenced by avatar::steal().
trait_DEBUG_NIGHTVISION
const trait_id trait_DEBUG_NIGHTVISION("DEBUG_NIGHTVISION") ("DEBUG_NIGHTVISION") static
Referenced by player_hit_message().
trait_DEFT
const trait_id trait_DEFT("DEFT") ("DEFT") static
Referenced by Character::melee_attack_abstract(), avatar::steal(), and stumble().
trait_POISONOUS
const trait_id trait_POISONOUS("POISONOUS") ("POISONOUS") static
Referenced by Character::melee_attack_abstract().
trait_POISONOUS2
const trait_id trait_POISONOUS2("POISONOUS2") ("POISONOUS2") static
Referenced by Character::melee_attack_abstract().
trait_PROF_SKATER
const trait_id trait_PROF_SKATER("PROF_SKATER") ("PROF_SKATER") static
Referenced by Character::get_dodge().
trait_VINES2
const trait_id trait_VINES2("VINES2") ("VINES2") static
Referenced by hardcoded_mutation_attack().
trait_VINES3
const trait_id trait_VINES3("VINES3") ("VINES3") static
Referenced by hardcoded_mutation_attack().
WBLOCK_1
const matec_id WBLOCK_1("WBLOCK_1") ("WBLOCK_1") static
Referenced by melee::blocking_ability().
WBLOCK_2
const matec_id WBLOCK_2("WBLOCK_2") ("WBLOCK_2") static
Referenced by melee::blocking_ability().
WBLOCK_3
const matec_id WBLOCK_3("WBLOCK_3") ("WBLOCK_3") static
Referenced by melee::blocking_ability().
weapon_category_UNARMED
const weapon_category_id weapon_category_UNARMED("UNARMED") ("UNARMED") static
Referenced by wielded_weapon_categories().
WHIP_DISARM
const matec_id WHIP_DISARM("WHIP_DISARM") ("WHIP_DISARM") static
Referenced by Character::reach_attack().