Cataclysm DDA: src/memorial_logger.h File Reference
memorial_logger.h File Reference
#include <iosfwd>
#include <new>
#include <optional>
#include <vector>
#include "calendar.h"
#include "event_subscriber.h"
#include "string_formatter.h"
#include "type_id.h"
Classes
class memorial_log_entry
class memorial_logger
Namespaces
cata
Macros
#define CATA_SRC_MEMORIAL_LOGGER_H
Functions
memorial_logger & get_memorial ()
Macro Definition Documentation
CATA_SRC_MEMORIAL_LOGGER_H
#define CATA_SRC_MEMORIAL_LOGGER_H
Definition at line 3 of file memorial_logger.h.
Function Documentation
get_memorial()
memorial_logger& get_memorial ()
Definition at line 161 of file game.cpp.
 {
     return g->memorial();
 }
Referenced by timed_event::actualize(), turn_handler::cleanup_at_end(), destroyed_armor_msg(), Character::fall_asleep(), Character::forced_dismount(), mattack::fungus_fortify(), and marloss_common().