Cataclysm DDA: src/messages.h File Reference
messages.h File Reference
#include <cstddef>
#include <iosfwd>
#include <type_traits>
#include <utility>
#include <vector>
#include "debug.h"
#include "enums.h"
#include "string_formatter.h"
Namespaces
catacurses
Contains the curses interface used by the whole game.
Messages
Macros
#define CATA_SRC_MESSAGES_H
#define add_msg_debug_if(condition, type, ...)
#define add_msg_debug(type, ...) add_msg_debug_if(true, type, __VA_ARGS__)
Functions
std::vector< std::pair< std::string, std::string > > Messages::recent_messages (size_t count)
bool Messages::has_debug_filter (debugmode::debug_filter type)
void Messages::add_msg (std::string msg)
void Messages::add_msg (const game_message_params &params, std::string msg)
void Messages::clear_messages ()
void Messages::deactivate ()
size_t Messages::size ()
bool Messages::has_undisplayed_messages ()
void Messages::display_messages ()
void Messages::display_messages (const catacurses::window &ipk_target, int left, int top, int right, int bottom)
void Messages::serialize (JsonOut &json)
void Messages::deserialize (const JsonObject &json)
void add_msg (std::string msg)
template<typename ... Args>
void add_msg (const std::string &msg, Args &&... args)
template<typename ... Args>
void add_msg (const char *const msg, Args &&... args)
template<typename ... Args>
void add_msg (const translation &msg, Args &&... args)
void add_msg (const game_message_params &params, std::string msg)
template<typename ... Args>
void add_msg (const game_message_params &params, const std::string &msg, Args &&... args)
template<typename ... Args>
void add_msg (const game_message_params &params, const char *const msg, Args &&... args)
void add_msg_if_player_sees (const tripoint &target, std::string msg)
void add_msg_if_player_sees (const Creature &target, std::string msg)
template<typename ... Args>
void add_msg_if_player_sees (const tripoint &target, const std::string &msg, Args &&... args)
template<typename ... Args>
void add_msg_if_player_sees (const Creature &target, const std::string &msg, Args &&... args)
template<typename ... Args>
void add_msg_if_player_sees (const tripoint &target, const char *const msg, Args &&... args)
template<typename ... Args>
void add_msg_if_player_sees (const Creature &target, const char *const msg, Args &&... args)
template<typename ... Args>
void add_msg_if_player_sees (const tripoint &target, const translation &msg, Args &&... args)
template<typename ... Args>
void add_msg_if_player_sees (const Creature &target, const translation &msg, Args &&... args)
void add_msg_if_player_sees (const tripoint &target, const game_message_params &params, std::string msg)
void add_msg_if_player_sees (const Creature &target, const game_message_params &params, std::string msg)
template<typename ... Args>
void add_msg_if_player_sees (const tripoint &target, const game_message_params &params, const std::string &msg, Args &&... args)
template<typename ... Args>
void add_msg_if_player_sees (const Creature &target, const game_message_params &params, const std::string &msg, Args &&... args)
template<typename ... Args>
void add_msg_if_player_sees (const tripoint &target, const game_message_params &params, const char *const msg, Args &&... args)
template<typename ... Args>
void add_msg_if_player_sees (const Creature &target, const game_message_params &params, const char *const msg, Args &&... args)
template<typename T >
T && clang_tidy_no_translations (T &&t)
void modify_msg_with_exclamations (std::string &msg, game_message_type type)
Macro Definition Documentation
add_msg_debug
#define add_msg_debug (type, ...) add_msg_debug_if(true, type, __VA_ARGS__)
Definition at line 177 of file messages.h.
add_msg_debug_if
#define add_msg_debug_if (condition, type, ...)
Value:
    do {                                                                                                \
        if( debug_mode && Messages::has_debug_filter( type ) && ( condition ) ) {                       \
            Messages::add_msg( m_debug, clang_tidy_no_translations( string_format( __VA_ARGS__ ) ) );   \
        }                                                                                               \
    } while( false )
Definition at line 170 of file messages.h.
CATA_SRC_MESSAGES_H
#define CATA_SRC_MESSAGES_H
Definition at line 3 of file messages.h.
Function Documentation
add_msg() [1/7]
template<typename ... Args> void add_msg (const char *const msg, Args &&... args) inline
Definition at line 52 of file messages.h.
 {
     return add_msg( string_format( msg, std::forward<Args>( args )... ) );
 }
References add_msg(), and string_format().
add_msg() [2/7]
template<typename ... Args> void add_msg (const game_message_params & params, const char *const msg, Args &&... args) inline
Definition at line 72 of file messages.h.
 {
     if( params.type == m_debug && !debug_mode ) {
         return;
     }
     return add_msg( params, string_format( msg, std::forward<Args>( args )... ) );
 }
References add_msg(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg() [3/7]
template<typename ... Args> void add_msg (const game_message_params & params, const std::string & msg, Args &&... args) inline
Definition at line 64 of file messages.h.
 {
     if( params.type == m_debug && !debug_mode ) {
         return;
     }
     return add_msg( params, string_format( msg, std::forward<Args>( args )... ) );
 }
References add_msg(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg() [4/7]
void add_msg (const game_message_params & params, std::string msg)
Definition at line 1002 of file messages.cpp.
 {
     Messages::add_msg( params, std::move( msg ) );
 }
References Messages::add_msg().
add_msg() [5/7]
template<typename ... Args> void add_msg (const std::string & msg, Args &&... args) inline
Definition at line 47 of file messages.h.
 {
     return add_msg( string_format( msg, std::forward<Args>( args )... ) );
 }
References add_msg(), and string_format().
add_msg() [6/7]
template<typename ... Args> void add_msg (const translation & msg, Args &&... args) inline
Definition at line 57 of file messages.h.
 {
     return add_msg( string_format( msg, std::forward<Args>( args )... ) );
 }
References add_msg(), and string_format().
add_msg() [7/7]
void add_msg (std::string msg)
Definition at line 997 of file messages.cpp.
 {
     Messages::add_msg( std::move( msg ) );
 }
References Messages::add_msg().
Referenced by basecamp::abandon_camp(), mattack::absorb_meat(), achievement_attained(), achievement_failed(), mdefense::acidsplash(), npc::act_on_danger_assessment(), vehicle::act_on_map(), act_vehicle_siphon(), act_vehicle_unload_fuel(), computer_session::action_miss_disarm(), computer_session::action_miss_launch(), computer_session::action_srcf_seal(), Character::activate_bionic(), activity_on_turn_move_loot(), timed_event::actualize(), effect_type::add_apply_msg(), anonymous_namespace{monexamine.cpp}::add_armor(), anonymous_namespace{monexamine.cpp}::add_leash(), add_msg(), npc::add_msg_if_npc(), npc::add_msg_player_or_npc(), Character::add_or_drop_with_msg(), iuse::afs_translocator(), iexamine::aggie_plant(), iexamine::arcfurnace_empty(), iexamine::arcfurnace_full(), talk_function::assign_camp(), anonymous_namespace{monexamine.cpp}::attach_bag_to(), anonymous_namespace{monexamine.cpp}::attach_saddle_to(), iexamine::autoclave_empty(), iexamine::autoclave_full(), iexamine::autodoc(), vehicle::automatic_fire_turret(), iexamine::bars(), trapfunc::beartrap(), best_installer(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), Character::bionics_install_failure(), Character::bionics_uninstall_failure(), trapfunc::blade(), Character::block_hit(), trapfunc::board(), mattack::boomer(), mattack::boomer_glow(), mattack::brandish(), trapfunc::bubble(), activity_handlers::build_do_turn(), vehicle::build_electronics_menu(), vehicle::build_interact_menu(), game::butcher(), butcher_dissect_item(), activity_handlers::butcher_finish(), talk_function::buy_haircut(), talk_function::buy_shave(), cardreader_examine_actor::call(), leap_actor::call(), melee_actor::call(), iuse::call_of_tindalos(), trapfunc::caltrops(), trapfunc::caltrops_glass(), Character::can_continue_craft(), vehicle::can_enable(), avatar_action::can_fire_weapon(), iexamine::can_hack(), liquid_handler::can_handle_liquid(), cancel_auto_move(), ebooksave_activity_actor::canceled(), move_furniture_activity_actor::canceled(), iuse::capture_monster_act(), iexamine::cardreader_foodplace(), iexamine::cardreader_robofac(), cast_spell(), Character::cast_spell(), iexamine::chainfence(), debug_menu::change_spells(), debug_menu::character_edit_menu(), game::chat(), monster::check_mech_powered(), mattack::check_money_left(), game::check_safe_mode_allowed(), choose_adjacent_highlight(), choose_direction(), choose_direction_rel_ms(), iexamine::choose_fertilizer(), iuse::chop_logs(), iuse::chop_tree(), complete_construction(), Character::complete_craft(), Character::complete_disassemble(), veh_interact::complete_vehicle(), iexamine::compost_empty(), iexamine::compost_full(), vehicle::control_engines(), game::control_vehicle(), trapfunc::cot(), Character::cough(), Character::craft(), Character::craft_skill_gain(), crafting_allowed(), trapfunc::crossbow(), anonymous_namespace{monexamine.cpp}::cull(), Character::customize_appearance(), salvage_actor::cut_up(), iexamine::cvdmachine(), mattack::dance(), mattack::darkman(), Character::deactivate_bionic(), dead_plant(), Character::deal_damage(), debug_menu::debug(), debug_menu::debug_menu_game_state(), mattack::dermatik(), npc::die(), dig_tool(), iuse::directional_antenna(), iexamine::dirtmound(), vehicle::disable_smart_controller_if_needed(), avatar::disarm(), Character::disassemble(), Character::dismount(), overmap_ui::display(), game::display_scent(), trapfunc::dissector(), anonymous_namespace{iexamine.cpp}::atm_menu::do_deposit_money(), vehicle::do_engine_damage(), npc::do_npc_read(), Pickup::do_pickup(), npc::do_player_activity(), game::do_regular_action(), npc::do_reload(), veh_interact::do_remove(), veh_interact::do_repair(), vehicle::do_towing_move(), shearing_activity_actor::do_turn(), move_items_activity_actor::do_turn(), pickup_activity_actor::do_turn(), unload_loot_activity_actor::do_turn(), construct::do_turn_exhume(), anonymous_namespace{iexamine.cpp}::atm_menu::do_withdraw_money(), mattack::dogthing(), construct::done_deconstruct(), construct::done_digormine_stair(), construct::done_extract_maybe_revert_to_dirt(), construct::done_grave(), construct::done_mine_upstair(), construct::done_window_curtains(), debug_menu::draw_benchmark(), iexamine_helper::drink_nectar(), anonymous_namespace{monexamine.cpp}::dump_items(), avatar_action::eat(), eat(), avatar_action::eat_here(), eff_fun_teleglow(), iuse::ehandcuffs(), iuse::ehandcuffs_tick(), explosion_handler::emp_blast(), talk_function::end_conversation(), mattack::evolve_kill_strike(), game::exam_vehicle(), trap::examine(), game::examine(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_wants_to_talk(), computer_session::failure_damage(), construct::failure_deconstruct(), computer_session::failure_manhacks(), computer_session::failure_pump_explode(), computer_session::failure_pump_leak(), computer_session::failure_secubots(), computer_session::failure_shutdown(), construct::failure_standard(), iexamine::fertilize_plant(), activity_handlers::fertilize_plot_do_turn(), fetch_activity(), talk_function::field_harvest(), field_processor_fd_push_items(), activity_handlers::fill_liquid_do_turn(), game::find_or_make_stairs(), tent_placement_activity_actor::finish(), read_activity_actor::finish(), ebooksave_activity_actor::finish(), reload_activity_actor::finish(), disable_activity_actor::finish(), forage_activity_actor::finish(), gunmod_add_activity_actor::finish(), longsalvage_activity_actor::finish(), anonymous_namespace{iexamine.cpp}::atm_menu::finish_interaction(), heal_actor::finish_using(), fire(), avatar_action::fire_turret_manual(), avatar_action::fire_wielded_weapon(), talk_function::flee(), mattack::flesh_tendril(), game::fling_creature(), iexamine::flower_cactus(), iexamine::flower_marloss(), iexamine::flower_poppy(), foamcrete_build(), Character::forced_dismount(), game::forced_door_closing(), known_magic::forget_spell(), mattack::frag(), suffer::from_artifact_resonance(), iexamine::fswitch(), fungal_effects::fungalize(), iexamine::fungus(), mattack::fungus_big_blossom(), mattack::fungus_bristle(), mattack::fungus_corporate(), mattack::fungus_fortify(), mattack::fungus_inject(), mattack::fungus_sprout(), map::furn_set(), iexamine::fvat_empty(), iexamine::fvat_full(), iexamine::gaspump(), iuse::geiger_active(), generic_barber(), activity_handlers::generic_game_turn_handler(), liquid_handler::get_liquid_target(), anonymous_namespace{monexamine.cpp}::give_items_to(), trapfunc::glow(), talk_function::goto_location(), grab(), game::grabbed_furn_move(), game::grabbed_move(), game::grabbed_veh_move(), grenade_helper(), iuse::grenade_inc_act(), iuse::gunmod_attach(), activity_handlers::hand_crank_do_turn(), handbrake(), game::handle_action(), handle_debug_mode(), Character::handle_skill_warning(), vehicle::handle_trap(), Character::hardcoded_effects(), iexamine::harvest_plant(), npc::heal_player(), heat_item(), vehicle::honk_horn(), talk_function::hostile(), avatar::identify(), Character::impact(), game::insert_item(), talk_function::insult_combat(), game::inventory_item_menu(), inscribe_actor::item_inscription(), iexamine::keg(), iexamine::kiln_empty(), iexamine::kiln_full(), monster::knock_back_to(), game::knockback(), trapfunc::lava(), character_martial_arts::learn_current_style_CQB(), character_martial_arts::learn_style(), talk_function::leave(), iexamine::ledge(), trapfunc::ledge(), mattack::leech_spawner(), game::list_items_monsters(), iexamine::locked_object(), iexamine::locked_object_pickable(), Creature::longpull(), game::look_around(), loot(), mattack::lunge(), iuse::manage_exosuit(), monexamine::mech_hack(), monster::melee_attack(), Character::melee_attack_abstract(), avatar_action::mend(), Character::mend_item(), activity_handlers::mend_item_finish(), vehicle::merge_appliance_into_grid(), vehicle::merge_rackable_vehicle(), Creature::messaging_projectile_attack(), anonymous_namespace{monexamine.cpp}::milk_source(), mill_activate(), iexamine::mill_finalize(), Character::mod_speed_bonus(), iuse::molotov_lit(), game::mon_info_update(), anonymous_namespace{do_turn.cpp}::monmove(), talk_function::morale_chat(), talk_function::morale_chat_activity(), Character::mount_creature(), monster::move(), avatar_action::move(), monster::move_effects(), map::move_vehicle(), game::moving_vehicle_dismount(), npc::mug_player(), multi_projectile_hit_message(), multicooker_hallu(), iuse::multicooker_tick(), npc::mutiny(), iexamine::none(), spell_events::notify(), game::npc_menu(), read_activity_actor::npc_read(), mattack::nurse_assist(), mattack::nurse_check_up(), mattack::nurse_operate(), monster::nursebot_operate(), Character::on_dodge(), Character::on_hit(), Character::on_try_dodge(), open(), gates::open_gate(), iexamine::open_safe(), main_menu::opening_screen(), activity_handlers::operation_do_turn(), activity_handlers::operation_finish(), spell_effect::pain_split(), vehicle::part_collision(), iexamine::part_con(), iexamine::pay_gas(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), timed_event::per_turn(), Character::perform_install(), Character::perform_uninstall(), perform_zone_activity_turn(), game::phasing_move(), mattack::photograph(), pick_part_to_heal(), npc::pick_up_item(), pickveh(), iexamine::pit(), trapfunc::pit(), iexamine::pit_covered(), trapfunc::pit_glass(), trapfunc::pit_spikes(), place_appliance(), place_construction(), mission_start::place_npc_software(), game::place_player(), overmap::place_specials(), iuse::play_game(), basecamp::player_eats_meal(), map::player_in_field(), read_activity_actor::player_read(), read_activity_actor::player_readma(), pldrive(), avatar_action::plthrow(), iexamine::portable_structure(), vehicle::possibly_recover_from_skid(), iexamine::pour_into_keg(), vehicle::power_parts(), Character::practice(), game::debug_hour_timer::print_time(), sounds::process_sound_markers(), monster::process_turn(), process_vehicle_items(), projectile_attack(), game::prompt_dangerous_tile(), anonymous_namespace{monexamine.cpp}::push(), put_into_vehicle(), iexamine::quern_examine(), game::quicksave(), avatar_action::ramp_move(), mattack::ratking(), rcdrive(), read(), avatar::read(), game::reload(), reload_furniture(), game::reload_item(), game::reload_wielded(), vehicle::remote_controlled(), iuse::remoteveh(), anonymous_namespace{monexamine.cpp}::remove_armor(), anonymous_namespace{monexamine.cpp}::remove_bag_from(), vehicle::remove_carried_vehicle(), Creature::remove_effect(), anonymous_namespace{monexamine.cpp}::remove_harness(), anonymous_namespace{monexamine.cpp}::remove_leash(), debug_menu::mission_debug::remove_mission(), DefaultRemovePartHandler::removed(), mattack::resurrect(), mission_start::reveal_refugee_center(), reveal_route(), reveal_target(), mattack::riotbot(), Character::rooted_message(), map::rotten_item_spawn(), iuse::rpgdie(), iexamine::rubble(), inventory::rust_iron_items(), iexamine::safe(), game::save_cyborg(), npc::say(), explosion_handler::scrambler_blast(), vehicle::separate_from_grid(), effect::set_intensity(), set_item_inventory(), avatar::set_movement_mode(), anonymous_namespace{monexamine.cpp}::shear_animal(), mattack::shockstorm(), explosion_handler::shockwave(), map::shoot(), trapfunc::shotgun(), show_pickup_message(), iexamine::shrub_marloss(), iexamine::shrub_wildveggies(), trapfunc::sinkhole(), sleep(), mattack::slimespring(), game::slip_down(), game::slip_down_chance(), vehicle::smart_controller_handle_turn(), smash(), vehicle::smash_security_system(), smoker_activate(), smoker_load_food(), iexamine::smoker_options(), trapfunc::snare_heavy(), trapfunc::snare_light(), safecracking_activity_actor::start(), shearing_activity_actor::start(), vehicle::start_engine(), vehicle::start_engines(), activity_handlers::start_engines_finish(), activity_handlers::start_fire_do_turn(), anonymous_namespace{monexamine.cpp}::start_leading(), talk_function::start_mugging(), stash_on_pet(), avatar::steal(), iexamine::stook_empty(), iexamine::stook_full(), talk_function::stop_following(), talk_function::stop_guard(), Character::stop_hauling(), anonymous_namespace{monexamine.cpp}::stop_leading(), talk_function::stranger_neutral(), Creature::stumble_invis(), anonymous_namespace{monexamine.cpp}::swap(), avatar_action::swim(), takeoff(), outfit::takeoff(), activity_handlers::teach_finish(), debug_menu::teleport_long(), debug_menu::teleport_overmap(), debug_menu::teleport_short(), teleport::teleport_to_point(), trapfunc::temple_flood(), trapfunc::temple_toggle(), vehicle::thrust(), anonymous_namespace{monexamine.cpp}::tie_pet(), game::debug_hour_timer::toggle(), vehicle::toggle_autopilot(), Character::toggle_hauling(), vehicle::toggle_tracking(), iuse::toolmod_attach(), teleporter_list::translocate(), iexamine::translocator(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), iexamine::tree_marloss(), mattack::triffid_heartbeat(), trapfunc::tripwire(), avatar::try_break_relax_gas(), game::try_get_left_click_action(), game::try_get_right_click_action(), Character::try_remove_bear_trap(), Character::try_remove_grab(), Character::try_remove_heavysnare(), Character::try_remove_impeding_effect(), Character::try_remove_lightsnare(), Character::try_remove_webs(), salvage_actor::try_to_cut_up(), vehicle::turrets_aim_and_fire_all_manual(), vehicle::turrets_aim_and_fire_single(), vehicle::turrets_override_automatic_aim(), Character::uncanny_dodge(), Character::uninstall_bionic(), avatar_action::unload(), Character::unload(), anonymous_namespace{monexamine.cpp}::untie_pet(), Character::update_bodytemp(), Character::update_frostbite(), mattack::upgrade(), change_scent_iuse::use(), salvage_actor::use(), musical_instrument_actor::use(), deploy_tent_actor::use(), sew_advanced_actor::use(), learn_spell_actor::use(), Character::use(), vehicle::use_autoclave(), game::use_computer(), vehicle::use_dishwasher(), vehicle::use_harness(), heal_actor::use_healing_item(), avatar_action::use_item(), vehicle::use_washing_machine(), salvage_actor::valid_to_cut_up(), debug_menu::vehicle_battery_charge(), debug_menu::vehicle_export(), map::vehicle_vehicle_collision(), iexamine::vending(), game::vertical_move(), activity_handlers::vibe_do_turn(), activity_handlers::view_recipe_do_turn(), avatar::vomit(), wait(), avatar::wake_up(), game::walk_move(), iuse::wash_items(), wear(), weather_sound(), avatar::wield(), game::wield(), wield_before_use(), talker_npc::will_talk_to_u(), monster::witness_thievery(), iexamine::workbench_internal(), and mdefense::zapback().
add_msg_if_player_sees() [1/14]
template<typename ... Args> void add_msg_if_player_sees (const Creature & target, const char *const msg, Args &&... args) inline
Definition at line 100 of file messages.h.
 {
     return add_msg_if_player_sees( target, string_format( msg, std::forward<Args>( args )... ) );
 }
References add_msg_if_player_sees(), and string_format().
add_msg_if_player_sees() [2/14]
template<typename ... Args> void add_msg_if_player_sees (const Creature & target, const game_message_params & params, const char *const msg, Args &&... args) inline
Definition at line 152 of file messages.h.
 {
     if( params.type == m_debug && !debug_mode ) {
         return;
     }
     return add_msg_if_player_sees( target, params, string_format( msg,
                                    std::forward<Args>( args )... ) );
 }
References add_msg_if_player_sees(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_if_player_sees() [3/14]
template<typename ... Args> void add_msg_if_player_sees (const Creature & target, const game_message_params & params, const std::string & msg, Args &&... args) inline
Definition at line 132 of file messages.h.
 {
     if( params.type == m_debug && !debug_mode ) {
         return;
     }
     return add_msg_if_player_sees( target, params, string_format( msg,
                                    std::forward<Args>( args )... ) );
 }
References add_msg_if_player_sees(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_if_player_sees() [4/14]
void add_msg_if_player_sees (const Creature & target, const game_message_params & params, std::string msg)
Definition at line 1029 of file messages.cpp.
 {
     if( get_player_view().sees( target ) ) {
         Messages::add_msg( params, std::move( msg ) );
     }
 }
References Messages::add_msg(), and get_player_view().
add_msg_if_player_sees() [5/14]
template<typename ... Args> void add_msg_if_player_sees (const Creature & target, const std::string & msg, Args &&... args) inline
Definition at line 89 of file messages.h.
 {
     return add_msg_if_player_sees( target, string_format( msg, std::forward<Args>( args )... ) );
 }
References add_msg_if_player_sees(), and string_format().
add_msg_if_player_sees() [6/14]
template<typename ... Args> void add_msg_if_player_sees (const Creature & target, const translation & msg, Args &&... args) inline
Definition at line 111 of file messages.h.
 {
     return add_msg_if_player_sees( target, string_format( msg, std::forward<Args>( args )... ) );
 }
References add_msg_if_player_sees(), and string_format().
add_msg_if_player_sees() [7/14]
void add_msg_if_player_sees (const Creature & target, std::string msg)
Definition at line 1014 of file messages.cpp.
 {
     if( get_player_view().sees( target ) ) {
         Messages::add_msg( std::move( msg ) );
     }
 }
References Messages::add_msg(), and get_player_view().
add_msg_if_player_sees() [8/14]
template<typename ... Args> void add_msg_if_player_sees (const tripoint & target, const char *const msg, Args &&... args) inline
Definition at line 95 of file messages.h.
 {
     return add_msg_if_player_sees( target, string_format( msg, std::forward<Args>( args )... ) );
 }
References add_msg_if_player_sees(), and string_format().
add_msg_if_player_sees() [9/14]
template<typename ... Args> void add_msg_if_player_sees (const tripoint & target, const game_message_params & params, const char *const msg, Args &&... args) inline
Definition at line 142 of file messages.h.
 {
     if( params.type == m_debug && !debug_mode ) {
         return;
     }
     return add_msg_if_player_sees( target, params, string_format( msg,
                                    std::forward<Args>( args )... ) );
 }
References add_msg_if_player_sees(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_if_player_sees() [10/14]
template<typename ... Args> void add_msg_if_player_sees (const tripoint & target, const game_message_params & params, const std::string & msg, Args &&... args) inline
Definition at line 122 of file messages.h.
 {
     if( params.type == m_debug && !debug_mode ) {
         return;
     }
     return add_msg_if_player_sees( target, params, string_format( msg,
                                    std::forward<Args>( args )... ) );
 }
References add_msg_if_player_sees(), debug_mode, m_debug, string_format(), and game_message_params::type.
add_msg_if_player_sees() [11/14]
void add_msg_if_player_sees (const tripoint & target, const game_message_params & params, std::string msg)
Definition at line 1021 of file messages.cpp.
 {
     if( get_player_view().sees( target ) ) {
         Messages::add_msg( params, std::move( msg ) );
     }
 }
References Messages::add_msg(), and get_player_view().
add_msg_if_player_sees() [12/14]
template<typename ... Args> void add_msg_if_player_sees (const tripoint & target, const std::string & msg, Args &&... args) inline
Definition at line 83 of file messages.h.
 {
     return add_msg_if_player_sees( target, string_format( msg, std::forward<Args>( args )... ) );
 }
References add_msg_if_player_sees(), and string_format().
add_msg_if_player_sees() [13/14]
template<typename ... Args> void add_msg_if_player_sees (const tripoint & target, const translation & msg, Args &&... args) inline
Definition at line 105 of file messages.h.
 {
     return add_msg_if_player_sees( target, string_format( msg, std::forward<Args>( args )... ) );
 }
References add_msg_if_player_sees(), and string_format().
add_msg_if_player_sees() [14/14]
void add_msg_if_player_sees (const tripoint & target, std::string msg)
Definition at line 1007 of file messages.cpp.
 {
     if( get_player_view().sees( target ) ) {
         Messages::add_msg( std::move( msg ) );
     }
 }
References Messages::add_msg(), and get_player_view().
Referenced by mattack::absorb_items(), mattack::acid(), monster::add_msg_if_npc(), add_msg_if_player_sees(), monster::add_msg_player_or_npc(), npc::add_msg_player_or_npc(), weakpoint_effect::apply_to(), Creature::attack_air(), vehicle::automatic_fire_turret(), blobify(), mattack::blow_whistle(), mattack::boomer(), mattack::boomer_glow(), vehicle::break_off(), mdeath::broken(), mattack::browse(), mon_spellcasting_actor::call(), gun_actor::call(), Character::can_continue_craft(), iuse::can_goo(), ebooksave_activity_actor::canceled(), npc::check_or_use_weapon_cbm(), mattack::chickenbot(), Character::complete_craft(), Character::complete_disassemble(), Character::craft_skill_gain(), crafting_allowed(), vehicle::damage_direct(), damage_targets(), mattack::darkman(), vehicle::decrement_summon_timer(), mattack::depart(), mattack::dermatik_growth(), monster::die(), npc::die(), monster::die_if_drowning(), mdeath::disappear(), npc::do_npc_read(), hacksaw_activity_actor::do_turn(), boltcutting_activity_actor::do_turn(), shearing_activity_actor::do_turn(), oxytorch_activity_actor::do_turn(), prying_activity_actor::do_turn(), read_activity_actor::do_turn(), ebooksave_activity_actor::do_turn(), mattack::doot(), map::drop_items(), drop_or_embed_projectile(), mattack::eat_carrion(), mattack::eat_crop(), mattack::eat_food(), npc::execute_action(), fetch_activity(), field_processor_fd_push_items(), ebooksave_activity_actor::finish(), shearing_activity_actor::finish(), mattack::flame(), mattack::flamethrower(), mattack::flesh_golem(), mattack::flesh_tendril(), mattack::frag(), fungal_effects::fungalize(), iuse::fungicide(), mattack::fungus(), mattack::fungus_growth(), mattack::fungus_haze(), generic_multi_activity_check_requirement(), mattack::graze(), Character::hardcoded_effects(), npc::heal_self(), map::hit_with_acid(), vehicle::idle(), mattack::jackson(), mattack::kamikaze(), magical_polymorph(), monster::make_fungus(), mattack::mon_leech_evolution(), monster::move_to(), move_to_parent_pocket_recursive(), mattack::multi_robot(), mdeath::normal(), npc_throw(), trapfunc::pit_glass(), trapfunc::pit_spikes(), mattack::plant(), npc::pretend_fire(), npc::pretend_heal(), item::process_corpse(), monster::process_effects(), item::process_link(), monster::process_turn(), monster::push_to(), npc::reach_omt_destination(), item::reset_link(), mattack::rifle(), npc::say(), mattack::science(), map::shake_vehicle(), vehicle::shed_loose_parts(), gun_actor::shoot(), monster::shove_vehicle(), mattack::shriek_alert(), map::smash_items(), mattack::split(), fungal_effects::spread_fungus_one_tile(), safecracking_activity_actor::start(), shearing_activity_actor::start(), mattack::tankgun(), trapfunc::telepad(), mattack::tindalos_teleport(), mattack::triffid_growth(), gun_actor::try_target(), Character::uninstall_bionic(), npc::use_painkiller(), game::water_affect_items(), and mattack::zombie_fuse().
clang_tidy_no_translations()
template<typename T > T&& clang_tidy_no_translations (T && t) inline
Definition at line 165 of file messages.h.
 {
     return std::forward<T>( t );
 }
modify_msg_with_exclamations()
void modify_msg_with_exclamations (std::string & msg, game_message_type type)
Referenced by anonymous_namespace{messages.cpp}::messages_impl::add_msg_string().