Cataclysm DDA: src/mission_start.cpp File Reference
mission_start.cpp File Reference
#include "mission.h"
#include <memory>
#include <new>
#include <optional>
#include <vector>
#include "avatar.h"
#include "character.h"
#include "computer.h"
#include "coordinates.h"
#include "debug.h"
#include "enum_traits.h"
#include "game.h"
#include "game_constants.h"
#include "item.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "messages.h"
#include "npc.h"
#include "npc_class.h"
#include "omdata.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "point.h"
#include "rng.h"
#include "string_formatter.h"
#include "translations.h"
#include "units.h"
Functions
static tripoint find_potential_computer_point (const tinymap &compmap)
static void create_lab_consoles (mission *miss, const tripoint_abs_omt &place, const std::string &otype, int security, const std::string &comp_name, const std::string &download_name)
Variables
static const furn_str_id furn_f_bed ("f_bed")
static const furn_str_id furn_f_console ("f_console")
static const furn_str_id furn_f_console_broken ("f_console_broken")
static const furn_str_id furn_f_dresser ("f_dresser")
static const itype_id itype_software_hacking ("software_hacking")
static const itype_id itype_software_math ("software_math")
static const itype_id itype_software_medical ("software_medical")
static const itype_id itype_software_useless ("software_useless")
static const mission_type_id mission_MISSION_GET_ZOMBIE_BLOOD_ANAL ("MISSION_GET_ZOMBIE_BLOOD_ANAL")
static const ter_str_id ter_t_floor ("t_floor")
static const ter_str_id ter_t_wall_metal ("t_wall_metal")
Function Documentation
create_lab_consoles()
static void create_lab_consoles (mission * miss, const tripoint_abs_omt & place, const std::string & otype, int security, const std::string & comp_name, const std::string & download_name) static
Definition at line 342 of file mission_start.cpp.
 {
     // Drop four computers in nearby lab spaces so the player can stumble upon one of them.
     for( int i = 0; i < 4; ++i ) {
         tripoint_abs_omt om_place = mission_util::target_om_ter_random(
                                         otype, -1, miss, false, 4, place );
         tinymap compmap;
         compmap.load( om_place, false );
         tripoint comppoint = find_potential_computer_point( compmap );
         computer *tmpcomp = compmap.add_computer( comppoint, comp_name, security );
         tmpcomp->set_mission( miss->get_id() );
         tmpcomp->add_option( download_name, COMPACT_DOWNLOAD_SOFTWARE, security );
         tmpcomp->add_failure( COMPFAIL_ALARM );
         tmpcomp->add_failure( COMPFAIL_DAMAGE );
         tmpcomp->add_failure( COMPFAIL_MANHACKS );
         compmap.save();
     }
 }
References tinymap::add_computer(), computer::add_failure(), computer::add_option(), COMPACT_DOWNLOAD_SOFTWARE, COMPFAIL_ALARM, COMPFAIL_DAMAGE, COMPFAIL_MANHACKS, find_potential_computer_point(), mission::get_id(), tinymap::load(), tinymap::save(), computer::set_mission(), and mission_util::target_om_ter_random().
Referenced by mission_start::create_hidden_lab_console(), mission_start::create_ice_lab_console(), and mission_start::create_lab_console().
find_potential_computer_point()
static tripoint find_potential_computer_point (const tinymap & compmap) static
Definition at line 87 of file mission_start.cpp.
 {
     constexpr int rng_x_min = 10;
     constexpr int rng_x_max = SEEX * 2 - 11;
     constexpr int rng_y_min = 10;
     constexpr int rng_y_max = SEEY * 2 - 11;
     static_assert( rng_x_min <= rng_x_max && rng_y_min <= rng_y_max, "invalid randomization range" );
     std::vector<tripoint> broken;
     std::vector<tripoint> potential;
     std::vector<tripoint> last_resort;
     for( const tripoint &p : compmap.points_on_zlevel() ) {
         if( compmap.furn( p ) == furn_f_console_broken ) {
             broken.emplace_back( p );
         } else if( broken.empty() && compmap.ter( p ) == ter_t_floor &&
                    compmap.furn( p ) == furn_str_id::NULL_ID() ) {
             for( const tripoint &p2 : compmap.points_in_radius( p, 1 ) ) {
                 if( compmap.furn( p2 ) == furn_f_bed || compmap.furn( p2 ) == furn_f_dresser ) {
                     potential.emplace_back( p );
                     break;
                 }
             }
             int wall = 0;
             for( const tripoint &p2 : compmap.points_in_radius( p, 1 ) ) {
                 if( compmap.has_flag_ter( ter_furn_flag::TFLAG_WALL, p2 ) ) {
                     wall++;
                 }
             }
             if( wall == 5 ) {
                 if( compmap.is_last_ter_wall( true, p.xy(), point( SEEX * 2, SEEY * 2 ), direction::NORTH ) &&
                     compmap.is_last_ter_wall( true, p.xy(), point( SEEX * 2, SEEY * 2 ), direction::SOUTH ) &&
                     compmap.is_last_ter_wall( true, p.xy(), point( SEEX * 2, SEEY * 2 ), direction::WEST ) &&
                     compmap.is_last_ter_wall( true, p.xy(), point( SEEX * 2, SEEY * 2 ), direction::EAST ) ) {
                     potential.emplace_back( p );
                 }
             }
         } else if( broken.empty() && potential.empty() && p.x >= rng_x_min && p.x <= rng_x_max
                    && p.y >= rng_y_min && p.y <= rng_y_max && compmap.furn( p ) != furn_f_console ) {
             last_resort.emplace_back( p );
         }
     }
     std::vector<tripoint> *used = &broken;
     if( used->empty() ) {
         used = &potential;
     }
     if( used->empty() ) {
         used = &last_resort;
     }
     // if there's no possible location, then we have to overwrite an existing console...
     const tripoint fallback( rng( rng_x_min, rng_x_max ), rng( rng_y_min, rng_y_max ),
                              compmap.get_abs_sub().z() );
     return random_entry( *used, fallback );
 }
References broken, EAST, tinymap::furn(), furn_f_bed, furn_f_console, furn_f_console_broken, furn_f_dresser, tinymap::get_abs_sub(), tinymap::has_flag_ter(), tinymap::is_last_ter_wall(), NORTH, string_id< furn_t >::NULL_ID(), tinymap::points_in_radius(), tinymap::points_on_zlevel(), random_entry(), rng(), SEEX, SEEY, SOUTH, tinymap::ter(), ter_t_floor, TFLAG_WALL, WEST, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by create_lab_consoles(), and mission_start::place_npc_software().
Variable Documentation
furn_f_bed
const furn_str_id furn_f_bed("f_bed") ("f_bed") static
Referenced by find_potential_computer_point().
furn_f_console
const furn_str_id furn_f_console("f_console") ("f_console") static
Referenced by find_potential_computer_point(), and mission_start::place_npc_software().
furn_f_console_broken
const furn_str_id furn_f_console_broken("f_console_broken") ("f_console_broken") static
Referenced by find_potential_computer_point().
furn_f_dresser
const furn_str_id furn_f_dresser("f_dresser") ("f_dresser") static
Referenced by find_potential_computer_point().
itype_software_hacking
const itype_id itype_software_hacking("software_hacking") ("software_hacking") static
Referenced by mission_start::place_npc_software().
itype_software_math
const itype_id itype_software_math("software_math") ("software_math") static
Referenced by mission_start::place_npc_software().
itype_software_medical
const itype_id itype_software_medical("software_medical") ("software_medical") static
Referenced by mission_start::place_npc_software().
itype_software_useless
const itype_id itype_software_useless("software_useless") ("software_useless") static
Referenced by mission_start::place_npc_software().
mission_MISSION_GET_ZOMBIE_BLOOD_ANAL
const mission_type_id mission_MISSION_GET_ZOMBIE_BLOOD_ANAL("MISSION_GET_ZOMBIE_BLOOD_ANAL") ("MISSION_GET_ZOMBIE_BLOOD_ANAL") static
Referenced by mission_start::place_npc_software().
ter_t_floor
const ter_str_id ter_t_floor("t_floor") ("t_floor") static
Referenced by find_potential_computer_point(), and mission_start::place_deposit_box().
ter_t_wall_metal
const ter_str_id ter_t_wall_metal("t_wall_metal") ("t_wall_metal") static
Referenced by mission_start::place_deposit_box().