Cataclysm DDA: src/missiondef.cpp File Reference
missiondef.cpp File Reference
#include "mission.h"
#include <algorithm>
#include <cstdlib>
#include <set>
#include "assign.h"
#include "calendar.h"
#include "condition.h"
#include "debug.h"
#include "enum_conversions.h"
#include "generic_factory.h"
#include "init.h"
#include "item.h"
#include "json.h"
#include "npc.h"
#include "rng.h"
Namespaces
io
Enumerations
enum legacy_mission_type_id {
MISSION_NULL , MISSION_GET_ANTIBIOTICS , MISSION_GET_SOFTWARE , MISSION_GET_ZOMBIE_BLOOD_ANAL ,
MISSION_RESCUE_DOG , MISSION_KILL_ZOMBIE_MOM , MISSION_REACH_SAFETY , MISSION_GET_FLAG ,
MISSION_GET_BLACK_BOX , MISSION_GET_BLACK_BOX_TRANSCRIPT , MISSION_EXPLORE_SARCOPHAGUS , MISSION_GET_RELIC ,
MISSION_RECOVER_PRIEST_DIARY , MISSION_INVESTIGATE_CULT , MISSION_INVESTIGATE_PRISON_VISIONARY , MISSION_GET_RECORD_WEATHER ,
MISSION_GET_RECORD_PATIENT , MISSION_REACH_FEMA_CAMP , MISSION_REACH_FARM_HOUSE , MISSION_GET_RECORD_ACCOUNTING ,
MISSION_GET_SAFE_BOX , MISSION_GET_DEPUTY_BADGE , MISSION_KILL_JABBERWOCK , MISSION_KILL_100_Z ,
MISSION_KILL_HORDE_MASTER , MISSION_RECRUIT_TRACKER , MISSION_JOIN_TRACKER , MISSION_FREE_MERCHANTS_EVAC_1 ,
MISSION_FREE_MERCHANTS_EVAC_2 , MISSION_FREE_MERCHANTS_EVAC_4 , MISSION_OLD_GUARD_REP_1 , MISSION_OLD_GUARD_REP_2 ,
MISSION_OLD_GUARD_REP_3 , MISSION_OLD_GUARD_REP_4 , MISSION_OLD_GUARD_NEC_1 , MISSION_OLD_GUARD_NEC_2 ,
MISSION_OLD_GUARD_NEC_COMMO_1 , MISSION_OLD_GUARD_NEC_COMMO_2 , MISSION_OLD_GUARD_NEC_COMMO_3 , MISSION_OLD_GUARD_NEC_COMMO_4 ,
MISSION_RANCH_FOREMAN_1 , MISSION_RANCH_FOREMAN_2 , MISSION_RANCH_FOREMAN_3 , MISSION_RANCH_FOREMAN_4 ,
MISSION_RANCH_FOREMAN_5 , MISSION_RANCH_FOREMAN_6 , MISSION_RANCH_FOREMAN_7 , MISSION_RANCH_FOREMAN_8 ,
MISSION_RANCH_FOREMAN_9 , MISSION_RANCH_FOREMAN_10 , MISSION_RANCH_FOREMAN_11 , MISSION_RANCH_FOREMAN_12 ,
MISSION_RANCH_FOREMAN_13 , MISSION_RANCH_FOREMAN_14 , MISSION_RANCH_FOREMAN_15 , MISSION_RANCH_FOREMAN_16 ,
MISSION_RANCH_FOREMAN_17 , MISSION_RANCH_NURSE_1 , MISSION_RANCH_NURSE_2 , MISSION_RANCH_NURSE_3 ,
MISSION_RANCH_NURSE_4 , MISSION_RANCH_NURSE_5 , MISSION_RANCH_NURSE_6 , MISSION_RANCH_NURSE_7 ,
MISSION_RANCH_NURSE_8 , MISSION_RANCH_NURSE_9 , MISSION_RANCH_NURSE_10 , MISSION_RANCH_NURSE_11 ,
MISSION_RANCH_SCAVENGER_1 , MISSION_RANCH_SCAVENGER_2 , MISSION_RANCH_SCAVENGER_3 , MISSION_RANCH_SCAVENGER_4 ,
MISSION_RANCH_BARTENDER_1 , MISSION_RANCH_BARTENDER_2 , MISSION_RANCH_BARTENDER_3 , MISSION_RANCH_BARTENDER_4 ,
MISSION_RANCH_BARTENDER_5 , MISSION_FREE_MERCHANTS_EVAC_3 , NUM_MISSION_IDS
}
Functions
template<>
std::string io::enum_to_string< mission_origin > (mission_origin data)
template<>
std::string io::enum_to_string< mission_goal > (mission_goal data)
template<typename Fun >
void assign_function (const JsonObject &jo, const std::string &id, Fun &target, const std::map< std::string, Fun > &cont)
Variables
static const mission_type_id mission_MISSION_EXPLORE_SARCOPHAGUS ("MISSION_EXPLORE_SARCOPHAGUS")
static const mission_type_id mission_MISSION_FREE_MERCHANTS_EVAC_1 ("MISSION_FREE_MERCHANTS_EVAC_1")
static const mission_type_id mission_MISSION_FREE_MERCHANTS_EVAC_2 ("MISSION_FREE_MERCHANTS_EVAC_2")
static const mission_type_id mission_MISSION_FREE_MERCHANTS_EVAC_3 ("MISSION_FREE_MERCHANTS_EVAC_3")
static const mission_type_id mission_MISSION_FREE_MERCHANTS_EVAC_4 ("MISSION_FREE_MERCHANTS_EVAC_4")
static const mission_type_id mission_MISSION_GET_ANTIBIOTICS ("MISSION_GET_ANTIBIOTICS")
static const mission_type_id mission_MISSION_GET_BLACK_BOX ("MISSION_GET_BLACK_BOX")
static const mission_type_id mission_MISSION_GET_BLACK_BOX_TRANSCRIPT ("MISSION_GET_BLACK_BOX_TRANSCRIPT")
static const mission_type_id mission_MISSION_GET_DEPUTY_BADGE ("MISSION_GET_DEPUTY_BADGE")
static const mission_type_id mission_MISSION_GET_FLAG ("MISSION_GET_FLAG")
static const mission_type_id mission_MISSION_GET_RECORD_ACCOUNTING ("MISSION_GET_RECORD_ACCOUNTING")
static const mission_type_id mission_MISSION_GET_RECORD_PATIENT ("MISSION_GET_RECORD_PATIENT")
static const mission_type_id mission_MISSION_GET_RECORD_WEATHER ("MISSION_GET_RECORD_WEATHER")
static const mission_type_id mission_MISSION_GET_RELIC ("MISSION_GET_RELIC")
static const mission_type_id mission_MISSION_GET_SAFE_BOX ("MISSION_GET_SAFE_BOX")
static const mission_type_id mission_MISSION_GET_SOFTWARE ("MISSION_GET_SOFTWARE")
static const mission_type_id mission_MISSION_GET_ZOMBIE_BLOOD_ANAL ("MISSION_GET_ZOMBIE_BLOOD_ANAL")
static const mission_type_id mission_MISSION_INVESTIGATE_CULT ("MISSION_INVESTIGATE_CULT")
static const mission_type_id mission_MISSION_INVESTIGATE_PRISON_VISIONARY ("MISSION_INVESTIGATE_PRISON_VISIONARY")
static const mission_type_id mission_MISSION_JOIN_TRACKER ("MISSION_JOIN_TRACKER")
static const mission_type_id mission_MISSION_KILL_100_Z ("MISSION_KILL_100_Z")
static const mission_type_id mission_MISSION_KILL_HORDE_MASTER ("MISSION_KILL_HORDE_MASTER")
static const mission_type_id mission_MISSION_KILL_JABBERWOCK ("MISSION_KILL_JABBERWOCK")
static const mission_type_id mission_MISSION_KILL_NEMESIS ("MISSION_KILL_NEMESIS")
static const mission_type_id mission_MISSION_KILL_ZOMBIE_MOM ("MISSION_KILL_ZOMBIE_MOM")
static const mission_type_id mission_MISSION_NULL ("MISSION_NULL")
static const mission_type_id mission_MISSION_OLD_GUARD_NEC_1 ("MISSION_OLD_GUARD_NEC_1")
static const mission_type_id mission_MISSION_OLD_GUARD_NEC_2 ("MISSION_OLD_GUARD_NEC_2")
static const mission_type_id mission_MISSION_OLD_GUARD_NEC_COMMO_1 ("MISSION_OLD_GUARD_NEC_COMMO_1")
static const mission_type_id mission_MISSION_OLD_GUARD_NEC_COMMO_2 ("MISSION_OLD_GUARD_NEC_COMMO_2")
static const mission_type_id mission_MISSION_OLD_GUARD_NEC_COMMO_3 ("MISSION_OLD_GUARD_NEC_COMMO_3")
static const mission_type_id mission_MISSION_OLD_GUARD_NEC_COMMO_4 ("MISSION_OLD_GUARD_NEC_COMMO_4")
static const mission_type_id mission_MISSION_OLD_GUARD_REP_1 ("MISSION_OLD_GUARD_REP_1")
static const mission_type_id mission_MISSION_OLD_GUARD_REP_2 ("MISSION_OLD_GUARD_REP_2")
static const mission_type_id mission_MISSION_OLD_GUARD_REP_3 ("MISSION_OLD_GUARD_REP_3")
static const mission_type_id mission_MISSION_OLD_GUARD_REP_4 ("MISSION_OLD_GUARD_REP_4")
static const mission_type_id mission_MISSION_RANCH_BARTENDER_1 ("MISSION_RANCH_BARTENDER_1")
static const mission_type_id mission_MISSION_RANCH_BARTENDER_2 ("MISSION_RANCH_BARTENDER_2")
static const mission_type_id mission_MISSION_RANCH_BARTENDER_3 ("MISSION_RANCH_BARTENDER_3")
static const mission_type_id mission_MISSION_RANCH_BARTENDER_4 ("MISSION_RANCH_BARTENDER_4")
static const mission_type_id mission_MISSION_RANCH_BARTENDER_5 ("MISSION_RANCH_BARTENDER_5")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_1 ("MISSION_RANCH_FOREMAN_1")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_10 ("MISSION_RANCH_FOREMAN_10")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_11 ("MISSION_RANCH_FOREMAN_11")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_12 ("MISSION_RANCH_FOREMAN_12")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_13 ("MISSION_RANCH_FOREMAN_13")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_14 ("MISSION_RANCH_FOREMAN_14")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_15 ("MISSION_RANCH_FOREMAN_15")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_16 ("MISSION_RANCH_FOREMAN_16")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_17 ("MISSION_RANCH_FOREMAN_17")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_2 ("MISSION_RANCH_FOREMAN_2")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_3 ("MISSION_RANCH_FOREMAN_3")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_4 ("MISSION_RANCH_FOREMAN_4")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_5 ("MISSION_RANCH_FOREMAN_5")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_6 ("MISSION_RANCH_FOREMAN_6")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_7 ("MISSION_RANCH_FOREMAN_7")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_8 ("MISSION_RANCH_FOREMAN_8")
static const mission_type_id mission_MISSION_RANCH_FOREMAN_9 ("MISSION_RANCH_FOREMAN_9")
static const mission_type_id mission_MISSION_RANCH_NURSE_1 ("MISSION_RANCH_NURSE_1")
static const mission_type_id mission_MISSION_RANCH_NURSE_10 ("MISSION_RANCH_NURSE_10")
static const mission_type_id mission_MISSION_RANCH_NURSE_11 ("MISSION_RANCH_NURSE_11")
static const mission_type_id mission_MISSION_RANCH_NURSE_2 ("MISSION_RANCH_NURSE_2")
static const mission_type_id mission_MISSION_RANCH_NURSE_3 ("MISSION_RANCH_NURSE_3")
static const mission_type_id mission_MISSION_RANCH_NURSE_4 ("MISSION_RANCH_NURSE_4")
static const mission_type_id mission_MISSION_RANCH_NURSE_5 ("MISSION_RANCH_NURSE_5")
static const mission_type_id mission_MISSION_RANCH_NURSE_6 ("MISSION_RANCH_NURSE_6")
static const mission_type_id mission_MISSION_RANCH_NURSE_7 ("MISSION_RANCH_NURSE_7")
static const mission_type_id mission_MISSION_RANCH_NURSE_8 ("MISSION_RANCH_NURSE_8")
static const mission_type_id mission_MISSION_RANCH_NURSE_9 ("MISSION_RANCH_NURSE_9")
static const mission_type_id mission_MISSION_RANCH_SCAVENGER_1 ("MISSION_RANCH_SCAVENGER_1")
static const mission_type_id mission_MISSION_RANCH_SCAVENGER_2 ("MISSION_RANCH_SCAVENGER_2")
static const mission_type_id mission_MISSION_RANCH_SCAVENGER_3 ("MISSION_RANCH_SCAVENGER_3")
static const mission_type_id mission_MISSION_RANCH_SCAVENGER_4 ("MISSION_RANCH_SCAVENGER_4")
static const mission_type_id mission_MISSION_REACH_FARM_HOUSE ("MISSION_REACH_FARM_HOUSE")
static const mission_type_id mission_MISSION_REACH_FEMA_CAMP ("MISSION_REACH_FEMA_CAMP")
static const mission_type_id mission_MISSION_REACH_SAFETY ("MISSION_REACH_SAFETY")
static const mission_type_id mission_MISSION_RECOVER_PRIEST_DIARY ("MISSION_RECOVER_PRIEST_DIARY")
static const mission_type_id mission_MISSION_RECRUIT_TRACKER ("MISSION_RECRUIT_TRACKER")
static const mission_type_id mission_MISSION_RESCUE_DOG ("MISSION_RESCUE_DOG")
static const std::map< std::string, std::function< void(mission *)> > mission_function_map
static const std::map< std::string, std::function< bool(const tripoint_abs_omt &)> > tripoint_function_map
static generic_factory< mission_type > mission_type_factory ("mission_type")
static DynamicDataLoader::deferred_json deferred
Enumeration Type Documentation
legacy_mission_type_id
enum legacy_mission_type_id
Enumerator
MISSION_NULL
MISSION_GET_ANTIBIOTICS
MISSION_GET_SOFTWARE
MISSION_GET_ZOMBIE_BLOOD_ANAL
MISSION_RESCUE_DOG
MISSION_KILL_ZOMBIE_MOM
MISSION_REACH_SAFETY
MISSION_GET_FLAG
MISSION_GET_BLACK_BOX
MISSION_GET_BLACK_BOX_TRANSCRIPT
MISSION_EXPLORE_SARCOPHAGUS
MISSION_GET_RELIC
MISSION_RECOVER_PRIEST_DIARY
MISSION_INVESTIGATE_CULT
MISSION_INVESTIGATE_PRISON_VISIONARY
MISSION_GET_RECORD_WEATHER
MISSION_GET_RECORD_PATIENT
MISSION_REACH_FEMA_CAMP
MISSION_REACH_FARM_HOUSE
MISSION_GET_RECORD_ACCOUNTING
MISSION_GET_SAFE_BOX
MISSION_GET_DEPUTY_BADGE
MISSION_KILL_JABBERWOCK
MISSION_KILL_100_Z
MISSION_KILL_HORDE_MASTER
MISSION_RECRUIT_TRACKER
MISSION_JOIN_TRACKER
MISSION_FREE_MERCHANTS_EVAC_1
MISSION_FREE_MERCHANTS_EVAC_2
MISSION_FREE_MERCHANTS_EVAC_4
MISSION_OLD_GUARD_REP_1
MISSION_OLD_GUARD_REP_2
MISSION_OLD_GUARD_REP_3
MISSION_OLD_GUARD_REP_4
MISSION_OLD_GUARD_NEC_1
MISSION_OLD_GUARD_NEC_2
MISSION_OLD_GUARD_NEC_COMMO_1
MISSION_OLD_GUARD_NEC_COMMO_2
MISSION_OLD_GUARD_NEC_COMMO_3
MISSION_OLD_GUARD_NEC_COMMO_4
MISSION_RANCH_FOREMAN_1
MISSION_RANCH_FOREMAN_2
MISSION_RANCH_FOREMAN_3
MISSION_RANCH_FOREMAN_4
MISSION_RANCH_FOREMAN_5
MISSION_RANCH_FOREMAN_6
MISSION_RANCH_FOREMAN_7
MISSION_RANCH_FOREMAN_8
MISSION_RANCH_FOREMAN_9
MISSION_RANCH_FOREMAN_10
MISSION_RANCH_FOREMAN_11
MISSION_RANCH_FOREMAN_12
MISSION_RANCH_FOREMAN_13
MISSION_RANCH_FOREMAN_14
MISSION_RANCH_FOREMAN_15
MISSION_RANCH_FOREMAN_16
MISSION_RANCH_FOREMAN_17
MISSION_RANCH_NURSE_1
MISSION_RANCH_NURSE_2
MISSION_RANCH_NURSE_3
MISSION_RANCH_NURSE_4
MISSION_RANCH_NURSE_5
MISSION_RANCH_NURSE_6
MISSION_RANCH_NURSE_7
MISSION_RANCH_NURSE_8
MISSION_RANCH_NURSE_9
MISSION_RANCH_NURSE_10
MISSION_RANCH_NURSE_11
MISSION_RANCH_SCAVENGER_1
MISSION_RANCH_SCAVENGER_2
MISSION_RANCH_SCAVENGER_3
MISSION_RANCH_SCAVENGER_4
MISSION_RANCH_BARTENDER_1
MISSION_RANCH_BARTENDER_2
MISSION_RANCH_BARTENDER_3
MISSION_RANCH_BARTENDER_4
MISSION_RANCH_BARTENDER_5
MISSION_FREE_MERCHANTS_EVAC_3
NUM_MISSION_IDS
Definition at line 111 of file missiondef.cpp.
{
     MISSION_NULL,
     MISSION_GET_ANTIBIOTICS,
     MISSION_GET_SOFTWARE,
     MISSION_GET_ZOMBIE_BLOOD_ANAL,
     MISSION_RESCUE_DOG,
     MISSION_KILL_ZOMBIE_MOM,
     MISSION_REACH_SAFETY,
     MISSION_GET_FLAG,                      //patriot 1
     MISSION_GET_BLACK_BOX,                 //patriot 2
     MISSION_GET_BLACK_BOX_TRANSCRIPT,      //patriot 3
     MISSION_EXPLORE_SARCOPHAGUS,           //patriot 4
     MISSION_GET_RELIC,                     //martyr 1
     MISSION_RECOVER_PRIEST_DIARY,          //martyr 2
     MISSION_INVESTIGATE_CULT,              //martyr 3
     MISSION_INVESTIGATE_PRISON_VISIONARY,  //martyr 4
     MISSION_GET_RECORD_WEATHER,            //scientist 1
     MISSION_GET_RECORD_PATIENT,            //humanitarian 1
     MISSION_REACH_FEMA_CAMP,               //humanitarian 2
     MISSION_REACH_FARM_HOUSE,              //humanitarian 3
     MISSION_GET_RECORD_ACCOUNTING,         //vigilante 1
     MISSION_GET_SAFE_BOX,                  //vigilante 2
     MISSION_GET_DEPUTY_BADGE,              //vigilante 3
     MISSION_KILL_JABBERWOCK,               //demon slayer 1
     MISSION_KILL_100_Z,                    //demon slayer 2
     MISSION_KILL_HORDE_MASTER,             //demon slayer 3
     MISSION_RECRUIT_TRACKER,               //demon slayer 4
     MISSION_JOIN_TRACKER,                  //demon slayer 4b
     MISSION_FREE_MERCHANTS_EVAC_1,         //Clear Back Bay
     MISSION_FREE_MERCHANTS_EVAC_2,         //Kill Raiders
     MISSION_FREE_MERCHANTS_EVAC_4,         //Acquire Plutonium Cells
     MISSION_OLD_GUARD_REP_1,               //Bandit Pair
     MISSION_OLD_GUARD_REP_2,               //Raider Informant
     MISSION_OLD_GUARD_REP_3,               //Missing without a trace
     MISSION_OLD_GUARD_REP_4,               //Raider Camp
     MISSION_OLD_GUARD_NEC_1,               //Locate Commo team for Necropolis Commander
     MISSION_OLD_GUARD_NEC_2,               //Cull Nightmares
     MISSION_OLD_GUARD_NEC_COMMO_1,         //Build a radio repeater mod
     MISSION_OLD_GUARD_NEC_COMMO_2,         //Disable external power connection
     MISSION_OLD_GUARD_NEC_COMMO_3,         //Install repeater mod in local radio station
     MISSION_OLD_GUARD_NEC_COMMO_4,         //Cyclical mission to install repeater mods
     MISSION_RANCH_FOREMAN_1,               //Rebuild civilization one 2x4 at a time
     MISSION_RANCH_FOREMAN_2,               //Beds need blankets to make
     MISSION_RANCH_FOREMAN_3,               //You can never have enough nails!
     MISSION_RANCH_FOREMAN_4,               //Need salt to trade for seed
     MISSION_RANCH_FOREMAN_5,               //Need liquid fertilizer
     MISSION_RANCH_FOREMAN_6,               //Need stone for well and fireplaces
     MISSION_RANCH_FOREMAN_7,               //Need pipes to finish well and parts for lumberyard
     MISSION_RANCH_FOREMAN_8,               //Need motors to finish sawmill
     MISSION_RANCH_FOREMAN_9,               //Need bleach to sterilize for clinic
     MISSION_RANCH_FOREMAN_10,              //Need first aid kits for clinic
     MISSION_RANCH_FOREMAN_11,              //Need welders for chop-shop
     MISSION_RANCH_FOREMAN_12,              //Need car batteries to power equipment
     MISSION_RANCH_FOREMAN_13,              //Need pair of two-way radios for scavengers
     MISSION_RANCH_FOREMAN_14,              //Need 5 backpacks for scavengers
     MISSION_RANCH_FOREMAN_15,              //Need Homebrewer's Bible for Bar
     MISSION_RANCH_FOREMAN_16,              //Need Sugar for Bar
     MISSION_RANCH_FOREMAN_17,              //Need glass sheets for 1st greenhouse
     MISSION_RANCH_NURSE_1,                 //Need aspirin
     MISSION_RANCH_NURSE_2,                 //Need hotplates
     MISSION_RANCH_NURSE_3,                 //Need multivitamins
     MISSION_RANCH_NURSE_4,                 //Need charcoal water filters
     MISSION_RANCH_NURSE_5,                 //Need chemistry set
     MISSION_RANCH_NURSE_6,                 //Need filter masks
     MISSION_RANCH_NURSE_7,                 //Need rubber gloves
     MISSION_RANCH_NURSE_8,                 //Need X-Acto
     MISSION_RANCH_NURSE_9,                 //Need Guide to Advanced Emergency Care
     MISSION_RANCH_NURSE_10,                //Need flu shot
     MISSION_RANCH_NURSE_11,                //Need empty syringes
     MISSION_RANCH_SCAVENGER_1,             //Need knife spears
     MISSION_RANCH_SCAVENGER_2,             //Need wearable flashlights
     MISSION_RANCH_SCAVENGER_3,             //Need leather body armor
     MISSION_RANCH_SCAVENGER_4,             //Need Molotov cocktails
     MISSION_RANCH_BARTENDER_1,             //Need Stills
     MISSION_RANCH_BARTENDER_2,             //Need Yeast
     MISSION_RANCH_BARTENDER_3,             //Need Sugar Beet Seeds
     MISSION_RANCH_BARTENDER_4,             //Need Metal Tanks
     MISSION_RANCH_BARTENDER_5,             //Need 55-Gallon Drums
     MISSION_FREE_MERCHANTS_EVAC_3,         //Info from Commune
     NUM_MISSION_IDS
 };
Function Documentation
assign_function()
template<typename Fun > void assign_function (const JsonObject & jo, const std::string & id, Fun & target, const std::map< std::string, Fun > & cont)
Definition at line 303 of file missiondef.cpp.
 {
     if( jo.has_string( id ) ) {
         const auto iter = cont.find( jo.get_string( id ) );
         if( iter != cont.end() ) {
             target = iter->second;
         } else {
             jo.throw_error_at( id, "Invalid mission function" );
         }
     }
 }
References JsonObject::get_string(), JsonObject::has_string(), and JsonObject::throw_error_at().
Referenced by mission_type::load().
Variable Documentation
deferred
DynamicDataLoader::deferred_json deferred static
Definition at line 291 of file missiondef.cpp.
Referenced by mission_type::finalize(), mission_type::load(), and mission_type::reset().
mission_function_map
const std::map<std::string, std::function<void(mission *)> > mission_function_map static
Initial value:
= {{
        { "standard", { } },
        { "kill_nemesis", mission_start::kill_nemesis },
        { "place_npc_software", mission_start::place_npc_software },
        { "place_deposit_box", mission_start::place_deposit_box },
        { "find_safety", mission_start::find_safety },
        { "place_book", mission_start::place_book },
        { "reveal_refugee_center", mission_start::reveal_refugee_center },
        { "create_lab_console", mission_start::create_lab_console },
        { "create_hidden_lab_console", mission_start::create_hidden_lab_console },
        { "create_ice_lab_console", mission_start::create_ice_lab_console },
    }
}
Definition at line 193 of file missiondef.cpp.
Referenced by mission_type::load().
mission_MISSION_EXPLORE_SARCOPHAGUS
const mission_type_id mission_MISSION_EXPLORE_SARCOPHAGUS("MISSION_EXPLORE_SARCOPHAGUS") ("MISSION_EXPLORE_SARCOPHAGUS") static
Referenced by mission_type::from_legacy().
mission_MISSION_FREE_MERCHANTS_EVAC_1
const mission_type_id mission_MISSION_FREE_MERCHANTS_EVAC_1("MISSION_FREE_MERCHANTS_EVAC_1") ("MISSION_FREE_MERCHANTS_EVAC_1") static
Referenced by mission_type::from_legacy().
mission_MISSION_FREE_MERCHANTS_EVAC_2
const mission_type_id mission_MISSION_FREE_MERCHANTS_EVAC_2("MISSION_FREE_MERCHANTS_EVAC_2") ("MISSION_FREE_MERCHANTS_EVAC_2") static
Referenced by mission_type::from_legacy().
mission_MISSION_FREE_MERCHANTS_EVAC_3
const mission_type_id mission_MISSION_FREE_MERCHANTS_EVAC_3("MISSION_FREE_MERCHANTS_EVAC_3") ("MISSION_FREE_MERCHANTS_EVAC_3") static
Referenced by mission_type::from_legacy().
mission_MISSION_FREE_MERCHANTS_EVAC_4
const mission_type_id mission_MISSION_FREE_MERCHANTS_EVAC_4("MISSION_FREE_MERCHANTS_EVAC_4") ("MISSION_FREE_MERCHANTS_EVAC_4") static
Referenced by mission_type::from_legacy().
mission_MISSION_GET_ANTIBIOTICS
const mission_type_id mission_MISSION_GET_ANTIBIOTICS("MISSION_GET_ANTIBIOTICS") ("MISSION_GET_ANTIBIOTICS") static
Referenced by mission_type::from_legacy().
mission_MISSION_GET_BLACK_BOX
const mission_type_id mission_MISSION_GET_BLACK_BOX("MISSION_GET_BLACK_BOX") ("MISSION_GET_BLACK_BOX") static
Referenced by mission_type::from_legacy().
mission_MISSION_GET_BLACK_BOX_TRANSCRIPT
const mission_type_id mission_MISSION_GET_BLACK_BOX_TRANSCRIPT("MISSION_GET_BLACK_BOX_TRANSCRIPT") ("MISSION_GET_BLACK_BOX_TRANSCRIPT") static
Referenced by mission_type::from_legacy().
mission_MISSION_GET_DEPUTY_BADGE
const mission_type_id mission_MISSION_GET_DEPUTY_BADGE("MISSION_GET_DEPUTY_BADGE") ("MISSION_GET_DEPUTY_BADGE") static
Referenced by mission_type::from_legacy().
mission_MISSION_GET_FLAG
const mission_type_id mission_MISSION_GET_FLAG("MISSION_GET_FLAG") ("MISSION_GET_FLAG") static
Referenced by mission_type::from_legacy().
mission_MISSION_GET_RECORD_ACCOUNTING
const mission_type_id mission_MISSION_GET_RECORD_ACCOUNTING("MISSION_GET_RECORD_ACCOUNTING") ("MISSION_GET_RECORD_ACCOUNTING") static
Referenced by mission_type::from_legacy().
mission_MISSION_GET_RECORD_PATIENT
const mission_type_id mission_MISSION_GET_RECORD_PATIENT("MISSION_GET_RECORD_PATIENT") ("MISSION_GET_RECORD_PATIENT") static
Referenced by mission_type::from_legacy().
mission_MISSION_GET_RECORD_WEATHER
const mission_type_id mission_MISSION_GET_RECORD_WEATHER("MISSION_GET_RECORD_WEATHER") ("MISSION_GET_RECORD_WEATHER") static
Referenced by mission_type::from_legacy().
mission_MISSION_GET_RELIC
const mission_type_id mission_MISSION_GET_RELIC("MISSION_GET_RELIC") ("MISSION_GET_RELIC") static
Referenced by mission_type::from_legacy().
mission_MISSION_GET_SAFE_BOX
const mission_type_id mission_MISSION_GET_SAFE_BOX("MISSION_GET_SAFE_BOX") ("MISSION_GET_SAFE_BOX") static
Referenced by mission_type::from_legacy().
mission_MISSION_GET_SOFTWARE
const mission_type_id mission_MISSION_GET_SOFTWARE("MISSION_GET_SOFTWARE") ("MISSION_GET_SOFTWARE") static
Referenced by mission_type::from_legacy().
mission_MISSION_GET_ZOMBIE_BLOOD_ANAL
const mission_type_id mission_MISSION_GET_ZOMBIE_BLOOD_ANAL("MISSION_GET_ZOMBIE_BLOOD_ANAL") ("MISSION_GET_ZOMBIE_BLOOD_ANAL") static
Referenced by mission_type::from_legacy().
mission_MISSION_INVESTIGATE_CULT
const mission_type_id mission_MISSION_INVESTIGATE_CULT("MISSION_INVESTIGATE_CULT") ("MISSION_INVESTIGATE_CULT") static
Referenced by mission_type::from_legacy().
mission_MISSION_INVESTIGATE_PRISON_VISIONARY
const mission_type_id mission_MISSION_INVESTIGATE_PRISON_VISIONARY("MISSION_INVESTIGATE_PRISON_VISIONARY") ("MISSION_INVESTIGATE_PRISON_VISIONARY") static
Referenced by mission_type::from_legacy().
mission_MISSION_JOIN_TRACKER
const mission_type_id mission_MISSION_JOIN_TRACKER("MISSION_JOIN_TRACKER") ("MISSION_JOIN_TRACKER") static
Referenced by mission_type::from_legacy().
mission_MISSION_KILL_100_Z
const mission_type_id mission_MISSION_KILL_100_Z("MISSION_KILL_100_Z") ("MISSION_KILL_100_Z") static
Referenced by mission_type::from_legacy().
mission_MISSION_KILL_HORDE_MASTER
const mission_type_id mission_MISSION_KILL_HORDE_MASTER("MISSION_KILL_HORDE_MASTER") ("MISSION_KILL_HORDE_MASTER") static
Referenced by mission_type::from_legacy().
mission_MISSION_KILL_JABBERWOCK
const mission_type_id mission_MISSION_KILL_JABBERWOCK("MISSION_KILL_JABBERWOCK") ("MISSION_KILL_JABBERWOCK") static
Referenced by mission_type::from_legacy().
mission_MISSION_KILL_NEMESIS
const mission_type_id mission_MISSION_KILL_NEMESIS("MISSION_KILL_NEMESIS") ("MISSION_KILL_NEMESIS") static
Referenced by mission_type::from_legacy().
mission_MISSION_KILL_ZOMBIE_MOM
const mission_type_id mission_MISSION_KILL_ZOMBIE_MOM("MISSION_KILL_ZOMBIE_MOM") ("MISSION_KILL_ZOMBIE_MOM") static
Referenced by mission_type::from_legacy().
mission_MISSION_NULL
const mission_type_id mission_MISSION_NULL("MISSION_NULL") ("MISSION_NULL") static
Referenced by mission_type::from_legacy().
mission_MISSION_OLD_GUARD_NEC_1
const mission_type_id mission_MISSION_OLD_GUARD_NEC_1("MISSION_OLD_GUARD_NEC_1") ("MISSION_OLD_GUARD_NEC_1") static
Referenced by mission_type::from_legacy().
mission_MISSION_OLD_GUARD_NEC_2
const mission_type_id mission_MISSION_OLD_GUARD_NEC_2("MISSION_OLD_GUARD_NEC_2") ("MISSION_OLD_GUARD_NEC_2") static
Referenced by mission_type::from_legacy().
mission_MISSION_OLD_GUARD_NEC_COMMO_1
const mission_type_id mission_MISSION_OLD_GUARD_NEC_COMMO_1("MISSION_OLD_GUARD_NEC_COMMO_1") ("MISSION_OLD_GUARD_NEC_COMMO_1") static
Referenced by mission_type::from_legacy().
mission_MISSION_OLD_GUARD_NEC_COMMO_2
const mission_type_id mission_MISSION_OLD_GUARD_NEC_COMMO_2("MISSION_OLD_GUARD_NEC_COMMO_2") ("MISSION_OLD_GUARD_NEC_COMMO_2") static
Referenced by mission_type::from_legacy().
mission_MISSION_OLD_GUARD_NEC_COMMO_3
const mission_type_id mission_MISSION_OLD_GUARD_NEC_COMMO_3("MISSION_OLD_GUARD_NEC_COMMO_3") ("MISSION_OLD_GUARD_NEC_COMMO_3") static
Referenced by mission_type::from_legacy().
mission_MISSION_OLD_GUARD_NEC_COMMO_4
const mission_type_id mission_MISSION_OLD_GUARD_NEC_COMMO_4("MISSION_OLD_GUARD_NEC_COMMO_4") ("MISSION_OLD_GUARD_NEC_COMMO_4") static
Referenced by mission_type::from_legacy().
mission_MISSION_OLD_GUARD_REP_1
const mission_type_id mission_MISSION_OLD_GUARD_REP_1("MISSION_OLD_GUARD_REP_1") ("MISSION_OLD_GUARD_REP_1") static
Referenced by mission_type::from_legacy().
mission_MISSION_OLD_GUARD_REP_2
const mission_type_id mission_MISSION_OLD_GUARD_REP_2("MISSION_OLD_GUARD_REP_2") ("MISSION_OLD_GUARD_REP_2") static
Referenced by mission_type::from_legacy().
mission_MISSION_OLD_GUARD_REP_3
const mission_type_id mission_MISSION_OLD_GUARD_REP_3("MISSION_OLD_GUARD_REP_3") ("MISSION_OLD_GUARD_REP_3") static
Referenced by mission_type::from_legacy().
mission_MISSION_OLD_GUARD_REP_4
const mission_type_id mission_MISSION_OLD_GUARD_REP_4("MISSION_OLD_GUARD_REP_4") ("MISSION_OLD_GUARD_REP_4") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_BARTENDER_1
const mission_type_id mission_MISSION_RANCH_BARTENDER_1("MISSION_RANCH_BARTENDER_1") ("MISSION_RANCH_BARTENDER_1") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_BARTENDER_2
const mission_type_id mission_MISSION_RANCH_BARTENDER_2("MISSION_RANCH_BARTENDER_2") ("MISSION_RANCH_BARTENDER_2") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_BARTENDER_3
const mission_type_id mission_MISSION_RANCH_BARTENDER_3("MISSION_RANCH_BARTENDER_3") ("MISSION_RANCH_BARTENDER_3") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_BARTENDER_4
const mission_type_id mission_MISSION_RANCH_BARTENDER_4("MISSION_RANCH_BARTENDER_4") ("MISSION_RANCH_BARTENDER_4") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_BARTENDER_5
const mission_type_id mission_MISSION_RANCH_BARTENDER_5("MISSION_RANCH_BARTENDER_5") ("MISSION_RANCH_BARTENDER_5") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_1
const mission_type_id mission_MISSION_RANCH_FOREMAN_1("MISSION_RANCH_FOREMAN_1") ("MISSION_RANCH_FOREMAN_1") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_10
const mission_type_id mission_MISSION_RANCH_FOREMAN_10("MISSION_RANCH_FOREMAN_10") ("MISSION_RANCH_FOREMAN_10") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_11
const mission_type_id mission_MISSION_RANCH_FOREMAN_11("MISSION_RANCH_FOREMAN_11") ("MISSION_RANCH_FOREMAN_11") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_12
const mission_type_id mission_MISSION_RANCH_FOREMAN_12("MISSION_RANCH_FOREMAN_12") ("MISSION_RANCH_FOREMAN_12") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_13
const mission_type_id mission_MISSION_RANCH_FOREMAN_13("MISSION_RANCH_FOREMAN_13") ("MISSION_RANCH_FOREMAN_13") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_14
const mission_type_id mission_MISSION_RANCH_FOREMAN_14("MISSION_RANCH_FOREMAN_14") ("MISSION_RANCH_FOREMAN_14") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_15
const mission_type_id mission_MISSION_RANCH_FOREMAN_15("MISSION_RANCH_FOREMAN_15") ("MISSION_RANCH_FOREMAN_15") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_16
const mission_type_id mission_MISSION_RANCH_FOREMAN_16("MISSION_RANCH_FOREMAN_16") ("MISSION_RANCH_FOREMAN_16") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_17
const mission_type_id mission_MISSION_RANCH_FOREMAN_17("MISSION_RANCH_FOREMAN_17") ("MISSION_RANCH_FOREMAN_17") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_2
const mission_type_id mission_MISSION_RANCH_FOREMAN_2("MISSION_RANCH_FOREMAN_2") ("MISSION_RANCH_FOREMAN_2") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_3
const mission_type_id mission_MISSION_RANCH_FOREMAN_3("MISSION_RANCH_FOREMAN_3") ("MISSION_RANCH_FOREMAN_3") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_4
const mission_type_id mission_MISSION_RANCH_FOREMAN_4("MISSION_RANCH_FOREMAN_4") ("MISSION_RANCH_FOREMAN_4") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_5
const mission_type_id mission_MISSION_RANCH_FOREMAN_5("MISSION_RANCH_FOREMAN_5") ("MISSION_RANCH_FOREMAN_5") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_6
const mission_type_id mission_MISSION_RANCH_FOREMAN_6("MISSION_RANCH_FOREMAN_6") ("MISSION_RANCH_FOREMAN_6") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_7
const mission_type_id mission_MISSION_RANCH_FOREMAN_7("MISSION_RANCH_FOREMAN_7") ("MISSION_RANCH_FOREMAN_7") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_8
const mission_type_id mission_MISSION_RANCH_FOREMAN_8("MISSION_RANCH_FOREMAN_8") ("MISSION_RANCH_FOREMAN_8") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_FOREMAN_9
const mission_type_id mission_MISSION_RANCH_FOREMAN_9("MISSION_RANCH_FOREMAN_9") ("MISSION_RANCH_FOREMAN_9") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_NURSE_1
const mission_type_id mission_MISSION_RANCH_NURSE_1("MISSION_RANCH_NURSE_1") ("MISSION_RANCH_NURSE_1") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_NURSE_10
const mission_type_id mission_MISSION_RANCH_NURSE_10("MISSION_RANCH_NURSE_10") ("MISSION_RANCH_NURSE_10") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_NURSE_11
const mission_type_id mission_MISSION_RANCH_NURSE_11("MISSION_RANCH_NURSE_11") ("MISSION_RANCH_NURSE_11") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_NURSE_2
const mission_type_id mission_MISSION_RANCH_NURSE_2("MISSION_RANCH_NURSE_2") ("MISSION_RANCH_NURSE_2") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_NURSE_3
const mission_type_id mission_MISSION_RANCH_NURSE_3("MISSION_RANCH_NURSE_3") ("MISSION_RANCH_NURSE_3") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_NURSE_4
const mission_type_id mission_MISSION_RANCH_NURSE_4("MISSION_RANCH_NURSE_4") ("MISSION_RANCH_NURSE_4") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_NURSE_5
const mission_type_id mission_MISSION_RANCH_NURSE_5("MISSION_RANCH_NURSE_5") ("MISSION_RANCH_NURSE_5") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_NURSE_6
const mission_type_id mission_MISSION_RANCH_NURSE_6("MISSION_RANCH_NURSE_6") ("MISSION_RANCH_NURSE_6") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_NURSE_7
const mission_type_id mission_MISSION_RANCH_NURSE_7("MISSION_RANCH_NURSE_7") ("MISSION_RANCH_NURSE_7") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_NURSE_8
const mission_type_id mission_MISSION_RANCH_NURSE_8("MISSION_RANCH_NURSE_8") ("MISSION_RANCH_NURSE_8") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_NURSE_9
const mission_type_id mission_MISSION_RANCH_NURSE_9("MISSION_RANCH_NURSE_9") ("MISSION_RANCH_NURSE_9") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_SCAVENGER_1
const mission_type_id mission_MISSION_RANCH_SCAVENGER_1("MISSION_RANCH_SCAVENGER_1") ("MISSION_RANCH_SCAVENGER_1") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_SCAVENGER_2
const mission_type_id mission_MISSION_RANCH_SCAVENGER_2("MISSION_RANCH_SCAVENGER_2") ("MISSION_RANCH_SCAVENGER_2") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_SCAVENGER_3
const mission_type_id mission_MISSION_RANCH_SCAVENGER_3("MISSION_RANCH_SCAVENGER_3") ("MISSION_RANCH_SCAVENGER_3") static
Referenced by mission_type::from_legacy().
mission_MISSION_RANCH_SCAVENGER_4
const mission_type_id mission_MISSION_RANCH_SCAVENGER_4("MISSION_RANCH_SCAVENGER_4") ("MISSION_RANCH_SCAVENGER_4") static
Referenced by mission_type::from_legacy().
mission_MISSION_REACH_FARM_HOUSE
const mission_type_id mission_MISSION_REACH_FARM_HOUSE("MISSION_REACH_FARM_HOUSE") ("MISSION_REACH_FARM_HOUSE") static
Referenced by mission_type::from_legacy().
mission_MISSION_REACH_FEMA_CAMP
const mission_type_id mission_MISSION_REACH_FEMA_CAMP("MISSION_REACH_FEMA_CAMP") ("MISSION_REACH_FEMA_CAMP") static
Referenced by mission_type::from_legacy().
mission_MISSION_REACH_SAFETY
const mission_type_id mission_MISSION_REACH_SAFETY("MISSION_REACH_SAFETY") ("MISSION_REACH_SAFETY") static
Referenced by mission_type::from_legacy().
mission_MISSION_RECOVER_PRIEST_DIARY
const mission_type_id mission_MISSION_RECOVER_PRIEST_DIARY("MISSION_RECOVER_PRIEST_DIARY") ("MISSION_RECOVER_PRIEST_DIARY") static
Referenced by mission_type::from_legacy().
mission_MISSION_RECRUIT_TRACKER
const mission_type_id mission_MISSION_RECRUIT_TRACKER("MISSION_RECRUIT_TRACKER") ("MISSION_RECRUIT_TRACKER") static
Referenced by mission_type::from_legacy().
mission_MISSION_RESCUE_DOG
const mission_type_id mission_MISSION_RESCUE_DOG("MISSION_RESCUE_DOG") ("MISSION_RESCUE_DOG") static
Referenced by mission_type::from_legacy().
mission_type_factory
generic_factory<mission_type> mission_type_factory("mission_type") ("mission_type") static
Referenced by mission_type::get_all(), mission_type::load_mission_type(), and mission_type::reset().
tripoint_function_map
const std::map<std::string, std::function<bool(const tripoint_abs_omt &)> > tripoint_function_map static
Initial value:
= {{
        { "never", mission_place::never },
        { "always", mission_place::always },
        { "near_town", mission_place::near_town }
    }
}
Definition at line 211 of file missiondef.cpp.
Referenced by mission_type::load().