Cataclysm DDA: src/mission_util.cpp File Reference
mission_util.cpp File Reference
#include <algorithm>
#include <functional>
#include <iosfwd>
#include <memory>
#include <new>
#include <optional>
#include <string>
#include <utility>
#include <vector>
#include "avatar.h"
#include "cata_assert.h"
#include "character.h"
#include "city.h"
#include "coordinates.h"
#include "condition.h"
#include "debug.h"
#include "dialogue.h"
#include "enum_conversions.h"
#include "enums.h"
#include "game.h"
#include "json.h"
#include "map_iterator.h"
#include "mapgen_functions.h"
#include "messages.h"
#include "mission.h"
#include "npc.h"
#include "omdata.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "point.h"
#include "rng.h"
#include "talker.h"
#include "translations.h"
#include "type_id.h"
Functions
static tripoint_abs_omt reveal_destination (const std::string &type)
static void reveal_route (mission *miss, const tripoint_abs_omt &destination)
static void reveal_target (mission *miss, const std::string &omter_id)
static void reveal_any_target (mission *miss, const std::vector< std::string > &omter_ids)
static tripoint_abs_omt random_house_in_city (const city_reference &cref)
Given a (valid!) city reference, select a random house within the city borders.
static std::optional< tripoint_abs_omt > find_or_create_om_terrain (const tripoint_abs_omt &origin_pos, const mission_target_params &params, dialogue &d)
static tripoint_abs_omt get_mission_om_origin (const mission_target_params &params, dialogue &d)
Function Documentation
find_or_create_om_terrain()
static std::optional<tripoint_abs_omt> find_or_create_om_terrain (const tripoint_abs_omt & origin_pos, const mission_target_params & params, dialogue & d) static
Definition at line 177 of file mission_util.cpp.
 {
     tripoint_abs_omt target_pos = overmap::invalid_tripoint;
     if( params.target_var.has_value() ) {
         return project_to<coords::omt>( get_tripoint_from_var( params.target_var.value(), d ) );
     }
     omt_find_params find_params;
     std::vector<std::pair<std::string, ot_match_type>> temp_types;
     std::pair<std::string, ot_match_type> temp_pair;
     temp_pair.first = params.overmap_terrain.evaluate( d );
     temp_pair.second = params.overmap_terrain_match_type;
     temp_types.push_back( temp_pair );
     find_params.types = temp_types;
     find_params.search_range = params.search_range.evaluate( d );
     find_params.min_distance = params.min_distance.evaluate( d );
     find_params.must_see = params.must_see;
     find_params.cant_see = params.cant_see;
     find_params.existing_only = true;
     auto get_target_position = [&]() {
         // Either find a random or closest match, based on the criteria.
         if( params.random ) {
             target_pos = overmap_buffer.find_random( origin_pos, find_params );
         } else {
             target_pos = overmap_buffer.find_closest( origin_pos, find_params );
         }
         // If we didn't find a match, and we're allowed to create new terrain, and the player didn't
         // have to see the location beforehand, then we can attempt to create the new terrain.
         if( target_pos == overmap::invalid_tripoint && params.create_if_necessary &&
             !params.must_see ) {
             // If this terrain is part of an overmap special...
             if( params.overmap_special ) {
                 // ...then attempt to place the whole special.
                 const bool placed = overmap_buffer.place_special( static_cast<overmap_special_id >(
                                         ( *params.overmap_special ).evaluate( d ) ), origin_pos,
                                     params.search_range.evaluate( d ) );
                 // If we succeeded in placing the special, then try and find the particular location
                 // we're interested in.
                 if( placed ) {
                     find_params.must_see = false;
                     target_pos = overmap_buffer.find_closest( origin_pos, find_params );
                 }
             } else if( params.replaceable_overmap_terrain ) {
                 // This terrain wasn't part of an overmap special, but we do have a replacement
                 // terrain specified. Find a random location of that replacement type.
                 find_params.must_see = false;
                 find_params.types.front().first = ( *params.replaceable_overmap_terrain ).evaluate( d );
                 target_pos = overmap_buffer.find_random( origin_pos, find_params );
                 // We didn't find it, so allow this search to create new overmaps and try again.
                 find_params.existing_only = true;
                 if( target_pos == overmap::invalid_tripoint ) {
                     target_pos = overmap_buffer.find_random( origin_pos, find_params );
                 }
                 // We found a match, so set this position (which was our replacement terrain)
                 // to our desired mission terrain.
                 if( target_pos != overmap::invalid_tripoint ) {
                     overmap_buffer.ter_set( target_pos, oter_id( params.overmap_terrain.evaluate( d ) ) );
                 }
             }
         }
     };
     // First try to get the position where we only allow existing overmaps.
     get_target_position();
     if( target_pos == overmap::invalid_tripoint ) {
         // If it's invalid, then that means we couldn't find it or create it (if allowed) on
         // our current overmap. We'll now go ahead and try again but allow it to create new overmaps.
         find_params.existing_only = false;
         get_target_position();
     }
     // If we got here and this is still invalid, it means that we couldn't find it nor create it
     // on any overmap (new or existing) within the allowed search range.
     if( target_pos == overmap::invalid_tripoint ) {
         debugmsg( "Unable to find and assign mission target %s.", params.overmap_terrain.evaluate( d ) );
         return std::nullopt;
     }
     return target_pos;
 }
References mission_target_params::cant_see, omt_find_params::cant_see, mission_target_params::create_if_necessary, debugmsg, dbl_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), omt_find_params::existing_only, overmapbuffer::find_closest(), overmapbuffer::find_random(), get_tripoint_from_var(), overmap::invalid_tripoint, mission_target_params::min_distance, omt_find_params::min_distance, mission_target_params::must_see, omt_find_params::must_see, overmap_buffer, mission_target_params::overmap_special, mission_target_params::overmap_terrain, mission_target_params::overmap_terrain_match_type, overmapbuffer::place_special(), mission_target_params::random, mission_target_params::replaceable_overmap_terrain, mission_target_params::search_range, omt_find_params::search_range, mission_target_params::target_var, overmapbuffer::ter_set(), and omt_find_params::types.
Referenced by mission_util::assign_mission_target(), and mission_util::get_om_terrain_pos().
get_mission_om_origin()
static tripoint_abs_omt get_mission_om_origin (const mission_target_params & params, dialogue & d) static
Definition at line 264 of file mission_util.cpp.
 {
     // use the player or NPC's current position, adjust for the z value if any
     tripoint_abs_omt origin_pos = get_player_character().global_omt_location();
     if( !params.origin_u ) {
         npc *guy = nullptr;
         if( params.guy ) {
             guy = params.guy;
         } else if( params.mission_pointer ) {
             guy = g->find_npc( params.mission_pointer->get_npc_id() );
         }
         if( guy ) {
             origin_pos = guy->global_omt_location();
         }
     }
     if( params.z ) {
         origin_pos.z() = ( *params.z ).evaluate( d );
     }
     return origin_pos;
 }
References g, mission::get_npc_id(), get_player_character(), Creature::global_omt_location(), mission_target_params::guy, mission_target_params::mission_pointer, mission_target_params::origin_u, coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and mission_target_params::z.
Referenced by mission_util::assign_mission_target(), and mission_util::get_om_terrain_pos().
random_house_in_city()
static tripoint_abs_omt random_house_in_city (const city_reference & cref) static
Given a (valid!) city reference, select a random house within the city borders.
Returns
global overmap terrain coordinates of the house.
Definition at line 122 of file mission_util.cpp.
 {
     // TODO: fix point types
     const tripoint_abs_omt city_center_omt =
         project_to<coords::omt>( cref.abs_sm_pos );
     std::vector<tripoint_abs_omt> valid;
     for( const tripoint_abs_omt &p : points_in_radius( city_center_omt, cref.city->size ) ) {
         if( overmap_buffer.check_ot( "house", ot_match_type::prefix, p ) ) {
             valid.push_back( p );
         }
     }
     return random_entry( valid, city_center_omt ); // center of the city is a good fallback
 }
References city_reference::abs_sm_pos, overmapbuffer::check_ot(), city_reference::city, overmap_buffer, points_in_radius(), prefix, random_entry(), and city::size.
Referenced by mission_util::random_house_in_closest_city().
reveal_any_target()
static void reveal_any_target (mission * miss, const std::vector< std::string > & omter_ids) static
Definition at line 89 of file mission_util.cpp.
 {
     reveal_target( miss, random_entry( omter_ids ) );
 }
References random_entry(), and reveal_target().
Referenced by mission_util::set_reveal_any().
reveal_destination()
static tripoint_abs_omt reveal_destination (const std::string & type) static
Definition at line 37 of file mission_util.cpp.
 {
     const tripoint_abs_omt your_pos = get_player_character().global_omt_location();
     const tripoint_abs_omt center_pos =
         overmap_buffer.find_random( your_pos, type, rng( 40, 80 ), false );
     if( center_pos != overmap::invalid_tripoint ) {
         overmap_buffer.reveal( center_pos, 2 );
         return center_pos;
     }
     return overmap::invalid_tripoint;
 }
References overmapbuffer::find_random(), get_player_character(), Creature::global_omt_location(), overmap::invalid_tripoint, overmap_buffer, overmapbuffer::reveal(), and rng().
Referenced by reveal_target().
reveal_route()
static void reveal_route (mission * miss, const tripoint_abs_omt & destination) static
Definition at line 51 of file mission_util.cpp.
 {
     const npc *p = g->find_npc( miss->get_npc_id() );
     if( p == nullptr ) {
         debugmsg( "couldn't find an NPC!" );
         return;
     }
     const tripoint_abs_omt source = get_player_character().global_omt_location();
     const tripoint_abs_omt source_road = overmap_buffer.find_closest( source, "road", 3, false );
     const tripoint_abs_omt dest_road = overmap_buffer.find_closest( destination, "road", 3, false );
     if( overmap_buffer.reveal_route( source_road, dest_road ) ) {
         add_msg( _( "%s also marks the road that leads to it" ), p->get_name() );
     }
 }
References _, add_msg(), debugmsg, overmapbuffer::find_closest(), g, Character::get_name(), mission::get_npc_id(), get_player_character(), Creature::global_omt_location(), overmap_buffer, and overmapbuffer::reveal_route().
Referenced by reveal_target().
reveal_target()
static void reveal_target (mission * miss, const std::string & omter_id) static
Definition at line 69 of file mission_util.cpp.
 {
     const npc *p = g->find_npc( miss->get_npc_id() );
     if( p == nullptr ) {
         debugmsg( "couldn't find an NPC!" );
         return;
     }
     const tripoint_abs_omt destination = reveal_destination( omter_id );
     if( destination != overmap::invalid_tripoint ) {
         const oter_id oter = overmap_buffer.ter( destination );
         add_msg( _( "%s has marked the only %s known to them on your map." ), p->get_name(),
                  oter->get_name() );
         miss->set_target( destination );
         if( one_in( 3 ) ) {
             reveal_route( miss, destination );
         }
     }
 }
References _, add_msg(), debugmsg, g, oter_t::get_name(), Character::get_name(), mission::get_npc_id(), overmap::invalid_tripoint, one_in(), overmap_buffer, reveal_destination(), reveal_route(), mission::set_target(), and overmapbuffer::ter().
Referenced by reveal_any_target(), and mission_util::set_reveal().