Cataclysm DDA: src/mission_companion.cpp File Reference
mission_companion.cpp File Reference
#include "mission_companion.h"
#include <algorithm>
#include <cstdlib>
#include <list>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <tuple>
#include <unordered_map>
#include <utility>
#include <vector>
#include "basecamp.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_assert.h"
#include "catacharset.h"
#include "character.h"
#include "colony.h"
#include "color.h"
#include "coordinates.h"
#include "creature.h"
#include "creature_tracker.h"
#include "cursesdef.h"
#include "debug.h"
#include "enums.h"
#include "faction.h"
#include "faction_camp.h"
#include "game.h"
#include "game_constants.h"
#include "input_context.h"
#include "inventory.h"
#include "item.h"
#include "item_group.h"
#include "item_stack.h"
#include "itype.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "memory_fast.h"
#include "messages.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "npctrade_utils.h"
#include "output.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "point.h"
#include "rng.h"
#include "skill.h"
#include "string_formatter.h"
#include "translations.h"
#include "ui.h"
#include "ui_manager.h"
#include "value_ptr.h"
#include "weather.h"
#include "weighted_list.h"
Classes
struct miss_data
struct comp_rank
Namespaces
io
talk_function
Functions
template<>
std::string io::enum_to_string< mission_kind > (mission_kind data)
std::string action_of (mission_kind kind)
bool is_equal (const mission_id &first, const mission_id &second)
void reset_miss_id (mission_id &miss_id)
bool is_equal (const ui_mission_id &first, const ui_mission_id &second)
static void talk_function::scavenger_patrol (mission_data &mission_key, npc &p)
static void talk_function::scavenger_raid (mission_data &mission_key, npc &p)
static void talk_function::hospital_raid (mission_data &mission_key, npc &p)
static void talk_function::commune_menial (mission_data &mission_key, npc &p)
static void talk_function::commune_carpentry (mission_data &mission_key, npc &p)
static void talk_function::commune_forage (mission_data &mission_key, npc &p)
static void talk_function::commune_refuge_caravan (mission_data &mission_key, npc &p)
static bool talk_function::handle_outpost_mission (const mission_entry &cur_key, npc &p)
static int scavenging_combat_skill (npc &p, int bonus, bool guns)
static int companion_combat_rank (const npc &p)
static int companion_survival_rank (const npc &p)
static int companion_industry_rank (const npc &p)
static bool companion_sort_compare (const npc_ptr &first, const npc_ptr &second)
Variables
static const efftype_id effect_riding ("riding")
static const furn_str_id furn_f_plant_harvest ("f_plant_harvest")
static const furn_str_id furn_f_plant_seed ("f_plant_seed")
static const item_group_id Item_spawn_data_farming_seeds ("farming_seeds")
static const item_group_id Item_spawn_data_forage_autumn ("forage_autumn")
static const item_group_id Item_spawn_data_forage_spring ("forage_spring")
static const item_group_id Item_spawn_data_forage_summer ("forage_summer")
static const item_group_id Item_spawn_data_forage_winter ("forage_winter")
static const item_group_id Item_spawn_data_npc_weapon_random ("npc_weapon_random")
static const itype_id itype_FMCNote ("FMCNote")
static const itype_id itype_fungal_seeds ("fungal_seeds")
static const itype_id itype_marloss_seed ("marloss_seed")
static const oter_str_id oter_looted_hospital ("looted_hospital")
static const oter_str_id oter_looted_hospital_roof ("looted_hospital_roof")
static const oter_str_id oter_looted_house ("looted_house")
static const oter_str_id oter_looted_house_basement ("looted_house_basement")
static const oter_str_id oter_looted_house_roof ("looted_house_roof")
static const oter_str_id oter_open_air ("open_air")
static const skill_id skill_bashing ("bashing")
static const skill_id skill_cutting ("cutting")
static const skill_id skill_dodge ("dodge")
static const skill_id skill_fabrication ("fabrication")
static const skill_id skill_gun ("gun")
static const skill_id skill_melee ("melee")
static const skill_id skill_stabbing ("stabbing")
static const skill_id skill_survival ("survival")
static const skill_id skill_unarmed ("unarmed")
static const string_id< class npc_template > npc_template_bandit ("bandit")
static const string_id< class npc_template > npc_template_commune_guard ("commune_guard")
static const string_id< class npc_template > npc_template_thug ("thug")
static const ter_str_id ter_t_curtains ("t_curtains")
static const ter_str_id ter_t_dirt ("t_dirt")
static const ter_str_id ter_t_dirtmound ("t_dirtmound")
static const ter_str_id ter_t_door_b ("t_door_b")
static const ter_str_id ter_t_door_boarded ("t_door_boarded")
static const ter_str_id ter_t_door_boarded_damaged ("t_door_boarded_damaged")
static const ter_str_id ter_t_door_boarded_damaged_peep ("t_door_boarded_damaged_peep")
static const ter_str_id ter_t_door_boarded_peep ("t_door_boarded_peep")
static const ter_str_id ter_t_door_c ("t_door_c")
static const ter_str_id ter_t_door_c_peep ("t_door_c_peep")
static const ter_str_id ter_t_door_glass_c ("t_door_glass_c")
static const ter_str_id ter_t_door_glass_o ("t_door_glass_o")
static const ter_str_id ter_t_door_locked ("t_door_locked")
static const ter_str_id ter_t_door_locked_alarm ("t_door_locked_alarm")
static const ter_str_id ter_t_door_locked_peep ("t_door_locked_peep")
static const ter_str_id ter_t_door_metal_c ("t_door_metal_c")
static const ter_str_id ter_t_door_metal_locked ("t_door_metal_locked")
static const ter_str_id ter_t_door_metal_o ("t_door_metal_o")
static const ter_str_id ter_t_door_metal_pickable ("t_door_metal_pickable")
static const ter_str_id ter_t_door_o ("t_door_o")
static const ter_str_id ter_t_rdoor_boarded ("t_rdoor_boarded")
static const ter_str_id ter_t_rdoor_boarded_damaged ("t_rdoor_boarded_damaged")
static const ter_str_id ter_t_wall ("t_wall")
static const ter_str_id ter_t_wall_glass ("t_wall_glass")
static const ter_str_id ter_t_wall_glass_alarm ("t_wall_glass_alarm")
static const ter_str_id ter_t_window ("t_window")
static const ter_str_id ter_t_window_alarm ("t_window_alarm")
static const ter_str_id ter_t_window_alarm_taped ("t_window_alarm_taped")
static const ter_str_id ter_t_window_boarded ("t_window_boarded")
static const ter_str_id ter_t_window_boarded_noglass ("t_window_boarded_noglass")
static const ter_str_id ter_t_window_domestic ("t_window_domestic")
static const ter_str_id ter_t_window_domestic_taped ("t_window_domestic_taped")
static const ter_str_id ter_t_window_no_curtains ("t_window_no_curtains")
static const ter_str_id ter_t_window_no_curtains_taped ("t_window_no_curtains_taped")
static const ter_str_id ter_t_window_taped ("t_window_taped")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
static const trait_id trait_NPC_CONSTRUCTION_LEV_2 ("NPC_CONSTRUCTION_LEV_2")
static const trait_id trait_NPC_MISSION_LEV_1 ("NPC_MISSION_LEV_1")
static const std::string var_DOCTOR_ANESTHETIC_SCAVENGERS_HELPED
static const std::string var_PURCHASED_FIELD_1_FENCE
static const std::string var_SCAVENGER_HOSPITAL_RAID
static const std::string var_SCAVENGER_HOSPITAL_RAID_STARTED
static const std::string role_id_faction_camp = "FACTION_CAMP"
static const std::string omt_evac_center_18 = "evac_center_18"
static const std::string omt_ranch_camp_63 = "ranch_camp_63"
static const std::string return_ally_question_string
static const std::string camp_upgrade_npc_string = "_faction_upgrade_camp"
static const std::string camp_upgrade_expansion_npc_string = "_faction_upgrade_exp_"
static const std::string caravan_commune_center_job_assign_parameter = "Assign"
static const std::string caravan_commune_center_job_active_parameter = "Active"
static const std::array< miss_data, Camp_Harvest+1 > miss_info
Function Documentation
action_of()
std::string action_of (mission_kind kind)
Definition at line 391 of file mission_companion.cpp.
 {
     return miss_info[kind].action.translated();
 }
References miss_info.
Referenced by npc::faction_display(), basecamp::get_available_missions(), and basecamp::get_available_missions_by_dir().
companion_combat_rank()
static int companion_combat_rank (const npc & p) static
Definition at line 2510 of file mission_companion.cpp.
 {
     int combat = 2 * p.get_dex() + 3 * p.get_str() + 2 * p.get_per() + p.get_int();
     for( const Skill &sk : Skill::skills ) {
         combat += p.get_skill_level( sk.ident() ) * sk.companion_combat_rank_factor();
     }
     return combat * std::min( p.get_dex(), 32 ) * std::min( p.get_str(), 32 ) / 64;
 }
References Character::get_dex(), Character::get_int(), Character::get_per(), Character::get_skill_level(), Character::get_str(), min(), and Skill::skills.
Referenced by companion_sort_compare().
companion_industry_rank()
static int companion_industry_rank (const npc & p) static
Definition at line 2528 of file mission_companion.cpp.
 {
     int industry = p.get_dex() + p.get_str() + p.get_per() + 3 * p.get_int();
     for( const Skill &sk : Skill::skills ) {
         industry += p.get_skill_level( sk.ident() ) * sk.companion_industry_rank_factor();
     }
     return industry * std::min( p.get_int(), 32 ) / 8;
 }
References Character::get_dex(), Character::get_int(), Character::get_per(), Character::get_skill_level(), Character::get_str(), min(), and Skill::skills.
companion_sort_compare()
static bool companion_sort_compare (const npc_ptr & first, const npc_ptr & second) static
Definition at line 2537 of file mission_companion.cpp.
 {
     return companion_combat_rank( *first ) > companion_combat_rank( *second );
 }
References companion_combat_rank(), and second.
Referenced by talk_function::companion_sort().
companion_survival_rank()
static int companion_survival_rank (const npc & p) static
Definition at line 2519 of file mission_companion.cpp.
 {
     float survival = 2 * p.get_dex() + p.get_str() + 2 * p.get_per() + 1.5 * p.get_int();
     for( const Skill &sk : Skill::skills ) {
         survival += p.get_skill_level( sk.ident() ) * sk.companion_survival_rank_factor();
     }
     return survival * std::min( p.get_dex(), 32 ) * std::min( p.get_per(), 32 ) / 64;
 }
References Character::get_dex(), Character::get_int(), Character::get_per(), Character::get_skill_level(), Character::get_str(), min(), and Skill::skills.
is_equal() [1/2]
bool is_equal (const mission_id & first, const mission_id & second)
Definition at line 396 of file mission_companion.cpp.
 {
     return first.id == second.id &&
            first.parameters == second.parameters &&
            first.mapgen_args == second.mapgen_args &&
            first.dir == second.dir;
 }
References mission_id::dir, mission_id::id, mission_id::mapgen_args, mission_id::parameters, and second.
Referenced by talk_function::companion_list(), talk_function::display_and_choose_opts(), basecamp::get_mission_workers(), basecamp::handle_hide_mission(), basecamp::hide_mission(), is_equal(), basecamp::is_hidden(), and basecamp::reveal_mission().
is_equal() [2/2]
bool is_equal (const ui_mission_id & first, const ui_mission_id & second)
Definition at line 564 of file mission_companion.cpp.
 {
     return first.ret == second.ret &&
            is_equal( first.id, second.id );
 }
References ui_mission_id::id, is_equal(), ui_mission_id::ret, and second.
reset_miss_id()
void reset_miss_id (mission_id & miss_id)
Definition at line 404 of file mission_companion.cpp.
 {
     miss_id = {};
 }
Referenced by npc::reset_companion_mission().
scavenging_combat_skill()
static int scavenging_combat_skill (npc & p, int bonus, bool guns) static
NPC Melee affects scavenging_patrol results \EFFECT_SURVIVAL_NPC affects scavenging_patrol results \EFFECT_BASHING_NPC affects scavenging_patrol results \EFFECT_CUTTING_NPC affects scavenging_patrol results \EFFECT_GUN_NPC affects scavenging_patrol results \EFFECT_STABBING_NPC affects scavenging_patrol results \EFFECT_UNARMED_NPC affects scavenging_patrol results \EFFECT_DODGE_NPC affects scavenging_patrol results
Definition at line 1779 of file mission_companion.cpp.
 {
     // the following doxygen aliases do not yet exist. this is marked for future reference
     ///\EFFECT_MELEE_NPC affects scavenging_patrol results
     ///\EFFECT_SURVIVAL_NPC affects scavenging_patrol results
     ///\EFFECT_BASHING_NPC affects scavenging_patrol results
     ///\EFFECT_CUTTING_NPC affects scavenging_patrol results
     ///\EFFECT_GUN_NPC affects scavenging_patrol results
     ///\EFFECT_STABBING_NPC affects scavenging_patrol results
     ///\EFFECT_UNARMED_NPC affects scavenging_patrol results
     ///\EFFECT_DODGE_NPC affects scavenging_patrol results
     return bonus + p.get_skill_level( skill_melee ) + .5 * p.get_skill_level( skill_survival ) +
            p.get_skill_level( skill_bashing ) + p.get_skill_level( skill_cutting ) +
            ( guns ? p.get_skill_level( skill_gun ) : 0 ) + p.get_skill_level( skill_stabbing ) +
            p.get_skill_level( skill_unarmed ) + p.get_skill_level( skill_dodge );
 }
References Character::get_skill_level(), skill_bashing, skill_cutting, skill_dodge, skill_gun, skill_melee, skill_stabbing, skill_survival, and skill_unarmed.
Referenced by talk_function::forage_return(), talk_function::hospital_raid_return(), talk_function::scavenging_patrol_return(), and talk_function::scavenging_raid_return().
Variable Documentation
camp_upgrade_expansion_npc_string
const std::string camp_upgrade_expansion_npc_string = "_faction_upgrade_exp_" static
Definition at line 163 of file mission_companion.cpp.
Referenced by mission_id::deserialize().
camp_upgrade_npc_string
const std::string camp_upgrade_npc_string = "_faction_upgrade_camp" static
Definition at line 162 of file mission_companion.cpp.
Referenced by mission_id::deserialize().
caravan_commune_center_job_active_parameter
const std::string caravan_commune_center_job_active_parameter = "Active" static
Definition at line 166 of file mission_companion.cpp.
Referenced by talk_function::commune_refuge_caravan(), and talk_function::handle_outpost_mission().
caravan_commune_center_job_assign_parameter
const std::string caravan_commune_center_job_assign_parameter = "Assign" static
Definition at line 165 of file mission_companion.cpp.
Referenced by talk_function::caravan_depart(), talk_function::commune_refuge_caravan(), and talk_function::handle_outpost_mission().
effect_riding
const efftype_id effect_riding("riding") ("riding") static
Referenced by talk_function::individual_mission().
furn_f_plant_harvest
const furn_str_id furn_f_plant_harvest("f_plant_harvest") ("f_plant_harvest") static
Referenced by talk_function::field_harvest().
furn_f_plant_seed
const furn_str_id furn_f_plant_seed("f_plant_seed") ("f_plant_seed") static
Referenced by talk_function::field_plant().
Item_spawn_data_farming_seeds
const item_group_id Item_spawn_data_farming_seeds("farming_seeds") ("farming_seeds") static
Referenced by talk_function::forage_return().
Item_spawn_data_forage_autumn
const item_group_id Item_spawn_data_forage_autumn("forage_autumn") ("forage_autumn") static
Referenced by talk_function::forage_return().
Item_spawn_data_forage_spring
const item_group_id Item_spawn_data_forage_spring("forage_spring") ("forage_spring") static
Referenced by talk_function::forage_return().
Item_spawn_data_forage_summer
const item_group_id Item_spawn_data_forage_summer("forage_summer") ("forage_summer") static
Referenced by talk_function::forage_return().
Item_spawn_data_forage_winter
const item_group_id Item_spawn_data_forage_winter("forage_winter") ("forage_winter") static
Referenced by talk_function::forage_return().
Item_spawn_data_npc_weapon_random
const item_group_id Item_spawn_data_npc_weapon_random("npc_weapon_random") ("npc_weapon_random") static
Referenced by talk_function::hospital_raid_return(), and talk_function::scavenging_raid_return().
itype_FMCNote
const itype_id itype_FMCNote("FMCNote") ("FMCNote") static
Referenced by talk_function::caravan_return(), talk_function::carpenter_return(), talk_function::field_harvest(), talk_function::field_plant(), talk_function::forage_return(), talk_function::labor_return(), talk_function::scavenging_patrol_return(), and talk_function::scavenging_raid_return().
itype_fungal_seeds
const itype_id itype_fungal_seeds("fungal_seeds") ("fungal_seeds") static
Referenced by talk_function::field_plant().
itype_marloss_seed
const itype_id itype_marloss_seed("marloss_seed") ("marloss_seed") static
Referenced by talk_function::field_plant().
miss_info
const std::array< miss_data, Camp_Harvest + 1 > miss_info static
Definition at line 228 of file mission_companion.cpp.
Referenced by action_of(), mission_data::add(), mission_id::deserialize(), and talk_function::handle_outpost_mission().
npc_template_bandit
const string_id<class npc_template> npc_template_bandit("bandit") ("bandit") static
Referenced by talk_function::caravan_return().
npc_template_commune_guard
const string_id<class npc_template> npc_template_commune_guard("commune_guard") ("commune_guard") static
Referenced by talk_function::caravan_return().
npc_template_thug
const string_id<class npc_template> npc_template_thug("thug") ("thug") static
Referenced by talk_function::caravan_return().
omt_evac_center_18
const std::string omt_evac_center_18 = "evac_center_18" static
Definition at line 155 of file mission_companion.cpp.
Referenced by talk_function::handle_outpost_mission().
omt_ranch_camp_63
const std::string omt_ranch_camp_63 = "ranch_camp_63" static
Definition at line 156 of file mission_companion.cpp.
Referenced by talk_function::companion_mission().
oter_looted_hospital
const oter_str_id oter_looted_hospital("looted_hospital") ("looted_hospital") static
Referenced by talk_function::hospital_raid_return().
oter_looted_hospital_roof
const oter_str_id oter_looted_hospital_roof("looted_hospital_roof") ("looted_hospital_roof") static
Referenced by talk_function::hospital_raid_return().
oter_looted_house
const oter_str_id oter_looted_house("looted_house") ("looted_house") static
Referenced by talk_function::scavenging_raid_return().
oter_looted_house_basement
const oter_str_id oter_looted_house_basement("looted_house_basement") ("looted_house_basement") static
Referenced by talk_function::scavenging_raid_return().
oter_looted_house_roof
const oter_str_id oter_looted_house_roof("looted_house_roof") ("looted_house_roof") static
Referenced by talk_function::scavenging_raid_return().
oter_open_air
const oter_str_id oter_open_air("open_air") ("open_air") static
Referenced by talk_function::hospital_raid_return(), and talk_function::scavenging_raid_return().
return_ally_question_string
const std::string return_ally_question_string static
Initial value:
=
    "\n\nDo you wish to bring your allies back into your party?"
Definition at line 158 of file mission_companion.cpp.
Referenced by talk_function::commune_carpentry(), talk_function::commune_forage(), talk_function::commune_menial(), talk_function::hospital_raid(), talk_function::scavenger_patrol(), and talk_function::scavenger_raid().
role_id_faction_camp
const std::string role_id_faction_camp = "FACTION_CAMP" static
Definition at line 153 of file mission_companion.cpp.
Referenced by talk_function::display_and_choose_opts().
skill_bashing
const skill_id skill_bashing("bashing") ("bashing") static
Referenced by scavenging_combat_skill().
skill_cutting
const skill_id skill_cutting("cutting") ("cutting") static
Referenced by scavenging_combat_skill().
skill_dodge
const skill_id skill_dodge("dodge") ("dodge") static
Referenced by talk_function::carpenter_return(), talk_function::forage_return(), and scavenging_combat_skill().
skill_fabrication
const skill_id skill_fabrication("fabrication") ("fabrication") static
Referenced by talk_function::carpenter_return().
skill_gun
const skill_id skill_gun("gun") ("gun") static
Referenced by scavenging_combat_skill().
skill_melee
const skill_id skill_melee("melee") ("melee") static
Referenced by scavenging_combat_skill().
skill_stabbing
const skill_id skill_stabbing("stabbing") ("stabbing") static
Referenced by scavenging_combat_skill().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by talk_function::carpenter_return(), talk_function::forage_return(), and scavenging_combat_skill().
skill_unarmed
const skill_id skill_unarmed("unarmed") ("unarmed") static
Referenced by scavenging_combat_skill().
ter_t_curtains
const ter_str_id ter_t_curtains("t_curtains") ("t_curtains") static
Referenced by talk_function::loot_building().
ter_t_dirt
const ter_str_id ter_t_dirt("t_dirt") ("t_dirt") static
Referenced by talk_function::field_plant().
ter_t_dirtmound
const ter_str_id ter_t_dirtmound("t_dirtmound") ("t_dirtmound") static
Referenced by talk_function::field_harvest(), and talk_function::field_plant().
ter_t_door_b
const ter_str_id ter_t_door_b("t_door_b") ("t_door_b") static
Referenced by talk_function::loot_building().
ter_t_door_boarded
const ter_str_id ter_t_door_boarded("t_door_boarded") ("t_door_boarded") static
Referenced by talk_function::loot_building().
ter_t_door_boarded_damaged
const ter_str_id ter_t_door_boarded_damaged("t_door_boarded_damaged") ("t_door_boarded_damaged") static
Referenced by talk_function::loot_building().
ter_t_door_boarded_damaged_peep
const ter_str_id ter_t_door_boarded_damaged_peep("t_door_boarded_damaged_peep") ("t_door_boarded_damaged_peep") static
Referenced by talk_function::loot_building().
ter_t_door_boarded_peep
const ter_str_id ter_t_door_boarded_peep("t_door_boarded_peep") ("t_door_boarded_peep") static
Referenced by talk_function::loot_building().
ter_t_door_c
const ter_str_id ter_t_door_c("t_door_c") ("t_door_c") static
Referenced by talk_function::loot_building().
ter_t_door_c_peep
const ter_str_id ter_t_door_c_peep("t_door_c_peep") ("t_door_c_peep") static
Referenced by talk_function::loot_building().
ter_t_door_glass_c
const ter_str_id ter_t_door_glass_c("t_door_glass_c") ("t_door_glass_c") static
Referenced by talk_function::loot_building().
ter_t_door_glass_o
const ter_str_id ter_t_door_glass_o("t_door_glass_o") ("t_door_glass_o") static
Referenced by talk_function::loot_building().
ter_t_door_locked
const ter_str_id ter_t_door_locked("t_door_locked") ("t_door_locked") static
Referenced by talk_function::loot_building().
ter_t_door_locked_alarm
const ter_str_id ter_t_door_locked_alarm("t_door_locked_alarm") ("t_door_locked_alarm") static
Referenced by talk_function::loot_building().
ter_t_door_locked_peep
const ter_str_id ter_t_door_locked_peep("t_door_locked_peep") ("t_door_locked_peep") static
Referenced by talk_function::loot_building().
ter_t_door_metal_c
const ter_str_id ter_t_door_metal_c("t_door_metal_c") ("t_door_metal_c") static
Referenced by talk_function::loot_building().
ter_t_door_metal_locked
const ter_str_id ter_t_door_metal_locked("t_door_metal_locked") ("t_door_metal_locked") static
Referenced by talk_function::loot_building().
ter_t_door_metal_o
const ter_str_id ter_t_door_metal_o("t_door_metal_o") ("t_door_metal_o") static
Referenced by talk_function::loot_building().
ter_t_door_metal_pickable
const ter_str_id ter_t_door_metal_pickable("t_door_metal_pickable") ("t_door_metal_pickable") static
Referenced by talk_function::loot_building().
ter_t_door_o
const ter_str_id ter_t_door_o("t_door_o") ("t_door_o") static
Referenced by talk_function::loot_building().
ter_t_rdoor_boarded
const ter_str_id ter_t_rdoor_boarded("t_rdoor_boarded") ("t_rdoor_boarded") static
Referenced by talk_function::loot_building().
ter_t_rdoor_boarded_damaged
const ter_str_id ter_t_rdoor_boarded_damaged("t_rdoor_boarded_damaged") ("t_rdoor_boarded_damaged") static
Referenced by talk_function::loot_building().
ter_t_wall
const ter_str_id ter_t_wall("t_wall") ("t_wall") static
Referenced by talk_function::loot_building().
ter_t_wall_glass
const ter_str_id ter_t_wall_glass("t_wall_glass") ("t_wall_glass") static
Referenced by talk_function::loot_building().
ter_t_wall_glass_alarm
const ter_str_id ter_t_wall_glass_alarm("t_wall_glass_alarm") ("t_wall_glass_alarm") static
Referenced by talk_function::loot_building().
ter_t_window
const ter_str_id ter_t_window("t_window") ("t_window") static
Referenced by talk_function::loot_building().
ter_t_window_alarm
const ter_str_id ter_t_window_alarm("t_window_alarm") ("t_window_alarm") static
Referenced by talk_function::loot_building().
ter_t_window_alarm_taped
const ter_str_id ter_t_window_alarm_taped("t_window_alarm_taped") ("t_window_alarm_taped") static
Referenced by talk_function::loot_building().
ter_t_window_boarded
const ter_str_id ter_t_window_boarded("t_window_boarded") ("t_window_boarded") static
Referenced by talk_function::loot_building().
ter_t_window_boarded_noglass
const ter_str_id ter_t_window_boarded_noglass("t_window_boarded_noglass") ("t_window_boarded_noglass") static
Referenced by talk_function::loot_building().
ter_t_window_domestic
const ter_str_id ter_t_window_domestic("t_window_domestic") ("t_window_domestic") static
Referenced by talk_function::loot_building().
ter_t_window_domestic_taped
const ter_str_id ter_t_window_domestic_taped("t_window_domestic_taped") ("t_window_domestic_taped") static
Referenced by talk_function::loot_building().
ter_t_window_no_curtains
const ter_str_id ter_t_window_no_curtains("t_window_no_curtains") ("t_window_no_curtains") static
Referenced by talk_function::loot_building().
ter_t_window_no_curtains_taped
const ter_str_id ter_t_window_no_curtains_taped("t_window_no_curtains_taped") ("t_window_no_curtains_taped") static
Referenced by talk_function::loot_building().
ter_t_window_taped
const ter_str_id ter_t_window_taped("t_window_taped") ("t_window_taped") static
Referenced by talk_function::loot_building().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by talk_function::companion_choose_return().
trait_NPC_CONSTRUCTION_LEV_2
const trait_id trait_NPC_CONSTRUCTION_LEV_2("NPC_CONSTRUCTION_LEV_2") ("NPC_CONSTRUCTION_LEV_2") static
Referenced by talk_function::field_harvest().
trait_NPC_MISSION_LEV_1
const trait_id trait_NPC_MISSION_LEV_1("NPC_MISSION_LEV_1") ("NPC_MISSION_LEV_1") static
Referenced by talk_function::companion_mission(), talk_function::forage_return(), talk_function::labor_return(), and talk_function::scavenging_patrol_return().
var_DOCTOR_ANESTHETIC_SCAVENGERS_HELPED
const std::string var_DOCTOR_ANESTHETIC_SCAVENGERS_HELPED static
Initial value:
=
    "npctalk_var_mission_tacoma_ranch_doctor_anesthetic_scavengers_helped"
Definition at line 144 of file mission_companion.cpp.
Referenced by talk_function::hospital_raid_return().
var_PURCHASED_FIELD_1_FENCE
const std::string var_PURCHASED_FIELD_1_FENCE static
Initial value:
=
    "npctalk_var_dialogue_tacoma_ranch_purchased_field_1_fence"
Definition at line 146 of file mission_companion.cpp.
Referenced by talk_function::field_harvest().
var_SCAVENGER_HOSPITAL_RAID
const std::string var_SCAVENGER_HOSPITAL_RAID static
Initial value:
=
    "npctalk_var_mission_tacoma_ranch_scavenger_hospital_raid"
Definition at line 148 of file mission_companion.cpp.
Referenced by talk_function::companion_mission(), and talk_function::hospital_raid_return().
var_SCAVENGER_HOSPITAL_RAID_STARTED
const std::string var_SCAVENGER_HOSPITAL_RAID_STARTED static
Initial value:
=
    "npctalk_var_mission_tacoma_ranch_scavenger_hospital_raid_started"
Definition at line 150 of file mission_companion.cpp.
Referenced by talk_function::handle_outpost_mission(), talk_function::hospital_raid(), and talk_function::hospital_raid_return().