Cataclysm DDA: src/mission_companion.h File Reference
mission_companion.h File Reference
#include <iosfwd>
#include <map>
#include <new>
#include <optional>
#include <string>
#include <vector>
#include "calendar.h"
#include "coordinates.h"
#include "mapgendata.h"
#include "memory_fast.h"
#include "point.h"
#include "type_id.h"
Classes
struct enum_traits< mission_kind >
struct mission_id
struct ui_mission_id
struct mission_entry
class mission_data
Namespaces
talk_function
Macros
#define CATA_SRC_MISSION_COMPANION_H
Typedefs
using npc_ptr = shared_ptr_fast< npc >
using comp_list = std::vector< npc_ptr >
Enumerations
enum mission_kind : int {
No_Mission , Scavenging_Patrol_Job , Scavenging_Raid_Job , Hospital_Raid_Job ,
Menial_Job , Carpentry_Job , Forage_Job , Caravan_Commune_Center_Job ,
Camp_Distribute_Food , Camp_Determine_Leadership , Camp_Have_Meal , Camp_Hide_Mission ,
Camp_Reveal_Mission , Camp_Assign_Jobs , Camp_Assign_Workers , Camp_Abandon ,
Camp_Upgrade , Camp_Emergency_Recall , Camp_Crafting , Camp_Gather_Materials ,
Camp_Collect_Firewood , Camp_Menial , Camp_Survey_Field , Camp_Survey_Expansion ,
Camp_Cut_Logs , Camp_Clearcut , Camp_Setup_Hide_Site , Camp_Relay_Hide_Site ,
Camp_Foraging , Camp_Trapping , Camp_Hunting , Camp_OM_Fortifications ,
Camp_Recruiting , Camp_Scouting , Camp_Combat_Patrol , Camp_Chop_Shop ,
Camp_Plow , Camp_Plant , Camp_Harvest , last_mission_kind
}
Functions
std::string action_of (mission_kind kind)
bool is_equal (const mission_id &first, const mission_id &second)
void reset_miss_id (mission_id &miss_id)
bool is_equal (const ui_mission_id &first, const ui_mission_id &second)
void talk_function::companion_mission (npc &p)
bool talk_function::display_and_choose_opts (mission_data &mission_key, const tripoint_abs_omt &omt_pos, const std::string &role_id, const std::string &title)
npc_ptr talk_function::individual_mission (npc &p, const std::string &desc, const mission_id &miss_id, bool group=false, const std::vector< item * > &equipment={}, const std::map< skill_id, int > &required_skills={}, bool silent_failure=false)
Send a companion on an individual mission or attaches them to a group to depart later Set submap_coords and pos.
npc_ptr talk_function::individual_mission (const tripoint_abs_omt &omt_pos, const std::string &role_id, const std::string &desc, const mission_id &miss_id, bool group=false, const std::vector< item * > &equipment={}, const std::map< skill_id, int > &required_skills={}, bool silent_failure=false)
void talk_function::caravan_return (npc &p, const std::string &dest, const mission_id &miss_id)
All of these missions are associated with the ranch camp and need to be updated/merged into the new ones.
void talk_function::caravan_depart (npc &p, const std::string &dest, const mission_id &miss_id)
int talk_function::caravan_dist (const std::string &dest)
void talk_function::field_plant (npc &p, const std::string &place)
void talk_function::field_harvest (npc &p, const std::string &place)
bool talk_function::scavenging_patrol_return (npc &p)
bool talk_function::scavenging_raid_return (npc &p)
bool talk_function::hospital_raid_return (npc &p)
bool talk_function::labor_return (npc &p)
bool talk_function::carpenter_return (npc &p)
bool talk_function::forage_return (npc &p)
void talk_function::companion_skill_trainer (npc &comp, const std::string &skill_tested="", time_duration time_worked=1_hours, int difficulty=1)
Trains NPC comp, in skill_tested for duration time_worked at difficulty 1, several groups of skills can also be input.
void talk_function::companion_skill_trainer (npc &comp, const skill_id &skill_tested, time_duration time_worked=1_hours, int difficulty=1)
bool talk_function::companion_om_combat_check (const comp_list &group, const tripoint_abs_omt &om_tgt, bool try_engage=false)
void talk_function::force_on_force (const comp_list &defender, const std::string &def_desc, const comp_list &attacker, const std::string &att_desc, int advantage)
bool talk_function::force_on_force (const comp_list &defender, const std::string &def_desc, const std::vector< monster * > &monsters_fighting, const std::string &att_desc, int advantage)
int talk_function::combat_score (const comp_list &group)
int talk_function::combat_score (const std::vector< monster * > &group)
void talk_function::attack_random (const comp_list &attacker, const comp_list &defender)
void talk_function::attack_random (const std::vector< monster * > &group, const comp_list &defender)
void talk_function::attack_random (const comp_list &attacker, const std::vector< monster * > &group)
npc_ptr talk_function::temp_npc (const string_id< npc_template > &type)
comp_list talk_function::companion_list (const npc &p, const mission_id &miss_id, bool contains=false)
Returns npcs that have the given companion mission.
comp_list talk_function::companion_list (const tripoint &omt_pos, const std::string &role_id, const mission_id &miss_id, bool contains=false)
comp_list talk_function::companion_sort (comp_list available, const std::map< skill_id, int > &required_skills={})
std::vector< comp_rank > talk_function::companion_rank (const comp_list &available, bool adj=true)
npc_ptr talk_function::companion_choose (const std::map< skill_id, int > &required_skills={}, bool silent_failure=false)
npc_ptr talk_function::companion_choose_return (const npc &p, const mission_id &miss_id, const time_point &deadline, bool ignore_parameters=false)
npc_ptr talk_function::companion_choose_return (const tripoint_abs_omt &omt_pos, const std::string &role_id, const mission_id &miss_id, const time_point &deadline, bool by_mission=true, bool ignore_parameters=false)
npc_ptr talk_function::companion_choose_return (comp_list &npc_list)
void talk_function::companion_return (npc &comp)
std::set< item > talk_function::loot_building (const tripoint_abs_omt &site, const oter_str_id &looted_replacement)
Macro Definition Documentation
CATA_SRC_MISSION_COMPANION_H
#define CATA_SRC_MISSION_COMPANION_H
Definition at line 3 of file mission_companion.h.
Typedef Documentation
comp_list
using comp_list = std::vector<npc_ptr>
Definition at line 26 of file mission_companion.h.
npc_ptr
using npc_ptr = shared_ptr_fast<npc>
Definition at line 25 of file mission_companion.h.
Enumeration Type Documentation
mission_kind
enum mission_kind : int
Enumerator
No_Mission
Scavenging_Patrol_Job
Scavenging_Raid_Job
Hospital_Raid_Job
Menial_Job
Carpentry_Job
Forage_Job
Caravan_Commune_Center_Job
Camp_Distribute_Food
Camp_Determine_Leadership
Camp_Have_Meal
Camp_Hide_Mission
Camp_Reveal_Mission
Camp_Assign_Jobs
Camp_Assign_Workers
Camp_Abandon
Camp_Upgrade
Camp_Emergency_Recall
Camp_Crafting
Camp_Gather_Materials
Camp_Collect_Firewood
Camp_Menial
Camp_Survey_Field
Camp_Survey_Expansion
Camp_Cut_Logs
Camp_Clearcut
Camp_Setup_Hide_Site
Camp_Relay_Hide_Site
Camp_Foraging
Camp_Trapping
Camp_Hunting
Camp_OM_Fortifications
Camp_Recruiting
Camp_Scouting
Camp_Combat_Patrol
Camp_Chop_Shop
Camp_Plow
Camp_Plant
Camp_Harvest
last_mission_kind
Definition at line 37 of file mission_companion.h.
                   : int {
     No_Mission,  //  Null value
     //  Jobs assigned to companions for external parties
     Scavenging_Patrol_Job,
     Scavenging_Raid_Job,
     Hospital_Raid_Job,
     Menial_Job,
     Carpentry_Job,
     Forage_Job,
     Caravan_Commune_Center_Job,
     //  Faction camp tasks
     Camp_Distribute_Food,        //  Direct action, not serialized
     Camp_Determine_Leadership,   //  Direct action, not serialized
     Camp_Have_Meal,              //  Direct action, not serialized
     Camp_Hide_Mission,           //  Direct action, not serialized
     Camp_Reveal_Mission,         //  Direct action, not serialized
     Camp_Assign_Jobs,
     Camp_Assign_Workers,
     Camp_Abandon,
     Camp_Upgrade,
     Camp_Emergency_Recall,
     Camp_Crafting,
     Camp_Gather_Materials,
     Camp_Collect_Firewood,
     Camp_Menial,
     Camp_Survey_Field,
     Camp_Survey_Expansion,
     Camp_Cut_Logs,
     Camp_Clearcut,
     Camp_Setup_Hide_Site,
     Camp_Relay_Hide_Site,
     Camp_Foraging,
     Camp_Trapping,
     Camp_Hunting,
     Camp_OM_Fortifications,
     Camp_Recruiting,
     Camp_Scouting,
     Camp_Combat_Patrol,
     Camp_Chop_Shop,  //  Obsolete removed during 0.E
     Camp_Plow,
     Camp_Plant,
     Camp_Harvest,
     last_mission_kind
 };
Function Documentation
action_of()
std::string action_of (mission_kind kind)
Definition at line 391 of file mission_companion.cpp.
 {
     return miss_info[kind].action.translated();
 }
References miss_info.
Referenced by npc::faction_display(), basecamp::get_available_missions(), and basecamp::get_available_missions_by_dir().
is_equal() [1/2]
bool is_equal (const mission_id & first, const mission_id & second)
Definition at line 396 of file mission_companion.cpp.
 {
     return first.id == second.id &&
            first.parameters == second.parameters &&
            first.mapgen_args == second.mapgen_args &&
            first.dir == second.dir;
 }
References mission_id::dir, mission_id::id, mission_id::mapgen_args, mission_id::parameters, and second.
Referenced by talk_function::companion_list(), talk_function::display_and_choose_opts(), basecamp::get_mission_workers(), basecamp::handle_hide_mission(), basecamp::hide_mission(), is_equal(), basecamp::is_hidden(), and basecamp::reveal_mission().
is_equal() [2/2]
bool is_equal (const ui_mission_id & first, const ui_mission_id & second)
Definition at line 564 of file mission_companion.cpp.
 {
     return first.ret == second.ret &&
            is_equal( first.id, second.id );
 }
References ui_mission_id::id, is_equal(), ui_mission_id::ret, and second.
reset_miss_id()
void reset_miss_id (mission_id & miss_id)
Definition at line 404 of file mission_companion.cpp.
 {
     miss_id = {};
 }
Referenced by npc::reset_companion_mission().