Cataclysm DDA: src/mission.cpp File Reference
mission.cpp File Reference
#include "mission.h"
#include <algorithm>
#include <cstdlib>
#include <istream>
#include <iterator>
#include <list>
#include <memory>
#include <new>
#include <numeric>
#include <set>
#include <unordered_map>
#include <utility>
#include "avatar.h"
#include "colony.h"
#include "creature.h"
#include "debug.h"
#include "dialogue_chatbin.h"
#include "enum_conversions.h"
#include "game.h"
#include "inventory.h"
#include "item.h"
#include "item_group.h"
#include "item_stack.h"
#include "kill_tracker.h"
#include "map.h"
#include "map_iterator.h"
#include "monster.h"
#include "npc.h"
#include "npc_class.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "point.h"
#include "requirements.h"
#include "string_formatter.h"
#include "translations.h"
#include "vehicle.h"
#include "vpart_position.h"
Namespaces
io
Macros
#define dbg(x) DebugLog((x),D_GAME) << __FILE__ << ":" << __LINE__ << ": "
Functions
template<>
std::string io::enum_to_string< mission::mission_status > (mission::mission_status data)
Variables
static const efftype_id effect_pet ("pet")
static const efftype_id effect_run ("run")
static const itype_id itype_null ("null")
static const mission_type_id mission_NULL ("NULL")
static std::unordered_map< int, mission > world_missions
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x),D_GAME) << __FILE__ << ":" << __LINE__ << ": "
Definition at line 41 of file mission.cpp.
Variable Documentation
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by mission::wrap_up().
effect_run
const efftype_id effect_run("run") ("run") static
Referenced by mission::wrap_up().
itype_null
const itype_id itype_null("null") ("null") static
Referenced by mission::is_complete(), and mission::wrap_up().
mission_NULL
const mission_type_id mission_NULL("NULL") ("NULL") static
Referenced by mission::mission_id().
world_missions
std::unordered_map<int, mission> world_missions static
Definition at line 77 of file mission.cpp.
Referenced by mission::add_existing(), mission::clear_all(), mission::find(), mission::get_all_active(), mission::on_creature_death(), mission::process_all(), mission::remove_active_world_mission(), mission::reserve_new(), and mission::update_world_missions_character().