Cataclysm DDA: src/mod_tileset.cpp File Reference
mod_tileset.cpp File Reference
#include "mod_tileset.h"
#include <algorithm>
#include <string>
#include "json.h"
Functions
void load_mod_tileset (const JsonObject &jsobj, const std::string_view, const cata_path &base_path, const cata_path &full_path)
void reset_mod_tileset ()
Variables
std::vector< mod_tileset > all_mod_tilesets
Function Documentation
load_mod_tileset()
void load_mod_tileset (const JsonObject & jsobj, const std::string_view , const cata_path & base_path, const cata_path & full_path)
Definition at line 10 of file mod_tileset.cpp.
 {
     // This function only checks whether mod tileset is compatible.
     // Actual sprites are loaded when the main tileset is loaded.
     // As such, most JSON members are skipped here.
     jsobj.allow_omitted_members();
     int new_num_in_file = 1;
     // Check mod tileset num in file
     for( const mod_tileset &mts : all_mod_tilesets ) {
         if( mts.get_full_path() == full_path ) {
             new_num_in_file++;
         }
     }
     all_mod_tilesets.emplace_back( base_path, full_path, new_num_in_file );
     std::vector<std::string> compatibility = jsobj.get_string_array( "compatibility" );
     for( const std::string &compatible_tileset_id : compatibility ) {
         all_mod_tilesets.back().add_compatible_tileset( compatible_tileset_id );
     }
 }
References all_mod_tilesets, JsonObject::allow_omitted_members(), PATH_INFO::base_path(), and JsonObject::get_string_array().
Referenced by DynamicDataLoader::initialize().
reset_mod_tileset()
void reset_mod_tileset ()
Definition at line 33 of file mod_tileset.cpp.
 {
     all_mod_tilesets.clear();
 }
References all_mod_tilesets.
Referenced by DynamicDataLoader::unload_data().
Variable Documentation
all_mod_tilesets
std::vector<mod_tileset> all_mod_tilesets
Definition at line 8 of file mod_tileset.cpp.
Referenced by load_mod_tileset(), and reset_mod_tileset().