Cataclysm DDA: src/mod_manager.cpp File Reference
mod_manager.cpp File Reference
#include "mod_manager.h"
#include <algorithm>
#include <functional>
#include <iterator>
#include <memory>
#include <ostream>
#include <queue>
#include <type_traits>
#include "assign.h"
#include "cata_utility.h"
#include "debug.h"
#include "dependency_tree.h"
#include "filesystem.h"
#include "json.h"
#include "localized_comparator.h"
#include "path_info.h"
#include "string_formatter.h"
#include "worldfactory.h"
Functions
static const std::string MOD_SEARCH_FILE ("modinfo.json")
const std::vector< std::pair< std::string, translation > > & get_mod_list_categories ()
const std::vector< std::pair< std::string, translation > > & get_mod_list_tabs ()
const std::map< std::string, std::string > & get_mod_list_cat_tab ()
static bool compare_mod_by_name_and_category (const MOD_INFORMATION *const a, const MOD_INFORMATION *const b)
Variables
static const mod_id MOD_INFORMATION_dev_default ("dev:default")
static const mod_id MOD_INFORMATION_user_default ("user:default")
Function Documentation
compare_mod_by_name_and_category()
static bool compare_mod_by_name_and_category (const MOD_INFORMATION *const a, const MOD_INFORMATION *const b) static
Definition at line 439 of file mod_manager.cpp.
 {
     return localized_compare( std::make_pair( a->category, a->name() ),
                               std::make_pair( b->category, b->name() ) );
 }
References a, b, and localized_compare.
Referenced by mod_manager::set_usable_mods().
get_mod_list_cat_tab()
const std::map<std::string, std::string>& get_mod_list_cat_tab ()
Definition at line 91 of file mod_manager.cpp.
 {
     static const std::map<std::string, std::string> mod_list_cat_tab = {
         {"item_exclude", "tab_blacklist"},
         {"monster_exclude", "tab_blacklist"},
         {"rebalance", "tab_balance"}
     };
     return mod_list_cat_tab;
 }
Referenced by worldfactory::show_worldgen_tab_modselection().
get_mod_list_categories()
const std::vector<std::pair<std::string, translation> >& get_mod_list_categories ()
Definition at line 58 of file mod_manager.cpp.
 {
     static const std::vector<std::pair<std::string, translation>> mod_list_categories = {
         {"total_conversion", to_translation( "TOTAL CONVERSIONS" )},
         {"content", to_translation( "CORE CONTENT PACKS" )},
         {"items", to_translation( "ITEM ADDITION MODS" )},
         {"creatures", to_translation( "CREATURE MODS" )},
         {"misc_additions", to_translation( "MISC ADDITIONS" )},
         {"buildings", to_translation( "BUILDINGS MODS" )},
         {"vehicles", to_translation( "VEHICLE MODS" )},
         {"rebalance", to_translation( "REBALANCING MODS" )},
         {"magical", to_translation( "MAGICAL MODS" )},
         {"item_exclude", to_translation( "ITEM EXCLUSION MODS" )},
         {"monster_exclude", to_translation( "MONSTER EXCLUSION MODS" )},
         {"graphical", to_translation( "GRAPHICAL MODS" )},
         {"accessibility", to_translation( "ACCESSIBILITY MODS" )},
         {"", to_translation( "NO CATEGORY" )}
     };
     return mod_list_categories;
 }
References to_translation().
Referenced by mod_manager::load_modfile(), and worldfactory::show_worldgen_tab_modselection().
get_mod_list_tabs()
const std::vector<std::pair<std::string, translation> >& get_mod_list_tabs ()
Definition at line 80 of file mod_manager.cpp.
 {
     static const std::vector<std::pair<std::string, translation>> mod_list_tabs = {
         {"tab_default", to_translation( "Default" )},
         {"tab_blacklist", to_translation( "Blacklist" )},
         {"tab_balance", to_translation( "Balance" )}
     };
     return mod_list_tabs;
 }
References to_translation().
Referenced by worldfactory::show_worldgen_tab_modselection().
MOD_SEARCH_FILE()
static const std::string MOD_SEARCH_FILE ("modinfo.json") static
Referenced by mod_manager::copy_mod_contents(), and mod_manager::load_mods_from().
Variable Documentation
MOD_INFORMATION_dev_default
const mod_id MOD_INFORMATION_dev_default("dev:default") ("dev:default") static
Referenced by mod_manager::refresh_mod_list().
MOD_INFORMATION_user_default
const mod_id MOD_INFORMATION_user_default("user:default") ("user:default") static
Referenced by mod_manager::refresh_mod_list().