Cataclysm DDA: src/mod_manager.h File Reference
mod_manager.h File Reference
#include <cstddef>
#include <iosfwd>
#include <map>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "path_info.h"
#include "pimpl.h"
#include "translations.h"
#include "type_id.h"
Classes
struct MOD_INFORMATION
class mod_manager
class mod_ui
Macros
#define CATA_SRC_MOD_MANAGER_H
Functions
const std::vector< std::pair< std::string, translation > > & get_mod_list_categories ()
const std::vector< std::pair< std::string, translation > > & get_mod_list_tabs ()
const std::map< std::string, std::string > & get_mod_list_cat_tab ()
Macro Definition Documentation
CATA_SRC_MOD_MANAGER_H
#define CATA_SRC_MOD_MANAGER_H
Definition at line 3 of file mod_manager.h.
Function Documentation
get_mod_list_cat_tab()
const std::map<std::string, std::string>& get_mod_list_cat_tab ()
Definition at line 91 of file mod_manager.cpp.
 {
     static const std::map<std::string, std::string> mod_list_cat_tab = {
         {"item_exclude", "tab_blacklist"},
         {"monster_exclude", "tab_blacklist"},
         {"rebalance", "tab_balance"}
     };
     return mod_list_cat_tab;
 }
Referenced by worldfactory::show_worldgen_tab_modselection().
get_mod_list_categories()
const std::vector<std::pair<std::string, translation> >& get_mod_list_categories ()
Definition at line 58 of file mod_manager.cpp.
 {
     static const std::vector<std::pair<std::string, translation>> mod_list_categories = {
         {"total_conversion", to_translation( "TOTAL CONVERSIONS" )},
         {"content", to_translation( "CORE CONTENT PACKS" )},
         {"items", to_translation( "ITEM ADDITION MODS" )},
         {"creatures", to_translation( "CREATURE MODS" )},
         {"misc_additions", to_translation( "MISC ADDITIONS" )},
         {"buildings", to_translation( "BUILDINGS MODS" )},
         {"vehicles", to_translation( "VEHICLE MODS" )},
         {"rebalance", to_translation( "REBALANCING MODS" )},
         {"magical", to_translation( "MAGICAL MODS" )},
         {"item_exclude", to_translation( "ITEM EXCLUSION MODS" )},
         {"monster_exclude", to_translation( "MONSTER EXCLUSION MODS" )},
         {"graphical", to_translation( "GRAPHICAL MODS" )},
         {"accessibility", to_translation( "ACCESSIBILITY MODS" )},
         {"", to_translation( "NO CATEGORY" )}
     };
     return mod_list_categories;
 }
References to_translation().
Referenced by mod_manager::load_modfile(), and worldfactory::show_worldgen_tab_modselection().
get_mod_list_tabs()
const std::vector<std::pair<std::string, translation> >& get_mod_list_tabs ()
Definition at line 80 of file mod_manager.cpp.
 {
     static const std::vector<std::pair<std::string, translation>> mod_list_tabs = {
         {"tab_default", to_translation( "Default" )},
         {"tab_blacklist", to_translation( "Blacklist" )},
         {"tab_balance", to_translation( "Balance" )}
     };
     return mod_list_tabs;
 }
References to_translation().
Referenced by worldfactory::show_worldgen_tab_modselection().