Cataclysm DDA: src/monattack.cpp File Reference
monattack.cpp File Reference
#include "monattack.h"
#include <algorithm>
#include <array>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <functional>
#include <list>
#include <map>
#include <memory>
#include <new>
#include <optional>
#include <ostream>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "activity_type.h"
#include "ballistics.h"
#include "bionics.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_assert.h"
#include "character.h"
#include "character_id.h"
#include "character_martial_arts.h"
#include "colony.h"
#include "creature.h"
#include "creature_tracker.h"
#include "damage.h"
#include "debug.h"
#include "dispersion.h"
#include "effect.h"
#include "effect_source.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "explosion.h"
#include "field_type.h"
#include "flag.h"
#include "fungal_effects.h"
#include "game.h"
#include "game_constants.h"
#include "gun_mode.h"
#include "harvest.h"
#include "item.h"
#include "item_stack.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "line.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "martialarts.h"
#include "material.h"
#include "mattack_actors.h"
#include "mattack_common.h"
#include "memorial_logger.h"
#include "messages.h"
#include "mission.h"
#include "mondefense.h"
#include "monfaction.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "npc.h"
#include "output.h"
#include "pathfinding.h"
#include "pimpl.h"
#include "point.h"
#include "projectile.h"
#include "rng.h"
#include "sounds.h"
#include "speech.h"
#include "string_formatter.h"
#include "text_snippets.h"
#include "tileray.h"
#include "timed_event.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "ui_manager.h"
#include "units.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "veh_type.h"
#include "viewer.h"
#include "vpart_position.h"
#include "weighted_list.h"
Classes
struct grenade_helper_struct
Functions
static bool within_visual_range (monster *z, int max_range)
static bool within_target_range (const monster *const z, const Creature *const target, int range)
static Creature * sting_get_target (monster *z, float range=5.0f)
static bool sting_shoot (monster *z, Creature *target, damage_instance &dam, float range)
static npc make_fake_npc (monster *z, int str, int dex, int inte, int per)
template<size_t N = 1>
std::pair< std::array< tripoint,(2 *N+1) *(2 *N+1) >, size_t > find_empty_neighbors (const tripoint &origin)
Find empty spaces around origin within a radius of N.
template<size_t N = 1>
std::pair< std::array< tripoint,(2 *N+1) *(2 *N+1) >, size_t > find_empty_neighbors (const Creature &c)
Find empty spaces around a creature within a radius of N.
static size_t get_random_index (const size_t size)
Get a size_t value in the closed interval [0, size]; a convenience to avoid messy casting.
template<typename Container >
size_t get_random_index (const Container &c)
Get a size_t value in the closed interval [0, c.size() - 1]; a convenience to avoid messy casting.
static bodypart_id body_part_hit_by_plant ()
static bool has_vine_parent (monster *z)
static void poly_keep_speed (monster &mon, const mtype_id &id)
static bool blobify (monster &blob, monster &target)
static void parrot_common (monster *parrot)
static int grenade_helper (monster *const z, Creature *const target, const int dist, const int moves, std::map< itype_id, grenade_helper_struct > data)
Variables
static const activity_id ACT_RELOAD ("ACT_RELOAD")
static const bionic_id bio_uncanny_dodge ("bio_uncanny_dodge")
static const damage_type_id damage_acid ("acid")
static const damage_type_id damage_bash ("bash")
static const damage_type_id damage_cut ("cut")
static const damage_type_id damage_electric ("electric")
static const damage_type_id damage_stab ("stab")
static const efftype_id effect_assisted ("assisted")
static const efftype_id effect_bite ("bite")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_boomered ("boomered")
static const efftype_id effect_controlled ("controlled")
static const efftype_id effect_corroding ("corroding")
static const efftype_id effect_countdown ("countdown")
static const efftype_id effect_darkness ("darkness")
static const efftype_id effect_dazed ("dazed")
static const efftype_id effect_deaf ("deaf")
static const efftype_id effect_dermatik ("dermatik")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_dragging ("dragging")
static const efftype_id effect_eyebot_assisted ("eyebot_assisted")
static const efftype_id effect_eyebot_depleted ("eyebot_depleted")
static const efftype_id effect_fungus ("fungus")
static const efftype_id effect_glowing ("glowing")
static const efftype_id effect_got_checked ("got_checked")
static const efftype_id effect_grabbed ("grabbed")
static const efftype_id effect_grabbing ("grabbing")
static const efftype_id effect_grown_of_fuse ("grown_of_fuse")
static const efftype_id effect_has_bag ("has_bag")
static const efftype_id effect_laserlocked ("laserlocked")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_operating ("operating")
static const efftype_id effect_paid ("paid")
static const efftype_id effect_paralyzepoison ("paralyzepoison")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_raising ("raising")
static const efftype_id effect_rat ("rat")
static const efftype_id effect_shrieking ("shrieking")
static const efftype_id effect_slimed ("slimed")
static const efftype_id effect_social_dissatisfied ("social_dissatisfied")
static const efftype_id effect_stunned ("stunned")
static const efftype_id effect_targeted ("targeted")
static const gun_mode_id gun_mode_AUTO ("AUTO")
static const itype_id itype_120mm_HEAT ("120mm_HEAT")
static const itype_id itype_40x46mm_m433 ("40x46mm_m433")
static const itype_id itype_556 ("556")
static const itype_id itype_anesthetic ("anesthetic")
static const itype_id itype_badge_deputy ("badge_deputy")
static const itype_id itype_badge_detective ("badge_detective")
static const itype_id itype_badge_doctor ("badge_doctor")
static const itype_id itype_badge_marshal ("badge_marshal")
static const itype_id itype_badge_swat ("badge_swat")
static const itype_id itype_bot_c4_hack ("bot_c4_hack")
static const itype_id itype_bot_flashbang_hack ("bot_flashbang_hack")
static const itype_id itype_bot_gasbomb_hack ("bot_gasbomb_hack")
static const itype_id itype_bot_grenade_hack ("bot_grenade_hack")
static const itype_id itype_bot_manhack ("bot_manhack")
static const itype_id itype_bot_mininuke_hack ("bot_mininuke_hack")
static const itype_id itype_bot_pacification_hack ("bot_pacification_hack")
static const itype_id itype_e_handcuffs ("e_handcuffs")
static const json_character_flag json_flag_BIONIC_LIMB ("BIONIC_LIMB")
static const limb_score_id limb_score_grip ("grip")
static const limb_score_id limb_score_reaction ("reaction")
static const material_id material_budget_steel ("budget_steel")
static const material_id material_ch_steel ("ch_steel")
static const material_id material_flesh ("flesh")
static const material_id material_hc_steel ("hc_steel")
static const material_id material_hflesh ("hflesh")
static const material_id material_iflesh ("iflesh")
static const material_id material_iron ("iron")
static const material_id material_lc_steel ("lc_steel")
static const material_id material_mc_steel ("mc_steel")
static const material_id material_qt_steel ("qt_steel")
static const material_id material_steel ("steel")
static const material_id material_veggy ("veggy")
static const material_id material_water ("water")
static const mtype_id mon_biollante ("mon_biollante")
static const mtype_id mon_blob ("mon_blob")
static const mtype_id mon_blob_brain ("mon_blob_brain")
static const mtype_id mon_blob_large ("mon_blob_large")
static const mtype_id mon_blob_small ("mon_blob_small")
static const mtype_id mon_breather ("mon_breather")
static const mtype_id mon_breather_hub ("mon_breather_hub")
static const mtype_id mon_creeper_hub ("mon_creeper_hub")
static const mtype_id mon_creeper_vine ("mon_creeper_vine")
static const mtype_id mon_dermatik ("mon_dermatik")
static const mtype_id mon_fungal_hedgerow ("mon_fungal_hedgerow")
static const mtype_id mon_fungal_tendril ("mon_fungal_tendril")
static const mtype_id mon_fungal_wall ("mon_fungal_wall")
static const mtype_id mon_fungaloid ("mon_fungaloid")
static const mtype_id mon_fungaloid_young ("mon_fungaloid_young")
static const mtype_id mon_headless_dog_thing ("mon_headless_dog_thing")
static const mtype_id mon_hound_tindalos_afterimage ("mon_hound_tindalos_afterimage")
static const mtype_id mon_leech_blossom ("mon_leech_blossom")
static const mtype_id mon_leech_root_drone ("mon_leech_root_drone")
static const mtype_id mon_leech_root_runner ("mon_leech_root_runner")
static const mtype_id mon_leech_stalk ("mon_leech_stalk")
static const mtype_id mon_manhack ("mon_manhack")
static const mtype_id mon_nursebot_defective ("mon_nursebot_defective")
static const mtype_id mon_shadow ("mon_shadow")
static const mtype_id mon_triffid ("mon_triffid")
static const mtype_id mon_turret_searchlight ("mon_turret_searchlight")
static const mtype_id mon_zombie_dancer ("mon_zombie_dancer")
static const mtype_id mon_zombie_gasbag_crawler ("mon_zombie_gasbag_crawler")
static const mtype_id mon_zombie_gasbag_impaler ("mon_zombie_gasbag_impaler")
static const mtype_id mon_zombie_jackson ("mon_zombie_jackson")
static const mtype_id mon_zombie_skeltal_minion ("mon_zombie_skeltal_minion")
static const skill_id skill_gun ("gun")
static const skill_id skill_launcher ("launcher")
static const skill_id skill_melee ("melee")
static const skill_id skill_rifle ("rifle")
static const skill_id skill_unarmed ("unarmed")
static const species_id species_LEECH_PLANT ("LEECH_PLANT")
static const species_id species_SLIME ("SLIME")
static const species_id species_ZOMBIE ("ZOMBIE")
static const ter_str_id ter_t_dirt ("t_dirt")
static const ter_str_id ter_t_dirtmound ("t_dirtmound")
static const ter_str_id ter_t_marloss ("t_marloss")
static const ter_str_id ter_t_root_wall ("t_root_wall")
static const ter_str_id ter_t_tree ("t_tree")
static const ter_str_id ter_t_tree_young ("t_tree_young")
static const ter_str_id ter_t_underbrush ("t_underbrush")
static const trait_id trait_ACIDBLOOD ("ACIDBLOOD")
static const trait_id trait_MARLOSS ("MARLOSS")
static const trait_id trait_MARLOSS_BLUE ("MARLOSS_BLUE")
static const trait_id trait_PARAIMMUNE ("PARAIMMUNE")
static const trait_id trait_PROF_CHURL ("PROF_CHURL")
static const trait_id trait_PROF_FED ("PROF_FED")
static const trait_id trait_PROF_PD_DET ("PROF_PD_DET")
static const trait_id trait_PROF_POLICE ("PROF_POLICE")
static const trait_id trait_PROF_SWAT ("PROF_SWAT")
static const trait_id trait_TAIL_CATTLE ("TAIL_CATTLE")
static const trait_id trait_THRESH_MARLOSS ("THRESH_MARLOSS")
static const trait_id trait_THRESH_MYCUS ("THRESH_MYCUS")
Function Documentation
blobify()
static bool blobify (monster & blob, monster & target) static
Definition at line 2464 of file monattack.cpp.
 {
     add_msg_if_player_sees( target, m_warning, _( "%s is engulfed by %s!" ),
                             target.disp_name(), blob.disp_name() );
     switch( target.get_size() ) {
         case creature_size::tiny:
             // Just consume it
             target.set_hp( 0 );
             blob.set_speed_base( blob.get_speed_base() + 5 );
             return false;
         case creature_size::small:
             target.poly( mon_blob_small );
             break;
         case creature_size::medium:
             target.poly( mon_blob );
             break;
         case creature_size::large:
             target.poly( mon_blob_large );
             break;
         case creature_size::huge:
             // No polymorphing huge stuff
             target.add_effect( effect_slimed, rng( 2_turns, 10_turns ) );
             break;
         default:
             debugmsg( "Tried to blobify %s with invalid size: %d",
                       target.disp_name(), static_cast<int>( target.get_size() ) );
             return false;
     }
     target.make_ally( blob );
     return true;
 }
References _, Creature::add_effect(), add_msg_if_player_sees(), debugmsg, monster::disp_name(), effect_slimed, monster::get_size(), Creature::get_speed_base(), huge, large, m_warning, monster::make_ally(), medium, mon_blob, mon_blob_large, mon_blob_small, monster::poly(), rng(), monster::set_hp(), Creature::set_speed_base(), small, and tiny.
Referenced by mattack::formblob().
body_part_hit_by_plant()
static bodypart_id body_part_hit_by_plant () static
Definition at line 1609 of file monattack.cpp.
 {
     bodypart_id hit;
     if( one_in( 2 ) ) {
         hit = bodypart_id( "leg_l" );
     } else {
         hit = bodypart_id( "leg_r" );
     }
     if( one_in( 4 ) ) {
         hit = bodypart_id( "torso" );
     } else if( one_in( 2 ) ) {
         if( one_in( 2 ) ) {
             hit = bodypart_id( "foot_l" );
         } else {
             hit = bodypart_id( "foot_r" );
         }
     }
     return hit;
 }
References one_in().
Referenced by mattack::fungus_fortify(), and mattack::growplants().
find_empty_neighbors() [1/2]
template<size_t N = 1> std::pair< std::array < tripoint, (2 * N + 1) * (2 * N + 1) >, size_t > find_empty_neighbors (const Creature & c)
Find empty spaces around a creature within a radius of N.
See also
find_empty_neighbors
Definition at line 1402 of file monattack.cpp.
 {
     return find_empty_neighbors<N>( c.pos() );
 }
References c.
find_empty_neighbors() [2/2]
template<size_t N = 1> std::pair< std::array < tripoint, (2 * N + 1) * (2 * N + 1) >, size_t > find_empty_neighbors (const tripoint & origin)
Find empty spaces around origin within a radius of N.
Returns
a pair with first = array<tripoint, area>; area = (2*N + 1)^2. second = the number of empty spaces found.
Definition at line 1379 of file monattack.cpp.
 {
     constexpr int r = static_cast<int>( N );
     std::pair < std::array < tripoint, ( 2 * N + 1 )*( 2 * N + 1 ) >, size_t > result;
     for( const tripoint &tmp : get_map().points_in_radius( origin, r ) ) {
         if( g->is_empty( tmp ) ) {
             result.first[result.second++] = tmp;
         }
     }
     return result;
 }
References g, get_map(), and map::points_in_radius().
Referenced by grenade_helper(), and mattack::science().
get_random_index() [1/2]
template<typename Container > size_t get_random_index (const Container & c)
Get a size_t value in the closed interval [0, c.size() - 1]; a convenience to avoid messy casting.
Definition at line 1421 of file monattack.cpp.
 {
     return get_random_index( c.size() );
 }
References c, and get_random_index().
get_random_index() [2/2]
static size_t get_random_index (const size_t size) static
Get a size_t value in the closed interval [0, size]; a convenience to avoid messy casting.
Definition at line 1411 of file monattack.cpp.
 {
     return static_cast<size_t>( rng( 0, static_cast<int>( size - 1 ) ) );
 }
References rng(), and om_direction::size.
Referenced by get_random_index(), grenade_helper(), and mattack::science().
grenade_helper()
static int grenade_helper (monster *const z, Creature *const target, const int dist, const int moves, std::map< itype_id, grenade_helper_struct > data) static
Definition at line 5259 of file monattack.cpp.
 {
     // Can't do anything if we can't act
     if( !z->can_act() ) {
         return 0;
     }
     // Too far or we can't target them
     if( !within_target_range( z, target, dist ) ) {
         return 0;
     }
     // We need an open space for these attacks
     const auto empty_neighbors = find_empty_neighbors( *z );
     const size_t empty_neighbor_count = empty_neighbors.second;
     if( !empty_neighbor_count ) {
         return 0;
     }
     // Find how much ammo we currently have
     int curr_ammo = 0;
     for( const std::pair<const itype_id, int> &amm : z->ammo ) {
         curr_ammo += amm.second;
     }
     if( curr_ammo == 0 ) {
         // We've run out of ammo, get angry and toggle the special off.
         z->anger = 100;
         return -1;
     }
     // Grab all attacks that pass their chance check
     weighted_float_list<itype_id> possible_attacks;
     for( const std::pair<const itype_id, int> &amm : z->ammo ) {
         if( amm.second > 0 ) {
             possible_attacks.add( amm.first, 1.0 / data[amm.first].chance );
         }
     }
     itype_id att = *possible_attacks.pick();
     z->mod_moves( -moves );
     z->ammo[att]--;
     // if the player can see it
     if( get_player_view().sees( *z ) ) {
         if( data[att].message.empty() ) {
             add_msg_debug( debugmode::DF_MATTACK, "Invalid ammo message in grenadier special." );
         } else {
             add_msg( m_bad, data[att].message, z->name() );
         }
     }
     // Get our monster type
     const itype *bomb_type = item::find_type( att );
     const use_function *usage = bomb_type->get_use( "place_monster" );
     if( usage == nullptr ) {
         // Invalid bomb item usage, Toggle this special off so we stop processing
         add_msg_debug( debugmode::DF_MATTACK, "Invalid bomb item usage in grenadier special for %s.",
                        z->name() );
         return -1;
     }
     const place_monster_iuse *actor = dynamic_cast<const place_monster_iuse *>
                                       ( usage->get_actor_ptr() );
     if( actor == nullptr ) {
         // Invalid bomb item, Toggle this special off so we stop processing
         add_msg_debug( debugmode::DF_MATTACK, "Invalid bomb type in grenadier special for %s.", z->name() );
         return -1;
     }
     const tripoint where = empty_neighbors.first[get_random_index( empty_neighbor_count )];
     if( monster *const hack = g->place_critter_at( actor->mtypeid, where ) ) {
         hack->make_ally( *z );
     }
     return 1;
 }
References weighted_list< W, T >::add(), add_msg(), add_msg_debug, monster::ammo, monster::anger, monster::can_act(), debugmode::DF_MATTACK, find_empty_neighbors(), item::find_type(), g, use_function::get_actor_ptr(), get_player_view(), get_random_index(), itype::get_use(), m_bad, mapgen_defer::message, Creature::mod_moves(), place_monster_iuse::mtypeid, monster::name(), weighted_list< W, T >::pick(), and within_target_range().
Referenced by mattack::grenadier(), and mattack::grenadier_elite().
has_vine_parent()
static bool has_vine_parent (monster * z) static
Definition at line 1746 of file monattack.cpp.
 {
     if( !z->has_dest() || !get_map().inbounds( z->get_dest() ) ) {
         return false;
     }
     const monster *parent = get_creature_tracker().creature_at<monster>( z->get_dest() );
     return parent != nullptr && parent->type->id == mon_creeper_hub;
 }
References creature_tracker::creature_at(), get_creature_tracker(), monster::get_dest(), get_map(), monster::has_dest(), mtype::id, mon_creeper_hub, and monster::type.
Referenced by mattack::vine().
make_fake_npc()
static npc make_fake_npc (monster * z, int str, int dex, int inte, int per) static
Definition at line 314 of file monattack.cpp.
 {
     npc tmp;
     tmp.name = _( "The " ) + z->name();
     tmp.set_fake( true );
     tmp.recoil = 0;
     tmp.setpos( z->pos() );
     tmp.str_cur = str;
     tmp.dex_cur = dex;
     tmp.int_cur = inte;
     tmp.per_cur = per;
     if( z->friendly != 0 ) {
         tmp.set_attitude( NPCATT_FOLLOW );
     } else {
         tmp.set_attitude( NPCATT_KILL );
     }
     return tmp;
 }
References _, Character::dex_cur, monster::friendly, Character::int_cur, Character::name, monster::name(), NPCATT_FOLLOW, NPCATT_KILL, Character::per_cur, Creature::pos(), Character::recoil, npc::set_attitude(), Creature::set_fake(), Creature::setpos(), and Character::str_cur.
Referenced by mattack::frag(), mattack::rifle(), and mattack::tankgun().
parrot_common()
static void parrot_common (monster * parrot) static
Definition at line 4239 of file monattack.cpp.
 {
     // It takes a while
     parrot->mod_moves( -to_moves<int>( 1_seconds ) );
     const SpeechBubble &speech = get_speech( parrot->type->id.str() );
     sounds::sound( parrot->pos(), speech.volume, sounds::sound_t::speech, speech.text.translated(),
                    false, "speech", parrot->type->id.str() );
 }
References get_speech(), mattack::parrot(), sounds::sound(), sounds::speech, and speech.
Referenced by mattack::parrot(), and mattack::parrot_at_danger().
poly_keep_speed()
static void poly_keep_speed (monster & mon, const mtype_id & id) static
Definition at line 2454 of file monattack.cpp.
 {
     // Retain old speed after polymorph
     // This prevents blobs regenerating speed through polymorphs
     // and thus replicating indefinitely, covering entire map
     const int old_speed = mon.get_speed_base();
     mon.poly( id );
     mon.set_speed_base( old_speed );
 }
References Creature::get_speed_base(), monster::poly(), and Creature::set_speed_base().
Referenced by mattack::formblob().
sting_get_target()
static Creature* sting_get_target (monster * z, float range = 5.0f) static
Definition at line 259 of file monattack.cpp.
 {
     Creature *target = z->attack_target();
     if( target == nullptr ) {
         return nullptr;
     }
     // Can't see/reach target, no attack
     if( !z->sees( *target ) ||
         !get_map().clear_path( z->pos(), target->pos(), range, 1, 100 ) ) {
         return nullptr;
     }
     return rl_dist( z->pos(), target->pos() ) <= range ? target : nullptr;
 }
References monster::attack_target(), get_map(), Creature::pos(), rl_dist(), and Creature::sees().
Referenced by mattack::gene_sting(), and mattack::para_sting().
sting_shoot()
static bool sting_shoot (monster * z, Creature * target, damage_instance & dam, float range) static
Definition at line 276 of file monattack.cpp.
 {
     if( target->uncanny_dodge() ) {
         target->add_msg_if_player( m_bad, _( "The %s shoots a dart but you dodge it." ),
                                    z->name() );
         return false;
     }
     projectile proj;
     proj.speed = 10;
     proj.range = range;
     proj.impact.add( dam );
     proj.proj_effects.insert( "NO_OVERSHOOT" );
     dealt_projectile_attack atk = projectile_attack( proj, z->pos(), target->pos(),
                                   dispersion_sources{ 500 }, z );
     if( atk.dealt_dam.total_damage() > 0 ) {
         target->add_msg_if_player( m_bad, _( "The %s shoots a dart into you!" ), z->name() );
         // whether this function returns true determines whether it applies a status effect like paralysis or mutation
         if( atk.dealt_dam.bp_hit->has_flag( json_flag_BIONIC_LIMB ) ) {
             return false;
         } else {
             return true;
         }
     } else {
         if( atk.missed_by == 1 ) {
             target->add_msg_if_player( m_good,
                                        _( "The %s shoots a dart at you, but misses!" ),
                                        z->name() );
         } else {
             target->add_msg_if_player( m_good,
                                        _( "The %s shoots a dart but it bounces off your armor." ),
                                        z->name() );
         }
         return false;
     }
 }
References _, damage_instance::add(), Creature::add_msg_if_player(), dealt_damage_instance::bp_hit, dealt_projectile_attack::dealt_dam, body_part_type::has_flag(), projectile::impact, json_flag_BIONIC_LIMB, m_bad, m_good, dealt_projectile_attack::missed_by, monster::name(), Creature::pos(), projectile::proj_effects, projectile_attack(), projectile::range, projectile::speed, dealt_damage_instance::total_damage(), and Creature::uncanny_dodge().
Referenced by mattack::gene_sting(), and mattack::para_sting().
within_target_range()
static bool within_target_range (const monster *const z, const Creature *const target, int range) static
Definition at line 252 of file monattack.cpp.
 {
     return target != nullptr &&
            rl_dist( z->pos(), target->pos() ) <= range &&
            z->sees( *target );
 }
References Creature::pos(), rl_dist(), and Creature::sees().
Referenced by grenade_helper(), mattack::kamikaze(), mattack::resurrect(), mattack::suicide(), and mattack::upgrade().
within_visual_range()
static bool within_visual_range (monster * z, int max_range) static
Definition at line 245 of file monattack.cpp.
 {
     Character &player_character = get_player_character();
     return !( rl_dist( z->pos(), player_character.pos() ) > max_range ||
               !z->sees( player_character ) );
 }
References get_player_character(), Creature::pos(), rl_dist(), and Creature::sees().
Referenced by mattack::flamethrower(), and mattack::photograph().
Variable Documentation
ACT_RELOAD
const activity_id ACT_RELOAD("ACT_RELOAD") ("ACT_RELOAD") static
Referenced by mattack::pull_metal_weapon().
bio_uncanny_dodge
const bionic_id bio_uncanny_dodge("bio_uncanny_dodge") ("bio_uncanny_dodge") static
Referenced by mattack::riotbot().
damage_acid
const damage_type_id damage_acid("acid") ("acid") static
Referenced by mattack::acid(), mattack::acid_accurate(), mattack::acid_barf(), and mattack::spit_sap().
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by mattack::bio_op_takedown(), mattack::flesh_golem(), mattack::lunge(), mattack::pull_metal_weapon(), mattack::taze(), and mattack::vine().
damage_cut
const damage_type_id damage_cut("cut") ("cut") static
Referenced by mattack::dermatik(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), and mattack::vine().
damage_electric
const damage_type_id damage_electric("electric") ("electric") static
Referenced by mattack::taze().
damage_stab
const damage_type_id damage_stab("stab") ("stab") static
Referenced by mattack::bio_op_impale(), mattack::evolve_kill_strike(), mattack::fungus_fortify(), mattack::gene_sting(), mattack::growplants(), mattack::para_sting(), and mattack::stretch_attack().
effect_assisted
const efftype_id effect_assisted("assisted") ("assisted") static
Referenced by mattack::nurse_assist().
effect_bite
const efftype_id effect_bite("bite") ("bite") static
Referenced by mattack::slimespring().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by mattack::bio_op_impale(), and mattack::slimespring().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
Referenced by mattack::acid_barf().
effect_boomered
const efftype_id effect_boomered("boomered") ("boomered") static
Referenced by mattack::boomer(), and mattack::boomer_glow().
effect_controlled
const efftype_id effect_controlled("controlled") ("controlled") static
Referenced by mattack::callblobs(), and mattack::jackson().
effect_corroding
const efftype_id effect_corroding("corroding") ("corroding") static
Referenced by mattack::acid_barf().
effect_countdown
const efftype_id effect_countdown("countdown") ("countdown") static
Referenced by mattack::kamikaze(), and mattack::nurse_check_up().
effect_darkness
const efftype_id effect_darkness("darkness") ("darkness") static
Referenced by mattack::darkman().
effect_dazed
const efftype_id effect_dazed("dazed") ("dazed") static
Referenced by mattack::shriek_stun().
effect_deaf
const efftype_id effect_deaf("deaf") ("deaf") static
Referenced by mattack::shriek_stun().
effect_dermatik
const efftype_id effect_dermatik("dermatik") ("dermatik") static
Referenced by mattack::dermatik().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by mattack::bio_op_takedown(), mattack::flesh_golem(), and mattack::lunge().
effect_dragging
const efftype_id effect_dragging("dragging") ("dragging") static
Referenced by mattack::nurse_operate().
effect_eyebot_assisted
const efftype_id effect_eyebot_assisted("eyebot_assisted") ("eyebot_assisted") static
Referenced by mattack::photograph().
effect_eyebot_depleted
const efftype_id effect_eyebot_depleted("eyebot_depleted") ("eyebot_depleted") static
Referenced by mattack::photograph().
effect_fungus
const efftype_id effect_fungus("fungus") ("fungus") static
Referenced by mattack::fungus_bristle(), mattack::fungus_fortify(), and mattack::fungus_inject().
effect_glowing
const efftype_id effect_glowing("glowing") ("glowing") static
Referenced by mattack::boomer_glow().
effect_got_checked
const efftype_id effect_got_checked("got_checked") ("got_checked") static
Referenced by mattack::nurse_check_up().
effect_grabbed
const efftype_id effect_grabbed("grabbed") ("grabbed") static
Referenced by mattack::nurse_operate().
effect_grabbing
const efftype_id effect_grabbing("grabbing") ("grabbing") static
Referenced by mattack::smash().
effect_grown_of_fuse
const efftype_id effect_grown_of_fuse("grown_of_fuse") ("grown_of_fuse") static
Referenced by mattack::zombie_fuse().
effect_has_bag
const efftype_id effect_has_bag("has_bag") ("has_bag") static
Referenced by mattack::check_money_left().
effect_laserlocked
const efftype_id effect_laserlocked("laserlocked") ("laserlocked") static
Referenced by mattack::frag(), and mattack::tankgun().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by mattack::flame().
effect_operating
const efftype_id effect_operating("operating") ("operating") static
Referenced by mattack::nurse_operate().
effect_paid
const efftype_id effect_paid("paid") ("paid") static
Referenced by mattack::check_money_left().
effect_paralyzepoison
const efftype_id effect_paralyzepoison("paralyzepoison") ("paralyzepoison") static
Referenced by mattack::para_sting().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by mattack::check_money_left().
effect_raising
const efftype_id effect_raising("raising") ("raising") static
Referenced by mattack::resurrect().
effect_rat
const efftype_id effect_rat("rat") ("rat") static
Referenced by mattack::ratking().
effect_shrieking
const efftype_id effect_shrieking("shrieking") ("shrieking") static
Referenced by mattack::parrot(), mattack::shriek_alert(), and mattack::shriek_stun().
effect_slimed
const efftype_id effect_slimed("slimed") ("slimed") static
Referenced by blobify(), and mattack::formblob().
effect_social_dissatisfied
const efftype_id effect_social_dissatisfied("social_dissatisfied") ("social_dissatisfied") static
Referenced by mattack::slimespring().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by mattack::bio_op_takedown().
effect_targeted
const efftype_id effect_targeted("targeted") ("targeted") static
Referenced by mattack::frag(), mattack::rifle(), and mattack::tankgun().
gun_mode_AUTO
const gun_mode_id gun_mode_AUTO("AUTO") ("AUTO") static
Referenced by mattack::frag(), mattack::rifle(), and mattack::tankgun().
itype_120mm_HEAT
const itype_id itype_120mm_HEAT("120mm_HEAT") ("120mm_HEAT") static
Referenced by mattack::tankgun().
itype_40x46mm_m433
const itype_id itype_40x46mm_m433("40x46mm_m433") ("40x46mm_m433") static
Referenced by mattack::frag().
itype_556
const itype_id itype_556("556") ("556") static
Referenced by mattack::rifle().
itype_anesthetic
const itype_id itype_anesthetic("anesthetic") ("anesthetic") static
Referenced by mattack::nurse_operate().
itype_badge_deputy
const itype_id itype_badge_deputy("badge_deputy") ("badge_deputy") static
Referenced by mattack::photograph().
itype_badge_detective
const itype_id itype_badge_detective("badge_detective") ("badge_detective") static
Referenced by mattack::photograph().
itype_badge_doctor
const itype_id itype_badge_doctor("badge_doctor") ("badge_doctor") static
Referenced by mattack::nurse_assist(), and mattack::nurse_operate().
itype_badge_marshal
const itype_id itype_badge_marshal("badge_marshal") ("badge_marshal") static
Referenced by mattack::photograph().
itype_badge_swat
const itype_id itype_badge_swat("badge_swat") ("badge_swat") static
Referenced by mattack::photograph().
itype_bot_c4_hack
const itype_id itype_bot_c4_hack("bot_c4_hack") ("bot_c4_hack") static
Referenced by mattack::grenadier(), and mattack::grenadier_elite().
itype_bot_flashbang_hack
const itype_id itype_bot_flashbang_hack("bot_flashbang_hack") ("bot_flashbang_hack") static
Referenced by mattack::grenadier(), and mattack::grenadier_elite().
itype_bot_gasbomb_hack
const itype_id itype_bot_gasbomb_hack("bot_gasbomb_hack") ("bot_gasbomb_hack") static
Referenced by mattack::grenadier(), and mattack::grenadier_elite().
itype_bot_grenade_hack
const itype_id itype_bot_grenade_hack("bot_grenade_hack") ("bot_grenade_hack") static
Referenced by mattack::grenadier_elite().
itype_bot_manhack
const itype_id itype_bot_manhack("bot_manhack") ("bot_manhack") static
Referenced by mattack::science().
itype_bot_mininuke_hack
const itype_id itype_bot_mininuke_hack("bot_mininuke_hack") ("bot_mininuke_hack") static
Referenced by mattack::grenadier_elite().
itype_bot_pacification_hack
const itype_id itype_bot_pacification_hack("bot_pacification_hack") ("bot_pacification_hack") static
Referenced by mattack::grenadier().
itype_e_handcuffs
const itype_id itype_e_handcuffs("e_handcuffs") ("e_handcuffs") static
Referenced by mattack::copbot(), mattack::photograph(), and mattack::riotbot().
json_flag_BIONIC_LIMB
const json_character_flag json_flag_BIONIC_LIMB("BIONIC_LIMB") ("BIONIC_LIMB") static
Referenced by mattack::dermatik(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), and sting_shoot().
limb_score_grip
const limb_score_id limb_score_grip("grip") ("grip") static
Referenced by mattack::bio_op_disarm(), and mattack::pull_metal_weapon().
limb_score_reaction
const limb_score_id limb_score_reaction("reaction") ("reaction") static
Referenced by mattack::bio_op_disarm().
material_budget_steel
const material_id material_budget_steel("budget_steel") ("budget_steel") static
Referenced by mattack::pull_metal_weapon().
material_ch_steel
const material_id material_ch_steel("ch_steel") ("ch_steel") static
Referenced by mattack::pull_metal_weapon().
material_flesh
const material_id material_flesh("flesh") ("flesh") static
Referenced by mattack::absorb_meat(), mattack::eat_carrion(), and mattack::formblob().
material_hc_steel
const material_id material_hc_steel("hc_steel") ("hc_steel") static
Referenced by mattack::pull_metal_weapon().
material_hflesh
const material_id material_hflesh("hflesh") ("hflesh") static
Referenced by mattack::absorb_meat(), and mattack::eat_carrion().
material_iflesh
const material_id material_iflesh("iflesh") ("iflesh") static
Referenced by mattack::eat_carrion(), and mattack::formblob().
material_iron
const material_id material_iron("iron") ("iron") static
Referenced by mattack::pull_metal_weapon().
material_lc_steel
const material_id material_lc_steel("lc_steel") ("lc_steel") static
Referenced by mattack::pull_metal_weapon().
material_mc_steel
const material_id material_mc_steel("mc_steel") ("mc_steel") static
Referenced by mattack::pull_metal_weapon().
material_qt_steel
const material_id material_qt_steel("qt_steel") ("qt_steel") static
Referenced by mattack::pull_metal_weapon().
material_steel
const material_id material_steel("steel") ("steel") static
Referenced by mattack::pull_metal_weapon().
material_veggy
const material_id material_veggy("veggy") ("veggy") static
Referenced by mattack::eat_carrion(), and mattack::formblob().
material_water
const material_id material_water("water") ("water") static
Referenced by mattack::eat_crop(), and mattack::eat_food().
mon_biollante
const mtype_id mon_biollante("mon_biollante") ("mon_biollante") static
Referenced by mattack::triffid_heartbeat().
mon_blob
const mtype_id mon_blob("mon_blob") ("mon_blob") static
Referenced by blobify(), and mattack::formblob().
mon_blob_brain
const mtype_id mon_blob_brain("mon_blob_brain") ("mon_blob_brain") static
Referenced by mattack::callblobs(), and mattack::formblob().
mon_blob_large
const mtype_id mon_blob_large("mon_blob_large") ("mon_blob_large") static
Referenced by blobify(), and mattack::formblob().
mon_blob_small
const mtype_id mon_blob_small("mon_blob_small") ("mon_blob_small") static
Referenced by blobify(), and mattack::formblob().
mon_breather
const mtype_id mon_breather("mon_breather") ("mon_breather") static
Referenced by mattack::breathe().
mon_breather_hub
const mtype_id mon_breather_hub("mon_breather_hub") ("mon_breather_hub") static
Referenced by mattack::breathe().
mon_creeper_hub
const mtype_id mon_creeper_hub("mon_creeper_hub") ("mon_creeper_hub") static
Referenced by has_vine_parent(), and mattack::triffid_heartbeat().
mon_creeper_vine
const mtype_id mon_creeper_vine("mon_creeper_vine") ("mon_creeper_vine") static
Referenced by mattack::grow_vine(), and mattack::vine().
mon_dermatik
const mtype_id mon_dermatik("mon_dermatik") ("mon_dermatik") static
Referenced by mattack::dermatik_growth().
mon_fungal_hedgerow
const mtype_id mon_fungal_hedgerow("mon_fungal_hedgerow") ("mon_fungal_hedgerow") static
Referenced by mattack::fungus_fortify().
mon_fungal_tendril
const mtype_id mon_fungal_tendril("mon_fungal_tendril") ("mon_fungal_tendril") static
Referenced by mattack::fungus_fortify().
mon_fungal_wall
const mtype_id mon_fungal_wall("mon_fungal_wall") ("mon_fungal_wall") static
Referenced by mattack::fungus_sprout().
mon_fungaloid
const mtype_id mon_fungaloid("mon_fungaloid") ("mon_fungaloid") static
Referenced by mattack::fungus_growth().
mon_fungaloid_young
const mtype_id mon_fungaloid_young("mon_fungaloid_young") ("mon_fungaloid_young") static
Referenced by mattack::plant().
mon_headless_dog_thing
const mtype_id mon_headless_dog_thing("mon_headless_dog_thing") ("mon_headless_dog_thing") static
Referenced by mattack::dogthing().
mon_hound_tindalos_afterimage
const mtype_id mon_hound_tindalos_afterimage("mon_hound_tindalos_afterimage") ("mon_hound_tindalos_afterimage") static
Referenced by mattack::tindalos_teleport().
mon_leech_blossom
const mtype_id mon_leech_blossom("mon_leech_blossom") ("mon_leech_blossom") static
Referenced by mattack::mon_leech_evolution().
mon_leech_root_drone
const mtype_id mon_leech_root_drone("mon_leech_root_drone") ("mon_leech_root_drone") static
Referenced by mattack::leech_spawner().
mon_leech_root_runner
const mtype_id mon_leech_root_runner("mon_leech_root_runner") ("mon_leech_root_runner") static
Referenced by mattack::leech_spawner().
mon_leech_stalk
const mtype_id mon_leech_stalk("mon_leech_stalk") ("mon_leech_stalk") static
Referenced by mattack::leech_spawner().
mon_manhack
const mtype_id mon_manhack("mon_manhack") ("mon_manhack") static
Referenced by mattack::science().
mon_nursebot_defective
const mtype_id mon_nursebot_defective("mon_nursebot_defective") ("mon_nursebot_defective") static
Referenced by mattack::nurse_operate().
mon_shadow
const mtype_id mon_shadow("mon_shadow") ("mon_shadow") static
Referenced by mattack::darkman().
mon_triffid
const mtype_id mon_triffid("mon_triffid") ("mon_triffid") static
Referenced by mattack::triffid_growth(), and mattack::triffid_heartbeat().
mon_turret_searchlight
const mtype_id mon_turret_searchlight("mon_turret_searchlight") ("mon_turret_searchlight") static
Referenced by mattack::searchlight().
mon_zombie_dancer
const mtype_id mon_zombie_dancer("mon_zombie_dancer") ("mon_zombie_dancer") static
Referenced by mattack::jackson().
mon_zombie_gasbag_crawler
const mtype_id mon_zombie_gasbag_crawler("mon_zombie_gasbag_crawler") ("mon_zombie_gasbag_crawler") static
Referenced by mattack::flesh_tendril().
mon_zombie_gasbag_impaler
const mtype_id mon_zombie_gasbag_impaler("mon_zombie_gasbag_impaler") ("mon_zombie_gasbag_impaler") static
Referenced by mattack::flesh_tendril().
mon_zombie_jackson
const mtype_id mon_zombie_jackson("mon_zombie_jackson") ("mon_zombie_jackson") static
Referenced by mattack::jackson().
mon_zombie_skeltal_minion
const mtype_id mon_zombie_skeltal_minion("mon_zombie_skeltal_minion") ("mon_zombie_skeltal_minion") static
Referenced by mattack::doot().
skill_gun
const skill_id skill_gun("gun") ("gun") static
Referenced by mattack::frag(), mattack::rifle(), and mattack::tankgun().
skill_launcher
const skill_id skill_launcher("launcher") ("launcher") static
Referenced by mattack::frag(), and mattack::tankgun().
skill_melee
const skill_id skill_melee("melee") ("melee") static
Referenced by mattack::bio_op_disarm(), mattack::dermatik(), and mattack::pull_metal_weapon().
skill_rifle
const skill_id skill_rifle("rifle") ("rifle") static
Referenced by mattack::rifle().
skill_unarmed
const skill_id skill_unarmed("unarmed") ("unarmed") static
Referenced by mattack::dermatik().
species_LEECH_PLANT
const species_id species_LEECH_PLANT("LEECH_PLANT") ("LEECH_PLANT") static
Referenced by mattack::leech_spawner(), and mattack::mon_leech_evolution().
species_SLIME
const species_id species_SLIME("SLIME") ("SLIME") static
Referenced by mattack::callblobs(), and mattack::formblob().
species_ZOMBIE
const species_id species_ZOMBIE("ZOMBIE") ("ZOMBIE") static
Referenced by mattack::jackson(), and mattack::resurrect().
ter_t_dirt
const ter_str_id ter_t_dirt("t_dirt") ("t_dirt") static
Referenced by mattack::graze(), and mattack::triffid_heartbeat().
ter_t_dirtmound
const ter_str_id ter_t_dirtmound("t_dirtmound") ("t_dirtmound") static
Referenced by mattack::growplants().
ter_t_marloss
const ter_str_id ter_t_marloss("t_marloss") ("t_marloss") static
Referenced by mattack::fungus_fortify().
ter_t_root_wall
const ter_str_id ter_t_root_wall("t_root_wall") ("t_root_wall") static
Referenced by mattack::triffid_heartbeat().
ter_t_tree
const ter_str_id ter_t_tree("t_tree") ("t_tree") static
Referenced by mattack::growplants().
ter_t_tree_young
const ter_str_id ter_t_tree_young("t_tree_young") ("t_tree_young") static
Referenced by mattack::growplants().
ter_t_underbrush
const ter_str_id ter_t_underbrush("t_underbrush") ("t_underbrush") static
Referenced by mattack::growplants().
trait_ACIDBLOOD
const trait_id trait_ACIDBLOOD("ACIDBLOOD") ("ACIDBLOOD") static
Referenced by mattack::dermatik().
trait_MARLOSS
const trait_id trait_MARLOSS("MARLOSS") ("MARLOSS") static
Referenced by mattack::fungus_fortify(), and mattack::fungus_inject().
trait_MARLOSS_BLUE
const trait_id trait_MARLOSS_BLUE("MARLOSS_BLUE") ("MARLOSS_BLUE") static
Referenced by mattack::fungus_fortify(), and mattack::fungus_inject().
trait_PARAIMMUNE
const trait_id trait_PARAIMMUNE("PARAIMMUNE") ("PARAIMMUNE") static
Referenced by mattack::dermatik().
trait_PROF_CHURL
const trait_id trait_PROF_CHURL("PROF_CHURL") ("PROF_CHURL") static
Referenced by mattack::frag().
trait_PROF_FED
const trait_id trait_PROF_FED("PROF_FED") ("PROF_FED") static
Referenced by mattack::photograph().
trait_PROF_PD_DET
const trait_id trait_PROF_PD_DET("PROF_PD_DET") ("PROF_PD_DET") static
Referenced by mattack::photograph().
trait_PROF_POLICE
const trait_id trait_PROF_POLICE("PROF_POLICE") ("PROF_POLICE") static
Referenced by mattack::photograph().
trait_PROF_SWAT
const trait_id trait_PROF_SWAT("PROF_SWAT") ("PROF_SWAT") static
Referenced by mattack::photograph().
trait_TAIL_CATTLE
const trait_id trait_TAIL_CATTLE("TAIL_CATTLE") ("TAIL_CATTLE") static
Referenced by mattack::dermatik().
trait_THRESH_MARLOSS
const trait_id trait_THRESH_MARLOSS("THRESH_MARLOSS") ("THRESH_MARLOSS") static
Referenced by mattack::fungus_bristle(), mattack::fungus_fortify(), and mattack::fungus_inject().
trait_THRESH_MYCUS
const trait_id trait_THRESH_MYCUS("THRESH_MYCUS") ("THRESH_MYCUS") static
Referenced by mattack::fungus_bristle(), mattack::fungus_fortify(), and mattack::fungus_inject().