Cataclysm DDA: src/mondeath.cpp File Reference
mondeath.cpp File Reference
#include "mondeath.h"
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <functional>
#include <iosfwd>
#include <list>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "calendar.h"
#include "character.h"
#include "colony.h"
#include "creature.h"
#include "debug.h"
#include "enums.h"
#include "explosion.h"
#include "field_type.h"
#include "fungal_effects.h"
#include "game.h"
#include "harvest.h"
#include "item_stack.h"
#include "itype.h"
#include "kill_tracker.h"
#include "line.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "mattack_actors.h"
#include "mattack_common.h"
#include "messages.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "point.h"
#include "rng.h"
#include "sounds.h"
#include "string_formatter.h"
#include "timed_event.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "value_ptr.h"
#include "viewer.h"
Functions
static void scatter_chunks (const itype_id &chunk_name, int chunk_amt, monster &z, int distance, int pile_size=1)
item_location make_mon_corpse (monster &z, int damageLvl)
Variables
static const efftype_id effect_critter_underfed ("critter_underfed")
static const efftype_id effect_no_ammo ("no_ammo")
static const harvest_drop_type_id harvest_drop_bone ("bone")
static const harvest_drop_type_id harvest_drop_flesh ("flesh")
static const species_id species_ZOMBIE ("ZOMBIE")
Function Documentation
make_mon_corpse()
item_location make_mon_corpse (monster & z, int damageLvl)
Definition at line 284 of file mondeath.cpp.
 {
     item corpse = item::make_corpse( z.type->id, calendar::turn, z.unique_name, z.get_upgrade_time() );
     // All corpses are at 37 C at time of death
     // This may not be true but anything better would be way too complicated
     if( z.is_warm() ) {
         corpse.set_item_temperature( units::from_celsius( 37 ) );
     }
     corpse.set_damage( damageLvl );
     if( z.has_effect( effect_no_ammo ) ) {
         corpse.set_var( "no_ammo", "no_ammo" );
     }
     if( z.has_effect( effect_critter_underfed ) ) {
         corpse.set_flag( STATIC( flag_id( "UNDERFED" ) ) );
     }
     return get_map().add_item_ret_loc( z.pos(), corpse );
 }
References map::add_item_ret_loc(), corpse, effect_critter_underfed, effect_no_ammo, units::from_celsius(), get_map(), monster::get_upgrade_time(), Creature::has_effect(), mtype::id, monster::is_warm(), item::make_corpse(), Creature::pos(), STATIC, calendar::turn, monster::type, and monster::unique_name.
Referenced by mdeath::normal().
scatter_chunks()
static void scatter_chunks (const itype_id & chunk_name, int chunk_amt, monster & z, int distance, int pile_size = 1) static
Definition at line 92 of file mondeath.cpp.
 {
     // can't have less than one item in a pile or it would cause an infinite loop
     pile_size = std::max( pile_size, 1 );
     // can't have more items in a pile than total items
     pile_size = std::min( chunk_amt, pile_size );
     distance = std::abs( distance );
     const item chunk( chunk_name, calendar::turn );
     map &here = get_map();
     int placed_chunks = 0;
     while( placed_chunks < chunk_amt ) {
         bool drop_chunks = true;
         tripoint tarp( z.pos() + point( rng( -distance, distance ), rng( -distance, distance ) ) );
         const auto traj = line_to( z.pos(), tarp );
         for( size_t j = 0; j < traj.size(); j++ ) {
             tarp = traj[j];
             if( one_in( 2 ) && z.bloodType().id() ) {
                 here.add_splatter( z.bloodType(), tarp );
             } else {
                 here.add_splatter( z.gibType(), tarp, rng( 1, j + 1 ) );
             }
             if( here.impassable( tarp ) ) {
                 here.bash( tarp, distance );
                 if( here.impassable( tarp ) ) {
                     // Target is obstacle, not destroyed by bashing,
                     // stop trajectory in front of it, if this is the first
                     // point (e.g. wall adjacent to monster), don't drop anything on it
                     if( j > 0 ) {
                         tarp = traj[j - 1];
                     } else {
                         drop_chunks = false;
                     }
                     break;
                 }
             }
         }
         if( drop_chunks ) {
             for( int i = placed_chunks; i < chunk_amt && i < placed_chunks + pile_size; i++ ) {
                 here.add_item_or_charges( tarp, chunk );
             }
         }
         placed_chunks += pile_size;
     }
 }
References abs(), map::add_item_or_charges(), map::add_splatter(), map::bash(), monster::bloodType(), get_map(), monster::gibType(), int_id< T >::id(), map::impassable(), line_to(), max(), min(), one_in(), Creature::pos(), rng(), and calendar::turn.
Referenced by mdeath::splatter().
Variable Documentation
effect_critter_underfed
const efftype_id effect_critter_underfed("critter_underfed") ("critter_underfed") static
Referenced by make_mon_corpse(), and mdeath::splatter().
effect_no_ammo
const efftype_id effect_no_ammo("no_ammo") ("no_ammo") static
Referenced by make_mon_corpse(), and mdeath::splatter().
harvest_drop_bone
const harvest_drop_type_id harvest_drop_bone("bone") ("bone") static
Referenced by mdeath::splatter().
harvest_drop_flesh
const harvest_drop_type_id harvest_drop_flesh("flesh") ("flesh") static
Referenced by mdeath::splatter().
species_ZOMBIE
const species_id species_ZOMBIE("ZOMBIE") ("ZOMBIE") static
Referenced by mdeath::normal().