Cataclysm DDA: src/mondeath.h File Reference
mondeath.h File Reference
#include "item.h"
Namespaces
mdeath
Macros
#define CATA_SRC_MONDEATH_H
Functions
item_location mdeath::normal (monster &z)
item_location mdeath::splatter (monster &z)
void mdeath::disappear (monster &z)
void mdeath::broken (monster &z)
item_location make_mon_corpse (monster &z, int damageLvl)
Macro Definition Documentation
CATA_SRC_MONDEATH_H
#define CATA_SRC_MONDEATH_H
Definition at line 3 of file mondeath.h.
Function Documentation
make_mon_corpse()
item_location make_mon_corpse (monster & z, int damageLvl)
Definition at line 284 of file mondeath.cpp.
 {
     item corpse = item::make_corpse( z.type->id, calendar::turn, z.unique_name, z.get_upgrade_time() );
     // All corpses are at 37 C at time of death
     // This may not be true but anything better would be way too complicated
     if( z.is_warm() ) {
         corpse.set_item_temperature( units::from_celsius( 37 ) );
     }
     corpse.set_damage( damageLvl );
     if( z.has_effect( effect_no_ammo ) ) {
         corpse.set_var( "no_ammo", "no_ammo" );
     }
     if( z.has_effect( effect_critter_underfed ) ) {
         corpse.set_flag( STATIC( flag_id( "UNDERFED" ) ) );
     }
     return get_map().add_item_ret_loc( z.pos(), corpse );
 }
References map::add_item_ret_loc(), corpse, effect_critter_underfed, effect_no_ammo, units::from_celsius(), get_map(), monster::get_upgrade_time(), Creature::has_effect(), mtype::id, monster::is_warm(), item::make_corpse(), Creature::pos(), STATIC, calendar::turn, monster::type, and monster::unique_name.
Referenced by mdeath::normal().