Cataclysm DDA: src/mondefense.cpp File Reference
mondefense.cpp File Reference
#include "mondefense.h"
#include <algorithm>
#include <cstddef>
#include <iosfwd>
#include <list>
#include <map>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "ballistics.h"
#include "creature.h"
#include "damage.h"
#include "dispersion.h"
#include "enums.h"
#include "gun_mode.h"
#include "item.h"
#include "line.h"
#include "mattack_actors.h"
#include "mattack_common.h"
#include "messages.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "point.h"
#include "projectile.h"
#include "rng.h"
#include "sounds.h"
#include "translations.h"
#include "type_id.h"
#include "viewer.h"
Variables
static const damage_type_id damage_acid ("acid")
static const damage_type_id damage_electric ("electric")
static const gun_mode_id gun_mode_DEFAULT ("DEFAULT")
Variable Documentation
damage_acid
const damage_type_id damage_acid("acid") ("acid") static
Referenced by mdefense::acidsplash().
damage_electric
const damage_type_id damage_electric("electric") ("electric") static
Referenced by mdefense::zapback().
gun_mode_DEFAULT
const gun_mode_id gun_mode_DEFAULT("DEFAULT") ("DEFAULT") static
Referenced by mdefense::return_fire().