Cataclysm DDA: src/monexamine.cpp File Reference
monexamine.cpp File Reference
#include "monexamine.h"
#include <functional>
#include <iosfwd>
#include <list>
#include <map>
#include <memory>
#include <string>
#include <utility>
#include <vector>
#include "activity_actor_definitions.h"
#include "avatar.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "creature.h"
#include "debug.h"
#include "enums.h"
#include "game.h"
#include "game_inventory.h"
#include "item.h"
#include "item_location.h"
#include "itype.h"
#include "iuse.h"
#include "map.h"
#include "messages.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "output.h"
#include "player_activity.h"
#include "point.h"
#include "rng.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "units.h"
#include "value_ptr.h"
#include "flag.h"
Namespaces
anonymous_namespace{monexamine.cpp}
Functions
item_location anonymous_namespace{monexamine.cpp}::tack_loc ()
void anonymous_namespace{monexamine.cpp}::attach_saddle_to (monster &z)
void anonymous_namespace{monexamine.cpp}::remove_saddle_from (monster &z)
void anonymous_namespace{monexamine.cpp}::mount_pet (monster &z)
void anonymous_namespace{monexamine.cpp}::swap (monster &z)
void anonymous_namespace{monexamine.cpp}::push (monster &z)
void anonymous_namespace{monexamine.cpp}::rename_pet (monster &z)
void anonymous_namespace{monexamine.cpp}::attach_bag_to (monster &z)
void anonymous_namespace{monexamine.cpp}::dump_items (monster &z)
void anonymous_namespace{monexamine.cpp}::remove_bag_from (monster &z)
bool anonymous_namespace{monexamine.cpp}::give_items_to (monster &z)
item_location anonymous_namespace{monexamine.cpp}::pet_armor_loc (monster &z)
bool anonymous_namespace{monexamine.cpp}::add_armor (monster &z)
void anonymous_namespace{monexamine.cpp}::remove_harness (monster &z)
void anonymous_namespace{monexamine.cpp}::remove_armor (monster &z)
void anonymous_namespace{monexamine.cpp}::play_with (monster &z)
void anonymous_namespace{monexamine.cpp}::cull (monster &z)
void anonymous_namespace{monexamine.cpp}::add_leash (monster &z)
void anonymous_namespace{monexamine.cpp}::remove_leash (monster &z)
void anonymous_namespace{monexamine.cpp}::tie_pet (monster &z)
void anonymous_namespace{monexamine.cpp}::untie_pet (monster &z)
void anonymous_namespace{monexamine.cpp}::start_leading (monster &z)
void anonymous_namespace{monexamine.cpp}::stop_leading (monster &z)
void anonymous_namespace{monexamine.cpp}::milk_source (monster &source_mon)
void anonymous_namespace{monexamine.cpp}::shear_animal (monster &z)
void anonymous_namespace{monexamine.cpp}::remove_battery (monster &z)
void anonymous_namespace{monexamine.cpp}::insert_battery (monster &z)
static int prompt_for_amount (const char *const msg, const int max)
Variables
static const efftype_id effect_controlled ("controlled")
static const efftype_id effect_critter_well_fed ("critter_well_fed")
static const efftype_id effect_harnessed ("harnessed")
static const efftype_id effect_has_bag ("has_bag")
static const efftype_id effect_leashed ("leashed")
static const efftype_id effect_led_by_leash ("led_by_leash")
static const efftype_id effect_monster_armor ("monster_armor")
static const efftype_id effect_monster_saddled ("monster_saddled")
static const efftype_id effect_paid ("paid")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_ridden ("ridden")
static const efftype_id effect_sheared ("sheared")
static const efftype_id effect_tied ("tied")
static const flag_id json_flag_MECH_BAT ("MECH_BAT")
static const flag_id json_flag_TACK ("TACK")
static const flag_id json_flag_TIE_UP ("TIE_UP")
static const itype_id itype_cash_card ("cash_card")
static const itype_id itype_id_military ("id_military")
static const quality_id qual_CUT ("CUT")
static const quality_id qual_SHEAR ("SHEAR")
static const skill_id skill_survival ("survival")
Function Documentation
prompt_for_amount()
static int prompt_for_amount (const char *const msg, const int max) static
Definition at line 874 of file monexamine.cpp.
 {
     const std::string formatted = string_format( msg, max );
     const int amount = string_input_popup()
                        .title( formatted )
                        .width( 20 )
                        .text( std::to_string( max ) )
                        .only_digits( true )
                        .query_int();
     return clamp( amount, 0, max );
 }
References clamp(), max(), string_input_popup::only_digits(), string_input_popup::query_int(), string_format(), string_input_popup::text(), string_input_popup::title(), to_string(), and string_input_popup::width().
Referenced by anonymous_namespace{iexamine.cpp}::atm_menu::do_deposit_money(), anonymous_namespace{iexamine.cpp}::atm_menu::do_withdraw_money(), and monexamine::pay_bot().
Variable Documentation
effect_controlled
const efftype_id effect_controlled("controlled") ("controlled") static
Referenced by Character::can_mount(), and anonymous_namespace{monexamine.cpp}::give_items_to().
effect_critter_well_fed
const efftype_id effect_critter_well_fed("critter_well_fed") ("critter_well_fed") static
Referenced by anonymous_namespace{monexamine.cpp}::milk_source().
effect_harnessed
const efftype_id effect_harnessed("harnessed") ("harnessed") static
Referenced by monexamine::pet_menu(), and anonymous_namespace{monexamine.cpp}::remove_harness().
effect_has_bag
const efftype_id effect_has_bag("has_bag") ("has_bag") static
Referenced by anonymous_namespace{monexamine.cpp}::attach_bag_to(), monexamine::pet_menu(), and anonymous_namespace{monexamine.cpp}::remove_bag_from().
effect_leashed
const efftype_id effect_leashed("leashed") ("leashed") static
Referenced by anonymous_namespace{monexamine.cpp}::add_leash(), monexamine::pet_menu(), anonymous_namespace{monexamine.cpp}::remove_leash(), and anonymous_namespace{monexamine.cpp}::untie_pet().
effect_led_by_leash
const efftype_id effect_led_by_leash("led_by_leash") ("led_by_leash") static
Referenced by monexamine::pet_menu(), anonymous_namespace{monexamine.cpp}::remove_leash(), anonymous_namespace{monexamine.cpp}::start_leading(), and anonymous_namespace{monexamine.cpp}::stop_leading().
effect_monster_armor
const efftype_id effect_monster_armor("monster_armor") ("monster_armor") static
Referenced by anonymous_namespace{monexamine.cpp}::add_armor(), monexamine::pet_menu(), and anonymous_namespace{monexamine.cpp}::remove_armor().
effect_monster_saddled
const efftype_id effect_monster_saddled("monster_saddled") ("monster_saddled") static
Referenced by anonymous_namespace{monexamine.cpp}::attach_saddle_to(), Character::can_mount(), monexamine::pet_menu(), and anonymous_namespace{monexamine.cpp}::remove_saddle_from().
effect_paid
const efftype_id effect_paid("paid") ("paid") static
Referenced by monexamine::pay_bot().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by monexamine::mech_hack(), and monexamine::pay_bot().
effect_ridden
const efftype_id effect_ridden("ridden") ("ridden") static
Referenced by Character::can_mount().
effect_sheared
const efftype_id effect_sheared("sheared") ("sheared") static
Referenced by monexamine::pet_menu().
effect_tied
const efftype_id effect_tied("tied") ("tied") static
Referenced by anonymous_namespace{monexamine.cpp}::milk_source(), monexamine::pet_menu(), anonymous_namespace{monexamine.cpp}::shear_animal(), anonymous_namespace{monexamine.cpp}::start_leading(), anonymous_namespace{monexamine.cpp}::swap(), anonymous_namespace{monexamine.cpp}::tie_pet(), and anonymous_namespace{monexamine.cpp}::untie_pet().
itype_cash_card
const itype_id itype_cash_card("cash_card") ("cash_card") static
Referenced by monexamine::pay_bot().
itype_id_military
const itype_id itype_id_military("id_military") ("id_military") static
Referenced by monexamine::mech_hack().
json_flag_MECH_BAT
const flag_id json_flag_MECH_BAT("MECH_BAT") ("MECH_BAT") static
Referenced by anonymous_namespace{monexamine.cpp}::insert_battery().
json_flag_TACK
const flag_id json_flag_TACK("TACK") ("TACK") static
Referenced by monexamine::pet_menu(), and anonymous_namespace{monexamine.cpp}::tack_loc().
json_flag_TIE_UP
const flag_id json_flag_TIE_UP("TIE_UP") ("TIE_UP") static
Referenced by anonymous_namespace{monexamine.cpp}::add_leash(), and monexamine::pet_menu().
qual_CUT
const quality_id qual_CUT("CUT") ("CUT") static
Referenced by anonymous_namespace{monexamine.cpp}::cull().
qual_SHEAR
const quality_id qual_SHEAR("SHEAR") ("SHEAR") static
Referenced by monexamine::pet_menu(), and anonymous_namespace{monexamine.cpp}::shear_animal().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by Character::can_mount(), and monexamine::pet_menu().