Cataclysm DDA: src/monfaction.cpp File Reference
monfaction.cpp File Reference
#include "monfaction.h"
#include <array>
#include <list>
#include <map>
#include <new>
#include <set>
#include <utility>
#include "debug.h"
#include "debug_menu.h"
#include "generic_factory.h"
#include "json.h"
Variables
static generic_factory< monfaction > faction_factory ("MONSTER_FACTION", "name")
Variable Documentation
faction_factory
generic_factory<monfaction> faction_factory("MONSTER_FACTION", "name") ("MONSTER_FACTION" , "name") static
Referenced by monfactions::finalize(), monfactions::get_all(), int_id< T >::id(), string_id< T >::id(), monfactions::load_monster_faction(), int_id< T >::obj(), string_id< T >::obj(), monfaction::populate_attitude_vec(), and monfactions::reset().