Cataclysm DDA: src/mongroup.cpp File Reference
mongroup.cpp File Reference
#include "mongroup.h"
#include <algorithm>
#include <string>
#include <utility>
#include "assign.h"
#include "calendar.h"
#include "cata_utility.h"
#include "debug.h"
#include "json.h"
#include "mtype.h"
#include "options.h"
#include "rng.h"
Namespaces
io
Functions
template<>
std::string io::enum_to_string< mongroup::horde_behaviour > (mongroup::horde_behaviour data)
static bool is_spawn_valid (const MonsterGroupEntry &entry, const time_point &sunset, const time_point &sunrise, const season_type season, const bool can_spawn_events)
static void check_group_def (const mongroup_id &g)
Variables
static const mtype_id mon_null ("mon_null")
static bool monster_whitelist_is_exclusive = false
Function Documentation
check_group_def()
static void check_group_def (const mongroup_id & g) static
Definition at line 585 of file mongroup.cpp.
 {
     for( const MonsterGroupEntry &m : g.obj().monsters ) {
         if( m.is_group() ) {
             if( !m.group.is_valid() ) {
                 debugmsg( "monster group %s contains unknown subgroup %s", g.c_str(), m.group.c_str() );
             } else {
                 check_group_def( m.group );
             }
         } else if( !m.name.is_valid() ) {
             debugmsg( "monster group %s contains unknown monster %s", g.c_str(), m.name.c_str() );
         }
     }
 }
References debugmsg, and g.
Referenced by MonsterGroupManager::check_group_definitions().
is_spawn_valid()
static bool is_spawn_valid (const MonsterGroupEntry & entry, const time_point & sunset, const time_point & sunrise, const season_type season, const bool can_spawn_events) static
Definition at line 129 of file mongroup.cpp.
 {
     // If an event was specified for this entry, check if it matches the current holiday
     if( entry.event != holiday::none && ( !can_spawn_events ||
                                           entry.event != get_holiday_from_time() ) ) {
         return false;
     }
     //Insure that the time is not before the spawn first appears or after it stops appearing
     if( calendar::turn < calendar::start_of_cataclysm + entry.starts ) {
         return false;
     }
     if( !entry.lasts_forever() && calendar::turn >= calendar::start_of_cataclysm + entry.ends ) {
         return false;
     }
     std::vector<std::pair<time_point, time_point> > valid_times_of_day;
     bool season_limited = false;
     bool season_matched = false;
     //Collect the various spawn conditions, and then insure they are met appropriately
     for( const std::string &elem : entry.conditions ) {
         //Collect valid time of day ranges
         if( elem == "DAY" || elem == "NIGHT" || elem == "DUSK" || elem == "DAWN" ) {
             if( elem == "DAY" ) {
                 valid_times_of_day.emplace_back( sunrise, sunset );
             } else if( elem == "NIGHT" ) {
                 valid_times_of_day.emplace_back( sunset, sunrise );
             } else if( elem == "DUSK" ) {
                 valid_times_of_day.emplace_back( sunset - 1_hours, sunset + 1_hours );
             } else if( elem == "DAWN" ) {
                 valid_times_of_day.emplace_back( sunrise - 1_hours, sunrise + 1_hours );
             }
         }
         //If we have any seasons listed, we know to limit by season, and if any season matches this season, we are good to spawn
         if( elem == "SUMMER" || elem == "WINTER" || elem == "SPRING" || elem == "AUTUMN" ) {
             season_limited = true;
             if( ( season == SUMMER && elem == "SUMMER" ) ||
                 ( season == WINTER && elem == "WINTER" ) ||
                 ( season == SPRING && elem == "SPRING" ) ||
                 ( season == AUTUMN && elem == "AUTUMN" ) ) {
                 season_matched = true;
             }
         }
     }
     //Make sure the current time of day is within one of the valid time ranges for this spawn
     bool is_valid_time_of_day = false;
     if( valid_times_of_day.empty() ) {
         //Then it can spawn whenever, since no times were defined
         is_valid_time_of_day = true;
     } else {
         //Otherwise, it's valid if it matches any of the times of day
         for( auto &elem : valid_times_of_day ) {
             if( calendar::turn > elem.first && calendar::turn < elem.second ) {
                 is_valid_time_of_day = true;
             }
         }
     }
     if( !is_valid_time_of_day ) {
         return false;
     }
     //If we are limited by season, make sure we matched a season
     if( season_limited && !season_matched ) {
         return false;
     }
     return true;
 }
References AUTUMN, MonsterGroupEntry::conditions, MonsterGroupEntry::ends, MonsterGroupEntry::event, get_holiday_from_time(), MonsterGroupEntry::lasts_forever(), none, season, SPRING, calendar::start_of_cataclysm, MonsterGroupEntry::starts, SUMMER, sunrise(), sunset(), calendar::turn, and WINTER.
Referenced by MonsterGroupManager::GetResultFromGroup().
Variable Documentation
mon_null
const mtype_id mon_null("mon_null") ("mon_null") static
Referenced by MonsterGroupManager::LoadMonsterGroup().
monster_whitelist_is_exclusive
bool monster_whitelist_is_exclusive = false static
Definition at line 34 of file mongroup.cpp.
Referenced by MonsterGroupManager::ClearMonsterGroups(), MonsterGroupManager::LoadMonsterWhitelist(), and MonsterGroupManager::monster_is_blacklisted().