Cataclysm DDA: src/monmove.cpp File Reference
monmove.cpp File Reference
#include "monster.h"
#include <algorithm>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <iterator>
#include <list>
#include <memory>
#include <ostream>
#include <string>
#include <unordered_map>
#include "behavior.h"
#include "bionics.h"
#include "cached_options.h"
#include "cata_utility.h"
#include "character.h"
#include "colony.h"
#include "creature_tracker.h"
#include "debug.h"
#include "field.h"
#include "field_type.h"
#include "game.h"
#include "game_constants.h"
#include "line.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "mattack_common.h"
#include "memory_fast.h"
#include "messages.h"
#include "monfaction.h"
#include "monster_oracle.h"
#include "mtype.h"
#include "npc.h"
#include "options.h"
#include "pathfinding.h"
#include "pimpl.h"
#include "rng.h"
#include "scent_map.h"
#include "sounds.h"
#include "string_formatter.h"
#include "submap.h"
#include "tileray.h"
#include "translations.h"
#include "trap.h"
#include "units.h"
#include "veh_type.h"
#include "vehicle.h"
#include "viewer.h"
#include "vpart_position.h"
Classes
struct monster_plan
Functions
static bool z_is_valid (int z)
static float get_stagger_adjust (const tripoint &source, const tripoint &destination, const tripoint &next_step)
Method to make monster movement speed consistent in the face of staggering behavior and differing distance metrics.
static std::vector< tripoint > get_bashing_zone (const tripoint &bashee, const tripoint &basher, int maxdepth)
static tripoint find_closest_stair (const tripoint &near_this, const ter_furn_flag stair_type)
Variables
static const damage_type_id damage_cut ("cut")
static const efftype_id effect_bouldering ("bouldering")
static const efftype_id effect_countdown ("countdown")
static const efftype_id effect_cramped_space ("cramped_space")
static const efftype_id effect_docile ("docile")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_dragging ("dragging")
static const efftype_id effect_grabbed ("grabbed")
static const efftype_id effect_harnessed ("harnessed")
static const efftype_id effect_led_by_leash ("led_by_leash")
static const efftype_id effect_no_sight ("no_sight")
static const efftype_id effect_operating ("operating")
static const efftype_id effect_pacified ("pacified")
static const efftype_id effect_psi_stunned ("psi_stunned")
static const efftype_id effect_pushed ("pushed")
static const efftype_id effect_stumbled_into_invisible ("stumbled_into_invisible")
static const efftype_id effect_stunned ("stunned")
static const field_type_str_id field_fd_last_known ("fd_last_known")
static const flag_id json_flag_GRAB ("GRAB")
static const flag_id json_flag_GRAB_FILTER ("GRAB_FILTER")
static const itype_id itype_pressurized_tank ("pressurized_tank")
static const material_id material_iflesh ("iflesh")
static const species_id species_FUNGUS ("FUNGUS")
static const species_id species_ZOMBIE ("ZOMBIE")
static const ter_str_id ter_t_lava ("t_lava")
static const ter_str_id ter_t_pit ("t_pit")
static const ter_str_id ter_t_pit_glass ("t_pit_glass")
static const ter_str_id ter_t_pit_spiked ("t_pit_spiked")
Function Documentation
find_closest_stair()
static tripoint find_closest_stair (const tripoint & near_this, const ter_furn_flag stair_type) static
Definition at line 1840 of file monmove.cpp.
 {
     map &here = get_map();
     for( const tripoint &candidate : closest_points_first( near_this, 10 ) ) {
         if( here.has_flag( stair_type, candidate ) ) {
             return candidate;
         }
     }
     // we didn't find it
     return near_this;
 }
References closest_points_first(), get_map(), and map::has_flag().
Referenced by monster::move_to().
get_bashing_zone()
static std::vector<tripoint> get_bashing_zone (const tripoint & bashee, const tripoint & basher, int maxdepth) static
Definition at line 1650 of file monmove.cpp.
 {
     std::vector<tripoint> direction;
     direction.push_back( bashee );
     direction.push_back( basher );
     // Draw a line from the target through the attacker.
     std::vector<tripoint> path = continue_line( direction, maxdepth );
     // Remove the target.
     path.insert( path.begin(), basher );
     std::vector<tripoint> zone;
     // Go ahead and reserve enough room for all the points since
     // we know how many it will be.
     zone.reserve( 3 * maxdepth );
     tripoint previous = bashee;
     for( const tripoint &p : path ) {
         std::vector<point> swath = squares_in_direction( previous.xy(), p.xy() );
         for( const point &q : swath ) {
             zone.emplace_back( q, bashee.z );
         }
         previous = p;
     }
     return zone;
 }
References continue_line(), squares_in_direction(), tripoint::xy(), and tripoint::z.
Referenced by monster::group_bash_skill().
get_stagger_adjust()
static float get_stagger_adjust (const tripoint & source, const tripoint & destination, const tripoint & next_step) static
Method to make monster movement speed consistent in the face of staggering behavior and differing distance metrics.
It works by scaling the cost to take a step by how much that step reduces the distance to your goal. Since it incorporates the current distance metric, it also scales for diagonal vs orthogonal movement.
Definition at line 825 of file monmove.cpp.
 {
     // TODO: push this down into rl_dist
     const float initial_dist =
         trigdist ? trig_dist( source, destination ) : rl_dist( source, destination );
     const float new_dist =
         trigdist ? trig_dist( next_step, destination ) : rl_dist( next_step, destination );
     // If we return 0, it wil cancel the action.
     return std::max( 0.01f, initial_dist - new_dist );
 }
References max(), rl_dist(), trig_dist(), and trigdist.
Referenced by monster::move().
z_is_valid()
static bool z_is_valid (int z) static
Definition at line 130 of file monmove.cpp.
 {
     return z >= -OVERMAP_DEPTH && z <= OVERMAP_HEIGHT;
 }
References OVERMAP_DEPTH, and OVERMAP_HEIGHT.
Referenced by monster::can_reach_to().
Variable Documentation
damage_cut
const damage_type_id damage_cut("cut") ("cut") static
Referenced by monster::know_danger_at(), and monster::move_to().
effect_bouldering
const efftype_id effect_bouldering("bouldering") ("bouldering") static
Referenced by monster::move_to().
effect_countdown
const efftype_id effect_countdown("countdown") ("countdown") static
Referenced by monster::nursebot_operate().
effect_cramped_space
const efftype_id effect_cramped_space("cramped_space") ("cramped_space") static
Referenced by monster::monster_move_in_vehicle().
effect_docile
const efftype_id effect_docile("docile") ("docile") static
Referenced by monster_plan::monster_plan().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by monster::push_to().
effect_dragging
const efftype_id effect_dragging("dragging") ("dragging") static
Referenced by monster::find_dragged_foe(), monster::move(), monster::nursebot_operate(), and monster::plan().
effect_grabbed
const efftype_id effect_grabbed("grabbed") ("grabbed") static
Referenced by monster::move(), and monster::nursebot_operate().
effect_harnessed
const efftype_id effect_harnessed("harnessed") ("harnessed") static
Referenced by monster::move().
effect_led_by_leash
const efftype_id effect_led_by_leash("led_by_leash") ("led_by_leash") static
Referenced by monster::move(), and monster::plan().
effect_no_sight
const efftype_id effect_no_sight("no_sight") ("no_sight") static
Referenced by monster::move_to().
effect_operating
const efftype_id effect_operating("operating") ("operating") static
Referenced by monster::nursebot_operate(), and monster::plan().
effect_pacified
const efftype_id effect_pacified("pacified") ("pacified") static
Referenced by monster::move().
effect_psi_stunned
const efftype_id effect_psi_stunned("psi_stunned") ("psi_stunned") static
Referenced by monster::move().
effect_pushed
const efftype_id effect_pushed("pushed") ("pushed") static
Referenced by monster::push_to().
effect_stumbled_into_invisible
const efftype_id effect_stumbled_into_invisible("stumbled_into_invisible") ("stumbled_into_invisible") static
Referenced by monster::attack_at().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by monster::knock_back_to(), monster::move(), and monster::push_to().
field_fd_last_known
const field_type_str_id field_fd_last_known("fd_last_known") ("fd_last_known") static
Referenced by monster::attack_at().
itype_pressurized_tank
const itype_id itype_pressurized_tank("pressurized_tank") ("pressurized_tank") static
Referenced by monster::move_to().
json_flag_GRAB
const flag_id json_flag_GRAB("GRAB") ("GRAB") static
Referenced by monster::nursebot_operate().
json_flag_GRAB_FILTER
const flag_id json_flag_GRAB_FILTER("GRAB_FILTER") ("GRAB_FILTER") static
Referenced by monster::nursebot_operate().
material_iflesh
const material_id material_iflesh("iflesh") ("iflesh") static
Referenced by monster::is_immune_field().
species_FUNGUS
const species_id species_FUNGUS("FUNGUS") ("FUNGUS") static
Referenced by monster::is_immune_field().
species_ZOMBIE
const species_id species_ZOMBIE("ZOMBIE") ("ZOMBIE") static
Referenced by monster::plan().
ter_t_lava
const ter_str_id ter_t_lava("t_lava") ("t_lava") static
Referenced by monster::know_danger_at().
ter_t_pit
const ter_str_id ter_t_pit("t_pit") ("t_pit") static
Referenced by monster::know_danger_at().
ter_t_pit_glass
const ter_str_id ter_t_pit_glass("t_pit_glass") ("t_pit_glass") static
Referenced by monster::know_danger_at().
ter_t_pit_spiked
const ter_str_id ter_t_pit_spiked("t_pit_spiked") ("t_pit_spiked") static
Referenced by monster::know_danger_at().