Cataclysm DDA: src/monstergenerator.h File Reference
monstergenerator.h File Reference
#include <array>
#include <iosfwd>
#include <map>
#include <memory>
#include <optional>
#include <vector>
#include "enum_bitset.h"
#include "enums.h"
#include "generic_factory.h"
#include "mattack_common.h"
#include "mtype.h"
#include "pimpl.h"
#include "translations.h"
#include "type_id.h"
Classes
struct species_type
class MonsterGenerator
Macros
#define CATA_SRC_MONSTERGENERATOR_H
Typedefs
using mon_action_death = void(*)(monster &)
using mon_action_attack = bool(*)(monster *)
using mon_action_defend = void(*)(monster &, Creature *, dealt_projectile_attack const *)
Functions
void load_monster_adjustment (const JsonObject &jsobj)
void reset_monster_adjustment ()
Macro Definition Documentation
CATA_SRC_MONSTERGENERATOR_H
#define CATA_SRC_MONSTERGENERATOR_H
Definition at line 3 of file monstergenerator.h.
Typedef Documentation
mon_action_attack
using mon_action_attack = bool (*)(monster *)
Definition at line 27 of file monstergenerator.h.
mon_action_death
using mon_action_death = void (*)(monster &)
Definition at line 26 of file monstergenerator.h.
mon_action_defend
using mon_action_defend = void (*)(monster &, Creature *, dealt_projectile_attack const *)
Definition at line 28 of file monstergenerator.h.
Function Documentation
load_monster_adjustment()
void load_monster_adjustment (const JsonObject & jsobj)
Definition at line 289 of file monstergenerator.cpp.
 {
     monster_adjustment adj;
     adj.species = species_id( jsobj.get_string( "species" ) );
     if( jsobj.has_member( "stat" ) ) {
         JsonObject stat = jsobj.get_object( "stat" );
         stat.read( "name", adj.stat );
         stat.read( "modifier", adj.stat_adjust );
     }
     if( jsobj.has_member( "flag" ) ) {
         JsonObject flag = jsobj.get_object( "flag" );
         flag.read( "name", adj.flag );
         flag.read( "value", adj.flag_val );
     }
     if( jsobj.has_member( "special" ) ) {
         jsobj.read( "special", adj.special );
     }
     adjustments.push_back( adj );
 }
References adjustments, monster_adjustment::flag, monster_adjustment::flag_val, JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_member(), JsonObject::read(), monster_adjustment::special, monster_adjustment::species, monster_adjustment::stat, and monster_adjustment::stat_adjust.
Referenced by DynamicDataLoader::initialize().
reset_monster_adjustment()
void reset_monster_adjustment ()
Definition at line 284 of file monstergenerator.cpp.
 {
     adjustments.clear();
 }
References adjustments.
Referenced by DynamicDataLoader::unload_data().