Cataclysm DDA: src/monstergenerator.cpp File Reference
monstergenerator.cpp File Reference
#include "mattack_common.h"
#include "monstergenerator.h"
#include <algorithm>
#include <cstdlib>
#include <limits>
#include <new>
#include <optional>
#include <set>
#include <string>
#include <utility>
#include "assign.h"
#include "bodypart.h"
#include "cached_options.h"
#include "calendar.h"
#include "catacharset.h"
#include "creature.h"
#include "damage.h"
#include "debug.h"
#include "enum_conversions.h"
#include "field_type.h"
#include "generic_factory.h"
#include "item.h"
#include "item_group.h"
#include "json.h"
#include "make_static.h"
#include "mattack_actors.h"
#include "monattack.h"
#include "mondeath.h"
#include "mondefense.h"
#include "mongroup.h"
#include "options.h"
#include "pathfinding.h"
#include "rng.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
#include "weakpoint.h"
Classes
struct monster_adjustment
class mattack_hardcoded_wrapper
Namespaces
anonymous_namespace{monstergenerator.cpp}
behavior
io
Functions
template<>
std::string io::enum_to_string< mon_trigger > (mon_trigger data)
template<>
std::string io::enum_to_string< mdeath_type > (mdeath_type data)
static int calc_bash_skill (const mtype &t)
static creature_size volume_to_size (const units::volume &vol)
void reset_monster_adjustment ()
void load_monster_adjustment (const JsonObject &jsobj)
static void build_behavior_tree (mtype &type)
Variables
static const material_id material_flesh ("flesh")
static const speed_description_id speed_description_DEFAULT ("DEFAULT")
static const spell_id spell_pseudo_dormant_trap_setup ("pseudo_dormant_trap_setup")
generic_factory< mon_flag > anonymous_namespace{monstergenerator.cpp}::mon_flags ("monster flags")
static std::vector< monster_adjustment > adjustments
Function Documentation
build_behavior_tree()
static void build_behavior_tree (mtype & type) static
Definition at line 309 of file monstergenerator.cpp.
 {
     type.set_strategy();
     for( const std::pair<const std::string, mtype_special_attack> &attack : type.special_attacks ) {
         if( string_id<behavior::node_t>( attack.first ).is_valid() ) {
             type.add_goal( attack.first );
         } /* TODO: Make this an error once all the special attacks are migrated. */
     }
 }
References spell_effect::attack(), and string_id< T >::is_valid().
Referenced by MonsterGenerator::finalize_mtypes().
calc_bash_skill()
static int calc_bash_skill (const mtype & t) static
Definition at line 218 of file monstergenerator.cpp.
 {
     // IOW, the critter's max bashing damage
     int ret = t.melee_dice * t.melee_sides;
     // This is for stuff that goes through solid rock: minerbots, dark wyrms, etc
     if( t.has_flag( mon_flag_BORES ) ) {
         ret *= 15;
     } else if( t.has_flag( mon_flag_DESTROYS ) ) {
         ret *= 2.5;
     } else if( !t.has_flag( mon_flag_BASHES ) ) {
         ret = 0;
     }
     return ret;
 }
References mtype::has_flag(), mtype::melee_dice, mtype::melee_sides, mon_flag_BASHES, mon_flag_BORES, mon_flag_DESTROYS, and cata::hash64_detail::ret.
Referenced by MonsterGenerator::finalize_mtypes().
load_monster_adjustment()
void load_monster_adjustment (const JsonObject & jsobj)
Definition at line 289 of file monstergenerator.cpp.
 {
     monster_adjustment adj;
     adj.species = species_id( jsobj.get_string( "species" ) );
     if( jsobj.has_member( "stat" ) ) {
         JsonObject stat = jsobj.get_object( "stat" );
         stat.read( "name", adj.stat );
         stat.read( "modifier", adj.stat_adjust );
     }
     if( jsobj.has_member( "flag" ) ) {
         JsonObject flag = jsobj.get_object( "flag" );
         flag.read( "name", adj.flag );
         flag.read( "value", adj.flag_val );
     }
     if( jsobj.has_member( "special" ) ) {
         jsobj.read( "special", adj.special );
     }
     adjustments.push_back( adj );
 }
References adjustments, monster_adjustment::flag, monster_adjustment::flag_val, JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_member(), JsonObject::read(), monster_adjustment::special, monster_adjustment::species, monster_adjustment::stat, and monster_adjustment::stat_adjust.
Referenced by DynamicDataLoader::initialize().
reset_monster_adjustment()
void reset_monster_adjustment ()
Definition at line 284 of file monstergenerator.cpp.
 {
     adjustments.clear();
 }
References adjustments.
Referenced by DynamicDataLoader::unload_data().
volume_to_size()
static creature_size volume_to_size (const units::volume & vol) static
Definition at line 234 of file monstergenerator.cpp.
 {
     if( vol <= 7500_ml ) {
         return creature_size::tiny;
     } else if( vol <= 46250_ml ) {
         return creature_size::small;
     } else if( vol <= 108000_ml ) {
         return creature_size::medium;
     } else if( vol <= 483750_ml ) {
         return creature_size::large;
     }
     return creature_size::huge;
 }
References huge, large, medium, small, and tiny.
Referenced by MonsterGenerator::finalize_mtypes().
Variable Documentation
adjustments
std::vector<monster_adjustment> adjustments static
Definition at line 282 of file monstergenerator.cpp.
Referenced by MonsterGenerator::finalize_mtypes(), load_monster_adjustment(), and reset_monster_adjustment().
material_flesh
const material_id material_flesh("flesh") ("flesh") static
Referenced by mtype::load().
speed_description_DEFAULT
const speed_description_id speed_description_DEFAULT("DEFAULT") ("DEFAULT") static
Referenced by mtype::load().
spell_pseudo_dormant_trap_setup
const spell_id spell_pseudo_dormant_trap_setup("pseudo_dormant_trap_setup") ("pseudo_dormant_trap_setup") static
Referenced by MonsterGenerator::generate_fake_pseudo_dormant_monster().