Cataclysm DDA: src/monster.cpp File Reference
monster.cpp File Reference
#include "monster.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <memory>
#include <optional>
#include <sstream>
#include <string>
#include <tuple>
#include "ascii_art.h"
#include "avatar.h"
#include "bodypart.h"
#include "catacharset.h"
#include "character.h"
#include "colony.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "creature_tracker.h"
#include "cursesdef.h"
#include "debug.h"
#include "effect.h"
#include "effect_on_condition.h"
#include "effect_source.h"
#include "event.h"
#include "event_bus.h"
#include "explosion.h"
#include "faction.h"
#include "field_type.h"
#include "game.h"
#include "game_constants.h"
#include "harvest.h"
#include "item.h"
#include "item_group.h"
#include "itype.h"
#include "line.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "mattack_common.h"
#include "melee.h"
#include "messages.h"
#include "mission.h"
#include "mod_manager.h"
#include "mondeath.h"
#include "mondefense.h"
#include "monfaction.h"
#include "mongroup.h"
#include "morale_types.h"
#include "mtype.h"
#include "mutation.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "projectile.h"
#include "rng.h"
#include "sounds.h"
#include "string_formatter.h"
#include "text_snippets.h"
#include "translations.h"
#include "trap.h"
#include "type_id.h"
#include "units.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "viewer.h"
#include "weakpoint.h"
#include "weather.h"
Functions
static int compute_kill_xp (const mtype_id &mon_type)
static void armor_enchantment_adjust (monster &mon, damage_unit &du)
static std::pair< std::string, nc_color > hp_description (int cur_hp, int max_hp)
Variables
static const anatomy_id anatomy_default_anatomy ("default_anatomy")
static const damage_type_id damage_bash ("bash")
static const damage_type_id damage_bullet ("bullet")
static const damage_type_id damage_cut ("cut")
static const damage_type_id damage_electric ("electric")
static const damage_type_id damage_heat ("heat")
static const damage_type_id damage_stab ("stab")
static const efftype_id effect_badpoison ("badpoison")
static const efftype_id effect_beartrap ("beartrap")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_bouldering ("bouldering")
static const efftype_id effect_cramped_space ("cramped_space")
static const efftype_id effect_critter_underfed ("critter_underfed")
static const efftype_id effect_critter_well_fed ("critter_well_fed")
static const efftype_id effect_crushed ("crushed")
static const efftype_id effect_deaf ("deaf")
static const efftype_id effect_disarmed ("disarmed")
static const efftype_id effect_docile ("docile")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_dripping_mechanical_fluid ("dripping_mechanical_fluid")
static const efftype_id effect_emp ("emp")
static const efftype_id effect_fake_common_cold ("fake_common_cold")
static const efftype_id effect_fake_flu ("fake_flu")
static const efftype_id effect_grabbing ("grabbing")
static const efftype_id effect_has_bag ("has_bag")
static const efftype_id effect_heavysnare ("heavysnare")
static const efftype_id effect_hit_by_player ("hit_by_player")
static const efftype_id effect_in_pit ("in_pit")
static const efftype_id effect_leashed ("leashed")
static const efftype_id effect_lightsnare ("lightsnare")
static const efftype_id effect_maimed_arm ("maimed_arm")
static const efftype_id effect_monster_armor ("monster_armor")
static const efftype_id effect_monster_saddled ("monster_saddled")
static const efftype_id effect_natures_commune ("natures_commune")
static const efftype_id effect_nemesis_buff ("nemesis_buff")
static const efftype_id effect_no_sight ("no_sight")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_pacified ("pacified")
static const efftype_id effect_paralyzepoison ("paralyzepoison")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_photophobia ("photophobia")
static const efftype_id effect_poison ("poison")
static const efftype_id effect_psi_stunned ("psi_stunned")
static const efftype_id effect_ridden ("ridden")
static const efftype_id effect_run ("run")
static const efftype_id effect_spooked ("spooked")
static const efftype_id effect_spooked_recent ("spooked_recent")
static const efftype_id effect_stunned ("stunned")
static const efftype_id effect_supercharged ("supercharged")
static const efftype_id effect_tied ("tied")
static const efftype_id effect_tpollen ("tpollen")
static const efftype_id effect_venom_dmg ("venom_dmg")
static const efftype_id effect_venom_player1 ("venom_player1")
static const efftype_id effect_venom_player2 ("venom_player2")
static const efftype_id effect_venom_weaken ("venom_weaken")
static const efftype_id effect_webbed ("webbed")
static const efftype_id effect_worked_on ("worked_on")
static const emit_id emit_emit_shock_cloud ("emit_shock_cloud")
static const emit_id emit_emit_shock_cloud_big ("emit_shock_cloud_big")
static const flag_id json_flag_DISABLE_FLIGHT ("DISABLE_FLIGHT")
static const flag_id json_flag_GRAB ("GRAB")
static const flag_id json_flag_GRAB_FILTER ("GRAB_FILTER")
static const itype_id itype_milk ("milk")
static const itype_id itype_milk_raw ("milk_raw")
static const json_character_flag json_flag_BIONIC_LIMB ("BIONIC_LIMB")
static const material_id material_bone ("bone")
static const material_id material_flesh ("flesh")
static const material_id material_hflesh ("hflesh")
static const material_id material_iflesh ("iflesh")
static const material_id material_iron ("iron")
static const material_id material_steel ("steel")
static const material_id material_stone ("stone")
static const material_id material_veggy ("veggy")
static const mfaction_str_id monfaction_acid_ant ("acid_ant")
static const mfaction_str_id monfaction_ant ("ant")
static const mfaction_str_id monfaction_bee ("bee")
static const mfaction_str_id monfaction_nether_player_hate ("nether_player_hate")
static const mfaction_str_id monfaction_wasp ("wasp")
static const species_id species_AMPHIBIAN ("AMPHIBIAN")
static const species_id species_CYBORG ("CYBORG")
static const species_id species_FISH ("FISH")
static const species_id species_FUNGUS ("FUNGUS")
static const species_id species_HORROR ("HORROR")
static const species_id species_LEECH_PLANT ("LEECH_PLANT")
static const species_id species_MAMMAL ("MAMMAL")
static const species_id species_MIGO ("MIGO")
static const species_id species_MOLLUSK ("MOLLUSK")
static const species_id species_NETHER ("NETHER")
static const species_id species_PLANT ("PLANT")
static const species_id species_PSI_NULL ("PSI_NULL")
static const species_id species_ROBOT ("ROBOT")
static const species_id species_ZOMBIE ("ZOMBIE")
static const species_id species_nether_player_hate ("nether_player_hate")
static const ter_str_id ter_t_gas_pump ("t_gas_pump")
static const ter_str_id ter_t_gas_pump_a ("t_gas_pump_a")
static const trait_id trait_ANIMALDISCORD ("ANIMALDISCORD")
static const trait_id trait_ANIMALDISCORD2 ("ANIMALDISCORD2")
static const trait_id trait_ANIMALEMPATH ("ANIMALEMPATH")
static const trait_id trait_ANIMALEMPATH2 ("ANIMALEMPATH2")
static const trait_id trait_BEE ("BEE")
static const trait_id trait_FLOWERS ("FLOWERS")
static const trait_id trait_INATTENTIVE ("INATTENTIVE")
static const trait_id trait_KILLER ("KILLER")
static const trait_id trait_MYCUS_FRIEND ("MYCUS_FRIEND")
static const trait_id trait_PHEROMONE_AMPHIBIAN ("PHEROMONE_AMPHIBIAN")
static const trait_id trait_PHEROMONE_INSECT ("PHEROMONE_INSECT")
static const trait_id trait_PHEROMONE_MAMMAL ("PHEROMONE_MAMMAL")
static const trait_id trait_TERRIFYING ("TERRIFYING")
static const trait_id trait_THRESH_MYCUS ("THRESH_MYCUS")
static constexpr int UPGRADE_MAX_ITERS = 5
static const std::map< creature_size, translation > size_names
static const std::map< monster_attitude, std::pair< std::string, color_id > > attitude_names
Function Documentation
armor_enchantment_adjust()
static void armor_enchantment_adjust (monster & mon, damage_unit & du) static
Definition at line 228 of file monster.cpp.
 {
     //If we're not dealing any damage of the given type, don't even bother.
     if( du.amount < 0.1f ) {
         return;
     }
     // FIXME: hardcoded damage types -> enchantments
     if( du.type == STATIC( damage_type_id( "acid" ) ) ) {
         du.amount = mon.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_ACID );
     } else if( du.type == STATIC( damage_type_id( "bash" ) ) ) {
         du.amount = mon.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_BASH );
     } else if( du.type == STATIC( damage_type_id( "biological" ) ) ) {
         du.amount = mon.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_BIO );
     } else if( du.type == STATIC( damage_type_id( "cold" ) ) ) {
         du.amount = mon.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_COLD );
     } else if( du.type == STATIC( damage_type_id( "cut" ) ) ) {
         du.amount = mon.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_CUT );
     } else if( du.type == STATIC( damage_type_id( "electric" ) ) ) {
         du.amount = mon.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_ELEC );
     } else if( du.type == STATIC( damage_type_id( "heat" ) ) ) {
         du.amount = mon.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_HEAT );
     } else if( du.type == STATIC( damage_type_id( "stab" ) ) ) {
         du.amount = mon.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_STAB );
     } else if( du.type == STATIC( damage_type_id( "bullet" ) ) ) {
         du.amount = mon.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_BULLET );
     }
     if( du.type != STATIC( damage_type_id( "pure" ) ) ) {
         du.amount = mon.calculate_by_enchantment( du.amount, enchant_vals::mod::ARMOR_ALL );
     }
     du.amount = std::max( 0.0f, du.amount );
 }
References damage_unit::amount, enchant_vals::ARMOR_ACID, enchant_vals::ARMOR_ALL, enchant_vals::ARMOR_BASH, enchant_vals::ARMOR_BIO, enchant_vals::ARMOR_BULLET, enchant_vals::ARMOR_COLD, enchant_vals::ARMOR_CUT, enchant_vals::ARMOR_ELEC, enchant_vals::ARMOR_HEAT, enchant_vals::ARMOR_STAB, monster::calculate_by_enchantment(), max(), STATIC, and damage_unit::type.
Referenced by monster::absorb_hit().
compute_kill_xp()
static int compute_kill_xp (const mtype_id & mon_type) static
Definition at line 222 of file monster.cpp.
 {
     return mon_type->difficulty + mon_type->difficulty_base;
 }
References mtype::difficulty, and mtype::difficulty_base.
Referenced by monster::die().
hp_description()
static std::pair<std::string, nc_color> hp_description (int cur_hp, int max_hp) static
Definition at line 803 of file monster.cpp.
 {
     std::string damage_info;
     nc_color col;
     if( cur_hp >= max_hp ) {
         damage_info = _( "It is uninjured." );
         col = c_green;
     } else if( cur_hp >= max_hp * 0.8 ) {
         damage_info = _( "It is lightly injured." );
         col = c_light_green;
     } else if( cur_hp >= max_hp * 0.6 ) {
         damage_info = _( "It is moderately injured." );
         col = c_yellow;
     } else if( cur_hp >= max_hp * 0.3 ) {
         damage_info = _( "It is heavily injured." );
         col = c_yellow;
     } else if( cur_hp >= max_hp * 0.1 ) {
         damage_info = _( "It is severely injured." );
         col = c_light_red;
     } else {
         damage_info = _( "It is nearly dead!" );
         col = c_red;
     }
     if( debug_mode ) {
         damage_info += "  ";
         damage_info += string_format( _( "%1$d/%2$d HP" ), cur_hp, max_hp );
     }
     return std::make_pair( damage_info, col );
 }
References _, c_green, c_light_green, c_light_red, c_red, c_yellow, debug_mode, and string_format().
Referenced by monster::extended_description().
Variable Documentation
anatomy_default_anatomy
const anatomy_id anatomy_default_anatomy("default_anatomy") ("default_anatomy") static
Referenced by monster::monster().
attitude_names
const std::map<monster_attitude, std::pair<std::string, color_id> > attitude_names static
Initial value:
{
    {monster_attitude::MATT_FRIEND, {translate_marker( "Friendly." ), def_h_white}},
    {monster_attitude::MATT_FPASSIVE, {translate_marker( "Passive." ), def_h_white}},
    {monster_attitude::MATT_FLEE, {translate_marker( "Fleeing!" ), def_c_green}},
    {monster_attitude::MATT_FOLLOW, {translate_marker( "Tracking." ), def_c_yellow}},
    {monster_attitude::MATT_IGNORE, {translate_marker( "Ignoring." ), def_c_light_gray}},
    {monster_attitude::MATT_ATTACK, {translate_marker( "Hostile!" ), def_c_red}},
    {monster_attitude::MATT_NULL, {translate_marker( "BUG: Behavior unnamed." ), def_h_red}},
}
Definition at line 212 of file monster.cpp.
Referenced by monster::get_attitude().
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by monster::deal_damage_handle_type(), monster::impact(), and monster::melee_attack().
damage_bullet
const damage_type_id damage_bullet("bullet") ("bullet") static
Referenced by monster::deal_damage_handle_type().
damage_cut
const damage_type_id damage_cut("cut") ("cut") static
Referenced by monster::impact(), and monster::melee_attack().
damage_electric
const damage_type_id damage_electric("electric") ("electric") static
Referenced by monster::is_elec_immune(), and monster::is_immune_damage().
damage_heat
const damage_type_id damage_heat("heat") ("heat") static
Referenced by monster::is_immune_damage(), monster::is_immune_effect(), and monster::process_one_effect().
damage_stab
const damage_type_id damage_stab("stab") ("stab") static
Referenced by monster::melee_attack().
effect_badpoison
const efftype_id effect_badpoison("badpoison") ("badpoison") static
Referenced by monster::is_immune_effect(), and monster::melee_attack().
effect_beartrap
const efftype_id effect_beartrap("beartrap") ("beartrap") static
Referenced by monster::color_with_effects(), monster::get_dodge(), and monster::move_effects().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by monster::is_immune_effect(), monster::make_bleed(), and monster::process_one_effect().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
Referenced by monster::process_one_effect(), and monster::process_turn().
effect_bouldering
const efftype_id effect_bouldering("bouldering") ("bouldering") static
Referenced by monster::get_dodge(), and monster::hit_roll().
effect_cramped_space
const efftype_id effect_cramped_space("cramped_space") ("cramped_space") static
Referenced by monster::process_effects().
effect_critter_underfed
const efftype_id effect_critter_underfed("critter_underfed") ("critter_underfed") static
Referenced by monster::digest_food(), monster::reset_digestion(), monster::try_biosignature(), and monster::try_reproduce().
effect_critter_well_fed
const efftype_id effect_critter_well_fed("critter_well_fed") ("critter_well_fed") static
Referenced by monster::digest_food(), monster::process_effects(), monster::refill_udders(), and monster::reset_digestion().
effect_crushed
const efftype_id effect_crushed("crushed") ("crushed") static
Referenced by monster::move_effects().
effect_deaf
const efftype_id effect_deaf("deaf") ("deaf") static
Referenced by monster::can_hear().
effect_disarmed
const efftype_id effect_disarmed("disarmed") ("disarmed") static
Referenced by monster::has_weapon().
effect_docile
const efftype_id effect_docile("docile") ("docile") static
Referenced by monster::attitude().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by monster::can_act(), monster::color_with_effects(), monster::get_dodge(), monster::impact(), monster::is_immune_effect(), and monster::move_effects().
effect_dripping_mechanical_fluid
const efftype_id effect_dripping_mechanical_fluid("dripping_mechanical_fluid") ("dripping_mechanical_fluid") static
Referenced by monster::make_bleed(), and monster::process_one_effect().
effect_emp
const efftype_id effect_emp("emp") ("emp") static
Referenced by monster::process_turn().
effect_fake_common_cold
const efftype_id effect_fake_common_cold("fake_common_cold") ("fake_common_cold") static
Referenced by monster::process_one_effect().
effect_fake_flu
const efftype_id effect_fake_flu("fake_flu") ("fake_flu") static
Referenced by monster::process_one_effect().
effect_grabbing
const efftype_id effect_grabbing("grabbing") ("grabbing") static
Referenced by monster::add_grab(), monster::is_grabbing(), and monster::remove_grab().
effect_has_bag
const efftype_id effect_has_bag("has_bag") ("has_bag") static
Referenced by monster::monster().
effect_heavysnare
const efftype_id effect_heavysnare("heavysnare") ("heavysnare") static
Referenced by monster::color_with_effects(), monster::die(), monster::get_dodge(), and monster::move_effects().
effect_hit_by_player
const efftype_id effect_hit_by_player("hit_by_player") ("hit_by_player") static
Referenced by monster::melee_attack().
effect_in_pit
const efftype_id effect_in_pit("in_pit") ("in_pit") static
Referenced by monster::move_effects().
effect_leashed
const efftype_id effect_leashed("leashed") ("leashed") static
Referenced by monster::monster().
effect_lightsnare
const efftype_id effect_lightsnare("lightsnare") ("lightsnare") static
Referenced by monster::color_with_effects(), monster::get_dodge(), and monster::move_effects().
effect_maimed_arm
const efftype_id effect_maimed_arm("maimed_arm") ("maimed_arm") static
Referenced by monster::has_weapon().
effect_monster_armor
const efftype_id effect_monster_armor("monster_armor") ("monster_armor") static
Referenced by monster::get_worn_armor_val(), monster::monster(), and monster::name_with_armor().
effect_monster_saddled
const efftype_id effect_monster_saddled("monster_saddled") ("monster_saddled") static
Referenced by monster::monster().
effect_natures_commune
const efftype_id effect_natures_commune("natures_commune") ("natures_commune") static
Referenced by monster::attitude().
effect_nemesis_buff
const efftype_id effect_nemesis_buff("nemesis_buff") ("nemesis_buff") static
Referenced by monster::process_effects().
effect_no_sight
const efftype_id effect_no_sight("no_sight") ("no_sight") static
Referenced by monster::process_one_effect().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by monster::color_with_effects(), monster::is_immune_effect(), and monster::process_one_effect().
effect_pacified
const efftype_id effect_pacified("pacified") ("pacified") static
Referenced by monster::color_with_effects().
effect_paralyzepoison
const efftype_id effect_paralyzepoison("paralyzepoison") ("paralyzepoison") static
Referenced by monster::is_immune_effect(), and monster::melee_attack().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by monster::is_pet().
effect_photophobia
const efftype_id effect_photophobia("photophobia") ("photophobia") static
Referenced by monster::process_effects().
effect_poison
const efftype_id effect_poison("poison") ("poison") static
Referenced by monster::is_immune_effect(), and monster::melee_attack().
effect_psi_stunned
const efftype_id effect_psi_stunned("psi_stunned") ("psi_stunned") static
Referenced by monster::can_act(), and monster::color_with_effects().
effect_ridden
const efftype_id effect_ridden("ridden") ("ridden") static
Referenced by monster::die(), monster::melee_attack(), monster::on_move(), and monster::print_info().
effect_run
const efftype_id effect_run("run") ("run") static
Referenced by monster::deal_projectile_attack(), monster::melee_attack(), and monster::process_one_effect().
effect_spooked
const efftype_id effect_spooked("spooked") ("spooked") static
Referenced by monster::process_effects().
effect_spooked_recent
const efftype_id effect_spooked_recent("spooked_recent") ("spooked_recent") static
Referenced by monster::process_effects().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by monster::can_act(), monster::color_with_effects(), monster::is_immune_effect(), and monster::stability_roll().
effect_supercharged
const efftype_id effect_supercharged("supercharged") ("supercharged") static
Referenced by monster::process_turn().
effect_tied
const efftype_id effect_tied("tied") ("tied") static
Referenced by monster::color_with_effects(), monster::get_dodge(), and monster::move_effects().
effect_tpollen
const efftype_id effect_tpollen("tpollen") ("tpollen") static
Referenced by monster::is_immune_effect().
effect_venom_dmg
const efftype_id effect_venom_dmg("venom_dmg") ("venom_dmg") static
Referenced by monster::is_immune_effect().
effect_venom_player1
const efftype_id effect_venom_player1("venom_player1") ("venom_player1") static
Referenced by monster::is_immune_effect().
effect_venom_player2
const efftype_id effect_venom_player2("venom_player2") ("venom_player2") static
Referenced by monster::is_immune_effect().
effect_venom_weaken
const efftype_id effect_venom_weaken("venom_weaken") ("venom_weaken") static
Referenced by monster::is_immune_effect().
effect_webbed
const efftype_id effect_webbed("webbed") ("webbed") static
Referenced by monster::can_act(), and monster::move_effects().
effect_worked_on
const efftype_id effect_worked_on("worked_on") ("worked_on") static
Referenced by monster::move_effects().
emit_emit_shock_cloud
const emit_id emit_emit_shock_cloud("emit_shock_cloud") ("emit_shock_cloud") static
Referenced by monster::process_turn().
emit_emit_shock_cloud_big
const emit_id emit_emit_shock_cloud_big("emit_shock_cloud_big") ("emit_shock_cloud_big") static
Referenced by monster::process_turn().
itype_milk
const itype_id itype_milk("milk") ("milk") static
Referenced by monster::refill_udders().
itype_milk_raw
const itype_id itype_milk_raw("milk_raw") ("milk_raw") static
Referenced by monster::refill_udders().
json_flag_BIONIC_LIMB
const json_character_flag json_flag_BIONIC_LIMB("BIONIC_LIMB") ("BIONIC_LIMB") static
Referenced by monster::melee_attack().
json_flag_DISABLE_FLIGHT
const flag_id json_flag_DISABLE_FLIGHT("DISABLE_FLIGHT") ("DISABLE_FLIGHT") static
Referenced by monster::flies().
json_flag_GRAB
const flag_id json_flag_GRAB("GRAB") ("GRAB") static
Referenced by monster::die(), monster::move_effects(), and monster::process_turn().
json_flag_GRAB_FILTER
const flag_id json_flag_GRAB_FILTER("GRAB_FILTER") ("GRAB_FILTER") static
Referenced by monster::die(), monster::move_effects(), and monster::process_turn().
material_bone
const material_id material_bone("bone") ("bone") static
Referenced by monster::make_fungus(), and monster::name_with_armor().
material_flesh
const material_id material_flesh("flesh") ("flesh") static
Referenced by monster::is_immune_effect(), monster::make_fungus(), monster::name_with_armor(), monster::on_load(), and monster::process_one_effect().
material_hflesh
const material_id material_hflesh("hflesh") ("hflesh") static
Referenced by monster::make_fungus(), and monster::name_with_armor().
material_iflesh
const material_id material_iflesh("iflesh") ("iflesh") static
Referenced by monster::is_immune_effect(), monster::make_fungus(), monster::name_with_armor(), monster::on_load(), and monster::process_one_effect().
material_iron
const material_id material_iron("iron") ("iron") static
Referenced by monster::name_with_armor().
material_steel
const material_id material_steel("steel") ("steel") static
Referenced by monster::is_immune_damage(), and monster::name_with_armor().
material_stone
const material_id material_stone("stone") ("stone") static
Referenced by monster::is_immune_damage().
material_veggy
const material_id material_veggy("veggy") ("veggy") static
Referenced by monster::make_fungus(), monster::name_with_armor(), monster::on_load(), and monster::process_one_effect().
monfaction_acid_ant
const mfaction_str_id monfaction_acid_ant("acid_ant") ("acid_ant") static
Referenced by monster::attitude().
monfaction_ant
const mfaction_str_id monfaction_ant("ant") ("ant") static
Referenced by monster::attitude().
monfaction_bee
const mfaction_str_id monfaction_bee("bee") ("bee") static
Referenced by monster::attitude().
monfaction_nether_player_hate
const mfaction_str_id monfaction_nether_player_hate("nether_player_hate") ("nether_player_hate") static
Referenced by monster::attitude().
monfaction_wasp
const mfaction_str_id monfaction_wasp("wasp") ("wasp") static
Referenced by monster::attitude().
size_names
const std::map<creature_size, translation> size_names static
Initial value:
{
    { creature_size::tiny, to_translation( "size adj", "tiny" ) },
    { creature_size::small, to_translation( "size adj", "small" ) },
    { creature_size::medium, to_translation( "size adj", "medium" ) },
    { creature_size::large, to_translation( "size adj", "large" ) },
    { creature_size::huge, to_translation( "size adj", "huge" ) },
}
Definition at line 204 of file monster.cpp.
Referenced by monster::extended_description(), and monster::print_info().
species_AMPHIBIAN
const species_id species_AMPHIBIAN("AMPHIBIAN") ("AMPHIBIAN") static
Referenced by monster::attitude().
species_CYBORG
const species_id species_CYBORG("CYBORG") ("CYBORG") static
Referenced by monster::is_electrical().
species_FISH
const species_id species_FISH("FISH") ("FISH") static
Referenced by monster::move_effects().
species_FUNGUS
const species_id species_FUNGUS("FUNGUS") ("FUNGUS") static
Referenced by monster::attitude(), and monster::make_fungus().
species_HORROR
const species_id species_HORROR("HORROR") ("HORROR") static
Referenced by monster::is_nether().
species_LEECH_PLANT
const species_id species_LEECH_PLANT("LEECH_PLANT") ("LEECH_PLANT") static
Referenced by monster::is_immune_effect().
species_MAMMAL
const species_id species_MAMMAL("MAMMAL") ("MAMMAL") static
Referenced by monster::attitude().
species_MIGO
const species_id species_MIGO("MIGO") ("MIGO") static
Referenced by monster::is_immune_effect().
species_MOLLUSK
const species_id species_MOLLUSK("MOLLUSK") ("MOLLUSK") static
Referenced by monster::move_effects().
species_NETHER
const species_id species_NETHER("NETHER") ("NETHER") static
Referenced by monster::is_immune_effect(), and monster::is_nether().
species_nether_player_hate
const species_id species_nether_player_hate("nether_player_hate") ("nether_player_hate") static
Referenced by monster::is_nether().
species_PLANT
const species_id species_PLANT("PLANT") ("PLANT") static
Referenced by monster::is_immune_effect().
species_PSI_NULL
const species_id species_PSI_NULL("PSI_NULL") ("PSI_NULL") static
Referenced by monster::has_mind().
species_ROBOT
const species_id species_ROBOT("ROBOT") ("ROBOT") static
Referenced by monster::is_electrical(), monster::make_bleed(), and monster::move_effects().
species_ZOMBIE
const species_id species_ZOMBIE("ZOMBIE") ("ZOMBIE") static
Referenced by monster::attitude(), monster::has_mind(), and monster::is_immune_effect().
ter_t_gas_pump
const ter_str_id ter_t_gas_pump("t_gas_pump") ("t_gas_pump") static
Referenced by monster::process_turn().
ter_t_gas_pump_a
const ter_str_id ter_t_gas_pump_a("t_gas_pump_a") ("t_gas_pump_a") static
Referenced by monster::process_turn().
trait_ANIMALDISCORD
const trait_id trait_ANIMALDISCORD("ANIMALDISCORD") ("ANIMALDISCORD") static
Referenced by monster::attitude().
trait_ANIMALDISCORD2
const trait_id trait_ANIMALDISCORD2("ANIMALDISCORD2") ("ANIMALDISCORD2") static
Referenced by monster::attitude().
trait_ANIMALEMPATH
const trait_id trait_ANIMALEMPATH("ANIMALEMPATH") ("ANIMALEMPATH") static
Referenced by monster::attitude().
trait_ANIMALEMPATH2
const trait_id trait_ANIMALEMPATH2("ANIMALEMPATH2") ("ANIMALEMPATH2") static
Referenced by monster::attitude().
trait_BEE
const trait_id trait_BEE("BEE") ("BEE") static
Referenced by monster::attitude().
trait_FLOWERS
const trait_id trait_FLOWERS("FLOWERS") ("FLOWERS") static
Referenced by monster::attitude().
trait_INATTENTIVE
const trait_id trait_INATTENTIVE("INATTENTIVE") ("INATTENTIVE") static
Referenced by monster::extended_description(), and monster::print_info().
trait_KILLER
const trait_id trait_KILLER("KILLER") ("KILLER") static
Referenced by monster::die().
trait_MYCUS_FRIEND
const trait_id trait_MYCUS_FRIEND("MYCUS_FRIEND") ("MYCUS_FRIEND") static
Referenced by monster::attitude().
trait_PHEROMONE_AMPHIBIAN
const trait_id trait_PHEROMONE_AMPHIBIAN("PHEROMONE_AMPHIBIAN") ("PHEROMONE_AMPHIBIAN") static
Referenced by monster::attitude().
trait_PHEROMONE_INSECT
const trait_id trait_PHEROMONE_INSECT("PHEROMONE_INSECT") ("PHEROMONE_INSECT") static
Referenced by monster::attitude().
trait_PHEROMONE_MAMMAL
const trait_id trait_PHEROMONE_MAMMAL("PHEROMONE_MAMMAL") ("PHEROMONE_MAMMAL") static
Referenced by monster::attitude().
trait_TERRIFYING
const trait_id trait_TERRIFYING("TERRIFYING") ("TERRIFYING") static
Referenced by monster::attitude().
trait_THRESH_MYCUS
const trait_id trait_THRESH_MYCUS("THRESH_MYCUS") ("THRESH_MYCUS") static
Referenced by monster::attitude().
UPGRADE_MAX_ITERS
constexpr int UPGRADE_MAX_ITERS = 5 static constexpr
Definition at line 202 of file monster.cpp.
Referenced by monster::next_upgrade_time().