Cataclysm DDA: src/morale_types.cpp File Reference
morale_types.cpp File Reference
#include "morale_types.h"
#include <cstddef>
#include <set>
#include <vector>
#include "generic_factory.h"
#include "itype.h"
#include "json.h"
#include "string_formatter.h"
#include "debug.h"
Namespaces
anonymous_namespace{morale_types.cpp}
Variables
const morale_type MORALE_ACCOMPLISHMENT ("morale_accomplishment")
const morale_type MORALE_ANTIFRUIT ("morale_antifruit")
const morale_type MORALE_ANTIJUNK ("morale_antijunk")
const morale_type MORALE_ANTIMEAT ("morale_antimeat")
const morale_type MORALE_ANTIVEGGY ("morale_antiveggy")
const morale_type MORALE_ANTIWHEAT ("morale_antiwheat")
const morale_type MORALE_ATE_WITHOUT_TABLE ("morale_ate_without_table")
const morale_type MORALE_ATE_WITH_TABLE ("morale_ate_with_table")
const morale_type MORALE_BOOK ("morale_book")
const morale_type MORALE_BUTCHER ("morale_butcher")
const morale_type MORALE_CANNIBAL ("morale_cannibal")
const morale_type MORALE_CHAT ("morale_chat")
const morale_type MORALE_COLD ("morale_cold")
const morale_type MORALE_COMFY ("morale_comfy")
const morale_type MORALE_CRAVING_ALCOHOL ("morale_craving_alcohol")
const morale_type MORALE_CRAVING_CAFFEINE ("morale_craving_caffeine")
const morale_type MORALE_CRAVING_COCAINE ("morale_craving_cocaine")
const morale_type MORALE_CRAVING_CRACK ("morale_craving_crack")
const morale_type MORALE_CRAVING_DIAZEPAM ("morale_craving_diazepam")
const morale_type MORALE_CRAVING_MARLOSS ("morale_craving_marloss")
const morale_type MORALE_CRAVING_MUTAGEN ("morale_craving_mutagen")
const morale_type MORALE_CRAVING_NICOTINE ("morale_craving_nicotine")
const morale_type MORALE_CRAVING_OPIATE ("morale_craving_opiate")
const morale_type MORALE_CRAVING_SPEED ("morale_craving_speed")
const morale_type MORALE_DRIED_OFF ("morale_dried_off")
const morale_type MORALE_FAILURE ("morale_failure")
const morale_type MORALE_FEELING_BAD ("morale_feeling_bad")
const morale_type MORALE_FEELING_GOOD ("morale_feeling_good")
const morale_type MORALE_FOOD_BAD ("morale_food_bad")
const morale_type MORALE_FOOD_GOOD ("morale_food_good")
const morale_type MORALE_FOOD_HOT ("morale_food_hot")
const morale_type MORALE_FUNERAL ("morale_funeral")
const morale_type MORALE_GAME ("morale_game")
const morale_type MORALE_GAME_FOUND_KITTEN ("morale_game_found_kitten")
const morale_type MORALE_GRAVEDIGGER ("morale_gravedigger")
const morale_type MORALE_HAIRCUT ("morale_haircut")
const morale_type MORALE_HONEY ("morale_honey")
const morale_type MORALE_HOT ("morale_hot")
const morale_type MORALE_KILLED_FRIEND ("morale_killed_friend")
const morale_type MORALE_KILLED_INNOCENT ("morale_killed_innocent")
const morale_type MORALE_KILLED_MONSTER ("morale_killed_monster")
const morale_type MORALE_KILLER_HAS_KILLED ("morale_killer_has_killed")
const morale_type MORALE_KILLER_NEED_TO_KILL ("morale_killer_need_to_kill")
const morale_type MORALE_LACTOSE ("morale_lactose")
const morale_type MORALE_MARLOSS ("morale_marloss")
const morale_type MORALE_MEATARIAN ("morale_meatarian")
const morale_type MORALE_MOODSWING ("morale_moodswing")
const morale_type MORALE_MUSIC ("morale_music")
const morale_type MORALE_MUTAGEN ("morale_mutagen")
const morale_type MORALE_MUTAGEN_CHIMERA ("morale_mutagen_chimera")
const morale_type MORALE_MUTAGEN_ELF ("morale_mutagen_elf")
const morale_type MORALE_MUTAGEN_MUTATION ("morale_mutagen_mutation")
const morale_type MORALE_MUTILATE_CORPSE ("morale_mutilate_corpse")
const morale_type MORALE_NO_DIGEST ("morale_no_digest")
const morale_type MORALE_NULL ("morale_null")
const morale_type MORALE_PERM_BADTEMPER ("morale_perm_badtemper")
const morale_type MORALE_PERM_CONSTRAINED ("morale_perm_constrained")
const morale_type MORALE_PERM_DEBUG ("morale_perm_debug")
const morale_type MORALE_PERM_FANCY ("morale_perm_fancy")
const morale_type MORALE_PERM_FILTHY ("morale_perm_filthy")
const morale_type MORALE_PERM_FPMODE_ON ("morale_perm_fpmode_on")
const morale_type MORALE_PERM_HOARDER ("morale_perm_hoarder")
const morale_type MORALE_PERM_MASOCHIST ("morale_perm_masochist")
const morale_type MORALE_PERM_NOFACE ("morale_perm_noface")
const morale_type MORALE_PERM_NOMAD ("morale_perm_nomad")
const morale_type MORALE_PERM_NUMB ("morale_perm_numb")
const morale_type MORALE_PERM_OPTIMIST ("morale_perm_optimist")
const morale_type MORALE_PERM_RADIOPHILE ("morale_perm_radiophile")
const morale_type MORALE_PHOTOS ("morale_photos")
const morale_type MORALE_PLAY_WITH_PET ("morale_play_with_pet")
const morale_type MORALE_PYROMANIA_NEARFIRE ("morale_pyromania_nearfire")
const morale_type MORALE_PYROMANIA_NOFIRE ("morale_pyromania_nofire")
const morale_type MORALE_PYROMANIA_STARTFIRE ("morale_pyromania_startfire")
const morale_type MORALE_SCREAM ("morale_scream")
const morale_type MORALE_SHAVE ("morale_shave")
const morale_type MORALE_SUPPORT ("morale_support")
const morale_type MORALE_SWEETTOOTH ("morale_sweettooth")
const morale_type MORALE_TREE_COMMUNION ("morale_tree_communion")
const morale_type MORALE_VEGETARIAN ("morale_vegetarian")
const morale_type MORALE_VOMITED ("morale_vomited")
const morale_type MORALE_WET ("morale_wet")
static const morale_type morale_accomplishment ("morale_accomplishment")
static const morale_type morale_antifruit ("morale_antifruit")
static const morale_type morale_antijunk ("morale_antijunk")
static const morale_type morale_antiwheat ("morale_antiwheat")
static const morale_type morale_ate_with_table ("morale_ate_with_table")
static const morale_type morale_ate_without_table ("morale_ate_without_table")
static const morale_type morale_book ("morale_book")
static const morale_type morale_butcher ("morale_butcher")
static const morale_type morale_cannibal ("morale_cannibal")
static const morale_type morale_chat ("morale_chat")
static const morale_type morale_cold ("morale_cold")
static const morale_type morale_comfy ("morale_comfy")
static const morale_type morale_craving_alcohol ("morale_craving_alcohol")
static const morale_type morale_craving_caffeine ("morale_craving_caffeine")
static const morale_type morale_craving_cocaine ("morale_craving_cocaine")
static const morale_type morale_craving_crack ("morale_craving_crack")
static const morale_type morale_craving_diazepam ("morale_craving_diazepam")
static const morale_type morale_craving_marloss ("morale_craving_marloss")
static const morale_type morale_craving_mutagen ("morale_craving_mutagen")
static const morale_type morale_craving_nicotine ("morale_craving_nicotine")
static const morale_type morale_craving_opiate ("morale_craving_opiate")
static const morale_type morale_craving_speed ("morale_craving_speed")
static const morale_type morale_dried_off ("morale_dried_off")
static const morale_type morale_failure ("morale_failure")
static const morale_type morale_feeling_bad ("morale_feeling_bad")
static const morale_type morale_feeling_good ("morale_feeling_good")
static const morale_type morale_food_bad ("morale_food_bad")
static const morale_type morale_food_good ("morale_food_good")
static const morale_type morale_food_hot ("morale_food_hot")
static const morale_type morale_funeral ("morale_funeral")
static const morale_type morale_game ("morale_game")
static const morale_type morale_game_found_kitten ("morale_game_found_kitten")
static const morale_type morale_gravedigger ("morale_gravedigger")
static const morale_type morale_haircut ("morale_haircut")
static const morale_type morale_honey ("morale_honey")
static const morale_type morale_hot ("morale_hot")
static const morale_type morale_killed_friend ("morale_killed_friend")
static const morale_type morale_killed_innocent ("morale_killed_innocent")
static const morale_type morale_killed_monster ("morale_killed_monster")
static const morale_type morale_killer_has_killed ("morale_killer_has_killed")
static const morale_type morale_killer_need_to_kill ("morale_killer_need_to_kill")
static const morale_type morale_lactose ("morale_lactose")
static const morale_type morale_marloss ("morale_marloss")
static const morale_type morale_meatarian ("morale_meatarian")
static const morale_type morale_moodswing ("morale_moodswing")
static const morale_type morale_music ("morale_music")
static const morale_type morale_mutagen ("morale_mutagen")
static const morale_type morale_mutagen_chimera ("morale_mutagen_chimera")
static const morale_type morale_mutagen_elf ("morale_mutagen_elf")
static const morale_type morale_mutagen_mutation ("morale_mutagen_mutation")
static const morale_type morale_mutilate_corpse ("morale_mutilate_corpse")
static const morale_type morale_no_digest ("morale_no_digest")
static const morale_type morale_null ("morale_null")
static const morale_type morale_perm_badtemper ("morale_perm_badtemper")
static const morale_type morale_perm_constrained ("morale_perm_constrained")
static const morale_type morale_perm_fancy ("morale_perm_fancy")
static const morale_type morale_perm_filthy ("morale_perm_filthy")
static const morale_type morale_perm_hoarder ("morale_perm_hoarder")
static const morale_type morale_perm_masochist ("morale_perm_masochist")
static const morale_type morale_perm_nomad ("morale_perm_nomad")
static const morale_type morale_perm_numb ("morale_perm_numb")
static const morale_type morale_perm_optimist ("morale_perm_optimist")
static const morale_type morale_photos ("morale_photos")
static const morale_type morale_play_with_pet ("morale_play_with_pet")
static const morale_type morale_pyromania_nearfire ("morale_pyromania_nearfire")
static const morale_type morale_pyromania_nofire ("morale_pyromania_nofire")
static const morale_type morale_pyromania_startfire ("morale_pyromania_startfire")
static const morale_type morale_scream ("morale_scream")
static const morale_type morale_shave ("morale_shave")
static const morale_type morale_support ("morale_support")
static const morale_type morale_sweettooth ("morale_sweettooth")
static const morale_type morale_vegetarian ("morale_vegetarian")
static const morale_type morale_vomited ("morale_vomited")
static const morale_type morale_wet ("morale_wet")
generic_factory< morale_type_data > anonymous_namespace{morale_types.cpp}::morale_data ("morale type")
Variable Documentation
MORALE_ACCOMPLISHMENT
const morale_type MORALE_ACCOMPLISHMENT("morale_accomplishment") ("morale_accomplishment")
morale_accomplishment
const morale_type morale_accomplishment("morale_accomplishment") ("morale_accomplishment") static
Referenced by morale_type_data::convert_legacy().
MORALE_ANTIFRUIT
const morale_type MORALE_ANTIFRUIT("morale_antifruit") ("morale_antifruit")
Referenced by Character::allergy_type().
morale_antifruit
const morale_type morale_antifruit("morale_antifruit") ("morale_antifruit") static
Referenced by morale_type_data::convert_legacy().
MORALE_ANTIJUNK
const morale_type MORALE_ANTIJUNK("morale_antijunk") ("morale_antijunk")
Referenced by Character::allergy_type().
morale_antijunk
const morale_type morale_antijunk("morale_antijunk") ("morale_antijunk") static
Referenced by morale_type_data::convert_legacy().
MORALE_ANTIMEAT
const morale_type MORALE_ANTIMEAT("morale_antimeat") ("morale_antimeat")
Referenced by Character::allergy_type().
MORALE_ANTIVEGGY
const morale_type MORALE_ANTIVEGGY("morale_antiveggy") ("morale_antiveggy")
Referenced by Character::allergy_type().
MORALE_ANTIWHEAT
const morale_type MORALE_ANTIWHEAT("morale_antiwheat") ("morale_antiwheat")
Referenced by Character::allergy_type().
morale_antiwheat
const morale_type morale_antiwheat("morale_antiwheat") ("morale_antiwheat") static
Referenced by morale_type_data::convert_legacy().
MORALE_ATE_WITH_TABLE
const morale_type MORALE_ATE_WITH_TABLE("morale_ate_with_table") ("morale_ate_with_table")
Referenced by Character::modify_morale().
morale_ate_with_table
const morale_type morale_ate_with_table("morale_ate_with_table") ("morale_ate_with_table") static
Referenced by morale_type_data::convert_legacy().
MORALE_ATE_WITHOUT_TABLE
const morale_type MORALE_ATE_WITHOUT_TABLE("morale_ate_without_table") ("morale_ate_without_table")
Referenced by Character::modify_morale().
morale_ate_without_table
const morale_type morale_ate_without_table("morale_ate_without_table") ("morale_ate_without_table") static
Referenced by morale_type_data::convert_legacy().
MORALE_BOOK
const morale_type MORALE_BOOK("morale_book") ("morale_book")
Referenced by read_activity_actor::npc_read(), and read_activity_actor::player_read().
morale_book
const morale_type morale_book("morale_book") ("morale_book") static
Referenced by morale_type_data::convert_legacy().
MORALE_BUTCHER
const morale_type MORALE_BUTCHER("morale_butcher") ("morale_butcher")
Referenced by set_up_butchery().
morale_butcher
const morale_type morale_butcher("morale_butcher") ("morale_butcher") static
Referenced by morale_type_data::convert_legacy().
MORALE_CANNIBAL
const morale_type MORALE_CANNIBAL("morale_cannibal") ("morale_cannibal")
Referenced by Character::modify_morale().
morale_cannibal
const morale_type morale_cannibal("morale_cannibal") ("morale_cannibal") static
Referenced by morale_type_data::convert_legacy().
MORALE_CHAT
const morale_type MORALE_CHAT("morale_chat") ("morale_chat")
Referenced by talk_function::morale_chat(), and talk_function::morale_chat_activity().
morale_chat
const morale_type morale_chat("morale_chat") ("morale_chat") static
Referenced by morale_type_data::convert_legacy(), and talk_effect_t::parse_string_effect().
MORALE_COLD
const morale_type MORALE_COLD("morale_cold") ("morale_cold")
Referenced by player_morale::update_bodytemp_penalty().
morale_cold
const morale_type morale_cold("morale_cold") ("morale_cold") static
Referenced by morale_type_data::convert_legacy().
MORALE_COMFY
const morale_type MORALE_COMFY("morale_comfy") ("morale_comfy")
Referenced by Character::update_bodytemp().
morale_comfy
const morale_type morale_comfy("morale_comfy") ("morale_comfy") static
Referenced by morale_type_data::convert_legacy().
MORALE_CRAVING_ALCOHOL
const morale_type MORALE_CRAVING_ALCOHOL("morale_craving_alcohol") ("morale_craving_alcohol")
Referenced by alcohol_diazepam_add().
morale_craving_alcohol
const morale_type morale_craving_alcohol("morale_craving_alcohol") ("morale_craving_alcohol") static
Referenced by morale_type_data::convert_legacy().
MORALE_CRAVING_CAFFEINE
const morale_type MORALE_CRAVING_CAFFEINE("morale_craving_caffeine") ("morale_craving_caffeine")
morale_craving_caffeine
const morale_type morale_craving_caffeine("morale_craving_caffeine") ("morale_craving_caffeine") static
Referenced by morale_type_data::convert_legacy().
MORALE_CRAVING_COCAINE
const morale_type MORALE_CRAVING_COCAINE("morale_craving_cocaine") ("morale_craving_cocaine")
Referenced by crack_coke_add().
morale_craving_cocaine
const morale_type morale_craving_cocaine("morale_craving_cocaine") ("morale_craving_cocaine") static
Referenced by morale_type_data::convert_legacy().
MORALE_CRAVING_CRACK
const morale_type MORALE_CRAVING_CRACK("morale_craving_crack") ("morale_craving_crack")
Referenced by crack_coke_add().
morale_craving_crack
const morale_type morale_craving_crack("morale_craving_crack") ("morale_craving_crack") static
Referenced by morale_type_data::convert_legacy().
MORALE_CRAVING_DIAZEPAM
const morale_type MORALE_CRAVING_DIAZEPAM("morale_craving_diazepam") ("morale_craving_diazepam")
Referenced by alcohol_diazepam_add().
morale_craving_diazepam
const morale_type morale_craving_diazepam("morale_craving_diazepam") ("morale_craving_diazepam") static
Referenced by morale_type_data::convert_legacy().
MORALE_CRAVING_MARLOSS
const morale_type MORALE_CRAVING_MARLOSS("morale_craving_marloss") ("morale_craving_marloss")
morale_craving_marloss
const morale_type morale_craving_marloss("morale_craving_marloss") ("morale_craving_marloss") static
Referenced by morale_type_data::convert_legacy().
MORALE_CRAVING_MUTAGEN
const morale_type MORALE_CRAVING_MUTAGEN("morale_craving_mutagen") ("morale_craving_mutagen")
morale_craving_mutagen
const morale_type morale_craving_mutagen("morale_craving_mutagen") ("morale_craving_mutagen") static
Referenced by morale_type_data::convert_legacy().
MORALE_CRAVING_NICOTINE
const morale_type MORALE_CRAVING_NICOTINE("morale_craving_nicotine") ("morale_craving_nicotine")
Referenced by nicotine_effect().
morale_craving_nicotine
const morale_type morale_craving_nicotine("morale_craving_nicotine") ("morale_craving_nicotine") static
Referenced by morale_type_data::convert_legacy().
MORALE_CRAVING_OPIATE
const morale_type MORALE_CRAVING_OPIATE("morale_craving_opiate") ("morale_craving_opiate")
Referenced by opiate_effect().
morale_craving_opiate
const morale_type morale_craving_opiate("morale_craving_opiate") ("morale_craving_opiate") static
Referenced by morale_type_data::convert_legacy().
MORALE_CRAVING_SPEED
const morale_type MORALE_CRAVING_SPEED("morale_craving_speed") ("morale_craving_speed")
Referenced by amphetamine_effect().
morale_craving_speed
const morale_type morale_craving_speed("morale_craving_speed") ("morale_craving_speed") static
Referenced by morale_type_data::convert_legacy().
MORALE_DRIED_OFF
const morale_type MORALE_DRIED_OFF("morale_dried_off") ("morale_dried_off")
morale_dried_off
const morale_type morale_dried_off("morale_dried_off") ("morale_dried_off") static
Referenced by morale_type_data::convert_legacy().
MORALE_FAILURE
const morale_type MORALE_FAILURE("morale_failure") ("morale_failure")
Referenced by item::handle_craft_failure().
morale_failure
const morale_type morale_failure("morale_failure") ("morale_failure") static
Referenced by morale_type_data::convert_legacy().
MORALE_FEELING_BAD
const morale_type MORALE_FEELING_BAD("morale_feeling_bad") ("morale_feeling_bad")
Referenced by suffer::from_chemimbalance().
morale_feeling_bad
const morale_type morale_feeling_bad("morale_feeling_bad") ("morale_feeling_bad") static
Referenced by morale_type_data::convert_legacy().
MORALE_FEELING_GOOD
const morale_type MORALE_FEELING_GOOD("morale_feeling_good") ("morale_feeling_good")
Referenced by workout_activity_actor::do_turn(), meditate_activity_actor::finish(), suffer::from_chemimbalance(), Character::process_bionic(), activity_handlers::vibe_do_turn(), and activity_handlers::vibe_finish().
morale_feeling_good
const morale_type morale_feeling_good("morale_feeling_good") ("morale_feeling_good") static
Referenced by morale_type_data::convert_legacy().
MORALE_FOOD_BAD
const morale_type MORALE_FOOD_BAD("morale_food_bad") ("morale_food_bad")
Referenced by iuse::blech(), and Character::modify_morale().
morale_food_bad
const morale_type morale_food_bad("morale_food_bad") ("morale_food_bad") static
Referenced by morale_type_data::convert_legacy().
MORALE_FOOD_GOOD
const morale_type MORALE_FOOD_GOOD("morale_food_good") ("morale_food_good")
Referenced by iuse::datura(), Character::modify_morale(), iuse::plantblech(), and avatar::vomit().
morale_food_good
const morale_type morale_food_good("morale_food_good") ("morale_food_good") static
Referenced by morale_type_data::convert_legacy().
MORALE_FOOD_HOT
const morale_type MORALE_FOOD_HOT("morale_food_hot") ("morale_food_hot")
Referenced by Character::modify_morale(), and avatar::vomit().
morale_food_hot
const morale_type morale_food_hot("morale_food_hot") ("morale_food_hot") static
Referenced by morale_type_data::convert_legacy().
MORALE_FUNERAL
const morale_type MORALE_FUNERAL("morale_funeral") ("morale_funeral")
Referenced by construct::done_grave().
morale_funeral
const morale_type morale_funeral("morale_funeral") ("morale_funeral") static
Referenced by morale_type_data::convert_legacy().
MORALE_GAME
const morale_type MORALE_GAME("morale_game") ("morale_game")
Referenced by activity_handlers::generic_game_finish(), activity_handlers::generic_game_turn_handler(), and iuse::portable_game().
morale_game
const morale_type morale_game("morale_game") ("morale_game") static
Referenced by morale_type_data::convert_legacy().
MORALE_GAME_FOUND_KITTEN
const morale_type MORALE_GAME_FOUND_KITTEN("morale_game_found_kitten") ("morale_game_found_kitten")
Referenced by iuse::portable_game().
morale_game_found_kitten
const morale_type morale_game_found_kitten("morale_game_found_kitten") ("morale_game_found_kitten") static
Referenced by morale_type_data::convert_legacy().
MORALE_GRAVEDIGGER
const morale_type MORALE_GRAVEDIGGER("morale_gravedigger") ("morale_gravedigger")
Referenced by construct::do_turn_exhume().
morale_gravedigger
const morale_type morale_gravedigger("morale_gravedigger") ("morale_gravedigger") static
Referenced by morale_type_data::convert_legacy().
MORALE_HAIRCUT
const morale_type MORALE_HAIRCUT("morale_haircut") ("morale_haircut")
Referenced by talk_function::buy_haircut(), and haircut_activity_actor::finish().
morale_haircut
const morale_type morale_haircut("morale_haircut") ("morale_haircut") static
Referenced by morale_type_data::convert_legacy().
MORALE_HONEY
const morale_type MORALE_HONEY("morale_honey") ("morale_honey")
Referenced by Character::modify_morale(), and avatar::vomit().
morale_honey
const morale_type morale_honey("morale_honey") ("morale_honey") static
Referenced by morale_type_data::convert_legacy().
MORALE_HOT
const morale_type MORALE_HOT("morale_hot") ("morale_hot")
Referenced by player_morale::update_bodytemp_penalty().
morale_hot
const morale_type morale_hot("morale_hot") ("morale_hot") static
Referenced by morale_type_data::convert_legacy().
MORALE_KILLED_FRIEND
const morale_type MORALE_KILLED_FRIEND("morale_killed_friend") ("morale_killed_friend")
morale_killed_friend
const morale_type morale_killed_friend("morale_killed_friend") ("morale_killed_friend") static
Referenced by morale_type_data::convert_legacy().
MORALE_KILLED_INNOCENT
const morale_type MORALE_KILLED_INNOCENT("morale_killed_innocent") ("morale_killed_innocent")
Referenced by npc::die().
morale_killed_innocent
const morale_type morale_killed_innocent("morale_killed_innocent") ("morale_killed_innocent") static
Referenced by morale_type_data::convert_legacy().
MORALE_KILLED_MONSTER
const morale_type MORALE_KILLED_MONSTER("morale_killed_monster") ("morale_killed_monster")
Referenced by spell_effect::guilt().
morale_killed_monster
const morale_type morale_killed_monster("morale_killed_monster") ("morale_killed_monster") static
Referenced by morale_type_data::convert_legacy().
MORALE_KILLER_HAS_KILLED
const morale_type MORALE_KILLER_HAS_KILLED("morale_killer_has_killed") ("morale_killer_has_killed")
Referenced by monster::die(), npc::die(), and suffer::from_other_mutations().
morale_killer_has_killed
const morale_type morale_killer_has_killed("morale_killer_has_killed") ("morale_killer_has_killed") static
Referenced by morale_type_data::convert_legacy().
MORALE_KILLER_NEED_TO_KILL
const morale_type MORALE_KILLER_NEED_TO_KILL("morale_killer_need_to_kill") ("morale_killer_need_to_kill")
Referenced by monster::die(), and suffer::from_other_mutations().
morale_killer_need_to_kill
const morale_type morale_killer_need_to_kill("morale_killer_need_to_kill") ("morale_killer_need_to_kill") static
Referenced by morale_type_data::convert_legacy().
MORALE_LACTOSE
const morale_type MORALE_LACTOSE("morale_lactose") ("morale_lactose")
Referenced by Character::allergy_type().
morale_lactose
const morale_type morale_lactose("morale_lactose") ("morale_lactose") static
Referenced by morale_type_data::convert_legacy().
MORALE_MARLOSS
const morale_type MORALE_MARLOSS("morale_marloss") ("morale_marloss")
Referenced by marloss_common(), and iuse::mycus().
morale_marloss
const morale_type morale_marloss("morale_marloss") ("morale_marloss") static
Referenced by morale_type_data::convert_legacy().
MORALE_MEATARIAN
const morale_type MORALE_MEATARIAN("morale_meatarian") ("morale_meatarian")
Referenced by Character::modify_morale().
morale_meatarian
const morale_type morale_meatarian("morale_meatarian") ("morale_meatarian") static
Referenced by morale_type_data::convert_legacy().
MORALE_MOODSWING
const morale_type MORALE_MOODSWING("morale_moodswing") ("morale_moodswing")
Referenced by suffer::while_awake().
morale_moodswing
const morale_type morale_moodswing("morale_moodswing") ("morale_moodswing") static
Referenced by morale_type_data::convert_legacy().
MORALE_MUSIC
const morale_type MORALE_MUSIC("morale_music") ("morale_music")
Referenced by iuse::bell(), iuse::play_music(), and musical_instrument_actor::use().
morale_music
const morale_type morale_music("morale_music") ("morale_music") static
Referenced by morale_type_data::convert_legacy().
MORALE_MUTAGEN
const morale_type MORALE_MUTAGEN("morale_mutagen") ("morale_mutagen")
morale_mutagen
const morale_type morale_mutagen("morale_mutagen") ("morale_mutagen") static
Referenced by morale_type_data::convert_legacy().
MORALE_MUTAGEN_CHIMERA
const morale_type MORALE_MUTAGEN_CHIMERA("morale_mutagen_chimera") ("morale_mutagen_chimera")
morale_mutagen_chimera
const morale_type morale_mutagen_chimera("morale_mutagen_chimera") ("morale_mutagen_chimera") static
Referenced by morale_type_data::convert_legacy().
MORALE_MUTAGEN_ELF
const morale_type MORALE_MUTAGEN_ELF("morale_mutagen_elf") ("morale_mutagen_elf")
morale_mutagen_elf
const morale_type morale_mutagen_elf("morale_mutagen_elf") ("morale_mutagen_elf") static
Referenced by morale_type_data::convert_legacy().
MORALE_MUTAGEN_MUTATION
const morale_type MORALE_MUTAGEN_MUTATION("morale_mutagen_mutation") ("morale_mutagen_mutation")
morale_mutagen_mutation
const morale_type morale_mutagen_mutation("morale_mutagen_mutation") ("morale_mutagen_mutation") static
Referenced by morale_type_data::convert_legacy().
MORALE_MUTILATE_CORPSE
const morale_type MORALE_MUTILATE_CORPSE("morale_mutilate_corpse") ("morale_mutilate_corpse")
morale_mutilate_corpse
const morale_type morale_mutilate_corpse("morale_mutilate_corpse") ("morale_mutilate_corpse") static
Referenced by morale_type_data::convert_legacy().
MORALE_NO_DIGEST
const morale_type MORALE_NO_DIGEST("morale_no_digest") ("morale_no_digest")
Referenced by Character::modify_morale().
morale_no_digest
const morale_type morale_no_digest("morale_no_digest") ("morale_no_digest") static
Referenced by morale_type_data::convert_legacy().
MORALE_NULL
const morale_type MORALE_NULL("morale_null") ("morale_null")
Referenced by Character::allergy_type(), add_type::load(), Character::modify_addiction(), Character::modify_morale(), and Character::will_eat().
morale_null
const morale_type morale_null("morale_null") ("morale_null") static
Referenced by morale_type_data::convert_legacy().
MORALE_PERM_BADTEMPER
const morale_type MORALE_PERM_BADTEMPER("morale_perm_badtemper") ("morale_perm_badtemper")
Referenced by player_morale::get_temper_mult(), anonymous_namespace{morale.cpp}::is_permanent_morale(), and player_morale::player_morale().
morale_perm_badtemper
const morale_type morale_perm_badtemper("morale_perm_badtemper") ("morale_perm_badtemper") static
Referenced by morale_type_data::convert_legacy().
MORALE_PERM_CONSTRAINED
const morale_type MORALE_PERM_CONSTRAINED("morale_perm_constrained") ("morale_perm_constrained")
Referenced by anonymous_namespace{morale.cpp}::is_permanent_morale(), and player_morale::update_constrained_penalty().
morale_perm_constrained
const morale_type morale_perm_constrained("morale_perm_constrained") ("morale_perm_constrained") static
Referenced by morale_type_data::convert_legacy().
MORALE_PERM_DEBUG
const morale_type MORALE_PERM_DEBUG("morale_perm_debug") ("morale_perm_debug")
Referenced by debug_menu::character_edit_menu(), and anonymous_namespace{morale.cpp}::is_permanent_morale().
MORALE_PERM_FANCY
const morale_type MORALE_PERM_FANCY("morale_perm_fancy") ("morale_perm_fancy")
Referenced by anonymous_namespace{morale.cpp}::is_permanent_morale(), and player_morale::update_stylish_bonus().
morale_perm_fancy
const morale_type morale_perm_fancy("morale_perm_fancy") ("morale_perm_fancy") static
Referenced by morale_type_data::convert_legacy().
MORALE_PERM_FILTHY
const morale_type MORALE_PERM_FILTHY("morale_perm_filthy") ("morale_perm_filthy")
Referenced by anonymous_namespace{morale.cpp}::is_permanent_morale(), and player_morale::update_squeamish_penalty().
morale_perm_filthy
const morale_type morale_perm_filthy("morale_perm_filthy") ("morale_perm_filthy") static
Referenced by morale_type_data::convert_legacy().
MORALE_PERM_FPMODE_ON
const morale_type MORALE_PERM_FPMODE_ON("morale_perm_fpmode_on") ("morale_perm_fpmode_on")
Referenced by Character::apply_persistent_morale().
MORALE_PERM_HOARDER
const morale_type MORALE_PERM_HOARDER("morale_perm_hoarder") ("morale_perm_hoarder")
Referenced by Character::hoarder_morale_penalty().
morale_perm_hoarder
const morale_type morale_perm_hoarder("morale_perm_hoarder") ("morale_perm_hoarder") static
Referenced by morale_type_data::convert_legacy().
MORALE_PERM_MASOCHIST
const morale_type MORALE_PERM_MASOCHIST("morale_perm_masochist") ("morale_perm_masochist")
Referenced by anonymous_namespace{morale.cpp}::is_permanent_morale(), and player_morale::update_masochist_bonus().
morale_perm_masochist
const morale_type morale_perm_masochist("morale_perm_masochist") ("morale_perm_masochist") static
Referenced by morale_type_data::convert_legacy().
MORALE_PERM_NOFACE
const morale_type MORALE_PERM_NOFACE("morale_perm_noface") ("morale_perm_noface")
Referenced by Character::apply_persistent_morale().
MORALE_PERM_NOMAD
const morale_type MORALE_PERM_NOMAD("morale_perm_nomad") ("morale_perm_nomad")
Referenced by Character::apply_persistent_morale().
morale_perm_nomad
const morale_type morale_perm_nomad("morale_perm_nomad") ("morale_perm_nomad") static
Referenced by morale_type_data::convert_legacy().
MORALE_PERM_NUMB
const morale_type MORALE_PERM_NUMB("morale_perm_numb") ("morale_perm_numb")
Referenced by player_morale::get_temper_mult(), anonymous_namespace{morale.cpp}::is_permanent_morale(), and player_morale::player_morale().
morale_perm_numb
const morale_type morale_perm_numb("morale_perm_numb") ("morale_perm_numb") static
Referenced by morale_type_data::convert_legacy().
MORALE_PERM_OPTIMIST
const morale_type MORALE_PERM_OPTIMIST("morale_perm_optimist") ("morale_perm_optimist")
Referenced by player_morale::get_temper_mult(), anonymous_namespace{morale.cpp}::is_permanent_morale(), and player_morale::player_morale().
morale_perm_optimist
const morale_type morale_perm_optimist("morale_perm_optimist") ("morale_perm_optimist") static
Referenced by morale_type_data::convert_legacy().
MORALE_PERM_RADIOPHILE
const morale_type MORALE_PERM_RADIOPHILE("morale_perm_radiophile") ("morale_perm_radiophile")
Referenced by anonymous_namespace{morale.cpp}::is_permanent_morale(), and player_morale::update_radiophile_bonus().
MORALE_PHOTOS
const morale_type MORALE_PHOTOS("morale_photos") ("morale_photos")
Referenced by iuse::einktabletpc().
morale_photos
const morale_type morale_photos("morale_photos") ("morale_photos") static
Referenced by morale_type_data::convert_legacy().
MORALE_PLAY_WITH_PET
const morale_type MORALE_PLAY_WITH_PET("morale_play_with_pet") ("morale_play_with_pet")
Referenced by play_with_pet_activity_actor::finish().
morale_play_with_pet
const morale_type morale_play_with_pet("morale_play_with_pet") ("morale_play_with_pet") static
Referenced by morale_type_data::convert_legacy().
MORALE_PYROMANIA_NEARFIRE
const morale_type MORALE_PYROMANIA_NEARFIRE("morale_pyromania_nearfire") ("morale_pyromania_nearfire")
Referenced by suffer::from_other_mutations(), and Character::update_bodytemp().
morale_pyromania_nearfire
const morale_type morale_pyromania_nearfire("morale_pyromania_nearfire") ("morale_pyromania_nearfire") static
Referenced by morale_type_data::convert_legacy().
MORALE_PYROMANIA_NOFIRE
const morale_type MORALE_PYROMANIA_NOFIRE("morale_pyromania_nofire") ("morale_pyromania_nofire")
Referenced by Character::activate_bionic(), apply_ammo_effects(), projectile::apply_effects_damage(), damage_targets(), Creature::deal_damage_handle_type(), Character::fire_gun(), suffer::from_other_mutations(), iuse::grenade_inc_act(), iexamine::kiln_empty(), iuse::molotov_lit(), firestarter_actor::resolve_firestarter_use(), smoker_activate(), Character::update_bodytemp(), and iuse_transform::use().
morale_pyromania_nofire
const morale_type morale_pyromania_nofire("morale_pyromania_nofire") ("morale_pyromania_nofire") static
Referenced by morale_type_data::convert_legacy().
MORALE_PYROMANIA_STARTFIRE
const morale_type MORALE_PYROMANIA_STARTFIRE("morale_pyromania_startfire") ("morale_pyromania_startfire")
Referenced by Character::activate_bionic(), apply_ammo_effects(), projectile::apply_effects_damage(), damage_targets(), Creature::deal_damage_handle_type(), Character::fire_gun(), suffer::from_other_mutations(), iuse::grenade_inc_act(), iexamine::kiln_empty(), iuse::molotov_lit(), firestarter_actor::resolve_firestarter_use(), smoker_activate(), and iuse_transform::use().
morale_pyromania_startfire
const morale_type morale_pyromania_startfire("morale_pyromania_startfire") ("morale_pyromania_startfire") static
Referenced by morale_type_data::convert_legacy().
MORALE_SCREAM
const morale_type MORALE_SCREAM("morale_scream") ("morale_scream")
Referenced by timed_event::actualize().
morale_scream
const morale_type morale_scream("morale_scream") ("morale_scream") static
Referenced by morale_type_data::convert_legacy().
MORALE_SHAVE
const morale_type MORALE_SHAVE("morale_shave") ("morale_shave")
Referenced by talk_function::buy_shave(), and shave_activity_actor::finish().
morale_shave
const morale_type morale_shave("morale_shave") ("morale_shave") static
Referenced by morale_type_data::convert_legacy().
MORALE_SUPPORT
const morale_type MORALE_SUPPORT("morale_support") ("morale_support")
Referenced by mattack::slimespring().
morale_support
const morale_type morale_support("morale_support") ("morale_support") static
Referenced by morale_type_data::convert_legacy().
MORALE_SWEETTOOTH
const morale_type MORALE_SWEETTOOTH("morale_sweettooth") ("morale_sweettooth")
Referenced by Character::modify_morale().
morale_sweettooth
const morale_type morale_sweettooth("morale_sweettooth") ("morale_sweettooth") static
Referenced by morale_type_data::convert_legacy().
MORALE_TREE_COMMUNION
const morale_type MORALE_TREE_COMMUNION("morale_tree_communion") ("morale_tree_communion")
Referenced by activity_handlers::tree_communion_do_turn().
MORALE_VEGETARIAN
const morale_type MORALE_VEGETARIAN("morale_vegetarian") ("morale_vegetarian")
morale_vegetarian
const morale_type morale_vegetarian("morale_vegetarian") ("morale_vegetarian") static
Referenced by morale_type_data::convert_legacy().
MORALE_VOMITED
const morale_type MORALE_VOMITED("morale_vomited") ("morale_vomited")
Referenced by avatar::vomit().
morale_vomited
const morale_type morale_vomited("morale_vomited") ("morale_vomited") static
Referenced by morale_type_data::convert_legacy().
MORALE_WET
const morale_type MORALE_WET("morale_wet") ("morale_wet")
Referenced by Character::apply_wetness_morale(), and iuse::towel_common().
morale_wet
const morale_type morale_wet("morale_wet") ("morale_wet") static
Referenced by morale_type_data::convert_legacy().