Cataclysm DDA: src/morale.cpp File Reference
morale.cpp File Reference
#include "morale.h"
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <numeric>
#include <set>
#include <string>
#include <utility>
#include "bodypart.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "color.h"
#include "cursesdef.h"
#include "debug.h"
#include "enums.h"
#include "input_context.h"
#include "item.h"
#include "localized_comparator.h"
#include "make_static.h"
#include "morale_types.h"
#include "output.h"
#include "point.h"
#include "string_formatter.h"
#include "translations.h"
#include "ui_manager.h"
Classes
struct morale_mult
Namespaces
anonymous_namespace{morale.cpp}
morale_mults
Functions
bool anonymous_namespace{morale.cpp}::is_permanent_morale (const morale_type &id)
static double operator* (double morale, const morale_mult &mult)
static int operator*= (int &morale, const morale_mult &mult)
Variables
static const efftype_id effect_cold ("cold")
static const efftype_id effect_hot ("hot")
static const efftype_id effect_took_prozac ("took_prozac")
static const efftype_id effect_took_prozac_bad ("took_prozac_bad")
static const trait_id trait_BADTEMPER ("BADTEMPER")
static const trait_id trait_CENOBITE ("CENOBITE")
static const trait_id trait_CHLOROMORPH ("CHLOROMORPH")
static const trait_id trait_FLOWERS ("FLOWERS")
static const trait_id trait_LEAVES2 ("LEAVES2")
static const trait_id trait_LEAVES3 ("LEAVES3")
static const trait_id trait_MASOCHIST ("MASOCHIST")
static const trait_id trait_MASOCHIST_MED ("MASOCHIST_MED")
static const trait_id trait_NUMB ("NUMB")
static const trait_id trait_OPTIMISTIC ("OPTIMISTIC")
static const trait_id trait_RADIOPHILE ("RADIOPHILE")
static const trait_id trait_ROOTS1 ("ROOTS1")
static const trait_id trait_ROOTS2 ("ROOTS2")
static const trait_id trait_ROOTS3 ("ROOTS3")
static const trait_id trait_STYLISH ("STYLISH")
static const trait_id trait_VANITY ("VANITY")
static const morale_mult morale_mults::optimist (1.2, 0.8)
static const morale_mult morale_mults::badtemper (0.8, 1.2)
static const morale_mult morale_mults::numb (0.25, 0.25)
static const morale_mult morale_mults::prozac (1.0, 0.25)
static const morale_mult morale_mults::prozac_bad (0.25, 1.0)
Function Documentation
operator*()
static double operator* (double morale, const morale_mult & mult) static
Definition at line 95 of file morale.cpp.
 {
     return morale * ( ( morale >= 0.0 ) ? mult.good : mult.bad );
 }
References morale_mult::bad, morale_mult::good, and spell_effect::morale().
operator*=()
static int operator*= (int & morale, const morale_mult & mult) static
Definition at line 100 of file morale.cpp.
 {
     morale = morale * mult;
     return morale;
 }
References spell_effect::morale().
Variable Documentation
effect_cold
const efftype_id effect_cold("cold") ("cold") static
Referenced by player_morale::on_effect_int_change().
effect_hot
const efftype_id effect_hot("hot") ("hot") static
Referenced by player_morale::on_effect_int_change().
effect_took_prozac
const efftype_id effect_took_prozac("took_prozac") ("took_prozac") static
Referenced by player_morale::on_effect_int_change().
effect_took_prozac_bad
const efftype_id effect_took_prozac_bad("took_prozac_bad") ("took_prozac_bad") static
Referenced by player_morale::on_effect_int_change().
trait_BADTEMPER
const trait_id trait_BADTEMPER("BADTEMPER") ("BADTEMPER") static
Referenced by player_morale::player_morale().
trait_CENOBITE
const trait_id trait_CENOBITE("CENOBITE") ("CENOBITE") static
Referenced by player_morale::player_morale(), and player_morale::update_masochist_bonus().
trait_CHLOROMORPH
const trait_id trait_CHLOROMORPH("CHLOROMORPH") ("CHLOROMORPH") static
Referenced by player_morale::player_morale(), and player_morale::update_constrained_penalty().
trait_FLOWERS
const trait_id trait_FLOWERS("FLOWERS") ("FLOWERS") static
Referenced by player_morale::player_morale(), and player_morale::update_constrained_penalty().
trait_LEAVES2
const trait_id trait_LEAVES2("LEAVES2") ("LEAVES2") static
Referenced by player_morale::player_morale(), and player_morale::update_constrained_penalty().
trait_LEAVES3
const trait_id trait_LEAVES3("LEAVES3") ("LEAVES3") static
Referenced by player_morale::player_morale(), and player_morale::update_constrained_penalty().
trait_MASOCHIST
const trait_id trait_MASOCHIST("MASOCHIST") ("MASOCHIST") static
Referenced by player_morale::player_morale(), and player_morale::update_masochist_bonus().
trait_MASOCHIST_MED
const trait_id trait_MASOCHIST_MED("MASOCHIST_MED") ("MASOCHIST_MED") static
Referenced by player_morale::player_morale(), and player_morale::update_masochist_bonus().
trait_NUMB
const trait_id trait_NUMB("NUMB") ("NUMB") static
Referenced by player_morale::player_morale().
trait_OPTIMISTIC
const trait_id trait_OPTIMISTIC("OPTIMISTIC") ("OPTIMISTIC") static
Referenced by player_morale::player_morale().
trait_RADIOPHILE
const trait_id trait_RADIOPHILE("RADIOPHILE") ("RADIOPHILE") static
Referenced by player_morale::player_morale(), and player_morale::update_radiophile_bonus().
trait_ROOTS1
const trait_id trait_ROOTS1("ROOTS1") ("ROOTS1") static
Referenced by player_morale::player_morale(), and player_morale::update_constrained_penalty().
trait_ROOTS2
const trait_id trait_ROOTS2("ROOTS2") ("ROOTS2") static
Referenced by player_morale::player_morale(), and player_morale::update_constrained_penalty().
trait_ROOTS3
const trait_id trait_ROOTS3("ROOTS3") ("ROOTS3") static
Referenced by player_morale::player_morale(), and player_morale::update_constrained_penalty().
trait_STYLISH
const trait_id trait_STYLISH("STYLISH") ("STYLISH") static
Referenced by player_morale::player_morale().
trait_VANITY
const trait_id trait_VANITY("VANITY") ("VANITY") static
Referenced by player_morale::player_morale(), and player_morale::update_constrained_penalty().