Cataclysm DDA: src/mutation_type.cpp File Reference
mutation_type.cpp File Reference
#include "mutation.h"
#include "json.h"
Classes
struct mutation_type
Functions
void load_mutation_type (const JsonObject &jsobj)
bool mutation_type_exists (const std::string &id)
std::vector< trait_id > get_mutations_in_type (const std::string &id)
std::vector< trait_and_var > mutations_var_in_type (const std::string &id)
std::vector< trait_id > get_mutations_in_types (const std::set< std::string > &ids)
Variables
static std::map< std::string, mutation_type > mutation_types
Function Documentation
get_mutations_in_type()
std::vector<trait_id> get_mutations_in_type (const std::string & id)
Definition at line 24 of file mutation_type.cpp.
 {
     std::vector<trait_id> ret;
     for( const mutation_branch &it : mutation_branch::get_all() ) {
         if( it.types.find( id ) != it.types.end() ) {
             ret.push_back( it.id );
         }
     }
     return ret;
 }
References mutation_branch::get_all(), and cata::hash64_detail::ret.
Referenced by Character::customize_appearance(), and get_mutations_in_types().
get_mutations_in_types()
std::vector<trait_id> get_mutations_in_types (const std::set< std::string > & ids)
Definition at line 52 of file mutation_type.cpp.
 {
     std::vector<trait_id> ret;
     for( const std::string &it : ids ) {
         std::vector<trait_id> this_id = get_mutations_in_type( it );
         ret.insert( ret.end(), this_id.begin(), this_id.end() );
     }
     return ret;
 }
References get_mutations_in_type(), and cata::hash64_detail::ret.
Referenced by are_same_type_traits(), Character::get_same_type_traits(), and Character::mutate_towards().
load_mutation_type()
void load_mutation_type (const JsonObject & jsobj)
Definition at line 11 of file mutation_type.cpp.
 {
     mutation_type new_type;
     new_type.id = jsobj.get_string( "id" );
     mutation_types[new_type.id] = new_type;
 }
References JsonObject::get_string(), mutation_type::id, and mutation_types.
Referenced by DynamicDataLoader::initialize().
mutation_type_exists()
bool mutation_type_exists (const std::string & id)
Definition at line 19 of file mutation_type.cpp.
 {
     return mutation_types.find( id ) != mutation_types.end();
 }
References mutation_types.
Referenced by mutation_branch::check_consistency().
mutations_var_in_type()
std::vector<trait_and_var> mutations_var_in_type (const std::string & id)
Definition at line 35 of file mutation_type.cpp.
 {
     std::vector<trait_and_var> ret;
     for( const mutation_branch &it : mutation_branch::get_all() ) {
         if( it.types.find( id ) != it.types.end() ) {
             if( it.variants.empty() ) {
                 ret.emplace_back( it.id, "" );
                 continue;
             }
             for( const std::pair<const std::string, mutation_variant> &var : it.variants ) {
                 ret.emplace_back( it.id, var.second.id );
             }
         }
     }
     return ret;
 }
References mutation_branch::get_all(), and cata::hash64_detail::ret.
Referenced by generic_barber().
Variable Documentation
mutation_types
std::map<std::string, mutation_type> mutation_types static
Definition at line 9 of file mutation_type.cpp.
Referenced by load_mutation_type(), and mutation_type_exists().