Cataclysm DDA: src/mutation_ui.cpp File Reference
mutation_ui.cpp File Reference
#include "character.h"
#include <algorithm>
#include <cstddef>
#include <functional>
#include <string>
#include <unordered_map>
#include "avatar.h"
#include "color.h"
#include "cursesdef.h"
#include "enums.h"
#include "input_context.h"
#include "inventory.h"
#include "mutation.h"
#include "output.h"
#include "popup.h"
#include "string_formatter.h"
#include "translations.h"
#include "ui_manager.h"
Enumerations
enum class mutation_menu_mode { activating , examining , reassigning , hiding }
enum class mutation_tab_mode { active , passive , none }
Functions
static void draw_exam_window (const catacurses::window &win, const int border_y)
static std::optional< trait_id > GetTrait (const std::vector< trait_id > &active, const std::vector< trait_id > &passive, int cursor, mutation_tab_mode tab_mode)
static void show_mutations_titlebar (const catacurses::window &window, const mutation_menu_mode menu_mode, const input_context &ctxt)
Variables
static const invlet_wrapper mutation_chars ("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ\"#&()*+./:;@[\\]^_{|}")
static const auto shortcut_desc
Enumeration Type Documentation
mutation_menu_mode
enum mutation_menu_mode strong
Enumerator
activating
examining
reassigning
hiding
Definition at line 21 of file mutation_ui.cpp.
{
     activating,
     examining,
     reassigning,
     hiding
 };
mutation_tab_mode
enum mutation_tab_mode strong
Enumerator
active
passive
none
Definition at line 27 of file mutation_ui.cpp.
{
     active,
     passive,
     none
 };
Function Documentation
draw_exam_window()
static void draw_exam_window (const catacurses::window & win, const int border_y) static
Definition at line 36 of file mutation_ui.cpp.
 {
     const int width = getmaxx( win );
     mvwputch( win, point( 0, border_y ), BORDER_COLOR, LINE_XXXO );
     mvwhline( win, point( 1, border_y ), LINE_OXOX, width - 2 );
     mvwputch( win, point( width - 1, border_y ), BORDER_COLOR, LINE_XOXX );
 }
References BORDER_COLOR, catacurses::getmaxx(), LINE_OXOX, LINE_XOXX, LINE_XXXO, catacurses::mvwhline(), and mvwputch().
Referenced by avatar::power_mutations().
GetTrait()
static std::optional<trait_id> GetTrait (const std::vector< trait_id > & active, const std::vector< trait_id > & passive, int cursor, mutation_tab_mode tab_mode) static
Definition at line 51 of file mutation_ui.cpp.
 {
     std::optional<trait_id> mut_id;
     if( tab_mode == mutation_tab_mode::active ) {
         mut_id = active[cursor];
     } else if( tab_mode == mutation_tab_mode::passive ) {
         mut_id = passive[cursor];
     }
     return mut_id;
 }
References active, and passive.
Referenced by avatar::power_mutations().
show_mutations_titlebar()
static void show_mutations_titlebar (const catacurses::window & window, const mutation_menu_mode menu_mode, const input_context & ctxt) static
Definition at line 64 of file mutation_ui.cpp.
 {
     werase( window );
     std::string desc;
     if( menu_mode == mutation_menu_mode::reassigning ) {
         desc += std::string( _( "Reassigning." ) ) + "  " +
                 _( "Select a mutation to reassign or press [<color_yellow>SPACE</color>] to cancel. " );
     }
     if( menu_mode == mutation_menu_mode::activating ) {
         desc += colorize( _( "Activating" ),
                           c_green ) + "  " + shortcut_desc( _( "%s Examine, " ),
                                   ctxt.get_desc( "TOGGLE_EXAMINE" ) );
     }
     if( menu_mode == mutation_menu_mode::examining ) {
         desc += colorize( _( "Examining" ),
                           c_light_blue ) + "  " + shortcut_desc( _( "%s Activate, " ),
                                   ctxt.get_desc( "TOGGLE_EXAMINE" ) );
     }
     if( menu_mode == mutation_menu_mode::hiding ) {
         desc += colorize( _( "Hiding" ), c_cyan ) + "  " + shortcut_desc( _( "%s Activate, " ),
                 ctxt.get_desc( "TOGGLE_EXAMINE" ) );
     }
     if( menu_mode != mutation_menu_mode::reassigning ) {
         desc += shortcut_desc( _( "%s Reassign, " ), ctxt.get_desc( "REASSIGN" ) );
     }
     desc += shortcut_desc( _( "%s Toggle sprite visibility, " ), ctxt.get_desc( "TOGGLE_SPRITE" ) );
     desc += shortcut_desc( _( "%s Change keybindings." ), ctxt.get_desc( "HELP_KEYBINDINGS" ) );
     // NOLINTNEXTLINE(cata-use-named-point-constants)
     fold_and_print( window, point( 1, 0 ), getmaxx( window ) - 1, c_white, desc );
     wnoutrefresh( window );
 }
References _, activating, c_cyan, c_green, c_light_blue, c_white, colorize(), examining, fold_and_print(), input_context::get_desc(), catacurses::getmaxx(), hiding, reassigning, shortcut_desc, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by avatar::power_mutations().
Variable Documentation
mutation_chars
const invlet_wrapper mutation_chars("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ\"#&()*+./:;@[\\]^_{|}") ("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ\"#&()*+./:;@^_{|}" [\\]) static
Referenced by avatar::power_mutations().
shortcut_desc
const auto shortcut_desc static
Initial value:
= [](const std::string_view comment, const std::string &keys)
{
    return string_format( comment, string_format( "[<color_yellow>%s</color>]", keys ) );
}
Definition at line 44 of file mutation_ui.cpp.
Referenced by show_mutations_titlebar().