Cataclysm DDA: src/mutation.h File Reference
mutation.h File Reference
#include <climits>
#include <iosfwd>
#include <map>
#include <new>
#include <optional>
#include <set>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>
#include "calendar.h"
#include "character.h"
#include "damage.h"
#include "hash_utils.h"
#include "memory_fast.h"
#include "point.h"
#include "translations.h"
#include "type_id.h"
#include "value_ptr.h"
Classes
struct dream
struct mut_attack
struct mut_transform
struct mut_personality_score
struct reflex_activation_data
struct trait_and_var
struct trait_replacement
struct mutation_variant
struct mutation_branch
struct mutation_branch::OverrideLook
struct mutation_category_trait
struct enum_traits< mutagen_technique >
Macros
#define CATA_SRC_MUTATION_H
Enumerations
enum class mutagen_technique : int {
consumed_mutagen , injected_mutagen , consumed_purifier , injected_purifier ,
injected_smart_purifier , num_mutagen_techniques
}
Functions
void load_mutation_type (const JsonObject &jsobj)
bool mutation_category_is_valid (const mutation_category_id &cat)
bool mutation_type_exists (const std::string &id)
std::vector< trait_id > get_mutations_in_types (const std::set< std::string > &ids)
std::vector< trait_id > get_mutations_in_type (const std::string &id)
bool mutation_is_in_category (const trait_id &mut, const mutation_category_id &cat)
std::vector< trait_and_var > mutations_var_in_type (const std::string &id)
bool trait_display_sort (const trait_and_var &a, const trait_and_var &b) noexcept
bool trait_display_nocolor_sort (const trait_and_var &a, const trait_and_var &b) noexcept
bool are_conflicting_traits (const trait_id &trait_a, const trait_id &trait_b)
bool b_is_lower_trait_of_a (const trait_id &trait_a, const trait_id &trait_b)
bool b_is_higher_trait_of_a (const trait_id &trait_a, const trait_id &trait_b)
bool are_opposite_traits (const trait_id &trait_a, const trait_id &trait_b)
bool are_same_type_traits (const trait_id &trait_a, const trait_id &trait_b)
bool contains_trait (std::vector< string_id< mutation_branch >> traits, const trait_id &trait)
int get_total_nonbad_in_category (const mutation_category_id &categ)
void test_crossing_threshold (Character &guy, const mutation_category_trait &m_category)
Variables
std::vector< dream > dreams
std::map< mutation_category_id, std::vector< trait_id > > mutations_category
Macro Definition Documentation
CATA_SRC_MUTATION_H
#define CATA_SRC_MUTATION_H
Definition at line 3 of file mutation.h.
Enumeration Type Documentation
mutagen_technique
enum mutagen_technique : int strong
Enumerator
consumed_mutagen
injected_mutagen
consumed_purifier
injected_purifier
injected_smart_purifier
num_mutagen_techniques
Definition at line 563 of file mutation.h.
                              : int {
     consumed_mutagen,
     injected_mutagen,
     consumed_purifier,
     injected_purifier,
     injected_smart_purifier,
     num_mutagen_techniques // last
 };
Function Documentation
are_conflicting_traits()
bool are_conflicting_traits (const trait_id & trait_a, const trait_id & trait_b)
Definition at line 2266 of file mutation.cpp.
 {
     return are_opposite_traits( trait_a, trait_b ) || b_is_lower_trait_of_a( trait_a, trait_b )
            || b_is_higher_trait_of_a( trait_a, trait_b ) || are_same_type_traits( trait_a, trait_b );
 }
References are_opposite_traits(), are_same_type_traits(), b_is_higher_trait_of_a(), and b_is_lower_trait_of_a().
Referenced by scenario::scenario_traits_conflict_with_profession_traits(), set_hobbies(), and set_profession().
are_opposite_traits()
bool are_opposite_traits (const trait_id & trait_a, const trait_id & trait_b)
Definition at line 2272 of file mutation.cpp.
 {
     return contains_trait( trait_a->cancels, trait_b );
 }
References mutation_branch::cancels, and contains_trait().
Referenced by are_conflicting_traits().
are_same_type_traits()
bool are_same_type_traits (const trait_id & trait_a, const trait_id & trait_b)
Definition at line 2287 of file mutation.cpp.
 {
     return contains_trait( get_mutations_in_types( trait_a->types ), trait_b );
 }
References contains_trait(), get_mutations_in_types(), and mutation_branch::types.
Referenced by are_conflicting_traits().
b_is_higher_trait_of_a()
bool b_is_higher_trait_of_a (const trait_id & trait_a, const trait_id & trait_b)
Definition at line 2282 of file mutation.cpp.
 {
     return contains_trait( trait_a->replacements, trait_b );
 }
References contains_trait(), and mutation_branch::replacements.
Referenced by are_conflicting_traits().
b_is_lower_trait_of_a()
bool b_is_lower_trait_of_a (const trait_id & trait_a, const trait_id & trait_b)
Definition at line 2277 of file mutation.cpp.
 {
     return contains_trait( trait_a->prereqs, trait_b );
 }
References contains_trait(), and mutation_branch::prereqs.
Referenced by are_conflicting_traits().
contains_trait()
bool contains_trait (std::vector< string_id< mutation_branch >> traits, const trait_id & trait)
Definition at line 2292 of file mutation.cpp.
 {
     return std::find( traits.begin(), traits.end(), trait ) != traits.end();
 }
Referenced by are_opposite_traits(), are_same_type_traits(), b_is_higher_trait_of_a(), b_is_lower_trait_of_a(), and has_cyclic_dependency().
get_mutations_in_type()
std::vector<trait_id> get_mutations_in_type (const std::string & id)
Definition at line 24 of file mutation_type.cpp.
 {
     std::vector<trait_id> ret;
     for( const mutation_branch &it : mutation_branch::get_all() ) {
         if( it.types.find( id ) != it.types.end() ) {
             ret.push_back( it.id );
         }
     }
     return ret;
 }
References mutation_branch::get_all(), and cata::hash64_detail::ret.
Referenced by Character::customize_appearance(), and get_mutations_in_types().
get_mutations_in_types()
std::vector<trait_id> get_mutations_in_types (const std::set< std::string > & ids)
Definition at line 52 of file mutation_type.cpp.
 {
     std::vector<trait_id> ret;
     for( const std::string &it : ids ) {
         std::vector<trait_id> this_id = get_mutations_in_type( it );
         ret.insert( ret.end(), this_id.begin(), this_id.end() );
     }
     return ret;
 }
References get_mutations_in_type(), and cata::hash64_detail::ret.
Referenced by are_same_type_traits(), Character::get_same_type_traits(), and Character::mutate_towards().
get_total_nonbad_in_category()
int get_total_nonbad_in_category (const mutation_category_id & categ)
Definition at line 206 of file mutation.cpp.
 {
     int mut_count = 0;
     // Iterate through all available traits in this category and count every one that isn't bad or the threshold.
     for( const trait_id &traits_iter : mutations_category[categ] ) {
         const mutation_branch &mdata = traits_iter.obj();
         if( mdata.points > -1 && !mdata.threshold ) {
             mut_count += 1;
         }
     }
     return mut_count;
 }
References mutations_category, mutation_branch::points, and mutation_branch::threshold.
Referenced by Character::roll_bad_mutation().
load_mutation_type()
void load_mutation_type (const JsonObject & jsobj)
Definition at line 11 of file mutation_type.cpp.
 {
     mutation_type new_type;
     new_type.id = jsobj.get_string( "id" );
     mutation_types[new_type.id] = new_type;
 }
References JsonObject::get_string(), mutation_type::id, and mutation_types.
Referenced by DynamicDataLoader::initialize().
mutation_category_is_valid()
bool mutation_category_is_valid (const mutation_category_id & cat)
Definition at line 1138 of file mutation_data.cpp.
 {
     return mutation_category_traits.count( cat );
 }
References mutation_category_traits.
mutation_is_in_category()
bool mutation_is_in_category (const trait_id & mut, const mutation_category_id & cat)
Definition at line 1149 of file mutation_data.cpp.
 {
     return std::find( mutations_category[cat].begin(), mutations_category[cat].end(),
                       mut ) != mutations_category[cat].end();
 }
References keycode::end, and mutations_category.
Referenced by Character::mutate(), and Character::mutate_towards().
mutation_type_exists()
bool mutation_type_exists (const std::string & id)
Definition at line 19 of file mutation_type.cpp.
 {
     return mutation_types.find( id ) != mutation_types.end();
 }
References mutation_types.
Referenced by mutation_branch::check_consistency().
mutations_var_in_type()
std::vector<trait_and_var> mutations_var_in_type (const std::string & id)
Definition at line 35 of file mutation_type.cpp.
 {
     std::vector<trait_and_var> ret;
     for( const mutation_branch &it : mutation_branch::get_all() ) {
         if( it.types.find( id ) != it.types.end() ) {
             if( it.variants.empty() ) {
                 ret.emplace_back( it.id, "" );
                 continue;
             }
             for( const std::pair<const std::string, mutation_variant> &var : it.variants ) {
                 ret.emplace_back( it.id, var.second.id );
             }
         }
     }
     return ret;
 }
References mutation_branch::get_all(), and cata::hash64_detail::ret.
Referenced by generic_barber().
test_crossing_threshold()
void test_crossing_threshold (Character & guy, const mutation_category_trait & m_category)
trait_display_nocolor_sort()
bool trait_display_nocolor_sort (const trait_and_var & a, const trait_and_var & b) noexcept
Definition at line 894 of file mutation_data.cpp.
 {
     return localized_compare( a.name(), b.name() );
 }
References a, b, and localized_compare.
Referenced by set_traits().
trait_display_sort()
bool trait_display_sort (const trait_and_var & a, const trait_and_var & b) noexcept
Definition at line 885 of file mutation_data.cpp.
 {
     auto trait_sort_key = []( const trait_and_var & t ) {
         return std::make_pair( -t.trait->get_display_color().to_int(), t.name() );
     };
     return localized_compare( trait_sort_key( a ), trait_sort_key( b ) );
 }
References a, b, and localized_compare.
Referenced by Character::disp_info(), and set_description().
Variable Documentation
dreams
std::vector<dream> dreams extern
Definition at line 48 of file mutation_data.cpp.
Referenced by Character::get_category_dream(), dream::load(), and DynamicDataLoader::unload_data().
mutations_category
std::map<mutation_category_id, std::vector<trait_id> > mutations_category extern
Definition at line 49 of file mutation_data.cpp.
Referenced by computer_session::action_list_mutations(), debug_menu::character_edit_menu(), mutation_branch::finalize_all(), get_total_nonbad_in_category(), Character::give_all_mutations(), Character::mutate(), Character::mutate_category(), mutation_is_in_category(), mutation_branch::reset_all(), and DynamicDataLoader::unload_data().