Cataclysm DDA: src/mutation_data.cpp File Reference
mutation_data.cpp File Reference
#include "mutation.h"
#include <cstdlib>
#include <map>
#include <memory>
#include <set>
#include <stdexcept>
#include <type_traits>
#include <vector>
#include "assign.h"
#include "color.h"
#include "condition.h"
#include "debug.h"
#include "effect_on_condition.h"
#include "enum_conversions.h"
#include "enums.h"
#include "generic_factory.h"
#include "json.h"
#include "localized_comparator.h"
#include "make_static.h"
#include "memory_fast.h"
#include "string_formatter.h"
#include "trait_group.h"
#include "translations.h"
Namespaces
anonymous_namespace{mutation_data.cpp}
Typedefs
using TraitGroupMap = std::map< trait_group::Trait_group_tag, shared_ptr_fast< Trait_group > >
using TraitSet = std::set< trait_id >
using trait_reader = string_id_reader<::mutation_branch >
using flag_reader = string_id_reader<::json_flag >
Functions
static mut_attack load_mutation_attack (const JsonObject &jo)
static social_modifiers load_mutation_social_mods (const JsonObject &jo)
static bool has_cyclic_dependency (const trait_id &mid, std::vector< trait_id > already_visited)
static void check_has_cyclic_dependency (const trait_id &mid)
static void check_consistency (const std::vector< trait_id > &mvec, const trait_id &mid, const std::string &what)
bool trait_display_sort (const trait_and_var &a, const trait_and_var &b) noexcept
bool trait_display_nocolor_sort (const trait_and_var &a, const trait_and_var &b) noexcept
static Trait_group & make_group_or_throw (const trait_group::Trait_group_tag &gid, bool is_collection)
bool mutation_category_is_valid (const mutation_category_id &cat)
bool mutation_is_in_category (const trait_id &mut, const mutation_category_id &cat)
Variables
static const mutation_category_id mutation_category_ANY ("ANY")
static const trait_group::Trait_group_tag Trait_group_EMPTY_GROUP ("EMPTY_GROUP")
static TraitSet trait_blacklist
static TraitGroupMap trait_groups
static std::map< trait_id, trait_replacement > trait_migrations
static trait_replacement trait_migration_remove { std::nullopt, std::nullopt, true }
generic_factory< mutation_branch > anonymous_namespace{mutation_data.cpp}::trait_factory ("trait")
std::vector< dream > dreams
std::map< mutation_category_id, std::vector< trait_id > > mutations_category
static std::map< mutation_category_id, mutation_category_trait > mutation_category_traits
Typedef Documentation
flag_reader
using flag_reader = string_id_reader<::json_flag>
Definition at line 35 of file mutation_data.cpp.
trait_reader
using trait_reader = string_id_reader<::mutation_branch>
Definition at line 34 of file mutation_data.cpp.
TraitGroupMap
using TraitGroupMap = std::map<trait_group::Trait_group_tag, shared_ptr_fast<Trait_group> >
Definition at line 31 of file mutation_data.cpp.
TraitSet
using TraitSet = std::set<trait_id>
Definition at line 33 of file mutation_data.cpp.
Function Documentation
check_consistency()
static void check_consistency (const std::vector< trait_id > & mvec, const trait_id & mid, const std::string & what) static
Definition at line 636 of file mutation_data.cpp.
 {
     for( const auto &m : mvec ) {
         if( !m.is_valid() ) {
             debugmsg( "mutation %s refers to undefined %s %s", mid.c_str(), what.c_str(), m.c_str() );
         }
         if( m == mid ) {
             debugmsg( "mutation %s refers to itself in %s context.  The program will crash if the player gains this mutation.",
                       mid.c_str(), what.c_str() );
         }
     }
 }
References string_id< T >::c_str(), and debugmsg.
check_has_cyclic_dependency()
static void check_has_cyclic_dependency (const trait_id & mid) static
Definition at line 627 of file mutation_data.cpp.
 {
     std::vector<trait_id> already_visited;
     if( has_cyclic_dependency( mid, already_visited ) ) {
         debugmsg( "mutation %s references itself in either of its prerequsition branches.  The program will crash if the player gains this mutation.",
                   mid.c_str() );
     }
 }
References string_id< T >::c_str(), debugmsg, and has_cyclic_dependency().
Referenced by mutation_branch::check_consistency().
has_cyclic_dependency()
static bool has_cyclic_dependency (const trait_id & mid, std::vector< trait_id > already_visited) static
Definition at line 603 of file mutation_data.cpp.
 {
     if( contains_trait( already_visited, mid ) ) {
         return true; // Circular dependency was found.
     }
     already_visited.push_back( mid );
     // Perform Depth-first search
     for( const trait_id &current_mutation : mid->prereqs ) {
         if( has_cyclic_dependency( current_mutation->id, already_visited ) ) {
             return true;
         }
     }
     for( const trait_id &current_mutation : mid->prereqs2 ) {
         if( has_cyclic_dependency( current_mutation->id, already_visited ) ) {
             return true;
         }
     }
     return false;
 }
References contains_trait(), mutation_branch::id, mutation_branch::prereqs, and mutation_branch::prereqs2.
Referenced by check_has_cyclic_dependency().
load_mutation_attack()
static mut_attack load_mutation_attack (const JsonObject & jo) static
Definition at line 139 of file mutation_data.cpp.
 {
     mut_attack ret;
     jo.read( "attack_text_u", ret.attack_text_u );
     jo.read( "attack_text_npc", ret.attack_text_npc );
     jo.read( "required_mutations", ret.required_mutations );
     jo.read( "blocker_mutations", ret.blocker_mutations );
     jo.read( "hardcoded_effect", ret.hardcoded_effect );
     if( jo.has_string( "body_part" ) ) {
         ret.bp = bodypart_str_id( jo.get_string( "body_part" ) );
     }
     jo.read( "chance", ret.chance );
     if( jo.has_array( "base_damage" ) ) {
         ret.base_damage = load_damage_instance( jo.get_array( "base_damage" ) );
     } else if( jo.has_object( "base_damage" ) ) {
         JsonObject jo_dam = jo.get_object( "base_damage" );
         ret.base_damage = load_damage_instance( jo_dam );
     }
     if( jo.has_array( "strength_damage" ) ) {
         ret.strength_damage = load_damage_instance( jo.get_array( "strength_damage" ) );
     } else if( jo.has_object( "strength_damage" ) ) {
         JsonObject jo_dam = jo.get_object( "strength_damage" );
         ret.strength_damage = load_damage_instance( jo_dam );
     }
     if( ret.attack_text_u.empty() || ret.attack_text_npc.empty() ) {
         jo.throw_error( "Attack message unset" );
     }
     if( !ret.hardcoded_effect && ret.base_damage.empty() && ret.strength_damage.empty() ) {
         jo.throw_error( "Damage unset" );
     } else if( ret.hardcoded_effect && ( !ret.base_damage.empty() || !ret.strength_damage.empty() ) ) {
         jo.throw_error( "Damage and hardcoded effect are both set (must be one, not both)" );
     }
     if( ret.chance <= 0 ) {
         jo.throw_error( "Chance of procing must be set and positive" );
     }
     return ret;
 }
References JsonObject::get_array(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_object(), JsonObject::has_string(), load_damage_instance(), JsonObject::read(), cata::hash64_detail::ret, and JsonObject::throw_error().
Referenced by mutation_branch::load().
load_mutation_social_mods()
static social_modifiers load_mutation_social_mods (const JsonObject & jo) static
Definition at line 185 of file mutation_data.cpp.
 {
     social_modifiers ret;
     jo.read( "lie", ret.lie );
     jo.read( "persuade", ret.persuade );
     jo.read( "intimidate", ret.intimidate );
     return ret;
 }
References JsonObject::read(), and cata::hash64_detail::ret.
Referenced by mutation_branch::load().
make_group_or_throw()
static Trait_group& make_group_or_throw (const trait_group::Trait_group_tag & gid, bool is_collection) static
Definition at line 984 of file mutation_data.cpp.
 {
     // NOTE: If the gid is already in the map, emplace will just return an iterator to it
     auto found = ( is_collection
                    ? trait_groups.emplace( gid, make_shared_fast<Trait_group_collection>( 100 ) )
                    : trait_groups.emplace( gid, make_shared_fast<Trait_group_distribution>( 100 ) ) ).first;
     // Evidently, making the collection/distribution separation better has made the code for this check worse.
     if( is_collection ) {
         if( dynamic_cast<Trait_group_distribution *>( found->second.get() ) ) {
             throw std::runtime_error( string_format(
                                           R"("mutation group "%s" already defined with type "distribution")", gid.str() ) );
         }
     } else {
         if( dynamic_cast<Trait_group_collection *>( found->second.get() ) ) {
             throw std::runtime_error( string_format(
                                           R"("mutation group "%s" already defined with type "collection")", gid.str() ) );
         }
     }
     return *found->second;
 }
References string_id< T >::str(), string_format(), and trait_groups.
Referenced by mutation_branch::load_trait_group().
mutation_category_is_valid()
bool mutation_category_is_valid (const mutation_category_id & cat)
Definition at line 1138 of file mutation_data.cpp.
 {
     return mutation_category_traits.count( cat );
 }
References mutation_category_traits.
mutation_is_in_category()
bool mutation_is_in_category (const trait_id & mut, const mutation_category_id & cat)
Definition at line 1149 of file mutation_data.cpp.
 {
     return std::find( mutations_category[cat].begin(), mutations_category[cat].end(),
                       mut ) != mutations_category[cat].end();
 }
References keycode::end, and mutations_category.
Referenced by Character::mutate(), and Character::mutate_towards().
trait_display_nocolor_sort()
bool trait_display_nocolor_sort (const trait_and_var & a, const trait_and_var & b) noexcept
Definition at line 894 of file mutation_data.cpp.
 {
     return localized_compare( a.name(), b.name() );
 }
References a, b, and localized_compare.
Referenced by set_traits().
trait_display_sort()
bool trait_display_sort (const trait_and_var & a, const trait_and_var & b) noexcept
Definition at line 885 of file mutation_data.cpp.
 {
     auto trait_sort_key = []( const trait_and_var & t ) {
         return std::make_pair( -t.trait->get_display_color().to_int(), t.name() );
     };
     return localized_compare( trait_sort_key( a ), trait_sort_key( b ) );
 }
References a, b, and localized_compare.
Referenced by Character::disp_info(), and set_description().
Variable Documentation
dreams
std::vector<dream> dreams
Definition at line 48 of file mutation_data.cpp.
Referenced by Character::get_category_dream(), dream::load(), and DynamicDataLoader::unload_data().
mutation_category_ANY
const mutation_category_id mutation_category_ANY("ANY") ("ANY") static
Referenced by mutation_branch::finalize_all().
mutation_category_traits
std::map<mutation_category_id, mutation_category_trait> mutation_category_traits static
Definition at line 50 of file mutation_data.cpp.
Referenced by mutation_category_trait::check_consistency(), mutation_category_trait::get_all(), mutation_category_trait::get_category(), mutation_category_trait::load(), mutation_category_is_valid(), and mutation_category_trait::reset().
mutations_category
std::map<mutation_category_id, std::vector<trait_id> > mutations_category
Definition at line 49 of file mutation_data.cpp.
Referenced by computer_session::action_list_mutations(), debug_menu::character_edit_menu(), mutation_branch::finalize_all(), get_total_nonbad_in_category(), Character::give_all_mutations(), Character::mutate(), Character::mutate_category(), mutation_is_in_category(), mutation_branch::reset_all(), and DynamicDataLoader::unload_data().
trait_blacklist
TraitSet trait_blacklist static
Definition at line 37 of file mutation_data.cpp.
Referenced by mutation_branch::finalize_trait_blacklist(), mutation_branch::load_trait_blacklist(), mutation_branch::reset_all(), and mutation_branch::trait_is_blacklisted().
Trait_group_EMPTY_GROUP
const trait_group::Trait_group_tag Trait_group_EMPTY_GROUP("EMPTY_GROUP") ("EMPTY_GROUP") static
Referenced by mutation_branch::reset_all().
trait_groups
TraitGroupMap trait_groups static
Definition at line 38 of file mutation_data.cpp.
Referenced by mutation_branch::get_all_group_names(), mutation_branch::get_group(), make_group_or_throw(), and mutation_branch::reset_all().
trait_migration_remove
trait_replacement trait_migration_remove { std::nullopt, std::nullopt, true } static
Definition at line 41 of file mutation_data.cpp.
Referenced by mutation_branch::trait_migration().
trait_migrations
std::map<trait_id, trait_replacement> trait_migrations static
Definition at line 40 of file mutation_data.cpp.
Referenced by mutation_branch::load_trait_migration(), and mutation_branch::trait_migration().