Cataclysm DDA: construct Namespace Reference
construct Namespace Reference
Functions
static bool check_nothing (const tripoint_bub_ms &)
static bool check_channel (const tripoint_bub_ms &)
static bool check_empty_lite (const tripoint_bub_ms &)
static bool check_empty (const tripoint_bub_ms &)
static bool check_support (const tripoint_bub_ms &)
static bool check_support_below (const tripoint_bub_ms &)
static bool check_single_support (const tripoint_bub_ms &p)
static bool check_stable (const tripoint_bub_ms &)
static bool check_nofloor_above (const tripoint_bub_ms &)
static bool check_deconstruct (const tripoint_bub_ms &)
static bool check_up_OK (const tripoint_bub_ms &)
static bool check_down_OK (const tripoint_bub_ms &)
static bool check_no_trap (const tripoint_bub_ms &)
static bool check_ramp_high (const tripoint_bub_ms &)
static bool check_no_wiring (const tripoint_bub_ms &)
static bool check_matching_down_above (const tripoint_bub_ms &p)
static void done_nothing (const tripoint_bub_ms &, Character &)
static void done_trunk_plank (const tripoint_bub_ms &, Character &)
static void done_grave (const tripoint_bub_ms &, Character &)
static void done_vehicle (const tripoint_bub_ms &, Character &)
static void done_appliance (const tripoint_bub_ms &, Character &)
static void done_wiring (const tripoint_bub_ms &, Character &)
static void done_deconstruct (const tripoint_bub_ms &, Character &)
static void done_digormine_stair (const tripoint_bub_ms &, bool, Character &)
static void done_dig_grave (const tripoint_bub_ms &p, Character &)
static void done_dig_grave_nospawn (const tripoint_bub_ms &p, Character &)
static void done_dig_stair (const tripoint_bub_ms &, Character &)
static void done_mine_downstair (const tripoint_bub_ms &, Character &)
static void done_mine_upstair (const tripoint_bub_ms &, Character &)
static void done_wood_stairs (const tripoint_bub_ms &, Character &)
static void done_window_curtains (const tripoint_bub_ms &, Character &)
static void done_extract_maybe_revert_to_dirt (const tripoint_bub_ms &, Character &)
static void done_mark_firewood (const tripoint_bub_ms &, Character &)
static void done_mark_practice_target (const tripoint_bub_ms &, Character &)
static void done_ramp_low (const tripoint_bub_ms &, Character &)
static void done_ramp_high (const tripoint_bub_ms &, Character &)
static void add_matching_down_above (const tripoint_bub_ms &p, Character &)
static void remove_above (const tripoint_bub_ms &p, Character &)
static void add_roof (const tripoint_bub_ms &p, Character &)
static void do_turn_shovel (const tripoint_bub_ms &, Character &)
static void do_turn_exhume (const tripoint_bub_ms &, Character &)
static void failure_standard (const tripoint_bub_ms &)
static void failure_deconstruct (const tripoint_bub_ms &)
Function Documentation
add_matching_down_above()
void construct::add_matching_down_above (const tripoint_bub_ms & p, Character &) static
Definition at line 1807 of file construction.cpp.
 {
     map &here = get_map();
     const std::string ter_here = here.ter( p ).id().str();
     const std::string ter_above = here.ter( p + tripoint_above ).id().str();
     const size_t separation = ter_here.find_last_of( '_' );
     if( separation > 0 ) {
         here.ter_set( p + tripoint_above, ter_id( ter_here.substr( 0, separation + 1 ) + "down" ) );
     }
 }
References get_map(), int_id< T >::id(), string_id< T >::str(), map::ter(), map::ter_set(), and tripoint_above.
Referenced by load_construction().
add_roof()
void construct::add_roof (const tripoint_bub_ms & p, Character &) static
Definition at line 1824 of file construction.cpp.
 {
     map &here = get_map();
     ter_id roof = here.ter( p ).obj().roof;
     if( !roof ) {
         debugmsg( "add_roof post_ter called on terrain lacking roof definition, %s.",
                   here.ter( p ).id().c_str() );
     }
     here.ter_set( p + tripoint_above, roof );
 }
References string_id< T >::c_str(), debugmsg, get_map(), int_id< T >::id(), int_id< T >::obj(), ter_t::roof, map::ter(), map::ter_set(), and tripoint_above.
Referenced by load_construction().
check_channel()
bool construct::check_channel (const tripoint_bub_ms & p) static
Definition at line 1225 of file construction.cpp.
 {
     map &here = get_map();
     for( const point &offset : four_adjacent_offsets ) {
         if( here.has_flag( ter_furn_flag::TFLAG_CURRENT, p + offset ) ) {
             return true;
         }
     }
     return false;
 }
References four_adjacent_offsets, get_map(), map::has_flag(), and TFLAG_CURRENT.
Referenced by load_construction().
check_deconstruct()
bool construct::check_deconstruct (const tripoint_bub_ms & p) static
Definition at line 1334 of file construction.cpp.
 {
     map &here = get_map();
     if( here.has_furn( p ) ) {
         // Can deconstruct furniture here, make sure regular deconstruction isn't available if easy deconstruction is possible
         if( here.has_flag_furn( ter_furn_flag::TFLAG_EASY_DECONSTRUCT, p ) ) {
             return false;
         }
         return here.furn( p ).obj().deconstruct.can_do;
     }
     // terrain can only be deconstructed when there is no furniture in the way
     return here.ter( p ).obj().deconstruct.can_do;
 }
References map_deconstruct_info::can_do, map_data_common_t::deconstruct, map::furn(), get_map(), map::has_flag_furn(), map::has_furn(), int_id< T >::obj(), map::ter(), and TFLAG_EASY_DECONSTRUCT.
Referenced by load_construction().
check_down_OK()
bool construct::check_down_OK (const tripoint_bub_ms &) static
Definition at line 1354 of file construction.cpp.
 {
     // You're not going below -OVERMAP_DEPTH.
     return ( get_map().get_abs_sub().z() > -OVERMAP_DEPTH );
 }
References get_map(), and OVERMAP_DEPTH.
Referenced by load_construction().
check_empty()
bool construct::check_empty (const tripoint_bub_ms & p) static
Definition at line 1243 of file construction.cpp.
 {
     map &here = get_map();
     // @TODO should check for *visible* traps only. But calling code must
     // first know how to handle constructing on top of an invisible trap!
     return ( here.has_flag( ter_furn_flag::TFLAG_FLAT, p ) && !here.has_furn( p ) &&
              g->is_empty( p ) && here.tr_at( p ).is_null() &&
              here.i_at( p ).empty() && !here.veh_at( p ) );
 }
References item_stack::empty(), g, get_map(), map::has_flag(), map::has_furn(), map::i_at(), trap::is_null(), TFLAG_FLAT, map::tr_at(), and map::veh_at().
Referenced by load_construction().
check_empty_lite()
bool construct::check_empty_lite (const tripoint_bub_ms & p) static
Definition at line 1236 of file construction.cpp.
 {
     map &here = get_map();
     return ( !here.has_furn( p ) && g->is_empty( p ) && here.tr_at( p ).is_null() &&
              here.i_at( p ).empty() && !here.veh_at( p ) );
 }
References item_stack::empty(), g, get_map(), map::has_furn(), map::i_at(), trap::is_null(), map::tr_at(), and map::veh_at().
Referenced by load_construction().
check_matching_down_above()
bool construct::check_matching_down_above (const tripoint_bub_ms & p) static
Definition at line 1387 of file construction.cpp.
 {
     map &here = get_map();
     const std::string ter_here = here.ter( p ).id().str();
     const std::string ter_above = here.ter( p + tripoint_above ).id().str();
     const size_t separation = ter_here.find_last_of( '_' );
     return separation > 0 &&
            ter_here.substr( 0, separation + 1 ) + "down" == ter_above;
 }
References get_map(), int_id< T >::id(), string_id< T >::str(), map::ter(), and tripoint_above.
Referenced by load_construction().
check_no_trap()
bool construct::check_no_trap (const tripoint_bub_ms & p) static
Definition at line 1360 of file construction.cpp.
 {
     return get_map().tr_at( p ).is_null();
 }
References get_map(), trap::is_null(), and map::tr_at().
Referenced by load_construction().
check_no_wiring()
bool construct::check_no_wiring (const tripoint_bub_ms & p) static
Definition at line 1376 of file construction.cpp.
 {
     const optional_vpart_position vp = get_map().veh_at( p );
     if( !vp ) {
         return true;
     }
     const vehicle &veh_target = vp->vehicle();
     return !veh_target.has_tag( flag_WIRING );
 }
References flag_WIRING(), get_map(), vehicle::has_tag(), and map::veh_at().
Referenced by load_construction().
check_nofloor_above()
bool construct::check_nofloor_above (const tripoint_bub_ms & p) static
Definition at line 1329 of file construction.cpp.
 {
     return get_map().has_flag( ter_furn_flag::TFLAG_NO_FLOOR, p + tripoint_above );
 }
References get_map(), map::has_flag(), TFLAG_NO_FLOOR, and tripoint_above.
Referenced by load_construction().
check_nothing()
static bool construct::check_nothing (const tripoint_bub_ms &) static
Definition at line 153 of file construction.cpp.
 {
     return true;
 }
Referenced by load_construction().
check_ramp_high()
bool construct::check_ramp_high (const tripoint_bub_ms & p) static
Definition at line 1365 of file construction.cpp.
 {
     map &here = get_map();
     for( const point &offset : four_adjacent_offsets ) {
         if( here.has_flag( ter_furn_flag::TFLAG_RAMP_DOWN, p + offset + tripoint_above ) ) {
             return true;
         }
     }
     return false;
 }
References four_adjacent_offsets, get_map(), map::has_flag(), TFLAG_RAMP_DOWN, and tripoint_above.
Referenced by load_construction().
check_single_support()
bool construct::check_single_support (const tripoint_bub_ms & p) static
Definition at line 1315 of file construction.cpp.
 {
     map &here = get_map();
     if( here.impassable( p ) ) {
         return false;
     }
     return here.has_flag( ter_furn_flag::TFLAG_SUPPORTS_ROOF, p + tripoint_below );
 }
References get_map(), map::has_flag(), map::impassable(), TFLAG_SUPPORTS_ROOF, and tripoint_below.
Referenced by load_construction().
check_stable()
bool construct::check_stable (const tripoint_bub_ms & p) static
Definition at line 1324 of file construction.cpp.
 {
     return get_map().has_flag( ter_furn_flag::TFLAG_SUPPORTS_ROOF, p + tripoint_below );
 }
References get_map(), map::has_flag(), TFLAG_SUPPORTS_ROOF, and tripoint_below.
Referenced by load_construction().
check_support()
bool construct::check_support (const tripoint_bub_ms & p) static
Definition at line 1253 of file construction.cpp.
 {
     map &here = get_map();
     // need two or more orthogonally adjacent supports
     if( here.impassable( p ) ) {
         return false;
     }
     int num_supports = 0;
     for( const point &offset : four_adjacent_offsets ) {
         if( here.has_flag( ter_furn_flag::TFLAG_SUPPORTS_ROOF, p + offset ) &&
             !here.has_flag( ter_furn_flag::TFLAG_SINGLE_SUPPORT, p + offset ) ) {
             num_supports++;
         }
     }
     // We want to find "walls" below (including windows and doors), but not open rooms and the like.
     if( here.has_flag( ter_furn_flag::TFLAG_SUPPORTS_ROOF, p + tripoint_below ) &&
         ( here.has_flag( ter_furn_flag::TFLAG_WALL, p + tripoint_below ) ||
           here.has_flag( ter_furn_flag::TFLAG_CONNECT_WITH_WALL, p + tripoint_below ) ) ) {
         num_supports += 2;
     }
     return num_supports >= 2;
 }
References four_adjacent_offsets, get_map(), map::has_flag(), map::impassable(), TFLAG_CONNECT_WITH_WALL, TFLAG_SINGLE_SUPPORT, TFLAG_SUPPORTS_ROOF, TFLAG_WALL, and tripoint_below.
Referenced by load_construction().
check_support_below()
bool construct::check_support_below (const tripoint_bub_ms & p) static
Definition at line 1276 of file construction.cpp.
 {
     bool blocking_creature = g->get_creature_if( [&]( const Creature & creature ) {
         return creature.pos() == p.raw();
     } ) != nullptr;
     map &here = get_map();
     // These checks are based on check_empty_lite, but accept no floor and the traps associated
     // with it, i.e. ledge, and various forms of pits.
     // - Check if there's nothing in the way. The "passable" check rejects tiles you can't
     //   pass through, but we want air and water to be OK as well (that's what we want to bridge).
     // - Apart from that, vehicles, items, creatures, and furniture also have to be absent.
     // - Then we have traps, and, unfortunately, there are "ledge" traps on all the open
     //   space tiles adjacent to passable tiles, so we can't just reject all traps outright,
     //   but have to accept those.
     if( !( here.passable( p.raw() ) || here.has_flag( ter_furn_flag::TFLAG_LIQUID, p ) ||
            here.has_flag( ter_furn_flag::TFLAG_NO_FLOOR, p ) ) ||
         blocking_creature || here.has_furn( p ) || !( here.tr_at( p ).is_null() ||
                 here.tr_at( p ).id == tr_ledge  || here.tr_at( p ).has_flag( json_flag_PIT ) ) ||
         !here.i_at( p ).empty() || here.veh_at( p ) ) {
         return false;
     }
     // need two or more orthogonally adjacent supports at the Z level below
     int num_supports = 0;
     for( const point &offset : four_adjacent_offsets ) {
         if( here.has_flag( ter_furn_flag::TFLAG_SUPPORTS_ROOF, p + offset + tripoint_below ) &&
             !here.has_flag( ter_furn_flag::TFLAG_SINGLE_SUPPORT, p + offset + tripoint_below ) ) {
             num_supports++;
         }
     }
     // We want to find "walls" below (including windows and doors), but not open rooms and the like.
     if( here.has_flag( ter_furn_flag::TFLAG_SUPPORTS_ROOF, p + tripoint_below ) &&
         ( here.has_flag( ter_furn_flag::TFLAG_WALL, p + tripoint_below ) ||
           here.has_flag( ter_furn_flag::TFLAG_CONNECT_WITH_WALL, p + tripoint_below ) ) ) {
         num_supports += 2;
     }
     return num_supports >= 2;
 }
References creature, item_stack::empty(), four_adjacent_offsets, g, get_map(), trap::has_flag(), map::has_flag(), map::has_furn(), map::i_at(), trap::id, trap::is_null(), json_flag_PIT, map::passable(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), TFLAG_CONNECT_WITH_WALL, TFLAG_LIQUID, TFLAG_NO_FLOOR, TFLAG_SINGLE_SUPPORT, TFLAG_SUPPORTS_ROOF, TFLAG_WALL, map::tr_at(), tr_ledge, tripoint_below, and map::veh_at().
Referenced by load_construction().
check_up_OK()
bool construct::check_up_OK (const tripoint_bub_ms &) static
Definition at line 1348 of file construction.cpp.
 {
     // You're not going above +OVERMAP_HEIGHT.
     return ( get_map().get_abs_sub().z() < OVERMAP_HEIGHT );
 }
References get_map(), and OVERMAP_HEIGHT.
Referenced by complete_construction(), and load_construction().
do_turn_exhume()
void construct::do_turn_exhume (const tripoint_bub_ms & p, Character & who) static
Definition at line 1850 of file construction.cpp.
 {
     do_turn_shovel( p, who );
     if( !who.has_morale( MORALE_GRAVEDIGGER ) ) {
         if( who.has_trait( trait_SPIRITUAL ) && !who.has_trait( trait_PSYCHOPATH ) )  {
             if( who.query_yn(
                     _( "Would you really touch the sacred resting place of the dead?" ) ) ) {
                 add_msg( m_info, _( "Exhuming a grave is really against your beliefs." ) );
                 who.add_morale( MORALE_GRAVEDIGGER, -50, -100, 48_hours, 12_hours );
                 if( one_in( 3 ) ) {
                     who.vomit();
                 }
             } else {
                 who.activity.set_to_null();
             }
         } else if( who.has_trait( trait_PSYCHOPATH ) ) {
             who.add_msg_if_player(
                 m_good, _( "Exhuming a grave is fun now, when there is no one to object." ) );
             who.add_morale( MORALE_GRAVEDIGGER, 25, 50, 2_hours, 1_hours );
         } else if( who.has_trait( trait_NUMB ) ) {
             who.add_msg_if_player( m_bad, _( "You wonder if you dig up anything useful." ) );
             who.add_morale( MORALE_GRAVEDIGGER, -25, -50, 2_hours, 1_hours );
         } else if( !who.has_trait( trait_EATDEAD ) && !who.has_trait( trait_SAPROVORE ) ) {
             who.add_msg_if_player( m_bad, _( "Exhuming this grave is utterly disgusting!" ) );
             who.add_morale( MORALE_GRAVEDIGGER, -25, -50, 2_hours, 1_hours );
             if( one_in( 5 ) ) {
                 who.vomit();
             }
         }
     }
 }
References _, Character::activity, Character::add_morale(), add_msg(), Character::add_msg_if_player(), do_turn_shovel(), Character::has_morale(), Character::has_trait(), m_bad, m_good, m_info, MORALE_GRAVEDIGGER, one_in(), Character::query_yn(), player_activity::set_to_null(), trait_EATDEAD, trait_NUMB, trait_PSYCHOPATH, trait_SAPROVORE, trait_SPIRITUAL, and Character::vomit().
Referenced by load_construction().
do_turn_shovel()
void construct::do_turn_shovel (const tripoint_bub_ms & p, Character & who) static
Definition at line 1835 of file construction.cpp.
 {
     // TODO: fix point types
     sfx::play_activity_sound( "tool", "shovel", sfx::get_heard_volume( p.raw() ) );
     if( calendar::once_every( 1_minutes ) ) {
         // TODO: fix point types
         //~ Sound of a shovel digging a pit at work!
         sounds::sound( p.raw(), 10, sounds::sound_t::activity, _( "hsh!" ) );
     }
     // TODO: fix point types
     if( !who.knows_trap( p.raw() ) ) {
         get_map().maybe_trigger_trap( p, who, true );
     }
 }
References _, sounds::activity, sfx::get_heard_volume(), get_map(), Character::knows_trap(), map::maybe_trigger_trap(), calendar::once_every(), sfx::play_activity_sound(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), and sounds::sound().
Referenced by do_turn_exhume(), and load_construction().
done_appliance()
void construct::done_appliance (const tripoint_bub_ms & p, Character &) static
Definition at line 1519 of file construction.cpp.
 {
     map &here = get_map();
     partial_con *pc = here.partial_con_at( p );
     if( !pc ) {
         debugmsg( "constructing failed: can't find partial construction" );
         return;
     }
     const std::list<item> components = pc->components;
     here.partial_con_remove( p );
     if( components.size() != 1 ) {
         debugmsg( "constructing failed: components size expected 1 actual %d", components.size() );
         return;
     }
     const item &base = components.front();
     const vpart_id &vpart = vpart_appliance_from_item( base.typeId() );
     // TODO: fix point types
     place_appliance( p.raw(), vpart, base );
 }
References partial_con::components, debugmsg, get_map(), map::partial_con_at(), map::partial_con_remove(), place_appliance(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), item::typeId(), and vpart_appliance_from_item().
Referenced by load_construction().
done_deconstruct()
void construct::done_deconstruct (const tripoint_bub_ms & p, Character & player_character) static
Definition at line 1544 of file construction.cpp.
 {
     map &here = get_map();
     auto deconstruction_practice_skill = [ &player_character ]( auto & skill ) {
         if( player_character.get_skill_level( skill.id ) >= skill.min ) {
             // Uses a modified version of the complete_construction formula using 20 minutes with halved yield before the multiplier
             player_character.practice( skill.id,
                                        static_cast<int>( skill.multiplier * ( 5.0 / 6.0 ) * ( 10 + 7.5 * ( skill.min +
                                                skill.max ) ) ), skill.max );
         }
     };
     // TODO: Make this the argument
     if( here.has_furn( p ) ) {
         const furn_t &f = here.furn( p ).obj();
         if( !f.deconstruct.can_do ) {
             add_msg( m_info, _( "That %s can not be disassembled!" ), f.name() );
             return;
         }
         if( f.deconstruct.furn_set.str().empty() ) {
             here.furn_set( p, furn_str_id::NULL_ID() );
         } else {
             here.furn_set( p, f.deconstruct.furn_set );
         }
         add_msg( _( "The %s is disassembled." ), f.name() );
         item &item_here = here.i_at( p ).size() != 1 ? null_item_reference() : here.i_at( p ).only_item();
         const std::vector<item *> drop = here.spawn_items( p,
                                          item_group::items_from( f.deconstruct.drop_group, calendar::turn ) );
         if( f.deconstruct.skill.has_value() ) {
             deconstruction_practice_skill( f.deconstruct.skill.value() );
         }
         // if furniture has liquid in it and deconstructs into watertight containers then fill them
         if( f.has_flag( "LIQUIDCONT" ) && item_here.made_of( phase_id::LIQUID ) ) {
             for( item *it : drop ) {
                 if( it->get_remaining_capacity_for_liquid( item_here ) <= 0 ) {
                     continue;
                 }
                 item_here.charges -= it->fill_with( item_here, item_here.charges, false, true, true );
                 if( item_here.charges <= 0 ) {
                     here.i_rem( p, &item_here );
                     break;
                 }
             }
         }
         // HACK: Hack alert.
         // Signs have cosmetics associated with them on the submap since
         // furniture can't store dynamic data to disk. To prevent writing
         // mysteriously appearing for a sign later built here, remove the
         // writing from the submap.
         here.delete_signage( p );
     } else {
         const ter_t &t = here.ter( p ).obj();
         if( !t.deconstruct.can_do ) {
             add_msg( _( "That %s can not be disassembled!" ), t.name() );
             return;
         }
         if( t.deconstruct.deconstruct_above ) {
             const tripoint_bub_ms top = p + tripoint_above;
             if( here.has_furn( top ) ) {
                 add_msg( _( "That %s can not be disassembled, since there is furniture above it." ), t.name() );
                 return;
             }
             done_deconstruct( top, player_character );
         }
         here.ter_set( p, t.deconstruct.ter_set );
         add_msg( _( "The %s is disassembled." ), t.name() );
         here.spawn_items( p, item_group::items_from( t.deconstruct.drop_group, calendar::turn ) );
         if( t.deconstruct.skill.has_value() ) {
             deconstruction_practice_skill( t.deconstruct.skill.value() );
         }
     }
 }
References _, add_msg(), map_deconstruct_info::can_do, item::charges, map_data_common_t::deconstruct, map_deconstruct_info::deconstruct_above, map::delete_signage(), map_deconstruct_info::drop_group, map::furn(), map::furn_set(), map_deconstruct_info::furn_set, get_map(), Character::get_skill_level(), map_data_common_t::has_flag(), map::has_furn(), map::i_at(), map::i_rem(), item_group::items_from(), LIQUID, m_info, item::made_of(), map_data_common_t::name(), string_id< furn_t >::NULL_ID(), null_item_reference(), int_id< T >::obj(), item_stack::only_item(), Character::practice(), item_stack::size(), map_deconstruct_info::skill, map::spawn_items(), string_id< T >::str(), map::ter(), map::ter_set(), map_deconstruct_info::ter_set, tripoint_above, and calendar::turn.
Referenced by load_construction().
done_dig_grave()
void construct::done_dig_grave (const tripoint_bub_ms & p, Character & who) static
Definition at line 1670 of file construction.cpp.
 {
     map &here = get_map();
     if( one_in( 10 ) ) {
         static const std::array<mtype_id, 5> monids = {
             { mon_zombie, mon_zombie_fat, mon_zombie_rot, mon_skeleton, mon_zombie_crawler }
         };
         // TODO: fix point types
         g->place_critter_at( random_entry( monids ), p.raw() );
         here.furn_set( p, furn_f_coffin_o );
         who.add_msg_if_player( m_warning, _( "Something crawls out of the coffin!" ) );
     } else {
         // TODO: fix point types
         here.spawn_item( p.raw(), itype_bone_human, rng( 5, 15 ) );
         here.furn_set( p, furn_f_coffin_c );
     }
     std::vector<item *> dropped =
         here.place_items( Item_spawn_data_allclothes, 50, p, p, false, calendar::turn );
     here.place_items( Item_spawn_data_grave, 25, p, p, false, calendar::turn );
     here.place_items( Item_spawn_data_jewelry_front, 20, p, p, false, calendar::turn );
     for( item * const &it : dropped ) {
         if( it->is_armor() ) {
             it->set_flag( json_flag_FILTHY );
             it->set_damage( rng( 1, it->max_damage() - 1 ) );
             it->rand_degradation();
         }
     }
     get_event_bus().send<event_type::exhumes_grave>( who.getID() );
 }
References _, Character::add_msg_if_player(), exhumes_grave, furn_f_coffin_c, furn_f_coffin_o, map::furn_set(), g, get_event_bus(), get_map(), Character::getID(), Item_spawn_data_allclothes, Item_spawn_data_grave, Item_spawn_data_jewelry_front, itype_bone_human, json_flag_FILTHY, m_warning, mon_skeleton, mon_zombie, mon_zombie_crawler, mon_zombie_fat, mon_zombie_rot, one_in(), map::place_items(), random_entry(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), rng(), event_bus::send(), map::spawn_item(), and calendar::turn.
Referenced by load_construction().
done_dig_grave_nospawn()
void construct::done_dig_grave_nospawn (const tripoint_bub_ms & p, Character & who) static
Definition at line 1701 of file construction.cpp.
 {
     get_map().furn_set( p, furn_f_coffin_c );
     get_event_bus().send<event_type::exhumes_grave>( who.getID() );
 }
References exhumes_grave, furn_f_coffin_c, map::furn_set(), get_event_bus(), get_map(), Character::getID(), and event_bus::send().
Referenced by load_construction().
done_dig_stair()
void construct::done_dig_stair (const tripoint_bub_ms & p, Character & who) static
Definition at line 1707 of file construction.cpp.
 {
     done_digormine_stair( p, true, who );
 }
References done_digormine_stair().
Referenced by load_construction().
done_digormine_stair()
void construct::done_digormine_stair (const tripoint_bub_ms & p, bool dig, Character & player_character) static
Definition at line 1629 of file construction.cpp.
 {
     map &here = get_map();
     const tripoint_bub_ms p_below = p + tripoint_below;
     bool dig_muts = player_character.has_trait( trait_PAINRESIST_TROGLO ) ||
                     player_character.has_trait( trait_STOCKY_TROGLO );
     int no_mut_penalty = dig_muts ? 10 : 0;
     int mine_penalty = dig ? 0 : 10;
     player_character.mod_stored_kcal( -43 - 9 * mine_penalty - 9 * no_mut_penalty );
     player_character.mod_thirst( 5 + mine_penalty + no_mut_penalty );
     player_character.mod_sleepiness( 10 + mine_penalty + no_mut_penalty );
     if( here.ter( p_below ) == ter_t_lava ) {
         if( !query_yn( _( "The rock feels much warmer than normal.  Proceed?" ) ) ) {
             here.ter_set( p, ter_t_pit ); // You dug down a bit before detecting the problem
             unroll_digging( dig ? 8 : 12 );
         } else {
             add_msg( m_warning, _( "You just tunneled into lava!" ) );
             get_event_bus().send<event_type::digs_into_lava>();
             here.ter_set( p, ter_t_hole );
         }
         return;
     }
     bool impassable = here.impassable( p_below );
     if( !impassable ) {
         add_msg( _( "You dig into a preexisting space, and improvise a ladder." ) );
     } else if( dig ) {
         add_msg( _( "You dig a stairway, adding sturdy timbers and a rope for safety." ) );
     } else {
         add_msg( _( "You drill out a passage, heading deeper underground." ) );
     }
     here.ter_set( p, ter_t_stairs_down ); // There's the top half
     here.ter_set( p_below, impassable ? ter_t_stairs_up :
                   ter_t_ladder_up ); // and there's the bottom half.
 }
References _, add_msg(), iuse::dig(), digs_into_lava, get_event_bus(), get_map(), Character::has_trait(), map::impassable(), impassable, m_warning, Character::mod_sleepiness(), Character::mod_stored_kcal(), Character::mod_thirst(), query_yn(), event_bus::send(), map::ter(), map::ter_set(), ter_t_hole, ter_t_ladder_up, ter_t_lava, ter_t_pit, ter_t_stairs_down, ter_t_stairs_up, trait_PAINRESIST_TROGLO, trait_STOCKY_TROGLO, tripoint_below, and unroll_digging().
Referenced by done_dig_stair(), and done_mine_downstair().
done_extract_maybe_revert_to_dirt()
void construct::done_extract_maybe_revert_to_dirt (const tripoint_bub_ms & p, Character &) static
Definition at line 1768 of file construction.cpp.
 {
     map &here = get_map();
     if( one_in( 10 ) ) {
         here.ter_set( p, ter_t_dirt );
     }
     if( here.ter( p ) == ter_t_clay ) {
         add_msg( _( "You gather some clay." ) );
     } else if( here.ter( p ) == ter_t_sand ) {
         add_msg( _( "You gather some sand." ) );
     } else {
         // Fall through to an undefined material.
         add_msg( _( "You gather some materials." ) );
     }
 }
References _, add_msg(), get_map(), one_in(), map::ter(), map::ter_set(), ter_t_clay, ter_t_dirt, and ter_t_sand.
Referenced by load_construction().
done_grave()
void construct::done_grave (const tripoint_bub_ms & p, Character & player_character) static
Definition at line 1406 of file construction.cpp.
 {
     map &here = get_map();
     map_stack its = here.i_at( p );
     for( const item &it : its ) {
         if( it.is_corpse() ) {
             if( it.get_corpse_name().empty() ) {
                 if( it.get_mtype()->has_flag( mon_flag_HUMAN ) ) {
                     if( player_character.has_trait( trait_SPIRITUAL ) ) {
                         player_character.add_morale( MORALE_FUNERAL, 50, 75, 1_days, 1_hours );
                         add_msg( m_good,
                                  _( "You feel relieved after providing last rites for this human being, whose name is lost in the Cataclysm." ) );
                     } else {
                         add_msg( m_neutral, _( "You bury remains of a human, whose name is lost in the Cataclysm." ) );
                     }
                 }
             } else {
                 if( player_character.has_trait( trait_SPIRITUAL ) ) {
                     player_character.add_morale( MORALE_FUNERAL, 50, 75, 1_days, 1_hours );
                     add_msg( m_good,
                              _( "You feel sadness, but also relief after providing last rites for %s, whose name you will keep in your memory." ),
                              it.get_corpse_name() );
                 } else {
                     add_msg( m_neutral,
                              _( "You bury remains of %s, who joined uncounted masses perished in the Cataclysm." ),
                              it.get_corpse_name() );
                 }
             }
             get_event_bus().send<event_type::buries_corpse>(
                 player_character.getID(), it.get_mtype()->id, it.get_corpse_name() );
         }
     }
     if( player_character.has_quality( qual_CUT ) ) {
         // TODO: fix point types
         iuse::handle_ground_graffiti( player_character, nullptr, _( "Inscribe something on the grave?" ),
                                       p.raw() );
     } else {
         add_msg( m_neutral,
                  _( "Unfortunately you don't have anything sharp to place an inscription on the grave." ) );
     }
     here.destroy_furn( p, true );
 }
References _, Character::add_morale(), add_msg(), buries_corpse, map::destroy_furn(), get_event_bus(), get_map(), Character::getID(), iuse::handle_ground_graffiti(), Character::has_quality(), Character::has_trait(), map::i_at(), m_good, m_neutral, mon_flag_HUMAN, MORALE_FUNERAL, qual_CUT, coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), event_bus::send(), and trait_SPIRITUAL.
Referenced by load_construction().
done_mark_firewood()
void construct::done_mark_firewood (const tripoint_bub_ms & p, Character &) static
Definition at line 1785 of file construction.cpp.
 {
     get_map().trap_set( p, tr_firewood_source );
 }
References get_map(), tr_firewood_source, and map::trap_set().
Referenced by load_construction().
done_mark_practice_target()
void construct::done_mark_practice_target (const tripoint_bub_ms & p, Character &) static
Definition at line 1790 of file construction.cpp.
 {
     get_map().trap_set( p, tr_practice_target );
 }
References get_map(), tr_practice_target, and map::trap_set().
Referenced by load_construction().
done_mine_downstair()
void construct::done_mine_downstair (const tripoint_bub_ms & p, Character & who) static
Definition at line 1712 of file construction.cpp.
 {
     done_digormine_stair( p, false, who );
 }
References done_digormine_stair().
Referenced by load_construction().
done_mine_upstair()
void construct::done_mine_upstair (const tripoint_bub_ms & p, Character & player_character) static
Definition at line 1717 of file construction.cpp.
 {
     map &here = get_map();
     const tripoint_bub_ms p_above = p + tripoint_above;
     if( here.ter( p_above ) == ter_t_lava ) {
         here.ter_set( p, ter_t_rock_floor ); // You dug a bit before discovering the problem
         add_msg( m_warning, _( "The rock overhead feels hot.  You decide *not* to mine magma." ) );
         unroll_digging( 12 );
         return;
     }
     if( here.has_flag_ter( ter_furn_flag::TFLAG_SHALLOW_WATER, p_above.raw() ) ||
         here.has_flag_ter( ter_furn_flag::TFLAG_DEEP_WATER, p_above.raw() ) ) {
         here.ter_set( p, ter_t_rock_floor ); // You dug a bit before discovering the problem
         add_msg( m_warning, _( "The rock above is rather damp.  You decide *not* to mine water." ) );
         unroll_digging( 12 );
         return;
     }
     bool dig_muts = player_character.has_trait( trait_PAINRESIST_TROGLO ) ||
                     player_character.has_trait( trait_STOCKY_TROGLO );
     int no_mut_penalty = dig_muts ? 15 : 0;
     player_character.mod_stored_kcal( -174 - 9 * no_mut_penalty );
     player_character.mod_thirst( 20 + no_mut_penalty );
     player_character.mod_sleepiness( 25 + no_mut_penalty );
     add_msg( _( "You drill out a passage, heading for the surface." ) );
     here.ter_set( p, ter_t_stairs_up ); // There's the bottom half
     here.ter_set( p_above, ter_t_stairs_down ); // and there's the top half.
 }
References _, add_msg(), get_map(), map::has_flag_ter(), Character::has_trait(), m_warning, Character::mod_sleepiness(), Character::mod_stored_kcal(), Character::mod_thirst(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), map::ter(), map::ter_set(), ter_t_lava, ter_t_rock_floor, ter_t_stairs_down, ter_t_stairs_up, TFLAG_DEEP_WATER, TFLAG_SHALLOW_WATER, trait_PAINRESIST_TROGLO, trait_STOCKY_TROGLO, tripoint_above, and unroll_digging().
Referenced by load_construction().
done_nothing()
static void construct::done_nothing (const tripoint_bub_ms & , Character &) static
Definition at line 181 of file construction.cpp.
 {}
Referenced by load_construction().
done_ramp_high()
void construct::done_ramp_high (const tripoint_bub_ms & p, Character &) static
Definition at line 1801 of file construction.cpp.
 {
     const tripoint_bub_ms top = p + tripoint_above;
     get_map().ter_set( top, ter_t_ramp_down_high );
 }
References get_map(), map::ter_set(), ter_t_ramp_down_high, and tripoint_above.
Referenced by load_construction().
done_ramp_low()
void construct::done_ramp_low (const tripoint_bub_ms & p, Character &) static
Definition at line 1795 of file construction.cpp.
 {
     const tripoint_bub_ms top = p + tripoint_above;
     get_map().ter_set( top, ter_t_ramp_down_low );
 }
References get_map(), map::ter_set(), ter_t_ramp_down_low, and tripoint_above.
Referenced by load_construction().
done_trunk_plank()
void construct::done_trunk_plank (const tripoint_bub_ms & , Character &) static
Definition at line 1397 of file construction.cpp.
 {
     int num_logs = rng( 2, 3 );
     Character &player_character = get_player_character();
     for( int i = 0; i < num_logs; ++i ) {
         iuse::cut_log_into_planks( player_character );
     }
 }
References iuse::cut_log_into_planks(), get_player_character(), and rng().
Referenced by load_construction().
done_vehicle()
void construct::done_vehicle (const tripoint_bub_ms & p, Character &) static
Definition at line 1469 of file construction.cpp.
 {
     std::string name = string_input_popup()
                        .title( _( "Enter new vehicle name:" ) )
                        .width( 20 )
                        .query_string();
     if( name.empty() ) {
         name = _( "Car" );
     }
     map &here = get_map();
     partial_con *pc = here.partial_con_at( p );
     if( !pc ) {
         debugmsg( "constructing failed: can't find partial construction" );
         return;
     }
     const std::list<item> components = pc->components;
     here.partial_con_remove( p );
     if( components.size() != 1 ) {
         debugmsg( "constructing failed: components size expected 1 actual %d", components.size() );
         return;
     }
     // TODO: fix point types
     vehicle *veh = here.add_vehicle( vehicle_prototype_none, p.raw(), 270_degrees, 0, 0 );
     if( !veh ) {
         debugmsg( "constructing failed: add_vehicle returned null" );
         return;
     }
     const item &base = components.front();
     veh->name = name;
     const int partnum = veh->install_part( point_zero, vpart_from_item( base.typeId() ), item( base ) );
     veh->part( partnum ).set_flag( vp_flag::unsalvageable_flag );
     // Update the vehicle cache immediately,
     // or the vehicle will be invisible for the first couple of turns.
     here.add_vehicle_to_cache( veh );
 }
References _, map::add_vehicle(), map::add_vehicle_to_cache(), partial_con::components, debugmsg, get_map(), vehicle::install_part(), om_direction::name(), vehicle::name, vehicle::part(), map::partial_con_at(), map::partial_con_remove(), point_zero, string_input_popup::query_string(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), vehicle_part::set_flag(), string_input_popup::title(), item::typeId(), unsalvageable_flag, vehicle_prototype_none, vpart_from_item(), and string_input_popup::width().
Referenced by load_construction().
done_window_curtains()
void construct::done_window_curtains (const tripoint_bub_ms & , Character & who) static
Definition at line 1756 of file construction.cpp.
 {
     map &here = get_map();
     tripoint avatar_pos = who.pos();
     // copied from iexamine::curtains
     here.spawn_item( avatar_pos, itype_nail, 1, 4 );
     here.spawn_item( avatar_pos, itype_sheet, 2 );
     here.spawn_item( avatar_pos, itype_stick );
     here.spawn_item( avatar_pos, itype_string_36 );
     add_msg( _( "After boarding up the window the curtains and curtain rod are left." ) );
 }
References _, add_msg(), get_map(), itype_nail, itype_sheet, itype_stick, itype_string_36, Creature::pos(), and map::spawn_item().
Referenced by load_construction().
done_wiring()
void construct::done_wiring (const tripoint_bub_ms & p, Character &) static
Definition at line 1512 of file construction.cpp.
 {
     get_map().partial_con_remove( p );
     place_appliance( p.raw(), vpart_from_item( itype_wall_wiring ) );
 }
References get_map(), itype_wall_wiring, map::partial_con_remove(), place_appliance(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), and vpart_from_item().
Referenced by load_construction().
done_wood_stairs()
void construct::done_wood_stairs (const tripoint_bub_ms & p, Character &) static
Definition at line 1750 of file construction.cpp.
 {
     const tripoint_bub_ms top = p + tripoint_above;
     get_map().ter_set( top, ter_t_wood_stairs_down );
 }
References get_map(), map::ter_set(), ter_t_wood_stairs_down, and tripoint_above.
Referenced by load_construction().
failure_deconstruct()
void construct::failure_deconstruct (const tripoint_bub_ms &) static
Definition at line 1887 of file construction.cpp.
 {
     add_msg( m_info, _( "You cannot deconstruct this!" ) );
 }
References _, add_msg(), and m_info.
Referenced by load_construction().
failure_standard()
void construct::failure_standard (const tripoint_bub_ms &) static
Definition at line 1882 of file construction.cpp.
 {
     add_msg( m_info, _( "You cannot build there!" ) );
 }
References _, add_msg(), and m_info.
Referenced by load_construction().
remove_above()
void construct::remove_above (const tripoint_bub_ms & p, Character &) static
Definition at line 1818 of file construction.cpp.
 {
     map &here = get_map();
     here.ter_set( p + tripoint_above, ter_t_open_air );
 }
References get_map(), map::ter_set(), ter_t_open_air, and tripoint_above.
Referenced by load_construction().