Cataclysm DDA: anonymous_namespace{recipe_groups.cpp} Namespace Reference
anonymous_namespace{recipe_groups.cpp} Namespace Reference
Classes
struct omt_types_parameters
struct recipe_group_data
Typedefs
using group_id = string_id< recipe_group_data >
Variables
generic_factory< recipe_group_data > recipe_groups_data ("recipe group type")
Typedef Documentation
group_id
using anonymous_namespace{recipe_groups.cpp}::group_id = typedef string_id<recipe_group_data>
Definition at line 22 of file recipe_groups.cpp.
Variable Documentation
recipe_groups_data
generic_factory<recipe_group_data> anonymous_namespace{recipe_groups.cpp}::recipe_groups_data("recipe group type") ("recipe group type")
Referenced by recipe_group::check(), recipe_group::get_building_of_recipe(), recipe_group::get_recipes_by_bldg(), recipe_group::get_recipes_by_id(), recipe_group::load(), and recipe_group::reset().