Cataclysm DDA: math_opers Namespace Reference
math_opers Namespace Reference
Functions
constexpr double neg (double, double r)
constexpr double pos (double, double r)
constexpr double add (double l, double r)
constexpr double sub (double l, double r)
constexpr double mul (double l, double r)
constexpr double div (double l, double r)
double mod (double l, double r)
double math_pow (double l, double r)
double lt (double l, double r)
double lte (double l, double r)
double gt (double l, double r)
double gte (double l, double r)
double eq (double l, double r)
double neq (double l, double r)
double b_neg (double, double r)
Function Documentation
add()
constexpr double math_opers::add (double l, double r) constexpr
Definition at line 208 of file math_parser_impl.h.
 {
     return l + r;
 }
b_neg()
double math_opers::b_neg (double , double r) inline
Definition at line 268 of file math_parser_impl.h.
 {
     return static_cast<double>( float_equals( r, 0 ) );
 }
References float_equals().
div()
constexpr double math_opers::div (double l, double r) constexpr
Definition at line 223 of file math_parser_impl.h.
 {
     return l / r;
 }
Referenced by Creature::deal_damage_handle_type(), game::display_scent(), scent_map::draw(), and insert_table().
eq()
double math_opers::eq (double l, double r) inline
Definition at line 258 of file math_parser_impl.h.
 {
     return static_cast<double>( l == r );
 }
Referenced by cata::list< element_type, element_allocator_type >::unique().
gt()
double math_opers::gt (double l, double r) inline
Definition at line 248 of file math_parser_impl.h.
 {
     return static_cast<double>( l > r );
 }
Referenced by value_constraint::deserialize(), and event_transformation_impl::updatable_value_constraint::permits().
gte()
double math_opers::gte (double l, double r) inline
Definition at line 253 of file math_parser_impl.h.
 {
     return static_cast<double>( l >= r );
 }
lt()
double math_opers::lt (double l, double r) inline
Definition at line 238 of file math_parser_impl.h.
 {
     return static_cast<double>( l < r );
 }
Referenced by value_constraint::deserialize(), and event_transformation_impl::updatable_value_constraint::permits().
lte()
double math_opers::lte (double l, double r) inline
Definition at line 243 of file math_parser_impl.h.
 {
     return static_cast<double>( l <= r );
 }
math_pow()
double math_opers::math_pow (double l, double r) inline
Definition at line 233 of file math_parser_impl.h.
 {
     return std::pow( l, r );
 }
mod()
double math_opers::mod (double l, double r) inline
Definition at line 228 of file math_parser_impl.h.
 {
     return std::fmod( l, r );
 }
References units::fmod().
mul()
constexpr double math_opers::mul (double l, double r) constexpr
Definition at line 218 of file math_parser_impl.h.
 {
     return l * r;
 }
Referenced by map::emit_field(), and Character::generic_weakpoint_skill().
neg()
constexpr double math_opers::neg (double , double r) constexpr
Definition at line 198 of file math_parser_impl.h.
 {
     return -r;
 }
Referenced by TextJsonIn::get_any_number().
neq()
double math_opers::neq (double l, double r) inline
Definition at line 263 of file math_parser_impl.h.
 {
     return static_cast<double>( l != r );
 }
pos()
constexpr double math_opers::pos (double , double r) constexpr
Definition at line 203 of file math_parser_impl.h.
 {
     return r;
 }
Referenced by map::_add_item_or_charges(), anonymous_namespace{item.cpp}::_stacks_location_hint(), iuse::acidbomb_act(), computer_session::action_close_gate(), computer_session::action_lock(), computer_session::action_open(), computer_session::action_open_gate(), computer_session::action_toll(), computer_session::action_unlock(), item::activate_thrown(), item::activation_consume(), scrollingcombattext::add(), map_item_stack::add_at_pos(), map::add_item_or_charges(), tinymap::add_item_or_charges(), map::add_item_ret_loc(), joins_tracker::add_joins_for(), inventory_selector::add_nearby_items(), add_summoned_mon(), joins_tracker::indexed_joins::all_at(), joins_tracker::all_unresolved_at(), map_memory::allocate_submap(), vehicle_part::ammo_consume(), item::ammo_consume(), item_contents::ammo_consume(), joins_tracker::indexed_joins::any_at(), VehicleFunction_json::apply(), apply_construction_marker(), bgcolor_from_string(), map::board_vehicle(), mattack::browse(), MapExtras::burned_ground_parser(), butcher_dissect_item(), butchery_quarter(), calc_steadiness(), calculate_ranged_chances(), use_function::call(), computer_session::can_activate(), use_function::can_call(), map::can_move_furniture(), can_recharge_lunar(), can_recharge_solar(), trap::can_see(), iuse::capture_monster_act(), iuse::capture_monster_veh(), game::catch_a_monster(), centerlistview(), debug_menu::character_edit_hp_menu(), fixed_overmap_special_data::check(), check_deploy_square(), choose_adjacent(), choose_adjacent_highlight(), map_memory::clear_tile_decoration(), color_from_string(), compost_set_empty(), compost_set_full(), query_popup::button::contains(), game::control_vehicle(), joins_tracker::count_unresolved_at(), create_radio_tower_reference(), map::creature_on_trap(), iuse::crowbar(), iuse::crowbar_weak(), scrollingcombattext::cSCT::cSCT(), query_popup::cursor(), salvage_actor::cut_up(), cycle_action(), target_ui::cycle_targets(), iuse::dbg_lux_meter(), iexamine::deployed_furniture(), map::deregister_vehicle_zone(), vehicle::deserialize(), item_location::deserialize(), climbing_aid::detect_conditions(), trap::detect_trap(), item_pocket::detonate(), dig_tool(), iexamine::dirtmound(), overmap_ui::display(), help::display_help(), veh_interact::display_list(), veh_interact::display_mode(), game::display_visibility(), ui::omap::display_visible_weather(), ui::omap::display_weather(), explosion_handler::do_blast(), veh_interact::do_install(), veh_interact::do_remove(), veh_interact::do_repair(), drop_activity_actor::do_turn(), stash_activity_actor::do_turn(), overmap_ui::draw_ascii(), draw_bionics_tab(), draw_connectors(), draw_custom_border(), explosion_handler::draw_custom_explosion(), draw_effects_tab(), overmap_ui::draw_om_sidebar(), draw_proficiencies_tab(), mission_ui_impl::draw_selected_description(), draw_speed_tab(), draw_traits_tab(), mattack::eat_carrion(), mattack::eat_food(), iuse::ehandcuffs_tick(), iexamine::elevator(), iuse::emf_passive_on(), map::emit_field(), item::energy_consume(), iuse::epic_music(), overmap_special_batch::erase(), map::examine(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), computer_session::failure_destroy_blood(), computer_session::failure_destroy_data(), computer_session::failure_manhacks(), computer_session::failure_secubots(), computer_session::failure_shutdown(), farm_action(), creature_tracker::find(), find_cosmetic(), find_empty_spot_nearby(), game::find_or_make_stairs(), chop_logs_activity_actor::finish(), chop_tree_activity_actor::finish(), clear_rubble_activity_actor::finish(), iuse::firecracker_pack_act(), iexamine::fireplace(), iuse::fish_trap_tick(), iuse::foodperson_voice(), game::forced_door_closing(), format_item_info(), fvat_set_empty(), fvat_set_full(), iuse::gasmask(), iuse::geiger_active(), map::generate(), map::generate_lightmap(), lru_cache< Key, Value >::get(), map::get_active_items_in_radius(), TextJsonObject::get_array(), get_auto_consume_moves(), TextJsonObject::get_bool(), get_changed_ids_from_update(), input_context::get_desc(), TextJsonObject::get_float(), anonymous_namespace{gates.cpp}::get_gate_id(), map::get_harvest(), map::get_harvest_names(), map::get_haulable_items(), sfx::get_heard_angle(), sfx::get_heard_volume(), TextJsonObject::get_int(), get_item_location(), outfit::get_item_position(), get_keg_capacity(), overmap_ui::get_note_display_info(), overmapbuffer::get_npcs_near(), overmapbuffer::get_npcs_near_omt(), TextJsonObject::get_object(), get_patient(), TextJsonObject::get_raw(), map::get_rc_items(), overmap_ui::get_scent_glyph(), TextJsonObject::get_string(), get_tag_positions(), TextJsonObject::get_tags(), map_memory::get_tile(), overmapbuffer::get_travel_path(), overmap_ui::get_weather_at_point(), map::get_wind_blockers(), scrollingcombattext::cSCT::getPosX(), scrollingcombattext::cSCT::getPosY(), good_fishing_spot(), iuse::granade_act(), mattack::graze(), iuse::grenade_inc_act(), mattack::grow_vine(), iuse::hammer(), handle_action_menu(), liquid_handler::handle_liquid_from_ground(), TextJsonObject::has_array(), TextJsonObject::has_bool(), map::has_haulable_items(), iexamine::has_keg(), has_neighbor(), TextJsonObject::has_null(), TextJsonObject::has_number(), TextJsonObject::has_object(), has_quality_from_vpart(), TextJsonObject::has_string(), hilite_string(), anonymous_namespace{animation.cpp}::hit_animation(), lru_cache< Key, Value >::insert(), itype::invoke(), place_trap_actor::is_allowed(), map::is_harvestable(), is_obstacle(), is_solid_neighbor(), anonymous_namespace{gates.cpp}::gate_data::is_suitable_wall(), iuse::jackhammer(), activity_handlers::jackhammer_finish(), item::leak(), item_contents::leak(), item_pocket::leak(), firestarter_actor::light_mod(), TextJsonIn::line_number(), npc::load(), vehicle_prototype::load(), map_memory::load(), map_memory::load_submap(), anonymous_namespace{item_tname.cpp}::location_hint(), logarithmic_range(), iuse::lux_meter(), make_node_address(), map_item_stack::map_item_stack(), map_selector::map_selector(), max_quality_from_vpart(), maybe_shift(), map::maybe_trigger_prox_trap(), map::maybe_trigger_trap(), target_handler::mode_turrets(), iuse::molotov_lit(), veh_interact::move_in_list(), move_to_parent_pocket_recursive(), firestarter_actor::moves_cost_by_fuel(), iuse::mp3_on(), iuse::multicooker(), iuse::multicooker_tick(), MapExtras::mx_helicopter(), inventory_selector::naturalize_category(), new_centered_win(), iuse::noise_emitter_on(), npc_throw(), om_range_mark(), item::on_drop(), gates::open_gate(), anonymous_namespace{debug_menu.cpp}::operator>>(), item_contents::overflow(), item_pocket::overflow(), item::overflow(), overlaps_vehicle(), iuse::pick_lock(), joins_tracker::pick_top_priority(), iuse::pickaxe(), activity_handlers::pickaxe_do_turn(), activity_handlers::pickaxe_finish(), mutable_overmap_special_data::place(), place_and_add_as_known(), game::place_player(), overmap_ui::place_ter_or_special(), iuse::plantblech(), veh_app_interact::plug(), joins_tracker::postpone(), iexamine::pour_into_keg(), firestarter_actor::prep_firestarter_use(), print_aim(), item_pocket::process(), item_contents::process(), item::process(), vehicle_part::process_contents(), item::process_corpse(), item::process_extinguish(), item::process_fake_mill(), item::process_fake_smoke(), item::process_internal(), map::process_items(), item::process_link(), item::process_litcig(), item::process_relic(), sounds::process_sound_markers(), item::process_temperature_rot(), item::process_tool(), activity_handlers::pulp_do_turn(), iuse::radio_tick(), TextJsonObject::read(), cata::string_formatter::read_argument_index(), read_legacy_creature_pos(), item::ready_to_revive(), inventory::reduce_stack(), iuse::remoteveh(), lru_cache< Key, Value >::remove(), anonymous_namespace{monexamine.cpp}::remove_battery(), inventory::remove_item(), replace_keybind_tag(), replace_substring(), game::reset_item_list_state(), vehicle_part::reset_target(), firestarter_actor::resolve_firestarter_use(), joins_tracker::restore_postponed_at(), retroactively_fill_from_funnel(), zone_manager::revert_vzones(), rm_prefix(), robot_finds_kitten::robot_finds_kitten(), mutable_overmap_phase_remainder::satisfy(), map_memory::save(), basecamp::scan_pseudo_items(), TextJsonIn::seek(), JsonOut::seek(), vehicle::serialize(), serialize_liquid_source(), serialize_liquid_target(), border_helper::border_info::set(), ui_adaptor::set_cursor(), set_description(), map_memory::set_tile_decoration(), map_memory::set_tile_symbol(), map_memory::set_tile_terrain(), iuse::sextant(), map::shift_traps(), iuse::shocktonfa_off(), iuse::shocktonfa_on(), shortcut_text(), robot_finds_kitten::show(), safemode::show(), iuse::siphon(), outfit::sort_armor(), map::spawn_monsters_submap(), spell_effect_area(), item::spill_contents(), item_contents::spill_contents(), item_pocket::spill_contents(), activity_handlers::start_engines_finish(), game::start_game(), game::start_hauling(), string_replace(), debug_menu::string_to_iterable(), TextJsonIn::substr(), iuse::tazer(), iuse::tazer2(), TextJsonObject::throw_error_at(), itype::tick(), tokenize(), trap::trigger(), trim_by_length(), try_fuel_fire(), relic::try_recharge(), update_mapgen_function_json::update_map(), message_iuse::use(), sound_iuse::use(), explosion_iuse::use(), delayed_transform_iuse::use(), deploy_furn_actor::use(), deploy_appliance_actor::use(), firestarter_actor::use(), fireweapon_on_actor::use(), holster_actor::use(), heal_actor::use(), place_trap_actor::use(), emit_actor::use(), iuse_function_wrapper::use(), item_stack::use_charges(), item::use_charges(), item::use_relic(), utf8_display_split_into(), math_exp::math_exp_impl::validate_string(), debug_menu::vehicle_battery_charge(), debug_menu::vehicle_export(), vehicle_selector::vehicle_selector(), warm_enough_to_plant(), game::wield(), wildcard_match(), wildcard_trim_rule(), debug_menu::wishitem(), and game::zones_manager().
sub()
constexpr double math_opers::sub (double l, double r) constexpr
Definition at line 213 of file math_parser_impl.h.
 {
     return l - r;
 }
Referenced by Item_factory::add_entry(), json_item_substitution::get_substitution(), profession::items(), json_item_substitution::load(), melee_actor::load_internal(), and mapgen_palette::load_place_mapings().