Cataclysm DDA: Pickup Namespace Reference
Pickup Namespace Reference
Classes
struct pick_info
Pick up information reminder for bulk loading.
struct pickup_rect
Enumerations
enum from_where : int { from_cargo = 0 , from_ground , prompt }
Functions
bool do_pickup (std::vector< item_location > &targets, std::vector< int > &quantities, bool autopickup, bool &stash_successful, Pickup::pick_info &info)
Returns false if the player was presented a prompt and decided to cancel the pickup.
bool query_thief ()
void autopickup (const tripoint &p)
Pick up items; 'g' or ',' or via examine()
int cost_to_move_item (const Character &who, const item &it)
Determines the cost of moving an item by a character.
Enumeration Type Documentation
from_where
enum Pickup::from_where : int
Enumerator
from_cargo
from_ground
prompt
Definition at line 39 of file pickup.h.
                 : int {
     from_cargo = 0,
     from_ground,
     prompt
 };
Function Documentation
autopickup()
void Pickup::autopickup (const tripoint & p)
Pick up items; 'g' or ',' or via examine()
Definition at line 393 of file pickup.cpp.
 {
     map &local = get_map();
     if( local.i_at( p ).empty() && !get_option<bool>( "AUTO_PICKUP_ADJACENT" ) ) {
         return;
     }
     // which items are we grabbing?
     std::vector<item_stack::iterator> here;
     const map_stack mapitems = local.i_at( p );
     for( item_stack::iterator it = mapitems.begin(); it != mapitems.end(); ++it ) {
         here.push_back( it );
     }
     Character &player = get_player_character();
     // Recursively pick up adjacent items if that option is on.
     if( get_option<bool>( "AUTO_PICKUP_ADJACENT" ) && player.pos() == p ) {
         //Autopickup adjacent
         std::array<direction, 8> adjacentDir = {
             direction::NORTH, direction::NORTHEAST, direction::EAST,
             direction::SOUTHEAST, direction::SOUTH, direction::SOUTHWEST,
             direction::WEST, direction::NORTHWEST
         };
         for( direction &elem : adjacentDir ) {
             tripoint apos = tripoint( displace_XY( elem ), 0 );
             apos += p;
             autopickup( apos );
         }
     }
     // Bail out if this square cannot be auto-picked-up
     if( g->check_zone( zone_type_NO_AUTO_PICKUP, p ) ||
         local.has_flag( ter_furn_flag::TFLAG_SEALED, p ) ) {
         return;
     }
     drop_locations selected_items = auto_pickup::select_items( here, p );
     if( selected_items.empty() ) {
         return;
     }
     // At this point we've selected our items, register an activity to pick them up.
     std::vector<int> quantities;
     std::vector<item_location> target_items;
     for( drop_location selected : selected_items ) {
         item *it = selected.first.get_item();
         target_items.push_back( selected.first );
         quantities.push_back( it->count_by_charges() ? it->charges : 0 );
     }
     pickup_activity_actor actor( target_items, quantities, player.pos(), true );
     player.assign_activity( actor );
     // Auto pickup will need to auto resume since there can be several of them on the stack.
     player.activity.auto_resume = true;
 }
References PATH_INFO::autopickup(), item_stack::begin(), item::charges, item::count_by_charges(), displace_XY(), EAST, item_stack::empty(), item_stack::end(), g, get_map(), get_player_character(), map::has_flag(), map::i_at(), NORTH, NORTHEAST, NORTHWEST, player, auto_pickup::select_items(), SOUTH, SOUTHEAST, SOUTHWEST, TFLAG_SEALED, WEST, and zone_type_NO_AUTO_PICKUP.
Referenced by game::place_player().
cost_to_move_item()
int Pickup::cost_to_move_item (const Character & who, const item & it)
Determines the cost of moving an item by a character.
Definition at line 447 of file pickup.cpp.
 {
     // Do not involve inventory capacity, it's not like you put it in backpack
     int ret = 50;
     if( who.is_armed() ) {
         // No free hand? That will cost you extra
         ret += 20;
     }
     const int delta_weight = units::to_gram( it.weight() - who.weight_capacity() );
     // Is it too heavy? It'll take 10 moves per kg over limit
     ret += std::max( 0, delta_weight / 100 );
     // Keep it sane - it's not a long activity
     return std::min( 400, ret );
 }
References Character::is_armed(), max(), min(), cata::hash64_detail::ret, units::to_gram(), item::weight(), and Character::weight_capacity().
Referenced by move_items_activity_actor::do_turn(), item_move_cost(), and activity_handlers::move_cost_cart().
do_pickup()
bool Pickup::do_pickup (std::vector< item_location > & targets, std::vector< int > & quantities, bool autopickup, bool & stash_successful, Pickup::pick_info & info)
Returns false if the player was presented a prompt and decided to cancel the pickup.
true in other cases.
Definition at line 336 of file pickup.cpp.
 {
     bool got_water = false;
     bool got_gas = false;
     bool got_frozen_liquid = false;
     Character &player_character = get_player_character();
     bool weight_is_okay = ( player_character.weight_carried() <= player_character.weight_capacity() );
     // Map of items picked up so we can output them all at the end and
     // merge dropping items with the same name.
     PickupMap mapPickup;
     bool problem = false;
     while( !problem && player_character.get_moves() >= 0 && !targets.empty() ) {
         item_location target = std::move( targets.back() );
         int quantity = quantities.back();
         // Whether we pick the item up or not, we're done trying to do so,
         // so remove it from the list.
         targets.pop_back();
         quantities.pop_back();
         if( !target ) {
             debugmsg( "lost target item of ACT_PICKUP" );
             continue;
         }
         problem = !pick_one_up( target, quantity, got_water, got_gas, mapPickup, autopickup,
                                 stash_successful, got_frozen_liquid, info );
         if( info.total_bulk_volume > 200_ml ) {
             // Bulk loading is not allowed beyond a certain volume
             info = Pickup::pick_info();
         }
     }
     if( !mapPickup.empty() ) {
         show_pickup_message( mapPickup );
     }
     if( got_frozen_liquid ) {
         add_msg( m_info, _( "Chunks of frozen liquid cannot be picked up without the correct tools." ) );
     }
     if( got_water ) {
         add_msg( m_info, _( "Spilt liquid cannot be picked back up.  Try mopping it instead." ) );
     }
     if( got_gas ) {
         add_msg( m_info, _( "Spilt gasses cannot be picked up.  They will disappear over time." ) );
     }
     if( weight_is_okay && player_character.weight_carried() > player_character.weight_capacity() ) {
         add_msg( m_bad, _( "You're overburdened!" ) );
     }
     player_character.recoil = MAX_RECOIL;
     return !problem;
 }
References _, add_msg(), PATH_INFO::autopickup(), debugmsg, Creature::get_moves(), get_player_character(), m_bad, m_info, MAX_RECOIL, pick_one_up(), Character::recoil, show_pickup_message(), Pickup::pick_info::total_bulk_volume, Character::weight_capacity(), and Character::weight_carried().
Referenced by pickup_activity_actor::do_turn().
query_thief()
bool Pickup::query_thief ()
Definition at line 103 of file pickup.cpp.
 {
     Character &u = get_player_character();
     const bool force_uc = get_option<bool>( "FORCE_CAPITAL_YN" );
     const auto &allow_key = force_uc ? input_context::disallow_lower_case_or_non_modified_letters
                             : input_context::allow_all_keys;
     std::string answer = query_popup()
                          .preferred_keyboard_mode( keyboard_mode::keycode )
                          .allow_cancel( false )
                          .context( "YES_NO_ALWAYS_NEVER" )
                          .message( "%s", force_uc && !is_keycode_mode_supported()
                                    ? _( "Picking up this item will be considered stealing, continue?  (Case sensitive)" )
                                    : _( "Picking up this item will be considered stealing, continue?" ) )
                          .option( "YES", allow_key ) // yes, steal all items in this location that is selected
                          .option( "NO", allow_key ) // no, pick up only what is free
                          .option( "ALWAYS", allow_key ) // Yes, steal all items and stop asking me this question
                          .option( "NEVER", allow_key ) // no, only grab free item and never ask me again
                          .cursor( 1 ) // default to the second option `NO`
                          .query()
                          .action; // retrieve the input action
     if( answer == "YES" ) {
         u.set_value( "THIEF_MODE", "THIEF_STEAL" );
         u.set_value( "THIEF_MODE_KEEP", "NO" );
         return true;
     } else if( answer == "NO" ) {
         u.set_value( "THIEF_MODE", "THIEF_HONEST" );
         u.set_value( "THIEF_MODE_KEEP", "NO" );
         return false;
     } else if( answer == "ALWAYS" ) {
         u.set_value( "THIEF_MODE", "THIEF_STEAL" );
         u.set_value( "THIEF_MODE_KEEP", "YES" );
         return true;
     } else if( answer == "NEVER" ) {
         u.set_value( "THIEF_MODE", "THIEF_HONEST" );
         u.set_value( "THIEF_MODE_KEEP", "YES" );
         return false;
     } else {
         // error
         debugmsg( "Not a valid option [ %s ]", answer );
     }
     return false;
 }
References _, query_popup::result::action, input_context::allow_all_keys(), query_popup::allow_cancel(), query_popup::context(), query_popup::cursor(), debugmsg, input_context::disallow_lower_case_or_non_modified_letters(), get_player_character(), is_keycode_mode_supported(), keycode, query_popup::message(), query_popup::option(), query_popup::preferred_keyboard_mode(), query_popup::query(), and u.
Referenced by check_stealing(), pick_one_up(), and query_consume_ownership().