Cataclysm DDA: mdeath Namespace Reference
mdeath Namespace Reference
Functions
item_location normal (monster &z)
item_location splatter (monster &z)
void disappear (monster &z)
void broken (monster &z)
Function Documentation
broken()
void mdeath::broken (monster & z)
Definition at line 220 of file mondeath.cpp.
 {
     // Bail out if flagged (simulates eyebot flying away)
     if( z.no_corpse_quiet ) {
         return;
     }
     std::string item_id = z.type->id.str();
     if( item_id.compare( 0, 4, "mon_" ) == 0 ) {
         item_id.erase( 0, 4 );
     }
     // make "broken_manhack", or "broken_eyebot", ...
     item_id.insert( 0, "broken_" );
     item broken_mon( item_id, calendar::turn );
     const int max_hp = std::max( z.get_hp_max(), 1 );
     const float overflow_damage = std::max( -z.get_hp(), 0 );
     const float corpse_damage = 2.5 * overflow_damage / max_hp;
     broken_mon.set_damage( static_cast<int>( std::floor( corpse_damage * itype::damage_scale ) ) );
     map &here = get_map();
     here.add_item_or_charges( z.pos(), broken_mon );
     if( z.type->has_flag( mon_flag_DROPS_AMMO ) ) {
         for( const std::pair<const itype_id, int> &ammo_entry : z.ammo ) {
             if( ammo_entry.second > 0 ) {
                 bool spawned = false;
                 for( const std::pair<const std::string, mtype_special_attack> &attack : z.type->special_attacks ) {
                     if( attack.second->id == "gun" ) {
                         item gun = item( dynamic_cast<const gun_actor *>( attack.second.get() )->gun_type );
                         bool same_ammo = false;
                         if( gun.typeId()->magazine_default.count( item( ammo_entry.first ).ammo_type() ) ) {
                             same_ammo = true;
                         }
                         if( same_ammo && gun.uses_magazine() ) {
                             std::vector<item> mags;
                             int ammo_count = ammo_entry.second;
                             while( ammo_count > 0 ) {
                                 item mag = item( gun.type->magazine_default.find( item( ammo_entry.first ).ammo_type() )->second );
                                 mag.ammo_set( ammo_entry.first,
                                               std::min( ammo_count, mag.type->magazine->capacity ) );
                                 mags.insert( mags.end(), mag );
                                 ammo_count -= mag.type->magazine->capacity;
                             }
                             here.spawn_items( z.pos(), mags );
                             spawned = true;
                             break;
                         }
                     }
                 }
                 if( !spawned ) {
                     here.spawn_item( z.pos(), ammo_entry.first, ammo_entry.second, 1,
                                      calendar::turn );
                 }
             }
         }
     }
     // TODO: make mdeath::splatter work for robots
     if( broken_mon.damage() >= broken_mon.max_damage() ) {
         add_msg_if_player_sees( z.pos(), m_good, _( "The %s is destroyed!" ), z.name() );
     } else {
         add_msg_if_player_sees( z.pos(), m_good, _( "The %s collapses!" ), z.name() );
     }
 }
References _, map::add_item_or_charges(), add_msg_if_player_sees(), monster::ammo, item::ammo_set(), item::ammo_type(), spell_effect::attack(), item::damage(), itype::damage_scale, floor(), monster::get_hp(), monster::get_hp_max(), get_map(), gun, gun_actor::gun_type, mtype::has_flag(), mtype::id, m_good, itype::magazine, max(), item::max_damage(), min(), mon_flag_DROPS_AMMO, monster::name(), monster::no_corpse_quiet, Creature::pos(), item::set_damage(), map::spawn_item(), map::spawn_items(), mtype::special_attacks, string_id< T >::str(), calendar::turn, item::type, and monster::type.
Referenced by monster::die().
disappear()
void mdeath::disappear (monster & z)
Definition at line 213 of file mondeath.cpp.
 {
     if( !z.type->has_flag( mon_flag_SILENT_DISAPPEAR ) ) {
         add_msg_if_player_sees( z.pos(), m_good, _( "The %s disappears." ), z.name() );
     }
 }
References _, add_msg_if_player_sees(), mtype::has_flag(), m_good, mon_flag_SILENT_DISAPPEAR, monster::name(), Creature::pos(), and monster::type.
Referenced by monster::die().
normal()
item_location mdeath::normal (monster & z)
Definition at line 59 of file mondeath.cpp.
 {
     if( z.no_corpse_quiet ) {
         return {};
     }
     if( !z.quiet_death && !z.has_flag( mon_flag_QUIETDEATH ) ) {
         if( z.type->in_species( species_ZOMBIE ) ) {
             sfx::play_variant_sound( "mon_death", "zombie_death", sfx::get_heard_volume( z.pos() ) );
         }
         //Currently it is possible to get multiple messages that a monster died.
         add_msg_if_player_sees( z, m_good, _( "The %s dies!" ), z.name() );
     }
     if( z.death_drops ) {
         const int max_hp = std::max( z.get_hp_max(), 1 );
         const float overflow_damage = std::max( -z.get_hp(), 0 );
         const float corpse_damage = 2.5 * overflow_damage / max_hp;
         const bool pulverized = corpse_damage > 5 && overflow_damage > z.get_hp_max();
         z.bleed(); // leave some blood if we have to
         if( pulverized ) {
             return splatter( z );
         } else {
             const float damage = std::floor( corpse_damage * itype::damage_scale );
             return make_mon_corpse( z, static_cast<int>( damage ) );
         }
     }
     return {};
 }
References _, add_msg_if_player_sees(), Creature::bleed(), itype::damage_scale, monster::death_drops, floor(), sfx::get_heard_volume(), monster::get_hp(), monster::get_hp_max(), monster::has_flag(), mtype::in_species(), m_good, make_mon_corpse(), max(), mon_flag_QUIETDEATH, monster::name(), monster::no_corpse_quiet, sfx::play_variant_sound(), Creature::pos(), monster::quiet_death, species_ZOMBIE, splatter(), and monster::type.
Referenced by monster::die().
splatter()
item_location mdeath::splatter (monster & z)
Definition at line 139 of file mondeath.cpp.
 {
     const bool gibbable = !z.type->has_flag( mon_flag_NOGIB );
     const int max_hp = std::max( z.get_hp_max(), 1 );
     const float overflow_damage = std::max( -z.get_hp(), 0 );
     const float corpse_damage = 2.5 * overflow_damage / max_hp;
     const field_type_id type_blood = z.bloodType();
     const field_type_id type_gib = z.gibType();
     map &here = get_map();
     if( gibbable ) {
         const auto area = here.points_in_radius( z.pos(), 1 );
         int number_of_gibs = std::min( std::floor( corpse_damage ) - 1, 1 + max_hp / 5.0f );
         if( z.type->size >= creature_size::medium ) {
             number_of_gibs += rng( 1, 6 );
             sfx::play_variant_sound( "mon_death", "zombie_gibbed", sfx::get_heard_volume( z.pos() ) );
         }
         for( int i = 0; i < number_of_gibs; ++i ) {
             here.add_splatter( type_gib, random_entry( area ), rng( 1, i + 1 ) );
             here.add_splatter( type_blood, random_entry( area ) );
         }
     }
     // 1% of the weight of the monster is the base, with overflow damage as a multiplier
     int gibbed_weight = rng( 0, std::round( to_gram( z.get_weight() ) / 100.0 *
                                             ( overflow_damage / max_hp + 1 ) ) );
     const int z_weight = to_gram( z.get_weight() );
     // limit gibbing to 15%
     gibbed_weight = std::min( gibbed_weight, z_weight * 15 / 100 );
     if( gibbable ) {
         float overflow_ratio = overflow_damage / max_hp + 1.0f;
         int gib_distance = std::round( rng( 2, 4 ) );
         for( const harvest_entry &entry : *z.type->harvest ) {
             // only flesh and bones survive.
             if( entry.type == harvest_drop_flesh || entry.type == harvest_drop_bone ) {
                 // the larger the overflow damage, the less you get
                 const int chunk_amt =
                     entry.mass_ratio / overflow_ratio / 10 *
                     z.get_weight() / item::find_type( itype_id( entry.drop ) )->weight;
                 scatter_chunks( itype_id( entry.drop ), chunk_amt, z, gib_distance,
                                 chunk_amt / ( gib_distance - 1 ) );
                 gibbed_weight -= entry.mass_ratio / overflow_ratio / 20 * to_gram( z.get_weight() );
             }
         }
         if( gibbed_weight > 0 ) {
             const itype_id &leftover_id = z.type->id->harvest->leftovers;
             const int chunk_amount =
                 gibbed_weight / to_gram( item::find_type( leftover_id )->weight );
             scatter_chunks( leftover_id, chunk_amount, z, gib_distance,
                             chunk_amount / ( gib_distance + 1 ) );
         }
         // add corpse with gib flag
         item corpse = item::make_corpse( z.type->id, calendar::turn, z.unique_name, z.get_upgrade_time() );
         if( corpse.is_null() ) {
             return {};
         }
         // Set corpse to damage that aligns with being pulped
         corpse.set_damage( 4000 );
         corpse.set_flag( STATIC( flag_id( "GIBBED" ) ) );
         if( z.has_effect( effect_no_ammo ) ) {
             corpse.set_var( "no_ammo", "no_ammo" );
         }
         if( z.has_effect( effect_critter_underfed ) ) {
             corpse.set_flag( STATIC( flag_id( "UNDERFED" ) ) );
         }
         return here.add_item_ret_loc( z.pos(), corpse );
     }
     return {};
 }
References map::add_item_ret_loc(), map::add_splatter(), monster::bloodType(), corpse, harvest_entry::drop, effect_critter_underfed, effect_no_ammo, item::find_type(), floor(), sfx::get_heard_volume(), monster::get_hp(), monster::get_hp_max(), get_map(), monster::get_upgrade_time(), monster::get_weight(), monster::gibType(), mtype::harvest, harvest_drop_bone, harvest_drop_flesh, Creature::has_effect(), mtype::has_flag(), mtype::id, harvest_list::leftovers, item::make_corpse(), harvest_entry::mass_ratio, max(), medium, min(), mon_flag_NOGIB, sfx::play_variant_sound(), map::points_in_radius(), Creature::pos(), random_entry(), rng(), round(), scatter_chunks(), mtype::size, STATIC, units::to_gram(), calendar::turn, harvest_entry::type, monster::type, monster::unique_name, and itype::weight.
Referenced by monster::die(), and normal().