Cataclysm DDA: anonymous_namespace{savegame_json.cpp} Namespace Reference
anonymous_namespace{savegame_json.cpp} Namespace Reference
Functions
void _write_rle_terrain (JsonOut &jsout, const std::string_view ter, int num)
Function Documentation
_write_rle_terrain()
void anonymous_namespace{savegame_json.cpp}::_write_rle_terrain (JsonOut & jsout, const std::string_view ter, int num)
Definition at line 4611 of file savegame_json.cpp.
 {
     jsout.start_array();
     jsout.write( ter );
     jsout.write( num );
     jsout.end_array();
 }
References JsonOut::end_array(), JsonOut::start_array(), and JsonOut::write().
Referenced by submap::store().