Cataclysm DDA: anonymous_namespace{diary_ui.cpp} Namespace Reference
anonymous_namespace{diary_ui.cpp} Namespace Reference
Functions
void print_list_scrollable (catacurses::window *win, const std::vector< std::string > &list, int *selection, int entries_per_page, int xoffset, int width, bool active, bool border, const report_color_error color_error)
print list scrollable, printed std::vector<std::string> as list with scrollbar
void print_list_scrollable (catacurses::window *win, const std::vector< std::string > &list, int *selection, bool active, bool border, const report_color_error color_error)
std::vector< std::string > text_to_list_scrollable (catacurses::window &win, const std::string &text, const bool border)
void print_list_scrollable (catacurses::window *win, const std::string &text, int *selection, bool active, bool border, const report_color_error color_error)
template<typename ... Ts>
void mvwprintwa (const catacurses::window &win, point p, Ts... args)
void draw_diary_border (catacurses::window *win)
Function Documentation
draw_diary_border()
void anonymous_namespace{diary_ui.cpp}::draw_diary_border (catacurses::window * win)
Definition at line 105 of file diary_ui.cpp.
 {
     const point max( getmaxx( *win ) - 1, getmaxy( *win ) - 1 );
     const point mid = max / 2;
     // left, right vertical lines
     for( int i = 0; i < 4; i++ ) {
         mvwvline( *win, point( 0     + i, 4 ), '|', max.y - 4 - 4 + 1 );
         mvwvline( *win, point( max.x - i, 4 ), '|', max.y - 4 - 4 + 1 );
     }
     // middle vertical line
     mvwvline( *win,     point( mid.x,     4 ), '|', max.y - 4 - 4 + 1 );
     // top horizontal line
     mvwhline( *win,     point( 4,         0 ), '_', max.x - 4 - 4 + 1 );
     // bottom horizontal lines
     mvwhline( *win,     point( 4, max.y - 2 ), '_', max.x - 4 - 4 + 1 );
     mvwhline( *win,     point( 4, max.y - 1 ), '=', max.x - 4 - 4 + 1 );
     mvwhline( *win,     point( 4, max.y - 0 ), '-', max.x - 4 - 4 + 1 );
     wattron( *win, BORDER_COLOR );
     //top left corner
     mvwprintwa( *win, point_zero,
                 "    ",
                 ".-/|",
                 "||||",
                 "||||" );
     // bottom left corner
     mvwprintwa( *win, point( 0, max.y - 3 ),
                 "||||",
                 "||||",
                 "||/=",
                 "`'--" );
     // top right corner
     mvwprintwa( *win, point( max.x - 3, 0 ),
                 "    ",
                 "|\\-.",
                 "||||",
                 "||||" );
     // bottom right corner
     mvwprintwa( *win, max + point( -3, -3 ),
                 "||||",
                 "||||",
                 "=\\||",
                 "--''" );
     // top middle
     mvwprintwa( *win, point( mid.x - 1, 0 ),
                 "   ",
                 "\\ /",
                 " | ",
                 " | " );
     // bottom middle
     mvwprintwa( *win, point( mid.x - 1, max.y - 3 ),
                 " | ",
                 " | ",
                 "\\|/",
                 "___" );
     wattroff( *win, BORDER_COLOR );
 }
References BORDER_COLOR, catacurses::getmaxx(), catacurses::getmaxy(), max(), catacurses::mvwhline(), mvwprintwa(), catacurses::mvwvline(), point_zero, catacurses::wattroff(), catacurses::wattron(), and point::x.
Referenced by diary::show_diary_ui().
mvwprintwa()
template<typename ... Ts> void anonymous_namespace{diary_ui.cpp}::mvwprintwa (const catacurses::window & win, point p, Ts... args)
Definition at line 95 of file diary_ui.cpp.
 {
     for( auto string : {
              args...
          } ) {
         mvwprintw( win, p, string );
         p += point_south;
     }
 }
References catacurses::mvwprintw(), and point_south.
Referenced by draw_diary_border().
print_list_scrollable() [1/3]
void anonymous_namespace{diary_ui.cpp}::print_list_scrollable (catacurses::window * win, const std::string & text, int * selection, bool active, bool border, const report_color_error color_error)
Definition at line 85 of file diary_ui.cpp.
 {
     std::vector<std::string> list = text_to_list_scrollable( *win, text, border );
     print_list_scrollable( win, list, selection, active, border, color_error );
 }
References text_to_list_scrollable().
Referenced by print_list_scrollable(), and diary::show_diary_ui().
print_list_scrollable() [2/3]
void anonymous_namespace{diary_ui.cpp}::print_list_scrollable (catacurses::window * win, const std::vector< std::string > & list, int * selection, bool active, bool border, const report_color_error color_error)
Definition at line 67 of file diary_ui.cpp.
 {
     print_list_scrollable( win, list, selection, getmaxy( *win ), 0, getmaxx( *win ),
                            active, border,
                            color_error );
 }
References catacurses::getmaxx(), catacurses::getmaxy(), and print_list_scrollable().
print_list_scrollable() [3/3]
void anonymous_namespace{diary_ui.cpp}::print_list_scrollable (catacurses::window * win, const std::vector< std::string > & list, int * selection, int entries_per_page, int xoffset, int width, bool active, bool border, const report_color_error color_error)
print list scrollable, printed std::vector<std::string> as list with scrollbar
Definition at line 26 of file diary_ui.cpp.
 {
     if( *selection < 0 && !list.empty() ) {
         *selection = static_cast<int>( list.size() ) - 1;
     } else if( *selection >= static_cast<int>( list.size() ) ) {
         *selection = 0;
     }
     const int borderspace = border ? 1 : 0;
     entries_per_page = entries_per_page - borderspace * 2;
     const int top_of_page = entries_per_page * ( *selection / entries_per_page );
     const int bottom_of_page = std::min<int>( top_of_page + entries_per_page, list.size() );
     const int line_width = width - 1 - borderspace;
     for( int i = top_of_page; i < bottom_of_page; i++ ) {
         const nc_color col = c_white;
         const int y = i - top_of_page;
         const bool highlight = *selection == i && active;
         const nc_color line_color = highlight ? hilite( col ) : col;
         std::string line_str = list[i];
         if( highlight ) {
             line_str = left_justify( remove_color_tags( line_str ), line_width );
         }
         trim_and_print( *win, point( xoffset + 1, y + borderspace ), line_width,
                         line_color, line_str, color_error );
     }
     if( border ) {
         draw_border( *win );
     }
     if( active && entries_per_page < static_cast<int>( list.size() ) ) {
         draw_scrollbar( *win, *selection, entries_per_page, list.size(), point( xoffset,
                         0 + borderspace ) );
     }
 }
References c_white, draw_border(), draw_scrollbar(), hilite(), left_justify(), remove_color_tags(), and trim_and_print().
text_to_list_scrollable()
std::vector<std::string> anonymous_namespace{diary_ui.cpp}::text_to_list_scrollable (catacurses::window & win, const std::string & text, const bool border)
Definition at line 77 of file diary_ui.cpp.
 {
     const int width = getmaxx( win );
     const int borderspace = border ? 1 : 0;
     // -1 on the left for scroll bar and another -1 on the right reserved for cursor
     return foldstring( text, width - 2 - borderspace * 2 );
 }
References foldstring(), and catacurses::getmaxx().
Referenced by print_list_scrollable(), and diary::show_diary_ui().