Cataclysm DDA: sounds Namespace Reference
sounds Namespace Reference
Enumerations
enum class sound_t : int {
background = 0 , weather , sensory , music ,
movement , speech , electronic_speech , activity ,
destructive_activity , alarm , combat , alert ,
order , LAST
}
Functions
void sound (const tripoint &p, int vol, sound_t category, const std::string &description, bool ambient=false, const std::string &id="", const std::string &variant="default")
Sound at (p) of intensity (vol)
void sound (const tripoint_bub_ms &p, int vol, sound_t category, const std::string &description, bool ambient=false, const std::string &id="", const std::string &variant="default")
void sound (const tripoint &p, int vol, sound_t category, const translation &description, bool ambient=false, const std::string &id="", const std::string &variant="default")
void sound (const tripoint_bub_ms &p, int vol, sound_t category, const translation &description, bool ambient=false, const std::string &id="", const std::string &variant="default")
void ambient_sound (const tripoint &p, int vol, sound_t category, const std::string &description)
Functions identical to sound(..., true).
void add_footstep (const tripoint &p, int volume, int distance, monster *source, const std::string &footstep)
Creates a list of coordinates at which to draw footsteps.
void reset_sounds ()
void reset_markers ()
void process_sounds ()
void process_sound_markers (Character *you)
std::vector< tripoint > get_footstep_markers ()
std::pair< std::vector< tripoint >, std::vector< tripoint > > get_monster_sounds ()
std::string sound_at (const tripoint &location)
Variables
bool sound_enabled
Tells us if sound has been enabled in options.
Enumeration Type Documentation
sound_t
enum sounds::sound_t : int strong
Enumerator
background
weather
sensory
music
movement
speech
electronic_speech
activity
destructive_activity
alarm
combat
alert
order
LAST
Definition at line 23 of file sounds.h.
                    : int {
     background = 0,
     weather,
     sensory, // Sonar etc. Ensures this sound will usually get a visual marker so the player can see it.
     music,
     movement,
     speech,
     electronic_speech, // Any electronic sound that's not music/alarm: Robot speech, radio, etc.
     activity,
     destructive_activity,
     alarm,
     combat, // any violent sounding activity
     alert, // louder than speech to get attention
     order,  // loudest to get attention
     LAST // must always be last
 };
Function Documentation
add_footstep()
void sounds::add_footstep (const tripoint & p, int volume, int distance, monster * source, const std::string & footstep)
Creates a list of coordinates at which to draw footsteps.
Definition at line 358 of file sounds.cpp.
 {
     const season_type seas = season_of_year( calendar::turn );
     const std::string seas_str = season_str( seas );
     sounds_since_last_turn.emplace_back( p, sound_event { volume,
                                          sound_t::movement, footstep, false, true, "", "", seas_str} );
 }
References season_of_year(), season_str(), sounds_since_last_turn, and calendar::turn.
Referenced by monster::footsteps().
ambient_sound()
void sounds::ambient_sound (const tripoint & p, int vol, sound_t category, const std::string & description)
Functions identical to sound(..., true).
Definition at line 312 of file sounds.cpp.
 {
     sound( p, vol, category, description, true );
 }
References anonymous_namespace{item_tname.cpp}::category().
Referenced by reload_activity_actor::make_reload_sound(), iuse::play_music(), and iuse::radio_tick().
get_footstep_markers()
std::vector< tripoint > sounds::get_footstep_markers ()
Definition at line 797 of file sounds.cpp.
 {
     // Optimization, make this static and clear it in reset_markers?
     std::vector<tripoint> footsteps;
     footsteps.reserve( sound_markers.size() );
     for( const auto &mark : sound_markers ) {
         footsteps.push_back( mark.first );
     }
     return footsteps;
 }
References sound_markers.
Referenced by draw_footsteps().
get_monster_sounds()
std::pair< std::vector< tripoint >, std::vector< tripoint > > sounds::get_monster_sounds ()
Definition at line 808 of file sounds.cpp.
 {
     auto sound_clusters = cluster_sounds( recent_sounds );
     std::vector<tripoint> sound_locations;
     sound_locations.reserve( recent_sounds.size() );
     for( const auto &sound : recent_sounds ) {
         sound_locations.push_back( sound.first );
     }
     std::vector<tripoint> cluster_centroids;
     cluster_centroids.reserve( sound_clusters.size() );
     for( const centroid &sound : sound_clusters ) {
         cluster_centroids.emplace_back( static_cast<int>( sound.x ), static_cast<int>( sound.y ),
                                         static_cast<int>( sound.z ) );
     }
     return { sound_locations, cluster_centroids };
 }
References cluster_sounds(), and recent_sounds.
Referenced by debug_menu::show_sound().
process_sound_markers()
void sounds::process_sound_markers (Character * you)
Definition at line 569 of file sounds.cpp.
 {
     bool is_deaf = you->is_deaf();
     const float volume_multiplier = you->hearing_ability();
     const int weather_vol = get_weather().weather_id->sound_attn;
     // NOLINTNEXTLINE(modernize-loop-convert)
     for( std::size_t i = 0; i < sounds_since_last_turn.size(); i++ ) {
         // copy values instead of making references here to fix use-after-free error
         // sounds_since_last_turn may be inserted with new elements inside the loop
         // so the references may become invalid after the vector enlarged its internal buffer
         const tripoint pos = sounds_since_last_turn[i].first;
         const sound_event sound = sounds_since_last_turn[i].second;
         const int distance_to_sound = sound_distance( you->pos(), pos );
         const int raw_volume = sound.volume;
         // The felt volume of a sound is not affected by negative multipliers, such as already
         // deafened players or players with sub-par hearing to begin with.
         int felt_volume = static_cast<int>( raw_volume * std::min( 1.0f,
                                             volume_multiplier ) ) - distance_to_sound;
         if( you->has_flag( json_flag_HEARING_PROTECTION ) ) {
             felt_volume /= 2;
         }
         // Deafening is based on the felt volume, as a player may be too deaf to
         // hear the deafening sound but still suffer additional hearing loss.
         const bool is_sound_deafening = rng( felt_volume / 2, felt_volume ) >= 150;
         // Deaf players hear no sound, but still are at risk of additional hearing loss.
         if( is_deaf ) {
             if( is_sound_deafening && !you->is_immune_effect( effect_deaf ) ) {
                 you->add_effect( effect_deaf, std::min( 4_minutes,
                                                         time_duration::from_turns( felt_volume - 130 ) / 8 ) );
                 if( !you->has_flag( json_flag_PAIN_IMMUNE ) ) {
                     you->add_msg_if_player( m_bad, _( "Your eardrums suddenly ache!" ) );
                     if( you->get_pain() < 10 ) {
                         you->mod_pain( rng( 0, 2 ) );
                     }
                 }
             }
             continue;
         }
         if( is_sound_deafening && !you->is_immune_effect( effect_deaf ) ) {
             const time_duration deafness_duration = time_duration::from_turns( felt_volume - 130 ) / 4;
             you->add_effect( effect_deaf, deafness_duration );
             if( you->is_deaf() && !is_deaf ) {
                 is_deaf = true;
                 continue;
             }
         }
         // The heard volume of a sound is the player heard volume, regardless of true volume level.
         const int heard_volume = static_cast<int>( ( raw_volume - weather_vol ) *
                                  volume_multiplier ) - distance_to_sound;
         if( heard_volume <= 0 && pos != you->pos() ) {
             continue;
         }
         // Player volume meter includes all sounds from their tile and adjacent tiles
         if( distance_to_sound <= 1 ) {
             you->volume = std::max( you->volume, heard_volume );
         }
         // Noises from vehicle player is in.
         if( you->controlling_vehicle ) {
             vehicle *veh = veh_pointer_or_null( get_map().veh_at( you->pos() ) );
             const int noise = veh ? static_cast<int>( veh->vehicle_noise ) : 0;
             you->volume = std::max( you->volume, noise );
         }
         // Secure the flag before wake_up() clears the effect
         bool slept_through = you->has_effect( effect_slept_through_alarm );
         // See if we need to wake someone up
         if( you->has_effect( effect_sleep ) ) {
             if( ( ( !( you->has_trait( trait_HEAVYSLEEPER ) ||
                        you->has_trait( trait_HEAVYSLEEPER2 ) ) && dice( 2, 15 ) < heard_volume ) ||
                   ( you->has_trait( trait_HEAVYSLEEPER ) && dice( 3, 15 ) < heard_volume ) ||
                   ( you->has_trait( trait_HEAVYSLEEPER2 ) && dice( 6, 15 ) < heard_volume ) ) &&
                 !you->has_effect( effect_narcosis ) &&
                 !you->has_bionic( bio_sleep_shutdown ) ) {
                 //Not kidding about sleep-through-firefight
                 you->wake_up();
                 you->add_msg_if_player( m_warning, _( "Something is making noise." ) );
             } else {
                 continue;
             }
         }
         const std::string &description = sound.description.empty() ? _( "a noise" ) : sound.description;
         if( you->is_npc() ) {
             if( !sound.ambient ) {
                 npc *guy = dynamic_cast<npc *>( you );
                 guy->handle_sound( sound.category, description, heard_volume, pos );
             }
             continue;
         }
         if( sound.category == sound_t::music ) {
             music::activate_music_id( music::music_id::sound );
         }
         // don't print our own noise or things without descriptions
         if( !sound.ambient && ( pos != you->pos() ) && !get_map().pl_sees( pos, distance_to_sound ) ) {
             if( uistate.distraction_noise &&
                 !you->activity.is_distraction_ignored( distraction_type::noise ) &&
                 !get_safemode().is_sound_safe( sound.description, distance_to_sound, you->controlling_vehicle ) ) {
                 const std::string query = string_format( _( "Heard %s!" ),
                                           trim_trailing_punctuations( description ) );
                 g->cancel_activity_or_ignore_query( distraction_type::noise, query );
             }
         }
         // skip some sounds to avoid message spam
         const bool from_player = pos == you->pos() || ( sound.category == sound_t::movement &&
                                  distance_to_sound <= 1 );
         if( describe_sound( sound.category, from_player ) ) {
             game_message_type severity = m_info;
             if( sound.category == sound_t::combat || sound.category == sound_t::alarm ) {
                 severity = m_warning;
             }
             // if we can see it, don't print a direction
             if( pos == you->pos() ) {
                 add_msg( severity, _( "From your position you hear %1$s" ), description );
             } else if( you->sees( pos ) ) {
                 add_msg( severity, _( "You hear %1$s" ), description );
             } else {
                 std::string direction = direction_name( direction_from( you->pos(), pos ) );
                 add_msg( severity, _( "From the %1$s you hear %2$s" ), direction, description );
             }
         }
         if( !you->has_effect( effect_sleep ) && you->has_effect( effect_alarm_clock ) &&
             !you->has_flag( STATIC( json_character_flag( "ALARMCLOCK" ) ) ) ) {
             // if we don't have effect_sleep but we're in_sleep_state, either
             // we were trying to fall asleep for so long our alarm is now going
             // off or something disturbed us while trying to sleep
             const bool trying_to_sleep = you->in_sleep_state();
             if( you->get_effect( effect_alarm_clock ).get_duration() == 1_turns ) {
                 if( slept_through ) {
                     add_msg( _( "Your alarm clock finally wakes you up." ) );
                 } else if( !trying_to_sleep ) {
                     add_msg( _( "Your alarm clock wakes you up." ) );
                 } else {
                     add_msg( _( "Your alarm clock goes off and you haven't slept a wink." ) );
                     you->activity.set_to_null();
                 }
                 add_msg( _( "You turn off your alarm-clock." ) );
                 you->get_effect( effect_alarm_clock ).set_duration( 0_turns );
             }
         }
         const std::string &sfx_id = sound.id;
         const std::string &sfx_variant = sound.variant;
         const std::string &sfx_season = sound.season;
         const bool indoors = !is_creature_outside( get_player_character() );
         const bool night = is_night( calendar::turn );
         if( !sfx_id.empty() ) {
             sfx::play_variant_sound( sfx_id, sfx_variant, sfx_season, indoors, night,
                                      sfx::get_heard_volume( pos ) );
         }
         // Place footstep markers.
         if( pos == you->pos() || ( you->sees( pos ) && ( sound.category != sound_t::sensory ) ) ) {
             // If we are or can see the source, don't draw a marker, except for sonar etc
             continue;
         }
         int err_offset;
         if( ( heard_volume + distance_to_sound ) / distance_to_sound < 2 ) {
             err_offset = rng( 0, 3 );
         } else if( ( heard_volume + distance_to_sound ) / distance_to_sound < 3 ) {
             err_offset = rng( 0, 2 );
         } else {
             err_offset = rng( 0, 1 );
         }
         // Echolocation has to be fairly precise or it's worse than useless.
         // However, it is never perfect.
         if( sound.category == sound_t::sensory ) {
             if( ( heard_volume + distance_to_sound ) / distance_to_sound < 2 ) {
                 err_offset = rng( 0, 3 );
             } else if( ( heard_volume + distance_to_sound ) / distance_to_sound < 3 ) {
                 err_offset = rng( 0, 2 );
             } else {
                 if( one_in( 3 ) ) {
                     err_offset = rng( 0, 1 );
                 } else {
                     err_offset = 0;
                 }
             }
         }
         // If Z-coordinate is different, draw even when you can see the source
         const bool diff_z = pos.z != you->posz();
         // Enumerate the valid points the player *cannot* see.
         // Unless the source is on a different z-level, then any point is fine
         // Also show sensory sounds like SONAR even if we can see the point.
         std::vector<tripoint> unseen_points;
         for( const tripoint &newp : get_map().points_in_radius( pos, err_offset ) ) {
             if( diff_z || sound.category == sound_t::sensory || !you->sees( newp ) ) {
                 unseen_points.emplace_back( newp );
             }
         }
         // Then place the sound marker in a random one.
         if( !unseen_points.empty() ) {
             sound_markers.emplace( random_entry( unseen_points ), sound );
         }
     }
     if( you->is_avatar() ) {
         sounds_since_last_turn.clear();
     }
 }
References _, music::activate_music_id(), Character::activity, Creature::add_effect(), add_msg(), Character::add_msg_if_player(), bio_sleep_shutdown, Character::controlling_vehicle, describe_sound(), dice(), direction_from(), direction_name(), uistatedata::distraction_noise, effect_alarm_clock, effect_deaf, effect_narcosis, effect_sleep, effect_slept_through_alarm, time_duration::from_turns(), g, effect::get_duration(), Creature::get_effect(), sfx::get_heard_volume(), get_map(), Creature::get_pain(), get_player_character(), get_safemode(), get_weather(), npc::handle_sound(), Character::has_bionic(), Creature::has_effect(), Character::has_flag(), Character::has_trait(), Character::hearing_ability(), Character::in_sleep_state(), Creature::is_avatar(), is_creature_outside(), Character::is_deaf(), player_activity::is_distraction_ignored(), Character::is_immune_effect(), is_night(), Character::is_npc(), json_flag_HEARING_PROTECTION, json_flag_PAIN_IMMUNE, m_bad, m_info, m_warning, max(), min(), Character::mod_pain(), noise, one_in(), pl_sees(), sfx::play_variant_sound(), points_in_radius(), Creature::pos(), math_opers::pos(), Creature::posz(), random_entry(), rng(), Character::sees(), effect::set_duration(), player_activity::set_to_null(), weather_type::sound_attn, sound_distance(), sound_markers, sounds_since_last_turn, STATIC, string_format(), trait_HEAVYSLEEPER, trait_HEAVYSLEEPER2, trim_trailing_punctuations(), calendar::turn, uistate, veh_pointer_or_null(), vehicle::vehicle_noise, Character::volume, Character::wake_up(), and weather_manager::weather_id.
Referenced by game::examine().
process_sounds()
void sounds::process_sounds ()
Definition at line 472 of file sounds.cpp.
 {
     std::vector<centroid> sound_clusters = cluster_sounds( recent_sounds );
     const int weather_vol = get_weather().weather_id->sound_attn;
     for( const centroid &this_centroid : sound_clusters ) {
         // Since monsters don't go deaf ATM we can just use the weather modified volume
         // If they later get physical effects from loud noises we'll have to change this
         // to use the unmodified volume for those effects.
         const int vol = this_centroid.volume - weather_vol;
         const tripoint source = tripoint( this_centroid.x, this_centroid.y, this_centroid.z );
         // --- Monster sound handling here ---
         // Alert all hordes
         int sig_power = get_signal_for_hordes( this_centroid );
         if( sig_power > 0 ) {
             const point abs_ms = get_map().getabs( source.xy() );
             // TODO: fix point types
             const point_abs_sm abs_sm( ms_to_sm_copy( abs_ms ) );
             const tripoint_abs_sm target( abs_sm, source.z );
             overmap_buffer.signal_hordes( target, sig_power );
         }
         // Alert all monsters (that can hear) to the sound.
         for( monster &critter : g->all_monsters() ) {
             // TODO: Generalize this to Creature::hear_sound
             const int dist = sound_distance( source, critter.pos() );
             if( vol * 2 > dist ) {
                 // Exclude monsters that certainly won't hear the sound
                 critter.hear_sound( source, vol, dist, this_centroid.provocative );
             }
         }
         // Trigger sound-triggered traps and ensure they are still valid
         for( const trap *trapType : trap::get_sound_triggered_traps() ) {
             for( const tripoint &tp : get_map().trap_locations( trapType->id ) ) {
                 const int dist = sound_distance( source, tp );
                 const trap &tr = get_map().tr_at( tp );
                 // Exclude traps that certainly won't hear the sound
                 if( vol * 2 > dist ) {
                     if( tr.triggered_by_sound( vol, dist ) ) {
                         tr.trigger( tp );
                     }
                 }
             }
         }
     }
     recent_sounds.clear();
 }
References cluster_sounds(), g, get_map(), get_signal_for_hordes(), trap::get_sound_triggered_traps(), get_weather(), map::getabs(), ms_to_sm_copy(), overmap_buffer, recent_sounds, overmapbuffer::signal_hordes(), weather_type::sound_attn, sound_distance(), map::tr_at(), trap::trigger(), trap::triggered_by_sound(), weather_manager::weather_id, tripoint::xy(), and tripoint::z.
reset_markers()
void sounds::reset_markers ()
Definition at line 792 of file sounds.cpp.
 {
     sound_markers.clear();
 }
References sound_markers.
Referenced by autodrive_activity_actor::do_turn().
reset_sounds()
void sounds::reset_sounds ()
Definition at line 785 of file sounds.cpp.
 {
     recent_sounds.clear();
     sounds_since_last_turn.clear();
     sound_markers.clear();
 }
References recent_sounds, sound_markers, and sounds_since_last_turn.
Referenced by game::setup().
sound() [1/4]
void sounds::sound (const tripoint & p, int vol, sound_t category, const std::string & description, bool ambient = false, const std::string & id = "", const std::string & variant = "default")
Sound at (p) of intensity (vol)
If the description parameter is a non-empty string, then a string message about the sound is generated for the player.
Parameters
p position of sound.
vol Volume of sound.
category general type of sound for faster parsing
description Description of the sound for the player
ambient Sound does not interrupt player activity if this is true
id Id of sound effect
variant Variant of sound effect given in id
Returns
true if the player could hear the sound.
Definition at line 318 of file sounds.cpp.
 {
     if( vol < 0 ) {
         // Bail out if no volume.
         debugmsg( "negative sound volume %d", vol );
         return;
     }
     // Description is not an optional parameter
     if( description.empty() ) {
         debugmsg( "Sound at %d:%d has no description!", p.x, p.y );
     }
     const season_type seas = season_of_year( calendar::turn );
     const std::string seas_str = season_str( seas );
     recent_sounds.emplace_back( p, monster_sound_event{ vol, is_provocative( category ) } );
     sounds_since_last_turn.emplace_back( p,
                                          sound_event { vol, category, description, ambient,
                                                  false, id, variant, seas_str } );
 }
References anonymous_namespace{item_tname.cpp}::category(), debugmsg, int_id< T >::id(), is_provocative(), recent_sounds, season_of_year(), season_str(), sounds_since_last_turn, calendar::turn, tripoint::x, and tripoint::y.
Referenced by explosion_handler::_make_explosion(), mattack::acid(), computer_session::action_irradiator(), computer_session::action_release(), computer_session::action_release_bionics(), computer_session::action_toll(), Character::activate_bionic(), timed_event::actualize(), vehicle::alarm(), vehicle::backfire(), map::bash_items(), map::bash_ter_furn(), map::bash_vehicle(), trapfunc::beartrap(), vehicle::beeper_sound(), iuse::bell(), Character::blossoms(), mattack::blow_whistle(), trapfunc::bubble(), trapfunc::caltrops_glass(), iuse::camera(), iexamine::cardreader_foodplace(), mattack::check_money_left(), chop_single_do_turn(), map::close_door(), mattack::copbot(), Character::cough(), vehicle::crash_terrain_around(), trapfunc::dissector(), hacksaw_activity_actor::do_turn(), oxytorch_activity_actor::do_turn(), workout_activity_actor::do_turn(), construct::do_turn_shovel(), mattack::doot(), vehicle::drive_to_local_target(), drop_or_embed_projectile(), mattack::dsa_drone_scan(), Character::echo_pulse(), eff_fun_hallu(), iuse::ehandcuffs_tick(), iuse::emf_passive_on(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), computer_session::failure_alarm(), hacking_activity_actor::finish(), boltcutting_activity_actor::finish(), lockpick_activity_actor::finish(), iuse::firecracker_pack_act(), explosion_handler::flashbang(), mattack::flesh_golem(), mattack::flesh_tendril(), iuse::foodperson_voice(), mattack::frag(), suffer::from_artifact_resonance(), suffer::from_other_mutations(), mattack::fungus(), mattack::fungus_big_blossom(), mattack::fungus_corporate(), mattack::fungus_haze(), iuse::geiger_active(), debug_menu::gen_sound(), mattack::generator(), trapfunc::glass(), game::grabbed_furn_move(), game::grabbed_veh_move(), iuse::granade_act(), gun_repair(), prying_activity_actor::handle_prying(), vehicle::handle_trap(), Character::hardcoded_effects(), vehicle::honk_horn(), mattack::howl(), trapfunc::hum(), activity_handlers::jackhammer_do_turn(), doors::lock_door(), Creature::longpull(), Character::make_clatter_sound(), Character::make_footstep_noise(), make_gun_sound_effect(), spell::make_sound(), Character::melee_attack_abstract(), Character::melee_special_effects(), map::move_vehicle(), iuse::multicooker_tick(), iexamine::nanofab(), vehicle::noise_and_smoke(), iuse::noise_emitter_on(), mattack::nurse_assist(), mattack::nurse_check_up(), mattack::nurse_operate(), monster::nursebot_operate(), map::open_door(), vehicle::operate_planter(), vehicle::operate_reaper(), vehicle::operate_scoop(), activity_handlers::operation_finish(), mattack::parrot(), parrot_common(), vehicle::part_collision(), iexamine::pay_gas(), iexamine::pedestal_wyrm(), Character::perform_technique(), mattack::photograph(), activity_handlers::pickaxe_do_turn(), vehicle::play_chimes(), monster::process_one_effect(), monster::process_turn(), mattack::rattle(), rcdrive(), mdefense::return_fire(), mattack::rifle(), mattack::riotbot(), npc::say(), sendRadioSignal(), mattack::shocking_reveal(), explosion_handler::shockwave(), map::shoot(), gun_actor::shoot(), trapfunc::shotgun(), Character::shout(), mattack::shriek(), mattack::shriek_alert(), smash(), trapfunc::snake(), trapfunc::snare_heavy(), trapfunc::snare_light(), sound(), trapfunc::sound_detect(), mattack::speaker(), activity_handlers::spellcasting_finish(), Character::spores(), vehicle::start_engine(), vehicle::stop_engines(), iuse::talking_doll(), mattack::tankgun(), trapfunc::telepad(), vehicle::transform_terrain(), mattack::triffid_heartbeat(), gun_actor::try_target(), doors::unlock_door(), sound_iuse::use(), fireweapon_off_actor::use(), manualnoise_actor::use(), and musical_instrument_actor::use().
sound() [2/4]
void sounds::sound (const tripoint & p, int vol, sound_t category, const translation & description, bool ambient = false, const std::string & id = "", const std::string & variant = "default")
Definition at line 345 of file sounds.cpp.
 {
     sounds::sound( p, vol, category, description.translated(), ambient, id, variant );
 }
References anonymous_namespace{item_tname.cpp}::category(), sound(), and translation::translated().
sound() [3/4]
void sounds::sound (const tripoint_bub_ms & p, int vol, sound_t category, const std::string & description, bool ambient = false, const std::string & id = "", const std::string & variant = "default")
Definition at line 338 of file sounds.cpp.
 {
     sounds::sound( p.raw(), vol, category, description, ambient, id, variant );
 }
References anonymous_namespace{item_tname.cpp}::category(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), and sound().
sound() [4/4]
void sounds::sound (const tripoint_bub_ms & p, int vol, sound_t category, const translation & description, bool ambient = false, const std::string & id = "", const std::string & variant = "default")
Definition at line 351 of file sounds.cpp.
 {
     sounds::sound( p.raw(), vol, category, description, ambient, id, variant );
 }
References anonymous_namespace{item_tname.cpp}::category(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), and sound().
sound_at()
std::string sounds::sound_at (const tripoint & location)
Definition at line 825 of file sounds.cpp.
 {
     auto this_sound = sound_markers.find( location );
     if( this_sound == sound_markers.end() ) {
         return std::string();
     }
     if( !this_sound->second.description.empty() ) {
         return this_sound->second.description;
     }
     return _( "a sound" );
 }
References _, location, and sound_markers.
Referenced by game::print_all_tile_info().
Variable Documentation
sound_enabled
bool sounds::sound_enabled extern
Tells us if sound has been enabled in options.
Referenced by options_manager::load().