Cataclysm DDA: target_handler Namespace Reference
target_handler Namespace Reference
Typedefs
using trajectory = std::vector< tripoint >
Functions
trajectory mode_select_only (avatar &you, int range)
Generic target select without fire something.
trajectory mode_fire (avatar &you, aim_activity_actor &activity)
Firing ranged weapon.
trajectory mode_throw (avatar &you, item &relevant, bool blind_throwing)
Throwing item.
trajectory mode_reach (avatar &you, item_location weapon)
Reach attacking.
trajectory mode_turret_manual (avatar &you, turret_data &turret)
Manually firing vehicle turret.
trajectory mode_turrets (avatar &you, vehicle &veh, const std::vector< vehicle_part * > &turrets)
Selecting target for turrets (when using vehicle controls)
trajectory mode_spell (avatar &you, spell &casting, bool no_fail, bool no_mana)
Casting a spell.
Typedef Documentation
trajectory
using target_handler::trajectory = typedef std::vector<tripoint>
Definition at line 29 of file ranged.h.
Function Documentation
mode_fire()
target_handler::trajectory target_handler::mode_fire (avatar & you, aim_activity_actor & activity)
Firing ranged weapon.
This mode allows spending moves on aiming.
Definition at line 428 of file ranged.cpp.
 {
     target_ui ui = target_ui();
     ui.you = &you;
     ui.mode = target_ui::TargetMode::Fire;
     ui.activity = &activity;
     ui.relevant = &*activity.get_weapon();
     gun_mode gun = ui.relevant->gun_current_mode();
     ui.range = gun.target->gun_range( &you );
     ui.ammo = gun->ammo_data();
     return ui.run();
 }
References target_ui::Fire, and gun.
Referenced by aim_activity_actor::do_turn().
mode_reach()
target_handler::trajectory target_handler::mode_reach (avatar & you, item_location weapon)
Reach attacking.
Definition at line 455 of file ranged.cpp.
 {
     target_ui ui = target_ui();
     ui.you = &you;
     ui.mode = target_ui::TargetMode::Reach;
     ui.relevant = weapon.get_item();
     ui.range = weapon ? weapon->current_reach_range( you ) : 1;
     restore_on_out_of_scope<tripoint> view_offset_prev( you.view_offset );
     return ui.run();
 }
References item::current_reach_range(), item_location::get_item(), target_ui::Reach, and Character::view_offset.
Referenced by reach_attack().
mode_select_only()
target_handler::trajectory target_handler::mode_select_only (avatar & you, int range)
Generic target select without fire something.
Definition at line 417 of file ranged.cpp.
 {
     target_ui ui = target_ui();
     ui.you = &you;
     ui.mode = target_ui::TargetMode::SelectOnly;
     ui.range = range;
     restore_on_out_of_scope<tripoint> view_offset_prev( you.view_offset );
     return ui.run();
 }
References target_ui::SelectOnly, and Character::view_offset.
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile().
mode_spell()
target_handler::trajectory target_handler::mode_spell (avatar & you, spell & casting, bool no_fail, bool no_mana)
Casting a spell.
Definition at line 511 of file ranged.cpp.
 {
     target_ui ui = target_ui();
     ui.you = &you;
     ui.mode = target_ui::TargetMode::Spell;
     ui.casting = &casting;
     ui.range = casting.range( you );
     ui.no_fail = no_fail;
     ui.no_mana = no_mana;
     restore_on_out_of_scope<tripoint> view_offset_prev( you.view_offset );
     return ui.run();
 }
References spell::range(), target_ui::Spell, and Character::view_offset.
Referenced by spell::select_target().
mode_throw()
target_handler::trajectory target_handler::mode_throw (avatar & you, item & relevant, bool blind_throwing)
Throwing item.
Definition at line 442 of file ranged.cpp.
 {
     target_ui ui = target_ui();
     ui.you = &you;
     ui.mode = blind_throwing ? target_ui::TargetMode::ThrowBlind : target_ui::TargetMode::Throw;
     ui.relevant = &relevant;
     ui.range = you.throw_range( relevant );
     restore_on_out_of_scope<tripoint> view_offset_prev( you.view_offset );
     return ui.run();
 }
References target_ui::Throw, Character::throw_range(), target_ui::ThrowBlind, and Character::view_offset.
Referenced by avatar::longpull(), and avatar_action::plthrow().
mode_turret_manual()
target_handler::trajectory target_handler::mode_turret_manual (avatar & you, turret_data & turret)
Manually firing vehicle turret.
Definition at line 467 of file ranged.cpp.
 {
     target_ui ui = target_ui();
     ui.you = &you;
     ui.mode = target_ui::TargetMode::TurretManual;
     ui.turret = &turret;
     ui.relevant = &*turret.base();
     ui.range = turret.range();
     ui.ammo = turret.ammo_data();
     restore_on_out_of_scope<tripoint> view_offset_prev( you.view_offset );
     return ui.run();
 }
References turret_data::ammo_data(), turret_data::base(), turret_data::range(), target_ui::TurretManual, and Character::view_offset.
Referenced by avatar_action::fire_turret_manual().
mode_turrets()
target_handler::trajectory target_handler::mode_turrets (avatar & you, vehicle & veh, const std::vector< vehicle_part * > & turrets)
Selecting target for turrets (when using vehicle controls)
Definition at line 481 of file ranged.cpp.
 {
     // Find radius of a circle centered at u encompassing all points turrets can aim at
     // FIXME: this calculation is fine for square distances, but results in an underestimation
     //        when used with real circles
     int range_total = 0;
     for( vehicle_part *t : turrets ) {
         int range = veh.turret_query( *t ).range();
         tripoint pos = veh.global_part_pos3( *t );
         int res = 0;
         res = std::max( res, rl_dist( you.pos(), pos + point( range, 0 ) ) );
         res = std::max( res, rl_dist( you.pos(), pos + point( -range, 0 ) ) );
         res = std::max( res, rl_dist( you.pos(), pos + point( 0, range ) ) );
         res = std::max( res, rl_dist( you.pos(), pos + point( 0, -range ) ) );
         range_total = std::max( range_total, res );
     }
     target_ui ui = target_ui();
     ui.you = &you;
     ui.mode = target_ui::TargetMode::Turrets;
     ui.veh = &veh;
     ui.vturrets = &turrets;
     ui.range = range_total;
     restore_on_out_of_scope<tripoint> view_offset_prev( you.view_offset );
     return ui.run();
 }
References vehicle::global_part_pos3(), max(), Creature::pos(), math_opers::pos(), turret_data::range(), rl_dist(), vehicle::turret_query(), target_ui::Turrets, and Character::view_offset.
Referenced by vehicle::turrets_aim().