Cataclysm DDA: talk_effect_fun::anonymous_namespace{npctalk.cpp} Namespace Reference
talk_effect_fun::anonymous_namespace{npctalk.cpp} Namespace Reference
Functions
talk_effect_fun_t::func f_companion_mission (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_add_effect (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_remove_effect (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_add_trait (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_activate_trait (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_deactivate_trait (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_remove_trait (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_learn_martial_art (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_forget_martial_art (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_mutate (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_mutate_category (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_mutate_towards (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_add_bionic (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_lose_bionic (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_add_var (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_remove_var (const JsonObject &jo, std::string_view member, bool is_npc)
void map_add_item (item &it, tripoint_abs_ms target_pos)
void receive_item (itype_id &item_name, int count, std::string_view container_name, const dialogue &d, bool use_item_group, bool suppress_message, const std::vector< std::string > &flags, bool add_talker=true, const tripoint_abs_ms &p=tripoint_abs_ms(), bool force_equip=false)
talk_effect_fun_t f_spawn_item (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_u_buy_item (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_u_sell_item (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_consume_item (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_remove_item_with (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_u_spend_cash (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_npc_change_faction (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_npc_change_class (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_change_faction_rep (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_add_debt (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_toggle_npc_rule (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_set_npc_rule (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_clear_npc_rule (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_npc_engagement_rule (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_npc_aim_rule (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_npc_cbm_reserve_rule (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_npc_cbm_recharge_rule (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_location_variable (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_location_variable_adjust (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_transform_radius (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_transform_line (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_place_override (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_mapgen_update (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_alter_timed_events (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_revert_location (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_npc_goal (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_guard_pos (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_bulk_trade_accept (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_npc_gets_item (bool to_use)
talk_effect_fun_t::func f_add_mission (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_u_buy_monster (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_learn_recipe (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_forget_recipe (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_turn_cost (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_npc_first_topic (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_message (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_assign_activity (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_add_wet (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_open_dialogue (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_take_control (const JsonObject &jo, std::string_view)
talk_effect_fun_t::func f_take_control_menu ()
talk_effect_fun_t::func f_sound_effect (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_give_achievment (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_mod_healthy (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_cast_spell (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_attack (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_die (bool is_npc)
talk_effect_fun_t::func f_prevent_death (bool is_npc)
talk_effect_fun_t::func f_lightning ()
talk_effect_fun_t::func f_next_weather ()
talk_effect_fun_t::func f_set_string_var (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_set_condition (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_assign_mission (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_finish_mission (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_remove_active_mission (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_offer_mission (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_set_flag (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_unset_flag (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_activate (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_math (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_transform_item (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_make_sound (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_run_eocs (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_run_eoc_until (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_run_eoc_selector (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_run_eoc_with (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_run_npc_eocs (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_run_monster_eocs (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_run_inv_eocs (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_map_run_item_eocs (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_set_talker (const JsonObject &jo, std::string_view member, bool is_npc)
void process_eoc (const effect_on_condition_id &eoc, dialogue &d, time_duration time_in_future)
talk_effect_fun_t::func f_queue_eocs (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_queue_eoc_with (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_weighted_list_eocs (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_if (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_switch (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_foreach (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_roll_remainder (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_add_morale (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_lose_morale (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_add_faction_trust (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_lose_faction_trust (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_custom_light_level (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_give_equipment (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func f_spawn_monster (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_spawn_npc (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_field (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_teleport (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func f_wants_to_talk (bool is_npc)
talk_effect_fun_t::func f_trigger_event (const JsonObject &jo, std::string_view member)
Function Documentation
f_activate()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 4748 of file npctalk.cpp.
 {
     str_or_var method = get_str_or_var( jo.get_member( member ), member, true );
     std::optional<var_info> target_var;
     if( jo.has_member( "target_var" ) ) {
         target_var = read_var_info( jo.get_object( "target_var" ) );
     }
     return [is_npc, method, target_var]( dialogue & d ) {
         Character *guy = d.actor( is_npc )->get_character();
         item_location *it = d.actor( !is_npc )->get_item();
         if( guy ) {
             const std::string method_str = method.evaluate( d );
             if( it && it->get_item() ) {
                 if( !it->get_item()->get_usable_item( method_str ) ) {
                     add_msg_debug( debugmode::DF_NPC, "Invalid use action.  %s", method_str );
                     return;
                 }
                 if( target_var.has_value() ) {
                     tripoint_abs_ms target_pos = get_tripoint_from_var( target_var, d );
                     if( get_map().inbounds( target_pos ) ) {
                         guy->invoke_item( it->get_item(), method_str, get_map().getlocal( target_pos ) );
                         return;
                     }
                 }
                 guy->invoke_item( it->get_item(), method.evaluate( d ) );
             } else {
                 debugmsg( "%s talker must be Item.", is_npc ? "alpha" : "beta" );
             }
         } else {
             debugmsg( "%s talker must be Character.", is_npc ? "beta" : "alpha" );
         }
     };
 }
References dialogue::actor(), add_msg_debug, debugmsg, debugmode::DF_NPC, abstract_str_or_var< T >::evaluate(), talker::get_character(), talker::get_item(), get_map(), JsonObject::get_member(), JsonObject::get_object(), get_str_or_var(), get_tripoint_from_var(), item::get_usable_item(), JsonObject::has_member(), Character::invoke_item(), member, and read_var_info().
f_activate_trait()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate_trait (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 2976 of file npctalk.cpp.
 {
     str_or_var new_trait = get_str_or_var( jo.get_member( member ), member, true );
     return [is_npc, new_trait]( dialogue const & d ) {
         d.actor( is_npc )->activate_mutation( trait_id( new_trait.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_add_bionic()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_bionic (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 3059 of file npctalk.cpp.
 {
     str_or_var new_bionic = get_str_or_var( jo.get_member( member ), member, true );
     return [is_npc, new_bionic]( dialogue const & d ) {
         d.actor( is_npc )->add_bionic( bionic_id( new_bionic.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_add_debt()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_debt (const JsonObject & jo, std::string_view member)
Definition at line 3453 of file npctalk.cpp.
 {
     std::vector<trial_mod> debt_modifiers;
     for( JsonArray jmod : jo.get_array( member ) ) {
         trial_mod this_modifier;
         this_modifier.first = jmod.next_string();
         this_modifier.second = jmod.next_int();
         debt_modifiers.push_back( this_modifier );
     }
     return [debt_modifiers]( dialogue const & d ) {
         int debt = 0;
         for( const trial_mod &this_mod : debt_modifiers ) {
             if( this_mod.first == "TOTAL" ) {
                 debt *= this_mod.second;
             } else {
                 debt += parse_mod( d, this_mod.first, this_mod.second );
             }
         }
         d.actor( true )->add_debt( debt );
     };
 }
References dialogue::actor(), talker::add_debt(), JsonObject::get_array(), member, and parse_mod().
f_add_effect()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_effect (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 2901 of file npctalk.cpp.
 {
     str_or_var new_effect = get_str_or_var( jo.get_member( member ), member, true );
     bool permanent = false;
     bool force = false;
     duration_or_var dov_duration;
     dbl_or_var dov_intensity;
     if( jo.has_string( "duration" ) ) {
         const std::string dur_string = jo.get_string( "duration" );
         if( dur_string == "PERMANENT" ) {
             permanent = true;
             dov_duration = get_duration_or_var( jo, "", false, 1_turns );
         } else {
             dov_duration = get_duration_or_var( jo, "duration", false, 1000_turns );
         }
     } else {
         dov_duration = get_duration_or_var( jo, "duration", true );
     }
     dov_intensity = get_dbl_or_var( jo, "intensity", false, 0 );
     if( jo.has_bool( "force" ) ) {
         force = jo.get_bool( "force" );
     }
     str_or_var target;
     if( jo.has_member( "target_part" ) ) {
         target = get_str_or_var( jo.get_member( "target_part" ), "target_part", false, "bp_null" );
     } else {
         target.str_val = "bp_null";
     }
     return [is_npc, new_effect, dov_duration, target, permanent, force,
             dov_intensity]( dialogue & d ) {
         d.actor( is_npc )->add_effect( efftype_id( new_effect.evaluate( d ) ),
                                        dov_duration.evaluate( d ),
                                        target.evaluate( d ), permanent, force,
                                        dov_intensity.evaluate( d ) );
     };
 }
References dbl_or_var::evaluate(), duration_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), force, JsonObject::get_bool(), get_dbl_or_var(), get_duration_or_var(), JsonObject::get_member(), get_str_or_var(), JsonObject::get_string(), JsonObject::has_bool(), JsonObject::has_member(), JsonObject::has_string(), member, permanent, and abstract_str_or_var< T >::str_val.
f_add_faction_trust()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_faction_trust (const JsonObject & jo, std::string_view member)
Definition at line 5732 of file npctalk.cpp.
 {
     dbl_or_var dov = get_dbl_or_var( jo, member );
     return [dov]( dialogue & d ) {
         d.actor( true )->get_faction()->trusts_u += dov.evaluate( d );
     };
 }
References dialogue::actor(), dbl_or_var::evaluate(), get_dbl_or_var(), talker::get_faction(), member, and faction_template::trusts_u.
f_add_mission()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_mission (const JsonObject & jo, std::string_view member)
Definition at line 4099 of file npctalk.cpp.
 {
     str_or_var mission_id = get_str_or_var( jo.get_member( member ), member, true );
     return [mission_id]( dialogue const & d ) {
         d.actor( true )->add_mission( mission_type_id( mission_id.evaluate( d ) ) );
     };
 }
References dialogue::actor(), talker::add_mission(), JsonObject::get_member(), get_str_or_var(), and member.
f_add_morale()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_morale (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 5703 of file npctalk.cpp.
 {
     str_or_var new_type = get_str_or_var( jo.get_member( member ), member, true );
     dbl_or_var dov_bonus = get_dbl_or_var( jo, "bonus" );
     dbl_or_var dov_max_bonus = get_dbl_or_var( jo, "max_bonus" );
     duration_or_var dov_duration = get_duration_or_var( jo, "duration", false, 1_hours );
     duration_or_var dov_decay_start = get_duration_or_var( jo, "decay_start", false, 30_minutes );
     const bool capped = jo.get_bool( "capped", false );
     return [is_npc, new_type, dov_bonus, dov_max_bonus, dov_duration, dov_decay_start,
             capped]( dialogue & d ) {
         d.actor( is_npc )->add_morale( morale_type( new_type.evaluate( d ) ),
                                        dov_bonus.evaluate( d ),
                                        dov_max_bonus.evaluate( d ),
                                        dov_duration.evaluate( d ),
                                        dov_decay_start.evaluate( d ),
                                        capped );
     };
 }
References dialogue::actor(), talker::add_morale(), dbl_or_var::evaluate(), duration_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), JsonObject::get_bool(), get_dbl_or_var(), get_duration_or_var(), JsonObject::get_member(), get_str_or_var(), and member.
f_add_trait()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_trait (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 2956 of file npctalk.cpp.
 {
     str_or_var new_trait = get_str_or_var( jo.get_member( member ), member, true );
     str_or_var new_variant;
     if( jo.has_member( "variant" ) ) {
         new_variant = get_str_or_var( jo.get_member( "variant" ), "variant", true );
     } else {
         new_variant.str_val = "";
     }
     return [is_npc, new_trait, new_variant]( dialogue const & d ) {
         const trait_id trait = trait_id( new_trait.evaluate( d ) );
         const mutation_variant *variant = trait->variant( new_variant.evaluate( d ) );
         d.actor( is_npc )->set_mutation( trait, variant );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), JsonObject::has_member(), member, abstract_str_or_var< T >::str_val, and mutation_branch::variant().
f_add_var()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_var (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 3077 of file npctalk.cpp.
 {
     dbl_or_var empty;
     const std::string var_name = get_talk_varname( jo, member, false, empty );
     const std::string var_base_name = get_talk_var_basename( jo, member, false );
     const bool time_check = jo.has_member( "time" ) && jo.get_bool( "time" );
     std::vector<std::string> possible_values = jo.get_string_array( "possible_values" );
     if( possible_values.empty() ) {
         const std::string value = time_check ? "" : jo.get_string( "value" );
         possible_values.push_back( value );
     }
     return [is_npc, var_name, possible_values, time_check, var_base_name]( dialogue const & d ) {
         talker *actor = d.actor( is_npc );
         if( time_check ) {
             actor->set_value( var_name, string_format( "%d", to_turn<int>( calendar::turn ) ) );
         } else {
             int index = rng( 0, possible_values.size() - 1 );
             actor->set_value( var_name, possible_values[index] );
             get_event_bus().send<event_type::u_var_changed>( var_base_name, possible_values[index] );
         }
     };
 }
References JsonObject::get_bool(), get_event_bus(), JsonObject::get_string(), JsonObject::get_string_array(), get_talk_var_basename(), get_talk_varname(), JsonObject::has_member(), member, rng(), event_bus::send(), talker::set_value(), string_format(), calendar::turn, and u_var_changed.
f_add_wet()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_wet (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 4309 of file npctalk.cpp.
 {
     dbl_or_var dov = get_dbl_or_var( jo, member );
     return [is_npc, dov]( dialogue & d ) {
         Character *target = d.actor( is_npc )->get_character();
         if( target ) {
             wet_character( *target, dov.evaluate( d ) );
         }
     };
 }
References dialogue::actor(), dbl_or_var::evaluate(), talker::get_character(), get_dbl_or_var(), member, and wet_character().
f_alter_timed_events()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_alter_timed_events (const JsonObject & jo, std::string_view member)
Definition at line 3894 of file npctalk.cpp.
 {
     str_or_var key = get_str_or_var( jo.get_member( member ), member, true );
     duration_or_var time_in_future = get_duration_or_var( jo, "time_in_future", false,
                                      0_seconds );
     return [key, time_in_future]( dialogue & d ) {
         get_timed_events().set_all( key.evaluate( d ), time_in_future.evaluate( d ) );
     };
 }
References duration_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), get_duration_or_var(), JsonObject::get_member(), get_str_or_var(), get_timed_events(), member, and timed_event_manager::set_all().
f_assign_activity()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_activity (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 4296 of file npctalk.cpp.
 {
     duration_or_var dov = get_duration_or_var( jo, "duration", true );
     str_or_var act = get_str_or_var( jo.get_member( member ), member, true );
     return [is_npc, dov, act]( dialogue & d ) {
         Character *target = d.actor( is_npc )->get_character();
         if( target ) {
             target->assign_activity( activity_id( act.evaluate( d ) ), to_moves<int>( dov.evaluate( d ) ) );
         }
     };
 }
References act, dialogue::actor(), Character::assign_activity(), duration_or_var::evaluate(), talker::get_character(), get_duration_or_var(), JsonObject::get_member(), get_str_or_var(), and member.
f_assign_mission()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_mission (const JsonObject & jo, std::string_view member)
Definition at line 4629 of file npctalk.cpp.
 {
     str_or_var mission_name = get_str_or_var( jo.get_member( member ), member, true );
     return [mission_name]( dialogue const & d ) {
         avatar &player_character = get_avatar();
         const mission_type_id &mission_type = mission_type_id( mission_name.evaluate( d ) );
         mission *new_mission = mission::reserve_new( mission_type, character_id() );
         new_mission->assign( player_character );
     };
 }
References mission::assign(), abstract_str_or_var< T >::evaluate(), get_avatar(), JsonObject::get_member(), get_str_or_var(), member, and mission::reserve_new().
f_attack()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_attack (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 4527 of file npctalk.cpp.
 {
     str_or_var force_technique = get_str_or_var( jo.get_member( member ), member, true );
     bool allow_special = jo.get_bool( "allow_special", true );
     bool allow_unarmed = jo.get_bool( "allow_unarmed", true );;
     dbl_or_var forced_movecost = get_dbl_or_var( jo, "forced_movecost", false, -1.0 );
     return [is_npc, allow_special, force_technique, allow_unarmed,
             forced_movecost]( dialogue & d ) {
         // if beta is attacking then target is the alpha
         talker *target = d.actor( !is_npc );
         talker *attacker = d.actor( is_npc );
         Creature *c = target->get_creature();
         if( c ) {
             matec_id m( force_technique.evaluate( d ) );
             attacker->attack_target( *c, allow_special, m, allow_unarmed, forced_movecost.evaluate( d ) );
         }
     };
 }
References dialogue::actor(), talker::attack_target(), c, dbl_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), JsonObject::get_bool(), talker::get_creature(), get_dbl_or_var(), JsonObject::get_member(), get_str_or_var(), and member.
f_bulk_trade_accept()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 3994 of file npctalk.cpp.
 {
     dbl_or_var dov_quantity;
     if( jo.has_member( member ) ) {
         dov_quantity = get_dbl_or_var( jo, member, false, -1 );
     } else {
         dov_quantity.min.dbl_val = -1;
     }
     bool is_trade = member == "u_bulk_trade_accept" || member == "npc_bulk_trade_accept";
     return [is_trade, is_npc, dov_quantity]( dialogue & d ) {
         talker *seller = d.actor( is_npc );
         talker *buyer = d.actor( !is_npc );
         item tmp( d.cur_item );
         int quantity = dov_quantity.evaluate( d );
         int seller_has = 0;
         int seller_has_loose = 0;
         std::vector<item> seller_cans;
         auto is_canned_item = [&tmp]( const item & e ) {
             std::vector<const item_pocket *> pockets = e.get_all_contained_pockets();
             return pockets.size() == 1 &&
                    pockets[0]->size() == 1 &&
                    pockets[0]->sealed() &&
                    pockets[0]->front().type == tmp.type;
         };
         if( tmp.count_by_charges() ) {
             seller_has = seller->charges_of( d.cur_item );
         } else {
             std::vector<item *> cans_tmp = seller->items_with( is_canned_item );
             for( item *it : cans_tmp ) {
                 seller_cans.emplace_back( *it );
             }
             seller_has_loose = seller->items_with( [&tmp,
             &cans_tmp]( const item & e ) {
                 return tmp.type == e.type &&
                 !std::any_of( cans_tmp.begin(), cans_tmp.end(), [&e]( const item * n ) {
                     return &n->get_all_contained_pockets()[0]->front() == &e;
                 } );
             } ).size();
             seller_has = cans_tmp.size() + seller_has_loose;
         }
         seller_has = ( quantity == -1 ) ? seller_has : std::min( seller_has, quantity );
         tmp.charges = seller_has;
         if( is_trade ) {
             const int npc_debt = d.actor( true )->debt();
             int price = total_price( *seller, d.cur_item ) * ( is_npc ? -1 : 1 ) + npc_debt;
             if( d.actor( true )->get_faction() && !d.actor( true )->get_faction()->currency.is_empty() ) {
                 const itype_id &pay_in = d.actor( true )->get_faction()->currency;
                 item pay( pay_in );
                 const int value = d.actor( true )->value( pay );
                 if( value > 0 ) {
                     int required = price / value;
                     int buyer_has = required;
                     if( is_npc ) {
                         buyer_has = std::min( buyer_has, buyer->charges_of( pay_in ) );
                         buyer->use_charges( pay_in, buyer_has );
                     } else {
                         if( buyer_has == 1 ) {
                             //~ %1%s is the NPC name, %2$s is an item
                             popup( _( "%1$s gives you a %2$s." ), buyer->disp_name(),
                                    pay.tname() );
                         } else if( buyer_has > 1 ) {
                             //~ %1%s is the NPC name, %2$d is a number of items, %3$s are items
                             popup( _( "%1$s gives you %2$d %3$s." ), buyer->disp_name(), buyer_has,
                                    pay.tname() );
                         }
                     }
                     for( int i = 0; i < buyer_has; i++ ) {
                         seller->i_add( pay );
                         price -= value;
                     }
                 } else {
                     debugmsg( "%s pays in bulk_trade_accept with faction currency worth 0!",
                               d.actor( true )->disp_name() );
                 }
             } else {
                 debugmsg( "%s has no faction currency to pay with in bulk_trade_accept!",
                           d.actor( true )->disp_name() );
             }
             d.actor( true )->add_debt( -npc_debt );
             d.actor( true )->add_debt( price );
         }
         if( tmp.count_by_charges() ) {
             seller->use_charges( d.cur_item, seller_has );
         } else {
             seller->use_amount( d.cur_item, seller_has_loose );
             seller->remove_items_with( is_canned_item );
         }
         if( seller_cans.size() != size_t( seller_has ) ) {
             buyer->i_add( tmp );
         }
         for( const item &it : seller_cans ) {
             buyer->i_add( it );
         }
     };
 }
References _, dialogue::actor(), talker::add_debt(), item::charges, talker::charges_of(), item::count_by_charges(), dialogue::cur_item, faction_template::currency, dbl_or_var_part::dbl_val, talker::debt(), debugmsg, talker::disp_name(), dbl_or_var::evaluate(), get_dbl_or_var(), talker::get_faction(), JsonObject::has_member(), talker::i_add(), string_id< T >::is_empty(), talker::items_with(), member, dbl_or_var::min, min(), popup(), talker::remove_items_with(), om_direction::size, item::tname(), total_price(), item::type, talker::use_amount(), talker::use_charges(), and talker::value().
Referenced by talk_effect_t::parse_string_effect().
f_cast_spell()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 4447 of file npctalk.cpp.
 {
     std::vector<effect_on_condition_id> true_eocs = load_eoc_vector( jo, "true_eocs" );
     std::vector<effect_on_condition_id> false_eocs = load_eoc_vector( jo, "false_eocs" );
     bool targeted = jo.get_bool( "targeted", false );
     std::optional<var_info> loc_var;
     if( jo.has_object( "loc" ) ) {
         loc_var = read_var_info( jo.get_object( "loc" ) );
     }
     JsonObject spell_jo = jo.get_object( member );
     str_or_var id = get_str_or_var( spell_jo.get_member( "id" ), "id" );
     bool hit_self = spell_jo.get_bool( "hit_self", false );
     int trigger_once_in = spell_jo.get_int( "once_in", 1 );
     translation_or_var trigger_message;
     if( spell_jo.has_member( "message" ) ) {
         trigger_message = get_translation_or_var( spell_jo.get_member( "message" ), "message", true );
     } else {
         trigger_message.str_val = translation();
     }
     translation_or_var npc_trigger_message;
     if( spell_jo.has_member( "npc_message" ) ) {
         npc_trigger_message = get_translation_or_var( spell_jo.get_member( "npc_message" ), "npc_message",
                               true );
     } else {
         npc_trigger_message.str_val = translation();
     }
     dbl_or_var dov_max_level = get_dbl_or_var( spell_jo, "max_level", false, -1 );
     dbl_or_var level = get_dbl_or_var( spell_jo, "min_level", false );
     if( spell_jo.has_string( "level" ) ) {
         debugmsg( "level member for fake_spell was renamed to min_level.  id: %s",
                   id.str_val.value_or( "" ) );
     }
     return [is_npc, id, hit_self, dov_max_level, trigger_once_in, level, trigger_message,
                     npc_trigger_message, targeted, loc_var, true_eocs,
             false_eocs]( dialogue & d ) {
         std::optional<int> max_level;
         int max_level_int = dov_max_level.evaluate( d );
         if( max_level_int == -1 ) {
             max_level = std::nullopt;
         } else {
             max_level = max_level_int;
         }
         fake_spell fake( spell_id( id.evaluate( d ) ), hit_self, max_level );
         fake.trigger_once_in = trigger_once_in;
         fake.level = level.evaluate( d );
         fake.trigger_message = no_translation( trigger_message.evaluate( d ) );
         fake.npc_trigger_message = no_translation( npc_trigger_message.evaluate( d ) );
         Creature *caster = d.actor( is_npc )->get_creature();
         if( !caster ) {
             debugmsg( "No valid caster for spell.  %s", d.get_callstack() );
             run_eoc_vector( false_eocs, d );
             return;
         } else {
             if( !fake.is_valid() ) {
                 debugmsg( "%s is not a valid spell.  %s", fake.id.c_str(), d.get_callstack() );
                 run_eoc_vector( false_eocs, d );
                 return;
             }
             spell sp = fake.get_spell( *caster, 0 );
             if( targeted ) {
                 if( std::optional<tripoint> target = sp.select_target( caster ) ) {
                     sp.cast_all_effects( *caster, *target );
                     caster->add_msg_player_or_npc( fake.trigger_message, fake.npc_trigger_message );
                 }
             } else {
                 const tripoint target_pos = loc_var ?
                                             get_map().getlocal( get_tripoint_from_var( loc_var, d ) ) : caster->pos();
                 sp.cast_all_effects( *caster, target_pos );
                 caster->add_msg_player_or_npc( fake.trigger_message, fake.npc_trigger_message );
             }
         }
         run_eoc_vector( true_eocs, d );
     };
 }
References dialogue::actor(), Creature::add_msg_player_or_npc(), string_id< T >::c_str(), spell::cast_all_effects(), debugmsg, dbl_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), JsonObject::get_bool(), dialogue::get_callstack(), talker::get_creature(), get_dbl_or_var(), JsonObject::get_int(), get_map(), JsonObject::get_member(), JsonObject::get_object(), fake_spell::get_spell(), get_str_or_var(), get_translation_or_var(), get_tripoint_from_var(), map::getlocal(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), base_camps::id, fake_spell::id, fake_spell::is_valid(), fake_spell::level, load_eoc_vector(), member, no_translation(), fake_spell::npc_trigger_message, Creature::pos(), read_var_info(), run_eoc_vector(), spell::select_target(), abstract_str_or_var< T >::str_val, fake_spell::trigger_message, and fake_spell::trigger_once_in.
f_change_faction_rep()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_change_faction_rep (const JsonObject & jo, std::string_view member)
Definition at line 3445 of file npctalk.cpp.
 {
     dbl_or_var rep_change = get_dbl_or_var( jo, member );
     return [rep_change]( dialogue & d ) {
         d.actor( true )->add_faction_rep( rep_change.evaluate( d ) );
     };
 }
References dialogue::actor(), talker::add_faction_rep(), dbl_or_var::evaluate(), get_dbl_or_var(), and member.
f_clear_npc_rule()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_clear_npc_rule (const JsonObject & jo, std::string_view member)
Definition at line 3491 of file npctalk.cpp.
 {
     str_or_var rule = get_str_or_var( jo.get_member( member ), member, true );
     return [rule]( dialogue const & d ) {
         d.actor( true )->clear_ai_rule( "ally_rule", rule.evaluate( d ) );
     };
 }
References dialogue::actor(), talker::clear_ai_rule(), abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_companion_mission()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_companion_mission (const JsonObject & jo, std::string_view member)
Definition at line 2892 of file npctalk.cpp.
 {
     str_or_var id = get_str_or_var( jo.get_member( member ), member, true );
     return [id]( dialogue const & d ) {
         std::string role_id = id.evaluate( d );
         d.actor( true )->set_companion_mission( role_id );
     };
 }
References JsonObject::get_member(), get_str_or_var(), base_camps::id, and member.
f_consume_item()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_consume_item (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 3348 of file npctalk.cpp.
 {
     str_or_var item_name = get_str_or_var( jo.get_member( member ), member, true );
     dbl_or_var charges = get_dbl_or_var( jo, "charges", false, 0 );
     dbl_or_var count;
     if( !jo.has_int( "charges" ) ) {
         count = get_dbl_or_var( jo, "count", false, 1 );
     } else {
         count = get_dbl_or_var( jo, "count", false, 0 );
     }
     const bool do_popup = jo.get_bool( "popup", false );
     return [do_popup, is_npc, item_name, count, charges]( dialogue & d ) {
         // this is stupid, but I couldn't get the assignment to work
         int current_count = count.evaluate( d );
         int current_charges = charges.evaluate( d );
         itype_id current_item_name = itype_id( item_name.evaluate( d ) );
         const auto consume_item = [&]( talker & p, const itype_id & item_name, int current_count,
         int current_charges ) {
             if( current_charges == 0 && item::count_by_charges( item_name ) ) {
                 current_charges = current_count;
                 current_count = 0;
             }
             if( current_count == 0 && current_charges > 0 &&
                 p.has_charges( item_name, current_charges, true ) ) {
                 p.use_charges( item_name, current_charges, true );
             } else if( p.has_amount( item_name, current_count ) ) {
                 if( current_charges > 0 && p.has_charges( item_name, current_charges, true ) ) {
                     p.use_charges( item_name, current_charges, true );
                 }
                 p.use_amount( item_name, current_count );
             } else {
                 item old_item( item_name );
                 //~ %1%s is the "You" or the NPC name, %2$s are a translated item name
                 popup( _( "%1$s doesn't have a %2$s!" ), p.disp_name(), old_item.tname() );
             }
         };
         if( is_npc ) {
             consume_item( *d.actor( true ), current_item_name, current_count, current_charges );
         } else {
             if( do_popup ) {
                 if( current_count == 1 ) {
                     popup( _( "You give %1$s a %2$s." ), d.actor( true )->disp_name(),
                            item::nname( current_item_name ) );
                 } else {
                     popup( _( "You give %1$s %2$d %3$s." ), d.actor( true )->disp_name(), current_count,
                            item::nname( current_item_name ), current_count );
                 }
             }
             consume_item( *d.actor( false ), current_item_name, current_count, current_charges );
         }
     };
 }
References _, dialogue::actor(), item::count_by_charges(), talker::disp_name(), dbl_or_var::evaluate(), JsonObject::get_bool(), get_dbl_or_var(), JsonObject::get_member(), get_str_or_var(), talker::has_amount(), talker::has_charges(), JsonObject::has_int(), tname::item_name(), member, item::nname(), popup(), item::tname(), talker::use_amount(), and talker::use_charges().
f_custom_light_level()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_custom_light_level (const JsonObject & jo, std::string_view member)
Definition at line 5749 of file npctalk.cpp.
 {
     dbl_or_var dov = get_dbl_or_var( jo, member, true );
     duration_or_var dov_length = get_duration_or_var( jo, "length", false, 0_seconds );
     str_or_var key;
     if( jo.has_member( "key" ) ) {
         key = get_str_or_var( jo.get_member( "key" ), "key", false, "" );
     } else {
         key.str_val = "";
     }
     return [dov_length, dov, key]( dialogue & d ) {
         get_timed_events().add( timed_event_type::CUSTOM_LIGHT_LEVEL,
                                 calendar::turn + dov_length.evaluate( d ) +
                                 1_seconds/*We add a second here because this will get ticked on the turn its applied before it has an effect*/,
                                 -1, dov.evaluate( d ), key.evaluate( d ) );
     };
 }
References timed_event_manager::add(), CUSTOM_LIGHT_LEVEL, dbl_or_var::evaluate(), duration_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), get_dbl_or_var(), get_duration_or_var(), JsonObject::get_member(), get_str_or_var(), get_timed_events(), JsonObject::has_member(), member, abstract_str_or_var< T >::str_val, and calendar::turn.
f_deactivate_trait()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_deactivate_trait (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 2985 of file npctalk.cpp.
 {
     str_or_var new_trait = get_str_or_var( jo.get_member( member ), member, true );
     return [is_npc, new_trait]( dialogue const & d ) {
         d.actor( is_npc )->deactivate_mutation( trait_id( new_trait.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_die()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_die (bool is_npc)
Definition at line 4549 of file npctalk.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         d.actor( is_npc )->die();
     };
 }
References dialogue::actor(), and talker::die().
Referenced by talk_effect_t::parse_string_effect().
f_field()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 6092 of file npctalk.cpp.
 {
     str_or_var new_field = get_str_or_var( jo.get_member( member ), member, true );
     dbl_or_var dov_intensity = get_dbl_or_var( jo, "intensity", false, 1 );
     duration_or_var dov_age = get_duration_or_var( jo, "age", false, 1_turns );
     dbl_or_var dov_radius = get_dbl_or_var( jo, "radius", false, 10000000 );
     const bool outdoor_only = jo.get_bool( "outdoor_only", false );
     const bool indoor_only = jo.get_bool( "indoor_only", false );
     const bool hit_player = jo.get_bool( "hit_player", true );
     std::optional<var_info> target_var;
     if( jo.has_member( "target_var" ) ) {
         target_var = read_var_info( jo.get_object( "target_var" ) );
     }
     return [new_field, dov_intensity, dov_age, dov_radius, outdoor_only,
                hit_player, target_var, is_npc, indoor_only]( dialogue & d ) {
         int radius = dov_radius.evaluate( d );
         int intensity = dov_intensity.evaluate( d );
         tripoint_abs_ms target_pos = d.actor( is_npc )->global_pos();
         if( target_var.has_value() ) {
             target_pos = get_tripoint_from_var( target_var, d );
         }
         for( const tripoint &dest : get_map().points_in_radius( get_map().getlocal( target_pos ),
                 radius ) ) {
             if( ( !outdoor_only || get_map().is_outside( dest ) ) && ( !indoor_only ||
                     !get_map().is_outside( dest ) ) ) {
                 get_map().add_field( dest, field_type_str_id( new_field.evaluate( d ) ), intensity,
                                      dov_age.evaluate( d ),
                                      hit_player );
             }
         }
     };
 }
References dialogue::actor(), map::add_field(), dbl_or_var::evaluate(), duration_or_var::evaluate(), JsonObject::get_bool(), get_dbl_or_var(), get_duration_or_var(), get_map(), JsonObject::get_member(), JsonObject::get_object(), get_str_or_var(), get_tripoint_from_var(), talker::global_pos(), JsonObject::has_member(), intensity, member, points_in_radius(), and read_var_info().
f_finish_mission()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_finish_mission (const JsonObject & jo, std::string_view member)
Definition at line 4641 of file npctalk.cpp.
 {
     str_or_var mission_name = get_str_or_var( jo.get_member( member ), member, true );
     bool success = false;
     std::optional<int> step;
     if( jo.has_int( "step" ) ) {
         step = jo.get_int( "step" );
     } else {
         success = jo.get_bool( "success" );
     }
     return [mission_name, success, step]( dialogue const & d ) {
         avatar &player_character = get_avatar();
         const mission_type_id &mission_type = mission_type_id( mission_name.evaluate( d ) );
         std::vector<mission *> missions = player_character.get_active_missions();
         for( mission *mission : missions ) {
             if( mission->mission_id() == mission_type ) {
                 if( step.has_value() ) {
                     mission->step_complete( step.value() );
                 } else if( success ) {
                     mission->wrap_up();
                 } else {
                     mission->fail();
                 }
                 break;
             }
         }
     };
 }
References abstract_str_or_var< T >::evaluate(), mission::fail(), avatar::get_active_missions(), get_avatar(), JsonObject::get_bool(), JsonObject::get_int(), JsonObject::get_member(), get_str_or_var(), JsonObject::has_int(), member, mission::mission_id(), mission::step_complete(), and mission::wrap_up().
f_foreach()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach (const JsonObject & jo, std::string_view member)
Definition at line 5567 of file npctalk.cpp.
 {
     std::string type = jo.get_string( member.data() );
     var_info itr = read_var_info( jo.get_object( "var" ) );
     talk_effect_t effect;
     effect.load_effect( jo, "effect" );
     std::string target;
     std::vector<str_or_var> array;
     if( jo.has_string( "target" ) ) {
         target = jo.get_string( "target" );
     } else if( jo.has_array( "target" ) ) {
         for( const JsonValue &jv : jo.get_array( "target" ) ) {
             array.emplace_back( get_str_or_var( jv, "target" ) );
         }
     }
     return [type, itr, effect, target, array]( dialogue & d ) {
         std::vector<std::string> list;
         if( type == "ids" ) {
             if( target == "bodypart" ) {
                 for( const body_part_type &bp : body_part_type::get_all() ) {
                     list.push_back( bp.id.str() );
                 }
             } else if( target == "flag" ) {
                 for( const json_flag &f : json_flag::get_all() ) {
                     list.push_back( f.id.str() );
                 }
             } else if( target == "trait" ) {
                 for( const mutation_branch &m : mutation_branch::get_all() ) {
                     list.push_back( m.id.str() );
                 }
             } else if( target == "vitamin" ) {
                 for( const std::pair<const vitamin_id, vitamin> &v : vitamin::all() ) {
                     list.push_back( v.first.str() );
                 }
             }
         } else if( type == "item_group" ) {
             item_group_id ig( target );
             for( const itype *type : item_group::every_possible_item_from( ig ) ) {
                 list.push_back( type->get_id().str() );
             }
         } else if( type == "monstergroup" ) {
             mongroup_id mg( target );
             for( const auto &m : MonsterGroupManager::GetMonstersFromGroup( mg, true ) ) {
                 list.push_back( m.str() );
             }
         } else if( type == "array" ) {
             for( const str_or_var &v : array ) {
                 list.emplace_back( v.evaluate( d ) );
             }
         }
         for( std::string_view str : list ) {
             write_var_value( itr.type, itr.name, &d, str.data() );
             effect.apply( d );
         }
     };
 }
References vitamin::all(), bp, item_group::every_possible_item_from(), body_part_type::get_all(), json_flag::get_all(), mutation_branch::get_all(), JsonObject::get_array(), JsonObject::get_object(), get_str_or_var(), JsonObject::get_string(), MonsterGroupManager::GetMonstersFromGroup(), JsonObject::has_array(), JsonObject::has_string(), int_id< T >::id(), member, abstract_var_info< T >::name, read_var_info(), string_id< T >::str(), abstract_var_info< T >::type, and write_var_value().
f_forget_martial_art()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_forget_martial_art (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 3012 of file npctalk.cpp.
 {
     str_or_var ma_to_forget = get_str_or_var( jo.get_member( member ), member, true );
     return [is_npc, ma_to_forget]( dialogue const & d ) {
         d.actor( is_npc )->forget_martial_art( matype_id( ma_to_forget.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_forget_recipe()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_forget_recipe (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 4144 of file npctalk.cpp.
 {
     str_or_var forgotten_recipe_id = get_str_or_var( jo.get_member( member ), member, true );
     return [forgotten_recipe_id, is_npc]( dialogue const & d ) {
         const recipe_id &r = recipe_id( forgotten_recipe_id.evaluate( d ) );
         d.actor( is_npc )->forget_recipe( r );
     };
 }
References dialogue::actor(), abstract_str_or_var< T >::evaluate(), talker::forget_recipe(), JsonObject::get_member(), get_str_or_var(), and member.
f_give_achievment()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_achievment (const JsonObject & jo, std::string_view member)
Definition at line 4416 of file npctalk.cpp.
 {
     str_or_var achieve = get_str_or_var( jo.get_member( member ), member, true );
     return [achieve]( dialogue const & d ) {
         const achievement_id achievement_to_give( achieve.evaluate( d ) );
         // make sure the achievement is being tracked and that it is currently pending
         std::vector<const achievement *> all_achievements = get_achievements().valid_achievements();
         if( std::find_if( all_achievements.begin(),
         all_achievements.end(), [&achievement_to_give]( const achievement * ach ) {
         return ach->id == achievement_to_give;
     } ) != all_achievements.end() ) {
             if( get_achievements().is_completed( achievement_to_give ) == achievement_completion::pending ) {
                 get_achievements().report_achievement( &achievement_to_give.obj(),
                                                        achievement_completion::completed );
             }
         }
     };
 }
References completed, abstract_str_or_var< T >::evaluate(), get_achievements(), JsonObject::get_member(), get_str_or_var(), member, string_id< T >::obj(), pending, achievements_tracker::report_achievement(), and achievements_tracker::valid_achievements().
f_give_equipment()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_equipment (const JsonObject & jo, std::string_view member)
Definition at line 5768 of file npctalk.cpp.
 {
     JsonObject jobj = jo.get_object( member );
     int allowance = 0;
     std::vector<trial_mod> debt_modifiers;
     if( jobj.has_int( "allowance" ) ) {
         allowance = jobj.get_int( "allowance" );
     } else if( jobj.has_array( "allowance" ) ) {
         for( JsonArray jmod : jobj.get_array( "allowance" ) ) {
             trial_mod this_modifier;
             this_modifier.first = jmod.next_string();
             this_modifier.second = jmod.next_int();
             debt_modifiers.push_back( this_modifier );
         }
     }
     return [debt_modifiers, allowance]( dialogue const & d ) {
         int debt = allowance;
         for( const trial_mod &this_mod : debt_modifiers ) {
             if( this_mod.first == "TOTAL" ) {
                 debt *= this_mod.second;
             } else {
                 debt += parse_mod( d, this_mod.first, this_mod.second );
             }
         }
         if( npc *p = d.actor( true )->get_npc() ) {
             talk_function::give_equipment_allowance( *p, debt );
         }
     };
 }
References dialogue::actor(), JsonObject::get_array(), JsonObject::get_int(), talker::get_npc(), JsonObject::get_object(), talk_function::give_equipment_allowance(), JsonObject::has_array(), JsonObject::has_int(), member, and parse_mod().
f_guard_pos()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_guard_pos (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 3975 of file npctalk.cpp.
 {
     std::optional<var_info> target_var = read_var_info( jo.get_object( member ) );
     bool unique_id = jo.get_bool( "unique_id", false );
     return [target_var, unique_id, is_npc]( dialogue const & d ) {
         npc *guy = d.actor( is_npc )->get_npc();
         if( guy ) {
             var_info cur_var = target_var.value();
             if( unique_id ) {
                 //12 since it should start with npctalk_var
                 cur_var.name.insert( 12, guy->get_unique_id() );
             }
             tripoint_abs_ms target_location = get_tripoint_from_var( cur_var, d );
             guy->set_guard_pos( target_location );
         }
     };
 }
References dialogue::actor(), JsonObject::get_bool(), talker::get_npc(), JsonObject::get_object(), get_tripoint_from_var(), npc::get_unique_id(), member, abstract_var_info< T >::name, read_var_info(), and npc::set_guard_pos().
f_if()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_if (const JsonObject & jo, std::string_view member)
Definition at line 5524 of file npctalk.cpp.
 {
     std::function<bool( dialogue & )> cond;
     talk_effect_t then_effect;
     talk_effect_t else_effect;
     read_condition( jo, std::string( member ), cond, false );
     then_effect.load_effect( jo, "then" );
     if( jo.has_member( "else" ) || jo.has_array( "else" ) ) {
         else_effect.load_effect( jo, "else" );
     }
     return [cond, then_effect, else_effect]( dialogue & d ) {
         if( cond( d ) ) {
             then_effect.apply( d );
         } else {
             else_effect.apply( d );
         }
     };
 }
References talk_effect_t::apply(), JsonObject::has_array(), JsonObject::has_member(), talk_effect_t::load_effect(), member, and read_condition().
f_learn_martial_art()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_learn_martial_art (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 3003 of file npctalk.cpp.
 {
     str_or_var ma_to_learn = get_str_or_var( jo.get_member( member ), member, true );
     return [is_npc, ma_to_learn]( dialogue const & d ) {
         d.actor( is_npc )->learn_martial_art( matype_id( ma_to_learn.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_learn_recipe()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_learn_recipe (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 4134 of file npctalk.cpp.
 {
     str_or_var learned_recipe_id = get_str_or_var( jo.get_member( member ), member, true );
     return [learned_recipe_id, is_npc]( dialogue const & d ) {
         const recipe_id &r = recipe_id( learned_recipe_id.evaluate( d ) );
         d.actor( is_npc )->learn_recipe( r );
     };
 }
References dialogue::actor(), abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), talker::learn_recipe(), and member.
f_lightning()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lightning ()
Definition at line 4566 of file npctalk.cpp.
 {
     return []( dialogue const &/* d */ ) {
         if( get_player_character().posz() >= 0 ) {
             get_weather().lightning_active = true;
         }
     };
 }
References get_player_character(), get_weather(), weather_manager::lightning_active, and Creature::posz().
Referenced by talk_effect_t::parse_string_effect().
f_location_variable()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 3534 of file npctalk.cpp.
 {
     dbl_or_var dov_min_radius = get_dbl_or_var( jo, "min_radius", false, 0 );
     dbl_or_var dov_max_radius = get_dbl_or_var( jo, "max_radius", false, 0 );
     dbl_or_var dov_z_adjust = get_dbl_or_var( jo, "z_adjust", false, 0 );
     dbl_or_var dov_x_adjust = get_dbl_or_var( jo, "x_adjust", false, 0 );
     dbl_or_var dov_y_adjust = get_dbl_or_var( jo, "y_adjust", false, 0 );
     bool z_override = jo.get_bool( "z_override", false );
     const bool outdoor_only = jo.get_bool( "outdoor_only", false );
     const bool passable_only = jo.get_bool( "passable_only", false );
     std::optional<mission_target_params> target_params;
     if( jo.has_object( "target_params" ) ) {
         JsonObject target_obj = jo.get_object( "target_params" );
         target_params = mission_util::parse_mission_om_target( target_obj );
     }
     std::optional<str_or_var> search_target;
     std::optional<std::string> search_type;
     dbl_or_var dov_target_min_radius = get_dbl_or_var( jo, "target_min_radius", false, 0 );
     dbl_or_var dov_target_max_radius = get_dbl_or_var( jo, "target_max_radius", false, 0 );
     int target_types = 0;
     if( jo.has_member( "terrain" ) ) {
         target_types++;
         search_type = "terrain";
     }
     if( jo.has_member( "furniture" ) ) {
         target_types++;
         search_type = "furniture";
     }
     if( jo.has_member( "monster" ) ) {
         target_types++;
         search_type = "monster";
     }
     if( jo.has_member( "npc" ) ) {
         target_types++;
         search_type = "npc";
     }
     if( jo.has_member( "trap" ) ) {
         target_types++;
         search_type = "trap";
     }
     if( jo.has_member( "zone" ) ) {
         target_types++;
         search_type = "zone";
     }
     if( target_types == 1 ) {
         search_target = get_str_or_var( jo.get_member( search_type.value() ), search_type.value(), true );
     } else if( target_types > 1 ) {
         jo.throw_error( "Can only have one of terrain, furniture, monster, trap, zone, or npc." );
     }
     var_info var = read_var_info( jo.get_object( member ) );
     var_type type = var.type;
     std::string var_name = var.name;
     std::vector<effect_on_condition_id> true_eocs = load_eoc_vector( jo, "true_eocs" );
     std::vector<effect_on_condition_id> false_eocs = load_eoc_vector( jo, "false_eocs" );
     return [dov_min_radius, dov_max_radius, var_name, outdoor_only, passable_only, target_params,
                             is_npc, type, dov_x_adjust, dov_y_adjust, dov_z_adjust, z_override, true_eocs, false_eocs,
                     search_target, search_type, dov_target_min_radius, dov_target_max_radius]( dialogue & d ) {
         talker *target = d.actor( is_npc );
         tripoint talker_pos = get_map().getabs( target->pos() );
         tripoint target_pos = talker_pos;
         if( target_params.has_value() ) {
             const tripoint_abs_omt omt_pos = mission_util::get_om_terrain_pos( target_params.value(), d );
             target_pos = tripoint( project_to<coords::ms>( omt_pos ).x(), project_to<coords::ms>( omt_pos ).y(),
                                    project_to<coords::ms>( omt_pos ).z() );
         }
         const tripoint_abs_ms abs_ms( target_pos );
         map *here_ptr = &get_map();
         std::unique_ptr<map> distant_map = std::make_unique<map>();
         if( !get_map().inbounds( abs_ms ) ) {
             distant_map->load( project_to<coords::sm>( abs_ms ), false );
             here_ptr = distant_map.get();
         }
         map &here = *here_ptr;
         if( search_target.has_value() ) {
             if( search_type.value() == "monster" && !get_map().inbounds( abs_ms ) ) {
                 here.spawn_monsters( true, true );
             }
             int min_target_dist = dov_target_min_radius.evaluate( d );
             std::string cur_search_target = search_target.value().evaluate( d );
             bool found = false;
             tripoint_range<tripoint> points = here.points_in_radius( here.getlocal( abs_ms ),
                                               size_t( dov_target_max_radius.evaluate( d ) ), size_t( 0 ) );
             for( const tripoint &search_loc : points ) {
                 if( rl_dist( here.getlocal( talker_pos ), search_loc ) <= min_target_dist ) {
                     continue;
                 }
                 if( search_type.value() == "terrain" ) {
                     if( here.ter( search_loc ).id().c_str() == cur_search_target ) {
                         target_pos = here.getabs( search_loc );
                         found = true;
                         break;
                     }
                 } else if( search_type.value() == "furniture" ) {
                     if( here.furn( search_loc ).id().c_str() == cur_search_target ||
                         ( !here.furn( search_loc ).id().is_null() && cur_search_target.empty() ) ) {
                         target_pos = here.getabs( search_loc );
                         found = true;
                         break;
                     }
                 } else if( search_type.value() == "trap" ) {
                     if( here.tr_at( search_loc ).id.c_str() == cur_search_target ||
                         ( !here.tr_at( search_loc ).is_null() &&
                           cur_search_target.empty() ) ) {
                         target_pos = here.getabs( search_loc );
                         found = true;
                         break;
                     }
                 } else if( search_type.value() == "monster" ) {
                     Creature *tmp_critter = get_creature_tracker().creature_at( here.getglobal( search_loc ) );
                     if( tmp_critter != nullptr && tmp_critter->is_monster() &&
                         ( tmp_critter->as_monster()->type->id.c_str() == cur_search_target ||
                           cur_search_target.empty() ) ) {
                         target_pos = here.getabs( search_loc );
                         found = true;
                         g->despawn_nonlocal_monsters();
                         break;
                     }
                 } else if( search_type.value() == "npc" ) {
                     for( shared_ptr_fast<npc> &person : overmap_buffer.get_npcs_near( project_to<coords::sm>( abs_ms ),
                             1 ) ) {
                         if( person->pos() == search_loc && ( person->myclass.c_str() == cur_search_target ||
                                                              cur_search_target.empty() ) ) {
                             target_pos = here.getabs( search_loc );
                             found = true;
                             break;
                         }
                     }
                 } else if( search_type.value() == "zone" ) {
                     zone_manager &mgr = zone_manager::get_manager();
                     if( mgr.get_zone_at( here.getglobal( search_loc ), zone_type_id( cur_search_target ) ) ) {
                         target_pos = here.getabs( search_loc );
                         found = true;
                         break;
                     }
                 }
             }
             talker_pos = target_pos;
             if( search_type.value() == "monster" ) {
                 g->despawn_nonlocal_monsters();
             }
             if( !found ) {
                 run_eoc_vector( false_eocs, d );
                 return;
             }
         }
         int max_radius = dov_max_radius.evaluate( d );
         if( max_radius > 0 ) {
             bool found = false;
             int min_radius = dov_min_radius.evaluate( d );
             for( int attempts = 0; attempts < 25; attempts++ ) {
                 target_pos = talker_pos + tripoint( rng( -max_radius, max_radius ), rng( -max_radius, max_radius ),
                                                     0 );
                 if( ( !outdoor_only || here.is_outside( target_pos ) ) &&
                     ( !passable_only || here.passable( here.getlocal( target_pos ) ) ) &&
                     rl_dist( target_pos, talker_pos ) >= min_radius ) {
                     found = true;
                     break;
                 }
             }
             if( !found ) {
                 run_eoc_vector( false_eocs, d );
                 return;
             }
         }
         // move the found value by the adjusts
         target_pos = target_pos + tripoint( dov_x_adjust.evaluate( d ), dov_y_adjust.evaluate( d ), 0 );
         if( z_override ) {
             target_pos = tripoint( target_pos.xy(),
                                    dov_z_adjust.evaluate( d ) );
         } else {
             target_pos = target_pos + tripoint( 0, 0,
                                                 dov_z_adjust.evaluate( d ) );
         }
         write_var_value( type, var_name, &d, target_pos.to_string() );
         run_eoc_vector( true_eocs, d );
     };
 }
References dialogue::actor(), Creature::as_monster(), string_id< T >::c_str(), creature_tracker::creature_at(), dbl_or_var::evaluate(), map::furn(), g, JsonObject::get_bool(), get_creature_tracker(), get_dbl_or_var(), zone_manager::get_manager(), get_map(), JsonObject::get_member(), overmapbuffer::get_npcs_near(), JsonObject::get_object(), mission_util::get_om_terrain_pos(), get_str_or_var(), zone_manager::get_zone_at(), map::getabs(), map::getglobal(), map::getlocal(), JsonObject::has_member(), JsonObject::has_object(), int_id< T >::id(), mtype::id, trap::id, Creature::is_monster(), string_id< T >::is_null(), trap::is_null(), map::is_outside(), load_eoc_vector(), member, overmap_buffer, mission_util::parse_mission_om_target(), map::passable(), map::points_in_radius(), talker::pos(), read_var_info(), rl_dist(), rng(), run_eoc_vector(), map::spawn_monsters(), map::ter(), JsonObject::throw_error(), tripoint::to_string(), map::tr_at(), monster::type, write_var_value(), and tripoint::xy().
f_location_variable_adjust()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable_adjust (const JsonObject & jo, std::string_view member)
Definition at line 3720 of file npctalk.cpp.
 {
     dbl_or_var dov_z_adjust = get_dbl_or_var( jo, "z_adjust", false, 0 );
     dbl_or_var dov_x_adjust = get_dbl_or_var( jo, "x_adjust", false, 0 );
     dbl_or_var dov_y_adjust = get_dbl_or_var( jo, "y_adjust", false, 0 );
     bool z_override = jo.get_bool( "z_override", false );
     bool overmap_tile = jo.get_bool( "overmap_tile", false );
     std::optional<var_info> input_var = read_var_info( jo.get_object( member ) );
     std::optional<var_info> output_var;
     if( jo.has_member( "output_var" ) ) {
         output_var = read_var_info( jo.get_object( "output_var" ) );
     }
     return [input_var, dov_x_adjust, dov_y_adjust, dov_z_adjust, z_override,
                output_var, overmap_tile ]( dialogue & d ) {
         tripoint_abs_ms target_pos = get_tripoint_from_var( input_var, d );
         if( overmap_tile ) {
             target_pos = target_pos + tripoint( dov_x_adjust.evaluate( d ) * coords::map_squares_per(
                                                     coords::omt ), dov_y_adjust.evaluate( d ) * coords::map_squares_per( coords::omt ), 0 );
         } else {
             target_pos = target_pos + tripoint( dov_x_adjust.evaluate( d ), dov_y_adjust.evaluate( d ), 0 );
         }
         if( z_override ) {
             target_pos = tripoint_abs_ms( target_pos.xy(), dov_z_adjust.evaluate( d ) );
         } else {
             target_pos = target_pos + tripoint( 0, 0, dov_z_adjust.evaluate( d ) );
         }
         if( output_var.has_value() ) {
             write_var_value( output_var.value().type, output_var.value().name, &d, target_pos.to_string() );
         } else {
             write_var_value( input_var.value().type, input_var.value().name,   &d, target_pos.to_string() );
         }
     };
 }
References dbl_or_var::evaluate(), JsonObject::get_bool(), get_dbl_or_var(), JsonObject::get_object(), get_tripoint_from_var(), JsonObject::has_member(), coords::map_squares_per(), member, coords::omt, read_var_info(), coords::coord_point_base< Point >::to_string(), write_var_value(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
f_lose_bionic()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_bionic (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 3068 of file npctalk.cpp.
 {
     str_or_var old_bionic = get_str_or_var( jo.get_member( member ), member, true );
     return [is_npc, old_bionic]( dialogue const & d ) {
         d.actor( is_npc )->remove_bionic( bionic_id( old_bionic.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_lose_faction_trust()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_faction_trust (const JsonObject & jo, std::string_view member)
Definition at line 5740 of file npctalk.cpp.
 {
     dbl_or_var dov = get_dbl_or_var( jo, member );
     return [dov]( dialogue & d ) {
         d.actor( true )->get_faction()->trusts_u -= dov.evaluate( d );
     };
 }
References dialogue::actor(), dbl_or_var::evaluate(), get_dbl_or_var(), talker::get_faction(), member, and faction_template::trusts_u.
f_lose_morale()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_morale (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 5723 of file npctalk.cpp.
 {
     str_or_var old_morale = get_str_or_var( jo.get_member( member ), member, true );
     return [is_npc, old_morale]( dialogue const & d ) {
         d.actor( is_npc )->remove_morale( morale_type( old_morale.evaluate( d ) ) );
     };
 }
References dialogue::actor(), abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), member, and talker::remove_morale().
f_make_sound()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 4814 of file npctalk.cpp.
 {
     dbl_or_var volume = get_dbl_or_var( jo, "volume", true );
     bool ambient = jo.get_bool( "ambient", false );
     bool snippet = jo.get_bool( "snippet", false );
     bool same_snippet = jo.get_bool( "same_snippet", false );
     str_or_var snip_id;
     translation_or_var message;
     if( snippet ) {
         snip_id = get_str_or_var( jo.get_member( member ), member, true );
     } else {
         message = get_translation_or_var( jo.get_member( member ), member, true );
     }
     sounds::sound_t type = sounds::sound_t::background;
     std::string type_string = jo.get_string( "type", "background" );
     if( type_string == "background" ) {
         type = sounds::sound_t::background;
     } else if( type_string == "weather" ) {
         type = sounds::sound_t::weather;
     } else if( type_string == "music" ) {
         type = sounds::sound_t::music;
     } else if( type_string == "movement" ) {
         type = sounds::sound_t::movement;
     } else if( type_string == "speech" ) {
         type = sounds::sound_t::speech;
     } else if( type_string == "electronic_speech" ) {
         type = sounds::sound_t::electronic_speech;
     } else if( type_string == "activity" ) {
         type = sounds::sound_t::activity;
     } else if( type_string == "destructive_activity" ) {
         type = sounds::sound_t::destructive_activity;
     } else if( type_string == "alarm" ) {
         type = sounds::sound_t::alarm;
     } else if( type_string == "combat" ) {
         type = sounds::sound_t::combat;
     } else if( type_string == "alert" ) {
         type = sounds::sound_t::alert;
     } else if( type_string == "order" ) {
         type = sounds::sound_t::order;
     } else {
         jo.throw_error( "Invalid message type." );
     }
     std::optional<var_info> target_var;
     if( jo.has_member( "target_var" ) ) {
         target_var = read_var_info( jo.get_object( "target_var" ) );
     }
     return [is_npc, snip_id, message, volume, ambient, type, target_var, snippet,
             same_snippet]( dialogue & d ) {
         tripoint_abs_ms target_pos = get_tripoint_from_var( target_var, d );
         std::string translated_message;
         if( snippet ) {
             if( same_snippet ) {
                 talker *target = d.actor( !is_npc );
                 std::string sid = target->get_value( snip_id.evaluate( d ) + "_snippet_id" );
                 if( sid.empty() ) {
                     sid = SNIPPET.random_id_from_category( snip_id.evaluate( d ) ).c_str();
                     target->set_value( snip_id.evaluate( d ) + "_snippet_id", sid );
                 }
                 translated_message = SNIPPET.expand( SNIPPET.get_snippet_by_id( snippet_id( sid ) ).value_or(
                         translation() ).translated() );
             } else {
                 translated_message = SNIPPET.expand( SNIPPET.random_from_category( snip_id.evaluate( d ) ).value_or(
                         translation() ).translated() );
             }
         } else {
             translated_message = message.evaluate( d );
         }
         sounds::sound( get_map().getlocal( target_pos ), volume.evaluate( d ), type, translated_message,
                        ambient );
     };
 }
References sounds::activity, dialogue::actor(), sounds::alarm, sounds::alert, sounds::background, string_id< T >::c_str(), sounds::combat, sounds::destructive_activity, sounds::electronic_speech, abstract_str_or_var< T >::evaluate(), snippet_library::expand(), JsonObject::get_bool(), get_dbl_or_var(), get_map(), JsonObject::get_member(), JsonObject::get_object(), snippet_library::get_snippet_by_id(), get_str_or_var(), JsonObject::get_string(), get_translation_or_var(), get_tripoint_from_var(), talker::get_value(), JsonObject::has_member(), member, mapgen_defer::message, sounds::movement, sounds::music, sounds::order, snippet_library::random_from_category(), snippet_library::random_id_from_category(), read_var_info(), talker::set_value(), SNIPPET, sounds::sound(), sounds::speech, JsonObject::throw_error(), and sounds::weather.
f_map_run_item_eocs()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 5330 of file npctalk.cpp.
 {
     str_or_var option = get_str_or_var( jo.get_member( member ), member );
     std::vector<effect_on_condition_id> true_eocs = load_eoc_vector( jo, "true_eocs" );
     std::vector<effect_on_condition_id> false_eocs = load_eoc_vector( jo, "false_eocs" );
     std::vector <item_search_data> data;
     for( const JsonValue &search_data_jo : jo.get_array( "search_data" ) ) {
         data.emplace_back( search_data_jo );
     }
     translation_or_var title;
     if( jo.has_member( "title" ) ) {
         title = get_translation_or_var( jo.get_member( "title" ), "title", true );
     } else {
         title.str_val = translation();
     }
     std::optional<var_info> loc_var;
     if( jo.has_object( "loc" ) ) {
         loc_var = read_var_info( jo.get_object( "loc" ) );
     }
     dbl_or_var dov_min_radius = get_dbl_or_var( jo, "min_radius", false, 0 );
     dbl_or_var dov_max_radius = get_dbl_or_var( jo, "max_radius", false, 0 );
     return [is_npc, option, true_eocs, false_eocs, data, loc_var, dov_min_radius, dov_max_radius,
             title]( dialogue & d ) {
         tripoint_abs_ms target_location = get_tripoint_from_var( loc_var, d );
         std::vector<item_location> items;
         map &here = get_map();
         tripoint center = here.getlocal( target_location );
         int max_radius = dov_max_radius.evaluate( d );
         int min_radius = dov_min_radius.evaluate( d );
         for( const tripoint &pos : here.points_in_radius( center, max_radius ) ) {
             if( rl_dist( center, pos ) >= min_radius && here.inbounds( pos ) ) {
                 for( item &it : here.i_at( pos ) ) {
                     items.emplace_back( map_cursor( pos ), &it );
                 }
             }
         }
         Character *guy = d.actor( is_npc )->get_character();
         guy = guy ? guy : &get_player_character();
         const auto f = [d, guy, title, center, min_radius,
            max_radius]( const item_location_filter & filter ) {
             inventory_filter_preset preset( filter );
             inventory_pick_selector inv_s( *guy, preset );
             inv_s.set_title( title.evaluate( d ) );
             inv_s.set_display_stats( false );
             inv_s.clear_items();
             for( const tripoint &pos : get_map().points_in_radius( center, max_radius ) ) {
                 if( rl_dist( center, pos ) >= min_radius ) {
                     inv_s.add_map_items( pos );
                 }
             }
             if( inv_s.empty() ) {
                 popup( _( "You don't have the necessary item at hand." ), PF_GET_KEY );
                 return item_location();
             }
             return inv_s.execute();
         };
         const item_menu_mul f_mul = [d, guy, title, center, min_radius,
            max_radius]( const item_location_filter & filter ) {
             inventory_filter_preset preset( filter );
             inventory_multiselector inv_s( *guy, preset );
             inv_s.set_title( title.evaluate( d ) );
             inv_s.set_display_stats( false );
             inv_s.clear_items();
             for( const tripoint &pos : get_map().points_in_radius( center, max_radius ) ) {
                 if( rl_dist( center, pos ) >= min_radius ) {
                     inv_s.add_map_items( pos );
                 }
             }
             if( inv_s.empty() ) {
                 popup( _( "You don't have the necessary item at hand." ), PF_GET_KEY );
                 return drop_locations();
             }
             return inv_s.execute();
         };
         run_item_eocs( d, is_npc, items, option.evaluate( d ), true_eocs, false_eocs, data,
                        f, f_mul );
     };
 }
References _, dialogue::actor(), inventory_selector::add_map_items(), center, inventory_selector::clear_items(), inventory_selector::empty(), dbl_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), inventory_pick_selector::execute(), inventory_multiselector::execute(), filter, JsonObject::get_array(), talker::get_character(), get_dbl_or_var(), get_map(), JsonObject::get_member(), JsonObject::get_object(), get_player_character(), get_str_or_var(), get_translation_or_var(), get_tripoint_from_var(), map::getlocal(), JsonObject::has_member(), JsonObject::has_object(), map::i_at(), map::inbounds(), load_eoc_vector(), member, PF_GET_KEY, points_in_radius(), map::points_in_radius(), popup(), math_opers::pos(), read_var_info(), rl_dist(), run_item_eocs(), inventory_selector::set_display_stats(), inventory_selector::set_title(), and music::title.
f_mapgen_update()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update (const JsonObject & jo, std::string_view member)
Definition at line 3839 of file npctalk.cpp.
 {
     mission_target_params target_params = mission_util::parse_mission_om_target( jo );
     std::vector<str_or_var> update_ids;
     duration_or_var dov_time_in_future = get_duration_or_var( jo, "time_in_future", false,
                                          0_seconds );
     if( jo.has_string( member ) ) {
         update_ids.emplace_back( get_str_or_var( jo.get_member( member ), member ) );
     } else if( jo.has_array( member ) ) {
         for( JsonValue jv : jo.get_array( member ) ) {
             update_ids.emplace_back( get_str_or_var( jv, member ) );
         }
     }
     std::optional<var_info> target_var;
     if( jo.has_member( "target_var" ) ) {
         target_var = read_var_info( jo.get_object( "target_var" ) );
     }
     str_or_var key;
     if( jo.has_member( "key" ) ) {
         key = get_str_or_var( jo.get_member( "key" ), "key", false, "" );
     } else {
         key.str_val = "";
     }
     return [target_params, update_ids, target_var, dov_time_in_future, key]( dialogue & d ) {
         tripoint_abs_omt omt_pos;
         if( target_var.has_value() ) {
             const tripoint_abs_ms abs_ms( get_tripoint_from_var( target_var, d ) );
             omt_pos = project_to<coords::omt>( abs_ms );
         } else {
             mission_target_params update_params = target_params;
             if( d.has_beta ) {
                 update_params.guy = d.actor( true )->get_npc();
             }
             omt_pos = mission_util::get_om_terrain_pos( update_params, d );
         }
         time_duration future = dov_time_in_future.evaluate( d );
         if( future > 0_seconds ) {
             time_point tif = calendar::turn + future + 1_seconds;
             //Timed events happen before the player turn and eocs are during so we add a second here to sync them up using the same variable
             for( const str_or_var &mapgen_update_id : update_ids ) {
                 get_timed_events().add( timed_event_type::UPDATE_MAPGEN, tif, -1, project_to<coords::ms>( omt_pos ),
                                         0, mapgen_update_id.evaluate( d ), key.evaluate( d ) );
             }
         } else {
             for( const str_or_var &mapgen_update_id : update_ids ) {
                 run_mapgen_update_func( update_mapgen_id( mapgen_update_id.evaluate( d ) ), omt_pos, {},
                                         d.actor( d.has_beta )->selected_mission() );
                 set_queued_points();
             }
             get_map().invalidate_map_cache( omt_pos.z() );
         }
     };
 }
References dialogue::actor(), timed_event_manager::add(), duration_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), JsonObject::get_array(), get_duration_or_var(), get_map(), JsonObject::get_member(), talker::get_npc(), JsonObject::get_object(), mission_util::get_om_terrain_pos(), get_str_or_var(), get_timed_events(), get_tripoint_from_var(), mission_target_params::guy, JsonObject::has_array(), dialogue::has_beta, JsonObject::has_member(), JsonObject::has_string(), map::invalidate_map_cache(), member, mission_util::parse_mission_om_target(), read_var_info(), run_mapgen_update_func(), talker::selected_mission(), set_queued_points(), abstract_str_or_var< T >::str_val, calendar::turn, UPDATE_MAPGEN, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
f_math()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_math (const JsonObject & jo, std::string_view member)
Definition at line 4786 of file npctalk.cpp.
 {
     eoc_math math;
     math.from_json( jo, member, eoc_math::type_t::assign );
     return [math = std::move( math )]( dialogue & d ) {
         return math.act( d );
     };
 }
References eoc_math::act(), eoc_math::assign, eoc_math::from_json(), and member.
f_message()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 4173 of file npctalk.cpp.
 {
     const bool snippet = jo.get_bool( "snippet", false );
     str_or_var snip_id;
     translation_or_var message;
     if( snippet ) {
         snip_id = get_str_or_var( jo.get_member( member ), member );
     } else {
         message = get_translation_or_var( jo.get_member( member ), member );
     }
     const bool same_snippet = jo.get_bool( "same_snippet", false );
     const bool outdoor_only = jo.get_bool( "outdoor_only", false );
     const bool sound = jo.get_bool( "sound", false );
     const bool popup_msg = jo.get_bool( "popup", false );
     const bool popup_w_interrupt_query_msg = jo.get_bool( "popup_w_interrupt_query", false );
     str_or_var interrupt_type;
     if( jo.has_member( "interrupt_type" ) ) {
         interrupt_type = get_str_or_var( jo.get_member( "interrupt_type" ), "interrupt_type", true );
     } else {
         interrupt_type.str_val = "default";
     }
     const bool global = member == "message";
     str_or_var type_string;
     if( jo.has_member( "type" ) ) {
         type_string = get_str_or_var( jo.get_member( "type" ), "type", true );
     } else {
         type_string.str_val = "neutral";
     }
     return [snip_id, message, outdoor_only, sound, snippet, same_snippet, type_string,
                      popup_msg, popup_w_interrupt_query_msg, interrupt_type, global, is_npc]
     ( dialogue const & d ) {
         Character *target = d.actor( is_npc )->get_character();
         if( global ) {
             target = &get_player_character();
         }
         if( !target || target->is_npc() ) {
             return;
         }
         game_message_type type = m_neutral;
         if( type_string.evaluate( d ) == "good" ) {
             type = m_good;
         } else if( type_string.evaluate( d ) == "neutral" ) {
             type = m_neutral;
         } else if( type_string.evaluate( d ) == "bad" ) {
             type = m_bad;
         } else if( type_string.evaluate( d ) == "mixed" ) {
             type = m_mixed;
         } else if( type_string.evaluate( d ) == "warning" ) {
             type = m_warning;
         } else if( type_string.evaluate( d ) == "info" ) {
             type = m_info;
         } else if( type_string.evaluate( d ) == "debug" ) {
             type = m_debug;
         } else if( type_string.evaluate( d ) == "headshot" ) {
             type = m_headshot;
         } else if( type_string.evaluate( d ) == "critical" ) {
             type = m_critical;
         } else if( type_string.evaluate( d ) == "grazing" ) {
             type = m_grazing;
         } else {
             debugmsg( "Invalid message type." );
         }
         std::string translated_message;
         if( snippet ) {
             if( same_snippet ) {
                 talker *target = d.actor( !is_npc );
                 std::string sid = target->get_value( snip_id.evaluate( d ) + "_snippet_id" );
                 if( sid.empty() ) {
                     sid = SNIPPET.random_id_from_category( snip_id.evaluate( d ) ).c_str();
                     target->set_value( snip_id.evaluate( d ) + "_snippet_id", sid );
                 }
                 translated_message = SNIPPET.expand( SNIPPET.get_snippet_by_id( snippet_id( sid ) ).value_or(
                         translation() ).translated() );
             } else {
                 translated_message = SNIPPET.expand( SNIPPET.random_from_category( snip_id.evaluate( d ) ).value_or(
                         translation() ).translated() );
             }
         } else {
             translated_message = message.evaluate( d );
         }
         std::unique_ptr<talker> default_talker = get_talker_for( get_player_character() );
         talker &alpha = d.has_alpha ? *d.actor( false ) : *default_talker;
         talker &beta = d.has_beta ? *d.actor( true ) : *default_talker;
         parse_tags( translated_message, alpha, beta, d );
         if( sound ) {
             bool display = false;
             map &here = get_map();
             if( !target->has_effect( effect_sleep ) && !target->is_deaf() ) {
                 if( !outdoor_only || here.get_abs_sub().z() >= 0 ||
                     one_in( std::max( roll_remainder( 2.0f * here.get_abs_sub().z() / target->hearing_ability() ),
                                       1 ) ) ) {
                     display = true;
                 }
             }
             if( !display ) {
                 return;
             }
         }
         if( popup_msg ) {
             popup( translated_message );
             g->cancel_activity_or_ignore_query( distraction_type::eoc, "" );
         }
         if( popup_w_interrupt_query_msg ) {
             if( interrupt_type.evaluate( d ) == "portal_storm_popup" ) {
                 g->portal_storm_query( distraction_type::portal_storm_popup,
                                        translated_message );
             } else if( interrupt_type.evaluate( d ) == "default" ) {
                 debugmsg( "Interrupt query called in json without proper interrupt type." );
             }
             // Would probably need an else-if for every possible distraction type, like this:
             //else if (interrupt_type == "hostile_spotted_near"){
             //    g->cancel_activity_or_ignore_query(distraction_type::hostile_spotted_near, "sample message");
             //}
             // I leave this to contributors who might actually wish to implement such interrupts,
             // so as to not overcomplicate the code.
         } else {
             target->add_msg_if_player( type, translated_message );
         }
     };
 }
References dialogue::actor(), Character::add_msg_if_player(), string_id< T >::c_str(), debugmsg, effect_sleep, eoc, abstract_str_or_var< T >::evaluate(), snippet_library::expand(), g, map::get_abs_sub(), JsonObject::get_bool(), talker::get_character(), get_map(), JsonObject::get_member(), get_player_character(), snippet_library::get_snippet_by_id(), get_str_or_var(), get_talker_for(), get_translation_or_var(), talker::get_value(), global, dialogue::has_alpha, dialogue::has_beta, Creature::has_effect(), JsonObject::has_member(), Character::hearing_ability(), Character::is_deaf(), Character::is_npc(), m_bad, m_critical, m_debug, m_good, m_grazing, m_headshot, m_info, m_mixed, m_neutral, m_warning, max(), member, mapgen_defer::message, one_in(), parse_tags(), popup(), portal_storm_popup, snippet_library::random_from_category(), snippet_library::random_id_from_category(), roll_remainder(), talker::set_value(), SNIPPET, abstract_str_or_var< T >::str_val, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
f_mod_healthy()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mod_healthy (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 4435 of file npctalk.cpp.
 {
     dbl_or_var dov_amount = get_dbl_or_var( jo, member );
     dbl_or_var dov_cap = get_dbl_or_var( jo, "cap" );
     return [is_npc, dov_amount, dov_cap]( dialogue & d ) {
         d.actor( is_npc )->mod_daily_health( dov_amount.evaluate( d ),
                                              dov_cap.evaluate( d ) );
     };
 }
References dialogue::actor(), dbl_or_var::evaluate(), get_dbl_or_var(), member, and talker::mod_daily_health().
f_mutate()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 3021 of file npctalk.cpp.
 {
     dbl_or_var highest_cat = get_dbl_or_var( jo, member, true, 0 );
     const bool use_vitamins = jo.get_bool( "use_vitamins", true );
     return [is_npc, highest_cat, use_vitamins]( dialogue & d ) {
         d.actor( is_npc )->mutate( highest_cat.evaluate( d ), use_vitamins );
     };
 }
References dbl_or_var::evaluate(), JsonObject::get_bool(), get_dbl_or_var(), and member.
f_mutate_category()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate_category (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 3031 of file npctalk.cpp.
 {
     str_or_var mut_cat = get_str_or_var( jo.get_member( member ), member, true, "" );
     const bool use_vitamins = jo.get_bool( "use_vitamins", true );
     return [is_npc, mut_cat, use_vitamins]( dialogue const & d ) {
         d.actor( is_npc )->mutate_category( mutation_category_id( mut_cat.evaluate( d ) ), use_vitamins );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_bool(), JsonObject::get_member(), get_str_or_var(), and member.
f_mutate_towards()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate_towards (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 3041 of file npctalk.cpp.
 {
     str_or_var trait = get_str_or_var( jo.get_member( member ), member, true, "" );
     str_or_var mut_cat;
     if( jo.has_member( "category" ) ) {
         mut_cat = get_str_or_var( jo.get_member( "category" ), "category", false, "" );
     } else {
         mut_cat.str_val = "";
     }
     const bool use_vitamins = jo.get_bool( "use_vitamins", true );
     return [is_npc, trait, mut_cat, use_vitamins]( dialogue const & d ) {
         d.actor( is_npc )->mutate_towards( trait_id( trait.evaluate( d ) ),
                                            mutation_category_id( mut_cat.evaluate( d ) ), use_vitamins );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_bool(), JsonObject::get_member(), get_str_or_var(), JsonObject::has_member(), member, and abstract_str_or_var< T >::str_val.
f_next_weather()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_next_weather ()
Definition at line 4575 of file npctalk.cpp.
 {
     return []( dialogue const &/* d */ ) {
         get_weather().set_nextweather( calendar::turn );
     };
 }
References get_weather(), weather_manager::set_nextweather(), and calendar::turn.
Referenced by talk_effect_t::parse_string_effect().
f_npc_aim_rule()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_aim_rule (const JsonObject & jo, std::string_view member)
Definition at line 3508 of file npctalk.cpp.
 {
     str_or_var rule = get_str_or_var( jo.get_member( member ), member, true );
     return [rule]( dialogue const & d ) {
         d.actor( true )->set_ai_rule( "aim_rule", rule.evaluate( d ) );
     };
 }
References dialogue::actor(), abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), member, and talker::set_ai_rule().
f_npc_cbm_recharge_rule()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_cbm_recharge_rule (const JsonObject & jo, std::string_view member)
Definition at line 3525 of file npctalk.cpp.
 {
     str_or_var rule = get_str_or_var( jo.get_member( member ), member, true );
     return [rule]( dialogue const & d ) {
         d.actor( true )->set_ai_rule( "cbm_recharge_rule", rule.evaluate( d ) );
     };
 }
References dialogue::actor(), abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), member, and talker::set_ai_rule().
f_npc_cbm_reserve_rule()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_cbm_reserve_rule (const JsonObject & jo, std::string_view member)
Definition at line 3516 of file npctalk.cpp.
 {
     str_or_var rule = get_str_or_var( jo.get_member( member ), member, true );
     return [rule]( dialogue const & d ) {
         d.actor( true )->set_ai_rule( "cbm_reserve_rule", rule.evaluate( d ) );
     };
 }
References dialogue::actor(), abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), member, and talker::set_ai_rule().
f_npc_change_class()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_change_class (const JsonObject & jo, std::string_view member)
Definition at line 3437 of file npctalk.cpp.
 {
     str_or_var class_name = get_str_or_var( jo.get_member( member ), member, true );
     return [class_name]( dialogue const & d ) {
         d.actor( true )->set_class( npc_class_id( class_name.evaluate( d ) ) );
     };
 }
References dialogue::actor(), abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), member, and talker::set_class().
f_npc_change_faction()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_change_faction (const JsonObject & jo, std::string_view member)
Definition at line 3429 of file npctalk.cpp.
 {
     str_or_var faction_name = get_str_or_var( jo.get_member( member ), member, true );
     return [faction_name]( dialogue const & d ) {
         d.actor( true )->set_fac( faction_id( faction_name.evaluate( d ) ) );
     };
 }
References dialogue::actor(), abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), member, and talker::set_fac().
f_npc_engagement_rule()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_engagement_rule (const JsonObject & jo, std::string_view member)
Definition at line 3499 of file npctalk.cpp.
 {
     str_or_var rule = get_str_or_var( jo.get_member( member ), member, true );
     return [rule]( dialogue const & d ) {
         d.actor( true )->set_ai_rule( "engagement_rule", rule.evaluate( d ) );
     };
 }
References dialogue::actor(), abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), member, and talker::set_ai_rule().
f_npc_first_topic()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_first_topic (const JsonObject & jo, std::string_view member)
Definition at line 4165 of file npctalk.cpp.
 {
     str_or_var chat_topic = get_str_or_var( jo.get_member( member ), member, true );
     return [chat_topic]( dialogue const & d ) {
         d.actor( true )->set_first_topic( chat_topic.evaluate( d ) );
     };
 }
References dialogue::actor(), abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), member, and talker::set_first_topic().
f_npc_gets_item()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_gets_item (bool to_use)
Definition at line 4092 of file npctalk.cpp.
 {
     return [to_use]( dialogue const & d ) {
         d.reason = d.actor( true )->give_item_to( to_use );
     };
 }
References dialogue::actor(), talker::give_item_to(), and dialogue::reason.
Referenced by talk_effect_t::parse_string_effect().
f_npc_goal()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_goal (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 3944 of file npctalk.cpp.
 {
     mission_target_params dest_params = mission_util::parse_mission_om_target( jo.get_object(
                                             member ) );
     std::vector<effect_on_condition_id> true_eocs = load_eoc_vector( jo, "true_eocs" );
     std::vector<effect_on_condition_id> false_eocs = load_eoc_vector( jo, "false_eocs" );
     return [dest_params, true_eocs, false_eocs, is_npc]( dialogue & d ) {
         npc *guy = d.actor( is_npc )->get_npc();
         if( guy ) {
             tripoint_abs_omt destination = mission_util::get_om_terrain_pos( dest_params, d );
             guy->goal = destination;
             guy->omt_path = overmap_buffer.get_travel_path( guy->global_omt_location(), guy->goal,
                             overmap_path_params::for_npc() );
             if( destination == tripoint_abs_omt() || destination == overmap::invalid_tripoint ||
                 guy->omt_path.empty() ) {
                 guy->goal = npc::no_goal_point;
                 guy->omt_path.clear();
                 run_eoc_vector( false_eocs, d );
                 return;
             }
             guy->set_mission( NPC_MISSION_TRAVELLING );
             guy->guard_pos = std::nullopt;
             guy->set_attitude( NPCATT_NULL );
             run_eoc_vector( true_eocs, d );
             return;
         }
         run_eoc_vector( false_eocs, d );
     };
 }
References dialogue::actor(), overmap_path_params::for_npc(), talker::get_npc(), JsonObject::get_object(), mission_util::get_om_terrain_pos(), overmapbuffer::get_travel_path(), Creature::global_omt_location(), npc::goal, npc::guard_pos, overmap::invalid_tripoint, load_eoc_vector(), member, npc::no_goal_point, NPC_MISSION_TRAVELLING, NPCATT_NULL, Character::omt_path, overmap_buffer, mission_util::parse_mission_om_target(), run_eoc_vector(), npc::set_attitude(), and npc::set_mission().
f_offer_mission()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_offer_mission (const JsonObject & jo, std::string_view member)
Definition at line 4688 of file npctalk.cpp.
 {
     std::vector<std::string> mission_names;
     if( jo.has_array( member ) ) {
         for( const std::string mission_name : jo.get_array( member ) ) {
             mission_names.push_back( mission_name );
         }
     } else if( jo.has_string( member ) ) {
         mission_names.push_back( jo.get_string( std::string( member ) ) );
     } else {
         jo.throw_error( "Invalid input for set_offer_mission" );
     }
     return [mission_names]( dialogue const & d ) {
         // assume that the alpha is the npc if there isn't a beta
         npc *p = d.actor( d.has_beta )->get_npc();
         if( p ) {
             for( const std::string &mission_name : mission_names ) {
                 p->add_new_mission( mission::reserve_new( mission_type_id( mission_name ), p->getID() ) );
             }
         }
     };
 }
References dialogue::actor(), npc::add_new_mission(), JsonObject::get_array(), talker::get_npc(), JsonObject::get_string(), Character::getID(), JsonObject::has_array(), dialogue::has_beta, JsonObject::has_string(), member, mission::reserve_new(), and JsonObject::throw_error().
f_open_dialogue()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue (const JsonObject & jo, std::string_view member)
Definition at line 4321 of file npctalk.cpp.
 {
     std::vector<effect_on_condition_id> true_eocs;
     std::vector<effect_on_condition_id> false_eocs;
     str_or_var topic;
     bool has_member = false;
     if( jo.has_object( member ) ) {
         has_member = true;
         JsonObject innerJo = jo.get_object( member );
         true_eocs = load_eoc_vector( innerJo, "true_eocs" );
         false_eocs = load_eoc_vector( innerJo, "false_eocs" );
         topic = get_str_or_var( innerJo.get_member( "topic" ), "topic" );
     }
     return [true_eocs, false_eocs, topic, has_member]( dialogue const & d ) {
         std::string actual_topic;
         if( has_member ) {
             actual_topic = topic.evaluate( d );
         }
         if( !d.actor( false )->get_character()->is_avatar() ) { //only open a dialog if the avatar is alpha
             run_eoc_vector( false_eocs, d );
             return;
         } else if( !actual_topic.empty() ) {
             get_avatar().talk_to( get_talker_for( std::vector<std::string> { actual_topic } ), false, false,
                                   true );
         } else if( d.actor( true )->get_character() != nullptr ) {
             get_avatar().talk_to( get_talker_for( d.actor( true )->get_character() ) );
         } else if( d.actor( true )->get_creature() != nullptr ) {
             get_avatar().talk_to( get_talker_for( d.actor( true )->get_creature() ) );
         } else if( d.actor( true )->get_monster() != nullptr ) {
             get_avatar().talk_to( get_talker_for( d.actor( true )->get_monster() ) );
         } else if( d.actor( true )->get_item() != nullptr ) {
             get_avatar().talk_to( get_talker_for( d.actor( true )->get_item() ) );
         } else if( d.actor( true )->get_computer() != nullptr ) {
             get_avatar().talk_to( get_talker_for( d.actor( true )->get_computer() ), false, true );
         }
         run_eoc_vector( true_eocs, d );
     };
 }
References dialogue::actor(), abstract_str_or_var< T >::evaluate(), get_avatar(), talker::get_character(), talker::get_computer(), talker::get_creature(), talker::get_item(), JsonObject::get_member(), talker::get_monster(), JsonObject::get_object(), get_str_or_var(), get_talker_for(), JsonObject::has_object(), Creature::is_avatar(), load_eoc_vector(), member, run_eoc_vector(), and avatar::talk_to().
Referenced by talk_effect_t::parse_string_effect().
f_place_override()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_place_override (const JsonObject & jo, std::string_view member)
Definition at line 3821 of file npctalk.cpp.
 {
     translation_or_var new_place = get_translation_or_var( jo.get_member( member ), member );
     duration_or_var dov_length = get_duration_or_var( jo, "length", true );
     str_or_var key;
     if( jo.has_member( "key" ) ) {
         key = get_str_or_var( jo.get_member( "key" ), "key", false, "" );
     } else {
         key.str_val = "";
     }
     return [new_place, dov_length, key]( dialogue & d ) {
         get_timed_events().add( timed_event_type::OVERRIDE_PLACE,
                                 calendar::turn + dov_length.evaluate( d ) + 1_seconds,
                                 //Timed events happen before the player turn and eocs are during so we add a second here to sync them up using the same variable
                                 -1, tripoint_abs_ms( tripoint_zero ), -1, new_place.evaluate( d ), key.evaluate( d ) );
     };
 }
References timed_event_manager::add(), duration_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), get_duration_or_var(), JsonObject::get_member(), get_str_or_var(), get_timed_events(), get_translation_or_var(), JsonObject::has_member(), member, OVERRIDE_PLACE, abstract_str_or_var< T >::str_val, tripoint_zero, and calendar::turn.
f_prevent_death()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_prevent_death (bool is_npc)
Definition at line 4556 of file npctalk.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         Character *ch = d.actor( is_npc )->get_character();
         if( ch ) {
             ch->prevent_death();
         }
     };
 }
References dialogue::actor(), talker::get_character(), and Character::prevent_death().
Referenced by talk_effect_t::parse_string_effect().
f_queue_eoc_with()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eoc_with (const JsonObject & jo, std::string_view member)
Definition at line 5459 of file npctalk.cpp.
 {
     effect_on_condition_id eoc = effect_on_conditions::load_inline_eoc( jo.get_member( member ), "" );
     std::unordered_map<std::string, str_translation_or_var> context;
     if( jo.has_object( "variables" ) ) {
         const JsonObject &variables = jo.get_object( "variables" );
         for( const JsonMember &jv : variables ) {
             context["npctalk_var_" + jv.name()] = get_str_translation_or_var( jv, jv.name(), true );
         }
     }
     duration_or_var dov_time_in_future = get_duration_or_var( jo, "time_in_future", false,
                                          0_seconds );
     return [dov_time_in_future, eoc, context]( dialogue & d ) {
         time_duration time_in_future = dov_time_in_future.evaluate( d );
         if( eoc->type == eoc_type::ACTIVATION ) {
             std::unordered_map<std::string, std::string> passed_variables;
             for( const auto &val : context ) {
                 passed_variables[val.first] = val.second.evaluate( d );
             }
             Character *alpha = d.has_alpha ? d.actor( false )->get_character() : nullptr;
             if( alpha ) {
                 effect_on_conditions::queue_effect_on_condition( time_in_future, eoc, *alpha, passed_variables );
             } else if( eoc->global ) {
                 effect_on_conditions::queue_effect_on_condition( time_in_future, eoc, get_player_character(),
                         passed_variables );
             }
             // If the target is a monster or item and the eoc is non global it won't be queued and will silently "fail"
             // this is so monster attacks against other monsters won't give error messages.
         } else {
             debugmsg( "Cannot queue a non activation effect_on_condition.  %s", d.get_callstack() );
         }
     };
 }
References ACTIVATION, dialogue::actor(), context, debugmsg, eoc, duration_or_var::evaluate(), dialogue::get_callstack(), talker::get_character(), get_duration_or_var(), JsonObject::get_member(), JsonObject::get_object(), get_player_character(), get_str_translation_or_var(), dialogue::has_alpha, JsonObject::has_object(), effect_on_conditions::load_inline_eoc(), member, and effect_on_conditions::queue_effect_on_condition().
f_queue_eocs()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eocs (const JsonObject & jo, std::string_view member)
Definition at line 5440 of file npctalk.cpp.
 {
     std::vector<eoc_entry> eocs_entries = load_eoc_vector_id_and_var( jo, member );
     if( eocs_entries.empty() ) {
         jo.throw_error( "Invalid input for queue_eocs" );
     }
     duration_or_var dov_time_in_future = get_duration_or_var( jo, "time_in_future", false,
                                          0_seconds );
     return [dov_time_in_future, eocs_entries]( dialogue & d ) {
         time_duration time_in_future = dov_time_in_future.evaluate( d );
         for( const eoc_entry &entry : eocs_entries ) {
             effect_on_condition_id eoc_id =
                 entry.var ? effect_on_condition_id( entry.var->evaluate( d ) ) : entry.id;
             process_eoc( eoc_id, d, time_in_future );
         };
     };
 }
References duration_or_var::evaluate(), get_duration_or_var(), load_eoc_vector_id_and_var(), member, process_eoc(), and JsonObject::throw_error().
f_remove_active_mission()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_active_mission (const JsonObject & jo, std::string_view member)
Definition at line 4671 of file npctalk.cpp.
 {
     str_or_var mission_name = get_str_or_var( jo.get_member( member ), member, true );
     return [mission_name]( dialogue const & d ) {
         avatar &player_character = get_avatar();
         const mission_type_id &mission_type = mission_type_id( mission_name.evaluate( d ) );
         std::vector<mission *> missions = player_character.get_active_missions();
         for( mission *mission : missions ) {
             if( mission->mission_id() == mission_type ) {
                 player_character.remove_active_mission( *mission );
                 break;
             }
         }
     };
 }
References abstract_str_or_var< T >::evaluate(), avatar::get_active_missions(), get_avatar(), JsonObject::get_member(), get_str_or_var(), member, mission::mission_id(), and avatar::remove_active_mission().
f_remove_effect()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_effect (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 2939 of file npctalk.cpp.
 {
     str_or_var old_effect = get_str_or_var( jo.get_member( member ), member, true );
     str_or_var target;
     if( jo.has_member( "target_part" ) ) {
         target = get_str_or_var( jo.get_member( "target_part" ), "target_part", false, "bp_null" );
     } else {
         target.str_val = "bp_null";
     }
     return [is_npc, old_effect, target]( dialogue const & d ) {
         d.actor( is_npc )->remove_effect( efftype_id( old_effect.evaluate( d ) ), target.evaluate( d ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), JsonObject::has_member(), member, and abstract_str_or_var< T >::str_val.
f_remove_item_with()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_item_with (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 3403 of file npctalk.cpp.
 {
     str_or_var item_name = get_str_or_var( jo.get_member( member ), member, true );
     return [is_npc, item_name]( dialogue const & d ) {
         itype_id item_id = itype_id( item_name.evaluate( d ) );
         d.actor( is_npc )->remove_items_with( [item_id]( const item & it ) {
             return it.typeId() == item_id;
         } );
     };
 }
References dialogue::actor(), JsonObject::get_member(), get_str_or_var(), tname::item_name(), member, talker::remove_items_with(), and item::typeId().
f_remove_trait()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_trait (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 2994 of file npctalk.cpp.
 {
     str_or_var old_trait = get_str_or_var( jo.get_member( member ), member, true );
     return [is_npc, old_trait]( dialogue const & d ) {
         d.actor( is_npc )->unset_mutation( trait_id( old_trait.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_remove_var()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_var (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 3101 of file npctalk.cpp.
 {
     dbl_or_var empty;
     const std::string var_name = get_talk_varname( jo, member, false, empty );
     return [is_npc, var_name]( dialogue const & d ) {
         d.actor( is_npc )->remove_value( var_name );
     };
 }
References get_talk_varname(), and member.
f_revert_location()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location (const JsonObject & jo, std::string_view member)
Definition at line 3904 of file npctalk.cpp.
 {
     duration_or_var dov_time_in_future = get_duration_or_var( jo, "time_in_future", true );
     str_or_var key;
     if( jo.has_member( "key" ) ) {
         key = get_str_or_var( jo.get_member( "key" ), "key", false, "" );
     } else {
         key.str_val = "";
     }
     std::optional<var_info> target_var = read_var_info( jo.get_object( member ) );
     return [target_var, dov_time_in_future, key]( dialogue & d ) {
         const tripoint_abs_ms abs_ms( get_tripoint_from_var( target_var, d ) );
         tripoint_abs_omt omt_pos = project_to<coords::omt>( abs_ms );
         time_point tif = calendar::turn + dov_time_in_future.evaluate( d ) + 1_seconds;
         // Timed events happen before the player turn and eocs are during so we add a second here to sync them up using the same variable
         // maptile is 4 submaps so queue up 4 submap reverts
         const tripoint_abs_sm revert_sm_base = project_to<coords::sm>( omt_pos );
         for( int x = 0; x < 2; x++ ) {
             for( int y = 0; y < 2; y++ ) {
                 const tripoint_abs_sm revert_sm = revert_sm_base + point( x, y );
                 submap *sm = MAPBUFFER.lookup_submap( revert_sm );
                 if( sm == nullptr ) {
                     tinymap tm;
                     // This creates the submaps if they didn't already exist.
                     // Note that all four submaps are loaded/created by this
                     // call, so the submap lookup can fail at most once.
                     tm.load( omt_pos, true );
                     sm = MAPBUFFER.lookup_submap( revert_sm );
                 }
                 get_timed_events().add( timed_event_type::REVERT_SUBMAP, tif, -1,
                                         project_to<coords::ms>( revert_sm ), 0, "",
                                         sm->get_revert_submap(), key.evaluate( d ) );
             }
         }
         get_map().invalidate_map_cache( omt_pos.z() );
     };
 }
References timed_event_manager::add(), duration_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), get_duration_or_var(), get_map(), JsonObject::get_member(), JsonObject::get_object(), get_str_or_var(), get_timed_events(), get_tripoint_from_var(), JsonObject::has_member(), map::invalidate_map_cache(), tinymap::load(), mapbuffer::lookup_submap(), MAPBUFFER, member, read_var_info(), REVERT_SUBMAP, coords::sm, abstract_str_or_var< T >::str_val, calendar::turn, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
f_roll_remainder()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 5626 of file npctalk.cpp.
 {
     std::vector<str_or_var> list;
     for( JsonValue jv : jo.get_array( member ) ) {
         list.emplace_back( get_str_or_var( jv, member ) );
     }
     str_or_var type = get_str_or_var( jo.get_member( "type" ), "type", true );
     translation_or_var message;
     if( jo.has_member( "message" ) ) {
         message = get_translation_or_var( jo.get_member( "message" ), "message", true );
     } else {
         message.str_val = translation();
     }
     std::vector<effect_on_condition_id> true_eocs = load_eoc_vector( jo, "true_eocs" );
     std::vector<effect_on_condition_id> false_eocs = load_eoc_vector( jo, "false_eocs" );
     return [list, type, is_npc, true_eocs, false_eocs, message]( dialogue const & d ) {
         std::vector<std::string> not_had;
         for( const str_or_var &cur_string : list ) {
             if( type.evaluate( d ) == "bionic" ) {
                 if( !d.actor( is_npc )->has_bionic( bionic_id( cur_string.evaluate( d ) ) ) ) {
                     not_had.push_back( cur_string.evaluate( d ) );
                 }
             } else if( type.evaluate( d ) == "mutation" ) {
                 if( !d.actor( is_npc )->has_trait( trait_id( cur_string.evaluate( d ) ) ) ) {
                     not_had.push_back( cur_string.evaluate( d ) );
                 }
             } else if( type.evaluate( d ) == "spell" ) {
                 if( d.actor( is_npc )->get_spell_level( spell_id( cur_string.evaluate( d ) ) ) == - 1 ) {
                     not_had.push_back( cur_string.evaluate( d ) );
                 }
             } else if( type.evaluate( d ) == "recipe" ) {
                 if( !d.actor( is_npc )->has_recipe( recipe_id( cur_string.evaluate( d ) ) ) ) {
                     not_had.push_back( cur_string.evaluate( d ) );
                 }
             } else {
                 debugmsg( "Invalid roll remainder type.  %s", d.get_callstack() );
             }
         }
         if( !not_had.empty() ) {
             int index = rng( 0, not_had.size() - 1 );
             std::string cur_choice = not_had[index];
             std::string name;
             if( type.evaluate( d ) == "bionic" ) {
                 bionic_id bionic( cur_choice );
                 d.actor( is_npc )->add_bionic( bionic );
                 name = bionic->name.translated();
             } else if( type.evaluate( d ) == "mutation" ) {
                 trait_id trait( cur_choice );
                 d.actor( is_npc )->set_mutation( trait );
                 name = trait->name();
             } else if( type.evaluate( d ) == "spell" ) {
                 spell_id spell( cur_choice );
                 d.actor( is_npc )->set_spell_level( spell, 1 );
                 name = spell->name.translated();
             } else if( type.evaluate( d ) == "recipe" ) {
                 recipe_id recipe( cur_choice );
                 d.actor( is_npc )->learn_recipe( recipe );
                 name = recipe->result_name();
             } else {
                 debugmsg( "Invalid roll remainder type.  %s", d.get_callstack() );
             }
             std::string cur_message = message.evaluate( d );
             if( !cur_message.empty() ) {
                 Character *target = d.actor( is_npc )->get_character();
                 if( target ) {
                     target->add_msg_if_player( cur_message, name );
                 }
             }
             run_eoc_vector( true_eocs, d );
         } else {
             run_eoc_vector( false_eocs, d );
         }
     };
 }
References dialogue::actor(), talker::add_bionic(), Character::add_msg_if_player(), debugmsg, JsonObject::get_array(), dialogue::get_callstack(), talker::get_character(), JsonObject::get_member(), talker::get_spell_level(), get_str_or_var(), get_translation_or_var(), talker::has_bionic(), JsonObject::has_member(), talker::has_recipe(), talker::has_trait(), talker::learn_recipe(), load_eoc_vector(), member, mapgen_defer::message, spell::name(), mutation_branch::name(), om_direction::name(), recipe::result_name(), rng(), run_eoc_vector(), talker::set_mutation(), and talker::set_spell_level().
f_run_eoc_selector()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector (const JsonObject & jo, std::string_view member)
Definition at line 4931 of file npctalk.cpp.
 {
     std::vector<eoc_entry> eocs = load_eoc_vector_id_and_var( jo, member );
     if( eocs.empty() ) {
         jo.throw_error( "Invalid input for run_eocs" );
     }
     std::vector<translation_or_var> eoc_names;
     if( jo.has_array( "names" ) ) {
         for( const JsonValue &jv : jo.get_array( "names" ) ) {
             eoc_names.emplace_back( get_translation_or_var( jv, "names", true ) );
         }
     }
     std::vector<translation_or_var> eoc_descriptions;
     if( jo.has_array( "descriptions" ) ) {
         for( const JsonValue &jv : jo.get_array( "descriptions" ) ) {
             eoc_descriptions.emplace_back( get_translation_or_var( jv, "descriptions", true ) );
         }
     }
     std::vector<char> eoc_keys;
     if( jo.has_array( "keys" ) ) {
         for( const JsonValue &jv : jo.get_array( "keys" ) ) {
             std::string val = jv.get_string();
             if( val.size() != 1 ) {
                 jo.throw_error( "Invalid input for run_eoc_selector, key strings must be exactly 1 character." );
             } else {
                 eoc_keys.push_back( val[0] );
             }
         }
     }
     if( !eoc_names.empty() && eoc_names.size() != eocs.size() ) {
         jo.throw_error( "Invalid input for run_eoc_selector, size of eocs and names needs to be identical, or names need to be empty" );
     }
     if( !eoc_descriptions.empty() && eoc_descriptions.size() != eocs.size() ) {
         jo.throw_error( "Invalid input for run_eoc_selector, size of eocs and descriptions needs to be identical, or descriptions need to be empty" );
     }
     if( !eoc_keys.empty() && eoc_keys.size() != eocs.size() ) {
         jo.throw_error( "Invalid input for run_eoc_selector, size of eocs and keys needs to be identical, or keys need to be empty." );
     }
     std::vector<std::unordered_map<std::string, str_translation_or_var>> context;
     if( jo.has_array( "variables" ) ) {
         for( const JsonValue &member : jo.get_array( "variables" ) ) {
             const JsonObject &variables = member.get_object();
             std::unordered_map<std::string, str_translation_or_var> temp_context;
             for( const JsonMember &jv : variables ) {
                 temp_context["npctalk_var_" + jv.name()] = get_str_translation_or_var( jv, jv.name(), true );
             }
             context.emplace_back( temp_context );
         }
     }
     if( !context.empty() && context.size() != 1 && context.size() != eocs.size() ) {
         jo.throw_error(
             string_format( "Invalid input for run_eoc_selector, size of vars needs to be 0 (no vars), 1 (all have the same vars), or the same size as the eocs (each has their own vars). Current size is: %d",
                            context.size() ) );
     }
     bool hide_failing = false;
     if( jo.has_bool( "hide_failing" ) ) {
         hide_failing = jo.get_bool( "hide_failing" );
     }
     bool allow_cancel = false;
     if( jo.has_bool( "allow_cancel" ) ) {
         allow_cancel = jo.get_bool( "allow_cancel" );
     }
     translation title = to_translation( "Select an option." );
     jo.read( "title", title );
     return [eocs, context, title, eoc_names, eoc_keys, eoc_descriptions,
           hide_failing, allow_cancel]( dialogue & d ) {
         uilist eoc_list;
         std::unique_ptr<talker> default_talker = get_talker_for( get_player_character() );
         talker &alpha = d.has_alpha ? *d.actor( false ) : *default_talker;
         talker &beta = d.has_beta ? *d.actor( true ) : *default_talker;
         eoc_list.text = title.translated();
         eoc_list.allow_cancel = allow_cancel;
         eoc_list.desc_enabled = !eoc_descriptions.empty();
         parse_tags( eoc_list.text, alpha, beta, d );
         for( size_t i = 0; i < eocs.size(); i++ ) {
             effect_on_condition_id eoc_id =
                 eocs[i].var ? effect_on_condition_id( eocs[i].var->evaluate( d ) ) : eocs[i].id;
             // check and set condition
             bool display = false;
             if( eoc_id->has_condition ) {
                 // if it has a condition check that it is true
                 display = eoc_id->test_condition( d );
             } else {
                 display = true;
             }
             if( hide_failing && !display ) {
                 // skip hidden entries
                 continue;
             }
             std::string name;
             std::string description;
             if( eoc_names.empty() ) {
                 name = eoc_id.str();
             } else {
                 name = eoc_names[i].evaluate( d );
                 parse_tags( name, alpha, beta, d );
             }
             if( !eoc_descriptions.empty() ) {
                 description = eoc_descriptions[i].evaluate( d );
                 parse_tags( description, alpha, beta, d );
             }
             if( eoc_keys.empty() ) {
                 eoc_list.entries.emplace_back( static_cast<int>( i ), display, std::nullopt, name, description );
             } else {
                 eoc_list.entries.emplace_back( static_cast<int>( i ), display, eoc_keys[i], name, description );
             }
         }
         if( eoc_list.entries.empty() ) {
             // if we have no entries should exit with error
             debugmsg( "No options for EOC_LIST" );
             return;
         }
         eoc_list.query();
         if( eoc_list.ret < 0 ) {
             return;
         }
         // add context variables
         dialogue newDialog( d );
         int contextIndex = 0;
         if( context.size() > 1 ) {
             contextIndex = eoc_list.ret;
         }
         if( !context.empty() ) {
             for( const auto &val : context[contextIndex] ) {
                 newDialog.set_value( val.first, val.second.evaluate( d ) );
             }
         }
         effect_on_condition_id chosen_eoc_id =
             eocs[eoc_list.ret].var ? effect_on_condition_id( eocs[eoc_list.ret].var->evaluate(
                         d ) ) : eocs[eoc_list.ret].id;
         chosen_eoc_id->activate( newDialog );
     };
 }
References effect_on_condition::activate(), dialogue::actor(), uilist::allow_cancel, context, debugmsg, uilist::desc_enabled, uilist::entries, JsonObject::get_array(), JsonObject::get_bool(), get_player_character(), get_str_translation_or_var(), get_talker_for(), get_translation_or_var(), dialogue::has_alpha, JsonObject::has_array(), dialogue::has_beta, JsonObject::has_bool(), effect_on_condition::has_condition, load_eoc_vector_id_and_var(), member, om_direction::name(), parse_tags(), uilist::query(), JsonObject::read(), uilist::ret, dialogue::set_value(), string_id< T >::str(), string_format(), effect_on_condition::test_condition(), uilist::text, JsonObject::throw_error(), music::title, and to_translation().
f_run_eoc_until()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_until (const JsonObject & jo, std::string_view member)
Definition at line 4906 of file npctalk.cpp.
 {
     effect_on_condition_id eoc = effect_on_conditions::load_inline_eoc( jo.get_member( member ), "" );
     std::function<bool( dialogue & )> cond;
     read_condition( jo, "condition", cond, true ); // The default result of this condition is true
     dbl_or_var iteration_count = get_dbl_or_var( jo, "iteration", false, 100 );
     return [eoc, cond, iteration_count]( dialogue & d ) {
         int max_iteration = iteration_count.evaluate( d );
         int curr_iteration = 0;
         // Amend the eoc to the callstack before the iteration.
         // In the interation, the eoc doesn't need to be amended repeatedly in activate().
         d.amend_callstack( "EOC: " + eoc->id.str() );
         while( cond( d ) ) {
             curr_iteration++;
             if( curr_iteration > max_iteration ) {
                 break;
             }
             eoc->activate( d, false );
         }
     };
 }
References dialogue::amend_callstack(), eoc, dbl_or_var::evaluate(), get_dbl_or_var(), JsonObject::get_member(), effect_on_conditions::load_inline_eoc(), member, and read_condition().
f_run_eoc_with()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with (const JsonObject & jo, std::string_view member)
Definition at line 5091 of file npctalk.cpp.
 {
     effect_on_condition_id eoc = effect_on_conditions::load_inline_eoc( jo.get_member( member ), "" );
     std::unordered_map<std::string, str_translation_or_var> context;
     if( jo.has_object( "variables" ) ) {
         const JsonObject &variables = jo.get_object( "variables" );
         for( const JsonMember &jv : variables ) {
             context["npctalk_var_" + jv.name()] = get_str_translation_or_var( jv, jv.name(), true );
         }
     }
     str_or_var alpha_var;
     str_or_var beta_var;
     bool is_alpha_loc = false;
     bool is_beta_loc = false;
     bool has_alpha_var = true;
     bool has_beta_var = true;
     if( jo.has_member( "beta_loc" ) ) {
         beta_var = get_str_or_var( jo.get_member( "beta_loc" ), "beta_loc", false, "npc" );
         is_beta_loc = true;
     } else if( jo.has_member( "beta_talker" ) ) {
         beta_var = get_str_or_var( jo.get_member( "beta_talker" ), "beta_talker", false, "npc" );
     } else {
         beta_var.str_val = "npc";
         has_beta_var = false;
     }
     if( jo.has_member( "alpha_loc" ) ) {
         alpha_var = get_str_or_var( jo.get_member( "alpha_loc" ), "alpha_loc", has_beta_var,
                                     "u" ); // alpha_talker is mandatory if beta_talker exists
         is_alpha_loc = true;
     } else if( jo.has_member( "alpha_talker" ) ) {
         alpha_var = get_str_or_var( jo.get_member( "alpha_talker" ), "alpha_talker", false, "u" );
     } else {
         alpha_var.str_val = "u";
         has_alpha_var = false;
     }
     std::vector<effect_on_condition_id> false_eocs = load_eoc_vector( jo, "false_eocs" );
     return [eoc, context, alpha_var, beta_var, is_alpha_loc, is_beta_loc, has_alpha_var,
          has_beta_var, false_eocs]( dialogue const & d ) {
         dialogue newDialog( d );
         if( has_alpha_var || has_beta_var ) {
             bool alpha_invalid = false;// whether alpha talker exists in the game
             bool beta_invalid = false;// whether beta talker exists in the game
             auto get_talker = [&d]( const str_or_var & var, bool is_loc, bool & invalid ) {
                 Creature *guy;
                 std::string str = var.evaluate( d );
                 if( is_loc ) {
                     tripoint_abs_ms pos = tripoint_abs_ms( tripoint::from_string( str ) );
                     guy = get_creature_tracker().creature_at( pos );
                     if( guy == nullptr ) {
                         invalid = true;
                     }
                 } else if( str.empty() ) {
                     guy = nullptr;
                 } else if( str == "u" ) {
                     guy = d.has_alpha ? d.actor( false )->get_creature() : nullptr;
                 } else if( str == "npc" ) {
                     guy = d.has_beta ? d.actor( true )->get_creature() : nullptr;
                 } else if( str == "avatar" ) {
                     guy = &get_avatar();
                 } else {
                     guy = get_character_from_id( str, g.get() );
                     if( guy == nullptr ) {
                         invalid = true;
                     }
                 }
                 return guy;
             };
             Creature *alpha_guy = get_talker( alpha_var, is_alpha_loc, alpha_invalid );
             Creature *beta_guy = get_talker( beta_var, is_beta_loc, beta_invalid );
             if( alpha_invalid || beta_invalid || ( alpha_guy == nullptr && beta_guy == nullptr ) ) {
                 run_eoc_vector( false_eocs, d );
                 return;
             } else {
                 newDialog = dialogue(
                                 ( alpha_guy == nullptr ) ? nullptr : get_talker_for( alpha_guy ),
                                 ( beta_guy == nullptr ) ? nullptr : get_talker_for( beta_guy ),
                                 d.get_conditionals(),
                                 d.get_context()
                             );
             }
         }
         for( const auto &val : context ) {
             newDialog.set_value( val.first, val.second.evaluate( d ) );
         }
         eoc->activate( newDialog );
     };
 }
References dialogue::actor(), context, creature_tracker::creature_at(), eoc, tripoint::from_string(), g, get_avatar(), get_character_from_id(), dialogue::get_conditionals(), dialogue::get_context(), talker::get_creature(), get_creature_tracker(), JsonObject::get_member(), JsonObject::get_object(), get_str_or_var(), get_str_translation_or_var(), get_talker_for(), dialogue::has_alpha, dialogue::has_beta, JsonObject::has_member(), JsonObject::has_object(), load_eoc_vector(), effect_on_conditions::load_inline_eoc(), member, math_opers::pos(), run_eoc_vector(), dialogue::set_value(), and abstract_str_or_var< T >::str_val.
f_run_eocs()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eocs (const JsonObject & jo, std::string_view member)
Definition at line 4889 of file npctalk.cpp.
 {
     std::vector<eoc_entry> eocs_entries = load_eoc_vector_id_and_var( jo, member );
     if( eocs_entries.empty() ) {
         jo.throw_error( "Invalid input for run_eocs" );
     }
     return [eocs_entries]( dialogue const & d ) {
         for( const eoc_entry &entry : eocs_entries ) {
             effect_on_condition_id eoc_id =
                 entry.var ? effect_on_condition_id( entry.var->evaluate( d ) ) : entry.id;
             dialogue newDialog( d );
             eoc_id->activate( newDialog );
         };
     };
 }
References effect_on_condition::activate(), load_eoc_vector_id_and_var(), member, and JsonObject::throw_error().
f_run_inv_eocs()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_inv_eocs (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 5298 of file npctalk.cpp.
 {
     str_or_var option = get_str_or_var( jo.get_member( member ), member );
     std::vector<effect_on_condition_id> true_eocs = load_eoc_vector( jo, "true_eocs" );
     std::vector<effect_on_condition_id> false_eocs = load_eoc_vector( jo, "false_eocs" );
     std::vector <item_search_data> data;
     for( const JsonValue &search_data_jo : jo.get_array( "search_data" ) ) {
         data.emplace_back( search_data_jo );
     }
     translation_or_var title;
     if( jo.has_member( "title" ) ) {
         title = get_translation_or_var( jo.get_member( "title" ), "title", true );
     } else {
         title.str_val = translation();
     }
     return [option, true_eocs, false_eocs, data, is_npc, title]( dialogue & d ) {
         Character *guy = d.actor( is_npc )->get_character();
         if( guy ) {
             const auto f = [d, guy, title]( const item_location_filter & filter ) {
                 return game_menus::inv::titled_filter_menu( filter, *guy, title.evaluate( d ) );
             };
             const auto f_mul = [d, guy, title]( const item_location_filter & filter ) {
                 return game_menus::inv::titled_multi_filter_menu( filter, *guy, title.evaluate( d ) );
             };
             run_item_eocs( d, is_npc, guy->all_items_loc(), option.evaluate( d ), true_eocs, false_eocs, data,
                            f, f_mul );
         }
     };
 }
References dialogue::actor(), abstract_str_or_var< T >::evaluate(), filter, JsonObject::get_array(), talker::get_character(), JsonObject::get_member(), get_str_or_var(), get_translation_or_var(), JsonObject::has_member(), load_eoc_vector(), member, run_item_eocs(), music::title, game_menus::inv::titled_filter_menu(), and game_menus::inv::titled_multi_filter_menu().
f_run_monster_eocs()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 5250 of file npctalk.cpp.
 {
     std::vector<effect_on_condition_id> eocs = load_eoc_vector( jo, member );
     std::vector<str_or_var> mtype_ids;
     for( JsonValue jv : jo.get_array( "mtype_ids" ) ) {
         mtype_ids.emplace_back( get_str_or_var( jv, "mtype_ids" ) );
     }
     std::optional<int> monster_range;
     if( jo.has_int( "monster_range" ) ) {
         monster_range = jo.get_int( "monster_range" );
     }
     bool monster_must_see = jo.get_bool( "monster_must_see", false );
     return [eocs, mtype_ids, monster_must_see, monster_range, is_npc]( dialogue const & d ) {
         std::vector<mtype_id> ids;
         ids.reserve( mtype_ids.size() );
         for( const str_or_var &id : mtype_ids ) {
             ids.emplace_back( id.evaluate( d ) );
         }
         tripoint actor_pos = d.actor( is_npc )->pos();
         const std::vector<Creature *> available = g->get_creatures_if( [ ids, monster_must_see,
              monster_range, actor_pos ]( const Creature & critter ) {
             bool id_valid = ids.empty();
             bool creature_is_monster = critter.is_monster();
             if( creature_is_monster ) {
                 for( const mtype_id &id : ids ) {
                     if( id == critter.as_monster()->type->id ) {
                         id_valid = true;
                         break;
                     }
                 }
             }
             return creature_is_monster && id_valid && ( !monster_range.has_value() ||
                     actor_pos.z == critter.posz() ) &&
                    ( !monster_must_see ||
                      critter.sees( actor_pos ) ) &&
                    ( !monster_range.has_value() || rl_dist( actor_pos, critter.pos() ) <= monster_range.value() );
         } );
         for( Creature *target : available ) {
             for( const effect_on_condition_id &eoc : eocs ) {
                 dialogue newDialog( get_talker_for( target ), nullptr, d.get_conditionals(), d.get_context() );
                 eoc->activate( newDialog );
             }
         }
     };
 }
References dialogue::actor(), Creature::as_monster(), available, eoc, g, JsonObject::get_array(), JsonObject::get_bool(), dialogue::get_conditionals(), dialogue::get_context(), JsonObject::get_int(), get_str_or_var(), get_talker_for(), JsonObject::has_int(), mtype::id, Creature::is_monster(), load_eoc_vector(), member, Creature::pos(), talker::pos(), Creature::posz(), rl_dist(), Creature::sees(), monster::type, and tripoint::z.
f_run_npc_eocs()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 5188 of file npctalk.cpp.
 {
     std::vector<effect_on_condition_id> eocs = load_eoc_vector( jo, member );
     std::vector<str_or_var> unique_ids;
     for( JsonValue jv : jo.get_array( "unique_ids" ) ) {
         unique_ids.emplace_back( get_str_or_var( jv, "unique_ids" ) );
     }
     bool local = jo.get_bool( "local", false );
     std::optional<int> npc_range;
     if( jo.has_int( "npc_range" ) ) {
         npc_range = jo.get_int( "npc_range" );
     }
     bool npc_must_see = jo.get_bool( "npc_must_see", false );
     if( local ) {
         return [eocs, unique_ids, npc_must_see, npc_range, is_npc]( dialogue const & d ) {
             tripoint actor_pos = d.actor( is_npc )->pos();
             std::vector<std::string> ids;
             ids.reserve( unique_ids.size() );
             for( const str_or_var &id : unique_ids ) {
                 ids.emplace_back( id.evaluate( d ) );
             }
             const std::vector<npc *> available = g->get_npcs_if( [npc_must_see, npc_range, actor_pos,
                           ids]( const npc & guy ) {
                 bool id_valid = ids.empty();
                 for( const std::string &id : ids ) {
                     if( id == guy.get_unique_id() ) {
                         id_valid = true;
                         break;
                     }
                 }
                 return id_valid && ( !npc_range.has_value() || actor_pos.z == guy.posz() ) && ( !npc_must_see ||
                         guy.sees( actor_pos ) ) &&
                        ( !npc_range.has_value() || rl_dist( actor_pos, guy.pos() ) <= npc_range.value() );
             } );
             for( npc *target : available ) {
                 for( const effect_on_condition_id &eoc : eocs ) {
                     dialogue newDialog( get_talker_for( target ), nullptr, d.get_conditionals(), d.get_context() );
                     eoc->activate( newDialog );
                 }
             }
         };
     } else {
         return [eocs, unique_ids]( dialogue const & d ) {
             for( const str_or_var &target : unique_ids ) {
                 if( g->unique_npc_exists( target.evaluate( d ) ) ) {
                     for( const effect_on_condition_id &eoc : eocs ) {
                         npc *npc = g->find_npc_by_unique_id( target.evaluate( d ) );
                         if( npc ) {
                             dialogue newDialog( get_talker_for( npc ), nullptr, d.get_conditionals(), d.get_context() );
                             eoc->activate( newDialog );
                         } else {
                             debugmsg( "Tried to use invalid npc: %s. %s", target.evaluate( d ), d.get_callstack() );
                         }
                     }
                 }
             }
         };
     }
 }
References dialogue::actor(), available, debugmsg, eoc, g, JsonObject::get_array(), JsonObject::get_bool(), dialogue::get_callstack(), dialogue::get_conditionals(), dialogue::get_context(), JsonObject::get_int(), get_str_or_var(), get_talker_for(), npc::get_unique_id(), JsonObject::has_int(), load_eoc_vector(), member, Creature::pos(), talker::pos(), Creature::posz(), rl_dist(), Character::sees(), and tripoint::z.
f_set_condition()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_condition (const JsonObject & jo, std::string_view member)
Definition at line 4617 of file npctalk.cpp.
 {
     str_or_var value;
     value = get_str_or_var( jo.get_member( member ), member );
     std::function<bool( dialogue & )> cond;
     read_condition( jo, "condition", cond, false );
     return [value, cond]( dialogue & d ) {
         d.set_conditional( value.evaluate( d ), cond );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), member, read_condition(), and dialogue::set_conditional().
f_set_flag()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_flag (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 4714 of file npctalk.cpp.
 {
     str_or_var flag = get_str_or_var( jo.get_member( member ), member, true );
     return [is_npc, flag]( dialogue & d ) {
         item_location *it = d.actor( is_npc )->get_item();
         if( it && it->get_item() ) {
             flag_id f_id( flag.evaluate( d ) );
             it->get_item()->set_flag( f_id );
         } else {
             debugmsg( "No valid %s talker.", is_npc ? "beta" : "alpha" );
         }
     };
 }
References dialogue::actor(), debugmsg, abstract_str_or_var< T >::evaluate(), talker::get_item(), JsonObject::get_member(), get_str_or_var(), member, and item::set_flag().
f_set_npc_rule()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_npc_rule (const JsonObject & jo, std::string_view member)
Definition at line 3483 of file npctalk.cpp.
 {
     str_or_var rule = get_str_or_var( jo.get_member( member ), member, true );
     return [rule]( dialogue const & d ) {
         d.actor( true )->set_ai_rule( "ally_rule", rule.evaluate( d ) );
     };
 }
References dialogue::actor(), abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), member, and talker::set_ai_rule().
f_set_string_var()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var (const JsonObject & jo, std::string_view member)
Definition at line 4582 of file npctalk.cpp.
 {
     const bool i18n = jo.get_bool( "i18n", false );
     std::vector<str_or_var> str_vals;
     std::vector<translation_or_var> i18n_vals;
     if( jo.has_array( member ) ) {
         for( JsonValue value : jo.get_array( member ) ) {
             if( i18n ) {
                 i18n_vals.emplace_back( get_translation_or_var( value, member ) );
             } else {
                 str_vals.emplace_back( get_str_or_var( value, member ) );
             }
         }
     } else {
         if( i18n ) {
             i18n_vals.emplace_back( get_translation_or_var( jo.get_member( member ), member ) );
         } else {
             str_vals.emplace_back( get_str_or_var( jo.get_member( member ), member ) );
         }
     }
     bool parse = jo.get_bool( "parse_tags", false );
     var_info var = read_var_info( jo.get_member( "target_var" ) );
     return [i18n, str_vals, i18n_vals, var, parse]( dialogue & d ) {
         int index = rng( 0, ( i18n ? i18n_vals.size() : str_vals.size() ) - 1 );
         std::string str = i18n ? i18n_vals[index].evaluate( d ) : str_vals[index].evaluate( d );
         if( parse ) {
             std::unique_ptr<talker> default_talker = get_talker_for( get_player_character() );
             talker &alpha = d.has_alpha ? *d.actor( false ) : *default_talker;
             talker &beta = d.has_beta ? *d.actor( true ) : *default_talker;
             parse_tags( str, alpha, beta, d );
         }
         write_var_value( var.type, var.name, &d, str );
     };
 }
References dialogue::actor(), JsonObject::get_array(), JsonObject::get_bool(), JsonObject::get_member(), get_player_character(), get_str_or_var(), get_talker_for(), get_translation_or_var(), dialogue::has_alpha, JsonObject::has_array(), dialogue::has_beta, member, parse_tags(), read_var_info(), rng(), and write_var_value().
f_set_talker()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_talker (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 5411 of file npctalk.cpp.
 {
     var_info var = read_var_info( jo.get_object( member ) );
     var_type type = var.type;
     std::string var_name = var.name;
     return [is_npc, var, type, var_name]( dialogue & d ) {
         int id = d.actor( is_npc )->getID().get_value();
         write_var_value( type, var_name, &d, id );
     };
 }
References dialogue::actor(), JsonObject::get_object(), character_id::get_value(), talker::getID(), member, read_var_info(), and write_var_value().
f_sound_effect()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect (const JsonObject & jo, std::string_view member)
Definition at line 4382 of file npctalk.cpp.
 {
     str_or_var variant = get_str_or_var( jo.get_member( member ), member, true );
     str_or_var id = get_str_or_var( jo.get_member( "id" ), "id", true );
     const bool outdoor_event = jo.get_bool( "outdoor_event", false );
     dbl_or_var volume;
     if( jo.has_member( "volume" ) ) {
         volume = get_dbl_or_var( jo, "volume", false, -1 );
     } else {
         volume.min.dbl_val = -1;
     }
     return [variant, id, outdoor_event, volume]( dialogue & d ) {
         map &here = get_map();
         int local_volume = volume.evaluate( d );
         Character *target = &get_player_character(); //Only the player can hear sound effects.
         if( target && !target->has_effect( effect_sleep ) && !target->is_deaf() ) {
             if( !outdoor_event || here.get_abs_sub().z() >= 0 ) {
                 if( local_volume == -1 ) {
                     local_volume = 80;
                 }
                 sfx::play_variant_sound( id.evaluate( d ), variant.evaluate( d ), local_volume,
                                          random_direction() );
             } else if( one_in( std::max( roll_remainder( 2.0f * here.get_abs_sub().z() /
                                          target->hearing_ability() ), 1 ) ) ) {
                 if( local_volume == -1 ) {
                     local_volume = 80 * target->hearing_ability();
                 }
                 sfx::play_variant_sound( id.evaluate( d ), variant.evaluate( d ), local_volume,
                                          random_direction() );
             }
         }
     };
 }
References effect_sleep, abstract_str_or_var< T >::evaluate(), map::get_abs_sub(), JsonObject::get_bool(), get_dbl_or_var(), get_map(), JsonObject::get_member(), get_player_character(), get_str_or_var(), Creature::has_effect(), JsonObject::has_member(), Character::hearing_ability(), base_camps::id, Character::is_deaf(), max(), member, one_in(), sfx::play_variant_sound(), random_direction(), roll_remainder(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
f_spawn_item()
talk_effect_fun_t talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item (const JsonObject & jo, std::string_view member)
Definition at line 3209 of file npctalk.cpp.
 {
     str_or_var item_name = get_str_or_var( jo.get_member( member ), member, true );
     str_or_var container_name;
     if( jo.has_member( "container" ) ) {
         container_name = get_str_or_var( jo.get_member( "container" ), "container", true );
     } else {
         container_name.str_val = "";
     }
     bool use_item_group = jo.get_bool( "use_item_group", false );
     bool suppress_message = jo.get_bool( "suppress_message", false );
     dbl_or_var count;
     if( !jo.has_int( "charges" ) ) {
         count = get_dbl_or_var( jo, "count", false, 1 );
     } else {
         count = get_dbl_or_var( jo, "count", false, 0 );
     }
     bool add_talker = true;
     if( member == "u_spawn_item" ) {
         add_talker = true;
     } else if( member == "map_spawn_item" ) {
         add_talker = false;
     }
     std::optional<var_info> loc_var;
     if( jo.has_object( "loc" ) ) {
         loc_var = read_var_info( jo.get_object( "loc" ) );
     }
     bool force_equip = jo.get_bool( "force_equip", false );
     std::vector<str_or_var> flags;
     for( JsonValue jv : jo.get_array( "flags" ) ) {
         flags.emplace_back( get_str_or_var( jv, "flags" ) );
     }
     talk_effect_fun_t ret( [item_name, count, container_name, use_item_group, suppress_message,
                add_talker, loc_var, force_equip, flags]( dialogue & d ) {
         itype_id iname = itype_id( item_name.evaluate( d ) );
         const tripoint_abs_ms target_location = get_tripoint_from_var( loc_var, d );
         std::vector<std::string> flags_str;
         flags_str.reserve( flags.size() );
         for( const str_or_var &flat_sov : flags ) {
             flags_str.emplace_back( flat_sov.evaluate( d ) );
         }
         receive_item( iname, count.evaluate( d ), container_name.evaluate( d ), d, use_item_group,
                       suppress_message, flags_str, add_talker, target_location, force_equip );
     } );
     ret.get_likely_rewards().emplace_back( count, item_name );
     return ret;
 }
References dbl_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), JsonObject::get_array(), JsonObject::get_bool(), get_dbl_or_var(), JsonObject::get_member(), JsonObject::get_object(), get_str_or_var(), get_tripoint_from_var(), JsonObject::has_int(), JsonObject::has_member(), JsonObject::has_object(), tname::item_name(), member, read_var_info(), receive_item(), cata::hash64_detail::ret, and abstract_str_or_var< T >::str_val.
f_spawn_monster()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 5798 of file npctalk.cpp.
 {
     bool group = jo.get_bool( "group", false );
     bool single_target = jo.get_bool( "single_target", false );
     str_or_var monster_id = get_str_or_var( jo.get_member( member ), member );
     dbl_or_var dov_target_range = get_dbl_or_var( jo, "target_range", false, 0 );
     dbl_or_var dov_hallucination_count = get_dbl_or_var( jo, "hallucination_count", false, 0 );
     dbl_or_var dov_real_count = get_dbl_or_var( jo, "real_count", false, 0 );
     dbl_or_var dov_min_radius = get_dbl_or_var( jo, "min_radius", false, 1 );
     dbl_or_var dov_max_radius = get_dbl_or_var( jo, "max_radius", false, 10 );
     const bool outdoor_only = jo.get_bool( "outdoor_only", false );
     const bool indoor_only = jo.get_bool( "indoor_only", false );
     if( indoor_only && outdoor_only ) {
         jo.throw_error( "Cannot be outdoor_only and indoor_only at the same time." );
     }
     const bool open_air_allowed = jo.get_bool( "open_air_allowed", false );
     const bool temporary_drop_items = jo.get_bool( "temporary_drop_items", false );
     const bool friendly = jo.get_bool( "friendly", false );
     duration_or_var dov_lifespan = get_duration_or_var( jo, "lifespan", false, 0_seconds );
     std::optional<var_info> target_var;
     if( jo.has_member( "target_var" ) ) {
         target_var = read_var_info( jo.get_object( "target_var" ) );
     }
     translation spawn_message;
     jo.read( "spawn_message", spawn_message );
     translation spawn_message_plural;
     jo.read( "spawn_message_plural", spawn_message_plural );
     std::vector<effect_on_condition_id> true_eocs = load_eoc_vector( jo, "true_eocs" );
     std::vector<effect_on_condition_id> false_eocs = load_eoc_vector( jo, "false_eocs" );
     return [monster_id, dov_target_range, dov_hallucination_count, dov_real_count, dov_min_radius,
                         dov_max_radius, outdoor_only, indoor_only, group, single_target, dov_lifespan, target_var,
                         spawn_message, spawn_message_plural, true_eocs, false_eocs, open_air_allowed, temporary_drop_items,
                 friendly, is_npc]( dialogue & d ) {
         monster target_monster;
         std::vector<Creature *> target_monsters;
         mongroup_id target_mongroup;
         bool use_target_monster = single_target;
         if( group ) {
             if( monster_id.evaluate( d ).empty() ) {
                 debugmsg( "Cannot use group without a valid monstergroup.  %s", d.get_callstack() );
             }
             if( single_target ) {
                 target_monster = monster( MonsterGroupManager::GetRandomMonsterFromGroup( mongroup_id(
                                               monster_id.evaluate( d ) ) ) );
             } else {
                 target_mongroup = mongroup_id( monster_id.evaluate( d ) );
             }
         } else if( monster_id.evaluate( d ).empty() ) {
             int target_range = dov_target_range.evaluate( d );
             if( single_target ) {
                 // Find a hostile creature in range to be used to create a hallucination or a copy of
                 Creature *copy = g->get_creature_if( [target_range]( const Creature & critter ) -> bool {
                     bool not_self = get_player_character().pos() != critter.pos();
                     bool in_range = std::round( rl_dist_exact( get_player_character().pos(), critter.pos() ) ) <= target_range;
                     bool valid_target = get_player_character().attitude_to( critter ) == Creature::Attitude::HOSTILE;
                     return not_self && in_range && valid_target;
                 } );
                 if( copy == nullptr ) {
                     run_eoc_vector( false_eocs, d );
                     return;
                 }
                 target_monster = *copy->as_monster();
             } else {
                 // Find all hostile creatures in range to be used to create hallucinations or copies of
                 std::vector<Creature *> monsters_in_range = g->get_creatures_if( [target_range](
                 const Creature & critter ) -> bool {
                     bool not_self = get_player_character().pos() != critter.pos();
                     bool in_range = std::round( rl_dist_exact( get_player_character().pos(), critter.pos() ) ) <= target_range;
                     bool valid_target = get_player_character().attitude_to( critter ) == Creature::Attitude::HOSTILE;
                     return not_self && in_range && valid_target;
                 } );
                 int valid_monsters = monsters_in_range.size();
                 if( valid_monsters == 0 ) {
                     run_eoc_vector( false_eocs, d );
                     return;
                 } else if( valid_monsters == 1 ) {
                     Creature *copy = monsters_in_range[0];
                     target_monster = *copy->as_monster();
                     use_target_monster = true;
                 } else {
                     target_monsters = monsters_in_range;
                 }
             }
         } else {
             if( single_target ) {
                 debugmsg( "single_target doesn't need to be defined for a singlular monster_id.  %s",
                           d.get_callstack() );
             }
             target_monster = monster( mtype_id( monster_id.evaluate( d ) ) );
             use_target_monster = true;
         }
         int min_radius = dov_min_radius.evaluate( d );
         int max_radius = dov_max_radius.evaluate( d );
         int real_count = dov_real_count.evaluate( d );
         int hallucination_count = dov_hallucination_count.evaluate( d );
         std::optional<time_duration> lifespan;
         tripoint target_pos = d.actor( is_npc )->pos();
         if( target_var.has_value() ) {
             target_pos = get_map().getlocal( get_tripoint_from_var( target_var, d ) );
         }
         int visible_spawns = 0;
         int spawns = 0;
         for( int i = 0; i < hallucination_count; i++ ) {
             tripoint spawn_point;
             if( !use_target_monster ) {
                 if( group ) {
                     target_monster = monster( MonsterGroupManager::GetRandomMonsterFromGroup( target_mongroup ) );
                 } else {
                     Creature *copy = target_monsters[ rng( 0, target_monsters.size() - 1 ) ];
                     target_monster = *copy->as_monster();
                 }
             }
             if( g->find_nearby_spawn_point( target_pos, target_monster.type->id, min_radius,
                                             max_radius, spawn_point, outdoor_only, indoor_only, open_air_allowed ) ) {
                 lifespan = dov_lifespan.evaluate( d );
                 if( lifespan.value() == 0_seconds ) {
                     lifespan.reset();
                 }
                 if( g->spawn_hallucination( spawn_point, target_monster.type->id, lifespan ) ) {
                     Creature *critter = get_creature_tracker().creature_at( spawn_point );
                     if( critter ) {
                         if( friendly ) {
                             critter->as_monster()->friendly = -1;
                         }
                         spawns++;
                         if( get_avatar().sees( *critter ) ) {
                             visible_spawns++;
                         }
                     }
                 }
             }
         }
         for( int i = 0; i < real_count; i++ ) {
             tripoint spawn_point;
             if( !use_target_monster ) {
                 if( group ) {
                     target_monster = monster( MonsterGroupManager::GetRandomMonsterFromGroup( target_mongroup ) );
                 } else {
                     Creature *copy = target_monsters[ rng( 0, target_monsters.size() - 1 ) ];
                     target_monster = *copy->as_monster();
                 }
             }
             if( g->find_nearby_spawn_point( target_pos, target_monster.type->id, min_radius,
                                             max_radius, spawn_point, outdoor_only, indoor_only, open_air_allowed ) ) {
                 monster *spawned = g->place_critter_at( target_monster.type->id, spawn_point );
                 if( spawned ) {
                     if( friendly ) {
                         spawned->friendly = -1;
                     }
                     spawns++;
                     if( get_avatar().sees( *spawned ) ) {
                         visible_spawns++;
                     }
                     lifespan = dov_lifespan.evaluate( d );
                     if( lifespan.value() > 0_seconds ) {
                         spawned->set_summon_time( lifespan.value() );
                         // Temporary monsters shouldn't drop items unless told to
                         spawned->no_extra_death_drops = !temporary_drop_items;
                         spawned->no_corpse_quiet = !temporary_drop_items;
                     }
                 }
             }
         }
         if( visible_spawns > 1 && !spawn_message_plural.empty() ) {
             get_avatar().add_msg_if_player( m_bad, spawn_message_plural );
         } else if( visible_spawns > 0 && !spawn_message.empty() ) {
             get_avatar().add_msg_if_player( m_bad, spawn_message );
         }
         if( spawns > 0 ) {
             run_eoc_vector( true_eocs, d );
         } else {
             run_eoc_vector( false_eocs, d );
         }
     };
 }
References dialogue::actor(), Character::add_msg_if_player(), Creature::as_monster(), Character::attitude_to(), creature_tracker::creature_at(), debugmsg, translation::empty(), dbl_or_var::evaluate(), duration_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), monster::friendly, friendly, g, get_avatar(), JsonObject::get_bool(), dialogue::get_callstack(), get_creature_tracker(), get_dbl_or_var(), get_duration_or_var(), get_map(), JsonObject::get_member(), JsonObject::get_object(), get_player_character(), get_str_or_var(), get_tripoint_from_var(), map::getlocal(), MonsterGroupManager::GetRandomMonsterFromGroup(), JsonObject::has_member(), Creature::HOSTILE, mtype::id, load_eoc_vector(), m_bad, member, monster::no_corpse_quiet, monster::no_extra_death_drops, Creature::pos(), talker::pos(), math_opers::pos(), JsonObject::read(), read_var_info(), rl_dist_exact(), rng(), round(), run_eoc_vector(), Creature::set_summon_time(), JsonObject::throw_error(), and monster::type.
f_spawn_npc()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 5978 of file npctalk.cpp.
 {
     str_or_var sov_npc_class = get_str_or_var( jo.get_member( member ), member );
     str_or_var unique_id;
     if( jo.has_member( "unique_id" ) ) {
         unique_id = get_str_or_var( jo.get_member( "unique_id" ), "unique_id" );
     } else {
         unique_id.str_val = "";
     }
     std::vector<str_or_var> traits;
     for( JsonValue jv : jo.get_array( "traits" ) ) {
         str_or_var entry = get_str_or_var( jv, "traits" );
         traits.emplace_back( entry );
     }
     dbl_or_var dov_hallucination_count = get_dbl_or_var( jo, "hallucination_count", false, 0 );
     dbl_or_var dov_real_count = get_dbl_or_var( jo, "real_count", false, 0 );
     dbl_or_var dov_min_radius = get_dbl_or_var( jo, "min_radius", false, 1 );
     dbl_or_var dov_max_radius = get_dbl_or_var( jo, "max_radius", false, 10 );
     const bool open_air_allowed = jo.get_bool( "open_air_allowed", false );
     const bool outdoor_only = jo.get_bool( "outdoor_only", false );
     const bool indoor_only = jo.get_bool( "indoor_only", false );
     if( indoor_only && outdoor_only ) {
         jo.throw_error( "Cannot be outdoor_only and indoor_only at the same time." );
     }
     duration_or_var dov_lifespan = get_duration_or_var( jo, "lifespan", false, 0_seconds );
     std::optional<var_info> target_var;
     if( jo.has_member( "target_var" ) ) {
         target_var = read_var_info( jo.get_object( "target_var" ) );
     }
     translation spawn_message;
     jo.read( "spawn_message", spawn_message );
     translation spawn_message_plural;
     jo.read( "spawn_message_plural", spawn_message_plural );
     std::vector<effect_on_condition_id> true_eocs = load_eoc_vector( jo, "true_eocs" );
     std::vector<effect_on_condition_id> false_eocs = load_eoc_vector( jo, "false_eocs" );
     return [sov_npc_class, unique_id, traits, dov_hallucination_count, dov_real_count,
                            dov_min_radius,
                            dov_max_radius, outdoor_only, indoor_only, dov_lifespan, target_var, spawn_message,
                    spawn_message_plural, true_eocs, false_eocs, open_air_allowed, is_npc]( dialogue & d ) {
         int min_radius = dov_min_radius.evaluate( d );
         int max_radius = dov_max_radius.evaluate( d );
         int real_count = dov_real_count.evaluate( d );
         int hallucination_count = dov_hallucination_count.evaluate( d );
         string_id<npc_template> cur_npc_class( sov_npc_class.evaluate( d ) );
         std::string cur_unique_id = unique_id.evaluate( d );
         std::vector<trait_id> cur_traits;
         cur_traits.reserve( traits.size() ); // Reserve space for all elements in traits
         for( const str_or_var &cur_trait : traits ) {
             cur_traits.emplace_back( cur_trait.evaluate( d ) );
         }
         std::optional<time_duration> lifespan;
         tripoint target_pos = d.actor( is_npc )->pos();
         if( target_var.has_value() ) {
             target_pos = get_map().getlocal( get_tripoint_from_var( target_var, d ) );
         }
         int visible_spawns = 0;
         int spawns = 0;
         for( int i = 0; i < real_count; i++ ) {
             tripoint spawn_point;
             if( g->find_nearby_spawn_point( target_pos, min_radius,
                                             max_radius, spawn_point, outdoor_only, indoor_only, open_air_allowed ) ) {
                 lifespan = dov_lifespan.evaluate( d );
                 if( lifespan.value() == 0_seconds ) {
                     lifespan.reset();
                 }
                 if( g->spawn_npc( spawn_point, cur_npc_class, cur_unique_id, cur_traits, lifespan ) ) {
                     Creature *guy = get_creature_tracker().creature_at( spawn_point );
                     if( guy ) {
                         spawns++;
                         if( get_avatar().sees( *guy ) ) {
                             visible_spawns++;
                         }
                     }
                 }
             }
         }
         cur_traits.emplace_back( trait_HALLUCINATION );
         for( int i = 0; i < hallucination_count; i++ ) {
             tripoint spawn_point;
             if( g->find_nearby_spawn_point( target_pos, min_radius,
                                             max_radius, spawn_point, outdoor_only, indoor_only, open_air_allowed ) ) {
                 lifespan = dov_lifespan.evaluate( d );
                 if( lifespan.value() == 0_seconds ) {
                     lifespan.reset();
                 }
                 std::string empty;
                 if( g->spawn_npc( spawn_point, cur_npc_class, empty, cur_traits, lifespan ) ) {
                     Creature *guy = get_creature_tracker().creature_at( spawn_point );
                     if( guy ) {
                         spawns++;
                         if( get_avatar().sees( *guy ) ) {
                             visible_spawns++;
                         }
                     }
                 }
             }
         }
         if( visible_spawns > 1 && !spawn_message_plural.empty() ) {
             get_avatar().add_msg_if_player( m_bad, spawn_message_plural );
         } else if( visible_spawns > 0 && !spawn_message.empty() ) {
             get_avatar().add_msg_if_player( m_bad, spawn_message );
         }
         if( spawns > 0 ) {
             run_eoc_vector( true_eocs, d );
         } else {
             run_eoc_vector( false_eocs, d );
         }
     };
 }
References dialogue::actor(), Character::add_msg_if_player(), creature_tracker::creature_at(), translation::empty(), dbl_or_var::evaluate(), duration_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), g, JsonObject::get_array(), get_avatar(), JsonObject::get_bool(), get_creature_tracker(), get_dbl_or_var(), get_duration_or_var(), get_map(), JsonObject::get_member(), JsonObject::get_object(), get_str_or_var(), get_tripoint_from_var(), map::getlocal(), JsonObject::has_member(), load_eoc_vector(), m_bad, member, talker::pos(), JsonObject::read(), read_var_info(), run_eoc_vector(), abstract_str_or_var< T >::str_val, JsonObject::throw_error(), and trait_HALLUCINATION.
f_switch()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_switch (const JsonObject & jo, std::string_view member)
Definition at line 5544 of file npctalk.cpp.
 {
     dbl_or_var eoc_switch = get_dbl_or_var( jo, member );
     std::vector<std::pair<dbl_or_var, talk_effect_t>> case_pairs;
     for( const JsonValue jv : jo.get_array( "cases" ) ) {
         JsonObject array_case = jv.get_object();
         talk_effect_t case_effect;
         case_effect.load_effect( array_case, "effect" );
         case_pairs.emplace_back( get_dbl_or_var( array_case, "case" ), case_effect );
     }
     return [eoc_switch, case_pairs]( dialogue & d ) {
         const double switch_int = eoc_switch.evaluate( d );
         talk_effect_t case_effect;
         for( const std::pair<dbl_or_var, talk_effect_t> &case_pair :
              case_pairs ) {
             if( switch_int >= case_pair.first.evaluate( d ) ) {
                 case_effect = case_pair.second;
             }
         }
         case_effect.apply( d );
     };
 }
References talk_effect_t::apply(), dbl_or_var::evaluate(), JsonObject::get_array(), get_dbl_or_var(), JsonObject::get_object(), talk_effect_t::load_effect(), and member.
f_take_control()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_take_control (const JsonObject & jo, std::string_view)
Definition at line 4360 of file npctalk.cpp.
 {
     std::vector<effect_on_condition_id> true_eocs = load_eoc_vector( jo, "true_eocs" );
     std::vector<effect_on_condition_id> false_eocs = load_eoc_vector( jo, "false_eocs" );
     return [true_eocs, false_eocs]( dialogue const & d ) {
         if( !d.actor( false )->get_character()->is_avatar() ) { //only take control if the avatar is alpha
             run_eoc_vector( false_eocs, d );
             return;
         } else if( d.actor( true )->get_npc() != nullptr ) {
             get_avatar().control_npc( *d.actor( true )->get_npc() );
         }
         run_eoc_vector( true_eocs, d );
     };
 }
References dialogue::actor(), avatar::control_npc(), get_avatar(), talker::get_character(), talker::get_npc(), Creature::is_avatar(), load_eoc_vector(), and run_eoc_vector().
Referenced by talk_effect_t::parse_string_effect().
f_take_control_menu()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_take_control_menu ()
Definition at line 4375 of file npctalk.cpp.
 {
     return []( dialogue const &/* d */ ) {
         get_avatar().control_npc_menu();
     };
 }
References avatar::control_npc_menu(), and get_avatar().
Referenced by talk_effect_t::parse_string_effect().
f_teleport()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 6129 of file npctalk.cpp.
 {
     std::optional<var_info> target_var = read_var_info( jo.get_object( member ) );
     translation_or_var fail_message;
     if( jo.has_member( "fail_message" ) ) {
         fail_message = get_translation_or_var( jo.get_member( "fail_message" ), "fail_message",
                                                false, translation() );
     } else {
         fail_message.str_val = translation();
     }
     translation_or_var success_message;
     if( jo.has_member( "success_message" ) ) {
         success_message = get_translation_or_var( jo.get_member( "success_message" ), "success_message",
                           false, translation() );
     } else {
         success_message.str_val = translation();
     }
     bool force = jo.get_bool( "force", false );
     return [is_npc, target_var, fail_message, success_message, force]( dialogue const & d ) {
         tripoint_abs_ms target_pos = get_tripoint_from_var( target_var, d );
         Creature *teleporter = d.actor( is_npc )->get_creature();
         if( teleporter ) {
             if( teleport::teleport_to_point( *teleporter, get_map().getlocal( target_pos ), true, false,
                                              false, force ) ) {
                 teleporter->add_msg_if_player( success_message.evaluate( d ) );
             } else {
                 teleporter->add_msg_if_player( fail_message.evaluate( d ) );
             }
         }
         item_location *it = d.actor( is_npc )->get_item();
         if( it && it->get_item() ) {
             map_add_item( *it->get_item(), target_pos );
             add_msg( success_message.evaluate( d ) );
             it->remove_item();
         }
     };
 }
References dialogue::actor(), add_msg(), Creature::add_msg_if_player(), abstract_str_or_var< T >::evaluate(), force, JsonObject::get_bool(), talker::get_creature(), talker::get_item(), get_map(), JsonObject::get_member(), JsonObject::get_object(), get_translation_or_var(), get_tripoint_from_var(), JsonObject::has_member(), map_add_item(), member, read_var_info(), visitable::remove_item(), abstract_str_or_var< T >::str_val, and teleport::teleport_to_point().
f_toggle_npc_rule()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_toggle_npc_rule (const JsonObject & jo, std::string_view member)
Definition at line 3475 of file npctalk.cpp.
 {
     str_or_var rule = get_str_or_var( jo.get_member( member ), member, true );
     return [rule]( dialogue const & d ) {
         d.actor( true )->toggle_ai_rule( "ally_rule", rule.evaluate( d ) );
     };
 }
References dialogue::actor(), abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), member, and talker::toggle_ai_rule().
f_transform_item()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_item (const JsonObject & jo, std::string_view member)
Definition at line 4796 of file npctalk.cpp.
 {
     str_or_var target_id = get_str_or_var( jo.get_member( member ), member, true );
     bool activate = jo.get_bool( "active", false );
     return [target_id, activate]( dialogue & d ) {
         item_location *it = d.actor( true )->get_item();
         if( it && it->get_item() ) {
             const std::string target_str = target_id.evaluate( d );
             ( *it )->convert( itype_id( target_str ), it->carrier() );
             ( *it )->active = activate || ( *it )->has_temperature();
         } else {
             debugmsg( "beta talker must be Item." );
         }
     };
 }
References dialogue::actor(), debugmsg, abstract_str_or_var< T >::evaluate(), JsonObject::get_bool(), talker::get_item(), JsonObject::get_member(), get_str_or_var(), and member.
f_transform_line()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_line (const JsonObject & jo, std::string_view member)
Definition at line 3805 of file npctalk.cpp.
 {
     str_or_var transform = get_str_or_var( jo.get_member( member ), member, true );
     var_info first = read_var_info( jo.get_object( "first" ) );
     var_info second = read_var_info( jo.get_object( "second" ) );
     return [transform, first, second]( dialogue const & d ) {
         tripoint_abs_ms const t_first = get_tripoint_from_var( first, d );
         tripoint_abs_ms const t_second = get_tripoint_from_var( second, d );
         tripoint_abs_ms const orig = coord_min( t_first, t_second );
         map tm;
         tm.load( project_to<coords::sm>( orig ), false );
         tm.transform_line( ter_furn_transform_id( transform.evaluate( d ) ), t_first, t_second );
     };
 }
References coords::coord_min(), JsonObject::get_member(), JsonObject::get_object(), get_str_or_var(), get_tripoint_from_var(), map::load(), member, read_var_info(), second, transform, and map::transform_line().
f_transform_radius()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 3759 of file npctalk.cpp.
 {
     str_or_var transform = get_str_or_var( jo.get_member( "ter_furn_transform" ),
                                            "ter_furn_transform", true );
     dbl_or_var dov = get_dbl_or_var( jo, member );
     duration_or_var dov_time_in_future = get_duration_or_var( jo, "time_in_future", false,
                                          0_seconds );
     std::optional<var_info> target_var;
     if( jo.has_member( "target_var" ) ) {
         target_var = read_var_info( jo.get_object( "target_var" ) );
     }
     str_or_var key;
     if( jo.has_member( "key" ) ) {
         key = get_str_or_var( jo.get_member( "key" ), "key", false, "" );
     } else {
         key.str_val = "";
     }
     return [dov, transform, target_var, dov_time_in_future, key, is_npc]( dialogue & d ) {
         tripoint_abs_ms target_pos = d.actor( is_npc )->global_pos();
         if( target_var.has_value() ) {
             target_pos = get_tripoint_from_var( target_var, d );
         }
         int radius = dov.evaluate( d );
         time_duration future = dov_time_in_future.evaluate( d );
         if( future > 0_seconds ) {
             get_timed_events().add( timed_event_type::TRANSFORM_RADIUS,
                                     calendar::turn + future + 1_seconds,
                                     //Timed events happen before the player turn and eocs are during so we add a second here to sync them up using the same variable
                                     -1, target_pos, radius, transform.evaluate( d ), key.evaluate( d ) );
         } else {
             // Use the main map when possible to reduce performance overhead.
             if( get_map().inbounds( target_pos - point{ radius, radius} ) &&
                 get_map().inbounds( target_pos + point{ radius, radius} ) ) {
                 get_map().transform_radius( ter_furn_transform_id( transform.evaluate( d ) ), radius, target_pos );
             } else {
                 map tm;
                 tm.load( project_to<coords::sm>( target_pos - point{ radius, radius} ), false );
                 tm.transform_radius( ter_furn_transform_id( transform.evaluate( d ) ), radius, target_pos );
             }
         }
     };
 }
References dialogue::actor(), timed_event_manager::add(), dbl_or_var::evaluate(), duration_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), get_dbl_or_var(), get_duration_or_var(), get_map(), JsonObject::get_member(), JsonObject::get_object(), get_str_or_var(), get_timed_events(), get_tripoint_from_var(), talker::global_pos(), JsonObject::has_member(), map::load(), member, read_var_info(), abstract_str_or_var< T >::str_val, transform, map::transform_radius(), TRANSFORM_RADIUS, and calendar::turn.
f_trigger_event()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_trigger_event (const JsonObject & jo, std::string_view member)
Definition at line 6184 of file npctalk.cpp.
 {
     std::string const type_str = jo.get_string( member.data() );
     JsonArray const &jargs = jo.get_array( "args" );
     event_type type = io::string_to_enum<event_type>( type_str );
     std::vector<str_or_var> args;
     args.reserve( jargs.size() );
     for( JsonValue const &jv : jargs ) {
         args.emplace_back( get_str_or_var( jv, "args" ) );
     }
     return [type, args]( dialogue & d ) {
         std::vector<std::string> args_str;
         args_str.reserve( args.size() );
         std::transform( args.cbegin(), args.cend(),
         std::back_inserter( args_str ), [&d]( str_or_var const & sov ) {
             return sov.evaluate( d );
         } );
         get_event_bus().send( cata::event::make_dyn( type, args_str ) );
     };
 }
References JsonObject::get_array(), get_event_bus(), get_str_or_var(), JsonObject::get_string(), cata::event::make_dyn(), member, event_bus::send(), and JsonArray::size().
f_turn_cost()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_turn_cost (const JsonObject & jo, std::string_view member)
Definition at line 4154 of file npctalk.cpp.
 {
     duration_or_var cost = get_duration_or_var( jo, member, true );
     return [cost]( dialogue & d ) {
         Character *target = d.actor( false )->get_character();
         if( target ) {
             target->mod_moves( -to_moves<int>( cost.evaluate( d ) ) );
         }
     };
 }
References dialogue::actor(), duration_or_var::evaluate(), talker::get_character(), get_duration_or_var(), member, and Creature::mod_moves().
f_u_buy_item()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item (const JsonObject & jo, std::string_view member)
Definition at line 3258 of file npctalk.cpp.
 {
     std::vector<effect_on_condition_id> true_eocs = load_eoc_vector( jo, "true_eocs" );
     std::vector<effect_on_condition_id> false_eocs = load_eoc_vector( jo, "false_eocs" );
     dbl_or_var cost = get_dbl_or_var( jo, "cost", false, 0 );
     dbl_or_var count;
     if( !jo.has_int( "charges" ) ) {
         count = get_dbl_or_var( jo, "count", false, 1 );
     } else {
         count = get_dbl_or_var( jo, "count", false, 0 );
     }
     bool use_item_group = jo.get_bool( "use_item_group", false );
     bool suppress_message = jo.get_bool( "suppress_message", false );
     str_or_var container_name;
     if( jo.has_member( "container" ) ) {
         container_name = get_str_or_var( jo.get_member( "container" ), "container", true );
     } else {
         container_name.str_val = "";
     }
     std::vector<str_or_var> flags;
     for( JsonValue jv : jo.get_array( "flags" ) ) {
         flags.emplace_back( get_str_or_var( jv, "flags" ) );
     }
     str_or_var item_name = get_str_or_var( jo.get_member( member ), member, true );
     return [item_name, cost, count, container_name, true_eocs, false_eocs,
                use_item_group, suppress_message, flags]( dialogue & d ) {
         if( !d.actor( true )->buy_from( cost.evaluate( d ) ) ) {
             popup( _( "You can't afford it!" ) );
             run_eoc_vector( false_eocs, d );
             return;
         }
         itype_id iname = itype_id( item_name.evaluate( d ) );
         std::vector<std::string> flags_str;
         flags_str.reserve( flags.size() );
         for( const str_or_var &flat_sov : flags ) {
             flags_str.emplace_back( flat_sov.evaluate( d ) );
         }
         receive_item( iname, count.evaluate( d ),
                       container_name.evaluate( d ), d, use_item_group, suppress_message, flags_str );
         run_eoc_vector( true_eocs, d );
     };
 }
References _, dialogue::actor(), talker::buy_from(), dbl_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), JsonObject::get_array(), JsonObject::get_bool(), get_dbl_or_var(), JsonObject::get_member(), get_str_or_var(), JsonObject::has_int(), JsonObject::has_member(), tname::item_name(), load_eoc_vector(), member, popup(), receive_item(), run_eoc_vector(), and abstract_str_or_var< T >::str_val.
f_u_buy_monster()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_monster (const JsonObject & jo, std::string_view member)
Definition at line 4107 of file npctalk.cpp.
 {
     str_or_var monster_type_id = get_str_or_var( jo.get_member( member ), member, true );
     dbl_or_var cost = get_dbl_or_var( jo, "cost", false, 0 );
     dbl_or_var count = get_dbl_or_var( jo, "count", false, 1 );
     const bool pacified = jo.get_bool( "pacified", false );
     translation_or_var name;
     if( jo.has_member( "name" ) ) {
         name = get_translation_or_var( jo.get_member( "name" ), "name", true );
     } else {
         name.str_val = translation();
     }
     std::vector<effect_on_condition_id> true_eocs = load_eoc_vector( jo, "true_eocs" );
     std::vector<effect_on_condition_id> false_eocs = load_eoc_vector( jo, "false_eocs" );
     return [monster_type_id, cost, count, pacified, name, true_eocs,
                      false_eocs]( dialogue & d ) {
         const mtype_id mtype( monster_type_id.evaluate( d ) );
         translation translated_name = no_translation( name.evaluate( d ) );
         if( d.actor( false )->buy_monster( *d.actor( true ), mtype, cost.evaluate( d ), count.evaluate( d ),
                                            pacified, translated_name ) ) {
             run_eoc_vector( true_eocs, d );
         } else {
             run_eoc_vector( false_eocs, d );
         }
     };
 }
References dialogue::actor(), talker::buy_monster(), dbl_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), JsonObject::get_bool(), get_dbl_or_var(), JsonObject::get_member(), get_str_or_var(), get_translation_or_var(), JsonObject::has_member(), load_eoc_vector(), member, om_direction::name(), no_translation(), and run_eoc_vector().
f_u_sell_item()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item (const JsonObject & jo, std::string_view member)
Definition at line 3302 of file npctalk.cpp.
 {
     std::vector<effect_on_condition_id> true_eocs = load_eoc_vector( jo, "true_eocs" );
     std::vector<effect_on_condition_id> false_eocs = load_eoc_vector( jo, "false_eocs" );
     dbl_or_var cost = get_dbl_or_var( jo, "cost", false, 0 );
     dbl_or_var count;
     if( !jo.has_int( "charges" ) ) {
         count = get_dbl_or_var( jo, "count", false, 1 );
     } else {
         count = get_dbl_or_var( jo, "count", false, 0 );
     }
     str_or_var item_name = get_str_or_var( jo.get_member( member ), member, true );
     return [item_name, cost, count, true_eocs, false_eocs]( dialogue & d ) {
         int current_count = count.evaluate( d );
         itype_id current_item_name = itype_id( item_name.evaluate( d ) );
         if( item::count_by_charges( current_item_name ) &&
             d.actor( false )->has_charges( current_item_name, current_count ) ) {
             for( item &it : d.actor( false )->use_charges( current_item_name, current_count ) ) {
                 it.set_owner( d.actor( true )->get_faction()->id );
                 d.actor( true )->i_add( it );
             }
         } else if( d.actor( false )->has_amount( current_item_name, current_count ) ) {
             for( item &it : d.actor( false )->use_amount( current_item_name, current_count ) ) {
                 it.set_owner( d.actor( true )->get_faction()->id );
                 d.actor( true )->i_add( it );
             }
         } else {
             //~ %1$s is a translated item name
             popup( _( "You don't have a %1$s!" ), item::nname( current_item_name ) );
             run_eoc_vector( false_eocs, d );
             return;
         }
         if( current_count == 1 ) {
             //~ %1%s is the NPC name, %2$s is an item
             popup( _( "You give %1$s a %2$s." ), d.actor( true )->disp_name(),
                    item::nname( current_item_name ) );
         } else {
             //~ %1%s is the NPC name, %2$d is a number of items, %3$s are items
             popup( _( "You give %1$s %2$d %3$s." ), d.actor( true )->disp_name(), current_count,
                    item::nname( current_item_name, current_count ) );
         }
         d.actor( true )->add_debt( cost.evaluate( d ) );
         run_eoc_vector( true_eocs, d );
     };
 }
References _, dialogue::actor(), talker::add_debt(), item::count_by_charges(), talker::disp_name(), dbl_or_var::evaluate(), get_dbl_or_var(), talker::get_faction(), JsonObject::get_member(), get_str_or_var(), talker::has_amount(), talker::has_charges(), JsonObject::has_int(), talker::i_add(), faction_template::id, tname::item_name(), load_eoc_vector(), member, item::nname(), popup(), run_eoc_vector(), talker::use_amount(), and talker::use_charges().
f_u_spend_cash()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_spend_cash (const JsonObject & jo, std::string_view member)
Definition at line 3415 of file npctalk.cpp.
 {
     dbl_or_var amount = get_dbl_or_var( jo, member );
     std::vector<effect_on_condition_id> true_eocs = load_eoc_vector( jo, "true_eocs" );
     std::vector<effect_on_condition_id> false_eocs = load_eoc_vector( jo, "false_eocs" );
     return [amount, true_eocs, false_eocs]( dialogue & d ) {
         if( d.actor( true )->buy_from( amount.evaluate( d ) ) ) {
             run_eoc_vector( true_eocs, d );
         } else {
             run_eoc_vector( false_eocs, d );
         }
     };
 }
References dialogue::actor(), talker::buy_from(), dbl_or_var::evaluate(), get_dbl_or_var(), load_eoc_vector(), member, and run_eoc_vector().
f_unset_flag()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_unset_flag (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 4731 of file npctalk.cpp.
 {
     str_or_var flag = get_str_or_var( jo.get_member( member ), member, true );
     return [is_npc, flag]( dialogue & d ) {
         item_location *it = d.actor( is_npc )->get_item();
         if( it && it->get_item() ) {
             flag_id f_id( flag.evaluate( d ) );
             it->get_item()->unset_flag( f_id );
         } else {
             debugmsg( "No valid %s talker.", is_npc ? "beta" : "alpha" );
         }
     };
 }
References dialogue::actor(), debugmsg, abstract_str_or_var< T >::evaluate(), talker::get_item(), JsonObject::get_member(), get_str_or_var(), member, and item::unset_flag().
f_wants_to_talk()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_wants_to_talk (bool is_npc)
Definition at line 6168 of file npctalk.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         npc *p = d.actor( is_npc )->get_npc();
         if( p ) {
             if( p->get_attitude() == NPCATT_TALK ) {
                 return;
             }
             if( p->sees( get_player_character() ) ) {
                 add_msg( _( "%s wants to talk to you." ), p->get_name() );
             }
             p->set_attitude( NPCATT_TALK );
         }
     };
 }
References _, dialogue::actor(), add_msg(), npc::get_attitude(), Character::get_name(), talker::get_npc(), get_player_character(), NPCATT_TALK, Character::sees(), and npc::set_attitude().
Referenced by talk_effect_t::parse_string_effect().
f_weighted_list_eocs()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_weighted_list_eocs (const JsonObject & jo, std::string_view member)
Definition at line 5497 of file npctalk.cpp.
 {
     std::vector<std::pair<effect_on_condition_id, dbl_or_var>> eoc_pairs;
     for( JsonArray ja : jo.get_array( member ) ) {
         JsonValue eoc = ja.next_value();
         dbl_or_var eoc_weight;
         if( ja.test_int() ) {
             eoc_weight.min = dbl_or_var_part{ ja.next_int() };
         } else {
             eoc_weight.min = get_dbl_or_var_part( ja.next_value(), member );
         }
         eoc_pairs.emplace_back( effect_on_conditions::load_inline_eoc( eoc, "" ),
                                 eoc_weight );
     }
     return [eoc_pairs]( dialogue & d ) {
         weighted_int_list<effect_on_condition_id> eocs;
         for( const std::pair<effect_on_condition_id, dbl_or_var> &eoc_pair :
              eoc_pairs ) {
             eocs.add( eoc_pair.first, eoc_pair.second.evaluate( d ) );
         }
         effect_on_condition_id picked_eoc = *eocs.pick();
         dialogue newDialog( d );
         picked_eoc->activate( newDialog );
     };
 }
References effect_on_condition::activate(), weighted_list< W, T >::add(), eoc, JsonObject::get_array(), get_dbl_or_var_part(), effect_on_conditions::load_inline_eoc(), member, dbl_or_var::min, and weighted_list< W, T >::pick().
map_add_item()
void talk_effect_fun::anonymous_namespace{npctalk.cpp}::map_add_item (item & it, tripoint_abs_ms target_pos)
Definition at line 3111 of file npctalk.cpp.
 {
     if( get_map().inbounds( target_pos ) ) {
         get_map().add_item_or_charges( get_map().getlocal( target_pos ), it );
     } else {
         tinymap target_bay;
         target_bay.load( project_to<coords::omt>( target_pos ), false );
         target_bay.add_item_or_charges( target_bay.getlocal( target_pos ), it );
     }
 }
References tinymap::add_item_or_charges(), map::add_item_or_charges(), get_map(), tinymap::getlocal(), and tinymap::load().
Referenced by f_teleport(), and receive_item().
process_eoc()
void talk_effect_fun::anonymous_namespace{npctalk.cpp}::process_eoc (const effect_on_condition_id & eoc, dialogue & d, time_duration time_in_future)
Definition at line 5422 of file npctalk.cpp.
 {
     if( eoc->type == eoc_type::ACTIVATION ) {
         Character *alpha = d.has_alpha ? d.actor( false )->get_character() : nullptr;
         if( alpha ) {
             effect_on_conditions::queue_effect_on_condition( time_in_future, eoc, *alpha, d.get_context() );
         } else if( eoc->global ) {
             effect_on_conditions::queue_effect_on_condition( time_in_future, eoc, get_player_character(),
                     d.get_context() );
         }
         // If the target is a monster or item and the eoc is non global it won't be queued and will silently "fail"
         // this is so monster attacks against other monsters won't give error messages.
     } else {
         debugmsg( "Cannot queue a non activation effect_on_condition.  %s", d.get_callstack() );
     }
 }
References ACTIVATION, dialogue::actor(), debugmsg, eoc, dialogue::get_callstack(), talker::get_character(), dialogue::get_context(), get_player_character(), dialogue::has_alpha, and effect_on_conditions::queue_effect_on_condition().
Referenced by f_queue_eocs().
receive_item()
void talk_effect_fun::anonymous_namespace{npctalk.cpp}::receive_item (itype_id & item_name, int count, std::string_view container_name, const dialogue & d, bool use_item_group, bool suppress_message, const std::vector< std::string > & flags, bool add_talker = true, const tripoint_abs_ms & p = tripoint_abs_ms(), bool force_equip = false)
Definition at line 3122 of file npctalk.cpp.
 {
     if( use_item_group ) {
         item_group::ItemList new_items;
         new_items = item_group::items_from( item_group_id( item_name.c_str() ), calendar::turn );
         std::string popup_message;
         for( item &new_item : new_items ) {
             for( const std::string &flag : flags ) {
                 new_item.set_flag( flag_id( flag ) );
             }
             if( add_talker ) {
                 d.actor( false )->i_add_or_drop( new_item, force_equip );
             } else {
                 map_add_item( new_item, p );
             }
             if( add_talker && !suppress_message && d.has_beta && !d.actor( true )->disp_name().empty() ) {
                 if( new_item.count() == 1 ) {
                     //~ %1%s is the NPC name, %2$s is an item
                     popup_message += string_format( _( "%1$s gives you a %2$s." ), d.actor( true )->disp_name(),
                                                     new_item.tname() ) + "\n";
                 } else {
                     //~ %1%s is the NPC name, %2$d is a number of items, %3$s are items
                     popup_message += string_format( _( "%1$s gives you %2$d %3$s." ), d.actor( true )->disp_name(),
                                                     new_item.count(), new_item.tname() ) + "\n";
                 }
             }
         }
         if( !popup_message.empty() ) {
             popup( popup_message );
         }
     } else {
         item new_item = item( item_name, calendar::turn );
         for( const std::string &flag : flags ) {
             new_item.set_flag( flag_id( flag ) );
         }
         if( container_name.empty() ) {
             if( new_item.count_by_charges() ) {
                 new_item.charges = count;
                 if( add_talker ) {
                     d.actor( false )->i_add_or_drop( new_item, force_equip );
                 } else {
                     map_add_item( new_item, p );
                 }
             } else {
                 for( int i_cnt = 0; i_cnt < count; i_cnt++ ) {
                     if( !new_item.ammo_default().is_null() ) {
                         new_item.ammo_set( new_item.ammo_default() );
                     }
                     if( add_talker ) {
                         d.actor( false )->i_add_or_drop( new_item, force_equip );
                     } else {
                         map_add_item( new_item, p );
                     }
                 }
             }
             if( add_talker && !suppress_message && d.has_beta && !d.actor( true )->disp_name().empty() ) {
                 if( count == 1 ) {
                     //~ %1%s is the NPC name, %2$s is an item
                     popup( _( "%1$s gives you a %2$s." ), d.actor( true )->disp_name(), new_item.tname() );
                 } else {
                     //~ %1%s is the NPC name, %2$d is a number of items, %3$s are items
                     popup( _( "%1$s gives you %2$d %3$s." ), d.actor( true )->disp_name(), count,
                            new_item.tname() );
                 }
             }
         } else {
             item container( std::string( container_name ), calendar::turn );
             new_item.charges = count;
             container.put_in( new_item,
                               pocket_type::CONTAINER );
             if( add_talker ) {
                 d.actor( false )->i_add_or_drop( container, force_equip );
             } else {
                 map_add_item( container, p );
             }
             if( add_talker && !suppress_message && d.has_beta && !d.actor( true )->disp_name().empty() ) {
                 //~ %1%s is the NPC name, %2$s is an item
                 popup( _( "%1$s gives you a %2$s." ), d.actor( true )->disp_name(), container.tname() );
             }
         }
     }
 }
References _, dialogue::actor(), item::ammo_default(), item::ammo_set(), item::charges, CONTAINER, item::count_by_charges(), talker::disp_name(), dialogue::has_beta, talker::i_add_or_drop(), string_id< T >::is_null(), tname::item_name(), item_group::items_from(), map_add_item(), popup(), item::put_in(), item::set_flag(), string_format(), item::tname(), and calendar::turn.
Referenced by f_spawn_item(), and f_u_buy_item().