Cataclysm DDA: mission_util Namespace Reference
mission_util Namespace Reference
Functions
tripoint_abs_omt random_house_in_closest_city ()
tripoint_abs_omt target_closest_lab_entrance (const tripoint_abs_omt &origin, int reveal_rad, mission *miss)
bool reveal_road (const tripoint_abs_omt &source, const tripoint_abs_omt &dest, overmapbuffer &omb)
tripoint_abs_omt reveal_om_ter (const std::string &omter, int reveal_rad, bool must_see, int target_z=0)
Reveal the cloest overmap terrain of a type and return the its location.
tripoint_abs_omt target_om_ter (const std::string &omter, int reveal_rad, mission *miss, bool must_see, int target_z=0)
Set target of mission to closest overmap terrain of that type, reveal the area around it (uses reveal with reveal_rad), and returns the mission target.
tripoint_abs_omt target_om_ter_random (const std::string &omter, int reveal_rad, mission *miss, bool must_see, int range, tripoint_abs_omt loc=overmap::invalid_tripoint)
void set_reveal (const std::string &terrain, std::vector< std::function< void(mission *miss)>> &funcs)
void set_reveal_any (const JsonArray &ja, std::vector< std::function< void(mission *miss)>> &funcs)
mission_target_params parse_mission_om_target (const JsonObject &jo)
std::optional< tripoint_abs_omt > assign_mission_target (const mission_target_params &params, dialogue &d)
tripoint_abs_omt get_om_terrain_pos (const mission_target_params &params, dialogue &d)
void set_assign_om_target (const JsonObject &jo, std::vector< std::function< void(mission *miss)>> &funcs)
bool set_update_mapgen (const JsonObject &jo, std::vector< std::function< void(mission *miss)>> &funcs)
bool load_funcs (const JsonObject &jo, std::vector< std::function< void(mission *miss)>> &funcs)
Function Documentation
assign_mission_target()
std::optional< tripoint_abs_omt > mission_util::assign_mission_target (const mission_target_params & params, dialogue & d)
Definition at line 286 of file mission_util.cpp.
 {
     // use the player or NPC's current position, adjust for the z value if any
     tripoint_abs_omt origin_pos = get_mission_om_origin( params, d );
     std::optional<tripoint_abs_omt> target_pos = find_or_create_om_terrain( origin_pos, params, d );
     if( target_pos ) {
         if( params.offset ) {
             *target_pos += *params.offset;
         }
         // If we specified a reveal radius, then go ahead and reveal around our found position.
         if( params.reveal_radius ) {
             overmap_buffer.reveal( *target_pos, ( *params.reveal_radius ).evaluate( d ) );
         }
         // Set the mission target to our found position.
         params.mission_pointer->set_target( *target_pos );
     }
     return target_pos;
 }
References find_or_create_om_terrain(), get_mission_om_origin(), mission_target_params::mission_pointer, mission_target_params::offset, overmap_buffer, overmapbuffer::reveal(), mission_target_params::reveal_radius, and mission::set_target().
Referenced by mission_start::reveal_refugee_center(), and set_assign_om_target().
get_om_terrain_pos()
tripoint_abs_omt mission_util::get_om_terrain_pos (const mission_target_params & params, dialogue & d)
Definition at line 310 of file mission_util.cpp.
 {
     // use the player or NPC's current position, adjust for the z value if any
     tripoint_abs_omt origin_pos = get_mission_om_origin( params, d );
     tripoint_abs_omt target_pos = origin_pos;
     if( ( params.overmap_terrain.default_val.has_value() ||
           params.overmap_terrain.str_val.has_value() || params.overmap_terrain.var_val.has_value() ) &&
         !params.overmap_terrain.evaluate( d ).empty() ) {
         std::optional<tripoint_abs_omt> temp_pos = find_or_create_om_terrain( origin_pos, params, d );
         if( temp_pos ) {
             target_pos = *temp_pos;
         }
     }
     if( params.offset ) {
         target_pos += *params.offset;
     }
     // If we specified a reveal radius, then go ahead and reveal around our found position.
     if( params.reveal_radius ) {
         overmap_buffer.reveal( target_pos, ( *params.reveal_radius ).evaluate( d ) );
     }
     return target_pos;
 }
References abstract_str_or_var< T >::default_val, abstract_str_or_var< T >::evaluate(), find_or_create_om_terrain(), get_mission_om_origin(), mission_target_params::offset, overmap_buffer, mission_target_params::overmap_terrain, overmapbuffer::reveal(), mission_target_params::reveal_radius, abstract_str_or_var< T >::str_val, and abstract_str_or_var< T >::var_val.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_goal().
load_funcs()
bool mission_util::load_funcs (const JsonObject & jo, std::vector< std::function< void(mission *miss)>> & funcs)
Definition at line 500 of file mission_util.cpp.
 {
     if( jo.has_string( "reveal_om_ter" ) ) {
         const std::string target_terrain = jo.get_string( "reveal_om_ter" );
         set_reveal( target_terrain, funcs );
     } else if( jo.has_member( "reveal_om_ter" ) ) {
         set_reveal_any( jo.get_array( "reveal_om_ter" ), funcs );
     } else if( jo.has_member( "assign_mission_target" ) ) {
         JsonObject mission_target = jo.get_object( "assign_mission_target" );
         set_assign_om_target( mission_target, funcs );
     }
     if( jo.has_object( "update_mapgen" ) ) {
         JsonObject update_mapgen = jo.get_object( "update_mapgen" );
         if( !set_update_mapgen( update_mapgen, funcs ) ) {
             return false;
         }
     } else {
         for( JsonObject update_mapgen : jo.get_array( "update_mapgen" ) ) {
             if( !set_update_mapgen( update_mapgen, funcs ) ) {
                 return false;
             }
         }
     }
     return true;
 }
References JsonObject::get_array(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), set_assign_om_target(), set_reveal(), set_reveal_any(), and set_update_mapgen().
Referenced by mission_type::parse_funcs().
parse_mission_om_target()
mission_target_params mission_util::parse_mission_om_target (const JsonObject & jo)
Definition at line 380 of file mission_util.cpp.
 {
     mission_target_params p;
     if( jo.has_member( "om_terrain" ) ) {
         p.overmap_terrain = get_str_or_var( jo.get_member( "om_terrain" ), "om_terrain", true );
     }
     if( jo.has_member( "om_terrain_match_type" ) ) {
         p.overmap_terrain_match_type = jo.get_enum_value<ot_match_type>( "om_terrain_match_type" );
     }
     if( jo.get_bool( "origin_npc", false ) ) {
         p.origin_u = false;
     }
     if( jo.has_member( "om_terrain_replace" ) ) {
         p.replaceable_overmap_terrain = get_str_or_var( jo.get_member( "om_terrain_replace" ),
                                         "om_terrain_replace", true );
     }
     if( jo.has_member( "om_special" ) ) {
         p.overmap_special = get_str_or_var( jo.get_member( "om_special" ), "om_special", true );
     }
     if( jo.has_member( "reveal_radius" ) ) {
         p.reveal_radius = get_dbl_or_var( jo, "reveal_radius" );
     }
     if( jo.has_member( "must_see" ) ) {
         p.must_see = jo.get_bool( "must_see" );
     }
     if( jo.has_member( "cant_see" ) ) {
         p.cant_see = jo.get_bool( "cant_see" );
     }
     if( jo.has_member( "exclude_seen" ) ) {
         p.random = jo.get_bool( "exclude" );
     }
     if( jo.has_member( "random" ) ) {
         p.random = jo.get_bool( "random" );
     }
     p.search_range  = get_dbl_or_var( jo, "search_range", false, OMAPX );
     p.min_distance  = get_dbl_or_var( jo, "min_distance", false );
     if( jo.has_member( "offset_x" ) || jo.has_member( "offset_y" ) || jo.has_member( "offset_z" ) ) {
         tripoint_rel_omt offset;
         if( jo.has_member( "offset_x" ) ) {
             offset.x() = jo.get_int( "offset_x" );
         }
         if( jo.has_member( "offset_y" ) ) {
             offset.y() = jo.get_int( "offset_y" );
         }
         if( jo.has_member( "offset_z" ) ) {
             offset.z() = jo.get_int( "offset_z" );
         }
         p.offset = offset;
     }
     if( jo.has_member( "z" ) ) {
         p.z = get_dbl_or_var( jo, "z" );
     }
     if( jo.has_member( "var" ) ) {
         p.target_var = read_var_info( jo.get_object( "var" ) );
     }
     return p;
 }
References mission_target_params::cant_see, JsonObject::get_bool(), get_dbl_or_var(), JsonObject::get_enum_value(), JsonObject::get_int(), JsonObject::get_member(), JsonObject::get_object(), get_str_or_var(), JsonObject::has_member(), mission_target_params::min_distance, mission_target_params::must_see, mission_target_params::offset, OMAPX, mission_target_params::origin_u, mission_target_params::overmap_special, mission_target_params::overmap_terrain, mission_target_params::overmap_terrain_match_type, mission_target_params::random, read_var_info(), mission_target_params::replaceable_overmap_terrain, mission_target_params::reveal_radius, mission_target_params::search_range, mission_target_params::target_var, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and mission_target_params::z.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_goal(), and set_assign_om_target().
random_house_in_closest_city()
tripoint_abs_omt mission_util::random_house_in_closest_city ()
Definition at line 136 of file mission_util.cpp.
 {
     Character &player_character = get_player_character();
     const tripoint_abs_sm center = player_character.global_sm_location();
     const city_reference cref = overmap_buffer.closest_city( center );
     if( !cref ) {
         debugmsg( "could not find closest city" );
         return player_character.global_omt_location();
     }
     return random_house_in_city( cref );
 }
References center, overmapbuffer::closest_city(), debugmsg, get_player_character(), Creature::global_omt_location(), Creature::global_sm_location(), overmap_buffer, and random_house_in_city().
Referenced by mission_start::place_npc_software().
reveal_om_ter()
tripoint_abs_omt mission_util::reveal_om_ter (const std::string & omter, int reveal_rad, bool must_see, int target_z = 0)
Reveal the cloest overmap terrain of a type and return the its location.
Definition at line 105 of file mission_util.cpp.
 {
     // Missions are normally on z-level 0, but allow an optional argument.
     tripoint_abs_omt loc = get_player_character().global_omt_location();
     loc.z() = target_z;
     const tripoint_abs_omt place = overmap_buffer.find_closest( loc, omter, 0, must_see );
     if( place != overmap::invalid_tripoint && reveal_rad >= 0 ) {
         overmap_buffer.reveal( place, reveal_rad );
     }
     return place;
 }
References overmapbuffer::find_closest(), get_player_character(), Creature::global_omt_location(), overmap::invalid_tripoint, overmap_buffer, overmapbuffer::reveal(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by set_update_mapgen(), and target_om_ter().
reveal_road()
bool mission_util::reveal_road (const tripoint_abs_omt & source, const tripoint_abs_omt & dest, overmapbuffer & omb)
Definition at line 94 of file mission_util.cpp.
 {
     const tripoint_abs_omt source_road = overmap_buffer.find_closest( source, "road", 3, false );
     const tripoint_abs_omt dest_road = overmap_buffer.find_closest( dest, "road", 3, false );
     return omb.reveal_route( source_road, dest_road );
 }
References overmapbuffer::find_closest(), overmap_buffer, and overmapbuffer::reveal_route().
Referenced by mission_start::create_hidden_lab_console(), mission_start::create_ice_lab_console(), and mission_start::create_lab_console().
set_assign_om_target()
void mission_util::set_assign_om_target (const JsonObject & jo, std::vector< std::function< void(mission *miss)>> & funcs)
Definition at line 461 of file mission_util.cpp.
 {
     mission_target_params p = parse_mission_om_target( jo );
     auto mission_func = [p = std::move( p )]( mission * miss ) mutable {
         p.mission_pointer = miss;
         dialogue d( get_talker_for( get_avatar() ), nullptr );
         assign_mission_target( p, d );
     };
     funcs.emplace_back( std::move( mission_func ) );
 }
References assign_mission_target(), get_avatar(), get_talker_for(), mission_target_params::mission_pointer, and parse_mission_om_target().
Referenced by load_funcs().
set_reveal()
void mission_util::set_reveal (const std::string & terrain, std::vector< std::function< void(mission *miss)>> & funcs)
Definition at line 439 of file mission_util.cpp.
 {
     auto mission_func = [ terrain ]( mission * miss ) {
         reveal_target( miss, terrain );
     };
     funcs.emplace_back( std::move( mission_func ) );
 }
References reveal_target(), and terrain.
Referenced by load_funcs().
set_reveal_any()
void mission_util::set_reveal_any (const JsonArray & ja, std::vector< std::function< void(mission *miss)>> & funcs)
Definition at line 448 of file mission_util.cpp.
 {
     std::vector<std::string> terrains;
     for( const std::string terrain : ja ) {
         terrains.push_back( terrain );
     }
     auto mission_func = [ terrains = std::move( terrains ) ]( mission * miss ) {
         reveal_any_target( miss, terrains );
     };
     funcs.emplace_back( std::move( mission_func ) );
 }
References reveal_any_target(), terrain, and anonymous_namespace{overmap.cpp}::terrains.
Referenced by load_funcs().
set_update_mapgen()
bool mission_util::set_update_mapgen (const JsonObject & jo, std::vector< std::function< void(mission *miss)>> & funcs)
Definition at line 473 of file mission_util.cpp.
 {
     bool defer = false;
     mapgen_update_func update_map = add_mapgen_update_func( jo, defer );
     if( defer ) {
         jo.allow_omitted_members();
         return false;
     }
     if( jo.has_member( "om_terrain" ) ) {
         const std::string om_terrain = jo.get_string( "om_terrain" );
         auto mission_func = [update_map = std::move( update_map ), om_terrain]( mission * miss ) {
             tripoint_abs_omt update_pos3 = mission_util::reveal_om_ter( om_terrain, 1, false );
             update_map( update_pos3, miss );
         };
         funcs.emplace_back( std::move( mission_func ) );
     } else {
         auto mission_func = [update_map = std::move( update_map )]( mission * miss ) {
             tripoint_abs_omt update_pos3 = miss->get_target();
             update_map( update_pos3, miss );
         };
         funcs.emplace_back( std::move( mission_func ) );
     }
     return true;
 }
References add_mapgen_update_func(), JsonObject::allow_omitted_members(), mapgen_defer::defer, JsonObject::get_string(), mission::get_target(), JsonObject::has_member(), and reveal_om_ter().
Referenced by load_funcs().
target_closest_lab_entrance()
tripoint_abs_omt mission_util::target_closest_lab_entrance (const tripoint_abs_omt & origin, int reveal_rad, mission * miss)
Definition at line 148 of file mission_util.cpp.
 {
     tripoint_abs_omt testpoint = origin;
     // Get the surface locations for labs and for spaces above hidden lab stairs.
     testpoint.z() = 0;
     tripoint_abs_omt surface = overmap_buffer.find_closest( testpoint, "lab_stairs", 0, false,
                                ot_match_type::contains );
     testpoint.z() = -1;
     tripoint_abs_omt underground =
         overmap_buffer.find_closest( testpoint, "hidden_lab_stairs", 0, false,
                                      ot_match_type::contains );
     underground.z() = 0;
     tripoint_abs_omt closest;
     if( square_dist( surface.xy(), origin.xy() ) <= square_dist( underground.xy(), origin.xy() ) ) {
         closest = surface;
     } else {
         closest = underground;
     }
     if( closest != overmap::invalid_tripoint && reveal_rad >= 0 ) {
         overmap_buffer.reveal( closest, reveal_rad );
     }
     miss->set_target( closest );
     return closest;
 }
References contains, overmapbuffer::find_closest(), overmap::invalid_tripoint, overmap_buffer, overmapbuffer::reveal(), mission::set_target(), square_dist(), coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by mission_start::create_hidden_lab_console(), mission_start::create_ice_lab_console(), and mission_start::create_lab_console().
target_om_ter()
tripoint_abs_omt mission_util::target_om_ter (const std::string & omter, int reveal_rad, mission * miss, bool must_see, int target_z = 0)
Set target of mission to closest overmap terrain of that type, reveal the area around it (uses reveal with reveal_rad), and returns the mission target.
Definition at line 342 of file mission_util.cpp.
 {
     const tripoint_abs_omt place = reveal_om_ter( omter, reveal_rad, must_see, target_z );
     miss->set_target( place );
     return place;
 }
References reveal_om_ter(), and mission::set_target().
target_om_ter_random()
tripoint_abs_omt mission_util::target_om_ter_random (const std::string & omter, int reveal_rad, mission * miss, bool must_see, int range, tripoint_abs_omt loc = overmap::invalid_tripoint)
Definition at line 350 of file mission_util.cpp.
 {
     Character &player_character = get_player_character();
     if( loc == overmap::invalid_tripoint ) {
         loc = player_character.global_omt_location();
     }
     auto places = overmap_buffer.find_all( loc, omter, range, must_see );
     if( places.empty() ) {
         return player_character.global_omt_location();
     }
     const overmap *loc_om = overmap_buffer.get_existing_om_global( loc ).om;
     cata_assert( loc_om );
     std::vector<tripoint_abs_omt> places_om;
     for( auto &i : places ) {
         if( loc_om == overmap_buffer.get_existing_om_global( i ).om ) {
             places_om.push_back( i );
         }
     }
     const tripoint_abs_omt place = random_entry( places_om );
     if( reveal_rad >= 0 ) {
         overmap_buffer.reveal( place, reveal_rad );
     }
     miss->set_target( place );
     return place;
 }
References cata_assert, overmapbuffer::find_all(), overmapbuffer::get_existing_om_global(), get_player_character(), Creature::global_omt_location(), overmap::invalid_tripoint, overmap_with_local_coords::om, overmap_buffer, random_entry(), overmapbuffer::reveal(), and mission::set_target().
Referenced by create_lab_consoles().