Cataclysm DDA: avatar_action Namespace Reference
avatar_action Namespace Reference
Functions
void eat (avatar &you, item_location &loc)
Eat food or fuel 'E' (or 'a')
void eat (avatar &you, item_location &loc, const std::vector< int > &consume_menu_selections, const std::vector< item_location > &consume_menu_selected_items, const std::string &consume_menu_filter, activity_id type)
bool eat_here (avatar &you)
void eat_or_use (avatar &you, item_location loc)
bool move (avatar &you, map &m, const tripoint &d)
bool move (avatar &you, map &m, const point &d)
bool ramp_move (avatar &you, map &m, const tripoint &dest)
void swim (map &m, avatar &you, const tripoint &p)
Handles swimming by the player.
void autoattack (avatar &you, map &m)
void mend (avatar &you, item_location loc)
bool can_fire_weapon (avatar &you, const map &m, const item &weapon)
Checks if the weapon is valid and if the player meets certain conditions for firing it.
void fire_wielded_weapon (avatar &you)
Checks if the wielded weapon is a gun and can be fired then starts interactive aiming.
void fire_ranged_mutation (Character &you, const item &fake_gun)
Stores fake gun specified by the mutation and starts interactive aiming.
void fire_ranged_bionic (avatar &you, const item &fake_gun)
Stores fake gun specified by the bionic and starts interactive aiming.
bool fire_turret_manual (avatar &you, map &m, turret_data &turret)
Checks if the player can manually (with their 2 hands, not via vehicle controls) fire a turret and then starts interactive aiming.
void plthrow (avatar &you, item_location loc, const std::optional< tripoint > &blind_throw_from_pos=std::nullopt)
void unload (avatar &you)
void use_item (avatar &you, item_location &loc, std::string const &method={})
void use_item (avatar &you)
bool check_stealing (Character &who, item &weapon)
Check if avatar is stealing a weapon.
Function Documentation
autoattack()
void avatar_action::autoattack (avatar & you, map & m)
Definition at line 715 of file avatar_action.cpp.
 {
     const item_location weapon = you.get_wielded_item();
     int reach = weapon ? weapon->reach_range( you ) : 1;
     std::vector<Creature *> critters = you.get_targetable_creatures( reach, true );
     critters.erase( std::remove_if( critters.begin(), critters.end(), [&you,
     reach]( const Creature * c ) {
         if( reach == 1 && !you.is_adjacent( c, true ) ) {
             return true;
         }
         if( !c->is_npc() ) {
             return false;
         }
         return !dynamic_cast<const npc &>( *c ).is_enemy();
     } ), critters.end() );
     if( critters.empty() ) {
         add_msg( m_info, _( "No hostile creature in reach.  Waiting a turn." ) );
         if( g->check_safe_mode_allowed() ) {
             you.pause();
         }
         return;
     }
     Creature &best = **std::max_element( critters.begin(), critters.end(),
     []( const Creature * l, const Creature * r ) {
         return rate_critter( *l ) > rate_critter( *r );
     } );
     const tripoint diff = best.pos() - you.pos();
     if( std::abs( diff.x ) <= 1 && std::abs( diff.y ) <= 1 && diff.z == 0 ) {
         move( you, m, tripoint( diff.xy(), 0 ) );
         return;
     }
     you.reach_attack( best.pos() );
 }
References c, Character::get_targetable_creatures(), Character::get_wielded_item(), npc::is_enemy(), and item::reach_range().
Referenced by game::do_regular_action().
can_fire_weapon()
bool avatar_action::can_fire_weapon (avatar & you, const map & m, const item & weapon)
Checks if the weapon is valid and if the player meets certain conditions for firing it.
Used for validating ACT_AIM and turret weapon
Returns
True if all conditions are true, otherwise false.
Definition at line 753 of file avatar_action.cpp.
 {
     if( !weapon.is_gun() ) {
         debugmsg( "Expected item to be a gun" );
         return false;
     }
     if( !you.try_break_relax_gas( _( "Your eyes steel, and you raise your weapon!" ),
                                   _( "You can't fire your weapon, it's too heavy…" ) ) ) {
         return false;
     }
     std::vector<std::string> messages;
     for( const std::pair<const gun_mode_id, gun_mode> &mode_map : weapon.gun_all_modes() ) {
         bool check_common = gunmode_checks_common( you, m, messages, mode_map.second );
         bool check_weapon = gunmode_checks_weapon( you, m, messages, mode_map.second );
         bool can_use_mode = check_common && check_weapon;
         if( can_use_mode ) {
             return true;
         }
     }
     for( const std::string &message : messages ) {
         add_msg( m_info, message );
     }
     return false;
 }
References _, add_msg(), debugmsg, item::gun_all_modes(), gunmode_checks_common(), gunmode_checks_weapon(), item::is_gun(), m_info, mapgen_defer::message, and avatar::try_break_relax_gas().
Referenced by aim_activity_actor::do_turn().
check_stealing()
bool avatar_action::check_stealing (Character & who, item & weapon)
Check if avatar is stealing a weapon.
Definition at line 6022 of file activity_actor.cpp.
 {
     return ::check_stealing( who, weapon );
 }
References check_stealing().
Referenced by game::wield().
eat() [1/2]
void avatar_action::eat (avatar & you, item_location & loc)
Eat food or fuel 'E' (or 'a')
Definition at line 946 of file avatar_action.cpp.
 {
     std::string filter;
     if( !you.activity.str_values.empty() ) {
         filter = you.activity.str_values.back();
     }
     avatar_action::eat( you, loc, you.activity.values, you.activity.targets, filter,
                         you.activity.id() );
 }
References Character::activity, filter, player_activity::id(), player_activity::str_values, player_activity::targets, and player_activity::values.
Referenced by activity_handlers::consume_drink_menu_do_turn(), activity_handlers::consume_food_menu_do_turn(), eat_or_use(), game::inventory_item_menu(), and game::open_consume_item_menu().
eat() [2/2]
void avatar_action::eat (avatar & you, item_location & loc, const std::vector< int > & consume_menu_selections, const std::vector< item_location > & consume_menu_selected_items, const std::string & consume_menu_filter, activity_id type)
Definition at line 956 of file avatar_action.cpp.
 {
     if( !loc ) {
         you.cancel_activity();
         add_msg( _( "Never mind." ) );
         return;
     }
     loc.overflow();
     you.assign_activity( consume_activity_actor( loc, consume_menu_selections,
                          consume_menu_selected_items, consume_menu_filter, type ) );
     you.last_item = item( *loc ).typeId();
 }
References _, add_msg(), Character::assign_activity(), Character::cancel_activity(), Character::last_item, item_location::overflow(), and item::typeId().
eat_here()
bool avatar_action::eat_here (avatar & you)
Definition at line 885 of file avatar_action.cpp.
 {
     map &here = get_map();
     if( ( you.has_active_mutation( trait_RUMINANT ) || you.has_active_mutation( trait_GRAZER ) ) &&
         ( here.has_flag( ter_furn_flag::TFLAG_SHRUB, you.pos() ) &&
           !here.has_flag( ter_furn_flag::TFLAG_GRAZER_INEDIBLE, you.pos() ) ) ) {
         if( you.has_effect( effect_hunger_engorged ) ) {
             add_msg( _( "You're too full to eat the leaves from the %s." ), here.ter( you.pos() )->name() );
             return true;
         } else {
             here.ter_set( you.pos(), ter_t_grass );
             item food( "underbrush", calendar::turn, 1 );
             you.assign_activity( consume_activity_actor( food ) );
             return true;
         }
     }
     if( ( you.has_active_mutation( trait_RUMINANT ) || you.has_active_mutation( trait_GRAZER ) ) &&
         ( here.has_flag( ter_furn_flag::TFLAG_FLOWER, you.pos() ) &&
           !here.has_flag( ter_furn_flag::TFLAG_GRAZER_INEDIBLE, you.pos() ) ) ) {
         if( you.has_effect( effect_hunger_engorged ) ) {
             add_msg( _( "You're too full to eat the %s." ), here.ter( you.pos() )->name() );
             return true;
         } else {
             here.furn_set( you.pos(), furn_str_id::NULL_ID() );
             item food( "small_plant", calendar::turn, 1 );
             you.assign_activity( consume_activity_actor( food ) );
             return true;
         }
     }
     if( you.has_active_mutation( trait_GRAZER ) &&
         ( here.has_flag( ter_furn_flag::TFLAG_GRAZABLE, you.pos() ) &&
           !here.has_flag( ter_furn_flag::TFLAG_FUNGUS, you.pos() ) ) ) {
         if( you.has_effect( effect_hunger_engorged ) ) {
             add_msg( _( "You're too full to graze." ) );
             return true;
         } else {
             item food( item( "grass", calendar::turn, 1 ) );
             you.assign_activity( consume_activity_actor( food ) );
             here.ter_set( you.pos(), here.get_ter_transforms_into( you.pos() ) );
             return true;
         }
     }
     if( you.has_active_mutation( trait_GRAZER ) ) {
         const ter_id &ter_underfoot = here.ter( you.pos() );
         if( ter_underfoot == ter_t_grass_golf || ter_underfoot == ter_t_grass ) {
             add_msg( _( "This grass is too short to graze." ) );
             return true;
         } else if( ter_underfoot == ter_t_grass_dead ) {
             add_msg( _( "This grass is dead and too mangled for you to graze." ) );
             return true;
         } else if( ter_underfoot == ter_t_grass_white ) {
             add_msg( _( "This grass is tainted with paint and thus inedible." ) );
             return true;
         } else if( ter_underfoot == ter_t_grass_alien ) {
             add_msg( _( "This grass is razor sharp and would probably shred your mouth." ) );
             return true;
         }
     }
     return false;
 }
References _, add_msg(), Character::assign_activity(), effect_hunger_engorged, map::furn_set(), get_map(), map::get_ter_transforms_into(), Character::has_active_mutation(), Creature::has_effect(), map::has_flag(), map_data_common_t::name(), string_id< furn_t >::NULL_ID(), Creature::pos(), map::ter(), map::ter_set(), ter_t_grass, ter_t_grass_alien, ter_t_grass_dead, ter_t_grass_golf, ter_t_grass_white, TFLAG_FLOWER, TFLAG_FUNGUS, TFLAG_GRAZABLE, TFLAG_GRAZER_INEDIBLE, TFLAG_SHRUB, trait_GRAZER, trait_RUMINANT, and calendar::turn.
Referenced by game::do_regular_action().
eat_or_use()
void avatar_action::eat_or_use (avatar & you, item_location loc)
Definition at line 973 of file avatar_action.cpp.
 {
     if( loc && loc->is_medical_tool() ) {
         avatar_action::use_item( you, loc, "heal" );
     } else {
         avatar_action::eat( you, loc );
     }
 }
References eat(), item::is_medical_tool(), and use_item().
Referenced by activity_handlers::consume_meds_menu_do_turn(), game::do_regular_action(), activity_handlers::eat_menu_do_turn(), game::inventory_item_menu(), and game::open_consume_item_menu().
fire_ranged_bionic()
void avatar_action::fire_ranged_bionic (avatar & you, const item & fake_gun)
Stores fake gun specified by the bionic and starts interactive aiming.
Definition at line 812 of file avatar_action.cpp.
 {
     you.assign_activity( aim_activity_actor::use_bionic( fake_gun ) );
 }
References Character::assign_activity(), and aim_activity_actor::use_bionic().
Referenced by Character::activate_bionic().
fire_ranged_mutation()
void avatar_action::fire_ranged_mutation (Character & you, const item & fake_gun)
Stores fake gun specified by the mutation and starts interactive aiming.
Definition at line 807 of file avatar_action.cpp.
 {
     you.assign_activity( aim_activity_actor::use_mutation( fake_gun ) );
 }
References Character::assign_activity(), and aim_activity_actor::use_mutation().
Referenced by Character::activate_mutation().
fire_turret_manual()
bool avatar_action::fire_turret_manual (avatar & you, map & m, turret_data & turret)
Checks if the player can manually (with their 2 hands, not via vehicle controls) fire a turret and then starts interactive aiming.
Assumes that the turret is on player position.
Returns
true if attempt to fire was successful (aim then cancel is also considered success)
Definition at line 817 of file avatar_action.cpp.
 {
     if( !turret.base()->is_gun() ) {
         debugmsg( "Expected turret base to be a gun." );
         return false;
     }
     switch( turret.query() ) {
         case turret_data::status::no_ammo:
             add_msg( m_bad, _( "The %s is out of ammo." ), turret.name() );
             return false;
         case turret_data::status::no_power:
             add_msg( m_bad, _( "The %s is not powered." ), turret.name() );
             return false;
         case turret_data::status::ready:
             break;
         default:
             debugmsg( "Unknown turret status" );
             return false;
     }
     // check if any gun modes are usable
     std::vector<std::string> messages;
     const std::map<gun_mode_id, gun_mode> gunmodes = turret.base()->gun_all_modes();
     if( !std::any_of( gunmodes.begin(), gunmodes.end(),
     [&you, &m, &messages]( const std::pair<const gun_mode_id, gun_mode> &p ) {
     return gunmode_checks_common( you, m, messages, p.second );
     } ) ) {
         // no gunmode is usable, dump reason messages why not
         for( const std::string &msg : messages ) {
             add_msg( m_bad, msg );
         }
         return false;
     }
     // all checks passed - start aiming
     g->temp_exit_fullscreen();
     target_handler::trajectory trajectory = target_handler::mode_turret_manual( you, turret );
     if( !trajectory.empty() ) {
         turret.fire( you, trajectory.back() );
     }
     g->reenter_fullscreen();
     return true;
 }
References _, add_msg(), turret_data::base(), debugmsg, turret_data::fire(), g, item::gun_all_modes(), item::is_gun(), m_bad, target_handler::mode_turret_manual(), turret_data::name(), turret_data::no_ammo, turret_data::no_power, turret_data::query(), and turret_data::ready.
Referenced by fire().
fire_wielded_weapon()
void avatar_action::fire_wielded_weapon (avatar & you)
Checks if the wielded weapon is a gun and can be fired then starts interactive aiming.
Definition at line 782 of file avatar_action.cpp.
 {
     const item_location weapon = you.get_wielded_item();
     if( !weapon ) {
         return;
     }
     if( weapon->is_gunmod() ) {
         add_msg( m_info,
                  _( "The %s must be attached to a gun, it can not be fired separately." ),
                  weapon->tname() );
         return;
     } else if( !weapon->is_gun() ) {
         return;
     } else if( weapon->ammo_data() &&
                !weapon->ammo_types().count( weapon->loaded_ammo().ammo_type() ) ) {
         add_msg( m_info, _( "The %s can't be fired while loaded with incompatible ammunition %s" ),
                  weapon->tname(), weapon->ammo_current()->nname( 1 ) );
         return;
     }
     you.assign_activity( aim_activity_actor::use_wielded() );
 }
References _, add_msg(), item::ammo_current(), item::ammo_data(), item::ammo_type(), item::ammo_types(), Character::assign_activity(), Character::get_wielded_item(), item::is_gun(), item::is_gunmod(), item::loaded_ammo(), m_info, itype::nname(), item::tname(), and aim_activity_actor::use_wielded().
Referenced by game::do_regular_action(), and fire().
mend()
void avatar_action::mend (avatar & you, item_location loc)
Definition at line 863 of file avatar_action.cpp.
 {
     if( you.fine_detail_vision_mod() > 4 ) {
         add_msg( m_bad, _( "It's too dark to work on mending this." ) );
         return;
     }
     if( !loc ) {
         if( you.is_armed() ) {
             loc = you.get_wielded_item();
         } else {
             add_msg( m_info, _( "You're not wielding anything." ) );
             return;
         }
     }
     if( you.has_item( *loc ) ) {
         you.mend_item( item_location( loc ) );
     }
 }
References _, add_msg(), Character::fine_detail_vision_mod(), Character::get_wielded_item(), visitable::has_item(), Character::is_armed(), m_bad, m_info, and Character::mend_item().
Referenced by game::do_regular_action(), and game::inventory_item_menu().
move() [1/2]
bool avatar_action::move (avatar & you, map & m, const point & d) inline
Definition at line 36 of file avatar_action.h.
 {
     return move( you, m, tripoint( d, 0 ) );
 }
References move().
move() [2/2]
bool avatar_action::move (avatar & you, map & m, const tripoint & d)
Definition at line 173 of file avatar_action.cpp.
 {
     bool in_shell = you.has_active_mutation( trait_SHELL2 ) ||
                     you.has_active_mutation( trait_SHELL3 );
     if( ( !g->check_safe_mode_allowed() ) || in_shell ) {
         if( in_shell ) {
             add_msg( m_warning, _( "You can't move while in your shell.  Deactivate it to go mobile." ) );
         }
         return false;
     }
     // If any leg broken without crutches and not already on the ground topple over
     if( ( !you.enough_working_legs() && !you.is_prone() &&
           !( you.get_wielded_item() && you.get_wielded_item()->has_flag( flag_CRUTCHES ) ) ) ) {
         you.set_movement_mode( move_mode_prone );
         you.add_msg_if_player( m_bad,
                                _( "Your broken legs can't hold your weight and you fall down in pain." ) );
     }
     const bool is_riding = you.is_mounted();
     tripoint dest_loc;
     if( d.z == 0 && ( you.has_effect( effect_stunned ) || you.has_effect( effect_psi_stunned ) ) ) {
         dest_loc.x = rng( you.posx() - 1, you.posx() + 1 );
         dest_loc.y = rng( you.posy() - 1, you.posy() + 1 );
         dest_loc.z = you.posz();
     } else {
         dest_loc.x = you.posx() + d.x;
         dest_loc.y = you.posy() + d.y;
         dest_loc.z = you.posz() + d.z;
     }
     if( dest_loc == you.pos() ) {
         // Well that sure was easy
         return true;
     }
     bool via_ramp = false;
     if( m.has_flag( ter_furn_flag::TFLAG_RAMP_UP, dest_loc ) ) {
         dest_loc.z += 1;
         via_ramp = true;
     } else if( m.has_flag( ter_furn_flag::TFLAG_RAMP_DOWN, dest_loc ) ) {
         dest_loc.z -= 1;
         via_ramp = true;
     }
     item_location weapon = you.get_wielded_item();
     if( m.has_flag( ter_furn_flag::TFLAG_MINEABLE, dest_loc ) && g->mostseen == 0 &&
         get_option<bool>( "AUTO_FEATURES" ) && get_option<bool>( "AUTO_MINING" ) &&
         !m.veh_at( dest_loc ) && !you.is_underwater() && !you.has_effect( effect_stunned ) &&
         !you.has_effect( effect_psi_stunned ) && !is_riding && !you.has_effect( effect_incorporeal ) ) {
         if( weapon && weapon->has_flag( flag_DIG_TOOL ) ) {
             if( weapon->type->can_use( "JACKHAMMER" ) &&
                 weapon->ammo_sufficient( &you ) ) {
                 you.invoke_item( &*weapon, "JACKHAMMER", dest_loc );
                 // don't move into the tile until done mining
                 you.defer_move( dest_loc );
                 return true;
             } else if( weapon->type->can_use( "PICKAXE" ) ) {
                 you.invoke_item( &*weapon, "PICKAXE", dest_loc );
                 // don't move into the tile until done mining
                 you.defer_move( dest_loc );
                 return true;
             }
         }
     }
     // by this point we're either walking, running, crouching, or attacking, so update the activity level to match
     if( !is_riding ) {
         you.set_activity_level( you.enchantment_cache->modify_value(
                                     enchant_vals::mod::MOVEMENT_EXERTION_MODIFIER, you.current_movement_mode()->exertion_level() ) );
     }
     // If the player is *attempting to* move on the X axis, update facing direction of their sprite to match.
     point new_d( dest_loc.xy() + point( -you.posx(), -you.posy() ) );
     if( !g->is_tileset_isometric() ) {
         if( new_d.x > 0 ) {
             you.facing = FacingDirection::RIGHT;
             if( is_riding ) {
                 you.mounted_creature->facing = FacingDirection::RIGHT;
             }
         } else if( new_d.x < 0 ) {
             you.facing = FacingDirection::LEFT;
             if( is_riding ) {
                 you.mounted_creature->facing = FacingDirection::LEFT;
             }
         }
     } else {
         //
         // iso:
         //
         // right key            =>  +x -y       FacingDirection::RIGHT
         // left key             =>  -x +y       FacingDirection::LEFT
         // up key               =>  +x +y       ______
         // down key             =>  -x -y       ______
         // y: left-up key       =>  __ +y       FacingDirection::LEFT
         // u: right-up key      =>  +x __       FacingDirection::RIGHT
         // b: left-down key     =>  -x __       FacingDirection::LEFT
         // n: right-down key    =>  __ -y       FacingDirection::RIGHT
         //
         // right key            =>  +x -y       FacingDirection::RIGHT
         // u: right-up key      =>  +x __       FacingDirection::RIGHT
         // n: right-down key    =>  __ -y       FacingDirection::RIGHT
         // up key               =>  +x +y       ______
         // down key             =>  -x -y       ______
         // left key             =>  -x +y       FacingDirection::LEFT
         // y: left-up key       =>  __ +y       FacingDirection::LEFT
         // b: left-down key     =>  -x __       FacingDirection::LEFT
         //
         // right key            =>  +x +y       FacingDirection::RIGHT
         // u: right-up key      =>  +x __       FacingDirection::RIGHT
         // n: right-down key    =>  __ +y       FacingDirection::RIGHT
         // up key               =>  +x -y       ______
         // left key             =>  -x -y       FacingDirection::LEFT
         // b: left-down key     =>  -x __       FacingDirection::LEFT
         // y: left-up key       =>  __ -y       FacingDirection::LEFT
         // down key             =>  -x +y       ______
         //
         if( new_d.x >= 0 && new_d.y >= 0 ) {
             you.facing = FacingDirection::RIGHT;
             if( is_riding ) {
                 auto *mons = you.mounted_creature.get();
                 mons->facing = FacingDirection::RIGHT;
             }
         }
         if( new_d.y <= 0 && new_d.x <= 0 ) {
             you.facing = FacingDirection::LEFT;
             if( is_riding ) {
                 auto *mons = you.mounted_creature.get();
                 mons->facing = FacingDirection::LEFT;
             }
         }
     }
     if( you.has_effect( effect_amigara ) ) {
         int curdist = INT_MAX;
         int newdist = INT_MAX;
         const tripoint minp = tripoint( 0, 0, you.posz() );
         const tripoint maxp = tripoint( MAPSIZE_X, MAPSIZE_Y, you.posz() );
         for( const tripoint &pt : m.points_in_rectangle( minp, maxp ) ) {
             if( m.ter( pt ) == ter_t_fault ) {
                 int dist = rl_dist( pt, you.pos() );
                 if( dist < curdist ) {
                     curdist = dist;
                 }
                 dist = rl_dist( pt, dest_loc );
                 if( dist < newdist ) {
                     newdist = dist;
                 }
             }
         }
         if( newdist > curdist ) {
             add_msg( m_info, _( "You cannot pull yourself away from the faultline…" ) );
             return false;
         }
     }
     dbg( D_PEDANTIC_INFO ) << "game:plmove: From (" <<
                            you.posx() << "," << you.posy() << "," << you.posz() << ") to (" <<
                            dest_loc.x << "," << dest_loc.y << "," << dest_loc.z << ")";
     if( g->disable_robot( dest_loc ) ) {
         return false;
     }
     // Check if our movement is actually an attack on a monster or npc
     // Are we displacing a monster?
     creature_tracker &creatures = get_creature_tracker();
     bool attacking = false;
     if( creatures.creature_at( dest_loc ) ) {
         attacking = true;
     }
     if( !you.move_effects( attacking ) ) {
         // move_effects determined we could not move, waste all moves
         you.set_moves( 0 );
         return false;
     }
     if( monster *const mon_ptr = creatures.creature_at<monster>( dest_loc, true ) ) {
         monster &critter = *mon_ptr;
         if( critter.friendly == 0 &&
             !critter.has_effect( effect_pet ) ) {
             if( you.is_auto_moving() ) {
                 add_msg( m_warning, _( "Monster in the way.  Auto move canceled." ) );
                 add_msg( m_info, _( "Move into the monster to attack." ) );
                 you.clear_destination();
                 return false;
             }
             if( !you.try_break_relax_gas( _( "Your willpower asserts itself, and so do you!" ),
                                           _( "You're too pacified to strike anything…" ) ) ) {
                 return false;
             }
             bool safe_mode = ( get_option<bool>( "SAFEMODE" ) ? SAFE_MODE_ON : SAFE_MODE_OFF );
             if( safe_mode ) {
                 // If safe mode is enabled, only allow attacking neutral creatures when it is inactive
                 if( critter.attitude_to( you ) == Creature::Attitude::NEUTRAL &&
                     g->safe_mode != SAFE_MODE_OFF ) {
                     const std::string msg_safe_mode = press_x( ACTION_TOGGLE_SAFEMODE );
                     add_msg( m_warning,
                              _( "Not attacking the %1$s -- safe mode is on!  (%2$s to turn it off)" ), critter.name(),
                              msg_safe_mode );
                     return false;
                 }
             } else {
                 // If safe mode is disabled, ask for confirmation before attacking a neutral creature
                 if( critter.attitude_to( you ) == Creature::Attitude::NEUTRAL &&
                     !query_yn( _( "You may be attacked!  Proceed?" ) ) ) {
                     return false;
                 }
             }
             you.melee_attack( critter, true );
             if( critter.is_hallucination() ) {
                 critter.die( &you );
             }
             g->draw_hit_mon( dest_loc, critter, critter.is_dead() );
             return false;
         } else if( critter.has_flag( mon_flag_IMMOBILE ) || critter.has_effect( effect_harnessed ) ||
                    critter.has_effect( effect_ridden ) ) {
             add_msg( m_info, _( "You can't displace your %s." ), critter.name() );
             return false;
         }
         // Successful displacing is handled (much) later
     }
     // If not a monster, maybe there's an NPC there
     if( npc *const np_ = creatures.creature_at<npc>( dest_loc ) ) {
         npc &np = *np_;
         if( you.is_auto_moving() ) {
             add_msg( _( "NPC in the way, Auto move canceled." ) );
             add_msg( m_info, _( "Move into the NPC to interact or attack." ) );
             you.clear_destination();
             return false;
         }
         if( !np.is_enemy() ) {
             g->npc_menu( np );
             return false;
         }
         you.melee_attack( np, true );
         np.make_angry();
         return false;
     }
     // GRAB: pre-action checking.
     int dpart = -1;
     const optional_vpart_position vp0 = m.veh_at( you.pos() );
     vehicle *const veh0 = veh_pointer_or_null( vp0 );
     const optional_vpart_position vp1 = m.veh_at( dest_loc );
     vehicle *const veh1 = veh_pointer_or_null( vp1 );
     bool veh_closed_door = false;
     bool outside_vehicle = veh0 == nullptr || veh0 != veh1;
     if( veh1 != nullptr ) {
         dpart = veh1->next_part_to_open( vp1->part_index(), outside_vehicle );
         veh_closed_door = dpart >= 0 && !veh1->part( dpart ).open;
     }
     if( veh0 != nullptr && std::abs( veh0->velocity ) > 100 ) {
         if( veh1 == nullptr ) {
             if( query_yn( _( "Dive from moving vehicle?" ) ) ) {
                 g->moving_vehicle_dismount( dest_loc );
             }
             return false;
         } else if( veh1 != veh0 ) {
             add_msg( m_info, _( "There is another vehicle in the way." ) );
             return false;
         } else if( !vp1.part_with_feature( "BOARDABLE", true ) ) {
             add_msg( m_info, _( "That part of the vehicle is currently unsafe." ) );
             return false;
         }
     }
     bool toSwimmable = m.has_flag( ter_furn_flag::TFLAG_SWIMMABLE, dest_loc ) &&
                        !m.has_flag_furn( "BRIDGE", dest_loc );
     bool toDeepWater = m.has_flag( ter_furn_flag::TFLAG_DEEP_WATER, dest_loc ) &&
                        !m.has_flag_furn( "BRIDGE", dest_loc );
     bool fromSwimmable = m.has_flag( ter_furn_flag::TFLAG_SWIMMABLE, you.pos() );
     bool fromDeepWater = m.has_flag( ter_furn_flag::TFLAG_DEEP_WATER, you.pos() );
     bool fromBoat = veh0 != nullptr;
     bool toBoat = veh1 != nullptr;
     if( is_riding ) {
         if( !you.check_mount_will_move( dest_loc ) ) {
             if( you.is_auto_moving() ) {
                 you.clear_destination();
             }
             you.mod_moves( -you.get_speed() * 0.2 );
             return false;
         }
     }
     // Dive into water!
     if( toSwimmable && toDeepWater && !toBoat ) {
         // Requires confirmation if we were on dry land previously
         if( is_riding ) {
             auto *mon = you.mounted_creature.get();
             if( !mon->swims() || mon->get_size() < you.get_size() + 2 ) {
                 add_msg( m_warning, _( "The %s cannot swim while it is carrying you!" ), mon->get_name() );
                 return false;
             }
         }
         if( ( fromSwimmable && fromDeepWater && !fromBoat ) ||
             check_water_affect_items( you ) ) {
             if( ( !fromDeepWater || fromBoat ) && you.swim_speed() < 500 ) {
                 add_msg( _( "You start swimming." ) );
                 add_msg( m_info, _( "%s to dive underwater." ),
                          press_x( ACTION_MOVE_DOWN ) );
             }
             avatar_action::swim( get_map(), get_avatar(), dest_loc );
         }
         g->on_move_effects();
         return true;
     }
     //Wooden Fence Gate (or equivalently walkable doors):
     // open it if we are walking
     // vault over it if we are running
     std::string door_name = m.obstacle_name( dest_loc );
     if( m.passable_ter_furn( dest_loc )
         && you.is_walking()
         && !veh_closed_door
         && m.open_door( you, dest_loc, !m.is_outside( you.pos() ) ) ) {
         you.mod_moves( -you.get_speed() );
         you.add_msg_if_player( _( "You open the %s." ), door_name );
         // if auto move is on, continue moving next turn
         if( you.is_auto_moving() ) {
             you.defer_move( dest_loc );
         }
         return true;
     }
     if( g->walk_move( dest_loc, via_ramp ) ) {
         return true;
     }
     if( g->phasing_move( dest_loc ) ) {
         return true;
     }
     if( veh_closed_door ) {
         if( !veh1->handle_potential_theft( you ) ) {
             return true;
         } else {
             door_name = veh1->part( dpart ).name();
             if( outside_vehicle ) {
                 veh1->open_all_at( dpart );
             } else {
                 veh1->open( dpart );
             }
             //~ %1$s - vehicle name, %2$s - part name
             you.add_msg_if_player( _( "You open the %1$s's %2$s." ), veh1->name, door_name );
         }
         you.mod_moves( -you.get_speed() );
         // if auto move is on, continue moving next turn
         if( you.is_auto_moving() ) {
             you.defer_move( dest_loc );
         }
         return true;
     }
     if( m.furn( dest_loc ) != furn_f_safe_c &&
         m.open_door( you, dest_loc, !m.is_outside( you.pos() ) ) ) {
         you.mod_moves( -you.get_speed() );
         if( veh1 != nullptr ) {
             //~ %1$s - vehicle name, %2$s - part name
             you.add_msg_if_player( _( "You open the %1$s's %2$s." ), veh1->name, door_name );
         } else {
             you.add_msg_if_player( _( "You open the %s." ), door_name );
         }
         // if auto move is on, continue moving next turn
         if( you.is_auto_moving() ) {
             you.defer_move( dest_loc );
         }
         return true;
     }
     // Invalid move
     const bool waste_moves = you.is_blind() || you.has_effect( effect_stunned );
     if( waste_moves || dest_loc.z != you.posz() ) {
         add_msg( _( "You bump into the %s!" ), m.obstacle_name( dest_loc ) );
         // Only lose movement if we're blind
         if( waste_moves ) {
             you.mod_moves( -you.get_speed() );
         }
     } else if( m.ter( dest_loc ) == ter_t_door_bar_locked ) {
         add_msg( _( "You rattle the bars but the door is locked!" ) );
     } else if( const std::unordered_set<ter_str_id> locked_doors = { ter_t_door_locked, ter_t_door_locked_peep, ter_t_door_locked_alarm, ter_t_door_locked_interior };
                locked_doors.find( m.ter( dest_loc ).id() ) != locked_doors.end() ) {
         // Don't drain move points for learning something you could learn just by looking
         add_msg( _( "That door is locked!" ) );
     }
     return false;
 }
References _, abs(), ACTION_MOVE_DOWN, ACTION_TOGGLE_SAFEMODE, add_msg(), Character::add_msg_if_player(), item::ammo_sufficient(), monster::attitude_to(), itype::can_use(), Character::check_mount_will_move(), check_water_affect_items(), Character::clear_destination(), creature_tracker::creature_at(), Character::current_movement_mode(), D_PEDANTIC_INFO, dbg, Character::defer_move(), monster::die(), effect_amigara, effect_harnessed, effect_incorporeal, effect_pet, effect_psi_stunned, effect_ridden, effect_stunned, Character::enchantment_cache, Character::enough_working_legs(), move_mode::exertion_level(), Creature::facing, flag_CRUTCHES, flag_DIG_TOOL, monster::friendly, map::furn(), furn_f_safe_c, g, get_avatar(), get_creature_tracker(), get_map(), Character::get_size(), Character::get_speed(), Character::get_wielded_item(), vehicle::handle_potential_theft(), Character::has_active_mutation(), Creature::has_effect(), item::has_flag(), monster::has_flag(), map::has_flag(), map::has_flag_furn(), int_id< T >::id(), avatar::invoke_item(), Character::is_auto_moving(), Character::is_blind(), monster::is_dead(), npc::is_enemy(), monster::is_hallucination(), Character::is_mounted(), map::is_outside(), Character::is_prone(), Creature::is_underwater(), Character::is_walking(), LEFT, m_bad, m_info, m_warning, npc::make_angry(), MAPSIZE_X, MAPSIZE_Y, Character::melee_attack(), Creature::mod_moves(), mon_flag_IMMOBILE, Character::mounted_creature, Character::move_effects(), move_mode_prone, enchant_vals::MOVEMENT_EXERTION_MODIFIER, vehicle_part::name(), monster::name(), vehicle::name, Creature::NEUTRAL, vehicle::next_part_to_open(), map::obstacle_name(), vehicle_part::open, vehicle::open(), vehicle::open_all_at(), map::open_door(), vehicle::part(), optional_vpart_position::part_with_feature(), map::passable_ter_furn(), map::points_in_rectangle(), Creature::pos(), Creature::posx(), Creature::posy(), Creature::posz(), press_x(), query_yn(), RIGHT, rl_dist(), rng(), SAFE_MODE_OFF, SAFE_MODE_ON, Character::set_activity_level(), avatar::set_movement_mode(), Creature::set_moves(), swim(), Character::swim_speed(), map::ter(), ter_t_door_bar_locked, ter_t_door_locked, ter_t_door_locked_alarm, ter_t_door_locked_interior, ter_t_door_locked_peep, ter_t_fault, TFLAG_DEEP_WATER, TFLAG_MINEABLE, TFLAG_RAMP_DOWN, TFLAG_RAMP_UP, TFLAG_SWIMMABLE, trait_SHELL2, trait_SHELL3, avatar::try_break_relax_gas(), item::type, map::veh_at(), veh_pointer_or_null(), vehicle::velocity, point::x, tripoint::x, tripoint::xy(), point::y, tripoint::y, and tripoint::z.
Referenced by game::do_regular_action(), move(), and ramp_move().
plthrow()
void avatar_action::plthrow (avatar & you, item_location loc, const std::optional< tripoint > & blind_throw_from_pos = std::nullopt)
Definition at line 982 of file avatar_action.cpp.
 {
     bool in_shell = you.has_active_mutation( trait_SHELL2 ) ||
                     you.has_active_mutation( trait_SHELL3 );
     if( in_shell ) {
         add_msg( m_info, _( "You can't effectively throw while you're in your shell." ) );
         return;
     } else if( you.has_effect( effect_incorporeal ) ) {
         add_msg( m_info, _( "You lack the substance to affect anything." ) );
         return;
     }
     if( you.is_mounted() ) {
         monster *mons = get_player_character().mounted_creature.get();
         if( mons->has_flag( mon_flag_RIDEABLE_MECH ) ) {
             if( !mons->check_mech_powered() ) {
                 add_msg( m_bad, _( "Your %s refuses to move as its batteries have been drained." ),
                          mons->get_name() );
                 return;
             }
         }
     }
     if( !loc ) {
         loc = game_menus::inv::titled_menu( you,  _( "Throw item" ),
                                             _( "You don't have any items to throw." ) );
     }
     if( !loc ) {
         add_msg( _( "Never mind." ) );
         return;
     }
     const ret_val<void> ret = you.can_wield( *loc );
     if( !ret.success() ) {
         add_msg( m_info, "%s", ret.c_str() );
         return;
     }
     // make a copy and get the original.
     // the copy is thrown and has its and the originals charges set appropriately
     // or deleted from inventory if its charges(1) or not stackable.
     item *orig = loc.get_item();
     item thrown = *orig;
     int range = you.throw_range( thrown );
     if( range < 0 ) {
         add_msg( m_info, _( "You don't have that item." ) );
         return;
     } else if( range == 0 ) {
         add_msg( m_info, _( "That is too heavy to throw." ) );
         return;
     }
     if( you.is_wielding( *orig ) && orig->has_flag( flag_NO_UNWIELD ) ) {
         // pos == -1 is the weapon, NO_UNWIELD is used for bio_claws_weapon
         add_msg( m_info, _( "That's part of your body, you can't throw that!" ) );
         return;
     }
     if( !you.try_break_relax_gas( _( "You concentrate mightily, and your body obeys!" ),
                                   _( "You can't muster up the effort to throw anything…" ) ) ) {
         return;
     }
     // if you're wearing the item you need to be able to take it off
     if( you.is_worn( *orig ) ) {
         ret_val<void> ret = you.can_takeoff( *orig );
         if( !ret.success() ) {
             add_msg( m_info, "%s", ret.c_str() );
             return;
         }
     }
     // you must wield the item to throw it
     if( !you.is_wielding( *orig ) ) {
         if( !you.wield( *orig ) ) {
             return;
         }
     }
     // Shift our position to our "peeking" position, so that the UI
     // for picking a throw point lets us target the location we couldn't
     // otherwise see.
     const tripoint original_player_position = you.pos();
     if( blind_throw_from_pos ) {
         you.setpos( *blind_throw_from_pos );
     }
     g->temp_exit_fullscreen();
     item_location weapon = you.get_wielded_item();
     target_handler::trajectory trajectory = target_handler::mode_throw( you, *weapon,
                                             blind_throw_from_pos.has_value() );
     // If we previously shifted our position, put ourselves back now that we've picked our target.
     if( blind_throw_from_pos ) {
         you.setpos( original_player_position );
     }
     if( trajectory.empty() ) {
         return;
     }
     if( weapon->count_by_charges() && weapon->charges > 1 ) {
         weapon->mod_charges( -1 );
         thrown.charges = 1;
     } else {
         you.remove_weapon();
     }
     you.throw_item( trajectory.back(), thrown, blind_throw_from_pos );
     g->reenter_fullscreen();
 }
References _, add_msg(), Character::can_takeoff(), Character::can_wield(), item::charges, monster::check_mech_powered(), item::count_by_charges(), effect_incorporeal, flag_NO_UNWIELD, g, item_location::get_item(), monster::get_name(), get_player_character(), Character::get_wielded_item(), Character::has_active_mutation(), Creature::has_effect(), item::has_flag(), monster::has_flag(), Character::is_mounted(), Character::is_wielding(), Character::is_worn(), m_bad, m_info, item::mod_charges(), target_handler::mode_throw(), mon_flag_RIDEABLE_MECH, Character::mounted_creature, Creature::pos(), Character::remove_weapon(), cata::hash64_detail::ret, Creature::setpos(), Character::throw_item(), Character::throw_range(), game_menus::inv::titled_menu(), trait_SHELL2, trait_SHELL3, avatar::try_break_relax_gas(), and avatar::wield().
Referenced by game::do_regular_action(), game::inventory_item_menu(), and game::peek().
ramp_move()
bool avatar_action::ramp_move (avatar & you, map & m, const tripoint & dest)
Definition at line 563 of file avatar_action.cpp.
 {
     if( dest_loc.z != you.posz() ) {
         // No recursive ramp_moves
         return false;
     }
     // We're moving onto a tile with no support, check if it has a ramp below
     if( !m.has_floor_or_support( dest_loc ) ) {
         tripoint below( dest_loc.xy(), dest_loc.z - 1 );
         if( m.has_flag( ter_furn_flag::TFLAG_RAMP, below ) ) {
             // But we're moving onto one from above
             const tripoint dp = dest_loc - you.pos();
             move( you, m, tripoint( dp.xy(), -1 ) );
             // No penalty for misaligned stairs here
             // Also cheaper than climbing up
             return true;
         }
         return false;
     }
     if( !m.has_flag( ter_furn_flag::TFLAG_RAMP, you.pos() ) ||
         m.passable( dest_loc ) ) {
         return false;
     }
     // Try to find an aligned end of the ramp that will make our climb faster
     // Basically, finish walking on the stairs instead of pulling self up by hand
     bool aligned_ramps = false;
     for( const tripoint &pt : m.points_in_radius( you.pos(), 1 ) ) {
         if( rl_dist( pt, dest_loc ) < 2 && m.has_flag( ter_furn_flag::TFLAG_RAMP_END, pt ) ) {
             aligned_ramps = true;
             break;
         }
     }
     const tripoint above_u( you.posx(), you.posy(), you.posz() + 1 );
     if( m.has_floor_or_support( above_u ) ) {
         add_msg( m_warning, _( "You can't climb here - there's a ceiling above." ) );
         return false;
     }
     const tripoint dp = dest_loc - you.pos();
     const tripoint old_pos = you.pos();
     move( you, m, tripoint( dp.xy(), 1 ) );
     // We can't just take the result of the above function here
     if( you.pos() != old_pos ) {
         const double total_move_cost = aligned_ramps ? 0.5 : 1.0;
         you.mod_moves( -you.get_speed() * total_move_cost );
     }
     return true;
 }
References _, add_msg(), below, Character::get_speed(), map::has_flag(), map::has_floor_or_support(), m_warning, Creature::mod_moves(), move(), map::passable(), map::points_in_radius(), Creature::pos(), Creature::posx(), Creature::posy(), Creature::posz(), rl_dist(), TFLAG_RAMP, TFLAG_RAMP_END, tripoint::xy(), and tripoint::z.
swim()
void avatar_action::swim (map & m, avatar & you, const tripoint & p)
Handles swimming by the player.
Called by avatar_action::move().
Definition at line 618 of file avatar_action.cpp.
 {
     if( !m.has_flag( ter_furn_flag::TFLAG_SWIMMABLE, p ) ) {
         dbg( D_ERROR ) << "game:plswim: Tried to swim in "
                        << m.tername( p ) << "!";
         debugmsg( "Tried to swim in %s!", m.tername( p ) );
         return;
     }
     if( you.has_effect( effect_onfire ) ) {
         add_msg( _( "The water puts out the flames!" ) );
         you.remove_effect( effect_onfire );
         if( you.is_mounted() ) {
             monster *mon = you.mounted_creature.get();
             if( mon->has_effect( effect_onfire ) ) {
                 mon->remove_effect( effect_onfire );
             }
         }
     }
     if( you.has_effect( effect_glowing ) ) {
         add_msg( _( "The water washes off the glowing goo!" ) );
         you.remove_effect( effect_glowing );
     }
     g->water_affect_items( you );
     int movecost = you.swim_speed();
     you.practice( skill_swimming, you.is_underwater() ? 2 : 1 );
     if( movecost >= 500 || you.has_effect( effect_winded ) ) {
         if( !you.is_underwater() &&
             !( you.shoe_type_count( itype_swim_fins ) == 2 ||
                ( you.shoe_type_count( itype_swim_fins ) == 1 && one_in( 2 ) ) ) ) {
             add_msg( m_bad, _( "You sink like a rock!" ) );
             you.set_underwater( true );
         }
     }
     if( you.oxygen <= 5 && you.is_underwater() ) {
         if( movecost < 500 ) {
             popup( _( "You need to breathe!  (%s to surface.)" ), press_x( ACTION_MOVE_UP ) );
         } else {
             popup( _( "You need to breathe but you can't swim!  Get to dry land, quick!" ) );
         }
     }
     bool diagonal = p.x != you.posx() && p.y != you.posy();
     if( you.in_vehicle ) {
         m.unboard_vehicle( you.pos() );
     }
     if( you.is_mounted() && m.veh_at( you.pos() ).part_with_feature( VPFLAG_BOARDABLE, true ) ) {
         add_msg( m_warning, _( "You cannot board a vehicle while mounted." ) );
         return;
     }
     if( const auto vp = m.veh_at( p ).part_with_feature( VPFLAG_BOARDABLE, true ) ) {
         if( !vp->vehicle().handle_potential_theft( you ) ) {
             return;
         }
     }
     tripoint old_abs_pos = m.getabs( you.pos() );
     you.setpos( p );
     g->update_map( you );
     cata_event_dispatch::avatar_moves( old_abs_pos, you, m );
     if( m.veh_at( you.pos() ).part_with_feature( VPFLAG_BOARDABLE, true ) ) {
         m.board_vehicle( you.pos(), &you );
     }
     you.mod_moves( -( ( movecost > 200 ? 200 : movecost ) * ( trigdist && diagonal ? M_SQRT2 : 1 ) ) );
     you.inv->rust_iron_items();
     if( !you.is_mounted() ) {
         you.burn_move_stamina( movecost );
     }
     body_part_set flags;
     if( !you.is_underwater() ) {
         flags = you.get_drenching_body_parts( false, true, true );
     } else {
         flags = you.get_drenching_body_parts();
     }
     you.drench( 100, flags, false );
 }
References _, ACTION_MOVE_UP, add_msg(), cata_event_dispatch::avatar_moves(), map::board_vehicle(), Character::burn_move_stamina(), D_ERROR, dbg, debugmsg, Character::drench(), effect_glowing, effect_onfire, effect_winded, g, Creature::get_drenching_body_parts(), map::getabs(), Creature::has_effect(), map::has_flag(), Character::in_vehicle, Character::inv, Character::is_mounted(), Creature::is_underwater(), itype_swim_fins, m_bad, M_SQRT2, m_warning, Creature::mod_moves(), Character::mounted_creature, one_in(), Character::oxygen, optional_vpart_position::part_with_feature(), popup(), Creature::pos(), Creature::posx(), Creature::posy(), Character::practice(), press_x(), Creature::remove_effect(), Character::set_underwater(), Creature::setpos(), Character::shoe_type_count(), skill_swimming, Character::swim_speed(), map::tername(), TFLAG_SWIMMABLE, trigdist, map::unboard_vehicle(), map::veh_at(), VPFLAG_BOARDABLE, tripoint::x, and tripoint::y.
Referenced by timed_event::actualize(), basecamp::combat_mission_return(), Character::knock_back_to(), game::knockback(), and move().
unload()
void avatar_action::unload (avatar & you)
Definition at line 1214 of file avatar_action.cpp.
 {
     std::pair<item_location, bool> ret = game_menus::inv::unload( you );
     if( !ret.first ) {
         add_msg( _( "Never mind." ) );
         return;
     }
     if( ret.second || !ret.first->is_container() ) {
         // Auto contain
         you.unload( ret.first );
     } else {
         // Manual contain
         item_location new_container = g->inv_map_splice( [&you]( const item_location & it ) {
             return it->is_container() && !it->is_corpse() && you.rate_action_insert( it ) == hint_rating::good;
         }, _( "Insert item" ), 1, _( "You have no container to insert items." ) );
         if( !new_container ) {
             add_msg( _( "Never mind." ) );
             return;
         }
         you.unload( ret.first, false, new_container );
     }
 }
References _, add_msg(), g, good, item::is_container(), item::is_corpse(), Character::rate_action_insert(), cata::hash64_detail::ret, game_menus::inv::unload(), and Character::unload().
Referenced by item_pocket::favorite_settings::deserialize(), game::do_regular_action(), item_pocket::favorite_settings::info(), item_pocket::favorite_settings::is_null(), item_pocket::favorite_settings::is_unloadable(), and item_pocket::favorite_settings::set_unloadable().
use_item() [1/2]
void avatar_action::use_item (avatar & you)
Definition at line 1104 of file avatar_action.cpp.
 {
     item_location loc;
     avatar_action::use_item( you, loc );
 }
References use_item().
use_item() [2/2]
void avatar_action::use_item (avatar & you, item_location & loc, std::string const & method = {})
Definition at line 1110 of file avatar_action.cpp.
 {
     if( you.has_effect( effect_incorporeal ) ) {
         you.add_msg_if_player( m_bad, _( "You can't use anything while incorporeal." ) );
         return;
     }
     // Some items may be used without being picked up first
     bool use_in_place = false;
     if( !loc ) {
         loc = game_menus::inv::use( you );
         if( !loc ) {
             add_msg( _( "Never mind." ) );
             return;
         }
     }
     loc.overflow();
     if( loc->is_comestible() && loc->is_frozen_liquid() ) {
         add_msg( _( "Try as you might, you can't consume frozen liquids." ) );
         return;
     }
     if( loc->wetness && loc->has_flag( flag_WATER_BREAK_ACTIVE ) ) {
         if( query_yn( _( "This item is still wet and it will break if you turn it on. Proceed?" ) ) ) {
             loc->deactivate();
             loc.get_item()->set_fault( random_entry( fault::get_by_type( std::string( "wet" ) ) ) );
             // An electronic item in water is also shorted.
             if( loc->has_flag( flag_ELECTRONIC ) ) {
                 loc.get_item()->set_fault( random_entry( fault::get_by_type( std::string( "shorted" ) ) ) );
             }
         } else {
             return;
         }
     }
     item_pocket *parent_pocket = nullptr;
     bool on_person = true;
     int pre_obtain_moves = you.get_moves();
     if( loc->has_flag( flag_ALLOWS_REMOTE_USE ) || you.is_worn( *loc ) ) {
         use_in_place = true;
         // Activate holster on map only if hands are free.
     } else if( you.can_wield( *loc ).success() && loc->is_holster() && !loc.held_by( you ) ) {
         use_in_place = true;
         // Adjustment because in player::wield_contents this amount is refunded.
         you.mod_moves( -loc.obtain_cost( you ) );
     } else {
         item_location::type loc_where = loc.where_recursive();
         std::string const name = loc->display_name();
         if( loc_where != item_location::type::character ) {
             pre_obtain_moves = -1;
             on_person = false;
         }
         // Get the parent pocket before the item is obtained.
         if( loc.has_parent() ) {
             parent_pocket = loc.parent_pocket();
         }
         loc = loc.obtain( you, 1 );
         if( parent_pocket ) {
             parent_pocket->on_contents_changed();
         }
         if( pre_obtain_moves == -1 ) {
             pre_obtain_moves = you.get_moves();
         }
         if( !loc ) {
             you.add_msg_if_player( _( "Couldn't pick up the %s." ), name );
             return;
         }
         if( loc_where != item_location::type::character ) {
             you.add_msg_if_player( _( "You pick up the %s." ), name );
         }
     }
     if( use_in_place ) {
         update_lum( loc, false );
         you.use( loc, pre_obtain_moves, method );
         if( loc ) {
             update_lum( loc, true );
             loc.make_active();
         }
     } else {
         you.use( loc, pre_obtain_moves, method );
         if( parent_pocket && on_person && parent_pocket->will_spill() ) {
             parent_pocket->handle_liquid_or_spill( you, loc.parent_item().get_item() );
         }
     }
     if( loc ) {
         loc.on_contents_changed();
     }
     you.recoil = MAX_RECOIL;
     you.invalidate_crafting_inventory();
 }
References _, add_msg(), Character::add_msg_if_player(), Character::can_wield(), item_location::character, item::deactivate(), item::display_name(), effect_incorporeal, flag_ALLOWS_REMOTE_USE, flag_ELECTRONIC, flag_WATER_BREAK_ACTIVE, fault::get_by_type(), item_location::get_item(), Creature::get_moves(), item_pocket::handle_liquid_or_spill(), Creature::has_effect(), item::has_flag(), item_location::has_parent(), item_location::held_by(), Character::invalidate_crafting_inventory(), item::is_comestible(), item::is_frozen_liquid(), item::is_holster(), Character::is_worn(), m_bad, item_location::make_active(), MAX_RECOIL, Creature::mod_moves(), om_direction::name(), item_location::obtain(), item_location::obtain_cost(), item_location::on_contents_changed(), item_pocket::on_contents_changed(), item_location::overflow(), item_location::parent_item(), item_location::parent_pocket(), query_yn(), random_entry(), Character::recoil, item::set_fault(), ret_val_common::success(), update_lum(), game_menus::inv::use(), Character::use(), item::wetness, item_location::where_recursive(), and item_pocket::will_spill().
Referenced by avatar::disp_medical(), game::do_regular_action(), eat_or_use(), exosuit_interact::insert_replace_activate_mod(), game::inventory_item_menu(), game::npc_menu(), and use_item().