Cataclysm DDA: cata Namespace Reference
cata Namespace Reference
Namespaces
event_detail
hash64_detail
options
tuple_hash_detail
views
Classes
class clone_ptr
class colony
class event
struct transparent_less_than
class flat_set
A SimpleAssociativeContainer implemented as a sorted vector.
struct tuple_hash
struct auto_hash
struct auto_hash< std::pair< T, U > >
struct auto_hash< std::tuple< T... > >
struct range_hash
class value_ptr
This class is essentially a copyable unique pointer.
class list
struct mdarray_default_size_impl
struct mdarray_default_size_impl< coords::coord_point< Point, coords::origin::reality_bubble, Scale, InBounds > >
struct mdarray_default_size_impl< coords::coord_point< Point, Origin, Scale, InBounds > >
class mdarray_impl_2d
class mdarray
class string_formatter
Type-safe and undefined-behavior free wrapper over sprintf.
struct heap
This class is essentially a copyable unique pointer, like value_ptr, except it hides the fact it is a unique_ptr.
Typedefs
template<typename CopyFrom , typename CopyTo >
using copy_const = std::conditional_t< std::is_const_v< CopyFrom >, const CopyTo, CopyTo >
Functions
template<typename RangeOfRanges >
auto cartesian_product (const RangeOfRanges &input) -> std::vector< std::vector< typename RangeOfRanges::value_type::value_type >>
template<typename Iterator , typename RatingFunction >
void sort_by_rating (Iterator begin, Iterator end, RatingFunction rating_func)
Sort elements of a sequence by their rating (the smaller the better).
template<typename T >
void find_cycles_impl (const std::unordered_map< T, std::vector< T >> &edges, const T &v, std::unordered_set< T > &visited, std::unordered_map< T, T > &on_current_branch, std::vector< std::vector< T >> &result)
template<typename T >
std::vector< std::vector< T > > find_cycles (const std::unordered_map< T, std::vector< T >> &edges)
template<class element_type , class element_allocator_type , typename element_skipfield_type >
void swap (colony< element_type, element_allocator_type, element_skipfield_type > &a, colony< element_type, element_allocator_type, element_skipfield_type > &b) COLONY_NOEXCEPT_SWAP(element_allocator_type)
Swaps colony A's contents with that of colony B.
template<event_type Type>
static void get_fields_if_match (event_type type, event::fields_type &out)
template<int... I>
static event::fields_type get_fields_helper (event_type type, std::integer_sequence< int, I... >)
template<class T , typename Hash = std::hash<T>>
void hash_combine (std::size_t &seed, const T &v, const Hash &hash=std::hash< T >())
std::size_t hash64 (std::uint64_t val)
template<class swap_element_type , class swap_element_allocator_type >
void swap (list< swap_element_type, swap_element_allocator_type > &a, list< swap_element_type, swap_element_allocator_type > &b) LIST_NOEXCEPT_SWAP(swap_element_allocator_type)
template<typename SetL , typename SetR >
bool sets_intersect (const SetL &l, const SetR &r)
void throw_error (const string_formatter &, std::string_view)
const char * string_formatter_set_temp_buffer (const string_formatter &, std::string &&)
std::string handle_string_format_error ()
template<typename RT , typename T >
std::enable_if_t< is_integer< RT > &&is_integer< T >, RT > convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< is_integer< RT > &&std::is_enum_v< std::decay_t< T > >, RT > convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< std::is_floating_point_v< RT > &&is_numeric< T > &&!is_integer< T >, RT > convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< std::is_same_v< RT, void * > &&std::is_pointer_v< std::decay_t< T > >, void * > convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< std::is_same_v< RT, const char * > &&is_string< T >, const char * > convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< std::is_same_v< RT, const char * > &&is_string_view< T >, const char * > convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< std::is_same_v< RT, const char * > &&is_cstring< T >, const char * > convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< std::is_same_v< RT, const char * > &&is_translation< T >, const char * > convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< std::is_same_v< RT, const char * > &&is_numeric< T > &&!is_char< T >, const char * > convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< std::is_same_v< RT, const char * > &&is_char< T >, const char * > convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
RT convert (RT *, const string_formatter &sf, T &&,...)
template<class T , class... Args>
value_ptr< T > make_value (Args &&...args)
template<class T >
bool value_ptr_equals (const value_ptr< T > &lhs, const value_ptr< T > &rhs)
Variables
template<typename Point >
constexpr size_t mdarray_default_size = mdarray_default_size_impl<Point>::value
template<typename T >
constexpr bool is_numeric
template<typename T >
constexpr bool is_integer
template<typename T >
constexpr bool is_char = std::is_same_v<std::decay_t<T>, char>
template<typename T >
constexpr bool is_string = std::is_same_v<std::decay_t<T>, std::string>
template<typename T >
constexpr bool is_string_view = std::is_same_v<std::decay_t<T>, std::string_view>
template<typename T >
constexpr bool is_cstring
template<typename T >
constexpr bool is_translation = std::is_same_v<std::decay_t<T>, translation>
Typedef Documentation
copy_const
template<typename CopyFrom , typename CopyTo > using cata::copy_const = typedef std::conditional_t<std::is_const_v<CopyFrom>, const CopyTo, CopyTo>
Definition at line 12 of file cata_type_traits.h.
Function Documentation
cartesian_product()
template<typename RangeOfRanges > auto cata::cartesian_product (const RangeOfRanges & input) -> std::vector<std::vector<typename RangeOfRanges::value_type::value_type>>
Definition at line 9 of file cartesian_product.h.
 {
     std::vector<std::vector<typename RangeOfRanges::value_type::value_type>> result;
     using Iterators = std::vector<typename RangeOfRanges::value_type::const_iterator>;
     Iterators iterators;
     iterators.reserve( input.size() );
     for( const auto &range : input ) {
         if( range.empty() ) {
             return result;
         }
         iterators.push_back( range.begin() );
     }
     while( true ) {
         // Append the new result
         result.emplace_back();
         auto &new_list = result.back();
         new_list.reserve( input.size() );
         for( typename Iterators::value_type it : iterators ) {
             new_list.push_back( *it );
         }
         // Increment the iterators
         size_t i = 0;
         for( ; i != input.size(); ++i ) {
             auto &which_it = iterators[i];
             const auto &range = input[i];
             ++which_it;
             if( which_it == range.end() ) {
                 which_it = range.begin();
             } else {
                 break;
             }
         }
         if( i == input.size() ) {
             return result;
         }
     }
 }
Referenced by calculate_all_blueprint_reqs().
convert() [1/9]
template<typename RT , typename T > std::enable_if_t< is_integer<RT> &&std::is_enum_v<std::decay_t<T> >, RT > cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 87 of file string_formatter.h.
 {
     return static_cast<RT>( value );
 }
convert() [2/9]
template<typename RT , typename T > std::enable_if_t< std::is_floating_point_v<RT> &&is_numeric<T>&& !is_integer<T>, RT > cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 94 of file string_formatter.h.
 {
     return value;
 }
convert() [3/9]
template<typename RT , typename T > std::enable_if_t< std::is_same_v<RT, void *>&&std::is_pointer_v<std::decay_t<T> >, void * > cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 101 of file string_formatter.h.
 {
     return const_cast<std::remove_const_t<std::remove_pointer_t<std::decay_t<T>>> *>( value );
 }
convert() [4/9]
template<typename RT , typename T > std::enable_if_t< std::is_same_v<RT, const char *> &&is_string<T>, const char * > cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 107 of file string_formatter.h.
 {
     return value.c_str();
 }
convert() [5/9]
template<typename RT , typename T > std::enable_if_t< std::is_same_v<RT, const char *> &&is_cstring<T>, const char * > cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 119 of file string_formatter.h.
 {
     return value;
 }
convert() [6/9]
template<typename RT , typename T > std::enable_if_t< std::is_same_v<RT, const char *> &&is_string_view<T>, const char * > cata::convert (RT * , const string_formatter & sf, T && value, int) inline
Definition at line 113 of file string_formatter.h.
 {
     return string_formatter_set_temp_buffer( sf, std::string( value ) );
 }
References string_formatter_set_temp_buffer().
convert() [7/9]
template<typename RT , typename T > std::enable_if_t< std::is_same_v<RT, const char *> &&is_translation<T>, const char * > cata::convert (RT * , const string_formatter & sf, T && value, int) inline
Definition at line 125 of file string_formatter.h.
 {
     return string_formatter_set_temp_buffer( sf, value.translated() );
 }
References string_formatter_set_temp_buffer().
convert() [8/9]
template<typename RT , typename T > std::enable_if_t<std::is_same_v<RT, const char *> &&is_numeric<T> &&!is_char<T>, const char * > cata::convert (RT * , const string_formatter & sf, T && value, int) inline
Definition at line 133 of file string_formatter.h.
 {
     return string_formatter_set_temp_buffer( sf, std::to_string( value ) );
 }
References string_formatter_set_temp_buffer(), and to_string().
convert() [9/9]
template<typename RT , typename T > std::enable_if_t< std::is_same_v<RT, const char *> &&is_char<T>, const char * > cata::convert (RT * , const string_formatter & sf, T && value, int) inline
Definition at line 139 of file string_formatter.h.
 {
     return string_formatter_set_temp_buffer( sf, std::string( 1, value ) );
 }
References string_formatter_set_temp_buffer().
find_cycles()
template<typename T > std::vector<std::vector<T> > cata::find_cycles (const std::unordered_map< T, std::vector< T >> & edges)
Definition at line 106 of file cata_algo.h.
 {
     std::unordered_set<T> visited;
     std::unordered_map<T, T> on_current_branch;
     std::vector<std::vector<T>> result;
     for( const auto &p : edges ) {
         const T &root = p.first;
         on_current_branch.emplace( root, root );
         find_cycles_impl( edges, root, visited, on_current_branch, result );
         on_current_branch.erase( root );
         cata_assert( on_current_branch.empty() );
     }
     return result;
 }
References cata_assert, and find_cycles_impl().
Referenced by recipe_dictionary::find_items_on_loops().
find_cycles_impl()
template<typename T > void cata::find_cycles_impl (const std::unordered_map< T, std::vector< T >> & edges, const T & v, std::unordered_set< T > & visited, std::unordered_map< T, T > & on_current_branch, std::vector< std::vector< T >> & result)
Definition at line 51 of file cata_algo.h.
 {
     bool new_vertex = visited.insert( v ).second;
     if( !new_vertex ) {
         return;
     }
     auto it = edges.find( v );
     if( it == edges.end() ) {
         return;
     }
     for( const T &next_v : it->second ) {
         if( next_v == v ) {
             // Trivial self-loop
             result.push_back( { v } );
             continue;
         }
         auto previous_match = on_current_branch.find( next_v );
         if( previous_match != on_current_branch.end() ) {
             // We have looped back to somewhere along the branch we took to
             // reach this vertex, so reconstruct the loop and save it.
             std::vector<T> loop;
             T on_path = v;
             while( true ) {
                 loop.push_back( on_path );
                 if( on_path == next_v ) {
                     break;
                 }
                 on_path = on_current_branch[on_path];
             }
             std::reverse( loop.begin(), loop.end() );
             result.push_back( loop );
         } else {
             on_current_branch.emplace( next_v, v );
             find_cycles_impl( edges, next_v, visited, on_current_branch, result );
             on_current_branch.erase( next_v );
         }
     }
 }
Referenced by find_cycles().
get_fields_helper()
template<int... I> static event::fields_type cata::get_fields_helper (event_type type, std::integer_sequence< int, I... >) static
Definition at line 232 of file event.cpp.
 {
     event::fields_type result;
     std::array<bool, sizeof...( I )> discard = {
         ( get_fields_if_match<static_cast<event_type>( I )>( type, result ), true )...
     };
     ( void ) discard;
     return result;
 }
Referenced by cata::event::get_fields().
get_fields_if_match()
template<event_type Type> static void cata::get_fields_if_match (event_type type, event::fields_type & out) static
Definition at line 221 of file event.cpp.
 {
     if( Type == type ) {
         out = { event_detail::event_spec<Type>::fields.begin(),
                 event_detail::event_spec<Type>::fields.end()
               };
     }
 }
handle_string_format_error()
std::string cata::handle_string_format_error ()
Definition at line 112 of file string_formatter.cpp.
 {
     try {
         throw;
     } catch( const std::exception &err ) {
         return err.what();
     }
 }
Referenced by string_format().
hash64()
std::size_t cata::hash64 (std::uint64_t val) inline
Definition at line 112 of file hash_utils.h.
 {
     return hash64_detail::maybe_mix_bits<std::size_t>( val );
 }
hash_combine()
template<class T , typename Hash = std::hash<T>> void cata::hash_combine (std::size_t & seed, const T & v, const Hash & hash = std::hash<T>()) inline
Definition at line 19 of file hash_utils.h.
 {
     seed ^= hash( v ) + 0x9e3779b9 + ( seed << 6 ) + ( seed >> 2 );
 }
References iuse::seed().
Referenced by cata::tuple_hash_detail::Impl< Tuple, Index >::apply(), cata::tuple_hash_detail::Impl< Tuple, 0 >::apply(), mongroup_hash::operator()(), cata::range_hash::operator()(), and cata::tuple_hash::operator()().
make_value()
template<class T , class... Args> value_ptr<T> cata::make_value (Args &&... args)
Definition at line 53 of file value_ptr.h.
 {
     return value_ptr<T>( new T( std::forward<Args>( args )... ) );
 }
sets_intersect()
template<typename SetL , typename SetR > bool cata::sets_intersect (const SetL & l, const SetR & r)
Definition at line 9 of file sets_intersect.h.
 {
     // There ar two reasonable implementation strategies for ordered sets, but
     // only one for unordered sets.  We use the approach that works for both,
     // but if both sets were ordered you can instead step though them in
     // parallel looking for a dupe.
     if( l.size() > r.size() ) {
         return sets_intersect( r, l );
     }
     for( const auto &elem : l ) {
         if( r.count( elem ) ) {
             return true;
         }
     }
     return false;
 }
Referenced by map_extra::is_valid_for(), and overmap::populate().
sort_by_rating()
template<typename Iterator , typename RatingFunction > void cata::sort_by_rating (Iterator begin, Iterator end, RatingFunction rating_func)
Sort elements of a sequence by their rating (the smaller the better).
Parameters
begin An input/output iterator.
end An input/output iterator.
rating_func A functor which calculates ratings (the outcome must be comparable using '<' operator).
The rating is calculated only once per each element.
Definition at line 26 of file cata_algo.h.
 {
     using value_t = typename Iterator::value_type;
     using pair_t = std::pair<value_t, decltype( rating_func( *begin ) )>;
     std::vector<pair_t> rated_entries;
     rated_entries.reserve( std::distance( begin, end ) );
     std::transform( begin, end, std::back_inserter( rated_entries ),
     [ &rating_func ]( const value_t &elem ) {
         return std::make_pair( elem, rating_func( elem ) );
     } );
     std::sort( rated_entries.begin(), rated_entries.end(), []( const pair_t &lhs, const pair_t &rhs ) {
         return lhs.second < rhs.second;
     } );
     std::transform( rated_entries.begin(), rated_entries.end(), begin, []( const pair_t &elem ) {
         return elem.first;
     } );
 }
References keycode::end.
Referenced by npc::move_away_from().
string_formatter_set_temp_buffer()
const char* cata::string_formatter_set_temp_buffer (const string_formatter & , std::string &&)
This is used for printing non-strings through "%s". It only works because this prints each format specifier separately, so the content of temp_buffer is only used once.
Definition at line 232 of file string_formatter.h.
{
             sf.temp_buffer = std::move( text );
             return sf.temp_buffer.c_str();
         }
Referenced by convert().
swap() [1/2]
template<class element_type , class element_allocator_type , typename element_skipfield_type > void cata::swap (colony< element_type, element_allocator_type, element_skipfield_type > & a, colony< element_type, element_allocator_type, element_skipfield_type > & b) inline
Swaps colony A's contents with that of colony B.
Assumes both colonies have same element type, allocator type, etc.
Definition at line 3505 of file colony.h.
 {
     a.swap( b );
 }
Referenced by approx_orientation(), assign(), closest_points_first(), consolidate(), avatar::control_npc(), vehicle::damage_all(), stats_tracker::deserialize(), draw_square(), creature_tracker::find_reachable(), CellularAutomata::generate_cellular_automaton(), JsonObject::init(), JsonArray::init(), item::io(), activity_byproduct::load(), shearing_entry::load(), overmap_special::load(), editmap::mapgen_preview(), map::mirror(), avatar::power_bionics(), avatar::power_mutations(), rng(), rng_float(), rng_normal(), rng_sequence(), map::rotate(), recipe_subset::search(), auto_pickup::user_interface::show(), Messages::dialog::show(), safemode::show(), panel_manager::show_adm(), cata::list< element_type, element_allocator_type >::splice(), zone_manager::swap(), advanced_inventory::swap_panes(), and maptile_soa::swap_soa_tile().
swap() [2/2]
template<class swap_element_type , class swap_element_allocator_type > void cata::swap (list< swap_element_type, swap_element_allocator_type > & a, list< swap_element_type, swap_element_allocator_type > & b) inline
Definition at line 2455 of file list.h.
 {
     a.swap( b );
 }
throw_error()
void cata::throw_error (const string_formatter & , std::string_view)
Definition at line 225 of file string_formatter.h.
{
             sf.throw_error( msg );
         }
Referenced by convert(), JsonValue::operator bool(), JsonValue::operator double(), JsonValue::operator int(), JsonValue::operator int64_t(), JsonValue::operator JsonArray(), JsonValue::operator JsonObject(), JsonValue::operator std::string(), JsonValue::operator uint64_t(), JsonValue::operator unsigned(), and cata::string_formatter::read_number_or_argument_index().
value_ptr_equals()
template<class T > bool cata::value_ptr_equals (const value_ptr< T > & lhs, const value_ptr< T > & rhs)
Definition at line 59 of file value_ptr.h.
 {
     return ( !lhs && !rhs ) || ( lhs && rhs && *lhs == *rhs );
 }
Referenced by translation::operator==().
Variable Documentation
mdarray_default_size
template<typename Point > constexpr size_t cata::mdarray_default_size = mdarray_default_size_impl<Point>::value constexpr
Definition at line 33 of file mdarray.h.