Cataclysm DDA: catacurses Namespace Reference
catacurses Namespace Reference
Contains the curses interface used by the whole game.
Classes
class window
A wrapper over a pointer to a curses window.
Typedefs
using chtype = int
using attr_t = unsigned short
Enumerations
enum base_color : short {
black = 0x00 , red = 0x01 , green = 0x02 , yellow = 0x03 ,
blue = 0x04 , magenta = 0x05 , cyan = 0x06 , white = 0x07 ,
dark_gray = 237
}
Functions
void init_interface ()
window newwin (int nlines, int ncols, const point &begin)
void wborder (const window &win, chtype ls, chtype rs, chtype ts, chtype bs, chtype tl, chtype tr, chtype bl, chtype br)
void mvwhline (const window &win, const point &p, chtype ch, int n)
void mvwvline (const window &win, const point &p, chtype ch, int n)
void wnoutrefresh (const window &win)
void wrefresh (const window &win)
void refresh ()
void doupdate ()
void wredrawln (const window &win, int beg_line, int num_lines)
void mvwprintw (const window &win, const point &p, const std::string &text)
template<typename ... Args>
void mvwprintw (const window &win, const point &p, const char *const fmt, Args &&... args)
void wprintw (const window &win, const std::string &text)
template<typename ... Args>
void wprintw (const window &win, const char *const fmt, Args &&... args)
void resizeterm ()
void werase (const window &win)
void init_pair (short pair, base_color f, base_color b)
void wmove (const window &win, const point &p)
void clear ()
void erase ()
void endwin ()
void mvwaddch (const window &win, const point &p, chtype ch)
void wclear (const window &win)
void curs_set (int visibility)
void wattron (const window &win, const nc_color &attrs)
void wattroff (const window &win, nc_color attrs)
void waddch (const window &win, chtype ch)
int getmaxy (const window &win)
int getmaxx (const window &win)
int getbegx (const window &win)
int getbegy (const window &win)
int getcurx (const window &win)
int getcury (const window &win)
bool supports_256_colors ()
Variables
window newscr
window stdscr
Detailed Description
Contains the curses interface used by the whole game.
All code (except platform/OS/build type specific code) should use functions/ types from this namespace only. The input_manager and input_context should be used for user input.
There are currently (Nov 2017) two implementations for most of this interface:
ncurses (mostly in ncurses_def.cpp). The interface originates from there, so it's mostly just forwarding to ncurses functions of the same name.
our own curses library cata_cursesport (mostly in cursesport.cpp), cursesport.h contains the structures and some functions specific to that.
A few (system specific) functions are implemented in three versions:
ncurses (ncurses_def.cpp),
Windows curses (no SDL, using cata_cursesport, see wincurses.cpp), and
SDL curses (using cata_cursesport, see sdltiles.cpp).
As this interface is derived from ncurses, refer to documentation of that.
The interface is in a separate namespace we can link with the ncurses library, which exports its functions globally.
Typedef Documentation
attr_t
using catacurses::attr_t = typedef unsigned short
Definition at line 93 of file cursesdef.h.
chtype
typedef int catacurses::chtype
Definition at line 92 of file cursesdef.h.
Enumeration Type Documentation
base_color
enum catacurses::base_color : short
Enumerator
black
red
green
yellow
blue
magenta
cyan
white
dark_gray
Definition at line 78 of file cursesdef.h.
                 : short {
     black = 0x00,    // RGB{0, 0, 0}
     red = 0x01,      // RGB{196, 0, 0}
     green = 0x02,    // RGB{0, 196, 0}
     yellow = 0x03,   // RGB{196, 180, 30}
     blue = 0x04,     // RGB{0, 0, 196}
     magenta = 0x05,  // RGB{196, 0, 180}
     cyan = 0x06,     // RGB{0, 170, 200}
     white = 0x07,    // RGB{196, 196, 196}
     // 256 Color Support
     dark_gray = 237,
 };
Function Documentation
clear()
void catacurses::clear ()
Definition at line 196 of file ncurses_def.cpp.
 {
     return curses_check_result( ::clear(), OK, "clear" );
 }
References clear, and curses_check_result().
curs_set()
void catacurses::curs_set (int visibility)
Definition at line 272 of file ncurses_def.cpp.
 {
     return curses_check_result( ::curs_set( visibility ), OK, "curs_set" );
 }
References curses_check_result().
Referenced by main().
doupdate()
void catacurses::doupdate ()
Definition at line 191 of file ncurses_def.cpp.
 {
     return curses_check_result( ::doupdate(), OK, "doupdate" );
 }
References curses_check_result().
Referenced by anonymous_namespace{main.cpp}::exit_handler(), input_manager::get_input_event(), refresh_display(), and resizeterm().
endwin()
void catacurses::endwin ()
Definition at line 206 of file ncurses_def.cpp.
 {
     return curses_check_result( ::endwin(), OK, "endwin" );
 }
References curses_check_result().
Referenced by anonymous_namespace{main.cpp}::exit_handler().
erase()
void catacurses::erase ()
Definition at line 201 of file ncurses_def.cpp.
 {
     return curses_check_result( ::erase(), OK, "erase" );
 }
References curses_check_result().
Referenced by background_pane::background_pane(), check_encoding(), debug_error_prompt(), ensure_term_size(), cata::list< element_type, element_allocator_type >::erase(), avatar::grab(), cata::list< element_type, element_allocator_type >::pop_back(), cata::list< element_type, element_allocator_type >::pop_front(), prepare_sorted_lists(), cata::list< element_type, element_allocator_type >::remove_if(), cata::list< element_type, element_allocator_type >::resize(), auto_notes::auto_note_manager_gui::show(), cata::flat_set< T, Compare, Data >::sort_data(), and cata::list< element_type, element_allocator_type >::unique().
getbegx()
int catacurses::getbegx (const window & win)
Definition at line 107 of file ncurses_def.cpp.
 {
     if( !win ) {
         return 0;
     }
     return ::getbegx( win.get<::WINDOW>() );
 }
References catacurses::window::get().
Referenced by scrollbar::apply(), tab_manager::draw(), border_helper::draw_border(), input_context::get_coordinates(), scrolling_text_view::handle_navigation(), multiline_list::handle_navigation(), mouse_in_window(), worldfactory::pick_world(), ui_adaptor::position_from_window(), main_menu::print_menu(), main_menu::print_menu_items(), ui_adaptor::record_cursor(), select_crafter_and_crafting_recipe(), ui_adaptor::set_cursor(), string_input_popup::show_history(), and show_scores_ui().
getbegy()
int catacurses::getbegy (const window & win)
Definition at line 115 of file ncurses_def.cpp.
 {
     if( !win ) {
         return 0;
     }
     return ::getbegy( win.get<::WINDOW>() );
 }
References catacurses::window::get().
Referenced by scrollbar::apply(), veh_interact::display_grid(), main_menu::display_text(), tab_manager::draw(), border_helper::draw_border(), input_context::get_coordinates(), scrolling_text_view::handle_navigation(), multiline_list::handle_navigation(), mouse_in_window(), worldfactory::pick_world(), ui_adaptor::position_from_window(), main_menu::print_menu(), main_menu::print_menu_items(), ui_adaptor::record_cursor(), ui_adaptor::set_cursor(), string_input_popup::show_history(), and show_scores_ui().
getcurx()
int catacurses::getcurx (const window & win)
Definition at line 123 of file ncurses_def.cpp.
 {
     if( !win ) {
         return 0;
     }
     return ::getcurx( win.get<::WINDOW>() );
 }
References catacurses::window::get().
Referenced by ui_adaptor::record_cursor(), and ui_adaptor::record_term_cursor().
getcury()
int catacurses::getcury (const window & win)
Definition at line 131 of file ncurses_def.cpp.
 {
     if( !win ) {
         return 0;
     }
     return ::getcury( win.get<::WINDOW>() );
 }
References catacurses::window::get().
Referenced by ui_adaptor::record_cursor(), and ui_adaptor::record_term_cursor().
getmaxx()
int catacurses::getmaxx (const window & win)
Definition at line 91 of file ncurses_def.cpp.
 {
     if( !win ) {
         return 0;
     }
     return ::getmaxx( win.get<::WINDOW>() );
 }
References catacurses::window::get().
Referenced by game::calc_driving_offset(), veh_interact::calc_lift_requirements(), veh_interact::calc_overview(), veh_interact::can_remove_part(), center_print(), check_encoding(), editmap::create_or_get_ui_adaptor(), veh_interact::create_or_get_ui_adaptor(), create_zone_callback(), custom_draw_func(), debug_error_prompt(), decorate_panel(), avatar::disp_medical(), faction_manager::display(), player_morale::display(), veh_interact::display_details(), veh_interact::display_grid(), veh_interact::display_list(), veh_interact::display_mode(), veh_interact::display_overview(), veh_interact::display_stats(), veh_interact::display_veh(), veh_interact::do_repair(), tab_manager::draw(), map::draw(), Creature::draw(), scent_map::draw(), dialogue_window::draw(), draw_bionics_tab(), draw_bionics_tabs(), draw_bionics_titlebar(), border_helper::draw_border(), draw_border_below_tabs(), prof_window::draw_borders(), draw_borders_external(), draw_borders_internal(), overmap_ui::draw_camp_labels(), talk_function::draw_camp_tabs(), overmap_ui::draw_city_labels(), inventory_selector::draw_columns(), draw_custom_border(), anonymous_namespace{animation.cpp}::draw_custom_explosion_curses(), draw_description(), anonymous_namespace{diary_ui.cpp}::draw_diary_border(), draw_effects_tab(), draw_exam_window(), inventory_selector::draw_footer(), inventory_selector::draw_frame(), draw_grid(), prof_window::draw_header(), draw_header(), inventory_selector::draw_header(), target_ui::draw_help_notice(), draw_hidden_amount(), draw_item_filter_rules(), draw_item_info(), anonymous_namespace{animation.cpp}::draw_line_curses(), draw_medical_titlebar(), help::draw_menu(), draw_messages(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), advanced_inventory::draw_minimap(), worldfactory::draw_mod_list(), worldfactory::draw_modselection_borders(), overmap_ui::draw_om_sidebar(), draw_points(), draw_proficiencies_tab(), draw_recipe_subtabs(), draw_recipe_tabs(), draw_skills_tab(), draw_speed_tab(), draw_tabs(), draw_traits_tab(), target_ui::draw_ui_window(), target_ui::draw_window_title(), map::drawsq(), ensure_term_size(), faction::faction_display(), npc::faction_display(), multiline_list::fold_entries(), veh_interact::format_reqs(), input_context::get_coordinates(), game::get_player_input(), recipe_result_info_cache::get_result_data(), scrolling_text_view::handle_navigation(), multiline_list::handle_navigation(), handle_player_display_action(), game_ui::init_ui(), insert_table(), game::is_in_viewport(), ma_style_callback::key(), mouse_in_window(), target_ui::panel_cursor_info(), target_ui::panel_spell_info(), worldfactory::pick_world(), ui_adaptor::position_from_window(), avatar::power_bionics(), game::print_all_tile_info(), Character::print_encumbrance(), game::print_fields_info(), game::print_furniture_info(), game::print_graffiti_info(), advanced_inventory::print_header(), dialogue_window::print_header(), npc::print_info(), avatar::print_info(), monster::print_info(), advanced_inventory::print_items(), game::print_items_info(), anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), main_menu::print_menu(), main_menu::print_menu_items(), game::print_part_con_info(), vehicle::print_part_list(), print_ranged_chance(), print_scrollable(), print_steadiness(), game::print_terrain_info(), game::print_vehicle_info(), string_editor_window::query_string(), advanced_inventory::redraw_pane(), wish_monster_callback::refresh(), game::reset_item_list_state(), inventory_selector::resize_window(), resizeterm(), right_print(), scrollable_text(), set_description(), set_points(), set_skills(), set_stats(), set_traits(), distraction_manager::distraction_manager_gui::show(), robot_finds_kitten::show(), options_manager::show(), safemode::show(), uilist::show(), diary::show_diary_ui(), color_manager::show_gui(), show_mutations_titlebar(), show_scores_ui(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), outfit::sort_armor(), anonymous_namespace{diary_ui.cpp}::text_to_list_scrollable(), scrolling_text_view::text_width(), editmap::uber_draw_ter(), veh_interact::update_part_requirements(), editmap::update_view_with_help(), computer_session::use(), and window_contains_point_relative().
getmaxy()
int catacurses::getmaxy (const window & win)
Definition at line 99 of file ncurses_def.cpp.
 {
     if( !win ) {
         return 0;
     }
     return ::getmaxy( win.get<::WINDOW>() );
 }
References catacurses::window::get().
Referenced by game::calc_driving_offset(), editmap::create_or_get_ui_adaptor(), veh_interact::create_or_get_ui_adaptor(), create_zone_callback(), avatar::disp_medical(), advanced_inventory::display(), veh_interact::display_grid(), veh_interact::display_overview(), main_menu::display_text(), veh_interact::display_veh(), veh_interact::do_main_loop(), map::draw(), Creature::draw(), scent_map::draw(), scrolling_text_view::draw(), dialogue_window::draw(), draw_bionics_tab(), draw_bionics_tabs(), border_helper::draw_border(), draw_border_below_tabs(), prof_window::draw_borders(), draw_borders_external(), overmap_ui::draw_camp_labels(), overmap_ui::draw_city_labels(), inventory_selector::draw_columns(), target_ui::draw_controls_list(), draw_custom_border(), anonymous_namespace{animation.cpp}::draw_custom_explosion_curses(), draw_description(), anonymous_namespace{diary_ui.cpp}::draw_diary_border(), draw_effects_tab(), draw_filter_and_sorting_indicators(), inventory_selector::draw_footer(), draw_grid(), target_ui::draw_help_notice(), draw_hidden_amount(), draw_item_info(), anonymous_namespace{animation.cpp}::draw_line_curses(), draw_medical_titlebar(), draw_messages(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), advanced_inventory::draw_minimap(), worldfactory::draw_mod_list(), overmap_ui::draw_om_sidebar(), draw_proficiencies_tab(), draw_recipe_subtabs(), draw_recipe_tabs(), draw_skills_tab(), draw_speed_tab(), draw_traits_tab(), target_ui::draw_ui_window(), draw_x_info(), map::drawsq(), ensure_term_size(), fold_and_print_from(), input_context::get_coordinates(), game::get_player_input(), scrolling_text_view::handle_navigation(), multiline_list::handle_navigation(), game_ui::init_ui(), insert_table(), game::is_in_viewport(), ma_style_callback::key(), game::list_items(), game::list_monsters(), game::look_around(), scrolling_text_view::max_offset(), mouse_in_window(), scrolling_text_view::page_down(), scrolling_text_view::page_up(), ui_adaptor::position_from_window(), avatar::power_mutations(), Character::print_encumbrance(), multiline_list::print_entries(), dialogue_window::print_header(), anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), main_menu::print_menu(), print_scrollable(), string_editor_window::query_string(), advanced_inventory::redraw_pane(), wish_monster_callback::refresh(), inventory_selector::resize_window(), resizeterm(), scrollable_text(), select_crafter_and_crafting_recipe(), multiline_list::set_entry_pos(), multiline_list::set_offset_pos(), live_view::show(), show_scores_ui(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), editmap::uber_draw_ter(), editmap::update_view_with_help(), computer_session::use(), and window_contains_point_relative().
init_interface()
void catacurses::init_interface ()
Exceptions
std::exception upon any errors. The caller should display / log it and abort the program. Only continue the program when this returned normally.
Definition at line 320 of file ncurses_def.cpp.
 {
     // ::endwin will free the pointer returned by ::initscr
     stdscr = window( std::shared_ptr<void>( ::initscr(), []( void *const ) { } ) );
     if( !stdscr ) {
         throw std::runtime_error( "initscr failed" );
     }
     newscr = window( std::shared_ptr<void>( ::newscr, []( void *const ) { } ) );
     if( !newscr ) {
         throw std::runtime_error( "null newscr" );
     }
     // our curses wrapper does not support changing this behavior, ncurses must
     // behave exactly like the wrapper, therefore:
     noecho();  // Don't echo keypresses
     cbreak();  // C-style breaks (e.g. ^C to SIGINT)
     keypad( stdscr.get<::WINDOW>(), true ); // Numpad is numbers
     set_escdelay( 10 ); // Make Escape actually responsive
     // TODO: error checking
     start_color();
     imclient = std::make_unique<cataimgui::client>();
     init_colors();
 #if !defined(__CYGWIN__)
     // ncurses mouse registration
     mouseinterval( 0 );
     mousemask( ALL_MOUSE_EVENTS | REPORT_MOUSE_POSITION, nullptr );
     // Sometimes the TERM variable is not set properly and mousemask won't turn on mouse pointer events.
     // The below line tries to force the mouse pointer events to be turned on anyway. ImTui misbehaves without them.
     printf( "\033[?1003h\n" );
 #endif
 }
References catacurses::window::get(), imclient, init_colors(), newscr, and stdscr.
Referenced by main().
init_pair()
void catacurses::init_pair (short pair, base_color f, base_color b)
Definition at line 296 of file ncurses_def.cpp.
 {
     if( imclient ) {
         imclient->upload_color_pair( pair, static_cast<int>( f ), static_cast<int>( b ) );
     }
     return curses_check_result( ::init_pair( pair, static_cast<short>( f ), static_cast<short>( b ) ),
                                 OK, "init_pair" );
 }
References b, curses_check_result(), imclient, and cataimgui::init_pair().
Referenced by init_colors().
mvwaddch()
void catacurses::mvwaddch (const window & win, const point & p, chtype ch)
Definition at line 239 of file ncurses_def.cpp.
 {
     if( !win ) {
         return;
     }
     return curses_check_result( ::mvwaddch( win.get<::WINDOW>(), p.y, p.x, ch ), OK, "mvwaddch" );
 }
References curses_check_result(), catacurses::window::get(), point::x, and point::y.
Referenced by mvwputch(), mvwputch_hi(), mvwputch_inv(), Messages::dialog::show(), and iexamine::vending().
mvwhline()
void catacurses::mvwhline (const window & win, const point & p, chtype ch, int n)
Definition at line 221 of file ncurses_def.cpp.
 {
     if( !win ) {
         return;
     }
     return curses_check_result( ::mvwhline( win.get<::WINDOW>(), p.y, p.x, ch, n ), OK,
                                 "mvwhline" );
 }
References curses_check_result(), catacurses::window::get(), point::x, and point::y.
Referenced by avatar::disp_medical(), player_morale::display(), talk_function::draw_camp_tabs(), draw_connectors(), anonymous_namespace{diary_ui.cpp}::draw_diary_border(), draw_exam_window(), inventory_selector::draw_frame(), draw_grid(), draw_header(), inventory_selector::draw_header(), draw_hidden_amount(), draw_recipe_tabs(), avatar::power_mutations(), dialogue_window::print_header(), smart_controller_ui::refresh(), wish_item_callback::refresh(), and iexamine::vending().
mvwprintw() [1/2]
template<typename ... Args> void catacurses::mvwprintw (const window & win, const point & p, const char *const fmt, Args &&... args) inline
Definition at line 110 of file cursesdef.h.
 {
     return mvwprintw( win, p, string_format( fmt, std::forward<Args>( args )... ) );
 }
References mvwprintw(), and string_format().
mvwprintw() [2/2]
void catacurses::mvwprintw (const window & win, const point & p, const std::string & text)
Definition at line 163 of file ncurses_def.cpp.
 {
     if( !win ) {
         return;
     }
     return curses_check_result( ::mvwprintw( win.get<::WINDOW>(), p.y, p.x, "%s", text.c_str() ),
                                 OK, "mvwprintw" );
 }
References curses_check_result(), catacurses::window::get(), point::x, and point::y.
Referenced by inventory_column::draw(), string_input_popup::draw(), game::list_items(), game::list_monsters(), mvwprintw(), anonymous_namespace{diary_ui.cpp}::mvwprintwa(), mvwprintz(), mvwputch(), mvwputch_hi(), mvwputch_inv(), target_ui::panel_target_info(), target_ui::panel_turret_list(), game::print_all_tile_info(), game::print_items_info(), print_ranged_chance(), print_steadiness(), advanced_inventory::redraw_pane(), wish_mutate_callback::refresh(), wish_monster_callback::refresh(), wish_item_callback::refresh(), and editmap::update_view_with_help().
mvwvline()
void catacurses::mvwvline (const window & win, const point & p, chtype ch, int n)
Definition at line 230 of file ncurses_def.cpp.
 {
     if( !win ) {
         return;
     }
     return curses_check_result( ::mvwvline( win.get<::WINDOW>(), p.y, p.x, ch, n ), OK,
                                 "mvwvline" );
 }
References curses_check_result(), catacurses::window::get(), point::x, and point::y.
Referenced by draw_border_win(), medical_column::draw_column(), draw_connectors(), anonymous_namespace{diary_ui.cpp}::draw_diary_border(), draw_grid(), and draw_recipe_subtabs().
newwin()
catacurses::window catacurses::newwin (int nlines, int ncols, const point & begin)
Definition at line 58 of file ncurses_def.cpp.
 {
     // TODO: check for errors
     const auto w = ::newwin( nlines, ncols, begin.y, begin.x );
     return catacurses::window( std::shared_ptr<void>( w, []( void *const w ) {
         ::curses_check_result( ::delwin( static_cast<::WINDOW *>( w ) ), OK, "delwin" );
     } ) );
 }
References curses_check_result(), point::x, and point::y.
Referenced by advanced_inventory::action_examine(), veh_interact::allocate_windows(), game::bury_screen(), debug_menu::change_spells(), game_menus::inv::compare_items(), Character::conduct_blood_analysis(), overmap_ui::create_note(), game::create_or_get_main_ui_adaptor(), editmap::create_or_get_ui_adaptor(), string_input_popup::create_window(), Character::disp_info(), avatar::disp_medical(), game::disp_NPC_epilogues(), game::disp_NPCs(), advanced_inventory::display(), faction_manager::display(), overmap_ui::display(), player_morale::display(), talk_function::display_and_choose_opts(), game::display_faction_epilogues(), help::display_help(), main_menu::display_sub_menu(), main_menu::display_text(), draw_item_info(), game::draw_panels(), inventory_examiner::execute(), game::extended_description(), Messages::dialog::init(), bodygraph_display::init_ui_windows(), prof_window::init_ui_windows(), veh_app_interact::init_ui_windows(), init_window(), target_ui::init_window_and_input(), exosuit_interact::init_windows(), main_menu::init_windows(), game::inventory_item_menu(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_monsters(), game::look_around(), overmap_ui::map_notes_callback::map_notes_callback(), new_centered_win(), worldfactory::pick_world(), overmap_ui::place_ter_or_special(), avatar::power_bionics(), avatar::power_mutations(), wish_monster_callback::refresh(), dialogue_window::resize(), inventory_selector::resize_window(), robot_finds_kitten::robot_finds_kitten(), overmap_ui::search(), select_crafter_and_crafting_recipe(), set_description(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), uilist::setup(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), options_manager::show(), safemode::show(), live_view::show(), worldfactory::show_active_world_mods(), panel_manager::show_adm(), diary::show_diary_ui(), color_manager::show_gui(), show_scores_ui(), worldfactory::show_worldgen_advanced(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), outfit::sort_armor(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), trade_ui::trade_ui(), computer_session::use(), iexamine::vending(), basecamp::worker_assignment_ui(), and game::zones_manager().
refresh()
void catacurses::refresh ()
Definition at line 181 of file ncurses_def.cpp.
 {
     return curses_check_result( ::refresh(), OK, "refresh" );
 }
References curses_check_result().
Referenced by target_ui::action_switch_mode(), check_encoding(), vehicle::deserialize(), overmap_ui::draw_notes(), ensure_term_size(), and handle_key_blocking_activity().
resizeterm()
void catacurses::resizeterm ()
Definition at line 308 of file ncurses_def.cpp.
 {
     const int new_x = ::getmaxx( stdscr.get<::WINDOW>() );
     const int new_y = ::getmaxy( stdscr.get<::WINDOW>() );
     if( ::is_term_resized( new_x, new_y ) ) {
         game_ui::init_ui();
         ui_manager::screen_resized();
         catacurses::doupdate();
     }
 }
References doupdate(), catacurses::window::get(), getmaxx(), getmaxy(), game_ui::init_ui(), ui_manager::screen_resized(), and stdscr.
Referenced by input_manager::get_input_event(), and input_manager::pump_events().
supports_256_colors()
bool catacurses::supports_256_colors ()
Definition at line 351 of file ncurses_def.cpp.
 {
     return COLORS >= 256;
 }
Referenced by color_manager::load_default().
waddch()
void catacurses::waddch (const window & win, chtype ch)
Definition at line 247 of file ncurses_def.cpp.
 {
     if( !win ) {
         return;
     }
     return curses_check_result( ::waddch( win.get<::WINDOW>(), ch ), OK, "waddch" );
 }
References curses_check_result(), and catacurses::window::get().
Referenced by wputch().
wattroff()
void catacurses::wattroff (const window & win, nc_color attrs)
Definition at line 139 of file ncurses_def.cpp.
 {
     if( !win ) {
         return;
     }
     return curses_check_result( ::wattroff( win.get<::WINDOW>(), attrs.to_int() ), OK, "wattroff" );
 }
References curses_check_result(), catacurses::window::get(), and nc_color::to_int().
Referenced by draw_border(), draw_custom_border(), anonymous_namespace{diary_ui.cpp}::draw_diary_border(), insert_table(), mvwprintz(), mvwputch(), mvwputch_hi(), mvwputch_inv(), advanced_inventory::redraw_pane(), Messages::dialog::show(), wprintz(), and wputch().
wattron()
void catacurses::wattron (const window & win, const nc_color & attrs)
Definition at line 147 of file ncurses_def.cpp.
 {
     if( !win ) {
         return;
     }
     return curses_check_result( ::wattron( win.get<::WINDOW>(), attrs.to_int() ), OK, "wattron" );
 }
References curses_check_result(), catacurses::window::get(), and nc_color::to_int().
Referenced by draw_border(), draw_custom_border(), anonymous_namespace{diary_ui.cpp}::draw_diary_border(), insert_table(), mvwprintz(), mvwputch(), mvwputch_hi(), mvwputch_inv(), advanced_inventory::redraw_pane(), Messages::dialog::show(), wprintz(), and wputch().
wborder()
void catacurses::wborder (const window & win, chtype ls, chtype rs, chtype ts, chtype bs, chtype tl, chtype tr, chtype bl, chtype br)
Definition at line 211 of file ncurses_def.cpp.
 {
     if( !win ) {
         return;
     }
     return curses_check_result( ::wborder( win.get<::WINDOW>(), ls, rs, ts, bs, tl, tr, bl, br ), OK,
                                 "wborder" );
 }
References curses_check_result(), and catacurses::window::get().
Referenced by veh_interact::display_details(), draw_border(), and iexamine::vending().
wclear()
void catacurses::wclear (const window & win)
Definition at line 264 of file ncurses_def.cpp.
 {
     if( !win ) {
         return;
     }
     return curses_check_result( ::wclear( win.get<::WINDOW>() ), OK, "wclear" );
 }
References curses_check_result(), and catacurses::window::get().
Referenced by draw_item_info().
werase()
void catacurses::werase (const window & win)
Definition at line 83 of file ncurses_def.cpp.
 {
     if( !win ) {
         return;
     }
     return curses_check_result( ::werase( win.get<::WINDOW>() ), OK, "werase" );
 }
References curses_check_result(), and catacurses::window::get().
Referenced by debug_menu::change_spells(), veh_interact::create_or_get_ui_adaptor(), custom_draw_func(), decorate_panel(), avatar::disp_medical(), game::disp_NPCs(), faction_manager::display(), player_morale::display(), talk_function::display_and_choose_opts(), veh_interact::display_details(), veh_interact::display_list(), veh_interact::display_mode(), veh_interact::display_name(), veh_interact::display_overview(), veh_interact::display_stats(), main_menu::display_sub_menu(), veh_interact::display_veh(), scrolling_text_view::draw(), dialogue_window::draw(), game::draw(), overmap_ui::draw(), string_input_popup::draw(), char_creation::draw_age(), draw_bionics_info(), draw_bionics_tab(), draw_bionics_tabs(), draw_bionics_titlebar(), char_creation::draw_blood(), draw_border_win(), talk_function::draw_camp_tabs(), draw_center_win(), draw_description(), prof_window::draw_details(), draw_effects_info(), draw_effects_tab(), draw_encumbrance_info(), draw_encumbrance_tab(), char_creation::draw_gender(), bodygraph_display::draw_graph(), prof_window::draw_header(), char_creation::draw_height(), bodygraph_display::draw_info(), veh_app_interact::draw_info(), draw_item_info(), draw_left_win(), lightson_game::draw_level(), char_creation::draw_location(), draw_medical_titlebar(), exosuit_interact::draw_menu(), help::draw_menu(), draw_messages(), game::draw_minimap(), worldfactory::draw_mod_list(), char_creation::draw_name(), char_creation::draw_outfit(), game::draw_panels(), bodygraph_display::draw_partlist(), draw_proficiencies_info(), draw_proficiencies_tab(), prof_window::draw_profs(), draw_recipe_subtabs(), draw_recipe_tabs(), draw_right_win(), draw_skills_info(), draw_skills_tab(), draw_speed_info(), draw_speed_tab(), draw_stats_info(), draw_stats_tab(), draw_tip(), draw_traits_info(), draw_traits_tab(), worldfactory::draw_worldgen_tabs(), game::extended_description(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_monsters(), game::look_around(), avatar::power_bionics(), avatar::power_mutations(), multiline_list::print_entries(), main_menu::print_menu(), vehicle::print_vparts_descs(), string_editor_window::query_string(), advanced_inventory::redraw_pane(), advanced_inventory::redraw_sidebar(), computer_session::refresh(), smart_controller_ui::refresh(), wish_monster_callback::refresh(), inventory_selector::refresh_window(), scrollable_text(), select_crafter_and_crafting_recipe(), set_description(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), distraction_manager::distraction_manager_gui::show(), Messages::dialog::show(), robot_finds_kitten::show(), options_manager::show(), live_view::show(), uilist::show(), diary::show_diary_ui(), show_mutations_titlebar(), show_scores_ui(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), snake_game::snake_over(), outfit::sort_armor(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), trade_ui::trade_ui(), overmap_ui::update_note_preview(), editmap::update_view_with_help(), iexamine::vending(), basecamp::worker_assignment_ui(), game::zones_manager(), and zones_manager_shortcuts().
wmove()
void catacurses::wmove (const window & win, const point & p)
Definition at line 155 of file ncurses_def.cpp.
 {
     if( !win ) {
         return;
     }
     return curses_check_result( ::wmove( win.get<::WINDOW>(), p.y, p.x ), OK, "wmove" );
 }
References curses_check_result(), catacurses::window::get(), point::x, and point::y.
Referenced by map::draw(), string_input_popup::draw(), map::drawsq(), fold_and_print_from(), worldfactory::pick_world(), print_colored_text(), restore_cursor(), shortcut_print(), robot_finds_kitten::show(), and worldfactory::show_worldgen_tab_modselection().
wnoutrefresh()
void catacurses::wnoutrefresh (const window & win)
Definition at line 67 of file ncurses_def.cpp.
 {
     if( !win ) {
         return;
     }
     return curses_check_result( ::wnoutrefresh( win.get<::WINDOW>() ), OK, "wnoutrefresh" );
 }
References curses_check_result(), and catacurses::window::get().
Referenced by background_pane::background_pane(), debug_menu::change_spells(), game_menus::inv::compare_items(), Character::conduct_blood_analysis(), exosuit_interact::create_or_get_ui_adaptor(), veh_app_interact::create_or_get_ui_adaptor(), veh_interact::create_or_get_ui_adaptor(), custom_draw_func(), debug_error_prompt(), Character::disp_info(), avatar::disp_medical(), game::disp_NPCs(), advanced_inventory::display(), faction_manager::display(), player_morale::display(), talk_function::display_and_choose_opts(), veh_interact::display_details(), veh_interact::display_grid(), help::display_help(), veh_interact::display_list(), veh_interact::display_mode(), veh_interact::display_name(), veh_interact::display_overview(), veh_interact::display_stats(), main_menu::display_sub_menu(), main_menu::display_text(), veh_interact::display_veh(), scrolling_text_view::draw(), dialogue_window::draw(), game::draw(), overmap_ui::draw(), string_input_popup::draw(), char_creation::draw_age(), overmap_ui::draw_ascii(), draw_bionics_info(), draw_bionics_tab(), draw_bionics_tabs(), draw_bionics_titlebar(), char_creation::draw_blood(), draw_border_win(), bodygraph_display::draw_borders(), prof_window::draw_borders(), draw_borders_external(), draw_borders_internal(), talk_function::draw_camp_tabs(), draw_can_craft_indicator(), draw_center_win(), draw_description(), prof_window::draw_details(), draw_effects_info(), draw_effects_tab(), draw_encumbrance_info(), draw_encumbrance_tab(), char_creation::draw_gender(), bodygraph_display::draw_graph(), draw_grid(), prof_window::draw_header(), draw_header(), char_creation::draw_height(), draw_hidden_amount(), bodygraph_display::draw_info(), veh_app_interact::draw_info(), draw_item_filter_rules(), draw_item_info(), draw_left_win(), lightson_game::draw_level(), char_creation::draw_location(), exosuit_interact::draw_menu(), help::draw_menu(), draw_messages(), game::draw_minimap(), worldfactory::draw_mod_list(), worldfactory::draw_modselection_borders(), char_creation::draw_name(), overmap_ui::draw_om_sidebar(), char_creation::draw_outfit(), game::draw_panels(), bodygraph_display::draw_partlist(), draw_proficiencies_info(), draw_proficiencies_tab(), prof_window::draw_profs(), draw_recipe_subtabs(), draw_recipe_tabs(), draw_right_win(), draw_skills_info(), draw_skills_tab(), draw_speed_info(), draw_speed_tab(), query_destination_callback::draw_squares(), draw_stats_info(), draw_stats_tab(), draw_tip(), draw_traits_info(), draw_traits_tab(), target_ui::draw_ui_window(), game::extended_description(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_monsters(), game::look_around(), worldfactory::pick_world(), overmap_ui::place_ter_or_special(), avatar::power_bionics(), avatar::power_mutations(), multiline_list::print_entries(), main_menu::print_menu(), vehicle::print_vparts_descs(), string_editor_window::query_string(), advanced_inventory::redraw_sidebar(), computer_session::refresh(), smart_controller_ui::refresh(), app_uilist_handler::refresh(), pocket_favorite_callback::refresh(), spellcasting_callback::refresh(), spellbook_callback::refresh(), teleporter_callback::refresh(), wish_mutate_callback::refresh(), wish_monster_callback::refresh(), wish_item_callback::refresh(), advanced_inventory::refresh_minimap(), inventory_selector::refresh_window(), scrollable_text(), overmap_ui::search(), select_crafter_and_crafting_recipe(), set_description(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), Messages::dialog::show(), robot_finds_kitten::show(), options_manager::show(), safemode::show(), live_view::show(), uilist::show(), worldfactory::show_active_world_mods(), diary::show_diary_ui(), color_manager::show_gui(), show_mutations_titlebar(), show_scores_ui(), worldfactory::show_worldgen_advanced(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), snake_game::snake_over(), outfit::sort_armor(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), trade_ui::trade_ui(), overmap_ui::update_note_preview(), editmap::update_view_with_help(), iexamine::vending(), basecamp::worker_assignment_ui(), game::zones_manager(), zones_manager_draw_borders(), and zones_manager_shortcuts().
wprintw() [1/2]
template<typename ... Args> void catacurses::wprintw (const window & win, const char *const fmt, Args &&... args) inline
Definition at line 118 of file cursesdef.h.
 {
     return wprintw( win, string_format( fmt, std::forward<Args>( args )... ) );
 }
References string_format(), and wprintw().
wprintw() [2/2]
void catacurses::wprintw (const window & win, const std::string & text)
Definition at line 172 of file ncurses_def.cpp.
 {
     if( !win ) {
         return;
     }
     return curses_check_result( ::wprintw( win.get<::WINDOW>(), "%s", text.c_str() ),
                                 OK, "wprintw" );
 }
References curses_check_result(), and catacurses::window::get().
Referenced by game::list_items(), game::list_monsters(), sokoban_game::print_score(), wprintw(), and wprintz().
wredrawln()
void catacurses::wredrawln (const window & win, int beg_line, int num_lines)
Definition at line 255 of file ncurses_def.cpp.
 {
     if( !win ) {
         return;
     }
     return curses_check_result( ::wredrawln( win.get<::WINDOW>(), beg_line, num_lines ), OK,
                                 "wredrawln" );
 }
References curses_check_result(), and catacurses::window::get().
Referenced by Messages::display_messages().
wrefresh()
void catacurses::wrefresh (const window & win)
Definition at line 75 of file ncurses_def.cpp.
 {
     if( !win ) {
         return;
     }
     return curses_check_result( ::wrefresh( win.get<::WINDOW>() ), OK, "wrefresh" );
 }
References curses_check_result(), and catacurses::window::get().
Variable Documentation
newscr
catacurses::window catacurses::newscr extern
Definition at line 305 of file ncurses_def.cpp.
Referenced by init_interface(), ui_adaptor::record_term_cursor(), and restore_cursor().
stdscr
catacurses::window catacurses::stdscr extern
Definition at line 306 of file ncurses_def.cpp.
Referenced by background_pane::background_pane(), check_encoding(), game::create_or_get_main_ui_adaptor(), veh_app_interact::create_or_get_ui_adaptor(), veh_interact::create_or_get_ui_adaptor(), debug_error_prompt(), overmap_ui::display(), draw_item_info(), ensure_term_size(), input_manager::get_input_event(), tab_manager::handle_input(), uilist::handle_mouse(), scrolling_text_view::handle_navigation(), multiline_list::handle_navigation(), init_interface(), game_ui::init_ui(), ma_style_callback::key(), main_menu::opening_screen(), worldfactory::pick_world(), realDebugmsg(), replay_buffered_debugmsg_prompts(), resizeterm(), set_hobbies(), set_profession(), set_scenario(), set_skills(), and set_traits().