Cataclysm DDA: auto_pickup Namespace Reference
auto_pickup Namespace Reference
Classes
class cache
The currently-active set of auto-pickup rules, in a form that allows quick lookup.
class rule
A single entry in the list of auto pickup entries rule_list.
class rule_list
A list of rules.
class user_interface
class base_settings
class player_settings
class npc_settings
Functions
std::list< std::pair< item_location, int > > select_items (const std::vector< item_stack::iterator > &from, const tripoint &location)
Select which items on the map tile should be auto-picked up.
Function Documentation
select_items()
drop_locations auto_pickup::select_items (const std::vector< item_stack::iterator > & from, const tripoint & location)
Select which items on the map tile should be auto-picked up.
The return value represents locations of the selected items on the map.
Parameters
from stack of item entries on a map tile.
location where the stack of items is located on the map.
Returns
sequence of selected items on the map.
Definition at line 248 of file auto_pickup.cpp.
 {
     drop_locations result;
     const map_cursor map_location = map_cursor( location );
     // iterate over all item stacks found in location
     for( const item_stack::iterator &stack : from ) {
         item *item_entry = &*stack;
         // do not auto pickup owned containers or items
         if( !get_option<bool>( "AUTO_PICKUP_OWNED" ) &&
             item_entry->is_owned_by( get_player_character() ) ) {
             continue;
         }
         // do not auto pickup spilt liquids
         if( item_entry->made_of( phase_id::LIQUID ) ) {
             continue;
         }
         rule_state pickup_state = get_autopickup_rule( item_entry );
         bool is_container = item_entry->is_container() && !item_entry->empty_container();
         // before checking contents check if item is on pickup list
         if( pickup_state == rule_state::WHITELISTED ) {
             if( item_entry->is_container() ) {
                 empty_autopickup_target( item_entry, location );
             }
             // skip if the container is still above the limit after emptying it
             if( !within_autopickup_limits( item_entry ) ) {
                 continue;
             }
             int it_count = 0; // TODO: factor in auto pickup max_quantity here
             item_location it_location = item_location( map_location, item_entry );
             result.emplace_back( std::make_pair( it_location, it_count ) );
         } else if( is_container || item_entry->ammo_capacity( ammo_battery ) ) {
             item_location container_location = item_location( map_location, item_entry );
             for( const item_location &add_item : get_autopickup_items( container_location ) ) {
                 int it_count = 0; // TODO: factor in auto pickup max_quantity here
                 result.emplace_back( std::make_pair( add_item, it_count ) );
             }
         }
     }
     return result;
 }
References ammo_battery, item::ammo_capacity(), empty_autopickup_target(), item::empty_container(), get_autopickup_items(), get_autopickup_rule(), get_player_character(), item::is_container(), anonymous_namespace{inventory_ui.cpp}::is_container(), item::is_owned_by(), LIQUID, location, item::made_of(), WHITELISTED, and within_autopickup_limits().
Referenced by Pickup::autopickup().