Cataclysm DDA: anonymous_namespace{monexamine.cpp} Namespace Reference
anonymous_namespace{monexamine.cpp} Namespace Reference
Functions
item_location tack_loc ()
void attach_saddle_to (monster &z)
void remove_saddle_from (monster &z)
void mount_pet (monster &z)
void swap (monster &z)
void push (monster &z)
void rename_pet (monster &z)
void attach_bag_to (monster &z)
void dump_items (monster &z)
void remove_bag_from (monster &z)
bool give_items_to (monster &z)
item_location pet_armor_loc (monster &z)
bool add_armor (monster &z)
void remove_harness (monster &z)
void remove_armor (monster &z)
void play_with (monster &z)
void cull (monster &z)
void add_leash (monster &z)
void remove_leash (monster &z)
void tie_pet (monster &z)
void untie_pet (monster &z)
void start_leading (monster &z)
void stop_leading (monster &z)
void milk_source (monster &source_mon)
void shear_animal (monster &z)
void remove_battery (monster &z)
void insert_battery (monster &z)
Function Documentation
add_armor()
bool anonymous_namespace{monexamine.cpp}::add_armor (monster & z)
Definition at line 308 of file monexamine.cpp.
 {
     std::string pet_name = z.get_name();
     item_location loc = pet_armor_loc( z );
     if( !loc ) {
         add_msg( _( "Never mind." ) );
         return true;
     }
     item &armor = *loc;
     units::mass max_weight = z.weight_capacity() - z.get_carried_weight();
     if( max_weight <= armor.weight() ) {
         add_msg( pgettext( "pet armor", "Your %1$s is too heavy for your %2$s." ), armor.tname( 1 ),
                  pet_name );
         return true;
     }
     armor.set_var( "pet_armor", "true" );
     z.armor_item = cata::make_value<item>( armor );
     add_msg( pgettext( "pet armor", "You put the %1$s on your %2$s." ), armor.display_name(),
              pet_name );
     loc.remove_item();
     z.add_effect( effect_monster_armor, 1_turns, true );
     // TODO: armoring a horse takes a lot longer than 2 seconds. This should be a long action.
     get_player_character().mod_moves( -to_moves<int>( 2_seconds ) );
     return true;
 }
References _, Creature::add_effect(), add_msg(), monster::armor_item, item::display_name(), effect_monster_armor, monster::get_carried_weight(), monster::get_name(), get_player_character(), Creature::mod_moves(), pet_armor_loc(), pgettext, item_location::remove_item(), item::set_var(), item::tname(), item::weight(), and monster::weight_capacity().
Referenced by monexamine::pet_menu().
add_leash()
void anonymous_namespace{monexamine.cpp}::add_leash (monster & z)
Definition at line 378 of file monexamine.cpp.
 {
     if( z.has_effect( effect_leashed ) ) {
         return;
     }
     Character &player_character = get_player_character();
     std::vector<item *> rope_inv = player_character.cache_get_items_with( json_flag_TIE_UP );
     if( rope_inv.empty() ) {
         return;
     }
     int i = 0;
     uilist selection_menu;
     selection_menu.text = string_format( _( "Select an item to leash your %s with." ), z.get_name() );
     selection_menu.addentry( i++, true, MENU_AUTOASSIGN, _( "Cancel" ) );
     for( const item *iter : rope_inv ) {
         selection_menu.addentry( i++, true, MENU_AUTOASSIGN, _( "Use %s" ), iter->tname() );
     }
     selection_menu.selected = 1;
     selection_menu.query();
     int index = selection_menu.ret;
     if( index == 0 || index == UILIST_CANCEL || index < 0 ||
         index > static_cast<int>( rope_inv.size() ) ) {
         return;
     }
     item *rope_item = rope_inv[index - 1];
     z.tied_item = cata::make_value<item>( *rope_item );
     player_character.i_rem( rope_item );
     z.add_effect( effect_leashed, 1_turns, true );
     add_msg( _( "You add a leash to your %s." ), z.get_name() );
 }
References _, Creature::add_effect(), add_msg(), uilist::addentry(), Character::cache_get_items_with(), effect_leashed, monster::get_name(), get_player_character(), Creature::has_effect(), Character::i_rem(), json_flag_TIE_UP, MENU_AUTOASSIGN, uilist::query(), uilist::ret, uilist::selected, string_format(), uilist::text, monster::tied_item, and UILIST_CANCEL.
Referenced by monexamine::pet_menu().
attach_bag_to()
void anonymous_namespace{monexamine.cpp}::attach_bag_to (monster & z)
Definition at line 169 of file monexamine.cpp.
 {
     std::string pet_name = z.get_name();
     auto filter = []( const item & it ) {
         return it.is_armor() && it.get_total_capacity() > 0_ml && !it.has_flag( flag_INTEGRATED );
     };
     avatar &player_character = get_avatar();
     item_location loc = game_menus::inv::titled_filter_menu( filter, player_character,
                         _( "Bag item" ) );
     if( !loc ) {
         add_msg( _( "Never mind." ) );
         return;
     }
     item &it = *loc;
     if( it.weight() > z.weight_capacity() ) {
         add_msg( _( "The %1$s is too heavy for the %2$s to carry." ), it.tname(), pet_name );
         return;
     }
     if( !it.is_container_empty() ) {
         for( item *top_item : it.all_items_top() ) {
             item &i = *top_item;
             z.add_item( i );
             it.remove_item( i );
         }
     }
     z.storage_item = cata::make_value<item>( it );
     add_msg( _( "You mount the %1$s on your %2$s." ), it.display_name(), pet_name );
     player_character.i_rem( &it );
     z.add_effect( effect_has_bag, 1_turns, true );
     // Update encumbrance in case we were wearing it
     player_character.flag_encumbrance();
     player_character.mod_moves( -to_moves<int>( 2_seconds ) );
 }
References _, Creature::add_effect(), monster::add_item(), add_msg(), item::all_items_top(), item::display_name(), effect_has_bag, filter, Character::flag_encumbrance(), flag_INTEGRATED, get_avatar(), monster::get_name(), Character::i_rem(), item::is_container_empty(), Creature::mod_moves(), visitable::remove_item(), monster::storage_item, game_menus::inv::titled_filter_menu(), item::tname(), item::weight(), and monster::weight_capacity().
Referenced by monexamine::pet_menu().
attach_saddle_to()
void anonymous_namespace{monexamine.cpp}::attach_saddle_to (monster & z)
Definition at line 82 of file monexamine.cpp.
 {
     if( z.has_effect( effect_monster_saddled ) ) {
         return;
     }
     item_location loc = tack_loc();
     if( !loc ) {
         add_msg( _( "Never mind." ) );
         return;
     }
     z.add_effect( effect_monster_saddled, 1_turns, true );
     z.tack_item = cata::make_value<item>( *loc.get_item() );
     loc.remove_item();
 }
References _, Creature::add_effect(), add_msg(), effect_monster_saddled, item_location::get_item(), Creature::has_effect(), item_location::remove_item(), monster::tack_item, and tack_loc().
Referenced by monexamine::pet_menu().
cull()
void anonymous_namespace{monexamine.cpp}::cull (monster & z)
Definition at line 368 of file monexamine.cpp.
 {
     Character &player_character = get_player_character();
     if( !player_character.has_quality( qual_CUT ) ) {
         add_msg( _( "You don't have a cutting tool." ) );
         return;
     }
     z.apply_damage( nullptr, bodypart_id( "torso" ), z.get_hp() );
 }
References _, add_msg(), monster::apply_damage(), monster::get_hp(), get_player_character(), Character::has_quality(), and qual_CUT.
Referenced by monexamine::pet_menu().
dump_items()
void anonymous_namespace{monexamine.cpp}::dump_items (monster & z)
Definition at line 207 of file monexamine.cpp.
 {
     std::string pet_name = z.get_name();
     Character &player_character = get_player_character();
     map &here = get_map();
     for( item &it : z.inv ) {
         if( it.has_var( "DESTROY_ITEM_ON_MON_DEATH" ) ) {
             continue;
         }
         here.add_item_or_charges( player_character.pos(), it );
     }
     z.inv.clear();
     add_msg( _( "You dump the contents of the %s's bag on the ground." ), pet_name );
     player_character.mod_moves( -to_moves<int>( 2_seconds ) );
 }
References _, map::add_item_or_charges(), add_msg(), get_map(), monster::get_name(), get_player_character(), item::has_var(), monster::inv, Creature::mod_moves(), and Creature::pos().
Referenced by monexamine::pet_menu(), and remove_bag_from().
give_items_to()
bool anonymous_namespace{monexamine.cpp}::give_items_to (monster & z)
Definition at line 241 of file monexamine.cpp.
 {
     std::string pet_name = z.get_name();
     if( !z.storage_item ) {
         add_msg( _( "There is no container on your %s to put things in!" ), pet_name );
         return true;
     }
     item &storage = *z.storage_item;
     units::mass max_weight = z.weight_capacity() - z.get_carried_weight();
     units::volume max_volume = storage.get_total_capacity() - z.get_carried_volume();
     units::length max_length = storage.max_containable_length();
     avatar &player_character = get_avatar();
     drop_locations items = game_menus::inv::multidrop( player_character );
     drop_locations to_move;
     for( const drop_location &itq : items ) {
         const item &it = *itq.first;
         units::volume item_volume = it.volume() * itq.second;
         units::mass item_weight = it.weight() * itq.second;
         units::length item_length = it.length();
         if( max_weight < item_weight ) {
             add_msg( _( "The %1$s is too heavy for the %2$s to carry." ), it.tname(), pet_name );
             continue;
         } else if( max_volume < item_volume ) {
             add_msg( _( "The %1$s is too big to fit in the %2$s." ), it.tname(), storage.tname() );
             continue;
         } else if( max_length < item_length ) {
             add_msg( _( "The %1$s is too long to fit in the %2$s." ), it.tname(), storage.tname() );
             continue;
         } else {
             max_weight -= item_weight;
             max_volume -= item_volume;
             to_move.insert( to_move.end(), itq );
         }
     }
     // Quit if there is nothing to add
     if( to_move.empty() ) {
         add_msg( _( "Never mind." ) );
         return true;
     }
     z.add_effect( effect_controlled, 5_turns );
     player_character.drop( to_move, z.pos(), true );
     // Print an appropriate message for the inserted item or items
     if( to_move.size() > 1 ) {
         add_msg( _( "You put %1$s items in the %2$s on your %3$s." ), to_move.size(), storage.tname(),
                  pet_name );
     } else {
         item_location loc = to_move.front().first;
         item &it = *loc;
         //~ %1$s - item name, %2$s - storage item name, %3$s - pet name
         add_msg( _( "You put the %1$s in the %2$s on your %3$s." ), it.tname(), storage.tname(), pet_name );
     }
     // Return success if all items were inserted
     return to_move.size() == items.size();
 }
References _, Creature::add_effect(), add_msg(), Character::drop(), effect_controlled, get_avatar(), monster::get_carried_volume(), monster::get_carried_weight(), monster::get_name(), item::get_total_capacity(), item::length(), item::max_containable_length(), game_menus::inv::multidrop(), Creature::pos(), monster::storage_item, item::tname(), item::volume(), item::weight(), and monster::weight_capacity().
Referenced by monexamine::pet_menu().
insert_battery()
void anonymous_namespace{monexamine.cpp}::insert_battery (monster & z)
Definition at line 530 of file monexamine.cpp.
 {
     if( z.battery_item ) {
         // already has a battery, shouldn't be called with one, but just in case.
         return;
     }
     Character &player_character = get_player_character();
     std::vector<item *> bat_inv = player_character.cache_get_items_with( json_flag_MECH_BAT );
     if( bat_inv.empty() ) {
         return;
     }
     int i = 0;
     uilist selection_menu;
     selection_menu.text = string_format( _( "Select an battery to insert into your %s." ),
                                          z.get_name() );
     selection_menu.addentry( i++, true, MENU_AUTOASSIGN, _( "Cancel" ) );
     for( const item *iter : bat_inv ) {
         selection_menu.addentry( i++, true, MENU_AUTOASSIGN, _( "Use %s" ), iter->tname() );
     }
     selection_menu.selected = 1;
     selection_menu.query();
     int index = selection_menu.ret;
     if( index == 0 || index == UILIST_CANCEL || index < 0 ||
         index > static_cast<int>( bat_inv.size() ) ) {
         return;
     }
     item *bat_item = bat_inv[index - 1];
     z.battery_item = cata::make_value<item>( *bat_item );
     player_character.i_rem( bat_item );
 }
References _, uilist::addentry(), monster::battery_item, Character::cache_get_items_with(), monster::get_name(), get_player_character(), Character::i_rem(), json_flag_MECH_BAT, MENU_AUTOASSIGN, uilist::query(), uilist::ret, uilist::selected, string_format(), uilist::text, and UILIST_CANCEL.
Referenced by monexamine::pet_menu().
milk_source()
void anonymous_namespace{monexamine.cpp}::milk_source (monster & source_mon)
Definition at line 473 of file monexamine.cpp.
 {
     itype_id milked_item = source_mon.type->starting_ammo.begin()->first;
     auto milkable_ammo = source_mon.ammo.find( milked_item );
     if( milkable_ammo == source_mon.ammo.end() ) {
         debugmsg( "The %s has no milkable %s.", source_mon.get_name(), milked_item.str() );
         return;
     }
     else if( milkable_ammo->second > 0 ) {
         const int moves = to_moves<int>( time_duration::from_minutes( milkable_ammo->second / 2 ) );
         std::vector<tripoint> coords{};
         std::vector<std::string> str_values{};
         Character &player_character = get_player_character();
         coords.push_back( get_map().getabs( source_mon.pos() ) );
         // pin the cow in place if it isn't already
         bool temp_tie = !source_mon.has_effect( effect_tied );
         if( temp_tie ) {
             source_mon.add_effect( effect_tied, 1_turns, true );
             str_values.emplace_back( "temp_tie" );
         }
         player_character.assign_activity( milk_activity_actor( moves, coords, str_values ) );
         add_msg( _( "You milk the %s." ), source_mon.get_name() );
     } else {
         add_msg( _( "The %s has no more milk." ), source_mon.get_name() );
         if( !source_mon.has_effect( effect_critter_well_fed ) ) {
             add_msg( _( "It might not be getting enough to eat." ) );
         }
     }
 }
References _, Creature::add_effect(), add_msg(), monster::ammo, Character::assign_activity(), debugmsg, effect_critter_well_fed, effect_tied, time_duration::from_minutes(), get_map(), monster::get_name(), get_player_character(), Creature::has_effect(), Creature::pos(), mtype::starting_ammo, string_id< T >::str(), and monster::type.
Referenced by monexamine::pet_menu().
mount_pet()
void anonymous_namespace{monexamine.cpp}::mount_pet (monster & z)
Definition at line 107 of file monexamine.cpp.
 {
     get_player_character().mount_creature( z );
 }
References get_player_character(), and Character::mount_creature().
Referenced by monexamine::pet_menu().
pet_armor_loc()
item_location anonymous_namespace{monexamine.cpp}::pet_armor_loc (monster & z)
Definition at line 297 of file monexamine.cpp.
 {
     auto filter = [z]( const item & it ) {
         return z.type->bodytype == it.get_pet_armor_bodytype() &&
                z.get_volume() >= it.get_pet_armor_min_vol() &&
                z.get_volume() <= it.get_pet_armor_max_vol();
     };
     return game_menus::inv::titled_filter_menu( filter, get_avatar(), _( "Pet armor" ) );
 }
References _, mtype::bodytype, filter, get_avatar(), monster::get_volume(), game_menus::inv::titled_filter_menu(), and monster::type.
Referenced by add_armor().
play_with()
void anonymous_namespace{monexamine.cpp}::play_with (monster & z)
Definition at line 360 of file monexamine.cpp.
 {
     std::string pet_name = z.get_name();
     Character &player_character = get_player_character();
     const std::string &petstr = z.type->petfood.pet;
     player_character.assign_activity( play_with_pet_activity_actor( pet_name, petstr ) );
 }
References Character::assign_activity(), monster::get_name(), get_player_character(), pet_food_data::pet, mtype::petfood, and monster::type.
Referenced by monexamine::pet_menu().
push()
void anonymous_namespace{monexamine.cpp}::push (monster & z)
Strength increases chance to successfully push your pet
Definition at line 137 of file monexamine.cpp.
 {
     std::string pet_name = z.get_name();
     Character &player_character = get_player_character();
     player_character.mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
     ///\EFFECT_STR increases chance to successfully push your pet
     if( one_in( player_character.str_cur ) ) {
         add_msg( _( "You pushed the %s, but it resisted." ), pet_name );
         return;
     }
     point delta( z.posx() - player_character.posx(), z.posy() - player_character.posy() );
     if( z.move_to( tripoint( z.posx( ) + delta.x, z.posy( ) + delta.y, z.posz( ) ) ) ) {
         add_msg( _( "You pushed the %s." ), pet_name );
     } else {
         add_msg( _( "You pushed the %s, but it resisted." ), pet_name );
         return;
     }
 }
References _, add_msg(), monster::get_name(), get_player_character(), Creature::mod_moves(), monster::move_to(), one_in(), Creature::posx(), Creature::posy(), Creature::posz(), Character::str_cur, point::x, and point::y.
Referenced by monexamine::mfriend_menu(), game::npc_menu(), and monexamine::pet_menu().
remove_armor()
void anonymous_namespace{monexamine.cpp}::remove_armor (monster & z)
Definition at line 343 of file monexamine.cpp.
 {
     std::string pet_name = z.get_name();
     if( z.armor_item ) {
         z.armor_item->erase_var( "pet_armor" );
         get_map().add_item_or_charges( z.pos(), *z.armor_item );
         add_msg( pgettext( "pet armor", "You remove the %1$s from %2$s." ), z.armor_item->display_name(),
                  pet_name );
         z.armor_item.reset();
         // TODO: removing armor from a horse takes a lot longer than 2 seconds. This should be a long action.
         get_player_character().mod_moves( -to_moves<int>( 2_seconds ) );
     } else {
         add_msg( m_bad, _( "Your %1$s isn't wearing armor!" ), pet_name );
     }
     z.remove_effect( effect_monster_armor );
 }
References _, map::add_item_or_charges(), add_msg(), monster::armor_item, effect_monster_armor, get_map(), monster::get_name(), get_player_character(), m_bad, Creature::mod_moves(), pgettext, Creature::pos(), and Creature::remove_effect().
Referenced by monexamine::pet_menu().
remove_bag_from()
void anonymous_namespace{monexamine.cpp}::remove_bag_from (monster & z)
Definition at line 223 of file monexamine.cpp.
 {
     std::string pet_name = z.get_name();
     if( z.storage_item ) {
         if( !z.inv.empty() ) {
             dump_items( z );
         }
         Character &player_character = get_player_character();
         get_map().add_item_or_charges( player_character.pos(), *z.storage_item );
         add_msg( _( "You remove the %1$s from %2$s." ), z.storage_item->display_name(), pet_name );
         z.storage_item.reset();
         player_character.mod_moves( -to_moves<int>( 2_seconds ) );
     } else {
         add_msg( m_bad, _( "Your %1$s doesn't have a bag!" ), pet_name );
     }
     z.remove_effect( effect_has_bag );
 }
References _, map::add_item_or_charges(), add_msg(), dump_items(), effect_has_bag, get_map(), monster::get_name(), get_player_character(), monster::inv, m_bad, Creature::mod_moves(), Creature::pos(), Creature::remove_effect(), and monster::storage_item.
Referenced by monexamine::pet_menu().
remove_battery()
void anonymous_namespace{monexamine.cpp}::remove_battery (monster & z)
Definition at line 524 of file monexamine.cpp.
 {
     get_map().add_item_or_charges( get_player_character().pos(), *z.battery_item );
     z.battery_item.reset();
 }
References map::add_item_or_charges(), monster::battery_item, get_map(), get_player_character(), and math_opers::pos().
Referenced by monexamine::pet_menu().
remove_harness()
void anonymous_namespace{monexamine.cpp}::remove_harness (monster & z)
Definition at line 337 of file monexamine.cpp.
 {
     z.remove_effect( effect_harnessed );
     add_msg( m_info, _( "You unhitch %s from the vehicle." ), z.get_name() );
 }
References _, add_msg(), effect_harnessed, monster::get_name(), m_info, and Creature::remove_effect().
Referenced by monexamine::pet_menu().
remove_leash()
void anonymous_namespace{monexamine.cpp}::remove_leash (monster & z)
Definition at line 409 of file monexamine.cpp.
 {
     if( !z.has_effect( effect_leashed ) ) {
         return;
     }
     z.remove_effect( effect_led_by_leash );
     z.remove_effect( effect_leashed );
     if( z.tied_item ) {
         get_player_character().i_add( *z.tied_item );
         z.tied_item.reset();
     }
     add_msg( _( "You remove the leash from your %s." ), z.get_name() );
 }
References _, add_msg(), effect_leashed, effect_led_by_leash, monster::get_name(), get_player_character(), Creature::has_effect(), Character::i_add(), Creature::remove_effect(), and monster::tied_item.
Referenced by monexamine::pet_menu().
remove_saddle_from()
void anonymous_namespace{monexamine.cpp}::remove_saddle_from (monster & z)
Definition at line 97 of file monexamine.cpp.
 {
     if( !z.has_effect( effect_monster_saddled ) ) {
         return;
     }
     z.remove_effect( effect_monster_saddled );
     get_player_character().i_add( *z.tack_item );
     z.tack_item.reset();
 }
References effect_monster_saddled, get_player_character(), Creature::has_effect(), Character::i_add(), Creature::remove_effect(), and monster::tack_item.
Referenced by monexamine::pet_menu().
rename_pet()
void anonymous_namespace{monexamine.cpp}::rename_pet (monster & z)
Definition at line 158 of file monexamine.cpp.
 {
     std::string unique_name = string_input_popup()
                               .title( _( "Enter new pet name:" ) )
                               .width( 20 )
                               .query_string();
     if( !unique_name.empty() ) {
         z.unique_name = unique_name;
     }
 }
References _, string_input_popup::query_string(), string_input_popup::title(), monster::unique_name, and string_input_popup::width().
Referenced by monexamine::mfriend_menu(), and monexamine::pet_menu().
shear_animal()
void anonymous_namespace{monexamine.cpp}::shear_animal (monster & z)
Definition at line 506 of file monexamine.cpp.
 {
     Character &guy = get_player_character();
     if( !guy.has_quality( qual_SHEAR ) ) {
         add_msg( _( "You don't have a shearing tool." ) );
     }
     // was monster already tied before shearing
     const bool monster_tied = z.has_effect( effect_tied );
     // tie the critter so it doesn't move while being sheared
     if( !monster_tied ) {
         z.add_effect( effect_tied, 1_turns, true );
     }
     guy.assign_activity( shearing_activity_actor( z.pos(), !monster_tied ) );
 }
References _, Creature::add_effect(), add_msg(), Character::assign_activity(), effect_tied, get_player_character(), Creature::has_effect(), Character::has_quality(), Creature::pos(), and qual_SHEAR.
Referenced by monexamine::pet_menu().
start_leading()
void anonymous_namespace{monexamine.cpp}::start_leading (monster & z)
Definition at line 445 of file monexamine.cpp.
 {
     if( z.has_effect( effect_led_by_leash ) ) {
         return;
     }
     if( z.has_effect( effect_tied ) ) {
         untie_pet( z );
     }
     z.add_effect( effect_led_by_leash, 1_turns, true );
     z.unset_dest();
     add_msg( _( "You take hold of the %s's leash to make it follow you." ), z.get_name() );
 }
References _, Creature::add_effect(), add_msg(), effect_led_by_leash, effect_tied, monster::get_name(), Creature::has_effect(), monster::unset_dest(), and untie_pet().
Referenced by monexamine::pet_menu().
stop_leading()
void anonymous_namespace{monexamine.cpp}::stop_leading (monster & z)
Definition at line 458 of file monexamine.cpp.
 {
     if( !z.has_effect( effect_led_by_leash ) ) {
         return;
     }
     z.remove_effect( effect_led_by_leash );
     // The pet may or may not stop following so don't print that here
     add_msg( _( "You release the %s's leash." ), z.get_name() );
 }
References _, add_msg(), effect_led_by_leash, monster::get_name(), Creature::has_effect(), and Creature::remove_effect().
Referenced by monexamine::pet_menu().
swap()
void anonymous_namespace{monexamine.cpp}::swap (monster & z)
Strength increases chance to successfully swap positions with your pet \EFFECT_DEX increases chance to successfully swap positions with your pet
Definition at line 112 of file monexamine.cpp.
 {
     std::string pet_name = z.get_name();
     Character &player_character = get_player_character();
     player_character.mod_moves( -to_moves<int>( 1_seconds ) * 1.5 );
     ///\EFFECT_STR increases chance to successfully swap positions with your pet
     ///\EFFECT_DEX increases chance to successfully swap positions with your pet
     if( !one_in( ( player_character.str_cur + player_character.dex_cur ) / 6 ) ) {
         bool t = z.has_effect( effect_tied );
         if( t ) {
             z.remove_effect( effect_tied );
         }
         g->swap_critters( player_character, z );
         if( t ) {
             z.add_effect( effect_tied, 1_turns, true );
         }
         add_msg( _( "You swap positions with your %s." ), pet_name );
     } else {
         add_msg( _( "You fail to budge your %s!" ), pet_name );
     }
 }
References _, Creature::add_effect(), add_msg(), Character::dex_cur, effect_tied, g, monster::get_name(), get_player_character(), Creature::has_effect(), Creature::mod_moves(), one_in(), Creature::remove_effect(), and Character::str_cur.
Referenced by monexamine::mfriend_menu(), and monexamine::pet_menu().
tack_loc()
item_location anonymous_namespace{monexamine.cpp}::tack_loc ()
Definition at line 73 of file monexamine.cpp.
 {
     auto filter = []( const item & it ) {
         return it.has_flag( json_flag_TACK );
     };
     return game_menus::inv::titled_filter_menu( filter, get_avatar(), _( "Tack" ) );
 }
References _, filter, get_avatar(), json_flag_TACK, and game_menus::inv::titled_filter_menu().
Referenced by attach_saddle_to().
tie_pet()
void anonymous_namespace{monexamine.cpp}::tie_pet (monster & z)
Definition at line 423 of file monexamine.cpp.
 {
     if( z.has_effect( effect_tied ) ) {
         return;
     }
     z.add_effect( effect_tied, 1_turns, true );
     add_msg( _( "You tie your %s." ), z.get_name() );
 }
References _, Creature::add_effect(), add_msg(), effect_tied, monster::get_name(), and Creature::has_effect().
Referenced by monexamine::pet_menu().
untie_pet()
void anonymous_namespace{monexamine.cpp}::untie_pet (monster & z)
Definition at line 432 of file monexamine.cpp.
 {
     if( !z.has_effect( effect_tied ) ) {
         return;
     }
     z.remove_effect( effect_tied );
     if( !z.has_effect( effect_leashed ) ) {
         // migration code dealing with animals tied before leashing was introduced
         z.add_effect( effect_leashed, 1_turns, true );
     }
     add_msg( _( "You untie your %s." ), z.get_name() );
 }
References _, Creature::add_effect(), add_msg(), effect_leashed, effect_tied, monster::get_name(), Creature::has_effect(), and Creature::remove_effect().
Referenced by monexamine::pet_menu(), and start_leading().