Cataclysm DDA: anonymous_namespace{veh_type.cpp} Namespace Reference
anonymous_namespace{veh_type.cpp} Namespace Reference
Variables
generic_factory< vehicle_prototype > vehicle_prototype_factory ("vehicle", "id")
generic_factory< vpart_info > vpart_info_factory ("vehicle_part", "id")
Variable Documentation
vehicle_prototype_factory
generic_factory<vehicle_prototype> anonymous_namespace{veh_type.cpp}::vehicle_prototype_factory("vehicle", "id") ("vehicle" , "id")
Referenced by vehicles::finalize_prototypes(), vehicles::get_all_prototypes(), vehicles::load_prototype(), and vehicles::reset_prototypes().
vpart_info_factory
generic_factory<vpart_info> anonymous_namespace{veh_type.cpp}::vpart_info_factory("vehicle_part", "id") ("vehicle_part" , "id")
Referenced by vehicles::parts::finalize(), vehicles::parts::get_all(), vpart_info::handle_inheritance(), string_id< T >::is_valid(), vehicles::parts::load(), and vehicles::parts::reset().