Cataclysm DDA: anonymous_namespace{debug_menu.cpp} Namespace Reference
anonymous_namespace{debug_menu.cpp} Namespace Reference
Classes
struct fake_tripoint
struct OM_point
Typedefs
using rdi_t = fs::recursive_directory_iterator
using f_validate_t = std::function< bool(fs::path const &dep, rdi_t &iter)>
Functions
std::istream & operator>> (std::istream &is, fake_tripoint &pos)
std::istream & operator>> (std::istream &is, OM_point &pos)
template<typename T >
T _from_fs_string (std::string const &s)
tripoint _from_map_string (std::string const &s)
tripoint _from_OM_string (std::string const &s)
bool _add_dir (tgz_archiver &tgz, fs::path const &root, f_validate_t const &validate={})
bool _trim_mapbuffer (fs::path const &dep, rdi_t &iter, tripoint_range< tripoint > const &segs, tripoint_range< tripoint > const &regs)
bool _trim_overmapbuffer (fs::path const &dep, tripoint_range< tripoint > const &oms)
bool _discard_temporary (fs::path const &dep)
void write_min_archive ()
Typedef Documentation
f_validate_t
using anonymous_namespace{debug_menu.cpp}::f_validate_t = typedef std::function<bool(fs::path const &dep, rdi_t &iter)>
Definition at line 328 of file debug_menu.cpp.
rdi_t
using anonymous_namespace{debug_menu.cpp}::rdi_t = typedef fs::recursive_directory_iterator
Definition at line 327 of file debug_menu.cpp.
Function Documentation
_add_dir()
bool anonymous_namespace{debug_menu.cpp}::_add_dir (tgz_archiver & tgz, fs::path const & root, f_validate_t const & validate = {})
Definition at line 330 of file debug_menu.cpp.
                                                                                      {} )
 {
     fs::path const cnc = root.has_root_path() ?  fs::canonical( root ) : root;
     fs::path const parent_cnc = cnc.parent_path();
     for( auto iter = rdi_t( cnc ); iter != rdi_t(); ++iter ) {
         fs::path const dep = iter->path().lexically_relative( parent_cnc );
         if( validate && !validate( dep, iter ) ) {
             continue;
         }
         if( !tgz.add_file( *iter, dep ) ) {
             popup( _( "Failed to create minimized archive" ) );
             return false;
         }
     }
     return true;
 }
Referenced by write_min_archive().
_discard_temporary()
bool anonymous_namespace{debug_menu.cpp}::_discard_temporary (fs::path const & dep)
Definition at line 382 of file debug_menu.cpp.
 {
     return !dep.has_extension() || dep.extension() != fs::u8path( ".temp" );
 }
Referenced by write_min_archive().
_from_fs_string()
template<typename T > T anonymous_namespace{debug_menu.cpp}::_from_fs_string (std::string const & s)
Definition at line 303 of file debug_menu.cpp.
 {
     std::istringstream is( s );
     is.imbue( std::locale::classic() );
     T result;
     is >> result;
     if( !is ) {
         return T{};
     }
     return result;
 }
_from_map_string()
tripoint anonymous_namespace{debug_menu.cpp}::_from_map_string (std::string const & s)
Definition at line 315 of file debug_menu.cpp.
 {
     fake_tripoint const ft = _from_fs_string<fake_tripoint>( s );
     return { ft.x, ft.y, ft.z };
 }
References anonymous_namespace{debug_menu.cpp}::fake_tripoint::x, anonymous_namespace{debug_menu.cpp}::fake_tripoint::y, and anonymous_namespace{debug_menu.cpp}::fake_tripoint::z.
_from_OM_string()
tripoint anonymous_namespace{debug_menu.cpp}::_from_OM_string (std::string const & s)
Definition at line 321 of file debug_menu.cpp.
 {
     OM_point const om = _from_fs_string<OM_point>( s );
     return { om.x, om.y, 0 };
 }
References coords::om.
Referenced by _trim_overmapbuffer().
_trim_mapbuffer()
bool anonymous_namespace{debug_menu.cpp}::_trim_mapbuffer (fs::path const & dep, rdi_t & iter, tripoint_range< tripoint > const & segs, tripoint_range< tripoint > const & regs)
Definition at line 351 of file debug_menu.cpp.
 {
     // discard map memory outside of current region and adjacent regions
     if( dep.parent_path().extension() == fs::u8path( ".mm1" ) &&
         !regs.is_point_inside( tripoint{ _from_map_string( dep.stem().string() ).xy(), 0 } ) ) {
         return false;
     }
     // discard map buffer outside of current and adjacent segments
     if( dep.parent_path().filename() == fs::u8path( "maps" ) &&
         !segs.is_point_inside(
             tripoint{ _from_map_string( dep.filename().string() ).xy(), 0 } ) ) {
         iter.disable_recursion_pending();
         return false;
     }
     return true;
 }
References tripoint_range< Tripoint >::is_point_inside().
Referenced by write_min_archive().
_trim_overmapbuffer()
bool anonymous_namespace{debug_menu.cpp}::_trim_overmapbuffer (fs::path const & dep, tripoint_range< tripoint > const & oms)
Definition at line 369 of file debug_menu.cpp.
 {
     std::string const fname = dep.filename().generic_u8string();
     std::string::size_type const seenpos = fname.find( ".seen." );
     if( seenpos != std::string::npos ) {
         return oms.is_point_inside( _from_OM_string( fname.substr( seenpos + 6 ) ) );
     }
     return fname.size() < 4 || fname[0] != 'o' || fname[1] != '.' ||
            oms.is_point_inside( _from_OM_string( fname.substr( 2 ) ) );
 }
References _from_OM_string(), and tripoint_range< Tripoint >::is_point_inside().
Referenced by write_min_archive().
operator>>() [1/2]
std::istream& anonymous_namespace{debug_menu.cpp}::operator>> (std::istream & is, fake_tripoint & pos)
Definition at line 288 of file debug_menu.cpp.
 {
     char c = 0;
     is >> pos.x &&is.get( c ) &&c == '.' &&is >> pos.y &&is.get( c ) &&c == '.' &&is >> pos.z;
     return is;
 }
References c, and math_opers::pos().
operator>>() [2/2]
std::istream& anonymous_namespace{debug_menu.cpp}::operator>> (std::istream & is, OM_point & pos)
Definition at line 295 of file debug_menu.cpp.
 {
     char c = 0;
     is >> pos.x &&is.get( c ) &&c == '.' &&is >> pos.y;
     return is;
 }
References c, and math_opers::pos().
write_min_archive()
void anonymous_namespace{debug_menu.cpp}::write_min_archive ()
Definition at line 387 of file debug_menu.cpp.
 {
     tripoint_abs_seg const seg = project_to<coords::seg>( get_avatar().get_location() );
     tripoint_range<tripoint> const segs = points_in_radius( tripoint{ seg.xy().raw(), 0 }, 1 );
     point sm = project_to<coords::sm>( get_avatar().get_location() ).raw().xy();
     point const reg = sm_to_mmr_remain( sm.x, sm.y );
     tripoint_range<tripoint> const regs = points_in_radius( tripoint{ reg, 0 }, 1 );
     tripoint_abs_om const om = project_to<coords::om>( get_avatar().get_location() );
     tripoint_range<tripoint> const oms = points_in_radius( tripoint{ om.raw().xy(), 0 }, 1 );
     fs::path const save_root( PATH_INFO::world_base_save_path_path() );
     std::string const ofile = save_root.string() + "-trimmed.tar.gz";
     tgz_archiver tgz( ofile );
     f_validate_t const mb_validate = [&segs, &regs, &oms]( fs::path const & dep, rdi_t & iter ) {
         return _discard_temporary( dep ) && _trim_mapbuffer( dep, iter, segs, regs ) &&
                _trim_overmapbuffer( dep, oms );
     };
     if( _add_dir( tgz, save_root, mb_validate ) &&
         _add_dir( tgz, fs::path( PATH_INFO::config_dir_path() ) ) ) {
         tgz.finalize();
         popup( string_format( _( "Minimized archive saved to %s" ), ofile ) );
     }
 }
References _, _add_dir(), _discard_temporary(), _trim_mapbuffer(), _trim_overmapbuffer(), PATH_INFO::config_dir_path(), tgz_archiver::finalize(), get_avatar(), coords::om, points_in_radius(), popup(), coords::seg, coords::sm, sm_to_mmr_remain(), string_format(), and PATH_INFO::world_base_save_path_path().
Referenced by debug_menu::debug().