Cataclysm DDA: mapf Namespace Reference
mapf Namespace Reference
Classes
class format_effect
Functions
void formatted_set_simple (map *m, const point &start, const char *cstr, const format_effect< ter_id > &ter_b, const format_effect< furn_id > &furn_b)
Set terrain and furniture on the supplied map.
template<size_t N, typename ... Args>
format_effect< ter_id > ter_bind (const char(&characters)[N], Args... ids)
The functions create a mapping of characters to ids, usable with formatted_set_simple.
template<size_t N, typename ... Args>
format_effect< furn_id > furn_bind (const char(&characters)[N], Args... ids)
Function Documentation
formatted_set_simple()
void mapf::formatted_set_simple (map * m, const point & start, const char * cstr, const format_effect< ter_id > & ter_b, const format_effect< furn_id > & furn_b)
Set terrain and furniture on the supplied map.
Parameters
m The supplied map
ter_b,furn_b The lookup table for placing terrain / furniture (result of ter_bind / furn_bind).
cstr Contains the ASCII representation of the map. Each character in it represents one tile on the map. It will be looked up in ter_b and furn_b to get the terrain/ furniture to place there (if that lookup returns a null id, nothing is set on the map). A newline character continues on the next line (resets x to startx and increments y).
start Coordinates in the map where to start drawing cstr.
Definition at line 14 of file mapgenformat.cpp.
 {
     const char *p = cstr;
     point p2( start );
     while( *p != 0 ) {
         if( *p == '\n' ) {
             p2.y++;
             p2.x = start.x;
         } else {
             const ter_id ter = ter_b.translate( *p );
             const furn_id furn = furn_b.translate( *p );
             if( ter != ter_str_id::NULL_ID() ) {
                 m->ter_set( p2, ter );
             }
             if( furn != furn_str_id::NULL_ID() ) {
                 if( furn == furn_f_toilet ) {
                     m->place_toilet( tripoint_bub_ms( p2.x, p2.y, m->get_abs_sub().z() ) );
                 } else {
                     m->furn_set( p2, furn );
                 }
             }
             p2.x++;
         }
         p++;
     }
 }
References furn_f_toilet, map::furn_set(), map::get_abs_sub(), string_id< furn_t >::NULL_ID(), string_id< ter_t >::NULL_ID(), map::place_toilet(), map::ter_set(), mapf::format_effect< ID >::translate(), point::x, point::y, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by mapgen_subway(), and science_room().
furn_bind()
template<size_t N, typename ... Args> format_effect<furn_id> mapf::furn_bind (const char(&) characters[N], Args... ids) inline
Definition at line 78 of file mapgenformat.h.
 {
     // Note to self: N contains the 0-char at the end of a string literal!
     static_assert( N % 2 == 0, "list of characters to bind to must be odd, e.g. \"a b c\"" );
     static_assert( N / 2 == sizeof...( Args ),
                    "list of characters to bind to must match the size of the remaining arguments" );
     return format_effect<furn_id>( characters, { std::forward<Args>( ids )... } );
 }
Referenced by mapgen_subway(), and science_room().
ter_bind()
template<size_t N, typename ... Args> format_effect<ter_id> mapf::ter_bind (const char(&) characters[N], Args... ids) inline
The functions create a mapping of characters to ids, usable with formatted_set_simple.
The first parameter must a string literal, containing the mapped characters. Only every second character of it is mapped: "a b c" maps a to the first id, b to the second and c to the third id. The further parameters form an array of suitable size with ids to map to.
ter_bind("a", t_dirt);
ter_bind("a b", t_dirt, t_wall);
// This does not work (t_wall is not mapped to any character):
ter_bind("a", t_dirt, t_wall);
// This does not work (character b is not mapped to any id):
ter_bind("a b", t_dirt);
Definition at line 67 of file mapgenformat.h.
 {
     // Note to self: N contains the 0-char at the end of a string literal!
     static_assert( N % 2 == 0, "list of characters to bind to must be odd, e.g. \"a b c\"" );
     static_assert( N / 2 == sizeof...( Args ),
                    "list of characters to bind to must match the size of the remaining arguments" );
     return format_effect<ter_id>( characters, { std::forward<Args>( ids )... } );
 }
Referenced by mapgen_subway(), and science_room().