Cataclysm DDA: vehicles Namespace Reference
vehicles Namespace Reference
Namespaces
parts
Functions
void load_prototype (const JsonObject &jo, const std::string &src)
void reset_prototypes ()
void finalize_prototypes ()
Works through cached vehicle definitions and creates vehicle objects from them.
const std::vector< vehicle_prototype > & get_all_prototypes ()
Variables
constexpr char variant_separator = '#'
constexpr double rolling_constant_to_variable = 33.33
constexpr float vmiph_per_tile = 400.0f
constexpr units::angle steer_increment = 15_degrees
Function Documentation
finalize_prototypes()
void vehicles::finalize_prototypes ()
Works through cached vehicle definitions and creates vehicle objects from them.
Definition at line 1562 of file veh_type.cpp.
 {
     vehicle_prototype_factory.finalize();
     for( const vehicle_prototype &const_proto : vehicles::get_all_prototypes() ) {
         vehicle_prototype &proto = const_cast<vehicle_prototype &>( const_proto );
         std::unordered_set<point> cargo_spots;
         // Calling the constructor with empty vproto_id as parameter
         // makes constructor bypass copying the (non-existing) blueprint.
         proto.blueprint = make_shared_fast<vehicle>( vproto_id() );
         vehicle &blueprint = *proto.blueprint;
         blueprint.type = proto.id;
         blueprint.name = proto.name.translated();
         blueprint.suspend_refresh();
         for( vehicle_prototype::part_def &pt : proto.parts ) {
             if( const vpart_migration *migration = vpart_migration::find_migration( pt.part ) ) {
                 debugmsg( "veh prototype '%s' needs fixing, part '%s' is migrated to '%s'",
                           proto.name, pt.part.str(), migration->part_id_new.str() );
                 pt.part = migration->part_id_new;
             }
             if( !pt.part.is_valid() ) {
                 debugmsg( "unknown vehicle part %s in %s", pt.part.c_str(), proto.id.str() );
                 continue;
             }
             const int part_idx = blueprint.install_part( pt.pos, pt.part );
             if( part_idx < 0 ) {
                 debugmsg( "init_vehicles: '%s' part '%s'(%d) can't be installed to %d,%d",
                           blueprint.name, pt.part.c_str(),
                           blueprint.part_count(), pt.pos.x, pt.pos.y );
             } else {
                 vehicle_part &vp = blueprint.part( part_idx );
                 const vpart_info &vpi = vp.info();
                 // try variant, if variant invalid default to first one
                 cata_assert( !vpi.variants.empty() );
                 const auto variant_it = vpi.variants.find( pt.variant );
                 if( variant_it == vpi.variants.end() ) {
                     vp.variant = vpi.variants.begin()->first;
                     if( !pt.variant.empty() ) { // only debugmsg if trying to select non-default variant
                         debugmsg( "veh prototype '%s' uses invalid variant '%s' for "
                                   "part '%s' defaulting to '%s'",
                                   proto.name, pt.variant, vp.info().id.str(), vp.variant );
                     }
                 } else {
                     vp.variant = pt.variant;
                 }
                 for( const itype_id &it : pt.tools ) {
                     blueprint.get_tools( vp ).emplace_back( it, calendar::turn );
                 }
                 if( pt.fuel ) {
                     vp.ammo_set( pt.fuel,
                                  pt.fuel->ammo ? vp.ammo_capacity( pt.fuel->ammo->type ) : vp.item_capacity( pt.fuel ) );
                 }
             }
             std::vector<itype_id> migrated;
             for( auto it = pt.ammo_types.begin(); it != pt.ammo_types.end(); ) {
                 if( item_controller->migrate_id( *it ) != *it ) {
                     migrated.push_back( item_controller->migrate_id( *it ) );
                     it = pt.ammo_types.erase( it );
                 } else {
                     ++it;
                 }
             }
             for( const itype_id &migrant : migrated ) {
                 pt.ammo_types.insert( migrant );
             }
             const itype *base = item::find_type( pt.part->base_item );
             if( !base->gun ) {
                 if( pt.with_ammo ) {
                     debugmsg( "init_vehicles: non-turret %s with ammo in %s", pt.part.c_str(),
                               proto.id.str() );
                 }
                 if( !pt.ammo_types.empty() ) {
                     debugmsg( "init_vehicles: non-turret %s with ammo_types in %s",
                               pt.part.c_str(), proto.id.str() );
                 }
                 if( pt.ammo_qty.first > 0 || pt.ammo_qty.second > 0 ) {
                     debugmsg( "init_vehicles: non-turret %s with ammo_qty in %s",
                               pt.part.c_str(), proto.id.str() );
                 }
             } else {
                 for( const auto &e : pt.ammo_types ) {
                     const itype *ammo = item::find_type( e );
                     if( !ammo->ammo || !base->gun->ammo.count( ammo->ammo->type ) ) {
                         debugmsg( "init_vehicles: turret %s has invalid ammo_type %s in %s",
                                   pt.part.c_str(), e.c_str(), proto.id.str() );
                     }
                 }
                 if( pt.ammo_types.empty() && !base->gun->ammo.empty() ) {
                     pt.ammo_types.insert( ammotype( *base->gun->ammo.begin() )->default_ammotype() );
                 }
             }
             if( item( &*base ).can_contain( item( pt.fuel ) ).success() || base->magazine ) {
                 if( !item::type_is_defined( pt.fuel ) ) {
                     debugmsg( "init_vehicles: tank %s specified invalid fuel in %s",
                               pt.part.c_str(), proto.id.str() );
                 }
             } else {
                 if( !pt.fuel.is_null() ) {
                     debugmsg( "init_vehicles: non-fuel store part %s with fuel in %s",
                               pt.part.c_str(), proto.id.str() );
                 }
             }
             if( pt.part.obj().has_flag( VPFLAG_CARGO ) ) {
                 cargo_spots.insert( pt.pos );
             }
         }
         blueprint.enable_refresh();
         for( vehicle_item_spawn &i : proto.item_spawns ) {
             if( cargo_spots.count( i.pos ) == 0 ) {
                 debugmsg( "Invalid spawn location (no CARGO vpart) in %s (%d, %d): %d%%",
                           proto.name, i.pos.x, i.pos.y, i.chance );
             }
             for( auto &j : i.item_ids ) {
                 if( !item::type_is_defined( j ) ) {
                     debugmsg( "unknown item %s in spawn list of %s", j.c_str(), proto.id.str() );
                 }
             }
             for( auto &j : i.item_groups ) {
                 if( !item_group::group_is_defined( j ) ) {
                     debugmsg( "unknown item group %s in spawn list of %s", j.c_str(), proto.id.str() );
                 }
             }
         }
     }
 }
References itype::ammo, vehicle_part::ammo_capacity(), vehicle_prototype::part_def::ammo_qty, vehicle_part::ammo_set(), vehicle_prototype::part_def::ammo_types, vpart_info::base_item, vehicle_prototype::blueprint, string_id< T >::c_str(), cata_assert, vehicle_item_spawn::chance, debugmsg, ammunition_type::default_ammotype(), vehicle::enable_refresh(), vpart_migration::find_migration(), item::find_type(), vehicle_prototype::part_def::fuel, get_all_prototypes(), vehicle::get_tools(), item_group::group_is_defined(), itype::gun, vpart_info::has_flag(), vpart_info::id, vehicle_prototype::id, vehicle_part::info(), vehicle::install_part(), string_id< T >::is_null(), string_id< T >::is_valid(), item, vehicle_part::item_capacity(), item_controller, vehicle_item_spawn::item_groups, vehicle_item_spawn::item_ids, vehicle_prototype::item_spawns, itype::magazine, vehicle_prototype::name, vehicle::name, string_id< T >::obj(), vehicle_prototype::part_def::part, vehicle::part(), vehicle::part_count(), vehicle_prototype::parts, vehicle_item_spawn::pos, vehicle_prototype::part_def::pos, string_id< T >::str(), vehicle::suspend_refresh(), vehicle_prototype::part_def::tools, translation::translated(), calendar::turn, vehicle::type, item::type_is_defined(), vehicle_prototype::part_def::variant, vehicle_part::variant, vpart_info::variants, anonymous_namespace{veh_type.cpp}::vehicle_prototype_factory, VPFLAG_CARGO, vehicle_prototype::part_def::with_ammo, point::x, and point::y.
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all_prototypes()
const std::vector< vehicle_prototype > & vehicles::get_all_prototypes ()
Definition at line 1248 of file veh_type.cpp.
 {
     return vehicle_prototype_factory.get_all();
 }
References anonymous_namespace{veh_type.cpp}::vehicle_prototype_factory.
Referenced by debug_menu::debug_menu_spawn_vehicle(), Item_factory::finalize_item_blacklist(), and finalize_prototypes().
load_prototype()
void vehicles::load_prototype (const JsonObject & jo, const std::string & src)
Definition at line 1243 of file veh_type.cpp.
 {
     vehicle_prototype_factory.load( jo, src );
 }
References anonymous_namespace{veh_type.cpp}::vehicle_prototype_factory.
Referenced by DynamicDataLoader::initialize().
reset_prototypes()
void vehicles::reset_prototypes ()
Definition at line 1253 of file veh_type.cpp.
 {
     vehicle_prototype_factory.reset();
 }
References anonymous_namespace{veh_type.cpp}::vehicle_prototype_factory.
Referenced by DynamicDataLoader::unload_data().
Variable Documentation
rolling_constant_to_variable
constexpr double vehicles::rolling_constant_to_variable = 33.33 constexpr
Definition at line 80 of file vehicle.h.
Referenced by vehicle::max_ground_velocity(), vehicle::safe_ground_velocity(), and vehicle::slowdown().
steer_increment
constexpr units::angle vehicles::steer_increment = 15_degrees constexpr
Definition at line 83 of file vehicle.h.
Referenced by vehicle::act_on_map(), vehicle::immediate_path(), vehicle::pldrive(), vehicle::selfdrive(), map::shake_vehicle(), and vehicle::turn().
variant_separator
constexpr char vehicles::variant_separator = '#' constexpr
Definition at line 38 of file veh_type.h.
Referenced by vpart_info::check(), vpart_display::get_tileset_id(), and get_vpart_str_variant().
vmiph_per_tile
constexpr float vehicles::vmiph_per_tile = 400.0f constexpr
Definition at line 81 of file vehicle.h.
Referenced by vehicle::act_on_map(), game::calc_driving_offset(), and vehicle::handling_difficulty().