Cataclysm DDA: anonymous_namespace{json_loader.cpp} Namespace Reference
anonymous_namespace{json_loader.cpp} Namespace Reference
Functions
flexbuffer_cache & base_cache ()
flexbuffer_cache & config_cache ()
flexbuffer_cache & data_cache ()
flexbuffer_cache & memorial_cache ()
flexbuffer_cache & user_cache ()
flexbuffer_cache & cache_for_save (const cata_path &path)
flexbuffer_cache & cache_for_lexically_normal_path (const cata_path &path)
std::optional< JsonValue > from_path_at_offset_opt_impl (const cata_path &source_file, size_t offset)
Variables
std::unordered_map< std::string, std::unique_ptr< flexbuffer_cache > > save_caches
Function Documentation
base_cache()
flexbuffer_cache& anonymous_namespace{json_loader.cpp}::base_cache ()
Definition at line 15 of file json_loader.cpp.
 {
     static flexbuffer_cache cache{ fs::u8path( PATH_INFO::base_path() ) / fs::u8path( "cache" ), fs::u8path( PATH_INFO::base_path() ) };
     return cache;
 }
References PATH_INFO::base_path().
Referenced by cache_for_lexically_normal_path().
cache_for_lexically_normal_path()
flexbuffer_cache& anonymous_namespace{json_loader.cpp}::cache_for_lexically_normal_path (const cata_path & path)
Definition at line 71 of file json_loader.cpp.
 {
     switch( path.get_logical_root() ) {
         case cata_path::root_path::base:
             return base_cache();
         case cata_path::root_path::config:
             return config_cache();
         case cata_path::root_path::data:
             return data_cache();
         case cata_path::root_path::memorial:
             return memorial_cache();
         case cata_path::root_path::save:
             // Saves we store data one per save.
             // But also... per character per save.
             return cache_for_save( path );
         case cata_path::root_path::user:
             return user_cache();
         case cata_path::root_path::unknown:
         default:
             cata_fatal( "Cannot create cache for unknown path %s",
                         path.generic_u8string() );
     }
 }
References cata_path::base, base_cache(), cache_for_save(), cata_fatal, cata_path::config, config_cache(), cata_path::data, data_cache(), cata_path::generic_u8string(), cata_path::get_logical_root(), cata_path::memorial, memorial_cache(), cata_path::save, cata_path::unknown, cata_path::user, and user_cache().
Referenced by from_path_at_offset_opt_impl().
cache_for_save()
flexbuffer_cache& anonymous_namespace{json_loader.cpp}::cache_for_save (const cata_path & path)
Definition at line 49 of file json_loader.cpp.
 {
     // Assume lexically normal path
     auto path_it = path.get_relative_path().begin();
     // First path element is the world name
     fs::path worldname_path = *path_it;
     std::string worldname_str = worldname_path.u8string();
     ++path_it;
     // Next element is either a file, a character folder, or the maps folder
     std::string folder_or_file = path_it->u8string();
     ++path_it;
     auto it = save_caches.find( worldname_str );
     if( it == save_caches.end() ) {
         it = save_caches.emplace( worldname_str,
                                   std::make_unique<flexbuffer_cache>( fs::path(),
                                           fs::u8path( PATH_INFO::savedir() ) / worldname_path ) ).first;
     }
     return *it->second;
 }
References cata_path::get_relative_path(), save_caches, and PATH_INFO::savedir().
Referenced by cache_for_lexically_normal_path().
config_cache()
flexbuffer_cache& anonymous_namespace{json_loader.cpp}::config_cache ()
Definition at line 21 of file json_loader.cpp.
 {
     static flexbuffer_cache cache{ fs::u8path( PATH_INFO::config_dir() ) / fs::u8path( "cache" ), fs::u8path( PATH_INFO::config_dir() ) };
     return cache;
 }
References PATH_INFO::config_dir().
Referenced by cache_for_lexically_normal_path().
data_cache()
flexbuffer_cache& anonymous_namespace{json_loader.cpp}::data_cache ()
Definition at line 27 of file json_loader.cpp.
 {
     static flexbuffer_cache cache{ fs::u8path( PATH_INFO::datadir() ) / fs::u8path( "cache" ), fs::u8path( PATH_INFO::datadir() ) };
     return cache;
 }
References PATH_INFO::datadir().
Referenced by cache_for_lexically_normal_path().
from_path_at_offset_opt_impl()
std::optional<JsonValue> anonymous_namespace{json_loader.cpp}::from_path_at_offset_opt_impl (const cata_path & source_file, size_t offset)
Definition at line 96 of file json_loader.cpp.
 {
     cata_path lexically_normal_path = source_file.lexically_normal();
     std::shared_ptr<parsed_flexbuffer> buffer;
     if( lexically_normal_path.get_logical_root() != cata_path::root_path::unknown ) {
         flexbuffer_cache &cache = cache_for_lexically_normal_path( lexically_normal_path );
         buffer = cache.parse_and_cache(
                      lexically_normal_path.get_unrelative_path(), offset );
     } else {
         buffer = flexbuffer_cache::parse( lexically_normal_path.get_unrelative_path(), offset );
     }
     if( !buffer ) {
         return std::nullopt;
     }
     flexbuffers::Reference buffer_root = flexbuffer_root_from_storage( buffer->get_storage() );
     return JsonValue( std::move( buffer ), buffer_root, nullptr, 0 );
 }
References cache_for_lexically_normal_path(), flexbuffer_root_from_storage(), cata_path::get_logical_root(), cata_path::get_unrelative_path(), cata_path::lexically_normal(), flexbuffer_cache::parse(), flexbuffer_cache::parse_and_cache(), and cata_path::unknown.
Referenced by json_loader::from_path_at_offset(), and json_loader::from_path_at_offset_opt().
memorial_cache()
flexbuffer_cache& anonymous_namespace{json_loader.cpp}::memorial_cache ()
Definition at line 33 of file json_loader.cpp.
 {
     static flexbuffer_cache cache{ fs::u8path( PATH_INFO::memorialdir() ) / fs::u8path( "cache" ), fs::u8path( PATH_INFO::memorialdir() ) };
     return cache;
 }
References PATH_INFO::memorialdir().
Referenced by cache_for_lexically_normal_path().
user_cache()
flexbuffer_cache& anonymous_namespace{json_loader.cpp}::user_cache ()
Definition at line 39 of file json_loader.cpp.
 {
     static flexbuffer_cache cache{ fs::u8path( PATH_INFO::user_dir() ) / fs::u8path( "cache" ), fs::u8path( PATH_INFO::user_dir() ) };
     return cache;
 }
References PATH_INFO::user_dir().
Referenced by cache_for_lexically_normal_path().
Variable Documentation
save_caches
std::unordered_map<std::string, std::unique_ptr<flexbuffer_cache> > anonymous_namespace{json_loader.cpp}::save_caches
Definition at line 45 of file json_loader.cpp.
Referenced by cache_for_save().