Cataclysm DDA: anonymous_namespace{start_location.cpp} Namespace Reference
anonymous_namespace{start_location.cpp} Namespace Reference
Variables
generic_factory< start_location > all_start_locations ("start locations")
Variable Documentation
all_start_locations
generic_factory<start_location> anonymous_namespace{start_location.cpp}::all_start_locations("start locations") ("start locations")
Referenced by start_locations::check_consistency(), start_locations::finalize_all(), start_locations::get_all(), start_locations::load(), and start_locations::reset().