Cataclysm DDA: om_lines Namespace Reference
om_lines Namespace Reference
Classes
struct type
Functions
static constexpr size_t rotate (size_t line, om_direction::type dir)
static constexpr size_t set_segment (size_t line, om_direction::type dir)
static constexpr bool has_segment (size_t line, om_direction::type dir)
static constexpr bool is_straight (size_t line)
static size_t from_dir (om_direction::type dir)
Variables
static const std::array< std::string, 5 > mapgen_suffixes
static const std::array< type, 1+om_direction::bits > all
static const size_t size = all.size()
static const size_t invalid = 0
Function Documentation
from_dir()
static size_t om_lines::from_dir (om_direction::type dir) static
Definition at line 283 of file overmap.cpp.
 {
     switch( dir ) {
         case om_direction::type::north:
         case om_direction::type::south:
             return 5;  // ns;
         case om_direction::type::east:
         case om_direction::type::west:
             return 10; // ew
         case om_direction::type::invalid:
         case om_direction::type::last:
             debugmsg( "Can't retrieve a line from the invalid direction." );
     }
     return 0;
 }
References debugmsg, om_direction::east, om_direction::invalid, om_direction::last, om_direction::north, om_direction::south, and om_direction::west.
has_segment()
static constexpr bool om_lines::has_segment (size_t line, om_direction::type dir) static constexpr
Definition at line 265 of file overmap.cpp.
 {
     if( dir == om_direction::type::invalid ) {
         return false;
     }
     return static_cast<bool>( line & 1 << static_cast<int>( dir ) );
 }
References om_direction::invalid, and line().
Referenced by overmap::build_connection(), and oter_t::has_connection().
is_straight()
static constexpr bool om_lines::is_straight (size_t line) static constexpr
Definition at line 273 of file overmap.cpp.
 {
     return line == 1
            || line == 2
            || line == 4
            || line == 5
            || line == 8
            || line == 10;
 }
References line().
Referenced by overmap::build_connection().
rotate()
static constexpr size_t om_lines::rotate (size_t line, om_direction::type dir) static constexpr
Definition at line 247 of file overmap.cpp.
 {
     if( dir == om_direction::type::invalid ) {
         return line;
     }
     // Bitwise rotation to the left.
     return ( ( line << static_cast<size_t>( dir ) ) |
              ( line >> ( om_direction::size - static_cast<size_t>( dir ) ) ) ) & om_direction::bits;
 }
References om_direction::bits, om_direction::invalid, line(), and om_direction::size.
Referenced by oter_t::get_rotated().
set_segment()
static constexpr size_t om_lines::set_segment (size_t line, om_direction::type dir) static constexpr
Definition at line 257 of file overmap.cpp.
 {
     if( dir == om_direction::type::invalid ) {
         return line;
     }
     return line | 1 << static_cast<int>( dir );
 }
References om_direction::invalid, and line().
Referenced by overmap::build_connection().
Variable Documentation
all
const std::array< type, 1 + om_direction::bits > om_lines::all static
Initial value:
= {{
        { UTF8_getch( LINE_XXXX_S ), 4, unconnected,  0, "_isolated"  },
        { UTF8_getch( LINE_XOXO_S ), 2, end_piece,    2, "_end_south" },
        { UTF8_getch( LINE_OXOX_S ), 2, end_piece,    1, "_end_west"  },
        { UTF8_getch( LINE_XXOO_S ), 1, corner,       1, "_ne"        },
        { UTF8_getch( LINE_XOXO_S ), 2, end_piece,    0, "_end_north" },
        { UTF8_getch( LINE_XOXO_S ), 0, edge,         0, "_ns"        },
        { UTF8_getch( LINE_OXXO_S ), 1, corner,       0, "_es"        },
        { UTF8_getch( LINE_XXXO_S ), 3, t_connection, 1, "_nes"       },
        { UTF8_getch( LINE_OXOX_S ), 2, end_piece,    3, "_end_east"  },
        { UTF8_getch( LINE_XOOX_S ), 1, corner,       2, "_wn"        },
        { UTF8_getch( LINE_OXOX_S ), 0, edge,         1, "_ew"        },
        { UTF8_getch( LINE_XXOX_S ), 3, t_connection, 2, "_new"       },
        { UTF8_getch( LINE_OOXX_S ), 1, corner,       3, "_sw"        },
        { UTF8_getch( LINE_XOXX_S ), 3, t_connection, 3, "_nsw"       },
        { UTF8_getch( LINE_OXXX_S ), 3, t_connection, 0, "_esw"       },
        { UTF8_getch( LINE_XXXX_S ), 4, center,       0, "_nesw"      }
    }
}
Definition at line 224 of file overmap.cpp.
Referenced by oter_t::get_mapgen_id(), oter_t::get_rotation(), and oter_t::get_rotation_and_subtile().
invalid
const size_t om_lines::invalid = 0 static
Definition at line 245 of file overmap.cpp.
Referenced by overmap::build_connection(), and fixed_overmap_special_data::check().
mapgen_suffixes
const std::array<std::string, 5> om_lines::mapgen_suffixes static
Initial value:
= {{
        "_straight", "_curved", "_end", "_tee", "_four_way"
    }
}
Definition at line 219 of file overmap.cpp.
Referenced by oter_t::get_mapgen_id(), and oter_type_t::load().
size
const size_t om_lines::size = all.size() static
Definition at line 244 of file overmap.cpp.
Referenced by oter_type_t::finalize(), overmap::generate_sub(), oter_type_t::get_linear(), om_direction::opposite(), overmap::place_cities(), om_direction::random(), om_direction::turn_left(), and om_direction::turn_right().