Cataclysm DDA: details Namespace Reference
details Namespace Reference
Functions
template<typename T , typename Set >
bool assign_set (const JsonObject &jo, const std::string_view name, Set &val)
Function Documentation
assign_set()
template<typename T , typename Set > bool details::assign_set (const JsonObject & jo, const std::string_view name, Set & val)
Definition at line 156 of file assign.h.
 {
     JsonObject add = jo.get_object( "extend" );
     add.allow_omitted_members();
     JsonObject del = jo.get_object( "delete" );
     del.allow_omitted_members();
     if( jo.has_string( name ) || jo.has_array( name ) ) {
         val = jo.get_tags<T, Set>( name );
         if( add.has_member( name ) || del.has_member( name ) ) {
             // ill-formed to (re)define a value and then extend/delete within same definition
             jo.throw_error_at( name, "multiple assignment of value" );
         }
         return true;
     }
     bool res = false;
     if( add.has_string( name ) || add.has_array( name ) ) {
         auto tags = add.get_tags<T>( name );
         val.insert( tags.begin(), tags.end() );
         res = true;
     }
     if( del.has_string( name ) || del.has_array( name ) ) {
         for( const auto &e : del.get_tags<T>( name ) ) {
             val.erase( e );
         }
         res = true;
     }
     return res;
 }
References JsonObject::allow_omitted_members(), JsonObject::get_object(), JsonObject::get_tags(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_string(), om_direction::name(), anonymous_namespace{item_tname.cpp}::tags(), and JsonObject::throw_error_at().