Cataclysm DDA: anonymous_namespace{overmap_location.cpp} Namespace Reference
anonymous_namespace{overmap_location.cpp} Namespace Reference
Variables
generic_factory< overmap_location > locations ("overmap location")
Variable Documentation
locations
generic_factory<overmap_location> anonymous_namespace{overmap_location.cpp}::locations("overmap location") ("overmap location")
Referenced by inventory_column::add_entry(), inventory_selector::add_entry(), debug_menu::character_edit_menu(), overmap_locations::check_consistency(), creature_select_menu(), game::display_visibility(), overmap_locations::finalize(), veh_menu::get_locations(), inventory_selector::highlight_one_of(), is_amongst_locations(), overmap_connection::subtype::load(), overmap_locations::load(), npc_select_menu(), pick_follower(), pickveh(), veh_menu::query(), overmap_locations::reset(), iuse::robotcontrol(), overmap_ui::search(), inventory_column::set_collapsed(), map::spawn_monsters_submap_group(), vehicle::turrets_set_mode(), vehicle::turrets_set_targeting(), Character::volume_capacity_with_tweaks(), Character::volume_carried_with_tweaks(), and Character::weight_carried_with_tweaks().