Cataclysm DDA: sm_rack Namespace Reference
sm_rack Namespace Reference
Variables
static const int MIN_CHARCOAL = 1200
static const int CHARCOAL_PER_LITER = 600
static const units::volume MAX_FOOD_VOLUME = units::from_liter(20)
static const units::volume MAX_FOOD_VOLUME_PORTABLE = units::from_liter(15)
Variable Documentation
CHARCOAL_PER_LITER
const int sm_rack::CHARCOAL_PER_LITER = 600 static
Definition at line 6081 of file iexamine.cpp.
Referenced by get_charcoal_charges(), and iexamine::smoker_options().
MAX_FOOD_VOLUME
const units::volume sm_rack::MAX_FOOD_VOLUME = units::from_liter(20) static
Definition at line 6082 of file iexamine.cpp.
Referenced by mill_activate(), iexamine::quern_examine(), smoker_activate(), smoker_load_food(), and iexamine::smoker_options().
MAX_FOOD_VOLUME_PORTABLE
const units::volume sm_rack::MAX_FOOD_VOLUME_PORTABLE = units::from_liter(15) static
Definition at line 6083 of file iexamine.cpp.
Referenced by smoker_activate(), smoker_load_food(), and iexamine::smoker_options().
MIN_CHARCOAL
const int sm_rack::MIN_CHARCOAL = 1200 static
Definition at line 6080 of file iexamine.cpp.
Referenced by get_charcoal_charges(), and iexamine::smoker_options().