Cataclysm DDA: construction_categories Namespace Reference
construction_categories Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void reset ()
const std::vector< construction_category > & get_all ()
Function Documentation
get_all()
const std::vector< construction_category > & construction_categories::get_all ()
Definition at line 76 of file construction_category.cpp.
 {
     return all_construction_categories.get_all();
 }
References anonymous_namespace{construction_category.cpp}::all_construction_categories.
Referenced by construction_menu(), and finalize_constructions().
load()
void construction_categories::load (const JsonObject & jo, const std::string & src)
Definition at line 66 of file construction_category.cpp.
 {
     all_construction_categories.load( jo, src );
 }
References anonymous_namespace{construction_category.cpp}::all_construction_categories.
Referenced by DynamicDataLoader::initialize().
reset()
void construction_categories::reset ()
Definition at line 71 of file construction_category.cpp.
 {
     all_construction_categories.reset();
 }
References anonymous_namespace{construction_category.cpp}::all_construction_categories.
Referenced by DynamicDataLoader::unload_data().