Cataclysm DDA: VehicleSpawnFunction Namespace Reference
VehicleSpawnFunction Namespace Reference
Functions
static void builtin_no_vehicles (map &, const std::string_view)
static void builtin_parkinglot (map &m, const std::string_view)
Function Documentation
builtin_no_vehicles()
static void VehicleSpawnFunction::builtin_no_vehicles (map & , const std::string_view) static
Definition at line 227 of file vehicle_group.cpp.
 {}
builtin_parkinglot()
static void VehicleSpawnFunction::builtin_parkinglot (map & m, const std::string_view) static
Definition at line 230 of file vehicle_group.cpp.
 {
     for( int v = 0; v < rng( 1, 4 ); v++ ) {
         tripoint pos_p;
         pos_p.x = rng( 0, 1 ) * 15 + rng( 4, 5 );
         pos_p.y = rng( 0, 4 ) * 4 + rng( 2, 4 );
         pos_p.z = m.get_abs_sub().z();
         if( !m.veh_at( pos_p ) ) {
             units::angle facing;
             if( one_in( 10 ) ) {
                 facing = random_direction();
             } else {
                 facing = one_in( 2 ) ? 0_degrees : 180_degrees;
             }
             m.add_vehicle( VehicleGroup_parkinglot->pick(), pos_p, facing, -1, -1 );
         }
     }
 }
References map::add_vehicle(), map::get_abs_sub(), one_in(), VehicleGroup::pick(), random_direction(), rng(), map::veh_at(), VehicleGroup_parkinglot, tripoint::x, tripoint::y, coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and tripoint::z.