Cataclysm DDA: item_group Namespace Reference
item_group Namespace Reference
Typedefs
using ItemList = std::vector< item >
Functions
item item_from (const item_group_id &group_id, const time_point &birthday)
Returns a random item from the item group, handles packaged food by putting it into its container and returning the container item.
item item_from (const item_group_id &group_id)
Same as above but with implicit birthday at turn 0.
ItemList items_from (const item_group_id &group_id, const time_point &birthday, spawn_flags flags=spawn_flags::none)
Create items from the given group.
ItemList items_from (const item_group_id &group_id)
Same as above but with implicit birthday at turn 0.
bool group_contains_item (const item_group_id &group_id, const itype_id &)
Check whether a specific item group contains a specific item type.
std::set< const itype * > every_possible_item_from (const item_group_id &group_id)
Return every item type that can possibly be spawned by the item group.
bool group_is_defined (const item_group_id &group_id)
Check whether an item group of the given id exists.
void debug_spawn ()
Shows an menu to debug the item groups.
void load_item_group (const JsonObject &jsobj, const item_group_id &group_id, const std::string &subtype)
See Item_factory::load_item_group.
item_group_id load_item_group (const JsonValue &value, const std::string &default_subtype, const std::string &context)
Get an item group id and (optionally) load an inlined item group.
Typedef Documentation
ItemList
using item_group::ItemList = typedef std::vector<item>
Definition at line 50 of file item_group.h.
Function Documentation
debug_spawn()
void item_group::debug_spawn ()
Shows an menu to debug the item groups.
Definition at line 5356 of file item_factory.cpp.
 {
     std::vector<item_group_id> groups = item_controller->get_all_group_names();
     uilist menu;
     menu.text = _( "Test which group?" );
     for( size_t i = 0; i < groups.size(); i++ ) {
         menu.entries.emplace_back( static_cast<int>( i ), true, -2, groups[i].str() );
     }
     while( true ) {
         menu.query();
         const int index = menu.ret;
         if( index >= static_cast<int>( groups.size() ) || index < 0 ) {
             break;
         }
         // Spawn items from the group 100 times
         std::map<std::string, int> itemnames;
         for( size_t a = 0; a < 100; a++ ) {
             const ItemList items = items_from( groups[index], calendar::turn );
             for( const item &it : items ) {
                 itemnames[it.display_name()]++;
             }
         }
         // Invert the map to get sorting!
         std::multimap<int, std::string> itemnames2;
         for( const auto &e : itemnames ) {
             itemnames2.insert( std::pair<int, std::string>( e.second, e.first ) );
         }
         uilist menu2;
         menu2.text = _( "Result of 100 spawns:" );
         for( const auto &e : itemnames2 ) {
             menu2.entries.emplace_back( static_cast<int>( menu2.entries.size() ), true, -2,
                                         string_format( _( "%d x %s" ), e.first, e.second ) );
         }
         menu2.query();
     }
 }
References _, a, uilist::entries, item_controller, items_from(), uilist::query(), uilist::ret, string_format(), uilist::text, and calendar::turn.
Referenced by debug_menu::debug().
every_possible_item_from()
std::set< const itype * > item_group::every_possible_item_from (const item_group_id & group_id)
Return every item type that can possibly be spawned by the item group.
Definition at line 1025 of file item_group.cpp.
 {
     Item_spawn_data *group = item_controller->get_group( group_id );
     if( group == nullptr ) {
         return {};
     }
     return group->every_item();
 }
References item_controller.
Referenced by jmapgen_sealed_item::check(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach().
group_contains_item()
bool item_group::group_contains_item (const item_group_id & group_id, const itype_id & type_id)
Check whether a specific item group contains a specific item type.
Definition at line 1016 of file item_group.cpp.
 {
     const Item_spawn_data *group = item_controller->get_group( group_id );
     if( group == nullptr ) {
         return false;
     }
     return group->has_item( type_id );
 }
References item_controller.
Referenced by zone_manager::custom_loot_has(), mission::get_all_item_group_matches(), recipe::in_byproducts(), icg_entry::matches(), and npc::wants_to_sell().
group_is_defined()
bool item_group::group_is_defined (const item_group_id & group_id)
Check whether an item group of the given id exists.
You may use this to either choose an alternative group or check the json definitions for consistency (spawn data in json that refers to a non-existing group is broken), or just alert the player.
Definition at line 1011 of file item_group.cpp.
 {
     return item_controller->get_group( group_id ) != nullptr;
 }
References item_controller.
Referenced by vpart_info::check(), check_bash_items(), harvest_list::check_consistency(), npc_class::check_consistency(), json_item_substitution::check_consistency(), Single_item_creator::check_consistency(), check_decon_items(), profession::check_definition(), MonsterGenerator::check_monster_definitions(), vehicles::finalize_prototypes(), get_unique_group_id(), jmapgen_loot::jmapgen_loot(), map::place_items(), starting_clothes(), starting_inv(), and npc::starting_weapon().
item_from() [1/2]
item item_group::item_from (const item_group_id & group_id)
Same as above but with implicit birthday at turn 0.
Definition at line 1006 of file item_group.cpp.
 {
     return item_from( group_id, calendar::turn_zero );
 }
References item_from(), and calendar::turn_zero.
item_from() [2/2]
item item_group::item_from (const item_group_id & group_id, const time_point & birthday)
Returns a random item from the item group, handles packaged food by putting it into its container and returning the container item.
Note that this may return a null-item, if the group does not exist, is empty or did not create an item this time. You have to check this with item::is_null.
Definition at line 997 of file item_group.cpp.
 {
     const Item_spawn_data *group = item_controller->get_group( group_id );
     if( group == nullptr ) {
         return item();
     }
     return group->create_single( birthday );
 }
References item_controller.
Referenced by talk_function::forage_return(), talk_function::hospital_raid_return(), item::item(), item_from(), random_item_from(), talk_function::scavenging_raid_return(), basecamp::search_results(), npc::shop_restock(), and npc::starting_weapon().
items_from() [1/2]
item_group::ItemList item_group::items_from (const item_group_id & group_id)
Same as above but with implicit birthday at turn 0.
Definition at line 992 of file item_group.cpp.
 {
     return items_from( group_id, calendar::turn_zero );
 }
References items_from(), and calendar::turn_zero.
items_from() [2/2]
item_group::ItemList item_group::items_from (const item_group_id & group_id, const time_point & birthday, spawn_flags flags = spawn_flags::none)
Create items from the given group.
It creates as many items as the group definition requests. For example if the group is a distribution that only contains item ids it will create a single item. If the group is a collection with several entries it can contain more than one item (or none at all). This function also creates ammo for guns, if this is requested in the item group and puts stuff into containers if that is required. The returned list may contain any number of items (or be empty), but it will never contain null-items.
Parameters
group_id The identifier of the item group. You may check its validity with group_is_defined.
birthday The birthday (item::bday) of the items created by this function.
flags The spawn flags used in spawning the items.
Definition at line 979 of file item_group.cpp.
 {
     const Item_spawn_data *group = item_controller->get_group( group_id );
     if( group == nullptr ) {
         return ItemList();
     }
     ItemList result;
     result.reserve( 20 );
     group->create( result, birthday, flags );
     return result;
 }
References item_controller.
Referenced by jmapgen_terrain::apply(), map::bash_ter_furn(), complete_construction(), create_byproducts_group(), debug_spawn(), construct::done_deconstruct(), monster::drop_items_on_death(), basecamp::gathering_description(), monster::generate_inventory(), json_item_substitution::get_bonus_items(), recipe::get_byproducts(), profession::items(), items_from(), talk_function::loot_building(), MapExtras::mx_casings(), MapExtras::mx_corpses(), om_harvest_ter(), vehicle_part::pieces_for_broken_part(), map::place_items(), vehicle::place_spawn_items(), map::put_items_from_loc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::receive_item(), npc::shop_restock(), smash(), monster::spawn_dissectables_on_death(), spell_effect::spawn_ethereal_item(), starting_clothes(), starting_inv(), and unpack_actor::use().
load_item_group() [1/2]
void item_group::load_item_group (const JsonObject & jsobj, const item_group_id & group_id, const std::string & subtype)
See Item_factory::load_item_group.
Definition at line 1034 of file item_group.cpp.
 {
     item_controller->load_item_group( jsobj, group_id, subtype );
 }
References item_controller, and subtype.
Referenced by jmapgen_item_group::jmapgen_item_group(), json_item_substitution::load(), mtype::load(), recipe::load(), vpart_info::load(), profession::load(), map_deconstruct_info::load(), map_bash_info::load(), load_construction(), and Item_factory::load_item_group().
load_item_group() [2/2]
item_group_id item_group::load_item_group (const JsonValue & value, const std::string & default_subtype, const std::string & context)
Get an item group id and (optionally) load an inlined item group.
If the value is string, it's assumed to be an item group id and it's returned directly.
If the value is a JSON object, it is loaded as item group. The group will be given a unique id (if the JSON object contains an id, it is ignored) and that id will be returned. If the JSON object does not contain a subtype, the given default is used.
If the value is a JSON array, it is loaded as item group: the default_subtype will be used as subtype of the new item group and the array is loaded like the "entries" array of a item group definition (see format of item groups).
Parameters
stream Stream to load from
default_subtype If an inlined item group is loaded this is used as the default subtype. It must be either "distribution" or "collection". See Item_group.
context A human-readable description of where this item group was defined which should be sufficient for a content developer to figure out where it is in the JSON files.
Exceptions
JsonError as usual for JSON errors, including invalid input values.
Definition at line 1057 of file item_group.cpp.
 {
     if( value.test_string() ) {
         return item_group_id( value.get_string() );
     } else if( value.test_object() ) {
         item_group_id group = get_unique_group_id();
         JsonObject jo = value.get_object();
         const std::string subtype = jo.get_string( "subtype", default_subtype );
         item_controller->load_item_group( jo, group, subtype, context );
         return group;
     } else if( value.test_array() ) {
         item_group_id group = get_unique_group_id();
         JsonArray jarr = value.get_array();
         // load_item_group needs a bool, invalid subtypes are unexpected and most likely errors
         // from the caller of this function.
         if( default_subtype != "collection" && default_subtype != "distribution" ) {
             debugmsg( "invalid subtype for item group: %s", default_subtype.c_str() );
         }
         item_controller->load_item_group( jarr, group, default_subtype == "collection", 0, 0,
                                           context );
         return group;
     }
     value.throw_error( "invalid item group, must be string (group id) or object/array (the group data)" );
 }
References context, debugmsg, JsonValue::get_array(), JsonValue::get_object(), JsonValue::get_string(), JsonObject::get_string(), get_unique_group_id(), item_controller, subtype, JsonValue::test_array(), JsonValue::test_object(), JsonValue::test_string(), and JsonValue::throw_error().