Cataclysm DDA: cata_event_dispatch Namespace Reference
cata_event_dispatch Namespace Reference
Functions
void avatar_moves (const tripoint &old_abs_pos, const avatar &u, const map &m)
Function Documentation
avatar_moves()
void cata_event_dispatch::avatar_moves (const tripoint & old_abs_pos, const avatar & u, const map & m)
Definition at line 13758 of file game.cpp.
 {
     const tripoint new_pos = u.pos();
     const tripoint new_abs_pos = m.getabs( new_pos );
     mtype_id mount_type;
     if( u.is_mounted() ) {
         mount_type = u.mounted_creature->type->id;
     }
     get_event_bus().send<event_type::avatar_moves>( mount_type, m.ter( new_pos ).id(),
             u.current_movement_mode(), u.is_underwater(), new_pos.z );
     // TODO: fix point types
     const tripoint_abs_omt old_abs_omt( ms_to_omt_copy( old_abs_pos ) );
     const tripoint_abs_omt new_abs_omt( ms_to_omt_copy( new_abs_pos ) );
     if( old_abs_omt != new_abs_omt ) {
         const oter_id &cur_ter = overmap_buffer.ter( new_abs_omt );
         const oter_id &past_ter = overmap_buffer.ter( old_abs_omt );
         get_event_bus().send<event_type::avatar_enters_omt>( new_abs_omt.raw(), cur_ter );
         // if the player has moved omt then might trigger an EOC for that OMT
         effect_on_conditions::om_move();
         if( !past_ter->get_exit_EOC().is_null() ) {
             dialogue d( get_talker_for( get_avatar() ), nullptr );
             effect_on_condition_id eoc = cur_ter->get_exit_EOC();
             if( eoc->type == eoc_type::ACTIVATION ) {
                 eoc->activate( d );
             } else {
                 debugmsg( "Must use an activation eoc for OMT movement.  Otherwise, create a non-recurring effect_on_condition for this with its condition and effects, then have a recurring one queue it." );
             }
         }
         if( !cur_ter->get_entry_EOC().is_null() ) {
             dialogue d( get_talker_for( get_avatar() ), nullptr );
             effect_on_condition_id eoc = cur_ter->get_exit_EOC();
             if( eoc->type == eoc_type::ACTIVATION ) {
                 eoc->activate( d );
             } else {
                 debugmsg( "Must use an activation eoc for OMT movement.  Otherwise, create a non-recurring effect_on_condition for this with its condition and effects, then have a recurring one queue it." );
             }
         }
     }
 }
References ACTIVATION, avatar_enters_omt, avatar_moves, Character::current_movement_mode(), debugmsg, eoc, game::get_avatar, oter_t::get_entry_EOC(), game::get_event_bus, oter_t::get_exit_EOC(), get_talker_for(), map::getabs(), int_id< T >::id(), Character::is_mounted(), string_id< T >::is_null(), Creature::is_underwater(), game::m, Character::mounted_creature, ms_to_omt_copy(), effect_on_conditions::om_move(), overmap_buffer, Creature::pos(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), event_bus::send(), map::ter(), overmapbuffer::ter(), game::u, and tripoint::z.
Referenced by avatar_action::swim(), game::vertical_move(), and game::walk_move().