Cataclysm DDA: io Namespace Reference
io Namespace Reference
Namespaces
detail
The namespace contains classes that do write/read to/from JSON via either the Json classes in "json.h" or via the io function of the object to be written/read.
Classes
struct default_tag
Tag that indicates the default value for io should be the default value of the type itself, i.e.
struct empty_default_tag
Tag that indicates the value of the io is some kind of container and its default value is to be empty.
struct required_tag
Tag that indicates the value is required and must exists in the JSON data.
class JsonObjectInputArchive
Input archive reading data from a Json object.
class JsonArrayInputArchive
Input archive reading data from a Json array.
class JsonObjectOutputArchive
Output archive matching the input archive JsonObjectInputArchive.
class JsonArrayOutputArchive
Output archive matching the input archive JsonArrayInputArchive.
class InvalidEnumString
struct array_archive_tag
Tag that indicates the class is stored in a JSON array.
struct object_archive_tag
Tag that indicates the class is stored in a JSON object.
struct acc_data
Functions
template<>
std::string enum_to_string< achievement_comparison > (achievement_comparison data)
template<>
std::string enum_to_string< achievement::time_bound::epoch > (achievement::time_bound::epoch data)
template<>
std::string enum_to_string< requirement_visibility > (requirement_visibility data)
template<>
std::string enum_to_string< achievement_completion > (achievement_completion data)
template<>
std::string enum_to_string< butcher_type > (butcher_type data)
template<>
std::string enum_to_string< based_on_type > (based_on_type data)
template<>
std::string enum_to_string< distraction_type > (distraction_type data)
template<>
std::string enum_to_string< aim_exit > (const aim_exit v)
template<>
std::string enum_to_string< aim_entry > (const aim_entry v)
template<>
std::string enum_to_string< bionic_ui_sort_mode > (bionic_ui_sort_mode mode)
template<>
std::string enum_to_string< side > (side data)
template<>
std::string enum_to_string< body_part_type::type > (body_part_type::type data)
template<>
std::string enum_to_string< moon_phase > (moon_phase phase_num)
template<>
std::string enum_to_string< time_accuracy > (time_accuracy acc)
template<>
std::string enum_to_string< cata_variant_type > (cata_variant_type type)
template<>
std::string enum_to_string< blood_type > (blood_type data)
template<>
std::string enum_to_string< character_stat > (character_stat data)
template<>
std::string enum_to_string< climbing_aid::category > (climbing_aid::category data)
template<>
std::string enum_to_string< clothing_mod_type > (clothing_mod_type data)
template<>
std::string enum_to_string< computer_action > (const computer_action act)
template<>
std::string enum_to_string< computer_failure_type > (const computer_failure_type fail)
template<>
std::string enum_to_string< usage_from > (usage_from data)
template<>
std::string enum_to_string< debug_menu::debug_menu_index > (debug_menu::debug_menu_index v)
template<>
std::string enum_to_string< eoc_type > (eoc_type data)
template<>
std::string enum_to_string< event_type > (event_type data)
template<>
std::string enum_to_string< game_message_type > (game_message_type data)
template<>
std::string enum_to_string< description_affix > (description_affix data)
template<>
std::string enum_to_string< tut_lesson > (tut_lesson data)
template<>
std::string enum_to_string< inventory_selector::uimode > (inventory_selector::uimode mode)
template<>
std::string enum_to_string< layer_level > (layer_level data)
template<>
std::string enum_to_string< encumbrance_modifier > (encumbrance_modifier data)
template<>
std::string enum_to_string< link_state > (link_state data)
template<>
std::string enum_to_string< grip_val > (grip_val val)
template<>
std::string enum_to_string< length_val > (length_val val)
template<>
std::string enum_to_string< surface_val > (surface_val val)
template<>
std::string enum_to_string< balance_val > (balance_val val)
template<>
std::string enum_to_string< phase_id > (phase_id data)
template<>
std::string enum_to_string< Item_spawn_data::overflow_behaviour > (Item_spawn_data::overflow_behaviour data)
template<>
std::string enum_to_string< pocket_type > (pocket_type data)
template<>
std::string enum_to_string< condition_type > (condition_type data)
template<>
std::string enum_to_string< itype_variant_kind > (itype_variant_kind data)
template<>
std::string enum_to_string< direction > (direction data)
template<>
std::string enum_to_string< spell_target > (spell_target data)
template<>
std::string enum_to_string< spell_shape > (spell_shape data)
template<>
std::string enum_to_string< spell_flag > (spell_flag data)
template<>
std::string enum_to_string< magic_energy_type > (magic_energy_type data)
template<>
std::string enum_to_string< enchantment::has > (enchantment::has data)
template<>
std::string enum_to_string< enchantment::condition > (enchantment::condition data)
template<>
std::string enum_to_string< enchant_vals::mod > (enchant_vals::mod data)
template<>
std::string enum_to_string< map_extra_method > (map_extra_method data)
template<>
std::string enum_to_string< ter_furn_flag > (ter_furn_flag data)
template<>
std::string enum_to_string< season_type > (season_type data)
template<>
std::string enum_to_string< jmapgen_flags > (jmapgen_flags v)
template<>
std::string enum_to_string< mapgen_parameter_scope > (mapgen_parameter_scope v)
template<>
std::string enum_to_string< breathability_rating > (breathability_rating data)
template<>
std::string enum_to_string< mission::mission_status > (mission::mission_status data)
template<>
std::string enum_to_string< mission_kind > (mission_kind data)
template<>
std::string enum_to_string< mission_origin > (mission_origin data)
template<>
std::string enum_to_string< mission_goal > (mission_goal data)
template<>
std::string enum_to_string< mongroup::horde_behaviour > (mongroup::horde_behaviour data)
template<>
std::string enum_to_string< mon_trigger > (mon_trigger data)
template<>
std::string enum_to_string< mdeath_type > (mdeath_type data)
template<>
std::string enum_to_string< music::music_id > (music::music_id data)
template<>
std::string enum_to_string< mutagen_technique > (mutagen_technique data)
template<>
std::string enum_to_string< overmap_special_subtype > (overmap_special_subtype data)
template<>
std::string enum_to_string< om_direction::type > (om_direction::type d)
template<>
std::string enum_to_string< cube_direction > (cube_direction data)
template<>
std::string enum_to_string< oter_flags > (oter_flags data)
template<>
std::string enum_to_string< oter_travel_cost_type > (oter_travel_cost_type data)
template<>
std::string enum_to_string< join_type > (join_type data)
template<>
std::string enum_to_string< ot_match_type > (ot_match_type data)
template<>
std::string enum_to_string< proficiency_bonus_type > (const proficiency_bonus_type data)
template<>
std::string enum_to_string< relic_procgen_data::type > (relic_procgen_data::type data)
template<>
std::string enum_to_string< relic_recharge_type > (relic_recharge_type type)
template<>
std::string enum_to_string< relic_recharge_has > (relic_recharge_has has)
template<>
std::string enum_to_string< sounds::sound_t > (sounds::sound_t data)
template<>
std::string enum_to_string< vitamin_type > (vitamin_type data)
template<>
std::string enum_to_string< precip_class > (precip_class data)
template<>
std::string enum_to_string< weather_sound_category > (weather_sound_category data)
template<>
std::string enum_to_string< widget_var > (widget_var data)
template<>
std::string enum_to_string< cardinal_direction > (cardinal_direction dir)
template<>
std::string enum_to_string< bodypart_status > (bodypart_status stat)
template<>
std::string enum_to_string< widget_alignment > (widget_alignment align)
Enumeration (de)serialization to/from string.
enum_to_string converts an enumeration value to a string (which can be written to JSON).
The result must be an non-empty string.
This function must be implemented somewhere for each enumeration type for which conversion is required.
Such enums must also specialize enum_traits to specify their 'last' member.
string_to_enum converts the string value back into an enumeration value. The input is expected to be one of the outputs of enum_to_string. If the given string does not match an enumeration, an InvalidEnumString is thrown.
string_to_enum<E>(enum_to_string<E>(X)) == X
must yield true for all values of the enumeration E.
template<typename E >
std::string enum_to_string (E)
template<typename E >
std::unordered_map< std::string, E > build_enum_lookup_map ()
template<typename E >
const std::unordered_map< std::string, E > & get_enum_lookup_map ()
template<typename C , typename E = typename C::mapped_type>
E string_to_enum_look_up (const C &container, const std::string &data)
template<typename E >
E string_to_enum (const std::string &data)
template<typename C , typename E = typename C::mapped_type>
std::optional< E > string_to_enum_look_up_optional (const C &container, const std::string &data)
template<typename E >
std::optional< E > string_to_enum_optional (const std::string &data)
template<typename E >
bool enum_is_valid (const std::string &data)
Function Documentation
build_enum_lookup_map()
template<typename E > std::unordered_map<std::string, E> io::build_enum_lookup_map ()
Definition at line 43 of file enum_conversions.h.
 {
     static_assert( std::is_enum_v<E>, "E should be an enum type" );
     static_assert( has_enum_traits<E>::value, "enum E needs a specialization of enum_traits" );
     std::unordered_map<std::string, E> result;
     using Int = std::underlying_type_t<E>;
     constexpr Int max = static_cast<Int>( enum_traits<E>::last );
     for( Int i = 0; i < max; ++i ) {
         E e = static_cast<E>( i );
         auto inserted = result.emplace( enum_to_string( e ), e );
         if( !inserted.second ) {
             cata_fatal( "repeated enum string %s (%d and %d)", inserted.first->first,
                         static_cast<Int>( inserted.first->second ), i );
         }
     }
     return result;
 }
References cata_fatal, enum_to_string(), and max().
enum_is_valid()
template<typename E > bool io::enum_is_valid (const std::string & data)
Definition at line 109 of file enum_conversions.h.
 {
     return get_enum_lookup_map<E>().count( data );
 }
enum_to_string()
template<typename E > std::string io::enum_to_string (E)
Referenced by anonymous_namespace{event_bus.cpp}::_make_dyn(), build_enum_lookup_map(), climbing_aid::condition::category_string(), debug_menu::character_edit_desc_menu(), achievement_requirement::check(), mapgen_parameter::check(), mutable_overmap_terrain::check(), mapgen_value< Id >::param_source::check(), jmapgen_vehicle::check(), new_field::check(), event_statistic_field_summary< IntField >::check(), value_constraint::check(), mapgen_parameter::check_consistent_with(), event_type_event_source::debug_description(), mutable_overmap_terrain::deserialize(), char_creation::draw_blood(), inventory_selector::draw_footer(), overmap_ui::draw_om_sidebar(), draw_stats_info(), draw_stats_tab(), item_contents::item_contents_helper::find_pocket_for(), cata_variant::get(), cata::event::get_variant(), overmap_special::load(), butchery_requirements::load(), mapgendata::neighbor_at(), jmapgen_nested::neighbor_flag_any_check::neighbor_flag_any_check(), jmapgen_nested::neighbor_flag_check::neighbor_flag_check(), jmapgen_nested::neighbor_join_check::neighbor_join_check(), jmapgen_nested::neighbor_oter_check::neighbor_oter_check(), memorial_logger::notify(), spell_type::serialize(), comp_selection< CompType >::serialize(), cata_variant_detail::convert_enum< T >::to_string(), and effect_type::verify().
enum_to_string< achievement::time_bound::epoch >()
template<> std::string io::enum_to_string< achievement::time_bound::epoch > (achievement::time_bound::epoch data)
Definition at line 116 of file achievement.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case achievement::time_bound::epoch::cataclysm: return "cataclysm";
         case achievement::time_bound::epoch::game_start: return "game_start";
         // *INDENT-ON*
         case achievement::time_bound::epoch::last:
             break;
     }
     cata_fatal( "Invalid epoch" );
 }
References cata_fatal, achievement::time_bound::cataclysm, achievement::time_bound::game_start, and achievement::time_bound::last.
enum_to_string< achievement_comparison >()
template<> std::string io::enum_to_string< achievement_comparison > (achievement_comparison data)
Definition at line 100 of file achievement.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case achievement_comparison::equal: return "==";
         case achievement_comparison::less_equal: return "<=";
         case achievement_comparison::greater_equal: return ">=";
         case achievement_comparison::anything: return "anything";
         // *INDENT-ON*
         case achievement_comparison::last:
             break;
     }
     cata_fatal( "Invalid achievement_comparison" );
 }
References anything, cata_fatal, equal, greater_equal, last, and less_equal.
enum_to_string< achievement_completion >()
template<> std::string io::enum_to_string< achievement_completion > (achievement_completion data)
Definition at line 580 of file achievement.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case achievement_completion::pending: return "pending";
         case achievement_completion::completed: return "completed";
         case achievement_completion::failed: return "failed";
         // *INDENT-ON*
         case achievement_completion::last:
             break;
     }
     cata_fatal( "Invalid achievement_completion" );
 }
References cata_fatal, completed, failed, last, and pending.
enum_to_string< aim_entry >()
template<> std::string io::enum_to_string< aim_entry > (const aim_entry v)
Definition at line 97 of file advanced_inv.cpp.
 {
     switch( v ) {
         // *INDENT-OFF*
         case aim_entry::START: return "START";
         case aim_entry::VEHICLE: return "VEHICLE";
         case aim_entry::MAP: return "MAP";
         case aim_entry::RESET: return "RESET";
         // *INDENT-ON*
         case aim_entry::last:
             break;
     }
     cata_fatal( "Invalid aim_entry" );
 }
References cata_fatal, last, MAP, RESET, START, and VEHICLE.
enum_to_string< aim_exit >()
template<> std::string io::enum_to_string< aim_exit > (const aim_exit v)
Definition at line 82 of file advanced_inv.cpp.
 {
     switch( v ) {
         // *INDENT-OFF*
         case aim_exit::none: return "none";
         case aim_exit::okay: return "okay";
         case aim_exit::re_entry: return "re_entry";
         // *INDENT-ON*
         case aim_exit::last:
             break;
     }
     cata_fatal( "Invalid aim_exit" );
 }
References cata_fatal, last, none, okay, and re_entry.
enum_to_string< balance_val >()
template<> std::string io::enum_to_string< balance_val > (balance_val val)
Definition at line 4015 of file item_factory.cpp.
 {
     switch( val ) {
         case balance_val::CLUMSY: return "clumsy";
         case balance_val::UNEVEN: return "uneven";
         case balance_val::NEUTRAL: return "neutral";
         case balance_val::GOOD: return "good";
         default: break;
     }
     cata_fatal( "Invalid balance val" );
 }
References cata_fatal, CLUMSY, GOOD, NEUTRAL, and UNEVEN.
enum_to_string< based_on_type >()
template<> std::string io::enum_to_string< based_on_type > (based_on_type data)
Definition at line 47 of file activity_type.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case based_on_type::TIME: return "time";
         case based_on_type::SPEED: return "speed";
         case based_on_type::NEITHER: return "neither";
         // *INDENT-ON*
         default:
             cata_fatal( "Invalid based_on_type in enum_to_string" );
     }
 }
References cata_fatal, NEITHER, SPEED, and TIME.
enum_to_string< bionic_ui_sort_mode >()
template<> std::string io::enum_to_string< bionic_ui_sort_mode > (bionic_ui_sort_mode mode)
Definition at line 165 of file bionics_ui.cpp.
 {
     switch( mode ) {
         case bionic_ui_sort_mode::nsort:
         case bionic_ui_sort_mode::NONE:
             return "none";
         case bionic_ui_sort_mode::POWER:
             return "power";
         case bionic_ui_sort_mode::NAME:
             return "name";
         case bionic_ui_sort_mode::INVLET:
             return "invlet";
     }
     return "error";
 }
References INVLET, NAME, NONE, nsort, and POWER.
enum_to_string< blood_type >()
template<> std::string io::enum_to_string< blood_type > (blood_type data)
Definition at line 504 of file character.cpp.
 {
     switch( data ) {
             // *INDENT-OFF*
         case blood_type::blood_O: return "O";
         case blood_type::blood_A: return "A";
         case blood_type::blood_B: return "B";
         case blood_type::blood_AB: return "AB";
             // *INDENT-ON*
         case blood_type::num_bt:
             break;
     }
     cata_fatal( "Invalid blood_type" );
 }
References blood_A, blood_AB, blood_B, blood_O, cata_fatal, and num_bt.
enum_to_string< body_part_type::type >()
template<> std::string io::enum_to_string< body_part_type::type > (body_part_type::type data)
Definition at line 76 of file bodypart.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case body_part_type::type::arm: return "arm";
         case body_part_type::type::other: return "other";
         case body_part_type::type::foot: return "foot";
         case body_part_type::type::hand: return "hand";
         case body_part_type::type::head: return "head";
         case body_part_type::type::leg: return "leg";
         case body_part_type::type::mouth: return "mouth";
         case body_part_type::type::sensor: return "sensor";
         case body_part_type::type::tail: return "tail";
         case body_part_type::type::torso: return "torso";
         case body_part_type::type::wing: return "wing";
             // *INDENT-ON*
         case body_part_type::type::num_types:
             break;
     }
     cata_fatal( "Invalid body part type." );
 }
References body_part_type::arm, cata_fatal, body_part_type::foot, body_part_type::hand, body_part_type::head, body_part_type::leg, body_part_type::mouth, body_part_type::num_types, body_part_type::other, body_part_type::sensor, body_part_type::tail, body_part_type::torso, and body_part_type::wing.
enum_to_string< bodypart_status >()
template<> std::string io::enum_to_string< bodypart_status > (bodypart_status stat)
Definition at line 240 of file widget.cpp.
 {
     switch( stat ) {
         case bodypart_status::BITTEN:
             return "bitten";
         case bodypart_status::INFECTED:
             return "infected";
         case bodypart_status::BROKEN:
             return "broken";
         case bodypart_status::SPLINTED:
             return "splinted";
         case bodypart_status::BANDAGED:
             return "bandaged";
         case bodypart_status::DISINFECTED:
             return "disinfected";
         case bodypart_status::BLEEDING:
             return "bleeding";
         case bodypart_status::num_bodypart_status:
         default:
             break;
     }
     cata_fatal( "Invalid bodypart_status" );
 }
References BANDAGED, BITTEN, BLEEDING, BROKEN, cata_fatal, DISINFECTED, INFECTED, num_bodypart_status, and SPLINTED.
enum_to_string< breathability_rating >()
template<> std::string io::enum_to_string< breathability_rating > (breathability_rating data)
Definition at line 40 of file material.cpp.
 {
     switch( data ) {
         case breathability_rating::IMPERMEABLE:
             return "IMPERMEABLE";
         case breathability_rating::POOR:
             return "POOR";
         case breathability_rating::AVERAGE:
             return "AVERAGE";
         case breathability_rating::GOOD:
             return "GOOD";
         case breathability_rating::MOISTURE_WICKING:
             return "MOISTURE_WICKING";
         case breathability_rating::SECOND_SKIN:
             return "SECOND_SKIN";
         case breathability_rating::last:
             break;
     }
     cata_fatal( "Invalid breathability" );
 }
References AVERAGE, cata_fatal, GOOD, IMPERMEABLE, last, MOISTURE_WICKING, POOR, and SECOND_SKIN.
enum_to_string< butcher_type >()
template<> std::string io::enum_to_string< butcher_type > (butcher_type data)
Definition at line 352 of file activity_handlers.cpp.
 {
     switch( data ) {
     case butcher_type::BLEED: return "BLEED";
     case butcher_type::DISMEMBER: return "DISMEMBER";
     case butcher_type::DISSECT: return "DISSECT";
     case butcher_type::FIELD_DRESS: return "FIELD_DRESS";
     case butcher_type::FULL: return "FULL";
     case butcher_type::QUARTER: return "QUARTER";
     case butcher_type::QUICK: return "QUICK";
     case butcher_type::SKIN: return "SKIN";
     case butcher_type::NUM_TYPES: break;
     }
     cata_fatal( "Invalid valid_target" );
 }
References BLEED, cata_fatal, DISMEMBER, DISSECT, FIELD_DRESS, FULL, NUM_TYPES, QUARTER, QUICK, and SKIN.
enum_to_string< cardinal_direction >()
template<> std::string io::enum_to_string< cardinal_direction > (cardinal_direction dir)
Definition at line 211 of file widget.cpp.
 {
     switch( dir ) {
         case cardinal_direction::NORTH:
             return "N";
         case cardinal_direction::SOUTH:
             return "S";
         case cardinal_direction::EAST:
             return "E";
         case cardinal_direction::WEST:
             return "W";
         case cardinal_direction::NORTHEAST:
             return "NE";
         case cardinal_direction::NORTHWEST:
             return "NW";
         case cardinal_direction::SOUTHEAST:
             return "SE";
         case cardinal_direction::SOUTHWEST:
             return "SW";
         case cardinal_direction::LOCAL:
             return "L";
         case cardinal_direction::num_cardinal_directions:
         default:
             break;
     }
     cata_fatal( "Invalid cardinal_direction" );
 }
References cata_fatal, EAST, LOCAL, NORTH, NORTHEAST, NORTHWEST, num_cardinal_directions, SOUTH, SOUTHEAST, SOUTHWEST, and WEST.
enum_to_string< cata_variant_type >()
template<> std::string io::enum_to_string< cata_variant_type > (cata_variant_type type)
Definition at line 34 of file cata_variant.cpp.
 {
     switch( type ) {
         // *INDENT-OFF*
         case cata_variant_type::void_: return "void";
         case cata_variant_type::achievement_id: return "achievement_id";
         case cata_variant_type::activity_id: return "activity_id";
         case cata_variant_type::addiction_id: return "addiction_id";
         case cata_variant_type::bionic_id: return "bionic_id";
         case cata_variant_type::body_part: return "body_part";
         case cata_variant_type::bool_: return "bool";
         case cata_variant_type::character_id: return "character_id";
         case cata_variant_type::chrono_seconds: return "chrono_seconds";
         case cata_variant_type::debug_menu_index: return "debug_menu_index";
         case cata_variant_type::efftype_id: return "efftype_id";
         case cata_variant_type::faction_id: return "faction_id";
         case cata_variant_type::field_type_id: return "field_type_id";
         case cata_variant_type::field_type_str_id: return "field_type_str_id";
         case cata_variant_type::furn_id: return "furn_id";
         case cata_variant_type::furn_str_id: return "furn_str_id";
         case cata_variant_type::flag_id: return "flag_id";
         case cata_variant_type::int_: return "int";
         case cata_variant_type::item_group_id: return "item_group_id";
         case cata_variant_type::itype_id: return "itype_id";
         case cata_variant_type::matype_id: return "matype_id";
         case cata_variant_type::mongroup_id: return "mongroup_id";
         case cata_variant_type::mtype_id: return "mtype_id";
         case cata_variant_type::move_mode_id: return "character_movemode";
         case cata_variant_type::mutagen_technique: return "mutagen_technique";
         case cata_variant_type::mutation_category_id: return "mutation_category_id";
         case cata_variant_type::nested_mapgen_id: return "nested_mapgen_id";
         case cata_variant_type::npc_template_id: return "npc_template_id";
         case cata_variant_type::oter_id: return "oter_id";
         case cata_variant_type::oter_type_str_id: return "oter_type_str_id";
         case cata_variant_type::overmap_special_id: return "overmap_special_id";
         case cata_variant_type::palette_id: return "palette_id";
         case cata_variant_type::point: return "point";
         case cata_variant_type::profession_id: return "profession_id";
         case cata_variant_type::proficiency_id: return "proficiency_id";
         case cata_variant_type::skill_id: return "skill_id";
         case cata_variant_type::species_id: return "species_id";
         case cata_variant_type::spell_id: return "spell_id";
         case cata_variant_type::string: return "string";
         case cata_variant_type::ter_id: return "ter_id";
         case cata_variant_type::ter_furn_transform_id: return "ter_furn_transform_id";
         case cata_variant_type::ter_str_id: return "ter_str_id";
         case cata_variant_type::trait_id: return "trait_id";
         case cata_variant_type::trap_id: return "trap_id";
         case cata_variant_type::trap_str_id: return "trap_str_id";
         case cata_variant_type::tripoint: return "tripoint";
         case cata_variant_type::vgroup_id: return "vgroup_id";
         case cata_variant_type::widget_id: return "widget_id";
         case cata_variant_type::zone_type_id: return "zone_type_id";
         // *INDENT-ON*
         case cata_variant_type::num_types:
             break;
     }
     debugmsg( "unknown cata_variant_type %d", static_cast<int>( type ) );
     return "";
 }
References achievement_id, activity_id, addiction_id, bionic_id, body_part, bool_, character_id, chrono_seconds, debug_menu_index, debugmsg, efftype_id, faction_id, field_type_id, field_type_str_id, flag_id, furn_id, furn_str_id, int_, item_group_id, itype_id, matype_id, mongroup_id, move_mode_id, mtype_id, mutagen_technique, mutation_category_id, nested_mapgen_id, npc_template_id, num_types, oter_id, oter_type_str_id, overmap_special_id, palette_id, point, profession_id, proficiency_id, skill_id, species_id, spell_id, string, ter_furn_transform_id, ter_id, ter_str_id, trait_id, trap_id, trap_str_id, tripoint, vgroup_id, void_, widget_id, and zone_type_id.
enum_to_string< character_stat >()
template<> std::string io::enum_to_string< character_stat > (character_stat data)
Definition at line 4302 of file character.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
     case character_stat::STRENGTH:     return "STR";
     case character_stat::DEXTERITY:    return "DEX";
     case character_stat::INTELLIGENCE: return "INT";
     case character_stat::PERCEPTION:   return "PER";
         // *INDENT-ON*
         case character_stat::DUMMY_STAT:
             break;
     }
     cata_fatal( "Invalid character_stat" );
 }
References cata_fatal, DEXTERITY, DUMMY_STAT, INTELLIGENCE, PERCEPTION, and STRENGTH.
enum_to_string< climbing_aid::category >()
template<> std::string io::enum_to_string< climbing_aid::category > (climbing_aid::category data)
Definition at line 150 of file climbing.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
     case climbing_aid::category::special: return "special";
     case climbing_aid::category::ter_furn: return "ter_furn";
     case climbing_aid::category::veh: return "veh";
     case climbing_aid::category::item: return "item";
     case climbing_aid::category::character: return "character";
     case climbing_aid::category::trait: return "trait";
         // *INDENT-ON*
         case climbing_aid::category::last:
             break;
     }
     cata_fatal( "Invalid climbing aid condition category" );
 }
References cata_fatal, climbing_aid::character, climbing_aid::item, climbing_aid::last, climbing_aid::special, climbing_aid::ter_furn, climbing_aid::trait, and climbing_aid::veh.
enum_to_string< clothing_mod_type >()
template<> std::string io::enum_to_string< clothing_mod_type > (clothing_mod_type data)
Definition at line 45 of file clothing_mod.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case clothing_mod_type_acid: return "acid";
         case clothing_mod_type_fire: return "fire";
         case clothing_mod_type_bash: return "bash";
         case clothing_mod_type_cut: return "cut";
         case clothing_mod_type_bullet: return "bullet";
         case clothing_mod_type_encumbrance: return "encumbrance";
         case clothing_mod_type_warmth: return "warmth";
         case clothing_mod_type_invalid: return "invalid";
         // *INDENT-ON*
         case num_clothing_mod_types:
             break;
     }
     debugmsg( "Invalid mod type value '%d'.", data );
     return "invalid";
 }
References clothing_mod_type_acid, clothing_mod_type_bash, clothing_mod_type_bullet, clothing_mod_type_cut, clothing_mod_type_encumbrance, clothing_mod_type_fire, clothing_mod_type_invalid, clothing_mod_type_warmth, debugmsg, and num_clothing_mod_types.
Referenced by clothing_mods::string_from_clothing_mod_type().
enum_to_string< computer_action >()
template<> std::string io::enum_to_string< computer_action > (const computer_action act)
Definition at line 325 of file computer.cpp.
 {
     switch( act ) {
         // *INDENT-OFF*
         case COMPACT_NULL: return "null";
         case COMPACT_AMIGARA_LOG: return "amigara_log";
         case COMPACT_AMIGARA_START: return "amigara_start";
         case COMPACT_BLOOD_ANAL: return "blood_anal";
         case COMPACT_CASCADE: return "cascade";
         case COMPACT_COMPLETE_DISABLE_EXTERNAL_POWER: return "complete_disable_external_power";
         case COMPACT_CONVEYOR: return "conveyor";
         case COMPACT_DATA_ANAL: return "data_anal";
         case COMPACT_DEACTIVATE_SHOCK_VENT: return "deactivate_shock_vent";
         case COMPACT_DISCONNECT: return "disconnect";
         case COMPACT_DOWNLOAD_SOFTWARE: return "download_software";
         case COMPACT_ELEVATOR_ON: return "elevator_on";
         case COMPACT_EMERG_MESS: return "emerg_mess";
         case COMPACT_EMERG_REF_CENTER: return "emerg_ref_center";
         case COMPACT_EXTRACT_RAD_SOURCE: return "extract_rad_source";
         case COMPACT_GEIGER: return "geiger";
         case COMPACT_IRRADIATOR: return "irradiator";
         case COMPACT_LIST_BIONICS: return "list_bionics";
         case COMPACT_LIST_MUTATIONS: return "list_mutations";
         case COMPACT_LOCK: return "lock";
         case COMPACT_MAP_SEWER: return "map_sewer";
         case COMPACT_MAP_SUBWAY: return "map_subway";
         case COMPACT_MAPS: return "maps";
         case COMPACT_MISS_DISARM: return "miss_disarm";
         case COMPACT_MISS_LAUNCH: return "miss_launch";
         case COMPACT_OPEN: return "open";
         case COMPACT_OPEN_GATE: return "open_gate";
         case COMPACT_CLOSE_GATE: return "close_gate";
         case COMPACT_OPEN_DISARM: return "open_disarm";
         case COMPACT_PORTAL: return "portal";
         case COMPACT_RADIO_ARCHIVE: return "radio_archive";
         case COMPACT_RELEASE: return "release";
         case COMPACT_RELEASE_BIONICS: return "release_bionics";
         case COMPACT_RELEASE_DISARM: return "release_disarm";
         case COMPACT_REPEATER_MOD: return "repeater_mod";
         case COMPACT_RESEARCH: return "research";
         case COMPACT_SAMPLE: return "sample";
         case COMPACT_SHUTTERS: return "shutters";
         case COMPACT_SR1_MESS: return "sr1_mess";
         case COMPACT_SR2_MESS: return "sr2_mess";
         case COMPACT_SR3_MESS: return "sr3_mess";
         case COMPACT_SR4_MESS: return "sr4_mess";
         case COMPACT_SRCF_1_MESS: return "srcf_1_mess";
         case COMPACT_SRCF_2_MESS: return "srcf_2_mess";
         case COMPACT_SRCF_3_MESS: return "srcf_3_mess";
         case COMPACT_SRCF_ELEVATOR: return "srcf_elevator";
         case COMPACT_SRCF_SEAL: return "srcf_seal";
         case COMPACT_SRCF_SEAL_ORDER: return "srcf_seal_order";
         case COMPACT_TERMINATE: return "terminate";
         case COMPACT_TOLL: return "toll";
         case COMPACT_TOWER_UNRESPONSIVE: return "tower_unresponsive";
         case COMPACT_UNLOCK: return "unlock";
         case COMPACT_UNLOCK_DISARM: return "unlock_disarm";
         // *INDENT-OFF*
         case NUM_COMPUTER_ACTIONS:
             break;
     }
     cata_fatal( "Invalid computer_action" );
 }
References act, cata_fatal, COMPACT_AMIGARA_LOG, COMPACT_AMIGARA_START, COMPACT_BLOOD_ANAL, COMPACT_CASCADE, COMPACT_CLOSE_GATE, COMPACT_COMPLETE_DISABLE_EXTERNAL_POWER, COMPACT_CONVEYOR, COMPACT_DATA_ANAL, COMPACT_DEACTIVATE_SHOCK_VENT, COMPACT_DISCONNECT, COMPACT_DOWNLOAD_SOFTWARE, COMPACT_ELEVATOR_ON, COMPACT_EMERG_MESS, COMPACT_EMERG_REF_CENTER, COMPACT_EXTRACT_RAD_SOURCE, COMPACT_GEIGER, COMPACT_IRRADIATOR, COMPACT_LIST_BIONICS, COMPACT_LIST_MUTATIONS, COMPACT_LOCK, COMPACT_MAP_SEWER, COMPACT_MAP_SUBWAY, COMPACT_MAPS, COMPACT_MISS_DISARM, COMPACT_MISS_LAUNCH, COMPACT_NULL, COMPACT_OPEN, COMPACT_OPEN_DISARM, COMPACT_OPEN_GATE, COMPACT_PORTAL, COMPACT_RADIO_ARCHIVE, COMPACT_RELEASE, COMPACT_RELEASE_BIONICS, COMPACT_RELEASE_DISARM, COMPACT_REPEATER_MOD, COMPACT_RESEARCH, COMPACT_SAMPLE, COMPACT_SHUTTERS, COMPACT_SR1_MESS, COMPACT_SR2_MESS, COMPACT_SR3_MESS, COMPACT_SR4_MESS, COMPACT_SRCF_1_MESS, COMPACT_SRCF_2_MESS, COMPACT_SRCF_3_MESS, COMPACT_SRCF_ELEVATOR, COMPACT_SRCF_SEAL, COMPACT_SRCF_SEAL_ORDER, COMPACT_TERMINATE, COMPACT_TOLL, COMPACT_TOWER_UNRESPONSIVE, COMPACT_UNLOCK, COMPACT_UNLOCK_DISARM, and NUM_COMPUTER_ACTIONS.
enum_to_string< computer_failure_type >()
template<> std::string io::enum_to_string< computer_failure_type > (const computer_failure_type fail)
Definition at line 390 of file computer.cpp.
 {
     switch( fail ){
         // *INDENT-OFF*
         case COMPFAIL_NULL: return "null";
         case COMPFAIL_ALARM: return "alarm";
         case COMPFAIL_AMIGARA: return "amigara";
         case COMPFAIL_DAMAGE: return "damage";
         case COMPFAIL_DESTROY_BLOOD: return "destroy_blood";
         case COMPFAIL_DESTROY_DATA: return "destroy_data";
         case COMPFAIL_MANHACKS: return "manhacks";
         case COMPFAIL_PUMP_EXPLODE: return "pump_explode";
         case COMPFAIL_PUMP_LEAK: return "pump_leak";
         case COMPFAIL_SECUBOTS: return "secubots";
         case COMPFAIL_SHUTDOWN: return "shutdown";
         // *INDENT-ON*
         case NUM_COMPUTER_FAILURES:
             break;
     }
     cata_fatal( "Invalid computer_failure_type" );
 }
References cata_fatal, COMPFAIL_ALARM, COMPFAIL_AMIGARA, COMPFAIL_DAMAGE, COMPFAIL_DESTROY_BLOOD, COMPFAIL_DESTROY_DATA, COMPFAIL_MANHACKS, COMPFAIL_NULL, COMPFAIL_PUMP_EXPLODE, COMPFAIL_PUMP_LEAK, COMPFAIL_SECUBOTS, COMPFAIL_SHUTDOWN, and NUM_COMPUTER_FAILURES.
enum_to_string< condition_type >()
template<> std::string io::enum_to_string< condition_type > (condition_type data)
Definition at line 36 of file itype.cpp.
 {
     switch( data ) {
         case condition_type::FLAG:
             return "FLAG";
         case condition_type::VITAMIN:
             return "VITAMIN";
         case condition_type::COMPONENT_ID:
             return "COMPONENT_ID";
         case condition_type::COMPONENT_ID_SUBSTRING:
             return "COMPONENT_ID_SUBSTRING";
         case condition_type::VAR:
             return "VAR";
         case condition_type::SNIPPET_ID:
             return "SNIPPET_ID";
         case condition_type::num_condition_types:
             break;
     }
     cata_fatal( "Invalid condition_type" );
 }
References cata_fatal, COMPONENT_ID, COMPONENT_ID_SUBSTRING, FLAG, num_condition_types, SNIPPET_ID, VAR, and VITAMIN.
enum_to_string< cube_direction >()
template<> std::string io::enum_to_string< cube_direction > (cube_direction data)
Definition at line 189 of file overmap.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case cube_direction::north: return "north";
         case cube_direction::east: return "east";
         case cube_direction::south: return "south";
         case cube_direction::west: return "west";
         case cube_direction::above: return "above";
         case cube_direction::below: return "below";
         // *INDENT-ON*
         case cube_direction::last:
             break;
     }
     cata_fatal( "Invalid cube_direction" );
 }
References above, below, cata_fatal, east, last, north, south, and west.
enum_to_string< debug_menu::debug_menu_index >()
template<> std::string io::enum_to_string< debug_menu::debug_menu_index > (debug_menu::debug_menu_index v)
Definition at line 174 of file debug_menu.cpp.
 {
     switch( v ) {
         // *INDENT-OFF*
         case debug_menu::debug_menu_index::WISH: return "WISH";
         case debug_menu::debug_menu_index::SHORT_TELEPORT: return "SHORT_TELEPORT";
         case debug_menu::debug_menu_index::LONG_TELEPORT: return "LONG_TELEPORT";
         case debug_menu::debug_menu_index::REVEAL_MAP: return "REVEAL_MAP";
         case debug_menu::debug_menu_index::SPAWN_NPC: return "SPAWN_NPC";
         case debug_menu::debug_menu_index::SPAWN_OM_NPC: return "SPAWN_OM_NPC";
         case debug_menu::debug_menu_index::SPAWN_MON: return "SPAWN_MON";
         case debug_menu::debug_menu_index::GAME_STATE: return "GAME_STATE";
         case debug_menu::debug_menu_index::KILL_AREA: return "KILL_AREA";
         case debug_menu::debug_menu_index::KILL_NPCS: return "KILL_NPCS";
         case debug_menu::debug_menu_index::MUTATE: return "MUTATE";
         case debug_menu::debug_menu_index::SPAWN_VEHICLE: return "SPAWN_VEHICLE";
         case debug_menu::debug_menu_index::CHANGE_SKILLS: return "CHANGE_SKILLS";
         case debug_menu::debug_menu_index::CHANGE_THEORY: return "CHANGE_THEORY";
         case debug_menu::debug_menu_index::LEARN_MA: return "LEARN_MA";
         case debug_menu::debug_menu_index::UNLOCK_RECIPES: return "UNLOCK_RECIPES";
         case debug_menu::debug_menu_index::FORGET_ALL_RECIPES: return "FORGET_ALL_RECIPES";
         case debug_menu::debug_menu_index::FORGET_ALL_ITEMS: return "FORGET_ALL_ITEMS";
         case debug_menu::debug_menu_index::EDIT_PLAYER: return "EDIT_PLAYER";
         case debug_menu::debug_menu_index::CONTROL_NPC: return "CONTROL_NPC";
         case debug_menu::debug_menu_index::SPAWN_ARTIFACT: return "SPAWN_ARTIFACT";
         case debug_menu::debug_menu_index::SPAWN_CLAIRVOYANCE: return "SPAWN_CLAIRVOYANCE";
         case debug_menu::debug_menu_index::MAP_EDITOR: return "MAP_EDITOR";
         case debug_menu::debug_menu_index::CHANGE_WEATHER: return "CHANGE_WEATHER";
         case debug_menu::debug_menu_index::WIND_DIRECTION: return "WIND_DIRECTION";
         case debug_menu::debug_menu_index::WIND_SPEED: return "WIND_SPEED";
         case debug_menu::debug_menu_index::GEN_SOUND: return "GEN_SOUND";
         case debug_menu::debug_menu_index::KILL_MONS: return "KILL_MONS";
         case debug_menu::debug_menu_index::DISPLAY_HORDES: return "DISPLAY_HORDES";
         case debug_menu::debug_menu_index::TEST_IT_GROUP: return "TEST_IT_GROUP";
         case debug_menu::debug_menu_index::DAMAGE_SELF: return "DAMAGE_SELF";
         case debug_menu::debug_menu_index::BLEED_SELF: return "BLEED_SELF";
         case debug_menu::debug_menu_index::SHOW_SOUND: return "SHOW_SOUND";
         case debug_menu::debug_menu_index::DISPLAY_WEATHER: return "DISPLAY_WEATHER";
         case debug_menu::debug_menu_index::DISPLAY_SCENTS: return "DISPLAY_SCENTS";
         case debug_menu::debug_menu_index::CHANGE_TIME: return "CHANGE_TIME";
         case debug_menu::debug_menu_index::FORCE_TEMP: return "FORCE_TEMP";
         case debug_menu::debug_menu_index::SET_AUTOMOVE: return "SET_AUTOMOVE";
         case debug_menu::debug_menu_index::SHOW_MUT_CAT: return "SHOW_MUT_CAT";
         case debug_menu::debug_menu_index::OM_EDITOR: return "OM_EDITOR";
         case debug_menu::debug_menu_index::BENCHMARK: return "BENCHMARK";
         case debug_menu::debug_menu_index::OM_TELEPORT: return "OM_TELEPORT";
         case debug_menu::debug_menu_index::OM_TELEPORT_COORDINATES: return "OM_TELEPORT_COORDINATES";
         case debug_menu::debug_menu_index::OM_TELEPORT_CITY: return "OM_TELEPORT_CITY";
         case debug_menu::debug_menu_index::TRAIT_GROUP: return "TRAIT_GROUP";
         case debug_menu::debug_menu_index::ENABLE_ACHIEVEMENTS: return "ENABLE_ACHIEVEMENTS";
         case debug_menu::debug_menu_index::UNLOCK_ALL: return "UNLOCK_ALL";
         case debug_menu::debug_menu_index::SHOW_MSG: return "SHOW_MSG";
         case debug_menu::debug_menu_index::CRASH_GAME: return "CRASH_GAME";
         case debug_menu::debug_menu_index::MAP_EXTRA: return "MAP_EXTRA";
         case debug_menu::debug_menu_index::DISPLAY_NPC_PATH: return "DISPLAY_NPC_PATH";
         case debug_menu::debug_menu_index::DISPLAY_NPC_ATTACK: return "DISPLAY_NPC_ATTACK";
         case debug_menu::debug_menu_index::PRINT_FACTION_INFO: return "PRINT_FACTION_INFO";
         case debug_menu::debug_menu_index::PRINT_NPC_MAGIC: return "PRINT_NPC_MAGIC";
         case debug_menu::debug_menu_index::QUIT_NOSAVE: return "QUIT_NOSAVE";
         case debug_menu::debug_menu_index::QUICKLOAD: return "QUICKLOAD";
         case debug_menu::debug_menu_index::TEST_WEATHER: return "TEST_WEATHER";
         case debug_menu::debug_menu_index::WRITE_GLOBAL_EOCS: return "WRITE_GLOBAL_EOCS";
         case debug_menu::debug_menu_index::WRITE_GLOBAL_VARS: return "WRITE_GLOBAL_VARS";
         case debug_menu::debug_menu_index::EDIT_GLOBAL_VARS: return "SET_GLOBAL_VARS";
         case debug_menu::debug_menu_index::WRITE_TIMED_EVENTS: return "WRITE_TIMED_EVENTS";
         case debug_menu::debug_menu_index::SAVE_SCREENSHOT: return "SAVE_SCREENSHOT";
         case debug_menu::debug_menu_index::GAME_REPORT: return "GAME_REPORT";
         case debug_menu::debug_menu_index::GAME_MIN_ARCHIVE: return "GAME_MIN_ARCHIVE";
         case debug_menu::debug_menu_index::DISPLAY_SCENTS_LOCAL: return "DISPLAY_SCENTS_LOCAL";
         case debug_menu::debug_menu_index::DISPLAY_SCENTS_TYPE_LOCAL: return "DISPLAY_SCENTS_TYPE_LOCAL";
         case debug_menu::debug_menu_index::DISPLAY_TEMP: return "DISPLAY_TEMP";
         case debug_menu::debug_menu_index::DISPLAY_VEHICLE_AI: return "DISPLAY_VEHICLE_AI";
         case debug_menu::debug_menu_index::DISPLAY_VISIBILITY: return "DISPLAY_VISIBILITY";
         case debug_menu::debug_menu_index::DISPLAY_LIGHTING: return "DISPLAY_LIGHTING";
         case debug_menu::debug_menu_index::DISPLAY_TRANSPARENCY: return "DISPLAY_TRANSPARENCY";
         case debug_menu::debug_menu_index::DISPLAY_RADIATION: return "DISPLAY_RADIATION";
         case debug_menu::debug_menu_index::HOUR_TIMER: return "HOUR_TIMER";
         case debug_menu::debug_menu_index::CHANGE_SPELLS: return "CHANGE_SPELLS";
         case debug_menu::debug_menu_index::TEST_MAP_EXTRA_DISTRIBUTION: return "TEST_MAP_EXTRA_DISTRIBUTION";
         case debug_menu::debug_menu_index::NESTED_MAPGEN: return "NESTED_MAPGEN";
         case debug_menu::debug_menu_index::VEHICLE_EXPORT: return "VEHICLE_EXPORT";
         case debug_menu::debug_menu_index::VEHICLE_DELETE: return "VEHICLE_DELETE";
         case debug_menu::debug_menu_index::VEHICLE_BATTERY_CHARGE: return "VEHICLE_BATTERY_CHARGE";
         case debug_menu::debug_menu_index::GENERATE_EFFECT_LIST: return "GENERATE_EFFECT_LIST";
         case debug_menu::debug_menu_index::ACTIVATE_EOC: return "ACTIVATE_EOC";
         case debug_menu::debug_menu_index::IMPORT_FOLLOWER: return "IMPORT_FOLLOWER";
         case debug_menu::debug_menu_index::EXPORT_FOLLOWER: return "EXPORT_FOLLOWER";
         case debug_menu::debug_menu_index::EXPORT_SELF: return "EXPORT_SELF";
         case debug_menu::debug_menu_index::QUICK_SETUP: return "QUICK_SETUP";
         case debug_menu::debug_menu_index::TOGGLE_SETUP_MUTATION: return "TOGGLE_SETUP_MUTATION";
         case debug_menu::debug_menu_index::NORMALIZE_BODY_STAT: return "NORMALIZE_BODY_STAT";
         case debug_menu::debug_menu_index::SIX_MILLION_DOLLAR_SURVIVOR: return "SIX_MILLION_DOLLAR_SURVIVOR";
         case debug_menu::debug_menu_index::EDIT_FACTION: return "EDIT_FACTION";
         case debug_menu::debug_menu_index::WRITE_CITY_LIST: return "WRITE_CITY_LIST";
         // *INDENT-ON*
         case debug_menu::debug_menu_index::last:
             break;
     }
     debugmsg( "unknown debug_menu::debug_menu_index %d", static_cast<int>( v ) );
     return "";
 }
References debug_menu::ACTIVATE_EOC, debug_menu::BENCHMARK, debug_menu::BLEED_SELF, debug_menu::CHANGE_SKILLS, debug_menu::CHANGE_SPELLS, debug_menu::CHANGE_THEORY, debug_menu::CHANGE_TIME, debug_menu::CHANGE_WEATHER, debug_menu::CONTROL_NPC, debug_menu::CRASH_GAME, debug_menu::DAMAGE_SELF, debugmsg, debug_menu::DISPLAY_HORDES, debug_menu::DISPLAY_LIGHTING, debug_menu::DISPLAY_NPC_ATTACK, debug_menu::DISPLAY_NPC_PATH, debug_menu::DISPLAY_RADIATION, debug_menu::DISPLAY_SCENTS, debug_menu::DISPLAY_SCENTS_LOCAL, debug_menu::DISPLAY_SCENTS_TYPE_LOCAL, debug_menu::DISPLAY_TEMP, debug_menu::DISPLAY_TRANSPARENCY, debug_menu::DISPLAY_VEHICLE_AI, debug_menu::DISPLAY_VISIBILITY, debug_menu::DISPLAY_WEATHER, debug_menu::EDIT_FACTION, debug_menu::EDIT_GLOBAL_VARS, debug_menu::EDIT_PLAYER, debug_menu::ENABLE_ACHIEVEMENTS, debug_menu::EXPORT_FOLLOWER, debug_menu::EXPORT_SELF, debug_menu::FORCE_TEMP, debug_menu::FORGET_ALL_ITEMS, debug_menu::FORGET_ALL_RECIPES, debug_menu::GAME_MIN_ARCHIVE, debug_menu::GAME_REPORT, debug_menu::GAME_STATE, debug_menu::GEN_SOUND, debug_menu::GENERATE_EFFECT_LIST, debug_menu::HOUR_TIMER, debug_menu::IMPORT_FOLLOWER, debug_menu::KILL_AREA, debug_menu::KILL_MONS, debug_menu::KILL_NPCS, debug_menu::last, debug_menu::LEARN_MA, debug_menu::LONG_TELEPORT, debug_menu::MAP_EDITOR, debug_menu::MAP_EXTRA, debug_menu::MUTATE, debug_menu::NESTED_MAPGEN, debug_menu::NORMALIZE_BODY_STAT, debug_menu::OM_EDITOR, debug_menu::OM_TELEPORT, debug_menu::OM_TELEPORT_CITY, debug_menu::OM_TELEPORT_COORDINATES, debug_menu::PRINT_FACTION_INFO, debug_menu::PRINT_NPC_MAGIC, debug_menu::QUICK_SETUP, debug_menu::QUICKLOAD, debug_menu::QUIT_NOSAVE, debug_menu::REVEAL_MAP, debug_menu::SAVE_SCREENSHOT, debug_menu::SET_AUTOMOVE, debug_menu::SHORT_TELEPORT, debug_menu::SHOW_MSG, debug_menu::SHOW_MUT_CAT, debug_menu::SHOW_SOUND, debug_menu::SIX_MILLION_DOLLAR_SURVIVOR, debug_menu::SPAWN_ARTIFACT, debug_menu::SPAWN_CLAIRVOYANCE, debug_menu::SPAWN_MON, debug_menu::SPAWN_NPC, debug_menu::SPAWN_OM_NPC, debug_menu::SPAWN_VEHICLE, debug_menu::TEST_IT_GROUP, debug_menu::TEST_MAP_EXTRA_DISTRIBUTION, debug_menu::TEST_WEATHER, debug_menu::TOGGLE_SETUP_MUTATION, debug_menu::TRAIT_GROUP, debug_menu::UNLOCK_ALL, debug_menu::UNLOCK_RECIPES, debug_menu::VEHICLE_BATTERY_CHARGE, debug_menu::VEHICLE_DELETE, debug_menu::VEHICLE_EXPORT, debug_menu::WIND_DIRECTION, debug_menu::WIND_SPEED, debug_menu::WISH, debug_menu::WRITE_CITY_LIST, debug_menu::WRITE_GLOBAL_EOCS, debug_menu::WRITE_GLOBAL_VARS, and debug_menu::WRITE_TIMED_EVENTS.
enum_to_string< description_affix >()
template<> std::string io::enum_to_string< description_affix > (description_affix data)
Definition at line 88 of file field_type.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case description_affix::DESCRIPTION_AFFIX_IN: return "in";
         case description_affix::DESCRIPTION_AFFIX_COVERED_IN: return "covered_in";
         case description_affix::DESCRIPTION_AFFIX_ON: return "on";
         case description_affix::DESCRIPTION_AFFIX_UNDER: return "under";
         case description_affix::DESCRIPTION_AFFIX_ILLUMINATED_BY: return "illuminated_by";
         // *INDENT-ON*
         case description_affix::DESCRIPTION_AFFIX_NUM:
             break;
     }
     debugmsg( "Invalid description affix value '%d'.", data );
     return "invalid";
 }
References debugmsg, DESCRIPTION_AFFIX_COVERED_IN, DESCRIPTION_AFFIX_ILLUMINATED_BY, DESCRIPTION_AFFIX_IN, DESCRIPTION_AFFIX_NUM, DESCRIPTION_AFFIX_ON, and DESCRIPTION_AFFIX_UNDER.
enum_to_string< direction >()
template<> std::string io::enum_to_string< direction > (direction data)
Definition at line 389 of file line.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case direction::ABOVENORTHWEST: return "above_north_west";
         case direction::NORTHWEST: return "north_west";
         case direction::BELOWNORTHWEST: return "below_north_west";
         case direction::ABOVENORTH: return "above_north";
         case direction::NORTH: return "north";
         case direction::BELOWNORTH: return "below_north";
         case direction::ABOVENORTHEAST: return "above_north_east";
         case direction::NORTHEAST: return "north_east";
         case direction::BELOWNORTHEAST: return "below_north_east";
         case direction::ABOVEWEST: return "above_west";
         case direction::WEST: return "west";
         case direction::BELOWWEST: return "below_west";
         case direction::ABOVECENTER: return "above";
         case direction::CENTER: return "center";
         case direction::BELOWCENTER: return "below";
         case direction::ABOVEEAST: return "above_east";
         case direction::EAST: return "east";
         case direction::BELOWEAST: return "below_east";
         case direction::ABOVESOUTHWEST: return "above_south_west";
         case direction::SOUTHWEST: return "south_west";
         case direction::BELOWSOUTHWEST: return "below_south_west";
         case direction::ABOVESOUTH: return "above_south";
         case direction::SOUTH: return "south";
         case direction::BELOWSOUTH: return "below_south";
         case direction::ABOVESOUTHEAST: return "above_south_east";
         case direction::SOUTHEAST: return "south_east";
         case direction::BELOWSOUTHEAST: return "below_south_east";
         // *INDENT-ON*
         case direction::last:
             break;
     }
     cata_fatal( "Invalid direction" );
 }
References ABOVECENTER, ABOVEEAST, ABOVENORTH, ABOVENORTHEAST, ABOVENORTHWEST, ABOVESOUTH, ABOVESOUTHEAST, ABOVESOUTHWEST, ABOVEWEST, BELOWCENTER, BELOWEAST, BELOWNORTH, BELOWNORTHEAST, BELOWNORTHWEST, BELOWSOUTH, BELOWSOUTHEAST, BELOWSOUTHWEST, BELOWWEST, cata_fatal, CENTER, EAST, last, NORTH, NORTHEAST, NORTHWEST, SOUTH, SOUTHEAST, SOUTHWEST, and WEST.
enum_to_string< distraction_type >()
template<> std::string io::enum_to_string< distraction_type > (distraction_type data)
Definition at line 61 of file activity_type.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case distraction_type::noise: return "noise";
         case distraction_type::pain: return "pain";
         case distraction_type::attacked: return "attacked";
         case distraction_type::hostile_spotted_far: return "hostile_spotted_far";
         case distraction_type::hostile_spotted_near: return "hostile_spotted_near";
         case distraction_type::talked_to: return "talked_to";
         case distraction_type::asthma: return "asthma";
         case distraction_type::motion_alarm: return "motion_alarm";
         case distraction_type::weather_change: return "weather_change";
         case distraction_type::portal_storm_popup: return "portal_storm_popup";
         case distraction_type::eoc: return "eoc";
         case distraction_type::dangerous_field: return "dangerous_field";
         case distraction_type::hunger: return "hunger";
         case distraction_type::thirst: return "thirst";
         case distraction_type::temperature: return "temperature";
         case distraction_type::mutation: return "mutation";
         case distraction_type::oxygen: return "oxygen";
         // *INDENT-ON*
         default:
             cata_fatal( "Invalid distraction_type in enum_to_string" );
     }
 }
References asthma, attacked, cata_fatal, dangerous_field, eoc, hostile_spotted_far, hostile_spotted_near, hunger, motion_alarm, mutation, noise, oxygen, pain, portal_storm_popup, talked_to, temperature, thirst, and weather_change.
enum_to_string< enchant_vals::mod >()
template<> std::string io::enum_to_string< enchant_vals::mod > (enchant_vals::mod data)
Definition at line 55 of file magic_enchantment.cpp.
     {
         switch ( data ) {
             case enchant_vals::mod::ARTIFACT_RESONANCE: return "ARTIFACT_RESONANCE";
             case enchant_vals::mod::STRENGTH: return "STRENGTH";
             case enchant_vals::mod::DEXTERITY: return "DEXTERITY";
             case enchant_vals::mod::PERCEPTION: return "PERCEPTION";
             case enchant_vals::mod::INTELLIGENCE: return "INTELLIGENCE";
             case enchant_vals::mod::SPEED: return "SPEED";
             case enchant_vals::mod::ATTACK_SPEED: return "ATTACK_SPEED";
             case enchant_vals::mod::MOVE_COST: return "MOVE_COST";
             case enchant_vals::mod::METABOLISM: return "METABOLISM";
             case enchant_vals::mod::MAX_MANA: return "MAX_MANA";
             case enchant_vals::mod::REGEN_MANA: return "REGEN_MANA";
             case enchant_vals::mod::BIONIC_POWER: return "BIONIC_POWER";
             case enchant_vals::mod::POWER_TRICKLE: return "POWER_TRICKLE";
             case enchant_vals::mod::MAX_STAMINA: return "MAX_STAMINA";
             case enchant_vals::mod::REGEN_STAMINA: return "REGEN_STAMINA";
             case enchant_vals::mod::FAT_TO_MAX_HP: return "FAT_TO_MAX_HP";
             case enchant_vals::mod::CARDIO_MULTIPLIER: return "CARDIO_MULTIPLIER";
             case enchant_vals::mod::MAX_HP: return "MAX_HP";
             case enchant_vals::mod::REGEN_HP: return "REGEN_HP";
             case enchant_vals::mod::REGEN_HP_AWAKE: return "REGEN_HP_AWAKE";
             case enchant_vals::mod::HUNGER: return "HUNGER";
             case enchant_vals::mod::THIRST: return "THIRST";
             case enchant_vals::mod::SLEEPINESS: return "SLEEPINESS";
             case enchant_vals::mod::SLEEPINESS_REGEN: return "SLEEPINESS_REGEN";
             case enchant_vals::mod::PAIN: return "PAIN";
             case enchant_vals::mod::PAIN_REMOVE: return "PAIN_REMOVE";
             case enchant_vals::mod::PAIN_PENALTY_MOD_STR: return "PAIN_PENALTY_MOD_STR";
             case enchant_vals::mod::PAIN_PENALTY_MOD_DEX: return "PAIN_PENALTY_MOD_DEX";
             case enchant_vals::mod::PAIN_PENALTY_MOD_INT: return "PAIN_PENALTY_MOD_INT";
             case enchant_vals::mod::PAIN_PENALTY_MOD_PER: return "PAIN_PENALTY_MOD_PER";
             case enchant_vals::mod::PAIN_PENALTY_MOD_SPEED: return "PAIN_PENALTY_MOD_SPEED";
             case enchant_vals::mod::MELEE_DAMAGE: return "MELEE_DAMAGE";
             case enchant_vals::mod::RANGED_DAMAGE: return "RANGED_DAMAGE";
             case enchant_vals::mod::DODGE_CHANCE: return "DODGE_CHANCE";
             case enchant_vals::mod::BONUS_BLOCK: return "BONUS_BLOCK";
             case enchant_vals::mod::BONUS_DODGE: return "BONUS_DODGE";
             case enchant_vals::mod::ATTACK_NOISE: return "ATTACK_NOISE";
             case enchant_vals::mod::SHOUT_NOISE: return "SHOUT_NOISE";
             case enchant_vals::mod::FOOTSTEP_NOISE: return "FOOTSTEP_NOISE";
             case enchant_vals::mod::SIGHT_RANGE_ELECTRIC: return "SIGHT_RANGE_ELECTRIC";
             case enchant_vals::mod::MOTION_VISION_RANGE: return "MOTION_VISION_RANGE";
             case enchant_vals::mod::SIGHT_RANGE_FAE: return "SIGHT_RANGE_FAE";
             case enchant_vals::mod::SIGHT_RANGE_NETHER: return "SIGHT_RANGE_NETHER";
             case enchant_vals::mod::SIGHT_RANGE_MINDS: return "SIGHT_RANGE_MINDS";
             case enchant_vals::mod::CARRY_WEIGHT: return "CARRY_WEIGHT";
             case enchant_vals::mod::WEAPON_DISPERSION: return "WEAPON_DISPERSION";
             case enchant_vals::mod::SOCIAL_LIE: return "SOCIAL_LIE";
             case enchant_vals::mod::SOCIAL_PERSUADE: return "SOCIAL_PERSUADE";
             case enchant_vals::mod::SOCIAL_INTIMIDATE: return "SOCIAL_INTIMIDATE";
             case enchant_vals::mod::SLEEPY: return "SLEEPY";
             case enchant_vals::mod::BODYTEMP_SLEEP: return "BODYTEMP_SLEEP";
             case enchant_vals::mod::LUMINATION: return "LUMINATION";
             case enchant_vals::mod::EFFECTIVE_HEALTH_MOD: return "EFFECTIVE_HEALTH_MOD";
             case enchant_vals::mod::MOD_HEALTH: return "MOD_HEALTH";
             case enchant_vals::mod::MOD_HEALTH_CAP: return "MOD_HEALTH_CAP";
             case enchant_vals::mod::HEALTHY_RATE: return "HEALTHY_RATE";
             case enchant_vals::mod::READING_EXP: return "READING_EXP";
             case enchant_vals::mod::SKILL_RUST_RESIST: return "SKILL_RUST_RESIST";
             case enchant_vals::mod::OVERMAP_SIGHT: return "OVERMAP_SIGHT";
             case enchant_vals::mod::READING_SPEED_MULTIPLIER: return "READING_SPEED_MULTIPLIER";
             case enchant_vals::mod::KCAL: return "KCAL";
             case enchant_vals::mod::VITAMIN_ABSORB_MOD: return "VITAMIN_ABSORB_MOD";
             case enchant_vals::mod::MELEE_STAMINA_CONSUMPTION: return "MELEE_STAMINA_CONSUMPTION";
             case enchant_vals::mod::OBTAIN_COST_MULTIPLIER: return "OBTAIN_COST_MULTIPLIER";
             case enchant_vals::mod::CASTING_TIME_MULTIPLIER: return "CASTING_TIME_MULTIPLIER";
             case enchant_vals::mod::CRAFTING_SPEED_MULTIPLIER: return "CRAFTING_SPEED_MULTIPLIER";
             case enchant_vals::mod::BIONIC_MANA_PENALTY: return "BIONIC_MANA_PENALTY";
             case enchant_vals::mod::STEALTH_MODIFIER: return "STEALTH_MODIFIER";
             case enchant_vals::mod::WEAKNESS_TO_WATER: return "WEAKNESS_TO_WATER";
             case enchant_vals::mod::MENDING_MODIFIER: return "MENDING_MODIFIER";
             case enchant_vals::mod::STOMACH_SIZE_MULTIPLIER: return "STOMACH_SIZE_MULTIPLIER";
             case enchant_vals::mod::LEARNING_FOCUS: return "LEARNING_FOCUS";
             case enchant_vals::mod::RECOIL_MODIFIER: return "RECOIL_MODIFIER";
             case enchant_vals::mod::ARMOR_ALL: return "ARMOR_ALL";
             case enchant_vals::mod::ARMOR_ACID: return "ARMOR_ACID";
             case enchant_vals::mod::ARMOR_BASH: return "ARMOR_BASH";
             case enchant_vals::mod::ARMOR_BIO: return "ARMOR_BIO";
             case enchant_vals::mod::ARMOR_COLD: return "ARMOR_COLD";
             case enchant_vals::mod::ARMOR_CUT: return "ARMOR_CUT";
             case enchant_vals::mod::ARMOR_ELEC: return "ARMOR_ELEC";
             case enchant_vals::mod::ARMOR_HEAT: return "ARMOR_HEAT";
             case enchant_vals::mod::ARMOR_STAB: return "ARMOR_STAB";
             case enchant_vals::mod::ARMOR_BULLET: return "ARMOR_BULLET";
             case enchant_vals::mod::EXTRA_BASH: return "EXTRA_BASH";
             case enchant_vals::mod::EXTRA_CUT: return "EXTRA_CUT";
             case enchant_vals::mod::EXTRA_STAB: return "EXTRA_STAB";
             case enchant_vals::mod::EXTRA_BULLET: return "EXTRA_BULLET";
             case enchant_vals::mod::EXTRA_HEAT: return "EXTRA_HEAT";
             case enchant_vals::mod::EXTRA_COLD: return "EXTRA_COLD";
             case enchant_vals::mod::EXTRA_ELEC: return "EXTRA_ELEC";
             case enchant_vals::mod::EXTRA_ACID: return "EXTRA_ACID";
             case enchant_vals::mod::EXTRA_BIO: return "EXTRA_BIO";
             case enchant_vals::mod::EXTRA_ELEC_PAIN: return "EXTRA_ELEC_PAIN";
             case enchant_vals::mod::ITEM_DAMAGE_PURE: return "ITEM_DAMAGE_PURE";
             case enchant_vals::mod::ITEM_DAMAGE_BASH: return "ITEM_DAMAGE_BASH";
             case enchant_vals::mod::ITEM_DAMAGE_CUT: return "ITEM_DAMAGE_CUT";
             case enchant_vals::mod::ITEM_DAMAGE_STAB: return "ITEM_DAMAGE_STAB";
             case enchant_vals::mod::ITEM_DAMAGE_BULLET: return "ITEM_DAMAGE_BULLET";
             case enchant_vals::mod::ITEM_DAMAGE_HEAT: return "ITEM_DAMAGE_HEAT";
             case enchant_vals::mod::ITEM_DAMAGE_COLD: return "ITEM_DAMAGE_COLD";
             case enchant_vals::mod::ITEM_DAMAGE_ELEC: return "ITEM_DAMAGE_ELEC";
             case enchant_vals::mod::ITEM_DAMAGE_ACID: return "ITEM_DAMAGE_ACID";
             case enchant_vals::mod::ITEM_DAMAGE_BIO: return "ITEM_DAMAGE_BIO";
             case enchant_vals::mod::ITEM_ARMOR_BASH: return "ITEM_ARMOR_BASH";
             case enchant_vals::mod::ITEM_ARMOR_CUT: return "ITEM_ARMOR_CUT";
             case enchant_vals::mod::ITEM_ARMOR_STAB: return "ITEM_ARMOR_STAB";
             case enchant_vals::mod::ITEM_ARMOR_BULLET: return "ITEM_ARMOR_BULLET";
             case enchant_vals::mod::ITEM_ARMOR_HEAT: return "ITEM_ARMOR_HEAT";
             case enchant_vals::mod::ITEM_ARMOR_COLD: return "ITEM_ARMOR_COLD";
             case enchant_vals::mod::ITEM_ARMOR_ELEC: return "ITEM_ARMOR_ELEC";
             case enchant_vals::mod::ITEM_ARMOR_ACID: return "ITEM_ARMOR_ACID";
             case enchant_vals::mod::ITEM_ARMOR_BIO: return "ITEM_ARMOR_BIO";
             case enchant_vals::mod::ITEM_ATTACK_SPEED: return "ITEM_ATTACK_SPEED";
             case enchant_vals::mod::CLIMATE_CONTROL_HEAT: return "CLIMATE_CONTROL_HEAT";
             case enchant_vals::mod::CLIMATE_CONTROL_CHILL: return "CLIMATE_CONTROL_CHILL";
             case enchant_vals::mod::COMBAT_CATCHUP: return "COMBAT_CATCHUP";
             case enchant_vals::mod::KNOCKBACK_RESIST: return "KNOCKBACK_RESIST";
             case enchant_vals::mod::KNOCKDOWN_RESIST: return "KNOCKDOWN_RESIST";
             case enchant_vals::mod::FALL_DAMAGE: return "FALL_DAMAGE";
             case enchant_vals::mod::FORCEFIELD: return "FORCEFIELD";
             case enchant_vals::mod::EVASION: return "EVASION";
             case enchant_vals::mod::OVERKILL_DAMAGE: return "OVERKILL_DAMAGE";
             case enchant_vals::mod::RANGE: return "RANGE";
             case enchant_vals::mod::AVOID_FRIENDRY_FIRE: return "AVOID_FRIENDRY_FIRE";
             case enchant_vals::mod::MOVECOST_SWIM_MOD: return "MOVECOST_SWIM_MOD";
             case enchant_vals::mod::MOVECOST_OBSTACLE_MOD: return "MOVECOST_OBSTACLE_MOD";
             case enchant_vals::mod::MOVECOST_FLATGROUND_MOD: return "MOVECOST_FLATGROUND_MOD";
             case enchant_vals::mod::SHOUT_NOISE_STR_MULT: return "SHOUT_NOISE_STR_MULT";
             case enchant_vals::mod::NIGHT_VIS: return "NIGHT_VIS";
             case enchant_vals::mod::HEARING_MULT: return "HEARING_MULT";
             case enchant_vals::mod::BANDAGE_BONUS: return "BANDAGE_BONUS";
             case enchant_vals::mod::DISINFECTANT_BONUS: return "DISINFECTANT_BONUS";
             case enchant_vals::mod::BLEED_STOP_BONUS: return "BLEED_STOP_BONUS";
             case enchant_vals::mod::UGLINESS: return "UGLINESS";
             case enchant_vals::mod::VOMIT_MUL: return "VOMIT_MUL";
             case enchant_vals::mod::SCENT_MASK: return "SCENT_MASK";
             case enchant_vals::mod::CONSUME_TIME_MOD: return "CONSUME_TIME_MOD";
             case enchant_vals::mod::SWEAT_MULTIPLIER: return "SWEAT_MULTIPLIER";
             case enchant_vals::mod::STAMINA_REGEN_MOD: return "STAMINA_REGEN_MOD";
             case enchant_vals::mod::MOVEMENT_EXERTION_MODIFIER: return "MOVEMENT_EXERTION_MODIFIER";
             case enchant_vals::mod::NUM_MOD: break;
         }
         cata_fatal( "Invalid enchant_vals::mod" );
     }
References enchant_vals::ARMOR_ACID, enchant_vals::ARMOR_ALL, enchant_vals::ARMOR_BASH, enchant_vals::ARMOR_BIO, enchant_vals::ARMOR_BULLET, enchant_vals::ARMOR_COLD, enchant_vals::ARMOR_CUT, enchant_vals::ARMOR_ELEC, enchant_vals::ARMOR_HEAT, enchant_vals::ARMOR_STAB, enchant_vals::ARTIFACT_RESONANCE, enchant_vals::ATTACK_NOISE, enchant_vals::ATTACK_SPEED, enchant_vals::AVOID_FRIENDRY_FIRE, enchant_vals::BANDAGE_BONUS, enchant_vals::BIONIC_MANA_PENALTY, enchant_vals::BIONIC_POWER, enchant_vals::BLEED_STOP_BONUS, enchant_vals::BODYTEMP_SLEEP, enchant_vals::BONUS_BLOCK, enchant_vals::BONUS_DODGE, enchant_vals::CARDIO_MULTIPLIER, enchant_vals::CARRY_WEIGHT, enchant_vals::CASTING_TIME_MULTIPLIER, cata_fatal, enchant_vals::CLIMATE_CONTROL_CHILL, enchant_vals::CLIMATE_CONTROL_HEAT, enchant_vals::COMBAT_CATCHUP, enchant_vals::CONSUME_TIME_MOD, enchant_vals::CRAFTING_SPEED_MULTIPLIER, enchant_vals::DEXTERITY, enchant_vals::DISINFECTANT_BONUS, enchant_vals::DODGE_CHANCE, enchant_vals::EFFECTIVE_HEALTH_MOD, enchant_vals::EVASION, enchant_vals::EXTRA_ACID, enchant_vals::EXTRA_BASH, enchant_vals::EXTRA_BIO, enchant_vals::EXTRA_BULLET, enchant_vals::EXTRA_COLD, enchant_vals::EXTRA_CUT, enchant_vals::EXTRA_ELEC, enchant_vals::EXTRA_ELEC_PAIN, enchant_vals::EXTRA_HEAT, enchant_vals::EXTRA_STAB, enchant_vals::FALL_DAMAGE, enchant_vals::FAT_TO_MAX_HP, enchant_vals::FOOTSTEP_NOISE, enchant_vals::FORCEFIELD, enchant_vals::HEALTHY_RATE, enchant_vals::HEARING_MULT, enchant_vals::HUNGER, enchant_vals::INTELLIGENCE, enchant_vals::ITEM_ARMOR_ACID, enchant_vals::ITEM_ARMOR_BASH, enchant_vals::ITEM_ARMOR_BIO, enchant_vals::ITEM_ARMOR_BULLET, enchant_vals::ITEM_ARMOR_COLD, enchant_vals::ITEM_ARMOR_CUT, enchant_vals::ITEM_ARMOR_ELEC, enchant_vals::ITEM_ARMOR_HEAT, enchant_vals::ITEM_ARMOR_STAB, enchant_vals::ITEM_ATTACK_SPEED, enchant_vals::ITEM_DAMAGE_ACID, enchant_vals::ITEM_DAMAGE_BASH, enchant_vals::ITEM_DAMAGE_BIO, enchant_vals::ITEM_DAMAGE_BULLET, enchant_vals::ITEM_DAMAGE_COLD, enchant_vals::ITEM_DAMAGE_CUT, enchant_vals::ITEM_DAMAGE_ELEC, enchant_vals::ITEM_DAMAGE_HEAT, enchant_vals::ITEM_DAMAGE_PURE, enchant_vals::ITEM_DAMAGE_STAB, enchant_vals::KCAL, enchant_vals::KNOCKBACK_RESIST, enchant_vals::KNOCKDOWN_RESIST, enchant_vals::LEARNING_FOCUS, enchant_vals::LUMINATION, enchant_vals::MAX_HP, enchant_vals::MAX_MANA, enchant_vals::MAX_STAMINA, enchant_vals::MELEE_DAMAGE, enchant_vals::MELEE_STAMINA_CONSUMPTION, enchant_vals::MENDING_MODIFIER, enchant_vals::METABOLISM, enchant_vals::MOD_HEALTH, enchant_vals::MOD_HEALTH_CAP, enchant_vals::MOTION_VISION_RANGE, enchant_vals::MOVE_COST, enchant_vals::MOVECOST_FLATGROUND_MOD, enchant_vals::MOVECOST_OBSTACLE_MOD, enchant_vals::MOVECOST_SWIM_MOD, enchant_vals::MOVEMENT_EXERTION_MODIFIER, enchant_vals::NIGHT_VIS, enchant_vals::NUM_MOD, enchant_vals::OBTAIN_COST_MULTIPLIER, enchant_vals::OVERKILL_DAMAGE, enchant_vals::OVERMAP_SIGHT, enchant_vals::PAIN, enchant_vals::PAIN_PENALTY_MOD_DEX, enchant_vals::PAIN_PENALTY_MOD_INT, enchant_vals::PAIN_PENALTY_MOD_PER, enchant_vals::PAIN_PENALTY_MOD_SPEED, enchant_vals::PAIN_PENALTY_MOD_STR, enchant_vals::PAIN_REMOVE, enchant_vals::PERCEPTION, enchant_vals::POWER_TRICKLE, enchant_vals::RANGE, enchant_vals::RANGED_DAMAGE, enchant_vals::READING_EXP, enchant_vals::READING_SPEED_MULTIPLIER, enchant_vals::RECOIL_MODIFIER, enchant_vals::REGEN_HP, enchant_vals::REGEN_HP_AWAKE, enchant_vals::REGEN_MANA, enchant_vals::REGEN_STAMINA, enchant_vals::SCENT_MASK, enchant_vals::SHOUT_NOISE, enchant_vals::SHOUT_NOISE_STR_MULT, enchant_vals::SIGHT_RANGE_ELECTRIC, enchant_vals::SIGHT_RANGE_FAE, enchant_vals::SIGHT_RANGE_MINDS, enchant_vals::SIGHT_RANGE_NETHER, enchant_vals::SKILL_RUST_RESIST, enchant_vals::SLEEPINESS, enchant_vals::SLEEPINESS_REGEN, enchant_vals::SLEEPY, enchant_vals::SOCIAL_INTIMIDATE, enchant_vals::SOCIAL_LIE, enchant_vals::SOCIAL_PERSUADE, enchant_vals::SPEED, enchant_vals::STAMINA_REGEN_MOD, enchant_vals::STEALTH_MODIFIER, enchant_vals::STOMACH_SIZE_MULTIPLIER, enchant_vals::STRENGTH, enchant_vals::SWEAT_MULTIPLIER, enchant_vals::THIRST, enchant_vals::UGLINESS, enchant_vals::VITAMIN_ABSORB_MOD, enchant_vals::VOMIT_MUL, enchant_vals::WEAKNESS_TO_WATER, and enchant_vals::WEAPON_DISPERSION.
enum_to_string< enchantment::condition >()
template<> std::string io::enum_to_string< enchantment::condition > (enchantment::condition data)
Definition at line 42 of file magic_enchantment.cpp.
     {
         switch ( data ) {
         case enchantment::condition::ALWAYS: return "ALWAYS";
         case enchantment::condition::ACTIVE: return "ACTIVE";
         case enchantment::condition::INACTIVE: return "INACTIVE";
         case enchantment::condition::DIALOG_CONDITION: return "DIALOG_CONDITION";
         case enchantment::condition::NUM_CONDITION: break;
         }
         cata_fatal( "Invalid enchantment::condition" );
     }
References cata_fatal.
enum_to_string< enchantment::has >()
template<> std::string io::enum_to_string< enchantment::has > (enchantment::has data)
Definition at line 30 of file magic_enchantment.cpp.
     {
         switch ( data ) {
         case enchantment::has::HELD: return "HELD";
         case enchantment::has::WIELD: return "WIELD";
         case enchantment::has::WORN: return "WORN";
         case enchantment::has::NUM_HAS: break;
         }
         cata_fatal( "Invalid enchantment::has" );
     }
References cata_fatal, and WIELD.
enum_to_string< encumbrance_modifier >()
template<> std::string io::enum_to_string< encumbrance_modifier > (encumbrance_modifier data)
Definition at line 3922 of file item_factory.cpp.
 {
     switch( data ) {
         case encumbrance_modifier::IMBALANCED:
             return "IMBALANCED";
         case encumbrance_modifier::RESTRICTS_NECK:
             return "RESTRICTS_NECK";
         case encumbrance_modifier::WELL_SUPPORTED:
             return "WELL_SUPPORTED";
         case encumbrance_modifier::NONE:
             return "NONE";
         case encumbrance_modifier::last:
             break;
     }
     cata_fatal( "Invalid encumbrance descriptor" );
 }
References cata_fatal, IMBALANCED, last, NONE, RESTRICTS_NECK, and WELL_SUPPORTED.
enum_to_string< eoc_type >()
template<> std::string io::enum_to_string< eoc_type > (eoc_type data)
Definition at line 37 of file effect_on_condition.cpp.
     {
         switch ( data ) {
         case eoc_type::ACTIVATION: return "ACTIVATION";
         case eoc_type::RECURRING: return "RECURRING";
         case eoc_type::SCENARIO_SPECIFIC: return "SCENARIO_SPECIFIC";
         case eoc_type::AVATAR_DEATH: return "AVATAR_DEATH";
         case eoc_type::NPC_DEATH: return "NPC_DEATH";
         case eoc_type::OM_MOVE: return "OM_MOVE";
         case eoc_type::PREVENT_DEATH: return "PREVENT_DEATH";
         case eoc_type::EVENT: return "EVENT";
         case eoc_type::NUM_EOC_TYPES: break;
         }
         cata_fatal( "Invalid eoc_type" );
     }
References ACTIVATION, AVATAR_DEATH, cata_fatal, EVENT, NPC_DEATH, NUM_EOC_TYPES, OM_MOVE, PREVENT_DEATH, RECURRING, and SCENARIO_SPECIFIC.
enum_to_string< event_type >()
template<> std::string io::enum_to_string< event_type > (event_type data)
Definition at line 11 of file event.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case event_type::activates_artifact: return "activates_artifact";
         case event_type::activates_mininuke: return "activates_mininuke";
         case event_type::administers_mutagen: return "administers_mutagen";
         case event_type::angers_amigara_horrors: return "angers_amigara_horrors";
         case event_type::avatar_enters_omt: return "avatar_enters_omt";
         case event_type::avatar_moves: return "avatar_moves";
         case event_type::avatar_dies: return "avatar_dies";
         case event_type::awakes_dark_wyrms: return "awakes_dark_wyrms";
         case event_type::becomes_wanted: return "becomes_wanted";
         case event_type::broken_bone: return "broken_bone";
         case event_type::broken_bone_mends: return "broken_bone_mends";
         case event_type::buries_corpse: return "buries_corpse";
         case event_type::causes_resonance_cascade: return "causes_resonance_cascade";
         case event_type::character_consumes_item: return "character_consumes_item";
         case event_type::character_dies: return "character_dies";
         case event_type::character_eats_item: return "character_eats_item";
         case event_type::character_casts_spell: return "character_casts_spell";
         case event_type::character_finished_activity: return "character_finished_activity";
         case event_type::character_forgets_spell: return "character_forgets_spell";
         case event_type::character_gains_effect: return "character_gains_effect";
         case event_type::character_gets_headshot: return "character_gets_headshot";
         case event_type::character_heals_damage: return "character_heals_damage";
         case event_type::character_kills_character: return "character_kills_character";
         case event_type::character_kills_monster: return "character_kills_monster";
         case event_type::character_learns_spell: return "character_learns_spell";
         case event_type::character_loses_effect: return "character_loses_effect";
         case event_type::character_melee_attacks_character:
                                                  return "character_melee_attacks_character";
         case event_type::character_melee_attacks_monster:
                                                  return "character_melee_attacks_monster";
         case event_type::character_ranged_attacks_character:
                                                  return "character_ranged_attacks_character";
         case event_type::character_ranged_attacks_monster:
                                                  return "character_ranged_attacks_monster";
         case event_type::character_smashes_tile: return "character_smashes_tile";
         case event_type::character_starts_activity: return "character_starts_activity";
         case event_type::character_takes_damage: return "character_takes_damage";
         case event_type::character_triggers_trap: return "character_triggers_trap";
         case event_type::character_falls_asleep: return "character_falls_asleep";
         case event_type::character_attempt_to_fall_asleep: return "character_attempt_to_fall_asleep";
         case event_type::character_wakes_up: return "character_wakes_up";
         case event_type::character_wears_item: return "character_wears_item";
         case event_type::character_wields_item: return "character_wields_item";
         case event_type::consumes_marloss_item: return "consumes_marloss_item";
         case event_type::crosses_marloss_threshold: return "crosses_marloss_threshold";
         case event_type::crosses_mutation_threshold: return "crosses_mutation_threshold";
         case event_type::crosses_mycus_threshold: return "crosses_mycus_threshold";
         case event_type::cuts_tree: return "cuts_tree";
         case event_type::dermatik_eggs_hatch: return "dermatik_eggs_hatch";
         case event_type::dermatik_eggs_injected: return "dermatik_eggs_injected";
         case event_type::destroys_triffid_grove: return "destroys_triffid_grove";
         case event_type::dies_from_asthma_attack: return "dies_from_asthma_attack";
         case event_type::dies_from_drug_overdose: return "dies_from_drug_overdose";
         case event_type::dies_from_bleeding: return "dies_from_bleeding";
         case event_type::dies_from_hypovolemia: return "dies_from_hypovolemia";
         case event_type::dies_from_redcells_loss: return "dies_from_redcells_loss";
         case event_type::dies_of_infection: return "dies_of_infection";
         case event_type::dies_of_starvation: return "dies_of_starvation";
         case event_type::dies_of_thirst: return "dies_of_thirst";
         case event_type::digs_into_lava: return "digs_into_lava";
         case event_type::disarms_nuke: return "disarms_nuke";
         case event_type::eats_sewage: return "eats_sewage";
         case event_type::evolves_mutation: return "evolves_mutation";
         case event_type::exhumes_grave: return "exhumes_grave";
         case event_type::fails_to_install_cbm: return "fails_to_install_cbm";
         case event_type::fails_to_remove_cbm: return "fails_to_remove_cbm";
         case event_type::falls_asleep_from_exhaustion: return "falls_asleep_from_exhaustion";
         case event_type::fuel_tank_explodes: return "fuel_tank_explodes";
         case event_type::gains_addiction: return "gains_addiction";
         case event_type::gains_mutation: return "gains_mutation";
         case event_type::gains_proficiency: return "gains_proficiency";
         case event_type::gains_skill_level: return "gains_skill_level";
         case event_type::game_avatar_death: return "game_avatar_death";
         case event_type::game_avatar_new: return "game_avatar_new";
         case event_type::game_load: return "game_load";
         case event_type::game_begin: return "game_begin";
         case event_type::game_over: return "game_over";
         case event_type::game_save: return "game_save";
         case event_type::game_start: return "game_start";
         case event_type::installs_cbm: return "installs_cbm";
         case event_type::installs_faulty_cbm: return "installs_faulty_cbm";
         case event_type::learns_martial_art: return "learns_martial_art";
         case event_type::loses_addiction: return "loses_addiction";
         case event_type::loses_mutation: return "loses_mutation";
         case event_type::npc_becomes_hostile: return "npc_becomes_hostile";
         case event_type::opens_portal: return "opens_portal";
         case event_type::opens_spellbook: return "opens_spellbook";
         case event_type::opens_temple: return "opens_temple";
         case event_type::player_fails_conduct: return "player_fails_conduct";
         case event_type::player_gets_achievement: return "player_gets_achievement";
         case event_type::player_levels_spell: return "player_levels_spell";
         case event_type::reads_book: return "reads_book";
         case event_type::releases_subspace_specimens: return "releases_subspace_specimens";
         case event_type::removes_cbm: return "removes_cbm";
         case event_type::seals_hazardous_material_sarcophagus: return "seals_hazardous_material_sarcophagus";
         case event_type::spellcasting_finish: return "spellcasting_finish";
         case event_type::telefrags_creature: return "telefrags_creature";
         case event_type::teleglow_teleports: return "teleglow_teleports";
         case event_type::teleports_into_wall: return "teleports_into_wall";
         case event_type::terminates_subspace_specimens: return "terminates_subspace_specimens";
         case event_type::throws_up: return "throws_up";
         case event_type::triggers_alarm: return "triggers_alarm";
         case event_type::uses_debug_menu: return "uses_debug_menu";
         case event_type::u_var_changed: return "u_var_changed";
         case event_type::vehicle_moves: return "vehicle_moves";
         case event_type::character_butchered_corpse: return "character_butchered_corpse";
         // *INDENT-ON*
         case event_type::num_event_types:
             break;
     }
     cata_fatal( "Invalid event_type" );
 }
References activates_artifact, activates_mininuke, administers_mutagen, angers_amigara_horrors, avatar_dies, avatar_enters_omt, avatar_moves, awakes_dark_wyrms, becomes_wanted, broken_bone, broken_bone_mends, buries_corpse, cata_fatal, causes_resonance_cascade, character_attempt_to_fall_asleep, character_butchered_corpse, character_casts_spell, character_consumes_item, character_dies, character_eats_item, character_falls_asleep, character_finished_activity, character_forgets_spell, character_gains_effect, character_gets_headshot, character_heals_damage, character_kills_character, character_kills_monster, character_learns_spell, character_loses_effect, character_melee_attacks_character, character_melee_attacks_monster, character_ranged_attacks_character, character_ranged_attacks_monster, character_smashes_tile, character_starts_activity, character_takes_damage, character_triggers_trap, character_wakes_up, character_wears_item, character_wields_item, consumes_marloss_item, crosses_marloss_threshold, crosses_mutation_threshold, crosses_mycus_threshold, cuts_tree, dermatik_eggs_hatch, dermatik_eggs_injected, destroys_triffid_grove, dies_from_asthma_attack, dies_from_bleeding, dies_from_drug_overdose, dies_from_hypovolemia, dies_from_redcells_loss, dies_of_infection, dies_of_starvation, dies_of_thirst, digs_into_lava, disarms_nuke, eats_sewage, evolves_mutation, exhumes_grave, fails_to_install_cbm, fails_to_remove_cbm, falls_asleep_from_exhaustion, fuel_tank_explodes, gains_addiction, gains_mutation, gains_proficiency, gains_skill_level, game_avatar_death, game_avatar_new, game_begin, game_load, game_over, game_save, game_start, installs_cbm, installs_faulty_cbm, learns_martial_art, loses_addiction, loses_mutation, npc_becomes_hostile, num_event_types, opens_portal, opens_spellbook, opens_temple, player_fails_conduct, player_gets_achievement, player_levels_spell, reads_book, releases_subspace_specimens, removes_cbm, seals_hazardous_material_sarcophagus, spellcasting_finish, telefrags_creature, teleglow_teleports, teleports_into_wall, terminates_subspace_specimens, throws_up, triggers_alarm, u_var_changed, uses_debug_menu, and vehicle_moves.
enum_to_string< game_message_type >()
template<> std::string io::enum_to_string< game_message_type > (game_message_type data)
Definition at line 66 of file field_type.cpp.
 {
     switch( data ) {
             // *INDENT-OFF*
         case game_message_type::m_good: return "good";
         case game_message_type::m_bad: return "bad";
         case game_message_type::m_mixed: return "mixed";
         case game_message_type::m_warning: return "warning";
         case game_message_type::m_info: return "info";
         case game_message_type::m_neutral: return "neutral";
         case game_message_type::m_debug: return "debug";
         case game_message_type::m_headshot: return "headshot";
         case game_message_type::m_critical: return "critical";
         case game_message_type::m_grazing: return "grazing";
             // *INDENT-ON*
         case game_message_type::num_game_message_type:
             break;
     }
     cata_fatal( "Invalid game_message_type" );
 }
References cata_fatal, m_bad, m_critical, m_debug, m_good, m_grazing, m_headshot, m_info, m_mixed, m_neutral, m_warning, and num_game_message_type.
enum_to_string< grip_val >()
template<> std::string io::enum_to_string< grip_val > (grip_val val)
Definition at line 3977 of file item_factory.cpp.
 {
     switch( val ) {
         case grip_val::BAD: return "bad";
         case grip_val::NONE: return "none";
         case grip_val::SOLID: return "solid";
         case grip_val::WEAPON: return "weapon";
         default: break;
     }
     cata_fatal( "Invalid grip val" );
 }
References BAD, cata_fatal, NONE, SOLID, and WEAPON.
enum_to_string< inventory_selector::uimode >()
template<> std::string io::enum_to_string< inventory_selector::uimode > (inventory_selector::uimode mode)
Definition at line 306 of file inventory_ui.cpp.
 {
     switch( mode ) {
         case inventory_selector::uimode::hierarchy:
             return "hierarchy";
         case inventory_selector::uimode::last:
         case inventory_selector::uimode::categories:
             break;
     }
     return "categories";
 }
References inventory_selector::categories, inventory_selector::hierarchy, and inventory_selector::last.
enum_to_string< Item_spawn_data::overflow_behaviour >()
template<> std::string io::enum_to_string< Item_spawn_data::overflow_behaviour > (Item_spawn_data::overflow_behaviour data)
Definition at line 78 of file item_group.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case Item_spawn_data::overflow_behaviour::none: return "none";
         case Item_spawn_data::overflow_behaviour::spill: return "spill";
         case Item_spawn_data::overflow_behaviour::discard: return "discard";
         // *INDENT-ON*
         case Item_spawn_data::overflow_behaviour::last:
             break;
     }
     cata_fatal( "Invalid overflow_behaviour" );
 }
References cata_fatal, Item_spawn_data::discard, Item_spawn_data::last, Item_spawn_data::none, and Item_spawn_data::spill.
enum_to_string< itype_variant_kind >()
template<> std::string io::enum_to_string< itype_variant_kind > (itype_variant_kind data)
Definition at line 58 of file itype.cpp.
 {
     switch( data ) {
         case itype_variant_kind::gun:
             return "gun";
         case itype_variant_kind::generic:
             return "generic";
         case itype_variant_kind::drug:
             return "drug";
         case itype_variant_kind::last:
             debugmsg( "Invalid variant type!" );
             return "";
     }
     return "";
 }
References debugmsg, drug, generic, gun, and last.
enum_to_string< jmapgen_flags >()
template<> std::string io::enum_to_string< jmapgen_flags > (jmapgen_flags v)
Definition at line 1568 of file mapgen.cpp.
 {
     switch( v ) {
         // *INDENT-OFF*
         case jmapgen_flags::allow_terrain_under_other_data: return "ALLOW_TERRAIN_UNDER_OTHER_DATA";
         case jmapgen_flags::dismantle_all_before_placing_terrain:
             return "DISMANTLE_ALL_BEFORE_PLACING_TERRAIN";
         case jmapgen_flags::erase_all_before_placing_terrain:
             return "ERASE_ALL_BEFORE_PLACING_TERRAIN";
         case jmapgen_flags::allow_terrain_under_furniture: return "ALLOW_TERRAIN_UNDER_FURNITURE";
         case jmapgen_flags::dismantle_furniture_before_placing_terrain:
             return "DISMANTLE_FURNITURE_BEFORE_PLACING_TERRAIN";
         case jmapgen_flags::erase_furniture_before_placing_terrain:
             return "ERASE_FURNITURE_BEFORE_PLACING_TERRAIN";
         case jmapgen_flags::allow_terrain_under_trap: return "ALLOW_TERRAIN_UNDER_TRAP";
         case jmapgen_flags::dismantle_trap_before_placing_terrain:
             return "DISMANTLE_TRAP_BEFORE_PLACING_TERRAIN";
         case jmapgen_flags::erase_trap_before_placing_terrain:
             return "ERASE_TRAP_BEFORE_PLACING_TERRAIN";
         case jmapgen_flags::allow_terrain_under_items: return "ALLOW_TERRAIN_UNDER_ITEMS";
         case jmapgen_flags::erase_items_before_placing_terrain:
             return "ERASE_ITEMS_BEFORE_PLACING_TERRAIN";
         case jmapgen_flags::no_underlying_rotate: return "NO_UNDERLYING_ROTATE";
         case jmapgen_flags::avoid_creatures: return "AVOID_CREATURES";
         // *INDENT-ON*
         case jmapgen_flags::last:
             break;
     }
     debugmsg( "unknown jmapgen_flags %d", static_cast<int>( v ) );
     return "";
 }
References allow_terrain_under_furniture, allow_terrain_under_items, allow_terrain_under_other_data, allow_terrain_under_trap, avoid_creatures, debugmsg, dismantle_all_before_placing_terrain, dismantle_furniture_before_placing_terrain, dismantle_trap_before_placing_terrain, erase_all_before_placing_terrain, erase_furniture_before_placing_terrain, erase_items_before_placing_terrain, erase_trap_before_placing_terrain, last, and no_underlying_rotate.
enum_to_string< join_type >()
template<> std::string io::enum_to_string< join_type > (join_type data)
Definition at line 1506 of file overmap.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case join_type::mandatory: return "mandatory";
         case join_type::available: return "available";
         // *INDENT-ON*
         case join_type::last:
             break;
     }
     cata_fatal( "Invalid join_type" );
 }
References available, cata_fatal, last, and mandatory.
enum_to_string< layer_level >()
template<> std::string io::enum_to_string< layer_level > (layer_level data)
Definition at line 2899 of file item_factory.cpp.
 {
     switch( data ) {
         case layer_level::PERSONAL:
             return "PERSONAL";
         case layer_level::SKINTIGHT:
             return "SKINTIGHT";
         case layer_level::NORMAL:
             return "NORMAL";
         case layer_level::WAIST:
             return "WAIST";
         case layer_level::OUTER:
             return "OUTER";
         case layer_level::BELTED:
             return "BELTED";
         case layer_level::AURA:
             return "AURA";
         case layer_level::NUM_LAYER_LEVELS:
             break;
     }
     cata_fatal( "Invalid layer_level" );
 }
References AURA, BELTED, cata_fatal, NORMAL, NUM_LAYER_LEVELS, OUTER, PERSONAL, SKINTIGHT, and WAIST.
enum_to_string< length_val >()
template<> std::string io::enum_to_string< length_val > (length_val val)
Definition at line 3990 of file item_factory.cpp.
 {
     switch( val ) {
         case length_val::HAND: return "hand";
         case length_val::SHORT: return "short";
         case length_val::LONG: return "long";
         default: break;
     }
     cata_fatal( "Invalid length val" );
 }
References cata_fatal, HAND, LONG, and SHORT.
enum_to_string< link_state >()
template<> std::string io::enum_to_string< link_state > (link_state data)
Definition at line 3944 of file item_factory.cpp.
 {
     switch( data ) {
         case link_state::no_link:
             return "no_link";
         case link_state::needs_reeling:
             return "needs_reeling";
         case link_state::automatic:
             return "automatic";
         case link_state::vehicle_port:
             return "vehicle_port";
         case link_state::vehicle_battery:
             return "vehicle_battery";
         case link_state::vehicle_tow:
             return "vehicle_tow";
         case link_state::bio_cable:
             return "bio_cable";
         case link_state::ups:
             return "ups";
         case link_state::solarpack:
             return "solarpack";
         case link_state::last:
             break;
     }
     cata_fatal( "Invalid link_state" );
 }
References automatic, bio_cable, cata_fatal, last, needs_reeling, no_link, solarpack, ups, vehicle_battery, vehicle_port, and vehicle_tow.
enum_to_string< magic_energy_type >()
template<> std::string io::enum_to_string< magic_energy_type > (magic_energy_type data)
Definition at line 165 of file magic.cpp.
 {
     switch( data ) {
     case magic_energy_type::bionic: return "BIONIC";
     case magic_energy_type::hp: return "HP";
     case magic_energy_type::mana: return "MANA";
     case magic_energy_type::none: return "NONE";
     case magic_energy_type::stamina: return "STAMINA";
     case magic_energy_type::last: break;
     }
     cata_fatal( "Invalid magic_energy_type" );
 }
References bionic, cata_fatal, hp, last, mana, none, and stamina.
enum_to_string< map_extra_method >()
template<> std::string io::enum_to_string< map_extra_method > (map_extra_method data)
Definition at line 205 of file map_extras.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case map_extra_method::null: return "null";
         case map_extra_method::map_extra_function: return "map_extra_function";
         case map_extra_method::mapgen: return "mapgen";
         case map_extra_method::update_mapgen: return "update_mapgen";
         case map_extra_method::num_map_extra_methods: break;
         // *INDENT-ON*
     }
     cata_fatal( "Invalid map_extra_method" );
 }
References cata_fatal, map_extra_function, mapgen, null, num_map_extra_methods, and update_mapgen.
enum_to_string< mapgen_parameter_scope >()
template<> std::string io::enum_to_string< mapgen_parameter_scope > (mapgen_parameter_scope v)
Definition at line 1601 of file mapgen.cpp.
 {
     switch( v ) {
         // *INDENT-OFF*
         case mapgen_parameter_scope::overmap_special: return "overmap_special";
         case mapgen_parameter_scope::omt: return "omt";
         case mapgen_parameter_scope::nest: return "nest";
         // *INDENT-ON*
         case mapgen_parameter_scope::last:
             break;
     }
     debugmsg( "unknown mapgen_parameter_scope %d", static_cast<int>( v ) );
     return "";
 }
References debugmsg, last, nest, omt, and overmap_special.
enum_to_string< mdeath_type >()
template<> std::string io::enum_to_string< mdeath_type > (mdeath_type data)
Definition at line 85 of file monstergenerator.cpp.
 {
     switch( data ) {
         case mdeath_type::NORMAL:
             return "NORMAL";
         case mdeath_type::SPLATTER:
             return "SPLATTER";
         case mdeath_type::BROKEN:
             return "BROKEN";
         case mdeath_type::NO_CORPSE:
             return "NO_CORPSE";
         case mdeath_type::LAST:
             break;
     }
     cata_fatal( "Invalid mdeath_type" );
 }
References BROKEN, cata_fatal, LAST, NO_CORPSE, NORMAL, and SPLATTER.
enum_to_string< mission::mission_status >()
template<> std::string io::enum_to_string< mission::mission_status > (mission::mission_status data)
Definition at line 895 of file mission.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case mission::mission_status::yet_to_start: return "yet_to_start";
         case mission::mission_status::in_progress: return "in_progress";
         case mission::mission_status::success: return "success";
         case mission::mission_status::failure: return "failure";
         // *INDENT-ON*
         case mission::mission_status::num_mission_status:
             break;
     }
     cata_fatal( "Invalid mission_status" );
 }
References cata_fatal, mission::failure, mission::in_progress, mission::num_mission_status, mission::success, and mission::yet_to_start.
enum_to_string< mission_goal >()
template<> std::string io::enum_to_string< mission_goal > (mission_goal data)
Definition at line 239 of file missiondef.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case MGOAL_NULL: return "MGOAL_NULL";
         case MGOAL_GO_TO: return "MGOAL_GO_TO";
         case MGOAL_GO_TO_TYPE: return "MGOAL_GO_TO_TYPE";
         case MGOAL_FIND_ITEM: return "MGOAL_FIND_ITEM";
         case MGOAL_FIND_ANY_ITEM: return "MGOAL_FIND_ANY_ITEM";
         case MGOAL_FIND_ITEM_GROUP: return "MGOAL_FIND_ITEM_GROUP";
         case MGOAL_FIND_MONSTER: return "MGOAL_FIND_MONSTER";
         case MGOAL_FIND_NPC: return "MGOAL_FIND_NPC";
         case MGOAL_ASSASSINATE: return "MGOAL_ASSASSINATE";
         case MGOAL_KILL_MONSTER: return "MGOAL_KILL_MONSTER";
         case MGOAL_KILL_MONSTERS: return "MGOAL_KILL_MONSTERS";
         case MGOAL_KILL_MONSTER_TYPE: return "MGOAL_KILL_MONSTER_TYPE";
         case MGOAL_KILL_MONSTER_SPEC: return "MGOAL_KILL_MONSTER_SPEC";
         case MGOAL_KILL_NEMESIS: return "MGOAL_KILL_NEMESIS";
         case MGOAL_RECRUIT_NPC: return "MGOAL_RECRUIT_NPC";
         case MGOAL_RECRUIT_NPC_CLASS: return "MGOAL_RECRUIT_NPC_CLASS";
         case MGOAL_COMPUTER_TOGGLE: return "MGOAL_COMPUTER_TOGGLE";
         case MGOAL_TALK_TO_NPC: return "MGOAL_TALK_TO_NPC";
         case MGOAL_CONDITION: return "MGOAL_CONDITION";
         // *INDENT-ON*
         case mission_goal::NUM_MGOAL:
             break;
     }
     cata_fatal( "Invalid mission_goal" );
 }
References cata_fatal, MGOAL_ASSASSINATE, MGOAL_COMPUTER_TOGGLE, MGOAL_CONDITION, MGOAL_FIND_ANY_ITEM, MGOAL_FIND_ITEM, MGOAL_FIND_ITEM_GROUP, MGOAL_FIND_MONSTER, MGOAL_FIND_NPC, MGOAL_GO_TO, MGOAL_GO_TO_TYPE, MGOAL_KILL_MONSTER, MGOAL_KILL_MONSTER_SPEC, MGOAL_KILL_MONSTER_TYPE, MGOAL_KILL_MONSTERS, MGOAL_KILL_NEMESIS, MGOAL_NULL, MGOAL_RECRUIT_NPC, MGOAL_RECRUIT_NPC_CLASS, MGOAL_TALK_TO_NPC, and NUM_MGOAL.
enum_to_string< mission_kind >()
template<> std::string io::enum_to_string< mission_kind > (mission_kind data)
Definition at line 176 of file mission_companion.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case mission_kind::No_Mission: return "No_Mission";
         case mission_kind::Scavenging_Patrol_Job: return "Scavenging_Patrol_Job";
         case mission_kind::Scavenging_Raid_Job: return "Scavenging_Raid_Job";
         case mission_kind::Hospital_Raid_Job: return "Hospital_Raid_Job";
         case mission_kind::Menial_Job: return "Menial_Job";
         case mission_kind::Carpentry_Job: return "Carpentry_Job";
         case mission_kind::Forage_Job: return "Forage_Job";
         case mission_kind::Caravan_Commune_Center_Job: return "Caravan_Commune_Center_Job";
         case mission_kind::Camp_Distribute_Food: return "Camp_Distribute_Food";
         case mission_kind::Camp_Determine_Leadership: return "Camp_Determine_Leadership";
         case mission_kind::Camp_Have_Meal: return "Camp_Have_Meal";
         case mission_kind::Camp_Hide_Mission: return "Camp_Hide_Mission";
         case mission_kind::Camp_Reveal_Mission: return "Camp_Reveal_Mission";
         case mission_kind::Camp_Assign_Jobs: return "Camp_Assign_Jobs";
         case mission_kind::Camp_Assign_Workers: return "Camp_Assign_Workers";
         case mission_kind::Camp_Abandon: return "Camp_Abandon";
         case mission_kind::Camp_Upgrade: return "Camp_Upgrade";
         case mission_kind::Camp_Emergency_Recall: return "Camp_Emergency_Recall";
         case mission_kind::Camp_Crafting: return "Camp_Crafting";
         case mission_kind::Camp_Gather_Materials: return "Camp_Gather_Materials";
         case mission_kind::Camp_Collect_Firewood: return "Camp_Collect_Firewood";
         case mission_kind::Camp_Menial: return "Camp_Menial";
         case mission_kind::Camp_Survey_Field: return "Camp_Survey_Field";
         case mission_kind::Camp_Survey_Expansion: return "Camp_Survey_Expansion";
         case mission_kind::Camp_Cut_Logs: return "Camp_Cut_Logs";
         case mission_kind::Camp_Clearcut: return "Camp_Clearcut";
         case mission_kind::Camp_Setup_Hide_Site: return "Camp_Setup_Hide_Site";
         case mission_kind::Camp_Relay_Hide_Site: return "Camp_Relay_Hide_Site";
         case mission_kind::Camp_Foraging: return "Camp_Foraging";
         case mission_kind::Camp_Trapping: return "Camp_Trapping";
         case mission_kind::Camp_Hunting: return "Camp_Hunting";
         case mission_kind::Camp_OM_Fortifications: return "Camp_OM_Fortifications";
         case mission_kind::Camp_Recruiting: return "Camp_Recruiting";
         case mission_kind::Camp_Scouting: return "Camp_Scouting";
         case mission_kind::Camp_Combat_Patrol: return "Camp_Combat_Patrol";
         case mission_kind::Camp_Chop_Shop: return "Camp_Chop_Shop";
         case mission_kind::Camp_Plow: return "Camp_Plow";
         case mission_kind::Camp_Plant: return "Camp_Plant";
         case mission_kind::Camp_Harvest: return "Camp_Harvest";
         // *INDENT-ON*
         case mission_kind::last_mission_kind:
             break;
     }
     cata_fatal( "Invalid event_type" );
 }
References Camp_Abandon, Camp_Assign_Jobs, Camp_Assign_Workers, Camp_Chop_Shop, Camp_Clearcut, Camp_Collect_Firewood, Camp_Combat_Patrol, Camp_Crafting, Camp_Cut_Logs, Camp_Determine_Leadership, Camp_Distribute_Food, Camp_Emergency_Recall, Camp_Foraging, Camp_Gather_Materials, Camp_Harvest, Camp_Have_Meal, Camp_Hide_Mission, Camp_Hunting, Camp_Menial, Camp_OM_Fortifications, Camp_Plant, Camp_Plow, Camp_Recruiting, Camp_Relay_Hide_Site, Camp_Reveal_Mission, Camp_Scouting, Camp_Setup_Hide_Site, Camp_Survey_Expansion, Camp_Survey_Field, Camp_Trapping, Camp_Upgrade, Caravan_Commune_Center_Job, Carpentry_Job, cata_fatal, Forage_Job, Hospital_Raid_Job, last_mission_kind, Menial_Job, No_Mission, Scavenging_Patrol_Job, and Scavenging_Raid_Job.
enum_to_string< mission_origin >()
template<> std::string io::enum_to_string< mission_origin > (mission_origin data)
Definition at line 221 of file missiondef.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case ORIGIN_NULL: return "ORIGIN_NULL";
         case ORIGIN_GAME_START: return "ORIGIN_GAME_START";
         case ORIGIN_OPENER_NPC: return "ORIGIN_OPENER_NPC";
         case ORIGIN_ANY_NPC: return "ORIGIN_ANY_NPC";
         case ORIGIN_SECONDARY: return "ORIGIN_SECONDARY";
         case ORIGIN_COMPUTER: return "ORIGIN_COMPUTER";
         // *INDENT-ON*
         case mission_origin::NUM_ORIGIN:
             break;
     }
     cata_fatal( "Invalid mission_origin" );
 }
References cata_fatal, NUM_ORIGIN, ORIGIN_ANY_NPC, ORIGIN_COMPUTER, ORIGIN_GAME_START, ORIGIN_NULL, ORIGIN_OPENER_NPC, and ORIGIN_SECONDARY.
enum_to_string< mon_trigger >()
template<> std::string io::enum_to_string< mon_trigger > (mon_trigger data)
Definition at line 61 of file monstergenerator.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case mon_trigger::STALK: return "STALK";
         case mon_trigger::HOSTILE_WEAK: return "PLAYER_WEAK";
         case mon_trigger::HOSTILE_CLOSE: return "PLAYER_CLOSE";
         case mon_trigger::HOSTILE_SEEN: return "HOSTILE_SEEN";
         case mon_trigger::HURT: return "HURT";
         case mon_trigger::FIRE: return "FIRE";
         case mon_trigger::FRIEND_DIED: return "FRIEND_DIED";
         case mon_trigger::FRIEND_ATTACKED: return "FRIEND_ATTACKED";
         case mon_trigger::SOUND: return "SOUND";
         case mon_trigger::PLAYER_NEAR_BABY: return "PLAYER_NEAR_BABY";
         case mon_trigger::MATING_SEASON: return "MATING_SEASON";
         case mon_trigger::BRIGHT_LIGHT: return "BRIGHT_LIGHT";
         // *INDENT-ON*
         case mon_trigger::LAST:
             break;
     }
     cata_fatal( "Invalid mon_trigger" );
 }
References BRIGHT_LIGHT, cata_fatal, FIRE, FRIEND_ATTACKED, FRIEND_DIED, HOSTILE_CLOSE, HOSTILE_SEEN, HOSTILE_WEAK, HURT, LAST, MATING_SEASON, PLAYER_NEAR_BABY, SOUND, and STALK.
enum_to_string< mongroup::horde_behaviour >()
template<> std::string io::enum_to_string< mongroup::horde_behaviour > (mongroup::horde_behaviour data)
Definition at line 54 of file mongroup.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case mongroup::horde_behaviour::none: return "none";
         case mongroup::horde_behaviour::city: return "city";
         case mongroup::horde_behaviour::roam: return "roam";
         case mongroup::horde_behaviour::nemesis: return "nemesis";
         // *INDENT-ON*
         case mongroup::horde_behaviour::last:
             break;
     }
     cata_fatal( "Invalid mongroup::horde_behaviour" );
 }
References cata_fatal, mongroup::city, mongroup::last, mongroup::nemesis, mongroup::none, and mongroup::roam.
enum_to_string< moon_phase >()
template<> std::string io::enum_to_string< moon_phase > (moon_phase phase_num)
Definition at line 66 of file calendar.cpp.
 {
     switch( phase_num ) {
         case moon_phase::MOON_NEW: return "MOON_NEW";
         case moon_phase::MOON_WAXING_CRESCENT: return "MOON_WAXING_CRESCENT";
         case moon_phase::MOON_HALF_MOON_WAXING: return "MOON_HALF_MOON_WAXING";
         case moon_phase::MOON_WAXING_GIBBOUS: return "MOON_WAXING_GIBBOUS";
         case moon_phase::MOON_FULL: return "MOON_FULL";
         case moon_phase::MOON_WANING_CRESCENT: return "MOON_WANING_CRESCENT";
         case moon_phase::MOON_HALF_MOON_WANING: return "MOON_HALF_MOON_WANING";
         case moon_phase::MOON_WANING_GIBBOUS: return "MOON_WANING_GIBBOUS";
         case moon_phase::MOON_PHASE_MAX: break;
     }
     cata_fatal( "Invalid moon_phase %d", phase_num );
 }
References cata_fatal, MOON_FULL, MOON_HALF_MOON_WANING, MOON_HALF_MOON_WAXING, MOON_NEW, MOON_PHASE_MAX, MOON_WANING_CRESCENT, MOON_WANING_GIBBOUS, MOON_WAXING_CRESCENT, and MOON_WAXING_GIBBOUS.
enum_to_string< music::music_id >()
template<> std::string io::enum_to_string< music::music_id > (music::music_id data)
Definition at line 8 of file music.cpp.
 {
     switch( data ) {
         case music::music_id::mp3:
             return "mp3";
         case music::music_id::instrument:
             return "instrument";
         case music::music_id::sound:
             return "sound";
         case music::music_id::title:
             return "title";
         case music::music_id::LAST:
             break;
     }
     cata_fatal( "Invalid music_id in enum_to_string" );
 }
References cata_fatal, music::instrument, music::LAST, music::mp3, and music::title.
enum_to_string< mutagen_technique >()
template<> std::string io::enum_to_string< mutagen_technique > (mutagen_technique data)
Definition at line 93 of file mutation.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case mutagen_technique::consumed_mutagen: return "consumed_mutagen";
         case mutagen_technique::injected_mutagen: return "injected_mutagen";
         case mutagen_technique::consumed_purifier: return "consumed_purifier";
         case mutagen_technique::injected_purifier: return "injected_purifier";
         case mutagen_technique::injected_smart_purifier: return "injected_smart_purifier";
         // *INDENT-ON*
         case mutagen_technique::num_mutagen_techniques:
             break;
     }
     cata_fatal( "Invalid mutagen_technique" );
 }
References cata_fatal, consumed_mutagen, consumed_purifier, injected_mutagen, injected_purifier, injected_smart_purifier, and num_mutagen_techniques.
enum_to_string< om_direction::type >()
template<> std::string io::enum_to_string< om_direction::type > (om_direction::type d)
Definition at line 172 of file overmap.cpp.
 {
     switch( d ) {
         // *INDENT-OFF*
         case om_direction::type::north: return "north";
         case om_direction::type::east: return "east";
         case om_direction::type::south: return "south";
         case om_direction::type::west: return "west";
         // *INDENT-ON*
         case om_direction::type::invalid:
         case om_direction::type::last:
             break;
     }
     cata_fatal( "Invalid om_direction" );
 }
References cata_fatal, om_direction::east, om_direction::invalid, om_direction::last, om_direction::north, om_direction::south, and om_direction::west.
enum_to_string< ot_match_type >()
template<> std::string io::enum_to_string< ot_match_type > (ot_match_type data)
Definition at line 7370 of file overmap.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case ot_match_type::exact: return "EXACT";
         case ot_match_type::type: return "TYPE";
         case ot_match_type::subtype: return "SUBTYPE";
         case ot_match_type::prefix: return "PREFIX";
         case ot_match_type::contains: return "CONTAINS";
         // *INDENT-ON*
         case ot_match_type::num_ot_match_type:
             break;
     }
     cata_fatal( "Invalid ot_match_type" );
 }
References cata_fatal, contains, exact, num_ot_match_type, prefix, subtype, and type.
enum_to_string< oter_flags >()
template<> std::string io::enum_to_string< oter_flags > (oter_flags data)
Definition at line 676 of file overmap.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case oter_flags::known_down: return "KNOWN_DOWN";
         case oter_flags::known_up: return "KNOWN_UP";
         case oter_flags::river_tile: return "RIVER";
         case oter_flags::bridge: return "BRIDGE";
         case oter_flags::has_sidewalk: return "SIDEWALK";
         case oter_flags::no_rotate: return "NO_ROTATE";
         case oter_flags::should_not_spawn: return "SHOULD_NOT_SPAWN";
         case oter_flags::ignore_rotation_for_adjacency: return "IGNORE_ROTATION_FOR_ADJACENCY";
         case oter_flags::line_drawing: return "LINEAR";
         case oter_flags::subway_connection: return "SUBWAY";
         case oter_flags::requires_predecessor: return "REQUIRES_PREDECESSOR";
         case oter_flags::water: return "WATER";
         case oter_flags::lake: return "LAKE";
         case oter_flags::lake_shore: return "LAKE_SHORE";
         case oter_flags::ocean: return "OCEAN";
         case oter_flags::ocean_shore: return "OCEAN_SHORE";
         case oter_flags::ravine: return "RAVINE";
         case oter_flags::ravine_edge: return "RAVINE_EDGE";
         case oter_flags::generic_loot: return "GENERIC_LOOT";
         case oter_flags::risk_high: return "RISK_HIGH";
         case oter_flags::risk_low: return "RISK_LOW";
         case oter_flags::source_ammo: return "SOURCE_AMMO";
         case oter_flags::source_animals: return "SOURCE_ANIMALS";
         case oter_flags::source_books: return "SOURCE_BOOKS";
         case oter_flags::source_chemistry: return "SOURCE_CHEMISTRY";
         case oter_flags::source_clothing: return "SOURCE_CLOTHING";
         case oter_flags::source_construction: return "SOURCE_CONSTRUCTION";
         case oter_flags::source_cooking: return "SOURCE_COOKING";
         case oter_flags::source_drink: return "SOURCE_DRINK";
         case oter_flags::source_electronics: return "SOURCE_ELECTRONICS";
         case oter_flags::source_fabrication: return "SOURCE_FABRICATION";
         case oter_flags::source_farming: return "SOURCE_FARMING";
         case oter_flags::source_food: return "SOURCE_FOOD";
         case oter_flags::source_forage: return "SOURCE_FORAGE";
         case oter_flags::source_fuel: return "SOURCE_FUEL";
         case oter_flags::source_gun: return "SOURCE_GUN";
         case oter_flags::source_luxury: return "SOURCE_LUXURY";
         case oter_flags::source_medicine: return "SOURCE_MEDICINE";
         case oter_flags::source_people: return "SOURCE_PEOPLE";
         case oter_flags::source_safety: return "SOURCE_SAFETY";
         case oter_flags::source_tailoring: return "SOURCE_TAILORING";
         case oter_flags::source_vehicles: return "SOURCE_VEHICLES";
         case oter_flags::source_weapon: return "SOURCE_WEAPON";
         // *INDENT-ON*
         case oter_flags::num_oter_flags:
             break;
     }
     cata_fatal( "Invalid oter_flags" );
 }
References bridge, cata_fatal, generic_loot, has_sidewalk, ignore_rotation_for_adjacency, known_down, known_up, lake, lake_shore, line_drawing, no_rotate, num_oter_flags, ocean, ocean_shore, ravine, ravine_edge, requires_predecessor, risk_high, risk_low, river_tile, should_not_spawn, source_ammo, source_animals, source_books, source_chemistry, source_clothing, source_construction, source_cooking, source_drink, source_electronics, source_fabrication, source_farming, source_food, source_forage, source_fuel, source_gun, source_luxury, source_medicine, source_people, source_safety, source_tailoring, source_vehicles, source_weapon, subway_connection, and water.
enum_to_string< oter_travel_cost_type >()
template<> std::string io::enum_to_string< oter_travel_cost_type > (oter_travel_cost_type data)
Definition at line 740 of file overmap.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case oter_travel_cost_type::other: return "other";
         case oter_travel_cost_type::road: return "road";
         case oter_travel_cost_type::field: return "field";
         case oter_travel_cost_type::dirt_road: return "dirt_road";
         case oter_travel_cost_type::trail: return "trail";
         case oter_travel_cost_type::forest: return "forest";
         case oter_travel_cost_type::shore: return "shore";
         case oter_travel_cost_type::swamp: return "swamp";
         case oter_travel_cost_type::water: return "water";
         case oter_travel_cost_type::air: return "air";
         case oter_travel_cost_type::impassable: return "impassable";
         // *INDENT-ON*
         case oter_travel_cost_type::last:
             break;
     }
     cata_fatal( "Invalid oter_travel_cost_type" );
 }
References air, cata_fatal, dirt_road, field, forest, impassable, last, other, road, shore, swamp, trail, and water.
enum_to_string< overmap_special_subtype >()
template<> std::string io::enum_to_string< overmap_special_subtype > (overmap_special_subtype data)
Definition at line 158 of file overmap.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case overmap_special_subtype::fixed: return "fixed";
         case overmap_special_subtype::mutable_: return "mutable";
         // *INDENT-ON*
         case overmap_special_subtype::last:
             break;
     }
     cata_fatal( "Invalid overmap_special_subtype" );
 }
enum_to_string< phase_id >()
template<> std::string io::enum_to_string< phase_id > (phase_id data)
Definition at line 5291 of file item_factory.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case phase_id::PNULL: return "null";
         case phase_id::LIQUID: return "liquid";
         case phase_id::SOLID: return "solid";
         case phase_id::GAS: return "gas";
         case phase_id::PLASMA: return "plasma";
         // *INDENT-ON*
         case phase_id::num_phases:
             break;
     }
     cata_fatal( "Invalid phase" );
 }
References cata_fatal, GAS, LIQUID, num_phases, PLASMA, PNULL, and SOLID.
enum_to_string< pocket_type >()
template<> std::string io::enum_to_string< pocket_type > (pocket_type data)
Definition at line 42 of file item_pocket.cpp.
 {
     switch ( data ) {
     case pocket_type::CONTAINER: return "CONTAINER";
     case pocket_type::MAGAZINE: return "MAGAZINE";
     case pocket_type::MAGAZINE_WELL: return "MAGAZINE_WELL";
     case pocket_type::MOD: return "MOD";
     case pocket_type::CORPSE: return "CORPSE";
     case pocket_type::SOFTWARE: return "SOFTWARE";
     case pocket_type::EBOOK: return "EBOOK";
     case pocket_type::CABLE: return "CABLE";
     case pocket_type::MIGRATION: return "MIGRATION";
     case pocket_type::LAST: break;
     }
     cata_fatal( "Invalid valid_target" );
 }
References CABLE, cata_fatal, CONTAINER, CORPSE, EBOOK, LAST, MAGAZINE, MAGAZINE_WELL, MIGRATION, MOD, and SOFTWARE.
enum_to_string< precip_class >()
template<> std::string io::enum_to_string< precip_class > (precip_class data)
Definition at line 21 of file weather_type.cpp.
 {
     switch( data ) {
         case precip_class::none:
             return "none";
         case precip_class::very_light:
             return "very_light";
         case precip_class::light:
             return "light";
         case precip_class::heavy:
             return "heavy";
         case precip_class::last:
             break;
     }
     cata_fatal( "Invalid precip_class" );
 }
References cata_fatal, heavy, last, light, none, and very_light.
enum_to_string< proficiency_bonus_type >()
template<> std::string io::enum_to_string< proficiency_bonus_type > (const proficiency_bonus_type data)
Definition at line 53 of file proficiency.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case proficiency_bonus_type::strength: return "strength";
         case proficiency_bonus_type::dexterity: return "dexterity";
         case proficiency_bonus_type::intelligence: return "intelligence";
         case proficiency_bonus_type::perception: return "perception";
         case proficiency_bonus_type::stamina: return "stamina";
         case proficiency_bonus_type::last: break;
         // *INDENT-ON*
     }
     debugmsg( "Invalid proficiency bonus type" );
     return "";
 }
References debugmsg, dexterity, intelligence, last, perception, stamina, and strength.
enum_to_string< relic_procgen_data::type >()
template<> std::string io::enum_to_string< relic_procgen_data::type > (relic_procgen_data::type data)
Definition at line 41 of file relic.cpp.
     {
         switch( data ) {
         case relic_procgen_data::type::active_enchantment: return "active_enchantment";
         case relic_procgen_data::type::hit_me: return "hit_me";
         case relic_procgen_data::type::hit_you: return "hit_you";
         case relic_procgen_data::type::passive_enchantment_add: return "passive_enchantment_add";
         case relic_procgen_data::type::passive_enchantment_mult: return "passive_enchantment_mult";
         case relic_procgen_data::type::last: break;
         }
         cata_fatal( "Invalid relic procgen data type" );
     }
References cata_fatal, and last.
enum_to_string< relic_recharge_has >()
template<> std::string io::enum_to_string< relic_recharge_has > (relic_recharge_has has)
Definition at line 73 of file relic.cpp.
 {
     // *INDENT-OFF*
     switch (has) {
     case relic_recharge_has::WIELD: return "wield";
     case relic_recharge_has::WORN: return "worn";
     case relic_recharge_has::HELD: return "held";
     case relic_recharge_has::NUM: break;
     }
     // *INDENT-ON*
     cata_fatal( "Invalid relic recharge has condition" );
 }
References cata_fatal, HELD, NUM, WIELD, and WORN.
enum_to_string< relic_recharge_type >()
template<> std::string io::enum_to_string< relic_recharge_type > (relic_recharge_type type)
Definition at line 55 of file relic.cpp.
 {
     // *INDENT-OFF*
     switch( type ) {
         case relic_recharge_type::NONE: return "none";
         case relic_recharge_type::PERIODIC: return "periodic";
         case relic_recharge_type::SOLAR_SUNNY: return "solar_sunny";
         case relic_recharge_type::LUNAR: return "lunar";
         case relic_recharge_type::FULL_MOON: return "full_moon";
         case relic_recharge_type::NEW_MOON: return "new_moon";
         case relic_recharge_type::SOLAR_CLOUDY: return "solar_cloudy";
         case relic_recharge_type::NUM: break;
     }
     // *INDENT-ON*
     cata_fatal( "Invalid relic recharge type" );
 }
References cata_fatal, FULL_MOON, LUNAR, NEW_MOON, NONE, NUM, PERIODIC, SOLAR_CLOUDY, and SOLAR_SUNNY.
enum_to_string< requirement_visibility >()
template<> std::string io::enum_to_string< requirement_visibility > (requirement_visibility data)
Definition at line 130 of file achievement.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case requirement_visibility::always: return "always";
         case requirement_visibility::when_requirement_completed: return "when_requirement_completed";
         case requirement_visibility::when_achievement_completed: return "when_achievement_completed";
         case requirement_visibility::never: return "never";
         // *INDENT-ON*
         case requirement_visibility::last:
             break;
     }
     cata_fatal( "Invalid requirement_visibility" );
 }
References always, cata_fatal, last, never, when_achievement_completed, and when_requirement_completed.
enum_to_string< season_type >()
template<> std::string io::enum_to_string< season_type > (season_type data)
Definition at line 783 of file mapdata.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case season_type::SPRING: return "spring";
         case season_type::SUMMER: return "summer";
         case season_type::AUTUMN: return "autumn";
         case season_type::WINTER: return "winter";
         // *INDENT-ON*
         case season_type::NUM_SEASONS:
             break;
     }
     cata_fatal( "Invalid season_type" );
 }
References AUTUMN, cata_fatal, NUM_SEASONS, SPRING, SUMMER, and WINTER.
enum_to_string< side >()
template<> std::string io::enum_to_string< side > (side data)
Definition at line 61 of file bodypart.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case side::LEFT: return "left";
         case side::RIGHT: return "right";
         case side::BOTH: return "both";
         // *INDENT-ON*
         case side::num_sides:
             break;
     }
     cata_fatal( "Invalid side" );
 }
References BOTH, cata_fatal, LEFT, num_sides, and RIGHT.
enum_to_string< sounds::sound_t >()
template<> std::string io::enum_to_string< sounds::sound_t > (sounds::sound_t data)
Definition at line 217 of file sounds.cpp.
 {
     switch ( data ) {
     case sounds::sound_t::background: return "background";
     case sounds::sound_t::weather: return "weather";
     case sounds::sound_t::sensory: return "sensory";
     case sounds::sound_t::music: return "music";
     case sounds::sound_t::movement: return "movement";
     case sounds::sound_t::speech: return "speech";
     case sounds::sound_t::electronic_speech: return "electronic_speech";
     case sounds::sound_t::activity: return "activity";
     case sounds::sound_t::destructive_activity: return "destructive_activity";
     case sounds::sound_t::alarm: return "alarm";
     case sounds::sound_t::combat: return "combat";
     case sounds::sound_t::alert: return "alert";
     case sounds::sound_t::order: return "order";
     case sounds::sound_t::LAST: break;
     }
     cata_fatal( "Invalid valid_target" );
 }
References sounds::activity, sounds::alarm, sounds::alert, sounds::background, cata_fatal, sounds::combat, sounds::destructive_activity, sounds::electronic_speech, sounds::LAST, sounds::movement, sounds::music, sounds::order, sounds::sensory, sounds::speech, and sounds::weather.
enum_to_string< spell_flag >()
template<> std::string io::enum_to_string< spell_flag > (spell_flag data)
Definition at line 119 of file magic.cpp.
 {
     switch( data ) {
         case spell_flag::PERMANENT: return "PERMANENT";
         case spell_flag::PERMANENT_ALL_LEVELS: return "PERMANENT_ALL_LEVELS";
         case spell_flag::PERCENTAGE_DAMAGE: return "PERCENTAGE_DAMAGE";
         case spell_flag::IGNORE_WALLS: return "IGNORE_WALLS";
         case spell_flag::NO_PROJECTILE: return "NO_PROJECTILE";
         case spell_flag::HOSTILE_SUMMON: return "HOSTILE_SUMMON";
         case spell_flag::HOSTILE_50: return "HOSTILE_50";
         case spell_flag::FRIENDLY_POLY: return "FRIENDLY_POLY";
         case spell_flag::POLYMORPH_GROUP: return "POLYMORPH_GROUP";
         case spell_flag::SILENT: return "SILENT";
         case spell_flag::NO_EXPLOSION_SFX: return "NO_EXPLOSION_SFX";
         case spell_flag::LOUD: return "LOUD";
         case spell_flag::VERBAL: return "VERBAL";
         case spell_flag::SOMATIC: return "SOMATIC";
         case spell_flag::NO_HANDS: return "NO_HANDS";
         case spell_flag::NO_LEGS: return "NO_LEGS";
         case spell_flag::UNSAFE_TELEPORT: return "UNSAFE_TELEPORT";
         case spell_flag::TARGET_TELEPORT: return "TARGET_TELEPORT";
         case spell_flag::SWAP_POS: return "SWAP_POS";
         case spell_flag::CONCENTRATE: return "CONCENTRATE";
         case spell_flag::RANDOM_AOE: return "RANDOM_AOE";
         case spell_flag::RANDOM_DAMAGE: return "RANDOM_DAMAGE";
         case spell_flag::RANDOM_DURATION: return "RANDOM_DURATION";
         case spell_flag::RANDOM_TARGET: return "RANDOM_TARGET";
         case spell_flag::RANDOM_CRITTER: return "RANDOM_CRITTER";
         case spell_flag::MUTATE_TRAIT: return "MUTATE_TRAIT";
         case spell_flag::PAIN_NORESIST: return "PAIN_NORESIST";
         case spell_flag::SPAWN_GROUP: return "SPAWN_GROUP";
         case spell_flag::IGNITE_FLAMMABLE: return "IGNITE_FLAMMABLE";
         case spell_flag::NO_FAIL: return "NO_FAIL";
         case spell_flag::WONDER: return "WONDER";
         case spell_flag::EXTRA_EFFECTS_FIRST: return "EXTRA_EFFECTS_FIRST";
         case spell_flag::MUST_HAVE_CLASS_TO_LEARN: return "MUST_HAVE_CLASS_TO_LEARN";
         case spell_flag::SPAWN_WITH_DEATH_DROPS: return "SPAWN_WITH_DEATH_DROPS";
         case spell_flag::NO_CORPSE_QUIET: return "NO_CORPSE_QUIET";
         case spell_flag::NON_MAGICAL: return "NON_MAGICAL";
         case spell_flag::PSIONIC: return "PSIONIC";
         case spell_flag::RECHARM: return "RECHARM";
         case spell_flag::LAST: break;
     }
     cata_fatal( "Invalid spell_flag" );
 }
References cata_fatal, CONCENTRATE, EXTRA_EFFECTS_FIRST, FRIENDLY_POLY, HOSTILE_50, HOSTILE_SUMMON, IGNITE_FLAMMABLE, IGNORE_WALLS, LAST, LOUD, MUST_HAVE_CLASS_TO_LEARN, MUTATE_TRAIT, NO_CORPSE_QUIET, NO_EXPLOSION_SFX, NO_FAIL, NO_HANDS, NO_LEGS, NO_PROJECTILE, NON_MAGICAL, PAIN_NORESIST, PERCENTAGE_DAMAGE, PERMANENT, PERMANENT_ALL_LEVELS, POLYMORPH_GROUP, PSIONIC, RANDOM_AOE, RANDOM_CRITTER, RANDOM_DAMAGE, RANDOM_DURATION, RANDOM_TARGET, RECHARM, SILENT, SOMATIC, SPAWN_GROUP, SPAWN_WITH_DEATH_DROPS, SWAP_POS, TARGET_TELEPORT, UNSAFE_TELEPORT, VERBAL, and WONDER.
enum_to_string< spell_shape >()
template<> std::string io::enum_to_string< spell_shape > (spell_shape data)
Definition at line 108 of file magic.cpp.
 {
     switch( data ) {
         case spell_shape::blast: return "blast";
         case spell_shape::cone: return "cone";
         case spell_shape::line: return "line";
         case spell_shape::num_shapes: break;
     }
     cata_fatal( "Invalid spell_shape" );
 }
References blast, cata_fatal, cone, line, and num_shapes.
enum_to_string< spell_target >()
template<> std::string io::enum_to_string< spell_target > (spell_target data)
Definition at line 93 of file magic.cpp.
 {
     switch( data ) {
         case spell_target::ally: return "ally";
         case spell_target::hostile: return "hostile";
         case spell_target::self: return "self";
         case spell_target::ground: return "ground";
         case spell_target::none: return "none";
         case spell_target::item: return "item";
         case spell_target::field: return "field";
         case spell_target::num_spell_targets: break;
     }
     cata_fatal( "Invalid valid_target" );
 }
References ally, cata_fatal, field, ground, hostile, item, none, num_spell_targets, and self.
enum_to_string< surface_val >()
template<> std::string io::enum_to_string< surface_val > (surface_val val)
Definition at line 4002 of file item_factory.cpp.
 {
     switch( val ) {
         case surface_val::POINT: return "point";
         case surface_val::LINE: return "line";
         case surface_val::ANY: return "any";
         case surface_val::EVERY: return "every";
         default: break;
     }
     cata_fatal( "Invalid surface val" );
 }
References ANY, cata_fatal, EVERY, LINE, and POINT.
enum_to_string< ter_furn_flag >()
template<> std::string io::enum_to_string< ter_furn_flag > (ter_furn_flag data)
Definition at line 141 of file mapdata.cpp.
 {
     // see mapdata.h for commentary
     switch( data ) {
         // *INDENT-OFF*
         case ter_furn_flag::TFLAG_TRANSPARENT: return "TRANSPARENT";
         case ter_furn_flag::TFLAG_FLAMMABLE: return "FLAMMABLE";
         case ter_furn_flag::TFLAG_REDUCE_SCENT: return "REDUCE_SCENT";
         case ter_furn_flag::TFLAG_SWIMMABLE: return "SWIMMABLE";
         case ter_furn_flag::TFLAG_SUPPORTS_ROOF: return "SUPPORTS_ROOF";
         case ter_furn_flag::TFLAG_MINEABLE: return "MINEABLE";
         case ter_furn_flag::TFLAG_NOITEM: return "NOITEM";
         case ter_furn_flag::TFLAG_NO_SIGHT: return "NO_SIGHT";
         case ter_furn_flag::TFLAG_NO_SCENT: return "NO_SCENT";
         case ter_furn_flag::TFLAG_SEALED: return "SEALED";
         case ter_furn_flag::TFLAG_ALLOW_FIELD_EFFECT: return "ALLOW_FIELD_EFFECT";
         case ter_furn_flag::TFLAG_LIQUID: return "LIQUID";
         case ter_furn_flag::TFLAG_COLLAPSES: return "COLLAPSES";
         case ter_furn_flag::TFLAG_FLAMMABLE_ASH: return "FLAMMABLE_ASH";
         case ter_furn_flag::TFLAG_DESTROY_ITEM: return "DESTROY_ITEM";
         case ter_furn_flag::TFLAG_INDOORS: return "INDOORS";
         case ter_furn_flag::TFLAG_LIQUIDCONT: return "LIQUIDCONT";
         case ter_furn_flag::TFLAG_FIRE_CONTAINER: return "FIRE_CONTAINER";
         case ter_furn_flag::TFLAG_FLAMMABLE_HARD: return "FLAMMABLE_HARD";
         case ter_furn_flag::TFLAG_SUPPRESS_SMOKE: return "SUPPRESS_SMOKE";
         case ter_furn_flag::TFLAG_SHARP: return "SHARP";
         case ter_furn_flag::TFLAG_DIGGABLE: return "DIGGABLE";
         case ter_furn_flag::TFLAG_ROUGH: return "ROUGH";
         case ter_furn_flag::TFLAG_UNSTABLE: return "UNSTABLE";
         case ter_furn_flag::TFLAG_WALL: return "WALL";
         case ter_furn_flag::TFLAG_DEEP_WATER: return "DEEP_WATER";
         case ter_furn_flag::TFLAG_SHALLOW_WATER: return "SHALLOW_WATER";
         case ter_furn_flag::TFLAG_WATER_CUBE: return "WATER_CUBE";
         case ter_furn_flag::TFLAG_CURRENT: return "CURRENT";
         case ter_furn_flag::TFLAG_HARVESTED: return "HARVESTED";
         case ter_furn_flag::TFLAG_PERMEABLE: return "PERMEABLE";
         case ter_furn_flag::TFLAG_AUTO_WALL_SYMBOL: return "AUTO_WALL_SYMBOL";
         case ter_furn_flag::TFLAG_CONNECT_WITH_WALL: return "CONNECT_WITH_WALL";
         case ter_furn_flag::TFLAG_CLIMBABLE: return "CLIMBABLE";
         case ter_furn_flag::TFLAG_GOES_DOWN: return "GOES_DOWN";
         case ter_furn_flag::TFLAG_GOES_UP: return "GOES_UP";
         case ter_furn_flag::TFLAG_NO_FLOOR: return "NO_FLOOR";
         case ter_furn_flag::TFLAG_ALLOW_ON_OPEN_AIR: return "ALLOW_ON_OPEN_AIR";
         case ter_furn_flag::TFLAG_SEEN_FROM_ABOVE: return "SEEN_FROM_ABOVE";
         case ter_furn_flag::TFLAG_RAMP_DOWN: return "RAMP_DOWN";
         case ter_furn_flag::TFLAG_RAMP_UP: return "RAMP_UP";
         case ter_furn_flag::TFLAG_RAMP: return "RAMP";
         case ter_furn_flag::TFLAG_HIDE_PLACE: return "HIDE_PLACE";
         case ter_furn_flag::TFLAG_BLOCK_WIND: return "BLOCK_WIND";
         case ter_furn_flag::TFLAG_FLAT: return "FLAT";
         case ter_furn_flag::TFLAG_RAIL: return "RAIL";
         case ter_furn_flag::TFLAG_THIN_OBSTACLE: return "THIN_OBSTACLE";
         case ter_furn_flag::TFLAG_SMALL_PASSAGE: return "SMALL_PASSAGE";
         case ter_furn_flag::TFLAG_Z_TRANSPARENT: return "Z_TRANSPARENT";
         case ter_furn_flag::TFLAG_SUN_ROOF_ABOVE: return "SUN_ROOF_ABOVE";
         case ter_furn_flag::TFLAG_FUNGUS: return "FUNGUS";
         case ter_furn_flag::TFLAG_LOCKED: return "LOCKED";
         case ter_furn_flag::TFLAG_PICKABLE: return "PICKABLE";
         case ter_furn_flag::TFLAG_WINDOW: return "WINDOW";
         case ter_furn_flag::TFLAG_DOOR: return "DOOR";
         case ter_furn_flag::TFLAG_SHRUB: return "SHRUB";
         case ter_furn_flag::TFLAG_YOUNG: return "YOUNG";
         case ter_furn_flag::TFLAG_PLANT: return "PLANT";
         case ter_furn_flag::TFLAG_FISHABLE: return "FISHABLE";
         case ter_furn_flag::TFLAG_TREE: return "TREE";
         case ter_furn_flag::TFLAG_PLOWABLE: return "PLOWABLE";
         case ter_furn_flag::TFLAG_ORGANIC: return "ORGANIC";
         case ter_furn_flag::TFLAG_CONSOLE: return "CONSOLE";
         case ter_furn_flag::TFLAG_PLANTABLE: return "PLANTABLE";
         case ter_furn_flag::TFLAG_GROWTH_HARVEST: return "GROWTH_HARVEST";
         case ter_furn_flag::TFLAG_GROWTH_OVERGROWN: return "GROWTH_OVERGROWN";
         case ter_furn_flag::TFLAG_MOUNTABLE: return "MOUNTABLE";
         case ter_furn_flag::TFLAG_RAMP_END: return "RAMP_END";
         case ter_furn_flag::TFLAG_FLOWER: return "FLOWER";
         case ter_furn_flag::TFLAG_CAN_SIT: return "CAN_SIT";
         case ter_furn_flag::TFLAG_FLAT_SURF: return "FLAT_SURF";
         case ter_furn_flag::TFLAG_BUTCHER_EQ: return "BUTCHER_EQ";
         case ter_furn_flag::TFLAG_GROWTH_SEEDLING: return "GROWTH_SEEDLING";
         case ter_furn_flag::TFLAG_GROWTH_MATURE: return "GROWTH_MATURE";
         case ter_furn_flag::TFLAG_WORKOUT_ARMS: return "WORKOUT_ARMS";
         case ter_furn_flag::TFLAG_WORKOUT_LEGS: return "WORKOUT_LEGS";
         case ter_furn_flag::TFLAG_TRANSLOCATOR: return "TRANSLOCATOR";
         case ter_furn_flag::TFLAG_AUTODOC: return "AUTODOC";
         case ter_furn_flag::TFLAG_AUTODOC_COUCH: return "AUTODOC_COUCH";
         case ter_furn_flag::TFLAG_OPENCLOSE_INSIDE: return "OPENCLOSE_INSIDE";
         case ter_furn_flag::TFLAG_SALT_WATER: return "SALT_WATER";
         case ter_furn_flag::TFLAG_PLACE_ITEM: return "PLACE_ITEM";
         case ter_furn_flag::TFLAG_BARRICADABLE_WINDOW_CURTAINS: return "BARRICADABLE_WINDOW_CURTAINS";
         case ter_furn_flag::TFLAG_CLIMB_SIMPLE: return "CLIMB_SIMPLE";
         case ter_furn_flag::TFLAG_NANOFAB_TABLE: return "NANOFAB_TABLE";
         case ter_furn_flag::TFLAG_ROAD: return "ROAD";
         case ter_furn_flag::TFLAG_TINY: return "TINY";
         case ter_furn_flag::TFLAG_SHORT: return "SHORT";
         case ter_furn_flag::TFLAG_NOCOLLIDE: return "NOCOLLIDE";
         case ter_furn_flag::TFLAG_BARRICADABLE_DOOR: return "BARRICADABLE_DOOR";
         case ter_furn_flag::TFLAG_BARRICADABLE_DOOR_DAMAGED: return "BARRICADABLE_DOOR_DAMAGED";
         case ter_furn_flag::TFLAG_BARRICADABLE_DOOR_REINFORCED: return "BARRICADABLE_DOOR_REINFORCED";
         case ter_furn_flag::TFLAG_USABLE_FIRE: return "USABLE_FIRE";
         case ter_furn_flag::TFLAG_CONTAINER: return "CONTAINER";
         case ter_furn_flag::TFLAG_NO_PICKUP_ON_EXAMINE: return "NO_PICKUP_ON_EXAMINE";
         case ter_furn_flag::TFLAG_RUBBLE: return "RUBBLE";
         case ter_furn_flag::TFLAG_DIGGABLE_CAN_DEEPEN: return "DIGGABLE_CAN_DEEPEN";
         case ter_furn_flag::TFLAG_PIT_FILLABLE: return "PIT_FILLABLE";
         case ter_furn_flag::TFLAG_DIFFICULT_Z: return "DIFFICULT_Z";
         case ter_furn_flag::TFLAG_ALIGN_WORKBENCH: return "ALIGN_WORKBENCH";
         case ter_furn_flag::TFLAG_NO_SPOIL: return "NO_SPOIL";
         case ter_furn_flag::TFLAG_EASY_DECONSTRUCT: return "EASY_DECONSTRUCT";
         case ter_furn_flag::TFLAG_LADDER: return "LADDER";
         case ter_furn_flag::TFLAG_ALARMED: return "ALARMED";
         case ter_furn_flag::TFLAG_CHOCOLATE: return "CHOCOLATE";
         case ter_furn_flag::TFLAG_SIGN: return "SIGN";
         case ter_furn_flag::TFLAG_SIGN_ALWAYS: return "SIGN_ALWAYS";
         case ter_furn_flag::TFLAG_DONT_REMOVE_ROTTEN: return "DONT_REMOVE_ROTTEN";
         case ter_furn_flag::TFLAG_BLOCKSDOOR: return "BLOCKSDOOR";
         case ter_furn_flag::TFLAG_SMALL_HIDE: return "SMALL_HIDE";
         case ter_furn_flag::TFLAG_NO_SELF_CONNECT: return "NO_SELF_CONNECT";
         case ter_furn_flag::TFLAG_BURROWABLE: return "BURROWABLE";
         case ter_furn_flag::TFLAG_MURKY: return "MURKY";
         case ter_furn_flag::TFLAG_AMMOTYPE_RELOAD: return "AMMOTYPE_RELOAD";
         case ter_furn_flag::TFLAG_TRANSPARENT_FLOOR: return "TRANSPARENT_FLOOR";
         case ter_furn_flag::TFLAG_TOILET_WATER: return "TOILET_WATER";
         case ter_furn_flag::TFLAG_ELEVATOR: return "ELEVATOR";
         case ter_furn_flag::TFLAG_ACTIVE_GENERATOR: return "ACTIVE_GENERATOR";
         case ter_furn_flag::TFLAG_NO_FLOOR_WATER: return "NO_FLOOR_WATER";
         case ter_furn_flag::TFLAG_GRAZABLE: return "GRAZABLE";
         case ter_furn_flag::TFLAG_GRAZER_INEDIBLE: return "GRAZER_INEDIBLE";
         case ter_furn_flag::TFLAG_BROWSABLE: return "BROWSABLE";
         case ter_furn_flag::TFLAG_SINGLE_SUPPORT: return "SINGLE_SUPPORT";
         case ter_furn_flag::TFLAG_CLIMB_ADJACENT: return "CLIMB_ADJACENT";
         case ter_furn_flag::TFLAG_FLOATS_IN_AIR: return "FLOATS_IN_AIR";
         // *INDENT-ON*
         case ter_furn_flag::NUM_TFLAG_FLAGS:
             break;
     }
     cata_fatal( "Invalid ter_furn_flag" );
 }
References cata_fatal, NUM_TFLAG_FLAGS, TFLAG_ACTIVE_GENERATOR, TFLAG_ALARMED, TFLAG_ALIGN_WORKBENCH, TFLAG_ALLOW_FIELD_EFFECT, TFLAG_ALLOW_ON_OPEN_AIR, TFLAG_AMMOTYPE_RELOAD, TFLAG_AUTO_WALL_SYMBOL, TFLAG_AUTODOC, TFLAG_AUTODOC_COUCH, TFLAG_BARRICADABLE_DOOR, TFLAG_BARRICADABLE_DOOR_DAMAGED, TFLAG_BARRICADABLE_DOOR_REINFORCED, TFLAG_BARRICADABLE_WINDOW_CURTAINS, TFLAG_BLOCK_WIND, TFLAG_BLOCKSDOOR, TFLAG_BROWSABLE, TFLAG_BURROWABLE, TFLAG_BUTCHER_EQ, TFLAG_CAN_SIT, TFLAG_CHOCOLATE, TFLAG_CLIMB_ADJACENT, TFLAG_CLIMB_SIMPLE, TFLAG_CLIMBABLE, TFLAG_COLLAPSES, TFLAG_CONNECT_WITH_WALL, TFLAG_CONSOLE, TFLAG_CONTAINER, TFLAG_CURRENT, TFLAG_DEEP_WATER, TFLAG_DESTROY_ITEM, TFLAG_DIFFICULT_Z, TFLAG_DIGGABLE, TFLAG_DIGGABLE_CAN_DEEPEN, TFLAG_DONT_REMOVE_ROTTEN, TFLAG_DOOR, TFLAG_EASY_DECONSTRUCT, TFLAG_ELEVATOR, TFLAG_FIRE_CONTAINER, TFLAG_FISHABLE, TFLAG_FLAMMABLE, TFLAG_FLAMMABLE_ASH, TFLAG_FLAMMABLE_HARD, TFLAG_FLAT, TFLAG_FLAT_SURF, TFLAG_FLOATS_IN_AIR, TFLAG_FLOWER, TFLAG_FUNGUS, TFLAG_GOES_DOWN, TFLAG_GOES_UP, TFLAG_GRAZABLE, TFLAG_GRAZER_INEDIBLE, TFLAG_GROWTH_HARVEST, TFLAG_GROWTH_MATURE, TFLAG_GROWTH_OVERGROWN, TFLAG_GROWTH_SEEDLING, TFLAG_HARVESTED, TFLAG_HIDE_PLACE, TFLAG_INDOORS, TFLAG_LADDER, TFLAG_LIQUID, TFLAG_LIQUIDCONT, TFLAG_LOCKED, TFLAG_MINEABLE, TFLAG_MOUNTABLE, TFLAG_MURKY, TFLAG_NANOFAB_TABLE, TFLAG_NO_FLOOR, TFLAG_NO_FLOOR_WATER, TFLAG_NO_PICKUP_ON_EXAMINE, TFLAG_NO_SCENT, TFLAG_NO_SELF_CONNECT, TFLAG_NO_SIGHT, TFLAG_NO_SPOIL, TFLAG_NOCOLLIDE, TFLAG_NOITEM, TFLAG_OPENCLOSE_INSIDE, TFLAG_ORGANIC, TFLAG_PERMEABLE, TFLAG_PICKABLE, TFLAG_PIT_FILLABLE, TFLAG_PLACE_ITEM, TFLAG_PLANT, TFLAG_PLANTABLE, TFLAG_PLOWABLE, TFLAG_RAIL, TFLAG_RAMP, TFLAG_RAMP_DOWN, TFLAG_RAMP_END, TFLAG_RAMP_UP, TFLAG_REDUCE_SCENT, TFLAG_ROAD, TFLAG_ROUGH, TFLAG_RUBBLE, TFLAG_SALT_WATER, TFLAG_SEALED, TFLAG_SEEN_FROM_ABOVE, TFLAG_SHALLOW_WATER, TFLAG_SHARP, TFLAG_SHORT, TFLAG_SHRUB, TFLAG_SIGN, TFLAG_SIGN_ALWAYS, TFLAG_SINGLE_SUPPORT, TFLAG_SMALL_HIDE, TFLAG_SMALL_PASSAGE, TFLAG_SUN_ROOF_ABOVE, TFLAG_SUPPORTS_ROOF, TFLAG_SUPPRESS_SMOKE, TFLAG_SWIMMABLE, TFLAG_THIN_OBSTACLE, TFLAG_TINY, TFLAG_TOILET_WATER, TFLAG_TRANSLOCATOR, TFLAG_TRANSPARENT, TFLAG_TRANSPARENT_FLOOR, TFLAG_TREE, TFLAG_UNSTABLE, TFLAG_USABLE_FIRE, TFLAG_WALL, TFLAG_WATER_CUBE, TFLAG_WINDOW, TFLAG_WORKOUT_ARMS, TFLAG_WORKOUT_LEGS, TFLAG_YOUNG, and TFLAG_Z_TRANSPARENT.
Referenced by map_data_common_t::set_flag().
enum_to_string< time_accuracy >()
template<> std::string io::enum_to_string< time_accuracy > (time_accuracy acc)
Definition at line 82 of file calendar.cpp.
 {
     switch( acc ) {
         case time_accuracy::PARTIAL: return "PARTIAL";
         case time_accuracy::FULL: return "FULL";
         case time_accuracy::NUM_TIME_ACCURACY:
         case time_accuracy::NONE: break;
         default:
             DebugLog( DebugLevel::D_WARNING, DebugClass::D_GAME )
                 << "Invalid time_accuracy " << static_cast<int>( acc );
     }
     return "NONE";
 }
References D_GAME, D_WARNING, DebugLog(), FULL, NONE, NUM_TIME_ACCURACY, and PARTIAL.
Referenced by get_diary_time_since_str(), and get_diary_time_str().
enum_to_string< tut_lesson >()
template<> std::string io::enum_to_string< tut_lesson > (tut_lesson data)
Definition at line 72 of file gamemode_tutorial.cpp.
 {
     switch( data ) {
             // *INDENT-OFF*
         case tut_lesson::LESSON_INTRO: return "LESSON_INTRO";
         case tut_lesson::LESSON_MOVE: return "LESSON_MOVE";
         case tut_lesson::LESSON_MOVEMENT_MODES: return "LESSON_MOVEMENT_MODES";
         case tut_lesson::LESSON_LOOK: return "LESSON_LOOK";
         case tut_lesson::LESSON_OPEN: return "LESSON_OPEN";
         case tut_lesson::LESSON_CLOSE: return "LESSON_CLOSE";
         case tut_lesson::LESSON_SMASH: return "LESSON_SMASH";
         case tut_lesson::LESSON_WINDOW: return "LESSON_WINDOW";
         case tut_lesson::LESSON_PICKUP: return "LESSON_PICKUP";
         case tut_lesson::LESSON_EXAMINE: return "LESSON_EXAMINE";
         case tut_lesson::LESSON_INTERACT: return "LESSON_INTERACT";
         case tut_lesson::LESSON_GOT_ARMOR: return "LESSON_GOT_ARMOR";
         case tut_lesson::LESSON_GOT_WEAPON: return "LESSON_GOT_WEAPON";
         case tut_lesson::LESSON_GOT_FOOD: return "LESSON_GOT_FOOD";
         case tut_lesson::LESSON_GOT_TOOL: return "LESSON_GOT_TOOL";
         case tut_lesson::LESSON_GOT_GUN: return "LESSON_GOT_GUN";
         case tut_lesson::LESSON_GOT_AMMO: return "LESSON_GOT_AMMO";
         case tut_lesson::LESSON_WORE_ARMOR: return "LESSON_WORE_ARMOR";
         case tut_lesson::LESSON_WORE_STORAGE: return "LESSON_WORE_STORAGE";
         case tut_lesson::LESSON_WORE_MASK: return "LESSON_WORE_MASK";
         case tut_lesson::LESSON_WEAPON_INFO: return "LESSON_WEAPON_INFO";
         case tut_lesson::LESSON_HIT_MONSTER: return "LESSON_HIT_MONSTER";
         case tut_lesson::LESSON_PAIN: return "LESSON_PAIN";
         case tut_lesson::LESSON_BUTCHER: return "LESSON_BUTCHER";
         case tut_lesson::LESSON_TOOK_PAINKILLER: return "LESSON_TOOK_PAINKILLER";
         case tut_lesson::LESSON_TOOK_CIG: return "LESSON_TOOK_CIG";
         case tut_lesson::LESSON_DRANK_WATER: return "LESSON_DRANK_WATER";
         case tut_lesson::LESSON_ACT_GRENADE: return "LESSON_ACT_GRENADE";
         case tut_lesson::LESSON_ACT_BUBBLEWRAP: return "LESSON_ACT_BUBBLEWRAP";
         case tut_lesson::LESSON_GUN_LOAD: return "LESSON_GUN_LOAD";
         case tut_lesson::LESSON_GUN_FIRE: return "LESSON_GUN_FIRE";
         case tut_lesson::LESSON_RECOIL: return "LESSON_RECOIL";
         case tut_lesson::LESSON_STAIRS: return "LESSON_STAIRS";
         case tut_lesson::LESSON_DARK_NO_FLASH: return "LESSON_DARK_NO_FLASH";
         case tut_lesson::LESSON_DARK: return "LESSON_DARK";
         case tut_lesson::LESSON_PICKUP_WATER: return "LESSON_PICKUP_WATER";
         case tut_lesson::LESSON_MONSTER_SIGHTED: return "LESSON_MONSTER_SIGHTED";
         case tut_lesson::LESSON_LOCKED_DOOR: return "LESSON_LOCKED_DOOR";
         case tut_lesson::LESSON_RESTORE_STAMINA: return "LESSON_RESTORE_STAMINA";
         case tut_lesson::LESSON_REACH_ATTACK: return "LESSON_REACH_ATTACK";
         case tut_lesson::LESSON_HOLSTERS_WEAR: return "LESSON_HOLSTERS_WEAR";
         case tut_lesson::LESSON_HOLSTERS_ACTIVATE: return "LESSON_HOLSTERS_ACTIVATE";
         case tut_lesson::LESSON_INVENTORY: return "LESSON_INVENTORY";
         case tut_lesson::LESSON_FLASHLIGHT: return "LESSON_FLASHLIGHT";
         case tut_lesson::LESSON_REMOTE_USE: return "LESSON_REMOTE_USE";
         case tut_lesson::LESSON_CRAFTING_FOOD: return "LESSON_CRAFTING_FOOD";
         case tut_lesson::LESSON_CONSTRUCTION: return "LESSON_CONSTRUCTION";
         case tut_lesson::LESSON_THROWING: return "LESSON_THROWING";
         case tut_lesson::LESSON_FINALE: return "LESSON_FINALE";
             // *INDENT-ON*
         case tut_lesson::NUM_LESSONS:
             break;
     }
     cata_fatal( "Invalid tut_lesson" );
 }
References cata_fatal, LESSON_ACT_BUBBLEWRAP, LESSON_ACT_GRENADE, LESSON_BUTCHER, LESSON_CLOSE, LESSON_CONSTRUCTION, LESSON_CRAFTING_FOOD, LESSON_DARK, LESSON_DARK_NO_FLASH, LESSON_DRANK_WATER, LESSON_EXAMINE, LESSON_FINALE, LESSON_FLASHLIGHT, LESSON_GOT_AMMO, LESSON_GOT_ARMOR, LESSON_GOT_FOOD, LESSON_GOT_GUN, LESSON_GOT_TOOL, LESSON_GOT_WEAPON, LESSON_GUN_FIRE, LESSON_GUN_LOAD, LESSON_HIT_MONSTER, LESSON_HOLSTERS_ACTIVATE, LESSON_HOLSTERS_WEAR, LESSON_INTERACT, LESSON_INTRO, LESSON_INVENTORY, LESSON_LOCKED_DOOR, LESSON_LOOK, LESSON_MONSTER_SIGHTED, LESSON_MOVE, LESSON_MOVEMENT_MODES, LESSON_OPEN, LESSON_PAIN, LESSON_PICKUP, LESSON_PICKUP_WATER, LESSON_REACH_ATTACK, LESSON_RECOIL, LESSON_REMOTE_USE, LESSON_RESTORE_STAMINA, LESSON_SMASH, LESSON_STAIRS, LESSON_THROWING, LESSON_TOOK_CIG, LESSON_TOOK_PAINKILLER, LESSON_WEAPON_INFO, LESSON_WINDOW, LESSON_WORE_ARMOR, LESSON_WORE_MASK, LESSON_WORE_STORAGE, and NUM_LESSONS.
Referenced by tutorial_game::add_message().
enum_to_string< usage_from >()
template<> std::string io::enum_to_string< usage_from > (usage_from data)
Definition at line 71 of file craft_command.cpp.
 {
     switch( data ) {
         // *INDENT-OFF*
         case usage_from::map: return "map";
         case usage_from::player: return "player";
         case usage_from::both: return "both";
         case usage_from::none: return "none";
         case usage_from::cancel: return "cancel";
         // *INDENT-ON*
         case usage_from::num_usages_from:
             break;
     }
     cata_fatal( "Invalid usage" );
 }
References both, cancel, cata_fatal, map, none, num_usages_from, and player.
enum_to_string< vitamin_type >()
template<> std::string io::enum_to_string< vitamin_type > (vitamin_type data)
Definition at line 159 of file vitamin.cpp.
 {
     switch( data ) {
         case vitamin_type::VITAMIN:
             return "vitamin";
         case vitamin_type::TOXIN:
             return "toxin";
         case vitamin_type::DRUG:
             return "drug";
         case vitamin_type::COUNTER:
             return "counter";
         case vitamin_type::num_vitamin_types:
             break;
     }
     cata_fatal( "Invalid vitamin_type" );
 }
References cata_fatal, COUNTER, DRUG, num_vitamin_types, TOXIN, and VITAMIN.
enum_to_string< weather_sound_category >()
template<> std::string io::enum_to_string< weather_sound_category > (weather_sound_category data)
Definition at line 39 of file weather_type.cpp.
 {
     switch( data ) {
         case weather_sound_category::drizzle:
             return "drizzle";
         case weather_sound_category::flurries:
             return "flurries";
         case weather_sound_category::rainy:
             return "rainy";
         case weather_sound_category::rainstorm:
             return "rainstorm";
         case weather_sound_category::snow:
             return "snow";
         case weather_sound_category::snowstorm:
             return "snowstorm";
         case weather_sound_category::thunder:
             return "thunder";
         case weather_sound_category::silent:
             return "silent";
         case weather_sound_category::portal_storm:
             return "portal_storm";
         case weather_sound_category::clear:
             return "clear";
         case weather_sound_category::sunny:
             return "sunny";
         case weather_sound_category::cloudy:
             return "cloudy";
         case weather_sound_category::last:
             break;
     }
     cata_fatal( "Invalid weather sound category." );
 }
References cata_fatal, clear, cloudy, drizzle, flurries, last, portal_storm, rainstorm, rainy, silent, snow, snowstorm, sunny, and thunder.
enum_to_string< widget_alignment >()
template<> std::string io::enum_to_string< widget_alignment > (widget_alignment align)
Definition at line 265 of file widget.cpp.
 {
     switch( align ) {
         case widget_alignment::LEFT:
             return "left";
         case widget_alignment::CENTER:
             return "center";
         case widget_alignment::RIGHT:
             return "right";
         case widget_alignment::num_widget_alignments:
         default:
             break;
     }
     cata_fatal( "Invalid widget_alignment" );
 }
References cata_fatal, CENTER, LEFT, num_widget_alignments, and RIGHT.
enum_to_string< widget_var >()
template<> std::string io::enum_to_string< widget_var > (widget_var data)
Definition at line 64 of file widget.cpp.
 {
     switch( data ) {
         case widget_var::focus:
             return "focus";
         case widget_var::move:
             return "move";
         case widget_var::move_remainder:
             return "move_remainder";
         case widget_var::move_cost:
             return "move_cost";
         case widget_var::mood:
             return "mood";
         case widget_var::pain:
             return "pain";
         case widget_var::sound:
             return "sound";
         case widget_var::speed:
             return "speed";
         case widget_var::stamina:
             return "stamina";
         case widget_var::sleepiness:
             return "sleepiness";
         case widget_var::health:
             return "health";
         case widget_var::weariness_level:
             return "weariness_level";
         case widget_var::mana:
             return "mana";
         case widget_var::max_mana:
             return "max_mana";
         case widget_var::power_percentage:
             return "power_percentage";
         case widget_var::log_power_balance:
             return "log_power_balance";
         case widget_var::morale_level:
             return "morale_level";
         // Compass
         case widget_var::compass_text:
             return "compass_text";
         case widget_var::compass_legend_text:
             return "compass_legend_text";
         // Base stats
         case widget_var::stat_str:
             return "stat_str";
         case widget_var::stat_dex:
             return "stat_dex";
         case widget_var::stat_int:
             return "stat_int";
         case widget_var::stat_per:
             return "stat_per";
         // Bodypart attributes
         case widget_var::bp_hp:
             return "bp_hp";
         case widget_var::bp_encumb:
             return "bp_encumb";
         case widget_var::bp_warmth:
             return "bp_warmth";
         case widget_var::bp_wetness:
             return "bp_wetness";
         case widget_var::cardio_fit:
             return "cardio_fit";
         case widget_var::cardio_acc:
             return "cardio_acc";
         case widget_var::carry_weight:
             return "carry_weight";
         // Description functions
         case widget_var::activity_text:
             return "activity_text";
         case widget_var::body_graph:
             return "body_graph";
         case widget_var::body_graph_temp:
             return "body_graph_temp";
         case widget_var::body_graph_encumb:
             return "body_graph_encumb";
         case widget_var::body_graph_status:
             return "body_graph_status";
         case widget_var::body_graph_wet:
             return "body_graph_wet";
         case widget_var::bp_armor_outer_text:
             return "bp_armor_outer_text";
         case widget_var::carry_weight_text:
             return "carry_weight_text";
         case widget_var::date_text:
             return "date_text";
         case widget_var::env_temp_text:
             return "env_temp_text";
         case widget_var::mood_text:
             return "mood_text";
         case widget_var::move_count_mode_text:
             return "move_count_mode_text";
         case widget_var::pain_text:
             return "pain_text";
         case widget_var::overmap_loc_text:
             return "overmap_loc_text";
         case widget_var::overmap_text:
             return "overmap_text";
         case widget_var::place_text:
             return "place_text";
         case widget_var::power_text:
             return "power_text";
         case widget_var::power_balance_text:
             return "power_balance_text";
         case widget_var::safe_mode_text:
             return "safe_mode_text";
         case widget_var::safe_mode_classic_text:
             return "safe_mode_classic_text";
         case widget_var::style_text:
             return "style_text";
         case widget_var::sundial_text:
             return "sundial_text";
         case widget_var::sundial_time_text:
             return "sundial_time_text";
         case widget_var::time_text:
             return "time_text";
         case widget_var::veh_azimuth_text:
             return "veh_azimuth_text";
         case widget_var::veh_cruise_text:
             return "veh_cruise_text";
         case widget_var::veh_fuel_text:
             return "veh_fuel_text";
         case widget_var::weariness_text:
             return "weariness_text";
         case widget_var::weary_transition_level:
             return "weary_transition_level";
         case widget_var::weary_malus_text:
             return "weary_malus_text";
         case widget_var::weather_text:
             return "weather_text";
         case widget_var::wielding_text:
             return "wielding_text";
         case widget_var::wielding_simple_text:
             return "wielding_simple_text";
         case widget_var::wielding_mode_text:
             return "wielding_mode_text";
         case widget_var::wielding_ammo_text:
             return "wielding_ammo_text";
         case widget_var::wind_text:
             return "wind_text";
         // Fall-through - invalid
         case widget_var::last:
             break;
     }
     cata_fatal( "Invalid widget_var" );
 }
References activity_text, body_graph, body_graph_encumb, body_graph_status, body_graph_temp, body_graph_wet, bp_armor_outer_text, bp_encumb, bp_hp, bp_warmth, bp_wetness, cardio_acc, cardio_fit, carry_weight, carry_weight_text, cata_fatal, compass_legend_text, compass_text, date_text, env_temp_text, focus, health, last, log_power_balance, mana, max_mana, mood, mood_text, morale_level, move, move_cost, move_count_mode_text, move_remainder, overmap_loc_text, overmap_text, pain, pain_text, place_text, power_balance_text, power_percentage, power_text, safe_mode_classic_text, safe_mode_text, sleepiness, sound, speed, stamina, stat_dex, stat_int, stat_per, stat_str, style_text, sundial_text, sundial_time_text, time_text, veh_azimuth_text, veh_cruise_text, veh_fuel_text, weariness_level, weariness_text, weary_malus_text, weary_transition_level, weather_text, wielding_ammo_text, wielding_mode_text, wielding_simple_text, wielding_text, and wind_text.
Referenced by widget::color_text_function_string().
get_enum_lookup_map()
template<typename E > const std::unordered_map<std::string, E>& io::get_enum_lookup_map ()
Definition at line 65 of file enum_conversions.h.
 {
     static const std::unordered_map<std::string, E> string_to_enum_map =
         build_enum_lookup_map<E>();
     return string_to_enum_map;
 }
string_to_enum()
template<typename E > E io::string_to_enum (const std::string & data)
Definition at line 85 of file enum_conversions.h.
 {
     return string_to_enum_look_up( get_enum_lookup_map<E>(), data );
 }
References string_to_enum_look_up().
string_to_enum_look_up()
template<typename C , typename E = typename C::mapped_type> E io::string_to_enum_look_up (const C & container, const std::string & data) inline
Definition at line 74 of file enum_conversions.h.
 {
     const auto iter = container.find( data );
     if( iter == container.end() ) {
         throw InvalidEnumString( "Invalid enum string '" + data + "' for '" +
                                  demangle( typeid( E ).name() ) + "'" );
     }
     return iter->second;
 }
References demangle(), and om_direction::name().
Referenced by string_to_enum().
string_to_enum_look_up_optional()
template<typename C , typename E = typename C::mapped_type> std::optional<E> io::string_to_enum_look_up_optional (const C & container, const std::string & data) inline
Definition at line 92 of file enum_conversions.h.
 {
     const auto iter = container.find( data );
     if( iter == container.end() ) {
         return std::nullopt;
     }
     return iter->second;
 }
Referenced by string_to_enum_optional().
string_to_enum_optional()
template<typename E > std::optional<E> io::string_to_enum_optional (const std::string & data)
Definition at line 103 of file enum_conversions.h.
 {
     return string_to_enum_look_up_optional( get_enum_lookup_map<E>(), data );
 }
References string_to_enum_look_up_optional().