Cataclysm DDA: anonymous_namespace{system_locale.cpp} Namespace Reference
anonymous_namespace{system_locale.cpp} Namespace Reference
Functions
std::optional< std::string > matchGameLanguage (const std::string_view lang)
Function Documentation
matchGameLanguage()
std::optional<std::string> anonymous_namespace{system_locale.cpp}::matchGameLanguage (const std::string_view lang)
Definition at line 31 of file system_locale.cpp.
 {
     const std::vector<options_manager::id_and_option> available_languages =
         get_options().get_option( "USE_LANG" ).getItems();
     for( const options_manager::id_and_option &available_language : available_languages ) {
         if( !available_language.first.empty() && string_starts_with( lang, available_language.first ) ) {
             return available_language.first;
         }
     }
     return std::nullopt;
 }
References options_manager::get_option(), get_options(), options_manager::cOpt::getItems(), and string_starts_with().
Referenced by SystemLocale::Language().