Cataclysm DDA: behavior Namespace Reference
behavior Namespace Reference
Classes
struct behavior_return
class tree
class node_t
class oracle_t
An oracle is a class in charge of introspecting into a game entity in a particular way.
class strategy_t
class sequential_t
class fallback_t
class sequential_until_done_t
class character_oracle_t
class monster_oracle_t
Enumerations
enum class status_t : char { running , success , failure }
Functions
void load_behavior (const JsonObject &jo, const std::string &src)
void reset ()
void finalize ()
void check_consistency ()
status_t return_running (const oracle_t *, const std::string_view)
static std::function< status_t(const oracle_t *, std::string_view) > make_function (status_t(character_oracle_t::*fun)(std::string_view) const)
static std::function< status_t(const oracle_t *, std::string_view) > make_function (status_t(monster_oracle_t::*fun)(std::string_view) const)
Variables
std::unordered_map< std::string, std::function< status_t(const oracle_t *, std::string_view) > > predicate_map
static sequential_t default_sequential
static fallback_t default_fallback
static sequential_until_done_t default_until_done
std::unordered_map< std::string, const strategy_t * > strategy_map
Enumeration Type Documentation
status_t
enum behavior::status_t : char strong
Enumerator
running
success
failure
Definition at line 23 of file behavior.h.
 : char { running, success, failure };
Function Documentation
check_consistency()
void behavior::check_consistency ()
Definition at line 209 of file behavior.cpp.
 {
     for( const node_t &checked_node : behavior_factory.get_all() ) {
         checked_node.check();
     }
 }
References anonymous_namespace{behavior.cpp}::behavior_factory.
Referenced by DynamicDataLoader::check_consistency().
finalize()
void behavior::finalize ()
Definition at line 198 of file behavior.cpp.
 {
     for( const node_data &new_node : temp_node_data ) {
         for( const std::string &child : new_node.children ) {
             const_cast<node_t &>( new_node.id.obj() ).
             add_child( &string_id<node_t>( child ).obj() );
         }
     }
     temp_node_data.clear();
 }
References string_id< T >::obj(), and anonymous_namespace{behavior.cpp}::temp_node_data.
Referenced by overmap_terrains::finalize(), overmap_land_use_codes::finalize(), overmap_specials::finalize(), overmap_locations::finalize(), ammo_effects::finalize_all(), effect_on_conditions::finalize_all(), field_types::finalize_all(), start_locations::finalize_all(), weather_types::finalize_all(), and DynamicDataLoader::finalize_loaded_data().
load_behavior()
void behavior::load_behavior (const JsonObject & jo, const std::string & src)
Definition at line 132 of file behavior.cpp.
 {
     behavior_factory.load( jo, src );
 }
References anonymous_namespace{behavior.cpp}::behavior_factory.
Referenced by DynamicDataLoader::initialize().
make_function() [1/2]
static std::function< status_t(const oracle_t *, std::string_view) > behavior::make_function (status_t(character_oracle_t::*)(std::string_view) const fun) static
Definition at line 21 of file behavior_oracle.cpp.
 {
     return static_cast<status_t ( oracle_t::* )( const std::string_view ) const>( fun );
 }
make_function() [2/2]
static std::function< status_t(const oracle_t *, std::string_view) > behavior::make_function (status_t(monster_oracle_t::*)(std::string_view) const fun) static
Definition at line 27 of file behavior_oracle.cpp.
 {
     return static_cast<status_t ( oracle_t::* )( std::string_view ) const>( fun );
 }
reset()
void behavior::reset ()
Definition at line 192 of file behavior.cpp.
 {
     temp_node_data.clear();
     behavior_factory.reset();
 }
References anonymous_namespace{behavior.cpp}::behavior_factory, and anonymous_namespace{behavior.cpp}::temp_node_data.
Referenced by DynamicDataLoader::unload_data().
return_running()
status_t behavior::return_running (const oracle_t * , const std::string_view)
Definition at line 14 of file behavior_oracle.cpp.
 {
     return status_t::running;
 }
References running.
Variable Documentation
default_fallback
fallback_t behavior::default_fallback static
Definition at line 10 of file behavior_strategy.cpp.
default_sequential
sequential_t behavior::default_sequential static
Definition at line 9 of file behavior_strategy.cpp.
default_until_done
sequential_until_done_t behavior::default_until_done static
Definition at line 11 of file behavior_strategy.cpp.
predicate_map
std::unordered_map< std::string, std::function< status_t(const oracle_t *, std::string_view)> > behavior::predicate_map
Initial value:
= {{
        { "npc_needs_warmth_badly", make_function( &character_oracle_t::needs_warmth_badly ) },
        { "npc_needs_water_badly", make_function( &character_oracle_t::needs_water_badly ) },
        { "npc_needs_food_badly", make_function( &character_oracle_t::needs_food_badly ) },
        { "npc_can_wear_warmer_clothes", make_function( &character_oracle_t::can_wear_warmer_clothes ) },
        { "npc_can_make_fire", make_function( &character_oracle_t::can_make_fire ) },
        { "npc_can_take_shelter", make_function( &character_oracle_t::can_take_shelter ) },
        { "npc_has_water", make_function( &character_oracle_t::has_water ) },
        { "npc_has_food", make_function( &character_oracle_t::has_food ) },
        { "monster_not_hallucination", make_function( &monster_oracle_t::not_hallucination ) },
        { "monster_items_available", make_function( &monster_oracle_t::items_available ) },
        { "monster_split_possible", make_function( &monster_oracle_t::split_possible ) },
        { "monster_adjacent_plants", make_function( &monster_oracle_t::adjacent_plants ) },
        { "monster_special_available", make_function( &monster_oracle_t::special_available ) }
    }
}
Definition at line 33 of file behavior_oracle.cpp.
Referenced by behavior::node_t::load().
strategy_map
std::unordered_map< std::string, const strategy_t * > behavior::strategy_map
Initial value:
= {{
        { "sequential", &default_sequential },
        { "fallback", &default_fallback },
        { "sequential_until_done", &default_until_done }
    }
}
Definition at line 13 of file behavior_strategy.cpp.
Referenced by behavior::node_t::load(), and mtype::set_strategy().