Cataclysm DDA: anonymous_namespace{activity_item_handling.cpp} Namespace Reference
anonymous_namespace{activity_item_handling.cpp} Namespace Reference
Typedefs
using checked_cache_t = std::vector< construction_id >
Functions
faction_id _fac_id (Character &you)
bool _can_construct (tripoint_bub_ms const &loc, construction_id const &idx, construction const &check, std::optional< construction_id > const &part_con_idx)
construction const * _find_alt_construction (tripoint_bub_ms const &loc, construction_id const &idx, std::optional< construction_id > const &part_con_idx, std::function< bool(construction const &)> const &filter)
template<class ID >
ID _get_id (construction_id const &idx)
construction const * _find_prereq (tripoint_bub_ms const &loc, construction_id const &idx, construction_id const &top_idx, std::optional< construction_id > const &part_con_idx, checked_cache_t &checked_cache)
bool already_done (construction const &build, tripoint_bub_ms const &loc)
void _tidy_move_items (Character &you, item_stack &stack, tripoint_bub_ms const &src_loc, tripoint_bub_ms const &dst_loc, const std::optional< vpart_reference > &vpr_src, activity_id const &activity_to_restore)
Typedef Documentation
checked_cache_t
using anonymous_namespace{activity_item_handling.cpp}::checked_cache_t = typedef std::vector<construction_id>
Definition at line 796 of file activity_item_handling.cpp.
Function Documentation
_can_construct()
bool anonymous_namespace{activity_item_handling.cpp}::_can_construct (tripoint_bub_ms const & loc, construction_id const & idx, construction const & check, std::optional< construction_id > const & part_con_idx)
Definition at line 768 of file activity_item_handling.cpp.
 {
     return ( part_con_idx && *part_con_idx == check.id ) ||
            ( check.pre_terrain != idx->post_terrain && can_construct( check, loc ) );
 }
References can_construct(), check(), and construction::post_terrain.
Referenced by _find_alt_construction(), and _find_prereq().
_fac_id()
faction_id anonymous_namespace{activity_item_handling.cpp}::_fac_id (Character & you)
Definition at line 160 of file activity_item_handling.cpp.
 {
     faction const *fac = you.get_faction();
     return fac == nullptr ? faction_id() : fac->id;
 }
References Character::get_faction(), and faction_template::id.
Referenced by activity_on_turn_move_loot(), add_basecamp_storage_to_loot_zone_list(), are_requirements_nearby(), can_do_activity_there(), generic_multi_activity_check_requirement(), generic_multi_activity_do(), generic_multi_activity_locations(), get_auto_consume_moves(), requirements_map(), tidy_activity(), and try_fuel_fire().
_find_alt_construction()
construction const* anonymous_namespace{activity_item_handling.cpp}::_find_alt_construction (tripoint_bub_ms const & loc, construction_id const & idx, std::optional< construction_id > const & part_con_idx, std::function< bool(construction const &)> const & filter)
Definition at line 777 of file activity_item_handling.cpp.
 {
     std::vector<construction *> cons = constructions_by_filter( filter );
     for( construction const *el : cons ) {
         if( _can_construct( loc, idx, *el, part_con_idx ) ) {
             return el;
         }
     }
     return nullptr;
 }
References _can_construct(), constructions_by_filter(), and filter.
Referenced by find_base_construction().
_find_prereq()
construction const* anonymous_namespace{activity_item_handling.cpp}::_find_prereq (tripoint_bub_ms const & loc, construction_id const & idx, construction_id const & top_idx, std::optional< construction_id > const & part_con_idx, checked_cache_t & checked_cache)
Definition at line 797 of file activity_item_handling.cpp.
 {
     construction const *con = nullptr;
     std::vector<construction *> cons = constructions_by_filter( [&idx, &top_idx](
     construction const & it ) {
         furn_id const f = top_idx->post_is_furniture ? _get_id<furn_id>( top_idx ) : furn_id();
         ter_id const t = top_idx->post_is_furniture ? ter_id() : _get_id<ter_id>( top_idx );
         return it.group != idx->group && !it.post_terrain.empty() &&
                it.post_terrain == idx->pre_terrain &&
                // don't get stuck building and deconstructing the top level post_terrain
                it.pre_terrain != top_idx->post_terrain &&
                ( it.pre_flags.empty() || !can_construct_furn_ter( it, f, t ) );
     } );
     for( construction const *gcon : cons ) {
         if( std::find( checked_cache.begin(), checked_cache.end(), gcon->id ) !=
             checked_cache.end() ) {
             continue;
         }
         checked_cache.emplace_back( gcon->id );
         if( _can_construct( loc, idx, *gcon, part_con_idx ) ) {
             return gcon;
         }
         // try to find a prerequisite of this prerequisite
         if( !gcon->pre_terrain.empty() || !gcon->pre_flags.empty() ) {
             con = _find_prereq( loc, gcon->id, top_idx, part_con_idx, checked_cache );
         }
         if( con != nullptr ) {
             return con;
         }
     }
     return nullptr;
 }
References _can_construct(), can_construct_furn_ter(), constructions_by_filter(), construction::group, construction::post_is_furniture, construction::post_terrain, construction::pre_flags, and construction::pre_terrain.
Referenced by find_base_construction().
_get_id()
template<class ID > ID anonymous_namespace{activity_item_handling.cpp}::_get_id (construction_id const & idx)
Definition at line 791 of file activity_item_handling.cpp.
 {
     return idx->post_terrain.empty() ? ID() : ID( idx->post_terrain );
 }
References construction::post_terrain.
_tidy_move_items()
void anonymous_namespace{activity_item_handling.cpp}::_tidy_move_items (Character & you, item_stack & stack, tripoint_bub_ms const & src_loc, tripoint_bub_ms const & dst_loc, const std::optional< vpart_reference > & vpr_src, activity_id const & activity_to_restore)
Definition at line 1756 of file activity_item_handling.cpp.
 {
     for( item &it : stack ) {
         if( it.has_var( "activity_var" ) && it.get_var( "activity_var", "" ) == you.name ) {
             move_item( you, it, it.count(), src_loc, dst_loc, vpr_src, activity_to_restore );
             break;
         }
     }
 }
References item::count(), item::get_var(), item::has_var(), move_item(), and Character::name.
Referenced by tidy_activity().
already_done()
bool anonymous_namespace{activity_item_handling.cpp}::already_done (construction const & build, tripoint_bub_ms const & loc)
Definition at line 833 of file activity_item_handling.cpp.
 {
     map &here = get_map();
     const furn_id furn = here.furn( loc );
     const ter_id ter = here.ter( loc );
     return !build.post_terrain.empty() &&
            ( ( !build.post_is_furniture && ter_id( build.post_terrain ) == ter ) ||
              ( build.post_is_furniture && furn_id( build.post_terrain ) == furn ) );
 }
References map::furn(), get_map(), construction::post_is_furniture, construction::post_terrain, and map::ter().
Referenced by find_base_construction().