Cataclysm DDA: PATH_INFO Namespace Reference
PATH_INFO Namespace Reference
Functions
void init_base_path (const std::string &path)
void init_user_dir (std::string dir)
void set_standard_filenames ()
std::string base_path ()
std::string cache_dir ()
std::string config_dir ()
std::string datadir ()
std::string debug ()
std::string defaulttilejson ()
std::string defaultlayeringjson ()
std::string defaulttilepng ()
std::string fontdir ()
std::string user_font ()
std::string graveyarddir ()
std::string keymap ()
std::string memorialdir ()
std::string achievementdir ()
std::string player_base_save_path ()
std::string savedir ()
std::string sokoban ()
std::string templatedir ()
std::string user_dir ()
std::string user_moddir ()
std::string world_base_save_path ()
std::string worldoptions ()
std::string crash ()
std::string tileset_conf ()
std::string langdir ()
std::string lang_file ()
std::string soundpack_conf ()
std::string credits ()
std::string motd ()
std::string title (holiday current_holiday)
cata_path autopickup ()
cata_path autonote ()
cata_path base_colors ()
cata_path base_path_path ()
cata_path color_templates ()
cata_path color_themes ()
cata_path colors ()
cata_path config_dir_path ()
cata_path custom_colors ()
cata_path data_sound ()
cata_path datadir_path ()
cata_path defaultsounddir ()
cata_path fontdata ()
cata_path gfxdir ()
cata_path help ()
cata_path jsondir ()
cata_path keybindings ()
cata_path keybindings_vehicle ()
cata_path langdir_path ()
cata_path lastworld ()
cata_path legacy_fontdata ()
cata_path memorialdir_path ()
cata_path achievementdir_path ()
cata_path moddir ()
cata_path mods_dev_default ()
cata_path mods_user_default ()
cata_path mods_replacements ()
cata_path names ()
cata_path options ()
cata_path panel_options ()
cata_path player_base_save_path_path ()
cata_path pocket_presets ()
cata_path safemode ()
cata_path savedir_path ()
cata_path templatedir_path ()
cata_path user_dir_path ()
cata_path user_gfx ()
cata_path user_keybindings ()
cata_path user_moddir_path ()
cata_path user_sound ()
cata_path world_base_save_path_path ()
void set_datadir (const std::string &datadir)
void set_config_dir (const std::string &config_dir)
void set_savedir (const std::string &savedir)
void set_memorialdir (const std::string &memorialdir)
void set_options (const std::string &options)
void set_keymap (const std::string &keymap)
void set_autopickup (const std::string &autopickup)
void set_motd (const std::string &motd)
Function Documentation
achievementdir()
std::string PATH_INFO::achievementdir ()
Definition at line 334 of file path_info.cpp.
 {
     return achievementdir_value;
 }
References achievementdir_value.
Referenced by game::save_achievements().
achievementdir_path()
cata_path PATH_INFO::achievementdir_path ()
Definition at line 342 of file path_info.cpp.
 {
     return achievementdir_path_value;
 }
References achievementdir_path_value.
Referenced by past_achievements_info::load().
autonote()
cata_path PATH_INFO::autonote ()
Definition at line 218 of file path_info.cpp.
 {
     return autonote_path_value;
 }
References autonote_path_value.
Referenced by auto_notes::auto_note_settings::load(), and auto_notes::auto_note_settings::save().
autopickup()
cata_path PATH_INFO::autopickup ()
Definition at line 214 of file path_info.cpp.
 {
     return autopickup_path_value;
 }
References autopickup_path_value.
Referenced by Pickup::autopickup(), Pickup::do_pickup(), auto_pickup::player_settings::load(), pick_one_up(), auto_pickup::player_settings::save(), and set_autopickup().
base_colors()
cata_path PATH_INFO::base_colors ()
Definition at line 222 of file path_info.cpp.
 {
     return config_dir_path_value / "base_colors.json";
 }
References config_dir_path_value.
Referenced by color_loader< ColorType >::load(), and color_manager::show_gui().
base_path()
std::string PATH_INFO::base_path ()
Definition at line 226 of file path_info.cpp.
 {
     return base_path_value;
 }
References base_path_value.
Referenced by DynamicDataLoader::add(), anonymous_namespace{json_loader.cpp}::base_cache(), find_translated_file(), DynamicDataLoader::load_all_from_json(), load_mod_tileset(), DynamicDataLoader::load_object(), and locale_dir().
base_path_path()
cata_path PATH_INFO::base_path_path ()
Definition at line 230 of file path_info.cpp.
 {
     return base_path_path_value;
 }
References base_path_path_value.
cache_dir()
std::string PATH_INFO::cache_dir ()
Definition at line 234 of file path_info.cpp.
 {
     return datadir_value + "cache/";
 }
References datadir_value.
color_templates()
cata_path PATH_INFO::color_templates ()
Definition at line 242 of file path_info.cpp.
 {
     return datadir_path_value / "raw" / "color_templates";
 }
References datadir_path_value.
Referenced by color_manager::show_gui().
color_themes()
cata_path PATH_INFO::color_themes ()
Definition at line 246 of file path_info.cpp.
 {
     return datadir_path_value / "raw" / "color_themes";
 }
References datadir_path_value.
Referenced by color_manager::show_gui().
colors()
cata_path PATH_INFO::colors ()
Definition at line 238 of file path_info.cpp.
 {
     return datadir_path_value / "raw" / "colors.json";
 }
References datadir_path_value.
Referenced by Character::conduct_blood_analysis(), get_bar(), color_loader< ColorType >::load(), msgtype_to_color(), sev(), and auto_notes::auto_note_manager_gui::show().
config_dir()
std::string PATH_INFO::config_dir ()
Definition at line 250 of file path_info.cpp.
 {
     return config_dir_value;
 }
References config_dir_value.
Referenced by anonymous_namespace{main.cpp}::assure_essential_dirs_exist(), anonymous_namespace{json_loader.cpp}::config_cache(), color_loader< ColorType >::load(), and set_config_dir().
config_dir_path()
cata_path PATH_INFO::config_dir_path ()
Definition at line 254 of file path_info.cpp.
 {
     return config_dir_path_value;
 }
References config_dir_path_value.
Referenced by anonymous_namespace{debug_menu.cpp}::write_min_archive().
crash()
std::string PATH_INFO::crash ()
Definition at line 422 of file path_info.cpp.
 {
     return config_dir_value + "crash.log";
 }
References config_dir_value.
credits()
std::string PATH_INFO::credits ()
Definition at line 467 of file path_info.cpp.
 {
     return find_translated_file( datadir_value + "credits/", ".credits",
                                  datadir_value + "credits/" + "en.credits" );
 }
References datadir_value, and find_translated_file().
Referenced by main_menu::init_strings().
custom_colors()
cata_path PATH_INFO::custom_colors ()
Definition at line 258 of file path_info.cpp.
 {
     return config_dir_path_value / "custom_colors.json";
 }
References config_dir_path_value.
Referenced by color_manager::load_custom(), and color_manager::save_custom().
data_sound()
cata_path PATH_INFO::data_sound ()
Definition at line 462 of file path_info.cpp.
 {
     return datadir_path_value / "sound";
 }
References datadir_path_value.
Referenced by options_manager::build_soundpacks_list().
datadir()
std::string PATH_INFO::datadir ()
Definition at line 262 of file path_info.cpp.
 {
     return datadir_value;
 }
References datadir_value.
Referenced by anonymous_namespace{json_loader.cpp}::data_cache(), main(), anonymous_namespace{main.cpp}::printVersionMessage(), and set_datadir().
datadir_path()
cata_path PATH_INFO::datadir_path ()
Definition at line 266 of file path_info.cpp.
 {
     return datadir_path_value;
 }
References datadir_path_value.
debug()
std::string PATH_INFO::debug ()
Definition at line 270 of file path_info.cpp.
 {
     return config_dir_value + "debug.log";
 }
References config_dir_value.
Referenced by debug_error_prompt(), and setupDebug().
defaultlayeringjson()
std::string PATH_INFO::defaultlayeringjson ()
Definition at line 282 of file path_info.cpp.
 {
     return "layering.json";
 }
defaultsounddir()
cata_path PATH_INFO::defaultsounddir ()
Definition at line 274 of file path_info.cpp.
 {
     return datadir_path_value / "sound";
 }
References datadir_path_value.
defaulttilejson()
std::string PATH_INFO::defaulttilejson ()
Definition at line 278 of file path_info.cpp.
 {
     return "tile_config.json";
 }
defaulttilepng()
std::string PATH_INFO::defaulttilepng ()
Definition at line 286 of file path_info.cpp.
 {
     return "tinytile.png";
 }
fontdata()
cata_path PATH_INFO::fontdata ()
Definition at line 290 of file path_info.cpp.
 {
     return config_dir_path_value / "fonts.json";
 }
References config_dir_path_value.
fontdir()
std::string PATH_INFO::fontdir ()
Definition at line 294 of file path_info.cpp.
 {
     return datadir_value + "font/";
 }
References datadir_value.
gfxdir()
cata_path PATH_INFO::gfxdir ()
Definition at line 446 of file path_info.cpp.
 {
     return gfxdir_path_value;
 }
References gfxdir_path_value.
Referenced by options_manager::build_tilesets_list().
graveyarddir()
std::string PATH_INFO::graveyarddir ()
Definition at line 302 of file path_info.cpp.
 {
     return user_dir_value + "graveyard/";
 }
References user_dir_value.
Referenced by game::move_save_to_graveyard().
help()
cata_path PATH_INFO::help ()
Definition at line 306 of file path_info.cpp.
 {
     return datadir_path_value / "help" / "texts.json";
 }
References datadir_path_value.
Referenced by help::load().
init_base_path()
void PATH_INFO::init_base_path (const std::string & path)
Definition at line 73 of file path_info.cpp.
 {
     base_path_value = as_norm_dir( path );
     base_path_path_value = cata_path{ cata_path::root_path::base, fs::path{} };
 }
References as_norm_dir(), cata_path::base, base_path_path_value, and base_path_value.
Referenced by main(), and anonymous_namespace{main.cpp}::parse_commandline().
init_user_dir()
void PATH_INFO::init_user_dir (std::string dir)
Definition at line 79 of file path_info.cpp.
 {
     if( dir.empty() ) {
         const char *user_dir;
 #if defined(_WIN32)
         user_dir = getenv_or_abort( "LOCALAPPDATA" );
         // On Windows userdir without dot
         dir = std::string( user_dir ) + "/cataclysm-dda/";
 #elif defined(MACOSX)
         user_dir = getenv_or_abort( "HOME" );
         dir = std::string( user_dir ) + "/Library/Application Support/Cataclysm/";
 #elif defined(USE_XDG_DIR)
         if( ( user_dir = getenv( "XDG_DATA_HOME" ) ) ) {
             dir = std::string( user_dir ) + "/cataclysm-dda/";
         } else {
             user_dir = getenv_or_abort( "HOME" );
             dir = std::string( user_dir ) + "/.local/share/cataclysm-dda/";
         }
 #else
         user_dir = getenv_or_abort( "HOME" );
         dir = std::string( user_dir ) + "/.cataclysm-dda/";
 #endif
     }
     user_dir_value = as_norm_dir( dir );
     user_dir_path_value = cata_path{ cata_path::root_path::user, fs::path{} };
 }
References as_norm_dir(), getenv_or_abort(), cata_path::user, user_dir(), user_dir_path_value, and user_dir_value.
Referenced by main(), and anonymous_namespace{main.cpp}::parse_commandline().
jsondir()
cata_path PATH_INFO::jsondir ()
Definition at line 346 of file path_info.cpp.
 {
     return datadir_path_value / "core";
 }
References datadir_path_value.
Referenced by game::load_core_data().
keybindings()
cata_path PATH_INFO::keybindings ()
Definition at line 310 of file path_info.cpp.
 {
     return datadir_path_value / "raw" / "keybindings.json";
 }
References datadir_path_value.
Referenced by input_manager::init().
keybindings_vehicle()
cata_path PATH_INFO::keybindings_vehicle ()
Definition at line 314 of file path_info.cpp.
 {
     return datadir_path_value / "raw" / "keybindings" / "vehicle.json";
 }
References datadir_path_value.
Referenced by input_manager::init().
keymap()
std::string PATH_INFO::keymap ()
Definition at line 318 of file path_info.cpp.
 {
     return keymap_value;
 }
References keymap_value.
Referenced by input_manager::init(), load_keyboard_settings(), parse_keymap(), and set_keymap().
lang_file()
std::string PATH_INFO::lang_file ()
Definition at line 458 of file path_info.cpp.
 {
     return "cataclysm-dda.mo";
 }
Referenced by options_manager::get_langs_with_translation_files().
langdir()
std::string PATH_INFO::langdir ()
Definition at line 450 of file path_info.cpp.
 {
     return langdir_value;
 }
References langdir_value.
Referenced by locale_dir().
langdir_path()
cata_path PATH_INFO::langdir_path ()
Definition at line 454 of file path_info.cpp.
 {
     return langdir_path_value;
 }
References langdir_path_value.
lastworld()
cata_path PATH_INFO::lastworld ()
Definition at line 322 of file path_info.cpp.
 {
     return config_dir_path_value / "lastworld.json";
 }
References config_dir_path_value.
Referenced by worldfactory::load_last_world_info(), and worldfactory::save_last_world_info().
legacy_fontdata()
cata_path PATH_INFO::legacy_fontdata ()
Definition at line 326 of file path_info.cpp.
 {
     return datadir_path_value / "fontdata.json";
 }
References datadir_path_value.
memorialdir()
std::string PATH_INFO::memorialdir ()
Definition at line 330 of file path_info.cpp.
 {
     return memorialdir_value;
 }
References memorialdir_value.
Referenced by diary::export_to_txt(), anonymous_namespace{json_loader.cpp}::memorial_cache(), set_memorialdir(), and game::write_memorial_file().
memorialdir_path()
cata_path PATH_INFO::memorialdir_path ()
Definition at line 338 of file path_info.cpp.
 {
     return memorialdir_path_value;
 }
References memorialdir_path_value.
Referenced by past_games_info::ensure_loaded().
moddir()
cata_path PATH_INFO::moddir ()
Definition at line 350 of file path_info.cpp.
 {
     return datadir_path_value / "mods";
 }
References datadir_path_value.
Referenced by overmap::generate(), and mod_manager::refresh_mod_list().
mods_dev_default()
cata_path PATH_INFO::mods_dev_default ()
Definition at line 434 of file path_info.cpp.
 {
     return datadir_path_value / "mods" / "default.json";
 }
References datadir_path_value.
Referenced by mod_manager::refresh_mod_list().
mods_replacements()
cata_path PATH_INFO::mods_replacements ()
Definition at line 430 of file path_info.cpp.
 {
     return datadir_path_value / "mods" / "replacements.json";
 }
References datadir_path_value.
Referenced by mod_manager::mod_manager().
mods_user_default()
cata_path PATH_INFO::mods_user_default ()
Definition at line 438 of file path_info.cpp.
 {
     return config_dir_path_value / "user-default-mods.json";
 }
References config_dir_path_value.
Referenced by mod_manager::refresh_mod_list(), and mod_manager::set_default_mods().
motd()
std::string PATH_INFO::motd ()
Definition at line 473 of file path_info.cpp.
 {
     return find_translated_file( datadir_value + "motd/", ".motd", motd_value );
 }
References datadir_value, find_translated_file(), and motd_value.
Referenced by main_menu::init_strings(), and set_motd().
names()
cata_path PATH_INFO::names ()
Definition at line 530 of file path_info.cpp.
 {
     return find_translated_file( datadir_path_value / "names", ".json",
                                  datadir_path_value / "names" / "en.json" );
 }
References datadir_path_value, and find_translated_file().
Referenced by computer_session::action_list_bionics(), anonymous_namespace{armor_layers.cpp}::body_part_names(), snippet_library::clear_snippets(), display::colorized_compass_legend_text(), anonymous_namespace{line.cpp}::direction_name_impl(), pocket_favorite_callback::key(), color_loader< ColorType >::main_color_names(), om_direction::name(), normalize_relative_path(), photo_def_for_camera_point(), photo_quality_name(), game::place_player(), read_activity_actor::player_read(), set_language(), MAP_SHARING::setAdmins(), MAP_SHARING::setDebuggers(), and inventory_entry::update_cache().
options()
cata_path PATH_INFO::options ()
Definition at line 354 of file path_info.cpp.
 {
     return options_path_value;
 }
References options_path_value.
Referenced by activity_on_turn_move_loot(), zone_manager::add(), options_manager::add(), options_manager::add_external(), options_manager::add_value(), iexamine::autodoc(), leap_actor::call(), can_do_activity_there(), iexamine::compost_empty(), construction_menu(), zone_manager::custom_loot_has(), options_manager::deserialize(), unload_loot_activity_actor::do_turn(), map::draw_lab(), fire(), outfit::fire_options(), query_popup_impl::fold_query(), iexamine::fvat_empty(), plot_options::get_descriptions(), blueprint_options::get_descriptions(), ignorable_options::get_descriptions(), loot_options::get_descriptions(), unload_options::get_descriptions(), options_manager::get_lang_options(), options_manager::get_option(), options_manager::get_world_defaults(), options_manager::has_option(), options_manager::init(), zone_options::is_valid(), iexamine::keg(), options_manager::load(), mapgen_place_zone(), mutation_branch::pick_variant(), mutation_branch::pick_variant_menu(), iuse::radio_on(), map::random_outdoor_tile(), mutable_overmap_phase_remainder::satisfy(), options_manager::save(), options_manager::serialize(), set_options(), options_manager::set_world_options(), options_manager::show(), iexamine::tree_maple_tapped(), vehicle::turrets_aim_and_fire_single(), and game::zones_manager().
panel_options()
cata_path PATH_INFO::panel_options ()
Definition at line 358 of file path_info.cpp.
 {
     return config_dir_path_value / "panel_options.json";
 }
References config_dir_path_value.
Referenced by panel_manager::load(), and panel_manager::save().
player_base_save_path()
std::string PATH_INFO::player_base_save_path ()
Definition at line 13248 of file game.cpp.
 {
     return PATH_INFO::world_base_save_path() + "/" + base64_encode( get_avatar().get_save_id() );
 }
References base64_encode(), game::get_avatar, and world_base_save_path().
Referenced by auto_notes::auto_note_settings::save(), auto_pickup::player_settings::save(), and game::save_player_data().
player_base_save_path_path()
cata_path PATH_INFO::player_base_save_path_path ()
Definition at line 13253 of file game.cpp.
 {
     return PATH_INFO::world_base_save_path_path() / base64_encode( get_avatar().get_save_id() );
 }
References base64_encode(), game::get_avatar, and world_base_save_path_path().
Referenced by anonymous_namespace{clzones.cpp}::_savefile(), auto_notes::auto_note_settings::build_save_path(), find_mm_dir(), auto_pickup::player_settings::load(), safemode::load(), overmapbuffer::player_filename(), auto_pickup::player_settings::save(), and safemode::save().
pocket_presets()
cata_path PATH_INFO::pocket_presets ()
Definition at line 362 of file path_info.cpp.
 {
     return config_dir_path_value / "pocket_presets.json";
 }
References config_dir_path_value.
Referenced by item_pocket::load_presets(), and item_pocket::save_presets().
safemode()
cata_path PATH_INFO::safemode ()
Definition at line 366 of file path_info.cpp.
 {
     return config_dir_path_value / "safemode.json";
 }
References config_dir_path_value.
Referenced by safemode::load(), and safemode::save().
savedir()
std::string PATH_INFO::savedir ()
Definition at line 370 of file path_info.cpp.
 {
     return savedir_value;
 }
References savedir_value.
Referenced by anonymous_namespace{main.cpp}::assure_essential_dirs_exist(), anonymous_namespace{json_loader.cpp}::cache_for_save(), WORLD::folder_path(), worldfactory::init(), set_savedir(), and world_base_save_path().
savedir_path()
cata_path PATH_INFO::savedir_path ()
Definition at line 374 of file path_info.cpp.
 {
     return savedir_path_value;
 }
References savedir_path_value.
Referenced by WORLD::folder_path_path(), and world_base_save_path_path().
set_autopickup()
void PATH_INFO::set_autopickup (const std::string & autopickup)
Definition at line 584 of file path_info.cpp.
 {
     autopickup_value = autopickup;
     autopickup_path_value = cata_path{ cata_path::root_path::unknown, autopickup_value };
 }
References autopickup(), autopickup_path_value, autopickup_value, and cata_path::unknown.
Referenced by anonymous_namespace{main.cpp}::parse_commandline().
set_config_dir()
void PATH_INFO::set_config_dir (const std::string & config_dir)
Definition at line 549 of file path_info.cpp.
 {
     config_dir_value = config_dir;
     config_dir_path_value = cata_path{ cata_path::root_path::config, fs::path{} };
     options_value = config_dir_value + "options.json";
     options_path_value = config_dir_path_value / "options.json";
     keymap_value = config_dir_value + "keymap.txt";
     keymap_path_value = config_dir_path_value / "keymap.txt";
     autopickup_value = config_dir_value + "auto_pickup.json";
     autopickup_path_value = config_dir_path_value / "auto_pickup.json";
 }
References autopickup_path_value, autopickup_value, cata_path::config, config_dir(), config_dir_path_value, config_dir_value, keymap_path_value, keymap_value, options_path_value, and options_value.
Referenced by anonymous_namespace{main.cpp}::parse_commandline().
set_datadir()
void PATH_INFO::set_datadir (const std::string & datadir)
Definition at line 536 of file path_info.cpp.
 {
     datadir_value = datadir;
     datadir_path_value = cata_path{ cata_path::root_path::data, fs::path{} };
     // Shared dirs
     gfxdir_value = datadir_value + "gfx/";
     gfxdir_path_value = datadir_path_value / "gfx";
     // Shared files
     motd_value = datadir_value + "motd/" + "en.motd";
     motd_path_value = datadir_path_value / "motd" / "en.motd";
 }
References cata_path::data, datadir(), datadir_path_value, datadir_value, gfxdir_path_value, gfxdir_value, motd_path_value, and motd_value.
Referenced by anonymous_namespace{main.cpp}::parse_commandline().
set_keymap()
void PATH_INFO::set_keymap (const std::string & keymap)
Definition at line 579 of file path_info.cpp.
 {
     keymap_value = keymap;
 }
References keymap(), and keymap_value.
Referenced by anonymous_namespace{main.cpp}::parse_commandline().
set_memorialdir()
void PATH_INFO::set_memorialdir (const std::string & memorialdir)
Definition at line 567 of file path_info.cpp.
 {
     memorialdir_value = memorialdir;
     memorialdir_path_value = cata_path{ cata_path::root_path::memorial, fs::path{} };
 }
References cata_path::memorial, memorialdir(), memorialdir_path_value, and memorialdir_value.
Referenced by anonymous_namespace{main.cpp}::parse_commandline().
set_motd()
void PATH_INFO::set_motd (const std::string & motd)
Definition at line 590 of file path_info.cpp.
 {
     motd_value = motd;
 }
References motd(), and motd_value.
Referenced by anonymous_namespace{main.cpp}::parse_commandline().
set_options()
void PATH_INFO::set_options (const std::string & options)
Definition at line 573 of file path_info.cpp.
 {
     options_value = options;
     options_path_value = cata_path{cata_path::root_path::unknown, options_value};
 }
References options(), options_path_value, options_value, and cata_path::unknown.
Referenced by anonymous_namespace{main.cpp}::parse_commandline().
set_savedir()
void PATH_INFO::set_savedir (const std::string & savedir)
Definition at line 561 of file path_info.cpp.
 {
     savedir_value = savedir;
     savedir_path_value = cata_path{ cata_path::root_path::save, fs::path{} };
 }
References cata_path::save, savedir(), savedir_path_value, and savedir_value.
Referenced by anonymous_namespace{main.cpp}::parse_commandline().
set_standard_filenames()
void PATH_INFO::set_standard_filenames ()
Definition at line 107 of file path_info.cpp.
 {
     // Special: data_dir and gfx_dir
     std::string prefix;
     cata_path prefix_path;
     // Data is always relative to itself. Also, the base path might not be writeable.
     datadir_path_value = cata_path{ cata_path::root_path::data, fs::path{} };
     if( !base_path_value.empty() ) {
 #if defined(DATA_DIR_PREFIX)
         datadir_value = base_path_value + "share/cataclysm-dda/";
         prefix = datadir_value;
         prefix_path = datadir_path_value;
 #else
         datadir_value = base_path_value + "data/";
         prefix = base_path_value;
         prefix_path = base_path_path_value;
 #endif
     } else {
         datadir_value = "data/";
         // Base path is empty here but everything else is still relative to base, which is empty.
         prefix_path = base_path_path_value;
     }
     gfxdir_value = prefix + "gfx/";
     gfxdir_path_value = prefix_path / "gfx";
     langdir_value = prefix + "lang/mo/";
     langdir_path_value = prefix_path / "lang" / "mo";
     // Shared dirs
     // Shared files
     motd_value = datadir_value + "motd/" + "en.motd";
     savedir_value = user_dir_value + "save/";
     // Special: savedir is always relative to itself even if in the user dir location.
     savedir_path_value = cata_path{ cata_path::root_path::save, fs::path{} };
     memorialdir_value = user_dir_value + "memorial/";
     memorialdir_path_value = user_dir_path_value / "memorial";
     achievementdir_value = user_dir_value + "achievements/";
     achievementdir_path_value = user_dir_path_value / "achievements";
 #if defined(USE_XDG_DIR)
     const char *user_dir;
     std::string dir;
     if( ( user_dir = getenv( "XDG_CONFIG_HOME" ) ) ) {
         dir = std::string( user_dir ) + "/cataclysm-dda/";
     } else {
         user_dir = getenv_or_abort( "HOME" );
         dir = std::string( user_dir ) + "/.config/cataclysm-dda/";
     }
     config_dir_value = dir;
     config_dir_path_value = cata_path{ cata_path::root_path::config, fs::path{} };
 #else
     config_dir_value = user_dir_value + "config/";
     config_dir_path_value = user_dir_path_value / "config";
 #endif
     options_value = config_dir_value + "options.json";
     options_path_value = config_dir_path_value / "options.json";
     keymap_value = config_dir_value + "keymap.txt";
     autopickup_value = config_dir_value + "auto_pickup.json";
     autopickup_path_value = config_dir_path_value / "auto_pickup.json";
     autonote_value = config_dir_value + "auto_note.json";
     autonote_path_value = config_dir_path_value / "auto_note.json";
 }
References achievementdir_path_value, achievementdir_value, autonote_path_value, autonote_value, autopickup_path_value, autopickup_value, base_path_path_value, base_path_value, cata_path::config, config_dir_path_value, config_dir_value, cata_path::data, datadir_path_value, datadir_value, getenv_or_abort(), gfxdir_path_value, gfxdir_value, keymap_value, langdir_path_value, langdir_value, memorialdir_path_value, memorialdir_value, motd_value, options_path_value, options_value, cata_path::save, savedir_path_value, savedir_value, user_dir(), user_dir_path_value, and user_dir_value.
Referenced by main(), and anonymous_namespace{main.cpp}::parse_commandline().
sokoban()
std::string PATH_INFO::sokoban ()
Definition at line 378 of file path_info.cpp.
 {
     return datadir_value + "raw/" + "sokoban.txt";
 }
References datadir_value.
Referenced by sokoban_game::start_game().
soundpack_conf()
std::string PATH_INFO::soundpack_conf ()
Definition at line 442 of file path_info.cpp.
 {
     return "soundpack.txt";
 }
Referenced by options_manager::build_soundpacks_list().
templatedir()
std::string PATH_INFO::templatedir ()
Definition at line 382 of file path_info.cpp.
 {
     return user_dir_value + "templates/";
 }
References user_dir_value.
Referenced by anonymous_namespace{main.cpp}::assure_essential_dirs_exist(), main_menu::load_char_templates(), main_menu::new_character_tab(), and avatar::save_template().
templatedir_path()
cata_path PATH_INFO::templatedir_path ()
Definition at line 386 of file path_info.cpp.
 {
     return user_dir_path_value / "templates";
 }
References user_dir_path_value.
Referenced by avatar::load_template().
tileset_conf()
std::string PATH_INFO::tileset_conf ()
Definition at line 426 of file path_info.cpp.
 {
     return "tileset.txt";
 }
Referenced by options_manager::build_tilesets_list().
title()
std::string PATH_INFO::title (holiday current_holiday)
Definition at line 478 of file path_info.cpp.
 {
     std::string theme_basepath = datadir_value + "title/";
     std::string theme_extension = ".title";
     std::string theme_fallback = theme_basepath + "en.title";
     if( !get_option<bool>( "ENABLE_ASCII_TITLE" ) ) {
         return _( "Cataclysm: Dark Days Ahead" );
     }
     if( x_in_y( get_option<int>( "ALT_TITLE" ), 100 ) ) {
         theme_extension = ".alt1";
         theme_fallback = datadir_value + "title/" + "en.alt1";
     }
     if( !get_option<bool>( "SEASONAL_TITLE" ) ) {
         return find_translated_file( theme_basepath, theme_extension, theme_fallback );
     }
     switch( current_holiday ) {
         case holiday::new_year:
             theme_extension = ".new_year";
             theme_fallback = datadir_value + "title/" + "en.new_year";
             break;
         case holiday::easter:
             theme_extension = ".easter";
             theme_fallback = datadir_value + "title/" + "en.easter";
             break;
         case holiday::independence_day:
             theme_extension = ".independence_day";
             theme_fallback = datadir_value + "title/" + "en.independence_day";
             break;
         case holiday::halloween:
             theme_extension = ".halloween";
             theme_fallback = datadir_value + "title/" + "en.halloween";
             break;
         case holiday::thanksgiving:
             theme_extension = ".thanksgiving";
             theme_fallback = datadir_value + "title/" + "en.thanksgiving";
             break;
         case holiday::christmas:
             theme_extension = ".christmas";
             theme_fallback = datadir_value + "title/" + "en.christmas";
             break;
         case holiday::none:
         case holiday::num_holiday:
         default:
             break;
     }
     return find_translated_file( theme_basepath, theme_extension, theme_fallback );
 }
References _, christmas, datadir_value, easter, find_translated_file(), halloween, independence_day, new_year, none, num_holiday, thanksgiving, and x_in_y().
Referenced by main_menu::init_strings().
user_dir()
std::string PATH_INFO::user_dir ()
Definition at line 390 of file path_info.cpp.
 {
     return user_dir_value;
 }
References user_dir_value.
Referenced by init_user_dir(), main(), anonymous_namespace{main.cpp}::printVersionMessage(), set_standard_filenames(), and anonymous_namespace{json_loader.cpp}::user_cache().
user_dir_path()
cata_path PATH_INFO::user_dir_path ()
Definition at line 394 of file path_info.cpp.
 {
     return user_dir_path_value;
 }
References user_dir_path_value.
user_font()
std::string PATH_INFO::user_font ()
Definition at line 298 of file path_info.cpp.
 {
     return user_dir_value + "font/";
 }
References user_dir_value.
Referenced by anonymous_namespace{main.cpp}::assure_essential_dirs_exist().
user_gfx()
cata_path PATH_INFO::user_gfx ()
Definition at line 398 of file path_info.cpp.
 {
     return user_dir_path_value / "gfx";
 }
References user_dir_path_value.
Referenced by anonymous_namespace{main.cpp}::assure_essential_dirs_exist(), and options_manager::build_tilesets_list().
user_keybindings()
cata_path PATH_INFO::user_keybindings ()
Definition at line 402 of file path_info.cpp.
 {
     return config_dir_path_value / "keybindings.json";
 }
References config_dir_path_value.
Referenced by input_manager::init(), and input_manager::save().
user_moddir()
std::string PATH_INFO::user_moddir ()
Definition at line 406 of file path_info.cpp.
 {
     return user_dir_value + "mods/";
 }
References user_dir_value.
user_moddir_path()
cata_path PATH_INFO::user_moddir_path ()
Definition at line 410 of file path_info.cpp.
 {
     return user_dir_path_value / "mods";
 }
References user_dir_path_value.
Referenced by mod_manager::refresh_mod_list().
user_sound()
cata_path PATH_INFO::user_sound ()
Definition at line 414 of file path_info.cpp.
 {
     return user_dir_path_value / "sound";
 }
References user_dir_path_value.
Referenced by anonymous_namespace{main.cpp}::assure_essential_dirs_exist(), and options_manager::build_soundpacks_list().
world_base_save_path()
std::string PATH_INFO::world_base_save_path ()
Definition at line 13258 of file game.cpp.
 {
     if( world_generator->active_world == nullptr ) {
         return PATH_INFO::savedir();
     }
     return world_generator->active_world->folder_path();
 }
References savedir(), and world_generator.
Referenced by diary::export_to_txt(), game::move_save_to_graveyard(), player_base_save_path(), game::save(), mapbuffer::save(), game::save_factions_missions_npcs(), and diary::store().
world_base_save_path_path()
cata_path PATH_INFO::world_base_save_path_path ()
Definition at line 13266 of file game.cpp.
 {
     if( world_generator->active_world == nullptr ) {
         return PATH_INFO::savedir_path();
     }
     return world_generator->active_world->folder_path_path();
 }
References savedir_path(), and world_generator.
Referenced by anonymous_namespace{clzones.cpp}::_savefile(), find_dirname(), diary::load(), game::load(), game::load_master(), player_base_save_path_path(), game::save(), overmapbuffer::terrain_filename(), and anonymous_namespace{debug_menu.cpp}::write_min_archive().
worldoptions()
std::string PATH_INFO::worldoptions ()
Definition at line 418 of file path_info.cpp.
 {
     return "worldoptions.json";
 }
Referenced by worldfactory::init(), isForbidden(), WORLD::load_options(), and WORLD::save().