Cataclysm DDA: anonymous_namespace{condition.cpp} Namespace Reference
anonymous_namespace{condition.cpp} Namespace Reference
Classes
struct deferred_math
struct condition_parser
Functions
std::queue< deferred_math > & get_deferred_math ()
std::shared_ptr< math_exp > & defer_math (std::string_view str, bool ass)
Variables
std::unordered_map< std::string_view, int(talker::*)() const > const f_get_vals
std::unordered_map< std::string_view, void(talker::*)(int)> const f_set_vals
Function Documentation
defer_math()
std::shared_ptr<math_exp>& anonymous_namespace{condition.cpp}::defer_math (std::string_view str, bool ass)
Definition at line 149 of file condition.cpp.
 {
     get_deferred_math().emplace( str, ass );
     return get_deferred_math().back().exp;
 }
References get_deferred_math().
Referenced by eoc_math::from_json().
get_deferred_math()
std::queue<deferred_math>& anonymous_namespace{condition.cpp}::get_deferred_math ()
Definition at line 143 of file condition.cpp.
 {
     static std::queue<deferred_math> dfr_math;
     return dfr_math;
 }
Referenced by defer_math(), and finalize_conditions().
Variable Documentation
f_get_vals
std::unordered_map<std::string_view, int (talker::*)() const> const anonymous_namespace{condition.cpp}::f_get_vals
Definition at line 2034 of file condition.cpp.
Referenced by conditional_t::get_get_dbl().
f_set_vals
std::unordered_map<std::string_view, void (talker::*)(int)> const anonymous_namespace{condition.cpp}::f_set_vals
Initial value:
= {
    { "age", &talker::set_age },
    { "anger", &talker::set_anger },
    { "dexterity_base", &talker::set_dex_max },
    { "dexterity_bonus", &talker::set_dex_bonus },
    { "exp", &talker::set_kill_xp },
    { "sleepiness", &talker::set_sleepiness },
    { "friendly", &talker::set_friendly },
    { "height", &talker::set_height },
    { "intelligence_base", &talker::set_int_max },
    { "intelligence_bonus", &talker::set_int_bonus },
    { "mana", &talker::set_mana_cur },
    { "morale", &talker::set_morale },
    { "npc_anger", &talker::set_npc_anger },
    { "npc_fear", &talker::set_npc_fear },
    { "npc_trust", &talker::set_npc_trust },
    { "npc_value", &talker::set_npc_value },
    { "perception_base", &talker::set_per_max },
    { "perception_bonus", &talker::set_per_bonus },
    { "pkill", &talker::set_pkill },
    { "rad", &talker::set_rad },
    { "sleep_deprivation", &talker::set_sleep_deprivation },
    { "stamina", &talker::set_stamina },
    { "stim", &talker::set_stim },
    { "strength_base", &talker::set_str_max },
    { "strength_bonus", &talker::set_str_bonus },
    { "thirst", &talker::set_thirst },
}
Definition at line 2151 of file condition.cpp.
Referenced by conditional_t::get_set_dbl().