Cataclysm DDA: effect_on_conditions Namespace Reference
effect_on_conditions Namespace Reference
Functions
const std::vector< effect_on_condition > & get_all ()
Get all currently loaded effect_on_conditions.
void finalize_all ()
Finalize all loaded effect_on_conditions.
void reset ()
Clear all loaded effects on condition (invalidating any pointers)
void load (const JsonObject &jo, const std::string &src)
Load effect on condition from JSON definition.
void check_consistency ()
Checks all loaded from JSON are valid.
void load_new_character (Character &you)
Sets up the initial queue for a new character.
void load_existing_character (Character &you)
Load any new eocs that don't exist in the save.
effect_on_condition_id load_inline_eoc (const JsonValue &jv, const std::string &src)
Loads an inline eoc.
void queue_effect_on_condition (time_duration duration, effect_on_condition_id eoc, Character &you, const std::unordered_map< std::string, std::string > &context)
queue an eoc to happen in the future
void process_effect_on_conditions (Character &you)
called every turn to process the queued eocs
void process_reactivate (Character &you)
called after certain events to test whether to reactivate eocs
void process_reactivate ()
void clear (Character &you)
clear all queued and inactive eocs
void write_eocs_to_file (Character &you)
write out all queued eocs and inactive eocs to a file for testing
void write_global_eocs_to_file ()
void prevent_death ()
Run all prevent death eocs.
void avatar_death ()
Run all avatar death eocs.
void om_move ()
Run all OM_MOVE eocs.
Function Documentation
avatar_death()
void effect_on_conditions::avatar_death ()
Run all avatar death eocs.
Definition at line 454 of file effect_on_condition.cpp.
 {
     avatar &player_character = get_avatar();
     Creature *klr = player_character.get_killer();
     // Make sure the creature still exists in game
     klr = !klr ? klr : g->get_creature_if( [klr]( const Creature & c ) {
         return klr == &c;
     } );
     dialogue d( get_talker_for( get_avatar() ), klr == nullptr ? nullptr : get_talker_for( klr ) );
     for( const effect_on_condition &eoc : effect_on_conditions::get_all() ) {
         if( eoc.type == eoc_type::AVATAR_DEATH ) {
             eoc.activate( d );
         }
     }
 }
References AVATAR_DEATH, c, eoc, g, get_all(), get_avatar(), Creature::get_killer(), and get_talker_for().
Referenced by game::is_game_over().
check_consistency()
void effect_on_conditions::check_consistency ()
Checks all loaded from JSON are valid.
Definition at line 74 of file effect_on_condition.cpp.
 {
 }
Referenced by DynamicDataLoader::check_consistency().
clear()
void effect_on_conditions::clear (Character & you)
clear all queued and inactive eocs
Definition at line 367 of file effect_on_condition.cpp.
 {
     while( !you.queued_effect_on_conditions.empty() ) {
         you.queued_effect_on_conditions.pop();
     }
     you.inactive_effect_on_condition_vector.clear();
     while( !g->queued_global_effect_on_conditions.empty() ) {
         g->queued_global_effect_on_conditions.pop();
     }
     g->inactive_global_effect_on_condition_vector.clear();
 }
References queued_eocs::empty(), g, Character::inactive_effect_on_condition_vector, queued_eocs::pop(), and Character::queued_effect_on_conditions.
Referenced by game::setup().
finalize_all()
void effect_on_conditions::finalize_all ()
Finalize all loaded effect_on_conditions.
Definition at line 485 of file effect_on_condition.cpp.
 {
     effect_on_condition_factory.finalize();
     for( const effect_on_condition &eoc : effect_on_condition_factory.get_all() ) {
         const_cast<effect_on_condition &>( eoc ).finalize();
     }
 }
References anonymous_namespace{effect_on_condition.cpp}::effect_on_condition_factory, eoc, and behavior::finalize().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< effect_on_condition > & effect_on_conditions::get_all ()
Get all currently loaded effect_on_conditions.
Definition at line 497 of file effect_on_condition.cpp.
 {
     return effect_on_condition_factory.get_all();
 }
References anonymous_namespace{effect_on_condition.cpp}::effect_on_condition_factory.
Referenced by avatar_death(), debug_menu::debug(), load_existing_character(), load_new_character(), eoc_events::notify(), om_move(), and prevent_death().
load()
void effect_on_conditions::load (const JsonObject & jo, const std::string & src)
Load effect on condition from JSON definition.
Definition at line 507 of file effect_on_condition.cpp.
 {
     effect_on_condition_factory.load( jo, src );
 }
References anonymous_namespace{effect_on_condition.cpp}::effect_on_condition_factory.
Referenced by DynamicDataLoader::initialize().
load_existing_character()
void effect_on_conditions::load_existing_character (Character & you)
Load any new eocs that don't exist in the save.
Definition at line 193 of file effect_on_condition.cpp.
 {
     bool is_avatar = you.is_avatar();
     std::map<effect_on_condition_id, bool> new_eocs;
     for( const effect_on_condition &eoc : effect_on_conditions::get_all() ) {
         if( eoc.type == eoc_type::RECURRING && ( is_avatar || !eoc.global ) ) {
             new_eocs[eoc.id] = true;
         }
     }
     process_new_eocs( you.queued_effect_on_conditions, you.inactive_effect_on_condition_vector,
                       new_eocs, false );
     if( is_avatar ) {
         process_new_eocs( g->queued_global_effect_on_conditions,
                           g->inactive_global_effect_on_condition_vector, new_eocs, true );
     }
     for( const std::pair<const effect_on_condition_id, bool> &eoc_pair : new_eocs ) {
         if( eoc_pair.second ) {
             dialogue d( get_talker_for( you ), nullptr );
             queue_effect_on_condition( next_recurrence( eoc_pair.first, d ),
                                        eoc_pair.first, you, {} );
         }
     }
 }
References eoc, g, get_all(), get_talker_for(), Character::inactive_effect_on_condition_vector, Creature::is_avatar(), next_recurrence(), process_new_eocs(), queue_effect_on_condition(), Character::queued_effect_on_conditions, and RECURRING.
Referenced by game::load(), and npc::on_load().
load_inline_eoc()
effect_on_condition_id effect_on_conditions::load_inline_eoc (const JsonValue & jv, const std::string & src)
Loads an inline eoc.
Definition at line 119 of file effect_on_condition.cpp.
 {
     if( jv.test_string() ) {
         return effect_on_condition_id( jv.get_string() );
     } else if( jv.test_object() ) {
         effect_on_condition inline_eoc;
         inline_eoc.load( jv.get_object(), src );
         mod_tracker::assign_src( inline_eoc, src );
         effect_on_condition_factory.insert( inline_eoc );
         return inline_eoc.id;
     } else {
         jv.throw_error( "effect_on_condition needs to be either a string or an effect_on_condition object." );
     }
 }
References mod_tracker::assign_src(), anonymous_namespace{effect_on_condition.cpp}::effect_on_condition_factory, JsonValue::get_object(), JsonValue::get_string(), effect_on_condition::id, effect_on_condition::load(), JsonValue::test_object(), JsonValue::test_string(), and JsonValue::throw_error().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_until(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_weighted_list_eocs(), eoc_examine_actor::load(), ma_technique::load(), martialart::load(), mutation_branch::load(), overmap_special::load(), recipe::load(), damage_type::load(), npc_template::load(), effect_on_conditons_actor::load(), bionic_data::load(), Item_factory::load(), load_eoc_vector(), and load_eoc_vector_id_and_var().
load_new_character()
void effect_on_conditions::load_new_character (Character & you)
Sets up the initial queue for a new character.
Definition at line 140 of file effect_on_condition.cpp.
 {
     bool is_avatar = you.is_avatar();
     for( const effect_on_condition_id &eoc_id : get_scenario()->eoc() ) {
         effect_on_condition eoc = eoc_id.obj();
         if( eoc.type == eoc_type::SCENARIO_SPECIFIC && ( is_avatar || eoc.run_for_npcs ) ) {
             queued_eoc new_eoc = queued_eoc{ eoc.id, calendar::turn_zero, {} };
             you.queued_effect_on_conditions.push( new_eoc );
         }
     }
     for( const effect_on_condition &eoc : effect_on_conditions::get_all() ) {
         if( eoc.type == eoc_type::RECURRING && ( ( is_avatar && eoc.global ) || !eoc.global ) ) {
             dialogue d( get_talker_for( you ), nullptr );
             queued_eoc new_eoc = queued_eoc{ eoc.id, calendar::turn + next_recurrence( eoc.id, d ), {} };
             if( eoc.global ) {
                 g->queued_global_effect_on_conditions.push( new_eoc );
             } else {
                 you.queued_effect_on_conditions.push( new_eoc );
             }
         }
     }
     effect_on_conditions::process_effect_on_conditions( you );
 }
References eoc, g, get_all(), get_scenario(), get_talker_for(), Creature::is_avatar(), next_recurrence(), process_effect_on_conditions(), queued_eocs::push(), Character::queued_effect_on_conditions, RECURRING, SCENARIO_SPECIFIC, calendar::turn, and calendar::turn_zero.
Referenced by npc::randomize(), and game::start_game().
om_move()
void effect_on_conditions::om_move ()
Run all OM_MOVE eocs.
Definition at line 470 of file effect_on_condition.cpp.
 {
     avatar &player_character = get_avatar();
     dialogue d( get_talker_for( player_character ), nullptr );
     for( const effect_on_condition &eoc : effect_on_conditions::get_all() ) {
         if( eoc.type == eoc_type::OM_MOVE ) {
             eoc.activate( d );
         }
     }
 }
References eoc, get_all(), get_avatar(), get_talker_for(), and OM_MOVE.
Referenced by cata_event_dispatch::avatar_moves().
prevent_death()
void effect_on_conditions::prevent_death ()
Run all prevent death eocs.
Definition at line 439 of file effect_on_condition.cpp.
 {
     avatar &player_character = get_avatar();
     dialogue d( get_talker_for( player_character ), nullptr );
     for( const effect_on_condition &eoc : effect_on_conditions::get_all() ) {
         if( eoc.type == eoc_type::PREVENT_DEATH ) {
             eoc.activate( d );
         }
         if( !player_character.is_dead_state() ) {
             player_character.clear_killer();
             break;
         }
     }
 }
References Creature::clear_killer(), eoc, get_all(), get_avatar(), get_talker_for(), Character::is_dead_state(), and PREVENT_DEATH.
Referenced by game::is_game_over().
process_effect_on_conditions()
void effect_on_conditions::process_effect_on_conditions (Character & you)
called every turn to process the queued eocs
Definition at line 272 of file effect_on_condition.cpp.
 {
     dialogue d( get_talker_for( you ), nullptr );
     process_eocs( you.queued_effect_on_conditions, you.inactive_effect_on_condition_vector, d );
     //only handle global eocs on the avatars turn
     if( you.is_avatar() ) {
         process_eocs( g->queued_global_effect_on_conditions, g->inactive_global_effect_on_condition_vector,
                       d );
     }
 }
References g, get_talker_for(), Character::inactive_effect_on_condition_vector, Creature::is_avatar(), process_eocs(), and Character::queued_effect_on_conditions.
Referenced by load_new_character(), and Character::process_turn().
process_reactivate() [1/2]
void effect_on_conditions::process_reactivate ()
Definition at line 307 of file effect_on_condition.cpp.
 {
     dialogue d( get_talker_for( get_avatar() ), nullptr );
     process_reactivation( g->inactive_global_effect_on_condition_vector,
                           g->queued_global_effect_on_conditions, d );
 }
References g, get_avatar(), get_talker_for(), and process_reactivation().
process_reactivate() [2/2]
void effect_on_conditions::process_reactivate (Character & you)
called after certain events to test whether to reactivate eocs
Definition at line 301 of file effect_on_condition.cpp.
 {
     dialogue d( get_talker_for( you ), nullptr );
     process_reactivation( you.inactive_effect_on_condition_vector, you.queued_effect_on_conditions, d );
 }
References get_talker_for(), Character::inactive_effect_on_condition_vector, process_reactivation(), and Character::queued_effect_on_conditions.
Referenced by Character::add_bionic(), Character::on_mutation_gain(), Character::on_mutation_loss(), Character::remove_bionic(), and weather_manager::update_weather().
queue_effect_on_condition()
void effect_on_conditions::queue_effect_on_condition (time_duration duration, effect_on_condition_id eoc, Character & you, const std::unordered_map< std::string, std::string > & context)
queue an eoc to happen in the future
Definition at line 218 of file effect_on_condition.cpp.
 {
     queued_eoc new_eoc = queued_eoc{ eoc, calendar::turn + duration, context };
     if( eoc->global ) {
         g->queued_global_effect_on_conditions.push( new_eoc );
     } else if( eoc->type == eoc_type::ACTIVATION || eoc->type == eoc_type::RECURRING ) {
         you.queued_effect_on_conditions.push( new_eoc );
     } else {
         debugmsg( "Invalid effect_on_condition and/or target.  EOC: %s", eoc->id.c_str() );
     }
 }
References ACTIVATION, context, debugmsg, eoc, g, queued_eocs::push(), Character::queued_effect_on_conditions, RECURRING, and calendar::turn.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eoc_with(), load_existing_character(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::process_eoc(), and Character::queue_effect().
reset()
void effect_on_conditions::reset ()
Clear all loaded effects on condition (invalidating any pointers)
Definition at line 502 of file effect_on_condition.cpp.
 {
     effect_on_condition_factory.reset();
 }
References anonymous_namespace{effect_on_condition.cpp}::effect_on_condition_factory.
Referenced by DynamicDataLoader::unload_data().
write_eocs_to_file()
void effect_on_conditions::write_eocs_to_file (Character & you)
write out all queued eocs and inactive eocs to a file for testing
Definition at line 379 of file effect_on_condition.cpp.
 {
     write_to_file( "eocs.output", [&you]( std::ostream & testfile ) {
         testfile << "Character Name: " + you.get_name() << std::endl;
         testfile << "id;timepoint;recurring" << std::endl;
         testfile << "queued eocs:" << std::endl;
         std::vector<queued_eoc> temp_queue;
         while( !you.queued_effect_on_conditions.empty() ) {
             temp_queue.push_back( you.queued_effect_on_conditions.top() );
             you.queued_effect_on_conditions.pop();
         }
         for( const queued_eoc &queue_entry : temp_queue ) {
             time_duration temp = queue_entry.time - calendar::turn;
             testfile << queue_entry.eoc.c_str() << ";" << to_string( temp ) << std::endl;
         }
         for( const queued_eoc &queued : temp_queue ) {
             you.queued_effect_on_conditions.push( queued );
         }
         testfile << "inactive eocs:" << std::endl;
         for( const effect_on_condition_id &eoc : you.inactive_effect_on_condition_vector ) {
             testfile << eoc.c_str() << std::endl;
         }
     }, "eocs test file" );
 }
References queued_eocs::empty(), eoc, Character::get_name(), Character::inactive_effect_on_condition_vector, Character::queued_effect_on_conditions, and write_to_file().
Referenced by debug_menu::character_edit_menu().
write_global_eocs_to_file()
void effect_on_conditions::write_global_eocs_to_file ()
Definition at line 409 of file effect_on_condition.cpp.
 {
     write_to_file( "eocs.output", [&]( std::ostream & testfile ) {
         testfile << "global" << std::endl;
         testfile << "id;timepoint;recurring" << std::endl;
         testfile << "queued eocs:" << std::endl;
         std::vector<queued_eoc> temp_queue;
         while( !g->queued_global_effect_on_conditions.empty() ) {
             temp_queue.push_back( g->queued_global_effect_on_conditions.top() );
             g->queued_global_effect_on_conditions.pop();
         }
         for( const queued_eoc &queue_entry : temp_queue ) {
             time_duration temp = queue_entry.time - calendar::turn;
             testfile << queue_entry.eoc.c_str() << ";" << to_string( temp ) << std::endl;
         }
         for( const queued_eoc &queued : temp_queue ) {
             g->queued_global_effect_on_conditions.push( queued );
         }
         testfile << "inactive eocs:" << std::endl;
         for( const effect_on_condition_id &eoc : g->inactive_global_effect_on_condition_vector ) {
             testfile << eoc.c_str() << std::endl;
         }
     }, "eocs test file" );
 }
References eoc, g, and write_to_file().
Referenced by debug_menu::debug().