Cataclysm DDA: anonymous_namespace{bionics.cpp} Namespace Reference
anonymous_namespace{bionics.cpp} Namespace Reference
Variables
generic_factory< bionic_data > bionic_factory ("bionic")
std::vector< bionic_id > faulty_bionics
Variable Documentation
bionic_factory
generic_factory<bionic_data> anonymous_namespace{bionics.cpp}::bionic_factory("bionic") ("bionic")
Referenced by bionic_data::finalize_bionic(), bionic_data::get_all(), bionic_data::load_bionic(), and reset_bionics().
faulty_bionics
std::vector<bionic_id> anonymous_namespace{bionics.cpp}::faulty_bionics
Definition at line 189 of file bionics.cpp.
Referenced by Character::bionics_install_failure(), bionic_data::load(), and reset_bionics().