Cataclysm DDA: anonymous_namespace{ammo.cpp} Namespace Reference
anonymous_namespace{ammo.cpp} Namespace Reference
Typedefs
using ammo_map_t = std::unordered_map< ammotype, ammunition_type >
Functions
ammo_map_t & all_ammunition_types ()
Typedef Documentation
ammo_map_t
using anonymous_namespace{ammo.cpp}::ammo_map_t = typedef std::unordered_map<ammotype, ammunition_type>
Definition at line 16 of file ammo.cpp.
Function Documentation
all_ammunition_types()
ammo_map_t& anonymous_namespace{ammo.cpp}::all_ammunition_types ()
Definition at line 18 of file ammo.cpp.
 {
     static ammo_map_t the_map;
     return the_map;
 }
Referenced by ammunition_type::check_consistency(), ammunition_type::load_ammunition_type(), and ammunition_type::reset().