Cataclysm DDA: overmap_terrains Namespace Reference
overmap_terrains Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void check_consistency ()
void finalize ()
void reset ()
const std::vector< oter_t > & get_all ()
Function Documentation
check_consistency()
void overmap_terrains::check_consistency ()
Definition at line 1015 of file overmap.cpp.
 {
     for( const oter_type_t &elem : terrain_types.get_all() ) {
         elem.check();
         if( elem.static_spawns.group && !elem.static_spawns.group.is_valid() ) {
             debugmsg( "Invalid monster group \"%s\" in spawns of \"%s\".", elem.static_spawns.group.c_str(),
                       elem.id.c_str() );
         }
     }
     for( const oter_t &elem : terrains.get_all() ) {
         const std::string mid = elem.get_mapgen_id();
         if( mid.empty() ) {
             continue;
         }
         const bool exists_hardcoded = elem.is_hardcoded();
         if( has_mapgen_for( mid ) ) {
             if( test_mode && exists_hardcoded ) {
                 debugmsg( "Mapgen terrain \"%s\" exists in both JSON and a hardcoded function.  Consider removing the latter.",
                           mid.c_str() );
             }
             check_mapgen_consistent_with( mid, elem );
         } else if( !exists_hardcoded ) {
             debugmsg( "No mapgen terrain exists for \"%s\".", mid.c_str() );
         }
     }
 }
References check_mapgen_consistent_with(), debugmsg, has_mapgen_for(), anonymous_namespace{overmap.cpp}::terrain_types, anonymous_namespace{overmap.cpp}::terrains, and test_mode.
Referenced by DynamicDataLoader::check_consistency().
finalize()
void overmap_terrains::finalize ()
Definition at line 1046 of file overmap.cpp.
 {
     terrain_types.finalize();
     for( const oter_type_t &elem : terrain_types.get_all() ) {
         const_cast<oter_type_t &>( elem ).finalize(); // This cast is ugly, but safe.
     }
     if( region_settings_map.find( "default" ) == region_settings_map.end() ) {
         debugmsg( "ERROR: can't find default overmap settings (region_map_settings 'default'), "
                   "Cataclysm pending.  And not the fun kind." );
     }
     for( auto &elem : region_settings_map ) {
         elem.second.finalize();
     }
     set_oter_ids();
 }
References debugmsg, behavior::finalize(), region_settings_map, set_oter_ids(), and anonymous_namespace{overmap.cpp}::terrain_types.
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< oter_t > & overmap_terrains::get_all ()
Definition at line 1072 of file overmap.cpp.
 {
     return terrains.get_all();
 }
References anonymous_namespace{overmap.cpp}::terrains.
Referenced by editmap::edit_mapgen(), overmap_connection::finalize(), overmap_location::finalize(), mapgen_factory::get_usages(), and overmap_ui::place_ter_or_special().
load()
void overmap_terrains::load (const JsonObject & jo, const std::string & src)
Definition at line 1010 of file overmap.cpp.
 {
     terrain_types.load( jo, src );
 }
References anonymous_namespace{overmap.cpp}::terrain_types.
Referenced by DynamicDataLoader::initialize().
reset()
void overmap_terrains::reset ()
Definition at line 1066 of file overmap.cpp.
 {
     terrain_types.reset();
     terrains.reset();
 }
References anonymous_namespace{overmap.cpp}::terrain_types, and anonymous_namespace{overmap.cpp}::terrains.
Referenced by DynamicDataLoader::unload_data().