Cataclysm DDA: anonymous_namespace{npctrade_utils.cpp} Namespace Reference
anonymous_namespace{npctrade_utils.cpp} Namespace Reference
Typedefs
using consume_cache = std::map< itype_id, int >
using consume_queue = std::vector< item_location >
using dest_t = std::vector< tripoint_abs_ms >
Functions
void _consume_item (item_location elem, consume_queue &consumed, consume_cache &cache, npc &guy, time_duration const &elapsed)
dest_t _get_shuffled_point_set (std::unordered_set< tripoint_abs_ms > const &set)
bool _to_map (item const &it, map &here, tripoint const &dpoint_here)
bool _to_veh (item const &it, std::optional< vpart_reference > const &vp)
Typedef Documentation
consume_cache
using anonymous_namespace{npctrade_utils.cpp}::consume_cache = typedef std::map<itype_id, int>
Definition at line 20 of file npctrade_utils.cpp.
consume_queue
using anonymous_namespace{npctrade_utils.cpp}::consume_queue = typedef std::vector<item_location>
Definition at line 21 of file npctrade_utils.cpp.
dest_t
using anonymous_namespace{npctrade_utils.cpp}::dest_t = typedef std::vector<tripoint_abs_ms>
Definition at line 22 of file npctrade_utils.cpp.
Function Documentation
_consume_item()
void anonymous_namespace{npctrade_utils.cpp}::_consume_item (item_location elem, consume_queue & consumed, consume_cache & cache, npc & guy, time_duration const & elapsed)
Definition at line 24 of file npctrade_utils.cpp.
 {
     if( !elem->is_owned_by( guy ) ) {
         return;
     }
     std::list<item *> const contents = elem->all_items_top( pocket_type::CONTAINER );
     if( contents.empty() ) {
         auto it = cache.find( elem->typeId() );
         if( it == cache.end() ) {
             int const rate = guy.myclass->get_shopkeeper_cons_rates().get_rate( *elem, guy );
             int const rate_init = rate >= 0 ? rate * to_days<int>( elapsed ) : -1;
             it = cache.emplace( elem->typeId(), rate_init ).first;
         }
         if( it->second != 0 ) {
             consumed.push_back( elem );
             it->second--;
         }
     } else {
         for( item *it : contents ) {
             _consume_item( item_location( elem, it ), consumed, cache, guy, elapsed );
         }
     }
 }
References item::all_items_top(), CONTAINER, anonymous_namespace{item_tname.cpp}::contents(), shopkeeper_cons_rates::get_rate(), npc_class::get_shopkeeper_cons_rates(), item::is_owned_by(), npc::myclass, and item::typeId().
Referenced by consume_items_in_zones().
_get_shuffled_point_set()
dest_t anonymous_namespace{npctrade_utils.cpp}::_get_shuffled_point_set (std::unordered_set< tripoint_abs_ms > const & set)
Definition at line 49 of file npctrade_utils.cpp.
 {
     dest_t ret;
     std::copy( set.begin(), set.end(), std::back_inserter( ret ) );
     std::shuffle( ret.begin(), ret.end(), rng_get_engine() );
     return ret;
 }
References cata::hash64_detail::ret, and rng_get_engine().
Referenced by distribute_items_to_npc_zones().
_to_map()
bool anonymous_namespace{npctrade_utils.cpp}::_to_map (item const & it, map & here, tripoint const & dpoint_here)
Definition at line 58 of file npctrade_utils.cpp.
 {
     if( here.can_put_items_ter_furn( dpoint_here ) &&
         here.free_volume( dpoint_here ) >= it.volume() ) {
         item const &ret = here.add_item_or_charges( dpoint_here, it, false );
         return ret.is_null();
     }
     return true;
 }
References map::add_item_or_charges(), map::can_put_items_ter_furn(), map::free_volume(), cata::hash64_detail::ret, and item::volume().
Referenced by distribute_items_to_npc_zones().
_to_veh()
bool anonymous_namespace{npctrade_utils.cpp}::_to_veh (item const & it, std::optional< vpart_reference > const & vp)
Definition at line 68 of file npctrade_utils.cpp.
 {
     if( vp->items().free_volume() >= it.volume() ) {
         std::optional<vehicle_stack::iterator> const ret = vp->vehicle().add_item( vp->part(), it );
         return !ret.has_value();
     }
     return true;
 }
References cata::hash64_detail::ret, and item::volume().
Referenced by distribute_items_to_npc_zones().