Cataclysm DDA: anonymous_namespace{behavior.cpp} Namespace Reference
anonymous_namespace{behavior.cpp} Namespace Reference
Variables
generic_factory< behavior::node_t > behavior_factory ("behavior")
std::list< node_data > temp_node_data
Variable Documentation
behavior_factory
generic_factory<behavior::node_t> anonymous_namespace{behavior.cpp}::behavior_factory("behavior") ("behavior")
Referenced by behavior::check_consistency(), behavior::load_behavior(), and behavior::reset().
temp_node_data
std::list<node_data> anonymous_namespace{behavior.cpp}::temp_node_data
Definition at line 116 of file behavior.cpp.
Referenced by behavior::finalize(), behavior::node_t::load(), and behavior::reset().