Cataclysm DDA: doors Namespace Reference
doors Namespace Reference
Functions
void close_door (map &m, Creature &who, const tripoint_bub_ms &closep)
Handles deducting moves, printing messages (only non-NPCs cause messages), actually closing it, checking if it can be closed, etc.
bool lock_door (map &m, Creature &who, const tripoint_bub_ms &lockp)
Locks a door at "lockp" as "who.".
bool unlock_door (map &m, Creature &who, const tripoint_bub_ms &lockp)
Unlocks a door at "lockp" as "who.".
bool can_lock_door (const map &m, const Creature &who, const tripoint_bub_ms &lockp)
Whether a door at "lockp" can be locked by "who.".
bool can_unlock_door (const map &m, const Creature &who, const tripoint_bub_ms &lockp)
Whether a door at "lockp" can be unlocked by "who.".
Function Documentation
can_lock_door()
bool doors::can_lock_door (const map & m, const Creature & who, const tripoint_bub_ms & lockp)
Whether a door at "lockp" can be locked by "who.".
Definition at line 395 of file gates.cpp.
 {
     int lockable = -1;
     if( const optional_vpart_position vp = m.veh_at( lockp ) ) {
         const vehicle *const veh = &vp->vehicle();
         const bool inside_vehicle = m.veh_at( who.pos() ) &&
                                     &vp->vehicle() == &m.veh_at( who.pos() )->vehicle();
         const int vpart = vp->part_index();
         lockable = veh->next_part_to_lock( vpart, !inside_vehicle );
     }
     return lockable >= 0;
 }
References vehicle::next_part_to_lock(), Creature::pos(), map::veh_at(), and vehicle::vehicle().
can_unlock_door()
bool doors::can_unlock_door (const map & m, const Creature & who, const tripoint_bub_ms & lockp)
Whether a door at "lockp" can be unlocked by "who.".
Definition at line 449 of file gates.cpp.
 {
     int unlockable = -1;
     if( const optional_vpart_position vp = m.veh_at( lockp ) ) {
         const vehicle *const veh = &vp->vehicle();
         const bool inside_vehicle = m.veh_at( who.pos() ) &&
                                     &vp->vehicle() == &m.veh_at( who.pos() )->vehicle();
         const int vpart = vp->part_index();
         unlockable = veh->next_part_to_unlock( vpart, !inside_vehicle );
     }
     return unlockable >= 0;
 }
References vehicle::next_part_to_unlock(), Creature::pos(), map::veh_at(), and vehicle::vehicle().
Referenced by npc::get_path_avoid(), and npc::move_to().
close_door()
void doors::close_door (map & m, Creature & who, const tripoint_bub_ms & closep)
Handles deducting moves, printing messages (only non-NPCs cause messages), actually closing it, checking if it can be closed, etc.
Definition at line 254 of file gates.cpp.
 {
     bool didit = false;
     const bool inside = !m.is_outside( who.pos() );
     const Creature *const mon = get_creature_tracker().creature_at( closep );
     if( mon ) {
         if( mon->is_avatar() ) {
             who.add_msg_if_player( m_info, _( "There's some buffoon in the way!" ) );
         } else if( mon->is_monster() ) {
             // TODO: Houseflies, mosquitoes, etc shouldn't count
             who.add_msg_if_player( m_info, _( "The %s is in the way!" ), mon->get_name() );
         } else {
             who.add_msg_if_player( m_info, _( "%s is in the way!" ), mon->disp_name() );
         }
         return;
     }
     if( optional_vpart_position vp = m.veh_at( closep ) ) {
         // There is a vehicle part here; see if it has anything that can be closed
         vehicle *const veh = &vp->vehicle();
         const int vpart = vp->part_index();
         const int closable = veh->next_part_to_close( vpart,
                              veh_pointer_or_null( m.veh_at( who.pos() ) ) != veh );
         const int inside_closable = veh->next_part_to_close( vpart );
         const int openable = veh->next_part_to_open( vpart );
         if( closable >= 0 ) {
             if( !veh->handle_potential_theft( get_avatar() ) ) {
                 return;
             }
             Character *ch = who.as_character();
             if( ch && veh->can_close( closable, *ch ) ) {
                 veh->close( closable );
                 //~ %1$s - vehicle name, %2$s - part name
                 who.add_msg_if_player( _( "You close the %1$s's %2$s." ), veh->name, veh->part( closable ).name() );
                 didit = true;
             }
         } else if( inside_closable >= 0 ) {
             who.add_msg_if_player( m_info, _( "That %s can only be closed from the inside." ),
                                    veh->part( inside_closable ).name() );
         } else if( openable >= 0 ) {
             who.add_msg_if_player( m_info, _( "That %s is already closed." ),
                                    veh->part( openable ).name() );
         } else {
             who.add_msg_if_player( m_info, _( "You cannot close the %s." ), veh->part( vpart ).name() );
         }
     } else if( m.furn( closep ) == furn_f_crate_o ) {
         who.add_msg_if_player( m_info, _( "You'll need to construct a seal to close the crate!" ) );
     } else if( !m.close_door( closep, inside, true ) ) {
         if( m.close_door( closep, true, true ) ) {
             who.add_msg_if_player( m_info,
                                    _( "You cannot close the %s from outside.  You must be inside the building." ),
                                    m.name( closep ) );
         } else {
             who.add_msg_if_player( m_info, _( "You cannot close the %s." ), m.name( closep ) );
         }
     } else {
         map_stack items_in_way = m.i_at( closep );
         // Scoot up to 25 liters of items out of the way
         if( m.furn( closep ) != furn_f_safe_o && !items_in_way.empty() ) {
             const units::volume max_nudge = 25_liter;
             const auto toobig = std::find_if( items_in_way.begin(), items_in_way.end(),
             [&max_nudge]( const item & it ) {
                 return it.volume() > max_nudge;
             } );
             if( toobig != items_in_way.end() ) {
                 who.add_msg_if_player( m_info, _( "The %s is too big to just nudge out of the way." ),
                                        toobig->tname() );
             } else if( items_in_way.stored_volume() > max_nudge ) {
                 who.add_msg_if_player( m_info, _( "There is too much stuff in the way." ) );
             } else {
                 m.close_door( closep, inside, false );
                 didit = true;
                 who.add_msg_if_player( m_info, _( "You push the %s out of the way." ),
                                        items_in_way.size() == 1 ? items_in_way.only_item().tname() : _( "stuff" ) );
                 who.mod_moves( -std::min( items_in_way.stored_volume() / ( max_nudge / 50 ), 100 ) );
                 if( m.has_flag( ter_furn_flag::TFLAG_NOITEM, closep ) ) {
                     // Just plopping items back on their origin square will displace them to adjacent squares
                     // since the door is closed now.
                     for( item &elem : items_in_way ) {
                         m.add_item_or_charges( closep, elem );
                     }
                     m.i_clear( closep );
                 }
             }
         } else {
             const std::string door_name = m.obstacle_name( closep );
             m.close_door( closep, inside, false );
             who.add_msg_if_player( _( "You close the %s." ), door_name );
             didit = true;
         }
     }
     if( didit ) {
         // TODO: Vary this? Based on strength, broken legs, and so on.
         who.mod_moves( -90 );
     }
 }
References _, map::add_item_or_charges(), Creature::add_msg_if_player(), Creature::as_character(), item_stack::begin(), vehicle::can_close(), vehicle::close(), map::close_door(), creature_tracker::creature_at(), Creature::disp_name(), item_stack::empty(), item_stack::end(), map::furn(), furn_f_crate_o, furn_f_safe_o, get_avatar(), get_creature_tracker(), Creature::get_name(), vehicle::handle_potential_theft(), map::has_flag(), map::i_at(), map::i_clear(), Creature::is_avatar(), Creature::is_monster(), map::is_outside(), m_info, min(), Creature::mod_moves(), vehicle_part::name(), map::name(), vehicle::name, vehicle::next_part_to_close(), vehicle::next_part_to_open(), map::obstacle_name(), item_stack::only_item(), vehicle::part(), Creature::pos(), item_stack::size(), item_stack::stored_volume(), TFLAG_NOITEM, item::tname(), map::veh_at(), veh_pointer_or_null(), and vehicle::vehicle().
Referenced by close(), game::do_regular_action(), and npc::move_to().
lock_door()
bool doors::lock_door (map & m, Creature & who, const tripoint_bub_ms & lockp)
Locks a door at "lockp" as "who.".
Involves deducting moves, printing messages (only non-NPCs can cause messages), checking if it is locked, performing the action, making sounds, etc.
Parameters
check_only prevents actions and returns whether a door can be locked here
Returns
whether a door was actually locked
Definition at line 356 of file gates.cpp.
 {
     bool didit = false;
     if( optional_vpart_position vp = m.veh_at( lockp ) ) {
         vehicle *const veh = &vp->vehicle();
         const int vpart = vp->part_index();
         const bool inside_vehicle = m.veh_at( who.pos() ) &&
                                     &vp->vehicle() == &m.veh_at( who.pos() )->vehicle();
         const int lockable = veh->next_part_to_lock( vpart, !inside_vehicle );
         const int inside_lockable = veh->next_part_to_lock( vpart );
         const int already_locked_part = veh->next_part_to_unlock( vpart );
         if( lockable >= 0 ) {
             if( const Character *const ch = who.as_character() ) {
                 if( !veh->handle_potential_theft( *ch ) ) {
                     return false;
                 }
                 veh->lock( lockable );
                 who.add_msg_if_player( _( "You lock the %1$s's %2$s." ), veh->name, veh->part( lockable ).name() );
                 didit = true;
             }
         } else if( inside_lockable >= 0 ) {
             who.add_msg_if_player( m_info, _( "That %s can only be locked from the inside." ),
                                    veh->part( inside_lockable ).name() );
         } else if( already_locked_part >= 0 ) {
             who.add_msg_if_player( m_info, _( "That %s is already locked." ),
                                    veh->part( already_locked_part ).name() );
         } else {
             who.add_msg_if_player( m_info, _( "You cannot lock the %s." ), veh->part( vpart ).name() );
         }
     }
     if( didit ) {
         sounds::sound( lockp, 1, sounds::sound_t::activity, _( "a soft chk." ) );
         who.mod_moves( -90 );
     }
     return didit;
 }
References _, sounds::activity, Creature::add_msg_if_player(), Creature::as_character(), vehicle::handle_potential_theft(), vehicle::lock(), m_info, Creature::mod_moves(), vehicle_part::name(), vehicle::name, vehicle::next_part_to_lock(), vehicle::next_part_to_unlock(), vehicle::part(), Creature::pos(), sounds::sound(), map::veh_at(), and vehicle::vehicle().
Referenced by npc::move_to().
unlock_door()
bool doors::unlock_door (map & m, Creature & who, const tripoint_bub_ms & lockp)
Unlocks a door at "lockp" as "who.".
Involves printing messages (only non-NPCs can cause messages), actually unlocking it, checking if it is locked, performing the action, making sounds, etc.
Returns
whether a door was actually unlocked
Definition at line 409 of file gates.cpp.
 {
     bool didit = false;
     if( optional_vpart_position vp = m.veh_at( lockp ) ) {
         vehicle *const veh = &vp->vehicle();
         const int vpart = vp->part_index();
         const bool inside_vehicle = m.veh_at( who.pos() ) &&
                                     &vp->vehicle() == &m.veh_at( who.pos() )->vehicle();
         const int already_unlocked_part = veh->next_part_to_lock( vpart );
         const int inside_unlockable = veh->next_part_to_unlock( vpart );
         const int unlockable = veh->next_part_to_unlock( vpart, !inside_vehicle );
         if( unlockable >= 0 ) {
             if( const Character *const ch = who.as_character() ) {
                 if( !veh->handle_potential_theft( *ch ) ) {
                     return false;
                 }
                 veh->unlock( unlockable );
                 who.add_msg_if_player( _( "You unlock the %1$s's %2$s." ), veh->name,
                                        veh->part( unlockable ).name() );
                 didit = true;
             }
         } else if( inside_unlockable >= 0 ) {
             who.add_msg_if_player( m_info, _( "That %s can only be unlocked from the inside." ),
                                    veh->part( inside_unlockable ).name() );
         } else if( already_unlocked_part >= 0 ) {
             who.add_msg_if_player( m_info, _( "That %s is already unlocked." ),
                                    veh->part( already_unlocked_part ).name() );
         } else {
             who.add_msg_if_player( m_info, _( "You cannot unlock the %s." ), veh->part( vpart ).name() );
         }
     }
     if( didit ) {
         sounds::sound( lockp, 1, sounds::sound_t::activity, _( "a soft click." ) );
         who.mod_moves( -90 );
     }
     return didit;
 }
References _, sounds::activity, Creature::add_msg_if_player(), Creature::as_character(), vehicle::handle_potential_theft(), m_info, Creature::mod_moves(), vehicle_part::name(), vehicle::name, vehicle::next_part_to_lock(), vehicle::next_part_to_unlock(), vehicle::part(), Creature::pos(), sounds::sound(), vehicle::unlock(), map::veh_at(), and vehicle::vehicle().
Referenced by npc::move_to().