Cataclysm DDA: anonymous_namespace{item_tname.cpp} Namespace Reference
anonymous_namespace{item_tname.cpp} Namespace Reference
Typedefs
using decl_f_print_segment = std::string(item const &it, unsigned int quantity, segment_bitset const &segments)
Functions
std::string noop (item const &, unsigned int, segment_bitset const &)
std::string faults (item const &it, unsigned int, segment_bitset const &)
std::string dirt_symbol (item const &it, unsigned int, segment_bitset const &)
std::string overheat_symbol (item const &it, unsigned int, segment_bitset const &)
std::string pre_asterisk (item const &it, unsigned int, segment_bitset const &)
std::string durability (item const &it, unsigned int, segment_bitset const &)
std::string wheel_diameter (item const &it, unsigned int, segment_bitset const &)
std::string burn (item const &it, unsigned int, segment_bitset const &)
std::string custom_item_prefix (item const &it, unsigned int, segment_bitset const &)
std::string custom_item_suffix (item const &it, unsigned int, segment_bitset const &)
std::string label (item const &it, unsigned int quantity, segment_bitset const &segments)
std::string mods (item const &it, unsigned int, segment_bitset const &)
std::string craft (item const &it, unsigned int, segment_bitset const &)
std::string wbl_mark (item const &it, unsigned int, segment_bitset const &)
std::string contents (item const &it, unsigned int, segment_bitset const &segments)
std::string food_traits (item const &it, unsigned int, segment_bitset const &)
std::string location_hint (item const &it, unsigned int, segment_bitset const &)
std::string ethereal (item const &it, unsigned int, segment_bitset const &)
std::string food_status (item const &it, unsigned int, segment_bitset const &)
std::string food_irradiated (item const &it, unsigned int, segment_bitset const &)
std::string temperature (item const &it, unsigned int, segment_bitset const &)
std::string clothing_size (item const &it, unsigned int, segment_bitset const &)
std::string filthy (item const &it, unsigned int, segment_bitset const &)
std::string tags (item const &it, unsigned int, segment_bitset const &)
std::string vars (item const &it, unsigned int, segment_bitset const &)
std::string segment_broken (item const &it, unsigned int, segment_bitset const &)
std::string cbm_status (item const &it, unsigned int, segment_bitset const &)
std::string ups (item const &it, unsigned int, segment_bitset const &)
std::string wetness (item const &it, unsigned int, segment_bitset const &)
std::string active (item const &it, unsigned int, segment_bitset const &)
std::string sealed (item const &it, unsigned int, segment_bitset const &)
std::string post_asterisk (item const &it, unsigned int, segment_bitset const &)
std::string weapon_mods (item const &it, unsigned int, segment_bitset const &)
std::string relic_charges (item const &it, unsigned int, segment_bitset const &)
std::string category (item const &it, unsigned int quantity, segment_bitset const &segments)
constexpr std::array< decl_f_print_segment *, num_segments > get_segs_array ()
constexpr bool all_segments_have_printers ()
Variables
constexpr size_t num_segments = static_cast<size_t>(tname::segments::last_segment)
Typedef Documentation
decl_f_print_segment
using anonymous_namespace{item_tname.cpp}::decl_f_print_segment = typedef std::string(item const &it, unsigned int quantity, segment_bitset const &segments)
Definition at line 550 of file item_tname.cpp.
Function Documentation
active()
std::string anonymous_namespace{item_tname.cpp}::active (item const & it, unsigned int , segment_bitset const &)
Definition at line 484 of file item_tname.cpp.
 {
     if( it.active && !it.has_temperature() && !string_ends_with( it.typeId().str(), "_on" ) ) {
         // Usually the items whose ids end in "_on" have the "active" or "on" string already contained
         // in their name, also food is active while it rots.
         return _( " (active)" );
     }
     return {};
 }
References _, item::active, active(), item::has_temperature(), string_id< T >::str(), string_ends_with(), and item::typeId().
Referenced by active(), and get_segs_array().
all_segments_have_printers()
constexpr bool anonymous_namespace{item_tname.cpp}::all_segments_have_printers () constexpr
Definition at line 597 of file item_tname.cpp.
 {
     for( decl_f_print_segment *printer : get_segs_array() ) {
         if( printer == nullptr ) {
             return false;
         }
     }
     return true;
 }
References get_segs_array().
burn()
std::string anonymous_namespace{item_tname.cpp}::burn (item const & it, unsigned int , segment_bitset const &)
Definition at line 108 of file item_tname.cpp.
 {
     if( !it.made_of_from_type( phase_id::LIQUID ) ) {
         if( it.volume() >= 1_liter && it.burnt * 125_ml >= it.volume() ) {
             return pgettext( "burnt adjective", "badly burnt " );
         }
         if( it.burnt > 0 ) {
             return pgettext( "burnt adjective", "burnt " );
         }
     }
     return {};
 }
References item::burnt, LIQUID, item::made_of_from_type(), pgettext, and item::volume().
Referenced by get_segs_array().
category()
std::string anonymous_namespace{item_tname.cpp}::category (item const & it, unsigned int quantity, segment_bitset const & segments)
Definition at line 540 of file item_tname.cpp.
 {
     nc_color const &color = segments[tname::segments::FOOD_PERISHABLE] && it.is_food()
                             ? it.color_in_inventory( &get_avatar() )
                             : c_magenta;
     return colorize( it.get_category_of_contents().name_noun( quantity ), color );
 }
References c_magenta, color(), item::color_in_inventory(), colorize(), tname::FOOD_PERISHABLE, get_avatar(), item::get_category_of_contents(), item::is_food(), and item_category::name_noun().
Referenced by computer_session::action_list_mutations(), snippet_library::add_snippet_from_json(), snippet_library::add_snippets_from_json(), sounds::ambient_sound(), proficiency::bonus_for(), Character::check_needs_extremes(), describe_sound(), query_popup_impl::fold_query(), proficiency::get_bonuses(), Character::get_proficiency_bonus(), proficiency_set::get_proficiency_bonus(), get_segs_array(), Character::give_all_mutations(), handle_action_menu(), snippet_library::has_category(), mtype::in_category(), Character::is_category_allowed(), is_provocative(), test_data::load(), load_recipe_category(), snippet_library::load_snippet(), Character::mutate_towards(), inventory_selector::naturalize_category(), memorial_logger::notify(), replace_keybind_tag(), inventory_entry::set_custom_category(), safemode::show(), sounds::sound(), and subcategories_for_category().
cbm_status()
std::string anonymous_namespace{item_tname.cpp}::cbm_status (item const & it, unsigned int , segment_bitset const &)
Definition at line 454 of file item_tname.cpp.
 {
     if( it.is_bionic() && !it.has_flag( flag_NO_PACKED ) ) {
         if( !it.has_flag( flag_NO_STERILE ) ) {
             return _( " (sterile)" );
         }
         return _( " (packed)" );
     }
     return {};
 }
References _, flag_NO_PACKED, flag_NO_STERILE, item::has_flag(), and item::is_bionic().
Referenced by get_segs_array().
clothing_size()
std::string anonymous_namespace{item_tname.cpp}::clothing_size (item const & it, unsigned int , segment_bitset const &)
Definition at line 369 of file item_tname.cpp.
 {
     const item::sizing sizing_level = it.get_sizing( get_avatar() );
     if( sizing_level == item::sizing::human_sized_small_char ) {
         return _( " (too big)" );
     } else if( sizing_level == item::sizing::big_sized_small_char ) {
         return _( " (huge!)" );
     } else if( sizing_level == item::sizing::human_sized_big_char ||
                sizing_level == item::sizing::small_sized_human_char ) {
         return _( " (too small)" );
     } else if( sizing_level == item::sizing::small_sized_big_char ) {
         return _( " (tiny!)" );
     } else if( !it.has_flag( flag_FIT ) && it.has_flag( flag_VARSIZE ) ) {
         return _( " (poor fit)" );
     }
     return {};
 }
References _, item::big_sized_small_char, flag_FIT, flag_VARSIZE, get_avatar(), item::get_sizing(), item::has_flag(), item::human_sized_big_char, item::human_sized_small_char, item::small_sized_big_char, and item::small_sized_human_char.
Referenced by get_segs_array().
contents()
std::string anonymous_namespace{item_tname.cpp}::contents (item const & it, unsigned int , segment_bitset const & segments)
Definition at line 216 of file item_tname.cpp.
 {
     item_contents const &contents = it.get_contents();
     if( item::aggregate_t aggi = it.aggregated_contents();
         segments[tname::segments::CONTENTS_FULL] && aggi ) {
         const item &contents_item = *aggi.header;
         const unsigned aggi_count = contents_item.count_by_charges() && contents_item.charges > 1
                                     ? contents_item.charges
                                     : aggi.count;
         const unsigned total_count = contents_item.count_by_charges() && contents_item.charges > 1
                                      ? contents_item.charges
                                      : contents.num_item_stacks();
         // without full contents for nested items to prevent excessively long names
         segment_bitset abrev( aggi.info.bits );
         abrev.set( tname::segments::CONTENTS_FULL, false );
         abrev.set( tname::segments::CONTENTS_ABREV, aggi_count == 1 );
         abrev.set( tname::segments::CATEGORY,
                    abrev[tname::segments::CATEGORY] && !abrev[tname::segments::TYPE] );
         std::string const contents_tname = contents_item.tname( aggi_count, abrev );
         std::string const ctnc = abrev[tname::segments::CATEGORY]
                                  ? contents_tname
                                  : colorize( contents_tname, contents_item.color_in_inventory() );
         // Don't append an item count for single items, or items that are ammo-exclusive
         // (eg: quivers), as they format their own counts.
         if( total_count > 1 && it.ammo_types().empty() ) {
             if( total_count == aggi_count ) {
                 return string_format(
                            segments[tname::segments::CONTENTS_COUNT]
                            //~ [container item name] " > [count] [type]"
                            ? npgettext( "item name", " > %1$zd %2$s", " > %1$zd %2$s", total_count )
                            : " > %2$s",
                            total_count, ctnc );
             }
             return string_format(
                        segments[tname::segments::CONTENTS_COUNT]
                        //~ [container item name] " > [count] [type] / [total] items"
                        ? npgettext( "item name", " > %1$zd %2$s / %3$zd item", " > %1$zd %2$s / %3$zd items", total_count )
                        : " > %2$s",
                        aggi_count, ctnc, total_count );
         }
         return string_format( " > %1$s", ctnc );
     } else if( segments[tname::segments::CONTENTS_ABREV] && !contents.empty_container() &&
                contents.num_item_stacks() != 0 ) {
         std::string const suffix =
             segments[tname::segments::CONTENTS_COUNT]
             ? npgettext( "item name",
                          //~ [container item name] " > [count] item"
                          " > %1$zd item", " > %1$zd items", contents.num_item_stacks() )
             : _( " > items" );
         return string_format( suffix, contents.num_item_stacks() );
     }
     return {};
 }
References _, item::aggregated_contents(), item::ammo_types(), tname::CATEGORY, item::charges, item::color_in_inventory(), colorize(), tname::CONTENTS_ABREV, tname::CONTENTS_COUNT, tname::CONTENTS_FULL, item::count_by_charges(), item::get_contents(), npgettext, enum_bitset< E >::set(), string_format(), item::tname(), and tname::TYPE.
Referenced by anonymous_namespace{npctrade_utils.cpp}::_consume_item(), veh_interact::complete_vehicle(), get_autopickup_items(), item::get_contents(), get_segs_array(), monster::monster_move_in_vehicle(), Character::move_in_vehicle(), Character::process_effects(), monster::process_effects(), map::set_graffiti(), and map::smash_items().
craft()
std::string anonymous_namespace{item_tname.cpp}::craft (item const & it, unsigned int , segment_bitset const &)
Definition at line 176 of file item_tname.cpp.
 {
     if( it.is_craft() ) {
         std::string maintext;
         if( it.typeId() == itype_disassembly ) {
             maintext = string_format( _( "in progress disassembly of %s" ),
                                       it.get_making().result_name() );
         } else {
             maintext = string_format( _( "in progress %s" ), it.get_making().result_name() );
         }
         if( it.charges > 1 ) {
             maintext += string_format( " (%d)", it.charges );
         }
         const int percent_progress = it.item_counter / 100000;
         return string_format( "%s (%d%%)", maintext, percent_progress );
     }
     return {};
 }
References _, item::charges, item::get_making(), item::is_craft(), item::item_counter, itype_disassembly, recipe::result_name(), string_format(), and item::typeId().
Referenced by craft_activity_actor::canceled(), craft_activity_actor::check_if_craft_okay(), destroy_random_component(), disassemble_activity_actor::do_turn(), craft_activity_actor::do_turn(), get_most_rotten_component(), get_segs_array(), get_shortest_lifespan_from_components(), place_craft_or_disassembly(), shelf_life_less_than_each_component(), and wield_craft().
custom_item_prefix()
std::string anonymous_namespace{item_tname.cpp}::custom_item_prefix (item const & it, unsigned int , segment_bitset const &)
Definition at line 122 of file item_tname.cpp.
 {
     std::string prefix;
     for( const flag_id &f : it.get_prefix_flags() ) {
         prefix += f->item_prefix().translated();
     }
     return prefix;
 }
References item::get_prefix_flags().
Referenced by get_segs_array().
custom_item_suffix()
std::string anonymous_namespace{item_tname.cpp}::custom_item_suffix (item const & it, unsigned int , segment_bitset const &)
Definition at line 132 of file item_tname.cpp.
 {
     std::string suffix;
     for( const flag_id &f : it.get_suffix_flags() ) {
         suffix.insert( 0, f->item_suffix().translated() );
     }
     return suffix;
 }
References item::get_suffix_flags().
Referenced by get_segs_array().
dirt_symbol()
std::string anonymous_namespace{item_tname.cpp}::dirt_symbol (item const & it, unsigned int , segment_bitset const &)
Definition at line 65 of file item_tname.cpp.
 {
     return it.dirt_symbol();
 }
References item::dirt_symbol().
Referenced by get_segs_array().
durability()
std::string anonymous_namespace{item_tname.cpp}::durability (item const & it, unsigned int , segment_bitset const &)
Definition at line 86 of file item_tname.cpp.
 {
     const std::string item_health_option = get_option<std::string>( "ITEM_HEALTH" );
     const bool show_bars = item_health_option == "both" || item_health_option == "bars";
     if( !it.is_null() &&
         ( it.damage() != 0 || ( it.degradation() > 0 && it.degradation() >= it.max_damage() / 5 ) ||
           ( show_bars && it.is_armor() ) ) ) {
         return it.durability_indicator();
     }
     return {};
 }
References item::damage(), item::degradation(), item::durability_indicator(), item::is_armor(), item::is_null(), and item::max_damage().
Referenced by get_segs_array().
ethereal()
std::string anonymous_namespace{item_tname.cpp}::ethereal (item const & it, unsigned int , segment_bitset const &)
Definition at line 309 of file item_tname.cpp.
 {
     if( it.ethereal ) {
         return string_format( _( " (%s turns)" ), it.get_var( "ethereal" ) );
     }
     return {};
 }
References _, item::ethereal, item::get_var(), and string_format().
Referenced by anonymous_namespace{item.cpp}::_stacks_ethereal(), get_segs_array(), and item::io().
faults()
std::string anonymous_namespace{item_tname.cpp}::faults (item const & it, unsigned int , segment_bitset const &)
Definition at line 49 of file item_tname.cpp.
 {
     std::string damtext;
     // add first prefix if item has a fault that defines a prefix (prioritize?)
     for( const fault_id &f : it.faults ) {
         const std::string prefix = f->item_prefix();
         if( !prefix.empty() ) {
             damtext = prefix + " ";
             break;
         }
     }
     return damtext;
 }
References item::faults, and fault::item_prefix().
Referenced by item::deserialize(), get_segs_array(), item::io(), and timed_event::per_turn().
filthy()
std::string anonymous_namespace{item_tname.cpp}::filthy (item const & it, unsigned int , segment_bitset const &)
Definition at line 389 of file item_tname.cpp.
 {
     if( it.is_filthy() ) {
         return _( " (filthy)" );
     }
     return {};
 }
References _, and item::is_filthy().
Referenced by salvage_actor::cut_up(), and get_segs_array().
food_irradiated()
std::string anonymous_namespace{item_tname.cpp}::food_irradiated (item const & it, unsigned int , segment_bitset const &)
Definition at line 338 of file item_tname.cpp.
 {
     if( it.goes_bad() ) {
         if( it.has_own_flag( flag_IRRADIATED ) ) {
             return _( " (irradiated)" );
         }
     }
     return {};
 }
References _, flag_IRRADIATED, item::goes_bad(), and item::has_own_flag().
Referenced by get_segs_array().
food_status()
std::string anonymous_namespace{item_tname.cpp}::food_status (item const & it, unsigned int , segment_bitset const &)
Definition at line 318 of file item_tname.cpp.
 {
     std::string tagtext;
     if( it.goes_bad() || it.is_food() ) {
         if( it.has_own_flag( flag_DIRTY ) ) {
             tagtext += _( " (dirty)" );
         } else if( it.rotten() ) {
             tagtext += _( " (rotten)" );
         } else if( it.has_flag( flag_MUSHY ) ) {
             tagtext += _( " (mushy)" );
         } else if( it.is_going_bad() ) {
             tagtext += _( " (old)" );
         } else if( it.is_fresh() ) {
             tagtext += _( " (fresh)" );
         }
     }
     return tagtext;
 }
References _, flag_DIRTY, flag_MUSHY, item::goes_bad(), item::has_flag(), item::has_own_flag(), item::is_food(), item::is_fresh(), item::is_going_bad(), and item::rotten().
Referenced by get_segs_array().
food_traits()
std::string anonymous_namespace{item_tname.cpp}::food_traits (item const & it, unsigned int , segment_bitset const &)
Definition at line 275 of file item_tname.cpp.
 {
     if( it.is_food() ) {
         if( it.has_flag( flag_HIDDEN_POISON ) &&
             get_avatar().get_greater_skill_or_knowledge_level( skill_survival ) >= 3 ) {
             return _( " (poisonous)" );
         } else if( it.has_flag( flag_HIDDEN_HALLU ) &&
                    get_avatar().get_greater_skill_or_knowledge_level( skill_survival ) >= 5 ) {
             return _( " (hallucinogenic)" );
         }
     }
     return {};
 }
References _, flag_HIDDEN_HALLU, flag_HIDDEN_POISON, get_avatar(), item::has_flag(), item::is_food(), and skill_survival.
Referenced by get_segs_array().
get_segs_array()
constexpr std::array<decl_f_print_segment *, num_segments> anonymous_namespace{item_tname.cpp}::get_segs_array () constexpr
Definition at line 554 of file item_tname.cpp.
 {
     std::array<decl_f_print_segment *, num_segments> arr{};
     arr[static_cast<size_t>( tname::segments::FAULTS ) ] = faults;
     arr[static_cast<size_t>( tname::segments::DIRT ) ] = dirt_symbol;
     arr[static_cast<size_t>( tname::segments::OVERHEAT ) ] = overheat_symbol;
     arr[static_cast<size_t>( tname::segments::FAVORITE_PRE ) ] = pre_asterisk;
     arr[static_cast<size_t>( tname::segments::DURABILITY ) ] = durability;
     arr[static_cast<size_t>( tname::segments::WHEEL_DIAMETER ) ] = wheel_diameter;
     arr[static_cast<size_t>( tname::segments::BURN ) ] = burn;
     arr[static_cast<size_t>( tname::segments::WEAPON_MODS ) ] = weapon_mods;
     arr[static_cast<size_t>( tname::segments::CUSTOM_ITEM_PREFIX )] = custom_item_prefix;
     arr[static_cast<size_t>( tname::segments::TYPE ) ] = label;
     arr[static_cast<size_t>( tname::segments::CATEGORY ) ] = category;
     arr[static_cast<size_t>( tname::segments::CUSTOM_ITEM_SUFFIX )] = custom_item_suffix;
     arr[static_cast<size_t>( tname::segments::MODS ) ] = mods;
     arr[static_cast<size_t>( tname::segments::CRAFT ) ] = craft;
     arr[static_cast<size_t>( tname::segments::WHITEBLACKLIST ) ] = wbl_mark;
     arr[static_cast<size_t>( tname::segments::CHARGES ) ] = noop;
     arr[static_cast<size_t>( tname::segments::FOOD_TRAITS ) ] = food_traits;
     arr[static_cast<size_t>( tname::segments::FOOD_STATUS ) ] = food_status;
     arr[static_cast<size_t>( tname::segments::FOOD_IRRADIATED ) ] = food_irradiated;
     arr[static_cast<size_t>( tname::segments::TEMPERATURE ) ] = temperature;
     arr[static_cast<size_t>( tname::segments::LOCATION_HINT ) ] = location_hint;
     arr[static_cast<size_t>( tname::segments::CLOTHING_SIZE ) ] = clothing_size;
     arr[static_cast<size_t>( tname::segments::ETHEREAL ) ] = ethereal;
     arr[static_cast<size_t>( tname::segments::FILTHY ) ] = filthy;
     arr[static_cast<size_t>( tname::segments::BROKEN ) ] = segment_broken;
     arr[static_cast<size_t>( tname::segments::CBM_STATUS ) ] = cbm_status;
     arr[static_cast<size_t>( tname::segments::UPS ) ] = ups;
     arr[static_cast<size_t>( tname::segments::TAGS ) ] = tags;
     arr[static_cast<size_t>( tname::segments::VARS ) ] = vars;
     arr[static_cast<size_t>( tname::segments::WETNESS ) ] = wetness;
     arr[static_cast<size_t>( tname::segments::ACTIVE ) ] = active;
     arr[static_cast<size_t>( tname::segments::SEALED ) ] = sealed;
     arr[static_cast<size_t>( tname::segments::FAVORITE_POST ) ] = post_asterisk;
     arr[static_cast<size_t>( tname::segments::RELIC ) ] = relic_charges;
     arr[static_cast<size_t>( tname::segments::LINK ) ] = noop;
     arr[static_cast<size_t>( tname::segments::TECHNIQUES ) ] = noop;
     arr[static_cast<size_t>( tname::segments::CONTENTS ) ] = contents;
     return arr;
 }
References active(), tname::ACTIVE, tname::BROKEN, burn(), tname::BURN, category(), tname::CATEGORY, cbm_status(), tname::CBM_STATUS, tname::CHARGES, clothing_size(), tname::CLOTHING_SIZE, contents(), tname::CONTENTS, craft(), tname::CRAFT, custom_item_prefix(), tname::CUSTOM_ITEM_PREFIX, custom_item_suffix(), tname::CUSTOM_ITEM_SUFFIX, tname::DIRT, dirt_symbol(), durability(), tname::DURABILITY, ethereal(), tname::ETHEREAL, faults(), tname::FAULTS, tname::FAVORITE_POST, tname::FAVORITE_PRE, filthy(), tname::FILTHY, food_irradiated(), tname::FOOD_IRRADIATED, food_status(), tname::FOOD_STATUS, food_traits(), tname::FOOD_TRAITS, tname::LINK, location_hint(), tname::LOCATION_HINT, mods(), tname::MODS, noop(), tname::OVERHEAT, overheat_symbol(), post_asterisk(), pre_asterisk(), tname::RELIC, relic_charges(), sealed(), tname::SEALED, segment_broken(), tags(), tname::TAGS, tname::TECHNIQUES, tname::TEMPERATURE, tname::TYPE, ups(), tname::UPS, vars(), tname::VARS, wbl_mark(), weapon_mods(), tname::WEAPON_MODS, wetness(), tname::WETNESS, wheel_diameter(), tname::WHEEL_DIAMETER, and tname::WHITEBLACKLIST.
Referenced by all_segments_have_printers(), and tname::print_segment().
label()
std::string anonymous_namespace{item_tname.cpp}::label (item const & it, unsigned int quantity, segment_bitset const & segments)
Definition at line 142 of file item_tname.cpp.
 {
     if( !it.is_craft() ) {
         return it.label( quantity, segments[tname::segments::VARIANT],
                          ( segments & tname::tname_conditional ) == tname::tname_conditional,
                          segments[tname::segments::CORPSE] );
     }
     return {};
 }
References tname::CORPSE, item::is_craft(), item::label(), tname::tname_conditional(), and tname::VARIANT.
Referenced by veh_interact::display_details(), draw_spellbook_info(), vpart_position::get_label(), get_labeled_bar(), load_speech(), vehicle::remove_part(), vpart_position::set_label(), vehicle::shift_parts(), and vehicle::split_vehicles().
location_hint()
std::string anonymous_namespace{item_tname.cpp}::location_hint (item const & it, unsigned int , segment_bitset const &)
Definition at line 290 of file item_tname.cpp.
 {
     if( it.has_var( "spawn_location_omt" ) ) {
         tripoint_abs_omt loc( it.get_var( "spawn_location_omt", tripoint_zero ) );
         tripoint_abs_omt player_loc( ms_to_omt_copy( get_map().getabs( get_avatar().pos() ) ) );
         int dist = rl_dist( player_loc, loc );
         if( dist < 1 ) {
             return _( " (from here)" );
         } else if( dist < 6 ) {
             return _( " (from nearby)" );
         } else if( dist < 30 ) {
             return _( " (from this area)" );
         }
         return _( " (from far away)" );
     }
     return {};
 }
References _, get_avatar(), get_map(), item::get_var(), item::has_var(), ms_to_omt_copy(), math_opers::pos(), rl_dist(), and tripoint_zero.
Referenced by get_segs_array().
mods()
std::string anonymous_namespace{item_tname.cpp}::mods (item const & it, unsigned int , segment_bitset const &)
Definition at line 152 of file item_tname.cpp.
 {
     int amt = 0;
     if( it.is_armor() && it.has_clothing_mod() ) {
         amt++;
     }
     if( ( ( it.is_gun() || it.is_tool() || it.is_magazine() ) && !it.is_power_armor() ) ||
         it.get_contents().has_additional_pockets() ) {
         for( const item *mod : it.is_gun() ? it.gunmods() : it.toolmods() ) {
             if( !it.type->gun || !it.type->gun->built_in_mods.count( mod->typeId() ) ||
                 !it.type->gun->default_mods.count( mod->typeId() ) ) {
                 amt++;
             }
         }
         amt += it.get_contents().get_added_pockets().size();
     }
     if( amt > 0 ) {
         return string_format( "+%d", amt );
     }
     return {};
 }
References item_contents::get_added_pockets(), item::get_contents(), itype::gun, item::gunmods(), item_contents::has_additional_pockets(), item::has_clothing_mod(), item::is_armor(), item::is_gun(), item::is_magazine(), item::is_power_armor(), item::is_tool(), string_format(), item::toolmods(), and item::type.
Referenced by inventory_selector::add_contained_gunmods(), assign(), detach_gunmods_actor::can_use(), modify_gunmods_actor::can_use(), worldfactory::draw_mod_list(), Character::effect_vitamin_mod(), gunmod_remove_activity_actor::finish(), Character::get_mutation_bionic_social_mods(), get_segs_array(), Character::gunmod_add(), Character::gunmod_remove(), item_pocket::gunmods(), game::load_world_modfiles(), main(), worldfactory::make_new_world(), mod_manager::remove_invalid_mods(), mod_manager::set_default_mods(), mod_manager::set_usable_mods(), worldfactory::show_worldgen_tab_modselection(), detach_gunmods_actor::use(), and modify_gunmods_actor::use().
noop()
std::string anonymous_namespace{item_tname.cpp}::noop (item const & , unsigned int , segment_bitset const &)
Definition at line 43 of file item_tname.cpp.
 {
     return {};
 }
Referenced by input_context::get_direction(), input_context::get_direction_rel_ms(), and get_segs_array().
overheat_symbol()
std::string anonymous_namespace{item_tname.cpp}::overheat_symbol (item const & it, unsigned int , segment_bitset const &)
Definition at line 71 of file item_tname.cpp.
 {
     return it.overheat_symbol();
 }
References item::overheat_symbol().
Referenced by get_segs_array().
post_asterisk()
std::string anonymous_namespace{item_tname.cpp}::post_asterisk (item const & it, unsigned int , segment_bitset const &)
Definition at line 506 of file item_tname.cpp.
 {
     if( it.is_favorite && get_option<std::string>( "ASTERISK_POSITION" ) == "suffix" ) {
         return _( " *" );
     }
     return {};
 }
References _, and item::is_favorite.
Referenced by get_segs_array().
pre_asterisk()
std::string anonymous_namespace{item_tname.cpp}::pre_asterisk (item const & it, unsigned int , segment_bitset const &)
Definition at line 77 of file item_tname.cpp.
 {
     if( it.is_favorite && get_option<std::string>( "ASTERISK_POSITION" ) == "prefix" ) {
         return _( "* " ); // Display asterisk for favorite items, before item's name
     }
     return {};
 }
References _, and item::is_favorite.
Referenced by get_segs_array().
relic_charges()
std::string anonymous_namespace{item_tname.cpp}::relic_charges (item const & it, unsigned int , segment_bitset const &)
Definition at line 531 of file item_tname.cpp.
 {
     if( it.is_relic() && it.relic_data->max_charges() > 0 && it.relic_data->charges_per_use() > 0 ) {
         return string_format( " (%d/%d)", it.relic_data->charges(), it.relic_data->max_charges() );
     }
     return {};
 }
References item::is_relic(), item::relic_data, and string_format().
Referenced by get_segs_array().
sealed()
std::string anonymous_namespace{item_tname.cpp}::sealed (item const & it, unsigned int , segment_bitset const &)
Definition at line 495 of file item_tname.cpp.
 {
     if( it.all_pockets_sealed() ) {
         return _( " (sealed)" );
     } else if( it.any_pockets_sealed() ) {
         return _( " (part sealed)" );
     }
     return {};
 }
References _, item::all_pockets_sealed(), and item::any_pockets_sealed().
Referenced by comestible_inventory_preset::comestible_inventory_preset(), map::could_see_items(), get_segs_array(), and item::in_container().
segment_broken()
std::string anonymous_namespace{item_tname.cpp}::segment_broken (item const & it, unsigned int , segment_bitset const &)
Definition at line 445 of file item_tname.cpp.
 {
     if( it.is_broken() ) {
         return _( " (broken)" );
     }
     return {};
 }
References _, and item::is_broken().
Referenced by get_segs_array().
tags()
std::string anonymous_namespace{item_tname.cpp}::tags (item const & it, unsigned int , segment_bitset const &)
Definition at line 398 of file item_tname.cpp.
 {
     std::string ret;
     if( it.is_gun() && ( it.has_flag( flag_COLLAPSED_STOCK ) || it.has_flag( flag_FOLDED_STOCK ) ) ) {
         ret += _( " (folded)" );
     }
     if( it.has_flag( flag_RADIO_MOD ) ) {
         ret += _( " (radio:" );
         if( it.has_flag( flag_RADIOSIGNAL_1 ) ) {
             ret += pgettext( "The radio mod is associated with the [R]ed button.", "R)" );
         } else if( it.has_flag( flag_RADIOSIGNAL_2 ) ) {
             ret += pgettext( "The radio mod is associated with the [B]lue button.", "B)" );
         } else if( it.has_flag( flag_RADIOSIGNAL_3 ) ) {
             ret += pgettext( "The radio mod is associated with the [G]reen button.", "G)" );
         } else {
             debugmsg( "Why is the radio neither red, blue, nor green?" );
             ret += "?)";
         }
     }
     if( it.active && ( it.has_flag( flag_WATER_EXTINGUISH ) || it.has_flag( flag_LITCIG ) ) ) {
         ret += _( " (lit)" );
     }
     return ret;
 }
References _, item::active, debugmsg, flag_COLLAPSED_STOCK, flag_FOLDED_STOCK, flag_LITCIG, flag_RADIO_MOD, flag_RADIOSIGNAL_1, flag_RADIOSIGNAL_2, flag_RADIOSIGNAL_3, flag_WATER_EXTINGUISH, item::has_flag(), item::is_gun(), pgettext, and cata::hash64_detail::ret.
Referenced by details::assign_set(), vehicle::deserialize(), editmap::edit_itm(), foldstring(), get_segs_array(), max_aoe_size(), and vehicle::serialize().
temperature()
std::string anonymous_namespace{item_tname.cpp}::temperature (item const & it, unsigned int , segment_bitset const &)
Definition at line 349 of file item_tname.cpp.
 {
     std::string ret;
     if( it.has_temperature() ) {
         if( it.has_flag( flag_HOT ) ) {
             ret = _( " (hot)" );
         }
         if( it.has_flag( flag_COLD ) ) {
             ret = _( " (cold)" );
         }
         if( it.has_flag( flag_FROZEN ) ) {
             ret += _( " (frozen)" );
         } else if( it.has_flag( flag_MELTS ) ) {
             ret += _( " (melted)" ); // he melted
         }
     }
     return ret;
 }
References _, flag_COLD, flag_FROZEN, flag_HOT, flag_MELTS, item::has_flag(), item::has_temperature(), and cata::hash64_detail::ret.
ups()
std::string anonymous_namespace{item_tname.cpp}::ups (item const & it, unsigned int , segment_bitset const &)
Definition at line 466 of file item_tname.cpp.
 {
     if( it.is_tool() && it.has_flag( flag_USE_UPS ) ) {
         return _( " (UPS)" );
     }
     return {};
 }
References _, flag_USE_UPS, item::has_flag(), item::is_tool(), and ups().
Referenced by get_segs_array(), and ups().
vars()
std::string anonymous_namespace{item_tname.cpp}::vars (item const & it, unsigned int , segment_bitset const &)
Definition at line 424 of file item_tname.cpp.
 {
     std::string ret;
     if( it.has_var( "NANOFAB_ITEM_ID" ) ) {
         if( it.has_flag( flag_NANOFAB_TEMPLATE_SINGLE_USE ) ) {
             //~ Single-use descriptor for nanofab templates. %s = name of resulting item. The leading space is intentional.
             ret += string_format( _( " (SINGLE USE %s)" ),
                                   item::nname( itype_id( it.get_var( "NANOFAB_ITEM_ID" ) ) ) );
         }
         ret += string_format( " (%s)", item::nname( itype_id( it.get_var( "NANOFAB_ITEM_ID" ) ) ) );
     }
     if( it.already_used_by_player( get_avatar() ) ) {
         ret += _( " (used)" );
     }
     if( it.has_flag( flag_IS_UPS ) && it.get_var( "cable" ) == "plugged_in" ) {
         ret += _( " (plugged in)" );
     }
     return ret;
 }
References _, item::already_used_by_player(), flag_IS_UPS, flag_NANOFAB_TEMPLATE_SINGLE_USE, get_avatar(), item::get_var(), item::has_flag(), item::has_var(), item::nname(), cata::hash64_detail::ret, and string_format().
Referenced by get_segs_array().
wbl_mark()
std::string anonymous_namespace{item_tname.cpp}::wbl_mark (item const & it, unsigned int , segment_bitset const &)
Definition at line 196 of file item_tname.cpp.
 {
     std::vector<const item_pocket *> pkts = it.get_all_contained_pockets();
     bool wl = false;
     bool bl = false;
     bool player_wbl = false;
     for( item_pocket const *pkt : pkts ) {
         bool const wl_ = !pkt->settings.get_item_whitelist().empty() ||
                          !pkt->settings.get_category_whitelist().empty();
         bool const bl_ = !pkt->settings.get_item_blacklist().empty() ||
                          !pkt->settings.get_category_blacklist().empty();
         player_wbl |= ( wl_ || bl_ ) && pkt->settings.was_edited();
         wl |= wl_;
         bl |= bl_;
     }
     return
         wl || bl ? colorize( "", player_wbl ? c_light_gray : c_dark_gray ) : std::string();
 }
References c_dark_gray, c_light_gray, colorize(), and item::get_all_contained_pockets().
Referenced by get_segs_array().
weapon_mods()
std::string anonymous_namespace{item_tname.cpp}::weapon_mods (item const & it, unsigned int , segment_bitset const &)
Definition at line 515 of file item_tname.cpp.
 {
     std::string modtext;
     if( it.gunmod_find( itype_barrel_small ) != nullptr ) {
         modtext += _( "sawn-off " );
     }
     if( it.is_gun() && it.has_flag( flag_REMOVED_STOCK ) ) {
         modtext += _( "pistol " );
     }
     if( it.has_flag( flag_DIAMOND ) ) {
         modtext += std::string( pgettext( "Adjective, as in diamond katana", "diamond" ) ) + " ";
     }
     return modtext;
 }
References _, flag_DIAMOND, flag_REMOVED_STOCK, item::gunmod_find(), item::has_flag(), item::is_gun(), itype_barrel_small, and pgettext.
Referenced by get_segs_array().
wetness()
std::string anonymous_namespace{item_tname.cpp}::wetness (item const & it, unsigned int , segment_bitset const &)
Definition at line 475 of file item_tname.cpp.
 {
     if( ( it.wetness > 0 ) || it.has_flag( flag_WET ) ) {
         return _( " (wet)" );
     }
     return {};
 }
References _, flag_WET, item::has_flag(), and item::wetness.
Referenced by get_segs_array(), handle_weather_effects(), item::io(), and Character::update_body_wetness().
wheel_diameter()
std::string anonymous_namespace{item_tname.cpp}::wheel_diameter (item const & it, unsigned int , segment_bitset const &)
Definition at line 99 of file item_tname.cpp.
 {
     if( it.is_wheel() && it.type->wheel->diameter > 0 ) {
         return string_format( pgettext( "vehicle adjective", "%d\" " ), it.type->wheel->diameter );
     }
     return {};
 }
References item::is_wheel(), pgettext, string_format(), item::type, and itype::wheel.
Referenced by get_segs_array().
Variable Documentation
num_segments
constexpr size_t anonymous_namespace{item_tname.cpp}::num_segments = static_cast<size_t>(tname::segments::last_segment) constexpr
Definition at line 552 of file item_tname.cpp.