Cataclysm DDA: anonymous_namespace{inventory_ui.cpp} Namespace Reference
anonymous_namespace{inventory_ui.cpp} Namespace Reference
Classes
struct item_name_t
Typedefs
using startup_timer = std::chrono::time_point< std::chrono::steady_clock, std::chrono::milliseconds >
using name_cache_t = std::unordered_map< item const *, item_name_t >
using parent_path_t = std::vector< item_location >
using pred_t = std::function< bool(inventory_entry const &)>
Functions
void debug_print_timer (startup_timer const &tp, std::string const &msg="inv_ui setup took")
item_name_t & get_cached_name (item const *it)
item_location get_topmost_parent (item_location const &topmost, item_location const &loc, inventory_selector_preset const &preset)
parent_path_t path_to_top (inventory_entry const &e, inventory_selector_preset const &pr)
void move_if (std::vector< inventory_entry > &src, std::vector< inventory_entry > &dst, pred_t const &pred)
bool always_yes (const inventory_entry &)
bool return_item (const inventory_entry &entry)
bool is_container (const item_location &loc)
bool is_worn_id (item_category_id const &id)
item_category const * wielded_worn_category (item_location const &loc, Character const &u)
Variables
startup_timer tp_start
name_cache_t item_name_cache
int item_name_cache_users = 0
Typedef Documentation
name_cache_t
using anonymous_namespace{inventory_ui.cpp}::name_cache_t = typedef std::unordered_map<item const *, item_name_t>
Definition at line 88 of file inventory_ui.cpp.
parent_path_t
using anonymous_namespace{inventory_ui.cpp}::parent_path_t = typedef std::vector<item_location>
Definition at line 113 of file inventory_ui.cpp.
pred_t
using anonymous_namespace{inventory_ui.cpp}::pred_t = typedef std::function<bool(inventory_entry const &)>
Definition at line 127 of file inventory_ui.cpp.
startup_timer
using anonymous_namespace{inventory_ui.cpp}::startup_timer = typedef std::chrono::time_point<std::chrono::steady_clock, std::chrono::milliseconds>
Definition at line 72 of file inventory_ui.cpp.
Function Documentation
always_yes()
bool anonymous_namespace{inventory_ui.cpp}::always_yes (const inventory_entry &)
Definition at line 143 of file inventory_ui.cpp.
 {
     return true;
 }
Referenced by inventory_insert_selector::get_raw_stats(), and selection_column::reset_width().
debug_print_timer()
void anonymous_namespace{inventory_ui.cpp}::debug_print_timer (startup_timer const & tp, std::string const & msg = "inv_ui setup took")
Definition at line 75 of file inventory_ui.cpp.
 {
     startup_timer const tp_now =
         std::chrono::time_point_cast<std::chrono::milliseconds>( std::chrono::steady_clock::now() );
     add_msg_debug( debugmode::DF_GAME, "%s: %i ms", msg, ( tp_now - tp ).count() );
 }
References add_msg_debug, and debugmode::DF_GAME.
Referenced by inventory_pick_selector::execute(), ammo_inventory_selector::execute(), inventory_compare_selector::execute(), inventory_drop_selector::execute(), pickup_selector::execute(), inventory_examiner::execute(), trade_selector::execute(), inventory_multiselector::execute(), and inventory_selector::prepare_layout().
get_cached_name()
item_name_t& anonymous_namespace{inventory_ui.cpp}::get_cached_name (item const * it)
Definition at line 92 of file inventory_ui.cpp.
 {
     auto iter = item_name_cache.find( it );
     if( iter == item_name_cache.end() ) {
         return item_name_cache
                .emplace( it, item_name_t{ remove_color_tags( it->tname( 1, tname::tname_sort_key ) ),
                                           remove_color_tags( it->tname( 1, true ) ),
                                           it->aggregated_contents().count } )
                .first->second;
     }
     return iter->second;
 }
References item::aggregated_contents(), item::aggregate_t::count, item_name_cache, remove_color_tags(), item::tname(), and tname::tname_sort_key().
Referenced by inventory_entry::update_cache().
get_topmost_parent()
item_location anonymous_namespace{inventory_ui.cpp}::get_topmost_parent (item_location const & topmost, item_location const & loc, inventory_selector_preset const & preset)
Definition at line 107 of file inventory_ui.cpp.
 {
     return preset.is_shown( loc ) ? topmost ? topmost : loc : item_location{};
 }
References inventory_selector_preset::is_shown().
Referenced by inventory_selector::add_entry_rec().
is_container()
bool anonymous_namespace{inventory_ui.cpp}::is_container (const item_location & loc)
Definition at line 153 of file inventory_ui.cpp.
 {
     return loc.where() == item_location::type::container;
 }
References item_location::container, and item_location::where().
Referenced by Item_factory::check_definitions(), inventory_holster_preset::is_shown(), auto_pickup::select_items(), and inventory_selector::toggle_categorize_contained().
is_worn_id()
bool anonymous_namespace{inventory_ui.cpp}::is_worn_id (item_category_id const & id)
Definition at line 158 of file inventory_ui.cpp.
 {
     return id == item_category_ITEMS_WORN || id == item_category_INTEGRATED ||
            id == item_category_BIONIC_FUEL_SOURCE;
 }
References item_category_BIONIC_FUEL_SOURCE, item_category_INTEGRATED, and item_category_ITEMS_WORN.
Referenced by inventory_selector_preset::get_cell_text().
move_if()
void anonymous_namespace{inventory_ui.cpp}::move_if (std::vector< inventory_entry > & src, std::vector< inventory_entry > & dst, pred_t const & pred)
Definition at line 128 of file inventory_ui.cpp.
 {
     for( auto it = src.begin(); it != src.end(); ) {
         if( pred( *it ) ) {
             if( it->is_item() ) {
                 dst.emplace_back( std::move( *it ) );
             }
             it = src.erase( it );
         } else {
             ++it;
         }
     }
 }
Referenced by inventory_column::prepare_paging().
path_to_top()
parent_path_t anonymous_namespace{inventory_ui.cpp}::path_to_top (inventory_entry const & e, inventory_selector_preset const & pr)
Definition at line 114 of file inventory_ui.cpp.
 {
     item_location it = e.any_item();
     parent_path_t path{ it };
     while( it.has_parent() ) {
         it = it.parent_item();
         if( pr.is_shown( it ) ) {
             path.emplace_back( it );
         }
     }
     return path;
 }
References inventory_entry::any_item(), item_location::has_parent(), inventory_selector_preset::is_shown(), and item_location::parent_item().
Referenced by inventory_column::indented_sort_compare().
return_item()
bool anonymous_namespace{inventory_ui.cpp}::return_item (const inventory_entry & entry)
Definition at line 148 of file inventory_ui.cpp.
 {
     return entry.is_item();
 }
References inventory_entry::is_item().
Referenced by inventory_selector::_categorize(), inventory_selector::_uncategorize(), inventory_selector::get_only_choice(), inventory_selector::highlight(), inventory_selector::item_entry_count(), ammo_inventory_selector::set_all_entries_chosen_count(), inventory_selector::toggle_categorize_contained(), and inventory_multiselector::toggle_categorize_contained().
wielded_worn_category()
item_category const* anonymous_namespace{inventory_ui.cpp}::wielded_worn_category (item_location const & loc, Character const & u)
Definition at line 164 of file inventory_ui.cpp.
 {
     if( loc == u.get_wielded_item() ) {
         return &item_category_WEAPON_HELD.obj();
     }
     if( u.is_worn( *loc ) || ( loc.has_parent() && is_worn_ablative( loc.parent_item(), loc ) ) ) {
         if( loc->has_flag( flag_BIONIC_FUEL_SOURCE ) ) {
             return &item_category_BIONIC_FUEL_SOURCE.obj();
         }
         if( loc->has_flag( flag_INTEGRATED ) ) {
             return &item_category_INTEGRATED.obj();
         }
         return &item_category_ITEMS_WORN.obj();
     }
     return nullptr;
 }
References flag_BIONIC_FUEL_SOURCE, flag_INTEGRATED, item::has_flag(), item_location::has_parent(), is_worn_ablative(), item_category_BIONIC_FUEL_SOURCE, item_category_INTEGRATED, item_category_ITEMS_WORN, item_category_WEAPON_HELD, string_id< T >::obj(), item_location::parent_item(), and u.
Referenced by inventory_selector::_categorize(), inventory_selector::_uncategorize(), and inventory_selector::add_character_items().
Variable Documentation
item_name_cache
name_cache_t anonymous_namespace{inventory_ui.cpp}::item_name_cache
Definition at line 89 of file inventory_ui.cpp.
Referenced by get_cached_name(), and inventory_selector::~inventory_selector().
item_name_cache_users
int anonymous_namespace{inventory_ui.cpp}::item_name_cache_users = 0
Definition at line 90 of file inventory_ui.cpp.
Referenced by inventory_selector::inventory_selector(), and inventory_selector::~inventory_selector().
tp_start
startup_timer anonymous_namespace{inventory_ui.cpp}::tp_start
Definition at line 73 of file inventory_ui.cpp.
Referenced by inventory_pick_selector::execute(), ammo_inventory_selector::execute(), inventory_compare_selector::execute(), inventory_drop_selector::execute(), pickup_selector::execute(), inventory_examiner::execute(), trade_selector::execute(), inventory_multiselector::execute(), and inventory_selector::inventory_selector().