Cataclysm DDA: game_ui Namespace Reference
game_ui Namespace Reference
Functions
void init_ui ()
Function Documentation
init_ui()
void game_ui::init_ui ()
Definition at line 600 of file game.cpp.
 {
     // clear the screen
     static bool first_init = true;
     if( first_init ) {
 #if !(defined(_WIN32) || defined(TILES))
         check_encoding();
 #endif
         first_init = false;
 #if defined(TILES)
         //class variable to track the option being active
         //only set once, toggle action is used to change during game
         pixel_minimap_option = get_option<bool>( "PIXEL_MINIMAP" );
         if( get_option<std::string>( "PIXEL_MINIMAP_BG" ) == "theme" ) {
             SDL_Color pixel_minimap_color = curses_color_to_SDL( c_black );
             pixel_minimap_r = pixel_minimap_color.r;
             pixel_minimap_g = pixel_minimap_color.g;
             pixel_minimap_b = pixel_minimap_color.b;
             pixel_minimap_a = pixel_minimap_color.a;
         } else {
             pixel_minimap_r = 0x00;
             pixel_minimap_g = 0x00;
             pixel_minimap_b = 0x00;
             pixel_minimap_a = 0xFF;
         }
 #endif // TILES
     }
     // First get TERMX, TERMY
 #if defined(TILES) || defined(_WIN32)
     TERMX = get_terminal_width();
     TERMY = get_terminal_height();
     get_options().get_option( "TERMINAL_X" ).setValue( TERMX * get_scaling_factor() );
     get_options().get_option( "TERMINAL_Y" ).setValue( TERMY * get_scaling_factor() );
     get_options().save();
 #else
     TERMY = getmaxy( catacurses::stdscr );
     TERMX = getmaxx( catacurses::stdscr );
     ensure_term_size();
     // try to make FULL_SCREEN_HEIGHT symmetric according to TERMY
     if( TERMY % 2 ) {
         FULL_SCREEN_HEIGHT = EVEN_MINIMUM_TERM_HEIGHT + 1;
     } else {
         FULL_SCREEN_HEIGHT = EVEN_MINIMUM_TERM_HEIGHT;
     }
 #endif
 }
References c_black, check_encoding(), curses_color_to_SDL(), ensure_term_size(), EVEN_MINIMUM_TERM_HEIGHT, FULL_SCREEN_HEIGHT, options_manager::get_option(), get_options(), get_terminal_height(), get_terminal_width(), catacurses::getmaxx(), catacurses::getmaxy(), pixel_minimap_a, pixel_minimap_b, pixel_minimap_g, pixel_minimap_option, pixel_minimap_r, options_manager::save(), options_manager::cOpt::setValue(), catacurses::stdscr, TERMX, and TERMY.
Referenced by main(), and catacurses::resizeterm().