Cataclysm DDA: talk_function Namespace Reference
talk_function Namespace Reference
Classes
struct teach_domain
Functions
void basecamp_mission (npc &)
void start_camp (npc &)
Start a faction camp on the current OM tile.
void draw_camp_tabs (const catacurses::window &win, base_camps::tab_mode cur_tab, const std::vector< std::vector< mission_entry >> &entries)
std::string name_mission_tabs (const tripoint_abs_omt &omt_pos, const std::string &role_id, const std::string &cur_title, base_camps::tab_mode cur_tab)
std::vector< std::pair< std::string, tripoint_abs_omt > > om_building_region (const tripoint_abs_omt &omt_pos, int range, bool purge=false)
Returns the OM tiles surrounding the camp, purge removes all tiles that aren't expansions.
point om_simple_dir (const tripoint_abs_omt &omt_pos, const tripoint_abs_omt &omt_tar)
Returns the x and y coordinates of (omt_tar - omt_pos), clamped to [-1, 1].
static void scavenger_patrol (mission_data &mission_key, npc &p)
static void scavenger_raid (mission_data &mission_key, npc &p)
static void hospital_raid (mission_data &mission_key, npc &p)
static void commune_menial (mission_data &mission_key, npc &p)
static void commune_carpentry (mission_data &mission_key, npc &p)
static void commune_forage (mission_data &mission_key, npc &p)
static void commune_refuge_caravan (mission_data &mission_key, npc &p)
static bool handle_outpost_mission (const mission_entry &cur_key, npc &p)
void companion_mission (npc &p)
bool display_and_choose_opts (mission_data &mission_key, const tripoint_abs_omt &omt_pos, const std::string &role_id, const std::string &title)
npc_ptr individual_mission (npc &p, const std::string &desc, const mission_id &miss_id, bool group=false, const std::vector< item * > &equipment={}, const std::map< skill_id, int > &required_skills={}, bool silent_failure=false)
Send a companion on an individual mission or attaches them to a group to depart later Set submap_coords and pos.
npc_ptr individual_mission (const tripoint_abs_omt &omt_pos, const std::string &role_id, const std::string &desc, const mission_id &miss_id, bool group=false, const std::vector< item * > &equipment={}, const std::map< skill_id, int > &required_skills={}, bool silent_failure=false)
void caravan_return (npc &p, const std::string &dest, const mission_id &miss_id)
All of these missions are associated with the ranch camp and need to be updated/merged into the new ones.
void caravan_depart (npc &p, const std::string &dest, const mission_id &miss_id)
int caravan_dist (const std::string &dest)
void field_plant (npc &p, const std::string &place)
void field_harvest (npc &p, const std::string &place)
bool scavenging_patrol_return (npc &p)
bool scavenging_raid_return (npc &p)
bool hospital_raid_return (npc &p)
bool labor_return (npc &p)
bool carpenter_return (npc &p)
bool forage_return (npc &p)
void companion_skill_trainer (npc &comp, const std::string &skill_tested="", time_duration time_worked=1_hours, int difficulty=1)
Trains NPC comp, in skill_tested for duration time_worked at difficulty 1, several groups of skills can also be input.
void companion_skill_trainer (npc &comp, const skill_id &skill_tested, time_duration time_worked=1_hours, int difficulty=1)
bool companion_om_combat_check (const comp_list &group, const tripoint_abs_omt &om_tgt, bool try_engage=false)
void force_on_force (const comp_list &defender, const std::string &def_desc, const comp_list &attacker, const std::string &att_desc, int advantage)
bool force_on_force (const comp_list &defender, const std::string &def_desc, const std::vector< monster * > &monsters_fighting, const std::string &att_desc, int advantage)
int combat_score (const comp_list &group)
int combat_score (const std::vector< monster * > &group)
void attack_random (const comp_list &attacker, const comp_list &defender)
void attack_random (const std::vector< monster * > &group, const comp_list &defender)
void attack_random (const comp_list &attacker, const std::vector< monster * > &group)
npc_ptr temp_npc (const string_id< npc_template > &type)
comp_list companion_list (const npc &p, const mission_id &miss_id, bool contains=false)
Returns npcs that have the given companion mission.
comp_list companion_list (const tripoint &omt_pos, const std::string &role_id, const mission_id &miss_id, bool contains=false)
comp_list companion_sort (comp_list available, const std::map< skill_id, int > &required_skills={})
std::vector< comp_rank > companion_rank (const comp_list &available, bool adj=true)
npc_ptr companion_choose (const std::map< skill_id, int > &required_skills={}, bool silent_failure=false)
npc_ptr companion_choose_return (const npc &p, const mission_id &miss_id, const time_point &deadline, bool ignore_parameters=false)
npc_ptr companion_choose_return (const tripoint_abs_omt &omt_pos, const std::string &role_id, const mission_id &miss_id, const time_point &deadline, bool by_mission=true, bool ignore_parameters=false)
npc_ptr companion_choose_return (comp_list &npc_list)
void companion_return (npc &comp)
std::set< item > loot_building (const tripoint_abs_omt &site, const oter_str_id &looted_replacement)
void nothing (npc &)
void assign_mission (npc &)
void mission_success (npc &)
void mission_failure (npc &)
void clear_mission (npc &)
void mission_reward (npc &)
void mission_favor (npc &)
void give_equipment (npc &)
void give_equipment_allowance (npc &p, int allowance)
void lesser_give_aid (npc &)
void lesser_give_all_aid (npc &)
void give_aid (npc &)
void give_all_aid (npc &)
void buy_horse (npc &)
void buy_cow (npc &)
void buy_chicken (npc &)
void bionic_install (npc &)
void bionic_install_allies (npc &)
void bionic_remove (npc &)
void bionic_remove_allies (npc &)
void dismount (npc &)
void find_mount (npc &)
void barber_beard (npc &)
void barber_hair (npc &)
void buy_haircut (npc &)
void buy_shave (npc &)
void morale_chat (npc &)
void morale_chat_activity (npc &)
void start_trade (npc &)
void sort_loot (npc &)
void do_construction (npc &)
void do_mining (npc &)
void do_mopping (npc &)
void do_read (npc &)
void do_eread (npc &)
void do_read_repeatedly (npc &)
void do_chop_plank (npc &)
void do_vehicle_deconstruct (npc &)
void do_vehicle_repair (npc &)
void do_chop_trees (npc &)
void do_fishing (npc &)
void do_farming (npc &)
void do_butcher (npc &)
void revert_activity (npc &)
void goto_location (npc &)
void assign_base (npc &)
void assign_guard (npc &)
void assign_camp (npc &)
void abandon_camp (npc &)
void stop_guard (npc &)
void end_conversation (npc &)
void insult_combat (npc &)
void reveal_stats (npc &)
void drop_items_in_place (npc &p)
void follow (npc &)
void follow_only (npc &)
void deny_follow (npc &)
void deny_lead (npc &)
void deny_equipment (npc &)
void deny_train (npc &)
void deny_personal_info (npc &)
void hostile (npc &)
void flee (npc &)
void leave (npc &)
void stop_following (npc &)
void stranger_neutral (npc &)
bool drop_stolen_item (item &cur_item, npc &p)
void start_mugging (npc &)
void player_leaving (npc &)
void remove_stolen_status (npc &)
void drop_weapon (npc &)
void player_weapon_away (npc &)
void player_weapon_drop (npc &)
void drop_stolen_item (npc &)
void lead_to_safety (npc &)
void start_training (npc &)
void start_training_npc (npc &)
void start_training_seminar (npc &p)
void start_training_gen (Character &teacher, std::vector< Character * > &students, teach_domain &d)
void wake_up (npc &)
void copy_npc_rules (npc &p)
void set_npc_pickup (npc &p)
void npc_thankful (npc &p)
void clear_overrides (npc &p)
void pick_style (npc &p)
void do_craft (npc &)
void do_disassembly (npc &p)
Function Documentation
abandon_camp()
void talk_function::abandon_camp (npc & p)
Definition at line 421 of file npctalk_funcs.cpp.
 {
     std::optional<basecamp *> bcp = overmap_buffer.find_camp( p.global_omt_location().xy() );
     if( bcp ) {
         basecamp *temp_camp = *bcp;
         temp_camp->abandon_camp();
     }
 }
References basecamp::abandon_camp(), overmapbuffer::find_camp(), Creature::global_omt_location(), overmap_buffer, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by talk_effect_t::parse_string_effect().
assign_base()
void talk_function::assign_base (npc &)
assign_camp()
void talk_function::assign_camp (npc & p)
Definition at line 430 of file npctalk_funcs.cpp.
 {
     std::optional<basecamp *> bcp = overmap_buffer.find_camp( p.global_omt_location().xy() );
     if( bcp ) {
         basecamp *temp_camp = *bcp;
         p.set_attitude( NPCATT_NULL );
         p.set_mission( NPC_MISSION_GUARD_ALLY );
         temp_camp->add_assignee( p.getID() );
         temp_camp->job_assignment_ui();
         temp_camp->validate_assignees();
         add_msg( _( "%1$s is assigned to %2$s" ), p.disp_name(), temp_camp->camp_name() );
         if( p.has_player_activity() ) {
             p.revert_after_activity();
         }
         p.chatbin.first_topic = p.chatbin.talk_friend_guard;
         p.set_omt_destination();
     }
 }
References _, basecamp::add_assignee(), add_msg(), basecamp::camp_name(), npc::chatbin, Character::disp_name(), overmapbuffer::find_camp(), dialogue_chatbin::first_topic, Character::getID(), Creature::global_omt_location(), npc::has_player_activity(), basecamp::job_assignment_ui(), NPC_MISSION_GUARD_ALLY, NPCATT_NULL, overmap_buffer, npc::revert_after_activity(), npc::set_attitude(), npc::set_mission(), npc::set_omt_destination(), dialogue_chatbin::talk_friend_guard, basecamp::validate_assignees(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by talk_effect_t::parse_string_effect(), and basecamp::worker_assignment_ui().
assign_guard()
void talk_function::assign_guard (npc & p)
Definition at line 404 of file npctalk_funcs.cpp.
 {
     if( !p.is_player_ally() ) {
         p.set_mission( NPC_MISSION_GUARD );
         p.set_omt_destination();
         return;
     }
     if( p.has_player_activity() ) {
         p.revert_after_activity();
     }
     p.set_attitude( NPCATT_NULL );
     p.set_mission( NPC_MISSION_GUARD_ALLY );
     p.chatbin.first_topic = p.chatbin.talk_friend_guard;
     p.set_omt_destination();
 }
References npc::chatbin, dialogue_chatbin::first_topic, npc::has_player_activity(), npc::is_player_ally(), NPC_MISSION_GUARD, NPC_MISSION_GUARD_ALLY, NPCATT_NULL, npc::revert_after_activity(), npc::set_attitude(), npc::set_mission(), npc::set_omt_destination(), and dialogue_chatbin::talk_friend_guard.
Referenced by game::chat(), npc::go_to_omt_destination(), talk_effect_t::parse_string_effect(), and npc::reach_omt_destination().
assign_mission()
void talk_function::assign_mission (npc & p)
Definition at line 115 of file npctalk_funcs.cpp.
 {
     mission *miss = p.chatbin.mission_selected;
     if( miss == nullptr ) {
         debugmsg( "assign_mission: mission_selected == nullptr" );
         return;
     } else if( miss->is_assigned() ) {
         DebugLog( D_WARNING, D_MAIN ) << "assign_mission: mission_id: " << miss->mission_id().str() <<
                                       " is already assigned!";
         return;
     }
     miss->assign( get_avatar() );
     p.chatbin.missions_assigned.push_back( miss );
     const auto it = std::find( p.chatbin.missions.begin(), p.chatbin.missions.end(), miss );
     p.chatbin.missions.erase( it );
 }
References mission::assign(), npc::chatbin, D_MAIN, D_WARNING, DebugLog(), debugmsg, get_avatar(), mission::is_assigned(), mission::mission_id(), dialogue_chatbin::mission_selected, dialogue_chatbin::missions, dialogue_chatbin::missions_assigned, and string_id< T >::str().
Referenced by talk_effect_t::parse_string_effect().
attack_random() [1/3]
void talk_function::attack_random (const comp_list & attacker, const comp_list & defender)
attack_random() [2/3]
void talk_function::attack_random (const comp_list & attacker, const std::vector< monster * > & group)
attack_random() [3/3]
void talk_function::attack_random (const std::vector< monster * > & group, const comp_list & defender)
barber_beard()
void talk_function::barber_beard (npc &)
Definition at line 770 of file npctalk_funcs.cpp.
 {
     generic_barber( "facial_hair" );
 }
References generic_barber().
Referenced by talk_effect_t::parse_string_effect().
barber_hair()
void talk_function::barber_hair (npc &)
Definition at line 775 of file npctalk_funcs.cpp.
 {
     generic_barber( "hair_style" );
 }
References generic_barber().
Referenced by talk_effect_t::parse_string_effect().
basecamp_mission()
void talk_function::basecamp_mission (npc & p)
Definition at line 747 of file faction_camp.cpp.
 {
     const std::string title = _( "Base Missions" );
     const tripoint_abs_omt omt_pos = p.global_omt_location();
     mission_data mission_key;
     std::optional<basecamp *> temp_camp = get_basecamp( p );
     if( !temp_camp ) {
         return;
     }
     basecamp *bcp = *temp_camp;
     bcp->set_by_radio( get_avatar().dialogue_by_radio );
     map &here = bcp->get_camp_map();
     bcp->form_storage_zones( here, p.get_location() );
     bcp->get_available_missions( mission_key, here );
     if( display_and_choose_opts( mission_key, omt_pos, base_camps::id, title ) ) {
         bcp->handle_mission( mission_key.cur_key.id );
     }
     here.save();
     // This is to make sure the basecamp::camp_map is always usable and valid.
     // Otherwise when quick saving unloads submaps, basecamp::camp_map is still valid but becomes unusable.
     bcp->unload_camp_map();
 }
References _, mission_data::cur_key, display_and_choose_opts(), basecamp::form_storage_zones(), basecamp::get_available_missions(), get_avatar(), get_basecamp(), basecamp::get_camp_map(), Creature::get_location(), Creature::global_omt_location(), basecamp::handle_mission(), base_camps::id, mission_entry::id, map::save(), basecamp::set_by_radio(), music::title, and basecamp::unload_camp_map().
Referenced by faction_manager::display(), and talk_effect_t::parse_string_effect().
bionic_install()
void talk_function::bionic_install (npc & p)
Definition at line 529 of file npctalk_funcs.cpp.
 {
     Character &pc = get_player_character();
     bionic_install_common( p, pc, pc );
 }
References bionic_install_common(), and get_player_character().
Referenced by talk_effect_t::parse_string_effect().
bionic_install_allies()
void talk_function::bionic_install_allies (npc & p)
Definition at line 535 of file npctalk_funcs.cpp.
 {
     npc *patient = pick_follower();
     if( !patient ) {
         return;
     }
     bionic_install_common( p, get_player_character(), *patient );
 }
References bionic_install_common(), get_player_character(), and pick_follower().
Referenced by talk_effect_t::parse_string_effect().
bionic_remove()
void talk_function::bionic_remove (npc & p)
Definition at line 593 of file npctalk_funcs.cpp.
 {
     bionic_remove_common( p, get_player_character() );
 }
References bionic_remove_common(), and get_player_character().
Referenced by talk_effect_t::parse_string_effect().
bionic_remove_allies()
void talk_function::bionic_remove_allies (npc & p)
Definition at line 598 of file npctalk_funcs.cpp.
 {
     npc *patient = pick_follower();
     if( !patient ) {
         return;
     }
     bionic_remove_common( p, *patient );
 }
References bionic_remove_common(), and pick_follower().
Referenced by talk_effect_t::parse_string_effect().
buy_chicken()
void talk_function::buy_chicken (npc & p)
Definition at line 211 of file npctalk_funcs.cpp.
 {
     spawn_animal( p, mon_chicken );
 }
References mon_chicken, and spawn_animal().
Referenced by talk_effect_t::parse_string_effect().
buy_cow()
void talk_function::buy_cow (npc & p)
Definition at line 220 of file npctalk_funcs.cpp.
 {
     spawn_animal( p, mon_cow );
 }
References mon_cow, and spawn_animal().
Referenced by talk_effect_t::parse_string_effect().
buy_haircut()
void talk_function::buy_haircut (npc & p)
Definition at line 780 of file npctalk_funcs.cpp.
 {
     Character &player_character = get_player_character();
     player_character.add_morale( MORALE_HAIRCUT, 5, 5, 720_minutes, 3_minutes );
     const int moves = to_moves<int>( 20_minutes );
     player_character.assign_activity( ACT_WAIT_NPC, moves );
     player_character.activity.str_values.push_back( p.get_name() );
     add_msg( m_good, _( "%s gives you a decent haircut" ), p.get_name() );
 }
References _, ACT_WAIT_NPC, Character::activity, Character::add_morale(), add_msg(), Character::assign_activity(), Character::get_name(), get_player_character(), m_good, MORALE_HAIRCUT, and player_activity::str_values.
Referenced by talk_effect_t::parse_string_effect().
buy_horse()
void talk_function::buy_horse (npc & p)
Definition at line 215 of file npctalk_funcs.cpp.
 {
     spawn_animal( p, mon_horse );
 }
References mon_horse, and spawn_animal().
Referenced by talk_effect_t::parse_string_effect().
buy_shave()
void talk_function::buy_shave (npc & p)
Definition at line 790 of file npctalk_funcs.cpp.
 {
     Character &player_character = get_player_character();
     player_character.add_morale( MORALE_SHAVE, 10, 10, 360_minutes, 3_minutes );
     const int moves = to_moves<int>( 5_minutes );
     player_character.assign_activity( ACT_WAIT_NPC, moves );
     player_character.activity.str_values.push_back( p.get_name() );
     add_msg( m_good, _( "%s gives you a decent shave" ), p.get_name() );
 }
References _, ACT_WAIT_NPC, Character::activity, Character::add_morale(), add_msg(), Character::assign_activity(), Character::get_name(), get_player_character(), m_good, MORALE_SHAVE, and player_activity::str_values.
Referenced by talk_effect_t::parse_string_effect().
caravan_depart()
void talk_function::caravan_depart (npc & p, const std::string & dest, const mission_id & miss_id)
Definition at line 1345 of file mission_companion.cpp.
 {
     mission_id miss_id = id;
     miss_id.parameters = caravan_commune_center_job_assign_parameter;
     std::vector<npc_ptr> npc_list = companion_list( p, miss_id );
     int distance = caravan_dist( dest );
     time_duration time = 20_minutes + distance * 10_minutes;
     const int hours = to_hours<int>( time );
     popup( n_gettext( "The caravan departs with an estimated total travel time of %d hour",
                       "The caravan departs with an estimated total travel time of %d hours", hours ), hours );
     const double uncertainty_multiplier = rng_float( 0.9, 1.1 );
     //  The caravan's duration has an uncertainty, but all members are part of the same caravan...
     for( auto &elem : npc_list ) {
         if( elem->companion_mission_time == calendar::before_time_starts ) {
             //Adds a 10% error in estimated travel time
             elem->set_companion_mission( p, id );
             elem->companion_mission_time = calendar::turn + time * uncertainty_multiplier;
         }
     }
 }
References calendar::before_time_starts, caravan_commune_center_job_assign_parameter, caravan_dist(), companion_list(), int_id< T >::id(), n_gettext, mission_id::parameters, popup(), rng_float(), and calendar::turn.
Referenced by handle_outpost_mission().
caravan_dist()
int talk_function::caravan_dist (const std::string & dest)
Definition at line 1369 of file mission_companion.cpp.
 {
     Character &player_character = get_player_character();
     const tripoint_abs_omt site =
         overmap_buffer.find_closest( player_character.global_omt_location(), dest, 0, false );
     int distance = rl_dist( player_character.global_omt_location(), site );
     return distance;
 }
References overmapbuffer::find_closest(), get_player_character(), Creature::global_omt_location(), overmap_buffer, and rl_dist().
Referenced by caravan_depart(), and caravan_return().
caravan_return()
void talk_function::caravan_return (npc & p, const std::string & dest, const mission_id & miss_id)
All of these missions are associated with the ranch camp and need to be updated/merged into the new ones.
Definition at line 1378 of file mission_companion.cpp.
 {
     npc_ptr comp = companion_choose_return( p, id, calendar::turn,
                                             true );  //  ignore_parameters = true due to backwards compatibility, changed during 0.F
     if( comp == nullptr ) {
         return;
     }
     if( comp->companion_mission_time == calendar::before_time_starts ) {
         popup( _( "%s returns to your party." ), comp->get_name() );
         companion_return( *comp );
         return;
     }
     //So we have chosen to return an individual or party who went on the mission
     //Everyone who was on the mission will have the same companion_mission_time
     //and will simulate the mission and return together
     std::vector<npc_ptr> caravan_party;
     std::vector<npc_ptr> bandit_party;
     std::vector<npc_ptr> npc_list = companion_list( p, id,
                                     true );  //  contains = true due to backwards compatibility, changed during 0.F
     const int rand_caravan_size = rng( 1, 3 );
     caravan_party.reserve( npc_list.size() + rand_caravan_size );
     for( int i = 0; i < rand_caravan_size; i++ ) {
         caravan_party.push_back( temp_npc( npc_template_commune_guard ) );
     }
     for( auto &elem : npc_list ) {
         if( elem->companion_mission_time == comp->companion_mission_time ) {
             caravan_party.push_back( elem );
         }
     }
     int distance = caravan_dist( dest );
     int time = 200 + distance * 100;
     int experience = rng( 10, time / 300 );
     const size_t rand_bandit_size = rng( 1, 3 );
     bandit_party.reserve( rand_bandit_size * 2 );
     for( size_t i = 0; i < rand_bandit_size * 2; i++ ) {
         bandit_party.push_back( temp_npc( npc_template_bandit ) );
         bandit_party.push_back( temp_npc( npc_template_thug ) );
     }
     if( one_in( 3 ) ) {
         if( one_in( 2 ) ) {
             popup( _( "A bandit party approaches the caravan in the open!" ) );
             force_on_force( caravan_party, "caravan", bandit_party, "band", 1 );
         } else if( one_in( 3 ) ) {
             popup( _( "A bandit party attacks the caravan while it it's camped!" ) );
             force_on_force( caravan_party, "caravan", bandit_party, "band", 2 );
         } else {
             popup( _( "The caravan walks into a bandit ambush!" ) );
             force_on_force( caravan_party, "caravan", bandit_party, "band", -1 );
         }
     }
     int merch_amount = 0;
     for( const auto &elem : caravan_party ) {
         //Scrub temporary party members and the dead
         if( elem->get_part_hp_cur( bodypart_id( "torso" ) ) == 0 && elem->has_companion_mission() ) {
             overmap_buffer.remove_npc( comp->getID() );
             merch_amount += ( time / 600 ) * 4;
         } else if( elem->has_companion_mission() ) {
             merch_amount += ( time / 600 ) * 7;
             companion_skill_trainer( *elem, "combat", experience * 10_minutes, 10 );
             companion_return( *elem );
         }
     }
     if( merch_amount != 0 ) {
         item merch = item( itype_FMCNote );
         get_player_character().i_add_or_drop( merch, merch_amount );
         popup( _( "The caravan party has returned.  Your share of the profits are %d merch!" ),
                merch_amount );
     } else {
         popup( _( "The caravan was a disaster and your companions never made it home" ) );
     }
 }
References _, calendar::before_time_starts, caravan_dist(), companion_choose_return(), companion_list(), companion_return(), companion_skill_trainer(), force_on_force(), get_player_character(), Character::i_add_or_drop(), itype_FMCNote, npc_template_bandit, npc_template_commune_guard, npc_template_thug, one_in(), overmap_buffer, popup(), overmapbuffer::remove_npc(), rng(), temp_npc(), and calendar::turn.
Referenced by handle_outpost_mission().
carpenter_return()
bool talk_function::carpenter_return (npc & p)
NPC Fabrication affects carpenter mission results NPC Dodge affects carpenter mission results NPC Survival affects carpenter mission results
Definition at line 2081 of file mission_companion.cpp.
 {
     npc_ptr comp = companion_choose_return( p, { Carpentry_Job, "", {}, std::nullopt},
                                             calendar::turn - 1_hours );
     if( comp == nullptr ) {
         return false;
     }
     if( one_in( 20 ) ) {
         // the following doxygen aliases do not yet exist. this is marked for future reference
         ///\EFFECT_FABRICATION_NPC affects carpenter mission results
         ///\EFFECT_DODGE_NPC affects carpenter mission results
         ///\EFFECT_SURVIVAL_NPC affects carpenter mission results
         int skill_1 = comp->get_greater_skill_or_knowledge_level( skill_fabrication );
         int skill_2 = comp->get_skill_level( skill_dodge );
         int skill_3 = comp->get_skill_level( skill_survival );
         popup( _( "While %s was framing a building, one of the walls began to collapse" ),
                comp->get_name() );
         if( skill_1 > rng( 1, 8 ) ) {
             popup( _( "In the blink of an eye, %s threw a brace up and averted a disaster." ),
                    comp->get_name() );
         } else if( skill_2 > rng( 1, 8 ) ) {
             popup( _( "Darting out a window, %s escaped the collapse." ), comp->get_name() );
         } else if( skill_3 > rng( 1, 8 ) ) {
             popup( _( "%s didn't make it out in time" ), comp->get_name() );
             popup( _( "but %s was rescued from the debris with only minor injuries!" ),
                    comp->get_name() );
         } else {
             popup( _( "%s didn't make it out in time" ), comp->get_name() );
             popup( _( "Everyone who was trapped under the collapsing roof died" ) );
             popup( _( "I'm sorry, there is nothing we could do." ) );
             overmap_buffer.remove_npc( comp->getID() );
             return false;
         }
     }
     float hours = to_hours<float>( calendar::turn - comp->companion_mission_time );
     int merch_amount = 5 * hours;
     companion_skill_trainer( *comp, "construction", calendar::turn -
                              comp->companion_mission_time, 2 );
     popup( _( "%s returns from working as a carpenter having earned %d merch and a bit of "
               "experience" ), comp->get_name(), merch_amount );
     item merch = item( itype_FMCNote );
     get_player_character().i_add_or_drop( merch, merch_amount );
     companion_return( *comp );
     return true;
 }
References _, Carpentry_Job, companion_choose_return(), companion_return(), companion_skill_trainer(), get_player_character(), Character::i_add_or_drop(), itype_FMCNote, one_in(), overmap_buffer, popup(), overmapbuffer::remove_npc(), rng(), skill_dodge, skill_fabrication, skill_survival, and calendar::turn.
Referenced by handle_outpost_mission().
clear_mission()
void talk_function::clear_mission (npc & p)
Definition at line 171 of file npctalk_funcs.cpp.
 {
     mission *miss = p.chatbin.mission_selected;
     if( miss == nullptr ) {
         debugmsg( "clear_mission: mission_selected == nullptr" );
         return;
     }
     const auto it = std::find( p.chatbin.missions_assigned.begin(), p.chatbin.missions_assigned.end(),
                                miss );
     if( it == p.chatbin.missions_assigned.end() ) {
         debugmsg( "clear_mission: mission_selected not in assigned" );
         return;
     }
     p.chatbin.missions_assigned.erase( it );
     if( p.chatbin.missions_assigned.empty() ) {
         p.chatbin.mission_selected = nullptr;
     } else {
         p.chatbin.mission_selected = p.chatbin.missions_assigned.front();
     }
     if( miss->has_follow_up() ) {
         p.add_new_mission( mission::reserve_new( miss->get_follow_up(), p.getID() ) );
         if( !p.chatbin.mission_selected ) {
             p.chatbin.mission_selected = p.chatbin.missions.front();
         }
     }
 }
References npc::add_new_mission(), npc::chatbin, debugmsg, mission::get_follow_up(), Character::getID(), mission::has_follow_up(), dialogue_chatbin::mission_selected, dialogue_chatbin::missions, dialogue_chatbin::missions_assigned, and mission::reserve_new().
Referenced by talk_effect_t::parse_string_effect(), and start_training_gen().
clear_overrides()
void talk_function::clear_overrides (npc & p)
Definition at line 1277 of file npctalk_funcs.cpp.
 {
     p.rules.clear_overrides();
 }
References npc_follower_rules::clear_overrides(), and npc::rules.
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
combat_score() [1/2]
int talk_function::combat_score (const comp_list & group)
combat_score() [2/2]
int talk_function::combat_score (const std::vector< monster * > & group)
Definition at line 1527 of file mission_companion.cpp.
 {
     int score = 0;
     for( monster * const &elem : group ) {
         if( elem->get_hp() > 0 ) {
             score += elem->type->difficulty;
         }
     }
     return score;
 }
commune_carpentry()
void talk_function::commune_carpentry (mission_data & mission_key, npc & p) static
Definition at line 769 of file mission_companion.cpp.
 {
     std::string entry = _( "Profit: 5 merch/hour\nDanger: Minimal\nTime: 1 hour minimum\n\n"
                            "Carpentry work requires more skill than menial labor while offering "
                            "modestly improved pay.  It is unlikely that your companions will face "
                            "combat, but there are hazards working on makeshift buildings." );
     const mission_id miss_id = {Carpentry_Job, "", {}, std::nullopt};
     mission_key.add_start( miss_id, _( "Assign Ally to Carpentry Work" ), entry );
     std::vector<npc_ptr>  npc_list = companion_list( p, miss_id );
     if( !npc_list.empty() ) {
         entry = _( "Profit: 5 merch/hour\nDanger: Minimal\nTime: 1 hour minimum\n\nLabor Roster:\n" );
         bool avail = false;
         for( auto &elem : npc_list ) {
             avail |= calendar::turn >= elem->companion_mission_time + 1_hours;
             entry += "  " + elem->get_name() + " [" + std::to_string( to_hours<int>( calendar::turn -
                      elem->companion_mission_time ) ) + _( " hours / 1 hour]\n" );
         }
         if( avail ) {
             entry += _( return_ally_question_string );
         }
         mission_key.add_return( miss_id,
                                 _( "Recover Ally from Carpentry Work" ), entry, avail );
     }
 }
References _, mission_data::add_return(), mission_data::add_start(), Carpentry_Job, companion_list(), return_ally_question_string, to_string(), and calendar::turn.
Referenced by companion_mission().
commune_forage()
void talk_function::commune_forage (mission_data & mission_key, npc & p) static
Definition at line 795 of file mission_companion.cpp.
 {
     std::string entry = _( "Profit: 4 merch/hour\nDanger: Low\nTime: 4 hour minimum\n\n"
                            "Foraging for food involves dispatching a companion to search the "
                            "surrounding wilderness for wild edibles.  Combat will be avoided, but "
                            "encounters with wild animals are to be expected.  The low pay is "
                            "supplemented with the odd item as a reward for particularly large "
                            "hauls." );
     const mission_id miss_id = {Forage_Job, "", {}, std::nullopt};
     mission_key.add_start( miss_id, _( "Assign Ally to Forage for Food" ),
                            entry );
     std::vector<npc_ptr> npc_list = companion_list( p, miss_id );
     if( !npc_list.empty() ) {
         bool avail = false;
         entry = _( "Profit: 4 merch/hour\nDanger: Low\nTime: 4 hour minimum\n\nLabor Roster:\n" );
         for( auto &elem : npc_list ) {
             avail |= calendar::turn >= elem->companion_mission_time + 4_hours;
             entry += "  " + elem->get_name() + " [" + std::to_string( to_hours<int>( calendar::turn -
                      elem->companion_mission_time ) ) + _( " hours / 4 hours]\n" );
         }
         if( avail ) {
             entry += _( return_ally_question_string );
         }
         mission_key.add_return( miss_id, _( "Recover Ally from Foraging" ), entry, avail );
     }
 }
References _, mission_data::add_return(), mission_data::add_start(), companion_list(), Forage_Job, return_ally_question_string, to_string(), and calendar::turn.
Referenced by companion_mission().
commune_menial()
void talk_function::commune_menial (mission_data & mission_key, npc & p) static
Definition at line 742 of file mission_companion.cpp.
 {
     std::string entry = _( "Profit: 3 merch/hour\nDanger: None\nTime: 1 hour minimum\n\n"
                            "Assigning one of your allies to menial labor is a safe way to teach "
                            "them basic skills and build reputation with the outpost.  Don't expect "
                            "much of a reward though." );
     const mission_id miss_id = {Menial_Job, "", {}, std::nullopt};
     mission_key.add_start( miss_id, _( "Assign Ally to Menial Labor" ), entry );
     std::vector<npc_ptr> npc_list = companion_list( p, miss_id );
     if( !npc_list.empty() ) {
         std::string entry =
             _( "Profit: 3 merch/hour\nDanger: Minimal\nTime: 1 hour minimum\n\nLabor Roster:\n" );
         bool avail = false;
         for( auto &elem : npc_list ) {
             avail |= calendar::turn >= elem->companion_mission_time + 1_hours;
             entry += "  " + elem->get_name() + " [" + std::to_string( to_hours<int>( calendar::turn -
                      elem->companion_mission_time ) ) + _( " hours / 1 hour]\n" );
         }
         if( avail ) {
             entry += _( return_ally_question_string );
         }
         mission_key.add_return( miss_id, _( "Recover Ally from Menial Labor" ),
                                 entry, avail );
     }
 }
References _, mission_data::add_return(), mission_data::add_start(), companion_list(), Menial_Job, return_ally_question_string, to_string(), and calendar::turn.
Referenced by companion_mission().
commune_refuge_caravan()
void talk_function::commune_refuge_caravan (mission_data & mission_key, npc & p) static
Definition at line 822 of file mission_companion.cpp.
 {
     std::string entry = _( "Profit: 7 merch/hour\nDanger: High\nTime: UNKNOWN\n\n"
                            "Adding companions to the caravan team increases the likelihood of "
                            "success.  By nature, caravans are extremely tempting targets for "
                            "raiders or hostile groups, so only a strong party is recommended.  The "
                            "rewards are significant for those participating, but are even more "
                            "important for the factions that profit.\n\n"
                            "The commune is sending food to the Free Merchants in the Refugee "
                            "Center as part of a tax and in exchange for skilled labor." );
     mission_id miss_id = {
         Caravan_Commune_Center_Job, caravan_commune_center_job_assign_parameter, {}, std::nullopt
     };
     mission_key.add_start( miss_id, _( "Caravan Commune-Refugee Center" ),
                            entry );
     std::vector<npc_ptr> npc_list = companion_list( p, miss_id );
     std::string return_entry = _( "Profit: 7 merch/hour\nDanger: High\nTime: UNKNOWN\n\n"
                                   "\nRoster:\n" );
     bool display_return = false;
     bool ready_return = false;
     if( !npc_list.empty() ) {
         entry = return_entry;
         display_return = true;
         ready_return = true;
         for( auto &elem : npc_list ) {
             const std::string line = "  " + elem->get_name() + _( " [READY TO DEPART]\n" );
             entry += line;
             return_entry += line;
         }
         entry += _( "\n\n"
                     "The caravan will contain two or three additional members "
                     "from the commune, are you ready to depart?" );
         miss_id.parameters = caravan_commune_center_job_active_parameter;
         mission_key.add_start( miss_id,
                                _( "Begin Commune-Refugee Center Run" ), entry );
     }
     miss_id.parameters = caravan_commune_center_job_active_parameter;
     npc_list = companion_list( p, miss_id );
     if( !npc_list.empty() ) {
         display_return = true;
         for( auto &elem : npc_list ) {
             if( calendar::turn >= elem->companion_mission_time ) {
                 ready_return = true;
                 return_entry += "  " + elem->get_name() + _( " [COMPLETE, READY TO BE RETURNED]\n" );
             } else {
                 return_entry += "  " + elem->get_name() + " [" + std::to_string( std::abs( to_hours<int>
                                 ( calendar::turn - elem->companion_mission_time ) ) ) + _( " Hours]\n" );
             }
         }
     }
     // Legacy compatibility. Changed during 0.F.
     miss_id.parameters.clear();
     npc_list = companion_list( p, miss_id );
     if( !npc_list.empty() ) {
         display_return = true;
         for( auto &elem : npc_list ) {
             if( calendar::turn >= elem->companion_mission_time ) {
                 ready_return = true;
                 return_entry += "  " + elem->get_name() + _( " [COMPLETE, READY TO BE RETURNED]\n" );
             } else {
                 return_entry += "  " + elem->get_name() + " [" + std::to_string( std::abs( to_hours<int>
                                 ( calendar::turn - elem->companion_mission_time ) ) ) + _( " Hours]\n" );
             }
         }
     }
     if( display_return ) {
         miss_id.parameters = caravan_commune_center_job_assign_parameter;
         mission_key.add_return( miss_id, _( "Recover Commune-Refugee Center" ),
                                 return_entry, ready_return );
     }
 }
References _, abs(), mission_data::add_return(), mission_data::add_start(), Caravan_Commune_Center_Job, caravan_commune_center_job_active_parameter, caravan_commune_center_job_assign_parameter, companion_list(), line(), mission_id::parameters, to_string(), and calendar::turn.
Referenced by companion_mission().
companion_choose()
npc_ptr talk_function::companion_choose (const std::map< skill_id, int > & required_skills = {}, bool silent_failure = false)
Definition at line 2614 of file mission_companion.cpp.
 {
     Character &player_character = get_player_character();
     std::vector<npc_ptr> available;
     std::optional<basecamp *> bcp = overmap_buffer.find_camp(
                                         player_character.global_omt_location().xy() );
     for( const character_id &elem : g->get_follower_list() ) {
         npc_ptr guy = overmap_buffer.find_npc( elem );
         if( !guy || guy->is_hallucination() ) {
             continue;
         }
         npc_companion_mission c_mission = guy->get_companion_mission();
         // get non-assigned visible followers
         if( player_character.posz() == guy->posz() && !guy->has_companion_mission() &&
             !guy->is_travelling() &&
             ( rl_dist( player_character.pos(), guy->pos() ) <= SEEX * 2 ) &&
             player_character.sees( guy->pos() ) ) {
             available.push_back( guy );
         } else if( bcp ) {
             basecamp *player_camp = *bcp;
             std::vector<npc_ptr> camp_npcs = player_camp->get_npcs_assigned();
             if( std::any_of( camp_npcs.begin(), camp_npcs.end(),
             [guy]( const npc_ptr & i ) {
             return ( i == guy ) && ( !guy->has_companion_mission() );
             } ) ) {
                 available.push_back( guy );
             }
         } else {
             const tripoint_abs_omt guy_omt_pos = guy->global_omt_location();
             std::optional<basecamp *> guy_camp = overmap_buffer.find_camp( guy_omt_pos.xy() );
             if( guy_camp ) {
                 // get NPCs assigned to guard a remote base
                 basecamp *temp_camp = *guy_camp;
                 std::vector<npc_ptr> assigned_npcs = temp_camp->get_npcs_assigned();
                 if( std::any_of( assigned_npcs.begin(), assigned_npcs.end(),
                 [guy]( const npc_ptr & i ) {
                 return ( i == guy ) && ( !guy->has_companion_mission() );
                 } ) ) {
                     available.push_back( guy );
                 }
             }
         }
     }
     if( available.empty() ) {
         if( !silent_failure ) {
             popup( _( "You don't have any companions to send out" ) );
         }
         return nullptr;
     }
     std::vector<uilist_entry> npc_menu;
     available = companion_sort( available, required_skills );
     std::vector<comp_rank> rankings = companion_rank( available );
     int x = 0;
     std::string menu_header;
     if( silent_failure ) {
         menu_header = left_justify( _( "Do you want to send someone else?" ), 51 );
     } else {
         menu_header = left_justify( _( "Who do you want to send?" ), 51 );
     }
     if( required_skills.empty() ) {
         menu_header += _( "[ COMBAT : SURVIVAL : INDUSTRY ]" );
     }
     for( const npc_ptr &e : available ) {
         std::string npc_desc;
         bool can_do = true;
         if( e->mission == NPC_MISSION_GUARD_ALLY ) {
             //~ %1$s: npc name
             npc_desc = string_format( pgettext( "companion", "%1$s (Guarding)" ), e->get_name() );
         } else {
             npc_desc = e->get_name();
         }
         if( required_skills.empty() ) {
             npc_desc = string_format( pgettext( "companion ranking", "%s [ %4d : %4d : %4d ]" ),
                                       left_justify( npc_desc, 51 ), rankings[x].combat,
                                       rankings[x].survival, rankings[x].industry );
         } else {
             npc_desc = left_justify( npc_desc, 51 );
             bool first = true;
             for( const std::pair<const skill_id, int> &skill_tested : required_skills ) {
                 if( first ) {
                     first = false;
                 } else {
                     npc_desc += ", ";
                 }
                 skill_id skill_tested_id = skill_tested.first;
                 int skill_level = skill_tested.second;
                 if( skill_level == 0 ) {
                     //~ %1$s: skill name, %2$d: companion skill level
                     npc_desc += string_format( pgettext( "companion skill", "%1$s %2$d" ),
                                                skill_tested_id.obj().name(),
                                                e->get_knowledge_level( skill_tested_id ) );
                 } else {
                     //~ %1$s: skill name, %2$d: companion skill level, %3$d: skill requirement
                     npc_desc += string_format( pgettext( "companion skill", "%1$s %2$d/%3$d" ),
                                                skill_tested_id.obj().name(),
                                                e->get_knowledge_level( skill_tested_id ),
                                                skill_level );
                     can_do &= e->get_knowledge_level( skill_tested_id ) >= skill_level;
                 }
             }
         }
         uilist_entry npc_entry = uilist_entry( x, can_do, -1, npc_desc );
         npc_menu.push_back( npc_entry );
         x++;
     }
     const size_t npc_choice = uilist( menu_header, npc_menu );
     if( npc_choice >= available.size() ) {
         if( !silent_failure ) {
             popup( _( "You choose to send no one" ), npc_choice );
         }
         return nullptr;
     }
     return available[npc_choice];
 }
References _, available, companion_rank(), companion_sort(), overmapbuffer::find_camp(), overmapbuffer::find_npc(), g, basecamp::get_npcs_assigned(), get_player_character(), Creature::global_omt_location(), left_justify(), Skill::name(), NPC_MISSION_GUARD_ALLY, string_id< T >::obj(), overmap_buffer, pgettext, popup(), Creature::pos(), Creature::posz(), rl_dist(), Character::sees(), SEEX, string_format(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by individual_mission(), and basecamp::start_menial_labor().
companion_choose_return() [1/3]
npc_ptr talk_function::companion_choose_return (comp_list & npc_list)
Definition at line 2778 of file mission_companion.cpp.
 {
     if( npc_list.empty() ) {
         popup( _( "You don't have any companions ready to return" ) );
         return nullptr;
     }
     if( npc_list.size() == 1 ) {
         return npc_list[0];
     }
     std::vector<std::string> npcs;
     npcs.reserve( npc_list.size() );
     for( auto &elem : npc_list ) {
         npcs.push_back( elem->get_name() );
     }
     const size_t npc_choice = uilist( _( "Who should return?" ), npcs );
     if( npc_choice < npc_list.size() ) {
         return npc_list[npc_choice];
     }
     popup( _( "No one returns to your party" ) );
     return nullptr;
 }
References _, and popup().
companion_choose_return() [2/3]
npc_ptr talk_function::companion_choose_return (const npc & p, const mission_id & miss_id, const time_point & deadline, bool ignore_parameters = false)
Definition at line 2735 of file mission_companion.cpp.
 {
     const tripoint_abs_omt omt_pos = p.global_omt_location();
     const std::string &role_id = p.companion_mission_role_id;
     return companion_choose_return( omt_pos, role_id, miss_id, deadline, true, ignore_parameters );
 }
References npc::companion_mission_role_id, and Creature::global_omt_location().
Referenced by caravan_return(), carpenter_return(), basecamp::companion_choose_return(), companion_choose_return(), basecamp::companion_crafting_choose_return(), basecamp::emergency_recall(), basecamp::farm_return(), forage_return(), hospital_raid_return(), labor_return(), scavenging_patrol_return(), and scavenging_raid_return().
companion_choose_return() [3/3]
npc_ptr talk_function::companion_choose_return (const tripoint_abs_omt & omt_pos, const std::string & role_id, const mission_id & miss_id, const time_point & deadline, bool by_mission = true, bool ignore_parameters = false)
Definition at line 2742 of file mission_companion.cpp.
 {
     std::vector<npc_ptr> available;
     Character &player_character = get_player_character();
     for( npc_ptr &guy : overmap_buffer.get_companion_mission_npcs() ) {
         npc_companion_mission c_mission = guy->get_companion_mission();
         if( c_mission.position != omt_pos ||
             c_mission.role_id != role_id ) {
             continue;
         }
         if( by_mission ) {
             if( c_mission.miss_id.id != miss_id.id || c_mission.miss_id.dir != miss_id.dir ) {
                 continue;
             }
             if( !ignore_parameters && c_mission.miss_id.parameters != miss_id.parameters ) {
                 continue;
             }
         }
         if( player_character.has_trait( trait_DEBUG_HS ) ||
             guy->companion_mission_time <= deadline ||
             ( deadline == calendar::before_time_starts &&
               guy->companion_mission_time_ret <= calendar::turn ) ) {
             available.push_back( guy );
         }
     }
     return companion_choose_return( available );
 }
References available, calendar::before_time_starts, companion_choose_return(), mission_id::dir, overmapbuffer::get_companion_mission_npcs(), get_player_character(), Character::has_trait(), mission_id::id, npc_companion_mission::miss_id, overmap_buffer, mission_id::parameters, npc_companion_mission::position, npc_companion_mission::role_id, trait_DEBUG_HS, and calendar::turn.
companion_list() [1/2]
std::vector< npc_ptr > talk_function::companion_list (const npc & p, const mission_id & miss_id, bool contains = false)
Returns npcs that have the given companion mission.
Definition at line 2493 of file mission_companion.cpp.
 {
     std::vector<npc_ptr> available;
     const tripoint_abs_omt omt_pos = p.global_omt_location();
     for( const auto &elem : overmap_buffer.get_companion_mission_npcs() ) {
         npc_companion_mission c_mission = elem->get_companion_mission();
         if( c_mission.position == omt_pos && is_equal( c_mission.miss_id, miss_id ) &&
             c_mission.role_id == p.companion_mission_role_id ) { // NOLINT(bugprone-branch-clone)
             available.push_back( elem );
         } else if( contains && c_mission.miss_id.id == miss_id.id ) {
             available.push_back( elem );
         }
     }
     return available;
 }
References available, npc::companion_mission_role_id, contains, overmapbuffer::get_companion_mission_npcs(), Creature::global_omt_location(), mission_id::id, is_equal(), npc_companion_mission::miss_id, overmap_buffer, npc_companion_mission::position, and npc_companion_mission::role_id.
Referenced by caravan_depart(), caravan_return(), commune_carpentry(), commune_forage(), commune_menial(), commune_refuge_caravan(), hospital_raid(), scavenger_patrol(), scavenger_raid(), and basecamp::upgrade_return().
companion_list() [2/2]
comp_list talk_function::companion_list (const tripoint & omt_pos, const std::string & role_id, const mission_id & miss_id, bool contains = false)
companion_mission()
void talk_function::companion_mission (npc & p)
Definition at line 596 of file mission_companion.cpp.
 {
     mission_data mission_key;
     std::string role_id = p.companion_mission_role_id;
     const tripoint_abs_omt omt_pos = p.global_omt_location();
     std::string title = _( "Outpost Missions" );
     if( role_id == "SCAVENGER" ) {
         title = _( "Junk Shop Missions" );
         scavenger_patrol( mission_key, p );
         if( p.has_trait( trait_NPC_MISSION_LEV_1 ) ) {
             scavenger_raid( mission_key, p );
         }
         Character &player_character = get_player_character();
         if( player_character.get_value( var_SCAVENGER_HOSPITAL_RAID ) == "yes" ) {
             hospital_raid( mission_key, p );
         }
     } else if( role_id == "COMMUNE CROPS" ) {
         title = _( "Agricultural Missions" );
         commune_forage( mission_key, p );
         commune_refuge_caravan( mission_key, p );
     } else if( role_id == "FOREMAN" ) {
         title = _( "Construction Missions" );
         commune_menial( mission_key, p );
         if( p.has_trait( trait_NPC_MISSION_LEV_1 ) ) {
             commune_carpentry( mission_key, p );
         }
     } else if( role_id == "REFUGEE MERCHANT" ) {
         title = _( "Free Merchant Missions" );
         commune_refuge_caravan( mission_key, p );
     } else if( role_id == "PLANT FIELD" ) {
         field_plant( p, omt_ranch_camp_63 );
         return;
     } else if( role_id == "HARVEST FIELD" ) {
         field_harvest( p, omt_ranch_camp_63 );
         return;
     } else {
         return;
     }
     if( display_and_choose_opts( mission_key, omt_pos, role_id, title ) ) {
         handle_outpost_mission( mission_key.cur_key, p );
     }
 }
References _, commune_carpentry(), commune_forage(), commune_menial(), commune_refuge_caravan(), npc::companion_mission_role_id, mission_data::cur_key, display_and_choose_opts(), field_harvest(), field_plant(), get_player_character(), Creature::get_value(), Creature::global_omt_location(), handle_outpost_mission(), Character::has_trait(), hospital_raid(), omt_ranch_camp_63, scavenger_patrol(), scavenger_raid(), music::title, trait_NPC_MISSION_LEV_1, and var_SCAVENGER_HOSPITAL_RAID.
Referenced by talker_npc::set_companion_mission().
companion_om_combat_check()
bool talk_function::companion_om_combat_check (const comp_list & group, const tripoint_abs_omt & om_tgt, bool try_engage = false)
Referenced by basecamp::combat_mission_return().
companion_rank()
std::vector<comp_rank> talk_function::companion_rank (const comp_list & available, bool adj = true)
Referenced by companion_choose().
companion_return()
void talk_function::companion_return (npc & comp)
Definition at line 2472 of file mission_companion.cpp.
 {
     cata_assert( !comp.is_active() );
     comp.reset_companion_mission();
     comp.companion_mission_time = calendar::before_time_starts;
     comp.companion_mission_time_ret = calendar::before_time_starts;
     Character &player_character = get_player_character();
     map &here = get_map();
     for( size_t i = 0; i < comp.companion_mission_inv.size(); i++ ) {
         for( const item &it : comp.companion_mission_inv.const_stack( i ) ) {
             if( !it.count_by_charges() || it.charges > 0 ) {
                 here.add_item_or_charges( player_character.pos(), it );
             }
         }
     }
     comp.companion_mission_inv.clear();
     comp.companion_mission_points.clear();
     // npc *may* be active, or not if outside the reality bubble
     g->reload_npcs();
 }
References map::add_item_or_charges(), calendar::before_time_starts, cata_assert, inventory::clear(), npc::companion_mission_inv, npc::companion_mission_points, npc::companion_mission_time, npc::companion_mission_time_ret, inventory::const_stack(), g, get_map(), get_player_character(), npc::is_active(), Creature::pos(), npc::reset_companion_mission(), and inventory::size().
Referenced by caravan_return(), carpenter_return(), forage_return(), hospital_raid_return(), labor_return(), scavenging_patrol_return(), and scavenging_raid_return().
companion_skill_trainer() [1/2]
void talk_function::companion_skill_trainer (npc & comp, const skill_id & skill_tested, time_duration time_worked = 1_hours, int difficulty = 1)
Definition at line 2465 of file mission_companion.cpp.
 {
     difficulty = std::max( 1, difficulty );
     comp.practice( skill_tested, difficulty * to_minutes<int>( time_worked ) / 10 );
 }
References max(), and Character::practice().
companion_skill_trainer() [2/2]
void talk_function::companion_skill_trainer (npc & comp, const std::string & skill_tested = "", time_duration time_worked = 1_hours, int difficulty = 1)
Trains NPC comp, in skill_tested for duration time_worked at difficulty 1, several groups of skills can also be input.
Definition at line 2437 of file mission_companion.cpp.
 {
     difficulty = std::max( 1, difficulty );
     int checks = 1 + to_minutes<int>( time_worked ) / 10;
     weighted_int_list<skill_id> skill_practice;
     if( skill_tested == "combat" ) {
         const skill_id best_skill = comp.best_combat_skill( combat_skills::ALL ).first;
         if( best_skill ) {
             skill_practice.add( best_skill, 30 );
         }
     }
     for( Skill &sk : Skill::skills ) {
         skill_practice.add( sk.ident(), sk.get_companion_skill_practice( skill_tested ) );
     }
     if( skill_practice.empty() ) {
         comp.practice( skill_id( skill_tested ), difficulty * to_minutes<int>( time_worked ) / 10 );
     } else {
         for( int i = 0; i < checks; i++ ) {
             skill_id *ident = skill_practice.pick();
             if( ident ) {
                 comp.practice( *ident, difficulty );
             }
         }
     }
 }
References weighted_list< W, T >::add(), ALL, npc::best_combat_skill(), weighted_list< W, T >::empty(), max(), weighted_list< W, T >::pick(), Character::practice(), and Skill::skills.
Referenced by caravan_return(), carpenter_return(), basecamp::finish_return(), forage_return(), hospital_raid_return(), labor_return(), scavenging_patrol_return(), scavenging_raid_return(), and survive_random_encounter().
companion_sort()
comp_list talk_function::companion_sort (comp_list available, const std::map< skill_id, int > & required_skills = {})
Definition at line 2542 of file mission_companion.cpp.
 {
     if( required_skills.empty() ) {
         std::sort( available.begin(), available.end(), companion_sort_compare );
         return available;
     }
     skill_id hardest_skill;
     int hardest_diff = -1;
     for( const std::pair<const skill_id, int> &req_skill : required_skills ) {
         if( req_skill.second > hardest_diff ) {
             hardest_diff = req_skill.second;
             hardest_skill = req_skill.first;
         }
     }
     struct companion_sort_skill {
         explicit companion_sort_skill( const skill_id  &skill_tested ) {
             req_skill = skill_tested;
         }
         bool operator()( const npc_ptr &first, const npc_ptr &second ) const {
             return static_cast<int>( first->get_skill_level( req_skill ) ) > static_cast<int>
                    ( second->get_skill_level( req_skill ) );
         }
         skill_id req_skill;
     };
     std::sort( available.begin(), available.end(), companion_sort_skill( hardest_skill ) );
     return available;
 }
References available, companion_sort_compare(), and second.
Referenced by companion_choose().
copy_npc_rules()
void talk_function::copy_npc_rules (npc & p)
Definition at line 1250 of file npctalk_funcs.cpp.
 {
     const npc *other = pick_follower();
     if( other != nullptr && other != &p ) {
         p.rules = other->rules;
     }
 }
References other, pick_follower(), and npc::rules.
Referenced by talk_effect_t::parse_string_effect().
deny_equipment()
void talk_function::deny_equipment (npc & p)
Definition at line 883 of file npctalk_funcs.cpp.
 {
     p.add_effect( effect_asked_for_item, 1_hours );
 }
References Creature::add_effect(), and effect_asked_for_item.
Referenced by talk_effect_t::parse_string_effect().
deny_follow()
void talk_function::deny_follow (npc & p)
Definition at line 873 of file npctalk_funcs.cpp.
 {
     p.add_effect( effect_asked_to_follow, 6_hours );
 }
References Creature::add_effect(), and effect_asked_to_follow.
Referenced by talk_effect_t::parse_string_effect().
deny_lead()
void talk_function::deny_lead (npc & p)
Definition at line 878 of file npctalk_funcs.cpp.
 {
     p.add_effect( effect_asked_to_lead, 6_hours );
 }
References Creature::add_effect(), and effect_asked_to_lead.
Referenced by talk_effect_t::parse_string_effect().
deny_personal_info()
void talk_function::deny_personal_info (npc & p)
Definition at line 893 of file npctalk_funcs.cpp.
 {
     p.add_effect( effect_asked_personal_info, 3_hours );
 }
References Creature::add_effect(), and effect_asked_personal_info.
Referenced by talk_effect_t::parse_string_effect().
deny_train()
void talk_function::deny_train (npc & p)
Definition at line 888 of file npctalk_funcs.cpp.
 {
     p.add_effect( effect_asked_to_train, 6_hours );
 }
References Creature::add_effect(), and effect_asked_to_train.
Referenced by talk_effect_t::parse_string_effect().
dismount()
void talk_function::dismount (npc & p)
Definition at line 276 of file npctalk_funcs.cpp.
 {
     p.npc_dismount();
 }
References npc::npc_dismount().
Referenced by talk_effect_t::parse_string_effect().
display_and_choose_opts()
bool talk_function::display_and_choose_opts (mission_data & mission_key, const tripoint_abs_omt & omt_pos, const std::string & role_id, const std::string & title)
Definition at line 904 of file mission_companion.cpp.
 {
     if( mission_key.entries.empty() ) {
         popup( _( "There are no missions at this colony.  Press Spacebar" ) );
         return false;
     }
     int TITLE_TAB_HEIGHT = 0;
     if( role_id == role_id_faction_camp ) {
         TITLE_TAB_HEIGHT = 1;
     }
     base_camps::tab_mode tab_mode = base_camps::TAB_MAIN;
     size_t sel = 0;
     // The following are for managing the right pane scrollbar.
     size_t info_offset = 0;
     nc_color col = c_white;
     std::vector<std::string> name_text;
     std::vector<std::string> mission_text;
     input_context ctxt( "FACTIONS" );
     ctxt.register_action( "UP", to_translation( "Move cursor up" ) );
     ctxt.register_action( "DOWN", to_translation( "Move cursor down" ) );
     ctxt.register_action( "NEXT_TAB" );
     ctxt.register_action( "PREV_TAB" );
     ctxt.register_action( "PAGE_UP", to_translation( "Fast scroll up" ) );
     ctxt.register_action( "PAGE_DOWN", to_translation( "Fast scroll down" ) );
     ctxt.register_action( "SCROLL_MISSION_INFO_UP" );
     ctxt.register_action( "SCROLL_MISSION_INFO_DOWN" );
     ctxt.register_action( "CONFIRM" );
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     std::vector<mission_entry> cur_key_list;
     auto reset_cur_key_list = [&]() {
         cur_key_list = mission_key.entries[0];
         for( const mission_entry &k : mission_key.entries[1] ) {
             bool has = false;
             for( const mission_entry &keys : cur_key_list ) {
                 if( is_equal( k.id, keys.id ) ) {
                     has = true;
                     break;
                 }
             }
             if( !has ) {
                 cur_key_list.push_back( k );
             }
         }
     };
     reset_cur_key_list();
     if( cur_key_list.empty() ) {
         popup( _( "There are no missions at this colony.  Press Spacebar" ) );
         return false;
     }
     size_t part_y = 0;
     size_t part_x = 0;
     size_t maxy = 0;
     size_t maxx = 0;
     size_t info_height = 0;
     size_t info_width = 0;
     catacurses::window w_list;
     catacurses::window w_tabs;
     catacurses::window w_info;
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         part_y = TERMY > FULL_SCREEN_HEIGHT ? ( TERMY - FULL_SCREEN_HEIGHT ) / 4 : 0;
         part_x = TERMX > FULL_SCREEN_WIDTH ? ( TERMX - FULL_SCREEN_WIDTH ) / 4 : 0;
         maxy = part_y ? TERMY - 2 * part_y : FULL_SCREEN_HEIGHT;
         maxx = part_x ? TERMX - 2 * part_x : FULL_SCREEN_WIDTH;
         info_height = maxy - 3;
         info_width = maxx - 1 - MAX_FAC_NAME_SIZE;
         w_list = catacurses::newwin( maxy, maxx,
                                      point( part_x, part_y + TITLE_TAB_HEIGHT ) );
         w_info = catacurses::newwin( info_height, info_width,
                                      point( part_x + MAX_FAC_NAME_SIZE, part_y + TITLE_TAB_HEIGHT + 1 ) );
         if( role_id == role_id_faction_camp ) {
             w_tabs = catacurses::newwin( TITLE_TAB_HEIGHT, maxx, point( part_x, part_y ) );
             ui.position( point( part_x, part_y ), point( maxx, maxy + TITLE_TAB_HEIGHT ) );
         } else {
             ui.position( point( part_x, part_y + TITLE_TAB_HEIGHT ), point( maxx, maxy ) );
         }
     } );
     ui.mark_resize();
     ui.on_redraw( [&]( const ui_adaptor & ) {
         werase( w_list );
         draw_border( w_list );
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         mvwprintz( w_list, point( 1, 1 ), c_white, name_mission_tabs( omt_pos, role_id, title,
                    tab_mode ) );
         std::vector<std::vector<std::string>> folded_names;
         size_t folded_names_lines = 0;
         for( const mission_entry &cur_key_entry : cur_key_list ) {
             std::vector<std::string> f_name = foldstring( cur_key_entry.name_display, MAX_FAC_NAME_SIZE - 5,
                                               ' ' );
             folded_names_lines += f_name.size();
             folded_names.emplace_back( f_name );
         }
         int name_offset = 0;
         size_t sel_pos = 0;
         // Translate from entry index to line index
         for( size_t i = 0; i < sel; i++ ) {
             sel_pos += folded_names[i].size();
         }
         calcStartPos( name_offset, sel_pos, info_height, folded_names_lines );
         int name_index = 0;
         // Are we so far down the list that we bump into the end?
         bool last_section = folded_names_lines < info_height ||
                             folded_names_lines - info_height <= static_cast<size_t>( name_offset );
         // Translate back from desired line index to the corresponding entry, making sure to round up
         // near the end to ensure the last line gets included.
         if( name_offset > 0 ) {
             for( size_t i = 0; i < cur_key_list.size(); i++ ) {
                 name_offset -= folded_names[i].size();
                 if( name_offset <= 0 ) {
                     if( name_offset == 0 || last_section ) {
                         name_index++;
                     }
                     break;
                 }
                 name_index++;
             }
         }
         size_t list_line = 2;
         for( size_t current = name_index; list_line < info_height + 2 &&
              current < cur_key_list.size(); current++ ) {
             nc_color col = current == sel ? h_white : c_white;
             //highlight important missions
             for( const mission_entry &k : mission_key.entries[0] ) {
                 if( is_equal( cur_key_list[current].id, k.id ) ) {
                     col = ( current == sel ? h_white : c_yellow );
                     break;
                 }
             }
             //dull uncraftable items
             for( const mission_entry &k : mission_key.entries[10] ) {
                 if( is_equal( cur_key_list[current].id, k.id ) ) {
                     col = ( current == sel ? h_white : c_dark_gray );
                     break;
                 }
             }
             std::vector<std::string> &name_text = folded_names[current];
             if( list_line + name_text.size() > info_height + 2 ) {
                 break;  //  Skip last entry that would spill over into the bar.
             }
             for( size_t name_line = 0; name_line < name_text.size(); name_line++ ) {
                 print_colored_text( w_list, point( name_line ? 5 : 1, list_line ),
                                     col, col, name_text[name_line] );
                 list_line += 1;
             }
         }
         if( folded_names_lines > info_height ) {
             scrollbar()
             .offset_x( 0 )
             .offset_y( 1 )
             .content_size( folded_names_lines )
             .viewport_pos( sel_pos )
             .viewport_size( info_height )
             .apply( w_list );
         }
         wnoutrefresh( w_list );
         werase( w_info );
         // Fold mission text, store it for scrolling
         mission_text = foldstring( mission_key.cur_key.text, info_width - 2, ' ' );
         if( info_height >= mission_text.size() ) {
             info_offset = 0;
         } else if( info_offset + info_height > mission_text.size() ) {
             info_offset = mission_text.size() - info_height;
         }
         if( mission_text.size() > info_height ) {
             scrollbar()
             .offset_x( info_width - 1 )
             .offset_y( 0 )
             .content_size( mission_text.size() )
             .viewport_pos( info_offset )
             .viewport_size( info_height )
             .apply( w_info );
         }
         const size_t end_line = std::min( info_height, mission_text.size() - info_offset );
         // Display the current subset of the mission text.
         for( size_t start_line = 0; start_line < end_line; start_line++ ) {
             print_colored_text( w_info, point( 0, start_line ), col, col,
                                 mission_text[start_line + info_offset] );
         }
         wnoutrefresh( w_info );
         if( role_id == role_id_faction_camp ) {
             werase( w_tabs );
             draw_camp_tabs( w_tabs, tab_mode, mission_key.entries );
             wnoutrefresh( w_tabs );
         }
     } );
     while( true ) {
         mission_key.cur_key = cur_key_list[sel];
         ui_manager::redraw();
         const std::string action = ctxt.handle_input();
         const int recmax = static_cast<int>( cur_key_list.size() );
         const int scroll_rate = recmax > 20 ? 10 : 3;
         if( action == "UP" || action == "SCROLL_UP" || action == "DOWN" || action == "SCROLL_DOWN" ) {
             sel = inc_clamp_wrap( sel, action == "DOWN" || action == "SCROLL_DOWN", cur_key_list.size() );
             info_offset = 0;
         } else if( action == "SCROLL_MISSION_INFO_UP" ) {
             if( info_offset > 0 ) {
                 info_offset--;
             }
         } else if( action == "SCROLL_MISSION_INFO_DOWN" ) {
             info_offset++;
         } else if( action == "PAGE_UP" || action == "PAGE_DOWN" ) {
             sel = inc_clamp_wrap( sel, action == "PAGE_UP" ? -scroll_rate : scroll_rate, cur_key_list.size() );
             info_offset = 0;
         } else if( action == "NEXT_TAB" && role_id == role_id_faction_camp ) {
             sel = 0;
             info_offset = 0;
             do {
                 if( tab_mode == base_camps::TAB_NW ) {
                     tab_mode = base_camps::TAB_MAIN;
                     reset_cur_key_list();
                 } else {
                     tab_mode = static_cast<base_camps::tab_mode>( tab_mode + 1 );
                     cur_key_list = mission_key.entries[tab_mode + 1];
                 }
             } while( cur_key_list.empty() );
         } else if( action == "PREV_TAB" && role_id == role_id_faction_camp ) {
             sel = 0;
             info_offset = 0;
             do {
                 if( tab_mode == base_camps::TAB_MAIN ) {
                     tab_mode = base_camps::TAB_NW;
                 } else {
                     tab_mode = static_cast<base_camps::tab_mode>( tab_mode - 1 );
                 }
                 if( tab_mode == base_camps::TAB_MAIN ) {
                     reset_cur_key_list();
                 } else {
                     cur_key_list = mission_key.entries[size_t( tab_mode ) + 1];
                 }
             } while( cur_key_list.empty() );
         } else if( action == "QUIT" ) {
             mission_entry dud;
             dud.id = { {No_Mission, "", {}, std::nullopt}, false};
             dud.name_display = "NONE";
             mission_key.cur_key = dud;
             break;
         } else if( action == "CONFIRM" ) {
             if( mission_key.cur_key.possible ) {
                 break;
             } else {
                 continue;
             }
         }
     }
     return true;
 }
References _, action, scrollbar::apply(), c_dark_gray, c_white, c_yellow, calcStartPos(), scrollbar::content_size(), mission_data::cur_key, draw_border(), draw_camp_tabs(), mission_data::entries, foldstring(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, h_white, input_context::handle_input(), ui_mission_id::id, mission_entry::id, inc_clamp_wrap(), is_equal(), MAX_FAC_NAME_SIZE, min(), mvwprintz(), mission_entry::name_display, name_mission_tabs(), catacurses::newwin(), No_Mission, scrollbar::offset_x(), scrollbar::offset_y(), popup(), mission_entry::possible, print_colored_text(), ui_manager::redraw(), input_context::register_action(), role_id_faction_camp, base_camps::TAB_MAIN, base_camps::TAB_NW, TERMX, TERMY, mission_entry::text, music::title, to_translation(), scrollbar::viewport_pos(), scrollbar::viewport_size(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by basecamp_mission(), iexamine::bulletin_board(), and companion_mission().
do_butcher()
void talk_function::do_butcher (npc & p)
Definition at line 299 of file npctalk_funcs.cpp.
 {
     p.assign_activity( ACT_MULTIPLE_BUTCHER );
 }
References ACT_MULTIPLE_BUTCHER, and Character::assign_activity().
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
do_chop_plank()
void talk_function::do_chop_plank (npc & p)
Definition at line 304 of file npctalk_funcs.cpp.
 {
     p.assign_activity( ACT_MULTIPLE_CHOP_PLANKS );
 }
References ACT_MULTIPLE_CHOP_PLANKS, and Character::assign_activity().
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
do_chop_trees()
void talk_function::do_chop_trees (npc & p)
Definition at line 319 of file npctalk_funcs.cpp.
 {
     p.assign_activity( ACT_MULTIPLE_CHOP_TREES );
 }
References ACT_MULTIPLE_CHOP_TREES, and Character::assign_activity().
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
do_construction()
void talk_function::do_construction (npc & p)
Definition at line 246 of file npctalk_funcs.cpp.
 {
     p.assign_activity( ACT_MULTIPLE_CONSTRUCTION );
 }
References ACT_MULTIPLE_CONSTRUCTION, and Character::assign_activity().
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
do_craft()
void talk_function::do_craft (npc & p)
Definition at line 339 of file npctalk_funcs.cpp.
 {
     p.do_npc_craft();
 }
References npc::do_npc_craft().
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
do_disassembly()
void talk_function::do_disassembly (npc & p)
Definition at line 344 of file npctalk_funcs.cpp.
 {
     p.assign_activity( ACT_MULTIPLE_DIS );
 }
References ACT_MULTIPLE_DIS, and Character::assign_activity().
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
do_eread()
void talk_function::do_eread (npc & p)
Definition at line 266 of file npctalk_funcs.cpp.
 {
     p.do_npc_read( true );
 }
References npc::do_npc_read().
Referenced by talk_effect_t::parse_string_effect().
do_farming()
void talk_function::do_farming (npc & p)
Definition at line 324 of file npctalk_funcs.cpp.
 {
     p.assign_activity( ACT_MULTIPLE_FARM );
 }
References ACT_MULTIPLE_FARM, and Character::assign_activity().
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
do_fishing()
void talk_function::do_fishing (npc & p)
Definition at line 329 of file npctalk_funcs.cpp.
 {
     p.assign_activity( ACT_MULTIPLE_FISH );
 }
References ACT_MULTIPLE_FISH, and Character::assign_activity().
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
do_mining()
void talk_function::do_mining (npc & p)
Definition at line 251 of file npctalk_funcs.cpp.
 {
     p.assign_activity( ACT_MULTIPLE_MINE );
 }
References ACT_MULTIPLE_MINE, and Character::assign_activity().
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
do_mopping()
void talk_function::do_mopping (npc & p)
Definition at line 256 of file npctalk_funcs.cpp.
 {
     p.assign_activity( ACT_MULTIPLE_MOP );
 }
References ACT_MULTIPLE_MOP, and Character::assign_activity().
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
do_read()
void talk_function::do_read (npc & p)
Definition at line 261 of file npctalk_funcs.cpp.
 {
     p.do_npc_read();
 }
References npc::do_npc_read().
Referenced by talk_effect_t::parse_string_effect().
do_read_repeatedly()
void talk_function::do_read_repeatedly (npc & p)
Definition at line 271 of file npctalk_funcs.cpp.
 {
     p.assign_activity( ACT_MULTIPLE_READ );
 }
References ACT_MULTIPLE_READ, and Character::assign_activity().
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
do_vehicle_deconstruct()
void talk_function::do_vehicle_deconstruct (npc & p)
Definition at line 309 of file npctalk_funcs.cpp.
 {
     p.assign_activity( ACT_VEHICLE_DECONSTRUCTION );
 }
References ACT_VEHICLE_DECONSTRUCTION, and Character::assign_activity().
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
do_vehicle_repair()
void talk_function::do_vehicle_repair (npc & p)
Definition at line 314 of file npctalk_funcs.cpp.
 {
     p.assign_activity( ACT_VEHICLE_REPAIR );
 }
References ACT_VEHICLE_REPAIR, and Character::assign_activity().
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
draw_camp_tabs()
void talk_function::draw_camp_tabs (const catacurses::window & win, base_camps::tab_mode cur_tab, const std::vector< std::vector< mission_entry >> & entries)
Definition at line 4632 of file faction_camp.cpp.
 {
     werase( win );
     const int width = getmaxx( win );
     mvwhline( win, point( 0, 2 ), LINE_OXOX, width );
     std::vector<std::string> tabs( base_camps::all_directions.size() );
     for( const auto &direction : base_camps::all_directions ) {
         tabs.at( direction.second.tab_order ) = direction.second.tab_title.translated();
     }
     const int tab_step = 3;
     int tab_space = 1;
     int tab_x = 0;
     for( auto &t : tabs ) {
         bool tab_empty = entries[tab_x + 1].empty();
         draw_subtab( win, tab_space, t, tab_x == cur_tab, false, tab_empty );
         tab_space += tab_step + utf8_width( t );
         tab_x++;
     }
     wnoutrefresh( win );
 }
References base_camps::all_directions, draw_subtab(), catacurses::getmaxx(), LINE_OXOX, catacurses::mvwhline(), om_direction::size, utf8_width(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by display_and_choose_opts().
drop_items_in_place()
void talk_function::drop_items_in_place (npc & p)
Definition at line 839 of file npctalk_funcs.cpp.
 {
     std::vector<drop_or_stash_item_info> to_drop;
     // add all non favorite carried items to the drop off list
     for( const item_location &npcs_item : p.all_items_loc() ) {
         if( !npcs_item->is_favorite && npcs_item.where() == item_location::type::container &&
             npcs_item.parent_item().where() == item_location::type::character ) {
             to_drop.emplace_back( npcs_item, npcs_item->count() );
         }
     }
     if( !to_drop.empty() ) {
         // spawn a activity for the npc to drop the specified items
         p.assign_activity( drop_activity_actor( to_drop, tripoint_zero, false ) );
         p.say( "<acknowledged>" );
     } else {
         p.say( _( "I don't have anything to drop off." ) );
     }
 }
References _, Character::all_items_loc(), Character::assign_activity(), item_location::character, item_location::container, npc::say(), and tripoint_zero.
Referenced by talk_effect_t::parse_string_effect().
drop_stolen_item() [1/2]
bool talk_function::drop_stolen_item (item & cur_item, npc & p)
Definition at line 958 of file npctalk_funcs.cpp.
 {
     Character &player_character = get_player_character();
     map &here = get_map();
     bool dropped = false;
     if( cur_item.is_old_owner( p ) ) {
         item to_drop = player_character.i_rem( &cur_item );
         to_drop.remove_old_owner();
         to_drop.set_owner( p );
         here.add_item_or_charges( player_character.pos(), to_drop );
         dropped = true;
     } else if( cur_item.is_container() ) {
         bool changed = false;
         for( item *contained : cur_item.all_items_top() ) {
             changed |= drop_stolen_item( *contained, p );
         }
         if( changed ) {
             dropped = true;
             cur_item.on_contents_changed();
         }
     }
     return dropped;
 }
References map::add_item_or_charges(), item::all_items_top(), get_map(), get_player_character(), Character::i_rem(), item::is_container(), item::is_old_owner(), item::on_contents_changed(), Creature::pos(), item::remove_old_owner(), and item::set_owner().
Referenced by drop_stolen_item(), and talk_effect_t::parse_string_effect().
drop_stolen_item() [2/2]
void talk_function::drop_stolen_item (npc & p)
Definition at line 982 of file npctalk_funcs.cpp.
 {
     bool dropped = false;
     Character &player_character = get_player_character();
     for( item *&elem : player_character.inv_dump() ) {
         dropped |= drop_stolen_item( *elem, p );
     }
     if( dropped ) {
         player_character.invalidate_weight_carried_cache();
     } else {
         debugmsg( "Failed to drop any stolen items." );
     }
     if( p.known_stolen_item ) {
         p.known_stolen_item = nullptr;
     }
     if( player_character.is_hauling() ) {
         player_character.stop_hauling();
     }
     p.set_attitude( NPCATT_NULL );
 }
References debugmsg, drop_stolen_item(), get_player_character(), Character::inv_dump(), Character::invalidate_weight_carried_cache(), Character::is_hauling(), npc::known_stolen_item, NPCATT_NULL, npc::set_attitude(), and Character::stop_hauling().
drop_weapon()
void talk_function::drop_weapon (npc & p)
Definition at line 1023 of file npctalk_funcs.cpp.
 {
     if( p.is_hallucination() ) {
         return;
     }
     item weap = p.remove_weapon();
     get_map().add_item_or_charges( p.pos(), weap );
 }
References map::add_item_or_charges(), get_map(), npc::is_hallucination(), Creature::pos(), and Character::remove_weapon().
Referenced by talk_effect_t::parse_string_effect().
end_conversation()
void talk_function::end_conversation (npc & p)
Definition at line 490 of file npctalk_funcs.cpp.
 {
     add_msg( _( "%s starts ignoring you." ), p.get_name() );
     p.chatbin.first_topic = "TALK_DONE";
 }
References _, add_msg(), npc::chatbin, dialogue_chatbin::first_topic, and Character::get_name().
Referenced by talk_effect_t::parse_string_effect().
field_harvest()
void talk_function::field_harvest (npc & p, const std::string & place)
Definition at line 1653 of file mission_companion.cpp.
 {
     Character &player_character = get_player_character();
     //First we need a list of plants that can be harvested...
     const tripoint_abs_omt site = overmap_buffer.find_closest(
                                       player_character.global_omt_location(), place, 20, false );
     tinymap bay;
     item tmp;
     std::vector<itype_id> seed_types;
     std::vector<itype_id> plant_types;
     std::vector<std::string> plant_names;
     bay.load( site, false );
     for( const tripoint &plot : bay.points_on_zlevel() ) {
         map_stack items = bay.i_at( plot );
         if( bay.furn( plot ) == furn_f_plant_harvest && !items.empty() ) {
             // Can't use item_stack::only_item() since there might be fertilizer
             map_stack::iterator seed = std::find_if( items.begin(), items.end(), []( const item & it ) {
                 return it.is_seed();
             } );
             if( seed != items.end() ) {
                 const islot_seed &seed_data = *seed->type->seed;
                 tmp = item( seed_data.fruit_id, calendar::turn );
                 bool check = false;
                 for( const std::string &elem : plant_names ) {
                     if( elem == tmp.type_name( 3 ) ) {
                         check = true;
                     }
                 }
                 if( !check ) {
                     plant_types.push_back( tmp.typeId() );
                     plant_names.push_back( tmp.type_name( 3 ) );
                     seed_types.push_back( seed->typeId() );
                 }
             }
         }
     }
     if( plant_names.empty() ) {
         popup( _( "There aren't any plants that are ready to harvest" ) );
         return;
     }
     // Choose the crop to harvest
     const int plant_index = uilist( _( "Which plants do you want to have harvested?" ),
                                     plant_names );
     // Did we cancel?
     if( plant_index < 0 || static_cast<size_t>( plant_index ) >= plant_types.size() ) {
         popup( _( "You decided to hold off for now" ) );
         return;
     }
     int number_plots = 0;
     int number_plants = 0;
     int number_seeds = 0;
     int skillLevel = 2;
     if( p.has_trait( trait_NPC_CONSTRUCTION_LEV_2 ) ||
         p.get_value( var_PURCHASED_FIELD_1_FENCE ) == "yes" ) {
         skillLevel += 2;
     }
     for( const tripoint &plot : bay.points_on_zlevel() ) {
         if( bay.furn( plot ) == furn_f_plant_harvest ) {
             // Can't use item_stack::only_item() since there might be fertilizer
             map_stack items = bay.i_at( plot );
             map_stack::iterator seed = std::find_if( items.begin(), items.end(), []( const item & it ) {
                 return it.is_seed();
             } );
             if( seed != items.end() ) {
                 const islot_seed &seed_data = *seed->type->seed;
                 const item item_seed = item( seed->type, calendar::turn );
                 tmp = item( seed_data.fruit_id, calendar::turn );
                 if( tmp.typeId() == plant_types[plant_index] ) {
                     number_plots++;
                     int plant_count = rng( skillLevel / 2, skillLevel );
                     plant_count *= bay.furn( plot )->plant->harvest_multiplier;
                     plant_count = std::min( std::max( plant_count, 1 ), 12 );
                     // Multiply by the plant's and seed's base charges to mimic creating
                     // items similar to iexamine::harvest_plant
                     number_plants += plant_count * tmp.charges;
                     number_seeds += std::max( 1, rng( plant_count / 4, plant_count / 2 ) ) * item_seed.charges;
                     bay.i_clear( plot );
                     bay.furn_set( plot, furn_str_id::NULL_ID() );
                     bay.ter_set( plot, ter_t_dirtmound );
                 }
             }
         }
     }
     bay.save();
     tmp = item( plant_types[plant_index], calendar::turn );
     int merch_amount = std::max( 0, ( number_plants * tmp.price( true ) / 250 ) - number_plots );
     bool liquidate = false;
     if( !player_character.has_amount( itype_FMCNote, number_plots ) ) {
         liquidate = true;
         popup( _( "You don't have enough to pay the workers to harvest the crop, so you are forced "
                   "to sell" ) );
     } else {
         liquidate = query_yn( _( "Do you wish to sell the crop of %1$d %2$s for a profit of %3$d merch?" ),
                               number_plants, plant_names[plant_index], merch_amount );
     }
     //Add fruit
     if( liquidate ) {
         add_msg( _( "The %s are sold for %d merch" ), plant_names[plant_index], merch_amount );
         item merch = item( itype_FMCNote );
         player_character.i_add_or_drop( merch, merch_amount );
     } else {
         if( tmp.count_by_charges() ) {
             tmp.charges = 1;
         }
         player_character.i_add_or_drop( tmp, number_plants );
         add_msg( _( "You receive %d %s" ), number_plants, plant_names[plant_index] );
     }
     tmp = item( seed_types[plant_index], calendar::turn );
     const islot_seed &seed_data = *tmp.type->seed;
     if( seed_data.spawn_seeds ) {
         if( tmp.count_by_charges() ) {
             tmp.charges = 1;
         }
         player_character.i_add_or_drop( tmp, number_seeds );
         add_msg( _( "You receive %d %s" ), number_seeds, tmp.type_name( 3 ) );
     }
 }
References _, add_msg(), item_stack::begin(), item::charges, check(), item::count_by_charges(), item_stack::empty(), item_stack::end(), overmapbuffer::find_closest(), islot_seed::fruit_id, tinymap::furn(), furn_f_plant_harvest, tinymap::furn_set(), get_player_character(), Creature::get_value(), Creature::global_omt_location(), visitable::has_amount(), Character::has_trait(), Character::i_add_or_drop(), tinymap::i_at(), tinymap::i_clear(), itype_FMCNote, tinymap::load(), max(), min(), string_id< furn_t >::NULL_ID(), overmap_buffer, furn_t::plant, tinymap::points_on_zlevel(), popup(), item::price(), query_yn(), rng(), tinymap::save(), itype::seed, iuse::seed(), islot_seed::spawn_seeds, tinymap::ter_set(), ter_t_dirtmound, trait_NPC_CONSTRUCTION_LEV_2, calendar::turn, item::type, item::type_name(), item::typeId(), and var_PURCHASED_FIELD_1_FENCE.
Referenced by companion_mission().
field_plant()
void talk_function::field_plant (npc & p, const std::string & place)
Definition at line 1546 of file mission_companion.cpp.
 {
     Character &player_character = get_player_character();
     if( !warm_enough_to_plant( player_character.pos() ) ) {
         popup( _( "It is too cold to plant anything now." ) );
         return;
     }
     std::vector<item *> seed_inv = player_character.cache_get_items_with( "is_seed", &item::is_seed,
     []( const item & itm ) {
         return itm.typeId() != itype_marloss_seed && itm.typeId() != itype_fungal_seeds;
     } );
     if( seed_inv.empty() ) {
         popup( _( "You have no seeds to plant!" ) );
         return;
     }
     int empty_plots = 0;
     int free_seeds = 0;
     std::vector<itype_id> seed_types;
     std::vector<std::string> seed_names;
     for( item *&seed : seed_inv ) {
         if( std::find( seed_types.begin(), seed_types.end(), seed->typeId() ) == seed_types.end() ) {
             seed_types.push_back( seed->typeId() );
             seed_names.push_back( seed->tname() );
         }
     }
     // Choose seed if applicable
     const int seed_index = uilist( _( "Which seeds do you wish to have planted?" ), seed_names );
     // Did we cancel?
     if( seed_index < 0 || static_cast<size_t>( seed_index ) >= seed_types.size() ) {
         popup( _( "You saved your seeds for later." ) );
         return;
     }
     const auto &seed_id = seed_types[seed_index];
     if( item::count_by_charges( seed_id ) ) {
         free_seeds = player_character.charges_of( seed_id );
     } else {
         free_seeds = player_character.amount_of( seed_id );
     }
     //Now we need to find how many free plots we have to plant in...
     const tripoint_abs_omt site = overmap_buffer.find_closest(
                                       player_character.global_omt_location(), place, 20, false );
     tinymap bay;
     bay.load( site, false );
     for( const tripoint &plot : bay.points_on_zlevel() ) {
         if( bay.ter( plot ) == ter_t_dirtmound ) {
             empty_plots++;
         }
     }
     if( empty_plots == 0 ) {
         popup( _( "You have no room to plant seeds" ) );
         return;
     }
     int limiting_number = free_seeds;
     if( free_seeds > empty_plots ) {
         limiting_number = empty_plots;
     }
     int player_merch = player_character.amount_of( itype_FMCNote );
     if( player_merch == 0 ) {
         popup( _( "I'm sorry, you don't have any money to plant those seeds" ) );
         return;
     }
     if( player_merch < limiting_number ) {
         limiting_number = player_merch;
         if( !query_yn(
                 _( "You only have enough money to plant %d plants.  Do you wish to have %d %s planted here for %d merch?" ),
                 limiting_number, limiting_number,
                 seed_names[seed_index], limiting_number ) ) {
             return;
         }
     } else {
         if( !query_yn( _( "Do you wish to have %d %s planted here for %d merch?" ), limiting_number,
                        seed_names[seed_index], limiting_number ) ) {
             return;
         }
     }
     player_character.use_amount( itype_FMCNote, limiting_number );
     //Plant the actual seeds
     for( const tripoint &plot : bay.points_on_zlevel() ) {
         if( bay.ter( plot ) == ter_t_dirtmound && limiting_number > 0 ) {
             std::list<item> used_seed;
             if( item::count_by_charges( seed_id ) ) {
                 used_seed = player_character.use_charges( seed_id, 1 );
             } else {
                 used_seed = player_character.use_amount( seed_id, 1 );
             }
             used_seed.front().set_age( 0_turns );
             bay.add_item_or_charges( plot, used_seed.front() );
             bay.set( plot, ter_t_dirt, furn_f_plant_seed );
             limiting_number--;
         }
     }
     bay.save();
     popup( _( "After counting your money and collecting your seeds, %s calls forth a labor party "
               "to plant your field." ), p.get_name() );
 }
References _, tinymap::add_item_or_charges(), Character::amount_of(), Character::cache_get_items_with(), Character::charges_of(), item::count_by_charges(), overmapbuffer::find_closest(), furn_f_plant_seed, Character::get_name(), get_player_character(), Creature::global_omt_location(), item::is_seed(), itype_FMCNote, itype_fungal_seeds, itype_marloss_seed, tinymap::load(), overmap_buffer, tinymap::points_on_zlevel(), popup(), Creature::pos(), query_yn(), tinymap::save(), iuse::seed(), tinymap::set(), tinymap::ter(), ter_t_dirt, ter_t_dirtmound, item::typeId(), Character::use_amount(), Character::use_charges(), and warm_enough_to_plant().
Referenced by companion_mission().
find_mount()
void talk_function::find_mount (npc & p)
Definition at line 281 of file npctalk_funcs.cpp.
 {
     // first find one nearby
     for( monster &critter : g->all_monsters() ) {
         if( p.can_mount( critter ) ) {
             // keep the horse still for some time, so that NPC can catch up to it and mount it.
             p.assign_activity( ACT_FIND_MOUNT );
             p.chosen_mount = g->shared_from( critter );
             // we found one, that's all we need.
             return;
         }
     }
     // if we got here and this was prompted by a renewal of the activity, and there are no valid monsters nearby, then cancel whole thing.
     if( p.has_player_activity() ) {
         p.revert_after_activity();
     }
 }
References ACT_FIND_MOUNT, Character::assign_activity(), Character::can_mount(), npc::chosen_mount, g, npc::has_player_activity(), and npc::revert_after_activity().
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
flee()
void talk_function::flee (npc & p)
Definition at line 912 of file npctalk_funcs.cpp.
 {
     add_msg( _( "%s turns to flee!" ), p.get_name() );
     p.set_attitude( NPCATT_FLEE );
 }
References _, add_msg(), Character::get_name(), NPCATT_FLEE, and npc::set_attitude().
Referenced by talk_effect_t::parse_string_effect().
follow()
void talk_function::follow (npc & p)
Definition at line 859 of file npctalk_funcs.cpp.
 {
     g->add_npc_follower( p.getID() );
     p.set_attitude( NPCATT_FOLLOW );
     p.set_fac( faction_your_followers );
     get_player_character().cash += p.cash;
     p.cash = 0;
 }
References Character::cash, faction_your_followers, g, get_player_character(), Character::getID(), NPCATT_FOLLOW, npc::set_attitude(), and npc::set_fac().
Referenced by talker_npc::enslave_mind(), talk_effect_t::parse_string_effect(), basecamp::recruit_return(), and text_style_check().
follow_only()
void talk_function::follow_only (npc & p)
Definition at line 868 of file npctalk_funcs.cpp.
 {
     p.set_attitude( NPCATT_FOLLOW );
 }
References NPCATT_FOLLOW, and npc::set_attitude().
Referenced by talk_effect_t::parse_string_effect().
forage_return()
bool talk_function::forage_return (npc & p)
NPC Survival affects forage mission results NPC Dodge affects forage mission results NPC Survival affects forage mission results
Definition at line 2136 of file mission_companion.cpp.
 {
     npc_ptr comp = companion_choose_return( p, { Forage_Job, "", {}, std::nullopt}, calendar::turn -
                                             4_hours );
     if( comp == nullptr ) {
         return false;
     }
     if( one_in( 10 ) ) {
         popup( _( "While foraging, a beast began to stalk %s" ), comp->get_name() );
         // the following doxygen aliases do not yet exist. this is marked for future reference
         ///\EFFECT_SURVIVAL_NPC affects forage mission results
         ///\EFFECT_DODGE_NPC affects forage mission results
         int skill_1 = comp->get_skill_level( skill_survival );
         int skill_2 = comp->get_skill_level( skill_dodge );
         if( skill_1 > rng( -2, 8 ) ) {
             popup( _( "Alerted by a rustle, %s fled to the safety of the outpost!" ), comp->get_name() );
         } else if( skill_2 > rng( -2, 8 ) ) {
             popup( _( "As soon as the cougar sprang, %s darted to the safety of the outpost!" ),
                    comp->get_name() );
         } else {
             popup( _( "%s was caught unaware and was forced to fight the creature at close "
                       "range!" ), comp->get_name() );
             int skill = scavenging_combat_skill( *comp, 0, false );
             int monsters = rng( 0, 10 );
             if( skill * rng_float( .80, 1.2 ) > monsters * rng_float( .8, 1.2 ) ) {
                 if( one_in( 2 ) ) {
                     popup( _( "%s was able to scare off the bear after delivering a nasty "
                               "blow!" ), comp->get_name() );
                 } else {
                     popup( _( "%s beat the cougar into a bloody pulp!" ), comp->get_name() );
                 }
             } else {
                 if( one_in( 2 ) ) {
                     popup( _( "%s was able to hold off the first wolf, but the others that were "
                               "skulking in the tree line caught up" ), comp->get_name() );
                     popup( _( "I'm sorry, there wasn't anything we could do" ) );
                 } else {
                     popup( _( "We we don't know what exactly happened, but we found %s's gear "
                               "ripped and bloody" ), comp->get_name() );
                     popup( _( "I fear your companion won't be returning." ) );
                 }
                 overmap_buffer.remove_npc( comp->getID() );
                 return false;
             }
         }
     }
     Character &player_character = get_player_character();
     float hours = to_hours<float>( calendar::turn - comp->companion_mission_time );
     int merch_amount = 4 * hours;
     companion_skill_trainer( *comp, "gathering", calendar::turn -
                              comp->companion_mission_time, 2 );
     popup( _( "%s returns from working as a forager having earned %d merch and a bit of "
               "experience" ), comp->get_name(), merch_amount );
     item merch = item( itype_FMCNote );
     player_character.i_add_or_drop( merch, merch_amount );
     // the following doxygen aliases do not yet exist. this is marked for future reference
     ///\EFFECT_SURVIVAL_NPC affects forage mission results
     float skill = comp->get_skill_level( skill_survival );
     if( skill > rng_float( -.5, 8 ) ) {
         item_group_id itemlist = Item_spawn_data_farming_seeds;
         if( one_in( 2 ) ) {
             switch( season_of_year( calendar::turn ) ) {
                 case SPRING:
                     itemlist = Item_spawn_data_forage_spring;
                     break;
                 case SUMMER:
                     itemlist = Item_spawn_data_forage_summer;
                     break;
                 case AUTUMN:
                     itemlist = Item_spawn_data_forage_autumn;
                     break;
                 case WINTER:
                     itemlist = Item_spawn_data_forage_winter;
                     break;
                 default:
                     debugmsg( "Invalid season" );
             }
         }
         item result = item_group::item_from( itemlist );
         if( !result.is_null() ) {
             popup( _( "%s returned with a %s for you!" ), comp->get_name(), result.tname() );
             player_character.i_add_or_drop( result );
         }
         if( one_in( 6 ) && !p.has_trait( trait_NPC_MISSION_LEV_1 ) ) {
             p.set_mutation( trait_NPC_MISSION_LEV_1 );
             popup( _( "%s feels more confident in your companions and is willing to let them "
                       "participate in advanced tasks." ), p.get_name() );
         }
     }
     companion_return( *comp );
     return true;
 }
References _, AUTUMN, companion_choose_return(), companion_return(), companion_skill_trainer(), debugmsg, Forage_Job, Character::get_name(), get_player_character(), Character::has_trait(), Character::i_add_or_drop(), item::is_null(), item_group::item_from(), Item_spawn_data_farming_seeds, Item_spawn_data_forage_autumn, Item_spawn_data_forage_spring, Item_spawn_data_forage_summer, Item_spawn_data_forage_winter, itype_FMCNote, one_in(), overmap_buffer, popup(), overmapbuffer::remove_npc(), rng(), rng_float(), scavenging_combat_skill(), season_of_year(), Character::set_mutation(), skill_dodge, skill_survival, SPRING, SUMMER, item::tname(), trait_NPC_MISSION_LEV_1, calendar::turn, and WINTER.
Referenced by handle_outpost_mission().
force_on_force() [1/2]
void talk_function::force_on_force (const comp_list & defender, const std::string & def_desc, const comp_list & attacker, const std::string & att_desc, int advantage)
Referenced by caravan_return().
force_on_force() [2/2]
bool talk_function::force_on_force (const comp_list & defender, const std::string & def_desc, const std::vector< monster * > & monsters_fighting, const std::string & att_desc, int advantage)
give_aid()
void talk_function::give_aid (npc & p)
Definition at line 684 of file npctalk_funcs.cpp.
 {
     Character &player_character = get_player_character();
     for( const bodypart_id &bp :
          player_character.get_all_body_parts( get_body_part_flags::only_main ) ) {
         player_character.heal( bp, 5 * rng( 2, 5 ) );
         if( player_character.has_effect( effect_bite, bp.id() ) ) {
             player_character.remove_effect( effect_bite, bp );
         }
         if( player_character.has_effect( effect_bleed, bp.id() ) ) {
             player_character.remove_effect( effect_bleed, bp );
         }
         if( player_character.has_effect( effect_infected, bp.id() ) ) {
             player_character.remove_effect( effect_infected, bp );
         }
     }
     const int moves = to_moves<int>( 30_minutes );
     player_character.assign_activity( ACT_WAIT_NPC, moves );
     player_character.activity.str_values.push_back( p.get_name() );
     p.add_effect( effect_currently_busy, 120_minutes );
 }
References ACT_WAIT_NPC, Character::activity, Creature::add_effect(), Character::assign_activity(), bp, effect_bite, effect_bleed, effect_currently_busy, effect_infected, Creature::get_all_body_parts(), Character::get_name(), get_player_character(), Creature::has_effect(), Character::heal(), int_id< T >::id(), only_main, Creature::remove_effect(), rng(), and player_activity::str_values.
Referenced by give_all_aid(), and talk_effect_t::parse_string_effect().
give_all_aid()
void talk_function::give_all_aid (npc & p)
Definition at line 707 of file npctalk_funcs.cpp.
 {
     give_aid( p ); // Provide aid to the player first
     Character &player_character = get_player_character();
     for( npc &guy : g->all_npcs() ) {
         if( guy.is_walking_with() && rl_dist( guy.pos(), player_character.pos() ) < PICKUP_RANGE ) {
             for( const bodypart_id &bp :
                  guy.get_all_body_parts( get_body_part_flags::only_main ) ) {
                 guy.heal( bp, 5 * rng( 2, 5 ) );
                 if( guy.has_effect( effect_bite, bp.id() ) ) {
                     guy.remove_effect( effect_bite, bp );
                 }
                 if( guy.has_effect( effect_bleed, bp.id() ) ) {
                     guy.remove_effect( effect_bleed, bp );
                 }
                 if( guy.has_effect( effect_infected, bp.id() ) ) {
                     guy.remove_effect( effect_infected, bp );
                 }
             }
         }
     }
     const int moves = to_moves<int>( 60_minutes );
     player_character.assign_activity( ACT_WAIT_NPC, moves );
     player_character.activity.str_values.push_back( p.get_name() );
     p.add_effect( effect_currently_busy, 240_minutes );
 }
References ACT_WAIT_NPC, Character::activity, Creature::add_effect(), Character::assign_activity(), bp, effect_bite, effect_bleed, effect_currently_busy, effect_infected, g, Character::get_name(), get_player_character(), give_aid(), int_id< T >::id(), only_main, PICKUP_RANGE, Creature::pos(), rl_dist(), rng(), and player_activity::str_values.
Referenced by talk_effect_t::parse_string_effect().
give_equipment()
void talk_function::give_equipment (npc & p)
Definition at line 607 of file npctalk_funcs.cpp.
 {
     give_equipment_allowance( p, 0 );
 }
References give_equipment_allowance().
Referenced by talk_effect_t::parse_string_effect().
give_equipment_allowance()
void talk_function::give_equipment_allowance (npc & p, int allowance)
Definition at line 612 of file npctalk_funcs.cpp.
 {
     std::vector<item_pricing> giving = npc_trading::init_selling( p );
     int chosen = -1;
     while( chosen == -1 && !giving.empty() ) {
         int index = rng( 0, giving.size() - 1 );
         if( giving[index].price < p.op_of_u.owed + allowance ) {
             chosen = index;
         } else {
             giving.erase( giving.begin() + index );
         }
     }
     if( giving.empty() ) {
         popup( _( "%s has nothing to give!" ), p.get_name() );
         return;
     }
     if( chosen < 0 || static_cast<size_t>( chosen ) >= giving.size() ) {
         debugmsg( "Chosen index is outside of available item range!" );
         chosen = 0;
     }
     item it = *giving[chosen].loc.get_item();
     giving[chosen].loc.remove_item();
     popup( _( "%1$s gives you a %2$s" ), p.get_name(), it.tname() );
     Character &player_character = get_player_character();
     it.set_owner( player_character );
     player_character.i_add( it );
     allowance -= giving[chosen].price;
     if( allowance < 0 ) {
         p.op_of_u.owed += allowance;
     }
     p.add_effect( effect_asked_for_item, 3_hours );
 }
References _, Creature::add_effect(), debugmsg, effect_asked_for_item, Character::get_name(), get_player_character(), Character::i_add(), npc_trading::init_selling(), npc::op_of_u, npc_opinion::owed, popup(), itype::price, visitable::remove_item(), rng(), item::set_owner(), and item::tname().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_equipment(), and give_equipment().
goto_location()
void talk_function::goto_location (npc & p)
Definition at line 349 of file npctalk_funcs.cpp.
 {
     int i = 0;
     uilist selection_menu;
     selection_menu.text = _( "Select a destination" );
     std::vector<basecamp *> camps;
     tripoint_abs_omt destination;
     Character &player_character = get_player_character();
     for( auto elem : player_character.camps ) {
         if( elem == p.global_omt_location() ) {
             continue;
         }
         std::optional<basecamp *> camp = overmap_buffer.find_camp( elem.xy() );
         if( !camp ) {
             continue;
         }
         basecamp *temp_camp = *camp;
         camps.push_back( temp_camp );
     }
     for( const basecamp *iter : camps ) {
         //~ %1$s: camp name, %2$d and %3$d: coordinates
         selection_menu.addentry( i++, true, MENU_AUTOASSIGN, pgettext( "camp", "%1$s at %2$s" ),
                                  iter->camp_name(), iter->camp_omt_pos().to_string() );
     }
     selection_menu.addentry( i++, true, MENU_AUTOASSIGN, _( "My current location" ) );
     selection_menu.addentry( i, true, MENU_AUTOASSIGN, _( "Cancel" ) );
     selection_menu.selected = 0;
     selection_menu.query();
     int index = selection_menu.ret;
     if( index < 0 || index > static_cast<int>( camps.size() + 1 ) ||
         index == static_cast<int>( camps.size() + 1 ) ) {
         return;
     }
     if( index == static_cast<int>( camps.size() ) ) {
         destination = player_character.global_omt_location();
     } else {
         const basecamp *selected_camp = camps[index];
         destination = selected_camp->camp_omt_pos();
     }
     p.goal = destination;
     p.omt_path = overmap_buffer.get_travel_path( p.global_omt_location(), p.goal,
                  overmap_path_params::for_npc() );
     if( destination == tripoint_abs_omt() || destination == overmap::invalid_tripoint ||
         p.omt_path.empty() ) {
         p.goal = npc::no_goal_point;
         p.omt_path.clear();
         add_msg( m_info, _( "That is not a valid destination for %s." ), p.disp_name() );
         return;
     }
     p.set_mission( NPC_MISSION_TRAVELLING );
     p.chatbin.first_topic = p.chatbin.talk_friend_guard;
     p.guard_pos = std::nullopt;
     p.set_attitude( NPCATT_NULL );
 }
References _, add_msg(), uilist::addentry(), basecamp::camp_omt_pos(), Character::camps, npc::chatbin, Character::disp_name(), overmapbuffer::find_camp(), dialogue_chatbin::first_topic, overmap_path_params::for_npc(), get_player_character(), overmapbuffer::get_travel_path(), Creature::global_omt_location(), npc::goal, npc::guard_pos, overmap::invalid_tripoint, m_info, MENU_AUTOASSIGN, npc::no_goal_point, NPC_MISSION_TRAVELLING, NPCATT_NULL, Character::omt_path, overmap_buffer, pgettext, uilist::query(), uilist::ret, uilist::selected, npc::set_attitude(), npc::set_mission(), dialogue_chatbin::talk_friend_guard, and uilist::text.
Referenced by talk_effect_t::parse_string_effect().
handle_outpost_mission()
bool talk_function::handle_outpost_mission (const mission_entry & cur_key, npc & p) static
Definition at line 1184 of file mission_companion.cpp.
 {
     switch( cur_key.id.id.id ) {
         case Scavenging_Patrol_Job:
             if( cur_key.id.ret ) {
                 scavenging_patrol_return( p );
             } else {
                 individual_mission( p, _( "departs on the scavenging patrol" ), cur_key.id.id );
             }
             break;
         case Scavenging_Raid_Job:
             if( cur_key.id.ret ) {
                 scavenging_raid_return( p );
             } else {
                 individual_mission( p, _( "departs on the scavenging raid" ), cur_key.id.id );
             }
             break;
         case Hospital_Raid_Job:
             if( cur_key.id.ret ) {
                 hospital_raid_return( p );
             } else {
                 npc_ptr npc = individual_mission( p, _( "departs on the hospital raid" ), cur_key.id.id );
                 if( npc != nullptr ) {
                     get_player_character().set_value( var_SCAVENGER_HOSPITAL_RAID_STARTED, "yes" );
                 }
             }
             break;
         case Menial_Job:
             if( cur_key.id.ret ) {
                 labor_return( p );
             } else {
                 individual_mission( p, _( "departs to work as a laborer" ), cur_key.id.id );
             }
             break;
         case Carpentry_Job:
             if( cur_key.id.ret ) {
                 carpenter_return( p );
             } else {
                 individual_mission( p, _( "departs to work as a carpenter" ), cur_key.id.id );
             }
             break;
         case Forage_Job:
             if( cur_key.id.ret ) {
                 forage_return( p );
             } else {
                 individual_mission( p, _( "departs to forage for food" ), cur_key.id.id );
             }
             break;
         case Caravan_Commune_Center_Job:
             if( cur_key.id.ret ) {
                 caravan_return( p, omt_evac_center_18, cur_key.id.id );
             } else if( cur_key.id.id.parameters == caravan_commune_center_job_assign_parameter ) {
                 individual_mission( p, _( "joins the caravan team" ), cur_key.id.id, true );
             } else if( cur_key.id.id.parameters == caravan_commune_center_job_active_parameter ) {
                 caravan_depart( p, omt_evac_center_18, cur_key.id.id );
             } else {
                 debugmsg( "Unrecognized caravan mission id parameter encountered: '%s'", cur_key.id.id.parameters );
             }
             break;
         case No_Mission:
             return false;
         case Camp_Distribute_Food:
         case Camp_Determine_Leadership:
         case Camp_Have_Meal:
         case Camp_Hide_Mission:
         case Camp_Reveal_Mission:
         case Camp_Assign_Jobs:
         case Camp_Assign_Workers:
         case Camp_Abandon:
         case Camp_Upgrade:
         case Camp_Emergency_Recall:
         case Camp_Crafting:
         case Camp_Gather_Materials:
         case Camp_Collect_Firewood:
         case Camp_Menial:
         case Camp_Survey_Field:
         case Camp_Survey_Expansion:
         case Camp_Cut_Logs:
         case Camp_Clearcut:
         case Camp_Setup_Hide_Site:
         case Camp_Relay_Hide_Site:
         case Camp_Foraging:
         case Camp_Trapping:
         case Camp_Hunting:
         case Camp_OM_Fortifications:
         case Camp_Recruiting:
         case Camp_Scouting:
         case Camp_Combat_Patrol:
         case Camp_Chop_Shop:
         case Camp_Plow:
         case Camp_Plant:
         case Camp_Harvest:
             debugmsg( "Non outpost mission encountered in outpost mission handling: '%s'",
                       miss_info [cur_key.id.id.id].serialize_id );
             return false;
         default:
             debugmsg( "Unrecognized mission id encountered in outpost mission handling: '%d'",
                       cur_key.id.id.id );
             return false;
     }
     return true;
 }
References _, Camp_Abandon, Camp_Assign_Jobs, Camp_Assign_Workers, Camp_Chop_Shop, Camp_Clearcut, Camp_Collect_Firewood, Camp_Combat_Patrol, Camp_Crafting, Camp_Cut_Logs, Camp_Determine_Leadership, Camp_Distribute_Food, Camp_Emergency_Recall, Camp_Foraging, Camp_Gather_Materials, Camp_Harvest, Camp_Have_Meal, Camp_Hide_Mission, Camp_Hunting, Camp_Menial, Camp_OM_Fortifications, Camp_Plant, Camp_Plow, Camp_Recruiting, Camp_Relay_Hide_Site, Camp_Reveal_Mission, Camp_Scouting, Camp_Setup_Hide_Site, Camp_Survey_Expansion, Camp_Survey_Field, Camp_Trapping, Camp_Upgrade, Caravan_Commune_Center_Job, caravan_commune_center_job_active_parameter, caravan_commune_center_job_assign_parameter, caravan_depart(), caravan_return(), carpenter_return(), Carpentry_Job, debugmsg, Forage_Job, forage_return(), get_player_character(), Hospital_Raid_Job, hospital_raid_return(), mission_id::id, ui_mission_id::id, mission_entry::id, individual_mission(), labor_return(), Menial_Job, miss_info, No_Mission, omt_evac_center_18, mission_id::parameters, ui_mission_id::ret, Scavenging_Patrol_Job, scavenging_patrol_return(), Scavenging_Raid_Job, scavenging_raid_return(), Creature::set_value(), and var_SCAVENGER_HOSPITAL_RAID_STARTED.
Referenced by companion_mission().
hospital_raid()
void talk_function::hospital_raid (mission_data & mission_key, npc & p) static
Definition at line 706 of file mission_companion.cpp.
 {
     const mission_id miss_id = {Hospital_Raid_Job, "", {}, std::nullopt};
     if( get_player_character().get_value( var_SCAVENGER_HOSPITAL_RAID_STARTED ) != "yes" ) {
         const std::string entry_assign =
             _( "Profit: hospital equipment, some items\nDanger: High\nTime: 20 hour mission\n\n"
                "Scavenging raid targeting a hospital to search for hospital equipment and as many "
                "valuable items as possible before being surrounded by the undead.  "
                "Combat is to be expected and assistance from the rest of the party "
                "can't be guaranteed.  This will be an extremely dangerous mission, "
                "so make sure everyone is prepared before they go." );
         mission_key.add_start( miss_id, _( "Assign Hospital Raid" ), entry_assign );
     }
     std::vector<npc_ptr> npc_list = companion_list( p, miss_id );
     if( !npc_list.empty() ) {
         std::string entry_return = _( "Profit: hospital materials\nDanger: High\nTime: 20 hour missions\n\n"
                                       "Raid Roster:\n" );
         bool avail = false;
         for( auto &elem : npc_list ) {
             const bool done = calendar::turn >= elem->companion_mission_time + 20_hours;
             avail |= done;
             if( done ) {
                 entry_return += "  " + elem->get_name() + _( " [DONE]\n" );
             } else {
                 entry_return += "  " + elem->get_name() + " [" + std::to_string( to_hours<int>( calendar::turn -
                                 elem->companion_mission_time ) ) + _( " hours / 20 hours]\n" );
             }
         }
         if( avail ) {
             entry_return += _( return_ally_question_string );
         }
         mission_key.add_return( miss_id, _( "Retrieve Hospital Raid" ), entry_return, avail );
     }
 }
References _, mission_data::add_return(), mission_data::add_start(), companion_list(), get_player_character(), Hospital_Raid_Job, return_ally_question_string, to_string(), calendar::turn, and var_SCAVENGER_HOSPITAL_RAID_STARTED.
Referenced by companion_mission().
hospital_raid_return()
bool talk_function::hospital_raid_return (npc & p)
Definition at line 1952 of file mission_companion.cpp.
 {
     npc_ptr comp = companion_choose_return( p, { Hospital_Raid_Job, "", {}, std::nullopt},
                                             calendar::turn - 20_hours );
     if( comp == nullptr ) {
         return false;
     }
     int experience = rng( 20, 40 );
     if( one_in( 2 ) ) {
         popup( _( "While scavenging, %s's party suddenly found itself set upon by a large mob of "
                   "undead" ), comp->get_name() );
         int skill = scavenging_combat_skill( *comp, 4, true );
         if( one_in( 10 ) ) {
             popup( _( "Through quick thinking the group was able to evade combat!" ) );
         } else {
             popup( _( "Combat took place in close quarters, focusing on melee skills" ) );
             int monsters = rng( 12, 30 );
             if( skill * rng_float( .60, 1.4 ) > ( .35 * monsters * rng_float( .6, 1.4 ) ) ) {
                 popup( _( "Through brute force the party smashed through the group of %d "
                           "undead!" ), monsters );
                 experience += rng( 2, 10 );
             } else {
                 popup( _( "Unfortunately they were overpowered by the undead  I'm sorry." ) );
                 overmap_buffer.remove_npc( comp->getID() );
                 // Let the player retry if everybody dies
                 get_player_character().set_value( var_SCAVENGER_HOSPITAL_RAID_STARTED, "no" );
                 return false;
             }
         }
     }
     Character &player_character = get_player_character();
     tripoint_abs_omt loot_location = player_character.global_omt_location();
     std::set<item> all_returned_items;
     for( int i = 0; i < rng( 2, 3 ); i++ ) {
         tripoint_abs_omt site = overmap_buffer.find_closest(
                                     loot_location, "hospital", 0, false, ot_match_type::prefix );
         if( site == overmap::invalid_tripoint ) {
             debugmsg( "No hospitals found." );
         } else {
             // Search the entire height of the hospital, including the roof
             for( int z = 0; z <= OVERMAP_HEIGHT; z++ ) {
                 site.z() = z;
                 const oter_id &omt_ref = overmap_buffer.ter( site );
                 // We're past the roof, so we can stop
                 if( omt_ref == oter_open_air ) {
                     break;
                 }
                 const std::string om_cur = omt_ref.id().c_str();
                 oter_str_id looted_replacement = oter_looted_hospital;
                 if( om_cur.find( "_roof" ) != std::string::npos ) {
                     looted_replacement = oter_looted_hospital_roof;
                 }
                 overmap_buffer.reveal( site, 2 );
                 std::set<item> returned_items = loot_building( site, looted_replacement );
                 all_returned_items.insert( returned_items.begin(), returned_items.end() );
             }
         }
     }
     companion_skill_trainer( *comp, "combat", experience * 10_minutes, 10 );
     popup( _( "%s returns from the raid having a fair bit of experience" ),
            comp->get_name() );
     if( one_in( 2 ) ) {
         item_group_id itemlist( "npc_misc" );
         if( one_in( 8 ) ) {
             itemlist = Item_spawn_data_npc_weapon_random;
         }
         item result = item_group::item_from( itemlist );
         if( !result.is_null() ) {
             popup( _( "%s returned with a %s for you!" ), comp->get_name(), result.tname() );
             player_character.i_add_or_drop( result );
         }
     }
     std::list<item> to_distribute;
     for( item i : all_returned_items ) {
         // One time mission, so the loot gets split evenly
         if( one_in( 2 ) ) {
             player_character.i_drop_at( i );
         } else {
             i.set_owner( p );
             to_distribute.push_back( i );
         }
     }
     distribute_items_to_npc_zones( to_distribute, p );
     player_character.set_value( var_DOCTOR_ANESTHETIC_SCAVENGERS_HELPED, "yes" );
     player_character.set_value( var_SCAVENGER_HOSPITAL_RAID, "no" );
     popup( _( "%s returned with some medical equipment that should help the doctor!" ),
            comp->get_name() );
     companion_return( *comp );
     return true;
 }
References _, string_id< T >::c_str(), companion_choose_return(), companion_return(), companion_skill_trainer(), debugmsg, distribute_items_to_npc_zones(), overmapbuffer::find_closest(), get_player_character(), Creature::global_omt_location(), Hospital_Raid_Job, Character::i_add_or_drop(), Character::i_drop_at(), int_id< T >::id(), overmap::invalid_tripoint, item::is_null(), item_group::item_from(), Item_spawn_data_npc_weapon_random, loot_building(), one_in(), oter_looted_hospital, oter_looted_hospital_roof, oter_open_air, overmap_buffer, OVERMAP_HEIGHT, popup(), prefix, overmapbuffer::remove_npc(), overmapbuffer::reveal(), rng(), rng_float(), scavenging_combat_skill(), Creature::set_value(), overmapbuffer::ter(), item::tname(), calendar::turn, var_DOCTOR_ANESTHETIC_SCAVENGERS_HELPED, var_SCAVENGER_HOSPITAL_RAID, var_SCAVENGER_HOSPITAL_RAID_STARTED, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by handle_outpost_mission().
hostile()
void talk_function::hostile (npc & p)
Definition at line 898 of file npctalk_funcs.cpp.
 {
     if( p.get_attitude() == NPCATT_KILL ) {
         return;
     }
     if( p.sees( get_player_character() ) ) {
         add_msg( _( "%s turns hostile!" ), p.get_name() );
     }
     get_event_bus().send<event_type::npc_becomes_hostile>( p.getID(), p.name );
     p.set_attitude( NPCATT_KILL );
 }
References _, add_msg(), npc::get_attitude(), get_event_bus(), Character::get_name(), get_player_character(), Character::getID(), Character::name, npc_becomes_hostile, NPCATT_KILL, Character::sees(), event_bus::send(), and npc::set_attitude().
Referenced by talk_effect_t::set_effect().
individual_mission() [1/2]
npc_ptr talk_function::individual_mission (const tripoint_abs_omt & omt_pos, const std::string & role_id, const std::string & desc, const mission_id & miss_id, bool group = false, const std::vector< item * > & equipment = {}, const std::map< skill_id, int > & required_skills = {}, bool silent_failure = false)
Definition at line 1306 of file mission_companion.cpp.
 {
     npc_ptr comp = companion_choose( required_skills, silent_failure );
     if( comp == nullptr ) {
         return comp;
     }
     // make sure, for now, that NPCs dismount their horse before going on a mission.
     if( comp->has_effect( effect_riding ) ) {
         comp->npc_dismount();
     }
     //Ensure we have someone to give equipment to before we lose it
     for( item *i : equipment ) {
         comp->companion_mission_inv.add_item( *i );
         if( item::count_by_charges( i->typeId() ) ) {
             comp->as_character()->use_charges( i->typeId(), i->charges );
         } else {
             comp->as_character()->use_amount( i->typeId(), 1 );
         }
     }
     if( comp->in_vehicle ) {
         get_map().unboard_vehicle( comp->pos() );
     }
     popup( "%s %s", comp->get_name(), desc );
     comp->set_companion_mission( omt_pos, role_id, miss_id );
     if( group ) {
         comp->companion_mission_time = calendar::before_time_starts;
     } else {
         comp->companion_mission_time = calendar::turn;
     }
     g->reload_npcs();
     g->validate_npc_followers();
     cata_assert( !comp->is_active() );
     return comp;
 }
References calendar::before_time_starts, cata_assert, companion_choose(), item::count_by_charges(), effect_riding, g, get_map(), popup(), calendar::turn, and map::unboard_vehicle().
individual_mission() [2/2]
npc_ptr talk_function::individual_mission (npc & p, const std::string & desc, const mission_id & miss_id, bool group = false, const std::vector< item * > & equipment = {}, const std::map< skill_id, int > & required_skills = {}, bool silent_failure = false)
Send a companion on an individual mission or attaches them to a group to depart later Set submap_coords and pos.
Parameters
desc is the description in the popup window
id is the value stored with the NPC when it is offloaded
group is whether the NPC is waiting for additional members before departing together
equipment is placed in the NPC's special inventory and dropped when they return
silent_failure is used to add an additional companion to a mission. Send a companion on an individual mission or attaches them to a group to depart later
Definition at line 1298 of file mission_companion.cpp.
 {
     const tripoint_abs_omt omt_pos = p.global_omt_location();
     return individual_mission( omt_pos, p.companion_mission_role_id, desc, miss_id, group,
                                equipment, required_skills, silent_failure );
 }
References npc::companion_mission_role_id, and Creature::global_omt_location().
Referenced by handle_outpost_mission(), basecamp::start_mission(), and basecamp::start_multi_mission().
insult_combat()
void talk_function::insult_combat (npc & p)
Definition at line 496 of file npctalk_funcs.cpp.
 {
     add_msg( _( "You start a fight with %s!" ), p.get_name() );
     p.chatbin.first_topic = "TALK_DONE";
     p.set_attitude( NPCATT_KILL );
 }
References _, add_msg(), npc::chatbin, dialogue_chatbin::first_topic, Character::get_name(), NPCATT_KILL, and npc::set_attitude().
Referenced by talk_effect_t::parse_string_effect().
labor_return()
bool talk_function::labor_return (npc & p)
Definition at line 2053 of file mission_companion.cpp.
 {
     npc_ptr comp = companion_choose_return( p, { Menial_Job, "", {}, std::nullopt}, calendar::turn -
                                             1_hours );
     if( comp == nullptr ) {
         return false;
     }
     float hours = to_hours<float>( calendar::turn - comp->companion_mission_time );
     int merch_amount = 3 * hours;
     companion_skill_trainer( *comp, "menial", calendar::turn - comp->companion_mission_time, 1 );
     popup( _( "%s returns from working as a laborer having earned %d merch and a bit of experience" ),
            comp->get_name(), merch_amount );
     companion_return( *comp );
     if( hours >= 8 && one_in( 8 ) && !p.has_trait( trait_NPC_MISSION_LEV_1 ) ) {
         p.set_mutation( trait_NPC_MISSION_LEV_1 );
         popup( _( "%s feels more confident in your companions and is willing to let them "
                   "participate in advanced tasks." ), p.get_name() );
     }
     item merch = item( itype_FMCNote );
     get_player_character().i_add_or_drop( merch, merch_amount );
     return true;
 }
References _, companion_choose_return(), companion_return(), companion_skill_trainer(), Character::get_name(), get_player_character(), Character::has_trait(), Character::i_add_or_drop(), itype_FMCNote, Menial_Job, one_in(), popup(), Character::set_mutation(), trait_NPC_MISSION_LEV_1, and calendar::turn.
Referenced by handle_outpost_mission().
lead_to_safety()
void talk_function::lead_to_safety (npc & p)
Definition at line 1053 of file npctalk_funcs.cpp.
 {
     mission *reach_safety_mission = mission::reserve_new( mission_MISSION_REACH_SAFETY,
                                     character_id() );
     reach_safety_mission->assign( get_avatar() );
     p.goal = reach_safety_mission->get_target();
     p.set_attitude( NPCATT_LEAD );
 }
References mission::assign(), character_id, get_avatar(), mission::get_target(), npc::goal, mission_MISSION_REACH_SAFETY, NPCATT_LEAD, mission::reserve_new(), and npc::set_attitude().
Referenced by talk_effect_t::parse_string_effect().
leave()
void talk_function::leave (npc & p)
Definition at line 918 of file npctalk_funcs.cpp.
 {
     add_msg( _( "%s leaves." ), p.get_name() );
     g->remove_npc_follower( p.getID() );
     std::string new_fac_id = "solo_";
     new_fac_id += p.name;
     p.job.clear_all_priorities();
     // create a new "lone wolf" faction for this one NPC
     faction *new_solo_fac = g->faction_manager_ptr->add_new_faction( p.name,
                             faction_id( new_fac_id ), faction_no_faction );
     p.set_fac( new_solo_fac ? new_solo_fac->id : faction_no_faction );
     if( new_solo_fac ) {
         new_solo_fac->known_by_u = true;
     }
     p.chatbin.first_topic = p.chatbin.talk_stranger_neutral;
     p.set_attitude( NPCATT_NULL );
     p.mission = NPC_MISSION_NULL;
     p.long_term_goal_action();
 }
References _, add_msg(), npc::chatbin, job_data::clear_all_priorities(), faction_no_faction, dialogue_chatbin::first_topic, g, Character::get_name(), Character::getID(), faction_template::id, npc::job, faction_template::known_by_u, npc::long_term_goal_action(), npc::mission, Character::name, NPC_MISSION_NULL, NPCATT_NULL, npc::set_attitude(), npc::set_fac(), and dialogue_chatbin::talk_stranger_neutral.
Referenced by talk_effect_t::parse_string_effect().
lesser_give_aid()
void talk_function::lesser_give_aid (npc & p)
Definition at line 645 of file npctalk_funcs.cpp.
 {
     Character &player_character = get_player_character();
     for( const bodypart_id &bp :
          player_character.get_all_body_parts( get_body_part_flags::only_main ) ) {
         player_character.heal( bp, rng( 5, 15 ) );
         if( player_character.has_effect( effect_bleed, bp.id() ) ) {
             player_character.remove_effect( effect_bleed, bp );
         }
     }
     const int moves = to_moves<int>( 15_minutes );
     player_character.assign_activity( ACT_WAIT_NPC, moves );
     player_character.activity.str_values.push_back( p.get_name() );
     p.add_effect( effect_currently_busy, 60_minutes );
 }
References ACT_WAIT_NPC, Character::activity, Creature::add_effect(), Character::assign_activity(), bp, effect_bleed, effect_currently_busy, Creature::get_all_body_parts(), Character::get_name(), get_player_character(), Creature::has_effect(), Character::heal(), int_id< T >::id(), only_main, Creature::remove_effect(), rng(), and player_activity::str_values.
Referenced by lesser_give_all_aid(), and talk_effect_t::parse_string_effect().
lesser_give_all_aid()
void talk_function::lesser_give_all_aid (npc & p)
Definition at line 661 of file npctalk_funcs.cpp.
 {
     lesser_give_aid( p ); // Provide lesser aid to the player first
     Character &player_character = get_player_character();
     for( npc &guy : g->all_npcs() ) {
         if( guy.is_walking_with() && rl_dist( guy.pos(), player_character.pos() ) < PICKUP_RANGE ) {
             for( const bodypart_id &bp :
                  guy.get_all_body_parts( get_body_part_flags::only_main ) ) {
                 guy.heal( bp, rng( 5, 15 ) );
                 if( guy.has_effect( effect_bleed, bp.id() ) ) {
                     guy.remove_effect( effect_bleed, bp );
                 }
             }
         }
     }
     const int moves = to_moves<int>( 30_minutes );
     player_character.assign_activity( ACT_WAIT_NPC, moves );
     player_character.activity.str_values.push_back( p.get_name() );
     p.add_effect( effect_currently_busy, 120_minutes );
 }
References ACT_WAIT_NPC, Character::activity, Creature::add_effect(), Character::assign_activity(), bp, effect_bleed, effect_currently_busy, g, Character::get_name(), get_player_character(), int_id< T >::id(), lesser_give_aid(), only_main, PICKUP_RANGE, Creature::pos(), rl_dist(), rng(), and player_activity::str_values.
Referenced by talk_effect_t::parse_string_effect().
loot_building()
std::set< item > talk_function::loot_building (const tripoint_abs_omt & site, const oter_str_id & looted_replacement)
Definition at line 2803 of file mission_companion.cpp.
 {
     tinymap bay;
     bay.load( site, false );
     creature_tracker &creatures = get_creature_tracker();
     std::set<item> return_items;
     for( const tripoint &p : bay.points_on_zlevel() ) {
         const ter_id t = bay.ter( p );
         //Open all the doors, doesn't need to be exhaustive
         const std::unordered_set<ter_str_id> openable_doors = {ter_t_door_c, ter_t_door_c_peep, ter_t_door_b, ter_t_door_boarded, ter_t_door_boarded_damaged, ter_t_rdoor_boarded, ter_t_rdoor_boarded_damaged, ter_t_door_boarded_peep, ter_t_door_boarded_damaged_peep };
         if( openable_doors.find( t.id() ) != openable_doors.end() ) {
             bay.ter_set( p, ter_t_door_o );
         } else if( t == ter_t_door_locked || t == ter_t_door_locked_peep || t == ter_t_door_locked_alarm ) {
             const map_bash_info &bash = bay.ter( p ).obj().bash;
             bay.ter_set( p, bash.ter_set );
             // Bash doors twice
             const map_bash_info &bash_again = bay.ter( p ).obj().bash;
             bay.ter_set( p, bash_again.ter_set );
             bay.spawn_items( p, item_group::items_from( bash.drop_group, calendar::turn ) );
             bay.spawn_items( p, item_group::items_from( bash_again.drop_group, calendar::turn ) );
         } else if( t == ter_t_door_metal_c || t == ter_t_door_metal_locked ||
                    t == ter_t_door_metal_pickable ) {
             bay.ter_set( p, ter_t_door_metal_o );
         } else if( t == ter_t_door_glass_c ) {
             bay.ter_set( p, ter_t_door_glass_o );
         } else if( t == ter_t_wall && one_in( 25 ) ) {
             const map_bash_info &bash = bay.ter( p ).obj().bash;
             bay.ter_set( p, bash.ter_set );
             bay.spawn_items( p, item_group::items_from( bash.drop_group, calendar::turn ) );
             bay.collapse_at( p, false );
         }
         //Smash easily breakable stuff
         else if( const std::unordered_set<ter_str_id> weak_window_ters = {ter_t_window, ter_t_window_taped, ter_t_window_domestic, ter_t_window_boarded_noglass, ter_t_window_domestic_taped, ter_t_window_alarm_taped, ter_t_window_boarded, ter_t_curtains, ter_t_window_alarm, ter_t_window_no_curtains, ter_t_window_no_curtains_taped };
                  weak_window_ters.find( t.id() ) != weak_window_ters.end() && one_in( 4 ) ) {
             const map_bash_info &bash = bay.ter( p ).obj().bash;
             bay.ter_set( p, bash.ter_set );
             bay.spawn_items( p, item_group::items_from( bash.drop_group, calendar::turn ) );
         } else if( ( t == ter_t_wall_glass || t == ter_t_wall_glass_alarm ) && one_in( 3 ) ) {
             const map_bash_info &bash = bay.ter( p ).obj().bash;
             bay.ter_set( p, bash.ter_set );
             bay.spawn_items( p, item_group::items_from( bash.drop_group, calendar::turn ) );
         } else if( bay.has_furn( p ) && bay.furn( p ).obj().bash.str_max != -1 && one_in( 10 ) ) {
             const map_bash_info &bash = bay.furn( p ).obj().bash;
             bay.furn_set( p, bash.furn_set );
             bay.delete_signage( p );
             bay.spawn_items( p, item_group::items_from( bash.drop_group, calendar::turn ) );
         }
         //Kill zombies!  Only works against pre-spawned enemies at the moment...
         Creature *critter = creatures.creature_at( p );
         if( critter != nullptr ) {
             critter->die( nullptr );
         }
         //Hoover up tasty items!
         map_stack items = bay.i_at( p );
         for( map_stack::iterator it = items.begin(); it != items.end(); ) {
             if( !it->made_of( phase_id::LIQUID ) &&
                 ( ( ( it->is_food() || it->is_food_container() ) && !one_in( 8 ) ) ||
                   ( it->price( true ) > 1000 && !one_in( 4 ) ) || one_in( 5 ) ) ) {
                 return_items.insert( *it );
                 it = items.erase( it );
             } else {
                 ++it;
             }
         }
     }
     bay.save();
     overmap_buffer.ter_set( site, looted_replacement );
     return return_items;
 }
References spell_effect::bash(), map_data_common_t::bash, item_stack::begin(), tinymap::collapse_at(), creature_tracker::creature_at(), tinymap::delete_signage(), Creature::die(), map_bash_info::drop_group, item_stack::end(), map_stack::erase(), tinymap::furn(), tinymap::furn_set(), get_creature_tracker(), tinymap::has_furn(), tinymap::i_at(), int_id< T >::id(), map_stack::insert(), item_group::items_from(), LIQUID, tinymap::load(), int_id< T >::obj(), one_in(), overmap_buffer, tinymap::points_on_zlevel(), tinymap::save(), tinymap::spawn_items(), map_bash_info::str_max, tinymap::ter(), tinymap::ter_set(), map_bash_info::ter_set, overmapbuffer::ter_set(), ter_t_curtains, ter_t_door_b, ter_t_door_boarded, ter_t_door_boarded_damaged, ter_t_door_boarded_damaged_peep, ter_t_door_boarded_peep, ter_t_door_c, ter_t_door_c_peep, ter_t_door_glass_c, ter_t_door_glass_o, ter_t_door_locked, ter_t_door_locked_alarm, ter_t_door_locked_peep, ter_t_door_metal_c, ter_t_door_metal_locked, ter_t_door_metal_o, ter_t_door_metal_pickable, ter_t_door_o, ter_t_rdoor_boarded, ter_t_rdoor_boarded_damaged, ter_t_wall, ter_t_wall_glass, ter_t_wall_glass_alarm, ter_t_window, ter_t_window_alarm, ter_t_window_alarm_taped, ter_t_window_boarded, ter_t_window_boarded_noglass, ter_t_window_domestic, ter_t_window_domestic_taped, ter_t_window_no_curtains, ter_t_window_no_curtains_taped, ter_t_window_taped, and calendar::turn.
Referenced by hospital_raid_return(), and scavenging_raid_return().
mission_failure()
void talk_function::mission_failure (npc & p)
Definition at line 156 of file npctalk_funcs.cpp.
 {
     mission *miss = p.chatbin.mission_selected;
     if( miss == nullptr ) {
         debugmsg( "mission_failure: mission_selected == nullptr" );
         return;
     }
     npc_opinion op;
     op.trust = -1;
     op.value = -1;
     op.anger = 1;
     p.op_of_u += op;
     miss->fail();
 }
References npc_opinion::anger, npc::chatbin, debugmsg, mission::fail(), dialogue_chatbin::mission_selected, npc::op_of_u, npc_opinion::trust, and npc_opinion::value.
Referenced by talk_effect_t::parse_string_effect().
mission_favor()
void talk_function::mission_favor (npc &)
mission_reward()
void talk_function::mission_reward (npc & p)
Definition at line 198 of file npctalk_funcs.cpp.
 {
     const mission *miss = p.chatbin.mission_selected;
     if( miss == nullptr ) {
         debugmsg( "Called mission_reward with null mission" );
         return;
     }
     int mission_value = miss->get_value();
     p.op_of_u.owed += mission_value;
     npc_trading::trade( p, 0, _( "Reward" ) );
 }
References _, npc::chatbin, debugmsg, mission::get_value(), dialogue_chatbin::mission_selected, npc::op_of_u, npc_opinion::owed, and npc_trading::trade().
Referenced by talk_effect_t::parse_string_effect().
mission_success()
void talk_function::mission_success (npc & p)
Definition at line 132 of file npctalk_funcs.cpp.
 {
     mission *miss = p.chatbin.mission_selected;
     if( miss == nullptr ) {
         debugmsg( "mission_success: mission_selected == nullptr" );
         return;
     }
     int miss_val = npc_trading::cash_to_favor( p, miss->get_value() );
     npc_opinion op;
     op.value = 1 + miss_val / 5;
     op.anger = -1;
     p.op_of_u += op;
     faction *p_fac = p.get_faction();
     if( p_fac != nullptr ) {
         int fac_val = std::min( 1 + miss_val / 10, 10 );
         p_fac->likes_u += fac_val;
         p_fac->respects_u += fac_val;
         p_fac->trusts_u += fac_val;
         p_fac->power += fac_val;
     }
     miss->wrap_up();
 }
References npc_opinion::anger, npc_trading::cash_to_favor(), npc::chatbin, debugmsg, npc::get_faction(), mission::get_value(), faction_template::likes_u, min(), dialogue_chatbin::mission_selected, npc::op_of_u, faction_template::power, faction_template::respects_u, faction_template::trusts_u, npc_opinion::value, and mission::wrap_up().
Referenced by talk_effect_t::parse_string_effect().
morale_chat()
void talk_function::morale_chat (npc & p)
Definition at line 800 of file npctalk_funcs.cpp.
 {
     get_player_character().add_morale( MORALE_CHAT, rng( 3, 10 ), 10, 200_minutes, 5_minutes / 2 );
     add_msg( m_good, _( "That was a pleasant conversation with %s" ), p.disp_name() );
 }
References _, Character::add_morale(), add_msg(), Character::disp_name(), get_player_character(), m_good, MORALE_CHAT, and rng().
morale_chat_activity()
void talk_function::morale_chat_activity (npc & p)
Definition at line 806 of file npctalk_funcs.cpp.
 {
     Character &player_character = get_player_character();
     const int moves = to_moves<int>( 10_minutes );
     player_character.assign_activity( ACT_SOCIALIZE, moves );
     player_character.activity.str_values.push_back( p.get_name() );
     if( one_in( 3 ) ) {
         p.say( SNIPPET.random_from_category( "npc_socialize" ).value_or( translation() ).translated() );
     }
     add_msg( m_good, _( "That was a pleasant conversation with %s." ), p.disp_name() );
     // 50% chance of increasing 1 npc opinion value each social chat after 6hr
     if( !p.has_effect( effect_socialized_recently ) ) {
         switch( rng( 1, 3 ) ) {
             case 1:
                 p.op_of_u.trust += rng( 0, 1 );
                 break;
             case 2:
                 p.op_of_u.value += rng( 0, 1 );
                 break;
             case 3:
                 if( p.op_of_u.anger > 0 ) {
                     p.op_of_u.anger += rng( 0, -1 );
                 }
                 break;
         }
         p.add_effect( effect_socialized_recently, 6_hours );
     }
     player_character.add_morale( MORALE_CHAT, rng( 3, 10 ), 10, 200_minutes, 5_minutes / 2 );
 }
References _, ACT_SOCIALIZE, Character::activity, Creature::add_effect(), Character::add_morale(), add_msg(), npc_opinion::anger, Character::assign_activity(), Character::disp_name(), effect_socialized_recently, Character::get_name(), get_player_character(), Creature::has_effect(), m_good, MORALE_CHAT, one_in(), npc::op_of_u, snippet_library::random_from_category(), rng(), npc::say(), SNIPPET, player_activity::str_values, npc_opinion::trust, and npc_opinion::value.
Referenced by talk_effect_t::parse_string_effect().
name_mission_tabs()
std::string talk_function::name_mission_tabs (const tripoint_abs_omt & omt_pos, const std::string & role_id, const std::string & cur_title, base_camps::tab_mode cur_tab)
Definition at line 4656 of file faction_camp.cpp.
 {
     if( role_id != base_camps::id ) {
         return cur_title;
     }
     std::optional<basecamp *> temp_camp = overmap_buffer.find_camp( omt_pos.xy() );
     if( !temp_camp ) {
         return cur_title;
     }
     basecamp *bcp = *temp_camp;
     for( const auto &direction : base_camps::all_directions ) {
         if( cur_tab == direction.second.tab_order ) {
             return bcp->expansion_tab( direction.first );
         }
     }
     return bcp->expansion_tab( base_camps::base_dir );
 }
References base_camps::all_directions, base_camps::base_dir, basecamp::expansion_tab(), overmapbuffer::find_camp(), base_camps::id, overmap_buffer, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by display_and_choose_opts().
nothing()
void talk_function::nothing (npc &)
Definition at line 111 of file npctalk_funcs.cpp.
 {
 }
Referenced by talk_effect_t::parse_string_effect().
npc_thankful()
void talk_function::npc_thankful (npc & p)
Definition at line 1263 of file npctalk_funcs.cpp.
 {
     if( p.get_attitude() == NPCATT_MUG || p.get_attitude() == NPCATT_WAIT_FOR_LEAVE ||
         p.get_attitude() == NPCATT_FLEE || p.get_attitude() == NPCATT_KILL ||
         p.get_attitude() == NPCATT_FLEE_TEMP ) {
         p.set_attitude( NPCATT_NULL );
     }
     if( p.chatbin.first_topic != p.chatbin.talk_friend ) {
         p.chatbin.first_topic = p.chatbin.talk_stranger_friendly;
     }
     p.personality.aggression -= 1;
 }
References npc_personality::aggression, npc::chatbin, dialogue_chatbin::first_topic, npc::get_attitude(), NPCATT_FLEE, NPCATT_FLEE_TEMP, NPCATT_KILL, NPCATT_MUG, NPCATT_NULL, NPCATT_WAIT_FOR_LEAVE, npc::personality, npc::set_attitude(), dialogue_chatbin::talk_friend, and dialogue_chatbin::talk_stranger_friendly.
Referenced by talk_effect_t::parse_string_effect().
om_building_region()
std::vector< std::pair< std::string, tripoint_abs_omt > > talk_function::om_building_region (const tripoint_abs_omt & omt_pos, int range, bool purge = false)
Returns the OM tiles surrounding the camp, purge removes all tiles that aren't expansions.
Definition at line 5315 of file faction_camp.cpp.
 {
     std::vector<std::pair<std::string, tripoint_abs_omt>> om_camp_region;
     for( const tripoint_abs_omt &omt_near_pos : points_in_radius( omt_pos, range ) ) {
         const oter_id &omt_rnear = overmap_buffer.ter( omt_near_pos );
         std::string om_rnear_id = omt_rnear.id().c_str();
         if( !purge || ( om_rnear_id.find( "faction_base_" ) != std::string::npos &&
                         // TODO: this exclusion check can be removed once primitive field camp OMTs have been purged
                         om_rnear_id.find( "faction_base_camp" ) == std::string::npos ) ) {
             om_camp_region.emplace_back( om_rnear_id, omt_near_pos );
         }
     }
     return om_camp_region;
 }
References string_id< T >::c_str(), int_id< T >::id(), overmap_buffer, points_in_radius(), and overmapbuffer::ter().
Referenced by basecamp::define_camp(), and start_camp().
om_simple_dir()
point talk_function::om_simple_dir (const tripoint_abs_omt & omt_pos, const tripoint_abs_omt & omt_tar)
Returns the x and y coordinates of (omt_tar - omt_pos), clamped to [-1, 1].
Definition at line 5331 of file faction_camp.cpp.
 {
     point_rel_omt diff = omt_tar.xy() - omt_pos.xy();
     return { clamp( diff.x(), -1, 1 ), clamp( diff.y(), -1, 1 ) };
 }
References clamp(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Referenced by basecamp::add_expansion(), basecamp::survey_field_return(), and basecamp::survey_return().
pick_style()
void talk_function::pick_style (npc & p)
Definition at line 1282 of file npctalk_funcs.cpp.
 {
     p.martial_arts_data->pick_style( p );
 }
References Character::martial_arts_data.
Referenced by talk_effect_t::parse_string_effect().
player_leaving()
void talk_function::player_leaving (npc & p)
Definition at line 1017 of file npctalk_funcs.cpp.
 {
     p.set_attitude( NPCATT_WAIT_FOR_LEAVE );
     p.patience = 15 - p.personality.aggression;
 }
References npc_personality::aggression, NPCATT_WAIT_FOR_LEAVE, npc::patience, npc::personality, and npc::set_attitude().
Referenced by talk_effect_t::parse_string_effect().
player_weapon_away()
void talk_function::player_weapon_away (npc &)
Definition at line 1032 of file npctalk_funcs.cpp.
 {
     Character &player_character = get_player_character();
     std::optional<bionic *> bionic_weapon = player_character.find_bionic_by_uid(
             player_character.get_weapon_bionic_uid() );
     if( bionic_weapon ) {
         player_character.deactivate_bionic( **bionic_weapon );
         return;
     }
     player_character.i_add( player_character.remove_weapon() );
 }
References Character::deactivate_bionic(), Character::find_bionic_by_uid(), get_player_character(), Character::get_weapon_bionic_uid(), Character::i_add(), and Character::remove_weapon().
Referenced by talk_effect_t::parse_string_effect(), and talk_effect_t::set_effect().
player_weapon_drop()
void talk_function::player_weapon_drop (npc &)
Definition at line 1046 of file npctalk_funcs.cpp.
 {
     Character &player_character = get_player_character();
     item weap = player_character.remove_weapon();
     drop_on_map( player_character, item_drop_reason::deliberate, {weap}, player_character.pos_bub() );
 }
References deliberate, drop_on_map(), get_player_character(), Creature::pos_bub(), and Character::remove_weapon().
Referenced by talk_effect_t::parse_string_effect(), and talk_effect_t::set_effect().
remove_stolen_status()
void talk_function::remove_stolen_status (npc & p)
Definition at line 1003 of file npctalk_funcs.cpp.
 {
     if( p.known_stolen_item ) {
         p.known_stolen_item = nullptr;
     }
     p.set_attitude( NPCATT_NULL );
 }
References npc::known_stolen_item, NPCATT_NULL, and npc::set_attitude().
Referenced by talk_effect_t::parse_string_effect().
reveal_stats()
void talk_function::reveal_stats (npc & p)
Definition at line 485 of file npctalk_funcs.cpp.
 {
     p.disp_info();
 }
References Character::disp_info().
Referenced by talk_effect_t::parse_string_effect().
revert_activity()
void talk_function::revert_activity (npc & p)
Definition at line 334 of file npctalk_funcs.cpp.
 {
     p.revert_after_activity();
 }
References npc::revert_after_activity().
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
scavenger_patrol()
void talk_function::scavenger_patrol (mission_data & mission_key, npc & p) static
Definition at line 641 of file mission_companion.cpp.
 {
     std::string entry = _( "Profit: 20-75 merch\nDanger: Low\nTime: 10 hour missions\n\n"
                            "Assigning one of your allies to patrol the surrounding wilderness "
                            "and isolated buildings presents the opportunity to build survival "
                            "skills while engaging in relatively safe combat against isolated "
                            "creatures." );
     const mission_id miss_id = { Scavenging_Patrol_Job, "", {}, std::nullopt };
     mission_key.add_start( miss_id, _( "Assign Scavenging Patrol" ), entry );
     std::vector<npc_ptr> npc_list = companion_list( p, miss_id );
     if( !npc_list.empty() ) {
         entry = _( "Profit: 20-75 merch\nDanger: Low\nTime: 10 hour missions\n\nPatrol Roster:\n" );
         bool avail = false;
         for( auto &elem : npc_list ) {
             const bool done = calendar::turn >= elem->companion_mission_time + 10_hours;
             avail |= done;
             if( done ) {
                 entry += "  " + elem->get_name() + _( " [DONE]\n" );
             } else {
                 entry += "  " + elem->get_name() + " [" + std::to_string( to_hours<int>( calendar::turn -
                          elem->companion_mission_time ) ) + _( " hours / 10 hours]\n" );
             }
         }
         if( avail ) {
             entry += _( return_ally_question_string );
         }
         mission_key.add_return( miss_id, _( "Retrieve Scavenging Patrol" ), entry, avail );
     }
 }
References _, mission_data::add_return(), mission_data::add_start(), companion_list(), return_ally_question_string, Scavenging_Patrol_Job, to_string(), and calendar::turn.
Referenced by companion_mission().
scavenger_raid()
void talk_function::scavenger_raid (mission_data & mission_key, npc & p) static
Definition at line 672 of file mission_companion.cpp.
 {
     std::string entry =
         _( "Profit: 50-100 merch, some items\nDanger: Medium\nTime: 10 hour missions\n\n"
            "Scavenging raids target formerly populated areas to loot as many "
            "valuable items as possible before being surrounded by the undead.  "
            "Combat is to be expected and assistance from the rest of the party "
            "can't be guaranteed.  The rewards are greater and there is a chance "
            "of the companion bringing back items." );
     const mission_id miss_id = {Scavenging_Raid_Job, "", {}, std::nullopt};
     mission_key.add_start( miss_id, _( "Assign Scavenging Raid" ), entry );
     std::vector<npc_ptr> npc_list = companion_list( p, miss_id );
     if( !npc_list.empty() ) {
         entry = _( "Profit: 50-100 merch\nDanger: Medium\nTime: 10 hour missions\n\n"
                    "Raid Roster:\n" );
         bool avail = false;
         for( auto &elem : npc_list ) {
             const bool done = calendar::turn >= elem->companion_mission_time + 10_hours;
             avail |= done;
             if( done ) {
                 entry += "  " + elem->get_name() + _( " [DONE]\n" );
             } else {
                 entry += "  " + elem->get_name() + " [" + std::to_string( to_hours<int>( calendar::turn -
                          elem->companion_mission_time ) ) + _( " hours / 10 hours]\n" );
             }
         }
         if( avail ) {
             entry += _( return_ally_question_string );
         }
         mission_key.add_return( miss_id, _( "Retrieve Scavenging Raid" ), entry, avail );
     }
 }
References _, mission_data::add_return(), mission_data::add_start(), companion_list(), return_ally_question_string, Scavenging_Raid_Job, to_string(), and calendar::turn.
Referenced by companion_mission().
scavenging_patrol_return()
bool talk_function::scavenging_patrol_return (npc & p)
Definition at line 1796 of file mission_companion.cpp.
 {
     npc_ptr comp = companion_choose_return( p, { Scavenging_Patrol_Job, "", {}, std::nullopt},
                                             calendar::turn - 10_hours );
     if( comp == nullptr ) {
         return false;
     }
     int experience = rng( 5, 20 );
     if( one_in( 4 ) ) {
         popup( _( "While scavenging, %s's party suddenly found itself set upon by a large mob of "
                   "undead" ), comp->get_name() );
         int skill = scavenging_combat_skill( *comp, 4, true );
         if( one_in( 6 ) ) {
             popup( _( "Through quick thinking the group was able to evade combat!" ) );
         } else {
             popup( _( "Combat took place in close quarters, focusing on melee skills" ) );
             int monsters = rng( 8, 30 );
             if( skill * rng_float( .60, 1.4 ) > .35 * monsters * rng_float( .6, 1.4 ) ) {
                 popup( _( "Through brute force the party smashed through the group of %d"
                           " undead!" ), monsters );
                 experience += rng( 2, 10 );
             } else {
                 popup( _( "Unfortunately they were overpowered by the undead  I'm sorry." ) );
                 overmap_buffer.remove_npc( comp->getID() );
                 return false;
             }
         }
     }
     int merch_amount = rng( 20, 75 );
     companion_skill_trainer( *comp, "combat", experience * 10_minutes, 10 );
     popup( _( "%s returns from patrol having earned %d merch and a fair bit of experience" ),
            comp->get_name(), merch_amount );
     if( one_in( 10 ) ) {
         popup( _( "%s was impressed with %s's performance and gave you a small bonus (25 merch)" ),
                p.get_name(), comp->get_name() );
         merch_amount += 25;
     }
     if( one_in( 10 ) && !p.has_trait( trait_NPC_MISSION_LEV_1 ) ) {
         p.set_mutation( trait_NPC_MISSION_LEV_1 );
         popup( _( "%s feels more confident in your abilities and is willing to let you "
                   "participate in daring raids." ), p.get_name() );
     }
     item merch = item( itype_FMCNote );
     get_player_character().i_add_or_drop( merch, merch_amount );
     companion_return( *comp );
     return true;
 }
References _, companion_choose_return(), companion_return(), companion_skill_trainer(), Character::get_name(), get_player_character(), Character::has_trait(), Character::i_add_or_drop(), itype_FMCNote, one_in(), overmap_buffer, popup(), overmapbuffer::remove_npc(), rng(), rng_float(), scavenging_combat_skill(), Scavenging_Patrol_Job, Character::set_mutation(), trait_NPC_MISSION_LEV_1, and calendar::turn.
Referenced by handle_outpost_mission().
scavenging_raid_return()
bool talk_function::scavenging_raid_return (npc & p)
Definition at line 1847 of file mission_companion.cpp.
 {
     npc_ptr comp = companion_choose_return( p, { Scavenging_Raid_Job, "", {}, std::nullopt},
                                             calendar::turn - 10_hours );
     if( comp == nullptr ) {
         return false;
     }
     int experience = rng( 10, 20 );
     if( one_in( 2 ) ) {
         popup( _( "While scavenging, %s's party suddenly found itself set upon by a large mob of "
                   "undead" ), comp->get_name() );
         int skill = scavenging_combat_skill( *comp, 4, true );
         if( one_in( 6 ) ) {
             popup( _( "Through quick thinking the group was able to evade combat!" ) );
         } else {
             popup( _( "Combat took place in close quarters, focusing on melee skills" ) );
             int monsters = rng( 8, 30 );
             if( skill * rng_float( .60, 1.4 ) > ( .35 * monsters * rng_float( .6, 1.4 ) ) ) {
                 popup( _( "Through brute force the party smashed through the group of %d "
                           "undead!" ), monsters );
                 experience += rng( 2, 10 );
             } else {
                 popup( _( "Unfortunately they were overpowered by the undead  I'm sorry." ) );
                 overmap_buffer.remove_npc( comp->getID() );
                 return false;
             }
         }
     }
     Character &player_character = get_player_character();
     tripoint_abs_omt loot_location = player_character.global_omt_location();
     std::set<item> all_returned_items;
     for( int i = 0; i < rng( 2, 3 ); i++ ) {
         tripoint_abs_omt site = overmap_buffer.find_closest(
                                     loot_location, "house", 0, false, ot_match_type::prefix );
         // Search the entire height of the house, including the basement and roof
         for( int z = -1; z <= OVERMAP_HEIGHT; z++ ) {
             site.z() = z;
             const oter_id &omt_ref = overmap_buffer.ter( site );
             // We're past the roof, so we can stop
             if( omt_ref == oter_open_air ) {
                 break;
             }
             const std::string om_cur = omt_ref.id().c_str();
             oter_str_id looted_replacement = oter_looted_house;
             if( om_cur.find( "_roof" ) != std::string::npos ) {
                 looted_replacement = oter_looted_house_roof;
             }
             if( z == -1 ) {
                 if( om_cur.find( "basement" ) != std::string::npos ) {
                     looted_replacement = oter_looted_house_basement;
                 } else {
                     continue;
                 }
             }
             overmap_buffer.reveal( site, 2 );
             std::set<item> returned_items = loot_building( site, looted_replacement );
             all_returned_items.insert( returned_items.begin(), returned_items.end() );
         }
     }
     int merch_amount = rng( 50, 100 );
     companion_skill_trainer( *comp, "combat", experience * 10_minutes, 10 );
     popup( _( "%s returns from the raid having earned %d merch and a fair bit of experience" ),
            comp->get_name(), merch_amount );
     if( one_in( 20 ) ) {
         popup( _( "%s was impressed with %s's performance and gave you a small bonus (25 merch)" ),
                p.get_name(), comp->get_name() );
         merch_amount += 25;
     }
     if( one_in( 2 ) ) {
         item_group_id itemlist( "npc_misc" );
         if( one_in( 8 ) ) {
             itemlist = Item_spawn_data_npc_weapon_random;
         }
         item result = item_group::item_from( itemlist );
         if( !result.is_null() ) {
             popup( _( "%s returned with a %s for you!" ), comp->get_name(), result.tname() );
             player_character.i_add_or_drop( result );
         }
     }
     std::list<item> to_distribute;
     for( item i : all_returned_items ) {
         // Scavengers get most items and put them up for sale, player gets the scraps
         if( one_in( 8 ) ) {
             player_character.i_drop_at( i );
         } else {
             i.set_owner( p );
             to_distribute.push_back( i );
         }
     }
     distribute_items_to_npc_zones( to_distribute, p );
     item merch = item( itype_FMCNote );
     player_character.i_add_or_drop( merch, merch_amount );
     companion_return( *comp );
     return true;
 }
References _, string_id< T >::c_str(), companion_choose_return(), companion_return(), companion_skill_trainer(), distribute_items_to_npc_zones(), overmapbuffer::find_closest(), Character::get_name(), get_player_character(), Creature::global_omt_location(), Character::i_add_or_drop(), Character::i_drop_at(), int_id< T >::id(), item::is_null(), item_group::item_from(), Item_spawn_data_npc_weapon_random, itype_FMCNote, loot_building(), one_in(), oter_looted_house, oter_looted_house_basement, oter_looted_house_roof, oter_open_air, overmap_buffer, OVERMAP_HEIGHT, popup(), prefix, overmapbuffer::remove_npc(), overmapbuffer::reveal(), rng(), rng_float(), scavenging_combat_skill(), Scavenging_Raid_Job, overmapbuffer::ter(), item::tname(), calendar::turn, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by handle_outpost_mission().
set_npc_pickup()
void talk_function::set_npc_pickup (npc & p)
Definition at line 1258 of file npctalk_funcs.cpp.
 {
     p.rules.pickup_whitelist->show( p.name );
 }
References Character::name, npc_follower_rules::pickup_whitelist, and npc::rules.
Referenced by talk_effect_t::parse_string_effect().
sort_loot()
void talk_function::sort_loot (npc & p)
Definition at line 241 of file npctalk_funcs.cpp.
 {
     p.assign_activity( ACT_MOVE_LOOT );
 }
References ACT_MOVE_LOOT, and Character::assign_activity().
Referenced by game::chat(), and talk_effect_t::parse_string_effect().
start_camp()
void talk_function::start_camp (npc & p)
Start a faction camp on the current OM tile.
Definition at line 702 of file faction_camp.cpp.
 {
     const tripoint_abs_omt omt_pos = p.global_omt_location();
     const oter_id &omt_ref = overmap_buffer.ter( omt_pos );
     const std::optional<mapgen_arguments> *maybe_args = overmap_buffer.mapgen_args( omt_pos );
     const auto &pos_camps = recipe_group::get_recipes_by_id( "all_faction_base_types", omt_ref,
                             maybe_args );
     if( pos_camps.empty() ) {
         popup( _( "You cannot build a camp here." ) );
         return;
     }
     const recipe_id camp_type = base_camps::select_camp_option( pos_camps,
                                 _( "Select a camp type:" ) );
     if( !camp_type ) {
         return;
     }
     for( const auto &om_near : om_building_region( omt_pos, 3 ) ) {
         const oter_id &om_type = oter_id( om_near.first );
         if( is_ot_match( "faction_base", om_type, ot_match_type::contains ) ) {
             tripoint_abs_omt const &building_omt_pos = om_near.second;
             std::vector<basecamp> const &camps = overmap_buffer.get_om_global( building_omt_pos ).om->camps;
             if( std::any_of( camps.cbegin(), camps.cend(), [&building_omt_pos]( const basecamp & camp ) {
             return camp.camp_omt_pos() == building_omt_pos;
             } ) ) {
                 popup( _( "You are too close to another camp!" ) );
                 return;
             }
         }
     }
     const recipe &making = camp_type.obj();
     if( !run_mapgen_update_func( making.get_blueprint(), omt_pos, {} ) ) {
         popup( _( "%s failed to start the %s basecamp, perhaps there is a vehicle in the way." ),
                p.disp_name(), making.get_blueprint().str() );
         return;
     }
     std::optional<basecamp *> camp = get_basecamp( p, camp_type.str() );
     if( camp.has_value() ) {
         for( int tab_num = base_camps::TAB_MAIN; tab_num <= base_camps::TAB_NW; tab_num++ ) {
             std::vector<ui_mission_id> temp;
             camp.value()->hidden_missions.push_back( temp );
         }
     }
 }
References _, overmap::camps, contains, Character::disp_name(), get_basecamp(), recipe::get_blueprint(), overmapbuffer::get_om_global(), recipe_group::get_recipes_by_id(), Creature::global_omt_location(), is_ot_match(), overmapbuffer::mapgen_args(), string_id< T >::obj(), overmap_with_local_coords::om, om_building_region(), overmap_buffer, popup(), run_mapgen_update_func(), base_camps::select_camp_option(), string_id< T >::str(), base_camps::TAB_MAIN, base_camps::TAB_NW, temp, and overmapbuffer::ter().
Referenced by talk_effect_t::parse_string_effect().
start_mugging()
void talk_function::start_mugging (npc & p)
Definition at line 1011 of file npctalk_funcs.cpp.
 {
     p.set_attitude( NPCATT_MUG );
     add_msg( _( "Pause to stay still.  Any movement may cause %s to attack." ), p.get_name() );
 }
References _, add_msg(), Character::get_name(), NPCATT_MUG, and npc::set_attitude().
Referenced by talk_effect_t::parse_string_effect(), and talk_effect_t::set_effect().
start_trade()
void talk_function::start_trade (npc & p)
Definition at line 236 of file npctalk_funcs.cpp.
 {
     npc_trading::trade( p, 0, _( "Trade" ) );
 }
References _, and npc_trading::trade().
Referenced by talk_effect_t::parse_string_effect().
start_training()
void talk_function::start_training (npc & p)
Definition at line 1084 of file npctalk_funcs.cpp.
 {
     teach_domain d;
     d.skill = p.chatbin.skill;
     d.style = p.chatbin.style;
     d.spell = p.chatbin.dialogue_spell;
     d.prof = p.chatbin.proficiency;
     std::vector<Character *> students;
     students.push_back( &get_player_character() );
     start_training_gen( p, students, d );
 }
References npc::chatbin, dialogue_chatbin::dialogue_spell, get_player_character(), talk_function::teach_domain::prof, dialogue_chatbin::proficiency, dialogue_chatbin::skill, talk_function::teach_domain::skill, talk_function::teach_domain::spell, start_training_gen(), dialogue_chatbin::style, and talk_function::teach_domain::style.
Referenced by talk_effect_t::parse_string_effect().
start_training_gen()
void talk_function::start_training_gen (Character & teacher, std::vector< Character * > & students, teach_domain & d)
Definition at line 1144 of file npctalk_funcs.cpp.
 {
     int cost = 0;
     time_duration time = 0_turns;
     std::string name;
     const skill_id &skill = d.skill;
     const matype_id &style = d.style;
     const spell_id &sp_id = d.spell;
     const proficiency_id &proficiency = d.prof;
     int expert_multiplier = 1;
     bool player_is_student = false;
     for( Character *student : students ) {
         if( student->is_avatar() ) {
             player_is_student = true;
         }
         int tmp_cost = 0;
         time_duration tmp_time = 0_turns;
         if( skill != skill_id() &&
             student->get_knowledge_level( skill ) < teacher.get_knowledge_level( skill ) ) {
             tmp_cost = calc_skill_training_cost_char( teacher, *student, skill );
             tmp_time = calc_skill_training_time_char( teacher, *student, skill );
             name = skill.str();
         } else if( style != matype_id() &&
                    !student->martial_arts_data->has_martialart( style ) ) {
             tmp_cost = calc_ma_style_training_cost( teacher, *student, style );
             tmp_time = calc_ma_style_training_time( teacher, *student, style );
             name = style.str();
         } else if( sp_id != spell_id() ) {
             // already checked if can learn this spell in npctalk.cpp
             tmp_cost = calc_spell_training_cost( teacher, *student, sp_id );
             tmp_time = calc_spell_training_time( teacher, *student, sp_id );
             name = sp_id.str();
             const spell &temp_spell = teacher.magic->get_spell( sp_id );
             const bool knows = student->magic->knows_spell( sp_id );
             expert_multiplier = knows ? temp_spell.get_level() -
                                 student->magic->get_spell( sp_id ).get_level() : 1;
         } else if( proficiency != proficiency_id() ) {
             tmp_cost = calc_proficiency_training_cost( teacher, *student, proficiency );
             tmp_time = calc_proficiency_training_time( teacher, *student, proficiency );
             name = proficiency.str();
         } else {
             debugmsg( "start_training with no valid skill or style set" );
             return;
         }
         // use the slowest common denominator and combine cost
         cost += tmp_cost;
         time = std::max( time, tmp_time );
     }
     if( !teacher.is_avatar() ) {
         npc &p = static_cast<npc &>( teacher );
         mission *miss = p.chatbin.mission_selected;
         const character_id &pid = get_player_character().getID();
         if( player_is_student && miss != nullptr &&
             miss->get_assigned_player_id() == pid && miss->is_complete( pid ) ) {
             clear_mission( p );
         } else if( !npc_trading::pay_npc( p, cost ) ) {
             return;
         }
     }
     const int teacher_id = teacher.getID().get_value();
     player_activity tact( ACT_TRAIN_TEACHER, to_moves<int>( time ), teacher_id, 0, name );
     for( Character *student : students ) {
         player_activity act( ACT_TRAIN, to_moves<int>( time ), teacher_id, 0, name );
         act.values.push_back( expert_multiplier );
         student->assign_activity( act );
         tact.values.push_back( student->getID().get_value() );
     }
     teacher.assign_activity( tact );
     teacher.add_effect( effect_asked_to_train, 6_hours );
 }
References act, ACT_TRAIN, ACT_TRAIN_TEACHER, Creature::add_effect(), Character::assign_activity(), calc_ma_style_training_cost(), calc_ma_style_training_time(), calc_proficiency_training_cost(), calc_proficiency_training_time(), calc_skill_training_cost_char(), calc_skill_training_time_char(), calc_spell_training_cost(), calc_spell_training_time(), npc::chatbin, clear_mission(), debugmsg, effect_asked_to_train, mission::get_assigned_player_id(), Character::get_knowledge_level(), spell::get_level(), get_player_character(), character_id::get_value(), Character::getID(), Creature::is_avatar(), mission::is_complete(), Character::magic, max(), dialogue_chatbin::mission_selected, om_direction::name(), npc_trading::pay_npc(), talk_function::teach_domain::prof, talk_function::teach_domain::skill, talk_function::teach_domain::spell, string_id< T >::str(), talk_function::teach_domain::style, and player_activity::values.
Referenced by game::chat(), start_training(), start_training_npc(), and start_training_seminar().
start_training_npc()
void talk_function::start_training_npc (npc & p)
Definition at line 1072 of file npctalk_funcs.cpp.
 {
     teach_domain d;
     d.skill = p.chatbin.skill;
     d.style = p.chatbin.style;
     d.spell = p.chatbin.dialogue_spell;
     d.prof = p.chatbin.proficiency;
     std::vector<Character *> students;
     students.push_back( &p );
     start_training_gen( get_player_character(), students, d );
 }
References npc::chatbin, dialogue_chatbin::dialogue_spell, get_player_character(), talk_function::teach_domain::prof, dialogue_chatbin::proficiency, dialogue_chatbin::skill, talk_function::teach_domain::skill, talk_function::teach_domain::spell, start_training_gen(), dialogue_chatbin::style, and talk_function::teach_domain::style.
Referenced by talk_effect_t::parse_string_effect().
start_training_seminar()
void talk_function::start_training_seminar (npc & p)
Definition at line 1096 of file npctalk_funcs.cpp.
 {
     teach_domain d;
     d.skill = p.chatbin.skill;
     d.style = p.chatbin.style;
     d.spell = p.chatbin.dialogue_spell;
     d.prof = p.chatbin.proficiency;
     std::vector<npc *> followers = g->get_npcs_if( [&p]( const npc & n ) {
         return n.is_player_ally() && n.is_following() && n.can_hear( p.pos(), p.get_shout_volume() );
     } );
     std::vector<Character *> students;
     for( npc *n : followers ) {
         if( n && p.getID() != n->getID() ) {
             students.push_back( n );
         }
     }
     students.push_back( &get_player_character() );
     std::vector<Character *> picked;
     std::function<bool( const Character * )> include_func = [&]( const Character * c ) {
         if( d.skill != skill_id() ) {
             return c->get_knowledge_level( d.skill ) < p.get_knowledge_level( d.skill );
         } else if( d.style != matype_id() ) {
             return !c->martial_arts_data->has_martialart( d.style );
         } else if( d.prof != proficiency_id() ) {
             return !c->has_proficiency( d.prof );
         } else if( d.spell != spell_id() ) {
             const bool knows = c->magic->knows_spell( d.spell );
             return !knows || c->magic->get_spell( d.spell ).get_level() <
                    p.magic->get_spell( d.spell ).get_level();
         }
         return false;
     };
     std::vector<int> selected = npcs_select_menu( students, _( "Who should participate?" ),
     [&include_func]( const Character * ch ) {
         return !include_func( ch );
     } );
     if( selected.empty() ) {
         return;
     }
     picked.reserve( selected.size() );
     for( int sel : selected ) {
         picked.emplace_back( students[sel] );
     }
     start_training_gen( p, picked, d );
 }
References _, c, Character::can_hear(), npc::chatbin, dialogue_chatbin::dialogue_spell, g, Character::get_knowledge_level(), get_player_character(), Character::get_shout_volume(), Character::getID(), npc::is_following(), npc::is_player_ally(), Character::magic, npcs_select_menu(), Creature::pos(), talk_function::teach_domain::prof, dialogue_chatbin::proficiency, dialogue_chatbin::skill, talk_function::teach_domain::skill, talk_function::teach_domain::spell, start_training_gen(), dialogue_chatbin::style, and talk_function::teach_domain::style.
Referenced by talk_effect_t::parse_string_effect().
stop_following()
void talk_function::stop_following (npc & p)
Definition at line 938 of file npctalk_funcs.cpp.
 {
     // this is to tell non-allied NPCs to stop following.
     // ( usually after a mission where they were temporarily tagging along )
     // so don't tell already allied NPCs to stop following.
     // they use the guard command for that.
     if( p.is_player_ally() ) {
         return;
     }
     add_msg( _( "%s stops following." ), p.get_name() );
     p.set_attitude( NPCATT_NULL );
 }
References _, add_msg(), Character::get_name(), npc::is_player_ally(), NPCATT_NULL, and npc::set_attitude().
Referenced by talk_effect_t::parse_string_effect().
stop_guard()
void talk_function::stop_guard (npc & p)
Definition at line 449 of file npctalk_funcs.cpp.
 {
     if( !p.is_player_ally() ) {
         p.set_attitude( NPCATT_NULL );
         p.set_mission( NPC_MISSION_NULL );
         return;
     }
     p.set_attitude( NPCATT_FOLLOW );
     add_msg( _( "%s begins to follow you." ), p.get_name() );
     p.set_mission( NPC_MISSION_NULL );
     if( p.has_companion_mission() ) {
         p.reset_companion_mission();
     }
     p.chatbin.first_topic = p.chatbin.talk_friend;
     p.goal = npc::no_goal_point;
     p.guard_pos = std::nullopt;
     if( p.assigned_camp ) {
         if( std::optional<basecamp *> bcp = overmap_buffer.find_camp( ( *p.assigned_camp ).xy() ) ) {
             ( *bcp )->remove_assignee( p.getID() );
             ( *bcp )->validate_assignees();
         }
         p.assigned_camp = std::nullopt;
     }
 }
References _, add_msg(), npc::assigned_camp, npc::chatbin, overmapbuffer::find_camp(), dialogue_chatbin::first_topic, Character::get_name(), Character::getID(), npc::goal, npc::guard_pos, npc::has_companion_mission(), npc::is_player_ally(), npc::no_goal_point, NPC_MISSION_NULL, NPCATT_FOLLOW, NPCATT_NULL, overmap_buffer, npc::reset_companion_mission(), npc::set_attitude(), npc::set_mission(), and dialogue_chatbin::talk_friend.
Referenced by basecamp::abandon_camp(), game::chat(), and talk_effect_t::parse_string_effect().
stranger_neutral()
void talk_function::stranger_neutral (npc & p)
Definition at line 951 of file npctalk_funcs.cpp.
 {
     add_msg( _( "%s feels less threatened by you." ), p.get_name() );
     p.set_attitude( NPCATT_NULL );
     p.chatbin.first_topic = p.chatbin.talk_stranger_neutral;
 }
References _, add_msg(), npc::chatbin, dialogue_chatbin::first_topic, Character::get_name(), NPCATT_NULL, npc::set_attitude(), and dialogue_chatbin::talk_stranger_neutral.
Referenced by talk_effect_t::parse_string_effect().
temp_npc()
npc_ptr talk_function::temp_npc (const string_id< npc_template > & type)
Definition at line 1538 of file mission_companion.cpp.
 {
     npc_ptr temp = make_shared_fast<npc>();
     temp->normalize();
     temp->load_npc_template( type );
     return temp;
 }
References temp.
Referenced by caravan_return().
wake_up()
void talk_function::wake_up (npc & p)
Definition at line 474 of file npctalk_funcs.cpp.
 {
     p.rules.clear_override( ally_rule::allow_sleep );
     p.rules.enable_override( ally_rule::allow_sleep );
     p.remove_effect( effect_allow_sleep );
     p.remove_effect( effect_lying_down );
     p.remove_effect( effect_npc_suspend );
     p.remove_effect( effect_sleep );
     // TODO: Get mad at player for waking us up unless we're in danger
 }
References allow_sleep, npc_follower_rules::clear_override(), effect_allow_sleep, effect_lying_down, effect_npc_suspend, effect_sleep, npc_follower_rules::enable_override(), Creature::remove_effect(), and npc::rules.
Referenced by game::chat(), and talk_effect_t::parse_string_effect().