Cataclysm DDA: overmap_locations Namespace Reference
overmap_locations Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void check_consistency ()
void reset ()
void finalize ()
Function Documentation
check_consistency()
void overmap_locations::check_consistency ()
Definition at line 89 of file overmap_location.cpp.
 {
     locations.check();
 }
References anonymous_namespace{overmap_location.cpp}::locations.
Referenced by DynamicDataLoader::check_consistency().
finalize()
void overmap_locations::finalize ()
Definition at line 99 of file overmap_location.cpp.
 {
     locations.finalize();
     for( const overmap_location &elem : locations.get_all() ) {
         const_cast<overmap_location &>( elem ).finalize(); // This cast is ugly, but safe.
     }
 }
References behavior::finalize(), and anonymous_namespace{overmap_location.cpp}::locations.
Referenced by DynamicDataLoader::finalize_loaded_data().
load()
void overmap_locations::load (const JsonObject & jo, const std::string & src)
Definition at line 84 of file overmap_location.cpp.
 {
     locations.load( jo, src );
 }
References anonymous_namespace{overmap_location.cpp}::locations.
Referenced by DynamicDataLoader::initialize().
reset()
void overmap_locations::reset ()
Definition at line 94 of file overmap_location.cpp.
 {
     locations.reset();
 }
References anonymous_namespace{overmap_location.cpp}::locations.
Referenced by DynamicDataLoader::unload_data().