Cataclysm DDA: anonymous_namespace{clothing_mod.cpp} Namespace Reference
anonymous_namespace{clothing_mod.cpp} Namespace Reference
Variables
generic_factory< clothing_mod > all_clothing_mods ("clothing mods")
Variable Documentation
all_clothing_mods
generic_factory<clothing_mod> anonymous_namespace{clothing_mod.cpp}::all_clothing_mods("clothing mods") ("clothing mods")
Referenced by clothing_mod::count(), clothing_mods::get_all(), string_id< T >::is_valid(), clothing_mods::load(), string_id< T >::obj(), and clothing_mods::reset().