Cataclysm DDA: dialogue_data Namespace Reference
dialogue_data Namespace Reference
Functions
const std::unordered_set< std::string > & simple_string_conds ()
const std::unordered_set< std::string > & complex_conds ()
Function Documentation
complex_conds()
const std::unordered_set< std::string > & dialogue_data::complex_conds ()
Definition at line 2642 of file condition.cpp.
 {
     static std::unordered_set<std::string> ret;
     if( ret.empty() ) {
         for( const condition_parser &p : parsers ) {
             ret.emplace( p.key_alpha );
             if( p.has_beta ) {
                 ret.emplace( p.key_beta );
             }
         }
     }
     return ret;
 }
References parsers, and cata::hash64_detail::ret.
Referenced by conditional_t::conditional_t(), and dynamic_line_t::dynamic_line_t().
simple_string_conds()
const std::unordered_set< std::string > & dialogue_data::simple_string_conds ()
Definition at line 2628 of file condition.cpp.
 {
     static std::unordered_set<std::string> ret;
     if( ret.empty() ) {
         for( const condition_parser &p : parsers_simple ) {
             ret.emplace( p.key_alpha );
             if( p.has_beta ) {
                 ret.emplace( p.key_beta );
             }
         }
     }
     return ret;
 }
References parsers_simple, and cata::hash64_detail::ret.
Referenced by conditional_t::conditional_t(), and dynamic_line_t::dynamic_line_t().