Cataclysm DDA: iexamine Namespace Reference
iexamine Namespace Reference
Functions
bool can_hack (Character &you)
bool try_start_hacking (Character &you, const tripoint &examp)
void egg_sack_generic (Character &you, const tripoint &examp, const mtype_id &montype)
void none (Character &you, const tripoint &examp)
Nothing player can interact with here.
bool always_false (const tripoint &examp)
bool false_and_debugmsg (const tripoint &examp)
bool always_true (const tripoint &examp)
bool harvestable_now (const tripoint &examp)
void gaspump (Character &you, const tripoint &examp)
Use "gas pump.".
void atm (Character &you, const tripoint &examp)
launches the atm menu class which then handles all the atm interactions.
void vending (Character &you, const tripoint &examp)
Generates vending machine UI and allows players to purchase contained items with a cash card.
void elevator (Character &you, const tripoint &examp)
void nanofab (Character &you, const tripoint &examp)
TEMPLATE FABRICATORS Generate items from found blueprints.
void controls_gate (Character &you, const tripoint &examp)
Open gate.
void cardreader (Character &you, const tripoint &examp)
void cardreader_robofac (Character &you, const tripoint &examp)
void cardreader_foodplace (Character &you, const tripoint &examp)
void intercom (Character &you, const tripoint &examp)
void cvdmachine (Character &you, const tripoint &examp)
Pick an appropriate item and apply diamond coating if possible.
void change_appearance (Character &you, const tripoint &examp)
Change player eye and skin color.
void rubble (Character &you, const tripoint &examp)
Prompt removal of rubble.
void chainfence (Character &you, const tripoint &examp)
Prompt climbing over fence.
void bars (Character &you, const tripoint &examp)
If player has amorphous trait, slip through the bars.
void deployed_furniture (Character &you, const tripoint &pos)
void portable_structure (Character &you, const tripoint &examp)
Determine structure's type and prompts its removal.
void pit (Character &you, const tripoint &examp)
If there is a 2x4 around, prompt placing it across pit.
void pit_covered (Character &you, const tripoint &examp)
Prompt removing the 2x4 placed across the pit.
void safe (Character &you, const tripoint &examp)
Attempt to crack safe through audio-feedback manual lock manipulation.
void gunsafe_el (Character &you, const tripoint &examp)
Attempt to "hack" the gunsafe's electronic lock and open it.
void harvest_furn_nectar (Character &you, const tripoint &examp)
void harvest_furn (Character &you, const tripoint &examp)
void harvest_ter_nectar (Character &you, const tripoint &examp)
void harvest_ter (Character &you, const tripoint &examp)
void harvested_plant (Character &you, const tripoint &examp)
Only harvest a plant once per season.
void locked_object (Character &you, const tripoint &examp)
Checks whether PC has a crowbar then calls iuse.crowbar.
void locked_object_pickable (Character &you, const tripoint &examp)
Checks whether PC has picklocks then calls pick_lock iuse function OR assigns ACT_LOCKPICK.
void bulletin_board (Character &you, const tripoint &examp)
void pedestal_wyrm (Character &you, const tripoint &examp)
Spawn 1d4 wyrms and sink pedestal into ground.
void pedestal_temple (Character &you, const tripoint &examp)
Put petrified eye on pedestal causing it to sink into ground and open temple.
void door_peephole (Character &you, const tripoint &examp)
Unlock/open door or attempt to peek through peephole.
void fswitch (Character &you, const tripoint &examp)
void flower_tulip (Character &you, const tripoint &examp)
void flower_spurge (Character &you, const tripoint &examp)
void flower_poppy (Character &you, const tripoint &examp)
Prompt pick (or drink nectar if able) poppy bud.
void flower_cactus (Character &you, const tripoint &examp)
Prompt pick cactus pad.
void flower_bluebell (Character &you, const tripoint &examp)
void flower_dahlia (Character &you, const tripoint &examp)
Dig up its roots or drink its nectar if you can.
void flower_marloss (Character &you, const tripoint &examp)
void fungus (Character &you, const tripoint &examp)
Remove furniture.
void dirtmound (Character &you, const tripoint &examp)
If it's warm enough, pick one of the player's seeds and plant it.
void aggie_plant (Character &you, const tripoint &examp)
void tree_hickory (Character &you, const tripoint &examp)
void tree_maple (Character &you, const tripoint &examp)
void tree_maple_tapped (Character &you, const tripoint &examp)
void shrub_marloss (Character &you, const tripoint &examp)
void tree_marloss (Character &you, const tripoint &examp)
void shrub_wildveggies (Character &you, const tripoint &examp)
void part_con (Character &you, const tripoint &examp)
void water_source (Character &, const tripoint &examp)
void finite_water_source (Character &, const tripoint &examp)
void kiln_empty (Character &you, const tripoint &examp)
void kiln_full (Character &you, const tripoint &examp)
void stook_empty (Character &, const tripoint &examp)
void stook_full (Character &, const tripoint &examp)
void arcfurnace_empty (Character &you, const tripoint &examp)
void arcfurnace_full (Character &you, const tripoint &examp)
void autoclave_empty (Character &you, const tripoint &examp)
void autoclave_full (Character &, const tripoint &examp)
void fireplace (Character &you, const tripoint &examp)
void fvat_empty (Character &you, const tripoint &examp)
void fvat_full (Character &you, const tripoint &examp)
void compost_empty (Character &you, const tripoint &examp)
void compost_full (Character &you, const tripoint &examp)
void keg (Character &you, const tripoint &examp)
void reload_furniture (Character &you, const tripoint &examp)
void curtains (Character &you, const tripoint &examp)
void sign (Character &you, const tripoint &examp)
void pay_gas (Character &you, const tripoint &examp)
void ledge (Character &you, const tripoint &examp)
void autodoc (Character &you, const tripoint &examp)
void attunement_altar (Character &you, const tripoint &examp)
void translocator (Character &you, const tripoint &examp)
void on_smoke_out (const tripoint &examp, const time_point &start_time)
void mill_finalize (Character &, const tripoint &examp)
void quern_examine (Character &you, const tripoint &examp)
void smoker_options (Character &you, const tripoint &examp)
void open_safe (Character &you, const tripoint &examp)
void workbench (Character &you, const tripoint &examp)
void workbench_internal (Character &you, const tripoint &examp, const std::optional< vpart_reference > &part)
void workout (Character &you, const tripoint &examp)
void invalid (Character &you, const tripoint &examp)
bool pour_into_keg (const tripoint &pos, item &liquid)
Pour liquid into a keg (furniture) on the map.
std::optional< tripoint > getGasPumpByNumber (const tripoint &p, int number)
bool toPumpFuel (const tripoint &src, const tripoint &dst, int units)
std::optional< tripoint > getNearFilledGasTank (const tripoint &center, int &fuel_units, fuel_station_fuel_type &fuel_type)
bool has_keg (const tripoint &pos)
Check whether there is a keg on the map that can be filled via pour_into_keg.
std::list< item > get_harvest_items (const itype &type, int plant_count, int seed_count, bool byproducts)
Items that appear when a generic plant is harvested.
std::vector< seed_tuple > get_seed_entries (const std::vector< item * > &seed_inv)
Make lists of unique seed types and names for the menu(no multiple hemp seeds etc)
int query_seed (const std::vector< seed_tuple > &seed_entries)
Choose seed for planting.
void plant_seed (Character &you, const tripoint &examp, const itype_id &seed_id)
Actual planting of selected seed.
void clear_overgrown (Character &you, const tripoint &examp)
void harvest_plant_ex (Character &you, const tripoint &examp)
void harvest_plant (Character &you, const tripoint &examp, bool from_activity)
Actual harvesting of selected plant.
void fertilize_plant (Character &you, const tripoint &tile, const itype_id &fertilizer)
itype_id choose_fertilizer (Character &you, const std::string &pname, bool ask_player)
ret_val< void > can_fertilize (Character &you, const tripoint &tile, const itype_id &fertilizer)
void practice_survival_while_foraging (Character &who)
Function Documentation
aggie_plant()
void iexamine::aggie_plant (Character & you, const tripoint & examp)
Definition at line 2848 of file iexamine.cpp.
 {
     map &here = get_map();
     // Can't use item_stack::only_item() since there might be fertilizer
     map_stack items = here.i_at( examp );
     const map_stack::iterator seed = std::find_if( items.begin(), items.end(), []( const item & it ) {
         return it.is_seed();
     } );
     if( seed == items.end() ) {
         debugmsg( "Missing seed for plant at (%d, %d, %d)", examp.x, examp.y, examp.z );
         here.i_clear( examp );
         here.furn_set( examp, furn_str_id::NULL_ID() );
         return;
     }
     const std::string pname = seed->get_plant_name();
     if( here.has_flag_furn( ter_furn_flag::TFLAG_GROWTH_HARVEST, examp ) &&
         query_yn( _( "Harvest the %s?" ), pname ) ) {
         harvest_plant( you, examp, false );
     } else if( !here.has_flag_furn( ter_furn_flag::TFLAG_GROWTH_HARVEST, examp ) ) {
         if( here.i_at( examp ).size() > 1 ) {
             add_msg( m_info, _( "This %s has already been fertilized." ), pname );
             return;
         }
         itype_id fertilizer = choose_fertilizer( you, pname, true /*ask player for confirmation */ );
         if( !fertilizer.is_empty() ) {
             fertilize_plant( you, examp, fertilizer );
         }
     }
 }
References _, add_msg(), item_stack::begin(), choose_fertilizer(), debugmsg, item_stack::end(), fertilize_plant(), map::furn_set(), get_map(), harvest_plant(), map::has_flag_furn(), map::i_at(), map::i_clear(), string_id< T >::is_empty(), m_info, string_id< furn_t >::NULL_ID(), query_yn(), iuse::seed(), item_stack::size(), TFLAG_GROWTH_HARVEST, tripoint::x, tripoint::y, and tripoint::z.
Referenced by iexamine_functions_from_string().
always_false()
bool iexamine::always_false (const tripoint & examp)
Definition at line 311 of file iexamine.cpp.
 {
     return false;
 }
Referenced by iexamine_functions_from_string().
always_true()
bool iexamine::always_true (const tripoint & examp)
Definition at line 323 of file iexamine.cpp.
 {
     return true;
 }
Referenced by iexamine_functions_from_string().
arcfurnace_empty()
void iexamine::arcfurnace_empty (Character & you, const tripoint & examp)
Fabrication decreases loss when firing a furnace
Definition at line 3036 of file iexamine.cpp.
 {
     map &here = get_map();
     furn_id cur_arcfurnace_type = here.furn( examp );
     furn_id next_arcfurnace_type = furn_str_id::NULL_ID();
     if( cur_arcfurnace_type == furn_f_arcfurnace_empty ) {
         next_arcfurnace_type = furn_f_arcfurnace_full;
     } else {
         debugmsg( "Examined furniture has action arcfurnace_empty, but is of type %s",
                   here.furn( examp ).id().c_str() );
         return;
     }
     static const std::set<material_id> arcfurnaceable{ material_cac2powder };
     bool fuel_present = false;
     map_stack items = here.i_at( examp );
     for( const item &i : items ) {
         if( i.typeId() == itype_chem_carbide ) {
             add_msg( _( "This furnace already contains calcium carbide." ) );
             add_msg( _( "Remove it before activating the arc furnace again." ) );
             return;
         } else if( i.made_of_any( arcfurnaceable ) ) {
             fuel_present = true;
         } else {
             add_msg( m_bad, _( "This furnace contains %s, which can't be made into calcium carbide!" ),
                      i.tname( 1, false ) );
             return;
         }
     }
     if( !fuel_present ) {
         add_msg( _( "This furnace is empty.  Fill it with powdered coke and lime mix, and try again." ) );
         return;
     }
     ///\EFFECT_FABRICATION decreases loss when firing a furnace
     const float skill = you.get_skill_level( skill_fabrication );
     int loss = 60 - 2 *
                skill; // Inefficiency is still fine, coal and limestone is abundant
     // Burn stuff that should get charred, leave out the rest
     units::volume total_volume = 0_ml;
     for( const item &i : items ) {
         total_volume += i.volume();
     }
     const itype *char_type = item::find_type( itype_unfinished_cac2 );
     int char_charges = char_type->charges_per_volume( ( 100 - loss ) * total_volume / 100 );
     if( char_charges < 1 ) {
         add_msg( _( "The batch in this furnace is too small to yield usable calcium carbide." ) );
         return;
     }
     //arc furnaces require a huge amount of current, so 1 full storage battery would work as a stand in
     if( you.available_ups() < 1250_kJ ) {
         add_msg( _( "This furnace is ready to be turned on, but you lack a UPS with sufficient power." ) );
         return;
     } else {
         add_msg( _( "This furnace contains %s %s of material, and is ready to be turned on." ),
                  format_volume( total_volume ), volume_units_abbr() );
         if( !query_yn( _( "Turn on the furnace?" ) ) ) {
             return;
         }
     }
     you.consume_ups( 1250_kJ );
     here.i_clear( examp );
     here.furn_set( examp, next_arcfurnace_type );
     item result( "unfinished_cac2", calendar::turn );
     result.charges = char_charges;
     here.add_item( examp, result );
     add_msg( _( "You turn on the furnace." ) );
 }
References _, map::add_item(), add_msg(), Character::available_ups(), string_id< T >::c_str(), item::charges, itype::charges_per_volume(), Character::consume_ups(), debugmsg, item::find_type(), format_volume(), map::furn(), furn_f_arcfurnace_empty, furn_f_arcfurnace_full, map::furn_set(), get_map(), Character::get_skill_level(), map::i_at(), map::i_clear(), int_id< T >::id(), itype_chem_carbide, itype_unfinished_cac2, m_bad, material_cac2powder, string_id< furn_t >::NULL_ID(), query_yn(), skill_fabrication, calendar::turn, and volume_units_abbr().
Referenced by iexamine_functions_from_string().
arcfurnace_full()
void iexamine::arcfurnace_full (Character & you, const tripoint & examp)
Definition at line 3109 of file iexamine.cpp.
 {
     map &here = get_map();
     furn_id cur_arcfurnace_type = here.furn( examp );
     furn_id next_arcfurnace_type = furn_str_id::NULL_ID();
     if( cur_arcfurnace_type == furn_f_arcfurnace_full ) {
         next_arcfurnace_type = furn_f_arcfurnace_empty;
     } else {
         debugmsg( "Examined furniture has action arcfurnace_full, but is of type %s",
                   here.furn( examp ).id().c_str() );
         return;
     }
     map_stack items = here.i_at( examp );
     if( items.empty() ) {
         add_msg( _( "This furnace is empty" ) );
         here.furn_set( examp, next_arcfurnace_type );
         return;
     }
     const itype *char_type = item::find_type( itype_chem_carbide );
     add_msg( _( "There's an arc furnace there." ) );
     const time_duration firing_time = 2_hours; // Arc furnaces work really fast in reality
     const time_duration time_left = firing_time - items.only_item().age();
     if( time_left > 0_turns ) {
         int hours = to_hours<int>( time_left );
         int minutes = to_minutes<int>( time_left ) + 1;
         if( minutes > 60 ) {
             add_msg( n_gettext( "It will finish burning in about %d hour.",
                                 "It will finish burning in about %d hours.",
                                 hours ), hours );
         } else if( minutes > 30 ) {
             add_msg( _( "It will finish burning in less than an hour." ) );
         } else {
             add_msg( n_gettext( "It should take about %d minute to finish burning.",
                                 "It should take about %d minutes to finish burning.",
                                 minutes ), minutes );
         }
         return;
     }
     units::volume total_volume = 0_ml;
     // Burn stuff that should get charred, leave out the rest
     for( auto item_it = items.begin(); item_it != items.end(); ) {
         if( item_it->typeId() == itype_unfinished_cac2 || item_it->typeId() == itype_chem_carbide ) {
             total_volume += item_it->volume();
             item_it = items.erase( item_it );
         } else {
             item_it++;
         }
     }
     item result( "chem_carbide", calendar::turn );
     result.charges = char_type->charges_per_volume( total_volume );
     here.add_item( examp, result );
     here.furn_set( examp, next_arcfurnace_type );
     add_msg( _( "It has finished burning, yielding %d calcium carbide." ), result.charges );
 }
References _, map::add_item(), add_msg(), item::age(), item_stack::begin(), string_id< T >::c_str(), item::charges, itype::charges_per_volume(), debugmsg, item_stack::empty(), item_stack::end(), map_stack::erase(), item::find_type(), map::furn(), furn_f_arcfurnace_empty, furn_f_arcfurnace_full, map::furn_set(), get_map(), map::i_at(), int_id< T >::id(), itype_chem_carbide, itype_unfinished_cac2, n_gettext, string_id< furn_t >::NULL_ID(), item_stack::only_item(), and calendar::turn.
Referenced by iexamine_functions_from_string().
atm()
void iexamine::atm (Character & you, const tripoint & examp)
launches the atm menu class which then handles all the atm interactions.
Definition at line 1016 of file iexamine.cpp.
 {
     atm_menu {you}.start();
 }
Referenced by activity_handlers::atm_do_turn(), and iexamine_functions_from_string().
attunement_altar()
void iexamine::attunement_altar (Character & you, const tripoint & examp)
Definition at line 576 of file iexamine.cpp.
 {
     std::set<trait_id> attunements;
     for( const mutation_branch &mut : mutation_branch::get_all() ) {
         if( mut.flags.count( json_flag_ATTUNEMENT ) ) {
             attunements.emplace( mut.id );
         }
     }
     // remove the attunements the player does not have prereqs for
     for( auto iter = attunements.begin(); iter != attunements.end(); ) {
         bool has_prereq = true;
         // the normal usage of prereqs only needs one, but attunements put all their prereqs into the same array
         // each prereqs is required for it as well
         for( const trait_id &prereq : ( *iter )->prereqs ) {
             if( !you.has_trait( prereq ) ) {
                 has_prereq = false;
                 break;
             }
         }
         if( has_prereq ) {
             ++iter;
         } else {
             iter = attunements.erase( iter );
         }
     }
     if( attunements.empty() ) {
         // the player doesn't have at least two base classes
         you.add_msg_if_player( _( "This altar gives you the creeps." ) );
         return;
     }
     // remove the attunements the player has conflicts for
     for( auto iter = attunements.begin(); iter != attunements.end(); ) {
         if( !you.has_opposite_trait( *iter ) && you.mutation_ok( *iter, true, true, true ) ) {
             ++iter;
         } else {
             iter = attunements.erase( iter );
         }
     }
     if( attunements.empty() ) {
         you.add_msg_if_player( _( "You've attained what you can for now." ) );
         return;
     }
     for( auto iter = attunements.begin(); iter != attunements.end(); ) {
         if( has_attunement_spell_prereqs( you, *iter ) ) {
             ++iter;
         } else {
             iter = attunements.erase( iter );
         }
     }
     if( attunements.empty() ) {
         you.add_msg_if_player( _( "You feel that the altar does not deem you worthy, yet." ) );
         return;
     }
     uilist attunement_list;
     attunement_list.title = _( "Pick an Attunement to show the world your Worth." );
     for( const trait_id &attunement : attunements ) {
         // There's no way for you to have this mutation, so a variant is pointless
         attunement_list.addentry( attunement->name() );
     }
     attunement_list.query();
     if( attunement_list.ret == UILIST_CANCEL ) {
         you.add_msg_if_player( _( "Maybe later." ) );
         return;
     }
     auto attunement_iter = attunements.begin();
     std::advance( attunement_iter, attunement_list.ret );
     const trait_id &attunement = *attunement_iter;
     // There's no way for you to have this mutation, so a variant is pointless
     if( query_yn( string_format( _( "Are you sure you want to pick %s?  This selection is permanent." ),
                                  attunement->name() ) ) ) {
         you.toggle_trait( attunement );
         // There's no way for you to have this mutation, so a variant is pointless
         you.add_msg_if_player( m_info, attunement->desc() );
     } else {
         you.add_msg_if_player( _( "Maybe later." ) );
     }
 }
References _, Character::add_msg_if_player(), uilist::addentry(), mutation_branch::desc(), mutation_branch::get_all(), has_attunement_spell_prereqs(), Character::has_opposite_trait(), Character::has_trait(), json_flag_ATTUNEMENT, m_info, Character::mutation_ok(), mutation_branch::name(), mutation_branch::prereqs, uilist::query(), query_yn(), uilist::ret, string_format(), uilist::title, Character::toggle_trait(), and UILIST_CANCEL.
Referenced by iexamine_functions_from_string().
autoclave_empty()
void iexamine::autoclave_empty (Character & you, const tripoint & examp)
Definition at line 3257 of file iexamine.cpp.
 {
     map &here = get_map();
     furn_id cur_autoclave_type = here.furn( examp );
     furn_id next_autoclave_type = furn_str_id::NULL_ID();
     if( cur_autoclave_type == furn_id( "f_autoclave" ) ) {
         next_autoclave_type = furn_id( "f_autoclave_full" );
     } else {
         debugmsg( "Examined furniture has action autoclave_empty, but is of type %s",
                   here.furn( examp ).id().c_str() );
         return;
     }
     map_stack items = here.i_at( examp );
     bool cbms = std::all_of( items.begin(), items.end(), []( const item & i ) {
         return i.is_bionic();
     } );
     bool filthy_cbms = std::all_of( items.begin(), items.end(), []( const item & i ) {
         return i.is_bionic() && i.has_flag( flag_FILTHY );
     } );
     if( items.empty() ) {
         add_msg( _( "This autoclave is empty" ) );
         return;
     }
     if( !cbms ) {
         add_msg( m_bad,
                  _( "You need to remove all non-CBM items from the autoclave to start the program." ) );
         return;
     }
     if( filthy_cbms ) {
         add_msg( m_bad,
                  _( "Some of those CBMs are filthy, you should wash them first for the sterilization process to work properly." ) );
         return;
     }
     requirement_data reqs = *requirement_data_autoclave;
     if( !reqs.can_make_with_inventory( you.crafting_inventory(), is_crafting_component ) ) {
         popup( "%s", reqs.list_missing() );
         return;
     }
     if( query_yn( _( "Start the autoclave?" ) ) ) {
         for( const auto &e : reqs.get_components() ) {
             you.consume_items( e, 1, is_crafting_component );
         }
         for( const auto &e : reqs.get_tools() ) {
             you.consume_tools( e );
         }
         you.invalidate_crafting_inventory();
         for( item &it : items ) {
             it.set_birthday( calendar::turn );
         }
         here.furn_set( examp, next_autoclave_type );
         add_msg( _( "You start the autoclave." ) );
     }
 }
References _, add_msg(), item_stack::begin(), string_id< T >::c_str(), requirement_data::can_make_with_inventory(), Character::consume_items(), Character::consume_tools(), Character::crafting_inventory(), debugmsg, item_stack::empty(), item_stack::end(), map::furn(), map::furn_set(), requirement_data::get_components(), get_map(), requirement_data::get_tools(), map::i_at(), int_id< T >::id(), Character::invalidate_crafting_inventory(), is_crafting_component(), requirement_data::list_missing(), m_bad, string_id< furn_t >::NULL_ID(), popup(), query_yn(), requirement_data_autoclave, and calendar::turn.
Referenced by iexamine_functions_from_string().
autoclave_full()
void iexamine::autoclave_full (Character & , const tripoint & examp)
Definition at line 3317 of file iexamine.cpp.
 {
     map &here = get_map();
     furn_id cur_autoclave_type = here.furn( examp );
     furn_id next_autoclave_type = furn_str_id::NULL_ID();
     if( cur_autoclave_type == furn_id( "f_autoclave_full" ) ) {
         next_autoclave_type = furn_id( "f_autoclave" );
     } else {
         debugmsg( "Examined furniture has action autoclave_full, but is of type %s",
                   here.furn( examp ).id().c_str() );
         return;
     }
     map_stack items = here.i_at( examp );
     bool cbms = std::all_of( items.begin(), items.end(), []( const item & i ) {
         return i.is_bionic();
     } );
     bool cbms_not_packed = std::all_of( items.begin(), items.end(), []( const item & i ) {
         return i.is_bionic() && i.has_flag( flag_NO_PACKED );
     } );
     if( items.empty() ) {
         add_msg( _( "This autoclave is empty" ) );
         here.furn_set( examp, next_autoclave_type );
         return;
     }
     if( !cbms ) {
         add_msg( m_bad,
                  _( "ERROR Autoclave can't process non CBM items." ) );
         return;
     }
     add_msg( _( "The autoclave is running." ) );
     const item &clock = *items.begin();
     const time_duration Cycle_time = 90_minutes;
     const time_duration time_left = Cycle_time - clock.age();
     if( time_left > 0_turns ) {
         add_msg( _( "The cycle will be complete in %s." ), to_string( time_left ) );
         return;
     }
     here.furn_set( examp, next_autoclave_type );
     for( item &it : items ) {
         if( !it.has_flag( flag_NO_PACKED ) ) {
             it.unset_flag( flag_NO_STERILE );
         }
     }
     add_msg( m_good, _( "The cycle is complete, the CBMs are now sterile." ) );
     if( cbms_not_packed ) {
         add_msg( m_info,
                  _( "CBMs in direct contact with the environment will almost immediately become contaminated." ) );
     }
     here.furn_set( examp, next_autoclave_type );
 }
References _, add_msg(), item::age(), item_stack::begin(), string_id< T >::c_str(), debugmsg, item_stack::empty(), item_stack::end(), flag_NO_PACKED, flag_NO_STERILE, map::furn(), map::furn_set(), get_map(), map::i_at(), int_id< T >::id(), m_bad, m_good, m_info, string_id< furn_t >::NULL_ID(), and to_string().
Referenced by iexamine_functions_from_string().
autodoc()
void iexamine::autodoc (Character & you, const tripoint & examp)
Definition at line 5684 of file iexamine.cpp.
 {
     enum options {
         INSTALL_CBM,
         UNINSTALL_CBM,
         BONESETTING,
         TREAT_WOUNDS,
         RAD_AWAY,
         BLOOD_ANALYSIS,
     };
     bool adjacent_couch = false;
     static avatar null_player;
     tripoint couch_pos;
     Character &patient = player_on_couch( you, examp, null_player, adjacent_couch, couch_pos );
     Character &Operator = operator_present( you, examp, null_player );
     static item null_cyborg;
     item &cyborg = cyborg_on_couch( couch_pos, null_cyborg );
     if( !adjacent_couch ) {
         popup( _( "No connected couches found.  Operation impossible.  Exiting." ) );
         return;
     }
     if( &patient == &null_player ) {
         if( &cyborg != &null_cyborg ) {
             if( cyborg.typeId() == itype_corpse && !cyborg.active ) {
                 popup( _( "Patient is dead.  Please remove corpse to proceed.  Exiting." ) );
                 return;
             } else if( cyborg.typeId() == itype_bot_broken_cyborg ||
                        cyborg.typeId() == itype_corpse ) {
                 popup( _( "ERROR Bionic Level Assessment: FULL CYBORG.  Autodoc Mk. XI can't operate.  Please move patient to appropriate facility.  Exiting." ) );
                 return;
             }
             uilist cmenu;
             cmenu.text = _( "Autodoc Mk. XI.  Status: Online.  Please choose operation." );
             cmenu.addentry( 1, true, 'i', _( "Choose Compact Bionic Module to install." ) );
             cmenu.addentry( 2, true, 'u', _( "Choose installed bionic to uninstall." ) );
             cmenu.query();
             switch( cmenu.ret ) {
                 case 1: {
                     popup( _( "ERROR NO SPACE AVAILABLE.  Operation impossible.  Exiting." ) );
                     break;
                 }
                 case 2: {
                     std::vector<std::string> choice_names;
                     choice_names.emplace_back( _( "Personality_Override" ) );
                     for( size_t i = 0; i < 6; i++ ) {
                         choice_names.emplace_back( _( "C0RR#PTED?D#TA" ) );
                     }
                     int choice_index = uilist( _( "Choose bionic to uninstall" ), choice_names );
                     if( choice_index == 0 ) {
                         g->save_cyborg( &cyborg, couch_pos, you );
                     } else {
                         popup( _( "UNKNOWN COMMAND.  Autodoc Mk. XI. Crashed." ) );
                         return;
                     }
                     break;
                 }
                 default:
                     return;
             }
             return;
         } else {
             popup( _( "No patient found located on the connected couches.  Operation impossible.  Exiting." ) );
             return;
         }
     } else if( patient.activity.id() == ACT_OPERATION ) {
         popup( _( "Operation underway.  Please wait until the end of the current procedure.  Estimated time remaining: %s." ),
                to_string( time_duration::from_moves( patient.activity.moves_left ) ) );
         you.add_msg_if_player( m_info, _( "The Autodoc is working on %s." ), patient.disp_name() );
         return;
     }
     const bool unsafe_usage = &Operator == &null_player || ( &Operator == &you && &patient == &you );
     std::string autodoc_header = _( "Autodoc Mk. XI.  Status: Online.  Please choose operation" );
     if( unsafe_usage ) {
         const std::string &warning_sign = colorize( " /", c_yellow ) + colorize( "!",
                                           c_red ) + colorize( "\\", c_yellow );
         const std::string &warning = warning_sign + colorize( _( " WARNING: Operator missing" ),
                                      c_red ) + warning_sign;
         autodoc_header = warning +
                          _( "\n Using the Autodoc without an operator can lead to <color_light_cyan>serious injuries</color> or <color_light_cyan>death</color>.\n By continuing with the operation you accept the risks and acknowledge that you will not take any legal actions against this facility in case of an accident. " );
     }
     std::vector<item> arm_splints;
     std::vector<item> leg_splints;
     for( const item &supplies : get_map().i_at( examp ) ) {
         if( supplies.typeId() == itype_arm_splint ) {
             arm_splints.push_back( supplies );
         }
         if( supplies.typeId() == itype_leg_splint ) {
             leg_splints.push_back( supplies );
         }
     }
     autodoc_header +=
         string_format(
             _( "\n\n<color_white>Internal supplies:</color>\n Arm splints: %d\n Leg splints: %d" ),
             arm_splints.size(), leg_splints.size() );
     uilist amenu;
     amenu.text = autodoc_header;
     amenu.addentry( INSTALL_CBM, true, 'i', _( "Choose Compact Bionic Module to install" ) );
     amenu.addentry( UNINSTALL_CBM, true, 'u', _( "Choose installed bionic to uninstall" ) );
     amenu.addentry( BONESETTING, true, 's', _( "Splint broken limbs" ) );
     amenu.addentry( TREAT_WOUNDS, true, 'w', _( "Treat wounds" ) );
     amenu.addentry( RAD_AWAY, true, 'r', _( "Check radiation level" ) );
     amenu.addentry( BLOOD_ANALYSIS, true, 'b', _( "Conduct blood analysis" ) );
     amenu.query();
     bool needs_anesthesia = true;
     std::vector<tool_comp> anesth_kit;
     if( patient.has_flag( json_flag_PAIN_IMMUNE ) || patient.has_bionic( bio_painkiller ) ||
         amenu.ret > 1 ) {
         needs_anesthesia = false;
     } else {
         const inventory &crafting_inv = you.crafting_inventory();
         std::vector<const item *> a_filter = crafting_inv.items_with( []( const item & it ) {
             return it.has_quality( qual_ANESTHESIA );
         } );
         for( const item *anesthesia_item : a_filter ) {
             if( anesthesia_item->ammo_remaining() >= 1 ) {
                 anesth_kit.emplace_back( anesthesia_item->typeId(), 1 );
             }
         }
     }
     switch( amenu.ret ) {
         case INSTALL_CBM: {
             item_location bionic = game_menus::inv::install_bionic( you, you, patient );
             if( !bionic ) {
                 return;
             }
             const itype *itemtype = bionic.get_item()->type;
             const std::string bionic_name = bionic.get_item()->typeId().c_str();
             Character &installer = best_installer( you, null_player, itemtype->bionic->difficulty );
             if( &installer == &null_player ) {
                 return;
             }
             std::vector<item_comp> progs;
             bool has_install_program = false;
             std::vector<const item *> install_programs = you.crafting_inventory().items_with( [itemtype](
                         const item & it ) -> bool { return it.typeId() == itemtype->bionic->installation_data; } );
             if( !install_programs.empty() ) {
                 has_install_program = true;
                 progs.emplace_back( install_programs[0]->typeId(), 1 );
             }
             const int weight = units::to_kilogram( patient.bodyweight() ) / 10;
             const int surgery_duration = itemtype->bionic->difficulty * 2;
             const requirement_data req_anesth = *requirement_data_anesthetic *
                                                 surgery_duration * weight;
             if( patient.can_install_bionics( ( *itemtype ), installer, true, has_install_program ? 10 : -1 ) ) {
                 const time_duration duration = itemtype->bionic->difficulty * 20_minutes;
                 patient.introduce_into_anesthesia( duration, installer, needs_anesthesia );
                 bionic.remove_item();
                 if( needs_anesthesia ) {
                     for( const auto &e : req_anesth.get_components() ) {
                         you.consume_items( e, 1, is_crafting_component );
                     }
                     for( const auto &e : req_anesth.get_tools() ) {
                         you.consume_tools( e );
                     }
                     you.invalidate_crafting_inventory();
                 }
                 installer.mod_moves( -to_moves<int>( 1_minutes ) );
                 patient.install_bionics( ( *itemtype ), installer, true, has_install_program ? 10 : -1 );
                 if( has_install_program ) {
                     you.consume_items( progs );
                 }
             }
             break;
         }
         case UNINSTALL_CBM: {
             const bionic_collection &installed_bionics = *patient.my_bionics;
             if( installed_bionics.empty() ) {
                 popup_player_or_npc( patient, _( "You don't have any bionics installed." ),
                                      _( "<npcname> doesn't have any bionics installed." ) );
                 return;
             }
             std::vector<bionic_id> bio_list;
             std::vector<std::string> bionic_names;
             std::vector<const bionic *> bionics;
             for( const bionic &bio : installed_bionics ) {
                 if( item::type_is_defined( bio.info().itype() ) ) {
                     bio_list.emplace_back( bio.id );
                     bionic_names.emplace_back( bio.info().name.translated() );
                     bionics.push_back( &bio );
                 }
             }
             int bionic_index = uilist( _( "Choose bionic to uninstall" ), bionic_names );
             if( bionic_index < 0 ) {
                 return;
             }
             const bionic_id &bid = bio_list[bionic_index];
             const int difficulty =  bid->itype()->bionic->difficulty;
             const float volume_anesth = difficulty * 20 * 2; // 2ml/min
             Character &installer = best_installer( you, null_player, difficulty );
             if( &installer == &null_player ) {
                 return;
             }
             if( patient.can_uninstall_bionic( *bionics[bionic_index], installer, true ) ) {
                 const time_duration duration = difficulty * 20_minutes;
                 patient.introduce_into_anesthesia( duration, installer, needs_anesthesia );
                 if( needs_anesthesia ) {
                     you.consume_tools( anesth_kit, volume_anesth );
                 }
                 installer.mod_moves( -to_moves<int>( 1_minutes ) );
                 patient.uninstall_bionic( *bionics[bionic_index], installer, true );
             }
             break;
         }
         case BONESETTING: {
             if( arm_splints.empty() && leg_splints.empty() ) {
                 popup( _( "Internal supply of splints exhausted.  Operation impossible.  Exiting." ) );
                 return;
             }
             int broken_limbs_count = 0;
             for( const bodypart_id &part :
                  patient.get_all_body_parts( get_body_part_flags::only_main ) ) {
                 const bool broken = patient.is_limb_broken( part );
                 effect &existing_effect = patient.get_effect( effect_mending, part );
                 // Skip part if not broken or already healed 50%
                 if( !broken || ( !existing_effect.is_null() &&
                                  existing_effect.get_duration() >
                                  existing_effect.get_max_duration() - 5_days - 1_turns ) ) {
                     continue;
                 }
                 broken_limbs_count++;
                 patient.mod_moves( -to_moves<int>( 5_seconds ) );
                 // TODO: fail here if unable to perform the action, i.e. can't wear more, trait mismatch.
                 int quantity = 1;
                 if( part == bodypart_id( "arm_l" ) || part == bodypart_id( "arm_r" ) ) {
                     if( !arm_splints.empty() ) {
                         for( const item &it : get_map().use_amount( examp, 1, itype_arm_splint, quantity ) ) {
                             patient.wear_item( it, false );
                         }
                     } else {
                         popup( _( "Internal supply of arm splints exhausted.  Splinting broken arms impossible.  Exiting." ) );
                         continue;
                     }
                 } else if( part == bodypart_id( "leg_l" ) || part == bodypart_id( "leg_r" ) ) {
                     if( !leg_splints.empty() ) {
                         for( const item &it : get_map().use_amount( examp, 1, itype_leg_splint, quantity ) ) {
                             patient.wear_item( it, false );
                         }
                     } else {
                         popup( _( "Internal supply of leg splints exhausted.  Splinting broken legs impossible.  Exiting." ) );
                         continue;
                     }
                 }
                 if( patient.worn_with_flag( flag_SPLINT, part ) ) {
                     patient.add_msg_player_or_npc( m_good, _( "The machine rapidly sets and splints your broken %s." ),
                                                    _( "The machine rapidly sets and splints <npcname>'s broken %s." ),
                                                    body_part_name( part ) );
                     patient.add_effect( effect_mending, 0_turns, part, true );
                     effect &mending_effect = patient.get_effect( effect_mending, part );
                     mending_effect.set_duration( mending_effect.get_max_duration() - 5_days );
                 }
             }
             if( broken_limbs_count == 0 ) {
                 popup_player_or_npc( patient, _( "You have no limbs that require splinting." ),
                                      _( "<npcname> doesn't have limbs that require splinting." ) );
             }
             break;
         }
         case TREAT_WOUNDS: {
             if( !patient.has_effect( effect_bleed ) && !patient.has_effect( effect_infected ) &&
                 !patient.has_effect( effect_bite ) ) {
                 you.add_msg_player_or_npc( m_info, _( "You don't have any wounds that need treatment." ),
                                            _( "<npcname> doesn't have any wounds that need treatment." ) );
                 return;
             }
             if( patient.has_effect( effect_infected ) || patient.has_effect( effect_tetanus ) ) {
                 if( patient.has_effect( effect_strong_antibiotic ) ||
                     patient.has_effect( effect_antibiotic ) ||
                     patient.has_effect( effect_weak_antibiotic ) ) {
                     patient.add_msg_player_or_npc( m_info,
                                                    _( "The Autodoc detected a bacterial infection in your body, but as it also detected you've already taken antibiotics, it decided not to apply another dose right now." ),
                                                    _( "The Autodoc detected a bacterial infection in <npcname>'s body, but as it also detected they've already taken antibiotics, it decided not to apply another dose right now." ) );
                 } else {
                     patient.add_effect( effect_strong_antibiotic, 12_hours );
                     patient.add_effect( effect_strong_antibiotic_visible, rng( 9_hours, 15_hours ) );
                     patient.mod_pain( 3 );
                     patient.add_msg_player_or_npc( m_good,
                                                    _( "The Autodoc detected a bacterial infection in your body and injected antibiotics to treat it." ),
                                                    _( "The Autodoc detected a bacterial infection in <npcname>'s body and injected antibiotics to treat it." ) );
                     if( patient.has_effect( effect_tetanus ) ) {
                         if( one_in( 3 ) ) {
                             patient.remove_effect( effect_tetanus );
                             patient.add_msg_if_player( m_good, _( "The muscle spasms start to go away." ) );
                         } else {
                             patient.add_msg_if_player( m_warning, _( "The medication does nothing to help the spasms." ) );
                         }
                     }
                 }
             }
             for( const bodypart_id &bp_healed :
                  patient.get_all_body_parts( get_body_part_flags::only_main ) ) {
                 if( patient.has_effect( effect_bleed, bp_healed.id() ) ) {
                     patient.remove_effect( effect_bleed, bp_healed );
                     patient.add_msg_player_or_npc( m_good,
                                                    _( "The Autodoc detected ongoing blood loss from your %s and administered you hemostatic drugs to stop it." ),
                                                    _( "The Autodoc detected ongoing blood loss from <npcname>'s %s and administered them hemostatic drugs to stop it." ),
                                                    body_part_name( bp_healed ) );
                 }
                 if( patient.has_effect( effect_bite, bp_healed.id() ) ) {
                     patient.remove_effect( effect_bite, bp_healed );
                     patient.add_msg_player_or_npc( m_good,
                                                    _( "The Autodoc detected an open wound on your %s and applied disinfectant to sterilize it." ),
                                                    _( "The Autodoc detected an open wound on <npcname>'s %s and applied disinfectant to sterilize it." ),
                                                    body_part_name( bp_healed ) );
                     // Fixed disinfectant intensity of 4 disinfectant_power + 10 first aid skill level of Autodoc.
                     const int disinfectant_intensity = 14;
                     patient.add_effect( effect_disinfected, 1_turns, bp_healed );
                     effect &e = patient.get_effect( effect_disinfected, bp_healed );
                     e.set_duration( e.get_int_dur_factor() * disinfectant_intensity );
                     patient.set_part_damage_disinfected( bp_healed,
                                                          patient.get_part_hp_max( bp_healed ) - patient.get_part_hp_cur( bp_healed ) );
                 }
             }
             patient.mod_moves( -to_moves<int>( 5_seconds ) );
             break;
         }
         case RAD_AWAY: {
             patient.mod_moves( -to_moves<int>( 5_seconds ) );
             patient.add_msg_player_or_npc( m_info,
                                            _( "The Autodoc scanned you and detected a radiation level of %d mSv." ),
                                            _( "The Autodoc scanned <npcname> and detected a radiation level of %d mSv." ),
                                            patient.get_rad() );
             if( patient.get_rad() ) {
                 if( patient.has_effect( effect_pblue ) ) {
                     patient.add_msg_player_or_npc( m_info,
                                                    _( "The Autodoc detected an anti-radiation drug in your bloodstream, so it decided not to administer you another dose right now." ),
                                                    _( "The Autodoc detected an anti-radiation drug in <npcname>'s bloodstream, so it decided not to administer them another dose right now." ) );
                 } else {
                     add_msg( m_good,
                              _( "The Autodoc administered an anti-radiation drug to treat radiation poisoning." ) );
                     patient.mod_pain( 3 );
                     patient.add_effect( effect_pblue, 1_hours );
                 }
             }
             if( static_cast<int>( patient.get_leak_level() ) ) {
                 popup( _( "Warning!  Autodoc detected a radiation leak of %d mSv from items in patient's possession.  Urgent decontamination procedures highly recommended." ),
                        static_cast<int>( patient.get_leak_level() ) );
             }
             break;
         }
         case BLOOD_ANALYSIS: {
             patient.mod_moves( -to_moves<int>( 5_seconds ) );
             patient.conduct_blood_analysis();
             patient.add_msg_player_or_npc( m_info,
                                            _( "The Autodoc analyzed your blood." ),
                                            _( "The Autodoc analyzed <npcname>'s blood." ) );
             break;
         }
         default:
             return;
     }
 }
References _, ACT_OPERATION, item::active, Character::activity, Creature::add_effect(), add_msg(), Character::add_msg_if_player(), Character::add_msg_player_or_npc(), uilist::addentry(), best_installer(), bio_painkiller, itype::bionic, body_part_name(), Character::bodyweight(), broken, c_red, c_yellow, Character::can_install_bionics(), Character::can_uninstall_bionic(), colorize(), Character::conduct_blood_analysis(), Character::consume_items(), Character::consume_tools(), Character::crafting_inventory(), cyborg_on_couch(), Character::disp_name(), effect_antibiotic, effect_bite, effect_bleed, effect_disinfected, effect_infected, effect_mending, effect_pblue, effect_strong_antibiotic, effect_strong_antibiotic_visible, effect_tetanus, effect_weak_antibiotic, flag_SPLINT, time_duration::from_moves(), g, Creature::get_all_body_parts(), requirement_data::get_components(), effect::get_duration(), Creature::get_effect(), effect::get_int_dur_factor(), Character::get_leak_level(), get_map(), effect::get_max_duration(), Creature::get_part_hp_cur(), Creature::get_part_hp_max(), Character::get_rad(), requirement_data::get_tools(), Character::has_bionic(), Creature::has_effect(), Character::has_flag(), visitable::has_quality(), player_activity::id(), string_id< T >::id(), game_menus::inv::install_bionic(), Character::install_bionics(), Character::introduce_into_anesthesia(), Character::invalidate_crafting_inventory(), is_crafting_component(), Character::is_limb_broken(), effect::is_null(), visitable::items_with(), bionic_data::itype(), itype_arm_splint, itype_bot_broken_cyborg, itype_corpse, itype_leg_splint, json_flag_PAIN_IMMUNE, m_good, m_info, m_warning, Creature::mod_moves(), Character::mod_pain(), player_activity::moves_left, Character::my_bionics, one_in(), only_main, operator_present(), PATH_INFO::options(), player_on_couch(), popup(), popup_player_or_npc(), qual_ANESTHESIA, uilist::query(), Creature::remove_effect(), requirement_data_anesthetic, uilist::ret, rng(), effect::set_duration(), Creature::set_part_damage_disinfected(), string_format(), uilist::text, units::to_kilogram(), to_string(), item::type_is_defined(), item::typeId(), Character::uninstall_bionic(), Character::wear_item(), and Character::worn_with_flag().
Referenced by bionic_success_chance(), Character::bionics_adjusted_skill(), Character::bionics_pl_skill(), Character::can_install_bionics(), Character::can_uninstall_bionic(), iexamine_functions_from_string(), Character::install_bionics(), activity_handlers::operation_do_turn(), and Character::uninstall_bionic().
bars()
void iexamine::bars (Character & you, const tripoint & examp)
If player has amorphous trait, slip through the bars.
Definition at line 1601 of file iexamine.cpp.
 {
     if( !you.has_trait( trait_AMORPHOUS ) ) {
         none( you, examp );
         return;
     }
     map &here = get_map();
     for( const bodypart_id &bp : you.get_all_body_parts() ) {
         if( you.encumb( bp ) >= 10 ) {
             add_msg( m_info,
                      _( "Your amorphous body could slip though the %s, but your cumbersome gear can't." ),
                      here.tername( examp ) );
             return;
         }
     }
     if( !query_yn( _( "Slip through the %s?" ), here.tername( examp ) ) ) {
         none( you, examp );
         return;
     }
     you.mod_moves( -to_moves<int>( 2_seconds ) );
     add_msg( _( "You slide right between the bars." ) );
     you.setpos( examp );
 }
References _, add_msg(), bp, Character::encumb(), Creature::get_all_body_parts(), get_map(), Character::has_trait(), m_info, Creature::mod_moves(), none, query_yn(), Creature::setpos(), map::tername(), and trait_AMORPHOUS.
Referenced by item::durability_indicator(), and iexamine_functions_from_string().
bulletin_board()
void iexamine::bulletin_board (Character & you, const tripoint & examp)
Definition at line 1971 of file iexamine.cpp.
 {
     g->validate_camps();
     map &here = get_map();
     // TODO: fix point types
     point_abs_omt omt( ms_to_omt_copy( here.getabs( examp.xy() ) ) );
     std::optional<basecamp *> bcp = overmap_buffer.find_camp( omt );
     if( bcp ) {
         basecamp *temp_camp = *bcp;
         temp_camp->validate_bb_pos( here.getabs( examp ) );
         temp_camp->validate_assignees();
         temp_camp->validate_sort_points();
         temp_camp->scan_pseudo_items();
         const std::string title = "Base Missions";
         mission_data mission_key;
         temp_camp->set_by_radio( false );
         temp_camp->get_available_missions( mission_key, here );
         if( talk_function::display_and_choose_opts( mission_key, temp_camp->camp_omt_pos(),
                 "FACTION_CAMP", title ) ) {
             temp_camp->handle_mission( mission_key.cur_key.id );
         }
     } else {
         you.add_msg_if_player( _( "This bulletin board is not inside a camp" ) );
     }
 }
References _, Character::add_msg_if_player(), basecamp::camp_omt_pos(), mission_data::cur_key, talk_function::display_and_choose_opts(), overmapbuffer::find_camp(), g, basecamp::get_available_missions(), get_map(), map::getabs(), basecamp::handle_mission(), mission_entry::id, ms_to_omt_copy(), overmap_buffer, basecamp::scan_pseudo_items(), basecamp::set_by_radio(), music::title, basecamp::validate_assignees(), basecamp::validate_bb_pos(), basecamp::validate_sort_points(), and tripoint::xy().
Referenced by iexamine_functions_from_string().
can_fertilize()
ret_val< void > iexamine::can_fertilize (Character & you, const tripoint & tile, const itype_id & fertilizer)
Definition at line 2745 of file iexamine.cpp.
 {
     map &here = get_map();
     if( !here.has_flag_furn( ter_furn_flag::TFLAG_PLANT, tile ) ) {
         return ret_val<void>::make_failure( _( "Tile isn't a plant" ) );
     }
     if( here.i_at( tile ).size() > 1 ) {
         return ret_val<void>::make_failure( _( "Tile is already fertilized" ) );
     }
     if( ( fertilizer->count_by_charges() && !you.has_charges( fertilizer, 1 ) ) ||
         !you.has_amount( fertilizer, 1 ) ) {
         return ret_val<void>::make_failure(
                    _( "Tried to fertilize with %s, but player doesn't have any." ),
                    fertilizer.c_str() );
     }
     return ret_val<void>::make_success();
 }
References _, string_id< T >::c_str(), itype::count_by_charges(), get_map(), visitable::has_amount(), Character::has_charges(), map::has_flag_furn(), map::i_at(), ret_val< T >::make_failure(), ret_val< T >::make_success(), item_stack::size(), and TFLAG_PLANT.
Referenced by fertilize_plant(), and activity_handlers::fertilize_plot_do_turn().
can_hack()
bool iexamine::can_hack (Character & you)
Definition at line 1383 of file iexamine.cpp.
 {
     if( you.has_trait( trait_ILLITERATE ) ) {
         add_msg( _( "You cannot read!" ) );
         return false;
     }
     item &best_hacking = you.best_item_with_quality( qual_HACK );
     if( best_hacking.is_null() || !item_location{you, &best_hacking}->ammo_sufficient( &you ) ) {
         add_msg( _( "You don't have a hacking tool with enough charges!" ) );
         return false;
     }
     return true;
 }
References _, add_msg(), item::ammo_sufficient(), Character::best_item_with_quality(), Character::has_trait(), item::is_null(), qual_HACK, and trait_ILLITERATE.
Referenced by cardreader_examine_actor::call(), cardreader_foodplace(), pay_gas(), and try_start_hacking().
cardreader()
void iexamine::cardreader (Character & you, const tripoint & examp)
cardreader_foodplace()
void iexamine::cardreader_foodplace (Character & you, const tripoint & examp)
Definition at line 1424 of file iexamine.cpp.
 {
     bool open = false;
     if( ( you.is_wearing( itype_foodperson_mask ) ||
           you.is_wearing( itype_foodperson_mask_on ) ) &&
         query_yn( _( "Press mask on the reader?" ) ) ) {
         you.mod_moves( -100 );
         map &here = get_map();
         for( const tripoint &tmp : here.points_in_radius( examp, 3 ) ) {
             if( here.ter( tmp ) == ter_t_door_metal_locked ) {
                 here.ter_set( tmp, ter_t_door_metal_c );
                 open = true;
             }
         }
         if( open ) {
             add_msg( _( "You press your face on the reader." ) );
             add_msg( m_good, _( "The nearby doors are unlocked." ) );
             sounds::sound( examp, 6, sounds::sound_t::electronic_speech,
                            _( "\"Hello Foodperson.  Welcome home.\"" ), true, "speech", "welcome" );
         } else {
             add_msg( _( "The nearby doors are already unlocked." ) );
             if( query_yn( _( "Lock doors?" ) ) ) {
                 for( const tripoint &tmp : here.points_in_radius( examp, 3 ) ) {
                     if( here.ter( tmp ) == ter_t_door_metal_o || here.ter( tmp ) == ter_t_door_metal_c ) {
                         if( you.pos() == tmp ) {
                             you.add_msg_if_player( m_bad, _( "You are in the way of the door, move before trying again." ) );
                         } else {
                             here.ter_set( tmp, ter_t_door_metal_locked );
                         }
                     }
                 }
             }
         }
     } else if( you.has_amount( itype_foodperson_mask, 1 ) ||
                you.has_amount( itype_foodperson_mask_on, 1 ) ) {
         sounds::sound( examp, 6, sounds::sound_t::electronic_speech,
                        _( "\"FOODPERSON DETECTED.  Please make yourself presentable.\"" ), true,
                        "speech", "welcome" );
     } else {
         sounds::sound( examp, 6, sounds::sound_t::electronic_speech,
                        _( "\"Your face is inadequate.  Please go away.\"" ), true,
                        "speech", "welcome" );
         if( can_hack( you ) && query_yn( _( "Attempt to hack this card-reader?" ) ) ) {
             try_start_hacking( you, examp );
         }
     }
 }
References _, add_msg(), Character::add_msg_if_player(), can_hack(), sounds::electronic_speech, get_map(), visitable::has_amount(), Character::is_wearing(), itype_foodperson_mask, itype_foodperson_mask_on, m_bad, m_good, Creature::mod_moves(), open(), map::points_in_radius(), Creature::pos(), query_yn(), sounds::sound(), map::ter(), map::ter_set(), ter_t_door_metal_c, ter_t_door_metal_locked, ter_t_door_metal_o, and try_start_hacking().
Referenced by iexamine_functions_from_string().
cardreader_robofac()
void iexamine::cardreader_robofac (Character & you, const tripoint & examp)
Definition at line 1410 of file iexamine.cpp.
 {
     itype_id card_type = itype_id_science;
     if( you.has_amount( card_type, 1 ) && query_yn( _( "Swipe your ID card?" ) ) ) {
         you.mod_moves( -100 );
         you.use_amount( card_type, 1 );
         add_msg( m_bad, _( "The card reader short circuits!" ) );
         get_map().ter_set( examp, ter_t_card_reader_broken );
         intercom( you, examp );
     } else {
         add_msg( _( "You have never seen this card reader model before.  Hacking it seems impossible." ) );
     }
 }
References _, add_msg(), get_map(), visitable::has_amount(), intercom(), itype_id_science, m_bad, Creature::mod_moves(), query_yn(), map::ter_set(), ter_t_card_reader_broken, and Character::use_amount().
Referenced by iexamine_functions_from_string().
chainfence()
void iexamine::chainfence (Character & you, const tripoint & examp)
Prompt climbing over fence.
Calculates move cost, applies it to player and moves them.
Definition at line 1513 of file iexamine.cpp.
 {
     // If player is grabbed, trapped, or somehow otherwise movement-impeded, first try to break free
     if( !you.move_effects( false ) ) {
         you.mod_moves( -to_moves<int>( 1_seconds ) );
         return;
     }
     if( you.get_working_arm_count() < 1 ) {
         add_msg( m_info, _( "You can't climb because your arms are too damaged or encumbered." ) );
         return;
     }
     const item_location weapon = you.get_wielded_item();
     if( weapon && weapon->is_two_handed( you ) ) {
         if( query_yn(
                 _( "You can't climb because you have to wield a %s with both hands.\n\nPut it away?" ),
                 weapon->tname() ) ) {
             if( !you.unwield() ) {
                 return;
             }
         } else {
             return;
         }
     }
     // We're not going to do anything if we're already on that point.
     // Also prompt the player before taking an action.
     if( you.pos() == examp || !query_yn( _( "Climb obstacle?" ) ) ) {
         none( you, examp );
         return;
     }
     map &here = get_map();
     int move_cost = 400;
     // TODO: Remove hardcoded trait checks when new arthropod bits happen
     if( here.has_flag( ter_furn_flag::TFLAG_CLIMB_SIMPLE, examp ) ) {
         if( you.has_proficiency( proficiency_prof_parkour ) ) {
             add_msg( _( "You vault over the obstacle with ease." ) );
             move_cost = 100; // Not tall enough to warrant spider-climbing, so only relevant trait.
         } else {
             add_msg( _( "You vault over the obstacle." ) );
             move_cost = 300; // Most common move cost for barricades pre-change.
         }
     } else if( you.has_trait( trait_ARACHNID_ARMS_OK ) &&
                !you.wearing_fitting_on( bodypart_id( "torso" ) ) ) {
         add_msg( _( "Climbing this obstacle is trivial for one such as you." ) );
         move_cost = 75; // Yes, faster than walking.  6-8 limbs are impressive.
     } else if( you.has_trait( trait_INSECT_ARMS_OK ) &&
                !you.wearing_fitting_on( bodypart_id( "torso" ) ) ) {
         add_msg( _( "You quickly scale the fence." ) );
         move_cost = 90;
     } else if( you.has_proficiency( proficiency_prof_parkour ) ) {
         add_msg( _( "This obstacle is no match for your freerunning abilities." ) );
         move_cost = 100;
     } else {
         move_cost = you.has_trait( trait_BADKNEES ) ? 800 : 400;
         if( g->slip_down( game::climb_maneuver::over_obstacle, climbing_aid_furn_CLIMBABLE ) ) {
             you.mod_moves( -move_cost );
             return;
         }
     }
     Character &player_character = get_player_character();
     sfx::play_variant_sound( "plmove", "clear_obstacle",
                              sfx::get_heard_volume( player_character.pos() ) );
     add_msg_debug( debugmode::DF_IEXAMINE,
                    "Move cost to vault: %d, limb score modifier %.1f", move_cost,
                    you.get_modifier( character_modifier_obstacle_climb_mod ) );
     move_cost /= you.get_modifier( character_modifier_obstacle_climb_mod );
     add_msg_debug( debugmode::DF_IEXAMINE,
                    "Final move cost %d", move_cost );
     you.mod_moves( -move_cost );
     if( you.in_vehicle ) {
         here.unboard_vehicle( you.pos() );
     }
     you.setpos( examp );
     if( examp.x < HALF_MAPSIZE_X || examp.y < HALF_MAPSIZE_Y ||
         examp.x >= HALF_MAPSIZE_X + SEEX || examp.y >= HALF_MAPSIZE_Y + SEEY ) {
         if( you.is_avatar() ) {
             g->update_map( you );
         }
     }
 }
References _, add_msg(), add_msg_debug, character_modifier_obstacle_climb_mod, climbing_aid_furn_CLIMBABLE, debugmode::DF_IEXAMINE, g, sfx::get_heard_volume(), get_map(), Character::get_modifier(), get_player_character(), Character::get_wielded_item(), Character::get_working_arm_count(), HALF_MAPSIZE_X, HALF_MAPSIZE_Y, map::has_flag(), Character::has_proficiency(), Character::has_trait(), Character::in_vehicle, Creature::is_avatar(), item::is_two_handed(), m_info, Creature::mod_moves(), Character::move_effects(), none, game::over_obstacle, sfx::play_variant_sound(), Creature::pos(), proficiency_prof_parkour, query_yn(), SEEX, SEEY, Creature::setpos(), TFLAG_CLIMB_SIMPLE, item::tname(), trait_ARACHNID_ARMS_OK, trait_BADKNEES, trait_INSECT_ARMS_OK, map::unboard_vehicle(), Character::unwield(), Character::wearing_fitting_on(), tripoint::x, and tripoint::y.
Referenced by iexamine_functions_from_string().
change_appearance()
void iexamine::change_appearance (Character & you, const tripoint & examp)
Change player eye and skin color.
Definition at line 380 of file iexamine.cpp.
 {
     uilist amenu;
     amenu.title = _( "Change what?" );
     amenu.addentry( 0, true, MENU_AUTOASSIGN, _( "Change eye color" ) );
     amenu.addentry( 1, true, MENU_AUTOASSIGN, _( "Change skin color" ) );
     amenu.query();
     if( amenu.ret == 0 ) {
         you.customize_appearance( customize_appearance_choice::EYES );
     } else if( amenu.ret == 1 ) {
         you.customize_appearance( customize_appearance_choice::SKIN );
     }
 }
References _, uilist::addentry(), Character::customize_appearance(), EYES, MENU_AUTOASSIGN, uilist::query(), uilist::ret, SKIN, and uilist::title.
Referenced by iexamine_functions_from_string().
choose_fertilizer()
itype_id iexamine::choose_fertilizer (Character & you, const std::string & pname, bool ask_player)
Definition at line 2814 of file iexamine.cpp.
 {
     std::vector<item *> f_inv = you.cache_get_items_with( flag_FERTILIZER );
     if( f_inv.empty() ) {
         add_msg( m_info, _( "You have no fertilizer for the %s." ), pname );
         return itype_id();
     }
     std::vector<itype_id> f_types;
     std::vector<std::string> f_names;
     for( const item * const &f : f_inv ) {
         if( std::find( f_types.begin(), f_types.end(), f->typeId() ) == f_types.end() ) {
             f_types.push_back( f->typeId() );
             f_names.push_back( f->tname() );
         }
     }
     if( ask_player && !query_yn( _( "Fertilize the %s" ), pname ) ) {
         return itype_id();
     }
     // Choose fertilizer from list
     int f_index = 0;
     if( f_types.size() > 1 ) {
         f_index = uilist( _( "Use which fertilizer?" ), f_names );
     }
     if( f_index < 0 ) {
         return itype_id();
     }
     return f_types[f_index];
 }
References _, add_msg(), Character::cache_get_items_with(), flag_FERTILIZER, m_info, and query_yn().
Referenced by aggie_plant(), and activity_handlers::fertilize_plot_do_turn().
clear_overgrown()
void iexamine::clear_overgrown (Character & you, const tripoint & examp)
Definition at line 2634 of file iexamine.cpp.
 {
     map &here = get_map();
     if( !here.has_flag_furn( ter_furn_flag::TFLAG_GROWTH_OVERGROWN, examp ) ) {
         debugmsg( "clear_overgrown called on tile which is not an overgrown crop!" );
         return;
     }
     player_activity act( ACT_HARVEST, to_moves<int>( 60_seconds ) );
     you.assign_activity( act );
     here.i_clear( examp );
     here.furn_set( examp, here.furn( examp )->plant->base );
     you.add_msg_if_player( m_neutral,
                            _( "You pull up what's left of the planted crop and trample the rest." ) );
 }
References _, act, ACT_HARVEST, Character::add_msg_if_player(), Character::assign_activity(), debugmsg, map::furn(), map::furn_set(), get_map(), map::has_flag_furn(), map::i_clear(), m_neutral, furn_t::plant, and TFLAG_GROWTH_OVERGROWN.
Referenced by generic_multi_activity_do(), and iexamine_functions_from_string().
compost_empty()
void iexamine::compost_empty (Character & you, const tripoint & examp)
Definition at line 3756 of file iexamine.cpp.
 {
     itype_id compost_type;
     std::string compost_nname;
     bool to_deposit = false;
     static const auto tank_volume = units::from_liter( 1000 );
     bool tank_full = false;
     bool ferment = false;
     bool compost_present = false;
     int charges_on_ground = 0;
     map &here = get_map();
     map_stack items = here.i_at( examp );
     for( auto item_it = items.begin(); item_it != items.end(); ) {
         if( !item_it->is_compostable() || compost_present ) {
             // This isn't a biomass or there was already another kind of biomass inside,
             // so this has to be moved.
             items.insert( *item_it );
             // This will add items to a space near the tank, because it's flagged as NOITEM.
             item_it = items.erase( item_it );
         } else {
             item_it++;
             compost_present = true;
         }
     }
     if( !compost_present ) {
         add_msg( _( "This tank is empty." ) );
         // TODO: Allow using biomass from crafting inventory
         const auto b_inv = you.cache_get_items_with( "is_compostable", &item::is_compostable );
         if( b_inv.empty() ) {
             add_msg( m_info, _( "You have no biomass to ferment." ) );
             return;
         }
         // Make lists of unique typeids and names for the menu
         // Code shamelessly stolen from the crop planting function!
         std::vector<itype_id> b_types;
         std::vector<std::string> b_names;
         for( const item *b : b_inv ) {
             if( std::find( b_types.begin(), b_types.end(), b->typeId() ) == b_types.end() ) {
                 b_types.push_back( b->typeId() );
                 b_names.push_back( item::nname( b->typeId() ) );
             }
         }
         // Choose biomass from list
         int b_index = 0;
         if( b_types.size() > 1 ) {
             b_index = uilist( _( "Use which biomass?" ), b_names );
         } else { //Only one biomass type was in inventory, so it's automatically used
             if( !query_yn( _( "Set %s in the tank?" ), b_names[0] ) ) {
                 b_index = -1;
             }
         }
         if( b_index < 0 ) {
             return;
         }
         to_deposit = true;
         compost_type = b_types[b_index];
         compost_nname = item::nname( compost_type );
     } else {
         item &compost = here.i_at( examp ).only_item();
         compost_type = compost.typeId();
         compost_nname = item::nname( compost_type );
         charges_on_ground = compost.charges;
         add_msg( _( "This tank contains %s (%d), %0.f%% full." ),
                  compost.tname(), compost.charges, compost.volume() * 100.0 / tank_volume );
         enum options { ADD_COMPOST, REMOVE_COMPOST, START_FERMENT };
         uilist selectmenu;
         selectmenu.text = _( "Select an action" );
         selectmenu.addentry( ADD_COMPOST, ( you.charges_of( compost_type ) > 0 ), MENU_AUTOASSIGN,
                              _( "Add more %s to the tank" ), compost_nname );
         selectmenu.addentry( REMOVE_COMPOST, compost.made_of( phase_id::LIQUID ), MENU_AUTOASSIGN,
                              _( "Remove %s from the tank" ), compost.tname() );
         selectmenu.addentry( START_FERMENT, true, MENU_AUTOASSIGN, _( "Start anaerobic digestion" ) );
         selectmenu.query();
         switch( selectmenu.ret ) {
             case ADD_COMPOST: {
                 to_deposit = true;
                 break;
             }
             case REMOVE_COMPOST: {
                 liquid_handler::handle_liquid_from_ground( here.i_at( examp ).begin(), examp );
                 return;
             }
             case START_FERMENT: {
                 ferment = true;
                 break;
             }
             default:
                 add_msg( _( "Never mind." ) );
                 return;
         }
     }
     if( to_deposit ) {
         item compost( compost_type, calendar::turn_zero );
         int charges_held = you.charges_of( compost_type );
         compost.charges = charges_on_ground;
         for( int i = 0; i < charges_held && !tank_full; i++ ) {
             you.use_charges( compost_type, 1 );
             compost.charges++;
             if( compost.volume() >= tank_volume ) {
                 tank_full = true;
             }
         }
         add_msg( _( "Set %s in the tank." ), compost_nname );
         add_msg( _( "The tank now contains %s (%d), %0.f%% full." ),
                  compost.tname(), compost.charges, compost.volume() * 100.0 / tank_volume );
         here.i_clear( examp );
         //This is needed to bypass NOITEM
         here.add_item( examp, compost );
         you.mod_moves( -to_moves<int>( 20_seconds ) );
         if( !tank_full ) {
             ferment = query_yn( _( "Start anaerobic digestion?" ) );
         }
     }
     if( tank_full || ferment ) {
         here.i_at( examp ).only_item().set_age( 0_turns );
         compost_set_full( examp );
         if( tank_full ) {
             add_msg( _( "The tank is full, so you close the lid and start anaerobic digestion." ) );
         } else {
             add_msg( _( "You close the lid and start anaerobic digestion." ) );
         }
         // Set timer for biogas production
         map &here = get_map();
         map_stack items_here = here.i_at( examp );
         item &ferm = *items_here.end();
         ferm.set_birthday( calendar::turn );
     }
 }
References _, map::add_item(), add_msg(), uilist::addentry(), b, item_stack::begin(), Character::cache_get_items_with(), item::charges, Character::charges_of(), compost_set_full(), item_stack::end(), map_stack::erase(), units::from_liter(), get_map(), liquid_handler::handle_liquid_from_ground(), map::i_at(), map::i_clear(), map_stack::insert(), item::is_compostable(), LIQUID, m_info, item::made_of(), MENU_AUTOASSIGN, Creature::mod_moves(), item::nname(), item_stack::only_item(), PATH_INFO::options(), uilist::query(), query_yn(), uilist::ret, item::set_age(), item::set_birthday(), uilist::text, item::tname(), calendar::turn, calendar::turn_zero, item::typeId(), Character::use_charges(), and item::volume().
Referenced by iexamine_functions_from_string().
compost_full()
void iexamine::compost_full (Character & you, const tripoint & examp)
Definition at line 3885 of file iexamine.cpp.
 {
     map &here = get_map();
     map_stack items_here = here.i_at( examp );
     if( items_here.empty() ) {
         debugmsg( "biomass_full was empty!" );
         compost_set_empty( examp );
         return;
     }
     for( item &it : items_here ) {
         if( !it.made_of_from_type( phase_id::LIQUID ) ) {
             add_msg( _( "You remove %s from the tank." ), it.tname() );
             here.add_item_or_charges( you.pos(), it );
             here.i_rem( examp, &it );
         }
     }
     if( items_here.empty() ) {
         compost_set_empty( examp );
         return;
     }
     item &compost_i = *items_here.begin();
     item &ferm = *items_here.end();
     const time_duration last_open_time = ferm.age();
     int fermented_days =  to_days<int>( last_open_time );
     // Biogas generating process starts after one month.
     int gas_gatherable =  fermented_days < 30 ? fermented_days : fermented_days - 30 ;
     int max_gas_gatherable = gas_gatherable < 5 ? gas_gatherable : 5 ;
     // Does the tank contain unfermented biomass, or already fermented liquid?
     if( compost_i.is_compostable() ) {
         add_msg( _( "There's a tank of %s set to ferment there." ), compost_i.tname() );
         // TODO: change compost_time to return time_duration
         const time_duration compost_time = compost_i.composting_time();
         const time_duration progress = compost_i.age();
         if( progress < compost_time ) {
             int hours = to_hours<int>( compost_time - progress );
             int days = to_days<int>( compost_time - progress );
             if( hours < 1 ) {
                 add_msg( _( "It will finish fermenting in less than an hour." ) );
             } else if( days < 1 ) {
                 add_msg( n_gettext( "It will finish fermenting in about %d hour.",
                                     "It will finish fermenting in about %d hours.",
                                     hours ), hours );
             } else {
                 add_msg( n_gettext( "It will finish fermenting in about %d day.",
                                     "It will finish fermenting in about %d days.",
                                     days ), days );
             }
             if( to_days<int>( progress ) >= 30 && gas_gatherable >= 1 ) {
                 if( query_yn( _( "Gather biogas?  Can't stop once releasing started." ) ) ) {
                     const std::map<itype_id, int> results = compost_i.composting_results();
                     const int count = compost_i.count();
                     const time_point gas_birthday = compost_i.birthday();
                     if( !max_gas_gatherable ) {
                         add_msg( _( "No biogas gathered." ) );
                     } else {
                         for( const std::pair<const itype_id, int> &result : results ) {
                             item biogas( result.first, gas_birthday );
                             // 40 L biogas for 1 KG of biomass over the whole anaerobic digestion process.
                             // 1 unit of biomass(0.5 KG) for 80 units(0.25 L for each unit) of biogas.
                             int gas_amount = count * max_gas_gatherable * 80 / 30;
                             if( result.first->phase == phase_id::GAS ) {
                                 if( !you.can_pickVolume_partial( biogas ) ) {
                                     add_msg( _( "You released some biogas from the tank." ) );
                                 } else {
                                     biogas.charges = result.second;
                                     you.i_add_or_drop( biogas, gas_amount );
                                     add_msg( _( "Gathered %s units of biogas." ), gas_amount );
                                 }
                             }
                         }
                     }
                     add_msg( n_gettext( "Biogas generating process started for about %d day.",
                                         "Biogas generating process started for about %d days.",
                                         max_gas_gatherable ), max_gas_gatherable );
                     ferm.set_birthday( calendar::turn );
                 }
             }
             return;
         }
         if( query_yn( _( "Finish fermenting?" ) ) ) {
             const std::map<itype_id, int> results = compost_i.composting_results();
             const int count = compost_i.count();
             const time_point birthday = compost_i.birthday();
             here.i_clear( examp );
             for( const std::pair<const itype_id, int> &result : results ) {
                 int amount = result.second * count;
                 // TODO: Different age based on settings
                 item compost( result.first, birthday );
                 if( result.first->phase == phase_id::LIQUID ) {
                     compost.charges = amount;
                     here.add_item( examp, compost );
                     add_msg( _( "The %s is now ready for use." ), result.first->nname( amount ) );
                 } else if( result.first->phase == phase_id::GAS ) {
                     int gas_amount = count * max_gas_gatherable * 80 / 30;
                     if( !gas_amount || !you.can_pickVolume_partial( compost ) ) {
                         add_msg( _( "You released some biogas from the tank." ) );
                     } else {
                         compost.charges = result.second;
                         you.i_add_or_drop( compost, gas_amount );
                         add_msg( _( "Gathered %s units of biogas." ), gas_amount );
                     }
                 } else {
                     you.i_add_or_drop( compost, amount );
                     add_msg( _( "You removed the %s from the tank." ), result.first->nname( amount ) );
                 }
             }
             you.mod_moves( -to_moves<int>( 5_seconds ) );
             you.practice( skill_chemistry, std::min( to_minutes<int>( compost_time ) / 10, 100 ) );
         }
         if( here.i_at( examp ).empty() ) {
             compost_set_empty( examp );
         }
         return;
     } else {
         add_msg( _( "There's a tank of %s there." ), compost_i.tname() );
     }
     const std::string compost_name = compost_i.tname();
     if( liquid_handler::handle_liquid_from_ground( items_here.begin(), examp ) ) {
         compost_set_empty( examp );
         add_msg( _( "You squeeze the last drops of %s from the tank." ), compost_name );
     }
 }
References _, map::add_item(), map::add_item_or_charges(), add_msg(), item::age(), item_stack::begin(), item::birthday(), Character::can_pickVolume_partial(), item::charges, compost_set_empty(), item::composting_results(), item::composting_time(), item::count(), debugmsg, item_stack::empty(), item_stack::end(), GAS, get_map(), liquid_handler::handle_liquid_from_ground(), Character::i_add_or_drop(), map::i_at(), map::i_clear(), map::i_rem(), item::is_compostable(), LIQUID, min(), Creature::mod_moves(), n_gettext, Creature::pos(), Character::practice(), query_yn(), item::set_birthday(), skill_chemistry, item::tname(), and calendar::turn.
Referenced by activity_handlers::fill_liquid_do_turn(), and iexamine_functions_from_string().
controls_gate()
void iexamine::controls_gate (Character & you, const tripoint & examp)
Open gate.
Definition at line 1374 of file iexamine.cpp.
 {
     if( !query_yn( _( "Use the %s?" ), get_map().tername( examp ) ) ) {
         none( you, examp );
         return;
     }
     g->open_gate( examp );
 }
References _, g, get_map(), none, and query_yn().
Referenced by anonymous_namespace{gates.cpp}::gate_data::check(), and iexamine_functions_from_string().
curtains()
void iexamine::curtains (Character & you, const tripoint & examp)
Definition at line 4868 of file iexamine.cpp.
 {
     map &here = get_map();
     const bool closed_window_with_curtains = here.has_flag(
                 ter_furn_flag::TFLAG_BARRICADABLE_WINDOW_CURTAINS,
                 examp );
     if( here.is_outside( you.pos() ) && ( here.has_flag( ter_furn_flag::TFLAG_WALL, examp ) ||
                                           closed_window_with_curtains ) ) {
         locked_object( you, examp );
         return;
     }
     const ter_id ter = here.ter( examp );
     // Peek through the curtains, or tear them down.
     uilist window_menu;
     window_menu.text = _( "Do what with the curtains?" );
     window_menu.addentry( 0, ( !ter.obj().close &&
                                closed_window_with_curtains ), 'p', _( "Peek through the closed curtains." ) );
     window_menu.addentry( 1, true, 't', _( "Tear down the curtains." ) );
     window_menu.query();
     const int choice = window_menu.ret;
     if( choice == 0 ) {
         // Peek
         g->peek( examp );
         you.add_msg_if_player( _( "You carefully peek through the curtains." ) );
     } else if( choice == 1 ) {
         // Mr. Gorbachev, tear down those curtains!
         if( here.ter( examp )->has_curtains() ) {
             here.ter_set( examp, here.ter( examp )->curtain_transform );
         }
         here.spawn_item( you.pos(), itype_nail, 1, 4, calendar::turn );
         here.spawn_item( you.pos(), itype_sheet, 2, 0, calendar::turn );
         here.spawn_item( you.pos(), itype_stick, 1, 0, calendar::turn );
         here.spawn_item( you.pos(), itype_string_36, 1, 0, calendar::turn );
         you.mod_moves( -to_moves<int>( 10_seconds ) );
         you.add_msg_if_player( _( "You tear the curtains and curtain rod off the windowframe." ) );
     } else {
         you.add_msg_if_player( _( "Never mind." ) );
     }
 }
References _, Character::add_msg_if_player(), uilist::addentry(), ter_t::close, map_data_common_t::curtain_transform, g, get_map(), map_data_common_t::has_curtains(), map::has_flag(), map::is_outside(), itype_nail, itype_sheet, itype_stick, itype_string_36, locked_object(), Creature::mod_moves(), int_id< T >::obj(), Creature::pos(), uilist::query(), uilist::ret, map::spawn_item(), map::ter(), map::ter_set(), uilist::text, TFLAG_BARRICADABLE_WINDOW_CURTAINS, TFLAG_WALL, and calendar::turn.
Referenced by ter_t::check(), vehicle::get_display_of_tile(), and iexamine_functions_from_string().
cvdmachine()
void iexamine::cvdmachine (Character & you, const tripoint & examp)
Pick an appropriate item and apply diamond coating if possible.
Definition at line 337 of file iexamine.cpp.
 {
     // Select an item to which it is possible to apply a diamond coating
     item_location loc = g->inv_map_splice( []( const item & e ) {
         return e.has_edged_damage() &&
                !e.has_flag( flag_DIAMOND ) && !e.has_flag( flag_NO_CVD ) &&
                ( e.made_of( material_steel ) || e.made_of( material_ch_steel ) ||
                  e.made_of( material_hc_steel ) || e.made_of( material_lc_steel ) ||
                  e.made_of( material_mc_steel ) || e.made_of( material_qt_steel ) );
     }, _( "Apply diamond coating" ), 1, _( "You don't have a suitable item to coat with diamond" ) );
     if( !loc ) {
         return;
     }
     // Require materials proportional to selected item volume
     auto qty = loc->volume() / units::legacy_volume_factor;
     qty = std::max( 1, qty );
     requirement_data reqs = *requirement_data_cvd_diamond * qty;
     if( !reqs.can_make_with_inventory( you.crafting_inventory(), is_crafting_component ) ) {
         popup( "%s", reqs.list_missing() );
         return;
     }
     // Consume materials
     for( const auto &e : reqs.get_components() ) {
         you.consume_items( e, 1, is_crafting_component );
     }
     for( const auto &e : reqs.get_tools() ) {
         you.consume_tools( e );
     }
     you.invalidate_crafting_inventory();
     // Apply flag to item
     loc->set_flag( flag_DIAMOND );
     add_msg( m_good, _( "You apply a diamond coating to your %s" ), loc->type_name() );
     you.mod_moves( -to_moves<int>( 10_seconds ) );
 }
References _, add_msg(), requirement_data::can_make_with_inventory(), Character::consume_items(), Character::consume_tools(), Character::crafting_inventory(), flag_DIAMOND, flag_NO_CVD, g, requirement_data::get_components(), requirement_data::get_tools(), item::has_edged_damage(), item::has_flag(), Character::invalidate_crafting_inventory(), is_crafting_component(), units::legacy_volume_factor, requirement_data::list_missing(), m_good, item::made_of(), material_ch_steel, material_hc_steel, material_lc_steel, material_mc_steel, material_qt_steel, material_steel, max(), Creature::mod_moves(), popup(), requirement_data_cvd_diamond, item::set_flag(), item::type_name(), and item::volume().
Referenced by iexamine_functions_from_string().
deployed_furniture()
void iexamine::deployed_furniture (Character & you, const tripoint & pos)
Definition at line 1625 of file iexamine.cpp.
 {
     map &here = get_map();
     tripoint drop_pos = pos;
     if( you.pos().z != pos.z ) {
         drop_pos = you.pos();
         if( !you.query_yn( _( "Pull up the %s?" ), here.furn( pos ).obj().name() ) ) {
             return;
         }
         you.add_msg_if_player( m_info, _( "You pull up the %s." ),
                                here.furn( pos ).obj().name() );
     } else {
         if( !you.query_yn( _( "Take down the %s?" ), here.furn( pos ).obj().name() ) ) {
             return;
         }
         you.add_msg_if_player( m_info, _( "You take down the %s." ),
                                here.furn( pos ).obj().name() );
     }
     const itype_id furn_item = here.furn( pos ).obj().deployed_item;
     here.add_item_or_charges( drop_pos, item( furn_item, calendar::turn ) );
     here.furn_set( pos, furn_str_id::NULL_ID() );
 }
References _, map::add_item_or_charges(), Character::add_msg_if_player(), furn_t::deployed_item, map::furn(), map::furn_set(), get_map(), m_info, map_data_common_t::name(), string_id< furn_t >::NULL_ID(), int_id< T >::obj(), Creature::pos(), math_opers::pos(), Character::query_yn(), calendar::turn, and tripoint::z.
Referenced by iexamine_functions_from_string(), smoker_options(), workbench(), and workbench_internal().
dirtmound()
void iexamine::dirtmound (Character & you, const tripoint & examp)
If it's warm enough, pick one of the player's seeds and plant it.
Definition at line 2541 of file iexamine.cpp.
 {
     if( !warm_enough_to_plant( get_player_character().pos() ) ) {
         add_msg( m_info, _( "It is too cold to plant anything now." ) );
         return;
     }
     map &here = get_map();
     /* ambient_light_at() not working?
     if (here.ambient_light_at(examp) < LIGHT_AMBIENT_LOW) {
         add_msg(m_info, _("It is too dark to plant anything now."));
         return;
     }*/
     std::vector<item *> seed_inv = you.cache_get_items_with( "is_seed", &item::is_seed );
     if( seed_inv.empty() ) {
         add_msg( m_info, _( "You have no seeds to plant." ) );
         return;
     }
     if( !here.i_at( examp ).empty() ) {
         add_msg( _( "Something's lying there" ) );
         return;
     }
     auto seed_entries = get_seed_entries( seed_inv );
     int seed_index = query_seed( seed_entries );
     // Did we cancel?
     if( seed_index < 0 || seed_index >= static_cast<int>( seed_entries.size() ) ) {
         add_msg( _( "You saved your seeds for later." ) );
         return;
     }
     const auto &seed_id = std::get<0>( seed_entries[seed_index] );
     if( !here.has_flag_ter_or_furn( seed_id->seed->required_terrain_flag, examp ) ) {
         add_msg( _( "This type of seed can not be planted in this location." ) );
         return;
     }
     plant_seed( you, examp, seed_id );
 }
References _, add_msg(), Character::cache_get_items_with(), item_stack::empty(), get_map(), get_player_character(), get_seed_entries(), map::has_flag_ter_or_furn(), map::i_at(), item::is_seed(), m_info, plant_seed(), math_opers::pos(), query_seed(), and warm_enough_to_plant().
Referenced by colorized_ter_name_flags_at(), and iexamine_functions_from_string().
door_peephole()
void iexamine::door_peephole (Character & you, const tripoint & examp)
Unlock/open door or attempt to peek through peephole.
Definition at line 2062 of file iexamine.cpp.
 {
     map &here = get_map();
     if( here.is_outside( you.pos() ) ) {
         // if door is a locked type attempt to open
         if( here.has_flag( ter_furn_flag::TFLAG_OPENCLOSE_INSIDE, examp ) ) {
             locked_object( you, examp );
         } else {
             you.add_msg_if_player( _( "You cannot look through the peephole from the outside." ) );
         }
         return;
     }
     // Peek through the peephole, or open the door.
     const int choice = uilist( _( "Do what with the door?" ), {
         _( "Peek through peephole." ),
         _( "Open door." )
     } );
     if( choice == 0 ) {
         // Peek
         g->peek( examp );
         you.add_msg_if_player( _( "You peek through the peephole." ) );
     } else if( choice == 1 ) {
         here.open_door( you, examp, true, false );
         you.add_msg_if_player( _( "You open the door." ) );
     } else {
         you.add_msg_if_player( _( "Never mind." ) );
     }
 }
References _, Character::add_msg_if_player(), g, get_map(), map::has_flag(), map::is_outside(), locked_object(), map::open_door(), Creature::pos(), and TFLAG_OPENCLOSE_INSIDE.
Referenced by iexamine_functions_from_string().
egg_sack_generic()
void iexamine::egg_sack_generic (Character & you, const tripoint & examp, const mtype_id & montype)
elevator()
void iexamine::elevator (Character & you, const tripoint & examp)
Definition at line 1278 of file iexamine.cpp.
 {
     map &here = get_map();
     tripoint_abs_ms const old_abs_pos = you.get_location();
     tripoint_abs_omt const this_omt = project_to<coords::omt>( here.getglobal( examp ) );
     tripoint const sm_orig = here.getlocal( project_to<coords::ms>( this_omt ) );
     std::vector<tripoint> this_elevator;
     for( tripoint const &pos : closest_points_first( examp, SEEX - 1 ) ) {
         if( here.has_flag( ter_furn_flag::TFLAG_ELEVATOR, pos ) ) {
             this_elevator.emplace_back( pos );
         }
     }
     auto const uit = std::find( this_elevator.cbegin(), this_elevator.cend(), you.pos() );
     if( uit == this_elevator.cend() ) {
         popup( _( "You must stand inside the elevator to use it." ) );
         return;
     }
     elevator_vehicles const vehs = _get_vehicles_on_elevator( this_elevator );
     if( vehs.blocking ) {
         popup( string_format( _( "The %s is blocking the elevator" ), vehs.v.front()->name ) );
         return;
     }
     int const movez = _choose_elevator_destz( examp, this_omt, sm_orig ) - uilist_positive;
     if( movez < -OVERMAP_DEPTH ) {
         return;
     }
     tripoint_abs_omt const that_omt( this_omt.xy(), movez );
     int const erot = _get_rot_delta( this_omt, that_omt );
     std::vector<tripoint> that_elevator;
     std::transform( this_elevator.begin(), this_elevator.end(), std::back_inserter( that_elevator ),
     [&erot, &sm_orig, &movez]( tripoint const & p ) {
         return _rotate_point_sm( { p.xy(), movez }, erot, sm_orig );
     } );
     creature_tracker &creatures = get_creature_tracker();
     // first find critters in the destination elevator and move them out of the way
     for( Creature &critter : g->all_creatures() ) {
         tripoint const cr_pos = here.getlocal( critter.get_location() );
         auto const eit = std::find( that_elevator.cbegin(), that_elevator.cend(), cr_pos );
         if( eit != that_elevator.cend() ) {
             for( const tripoint &candidate : closest_points_first( *eit, 10 ) ) {
                 if( !here.has_flag( ter_furn_flag::TFLAG_ELEVATOR, candidate ) &&
                     here.passable( candidate ) &&
                     creatures.creature_at( candidate ) == nullptr ) {
                     critter.setpos( candidate );
                     break;
                 }
             }
         }
     }
     const auto move_item = [&]( map_stack & items, const tripoint & src, const tripoint & dest ) {
         for( auto it = items.begin(); it != items.end(); ) {
             here.add_item_or_charges( dest, *it );
             it = here.i_rem( src, it );
         }
     };
     // move along every item in the elevator
     for( decltype( this_elevator )::size_type i = 0; i < this_elevator.size(); i++ ) {
         tripoint const &src = this_elevator[i];
         map_stack items = here.i_at( src );
         move_item( items, src, that_elevator[i] );
     }
     // move along all creatures on the elevator
     for( Creature &critter : g->all_creatures() ) {
         auto const eit = std::find( this_elevator.cbegin(), this_elevator.cend(), critter.pos() );
         if( eit != this_elevator.cend() ) {
             critter.setpos( that_elevator[ std::distance( this_elevator.cbegin(), eit ) ] );
         }
     }
     for( vehicle *v : vehs.v ) {
         tripoint const p = _rotate_point_sm( { v->global_pos3().xy(), movez }, erot, sm_orig );
         here.displace_vehicle( *v, p - v->global_pos3() );
         v->turn( erot * 90_degrees );
         v->face = tileray( v->turn_dir );
         v->precalc_mounts( 0, v->turn_dir, v->pivot_anchor[0] );
     }
     here.rebuild_vehicle_level_caches();
     if( you.is_avatar() ) {
         g->vertical_shift( movez );
         g->update_map( you, true );
         cata_event_dispatch::avatar_moves( old_abs_pos.raw(), *you.as_avatar(), get_map() );
     }
 }
References _, anonymous_namespace{iexamine.cpp}::_choose_elevator_destz(), anonymous_namespace{iexamine.cpp}::_get_rot_delta(), anonymous_namespace{iexamine.cpp}::_get_vehicles_on_elevator(), closest_points_first(), Creature::get_location(), get_map(), map::getglobal(), map::getlocal(), map::has_flag(), OVERMAP_DEPTH, popup(), Creature::pos(), math_opers::pos(), SEEX, string_format(), TFLAG_ELEVATOR, anonymous_namespace{iexamine.cpp}::uilist_positive, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by anonymous_namespace{iexamine.cpp}::_choose_elevator_destz(), anonymous_namespace{iexamine.cpp}::_get_vehicles_on_elevator(), and iexamine_functions_from_string().
false_and_debugmsg()
bool iexamine::false_and_debugmsg (const tripoint & examp)
Definition at line 316 of file iexamine.cpp.
 {
     debugmsg( "Called false_and_debugmsg on %s - was a terrain with an actor configured incorrectly?",
               get_map().tername( examp ) );
     return false;
 }
References debugmsg, and get_map().
Referenced by iexamine_functions_from_string().
fertilize_plant()
void iexamine::fertilize_plant (Character & you, const tripoint & tile, const itype_id & fertilizer)
Definition at line 2765 of file iexamine.cpp.
 {
     ret_val<void> can_fert = can_fertilize( you, tile, fertilizer );
     if( !can_fert.success() ) {
         debugmsg( can_fert.str() );
         return;
     }
     std::list<item> planted;
     if( fertilizer->count_by_charges() ) {
         planted = you.use_charges( fertilizer, 1 );
     } else {
         planted = you.use_amount( fertilizer, 1 );
     }
     // Reduce the amount of time it takes until the next stage of the plant by
     // 20% of a seasons length. (default 2.8 days).
     const time_duration fertilizerEpoch = calendar::season_length() * 0.2;
     map &here = get_map();
     // Can't use item_stack::only_item() since there might be fertilizer
     map_stack items = here.i_at( tile );
     const map_stack::iterator seed = std::find_if( items.begin(), items.end(), []( const item & it ) {
         return it.is_seed();
     } );
     if( seed == items.end() ) {
         debugmsg( "Missing seed for plant at (%d, %d, %d)", tile.x, tile.y, tile.z );
         here.i_clear( tile );
         here.furn_set( tile, furn_str_id::NULL_ID() );
         return;
     }
     // TODO: item should probably clamp the value on its own
     seed->set_birthday( seed->birthday() - fertilizerEpoch );
     // The plant furniture has the NOITEM token which prevents adding items on that square,
     // spawned items are moved to an adjacent field instead, but the fertilizer token
     // must be on the square of the plant, therefore this hack:
     const furn_id old_furn = here.furn( tile );
     here.furn_set( tile, furn_str_id::NULL_ID() );
     here.spawn_item( tile, itype_fertilizer, 1, 1, calendar::turn );
     here.furn_set( tile, old_furn );
     you.mod_moves( -to_moves<int>( 10_seconds ) );
     //~ %1$s: plant name, %2$s: fertilizer name
     add_msg( m_info, _( "You fertilize the %1$s with the %2$s." ), seed->get_plant_name(),
              planted.front().tname() );
 }
References _, add_msg(), item_stack::begin(), can_fertilize(), itype::count_by_charges(), debugmsg, item_stack::end(), map::furn(), map::furn_set(), get_map(), map::i_at(), map::i_clear(), itype_fertilizer, m_info, Creature::mod_moves(), string_id< furn_t >::NULL_ID(), calendar::season_length(), iuse::seed(), map::spawn_item(), ret_val_common::str(), ret_val_common::success(), calendar::turn, Character::use_amount(), Character::use_charges(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by aggie_plant(), and activity_handlers::fertilize_plot_do_turn().
finite_water_source()
void iexamine::finite_water_source (Character & , const tripoint & examp)
Definition at line 4665 of file iexamine.cpp.
 {
     map_stack items = get_map().i_at( examp );
     for( auto item_it = items.begin(); item_it != items.end(); ++item_it ) {
         if( item_it->made_of( phase_id::LIQUID ) ) {
             liquid_handler::handle_liquid_from_ground( item_it, examp );
             break;
         }
     }
 }
References item_stack::begin(), item_stack::end(), get_map(), liquid_handler::handle_liquid_from_ground(), map::i_at(), and LIQUID.
Referenced by iexamine_functions_from_string().
fireplace()
void iexamine::fireplace (Character & you, const tripoint & examp)
Definition at line 3387 of file iexamine.cpp.
 {
     map &here = get_map();
     const bool already_on_fire = here.has_nearby_fire( examp, 0 );
     const bool furn_is_deployed = !here.furn( examp ).obj().deployed_item.is_empty();
     auto is_firestarter = []( const item & it ) {
         return it.has_flag( flag_FIRESTARTER ) || it.has_flag( flag_FIRE );
     };
     auto is_firequencher = []( const item & it ) {
         return it.damage_melee( STATIC( damage_type_id( "bash" ) ) );
     };
     std::multimap<int, item *> firestarters;
     std::vector<item *> firequenchers = you.items_with( is_firequencher );
     for( item *it : you.items_with( is_firestarter ) ) {
         add_firestarter( it, firestarters, you, examp );
     }
     for( const tripoint &pos : closest_points_first( you.pos(), PICKUP_RANGE ) ) {
         if( pos == examp ) {
             // stuff in the fireplace can't light or quench itself
             continue;
         }
         for( item_location &it : here.items_with( pos, is_firestarter ) ) {
             add_firestarter( &*it, firestarters, you, examp );
         }
         // anything is fine, so only check if we got nothing yet
         if( firequenchers.empty() ) {
             for( item_location &it : here.items_with( pos, is_firequencher ) ) {
                 firequenchers.push_back( &*it );
             }
         }
     }
     const bool has_firestarter = !firestarters.empty();
     const bool has_bionic_firestarter = you.has_bionic( bio_lighter ) &&
                                         you.enough_power_for( bio_lighter );
     uilist selection_menu;
     selection_menu.text = _( "Select an action" );
     if( here.has_items( examp ) ) {
         // Note: This is displayed regardless of whether "examine with pickup" was used
         selection_menu.addentry( 0, true, 'g', _( "Get items" ) );
     }
     if( !already_on_fire ) {
         selection_menu.addentry( 1, has_firestarter, 'f',
                                  has_firestarter ? _( "Start a fire" ) : _( "Start a fire you'll need a fire source." ) );
         if( has_bionic_firestarter ) {
             selection_menu.addentry( 2, true, 'b', _( "Use a CBM to start a fire" ) );
         }
     } else if( !firequenchers.empty() ) {
         selection_menu.addentry( 4, true, 'e', _( "Extinguish fire" ) );
     } else {
         selection_menu.addentry( 4, false, 'e', _( "Extinguish fire (bashing item required)" ) );
     }
     if( furn_is_deployed ) {
         selection_menu.addentry( 3, true, 't', _( "Take down the %s" ), here.furnname( examp ) );
     }
     selection_menu.query();
     switch( selection_menu.ret ) {
         case 0:
             none( you, examp );
             g->pickup( examp );
             return;
         case 1: {
             for( auto &firestarter : firestarters ) {
                 item *it = firestarter.second;
                 const use_function *usef = it->type->get_use( "firestarter" );
                 const firestarter_actor *actor = dynamic_cast<const firestarter_actor *>( usef->get_actor_ptr() );
                 you.add_msg_if_player( _( "You attempt to start a fire with your %s" ), it->tname() );
                 const ret_val<void> can_use = actor->can_use( you, *it, examp );
                 if( can_use.success() ) {
                     const int charges = actor->use( &you, *it, examp ).value_or( 0 );
                     you.use_charges( it->typeId(), charges );
                     return;
                 } else {
                     you.add_msg_if_player( m_bad, can_use.str() );
                 }
             }
             you.add_msg_if_player( _( "You weren't able to start a fire." ) );
             return;
         }
         case 2: {
             if( !here.get_field( examp, fd_fire ) && here.add_field( examp, fd_fire, 1 ) ) {
                 you.mod_power_level( -bio_lighter->power_activate );
                 you.mod_moves( -to_moves<int>( 1_seconds ) );
             } else {
                 you.add_msg_if_player( m_info, _( "You can't light a fire there." ) );
             }
             return;
         }
         case 3: {
             if( already_on_fire ) {
                 if( !query_yn( _( "Really take down the %s while it's on fire?" ), here.furnname( examp ) ) ) {
                     return;
                 }
             }
             you.add_msg_if_player( m_info, _( "You take down the %s." ),
                                    here.furnname( examp ) );
             const itype_id furn_item = here.furn( examp ).obj().deployed_item;
             here.add_item_or_charges( examp, item( furn_item, calendar::turn ) );
             here.furn_set( examp, furn_str_id::NULL_ID() );
             return;
         }
         case 4: {
             here.remove_field( examp, fd_fire );
             you.mod_moves( -200 );
             you.add_msg_if_player( m_info, _( "With a few determined moves you put out the fire in the %s." ),
                                    here.furnname( examp ) );
             return;
         }
         default:
             none( you, examp );
             return;
     }
 }
References _, map::add_field(), add_firestarter(), map::add_item_or_charges(), Character::add_msg_if_player(), uilist::addentry(), bio_lighter, firestarter_actor::can_use(), closest_points_first(), furn_t::deployed_item, Character::enough_power_for(), fd_fire, flag_FIRE, flag_FIRESTARTER, map::furn(), map::furn_set(), map::furnname(), g, use_function::get_actor_ptr(), map::get_field(), get_map(), itype::get_use(), Character::has_bionic(), map::has_items(), map::has_nearby_fire(), string_id< T >::is_empty(), visitable::items_with(), map::items_with(), m_bad, m_info, Creature::mod_moves(), Character::mod_power_level(), none, string_id< furn_t >::NULL_ID(), int_id< T >::obj(), PICKUP_RANGE, Creature::pos(), math_opers::pos(), bionic_data::power_activate, uilist::query(), query_yn(), map::remove_field(), uilist::ret, STATIC, ret_val_common::str(), ret_val_common::success(), uilist::text, item::tname(), calendar::turn, item::type, item::typeId(), firestarter_actor::use(), and Character::use_charges().
Referenced by game::examine(), and iexamine_functions_from_string().
flower_bluebell()
void iexamine::flower_bluebell (Character & you, const tripoint & examp)
flower_cactus()
void iexamine::flower_cactus (Character & you, const tripoint & examp)
Prompt pick cactus pad.
Not safe for player.
Definition at line 2289 of file iexamine.cpp.
 {
     if( dead_plant( true, you, examp ) ) {
         return;
     }
     map &here = get_map();
     if( !query_yn( _( "Pick %s?" ), here.furnname( examp ) ) ) {
         none( you, examp );
         return;
     }
     if( one_in( 6 ) ) {
         add_msg( m_bad, _( "The cactus' nettles sting you!" ) );
         you.apply_damage( nullptr, bodypart_id( "arm_l" ), 4 );
         you.apply_damage( nullptr, bodypart_id( "arm_r" ), 4 );
     }
     here.furn_set( examp, furn_str_id::NULL_ID() );
     iexamine_helper::handle_harvest( you, "cactus_pad", false );
     iexamine_helper::handle_harvest( you, "seed_cactus", false );
 }
References _, add_msg(), Character::apply_damage(), dead_plant(), map::furn_set(), map::furnname(), get_map(), iexamine_helper::handle_harvest(), m_bad, none, string_id< furn_t >::NULL_ID(), one_in(), and query_yn().
Referenced by iexamine_functions_from_string().
flower_dahlia()
void iexamine::flower_dahlia (Character & you, const tripoint & examp)
Dig up its roots or drink its nectar if you can.
Definition at line 2316 of file iexamine.cpp.
 {
     if( dead_plant( true, you, examp ) ) {
         return;
     }
     if( iexamine_helper::drink_nectar( you ) ) {
         return;
     }
     map &here = get_map();
     bool can_get_root = you.has_quality( qual_DIG ) || you.has_trait( trait_BURROW ) ||
                         you.has_trait( trait_BURROWLARGE );
     if( can_get_root ) {
         if( !query_yn( _( "Pick %s?" ), here.furnname( examp ) ) ) {
             none( you, examp );
             return;
         }
     } else {
         if( !query_yn( _( "You don't have a digging tool to dig up roots.  Pick %s anyway?" ),
                        here.furnname( examp ) ) ) {
             none( you, examp );
             return;
         }
     }
     here.furn_set( examp, furn_str_id::NULL_ID() );
     if( can_get_root ) {
         iexamine_helper::handle_harvest( you, "dahlia_root", false );
     }
     iexamine_helper::handle_harvest( you, "seed_dahlia", false );
     iexamine_helper::handle_harvest( you, "withered", false );
     // There was a bud and flower spawn here
     // But those were useless, don't re-add until they get useful
 }
References _, dead_plant(), iexamine_helper::drink_nectar(), map::furn_set(), map::furnname(), get_map(), iexamine_helper::handle_harvest(), Character::has_quality(), Character::has_trait(), none, string_id< furn_t >::NULL_ID(), qual_DIG, query_yn(), trait_BURROW, and trait_BURROWLARGE.
Referenced by iexamine_functions_from_string().
flower_marloss()
void iexamine::flower_marloss (Character & you, const tripoint & examp)
Definition at line 2435 of file iexamine.cpp.
 {
     if( season_of_year( calendar::turn ) == WINTER ) {
         add_msg( m_info, _( "This flower is still alive, despite the harsh conditions" ) );
     }
     map &here = get_map();
     if( can_drink_nectar( you ) ) {
         if( !query_yn( _( "You feel out of place as you explore the %s. Drink?" ),
                        here.furnname( examp ) ) ) {
             return;
         }
         you.mod_moves( -to_moves<int>
                        ( 30_seconds ) ); // Takes 30 seconds, more or less if faster/slower than 100 speed
         add_msg( m_bad, _( "This flower tastes very wrong" ) );
         // If you can drink flowers, you're post-thresh and the Mycus does not want you.
         you.add_effect( effect_teleglow, 10_minutes );
     }
     if( !query_yn( _( "Pick %s?" ), here.furnname( examp ) ) ) {
         none( you, examp );
         return;
     }
     here.furn_set( examp, furn_str_id::NULL_ID() );
     here.spawn_item( you.pos(), itype_marloss_seed, 1, 3, calendar::turn );
     iexamine_helper::handle_harvest( you, "withered", false );
 }
References _, Creature::add_effect(), add_msg(), can_drink_nectar(), effect_teleglow, map::furn_set(), map::furnname(), get_map(), iexamine_helper::handle_harvest(), itype_marloss_seed, m_bad, m_info, Creature::mod_moves(), none, string_id< furn_t >::NULL_ID(), Creature::pos(), query_yn(), season_of_year(), map::spawn_item(), calendar::turn, and WINTER.
Referenced by iexamine_functions_from_string().
flower_poppy()
void iexamine::flower_poppy (Character & you, const tripoint & examp)
Prompt pick (or drink nectar if able) poppy bud.
Not safe for player.
Drinking causes: -25 hunger, +20 sleepiness, pkill2-70 effect and, 1 in 20 pkiller-1 addiction. Picking w/ env_resist < 5 causes 1 in 3 sleep for 12 min and 4 dmg to each leg
Definition at line 2230 of file iexamine.cpp.
 {
     if( dead_plant( true, you, examp ) ) {
         return;
     }
     map &here = get_map();
     // TODO: Get rid of this section and move it to eating
     // Two y/n prompts is just too much
     if( can_drink_nectar( you ) ) {
         if( !query_yn( _( "You feel woozy as you explore the %s. Drink?" ),
                        here.furnname( examp ) ) ) {
             return;
         }
         add_msg( _( "You slowly suck up the nectar." ) );
         item poppy( "poppy_nectar", calendar::turn, 1 );
         you.assign_activity( consume_activity_actor( poppy ) );
         you.mod_sleepiness( 20 );
         you.add_effect( effect_pkill2, 7_minutes );
         // Please drink poppy nectar responsibly.
         if( one_in( 20 ) ) {
             you.add_addiction( STATIC( addiction_id( "opiate" ) ), 1 );
         }
     }
     if( !query_yn( _( "Pick %s?" ), here.furnname( examp ) ) ) {
         none( you, examp );
         return;
     }
     int resist = you.get_env_resist( bodypart_id( "mouth" ) );
     if( resist < 10 ) {
         // Can't smell the flowers with a gas mask on!
         add_msg( m_warning, _( "This flower has a heady aroma." ) );
     }
     weather_sum recentWeather = sum_conditions( calendar::turn - 10_minutes, calendar::turn,
                                 you.get_location() );
     // If it has been raining recently, then this event is twice less likely.
     if( ( ( recentWeather.rain_amount > 1 ) ? one_in( 6 ) : one_in( 3 ) ) && resist < 5 ) {
         // Should user player::infect, but can't!
         // player::infect needs to be restructured to return a bool indicating success.
         add_msg( m_bad, _( "The flower's fragrance makes you extremely drowsy" ) );
         you.fall_asleep( 2_hours );
         add_msg( m_bad, _( "Your legs are covered in the poppy's roots!" ) );
         you.apply_damage( nullptr, bodypart_id( "leg_l" ), 4 );
         you.apply_damage( nullptr, bodypart_id( "leg_r" ), 4 );
         you.mod_moves( -to_moves<int>( 1_seconds ) * 0.5 );
     }
     here.furn_set( examp, furn_str_id::NULL_ID() );
     iexamine_helper::handle_harvest( you, "poppy_bud", false );
     iexamine_helper::handle_harvest( you, "withered", false );
 }
References _, Character::add_addiction(), Creature::add_effect(), add_msg(), Character::apply_damage(), Character::assign_activity(), can_drink_nectar(), dead_plant(), effect_pkill2, Character::fall_asleep(), map::furn_set(), map::furnname(), Character::get_env_resist(), Creature::get_location(), get_map(), iexamine_helper::handle_harvest(), m_bad, m_warning, Creature::mod_moves(), Character::mod_sleepiness(), none, string_id< furn_t >::NULL_ID(), one_in(), query_yn(), weather_sum::rain_amount, STATIC, sum_conditions(), and calendar::turn.
Referenced by iexamine_functions_from_string().
flower_spurge()
void iexamine::flower_spurge (Character & you, const tripoint & examp)
flower_tulip()
void iexamine::flower_tulip (Character & you, const tripoint & examp)
fswitch()
void iexamine::fswitch (Character & you, const tripoint & examp)
Definition at line 2093 of file iexamine.cpp.
 {
     map &here = get_map();
     if( !query_yn( _( "Flip the %s?" ), here.tername( examp ) ) ) {
         none( you, examp );
         return;
     }
     ter_id terid = here.ter( examp );
     you.mod_moves( -to_moves<int>( 1_seconds ) );
     tripoint tmp;
     tmp.z = examp.z;
     for( tmp.y = examp.y; tmp.y <= examp.y + 5; tmp.y++ ) {
         for( tmp.x = 0; tmp.x < MAPSIZE_X; tmp.x++ ) {
             const ter_id &nearby_ter = here.ter( tmp );
             if( terid == ter_t_switch_rg ) {
                 if( nearby_ter == ter_t_rock_red ) {
                     here.ter_set( tmp, ter_t_floor_red );
                 } else if( nearby_ter == ter_t_floor_red ) {
                     here.ter_set( tmp, ter_t_rock_red );
                 } else if( nearby_ter == ter_t_rock_green ) {
                     here.ter_set( tmp, ter_t_floor_green );
                 } else if( nearby_ter == ter_t_floor_green ) {
                     here.ter_set( tmp, ter_t_rock_green );
                 }
             } else if( terid == ter_t_switch_gb ) {
                 if( nearby_ter == ter_t_rock_blue ) {
                     here.ter_set( tmp, ter_t_floor_blue );
                 } else if( nearby_ter == ter_t_floor_blue ) {
                     here.ter_set( tmp, ter_t_rock_blue );
                 } else if( nearby_ter == ter_t_rock_green ) {
                     here.ter_set( tmp, ter_t_floor_green );
                 } else if( nearby_ter == ter_t_floor_green ) {
                     here.ter_set( tmp, ter_t_rock_green );
                 }
             } else if( terid == ter_t_switch_rb ) {
                 if( nearby_ter == ter_t_rock_blue ) {
                     here.ter_set( tmp, ter_t_floor_blue );
                 } else if( nearby_ter == ter_t_floor_blue ) {
                     here.ter_set( tmp, ter_t_rock_blue );
                 } else if( nearby_ter == ter_t_rock_red ) {
                     here.ter_set( tmp, ter_t_floor_red );
                 } else if( nearby_ter == ter_t_floor_red ) {
                     here.ter_set( tmp, ter_t_rock_red );
                 }
             } else if( terid == ter_t_switch_even ) {
                 if( ( tmp.y - examp.y ) % 2 == 1 ) {
                     if( nearby_ter == ter_t_rock_red ) {
                         here.ter_set( tmp, ter_t_floor_red );
                     } else if( nearby_ter == ter_t_floor_red ) {
                         here.ter_set( tmp, ter_t_rock_red );
                     } else if( nearby_ter == ter_t_rock_green ) {
                         here.ter_set( tmp, ter_t_floor_green );
                     } else if( nearby_ter == ter_t_floor_green ) {
                         here.ter_set( tmp, ter_t_rock_green );
                     } else if( nearby_ter == ter_t_rock_blue ) {
                         here.ter_set( tmp, ter_t_floor_blue );
                     } else if( nearby_ter == ter_t_floor_blue ) {
                         here.ter_set( tmp, ter_t_rock_blue );
                     }
                 }
             }
         }
     }
     add_msg( m_warning, _( "You hear the rumble of rock shifting." ) );
     get_timed_events().add( timed_event_type::TEMPLE_SPAWN, calendar::turn + 3_turns );
 }
References _, timed_event_manager::add(), add_msg(), get_map(), get_timed_events(), m_warning, MAPSIZE_X, Creature::mod_moves(), none, query_yn(), TEMPLE_SPAWN, map::ter(), map::ter_set(), ter_t_floor_blue, ter_t_floor_green, ter_t_floor_red, ter_t_rock_blue, ter_t_rock_green, ter_t_rock_red, ter_t_switch_even, ter_t_switch_gb, ter_t_switch_rb, ter_t_switch_rg, map::tername(), calendar::turn, tripoint::x, tripoint::y, and tripoint::z.
Referenced by iexamine_functions_from_string().
fungus()
void iexamine::fungus (Character & you, const tripoint & examp)
Remove furniture.
Add spore effect.
Definition at line 2464 of file iexamine.cpp.
 {
     map &here = get_map();
     add_msg( _( "The %s crumbles into spores!" ), here.furnname( examp ) );
     fungal_effects().create_spores( examp, &you );
     here.furn_set( examp, furn_str_id::NULL_ID() );
     you.mod_moves( -to_moves<int>( 1_seconds ) * 0.5 );
 }
References _, add_msg(), fungal_effects::create_spores(), map::furn_set(), map::furnname(), get_map(), Creature::mod_moves(), and string_id< furn_t >::NULL_ID().
Referenced by colorized_ter_name_flags_at(), mattack::fungus_corporate(), harvest_plant(), iexamine_functions_from_string(), and game::walk_move().
fvat_empty()
void iexamine::fvat_empty (Character & you, const tripoint & examp)
Definition at line 3529 of file iexamine.cpp.
 {
     itype_id brew_type;
     std::string brew_nname;
     bool to_deposit = false;
     static const auto vat_volume = units::from_liter( 50 );
     bool vat_full = false;
     bool ferment = false;
     bool brew_present = false;
     int charges_on_ground = 0;
     map &here = get_map();
     map_stack items = here.i_at( examp );
     for( auto item_it = items.begin(); item_it != items.end(); ) {
         if( !item_it->is_brewable() || brew_present ) {
             // This isn't a brew or there was already another kind of brew inside,
             // so this has to be moved.
             items.insert( *item_it );
             // This will add items to a space near the vat, because it's flagged as NOITEM.
             item_it = items.erase( item_it );
         } else {
             item_it++;
             brew_present = true;
         }
     }
     if( !brew_present ) {
         add_msg( _( "This keg is empty." ) );
         // TODO: Allow using brews from crafting inventory
         const auto b_inv = you.cache_get_items_with( "is_brewable", &item::is_brewable );
         if( b_inv.empty() ) {
             add_msg( m_info, _( "You have no brew to ferment." ) );
             return;
         }
         // Make lists of unique typeids and names for the menu
         // Code shamelessly stolen from the crop planting function!
         std::vector<itype_id> b_types;
         std::vector<std::string> b_names;
         for( const item *b : b_inv ) {
             if( std::find( b_types.begin(), b_types.end(), b->typeId() ) == b_types.end() ) {
                 b_types.push_back( b->typeId() );
                 b_names.push_back( item::nname( b->typeId() ) );
             }
         }
         // Choose brew from list
         int b_index = 0;
         if( b_types.size() > 1 ) {
             b_index = uilist( _( "Use which brew?" ), b_names );
         } else { //Only one brew type was in inventory, so it's automatically used
             if( !query_yn( _( "Set %s in the vat?" ), b_names[0] ) ) {
                 b_index = -1;
             }
         }
         if( b_index < 0 ) {
             return;
         }
         to_deposit = true;
         brew_type = b_types[b_index];
         brew_nname = item::nname( brew_type );
     } else {
         item &brew = here.i_at( examp ).only_item();
         brew_type = brew.typeId();
         brew_nname = item::nname( brew_type );
         charges_on_ground = brew.charges;
         add_msg( _( "This keg contains %s (%d), %0.f%% full." ),
                  brew.tname(), brew.charges, brew.volume() * 100.0 / vat_volume );
         enum options { ADD_BREW, REMOVE_BREW, START_FERMENT };
         uilist selectmenu;
         selectmenu.text = _( "Select an action" );
         selectmenu.addentry( ADD_BREW, ( you.charges_of( brew_type ) > 0 ), MENU_AUTOASSIGN,
                              _( "Add more %s to the vat" ), brew_nname );
         selectmenu.addentry( REMOVE_BREW, brew.made_of( phase_id::LIQUID ), MENU_AUTOASSIGN,
                              _( "Remove %s from the vat" ), brew.tname() );
         selectmenu.addentry( START_FERMENT, true, MENU_AUTOASSIGN, _( "Start fermenting cycle" ) );
         selectmenu.query();
         switch( selectmenu.ret ) {
             case ADD_BREW: {
                 to_deposit = true;
                 break;
             }
             case REMOVE_BREW: {
                 liquid_handler::handle_liquid_from_ground( here.i_at( examp ).begin(), examp );
                 return;
             }
             case START_FERMENT: {
                 ferment = true;
                 break;
             }
             default:
                 add_msg( _( "Never mind." ) );
                 return;
         }
     }
     if( to_deposit ) {
         item brew( brew_type, calendar::turn_zero );
         int charges_held = you.charges_of( brew_type );
         brew.charges = charges_on_ground;
         for( int i = 0; i < charges_held && !vat_full; i++ ) {
             you.use_charges( brew_type, 1 );
             brew.charges++;
             if( brew.volume() >= vat_volume ) {
                 vat_full = true;
             }
         }
         add_msg( _( "Set %s in the vat." ), brew_nname );
         add_msg( _( "The keg now contains %s (%d), %0.f%% full." ),
                  brew.tname(), brew.charges, brew.volume() * 100.0 / vat_volume );
         here.i_clear( examp );
         //This is needed to bypass NOITEM
         here.add_item( examp, brew );
         you.mod_moves( -to_moves<int>( 20_seconds ) );
         if( !vat_full ) {
             ferment = query_yn( _( "Start fermenting cycle?" ) );
         }
     }
     if( vat_full || ferment ) {
         here.i_at( examp ).only_item().set_age( 0_turns );
         fvat_set_full( examp );
         if( vat_full ) {
             add_msg( _( "The vat is full, so you close the lid and start the fermenting cycle." ) );
         } else {
             add_msg( _( "You close the lid and start the fermenting cycle." ) );
         }
     }
 }
References _, map::add_item(), add_msg(), uilist::addentry(), b, item_stack::begin(), Character::cache_get_items_with(), item::charges, Character::charges_of(), item_stack::end(), map_stack::erase(), units::from_liter(), fvat_set_full(), get_map(), liquid_handler::handle_liquid_from_ground(), map::i_at(), map::i_clear(), map_stack::insert(), item::is_brewable(), LIQUID, m_info, item::made_of(), MENU_AUTOASSIGN, Creature::mod_moves(), item::nname(), item_stack::only_item(), PATH_INFO::options(), uilist::query(), query_yn(), uilist::ret, item::set_age(), uilist::text, item::tname(), calendar::turn_zero, item::typeId(), Character::use_charges(), and item::volume().
Referenced by iexamine_functions_from_string().
fvat_full()
void iexamine::fvat_full (Character & you, const tripoint & examp)
Definition at line 3653 of file iexamine.cpp.
 {
     map &here = get_map();
     map_stack items_here = here.i_at( examp );
     if( items_here.empty() ) {
         debugmsg( "fvat_full was empty!" );
         fvat_set_empty( examp );
         return;
     }
     for( item &it : items_here ) {
         if( !it.made_of_from_type( phase_id::LIQUID ) ) {
             add_msg( _( "You remove %s from the vat." ), it.tname() );
             here.add_item_or_charges( you.pos(), it );
             here.i_rem( examp, &it );
         }
     }
     if( items_here.empty() ) {
         fvat_set_empty( examp );
         return;
     }
     item &brew_i = *items_here.begin();
     // Does the vat contain unfermented brew, or already fermented booze?
     // TODO: Allow "recursive brewing" to continue without player having to check on it
     if( brew_i.is_brewable() ) {
         add_msg( _( "There's a vat of %s set to ferment there." ), brew_i.tname() );
         // TODO: change brew_time to return time_duration
         const time_duration brew_time = brew_i.brewing_time();
         const time_duration progress = brew_i.age();
         if( progress < brew_time ) {
             int hours = to_hours<int>( brew_time - progress );
             if( hours < 1 ) {
                 add_msg( _( "It will finish brewing in less than an hour." ) );
             } else {
                 add_msg( n_gettext( "It will finish brewing in about %d hour.",
                                     "It will finish brewing in about %d hours.",
                                     hours ), hours );
             }
             return;
         }
         if( query_yn( _( "Finish brewing?" ) ) ) {
             const std::map<itype_id, int> results = brew_i.brewing_results();
             const int count = brew_i.count();
             const time_point birthday = brew_i.birthday();
             here.i_clear( examp );
             for( const std::pair<const itype_id, int> &result : results ) {
                 int amount = result.second * count;
                 // TODO: Different age based on settings
                 item booze( result.first, birthday );
                 if( result.first->phase == phase_id::LIQUID ) {
                     booze.charges = amount;
                     here.add_item( examp, booze );
                     add_msg( _( "The %s is now ready for bottling." ), result.first->nname( amount ) );
                 } else {
                     you.i_add_or_drop( booze, amount );
                     add_msg( _( "You remove the %s from the vat." ), result.first->nname( amount ) );
                 }
             }
             you.mod_moves( -to_moves<int>( 5_seconds ) );
             you.practice( skill_cooking, std::min( to_minutes<int>( brew_time ) / 10, 100 ) );
         }
         if( here.i_at( examp ).empty() ) {
             fvat_set_empty( examp );
         }
         return;
     } else {
         add_msg( _( "There's a vat of fermented %s there." ), brew_i.tname() );
     }
     const std::string booze_name = brew_i.tname();
     if( liquid_handler::handle_liquid_from_ground( items_here.begin(), examp ) ) {
         fvat_set_empty( examp );
         add_msg( _( "You squeeze the last drops of %s from the vat." ), booze_name );
     }
 }
References _, map::add_item(), map::add_item_or_charges(), add_msg(), item::age(), item_stack::begin(), item::birthday(), item::brewing_results(), item::brewing_time(), item::charges, item::count(), debugmsg, item_stack::empty(), fvat_set_empty(), get_map(), liquid_handler::handle_liquid_from_ground(), Character::i_add_or_drop(), map::i_at(), map::i_clear(), map::i_rem(), item::is_brewable(), LIQUID, min(), Creature::mod_moves(), n_gettext, Creature::pos(), Character::practice(), query_yn(), skill_cooking, and item::tname().
Referenced by activity_handlers::fill_liquid_do_turn(), and iexamine_functions_from_string().
gaspump()
void iexamine::gaspump (Character & you, const tripoint & examp)
Use "gas pump.".
Will pump any liquids on tile.
Note
Dexterity decreases chance of spilling gas from a pump
Note
Dexterity decreases amount of gas spilled, if gas is spilled from pump
Definition at line 523 of file iexamine.cpp.
 {
     map &here = get_map();
     if( !query_yn( _( "Use the %s?" ), here.tername( examp ) ) ) {
         none( you, examp );
         return;
     }
     map_stack items = here.i_at( examp );
     for( auto item_it = items.begin(); item_it != items.end(); ++item_it ) {
         if( item_it->made_of( phase_id::LIQUID ) ) {
             /// @note \EFFECT_DEX decreases chance of spilling gas from a pump
             if( one_in( 10 + you.get_dex() ) ) {
                 add_msg( m_bad, _( "You accidentally spill the %s." ), item_it->type_name() );
                 static const auto max_spill_volume = units::from_liter( 1 );
                 const int max_spill_charges = std::max( 1, item_it->charges_per_volume( max_spill_volume ) );
                 /// @note \EFFECT_DEX decreases amount of gas spilled, if gas is spilled from pump
                 const int qty = rng( 1, max_spill_charges * 8.0 / std::max( 1, you.get_dex() ) );
                 item spill = item_it->split( qty );
                 if( spill.is_null() ) {
                     here.add_item_or_charges( you.pos(), *item_it );
                     items.erase( item_it );
                 } else {
                     here.add_item_or_charges( you.pos(), spill );
                 }
             } else {
                 liquid_handler::handle_liquid_from_ground( item_it, examp, 1 );
             }
             return;
         }
     }
     add_msg( m_info, _( "Out of order." ) );
 }
References _, map::add_item_or_charges(), add_msg(), item_stack::begin(), item_stack::end(), map_stack::erase(), units::from_liter(), Character::get_dex(), get_map(), liquid_handler::handle_liquid_from_ground(), map::i_at(), item::is_null(), LIQUID, m_bad, m_info, max(), none, one_in(), Creature::pos(), query_yn(), rng(), item::split(), and map::tername().
Referenced by activity_handlers::fill_liquid_do_turn(), and iexamine_functions_from_string().
get_harvest_items()
std::list< item > iexamine::get_harvest_items (const itype & type, int plant_count, int seed_count, bool byproducts)
Items that appear when a generic plant is harvested.
Seed islot_seed.
Parameters
type The seed type, must have a itype::seed slot.
plant_count Number of fruits to generate. For charge-based items, this specifies multiples of the default charge.
seed_count Number of seeds to generate.
byproducts If true, byproducts (like straw, withered plants, see islot_seed::byproducts) are included.
Definition at line 2592 of file iexamine.cpp.
 {
     std::list<item> result;
     if( !type.seed ) {
         return result;
     }
     const islot_seed &seed_data = *type.seed;
     // This is a temporary measure, itype should instead provide appropriate accessors
     // to expose data about the seed item to allow harvesting to function.
     const itype_id &seed_type = type.get_id();
     const auto add = [&]( const itype_id & id, const int count ) {
         item new_item( id, calendar::turn );
         if( new_item.count_by_charges() && count > 0 ) {
             new_item.charges *= count;
             new_item.charges /= seed_data.fruit_div;
             if( new_item.charges <= 0 ) {
                 new_item.charges = 1;
             }
             result.push_back( new_item );
         } else if( count > 0 ) {
             result.insert( result.begin(), count, new_item );
         }
     };
     if( seed_data.spawn_seeds ) {
         add( seed_type, seed_count );
     }
     add( seed_data.fruit_id, plant_count );
     if( byproducts ) {
         for( const itype_id &b : seed_data.byproducts ) {
             add( b, 1 );
         }
     }
     return result;
 }
References b, islot_seed::byproducts, item::charges, item::count_by_charges(), islot_seed::fruit_div, islot_seed::fruit_id, int_id< T >::id(), islot_seed::spawn_seeds, and calendar::turn.
Referenced by farm_action(), harvest_plant(), and vehicle::operate_reaper().
get_seed_entries()
std::vector< seed_tuple > iexamine::get_seed_entries (const std::vector< item * > & seed_inv)
Make lists of unique seed types and names for the menu(no multiple hemp seeds etc)
Definition at line 2476 of file iexamine.cpp.
 {
     std::map<itype_id, int> seed_map;
     for( const item *seed : seed_inv ) {
         seed_map[seed->typeId()] += ( seed->charges > 0 ? seed->charges : 1 );
     }
     std::vector<seed_tuple> seed_entries;
     seed_entries.reserve( seed_map.size() );
     for( const auto &pr : seed_map ) {
         seed_entries.emplace_back(
             pr.first, item::nname( pr.first, pr.second ), pr.second );
     }
     // Sort by name
     std::sort( seed_entries.begin(), seed_entries.end(),
     []( const seed_tuple & l, const seed_tuple & r ) {
         return std::get<1>( l ).compare( std::get<1>( r ) ) < 0;
     } );
     return seed_entries;
 }
References item::nname(), and iuse::seed().
Referenced by dirtmound(), plot_options::query_seed(), and vehicle::reload_seeds().
getGasPumpByNumber()
std::optional< tripoint > iexamine::getGasPumpByNumber (const tripoint & p, int number)
Definition at line 5091 of file iexamine.cpp.
 {
     int k = 0;
     map &here = get_map();
     for( const tripoint &tmp : here.points_in_radius( p, 12 ) ) {
         const ter_id t = here.ter( tmp );
         if( ( t == ter_t_gas_pump || t == ter_t_gas_pump_a
               || t == ter_t_diesel_pump || t == ter_t_diesel_pump_a ) && number == k++ ) {
             return tmp;
         }
     }
     return std::nullopt;
 }
References get_map(), map::points_in_radius(), map::ter(), ter_t_diesel_pump, ter_t_diesel_pump_a, ter_t_gas_pump, and ter_t_gas_pump_a.
Referenced by hacking_activity_actor::finish(), and pay_gas().
getNearFilledGasTank()
std::optional< tripoint > iexamine::getNearFilledGasTank (const tripoint & center, int & fuel_units, fuel_station_fuel_type & fuel_type)
Definition at line 4983 of file iexamine.cpp.
 {
     std::optional<tripoint> tank_loc;
     int distance = INT_MAX;
     fuel_units = 0;
     map &here = get_map();
     for( const tripoint &tmp : here.points_in_radius( center, SEEX * 2 ) ) {
         furn_id check_for_fuel_tank = here.furn( tmp );
         if( ( fuel_type == FUEL_TYPE_GASOLINE && check_for_fuel_tank != furn_f_gas_tank ) ||
             ( fuel_type == FUEL_TYPE_DIESEL && check_for_fuel_tank != furn_f_diesel_tank ) ) {
             continue;
         }
         const int new_distance = rl_dist( center, tmp );
         if( new_distance >= distance ) {
             continue;
         }
         if( !tank_loc ) {
             // Return a potentially empty tank, but only if we don't find a closer full one.
             tank_loc.emplace( tmp );
         }
         for( item &k : here.i_at( tmp ) ) {
             if( k.made_of( phase_id::LIQUID ) ) {
                 distance = new_distance;
                 tank_loc.emplace( tmp );
                 fuel_units = k.charges;
                 break;
             }
         }
     }
     return tank_loc;
 }
References center, FUEL_TYPE_DIESEL, FUEL_TYPE_GASOLINE, map::furn(), furn_f_diesel_tank, furn_f_gas_tank, get_map(), map::i_at(), LIQUID, map::points_in_radius(), rl_dist(), and SEEX.
Referenced by hacking_activity_actor::finish(), and pay_gas().
gunsafe_el()
void iexamine::gunsafe_el (Character & you, const tripoint & examp)
Attempt to "hack" the gunsafe's electronic lock and open it.
Definition at line 1816 of file iexamine.cpp.
 {
     if( query_yn( _( "Attempt to hack this safe?" ) ) ) {
         try_start_hacking( you, examp );
     }
 }
References _, query_yn(), and try_start_hacking().
Referenced by get_hack_type(), and iexamine_functions_from_string().
harvest_furn()
void iexamine::harvest_furn (Character & you, const tripoint & examp)
Definition at line 2393 of file iexamine.cpp.
 {
     bool auto_forage = get_option<bool>( "AUTO_FEATURES" ) &&
                        get_option<std::string>( "AUTO_FORAGING" ) == "all";
     if( !auto_forage && !query_pick( you, examp ) ) {
         return;
     }
     you.assign_activity( harvest_activity_actor( examp, auto_forage ) );
 }
References Character::assign_activity(), and query_pick().
Referenced by iexamine_functions_from_string(), game::place_player(), and harvest_activity_actor::start().
harvest_furn_nectar()
void iexamine::harvest_furn_nectar (Character & you, const tripoint & examp)
Definition at line 2383 of file iexamine.cpp.
 {
     bool auto_forage = get_option<bool>( "AUTO_FEATURES" ) &&
                        get_option<std::string>( "AUTO_FORAGING" ) == "all";
     if( !auto_forage && !query_pick( you, examp ) ) {
         return;
     }
     you.assign_activity( harvest_activity_actor( examp, auto_forage ) );
 }
References Character::assign_activity(), and query_pick().
Referenced by iexamine_functions_from_string(), game::place_player(), and harvest_activity_actor::start().
harvest_plant()
void iexamine::harvest_plant (Character & you, const tripoint & examp, bool from_activity)
Actual harvesting of selected plant.
Survival increases number of plants harvested from a seed
Definition at line 2676 of file iexamine.cpp.
 {
     map &here = get_map();
     // Can't use item_stack::only_item() since there might be fertilizer
     map_stack items = here.i_at( examp );
     const map_stack::iterator seed = std::find_if( items.begin(), items.end(), []( const item & it ) {
         return it.is_seed();
     } );
     if( seed == items.end() ) {
         debugmsg( "Missing seed for plant at (%d, %d, %d)", examp.x, examp.y, examp.z );
         here.i_clear( examp );
         here.furn_set( examp, furn_str_id::NULL_ID() );
         return;
     }
     const itype_id &seedType = seed->typeId();
     if( seedType == itype_fungal_seeds ) {
         fungus( you, examp );
         here.i_clear( examp );
     } else if( seedType == itype_marloss_seed ) {
         fungus( you, examp );
         here.i_clear( examp );
         if( you.has_trait( trait_M_DEPENDENT ) && ( you.get_kcal_percent() < 0.8f ||
                 you.get_thirst() > 300 ) ) {
             here.ter_set( examp, ter_t_marloss );
             add_msg( m_info,
                      _( "We have altered this unit's configuration to extract and provide local nutriment.  The Mycus provides." ) );
         } else if( you.has_trait( trait_M_DEFENDER ) || ( ( you.has_trait( trait_M_SPORES ) ||
                    you.has_trait( trait_M_FERTILE ) ) &&
                    one_in( 2 ) ) ) {
             g->place_critter_at( mon_fungal_blossom, examp );
             add_msg( m_info, _( "The seed blooms forth!  We have brought true beauty to this world." ) );
         } else if( you.has_trait( trait_THRESH_MYCUS ) || one_in( 4 ) ) {
             here.furn_set( examp, furn_f_flower_marloss );
             add_msg( m_info, _( "The seed blossoms rather rapidly" ) );
         } else {
             here.furn_set( examp, furn_f_flower_fungal );
             add_msg( m_info, _( "The seed blossoms into a flower-looking fungus." ) );
         }
     } else { // Generic seed, use the seed item data
         const inventory &crafting_inv = you.crafting_inventory();
         if( seed->has_flag( flag_CUT_HARVEST ) && !crafting_inv.has_quality( qual_GRASS_CUT ) ) {
             you.add_msg_if_player( m_info, _( "You will need a grass-cutting tool to harvest this plant." ) );
             return;
         } else {
             const itype &type = *seed->type;
             player_activity act( ACT_HARVEST, to_moves<int>( 60_seconds ) );
             you.assign_activity( act );
             here.i_clear( examp );
             int skillLevel = round( you.get_skill_level( skill_survival ) );
             ///\EFFECT_SURVIVAL increases number of plants harvested from a seed
             int plant_count = rng( skillLevel / 2, skillLevel );
             plant_count *= here.furn( examp )->plant->harvest_multiplier;
             plant_count = std::min( std::max( plant_count, 1 ), 12 );
             int seedCount = std::max( 1, rng( plant_count / 4, plant_count / 2 ) );
             for( item &i : get_harvest_items( type, plant_count, seedCount, true ) ) {
                 if( from_activity ) {
                     i.set_var( "activity_var", you.name );
                 }
                 here.add_item_or_charges( you.pos(), i );
             }
             here.furn_set( examp, furn_str_id( here.furn( examp )->plant->base ) );
             you.add_msg_if_player( m_neutral, _( "You harvest the plant." ) );
         }
     }
 }
References _, act, ACT_HARVEST, map::add_item_or_charges(), add_msg(), Character::add_msg_if_player(), Character::assign_activity(), item_stack::begin(), Character::crafting_inventory(), debugmsg, item_stack::end(), flag_CUT_HARVEST, fungus(), map::furn(), furn_f_flower_fungal, furn_f_flower_marloss, map::furn_set(), g, get_harvest_items(), Character::get_kcal_percent(), get_map(), Character::get_skill_level(), Character::get_thirst(), inventory::has_quality(), Character::has_trait(), map::i_at(), map::i_clear(), itype_fungal_seeds, itype_marloss_seed, m_info, m_neutral, max(), min(), mon_fungal_blossom, Character::name, string_id< furn_t >::NULL_ID(), one_in(), furn_t::plant, Creature::pos(), qual_GRASS_CUT, rng(), round(), iuse::seed(), skill_survival, map::ter_set(), ter_t_marloss, trait_M_DEFENDER, trait_M_DEPENDENT, trait_M_FERTILE, trait_M_SPORES, trait_THRESH_MYCUS, tripoint::x, tripoint::y, and tripoint::z.
Referenced by aggie_plant(), generic_multi_activity_do(), and harvest_plant_ex().
harvest_plant_ex()
void iexamine::harvest_plant_ex (Character & you, const tripoint & examp)
Definition at line 2652 of file iexamine.cpp.
 {
     map &here = get_map();
     // Can't use item_stack::only_item() since there might be fertilizer
     map_stack items = here.i_at( examp );
     const map_stack::iterator seed = std::find_if( items.begin(), items.end(), []( const item & it ) {
         return it.is_seed();
     } );
     if( seed == items.end() ) {
         debugmsg( "Missing seed for plant at (%d, %d, %d)", examp.x, examp.y, examp.z );
         here.i_clear( examp );
         here.furn_set( examp, furn_str_id::NULL_ID() );
         return;
     }
     if( here.has_flag_furn( ter_furn_flag::TFLAG_GROWTH_HARVEST, examp ) ) {
         harvest_plant( you, examp, false );
     }
 }
References item_stack::begin(), debugmsg, item_stack::end(), map::furn_set(), get_map(), harvest_plant(), map::has_flag_furn(), map::i_at(), map::i_clear(), string_id< furn_t >::NULL_ID(), iuse::seed(), TFLAG_GROWTH_HARVEST, tripoint::x, tripoint::y, and tripoint::z.
Referenced by iexamine_functions_from_string(), and game::place_player().
harvest_ter()
void iexamine::harvest_ter (Character & you, const tripoint & examp)
Definition at line 2415 of file iexamine.cpp.
 {
     bool auto_forage = get_option<bool>( "AUTO_FEATURES" ) &&
                        ( get_option<std::string>( "AUTO_FORAGING" ) == "all" ||
                          get_option<std::string>( "AUTO_FORAGING" ) == "trees" );
     if( !auto_forage && !query_pick( you, examp ) ) {
         return;
     }
     you.assign_activity( harvest_activity_actor( examp, auto_forage ) );
 }
References Character::assign_activity(), and query_pick().
Referenced by iexamine_functions_from_string(), and game::place_player().
harvest_ter_nectar()
void iexamine::harvest_ter_nectar (Character & you, const tripoint & examp)
Definition at line 2403 of file iexamine.cpp.
 {
     bool auto_forage = get_option<bool>( "AUTO_FEATURES" ) &&
                        ( get_option<std::string>( "AUTO_FORAGING" ) == "all" ||
                          get_option<std::string>( "AUTO_FORAGING" ) == "bushes" ||
                          get_option<std::string>( "AUTO_FORAGING" ) == "trees" );
     if( !auto_forage && !query_pick( you, examp ) ) {
         return;
     }
     you.assign_activity( harvest_activity_actor( examp, auto_forage ) );
 }
References Character::assign_activity(), and query_pick().
Referenced by iexamine_functions_from_string(), and game::place_player().
harvestable_now()
bool iexamine::harvestable_now (const tripoint & examp)
Definition at line 328 of file iexamine.cpp.
 {
     const harvest_id hid = get_map().get_harvest( examp );
     return !hid->is_null() && !hid->empty();
 }
References harvest_list::empty(), map::get_harvest(), get_map(), and harvest_list::is_null().
Referenced by iexamine_functions_from_string().
harvested_plant()
void iexamine::harvested_plant (Character & you, const tripoint & examp)
Only harvest a plant once per season.
Display message and call iexamine::none.
Definition at line 2429 of file iexamine.cpp.
 {
     you.add_msg_if_player( m_info, _( "Nothing can be harvested from this plant in current season" ) );
     iexamine::none( you, examp );
 }
References _, Character::add_msg_if_player(), m_info, and none().
Referenced by iexamine_functions_from_string().
has_keg()
bool iexamine::has_keg (const tripoint & pos)
Check whether there is a keg on the map that can be filled via pour_into_keg.
Definition at line 4027 of file iexamine.cpp.
 {
     return get_keg_capacity( pos ) > 0_ml;
 }
References get_keg_capacity(), and math_opers::pos().
Referenced by activity_handlers::fill_liquid_do_turn(), and liquid_handler::get_liquid_target().
intercom()
void iexamine::intercom (Character & you, const tripoint & examp)
Definition at line 1472 of file iexamine.cpp.
 {
     const std::vector<npc *> intercom_npcs = g->get_npcs_if( [examp]( const npc & guy ) {
         return guy.myclass == NC_ROBOFAC_INTERCOM && rl_dist( guy.pos(), examp ) < 10;
     } );
     if( intercom_npcs.empty() ) {
         you.add_msg_if_player( m_info, _( "No one responds." ) );
     } else {
         // TODO: This needs to be converted a talker_console or something
         get_avatar().talk_to( get_talker_for( *intercom_npcs.front() ), false );
     }
 }
References _, Character::add_msg_if_player(), g, get_avatar(), get_talker_for(), m_info, npc::myclass, NC_ROBOFAC_INTERCOM, Creature::pos(), rl_dist(), and avatar::talk_to().
Referenced by cardreader_robofac(), and iexamine_functions_from_string().
invalid()
void iexamine::invalid (Character & you, const tripoint & examp)
Definition at line 7322 of file iexamine.cpp.
 {
     debugmsg( "Called invalid iexamine function on %s!", get_map().tername( examp ) );
 }
References debugmsg, and get_map().
Referenced by iexamine_functions_from_string().
keg()
void iexamine::keg (Character & you, const tripoint & examp)
Definition at line 4058 of file iexamine.cpp.
 {
     none( you, examp );
     map &here = get_map();
     const std::string keg_name = here.name( examp );
     const units::volume keg_cap = get_keg_capacity( examp );
     const bool has_container_with_liquid = map_cursor( examp ).has_item_with( []( const item & it ) {
         return !it.is_container_empty() && it.can_unload_liquid();
     } );
     const bool liquid_present = map_cursor( examp ).has_item_with( []( const item & it ) {
         return it.made_of_from_type( phase_id::LIQUID );
     } );
     if( !liquid_present || has_container_with_liquid ) {
         add_msg( m_info, _( "It is empty." ) );
         // Get list of all drinks
         auto drinks_inv = you.items_with( []( const item & it ) {
             return it.made_of( phase_id::LIQUID );
         } );
         if( drinks_inv.empty() ) {
             add_msg( m_info, _( "You don't have any drinks to fill the %s with." ), keg_name );
             return;
         }
         // Make lists of unique drinks... about third time we do this, maybe we ought to make a function next time
         std::vector<itype_id> drink_types;
         std::vector<std::string> drink_names;
         std::vector<double> drink_rot;
         std::vector<time_point> drink_bday;
         for( item *&drink : drinks_inv ) {
             auto found_drink = std::find( drink_types.begin(), drink_types.end(), drink->typeId() );
             if( found_drink == drink_types.end() ) {
                 drink_types.push_back( drink->typeId() );
                 drink_names.push_back( item::nname( drink->typeId() ) );
                 drink_rot.push_back( drink->get_relative_rot() );
                 drink_bday.push_back( drink->birthday() );
             } else {
                 auto rot_iter = std::next( drink_rot.begin(), std::distance( drink_types.begin(), found_drink ) );
                 // Yep, worst rot wins.
                 *rot_iter = std::max( *rot_iter, drink->get_relative_rot() );
             }
         }
         // Choose drink to store in keg from list
         int drink_index = 0;
         if( drink_types.size() > 1 ) {
             drink_index = uilist( _( "Store which drink?" ), drink_names );
             if( drink_index < 0 || static_cast<size_t>( drink_index ) >= drink_types.size() ) {
                 drink_index = -1;
             }
         } else { //Only one drink type was in inventory, so it's automatically used
             if( !query_yn( _( "Fill the %1$s with %2$s?" ),
                            keg_name, drink_names[0].c_str() ) ) {
                 drink_index = -1;
             }
         }
         if( drink_index < 0 ) {
             return;
         }
         // First empty the keg of foreign objects
         displace_items_except_one_liquid( examp );
         //Store liquid chosen in the keg
         itype_id drink_type = drink_types[ drink_index ];
         int charges_held = you.charges_of( drink_type );
         item drink( drink_type, drink_bday[ drink_index ] );
         drink.set_relative_rot( drink_rot[ drink_index ] );
         drink.charges = 0;
         bool keg_full = false;
         Character &player_character = get_player_character();
         for( int i = 0; i < charges_held && !keg_full; i++ ) {
             player_character.use_charges( drink.typeId(), 1 );
             drink.charges++;
             keg_full = drink.volume() >= keg_cap;
         }
         if( keg_full ) {
             add_msg( _( "You completely fill the %1$s with %2$s." ),
                      keg_name, item::nname( drink_type ) );
         } else {
             add_msg( _( "You fill the %1$s with %2$s." ),
                      keg_name, item::nname( drink_type ) );
         }
         you.mod_moves( -to_moves<int>( 10_seconds ) );
         here.i_clear( examp );
         here.add_item( examp, drink );
         return;
     } else {
         // First empty the keg of foreign objects
         displace_items_except_one_liquid( examp );
         map_stack items = here.i_at( examp );
         item &drink = items.only_item();
         const std::string drink_tname = drink.tname();
         const std::string drink_nname = item::nname( drink.typeId() );
         enum options {
             DISPENSE,
             HAVE_A_DRINK,
             REFILL,
         };
         uilist selectmenu;
         //~ $1 - furniture name, $2 - liquid name, $3 - liquid charges, $4 - liquid volume, $5 - liquid capacity
         selectmenu.text = string_format( _( "%1$s with %2$s (%3$d)    %4$s / %5$s" ),
                                          uppercase_first_letter( keg_name ), drink_tname, drink.charges,
                                          vol_to_string( drink.volume(), true, true ), vol_to_string( keg_cap, true, true ) );
         selectmenu.addentry( DISPENSE, drink.made_of( phase_id::LIQUID ), MENU_AUTOASSIGN,
                              _( "Dispense or dump %s" ), drink_tname );
         selectmenu.addentry( HAVE_A_DRINK, drink.is_food() && drink.made_of( phase_id::LIQUID ),
                              MENU_AUTOASSIGN, _( "Have a drink" ) );
         selectmenu.addentry( REFILL, true, MENU_AUTOASSIGN, _( "Refill" ) );
         selectmenu.query();
         switch( selectmenu.ret ) {
             case DISPENSE:
                 if( liquid_handler::handle_liquid_from_ground( items.begin(), examp ) ) {
                     add_msg( _( "You squeeze the last drops of %1$s from the %2$s." ),
                              drink_tname, keg_name );
                 }
                 return;
             case HAVE_A_DRINK:
                 if( !you.can_consume_as_is( drink ) ) {
                     return; // They didn't actually drink
                 }
                 you.assign_activity( consume_activity_actor( drink ) );
                 drink.charges--;
                 if( drink.charges == 0 ) {
                     add_msg( _( "You squeeze the last drops of %1$s from the %2$s." ),
                              drink_tname, keg_name );
                     here.i_clear( examp );
                 }
                 return;
             case REFILL: {
                 if( drink.volume() >= keg_cap ) {
                     add_msg( _( "The %s is completely full." ), keg_name );
                     return;
                 }
                 int charges_held = you.charges_of( drink.typeId() );
                 if( charges_held < 1 ) {
                     add_msg( m_info, _( "You don't have any %1$s to fill the %2$s with." ),
                              drink_nname, keg_name );
                     return;
                 }
                 item tmp( drink.typeId(), calendar::turn, charges_held );
                 pour_into_keg( examp, tmp );
                 you.use_charges( drink.typeId(), charges_held - tmp.charges );
                 add_msg( _( "You fill the %1$s with %2$s." ), keg_name, drink_nname );
                 you.mod_moves( -to_moves<int>( 10_seconds ) );
                 return;
             }
             default:
                 return;
         }
     }
 }
References _, map::add_item(), add_msg(), uilist::addentry(), Character::assign_activity(), item_stack::begin(), Character::can_consume_as_is(), item::can_unload_liquid(), item::charges, Character::charges_of(), displace_items_except_one_liquid(), get_keg_capacity(), get_map(), get_player_character(), liquid_handler::handle_liquid_from_ground(), visitable::has_item_with(), map::i_at(), map::i_clear(), item::is_container_empty(), item::is_food(), visitable::items_with(), LIQUID, m_info, item::made_of(), item::made_of_from_type(), max(), MENU_AUTOASSIGN, Creature::mod_moves(), map::name(), item::nname(), none, item_stack::only_item(), PATH_INFO::options(), pour_into_keg(), uilist::query(), query_yn(), uilist::ret, item::set_relative_rot(), string_format(), uilist::text, item::tname(), calendar::turn, item::typeId(), uppercase_first_letter(), Character::use_charges(), vol_to_string(), and item::volume().
Referenced by inventory::form_from_map(), and iexamine_functions_from_string().
kiln_empty()
void iexamine::kiln_empty (Character & you, const tripoint & examp)
Fabrication decreases loss when firing a kiln
Definition at line 2883 of file iexamine.cpp.
 {
     map &here = get_map();
     furn_id cur_kiln_type = here.furn( examp );
     furn_id next_kiln_type = furn_str_id::NULL_ID();
     if( cur_kiln_type == furn_f_kiln_empty ) {
         next_kiln_type = furn_f_kiln_full;
     } else if( cur_kiln_type == furn_f_kiln_metal_empty ) {
         next_kiln_type = furn_f_kiln_metal_full;
     } else {
         debugmsg( "Examined furniture has action kiln_empty, but is of type %s",
                   here.furn( examp ).id().c_str() );
         return;
     }
     static const std::set<material_id> kilnable{ material_wood, material_bone };
     bool fuel_present = false;
     map_stack items = here.i_at( examp );
     for( const item &i : items ) {
         if( i.typeId() == itype_charcoal ) {
             add_msg( _( "This kiln already contains charcoal." ) );
             add_msg( _( "Remove it before firing the kiln again." ) );
             return;
         } else if( i.made_of_any( kilnable ) ) {
             fuel_present = true;
         } else {
             add_msg( m_bad, _( "This kiln contains %s, which can't be made into charcoal!" ), i.tname( 1,
                      false ) );
             return;
         }
     }
     if( !fuel_present ) {
         add_msg( _( "This kiln is empty.  Fill it with wood or bone and try again." ) );
         return;
     }
     // https://energypedia.info/wiki/Charcoal_Production
     // charcoal has about 25% of the density of wood, and wood pyrolysis produces about 10-15% charcoal by weight for a stone kiln.
     // listed efficiency is for primitive or DIY production, industrial process in a metal kiln is more efficient at 20-25%
     // 100% efficient conversion would be 1kg wood = 0.25kg charcoal, 1:1 volume conversion
     // fabrication should help here as kiln design and how you stack the wood matter to a degree, though the impact is low overall
     // For a cruddy kiln (a pit with a rock chimney) assume 10-15% efficiency, depending on fabrication (40-60% wastage)
     // For a well made kiln (industrial-style metal kiln) assume 20-25% efficiency, depending on fabrication (0-20% wastage)
     ///\EFFECT_FABRICATION decreases loss when firing a kiln
     const float skill = you.get_skill_level( skill_fabrication );
     int loss = 0;
     // if the current kiln is a metal one, use a more efficient conversion rate otherwise default to assuming it is a rock pit kiln
     if( cur_kiln_type == furn_f_kiln_metal_empty ) {
         loss = 20 - 2 * skill;
     } else {
         loss = 60 - 2 * skill;
     }
     // Burn stuff that should get charred, leave out the rest
     units::volume total_volume = 0_ml;
     for( const item &i : items ) {
         total_volume += i.volume();
     }
     const itype *char_type = item::find_type( itype_unfinished_charcoal );
     int char_charges = char_type->charges_per_volume( ( 100 - loss ) * total_volume / 100 );
     if( char_charges < 1 ) {
         add_msg( _( "The batch in this kiln is too small to yield any charcoal." ) );
         return;
     }
     if( !you.has_charges( itype_fire, 1 ) ) {
         add_msg( _( "This kiln is ready to be fired, but you have no fire source." ) );
         return;
     } else {
         add_msg( _( "This kiln contains %s %s of material, and is ready to be fired." ),
                  format_volume( total_volume ), volume_units_abbr() );
         if( !query_yn( _( "Fire the kiln?" ) ) ) {
             return;
         }
     }
     you.use_charges( itype_fire, 1 );
     here.i_clear( examp );
     here.furn_set( examp, next_kiln_type );
     item result( "unfinished_charcoal", calendar::turn );
     result.charges = char_charges;
     here.add_item( examp, result );
     if( you.has_trait( trait_PYROMANIA ) ) {
         you.add_morale( MORALE_PYROMANIA_STARTFIRE, 5, 10, 3_hours, 2_hours );
         you.rem_morale( MORALE_PYROMANIA_NOFIRE );
         you.add_msg_if_player( m_good, _( "You happily light a fire in the charcoal kiln." ) );
     } else {
         add_msg( _( "You fire the charcoal kiln." ) );
     }
 }
References _, map::add_item(), Character::add_morale(), add_msg(), Character::add_msg_if_player(), string_id< T >::c_str(), item::charges, itype::charges_per_volume(), debugmsg, item::find_type(), format_volume(), map::furn(), furn_f_kiln_empty, furn_f_kiln_full, furn_f_kiln_metal_empty, furn_f_kiln_metal_full, map::furn_set(), get_map(), Character::get_skill_level(), Character::has_charges(), Character::has_trait(), map::i_at(), map::i_clear(), int_id< T >::id(), itype_charcoal, itype_fire, itype_unfinished_charcoal, m_bad, m_good, material_bone, material_wood, MORALE_PYROMANIA_NOFIRE, MORALE_PYROMANIA_STARTFIRE, string_id< furn_t >::NULL_ID(), query_yn(), Character::rem_morale(), skill_fabrication, trait_PYROMANIA, calendar::turn, Character::use_charges(), and volume_units_abbr().
Referenced by iexamine_functions_from_string().
kiln_full()
void iexamine::kiln_full (Character & you, const tripoint & examp)
Definition at line 2976 of file iexamine.cpp.
 {
     map &here = get_map();
     furn_id cur_kiln_type = here.furn( examp );
     furn_id next_kiln_type = furn_str_id::NULL_ID();
     if( cur_kiln_type == furn_f_kiln_full ) {
         next_kiln_type = furn_f_kiln_empty;
     } else if( cur_kiln_type == furn_f_kiln_metal_full ) {
         next_kiln_type = furn_f_kiln_metal_empty;
     } else {
         debugmsg( "Examined furniture has action kiln_full, but is of type %s",
                   here.furn( examp ).id().c_str() );
         return;
     }
     map_stack items = here.i_at( examp );
     if( items.empty() ) {
         add_msg( _( "This kiln is empty" ) );
         here.furn_set( examp, next_kiln_type );
         return;
     }
     const itype *char_type = item::find_type( itype_charcoal );
     add_msg( _( "There's a charcoal kiln there." ) );
     const time_duration firing_time =
         24_hours; // internet guides claim about one day for a fairly large pot
     const time_duration time_left = firing_time - items.only_item().age();
     if( time_left > 0_turns ) {
         int hours = to_hours<int>( time_left );
         int minutes = to_minutes<int>( time_left ) + 1;
         if( minutes > 60 ) {
             add_msg( n_gettext( "It will finish burning in about %d hour.",
                                 "It will finish burning in about %d hours.",
                                 hours ), hours );
         } else if( minutes > 30 ) {
             add_msg( _( "It will finish burning in less than an hour." ) );
         } else {
             add_msg( n_gettext( "It should take about %d minute to finish burning.",
                                 "It should take about %d minutes to finish burning.",
                                 minutes ), minutes );
         }
         return;
     }
     units::volume total_volume = 0_ml;
     // Burn stuff that should get charred, leave out the rest
     for( auto item_it = items.begin(); item_it != items.end(); ) {
         if( item_it->typeId() == itype_unfinished_charcoal || item_it->typeId() == itype_charcoal ) {
             total_volume += item_it->volume();
             item_it = items.erase( item_it );
         } else {
             item_it++;
         }
     }
     item result( "charcoal", calendar::turn );
     result.charges = char_type->charges_per_volume( total_volume );
     here.add_item( examp, result );
     here.furn_set( examp, next_kiln_type );
     add_msg( _( "It has finished burning, yielding %d charcoal." ), result.charges );
 }
References _, map::add_item(), add_msg(), item::age(), item_stack::begin(), string_id< T >::c_str(), item::charges, itype::charges_per_volume(), debugmsg, item_stack::empty(), item_stack::end(), map_stack::erase(), item::find_type(), map::furn(), furn_f_kiln_empty, furn_f_kiln_full, furn_f_kiln_metal_empty, furn_f_kiln_metal_full, map::furn_set(), get_map(), map::i_at(), int_id< T >::id(), itype_charcoal, itype_unfinished_charcoal, n_gettext, string_id< furn_t >::NULL_ID(), item_stack::only_item(), and calendar::turn.
Referenced by iexamine_functions_from_string().
ledge()
void iexamine::ledge (Character & you, const tripoint & examp)
Definition at line 5378 of file iexamine.cpp.
 {
     enum ledge_actions {
         ledge_peek_down = 1,
         ledge_jump_across,
         ledge_fall_down,
         ledge_examine_furniture_below,
         ledge_glide,
     };
     map &here = get_map();
     tripoint jump_target( you.posx() + 2 * sgn( examp.x - you.posx() ),
                           you.posy() + 2 * sgn( examp.y - you.posy() ),
                           you.posz() );
     bool jump_target_valid = ( here.ter( jump_target ).obj().trap != tr_ledge );
     point jd( examp.xy() + point( -you.posx(), -you.posy() ) );
     int jump_direction = 0;
     if( jd.y > 0 && jd.x == 0 ) {
         jump_direction = 0; //south
     } else if( jd.y > 0 && jd.x < 0 ) {
         jump_direction = 1; //southwest
     } else if( jd.y == 0 && jd.x < 0 ) {
         jump_direction = 2; //west
     } else if( jd.y < 0 && jd.x < 0 ) {
         jump_direction = 3; //northwest
     } else if( jd.y < 0 && jd.x == 0 ) {
         jump_direction = 4; //north
     } else if( jd.y < 0 && jd.x > 0 ) {
         jump_direction = 5; //northeast
     } else if( jd.y == 0 && jd.x > 0 ) {
         jump_direction = 6; //east
     } else if( jd.y > 0 && jd.x > 0 ) {
         jump_direction = 7; //southeast
     }
     tripoint just_below = examp;
     just_below.z--;
     uilist cmenu;
     cmenu.text = _( "There is a ledge here.  What do you want to do?" );
     // NOTE this menu is merged with the climb down menu, manage keys carefully.
     cmenu.addentry( ledge_peek_down, true, 'p', _( "Peek down." ) );
     g->climb_down_menu_gen( examp, cmenu );
     if( here.has_flag_furn( "EXAMINE_FROM_ABOVE", just_below ) ) {
         cmenu.addentry( ledge_examine_furniture_below, true, 'e',
                         _( "Reach for the %s below." ), here.furn( just_below ).obj().name() );
     }
     cmenu.addentry( ledge_jump_across, jump_target_valid, 'j',
                     ( jump_target_valid ? _( "Jump across." ) : _( "Can't jump across (need a small gap)." ) ) );
     cmenu.addentry( ledge_fall_down, true, 'f', _( "Fall down." ) );
     if( you.has_flag( json_flag_GLIDE ) || you.has_flag( json_flag_WING_GLIDE ) ||
         you.has_bodypart_with_flag( json_flag_WING_ARM ) ) {
         cmenu.addentry( ledge_glide, you.can_fly(), 'g',
                         ( you.can_fly() ? _( "Glide away." ) : _( "You can't glide in your current state" ) ) );
     }
     cmenu.query();
     creature_tracker &creatures = get_creature_tracker();
     if( g->climb_down_menu_pick( examp, cmenu.ret ) ) {
         // This branch means the player chose some option generated by the climb menu.
         return;
     }
     switch( cmenu.ret ) {
         case ledge_jump_across: {
             // If player is grabbed, trapped, or somehow otherwise movement-impeded, first try to break free
             if( !you.move_effects( false ) ) {
                 you.mod_moves( -to_moves<int>( 1_seconds ) );
                 return;
             }
             if( you.get_str() < 4 ) {
                 add_msg( m_warning, _( "You are too weak to jump over an obstacle." ) );
             } else if( 100 * you.weight_carried() / you.weight_capacity() > 25 ) {
                 add_msg( m_warning, _( "You are too burdened to jump over an obstacle." ) );
             } else if( !here.valid_move( examp, jump_target, false, true ) ) {
                 add_msg( m_warning, _( "You cannot jump over an obstacle - something is blocking the way." ) );
             } else if( creatures.creature_at( jump_target ) ) {
                 add_msg( m_warning, _( "You cannot jump over an obstacle - there is %s blocking the way." ),
                          creatures.creature_at( jump_target )->disp_name() );
             } else if( !jump_target_valid ) {
                 add_msg( m_warning, _( "You are not going to jump over an obstacle only to fall down." ) );
             } else {
                 add_msg( m_info, _( "You jump over an obstacle." ) );
                 you.set_activity_level( BRISK_EXERCISE );
                 g->place_player( jump_target );
             }
             break;
         }
         /*case ledge_climb_down: {
             g->climb_down( examp );
             break;
         }*/
         case ledge_peek_down: {
             // Peek
             tripoint where = examp;
             tripoint below = examp;
             below.z--;
             while( here.valid_move( where, below, false, true ) ) {
                 where.z--;
                 below.z--;
             }
             const int height = examp.z - where.z;
             add_msg_debug( debugmode::DF_IEXAMINE, "Ledge height %d", height );
             if( height == 0 ) {
                 you.add_msg_if_player( _( "You can't peek down there." ) );
                 return;
             }
             g->peek( where );
             you.add_msg_if_player( _( "You peek over the ledge." ) );
             break;
         }
         case ledge_examine_furniture_below: {
             // Examine the furniture below.
             here.furn( just_below ).obj().examine( you, just_below );
             break;
         }
         /*case ledge_cling_down: {
             // If player is grabbed, trapped, or somehow otherwise movement-impeded, first try to break free
             if( !you.move_effects( false ) ) {
                 you.mod_moves( -to_moves<int>( 1_seconds ) );
                 return;
             }
             if( !here.valid_move( you.pos(), examp, false, true ) ) {
                 // Covered with something
                 return;
             } else {
                 you.setpos( examp );
                 g->vertical_move( -1, false );
                 if( here.has_flag( ter_furn_flag::TFLAG_DEEP_WATER, you.pos() ) ) {
                     you.set_underwater( true );
                     g->water_affect_items( you );
                     you.add_msg_if_player( _( "You crawl down and dive underwater." ) );
                 }
             }
             break;
         }*/
         case ledge_glide: {
             int glide_distance = 5;
             const weather_manager &weather = get_weather();
             add_msg( m_info, _( "You soar away from the ledge." ) );
             int angledifference = std::abs( weather.winddirection - jump_direction * 45 );
             // Handle cases where the difference wraps around due to compass directions
             angledifference = std::min( angledifference, 360 - angledifference );
             if( angledifference <= 45 && weather.windspeed >= 12 ) {
                 add_msg( m_warning, _( "Your glide is aided by a tailwind." ) );
                 glide_distance += 1;
             }
             // Check if the directions are greater than 135 degrees apart
             else if( angledifference >= 135 && weather.windspeed >= 12 ) {
                 add_msg( m_warning, _( "Your glide is hindered by a headwind." ) );
                 glide_distance -= 1;
             }
             if( jump_direction == 1 || jump_direction == 3 || jump_direction == 5 || jump_direction == 7 ) {
                 glide_distance = std::round( 0.7 * glide_distance );
             }
             you.as_avatar()->grab( object_type::NONE );
             glide_activity_actor glide( &you, jump_direction, glide_distance );
             you.remove_effect( effect_bouldering );
             you.assign_activity( glide );
             you.add_effect( effect_gliding, 1_turns, true );
             you.setpos( examp );
             break;
         }
         case ledge_fall_down: {
             if( query_yn( _( "Climbing might be safer.  Really fall from the ledge?" ) ) ) {
                 you.mod_moves( -to_moves<int>( 1_seconds ) );
                 // If player is grabbed, trapped, or somehow otherwise movement-impeded, first try to break free
                 if( !you.move_effects( false ) ) {
                     return;
                 }
                 // Step into open air, then fall...
                 if( you.has_effect_with_flag( json_flag_LEVITATION ) ) {
                     you.add_effect( effect_slow_descent, 1_seconds, false );
                 }
                 you.setpos( examp );
                 you.gravity_check();
             } else {
                 // Just to highlight the trepidation
                 popup( _( "You decided to step back from the ledge." ) );
             }
             break;
         }
         default:
             popup( _( "You decided to step back from the ledge." ) );
             break;
     }
 }
References _, abs(), Creature::add_effect(), add_msg(), add_msg_debug, Character::add_msg_if_player(), uilist::addentry(), Creature::as_avatar(), Character::assign_activity(), below, BRISK_EXERCISE, Character::can_fly(), creature_tracker::creature_at(), debugmode::DF_IEXAMINE, effect_bouldering, effect_gliding, effect_slow_descent, map_data_common_t::examine(), map::furn(), g, get_creature_tracker(), get_map(), Character::get_str(), get_weather(), avatar::grab(), Character::gravity_check(), Character::has_bodypart_with_flag(), Creature::has_effect_with_flag(), Character::has_flag(), map::has_flag_furn(), json_flag_GLIDE, json_flag_LEVITATION, json_flag_WING_ARM, json_flag_WING_GLIDE, m_info, m_warning, min(), Creature::mod_moves(), Character::move_effects(), map_data_common_t::name(), NONE, int_id< T >::obj(), popup(), Creature::posx(), Creature::posy(), Creature::posz(), uilist::query(), query_yn(), Creature::remove_effect(), uilist::ret, round(), Character::set_activity_level(), Creature::setpos(), sgn(), map::ter(), uilist::text, tr_ledge, ter_t::trap, map::valid_move(), Character::weight_capacity(), Character::weight_carried(), point::x, tripoint::x, tripoint::xy(), point::y, tripoint::y, and tripoint::z.
Referenced by iexamine_functions_from_string(), and game::walk_move().
locked_object()
void iexamine::locked_object (Character & you, const tripoint & examp)
Checks whether PC has a crowbar then calls iuse.crowbar.
Definition at line 1826 of file iexamine.cpp.
 {
     map &here = get_map();
     item &best_prying = you.best_item_with_quality( qual_PRY );
     item &best_lockpick = you.best_item_with_quality( qual_LOCKPICK );
     optional_vpart_position veh = here.veh_at( examp );
     int locked_part = -1;
     // Check if the locked thing is a lockable door part.
     if( veh ) {
         std::vector<vehicle_part *> parts_at_target = veh->vehicle().get_parts_at(
                     examp, "LOCKABLE_DOOR", part_status_flag::available );
         if( !parts_at_target.empty() ) {
             locked_part = veh->vehicle().next_part_to_unlock(
                               veh->vehicle().index_of_part( parts_at_target.front() ) );
         }
     }
     const std::string target_name = here.has_furn( examp ) ? here.furnname( examp ) :
                                     locked_part >= 0 ? veh->vehicle().part( locked_part ).name() :
                                     here.tername( examp );
     const bool has_prying = !best_prying.is_null();
     const bool can_pick = ( here.has_flag( ter_furn_flag::TFLAG_PICKABLE, examp ) ||
                             locked_part >= 0 ) &&
                           ( !best_lockpick.is_null() || you.has_bionic( bio_lockpick ) );
     enum act {
         pick = 0,
         pry = 1,
         none = 2
     };
     int action = act::none;
     if( has_prying && can_pick ) {
         const int pry_has = best_prying.get_quality( qual_PRY );
         const int pry_req = here.has_furn( examp ) ?
                             here.furn( examp )->prying->prying_data().prying_level :
                             here.ter( examp )->prying->prying_data().prying_level;
         if( pry_has < pry_req ) {
             action = act::pick;
         } else {
             uilist amenu;
             amenu.text = string_format( _( "What to do with the %s?" ),
                                         target_name );
             amenu.addentry( 0, true, 'l', _( "Pick the lock" ) );
             amenu.addentry( 1, true, 'p', _( "Pry open" ) );
             amenu.query();
             if( amenu.ret < act::pick || amenu.ret > act::pry ) {
                 return;
             }
             action = amenu.ret;
         }
     } else {
         action = has_prying ? act::pry : can_pick ? act::pick : act::none;
     }
     if( action == act::none ) {
         add_msg( m_info, _( "The %s is locked.  You could pry it open with the right tool" ),
                  target_name );
         return;
     } else if( action == act::pry ) {
         //~ %1$s: terrain/furniture name, %2$s: prying tool name
         you.add_msg_if_player( _( "You attempt to pry open the %1$s using your %2$s" ),
                                target_name, best_prying.tname() );
         iuse::crowbar( &you, &best_prying, examp );
     } else if( action == act::pick ) {
         locked_object_pickable( you, examp );
     }
 }
References _, act, action, add_msg(), Character::add_msg_if_player(), uilist::addentry(), available, Character::best_item_with_quality(), bio_lockpick, iuse::crowbar(), map::furn(), map::furnname(), get_map(), item::get_quality(), Character::has_bionic(), map::has_flag(), map::has_furn(), item::is_null(), locked_object_pickable(), m_info, none, ter_t::prying, furn_t::prying, qual_LOCKPICK, qual_PRY, uilist::query(), uilist::ret, string_format(), map::ter(), map::tername(), uilist::text, TFLAG_PICKABLE, item::tname(), and map::veh_at().
Referenced by curtains(), door_peephole(), and iexamine_functions_from_string().
locked_object_pickable()
void iexamine::locked_object_pickable (Character & you, const tripoint & examp)
Checks whether PC has picklocks then calls pick_lock iuse function OR assigns ACT_LOCKPICK.
Definition at line 1898 of file iexamine.cpp.
 {
     map &here = get_map();
     const optional_vpart_position veh = here.veh_at( examp );
     int locked_part = -1;
     if( veh ) {
         const std::vector<vehicle_part *> parts_at_target = veh->vehicle().get_parts_at(
                     examp, "LOCKABLE_DOOR", part_status_flag::available );
         if( !parts_at_target.empty() ) {
             locked_part = veh->vehicle().next_part_to_unlock(
                               veh->vehicle().index_of_part( parts_at_target.front() ) );
         }
     }
     const std::string target_name = here.has_furn( examp ) ? here.furnname( examp ) :
                                     locked_part >= 0 ? veh->vehicle().part( locked_part ).name() : here.tername( examp );
     if( you.has_bionic( bio_lockpick ) ) {
         if( you.get_power_level() >= bio_lockpick->power_activate ) {
             you.mod_power_level( -bio_lockpick->power_activate );
             you.add_msg_if_player( m_info, _( "You activate your %s." ), bio_lockpick->name );
             you.assign_activity( lockpick_activity_actor::use_bionic( here.getabs( examp ) ) );
             return;
         } else {
             you.add_msg_if_player( m_info, _( "You don't have enough power to activate your %s." ),
                                    bio_lockpick->name );
         }
     }
     std::vector<item *> picklocks = you.items_with( [&you]( const item & it ) {
         // Don't include worn items such as hairpins
         if( !you.is_worn( it ) ) {
             return it.type->get_use( "PICK_LOCK" ) != nullptr;
         }
         return false;
     } );
     if( picklocks.empty() ) {
         add_msg( m_info, _( "The %s is locked.  If only you had something to pick its lock with" ),
                  target_name );
         return;
     }
     // Sort by their picklock level.
     std::sort( picklocks.begin(), picklocks.end(), [&]( const item * a, const item * b ) {
         int a_quality = a->get_quality( qual_LOCKPICK );
         int b_quality = b->get_quality( qual_LOCKPICK );
         // Sort by durability to spend most broken item
         if( a_quality == b_quality ) {
             return a->damage() > b->damage();
         }
         return a_quality > b_quality;
     } );
     for( item *it : picklocks ) {
         if( !query_yn( _( "Pick the lock of %1$s using your %2$s?" ),
                        target_name, it->tname() ) ) {
             return;
         }
         const use_function *iuse_fn = it->type->get_use( "PICK_LOCK" );
         you.add_msg_if_player( _( "You attempt to pick the lock of %1$s using your %2$s" ),
                                target_name, it->tname() );
         const ret_val<void> can_use = iuse_fn->can_call( you, *it, examp );
         if( can_use.success() ) {
             iuse_fn->call( &you, *it, examp );
             return;
         } else {
             you.add_msg_if_player( m_bad, can_use.str() );
         }
     }
 }
References _, a, add_msg(), Character::add_msg_if_player(), Character::assign_activity(), available, b, bio_lockpick, map::furnname(), get_map(), Character::get_power_level(), map::getabs(), Character::has_bionic(), map::has_furn(), Character::is_worn(), visitable::items_with(), m_info, Character::mod_power_level(), bionic_data::name, bionic_data::power_activate, map::tername(), lockpick_activity_actor::use_bionic(), and map::veh_at().
Referenced by iexamine_functions_from_string(), and locked_object().
mill_finalize()
void iexamine::mill_finalize (Character & , const tripoint & examp)
Definition at line 6379 of file iexamine.cpp.
 {
     map &here = get_map();
     const furn_id cur_mill_type = here.furn( examp );
     furn_id next_mill_type = furn_str_id::NULL_ID();
     if( cur_mill_type == furn_f_wind_mill_active ) {
         next_mill_type = furn_f_wind_mill;
     } else if( cur_mill_type == furn_f_water_mill_active ) {
         next_mill_type = furn_f_water_mill;
     } else {
         debugmsg( "Furniture executed action mill_finalize, but is of type %s",
                   here.furn( examp ).id().c_str() );
         return;
     }
     map_stack items = here.i_at( examp );
     if( items.empty() ) {
         here.furn_set( examp, next_mill_type );
         return;
     }
     std::map<itype_id, int> millable_counts;
     for( const item &iter : items ) {
         if( iter.type->milling_data && !iter.type->milling_data->into_.is_null() ) {
             if( millable_counts.find( iter.typeId() ) == millable_counts.end() ) {
                 millable_counts.emplace( iter.typeId(), 1 );
             } else {
                 millable_counts[iter.typeId()]++;
             }
         }
     }
     for( std::pair<const string_id<itype>, int> mill_type_count : millable_counts ) {
         const item source( mill_type_count.first );
         const item product( source.type->milling_data->into_ );
         const recipe rec = *source.type->milling_data->recipe_;
         if( rec.is_null() ) {
             debugmsg( _( "Failed to find milling recipe for %s. It wasn't milled." ),
                       source.display_name().c_str() );
         } else {
             const requirement_data::alter_item_comp_vector &components =
                 rec.simple_requirements().get_components();
             int lot_size = 0;
             // Making the assumption that milling only uses a single type of input product. Support for mixed products would require additional logic.
             // We also make the assumption that this is the only relevant input, so if lubricants etc. was to be added more logic would be needed.
             for( const std::vector<item_comp> &component : components ) {
                 for( const item_comp &comp : component ) {
                     if( comp.type == mill_type_count.first ) {
                         lot_size = comp.count;
                         break;
                     }
                 }
                 if( lot_size > 0 ) {
                     break;
                 }
             }
             if( lot_size == 0 ) {
                 debugmsg( _( "Failed to find milling recipe for %s. Milling of it failed." ),
                           source.display_name().c_str() );
                 mill_type_count.second = 0;
             } else {
                 const int batches = mill_type_count.second / lot_size;
                 const int process_count = batches * lot_size;
                 if( batches == 0 ) {
                     add_msg( m_info, _( "%s is milled in batches of %d, so none was processed." ),
                              source.tname(), lot_size );
                 } else if( process_count != mill_type_count.second ) {
                     add_msg( m_info, _( "%s is milled in batches of %d, so %d remained unprocessed." ),
                              source.tname(), lot_size, mill_type_count.second - batches * lot_size );
                 }
                 mill_type_count.second = process_count;
                 item_components item_component_lot;
                 int count = 0;
                 for( item &iter : items ) {
                     if( iter.typeId() == mill_type_count.first ) {
                         item_component_lot.add( iter );
                         count++;
                         if( count == mill_type_count.second ) {
                             break;
                         }
                     }
                 }
                 std::vector<item> results = rec.create_results( batches, &item_component_lot );
                 for( const item &result : results ) {
                     here.add_item( examp, result );
                 }
                 for( map_stack::iterator iter = items.begin(); iter != items.end(); ) {
                     item &it = *iter;
                     if( it.typeId() == mill_type_count.first && mill_type_count.second > 0 ) {
                         iter = items.erase( iter );
                         mill_type_count.second--;
                     } else {
                         ++iter;
                     }
                 }
             }
         }
     }
     here.furn_set( examp, next_mill_type );
 }
References _, item_components::add(), map::add_item(), add_msg(), string_id< T >::c_str(), recipe::create_results(), debugmsg, item::display_name(), item_stack::empty(), map::furn(), furn_f_water_mill, furn_f_water_mill_active, furn_f_wind_mill, furn_f_wind_mill_active, map::furn_set(), requirement_data::get_components(), get_map(), map::i_at(), int_id< T >::id(), recipe::is_null(), m_info, itype::milling_data, string_id< furn_t >::NULL_ID(), recipe::simple_requirements(), item::tname(), item::type, and item::typeId().
Referenced by item::process_fake_mill().
nanofab()
void iexamine::nanofab (Character & you, const tripoint & examp)
TEMPLATE FABRICATORS Generate items from found blueprints.
Definition at line 399 of file iexamine.cpp.
 {
     bool table_exists = false;
     std::list<item_location> on_table;
     item_location nanofab_template;
     tripoint spawn_point;
     map &here = get_map();
     std::set<itype_id> allowed_template = here.ter( examp )->allowed_template_id;
     for( const tripoint &valid_location : here.points_in_radius( examp, 1 ) ) {
         if( here.has_flag( ter_furn_flag::TFLAG_NANOFAB_TABLE, valid_location ) ) {
             spawn_point = valid_location;
             table_exists = true;
             on_table = here.items_with( valid_location, [&]( const item & it ) {
                 return it.has_flag( flag_NANOFAB_REPAIR );
             } );
             break;
         }
     }
     if( !table_exists ) {
         return;
     }
     item new_item;
     requirement_data reqs;
     // If there is something on the table that can be repaired suggest to repair that instead of printing something new
     if( !on_table.empty() ) {
         new_item = item( on_table.front()->typeId(), calendar::turn );
         int damage = on_table.front()->damage_level();
         if( damage <= 0 ) {
             popup( _( "FABRICATOR COMPLIANT ITEM %s DETECTED, BUT NOT DAMAGED REMOVE WORKING ITEM FROM FABRICATOR" ),
                    new_item.display_name() );
             sounds::sound( spawn_point, 10, sounds::sound_t::speech,
                            _( "REMOVE WORKING ITEM FROM FABRICATOR." ), true );
             return;
         }
         if( !on_table.front()->empty() ) {
             popup( _( "ITEM %s DETECTED, CONTENTS OF ITEM WILL BE DESTROYED BY FABRICATOR PLEASE EMPTY ITEM AND RETURN" ),
                    new_item.display_name() );
             sounds::sound( spawn_point, 10, sounds::sound_t::speech,
                            _( "PLEASE EMPTY ITEM AND RETURN." ), true );
             return;
         }
         sounds::sound( spawn_point, 10, sounds::sound_t::speech,
                        _( "REPAIR INTEGRITY DAMAGE?" ), true );
         if( !query_yn( _( "FABRICATOR COMPLIANT ITEM %s DETECTED, REPAIR INTEGRITY DAMAGE?" ),
                        new_item.display_name() ) ) {
             return;
         }
         // multiplier for the item being not completely destroyed
         float dam_mult = .05f * damage;
         int qty = std::max( 1, static_cast<int>( dam_mult * new_item.volume() / 250_ml ) );
         std::vector<std::vector<item_comp>> requirement_comp_vector;
         std::vector<std::vector<quality_requirement>> quality_comp_vector;
         std::vector<std::vector<tool_comp>> tool_comp_vector;
         std::vector<item_comp> nano_req = { item_comp( itype_nanomaterial, 5 * qty ) };
         requirement_comp_vector.push_back( nano_req );
         std::vector<item_comp> item_req = { item_comp( on_table.front()->typeId(), 1 ) };
         requirement_comp_vector.push_back( item_req );
         reqs = requirement_data( tool_comp_vector, quality_comp_vector, requirement_comp_vector );
     } else {
         //Create a list of the names of all acceptable templates.
         std::set<std::string> templatenames;
         for( const itype_id &id : allowed_template ) {
             templatenames.insert( id->nname( 1 ) );
         }
         std::string name_list = enumerate_as_string( templatenames );
         //Template selection
         nanofab_template = g->inv_map_splice( [&]( const item & e ) {
             return  std::any_of( allowed_template.begin(), allowed_template.end(),
             [&e]( const itype_id itid ) {
                 return e.typeId() == itid;
             } );
         }, _( "Introduce a compatible template." ), PICKUP_RANGE,
         _( "You don't have any usable templates.\n\nCompatible templates are: " ) + name_list );
         if( !nanofab_template ) {
             return;
         }
         new_item = item( nanofab_template->get_var( "NANOFAB_ITEM_ID" ), calendar::turn );
         int qty = std::max( 1, new_item.volume() / 250_ml );
         reqs = *nanofab_template->type->template_requirements * qty;
     }
     // either way the new item should have the nanofabricator flag
     if( !new_item.has_flag( flag_NANOFAB_REPAIR ) ) {
         new_item.set_flag( flag_NANOFAB_REPAIR );
     }
     if( !reqs.can_make_with_inventory( you.crafting_inventory(), is_crafting_component ) ) {
         popup( "%s", reqs.list_missing() );
         return;
     }
     // Consume materials
     for( const auto &e : reqs.get_components() ) {
         you.consume_items( e, 1, is_crafting_component );
     }
     for( const auto &e : reqs.get_tools() ) {
         you.consume_tools( e );
     }
     you.invalidate_crafting_inventory();
     if( new_item.is_armor() && new_item.has_flag( flag_VARSIZE ) ) {
         new_item.set_flag( flag_FIT );
     }
     here.add_item_or_charges( spawn_point, new_item );
     // if this template is single use
     // also check if the template exists at all
     if( nanofab_template && nanofab_template->has_flag( flag_NANOFAB_TEMPLATE_SINGLE_USE ) ) {
         nanofab_template.remove_item();
     }
 }
References _, map::add_item_or_charges(), ter_t::allowed_template_id, requirement_data::can_make_with_inventory(), Character::consume_items(), Character::consume_tools(), Character::crafting_inventory(), item::display_name(), enumerate_as_string(), flag_FIT, flag_NANOFAB_REPAIR, flag_NANOFAB_TEMPLATE_SINGLE_USE, flag_VARSIZE, g, requirement_data::get_components(), get_map(), requirement_data::get_tools(), item::get_var(), item::has_flag(), map::has_flag(), int_id< T >::id(), Character::invalidate_crafting_inventory(), item::is_armor(), is_crafting_component(), map::items_with(), itype_nanomaterial, requirement_data::list_missing(), max(), PICKUP_RANGE, map::points_in_radius(), popup(), query_yn(), item_location::remove_item(), item::set_flag(), sounds::sound(), sounds::speech, itype::template_requirements, map::ter(), TFLAG_NANOFAB_TABLE, calendar::turn, item::type, and item::volume().
Referenced by iexamine_functions_from_string().
none()
void iexamine::none (Character & you, const tripoint & examp)
Nothing player can interact with here.
Definition at line 306 of file iexamine.cpp.
 {
     add_msg( _( "That is a %s." ), get_map().name( examp ) );
 }
References _, add_msg(), get_map(), and om_direction::name().
Referenced by colorized_ter_name_flags_at(), dead_plant(), harvested_plant(), iexamine_functions_from_string(), pick_plant(), query_pick(), and harvest_activity_actor::start().
on_smoke_out()
void iexamine::on_smoke_out (const tripoint & examp, const time_point & start_time)
Definition at line 6737 of file iexamine.cpp.
 {
     map &here = get_map();
     if( here.furn( examp ) == furn_f_smoking_rack_active ||
         here.furn( examp ) == furn_f_metal_smoking_rack_active ) {
         smoker_finalize( get_avatar(), examp, start_time );
     }
 }
References map::furn(), furn_f_metal_smoking_rack_active, furn_f_smoking_rack_active, get_avatar(), get_map(), and smoker_finalize().
Referenced by item::process_fake_smoke().
open_safe()
void iexamine::open_safe (Character & you, const tripoint & examp)
Definition at line 7150 of file iexamine.cpp.
 {
     add_msg( m_info, _( "You open the unlocked safe." ) );
     get_map().furn_set( examp, furn_f_safe_o );
 }
References _, add_msg(), furn_f_safe_o, map::furn_set(), get_map(), and m_info.
Referenced by iexamine_functions_from_string().
part_con()
void iexamine::part_con (Character & you, const tripoint & examp)
Definition at line 4630 of file iexamine.cpp.
 {
     map &here = get_map();
     // TODO: fix point types
     if( partial_con *const pc = here.partial_con_at( tripoint_bub_ms( examp ) ) ) {
         if( you.fine_detail_vision_mod() > 4 &&
             !you.has_trait( trait_DEBUG_HS ) ) {
             add_msg( m_info, _( "It is too dark to construct right now." ) );
             return;
         }
         const construction &built = pc->id.obj();
         if( !query_yn( _( "Unfinished task: %s, %d%% complete here, continue construction?" ),
                        built.group->name(), pc->counter / 100000 ) ) {
             if( query_yn( _( "Cancel construction?" ) ) ) {
                 for( const item &it : pc->components ) {
                     here.add_item_or_charges( you.pos(), it );
                 }
                 // TODO: fix point types
                 here.partial_con_remove( tripoint_bub_ms( examp ) );
             }
         } else {
             you.assign_activity( ACT_BUILD );
             you.activity.placement = here.getglobal( examp );
         }
         return;
     }
 }
References _, ACT_BUILD, Character::activity, map::add_item_or_charges(), add_msg(), Character::assign_activity(), item::components, Character::fine_detail_vision_mod(), get_map(), map::getglobal(), construction::group, Character::has_trait(), construction::id, m_info, construction_group::name(), int_id< T >::obj(), map::partial_con_at(), map::partial_con_remove(), player_activity::placement, Creature::pos(), query_yn(), and trait_DEBUG_HS.
Referenced by can_do_activity_there(), and game::examine().
pay_gas()
void iexamine::pay_gas (Character & you, const tripoint & examp)
Definition at line 5185 of file iexamine.cpp.
 {
     int choice = -1;
     const int buy_gas = 1;
     const int choose_pump = 2;
     const int hack = 3;
     const int refund = 4;
     if( you.has_trait( trait_ILLITERATE ) ) {
         popup( _( "You're illiterate, and can't read the screen." ) );
     }
     fuel_station_fuel_type fuelType = FUEL_TYPE_NONE;
     std::string fuelTypeStr;
     int pumpCount = getNearPumpCount( examp, fuelType );
     fuelTypeStr = fuelType == FUEL_TYPE_GASOLINE ? _( "gasoline" ) : fuelType == FUEL_TYPE_DIESEL ?
                   _( "diesel" ) : "";
     if( pumpCount == 0 ) {
         popup( str_to_illiterate_str( string_format( _( "Failure!  No %s pumps found!" ), fuelTypeStr ) ) );
         return;
     }
     int tankUnits;
     const std::optional<tripoint> pTank_ = getNearFilledGasTank( examp, tankUnits, fuelType );
     if( !pTank_ ) {
         popup( str_to_illiterate_str( string_format( _( "Failure!  No %s tank found!" ), fuelTypeStr ) ) );
         return;
     }
     const tripoint pTank = *pTank_;
     if( tankUnits == 0 ) {
         popup( str_to_illiterate_str(
                    string_format( _( "This station is out of %s.  We apologize for the inconvenience." ),
                                   fuelTypeStr ) ) );
         return;
     }
     if( uistate.ags_pay_gas_selected_pump + 1 > pumpCount ) {
         uistate.ags_pay_gas_selected_pump = 0;
     }
     int discount = findBestGasDiscount( you );
     std::string discountName = getGasDiscountName( discount );
     int pricePerUnit = getGasPricePerLiter( discount );
     uilist amenu;
     amenu.selected = 1;
     amenu.text = str_to_illiterate_str( _( "Welcome to AutoGas!" ) );
     amenu.addentry( 0, false, -1, str_to_illiterate_str( _( "What would you like to do?" ) ) );
     amenu.addentry( buy_gas, true, 'b', str_to_illiterate_str( string_format( _( "Buy %s." ),
                     fuelTypeStr ) ) );
     amenu.addentry( refund, true, 'r', str_to_illiterate_str( _( "Refund cash." ) ) );
     std::string gaspumpselected = str_to_illiterate_str( string_format( _( "Current %s pump: " ),
                                   fuelTypeStr ) + std::to_string( uistate.ags_pay_gas_selected_pump + 1 ) );
     amenu.addentry( 0, false, -1, gaspumpselected );
     amenu.addentry( choose_pump, true, 'p',
                     str_to_illiterate_str( string_format( _( "Choose a %s pump." ), fuelTypeStr ) ) );
     amenu.addentry( 0, false, -1, str_to_illiterate_str( _( "Your discount: " ) ) + discountName );
     amenu.addentry( 0, false, -1, string_format( str_to_illiterate_str(
                         _( "Your price per %s unit: " ) ), fuelTypeStr )
                     +
                     format_money( pricePerUnit ) );
     if( can_hack( you ) ) {
         amenu.addentry( hack, true, 'h', _( "Hack console." ) );
     }
     amenu.query();
     choice = amenu.ret;
     if( choose_pump == choice ) {
         uilist amenu;
         amenu.selected = uistate.ags_pay_gas_selected_pump;
         amenu.text = str_to_illiterate_str( string_format( _( "Please choose %s pump:" ), fuelTypeStr ) );
         std::vector<tripoint> pumps;
         for( int i = 0; i < pumpCount; i++ ) {
             amenu.addentry( i, true, -1,
                             str_to_illiterate_str( _( "Pump " ) ) + std::to_string( i + 1 ) );
             pumps.emplace_back( getGasPumpByNumber( examp, i ).value_or( examp ) );
         }
         pointmenu_cb callback( pumps );
         amenu.callback = &callback;
         amenu.w_y_setup = 0;
         amenu.query();
         choice = amenu.ret;
         if( choice < 0 ) {
             return;
         }
         uistate.ags_pay_gas_selected_pump = choice;
         turnOnSelectedPump( examp, uistate.ags_pay_gas_selected_pump, fuelType );
         return;
     }
     if( buy_gas == choice ) {
         int money = you.charges_of( itype_cash_card );
         if( money < pricePerUnit ) {
             popup( str_to_illiterate_str(
                        _( "Not enough money, please refill your cash card." ) ) ); //or ride on a solar car, ha ha ha
             return;
         }
         int maximum_liters = std::min( money / pricePerUnit, tankUnits / 1000 );
         std::string popupmsg = str_to_illiterate_str( string_format(
                                    _( "How many liters of %s to buy?  Max: %d L.  (0 to cancel)" ), fuelTypeStr, maximum_liters ) );
         int liters = string_input_popup()
                      .title( popupmsg )
                      .width( 20 )
                      .text( std::to_string( maximum_liters ) )
                      .only_digits( true )
                      .query_int();
         if( liters <= 0 ) {
             return;
         }
         if( liters > maximum_liters ) {
             liters = maximum_liters;
         }
         const std::optional<tripoint> pGasPump = getGasPumpByNumber( examp,
                 uistate.ags_pay_gas_selected_pump );
         if( !pGasPump || !toPumpFuel( pTank, *pGasPump, liters * 1000 ) ) {
             return;
         }
         sounds::sound( you.pos(), 6, sounds::sound_t::activity, _( "Glug Glug Glug" ), true, "tool",
                        "gaspump" );
         int cost = liters * pricePerUnit;
         money -= cost;
         you.use_charges( itype_cash_card, cost );
         add_msg( m_info, _( "Your cash cards now hold %s." ), format_money( money ) );
         you.mod_moves( -to_moves<int>( 5_seconds ) );
         return;
     }
     if( hack == choice ) {
         try_start_hacking( you, examp );
     }
     if( refund == choice ) {
         std::vector<item *> cash_cards = you.cache_get_items_with( "is_cash_card", &item::is_cash_card );
         if( cash_cards.empty() ) {
             popup( _( "You do not have a cash card to refund money!" ) );
             return;
         }
         const std::optional<tripoint> pGasPump = getGasPumpByNumber( examp,
                 uistate.ags_pay_gas_selected_pump );
         int amount_fuel = pGasPump ? fromPumpFuel( pTank, *pGasPump ) : -1;
         if( amount_fuel < 0 ) {
             popup( _( "Unable to refund, no fuel in pump." ) );
             return;
         }
         sounds::sound( you.pos(), 6, sounds::sound_t::activity, _( "Glug Glug Glug" ), true, "tool",
                        "gaspump" );
         // getGasPricePerLiter( platinum_discount) min price to avoid exploit
         int amount_money = amount_fuel * getGasPricePerLiter( 3 ) / 1000.0f;
         std::sort( cash_cards.begin(), cash_cards.end(), []( item * l, const item * r ) {
             return l->ammo_remaining() > r->ammo_remaining();
         } );
         for( item * const &cc : cash_cards ) {
             if( amount_money == 0 ) {
                 break;
             }
             const int transfer = std::min( amount_money, cc->remaining_ammo_capacity() );
             cc->ammo_set( cc->ammo_default(), transfer + cc->ammo_remaining() );
             amount_money -= transfer;
         }
         if( amount_money ) {
             add_msg( m_info, _( "All cash cards at maximum capacity." ) );
             // all fuel already removed from pump, so remaining amount_money simply ignored
         }
         add_msg( m_info, _( "Your cash cards now hold %s." ),
                  format_money( you.charges_of( itype_cash_card ) ) );
         you.mod_moves( -to_moves<int>( 5_seconds ) );
         return;
     }
 }
References _, sounds::activity, add_msg(), uilist::addentry(), uistatedata::ags_pay_gas_selected_pump, Character::cache_get_items_with(), uilist::callback, can_hack(), Character::charges_of(), findBestGasDiscount(), format_money(), fromPumpFuel(), FUEL_TYPE_DIESEL, FUEL_TYPE_GASOLINE, FUEL_TYPE_NONE, getGasDiscountName(), getGasPricePerLiter(), getGasPumpByNumber(), getNearFilledGasTank(), getNearPumpCount(), Character::has_trait(), item::is_cash_card(), itype_cash_card, m_info, min(), Creature::mod_moves(), string_input_popup::only_digits(), popup(), Creature::pos(), uilist::query(), string_input_popup::query_int(), uilist::ret, uilist::selected, sounds::sound(), str_to_illiterate_str(), string_format(), string_input_popup::text(), uilist::text, string_input_popup::title(), to_string(), toPumpFuel(), trait_ILLITERATE, try_start_hacking(), turnOnSelectedPump(), uistate, Character::use_charges(), uilist::w_y_setup, and string_input_popup::width().
Referenced by get_hack_type(), and iexamine_functions_from_string().
pedestal_temple()
void iexamine::pedestal_temple (Character & you, const tripoint & examp)
Put petrified eye on pedestal causing it to sink into ground and open temple.
Definition at line 2038 of file iexamine.cpp.
 {
     map &here = get_map();
     map_stack items = here.i_at( examp );
     if( !items.empty() && items.only_item().typeId() == itype_petrified_eye ) {
         add_msg( _( "The pedestal sinks into the ground" ) );
         here.ter_set( examp, ter_t_dirt );
         here.i_clear( examp );
         get_timed_events().add( timed_event_type::TEMPLE_OPEN, calendar::turn + 10_seconds );
     } else if( you.has_amount( itype_petrified_eye, 1 ) &&
                query_yn( _( "Place your petrified eye on the pedestal?" ) ) ) {
         you.use_amount( itype_petrified_eye, 1 );
         add_msg( _( "The pedestal sinks into the ground" ) );
         here.ter_set( examp, ter_t_dirt );
         get_timed_events().add( timed_event_type::TEMPLE_OPEN, calendar::turn + 10_seconds );
     } else {
         add_msg( _( "This pedestal is engraved in eye-shaped diagrams, and has a "
                     "large semi-spherical indentation at the top." ) );
     }
 }
References _, timed_event_manager::add(), add_msg(), item_stack::empty(), get_map(), get_timed_events(), visitable::has_amount(), map::i_at(), map::i_clear(), itype_petrified_eye, item_stack::only_item(), query_yn(), TEMPLE_OPEN, map::ter_set(), ter_t_dirt, calendar::turn, item::typeId(), and Character::use_amount().
Referenced by iexamine_functions_from_string().
pedestal_wyrm()
void iexamine::pedestal_wyrm (Character & you, const tripoint & examp)
Spawn 1d4 wyrms and sink pedestal into ground.
Definition at line 2001 of file iexamine.cpp.
 {
     map &here = get_map();
     map_stack items = here.i_at( examp );
     if( !items.empty() ) {
         if( items.only_item().typeId() == itype_petrified_eye &&
             query_yn( _( "Remove the petrified eye from the pedestal?" ) ) ) {
             here.i_clear( examp );
             item eye( itype_petrified_eye );
             you.i_add_or_drop( eye );
             // Send in a few wyrms to start things off.
             get_event_bus().send<event_type::awakes_dark_wyrms>();
             for( const tripoint &p : here.points_on_zlevel() ) {
                 if( here.ter( p ) == ter_t_orifice ) {
                     g->place_critter_around( mon_dark_wyrm, p, 1 );
                 }
             }
             sounds::sound( examp, 80, sounds::sound_t::combat, _( "an ominous grinding noise" ), true,
                            "misc", "stones_grinding" );
             add_msg( _( "The pedestal sinks into the ground" ) );
             here.ter_set( examp, ter_t_rock_floor );
             get_timed_events().add( timed_event_type::SPAWN_WYRMS,
                                     calendar::turn + rng( 30_seconds, 60_seconds ) );
         } else {
             none( you, examp );
             add_msg( _( "You decided to leave the petrified eye on the pedestal" ) );
             return;
         }
     }
 }
References _, timed_event_manager::add(), add_msg(), awakes_dark_wyrms, sounds::combat, item_stack::empty(), g, get_event_bus(), get_map(), get_timed_events(), Character::i_add_or_drop(), map::i_at(), map::i_clear(), itype_petrified_eye, mon_dark_wyrm, none, item_stack::only_item(), map::points_on_zlevel(), query_yn(), rng(), event_bus::send(), sounds::sound(), SPAWN_WYRMS, map::ter(), map::ter_set(), ter_t_orifice, ter_t_rock_floor, calendar::turn, and item::typeId().
Referenced by iexamine_functions_from_string().
pit()
void iexamine::pit (Character & you, const tripoint & examp)
If there is a 2x4 around, prompt placing it across pit.
Definition at line 1716 of file iexamine.cpp.
 {
     const inventory &crafting_inv = you.crafting_inventory();
     if( !crafting_inv.has_amount( itype_2x4, 1 ) ) {
         none( you, examp );
         return;
     }
     std::vector<item_comp> planks;
     planks.emplace_back( itype_2x4, 1 );
     map &here = get_map();
     if( query_yn( _( "Place a plank over the pit?" ) ) ) {
         you.consume_items( planks, 1, is_crafting_component );
         const ter_id &ter_pit = here.ter( examp );
         if( ter_pit == ter_t_pit ) {
             here.ter_set( examp, ter_t_pit_covered );
         } else if( ter_pit == ter_t_pit_spiked ) {
             here.ter_set( examp, ter_t_pit_spiked_covered );
         } else if( ter_pit == ter_t_pit_glass ) {
             here.ter_set( examp, ter_t_pit_glass_covered );
         }
         add_msg( _( "You place a plank of wood over the pit." ) );
         you.mod_moves( -to_moves<int>( 1_seconds ) );
     }
 }
References _, add_msg(), Character::consume_items(), Character::crafting_inventory(), get_map(), visitable::has_amount(), is_crafting_component(), itype_2x4, Creature::mod_moves(), none, query_yn(), map::ter(), map::ter_set(), ter_t_pit, ter_t_pit_covered, ter_t_pit_glass, ter_t_pit_glass_covered, ter_t_pit_spiked, and ter_t_pit_spiked_covered.
Referenced by iexamine_functions_from_string(), and trapfunc::sinkhole().
pit_covered()
void iexamine::pit_covered (Character & you, const tripoint & examp)
Prompt removing the 2x4 placed across the pit.
Definition at line 1745 of file iexamine.cpp.
 {
     if( !query_yn( _( "Remove cover?" ) ) ) {
         none( you, examp );
         return;
     }
     map &here = get_map();
     item plank( "2x4", calendar::turn );
     add_msg( _( "You remove the plank." ) );
     here.add_item_or_charges( you.pos(), plank );
     const ter_id &ter_pit = here.ter( examp );
     if( ter_pit == ter_t_pit_covered ) {
         here.ter_set( examp, ter_t_pit );
     } else if( ter_pit == ter_t_pit_spiked_covered ) {
         here.ter_set( examp, ter_t_pit_spiked );
     } else if( ter_pit == ter_t_pit_glass_covered ) {
         here.ter_set( examp, ter_t_pit_glass );
     }
     you.mod_moves( -to_moves<int>( 1_seconds ) );
 }
References _, map::add_item_or_charges(), add_msg(), get_map(), Creature::mod_moves(), none, Creature::pos(), query_yn(), map::ter(), map::ter_set(), ter_t_pit, ter_t_pit_covered, ter_t_pit_glass, ter_t_pit_glass_covered, ter_t_pit_spiked, ter_t_pit_spiked_covered, and calendar::turn.
Referenced by iexamine_functions_from_string().
plant_seed()
void iexamine::plant_seed (Character & you, const tripoint & examp, const itype_id & seed_id)
Actual planting of selected seed.
Definition at line 2530 of file iexamine.cpp.
 {
     player_activity act( ACT_PLANT_SEED, to_moves<int>( 30_seconds ) );
     act.placement = get_map().getglobal( examp );
     act.str_values.emplace_back( seed_id );
     you.assign_activity( act );
 }
References act, ACT_PLANT_SEED, Character::assign_activity(), get_map(), and map::getglobal().
Referenced by dirtmound(), and generic_multi_activity_do().
portable_structure()
void iexamine::portable_structure (Character & you, const tripoint & examp)
Determine structure's type and prompts its removal.
Definition at line 1674 of file iexamine.cpp.
 {
     map &here = get_map();
     const furn_str_id fid = here.furn( examp ).id();
     const std::pair<itype_id, const deploy_tent_actor *> tent_item_type = find_tent_itype( fid );
     if( tent_item_type.first.is_null() ) {
         debugmsg( "unknown furniture %s: don't know how to transform it into an item", fid.str() );
         return;
     }
     itype_id dropped = tent_item_type.first;
     std::string name = item::nname( dropped );
     int radius;
     if( tent_item_type.second ) {
         const deploy_tent_actor &actor = *tent_item_type.second;
         if( !actor.check_intact( examp ) ) {
             if( !actor.broken_type ) {
                 add_msg( _( "The %s is broken and can not be picked up." ), name );
                 none( you, examp );
                 return;
             }
             dropped = *actor.broken_type;
             name = string_format( _( "damaged %s" ), name );
         }
         radius = actor.radius;
     } else {
         radius = std::max( 1, fid->bash.collapse_radius );
     }
     if( !query_yn( _( "Take down the %s?" ), name ) ) {
         none( you, examp );
         return;
     }
     tent_deconstruct_activity_actor actor( to_moves<int>( 20_minutes ), radius, examp, dropped );
     you.assign_activity( actor );
 }
References _, add_msg(), Character::assign_activity(), map_data_common_t::bash, deploy_tent_actor::broken_type, deploy_tent_actor::check_intact(), map_bash_info::collapse_radius, debugmsg, find_tent_itype(), map::furn(), get_map(), int_id< T >::id(), max(), om_direction::name(), item::nname(), none, query_yn(), deploy_tent_actor::radius, string_id< T >::str(), and string_format().
Referenced by iexamine_functions_from_string().
pour_into_keg()
bool iexamine::pour_into_keg (const tripoint & pos, item & liquid)
Pour liquid into a keg (furniture) on the map.
The transferred charges (if any) will be removed from the liquid item.
Returns
Whether any charges have been transferred at all.
Definition at line 4220 of file iexamine.cpp.
 {
     const units::volume keg_cap = get_keg_capacity( pos );
     if( keg_cap <= 0_ml ) {
         return false;
     }
     map &here = get_map();
     const std::string keg_name = here.name( pos );
     map_stack stack = here.i_at( pos );
     if( stack.empty() ) {
         here.add_item( pos, liquid );
         here.i_at( pos ).only_item().charges = 0; // Will be set later
     } else if( stack.only_item().typeId() != liquid.typeId() ) {
         add_msg( _( "The %s already contains some %s, you can't add a different liquid to it." ),
                  keg_name, item::nname( stack.only_item().typeId() ) );
         return false;
     }
     item &drink = stack.only_item();
     if( drink.volume() >= keg_cap ) {
         add_msg( _( "The %s is full." ), keg_name );
         return false;
     }
     add_msg( _( "You pour %1$s into the %2$s." ), liquid.tname(), keg_name );
     while( liquid.charges > 0 && drink.volume() < keg_cap ) {
         drink.charges++;
         liquid.charges--;
     }
     return true;
 }
References _, map::add_item(), add_msg(), item::charges, item_stack::empty(), get_keg_capacity(), get_map(), map::i_at(), map::name(), item::nname(), item_stack::only_item(), math_opers::pos(), item::tname(), item::typeId(), and item::volume().
Referenced by activity_handlers::fill_liquid_do_turn(), keg(), and liquid_handler::perform_liquid_transfer().
practice_survival_while_foraging()
void iexamine::practice_survival_while_foraging (Character & who)
Intelligence Intelligence caps survival skill gains from foraging Survival decreases survival skill gain from foraging (NEGATIVE)
Definition at line 7445 of file iexamine.cpp.
 {
     ///\EFFECT_INT Intelligence caps survival skill gains from foraging
     const int max_forage_skill = who.int_cur / 3 + 1;
     ///\EFFECT_SURVIVAL decreases survival skill gain from foraging (NEGATIVE)
     const int max_exp = 2 * ( max_forage_skill - static_cast<int>( who.get_skill_level(
                                   skill_survival ) ) );
     // Award experience for foraging attempt regardless of success
     who.practice( skill_survival, rng( 1, max_exp ), max_forage_skill );
 }
References Character::get_skill_level(), Character::int_cur, Character::practice(), rng(), and skill_survival.
Referenced by harvest_activity_actor::finish(), and forage_activity_actor::finish().
quern_examine()
void iexamine::quern_examine (Character & you, const tripoint & examp)
Definition at line 6746 of file iexamine.cpp.
 {
     map &here = get_map();
     if( here.furn( examp ) == furn_f_water_mill ) {
         if( !here.is_water_shallow_current( examp ) ) {
             add_msg( _( "The water mill needs to be over shallow flowing water to work." ) );
             return;
         }
     }
     if( here.furn( examp ) == furn_f_wind_mill ) {
         if( g->is_sheltered( examp ) ) {
             add_msg( _( "The wind mill needs to be outside in the wind to work." ) );
             return;
         }
     }
     const bool active = here.furn( examp ) == furn_f_water_mill_active ||
                         here.furn( examp ) == furn_f_wind_mill_active;
     map_stack items_here = here.i_at( examp );
     if( items_here.empty() && active ) {
         debugmsg( "active mill was empty!" );
         if( here.furn( examp ) == furn_f_water_mill_active ) {
             here.furn_set( examp, furn_f_water_mill );
         } else if( here.furn( examp ) == furn_f_wind_mill_active ) {
             here.furn_set( examp, furn_f_wind_mill );
         }
         return;
     }
     if( items_here.size() == 1 && items_here.begin()->typeId() == itype_fake_milling_item ) {
         debugmsg( "f_mill_active was empty, and had fake_milling_item!" );
         if( here.furn( examp ) == furn_f_water_mill_active ) {
             here.furn_set( examp, furn_f_water_mill );
         } else if( here.furn( examp ) == furn_f_wind_mill_active ) {
             here.furn_set( examp, furn_f_wind_mill );
         }
         items_here.erase( items_here.begin() );
         return;
     }
     time_duration time_left = 0_turns;
     units::volume f_volume = 0_ml;
     bool f_check = false;
     for( const item &it : items_here ) {
         if( it.typeId() != itype_fake_milling_item ) {
             f_check = true;
             f_volume += it.volume();
         }
         if( active && it.typeId() == itype_fake_milling_item ) {
             time_left = time_duration::from_turns( it.item_counter );
         }
     }
     const bool empty = f_volume == 0_ml;
     const bool full = f_volume >= sm_rack::MAX_FOOD_VOLUME;
     const auto remaining_capacity = sm_rack::MAX_FOOD_VOLUME - f_volume;
     uilist smenu;
     smenu.text = _( "What to do with the mill?" );
     smenu.desc_enabled = true;
     smenu.addentry( 0, true, 'i', _( "Inspect mill" ) );
     if( !active ) {
         smenu.addentry_desc( 1, !empty, 'r',
                              empty ?  _( "Remove brake and start milling insert some products for milling first" ) :
                              _( "Remove brake and start milling" ),
                              string_format( _( "Remove brake and start milling, milling will take about %s." ),
                                             to_string( milling_time ) ) );
         smenu.addentry_desc( 2, !full, 'p',
                              full ? _( "Insert products for milling mill is full" ) :
                              string_format( _( "Insert products for milling remaining capacity is %s %s" ),
                                             format_volume( remaining_capacity ), volume_units_abbr() ),
                              _( "Fill the mill with starchy products such as wheat, barley or oats." ) );
         if( f_check ) {
             smenu.addentry( 3, f_check, 'e', _( "Remove products from mill" ) );
         }
     } else {
         smenu.addentry_desc( 4, true, 'x',
                              _( "Apply brake to mill" ),
                              _( "Applying the brake will stop milling process." ) );
     }
     smenu.query();
     switch( smenu.ret ) {
         case 0: { //inspect mill
             std::string pop;
             if( active ) {
                 pop = colorize( _( "There's a mill here.  It is turning and milling." ), c_green ) + "\n";
                 if( time_left > 0_turns ) {
                     pop += string_format( _( "It should take about %s to finish milling." ),
                                           to_string_clipped( time_left ) ) + "\n";
                 }
             } else {
                 pop += colorize( _( "There's a mill here." ), c_green ) + "\n";
             }
             pop += colorize( _( "You inspect its contents and find: " ), c_green ) + "\n\n";
             if( items_here.empty() ) {
                 pop += _( "that it is empty." );
             } else {
                 for( const item &it : items_here ) {
                     if( it.typeId() == itype_fake_milling_item ) {
                         pop += "\n" + colorize( _( "You see some grains that are not yet milled to fine flour." ),
                                                 c_red ) + "\n";
                         continue;
                     }
                     pop += "-> " + it.display_name() + "\n";
                 }
             }
             popup( pop, PF_NONE );
             break;
         }
         case 1:
             //activate
             if( active ) {
                 add_msg( _( "It is already milling." ) );
             } else {
                 mill_activate( you, examp );
             }
             break;
         case 2:
             // load food
             mill_load_food( you, examp, remaining_capacity );
             break;
         case 3:
             // remove food
             for( map_stack::iterator it = items_here.begin(); it != items_here.end(); ) {
                 if( it->typeId() != itype_fake_milling_item ) {
                     // get handling cost before the item reference is invalidated
                     const int handling_cost = -you.item_handling_cost( *it );
                     add_msg( _( "You remove %s from the mill." ), it->tname() );
                     here.add_item_or_charges( you.pos(), *it );
                     it = items_here.erase( it );
                     you.mod_moves( handling_cost );
                 } else {
                     ++it;
                 }
             }
             if( active ) {
                 if( here.furn( examp ) == furn_f_water_mill_active ) {
                     here.furn_set( examp, furn_f_water_mill );
                 } else if( here.furn( examp ) == furn_f_wind_mill_active ) {
                     here.furn_set( examp, furn_f_wind_mill );
                 }
                 add_msg( m_info, _( "You stop the milling process." ) );
             }
             break;
         default:
             add_msg( m_info, _( "Never mind." ) );
             break;
         case 4:
             if( here.furn( examp ) == furn_f_water_mill_active ) {
                 here.furn_set( examp, furn_f_water_mill );
             } else if( here.furn( examp ) == furn_f_wind_mill_active ) {
                 here.furn_set( examp, furn_f_wind_mill );
             }
             for( map_stack::iterator it = items_here.begin(); it != items_here.end(); ) {
                 if( it->typeId() == itype_fake_milling_item ) {
                     it = items_here.erase( it );
                 } else {
                     ++it;
                 }
             }
             add_msg( m_info, _( "You stop the milling process." ) );
             break;
     }
 }
References _, map::add_item_or_charges(), add_msg(), uilist::addentry(), uilist::addentry_desc(), item_stack::begin(), c_green, c_red, colorize(), debugmsg, uilist::desc_enabled, item::display_name(), item_stack::empty(), item_stack::end(), map_stack::erase(), format_volume(), time_duration::from_turns(), map::furn(), furn_f_water_mill, furn_f_water_mill_active, furn_f_wind_mill, furn_f_wind_mill_active, map::furn_set(), g, get_map(), map::i_at(), map::is_water_shallow_current(), item::item_counter, Character::item_handling_cost(), itype_fake_milling_item, m_info, sm_rack::MAX_FOOD_VOLUME, mill_activate(), mill_load_food(), milling_time, Creature::mod_moves(), PF_NONE, popup(), Creature::pos(), uilist::query(), uilist::ret, item_stack::size(), string_format(), uilist::text, item::tname(), to_string(), to_string_clipped(), item::typeId(), item::volume(), and volume_units_abbr().
Referenced by iexamine_functions_from_string().
query_seed()
int iexamine::query_seed (const std::vector< seed_tuple > & seed_entries)
Choose seed for planting.
Definition at line 2502 of file iexamine.cpp.
 {
     uilist smenu;
     smenu.text = _( "Use which seed?" );
     int count = 0;
     for( const auto &entry : seed_entries ) {
         const std::string &seed_name = std::get<1>( entry );
         int seed_count = std::get<2>( entry );
         std::string format = seed_count > 0 ? "%s (%d)" : "%s";
         smenu.addentry( count++, true, MENU_AUTOASSIGN, format.c_str(),
                         seed_name, seed_count );
     }
     smenu.query();
     if( smenu.ret >= 0 ) {
         return smenu.ret;
     } else {
         return seed_entries.size();
     }
 }
References _, uilist::addentry(), MENU_AUTOASSIGN, uilist::query(), uilist::ret, and uilist::text.
Referenced by dirtmound(), plot_options::query_seed(), and vehicle::reload_seeds().
reload_furniture()
void iexamine::reload_furniture (Character & you, const tripoint & examp)
Definition at line 4863 of file iexamine.cpp.
 {
     return reload_furniture( you, examp, true );
 }
References reload_furniture().
Referenced by iexamine_functions_from_string().
rubble()
void iexamine::rubble (Character & you, const tripoint & examp)
Prompt removal of rubble.
Select best shovel and invoke "CLEAR_RUBBLE" on tile.
Definition at line 1488 of file iexamine.cpp.
 {
     int moves;
     if( you.has_quality( qual_DIG, 3 ) || you.has_trait( trait_BURROW ) ||
         you.has_trait( trait_BURROWLARGE ) ) {
         moves = to_moves<int>( 1_minutes );
     } else if( you.has_quality( qual_DIG, 2 ) ) {
         moves = to_moves<int>( 2_minutes );
     } else {
         add_msg( m_info, _( "If only you had a shovel" ) );
         return;
     }
     map &here = get_map();
     if( ( here.veh_at( examp ) || here.can_see_trap_at( examp, you ) ||
           get_creature_tracker().creature_at( examp ) != nullptr ) &&
         !query_yn( _( "Clear up that %s?" ), here.furnname( examp ) ) ) {
         return;
     }
     you.assign_activity( clear_rubble_activity_actor( moves ) );
     you.activity.placement = here.getglobal( examp );
 }
References _, Character::activity, add_msg(), Character::assign_activity(), map::can_see_trap_at(), map::furnname(), get_creature_tracker(), get_map(), map::getglobal(), Character::has_quality(), Character::has_trait(), m_info, player_activity::placement, qual_DIG, query_yn(), trait_BURROW, trait_BURROWLARGE, and map::veh_at().
Referenced by iexamine_functions_from_string().
safe()
void iexamine::safe (Character & you, const tripoint & examp)
Attempt to crack safe through audio-feedback manual lock manipulation.
Try to unlock the safe by moving the dial and listening for the mechanism to "click into place." Time per attempt affected by perception and mechanics. 30 minutes per attempt minimum. Small chance of just guessing the combo without listening device.
Definition at line 1776 of file iexamine.cpp.
 {
     bool has_cracking_tool = you.has_flag( json_flag_SAFECRACK_NO_TOOL );
     // short-circuit to avoid the more expensive iteration over items
     has_cracking_tool = has_cracking_tool || you.cache_has_item_with( flag_SAFECRACK );
     if( !has_cracking_tool ) {
         you.mod_moves( -to_moves<int>( 10_seconds ) );
         // Assume a 3 digit 100-number code. Many safes allow adjacent + 1 dial locations to match,
         // so 1/20^3, or 1/8,000 odds.
         // Additionally, safes can be left-handed or right-handed, doubling the problem space.
         // The dialing procedures for safes vary, I'm estimating 5 procedures.
         // See https://hoogerhydesafe.com/resources/combination-lock-dialing-procedures/
         // At the end of the day, that means a 1 / 80,000 chance per attempt.
         // If someone is interested, they can feel free to add a proficiency for
         // "safe recognition" to mitigate or eliminate this 2x and 5x factor.
         if( one_in( 80000 ) ) {
             you.add_msg_if_player( m_good, _( "You mess with the dial for a little bit and it opens!" ) );
             get_map().furn_set( examp, furn_f_safe_o );
             return;
         } else {
             you.add_msg_if_player( m_info, _( "You mess with the dial for a little bit." ) );
             return;
         }
     }
     if( you.is_deaf() ) {
         add_msg( m_info, _( "You can't crack a safe while deaf!" ) );
         return;
     } else if( you.has_effect( effect_earphones ) ) {
         add_msg( m_info, _( "You can't crack a safe while listening to music!" ) );
         return;
     } else if( query_yn( _( "Attempt to crack the safe?" ) ) ) {
         you.assign_activity( safecracking_activity_actor( examp ) );
     }
 }
References _, add_msg(), Character::add_msg_if_player(), Character::assign_activity(), Character::cache_has_item_with(), effect_earphones, flag_SAFECRACK, furn_f_safe_o, map::furn_set(), get_map(), Creature::has_effect(), Character::has_flag(), Character::is_deaf(), json_flag_SAFECRACK_NO_TOOL, m_good, m_info, Creature::mod_moves(), one_in(), and query_yn().
Referenced by Character::can_pickWeight(), Character::can_pickWeight_partial(), iexamine_functions_from_string(), vehicle::lift_thrust_of_rotorcraft(), spell_effect::short_range_teleport(), sinkhole_safety_roll(), Character::switch_mutations(), teleport::teleport(), teleport::teleport_to_point(), and vehicle::total_power().
shrub_marloss()
void iexamine::shrub_marloss (Character & you, const tripoint & examp)
Definition at line 4477 of file iexamine.cpp.
 {
     if( you.has_trait( trait_THRESH_MYCUS ) ) {
         pick_plant( you, examp, itype_mycus_fruit, ter_t_shrub_fungal );
     } else if( you.has_trait( trait_THRESH_MARLOSS ) ) {
         map &here = get_map();
         here.spawn_item( you.pos(), itype_mycus_fruit, 1, 0, calendar::turn );
         here.ter_set( examp, ter_t_fungus );
         add_msg( m_info, _( "The shrub offers up a fruit, then crumbles into a fungal bed." ) );
     } else {
         pick_plant( you, examp, itype_marloss_berry, ter_t_shrub_fungal );
     }
 }
References _, add_msg(), get_map(), Character::has_trait(), itype_marloss_berry, itype_mycus_fruit, m_info, pick_plant(), Creature::pos(), map::spawn_item(), map::ter_set(), ter_t_fungus, ter_t_shrub_fungal, trait_THRESH_MARLOSS, trait_THRESH_MYCUS, and calendar::turn.
Referenced by iexamine_functions_from_string(), and game::place_player().
shrub_wildveggies()
void iexamine::shrub_wildveggies (Character & you, const tripoint & examp)
Survival speeds up foraging Perception randomly speeds up foraging
Definition at line 4512 of file iexamine.cpp.
 {
     map &here = get_map();
     // Ask if there's something possibly more interesting than this shrub here
     if( ( !here.i_at( examp ).empty() ||
           here.veh_at( examp ) ||
           here.can_see_trap_at( examp, you ) ||
           get_creature_tracker().creature_at( examp ) != nullptr ) &&
         !query_yn( _( "Forage through %s?" ), here.tername( examp ) ) ) {
         none( you, examp );
         return;
     }
     add_msg( _( "You forage through the %s." ), here.tername( examp ) );
     ///\EFFECT_SURVIVAL speeds up foraging
     int move_cost = 100000 / ( 2 * you.get_skill_level( skill_survival ) + 5 );
     ///\EFFECT_PER randomly speeds up foraging
     move_cost /= rng( std::max( 4, you.per_cur ), 4 + you.per_cur * 2 );
     you.assign_activity( forage_activity_actor( move_cost ) );
     you.activity.placement = here.getglobal( examp );
     you.activity.auto_resume = true;
 }
References _, Character::activity, add_msg(), Character::assign_activity(), player_activity::auto_resume, map::can_see_trap_at(), item_stack::empty(), get_creature_tracker(), get_map(), Character::get_skill_level(), map::getglobal(), map::i_at(), max(), none, Character::per_cur, player_activity::placement, query_yn(), rng(), skill_survival, map::tername(), and map::veh_at().
Referenced by iexamine_functions_from_string(), and game::place_player().
sign()
void iexamine::sign (Character & you, const tripoint & examp)
Definition at line 4912 of file iexamine.cpp.
 {
     map &here = get_map();
     std::string existing_signage = here.get_signage( examp );
     bool previous_signage_exists = !existing_signage.empty();
     // Display existing message, or lack thereof.
     if( here.furn( examp )->has_flag( ter_furn_flag::TFLAG_SIGN_ALWAYS ) || previous_signage_exists ) {
         if( you.has_trait( trait_ILLITERATE ) ) {
             popup( _( "You're illiterate, and can't read the message on the sign." ) );
         } else if( previous_signage_exists ) {
             popup( existing_signage );
         } else {
             you.add_msg_if_player( m_neutral, _( "Nothing legible on the sign." ) );
         }
         // Allow chance to modify message.
         std::vector<tool_comp> tools;
         std::vector<const item *> filter = you.crafting_inventory().items_with( []( const item & it ) {
             return it.has_flag( flag_WRITE_MESSAGE ) && it.charges > 0;
         } );
         tools.reserve( filter.size() );
         for( const item *writing_item : filter ) {
             tools.emplace_back( writing_item->typeId(), 1 );
         }
         if( !tools.empty() ) {
             // Different messages if the sign already has writing associated with it.
             std::string query_message = previous_signage_exists ?
                                         _( "Overwrite the existing message on the sign?" ) :
                                         _( "Add a message to the sign?" );
             std::string ignore_message = _( "You leave the sign alone." );
             if( query_yn( query_message ) ) {
                 std::string signage = string_input_popup()
                                       .title( _( "Write what?" ) )
                                       .identifier( "signage" )
                                       .query_string();
                 if( signage.empty() ) {
                     you.add_msg_if_player( m_neutral, ignore_message );
                 } else {
                     std::string spray_painted_message = previous_signage_exists ?
                                                         _( "You overwrite the previous message on the sign with your graffiti." ) :
                                                         _( "You graffiti a message onto the sign." );
                     here.set_signage( examp, signage );
                     you.add_msg_if_player( m_info, spray_painted_message );
                     you.mod_moves( - 20 * signage.length() );
                     you.consume_tools( tools, 1 );
                 }
             } else {
                 you.add_msg_if_player( m_neutral, ignore_message );
             }
         }
     }
 }
References _, Character::add_msg_if_player(), item::charges, Character::consume_tools(), Character::crafting_inventory(), filter, flag_WRITE_MESSAGE, map::furn(), get_map(), map::get_signage(), item::has_flag(), map_data_common_t::has_flag(), Character::has_trait(), string_input_popup::identifier(), visitable::items_with(), m_info, m_neutral, Creature::mod_moves(), popup(), string_input_popup::query_string(), query_yn(), map::set_signage(), TFLAG_SIGN_ALWAYS, string_input_popup::title(), and trait_ILLITERATE.
Referenced by Character::apply_mods(), trade_ui::autobalance(), vehicle::autodrive_controller::compute_next_nodes(), spell_effect::directed_push(), widget::get_var_value(), iexamine_functions_from_string(), player_morale::set_worn(), and musical_instrument_actor::use().
smoker_options()
void iexamine::smoker_options (Character & you, const tripoint & examp)
Definition at line 6921 of file iexamine.cpp.
 {
     map &here = get_map();
     const bool active = here.furn( examp ) == furn_f_smoking_rack_active ||
                         here.furn( examp ) == furn_f_metal_smoking_rack_active;
     const bool portable = here.furn( examp ) == furn_f_metal_smoking_rack ||
                           here.furn( examp ) == furn_f_metal_smoking_rack_active;
     map_stack items_here = here.i_at( examp );
     if( portable && items_here.empty() && active ) {
         debugmsg( "f_metal_smoking_rack_active was empty!" );
         here.furn_set( examp, furn_f_metal_smoking_rack );
         return;
     } else if( items_here.empty() && active ) {
         debugmsg( "f_smoking_rack_active was empty!" );
         here.furn_set( examp, furn_f_smoking_rack );
         return;
     }
     if( portable && items_here.size() == 1 && items_here.begin()->typeId() == itype_fake_smoke_plume ) {
         debugmsg( "f_metal_smoking_rack_active was empty, and had fake_smoke_plume!" );
         here.furn_set( examp, furn_f_metal_smoking_rack );
         items_here.erase( items_here.begin() );
         return;
     } else if( items_here.size() == 1 && items_here.begin()->typeId() == itype_fake_smoke_plume ) {
         debugmsg( "f_smoking_rack_active was empty, and had fake_smoke_plume!" );
         here.furn_set( examp, furn_f_smoking_rack );
         items_here.erase( items_here.begin() );
         return;
     }
     bool rem_f_opt = false;
     time_duration time_left = 0_turns;
     int hours_left = 0;
     int minutes_left = 0;
     units::volume f_volume = 0_ml;
     bool f_check = false;
     for( const item &it : items_here ) {
         if( it.is_food() ) {
             f_check = true;
             f_volume += it.volume();
         }
         if( active && it.typeId() == itype_fake_smoke_plume ) {
             time_left = time_duration::from_turns( it.item_counter );
             hours_left = to_hours<int>( time_left );
             minutes_left = to_minutes<int>( time_left ) + 1;
         }
     }
     const furn_t &f = here.furn( examp ).obj();
     const itype *type = f.crafting_pseudo_item_type();
     std::vector<const itype *> ammo_list = f.crafting_ammo_item_types();
     const bool empty = f_volume == 0_ml;
     const bool full = f_volume >= sm_rack::MAX_FOOD_VOLUME;
     const bool full_portable = f_volume >= sm_rack::MAX_FOOD_VOLUME_PORTABLE;
     const auto remaining_capacity = sm_rack::MAX_FOOD_VOLUME - f_volume;
     const auto remaining_capacity_portable = sm_rack::MAX_FOOD_VOLUME_PORTABLE - f_volume;
     const bool has_coal_in_inventory = you.crafting_inventory().charges_of( itype_charcoal ) > 0;
     const int coal_charges = count_charges_in_list( item::find_type( itype_charcoal ), items_here );
     const int need_charges = get_charcoal_charges( f_volume );
     const int max_charges = type == nullptr || ammo_list.empty() ||
                             !ammo_list[0]->ammo ? 0 : item( type ).ammo_capacity( ammo_list[0]->ammo->type );
     const bool has_coal = coal_charges > 0;
     const bool has_enough_coal = coal_charges >= need_charges;
     uilist smenu;
     smenu.text = _( "What to do with the smoking rack:" );
     smenu.desc_enabled = true;
     smenu.addentry( 0, true, 'i', _( "Inspect smoking rack" ) );
     if( !active ) {
         smenu.addentry_desc( 1, !empty && has_enough_coal, 'l',
                              empty ?  _( "Light up and smoke food insert some food for smoking first" ) :
                              !has_enough_coal ? string_format(
                                  _( "Light up and smoke food need extra %d charges of charcoal" ),
                                  need_charges - coal_charges ) :
                              _( "Light up and smoke food" ),
                              _( "Light up the smoking rack and start smoking.  Smoking will take about 6 hours." ) );
         if( portable ) {
             smenu.addentry_desc( 2, !full_portable, 'f',
                                  full_portable ? _( "Insert food for smoking smoking rack is full" ) :
                                  string_format( _( "Insert food for smoking remaining capacity is %s %s" ),
                                                 format_volume( remaining_capacity_portable ), volume_units_abbr() ),
                                  _( "Fill the smoking rack with raw meat, fish or sausages for smoking or fruit or vegetable or smoked meat for drying." ) );
             smenu.addentry_desc( 8, !active, 'z',
                                  active ? _( "You cannot disassemble this smoking rack while it is active!" ) :
                                  _( "Disassemble the smoking rack" ), "" );
         } else {
             smenu.addentry_desc( 2, !full, 'f',
                                  full ? _( "Insert food for smoking smoking rack is full" ) :
                                  string_format( _( "Insert food for smoking remaining capacity is %s %s" ),
                                                 format_volume( remaining_capacity ), volume_units_abbr() ),
                                  _( "Fill the smoking rack with raw meat, fish or sausages for smoking or fruit or vegetable or smoked meat for drying." ) );
         }
         if( f_check ) {
             smenu.addentry( 4, f_check, 'e', _( "Remove food from smoking rack" ) );
         }
         smenu.addentry_desc( 3, has_coal_in_inventory && coal_charges < max_charges, 'r',
                              !has_coal_in_inventory ? _( "Reload with charcoal you don't have any" ) :
                              ( coal_charges >= max_charges ? _( "Reload with charcoal at maximum capacity" ) :
                                _( "Reload with charcoal" ) ),
                              string_format(
                                  _( "You need %d charges of charcoal for %s %s of food.  Minimal amount of charcoal is %d charges." ),
                                  sm_rack::CHARCOAL_PER_LITER, format_volume( 1_liter ), volume_units_long(),
                                  sm_rack::MIN_CHARCOAL ) );
     } else {
         smenu.addentry_desc( 7, true, 'x',
                              _( "Quench burning charcoal" ),
                              _( "Quenching will stop smoking process, but also destroy all used charcoal." ) );
     }
     if( has_coal ) {
         smenu.addentry( 5, true, 'c',
                         active ? string_format( _( "Rake out %d excess charges of charcoal from smoking rack" ),
                                                 coal_charges ) :
                         string_format( _( "Remove %d charges of charcoal from smoking rack" ), coal_charges ) );
     }
     smenu.query();
     switch( smenu.ret ) {
         case 0: { //inspect smoking rack
             std::string pop;
             if( active ) {
                 pop += colorize( _( "There's a smoking rack here.  It is lit and smoking." ), c_green ) + "\n";
                 if( time_left > 0_turns ) {
                     if( minutes_left > 60 ) {
                         pop += string_format( n_gettext( "It will finish smoking in about %d hour.",
                                                          "It will finish smoking in about %d hours.",
                                                          hours_left ), hours_left ) + "\n\n";
                     } else if( minutes_left > 30 ) {
                         pop += _( "It will finish smoking in less than an hour." ) + std::string( "\n" );
                     } else {
                         pop += string_format( n_gettext( "It should take about %d minute to finish smoking.",
                                                          "It should take about %d minutes to finish smoking.",
                                                          minutes_left ), minutes_left ) + "\n ";
                     }
                 }
             } else {
                 pop += colorize( _( "There's a smoking rack here." ), c_green ) + "\n";
             }
             pop += colorize( _( "You inspect its contents and find: " ), c_green ) + "\n";
             if( items_here.empty() ) {
                 pop += _( "that it is empty." );
             } else {
                 for( const item &it : items_here ) {
                     if( it.typeId() == itype_fake_smoke_plume ) {
                         pop += "\n" + colorize( _( "You see some smoldering embers there." ), c_red ) + "\n";
                         continue;
                     }
                     pop += "-> " + it.display_name() + "\n";
                 }
             }
             popup( pop, PF_NONE );
             break;
         }
         case 1:
             //activate
             if( active ) {
                 add_msg( _( "It is already lit and smoking." ) );
             } else {
                 smoker_activate( you, examp );
             }
             break;
         case 2:
             // load food
             if( portable ) {
                 smoker_load_food( you, examp, remaining_capacity_portable );
             } else {
                 smoker_load_food( you, examp, remaining_capacity );
             }
             break;
         case 3:
             // load charcoal
             reload_furniture( you, examp, false );
             break;
         case 4:
             // remove food
             rem_f_opt = true;
         /* fallthrough */
         case 5: {
             //remove charcoal
             for( map_stack::iterator it = items_here.begin(); it != items_here.end(); ) {
                 if( ( rem_f_opt && it->is_food() ) || ( !rem_f_opt && ( it->typeId() == itype_charcoal ) ) ) {
                     // get handling cost before the item reference is invalidated
                     const int handling_cost = -you.item_handling_cost( *it );
                     add_msg( _( "You remove %s from the rack." ), it->tname() );
                     here.add_item_or_charges( you.pos(), *it );
                     it = items_here.erase( it );
                     you.mod_moves( handling_cost );
                 } else {
                     ++it;
                 }
             }
             if( portable && active && rem_f_opt ) {
                 here.furn_set( examp, furn_f_metal_smoking_rack );
                 add_msg( m_info, _( "You stop the smoking process." ) );
             } else if( active && rem_f_opt ) {
                 here.furn_set( examp, furn_f_smoking_rack );
                 add_msg( m_info, _( "You stop the smoking process." ) );
             }
         }
         break;
         default:
             add_msg( m_info, _( "Never mind." ) );
             break;
         case 7:
             if( portable ) {
                 here.furn_set( examp, furn_f_metal_smoking_rack );
                 add_msg( m_info, _( "You stop the smoking process." ) );
             } else {
                 here.furn_set( examp, furn_f_smoking_rack );
                 add_msg( m_info, _( "You stop the smoking process." ) );
             }
             break;
         case 8:
             here.furn_set( examp, furn_f_metal_smoking_rack );
             deployed_furniture( you, examp );
             break;
     }
 }
References _, map::add_item_or_charges(), add_msg(), uilist::addentry(), uilist::addentry_desc(), item::ammo_capacity(), item_stack::begin(), c_green, c_red, sm_rack::CHARCOAL_PER_LITER, inventory::charges_of(), colorize(), count_charges_in_list(), furn_t::crafting_ammo_item_types(), Character::crafting_inventory(), furn_t::crafting_pseudo_item_type(), debugmsg, deployed_furniture(), uilist::desc_enabled, item::display_name(), item_stack::empty(), item_stack::end(), map_stack::erase(), item::find_type(), format_volume(), time_duration::from_turns(), map::furn(), furn_f_metal_smoking_rack, furn_f_metal_smoking_rack_active, furn_f_smoking_rack, furn_f_smoking_rack_active, map::furn_set(), get_charcoal_charges(), get_map(), map::i_at(), item::is_food(), item::item_counter, Character::item_handling_cost(), itype_charcoal, itype_fake_smoke_plume, m_info, sm_rack::MAX_FOOD_VOLUME, sm_rack::MAX_FOOD_VOLUME_PORTABLE, sm_rack::MIN_CHARCOAL, Creature::mod_moves(), n_gettext, int_id< T >::obj(), PF_NONE, popup(), Creature::pos(), uilist::query(), reload_furniture(), uilist::ret, item_stack::size(), smoker_activate(), smoker_load_food(), string_format(), uilist::text, item::tname(), item::typeId(), item::volume(), volume_units_abbr(), and volume_units_long().
Referenced by iexamine_functions_from_string().
stook_empty()
void iexamine::stook_empty (Character & , const tripoint & examp)
Definition at line 3168 of file iexamine.cpp.
 {
     map &here = get_map();
     furn_id cur_stook_type = here.furn( examp );
     furn_id next_stook_type = furn_str_id::NULL_ID();
     if( cur_stook_type == furn_f_stook_empty ) {
         next_stook_type = furn_f_stook_full;
     } else {
         debugmsg( "Examined furniture has action stook_empty, but is of type %s",
                   here.furn( examp ).id().c_str() );
         return;
     }
     bool grain_present = false;
     map_stack items = here.i_at( examp );
     for( const item &i : items ) {
         if( i.has_flag( flag_FRESH_GRAIN ) && !i.rotten() ) {
             grain_present = true;
         } else {
             add_msg( m_bad, _( "This pile contains %s, which can't be dried here!" ), i.tname( 1,
                      false ) );
             return;
         }
     }
     if( !grain_present ) {
         add_msg( _( "Place some fresh grain here and try again." ) );
         return;
     } else if( !here.is_outside( examp ) ) {
         add_msg( _( "The stook will need to be set up outside to dry." ) );
         return;
     } else {
         add_msg( _( "This pile contains grain that is ready to be left out for drying." ) );
         if( !query_yn( _( "Stand the grain up to dry?" ) ) ) {
             return;
         }
     }
     here.furn_set( examp, next_stook_type );
     add_msg( _( "You set up the stook and leave it to dry." ) );
 }
References _, add_msg(), string_id< T >::c_str(), debugmsg, flag_FRESH_GRAIN, map::furn(), furn_f_stook_empty, furn_f_stook_full, map::furn_set(), get_map(), map::i_at(), int_id< T >::id(), map::is_outside(), m_bad, string_id< furn_t >::NULL_ID(), and query_yn().
Referenced by iexamine_functions_from_string().
stook_full()
void iexamine::stook_full (Character & , const tripoint & examp)
Definition at line 3210 of file iexamine.cpp.
 {
     map &here = get_map();
     furn_id cur_stook_type = here.furn( examp );
     furn_id next_stook_type = furn_str_id::NULL_ID();
     if( cur_stook_type == furn_f_stook_full ) {
         next_stook_type = furn_str_id::NULL_ID();
     } else {
         debugmsg( "Examined furniture has action stook_full, but is of type %s",
                   here.furn( examp ).id().c_str() );
         return;
     }
     map_stack items = here.i_at( examp );
     if( items.empty() ) {
         debugmsg( _( "Examined furniture is stook_full but doesn't contain any grain." ) );
         here.furn_set( examp, next_stook_type );
         return;
     }
     add_msg( _( "There's a grain stook there." ) );
     const item &clock = *items.begin();
     const time_duration drying_time = 336_hours;
     const time_duration time_left = drying_time - clock.age();
     if( time_left > 0_turns ) {
         add_msg( _( "The stook will finish drying in %s." ), to_string( time_left ) );
         return;
     }
     for( item &it : items ) {
         if( it.has_flag( flag_SMOKABLE ) && it.get_comestible() ) {
             item result( it.get_comestible()->smoking_result, it.birthday() );
             recipe rec;
             result.inherit_flags( it, rec );
             if( !result.has_flag( flag_NUTRIENT_OVERRIDE ) ) {
                 // If the item has "cooks_like" it will be replaced by that item as a component.
                 if( !it.get_comestible()->cooks_like.is_empty() ) {
                     // Set charges to 1 for stacking purposes.
                     it = item( it.get_comestible()->cooks_like, it.birthday(), 1 );
                 }
                 result.components.add( it );
             }
             add_msg( _( "You take down the stook as the drying process is now finished." ) );
             it = result;
         }
     }
     here.furn_set( examp, next_stook_type );
 }
References _, item_components::add(), add_msg(), item::age(), item_stack::begin(), string_id< T >::c_str(), item::components, debugmsg, item_stack::empty(), flag_NUTRIENT_OVERRIDE, flag_SMOKABLE, map::furn(), furn_f_stook_full, map::furn_set(), get_map(), item::has_flag(), map::i_at(), int_id< T >::id(), item::inherit_flags(), string_id< furn_t >::NULL_ID(), and to_string().
Referenced by iexamine_functions_from_string().
toPumpFuel()
bool iexamine::toPumpFuel (const tripoint & src, const tripoint & dst, int units)
Definition at line 5105 of file iexamine.cpp.
 {
     map &here = get_map();
     map_stack items = here.i_at( src );
     for( auto item_it = items.begin(); item_it != items.end(); ++item_it ) {
         if( item_it->made_of( phase_id::LIQUID ) ) {
             if( item_it->charges < units ) {
                 return false;
             }
             item_it->charges -= units;
             item liq_d( item_it->type, calendar::turn, units );
             here.add_item_or_charges( dst, liq_d );
             if( item_it->charges < 1 ) {
                 items.erase( item_it );
             }
             return true;
         }
     }
     return false;
 }
References map::add_item_or_charges(), item_stack::begin(), item_stack::end(), map_stack::erase(), get_map(), map::i_at(), LIQUID, and calendar::turn.
Referenced by hacking_activity_actor::finish(), and pay_gas().
translocator()
void iexamine::translocator (Character & you, const tripoint & examp)
Todo:
fix point types
Definition at line 654 of file iexamine.cpp.
 {
     /// @todo fix point types
     const tripoint_abs_omt omt_loc( ms_to_omt_copy( get_map().getabs( examp ) ) );
     avatar &player_character = get_avatar();
     const bool activated = player_character.translocators.knows_translocator( omt_loc );
     if( !activated ) {
         player_character.translocators.activate_teleporter( omt_loc, examp );
         add_msg( m_info, _( "Translocator gate active." ) );
     } else {
         if( query_yn( _( "Do you want to deactivate this active Translocator?" ) ) ) {
             player_character.translocators.deactivate_teleporter( omt_loc, examp );
         }
     }
 }
References _, teleporter_list::activate_teleporter(), add_msg(), teleporter_list::deactivate_teleporter(), get_avatar(), get_map(), teleporter_list::knows_translocator(), m_info, ms_to_omt_copy(), query_yn(), and avatar::translocators.
Referenced by iexamine_functions_from_string().
tree_hickory()
void iexamine::tree_hickory (Character & you, const tripoint & examp)
Survival increases hickory root number per tree Survival speeds up hickory root digging
Definition at line 4284 of file iexamine.cpp.
 {
     bool auto_forage = get_option<bool>( "AUTO_FEATURES" ) &&
                        ( get_option<std::string>( "AUTO_FORAGING" ) == "all" ||
                          get_option<std::string>( "AUTO_FORAGING" ) == "trees" );
     bool digging_up = false;
     map &here = get_map();
     if( !auto_forage && you.is_avatar() && you.has_quality( qual_DIG ) &&
         query_yn( _( "Dig up %s?  This kills the tree!" ), here.tername( examp ) ) ) {
         digging_up = true;
         /** @EFFECT_SURVIVAL increases hickory root number per tree */
         here.spawn_item( you.pos(), itype_hickory_root, rng( 1,
                          round( 3 + you.get_skill_level( skill_survival ) ) ),
                          0,
                          calendar::turn );
         here.ter_set( examp, ter_t_tree_hickory_dead );
         /** @EFFECT_SURVIVAL speeds up hickory root digging */
         you.mod_moves( -to_moves<int>( 20_seconds ) / ( you.get_skill_level( skill_survival ) + 1 ) + 100 );
     }
     if( !auto_forage && !digging_up && you.is_avatar() ) {
         you.add_msg_if_player( _( "You could dig this tree up for roots" ) );
     }
     if( !auto_forage && !query_pick( you, examp ) ) {
         return;
     }
     you.assign_activity( harvest_activity_actor( examp, auto_forage ) );
 }
References _, Character::add_msg_if_player(), Character::assign_activity(), get_map(), Character::get_skill_level(), Character::has_quality(), Creature::is_avatar(), itype_hickory_root, Creature::mod_moves(), Creature::pos(), qual_DIG, query_pick(), query_yn(), rng(), round(), skill_survival, map::spawn_item(), map::ter_set(), ter_t_tree_hickory_dead, map::tername(), and calendar::turn.
Referenced by iexamine_functions_from_string().
tree_maple()
void iexamine::tree_maple (Character & you, const tripoint & examp)
Definition at line 4326 of file iexamine.cpp.
 {
     const inventory &crafting_inv = you.crafting_inventory();
     if( !crafting_inv.has_quality( qual_DRILL ) ) {
         add_msg( m_info, _( "You need a tool to drill the crust to tap this maple tree." ) );
         return;
     }
     if( !crafting_inv.has_quality( qual_HAMMER ) ) {
         add_msg( m_info,
                  _( "You need a tool to hammer the spile into the crust to tap this maple tree." ) );
         return;
     }
     map &here = get_map();
     item_location spile_loc = g->inv_map_splice( [&here]( const item_location & it ) {
         return it->get_quality_nonrecursive( qual_TREE_TAP ) > 0 &&
                !( here.ter( it.position() ) == ter_t_tree_maple_tapped );
     }, _( "Use which tapping tool?" ), PICKUP_RANGE, _( "You don't have a tapping tool at hand." ) );
     item *spile = spile_loc.get_item();
     if( !spile ) {
         return;
     }
     std::string spile_name = spile->tname();
     you.mod_moves( -to_moves<int>( 20_seconds ) );
     here.ter_set( examp, ter_t_tree_maple_tapped );
     here.add_item_or_charges( examp, *spile, false );
     spile_loc.remove_item();
     add_msg( m_info, _( "You drill the maple tree crust and tap a %s into the prepared hole." ),
              spile_name );
     item_location cont_loc = maple_tree_sap_container();
     item *container = cont_loc.get_item();
     if( container ) {
         here.add_item_or_charges( examp, *container, false );
         add_msg( m_info, _( "You hang the %s under the %s to collect sap." ), container->tname(),
                  spile_name );
         cont_loc.remove_item();
     } else {
         add_msg( m_info, _( "No container added.  The sap will just spill on the ground." ) );
     }
 }
References _, map::add_item_or_charges(), add_msg(), Character::crafting_inventory(), g, item_location::get_item(), get_map(), item::get_quality_nonrecursive(), inventory::has_quality(), m_info, maple_tree_sap_container(), Creature::mod_moves(), PICKUP_RANGE, item_location::position(), qual_DRILL, qual_HAMMER, qual_TREE_TAP, item_location::remove_item(), map::ter(), map::ter_set(), ter_t_tree_maple_tapped, and item::tname().
Referenced by iexamine_functions_from_string().
tree_maple_tapped()
void iexamine::tree_maple_tapped (Character & you, const tripoint & examp)
Definition at line 4372 of file iexamine.cpp.
 {
     bool has_sap = false;
     item *container = nullptr;
     item *spile = nullptr;
     int charges = 0;
     const std::string maple_sap_name = item::nname( itype_maple_sap );
     map &here = get_map();
     map_stack items = here.i_at( examp );
     for( item &it : items ) {
         if( it.will_spill() || it.is_watertight_container() ) {
             container = &it;
             it.visit_items( [&charges, &has_sap]( const item * it, item * ) {
                 if( it->typeId() == itype_maple_sap ) {
                     has_sap = true;
                     charges = it->charges;
                     return VisitResponse::ABORT;
                 }
                 return VisitResponse::NEXT;
             } );
         }
         if( it.get_quality_nonrecursive( qual_TREE_TAP ) > 0 ) {
             spile = &it;
         }
     }
     if( !spile ) {
         return;
     }
     enum options {
         REMOVE_TAP,
         ADD_CONTAINER,
         HARVEST_SAP,
         REMOVE_CONTAINER,
     };
     uilist selectmenu;
     selectmenu.addentry( REMOVE_TAP, true, MENU_AUTOASSIGN, _( "Remove tap" ) );
     selectmenu.addentry( ADD_CONTAINER, !container, MENU_AUTOASSIGN,
                          _( "Add a container to receive the %s" ), maple_sap_name );
     selectmenu.addentry( HARVEST_SAP, has_sap, MENU_AUTOASSIGN, _( "Harvest current %s (%d)" ),
                          maple_sap_name, charges );
     selectmenu.addentry( REMOVE_CONTAINER, container, MENU_AUTOASSIGN, _( "Remove container" ) );
     selectmenu.text = _( "Select an action" );
     selectmenu.query();
     switch( selectmenu.ret ) {
         case REMOVE_TAP: {
             if( !you.crafting_inventory().has_quality( qual_HAMMER ) ) {
                 add_msg( m_info, _( "You need a hammering tool to remove the %s from the crust." ),
                          spile->tname() );
                 return;
             }
             add_msg( _( "You remove the %s." ), spile->tname() );
             here.add_item_or_charges( you.pos(), *spile );
             if( container ) {
                 here.add_item_or_charges( you.pos(), *container );
             }
             here.i_clear( examp );
             you.mod_moves( -to_moves<int>( 20_seconds ) );
             here.ter_set( examp, ter_t_tree_maple );
             return;
         }
         case ADD_CONTAINER: {
             item_location cont_loc = maple_tree_sap_container();
             container = cont_loc.get_item();
             if( container ) {
                 here.add_item_or_charges( examp, *container, false );
                 you.mod_moves( -you.item_handling_cost( *container ) );
                 add_msg( m_info, _( "You hang the %s under the spile to collect sap." ), container->tname() );
                 cont_loc.remove_item();
             } else {
                 add_msg( m_info, _( "No container added.  The sap will just spill on the ground." ) );
             }
             return;
         }
         case HARVEST_SAP: {
             liquid_handler::handle_liquid_from_container( *container, PICKUP_RANGE );
             return;
         }
         case REMOVE_CONTAINER: {
             here.add_item_or_charges( you.pos(), *container );
             you.mod_moves( -you.item_handling_cost( *container ) );
             here.i_rem( examp, container );
             return;
         }
         default:
             return;
     }
 }
References _, map::add_item_or_charges(), add_msg(), uilist::addentry(), Character::crafting_inventory(), item_location::get_item(), get_map(), liquid_handler::handle_liquid_from_container(), inventory::has_quality(), map::i_at(), map::i_clear(), map::i_rem(), Character::item_handling_cost(), itype_maple_sap, m_info, maple_tree_sap_container(), MENU_AUTOASSIGN, Creature::mod_moves(), NEXT, item::nname(), PATH_INFO::options(), PICKUP_RANGE, Creature::pos(), qual_HAMMER, qual_TREE_TAP, uilist::query(), item_location::remove_item(), uilist::ret, map::ter_set(), ter_t_tree_maple, uilist::text, item::tname(), item::typeId(), and item::visit_items().
Referenced by iexamine_functions_from_string().
tree_marloss()
void iexamine::tree_marloss (Character & you, const tripoint & examp)
Definition at line 4491 of file iexamine.cpp.
 {
     map &here = get_map();
     if( you.has_trait( trait_THRESH_MYCUS ) ) {
         pick_plant( you, examp, itype_mycus_fruit, ter_t_tree_fungal );
         if( you.has_trait( trait_M_DEPENDENT ) && one_in( 3 ) ) {
             // Folks have a better shot at keeping fed.
             add_msg( m_info,
                      _( "We have located a particularly vital nutrient deposit underneath this location." ) );
             add_msg( m_good, _( "Additional nourishment is available." ) );
             here.ter_set( examp, ter_t_marloss_tree );
         }
     } else if( you.has_trait( trait_THRESH_MARLOSS ) ) {
         here.spawn_item( you.pos(), itype_mycus_fruit, 1, 0, calendar::turn );
         here.ter_set( examp, ter_t_tree_fungal );
         add_msg( m_info, _( "The tree offers up a fruit, then shrivels into a fungal tree." ) );
     } else {
         pick_plant( you, examp, itype_marloss_berry, ter_t_tree_fungal );
     }
 }
References _, add_msg(), get_map(), Character::has_trait(), itype_marloss_berry, itype_mycus_fruit, m_good, m_info, one_in(), pick_plant(), Creature::pos(), map::spawn_item(), map::ter_set(), ter_t_marloss_tree, ter_t_tree_fungal, trait_M_DEPENDENT, trait_THRESH_MARLOSS, trait_THRESH_MYCUS, and calendar::turn.
Referenced by iexamine_functions_from_string(), and game::place_player().
try_start_hacking()
bool iexamine::try_start_hacking (Character & you, const tripoint & examp)
Definition at line 1397 of file iexamine.cpp.
 {
     if( !can_hack( you ) ) {
         return false;
     } else {
         item_location hacking_tool = item_location{you, &you.best_item_with_quality( qual_HACK )};
         hacking_tool->ammo_consume( hacking_tool->ammo_required(), hacking_tool.position(), &you );
         you.assign_activity( hacking_activity_actor( hacking_tool ) );
         you.activity.placement = get_map().getglobal( examp );
         return true;
     }
 }
References Character::activity, item::ammo_consume(), item::ammo_required(), Character::assign_activity(), Character::best_item_with_quality(), can_hack(), get_map(), map::getglobal(), player_activity::placement, item_location::position(), and qual_HACK.
Referenced by cardreader_examine_actor::call(), cardreader_foodplace(), gunsafe_el(), and pay_gas().
vending()
void iexamine::vending (Character & you, const tripoint & examp)
Generates vending machine UI and allows players to purchase contained items with a cash card.
Definition at line 1024 of file iexamine.cpp.
 {
     constexpr int moves_cost = to_moves<int>( 5_seconds );
     int money = you.charges_of( itype_cash_card );
     map_stack vend_items = get_map().i_at( examp );
     if( vend_items.empty() ) {
         add_msg( m_info, _( "The vending machine is empty." ) );
         return;
     }
     if( !money ) {
         popup( _( "You need some money on a cash card to buy things." ) );
     }
     int w_items_w = 0;
     int w_info_w = 0;
     int list_lines = 0;
     int lines_above = 0;
     int lines_below = 0;
     constexpr int first_item_offset = 3; // header size
     catacurses::window w;
     catacurses::window w_item_info;
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         const point padding( std::max( 0, TERMX - FULL_SCREEN_WIDTH ) / 4, std::max( 0,
                              TERMY - FULL_SCREEN_HEIGHT ) / 6 );
         const int window_h   = FULL_SCREEN_HEIGHT + std::max( 0, TERMY - FULL_SCREEN_HEIGHT ) * 2 / 3;
         const int window_w   = FULL_SCREEN_WIDTH + std::max( 0, TERMX - FULL_SCREEN_WIDTH ) / 2;
         w_items_w  = window_w / 2;
         w_info_w   = window_w - w_items_w;
         list_lines = window_h - 4; // minus for header and footer
         lines_above = list_lines / 2;                  // lines above the selector
         lines_below = list_lines / 2 + list_lines % 2; // lines below the selector
         w = catacurses::newwin( window_h, w_items_w,
                                 padding );
         w_item_info = catacurses::newwin( window_h, w_info_w,
                                           padding + point( w_items_w, 0 ) );
         ui.position( padding, point( window_w, window_h ) );
     } );
     ui.mark_resize();
     bool used_machine = false;
     input_context ctxt( "VENDING_MACHINE" );
     ctxt.register_navigate_ui_list();
     ctxt.register_action( "SCROLL_ITEM_INFO_UP" );
     ctxt.register_action( "SCROLL_ITEM_INFO_DOWN" );
     ctxt.register_action( "CONFIRM" );
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     // Collate identical items.
     // First, build a map {item::tname} => {item_it, item_it, item_it...}
     using iterator_t = decltype( std::begin( vend_items ) ); // map_stack::iterator doesn't exist.
     std::map<std::string, std::vector<iterator_t>> item_map;
     for( auto it = std::begin( vend_items ); it != std::end( vend_items ); ++it ) {
         // |# {name}|
         // 123      4
         std::string suffix = it->count() > 1 ? string_format( " (%d)", it->count() ) : "";
         item_map[it->tname() + suffix].push_back( it );
     }
     // Next, put pointers to the pairs in the map in a vector to allow indexing.
     std::vector<std::map<std::string, std::vector<iterator_t>>::value_type *> item_list;
     item_list.reserve( item_map.size() );
     for( auto &pair : item_map ) {
         item_list.emplace_back( &pair );
     }
     int cur_pos = 0;
     int item_info_scroll_pos = 0;
     const int &item_info_scroll_delta = list_lines;
     ui.on_redraw( [&]( const ui_adaptor & ) {
         const int num_items = item_list.size();
         const int page_size = std::min( num_items, list_lines );
         werase( w );
         wborder( w, LINE_XOXO, LINE_XOXO, LINE_OXOX, LINE_OXOX,
                  LINE_OXXO, LINE_OOXX, LINE_XXOO, LINE_XOOX );
         mvwhline( w, point( 1, first_item_offset - 1 ), LINE_OXOX, w_items_w - 2 );
         mvwaddch( w, point( 0, first_item_offset - 1 ), LINE_XXXO ); // |-
         mvwaddch( w, point( w_items_w - 1, first_item_offset - 1 ), LINE_XOXX ); // -|
         trim_and_print( w, point( 2, 1 ), w_items_w - 3, c_light_gray,
                         _( "Money left: %s" ), format_money( money ) );
         // Keep the item selector centered in the page.
         int page_beg;
         if( cur_pos < num_items - cur_pos ) {
             page_beg = std::max( 0, cur_pos - lines_above );
         } else {
             int page_end = std::min( num_items, cur_pos + lines_below );
             page_beg = std::max( 0, page_end - list_lines );
         }
         for( int line = 0; line < page_size; ++line ) {
             const int i = page_beg + line;
             const nc_color color = ( i == cur_pos ) ? h_light_gray : c_light_gray;
             const auto &elem = item_list[i];
             const int count = elem->second.size();
             const char c = ( count < 10 ) ? ( '0' + count ) : '*';
             trim_and_print( w, point( 1, first_item_offset + line ), w_items_w - 3, color, "%c %s", c,
                             elem->first.c_str() );
         }
         draw_scrollbar( w, cur_pos, list_lines, num_items, point( 0, first_item_offset ) );
         wnoutrefresh( w );
         // Item info
         auto &cur_items = item_list[static_cast<size_t>( cur_pos )]->second;
         auto &cur_item  = cur_items.back();
         std::vector<iteminfo> cur_item_info;
         cur_item->info( true, cur_item_info );
         item_info_data data( cur_item->display_name(), "", cur_item_info, {}, item_info_scroll_pos );
         data.without_getch = true;
         draw_item_info( w_item_info, data );
     } );
     for( ;; ) {
         ui_manager::redraw();
         const int num_items = item_list.size();
         // Item info
         auto &cur_items = item_list[static_cast<size_t>( cur_pos )]->second;
         auto &cur_item  = cur_items.back();
         const std::string &action = ctxt.handle_input();
         if( navigate_ui_list( action, cur_pos, 3, num_items, true ) ) {
             item_info_scroll_pos = 0;
         } else if( action == "SCROLL_ITEM_INFO_UP" ) {
             // clamping to min/max is done in draw_item_info
             item_info_scroll_pos -= item_info_scroll_delta;
         } else if( action == "SCROLL_ITEM_INFO_DOWN" ) {
             item_info_scroll_pos += item_info_scroll_delta;
         } else if( action == "CONFIRM" ) {
             const int iprice = cur_item->price( false );
             if( iprice > money ) {
                 popup( _( "You can't afford that item." ) );
                 continue;
             }
             if( !used_machine ) {
                 used_machine = true;
                 you.mod_moves( -moves_cost );
             }
             money -= iprice;
             you.use_charges( itype_cash_card, iprice );
             you.i_add_or_drop( *cur_item );
             vend_items.erase( cur_item );
             cur_items.pop_back();
             if( !cur_items.empty() ) {
                 continue;
             }
             item_info_scroll_pos = 0;
             item_list.erase( std::begin( item_list ) + cur_pos );
             if( item_list.empty() ) {
                 add_msg( _( "With a beep, the empty vending machine shuts down." ) );
                 return;
             } else if( cur_pos == num_items - 1 ) {
                 cur_pos--;
             }
         } else if( action == "QUIT" ) {
             break;
         }
     }
 }
References _, action, add_msg(), c, c_light_gray, Character::charges_of(), color(), draw_item_info(), draw_scrollbar(), item_stack::empty(), keycode::end, map_stack::erase(), format_money(), FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH, get_map(), h_light_gray, input_context::handle_input(), Character::i_add_or_drop(), map::i_at(), itype_cash_card, line(), LINE_OOXX, LINE_OXOX, LINE_OXXO, LINE_XOOX, LINE_XOXO, LINE_XOXX, LINE_XXOO, LINE_XXXO, m_info, max(), min(), Creature::mod_moves(), catacurses::mvwaddch(), catacurses::mvwhline(), navigate_ui_list(), catacurses::newwin(), popup(), ui_manager::redraw(), input_context::register_action(), input_context::register_navigate_ui_list(), second, string_format(), TERMX, TERMY, trim_and_print(), Character::use_charges(), catacurses::wborder(), catacurses::werase(), item_info_data::without_getch, and catacurses::wnoutrefresh().
Referenced by iexamine_functions_from_string().
water_source()
void iexamine::water_source (Character & , const tripoint & examp)
Definition at line 4658 of file iexamine.cpp.
 {
     map &here = get_map();
     item water = here.water_from( examp );
     liquid_handler::handle_liquid( water, nullptr, 0, &examp );
 }
References get_map(), liquid_handler::handle_liquid(), water, and map::water_from().
Referenced by colorized_ter_name_flags_at(), iexamine_functions_from_string(), and map::water_from().
workbench()
void iexamine::workbench (Character & you, const tripoint & examp)
Definition at line 7156 of file iexamine.cpp.
 {
     if( get_option<bool>( "WORKBENCH_ALL_OPTIONS" ) ) {
         workbench_internal( you, examp, std::nullopt );
     } else {
         if( !get_map().i_at( examp ).empty() ) {
             g->pickup( examp );
         }
         if( item::type_is_defined( get_map().furn( examp ).obj().deployed_item ) ) {
             deployed_furniture( you, examp );
         }
     }
 }
References deployed_furniture(), g, get_map(), int_id< T >::obj(), item::type_is_defined(), and workbench_internal().
Referenced by game::examine(), iexamine_functions_from_string(), and set_item_map_or_vehicle().
workbench_internal()
void iexamine::workbench_internal (Character & you, const tripoint & examp, const std::optional< vpart_reference > & part)
Definition at line 7170 of file iexamine.cpp.
 {
     std::vector<item_location> crafts;
     std::string name;
     bool is_undeployable = false;
     bool items_at_loc = false;
     map &here = get_map();
     if( part ) {
         name = part->part().name();
         for( item &it : part->items() ) {
             if( it.is_craft() ) {
                 crafts.emplace_back( vehicle_cursor( part->vehicle(), part->part_index() ), &it );
             }
         }
     } else {
         name = here.furn( examp ).obj().name();
         if( item::type_is_defined( here.furn( examp ).obj().deployed_item ) ) {
             is_undeployable = true;
         }
         map_stack items_at_furn = here.i_at( examp );
         items_at_loc = !items_at_furn.empty();
         for( item &it : items_at_furn ) {
             if( it.is_craft() ) {
                 crafts.emplace_back( map_cursor( examp ), &it );
             }
         }
     }
     uilist amenu;
     enum option : int {
         start_craft = 0,
         repeat_craft,
         start_long_craft,
         work_on_craft,
         get_items,
         undeploy
     };
     amenu.text = string_format( pgettext( "furniture", "What to do at the %s?" ), name );
     amenu.addentry( start_craft,      true,            '1', _( "Craft items" ) );
     amenu.addentry( repeat_craft,     true,            '2', _( "Recraft last recipe" ) );
     amenu.addentry( start_long_craft, true,            '3', _( "Craft as long as possible" ) );
     amenu.addentry( work_on_craft,    !crafts.empty(), '4', _( "Work on craft or disassembly" ) );
     if( !part && here.has_items( examp ) ) {
         amenu.addentry( get_items,    items_at_loc,    'g', _( "Get items" ) );
     }
     if( is_undeployable ) {
         amenu.addentry( undeploy,     true,            't', _( "Take down the %s" ), name );
     }
     amenu.query();
     const option choice = static_cast<option>( amenu.ret );
     bool in_shell = you.has_active_mutation( trait_SHELL2 ) ||
                     you.has_active_mutation( trait_SHELL3 );
     switch( choice ) {
         case start_craft: {
             if( in_shell ) {
                 you.add_msg_if_player( m_info, _( "You can't craft while you're in your shell." ) );
             } else if( you.has_effect( effect_incorporeal ) ) {
                 add_msg( m_info, _( "You lack the substance to affect anything." ) );
             } else {
                 you.craft( examp );
             }
             break;
         }
         case repeat_craft: {
             if( in_shell ) {
                 you.add_msg_if_player( m_info, _( "You can't craft while you're in your shell." ) );
             } else if( you.has_effect( effect_incorporeal ) ) {
                 add_msg( m_info, _( "You lack the substance to affect anything." ) );
             } else {
                 you.recraft( examp );
             }
             break;
         }
         case start_long_craft: {
             if( in_shell ) {
                 you.add_msg_if_player( m_info, _( "You can't craft while you're in your shell." ) );
             } else if( you.has_effect( effect_incorporeal ) ) {
                 add_msg( m_info, _( "You lack the substance to affect anything." ) );
             } else {
                 you.long_craft( examp );
             }
             break;
         }
         case work_on_craft: {
             std::vector<std::string> item_names;
             for( item_location &it : crafts ) {
                 if( it ) {
                     item_names.emplace_back( it.get_item()->tname() );
                 }
             }
             uilist amenu2( _( "Which craft or disassembly to work on?" ), item_names );
             if( amenu2.ret == UILIST_CANCEL ) {
                 break;
             }
             item *selected_craft = crafts[amenu2.ret].get_item();
             if( !selected_craft ) {
                 break;
             }
             if( selected_craft->typeId() == itype_disassembly ) {
                 you.disassemble( crafts[amenu2.ret], true );
             } else {
                 if( !you.can_continue_craft( *selected_craft ) ) {
                     break;
                 }
                 const recipe &rec = selected_craft->get_making();
                 if( !you.has_recipe( &rec ) ) {
                     you.add_msg_player_or_npc(
                         _( "You don't know the recipe for the %s and can't continue crafting." ),
                         _( "<npcname> doesn't know the recipe for the %s and can't continue crafting." ),
                         rec.result_name() );
                     break;
                 }
                 you.add_msg_player_or_npc(
                     pgettext( "in progress craft", "You start working on the %s." ),
                     pgettext( "in progress craft", "<npcname> starts working on the %s." ),
                     selected_craft->tname() );
                 you.assign_activity( craft_activity_actor( crafts[amenu2.ret], false ) );
             }
             break;
         }
         case get_items: {
             g->pickup( examp );
             break;
         }
         case undeploy: {
             deployed_furniture( you, examp );
             break;
         }
     }
 }
References _, add_msg(), Character::add_msg_if_player(), Character::add_msg_player_or_npc(), uilist::addentry(), Character::assign_activity(), Character::can_continue_craft(), Character::craft(), deployed_furniture(), furn_t::deployed_item, Character::disassemble(), effect_incorporeal, item_stack::empty(), map::furn(), g, item::get_making(), get_map(), Character::has_active_mutation(), Creature::has_effect(), map::has_items(), Character::has_recipe(), map::i_at(), item::is_craft(), itype_disassembly, Character::long_craft(), m_info, map_data_common_t::name(), om_direction::name(), int_id< T >::obj(), pgettext, uilist::query(), Character::recraft(), recipe::result_name(), uilist::ret, string_format(), uilist::text, item::tname(), trait_SHELL2, trait_SHELL3, item::type_is_defined(), item::typeId(), and UILIST_CANCEL.
Referenced by workbench().
workout()
void iexamine::workout (Character & you, const tripoint & examp)
Definition at line 7313 of file iexamine.cpp.
 {
     if( !query_yn( _( "Use the %s to exercise?" ), get_map().furnname( examp ) ) ) {
         none( you, examp );
         return;
     }
     you.assign_activity( workout_activity_actor( examp ) );
 }
References _, Character::assign_activity(), get_map(), none, and query_yn().
Referenced by iexamine_functions_from_string().