Cataclysm DDA: anonymous_namespace{gates.cpp} Namespace Reference
anonymous_namespace{gates.cpp} Namespace Reference
Classes
struct gate_data
Typedefs
using gate_id = string_id< gate_data >
Functions
gate_id get_gate_id (const tripoint_bub_ms &pos)
Variables
generic_factory< gate_data > gates_data ("gate type")
Typedef Documentation
gate_id
using anonymous_namespace{gates.cpp}::gate_id = typedef string_id<gate_data>
Definition at line 45 of file gates.cpp.
Function Documentation
get_gate_id()
gate_id anonymous_namespace{gates.cpp}::get_gate_id (const tripoint_bub_ms & pos)
Definition at line 76 of file gates.cpp.
 {
     return gate_id( get_map().ter( pos ).id().str() );
 }
References get_map(), and math_opers::pos().
Referenced by gates::open_gate().
Variable Documentation
gates_data
generic_factory<gate_data> anonymous_namespace{gates.cpp}::gates_data("gate type") ("gate type")
Referenced by gates::check(), gates::load(), gates::open_gate(), and gates::reset().