Cataclysm DDA: rotatable_symbols Namespace Reference
rotatable_symbols Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void reset ()
uint32_t get (const uint32_t &symbol, int n)
Function Documentation
get()
uint32_t rotatable_symbols::get (const uint32_t & symbol, int n)
Definition at line 91 of file rotatable_symbols.cpp.
 {
     n = std::abs( n ) % 4;
     if( n == 0 ) {
         return symbol;
     }
     const auto iter = std::lower_bound( symbols.begin(), symbols.end(), symbol );
     const bool found = iter != symbols.end() && iter->symbol == symbol;
     return found ? iter->rotated_symbol[n - 1] : symbol;
 }
References abs(), symbol(), and anonymous_namespace{rotatable_symbols.cpp}::symbols.
Referenced by display::current_position_text(), cata::value_ptr< T >::deserialize(), game::do_regular_action(), creature_tracker::find_reachable(), get_part_helper(), worldfactory::init(), game::print_terrain_info(), om_direction::rotate_symbol(), cata::value_ptr< T >::serialize(), avatar::should_show_map_memory(), editmap::update_view_with_help(), monster::will_reach(), and game::zones_manager().
load()
void rotatable_symbols::load (const JsonObject & jo, const std::string & src)
Definition at line 38 of file rotatable_symbols.cpp.
 {
     const std::string tuple_key = "tuple";
     const bool strict = src == "dda";
     std::vector<std::string> tuple_temp;
     mandatory( jo, false, tuple_key, tuple_temp );
     if( tuple_temp.size() != 2 && tuple_temp.size() != 4 ) {
         jo.throw_error_at( tuple_key, "Invalid size.  Must be either 2 or 4." );
     }
     std::vector<uint32_t> tuple;
     tuple.reserve( tuple_temp.size() );
     for( std::string &elem : tuple_temp ) {
         tuple.emplace_back( UTF8_getch( elem ) );
     }
     rotatable_symbol temp_entry;
     for( auto iter = tuple.cbegin(); iter != tuple.cend(); ++iter ) {
         const auto entry_iter = std::lower_bound( symbols.begin(), symbols.end(), *iter );
         const bool found = entry_iter != symbols.end() && entry_iter->symbol == *iter;
         if( strict && found ) {
             jo.throw_error_at(
                 tuple_key, string_format( "Symbol %ld was already defined.", *iter ) );
         }
         rotatable_symbol &entry = found ? *entry_iter : temp_entry;
         entry.symbol = *iter;
         auto rotation_iter = iter;
         for( unsigned int &element : entry.rotated_symbol ) {
             if( ++rotation_iter == tuple.cend() ) {
                 rotation_iter = tuple.cbegin();
             }
             element = *rotation_iter;
         }
         if( !found ) {
             symbols.insert( entry_iter, entry );
         }
     }
 }
References mandatory(), strict, string_format(), anonymous_namespace{rotatable_symbols.cpp}::symbols, JsonObject::throw_error_at(), and UTF8_getch().
Referenced by DynamicDataLoader::initialize().
reset()
void rotatable_symbols::reset ()
Definition at line 86 of file rotatable_symbols.cpp.
 {
     symbols.clear();
 }
References anonymous_namespace{rotatable_symbols.cpp}::symbols.
Referenced by DynamicDataLoader::unload_data().