Cataclysm DDA: anonymous_namespace{math_parser_diag_value.cpp} Namespace Reference
anonymous_namespace{math_parser_diag_value.cpp} Namespace Reference
Functions
template<typename T >
constexpr std::string_view _str_type_of (T)
template<class C , class R = C, bool at_runtime = false>
constexpr R _diag_value_at_parse_time (diag_value::impl_t const &data)
Function Documentation
_diag_value_at_parse_time()
template<class C , class R = C, bool at_runtime = false> constexpr R anonymous_namespace{math_parser_diag_value.cpp}::_diag_value_at_parse_time (diag_value::impl_t const & data) constexpr
Definition at line 33 of file math_parser_diag_value.cpp.
 {
     return std::visit( overloaded{
         []( C const & v ) -> R
         {
             return v;
         },
         []( auto const & v ) -> R
         {
             if constexpr( at_runtime )
             {
                 debugmsg( "Expected %s, got %s", _str_type_of( C{} ), _str_type_of( v ) );
                 static R null_R{};
                 return null_R;
             } else
             {
                 throw std::invalid_argument( string_format( "Expected %s, got %s", _str_type_of( C{} ),
                                              _str_type_of( v ) ) );
             }
         },
     },
     data );
 }
References _str_type_of(), debugmsg, and string_format().
_str_type_of()
template<typename T > constexpr std::string_view anonymous_namespace{math_parser_diag_value.cpp}::_str_type_of (T) constexpr
Definition at line 16 of file math_parser_diag_value.cpp.
 {
     if constexpr( std::is_same_v<T, double> ) {
         return "double";
     } else if constexpr( std::is_same_v<T, std::string> ) {
         return "string";
     } else if constexpr( std::is_same_v<T, var_info> ) {
         return "variable";
     } else if constexpr( std::is_same_v<T, math_exp> ) {
         return "sub-expression";
     } else if constexpr( std::is_same_v<T, diag_array> ) {
         return "array";
     }
     return "cookies";
 }
Referenced by _diag_value_at_parse_time().