Cataclysm DDA: turn_handler Namespace Reference
turn_handler Namespace Reference
Functions
bool cleanup_at_end ()
Function Documentation
cleanup_at_end()
bool turn_handler::cleanup_at_end ()
Definition at line 103 of file do_turn.cpp.
 {
     avatar &u = get_avatar();
     if( g->uquit == QUIT_DIED || g->uquit == QUIT_SUICIDE ) {
         // Put (non-hallucinations) into the overmap so they are not lost.
         for( monster &critter : g->all_monsters() ) {
             g->despawn_monster( critter );
         }
         // if player has "hunted" trait, remove their nemesis monster on death
         if( u.has_trait( trait_HAS_NEMESIS ) ) {
             overmap_buffer.remove_nemesis();
         }
         // Reset NPC factions and disposition
         g->reset_npc_dispositions();
         // Save the factions', missions and set the NPC's overmap coordinates
         // Npcs are saved in the overmap.
         g->save_factions_missions_npcs(); //missions need to be saved as they are global for all saves.
         // and the overmap, and the local map.
         g->save_maps(); //Omap also contains the npcs who need to be saved.
         //save achievements entry
         g->save_achievements();
         g->death_screen();
         std::chrono::seconds time_since_load =
             std::chrono::duration_cast<std::chrono::seconds>(
                 std::chrono::steady_clock::now() - g->time_of_last_load );
         std::chrono::seconds total_time_played = g->time_played_at_last_load + time_since_load;
         get_event_bus().send<event_type::game_over>( total_time_played );
         // Struck the save_player_data here to forestall Weirdness
         g->move_save_to_graveyard();
         g->write_memorial_file( g->stats().value_of( event_statistic_last_words )
                                 .get<cata_variant_type::string>() );
         get_memorial().clear();
         std::vector<std::string> characters = g->list_active_saves();
         // remove current player from the active characters list, as they are dead
         std::vector<std::string>::iterator curchar = std::find( characters.begin(),
                 characters.end(), u.get_save_id() );
         if( curchar != characters.end() ) {
             characters.erase( curchar );
         }
         if( characters.empty() ) {
             bool queryDelete = false;
             bool queryReset = false;
             if( get_option<std::string>( "WORLD_END" ) == "query" ) {
                 bool decided = false;
                 std::string buffer = _( "Warning: NPC interactions and some other global flags "
                                         "will not all reset when starting a new character in an "
                                         "already-played world.  This can lead to some strange "
                                         "behavior.\n\n"
                                         "Are you sure you wish to keep this world?"
                                       );
                 while( !decided ) {
                     uilist smenu;
                     smenu.allow_cancel = false;
                     smenu.addentry( 0, true, 'r', "%s", _( "Reset world" ) );
                     smenu.addentry( 1, true, 'd', "%s", _( "Delete world" ) );
                     smenu.addentry( 2, true, 'k', "%s", _( "Keep world" ) );
                     smenu.query();
                     switch( smenu.ret ) {
                         case 0:
                             queryReset = true;
                             decided = true;
                             break;
                         case 1:
                             queryDelete = true;
                             decided = true;
                             break;
                         case 2:
                             decided = query_yn( buffer );
                             break;
                     }
                 }
             }
             if( queryDelete || get_option<std::string>( "WORLD_END" ) == "delete" ) {
                 world_generator->delete_world( world_generator->active_world->world_name, true );
             } else if( queryReset || get_option<std::string>( "WORLD_END" ) == "reset" ) {
                 world_generator->delete_world( world_generator->active_world->world_name, false );
             }
         } else if( get_option<std::string>( "WORLD_END" ) != "keep" ) {
             std::string tmpmessage;
             for( auto &character : characters ) {
                 tmpmessage += "\n  ";
                 tmpmessage += character;
             }
             popup( _( "World retained.  Characters remaining:%s" ), tmpmessage );
         }
         if( g->gamemode ) {
             g->gamemode = std::make_unique<special_game>(); // null gamemode or something..
         }
     }
     //Reset any offset due to driving
     g->set_driving_view_offset( point_zero );
     //clear all sound channels
     sfx::fade_audio_channel( sfx::channel::any, 300 );
     sfx::fade_audio_group( sfx::group::weather, 300 );
     sfx::fade_audio_group( sfx::group::time_of_day, 300 );
     sfx::fade_audio_group( sfx::group::context_themes, 300 );
     sfx::fade_audio_group( sfx::group::sleepiness, 300 );
     zone_manager::get_manager().clear();
     MAPBUFFER.clear();
     overmap_buffer.clear();
 #if defined(__ANDROID__)
     quick_shortcuts_map.clear();
 #endif
     return true;
 }
References _, uilist::allow_cancel, memorial_logger::clear(), event_statistic_last_words, g, game_over, get_avatar(), get_event_bus(), get_memorial(), overmap_buffer, QUIT_DIED, QUIT_SUICIDE, overmapbuffer::remove_nemesis(), event_bus::send(), string, trait_HAS_NEMESIS, and u.