Cataclysm DDA: anonymous_namespace{filesystem.cpp} Namespace Reference
anonymous_namespace{filesystem.cpp} Namespace Reference
Functions
template<typename Function >
void for_each_dir_entry (const fs::path &path, Function &&function)
bool is_directory (const fs::directory_entry &entry, const std::string &full_path)
bool is_directory (const fs::directory_entry &entry)
bool name_contains (const fs::directory_entry &entry, const std::string &match, const bool at_end)
template<typename Predicate >
std::vector< std::string > find_file_if_bfs (const std::string &root_path, const bool recursive_search, Predicate predicate)
template<typename Predicate >
std::vector< cata_path > find_file_if_bfs (const cata_path &root_path, const bool recursive_search, Predicate predicate)
Function Documentation
find_file_if_bfs() [1/2]
template<typename Predicate > std::vector<cata_path> anonymous_namespace{filesystem.cpp}::find_file_if_bfs (const cata_path & root_path, const bool recursive_search, Predicate predicate)
Definition at line 359 of file filesystem.cpp.
 {
     cata_path norm_root_path = root_path.lexically_normal();
     std::deque<fs::path>  directories{ norm_root_path.get_unrelative_path() };
     std::vector<fs::path> results;
     while( !directories.empty() ) {
         const fs::path path = std::move( directories.front() );
         directories.pop_front();
         const std::ptrdiff_t n_dirs = static_cast<std::ptrdiff_t>( directories.size() );
         const std::ptrdiff_t n_results = static_cast<std::ptrdiff_t>( results.size() );
         // We could use fs::recursive_directory_iterator maybe
         for_each_dir_entry( path, [&]( const fs::directory_entry & entry ) {
             const fs::path &full_path = entry.path();
             // don't add files ending in '~'.
             fs::path filename = full_path.filename();
             if( !filename.empty() && filename.generic_u8string().back() == '~' ) {
                 return;
             }
             // add sub directories to recursive_search if requested
             const bool is_dir = is_directory( entry );
             if( recursive_search && is_dir ) {
                 directories.emplace_back( full_path );
             }
             // check the file
             if( !predicate( entry, is_dir ) ) {
                 return;
             }
             results.emplace_back( full_path );
         } );
         // Keep files and directories to recurse ordered consistently
         // by sorting from the old end to the new end.
         // NOLINTNEXTLINE(cata-use-localized-sorting)
         std::sort( std::begin( directories ) + n_dirs, std::end( directories ) );
         // NOLINTNEXTLINE(cata-use-localized-sorting)
         std::sort( std::begin( results ) + n_results, std::end( results ) );
     }
     std::vector<cata_path> cps;
     cps.reserve( results.size() );
     for( const fs::path &result_path : results ) {
         // Re-relativize paths against the root.
         cps.emplace_back( norm_root_path.get_logical_root(),
                           result_path.lexically_relative( norm_root_path.get_logical_root_path() ) );
     }
     return cps;
 }
References keycode::end, for_each_dir_entry(), cata_path::get_logical_root(), cata_path::get_logical_root_path(), cata_path::get_unrelative_path(), is_directory(), and cata_path::lexically_normal().
Referenced by get_directories_with(), and get_files_from_path().
find_file_if_bfs() [2/2]
template<typename Predicate > std::vector<std::string> anonymous_namespace{filesystem.cpp}::find_file_if_bfs (const std::string & root_path, const bool recursive_search, Predicate predicate)
Definition at line 310 of file filesystem.cpp.
 {
     std::deque<std::string>  directories {!root_path.empty() ? root_path : "."};
     std::vector<std::string> results;
     while( !directories.empty() ) {
         const fs::path path = fs::u8path( directories.front() );
         directories.pop_front();
         const std::ptrdiff_t n_dirs    = static_cast<std::ptrdiff_t>( directories.size() );
         const std::ptrdiff_t n_results = static_cast<std::ptrdiff_t>( results.size() );
         // We could use fs::recursive_directory_iterator maybe
         for_each_dir_entry( path, [&]( const fs::directory_entry & entry ) {
             const std::string full_path = entry.path().generic_u8string();
             // don't add files ending in '~'.
             if( full_path.back() == '~' ) {
                 return;
             }
             // add sub directories to recursive_search if requested
             const bool is_dir = is_directory( entry, full_path );
             if( recursive_search && is_dir ) {
                 directories.emplace_back( full_path );
             }
             // check the file
             if( !predicate( entry, is_dir ) ) {
                 return;
             }
             results.emplace_back( full_path );
         } );
         // Keep files and directories to recurse ordered consistently
         // by sorting from the old end to the new end.
         // NOLINTNEXTLINE(cata-use-localized-sorting)
         std::sort( std::begin( directories ) + n_dirs,    std::end( directories ) );
         // NOLINTNEXTLINE(cata-use-localized-sorting)
         std::sort( std::begin( results )     + n_results, std::end( results ) );
     }
     return results;
 }
References keycode::end, for_each_dir_entry(), and is_directory().
for_each_dir_entry()
template<typename Function > void anonymous_namespace{filesystem.cpp}::for_each_dir_entry (const fs::path & path, Function && function)
Definition at line 227 of file filesystem.cpp.
 {
     if( path.empty() ) {
         return;
     }
     std::error_code ec;
     auto dir_iter = fs::directory_iterator( path, ec );
     if( ec ) {
         std::string e_str = ec.message();
         DebugLog( D_WARNING, D_MAIN ) << "opendir [" << path.generic_u8string() << "] failed with \"" <<
                                       e_str << "\".";
         return;
     }
     for( const fs::directory_entry &dir_entry : dir_iter ) {
         function( dir_entry );
     }
 }
References D_MAIN, D_WARNING, and DebugLog().
Referenced by find_file_if_bfs().
is_directory() [1/2]
bool anonymous_namespace{filesystem.cpp}::is_directory (const fs::directory_entry & entry)
Definition at line 264 of file filesystem.cpp.
 {
     // We do an extra dance here because directory_entry might not have a cached valid stat result.
     std::error_code ec;
     bool result = entry.is_directory( ec );
     if( ec ) {
         std::string e_str = ec.message();
         DebugLog( D_WARNING, D_MAIN ) << "stat [" << entry.path().generic_u8string() << "] failed with \""
                                       << e_str << "\".";
         return false;
     }
     return result;
 }
References D_MAIN, D_WARNING, and DebugLog().
Referenced by assure_dir_exist(), dir_exist(), file_exist(), and find_file_if_bfs().
is_directory() [2/2]
bool anonymous_namespace{filesystem.cpp}::is_directory (const fs::directory_entry & entry, const std::string & full_path)
Definition at line 249 of file filesystem.cpp.
 {
     // We do an extra dance here because directory_entry might not have a cached valid stat result.
     std::error_code ec;
     bool result = entry.is_directory( ec );
     if( ec ) {
         std::string e_str = ec.message();
         DebugLog( D_WARNING, D_MAIN ) << "stat [" << full_path << "] failed with \"" << e_str << "\".";
         return false;
     }
     return result;
 }
References D_MAIN, D_WARNING, and DebugLog().
Referenced by tgz_archiver::_gen_tar_header(), and ofstream_wrapper::open().
name_contains()
bool anonymous_namespace{filesystem.cpp}::name_contains (const fs::directory_entry & entry, const std::string & match, const bool at_end)
Definition at line 284 of file filesystem.cpp.
 {
     std::string entry_name = entry.path().filename().u8string();
     const size_t len_fname = entry_name.length();
     const size_t len_match = match.length();
     if( len_match > len_fname ) {
         return false;
     }
     const size_t offset = at_end ? ( len_fname - len_match ) : 0;
     return strstr( entry_name.c_str() + offset, match.c_str() ) != nullptr;
 }
Referenced by get_directories_with(), and get_files_from_path().