Cataclysm DDA: ui_manager Namespace Reference
ui_manager Namespace Reference
Functions
void invalidate (const rectangle< point > &rect, bool reenable_uis_below)
Invalidate a portion of the screen when a UI is resized, closed, etc.
void redraw ()
Invalidate the top window and redraw all invalidated windows.
void redraw_invalidated ()
Redraw all invalidated windows without invalidating the top window.
void screen_resized ()
Handle resize of the game window.
void invalidate_all_ui_adaptors ()
Function Documentation
invalidate()
void ui_manager::invalidate (const rectangle< point > & rect, bool reenable_uis_below)
Invalidate a portion of the screen when a UI is resized, closed, etc.
Not supposed to be directly called by the user. rect is the pixel dimensions in tiles or console cell dimensions in curses
Definition at line 499 of file ui_manager.cpp.
 {
     ui_adaptor::invalidate( rect, reenable_uis_below );
 }
References ui_adaptor::invalidate().
Referenced by vehicle::do_towing_move(), ui_adaptor::position(), ui_adaptor::position_absolute(), ui_adaptor::position_from_window(), and ui_adaptor::~ui_adaptor().
invalidate_all_ui_adaptors()
void ui_manager::invalidate_all_ui_adaptors ()
Definition at line 518 of file ui_manager.cpp.
 {
     for( ui_adaptor &adaptor : ui_stack ) {
         adaptor.invalidate_ui();
     }
 }
References ui_stack.
Referenced by input_context::handle_input().
redraw()
void ui_manager::redraw ()
Invalidate the top window and redraw all invalidated windows.
Note that ui_manager may redraw multiple times when a ui_adaptor callback calls debugmsg, the game window is resized, or the system requests a redraw, so any data that may change after a resize or on each redraw should be calculated within the respective callbacks.
Definition at line 504 of file ui_manager.cpp.
 {
     ui_adaptor::redraw();
 }
References ui_adaptor::redraw().
Referenced by veh_app_interact::app_loop(), game::cancel_activity_or_ignore_query(), debug_menu::change_spells(), choose_direction(), choose_direction_rel_ms(), game_menus::inv::compare_items(), Character::conduct_blood_analysis(), smart_controller_ui::control(), debug_menu::debug(), debug_error_prompt(), avatar::disp_medical(), game::disp_NPCs(), advanced_inventory::display(), bodygraph_display::display(), faction_manager::display(), overmap_ui::display(), player_morale::display(), talk_function::display_and_choose_opts(), help::display_help(), input_context::display_menu(), game::display_om_pathfinding_progress(), game::display_scent(), veh_interact::do_change_shape(), veh_interact::do_install(), veh_interact::do_main_loop(), veh_interact::do_remove(), veh_interact::do_repair(), draw_item_info(), editmap::edit(), past_games_info::ensure_loaded(), inventory_pick_selector::execute(), ammo_inventory_selector::execute(), inventory_compare_selector::execute(), inventory_drop_selector::execute(), pickup_selector::execute(), unload_selector::execute(), inventory_examiner::execute(), inventory_multiselector::execute(), game::extended_description(), handle_key_blocking_activity(), game::handle_mouseview(), anonymous_namespace{animation.cpp}::hit_animation(), uilist::inputfilter(), exosuit_interact::interact_loop(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_monsters(), game::look_around(), editmap::mapgen_retarget(), main_menu::opening_screen(), dialogue::opt(), veh_interact::overview(), worldfactory::pick_world(), overmap_ui::place_ter_or_special(), game::portal_storm_query(), avatar::power_bionics(), avatar::power_mutations(), uilist::query(), computer_session::query_any(), query_popup::query_once(), string_editor_window::query_string(), string_input_popup::query_string(), inventory_selector::query_string(), computer_session::query_ynq(), game::quicksave(), robot_finds_kitten::robot_finds_kitten(), demo_ui::run(), Messages::dialog::run(), target_ui::run(), prof_window::run(), mapbuffer::save(), scrollable_text(), overmap_ui::search(), editmap::select_shape(), set_description(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), game::setup(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), loading_ui::show(), options_manager::show(), safemode::show(), worldfactory::show_active_world_mods(), panel_manager::show_adm(), color_manager::show_gui(), show_scores_ui(), debug_menu::show_sound(), worldfactory::show_worldgen_advanced(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), outfit::sort_armor(), game::start_game(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), computer_session::use(), iexamine::vending(), basecamp::worker_assignment_ui(), and game::zones_manager().
redraw_invalidated()
void ui_manager::redraw_invalidated ()
Redraw all invalidated windows without invalidating the top window.
Definition at line 509 of file ui_manager.cpp.
 {
     ui_adaptor::redraw_invalidated();
 }
References ui_adaptor::redraw_invalidated().
Referenced by Character::disp_info(), advanced_inventory::display(), melee_actor::do_grab(), anonymous_namespace{animation.cpp}::basic_animation::draw(), debug_menu::draw_benchmark(), mission_ui::draw_mission_ui(), trade_selector::execute(), anonymous_namespace{main.cpp}::exit_handler(), game::fling_creature(), game::get_player_input(), input_context::handle_input(), map::move_vehicle(), and diary::show_diary_ui().
screen_resized()
void ui_manager::screen_resized ()
Handle resize of the game window.
Not supposed to be directly called by the user.
Definition at line 514 of file ui_manager.cpp.
 {
     ui_adaptor::screen_resized();
 }
References ui_adaptor::screen_resized().
Referenced by catacurses::resizeterm().