Cataclysm DDA: vehicles::parts Namespace Reference
vehicles::parts Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void check ()
void reset ()
void finalize ()
const std::vector< vpart_info > & get_all ()
Function Documentation
check()
void vehicles::parts::check ()
Definition at line 776 of file veh_type.cpp.
 {
     for( const vpart_info &vpi : vehicles::parts::get_all() ) {
         vpi.check();
     }
 }
References get_all().
Referenced by DynamicDataLoader::check_consistency().
finalize()
void vehicles::parts::finalize ()
Definition at line 549 of file veh_type.cpp.
 {
     vpart_info_factory.finalize();
     for( const itype *const item : item_controller->find( mountable_gun_filter ) ) {
         vpart_info new_part = *vpart_turret_generic; // copy from generic
         const itype_id item_id = item->get_id();
         new_part.id = vpart_id( "turret_" + item_id.str() );
         new_part.base_item = item_id;
         new_part.description = item->description;
         new_part.color = item->color;
         // calculate requirements for install/removal by gross estimate
         int primary_req = 3; // 3 in whatever gun's skill is set to
         int mechanics_req = 3 + static_cast<int>( item->weight / 10_kilogram );
         int electronics_req = 0; // calculated below
         // if turret base item is migrated-from or blacklisted hide it from install menu
         if( item_id != item_controller->migrate_id( item_id ) ||
             item_is_blacklisted( item->get_id() ) ) {
             new_part.set_flag( "NO_INSTALL_HIDDEN" );
         }
         if( gun_uses_liquid_ammo( *item ) ) {
             new_part.set_flag( "USE_TANKS" );
             // +1 mechanics level for liquid plumbing
             mechanics_req++;
         }
         const int battery_mags_drain = gun_battery_mags_drain( *item );
         if( battery_mags_drain ) {
             // USE_BATTERIES for afs cartridge-like batteries
             new_part.set_flag( "USE_BATTERIES" );
             // +1 electronics level per 15 battery charges used for electric plumbing
             electronics_req += static_cast<int>( std::ceil( battery_mags_drain / 15.0 ) );
         }
         // make part foldable for pistols and SMGs
         bool is_foldable = item->qualities.count( qual_PISTOL ) > 0 ||
                            item->qualities.count( qual_SMG ) > 0;
         if( is_foldable ) {
             new_part.folded_volume = item->volume;
         }
         // cap all skills at 8
         primary_req = std::min( 8, primary_req );
         mechanics_req = std::min( 8, mechanics_req );
         electronics_req = std::min( 8, electronics_req );
         new_part.install_skills.emplace( item->gun->skill_used, primary_req );
         new_part.removal_skills.emplace( item->gun->skill_used, primary_req / 2 );
         new_part.install_skills.emplace( "mechanics", mechanics_req );
         new_part.removal_skills.emplace( "mechanics", mechanics_req / 2 );
         if( electronics_req > 0 ) {
             new_part.install_skills.emplace( "electronics", electronics_req );
             new_part.removal_skills.emplace( "electronics", electronics_req / 2 );
         }
         int difficulty = primary_req + mechanics_req + electronics_req * 2;
         time_duration install_time = 10_minutes * difficulty;
         time_duration removal_time = 10_minutes * difficulty / 2;
         new_part.install_moves = install_time;
         new_part.removal_moves = removal_time;
         new_part.looks_like = get_looks_like( new_part, *item );
         vpart_info_factory.insert( new_part );
     }
     // hide the generic turret prototype
     vpart_info &vpi_turret_generic = const_cast<vpart_info &>( *vpart_turret_generic );
     vpi_turret_generic.set_flag( "NO_INSTALL_HIDDEN" );
     for( const vpart_info &const_vpi : vehicles::parts::get_all() ) {
         // const_cast hack until/if generic factory supports finalize
         vpart_info &vpi = const_cast<vpart_info &>( const_vpi );
         vpi.finalize();
     }
 }
References vpart_info::base_item, ceil(), item::color(), vpart_info::color, item::count(), vpart_info::description, vpart_info::finalize(), vpart_info::folded_volume, get_all(), get_looks_like(), gun_battery_mags_drain(), gun_uses_liquid_ammo(), vpart_info::id, vpart_info::install_moves, vpart_info::install_skills, item_controller, item_is_blacklisted(), vpart_info::looks_like, min(), mountable_gun_filter(), qual_PISTOL, qual_SMG, vpart_info::removal_moves, vpart_info::removal_skills, vpart_info::set_flag(), string_id< T >::str(), item::volume(), anonymous_namespace{veh_type.cpp}::vpart_info_factory, vpart_turret_generic, and item::weight().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< vpart_info > & vehicles::parts::get_all ()
Definition at line 960 of file veh_type.cpp.
 {
     return vpart_info_factory.get_all();
 }
References anonymous_namespace{veh_type.cpp}::vpart_info_factory.
Referenced by vehicle::can_mount(), check(), item::final_info(), finalize(), finalize_constructions(), item::link_to(), veh_interact::move_cursor(), vpart_appliance_from_item(), and vpart_from_item().
load()
void vehicles::parts::load (const JsonObject & jo, const std::string & src)
Definition at line 236 of file veh_type.cpp.
 {
     vpart_info_factory.load( jo, src );
 }
References anonymous_namespace{veh_type.cpp}::vpart_info_factory.
Referenced by DynamicDataLoader::initialize().
reset()
void vehicles::parts::reset ()
Definition at line 955 of file veh_type.cpp.
 {
     vpart_info_factory.reset();
 }
References anonymous_namespace{veh_type.cpp}::vpart_info_factory.
Referenced by DynamicDataLoader::unload_data().