Cataclysm DDA: ui::omap Namespace Reference
ui::omap Namespace Reference
Functions
void display ()
Display overmap centered at the player's position.
void display_hordes ()
Display overmap like with display() and display hordes.
void display_weather ()
Display overmap like with display() and display the weather.
void display_visible_weather ()
Display overmap like with display() and display the weather that is within line of sight.
void display_scents ()
Display overmap like with display() and display scent traces.
void display_zones (const tripoint_abs_omt &center, const tripoint_abs_omt &select, int iZoneIndex)
Display overmap like with display() and display the given zone.
void display_editor ()
Display overmap like with display() and enable the overmap editor.
tripoint_abs_omt choose_point (bool show_debug_info=false)
Interactive point choosing; used as the map screen.
tripoint_abs_omt choose_point (int z, bool show_debug_info=false)
Same as above but start at z-level z instead of players current z-level, x and y are taken from the players position.
tripoint_abs_omt choose_point (const tripoint_abs_omt &origin, bool show_debug_info=false)
Interactive point choosing; used as the map screen.
void setup_cities_menu (uilist &cities_menu, std::vector< city > &cities_container)
std::optional< city > select_city (uilist &cities_menu, std::vector< city > &cities_container, bool random=false)
Function Documentation
choose_point() [1/3]
tripoint_abs_omt ui::omap::choose_point (bool show_debug_info = false)
Interactive point choosing; used as the map screen.
The map is initially center at the players position.
Returns
The absolute coordinates of the chosen point or invalid_point if canceled with Escape (or similar key).
Definition at line 2103 of file overmap_ui.cpp.
 {
     overmap_ui::draw_data_t data;
     data.debug_info = show_debug_info;
     return overmap_ui::display( get_player_character().global_omt_location(), data );
 }
References overmap_ui::draw_data_t::debug_info, overmap_ui::display(), and get_player_character().
Referenced by computer_session::action_miss_launch(), debug_menu::map_extra(), om_target_tile(), basecamp::survey_field_return(), basecamp::survey_return(), and debug_menu::teleport_long().
choose_point() [2/3]
tripoint_abs_omt ui::omap::choose_point (const tripoint_abs_omt & origin, bool show_debug_info = false)
Interactive point choosing; used as the map screen.
The map is initially centered on the origin.
Returns
The absolute coordinates of the chosen point or invalid_point if canceled with Escape (or similar key).
Definition at line 2110 of file overmap_ui.cpp.
 {
     overmap_ui::draw_data_t data;
     data.debug_info = show_debug_info;
     return overmap_ui::display( origin, data );
 }
References overmap_ui::draw_data_t::debug_info, and overmap_ui::display().
choose_point() [3/3]
tripoint_abs_omt ui::omap::choose_point (int z, bool show_debug_info = false)
Same as above but start at z-level z instead of players current z-level, x and y are taken from the players position.
Definition at line 2117 of file overmap_ui.cpp.
 {
     overmap_ui::draw_data_t data;
     data.debug_info = show_debug_info;
     tripoint_abs_omt loc = get_player_character().global_omt_location();
     loc.z() = z;
     return overmap_ui::display( loc, data );
 }
References overmap_ui::draw_data_t::debug_info, overmap_ui::display(), get_player_character(), Creature::global_omt_location(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
display()
void ui::omap::display ()
Display overmap centered at the player's position.
Definition at line 2047 of file overmap_ui.cpp.
 {
     overmap_ui::display( get_player_character().global_omt_location(), overmap_ui::draw_data_t() );
 }
References overmap_ui::display(), and get_player_character().
Referenced by game::do_regular_action().
display_editor()
void ui::omap::display_editor ()
Display overmap like with display() and enable the overmap editor.
Definition at line 2087 of file overmap_ui.cpp.
 {
     overmap_ui::draw_data_t data;
     data.debug_editor = true;
     overmap_ui::display( get_player_character().global_omt_location(), data );
 }
References overmap_ui::draw_data_t::debug_editor, overmap_ui::display(), and get_player_character().
Referenced by debug_menu::debug().
display_hordes()
void ui::omap::display_hordes ()
Display overmap like with display() and display hordes.
Definition at line 2052 of file overmap_ui.cpp.
 {
     overmap_ui::draw_data_t data;
     uistate.overmap_debug_mongroup = true;
     overmap_ui::display( get_player_character().global_omt_location(), data );
     uistate.overmap_debug_mongroup = false;
 }
References overmap_ui::display(), get_player_character(), uistatedata::overmap_debug_mongroup, and uistate.
Referenced by debug_menu::debug().
display_scents()
void ui::omap::display_scents ()
Display overmap like with display() and display scent traces.
Definition at line 2080 of file overmap_ui.cpp.
 {
     overmap_ui::draw_data_t data;
     data.debug_scent = true;
     overmap_ui::display( get_player_character().global_omt_location(), data );
 }
References overmap_ui::draw_data_t::debug_scent, overmap_ui::display(), and get_player_character().
Referenced by debug_menu::debug().
display_visible_weather()
void ui::omap::display_visible_weather ()
Display overmap like with display() and display the weather that is within line of sight.
Definition at line 2070 of file overmap_ui.cpp.
 {
     overmap_ui::draw_data_t data;
     uistate.overmap_visible_weather = true;
     tripoint_abs_omt pos = get_player_character().global_omt_location();
     pos.z() = 10;
     overmap_ui::display( pos, data );
     uistate.overmap_visible_weather = false;
 }
References overmap_ui::display(), get_player_character(), Creature::global_omt_location(), uistatedata::overmap_visible_weather, math_opers::pos(), and uistate.
Referenced by game::do_regular_action().
display_weather()
void ui::omap::display_weather ()
Display overmap like with display() and display the weather.
Definition at line 2060 of file overmap_ui.cpp.
 {
     overmap_ui::draw_data_t data;
     uistate.overmap_debug_weather = true;
     tripoint_abs_omt pos = get_player_character().global_omt_location();
     pos.z() = 10;
     overmap_ui::display( pos, data );
     uistate.overmap_debug_weather = false;
 }
References overmap_ui::display(), get_player_character(), Creature::global_omt_location(), uistatedata::overmap_debug_weather, math_opers::pos(), and uistate.
Referenced by debug_menu::debug().
display_zones()
void ui::omap::display_zones (const tripoint_abs_omt & center, const tripoint_abs_omt & select, int iZoneIndex)
Display overmap like with display() and display the given zone.
Definition at line 2094 of file overmap_ui.cpp.
 {
     overmap_ui::draw_data_t data;
     data.select = select;
     data.iZoneIndex = iZoneIndex;
     overmap_ui::display( center, data );
 }
References center, overmap_ui::display(), overmap_ui::draw_data_t::iZoneIndex, and overmap_ui::draw_data_t::select.
Referenced by game::zones_manager().
select_city()
std::optional< city > ui::omap::select_city (uilist & cities_menu, std::vector< city > & cities_container, bool random = false)
Definition at line 2151 of file overmap_ui.cpp.
 {
     std::optional<city> ret_val = std::nullopt;
     if( random ) {
         ret_val = random_entry( cities_container );
     } else {
         cities_menu.query();
         if( cities_menu.ret == RANDOM_CITY_ENTRY ) {
             ret_val = random_entry( cities_container );
         } else if( cities_menu.ret == UILIST_CANCEL ) {
             ret_val = std::nullopt;
         } else {
             if( cities_menu.entries.size() > 1 ) {
                 ret_val = cities_container[cities_menu.selected - 1];
             }
         }
     }
     return ret_val;
 }
References uilist::entries, uilist::query(), om_direction::random(), RANDOM_CITY_ENTRY, random_entry(), uilist::ret, uilist::selected, and UILIST_CANCEL.
Referenced by set_description(), and debug_menu::teleport_city().
setup_cities_menu()
void ui::omap::setup_cities_menu (uilist & cities_menu, std::vector< city > & cities_container)
Definition at line 2126 of file overmap_ui.cpp.
 {
     if( get_option<bool>( "SELECT_STARTING_CITY" ) ) {
         uilist_entry entry_random_city( RANDOM_CITY_ENTRY, true, '*',
                                         _( "<color_red>* Random city *</color>" ),
                                         _( "Location: <color_white>(?,?)</color>:<color_white>(?,?)</color>" ),
                                         //~ "pop" refers to population count
                                         _( "(pop <color_white>?</color>)" )
                                       );
         cities_menu.entries.emplace_back( entry_random_city );
         cities_menu.desc_enabled = true;
         cities_menu.title = _( "Select a starting city" );
         for( const city &c : cities_container ) {
             uilist_entry entry( c.database_id, true, -1, string_format( _( "%s (size: %d)" ), c.name, c.size ),
                                 string_format(
                                     _( "Location: <color_white>%s</color>:<color_white>%s</color>" ),
                                     c.pos_om.to_string(), c.pos.to_string() ),
                                 //~ "pop" refers to population count
                                 string_format( _( "(pop <color_white>%s</color>)" ), c.population ) );
             cities_menu.entries.emplace_back( entry );
         }
         cities_menu.w_height_setup = TERMY - 4;
     }
 }
References _, c, uilist::desc_enabled, uilist::entries, RANDOM_CITY_ENTRY, string_format(), TERMY, uilist::title, and uilist::w_height_setup.
Referenced by set_description(), and debug_menu::teleport_city().