Cataclysm DDA: gates Namespace Reference
gates Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void check ()
void reset ()
void open_gate (const tripoint_bub_ms &pos, Character &p)
opens the gate via player's activity
void open_gate (const tripoint_bub_ms &pos)
opens the gate immediately
Function Documentation
check()
void gates::check ()
Definition at line 146 of file gates.cpp.
 {
     gates_data.check();
 }
References anonymous_namespace{gates.cpp}::gates_data.
Referenced by DynamicDataLoader::check_consistency().
load()
void gates::load (const JsonObject & jo, const std::string & src)
Definition at line 141 of file gates.cpp.
 {
     gates_data.load( jo, src );
 }
References anonymous_namespace{gates.cpp}::gates_data.
Referenced by DynamicDataLoader::initialize().
open_gate() [1/2]
void gates::open_gate (const tripoint_bub_ms & pos)
opens the gate immediately
Definition at line 168 of file gates.cpp.
 {
     const gate_id gid = get_gate_id( pos );
     if( !gates_data.is_valid( gid ) ) {
         return;
     }
     const gate_data &gate = gates_data.obj( gid );
     bool open = false;
     bool close = false;
     bool fail = false;
     map &here = get_map();
     for( const point &wall_offset : four_adjacent_offsets ) {
         const tripoint_bub_ms wall_pos = pos + wall_offset;
         if( !gate.is_suitable_wall( wall_pos ) ) {
             continue;
         }
         for( const point &gate_offset : four_adjacent_offsets ) {
             const tripoint_bub_ms gate_pos = wall_pos + gate_offset;
             if( gate_pos == pos ) {
                 continue; // Never comes back
             }
             if( !open ) { // Closing the gate...
                 tripoint_bub_ms cur_pos = gate_pos;
                 while( here.ter( cur_pos ) == gate.floor.id() ) {
                     fail = !g->forced_door_closing( cur_pos, gate.door.id(), gate.bash_dmg ) || fail;
                     close = !fail;
                     cur_pos += gate_offset;
                 }
             }
             if( !close ) { // Opening the gate...
                 tripoint_bub_ms cur_pos = gate_pos;
                 while( true ) {
                     const ter_id ter = here.ter( cur_pos );
                     if( ter == gate.door.id() ) {
                         here.ter_set( cur_pos, gate.floor.id() );
                         open = !fail;
                     } else if( ter != gate.floor.id() ) {
                         break;
                     }
                     cur_pos += gate_offset;
                 }
             }
         }
     }
     if( get_player_view().sees( pos ) ) {
         if( open ) {
             add_msg( gate.open_message );
         } else if( close ) {
             add_msg( gate.close_message );
         } else if( fail ) {
             add_msg( gate.fail_message );
         } else {
             add_msg( _( "Nothing happens." ) );
         }
     }
 }
References _, add_msg(), close(), four_adjacent_offsets, g, anonymous_namespace{gates.cpp}::gates_data, anonymous_namespace{gates.cpp}::get_gate_id(), get_map(), get_player_view(), int_id< T >::id(), open(), math_opers::pos(), map::ter(), and map::ter_set().
open_gate() [2/2]
void gates::open_gate (const tripoint_bub_ms & pos, Character & p)
opens the gate via player's activity
Definition at line 236 of file gates.cpp.
 {
     const gate_id gid = get_gate_id( pos );
     if( !gates_data.is_valid( gid ) ) {
         p.add_msg_if_player( _( "Nothing happens." ) );
         return;
     }
     const gate_data &gate = gates_data.obj( gid );
     p.add_msg_if_player( gate.pull_message );
     p.assign_activity( open_gate_activity_actor( gate.moves, pos ) );
 }
References _, Character::add_msg_if_player(), Character::assign_activity(), anonymous_namespace{gates.cpp}::gates_data, anonymous_namespace{gates.cpp}::get_gate_id(), and math_opers::pos().
Referenced by open_gate_activity_actor::finish(), and game::open_gate().
reset()
void gates::reset ()
Definition at line 151 of file gates.cpp.
 {
     gates_data.reset();
 }
References anonymous_namespace{gates.cpp}::gates_data.
Referenced by DynamicDataLoader::unload_data().