Cataclysm DDA: map_field_processing Namespace Reference
map_field_processing Namespace Reference
Typedefs
using FieldProcessorPtr = void(*)(const tripoint &p, field_entry &cur, field_proc_data &pd)
Pointer to the "field processor" - a function that will be called each alive field entry of a matching field type during field processing.
Functions
std::vector< FieldProcessorPtr > processors_for_type (const field_type &ft)
Returns list of "field processors" for a given field type.
Typedef Documentation
FieldProcessorPtr
using map_field_processing::FieldProcessorPtr = typedef void(*)(const tripoint &p, field_entry &cur, field_proc_data &pd)
Pointer to the "field processor" - a function that will be called each alive field entry of a matching field type during field processing.
Definition at line 17 of file map_field.h.
Function Documentation
processors_for_type()
std::vector< FieldProcessorPtr > map_field_processing::processors_for_type (const field_type & ft)
Returns list of "field processors" for a given field type.
Definition at line 2182 of file map_field.cpp.
 {
     std::vector<FieldProcessorPtr> processors;
     const bool intensity_upgrade_chance = std::any_of( ft.intensity_levels.begin(),
                                           ft.intensity_levels.end(),
     []( const field_intensity_level & elem ) {
         return elem.intensity_upgrade_chance > 0;
     } );
     const bool extra_radiation = std::any_of( ft.intensity_levels.begin(), ft.intensity_levels.end(),
     []( const field_intensity_level & elem ) {
         return elem.extra_radiation_max > 0;
     } );
     const bool has_monster_spawn_chance = std::any_of( ft.intensity_levels.begin(),
                                           ft.intensity_levels.end(),
     []( const field_intensity_level & elem ) {
         return elem.monster_spawn_chance > 0 && elem.monster_spawn_count > 0;
     } );
     if( intensity_upgrade_chance ) {
         processors.push_back( &field_processor_upgrade_intensity );
     }
     if( ft.underwater_age_speedup != 0_turns ) {
         processors.push_back( &field_processor_underwater_dissipation );
     }
     if( ft.apply_slime_factor > 0 ) {
         processors.push_back( &field_processor_apply_slime );
     }
     if( ft.gas_can_spread() ) {
         processors.push_back( &field_processor_spread_gas );
     }
     // Apply radiation
     if( extra_radiation ) {
         processors.push_back( &field_processor_extra_radiation );
     }
     // Apply wandering fields from vents
     if( ft.wandering_field ) {
         processors.push_back( &field_processor_wandering_field );
     }
     if( has_monster_spawn_chance ) {
         processors.push_back( &field_processor_monster_spawn );
     }
     // legacy
     if( ft.legacy_make_rubble ) {
         processors.push_back( &field_processor_make_rubble );
     }
     // Per-type processors:
     if( ft.id == fd_acid ) {
         processors.push_back( &field_processor_fd_acid );
     }
     if( ft.id == fd_extinguisher ) {
         processors.push_back( &field_processor_fd_extinguisher );
     }
     if( ft.id == fd_fire ) {
         processors.push_back( &field_processor_fd_fire );
     }
     if( ft.id == fd_fungal_haze ) {
         processors.push_back( &field_processor_fd_fungal_haze );
     }
     if( ft.id == fd_fire_vent ) {
         processors.push_back( &field_processor_fd_fire_vent );
     }
     if( ft.id == fd_flame_burst ) {
         processors.push_back( &field_processor_fd_flame_burst );
     }
     if( ft.id == fd_electricity || ft.id == fd_electricity_unlit ) {
         processors.push_back( &field_processor_fd_electricity );
     }
     if( ft.id == fd_push_items ) {
         processors.push_back( &field_processor_fd_push_items );
     }
     if( ft.id == fd_shock_vent ) {
         processors.push_back( &field_processor_fd_shock_vent );
     }
     if( ft.id == fd_acid_vent ) {
         processors.push_back( &field_processor_fd_acid_vent );
     }
     if( ft.id == fd_incendiary ) {
         processors.push_back( &field_processor_fd_incendiary );
     }
     if( ft.id == fd_fungicidal_gas ) {
         processors.push_back( &field_processor_fd_fungicidal_gas );
     }
     if( ft.id == fd_last_known ) {
         processors.push_back( &field_processor_fd_last_known );
     }
     return processors;
 }
References field_type::apply_slime_factor, fd_acid, fd_acid_vent, fd_electricity, fd_electricity_unlit, fd_extinguisher, fd_fire, fd_fire_vent, fd_flame_burst, fd_fungal_haze, fd_fungicidal_gas, fd_incendiary, fd_last_known, fd_push_items, fd_shock_vent, field_processor_apply_slime(), field_processor_extra_radiation(), field_processor_fd_acid(), field_processor_fd_acid_vent(), field_processor_fd_electricity(), field_processor_fd_extinguisher(), field_processor_fd_fire(), field_processor_fd_fire_vent(), field_processor_fd_flame_burst(), field_processor_fd_fungal_haze(), field_processor_fd_fungicidal_gas(), field_processor_fd_incendiary(), field_processor_fd_last_known(), field_processor_fd_push_items(), field_processor_fd_shock_vent(), field_processor_make_rubble(), field_processor_monster_spawn(), field_processor_spread_gas(), field_processor_underwater_dissipation(), field_processor_upgrade_intensity(), field_processor_wandering_field(), field_type::gas_can_spread(), field_type::id, field_type::intensity_levels, field_type::legacy_make_rubble, field_type::underwater_age_speedup, and field_type::wandering_field.
Referenced by field_type::finalize().