Cataclysm DDA: recipe_group Namespace Reference
recipe_group Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void check ()
void reset ()
std::map< recipe_id, translation > get_recipes_by_bldg (const std::string &bldg)
std::map< recipe_id, translation > get_recipes_by_id (const std::string &id)
std::map< recipe_id, translation > get_recipes_by_id (const std::string &id, const oter_id &omt_ter, const std::optional< mapgen_arguments > *maybe_args)
std::string get_building_of_recipe (const std::string &recipe)
Function Documentation
check()
void recipe_group::check ()
Definition at line 186 of file recipe_groups.cpp.
 {
     recipe_groups_data.check();
 }
References anonymous_namespace{recipe_groups.cpp}::recipe_groups_data.
Referenced by DynamicDataLoader::finalize_loaded_data().
get_building_of_recipe()
std::string recipe_group::get_building_of_recipe (const std::string & recipe)
Definition at line 168 of file recipe_groups.cpp.
 {
     for( const auto &group : recipe_groups_data.get_all() ) {
         for( const auto &rec : group.recipes ) {
             if( rec.first.str() == recipe ) {
                 return group.building_type;
             }
         }
     }
     return "";
 }
References anonymous_namespace{recipe_groups.cpp}::recipe_groups_data.
Referenced by basecamp::companion_crafting_choose_return(), companion_per_recipe_building_type(), and basecamp::handle_mission().
get_recipes_by_bldg()
std::map< recipe_id, translation > recipe_group::get_recipes_by_bldg (const std::string & bldg)
Definition at line 85 of file recipe_groups.cpp.
 {
     std::map<recipe_id, translation> all_rec;
     if( bldg == "ALL" ) {
         for( const auto &gr : recipe_groups_data.get_all() ) {
             all_rec.insert( gr.recipes.cbegin(), gr.recipes.cend() );
         }
         return all_rec;
     } else {
         for( const auto &gr : recipe_groups_data.get_all() ) {
             if( gr.building_type != bldg ) {
                 continue;
             }
             all_rec.insert( gr.recipes.cbegin(), gr.recipes.cend() );
         }
         return all_rec;
     }
 }
References anonymous_namespace{recipe_groups.cpp}::recipe_groups_data.
Referenced by basecamp::recipe_deck().
get_recipes_by_id() [1/2]
std::map< recipe_id, translation > recipe_group::get_recipes_by_id (const std::string & id)
Definition at line 104 of file recipe_groups.cpp.
 {
     std::map<recipe_id, translation> all_rec;
     if( !recipe_groups_data.is_valid( group_id( id ) ) ) {
         return all_rec;
     }
     const recipe_group_data &group = recipe_groups_data.obj( group_id( id ) );
     return group.recipes;
 }
References anonymous_namespace{recipe_groups.cpp}::recipe_groups_data.
Referenced by dynamic_line_t::dynamic_line_t(), basecamp::expansion_tab(), conditional_fun::anonymous_namespace{condition.cpp}::f_at_om_location(), conditional_fun::anonymous_namespace{condition.cpp}::f_near_om_location(), basecamp::get_available_missions(), basecamp::recipe_deck(), talk_function::start_camp(), and basecamp::survey_return().
get_recipes_by_id() [2/2]
std::map< recipe_id, translation > recipe_group::get_recipes_by_id (const std::string & id, const oter_id & omt_ter, const std::optional< mapgen_arguments > * maybe_args)
Definition at line 114 of file recipe_groups.cpp.
 {
     std::map<recipe_id, translation> all_rec;
     if( !recipe_groups_data.is_valid( group_id( id ) ) ) {
         return all_rec;
     }
     const recipe_group_data &group = recipe_groups_data.obj( group_id( id ) );
     for( const auto &recp : group.recipes ) {
         const auto &recp_terrain_it = group.om_terrains.find( recp.first );
         if( recp_terrain_it == group.om_terrains.end() ) {
             debugmsg( "Recipe %s doesn't specify 'om_terrains', use ANY instead if intended to work anywhere",
                       recp.second );
             continue;
         }
         for( const omt_types_parameters &om_terrain : recp_terrain_it->second ) {
             if( om_terrain.omt == "ANY" ) {
                 all_rec.emplace( recp );
                 break;
             }
             if( !is_ot_match( om_terrain.omt, omt_ter, om_terrain.omt_type ) ) {
                 continue;
             }
             if( om_terrain.parameters.empty() ) {
                 all_rec.emplace( recp );
                 break;
             }
             if( !!maybe_args ) {
                 bool parameters_matched = true;
                 for( const auto &key_value_set_pair : om_terrain.parameters ) {
                     auto map_key_it = maybe_args->value().map.find( key_value_set_pair.first );
                     if( map_key_it == maybe_args->value().map.end() ) {
                         debugmsg( "Parameter key %s in recipe %s not found for omt %s", key_value_set_pair.first, id,
                                   omt_ter.id().str() );
                         continue;
                     }
                     if( key_value_set_pair.second.find( map_key_it->second.get_string() ) ==
                         key_value_set_pair.second.end() ) {
                         parameters_matched = false;
                         break;
                     }
                 }
                 if( parameters_matched ) {
                     all_rec.emplace( recp );
                     break;
                 }
             } else {
                 debugmsg( "Parameter(s) expected for recipe %s but none found for omt %s", id, omt_ter.id().str() );
             }
         }
     }
     return all_rec;
 }
References debugmsg, int_id< T >::id(), is_ot_match(), omt_types_parameters::omt, omt_types_parameters::omt_type, omt_types_parameters::parameters, anonymous_namespace{recipe_groups.cpp}::recipe_groups_data, and string_id< T >::str().
load()
void recipe_group::load (const JsonObject & jo, const std::string & src)
Definition at line 181 of file recipe_groups.cpp.
 {
     recipe_groups_data.load( jo, src );
 }
References anonymous_namespace{recipe_groups.cpp}::recipe_groups_data.
Referenced by DynamicDataLoader::initialize().
reset()
void recipe_group::reset ()
Definition at line 191 of file recipe_groups.cpp.
 {
     recipe_groups_data.reset();
 }
References anonymous_namespace{recipe_groups.cpp}::recipe_groups_data.
Referenced by DynamicDataLoader::unload_data().