Cataclysm DDA: iuse Namespace Reference
iuse Namespace Reference
Functions
std::optional< int > alcohol_medium (Character *, item *, const tripoint &)
std::optional< int > alcohol_strong (Character *, item *, const tripoint &)
std::optional< int > alcohol_weak (Character *, item *, const tripoint &)
std::optional< int > antibiotic (Character *, item *, const tripoint &)
std::optional< int > anticonvulsant (Character *, item *, const tripoint &)
std::optional< int > antifungal (Character *, item *, const tripoint &)
std::optional< int > antiparasitic (Character *, item *, const tripoint &)
std::optional< int > blech (Character *, item *, const tripoint &)
std::optional< int > blech_because_unclean (Character *, item *, const tripoint &)
std::optional< int > chew (Character *, item *, const tripoint &)
std::optional< int > coke (Character *, item *, const tripoint &)
std::optional< int > datura (Character *, item *, const tripoint &)
std::optional< int > ecig (Character *, item *, const tripoint &)
std::optional< int > eyedrops (Character *, item *, const tripoint &)
std::optional< int > flu_vaccine (Character *, item *, const tripoint &)
std::optional< int > flumed (Character *, item *, const tripoint &)
std::optional< int > flusleep (Character *, item *, const tripoint &)
std::optional< int > fungicide (Character *, item *, const tripoint &)
std::optional< int > honeycomb (Character *, item *, const tripoint &)
std::optional< int > inhaler (Character *, item *, const tripoint &)
std::optional< int > marloss (Character *, item *, const tripoint &)
std::optional< int > marloss_gel (Character *, item *, const tripoint &)
std::optional< int > marloss_seed (Character *, item *, const tripoint &)
std::optional< int > meditate (Character *, item *, const tripoint &)
std::optional< int > meth (Character *, item *, const tripoint &)
std::optional< int > mycus (Character *, item *, const tripoint &)
std::optional< int > petfood (Character *p, item *it, const tripoint &)
std::optional< int > plantblech (Character *, item *, const tripoint &)
std::optional< int > poison (Character *, item *, const tripoint &)
std::optional< int > prozac (Character *, item *, const tripoint &)
std::optional< int > purify_smart (Character *, item *, const tripoint &)
std::optional< int > sewage (Character *, item *, const tripoint &)
std::optional< int > smoking (Character *, item *, const tripoint &)
Entry point for intentional bodily intake of smoke via paper wrapped one time use items: cigars, cigarettes, etc.
std::optional< int > thorazine (Character *, item *, const tripoint &)
std::optional< int > weed_cake (Character *, item *, const tripoint &)
std::optional< int > xanax (Character *, item *, const tripoint &)
std::optional< int > acidbomb_act (Character *, item *, const tripoint &)
std::optional< int > adrenaline_injector (Character *, item *, const tripoint &)
std::optional< int > afs_translocator (Character *, item *, const tripoint &)
std::optional< int > bell (Character *, item *, const tripoint &)
std::optional< int > blood_draw (Character *, item *, const tripoint &)
std::optional< int > boltcutters (Character *, item *, const tripoint &)
std::optional< int > break_stick (Character *, item *, const tripoint &)
std::optional< int > c4 (Character *, item *, const tripoint &)
std::optional< int > call_of_tindalos (Character *, item *, const tripoint &)
std::optional< int > camera (Character *, item *, const tripoint &)
std::optional< int > can_goo (Character *, item *, const tripoint &)
std::optional< int > capture_monster_act (Character *, item *, const tripoint &)
std::optional< int > capture_monster_veh (Character *, item *, const tripoint &)
std::optional< int > change_eyes (Character *, item *, const tripoint &)
std::optional< int > change_skin (Character *, item *, const tripoint &)
std::optional< int > chop_logs (Character *, item *, const tripoint &)
std::optional< int > chop_tree (Character *, item *, const tripoint &)
std::optional< int > clear_rubble (Character *, item *, const tripoint &)
std::optional< int > coin_flip (Character *, item *, const tripoint &)
std::optional< int > contacts (Character *, item *, const tripoint &)
std::optional< int > crowbar (Character *, item *, const tripoint &)
std::optional< int > crowbar_weak (Character *, item *, const tripoint &)
std::optional< int > dig (Character *, item *, const tripoint &)
std::optional< int > dig_channel (Character *, item *, const tripoint &)
std::optional< int > directional_antenna (Character *, item *, const tripoint &)
std::optional< int > directional_hologram (Character *, item *, const tripoint &)
std::optional< int > dive_tank_activate (Character *, item *, const tripoint &)
std::optional< int > dive_tank (Character *, item *, const tripoint &)
std::optional< int > dog_whistle (Character *, item *, const tripoint &)
std::optional< int > ehandcuffs (Character *, item *, const tripoint &)
std::optional< int > ehandcuffs_tick (Character *, item *, const tripoint &)
std::optional< int > epic_music (Character *, item *, const tripoint &)
std::optional< int > einktabletpc (Character *, item *, const tripoint &)
std::optional< int > emf_passive_on (Character *, item *, const tripoint &)
std::optional< int > extinguisher (Character *, item *, const tripoint &)
std::optional< int > fill_pit (Character *, item *, const tripoint &)
std::optional< int > firecracker (Character *, item *, const tripoint &)
std::optional< int > firecracker_pack (Character *, item *, const tripoint &)
std::optional< int > firecracker_pack_act (Character *, item *, const tripoint &)
std::optional< int > fish_trap (Character *, item *, const tripoint &)
std::optional< int > fish_trap_tick (Character *, item *, const tripoint &)
std::optional< int > fishing_rod (Character *, item *, const tripoint &)
std::optional< int > fitness_check (Character *p, item *it, const tripoint &)
std::optional< int > foodperson (Character *, item *, const tripoint &)
std::optional< int > foodperson_voice (Character *, item *, const tripoint &)
std::optional< int > gasmask (Character *, item *, const tripoint &)
std::optional< int > gasmask_activate (Character *, item *, const tripoint &)
std::optional< int > geiger (Character *, item *, const tripoint &)
std::optional< int > geiger_active (Character *, item *, const tripoint &)
std::optional< int > granade_act (Character *, item *, const tripoint &)
std::optional< int > grenade_inc_act (Character *, item *, const tripoint &)
std::optional< int > gun_repair (Character *, item *, const tripoint &)
std::optional< int > gunmod_attach (Character *, item *, const tripoint &)
std::optional< int > hacksaw (Character *, item *, const tripoint &it_pnt)
std::optional< int > hairkit (Character *, item *, const tripoint &)
std::optional< int > hammer (Character *, item *, const tripoint &)
std::optional< int > hand_crank (Character *, item *, const tripoint &)
std::optional< int > heat_food (Character *, item *, const tripoint &)
std::optional< int > heatpack (Character *, item *, const tripoint &)
std::optional< int > hotplate (Character *, item *, const tripoint &)
std::optional< int > hotplate_atomic (Character *, item *, const tripoint &)
std::optional< int > jackhammer (Character *, item *, const tripoint &)
std::optional< int > jet_injector (Character *, item *, const tripoint &)
std::optional< int > lumber (Character *, item *, const tripoint &)
std::optional< int > ma_manual (Character *, item *, const tripoint &)
std::optional< int > magic_8_ball (Character *, item *, const tripoint &)
std::optional< int > measure_resonance (Character *, item *, const tripoint &)
std::optional< int > electricstorage (Character *, item *, const tripoint &)
std::optional< int > ebooksave (Character *, item *, const tripoint &)
std::optional< int > ebookread (Character *, item *, const tripoint &)
std::optional< int > makemound (Character *, item *, const tripoint &)
std::optional< int > mace (Character *, item *, const tripoint &)
std::optional< int > manage_exosuit (Character *, item *, const tripoint &)
std::optional< int > melatonin_tablet (Character *, item *, const tripoint &)
std::optional< int > mininuke (Character *, item *, const tripoint &)
std::optional< int > molotov_lit (Character *, item *, const tripoint &)
std::optional< int > mop (Character *, item *, const tripoint &)
std::optional< int > mp3 (Character *, item *, const tripoint &)
std::optional< int > mp3_on (Character *, item *, const tripoint &)
std::optional< int > mp3_deactivate (Character *, item *, const tripoint &)
std::optional< int > noise_emitter_on (Character *, item *, const tripoint &)
std::optional< int > oxygen_bottle (Character *, item *, const tripoint &)
std::optional< int > oxytorch (Character *, item *, const tripoint &)
std::optional< int > binder_add_recipe (Character *, item *, const tripoint &)
std::optional< int > binder_manage_recipe (Character *, item *, const tripoint &)
std::optional< int > pack_cbm (Character *p, item *it, const tripoint &)
std::optional< int > pack_item (Character *, item *, const tripoint &)
std::optional< int > pick_lock (Character *p, item *it, const tripoint &pos)
std::optional< int > pickaxe (Character *, item *, const tripoint &)
std::optional< int > play_game (Character *, item *, const tripoint &)
std::optional< int > portable_game (Character *, item *, const tripoint &)
std::optional< int > portal (Character *, item *, const tripoint &)
std::optional< int > radglove (Character *, item *, const tripoint &)
std::optional< int > radio_mod (Character *, item *, const tripoint &)
std::optional< int > radio_off (Character *, item *, const tripoint &)
std::optional< int > radio_on (Character *, item *, const tripoint &)
std::optional< int > radio_tick (Character *, item *, const tripoint &)
std::optional< int > remove_all_mods (Character *, item *, const tripoint &)
std::optional< int > robotcontrol (Character *, item *, const tripoint &)
std::optional< int > rpgdie (Character *, item *, const tripoint &)
std::optional< int > seed (Character *, item *, const tripoint &)
std::optional< int > shavekit (Character *, item *, const tripoint &)
std::optional< int > shocktonfa_off (Character *, item *, const tripoint &)
std::optional< int > shocktonfa_on (Character *, item *, const tripoint &)
std::optional< int > siphon (Character *, item *, const tripoint &)
std::optional< int > solarpack (Character *, item *, const tripoint &)
std::optional< int > solarpack_off (Character *, item *, const tripoint &)
std::optional< int > spray_can (Character *, item *, const tripoint &)
std::optional< int > stimpack (Character *, item *, const tripoint &)
std::optional< int > strong_antibiotic (Character *, item *, const tripoint &)
std::optional< int > talking_doll (Character *, item *, const tripoint &)
std::optional< int > tazer (Character *, item *, const tripoint &)
std::optional< int > tazer2 (Character *, item *, const tripoint &)
std::optional< int > teleport (Character *, item *, const tripoint &)
std::optional< int > toolmod_attach (Character *, item *, const tripoint &)
std::optional< int > towel (Character *, item *, const tripoint &)
std::optional< int > unfold_generic (Character *, item *, const tripoint &)
std::optional< int > unpack_item (Character *, item *, const tripoint &)
std::optional< int > vibe (Character *, item *, const tripoint &)
std::optional< int > voltmeter (Character *p, item *it, const tripoint &)
std::optional< int > vortex (Character *, item *, const tripoint &)
std::optional< int > wash_all_items (Character *, item *, const tripoint &)
std::optional< int > wash_hard_items (Character *, item *, const tripoint &)
std::optional< int > wash_items (Character *p, bool soft_items, bool hard_items)
std::optional< int > wash_soft_items (Character *, item *, const tripoint &)
std::optional< int > water_purifier (Character *, item *, const tripoint &)
std::optional< int > weak_antibiotic (Character *, item *, const tripoint &)
std::optional< int > weather_tool (Character *, item *, const tripoint &)
std::optional< int > sextant (Character *, item *, const tripoint &)
std::optional< int > lux_meter (Character *, item *, const tripoint &)
std::optional< int > dbg_lux_meter (Character *, item *, const tripoint &)
std::optional< int > calories_intake_tracker (Character *p, item *, const tripoint &)
std::optional< int > radiocar (Character *, item *, const tripoint &)
std::optional< int > radiocaron (Character *, item *, const tripoint &)
std::optional< int > radiocontrol (Character *, item *, const tripoint &)
std::optional< int > radiocontrol_tick (Character *, item *, const tripoint &)
std::optional< int > multicooker (Character *, item *, const tripoint &)
std::optional< int > multicooker_tick (Character *, item *, const tripoint &)
std::optional< int > remoteveh (Character *, item *, const tripoint &)
std::optional< int > remoteveh_tick (Character *, item *, const tripoint &)
std::optional< int > craft (Character *, item *, const tripoint &)
std::optional< int > disassemble (Character *, item *, const tripoint &)
void cut_log_into_planks (Character &)
void play_music (Character *p, const tripoint &source, int volume, int max_morale)
int towel_common (Character *, item *, bool)
bool robotcontrol_can_target (Character *, const monster &)
std::optional< int > handle_ground_graffiti (Character &p, item *it, const std::string &prefix, const tripoint &where)
std::optional< std::string > can_smoke (const Character &you)
Function Documentation
acidbomb_act()
std::optional< int > iuse::acidbomb_act (Character * p, item * it, const tripoint & pos)
Definition at line 3422 of file iuse.cpp.
 {
     if( !p ) {
         it->charges = -1;
         map &here = get_map();
         for( const tripoint &tmp : here.points_in_radius( pos, 1 ) ) {
             here.add_field( tmp, fd_acid, 3 );
         }
         return 1;
     }
     return std::nullopt;
 }
References map::add_field(), item::charges, fd_acid, get_map(), map::points_in_radius(), and math_opers::pos().
Referenced by Item_factory::init().
adrenaline_injector()
std::optional< int > iuse::adrenaline_injector (Character * p, item * it, const tripoint &)
Definition at line 5028 of file iuse.cpp.
 {
     if( p->is_npc() && p->get_effect_dur( effect_adrenaline ) >= 30_minutes ) {
         return std::nullopt;
     }
     p->mod_moves( -to_moves<int>( 1_seconds ) );
     p->add_msg_player_or_npc( _( "You inject yourself with adrenaline." ),
                               _( "<npcname> injects themselves with adrenaline." ) );
     item syringe( "syringe", it->birthday() );
     p->i_add( syringe );
     if( p->has_effect( effect_adrenaline ) ) {
         p->add_msg_if_player( m_bad, _( "Your heart spasms!" ) );
         // Note: not the mod, the health
         p->mod_livestyle( -20 );
     }
     p->add_effect( effect_adrenaline, 20_minutes );
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), Character::add_msg_player_or_npc(), item::birthday(), effect_adrenaline, Creature::get_effect_dur(), Creature::has_effect(), Character::i_add(), Character::is_npc(), m_bad, Character::mod_livestyle(), and Creature::mod_moves().
Referenced by Character::get_consume_time(), and Item_factory::init().
afs_translocator()
std::optional< int > iuse::afs_translocator (Character * p, item * it, const tripoint &)
Definition at line 6896 of file iuse.cpp.
 {
     if( !it->ammo_sufficient( p ) ) {
         return std::nullopt;
     }
     const std::optional<tripoint> dest_ = choose_adjacent( _( "Create buoy where?" ) );
     if( !dest_ ) {
         return std::nullopt;
     }
     tripoint dest = *dest_;
     p->mod_moves( -to_moves<int>( 2_seconds ) );
     map &here = get_map();
     if( here.impassable( dest ) || here.has_flag( ter_furn_flag::TFLAG_NO_FLOOR, dest ) ||
         here.has_furn( dest ) ) {
         add_msg( m_info, _( "The %s, emits a short angry beep." ), it->tname() );
         return std::nullopt;
     } else {
         here.furn_set( dest, furn_f_translocator_buoy );
         add_msg( m_info, _( "Space warps momentarily as the %s is created." ),
                  furn_f_translocator_buoy.obj().name() );
         return  1;
     }
 }
References _, add_msg(), item::ammo_sufficient(), choose_adjacent(), furn_f_translocator_buoy, map::furn_set(), get_map(), map::has_flag(), map::has_furn(), map::impassable(), m_info, Creature::mod_moves(), map_data_common_t::name(), string_id< T >::obj(), TFLAG_NO_FLOOR, and item::tname().
Referenced by Item_factory::init().
alcohol_medium()
std::optional< int > iuse::alcohol_medium (Character * p, item * it, const tripoint &)
Definition at line 526 of file iuse.cpp.
 {
     return alcohol( *p, *it, 1 );
 }
References alcohol().
Referenced by Item_factory::init().
alcohol_strong()
std::optional< int > iuse::alcohol_strong (Character * p, item * it, const tripoint &)
Definition at line 531 of file iuse.cpp.
 {
     return alcohol( *p, *it, 2 );
 }
References alcohol().
Referenced by Item_factory::init().
alcohol_weak()
std::optional< int > iuse::alcohol_weak (Character * p, item * it, const tripoint &)
Definition at line 521 of file iuse.cpp.
 {
     return alcohol( *p, *it, 0 );
 }
References alcohol().
Referenced by Item_factory::init().
antibiotic()
std::optional< int > iuse::antibiotic (Character * p, item * , const tripoint &)
Definition at line 625 of file iuse.cpp.
 {
     p->add_msg_player_or_npc( m_neutral,
                               _( "You take some antibiotics." ),
                               _( "<npcname> takes some antibiotics." ) );
     if( p->has_effect( effect_tetanus ) ) {
         if( one_in( 3 ) ) {
             p->remove_effect( effect_tetanus );
             p->add_msg_if_player( m_good, _( "The muscle spasms start to go away." ) );
         } else {
             p->add_msg_if_player( m_warning, _( "The medication does nothing to help the spasms." ) );
         }
     }
     if( p->has_effect( effect_infected ) && !p->has_effect( effect_antibiotic ) ) {
         p->add_msg_if_player( m_good,
                               _( "Maybe this is just the placebo effect, but you feel a little better as the dose settles in." ) );
     }
     p->add_effect( effect_antibiotic, 12_hours );
     p->add_effect( effect_antibiotic_visible, rng( 9_hours, 15_hours ) );
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), Character::add_msg_player_or_npc(), effect_antibiotic, effect_antibiotic_visible, effect_infected, effect_tetanus, Creature::has_effect(), m_good, m_neutral, m_warning, one_in(), Creature::remove_effect(), and rng().
Referenced by Item_factory::init().
anticonvulsant()
std::optional< int > iuse::anticonvulsant (Character * p, item * , const tripoint &)
Strength reduces duration of anticonvulsant medication
Definition at line 789 of file iuse.cpp.
 {
     p->add_msg_if_player( _( "You take some anticonvulsant medication." ) );
     /** @EFFECT_STR reduces duration of anticonvulsant medication */
     time_duration duration = 8_hours - p->str_cur * rng( 0_turns, 10_minutes );
     if( p->has_trait( trait_TOLERANCE ) ) {
         duration -= 1_hours;
     }
     if( p->has_trait( trait_LIGHTWEIGHT ) ) {
         duration += 2_hours;
     }
     p->add_effect( effect_valium, duration );
     p->add_effect( effect_took_anticonvulsant_visible, duration );
     p->add_effect( effect_high, duration );
     if( p->has_effect( effect_shakes ) ) {
         p->remove_effect( effect_shakes );
         p->add_msg_if_player( m_good, _( "You stop shaking." ) );
     }
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), effect_high, effect_shakes, effect_took_anticonvulsant_visible, effect_valium, Creature::has_effect(), Character::has_trait(), m_good, Creature::remove_effect(), rng(), Character::str_cur, trait_LIGHTWEIGHT, and trait_TOLERANCE.
Referenced by Item_factory::init().
antifungal()
std::optional< int > iuse::antifungal (Character * p, item * , const tripoint &)
Definition at line 722 of file iuse.cpp.
 {
     if( p->cant_do_underwater() ) {
         return std::nullopt;
     }
     p->add_effect( effect_antifungal, 4_hours );
     if( p->has_effect( effect_fungus ) ) {
         p->add_msg_if_player( m_warning,
                               _( "You feel a burning sensation slowly radiating throughout your skin." ) );
     }
     if( p->has_effect( effect_spores ) ) {
         if( !p->has_effect( effect_fungus ) ) {
             p->add_msg_if_player( m_warning, _( "Your skin grows warm for a moment." ) );
         }
     }
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), Creature::cant_do_underwater(), effect_antifungal, effect_fungus, effect_spores, Creature::has_effect(), and m_warning.
Referenced by Item_factory::init().
antiparasitic()
std::optional< int > iuse::antiparasitic (Character * p, item * , const tripoint &)
Definition at line 740 of file iuse.cpp.
 {
     if( p->cant_do_underwater() ) {
         return std::nullopt;
     }
     p->add_msg_if_player( _( "You take some antiparasitic medication." ) );
     if( p->has_effect( effect_dermatik ) ) {
         p->remove_effect( effect_dermatik );
         p->add_msg_if_player( m_good, _( "The itching sensation under your skin fades away." ) );
     }
     if( p->has_effect( effect_tapeworm ) ) {
         p->remove_effect( effect_tapeworm );
         p->guts.mod_nutr( -1 ); // You just digested the tapeworm.
         if( p->has_flag( json_flag_PAIN_IMMUNE ) ) {
             p->add_msg_if_player( m_good, _( "Your bowels clench as something inside them dies." ) );
         } else {
             p->add_msg_if_player( m_mixed, _( "Your bowels spasm painfully as something inside them dies." ) );
             p->mod_pain( rng( 8, 24 ) );
         }
     }
     if( p->has_effect( effect_bloodworms ) ) {
         p->remove_effect( effect_bloodworms );
         p->add_msg_if_player( _( "Your skin prickles and your veins itch for a few moments." ) );
     }
     if( p->has_effect( effect_blood_spiders ) ) {
         p->remove_effect( effect_blood_spiders );
         p->add_msg_if_player( _( "Your veins relax in a soothing wave through your body." ) );
     }
     if( p->has_effect( effect_brainworms ) ) {
         p->remove_effect( effect_brainworms );
         if( p->has_flag( json_flag_PAIN_IMMUNE ) ) {
             p->add_msg_if_player( m_good, _( "The pressure inside your head feels better already." ) );
         } else {
             p->add_msg_if_player( m_mixed,
                                   _( "Your head pounds like a sore tooth as something inside of it dies." ) );
             p->mod_pain( rng( 8, 24 ) );
         }
     }
     if( p->has_effect( effect_paincysts ) ) {
         p->remove_effect( effect_paincysts );
         if( p->has_flag( json_flag_PAIN_IMMUNE ) ) {
             p->add_msg_if_player( m_good, _( "The stiffness in your joints goes away." ) );
         } else {
             p->add_msg_if_player( m_good, _( "The pain in your joints goes away." ) );
         }
     }
     return 1;
 }
References _, Character::add_msg_if_player(), Creature::cant_do_underwater(), effect_blood_spiders, effect_bloodworms, effect_brainworms, effect_dermatik, effect_paincysts, effect_tapeworm, Character::guts, Creature::has_effect(), Character::has_flag(), json_flag_PAIN_IMMUNE, m_good, m_mixed, stomach_contents::mod_nutr(), Character::mod_pain(), Creature::remove_effect(), and rng().
Referenced by Item_factory::init().
bell()
std::optional< int > iuse::bell (Character * p, item * it, const tripoint &)
Definition at line 5281 of file iuse.cpp.
 {
     if( it->typeId() == itype_cow_bell ) {
         sounds::sound( p->pos(), 12, sounds::sound_t::music, _( "Clank!  Clank!" ), true, "misc",
                        "cow_bell" );
         if( !p->is_deaf() ) {
             auto cattle_level =
                 p->mutation_category_level.find( mutation_category_CATTLE );
             const int cow_factor = 1 + ( cattle_level == p->mutation_category_level.end() ?
                                          0 : cattle_level->second );
             if( x_in_y( cow_factor, 1 + cow_factor ) ) {
                 p->add_morale( MORALE_MUSIC, 1, std::min( cow_factor, 100 ) );
             }
         }
     } else {
         sounds::sound( p->pos(), 4, sounds::sound_t::music, _( "Ring!  Ring!" ), true, "misc", "bell" );
     }
     return 1;
 }
References _, Character::add_morale(), Character::is_deaf(), itype_cow_bell, min(), MORALE_MUSIC, sounds::music, mutation_category_CATTLE, Character::mutation_category_level, Creature::pos(), sounds::sound(), item::typeId(), and x_in_y().
Referenced by Item_factory::init().
binder_add_recipe()
std::optional< int > iuse::binder_add_recipe (Character * p, item * binder, const tripoint &)
Definition at line 8756 of file iuse.cpp.
 {
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     if( p->is_underwater() ) {
         p->add_msg_if_player( m_info, _( "You rethink trying to write underwater." ) );
         return std::nullopt;
     }
     const inventory crafting_inv = p->crafting_inventory();
     const std::vector<const item *> writing_tools = crafting_inv.items_with( [&]( const item & it ) {
         return it.has_flag( flag_WRITE_MESSAGE ) && it.ammo_sufficient( p );
     } );
     if( writing_tools.empty() ) {
         p->add_msg_if_player( m_info, _( "You do not have anything to write with." ) );
         return std::nullopt;
     }
     if( p->fine_detail_vision_mod() > 4.0f ) {
         p->add_msg_if_player( m_info, _( "It's too dark to write!" ) );
         return std::nullopt;
     }
     const recipe_subset res = p->get_recipes_from_books( crafting_inv );
     const std::vector<const recipe *> recipes( res.begin(), res.end() );
     const auto enough_writing_tool_charges = [&writing_tools]( int pages ) {
         for( const item *it : writing_tools ) {
             if( it->ammo_required() == 0 ) {
                 return true;
             }
             pages -= it->ammo_remaining() / it->ammo_required();
             if( pages <= 0 ) {
                 return true;
             }
         }
         return false;
     };
     uilist menu;
     menu.text = _( "Choose recipe to copy" );
     menu.hilight_disabled = true;
     menu.desc_enabled = true;
     for( const recipe *r : recipes ) {
         std::string desc;
         const int pages = bookbinder_copy_activity_actor::pages_for_recipe( *r );
         const std::string pages_str = string_format( n_gettext( "%1$d page", "%1$d pages", pages ), pages );
         if( !p->has_charges( itype_paper, pages ) ) {
             desc = _( "You do not have enough paper to copy this recipe." );
         } else if( binder->remaining_ammo_capacity() <  pages ) {
             desc = _( "Your recipe book can not fit this recipe." );
         } else if( binder->get_saved_recipes().count( r->ident() ) != 0 ) {
             desc = string_format( _( "Your recipe book already has a recipe for %s." ), r->result_name() );
         } else if( !enough_writing_tool_charges( pages ) ) {
             desc = _( "Your writing tools do not have enough charges." );
         }
         menu.addentry_col( -1, desc.empty(), std::nullopt, r->result_name(), pages_str, desc );
     }
     if( menu.entries.empty() ) {
         p->add_msg_if_player( m_info, _( "You do not have any recipes you can copy." ) );
         return std::nullopt;
     }
     menu.query();
     if( menu.ret < 0 ) {
         return std::nullopt;
     }
     bookbinder_copy_activity_actor act( item_location( *p, binder ), recipes[menu.ret]->ident() );
     p->assign_activity( act );
     return std::nullopt;
 }
References _, act, Character::add_msg_if_player(), uilist::addentry_col(), item::ammo_remaining(), item::ammo_required(), item::ammo_sufficient(), Character::assign_activity(), recipe_subset::begin(), Character::cant_do_mounted(), Character::crafting_inventory(), uilist::desc_enabled, recipe_subset::end(), uilist::entries, Character::fine_detail_vision_mod(), flag_WRITE_MESSAGE, Character::get_recipes_from_books(), item::get_saved_recipes(), Character::has_charges(), item::has_flag(), uilist::hilight_disabled, Creature::is_underwater(), visitable::items_with(), itype_paper, m_info, n_gettext, bookbinder_copy_activity_actor::pages_for_recipe(), uilist::query(), item::remaining_ammo_capacity(), uilist::ret, string_format(), and uilist::text.
Referenced by Item_factory::init().
binder_manage_recipe()
std::optional< int > iuse::binder_manage_recipe (Character * p, item * binder, const tripoint & ipos)
Definition at line 8832 of file iuse.cpp.
 {
     if( p->is_underwater() ) {
         p->add_msg_if_player( m_info, _( "Doing that would ruin the %1$s." ), binder->tname() );
         return std::nullopt;
     }
     std::set<recipe_id> binder_recipes = binder->get_saved_recipes();
     const std::vector<recipe_id> recipes( binder_recipes.begin(), binder_recipes.end() );
     if( binder_recipes.empty() ) {
         p->add_msg_if_player( m_info, _( "You have no recipes to manage." ) );
         return std::nullopt;
     }
     uilist rmenu;
     rmenu.text = _( "Manage recipes" );
     for( const recipe_id &new_recipe : recipes ) {
         std::string recipe_name = new_recipe->result_name();
         if( p->knows_recipe( &new_recipe.obj() ) ) {
             recipe_name += _( " (KNOWN)" );
         }
         const int pages = bookbinder_copy_activity_actor::pages_for_recipe( *new_recipe );
         rmenu.addentry_col( -1, true, ' ', recipe_name,
                             string_format( n_gettext( "%1$d page", "%1$d pages", pages ), pages ) );
     }
     rmenu.query();
     if( rmenu.ret < 0 ) {
         return std::nullopt;
     }
     const recipe_id &rec = recipes[rmenu.ret];
     if( !query_yn( _( "Remove the recipe for %1$s?" ), rec->result_name() ) ) {
         return std::nullopt;
     }
     binder_recipes.erase( rec );
     binder->set_saved_recipes( binder_recipes );
     const int pages = bookbinder_copy_activity_actor::pages_for_recipe( *rec );
     binder->ammo_consume( pages, ipos, p );
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), uilist::addentry_col(), item::ammo_consume(), item::get_saved_recipes(), Creature::is_underwater(), Character::knows_recipe(), m_info, n_gettext, bookbinder_copy_activity_actor::pages_for_recipe(), uilist::query(), query_yn(), recipe::result_name(), uilist::ret, item::set_saved_recipes(), string_format(), uilist::text, and item::tname().
Referenced by Item_factory::init().
blech()
std::optional< int > iuse::blech (Character * p, item * it, const tripoint &)
Definition at line 1054 of file iuse.cpp.
 {
     // TODO: Add more effects?
     if( it->made_of( phase_id::LIQUID ) ) {
         if( !p->query_yn( _( "This looks unhealthy, sure you want to drink it?" ) ) ) {
             return std::nullopt;
         }
     } else { //Assume that if a blech consumable isn't a drink, it will be eaten.
         if( !p->query_yn( _( "This looks unhealthy, sure you want to eat it?" ) ) ) {
             return std::nullopt;
         }
     }
     if( it->has_flag( flag_ACID ) && ( p->has_trait( trait_ACIDPROOF ) ||
                                        p->has_trait( trait_ACIDBLOOD ) ) ) {
         p->add_msg_if_player( m_bad, _( "Blech, that tastes gross!" ) );
         //reverse the harmful values of drinking this acid.
         double multiplier = -1;
         p->stomach.mod_nutr( -p->nutrition_for( *it ) * multiplier );
         p->mod_thirst( -it->get_comestible()->quench * multiplier );
         p->stomach.mod_quench( 20 ); //acidproof people can drink acids like diluted water.
         p->mod_daily_health( it->get_comestible()->healthy * multiplier,
                              it->get_comestible()->healthy * multiplier );
         p->add_morale( MORALE_FOOD_BAD, it->get_comestible_fun() * multiplier, 60, 1_hours, 30_minutes,
                        false, it->type );
     } else if( it->has_flag( flag_ACID ) || it->has_flag( flag_CORROSIVE ) ) {
         p->add_msg_if_player( m_bad, _( "Blech, that burns your throat!" ) );
         p->mod_pain( rng( 32, 64 ) );
         p->add_effect( effect_poison, 1_hours );
         p->apply_damage( nullptr, bodypart_id( "torso" ), rng( 4, 12 ) );
         p->vomit();
     } else {
         p->add_msg_if_player( m_bad, _( "Blech, you don't feel you can stomach much of that." ) );
         p->add_effect( effect_nausea, 3_minutes );
     }
     return 1;
 }
References _, Creature::add_effect(), Character::add_morale(), Character::add_msg_if_player(), Character::apply_damage(), effect_nausea, effect_poison, flag_ACID, flag_CORROSIVE, item::get_comestible(), item::get_comestible_fun(), item::has_flag(), Character::has_trait(), LIQUID, m_bad, item::made_of(), Character::mod_daily_health(), stomach_contents::mod_nutr(), Character::mod_pain(), stomach_contents::mod_quench(), Character::mod_thirst(), MORALE_FOOD_BAD, Character::nutrition_for(), Character::query_yn(), rng(), Character::stomach, trait_ACIDBLOOD, trait_ACIDPROOF, item::type, and Character::vomit().
Referenced by Item_factory::init(), and plantblech().
blech_because_unclean()
std::optional< int > iuse::blech_because_unclean (Character * p, item * it, const tripoint &)
Definition at line 1092 of file iuse.cpp.
 {
     if( !p->is_npc() ) {
         if( it->made_of( phase_id::LIQUID ) ) {
             if( !p->query_yn( _( "This looks unclean; are you sure you want to drink it?" ) ) ) {
                 return std::nullopt;
             }
         } else { //Assume that if a blech consumable isn't a drink, it will be eaten.
             if( !p->query_yn( _( "This looks unclean; are you sure you want to eat it?" ) ) ) {
                 return std::nullopt;
             }
         }
     }
     return 1;
 }
References _, Character::is_npc(), LIQUID, item::made_of(), and Character::query_yn().
Referenced by Item_factory::init().
blood_draw()
std::optional< int > iuse::blood_draw (Character * p, item * it, const tripoint &)
Definition at line 4389 of file iuse.cpp.
 {
     if( p->is_npc() ) {
         return std::nullopt;    // No NPCs for now!
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     if( !it->empty() ) {
         p->add_msg_if_player( m_info, _( "That %s is full!" ), it->tname() );
         return std::nullopt;
     }
     item blood( "blood", calendar::turn );
     bool drew_blood = false;
     bool acid_blood = false;
     bool vampire = false;
     units::temperature blood_temp = units::from_kelvin( -1.0f ); //kelvins
     for( item &map_it : get_map().i_at( point( p->posx(), p->posy() ) ) ) {
         if( map_it.is_corpse() &&
             query_yn( _( "Draw blood from %s?" ),
                       colorize( map_it.tname(), map_it.color_in_inventory() ) ) ) {
             p->add_msg_if_player( m_info, _( "You drew blood from the %s" ), map_it.tname() );
             drew_blood = true;
             blood_temp = map_it.temperature;
             field_type_id bloodtype( map_it.get_mtype()->bloodType() );
             if( bloodtype.obj().has_acid ) {
                 acid_blood = true;
             } else {
                 blood.set_mtype( map_it.get_mtype() );
                 for( const harvest_entry &entry : map_it.get_mtype()->harvest.obj() ) {
                     if( entry.type == harvest_drop_blood ) {
                         blood.convert( itype_id( entry.drop ) );
                         break;
                     }
                 }
             }
         }
     }
     if( !drew_blood && query_yn( _( "Draw your own blood?" ) ) ) {
         p->add_msg_if_player( m_info, _( "You drew your own blood" ) );
         drew_blood = true;
         blood_temp = units::from_celsius( 37 );
         if( p->has_trait( trait_ACIDBLOOD ) ) {
             acid_blood = true;
         }
         if( p->has_trait( trait_VAMPIRE ) ) {
             vampire = true;
         }
         // From wikipedia,
         // "To compare, this (volume of blood loss that causes death) is five to eight times
         // as much blood as people usually give in a blood donation.[2]"
         // This is half a TU, hence I'm setting it to 1/10th of a lethal exsanguination.
         p->vitamin_mod( vitamin_redcells, vitamin_redcells->min() / 10 );
         p->vitamin_mod( vitamin_blood, vitamin_blood->min() / 10 );
         p->mod_pain( 3 );
     }
     if( acid_blood ) {
         item acid( "blood_acid", calendar::turn );
         acid.set_item_temperature( blood_temp );
         it->put_in( acid, pocket_type::CONTAINER );
         if( one_in( 3 ) ) {
             if( it->inc_damage() ) {
                 p->add_msg_if_player( m_info, _( "but acidic blood melts the %s, destroying it!" ),
                                       it->tname() );
                 p->i_rem( it );
                 return 0;
             }
             p->add_msg_if_player( m_info, _( "but acidic blood damages the %s!" ), it->tname() );
         }
     }
     if( vampire ) {
         p->vitamin_mod( vitamin_human_blood_vitamin, -500 );
     }
     if( !drew_blood ) {
         return std::nullopt;;
     }
     blood.set_item_temperature( blood_temp );
     it->put_in( blood, pocket_type::CONTAINER );
     p->mod_moves( -to_moves<int>( 5_seconds ) );
     return 1;
 }
References _, mattack::acid(), Character::add_msg_if_player(), Character::cant_do_mounted(), colorize(), CONTAINER, item::convert(), item::empty(), units::from_celsius(), units::from_kelvin(), get_map(), harvest_drop_blood, field_type::has_acid, Character::has_trait(), Character::i_rem(), item::inc_damage(), Character::is_npc(), m_info, vitamin::min(), Creature::mod_moves(), Character::mod_pain(), int_id< T >::obj(), one_in(), Creature::posx(), Creature::posy(), item::put_in(), query_yn(), item::set_item_temperature(), item::set_mtype(), item::tname(), trait_ACIDBLOOD, trait_VAMPIRE, calendar::turn, vitamin_blood, vitamin_human_blood_vitamin, Character::vitamin_mod(), and vitamin_redcells.
Referenced by Item_factory::init().
boltcutters()
std::optional< int > iuse::boltcutters (Character * p, item * it, const tripoint &)
Definition at line 4726 of file iuse.cpp.
 {
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     map &here = get_map();
     const std::function<bool( const tripoint & )> f =
     [&here, p]( const tripoint & pnt ) {
         if( pnt == p->pos() ) {
             return false;
         } else if( here.has_furn( pnt ) ) {
             return here.furn( pnt )->boltcut->valid();
         } else if( !here.ter( pnt )->is_null() ) {
             return here.ter( pnt )->boltcut->valid();
         }
         return false;
     };
     const std::optional<tripoint> pnt_ = choose_adjacent_highlight(
             _( "Cut up metal where?" ), _( "There is no metal to cut up nearby." ), f, false );
     if( !pnt_ ) {
         return std::nullopt;
     }
     const tripoint &pnt = *pnt_;
     if( !f( pnt ) ) {
         if( pnt == p->pos() ) {
             p->add_msg_if_player( m_info,
                                   _( "You neatly sever all of the veins and arteries in your body.  Oh, wait; never mind." ) );
         } else {
             p->add_msg_if_player( m_info, _( "You can't cut that." ) );
         }
         return std::nullopt;
     }
     p->assign_activity( boltcutting_activity_actor( pnt, item_location{*p, it} ) );
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), Character::assign_activity(), ter_t::boltcut, furn_t::boltcut, Character::cant_do_mounted(), choose_adjacent_highlight(), map::furn(), get_map(), map::has_furn(), ter_t::is_null(), m_info, Creature::pos(), and map::ter().
Referenced by Item_factory::init().
break_stick()
std::optional< int > iuse::break_stick (Character * p, item * it, const tripoint &)
Definition at line 8253 of file iuse.cpp.
 {
     p->mod_moves( -to_moves<int>( 2_seconds ) );
     p->mod_stamina( static_cast<int>( 0.05f * p->get_stamina_max() ) );
     if( p->get_str() < 5 ) {
         p->add_msg_if_player( _( "You are too weak to even try." ) );
         return 0;
     } else if( p->get_str() <= rng( 5, 11 ) ) {
         p->add_msg_if_player(
             _( "You use all your strength, but the stick won't break.  Perhaps try again?" ) );
         return 0;
     }
     std::vector<item_comp> comps;
     comps.emplace_back( it->typeId(), 1 );
     p->consume_items( comps, 1, is_crafting_component );
     int chance = rng( 0, 100 );
     map &here = get_map();
     if( chance <= 20 ) {
         p->add_msg_if_player( _( "You try to break the stick in two, but it shatters into splinters." ) );
         here.spawn_item( p->pos(), "splinter", 2 );
         return 1;
     } else if( chance <= 40 ) {
         p->add_msg_if_player( _( "The stick breaks clean into two parts." ) );
         here.spawn_item( p->pos(), "stick", 2 );
         return 1;
     } else if( chance <= 100 ) {
         p->add_msg_if_player( _( "You break the stick, but one half shatters into splinters." ) );
         here.spawn_item( p->pos(), "stick", 1 );
         here.spawn_item( p->pos(), "splinter", 1 );
         return 1;
     }
     return 0;
 }
References _, Character::add_msg_if_player(), Character::consume_items(), get_map(), Character::get_stamina_max(), Character::get_str(), is_crafting_component(), Creature::mod_moves(), Character::mod_stamina(), Creature::pos(), rng(), map::spawn_item(), and item::typeId().
Referenced by Item_factory::init().
c4()
std::optional< int > iuse::c4 (Character * p, item * it, const tripoint &)
Definition at line 3406 of file iuse.cpp.
 {
     int time;
     bool got_value = query_int( time, _( "Set the timer to how many seconds (0 to cancel)?" ) );
     if( !got_value || time <= 0 ) {
         p->add_msg_if_player( _( "Never mind." ) );
         return std::nullopt;
     }
     p->add_msg_if_player( n_gettext( "You set the timer to %d second.",
                                      "You set the timer to %d seconds.", time ), time );
     it->convert( itype_c4armed );
     it->countdown_point = calendar::turn + time_duration::from_seconds( time );
     it->active = true;
     return 1;
 }
References _, item::active, Character::add_msg_if_player(), item::convert(), item::countdown_point, time_duration::from_seconds(), itype_c4armed, n_gettext, query_int(), and calendar::turn.
Referenced by Item_factory::init(), and raw_noise_4d().
call_of_tindalos()
std::optional< int > iuse::call_of_tindalos (Character * p, item * , const tripoint &)
Definition at line 4377 of file iuse.cpp.
 {
     map &here = get_map();
     for( const tripoint &dest : here.points_in_radius( p->pos(), 12 ) ) {
         if( here.is_cornerfloor( dest ) ) {
             here.add_field( dest, fd_tindalos_rift, 3 );
             add_msg( m_info, _( "You hear a low-pitched echoing howl." ) );
         }
     }
     return 1;
 }
References _, map::add_field(), add_msg(), fd_tindalos_rift, get_map(), map::is_cornerfloor(), m_info, map::points_in_radius(), and Creature::pos().
Referenced by Item_factory::init().
calories_intake_tracker()
std::optional< int > iuse::calories_intake_tracker (Character * p, item * it, const tripoint &)
Definition at line 7895 of file iuse.cpp.
 {
     if( p->has_trait( trait_ILLITERATE ) ) {
         p->add_msg_if_player( m_info, _( "You don't know what you're looking at." ) );
         return std::nullopt;
     } else {
         std::string msg;
         msg.append( "***  " );
         msg.append( string_format( _( "You check your registered calories intake on your %s." ),
                                    it->tname( 1, false ) ) );
         msg.append( "  ***\n\n" );
         msg.append( "-> " );
         msg.append( string_format( _( "You consumed %d kcal today and %d kcal yesterday." ),
                                    p->as_avatar()->get_daily_ingested_kcal( false ),
                                    p->as_avatar()->get_daily_ingested_kcal( true ) ) );
         p->add_msg_if_player( m_neutral, msg );
         popup( msg );
     }
     return 1;
 }
References _, Character::add_msg_if_player(), Creature::as_avatar(), avatar::get_daily_ingested_kcal(), Character::has_trait(), m_info, m_neutral, popup(), string_format(), item::tname(), and trait_ILLITERATE.
Referenced by Item_factory::init().
camera()
std::optional< int > iuse::camera (Character * p, item * it, const tripoint &)
Definition at line 6517 of file iuse.cpp.
 {
     enum {c_shot, c_photos, c_monsters, c_upload};
     // From item processing
     if( !p ) {
         debugmsg( "%s called action camera that requires character but no character is present",
                   it->typeId().str() );
         return std::nullopt;
     }
     // CAMERA_NPC_PHOTOS is old save variable
     bool found_extended_photos = !it->get_var( "CAMERA_NPC_PHOTOS" ).empty() ||
                                  !it->get_var( "CAMERA_EXTENDED_PHOTOS" ).empty();
     bool found_monster_photos = !it->get_var( "CAMERA_MONSTER_PHOTOS" ).empty();
     uilist amenu;
     amenu.text = _( "What to do with camera?" );
     amenu.addentry( c_shot, true, 't', _( "Take a photo" ) );
     if( !found_extended_photos && !found_monster_photos ) {
         amenu.addentry( c_photos, false, 'l', _( "No photos in memory" ) );
     } else {
         if( found_extended_photos ) {
             amenu.addentry( c_photos, true, 'l', _( "List photos" ) );
         }
         if( found_monster_photos ) {
             amenu.addentry( c_monsters, true, 'm', _( "Your collection of monsters" ) );
         }
         amenu.addentry( c_upload, true, 'u', _( "Upload photos to memory card" ) );
     }
     amenu.query();
     const int choice = amenu.ret;
     if( choice < 0 ) {
         return std::nullopt;
     }
     map &here = get_map();
     creature_tracker &creatures = get_creature_tracker();
     if( c_shot == choice ) {
         const std::optional<tripoint> aim_point_ = g->look_around();
         if( !aim_point_ ) {
             p->add_msg_if_player( _( "Never mind." ) );
             return std::nullopt;
         }
         tripoint aim_point = *aim_point_;
         bool incorrect_focus = false;
         tripoint_range<tripoint> aim_bounds = here.points_in_radius( aim_point, 2 );
         std::vector<tripoint> trajectory = line_to( p->pos(), aim_point, 0, 0 );
         trajectory.push_back( aim_point );
         p->mod_moves( -to_moves<int>( 1_seconds ) * 0.5 );
         sounds::sound( p->pos(), 8, sounds::sound_t::activity, _( "Click." ), true, "tool",
                        "camera_shutter" );
         for( std::vector<tripoint>::iterator point_it = trajectory.begin();
              point_it != trajectory.end();
              ++point_it ) {
             const tripoint trajectory_point = *point_it;
             if( point_it != trajectory.end() ) {
                 const tripoint next_point = *( point_it + 1 ); // Trajectory ends on last visible tile
                 if( !here.sees( p->pos(), next_point, rl_dist( p->pos(), next_point ) + 3 ) ) {
                     p->add_msg_if_player( _( "You have the wrong camera focus." ) );
                     incorrect_focus = true;
                     // recalculate target point
                     aim_point = trajectory_point;
                     aim_bounds = here.points_in_radius( trajectory_point, 2 );
                 }
             }
             monster *const mon = creatures.creature_at<monster>( trajectory_point, true );
             Character *const guy = creatures.creature_at<Character>( trajectory_point );
             if( mon || guy || trajectory_point == aim_point ) {
                 int dist = rl_dist( p->pos(), trajectory_point );
                 int camera_bonus = it->has_flag( flag_CAMERA_PRO ) ? 10 : 0;
                 int photo_quality = 20 - rng( dist, dist * 2 ) * 2 + rng( camera_bonus / 2, camera_bonus );
                 if( photo_quality > 5 ) {
                     photo_quality = 5;
                 }
                 if( photo_quality < 0 ) {
                     photo_quality = 0;
                 }
                 if( p->is_blind() ) {
                     photo_quality /= 2;
                 }
                 if( mon ) {
                     monster &z = *mon;
                     // shoot past small monsters and hallucinations
                     if( trajectory_point != aim_point && ( z.type->size <= creature_size::small ||
                                                            z.is_hallucination() ||
                                                            z.type->in_species( species_HALLUCINATION ) ) ) {
                         continue;
                     }
                     if( !aim_bounds.is_point_inside( trajectory_point ) ) {
                         // take a photo of the monster that's in the way
                         p->add_msg_if_player( m_warning, _( "A %s got in the way of your photo." ), z.name() );
                         incorrect_focus = true;
                     } else if( trajectory_point != aim_point ) { // shoot past mon that will be in photo anyway
                         continue;
                     }
                     // get a special message if the target is a hallucination
                     if( trajectory_point == aim_point && ( z.is_hallucination() ||
                                                            z.type->in_species( species_HALLUCINATION ) ) ) {
                         p->add_msg_if_player( _( "Strange there's nothing in the center of this picture?" ) );
                     }
                 } else if( guy ) {
                     if( trajectory_point == aim_point && guy->is_hallucination() ) {
                         p->add_msg_if_player( _( "Strange %s isn't visible on the picture?" ), guy->get_name() );
                     } else if( !aim_bounds.is_point_inside( trajectory_point ) ) {
                         // take a photo of the monster that's in the way
                         p->add_msg_if_player( m_warning, _( "%s got in the way of your photo." ), guy->get_name() );
                         incorrect_focus = true;
                     } else if( trajectory_point != aim_point ) {  // shoot past guy that will be in photo anyway
                         continue;
                     }
                 }
                 if( incorrect_focus ) {
                     photo_quality = photo_quality == 0 ? 0 : photo_quality - 1;
                 }
                 std::vector<item::extended_photo_def> extended_photos;
                 std::vector<monster *> monster_vec;
                 std::vector<Character *> character_vec;
                 item::extended_photo_def photo = photo_def_for_camera_point( trajectory_point, p->pos(),
                                                  monster_vec, character_vec );
                 photo.quality = photo_quality;
                 try {
                     it->read_extended_photos( extended_photos, "CAMERA_EXTENDED_PHOTOS", false );
                     extended_photos.push_back( photo );
                     it->write_extended_photos( extended_photos, "CAMERA_EXTENDED_PHOTOS" );
                 } catch( const JsonError &e ) {
                     debugmsg( "Error when adding new photo (loaded photos = %i): %s", extended_photos.size(),
                               e.c_str() );
                 }
                 const bool selfie = std::find( character_vec.begin(), character_vec.end(),
                                                p ) != character_vec.end();
                 if( selfie ) {
                     p->add_msg_if_player( _( "You took a selfie." ) );
                 } else {
                     if( p->is_blind() ) {
                         p->add_msg_if_player( _( "You took a photo of %s." ), photo.name );
                     } else {
                         p->add_msg_if_player( _( "You took a photo of %1$s. It is %2$s." ), photo.name,
                                               photo_quality_name( photo_quality ) );
                     }
                     std::vector<std::string> blinded_names;
                     for( monster * const &monster_p : monster_vec ) {
                         if( dist < 4 && one_in( dist + 2 ) && monster_p->has_flag( mon_flag_SEES ) ) {
                             monster_p->add_effect( effect_blind, rng( 5_turns, 10_turns ) );
                             blinded_names.push_back( monster_p->name() );
                         }
                     }
                     for( Character * const &character_p : character_vec ) {
                         if( dist < 4 && one_in( dist + 2 ) && !character_p->is_blind() ) {
                             character_p->add_effect( effect_blind, rng( 5_turns, 10_turns ) );
                             blinded_names.push_back( character_p->get_name() );
                         }
                     }
                     if( !blinded_names.empty() ) {
                         p->add_msg_if_player( _( "%s looks blinded." ), enumerate_as_string( blinded_names.begin(),
                         blinded_names.end(), []( const std::string & it ) {
                             return colorize( it, c_light_blue );
                         } ) );
                     }
                 }
                 if( !monster_vec.empty() ) {
                     item_save_monsters( *p, *it, monster_vec, photo_quality );
                 }
                 return 1;
             }
         }
         return 1;
     }
     if( c_photos == choice ) {
         show_photo_selection( *p, *it, "CAMERA_EXTENDED_PHOTOS" );
         return 1;
     }
     if( c_monsters == choice ) {
         if( p->is_blind() ) {
             p->add_msg_if_player( _( "You can't see the camera screen, you're blind." ) );
             return 0;
         }
         uilist pmenu;
         pmenu.text = _( "Your collection of monsters:" );
         std::vector<mtype_id> monster_photos;
         std::vector<std::string> descriptions;
         std::istringstream f_mon( it->get_var( "CAMERA_MONSTER_PHOTOS" ) );
         std::string s;
         int k = 0;
         while( getline( f_mon, s, ',' ) ) {
             if( s.empty() ) {
                 continue;
             }
             monster_photos.emplace_back( s );
             std::string menu_str;
             const monster dummy( monster_photos.back() );
             menu_str = dummy.name();
             descriptions.push_back( dummy.type->get_description() );
             getline( f_mon, s, ',' );
             const int quality = get_quality_from_string( s );
             menu_str += " [" + photo_quality_name( quality ) + "]";
             pmenu.addentry( k++, true, -1, menu_str.c_str() );
         }
         int choice;
         do {
             pmenu.query();
             choice = pmenu.ret;
             if( choice < 0 ) {
                 break;
             }
             popup( "%s", descriptions[choice].c_str() );
         } while( true );
         return 1;
     }
     if( c_upload == choice ) {
         if( p->is_blind() ) {
             p->add_msg_if_player( _( "You can't see the camera screen, you're blind." ) );
             return std::nullopt;
         }
         p->mod_moves( -to_moves<int>( 2_seconds ) );
         avatar *you = p->as_avatar();
         item_location loc;
         if( you != nullptr ) {
             loc = game_menus::inv::titled_filter_menu( []( const item & it ) {
                 return it.has_flag( flag_MC_MOBILE );
             }, *you, _( "Insert memory card" ) );
         }
         if( !loc ) {
             p->add_msg_if_player( m_info, _( "You don't have that item!" ) );
             return 1;
         }
         item &mc = *loc;
         if( mc.has_flag( flag_MC_HAS_DATA ) ) {
             if( !query_yn( _( "Are you sure you want to clear the old data on the card?" ) ) ) {
                 return 1;
             }
         }
         mc.convert( itype_memory_card );
         mc.clear_vars();
         mc.unset_flags();
         mc.set_flag( flag_MC_HAS_DATA );
         mc.set_var( "MC_MONSTER_PHOTOS", it->get_var( "CAMERA_MONSTER_PHOTOS" ) );
         mc.set_var( "MC_EXTENDED_PHOTOS", it->get_var( "CAMERA_EXTENDED_PHOTOS" ) );
         p->add_msg_if_player( m_info,
                               _( "You upload your photos and monster collection to the memory card." ) );
         return 1;
     }
     return 1;
 }
References _, sounds::activity, Character::add_msg_if_player(), uilist::addentry(), Creature::as_avatar(), JsonError::c_str(), item::clear_vars(), item::convert(), creature_tracker::creature_at(), debugmsg, effect_blind, enumerate_as_string(), flag_CAMERA_PRO, flag_MC_HAS_DATA, flag_MC_MOBILE, g, get_creature_tracker(), mtype::get_description(), get_map(), get_quality_from_string(), item::get_var(), item::has_flag(), mtype::in_species(), Character::is_blind(), monster::is_hallucination(), tripoint_range< Tripoint >::is_point_inside(), item_save_monsters(), itype_memory_card, line_to(), m_info, m_warning, Creature::mod_moves(), mon_flag_SEES, item::extended_photo_def::name, monster::name(), one_in(), photo_def_for_camera_point(), photo_quality_name(), map::points_in_radius(), popup(), Creature::pos(), item::extended_photo_def::quality, uilist::query(), query_yn(), item::read_extended_photos(), uilist::ret, rl_dist(), rng(), map::sees(), item::set_flag(), item::set_var(), show_photo_selection(), mtype::size, small, sounds::sound(), species_HALLUCINATION, string_id< T >::str(), uilist::text, game_menus::inv::titled_filter_menu(), monster::type, item::typeId(), item::unset_flags(), and item::write_extended_photos().
Referenced by map::build_seen_cache(), and Item_factory::init().
can_goo()
std::optional< int > iuse::can_goo (Character * p, item * it, const tripoint &)
Definition at line 3225 of file iuse.cpp.
 {
     it->convert( itype_canister_empty );
     int tries = 0;
     tripoint goop;
     goop.z = p->posz();
     map &here = get_map();
     do {
         goop.x = p->posx() + rng( -2, 2 );
         goop.y = p->posy() + rng( -2, 2 );
         tries++;
     } while( here.impassable( goop ) && tries < 10 );
     if( tries == 10 ) {
         return std::nullopt;
     }
     creature_tracker &creatures = get_creature_tracker();
     if( monster *const mon_ptr = creatures.creature_at<monster>( goop ) ) {
         monster &critter = *mon_ptr;
         add_msg_if_player_sees( goop, _( "Black goo emerges from the canister and envelopes the %s!" ),
                                 critter.name() );
         critter.poly( mon_blob );
         critter.set_speed_base( critter.get_speed_base() - rng( 5, 25 ) );
         critter.set_hp( critter.get_speed() );
     } else {
         add_msg_if_player_sees( goop, _( "Living black goo emerges from the canister!" ) );
         if( monster *const goo = g->place_critter_at( mon_blob, goop ) ) {
             goo->friendly = -1;
         }
     }
     if( x_in_y( 3.0, 4.0 ) ) {
         tries = 0;
         bool found = false;
         do {
             goop.x = p->posx() + rng( -2, 2 );
             goop.y = p->posy() + rng( -2, 2 );
             tries++;
             found = here.passable( goop ) && here.tr_at( goop ).is_null();
         } while( !found && tries < 10 );
         if( found ) {
             add_msg_if_player_sees( goop, m_warning, _( "A nearby splatter of goo forms into a goo pit." ) );
             here.trap_set( goop, tr_goo );
         } else {
             return 0;
         }
     }
     return 1;
 }
References _, add_msg_if_player_sees(), item::convert(), creature_tracker::creature_at(), g, get_creature_tracker(), get_map(), Creature::get_speed(), Creature::get_speed_base(), trapfunc::goo(), map::impassable(), trap::is_null(), itype_canister_empty, m_warning, mon_blob, monster::name(), map::passable(), monster::poly(), Creature::posx(), Creature::posy(), Creature::posz(), rng(), monster::set_hp(), Creature::set_speed_base(), map::tr_at(), tr_goo, map::trap_set(), tripoint::x, x_in_y(), tripoint::y, and tripoint::z.
Referenced by Item_factory::init().
can_smoke()
std::optional< std::string > iuse::can_smoke (const Character & you)
Definition at line 451 of file iuse.cpp.
 {
     auto cigs = you.cache_get_items_with( flag_LITCIG, []( const item & it ) {
         return it.active;
     } );
     if( !cigs.empty() ) {
         return string_format( _( "You're already smoking a %s!" ), cigs[0]->tname() );
     }
     if( !you.has_charges( itype_fire, 1 ) ) {
         return _( "You don't have anything to light it with!" );
     }
     return std::nullopt;
 }
References _, item::active, Character::cache_get_items_with(), flag_LITCIG, Character::has_charges(), itype_fire, and string_format().
Referenced by Character::can_eat(), activatable_inventory_preset::get_denial(), and smoking().
capture_monster_act()
std::optional< int > iuse::capture_monster_act (Character * p, item * it, const tripoint & pos)
Definition at line 7997 of file iuse.cpp.
 {
     if( p->is_mounted() ) {
         p->add_msg_if_player( m_info, _( "You can't capture a creature mounted." ) );
         return std::nullopt;
     }
     if( it->has_var( "contained_name" ) ) {
         // Remember contained_name for messages after release_monster erases it
         const std::string contained_name = it->get_var( "contained_name", "" );
         if( it->release_monster( pos ) ) {
             // It's been activated somewhere where there isn't a player or monster, good.
             return 0;
         }
         if( it->has_flag( flag_PLACE_RANDOMLY ) ) {
             if( it->release_monster( p->pos(), 1 ) ) {
                 return 0;
             }
             p->add_msg_if_player( _( "There is no place to put the %s." ), contained_name );
             return std::nullopt;
         } else {
             const std::string query = string_format( _( "Place the %s where?" ), contained_name );
             const std::optional<tripoint> pos_ = choose_adjacent( query );
             if( !pos_ ) {
                 return std::nullopt;
             }
             if( it->release_monster( *pos_ ) ) {
                 p->add_msg_if_player( _( "You release the %s." ), contained_name );
                 return 0;
             }
             p->add_msg_if_player( m_info, _( "You can't place the %s there!" ), contained_name );
             return std::nullopt;
         }
     } else {
         if( !it->has_property( "creature_size_capacity" ) ) {
             debugmsg( "%s has no creature_size_capacity.", it->tname() );
             return std::nullopt;
         }
         const std::string capacity = it->get_property_string( "creature_size_capacity" );
         if( Creature::size_map.count( capacity ) == 0 ) {
             debugmsg( "%s has invalid creature_size_capacity %s.",
                       it->tname(), capacity.c_str() );
             return std::nullopt;
         }
         const std::function<bool( const tripoint & )> adjacent_capturable = []( const tripoint & pnt ) {
             const monster *mon_ptr = get_creature_tracker().creature_at<monster>( pnt );
             return mon_ptr != nullptr;
         };
         const std::string query = string_format( _( "Grab which creature to place in the %s?" ),
                                   it->tname() );
         const std::optional<tripoint> target_ = choose_adjacent_highlight( query,
                                                 _( "There is no creature nearby you can capture." ), adjacent_capturable, false );
         if( !target_ ) {
             p->add_msg_if_player( m_info, _( "You can't use a %s there." ), it->tname() );
             return std::nullopt;
         }
         const tripoint target = *target_;
         // Capture the thing, if it's on the target square.
         if( const monster *const mon_ptr = get_creature_tracker().creature_at<monster>( target ) ) {
             const monster &f = *mon_ptr;
             if( f.get_size() > Creature::size_map.find( capacity )->second ) {
                 p->add_msg_if_player( m_info, _( "The %1$s is too big to put in your %2$s." ),
                                       f.type->nname(), it->tname() );
                 return std::nullopt;
             }
             // TODO: replace this with some kind of melee check.
             int chance = f.hp_percentage() / 10;
             // A weaker monster is easier to capture.
             // If the monster is friendly, then put it in the item
             // without checking if it rolled a success.
             if( f.friendly != 0 || one_in( chance ) ) {
                 p->add_msg_if_player( _( "You capture the %1$s in your %2$s." ),
                                       f.type->nname(), it->tname() );
                 return it->contain_monster( target );
             } else {
                 p->add_msg_if_player( m_bad, _( "The %1$s avoids your attempts to put it in the %2$s." ),
                                       f.type->nname(), it->type->nname( 1 ) );
             }
             p->mod_moves( -to_moves<int>( 1_seconds ) );
         } else {
             add_msg( _( "The %s can't capture nothing" ), it->tname() );
             return std::nullopt;
         }
     }
     return 0;
 }
References _, add_msg(), Character::add_msg_if_player(), choose_adjacent(), choose_adjacent_highlight(), item::contain_monster(), item::count(), creature_tracker::creature_at(), debugmsg, flag_PLACE_RANDOMLY, monster::friendly, get_creature_tracker(), item::get_property_string(), monster::get_size(), item::get_var(), item::has_flag(), item::has_property(), item::has_var(), monster::hp_percentage(), Character::is_mounted(), m_bad, m_info, Creature::mod_moves(), itype::nname(), mtype::nname(), one_in(), Creature::pos(), math_opers::pos(), item::release_monster(), Creature::size_map, string_format(), item::tname(), item::type, and monster::type.
Referenced by capture_monster_veh(), and Item_factory::init().
capture_monster_veh()
std::optional< int > iuse::capture_monster_veh (Character * p, item * it, const tripoint & pos)
Definition at line 7944 of file iuse.cpp.
 {
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     if( !it->has_flag( flag_VEHICLE ) ) {
         p->add_msg_if_player( m_info, _( "The %s must be installed in a vehicle before being loaded." ),
                               it->tname() );
         return std::nullopt;
     }
     capture_monster_act( p, it, pos );
     return 0;
 }
References _, Character::add_msg_if_player(), Character::cant_do_mounted(), capture_monster_act(), flag_VEHICLE, item::has_flag(), m_info, math_opers::pos(), and item::tname().
Referenced by Item_factory::init().
change_eyes()
std::optional< int > iuse::change_eyes (Character * p, item * , const tripoint &)
Definition at line 2964 of file iuse.cpp.
 {
     if( p->is_avatar() ) {
         p->customize_appearance( customize_appearance_choice::EYES );
     }
     return std::nullopt;
 }
References Character::customize_appearance(), EYES, and Creature::is_avatar().
Referenced by Item_factory::init().
change_skin()
std::optional< int > iuse::change_skin (Character * p, item * , const tripoint &)
Definition at line 2972 of file iuse.cpp.
 {
     if( p->is_avatar() ) {
         p->customize_appearance( customize_appearance_choice::SKIN );
     }
     return std::nullopt;
 }
References Character::customize_appearance(), Creature::is_avatar(), and SKIN.
Referenced by Item_factory::init().
chew()
std::optional< int > iuse::chew (Character * p, item * it, const tripoint &)
Definition at line 1131 of file iuse.cpp.
 {
     // TODO: Add more effects?
     p->add_msg_if_player( _( "You chew your %s." ), it->tname() );
     return 1;
 }
References _, Character::add_msg_if_player(), and item::tname().
Referenced by eat(), Item_factory::init(), and Character::modify_morale().
chop_logs()
std::optional< int > iuse::chop_logs (Character * p, item * it, const tripoint &)
Definition at line 4587 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action chop_logs that requires character but no character is present",
                   it->typeId().str() );
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     const std::set<ter_str_id> allowed_ter_id {
         ter_t_trunk,
         ter_t_stump
     };
     map &here = get_map();
     const std::function<bool( const tripoint & )> f = [&allowed_ter_id, &here]( const tripoint & pnt ) {
         const ter_id type = here.ter( pnt );
         const bool is_allowed_terrain = allowed_ter_id.find( type.id() ) != allowed_ter_id.end();
         return is_allowed_terrain;
     };
     const std::optional<tripoint> pnt_ = choose_adjacent_highlight(
             _( "Chop which tree trunk?" ), _( "There is no tree trunk to chop nearby." ), f, false );
     if( !pnt_ ) {
         return std::nullopt;
     }
     const tripoint &pnt = *pnt_;
     if( !f( pnt ) ) {
         p->add_msg_if_player( m_info, _( "You can't chop that." ) );
         return std::nullopt;
     }
     int moves = chop_moves( p, it );
     const std::vector<Character *> helpers = p->get_crafting_helpers();
     for( std::size_t i = 0; i < helpers.size() && i < 3; i++ ) {
         add_msg( m_info, _( "%s helps with this task" ), helpers[i]->get_name() );
     }
     p->assign_activity( chop_logs_activity_actor( moves, item_location( *p, it ) ) );
     p->activity.placement = here.getglobal( pnt );
     return 1;
 }
References _, Character::activity, add_msg(), Character::add_msg_if_player(), Character::assign_activity(), Character::cant_do_mounted(), choose_adjacent_highlight(), chop_moves(), debugmsg, Character::get_crafting_helpers(), get_map(), map::getglobal(), m_info, player_activity::placement, string_id< T >::str(), map::ter(), ter_t_stump, ter_t_trunk, and item::typeId().
Referenced by Item_factory::init().
chop_tree()
std::optional< int > iuse::chop_tree (Character * p, item * it, const tripoint &)
Definition at line 4544 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action chop_tree that requires character but no character is present",
                   it->typeId().str() );
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     map &here = get_map();
     const std::function<bool( const tripoint & )> f = [&here, p]( const tripoint & pnt ) {
         if( pnt == p->pos() ) {
             return false;
         }
         return here.has_flag( ter_furn_flag::TFLAG_TREE, pnt );
     };
     const std::optional<tripoint> pnt_ = choose_adjacent_highlight(
             _( "Chop down which tree?" ), _( "There is no tree to chop down nearby." ), f, false );
     if( !pnt_ ) {
         return std::nullopt;
     }
     const tripoint &pnt = *pnt_;
     if( !f( pnt ) ) {
         if( pnt == p->pos() ) {
             p->add_msg_if_player( m_info, _( "You're not stern enough to shave yourself with THIS." ) );
         } else {
             p->add_msg_if_player( m_info, _( "You can't chop down that." ) );
         }
         return std::nullopt;
     }
     int moves = chop_moves( p, it );
     const std::vector<Character *> helpers = p->get_crafting_helpers();
     for( std::size_t i = 0; i < helpers.size() && i < 3; i++ ) {
         add_msg( m_info, _( "%s helps with this task" ), helpers[i]->get_name() );
     }
     p->assign_activity( chop_tree_activity_actor( moves, item_location( *p, it ) ) );
     p->activity.placement = here.getglobal( pnt );
     return 1;
 }
References _, Character::activity, add_msg(), Character::add_msg_if_player(), Character::assign_activity(), Character::cant_do_mounted(), choose_adjacent_highlight(), chop_moves(), debugmsg, Character::get_crafting_helpers(), get_map(), map::getglobal(), map::has_flag(), m_info, player_activity::placement, Creature::pos(), string_id< T >::str(), TFLAG_TREE, and item::typeId().
Referenced by Item_factory::init().
clear_rubble()
std::optional< int > iuse::clear_rubble (Character * p, item * it, const tripoint &)
Definition at line 2894 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action clear_rubble that requires character but no character is present",
                   it->typeId().str() );
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     std::vector<construction> const &cnstr = get_constructions();
     auto const build = std::find_if( cnstr.begin(), cnstr.end(), []( const construction & it ) {
         return it.str_id == construction_constr_clear_rubble;
     } );
     place_construction( { build->group } );
     return 0;
 }
References Character::cant_do_mounted(), debugmsg, get_constructions(), place_construction(), string_id< T >::str(), and item::typeId().
Referenced by Item_factory::init().
coin_flip()
std::optional< int > iuse::coin_flip (Character * p, item * it, const tripoint &)
Definition at line 8395 of file iuse.cpp.
 {
     p->add_msg_if_player( m_info, _( "You flip a %s." ), it->tname() );
     p->add_msg_if_player( m_info, one_in( 2 ) ? _( "Heads!" ) : _( "Tails!" ) );
     return 0;
 }
References _, Character::add_msg_if_player(), m_info, one_in(), and item::tname().
Referenced by Item_factory::init().
coke()
std::optional< int > iuse::coke (Character * p, item * , const tripoint &)
Strength reduces duration of coke
Definition at line 834 of file iuse.cpp.
 {
     p->add_msg_if_player( _( "You snort a bump of coke." ) );
     /** @EFFECT_STR reduces duration of coke */
     time_duration duration = 20_minutes - 1_seconds * p->str_cur + rng( 0_minutes, 1_minutes );
     if( p->has_trait( trait_TOLERANCE ) ) {
         duration -= 1_minutes; // Symmetry would cause problems :-/
     }
     if( p->has_trait( trait_LIGHTWEIGHT ) ) {
         duration += 2_minutes;
     }
     p->mod_hunger( -8 );
     p->add_effect( effect_high, duration );
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), effect_high, Character::has_trait(), Character::mod_hunger(), rng(), Character::str_cur, trait_LIGHTWEIGHT, and trait_TOLERANCE.
Referenced by Item_factory::init().
contacts()
std::optional<int> iuse::contacts (Character * , item * , const tripoint &)
craft()
std::optional< int > iuse::craft (Character * p, item * it, const tripoint &)
Definition at line 8329 of file iuse.cpp.
 {
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     it = wield_before_use( p, it, _( "Wield the %s and start working?" ) );
     if( !it ) {
         return std::nullopt;
     }
     const std::string craft_name = it->tname();
     if( !it->is_craft() ) {
         debugmsg( "Attempted to start working on non craft '%s.'  Aborting.", craft_name );
         return std::nullopt;
     }
     if( !p->can_continue_craft( *it ) ) {
         return std::nullopt;
     }
     const recipe &rec = it->get_making();
     if( !p->has_recipe( &rec ) ) {
         p->add_msg_player_or_npc(
             _( "You don't know the recipe for the %s and can't continue crafting." ),
             _( "<npcname> doesn't know the recipe for the %s and can't continue crafting." ),
             rec.result_name() );
         return 0;
     }
     p->add_msg_player_or_npc(
         pgettext( "in progress craft", "You start working on the %s." ),
         pgettext( "in progress craft", "<npcname> starts working on the %s." ), craft_name );
     item_location craft_loc = item_location( *p, it );
     p->assign_activity( craft_activity_actor( craft_loc, false ) );
     return 0;
 }
References _, Character::add_msg_player_or_npc(), Character::assign_activity(), Character::can_continue_craft(), Character::cant_do_mounted(), debugmsg, item::get_making(), Character::has_recipe(), item::is_craft(), pgettext, recipe::result_name(), item::tname(), and wield_before_use().
Referenced by Item_factory::init().
crowbar()
std::optional< int > iuse::crowbar (Character * p, item * it, const tripoint & pos)
Definition at line 2719 of file iuse.cpp.
 {
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     map &here = get_map();
     const std::function<bool( const tripoint & )> f =
     [&here, p]( const tripoint & pnt ) {
         if( pnt == p->pos() ) {
             return false;
         } else if( here.has_furn( pnt ) ) {
             return here.furn( pnt )->prying->valid();
         } else if( !here.ter( pnt )->is_null() ) {
             return here.ter( pnt )->prying->valid();
         }
         return false;
     };
     const std::optional<tripoint> pnt_ = ( pos != p->pos() ) ? pos : choose_adjacent_highlight(
             _( "Pry where?" ), _( "There is nothing to pry nearby." ), f, false );
     if( !pnt_ ) {
         return std::nullopt;
     }
     const tripoint &pnt = *pnt_;
     const pry_data *prying;
     if( here.has_furn( pnt ) ) {
         prying = &here.furn( pnt )->prying->prying_data();
     } else {
         prying = &here.ter( pnt )->prying->prying_data();
     }
     if( !f( pnt ) ) {
         if( pnt == p->pos() ) {
             if( it->typeId() == STATIC( itype_id( "hammer" ) ) ) {
                 p->add_msg_if_player( m_info, _( "You try to hit yourself with the hammer." ) );
                 p->add_msg_if_player( m_info, _( "But you can't touch this." ) );
             } else {
                 p->add_msg_if_player( m_info, _( "You attempt to pry open your wallet, "
                                                  "but alas.  You are just too miserly." ) );
             }
         } else {
             p->add_msg_if_player( m_info, _( "You can't pry that." ) );
         }
         return std::nullopt;
     }
     // previously iuse::hammer
     if( prying->prying_nails ) {
         p->assign_activity( prying_activity_actor( pnt, item_location{*p, it} ) );
         return std::nullopt;
     }
     // Doors need PRY 2 which is on a crowbar, crates need PRY 1 which is on a crowbar
     // & a claw hammer.
     // The iexamine function for crate supplies a hammer object.
     // So this stops the player (A)ctivating a Hammer with a Crowbar in their backpack
     // then managing to open a door.
     const int pry_level = it->get_quality( qual_PRY );
     if( pry_level < prying->prying_level ) {
         // This doesn't really make it clear to the player
         // why their attempt is failing.
         p->add_msg_if_player( _( "You can't get sufficient leverage to open that with your %1$s." ),
                               it->tname() );
         p->mod_moves( -50 ); // spend a few moves trying it.
         return std::nullopt;
     }
     p->assign_activity( prying_activity_actor( pnt, item_location{*p, it} ) );
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), Character::assign_activity(), Character::cant_do_mounted(), choose_adjacent_highlight(), map::furn(), get_map(), item::get_quality(), map::has_furn(), ter_t::is_null(), m_info, Creature::mod_moves(), Creature::pos(), math_opers::pos(), ter_t::prying, furn_t::prying, pry_data::prying_nails, qual_PRY, STATIC, map::ter(), item::tname(), and item::typeId().
Referenced by crowbar_weak(), hammer(), Item_factory::init(), and iexamine::locked_object().
crowbar_weak()
std::optional< int > iuse::crowbar_weak (Character * p, item * it, const tripoint & pos)
Definition at line 2714 of file iuse.cpp.
 {
     return iuse::crowbar( p, it, pos );
 }
References crowbar(), and math_opers::pos().
Referenced by Item_factory::init().
cut_log_into_planks()
void iuse::cut_log_into_planks (Character & p)
Definition at line 4479 of file iuse.cpp.
 {
     if( p.cant_do_mounted() ) {
         return;
     }
     const int moves = to_moves<int>( 20_minutes );
     p.add_msg_if_player( _( "You cut the log into planks." ) );
     p.assign_activity( chop_planks_activity_actor( moves ) );
     p.activity.placement = get_map().getglobal( p.pos() );
 }
References _, Character::activity, Character::add_msg_if_player(), Character::assign_activity(), Character::cant_do_mounted(), get_map(), map::getglobal(), player_activity::placement, and Creature::pos().
Referenced by construct::done_trunk_plank(), and lumber().
datura()
std::optional< int > iuse::datura (Character * p, item * it, const tripoint &)
Definition at line 988 of file iuse.cpp.
 {
     if( p->is_npc() ) {
         return std::nullopt;
     }
     p->add_effect( effect_datura, rng( 3_hours, 13_hours ) );
     p->add_msg_if_player( _( "You eat the datura seed." ) );
     if( p->has_trait( trait_SPIRITUAL ) ) {
         p->add_morale( MORALE_FOOD_GOOD, 36, 72, 2_hours, 1_hours, false, it->type );
     }
     return 1;
 }
References _, Creature::add_effect(), Character::add_morale(), Character::add_msg_if_player(), effect_datura, Character::has_trait(), Character::is_npc(), MORALE_FOOD_GOOD, rng(), trait_SPIRITUAL, and item::type.
Referenced by Item_factory::init().
dbg_lux_meter()
std::optional< int > iuse::dbg_lux_meter (Character * p, item * , const tripoint & pos)
Definition at line 7878 of file iuse.cpp.
 {
     map &here = get_map();
     const float incident_light = incident_sunlight( current_weather( here.getglobal( pos ) ),
                                  calendar::turn );
     const float nat_light = g->natural_light_level( pos.z );
     const float sunlight = sun_light_at( calendar::turn );
     const float sun_irrad = sun_irradiance( calendar::turn );
     const float incident_irrad = incident_sun_irradiance( current_weather( here.getglobal( pos ) ),
                                  calendar::turn );
     p->add_msg_if_player( m_neutral,
                           _( "Incident light: %.1f\nNatural light: %.1f\nSunlight: %.1f\nSun irradiance: %.1f\nIncident irradiance %.1f" ),
                           incident_light, nat_light, sunlight, sun_irrad, incident_irrad );
     return 0;
 }
References _, Character::add_msg_if_player(), current_weather(), g, get_map(), map::getglobal(), incident_sun_irradiance(), incident_sunlight(), m_neutral, math_opers::pos(), sun_irradiance(), sun_light_at(), and calendar::turn.
Referenced by Item_factory::init().
dig()
std::optional< int > iuse::dig (Character * p, item * it, const tripoint &)
Definition at line 2830 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action dig that requires character but no character is present",
                   it->typeId().str() );
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     std::vector<construction> const &cnstr = get_constructions();
     auto const build = std::find_if( cnstr.begin(), cnstr.end(), []( const construction & it ) {
         return it.str_id == construction_constr_pit;
     } );
     auto const build_shallow = std::find_if( cnstr.begin(), cnstr.end(), []( const construction & it ) {
         return it.str_id == construction_constr_pit_shallow;
     } );
     place_construction( { build->group, build_shallow->group } );
     return 0;
 }
References Character::cant_do_mounted(), debugmsg, get_constructions(), place_construction(), string_id< T >::str(), and item::typeId().
Referenced by construct::done_digormine_stair(), and Item_factory::init().
dig_channel()
std::optional< int > iuse::dig_channel (Character * p, item * it, const tripoint &)
Definition at line 2854 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action dig_channel that requires character but no character is present",
                   it->typeId().str() );
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     std::vector<construction> const &cnstr = get_constructions();
     auto const build = std::find_if( cnstr.begin(), cnstr.end(), []( const construction & it ) {
         return it.str_id == construction_constr_water_channel;
     } );
     place_construction( { build->group } );
     return 0;
 }
References Character::cant_do_mounted(), debugmsg, get_constructions(), place_construction(), string_id< T >::str(), and item::typeId().
Referenced by Item_factory::init().
directional_antenna()
std::optional< int > iuse::directional_antenna (Character * p, item * , const tripoint &)
Definition at line 2473 of file iuse.cpp.
 {
     // Find out if we have an active radio
     auto radios = p->cache_get_items_with( itype_radio_on );
     // If we don't wield the radio, also check on the ground
     if( radios.empty() ) {
         map_stack items = get_map().i_at( p->pos() );
         for( item &an_item : items ) {
             if( an_item.typeId() == itype_radio_on ) {
                 radios.push_back( &an_item );
             }
         }
     }
     if( radios.empty() ) {
         add_msg( m_info, _( "You must have an active radio to check for signal direction." ) );
         return std::nullopt;
     }
     const item radio = *radios.front();
     // Find the radio station it's tuned to (if any)
     const radio_tower_reference tref = overmap_buffer.find_radio_station( radio.frequency );
     if( !tref ) {
         p->add_msg_if_player( m_info, _( "You can't find the direction if your radio isn't tuned." ) );
         return std::nullopt;
     }
     // Report direction.
     const tripoint_abs_sm player_pos = p->global_sm_location();
     direction angle = direction_from( player_pos.xy(), tref.abs_sm_pos );
     add_msg( _( "The signal seems strongest to the %s." ), direction_name( angle ) );
     return 1;
 }
References _, radio_tower_reference::abs_sm_pos, add_msg(), Character::add_msg_if_player(), Character::cache_get_items_with(), direction_from(), direction_name(), overmapbuffer::find_radio_station(), get_map(), Creature::global_sm_location(), map::i_at(), itype_radio_on, m_info, overmap_buffer, Creature::pos(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by Item_factory::init().
directional_hologram()
std::optional< int > iuse::directional_hologram (Character * p, item * it, const tripoint &)
Definition at line 7916 of file iuse.cpp.
 {
     if( it->is_armor() &&  !p->is_worn( *it ) ) {
         p->add_msg_if_player( m_neutral, _( "You need to wear the %1$s before activating it." ),
                               it->tname() );
         return std::nullopt;
     }
     const std::optional<tripoint> posp = choose_adjacent( _( "Choose hologram direction." ) );
     if( !posp ) {
         return std::nullopt;
     }
     const tripoint delta = *posp - get_player_character().pos();
     monster *const hologram = g->place_critter_at( mon_hologram, *posp );
     if( !hologram ) {
         p->add_msg_if_player( m_info, _( "Can't create a hologram there." ) );
         return std::nullopt;
     }
     tripoint_abs_ms target = p->get_location() + delta * ( 4 * SEEX );
     hologram->friendly = -1;
     hologram->add_effect( effect_docile, 1_hours );
     hologram->wandf = -30;
     hologram->set_summon_time( 60_seconds );
     hologram->set_dest( target );
     p->mod_moves( -to_moves<int>( 1_seconds ) );
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), choose_adjacent(), effect_docile, monster::friendly, g, Creature::get_location(), get_player_character(), item::is_armor(), Character::is_worn(), m_info, m_neutral, Creature::mod_moves(), mon_hologram, Creature::pos(), SEEX, monster::set_dest(), Creature::set_summon_time(), item::tname(), and monster::wandf.
Referenced by Item_factory::init().
disassemble()
std::optional< int > iuse::disassemble (Character * p, item * it, const tripoint &)
Definition at line 8366 of file iuse.cpp.
 {
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     it = wield_before_use( p, it, _( "Wield the %s and start working?" ) );
     if( !it ) {
         return std::nullopt;
     }
     if( !p->has_item( *it ) ) {
         return std::nullopt;
     }
     p->disassemble( item_location( *p, it ), false );
     return 0;
 }
References _, Character::cant_do_mounted(), Character::disassemble(), visitable::has_item(), and wield_before_use().
Referenced by Item_factory::init().
dive_tank()
std::optional< int > iuse::dive_tank (Character * p, item * it, const tripoint &)
Definition at line 3861 of file iuse.cpp.
 {
     if( p && p->is_worn( *it ) ) {
         if( p->is_underwater() && p->oxygen < 10 ) {
             p->oxygen += 20;
         }
         if( one_in( 15 ) ) {
             p->add_msg_if_player( m_bad, _( "You take a deep breath from your %s." ), it->tname() );
         }
         if( it->ammo_remaining() == 0 ) {
             p->add_msg_if_player( m_bad, _( "Air in your %s runs out." ), it->tname() );
             it->erase_var( "overwrite_env_resist" );
             it->convert( *it->type->revert_to ).active = false;
         }
     } else { // not worn = off thanks to on-demand regulator
         it->erase_var( "overwrite_env_resist" );
         it->convert( *it->type->revert_to ).active = false;
     }
     return 1;
 }
References _, item::active, Character::add_msg_if_player(), item::ammo_remaining(), item::convert(), item::erase_var(), Creature::is_underwater(), Character::is_worn(), m_bad, one_in(), Character::oxygen, itype::revert_to, item::tname(), and item::type.
Referenced by Item_factory::init().
dive_tank_activate()
std::optional< int > iuse::dive_tank_activate (Character * p, item * it, const tripoint &)
Definition at line 3883 of file iuse.cpp.
 {
     if( it->ammo_remaining() == 0 ) {
         p->add_msg_if_player( _( "Your %s is empty." ), it->tname() );
     } else if( it->active ) { //off
         p->add_msg_if_player( _( "You turn off the regulator and close the air valve." ) );
         it->erase_var( "overwrite_env_resist" );
         it->convert( *it->type->revert_to ).active = false;
     } else { //on
         if( !p->is_worn( *it ) ) {
             p->add_msg_if_player( _( "You should wear it first." ) );
         } else {
             p->add_msg_if_player( _( "You turn on the regulator and open the air valve." ) );
             it->set_var( "overwrite_env_resist", it->get_base_env_resist_w_filter() );
             it->convert( itype_id( it->typeId().str() + "_on" ) ).active = true;
         }
     }
     return 1;
 }
References _, item::active, Character::add_msg_if_player(), item::ammo_remaining(), item::convert(), item::erase_var(), item::get_base_env_resist_w_filter(), Character::is_worn(), itype::revert_to, item::set_var(), string_id< T >::str(), item::tname(), item::type, and item::typeId().
Referenced by Item_factory::init().
dog_whistle()
std::optional< int > iuse::dog_whistle (Character * p, item * , const tripoint &)
Definition at line 4317 of file iuse.cpp.
 {
     if( !p->is_avatar() ) {
         return std::nullopt;
     }
     if( p->cant_do_underwater() ) {
         return std::nullopt;
     }
     p->add_msg_if_player( _( "You blow your dog whistle." ) );
     // Can the Character hear the dog whistle?
     auto hearing_check = [p]( const Character & who ) -> bool {
         return !who.is_deaf() && p->sees( who ) &&
         who.has_trait( STATIC( trait_id( "THRESH_LUPINE" ) ) );
     };
     for( const npc &subject : g->all_npcs() ) {
         if( !( one_in( 3 ) && hearing_check( subject ) ) ) {
             continue;
         }
         std::optional<translation> npc_message;
         if( p->attitude_to( subject ) == Creature::Attitude::HOSTILE ) {
             npc_message = SNIPPET.random_from_category( "dogwhistle_message_npc_hostile" );
         } else {
             npc_message = SNIPPET.random_from_category( "dogwhistle_message_npc_not_hostile" );
         }
         if( npc_message ) {
             subject.say( npc_message.value().translated() );
         }
     }
     if( hearing_check( *p ) && one_in( 3 ) ) {
         std::optional<translation> your_message = SNIPPET.random_from_category( "dogwhistle_message_you" );
         if( your_message ) {
             p->add_msg_if_player( m_info, your_message.value().translated() );
         }
     }
     for( monster &critter : g->all_monsters() ) {
         if( critter.friendly != 0 && critter.has_flag( mon_flag_DOGFOOD ) ) {
             bool u_see = get_player_view().sees( critter );
             if( critter.has_effect( effect_docile ) ) {
                 if( u_see ) {
                     p->add_msg_if_player( _( "Your %s looks ready to attack." ), critter.name() );
                 }
                 critter.remove_effect( effect_docile );
             } else {
                 if( u_see ) {
                     p->add_msg_if_player( _( "Your %s goes docile." ), critter.name() );
                 }
                 critter.add_effect( effect_docile, 1_turns, true );
             }
         }
     }
     return 1;
 }
References _, Character::add_msg_if_player(), Character::attitude_to(), Creature::cant_do_underwater(), effect_docile, g, get_player_view(), Creature::HOSTILE, Creature::is_avatar(), m_info, mon_flag_DOGFOOD, one_in(), snippet_library::random_from_category(), Character::sees(), viewer::sees(), SNIPPET, and STATIC.
Referenced by Item_factory::init().
ebookread()
std::optional< int > iuse::ebookread (Character * p, item * it, const tripoint &)
Definition at line 8707 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action ebookread that requires character but no character is present",
                   it->typeId().str() );
         return std::nullopt;
     }
     if( !it->is_ebook_storage() ) {
         debugmsg( "EBOOKREAD iuse called on item without ebook type pocket" );
         return std::nullopt;
     }
     if( p->is_npc() ) {
         return std::nullopt;
     }
     if( p->is_underwater() ) {
         p->add_msg_if_player( m_info, _( "Unfortunately your device is not waterproof." ) );
         return std::nullopt;
     }
     if( p->has_flag( json_flag_HYPEROPIC ) && !p->worn_with_flag( flag_FIX_FARSIGHT ) &&
         !p->has_effect( effect_contacts ) && !p->has_effect( effect_transition_contacts ) &&
         !p->has_flag( json_flag_ENHANCED_VISION ) ) {
         p->add_msg_if_player( m_info,
                               _( "You'll need to put on reading glasses before you can see the screen." ) );
         return std::nullopt;
     }
     // Only turn on the eBook light, if it's too dark to read
     if( p->fine_detail_vision_mod() > 4 && !it->active && it->is_transformable() ) {
         const use_function *readinglight = it->type->get_use( "transform" );
         if( readinglight ) {
             readinglight->call( p, *it, p->pos() );
         }
     }
     item_location ereader = item_location( *p, it );
     item_location book = game_menus::inv::ebookread( *p, ereader );
     if( !book ) {
         return std::nullopt;
     }
     p->as_avatar()->read( book, ereader );
     return std::nullopt;
 }
References _, item::active, Character::add_msg_if_player(), Creature::as_avatar(), use_function::call(), debugmsg, game_menus::inv::ebookread(), effect_contacts, effect_transition_contacts, Character::fine_detail_vision_mod(), flag_FIX_FARSIGHT, itype::get_use(), Creature::has_effect(), Character::has_flag(), item::is_ebook_storage(), Character::is_npc(), item::is_transformable(), Creature::is_underwater(), json_flag_ENHANCED_VISION, json_flag_HYPEROPIC, m_info, Creature::pos(), avatar::read(), string_id< T >::str(), item::type, item::typeId(), and Character::worn_with_flag().
Referenced by Item_factory::init().
ebooksave()
std::optional< int > iuse::ebooksave (Character * p, item * it, const tripoint &)
Definition at line 8665 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action ebooksave that requires character but no character is present",
                   it->typeId().str() );
         return std::nullopt;
     }
     if( !it->is_ebook_storage() ) {
         debugmsg( "EBOOKSAVE iuse called on item without ebook type pocket" );
         return std::nullopt;
     }
     if( p->is_npc() ) {
         return std::nullopt;
     }
     if( p->is_underwater() ) {
         p->add_msg_if_player( m_info, _( "Unfortunately your device is not waterproof." ) );
         return std::nullopt;
     }
     if( p->has_flag( json_flag_HYPEROPIC ) && !p->worn_with_flag( flag_FIX_FARSIGHT ) &&
         !p->has_effect( effect_contacts ) && !p->has_effect( effect_transition_contacts ) &&
         !p->has_flag( json_flag_ENHANCED_VISION ) ) {
         p->add_msg_if_player( m_info,
                               _( "You'll need to put on reading glasses before you can see the screen." ) );
         return std::nullopt;
     }
     item_location ereader = item_location( *p, it );
     const drop_locations to_scan = game_menus::inv::ebooksave( *p, ereader );
     if( to_scan.empty() ) {
         return std::nullopt;
     }
     std::vector<item_location> books;
     for( const auto &pair : to_scan ) {
         books.push_back( pair.first );
     }
     p->assign_activity( ebooksave_activity_actor( books, ereader ) );
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), Character::assign_activity(), debugmsg, game_menus::inv::ebooksave(), effect_contacts, effect_transition_contacts, flag_FIX_FARSIGHT, Creature::has_effect(), Character::has_flag(), item::is_ebook_storage(), Character::is_npc(), Creature::is_underwater(), json_flag_ENHANCED_VISION, json_flag_HYPEROPIC, m_info, string_id< T >::str(), item::typeId(), and Character::worn_with_flag().
Referenced by Item_factory::init().
ecig()
std::optional< int > iuse::ecig (Character * p, item * it, const tripoint &)
Definition at line 598 of file iuse.cpp.
 {
     if( it->typeId() == itype_ecig ) {
         p->add_msg_if_player( m_neutral, _( "You take a puff from your electronic cigarette." ) );
     } else if( it->typeId() == itype_advanced_ecig ) {
         if( p->has_charges( itype_nicotine_liquid, 1 ) ) {
             p->add_msg_if_player( m_neutral,
                                   _( "You inhale some vapor from your advanced electronic cigarette." ) );
             p->use_charges( itype_nicotine_liquid, 1 );
             item dummy_ecig = item( "ecig", calendar::turn );
             p->consume_effects( dummy_ecig );
         } else {
             p->add_msg_if_player( m_info, _( "You don't have any nicotine liquid!" ) );
             return std::nullopt;
         }
     }
     p->mod_thirst( 1 );
     p->mod_hunger( -1 );
     p->add_effect( effect_cig, 10_minutes );
     if( p->get_effect_dur( effect_cig ) > 10_minutes * ( p->addiction_level(
                 addiction_nicotine ) + 1 ) ) {
         p->add_msg_if_player( m_bad, _( "Ugh, too much nicotine you feel nasty." ) );
     }
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), Character::addiction_level(), addiction_nicotine, Character::consume_effects(), effect_cig, Creature::get_effect_dur(), Character::has_charges(), item, itype_advanced_ecig, itype_ecig, itype_nicotine_liquid, m_bad, m_info, m_neutral, Character::mod_hunger(), Character::mod_thirst(), calendar::turn, item::typeId(), and Character::use_charges().
Referenced by Item_factory::init().
ehandcuffs()
std::optional< int > iuse::ehandcuffs (Character * , item * it, const tripoint &)
Definition at line 6884 of file iuse.cpp.
 {
     if( it->active ) {
         add_msg( _( "The %s are clamped tightly on your wrists.  You can't take them off." ),
                  it->tname() );
     } else {
         add_msg( _( "The %s have discharged and can be taken off." ), it->tname() );
     }
     return 1;
 }
References _, item::active, add_msg(), and item::tname().
Referenced by Item_factory::init().
ehandcuffs_tick()
std::optional< int > iuse::ehandcuffs_tick (Character * p, item * it, const tripoint & pos)
Definition at line 6802 of file iuse.cpp.
 {
     if( get_map().has_flag( ter_furn_flag::TFLAG_SWIMMABLE, pos.xy() ) ) {
         it->unset_flag( flag_NO_UNWIELD );
         it->ammo_unset();
         it->active = false;
         add_msg( m_good, _( "%s automatically turned off!" ), it->tname() );
         return 1;
     }
     if( !p ) {
         // Active but not in use. Deactivate
         sounds::sound( pos, 2, sounds::sound_t::combat, "Click.", true, "tools", "handcuffs" );
         it->unset_flag( flag_NO_UNWIELD );
         it->active = false;
         return 1;
     }
     if( it->charges == 0 ) {
         sounds::sound( pos, 2, sounds::sound_t::combat, "Click.", true, "tools", "handcuffs" );
         it->unset_flag( flag_NO_UNWIELD );
         it->active = false;
         if( p ) {
             add_msg( m_good, _( "%s on your wrists opened!" ), it->tname() );
         }
         return 1;
     }
     if( p->has_active_bionic( bio_shock ) && p->get_power_level() >= bio_shock->power_trigger &&
         one_in( 5 ) ) {
         p->mod_power_level( -bio_shock->power_trigger );
         it->unset_flag( flag_NO_UNWIELD );
         it->charges = 0;
         it->active = false;
         add_msg( m_good, _( "The %s crackle with electricity from your bionic, then come off your hands!" ),
                  it->tname() );
         return 1;
     }
     if( calendar::once_every( 1_minutes ) ) {
         sounds::sound( pos, 10, sounds::sound_t::alarm, _( "a police siren, whoop WHOOP." ), true,
                        "environment", "police_siren" );
     }
     const point p2( it->get_var( "HANDCUFFS_X", 0 ), it->get_var( "HANDCUFFS_Y", 0 ) );
     if( ( it->ammo_remaining() > it->type->maximum_charges() - 1000 ) && ( p2.x != pos.x ||
             p2.y != pos.y ) ) {
         if( p->is_elec_immune() ) {
             if( one_in( 10 ) ) {
                 add_msg( m_good, _( "The cuffs try to shock you, but you're protected from electricity." ) );
             }
         } else {
             add_msg( m_bad, _( "Ouch, the cuffs shock you!" ) );
             p->apply_damage( nullptr, bodypart_id( "arm_l" ), rng( 0, 2 ) );
             p->apply_damage( nullptr, bodypart_id( "arm_r" ), rng( 0, 2 ) );
             p->mod_pain( rng( 2, 5 ) );
         }
         it->charges -= 50;
         if( it->charges < 1 ) {
             it->charges = 1;
         }
         it->set_var( "HANDCUFFS_X", pos.x );
         it->set_var( "HANDCUFFS_Y", pos.y );
         return 1;
     }
     return 1;
 }
References _, item::active, add_msg(), sounds::alarm, item::ammo_remaining(), item::ammo_unset(), Character::apply_damage(), bio_shock, item::charges, sounds::combat, flag_NO_UNWIELD, get_map(), Character::get_power_level(), item::get_var(), Character::has_active_bionic(), item::has_flag(), Character::is_elec_immune(), m_bad, m_good, itype::maximum_charges(), Character::mod_pain(), Character::mod_power_level(), calendar::once_every(), one_in(), math_opers::pos(), bionic_data::power_trigger, rng(), item::set_var(), sounds::sound(), TFLAG_SWIMMABLE, item::tname(), item::type, item::unset_flag(), point::x, and point::y.
Referenced by Item_factory::init().
einktabletpc()
std::optional< int > iuse::einktabletpc (Character * p, item * it, const tripoint &)
Definition at line 5497 of file iuse.cpp.
 {
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     } else if( !p->is_npc() ) {
         enum {
             ei_invalid, ei_photo, ei_music, ei_recipe, ei_uploaded_photos, ei_monsters, ei_download,
         };
         if( p->cant_do_underwater() ) {
             return std::nullopt;
         }
         if( p->has_trait( trait_ILLITERATE ) ) {
             p->add_msg_if_player( m_info, _( "You can't read a computer screen." ) );
             return std::nullopt;
         }
         if( p->has_flag( json_flag_HYPEROPIC ) && !p->worn_with_flag( flag_FIX_FARSIGHT ) &&
             !p->has_effect( effect_contacts ) && !p->has_effect( effect_transition_contacts ) &&
             !p->has_flag( json_flag_ENHANCED_VISION ) ) {
             p->add_msg_if_player( m_info,
                                   _( "You'll need to put on reading glasses before you can see the screen." ) );
             return std::nullopt;
         }
         if( !it->active ) {
             it->erase_var( "EIPC_MUSIC_ON" );
         }
         uilist amenu;
         amenu.text = _( "Choose menu option:" );
         const int photos = it->get_var( "EIPC_PHOTOS", 0 );
         if( photos > 0 ) {
             amenu.addentry( ei_photo, true, 'p', _( "Unsorted photos [%d]" ), photos );
         } else {
             amenu.addentry( ei_photo, false, 'p', _( "No photos on device" ) );
         }
         const int songs = it->get_var( "EIPC_MUSIC", 0 );
         if( songs > 0 ) {
             if( it->has_var( "EIPC_MUSIC_ON" ) ) {
                 amenu.addentry( ei_music, true, 'm', _( "Turn music off" ) );
             } else {
                 amenu.addentry( ei_music, true, 'm', _( "Turn music on [%d]" ), songs );
             }
         } else {
             amenu.addentry( ei_music, false, 'm', _( "No music on device" ) );
         }
         if( !it->get_saved_recipes().empty() ) {
             amenu.addentry( ei_recipe, true, 'r', _( "List stored recipes" ) );
         }
         if( !it->get_var( "EIPC_EXTENDED_PHOTOS" ).empty() ) {
             amenu.addentry( ei_uploaded_photos, true, 'l', _( "Your photos" ) );
         }
         if( !it->get_var( "EINK_MONSTER_PHOTOS" ).empty() ) {
             amenu.addentry( ei_monsters, true, 'y', _( "Your collection of monsters" ) );
         } else {
             amenu.addentry( ei_monsters, false, 'y', _( "Collection of monsters is empty" ) );
         }
         amenu.addentry( ei_download, true, 'w', _( "Download data from memory cards" ) );
         amenu.query();
         const int choice = amenu.ret;
         if( ei_photo == choice ) {
             const int photos = it->get_var( "EIPC_PHOTOS", 0 );
             const int viewed = std::min( photos, static_cast<int>( rng( 10, 30 ) ) );
             const int count = photos - viewed;
             if( count == 0 ) {
                 it->erase_var( "EIPC_PHOTOS" );
             } else {
                 it->set_var( "EIPC_PHOTOS", count );
             }
             p->mod_moves( -to_moves<int>( rng( 3_seconds, 7_seconds ) ) );
             if( p->has_trait( trait_PSYCHOPATH ) ) {
                 p->add_msg_if_player( m_info, _( "Wasted time.  These pictures do not provoke your senses." ) );
             } else {
                 p->add_morale( MORALE_PHOTOS, rng( 15, 30 ), 100 );
                 p->add_msg_if_player( m_good, "%s",
                                       SNIPPET.random_from_category( "examine_photo_msg" ).value_or( translation() ) );
             }
             return 1;
         }
         if( ei_music == choice ) {
             p->mod_moves( -to_moves<int>( 1_seconds ) * 0.3 );
             // Turn on the screen before playing musics
             if( !it->active ) {
                 if( it->is_transformable() ) {
                     const use_function *readinglight = it->type->get_use( "transform" );
                     if( readinglight ) {
                         readinglight->call( p, *it, p->pos() );
                     }
                 }
                 it->activate();
             }
             // If transformable we use transform action to turn off the device
             else if( !it->is_transformable() ) {
                 it->deactivate();
             }
             if( it->has_var( "EIPC_MUSIC_ON" ) ) {
                 it->erase_var( "EIPC_MUSIC_ON" );
                 p->add_msg_if_player( m_info, _( "You turned off the music on your %s." ), it->tname() );
             } else {
                 it->set_var( "EIPC_MUSIC_ON", "1" );
                 p->add_msg_if_player( m_info, _( "You turned on the music on your %s." ), it->tname() );
             }
             return 1;
         }
         if( ei_recipe == choice ) {
             p->mod_moves( -to_moves<int>( 1_seconds ) * 0.5 );
             uilist rmenu;
             for( const recipe_id &rid : it->get_saved_recipes() ) {
                 rmenu.addentry( 0, true, 0, rid->result_name( /* decorated = */ true ) );
             }
             rmenu.text = _( "List recipes:" );
             rmenu.query();
             return 1;
         }
         if( ei_uploaded_photos == choice ) {
             show_photo_selection( *p, *it, "EIPC_EXTENDED_PHOTOS" );
             return 1;
         }
         if( ei_monsters == choice ) {
             uilist pmenu;
             pmenu.text = _( "Your collection of monsters:" );
             std::vector<mtype_id> monster_photos;
             std::istringstream f( it->get_var( "EINK_MONSTER_PHOTOS" ) );
             std::string s;
             int k = 0;
             while( getline( f, s, ',' ) ) {
                 if( s.empty() ) {
                     continue;
                 }
                 monster_photos.emplace_back( s );
                 std::string menu_str;
                 const monster dummy( monster_photos.back() );
                 menu_str = dummy.name();
                 getline( f, s, ',' );
                 const int quality = get_quality_from_string( s );
                 menu_str += " [" + photo_quality_name( quality ) + "]";
                 pmenu.addentry( k++, true, -1, menu_str.c_str() );
             }
             int choice;
             do {
                 pmenu.query();
                 choice = pmenu.ret;
                 if( choice < 0 ) {
                     break;
                 }
                 const monster dummy( monster_photos[choice] );
                 popup( dummy.type->get_description() );
             } while( true );
             return 1;
         }
         if( ei_download == choice ) {
             if( !p->has_item( *it ) ) {
                 p->add_msg_if_player( m_info, _( "You don't have that item!" ) );
                 return std::nullopt; // need posession of reader item for item_location to work right
             }
             if( !p->is_avatar() ) {
                 return std::nullopt; // npc triggered iuse?
             }
             inventory_filter_preset preset( []( const item_location & it ) {
                 return it->has_flag( flag_MC_HAS_DATA ) || it->type->memory_card_data;
             } );
             inventory_multiselector inv_s( *p, preset );
             inv_s.set_title( _( "Choose memory cards to download data from:" ) );
             inv_s.set_display_stats( true );
             inv_s.add_character_items( *p );
             inv_s.add_nearby_items( 1 );
             const std::list<std::pair<item_location, int>> locs = inv_s.execute();
             if( locs.empty() ) {
                 p->add_msg_if_player( m_info, _( "Nevermind." ) );
                 return std::nullopt;
             }
             std::vector<item_location> targets;
             for( const auto& [item_loc, count] : locs ) {
                 targets.emplace_back( item_loc );
             }
             const item_location reader( *p, it );
             const data_handling_activity_actor actor( reader, targets );
             p->assign_activity( player_activity( actor ) );
         }
     }
     return std::nullopt;
 }
References _, item::activate(), item::active, Character::add_morale(), Character::add_msg_if_player(), uilist::addentry(), Character::assign_activity(), use_function::call(), Character::cant_do_mounted(), Creature::cant_do_underwater(), item::count(), item::deactivate(), effect_contacts, effect_transition_contacts, item::erase_var(), flag_FIX_FARSIGHT, flag_MC_HAS_DATA, mtype::get_description(), get_quality_from_string(), item::get_saved_recipes(), itype::get_use(), item::get_var(), Creature::has_effect(), item::has_flag(), Character::has_flag(), visitable::has_item(), Character::has_trait(), item::has_var(), Creature::is_avatar(), Character::is_npc(), item::is_transformable(), json_flag_ENHANCED_VISION, json_flag_HYPEROPIC, m_good, m_info, itype::memory_card_data, min(), Creature::mod_moves(), MORALE_PHOTOS, monster::name(), photo_quality_name(), popup(), Creature::pos(), uilist::query(), snippet_library::random_from_category(), uilist::ret, rng(), item::set_var(), show_photo_selection(), SNIPPET, uilist::text, item::tname(), trait_ILLITERATE, trait_PSYCHOPATH, item::type, monster::type, and Character::worn_with_flag().
Referenced by Item_factory::init().
electricstorage()
std::optional< int > iuse::electricstorage (Character * p, item * it, const tripoint &)
Definition at line 8537 of file iuse.cpp.
 {
     // From item processing
     if( !p ) {
         debugmsg( "%s called action electricstorage that requires character but no character is present",
                   it->typeId().str() );
         return std::nullopt;
     }
     if( p->is_npc() ) {
         return std::nullopt;
     }
     if( p->is_underwater() ) {
         p->add_msg_if_player( m_info, _( "Unfortunately your device is not waterproof." ) );
         return std::nullopt;
     }
     if( !it->is_ebook_storage() ) {
         debugmsg( "ELECTRICSTORAGE iuse called on item without ebook type pocket" );
         return std::nullopt;
     }
     if( p->has_flag( json_flag_HYPEROPIC ) && !p->worn_with_flag( flag_FIX_FARSIGHT ) &&
         !p->has_effect( effect_contacts ) && !p->has_effect( effect_transition_contacts ) &&
         !p->has_flag( json_flag_ENHANCED_VISION ) ) {
         p->add_msg_if_player( m_info,
                               _( "You'll need to put on reading glasses before you can see the screen." ) );
         return std::nullopt;
     }
     auto filter = [it]( const item & itm ) {
         return !itm.is_broken() &&
                &itm != it &&
                itm.has_pocket_type( pocket_type::EBOOK );
     };
     item_location storage_card = game_menus::inv::titled_filter_menu(
                                      filter, *p->as_avatar(), _( "Use what storage device?" ),
                                      -1, _( "You don't have any empty book storage devices." ) );
     if( !storage_card ) {
         return std::nullopt;
     }
     // list of books of from_it that are not in to_it
     auto book_difference = []( const item & from_it, const item & to_it ) -> std::vector<const item *> {
         std::set<itype_id> existing_ebooks;
         for( const item *ebook : to_it.ebooks() )
         {
             if( !ebook->is_book() ) {
                 debugmsg( "ebook type pocket contains non-book item %s", ebook->typeId().str() );
                 continue;
             }
             existing_ebooks.insert( ebook->typeId() );
         }
         std::vector<const item *> ebooks;
         for( const item *ebook : from_it.ebooks() )
         {
             if( !ebook->is_book() ) {
                 debugmsg( "ebook type pocket contains non-book item %s", ebook->typeId().str() );
                 continue;
             }
             if( existing_ebooks.count( ebook->typeId() ) ) {
                 continue;
             }
             ebooks.emplace_back( ebook );
         }
         return ebooks;
     };
     std::vector<const item *> to_storage = book_difference( *it, *storage_card );
     std::vector<const item *> to_device = book_difference( *storage_card, *it );
     uilist smenu;
     smenu.text = _( "What to do with your storage devices:" );
     smenu.addentry( 1, !to_device.empty(), 't', _( "Copy to device from the card" ) );
     smenu.addentry( 2, !to_storage.empty(), 'f', _( "Copy from device to the card" ) );
     smenu.addentry( 3, !storage_card->ebooks().empty(), 'v', _( "View books in the card" ) );
     smenu.query();
     // were any books moved to or from the device
     int books_moved = 0;
     auto move_books = [&books_moved]( const std::vector<const item *> &fromset, item & toit ) -> void {
         books_moved = fromset.size();
         for( const item *ebook : fromset )
         {
             toit.put_in( *ebook, pocket_type::EBOOK );
         }
     };
     if( smenu.ret == 1 ) {
         // to device
         move_books( to_device, *it );
     } else if( smenu.ret == 2 ) {
         // from device
         move_books( to_storage, *storage_card );
     } else if( smenu.ret == 3 ) {
         game_menus::inv::ebookread( *p, storage_card );
         return std::nullopt;
     } else {
         return std::nullopt;
     }
     if( books_moved > 0 ) {
         p->mod_moves( -to_moves<int>( 2_seconds ) );
         if( smenu.ret == 1 ) {
             p->add_msg_if_player( m_info,
                                   n_gettext( "Copied one book to the device.",
                                              "Copied %1$s books to the device.", books_moved ),
                                   books_moved );
         } else if( smenu.ret == 2 ) {
             p->add_msg_if_player( m_info,
                                   n_gettext( "Copied one book to the %2$s.",
                                              "Copied %1$s books to the %2$s.", books_moved ),
                                   books_moved, storage_card->tname() );
         }
     }
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), uilist::addentry(), Creature::as_avatar(), debugmsg, EBOOK, game_menus::inv::ebookread(), item::ebooks(), effect_contacts, effect_transition_contacts, filter, flag_FIX_FARSIGHT, Creature::has_effect(), Character::has_flag(), item::has_pocket_type(), item::is_ebook_storage(), Character::is_npc(), Creature::is_underwater(), json_flag_ENHANCED_VISION, json_flag_HYPEROPIC, m_info, Creature::mod_moves(), n_gettext, uilist::query(), uilist::ret, string_id< T >::str(), uilist::text, game_menus::inv::titled_filter_menu(), item::tname(), item::typeId(), and Character::worn_with_flag().
Referenced by Item_factory::init().
emf_passive_on()
std::optional< int > iuse::emf_passive_on (Character * , item * , const tripoint & pos)
Definition at line 2638 of file iuse.cpp.
 {
     // need to calculate distance to closest electrical thing
     // set distance as farther than the radius
     const int max = 10;
     int distance = max + 1;
     creature_tracker &creatures = get_creature_tracker();
     map &here = get_map();
     // can't get a reading during a portal storm
     if( get_weather().weather_id == weather_portal_storm ) {
         sounds::sound( pos, 6, sounds::sound_t::alarm, _( "BEEEEE-CHHHHHHH-eeEEEEEEE-CHHHHHHHHHHHH" ), true,
                        "tool", "emf_detector" );
         // skip continuing to check for locations
         return 1;
     }
     for( const tripoint &loc : closest_points_first( pos, max ) ) {
         const Creature *critter = creatures.creature_at( loc );
         // if the creature exists and is either a robot or electric
         bool found = critter != nullptr && critter->is_electrical();
         // check for an electrical field
         if( !found ) {
             for( const auto &fd : here.field_at( loc ) ) {
                 if( fd.first->has_elec ) {
                     found = true;
                     break;
                 }
             }
         }
         // if an electrical field or creature is nearby
         if( found ) {
             distance = rl_dist( pos, loc );
             if( distance <= 3 ) {
                 sounds::sound( pos, 4, sounds::sound_t::alarm, _( "BEEEEEEP BEEEEEEP" ), true, "tool",
                                "emf_detector" );
             } else if( distance <= 7 ) {
                 sounds::sound( pos, 3, sounds::sound_t::alarm, _( "BEEP BEEP" ), true, "tool",
                                "emf_detector" );
             } else if( distance <= 10 ) {
                 sounds::sound( pos, 2, sounds::sound_t::alarm, _( "beep beep" ), true, "tool",
                                "emf_detector" );
             }
             // skip continuing to check for locations
             return 1;
         }
     }
     return 1;
 }
References _, sounds::alarm, closest_points_first(), creature_tracker::creature_at(), map::field_at(), get_creature_tracker(), get_map(), get_weather(), Creature::is_electrical(), max(), math_opers::pos(), rl_dist(), sounds::sound(), and weather_portal_storm.
Referenced by Item_factory::init().
epic_music()
std::optional< int > iuse::epic_music (Character * p, item * it, const tripoint & pos)
Definition at line 5485 of file iuse.cpp.
 {
     if( !it->get_var( "EIPC_MUSIC_ON" ).empty() &&
         it->ammo_sufficient( p ) ) {
         //the more varied music, the better max mood.
         const int songs = it->get_var( "EIPC_MUSIC", 0 );
         play_music( p, pos, 8, std::min( 25, songs ) );
     }
     return std::nullopt;
 }
References item::ammo_sufficient(), item::get_var(), min(), play_music(), and math_opers::pos().
Referenced by Item_factory::init().
extinguisher()
std::optional< int > iuse::extinguisher (Character * p, item * it, const tripoint &)
Definition at line 1918 of file iuse.cpp.
 {
     if( !it->ammo_sufficient( p ) ) {
         return std::nullopt;
     }
     // If anyone other than the player wants to use one of these,
     // they're going to need to figure out how to aim it.
     const std::optional<tripoint> dest_ = choose_adjacent( _( "Spray where?" ) );
     if( !dest_ ) {
         return std::nullopt;
     }
     tripoint dest = *dest_;
     p->mod_moves( -to_moves<int>( 2_seconds ) );
     map &here = get_map();
     // Reduce the strength of fire (if any) in the target tile.
     here.add_field( dest, fd_extinguisher, 3, 10_turns );
     // Also spray monsters in that tile.
     if( monster *const mon_ptr = get_creature_tracker().creature_at<monster>( dest, true ) ) {
         monster &critter = *mon_ptr;
         critter.mod_moves( -to_moves<int>( 2_seconds ) );
         bool blind = false;
         if( one_in( 2 ) && critter.has_flag( mon_flag_SEES ) ) {
             blind = true;
             critter.add_effect( effect_blind, rng( 1_minutes, 2_minutes ) );
         }
         viewer &player_view = get_player_view();
         if( player_view.sees( critter ) ) {
             p->add_msg_if_player( _( "The %s is sprayed!" ), critter.name() );
             if( blind ) {
                 p->add_msg_if_player( _( "The %s looks blinded." ), critter.name() );
             }
         }
         if( critter.made_of( phase_id::LIQUID ) ) {
             if( player_view.sees( critter ) ) {
                 p->add_msg_if_player( _( "The %s is frozen!" ), critter.name() );
             }
             critter.apply_damage( p, bodypart_id( "torso" ), rng( 20, 60 ) );
             critter.set_speed_base( critter.get_speed_base() / 2 );
         }
     }
     // Slightly reduce the strength of fire immediately behind the target tile.
     if( here.passable( dest ) ) {
         dest.x += ( dest.x - p->posx() );
         dest.y += ( dest.y - p->posy() );
         here.mod_field_intensity( dest, fd_fire, std::min( 0 - rng( 0, 1 ) + rng( 0, 1 ), 0 ) );
     }
     return 1;
 }
References _, Creature::add_effect(), map::add_field(), Character::add_msg_if_player(), item::ammo_sufficient(), monster::apply_damage(), choose_adjacent(), effect_blind, fd_extinguisher, fd_fire, get_creature_tracker(), get_map(), get_player_view(), Creature::get_speed_base(), monster::has_flag(), LIQUID, monster::made_of(), min(), map::mod_field_intensity(), Creature::mod_moves(), mon_flag_SEES, monster::name(), one_in(), map::passable(), Creature::posx(), Creature::posy(), rng(), viewer::sees(), Creature::set_speed_base(), tripoint::x, and tripoint::y.
Referenced by Item_factory::init().
eyedrops()
std::optional< int > iuse::eyedrops (Character * p, item * it, const tripoint &)
Definition at line 647 of file iuse.cpp.
 {
     if( p->cant_do_underwater() ) {
         return std::nullopt;
     }
     if( !it->ammo_sufficient( p ) ) {
         p->add_msg_if_player( _( "You're out of %s." ), it->tname() );
         return std::nullopt;
     }
     p->add_msg_if_player( _( "You use your %s." ), it->tname() );
     p->mod_moves( -to_moves<int>( 10_seconds ) );
     if( p->has_effect( effect_boomered ) ) {
         p->remove_effect( effect_boomered );
         p->add_msg_if_player( m_good, _( "You wash the slime from your eyes." ) );
     }
     return 1;
 }
References _, Character::add_msg_if_player(), item::ammo_sufficient(), Creature::cant_do_underwater(), effect_boomered, Creature::has_effect(), m_good, Creature::mod_moves(), Creature::remove_effect(), and item::tname().
Referenced by Item_factory::init().
fill_pit()
std::optional< int > iuse::fill_pit (Character * p, item * it, const tripoint &)
Definition at line 2874 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action fill_pit that requires character but no character is present",
                   it->typeId().str() );
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     std::vector<construction> const &cnstr = get_constructions();
     auto const build = std::find_if( cnstr.begin(), cnstr.end(), []( const construction & it ) {
         return it.str_id == construction_constr_fill_pit;
     } );
     place_construction( { build->group } );
     return 0;
 }
References Character::cant_do_mounted(), debugmsg, get_constructions(), place_construction(), string_id< T >::str(), and item::typeId().
Referenced by Item_factory::init().
firecracker()
std::optional< int > iuse::firecracker (Character * p, item * it, const tripoint &)
Definition at line 3528 of file iuse.cpp.
 {
     if( p->cant_do_underwater() ) {
         return std::nullopt;
     }
     if( !p->use_charges_if_avail( itype_fire, 1 ) ) {
         p->add_msg_if_player( m_info, _( "You need a source of fire!" ) );
         return std::nullopt;
     }
     p->add_msg_if_player( _( "You light the firecracker." ) );
     it->convert( itype_firecracker_act, p );
     it->countdown_point = calendar::turn + 2_seconds;
     it->active = true;
     return 1;
 }
References _, item::active, Character::add_msg_if_player(), Creature::cant_do_underwater(), item::convert(), item::countdown_point, itype_fire, itype_firecracker_act, m_info, calendar::turn, and Character::use_charges_if_avail().
Referenced by Item_factory::init().
firecracker_pack()
std::optional< int > iuse::firecracker_pack (Character * p, item * it, const tripoint &)
Definition at line 3491 of file iuse.cpp.
 {
     if( p->cant_do_underwater() ) {
         return std::nullopt;
     }
     if( !p->has_charges( itype_fire, 1 ) ) {
         p->add_msg_if_player( m_info, _( "You need a source of fire!" ) );
         return std::nullopt;
     }
     p->add_msg_if_player( _( "You light the pack of firecrackers." ) );
     it->convert( itype_firecracker_pack_act, p );
     it->countdown_point = calendar::turn + 27_seconds;
     it->set_age( 0_turns );
     it->active = true;
     return 0; // don't use any charges at all. it has became a new item
 }
References _, item::active, Character::add_msg_if_player(), Creature::cant_do_underwater(), item::convert(), item::countdown_point, Character::has_charges(), itype_fire, itype_firecracker_pack_act, m_info, item::set_age(), and calendar::turn.
Referenced by Item_factory::init().
firecracker_pack_act()
std::optional< int > iuse::firecracker_pack_act (Character * , item * it, const tripoint & pos)
Definition at line 3508 of file iuse.cpp.
 {
     // Two seconds of lit fuse burning
     // Followed by random number of explosions (4-6) per turn until 25 epxlosions have happened
     // Finally item despawns since countdown has ended
     if( it->age() < 2_seconds ) {
         sounds::sound( pos, 0, sounds::sound_t::alarm, _( "ssss" ), true, "misc", "lit_fuse" );
     } else {
         // Time left to countdown_point is used to track of number of explosions
         int explosions = rng( 4, 6 );
         int i = 0;
         explosions = std::min( explosions, to_seconds<int>( it->countdown_point - calendar::turn ) );
         for( i = 0; i < explosions; i++ ) {
             sounds::sound( pos, 20, sounds::sound_t::combat, _( "Bang!" ), false, "explosion", "small" );
         }
         it->countdown_point -= ( explosions - 1 ) * 1_seconds;
     }
     return 0;
 }
References _, item::age(), sounds::alarm, sounds::combat, item::countdown_point, min(), math_opers::pos(), rng(), sounds::sound(), and calendar::turn.
Referenced by Item_factory::init().
fish_trap()
std::optional< int > iuse::fish_trap (Character * p, item * it, const tripoint &)
Definition at line 1784 of file iuse.cpp.
 {
     map &here = get_map();
     // Handle deploying fish trap.
     if( it->active ) {
         it->active = false;
         return 0;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     if( p->cant_do_underwater() ) {
         return std::nullopt;
     }
     if( it->ammo_remaining() == 0 ) {
         p->add_msg_if_player( _( "Fish aren't foolish enough to go in here without bait." ) );
         return std::nullopt;
     }
     const std::optional<tripoint> pnt_ = choose_adjacent( _( "Put fish trap where?" ) );
     if( !pnt_ ) {
         return std::nullopt;
     }
     const tripoint pnt = *pnt_;
     if( !here.has_flag( ter_furn_flag::TFLAG_FISHABLE, pnt ) ) {
         p->add_msg_if_player( m_info, _( "You can't fish there!" ) );
         return std::nullopt;
     }
     if( !good_fishing_spot( pnt, p ) ) {
         return std::nullopt;
     }
     it->active = true;
     it->set_age( 0_turns );
     here.add_item_or_charges( pnt, *it );
     p->i_rem( it );
     p->add_msg_if_player( m_info,
                           _( "You place the fish trap; in three hours or so, you may catch some fish." ) );
     return 0;
 }
References _, item::active, map::add_item_or_charges(), Character::add_msg_if_player(), item::ammo_remaining(), Character::cant_do_mounted(), Creature::cant_do_underwater(), choose_adjacent(), get_map(), good_fishing_spot(), map::has_flag(), Character::i_rem(), m_info, item::set_age(), and TFLAG_FISHABLE.
Referenced by Item_factory::init().
fish_trap_tick()
std::optional< int > iuse::fish_trap_tick (Character * p, item * it, const tripoint & pos)
Survival randomly increases number of fish caught in fishing trap
Definition at line 1829 of file iuse.cpp.
 {
     map &here = get_map();
     // Handle processing fish trap over time.
     if( it->ammo_remaining() == 0 ) {
         it->active = false;
         return 0;
     }
     if( it->age() > 3_hours ) {
         it->active = false;
         if( !here.has_flag( ter_furn_flag::TFLAG_FISHABLE, pos ) ) {
             return 0;
         }
         avatar &player = get_avatar();
         int success = -50;
         const float surv = player.get_skill_level( skill_survival );
         const int attempts = rng( it->ammo_remaining(), it->ammo_remaining() * it->ammo_remaining() );
         for( int i = 0; i < attempts; i++ ) {
             /** @EFFECT_SURVIVAL randomly increases number of fish caught in fishing trap */
             success += rng( round( surv ), round( surv * surv ) );
         }
         int bait_consumed = rng( 0, it->ammo_remaining() + 1 );
         if( bait_consumed > it->ammo_remaining() ) {
             bait_consumed = it->ammo_remaining();
         }
         int fishes = 0;
         if( success < 0 ) {
             fishes = 0;
         } else if( success < 300 ) {
             fishes = 1;
         } else if( success < 1500 ) {
             fishes = 2;
         } else {
             fishes = rng( 3, 5 );
         }
         if( fishes == 0 ) {
             it->ammo_consume( it->ammo_remaining(), pos, nullptr );
             player.practice( skill_survival, rng( 5, 15 ) );
             return 0;
         }
         //get the fishables around the trap's spot
         std::unordered_set<tripoint> fishable_locations = g->get_fishable_locations( 60, pos );
         std::vector<monster *> fishables = g->get_fishable_monsters( fishable_locations );
         for( int i = 0; i < fishes; i++ ) {
             player.practice( skill_survival, rng( 3, 10 ) );
             if( !fishables.empty() ) {
                 monster *chosen_fish = random_entry( fishables );
                 // reduce the abstract fish_population marker of that fish
                 chosen_fish->fish_population -= 1;
                 if( chosen_fish->fish_population <= 0 ) {
                     g->catch_a_monster( chosen_fish, pos, p, 300_hours ); //catch the fish!
                 } else {
                     here.add_item_or_charges( pos, item::make_corpse( chosen_fish->type->id,
                                               calendar::turn + rng( 0_turns,
                                                       3_hours ) ) );
                 }
             } else {
                 //there will always be a chance that the player will get lucky and catch a fish
                 //not existing in the fishables vector. (maybe it was in range, but wandered off)
                 //lets say it is a 5% chance per fish to catch
                 if( one_in( 20 ) ) {
                     const std::vector<mtype_id> fish_group = MonsterGroupManager::GetMonstersFromGroup(
                                 GROUP_FISH, true );
                     const mtype_id &fish_mon = random_entry_ref( fish_group );
                     //Yes, we can put fishes in the trap like knives in the boot,
                     //and then get fishes via activation of the item,
                     //but it's not as comfortable as if you just put fishes in the same tile with the trap.
                     //Also: corpses and comestibles do not rot in containers like this, but on the ground they will rot.
                     //we don't know when it was caught so use a random turn
                     here.add_item_or_charges( pos, item::make_corpse( fish_mon, it->birthday() + rng( 0_turns,
                                               3_hours ) ) );
                     break; //this can happen only once
                 }
             }
         }
         it->ammo_consume( bait_consumed, pos, nullptr );
     }
     return 0;
 }
References item::active, map::add_item_or_charges(), item::age(), item::ammo_consume(), item::ammo_remaining(), item::birthday(), monster::fish_population, g, get_avatar(), get_map(), MonsterGroupManager::GetMonstersFromGroup(), GROUP_FISH, map::has_flag(), mtype::id, item::make_corpse(), one_in(), player, math_opers::pos(), random_entry(), random_entry_ref(), rng(), round(), skill_survival, TFLAG_FISHABLE, calendar::turn, and monster::type.
Referenced by Item_factory::init().
fishing_rod()
std::optional< int > iuse::fishing_rod (Character * p, item * it, const tripoint &)
Definition at line 1756 of file iuse.cpp.
 {
     if( p->is_npc() ) {
         // Long actions - NPCs don't like those yet.
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     map &here = get_map();
     std::optional<tripoint> found;
     for( const tripoint &pnt : here.points_in_radius( p->pos(), 1 ) ) {
         if( here.has_flag( ter_furn_flag::TFLAG_FISHABLE, pnt ) && good_fishing_spot( pnt, p ) ) {
             found = pnt;
             break;
         }
     }
     if( !found ) {
         p->add_msg_if_player( m_info, _( "You can't fish there!" ) );
         return std::nullopt;
     }
     p->add_msg_if_player( _( "You cast your line and wait to hook something" ) );
     p->assign_activity( ACT_FISH, to_moves<int>( 5_hours ), 0, 0, it->tname() );
     p->activity.targets.emplace_back( *p, it );
     p->activity.coord_set = g->get_fishable_locations( 60, *found );
     return 0;
 }
References _, ACT_FISH, Character::activity, Character::add_msg_if_player(), Character::assign_activity(), Character::cant_do_mounted(), player_activity::coord_set, g, get_map(), good_fishing_spot(), map::has_flag(), Character::is_npc(), m_info, map::points_in_radius(), Creature::pos(), player_activity::targets, TFLAG_FISHABLE, and item::tname().
Referenced by Item_factory::init().
fitness_check()
std::optional< int > iuse::fitness_check (Character * p, item * it, const tripoint &)
Definition at line 4164 of file iuse.cpp.
 {
     if( p->has_trait( trait_ILLITERATE ) ) {
         p->add_msg_if_player( m_info, _( "You don't know what you're looking at." ) );
         return std::nullopt;
     } else {
         //What else should block using f-band?
         std::string msg;
         msg.append( "***  " );
         msg.append( string_format( _( "You check your health metrics on your %s." ), it->tname( 1,
                                    false ) ) );
         msg.append( "  ***\n\n" );
         const int bpm = p->heartrate_bpm();
         msg.append( "-> " );
         msg.append( string_format( _( "Your heart rate is %i bpm." ), bpm ) );
         if( bpm > 179 ) {
             msg.append( "\n" );
             msg.append( "-> " );
             msg.append( _( "WARNING!  Slow down!  Your pulse is getting too high, champion!" ) );
         }
         const std::string exercise = p->activity_level_str();
         msg.append( "\n" );
         msg.append( "-> " );
         if( exercise == "NO_EXERCISE" ) {
             msg.append( _( "You haven't really been active today.  Try going for a walk!" ) );
         } else if( exercise == "LIGHT_EXERCISE" ) {
             msg.append( _( "Good start!  Keep it up and move more." ) );
         } else if( exercise == "MODERATE_EXERCISE" ) {
             msg.append( _( "Doing good!  Don't stop, push the limit!" ) );
         } else if( exercise == "ACTIVE_EXERCISE" ) {
             msg.append( _( "Great job!  Take a break and don't forget about hydration!" ) );
         } else {
             msg.append( _( "You are too active!  Avoid overexertion for your safety and health." ) );
         }
         msg.append( "\n" );
         msg.append( "-> " );
         msg.append( string_format( _( "You consumed %d kcal today and %d kcal yesterday." ),
                                    p->as_avatar()->get_daily_ingested_kcal( false ),
                                    p->as_avatar()->get_daily_ingested_kcal( true ) ) );
         msg.append( "\n" );
         msg.append( "-> " );
         msg.append( string_format( _( "You burned %d kcal today and %d kcal yesterday." ),
                                    p->as_avatar()->get_daily_spent_kcal( false ),
                                    p->as_avatar()->get_daily_spent_kcal( true ) ) );
         //TODO add whatever else makes sense (steps, sleep quality, health level approximation?)
         p->add_msg_if_player( m_neutral, msg );
         popup( msg );
     }
     return 1;
 }
References _, Character::activity_level_str(), Character::add_msg_if_player(), Creature::as_avatar(), avatar::get_daily_ingested_kcal(), avatar::get_daily_spent_kcal(), Character::has_trait(), Character::heartrate_bpm(), m_info, m_neutral, popup(), string_format(), item::tname(), and trait_ILLITERATE.
Referenced by Item_factory::init().
flu_vaccine()
std::optional< int > iuse::flu_vaccine (Character * p, item * it, const tripoint &)
Definition at line 888 of file iuse.cpp.
 {
     p->add_msg_if_player( _( "You inject the vaccine." ) );
     time_point expiration_date = it->birthday() + 24_weeks;
     time_duration remaining_time = expiration_date - calendar::turn;
     // FIXME Removing feedback and visible status would be more realistic
     if( remaining_time > 0_turns ) {
         p->add_msg_if_player( m_good, _( "You no longer need to fear the flu, at least for some time." ) );
         p->add_effect( effect_flushot, remaining_time, false );
     } else {
         p->add_msg_if_player( m_bad,
                               _( "You notice the date on the packaging is pretty old.  It may no longer be effective." ) );
     }
     p->mod_pain( 3 );
     item syringe( "syringe", it->birthday() );
     p->i_add_or_drop( syringe );
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), item::birthday(), effect_flushot, Character::i_add_or_drop(), m_bad, m_good, Character::mod_pain(), and calendar::turn.
Referenced by Item_factory::init().
flumed()
std::optional< int > iuse::flumed (Character * p, item * it, const tripoint &)
Definition at line 1002 of file iuse.cpp.
 {
     p->add_effect( effect_took_flumed, 10_hours );
     p->add_msg_if_player( _( "You take some %s." ), it->tname() );
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), effect_took_flumed, and item::tname().
Referenced by Item_factory::init().
flusleep()
std::optional< int > iuse::flusleep (Character * p, item * it, const tripoint &)
Definition at line 1009 of file iuse.cpp.
 {
     p->add_effect( effect_took_flumed, 12_hours );
     p->mod_sleepiness( 30 );
     p->add_msg_if_player( _( "You take some %s." ), it->tname() );
     p->add_msg_if_player( m_warning, _( "You feel very sleepy" ) );
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), effect_took_flumed, m_warning, Character::mod_sleepiness(), and item::tname().
Referenced by Item_factory::init().
foodperson()
std::optional< int > iuse::foodperson (Character * p, item * it, const tripoint &)
Definition at line 6934 of file iuse.cpp.
 {
     // Prevent crash if battery was somehow removed.
     if( !it->magazine_current() ) {
         return std::nullopt;
     }
     time_duration shift = time_duration::from_turns( it->magazine_current()->ammo_remaining() *
                           it->type->tool->turns_per_charge );
     p->add_msg_if_player( m_info, _( "Your HUD lights-up: \"Your shift ends in %s\"." ),
                           to_string( shift ) );
     return 0;
 }
References _, Character::add_msg_if_player(), item::ammo_remaining(), time_duration::from_turns(), m_info, item::magazine_current(), shift, to_string(), itype::tool, and item::type.
Referenced by Item_factory::init().
foodperson_voice()
std::optional< int > iuse::foodperson_voice (Character * , item * , const tripoint & pos)
Definition at line 6924 of file iuse.cpp.
 {
     if( calendar::once_every( 1_minutes ) ) {
         const SpeechBubble &speech = get_speech( "foodperson_mask" );
         sounds::sound( pos, speech.volume, sounds::sound_t::alarm, speech.text.translated(), true, "speech",
                        "foodperson_mask" );
     }
     return 0;
 }
References sounds::alarm, get_speech(), calendar::once_every(), math_opers::pos(), sounds::sound(), and speech.
Referenced by Item_factory::init().
fungicide()
std::optional< int > iuse::fungicide (Character * p, item * , const tripoint &)
Definition at line 665 of file iuse.cpp.
 {
     if( p->cant_do_underwater() ) {
         return std::nullopt;
     }
     const bool has_fungus = p->has_effect( effect_fungus );
     const bool has_spores = p->has_effect( effect_spores );
     if( p->is_npc() && !has_fungus && !has_spores ) {
         return std::nullopt;
     }
     p->add_msg_player_or_npc( _( "You use your fungicide." ), _( "<npcname> uses some fungicide." ) );
     if( has_fungus && one_in( 3 ) ) {
         // this is not a medicine, the effect is shorter
         p->add_effect( effect_antifungal, 1_hours );
         if( p->has_effect( effect_fungus ) ) {
             p->add_msg_if_player( m_warning,
                                   _( "You feel a burning sensation slowly radiating throughout your skin." ) );
         }
     }
     creature_tracker &creatures = get_creature_tracker();
     if( has_spores && one_in( 2 ) ) {
         if( !p->has_effect( effect_fungus ) ) {
             p->add_msg_if_player( m_warning, _( "Your skin grows warm for a moment." ) );
         }
         p->remove_effect( effect_spores );
         int spore_count = rng( 1, 6 );
         map &here = get_map();
         for( const tripoint &dest : here.points_in_radius( p->pos(), 1 ) ) {
             if( spore_count == 0 ) {
                 break;
             }
             if( dest == p->pos() ) {
                 continue;
             }
             if( here.passable( dest ) && x_in_y( spore_count, 8 ) ) {
                 if( monster *const mon_ptr = creatures.creature_at<monster>( dest ) ) {
                     monster &critter = *mon_ptr;
                     if( !critter.type->in_species( species_FUNGUS ) ) {
                         add_msg_if_player_sees( dest, m_warning, _( "The %s is covered in tiny spores!" ),
                                                 critter.name() );
                     }
                     if( !critter.make_fungus() ) {
                         critter.die( p ); // counts as kill by player
                     }
                 } else {
                     g->place_critter_at( mon_spore, dest );
                 }
                 spore_count--;
             }
         }
     }
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), add_msg_if_player_sees(), Character::add_msg_player_or_npc(), Creature::cant_do_underwater(), creature_tracker::creature_at(), monster::die(), effect_antifungal, effect_fungus, effect_spores, g, get_creature_tracker(), get_map(), Creature::has_effect(), mtype::in_species(), Character::is_npc(), m_warning, monster::make_fungus(), mon_spore, monster::name(), one_in(), map::passable(), map::points_in_radius(), Creature::pos(), Creature::remove_effect(), rng(), species_FUNGUS, monster::type, and x_in_y().
Referenced by Item_factory::init().
gasmask()
std::optional< int > iuse::gasmask (Character * p, item * it, const tripoint & pos)
6000/that is the amount of "gas absorbed" charges to tick up every second in order to reach that number.
Definition at line 3972 of file iuse.cpp.
 {
     if( p && p->is_worn( *it ) ) {
         // calculate amount of absorbed gas per filter charge
         const field &gasfield = get_map().field_at( pos );
         for( const auto &dfield : gasfield ) {
             const field_entry &entry = dfield.second;
             int gas_abs_factor = to_turns<int>( entry.get_field_type()->gas_absorption_factor );
             // Not set, skip this field
             if( gas_abs_factor == 0 ) {
                 continue;
             }
             const field_intensity_level &int_level = entry.get_intensity_level();
             // 6000 is the amount of "gas absorbed" charges in a full 100 capacity gas mask cartridge.
             // factor/concentration gives an amount of seconds the cartidge is expected to last in current conditions.
             /// 6000/that is the amount of "gas absorbed" charges to tick up every second in order to reach that number.
             float gas_absorbed = 6000 / ( static_cast<float>( gas_abs_factor ) / static_cast<float>
                                           ( int_level.concentration ) );
             add_msg_debug( debugmode::DF_IUSE, "Absorbing %g/60 from field: 6000 / (%d * %d)", gas_absorbed,
                            gas_abs_factor, int_level.concentration );
             if( gas_absorbed > 0 ) {
                 it->set_var( "gas_absorbed", it->get_var( "gas_absorbed", 0 ) + gas_absorbed );
             }
         }
         if( it->get_var( "gas_absorbed", 0 ) >= 60 ) {
             it->ammo_consume( 1, pos, p );
             it->set_var( "gas_absorbed", 0 );
             if( it->ammo_remaining() < 10 ) {
                 p->add_msg_player_or_npc(
                     m_bad,
                     _( "Your %s is getting hard to breathe in!" ),
                     _( "<npcname>'s gas mask is getting hard to breathe in!" )
                     , it->tname() );
             }
         }
         if( it->ammo_remaining() == 0 ) {
             p->add_msg_player_or_npc(
                 m_bad,
                 _( "Your %s requires new filters!" ),
                 _( "<npcname> needs new gas mask filters!" )
                 , it->tname() );
         }
     }
     if( it->ammo_remaining() == 0 ) {
         it->set_var( "overwrite_env_resist", 0 );
         it->active = false;
     }
     return 0;
 }
References _, item::active, add_msg_debug, Character::add_msg_player_or_npc(), item::ammo_consume(), item::ammo_remaining(), field_intensity_level::concentration, debugmode::DF_IUSE, map::field_at(), field_type::gas_absorption_factor, field_entry::get_field_type(), field_entry::get_intensity_level(), get_map(), item::get_var(), Character::is_worn(), m_bad, math_opers::pos(), item::set_var(), and item::tname().
Referenced by Item_factory::init().
gasmask_activate()
std::optional< int > iuse::gasmask_activate (Character * p, item * it, const tripoint &)
Definition at line 3959 of file iuse.cpp.
 {
     if( it->ammo_remaining() == 0 ) {
         p->add_msg_if_player( _( "Your %s doesn't have a filter." ), it->tname() );
     } else {
         p->add_msg_if_player( _( "You prepare your %s." ), it->tname() );
         it->active = true;
         it->set_var( "overwrite_env_resist", it->get_base_env_resist_w_filter() );
     }
     return 0;
 }
References _, item::active, Character::add_msg_if_player(), item::ammo_remaining(), item::get_base_env_resist_w_filter(), item::set_var(), and item::tname().
Referenced by Item_factory::init().
geiger()
std::optional< int > iuse::geiger (Character * p, item * it, const tripoint &)
Definition at line 3127 of file iuse.cpp.
 {
     int ch = uilist( _( "Geiger counter:" ), {
         _( "Scan yourself or other person" ), _( "Scan the ground" ), _( "Turn continuous scan on" )
     } );
     creature_tracker &creatures = get_creature_tracker();
     switch( ch ) {
         case 0: {
             const std::function<bool( const tripoint & )> f = [&]( const tripoint & pnt ) {
                 return creatures.creature_at<Character>( pnt ) != nullptr;
             };
             const std::optional<tripoint> pnt_ = choose_adjacent_highlight( _( "Scan whom?" ),
                                                  _( "There is no one to scan nearby." ), f, false );
             if( !pnt_ ) {
                 return std::nullopt;
             }
             const tripoint &pnt = *pnt_;
             if( pnt == p->pos() ) {
                 p->add_msg_if_player( m_info, _( "Your radiation level: %d mSv (%d mSv from items)" ), p->get_rad(),
                                       static_cast<int>( p->get_leak_level() ) );
                 break;
             }
             if( npc *const person_ = creatures.creature_at<npc>( pnt ) ) {
                 npc &person = *person_;
                 p->add_msg_if_player( m_info, _( "%s's radiation level: %d mSv (%d mSv from items)" ),
                                       person.get_name(), person.get_rad(),
                                       static_cast<int>( person.get_leak_level() ) );
             }
             break;
         }
         case 1:
             p->add_msg_if_player( m_info, _( "The ground's radiation level: %d mSv/h" ),
                                   get_map().get_radiation( p->pos() ) );
             break;
         case 2:
             p->add_msg_if_player( _( "The geiger counter's scan LED turns on." ) );
             it->convert( itype_geiger_on, p ).active = true;
             break;
         default:
             return std::nullopt;
     }
     p->mod_moves( -100 );
     return 1;
 }
References _, item::active, Character::add_msg_if_player(), choose_adjacent_highlight(), item::convert(), get_creature_tracker(), Character::get_leak_level(), get_map(), Character::get_name(), Character::get_rad(), itype_geiger_on, m_info, Creature::mod_moves(), and Creature::pos().
Referenced by Item_factory::init().
geiger_active()
std::optional< int > iuse::geiger_active (Character * , item * , const tripoint & pos)
Definition at line 3174 of file iuse.cpp.
 {
     const int rads = get_map().get_radiation( pos );
     if( rads == 0 ) {
         return 1;
     }
     std::string description = rads > 50 ? _( "buzzing" ) :
                               rads > 25 ? _( "rapid clicking" ) : _( "clicking" );
     std::string sound_var = rads > 50 ? _( "geiger_high" ) :
                             rads > 25 ? _( "geiger_medium" ) : _( "geiger_low" );
     sounds::sound( pos, 6, sounds::sound_t::alarm, description, true, "tool", sound_var );
     if( !get_avatar().can_hear( pos, 6 ) ) {
         // can not hear it, but may have alarmed other creatures
         return 1;
     }
     if( rads > 50 ) {
         add_msg( m_warning, _( "The geiger counter buzzes intensely." ) );
     } else if( rads > 35 ) {
         add_msg( m_warning, _( "The geiger counter clicks wildly." ) );
     } else if( rads > 25 ) {
         add_msg( m_warning, _( "The geiger counter clicks rapidly." ) );
     } else if( rads > 15 ) {
         add_msg( m_warning, _( "The geiger counter clicks steadily." ) );
     } else if( rads > 8 ) {
         add_msg( m_warning, _( "The geiger counter clicks slowly." ) );
     } else if( rads > 4 ) {
         add_msg( _( "The geiger counter clicks intermittently." ) );
     } else {
         add_msg( _( "The geiger counter clicks once." ) );
     }
     return 1;
 }
References _, add_msg(), sounds::alarm, get_avatar(), get_map(), map::get_radiation(), m_warning, math_opers::pos(), and sounds::sound().
Referenced by Item_factory::init().
granade_act()
std::optional< int > iuse::granade_act (Character * , item * it, const tripoint & pos)
Maximum Strength increases possible granade str buff for NPCs Maximum Dexterity increases possible granade dex buff for NPCs Maximum Intelligence increases possible granade int buff for NPCs Maximum Perception increases possible granade per buff for NPCs Maximum Strength increases possible granade str buff Maximum Dexterity increases possible granade dex buff Maximum Intelligence increases possible granade int buff Maximum Perception increases possible granade per buff Maximum Strength increases possible granade str debuff for NPCs (NEGATIVE) Maximum Dexterity increases possible granade dex debuff for NPCs (NEGATIVE) Maximum Intelligence increases possible granade int debuff for NPCs (NEGATIVE) Maximum Perception increases possible granade per debuff for NPCs (NEGATIVE) Maximum Strength increases possible granade str debuff (NEGATIVE) Maximum Dexterity increases possible granade dex debuff (NEGATIVE) Maximum Intelligence increases possible granade int debuff (NEGATIVE) Maximum Perception increases possible granade per debuff (NEGATIVE)
Definition at line 3274 of file iuse.cpp.
 {
     if( pos.x == -999 || pos.y == -999 ) {
         return std::nullopt;
     }
     map &here = get_map();
     creature_tracker &creatures = get_creature_tracker();
     int explosion_radius = 3;
     int effect_roll = rng( 1, 4 );
     auto buff_stat = [&]( int &current_stat, int modify_by ) {
         int modified_stat = current_stat + modify_by;
         current_stat = std::max( current_stat, std::min( 15, modified_stat ) );
     };
     avatar &player_character = get_avatar();
     switch( effect_roll ) {
         case 1:
             sounds::sound( pos, 100, sounds::sound_t::electronic_speech, _( "BUGFIXES!" ),
                            true, "speech", it->typeId().str() );
             explosion_handler::draw_explosion( pos, explosion_radius, c_light_cyan );
             for( const tripoint &dest : here.points_in_radius( pos, explosion_radius ) ) {
                 monster *const mon = creatures.creature_at<monster>( dest, true );
                 if( mon && ( mon->type->in_species( species_INSECT ) || mon->is_hallucination() ) ) {
                     mon->die_in_explosion( nullptr );
                 }
             }
             break;
         case 2:
             sounds::sound( pos, 100, sounds::sound_t::electronic_speech, _( "BUFFS!" ),
                            true, "speech", it->typeId().str() );
             explosion_handler::draw_explosion( pos, explosion_radius, c_green );
             for( const tripoint &dest : here.points_in_radius( pos, explosion_radius ) ) {
                 if( monster *const mon_ptr = creatures.creature_at<monster>( dest ) ) {
                     monster &critter = *mon_ptr;
                     critter.set_speed_base(
                         critter.get_speed_base() * rng_float( 1.1, 2.0 ) );
                     critter.set_hp( critter.get_hp() * rng_float( 1.1, 2.0 ) );
                 } else if( npc *const person = creatures.creature_at<npc>( dest ) ) {
                     /** @EFFECT_STR_MAX increases possible granade str buff for NPCs */
                     buff_stat( person->str_max, rng( 0, person->str_max / 2 ) );
                     /** @EFFECT_DEX_MAX increases possible granade dex buff for NPCs */
                     buff_stat( person->dex_max, rng( 0, person->dex_max / 2 ) );
                     /** @EFFECT_INT_MAX increases possible granade int buff for NPCs */
                     buff_stat( person->int_max, rng( 0, person->int_max / 2 ) );
                     /** @EFFECT_PER_MAX increases possible granade per buff for NPCs */
                     buff_stat( person->per_max, rng( 0, person->per_max / 2 ) );
                 } else if( player_character.pos() == dest ) {
                     /** @EFFECT_STR_MAX increases possible granade str buff */
                     buff_stat( player_character.str_max, rng( 0, player_character.str_max / 2 ) );
                     /** @EFFECT_DEX_MAX increases possible granade dex buff */
                     buff_stat( player_character.dex_max, rng( 0, player_character.dex_max / 2 ) );
                     /** @EFFECT_INT_MAX increases possible granade int buff */
                     buff_stat( player_character.int_max, rng( 0, player_character.int_max / 2 ) );
                     /** @EFFECT_PER_MAX increases possible granade per buff */
                     buff_stat( player_character.per_max, rng( 0, player_character.per_max / 2 ) );
                     player_character.recalc_hp();
                     for( const bodypart_id &bp : player_character.get_all_body_parts(
                              get_body_part_flags::only_main ) ) {
                         player_character.set_part_hp_cur( bp, player_character.get_part_hp_cur( bp ) * rng_float( 1,
                                                           1.2 ) );
                         const int hp_max = player_character.get_part_hp_max( bp );
                         if( player_character.get_part_hp_cur( bp ) > hp_max ) {
                             player_character.set_part_hp_cur( bp, hp_max );
                         }
                     }
                 }
             }
             break;
         case 3:
             sounds::sound( pos, 100, sounds::sound_t::electronic_speech, _( "NERFS!" ),
                            true, "speech", it->typeId().str() );
             explosion_handler::draw_explosion( pos, explosion_radius, c_red );
             for( const tripoint &dest : here.points_in_radius( pos, explosion_radius ) ) {
                 if( monster *const mon_ptr = creatures.creature_at<monster>( dest ) ) {
                     monster &critter = *mon_ptr;
                     critter.set_speed_base(
                         rng( 0, critter.get_speed_base() ) );
                     critter.set_hp( rng( 1, critter.get_hp() ) );
                 } else if( npc *const person = creatures.creature_at<npc>( dest ) ) {
                     /** @EFFECT_STR_MAX increases possible granade str debuff for NPCs (NEGATIVE) */
                     person->str_max -= rng( 0, person->str_max / 2 );
                     /** @EFFECT_DEX_MAX increases possible granade dex debuff for NPCs (NEGATIVE) */
                     person->dex_max -= rng( 0, person->dex_max / 2 );
                     /** @EFFECT_INT_MAX increases possible granade int debuff for NPCs (NEGATIVE) */
                     person->int_max -= rng( 0, person->int_max / 2 );
                     /** @EFFECT_PER_MAX increases possible granade per debuff for NPCs (NEGATIVE) */
                     person->per_max -= rng( 0, person->per_max / 2 );
                 } else if( player_character.pos() == dest ) {
                     /** @EFFECT_STR_MAX increases possible granade str debuff (NEGATIVE) */
                     player_character.str_max -= rng( 0, player_character.str_max / 2 );
                     /** @EFFECT_DEX_MAX increases possible granade dex debuff (NEGATIVE) */
                     player_character.dex_max -= rng( 0, player_character.dex_max / 2 );
                     /** @EFFECT_INT_MAX increases possible granade int debuff (NEGATIVE) */
                     player_character.int_max -= rng( 0, player_character.int_max / 2 );
                     /** @EFFECT_PER_MAX increases possible granade per debuff (NEGATIVE) */
                     player_character.per_max -= rng( 0, player_character.per_max / 2 );
                     player_character.recalc_hp();
                     for( const bodypart_id &bp : player_character.get_all_body_parts(
                              get_body_part_flags::only_main ) ) {
                         const int hp_cur = player_character.get_part_hp_cur( bp );
                         if( hp_cur > 0 ) {
                             player_character.set_part_hp_cur( bp, rng( 1, hp_cur ) );
                         }
                     }
                 }
             }
             break;
         case 4:
             sounds::sound( pos, 100, sounds::sound_t::electronic_speech, _( "REVERTS!" ),
                            true, "speech", it->typeId().str() );
             explosion_handler::draw_explosion( pos, explosion_radius, c_pink );
             for( const tripoint &dest : here.points_in_radius( pos, explosion_radius ) ) {
                 if( monster *const mon_ptr = creatures.creature_at<monster>( dest ) ) {
                     monster &critter = *mon_ptr;
                     critter.set_speed_base( critter.type->speed );
                     critter.set_hp( critter.get_hp_max() );
                     critter.clear_effects();
                 } else if( npc *const person = creatures.creature_at<npc>( dest ) ) {
                     person->environmental_revert_effect();
                 } else if( player_character.pos() == dest ) {
                     player_character.environmental_revert_effect();
                     do_purify( player_character );
                 }
             }
             break;
     }
     return 1;
 }
References _, bp, c_green, c_light_cyan, c_pink, c_red, Creature::clear_effects(), creature_tracker::creature_at(), Character::dex_max, monster::die_in_explosion(), do_purify(), explosion_handler::draw_explosion(), sounds::electronic_speech, Character::environmental_revert_effect(), Creature::get_all_body_parts(), get_avatar(), get_creature_tracker(), monster::get_hp(), monster::get_hp_max(), get_map(), Creature::get_part_hp_cur(), Creature::get_part_hp_max(), Creature::get_speed_base(), mtype::in_species(), Character::int_max, monster::is_hallucination(), max(), min(), only_main, Character::per_max, map::points_in_radius(), Creature::pos(), math_opers::pos(), Character::recalc_hp(), rng(), rng_float(), monster::set_hp(), Character::set_part_hp_cur(), Creature::set_speed_base(), sounds::sound(), species_INSECT, mtype::speed, string_id< T >::str(), Character::str_max, monster::type, and item::typeId().
Referenced by Item_factory::init().
grenade_inc_act()
std::optional< int > iuse::grenade_inc_act (Character * p, item * , const tripoint & pos)
Definition at line 3435 of file iuse.cpp.
 {
     if( pos.x == -999 || pos.y == -999 ) {
         return std::nullopt;
     }
     map &here = get_map();
     int num_flames = rng( 3, 5 );
     for( int current_flame = 0; current_flame < num_flames; current_flame++ ) {
         tripoint dest( pos + point( rng( -5, 5 ), rng( -5, 5 ) ) );
         std::vector<tripoint> flames = line_to( pos, dest, 0, 0 );
         for( tripoint &flame : flames ) {
             here.add_field( flame, fd_fire, rng( 0, 2 ) );
         }
     }
     explosion_handler::explosion( p, pos, 8, 0.8, true );
     for( const tripoint &dest : here.points_in_radius( pos, 2 ) ) {
         here.add_field( dest, fd_incendiary, 3 );
     }
     avatar &player = get_avatar();
     if( player.has_trait( trait_PYROMANIA ) && player.sees( pos ) ) {
         player.add_morale( MORALE_PYROMANIA_STARTFIRE, 15, 15, 8_hours, 6_hours );
         player.rem_morale( MORALE_PYROMANIA_NOFIRE );
         add_msg( m_good, _( "Fire  Good" ) );
     }
     return 0;
 }
References _, map::add_field(), add_msg(), explosion_handler::explosion(), fd_fire, fd_incendiary, mattack::flame(), get_avatar(), get_map(), line_to(), m_good, MORALE_PYROMANIA_NOFIRE, MORALE_PYROMANIA_STARTFIRE, player, map::points_in_radius(), math_opers::pos(), rng(), and trait_PYROMANIA.
Referenced by Item_factory::init().
gun_repair()
std::optional< int > iuse::gun_repair (Character * p, item * it, const tripoint &)
Mechanics >1 allows gun repair
Definition at line 5139 of file iuse.cpp.
 {
     if( !it->ammo_sufficient( p ) ) {
         return std::nullopt;
     }
     if( p->cant_do_underwater() ) {
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     /** @EFFECT_MECHANICS >1 allows gun repair */
     if( p->get_skill_level( skill_mechanics ) < 2 ) {
         p->add_msg_if_player( m_info, _( "You need a mechanics skill of 2 to use this repair kit." ) );
         return std::nullopt;
     }
     item_location loc = game_menus::inv::titled_filter_menu( []( const item_location & loc ) {
         return loc->is_firearm() && !loc->has_flag( flag_NO_REPAIR );
     }, get_avatar(), _( "Select the firearm to repair:" ) );
     if( !loc ) {
         p->add_msg_if_player( m_info, _( "You don't have that item!" ) );
         return std::nullopt;
     }
     return ::gun_repair( p, it, loc );
 }
References _, Character::add_msg_if_player(), item::ammo_sufficient(), Character::cant_do_mounted(), Creature::cant_do_underwater(), flag_NO_REPAIR, get_avatar(), Character::get_skill_level(), gun_repair(), item::has_flag(), item::is_firearm(), m_info, skill_mechanics, and game_menus::inv::titled_filter_menu().
Referenced by Item_factory::init().
gunmod_attach()
std::optional< int > iuse::gunmod_attach (Character * p, item * it, const tripoint &)
Definition at line 5194 of file iuse.cpp.
 {
     if( !it || !it->is_gunmod() ) {
         debugmsg( "tried to attach non-gunmod" );
         return std::nullopt;
     }
     if( !p ) {
         return std::nullopt;
     }
     do {
         item_location loc = game_menus::inv::gun_to_modify( *p->as_character(), *it );
         if( !loc ) {
             add_msg( m_info, _( "Never mind." ) );
             return std::nullopt;
         }
         if( !loc->is_gunmod_compatible( *it ).success() ) {
             return std::nullopt;
         }
         const item mod_copy( *it );
         item modded_gun( *loc );
         modded_gun.put_in( mod_copy, pocket_type::MOD );
         if( !game_menus::inv::compare_items( *loc, modded_gun, _( "Attach modification?" ) ) ) {
             continue;
         }
         p->gunmod_add( *loc, *it );
         return 0;
     } while( true );
 }
References _, add_msg(), Character::as_character(), game_menus::inv::compare_items(), debugmsg, game_menus::inv::gun_to_modify(), Character::gunmod_add(), item::is_gunmod(), item::is_gunmod_compatible(), m_info, MOD, item::put_in(), and ret_val_common::success().
Referenced by Item_factory::init().
hacksaw()
std::optional< int > iuse::hacksaw (Character * p, item * it, const tripoint & it_pnt)
Definition at line 4678 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action hacksaw that requires character but no character is present",
                   it->typeId().str() );
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     map &here = get_map();
     const std::function<bool( const tripoint & )> f =
     [&here, p]( const tripoint & pnt ) {
         if( pnt == p->pos() ) {
             return false;
         } else if( here.has_furn( pnt ) ) {
             return here.furn( pnt )->hacksaw->valid();
         } else if( !here.ter( pnt )->is_null() ) {
             return here.ter( pnt )->hacksaw->valid();
         }
         return false;
     };
     const std::optional<tripoint> pnt_ = choose_adjacent_highlight(
             _( "Cut up metal where?" ), _( "There is no metal to cut up nearby." ), f, false );
     if( !pnt_ ) {
         return std::nullopt;
     }
     const tripoint &pnt = *pnt_;
     if( !f( pnt ) ) {
         if( pnt == p->pos() ) {
             p->add_msg_if_player( m_info, _( "Why would you do that?" ) );
             p->add_msg_if_player( m_info, _( "You're not even chained to a boiler." ) );
         } else {
             p->add_msg_if_player( m_info, _( "You can't cut that." ) );
         }
         return std::nullopt;
     }
     if( p->pos() == it_pnt ) {
         p->assign_activity( hacksaw_activity_actor( pnt, item_location{ *p, it } ) );
     } else {
         p->assign_activity( hacksaw_activity_actor( pnt, it->typeId(), it_pnt ) );
     }
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), Character::assign_activity(), Character::cant_do_mounted(), choose_adjacent_highlight(), debugmsg, map::furn(), get_map(), ter_t::hacksaw, furn_t::hacksaw, map::has_furn(), ter_t::is_null(), m_info, Creature::pos(), string_id< T >::str(), map::ter(), and item::typeId().
Referenced by Item_factory::init().
hairkit()
std::optional<int> iuse::hairkit (Character * , item * , const tripoint &)
hammer()
std::optional< int > iuse::hammer (Character * p, item * it, const tripoint & pos)
Definition at line 2709 of file iuse.cpp.
 {
     return iuse::crowbar( p, it, pos );
 }
References crowbar(), and math_opers::pos().
Referenced by Item_factory::init().
hand_crank()
std::optional< int > iuse::hand_crank (Character * p, item * it, const tripoint &)
Definition at line 4215 of file iuse.cpp.
 {
     if( p->is_npc() ) {
         // Long action
         return std::nullopt;
     }
     if( p->is_underwater() ) {
         p->add_msg_if_player( m_info, _( "It's not waterproof enough to work underwater." ) );
         return std::nullopt;
     }
     if( p->get_sleepiness() >= sleepiness_levels::DEAD_TIRED ) {
         p->add_msg_if_player( m_info, _( "You're too exhausted to keep cranking." ) );
         return std::nullopt;
     }
     item *magazine = it->magazine_current();
     if( magazine && magazine->has_flag( flag_RECHARGE ) ) {
         // 1600 minutes. It shouldn't ever run this long, but it's an upper bound.
         // expectation is it runs until the player is too tired.
         int moves = to_moves<int>( 1600_minutes );
         if( it->ammo_capacity( ammo_battery ) > it->ammo_remaining() ) {
             p->add_msg_if_player( _( "You start cranking the %s to charge its %s." ), it->tname(),
                                   it->magazine_current()->tname() );
             p->assign_activity( ACT_HAND_CRANK, moves, -1, 0, "hand-cranking" );
             p->activity.targets.emplace_back( *p, it );
         } else {
             p->add_msg_if_player( _( "You could use the %s to charge its %s, but it's already charged." ),
                                   it->tname(), magazine->tname() );
         }
     } else {
         p->add_msg_if_player( m_info, _( "You need a rechargeable battery cell to charge." ) );
     }
     return 0;
 }
References _, ACT_HAND_CRANK, Character::activity, Character::add_msg_if_player(), ammo_battery, item::ammo_capacity(), item::ammo_remaining(), Character::assign_activity(), DEAD_TIRED, flag_RECHARGE, Character::get_sleepiness(), item::has_flag(), Character::is_npc(), Creature::is_underwater(), m_info, item::magazine_current(), player_activity::targets, and item::tname().
Referenced by Item_factory::init().
handle_ground_graffiti()
std::optional< int > iuse::handle_ground_graffiti (Character & p, item * it, const std::string & prefix, const tripoint & where)
Definition at line 4817 of file iuse.cpp.
 {
     map &here = get_map();
     string_input_popup popup;
     std::string message = popup
                           .description( prefix + " " + _( "(To delete, clear the text and confirm)" ) )
                           .text( here.has_graffiti_at( where ) ? here.graffiti_at( where ) : std::string() )
                           .identifier( "graffiti" )
                           .query_string();
     if( popup.canceled() ) {
         return std::nullopt;
     }
     bool grave = here.ter( where ) == ter_t_grave_new;
     int move_cost;
     if( message.empty() ) {
         if( here.has_graffiti_at( where ) ) {
             move_cost = 3 * here.graffiti_at( where ).length();
             here.delete_graffiti( where );
             if( grave ) {
                 p.add_msg_if_player( m_info, _( "You blur the inscription on the grave." ) );
             } else {
                 p.add_msg_if_player( m_info, _( "You manage to get rid of the message on the surface." ) );
             }
         } else {
             return std::nullopt;
         }
     } else {
         here.set_graffiti( where, message );
         if( grave ) {
             p.add_msg_if_player( m_info, _( "You carve an inscription on the grave." ) );
         } else {
             p.add_msg_if_player( m_info, _( "You write a message on the surface." ) );
         }
         move_cost = 2 * message.length();
     }
     p.mod_moves( -move_cost );
     if( it != nullptr ) {
         return 1;
     } else {
         return 0;
     }
 }
References _, Character::add_msg_if_player(), map::delete_graffiti(), get_map(), map::graffiti_at(), map::has_graffiti_at(), m_info, mapgen_defer::message, Creature::mod_moves(), popup(), map::set_graffiti(), map::ter(), and ter_t_grave_new.
Referenced by construct::done_grave(), spray_can(), and inscribe_actor::use().
heat_food()
std::optional< int > iuse::heat_food (Character * p, item * it, const tripoint &)
Definition at line 4901 of file iuse.cpp.
 {
     if( get_map().has_nearby_fire( p->pos() ) ) {
         heat_item( *p );
         return 0;
     } else if( p->has_active_bionic( bio_tools ) && p->get_power_level() > 10_kJ &&
                query_yn( _( "There is no fire around; use your integrated toolset instead?" ) ) ) {
         if( heat_item( *p ) ) {
             p->mod_power_level( -10_kJ );
             return 0;
         }
     } else {
         p->add_msg_if_player( m_info,
                               _( "You need to be next to a fire to heat something up with the %s." ),
                               it->tname() );
     }
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), bio_tools, get_map(), Character::get_power_level(), Character::has_active_bionic(), heat_item(), m_info, Character::mod_power_level(), Creature::pos(), query_yn(), and item::tname().
Referenced by Item_factory::init().
heatpack()
std::optional< int > iuse::heatpack (Character * p, item * it, const tripoint &)
Definition at line 4893 of file iuse.cpp.
 {
     if( heat_item( *p ) ) {
         it->convert( itype_heatpack_used, p );
     }
     return 0;
 }
References item::convert(), heat_item(), and itype_heatpack_used.
Referenced by Item_factory::init().
honeycomb()
std::optional< int > iuse::honeycomb (Character * p, item * , const tripoint &)
Definition at line 478 of file iuse.cpp.
 {
     get_map().spawn_item( p->pos(), itype_wax, 2 );
     return 1;
 }
References get_map(), itype_wax, Creature::pos(), and map::spawn_item().
Referenced by Item_factory::init().
hotplate()
std::optional< int > iuse::hotplate (Character * p, item * it, const tripoint &)
Definition at line 4920 of file iuse.cpp.
 {
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     if( !it->ammo_sufficient( p ) ) {
         p->add_msg_if_player( m_info, _( "The %s's batteries are dead." ), it->tname() );
         return std::nullopt;
     }
     if( heat_item( *p ) ) {
         return 1;
     }
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), item::ammo_sufficient(), Character::cant_do_mounted(), heat_item(), m_info, and item::tname().
Referenced by Item_factory::init().
hotplate_atomic()
std::optional< int > iuse::hotplate_atomic (Character * p, item * it, const tripoint &)
Definition at line 4936 of file iuse.cpp.
 {
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     if( it->typeId() == itype_atomic_coffeepot ) {
         heat_item( *p );
     }
     return std::nullopt;
 }
References Character::cant_do_mounted(), heat_item(), itype_atomic_coffeepot, and item::typeId().
Referenced by Item_factory::init().
inhaler()
std::optional< int > iuse::inhaler (Character * p, item * , const tripoint &)
Definition at line 1018 of file iuse.cpp.
 {
     p->add_msg_player_or_npc( m_neutral, _( "You take a puff from your inhaler." ),
                               _( "<npcname> takes a puff from their inhaler." ) );
     if( !p->remove_effect( effect_asthma ) ) {
         p->mod_sleepiness( -3 ); // if we don't have asthma can be used as stimulant
         if( one_in( 20 ) ) {   // with a small but significant risk of adverse reaction
             p->add_effect( effect_shakes, rng( 2_minutes, 5_minutes ) );
         }
     }
     p->add_effect( effect_took_antiasthmatic, rng( 6_hours, 12_hours ) );
     p->remove_effect( effect_smoke_lungs );
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_player_or_npc(), effect_asthma, effect_shakes, effect_smoke_lungs, effect_took_antiasthmatic, m_neutral, Character::mod_sleepiness(), one_in(), Creature::remove_effect(), and rng().
Referenced by Item_factory::init().
jackhammer()
std::optional< int > iuse::jackhammer (Character * p, item * it, const tripoint & pos)
Definition at line 3051 of file iuse.cpp.
 {
     // use has_enough_charges to check for UPS availability
     // p is assumed to exist for iuse cases
     if( !it->ammo_sufficient( p ) ) {
         return std::nullopt;
     }
     return dig_tool( p, it, pos, ACT_JACKHAMMER,
                      _( "Drill where?" ), _( "You can't drill there." ),
                      _( "You start drilling into the %1$s with your %2$s." ) );
 }
References _, ACT_JACKHAMMER, item::ammo_sufficient(), dig_tool(), and math_opers::pos().
Referenced by Item_factory::init().
jet_injector()
std::optional< int > iuse::jet_injector (Character * p, item * it, const tripoint &)
Definition at line 5051 of file iuse.cpp.
 {
     if( !it->ammo_sufficient( p ) ) {
         p->add_msg_if_player( m_info, _( "The jet injector is empty." ) );
         return std::nullopt;
     } else {
         p->add_msg_if_player( _( "You inject yourself with the jet injector." ) );
         // Intensity is 2 here because intensity = 1 is the comedown
         p->add_effect( effect_jetinjector, 20_minutes, false, 2 );
         p->mod_painkiller( 20 );
         p->mod_stim( 10 );
         p->healall( 20 );
     }
     if( p->has_effect( effect_jetinjector ) ) {
         if( p->get_effect_dur( effect_jetinjector ) > 20_minutes ) {
             p->add_msg_if_player( m_warning, _( "Your heart is beating alarmingly fast!" ) );
         }
     }
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), item::ammo_sufficient(), effect_jetinjector, Creature::get_effect_dur(), Creature::has_effect(), Character::healall(), m_info, m_warning, Character::mod_painkiller(), and Character::mod_stim().
Referenced by Item_factory::init().
lumber()
std::optional< int > iuse::lumber (Character * p, item * it, const tripoint &)
Definition at line 4491 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action lumber that requires character but no character is present",
                   it->typeId().str() );
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     map &here = get_map();
     // Check if player is standing on any lumber
     for( item &i : here.i_at( p->pos() ) ) {
         if( i.typeId() == itype_log ) {
             here.i_rem( p->pos(), &i );
             cut_log_into_planks( *p );
             return 1;
         }
     }
     // If the player is not standing on a log, check inventory
     avatar *you = p->as_avatar();
     item_location loc;
     auto filter = []( const item & it ) {
         return it.typeId() == itype_log;
     };
     if( you != nullptr ) {
         loc = game_menus::inv::titled_filter_menu( filter, *you, _( "Cut up what?" ) );
     }
     if( !loc ) {
         p->add_msg_if_player( m_info, _( "You don't have that item!" ) );
         return std::nullopt;
     }
     p->i_rem( &*loc );
     cut_log_into_planks( *p );
     return 1;
 }
References _, Character::add_msg_if_player(), Creature::as_avatar(), Character::cant_do_mounted(), cut_log_into_planks(), debugmsg, filter, get_map(), map::i_at(), Character::i_rem(), map::i_rem(), itype_log, m_info, Creature::pos(), string_id< T >::str(), game_menus::inv::titled_filter_menu(), and item::typeId().
Referenced by Item_factory::init().
lux_meter()
std::optional< int > iuse::lux_meter (Character * p, item * it, const tripoint & pos)
Definition at line 7870 of file iuse.cpp.
 {
     p->add_msg_if_player( m_neutral, _( "The illumination is %.1f." ),
                           g->natural_light_level( pos.z ) );
     return it->type->charges_to_use();
 }
References _, Character::add_msg_if_player(), itype::charges_to_use(), g, m_neutral, math_opers::pos(), and item::type.
Referenced by Item_factory::init().
ma_manual()
std::optional< int > iuse::ma_manual (Character * p, item * it, const tripoint &)
Definition at line 2692 of file iuse.cpp.
 {
     // [CR] - should NPCs just be allowed to learn this stuff? Just like that?
     const matype_id style_to_learn = martial_art_learned_from( *it->type );
     if( !style_to_learn.is_valid() ) {
         debugmsg( "ERROR: Invalid martial art" );
         return std::nullopt;
     }
     p->martial_arts_data->learn_style( style_to_learn, p->is_avatar() );
     return 1;
 }
References debugmsg, Creature::is_avatar(), string_id< T >::is_valid(), martial_art_learned_from(), Character::martial_arts_data, and item::type.
Referenced by Item_factory::init().
mace()
std::optional< int > iuse::mace (Character * p, item * it, const tripoint &)
Definition at line 2295 of file iuse.cpp.
 {
     if( !it->ammo_sufficient( p ) ) {
         return std::nullopt;
     }
     // If anyone other than the player wants to use one of these,
     // they're going to need to figure out how to aim it.
     const std::optional<tripoint> dest_ = choose_adjacent( _( "Spray where?" ) );
     if( !dest_ ) {
         return std::nullopt;
     }
     tripoint dest = *dest_;
     p->mod_moves( -to_moves<int>( 2_seconds ) );
     map &here = get_map();
     here.add_field( dest, fd_tear_gas, 2, 3_turns );
     // Also spray monsters in that tile.
     if( monster *const mon_ptr = get_creature_tracker().creature_at<monster>( dest, true ) ) {
         monster &critter = *mon_ptr;
         critter.mod_moves( -to_moves<int>( 2_seconds ) );
         bool blind = false;
         if( one_in( 2 ) && critter.has_flag( mon_flag_SEES ) ) {
             blind = true;
             critter.add_effect( effect_blind, rng( 1_minutes, 2_minutes ) );
         }
         // even if it's not blinded getting maced hurts a lot and stuns it
         if( !critter.has_flag( mon_flag_NO_BREATHE ) ) {
             critter.mod_moves( -to_moves<int>( 3_seconds ) );
             p->add_msg_if_player( _( "The %s recoils in pain!" ), critter.name() );
         }
         viewer &player_view = get_player_view();
         if( player_view.sees( critter ) ) {
             p->add_msg_if_player( _( "The %s is sprayed!" ), critter.name() );
             if( blind ) {
                 p->add_msg_if_player( _( "The %s looks blinded." ), critter.name() );
             }
         }
     }
     return 1;
 }
References _, Creature::add_effect(), map::add_field(), Character::add_msg_if_player(), item::ammo_sufficient(), choose_adjacent(), effect_blind, fd_tear_gas, get_creature_tracker(), get_map(), get_player_view(), monster::has_flag(), Creature::mod_moves(), mon_flag_NO_BREATHE, mon_flag_SEES, monster::name(), one_in(), rng(), and viewer::sees().
Referenced by Item_factory::init().
magic_8_ball()
std::optional< int > iuse::magic_8_ball (Character * p, item * it, const tripoint &)
Definition at line 8450 of file iuse.cpp.
 {
     p->add_msg_if_player( m_info, _( "You ask the %s, then flip it." ), it->tname() );
     int rn = rng( 0, 3 );
     std::string msg_category;
     game_message_type color;
     if( rn == 0 ) {
         msg_category = "magic_8ball_bad";
         color = m_bad;
     } else if( rn == 1 ) {
         msg_category = "magic_8ball_unknown";
         color = m_info;
     } else {
         msg_category = "magic_8ball_good";
         color = m_good;
     }
     p->add_msg_if_player( color, _( "The %s says: %s" ), it->tname(),
                           SNIPPET.random_from_category( msg_category ).value_or( translation() ) );
     return 0;
 }
References _, Character::add_msg_if_player(), item::color(), m_bad, m_good, m_info, snippet_library::random_from_category(), rng(), SNIPPET, and item::tname().
Referenced by Item_factory::init().
makemound()
std::optional< int > iuse::makemound (Character * p, item * it, const tripoint &)
Definition at line 2795 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action makemound that requires character but no character is present",
                   it->typeId().str() );
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     const std::optional<tripoint> pnt_ = choose_adjacent( _( "Till soil where?" ) );
     if( !pnt_ ) {
         return std::nullopt;
     }
     const tripoint pnt = *pnt_;
     if( pnt == p->pos() ) {
         p->add_msg_if_player( m_info,
                               _( "You think about jumping on a shovel, but then change your mind." ) );
         return std::nullopt;
     }
     map &here = get_map();
     if( here.has_flag( ter_furn_flag::TFLAG_PLOWABLE, pnt ) &&
         !here.has_flag( ter_furn_flag::TFLAG_PLANT, pnt ) ) {
         p->add_msg_if_player( _( "You start churning up the earth here." ) );
         p->assign_activity( churn_activity_actor( 18000, item_location( *p, it ) ) );
         p->activity.placement = here.getglobal( pnt );
         return 1;
     } else {
         p->add_msg_if_player( _( "You can't churn up this ground." ) );
         return std::nullopt;
     }
 }
References _, Character::activity, Character::add_msg_if_player(), Character::assign_activity(), Character::cant_do_mounted(), choose_adjacent(), debugmsg, get_map(), map::getglobal(), map::has_flag(), m_info, player_activity::placement, Creature::pos(), string_id< T >::str(), TFLAG_PLANT, TFLAG_PLOWABLE, and item::typeId().
Referenced by Item_factory::init().
manage_exosuit()
std::optional< int > iuse::manage_exosuit (Character * p, item * it, const tripoint &)
Definition at line 2339 of file iuse.cpp.
 {
     if( !p->is_avatar() ) {
         return std::nullopt;
     }
     if( it->get_all_contained_pockets().empty() ) {
         add_msg( m_warning, _( "Your %s does not have any pockets to contain modules." ), it->tname() );
         return std::nullopt;
     }
     p->mod_moves( -exosuit_interact::run( it ) );
     return 0;
 }
References _, add_msg(), item::get_all_contained_pockets(), Creature::is_avatar(), m_warning, Creature::mod_moves(), exosuit_interact::run(), and item::tname().
Referenced by Item_factory::init().
marloss()
std::optional< int > iuse::marloss (Character * p, item * it, const tripoint &)
Definition at line 1383 of file iuse.cpp.
 {
     if( marloss_prevented( *p ) ) {
         return std::nullopt;
     }
     get_event_bus().send<event_type::consumes_marloss_item>( p->getID(), it->typeId() );
     marloss_common( *p, *it, trait_MARLOSS );
     return 1;
 }
References consumes_marloss_item, get_event_bus(), Character::getID(), marloss_common(), marloss_prevented(), event_bus::send(), trait_MARLOSS, and item::typeId().
Referenced by Item_factory::init().
marloss_gel()
std::optional< int > iuse::marloss_gel (Character * p, item * it, const tripoint &)
Definition at line 1412 of file iuse.cpp.
 {
     if( marloss_prevented( *p ) ) {
         return std::nullopt;
     }
     get_event_bus().send<event_type::consumes_marloss_item>( p->getID(), it->typeId() );
     marloss_common( *p, *it, trait_MARLOSS_YELLOW );
     return 1;
 }
References consumes_marloss_item, get_event_bus(), Character::getID(), marloss_common(), marloss_prevented(), event_bus::send(), trait_MARLOSS_YELLOW, and item::typeId().
Referenced by Item_factory::init().
marloss_seed()
std::optional< int > iuse::marloss_seed (Character * p, item * it, const tripoint &)
Definition at line 1395 of file iuse.cpp.
 {
     if( !query_yn( _( "Are you sure you want to eat the %s?  You could plant it in a mound of dirt." ),
                    colorize( it->tname(), it->color_in_inventory() ) ) ) {
         return std::nullopt; // Save the seed for later!
     }
     if( marloss_prevented( *p ) ) {
         return std::nullopt;
     }
     get_event_bus().send<event_type::consumes_marloss_item>( p->getID(), it->typeId() );
     marloss_common( *p, *it, trait_MARLOSS_BLUE );
     return 1;
 }
References _, item::color_in_inventory(), colorize(), consumes_marloss_item, get_event_bus(), Character::getID(), marloss_common(), marloss_prevented(), query_yn(), event_bus::send(), item::tname(), trait_MARLOSS_BLUE, and item::typeId().
Referenced by Item_factory::init().
measure_resonance()
std::optional< int > iuse::measure_resonance (Character * p, item * it, const tripoint &)
Definition at line 8471 of file iuse.cpp.
 {
     if( !it->ammo_sufficient( p ) ) {
         popup( _( "The device doesn't have enough power to function!" ) );
         return std::nullopt;
     }
     // Get a list of resonant artifacts to show the player.
     std::vector<uilist_entry> uile;
     std::vector<item_location> artifacts;
     int i = 0;
     for( const item_location &item_loc : p->all_items_loc() ) {
         const item *tested_item = item_loc.get_item();
         if( !tested_item->get_proc_enchantments().empty() ) {
             // We've found an item with an enchantment. This doesn't guarantee it is an artifact! Prune the list to only items with resonance
             bool is_resonant_artifact = false;
             for( enchant_cache &maybe_artifact : tested_item->get_proc_enchantments() ) {
                 if( maybe_artifact.get_value_add( enchant_vals::mod::ARTIFACT_RESONANCE ) ) {
                     // Found an artifact with resonance!
                     is_resonant_artifact = true;
                 }
             }
             if( is_resonant_artifact ) {
                 // Return tname, should handle renamed artifacts?
                 uilist_entry entry( i, true, i + 49, item_loc.get_item()->tname() );
                 uile.emplace_back( entry );
                 artifacts.emplace_back( item_loc );
                 i++;
             }
         }
     }
     if( artifacts.empty() ) {
         popup( _( "The device indicates none of the items on your person resonate with registered nether phenomena." ) );
         // Explicitly no cost for passive detection
         return std::nullopt;
     }
     int choice = 0;
     choice = uilist( _( "The device found these items have resonant properties.\nChoose one to scan." ),
                      uile );
     if( choice < 0 || static_cast<size_t>( choice ) >= artifacts.size() ) {
         // Player exited menu. No cost, return early.
         return std::nullopt;
     }
     popup( _( "Calculating." ) );
     popup( _( "Calculating" ) );
     int actual_resonance = 0;
     // Add up the resonance of all the enchantments on the selected item to get the item's total resonance
     for( enchant_cache &this_ench : artifacts.at( choice ).get_item()->get_proc_enchantments() ) {
         actual_resonance += this_ench.get_value_add( enchant_vals::mod::ARTIFACT_RESONANCE );
     }
     // Random 15% +- on the detection, no freebies here.
     int resonance_offset_low = 0.85 * actual_resonance;
     int resonance_offset_high = 1.15 * actual_resonance;
     int detected_resonance = rng( resonance_offset_low, resonance_offset_high );
     // Different messages for different resonance levels? Dangerous resonance levels are in suffer::from_artifact_resonance
     popup( _( "Detected resonance approximately equal to %i units." ), detected_resonance );
     p->consume_charges( *it, it->type->charges_to_use() );
     p->mod_moves( -to_moves<int>( 2_minutes ) );
     return 0;
 }
References _, Character::all_items_loc(), item::ammo_sufficient(), enchant_vals::ARTIFACT_RESONANCE, itype::charges_to_use(), Character::consume_charges(), item::get_proc_enchantments(), Creature::mod_moves(), popup(), rng(), and item::type.
Referenced by Item_factory::init().
meditate()
std::optional< int > iuse::meditate (Character * p, item * it, const tripoint &)
Definition at line 929 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action meditate that requires character but no character is present",
                   it->typeId().str() );
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     if( p->has_trait( trait_SPIRITUAL ) ) {
         p->assign_activity( meditate_activity_actor() );
     } else {
         p->add_msg_if_player( _( "This %s probably meant a lot to someone at one time." ),
                               it->tname() );
     }
     return 1;
 }
References _, Character::add_msg_if_player(), Character::assign_activity(), Character::cant_do_mounted(), debugmsg, Character::has_trait(), string_id< T >::str(), item::tname(), trait_SPIRITUAL, and item::typeId().
Referenced by Item_factory::init().
melatonin_tablet()
std::optional< int > iuse::melatonin_tablet (Character * p, item * it, const tripoint &)
Definition at line 8384 of file iuse.cpp.
 {
     p->add_msg_if_player( _( "You pop a %s." ), it->tname() );
     if( p->has_effect( effect_melatonin ) ) {
         p->add_msg_if_player( m_warning,
                               _( "Simply taking more melatonin won't help.  You have to go to sleep for it to work." ) );
     }
     p->add_effect( effect_melatonin, 16_hours );
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), effect_melatonin, Creature::has_effect(), m_warning, and item::tname().
meth()
std::optional< int > iuse::meth (Character * p, item * , const tripoint &)
Strength reduces duration of meth Maximum Strength >4 experiences less hunger benefit from meth
Definition at line 850 of file iuse.cpp.
 {
     /** @EFFECT_STR reduces duration of meth */
     time_duration duration = 1_minutes * ( 60 - p->str_cur );
     if( p->has_amount( itype_apparatus, 1 ) && p->use_charges_if_avail( itype_fire, 1 ) ) {
         p->add_msg_if_player( m_neutral, _( "You smoke your meth." ) );
         p->add_msg_if_player( m_good, _( "The world seems to sharpen." ) );
         p->mod_sleepiness( -375 );
         if( p->has_trait( trait_TOLERANCE ) ) {
             duration *= 1.2;
         } else {
             duration *= ( p->has_trait( trait_LIGHTWEIGHT ) ? 1.8 : 1.5 );
         }
         map &here = get_map();
         // breathe out some smoke
         for( int i = 0; i < 3; i++ ) {
             point offset( rng( -2, 2 ), rng( -2, 2 ) );
             here.add_field( p->pos_bub() + offset, field_type_id( "fd_methsmoke" ), 2 );
         }
     } else {
         p->add_msg_if_player( _( "You snort some crystal meth." ) );
         p->mod_sleepiness( -300 );
     }
     if( !p->has_effect( effect_meth ) ) {
         duration += 1_hours;
     }
     if( duration > 0_turns ) {
         // meth actually inhibits hunger, weaker characters benefit more
         /** @EFFECT_STR_MAX >4 experiences less hunger benefit from meth */
         int hungerpen = p->str_max < 5 ? 35 : 40 - ( 2 * p->str_max );
         if( hungerpen > 0 ) {
             p->mod_hunger( -hungerpen );
         }
         p->add_effect( effect_meth, duration );
     }
     return 1;
 }
References _, Creature::add_effect(), map::add_field(), Character::add_msg_if_player(), effect_meth, get_map(), visitable::has_amount(), Creature::has_effect(), Character::has_trait(), itype_apparatus, itype_fire, m_good, m_neutral, Character::mod_hunger(), Character::mod_sleepiness(), Creature::pos_bub(), rng(), Character::str_cur, Character::str_max, trait_LIGHTWEIGHT, trait_TOLERANCE, and Character::use_charges_if_avail().
Referenced by Item_factory::init().
mininuke()
std::optional< int > iuse::mininuke (Character * p, item * it, const tripoint &)
Definition at line 3544 of file iuse.cpp.
 {
     int time;
     bool got_value = query_int( time, _( "Set the timer to ___ turns (0 to cancel)?" ) );
     if( !got_value || time <= 0 ) {
         p->add_msg_if_player( _( "Never mind." ) );
         return std::nullopt;
     }
     p->add_msg_if_player( _( "You set the timer to %s." ),
                           to_string( time_duration::from_turns( time ) ) );
     get_event_bus().send<event_type::activates_mininuke>( p->getID() );
     it->convert( itype_mininuke_act, p );
     it->countdown_point = calendar::turn + time_duration::from_seconds( time );
     it->active = true;
     return 1;
 }
References _, activates_mininuke, item::active, Character::add_msg_if_player(), item::convert(), item::countdown_point, time_duration::from_seconds(), time_duration::from_turns(), get_event_bus(), Character::getID(), itype_mininuke_act, query_int(), event_bus::send(), to_string(), and calendar::turn.
Referenced by Item_factory::init(), and explosion_handler::nuke().
molotov_lit()
std::optional< int > iuse::molotov_lit (Character * p, item * it, const tripoint & pos)
Definition at line 3464 of file iuse.cpp.
 {
     if( !p ) {
         // It was thrown or dropped, so burst into flames
         map &here = get_map();
         for( const tripoint &pt : here.points_in_radius( pos, 1, 0 ) ) {
             const int intensity = 1 + one_in( 3 ) + one_in( 5 );
             here.add_field( pt, fd_fire, intensity );
         }
         avatar &player = get_avatar();
         if( player.has_trait( trait_PYROMANIA ) && player.sees( pos ) ) {
             player.add_morale( MORALE_PYROMANIA_STARTFIRE, 15, 15, 8_hours, 6_hours );
             player.rem_morale( MORALE_PYROMANIA_NOFIRE );
             add_msg( m_good, _( "Fire  Good" ) );
         }
         return 1;
     }
     // 20% chance of going out harmlessly.
     if( one_in( 5 ) ) {
         p->add_msg_if_player( _( "Your lit Molotov goes out." ) );
         it->convert( itype_molotov, p ).active = false;
     }
     return 0;
 }
References _, item::active, map::add_field(), add_msg(), Character::add_msg_if_player(), item::convert(), fd_fire, get_avatar(), get_map(), intensity, itype_molotov, m_good, MORALE_PYROMANIA_NOFIRE, MORALE_PYROMANIA_STARTFIRE, one_in(), player, map::points_in_radius(), math_opers::pos(), and trait_PYROMANIA.
Referenced by Item_factory::init().
mop()
std::optional< int > iuse::mop (Character * p, item * , const tripoint &)
Definition at line 4765 of file iuse.cpp.
 {
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     map &here = get_map();
     const std::function<bool( const tripoint & )> f = [&here]( const tripoint & pnt ) {
         // TODO: fix point types
         return here.terrain_moppable( tripoint_bub_ms( pnt ) );
     };
     const std::optional<tripoint> pnt_ = choose_adjacent_highlight(
             _( "Mop where?" ), _( "There is nothing to mop nearby." ), f, false );
     if( !pnt_ ) {
         return std::nullopt;
     }
     // TODO: fix point types
     const tripoint_bub_ms pnt( *pnt_ );
     // TODO: fix point types
     if( !f( pnt.raw() ) ) {
         if( pnt == p->pos_bub() ) {
             p->add_msg_if_player( m_info, _( "You mop yourself up." ) );
             p->add_msg_if_player( m_info, _( "The universe implodes and reforms around you." ) );
         } else {
             p->add_msg_if_player( m_bad, _( "There's nothing to mop there." ) );
         }
         return std::nullopt;
     }
     if( p->is_blind() ) {
         p->add_msg_if_player( m_info, _( "You move the mop around, unsure whether it's doing any good." ) );
         p->mod_moves( -to_moves<int>( 1_seconds ) * 0.15 );
         if( one_in( 3 ) ) {
             here.mop_spills( pnt );
         }
     } else if( here.mop_spills( pnt ) ) {
         p->add_msg_if_player( m_info, _( "You mop up the spill." ) );
         p->mod_moves( -to_moves<int>( 1_seconds ) * 0.15 );
     } else {
         return std::nullopt;
     }
     return 1;
 }
References _, Character::add_msg_if_player(), Character::cant_do_mounted(), choose_adjacent_highlight(), get_map(), Character::is_blind(), m_bad, m_info, Creature::mod_moves(), map::mop_spills(), one_in(), Creature::pos_bub(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), and map::terrain_moppable().
Referenced by Item_factory::init().
mp3()
std::optional< int > iuse::mp3 (Character * p, item * it, const tripoint &)
Definition at line 3718 of file iuse.cpp.
 {
     // TODO: avoid item id hardcoding to make this function usable for pure json-defined devices.
     if( !it->ammo_sufficient( p ) ) {
         p->add_msg_if_player( m_info, _( "The device's batteries are dead." ) );
     } else if( p->has_active_item( itype_mp3_on ) || p->has_active_item( itype_smartphone_music ) ||
                p->has_active_item( itype_afs_atomic_smartphone_music ) ||
                p->has_active_item( itype_afs_atomic_wraitheon_music ) ) {
         p->add_msg_if_player( m_info, _( "You are already listening to music!" ) );
     } else {
         p->add_msg_if_player( m_info, _( "You put in the earbuds and start listening to music." ) );
         if( it->typeId() == itype_mp3 ) {
             it->convert( itype_mp3_on, p ).active = true;
         } else if( it->typeId() == itype_smart_phone ) {
             it->convert( itype_smartphone_music, p ).active = true;
         } else if( it->typeId() == itype_afs_atomic_smartphone ) {
             it->convert( itype_afs_atomic_smartphone_music, p ).active = true;
         } else if( it->typeId() == itype_afs_wraitheon_smartphone ) {
             it->convert( itype_afs_atomic_wraitheon_music, p ).active = true;
         }
         p->mod_moves( -200 );
     }
     return 1;
 }
References _, item::active, Character::add_msg_if_player(), item::ammo_sufficient(), item::convert(), Character::has_active_item(), itype_afs_atomic_smartphone, itype_afs_atomic_smartphone_music, itype_afs_atomic_wraitheon_music, itype_afs_wraitheon_smartphone, itype_mp3, itype_mp3_on, itype_smart_phone, itype_smartphone_music, m_info, Creature::mod_moves(), and item::typeId().
Referenced by Item_factory::init().
mp3_deactivate()
std::optional< int > iuse::mp3_deactivate (Character * p, item * it, const tripoint &)
Definition at line 3816 of file iuse.cpp.
 {
     if( it->typeId() == itype_mp3_on ) {
         p->add_msg_if_player( _( "The mp3 player turns off." ) );
         it->convert( itype_mp3, p ).active = false;
     } else if( it->typeId() == itype_smartphone_music ) {
         p->add_msg_if_player( _( "The phone turns off." ) );
         it->convert( itype_smart_phone, p ).active = false;
     } else if( it->typeId() == itype_afs_atomic_smartphone_music ) {
         p->add_msg_if_player( _( "The phone turns off." ) );
         it->convert( itype_afs_atomic_smartphone, p ).active = false;
     } else if( it->typeId() == itype_afs_atomic_wraitheon_music ) {
         p->add_msg_if_player( _( "The phone turns off." ) );
         it->convert( itype_afs_wraitheon_smartphone, p ).active = false;
     }
     p->mod_moves( -200 );
     music::deactivate_music_id( music::music_id::mp3 );
     return 0;
 }
References _, item::active, Character::add_msg_if_player(), item::convert(), music::deactivate_music_id(), itype_afs_atomic_smartphone, itype_afs_atomic_smartphone_music, itype_afs_atomic_wraitheon_music, itype_afs_wraitheon_smartphone, itype_mp3, itype_mp3_on, itype_smart_phone, itype_smartphone_music, Creature::mod_moves(), music::mp3, and item::typeId().
Referenced by Item_factory::init().
mp3_on()
std::optional< int > iuse::mp3_on (Character * p, item * , const tripoint & pos)
Definition at line 3808 of file iuse.cpp.
 {
     // mp3 player in inventory, we can listen
     play_music( p, pos, 0, 20 );
     music::activate_music_id( music::music_id::mp3 );
     return 1;
 }
References music::activate_music_id(), music::mp3, play_music(), and math_opers::pos().
Referenced by Item_factory::init().
multicooker()
std::optional< int > iuse::multicooker (Character * p, item * it, const tripoint & pos)
Electronics >3 allows multicooker upgrade Fabrication >3 allows multicooker upgrade Intelligence increases chance to successfully upgrade multi-cooker Electronics increases chance to successfully upgrade multi-cooker Fabrication increases chance to successfully upgrade multi-cooker
Definition at line 7431 of file iuse.cpp.
 {
     static const int charges_to_start = 50;
     const int charge_buffer = 2;
     enum {
         mc_start, mc_stop, mc_take, mc_upgrade, mc_empty
     };
     if( p->cant_do_underwater() ) {
         return std::nullopt;
     }
     if( p->has_trait( trait_ILLITERATE ) ) {
         p->add_msg_if_player( m_info,
                               _( "You can't read, and don't understand the screen or the buttons!" ) );
         return std::nullopt;
     }
     if( p->has_effect( effect_hallu ) || p->has_effect( effect_visuals ) ) {
         if( multicooker_hallu( *p ) ) {
             return 0;
         }
     }
     if( p->has_flag( json_flag_HYPEROPIC ) && !p->worn_with_flag( flag_FIX_FARSIGHT ) &&
         !p->has_effect( effect_contacts ) && !p->has_effect( effect_transition_contacts ) ) {
         p->add_msg_if_player( m_info,
                               _( "You'll need to put on reading glasses before you can see the screen." ) );
         return std::nullopt;
     }
     uilist menu;
     menu.text = _( "Welcome to the RobotChef3000.  Choose option:" );
     item *dish_it = it->get_item_with(
     []( const item & it ) {
         return !( it.is_toolmod() || it.is_magazine() );
     } );
     if( it->active ) {
         menu.addentry( mc_stop, true, 's', _( "Stop cooking" ) );
     } else {
         if( dish_it == nullptr ) {
             if( it->ammo_remaining( p, true ) < charges_to_start ) {
                 p->add_msg_if_player( _( "Batteries are low." ) );
                 return 0;
             }
             menu.addentry( mc_start, true, 's', _( "Start cooking" ) );
             /** @EFFECT_ELECTRONICS >3 allows multicooker upgrade */
             /** @EFFECT_FABRICATION >3 allows multicooker upgrade */
             if( p->get_skill_level( skill_electronics ) >= 4 && p->get_skill_level( skill_fabrication ) >= 4 ) {
                 const std::string upgr = it->get_var( "MULTI_COOK_UPGRADE" );
                 if( upgr.empty() ) {
                     menu.addentry( mc_upgrade, true, 'u', _( "Upgrade multi-cooker" ) );
                 } else {
                     if( upgr == "UPGRADE" ) {
                         menu.addentry( mc_upgrade, false, 'u', _( "Multi-cooker already upgraded" ) );
                     } else {
                         menu.addentry( mc_upgrade, false, 'u', _( "Multi-cooker unable to upgrade" ) );
                     }
                 }
             }
         } else {
             // Something other than a recipe item might be stored in the pocket.
             if( dish_it->typeId().str() == it->get_var( "DISH" ) ) {
                 menu.addentry( mc_take, true, 't', _( "Take out dish" ) );
             } else {
                 menu.addentry( mc_empty, true, 't',
                                _( "Obstruction detected.  Please remove any items lodged in the multi-cooker." ) );
             }
         }
     }
     menu.query();
     int choice = menu.ret;
     if( choice < 0 ) {
         return std::nullopt;
     }
     if( mc_stop == choice ) {
         if( query_yn( _( "Really stop cooking?" ) ) ) {
             it->active = false;
             it->erase_var( "DISH" );
             it->erase_var( "COOKTIME" );
             it->erase_var( "RECIPE" );
             it->convert( itype_multi_cooker, p );
         }
         return 0;
     }
     if( mc_take == choice ) {
         item &dish = *dish_it;
         if( dish.has_flag( flag_FROZEN ) ) {
             dish.cold_up();  //don't know how to check if the dish is frozen liquid and prevent extraction of it into inventory...
         }
         const std::string dish_name = dish.tname( dish.charges, false );
         const bool is_delicious = dish.has_flag( flag_HOT ) && dish.has_flag( flag_EATEN_HOT );
         if( dish.made_of( phase_id::LIQUID ) ) {
             if( !p->check_eligible_containers_for_crafting( *recipe_id( it->get_var( "RECIPE" ) ), 1 ) ) {
                 p->add_msg_if_player( m_info, _( "You don't have a suitable container to store your %s." ),
                                       dish_name );
                 return 0;
             }
             liquid_handler::handle_all_liquid( dish, PICKUP_RANGE );
         } else {
             p->i_add( dish );
         }
         it->remove_item( *dish_it );
         it->erase_var( "RECIPE" );
         if( is_delicious ) {
             p->add_msg_if_player( m_good,
                                   _( "You got the dish from the multi-cooker.  The %s smells delicious." ),
                                   dish_name );
         } else {
             p->add_msg_if_player( m_good, _( "You got the %s from the multi-cooker." ),
                                   dish_name );
         }
         return 0;
     }
     // Do nothing if there's non-dish contained in the cooker
     if( mc_empty == choice ) {
         return std::nullopt;
     }
     if( mc_start == choice ) {
         uilist dmenu;
         dmenu.text = _( "Choose desired meal:" );
         std::vector<const recipe *> dishes;
         inventory crafting_inv = p->crafting_inventory();
         // add some tools and qualities. we can't add this qualities to
         // json, because multicook must be used only by activating, not as
         // component other crafts.
         crafting_inv.push_back( item( "hotplate", calendar::turn_zero ) ); //hotplate inside
         // some recipes requires tongs
         crafting_inv.push_back( item( "tongs", calendar::turn_zero ) );
         // toolset with CUT and other qualities inside
         crafting_inv.push_back( item( "toolset", calendar::turn_zero ) );
         // good COOK, BOIL, CONTAIN qualities inside
         crafting_inv.push_back( item( "pot", calendar::turn_zero ) );
         int counter = 0;
         static const std::set<std::string> multicooked_subcats = { "CSC_FOOD_MEAT", "CSC_FOOD_VEGGI", "CSC_FOOD_PASTA" };
         for( const recipe * const &r : get_avatar().get_learned_recipes().in_category( "CC_FOOD" ) ) {
             if( multicooked_subcats.count( r->subcategory ) > 0 ) {
                 dishes.push_back( r );
                 const bool can_make = r->deduped_requirements().can_make_with_inventory(
                                           crafting_inv, r->get_component_filter() );
                 dmenu.addentry( counter++, can_make, -1, r->result_name( /*decorated=*/true ) );
             }
         }
         dmenu.query();
         int choice = dmenu.ret;
         if( choice < 0 ) {
             return std::nullopt;
         } else {
             const recipe *meal = dishes[choice];
             int mealtime;
             if( it->get_var( "MULTI_COOK_UPGRADE" ) == "UPGRADE" ) {
                 mealtime = meal->time_to_craft_moves( *p, recipe_time_flag::ignore_proficiencies );
             } else {
                 mealtime = meal->time_to_craft_moves( *p, recipe_time_flag::ignore_proficiencies ) * 2;
             }
             const int all_charges = charges_to_start + mealtime / 1000 * units::to_watt(
                                         it->type->tool->power_draw ) / 1000;
             if( it->ammo_remaining( p, true ) < all_charges ) {
                 p->add_msg_if_player( m_warning,
                                       _( "The multi-cooker needs %d charges to cook this dish." ),
                                       all_charges );
                 return std::nullopt;
             }
             const auto filter = is_crafting_component;
             const requirement_data *reqs =
                 meal->deduped_requirements().select_alternative( *p, crafting_inv, filter );
             if( !reqs ) {
                 return std::nullopt;
             }
             for( const auto &component : reqs->get_components() ) {
                 p->consume_items( component, 1, filter );
             }
             it->set_var( "RECIPE", meal->ident().str() );
             it->set_var( "DISH", meal->result().str() );
             it->set_var( "COOKTIME", mealtime );
             p->add_msg_if_player( m_good,
                                   _( "The screen flashes blue symbols and scales as the multi-cooker begins to shake." ) );
             it->convert( itype_multi_cooker_filled, p ).active = true;
             it->ammo_consume( charges_to_start - charge_buffer, pos, p );
             p->practice( skill_cooking, meal->difficulty * 3 ); //little bonus
             return 0;
         }
     }
     if( mc_upgrade == choice ) {
         if( !p->has_morale_to_craft() ) {
             p->add_msg_if_player( m_info, _( "Your morale is too low to craft" ) );
             return std::nullopt;
         }
         bool has_tools = true;
         const inventory &cinv = p->crafting_inventory();
         if( !cinv.has_amount( itype_soldering_iron, 1 ) ) {
             p->add_msg_if_player( m_warning, _( "You need a %s." ),
                                   item::nname( itype_soldering_iron ) );
             has_tools = false;
         }
         if( !cinv.has_quality( qual_SCREW_FINE ) ) {
             p->add_msg_if_player( m_warning, _( "You need an item with %s of 1 or more to upgrade this." ),
                                   qual_SCREW_FINE.obj().name );
             has_tools = false;
         }
         if( !has_tools ) {
             return std::nullopt;
         }
         p->practice( skill_electronics, rng( 5, 10 ) );
         p->practice( skill_fabrication, rng( 5, 10 ) );
         p->mod_moves( -to_moves<int>( 7_seconds ) );
         /** @EFFECT_INT increases chance to successfully upgrade multi-cooker */
         /** @EFFECT_ELECTRONICS increases chance to successfully upgrade multi-cooker */
         /** @EFFECT_FABRICATION increases chance to successfully upgrade multi-cooker */
         if( p->get_skill_level( skill_electronics ) + p->get_skill_level( skill_fabrication ) + p->int_cur >
             rng( 20, 35 ) ) {
             p->practice( skill_electronics, rng( 5, 20 ) );
             p->practice( skill_fabrication, rng( 5, 20 ) );
             p->add_msg_if_player( m_good,
                                   _( "You've successfully upgraded the multi-cooker, master tinkerer!  Now it cooks faster!" ) );
             it->set_var( "MULTI_COOK_UPGRADE", "UPGRADE" );
             return 0;
         } else {
             if( !one_in( 5 ) ) {
                 p->add_msg_if_player( m_neutral,
                                       _( "You sagely examine and analyze the multi-cooker, but don't manage to accomplish anything." ) );
             } else {
                 p->add_msg_if_player( m_bad,
                                       _( "Your tinkering nearly breaks the multi-cooker!  Fortunately, it still works, but best to stop messing with it." ) );
                 it->set_var( "MULTI_COOK_UPGRADE", "DAMAGED" );
             }
             return 0;
         }
     }
     return 0;
 }
References _, item::active, Character::add_msg_if_player(), uilist::addentry(), item::ammo_consume(), item::ammo_remaining(), Creature::cant_do_underwater(), item::charges, Character::check_eligible_containers_for_crafting(), item::cold_up(), Character::consume_items(), item::convert(), Character::crafting_inventory(), recipe::deduped_requirements(), recipe::difficulty, effect_contacts, effect_hallu, effect_transition_contacts, effect_visuals, item::erase_var(), filter, flag_EATEN_HOT, flag_FIX_FARSIGHT, flag_FROZEN, flag_HOT, get_avatar(), requirement_data::get_components(), item::get_item_with(), Character::get_skill_level(), item::get_var(), liquid_handler::handle_all_liquid(), visitable::has_amount(), Creature::has_effect(), item::has_flag(), Character::has_flag(), Character::has_morale_to_craft(), inventory::has_quality(), read_only_visitable::has_tools(), Character::has_trait(), Character::i_add(), recipe::ident(), ignore_proficiencies, Character::int_cur, is_crafting_component(), item::is_magazine(), item::is_toolmod(), item::item(), itype_multi_cooker, itype_multi_cooker_filled, itype_soldering_iron, json_flag_HYPEROPIC, LIQUID, m_bad, m_good, m_info, m_neutral, m_warning, item::made_of(), Creature::mod_moves(), multicooker_hallu(), quality::name, item::nname(), string_id< T >::obj(), one_in(), PICKUP_RANGE, math_opers::pos(), Character::practice(), inventory::push_back(), qual_SCREW_FINE, uilist::query(), query_yn(), visitable::remove_item(), recipe::result(), uilist::ret, rng(), deduped_requirement_data::select_alternative(), item::set_var(), skill_cooking, skill_electronics, skill_fabrication, string_id< T >::str(), uilist::text, recipe::time_to_craft_moves(), item::tname(), units::to_watt(), itype::tool, trait_ILLITERATE, calendar::turn_zero, item::type, item::typeId(), and Character::worn_with_flag().
Referenced by Item_factory::init().
multicooker_tick()
std::optional< int > iuse::multicooker_tick (Character * p, item * it, const tripoint & pos)
Intelligence increases chance of checking multi-cooker on time Survival increases chance of checking multi-cooker on time
Definition at line 7718 of file iuse.cpp.
 {
     const int charge_buffer = 2;
     //stop action before power runs out and iuse deletes the cooker
     if( it->ammo_remaining( p, true ) < charge_buffer ) {
         it->active = false;
         it->erase_var( "RECIPE" );
         it->convert( itype_multi_cooker, p );
         //drain the buffer amount given at activation
         it->ammo_consume( charge_buffer, pos, p );
         p->add_msg_if_player( m_info,
                               _( "Batteries low, entering standby mode.  With a low buzzing sound the multi-cooker shuts down." ) );
         return 0;
     }
     int cooktime = it->get_var( "COOKTIME", 0 );
     cooktime -= 100;
     if( cooktime >= 300 && cooktime < 400 ) {
         //Smart or good cook or careful
         /** @EFFECT_INT increases chance of checking multi-cooker on time */
         /** @EFFECT_SURVIVAL increases chance of checking multi-cooker on time */
         avatar &player = get_avatar();
         if( player.int_cur + player.get_skill_level( skill_cooking ) + player.get_skill_level(
                 skill_survival ) > 16 ) {
             add_msg( m_info, _( "The multi-cooker should be finishing shortly" ) );
         }
     }
     if( cooktime <= 0 ) {
         item meal( it->get_var( "DISH" ), time_point( calendar::turn ), 1 );
         if( ( *recipe_id( it->get_var( "RECIPE" ) ) ).hot_result() ) {
             meal.heat_up();
         } else {
             meal.set_item_temperature( std::max( temperatures::cold,
                                                  get_weather().get_temperature( pos ) ) );
         }
         it->active = false;
         it->erase_var( "COOKTIME" );
         it->convert( itype_multi_cooker, p );
         if( it->can_contain( meal ).success() ) {
             it->put_in( meal, pocket_type::CONTAINER );
         } else {
             add_msg( m_info,
                      _( "Obstruction detected.  Please remove any items lodged in the multi-cooker." ) );
             return 0;
         }
         //~ sound of a multi-cooker finishing its cycle!
         sounds::sound( pos, 8, sounds::sound_t::alarm, _( "ding!" ), true, "misc", "ding" );
         return 0;
     } else {
         it->set_var( "COOKTIME", cooktime );
         return 0;
     }
     return 0;
 }
References _, item::active, add_msg(), Character::add_msg_if_player(), sounds::alarm, item::ammo_consume(), item::ammo_remaining(), item::can_contain(), temperatures::cold, CONTAINER, item::convert(), item::erase_var(), get_avatar(), item::get_var(), get_weather(), item::heat_up(), itype_multi_cooker, m_info, max(), player, math_opers::pos(), item::put_in(), item::set_item_temperature(), item::set_var(), skill_cooking, skill_survival, sounds::sound(), ret_val_common::success(), and calendar::turn.
Referenced by Item_factory::init().
mycus()
std::optional< int > iuse::mycus (Character * p, item * , const tripoint &)
Intelligence slightly reduces sleep duration when eating Mycus
Definition at line 1424 of file iuse.cpp.
 {
     if( p->is_npc() ) {
         return 1;
     }
     // Welcome our guide.  Welcome.  To. The Mycus.
     // From an end-user perspective, dialogue should be presented uniformly:
     // initial caps, as in human writing, or all lowercase letters.
     // I think that all lowercase, because it contrasts with normal convention, reinforces the Mycus' alien nature
     if( p->has_trait( trait_THRESH_MARLOSS ) ) {
         get_event_bus().send<event_type::crosses_mycus_threshold>( p->getID() );
         p->add_msg_if_player( m_neutral,
                               _( "It tastes amazing, and you finish it quickly." ) );
         p->add_msg_if_player( m_good, _( "You feel better all over." ) );
         p->mod_painkiller( 30 );
         p->set_rad( 0 );
         p->healall( 4 ); // Can't make you a whole new person, but not for lack of trying
         p->add_msg_if_player( m_good,
                               _( "As it settles in, you feel ecstasy radiating through every part of your body" ) );
         p->add_morale( MORALE_MARLOSS, 1000, 1000 ); // Last time you'll ever have it this good.  So enjoy.
         p->add_msg_if_player( m_good,
                               _( "Your eyes roll back in your head.  Everything dissolves into a blissful haze" ) );
         /** @EFFECT_INT slightly reduces sleep duration when eating Mycus */
         p->fall_asleep( 5_hours - p->int_cur * 1_minutes );
         p->unset_mutation( trait_THRESH_MARLOSS );
         p->set_mutation( trait_THRESH_MYCUS );
         g->invalidate_main_ui_adaptor();
         //~ The Mycus does not use the term (or encourage the concept of) "you".  The PC is a local/native organism, but is now the Mycus.
         //~ It still understands the concept, but uninitelligent fungaloids and mind-bent symbiotes should not need it.
         //~ We are the Mycus.
         popup( _( "we welcome into us.  we have endured long in this forbidding world." ) );
         p->add_msg_if_player( " " );
         p->add_msg_if_player( m_good,
                               _( "A sea of white caps, waving gently.  A haze of spores wafting silently over a forest." ) );
         g->invalidate_main_ui_adaptor();
         popup( _( "the natives have a saying: \"e pluribus unum.\"  out of many, one." ) );
         p->add_msg_if_player( " " );
         p->add_msg_if_player( m_good,
                               _( "The blazing pink redness of the berry.  The juices spreading across our tongue, the warmth draping over us like a lover's embrace." ) );
         g->invalidate_main_ui_adaptor();
         popup( _( "we welcome the union of our lines in our local guide.  we will prosper, and unite this world.  even now, our fruits adapt to better serve local physiology." ) );
         p->add_msg_if_player( " " );
         p->add_msg_if_player( m_good,
                               _( "The sky-blue of the seed.  The nutty, creamy flavors intermingling with the berry, a memory that will never leave us." ) );
         g->invalidate_main_ui_adaptor();
         popup( _( "as, in time, shall we adapt to better welcome those who have not received us." ) );
         p->add_msg_if_player( " " );
         p->add_msg_if_player( m_good,
                               _( "The amber-yellow of the sap.  Feel it flowing through our veins, taking the place of the strange, thin red gruel called \"blood.\"" ) );
         g->invalidate_main_ui_adaptor();
         popup( _( "we are the Mycus." ) );
         /*p->add_msg_if_player( m_good,
                               _( "We welcome into us.  We have endured long in this forbidding world." ) );
         p->add_msg_if_player( m_good,
                               _( "The natives have a saying: \"E Pluribus Unum\"  Out of many, one." ) );
         p->add_msg_if_player( m_good,
                               _( "We welcome the union of our lines in our local guide.  We will prosper, and unite this world." ) );
         p->add_msg_if_player( m_good, _( "Even now, our fruits adapt to better serve local physiology." ) );
         p->add_msg_if_player( m_good,
                               _( "As, in time, shall we adapt to better welcome those who have not received us." ) );*/
         map &here = get_map();
         fungal_effects fe;
         for( const tripoint &nearby_pos : here.points_in_radius( p->pos(), 3 ) ) {
             if( here.move_cost( nearby_pos ) != 0 && !here.has_furn( nearby_pos ) &&
                 !here.has_flag( ter_furn_flag::TFLAG_DEEP_WATER, nearby_pos ) &&
                 !here.has_flag( ter_furn_flag::TFLAG_NO_FLOOR, nearby_pos ) ) {
                 fe.marlossify( nearby_pos );
             }
         }
         p->rem_addiction( addiction_marloss_r );
         p->rem_addiction( addiction_marloss_b );
         p->rem_addiction( addiction_marloss_y );
     } else if( p->has_trait( trait_THRESH_MYCUS ) &&
                !p->has_trait( trait_M_DEPENDENT ) ) { // OK, now set the hook.
         if( !one_in( 3 ) ) {
             p->mutate_category( mutation_category_MYCUS, false, true );
             p->mod_stored_kcal( -87 );
             p->mod_thirst( 10 );
             p->mod_sleepiness( 5 );
             p->add_morale( MORALE_MARLOSS, 25, 200 ); // still covers up mutation pain
         }
     } else if( p->has_trait( trait_THRESH_MYCUS ) ) {
         p->mod_painkiller( 5 );
         p->mod_stim( 5 );
     } else { // In case someone gets one without having been adapted first.
         // Marloss is the Mycus' method of co-opting humans.  Mycus fruit is for symbiotes' maintenance and development.
         p->add_msg_if_player(
             _( "This tastes really weird!  You're not sure it's good for you" ) );
         p->mutate();
         p->mod_pain( 2 * rng( 1, 5 ) );
         p->mod_stored_kcal( -87 );
         p->mod_thirst( 10 );
         p->mod_sleepiness( 5 );
         p->vomit(); // no hunger/quench benefit for you
         p->mod_daily_health( -8, -50 );
     }
     return 1;
 }
References _, Character::add_morale(), Character::add_msg_if_player(), addiction_marloss_b, addiction_marloss_r, addiction_marloss_y, crosses_mycus_threshold, Character::fall_asleep(), g, get_event_bus(), get_map(), Character::getID(), map::has_flag(), map::has_furn(), Character::has_trait(), Character::healall(), Character::int_cur, Character::is_npc(), m_good, m_neutral, fungal_effects::marlossify(), Character::mod_daily_health(), Character::mod_pain(), Character::mod_painkiller(), Character::mod_sleepiness(), Character::mod_stim(), Character::mod_stored_kcal(), Character::mod_thirst(), MORALE_MARLOSS, map::move_cost(), Character::mutate(), Character::mutate_category(), mutation_category_MYCUS, one_in(), map::points_in_radius(), popup(), Creature::pos(), Character::rem_addiction(), rng(), event_bus::send(), Character::set_mutation(), Character::set_rad(), TFLAG_DEEP_WATER, TFLAG_NO_FLOOR, trait_M_DEPENDENT, trait_THRESH_MARLOSS, trait_THRESH_MYCUS, Character::unset_mutation(), and Character::vomit().
Referenced by mattack::fungus_fortify(), Item_factory::init(), and Character::update_stomach().
noise_emitter_on()
std::optional< int > iuse::noise_emitter_on (Character * , item * , const tripoint & pos)
Definition at line 2631 of file iuse.cpp.
 {
     sounds::sound( pos, 30, sounds::sound_t::alarm, _( "KXSHHHHRRCRKLKKK!" ), true, "tool",
                    "noise_emitter" );
     return 1;
 }
References _, sounds::alarm, math_opers::pos(), and sounds::sound().
Referenced by Item_factory::init().
oxygen_bottle()
std::optional< int > iuse::oxygen_bottle (Character * p, item * it, const tripoint &)
Definition at line 1033 of file iuse.cpp.
 {
     p->mod_moves( -to_moves<int>( 10_seconds ) );
     p->add_msg_player_or_npc( m_neutral, string_format( _( "You breathe deeply from the %s." ),
                               it->tname() ),
                               string_format( _( "<npcname> breathes from the %s." ),
                                       it->tname() ) );
     if( p->has_effect( effect_smoke_lungs ) ) {
         p->remove_effect( effect_smoke_lungs );
     } else if( p->has_effect( effect_teargas ) ) {
         p->remove_effect( effect_teargas );
     } else if( p->has_effect( effect_asthma ) ) {
         p->remove_effect( effect_asthma );
     } else if( p->get_stim() < 16 ) {
         p->mod_stim( 8 );
         p->mod_painkiller( 2 );
     }
     p->mod_painkiller( 2 );
     return 1;
 }
References _, Character::add_msg_player_or_npc(), effect_asthma, effect_smoke_lungs, effect_teargas, Character::get_stim(), Creature::has_effect(), m_neutral, Creature::mod_moves(), Character::mod_painkiller(), Character::mod_stim(), Creature::remove_effect(), string_format(), and item::tname().
Referenced by Item_factory::init().
oxytorch()
std::optional< int > iuse::oxytorch (Character * p, item * it, const tripoint &)
Definition at line 4631 of file iuse.cpp.
 {
     if( p->is_npc() ) {
         // Long action
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     if( !p->has_quality( qual_GLARE, 1 ) ) {
         p->add_msg_if_player( m_info, _( "You need welding goggles to do that." ) );
         return std::nullopt;
     }
     map &here = get_map();
     const std::function<bool( const tripoint & )> f =
     [&here, p]( const tripoint & pnt ) {
         if( pnt == p->pos() ) {
             return false;
         } else if( here.has_furn( pnt ) ) {
             return here.furn( pnt )->oxytorch->valid();
         } else if( !here.ter( pnt )->is_null() ) {
             return here.ter( pnt )->oxytorch->valid();
         }
         return false;
     };
     const std::optional<tripoint> pnt_ = choose_adjacent_highlight(
             _( "Cut up metal where?" ), _( "There is no metal to cut up nearby." ), f, false );
     if( !pnt_ ) {
         return std::nullopt;
     }
     const tripoint &pnt = *pnt_;
     if( !f( pnt ) ) {
         if( pnt == p->pos() ) {
             p->add_msg_if_player( m_info, _( "Yuck.  Acetylene gas smells weird." ) );
         } else {
             p->add_msg_if_player( m_info, _( "You can't cut that." ) );
         }
         return std::nullopt;
     }
     p->assign_activity( oxytorch_activity_actor( pnt, item_location{*p, it} ) );
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), Character::assign_activity(), Character::cant_do_mounted(), choose_adjacent_highlight(), map::furn(), get_map(), map::has_furn(), Character::has_quality(), Character::is_npc(), ter_t::is_null(), m_info, ter_t::oxytorch, furn_t::oxytorch, Creature::pos(), qual_GLARE, and map::ter().
Referenced by Item_factory::init().
pack_cbm()
std::optional< int > iuse::pack_cbm (Character * p, item * it, const tripoint &)
Definition at line 2366 of file iuse.cpp.
 {
     item_location bionic = g->inv_map_splice( []( const item & e ) {
         return e.is_bionic() && e.has_flag( flag_NO_PACKED );
     }, _( "Choose CBM to pack" ), PICKUP_RANGE, _( "You don't have any CBMs." ) );
     if( !bionic ) {
         return std::nullopt;
     }
     if( !bionic.get_item()->faults.empty() ) {
         if( p->query_yn( _( "This CBM is faulty.  You should mend it first.  Do you want to try?" ) ) ) {
             p->mend_item( std::move( bionic ) );
         }
         return 0;
     }
     const int success = round( p->get_skill_level( skill_firstaid ) ) - rng( 0, 6 );
     if( success > 0 ) {
         p->add_msg_if_player( m_good, _( "You carefully prepare the CBM for sterilization." ) );
         bionic.get_item()->unset_flag( flag_NO_PACKED );
     } else {
         p->add_msg_if_player( m_bad, _( "You fail to properly prepare the CBM." ) );
     }
     std::vector<item_comp> comps;
     comps.emplace_back( it->typeId(), 1 );
     p->consume_items( comps, 1, is_crafting_component );
     return 0;
 }
References _, Character::add_msg_if_player(), Character::consume_items(), flag_NO_PACKED, g, Character::get_skill_level(), item::has_flag(), item::is_bionic(), is_crafting_component(), m_bad, m_good, Character::mend_item(), PICKUP_RANGE, Character::query_yn(), rng(), round(), skill_firstaid, and item::typeId().
Referenced by Item_factory::init().
pack_item()
std::optional< int > iuse::pack_item (Character * p, item * it, const tripoint &)
Definition at line 2397 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action pack_item that requires character but no character is present",
                   it->typeId().str() );
     }
     if( p->cant_do_underwater() ) {
         return std::nullopt;
     }
     if( p->is_worn( *it ) ) {
         p->add_msg_if_player( m_info, _( "You can't pack your %s until you take it off." ),
                               it->tname() );
         return std::nullopt;
     } else { // Turning it off
         std::string oname = it->typeId().str();
         if( string_ends_with( oname, "_on" ) ) {
             oname.erase( oname.length() - 3, 3 );
         } else {
             debugmsg( "no item type to turn it into (%s)!", oname );
             return std::nullopt;
         }
         p->mod_moves( -to_moves<int>( 10_seconds ) );
         p->add_msg_if_player( _( "You pack your %s for storage." ), it->tname() );
         it->convert( itype_id( oname ), p ).active = false;
     }
     return 0;
 }
References _, item::active, Character::add_msg_if_player(), Creature::cant_do_underwater(), item::convert(), debugmsg, Character::is_worn(), m_info, Creature::mod_moves(), string_id< T >::str(), string_ends_with(), item::tname(), and item::typeId().
Referenced by Item_factory::init().
petfood()
std::optional< int > iuse::petfood (Character * p, item * it, const tripoint &)
Definition at line 1525 of file iuse.cpp.
 {
     if( !it->is_comestible() ) {
         p->add_msg_if_player( _( "You doubt someone would want to eat %1$s." ), it->tname() );
         return std::nullopt;
     }
     const std::optional<tripoint> pnt = choose_adjacent( string_format(
                                             _( "Tame which animal with %s?" ),
                                             it->tname() ) );
     if( !pnt ) {
         return std::nullopt;
     }
     creature_tracker &creatures = get_creature_tracker();
     // First a check to see if we are trying to feed a NPC dog food.
     if( npc *const who = creatures.creature_at<npc>( *pnt ) ) {
         if( query_yn( _( "Are you sure you want to feed a person %1$s?" ), it->tname() ) ) {
             p->mod_moves( -to_moves<int>( 1_seconds ) );
             p->add_msg_if_player( _( "You put your %1$s into %2$s's mouth!" ),
                                   it->tname(), who->disp_name( true ) );
             if( x_in_y( 9, 10 ) || who->is_ally( *p ) ) {
                 who->say(
                     _( "Okay, but please, don't give me this again.  I don't want to eat pet food in the Cataclysm all day." ) );
             } else {
                 p->add_msg_if_player( _( "%s knocks it from your hand!" ), who->disp_name() );
                 who->make_angry();
             }
             p->consume_charges( *it, 1 );
             return std::nullopt;
         } else {
             p->add_msg_if_player( _( "Never mind." ) );
             return std::nullopt;
         }
         // Then monsters.
     } else if( monster *const mon = creatures.creature_at<monster>( *pnt, true ) ) {
         p->mod_moves( -to_moves<int>( 1_seconds ) );
         bool can_feed = false;
         const pet_food_data &petfood = mon->type->petfood;
         const std::set<std::string> &itemfood = it->get_comestible()->petfood;
         for( const std::string &food : petfood.food ) {
             if( itemfood.find( food ) != itemfood.end() ) {
                 can_feed = true;
                 break;
             }
         }
         if( !can_feed ) {
             p->add_msg_if_player( _( "The %s doesn't want that kind of food." ), mon->get_name() );
             return std::nullopt;
         }
         bool halluc = mon->is_hallucination();
         if( mon->type->id == mon_dog_thing ) {
             if( !halluc ) {
                 p->deal_damage( mon, bodypart_id( "hand_r" ), damage_instance( STATIC( damage_type_id( "cut" ) ),
                                 rng( 1, 10 ) ) );
             }
             p->add_msg_if_player( m_bad, _( "You want to feed it the dog food, but it bites your fingers!" ) );
             if( one_in( 5 ) ) {
                 p->add_msg_if_player(
                     _( "Apparently, it's more interested in your flesh than the dog food in your hand!" ) );
                 if( halluc ) {
                     item drop_me = p->reduce_charges( it, 1 );
                     p->i_drop_at( drop_me );
                 } else {
                     p->consume_charges( *it, 1 );
                 }
             }
             return std::nullopt;
         }
         if( halluc && one_in( 4 ) ) {
             p->add_msg_if_player( _( "You try to feed the %1$s some %2$s, but it vanishes!" ),
                                   mon->type->nname(), it->tname() );
             mon->die( nullptr );
             return std::nullopt;
         }
         p->add_msg_if_player( _( "You feed your %1$s to the %2$s." ), it->tname(), mon->get_name() );
         if( mon->has_flag( mon_flag_EATS ) ) {
             int kcal = it->get_comestible()->default_nutrition.kcal();
             mon->amount_eaten += kcal;
             if( mon->amount_eaten >= mon->stomach_size ) {
                 p->add_msg_if_player( _( "The %1$s seems full now." ), mon->get_name() );
             }
         } else if( !mon->has_flag( mon_flag_EATS ) ) {
             mon->add_effect( effect_critter_well_fed, 24_hours );
         }
         if( petfood.feed.empty() ) {
             p->add_msg_if_player( m_good, _( "The %1$s is your pet now!" ), mon->get_name() );
         } else {
             p->add_msg_if_player( m_good, petfood.feed, mon->get_name() );
         }
         mon->friendly = -1;
         mon->add_effect( effect_pet, 1_turns, true );
         if( halluc ) {
             item drop_me = p->reduce_charges( it, 1 );
             p->i_drop_at( drop_me );
         } else {
             p->consume_charges( *it, 1 );
         }
         return std::nullopt;
     }
     p->add_msg_if_player( _( "There is nothing to be fed here." ) );
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), choose_adjacent(), Character::consume_charges(), creature_tracker::creature_at(), Character::deal_damage(), effect_critter_well_fed, effect_pet, item::get_comestible(), get_creature_tracker(), Character::i_drop_at(), item::is_comestible(), m_bad, m_good, Creature::mod_moves(), mon_dog_thing, mon_flag_EATS, one_in(), query_yn(), Character::reduce_charges(), rng(), STATIC, string_format(), item::tname(), and x_in_y().
Referenced by Item_factory::init().
pick_lock()
std::optional< int > iuse::pick_lock (Character * p, item * it, const tripoint & pos)
Dexterity speeds up door lock picking Lock Picking speeds up door lock picking
Definition at line 3065 of file iuse.cpp.
 {
     if( p->is_npc() ) {
         return std::nullopt;
     }
     avatar &you = dynamic_cast<avatar &>( *p );
     std::optional<tripoint> target;
     // Prompt for a target lock to pick, or use the given tripoint
     if( pos == you.pos() ) {
         target = lockpick_activity_actor::select_location( you );
     } else {
         target = pos;
     }
     if( !target.has_value() ) {
         return std::nullopt;
     }
     int qual = it->get_quality( qual_LOCKPICK );
     if( qual < 1 ) {
         debugmsg( "Item %s with 'PICK_LOCK' use action requires LOCKPICK quality of at least 1.",
                   it->typeId().c_str() );
         qual = 1;
     }
     /** @EFFECT_DEX speeds up door lock picking */
     /** @EFFECT_LOCKPICK speeds up door lock picking */
     int duration_proficiency_factor = 10;
     if( you.has_proficiency( proficiency_prof_lockpicking ) ) {
         duration_proficiency_factor = 5;
     }
     if( you.has_proficiency( proficiency_prof_lockpicking_expert ) ) {
         duration_proficiency_factor = 1;
     }
     time_duration duration = 5_seconds;
     if( !it->has_flag( flag_PERFECT_LOCKPICK ) ) {
         duration = std::max( 30_seconds,
                              ( 10_minutes - time_duration::from_minutes( qual + static_cast<float>( you.dex_cur ) / 4.0f +
                                      you.get_skill_level( skill_traps ) ) ) * duration_proficiency_factor );
     }
     you.assign_activity( lockpick_activity_actor::use_item( to_moves<int>( duration ),
                          item_location( you, it ), get_map().getabs( *target ) ) );
     return 1;
 }
References Character::assign_activity(), string_id< T >::c_str(), debugmsg, Character::dex_cur, flag_PERFECT_LOCKPICK, time_duration::from_minutes(), get_map(), item::get_quality(), Character::get_skill_level(), item::has_flag(), Character::has_proficiency(), Character::is_npc(), max(), Creature::pos(), math_opers::pos(), proficiency_prof_lockpicking, proficiency_prof_lockpicking_expert, qual_LOCKPICK, lockpick_activity_actor::select_location(), skill_traps, item::typeId(), and lockpick_activity_actor::use_item().
Referenced by Item_factory::init().
pickaxe()
std::optional< int > iuse::pickaxe (Character * p, item * it, const tripoint & pos)
Strength decreases time to dig with a pickaxe
Definition at line 3112 of file iuse.cpp.
 {
     if( p->is_npc() ) {
         // Long action
         return std::nullopt;
     }
     /** @EFFECT_STR decreases time to dig with a pickaxe */
     int extra_moves = ( ( MAX_STAT + 4 ) -
                         std::min( p->get_arm_str(), MAX_STAT ) ) * to_moves<int>( 5_minutes );
     return dig_tool( p, it, pos, ACT_PICKAXE,
                      _( "Mine where?" ), _( "You can't mine there." ), _( "You strike the %1$s with your %2$s." ),
                      extra_moves );
 }
References _, ACT_PICKAXE, dig_tool(), Character::get_arm_str(), Character::is_npc(), MAX_STAT, min(), and math_opers::pos().
Referenced by Item_factory::init().
plantblech()
std::optional< int > iuse::plantblech (Character * p, item * it, const tripoint & pos)
Definition at line 1108 of file iuse.cpp.
 {
     if( p->has_trait( trait_THRESH_PLANT ) ) {
         double multiplier = -1;
         if( p->has_trait( trait_CHLOROMORPH ) ) {
             multiplier = -3;
             p->add_msg_if_player( m_good, _( "The meal is revitalizing." ) );
         } else {
             p->add_msg_if_player( m_good, _( "Oddly enough, this doesn't taste so bad." ) );
         }
         //reverses the harmful values of drinking fertilizer
         p->stomach.mod_nutr( p->nutrition_for( *it ) * multiplier );
         p->mod_thirst( -it->get_comestible()->quench * multiplier );
         p->mod_daily_health( it->get_comestible()->healthy * multiplier,
                              it->get_comestible()->healthy * multiplier );
         p->add_morale( MORALE_FOOD_GOOD, -10 * multiplier, 60, 1_hours, 30_minutes, false, it->type );
         return 1;
     } else {
         return blech( p, it, pos );
     }
 }
References _, Character::add_morale(), Character::add_msg_if_player(), blech(), item::get_comestible(), Character::has_trait(), m_good, Character::mod_daily_health(), stomach_contents::mod_nutr(), Character::mod_thirst(), MORALE_FOOD_GOOD, Character::nutrition_for(), math_opers::pos(), Character::stomach, trait_CHLOROMORPH, trait_THRESH_PLANT, and item::type.
Referenced by Item_factory::init().
play_game()
std::optional< int > iuse::play_game (Character * p, item * it, const tripoint &)
Definition at line 8402 of file iuse.cpp.
 {
     if( p->is_avatar() ) {
         std::vector<npc *> followers = g->get_npcs_if( [p]( const npc & n ) {
             return n.is_ally( *p ) && p->sees( n ) && n.can_hear( p->pos(), p->get_shout_volume() );
         } );
         int fcount = followers.size();
         if( fcount > 0 ) {
             const char *qstr = fcount > 1 ? _( "Play the %s with your friends?" ) :
                                _( "Play the %s with your friend?" );
             std::string res = query_popup()
                               .context( "FRIENDS_ME_CANCEL" )
                               .message( qstr, it->tname() )
                               .option( "FRIENDS" ).option( "ME" ).option( "CANCEL" )
                               .query().action;
             if( res == "FRIENDS" ) {
                 if( fcount > 1 ) {
                     add_msg( n_gettext( "You and your %d friend start playing.",
                                         "You and your %d friends start playing.", fcount ), fcount );
                 } else {
                     add_msg( _( "You and your friend start playing." ) );
                 }
                 p->assign_activity( ACT_GENERIC_GAME, to_moves<int>( 1_hours ), fcount,
                                     p->get_item_position( it ), "gaming with friends" );
                 for( npc *n : followers ) {
                     n->assign_activity( ACT_GENERIC_GAME, to_moves<int>( 1_hours ), fcount,
                                         n->get_item_position( it ), "gaming with friends" );
                 }
             } else if( res == "ME" ) {
                 p->add_msg_if_player( _( "You start playing." ) );
                 p->assign_activity( ACT_GENERIC_GAME, to_moves<int>( 1_hours ), -1,
                                     p->get_item_position( it ), "gaming" );
             } else {
                 return std::nullopt;
             }
             return 0;
         } // else, fall through to playing alone
     }
     if( query_yn( _( "Play a game with the %s?" ), it->tname() ) ) {
         p->add_msg_if_player( _( "You start playing." ) );
         p->assign_activity( ACT_GENERIC_GAME, to_moves<int>( 1_hours ), -1,
                             p->get_item_position( it ), "gaming" );
     } else {
         return std::nullopt;
     }
     return 0;
 }
References _, ACT_GENERIC_GAME, query_popup::result::action, add_msg(), Character::add_msg_if_player(), Character::assign_activity(), Character::can_hear(), query_popup::context(), g, Character::get_item_position(), Character::get_shout_volume(), npc::is_ally(), Creature::is_avatar(), query_popup::message(), n_gettext, query_popup::option(), Creature::pos(), query_popup::query(), query_yn(), Character::sees(), and item::tname().
Referenced by Item_factory::init().
play_music()
void iuse::play_music (Character * p, const tripoint & source, int volume, int max_morale)
Definition at line 3773 of file iuse.cpp.
 {
     // TODO: what about other "player", e.g. when a NPC is listening or when the PC is listening,
     // the other characters around should be able to profit as well.
     const bool do_effects = p && p->can_hear( source, volume ) && !p->in_sleep_state();
     std::string sound = "music";
     if( calendar::once_every( time_duration::from_minutes(
                                   get_option<int>( "DESCRIBE_MUSIC_FREQUENCY" ) ) ) ) {
         // Every X minutes, describe the music
         const std::string music = get_music_description();
         if( !music.empty() ) {
             sound = music;
             // descriptions aren't printed for sounds at our position
             if( do_effects && p->pos() == source ) {
                 p->add_msg_if_player( _( "You listen to %s" ), music );
             }
         }
     }
     if( volume != 0 ) {
         sounds::ambient_sound( source, volume, sounds::sound_t::music, sound );
     }
     if( do_effects ) {
         p->add_effect( effect_music, 1_turns );
         p->add_morale( MORALE_MUSIC, 1, max_morale, 5_minutes, 2_minutes, true );
         // mp3 player reduces hearing
         if( volume == 0 ) {
             p->add_effect( effect_earphones, 1_turns );
         }
     }
 }
References _, Creature::add_effect(), Character::add_morale(), Character::add_msg_if_player(), sounds::ambient_sound(), Character::can_hear(), effect_earphones, effect_music, time_duration::from_minutes(), get_music_description(), Character::in_sleep_state(), MORALE_MUSIC, sounds::music, calendar::once_every(), and Creature::pos().
Referenced by vehicle::play_music().
poison()
std::optional< int > iuse::poison (Character * p, item * it, const tripoint &)
Strength increases EATPOISON trait effectiveness (50-90%)
Definition at line 907 of file iuse.cpp.
 {
     if( p->has_trait( trait_EATDEAD ) ) {
         return 1;
     }
     // NPCs have a magical sense of what is inedible
     // Players can abuse the crafting menu instead...
     if( !it->has_flag( flag_HIDDEN_POISON ) &&
         ( p->is_npc() ||
           !p->query_yn( _( "Are you sure you want to eat this?  It looks poisonous" ) ) ) ) {
         return std::nullopt;
     }
     /** @EFFECT_STR increases EATPOISON trait effectiveness (50-90%) */
     if( p->has_trait( trait_EATPOISON ) && ( !one_in( p->str_cur / 2 ) ) ) {
         return 1;
     }
     p->add_effect( effect_poison, 1_hours );
     p->add_effect( effect_foodpoison, 3_hours );
     return 1;
 }
References _, Creature::add_effect(), effect_foodpoison, effect_poison, flag_HIDDEN_POISON, item::has_flag(), Character::has_trait(), Character::is_npc(), one_in(), Character::query_yn(), Character::str_cur, trait_EATDEAD, and trait_EATPOISON.
Referenced by Item_factory::init(), and item::io().
portable_game()
std::optional< int > iuse::portable_game (Character * p, item * it, const tripoint &)
Definition at line 4023 of file iuse.cpp.
 {
     if( p->is_npc() ) {
         // Long action
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     if( p->cant_do_underwater() ) {
         return std::nullopt;
     }
     if( p->has_trait( trait_ILLITERATE ) ) {
         p->add_msg_if_player( m_info, _( "You're illiterate!" ) );
         return std::nullopt;
     } else if( it->typeId() != itype_arcade_machine && !it->ammo_sufficient( p ) ) {
         p->add_msg_if_player( m_info, _( "The %s's batteries are dead." ), it->tname() );
         return std::nullopt;
     } else {
         std::string loaded_software = "robot_finds_kitten";
         // number of nearby friends with gaming devices
         std::vector<npc *> friends_w_game = g->get_npcs_if( [&it, p]( const npc & n ) {
             return n.is_player_ally() && p->sees( n ) &&
                    n.can_hear( p->pos(), p->get_shout_volume() ) &&
             n.has_item_with( [&it]( const item & i ) {
                 return i.typeId() == it->typeId() && i.ammo_sufficient( nullptr );
             } );
         } );
         uilist as_m;
         as_m.text = _( "What do you want to play?" );
         as_m.entries.emplace_back( 1, true, '1', _( "robotfindskitten" ) );
         as_m.entries.emplace_back( 2, true, '2', _( "S N A K E" ) );
         as_m.entries.emplace_back( 3, true, '3', _( "Sokoban" ) );
         as_m.entries.emplace_back( 4, true, '4', _( "Minesweeper" ) );
         as_m.entries.emplace_back( 5, true, '5', _( "Lights on!" ) );
         if( friends_w_game.empty() ) {
             as_m.entries.emplace_back( 6, true, '6', _( "Play anything for a while" ) );
         } else {
             as_m.entries.emplace_back( 6, true, '6', _( "Play something with friends" ) );
             as_m.entries.emplace_back( 7, true, '7', _( "Play something alone" ) );
         }
         as_m.query();
         bool w_friends = false;
         switch( as_m.ret ) {
             case 1:
                 loaded_software = "robot_finds_kitten";
                 break;
             case 2:
                 loaded_software = "snake_game";
                 break;
             case 3:
                 loaded_software = "sokoban_game";
                 break;
             case 4:
                 loaded_software = "minesweeper_game";
                 break;
             case 5:
                 loaded_software = "lightson_game";
                 break;
             case 6:
                 loaded_software = "null";
                 w_friends = !friends_w_game.empty();
                 break;
             case 7: {
                 if( friends_w_game.empty() ) {
                     return std::nullopt;
                 }
                 loaded_software = "null";
             }
             break;
             default:
                 //Cancel
                 return std::nullopt;
         }
         //Play in 15-minute chunks
         const int moves = to_moves<int>( 15_minutes );
         size_t num_friends = w_friends ? friends_w_game.size() : 0;
         int winner = rng( 0, num_friends );
         if( winner == 0 ) {
             winner = get_player_character().getID().get_value();
         } else {
             winner = friends_w_game[winner - 1]->getID().get_value();
         }
         player_activity game_act( ACT_GENERIC_GAME, to_moves<int>( 1_hours ), num_friends,
                                   p->get_item_position( it ), w_friends ? "gaming with friends" : "gaming" );
         game_act.values.emplace_back( winner );
         if( w_friends ) {
             std::string it_name = it->type_name( num_friends + 1 );
             if( num_friends > 1 ) {
                 p->add_msg_if_player( _( "You and your %1$u friends play on your %2$s for a while." ), num_friends,
                                       it_name );
             } else {
                 p->add_msg_if_player( _( "You and your friend play on your %s for a while." ), it_name );
             }
             for( npc *n : friends_w_game ) {
                 std::vector<item *> nit = n->cache_get_items_with( it->typeId(), []( const item & i ) {
                     return i.ammo_sufficient( nullptr );
                 } );
                 n->assign_activity( game_act );
                 n->activity.targets.emplace_back( *n, nit.front() );
                 n->activity.position = n->get_item_position( nit.front() );
             }
         } else {
             p->add_msg_if_player( _( "You play on your %s for a while." ), it->tname() );
         }
         if( loaded_software == "null" ) {
             p->assign_activity( game_act );
             p->activity.targets.emplace_back( *p, it );
             return 0;
         }
         p->assign_activity( ACT_GAME, moves, -1, 0, "gaming" );
         p->activity.targets.emplace_back( *p, it );
         std::map<std::string, std::string> game_data;
         game_data.clear();
         int game_score = 0;
         play_videogame( loaded_software, game_data, game_score );
         if( game_data.find( "end_message" ) != game_data.end() ) {
             p->add_msg_if_player( game_data["end_message"] );
         }
         if( game_score != 0 ) {
             if( game_data.find( "moraletype" ) != game_data.end() ) {
                 std::string moraletype = game_data.find( "moraletype" )->second;
                 if( moraletype == "MORALE_GAME_FOUND_KITTEN" ) {
                     p->add_morale( MORALE_GAME_FOUND_KITTEN, game_score, 110 );
                 } /*else if ( ...*/
             } else {
                 p->add_morale( MORALE_GAME, game_score, 110 );
             }
         }
     }
     return 0;
 }
References _, ACT_GAME, ACT_GENERIC_GAME, Character::activity, Character::add_morale(), Character::add_msg_if_player(), item::ammo_sufficient(), Character::assign_activity(), Character::cache_get_items_with(), Character::can_hear(), Character::cant_do_mounted(), Creature::cant_do_underwater(), uilist::entries, g, Character::get_item_position(), get_player_character(), Character::get_shout_volume(), character_id::get_value(), Character::getID(), visitable::has_item_with(), Character::has_trait(), Character::is_npc(), npc::is_player_ally(), itype_arcade_machine, m_info, MORALE_GAME, MORALE_GAME_FOUND_KITTEN, play_videogame(), Creature::pos(), player_activity::position, uilist::query(), uilist::ret, rng(), Character::sees(), player_activity::targets, uilist::text, item::tname(), trait_ILLITERATE, item::type_name(), item::typeId(), and player_activity::values.
Referenced by vehicle::build_electronics_menu(), and Item_factory::init().
portal()
std::optional< int > iuse::portal (Character * p, item * it, const tripoint &)
Definition at line 3561 of file iuse.cpp.
 {
     if( !it->ammo_sufficient( p ) ) {
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     tripoint t( p->posx() + rng( -2, 2 ), p->posy() + rng( -2, 2 ), p->posz() );
     get_map().trap_set( t, tr_portal );
     return 1;
 }
References item::ammo_sufficient(), Character::cant_do_mounted(), get_map(), Creature::posx(), Creature::posy(), Creature::posz(), rng(), tr_portal, and map::trap_set().
Referenced by Item_factory::init().
prozac()
std::optional< int > iuse::prozac (Character * p, item * , const tripoint &)
Definition at line 973 of file iuse.cpp.
 {
     if( !p->has_effect( effect_took_prozac ) ) {
         p->add_effect( effect_took_prozac, 12_hours );
     } else {
         p->mod_stim( 3 );
     }
     if( one_in( 50 ) ) { // adverse reaction, same duration as prozac effect.
         p->add_msg_if_player( m_warning, _( "You suddenly feel hollow inside." ) );
         p->add_effect( effect_took_prozac_bad, p->get_effect_dur( effect_took_prozac ) );
     }
     p->add_effect( effect_took_prozac_visible, rng( 9_hours, 15_hours ) );
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), effect_took_prozac, effect_took_prozac_bad, effect_took_prozac_visible, Creature::get_effect_dur(), Creature::has_effect(), m_warning, Character::mod_stim(), one_in(), and rng().
Referenced by Item_factory::init().
purify_smart()
std::optional< int > iuse::purify_smart (Character * p, item * it, const tripoint &)
Definition at line 1164 of file iuse.cpp.
 {
     std::vector<trait_id> valid; // Which flags the player has
     std::vector<std::string> valid_names; // Which flags the player has
     for( const mutation_branch &traits_iter : mutation_branch::get_all() ) {
         if( p->has_trait( traits_iter.id ) &&
             !p->has_base_trait( traits_iter.id ) &&
             p->purifiable( traits_iter.id ) ) {
             //Looks for active mutation
             valid.push_back( traits_iter.id );
             valid_names.push_back( p->mutation_name( traits_iter.id ) );
         }
     }
     if( valid.empty() ) {
         p->add_msg_if_player( _( "You don't have any mutations to purify." ) );
         return std::nullopt;
     }
     int mutation_index = uilist( _( "Choose a mutation to purify: " ), valid_names );
     // Because valid_names doesn't start with a space,
     // include one here to prettify the output
     if( mutation_index < 0 ) {
         return std::nullopt;
     }
     p->add_msg_if_player(
         _( "You inject the purifier.  The liquid thrashes inside the tube and goes down reluctantly." ) );
     p->remove_mutation( valid[mutation_index] );
     valid.erase( valid.begin() + mutation_index );
     // and one or two more untargeted purifications.
     if( !valid.empty() ) {
         p->remove_mutation( random_entry_removed( valid ) );
     }
     if( !valid.empty() && one_in( 2 ) ) {
         p->remove_mutation( random_entry_removed( valid ) );
     }
     p->mod_pain( 3 );
     item syringe( "syringe", it->birthday() );
     p->i_add( syringe );
     p->vitamins_mod( it->get_comestible()->default_nutrition.vitamins() );
     get_event_bus().send<event_type::administers_mutagen>( p->getID(),
             mutagen_technique::injected_smart_purifier );
     return 1;
 }
References _, Character::add_msg_if_player(), administers_mutagen, item::birthday(), mutation_branch::get_all(), item::get_comestible(), get_event_bus(), Character::getID(), Character::has_base_trait(), Character::has_trait(), Character::i_add(), injected_smart_purifier, Character::mod_pain(), Character::mutation_name(), one_in(), Character::purifiable(), random_entry_removed(), Character::remove_mutation(), event_bus::send(), and Character::vitamins_mod().
Referenced by Item_factory::init().
radglove()
std::optional< int > iuse::radglove (Character * p, item * it, const tripoint &)
Definition at line 5096 of file iuse.cpp.
 {
     if( p->get_item_position( it ) >= -1 ) {
         p->add_msg_if_player( m_info,
                               _( "You must wear the radiation biomonitor before you can activate it." ) );
         return std::nullopt;
     } else if( !it->ammo_sufficient( p ) ) {
         p->add_msg_if_player( m_info, _( "The radiation biomonitor needs batteries to function." ) );
         return std::nullopt;
     } else {
         p->add_msg_if_player( _( "You activate your radiation biomonitor." ) );
         if( p->get_rad() >= 1 ) {
             p->add_msg_if_player( m_warning, _( "You are currently irradiated." ) );
             p->add_msg_player_or_say( m_info,
                                       _( "Your radiation level: %d mSv." ),
                                       _( "It says here that my radiation level is %d mSv." ),
                                       p->get_rad() );
         } else {
             p->add_msg_player_or_say( m_info,
                                       _( "You aren't currently irradiated." ),
                                       _( "It says I'm not irradiated." ) );
         }
         p->add_msg_if_player( _( "Have a nice day!" ) );
     }
     return 1;
 }
References _, Character::add_msg_if_player(), Character::add_msg_player_or_say(), item::ammo_sufficient(), Character::get_item_position(), Character::get_rad(), m_info, and m_warning.
Referenced by Item_factory::init().
radio_mod()
std::optional< int > iuse::radio_mod (Character * p, item * , const tripoint &)
Definition at line 1637 of file iuse.cpp.
 {
     if( p->is_npc() ) {
         // Now THAT would be kinda cruel
         return std::nullopt;
     }
     auto filter = []( const item & itm ) {
         return itm.has_flag( flag_RADIO_MODABLE );
     };
     // note: if !p->is_npc() then p is avatar
     item_location loc = game_menus::inv::titled_filter_menu(
                             filter, *p->as_avatar(), _( "Modify what?" ) );
     if( !loc ) {
         p->add_msg_if_player( _( "You don't have that item!" ) );
         return std::nullopt;
     }
     item &modded = *loc;
     int choice = uilist( _( "Which signal should activate the item?" ), {
         _( "\"Red\"" ), _( "\"Blue\"" ), _( "\"Green\"" )
     } );
     flag_id newtag;
     std::string colorname;
     switch( choice ) {
         case 0:
             newtag = flag_RADIOSIGNAL_1;
             colorname = _( "\"Red\"" );
             break;
         case 1:
             newtag = flag_RADIOSIGNAL_2;
             colorname = _( "\"Blue\"" );
             break;
         case 2:
             newtag = flag_RADIOSIGNAL_3;
             colorname = _( "\"Green\"" );
             break;
         default:
             return std::nullopt;
     }
     if( modded.has_flag( flag_RADIO_MOD ) && modded.has_flag( newtag ) ) {
         p->add_msg_if_player( _( "This item has been modified this way already." ) );
         return std::nullopt;
     }
     remove_radio_mod( modded, *p );
     p->add_msg_if_player(
         _( "You modify your %1$s to listen for the %2$s activation signal on the radio." ),
         modded.tname(), colorname );
     modded.set_flag( flag_RADIO_ACTIVATION )
     .set_flag( flag_RADIOCARITEM )
     .set_flag( flag_RADIO_MOD )
     .set_flag( newtag );
     return 1;
 }
References _, Character::add_msg_if_player(), Creature::as_avatar(), filter, flag_RADIO_ACTIVATION, flag_RADIO_MOD, flag_RADIO_MODABLE, flag_RADIOCARITEM, flag_RADIOSIGNAL_1, flag_RADIOSIGNAL_2, flag_RADIOSIGNAL_3, item::has_flag(), Character::is_npc(), remove_radio_mod(), item::set_flag(), game_menus::inv::titled_filter_menu(), and item::tname().
Referenced by Item_factory::init().
radio_off()
std::optional< int > iuse::radio_off (Character * p, item * it, const tripoint &)
Definition at line 2462 of file iuse.cpp.
 {
     if( !it->ammo_sufficient( p ) ) {
         p->add_msg_if_player( _( "It's dead." ) );
     } else {
         p->add_msg_if_player( _( "You turn the radio on." ) );
         it->convert( itype_radio_on, p ).active = true;
     }
     return 1;
 }
References _, item::active, Character::add_msg_if_player(), item::ammo_sufficient(), item::convert(), and itype_radio_on.
Referenced by Item_factory::init().
radio_on()
std::optional< int > iuse::radio_on (Character * , item * it, const tripoint &)
Definition at line 2582 of file iuse.cpp.
 {
     const auto tower_desc = []( const int noise ) {
         if( noise == 0 ) {
             return SNIPPET.random_from_category( "radio_station_desc_noise_0" )->translated();
         } else if( noise <= 20 ) {
             return SNIPPET.random_from_category( "radio_station_desc_noise_20" )->translated();
         } else if( noise <= 40 ) {
             return SNIPPET.random_from_category( "radio_station_desc_noise_40" )->translated();
         } else if( noise <= 60 ) {
             return SNIPPET.random_from_category( "radio_station_desc_noise_60" )->translated();
         } else if( noise <= 80 ) {
             return SNIPPET.random_from_category( "radio_station_desc_noise_80" )->translated();
         }
         return SNIPPET.random_from_category( "radio_station_desc_noise_max" )->translated();
     };
     std::vector<radio_tower_reference> options = overmap_buffer.find_all_radio_stations();
     if( options.empty() ) {
         popup( SNIPPET.random_from_category( "radio_scan_no_stations" )->translated() );
     }
     uilist scanlist;
     scanlist.title = _( "Select a station" );
     scanlist.desc_enabled = true;
     add_msg_debug( debugmode::DF_RADIO, "Radio scan:" );
     for( size_t i = 0; i < options.size(); ++i ) {
         std::string selected_text;
         const radio_tower_reference &tref = options[i];
         if( it->frequency == tref.tower->frequency ) {
             selected_text = pgettext( "radio station", " (selected)" );
         }
         //~ Selected radio station, %d is a number in sequence (1,2,3...),
         //~ %s is ' (selected)' if this is the radio station playing, else nothing
         const std::string station_name = string_format( _( "Station %d%s" ), i + 1, selected_text );
         const int noise_chance = radio_static_chance( tref );
         scanlist.addentry_desc( i, true, MENU_AUTOASSIGN, station_name, tower_desc( noise_chance ) );
         const point_abs_omt dbgpos = project_to<coords::omt>( tref.abs_sm_pos );
         add_msg_debug( debugmode::DF_RADIO, "  %d: %d at (%d %d) str [%d/%d]", i + 1, tref.tower->frequency,
                        dbgpos.x(), dbgpos.y(), tref.signal_strength, tref.tower->strength );
     }
     scanlist.query();
     const int sel = scanlist.ret;
     if( sel >= 0 && static_cast<size_t>( sel ) < options.size() ) {
         it->frequency = options[sel].tower->frequency;
     }
     return 1;
 }
References _, radio_tower_reference::abs_sm_pos, add_msg_debug, uilist::addentry_desc(), uilist::desc_enabled, debugmode::DF_RADIO, cata_path::empty(), overmapbuffer::find_all_radio_stations(), item::frequency, radio_tower::frequency, MENU_AUTOASSIGN, PATH_INFO::options(), overmap_buffer, pgettext, popup(), uilist::query(), radio_static_chance(), snippet_library::random_from_category(), uilist::ret, radio_tower_reference::signal_strength, SNIPPET, radio_tower::strength, string_format(), uilist::title, radio_tower_reference::tower, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Referenced by Item_factory::init().
radio_tick()
std::optional< int > iuse::radio_tick (Character * , item * it, const tripoint & pos)
Definition at line 2528 of file iuse.cpp.
 {
     std::string message = _( "Radio: Kssssssssssssh." );
     const radio_tower_reference tref = overmap_buffer.find_radio_station( it->frequency );
     add_msg_debug( debugmode::DF_RADIO, "Set freq: %d", it->frequency );
     if( tref ) {
         point_abs_omt dbgpos = project_to<coords::omt>( tref.abs_sm_pos );
         add_msg_debug( debugmode::DF_RADIO, "found broadcast (str %d) at (%d %d)",
                        tref.signal_strength, dbgpos.x(), dbgpos.y() );
         const radio_tower *selected_tower = tref.tower;
         if( selected_tower->type == radio_type::MESSAGE_BROADCAST ) {
             message = selected_tower->message;
         } else if( selected_tower->type == radio_type::WEATHER_RADIO ) {
             message = weather_forecast( tref.abs_sm_pos );
         }
         const city *c = overmap_buffer.closest_city( tripoint_abs_sm( tref.abs_sm_pos, 0 ) ).city;
         //~ radio noise
         const std::string cityname = c == nullptr ? _( "ksssh" ) : c->name;
         replace_city_tag( message, cityname );
         int static_chance = radio_static_chance( tref );
         add_msg_debug( debugmode::DF_RADIO, "Message: '%s' at %d%% noise", message, static_chance );
         message = obscure_message( message, [&static_chance]()->int {
             if( x_in_y( static_chance, 100 ) )
             {
                 // Gradually replace random characters with noise as distance increases
                 if( one_in( 3 ) && static_chance - rng( 0, 25 ) < 50 ) {
                     // Replace with random character
                     return 0;
                 }
                 // Replace with '#'
                 return '#';
             }
             // Leave unchanged
             return -1;
         } );
         std::vector<std::string> segments = foldstring( message, RADIO_PER_TURN );
         int index = to_turn<int>( calendar::turn ) % segments.size();
         message = string_format( _( "radio: %s" ), segments[index] );
     }
     sounds::ambient_sound( pos, 6, sounds::sound_t::electronic_speech, message );
     if( !sfx::is_channel_playing( sfx::channel::radio ) ) {
         if( one_in( 10 ) ) {
             sfx::play_ambient_variant_sound( "radio", "static", 100, sfx::channel::radio, 300, -1, 0 );
         } else if( one_in( 10 ) ) {
             sfx::play_ambient_variant_sound( "radio", "inaudible_chatter", 100, sfx::channel::radio, 300, -1,
                                              0 );
         }
     }
     return 1;
 }
References _, radio_tower_reference::abs_sm_pos, add_msg_debug, sounds::ambient_sound(), c, city_reference::city, overmapbuffer::closest_city(), debugmode::DF_RADIO, sounds::electronic_speech, overmapbuffer::find_radio_station(), foldstring(), item::frequency, sfx::is_channel_playing(), mapgen_defer::message, radio_tower::message, MESSAGE_BROADCAST, obscure_message(), one_in(), overmap_buffer, sfx::play_ambient_variant_sound(), math_opers::pos(), sfx::radio, RADIO_PER_TURN, radio_static_chance(), replace_city_tag(), rng(), radio_tower_reference::signal_strength, string_format(), radio_tower_reference::tower, calendar::turn, radio_tower::type, weather_forecast(), WEATHER_RADIO, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), x_in_y(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Referenced by Item_factory::init().
radiocar()
std::optional< int > iuse::radiocar (Character * p, item * it, const tripoint &)
Definition at line 6949 of file iuse.cpp.
 {
     int choice = -1;
     item *bomb_it = it->get_item_with( []( const item & c ) {
         return c.has_flag( flag_RADIOCARITEM );
     } );
     if( bomb_it == nullptr ) {
         choice = uilist( _( "Using RC car:" ), {
             _( "Turn on" ), _( "Put a bomb to car" )
         } );
     } else {
         choice = uilist( _( "Using RC car:" ), {
             _( "Turn on" ), bomb_it->tname()
         } );
     }
     if( choice < 0 ) {
         return std::nullopt;
     }
     if( choice == 0 ) { //Turn car ON
         if( !it->ammo_sufficient( p ) ) {
             p->add_msg_if_player( _( "The RC car's batteries seem to be dead." ) );
             return std::nullopt;
         }
         it->convert( itype_radio_car_on, p ).active = true;
         p->add_msg_if_player(
             _( "You turned on your RC car; now place it on the ground, and use your radio control to play." ) );
         return 0;
     }
     if( choice == 1 ) {
         if( bomb_it == nullptr ) { //arming car with bomb
             avatar *you = p->as_avatar();
             item_location loc;
             if( you != nullptr ) {
                 loc = game_menus::inv::titled_filter_menu( []( const item & it ) {
                     return it.has_flag( flag_RADIOCARITEM );
                 }, *you, _( "Arm what?" ) );
             }
             if( !loc ) {
                 p->add_msg_if_player( m_info, _( "You don't have that item!" ) );
                 return 0;
             }
             item &put = *loc;
             if( put.has_flag( flag_RADIOCARITEM ) && ( put.volume() <= 1250_ml ||
                     ( put.weight() <= 2_kilogram ) ) ) {
                 p->mod_moves( -to_moves<int>( 3_seconds ) );
                 p->add_msg_if_player( _( "You armed your RC car with %s." ),
                                       put.tname() );
                 it->put_in( p->i_rem( &put ), pocket_type::CONTAINER );
             } else if( !put.has_flag( flag_RADIOCARITEM ) ) {
                 p->add_msg_if_player( _( "You want to arm your RC car with %s?  But how?" ),
                                       put.tname() );
             } else {
                 p->add_msg_if_player( _( "Your %s is too heavy or bulky for this RC car." ),
                                       put.tname() );
             }
         } else { // Disarm the car
             p->mod_moves( -to_moves<int>( 2_seconds ) );
             p->inv->assign_empty_invlet( *bomb_it, *p, true ); // force getting an invlet.
             p->i_add( *bomb_it );
             it->remove_item( *bomb_it );
             p->add_msg_if_player( _( "You disarmed your RC car." ) );
         }
     }
     return 1;
 }
References _, item::active, Character::add_msg_if_player(), item::ammo_sufficient(), Creature::as_avatar(), c, CONTAINER, item::convert(), flag_RADIOCARITEM, item::get_item_with(), item::has_flag(), Character::i_add(), Character::i_rem(), Character::inv, itype_radio_car_on, m_info, Creature::mod_moves(), item::put_in(), visitable::remove_item(), game_menus::inv::titled_filter_menu(), item::tname(), item::volume(), and item::weight().
Referenced by Item_factory::init().
radiocaron()
std::optional< int > iuse::radiocaron (Character * p, item * it, const tripoint &)
Definition at line 7026 of file iuse.cpp.
 {
     if( !it->ammo_sufficient( p ) ) {
         // Deactivate since other mode has an iuse too.
         it->convert( itype_radio_car, p ).active = false;
         return 0;
     }
     int choice = uilist( _( "What to do with your activated RC car?" ), {
         _( "Turn off" )
     } );
     if( choice < 0 ) {
         return 1;
     }
     if( choice == 0 ) {
         it->convert( itype_radio_car, p ).active = false;
         p->add_msg_if_player( _( "You turned off your RC car." ) );
         return 1;
     }
     return 1;
 }
References _, item::active, Character::add_msg_if_player(), item::ammo_sufficient(), item::convert(), and itype_radio_car.
Referenced by Item_factory::init().
radiocontrol()
std::optional< int > iuse::radiocontrol (Character * p, item * it, const tripoint &)
Definition at line 7111 of file iuse.cpp.
 {
     const char *car_action = nullptr;
     if( !it->active ) {
         car_action = _( "Take control of RC car" );
     } else {
         car_action = _( "Stop controlling RC car" );
     }
     int choice = uilist( _( "What to do with the radio control?" ), {
         car_action,
         _( "Press red button" ), _( "Press blue button" ), _( "Press green button" )
     } );
     map &here = get_map();
     if( choice < 0 ) {
         return 0;
     } else if( choice == 0 ) {
         if( it->active ) {
             it->active = false;
             p->remove_value( "remote_controlling" );
         } else {
             std::list<std::pair<tripoint, item *>> rc_pairs = here.get_rc_items();
             tripoint rc_item_location = {999, 999, 999};
             // TODO: grab the closest car or similar?
             for( auto &rc_pairs_rc_pair : rc_pairs ) {
                 if( rc_pairs_rc_pair.second->has_flag( flag_RADIOCAR ) &&
                     rc_pairs_rc_pair.second->active ) {
                     rc_item_location = rc_pairs_rc_pair.first;
                 }
             }
             if( rc_item_location.x == 999 ) {
                 p->add_msg_if_player( _( "No active RC cars on ground and in range." ) );
                 return 1;
             } else {
                 std::stringstream car_location_string;
                 // Populate with the point and stash it.
                 car_location_string << rc_item_location.x << ' ' <<
                                     rc_item_location.y << ' ' << rc_item_location.z;
                 p->add_msg_if_player( m_good, _( "You take control of the RC car." ) );
                 p->set_value( "remote_controlling", car_location_string.str() );
                 it->active = true;
             }
         }
     } else {
         const flag_id signal( "RADIOSIGNAL_" + std::to_string( choice ) );
         if( p->cache_has_item_with( flag_BOMB, [&p, &signal]( const item & it ) {
         if( it.has_flag( flag_RADIO_ACTIVATION ) && it.has_flag( signal ) ) {
                 p->add_msg_if_player( m_warning,
                                       _( "The %s in your inventory would explode on this signal.  Place it down before sending the signal." ),
                                       it.display_name() );
                 return true;
             }
             return false;
         } ) ) {
             return std::nullopt;
         }
         if( p->cache_has_item_with( flag_RADIO_CONTAINER, [&p, &signal]( const item & it ) {
         const item *rad_cont = it.get_item_with( [&signal]( const item & c ) {
             return c.has_flag( flag_BOMB ) && c.has_flag( signal );
             } );
             if( rad_cont != nullptr ) {
                 p->add_msg_if_player( m_warning,
                                       _( "The %1$s in your %2$s would explode on this signal.  Place it down before sending the signal." ),
                                       rad_cont->display_name(), it.display_name() );
                 return true;
             }
             return false;
         } ) ) {
             return std::nullopt;
         }
         p->add_msg_if_player( _( "Click." ) );
         sendRadioSignal( *p, signal );
         p->mod_moves( -to_moves<int>( 2_seconds ) );
     }
     return 1;
 }
References _, item::active, Character::add_msg_if_player(), Character::cache_has_item_with(), flag_BOMB, flag_RADIO_CONTAINER, flag_RADIOCAR, get_map(), m_good, Creature::remove_value(), Creature::set_value(), to_string(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by Item_factory::init().
radiocontrol_tick()
std::optional< int > iuse::radiocontrol_tick (Character * p, item * it, const tripoint &)
Definition at line 7092 of file iuse.cpp.
 {
     if( !p ) {
         // Player has dropped the controller
         avatar &player = get_avatar();
         it->active = false;
         player.remove_value( "remote_controlling" );
         return 1;
     }
     if( !it->ammo_sufficient( p ) ) {
         it->active = false;
         p->remove_value( "remote_controlling" );
     } else if( p->get_value( "remote_controlling" ).empty() ) {
         it->active = false;
     }
     return 1;
 }
References item::active, item::ammo_sufficient(), get_avatar(), Creature::get_value(), player, and Creature::remove_value().
Referenced by Item_factory::init().
remoteveh()
std::optional< int > iuse::remoteveh (Character * p, item * it, const tripoint & pos)
Definition at line 7318 of file iuse.cpp.
 {
     vehicle *remote = g->remoteveh();
     bool controlling = it->active && remote != nullptr;
     int choice = uilist( _( "What to do with the remote vehicle control:" ), {
         controlling ? _( "Stop controlling the vehicle." ) : _( "Take control of a vehicle." ),
         _( "Execute one vehicle action" )
     } );
     if( choice < 0 || choice > 1 ) {
         return std::nullopt;
     }
     if( choice == 0 && controlling ) {
         it->active = false;
         g->setremoteveh( nullptr );
         return 0;
     }
     avatar &player_character = get_avatar();
     point p2( player_character.view_offset.xy() );
     vehicle *veh = pickveh( pos, choice == 0 );
     if( veh == nullptr ) {
         return std::nullopt;
     }
     if( !hackveh( *p, *it, *veh ) ) {
         return 0;
     }
     if( choice == 0 ) {
         if( p->has_trait( trait_WAYFARER ) ) {
             add_msg( m_info,
                      _( "Despite using a controller, you still refuse to take control of this vehicle." ) );
         } else {
             it->active = true;
             g->setremoteveh( veh );
             p->add_msg_if_player( m_good, _( "You take control of the vehicle." ) );
             if( !veh->engine_on ) {
                 veh->start_engines();
             }
         }
     } else if( choice == 1 ) {
         const auto rctrl_parts = veh->get_avail_parts( "REMOTE_CONTROLS" );
         const auto electronics_parts = veh->get_avail_parts( "CTRL_ELECTRONIC" );
         // Revert to original behavior if we can't find remote controls.
         if( empty( rctrl_parts ) ) {
             veh->interact_with( electronics_parts.begin()->pos() );
         } else {
             veh->interact_with( rctrl_parts.begin()->pos() );
         }
     }
     player_character.view_offset.x = p2.x;
     player_character.view_offset.y = p2.y;
     return 1;
 }
References _, item::active, add_msg(), Character::add_msg_if_player(), item::empty(), vehicle::engine_on, g, vehicle::get_avail_parts(), get_avatar(), hackveh(), Character::has_trait(), vehicle::interact_with(), m_good, m_info, pickveh(), math_opers::pos(), vehicle::start_engines(), trait_WAYFARER, Character::view_offset, point::x, tripoint::x, tripoint::xy(), point::y, and tripoint::y.
Referenced by Item_factory::init(), and map::shift().
remoteveh_tick()
std::optional< int > iuse::remoteveh_tick (Character * p, item * it, const tripoint &)
Definition at line 7296 of file iuse.cpp.
 {
     vehicle *remote = g->remoteveh();
     bool stop = false;
     if( !it->ammo_sufficient( p ) ) {
         p->add_msg_if_player( m_bad, _( "The remote control's battery goes dead." ) );
         stop = true;
     } else if( remote == nullptr ) {
         p->add_msg_if_player( _( "Lost contact with the vehicle." ) );
         stop = true;
     } else if( remote->fuel_left( itype_battery ) == 0 ) {
         p->add_msg_if_player( m_bad, _( "The vehicle's battery died." ) );
         stop = true;
     }
     if( stop ) {
         it->active = false;
         g->setremoteveh( nullptr );
     }
     return 1;
 }
References _, item::active, Character::add_msg_if_player(), item::ammo_sufficient(), vehicle::fuel_left(), g, itype_battery, and m_bad.
Referenced by Item_factory::init().
remove_all_mods()
std::optional< int > iuse::remove_all_mods (Character * p, item * , const tripoint &)
Definition at line 1698 of file iuse.cpp.
 {
     if( !p ) {
         return std::nullopt;
     }
     item_location loc = g->inv_map_splice( []( const item & e ) {
         for( const item *it : e.toolmods() ) {
             if( !it->is_irremovable() ) {
                 return true;
             }
         }
         return false;
     },
     _( "Remove mods from tool?" ), 1,
     _( "You don't have any modified tools." ) );
     if( !loc ) {
         add_msg( m_info, _( "Never mind." ) );
         return std::nullopt;
     }
     if( !loc->ammo_remaining() || p->unload( loc ) ) {
         item *mod = loc->get_item_with(
         []( const item & e ) {
             return e.is_toolmod() && !e.is_irremovable();
         } );
         add_msg( m_info, _( "You remove the %s from the tool." ), mod->tname() );
         p->i_add_or_drop( *mod );
         loc->remove_item( *mod );
         remove_radio_mod( *loc, *p );
         loc->on_contents_changed();
     }
     return 0;
 }
References g, and item::toolmods().
Referenced by Item_factory::init().
robotcontrol()
std::optional< int > iuse::robotcontrol (Character * p, item * it, const tripoint &)
Intelligence speeds up hacking preparation Computer speeds up hacking preparation
Definition at line 5319 of file iuse.cpp.
 {
     bool isComputer = !it->has_flag( flag_MAGICAL );
     int choice = 0;
     if( isComputer ) {
         if( !it->ammo_sufficient( p ) ) {
             p->add_msg_if_player( _( "The %s's batteries are dead." ), it->tname() );
             return std::nullopt;
         }
         if( p->has_trait( trait_ILLITERATE ) ) {
             p->add_msg_if_player( _( "You can't read a computer screen." ) );
             return std::nullopt;
         }
         if( p->has_flag( json_flag_HYPEROPIC ) && !p->worn_with_flag( flag_FIX_FARSIGHT ) &&
             !p->has_effect( effect_contacts ) && !p->has_effect( effect_transition_contacts ) &&
             !p->has_flag( json_flag_ENHANCED_VISION ) ) {
             p->add_msg_if_player( m_info,
                                   _( "You'll need to put on reading glasses before you can see the screen." ) );
             return std::nullopt;
         }
         choice = uilist( _( "Welcome to hackPRO!" ), {
             _( "Prepare IFF protocol override" ),
             _( "Set friendly robots to passive mode" ),
             _( "Set friendly robots to combat mode" )
         } );
     } else {
         if( !it->ammo_sufficient( p ) ) {
             p->add_msg_if_player( _( "The %s lacks charge to function." ), it->tname() );
             return std::nullopt;
         }
         choice = uilist( _( "You prepare to manipulate nearby robots!" ), {
             _( "Prepare IFF protocol override" ),
             _( "Set friendly robots to passive mode" ),
             _( "Set friendly robots to combat mode" )
         } );
     }
     switch( choice ) {
         case 0: { // attempt to make a robot friendly
             uilist pick_robot;
             pick_robot.text = _( "Choose an endpoint to hack." );
             // Build a list of all unfriendly robots in range.
             // TODO: change into vector<Creature*>
             std::vector< shared_ptr_fast< monster> > mons;
             std::vector< tripoint > locations;
             int entry_num = 0;
             for( const monster &candidate : g->all_monsters() ) {
                 if( robotcontrol_can_target( p, candidate ) ) {
                     mons.push_back( g->shared_from( candidate ) );
                     pick_robot.addentry( entry_num++, true, MENU_AUTOASSIGN, candidate.name() );
                     tripoint seen_loc;
                     // Show locations of seen robots, center on player if robot is not seen
                     if( p->sees( candidate ) ) {
                         seen_loc = candidate.pos();
                     } else {
                         seen_loc = p->pos();
                     }
                     locations.push_back( seen_loc );
                 }
             }
             if( mons.empty() ) {
                 p->add_msg_if_player( m_info, _( "No enemy robots in range." ) );
                 return 1;
             }
             pointmenu_cb callback( locations );
             pick_robot.callback = &callback;
             pick_robot.query();
             if( pick_robot.ret < 0 || static_cast<size_t>( pick_robot.ret ) >= mons.size() ) {
                 p->add_msg_if_player( m_info, _( "Never mind" ) );
                 return 1;
             }
             const size_t mondex = pick_robot.ret;
             shared_ptr_fast< monster > z = mons[mondex];
             p->add_msg_if_player( _( "You start reprogramming the %s into an ally." ), z->name() );
             /** @EFFECT_INT speeds up hacking preparation */
             /** @EFFECT_COMPUTER speeds up hacking preparation */
             int move_cost = std::max( 100,
                                       1000 - static_cast<int>( p->int_cur * 10 - p->get_skill_level( skill_computer ) * 10 ) );
             player_activity act( ACT_ROBOT_CONTROL, move_cost );
             act.monsters.emplace_back( z );
             p->assign_activity( act );
             return 1;
         }
         case 1: { //make all friendly robots stop their purposeless extermination of (un)life.
             p->mod_moves( -to_moves<int>( 1_seconds ) );
             int f = 0; //flag to check if you have robotic allies
             for( monster &critter : g->all_monsters() ) {
                 if( critter.friendly != 0 && critter.type->in_species( species_ROBOT ) ) {
                     p->add_msg_if_player( _( "A following %s goes into passive mode." ),
                                           critter.name() );
                     critter.add_effect( effect_docile, 1_turns, true );
                     f = 1;
                 }
             }
             if( f == 0 ) {
                 p->add_msg_if_player( _( "You aren't commanding any robots." ) );
                 return std::nullopt;
             }
             return 1;
         }
         case 2: { //make all friendly robots terminate (un)life with extreme prejudice
             p->mod_moves( -to_moves<int>( 1_seconds ) );
             int f = 0; //flag to check if you have robotic allies
             for( monster &critter : g->all_monsters() ) {
                 if( critter.friendly != 0 && critter.has_flag( mon_flag_ELECTRONIC ) ) {
                     p->add_msg_if_player( _( "A following %s goes into combat mode." ),
                                           critter.name() );
                     critter.remove_effect( effect_docile );
                     f = 1;
                 }
             }
             if( f == 0 ) {
                 p->add_msg_if_player( _( "You aren't commanding any robots." ) );
                 return std::nullopt;
             }
             return 1;
         }
     }
     return 0;
 }
References _, act, ACT_ROBOT_CONTROL, Character::add_msg_if_player(), uilist::addentry(), item::ammo_sufficient(), Character::assign_activity(), uilist::callback, effect_contacts, effect_docile, effect_transition_contacts, flag_FIX_FARSIGHT, flag_MAGICAL, g, Character::get_skill_level(), Creature::has_effect(), item::has_flag(), Character::has_flag(), Character::has_trait(), Character::int_cur, json_flag_ENHANCED_VISION, json_flag_HYPEROPIC, anonymous_namespace{overmap_location.cpp}::locations, m_info, max(), MENU_AUTOASSIGN, Creature::mod_moves(), mon_flag_ELECTRONIC, Creature::pos(), uilist::query(), uilist::ret, robotcontrol_can_target(), Character::sees(), skill_computer, species_ROBOT, uilist::text, item::tname(), trait_ILLITERATE, and Character::worn_with_flag().
Referenced by Item_factory::init().
robotcontrol_can_target()
bool iuse::robotcontrol_can_target (Character * p, const monster & m)
Definition at line 5311 of file iuse.cpp.
 {
     return !m.is_dead()
            && m.type->in_species( species_ROBOT )
            && m.friendly == 0
            && rl_dist( p->pos(), m.pos() ) <= 10;
 }
References monster::friendly, mtype::in_species(), monster::is_dead(), Creature::pos(), rl_dist(), species_ROBOT, and monster::type.
Referenced by activity_handlers::robot_control_do_turn(), activity_handlers::robot_control_finish(), and robotcontrol().
rpgdie()
std::optional< int > iuse::rpgdie (Character * you, item * die, const tripoint &)
Definition at line 3839 of file iuse.cpp.
 {
     if( you->cant_do_mounted() ) {
         return std::nullopt;
     }
     int num_sides = die->get_var( "die_num_sides", 0 );
     if( num_sides == 0 ) {
         const std::vector<int> sides_options = { 4, 6, 8, 10, 12, 20, 50 };
         const int sides = sides_options[ rng( 0, sides_options.size() - 1 ) ];
         num_sides = sides;
         die->set_var( "die_num_sides", sides );
     }
     const int roll = rng( 1, num_sides );
     //~ %1$d: roll number, %2$d: side number of a die, %3$s: die item name
     you->add_msg_if_player( pgettext( "dice", "You roll a %1$d on your %2$d sided %3$s" ), roll,
                             num_sides, die->tname() );
     if( roll == num_sides ) {
         add_msg( m_good, _( "Critical!" ) );
     }
     return roll;
 }
References _, add_msg(), Character::add_msg_if_player(), Character::cant_do_mounted(), item::get_var(), m_good, num_sides, pgettext, rng(), item::set_var(), and item::tname().
Referenced by Item_factory::init().
seed()
std::optional< int > iuse::seed (Character * p, item * it, const tripoint &)
Definition at line 5301 of file iuse.cpp.
 {
     if( p->is_npc() ||
         query_yn( _( "Are you sure you want to eat the %s?  You could plant it in a mound of dirt." ),
                   colorize( it->tname(), it->color_in_inventory() ) ) ) {
         return 1; //This eats the seed object.
     }
     return std::nullopt;
 }
References _, item::color_in_inventory(), colorize(), Character::is_npc(), query_yn(), and item::tname().
Referenced by computer_session::action_research(), iexamine::aggie_plant(), cata::tuple_hash_detail::Impl< Tuple, Index >::apply(), cata::tuple_hash_detail::Impl< Tuple, 0 >::apply(), can_do_activity_there(), farm_action(), iexamine::fertilize_plant(), talk_function::field_harvest(), talk_function::field_plant(), map::furnname(), generic_multi_activity_do(), get_common_data(), iexamine::get_seed_entries(), weather_generator::get_weather(), weather_generator::get_weather_conditions(), weather_generator::get_weather_temperature(), map::grow_plant(), iexamine::harvest_plant(), iexamine::harvest_plant_ex(), cata::hash_combine(), Item_factory::init(), vehicle::operate_reaper(), cata::range_hash::operator()(), cata::tuple_hash::operator()(), snippet_library::random_from_category(), rng_get_first_seed(), rng_sequence(), rng_set_engine_seed(), fungal_effects::spread_fungus_one_tile(), basecamp::start_farm_op(), and weather_generator::test_weather().
sewage()
std::optional< int > iuse::sewage (Character * p, item * , const tripoint &)
Definition at line 467 of file iuse.cpp.
 {
     if( !p->query_yn( _( "Are you sure you want to drink this?" ) ) ) {
         return std::nullopt;
     }
     get_event_bus().send<event_type::eats_sewage>();
     p->vomit();
     return 1;
 }
References _, eats_sewage, get_event_bus(), Character::query_yn(), event_bus::send(), and Character::vomit().
Referenced by computer_session::action_sample(), and Item_factory::init().
sextant()
std::optional< int > iuse::sextant (Character * p, item * , const tripoint & pos)
Definition at line 7851 of file iuse.cpp.
 {
     const std::pair<units::angle, units::angle> sun_position = sun_azimuth_altitude( calendar::turn );
     const float altitude = to_degrees( sun_position.second );
     if( debug_mode ) {
         // Debug mode always shows all sun angles
         const float azimuth = to_degrees( sun_position.first );
         p->add_msg_if_player( m_neutral, "Sun altitude %.1f, azimuth %.1f", altitude, azimuth );
     } else if( g->is_sheltered( pos ) ) {
         p->add_msg_if_player( m_neutral, _( "You can't see the Sun from here." ) );
     } else if( altitude > 0 ) {
         p->add_msg_if_player( m_neutral, _( "The Sun is at an altitude of %.1f." ), altitude );
     } else {
         p->add_msg_if_player( m_neutral, _( "The Sun is below the horizon." ) );
     }
     return 0;
 }
References _, Character::add_msg_if_player(), debug_mode, g, m_neutral, math_opers::pos(), sun_azimuth_altitude(), units::to_degrees(), and calendar::turn.
Referenced by Item_factory::init().
shavekit()
std::optional<int> iuse::shavekit (Character * , item * , const tripoint &)
shocktonfa_off()
std::optional< int > iuse::shocktonfa_off (Character * p, item * it, const tripoint & pos)
Definition at line 3662 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action shocktonfa_off that requires character but no character is present",
                   it->typeId().str() );
     }
     int choice = uilist( _( "tactical tonfa" ), {
         _( "Zap something" ), _( "Turn on light" )
     } );
     switch( choice ) {
         case 0: {
             return iuse::tazer2( p, it, pos );
         }
         case 1: {
             if( !it->ammo_sufficient( p ) ) {
                 p->add_msg_if_player( m_info, _( "The batteries are dead." ) );
                 return std::nullopt;
             } else {
                 p->add_msg_if_player( _( "You turn the light on." ) );
                 it->convert( itype_shocktonfa_on, p ).active = true;
                 return 1;
             }
         }
     }
     return 0;
 }
References _, item::active, Character::add_msg_if_player(), item::ammo_sufficient(), item::convert(), debugmsg, itype_shocktonfa_on, m_info, math_opers::pos(), string_id< T >::str(), tazer2(), and item::typeId().
Referenced by Item_factory::init().
shocktonfa_on()
std::optional< int > iuse::shocktonfa_on (Character * p, item * it, const tripoint & pos)
Definition at line 3690 of file iuse.cpp.
 {
     if( !p ) { // Effects while simply on
         debugmsg( "%s called action shocktonfa_on that requires character but no character is present",
                   it->typeId().str() );
     } else {
         if( !it->ammo_sufficient( p ) ) {
             p->add_msg_if_player( m_info, _( "Your tactical tonfa is out of power." ) );
             it->convert( itype_shocktonfa_off, p ).active = false;
         } else {
             int choice = uilist( _( "tactical tonfa" ), {
                 _( "Zap something" ), _( "Turn off light" )
             } );
             switch( choice ) {
                 case 0: {
                     return iuse::tazer2( p, it, pos );
                 }
                 case 1: {
                     p->add_msg_if_player( _( "You turn off the light." ) );
                     it->convert( itype_shocktonfa_off, p ).active = false;
                 }
             }
         }
     }
     return 0;
 }
References _, item::active, Character::add_msg_if_player(), item::ammo_sufficient(), item::convert(), debugmsg, itype_shocktonfa_off, m_info, math_opers::pos(), string_id< T >::str(), tazer2(), and item::typeId().
Referenced by Item_factory::init().
siphon()
std::optional< int > iuse::siphon (Character * p, item * , const tripoint &)
Definition at line 2914 of file iuse.cpp.
 {
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     map &here = get_map();
     const std::function<bool( const tripoint & )> f = [&here]( const tripoint & pnt ) {
         const optional_vpart_position vp = here.veh_at( pnt );
         return !!vp;
     };
     vehicle *v = nullptr;
     bool found_more_than_one = false;
     for( const tripoint &pos : here.points_in_radius( p->pos(), 1 ) ) {
         const optional_vpart_position vp = here.veh_at( pos );
         if( !vp ) {
             continue;
         }
         vehicle *vfound = &vp->vehicle();
         if( v == nullptr ) {
             v = vfound;
         } else {
             //found more than one vehicle?
             if( v != vfound ) {
                 v = nullptr;
                 found_more_than_one = true;
                 break;
             }
         }
     }
     if( found_more_than_one ) {
         std::optional<tripoint> pnt_ = choose_adjacent_highlight(
                                            _( "Siphon from where?" ), _( "There is nothing to siphon from nearby." ), f, false );
         if( !pnt_ ) {
             return std::nullopt;
         }
         const optional_vpart_position vp = here.veh_at( *pnt_ );
         if( vp ) {
             v = &vp->vehicle();
         }
     }
     if( v == nullptr ) {
         p->add_msg_if_player( m_info, _( "There's no vehicle there." ) );
         return std::nullopt;
     }
     act_vehicle_siphon( v );
     return 1;
 }
References _, act_vehicle_siphon(), Character::add_msg_if_player(), Character::cant_do_mounted(), choose_adjacent_highlight(), get_map(), m_info, map::points_in_radius(), Creature::pos(), math_opers::pos(), and map::veh_at().
Referenced by Item_factory::init().
smoking()
std::optional< int > iuse::smoking (Character * p, item * it, const tripoint &)
Entry point for intentional bodily intake of smoke via paper wrapped one time use items: cigars, cigarettes, etc.
Parameters
p Player doing the smoking
it the item to be smoked.
Returns
Charges used in item smoked
Definition at line 544 of file iuse.cpp.
 {
     std::optional<std::string> litcig = can_smoke( *p );
     if( litcig.has_value() ) {
         p->add_msg_if_player( m_info, _( litcig.value_or( "" ) ) );
         return std::nullopt;
     }
     item cig;
     if( it->typeId() == itype_cig || it->typeId() == itype_handrolled_cig ) {
         cig = item( "cig_lit", calendar::turn );
         cig.item_counter = to_turns<int>( 4_minutes );
         p->mod_hunger( -3 );
         p->mod_thirst( 2 );
     } else if( it->typeId() == itype_cigar ) {
         cig = item( "cigar_lit", calendar::turn );
         cig.item_counter = to_turns<int>( 12_minutes );
         p->mod_thirst( 3 );
         p->mod_hunger( -4 );
     } else if( it->typeId() == itype_joint ) {
         cig = item( "joint_lit", calendar::turn );
         cig.item_counter = to_turns<int>( 4_minutes );
         p->mod_hunger( 4 );
         p->mod_thirst( 6 );
         if( p->get_painkiller() < 5 ) {
             p->set_painkiller( ( p->get_painkiller() + 3 ) * 2 );
         }
     } else {
         p->add_msg_if_player( m_bad,
                               _( "Please let the devs know you should be able to smoke a %s, but the smoking code does not know how." ),
                               it->tname() );
         return std::nullopt;
     }
     // If we're here, we better have a cig to light.
     p->use_charges_if_avail( itype_fire, 1 );
     cig.active = true;
     p->inv->add_item( cig, false, true );
     p->add_msg_if_player( m_neutral, _( "You light a %s." ), cig.tname() );
     // Parting messages
     if( it->typeId() == itype_joint ) {
         // Would group with the joint, but awkward to mutter before lighting up.
         if( one_in( 5 ) ) {
             weed_msg( *p );
         }
     }
     if( p->get_effect_dur( effect_cig ) > 10_minutes * ( p->addiction_level(
                 addiction_nicotine ) + 1 ) ) {
         p->add_msg_if_player( m_bad, _( "Ugh, too much smoke you feel nasty." ) );
     }
     return 1;
 }
References _, item::active, Character::add_msg_if_player(), Character::addiction_level(), addiction_nicotine, can_smoke(), effect_cig, Creature::get_effect_dur(), Character::get_painkiller(), Character::inv, item, item::item_counter, itype_cig, itype_cigar, itype_fire, itype_handrolled_cig, itype_joint, m_bad, m_info, m_neutral, Character::mod_hunger(), Character::mod_thirst(), one_in(), Character::set_painkiller(), item::tname(), calendar::turn, item::typeId(), Character::use_charges_if_avail(), and weed_msg().
Referenced by Character::can_eat(), Character::get_consume_time(), activatable_inventory_preset::get_denial(), and Item_factory::init().
solarpack()
std::optional< int > iuse::solarpack (Character * p, item * it, const tripoint &)
Definition at line 3903 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action solarpack that requires character but no character is present",
                   it->typeId().str() );
         return std::nullopt;
     }
     const bionic_id rem_bid = p->get_remote_fueled_bionic();
     if( rem_bid.is_empty() ) {  // Cable CBM required
         p->add_msg_if_player(
             _( "You have no cable charging system to plug it into, so you leave it alone." ) );
         return std::nullopt;
     } else if( !p->has_active_bionic( rem_bid ) ) {  // when OFF it takes no effect
         p->add_msg_if_player( _( "Activate your cable charging system to take advantage of it." ) );
     }
     if( it->is_armor() && !p->is_worn( *it ) ) {
         p->add_msg_if_player( m_neutral, _( "You need to wear the %1$s before you can unfold it." ),
                               it->tname() );
         return std::nullopt;
     }
     // no doubled sources of power
     if( p->worn_with_flag( flag_SOLARPACK_ON ) ) {
         p->add_msg_if_player( m_neutral, _( "You can't use the %1$s with another of its kind." ),
                               it->tname() );
         return std::nullopt;
     }
     p->add_msg_if_player(
         _( "You unfold the solar array from the pack.  You still need to connect it with a cable." ) );
     it->convert( itype_id( it->typeId().str() + "_on" ), p );
     return 0;
 }
References _, Character::add_msg_if_player(), item::convert(), debugmsg, flag_SOLARPACK_ON, Character::get_remote_fueled_bionic(), Character::has_active_bionic(), item::is_armor(), string_id< T >::is_empty(), Character::is_worn(), m_neutral, string_id< T >::str(), item::tname(), item::typeId(), and Character::worn_with_flag().
Referenced by Item_factory::init().
solarpack_off()
std::optional< int > iuse::solarpack_off (Character * p, item * it, const tripoint &)
Definition at line 3937 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action solarpack_off that requires character but no character is present",
                   it->typeId().str() );
         return std::nullopt;
     }
     if( !p->is_worn( *it ) ) {  // folding when not worn
         p->add_msg_if_player( _( "You fold your portable solar array into the pack." ) );
     } else {
         p->add_msg_if_player( _( "You unplug your portable solar array, and fold it into the pack." ) );
     }
     it->erase_var( "cable" );
     // 3 = "_on"
     it->convert( itype_id( it->typeId().str().substr( 0,
                            it->typeId().str().size() - 3 ) ), p ).active = false;
     p->process_items(); // Process carried items to disconnect any connected cables
     return 0;
 }
References _, item::active, Character::add_msg_if_player(), item::convert(), debugmsg, item::erase_var(), Character::is_worn(), Character::process_items(), string_id< T >::str(), and item::typeId().
Referenced by Item_factory::init().
spray_can()
std::optional< int > iuse::spray_can (Character * p, item * it, const tripoint &)
Definition at line 4808 of file iuse.cpp.
 {
     const std::optional<tripoint> dest_ = choose_adjacent( _( "Spray where?" ) );
     if( !dest_ ) {
         return std::nullopt;
     }
     return handle_ground_graffiti( *p, it, _( "Spray what?" ), dest_.value() );
 }
References _, choose_adjacent(), and handle_ground_graffiti().
Referenced by Item_factory::init().
stimpack()
std::optional< int > iuse::stimpack (Character * p, item * it, const tripoint &)
Definition at line 5073 of file iuse.cpp.
 {
     if( p->get_item_position( it ) >= -1 ) {
         p->add_msg_if_player( m_info,
                               _( "You must wear the stimulant delivery system before you can activate it." ) );
         return std::nullopt;
     }
     if( !it->ammo_sufficient( p ) ) {
         p->add_msg_if_player( m_info, _( "The stimulant delivery system is empty." ) );
         return std::nullopt;
     } else {
         p->add_msg_if_player( _( "You inject yourself with the stimulants." ) );
         // Intensity is 2 here because intensity = 1 is the comedown
         p->add_effect( effect_stimpack, 25_minutes, false, 2 );
         p->mod_painkiller( 2 );
         p->mod_stim( 20 );
         p->mod_sleepiness( -100 );
         p->set_stamina( p->get_stamina_max() );
     }
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), item::ammo_sufficient(), effect_stimpack, Character::get_item_position(), Character::get_stamina_max(), m_info, Character::mod_painkiller(), Character::mod_sleepiness(), Character::mod_stim(), and Character::set_stamina().
Referenced by Item_factory::init().
strong_antibiotic()
std::optional< int > iuse::strong_antibiotic (Character * p, item * it, const tripoint &)
Definition at line 8299 of file iuse.cpp.
 {
     p->add_msg_if_player( _( "You take some %s." ), it->tname() );
     if( p->has_effect( effect_infected ) && !p->has_effect( effect_strong_antibiotic ) ) {
         p->add_msg_if_player( m_good, _( "You feel much better - almost entirely." ) );
     }
     p->add_effect( effect_strong_antibiotic, 12_hours );
     p->add_effect( effect_strong_antibiotic_visible, rng( 9_hours, 15_hours ) );
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), effect_infected, effect_strong_antibiotic, effect_strong_antibiotic_visible, Creature::has_effect(), m_good, rng(), and item::tname().
Referenced by Item_factory::init().
talking_doll()
std::optional< int > iuse::talking_doll (Character * p, item * it, const tripoint &)
Definition at line 5124 of file iuse.cpp.
 {
     if( !it->ammo_sufficient( p ) ) {
         p->add_msg_if_player( m_info, _( "The %s's batteries are dead." ), it->tname() );
         return std::nullopt;
     }
     p->add_msg_if_player( m_neutral, _( "You press a button on the doll to make it talk." ) );
     const SpeechBubble speech = get_speech( it->typeId().str() );
     sounds::sound( p->pos(), speech.volume, sounds::sound_t::electronic_speech,
                    speech.text.translated(), true, "speech", it->typeId().str() );
     return 1;
 }
References _, Character::add_msg_if_player(), item::ammo_sufficient(), sounds::electronic_speech, get_speech(), m_info, m_neutral, Creature::pos(), sounds::sound(), speech, string_id< T >::str(), item::tname(), and item::typeId().
Referenced by Item_factory::init().
tazer()
std::optional< int > iuse::tazer (Character * p, item * it, const tripoint & pos)
Definition at line 3574 of file iuse.cpp.
 {
     if( !it->ammo_sufficient( p ) ) {
         return std::nullopt;
     }
     tripoint pnt = pos;
     if( pos == p->pos() ) {
         const std::optional<tripoint> pnt_ = choose_adjacent( _( "Shock where?" ) );
         if( !pnt_ ) {
             return std::nullopt;
         }
         pnt = *pnt_;
     }
     if( pnt == p->pos() ) {
         p->add_msg_if_player( m_info, _( "Umm.  No." ) );
         return std::nullopt;
     }
     Creature *target = get_creature_tracker().creature_at( pnt, true );
     if( target == nullptr ) {
         p->add_msg_if_player( _( "There's nothing to zap there!" ) );
         return std::nullopt;
     }
     npc *foe = dynamic_cast<npc *>( target );
     if( foe != nullptr &&
         !foe->is_enemy() &&
         !p->query_yn( _( "Do you really want to shock %s?" ), target->disp_name() ) ) {
         return std::nullopt;
     }
     const float hit_roll = p->hit_roll();
     p->mod_moves( -to_moves<int>( 1_seconds ) );
     const bool tazer_was_dodged = target->dodge_check( p->hit_roll() );
     const bool tazer_was_armored = hit_roll < target->get_armor_type( STATIC(
                                        damage_type_id( "bash" ) ), bodypart_id( "torso" ) );
     if( tazer_was_dodged ) {
         p->add_msg_player_or_npc( _( "You attempt to shock %s, but miss." ),
                                   _( "<npcname> attempts to shock %s, but misses." ),
                                   target->disp_name() );
     } else if( tazer_was_armored ) {
         p->add_msg_player_or_npc( _( "You attempt to shock %s, but are blocked by armor." ),
                                   _( "<npcname> attempts to shock %s, but is blocked by armor." ),
                                   target->disp_name() );
     } else {
         // Stun duration scales harshly inversely with big creatures
         if( target->get_size() == creature_size::tiny ) {
             target->mod_moves( -to_moves<int>( 1_seconds ) * rng_float( 1.5, 2.5 ) );
         } else if( target->get_size() == creature_size::small ) {
             target->mod_moves( -to_moves<int>( 1_seconds ) * rng_float( 1.25, 2.0 ) );
         } else if( target->get_size() == creature_size::large ) {
             target->mod_moves( -to_moves<int>( 1_seconds ) * rng_float( 0.95, 1.15 ) );
         } else if( target->get_size() == creature_size::huge ) {
             target->mod_moves( -to_moves<int>( 1_seconds ) * rng_float( 0.5, 0.8 ) );
         } else {
             target->mod_moves( -to_moves<int>( 1_seconds ) * rng_float( 1.1, 1.5 ) );
         }
         p->add_msg_player_or_npc( m_good,
                                   _( "You shock %s!" ),
                                   _( "<npcname> shocks %s!" ),
                                   target->disp_name() );
     }
     if( foe != nullptr ) {
         foe->on_attacked( *p );
     }
     return 1;
 }
References _, Character::add_msg_if_player(), Character::add_msg_player_or_npc(), item::ammo_sufficient(), choose_adjacent(), creature_tracker::creature_at(), Creature::disp_name(), Creature::dodge_check(), Creature::get_armor_type(), get_creature_tracker(), Creature::get_size(), Character::hit_roll(), huge, npc::is_enemy(), large, m_good, m_info, Creature::mod_moves(), npc::on_attacked(), Creature::pos(), math_opers::pos(), Character::query_yn(), rng_float(), small, STATIC, and tiny.
Referenced by Item_factory::init(), and tazer2().
tazer2()
std::optional< int > iuse::tazer2 (Character * p, item * it, const tripoint & pos)
Definition at line 3647 of file iuse.cpp.
 {
     if( it->ammo_remaining( p, true ) >= 2 ) {
         // Instead of having a ctrl+c+v of the function above, spawn a fake tazer and use it
         // Ugly, but less so than copied blocks
         item fake( "tazer", calendar::turn_zero );
         fake.charges = 2;
         return tazer( p, &fake, pos );
     } else {
         p->add_msg_if_player( m_info, _( "Insufficient power" ) );
     }
     return std::nullopt;
 }
References _, Character::add_msg_if_player(), item::ammo_remaining(), item::charges, m_info, math_opers::pos(), tazer(), and calendar::turn_zero.
Referenced by Item_factory::init(), shocktonfa_off(), and shocktonfa_on().
teleport()
std::optional< int > iuse::teleport (Character * p, item * it, const tripoint &)
Definition at line 3208 of file iuse.cpp.
 {
     if( p->is_npc() ) {
         // That would be evil
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     if( !it->ammo_sufficient( p ) ) {
         return std::nullopt;
     }
     p->mod_moves( -to_moves<int>( 1_seconds ) );
     teleport::teleport( *p );
     return 1;
 }
References item::ammo_sufficient(), Character::cant_do_mounted(), Character::is_npc(), Creature::mod_moves(), and teleport::teleport().
Referenced by Item_factory::init().
thorazine()
std::optional< int > iuse::thorazine (Character * p, item * , const tripoint &)
Definition at line 948 of file iuse.cpp.
 {
     if( p->has_effect( effect_took_thorazine ) ) {
         p->remove_effect( effect_took_thorazine );
         p->mod_sleepiness( 15 );
     }
     p->add_effect( effect_took_thorazine, 12_hours );
     p->mod_sleepiness( 5 );
     p->remove_effect( effect_hallu );
     p->remove_effect( effect_visuals );
     p->remove_effect( effect_high );
     if( !p->has_effect( effect_dermatik ) ) {
         p->remove_effect( effect_formication );
     }
     if( one_in( 50 ) ) { // adverse reaction
         p->add_msg_if_player( m_bad, _( "You feel completely exhausted." ) );
         p->mod_sleepiness( 15 );
         p->add_effect( effect_took_thorazine_bad, p->get_effect_dur( effect_took_thorazine ) );
     } else {
         p->add_msg_if_player( m_warning, _( "You feel a bit wobbly." ) );
     }
     p->add_effect( effect_took_thorazine_visible, rng( 9_hours, 15_hours ) );
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), effect_dermatik, effect_formication, effect_hallu, effect_high, effect_took_thorazine, effect_took_thorazine_bad, effect_took_thorazine_visible, effect_visuals, Creature::get_effect_dur(), Creature::has_effect(), m_bad, m_warning, Character::mod_sleepiness(), one_in(), Creature::remove_effect(), and rng().
Referenced by Item_factory::init().
toolmod_attach()
std::optional< int > iuse::toolmod_attach (Character * p, item * it, const tripoint &)
Definition at line 5231 of file iuse.cpp.
 {
     if( !it || !it->is_toolmod() ) {
         debugmsg( "tried to attach non-toolmod" );
         return std::nullopt;
     }
     if( !p ) {
         return std::nullopt;
     }
     auto filter = [&it]( const item & e ) {
         // don't allow ups or bionic battery mods on a UPS or UPS-powered/bionic-powered tools
         if( ( it->has_flag( flag_USE_UPS ) || it->has_flag( flag_USES_BIONIC_POWER ) ) &&
             ( e.has_flag( flag_IS_UPS ) || e.has_flag( flag_USE_UPS ) ||
               e.has_flag( flag_USES_BIONIC_POWER ) ) ) {
             return false;
         }
         // can't mod non-tool, or a tool with existing mods, or a battery currently installed
         if( !e.is_tool() || !e.toolmods().empty() || e.magazine_current() ) {
             return false;
         }
         // can only attach to unmodified tools that use compatible ammo
         return std::any_of( it->type->mod->acceptable_ammo.begin(),
         it->type->mod->acceptable_ammo.end(), [&]( const ammotype & at ) {
             return e.type->tool->ammo_id.count( at );
         } );
     };
     item_location loc = g->inv_map_splice( filter, _( "Select tool to modify:" ), 1,
                                            _( "You don't have compatible tools." ) );
     if( !loc ) {
         add_msg( m_info, _( "Never mind." ) );
         return std::nullopt;
     }
     if( loc->ammo_remaining() ) {
         if( !p->unload( loc ) ) {
             p->add_msg_if_player( m_info, _( "You cancel unloading the tool." ) );
             return std::nullopt;
         }
     }
     p->toolmod_add( std::move( loc ), item_location( *p, it ) );
     return 0;
 }
References _, add_msg(), Character::add_msg_if_player(), item::ammo_remaining(), debugmsg, filter, flag_IS_UPS, flag_USE_UPS, flag_USES_BIONIC_POWER, g, item::has_flag(), item::is_tool(), item::is_toolmod(), m_info, item::magazine_current(), itype::mod, Character::toolmod_add(), item::toolmods(), item::type, and Character::unload().
Referenced by Item_factory::init().
towel()
std::optional< int > iuse::towel (Character * p, item * it, const tripoint &)
Definition at line 4948 of file iuse.cpp.
 {
     return towel_common( p, it, false );
 }
References towel_common().
Referenced by Item_factory::init().
towel_common()
int iuse::towel_common (Character * p, item * it, bool)
Definition at line 4953 of file iuse.cpp.
 {
     if( !p ) {
         debugmsg( "%s called action towel that requires character but no character is present",
                   it->typeId().str() );
         return 0;
     }
     bool slime = p->has_effect( effect_slimed );
     bool boom = p->has_effect( effect_boomered );
     bool glow = p->has_effect( effect_glowing );
     int mult = slime + boom + glow; // cleaning off more than one at once makes it take longer
     bool towelUsed = false;
     const std::string name = it ? it->tname() : _( "towel" );
     // can't use an already wet towel!
     if( it && it->is_filthy() ) {
         p->add_msg_if_player( m_info, _( "That %s is too filthy to clean anything!" ),
                               it->tname() );
     } else if( it && it->has_flag( flag_WET ) ) {
         p->add_msg_if_player( m_info, _( "That %s is too wet to soak up any more liquid!" ),
                               it->tname() );
         // clean off the messes first, more important
     } else if( slime || boom || glow ) {
         p->remove_effect( effect_slimed ); // able to clean off all at once
         p->remove_effect( effect_boomered );
         p->remove_effect( effect_glowing );
         p->add_msg_if_player( _( "You use the %s to clean yourself off, saturating it with slime!" ),
                               name );
         towelUsed = true;
         if( it && it->typeId() == itype_towel ) {
             it->set_flag( flag_FILTHY );
         }
         // dry off from being wet
     } else if( p->has_atleast_one_wet_part() ) {
         p->rem_morale( MORALE_WET );
         p->set_all_parts_wetness( 0 );
         p->add_msg_if_player( _( "You use the %s to dry off, saturating it with water!" ),
                               name );
         towelUsed = true;
         if( it && it->typeId() == itype_towel ) {
             it->item_counter = to_turns<int>( 30_minutes );
             // change "towel" to a "towel_wet" (different flavor text/color)
             it->convert( itype_towel_wet, p );
         }
         // default message
     } else {
         p->add_msg_if_player( _( "You are already dry; the %s does nothing." ), name );
     }
     // towel was used
     if( towelUsed ) {
         if( mult == 0 ) {
             mult = 1;
         }
         p->mod_moves( -to_moves<int>( 1_seconds ) * 0.5 * mult );
         if( it ) {
             // WET, active items have their timer decremented every turn
             it->set_flag( flag_WET );
             it->active = true;
         }
     }
     return it ? 1 : 0;
 }
References _, item::active, Character::add_msg_if_player(), item::convert(), debugmsg, effect_boomered, effect_glowing, effect_slimed, flag_FILTHY, flag_WET, trapfunc::glow(), Creature::has_atleast_one_wet_part(), Creature::has_effect(), item::has_flag(), item::is_filthy(), item::item_counter, itype_towel, itype_towel_wet, m_info, Creature::mod_moves(), MORALE_WET, om_direction::name(), Character::rem_morale(), Creature::remove_effect(), Creature::set_all_parts_wetness(), item::set_flag(), string_id< T >::str(), item::tname(), and item::typeId().
Referenced by towel().
unfold_generic()
std::optional< int > iuse::unfold_generic (Character * p, item * it, const tripoint &)
Definition at line 5021 of file iuse.cpp.
 {
     p->assign_activity( vehicle_unfolding_activity_actor( *it ) );
     p->i_rem( it );
     return 0;
 }
References Character::assign_activity(), and Character::i_rem().
Referenced by Item_factory::init().
unpack_item()
std::optional< int > iuse::unpack_item (Character * p, item * it, const tripoint &)
Definition at line 2352 of file iuse.cpp.
 {
     if( p->cant_do_underwater() ) {
         return std::nullopt;
     }
     std::string oname = it->typeId().str() + "_on";
     p->mod_moves( -to_moves<int>( 10_seconds ) );
     p->add_msg_if_player( _( "You unpack your %s for use." ), it->tname() );
     it->convert( itype_id( oname ), p ).active = false;
     // Check if unpacking led to invalid container state
     p->invalidate_inventory_validity_cache();
     return 0;
 }
References _, item::active, Character::add_msg_if_player(), Creature::cant_do_underwater(), item::convert(), Character::invalidate_inventory_validity_cache(), Creature::mod_moves(), string_id< T >::str(), item::tname(), and item::typeId().
Referenced by Item_factory::init().
vibe()
std::optional< int > iuse::vibe (Character * p, item * it, const tripoint &)
Definition at line 4249 of file iuse.cpp.
 {
     if( p->is_npc() ) {
         // Long action
         // Also, that would be creepy as fuck, seriously
         return std::nullopt;
     }
     if( p->is_mounted() ) {
         p->add_msg_if_player( m_info, _( "You can't do that while mounted." ) );
         return std::nullopt;
     }
     if( p->is_underwater() && ( !( p->has_trait( trait_GILLS ) ||
                                    p->is_wearing( itype_rebreather_on ) ||
                                    p->is_wearing( itype_rebreather_xl_on ) ||
                                    p->is_wearing( itype_mask_h20survivor_on ) ) ) ) {
         p->add_msg_if_player( m_info, _( "It might be waterproof, but your lungs aren't." ) );
         return std::nullopt;
     }
     if( !it->ammo_sufficient( p ) ) {
         p->add_msg_if_player( m_info, _( "The %s's batteries are dead." ), it->tname() );
         return std::nullopt;
     }
     if( p->get_sleepiness() >= sleepiness_levels::DEAD_TIRED ) {
         p->add_msg_if_player( m_info, _( "*Your* batteries are dead." ) );
         return std::nullopt;
     } else {
         int moves = to_moves<int>( 20_minutes );
         if( it->ammo_remaining() > 0 ) {
             p->add_msg_if_player( _( "You fire up your %s and start getting the tension out." ),
                                   it->tname() );
         } else {
             p->add_msg_if_player( _( "You whip out your %s and start getting the tension out." ),
                                   it->tname() );
         }
         p->assign_activity( ACT_VIBE, moves, -1, 0, "de-stressing" );
         p->activity.targets.emplace_back( *p, it );
     }
     return 1;
 }
References _, ACT_VIBE, Character::activity, Character::add_msg_if_player(), item::ammo_remaining(), item::ammo_sufficient(), Character::assign_activity(), DEAD_TIRED, Character::get_sleepiness(), Character::has_trait(), Character::is_mounted(), Character::is_npc(), Creature::is_underwater(), Character::is_wearing(), itype_mask_h20survivor_on, itype_rebreather_on, itype_rebreather_xl_on, m_info, player_activity::targets, item::tname(), and trait_GILLS.
Referenced by Item_factory::init().
voltmeter()
std::optional< int > iuse::voltmeter (Character * p, item * it, const tripoint &)
Definition at line 8879 of file iuse.cpp.
 {
     const std::optional<tripoint> pnt_ = choose_adjacent( _( "Check voltage where?" ) );
     if( !pnt_ ) {
         return std::nullopt;
     }
     const map &here = get_map();
     const optional_vpart_position vp = here.veh_at( *pnt_ );
     if( !vp ) {
         p->add_msg_if_player( _( "There's nothing to measure there." ) );
         return std::nullopt;
     }
     if( vp->vehicle().fuel_left( itype_battery ) ) {
         p->add_msg_if_player( _( "The %1$s has voltage." ), vp->vehicle().name );
     } else {
         p->add_msg_if_player( _( "The %1$s has no voltage." ), vp->vehicle().name );
     }
     return 1;
 }
References _, Character::add_msg_if_player(), choose_adjacent(), get_map(), itype_battery, and map::veh_at().
Referenced by Item_factory::init().
vortex()
std::optional< int > iuse::vortex (Character * p, item * it, const tripoint &)
Definition at line 4289 of file iuse.cpp.
 {
     std::vector<point> spawn;
     for( int i = -3; i <= 3; i++ ) {
         spawn.emplace_back( -3, i );
         spawn.emplace_back( +3, i );
         spawn.emplace_back( i, -3 );
         spawn.emplace_back( i, +3 );
     }
     while( !spawn.empty() ) {
         const tripoint offset( random_entry_removed( spawn ), 0 );
         monster *const mon = g->place_critter_at( mon_vortex, offset + p->pos() );
         if( !mon ) {
             continue;
         }
         p->add_msg_if_player( m_warning, _( "Air swirls all over" ) );
         p->mod_moves( -to_moves<int>( 1_seconds ) );
         it->convert( itype_spiral_stone, p );
         mon->friendly = -1;
         return 1;
     }
     // Only reachable when no monster has been spawned.
     p->add_msg_if_player( m_warning, _( "Air swirls around you for a moment." ) );
     return 0;
 }
References _, Character::add_msg_if_player(), item::convert(), monster::friendly, g, itype_spiral_stone, m_warning, Creature::mod_moves(), mon_vortex, Creature::pos(), and random_entry_removed().
Referenced by Item_factory::init().
wash_all_items()
std::optional< int > iuse::wash_all_items (Character * p, item * , const tripoint &)
Definition at line 8134 of file iuse.cpp.
 {
     if( p->fine_detail_vision_mod() > 4 ) {
         p->add_msg_if_player( _( "You can't see to do that!" ) );
         return std::nullopt;
     }
     // Check that player isn't over volume limit as this might cause it to break... this is a hack.
     // TODO: find a better solution.
     if( p->volume_capacity() < p->volume_carried() ) {
         p->add_msg_if_player( _( "You're carrying too much to clean anything." ) );
         return std::nullopt;
     }
     wash_items( p, true, true );
     return 0;
 }
References _, Character::add_msg_if_player(), Character::fine_detail_vision_mod(), Character::volume_capacity(), Character::volume_carried(), and wash_items().
Referenced by Item_factory::init().
wash_hard_items()
std::optional< int > iuse::wash_hard_items (Character * p, item * , const tripoint &)
Definition at line 8114 of file iuse.cpp.
 {
     if( p->fine_detail_vision_mod() > 4 ) {
         p->add_msg_if_player( _( "You can't see to do that!" ) );
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     // Check that player isn't over volume limit as this might cause it to break... this is a hack.
     // TODO: find a better solution.
     if( p->volume_capacity() < p->volume_carried() ) {
         p->add_msg_if_player( _( "You're carrying too much to clean anything." ) );
         return std::nullopt;
     }
     wash_items( p, false, true );
     return 0;
 }
References _, Character::add_msg_if_player(), Character::cant_do_mounted(), Character::fine_detail_vision_mod(), Character::volume_capacity(), Character::volume_carried(), and wash_items().
Referenced by Item_factory::init().
wash_items()
std::optional< int > iuse::wash_items (Character * p, bool soft_items, bool hard_items)
Definition at line 8152 of file iuse.cpp.
 {
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     p->inv->restack( *p );
     const inventory &crafting_inv = p->crafting_inventory();
     auto is_liquid = []( const item & it ) {
         return it.made_of( phase_id::LIQUID );
     };
     int available_water = std::max(
                               crafting_inv.charges_of( itype_water, INT_MAX, is_liquid ),
                               crafting_inv.charges_of( itype_water_clean, INT_MAX, is_liquid )
                           );
     int available_cleanser = std::max( crafting_inv.charges_of( itype_soap ),
                                        std::max( crafting_inv.charges_of( itype_detergent ),
                                                crafting_inv.charges_of( itype_liquid_soap, INT_MAX, is_liquid ) ) );
     const inventory_filter_preset preset( [soft_items, hard_items]( const item_location & location ) {
         return location->has_flag( flag_FILTHY ) && !location->has_flag( flag_NO_CLEAN ) &&
                ( ( soft_items && location->is_soft() ) || ( hard_items && !location->is_soft() ) );
     } );
     auto make_raw_stats = [available_water,
                            available_cleanser]( const std::vector<std::pair<item_location, int>> &locs
     ) {
         units::volume total_volume = 0_ml;
         for( const auto &pair : locs ) {
             total_volume += pair.first->volume( false, true, pair.second );
         }
         washing_requirements required = washing_requirements_for_volume( total_volume );
         const std::string time = colorize( to_string( time_duration::from_moves( required.time ), true ),
                                            c_light_gray );
         auto to_string = []( int val ) -> std::string {
             if( val == INT_MAX )
             {
                 return pgettext( "short for infinity", "inf" );
             }
             return string_format( "%3d", val );
         };
         const std::string water = string_join( display_stat( "", required.water, available_water,
                                                to_string ), "" );
         const std::string cleanser = string_join( display_stat( "", required.cleanser, available_cleanser,
                                      to_string ), "" );
         using stats = inventory_selector::stats;
         return stats{{
                 {{ _( "Water" ), water }},
                 {{ _( "Cleanser" ), cleanser }},
                 {{ _( "Estimated time" ), time }}
             }};
     };
     inventory_multiselector inv_s( *p, preset, _( "ITEMS TO CLEAN" ),
                                    make_raw_stats, /*allow_select_contained=*/true );
     inv_s.add_character_items( *p );
     inv_s.add_nearby_items( PICKUP_RANGE );
     inv_s.set_title( _( "Multiclean" ) );
     inv_s.set_hint( _( "To clean x items, type a number before selecting." ) );
     if( inv_s.empty() ) {
         popup( std::string( _( "You have nothing to clean." ) ), PF_GET_KEY );
         return std::nullopt;
     }
     const drop_locations to_clean = inv_s.execute();
     if( to_clean.empty() ) {
         return std::nullopt;
     }
     // Determine if we have enough water and cleanser for all the items.
     units::volume total_volume = 0_ml;
     for( drop_location pair : to_clean ) {
         if( !pair.first ) {
             p->add_msg_if_player( m_info, _( "Never mind." ) );
             return std::nullopt;
         }
         total_volume += pair.first->volume( false, true, pair.second );
     }
     washing_requirements required = washing_requirements_for_volume( total_volume );
     if( !crafting_inv.has_charges( itype_water, required.water, is_liquid ) &&
         !crafting_inv.has_charges( itype_water_clean, required.water, is_liquid ) ) {
         p->add_msg_if_player( _( "You need %1$i charges of water or clean water to wash these items." ),
                               required.water );
         return std::nullopt;
     } else if( !crafting_inv.has_charges( itype_soap, required.cleanser ) &&
                !crafting_inv.has_charges( itype_detergent, required.cleanser ) &&
                !crafting_inv.has_charges( itype_liquid_soap, required.cleanser, is_liquid ) ) {
         p->add_msg_if_player( _( "You need %1$i charges of cleansing agent to wash these items." ),
                               required.cleanser );
         return std::nullopt;
     }
     const std::vector<Character *> helpers = p->get_crafting_helpers();
     const std::size_t helpersize = p->get_num_crafting_helpers( 3 );
     required.time *= ( 1.0f - ( helpersize / 10.0f ) );
     for( std::size_t i = 0; i < helpersize; i++ ) {
         add_msg( m_info, _( "%s helps with this task" ), helpers[i]->get_name() );
     }
     // Assign the activity values.
     p->assign_activity( wash_activity_actor( to_clean, required ) );
     return 0;
 }
References _, inventory_selector::add_character_items(), add_msg(), Character::add_msg_if_player(), inventory_selector::add_nearby_items(), Character::assign_activity(), c_light_gray, Character::cant_do_mounted(), inventory::charges_of(), washing_requirements::cleanser, colorize(), Character::crafting_inventory(), display_stat(), inventory_selector::empty(), inventory_multiselector::execute(), flag_FILTHY, flag_NO_CLEAN, time_duration::from_moves(), Character::get_crafting_helpers(), Character::get_num_crafting_helpers(), read_only_visitable::has_charges(), Character::inv, itype_detergent, itype_liquid_soap, itype_soap, itype_water, itype_water_clean, LIQUID, location, m_info, max(), PF_GET_KEY, pgettext, PICKUP_RANGE, popup(), inventory_selector::set_hint(), inventory_selector::set_title(), string_format(), string_join(), washing_requirements::time, to_string(), washing_requirements_for_volume(), washing_requirements::water, and water.
Referenced by wash_all_items(), wash_hard_items(), and wash_soft_items().
wash_soft_items()
std::optional< int > iuse::wash_soft_items (Character * p, item * , const tripoint &)
Definition at line 8094 of file iuse.cpp.
 {
     if( p->fine_detail_vision_mod() > 4 ) {
         p->add_msg_if_player( _( "You can't see to do that!" ) );
         return std::nullopt;
     }
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     // Check that player isn't over volume limit as this might cause it to break... this is a hack.
     // TODO: find a better solution.
     if( p->volume_capacity() < p->volume_carried() ) {
         p->add_msg_if_player( _( "You're carrying too much to clean anything." ) );
         return std::nullopt;
     }
     wash_items( p, true, false );
     return 0;
 }
References _, Character::add_msg_if_player(), Character::cant_do_mounted(), Character::fine_detail_vision_mod(), Character::volume_capacity(), Character::volume_carried(), and wash_items().
Referenced by Item_factory::init().
water_purifier()
std::optional< int > iuse::water_purifier (Character * p, item * it, const tripoint &)
Definition at line 2426 of file iuse.cpp.
 {
     if( p->cant_do_mounted() ) {
         return std::nullopt;
     }
     item_location obj = g->inv_map_splice( []( const item & e ) {
         return !e.empty() && e.has_item_with( []( const item & it ) {
             return it.typeId() == itype_water;
         } );
     }, _( "Purify what?" ), 1, _( "You don't have water to purify." ) );
     if( !obj ) {
         p->add_msg_if_player( m_info, _( "You don't have that item!" ) );
         return std::nullopt;
     }
     const std::vector<item *> liquids = obj->items_with( []( const item & it ) {
         return it.typeId() == itype_water;
     } );
     int charges_of_water = 0;
     for( const item *water : liquids ) {
         charges_of_water += water->charges;
     }
     if( !it->ammo_sufficient( p, charges_of_water ) ) {
         p->add_msg_if_player( m_info, _( "That volume of water is too large to purify." ) );
         return std::nullopt;
     }
     p->mod_moves( -to_moves<int>( 2_seconds ) );
     for( item *water : liquids ) {
         water->convert( itype_water_clean, p ).poison = 0;
     }
     return charges_of_water;
 }
References _, Character::add_msg_if_player(), item::ammo_sufficient(), Character::cant_do_mounted(), item::empty(), g, visitable::has_item_with(), itype_water, itype_water_clean, m_info, Creature::mod_moves(), int_id< T >::obj(), item::typeId(), and water.
Referenced by Item_factory::init().
weak_antibiotic()
std::optional< int > iuse::weak_antibiotic (Character * p, item * it, const tripoint &)
Definition at line 8288 of file iuse.cpp.
 {
     p->add_msg_if_player( _( "You take some %s." ), it->tname() );
     if( p->has_effect( effect_infected ) && !p->has_effect( effect_weak_antibiotic ) ) {
         p->add_msg_if_player( m_good, _( "The throbbing of the infection diminishes.  Slightly." ) );
     }
     p->add_effect( effect_weak_antibiotic, 12_hours );
     p->add_effect( effect_weak_antibiotic_visible, rng( 9_hours, 15_hours ) );
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), effect_infected, effect_weak_antibiotic, effect_weak_antibiotic_visible, Creature::has_effect(), m_good, rng(), and item::tname().
Referenced by Item_factory::init().
weather_tool()
std::optional< int > iuse::weather_tool (Character * p, item * it, const tripoint &)
Definition at line 7781 of file iuse.cpp.
 {
     weather_manager &weather = get_weather();
     const w_point weatherPoint = *weather.weather_precise;
     /* Possibly used twice. Worth spending the time to precalculate. */
     const units::temperature player_local_temp = weather.get_temperature( p->pos() );
     if( it->typeId() == itype_weather_reader ) {
         p->add_msg_if_player( m_neutral, _( "The %s's monitor slowly outputs the data" ),
                               it->tname() );
     }
     if( it->has_flag( flag_THERMOMETER ) ) {
         std::string temperature_str;
         if( get_map().has_flag_ter( ter_furn_flag::TFLAG_DEEP_WATER, p->pos() ) ||
             get_map().has_flag_ter( ter_furn_flag::TFLAG_SHALLOW_WATER, p->pos() ) ) {
             temperature_str = print_temperature( get_weather().get_cur_weather_gen().get_water_temperature() );
         } else {
             temperature_str = print_temperature( player_local_temp );
         }
         p->add_msg_if_player( m_neutral, _( "The %1$s reads %2$s." ), it->tname(),
                               temperature_str );
     }
     if( it->has_flag( flag_HYGROMETER ) ) {
         if( it->typeId() == itype_hygrometer ) {
             p->add_msg_if_player(
                 m_neutral, _( "The %1$s reads %2$s." ), it->tname(),
                 print_humidity( get_local_humidity( weatherPoint.humidity, get_weather().weather_id,
                                                     g->is_sheltered( p->pos() ) ) ) );
         } else {
             p->add_msg_if_player(
                 m_neutral, _( "Relative Humidity: %s." ),
                 print_humidity( get_local_humidity( weatherPoint.humidity, get_weather().weather_id,
                                                     g->is_sheltered( p->pos() ) ) ) );
         }
     }
     if( it->has_flag( flag_BAROMETER ) ) {
         if( it->typeId() == itype_barometer ) {
             p->add_msg_if_player(
                 m_neutral, _( "The %1$s reads %2$s." ), it->tname(),
                 print_pressure( static_cast<int>( weatherPoint.pressure ) ) );
         } else {
             p->add_msg_if_player( m_neutral, _( "Pressure: %s." ),
                                   print_pressure( static_cast<int>( weatherPoint.pressure ) ) );
         }
     }
     if( it->typeId() == itype_weather_reader ) {
         int vehwindspeed = 0;
         if( optional_vpart_position vp = get_map().veh_at( p->pos() ) ) {
             vehwindspeed = std::abs( vp->vehicle().velocity / 100 ); // For mph
         }
         const oter_id &cur_om_ter = overmap_buffer.ter( p->global_omt_location() );
         const int windpower = get_local_windpower( weather.windspeed + vehwindspeed, cur_om_ter,
                               p->get_location(), weather.winddirection, g->is_sheltered( p->pos() ) );
         p->add_msg_if_player( m_neutral, _( "Wind Speed: %.1f %s." ),
                               convert_velocity( windpower * 100, VU_WIND ),
                               velocity_units( VU_WIND ) );
         p->add_msg_if_player(
             m_neutral, _( "Feels Like: %s." ),
             print_temperature( player_local_temp + get_local_windchill( weatherPoint.temperature,
                                weatherPoint.humidity, windpower ) ) );
         std::string dirstring = get_dirstring( weather.winddirection );
         p->add_msg_if_player( m_neutral, _( "Wind Direction: From the %s." ), dirstring );
     }
     return 1; //TODO check
 }
References _, abs(), Character::add_msg_if_player(), convert_velocity(), flag_BAROMETER, flag_HYGROMETER, flag_THERMOMETER, g, get_dirstring(), get_local_humidity(), get_local_windchill(), get_local_windpower(), Creature::get_location(), get_map(), get_weather(), Creature::global_omt_location(), item::has_flag(), w_point::humidity, itype_barometer, itype_hygrometer, itype_weather_reader, m_neutral, overmap_buffer, Creature::pos(), w_point::pressure, print_humidity(), print_pressure(), print_temperature(), w_point::temperature, overmapbuffer::ter(), TFLAG_DEEP_WATER, TFLAG_SHALLOW_WATER, item::tname(), item::typeId(), velocity_units(), and VU_WIND.
Referenced by Item_factory::init().
weed_cake()
std::optional< int > iuse::weed_cake (Character * p, item * , const tripoint &)
Definition at line 810 of file iuse.cpp.
 {
     p->add_msg_if_player(
         _( "You start scarfing down the delicious cake.  It tastes a little funny, though" ) );
     time_duration duration = 12_minutes;
     if( p->has_trait( trait_TOLERANCE ) ) {
         duration = 9_minutes;
     }
     if( p->has_trait( trait_LIGHTWEIGHT ) ) {
         duration = 15_minutes;
     }
     p->mod_hunger( 2 );
     p->mod_thirst( 6 );
     if( p->get_painkiller() < 5 ) {
         p->set_painkiller( ( p->get_painkiller() + 3 ) * 2 );
     }
     p->add_effect( effect_weed_high, duration );
     p->mod_moves( -to_moves<int>( 1_seconds ) );
     if( one_in( 5 ) ) {
         weed_msg( *p );
     }
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), effect_weed_high, Character::get_painkiller(), Character::has_trait(), Character::mod_hunger(), Creature::mod_moves(), Character::mod_thirst(), one_in(), Character::set_painkiller(), trait_LIGHTWEIGHT, trait_TOLERANCE, and weed_msg().
Referenced by Item_factory::init().
xanax()
std::optional< int > iuse::xanax (Character * p, item * it, const tripoint &)
Definition at line 484 of file iuse.cpp.
 {
     p->add_msg_if_player( _( "You take some %s." ), it->tname() );
     p->add_effect( effect_took_xanax, 90_minutes );
     p->add_effect( effect_took_xanax_visible, rng( 70_minutes, 110_minutes ) );
     return 1;
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), effect_took_xanax, effect_took_xanax_visible, rng(), and item::tname().
Referenced by Item_factory::init().