Cataclysm DDA: tname Namespace Reference
tname Namespace Reference
Typedefs
using segment_bitset = enum_bitset< tname::segments >
Enumerations
enum class segments : std::size_t {
FAULTS = 0 , DIRT , OVERHEAT , FAVORITE_PRE ,
DURABILITY , WHEEL_DIAMETER , BURN , WEAPON_MODS ,
CUSTOM_ITEM_PREFIX , TYPE , CATEGORY , CUSTOM_ITEM_SUFFIX ,
MODS , CRAFT , WHITEBLACKLIST , CHARGES ,
FOOD_TRAITS , FOOD_STATUS , FOOD_IRRADIATED , TEMPERATURE ,
LOCATION_HINT , CLOTHING_SIZE , ETHEREAL , FILTHY ,
BROKEN , CBM_STATUS , UPS , TAGS ,
VARS , WETNESS , ACTIVE , SEALED ,
FAVORITE_POST , RELIC , LINK , TECHNIQUES ,
CONTENTS , last_segment , VARIANT , COMPONENTS ,
CORPSE , CONTENTS_FULL , CONTENTS_ABREV , CONTENTS_COUNT ,
FOOD_PERISHABLE , last
}
Functions
std::string print_segment (tname::segments segment, item const &it, unsigned int quantity, segment_bitset const &segments)
constexpr segment_bitset default_tname (default_tname_bits)
constexpr segment_bitset unprefixed_tname (default_tname_bits &~tname_prefix_bits)
constexpr segment_bitset tname_sort_key (default_tname_bits &~tname_unsortable_bits)
constexpr segment_bitset tname_contents (tname_contents_bits)
constexpr segment_bitset tname_conditional (tname_conditional_bits)
constexpr segment_bitset item_name (item_name_bits)
Variables
constexpr uint64_t default_tname_bits
constexpr uint64_t tname_prefix_bits
constexpr uint64_t tname_unsortable_bits
constexpr uint64_t tname_contents_bits
constexpr uint64_t tname_conditional_bits
constexpr uint64_t item_name_bits
Typedef Documentation
segment_bitset
using tname::segment_bitset = typedef enum_bitset<tname::segments>
Definition at line 75 of file item_tname.h.
Enumeration Type Documentation
segments
enum tname::segments : std::size_t strong
Enumerator
FAULTS
DIRT
OVERHEAT
FAVORITE_PRE
DURABILITY
WHEEL_DIAMETER
BURN
WEAPON_MODS
CUSTOM_ITEM_PREFIX
TYPE
CATEGORY
CUSTOM_ITEM_SUFFIX
MODS
CRAFT
WHITEBLACKLIST
CHARGES
FOOD_TRAITS
FOOD_STATUS
FOOD_IRRADIATED
TEMPERATURE
LOCATION_HINT
CLOTHING_SIZE
ETHEREAL
FILTHY
BROKEN
CBM_STATUS
UPS
TAGS
VARS
WETNESS
ACTIVE
SEALED
FAVORITE_POST
RELIC
LINK
TECHNIQUES
CONTENTS
last_segment
VARIANT
COMPONENTS
CORPSE
CONTENTS_FULL
CONTENTS_ABREV
CONTENTS_COUNT
FOOD_PERISHABLE
last
Definition at line 18 of file item_tname.h.
                     : std::size_t {
     FAULTS = 0,
     DIRT,
     OVERHEAT,
     FAVORITE_PRE,
     DURABILITY,
     WHEEL_DIAMETER,
     BURN,
     WEAPON_MODS,
     CUSTOM_ITEM_PREFIX,
     TYPE,
     CATEGORY,
     CUSTOM_ITEM_SUFFIX,
     MODS,
     CRAFT,
     WHITEBLACKLIST,
     CHARGES,
     FOOD_TRAITS,
     FOOD_STATUS,
     FOOD_IRRADIATED,
     TEMPERATURE,
     LOCATION_HINT,
     CLOTHING_SIZE,
     ETHEREAL,
     FILTHY,
     BROKEN,
     CBM_STATUS,
     UPS,
     TAGS,
     VARS,
     WETNESS,
     ACTIVE,
     SEALED,
     FAVORITE_POST,
     RELIC,
     LINK,
     TECHNIQUES,
     CONTENTS,
     last_segment,
     // separate flags for TYPE
     VARIANT,
     COMPONENTS,
     CORPSE,
     // separate flags for CONTENTS
     CONTENTS_FULL,
     CONTENTS_ABREV,
     CONTENTS_COUNT,
     // separate flags for CATEGORY
     FOOD_PERISHABLE,
     last,
 };
Function Documentation
default_tname()
constexpr segment_bitset tname::default_tname (default_tname_bits) constexpr
Referenced by item::tname(), and Character::weapname_simple().
item_name()
constexpr segment_bitset tname::item_name (item_name_bits) constexpr
Referenced by enumerate_objects_around_point(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_consume_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_item_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item(), Character::fall_asleep(), fetch_activity(), get_autopickup_rule(), memorial_logger::notify(), photo_def_for_camera_point(), advanced_inventory::print_items(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::receive_item(), recipe::result_name(), outfit::sort_armor(), tool_comp::to_string(), item_comp::to_string(), talker_character::use_amount(), and talker_character::use_charges().
print_segment()
std::string tname::print_segment (tname::segments segment, item const & it, unsigned int quantity, segment_bitset const & segments)
Definition at line 614 of file item_tname.cpp.
 {
     static std::array<decl_f_print_segment *, num_segments> const arr = get_segs_array();
     size_t const idx = static_cast<size_t>( segment );
     return ( *arr.at( idx ) )( it, quantity, segments );
 }
References anonymous_namespace{item_tname.cpp}::get_segs_array().
Referenced by item::tname().
tname_conditional()
constexpr segment_bitset tname::tname_conditional (tname_conditional_bits) constexpr
Referenced by anonymous_namespace{item_tname.cpp}::label().
tname_contents()
constexpr segment_bitset tname::tname_contents (tname_contents_bits) constexpr
Referenced by item::stacks_with().
tname_sort_key()
constexpr segment_bitset tname::tname_sort_key (default_tname_bits &~ tname_unsortable_bits) constexpr
Referenced by anonymous_namespace{inventory_ui.cpp}::get_cached_name().
unprefixed_tname()
constexpr segment_bitset tname::unprefixed_tname (default_tname_bits &~ tname_prefix_bits) constexpr
Referenced by inventory_selector::drag_drop_item(), make_gun_sound_effect(), and item::tname().
Variable Documentation
default_tname_bits
constexpr uint64_t tname::default_tname_bits constexpr
Initial value:
=
    std::numeric_limits<uint64_t>::max() &
    ~( 1ULL << static_cast<size_t>( tname::segments::CATEGORY ) )
Definition at line 92 of file item_tname.h.
item_name_bits
constexpr uint64_t tname::item_name_bits constexpr
Initial value:
=
    1ULL << static_cast<size_t>( tname::segments::CUSTOM_ITEM_PREFIX ) |
    1ULL << static_cast<size_t>( tname::segments::TYPE ) |
    1ULL << static_cast<size_t>( tname::segments::CUSTOM_ITEM_SUFFIX )
Definition at line 111 of file item_tname.h.
tname_conditional_bits
constexpr uint64_t tname::tname_conditional_bits constexpr
Initial value:
=
    1ULL << static_cast<size_t>( tname::segments::COMPONENTS ) |
    1ULL << static_cast<size_t>( tname::segments::TAGS ) |
    1ULL << static_cast<size_t>( tname::segments::VARS )
Definition at line 107 of file item_tname.h.
tname_contents_bits
constexpr uint64_t tname::tname_contents_bits constexpr
Initial value:
=
    1ULL << static_cast<size_t>( tname::segments::CONTENTS ) |
    1ULL << static_cast<size_t>( tname::segments::CONTENTS_FULL ) |
    1ULL << static_cast<size_t>( tname::segments::CONTENTS_ABREV ) |
    1ULL << static_cast<size_t>( tname::segments::CONTENTS_COUNT )
Definition at line 102 of file item_tname.h.
tname_prefix_bits
constexpr uint64_t tname::tname_prefix_bits constexpr
Initial value:
=
    1ULL << static_cast<size_t>( tname::segments::FAVORITE_PRE ) |
    1ULL << static_cast<size_t>( tname::segments::DURABILITY ) |
    1ULL << static_cast<size_t>( tname::segments::BURN )
Definition at line 95 of file item_tname.h.
tname_unsortable_bits
constexpr uint64_t tname::tname_unsortable_bits constexpr
Initial value:
=
    tname_prefix_bits |
    ( 1ULL << static_cast<size_t>( tname::segments::CONTENTS_COUNT ) )
Definition at line 99 of file item_tname.h.