Cataclysm DDA: anonymous_namespace{mapdata.cpp} Namespace Reference
anonymous_namespace{mapdata.cpp} Namespace Reference
Variables
generic_factory< ter_t > terrain_data ("terrain")
generic_factory< furn_t > furniture_data ("furniture")
Variable Documentation
furniture_data
generic_factory<furn_t> anonymous_namespace{mapdata.cpp}::furniture_data("furniture") ("furniture")
Referenced by check_furniture_and_terrain(), furn_t::count(), string_id< T >::id(), int_id< T >::is_valid(), string_id< T >::is_valid(), load_furniture(), int_id< T >::obj(), string_id< T >::obj(), and reset_furn_ter().
terrain_data
generic_factory<ter_t> anonymous_namespace{mapdata.cpp}::terrain_data("terrain") ("terrain")
Referenced by check_furniture_and_terrain(), ter_t::count(), int_id< T >::id(), int_id< T >::is_valid(), string_id< T >::is_valid(), load_terrain(), int_id< T >::obj(), string_id< T >::obj(), reset_furn_ter(), and set_ter_ids().