Cataclysm DDA: game_menus::inv Namespace Reference
game_menus::inv Namespace Reference
Functions
item_location titled_menu (Character &you, const std::string &title, const std::string &none_message="")
item_location titled_filter_menu (const item_filter &filter, Character &you, const std::string &title, int radius=-1, const std::string &none_message="")
item_location titled_filter_menu (const item_location_filter &filter, Character &you, const std::string &title, int radius=-1, const std::string &none_message="")
drop_locations titled_multi_filter_menu (const item_location_filter &filter, Character &you, const std::string &title, int radius=-1, const std::string &none_message="")
Customized inventory menus
The functions here execute customized inventory menus for specific game situations.
Each menu displays only related inventory (or nearby) items along with context dependent information. More functions will follow. TODO: update all 'inv_for...()' functions to return item_location instead of plain int and move them here.
Returns
Either location of the selected item or null location if none was selected.
void common (avatar &you)
void common (item_location &loc, avatar &you)
void compare (avatar &you, const std::optional< tripoint > &offset)
void reassign_letter (avatar &you, item &it)
void swap_letters (avatar &you)
bool compare_items (const item &first, const item &second, const std::string &confirm_message="")
Compares two items, if confirm_message isn't empty then it will be printed to the screen and function return value will be true if confirm button was pressed, false for "quit" input.
drop_locations multidrop (Character &you)
Select items to drop.
drop_locations pickup (avatar &you, const std::optional< tripoint > &target=std::nullopt, const std::vector< drop_location > &selection={})
Select items to pick up.
drop_locations smoke_food (Character &you, units::volume total_capacity, units::volume used_capacity)
item_location consume (avatar &you, const item_location &loc=item_location())
Consume an item via a custom menu.
item_location consume_food (avatar &you)
Consuming a food item via a custom menu.
item_location consume_drink (avatar &you)
Consuming a drink item via a custom menu.
item_location consume_meds (avatar &you)
Consuming a medication item via a custom menu.
item_location container_for (Character &you, const item &liquid, int radius=0, const item *avoid=nullptr)
Choosing a container for liquid.
item_location disassemble (Character &you)
Item disassembling menu.
item_location gun_to_modify (Character &you, const item &gunmod)
Gunmod installation menu.
item_location gunmod_to_remove (Character &you, item &gun)
Gunmod removal menu.
item_location read (Character &you)
Book reading menu.
item_location ereader_to_use (Character &you)
E-Book reading menu.
item_location ebookread (Character &you, item_location &ereader)
eBook reading menu.
drop_locations ebooksave (Character &who, item_location &ereader)
Select books to save to E-Book reader menu.
item_location steal (avatar &you, Character &victim)
Menu for stealing stuff.
item_location use (avatar &you)
Item activation menu.
item_location wield (avatar &you)
Item wielding/unwielding menu.
drop_locations holster (avatar &you, const item_location &holster)
Item wielding/unwielding menu.
void insert_items (avatar &you, item_location &holster)
drop_locations unload_container (avatar &you)
item_location saw_barrel (Character &you, item &tool)
Choosing a gun to saw down it's barrel.
item_location saw_stock (Character &you, item &tool)
Choosing a gun to saw down its barrel.
item_location molle_attach (Character &you, item &tool)
Choosing an item to attach to a load bearing vest.
item_location veh_tool_attach (Character &you, const std::string &vp_name, const std::set< itype_id > &allowed_types)
Choosing an item to attach to a vehicle tool station.
item_location wear (Character &you, const bodypart_id &bp=bodypart_id("bp_null"))
Choose item to wear.
item_location take_off (avatar &you)
Choose item to take off.
item_location salvage (Character &you, const salvage_actor *actor)
Item cut up menu.
item_location repair (Character &you, const repair_item_actor *actor, const item *main_tool)
Repair menu.
item_location install_bionic (Character &installer, Character &patron, Character &patient, bool surgeon=false)
Bionic install menu.
item_location sterilize_cbm (Character &you)
Autoclave sterilize menu.
item_location change_sprite (Character &you)
Change sprite menu.
std::pair< item_location, bool > unload (Character &you)
Unload item menu.
item::reload_option select_ammo (Character &you, const item_location &loc, bool prompt=false, bool empty=true)
Function Documentation
change_sprite()
item_location game_menus::inv::change_sprite (Character & you)
Change sprite menu.
Definition at line 2750 of file game_inventory.cpp.
 {
     return inv_internal( you, change_sprite_inventory_preset( you ),
                          _( "Change appearance of your armor:" ), -1,
                          _( "You have nothing to wear." ) );
 }
References _, and inv_internal().
Referenced by change_armor_sprite().
common() [1/2]
void game_menus::inv::common (avatar & you)
Definition at line 241 of file game_inventory.cpp.
 {
     // Return to inventory menu on those inputs
     static const std::set<int> loop_options = { { '\0', '=', 'f', '<', '>'}};
     inventory_selector_preset inv_s_p = default_preset;
     inv_s_p.save_state = &inventory_ui_default_state;
     inventory_pick_selector inv_s( you, inv_s_p );
     inv_s.set_title( _( "Inventory" ) );
     inv_s.set_hint( string_format(
                         _( "Item hotkeys assigned: <color_light_gray>%d</color>/<color_light_gray>%d</color>" ),
                         you.allocated_invlets().count(), inv_chars.size() ) );
     int res = 0;
     item_location location;
     std::string filter;
     do {
         you.inv->restack( you );
         inv_s.drag_enabled = true;
         inv_s.clear_items();
         inv_s.add_character_items( you );
         inv_s.set_filter( filter );
         if( location != item_location::nowhere ) {
             inv_s.highlight_one_of( { location } );
         }
         location = inv_s.execute();
         filter = inv_s.get_filter();
         if( location == item_location::nowhere ) {
             break;
         }
         res = g->inventory_item_menu( location );
     } while( loop_options.count( res ) != 0 );
 }
References _, inventory_selector::add_character_items(), Character::allocated_invlets(), inventory_selector::clear_items(), default_preset, inventory_pick_selector::drag_enabled, inventory_pick_selector::execute(), filter, g, inventory_selector::get_filter(), inventory_selector::highlight_one_of(), Character::inv, inv_chars, inventory_ui_default_state, location, item_location::nowhere, inventory_selector_preset::save_state, inventory_selector::set_filter(), inventory_selector::set_hint(), inventory_selector::set_title(), and string_format().
Referenced by game::do_regular_action(), weather_generator::get_weather(), game::inventory_item_menu(), and weather_temperature_from_common_data().
common() [2/2]
void game_menus::inv::common (item_location & loc, avatar & you)
Definition at line 280 of file game_inventory.cpp.
 {
     // Return to inventory menu on those inputs
     static const std::set<int> loop_options = { { '\0', '=', 'f' } };
     container_inventory_selector inv_s( you, loc );
     inv_s.set_title( string_format( _( "Inventory of %s" ), loc->tname() ) );
     inv_s.set_hint( string_format(
                         _( "Item hotkeys assigned: <color_light_gray>%d</color>/<color_light_gray>%d</color>" ),
                         you.allocated_invlets().count(), inv_chars.size() ) );
     int res = 0;
     item_location location;
     std::string filter;
     do {
         inv_s.clear_items();
         inv_s.add_contained_items( loc );
         inv_s.set_filter( filter );
         if( location != item_location::nowhere ) {
             inv_s.highlight_one_of( { location } );
         }
         location = inv_s.execute();
         filter = inv_s.get_filter();
         if( location == item_location::nowhere ) {
             break;
         }
         res = g->inventory_item_menu( location );
     } while( loop_options.count( res ) != 0 );
 }
References _, inventory_selector::add_contained_items(), Character::allocated_invlets(), inventory_selector::clear_items(), inventory_pick_selector::execute(), filter, g, inventory_selector::get_filter(), inventory_selector::highlight_one_of(), inv_chars, location, item_location::nowhere, inventory_selector::set_filter(), inventory_selector::set_hint(), inventory_selector::set_title(), string_format(), and item::tname().
compare()
void game_menus::inv::compare (avatar & you, const std::optional< tripoint > & offset)
Definition at line 2394 of file game_inventory.cpp.
 {
     you.inv->restack( you );
     inventory_compare_selector inv_s( you );
     inv_s.add_character_items( you );
     inv_s.set_title( _( "Compare" ) );
     inv_s.set_hint( _( "Select two items to compare them." ) );
     if( offset ) {
         inv_s.add_map_items( you.pos() + *offset );
         inv_s.add_vehicle_items( you.pos() + *offset );
     } else {
         inv_s.add_nearby_items();
     }
     if( inv_s.empty() ) {
         popup( std::string( _( "There are no items to compare." ) ), PF_GET_KEY );
         return;
     }
     do {
         const auto to_compare = inv_s.execute();
         if( to_compare.first == nullptr || to_compare.second == nullptr ) {
             break;
         }
         compare_items( *to_compare.first, *to_compare.second );
     } while( true );
 }
References _, inventory_selector::add_character_items(), inventory_selector::add_map_items(), inventory_selector::add_nearby_items(), inventory_selector::add_vehicle_items(), compare_items(), inventory_selector::empty(), inventory_compare_selector::execute(), Character::inv, PF_GET_KEY, popup(), Creature::pos(), inventory_selector::set_hint(), and inventory_selector::set_title().
Referenced by veh_interact::calc_overview(), player_difficulty::calc_social_value(), cardreader_examine_actor::consume_card(), game::do_regular_action(), npc::evaluate_best_attack(), ma_buff::from_effect(), game::list_items(), item::magazine_info(), cata::list< element_type, element_allocator_type >::merge(), cata::colony< element_type, element_allocator_type, element_skipfield_type >::sort(), cata::list< element_type, element_allocator_type >::sort(), and cata::list< element_type, element_allocator_type >::unique().
compare_items()
bool game_menus::inv::compare_items (const item & first, const item & second, const std::string & confirm_message = "")
Compares two items, if confirm_message isn't empty then it will be printed to the screen and function return value will be true if confirm button was pressed, false for "quit" input.
Returns
False if confirm_message is empty or QUIT input was pressed.
Definition at line 2292 of file game_inventory.cpp.
 {
     std::string action;
     input_context ctxt;
     ui_adaptor ui;
     item_info_data item_info_first;
     item_info_data item_info_second;
     int page_size = 0;
     int scroll_pos_first = 0;
     int scroll_pos_second = 0;
     bool first_execution = true;
     static int lang_version = detail::get_current_language_version();
     do {
         //lang check here is needed to redraw the menu when using "Toggle language to English" option
         if( first_execution || lang_version != detail::get_current_language_version() ) {
             std::vector<iteminfo> v_item_first;
             std::vector<iteminfo> v_item_second;
             first.info( true, v_item_first );
             second.info( true, v_item_second );
             item_info_first = item_info_data( first.tname(), first.type_name(),
                                               v_item_first, v_item_second, scroll_pos_first );
             item_info_second = item_info_data( second.tname(), second.type_name(),
                                                v_item_second, v_item_first, scroll_pos_second );
             item_info_first.without_getch = true;
             item_info_second.without_getch = true;
             ctxt.register_action( "HELP_KEYBINDINGS" );
             if( !confirm_message.empty() ) {
                 ctxt.register_action( "CONFIRM" );
             }
             ctxt.register_action( "QUIT" );
             ctxt.register_action( "UP" );
             ctxt.register_action( "DOWN" );
             ctxt.register_action( "PAGE_UP" );
             ctxt.register_action( "PAGE_DOWN" );
             catacurses::window wnd_first;
             catacurses::window wnd_second;
             catacurses::window wnd_message;
             ui.reset();
             ui.on_screen_resize( [&]( ui_adaptor & ui ) {
                 const int half_width = TERMX / 2;
                 const int height = TERMY;
                 const int offset_y = confirm_message.empty() ? 0 : 3;
                 page_size = TERMY - offset_y - 2;
                 wnd_first = catacurses::newwin( height - offset_y, half_width, point_zero );
                 wnd_second = catacurses::newwin( height - offset_y, half_width, point( half_width, 0 ) );
                 if( !confirm_message.empty() ) {
                     wnd_message = catacurses::newwin( offset_y, TERMX, point( 0, height - offset_y ) );
                 }
                 ui.position( point_zero, point( half_width * 2, height ) );
             } );
             ui.mark_resize();
             ui.on_redraw( [&]( const ui_adaptor & ) {
                 if( !confirm_message.empty() ) {
                     draw_border( wnd_message );
                     nc_color col = c_white;
                     print_colored_text(
                         wnd_message, point( 3, 1 ), col, col,
                         confirm_message + " " +
                         ctxt.describe_key_and_name( "CONFIRM" ) + " " +
                         ctxt.describe_key_and_name( "QUIT" ) );
                     wnoutrefresh( wnd_message );
                 }
                 draw_item_info( wnd_first, item_info_first );
                 draw_item_info( wnd_second, item_info_second );
             } );
             lang_version = detail::get_current_language_version();
             first_execution = false;
         }
         ui_manager::redraw();
         action = ctxt.handle_input();
         if( action == "UP" ) {
             scroll_pos_first--;
             scroll_pos_second--;
         } else if( action == "DOWN" ) {
             scroll_pos_first++;
             scroll_pos_second++;
         } else if( action == "PAGE_UP" ) {
             scroll_pos_first  -= page_size;
             scroll_pos_second -= page_size;
         } else if( action == "PAGE_DOWN" ) {
             scroll_pos_first += page_size;
             scroll_pos_second += page_size;
         }
     } while( action != "QUIT" && action != "CONFIRM" );
     return action == "CONFIRM";
 }
References action, c_white, input_context::describe_key_and_name(), draw_border(), draw_item_info(), detail::get_current_language_version(), input_context::handle_input(), item::info(), catacurses::newwin(), point_zero, print_colored_text(), ui_manager::redraw(), input_context::register_action(), second, TERMX, TERMY, item::tname(), item::type_name(), item_info_data::without_getch, and catacurses::wnoutrefresh().
Referenced by compare(), compare_recipe_with_item(), iuse::gunmod_attach(), and detach_gunmods_actor::use().
consume()
item_location game_menus::inv::consume (avatar & you, const item_location & loc = item_location())
Consume an item via a custom menu.
If item_location is provided then consume only from the contents of that container.
Definition at line 996 of file game_inventory.cpp.
 {
     static item_location container_location;
     if( !you.has_activity( ACT_EAT_MENU ) ) {
         you.assign_activity( ACT_EAT_MENU );
         container_location = loc;
     }
     std::string none_message = you.activity.str_values.size() == 2 ?
                                _( "You have nothing else to consume." ) : _( "You have nothing to consume." );
     return inv_internal( you, comestible_inventory_preset( you ),
                          _( "Consume item" ), 1,
                          none_message,
                          get_consume_needs_hint( you ),
                          container_location );
 }
References _, ACT_EAT_MENU, Character::activity, Character::assign_activity(), get_consume_needs_hint(), Character::has_activity(), inv_internal(), and player_activity::str_values.
Referenced by basecamp::distribute_food(), game::do_regular_action(), activity_handlers::eat_menu_do_turn(), and game::inventory_item_menu().
consume_drink()
item_location game_menus::inv::consume_drink (avatar & you)
Consuming a drink item via a custom menu.
Definition at line 1043 of file game_inventory.cpp.
 {
     if( !you.has_activity( ACT_CONSUME_DRINK_MENU ) ) {
         you.assign_activity( ACT_CONSUME_DRINK_MENU );
     }
     std::string none_message = you.activity.str_values.size() == 2 ?
                                _( "You have nothing else to drink." ) : _( "You have nothing to drink." );
     return inv_internal( you, comestible_filtered_inventory_preset( you, []( const item & it ) {
         return it.is_comestible() && it.get_comestible()->comesttype == "DRINK" &&
                !it.has_flag( flag_USE_EAT_VERB );
     } ),
     _( "Consume drink" ), 1,
     none_message,
     get_consume_needs_hint( you ) );
 }
References _, ACT_CONSUME_DRINK_MENU, Character::activity, Character::assign_activity(), flag_USE_EAT_VERB, item::get_comestible(), get_consume_needs_hint(), Character::has_activity(), item::has_flag(), inv_internal(), item::is_comestible(), and player_activity::str_values.
Referenced by activity_handlers::consume_drink_menu_do_turn(), and game::open_consume_item_menu().
consume_food()
item_location game_menus::inv::consume_food (avatar & you)
Consuming a food item via a custom menu.
Definition at line 1027 of file game_inventory.cpp.
 {
     if( !you.has_activity( ACT_CONSUME_FOOD_MENU ) ) {
         you.assign_activity( ACT_CONSUME_FOOD_MENU );
     }
     std::string none_message = you.activity.str_values.size() == 2 ?
                                _( "You have nothing else to eat." ) : _( "You have nothing to eat." );
     return inv_internal( you, comestible_filtered_inventory_preset( you, []( const item & it ) {
         return ( it.is_comestible() && it.get_comestible()->comesttype == "FOOD" ) ||
                it.has_flag( flag_USE_EAT_VERB );
     } ),
     _( "Consume food" ), 1,
     none_message,
     get_consume_needs_hint( you ) );
 }
References _, ACT_CONSUME_FOOD_MENU, Character::activity, Character::assign_activity(), flag_USE_EAT_VERB, item::get_comestible(), get_consume_needs_hint(), Character::has_activity(), item::has_flag(), inv_internal(), item::is_comestible(), and player_activity::str_values.
Referenced by activity_handlers::consume_food_menu_do_turn(), and game::open_consume_item_menu().
consume_meds()
item_location game_menus::inv::consume_meds (avatar & you)
Consuming a medication item via a custom menu.
Definition at line 1059 of file game_inventory.cpp.
 {
     if( !you.has_activity( ACT_CONSUME_MEDS_MENU ) ) {
         you.assign_activity( ACT_CONSUME_MEDS_MENU );
     }
     std::string none_message = you.activity.str_values.size() == 2 ?
                                _( "You have no more medication to consume." ) : _( "You have no medication to consume." );
     return inv_internal( you, comestible_filtered_inventory_preset( you, []( const item & it ) {
         return it.is_medication() || it.is_medical_tool();
     } ),
     _( "Consume medication" ), 1,
     none_message,
     get_consume_needs_hint( you ) );
 }
References _, ACT_CONSUME_MEDS_MENU, Character::activity, Character::assign_activity(), get_consume_needs_hint(), Character::has_activity(), inv_internal(), item::is_medical_tool(), item::is_medication(), and player_activity::str_values.
Referenced by activity_handlers::consume_meds_menu_do_turn(), and game::open_consume_item_menu().
container_for()
item_location game_menus::inv::container_for (Character & you, const item & liquid, int radius = 0, const item * avoid = nullptr)
Choosing a container for liquid.
Definition at line 501 of file game_inventory.cpp.
 {
     return inv_internal( you, liquid_inventory_selector_preset( liquid, avoid ),
                          string_format( _( "Container for %s | %s %s" ), liquid.display_name( liquid.charges ),
                                         format_volume( liquid.volume() ), volume_units_abbr() ), radius,
                          string_format( _( "You don't have a suitable container for carrying %s." ),
                                         liquid.tname() ) );
 }
References _, item::charges, item::display_name(), format_volume(), inv_internal(), string_format(), item::tname(), item::volume(), and volume_units_abbr().
Referenced by liquid_handler::get_liquid_target().
disassemble()
item_location game_menus::inv::disassemble (Character & you)
Item disassembling menu.
Definition at line 641 of file game_inventory.cpp.
 {
     return inv_internal( you, disassemble_inventory_preset( you, you.crafting_inventory() ),
                          _( "Disassemble item" ), 1,
                          _( "You don't have any items you could disassemble." ) );
 }
References _, Character::crafting_inventory(), and inv_internal().
Referenced by Character::disassemble().
ebookread()
item_location game_menus::inv::ebookread (Character & you, item_location & ereader)
eBook reading menu.
Definition at line 1564 of file game_inventory.cpp.
 {
     const std::string none_message =
         you.is_avatar() ?
         string_format( _( "%1$s have nothing to read." ), you.disp_name( false, true ) ) :
         string_format( _( "%1$s has nothing to read." ), you.disp_name( false, true ) );
     const ebookread_inventory_preset preset( you );
     inventory_pick_selector inv_s( you, preset );
     inv_s.set_title( _( "Read" ) );
     inv_s.set_display_stats( false );
     inv_s.clear_items();
     inv_s.add_contained_ebooks( ereader );
     if( inv_s.empty() ) {
         popup( none_message, PF_GET_KEY );
         return item_location();
     }
     item_location location = inv_s.execute();
     return location;
 }
References _, inventory_selector::add_contained_ebooks(), inventory_selector::clear_items(), Character::disp_name(), inventory_selector::empty(), inventory_pick_selector::execute(), Creature::is_avatar(), location, PF_GET_KEY, popup(), inventory_selector::set_display_stats(), inventory_selector::set_title(), and string_format().
Referenced by npc::do_npc_read(), iuse::ebookread(), and iuse::electricstorage().
ebooksave()
drop_locations game_menus::inv::ebooksave (Character & who, item_location & ereader)
Select books to save to E-Book reader menu.
Definition at line 1590 of file game_inventory.cpp.
 {
     std::set<itype_id> already_saved;
     for( const item *ebook : ereader->ebooks() ) {
         if( !ebook->is_book() ) {
             debugmsg( "ebook type pocket contains non-book item %s", ebook->typeId().str() );
             continue;
         }
         already_saved.insert( ebook->typeId() );
     }
     const inventory_filter_preset preset( [&who, &already_saved]( const item_location & loc ) {
         return loc->is_book()
                && loc->type->book->is_scannable
                && !already_saved.count( loc->typeId() )
                && loc->is_owned_by( who, true );
     } );
     const int available_charges = ereader->ammo_remaining();
     auto make_raw_stats = [&available_charges, &ereader](
                               const std::vector<std::pair<item_location, int>> &locs
     ) {
         std::vector<item_location> books;
         books.reserve( locs.size() );
         for( const auto &pair : locs ) {
             books.push_back( pair.first );
         }
         const int required_charges = ebooksave_activity_actor::required_charges( books, ereader );
         const time_duration required_time = ebooksave_activity_actor::required_time( books );
         auto int_to_str = []( int val ) -> std::string {
             return string_format( "%d", val );
         };
         const std::string charges = string_join( display_stat( "", required_charges,
                                     available_charges,
                                     int_to_str ), "" );
         const std::string time = colorize( to_string( required_time, true ),
                                            c_light_gray );
         using stats = inventory_selector::stats;
         return stats{{
                 {{ _( "Charges" ), charges }},
                 {{ _( "Estimated time" ), time }}
             }};
     };
     inventory_multiselector inv_s( who, preset, _( "SELECT BOOKS TO SCAN" ),
                                    make_raw_stats, /*allow_select_contained=*/true );
     inv_s.add_character_items( who );
     inv_s.add_nearby_items( PICKUP_RANGE );
     inv_s.set_title( _( "Scan which books?" ) );
     if( inv_s.empty() ) {
         popup( std::string( _( "You have no books to scan." ) ), PF_GET_KEY );
         return drop_locations();
     }
     return inv_s.execute();
 }
References _, inventory_selector::add_character_items(), inventory_selector::add_nearby_items(), item::ammo_remaining(), itype::book, c_light_gray, colorize(), debugmsg, display_stat(), item::ebooks(), inventory_selector::empty(), inventory_multiselector::execute(), int_to_str(), item::is_book(), item::is_owned_by(), PF_GET_KEY, PICKUP_RANGE, popup(), ebooksave_activity_actor::required_charges(), ebooksave_activity_actor::required_time(), inventory_selector::set_title(), string_format(), string_join(), to_string(), item::type, and item::typeId().
Referenced by iuse::ebooksave().
ereader_to_use()
item_location game_menus::inv::ereader_to_use (Character & you)
E-Book reading menu.
Definition at line 1377 of file game_inventory.cpp.
 {
     const std::string msg = _( "You don't have any e-readers you can use." );
     return inv_internal( you, ereader_inventory_preset( you ), _( "Select e-reader." ), 1, msg );
 }
References _, and inv_internal().
Referenced by npc::do_npc_read().
gun_to_modify()
item_location game_menus::inv::gun_to_modify (Character & you, const item & gunmod)
Gunmod installation menu.
Definition at line 1251 of file game_inventory.cpp.
 {
     return inv_internal( you, gunmod_inventory_preset( you, gunmod ),
                          _( "Select gun to modify" ), -1,
                          _( "You don't have any guns to modify." ) );
 }
References _, and inv_internal().
Referenced by iuse::gunmod_attach().
gunmod_to_remove()
item_location game_menus::inv::gunmod_to_remove (Character & you, item & gun)
Gunmod removal menu.
Definition at line 1308 of file game_inventory.cpp.
 {
     const std::string none_message = _( "You don't have any mods to remove." );
     const gunmod_remove_inventory_preset preset( you, gun );
     inventory_pick_selector inv_s( you, preset );
     inv_s.set_title( _( "Remove which modification?" ) );
     inv_s.set_display_stats( false );
     inv_s.clear_items();
     inv_s.add_contained_gunmods( you, gun );
     if( inv_s.empty() ) {
         popup( none_message, PF_GET_KEY );
         return item_location();
     }
     item_location location = inv_s.execute();
     return location;
 }
References _, inventory_selector::add_contained_gunmods(), inventory_selector::clear_items(), inventory_selector::empty(), inventory_pick_selector::execute(), gun, location, PF_GET_KEY, popup(), inventory_selector::set_display_stats(), and inventory_selector::set_title().
Referenced by detach_gunmods_actor::use().
holster()
drop_locations game_menus::inv::holster (avatar & you, const item_location & holster)
Item wielding/unwielding menu.
Definition at line 1788 of file game_inventory.cpp.
 {
     const std::string holster_name = holster->tname( 1, false );
     const use_function *use = holster->type->get_use( "holster" );
     const holster_actor *actor = use == nullptr ? nullptr : dynamic_cast<const holster_actor *>
                                  ( use->get_actor_ptr() );
     const std::string title = ( actor ? actor->holster_prompt.empty() : true )
                               ? string_format( _( "Put item into %s" ), holster->tname() )
                               : actor->holster_prompt.translated();
     const std::string hint = string_format( _( "Choose an item to put into your %s" ),
                                             holster_name );
     inventory_holster_preset holster_preset( holster, &get_avatar() );
     inventory_insert_selector insert_menu( you, holster_preset, _( "ITEMS TO INSERT" ),
                                            /*warn_liquid=*/false );
     insert_menu.add_character_items( you );
     insert_menu.add_nearby_items( 1 );
     insert_menu.set_display_stats( true );
     insert_menu.set_title( title );
     insert_menu.set_hint( hint );
     return insert_menu.execute();
 }
References _, inventory_selector::add_character_items(), inventory_selector::add_nearby_items(), translation::empty(), inventory_drop_selector::execute(), get_avatar(), holster_actor::holster_prompt, inventory_selector::set_display_stats(), inventory_selector::set_hint(), inventory_selector::set_title(), string_format(), music::title, translation::translated(), and use().
Referenced by holster_actor::can_holster(), inventory_holster_preset::get_denial(), inventory_holster_preset::get_holster(), inventory_insert_selector::get_raw_stats(), insert_items(), inventory_holster_preset::is_shown(), holster_actor::store(), and try_insert().
insert_items()
void game_menus::inv::insert_items (avatar & you, item_location & holster)
Definition at line 1815 of file game_inventory.cpp.
 {
     if( holster->will_spill_if_unsealed()
         && holster.where() != item_location::type::map
         && !you.is_wielding( *holster ) ) {
         you.add_msg_if_player( m_info, _( "The %s would spill unless it's on the ground or wielded." ),
                                holster->type_name() );
         return;
     }
     drop_locations holstered_list = game_menus::inv::holster( you, holster );
     if( !holstered_list.empty() ) {
         you.assign_activity( insert_item_activity_actor( holster, holstered_list ) );
     }
 }
References _, Character::add_msg_if_player(), Character::assign_activity(), holster(), Character::is_wielding(), m_info, and item_location::map.
Referenced by game::insert_item(), game::inventory_item_menu(), and holster_actor::use().
install_bionic()
item_location game_menus::inv::install_bionic (Character & installer, Character & patron, Character & patient, bool surgeon = false)
Bionic install menu.
Definition at line 2710 of file game_inventory.cpp.
 {
     if( surgeon ) {
         return autodoc_internal( patron, patient, bionic_install_surgeon_preset( installer, patient ), 5,
                                  surgeon );
     } else {
         return autodoc_internal( patron, patient, bionic_install_preset( installer, patient ), 5 );
     }
 }
References autodoc_internal().
Referenced by iexamine::autodoc(), and bionic_install_common().
molle_attach()
item_location game_menus::inv::molle_attach (Character & you, item & tool)
Choosing an item to attach to a load bearing vest.
Definition at line 2153 of file game_inventory.cpp.
 {
     const molle_attach_actor *actor = dynamic_cast<const molle_attach_actor *>
                                       ( tool.type->get_use( "attach_molle" )->get_actor_ptr() );
     if( !actor ) {
         debugmsg( "Tried to use a wrong item." );
         return item_location();
     }
     const int vacancies = actor->size - tool.get_contents().get_additional_space_used();
     return inv_internal( you, attach_molle_inventory_preset( actor, &tool ),
                          _( "Attach an item to the vest" ), 1,
                          _( "You don't have any MOLLE compatible items." ),
                          string_format( "%s\n%s",
                                         string_format( _( "Choose an accessory to attach to your %s" ),
                                                 tool.tname( 1, false ) ),
                                         string_format( n_gettext( "There is space for %d small item",
                                                 "There is space for %d small items",
                                                 vacancies ), vacancies )
                                       )
                        );
 }
References _, debugmsg, use_function::get_actor_ptr(), item_contents::get_additional_space_used(), item::get_contents(), itype::get_use(), inv_internal(), n_gettext, molle_attach_actor::size, string_format(), item::tname(), and item::type.
Referenced by molle_attach_actor::use().
multidrop()
drop_locations game_menus::inv::multidrop (Character & you)
Select items to drop.
Returns
A list of pairs of item_location, quantity.
Definition at line 2190 of file game_inventory.cpp.
 {
     you.inv->restack( you );
     const inventory_filter_preset preset( [ &you ]( const item_location & location ) {
         return you.can_drop( *location ).success() &&
                ( !location.get_item()->is_frozen_liquid() || !location.has_parent() ||
                  location.get_item()->has_flag( flag_SHREDDED ) );
     } );
     inventory_drop_selector inv_s( you, preset );
     inv_s.add_character_items( you );
     inv_s.set_title( _( "Multidrop" ) );
     inv_s.set_hint( _( "To drop x items, type a number before selecting." ) );
     if( inv_s.empty() ) {
         popup( std::string( _( "You have nothing to drop." ) ), PF_GET_KEY );
         return drop_locations();
     }
     return inv_s.execute();
 }
References _, Character::can_drop(), flag_SHREDDED, Character::inv, location, PF_GET_KEY, popup(), and ret_val_common::success().
Referenced by debug_menu::character_edit_menu(), game::drop_in_direction(), and anonymous_namespace{monexamine.cpp}::give_items_to().
pickup()
drop_locations game_menus::inv::pickup (avatar & you, const std::optional< tripoint > & target = std::nullopt, const std::vector< drop_location > & selection = {})
Select items to pick up.
If target is provided, pick up items only from that tile (presumably adjacent to the avatar). Otherwise, pick up items from the avatar's current location and all adjacent tiles.
Returns
A list of pairs of item_location, quantity.
Definition at line 2214 of file game_inventory.cpp.
 {
     pickup_inventory_preset preset( you, /*skip_wield_check=*/true, /*ignore_liquidcont=*/true );
     preset.save_state = &pickup_ui_default_state;
     pickup_selector pick_s( you, preset, _( "ITEMS TO PICK UP" ), target );
     // Add items from the selected tile, or from current and all surrounding tiles
     if( target ) {
         pick_s.add_vehicle_items( *target );
         pick_s.add_map_items( *target );
     } else {
         pick_s.add_nearby_items();
     }
     pick_s.set_title( _( "Pickup" ) );
     if( pick_s.empty() ) {
         popup( std::string( _( "There is nothing to pick up." ) ), PF_GET_KEY );
         return drop_locations();
     }
     if( !selection.empty() ) {
         pick_s.apply_selection( selection );
     }
     return pick_s.execute();
 }
References _, inventory_selector::add_map_items(), inventory_selector::add_nearby_items(), inventory_selector::add_vehicle_items(), pickup_selector::apply_selection(), inventory_selector::empty(), pickup_selector::execute(), PF_GET_KEY, pickup_ui_default_state, popup(), inventory_selector_preset::save_state, and inventory_selector::set_title().
Referenced by pickup_menu_activity_actor::do_turn(), game::pickup(), and game::pickup_all().
read()
item_location game_menus::inv::read (Character & you)
Book reading menu.
Definition at line 1557 of file game_inventory.cpp.
 {
     const std::string msg = you.is_avatar() ? _( "You have nothing to read." ) :
                             string_format( _( "%s has nothing to read." ), you.disp_name() );
     return inv_internal( you, read_inventory_preset( you ), _( "Read" ), 1, msg );
 }
References _, Character::disp_name(), inv_internal(), Creature::is_avatar(), and string_format().
Referenced by npc::do_npc_read(), and read().
reassign_letter()
void game_menus::inv::reassign_letter (avatar & you, item & it)
Definition at line 2427 of file game_inventory.cpp.
 {
     while( true ) {
         const int invlet = popup_getkey(
                                _( "Enter new letter.  Press SPACE to clear a manually-assigned letter, ESCAPE to cancel." ) );
         if( invlet == KEY_ESCAPE ) {
             break;
         } else if( invlet == ' ' ) {
             you.reassign_item( it, 0 );
             const std::string auto_setting = get_option<std::string>( "AUTO_INV_ASSIGN" );
             if( auto_setting == "enabled" || ( auto_setting == "favorites" && it.is_favorite ) ) {
                 popup_getkey(
                     _( "Note: The Auto Inventory Letters setting might still reassign a letter to this item.\n"
                        "If this is undesired, you may wish to change the setting in Options." ) );
             }
             break;
         } else if( inv_chars.valid( invlet ) ) {
             you.reassign_item( it, invlet );
             break;
         }
     }
 }
References _, inv_chars, item::is_favorite, KEY_ESCAPE, popup_getkey(), avatar::reassign_item(), and invlet_wrapper::valid().
Referenced by game::inventory_item_menu(), and swap_letters().
repair()
item_location game_menus::inv::repair (Character & you, const repair_item_actor * actor, const item * main_tool)
Repair menu.
Definition at line 2106 of file game_inventory.cpp.
 {
     return inv_internal( you, repair_inventory_preset( actor, main_tool, you ),
                          _( "Repair what?" ), 1,
                          string_format( _( "You have no items that could be repaired with a %s." ),
                                         main_tool->type_name( 1 ) ), get_repair_hint( you, actor, main_tool ) );
 }
References _, get_repair_hint(), inv_internal(), string_format(), and item::type_name().
Referenced by repair_item_finish().
salvage()
item_location game_menus::inv::salvage (Character & you, const salvage_actor * actor)
Item cut up menu.
Definition at line 2009 of file game_inventory.cpp.
 {
     return inv_internal( you, salvage_inventory_preset( actor ),
                          _( "Cut up what?" ), 1,
                          _( "You have nothing to cut up." ) );
 }
References _, and inv_internal().
Referenced by salvage_actor::cut_up(), and salvage_actor::use().
saw_barrel()
item_location game_menus::inv::saw_barrel (Character & you, item & tool)
Choosing a gun to saw down it's barrel.
Definition at line 2115 of file game_inventory.cpp.
 {
     const saw_barrel_actor *actor = dynamic_cast<const saw_barrel_actor *>
                                     ( tool.type->get_use( "saw_barrel" )->get_actor_ptr() );
     if( !actor ) {
         debugmsg( "Tried to use a wrong item." );
         return item_location();
     }
     return inv_internal( you, saw_barrel_inventory_preset( you, tool, *actor ),
                          _( "Saw barrel" ), 1,
                          _( "You don't have any guns." ),
                          string_format( _( "Choose a weapon to use your %s on" ),
                                         tool.tname( 1, false )
                                       )
                        );
 }
References _, debugmsg, use_function::get_actor_ptr(), itype::get_use(), inv_internal(), string_format(), item::tname(), and item::type.
Referenced by saw_barrel_actor::use().
saw_stock()
item_location game_menus::inv::saw_stock (Character & you, item & tool)
Choosing a gun to saw down its barrel.
Definition at line 2134 of file game_inventory.cpp.
 {
     const saw_stock_actor *actor = dynamic_cast<const saw_stock_actor *>
                                    ( tool.type->get_use( "saw_stock" )->get_actor_ptr() );
     if( !actor ) {
         debugmsg( "Tried to use a wrong item." );
         return item_location();
     }
     return inv_internal( you, saw_stock_inventory_preset( you, tool, *actor ),
                          _( "Saw stock" ), 1,
                          _( "You don't have any guns." ),
                          string_format( _( "Choose a weapon to use your %s on" ),
                                         tool.tname( 1, false )
                                       )
                        );
 }
References _, debugmsg, use_function::get_actor_ptr(), itype::get_use(), inv_internal(), string_format(), item::tname(), and item::type.
Referenced by saw_stock_actor::use().
select_ammo()
item::reload_option game_menus::inv::select_ammo (Character & you, const item_location & loc, bool prompt = false, bool empty = true)
Definition at line 2912 of file game_inventory.cpp.
 {
     const select_ammo_inventory_preset preset( you, loc, empty );
     ammo_inventory_selector inv_s( you, loc, preset );
     inv_s.set_title( string_format( loc->is_watertight_container() ? _( "Refill %s" ) :
                                     loc->has_flag( flag_RELOAD_AND_SHOOT ) ? _( "Select ammo for %s" ) : _( "Reload %s" ),
                                     loc->display_name() ) );
     inv_s.set_hint( _( "Choose ammo to reload" ) );
     inv_s.set_display_stats( false );
     inv_s.clear_items();
     inv_s.add_character_items( you );
     inv_s.add_nearby_items( 1 );
     inv_s.set_all_entries_chosen_count();
     if( inv_s.empty() ) {
         popup( _( "You have nothing to reload." ), PF_GET_KEY );
         return item::reload_option();
     }
     drop_location selected;
     if( !prompt && inv_s.item_entry_count() == 1 ) {
         selected = inv_s.get_only_choice();
     } else {
         selected = inv_s.execute();
     }
     if( !selected.first ) {
         return item::reload_option();
     }
     item_location target_loc;
     for( const item_location &opt : get_possible_reload_targets( loc ) ) {
         if( opt->can_reload_with( *selected.first, true ) ) {
             target_loc = opt;
             break;
         }
     }
     item::reload_option opt( &you, target_loc, selected.first );
     opt.qty( selected.second );
     return opt;
 }
References _, inventory_selector::add_character_items(), inventory_selector::add_nearby_items(), inventory_selector::clear_items(), item::display_name(), inventory_selector::empty(), ammo_inventory_selector::execute(), flag_RELOAD_AND_SHOOT, inventory_selector::get_only_choice(), get_possible_reload_targets(), item::has_flag(), item::is_watertight_container(), inventory_selector::item_entry_count(), PF_GET_KEY, popup(), Pickup::prompt, item::reload_option::qty(), ammo_inventory_selector::set_all_entries_chosen_count(), inventory_selector::set_display_stats(), inventory_selector::set_hint(), inventory_selector::set_title(), and string_format().
Referenced by reload_furniture(), and avatar::select_ammo().
smoke_food()
drop_locations game_menus::inv::smoke_food (Character & you, units::volume total_capacity, units::volume used_capacity)
Definition at line 2251 of file game_inventory.cpp.
 {
     const smokable_selector_preset preset;
     auto make_raw_stats = [ &total_capacity, &used_capacity ]
     ( const std::vector<std::pair<item_location, int>> &locs ) {
         units::volume added_volume = 0_ml;
         for( std::pair<item_location, int> loc : locs ) {
             added_volume += loc.first->volume() * loc.second / loc.first->count();
         }
         std::string volume_caption = string_format( _( "Volume (%s):" ), volume_units_abbr() );
         return inventory_selector::stats{
             {
                 display_stat( volume_caption,
                               units::to_milliliter( used_capacity + added_volume ),
                               units::to_milliliter( total_capacity ), []( int v )
                 {
                     return format_volume( units::from_milliliter( v ) );
                 } )
             }
         };
     };
     inventory_multiselector smoke_s( you, preset, _( "FOOD TO SMOKE" ), make_raw_stats );
     smoke_s.add_nearby_items( PICKUP_RANGE );
     smoke_s.add_character_items( you );
     smoke_s.set_title( _( "Insert food into smoking rack" ) );
     smoke_s.set_hint( _( "To select x items, type a number before selecting." ) );
     smoke_s.set_invlet_type( inventory_selector::selector_invlet_type::SELECTOR_INVLET_ALPHA );
     if( smoke_s.empty() ) {
         popup( std::string( _( "You don't have any food that can be smoked." ) ), PF_GET_KEY );
         return drop_locations();
     }
     return smoke_s.execute();
 }
References _, inventory_selector::add_character_items(), inventory_selector::add_nearby_items(), item::count(), display_stat(), inventory_selector::empty(), inventory_multiselector::execute(), format_volume(), units::from_milliliter(), PF_GET_KEY, PICKUP_RANGE, popup(), inventory_selector::set_hint(), inventory_selector::set_invlet_type(), inventory_selector::set_title(), string_format(), units::to_milliliter(), item::volume(), and volume_units_abbr().
Referenced by smoker_load_food().
steal()
item_location game_menus::inv::steal (avatar & you, Character & victim)
Menu for stealing stuff.
Definition at line 1660 of file game_inventory.cpp.
 {
     return inv_internal( victim, steal_inventory_preset( you, victim ),
                          string_format( _( "Steal from %s" ), victim.get_name() ), -1,
                          string_format( _( "%s's inventory is empty." ), victim.get_name() ) );
 }
References _, Character::get_name(), inv_internal(), and string_format().
Referenced by game::npc_menu(), and avatar::steal().
sterilize_cbm()
item_location game_menus::inv::sterilize_cbm (Character & you)
Autoclave sterilize menu.
swap_letters()
void game_menus::inv::swap_letters (avatar & you)
Definition at line 2451 of file game_inventory.cpp.
 {
     you.inv->restack( you );
     inventory_pick_selector inv_s( you );
     inv_s.add_character_items( you );
     inv_s.set_title( _( "Swap Inventory Letters" ) );
     inv_s.set_display_stats( false );
     if( inv_s.empty() ) {
         popup( std::string( _( "Your inventory is empty." ) ), PF_GET_KEY );
         return;
     }
     while( true ) {
         const std::string invlets = colorize_symbols( inv_chars.get_allowed_chars(),
         [ &you ]( const std::string::value_type & elem ) {
             if( you.inv->assigned_invlet.count( elem ) ) {
                 return c_yellow;
             } else if( you.invlet_to_item( elem ) != nullptr ) {
                 return c_white;
             } else {
                 return c_dark_gray;
             }
         } );
         inv_s.set_hint( invlets );
         item_location loc = inv_s.execute();
         if( !loc ) {
             break;
         }
         reassign_letter( you, *loc );
     }
 }
References _, inventory_selector::add_character_items(), colorize_symbols(), inventory_selector::empty(), inventory_pick_selector::execute(), invlet_wrapper::get_allowed_chars(), Character::inv, inv_chars, Character::invlet_to_item(), PF_GET_KEY, popup(), reassign_letter(), inventory_selector::set_display_stats(), inventory_selector::set_hint(), and inventory_selector::set_title().
Referenced by game::do_regular_action().
take_off()
item_location game_menus::inv::take_off (avatar & you)
Choose item to take off.
Definition at line 449 of file game_inventory.cpp.
 {
     return inv_internal( you, take_off_inventory_preset( you, "color_red" ), _( "Take off item" ), 1,
                          _( "You're not wearing anything." ) );
 }
References _, and inv_internal().
Referenced by takeoff().
titled_filter_menu() [1/2]
item_location game_menus::inv::titled_filter_menu (const item_filter & filter, Character & you, const std::string & title, int radius = -1, const std::string & none_message = "")
Definition at line 315 of file game_inventory.cpp.
 {
     return inv_internal( you, inventory_filter_preset( convert_filter( filter ) ),
                          title, radius, none_message );
 }
References convert_filter(), filter, inv_internal(), and music::title.
Referenced by anonymous_namespace{monexamine.cpp}::attach_bag_to(), iuse::camera(), change_armor_sprite(), iuse::electricstorage(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_inv_eocs(), iuse::gun_repair(), link_up_actor::link_extend_cable(), iuse::lumber(), game::npc_menu(), anonymous_namespace{monexamine.cpp}::pet_armor_loc(), pick_usb(), iuse::radio_mod(), iuse::radiocar(), anonymous_namespace{monexamine.cpp}::tack_loc(), sew_advanced_actor::use(), and link_up_actor::use().
titled_filter_menu() [2/2]
item_location game_menus::inv::titled_filter_menu (const item_location_filter & filter, Character & you, const std::string & title, int radius = -1, const std::string & none_message = "")
Definition at line 322 of file game_inventory.cpp.
 {
     return inv_internal( you, inventory_filter_preset( filter ), title, radius, none_message );
 }
References filter, inv_internal(), and music::title.
titled_menu()
item_location game_menus::inv::titled_menu (Character & you, const std::string & title, const std::string & none_message = "")
Definition at line 334 of file game_inventory.cpp.
 {
     const std::string msg = none_message.empty() ? _( "Your inventory is empty." ) : none_message;
     return inv_internal( you, inventory_selector_preset(), title, -1, msg );
 }
References _, inv_internal(), and music::title.
Referenced by debug_menu::character_edit_menu(), talker_npc::give_item_to(), avatar_action::plthrow(), and inscribe_actor::use().
titled_multi_filter_menu()
drop_locations game_menus::inv::titled_multi_filter_menu (const item_location_filter & filter, Character & you, const std::string & title, int radius = -1, const std::string & none_message = "")
Definition at line 328 of file game_inventory.cpp.
 {
     return inv_internal_multi( you, inventory_filter_preset( filter ), title, radius, none_message );
 }
References filter, inv_internal_multi(), and music::title.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_inv_eocs().
unload()
std::pair< item_location, bool > game_menus::inv::unload (Character & you)
Unload item menu.
Definition at line 2757 of file game_inventory.cpp.
 {
     const inventory_filter_preset preset( [&you]( const item_location & location ) {
         return you.rate_action_unload( *location ) == hint_rating::good;
     } );
     unload_selector inv_s( you, preset );
     inv_s.set_title( _( "Unload item" ) );
     inv_s.set_display_stats( false );
     you.inv->restack( you );
     inv_s.clear_items();
     inv_s.add_character_items( you );
     inv_s.add_nearby_items( 1 );
     if( inv_s.empty() ) {
         popup( _( "You have nothing to unload." ), PF_GET_KEY );
         return std::make_pair( item_location(), false );
     }
     return inv_s.execute();
 }
References _, good, Character::inv, location, PF_GET_KEY, popup(), and Character::rate_action_unload().
Referenced by avatar_action::unload().
unload_container()
drop_locations game_menus::inv::unload_container (avatar & you)
Definition at line 1857 of file game_inventory.cpp.
 {
     inventory_filter_preset unload_preset( valid_unload_container );
     inventory_drop_selector insert_menu( you, unload_preset, _( "CONTAINERS TO UNLOAD" ),
                                          /*warn_liquid=*/false );
     insert_menu.add_character_items( you );
     insert_menu.add_nearby_items( 1 );
     insert_menu.set_display_stats( false );
     insert_menu.set_title( _( "Select containers to unload" ) );
     drop_locations dropped;
     for( drop_location &droplc : insert_menu.execute() ) {
         for( item *it : droplc.first->all_items_top( pocket_type::CONTAINER, true ) ) {
             // no liquids and no items marked as favorite
             if( ( !it->made_of( phase_id::LIQUID ) || ( it->made_of( phase_id::LIQUID ) &&
                     it->is_frozen_liquid() ) ) && !it->is_favorite ) {
                 dropped.emplace_back( item_location( droplc.first, it ), it->count() );
             }
         }
     }
     return dropped;
 }
References _, inventory_selector::add_character_items(), inventory_selector::add_nearby_items(), item::all_items_top(), CONTAINER, item::count(), inventory_drop_selector::execute(), LIQUID, inventory_selector::set_display_stats(), inventory_selector::set_title(), and valid_unload_container().
Referenced by game::unload_container().
use()
item_location game_menus::inv::use (avatar & you)
Item activation menu.
Definition at line 1180 of file game_inventory.cpp.
 {
     return inv_internal( you, activatable_inventory_preset( you ),
                          _( "Use item" ), 1,
                          _( "You don't have any items you can use." ) );
 }
References _, and inv_internal().
Referenced by holster(), itype::invoke(), mattack::kamikaze(), item_action_generator::map_actions_to_items(), snippet_library::reload_names(), and avatar_action::use_item().
veh_tool_attach()
item_location game_menus::inv::veh_tool_attach (Character & you, const std::string & vp_name, const std::set< itype_id > & allowed_types)
Choosing an item to attach to a vehicle tool station.
Definition at line 2178 of file game_inventory.cpp.
 {
     return inv_internal( you, attach_veh_tool_inventory_preset( allowed_types ),
                          string_format( _( "Attach an item to the %s" ), vp_name ), 1,
                          string_format( _( "You don't have any items compatible with %s.\n\nAllowed equipment:\n%s" ),
     vp_name, enumerate_as_string( allowed_types, []( const itype_id & it ) {
         return it->nname( 1 );
     } ) ),
     string_format( _( "Choose a tool to attach to %s" ), vp_name ) );
 }
References _, enumerate_as_string(), inv_internal(), itype::nname(), and string_format().
wear()
item_location game_menus::inv::wear (Character & you, const bodypart_id & bp = bodypart_id("bp_null"))
Choose item to wear.
Definition at line 421 of file game_inventory.cpp.
 {
     return inv_internal( you, wear_inventory_preset( you, "color_yellow", bp ), _( "Wear item" ), 1,
                          _( "You have nothing to wear." ) );
 }
References _, bp, and inv_internal().
Referenced by outfit::sort_armor(), and wear().
wield()
item_location game_menus::inv::wield (avatar & you)
Item wielding/unwielding menu.
Definition at line 1766 of file game_inventory.cpp.
 {
     return inv_internal( you, weapon_inventory_preset( you ), _( "Wield item" ), 1,
                          _( "You have nothing to wield." ) );
 }
References _, and inv_internal().
Referenced by game::wield().