Cataclysm DDA: anonymous_namespace{trade_ui.cpp} Namespace Reference
anonymous_namespace{trade_ui.cpp} Namespace Reference
Functions
point _pane_orig (int side)
point _pane_size ()
Function Documentation
_pane_orig()
point anonymous_namespace{trade_ui.cpp}::_pane_orig (int side)
Definition at line 30 of file trade_ui.cpp.
 {
     return { side > 0 ? TERMX / 2 : 0, trade_ui::header_size };
 }
References trade_ui::header_size, and TERMX.
Referenced by _pane_size(), and trade_ui::resize().
_pane_size()
point anonymous_namespace{trade_ui.cpp}::_pane_size ()
Definition at line 35 of file trade_ui.cpp.
 {
     return { TERMX / 2, TERMY - _pane_orig( 0 ).y };
 }
References _pane_orig(), TERMX, TERMY, and point::y.
Referenced by trade_ui::resize().