Cataclysm DDA: trait_group Namespace Reference
trait_group Namespace Reference
Typedefs
using Trait_group_tag = string_id< Trait_group >
using Trait_list = std::vector< trait_and_var >
Functions
Trait_list traits_from (const Trait_group_tag &gid)
Returns a randomized list of traits from the given trait group.
bool group_contains_trait (const Trait_group_tag &gid, const trait_id &tid)
Check whether a particular trait is a member of the given group.
void load_trait_group (const JsonObject &jsobj, const Trait_group_tag &gid, const std::string &subtype)
See mutation_branch::load_trait_group.
Trait_group_tag load_trait_group (const JsonValue &value, const std::string &default_subtype)
Get a trait group ID and optionally load an inlined trait group.
void debug_spawn ()
Show a debug menu for testing trait groups.
Typedef Documentation
Trait_group_tag
typedef string_id< Trait_group > trait_group::Trait_group_tag
Definition at line 24 of file npc_class.h.
Trait_list
using trait_group::Trait_list = typedef std::vector<trait_and_var>
Definition at line 21 of file trait_group.h.
Function Documentation
debug_spawn()
void trait_group::debug_spawn ()
Show a debug menu for testing trait groups.
Definition at line 85 of file trait_group.cpp.
 {
     std::vector<Trait_group_tag> groups = mutation_branch::get_all_group_names();
     uilist menu;
     menu.text = _( "Test which group?" );
     for( size_t i = 0; i < groups.size(); i++ ) {
         menu.entries.emplace_back( static_cast<int>( i ), true, -2, groups[i].str() );
     }
     while( true ) {
         menu.query();
         const int index = menu.ret;
         if( index >= static_cast<int>( groups.size() ) || index < 0 ) {
             break;
         }
         // Spawn traits from the group 100 times
         std::map<std::string, int> traitnames;
         for( size_t a = 0; a < 100; a++ ) {
             const Trait_list traits = traits_from( groups[index] );
             for( const trait_and_var &tr : traits ) {
                 traitnames[tr.name()]++;
             }
         }
         // Invert the map to get sorting!
         std::multimap<int, std::string> traitnames2;
         for( const auto &e : traitnames ) {
             traitnames2.insert( std::pair<int, std::string>( e.second, e.first ) );
         }
         uilist menu2;
         menu2.text = _( "Result of 100 spawns:" );
         for( const auto &e : traitnames2 ) {
             menu2.entries.emplace_back( static_cast<int>( menu2.entries.size() ), true, -2,
                                         string_format( _( "%d x %s" ), e.first, e.second ) );
         }
         menu2.query();
     }
 }
References _, a, uilist::entries, mutation_branch::get_all_group_names(), uilist::query(), uilist::ret, string_format(), uilist::text, and traits_from().
Referenced by debug_menu::debug().
group_contains_trait()
bool trait_group::group_contains_trait (const Trait_group_tag & gid, const trait_id & tid)
Check whether a particular trait is a member of the given group.
Definition at line 26 of file trait_group.cpp.
 {
     return mutation_branch::get_group( gid )->has_trait( tid );
 }
References mutation_branch::get_group().
load_trait_group() [1/2]
void trait_group::load_trait_group (const JsonObject & jsobj, const Trait_group_tag & gid, const std::string & subtype)
See mutation_branch::load_trait_group.
Definition at line 31 of file trait_group.cpp.
 {
     mutation_branch::load_trait_group( jsobj, gid, subtype );
 }
References mutation_branch::load_trait_group(), and subtype.
Referenced by npc_class::load().
load_trait_group() [2/2]
Trait_group_tag trait_group::load_trait_group (const JsonValue & value, const std::string & default_subtype)
Get a trait group ID and optionally load an inlined trait group.
If the value is string, it's assumed to be a trait group id and it's returned directly.
If the value is a JSON object, it is loaded as a trait group. The group will be given a unique id (if the JSON object contains an id, it is ignored) and that id will be returned. If the JSON object does not contain a subtype, the given default is used.
If the value is a JSON array, it is loaded as a trait group: the default_subtype will be used as subtype of the new trait group and the array is loaded like the "entries" array of a trait group definition (see format of trait groups).
Parameters
default_subtype If an inlined trait group is loaded this is used as the default subtype. It must be either "distribution" or "collection". See Trait_group.
Exceptions
JsonError as usual for JSON errors, including invalid input values.
Definition at line 55 of file trait_group.cpp.
 {
     if( value.test_string() ) {
         return Trait_group_tag( value.get_string() );
     } else if( value.test_object() ) {
         Trait_group_tag group = get_unique_trait_group_id();
         JsonObject jo = value.get_object();
         const std::string subtype = jo.get_string( "subtype", default_subtype );
         mutation_branch::load_trait_group( jo, group, subtype );
         return group;
     } else if( value.test_array() ) {
         Trait_group_tag group = get_unique_trait_group_id();
         if( default_subtype != "collection" && default_subtype != "distribution" ) {
             value.throw_error( "invalid subtype for trait group" );
         }
         mutation_branch::load_trait_group( value.get_array(), group, default_subtype == "collection" );
         return group;
     } else {
         value.throw_error( "invalid trait group, must be string (group id) or object/array (the group data)" );
         return Trait_group_tag{};
     }
 }
References JsonValue::get_array(), JsonValue::get_object(), JsonValue::get_string(), JsonObject::get_string(), get_unique_trait_group_id(), mutation_branch::load_trait_group(), subtype, JsonValue::test_array(), JsonValue::test_object(), JsonValue::test_string(), and JsonValue::throw_error().
traits_from()
Trait_list trait_group::traits_from (const Trait_group_tag & gid)
Returns a randomized list of traits from the given trait group.
Definition at line 21 of file trait_group.cpp.
 {
     return mutation_branch::get_group( gid )->create();
 }
References mutation_branch::get_group().
Referenced by debug_spawn(), and npc::randomize().