Cataclysm DDA: anonymous_namespace{npctrade.cpp} Namespace Reference
anonymous_namespace{npctrade.cpp} Namespace Reference
Functions
int _trading_price (Character const &buyer, Character const &seller, item_location const &it, int amount)
Function Documentation
_trading_price()
int anonymous_namespace{npctrade.cpp}::_trading_price (Character const & buyer, Character const & seller, item_location const & it, int amount)
Definition at line 197 of file npctrade.cpp.
 {
     if( seller.is_npc() ) {
         if( !seller.as_npc()->wants_to_sell( it, 1 ).success() ) {
             return 0;
         }
     } else if( buyer.is_npc() ) {
         if( !buyer.as_npc()->wants_to_buy( *it, 1 ).success() ) {
             return 0;
         }
     }
     int ret = npc_trading::adjusted_price( it.get_item(), amount, buyer, seller );
     for( item_pocket const *pk : it->get_all_standard_pockets() ) {
         for( item const *pkit : pk->all_items_top() ) {
             ret += _trading_price( buyer, seller, item_location{ it, const_cast<item *>( pkit ) },
                                    -1 );
         }
     }
     return ret;
 }
References npc_trading::adjusted_price(), item::all_items_top(), Creature::as_npc(), item::get_all_standard_pockets(), item_location::get_item(), Character::is_npc(), cata::hash64_detail::ret, npc::wants_to_buy(), and npc::wants_to_sell().
Referenced by npc_trading::trading_price().