Cataclysm DDA: overmap_connections Namespace Reference
overmap_connections Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void finalize ()
void check_consistency ()
void reset ()
string_id< overmap_connection > guess_for (const int_id< oter_type_t > &oter_id)
string_id< overmap_connection > guess_for (const int_id< oter_t > &oter_id)
Function Documentation
check_consistency()
void overmap_connections::check_consistency ()
Definition at line 143 of file overmap_connection.cpp.
 {
     connections.check();
 }
References anonymous_namespace{overmap_connection.cpp}::connections.
Referenced by DynamicDataLoader::check_consistency().
finalize()
void overmap_connections::finalize ()
Definition at line 135 of file overmap_connection.cpp.
 {
     connections.finalize();
     for( const overmap_connection &elem : connections.get_all() ) {
         const_cast<overmap_connection &>( elem ).finalize(); // This cast is ugly, but safe.
     }
 }
References anonymous_namespace{overmap_connection.cpp}::connections, and overmap_connection::finalize().
Referenced by DynamicDataLoader::finalize_loaded_data().
guess_for() [1/2]
string_id< overmap_connection > overmap_connections::guess_for (const int_id< oter_t > & oter_id)
Definition at line 153 of file overmap_connection.cpp.
 {
     const auto &all = connections.get_all();
     const auto iter = std::find_if( all.cbegin(),
     all.cend(), [&oter_id]( const overmap_connection & elem ) {
         return elem.pick_subtype_for( oter_id ) != nullptr;
     } );
     return iter != all.cend() ? iter->id : string_id<overmap_connection>::NULL_ID();
 }
References om_direction::all, anonymous_namespace{overmap_connection.cpp}::connections, and string_id< T >::NULL_ID().
guess_for() [2/2]
string_id< overmap_connection > overmap_connections::guess_for (const int_id< oter_type_t > & oter_id)
Definition at line 164 of file overmap_connection.cpp.
 {
     return guess_for( oter_id->get_first() );
 }
Referenced by fixed_overmap_special_data::finalize(), and overmapbuffer::reveal_route().
load()
void overmap_connections::load (const JsonObject & jo, const std::string & src)
Definition at line 130 of file overmap_connection.cpp.
 {
     connections.load( jo, src );
 }
References anonymous_namespace{overmap_connection.cpp}::connections, and overmap_connection::src.
Referenced by DynamicDataLoader::initialize().
reset()
void overmap_connections::reset ()
Definition at line 148 of file overmap_connection.cpp.
 {
     connections.reset();
 }
References anonymous_namespace{overmap_connection.cpp}::connections.
Referenced by DynamicDataLoader::unload_data().