Cataclysm DDA: detail Namespace Reference
detail Namespace Reference
Classes
class is_optional_helper
class is_optional_helper< std::optional< T > >
class local_translation_cache
class local_translation_cache< std::string >
class local_translation_cache< const char * >
Functions
const char * _translate_internal (const char *msg)
std::string _translate_internal (const std::string &msg)
int get_current_language_version ()
local_translation_cache< const char * > get_local_translation_cache (const char *)
local_translation_cache< std::string > get_local_translation_cache (const std::string_view)
template<typename T , typename Error >
T read_from_json_string_common (const std::string_view s, const std::vector< std::pair< std::string, T >> &units, Error &&error)
Function Documentation
_translate_internal() [1/2]
const char* detail::_translate_internal (const char * msg) inline
Definition at line 30 of file translation_cache.h.
 {
     return msg;
 }
Referenced by detail::local_translation_cache< const char * >::operator()(), detail::local_translation_cache< std::string >::operator()(), and translation::translated().
_translate_internal() [2/2]
std::string detail::_translate_internal (const std::string & msg) inline
Definition at line 35 of file translation_cache.h.
 {
     return msg;
 }
get_current_language_version()
int detail::get_current_language_version ()
Definition at line 15 of file translations.cpp.
 {
     return current_language_version;
 }
References current_language_version.
Referenced by cached_recipe_info(), game_menus::inv::compare_items(), inventory_entry::get_entry_cell_cache(), recipe_result_info_cache::get_result_data(), game::inventory_item_menu(), detail::local_translation_cache< const char * >::operator()(), detail::local_translation_cache< std::string >::operator()(), and translation::translated().
get_local_translation_cache() [1/2]
local_translation_cache<const char *> detail::get_local_translation_cache (const char *) inline
Definition at line 102 of file translation_cache.h.
 {
     return local_translation_cache<const char *>();
 }
get_local_translation_cache() [2/2]
local_translation_cache<std::string> detail::get_local_translation_cache (const std::string_view) inline
Definition at line 107 of file translation_cache.h.
 {
     return local_translation_cache<std::string>();
 }
read_from_json_string_common()
template<typename T , typename Error > T detail::read_from_json_string_common (const std::string_view s, const std::vector< std::pair< std::string, T >> & units, Error && error)
Definition at line 1213 of file units.h.
 {
     size_t i = 0;
     // returns whether we are at the end of the string
     const auto skip_spaces = [&]() {
         while( i < s.size() && s[ i ] == ' ' ) {
             ++i;
         }
         return i >= s.size();
     };
     const auto get_unit = [&]() {
         if( skip_spaces() ) {
             error( "invalid quantity string: missing unit", i );
         }
         for( const std::pair<std::string, T> &pair : units ) {
             const std::string &unit = pair.first;
             if( s.size() >= unit.size() + i && s.compare( i, unit.size(), unit ) == 0 ) {
                 i += unit.size();
                 return pair.second;
             }
         }
         error( "invalid quantity string: unknown unit", i );
         // above always throws but lambdas cannot be marked [[noreturn]]
         throw std::string( "Exceptionally impossible" );
     };
     if( skip_spaces() ) {
         error( "invalid quantity string: empty string", i );
         // above always throws but lambdas cannot be marked [[noreturn]]
         throw std::string( "Exceptionally impossible" );
     }
     T result{};
     do {
         int sign_value = +1;
         if( s[ i ] == '-' ) {
             sign_value = -1;
             ++i;
         } else if( s[ i ] == '+' ) {
             ++i;
         }
         if( i >= s.size() || !isdigit( s[ i ] ) ) {
             error( "invalid quantity string: number expected", i );
             // above always throws but lambdas cannot be marked [[noreturn]]
             throw std::string( "Exceptionally impossible" );
         }
         int value = 0;
         for( ; i < s.size() && isdigit( s[ i ] ); ++i ) {
             value = value * 10 + ( s[ i ] - '0' );
         }
         result += sign_value * value * get_unit();
     } while( !skip_spaces() );
     return result;
 }
References error.