Cataclysm DDA: iexamine_helper Namespace Reference
iexamine_helper Namespace Reference
Functions
bool drink_nectar (Character &you)
Consume Nectar.
void handle_harvest (Character &you, const std::string &itemid, bool force_drop)
Spawn an item after harvesting the plant.
Function Documentation
drink_nectar()
bool iexamine_helper::drink_nectar (Character & you)
Consume Nectar.
-15 hunger.
Definition at line 2192 of file iexamine.cpp.
 {
     if( can_drink_nectar( you ) ) {
         add_msg( _( "You drink some nectar." ) );
         item nectar( "nectar", calendar::turn, 1 );
         you.assign_activity( consume_activity_actor( nectar ) );
         return true;
     }
     return false;
 }
References _, add_msg(), Character::assign_activity(), can_drink_nectar(), and calendar::turn.
Referenced by harvest_activity_actor::finish(), and iexamine::flower_dahlia().
handle_harvest()
void iexamine_helper::handle_harvest (Character & you, const std::string & itemid, bool force_drop)
Spawn an item after harvesting the plant.
Definition at line 2207 of file iexamine.cpp.
 {
     item harvest = item( itemid );
     if( harvest.has_temperature() ) {
         harvest.set_item_temperature( get_weather().get_temperature( you.pos() ) );
     }
     if( !force_drop && you.can_pickVolume( harvest, true ) &&
         you.can_pickWeight( harvest, !get_option<bool>( "DANGEROUS_PICKUPS" ) ) ) {
         you.i_add( harvest );
         you.add_msg_if_player( _( "You harvest: %s." ), harvest.tname() );
     } else {
         get_map().add_item_or_charges( you.pos(), harvest );
         you.add_msg_if_player( _( "You harvest and drop: %s." ), harvest.tname() );
     }
 }
References _, map::add_item_or_charges(), Character::add_msg_if_player(), Character::can_pickVolume(), Character::can_pickWeight(), get_map(), get_weather(), harvest, Character::i_add(), and Creature::pos().
Referenced by harvest_activity_actor::finish(), iexamine::flower_cactus(), iexamine::flower_dahlia(), iexamine::flower_marloss(), and iexamine::flower_poppy().