Cataclysm DDA: activity_handlers Namespace Reference
activity_handlers Namespace Reference
Functions
bool resume_for_multi_activities (Character &you)
void generic_game_turn_handler (player_activity *act, Character *you, int morale_bonus, int morale_max_bonus)
void adv_inventory_do_turn (player_activity *act, Character *you)
activity_do_turn functions:
void armor_layers_do_turn (player_activity *act, Character *you)
void atm_do_turn (player_activity *act, Character *you)
void build_do_turn (player_activity *act, Character *you)
void dismember_do_turn (player_activity *act, Character *you)
void chop_trees_do_turn (player_activity *act, Character *you)
void consume_drink_menu_do_turn (player_activity *act, Character *you)
void consume_food_menu_do_turn (player_activity *act, Character *you)
void consume_meds_menu_do_turn (player_activity *act, Character *you)
void eat_menu_do_turn (player_activity *act, Character *you)
void fertilize_plot_do_turn (player_activity *act, Character *you)
void fetch_do_turn (player_activity *act, Character *you)
void fill_liquid_do_turn (player_activity *act, Character *you)
void find_mount_do_turn (player_activity *act, Character *you)
void fish_do_turn (player_activity *act, Character *you)
void game_do_turn (player_activity *act, Character *you)
void generic_game_do_turn (player_activity *act, Character *you)
void hand_crank_do_turn (player_activity *act, Character *you)
void jackhammer_do_turn (player_activity *act, Character *you)
void move_loot_do_turn (player_activity *act, Character *you)
void multiple_butcher_do_turn (player_activity *act, Character *you)
void multiple_chop_planks_do_turn (player_activity *act, Character *you)
void multiple_construction_do_turn (player_activity *act, Character *you)
void multiple_craft_do_turn (player_activity *act, Character *you)
void multiple_dis_do_turn (player_activity *act, Character *you)
void multiple_farm_do_turn (player_activity *act, Character *you)
void multiple_fish_do_turn (player_activity *act, Character *you)
void multiple_read_do_turn (player_activity *act, Character *you)
void multiple_mine_do_turn (player_activity *act, Character *you)
void multiple_mop_do_turn (player_activity *act, Character *you)
void operation_do_turn (player_activity *act, Character *you)
void pickaxe_do_turn (player_activity *act, Character *you)
void pulp_do_turn (player_activity *act, Character *you)
void repair_item_do_turn (player_activity *act, Character *you)
void robot_control_do_turn (player_activity *act, Character *you)
void start_fire_do_turn (player_activity *act, Character *you)
void study_spell_do_turn (player_activity *act, Character *you)
void tidy_up_do_turn (player_activity *act, Character *you)
void travel_do_turn (player_activity *act, Character *you)
void tree_communion_do_turn (player_activity *act, Character *you)
void vehicle_deconstruction_do_turn (player_activity *act, Character *you)
void vehicle_repair_do_turn (player_activity *act, Character *you)
void vibe_do_turn (player_activity *act, Character *you)
void view_recipe_do_turn (player_activity *act, Character *you)
void wait_stamina_do_turn (player_activity *act, Character *you)
void atm_finish (player_activity *act, Character *you)
activity_finish functions:
void butcher_finish (player_activity *act, Character *you)
void eat_menu_finish (player_activity *act, Character *you)
void fish_finish (player_activity *act, Character *you)
void generic_game_finish (player_activity *act, Character *you)
void gunmod_add_finish (player_activity *act, Character *you)
void heat_item_finish (player_activity *act, Character *you)
void jackhammer_finish (player_activity *act, Character *you)
void mend_item_finish (player_activity *act, Character *you)
void operation_finish (player_activity *act, Character *you)
void pickaxe_finish (player_activity *act, Character *you)
void plant_seed_finish (player_activity *act, Character *you)
void pull_creature_finish (player_activity *act, Character *you)
void pulp_finish (player_activity *act, Character *you)
void repair_item_finish (player_activity *act, Character *you)
void robot_control_finish (player_activity *act, Character *you)
void socialize_finish (player_activity *act, Character *you)
void spellcasting_finish (player_activity *act, Character *you)
void start_engines_finish (player_activity *act, Character *you)
void start_fire_finish (player_activity *act, Character *you)
void study_spell_finish (player_activity *act, Character *you)
void teach_finish (player_activity *act, Character *you)
void toolmod_add_finish (player_activity *act, Character *you)
void train_finish (player_activity *act, Character *you)
void vehicle_finish (player_activity *act, Character *you)
void vibe_finish (player_activity *act, Character *you)
void view_recipe_finish (player_activity *act, Character *you)
void wait_finish (player_activity *act, Character *you)
void wait_npc_finish (player_activity *act, Character *you)
void wait_stamina_finish (player_activity *act, Character *you)
void wait_weather_finish (player_activity *act, Character *you)
int move_cost (const item &it, const tripoint_bub_ms &src, const tripoint_bub_ms &dest)
int move_cost_cart (const item &it, const tripoint_bub_ms &src, const tripoint_bub_ms &dest, const units::volume &capacity)
int move_cost_inv (const item &it, const tripoint_bub_ms &src, const tripoint_bub_ms &dest)
Variables
const std::map< activity_id, std::function< void(player_activity *, Character *)> > do_turn_functions
const std::map< activity_id, std::function< void(player_activity *, Character *)> > finish_functions
Function Documentation
adv_inventory_do_turn()
void activity_handlers::adv_inventory_do_turn (player_activity * act, Character * you)
activity_do_turn functions:
Definition at line 2816 of file activity_handlers.cpp.
 {
     you->cancel_activity();
     create_advanced_inv();
 }
References Character::cancel_activity(), and create_advanced_inv().
armor_layers_do_turn()
void activity_handlers::armor_layers_do_turn (player_activity * act, Character * you)
Definition at line 2868 of file activity_handlers.cpp.
 {
     you->cancel_activity();
     you->worn.sort_armor( *you );
 }
References Character::cancel_activity(), outfit::sort_armor(), and Character::worn.
atm_do_turn()
void activity_handlers::atm_do_turn (player_activity * act, Character * you)
Definition at line 2874 of file activity_handlers.cpp.
 {
     iexamine::atm( *you, you->pos() );
 }
References iexamine::atm(), and Creature::pos().
atm_finish()
void activity_handlers::atm_finish (player_activity * act, Character * you)
activity_finish functions:
Definition at line 3452 of file activity_handlers.cpp.
 {
     // ATM sets index to 0 to indicate it's finished.
     if( !act->index ) {
         act->set_to_null();
     }
 }
References act.
build_do_turn()
void activity_handlers::build_do_turn (player_activity * act, Character * you)
Definition at line 3313 of file activity_handlers.cpp.
 {
     map &here = get_map();
     partial_con *pc = here.partial_con_at( here.bub_from_abs( act->placement ) );
     // Maybe the player and the NPC are working on the same construction at the same time
     if( !pc ) {
         if( you->is_npc() ) {
             // if player completes the work while NPC still in activity loop
             you->activity = player_activity();
             you->set_moves( 0 );
         } else {
             you->cancel_activity();
         }
         add_msg( m_info, _( "%s did not find an unfinished construction at the activity spot." ),
                  you->disp_name() );
         return;
     }
     you->set_activity_level( pc->id->activity_level );
     // if you ( or NPC ) are finishing someone else's started construction...
     const construction &built = pc->id.obj();
     if( !you->has_trait( trait_DEBUG_HS ) && !you->meets_skill_requirements( built ) ) {
         add_msg( m_info, _( "%s can't work on this construction anymore." ), you->disp_name() );
         you->cancel_activity();
         if( you->is_npc() ) {
             you->activity = player_activity();
             you->set_moves( 0 );
         }
         return;
     }
     // item_counter represents the percent progress relative to the base batch time
     // stored precise to 5 decimal places ( e.g. 67.32 percent would be stored as 6732000 )
     const int old_counter = pc->counter;
     // Base moves for construction with no speed modifier or assistants
     // Clamp to >= 100 to prevent division by 0 or int overflow on characters with high speed;
     const double base_total_moves = std::max( 100, built.time );
     // Current expected total moves, includes construction speed modifiers and assistants
     const double cur_total_moves = std::max( 100, built.adjusted_time() );
     // Delta progress in moves adjusted for current crafting speed
     const double delta_progress = you->get_moves() * base_total_moves / cur_total_moves;
     // Current progress in moves
     const double current_progress = old_counter * base_total_moves / 10000000.0 +
                                     delta_progress;
     // Current progress as a percent of base_total_moves to 2 decimal places
     pc->counter = std::round( current_progress / base_total_moves * 10000000.0 );
     you->set_moves( 0 );
     pc->id->do_turn_special( here.bub_from_abs( act->placement ), *you );
     pc->counter = std::min( pc->counter, 10000000 );
     // If construction_progress has reached 100% or more
     if( pc->counter >= 10000000 ) {
         // Activity is canceled in complete_construction()
         complete_construction( you->as_character() );
     }
 }
References _, act, Character::activity, construction::activity_level, add_msg(), construction::adjusted_time(), Character::as_character(), map::bub_from_abs(), Character::cancel_activity(), complete_construction(), partial_con::counter, Character::disp_name(), construction::do_turn_special, get_map(), Creature::get_moves(), Character::has_trait(), partial_con::id, Character::is_npc(), m_info, max(), Character::meets_skill_requirements(), min(), int_id< T >::obj(), map::partial_con_at(), round(), Character::set_activity_level(), Creature::set_moves(), construction::time, and trait_DEBUG_HS.
butcher_finish()
void activity_handlers::butcher_finish (player_activity * act, Character * you)
Definition at line 1241 of file activity_handlers.cpp.
 {
     // No targets means we are done
     if( act->targets.empty() ) {
         act->set_to_null();
         resume_for_multi_activities( *you );
         return;
     }
     item_location target = act->targets.back();
     // Corpses can disappear (rezzing!), so check for that
     if( !target || !target->is_corpse() ) {
         you->add_msg_if_player( m_info, _( "There's no corpse to butcher!" ) );
         act->set_to_null();
         return;
     }
     butcher_type action = butcher_type::QUICK;
     if( act->id() == ACT_BUTCHER ) {
         action = butcher_type::QUICK;
     } else if( act->id() == ACT_BUTCHER_FULL ) {
         action = butcher_type::FULL;
     } else if( act->id() == ACT_FIELD_DRESS ) {
         action = butcher_type::FIELD_DRESS;
     } else if( act->id() == ACT_QUARTER ) {
         action = butcher_type::QUARTER;
     } else if( act->id() == ACT_DISSECT ) {
         action = butcher_type::DISSECT;
     } else if( act->id() == ACT_BLEED ) {
         action = butcher_type::BLEED;
     } else if( act->id() == ACT_SKIN ) {
         action = butcher_type::SKIN;
     } else if( act->id() == ACT_DISMEMBER ) {
         action = butcher_type::DISMEMBER;
     }
     // index is a bool that determines if we are ready to start the next target
     if( act->index ) {
         set_up_butchery( *act, *you, action );
         return;
     }
     item &corpse_item = *target;
     const mtype *corpse = corpse_item.get_mtype();
     const field_type_id type_blood = corpse->bloodType();
     const field_type_id type_gib = corpse->gibType();
     // Dump items from the "container" before destroying it.
     // Presumably, the character would be doing this while setting up for butchering.
     corpse_item.spill_contents( target.position() );
     if( action == butcher_type::QUARTER ) {
         butchery_quarter( &corpse_item, *you );
         act->index = true;
         return;
     }
     map &here = get_map();
     if( action == butcher_type::DISMEMBER ) {
         here.add_splatter( type_gib, you->pos(), rng( corpse->size + 2, ( corpse->size + 1 ) * 2 ) );
     }
     // all action types - yields
     if( !butchery_drops_harvest( &corpse_item, *corpse, *you, action ) ) {
         // FATAL FAILURE
         add_msg( m_warning, SNIPPET.random_from_category( "harvest_drop_default_dissect_failed" ).value_or(
                      translation() ).translated() );
         // Remove the target from the map
         target.remove_item();
         act->targets.pop_back();
         here.add_splatter( type_gib, you->pos(), rng( corpse->size + 2, ( corpse->size + 1 ) * 2 ) );
         here.add_splatter( type_blood, you->pos(), rng( corpse->size + 2, ( corpse->size + 1 ) * 2 ) );
         for( int i = 1; i <= corpse->size; i++ ) {
             here.add_splatter_trail( type_gib, you->pos(), random_entry( here.points_in_radius( you->pos(),
                                      corpse->size + 1 ) ) );
             here.add_splatter_trail( type_blood, you->pos(), random_entry( here.points_in_radius( you->pos(),
                                      corpse->size + 1 ) ) );
         }
         // Ready to move on to the next item, if there is one
         act->index = true;
         return;
     }
     //end messages and effects
     switch( action ) {
         case butcher_type::QUARTER:
             break;
         case butcher_type::QUICK:
             add_msg( m_good, SNIPPET.random_from_category( "harvest_drop_default_quick_butcher" ).value_or(
                          translation() ).translated() );
             // Remove the target from the map
             target.remove_item();
             if( !act->targets.empty() ) {
                 act->targets.pop_back();
             }
             break;
         case butcher_type::FULL:
             add_msg( m_good, SNIPPET.random_from_category( "harvest_drop_default_full_butcher" ).value_or(
                          translation() ).translated() );
             // Remove the target from the map
             target.remove_item();
             if( !act->targets.empty() ) {
                 act->targets.pop_back();
             }
             break;
         case butcher_type::FIELD_DRESS: {
             bool success = roll_butchery_dissect( round( you->get_average_skill_level( skill_survival ) ),
                                                   you->dex_cur,
                                                   you->max_quality( qual_BUTCHER, PICKUP_RANGE ) ) > 0;
             add_msg( success ? m_good : m_warning,
                      SNIPPET.random_from_category( success ? "harvest_drop_default_field_dress_success" :
                                                    "harvest_drop_default_field_dress_failed" ).value_or( translation() ).translated() );
             corpse_item.set_flag( success ? flag_FIELD_DRESS : flag_FIELD_DRESS_FAILED );
             here.add_splatter( type_gib, you->pos(), rng( corpse->size + 2, ( corpse->size + 1 ) * 2 ) );
             here.add_splatter( type_blood, you->pos(), rng( corpse->size + 2, ( corpse->size + 1 ) * 2 ) );
             for( int i = 1; i <= corpse->size; i++ ) {
                 here.add_splatter_trail( type_gib, you->pos(), random_entry( here.points_in_radius( you->pos(),
                                          corpse->size + 1 ) ) );
                 here.add_splatter_trail( type_blood, you->pos(), random_entry( here.points_in_radius( you->pos(),
                                          corpse->size + 1 ) ) );
             }
             if( !act->targets.empty() ) {
                 act->targets.pop_back();
             }
             break;
         }
         case butcher_type::SKIN:
             add_msg( m_good, SNIPPET.random_from_category( "harvest_drop_default_skinning" ).value_or(
                          translation() ).translated() );
             corpse_item.set_flag( flag_SKINNED );
             if( !act->targets.empty() ) {
                 act->targets.pop_back();
             }
             break;
         case butcher_type::BLEED:
             add_msg( m_good, SNIPPET.random_from_category( "harvest_drop_default_bleed" ).value_or(
                          translation() ).translated() );
             corpse_item.set_flag( flag_BLED );
             if( !act->targets.empty() ) {
                 act->targets.pop_back();
             }
             break;
         case butcher_type::DISMEMBER:
             add_msg( m_good, SNIPPET.random_from_category( "harvest_drop_default_dismember" ).value_or(
                          translation() ).translated() );
             // Remove the target from the map
             target.remove_item();
             if( !act->targets.empty() ) {
                 act->targets.pop_back();
             }
             break;
         case butcher_type::DISSECT:
             add_msg( m_good, SNIPPET.random_from_category( "harvest_drop_default_dissect_success" ).value_or(
                          translation() ).translated() );
             // Remove the target from the map
             target.remove_item();
             if( !act->targets.empty() ) {
                 act->targets.pop_back();
             }
             break;
         case butcher_type::NUM_TYPES:
             debugmsg( "ERROR: Invalid butcher_type" );
             break;
     }
     you->recoil = MAX_RECOIL;
     get_event_bus().send<event_type::character_butchered_corpse>( you->getID(),
             corpse_item.get_mtype()->id, act->id().str() );
     // Ready to move on to the next item, if there is one (for example if multibutchering)
     act->index = true;
     // if it's mutli-tile butchering, then restart the backlog.
     resume_for_multi_activities( *you );
 }
References _, act, ACT_BLEED, ACT_BUTCHER, ACT_BUTCHER_FULL, ACT_DISMEMBER, ACT_DISSECT, ACT_FIELD_DRESS, ACT_QUARTER, ACT_SKIN, action, add_msg(), Character::add_msg_if_player(), map::add_splatter(), map::add_splatter_trail(), BLEED, butchery_drops_harvest(), butchery_quarter(), character_butchered_corpse, corpse, debugmsg, Character::dex_cur, DISMEMBER, DISSECT, FIELD_DRESS, flag_BLED, flag_FIELD_DRESS, flag_FIELD_DRESS_FAILED, flag_SKINNED, FULL, Character::get_average_skill_level(), get_event_bus(), get_map(), item::get_mtype(), Character::getID(), activity_type::id(), mtype::id, item::is_corpse(), m_good, m_info, m_warning, Character::max_quality(), MAX_RECOIL, NUM_TYPES, PICKUP_RANGE, map::points_in_radius(), Creature::pos(), item_location::position(), qual_BUTCHER, QUARTER, QUICK, random_entry(), snippet_library::random_from_category(), Character::recoil, item_location::remove_item(), resume_for_multi_activities(), rng(), roll_butchery_dissect(), round(), event_bus::send(), item::set_flag(), set_up_butchery(), skill_survival, SKIN, SNIPPET, item::spill_contents(), and string_id< T >::str().
chop_trees_do_turn()
void activity_handlers::chop_trees_do_turn (player_activity * act, Character * you)
Definition at line 3430 of file activity_handlers.cpp.
 {
     generic_multi_activity_handler( *act, *you );
 }
References act, and generic_multi_activity_handler().
consume_drink_menu_do_turn()
void activity_handlers::consume_drink_menu_do_turn (player_activity * act, Character * you)
Definition at line 2751 of file activity_handlers.cpp.
 {
     avatar &player_character = get_avatar();
     item_location loc = game_menus::inv::consume_drink( player_character );
     avatar_action::eat( player_character, loc );
 }
References game_menus::inv::consume_drink(), avatar_action::eat(), and get_avatar().
consume_food_menu_do_turn()
void activity_handlers::consume_food_menu_do_turn (player_activity * act, Character * you)
Definition at line 2744 of file activity_handlers.cpp.
 {
     avatar &player_character = get_avatar();
     item_location loc = game_menus::inv::consume_food( player_character );
     avatar_action::eat( player_character, loc );
 }
References game_menus::inv::consume_food(), avatar_action::eat(), and get_avatar().
consume_meds_menu_do_turn()
void activity_handlers::consume_meds_menu_do_turn (player_activity * act, Character * you)
Definition at line 2758 of file activity_handlers.cpp.
 {
     avatar &player_character = get_avatar();
     avatar_action::eat_or_use( player_character, game_menus::inv::consume_meds( player_character ) );
 }
References game_menus::inv::consume_meds(), avatar_action::eat_or_use(), and get_avatar().
dismember_do_turn()
void activity_handlers::dismember_do_turn (player_activity * act, Character * you)
Definition at line 2975 of file activity_handlers.cpp.
 {
     you->burn_energy_arms( -20 );
 }
References Character::burn_energy_arms().
eat_menu_do_turn()
void activity_handlers::eat_menu_do_turn (player_activity * act, Character * you)
Definition at line 2731 of file activity_handlers.cpp.
 {
     if( !you->is_avatar() ) {
         debugmsg( "Character %s somehow opened the eat menu!  Cancelling their activity to prevent infinite loop",
                   you->name );
         you->cancel_activity();
         return;
     }
     avatar &player_character = get_avatar();
     avatar_action::eat_or_use( player_character, game_menus::inv::consume( player_character ) );
 }
References Character::cancel_activity(), game_menus::inv::consume(), debugmsg, avatar_action::eat_or_use(), get_avatar(), Creature::is_avatar(), and Character::name.
eat_menu_finish()
void activity_handlers::eat_menu_finish (player_activity * act, Character * you)
Definition at line 3460 of file activity_handlers.cpp.
 {
     // Only exists to keep the eat activity alive between turns
 }
fertilize_plot_do_turn()
void activity_handlers::fertilize_plot_do_turn (player_activity * act, Character * you)
Definition at line 3564 of file activity_handlers.cpp.
 {
     itype_id fertilizer;
     auto check_fertilizer = [&]( bool ask_user = true ) -> void {
         if( act->str_values.empty() )
         {
             act->str_values.emplace_back( "" );
         }
         fertilizer = itype_id( act->str_values[0] );
         /* If unspecified, or if we're out of what we used before, ask */
         if( ask_user && ( fertilizer.is_empty() || !you->has_charges( fertilizer, 1 ) ) )
         {
             fertilizer = iexamine::choose_fertilizer( *you, "plant",
                     false /* Don't confirm action with player */ );
             act->str_values[0] = fertilizer.str();
         }
     };
     auto have_fertilizer = [&]() {
         return !fertilizer.is_empty() && you->has_charges( fertilizer, 1 );
     };
     const auto reject_tile = [&]( const tripoint_bub_ms & tile ) {
         check_fertilizer();
         // TODO: fix point types
         ret_val<void> can_fert = iexamine::can_fertilize( *you, tile.raw(), fertilizer );
         return !can_fert.success();
     };
     const auto fertilize = [&]( Character & you, const tripoint_bub_ms & tile ) {
         check_fertilizer();
         if( have_fertilizer() ) {
             // TODO: fix point types
             iexamine::fertilize_plant( you, tile.raw(), fertilizer );
             if( !have_fertilizer() ) {
                 add_msg( m_info, _( "You have run out of %s." ), item::nname( fertilizer ) );
             }
         }
     };
     check_fertilizer();
     if( !have_fertilizer() ) {
         act->set_to_null();
         return;
     }
     perform_zone_activity_turn( you,
                                 zone_type_FARM_PLOT,
                                 reject_tile,
                                 fertilize,
                                 _( "You fertilized every plot you could." ) );
 }
References _, act, add_msg(), iexamine::can_fertilize(), iexamine::choose_fertilizer(), iexamine::fertilize_plant(), Character::has_charges(), string_id< T >::is_empty(), m_info, item::nname(), perform_zone_activity_turn(), string_id< T >::str(), ret_val_common::success(), and zone_type_FARM_PLOT.
fetch_do_turn()
void activity_handlers::fetch_do_turn (player_activity * act, Character * you)
Definition at line 3440 of file activity_handlers.cpp.
 {
     generic_multi_activity_handler( *act, *you );
 }
References act, and generic_multi_activity_handler().
fill_liquid_do_turn()
void activity_handlers::fill_liquid_do_turn (player_activity * act, Character * you)
Definition at line 1423 of file activity_handlers.cpp.
 {
     player_activity &act_ref = *act;
     try {
         // 1. Gather the source item.
         vehicle *source_veh = nullptr;
         const tripoint source_pos = act_ref.coords.at( 0 );
         map &here = get_map();
         map_stack source_stack = here.i_at( source_pos );
         map_stack::iterator on_ground;
         monster *source_mon = nullptr;
         item liquid;
         const liquid_source_type source_type = static_cast<liquid_source_type>( act_ref.values.at( 0 ) );
         int part_num = -1;
         int veh_charges = 0;
         switch( source_type ) {
             case liquid_source_type::VEHICLE:
                 source_veh = veh_pointer_or_null( here.veh_at( source_pos ) );
                 if( source_veh == nullptr ) {
                     throw std::runtime_error( "could not find source vehicle for liquid transfer" );
                 }
                 deserialize_from_string( liquid, act_ref.str_values.at( 0 ) );
                 part_num = static_cast<int>( act_ref.values.at( 1 ) );
                 veh_charges = liquid.charges;
                 break;
             case liquid_source_type::INFINITE_MAP:
                 deserialize_from_string( liquid, act_ref.str_values.at( 0 ) );
                 liquid.charges = item::INFINITE_CHARGES;
                 break;
             case liquid_source_type::MAP_ITEM:
                 if( static_cast<size_t>( act_ref.values.at( 1 ) ) >= source_stack.size() ) {
                     throw std::runtime_error( "could not find source item on ground for liquid transfer" );
                 }
                 on_ground = source_stack.begin();
                 std::advance( on_ground, act_ref.values.at( 1 ) );
                 liquid = *on_ground;
                 break;
             case liquid_source_type::MONSTER:
                 Creature *c = get_creature_tracker().creature_at( source_pos );
                 source_mon = dynamic_cast<monster *>( c );
                 if( source_mon == nullptr ) {
                     debugmsg( "could not find source creature for liquid transfer" );
                     act_ref.set_to_null();
                 }
                 deserialize_from_string( liquid, act_ref.str_values.at( 0 ) );
                 liquid.charges = 1;
                 break;
         }
         static const units::volume volume_per_second = units::from_liter( 4.0F / 6.0F );
         const int charges_per_second = std::max( 1, liquid.charges_per_volume( volume_per_second ) );
         liquid.charges = std::min( charges_per_second, liquid.charges );
         const int original_charges = liquid.charges;
         if( liquid.has_temperature() && units::to_joule_per_gram( liquid.specific_energy ) < 0 ) {
             liquid.set_item_temperature( std::max( get_weather().get_temperature( you->pos() ),
                                                    temperatures::cold ) );
         }
         // 2. Transfer charges.
         const vehicle *veh = nullptr;
         size_t part;
         switch( static_cast<liquid_target_type>( act_ref.values.at( 2 ) ) ) {
             case liquid_target_type::VEHICLE: {
                 const optional_vpart_position vp = here.veh_at( act_ref.coords.at( 1 ) );
                 if( act_ref.values.size() > 4 && vp ) {
                     const vpart_reference vpr( vp->vehicle(), act_ref.values[4] );
                     veh = &vp->vehicle();
                     part = act_ref.values[4];
                     if( source_veh &&
                         source_veh->fuel_left( liquid.typeId(), ( veh ? std::function<bool( const vehicle_part & )> { [&]( const vehicle_part & pa )
                 {
                     return &veh->part( part ) != &pa;
                     }
                                                                                                                     } : return_true<const vehicle_part &> ) ) <= 0 ) {
                         act_ref.set_to_null();
                         return;
                     }
                     you->pour_into( vpr, liquid );
                 } else {
                     throw std::runtime_error( "could not find target vehicle for liquid transfer" );
                 }
                 break;
             }
             case liquid_target_type::CONTAINER:
                 you->pour_into( act_ref.targets.at( 0 ), liquid, true );
                 break;
             case liquid_target_type::MAP:
                 if( iexamine::has_keg( act_ref.coords.at( 1 ) ) ) {
                     iexamine::pour_into_keg( act_ref.coords.at( 1 ), liquid );
                 } else {
                     here.add_item_or_charges( act_ref.coords.at( 1 ), liquid );
                     you->add_msg_if_player( _( "You pour %1$s onto the ground." ), liquid.tname() );
                     liquid.charges = 0;
                 }
                 break;
             case liquid_target_type::MONSTER:
                 liquid.charges = 0;
                 break;
         }
         const int removed_charges = original_charges - liquid.charges;
         if( removed_charges == 0 ) {
             // Nothing has been transferred, target must be full.
             act_ref.set_to_null();
             return;
         }
         // 3. Remove charges from source.
         switch( source_type ) {
             case liquid_source_type::VEHICLE:
                 if( part_num != -1 ) {
                     const vehicle_part &pt = source_veh->part( part_num );
                     if( pt.is_leaking() && !pt.ammo_remaining() ) {
                         act_ref.set_to_null(); // leaky tank spilled while we were transferring
                         return;
                     }
                     source_veh->drain( part_num, removed_charges );
                     liquid.charges = veh_charges - removed_charges;
                     // If there's no liquid left in this tank we're done, otherwise
                     // we need to update our liquid serialization to reflect how
                     // many charges are actually left for the next time we come
                     // around this loop.
                     if( !liquid.charges ) {
                         act_ref.set_to_null();
                     } else {
                         if( act_ref.str_values.empty() ) {
                             act_ref.str_values.emplace_back( );
                         }
                         act_ref.str_values[0] = serialize( liquid );
                     }
                 } else {
                     source_veh->drain( liquid.typeId(), removed_charges, ( veh ? std::function<bool( vehicle_part & )> { [&]( vehicle_part & pa )
                     {
                         return &veh->part( part ) != &pa;
                     }
                                                                                                                        } : return_true<vehicle_part &> ) );
                 }
                 break;
             case liquid_source_type::MAP_ITEM:
                 on_ground->charges -= removed_charges;
                 if( on_ground->charges <= 0 ) {
                     source_stack.erase( on_ground );
                     if( here.ter( source_pos )->has_examine( iexamine::gaspump ) ) {
                         add_msg( _( "With a clang and a shudder, the %s pump goes silent." ),
                                  liquid.type_name( 1 ) );
                     } else if( here.furn( source_pos )->has_examine( iexamine::fvat_full ) ) {
                         add_msg( _( "You squeeze the last drops of %s from the vat." ),
                                  liquid.type_name( 1 ) );
                         map_stack items_here = here.i_at( source_pos );
                         if( items_here.empty() ) {
                             if( here.furn( source_pos ) == furn_f_fvat_wood_full ) {
                                 here.furn_set( source_pos, furn_f_fvat_wood_empty );
                             } else {
                                 here.furn_set( source_pos, furn_f_fvat_empty );
                             }
                         }
                     } else if( here.furn( source_pos )->has_examine( iexamine::compost_full ) ) {
                         add_msg( _( "You squeeze the last drops of %s from the tank." ),
                                  liquid.type_name( 1 ) );
                         map_stack items_here = here.i_at( source_pos );
                         if( items_here.empty() ) {
                             if( here.furn( source_pos ) == furn_f_compost_full ) {
                                 here.furn_set( source_pos, furn_f_compost_empty );
                             }
                         }
                     }
                     act_ref.set_to_null();
                 }
                 break;
             case liquid_source_type::INFINITE_MAP:
                 // nothing, the liquid source is infinite
                 break;
             case liquid_source_type::MONSTER:
                 // liquid source charges handled in monexamine::milk_source
                 if( liquid.charges == 0 ) {
                     act_ref.set_to_null();
                 }
                 break;
         }
         if( removed_charges < original_charges ) {
             // Transferred less than the available charges -> target must be full
             act_ref.set_to_null();
         }
     } catch( const std::runtime_error &err ) {
         debugmsg( "error in activity data: \"%s\"", err.what() );
         act_ref.set_to_null();
         return;
     }
 }
References _, act, map::add_item_or_charges(), add_msg(), Character::add_msg_if_player(), vehicle_part::ammo_remaining(), item_stack::begin(), c, item::charges, item::charges_per_volume(), temperatures::cold, iexamine::compost_full(), CONTAINER, player_activity::coords, creature_tracker::creature_at(), debugmsg, deserialize_from_string(), item_stack::empty(), units::from_liter(), vehicle::fuel_left(), furn_f_compost_empty, furn_f_compost_full, furn_f_fvat_empty, furn_f_fvat_wood_empty, furn_f_fvat_wood_full, iexamine::fvat_full(), iexamine::gaspump(), get_creature_tracker(), get_map(), get_weather(), iexamine::has_keg(), item::has_temperature(), map::i_at(), item::INFINITE_CHARGES, INFINITE_MAP, vehicle_part::is_leaking(), MAP, MAP_ITEM, max(), min(), MONSTER, Creature::pos(), Character::pour_into(), iexamine::pour_into_keg(), serialize(), item::set_item_temperature(), player_activity::set_to_null(), item_stack::size(), item::specific_energy, player_activity::str_values, player_activity::targets, item::tname(), units::to_joule_per_gram(), item::typeId(), player_activity::values, map::veh_at(), veh_pointer_or_null(), and VEHICLE.
find_mount_do_turn()
void activity_handlers::find_mount_do_turn (player_activity * act, Character * you)
Definition at line 2992 of file activity_handlers.cpp.
 {
     //npc only activity
     if( you->is_avatar() ) {
         act->set_to_null();
         return;
     }
     npc &guy = dynamic_cast<npc &>( *you );
     auto strong_monster = guy.chosen_mount.lock();
     monster *mon = strong_monster.get();
     if( !mon ) {
         act->set_to_null();
         guy.revert_after_activity();
         return;
     }
     if( rl_dist( guy.pos(), mon->pos() ) <= 1 ) {
         if( mon->has_effect( effect_controlled ) ) {
             mon->remove_effect( effect_controlled );
         }
         if( you->can_mount( *mon ) ) {
             act->set_to_null();
             guy.revert_after_activity();
             guy.chosen_mount = weak_ptr_fast<monster>();
             you->mount_creature( *mon );
         } else {
             act->set_to_null();
             guy.revert_after_activity();
             return;
         }
     } else {
         const std::vector<tripoint_bub_ms> route =
             route_adjacent( *you, guy.chosen_mount.lock()->pos_bub() );
         if( route.empty() ) {
             act->set_to_null();
             guy.revert_after_activity();
             mon->remove_effect( effect_controlled );
             return;
         } else {
             you->activity = player_activity();
             mon->add_effect( effect_controlled, 40_turns );
             you->set_destination( route, player_activity( ACT_FIND_MOUNT ) );
         }
     }
 }
References act, ACT_FIND_MOUNT, Character::activity, Creature::add_effect(), Character::can_mount(), npc::chosen_mount, effect_controlled, Creature::has_effect(), Creature::is_avatar(), Character::mount_creature(), Creature::pos(), Creature::remove_effect(), npc::revert_after_activity(), rl_dist(), route_adjacent(), and Character::set_destination().
fish_do_turn()
void activity_handlers::fish_do_turn (player_activity * act, Character * you)
Definition at line 2910 of file activity_handlers.cpp.
 {
     item &it = *act->targets.front();
     float fish_chance = 1.0f;
     float survival_skill = you->get_skill_level( skill_survival );
     switch( it.get_quality( qual_FISHING_ROD ) ) {
         case 1:
             survival_skill += dice( 1, 6 );
             break;
         case 2:
             // Much better chances with a good fishing implement.
             survival_skill += dice( 4, 9 );
             survival_skill *= 2;
             break;
         default:
             debugmsg( "ERROR: Invalid FISHING_ROD tool quality on %s", item::nname( it.typeId() ) );
             break;
     }
     std::vector<monster *> fishables = g->get_fishable_monsters( act->coord_set );
     // Fish are always there, even if it doesn't seem like they are visible!
     if( fishables.empty() ) {
         fish_chance += survival_skill / 2;
     } else {
         // if they are visible however, it implies a larger population
         for( monster *elem : fishables ) {
             fish_chance += elem->fish_population;
         }
         fish_chance += survival_skill;
     }
     // no matter the population of fish, your skill and tool limits the ease of catching.
     fish_chance = std::min( survival_skill * 10, fish_chance );
     if( x_in_y( fish_chance, 600000 ) ) {
         you->add_msg_if_player( m_good, _( "You feel a tug on your line!" ) );
         rod_fish( you, fishables );
     }
     if( calendar::once_every( 60_minutes ) ) {
         you->practice( skill_survival, rng( 1, 3 ) );
     }
 }
References _, act, Character::add_msg_if_player(), debugmsg, dice(), g, item::get_quality(), Character::get_skill_level(), m_good, min(), item::nname(), calendar::once_every(), Character::practice(), qual_FISHING_ROD, rng(), rod_fish(), skill_survival, item::typeId(), and x_in_y().
fish_finish()
void activity_handlers::fish_finish (player_activity * act, Character * you)
Definition at line 2951 of file activity_handlers.cpp.
 {
     act->set_to_null();
     you->add_msg_if_player( m_info, _( "You finish fishing" ) );
     if( !you->backlog.empty() && you->backlog.front().id() == ACT_MULTIPLE_FISH ) {
         you->backlog.clear();
         you->assign_activity( ACT_TIDY_UP );
     }
 }
References _, act, ACT_MULTIPLE_FISH, ACT_TIDY_UP, Character::add_msg_if_player(), Character::assign_activity(), Character::backlog, and m_info.
game_do_turn()
void activity_handlers::game_do_turn (player_activity * act, Character * you)
Definition at line 1674 of file activity_handlers.cpp.
 {
     generic_game_turn_handler( act, you, 1, 100 );
 }
References act, and generic_game_turn_handler().
generic_game_do_turn()
void activity_handlers::generic_game_do_turn (player_activity * act, Character * you)
Definition at line 1669 of file activity_handlers.cpp.
 {
     generic_game_turn_handler( act, you, 4, 60 );
 }
References act, and generic_game_turn_handler().
generic_game_finish()
void activity_handlers::generic_game_finish (player_activity * act, Character * you)
Definition at line 1648 of file activity_handlers.cpp.
 {
     // Apply small bonus with diminishing returns for playing with friends
     if( act->index > 0 && act->name.find( "with friends" ) != std::string::npos ) {
         float mod = 1.f;
         float acc = 0.4f;
         for( int i = act->index; i > 0; i-- ) {
             mod += acc;
             acc *= acc;
         }
         if( !act->values.empty() && act->values[0] == you->getID().get_value() ) {
             // A winner is you! Feel more happy!
             mod *= 1.5f;
             you->add_msg_if_player( m_good, _( "You won!" ) );
             you->add_msg_if_npc( m_good, _( "<npcname> won!" ) );
         }
         you->add_morale( MORALE_GAME, 4 * mod );
     }
     act->set_to_null();
 }
References _, act, Character::add_morale(), Creature::add_msg_if_npc(), Character::add_msg_if_player(), character_id::get_value(), Character::getID(), m_good, and MORALE_GAME.
generic_game_turn_handler()
void activity_handlers::generic_game_turn_handler (player_activity * act, Character * you, int morale_bonus, int morale_max_bonus)
Definition at line 1617 of file activity_handlers.cpp.
 {
     // Consume battery charges for every minute spent playing
     if( calendar::once_every( 1_minutes ) ) {
         if( !act->targets.empty() ) {
             item &game_item = *act->targets.front();
             int req = game_item.ammo_required();
             bool fail = req > 0 && game_item.ammo_consume( req, tripoint_zero, you ) == 0;
             if( fail ) {
                 act->moves_left = 0;
                 if( you->is_avatar() ) {
                     add_msg( m_info, _( "The %s runs out of batteries." ), game_item.tname() );
                 }
                 return;
             }
         }
         if( act->index > 0 && act->name.find( "with friends" ) != std::string::npos ) {
             // 1 friend -> x1.2,  2 friends -> x1.4,  3 friends -> x1.6  ...
             float mod = std::sqrt( ( act->index * 0.5f ) + 0.5f ) + 0.2f;
             morale_bonus = std::ceil( morale_bonus * mod );
             // half mult for max bonus
             mod = 1.f + ( mod - 1.f ) * 0.5f;
             morale_max_bonus *= mod;
         }
         // Playing alone - 1 points/min, almost 2 hours to fill
         you->add_morale( MORALE_GAME, morale_bonus, morale_max_bonus );
     }
 }
References _, act, Character::add_morale(), add_msg(), item::ammo_consume(), item::ammo_required(), ceil(), Creature::is_avatar(), m_info, MORALE_GAME, calendar::once_every(), sqrt(), item::tname(), and tripoint_zero.
Referenced by game_do_turn(), and generic_game_do_turn().
gunmod_add_finish()
void activity_handlers::gunmod_add_finish (player_activity * act, Character * you)
hand_crank_do_turn()
void activity_handlers::hand_crank_do_turn (player_activity * act, Character * you)
Definition at line 2118 of file activity_handlers.cpp.
 {
     // Hand-crank chargers seem to range from 2 watt (very common easily verified)
     // to 10 watt (suspicious claims from some manufacturers) sustained output.
     // It takes 2.4 minutes to produce 1kj at just slightly under 7 watts (25 kj per hour)
     // time-based instead of speed based because it's a sustained activity
     item &hand_crank_item = *act->targets.front();
     int time_to_crank = to_seconds<int>( 144_seconds );
     // Modify for weariness
     time_to_crank /= you->exertion_adjusted_move_multiplier( act->exertion_level() );
     if( calendar::once_every( time_duration::from_seconds( time_to_crank ) ) ) {
         if( hand_crank_item.ammo_capacity( ammo_battery ) > hand_crank_item.ammo_remaining() ) {
             hand_crank_item.ammo_set( itype_battery, hand_crank_item.ammo_remaining() + 1 );
         } else {
             act->moves_left = 0;
             add_msg( m_info, _( "You've charged the battery completely." ) );
         }
     }
     if( you->get_sleepiness() >= sleepiness_levels::DEAD_TIRED ) {
         act->moves_left = 0;
         add_msg( m_info, _( "You're too exhausted to keep cranking." ) );
     }
 }
References _, act, add_msg(), ammo_battery, item::ammo_capacity(), item::ammo_remaining(), item::ammo_set(), DEAD_TIRED, Character::exertion_adjusted_move_multiplier(), activity_type::exertion_level(), time_duration::from_seconds(), Character::get_sleepiness(), itype_battery, m_info, and calendar::once_every().
heat_item_finish()
void activity_handlers::heat_item_finish (player_activity * act, Character * you)
Definition at line 2608 of file activity_handlers.cpp.
 {
     act->set_to_null();
     if( act->targets.size() != 1 ) {
         debugmsg( "invalid arguments to ACT_HEATING" );
         return;
     }
     item_location &loc = act->targets[ 0 ];
     item *const heat = loc.get_item();
     if( heat == nullptr ) {
         return;
     }
     if( !heat->has_temperature() ) {
         debugmsg( "item %s is not heatable", heat->typeId().str() );
         return;
     }
     item &target = *heat;
     if( target.has_own_flag( flag_FROZEN ) ) {
         target.apply_freezerburn();
         if( target.has_flag( flag_EATEN_COLD ) ) {
             target.cold_up();
             you->add_msg_if_player( m_info,
                                     _( "You defrost the food, but don't heat it up, since you enjoy it cold." ) );
         } else {
             target.heat_up();
             you->add_msg_if_player( m_info, _( "You defrost and heat up the food." ) );
         }
     } else {
         target.heat_up();
         you->add_msg_if_player( m_info, _( "You heat up the food." ) );
     }
 }
References _, act, Character::add_msg_if_player(), item::apply_freezerburn(), item::cold_up(), debugmsg, flag_EATEN_COLD, flag_FROZEN, item_location::get_item(), item::has_flag(), item::has_own_flag(), item::has_temperature(), item::heat_up(), m_info, string_id< T >::str(), and item::typeId().
jackhammer_do_turn()
void activity_handlers::jackhammer_do_turn (player_activity * act, Character * you)
Definition at line 3470 of file activity_handlers.cpp.
 {
     map &here = get_map();
     sfx::play_activity_sound( "tool", "jackhammer",
                               sfx::get_heard_volume( here.getlocal( act->placement ) ) );
     if( calendar::once_every( 1_minutes ) ) {
         sounds::sound( here.getlocal( act->placement ), 15, sounds::sound_t::destructive_activity,
                        //~ Sound of a jackhammer at work!
                        _( "TATATATATATATAT!" ) );
     }
 }
References _, act, sounds::destructive_activity, sfx::get_heard_volume(), get_map(), map::getlocal(), calendar::once_every(), sfx::play_activity_sound(), and sounds::sound().
jackhammer_finish()
void activity_handlers::jackhammer_finish (player_activity * act, Character * you)
Definition at line 3482 of file activity_handlers.cpp.
 {
     map &here = get_map();
     const tripoint &pos = here.getlocal( act->placement );
     here.destroy( pos, true );
     you->add_msg_player_or_npc( m_good,
                                 _( "You finish drilling." ),
                                 _( "<npcname> finishes drilling." ) );
     act->set_to_null();
     if( !act->targets.empty() ) {
         item &it = *act->targets.front();
         it.ammo_consume( it.ammo_required(), tripoint_zero, you );
     } else {
         debugmsg( "jackhammer activity targets empty" );
     }
     if( resume_for_multi_activities( *you ) ) {
         for( item &elem : here.i_at( pos ) ) {
             elem.set_var( "activity_var", you->name );
         }
     }
 }
References _, act, Character::add_msg_player_or_npc(), item::ammo_consume(), item::ammo_required(), debugmsg, map::destroy(), get_map(), map::getlocal(), map::i_at(), m_good, Character::name, math_opers::pos(), resume_for_multi_activities(), and tripoint_zero.
mend_item_finish()
void activity_handlers::mend_item_finish (player_activity * act, Character * you)
Definition at line 2641 of file activity_handlers.cpp.
 {
     act->set_to_null();
     if( act->targets.size() != 1 ) {
         debugmsg( "invalid arguments to ACT_MEND_ITEM" );
         return;
     }
     if( !act->targets[0] ) {
         debugmsg( "lost targets[0] item location for ACT_MEND_ITEM" );
         return;
     }
     item &target = *act->targets[0];
     const fault_id fault_id( act->name );
     if( target.faults.count( fault_id ) == 0 ) {
         debugmsg( "item %s does not have fault %s", target.tname(), fault_id.str() );
         return;
     }
     if( act->str_values.empty() ) {
         debugmsg( "missing fault_fix_id for ACT_MEND_ITEM." );
         return;
     }
     const fault_fix_id fix_id( act->str_values[0] );
     if( !fix_id.is_valid() ) {
         debugmsg( "invalid fault_fix_id '%s' for ACT_MEND_ITEM.", fix_id.str() );
         return;
     }
     const fault_fix &fix = *fix_id;
     const requirement_data &reqs = fix.get_requirements();
     const inventory &inv = you->crafting_inventory();
     if( !reqs.can_make_with_inventory( inv, is_crafting_component ) ) {
         add_msg( m_info, _( "You are currently unable to mend the %s." ), target.tname() );
         return;
     }
     for( const auto &e : reqs.get_components() ) {
         you->consume_items( e );
     }
     for( const auto &e : reqs.get_tools() ) {
         you->consume_tools( e );
     }
     you->invalidate_crafting_inventory();
     for( const ::fault_id &id : fix.faults_removed ) {
         target.faults.erase( id );
     }
     for( const ::fault_id &id : fix.faults_added ) {
         target.faults.insert( id );
     }
     for( const auto &[var_name, var_value] : fix.set_variables ) {
         target.set_var( var_name, var_value );
     }
     const std::string start_durability = target.durability_indicator( true );
     if( fix.mod_damage ) {
         target.mod_damage( fix.mod_damage );
     }
     if( fix.mod_degradation ) {
         target.set_degradation( target.degradation() + fix.mod_degradation );
     }
     for( const auto &[skill_id, level] : fix.skills ) {
         you->practice( skill_id, 10, static_cast<int>( level * 1.25 ) );
     }
     for( const auto &[proficiency_id, mult] : fix.time_save_profs ) {
         you->practice_proficiency( proficiency_id, fix.time );
     }
     add_msg( m_good, fix.success_msg.translated(), target.tname( 1, false ),
              start_durability, target.durability_indicator( true ) );
 }
References _, act, add_msg(), requirement_data::can_make_with_inventory(), Character::consume_items(), Character::consume_tools(), Character::crafting_inventory(), debugmsg, item::degradation(), item::durability_indicator(), item::faults, fault_fix::faults_added, fault_fix::faults_removed, requirement_data::get_components(), fault_fix::get_requirements(), requirement_data::get_tools(), Character::invalidate_crafting_inventory(), is_crafting_component(), string_id< T >::is_valid(), m_good, m_info, fault_fix::mod_damage, item::mod_damage(), fault_fix::mod_degradation, Character::practice(), Character::practice_proficiency(), item::set_degradation(), item::set_var(), fault_fix::set_variables, fault_fix::skills, string_id< T >::str(), fault_fix::success_msg, fault_fix::time, fault_fix::time_save_profs, item::tname(), and translation::translated().
move_cost()
int activity_handlers::move_cost (const item & it, const tripoint_bub_ms & src, const tripoint_bub_ms & dest)
Definition at line 538 of file activity_item_handling.cpp.
 {
     avatar &player_character = get_avatar();
     if( player_character.get_grab_type() == object_type::VEHICLE ) {
         const tripoint cart_position = player_character.pos() + player_character.grab_point;
         if( const std::optional<vpart_reference> ovp = get_map().veh_at( cart_position ).cargo() ) {
             return move_cost_cart( it, src, dest, ovp->items().free_volume() );
         }
     }
     return move_cost_inv( it, src, dest );
 }
References get_avatar(), avatar::get_grab_type(), get_map(), Character::grab_point, move_cost_cart(), move_cost_inv(), Creature::pos(), and VEHICLE.
Referenced by move_cost_cart(), move_cost_inv(), and move_item().
move_cost_cart()
int activity_handlers::move_cost_cart (const item & it, const tripoint_bub_ms & src, const tripoint_bub_ms & dest, const units::volume & capacity)
Definition at line 509 of file activity_item_handling.cpp.
 {
     // to prevent potentially ridiculous number
     const int MAX_COST = 500;
     // cost to move item into the cart
     const int pickup_cost = Pickup::cost_to_move_item( get_player_character(), it );
     // cost to move item out of the cart
     const int drop_cost = pickup_cost;
     // typical flat ground move cost
     const int mc_per_tile = 100;
     // only free cart capacity
     const int cart_capacity = units::to_milliliter( capacity );
     const int item_volume = units::to_milliliter( it.volume() );
     const double fr = get_capacity_fraction( cart_capacity, item_volume );
     // approximation of movement cost between source and destination
     const int move_cost = mc_per_tile * rl_dist( src, dest ) * fr;
     return std::min( pickup_cost + drop_cost + move_cost, MAX_COST );
 }
References Pickup::cost_to_move_item(), get_capacity_fraction(), get_player_character(), min(), move_cost(), rl_dist(), units::to_milliliter(), and item::volume().
Referenced by move_cost().
move_cost_inv()
int activity_handlers::move_cost_inv (const item & it, const tripoint_bub_ms & src, const tripoint_bub_ms & dest)
Definition at line 475 of file activity_item_handling.cpp.
 {
     // to prevent potentially ridiculous number
     const int MAX_COST = 500;
     // it seems that pickup cost is flat 100
     // in function pick_one_up, variable moves_taken has initial value of 100
     // and never changes until it is finally used in function
     // remove_from_map_or_vehicle
     const int pickup_cost = 100;
     // drop cost for non-tumbling items (from inventory overload) is also flat 100
     // according to convert_to_items (it does contain todo to use calculated costs)
     const int drop_cost = 100;
     // typical flat ground move cost
     const int mc_per_tile = 100;
     Character &player_character = get_player_character();
     // only free inventory capacity
     const int inventory_capacity = units::to_milliliter( player_character.volume_capacity() -
                                    player_character.volume_carried() );
     const int item_volume = units::to_milliliter( it.volume() );
     const double fr = get_capacity_fraction( inventory_capacity, item_volume );
     // approximation of movement cost between source and destination
     const int move_cost = mc_per_tile * rl_dist( src, dest ) * fr;
     return std::min( pickup_cost + drop_cost + move_cost, MAX_COST );
 }
References get_capacity_fraction(), get_player_character(), min(), move_cost(), rl_dist(), units::to_milliliter(), item::volume(), Character::volume_capacity(), and Character::volume_carried().
Referenced by move_cost().
move_loot_do_turn()
void activity_handlers::move_loot_do_turn (player_activity * act, Character * you)
Definition at line 2811 of file activity_handlers.cpp.
 {
     activity_on_turn_move_loot( *act, *you );
 }
References act, and activity_on_turn_move_loot().
multiple_butcher_do_turn()
void activity_handlers::multiple_butcher_do_turn (player_activity * act, Character * you)
Definition at line 3400 of file activity_handlers.cpp.
 {
     generic_multi_activity_handler( *act, *you );
 }
References act, and generic_multi_activity_handler().
multiple_chop_planks_do_turn()
void activity_handlers::multiple_chop_planks_do_turn (player_activity * act, Character * you)
Definition at line 3395 of file activity_handlers.cpp.
 {
     generic_multi_activity_handler( *act, *you );
 }
References act, and generic_multi_activity_handler().
multiple_construction_do_turn()
void activity_handlers::multiple_construction_do_turn (player_activity * act, Character * you)
Definition at line 3380 of file activity_handlers.cpp.
 {
     generic_multi_activity_handler( *act, *you );
 }
References act, and generic_multi_activity_handler().
multiple_craft_do_turn()
void activity_handlers::multiple_craft_do_turn (player_activity * act, Character * you)
Definition at line 3405 of file activity_handlers.cpp.
 {
     generic_multi_activity_handler( *act, *you );
 }
References act, and generic_multi_activity_handler().
multiple_dis_do_turn()
void activity_handlers::multiple_dis_do_turn (player_activity * act, Character * you)
Definition at line 3410 of file activity_handlers.cpp.
 {
     generic_multi_activity_handler( *act, *you );
 }
References act, and generic_multi_activity_handler().
multiple_farm_do_turn()
void activity_handlers::multiple_farm_do_turn (player_activity * act, Character * you)
Definition at line 3435 of file activity_handlers.cpp.
 {
     generic_multi_activity_handler( *act, *you );
 }
References act, and generic_multi_activity_handler().
multiple_fish_do_turn()
void activity_handlers::multiple_fish_do_turn (player_activity * act, Character * you)
Definition at line 3375 of file activity_handlers.cpp.
 {
     generic_multi_activity_handler( *act, *you );
 }
References act, and generic_multi_activity_handler().
multiple_mine_do_turn()
void activity_handlers::multiple_mine_do_turn (player_activity * act, Character * you)
Definition at line 3385 of file activity_handlers.cpp.
 {
     generic_multi_activity_handler( *act, *you );
 }
References act, and generic_multi_activity_handler().
multiple_mop_do_turn()
void activity_handlers::multiple_mop_do_turn (player_activity * act, Character * you)
Definition at line 3390 of file activity_handlers.cpp.
 {
     generic_multi_activity_handler( *act, *you );
 }
References act, and generic_multi_activity_handler().
multiple_read_do_turn()
void activity_handlers::multiple_read_do_turn (player_activity * act, Character * you)
Definition at line 3415 of file activity_handlers.cpp.
 {
     generic_multi_activity_handler( *act, *you );
 }
References act, and generic_multi_activity_handler().
operation_do_turn()
void activity_handlers::operation_do_turn (player_activity * act, Character * you)
values[0]: Difficulty
values[1]: success
values[2]: bionic UID when uninstalling
values[3]: pl_skill
str_values[0]: install/uninstall
str_values[1]: bionic_id when installing
str_values[2]: installer_name
str_values[3]: bool autodoc
Definition at line 3081 of file activity_handlers.cpp.
 {
     /**
     - values[0]: Difficulty
     - values[1]: success
     - values[2]: bionic UID when uninstalling
     - values[3]: pl_skill
     - str_values[0]: install/uninstall
     - str_values[1]: bionic_id when installing
     - str_values[2]: installer_name
     - str_values[3]: bool autodoc
     */
     enum operation_values_ids {
         operation_type = 0,
         cbm_id = 1,
         installer_name = 2,
         is_autodoc = 3
     };
     const bionic_id bid( act->str_values[cbm_id] );
     const bool autodoc = act->str_values[is_autodoc] == "true";
     Character &player_character = get_player_character();
     const bool u_see = player_character.sees( you->pos() ) &&
                        ( !player_character.has_effect( effect_narcosis ) ||
                          player_character.has_bionic( bio_painkiller ) ||
                          player_character.has_flag( json_flag_PAIN_IMMUNE ) );
     const int difficulty = act->values.front();
     const std::vector<bodypart_id> bps = get_occupied_bodyparts( bid );
     const time_duration half_op_duration = difficulty * 10_minutes;
     const time_duration message_freq = difficulty * 2_minutes;
     time_duration time_left = time_duration::from_moves( act->moves_left );
     map &here = get_map();
     if( autodoc && here.inbounds( you->pos() ) ) {
         const std::list<tripoint> autodocs = here.find_furnitures_with_flag_in_radius( you->pos(), 1,
                                              ter_furn_flag::TFLAG_AUTODOC );
         if( !here.has_flag_furn( ter_furn_flag::TFLAG_AUTODOC_COUCH, you->pos() ) || autodocs.empty() ) {
             you->remove_effect( effect_under_operation );
             act->set_to_null();
             if( u_see ) {
                 add_msg( m_bad, _( "The Autodoc suffers a catastrophic failure." ) );
                 you->add_msg_player_or_npc( m_bad,
                                             _( "The Autodoc's failure damages you greatly." ),
                                             _( "The Autodoc's failure damages <npcname> greatly." ) );
             }
             if( !bps.empty() ) {
                 for( const bodypart_id &bp : bps ) {
                     you->add_effect( effect_bleed,  1_minutes * difficulty, bp, true, 1 );
                     you->apply_damage( nullptr, bp, 20 * difficulty );
                     if( u_see ) {
                         you->add_msg_player_or_npc( m_bad, _( "Your %s is ripped open." ),
                                                     _( "<npcname>'s %s is ripped open." ), body_part_name_accusative( bp ) );
                     }
                     if( bp == bodypart_id( "eyes" ) ) {
                         you->add_effect( effect_blind, 1_hours );
                     }
                 }
             } else {
                 you->add_effect( effect_bleed,  1_minutes * difficulty, bodypart_str_id::NULL_ID(), true, 1 );
                 you->apply_damage( nullptr, bodypart_id( "torso" ), 20 * difficulty );
             }
         }
     }
     if( time_left > half_op_duration ) {
         if( !bps.empty() ) {
             for( const bodypart_id &bp : bps ) {
                 if( calendar::once_every( message_freq ) && u_see && autodoc ) {
                     you->add_msg_player_or_npc( m_info,
                                                 _( "The Autodoc is meticulously cutting your %s open." ),
                                                 _( "The Autodoc is meticulously cutting <npcname>'s %s open." ),
                                                 body_part_name_accusative( bp ) );
                 }
             }
         } else {
             if( calendar::once_every( message_freq ) && u_see ) {
                 you->add_msg_player_or_npc( m_info,
                                             _( "The Autodoc is meticulously cutting you open." ),
                                             _( "The Autodoc is meticulously cutting <npcname> open." ) );
             }
         }
     } else if( time_left == half_op_duration ) {
         if( act->str_values[operation_type] == "uninstall" ) {
             if( u_see && autodoc ) {
                 add_msg( m_info, _( "The Autodoc attempts to carefully extract the bionic." ) );
             }
             if( std::optional<bionic *> bio = you->find_bionic_by_uid( act->values[2] ) ) {
                 you->perform_uninstall( **bio, act->values[0], act->values[1], act->values[3] );
             } else {
                 debugmsg( _( "Tried to uninstall bionic with UID %s, but you don't have this bionic installed." ),
                           act->values[2] );
                 you->remove_effect( effect_under_operation );
                 act->set_to_null();
             }
         } else {
             if( u_see && autodoc ) {
                 add_msg( m_info, _( "The Autodoc attempts to carefully insert the bionic." ) );
             }
             if( bid.is_valid() ) {
                 const bionic_id upbid = bid->upgraded_bionic;
                 // TODO: Let the user pick bionic to upgrade if multiple candidates exist
                 bionic_uid upbio_uid = 0;
                 if( std::optional<bionic *> bio = you->find_bionic_by_type( upbid ) ) {
                     upbio_uid = ( *bio )->get_uid();
                 }
                 you->perform_install( bid, upbio_uid, act->values[0], act->values[1], act->values[3],
                                       act->str_values[installer_name], bid->canceled_mutations, you->pos() );
             } else {
                 debugmsg( _( "%s is no a valid bionic_id" ), bid.c_str() );
                 you->remove_effect( effect_under_operation );
                 act->set_to_null();
             }
         }
     } else if( act->values[1] > 0 ) {
         if( !bps.empty() ) {
             for( const bodypart_id &bp : bps ) {
                 if( calendar::once_every( message_freq ) && u_see && autodoc ) {
                     you->add_msg_player_or_npc( m_info,
                                                 _( "The Autodoc is stitching your %s back up." ),
                                                 _( "The Autodoc is stitching <npcname>'s %s back up." ),
                                                 body_part_name_accusative( bp ) );
                 }
             }
         } else {
             if( calendar::once_every( message_freq ) && u_see && autodoc ) {
                 you->add_msg_player_or_npc( m_info,
                                             _( "The Autodoc is stitching you back up." ),
                                             _( "The Autodoc is stitching <npcname> back up." ) );
             }
         }
     } else {
         if( calendar::once_every( message_freq ) && u_see && autodoc ) {
             you->add_msg_player_or_npc( m_bad,
                                         _( "The Autodoc is moving erratically through the rest of its program, not actually stitching your wounds." ),
                                         _( "The Autodoc is moving erratically through the rest of its program, not actually stitching <npcname>'s wounds." ) );
         }
     }
     // Makes sure NPC is still under anesthesia
     if( you->has_effect( effect_narcosis ) ) {
         const time_duration remaining_time = you->get_effect_dur( effect_narcosis );
         if( remaining_time < time_left ) {
             const time_duration top_off_time = time_left - remaining_time;
             you->add_effect( effect_narcosis, top_off_time );
             you->add_effect( effect_sleep, top_off_time );
         }
     } else {
         you->add_effect( effect_narcosis, time_left );
         you->add_effect( effect_sleep, time_left );
     }
 }
References _, act, Creature::add_effect(), add_msg(), Character::add_msg_player_or_npc(), Character::apply_damage(), iexamine::autodoc(), bio_painkiller, body_part_name_accusative(), bp, string_id< T >::c_str(), bionic_data::canceled_mutations, debugmsg, effect_bleed, effect_blind, effect_narcosis, effect_sleep, effect_under_operation, Character::find_bionic_by_type(), Character::find_bionic_by_uid(), map::find_furnitures_with_flag_in_radius(), time_duration::from_moves(), Creature::get_effect_dur(), get_map(), get_occupied_bodyparts(), get_player_character(), Character::has_bionic(), Creature::has_effect(), Character::has_flag(), map::has_flag_furn(), map::inbounds(), string_id< T >::is_valid(), json_flag_PAIN_IMMUNE, m_bad, m_info, string_id< body_part_type >::NULL_ID(), calendar::once_every(), Character::perform_install(), Character::perform_uninstall(), Creature::pos(), Creature::remove_effect(), Character::sees(), TFLAG_AUTODOC, TFLAG_AUTODOC_COUCH, and bionic_data::upgraded_bionic.
operation_finish()
void activity_handlers::operation_finish (player_activity * act, Character * you)
Definition at line 3243 of file activity_handlers.cpp.
 {
     map &here = get_map();
     if( act->str_values[3] == "true" ) {
         if( act->values[1] > 0 ) {
             add_msg( m_good,
                      _( "The Autodoc returns to its resting position after successfully performing the operation." ) );
             const std::list<tripoint> autodocs = here.find_furnitures_with_flag_in_radius( you->pos(), 1,
                                                  ter_furn_flag::TFLAG_AUTODOC );
             sounds::sound( autodocs.front(), 10, sounds::sound_t::music,
                            _( "a short upbeat jingle: \"Operation successful\"" ), true,
                            "Autodoc",
                            "success" );
         } else {
             add_msg( m_bad,
                      _( "The Autodoc jerks back to its resting position after failing the operation." ) );
             const std::list<tripoint> autodocs = here.find_furnitures_with_flag_in_radius( you->pos(), 1,
                                                  ter_furn_flag::TFLAG_AUTODOC );
             sounds::sound( autodocs.front(), 10, sounds::sound_t::music,
                            _( "a sad beeping noise: \"Operation failed\"" ), true,
                            "Autodoc",
                            "failure" );
         }
     } else {
         if( act->values[1] > 0 ) {
             add_msg( m_good,
                      _( "The operation is a success." ) );
         } else {
             add_msg( m_bad,
                      _( "The operation is a failure." ) );
         }
     }
     you->remove_effect( effect_under_operation );
     act->set_to_null();
 }
References _, act, add_msg(), effect_under_operation, map::find_furnitures_with_flag_in_radius(), get_map(), m_bad, m_good, sounds::music, Creature::pos(), Creature::remove_effect(), sounds::sound(), and TFLAG_AUTODOC.
pickaxe_do_turn()
void activity_handlers::pickaxe_do_turn (player_activity * act, Character * you)
Definition at line 1679 of file activity_handlers.cpp.
 {
     const tripoint &pos = get_map().getlocal( act->placement );
     sfx::play_activity_sound( "tool", "pickaxe", sfx::get_heard_volume( pos ) );
     // each turn is too much
     if( calendar::once_every( 1_minutes ) ) {
         //~ Sound of a Pickaxe at work!
         sounds::sound( pos, 30, sounds::sound_t::destructive_activity, _( "CHNK!  CHNK!  CHNK!" ) );
     }
 }
References _, act, sounds::destructive_activity, sfx::get_heard_volume(), get_map(), map::getlocal(), calendar::once_every(), sfx::play_activity_sound(), math_opers::pos(), and sounds::sound().
pickaxe_finish()
void activity_handlers::pickaxe_finish (player_activity * act, Character * you)
Definition at line 1690 of file activity_handlers.cpp.
 {
     map &here = get_map();
     const tripoint pos( here.getlocal( act->placement ) );
     // Invalidate the activity early to prevent a query from mod_pain()
     act->set_to_null();
     if( you->is_avatar() ) {
         const int helpersize = get_player_character().get_num_crafting_helpers( 3 );
         if( here.is_bashable( pos ) && here.has_flag( ter_furn_flag::TFLAG_SUPPORTS_ROOF, pos ) &&
             here.ter( pos ) != ter_t_tree ) {
             // Tunneling through solid rock is sweaty, backbreaking work
             // Betcha wish you'd opted for the J-Hammer
             if( you->has_trait( trait_STOCKY_TROGLO ) ) {
                 you->mod_pain( std::max( 0, ( 1 * static_cast<int>( rng( 0, 3 ) ) ) - helpersize ) );
             } else {
                 you->mod_pain( std::max( 0, ( 2 * static_cast<int>( rng( 1, 3 ) ) ) - helpersize ) );
             }
         }
     }
     you->add_msg_player_or_npc( m_good,
                                 _( "You finish digging." ),
                                 _( "<npcname> finishes digging." ) );
     here.destroy( pos, true );
     if( !act->targets.empty() ) {
         item &it = *act->targets.front();
         you->consume_charges( it, it.ammo_required() );
     } else {
         debugmsg( "pickaxe activity targets empty" );
     }
     if( resume_for_multi_activities( *you ) ) {
         for( item &elem : here.i_at( pos ) ) {
             elem.set_var( "activity_var", you->name );
         }
     }
 }
References _, act, Character::add_msg_player_or_npc(), item::ammo_required(), Character::consume_charges(), debugmsg, map::destroy(), get_map(), Character::get_num_crafting_helpers(), get_player_character(), map::getlocal(), map::has_flag(), Character::has_trait(), map::i_at(), Creature::is_avatar(), map::is_bashable(), m_good, max(), Character::mod_pain(), Character::name, math_opers::pos(), resume_for_multi_activities(), rng(), map::ter(), ter_t_tree, TFLAG_SUPPORTS_ROOF, and trait_STOCKY_TROGLO.
plant_seed_finish()
void activity_handlers::plant_seed_finish (player_activity * act, Character * you)
Definition at line 3279 of file activity_handlers.cpp.
 {
     map &here = get_map();
     tripoint examp = here.getlocal( act->placement );
     const itype_id seed_id( act->str_values[0] );
     std::list<item> used_seed;
     if( item::count_by_charges( seed_id ) ) {
         used_seed = you->use_charges( seed_id, 1 );
     } else {
         used_seed = you->use_amount( seed_id, 1 );
     }
     if( !used_seed.empty() ) {
         used_seed.front().set_age( 0_turns );
         if( used_seed.front().has_var( "activity_var" ) ) {
             used_seed.front().erase_var( "activity_var" );
         }
         used_seed.front().set_flag( json_flag_HIDDEN_ITEM );
         here.add_item_or_charges( examp, used_seed.front() );
         if( here.has_flag_furn( seed_id->seed->required_terrain_flag, examp ) ) {
             here.furn_set( examp, furn_str_id( here.furn( examp )->plant->transform ) );
         } else if( seed_id->seed->required_terrain_flag == ter_furn_flag::TFLAG_PLANTABLE ) {
             here.set( examp, ter_t_dirt, furn_f_plant_seed );
         } else {
             here.furn_set( examp, furn_f_plant_seed );
         }
         you->add_msg_player_or_npc( _( "You plant some %s." ), _( "<npcname> plants some %s." ),
                                     item::nname( seed_id ) );
     }
     // Go back to what we were doing before
     // could be player zone activity, or could be NPC multi-farming
     act->set_to_null();
     resume_for_multi_activities( *you );
 }
References _, act, map::add_item_or_charges(), Character::add_msg_player_or_npc(), item::count_by_charges(), map::furn(), furn_f_plant_seed, map::furn_set(), get_map(), map::getlocal(), map::has_flag_furn(), json_flag_HIDDEN_ITEM, item::nname(), furn_t::plant, resume_for_multi_activities(), itype::seed, map::set(), ter_t_dirt, TFLAG_PLANTABLE, Character::use_amount(), and Character::use_charges().
pull_creature_finish()
void activity_handlers::pull_creature_finish (player_activity * act, Character * you)
Definition at line 3698 of file activity_handlers.cpp.
 {
     if( you->is_avatar() ) {
         you->as_avatar()->longpull( act->name );
     } else {
         // TODO: fix point types
         you->longpull( act->name, get_map().bub_from_abs( act->placement ).raw() );
     }
     act->set_to_null();
 }
References act, Creature::as_avatar(), get_map(), Creature::is_avatar(), avatar::longpull(), and Creature::longpull().
pulp_do_turn()
void activity_handlers::pulp_do_turn (player_activity * act, Character * you)
Strength increases pulping power, with diminishing returns
Definition at line 1726 of file activity_handlers.cpp.
 {
     map &here = get_map();
     const tripoint &pos = here.getlocal( act->placement );
     const item_location weapon = you->get_wielded_item();
     int weap_cut = 0;
     int weap_stab = 0;
     int weap_bash = 0;
     int mess_radius = 1;
     if( weapon ) {
         // FIXME: Hardcoded damage types
         weap_cut = weapon->damage_melee( damage_cut );
         weap_stab = weapon->damage_melee( damage_stab );
         weap_bash = weapon->damage_melee( damage_bash );
         if( weapon->has_flag( flag_MESSY ) ) {
             mess_radius = 2;
         }
     }
     // Stabbing weapons are a lot less effective at pulping
     const int cut_power = std::max( weap_cut, weap_stab / 2 );
     ///\EFFECT_STR increases pulping power, with diminishing returns
     float pulp_power = std::sqrt( ( you->get_arm_str() + weap_bash ) * ( cut_power + 1.0f ) );
     float pulp_effort = you->str_cur + weap_bash;
     // Multiplier to get the chance right + some bonus for survival skill
     pulp_power *= 40 + you->get_skill_level( skill_survival ) * 5;
     int moves = 0;
     // use this to collect how many corpse are pulped
     int &num_corpses = act->index;
     map_stack corpse_pile = here.i_at( pos );
     for( item &corpse : corpse_pile ) {
         const mtype *corpse_mtype = corpse.get_mtype();
         const bool acid_immune = you->is_immune_damage( damage_acid ) ||
                                  you->is_immune_field( fd_acid );
         if( !corpse.is_corpse() || !corpse.can_revive() ||
             ( ( std::find( act->str_values.begin(), act->str_values.end(), "auto_pulp_no_acid" ) !=
                 act->str_values.end() && corpse_mtype->bloodType().obj().has_acid ) && !acid_immune ) ) {
             // Don't smash non-rezing corpses //don't smash acid zombies when auto pulping unprotected
             continue;
         }
         while( corpse.damage() < corpse.max_damage() ) {
             // Increase damage as we keep smashing ensuring we eventually smash the target.
             if( x_in_y( pulp_power, corpse.volume() / units::legacy_volume_factor ) ) {
                 corpse.inc_damage();
                 if( corpse.damage() == corpse.max_damage() ) {
                     num_corpses++;
                 }
             }
             if( x_in_y( pulp_power, corpse.volume() / units::legacy_volume_factor ) ) {
                 // Splatter some blood around
                 // Splatter a bit more randomly, so that it looks cooler
                 const int radius = mess_radius + x_in_y( pulp_power, 500 ) + x_in_y( pulp_power, 1000 );
                 const tripoint dest( pos + point( rng( -radius, radius ), rng( -radius, radius ) ) );
                 const field_type_id type_blood = ( mess_radius > 1 && x_in_y( pulp_power, 10000 ) ) ?
                                                  corpse.get_mtype()->gibType() :
                                                  corpse.get_mtype()->bloodType();
                 here.add_splatter_trail( type_blood, pos, dest );
             }
             // mixture of isaac clarke stomps and swinging your weapon
             you->burn_energy_all( -pulp_effort );
             you->recoil = MAX_RECOIL;
             if( one_in( 4 ) ) {
                 // Smashing may not be butchery, but it involves some zombie anatomy
                 you->practice( skill_survival, 2, 2 );
             }
             float stamina_ratio = static_cast<float>( you->get_stamina() ) / you->get_stamina_max();
             moves += 100 / std::max( 0.25f,
                                      stamina_ratio ) * you->exertion_adjusted_move_multiplier( act->exertion_level() );
             if( stamina_ratio < 0.33 || you->is_npc() ) {
                 you->set_moves( std::min( 0, you->get_moves() - moves ) );
                 return;
             }
             if( moves >= you->get_moves() ) {
                 // Enough for this turn;
                 you->mod_moves( -moves );
                 return;
             }
         }
         corpse.set_flag( flag_PULPED );
     }
     // If we reach this, all corpses have been pulped, finish the activity
     act->moves_left = 0;
     if( num_corpses == 0 ) {
         you->add_msg_if_player( m_bad, _( "The corpse moved before you could finish smashing it!" ) );
         return;
     }
     // TODO: Factor in how long it took to do the smashing.
     you->add_msg_player_or_npc( n_gettext( "The corpse is thoroughly pulped.",
                                            "The corpses are thoroughly pulped.", num_corpses ),
                                 n_gettext( "<npcname> finished pulping the corpse.",
                                            "<npcname> finished pulping the corpses.", num_corpses ) );
 }
References _, act, Character::add_msg_if_player(), Character::add_msg_player_or_npc(), map::add_splatter_trail(), mtype::bloodType(), Character::burn_energy_all(), corpse, damage_acid, damage_bash, damage_cut, item::damage_melee(), damage_stab, Character::exertion_adjusted_move_multiplier(), activity_type::exertion_level(), fd_acid, flag_MESSY, flag_PULPED, Character::get_arm_str(), get_map(), Creature::get_moves(), Character::get_skill_level(), Character::get_stamina(), Character::get_stamina_max(), Character::get_wielded_item(), map::getlocal(), field_type::has_acid, item::has_flag(), map::i_at(), Character::is_immune_damage(), Character::is_immune_field(), units::legacy_volume_factor, m_bad, max(), MAX_RECOIL, min(), Creature::mod_moves(), n_gettext, int_id< T >::obj(), one_in(), math_opers::pos(), Character::practice(), Character::recoil, rng(), Creature::set_moves(), skill_survival, sqrt(), Character::str_cur, and x_in_y().
pulp_finish()
void activity_handlers::pulp_finish (player_activity * act, Character * you)
Definition at line 1829 of file activity_handlers.cpp.
 {
     if( you->is_npc() ) {
         npc *guy = dynamic_cast<npc *>( you );
         guy->revert_after_activity();
         guy->pulp_location.reset();
     } else {
         act->set_to_null();
     }
 }
References act, Character::is_npc(), npc::pulp_location, and npc::revert_after_activity().
repair_item_do_turn()
void activity_handlers::repair_item_do_turn (player_activity * act, Character * you)
Definition at line 2961 of file activity_handlers.cpp.
 {
     // Moves are decremented based on a combination of speed and good vision (not in the dark, farsighted, etc)
     const float exertion_mult = you->exertion_adjusted_move_multiplier( act->exertion_level() );
     const int effective_moves = you->get_moves() / ( you->fine_detail_vision_mod() * exertion_mult );
     if( effective_moves <= act->moves_left ) {
         act->moves_left -= effective_moves;
         you->set_moves( 0 );
     } else {
         you->mod_moves( -act->moves_left * you->fine_detail_vision_mod() );
         act->moves_left = 0;
     }
 }
References act, Character::exertion_adjusted_move_multiplier(), activity_type::exertion_level(), Character::fine_detail_vision_mod(), Creature::get_moves(), Creature::mod_moves(), and Creature::set_moves().
repair_item_finish()
void activity_handlers::repair_item_finish (player_activity * act, Character * you)
Definition at line 2380 of file activity_handlers.cpp.
 {
     ::repair_item_finish( act, you, false );
 }
References act, and repair_item_finish().
resume_for_multi_activities()
bool activity_handlers::resume_for_multi_activities (Character & you)
Definition at line 384 of file activity_handlers.cpp.
 {
     if( !you.backlog.empty() ) {
         player_activity &back_act = you.backlog.front();
         if( back_act.is_multi_type() ) {
             assign_multi_activity( you, back_act );
             you.backlog.clear();
             return true;
         }
     }
     return false;
 }
References assign_multi_activity(), Character::backlog, and player_activity::is_multi_type().
Referenced by butcher_finish(), chop_logs_activity_actor::finish(), chop_planks_activity_actor::finish(), chop_tree_activity_actor::finish(), churn_activity_actor::finish(), mop_activity_actor::finish(), generic_multi_activity_do(), jackhammer_finish(), pickaxe_finish(), plant_seed_finish(), and vehicle_finish().
robot_control_do_turn()
void activity_handlers::robot_control_do_turn (player_activity * act, Character * you)
Definition at line 3618 of file activity_handlers.cpp.
 {
     if( act->monsters.empty() ) {
         debugmsg( "No monster assigned in ACT_ROBOT_CONTROL" );
         act->set_to_null();
         return;
     }
     const shared_ptr_fast<monster> z = act->monsters[0].lock();
     if( !z || !iuse::robotcontrol_can_target( you, *z ) ) {
         you->add_msg_if_player( _( "Target lost.  IFF override failed." ) );
         act->set_to_null();
         return;
     }
     // TODO: Add some kind of chance of getting the target's attention
 }
References _, act, Character::add_msg_if_player(), debugmsg, and iuse::robotcontrol_can_target().
robot_control_finish()
void activity_handlers::robot_control_finish (player_activity * act, Character * you)
Intelligence increases chance of successful robot reprogramming, vs difficulty Computer increases chance of successful robot reprogramming, vs difficulty
Definition at line 3636 of file activity_handlers.cpp.
 {
     act->set_to_null();
     if( act->monsters.empty() ) {
         debugmsg( "No monster assigned in ACT_ROBOT_CONTROL" );
         return;
     }
     shared_ptr_fast<monster> z = act->monsters[0].lock();
     act->monsters.clear();
     if( !z || !iuse::robotcontrol_can_target( you, *z ) ) {
         you->add_msg_if_player( _( "Target lost.  IFF override failed." ) );
         return;
     }
     you->add_msg_if_player( _( "You unleash your override attack on the %s." ), z->name() );
     /** @EFFECT_INT increases chance of successful robot reprogramming, vs difficulty */
     /** @EFFECT_COMPUTER increases chance of successful robot reprogramming, vs difficulty */
     const float computer_skill = you->get_skill_level( skill_computer );
     const float randomized_skill = rng( 2, you->int_cur ) + computer_skill;
     float success = computer_skill - 3 * z->type->difficulty / randomized_skill;
     if( z->has_flag( mon_flag_RIDEABLE_MECH ) ) {
         success = randomized_skill - rng( 1, 11 );
     }
     // rideable mechs are not hostile, they have no AI, they do not resist control as much.
     if( success >= 0 ) {
         you->add_msg_if_player( _( "You successfully override the %s's IFF protocols!" ),
                                 z->name() );
         z->friendly = -1;
         if( z->has_flag( mon_flag_RIDEABLE_MECH ) ) {
             z->add_effect( effect_pet, 1_turns, true );
         }
     } else if( success >= -2 ) {
         //A near success
         you->add_msg_if_player( _( "The %s short circuits as you attempt to reprogram it!" ), z->name() );
         //damage it a little
         z->apply_damage( you, bodypart_id( "torso" ), rng( 1, 10 ) );
         if( z->is_dead() ) {
             you->practice( skill_computer, 10 );
             // Do not do the other effects if the robot died
             return;
         }
         if( one_in( 3 ) ) {
             you->add_msg_if_player( _( "and turns friendly!" ) );
             //did the robot became friendly permanently?
             if( one_in( 3 ) ) {
                 //it did
                 z->friendly = -1;
             } else {
                 // it didn't
                 z->friendly = rng( 5, 40 );
             }
         }
     } else {
         you->add_msg_if_player( _( "but the robot refuses to acknowledge you as an ally!" ) );
     }
     you->practice( skill_computer, 10 );
 }
References _, act, Character::add_msg_if_player(), debugmsg, effect_pet, Character::get_skill_level(), Character::int_cur, mon_flag_RIDEABLE_MECH, one_in(), Character::practice(), rng(), iuse::robotcontrol_can_target(), and skill_computer.
socialize_finish()
void activity_handlers::socialize_finish (player_activity * act, Character * you)
Definition at line 3075 of file activity_handlers.cpp.
 {
     you->add_msg_if_player( _( "%s finishes chatting with you." ), act->str_values[0] );
     act->set_to_null();
 }
References _, act, and Character::add_msg_if_player().
spellcasting_finish()
void activity_handlers::spellcasting_finish (player_activity * act, Character * you)
Definition at line 3802 of file activity_handlers.cpp.
 {
     act->set_to_null();
     const int level_override = act->get_value( 0 );
     spell_id sp( act->name );
     // if level is -1 then we know it's a player spell, otherwise we build it from the ground up
     spell temp_spell( sp );
     spell &spell_being_cast = ( level_override == -1 ) ? you->magic->get_spell( sp ) : temp_spell;
     // if level != 1 then we need to set the spell's level
     if( level_override != -1 ) {
         spell_being_cast.set_level( *you, level_override );
     }
     // choose target for spell before continuing
     const std::optional<tripoint> target = act->coords.empty() ? spell_being_cast.select_target(
             you ) : get_map().getlocal( act->coords.front() );
     if( target ) {
         // npcs check for target viability
         if( !you->is_npc() || spell_being_cast.is_valid_target( *you, *target ) ) {
             // no turning back now. it's all said and done.
             bool success = act->get_value( 1 ) == 1 ||
                            rng_float( 0.0f, 1.0f ) >= spell_being_cast.spell_fail( *you );
             int exp_gained = spell_being_cast.casting_exp( *you );
             if( !success ) {
                 you->add_msg_if_player( game_message_params{ m_bad, gmf_bypass_cooldown },
                                         _( "You lose your concentration!" ) );
                 if( !spell_being_cast.is_max_level( *you ) && level_override == -1 ) {
                     // still get some experience for trying
                     spell_being_cast.gain_exp( *you, exp_gained / 5 );
                     you->add_msg_if_player( m_good, _( "You gain %i experience.  New total %i." ), exp_gained / 5,
                                             spell_being_cast.xp() );
                 }
                 get_event_bus().send<event_type::spellcasting_finish>( you->getID(), false, sp,
                         spell_being_cast.spell_class(), spell_being_cast.get_difficulty( *you ),
                         spell_being_cast.energy_cost( *you ), spell_being_cast.casting_time( *you ),
                         spell_being_cast.damage( *you ) );
                 return;
             }
             if( spell_being_cast.has_flag( spell_flag::VERBAL ) && !you->has_flag( json_flag_SILENT_SPELL ) ) {
                 sounds::sound( you->pos(), you->get_shout_volume() / 2, sounds::sound_t::speech,
                                _( "cast a spell" ),
                                false );
             }
             you->add_msg_if_player( spell_being_cast.message(), spell_being_cast.name() );
             // this is here now so that the spell first consume its components then casts its effects, necessary to cast
             // spells with the components in hand.
             spell_being_cast.use_components( *you );
             // pay the cost.  Allows ternaries based on having an effect or trait to calculate cost correctly
             int cost = spell_being_cast.energy_cost( *you );
             spell_being_cast.cast_all_effects( *you, *target );
             if( act->get_value( 2 ) != 0 ) {
                 switch( spell_being_cast.energy_source() ) {
                     case magic_energy_type::mana:
                         you->magic->mod_mana( *you, -cost );
                         break;
                     case magic_energy_type::stamina:
                         you->mod_stamina( -cost );
                         break;
                     case magic_energy_type::bionic:
                         you->mod_power_level( -units::from_kilojoule( static_cast<std::int64_t>( cost ) ) );
                         break;
                     case magic_energy_type::hp:
                         blood_magic( you, cost );
                         break;
                     case magic_energy_type::none:
                     default:
                         break;
                 }
             }
             if( level_override == -1 ) {
                 if( !spell_being_cast.is_max_level( *you ) ) {
                     // reap the reward
                     int old_level = spell_being_cast.get_level();
                     if( old_level == 0 ) {
                         spell_being_cast.gain_level( *you );
                         you->add_msg_if_player( m_good,
                                                 _( "Something about how this spell works just clicked!  You gained a level!" ) );
                     } else {
                         spell_being_cast.gain_exp( *you, exp_gained );
                         you->add_msg_if_player( m_good, _( "You gain %i experience.  New total %i." ), exp_gained,
                                                 spell_being_cast.xp() );
                     }
                     if( spell_being_cast.get_level() != old_level ) {
                         // Level 0-1 message is printed above - notify player when leveling up further
                         if( old_level > 0 ) {
                             you->add_msg_if_player( m_good, _( "You gained a level in %s!" ), spell_being_cast.name() );
                         }
                     }
                 }
             }
             if( !act->targets.empty() ) {
                 item *it = act->targets.front().get_item();
                 if( it && !it->has_flag( flag_USE_PLAYER_ENERGY ) ) {
                     you->consume_charges( *it, it->type->charges_to_use() );
                 }
             }
             get_event_bus().send<event_type::spellcasting_finish>( you->getID(), true, sp,
                     spell_being_cast.spell_class(), spell_being_cast.get_difficulty( *you ),
                     spell_being_cast.energy_cost( *you ), spell_being_cast.casting_time( *you ),
                     spell_being_cast.damage( *you ) );
         }
     }
 }
References _, act, Character::add_msg_if_player(), bionic, blood_magic(), spell::cast_all_effects(), spell::casting_exp(), spell::casting_time(), itype::charges_to_use(), Character::consume_charges(), spell::damage(), spell::energy_cost(), spell::energy_source(), flag_USE_PLAYER_ENERGY, units::from_kilojoule(), spell::gain_exp(), spell::gain_level(), spell::get_difficulty(), get_event_bus(), spell::get_level(), get_map(), Character::get_shout_volume(), Character::getID(), map::getlocal(), gmf_bypass_cooldown, item::has_flag(), Character::has_flag(), spell::has_flag(), hp, spell::is_max_level(), Character::is_npc(), spell::is_valid_target(), json_flag_SILENT_SPELL, m_bad, m_good, Character::magic, mana, spell::message(), Character::mod_power_level(), Character::mod_stamina(), spell::name(), none, Creature::pos(), rng_float(), spell::select_target(), event_bus::send(), spell::set_level(), sounds::sound(), sounds::speech, spell::spell_class(), spell::spell_fail(), spellcasting_finish, stamina, item::type, spell::use_components(), VERBAL, and spell::xp().
start_engines_finish()
void activity_handlers::start_engines_finish (player_activity * act, Character * you)
Definition at line 2178 of file activity_handlers.cpp.
 {
     act->set_to_null();
     // Find the vehicle by looking for a remote vehicle first, then at
     // act->relative_placement away from avatar
     vehicle *veh = g->remoteveh();
     map &here = get_map();
     if( !veh ) {
         const tripoint_bub_ms pos = get_player_character().pos_bub() + act->relative_placement;
         veh = veh_pointer_or_null( here.veh_at( pos ) );
         if( !veh ) {
             return;
         }
     }
     int attempted = 0;
     int non_muscle_attempted = 0;
     int started = 0;
     int non_muscle_started = 0;
     int non_combustion_started = 0;
     const bool take_control = act->values[0];
     for( const int p : veh->engines ) {
         vehicle_part &vp = veh->part( p );
         if( veh->is_engine_on( vp ) ) {
             attempted++;
             if( !veh->is_engine_type( vp, itype_muscle ) &&
                 !veh->is_engine_type( vp, itype_animal ) ) {
                 non_muscle_attempted++;
             }
             if( veh->start_engine( vp ) ) {
                 started++;
                 if( !veh->is_engine_type( vp, itype_muscle ) &&
                     !veh->is_engine_type( vp, itype_animal ) ) {
                     non_muscle_started++;
                 } else {
                     non_combustion_started++;
                 }
             }
         }
     }
     //Did any engines start?
     veh->engine_on = started;
     //init working engine noise
     sfx::do_vehicle_engine_sfx();
     if( attempted == 0 ) {
         add_msg( m_info, _( "The %s doesn't have an engine!" ), veh->name );
     } else if( non_muscle_attempted > 0 ) {
         //Some non-muscle engines tried to start
         if( non_muscle_attempted == non_muscle_started ) {
             //All of the non-muscle engines started
             add_msg( n_gettext( "The %s's engine starts up.",
                                 "The %s's engines start up.", non_muscle_started ), veh->name );
         } else if( non_muscle_started > 0 ) {
             //Only some of the non-muscle engines started
             add_msg( n_gettext( "One of the %s's engines start up.",
                                 "Some of the %s's engines start up.", non_muscle_started ), veh->name );
         } else if( non_combustion_started > 0 ) {
             //Non-combustions "engines" started
             add_msg( _( "The %s is ready for movement." ), veh->name );
         } else {
             //All of the non-muscle engines failed
             add_msg( m_bad, n_gettext( "The %s's engine fails to start.",
                                        "The %s's engines fail to start.", non_muscle_attempted ), veh->name );
         }
     }
     if( take_control && !veh->engine_on && !veh->velocity ) {
         you->controlling_vehicle = false;
         add_msg( _( "You let go of the controls." ) );
     }
 }
References _, act, add_msg(), Character::controlling_vehicle, sfx::do_vehicle_engine_sfx(), vehicle::engine_on, vehicle::engines, g, get_map(), get_player_character(), vehicle::is_engine_on(), vehicle::is_engine_type(), itype_animal, itype_muscle, m_bad, m_info, n_gettext, vehicle::name, vehicle::part(), math_opers::pos(), Creature::pos_bub(), vehicle::start_engine(), map::veh_at(), veh_pointer_or_null(), and vehicle::velocity.
start_fire_do_turn()
void activity_handlers::start_fire_do_turn (player_activity * act, Character * you)
Definition at line 1869 of file activity_handlers.cpp.
 {
     map &here = get_map();
     // TODO: fix point types
     tripoint where = here.getlocal( act->placement );
     if( !here.is_flammable( where ) ) {
         try_fuel_fire( *act, *you, true );
         if( !here.is_flammable( where ) ) {
             you->add_msg_if_player( m_info, _( "There's nothing to light there." ) );
             you->cancel_activity();
             return;
         }
     }
     // Sometimes when an item is dropped it causes the whole item* to get set to null.
     // This null pointer gets cast to a reference at some point, causing UB and
     // segfaults. It looks like something is supposed to catch this, maybe
     // get_safe_reference in item.cpp, but it's not working so we check for a
     // null pointer here.
     //
     if( act->targets.front().get_item() == nullptr ) {
         add_msg( m_bad, _( "You have lost the item you were using to start the fire." ) );
         you->cancel_activity();
         return;
     }
     item &firestarter = *act->targets.front();
     if( firestarter.has_flag( flag_REQUIRES_TINDER ) ) {
         if( !here.tinder_at( where ) ) {
             inventory_filter_preset preset( []( const item_location & loc ) {
                 return loc->has_flag( flag_TINDER );
             } );
             inventory_pick_selector inv_s( *you, preset );
             inv_s.add_nearby_items( PICKUP_RANGE );
             inv_s.add_character_items( *you );
             inv_s.set_title( _( "Select tinder to use for lighting a fire" ) );
             item_location tinder;
             if( inv_s.empty() || !( tinder = inv_s.execute() ) ) {
                 you->add_msg_if_player( m_info, _( "This item requires tinder to light." ) );
                 you->cancel_activity();
                 return;
             }
             item copy = *tinder;
             bool count_by_charges = tinder->count_by_charges();
             if( count_by_charges ) {
                 tinder->charges--;
                 copy.charges = 1;
             }
             here.add_item_or_charges( where, copy );
             if( !count_by_charges || tinder->charges <= 0 ) {
                 tinder.remove_item();
             }
         }
     }
     const use_function *usef = firestarter.type->get_use( "firestarter" );
     if( usef == nullptr || usef->get_actor_ptr() == nullptr ) {
         add_msg( m_bad, _( "You have lost the item you were using to start the fire." ) );
         you->cancel_activity();
         return;
     }
     you->mod_moves( -you->get_moves() );
     const firestarter_actor *actor = dynamic_cast<const firestarter_actor *>( usef->get_actor_ptr() );
     const float light = actor->light_mod( you->pos() );
     act->moves_left -= light * 100;
     if( light < 0.1 ) {
         add_msg( m_bad, _( "There is not enough sunlight to start a fire now.  You stop trying." ) );
         you->cancel_activity();
     }
 }
References _, act, map::add_item_or_charges(), add_msg(), Character::add_msg_if_player(), Character::cancel_activity(), item::charges, item::count_by_charges(), flag_REQUIRES_TINDER, flag_TINDER, use_function::get_actor_ptr(), get_map(), Creature::get_moves(), itype::get_use(), map::getlocal(), item::has_flag(), map::is_flammable(), light, firestarter_actor::light_mod(), m_bad, m_info, Creature::mod_moves(), PICKUP_RANGE, Creature::pos(), item_location::remove_item(), map::tinder_at(), try_fuel_fire(), and item::type.
start_fire_finish()
void activity_handlers::start_fire_finish (player_activity * act, Character * you)
Definition at line 1840 of file activity_handlers.cpp.
 {
     static const std::string iuse_name_string( "firestarter" );
     item &it = *act->targets.front();
     item *used_tool = it.get_usable_item( iuse_name_string );
     if( used_tool == nullptr ) {
         debugmsg( "Lost tool used for starting fire" );
         act->set_to_null();
         return;
     }
     const use_function *use_fun = used_tool->get_use( iuse_name_string );
     const firestarter_actor *actor = dynamic_cast<const firestarter_actor *>
                                      ( use_fun->get_actor_ptr() );
     if( actor == nullptr ) {
         debugmsg( "iuse_actor type descriptor and actual type mismatch" );
         act->set_to_null();
         return;
     }
     it.activation_consume( 1, you->pos(), you );
     you->practice( skill_survival, act->index, 5 );
     firestarter_actor::resolve_firestarter_use( you, get_map().bub_from_abs( act->placement ) );
     act->set_to_null();
 }
References act, item::activation_consume(), debugmsg, use_function::get_actor_ptr(), get_map(), item::get_usable_item(), item::get_use(), Creature::pos(), Character::practice(), firestarter_actor::resolve_firestarter_use(), and skill_survival.
study_spell_do_turn()
void activity_handlers::study_spell_do_turn (player_activity * act, Character * you)
Definition at line 3915 of file activity_handlers.cpp.
 {
     // Stop if there is not enough light to study
     if( you->fine_detail_vision_mod() > 4 ) {
         act->values[2] = -1;
         act->moves_left = 0;
         return;
     }
     // str_value 1 is "study" if we already know the spell, and want to study it more
     if( act->get_str_value( 1 ) == "study" ) {
         spell &studying = you->magic->get_spell( spell_id( act->name ) );
         // If we are studying to gain a level, keep studying until level changes
         if( act->get_str_value( 0 ) == "gain_level" ) {
             if( studying.get_level() < act->get_value( 1 ) ) {
                 act->moves_left = 1000000;
             } else {
                 act->moves_left = 0;
             }
         }
         const int old_level = studying.get_level();
         // Gain some experience from studying
         const int xp = roll_remainder( studying.exp_modifier( *you ) / to_turns<float>( 6_seconds ) );
         act->values[0] += xp;
         studying.gain_exp( *you, xp );
         bool leveled_up = you->practice( studying.skill(), xp, studying.get_difficulty( *you ), true );
         if( leveled_up &&
             studying.get_difficulty( *you ) < static_cast<int>( you->get_skill_level( studying.skill() ) ) ) {
             you->handle_skill_warning( studying.skill(),
                                        true ); // show the skill warning on level up, since we suppress it in practice() above
         }
         // Notify player if the spell leveled up
         if( studying.get_level() > old_level ) {
             you->add_msg_if_player( m_good, _( "You gained a level in %s!" ), studying.name() );
         }
     }
 }
References _, act, Character::add_msg_if_player(), spell::exp_modifier(), Character::fine_detail_vision_mod(), spell::gain_exp(), spell::get_difficulty(), spell::get_level(), Character::get_skill_level(), Character::handle_skill_warning(), m_good, Character::magic, spell::name(), Character::practice(), roll_remainder(), and spell::skill().
study_spell_finish()
void activity_handlers::study_spell_finish (player_activity * act, Character * you)
Definition at line 3952 of file activity_handlers.cpp.
 {
     act->set_to_null();
     const int total_exp_gained = act->get_value( 0 );
     if( act->get_str_value( 1 ) == "study" ) {
         you->add_msg_if_player( m_good, _( "You gained %i experience from your study session." ),
                                 total_exp_gained );
     } else if( act->get_str_value( 1 ) == "learn" && act->values[2] == 0 ) {
         you->magic->learn_spell( act->name, *you );
     }
     if( act->values[2] == -1 ) {
         you->add_msg_if_player( m_bad, _( "It's too dark to read." ) );
     }
 }
References _, act, Character::add_msg_if_player(), m_bad, m_good, and Character::magic.
teach_finish()
void activity_handlers::teach_finish (player_activity * act, Character * you)
Definition at line 1974 of file activity_handlers.cpp.
 {
     const skill_id sk( act->name );
     const proficiency_id pr( act->name );
     const matype_id ma( act->name );
     const spell_id sp( act->name );
     std::string subject;
     if( sk.is_valid() ) {
         subject = sk->name();
     } else if( pr.is_valid() ) {
         subject = pr->name();
     } else if( ma.is_valid() ) {
         subject = ma->name.translated();
     } else if( sp.is_valid() ) {
         subject = sp->name.translated();
     } else {
         debugmsg( "teach_finish without a valid skill or style or spell name" );
     }
     if( you->is_avatar() ) {
         add_msg( m_good, _( "You finish teaching %s." ), subject );
     } else {
         add_msg( m_good, _( "%s finishes teaching %s." ), you->name, subject );
     }
     act->set_to_null();
 }
References _, act, add_msg(), debugmsg, Creature::is_avatar(), string_id< T >::is_valid(), m_good, Character::name, spell_type::name, martialart::name, proficiency::name(), Skill::name(), and translation::translated().
tidy_up_do_turn()
void activity_handlers::tidy_up_do_turn (player_activity * act, Character * you)
Definition at line 3370 of file activity_handlers.cpp.
 {
     generic_multi_activity_handler( *act, *you );
 }
References act, and generic_multi_activity_handler().
toolmod_add_finish()
void activity_handlers::toolmod_add_finish (player_activity * act, Character * you)
Definition at line 2713 of file activity_handlers.cpp.
 {
     act->set_to_null();
     if( act->targets.size() != 2 || !act->targets[0] || !act->targets[1] ) {
         debugmsg( "Incompatible arguments to ACT_TOOLMOD_ADD" );
         return;
     }
     item &tool = *act->targets[0];
     item &mod = *act->targets[1];
     you->add_msg_if_player( m_good, _( "You successfully attached the %1$s to your %2$s." ),
                             mod.tname(), tool.tname() );
     mod.set_flag( flag_IRREMOVABLE );
     tool.put_in( mod, pocket_type::MOD );
     tool.on_contents_changed();
     act->targets[1].remove_item();
 }
References _, act, Character::add_msg_if_player(), debugmsg, flag_IRREMOVABLE, m_good, MOD, item::on_contents_changed(), item::put_in(), and item::tname().
train_finish()
void activity_handlers::train_finish (player_activity * act, Character * you)
Definition at line 2003 of file activity_handlers.cpp.
 {
     const std::vector<npc *> teachlist = g->get_npcs_if( [act]( const npc & n ) {
         return n.getID().get_value() == act->index;
     } );
     Character *teacher = &get_player_character();
     if( !teachlist.empty() ) {
         teacher = teachlist.front();
     }
     if( teacher->activity.id() == ACT_TRAIN_TEACHER ) {
         bool all_students_done = true;
         g->get_npcs_if( [&]( const npc & n ) {
             for( int st_id : teacher->activity.values ) {
                 if( n.getID().get_value() == st_id && n.activity.id() == ACT_TRAIN ) {
                     all_students_done = false;
                     break;
                 }
             }
             return false;
         } );
         if( all_students_done ) {
             teacher->cancel_activity();
         }
     }
     const skill_id sk( act->name );
     if( sk.is_valid() ) {
         const Skill &skill = sk.obj();
         std::string skill_name = skill.name();
         int old_skill_level = you->get_knowledge_level( sk );
         you->practice( sk, 100, old_skill_level + 2 );
         int new_skill_level = you->get_knowledge_level( sk );
         if( old_skill_level != new_skill_level ) {
             if( you->is_avatar() ) {
                 add_msg( m_good, _( "You finish training %s to level %d." ),
                          skill_name, new_skill_level );
             }
             get_event_bus().send<event_type::gains_skill_level>( you->getID(), sk, new_skill_level );
         } else if( you->is_avatar() ) {
             add_msg( m_good, _( "You get some training in %s." ), skill_name );
         }
         act->set_to_null();
         return;
     }
     const proficiency_id &proficiency = proficiency_id( act->name );
     if( proficiency.is_valid() ) {
         you->practice_proficiency( proficiency, 15_minutes );
         if( you->is_avatar() ) {
             add_msg( m_good, _( "You get some training in %s." ), proficiency->name() );
         }
         act->set_to_null();
         return;
     }
     const matype_id &ma_id = matype_id( act->name );
     if( ma_id.is_valid() ) {
         const martialart &mastyle = ma_id.obj();
         // Trained martial arts,
         get_event_bus().send<event_type::learns_martial_art>( you->getID(), ma_id );
         you->martial_arts_data->learn_style( mastyle.id, you->is_avatar() );
     } else if( !magic_train( act, you ) ) {
         debugmsg( "train_finish without a valid skill or style or spell name" );
     }
     act->set_to_null();
 }
References act, ACT_TRAIN_TEACHER, Character::activity, Character::cancel_activity(), g, get_player_character(), Character::getID(), player_activity::id(), and player_activity::values.
travel_do_turn()
void activity_handlers::travel_do_turn (player_activity * act, Character * you)
Definition at line 2822 of file activity_handlers.cpp.
 {
     if( !you->omt_path.empty() ) {
         you->omt_path.pop_back();
         if( you->omt_path.empty() ) {
             you->add_msg_if_player( m_info, _( "You have reached your destination." ) );
             act->set_to_null();
             return;
         }
         const tripoint_abs_omt next_omt = you->omt_path.back();
         tripoint_abs_ms waypoint;
         if( you->omt_path.size() == 1 ) {
             // if next omt is the final one, target its midpoint
             waypoint = midpoint( project_bounds<coords::ms>( next_omt ) );
         } else {
             // otherwise target the middle of the edge nearest to our current location
             const tripoint_abs_ms cur_omt_mid = midpoint( project_bounds<coords::ms>
                                                 ( you->global_omt_location() ) );
             waypoint = clamp( cur_omt_mid, project_bounds<coords::ms>( next_omt ) );
         }
         map &here = get_map();
         tripoint_bub_ms centre_sub = here.bub_from_abs( waypoint );
         if( !here.passable( centre_sub ) ) {
             tripoint_range<tripoint_bub_ms> candidates = here.points_in_radius( centre_sub, 2 );
             for( const tripoint_bub_ms &elem : candidates ) {
                 if( here.passable( elem ) ) {
                     centre_sub = elem;
                     break;
                 }
             }
         }
         const std::vector<tripoint_bub_ms> route_to =
             here.route( you->pos_bub(), centre_sub, you->get_pathfinding_settings(),
                         you->get_path_avoid() );
         if( !route_to.empty() ) {
             const activity_id act_travel = ACT_TRAVELLING;
             you->set_destination( route_to, player_activity( act_travel ) );
         } else {
             you->add_msg_if_player( _( "You cannot reach that destination" ) );
         }
     } else {
         you->add_msg_if_player( m_info, _( "You have reached your destination." ) );
     }
     act->set_to_null();
 }
References _, act, ACT_TRAVELLING, Character::add_msg_if_player(), map::bub_from_abs(), clamp(), get_map(), Character::get_path_avoid(), Character::get_pathfinding_settings(), Creature::global_omt_location(), m_info, midpoint(), Character::omt_path, map::passable(), map::points_in_radius(), Creature::pos_bub(), map::route(), and Character::set_destination().
tree_communion_do_turn()
void activity_handlers::tree_communion_do_turn (player_activity * act, Character * you)
Definition at line 3709 of file activity_handlers.cpp.
 {
     // There's an initial rooting process.
     if( act->values.front() > 0 ) {
         act->values.front() -= 1;
         if( act->values.front() == 0 ) {
             if( you->has_trait( trait_id( trait_SPIRITUAL ) ) ) {
                 you->add_msg_if_player( m_good, _( "The ancient tree spirits answer your call." ) );
             } else {
                 you->add_msg_if_player( m_good, _( "Your communion with the trees has begun." ) );
             }
         }
         return;
     }
     // Information is received every minute.
     if( !calendar::once_every( 1_minutes ) ) {
         return;
     }
     // Breadth-first search forest tiles until one reveals new overmap tiles.
     std::queue<tripoint_abs_omt> q;
     std::unordered_set<tripoint_abs_omt> seen;
     tripoint_abs_omt loc = you->global_omt_location();
     q.push( loc );
     seen.insert( loc );
     const std::function<bool( const oter_id & )> filter = []( const oter_id & ter ) {
         return ter.obj().is_wooded() || ter.obj().get_name() == "field";
     };
     while( !q.empty() ) {
         tripoint_abs_omt tpt = q.front();
         if( overmap_buffer.reveal( tpt, 3, filter ) ) {
             if( you->has_trait( trait_SPIRITUAL ) ) {
                 you->add_morale( MORALE_TREE_COMMUNION, 2, 30, 8_hours, 6_hours );
             } else {
                 you->add_morale( MORALE_TREE_COMMUNION, 1, 15, 2_hours, 1_hours );
             }
             if( one_in( 128 ) ) {
                 if( one_in( 256 ) ) {
                     if( you->has_effect( effect_social_dissatisfied ) ) {
                         you->remove_effect( effect_social_dissatisfied );
                     }
                     if( ( you->has_flag( json_flag_SOCIAL1 ) || you->has_flag( json_flag_SOCIAL2 ) ) &&
                         !you->has_effect( effect_social_satisfied ) ) {
                         you->add_effect( effect_social_satisfied, 3_hours, false, 1 );
                     }
                     if( ( you->has_flag( json_flag_ASOCIAL1 ) || you->has_flag( json_flag_ASOCIAL2 ) ) &&
                         !you->has_effect( effect_asocial_dissatisfied ) ) {
                         you->add_effect( effect_asocial_dissatisfied, 3_hours, false, 1 );
                     }
                 }
                 you->add_msg_if_player( "%s", SNIPPET.random_from_category( "tree_communion" ).value_or(
                                             translation() ) );
             }
             return;
         }
         for( const tripoint_abs_omt &neighbor : points_in_radius( tpt, 1 ) ) {
             if( seen.find( neighbor ) != seen.end() ) {
                 continue;
             }
             seen.insert( neighbor );
             if( !overmap_buffer.ter( neighbor ).obj().is_wooded() ) {
                 continue;
             }
             q.push( neighbor );
         }
         q.pop();
     }
     you->add_msg_if_player( m_info, _( "The trees have shown you what they will." ) );
     act->set_to_null();
 }
References _, act, Creature::add_effect(), Character::add_morale(), Character::add_msg_if_player(), effect_asocial_dissatisfied, effect_social_dissatisfied, effect_social_satisfied, filter, Creature::global_omt_location(), Creature::has_effect(), Character::has_flag(), Character::has_trait(), oter_t::is_wooded(), json_flag_ASOCIAL1, json_flag_ASOCIAL2, json_flag_SOCIAL1, json_flag_SOCIAL2, m_good, m_info, MORALE_TREE_COMMUNION, int_id< T >::obj(), calendar::once_every(), one_in(), overmap_buffer, points_in_radius(), snippet_library::random_from_category(), Creature::remove_effect(), overmapbuffer::reveal(), SNIPPET, overmapbuffer::ter(), and trait_SPIRITUAL.
vehicle_deconstruction_do_turn()
void activity_handlers::vehicle_deconstruction_do_turn (player_activity * act, Character * you)
Definition at line 3420 of file activity_handlers.cpp.
 {
     generic_multi_activity_handler( *act, *you );
 }
References act, and generic_multi_activity_handler().
vehicle_finish()
void activity_handlers::vehicle_finish (player_activity * act, Character * you)
Definition at line 2071 of file activity_handlers.cpp.
 {
     map &here = get_map();
     //Grab this now, in case the vehicle gets shifted
     const optional_vpart_position vp = here.veh_at( here.getlocal( tripoint( act->values[0],
                                        act->values[1],
                                        you->posz() ) ) );
     veh_interact::complete_vehicle( *you );
     // complete_vehicle set activity type to NULL if the vehicle
     // was completely dismantled, otherwise the vehicle still exist and
     // is to be examined again.
     if( act->is_null() ) {
         if( npc *guy = dynamic_cast<npc *>( you ) ) {
             guy->revert_after_activity();
             guy->set_moves( 0 );
         }
         return;
     }
     act->set_to_null();
     if( !you->is_npc() ) {
         if( act->values.size() < 7 ) {
             dbg( D_ERROR ) << "game:process_activity: invalid ACT_VEHICLE values: "
                            << act->values.size();
             debugmsg( "process_activity invalid ACT_VEHICLE values:%d",
                       act->values.size() );
         } else {
             if( vp ) {
                 here.invalidate_map_cache( here.get_abs_sub().z() );
                 // TODO: Z (and also where the activity is queued)
                 // Or not, because the vehicle coordinates are dropped anyway
                 if( !resume_for_multi_activities( *you ) ) {
                     point int_p( act->values[ 2 ], act->values[ 3 ] );
                     if( vp->vehicle().is_appliance() ) {
                         g->exam_appliance( vp->vehicle(), int_p );
                     } else {
                         g->exam_vehicle( vp->vehicle(), int_p );
                     }
                 }
                 return;
             } else {
                 dbg( D_ERROR ) << "game:process_activity: ACT_VEHICLE: vehicle not found";
                 debugmsg( "process_activity ACT_VEHICLE: vehicle not found" );
             }
         }
     }
 }
References act, veh_interact::complete_vehicle(), D_ERROR, dbg, debugmsg, g, map::get_abs_sub(), get_map(), map::getlocal(), map::invalidate_map_cache(), Character::is_npc(), Creature::posz(), resume_for_multi_activities(), map::veh_at(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
vehicle_repair_do_turn()
void activity_handlers::vehicle_repair_do_turn (player_activity * act, Character * you)
Definition at line 3425 of file activity_handlers.cpp.
 {
     generic_multi_activity_handler( *act, *you );
 }
References act, and generic_multi_activity_handler().
vibe_do_turn()
void activity_handlers::vibe_do_turn (player_activity * act, Character * you)
Definition at line 2144 of file activity_handlers.cpp.
 {
     //Using a vibrator takes time (10 minutes), not speed
     //Linear increase in morale during action with a small boost at end
     //Deduct 1 battery charge for every minute in use, or vibrator is much less effective
     item &vibrator_item = *act->targets.front();
     if( you->encumb( bodypart_id( "mouth" ) ) >= 30 ) {
         act->moves_left = 0;
         add_msg( m_bad, _( "You have trouble breathing, and stop." ) );
     }
     if( calendar::once_every( 1_minutes ) ) {
         if( vibrator_item.ammo_remaining( you ) > 0 ) {
             vibrator_item.ammo_consume( 1, you->pos(), you );
             you->add_morale( MORALE_FEELING_GOOD, 3, 40 );
             if( vibrator_item.ammo_remaining( you ) == 0 ) {
                 add_msg( m_info, _( "The %s runs out of batteries." ), vibrator_item.tname() );
             }
         } else {
             //twenty minutes to fill
             you->add_morale( MORALE_FEELING_GOOD, 1, 40 );
         }
     }
     // Dead Tired: different kind of relaxation needed
     if( you->get_sleepiness() >= sleepiness_levels::DEAD_TIRED ) {
         act->moves_left = 0;
         add_msg( m_info, _( "You're too tired to continue." ) );
     }
     // Vibrator requires that you be able to move around, stretch, etc, so doesn't play
     // well with roots.  Sorry.  :-(
 }
References _, act, Character::add_morale(), add_msg(), item::ammo_consume(), item::ammo_remaining(), DEAD_TIRED, Character::encumb(), Character::get_sleepiness(), m_bad, m_info, MORALE_FEELING_GOOD, calendar::once_every(), Creature::pos(), and item::tname().
vibe_finish()
void activity_handlers::vibe_finish (player_activity * act, Character * you)
Definition at line 3445 of file activity_handlers.cpp.
 {
     you->add_msg_if_player( m_good, _( "You feel much better." ) );
     you->add_morale( MORALE_FEELING_GOOD, 10, 40 );
     act->set_to_null();
 }
References _, act, Character::add_morale(), Character::add_msg_if_player(), m_good, and MORALE_FEELING_GOOD.
view_recipe_do_turn()
void activity_handlers::view_recipe_do_turn (player_activity * act, Character * you)
Definition at line 2764 of file activity_handlers.cpp.
 {
     if( !you->is_avatar() ) {
         return;
     }
     recipe_id id( act->name );
     std::string itname;
     if( act->index != 0 ) {
         // act->name is recipe_id
         itname = id->result_name();
         if( !you->get_group_available_recipes().contains( &id.obj() ) ) {
             add_msg( m_info, _( "You don't know how to craft the %s!" ), itname );
             return;
         }
         you->craft( std::nullopt, id );
         return;
     }
     // act->name is itype_id
     itype_id item( act->name );
     itname = item->nname( 1U );
     bool is_byproduct = false;  // product or byproduct
     bool can_craft = false;
     // Does a recipe for the item exist?
     for( const auto& [_, r] : recipe_dict ) {
         if( !r.obsolete && ( item == r.result() || r.in_byproducts( item ) ) ) {
             is_byproduct = true;
             // If a recipe exists, does my group know it?
             if( you->get_group_available_recipes().contains( &r ) ) {
                 can_craft = true;
                 break;
             }
         }
     }
     if( !is_byproduct ) {
         add_msg( m_info, _( "You wonder if it's even possible to craft the %s" ), itname );
         return;
     } else if( !can_craft ) {
         add_msg( m_info, _( "You don't know how to craft the %s!" ), itname );
         return;
     }
     std::string filterstring = string_format( "r:%s", itname );
     you->craft( std::nullopt, recipe_id(), filterstring );
 }
References _, act, add_msg(), recipe_subset::contains(), Character::craft(), Character::get_group_available_recipes(), int_id< T >::id(), Creature::is_avatar(), m_info, item::nname(), recipe_dict, and string_format().
view_recipe_finish()
void activity_handlers::view_recipe_finish (player_activity * act, Character * you)
Definition at line 3465 of file activity_handlers.cpp.
 {
     act->set_to_null();
 }
References act.
wait_finish()
void activity_handlers::wait_finish (player_activity * act, Character * you)
Definition at line 2980 of file activity_handlers.cpp.
 {
     you->add_msg_if_player( _( "You finish waiting." ) );
     act->set_to_null();
 }
References _, act, and Character::add_msg_if_player().
wait_npc_finish()
void activity_handlers::wait_npc_finish (player_activity * act, Character * you)
Definition at line 3037 of file activity_handlers.cpp.
 {
     you->add_msg_if_player( _( "%s finishes with you" ), act->str_values[0] );
     act->set_to_null();
 }
References _, act, and Character::add_msg_if_player().
wait_stamina_do_turn()
void activity_handlers::wait_stamina_do_turn (player_activity * act, Character * you)
Definition at line 3043 of file activity_handlers.cpp.
 {
     int stamina_threshold = you->get_stamina_max();
     if( !act->values.empty() ) {
         stamina_threshold = act->values[0];
         // remember initial stamina, only for waiting-with-threshold
         if( act->values.size() == 1 ) {
             act->values.push_back( you->get_stamina() );
         }
     }
     if( you->get_stamina() >= stamina_threshold ) {
         wait_stamina_finish( act, you );
     }
 }
References act, Character::get_stamina(), Character::get_stamina_max(), and wait_stamina_finish().
wait_stamina_finish()
void activity_handlers::wait_stamina_finish (player_activity * act, Character * you)
Definition at line 3058 of file activity_handlers.cpp.
 {
     if( !act->values.empty() ) {
         const int stamina_threshold = act->values[0];
         const int stamina_initial = ( act->values.size() > 1 ) ? act->values[1] : you->get_stamina();
         if( you->get_stamina() < stamina_threshold && you->get_stamina() <= stamina_initial ) {
             debugmsg( "Failed to wait until stamina threshold %d reached, only at %d. You may not be regaining stamina.",
                       act->values.front(), you->get_stamina() );
         }
     } else if( you->get_stamina() < you->get_stamina_max() ) {
         you->add_msg_if_player( _( "You are bored of waiting, so you stop." ) );
     } else {
         you->add_msg_if_player( _( "You finish waiting and feel refreshed." ) );
     }
     act->set_to_null();
 }
References _, act, Character::add_msg_if_player(), debugmsg, Character::get_stamina(), and Character::get_stamina_max().
Referenced by wait_stamina_do_turn().
wait_weather_finish()
void activity_handlers::wait_weather_finish (player_activity * act, Character * you)
Definition at line 2986 of file activity_handlers.cpp.
 {
     you->add_msg_if_player( _( "You finish waiting." ) );
     act->set_to_null();
 }
References _, act, and Character::add_msg_if_player().
Variable Documentation
do_turn_functions
const std::map< activity_id, std::function< void(player_activity *, Character *)> > activity_handlers::do_turn_functions extern
Definition at line 255 of file activity_handlers.cpp.
Referenced by activity_type::call_do_turn(), and activity_type::check_consistency().
finish_functions
const std::map< activity_id, std::function< void(player_activity *, Character *)> > activity_handlers::finish_functions extern
Definition at line 305 of file activity_handlers.cpp.
Referenced by activity_type::call_finish(), and activity_type::check_consistency().