Cataclysm DDA: anonymous_namespace{do_turn.cpp} Namespace Reference
anonymous_namespace{do_turn.cpp} Namespace Reference
Functions
void monmove ()
void overmap_npc_move ()
Function Documentation
monmove()
void anonymous_namespace{do_turn.cpp}::monmove ()
Definition at line 263 of file do_turn.cpp.
 {
     g->cleanup_dead();
     map &m = get_map();
     avatar &u = get_avatar();
     for( monster &critter : g->all_monsters() ) {
         // Critters in impassable tiles get pushed away, unless it's not impassable for them
         if( !critter.is_dead() && m.impassable( critter.pos() ) && !critter.can_move_to( critter.pos() ) ) {
             dbg( D_ERROR ) << "game:monmove: " << critter.name()
                            << " can't move to its location!  (" << critter.posx()
                            << ":" << critter.posy() << ":" << critter.posz() << "), "
                            << m.tername( critter.pos() );
             add_msg_debug( debugmode::DF_MONSTER, "%s can't move to its location!  (%d,%d,%d), %s",
                            critter.name(),
                            critter.posx(), critter.posy(), critter.posz(), m.tername( critter.pos() ) );
             bool okay = false;
             for( const tripoint &dest : m.points_in_radius( critter.pos(), 3 ) ) {
                 if( critter.can_move_to( dest ) && g->is_empty( dest ) ) {
                     critter.setpos( dest );
                     okay = true;
                     break;
                 }
             }
             if( !okay ) {
                 // die of "natural" cause (overpopulation is natural)
                 critter.die( nullptr );
             }
         }
         if( !critter.is_dead() ) {
             critter.process_turn();
         }
         m.creature_in_field( critter );
         if( calendar::once_every( 1_days ) ) {
             if( critter.has_flag( mon_flag_MILKABLE ) ) {
                 critter.refill_udders();
             }
             critter.try_biosignature();
             critter.try_reproduce();
         }
         while( critter.get_moves() > 0 && !critter.is_dead() && !critter.has_effect( effect_ridden ) ) {
             critter.made_footstep = false;
             // Controlled critters don't make their own plans
             if( !critter.has_effect( effect_controlled ) ) {
                 // Formulate a path to follow
                 critter.plan();
             } else {
                 critter.set_moves( 0 );
                 break;
             }
             critter.move(); // Move one square, possibly hit u
             critter.process_triggers();
             m.creature_in_field( critter );
         }
         if( !critter.is_dead() &&
             u.has_active_bionic( bio_alarm ) &&
             u.get_power_level() >= bio_alarm->power_trigger &&
             rl_dist( u.pos(), critter.pos() ) <= 5 &&
             !critter.is_hallucination() ) {
             u.mod_power_level( -bio_alarm->power_trigger );
             add_msg( m_warning, _( "Your motion alarm goes off!" ) );
             g->cancel_activity_or_ignore_query( distraction_type::motion_alarm,
                                                 _( "Your motion alarm goes off!" ) );
             if( u.has_effect( effect_sleep ) ) {
                 u.wake_up();
             }
         }
     }
     g->cleanup_dead();
     // The remaining monsters are all alive, but may be outside of the reality bubble.
     // If so, despawn them. This is not the same as dying, they will be stored for later and the
     // monster::die function is not called.
     g->despawn_nonlocal_monsters();
     // Now, do active NPCs.
     for( npc &guy : g->all_npcs() ) {
         int turns = 0;
         int real_count = 0;
         const int count_limit = std::max( 10, guy.get_moves() / 64 );
         if( guy.is_mounted() ) {
             guy.check_mount_is_spooked();
         }
         m.creature_in_field( guy );
         if( !guy.has_effect( effect_npc_suspend ) ) {
             guy.process_turn();
         }
         while( !guy.is_dead() && ( !guy.in_sleep_state() || guy.activity.id() == ACT_OPERATION ) &&
                guy.get_moves() > 0 && turns < 10 ) {
             const int moves = guy.get_moves();
             const bool has_destination = guy.has_destination_activity();
             guy.move();
             if( moves == guy.get_moves() ) {
                 // Count every time we exit npc::move() without spending any moves.
                 real_count++;
                 if( has_destination == guy.has_destination_activity() || real_count > count_limit ) {
                     turns++;
                 }
             }
             // Turn on debug mode when in infinite loop
             // It has to be done before the last turn, otherwise
             // there will be no meaningful debug output.
             if( turns == 9 ) {
                 debugmsg( "NPC '%s' entered infinite loop, npc activity id: '%s'",
                           guy.get_name(), guy.activity.id().str() );
             }
         }
         // If we spun too long trying to decide what to do (without spending moves),
         // Invoke cognitive suspension to prevent an infinite loop.
         if( turns == 10 ) {
             add_msg( _( "%s faints!" ), guy.get_name() );
             guy.reboot();
         }
         if( !guy.is_dead() ) {
             guy.npc_update_body();
         }
     }
     g->cleanup_dead();
 }
References _, ACT_OPERATION, add_msg(), add_msg_debug, bio_alarm, map::creature_in_field(), D_ERROR, dbg, debugmsg, debugmode::DF_MONSTER, effect_controlled, effect_npc_suspend, effect_ridden, effect_sleep, g, get_avatar(), get_map(), map::impassable(), m_warning, max(), mon_flag_MILKABLE, motion_alarm, okay, calendar::once_every(), map::points_in_radius(), bionic_data::power_trigger, rl_dist(), map::tername(), and u.
overmap_npc_move()
void anonymous_namespace{do_turn.cpp}::overmap_npc_move ()
Definition at line 389 of file do_turn.cpp.
 {
     avatar &u = get_avatar();
     std::vector<npc *> travelling_npcs;
     static constexpr int move_search_radius = 600;
     for( auto &elem : overmap_buffer.get_npcs_near_player( move_search_radius ) ) {
         if( !elem ) {
             continue;
         }
         npc *npc_to_add = elem.get();
         if( ( !npc_to_add->is_active() || rl_dist( u.pos(), npc_to_add->pos() ) > SEEX * 2 ) &&
             npc_to_add->mission == NPC_MISSION_TRAVELLING ) {
             travelling_npcs.push_back( npc_to_add );
         }
     }
     bool npcs_need_reload = false;
     for( npc *&elem : travelling_npcs ) {
         if( elem->has_omt_destination() ) {
             if( !elem->omt_path.empty() ) {
                 if( rl_dist( elem->omt_path.back(), elem->global_omt_location() ) > 2 ) {
                     // recalculate path, we got distracted doing something else probably
                     elem->omt_path.clear();
                 } else if( elem->omt_path.back() == elem->global_omt_location() ) {
                     elem->omt_path.pop_back();
                 }
             }
             if( elem->omt_path.empty() ) {
                 elem->omt_path = overmap_buffer.get_travel_path( elem->global_omt_location(), elem->goal,
                                  overmap_path_params::for_npc() );
                 if( elem->omt_path.empty() ) { // goal is unreachable, or already reached goal, reset it
                     elem->goal = npc::no_goal_point;
                 }
             } else {
                 elem->travel_overmap( elem->omt_path.back() );
                 npcs_need_reload = true;
             }
         }
         if( !elem->has_omt_destination() && calendar::once_every( 1_hours ) && one_in( 3 ) ) {
             // travelling destination is reached/not set, try different one
             elem->set_omt_destination();
         }
     }
     if( npcs_need_reload ) {
         g->reload_npcs();
     }
 }
References overmap_path_params::for_npc(), g, get_avatar(), overmapbuffer::get_npcs_near_player(), overmapbuffer::get_travel_path(), npc::is_active(), npc::mission, npc::no_goal_point, NPC_MISSION_TRAVELLING, Character::omt_path, calendar::once_every(), one_in(), overmap_buffer, Creature::pos(), rl_dist(), SEEX, and u.