Cataclysm DDA: Messages Namespace Reference
Messages Namespace Reference
Classes
class dialog
Functions
std::vector< std::pair< std::string, std::string > > recent_messages (size_t count)
bool has_debug_filter (debugmode::debug_filter type)
void add_msg (std::string msg)
void add_msg (const game_message_params &params, std::string msg)
void clear_messages ()
void deactivate ()
size_t size ()
bool has_undisplayed_messages ()
void display_messages ()
void display_messages (const catacurses::window &ipk_target, int left, int top, int right, int bottom)
void serialize (JsonOut &json)
void deserialize (const JsonObject &json)
Function Documentation
add_msg() [1/2]
void Messages::add_msg (const game_message_params & params, std::string msg)
Definition at line 459 of file messages.cpp.
 {
     player_messages.add_msg_string( std::move( msg ), params );
 }
References anonymous_namespace{messages.cpp}::messages_impl::add_msg_string(), and anonymous_namespace{messages.cpp}::player_messages.
add_msg() [2/2]
void Messages::add_msg (std::string msg)
Definition at line 454 of file messages.cpp.
 {
     player_messages.add_msg_string( std::move( msg ) );
 }
References anonymous_namespace{messages.cpp}::messages_impl::add_msg_string(), and anonymous_namespace{messages.cpp}::player_messages.
Referenced by add_msg(), Character::add_msg_if_player(), add_msg_if_player_sees(), Character::add_msg_player_or_npc(), and Character::add_msg_player_or_say().
clear_messages()
void Messages::clear_messages ()
Definition at line 464 of file messages.cpp.
 {
     player_messages.messages.clear();
     player_messages.active = true;
 }
References anonymous_namespace{messages.cpp}::messages_impl::active, anonymous_namespace{messages.cpp}::messages_impl::messages, and anonymous_namespace{messages.cpp}::player_messages.
Referenced by game::setup().
deactivate()
void Messages::deactivate ()
Definition at line 470 of file messages.cpp.
 {
     player_messages.active = false;
 }
References anonymous_namespace{messages.cpp}::messages_impl::active, and anonymous_namespace{messages.cpp}::player_messages.
Referenced by game::is_game_over().
deserialize()
void Messages::deserialize (const JsonObject & json)
Definition at line 443 of file messages.cpp.
 {
     if( !json.has_member( "player_messages" ) ) {
         return;
     }
     JsonObject obj = json.get_object( "player_messages" );
     obj.read( "messages", player_messages.messages );
     obj.read( "curmes", player_messages.curmes );
 }
References anonymous_namespace{messages.cpp}::messages_impl::curmes, JsonObject::get_object(), JsonObject::has_member(), anonymous_namespace{messages.cpp}::messages_impl::messages, int_id< T >::obj(), and anonymous_namespace{messages.cpp}::player_messages.
Referenced by game::unserialize().
display_messages() [1/2]
void Messages::display_messages ()
Definition at line 914 of file messages.cpp.
 {
     dialog dlg;
     dlg.run();
     player_messages.curmes = calendar::turn;
 }
References anonymous_namespace{messages.cpp}::messages_impl::curmes, anonymous_namespace{messages.cpp}::player_messages, Messages::dialog::run(), and calendar::turn.
Referenced by game::death_screen(), game::do_regular_action(), draw_messages(), handle_key_blocking_activity(), read_activity_actor::npc_read(), and advanced_inventory::redraw_sidebar().
display_messages() [2/2]
void Messages::display_messages (const catacurses::window & ipk_target, int left, int top, int right, int bottom)
Definition at line 921 of file messages.cpp.
 {
     if( !size() ) {
         return;
     }
     const int maxlength = right - left;
     int line = log_from_top ? top : bottom;
     if( log_from_top ) {
         for( int i = size() - 1; i >= 0; --i ) {
             if( line > bottom ) {
                 break;
             }
             const game_message &m = player_messages.messages[i];
             if( message_exceeds_ttl( m ) ) {
                 break;
             }
             const nc_color col = m.get_color( player_messages.curmes );
             std::string message_text = m.get_with_count();
             if( !m.is_recent( player_messages.curmes ) ) {
                 message_text = remove_color_tags( message_text );
             }
             for( const std::string &folded : foldstring( message_text, maxlength ) ) {
                 if( line > bottom ) {
                     break;
                 }
                 // Redrawing line to ensure new messages similar to previous
                 // messages will not be missed by screen readers
                 wredrawln( ipk_target, line, 1 );
                 nc_color col_out = col;
                 print_colored_text( ipk_target, point( left, line++ ), col_out, col, folded );
             }
         }
     } else {
         for( int i = size() - 1; i >= 0; --i ) {
             if( line < top ) {
                 break;
             }
             const game_message &m = player_messages.messages[i];
             if( message_exceeds_ttl( m ) ) {
                 break;
             }
             if( m.is_in_cooldown() ) {
                 // message is still (or was at some point) into a cooldown period.
                 continue;
             }
             const nc_color col = m.get_color( player_messages.curmes );
             std::string message_text = m.get_with_count();
             if( !m.is_recent( player_messages.curmes ) ) {
                 message_text = remove_color_tags( message_text );
             }
             const auto folded_strings = foldstring( message_text, maxlength );
             const auto folded_rend = folded_strings.rend();
             for( auto string_iter = folded_strings.rbegin();
                  string_iter != folded_rend && line >= top; ++string_iter, line-- ) {
                 // Redrawing line to ensure new messages similar to previous
                 // messages will not be missed by screen readers
                 wredrawln( ipk_target, line, 1 );
                 nc_color col_out = col;
                 print_colored_text( ipk_target, point( left, line ), col_out, col, *string_iter );
             }
         }
     }
     player_messages.curmes = calendar::turn;
 }
References anonymous_namespace{messages.cpp}::messages_impl::curmes, foldstring(), line(), log_from_top, anonymous_namespace{messages.cpp}::message_exceeds_ttl(), anonymous_namespace{messages.cpp}::messages_impl::messages, anonymous_namespace{messages.cpp}::player_messages, print_colored_text(), remove_color_tags(), size(), calendar::turn, and catacurses::wredrawln().
has_debug_filter()
bool Messages::has_debug_filter (debugmode::debug_filter type)
Definition at line 429 of file messages.cpp.
 {
     return debug_mode && debugmode::enabled_filters.count( type ) == 1;
 }
References debug_mode, and debugmode::enabled_filters.
has_undisplayed_messages()
bool Messages::has_undisplayed_messages ()
Definition at line 480 of file messages.cpp.
 {
     return player_messages.has_undisplayed_messages();
 }
References anonymous_namespace{messages.cpp}::messages_impl::has_undisplayed_messages(), and anonymous_namespace{messages.cpp}::player_messages.
recent_messages()
std::vector< std::pair< std::string, std::string > > Messages::recent_messages (size_t count)
Definition at line 424 of file messages.cpp.
 {
     return player_messages.recent_messages( count );
 }
References anonymous_namespace{messages.cpp}::player_messages, and anonymous_namespace{messages.cpp}::messages_impl::recent_messages().
Referenced by memorial_logger::write_text_memorial().
serialize()
void Messages::serialize (JsonOut & json)
Definition at line 434 of file messages.cpp.
 {
     json.member( "player_messages" );
     json.start_object();
     json.member( "messages", player_messages.messages );
     json.member( "curmes", player_messages.curmes );
     json.end_object();
 }
References anonymous_namespace{messages.cpp}::messages_impl::curmes, JsonOut::end_object(), JsonOut::member(), anonymous_namespace{messages.cpp}::messages_impl::messages, anonymous_namespace{messages.cpp}::player_messages, and JsonOut::start_object().
Referenced by game::serialize().
size()
size_t Messages::size ()
Definition at line 475 of file messages.cpp.
 {
     return player_messages.messages.size();
 }
References anonymous_namespace{messages.cpp}::messages_impl::messages, and anonymous_namespace{messages.cpp}::player_messages.
Referenced by display_messages(), and Messages::dialog::init().