Cataclysm DDA: anonymous_namespace{iexamine.cpp} Namespace Reference
anonymous_namespace{iexamine.cpp} Namespace Reference
Classes
class atm_menu
Implements iexamine::atm(...)
struct elevator_vehicles
Functions
int _get_rot_delta (tripoint_abs_omt const &this_omt, tripoint_abs_omt const &that_omt)
tripoint _rotate_point_sm (tripoint const &p, int erot, tripoint const &orig)
int _choose_elevator_destz (tripoint const &examp, tripoint_abs_omt const &this_omt, tripoint const &sm_orig)
elevator_vehicles _get_vehicles_on_elevator (std::vector< tripoint > const &elevator)
Variables
constexpr int uilist_positive = 10000
Function Documentation
_choose_elevator_destz()
int anonymous_namespace{iexamine.cpp}::_choose_elevator_destz (tripoint const & examp, tripoint_abs_omt const & this_omt, tripoint const & sm_orig)
Definition at line 1224 of file iexamine.cpp.
 {
     map &here = get_map();
     uilist choice;
     choice.title = _( "Select destination floor" );
     for( int z = OVERMAP_HEIGHT; z >= -OVERMAP_DEPTH; z-- ) {
         tripoint_abs_omt const that_omt( this_omt.xy(), z );
         tripoint const zp =
             _rotate_point_sm( { examp.xy(), z }, _get_rot_delta( this_omt, that_omt ), sm_orig );
         if( here.ter( zp )->has_examine( iexamine::elevator ) ) {
             std::string const omt_name = overmap_buffer.ter_existing( that_omt )->get_name();
             std::string const name = string_format(
                                          "%i %s%s", z, omt_name, z == examp.z ? _( " (this floor)" ) : std::string() );
             choice.addentry( z + uilist_positive, z != examp.z, MENU_AUTOASSIGN, name );
         }
     }
     choice.query();
     return choice.ret;
 }
References _, _get_rot_delta(), _rotate_point_sm(), uilist::addentry(), iexamine::elevator(), get_map(), oter_t::get_name(), map_data_common_t::has_examine(), MENU_AUTOASSIGN, om_direction::name(), overmap_buffer, OVERMAP_DEPTH, OVERMAP_HEIGHT, uilist::query(), uilist::ret, string_format(), map::ter(), overmapbuffer::ter_existing(), uilist::title, uilist_positive, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), tripoint::xy(), and tripoint::z.
Referenced by iexamine::elevator().
_get_rot_delta()
int anonymous_namespace{iexamine.cpp}::_get_rot_delta (tripoint_abs_omt const & this_omt, tripoint_abs_omt const & that_omt)
Definition at line 1207 of file iexamine.cpp.
 {
     om_direction::type const this_dir = overmap_buffer.ter( that_omt )->get_dir();
     om_direction::type const that_dir = overmap_buffer.ter( this_omt )->get_dir();
     int const diff = static_cast<int>( this_dir ) - static_cast<int>( that_dir );
     return diff >= 0 ? diff : 4 + diff;
 }
References oter_t::get_dir(), overmap_buffer, and overmapbuffer::ter().
Referenced by _choose_elevator_destz(), and iexamine::elevator().
_get_vehicles_on_elevator()
elevator_vehicles anonymous_namespace{iexamine.cpp}::_get_vehicles_on_elevator (std::vector< tripoint > const & elevator)
Definition at line 1251 of file iexamine.cpp.
 {
     std::vector<vehicle *> ret;
     VehicleList const vehs = get_map().get_vehicles();
     for( wrapped_vehicle const &v : vehs ) {
         bool inbounds = true;
         bool can_block = false;
         for( const vpart_reference &vp : v.v->get_all_parts() ) {
             tripoint const p = v.pos + vp.part().precalc[0];
             auto const eit = std::find( elevator.cbegin(), elevator.cend(), p );
             inbounds &= eit != elevator.cend();
             if( !inbounds ) {
                 break;
             }
             can_block = true;
         }
         if( inbounds ) {
             ret.emplace_back( v.v );
         } else if( can_block ) {
             return { true, { v.v } };
         }
     }
     return { false, ret };
 }
References iexamine::elevator(), get_map(), map::get_vehicles(), and cata::hash64_detail::ret.
Referenced by iexamine::elevator().
_rotate_point_sm()
tripoint anonymous_namespace{iexamine.cpp}::_rotate_point_sm (tripoint const & p, int erot, tripoint const & orig)
Definition at line 1215 of file iexamine.cpp.
 {
     tripoint const p_sm( p - orig.xy() );
     tripoint const rd = p_sm.rotate( erot, { SEEX * 2, SEEY * 2 } );
     return tripoint{ rd + orig.xy() };
 }
References tripoint::rotate(), SEEX, SEEY, and tripoint::xy().
Referenced by _choose_elevator_destz().
Variable Documentation
uilist_positive
constexpr int anonymous_namespace{iexamine.cpp}::uilist_positive = 10000 constexpr
Definition at line 1222 of file iexamine.cpp.
Referenced by _choose_elevator_destz(), and iexamine::elevator().