Cataclysm DDA: anonymous_namespace{bionics_ui.cpp} Namespace Reference
anonymous_namespace{bionics_ui.cpp} Namespace Reference
Classes
struct bionic_sort_less
Typedefs
using sorted_bionics = cata::flat_set< bionic *, bionic_sort_less >
Enumerations
enum bionic_tab_mode { TAB_ACTIVE , TAB_PASSIVE }
enum bionic_menu_mode { ACTIVATING , EXAMINING , REASSIGNING }
Functions
std::string sort_mode_str (bionic_ui_sort_mode mode)
bool is_power_cbm (const bionic_data &data)
units::energy bionic_sort_power (const bionic_data &lbd)
sorted_bionics filtered_bionics (bionic_collection &all_bionics, bionic_tab_mode mode)
bionic_ui_sort_mode pick_sort_mode ()
Typedef Documentation
sorted_bionics
using anonymous_namespace{bionics_ui.cpp}::sorted_bionics = typedef cata::flat_set<bionic *, bionic_sort_less>
Definition at line 122 of file bionics_ui.cpp.
Enumeration Type Documentation
bionic_menu_mode
enum anonymous_namespace{bionics_ui.cpp}::bionic_menu_mode
Enumerator
ACTIVATING
EXAMINING
REASSIGNING
Definition at line 62 of file bionics_ui.cpp.
                       {
     ACTIVATING,
     EXAMINING,
     REASSIGNING
 };
bionic_tab_mode
enum anonymous_namespace{bionics_ui.cpp}::bionic_tab_mode
Enumerator
TAB_ACTIVE
TAB_PASSIVE
Definition at line 58 of file bionics_ui.cpp.
                      {
     TAB_ACTIVE,
     TAB_PASSIVE
 };
Function Documentation
bionic_sort_power()
units::energy anonymous_namespace{bionics_ui.cpp}::bionic_sort_power (const bionic_data & lbd)
Definition at line 89 of file bionics_ui.cpp.
 {
     return is_power_cbm( lbd ) ? units::energy( -1_kJ * lbd.fuel_efficiency ) :
            lbd.power_activate + lbd.power_over_time;
 }
References bionic_data::fuel_efficiency, is_power_cbm(), bionic_data::power_activate, and bionic_data::power_over_time.
Referenced by anonymous_namespace{bionics_ui.cpp}::bionic_sort_less::operator()().
filtered_bionics()
sorted_bionics anonymous_namespace{bionics_ui.cpp}::filtered_bionics (bionic_collection & all_bionics, bionic_tab_mode mode)
Definition at line 124 of file bionics_ui.cpp.
 {
     sorted_bionics filtered_entries;
     for( bionic &elem : all_bionics ) {
         if( ( mode == TAB_ACTIVE ) == elem.id->activated ) {
             filtered_entries.insert( &elem );
         }
     }
     return filtered_entries;
 }
References cata::flat_set< T, Compare, Data >::insert(), and TAB_ACTIVE.
Referenced by avatar::power_bionics().
is_power_cbm()
bool anonymous_namespace{bionics_ui.cpp}::is_power_cbm (const bionic_data & data)
Definition at line 84 of file bionics_ui.cpp.
 {
     return !data.fuel_opts.empty() || data.is_remote_fueled;
 }
References bionic_data::fuel_opts, and bionic_data::is_remote_fueled.
Referenced by bionic_sort_power().
pick_sort_mode()
bionic_ui_sort_mode anonymous_namespace{bionics_ui.cpp}::pick_sort_mode ()
Definition at line 136 of file bionics_ui.cpp.
 {
     uilist tmenu;
     tmenu.text = _( "Sort bionics by:" );
     tmenu.addentry( 1, true, 'p', sort_mode_str( bionic_ui_sort_mode::POWER ) );
     tmenu.addentry( 2, true, 'n', sort_mode_str( bionic_ui_sort_mode::NAME ) );
     tmenu.addentry( 3, true, 'i', sort_mode_str( bionic_ui_sort_mode::INVLET ) );
     tmenu.addentry( 4, true, 'o', sort_mode_str( bionic_ui_sort_mode::NONE ) );
     tmenu.query();
     switch( tmenu.ret ) {
         case 1:
             return bionic_ui_sort_mode::POWER;
         case 2:
             return bionic_ui_sort_mode::NAME;
         case 3:
             return bionic_ui_sort_mode::INVLET;
         case 4:
             return bionic_ui_sort_mode::NONE;
     }
     return bionic_ui_sort_mode::NONE;
 }
References _, uilist::addentry(), INVLET, NAME, NONE, POWER, uilist::query(), uilist::ret, sort_mode_str(), and uilist::text.
Referenced by avatar::power_bionics().
sort_mode_str()
std::string anonymous_namespace{bionics_ui.cpp}::sort_mode_str (bionic_ui_sort_mode mode)
Definition at line 68 of file bionics_ui.cpp.
 {
     switch( mode ) {
         case bionic_ui_sort_mode::nsort:
         case bionic_ui_sort_mode::NONE:
             return _( "None" );
         case bionic_ui_sort_mode::POWER:
             return _( "Power usage" );
         case bionic_ui_sort_mode::NAME:
             return _( "Name" );
         case bionic_ui_sort_mode::INVLET:
             return _( "Manual (shortcut)" );
     }
     return "error";
 }
References _, INVLET, NAME, NONE, nsort, and POWER.
Referenced by draw_bionics_titlebar(), and pick_sort_mode().