Cataclysm DDA: npc_trading Namespace Reference
npc_trading Namespace Reference
Functions
bool pay_npc (npc &np, int cost)
int bionic_install_price (Character &installer, Character &patient, item_location const &bionic)
int adjusted_price (item const *it, int amount, Character const &buyer, Character const &seller)
int trading_price (Character const &buyer, Character const &seller, trade_selector::entry_t const &it)
int calc_npc_owes_you (const npc &np, int your_balance)
bool npc_will_accept_trade (npc const &np, int your_balance)
bool npc_can_fit_items (npc const &np, trade_selector::select_t const &to_trade)
void update_npc_owed (npc &np, int your_balance, int your_sale_value)
int cash_to_favor (const npc &, int cash)
std::list< item > transfer_items (trade_selector::select_t &stuff, Character &giver, Character &receiver, std::list< item_location * > &from_map, bool use_escrow)
double net_price_adjustment (const Character &buyer, const Character &seller)
bool trade (npc &p, int cost, const std::string &deal)
std::vector< item_pricing > init_selling (npc &p)
Function Documentation
adjusted_price()
int npc_trading::adjusted_price (item const * it, int amount, Character const & buyer, Character const & seller)
Definition at line 162 of file npctrade.cpp.
 {
     npc const *faction_party = buyer.is_npc() ? buyer.as_npc() : seller.as_npc();
     faction_price_rule const *const fpr = faction_party->get_price_rules( *it );
     double price = it->price_no_contents( true, fpr != nullptr ? fpr->price : std::nullopt );
     if( fpr != nullptr ) {
         price *= fpr->premium;
         if( seller.is_npc() ) {
             price *= fpr->markup;
         }
     }
     if( it->count_by_charges() && amount >= 0 ) {
         price *= static_cast<double>( amount ) / it->charges;
     }
     if( buyer.is_npc() ) {
         price = buyer.as_npc()->value( *it, price );
     } else if( seller.is_npc() ) {
         price = seller.as_npc()->value( *it, price );
     }
     if( fpr != nullptr && fpr->fixed_adj.has_value() ) {
         double const fixed_adj = fpr->fixed_adj.value();
         price *= 1 + ( seller.is_npc() ? fixed_adj : -fixed_adj );
     } else {
         double const adjust = npc_trading::net_price_adjustment( buyer, seller );
         price *= 1 + 0.25 * adjust;
     }
     return static_cast<int>( std::ceil( price ) );
 }
References Creature::as_npc(), ceil(), item::charges, item::count_by_charges(), faction_price_rule::fixed_adj, npc::get_price_rules(), Character::is_npc(), faction_price_rule::markup, net_price_adjustment(), faction_price_rule::premium, faction_price_rule::price, item::price_no_contents(), and npc::value().
Referenced by anonymous_namespace{npctrade.cpp}::_trading_price().
bionic_install_price()
int npc_trading::bionic_install_price (Character & installer, Character & patient, item_location const & bionic)
Definition at line 153 of file npctrade.cpp.
 {
     return bionic->price( true ) * 2 +
            ( bionic->is_owned_by( patient )
              ? 0
              : npc_trading::trading_price( patient, installer, { bionic, 1 } ) );
 }
References trading_price().
Referenced by bionic_install_common(), bionic_install_surgeon_preset::get_denial(), and bionic_install_surgeon_preset::get_money_amount().
calc_npc_owes_you()
int npc_trading::calc_npc_owes_you (const npc & np, int your_balance)
Definition at line 248 of file npctrade.cpp.
 {
     // Friends don't hold debts against friends.
     if( np.will_exchange_items_freely() ) {
         return 0;
     }
     // If they're going to owe you more than before, and it's more than they're willing
     // to owe, then cap the amount owed at the present level or their willingness to owe
     // (whichever is bigger).
     //
     // When could they owe you more than max_willing_to_owe? It could be from quest rewards,
     // when they were less angry, or from when you were better friends.
     if( your_balance > np.op_of_u.owed && your_balance > np.max_willing_to_owe() ) {
         return std::max( np.op_of_u.owed, np.max_willing_to_owe() );
     }
     // Fair's fair. NPC will remember this debt (or credit they've extended)
     return your_balance;
 }
References max(), npc::max_willing_to_owe(), npc::op_of_u, npc_opinion::owed, and npc::will_exchange_items_freely().
Referenced by trade_ui::_confirm_trade(), and update_npc_owed().
cash_to_favor()
int npc_trading::cash_to_favor (const npc & , int cash)
Definition at line 416 of file npctalk.cpp.
 {
     // TODO: It should affect different NPCs to a different degree
     // Square root of mission value in dollars
     // ~31 for zed mom, 50 for horde master, ~63 for plutonium cells
     double scaled_mission_val = std::sqrt( cash / 100.0 );
     return roll_remainder( scaled_mission_val );
 }
References roll_remainder(), and sqrt().
Referenced by talker_npc::cash_to_favor(), and talk_function::mission_success().
init_selling()
std::vector< item_pricing > npc_trading::init_selling (npc & p)
Definition at line 108 of file npctrade.cpp.
 {
     std::vector<item_pricing> result;
     const std::vector<item *> inv_all = np.items_with( []( const item & it ) {
         return !it.made_of( phase_id::LIQUID );
     } );
     for( item *i : inv_all ) {
         item &it = *i;
         int val = np.value( it );
         // FIXME: this item_location is a hack
         if( np.wants_to_sell( item_location{ np, i }, val ).success() ) {
             result.emplace_back( np, it, val, static_cast<int>( it.count() ) );
         }
     }
     item_location weapon = np.get_wielded_item();
     if(
         np.will_exchange_items_freely() && weapon && !weapon->has_flag( json_flag_NO_UNWIELD )
     ) {
         result.emplace_back( np, *weapon, np.value( *weapon ), false );
     }
     return result;
 }
References item::count(), Character::get_wielded_item(), item::has_flag(), visitable::items_with(), json_flag_NO_UNWIELD, LIQUID, item::made_of(), npc::value(), npc::wants_to_sell(), and npc::will_exchange_items_freely().
Referenced by talk_function::give_equipment_allowance().
net_price_adjustment()
double npc_trading::net_price_adjustment (const Character & buyer, const Character & seller)
NPC Intelligence slightly increases bartering price changes, relative to your INT NPC Barter increases bartering price changes, relative to your BARTER Intelligence slightly increases bartering price changes, relative to NPC INT Barter increases bartering price changes, relative to NPC BARTER
Definition at line 134 of file npctrade.cpp.
 {
     // Adjust the prices based on your social skill.
     // cap adjustment so nothing is ever sold below value
     ///\EFFECT_INT_NPC slightly increases bartering price changes, relative to your INT
     ///\EFFECT_BARTER_NPC increases bartering price changes, relative to your BARTER
     ///\EFFECT_INT slightly increases bartering price changes, relative to NPC INT
     ///\EFFECT_BARTER increases bartering price changes, relative to NPC BARTER
     int const int_diff = seller.int_cur - buyer.int_cur;
     double const int_adj = 1 + 0.05 * std::min( 19, std::abs( int_diff ) );
     double const soc_adj = price_adjustment( round( seller.get_skill_level( skill_speech ) -
                            buyer.get_skill_level( skill_speech ) ) );
     double const adjust = int_diff >= 0 ? int_adj * soc_adj : soc_adj / int_adj;
     return seller.is_npc() ? adjust : -1 / adjust;
 }
References abs(), Character::get_skill_level(), Character::int_cur, Character::is_npc(), min(), price_adjustment(), round(), and skill_speech.
Referenced by adjusted_price().
npc_can_fit_items()
bool npc_trading::npc_can_fit_items (npc const & np, trade_selector::select_t const & to_trade)
Definition at line 343 of file npctrade.cpp.
 {
     std::vector<item> avail_pockets = np.worn.available_pockets();
     if( !to_trade.empty() && avail_pockets.empty() ) {
         return false;
     }
     for( trade_selector::entry_t const &it : to_trade ) {
         bool item_stored = false;
         for( item &pkt : avail_pockets ) {
             const units::volume pvol = pkt.max_containable_volume();
             const item &i = *it.first;
             if( pkt.can_holster( i ) || ( pkt.can_contain( i ).success() && pvol > i.volume() ) ) {
                 pkt.put_in( i, pocket_type::CONTAINER );
                 item_stored = true;
                 break;
             }
         }
         if( !item_stored && !np.can_wear( *it.first, false ).success() ) {
             return false;
         }
     }
     return true;
 }
References outfit::available_pockets(), Character::can_wear(), CONTAINER, item::put_in(), ret_val_common::success(), item::volume(), and Character::worn.
Referenced by trade_ui::_confirm_trade().
npc_will_accept_trade()
bool npc_trading::npc_will_accept_trade (npc const & np, int your_balance)
Definition at line 339 of file npctrade.cpp.
 {
     return np.will_exchange_items_freely() || your_balance + np.max_credit_extended() >= 0;
 }
References npc::max_credit_extended(), and npc::will_exchange_items_freely().
Referenced by trade_ui::_confirm_trade(), and trade_ui::_draw_header().
pay_npc()
bool npc_trading::pay_npc (npc & np, int cost)
Definition at line 1062 of file npctalk_funcs.cpp.
 {
     if( np.op_of_u.owed >= cost ) {
         np.op_of_u.owed -= cost;
         return true;
     }
     return npc_trading::trade( np, cost, _( "Pay:" ) );
 }
References _, npc::op_of_u, npc_opinion::owed, and trade().
Referenced by bionic_install_common(), bionic_remove_common(), talker_npc::buy_from(), talker_avatar::buy_monster(), and talk_function::start_training_gen().
trade()
bool npc_trading::trade (npc & p, int cost, const std::string & deal)
Definition at line 278 of file npctrade.cpp.
 {
     np.shop_restock();
     //np.drop_items( np.weight_carried() - np.weight_capacity(),
     //               np.volume_carried() - np.volume_capacity() );
     np.drop_invalid_inventory();
     std::unique_ptr<trade_ui> tradeui = std::make_unique<trade_ui>( get_avatar(), np, cost, deal );
     trade_ui::trade_result_t trade_result = tradeui->perform_trade();
     if( trade_result.traded ) {
         tradeui.reset();
         std::list<item_location *> from_map;
         std::list<item> escrow;
         avatar &player_character = get_avatar();
         // Movement of items in 3 steps: player to escrow - npc to player - escrow to npc.
         escrow = npc_trading::transfer_items( trade_result.items_you, player_character, np, from_map,
                                               true );
         npc_trading::transfer_items( trade_result.items_trader, np, player_character, from_map, false );
         // Now move items from escrow to the npc. Keep the weapon wielded.
         if( np.is_shopkeeper() ) {
             distribute_items_to_npc_zones( escrow, np );
         } else {
             for( const item &i : escrow ) {
                 np.i_add( i, true, nullptr, nullptr, true, false );
             }
         }
         for( item_location *loc_ptr : from_map ) {
             if( !loc_ptr ) {
                 continue;
             }
             item *it = loc_ptr->get_item();
             if( !it ) {
                 continue;
             }
             if( it->has_var( "trade_charges" ) && it->count_by_charges() ) {
                 it->charges -= static_cast<int>( it->get_var( "trade_charges", 0 ) );
                 if( it->charges <= 0 ) {
                     loc_ptr->remove_item();
                 } else {
                     it->erase_var( "trade_charges" );
                 }
             } else if( it->has_var( "trade_amount" ) ) {
                 loc_ptr->remove_item();
             }
         }
         // NPCs will remember debts, to the limit that they'll extend credit or previous debts
         if( !np.will_exchange_items_freely() ) {
             player_character.cash -= trade_result.delta_bank;
             update_npc_owed( np, trade_result.balance, trade_result.value_you );
             player_character.practice( skill_speech, trade_result.value_you / 10000 );
         }
     }
     return trade_result.traded ;
 }
References trade_ui::trade_result_t::balance, Character::cash, item::charges, item::count_by_charges(), trade_ui::trade_result_t::delta_bank, distribute_items_to_npc_zones(), Character::drop_invalid_inventory(), item::erase_var(), get_avatar(), item::get_var(), item::has_var(), Character::i_add(), npc::is_shopkeeper(), trade_ui::trade_result_t::items_trader, trade_ui::trade_result_t::items_you, Character::practice(), npc::shop_restock(), skill_speech, trade_ui::trade_result_t::traded, transfer_items(), update_npc_owed(), trade_ui::trade_result_t::value_you, and npc::will_exchange_items_freely().
Referenced by talk_function::mission_reward(), game::npc_menu(), pay_npc(), and talk_function::start_trade().
trading_price()
int npc_trading::trading_price (Character const & buyer, Character const & seller, trade_selector::entry_t const & it)
Definition at line 220 of file npctrade.cpp.
 {
     return _trading_price( buyer, seller, it.first, it.second );
 }
References anonymous_namespace{npctrade.cpp}::_trading_price().
Referenced by trade_ui::autobalance(), bionic_install_price(), trade_preset::get_denial(), trade_ui::recalc_values_cpane(), trade_preset::trade_preset(), and transfer_items().
transfer_items()
std::list< item > npc_trading::transfer_items (trade_selector::select_t & stuff, Character & giver, Character & receiver, std::list< item_location * > & from_map, bool use_escrow)
Definition at line 30 of file npctrade.cpp.
 {
     // escrow is used only when the npc is the destination. Item transfer to the npc is deferred.
     std::list<item> escrow = std::list<item>();
     for( trade_selector::entry_t &ip : stuff ) {
         if( ip.first.get_item() == nullptr ) {
             DebugLog( D_ERROR, D_NPC ) << "Null item being traded in npc_trading::transfer_items";
             continue;
         }
         item gift = *ip.first.get_item();
         npc const *npc = nullptr;
         std::function<bool( item_location const &, int )> f_wants;
         if( giver.is_npc() ) {
             npc = giver.as_npc();
             f_wants = [npc]( item_location const & it, int price ) {
                 return npc->wants_to_sell( it, price ).success();
             };
         } else if( receiver.is_npc() ) {
             npc = receiver.as_npc();
             f_wants = [npc]( item_location const & it, int price ) {
                 return npc->wants_to_buy( *it, price ).success();
             };
         }
         // spill contained, unwanted items
         if( f_wants && gift.is_container() ) {
             for( item *it : gift.get_contents().all_items_top() ) {
                 int const price =
                     trading_price( giver, receiver, { item_location{ giver, it }, 1 } );
                 if( !f_wants( item_location{ ip.first, it }, price ) ) {
                     giver.i_add_or_drop( *it, 1, ip.first.get_item() );
                     gift.remove_item( *it );
                 }
             }
         }
         gift.set_owner( receiver );
         // Items are moving to escrow.
         if( use_escrow && ip.first->count_by_charges() ) {
             gift.charges = ip.second;
             escrow.emplace_back( gift );
         } else if( use_escrow ) {
             std::fill_n( std::back_inserter( escrow ), ip.second, gift );
             // No escrow in use. Items moving from giver to receiver.
         } else if( ip.first->count_by_charges() ) {
             gift.charges = ip.second;
             item newit = item( gift );
             ret_val<item_location> ret = receiver.i_add_or_fill( newit, true, nullptr, &gift,
                                          /*allow_drop=*/true, /*allow_wield=*/true, false );
         } else {
             for( int i = 0; i < ip.second; i++ ) {
                 receiver.i_add( gift );
             }
         }
         if( ip.first.held_by( giver ) ) {
             if( ip.first->count_by_charges() ) {
                 giver.use_charges( gift.typeId(), ip.second );
             } else if( ip.second > 0 ) {
                 giver.remove_items_with( [&ip]( const item & i ) {
                     return &i == ip.first.get_item();
                 }, ip.second );
             }
         } else {
             if( ip.first->count_by_charges() ) {
                 ip.first.get_item()->set_var( "trade_charges", ip.second );
             } else {
                 ip.first.get_item()->set_var( "trade_amount", 1 );
             }
             from_map.push_back( &ip.first );
         }
     }
     return escrow;
 }
References item_contents::all_items_top(), Creature::as_npc(), item::charges, D_ERROR, D_NPC, DebugLog(), item::get_contents(), Character::i_add(), Character::i_add_or_drop(), Character::i_add_or_fill(), item::is_container(), Character::is_npc(), visitable::remove_item(), Character::remove_items_with(), cata::hash64_detail::ret, item::set_owner(), trading_price(), item::typeId(), Character::use_charges(), npc::wants_to_buy(), and npc::wants_to_sell().
Referenced by trade().
update_npc_owed()
void npc_trading::update_npc_owed (npc & np, int your_balance, int your_sale_value)
Definition at line 268 of file npctrade.cpp.
 {
     np.op_of_u.owed = calc_npc_owes_you( np, your_balance );
     np.op_of_u.sold += your_sale_value;
 }
References calc_npc_owes_you(), npc::op_of_u, npc_opinion::owed, and npc_opinion::sold.
Referenced by trade().