Cataclysm DDA: coords Namespace Reference
coords Namespace Reference
Classes
class coord_point_base
A generic coordinate-type-safe point.
class coord_point_mut
class coord_point_mut< Point, Subpoint, true >
class coord_point
struct project_to_impl
struct project_to_impl< ScaleUp, 0, ResultScale, InBounds >
struct project_to_impl< 0, ScaleDown, ResultScale, false >
struct project_to_impl< 0, ScaleDown, ResultScale, true >
struct remainder_inbounds
struct remainder_inbounds< Point, origin::submap, scale::map_square, InBounds >
struct quotient_remainder_helper
struct quotient_remainder_point
struct quotient_remainder_tripoint
Typedefs
template<typename Point , origin RemainderOrigin, scale SourceScale, bool InBounds>
using remainder_inbounds_t = typename remainder_inbounds< Point, RemainderOrigin, SourceScale, InBounds >::type
Enumerations
enum class scale {
map_square , submap , overmap_terrain , segment ,
overmap , vehicle
}
enum class origin {
relative , abs , submap , overmap_terrain ,
overmap , reality_bubble
}
Functions
constexpr int map_squares_per (scale s)
constexpr origin origin_from_scale (scale s)
constexpr scale scale_from_origin (origin o)
template<typename Point , origin Origin, scale Scale>
constexpr coord_point< Point, Origin, Scale > & operator+= (coord_point< Point, Origin, Scale > &me, const coord_point< Point, origin::relative, Scale > &r)
template<typename Point , origin Origin, scale Scale>
constexpr coord_point< Point, Origin, Scale > & operator-= (coord_point< Point, Origin, Scale > &me, const coord_point< Point, origin::relative, Scale > &r)
template<typename Point , origin Origin, scale Scale>
constexpr coord_point< Point, Origin, Scale > & operator+= (coord_point< Point, Origin, Scale > &me, const point &r)
template<typename Point , origin Origin, scale Scale>
constexpr coord_point< Point, Origin, Scale > & operator-= (coord_point< Point, Origin, Scale > &me, const point &r)
template<typename Point , origin Origin, scale Scale>
constexpr coord_point< Point, Origin, Scale > & operator+= (coord_point< Point, Origin, Scale > &me, const tripoint &r)
template<typename Point , origin Origin, scale Scale>
constexpr coord_point< Point, Origin, Scale > & operator-= (coord_point< Point, Origin, Scale > &me, const tripoint &r)
template<typename Point , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds>
constexpr bool operator== (const coord_point< Point, Origin, Scale, LhsInBounds > &l, const coord_point< Point, Origin, Scale, RhsInBounds > &r)
template<typename Point , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds>
constexpr bool operator!= (const coord_point< Point, Origin, Scale, LhsInBounds > &l, const coord_point< Point, Origin, Scale, RhsInBounds > &r)
template<typename Point , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds>
constexpr bool operator< (const coord_point< Point, Origin, Scale, LhsInBounds > &l, const coord_point< Point, Origin, Scale, RhsInBounds > &r)
template<typename PointL , typename PointR , origin OriginL, scale Scale, bool InBounds>
constexpr auto operator+ (const coord_point< PointL, OriginL, Scale, InBounds > &l, const coord_point< PointR, origin::relative, Scale > &r)
template<typename PointL , typename PointR , origin OriginR, scale Scale, bool InBounds, typename = std::enable_if_t < OriginR != origin::relative >>
constexpr auto operator+ (const coord_point< PointL, origin::relative, Scale > &l, const coord_point< PointR, OriginR, Scale, InBounds > &r)
template<typename PointL , typename PointR , origin OriginL, scale Scale, bool InBounds>
constexpr auto operator- (const coord_point< PointL, OriginL, Scale, InBounds > &l, const coord_point< PointR, origin::relative, Scale > &r)
template<typename PointL , typename PointR , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds, typename = std::enable_if_t < Origin != origin::relative >>
constexpr auto operator- (const coord_point< PointL, Origin, Scale, LhsInBounds > &l, const coord_point< PointR, Origin, Scale, RhsInBounds > &r)
template<typename Point , scale Scale>
constexpr coord_point< Point, origin::relative, Scale > operator* (int l, const coord_point< Point, origin::relative, Scale > &r)
template<typename Point , scale Scale>
constexpr coord_point< Point, origin::relative, Scale > operator* (const coord_point< Point, origin::relative, Scale > &r, int l)
template<typename Point , origin Origin, scale Scale, bool InBounds>
std::ostream & operator<< (std::ostream &os, const coord_point< Point, Origin, Scale, InBounds > &p)
template<typename Point , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds>
constexpr coord_point< Point, Origin, Scale, LhsInBounds &&RhsInBounds > coord_min (const coord_point< Point, Origin, Scale, LhsInBounds > &l, const coord_point< Point, Origin, Scale, RhsInBounds > &r)
template<typename Point , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds>
constexpr coord_point< Point, Origin, Scale, LhsInBounds &&RhsInBounds > coord_max (const coord_point< Point, Origin, Scale, LhsInBounds > &l, const coord_point< Point, Origin, Scale, RhsInBounds > &r)
template<scale ResultScale, typename Point , origin Origin, scale SourceScale, bool InBounds>
auto project_to (const coord_point< Point, Origin, SourceScale, InBounds > &src)
template<scale ResultScale, origin Origin, scale SourceScale, bool InBounds>
quotient_remainder_point< Origin, ResultScale, SourceScale, InBounds > project_remain (const coord_point< point, Origin, SourceScale, InBounds > &src)
template<scale ResultScale, origin Origin, scale SourceScale, bool InBounds>
quotient_remainder_tripoint< Origin, ResultScale, SourceScale, InBounds > project_remain (const coord_point< tripoint, Origin, SourceScale, InBounds > &src)
template<typename PointL , typename PointR , origin CoarseOrigin, scale CoarseScale, origin FineOrigin, scale FineScale, bool CoarseInBounds, bool FineInBounds>
auto project_combine (const coord_point< PointL, CoarseOrigin, CoarseScale, CoarseInBounds > &coarse, const coord_point< PointR, FineOrigin, FineScale, FineInBounds > &fine)
template<scale FineScale, origin Origin, scale CoarseScale, bool InBounds>
auto project_bounds (const coord_point< point, Origin, CoarseScale, InBounds > &coarse)
template<scale FineScale, origin Origin, scale CoarseScale, bool InBounds>
auto project_bounds (const coord_point< tripoint, Origin, CoarseScale, InBounds > &coarse)
Variables
constexpr scale ms = scale::map_square
constexpr scale sm = scale::submap
constexpr scale omt = scale::overmap_terrain
constexpr scale seg = scale::segment
constexpr scale om = scale::overmap
Typedef Documentation
remainder_inbounds_t
template<typename Point , origin RemainderOrigin, scale SourceScale, bool InBounds> using coords::remainder_inbounds_t = typedef typename remainder_inbounds<Point, RemainderOrigin, SourceScale, InBounds>::type
Definition at line 522 of file coordinates.h.
Enumeration Type Documentation
origin
enum coords::origin strong
Enumerator
relative
abs
submap
overmap_terrain
overmap
reality_bubble
Definition at line 65 of file coordinates.h.
                   {
     relative, // this is a special origin that can be added to any other
     abs, // the global absolute origin for the entire game
     submap, // from corner of submap
     overmap_terrain, // from corner of overmap_terrain
     overmap, // from corner of overmap
     reality_bubble, // from corner of a reality bubble (aka 'map' or 'tinymap')
 };
scale
enum coords::scale strong
Enumerator
map_square
submap
overmap_terrain
segment
overmap
vehicle
Definition at line 29 of file coordinates.h.
                  {
     map_square,
     submap,
     overmap_terrain,
     segment,
     overmap,
     vehicle
 };
Function Documentation
coord_max()
template<typename Point , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds> constexpr coord_point< Point, Origin, Scale, LhsInBounds &&RhsInBounds > coords::coord_max (const coord_point< Point, Origin, Scale, LhsInBounds > & l, const coord_point< Point, Origin, Scale, RhsInBounds > & r) inline constexpr
Definition at line 448 of file coordinates.h.
 {
     return coord_point < Point, Origin, Scale, LhsInBounds &&
            RhsInBounds >::make_unchecked( std::max( l.x(), r.x() ), std::max( l.y(), r.y() ), std::max( l.z(),
                                           r.z() ) );
 }
References max(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
coord_min()
template<typename Point , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds> constexpr coord_point< Point, Origin, Scale, LhsInBounds &&RhsInBounds > coords::coord_min (const coord_point< Point, Origin, Scale, LhsInBounds > & l, const coord_point< Point, Origin, Scale, RhsInBounds > & r) inline constexpr
Definition at line 438 of file coordinates.h.
 {
     return coord_point < Point, Origin, Scale, LhsInBounds &&
            RhsInBounds >::make_unchecked( std::min( l.x(), r.x() ), std::min( l.y(), r.y() ), std::min( l.z(),
                                           r.z() ) );
 }
References min(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_line().
map_squares_per()
constexpr int coords::map_squares_per (scale s) constexpr
Definition at line 44 of file coordinates.h.
 {
     static_assert( SEEX == SEEY, "we assume submaps are square" );
     static_assert( OMAPX == OMAPY, "we assume overmaps are square" );
     switch( s ) {
         case scale::map_square:
             return 1;
         case scale::submap:
             return SEEX;
         case scale::overmap_terrain:
             return SEEX * 2;
         case scale::segment:
             return SEG_SIZE * map_squares_per( scale::overmap_terrain );
         case scale::overmap:
             return OMAPX * map_squares_per( scale::overmap_terrain );
         default:
             constexpr_fatal( 0, "Requested scale of %d", s );
     }
 }
References constexpr_fatal, OMAPX, OMAPY, SEEX, SEEY, and SEG_SIZE.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable_adjust(), project_remain(), project_to(), and npc::spawn_at_omt().
operator!=()
template<typename Point , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds> constexpr bool coords::operator!= (const coord_point< Point, Origin, Scale, LhsInBounds > & l, const coord_point< Point, Origin, Scale, RhsInBounds > & r) inline constexpr
Definition at line 358 of file coordinates.h.
 {
     return l.raw() != r.raw();
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
operator*() [1/2]
template<typename Point , scale Scale> constexpr coord_point<Point, origin::relative, Scale> coords::operator* (const coord_point< Point, origin::relative, Scale > & r, int l) inline constexpr
Definition at line 423 of file coordinates.h.
 {
     return coord_point<Point, origin::relative, Scale>( r.raw() * l );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
operator*() [2/2]
template<typename Point , scale Scale> constexpr coord_point<Point, origin::relative, Scale> coords::operator* (int l, const coord_point< Point, origin::relative, Scale > & r) inline constexpr
Definition at line 416 of file coordinates.h.
 {
     return coord_point<Point, origin::relative, Scale>( l * r.raw() );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
operator+() [1/2]
template<typename PointL , typename PointR , origin OriginR, scale Scale, bool InBounds, typename = std::enable_if_t < OriginR != origin::relative >> constexpr auto coords::operator+ (const coord_point< PointL, origin::relative, Scale > & l, const coord_point< PointR, OriginR, Scale, InBounds > & r) inline constexpr
Definition at line 384 of file coordinates.h.
 {
     using PointResult = decltype( PointL() + PointR() );
     return coord_point<PointResult, OriginR, Scale>( l.raw() + r.raw() );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
operator+() [2/2]
template<typename PointL , typename PointR , origin OriginL, scale Scale, bool InBounds> constexpr auto coords::operator+ (const coord_point< PointL, OriginL, Scale, InBounds > & l, const coord_point< PointR, origin::relative, Scale > & r) inline constexpr
Definition at line 372 of file coordinates.h.
 {
     using PointResult = decltype( PointL() + PointR() );
     return coord_point<PointResult, OriginL, Scale>( l.raw() + r.raw() );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
operator+=() [1/3]
template<typename Point , origin Origin, scale Scale> constexpr coord_point<Point, Origin, Scale>& coords::operator+= (coord_point< Point, Origin, Scale > & me, const coord_point< Point, origin::relative, Scale > & r) inline constexpr
Definition at line 303 of file coordinates.h.
 {
     me.raw() += r.raw();
     return me;
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
operator+=() [2/3]
template<typename Point , origin Origin, scale Scale> constexpr coord_point<Point, Origin, Scale>& coords::operator+= (coord_point< Point, Origin, Scale > & me, const point & r) inline constexpr
Definition at line 319 of file coordinates.h.
 {
     me.raw() += r;
     return me;
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
operator+=() [3/3]
template<typename Point , origin Origin, scale Scale> constexpr coord_point<Point, Origin, Scale>& coords::operator+= (coord_point< Point, Origin, Scale > & me, const tripoint & r) inline constexpr
Definition at line 335 of file coordinates.h.
 {
     me.raw() += r;
     return me;
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
operator-() [1/2]
template<typename PointL , typename PointR , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds, typename = std::enable_if_t < Origin != origin::relative >> constexpr auto coords::operator- (const coord_point< PointL, Origin, Scale, LhsInBounds > & l, const coord_point< PointR, Origin, Scale, RhsInBounds > & r) inline constexpr
Definition at line 406 of file coordinates.h.
 {
     using PointResult = decltype( PointL() + PointR() );
     return coord_point<PointResult, origin::relative, Scale>( l.raw() - r.raw() );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
operator-() [2/2]
template<typename PointL , typename PointR , origin OriginL, scale Scale, bool InBounds> constexpr auto coords::operator- (const coord_point< PointL, OriginL, Scale, InBounds > & l, const coord_point< PointR, origin::relative, Scale > & r) inline constexpr
Definition at line 393 of file coordinates.h.
 {
     using PointResult = decltype( PointL() + PointR() );
     return coord_point<PointResult, OriginL, Scale>( l.raw() - r.raw() );
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
operator-=() [1/3]
template<typename Point , origin Origin, scale Scale> constexpr coord_point<Point, Origin, Scale>& coords::operator-= (coord_point< Point, Origin, Scale > & me, const coord_point< Point, origin::relative, Scale > & r) inline constexpr
Definition at line 311 of file coordinates.h.
 {
     me.raw() -= r.raw();
     return me;
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
operator-=() [2/3]
template<typename Point , origin Origin, scale Scale> constexpr coord_point<Point, Origin, Scale>& coords::operator-= (coord_point< Point, Origin, Scale > & me, const point & r) inline constexpr
Definition at line 327 of file coordinates.h.
 {
     me.raw() -= r;
     return me;
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
operator-=() [3/3]
template<typename Point , origin Origin, scale Scale> constexpr coord_point<Point, Origin, Scale>& coords::operator-= (coord_point< Point, Origin, Scale > & me, const tripoint & r) inline constexpr
Definition at line 343 of file coordinates.h.
 {
     me.raw() -= r;
     return me;
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
operator<()
template<typename Point , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds> constexpr bool coords::operator< (const coord_point< Point, Origin, Scale, LhsInBounds > & l, const coord_point< Point, Origin, Scale, RhsInBounds > & r) inline constexpr
Definition at line 365 of file coordinates.h.
 {
     return l.raw() < r.raw();
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
operator<<()
template<typename Point , origin Origin, scale Scale, bool InBounds> std::ostream& coords::operator<< (std::ostream & os, const coord_point< Point, Origin, Scale, InBounds > & p) inline
Definition at line 430 of file coordinates.h.
 {
     return os << p.raw();
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
operator==()
template<typename Point , origin Origin, scale Scale, bool LhsInBounds, bool RhsInBounds> constexpr bool coords::operator== (const coord_point< Point, Origin, Scale, LhsInBounds > & l, const coord_point< Point, Origin, Scale, RhsInBounds > & r) inline constexpr
Definition at line 351 of file coordinates.h.
 {
     return l.raw() == r.raw();
 }
References coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
origin_from_scale()
constexpr origin coords::origin_from_scale (scale s) constexpr
Definition at line 74 of file coordinates.h.
 {
     switch( s ) {
         case scale::submap:
             return origin::submap;
         case scale::overmap_terrain:
             return origin::overmap_terrain;
         case scale::overmap:
             return origin::overmap;
         default:
             constexpr_fatal( origin::abs, "Requested origin for scale %d", s );
     }
 }
References abs(), and constexpr_fatal.
Referenced by project_combine(), and project_remain().
project_bounds() [1/2]
template<scale FineScale, origin Origin, scale CoarseScale, bool InBounds> auto coords::project_bounds (const coord_point< point, Origin, CoarseScale, InBounds > & coarse) inline
Definition at line 649 of file coordinates.h.
 {
     constexpr point one( 1, 1 ); // NOLINT(cata-use-named-point-constants)
     return half_open_rectangle<coord_point<point, Origin, FineScale>>(
                project_to<FineScale>( coarse ), project_to<FineScale>( coarse + one ) );
 }
project_bounds() [2/2]
template<scale FineScale, origin Origin, scale CoarseScale, bool InBounds> auto coords::project_bounds (const coord_point< tripoint, Origin, CoarseScale, InBounds > & coarse) inline
Definition at line 657 of file coordinates.h.
 {
     constexpr point one( 1, 1 ); // NOLINT(cata-use-named-point-constants)
     return half_open_cuboid<coord_point<tripoint, Origin, FineScale>>(
                project_to<FineScale>( coarse ), project_to<FineScale>( coarse + one ) );
 }
project_combine()
template<typename PointL , typename PointR , origin CoarseOrigin, scale CoarseScale, origin FineOrigin, scale FineScale, bool CoarseInBounds, bool FineInBounds> auto coords::project_combine (const coord_point< PointL, CoarseOrigin, CoarseScale, CoarseInBounds > & coarse, const coord_point< PointR, FineOrigin, FineScale, FineInBounds > & fine) inline
Definition at line 633 of file coordinates.h.
 {
     static_assert( origin_from_scale( CoarseScale ) == FineOrigin,
                    "given point types are not compatible for combination" );
     static_assert( PointL::dimension != 3 || PointR::dimension != 3,
                    "two tripoints should not be combined; it's unclear how to handle z" );
     using PointResult = decltype( PointL() + PointR() );
     const coord_point<PointL, CoarseOrigin, FineScale> refined_coarse =
         project_to<FineScale>( coarse );
     return coord_point < PointResult, CoarseOrigin, FineScale, CoarseInBounds &&
            FineInBounds >::make_unchecked( refined_coarse.raw() + fine.raw() );
 }
References character_health_category::fine, origin_from_scale(), and coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
Referenced by create_radio_tower_reference(), overmap::find_extras(), overmap::find_notes(), start_location::find_player_initial_location(), overmap::find_terrain(), overmap::generate_sub(), overmapbuffer::get_extras(), overmapbuffer::get_notes(), tutorial_game::init(), overmap::is_omt_generated(), monster::load(), overmap::load_monster_groups(), overmap::migrate_oter_ids(), overmap::move_hordes(), overmap::place_mongroups(), overmapbuffer::place_special(), overmap::place_special(), overmap_ui::search(), overmap::signal_hordes(), map::spawn_monsters_submap_group(), overmap::unserialize(), game::unserialize(), and mongroup::wander().
project_remain() [1/2]
template<scale ResultScale, origin Origin, scale SourceScale, bool InBounds> quotient_remainder_point<Origin, ResultScale, SourceScale, InBounds> coords::project_remain (const coord_point< point, Origin, SourceScale, InBounds > & src) inline
Definition at line 603 of file coordinates.h.
 {
     constexpr int ScaleDown = map_squares_per( ResultScale ) / map_squares_per( SourceScale );
     static_assert( ScaleDown > 0, "You can only project to coarser coordinate systems" );
     constexpr static origin RemainderOrigin = origin_from_scale( ResultScale );
     coord_point<point, Origin, ResultScale, InBounds> quotient = project_to< ResultScale>( src );
     remainder_inbounds_t<point, RemainderOrigin, SourceScale, InBounds> remainder =
         remainder_inbounds_t<point, RemainderOrigin, SourceScale, InBounds>::make_unchecked(
             src.raw() - quotient.raw() * ScaleDown );
     return { quotient, remainder };
 }
References map_squares_per(), origin_from_scale(), and coords::coord_point_mut< Point, Subpoint, InBounds >::raw().
project_remain() [2/2]
template<scale ResultScale, origin Origin, scale SourceScale, bool InBounds> quotient_remainder_tripoint<Origin, ResultScale, SourceScale, InBounds> coords::project_remain (const coord_point< tripoint, Origin, SourceScale, InBounds > & src) inline
Definition at line 618 of file coordinates.h.
 {
     using qrp = quotient_remainder_tripoint<Origin, ResultScale, SourceScale, InBounds>;
     using quotient_type_tripoint = typename qrp::quotient_type_tripoint;
     using remainder_type_tripoint = typename qrp::remainder_type_tripoint;
     quotient_remainder_point<Origin, ResultScale, SourceScale, InBounds> point_result =
         project_remain<ResultScale>( src.xy() );
     return { point_result.quotient, point_result.remainder,
              quotient_type_tripoint::make_unchecked( point_result.quotient, src.z() ),
              remainder_type_tripoint::make_unchecked( point_result.remainder, src.z() ) };
 }
References coords::quotient_remainder_point< Origin, CoarseScale, FineScale, InBounds >::quotient, coords::quotient_remainder_point< Origin, CoarseScale, FineScale, InBounds >::remainder, coords::coord_point< Point, Origin, Scale, InBounds >::xy(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
project_to()
template<scale ResultScale, typename Point , origin Origin, scale SourceScale, bool InBounds> auto coords::project_to (const coord_point< Point, Origin, SourceScale, InBounds > & src) inline
Definition at line 497 of file coordinates.h.
 {
     constexpr int scale_down = map_squares_per( ResultScale ) / map_squares_per( SourceScale );
     constexpr int scale_up = map_squares_per( SourceScale ) / map_squares_per( ResultScale );
     return project_to_impl<scale_up, scale_down, ResultScale, InBounds>()( src );
 }
References map_squares_per().
Referenced by zone_data::refresh_display().
scale_from_origin()
constexpr scale coords::scale_from_origin (origin o) constexpr
Definition at line 88 of file coordinates.h.
 {
     switch( o ) {
         case origin::submap:
             return scale::submap;
         case origin::overmap_terrain:
             return scale::overmap_terrain;
         case origin::overmap:
             return scale::overmap;
         default:
             constexpr_fatal( ms, "Requested scale for origin %d", o );
     }
 }
References constexpr_fatal, and ms.
Variable Documentation
ms
constexpr scale coords::ms = scale::map_square constexpr
Definition at line 38 of file coordinates.h.
Referenced by debug_menu::debug(), Character::made_of_any(), monster::made_of_any(), zone_data::refresh_display(), and scale_from_origin().
om
constexpr scale coords::om = scale::overmap constexpr
Definition at line 42 of file coordinates.h.
Referenced by anonymous_namespace{debug_menu.cpp}::_from_OM_string(), overmapbuffer::add_nemesis(), mutable_overmap_phase_remainder::can_place(), companion_travel_time_calc(), create_radio_tower_reference(), overmap_special_terrain::deserialize(), overmapbuffer::despawn_monster(), game::draw_minimap(), overmapbuffer::find_all_radio_stations(), overmapbuffer::find_radio_station(), overmapbuffer::fix_mongroups(), overmapbuffer::fix_nemesis(), overmapbuffer::get_camps_near(), overmapbuffer::get_cities_near(), weather_manager::get_cur_weather_gen(), overmapbuffer::get_existing_om_global(), overmapbuffer::get_extras(), overmapbuffer::get_notes(), overmapbuffer::get_om_global(), overmapbuffer::get_overmap_npcs(), overmapbuffer::get_settings(), overmapbuffer::groups_at(), overmapbuffer::move_hordes(), display::overmap_position_text(), fixed_overmap_special_data::place(), mutable_overmap_special_data::place(), overmap_special::place(), overmapbuffer::place_special(), overmapbuffer::process_mongroups(), mutable_overmap_phase_remainder::satisfy(), overmap_special::score_rotation_at(), fixed_overmap_special_data::score_rotation_at(), overmapbuffer::signal_hordes(), overmapbuffer::spawn_monster(), game::start_game(), mongroup::wander(), and anonymous_namespace{debug_menu.cpp}::write_min_archive().
omt
constexpr scale coords::omt = scale::overmap_terrain constexpr
Definition at line 40 of file coordinates.h.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable_adjust(), and npc::spawn_at_omt().
seg
constexpr scale coords::seg = scale::segment constexpr
Definition at line 41 of file coordinates.h.
Referenced by basecamp::deserialize(), cataimgui::window::draw_colored_text(), print_colored_text(), trim_by_length(), update_color_stack(), and anonymous_namespace{debug_menu.cpp}::write_min_archive().
sm
constexpr scale coords::sm = scale::submap constexpr
Definition at line 39 of file coordinates.h.
Referenced by timed_event::actualize(), mapbuffer::add_submap(), map_memory::allocate_submap(), map::apply_light_source(), map::calc_max_populated_zlev(), map_memory::clear_tile_decoration(), map::computer_at(), mapbuffer::deserialize(), mm_region::deserialize(), overmapbuffer::despawn_monster(), overmap_ui::draw_ascii(), map::draw_fill_background(), editmap::draw_main_ui_overlay(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), fake_map::fake_map(), map_memory::fetch_submap(), map_memory::find_submap(), vehicle::find_vehicle(), map::generate_lightmap(), generate_uniform(), map::get_active_items_in_radius(), game::get_cur_om(), map_memory::get_tile(), map::has_field_at(), is_sm_tile_outside(), is_sm_tile_over_water(), map::light_at(), mutation_branch::load(), bionic_data::load(), map_memory::load_submap(), map::maptile_at_internal(), map::mirror(), map::reset_vehicles_sm_pos(), map::rotate(), map_memory::save(), mapbuffer::save_quad(), map::scent_blockers(), mm_region::serialize(), map_memory::set_tile_decoration(), map_memory::set_tile_symbol(), map_memory::set_tile_terrain(), advanced_inventory::show_sort_menu(), map::unsafe_get_submap_at(), map::update_visibility_cache(), and anonymous_namespace{debug_menu.cpp}::write_min_archive().