Cataclysm DDA: item_internal Namespace Reference
item_internal Namespace Reference
Classes
struct scoped_goes_bad_cache
Functions
static bool goes_bad_cache_fetch ()
static void goes_bad_cache_set (const item *i)
static void goes_bad_cache_unset ()
static bool goes_bad_cache_is_for (const item *i)
Variables
static bool goes_bad_temp_cache = false
static const item * goes_bad_temp_cache_for = nullptr
Function Documentation
goes_bad_cache_fetch()
static bool item_internal::goes_bad_cache_fetch () static
Definition at line 260 of file item.cpp.
 {
     return goes_bad_temp_cache;
 }
References goes_bad_temp_cache.
Referenced by item::goes_bad().
goes_bad_cache_is_for()
static bool item_internal::goes_bad_cache_is_for (const item * i) static
Definition at line 274 of file item.cpp.
 {
     return goes_bad_temp_cache_for == i;
 }
References goes_bad_temp_cache_for.
Referenced by item::goes_bad().
goes_bad_cache_set()
static void item_internal::goes_bad_cache_set (const item * i) static
Definition at line 264 of file item.cpp.
 {
     goes_bad_temp_cache = i->goes_bad();
     goes_bad_temp_cache_for = i;
 }
References item::goes_bad(), goes_bad_temp_cache, and goes_bad_temp_cache_for.
Referenced by item_internal::scoped_goes_bad_cache::scoped_goes_bad_cache().
goes_bad_cache_unset()
static void item_internal::goes_bad_cache_unset () static
Definition at line 269 of file item.cpp.
 {
     goes_bad_temp_cache = false;
     goes_bad_temp_cache_for = nullptr;
 }
References goes_bad_temp_cache, and goes_bad_temp_cache_for.
Referenced by item_internal::scoped_goes_bad_cache::~scoped_goes_bad_cache().
Variable Documentation
goes_bad_temp_cache
bool item_internal::goes_bad_temp_cache = false static
Definition at line 258 of file item.cpp.
Referenced by goes_bad_cache_fetch(), goes_bad_cache_set(), and goes_bad_cache_unset().
goes_bad_temp_cache_for
const item* item_internal::goes_bad_temp_cache_for = nullptr static
Definition at line 259 of file item.cpp.
Referenced by goes_bad_cache_is_for(), goes_bad_cache_set(), and goes_bad_cache_unset().