Cataclysm DDA: melee Namespace Reference
melee Namespace Reference
Functions
float melee_hit_range (float accuracy)
Once the accuracy (sum of modifiers) of an attack has been determined, this is used to actually roll the "hit value" of the attack to be compared to dodge.
melee_statistic_data get_stats ()
void clear_stats ()
int blocking_ability (const item &shield)
Variables
melee_statistic_data melee_stats
Function Documentation
blocking_ability()
int melee::blocking_ability (const item & shield)
Definition at line 2024 of file melee.cpp.
 {
     int block_bonus = 0;
     if( shield.has_technique( WBLOCK_3 ) ) {
         block_bonus = 10;
     } else if( shield.has_technique( WBLOCK_2 ) ) {
         block_bonus = 6;
     } else if( shield.has_technique( WBLOCK_1 ) ) {
         block_bonus = 4;
     } else if( shield.has_flag( flag_BLOCK_WHILE_WORN ) ) {
         block_bonus = 2;
     }
     return block_bonus;
 }
References flag_BLOCK_WHILE_WORN, item::has_flag(), item::has_technique(), WBLOCK_1, WBLOCK_2, and WBLOCK_3.
Referenced by Character::best_shield(), outfit::best_shield(), and Character::block_hit().
clear_stats()
void melee::clear_stats ()
Definition at line 2989 of file melee.cpp.
 {
     melee_stats = melee_statistic_data{};
 }
References melee_stats.
get_stats()
melee_statistic_data melee::get_stats ()
Definition at line 158 of file game.cpp.
 {
     return g->stats();
 }
melee_hit_range()
float melee::melee_hit_range (float accuracy)
Once the accuracy (sum of modifiers) of an attack has been determined, this is used to actually roll the "hit value" of the attack to be compared to dodge.
Definition at line 2979 of file melee.cpp.
 {
     return normal_roll( accuracy * 5, 25.0f );
 }
References normal_roll().
Referenced by Character::hit_roll(), monster::hit_roll(), and monster::melee_attack().
Variable Documentation
melee_stats
melee_statistic_data melee::melee_stats
Definition at line 2996 of file melee.cpp.
Referenced by clear_stats(), Character::crit_chance(), and Character::melee_attack_abstract().