Cataclysm DDA: music Namespace Reference
music Namespace Reference
Enumerations
enum music_id {
mp3 , instrument , sound , title ,
LAST
}
Functions
bool is_active_music_id (music_id data)
music_id get_music_id ()
std::string get_music_id_string ()
void activate_music_id (music_id data)
void activate_music_id (const std::string &data)
void deactivate_music_id (music_id data)
void deactivate_music_id (const std::string &data)
void deactivate_music_id_all ()
void update_music_id_is_empty_flag (music_id data, bool update)
void update_music_id_is_empty_flag (const std::string &data, bool update)
Variables
std::map< music_id, std::pair< bool, bool > > music_id_list
Enumeration Type Documentation
music_id
enum music::music_id
Enumerator
mp3
instrument
sound
title
LAST
Definition at line 10 of file music.h.
               {
     mp3,
     instrument,
     sound,
     title,
     LAST
 };
Function Documentation
activate_music_id() [1/2]
void music::activate_music_id (const std::string & data)
Definition at line 59 of file music.cpp.
 {
     activate_music_id( io::string_to_enum<music_id>( data ) );
 }
References activate_music_id().
activate_music_id() [2/2]
void music::activate_music_id (music_id data)
Definition at line 54 of file music.cpp.
 {
     music_id_list[data].second = true;
 }
References music_id_list.
Referenced by activate_music_id(), deactivate_music_id_all(), iuse::mp3_on(), sounds::process_sound_markers(), and musical_instrument_actor::use().
deactivate_music_id() [1/2]
void music::deactivate_music_id (const std::string & data)
Definition at line 69 of file music.cpp.
 {
     deactivate_music_id( io::string_to_enum<music_id>( data ) );
 }
References deactivate_music_id().
deactivate_music_id() [2/2]
void music::deactivate_music_id (music_id data)
Definition at line 64 of file music.cpp.
 {
     music_id_list[data].second = false;
 }
References music_id_list.
Referenced by deactivate_music_id(), iuse::mp3_deactivate(), and musical_instrument_actor::use().
deactivate_music_id_all()
void music::deactivate_music_id_all ()
Definition at line 74 of file music.cpp.
 {
     for( std::pair<const music_id, std::pair<bool, bool>> &pair : music_id_list ) {
         pair.second.second = false;
     }
     activate_music_id( music_id::title );
 }
References activate_music_id(), music_id_list, and title.
Referenced by main_menu::opening_screen().
get_music_id()
music_id music::get_music_id ()
Definition at line 38 of file music.cpp.
 {
     for( std::pair<const music_id, std::pair<bool, bool>> &pair : music_id_list ) {
         if( pair.second.first && pair.second.second ) {
             return pair.first;
         }
     }
     cata_fatal( "At least one music_id must remain activated in music::get_music_id" );
 }
References cata_fatal, and music_id_list.
Referenced by get_music_id_string(), and main_menu::opening_screen().
get_music_id_string()
std::string music::get_music_id_string ()
Definition at line 49 of file music.cpp.
 {
     return io::enum_to_string<music_id>( get_music_id() );
 }
References get_music_id().
Referenced by main_menu::opening_screen().
is_active_music_id()
bool music::is_active_music_id (music_id data)
Definition at line 33 of file music.cpp.
 {
     return music_id_list[data].first && music_id_list[data].second;
 }
References music_id_list.
Referenced by musical_instrument_actor::use().
update_music_id_is_empty_flag() [1/2]
void music::update_music_id_is_empty_flag (const std::string & data, bool update)
Definition at line 88 of file music.cpp.
 {
     music_id_list[io::string_to_enum<music_id>( data )].first = update;
 }
References music_id_list.
update_music_id_is_empty_flag() [2/2]
void music::update_music_id_is_empty_flag (music_id data, bool update)
Definition at line 83 of file music.cpp.
 {
     music_id_list[data].first = update;
 }
References music_id_list.
Variable Documentation
music_id_list
std::map< music_id, std::pair< bool, bool > > music::music_id_list
Initial value:
{
    { mp3, { false, false } }, { instrument, { false, false } }, { sound, { false, false } }, {title, { true, true } }
}
Definition at line 29 of file music.cpp.
Referenced by activate_music_id(), deactivate_music_id(), deactivate_music_id_all(), get_music_id(), is_active_music_id(), and update_music_id_is_empty_flag().