Cataclysm DDA: start_locations Namespace Reference
start_locations Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void finalize_all ()
void check_consistency ()
void reset ()
const std::vector< start_location > & get_all ()
Function Documentation
check_consistency()
void start_locations::check_consistency ()
Definition at line 625 of file start_location.cpp.
 {
     all_start_locations.check();
 }
References anonymous_namespace{start_location.cpp}::all_start_locations.
Referenced by DynamicDataLoader::check_consistency().
finalize_all()
void start_locations::finalize_all ()
Definition at line 617 of file start_location.cpp.
 {
     all_start_locations.finalize();
     for( const start_location &start_loc : all_start_locations.get_all() ) {
         const_cast<start_location &>( start_loc ).finalize();
     }
 }
References anonymous_namespace{start_location.cpp}::all_start_locations, and behavior::finalize().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< start_location > & start_locations::get_all ()
Definition at line 635 of file start_location.cpp.
 {
     return all_start_locations.get_all();
 }
References anonymous_namespace{start_location.cpp}::all_start_locations.
Referenced by avatar::load_template(), and set_description().
load()
void start_locations::load (const JsonObject & jo, const std::string & src)
Definition at line 612 of file start_location.cpp.
 {
     all_start_locations.load( jo, src );
 }
References anonymous_namespace{start_location.cpp}::all_start_locations.
Referenced by DynamicDataLoader::initialize().
reset()
void start_locations::reset ()
Definition at line 630 of file start_location.cpp.
 {
     all_start_locations.reset();
 }
References anonymous_namespace{start_location.cpp}::all_start_locations.
Referenced by DynamicDataLoader::unload_data().