Cataclysm DDA: anonymous_namespace{magic.cpp} Namespace Reference
anonymous_namespace{magic.cpp} Namespace Reference
Variables
generic_factory< spell_type > spell_factory ("spell")
Variable Documentation
spell_factory
generic_factory<spell_type> anonymous_namespace{magic.cpp}::spell_factory("spell") ("spell")
Referenced by spell_type::get_all(), spell_type::is_valid(), spell_type::load_spell(), spell_events::notify(), and spell_type::reset_all().