Cataclysm DDA: calendar Namespace Reference
calendar Namespace Reference
Time keeping class.
Functions
bool once_every (const time_duration &event_frequency)
Predicate to handle rate-limiting.
bool eternal_season ()
void set_eternal_season (bool is_eternal_season)
bool eternal_night ()
void set_eternal_night (bool is_eternal_night)
bool eternal_day ()
void set_eternal_day (bool is_eternal_day)
time_duration year_length ()
time_duration season_length ()
void set_season_length (int dur)
void set_location (float latitude, float longitude)
float season_ratio ()
float season_from_default_ratio ()
std::string name_season (season_type s)
Returns the translated name of the season (with first letter being uppercase).
Variables
const int INDEFINITELY_LONG
A number that represents the longest possible action.
const time_duration INDEFINITELY_LONG_DURATION
The expected duration of the cataclysm.
time_point start_of_cataclysm = calendar::turn_zero
time_point start_of_game = calendar::turn_zero
time_point turn = calendar::turn_zero
season_type initial_season = SPRING
constexpr time_point before_time_starts = time_point::from_turn(-1)
A time point that is always before the current turn, even when the game has just started.
constexpr time_point turn_zero = time_point::from_turn(0)
Represents time point 0.
constexpr time_point turn_max = time_point::from_turn(INT_MAX)
Largest possible time point.
Detailed Description
Time keeping class.
Encapsulates the current time of day, date, and year. Also tracks seasonal variation in day length, the passing of the seasons themselves, and the phases of the moon.
Function Documentation
eternal_day()
bool calendar::eternal_day ()
Returns
Whether the eternal day is enabled.
Definition at line 705 of file calendar.cpp.
 {
     return is_eternal_day;
 }
References is_eternal_day.
Referenced by sun_azimuth_altitude().
eternal_night()
bool calendar::eternal_night ()
Returns
Whether the eternal night is enabled.
Definition at line 700 of file calendar.cpp.
 {
     return is_eternal_night;
 }
References is_eternal_night.
Referenced by sun_azimuth_altitude().
eternal_season()
bool calendar::eternal_season ()
Returns
Whether the eternal season is enabled.
Definition at line 695 of file calendar.cpp.
 {
     return is_eternal_season;
 }
References is_eternal_season.
Referenced by clipped_time(), season_effective_time::season_effective_time(), season_of_year(), weather_generator::test_weather(), and to_string().
name_season()
std::string calendar::name_season (season_type s)
Returns the translated name of the season (with first letter being uppercase).
Definition at line 758 of file calendar.cpp.
 {
     static const std::array<std::string, 5> season_names_untranslated = {{
             //~First letter is supposed to be uppercase
             std::string( translate_marker( "Spring" ) ),
             //~First letter is supposed to be uppercase
             std::string( translate_marker( "Summer" ) ),
             //~First letter is supposed to be uppercase
             std::string( translate_marker( "Autumn" ) ),
             //~First letter is supposed to be uppercase
             std::string( translate_marker( "Winter" ) ),
             std::string( translate_marker( "End times" ) )
         }
     };
     if( s >= SPRING && s <= WINTER ) {
         return _( season_names_untranslated[ s ] );
     }
     return _( season_names_untranslated[ 4 ] );
 }
References _, SPRING, translate_marker, and WINTER.
Referenced by display::date_string(), map_data_common_t::extended_description(), get_diary_time_str(), calendar_ui::select_time_point(), and to_string().
once_every()
bool calendar::once_every (const time_duration & event_frequency)
Predicate to handle rate-limiting.
Returns true after every event_frequency duration.
Definition at line 753 of file calendar.cpp.
 {
     return ( calendar::turn - calendar::turn_zero ) % event_frequency == 0_turns;
 }
References turn, and turn_zero.
Referenced by vehicle::beeper_sound(), item::charge_linked_batteries(), mattack::check_money_left(), Character::check_needs_extremes(), chop_single_do_turn(), Character::crafting_speed_multiplier(), Character::do_skill_rust(), player_activity::do_turn(), data_handling_activity_actor::do_turn(), hotwire_car_activity_actor::do_turn(), hacksaw_activity_actor::do_turn(), oxytorch_activity_actor::do_turn(), vehicle_folding_activity_actor::do_turn(), vehicle_unfolding_activity_actor::do_turn(), read_activity_actor::do_turn(), ebooksave_activity_actor::do_turn(), try_sleep_activity_actor::do_turn(), safecracking_activity_actor::do_turn(), workout_activity_actor::do_turn(), construct::do_turn_shovel(), eff_fun_fake_common_cold(), eff_fun_fake_flu(), eff_fun_hypovolemia(), eff_fun_sleep(), iuse::ehandcuffs_tick(), field_processor_upgrade_intensity(), activity_handlers::fish_do_turn(), iuse::foodperson_voice(), suffer::from_other_mutations(), suffer::from_radiation(), suffer::from_stimulants(), vehicle::gain_moves(), map::generate_lightmap(), mattack::generator(), activity_handlers::generic_game_turn_handler(), player_activity::get_distractions(), activity_handlers::hand_crank_do_turn(), handle_weather_effects(), Character::hardcoded_effects(), activity_handlers::jackhammer_do_turn(), anonymous_namespace{do_turn.cpp}::monmove(), npc::move(), npc::move_pause(), npc::npc_update_body(), activity_handlers::operation_do_turn(), opiate_effect(), anonymous_namespace{do_turn.cpp}::overmap_npc_move(), timed_event::per_turn(), game::perhaps_add_random_npc(), activity_handlers::pickaxe_do_turn(), iuse::play_music(), game::debug_hour_timer::print_time(), Character::process_bionic(), Character::process_one_effect(), monster::process_one_effect(), Character::process_turn(), monster::process_turn(), npc::process_turn(), process_vehicle_items(), item::ready_to_revive(), Character::reset_stats(), mattack::riotbot(), Character::search_surroundings(), mattack::searchlight(), Character::suffer(), activity_handlers::tree_communion_do_turn(), Character::update_body(), Character::update_bodytemp(), Character::update_health(), Character::update_needs(), musical_instrument_actor::use(), activity_handlers::vibe_do_turn(), and wet_character().
season_from_default_ratio()
float calendar::season_from_default_ratio ()
Returns
ratio of actual season length (a world option) to default season length. This should be used to convert JSON values (that assume the default for the season length option) to actual in-game length.
Definition at line 748 of file calendar.cpp.
 {
     return to_days<float>( season_length() ) / default_season_length;
 }
References default_season_length, and season_length().
Referenced by item::brewing_time(), item::composting_time(), and get_moon_phase().
season_length()
time_duration calendar::season_length ()
Returns
Time of a season (configured in current world settings)
Definition at line 715 of file calendar.cpp.
 {
     return time_duration::from_days( std::max( cur_season_length, 1 ) );
 }
References cur_season_length, time_duration::from_days(), and max().
Referenced by clipped_time(), day_of_season(), iexamine::fertilize_plant(), shearing_activity_actor::finish(), get_diary_time_str(), Character::get_sick(), weather_generator::get_water_temperature(), map::produce_sap(), map::restock_fruits(), season_from_default_ratio(), season_of_year(), season_ratio(), calendar_ui::select_time_point(), to_string(), and year_length().
season_ratio()
float calendar::season_ratio ()
Returns
relative length of game season to real life season.
Definition at line 743 of file calendar.cpp.
 {
     return to_days<float>( season_length() ) / real_world_season_length;
 }
References real_world_season_length, and season_length().
Referenced by item::get_plant_epoch(), and construction::time_scale().
set_eternal_day()
void calendar::set_eternal_day (bool is_eternal_day)
Definition at line 727 of file calendar.cpp.
 {
     is_eternal_day = is_eternal;
 }
References is_eternal_day.
Referenced by game::load(), game::setup(), and options_manager::show().
set_eternal_night()
void calendar::set_eternal_night (bool is_eternal_night)
Definition at line 723 of file calendar.cpp.
 {
     is_eternal_night = is_eternal;
 }
References is_eternal_night.
Referenced by game::load(), game::setup(), and options_manager::show().
set_eternal_season()
void calendar::set_eternal_season (bool is_eternal_season)
Definition at line 719 of file calendar.cpp.
 {
     is_eternal_season = is_eternal;
 }
References is_eternal_season.
Referenced by game::load(), game::setup(), and options_manager::show().
set_location()
void calendar::set_location (float latitude, float longitude)
Definition at line 735 of file calendar.cpp.
 {
     location = { units::from_degrees( latitude ), units::from_degrees( longitude ) };
 }
References units::from_degrees(), and location.
Referenced by avatar::load(), npc::load(), monster::load(), and game::setup().
set_season_length()
void calendar::set_season_length (int dur)
Definition at line 731 of file calendar.cpp.
 {
     cur_season_length = dur;
 }
References cur_season_length, and dur.
Referenced by game::load(), game::setup(), and options_manager::show().
year_length()
time_duration calendar::year_length ()
Returns
Time in a year, (configured in current world settings)
Definition at line 710 of file calendar.cpp.
 {
     return season_length() * 4;
 }
References season_length().
Referenced by Character::age(), clipped_time(), get_common_data(), get_diary_time_str(), scenario::load(), map::produce_sap(), calendar_ui::select_time_point(), talker_character::set_age(), sidereal_time_at(), sun_ra_declination(), weather_generator::test_weather(), time_past_new_year(), and to_string().
Variable Documentation
before_time_starts
constexpr time_point calendar::before_time_starts = time_point::from_turn(-1) constexpr
A time point that is always before the current turn, even when the game has just started.
This implies before_time_starts < calendar::turn is always true. It can be used to initialize time_point values that denote the last time a cache was update.
Definition at line 535 of file calendar.h.
Referenced by talk_function::caravan_depart(), talk_function::caravan_return(), talk_function::companion_choose_return(), talk_function::companion_return(), basecamp::farm_return(), basecamp::finish_return(), overmap_ui::get_scent_glyph(), overmap_ui::get_weather_at_point(), talk_function::individual_mission(), Character::load(), monster::load(), npc::load(), monster::monster(), season_of_year(), Character::set_time_died(), game::setup(), game::start_game(), stomach_contents::stomach_contents(), overmap::unserialize(), and weather_manager::weather_manager().
INDEFINITELY_LONG
const int calendar::INDEFINITELY_LONG extern
A number that represents the longest possible action.
This number should be regarded as a number of turns, and can safely be converted to a number of seconds or moves (movement points) without integer overflow. If used to represent a larger unit (hours/days/years), then this will result in integer overflow.
Referenced by npc::address_needs(), get_duration_or_var_part(), game::place_player(), smash(), and wait().
INDEFINITELY_LONG_DURATION
const time_duration calendar::INDEFINITELY_LONG_DURATION extern
The expected duration of the cataclysm.
Large duration that can be used to approximate infinite amounts of time.
This number can't be safely converted to a number of moves without causing an integer overflow.
Referenced by clipped_time(), comestible_inventory_preset::comestible_inventory_preset(), get_comestible_time_left(), comestible_inventory_preset::get_time_left(), item::spoilage_sort_order(), and to_string().
initial_season
season_type calendar::initial_season = SPRING extern
Definition at line 39 of file calendar.cpp.
Referenced by season_of_year(), game::serialize(), game::start_calendar(), and game::unserialize().
start_of_cataclysm
time_point calendar::start_of_cataclysm = calendar::turn_zero extern
Definition at line 36 of file calendar.cpp.
Referenced by jmapgen_liquid_item::apply(), jmapgen_corpse::apply(), jmapgen_item_group::apply(), jmapgen_loot::apply(), jmapgen_spawn_item::apply(), apply_construction_marker(), MapExtras::apply_function(), map::draw_lab(), map::draw_slimepit(), monster::drop_items_on_death(), epoch_to_time_point(), monster::generate_inventory(), MonsterGroupManager::GetUpgradedMonsterGroup(), tutorial_game::init(), item::io(), is_spawn_valid(), MapExtras::mx_casings(), MapExtras::mx_corpses(), MapExtras::mx_minefield(), MapExtras::mx_roadworks(), map::place_gas_pump(), vehicle::place_spawn_items(), map::place_toilet(), map::place_vending(), npc::randomize(), science_room(), game::serialize(), set_description(), game::start_calendar(), map::ter_set(), anonymous_namespace{math_parser_diag.cpp}::time_eval(), anonymous_namespace{math_parser_diag.cpp}::time_since_eval(), monster::try_upgrade(), game::unserialize(), and update_mapgen_function_json::update_map().
start_of_game
time_point calendar::start_of_game = calendar::turn_zero extern
Definition at line 37 of file calendar.cpp.
Referenced by advanced_spawn_time(), game::bury_screen(), SkillLevel::deserialize(), event_multiset::deserialize(), stats_tracker::deserialize(), char_creation::draw_age(), epoch_to_time_point(), season_effective_time::season_effective_time(), game::serialize(), set_description(), game::setup(), game::start_calendar(), and game::unserialize().
turn
time_point calendar::turn = calendar::turn_zero extern
Definition at line 38 of file calendar.cpp.
Referenced by anonymous_namespace{event_bus.cpp}::_make_dyn(), explosion_handler::_make_explosion(), act_vehicle_unload_fuel(), computer_session::action_amigara_log(), computer_session::action_amigara_start(), computer_session::action_data_anal(), computer_session::action_sample(), computer_session::action_toll(), Character::activate_bionic(), computer_session::activate_random_failure(), activity_tracker::activity(), activity_on_turn_move_loot(), timed_event::actualize(), map::actualize(), memorial_logger::add(), Creature::add_effect(), Character::add_faction_warning(), sounds::add_footstep(), item::add_rain_to_container(), item::age(), alcohol_diazepam_add(), item::ammo_set(), vehicle_part::ammo_set(), amphetamine_effect(), jmapgen_corpse::apply(), jmapgen_terrain::apply(), MapExtras::apply_function(), iexamine::arcfurnace_empty(), iexamine::arcfurnace_full(), mission::assign(), stomach_contents::ate(), iexamine::autoclave_empty(), activity_tracker::average_activity(), map::bash_ter_furn(), Character::beyond_final_warning(), iuse::blood_draw(), mdeath::broken(), Character::burn_fuel(), game::bury_screen(), game::butcher(), butchery_drops_harvest(), iuse::c4(), monster::can_pathfind(), can_recharge_lunar(), can_recharge_solar(), workout_activity_actor::can_resume_with_internal(), Character::can_sleep(), workout_activity_actor::canceled(), talk_function::caravan_depart(), talk_function::caravan_return(), talk_function::carpenter_return(), game::catch_a_monster(), debug_menu::change_weather(), basecamp::choose_new_leader(), Character::climate_control_strength(), anonymous_namespace{messages.cpp}::messages_impl::coalesce_messages(), map_data_common_t::color(), talk_function::commune_carpentry(), talk_function::commune_forage(), talk_function::commune_menial(), talk_function::commune_refuge_caravan(), basecamp::companion_choose_return(), talk_function::companion_choose_return(), basecamp::companion_crafting_choose_return(), npc::complain_about(), complete_construction(), Character::complete_disassemble(), achievement::time_bound::completed(), iexamine::compost_empty(), iexamine::compost_full(), Character::compute_nutrient_range(), item::convert(), crack_coke_add(), Character::crafting_inventory(), mission_type::create(), map::create_burnproducts(), create_byproducts_group(), create_byproducts_legacy(), create_charge_items(), relic_procgen_data::create_item(), recipe::create_result(), Single_item_creator::create_single_without_container(), Character::current_warnings_fac(), iexamine::curtains(), salvage_actor::cut_up(), cycle_action(), display::date_string(), iuse::dbg_lux_meter(), dead_plant(), debug_menu::debug(), item::debug_info(), debug_menu::debug_menu_game_state(), item_group::debug_spawn(), Creature::decrement_summon_timer(), iexamine::deployed_furniture(), vehicle_part::deserialize(), stats_tracker::deserialize(), time_point::deserialize(), Character::die(), monster::digest_food(), effect::disp_desc(), Character::disp_info(), Messages::display_messages(), item::display_name(), field_entry::do_decay(), anonymous_namespace{iexamine.cpp}::atm_menu::do_purchase_card(), iuse_transform::do_transform(), unload_loot_activity_actor::do_turn(), construct::done_deconstruct(), construct::done_dig_grave(), draw_effects_summary(), game::draw_panels(), mission_ui_impl::draw_selected_description(), iexamine_helper::drink_nectar(), mattack::dsa_drone_scan(), eat(), avatar_action::eat_here(), iuse::ecig(), eff_fun_sleep(), basecamp::emergency_recall(), explosion_handler::emp_blast(), monster::extended_description(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_custom_light_level(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_day(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_season(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_next_weather(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_place_override(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), npc::faction_display(), computer_session::failure_amigara(), farm_action(), iexamine::fertilize_plant(), talk_function::field_harvest(), map::fill_funnels(), vehicles::finalize_prototypes(), npc::find_job_to_perform(), tent_deconstruct_activity_actor::finish(), bookbinder_copy_activity_actor::finish(), hacksaw_activity_actor::finish(), boltcutting_activity_actor::finish(), milk_activity_actor::finish(), shearing_activity_actor::finish(), oxytorch_activity_actor::finish(), chop_logs_activity_actor::finish(), chop_planks_activity_actor::finish(), disable_activity_actor::finish(), forage_activity_actor::finish(), basecamp::finish_return(), iuse::firecracker(), iuse::firecracker_pack(), iuse::firecracker_pack_act(), iexamine::fireplace(), iuse::fish_trap_tick(), iexamine::flower_marloss(), iexamine::flower_poppy(), iuse::flu_vaccine(), talk_function::forage_return(), inventory::form_from_map(), fromPumpFuel(), iexamine::fswitch(), Character::fun_for(), basecamp::gathering_description(), basecamp::gathering_return(), generate_uniform(), generic_multi_activity_check_requirement(), generic_multi_activity_handler(), basecamp::get_available_missions_by_dir(), item::get_category_of_contents(), get_diary_time_str(), vehicle::get_folded_item(), map_data_common_t::get_harvest(), iexamine::get_harvest_items(), get_recipe_result_item(), npc::get_restock_interval(), recipe_result_info_cache::get_result_data(), vehicle_part::get_salvageable(), overmap_ui::get_scent_glyph(), weather_generator::get_water_temperature(), overmap_ui::get_weather_at_point(), MonsterGroupManager::GetResultFromGroup(), MonsterGroupManager::GetUpgradedMonsterGroup(), glare(), game::grabbed_veh_move(), game::handle_action(), vehicle::handle_potential_theft(), prying_activity_actor::handle_prying(), prying_activity_actor::handle_prying_nails(), talk_function::hospital_raid(), talk_function::hospital_raid_return(), vehicle::idle(), suffer::in_sunlight(), monster::increment_pathfinding_cd(), talk_function::individual_mission(), iuse_transform::info(), tutorial_game::init(), weldrig_hack::init(), vehicle::init_state(), field_entry::initialize_decay(), activity_tracker::instantaneous_activity_level(), item::io(), game::is_in_sunlight(), anonymous_namespace{messages.cpp}::game_message::is_new(), anonymous_namespace{messages.cpp}::game_message::is_recent(), is_spawn_valid(), item::item(), mattack::kamikaze(), iexamine::keg(), iexamine::kiln_empty(), iexamine::kiln_full(), talk_function::labor_return(), vehicle::leak_fuel(), firestarter_actor::light_mod(), Creature::load(), effect_on_conditions::load_new_character(), map::loadn(), activity_tracker::log_activity(), talk_function::loot_building(), cata::event::make(), item::make_corpse(), basecamp::make_corpse_from_group(), make_gun_projectile(), make_mon_corpse(), map::make_rubble(), editmap::mapgen_preview(), monster::mating_angry(), Character::melee_attack_abstract(), mill_activate(), iuse::mininuke(), game::mon_info_update(), monster::monster(), anonymous_namespace{math_parser_diag.cpp}::moon_phase_eval(), monster::move_to(), iuse::multicooker_tick(), MapExtras::mx_casings(), iexamine::nanofab(), game::natural_light_level(), diary::new_page(), activity_tracker::new_turn(), nicotine_effect(), npc::npc(), npc::npc_update_body(), om_cutdown_trees(), om_harvest_ter(), monster::on_load(), npc::on_load(), monster::on_unload(), once_every(), opiate_effect(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), monexamine::pet_menu(), photo_def_for_camera_point(), mattack::photograph(), pick_plant(), vehicle_part::pieces_for_broken_part(), iexamine::pit_covered(), place_appliance(), Character::place_corpse(), map::place_items(), tinymap::place_items(), game::place_player_overmap(), map::place_vending(), SkillLevel::practice(), vehicle::prepare_tools(), mission::process(), timed_event_manager::process(), Creature::process_effects(), process_eocs(), item::process_internal(), item::process_link(), Character::process_one_effect(), monster::process_one_effect(), process_reactivation(), sounds::process_sound_markers(), item::process_temperature_rot(), item::process_tool(), Character::process_turn(), map::produce_sap(), inventory::provide_pseudo_item(), map::put_items_from_loc(), tinymap::put_items_from_loc(), effect_on_conditions::queue_effect_on_condition(), iuse::radio_tick(), random_item_from(), npc::randomize(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::receive_item(), advanced_inventory::redraw_sidebar(), monster::refill_udders(), anonymous_namespace{messages.cpp}::messages_impl::refresh_cooldown(), game::remoteveh(), remove_ammo(), monster::reset_digestion(), monster::reset_pathfinding_cd(), item::reset_temp_check(), map::restock_fruits(), vehicle::restore_folded_parts(), rod_fish(), SkillLevel::rust(), map::saven(), scatter_chunks(), talk_function::scavenger_patrol(), talk_function::scavenger_raid(), talk_function::scavenging_patrol_return(), talk_function::scavenging_raid_return(), basecamp::search_results(), game::serialize(), item::set_age(), talker_character::set_age(), timed_event_manager::set_all(), vehicle::set_old_owner(), item::set_relative_rot(), overmapbuffer::set_scent(), Creature::set_summon_time(), game::setremoteveh(), iuse::sextant(), gun_actor::shoot(), npc::shop_restock(), Messages::dialog::show(), iexamine::shrub_marloss(), vehicle::slow_leak(), vehicle::smart_controller_handle_turn(), smash(), smoker_activate(), iuse::smoking(), sounds::sound(), monster::spawn_dissectables_on_death(), spell_effect::spawn_ethereal_item(), debug_menu::spawn_nested_mapgen(), mdeath::splatter(), fungal_effects::spread_fungus_one_tile(), hacksaw_activity_actor::start(), game::start_calendar(), basecamp::start_cut_logs(), game::start_game(), basecamp::start_mission(), basecamp::start_multi_mission(), basecamp::start_relay_hide_site(), basecamp::start_setup_hide_site(), npc::starting_weapon(), display::sundial_text_color(), display::sundial_time_text_color(), map_data_common_t::symbol(), trapfunc::temple_flood(), weather_generator::test_weather(), display::time_approx(), anonymous_namespace{math_parser_diag.cpp}::time_ass(), anonymous_namespace{math_parser_diag.cpp}::time_eval(), stomach_contents::time_since_ate(), anonymous_namespace{math_parser_diag.cpp}::time_since_eval(), display::time_string(), anonymous_namespace{math_parser_diag.cpp}::time_until_eval(), spell_effect::timed_event(), monster::to_item(), iexamine::toPumpFuel(), avatar::total_daily_calories_string(), vehicle::total_solar_epower(), iexamine::tree_hickory(), iexamine::tree_marloss(), monster::try_biosignature(), relic::try_recharge(), Character::try_remove_heavysnare(), monster::try_reproduce(), monster::try_upgrade(), achievement::time_bound::ui_text(), vehicle::unlink_cables(), unload_activity_actor::unload(), Character::unload(), game::unserialize(), scent_map::update(), Character::update_body(), Character::update_bodytemp(), update_emergency_recall(), item::update_link_traits(), update_time_fixed(), update_time_left(), editmap::update_view_with_help(), weather_manager::update_weather(), computer_session::use(), unpack_actor::use(), saw_barrel_actor::use(), saw_stock_actor::use(), vehicle::use_vehicle_tool(), Character::vomit(), wait(), game::walk_move(), map::water_from(), weather_forecast(), debug_menu::wind_direction(), debug_menu::wind_speed(), wishitem_produce(), and memorial_logger::write_text_memorial().
turn_max
constexpr time_point calendar::turn_max = time_point::from_turn(INT_MAX) constexpr
Largest possible time point.
About 69 years after turn_zero
Definition at line 546 of file calendar.h.
Referenced by item::debug_info(), item::io(), item::on_contents_changed(), and item::process_internal().
turn_zero
constexpr time_point calendar::turn_zero = time_point::from_turn(0) constexpr
Represents time point 0.
TODO: flesh out the documentation
Definition at line 541 of file calendar.h.
Referenced by computer_session::action_blood_anal(), computer_session::action_download_software(), Character::activate_bionic(), effect::activated(), map::add_corpse(), basecamp::add_resource(), Character::age(), alcohol_diazepam_add(), amphetamine_effect(), are_requirements_nearby(), mission::assign(), bionic_remove_common(), Item_spawn_data::check_consistency(), basecamp::choose_new_leader(), iexamine::compost_empty(), crack_coke_add(), mission_type::create(), day_of_season(), day_of_week(), debug_menu::debug_menu_game_state(), effect::deserialize(), monster::die(), Character::die(), item::display_name(), field_entry::do_decay(), game::draw_panels(), monster::extended_description(), vpart_info::finalize(), Single_item_creator::finalize(), basecamp::form_crafting_inventory(), funnel_charges_per_turn(), iexamine::fvat_empty(), get_common_data(), get_diary_time_str(), diary::get_head_text(), get_moon_phase(), mission::has_deadline(), anonymous_namespace{messages.cpp}::messages_impl::hide_message_in_cooldown(), hour_of_day(), vehicle::init_state(), item::io(), item_pocket::is_funnel_container(), item_group::item_from(), item_group::items_from(), mattack::kamikaze(), npc::load(), scenario::load(), submap::load(), effect_on_conditions::load_new_character(), maple_tree_sap_container(), Character::melee_attack_abstract(), minute_of_hour(), game::mon_info_update(), monster::monster(), iuse::multicooker(), MapExtras::mx_minefield(), nicotine_effect(), noon(), Character::normalize(), npc::on_load(), once_every(), opiate_effect(), mission_start::place_npc_software(), tutorial_game::post_action(), npc::randomize(), anonymous_namespace{messages.cpp}::messages_impl::refresh_cooldown(), requirements_map(), mattack::riotbot(), science_room(), mattack::searchlight(), calendar_ui::select_time_point(), talker_character::set_age(), item::set_birthday(), npc::shop_restock(), sidereal_time_at(), game::start_calendar(), sun_ra_declination(), iuse::tazer2(), weather_generator::test_weather(), anonymous_namespace{math_parser_diag.cpp}::time_ass(), anonymous_namespace{math_parser_diag.cpp}::time_eval(), time_past_midnight(), time_past_new_year(), to_string(), monster::try_upgrade(), Character::uninstall_bionic(), place_monster_iuse::use(), basecamp::use_charges(), vehicle::use_charges(), use_charges_from_furn(), weather_forecast(), and debug_menu::wishitem().