Cataclysm DDA: anonymous_namespace{npcmove.cpp} Namespace Reference
anonymous_namespace{npcmove.cpp} Namespace Reference
Functions
bool good_for_pickup (const item &it, npc &who, const tripoint &there)
Variables
const std::vector< bionic_id > defense_cbms
const std::vector< bionic_id > health_cbms
const std::vector< bionic_id > weapon_cbms
const int avoidance_vehicles_radius = 5
Function Documentation
good_for_pickup()
bool anonymous_namespace{npcmove.cpp}::good_for_pickup (const item & it, npc & who, const tripoint & there)
Definition at line 219 of file npcmove.cpp.
 {
     return who.can_take_that( it ) &&
            who.wants_take_that( it ) &&
            who.would_take_that( it, there );
 }
References npc::can_take_that(), npc::wants_take_that(), and npc::would_take_that().
Referenced by npc::find_item(), and npc::pick_up_item().
Variable Documentation
avoidance_vehicles_radius
const int anonymous_namespace{npcmove.cpp}::avoidance_vehicles_radius = 5
Definition at line 217 of file npcmove.cpp.
Referenced by npc::move().
defense_cbms
const std::vector<bionic_id> anonymous_namespace{npcmove.cpp}::defense_cbms
Initial value:
= { {
        bio_ads,
        bio_faraday,
        bio_heat_absorb,
        bio_heatsink,
        bio_ods,
        bio_shock
    }
}
Definition at line 192 of file npcmove.cpp.
Referenced by npc::activate_combat_cbms(), and npc::deactivate_combat_cbms().
health_cbms
const std::vector<bionic_id> anonymous_namespace{npcmove.cpp}::health_cbms
Initial value:
= { {
        bio_leukocyte,
        bio_plutfilter
    }
}
Definition at line 202 of file npcmove.cpp.
Referenced by npc::move_pause().
weapon_cbms
const std::vector<bionic_id> anonymous_namespace{npcmove.cpp}::weapon_cbms
Initial value:
= { {
        bio_chain_lightning,
        bio_laser,
        bio_blade,
        bio_claws
    }
}
Definition at line 209 of file npcmove.cpp.
Referenced by npc::activate_combat_cbms(), and npc::deactivate_combat_cbms().