Cataclysm DDA: conditional_fun::anonymous_namespace{condition.cpp} Namespace Reference
conditional_fun::anonymous_namespace{condition.cpp} Namespace Reference
Functions
conditional_t::func f_has_any_trait (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_trait (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_visible_trait (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_martial_art (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_flag (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_species (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_bodytype (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_activity (bool is_npc)
conditional_t::func f_has_activity (const JsonObject &, std::string_view, bool is_npc)
conditional_t::func f_has_proficiency (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_is_riding (bool is_npc)
conditional_t::func f_is_riding (const JsonObject &, std::string_view, bool is_npc)
conditional_t::func f_npc_has_class (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_u_has_mission (const JsonObject &jo, std::string_view member)
conditional_t::func f_u_monsters_in_direction (const JsonObject &jo, std::string_view member)
conditional_t::func f_u_safe_mode_trigger (const JsonObject &jo, std::string_view member)
conditional_t::func f_u_profession (const JsonObject &jo, std::string_view member)
conditional_t::func f_has_strength (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_dexterity (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_intelligence (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_perception (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_part_temp (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_is_wearing (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_item (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_items (const JsonObject &jo, const std::string_view member, bool is_npc)
conditional_t::func f_has_item_with_flag (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_item_category (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_bionics (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_any_effect (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_effect (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_need (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_at_om_location (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_near_om_location (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_var (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_expects_vars (const JsonObject &jo, std::string_view member)
conditional_t::func f_npc_role_nearby (const JsonObject &jo, std::string_view member)
conditional_t::func f_npc_allies (const JsonObject &jo, std::string_view member)
conditional_t::func f_npc_allies_global (const JsonObject &jo, std::string_view member)
conditional_t::func f_u_has_cash (const JsonObject &jo, std::string_view member)
conditional_t::func f_u_are_owed (const JsonObject &jo, std::string_view member)
conditional_t::func f_npc_aim_rule (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_npc_engagement_rule (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_npc_cbm_reserve_rule (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_npc_cbm_recharge_rule (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_npc_rule (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_npc_override (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_is_season (const JsonObject &jo, std::string_view member)
conditional_t::func f_mission_goal (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_is_gender (bool is_male, bool is_npc)
conditional_t::func f_is_male (bool is_npc)
conditional_t::func f_is_female (bool is_npc)
conditional_t::func f_is_alive (bool is_npc)
conditional_t::func f_exists (bool is_npc)
conditional_t::func f_is_avatar (bool is_npc)
conditional_t::func f_is_npc (bool is_npc)
conditional_t::func f_is_character (bool is_npc)
conditional_t::func f_is_monster (bool is_npc)
conditional_t::func f_is_item (bool is_npc)
conditional_t::func f_is_furniture (bool is_npc)
conditional_t::func f_player_see (bool is_npc)
conditional_t::func f_no_assigned_mission ()
conditional_t::func f_has_assigned_mission ()
conditional_t::func f_has_many_assigned_missions ()
conditional_t::func f_no_available_mission (bool is_npc)
conditional_t::func f_has_available_mission (bool is_npc)
conditional_t::func f_has_many_available_missions (bool is_npc)
conditional_t::func f_mission_complete (bool is_npc)
conditional_t::func f_mission_incomplete (bool is_npc)
conditional_t::func f_mission_failed (bool is_npc)
conditional_t::func f_npc_service (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_npc_available (bool is_npc)
conditional_t::func f_npc_following (bool is_npc)
conditional_t::func f_npc_friend (bool is_npc)
conditional_t::func f_npc_hostile (bool is_npc)
conditional_t::func f_npc_train_skills (bool is_npc)
conditional_t::func f_npc_train_styles (bool is_npc)
conditional_t::func f_npc_train_spells (bool is_npc)
conditional_t::func f_at_safe_space (bool is_npc)
conditional_t::func f_can_stow_weapon (bool is_npc)
conditional_t::func f_can_drop_weapon (bool is_npc)
conditional_t::func f_has_weapon (bool is_npc)
conditional_t::func f_is_driving (bool is_npc)
conditional_t::func f_has_stolen_item (bool)
conditional_t::func f_is_day ()
conditional_t::func f_is_outside (bool is_npc)
conditional_t::func f_is_underwater (bool is_npc)
conditional_t::func f_one_in_chance (const JsonObject &jo, std::string_view member)
conditional_t::func f_query (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_query_tile (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_x_in_y_chance (const JsonObject &jo, const std::string_view member)
conditional_t::func f_is_weather (const JsonObject &jo, std::string_view member)
conditional_t::func f_map_ter_furn_with_flag (const JsonObject &jo, std::string_view member)
conditional_t::func f_map_ter_furn_id (const JsonObject &jo, std::string_view member)
conditional_t::func f_map_in_city (const JsonObject &jo, std::string_view member)
conditional_t::func f_mod_is_loaded (const JsonObject &jo, std::string_view member)
conditional_t::func f_has_faction_trust (const JsonObject &jo, std::string_view member)
conditional_t::func f_compare_string (const JsonObject &jo, std::string_view member)
conditional_t::func f_get_condition (const JsonObject &jo, std::string_view member)
conditional_t::func f_test_eoc (const JsonObject &jo, std::string_view member)
conditional_t::func f_has_ammo ()
conditional_t::func f_math (const JsonObject &jo, const std::string_view member)
conditional_t::func f_u_has_camp ()
conditional_t::func f_has_pickup_list (bool is_npc)
conditional_t::func f_is_by_radio ()
conditional_t::func f_has_reason ()
conditional_t::func f_roll_contested (const JsonObject &jo, const std::string_view member)
conditional_t::func f_u_know_recipe (const JsonObject &jo, std::string_view member)
conditional_t::func f_mission_has_generic_rewards ()
conditional_t::func f_has_worn_with_flag (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_wielded_with_flag (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_wielded_with_weapon_category (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_can_see (bool is_npc)
conditional_t::func f_is_deaf (bool is_npc)
conditional_t::func f_is_on_terrain (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_is_on_terrain_with_flag (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_is_in_field (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_has_move_mode (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_can_see_location (const JsonObject &jo, std::string_view member, bool is_npc)
conditional_t::func f_using_martial_art (const JsonObject &jo, std::string_view member, bool is_npc)
Function Documentation
f_at_om_location()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_at_om_location (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 984 of file condition.cpp.
 {
     str_or_var location = get_str_or_var( jo.get_member( member ), member, true );
     return [location, is_npc]( dialogue const & d ) {
         const tripoint_abs_omt omt_pos = d.actor( is_npc )->global_omt_location();
         const oter_id &omt_ter = overmap_buffer.ter( omt_pos );
         const std::string &omt_str = omt_ter.id().str();
         std::string location_value = location.evaluate( d );
         if( location_value == "FACTION_CAMP_ANY" ) {
             std::optional<basecamp *> bcp = overmap_buffer.find_camp( omt_pos.xy() );
             if( bcp ) {
                 return true;
             }
             // TODO: legacy check to be removed once primitive field camp OMTs have been purged
             return omt_str.find( "faction_base_camp" ) != std::string::npos;
         } else if( location_value == "FACTION_CAMP_START" ) {
             const std::optional<mapgen_arguments> *maybe_args = overmap_buffer.mapgen_args( omt_pos );
             return !recipe_group::get_recipes_by_id( "all_faction_base_types", omt_ter, maybe_args ).empty();
         } else {
             return oter_no_dir( omt_ter ) == location_value;
         }
     };
 }
References overmapbuffer::find_camp(), JsonObject::get_member(), recipe_group::get_recipes_by_id(), get_str_or_var(), int_id< T >::id(), location, overmapbuffer::mapgen_args(), member, oter_no_dir(), overmap_buffer, string_id< T >::str(), overmapbuffer::ter(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
f_at_safe_space()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_at_safe_space (bool is_npc)
Definition at line 1430 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return overmap_buffer.is_safe( d.actor( is_npc )->global_omt_location() ) &&
                d.actor( is_npc )->is_safe();
     };
 }
References overmapbuffer::is_safe(), and overmap_buffer.
f_bodytype()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_bodytype (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 660 of file condition.cpp.
 {
     str_or_var bt_to_check = get_str_or_var( jo.get_member( member ), member, true );
     return [bt_to_check, is_npc]( dialogue const & d ) {
         const talker *actor = d.actor( is_npc );
         return actor->bodytype( bodytype_id( bt_to_check.evaluate( d ) ) );
     };
 }
References talker::bodytype(), abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_can_drop_weapon()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_can_drop_weapon (bool is_npc)
Definition at line 1446 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         const talker *actor = d.actor( is_npc );
         return !actor->unarmed_attack() && !actor->wielded_with_flag( flag_NO_UNWIELD );
     };
 }
References flag_NO_UNWIELD, talker::unarmed_attack(), and talker::wielded_with_flag().
f_can_see()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_can_see (bool is_npc)
Definition at line 1835 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->can_see();
     };
 }
f_can_see_location()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_can_see_location (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1895 of file condition.cpp.
 {
     str_or_var target = get_str_or_var( jo.get_member( member ), member, true );
     return [is_npc, target]( dialogue const & d ) {
         tripoint_abs_ms target_pos = tripoint_abs_ms( tripoint::from_string( target.evaluate( d ) ) );
         return d.actor( is_npc )->can_see_location( get_map().getlocal( target_pos ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), tripoint::from_string(), get_map(), JsonObject::get_member(), get_str_or_var(), and member.
f_can_stow_weapon()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_can_stow_weapon (bool is_npc)
Definition at line 1438 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         const talker *actor = d.actor( is_npc );
         return !actor->unarmed_attack() && actor->can_stash_weapon();
     };
 }
References talker::can_stash_weapon(), and talker::unarmed_attack().
f_compare_string()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_compare_string (const JsonObject & jo, std::string_view member)
Definition at line 1672 of file condition.cpp.
 {
     str_or_var first;
     str_or_var second;
     JsonArray objects = jo.get_array( member );
     if( objects.size() != 2 ) {
         jo.throw_error( "incorrect number of values.  Expected 2 in " + jo.str() );
         return []( dialogue const & ) {
             return false;
         };
     }
     if( objects.has_object( 0 ) ) {
         first = get_str_or_var( objects.next_value(), member, true );
     } else {
         first.str_val = objects.next_string();
     }
     if( objects.has_object( 1 ) ) {
         second = get_str_or_var( objects.next_value(), member, true );
     } else {
         second.str_val = objects.next_string();
     }
     return [first, second]( dialogue const & d ) {
         return first.evaluate( d ) == second.evaluate( d );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_array(), get_str_or_var(), JsonArray::has_object(), member, JsonArray::next_string(), JsonArray::next_value(), second, JsonArray::size(), JsonObject::str(), abstract_str_or_var< T >::str_val, and JsonObject::throw_error().
f_exists()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_exists (bool is_npc)
Definition at line 1242 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         if( ( is_npc && !d.has_beta ) || ( !is_npc && !d.has_alpha ) ) {
             return false;
         } else {
             return true;
         }
     };
 }
f_expects_vars()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_expects_vars (const JsonObject & jo, std::string_view member)
Definition at line 1065 of file condition.cpp.
 {
     std::vector<str_or_var> to_check;
     if( jo.has_array( member ) ) {
         for( const JsonValue &jv : jo.get_array( member ) ) {
             to_check.push_back( get_str_or_var( jv, member, true ) );
         }
     }
     return [to_check]( dialogue const & d ) {
         std::string missing_variables;
         for( const str_or_var &val : to_check ) {
             if( d.get_context().find( "npctalk_var_" + val.evaluate( d ) ) == d.get_context().end() ) {
                 missing_variables += val.evaluate( d ) + ", ";
             }
         }
         if( !missing_variables.empty() ) {
             debugmsg( string_format( "Missing required variables: %s", missing_variables ) );
             return false;
         }
         return true;
     };
 }
References debugmsg, JsonObject::get_array(), get_str_or_var(), JsonObject::has_array(), member, and string_format().
f_get_condition()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_get_condition (const JsonObject & jo, std::string_view member)
Definition at line 1700 of file condition.cpp.
 {
     str_or_var conditionalToGet = get_str_or_var( jo.get_member( member ), member, true );
     return [conditionalToGet]( dialogue & d ) {
         return d.evaluate_conditional( conditionalToGet.evaluate( d ), d );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_has_activity() [1/2]
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_activity (bool is_npc)
Definition at line 670 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->has_activity();
     };
 }
f_has_activity() [2/2]
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_activity (const JsonObject & , std::string_view , bool is_npc)
Definition at line 677 of file condition.cpp.
 {
     return f_has_activity( is_npc );
 }
f_has_ammo()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_ammo ()
Definition at line 1721 of file condition.cpp.
 {
     return []( dialogue & d ) {
         item_location *it = d.actor( true )->get_item();
         if( it ) {
             return ( *it )->ammo_sufficient( d.actor( false )->get_character() );
         } else {
             debugmsg( "beta talker must be Item" );
             return false;
         }
     };
 }
References item::ammo_sufficient(), and debugmsg.
f_has_any_effect()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_any_effect (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 914 of file condition.cpp.
 {
     std::vector<str_or_var> effects_to_check;
     for( JsonValue jv : jo.get_array( member ) ) {
         effects_to_check.emplace_back( get_str_or_var( jv, member ) );
     }
     dbl_or_var intensity = get_dbl_or_var( jo, "intensity", false, -1 );
     str_or_var bp;
     if( jo.has_member( "bodypart" ) ) {
         bp = get_str_or_var( jo.get_member( "bodypart" ), "bodypart", true );
     } else {
         bp.str_val = "";
     }
     return [effects_to_check, intensity, bp, is_npc]( dialogue & d ) {
         bodypart_id bid = bp.evaluate( d ).empty() ? get_bp_from_str( d.reason ) :
                           bodypart_id( bp.evaluate( d ) );
         for( const str_or_var &effect_id : effects_to_check ) {
             effect target = d.actor( is_npc )->get_effect( efftype_id( effect_id.evaluate( d ) ), bid );
             if( !target.is_null() && intensity.evaluate( d ) <= target.get_intensity() ) {
                 return true;
             }
         }
         return false;
     };
 }
References bp, JsonObject::get_array(), get_bp_from_str(), get_dbl_or_var(), effect::get_intensity(), JsonObject::get_member(), get_str_or_var(), JsonObject::has_member(), intensity, effect::is_null(), and member.
f_has_any_trait()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_any_trait (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 587 of file condition.cpp.
 {
     std::vector<str_or_var> traits_to_check;
     for( JsonValue jv : jo.get_array( member ) ) {
         traits_to_check.emplace_back( get_str_or_var( jv, member ) );
     }
     return [traits_to_check, is_npc]( dialogue const & d ) {
         const talker *actor = d.actor( is_npc );
         for( const str_or_var &trait : traits_to_check ) {
             if( actor->has_trait( trait_id( trait.evaluate( d ) ) ) ) {
                 return true;
             }
         }
         return false;
     };
 }
References JsonObject::get_array(), get_str_or_var(), talker::has_trait(), and member.
f_has_assigned_mission()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_assigned_mission ()
Definition at line 1313 of file condition.cpp.
 {
     return []( dialogue const & d ) {
         return d.missions_assigned.size() == 1;
     };
 }
f_has_available_mission()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_available_mission (bool is_npc)
Definition at line 1334 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->available_missions().size() == 1;
     };
 }
f_has_bionics()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_bionics (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 901 of file condition.cpp.
 {
     str_or_var bionics_id = get_str_or_var( jo.get_member( member ), member, true );
     return [bionics_id, is_npc]( dialogue const & d ) {
         const talker *actor = d.actor( is_npc );
         if( bionics_id.evaluate( d ) == "ANY" ) {
             return actor->num_bionics() > 0 || actor->has_max_power();
         }
         return actor->has_bionic( bionic_id( bionics_id.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), talker::has_bionic(), talker::has_max_power(), member, and talker::num_bionics().
f_has_dexterity()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_dexterity (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 780 of file condition.cpp.
 {
     dbl_or_var dov = get_dbl_or_var( jo, member );
     return [dov, is_npc]( dialogue & d ) {
         return d.actor( is_npc )->dex_cur() >= dov.evaluate( d );
     };
 }
References dbl_or_var::evaluate(), get_dbl_or_var(), and member.
f_has_effect()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_effect (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 941 of file condition.cpp.
 {
     str_or_var effect_id = get_str_or_var( jo.get_member( member ), member, true );
     dbl_or_var intensity = get_dbl_or_var( jo, "intensity", false, -1 );
     str_or_var bp;
     if( jo.has_member( "bodypart" ) ) {
         bp = get_str_or_var( jo.get_member( "bodypart" ), "bodypart", true );
     } else {
         bp.str_val = "";
     }
     return [effect_id, intensity, bp, is_npc]( dialogue & d ) {
         bodypart_id bid = bp.evaluate( d ).empty() ? get_bp_from_str( d.reason ) :
                           bodypart_id( bp.evaluate( d ) );
         effect target = d.actor( is_npc )->get_effect( efftype_id( effect_id.evaluate( d ) ), bid );
         return !target.is_null() && intensity.evaluate( d ) <= target.get_intensity();
     };
 }
References bp, abstract_str_or_var< T >::evaluate(), get_bp_from_str(), get_dbl_or_var(), effect::get_intensity(), JsonObject::get_member(), get_str_or_var(), JsonObject::has_member(), intensity, effect::is_null(), and member.
f_has_faction_trust()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_faction_trust (const JsonObject & jo, std::string_view member)
Definition at line 1664 of file condition.cpp.
 {
     dbl_or_var dov = get_dbl_or_var( jo, member );
     return [dov]( dialogue & d ) {
         return d.actor( true )->get_faction()->trusts_u >= dov.evaluate( d );
     };
 }
References dbl_or_var::evaluate(), get_dbl_or_var(), and member.
f_has_flag()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_flag (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 637 of file condition.cpp.
 {
     str_or_var trait_flag_to_check = get_str_or_var( jo.get_member( member ), member, true );
     return [trait_flag_to_check, is_npc]( dialogue const & d ) {
         const talker *actor = d.actor( is_npc );
         if( json_character_flag( trait_flag_to_check.evaluate( d ) ) == json_flag_MUTATION_THRESHOLD ) {
             return actor->crossed_threshold();
         }
         return actor->has_flag( json_character_flag( trait_flag_to_check.evaluate( d ) ) );
     };
 }
References talker::crossed_threshold(), abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), talker::has_flag(), json_flag_MUTATION_THRESHOLD, and member.
f_has_intelligence()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_intelligence (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 789 of file condition.cpp.
 {
     dbl_or_var dov = get_dbl_or_var( jo, member );
     return [dov, is_npc]( dialogue & d ) {
         return d.actor( is_npc )->int_cur() >= dov.evaluate( d );
     };
 }
References dbl_or_var::evaluate(), get_dbl_or_var(), and member.
f_has_item()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_item (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 829 of file condition.cpp.
 {
     str_or_var item_id = get_str_or_var( jo.get_member( member ), member, true );
     return [item_id, is_npc]( dialogue const & d ) {
         const talker *actor = d.actor( is_npc );
         return actor->charges_of( itype_id( item_id.evaluate( d ) ) ) > 0 ||
                actor->has_amount( itype_id( item_id.evaluate( d ) ), 1 );
     };
 }
References talker::charges_of(), abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), talker::has_amount(), and member.
f_has_item_category()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_item_category (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 879 of file condition.cpp.
 {
     str_or_var category_id = get_str_or_var( jo.get_member( member ), member, true );
     size_t count = 1;
     if( jo.has_int( "count" ) ) {
         int tcount = jo.get_int( "count" );
         if( tcount > 1 && tcount < INT_MAX ) {
             count = static_cast<size_t>( tcount );
         }
     }
     return [category_id, count, is_npc]( dialogue const & d ) {
         const talker *actor = d.actor( is_npc );
         const item_category_id cat_id = item_category_id( category_id.evaluate( d ) );
         const auto items_with = actor->const_items_with( [cat_id]( const item & it ) {
             return it.get_category_shallow().get_id() == cat_id;
         } );
         return items_with.size() >= count;
     };
 }
References talker::const_items_with(), abstract_str_or_var< T >::evaluate(), item::get_category_shallow(), std::this_thread::get_id(), JsonObject::get_int(), JsonObject::get_member(), get_str_or_var(), JsonObject::has_int(), and member.
f_has_item_with_flag()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_item_with_flag (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 870 of file condition.cpp.
 {
     str_or_var flag = get_str_or_var( jo.get_member( member ), member, true );
     return [flag, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->has_item_with_flag( flag_id( flag.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_has_items()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_items (const JsonObject & jo, const std::string_view member, bool is_npc)
Definition at line 839 of file condition.cpp.
 {
     JsonObject has_items = jo.get_object( member );
     if( !has_items.has_member( "item" ) || ( !has_items.has_member( "count" ) &&
             !has_items.has_member( "charges" ) ) ) {
         return []( dialogue const & ) {
             return false;
         };
     } else {
         str_or_var item_id = get_str_or_var( has_items.get_member( "item" ), "item", true );
         dbl_or_var count = get_dbl_or_var( has_items, "count", false );
         dbl_or_var charges = get_dbl_or_var( has_items, "charges", false );
         return [item_id, count, charges, is_npc]( dialogue & d ) {
             const talker *actor = d.actor( is_npc );
             itype_id id = itype_id( item_id.evaluate( d ) );
             if( charges.evaluate( d ) == 0 && item::count_by_charges( id ) ) {
                 return actor->has_charges( id, count.evaluate( d ), true );
             }
             if( charges.evaluate( d ) > 0 && count.evaluate( d ) == 0 ) {
                 return actor->has_charges( id, charges.evaluate( d ), true );
             }
             bool has_enough_charges = true;
             if( charges.evaluate( d ) > 0 ) {
                 has_enough_charges = actor->has_charges( id, charges.evaluate( d ), true );
             }
             return has_enough_charges && actor->has_amount( id, count.evaluate( d ) );
         };
     }
 }
References item::count_by_charges(), dbl_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), get_dbl_or_var(), JsonObject::get_member(), JsonObject::get_object(), get_str_or_var(), talker::has_amount(), talker::has_charges(), JsonObject::has_member(), and member.
f_has_many_assigned_missions()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_many_assigned_missions ()
Definition at line 1320 of file condition.cpp.
 {
     return []( dialogue const & d ) {
         return d.missions_assigned.size() >= 2;
     };
 }
f_has_many_available_missions()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_many_available_missions (bool is_npc)
Definition at line 1341 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->available_missions().size() >= 2;
     };
 }
f_has_martial_art()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_martial_art (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 628 of file condition.cpp.
 {
     str_or_var style_to_check = get_str_or_var( jo.get_member( member ), member, true );
     return [style_to_check, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->knows_martial_art( matype_id( style_to_check.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_has_move_mode()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_move_mode (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1886 of file condition.cpp.
 {
     str_or_var mode = get_str_or_var( jo.get_member( member ), member, true );
     return [mode, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->get_move_mode() == move_mode_id( mode.evaluate( d ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_has_part_temp()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_part_temp (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 807 of file condition.cpp.
 {
     dbl_or_var dov = get_dbl_or_var( jo, member );
     std::optional<bodypart_id> bp;
     optional( jo, false, "bodypart", bp );
     return [dov, bp, is_npc]( dialogue & d ) {
         bodypart_id bid = bp.value_or( get_bp_from_str( d.reason ) );
         return units::to_legacy_bodypart_temp( d.actor( is_npc )->get_cur_part_temp(
                 bid ) ) >= dov.evaluate( d );
     };
 }
References bp, dbl_or_var::evaluate(), get_bp_from_str(), get_dbl_or_var(), member, optional(), and units::to_legacy_bodypart_temp().
f_has_perception()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_perception (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 798 of file condition.cpp.
 {
     dbl_or_var dov = get_dbl_or_var( jo, member );
     return [dov, is_npc]( dialogue & d ) {
         return d.actor( is_npc )->per_cur() >= dov.evaluate( d );
     };
 }
References dbl_or_var::evaluate(), get_dbl_or_var(), and member.
f_has_pickup_list()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_pickup_list (bool is_npc)
Definition at line 1750 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->has_ai_rule( "pickup_rule", "any" );
     };
 }
f_has_proficiency()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_proficiency (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 682 of file condition.cpp.
 {
     str_or_var proficiency_to_check = get_str_or_var( jo.get_member( member ), member, true );
     return [proficiency_to_check, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->knows_proficiency( proficiency_id( proficiency_to_check.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_has_reason()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_reason ()
Definition at line 1764 of file condition.cpp.
 {
     return []( dialogue const & d ) {
         return !d.reason.empty();
     };
 }
f_has_species()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_species (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 650 of file condition.cpp.
 {
     str_or_var species_to_check = get_str_or_var( jo.get_member( member ), member, true );
     return [species_to_check, is_npc]( dialogue const & d ) {
         const talker *actor = d.actor( is_npc );
         return actor->has_species( species_id( species_to_check.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), talker::has_species(), and member.
f_has_stolen_item()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_stolen_item (bool)
Definition at line 1472 of file condition.cpp.
 {
     return []( dialogue const & d ) {
         return d.actor( false )->has_stolen_item( *d.actor( true ) );
     };
 }
f_has_strength()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_strength (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 771 of file condition.cpp.
 {
     dbl_or_var dov = get_dbl_or_var( jo, member );
     return [dov, is_npc]( dialogue & d ) {
         return d.actor( is_npc )->str_cur() >= dov.evaluate( d );
     };
 }
References dbl_or_var::evaluate(), get_dbl_or_var(), and member.
f_has_trait()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_trait (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 604 of file condition.cpp.
 {
     str_or_var trait_to_check = get_str_or_var( jo.get_member( member ), member, true );
     return [trait_to_check, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->has_trait( trait_id( trait_to_check.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_has_var()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_var (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1047 of file condition.cpp.
 {
     dbl_or_var empty;
     const std::string var_name = get_talk_varname( jo, member, false, empty );
     const std::string &value = jo.has_member( "value" ) ? jo.get_string( "value" ) : std::string();
     if( !jo.has_member( "value" ) ) {
         jo.throw_error( R"(Missing field: "value")" );
         return []( dialogue const & ) {
             return false;
         };
     }
     return [var_name, value, is_npc]( dialogue const & d ) {
         const talker *actor = d.actor( is_npc );
         return actor->get_value( var_name ) == value;
     };
 }
References JsonObject::get_string(), get_talk_varname(), talker::get_value(), JsonObject::has_member(), member, and JsonObject::throw_error().
f_has_visible_trait()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_visible_trait (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 612 of file condition.cpp.
 {
     str_or_var trait_to_check = get_str_or_var( jo.get_member( member ), member, true );
     return [trait_to_check, is_npc]( dialogue const & d ) {
         const talker *observer = d.actor( !is_npc );
         const talker *observed = d.actor( is_npc );
         int visibility_cap = observer->get_character()->get_mutation_visibility_cap(
                                  observed->get_character() );
         bool observed_has = observed->has_trait( trait_id( trait_to_check.evaluate( d ) ) );
         const mutation_branch &mut_branch = trait_id( trait_to_check.evaluate( d ) ).obj();
         bool is_visible = mut_branch.visibility > 0 && mut_branch.visibility >= visibility_cap;
         return observed_has && is_visible;
     };
 }
References abstract_str_or_var< T >::evaluate(), talker::get_character(), JsonObject::get_member(), Character::get_mutation_visibility_cap(), get_str_or_var(), talker::has_trait(), member, string_id< T >::obj(), and mutation_branch::visibility.
f_has_weapon()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_weapon (bool is_npc)
Definition at line 1454 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return !d.actor( is_npc )->unarmed_attack();
     };
 }
f_has_wielded_with_flag()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_wielded_with_flag (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1816 of file condition.cpp.
 {
     str_or_var flag = get_str_or_var( jo.get_member( member ), member, true );
     return [flag, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->wielded_with_flag( flag_id( flag.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_has_wielded_with_weapon_category()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_wielded_with_weapon_category (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1825 of file condition.cpp.
 {
     str_or_var w_cat = get_str_or_var( jo.get_member( member ), member, true );
     return [w_cat, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->wielded_with_weapon_category( weapon_category_id( w_cat.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_has_worn_with_flag()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_has_worn_with_flag (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1804 of file condition.cpp.
 {
     str_or_var flag = get_str_or_var( jo.get_member( member ), member, true );
     std::optional<bodypart_id> bp;
     optional( jo, false, "bodypart", bp );
     return [flag, bp, is_npc]( dialogue const & d ) {
         bodypart_id bid = bp.value_or( get_bp_from_str( d.reason ) );
         return d.actor( is_npc )->worn_with_flag( flag_id( flag.evaluate( d ) ), bid );
     };
 }
References bp, abstract_str_or_var< T >::evaluate(), get_bp_from_str(), JsonObject::get_member(), get_str_or_var(), member, and optional().
f_is_alive()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_alive (bool is_npc)
Definition at line 1235 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->get_is_alive();
     };
 }
f_is_avatar()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_avatar (bool is_npc)
Definition at line 1252 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->get_character() && d.actor( is_npc )->get_character()->is_avatar();
     };
 }
f_is_by_radio()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_by_radio ()
Definition at line 1757 of file condition.cpp.
 {
     return []( dialogue const & d ) {
         return d.by_radio;
     };
 }
f_is_character()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_character (bool is_npc)
Definition at line 1266 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->get_character();
     };
 }
f_is_day()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_day ()
Definition at line 1479 of file condition.cpp.
 {
     return []( dialogue const & ) {
         return !is_night( calendar::turn );
     };
 }
References is_night(), and calendar::turn.
f_is_deaf()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_deaf (bool is_npc)
Definition at line 1842 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->is_deaf();
     };
 }
f_is_driving()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_driving (bool is_npc)
Definition at line 1461 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         const talker *actor = d.actor( is_npc );
         if( const optional_vpart_position vp = get_map().veh_at( actor->pos() ) ) {
             return vp->vehicle().is_moving() && actor->is_in_control_of( vp->vehicle() );
         }
         return false;
     };
 }
References get_map(), talker::is_in_control_of(), talker::pos(), and map::veh_at().
f_is_female()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_female (bool is_npc)
Definition at line 1230 of file condition.cpp.
 {
     return f_is_gender( false, is_npc );
 }
References f_is_gender().
f_is_furniture()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_furniture (bool is_npc)
Definition at line 1287 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->get_computer();
     };
 }
f_is_gender()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_gender (bool is_male, bool is_npc)
Definition at line 1219 of file condition.cpp.
 {
     return [is_male, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->is_male() == is_male;
     };
 }
Referenced by f_is_female(), and f_is_male().
f_is_in_field()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_in_field (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1869 of file condition.cpp.
 {
     str_or_var field_type = get_str_or_var( jo.get_member( member ), member, true );
     return [field_type, is_npc]( dialogue const & d ) {
         map &here = get_map();
         field_type_id ft = field_type_id( field_type.evaluate( d ) );
         for( const std::pair<const field_type_id, field_entry> &f : here.field_at( d.actor(
                     is_npc )->pos() ) ) {
             if( f.second.get_field_type() == ft ) {
                 return true;
             }
         }
         return false;
     };
 }
References map::field_at(), get_map(), JsonObject::get_member(), get_str_or_var(), and member.
f_is_item()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_item (bool is_npc)
Definition at line 1280 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->get_item();
     };
 }
f_is_male()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_male (bool is_npc)
Definition at line 1226 of file condition.cpp.
 {
     return f_is_gender( true, is_npc );
 }
References f_is_gender().
f_is_monster()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_monster (bool is_npc)
Definition at line 1273 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->get_monster();
     };
 }
f_is_npc()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_npc (bool is_npc)
Definition at line 1259 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->get_npc();
     };
 }
f_is_on_terrain()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_on_terrain (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1849 of file condition.cpp.
 {
     str_or_var terrain_type = get_str_or_var( jo.get_member( member ), member, true );
     return [terrain_type, is_npc]( dialogue const & d ) {
         map &here = get_map();
         return here.ter( d.actor( is_npc )->pos() ) == ter_id( terrain_type.evaluate( d ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), get_map(), JsonObject::get_member(), get_str_or_var(), member, and map::ter().
f_is_on_terrain_with_flag()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_on_terrain_with_flag (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1859 of file condition.cpp.
 {
     str_or_var terrain_type = get_str_or_var( jo.get_member( member ), member, true );
     return [terrain_type, is_npc]( dialogue const & d ) {
         map &here = get_map();
         return here.ter( d.actor( is_npc )->pos() )->has_flag( terrain_type.evaluate( d ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), get_map(), JsonObject::get_member(), get_str_or_var(), map_data_common_t::has_flag(), member, and map::ter().
f_is_outside()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_outside (bool is_npc)
Definition at line 1486 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return is_creature_outside( *static_cast<talker const *>( d.actor( is_npc ) )->get_creature() );
     };
 }
References talker::get_creature(), and is_creature_outside().
f_is_riding() [1/2]
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_riding (bool is_npc)
Definition at line 691 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->is_mounted();
     };
 }
f_is_riding() [2/2]
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_riding (const JsonObject & , std::string_view , bool is_npc)
Definition at line 698 of file condition.cpp.
 {
     return f_is_riding( is_npc );
 }
f_is_season()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_season (const JsonObject & jo, std::string_view member)
Definition at line 1193 of file condition.cpp.
 {
     str_or_var season_name = get_str_or_var( jo.get_member( member ), member, true );
     return [season_name]( dialogue const & d ) {
         const season_type season = season_of_year( calendar::turn );
         return ( season == SPRING && season_name.evaluate( d ) == "spring" ) ||
                ( season == SUMMER && season_name.evaluate( d ) == "summer" ) ||
                ( season == AUTUMN && season_name.evaluate( d ) == "autumn" ) ||
                ( season == WINTER && season_name.evaluate( d ) == "winter" );
     };
 }
References AUTUMN, abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), member, season, season_of_year(), SPRING, SUMMER, calendar::turn, and WINTER.
f_is_underwater()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_underwater (bool is_npc)
Definition at line 1493 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return get_map().is_divable( d.actor( is_npc )->pos() );
     };
 }
References get_map(), and map::is_divable().
f_is_wearing()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_wearing (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 820 of file condition.cpp.
 {
     str_or_var item_id = get_str_or_var( jo.get_member( member ), member, true );
     return [item_id, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->is_wearing( itype_id( item_id.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_is_weather()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_is_weather (const JsonObject & jo, std::string_view member)
Definition at line 1591 of file condition.cpp.
 {
     str_or_var weather = get_str_or_var( jo.get_member( member ), member, true );
     return [weather]( dialogue const & d ) {
         return get_weather().weather_id == weather_type_id( weather.evaluate( d ) );
     };
 }
References JsonObject::get_member(), get_str_or_var(), get_weather(), member, and weather_manager::weather_id.
f_map_in_city()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_map_in_city (const JsonObject & jo, std::string_view member)
Definition at line 1639 of file condition.cpp.
 {
     str_or_var target = get_str_or_var( jo.get_member( member ), member, true );
     return [target]( dialogue const & d ) {
         tripoint_abs_ms target_pos = tripoint_abs_ms( tripoint::from_string( target.evaluate( d ) ) );
         city_reference c = overmap_buffer.closest_city( project_to<coords::sm>( target_pos ) );
         c.distance = rl_dist( c.abs_sm_pos, project_to<coords::sm>( target_pos ) );
         return c && c.get_distance_from_bounds() <= 0;
     };
 }
References c, overmapbuffer::closest_city(), abstract_str_or_var< T >::evaluate(), tripoint::from_string(), JsonObject::get_member(), get_str_or_var(), member, overmap_buffer, and rl_dist().
f_map_ter_furn_id()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_id (const JsonObject & jo, std::string_view member)
Definition at line 1619 of file condition.cpp.
 {
     str_or_var furn_type = get_str_or_var( jo.get_member( member ), member, true );
     var_info loc_var = read_var_info( jo.get_object( "loc" ) );
     bool terrain = true;
     if( member == "map_terrain_id" ) {
         terrain = true;
     } else if( member == "map_furniture_id" ) {
         terrain = false;
     }
     return [terrain, furn_type, loc_var]( dialogue const & d ) {
         tripoint loc = get_map().getlocal( get_tripoint_from_var( loc_var, d ) );
         if( terrain ) {
             return get_map().ter( loc ) == ter_id( furn_type.evaluate( d ) );
         } else {
             return get_map().furn( loc ) == furn_id( furn_type.evaluate( d ) );
         }
     };
 }
References abstract_str_or_var< T >::evaluate(), map::furn(), get_map(), JsonObject::get_member(), JsonObject::get_object(), get_str_or_var(), get_tripoint_from_var(), map::getlocal(), member, read_var_info(), map::ter(), and terrain.
f_map_ter_furn_with_flag()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_with_flag (const JsonObject & jo, std::string_view member)
Definition at line 1599 of file condition.cpp.
 {
     str_or_var furn_type = get_str_or_var( jo.get_member( member ), member, true );
     var_info loc_var = read_var_info( jo.get_object( "loc" ) );
     bool terrain = true;
     if( member == "map_terrain_with_flag" ) {
         terrain = true;
     } else if( member == "map_furniture_with_flag" ) {
         terrain = false;
     }
     return [terrain, furn_type, loc_var]( dialogue const & d ) {
         tripoint loc = get_map().getlocal( get_tripoint_from_var( loc_var, d ) );
         if( terrain ) {
             return get_map().ter( loc )->has_flag( furn_type.evaluate( d ) );
         } else {
             return get_map().furn( loc )->has_flag( furn_type.evaluate( d ) );
         }
     };
 }
References abstract_str_or_var< T >::evaluate(), map::furn(), get_map(), JsonObject::get_member(), JsonObject::get_object(), get_str_or_var(), get_tripoint_from_var(), map::getlocal(), map_data_common_t::has_flag(), member, read_var_info(), map::ter(), and terrain.
f_math()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_math (const JsonObject & jo, const std::string_view member)
Definition at line 1734 of file condition.cpp.
 {
     eoc_math math;
     math.from_json( jo, member, eoc_math::type_t::compare );
     return [math = std::move( math )]( dialogue & d ) {
         return math.act( d );
     };
 }
References eoc_math::act(), eoc_math::compare, eoc_math::from_json(), and member.
f_mission_complete()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_mission_complete (bool is_npc)
Definition at line 1348 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         mission *miss = d.actor( is_npc )->selected_mission();
         return miss && miss->is_complete( d.actor( is_npc )->getID() );
     };
 }
References mission::is_complete().
f_mission_failed()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_mission_failed (bool is_npc)
Definition at line 1364 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         mission *miss = d.actor( is_npc )->selected_mission();
         return miss && miss->has_failed();
     };
 }
References mission::has_failed().
f_mission_goal()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_mission_goal (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1205 of file condition.cpp.
 {
     str_or_var mission_goal_str = get_str_or_var( jo.get_member( member ), member, true );
     return [mission_goal_str, is_npc]( dialogue const & d ) {
         mission *miss = d.actor( is_npc )->selected_mission();
         if( !miss ) {
             return false;
         }
         const mission_goal mgoal = io::string_to_enum<mission_goal>( mission_goal_str.evaluate( d ) );
         return miss->get_type().goal == mgoal;
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), mission::get_type(), mission_type::goal, and member.
f_mission_has_generic_rewards()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_mission_has_generic_rewards ()
Definition at line 1792 of file condition.cpp.
 {
     return []( dialogue const & d ) {
         mission *miss = d.actor( true )->selected_mission();
         if( miss == nullptr ) {
             debugmsg( "mission_has_generic_rewards: mission_selected == nullptr" );
             return true;
         }
         return miss->has_generic_rewards();
     };
 }
References debugmsg, and mission::has_generic_rewards().
f_mission_incomplete()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_mission_incomplete (bool is_npc)
Definition at line 1356 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         mission *miss = d.actor( is_npc )->selected_mission();
         return miss && !miss->is_complete( d.actor( is_npc )->getID() );
     };
 }
References mission::is_complete().
f_mod_is_loaded()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_mod_is_loaded (const JsonObject & jo, std::string_view member)
Definition at line 1650 of file condition.cpp.
 {
     str_or_var compared_mod = get_str_or_var( jo.get_member( member ), member, true );
     return [compared_mod]( dialogue const & d ) {
         mod_id comp_mod = mod_id( compared_mod.evaluate( d ) );
         for( const mod_id &mod : world_generator->active_world->active_mod_order ) {
             if( comp_mod == mod ) {
                 return true;
             }
         }
         return false;
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), member, and world_generator.
f_near_om_location()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_near_om_location (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1010 of file condition.cpp.
 {
     str_or_var location = get_str_or_var( jo.get_member( member ), member, true );
     const dbl_or_var range = get_dbl_or_var( jo, "range", false, 1 );
     return [location, range, is_npc]( dialogue & d ) {
         const tripoint_abs_omt omt_pos = d.actor( is_npc )->global_omt_location();
         for( const tripoint_abs_omt &curr_pos : points_in_radius( omt_pos,
                 range.evaluate( d ) ) ) {
             const oter_id &omt_ter = overmap_buffer.ter( curr_pos );
             const std::optional<mapgen_arguments> *maybe_args = overmap_buffer.mapgen_args( omt_pos );
             const std::string &omt_str = omt_ter.id().str();
             std::string location_value = location.evaluate( d );
             if( location_value == "FACTION_CAMP_ANY" ) {
                 std::optional<basecamp *> bcp = overmap_buffer.find_camp( curr_pos.xy() );
                 if( bcp ) {
                     return true;
                 }
                 // TODO: legacy check to be removed once primitive field camp OMTs have been purged
                 if( omt_str.find( "faction_base_camp" ) != std::string::npos ) {
                     return true;
                 }
             } else if( location_value  == "FACTION_CAMP_START" &&
                        !recipe_group::get_recipes_by_id( "all_faction_base_types", omt_ter, maybe_args ).empty() ) {
                 return true;
             } else {
                 if( oter_no_dir( omt_ter ) == location_value ) {
                     return true;
                 }
             }
         }
         // should never get here this is for safety
         return false;
     };
 }
References dbl_or_var::evaluate(), overmapbuffer::find_camp(), get_dbl_or_var(), JsonObject::get_member(), recipe_group::get_recipes_by_id(), get_str_or_var(), int_id< T >::id(), location, overmapbuffer::mapgen_args(), member, oter_no_dir(), overmap_buffer, points_in_radius(), string_id< T >::str(), and overmapbuffer::ter().
f_need()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_need (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 960 of file condition.cpp.
 {
     str_or_var need = get_str_or_var( jo.get_member( member ), member, true );
     dbl_or_var dov;
     if( jo.has_int( "amount" ) ) {
         dov.min.dbl_val = jo.get_int( "amount" );
     } else if( jo.has_object( "amount" ) ) {
         dov = get_dbl_or_var( jo, "amount" );
     } else if( jo.has_string( "level" ) ) {
         const std::string &level = jo.get_string( "level" );
         auto flevel = sleepiness_level_strs.find( level );
         if( flevel != sleepiness_level_strs.end() ) {
             dov.min.dbl_val = static_cast<int>( flevel->second );
         }
     }
     return [need, dov, is_npc]( dialogue & d ) {
         const talker *actor = d.actor( is_npc );
         int amount = dov.evaluate( d );
         return ( actor->get_sleepiness() > amount && need.evaluate( d ) == "sleepiness" ) ||
                ( actor->get_hunger() > amount && need.evaluate( d ) == "hunger" ) ||
                ( actor->get_thirst() > amount && need.evaluate( d ) == "thirst" );
     };
 }
References dbl_or_var_part::dbl_val, dbl_or_var::evaluate(), abstract_str_or_var< T >::evaluate(), get_dbl_or_var(), talker::get_hunger(), JsonObject::get_int(), JsonObject::get_member(), talker::get_sleepiness(), get_str_or_var(), JsonObject::get_string(), talker::get_thirst(), JsonObject::has_int(), JsonObject::has_object(), JsonObject::has_string(), member, dbl_or_var::min, and sleepiness_level_strs.
f_no_assigned_mission()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_no_assigned_mission ()
Definition at line 1306 of file condition.cpp.
 {
     return []( dialogue const & d ) {
         return d.missions_assigned.empty();
     };
 }
f_no_available_mission()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_no_available_mission (bool is_npc)
Definition at line 1327 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->available_missions().empty();
     };
 }
f_npc_aim_rule()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_aim_rule (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1140 of file condition.cpp.
 {
     str_or_var setting = get_str_or_var( jo.get_member( member ), member, true );
     return [setting, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->has_ai_rule( "aim_rule", setting.evaluate( d ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_npc_allies()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_allies (const JsonObject & jo, std::string_view member)
Definition at line 1102 of file condition.cpp.
 {
     dbl_or_var dov = get_dbl_or_var( jo, member );
     return [dov]( dialogue & d ) {
         return g->allies().size() >= static_cast<std::vector<npc *>::size_type>( dov.evaluate( d ) );
     };
 }
References dbl_or_var::evaluate(), g, get_dbl_or_var(), and member.
f_npc_allies_global()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_allies_global (const JsonObject & jo, std::string_view member)
Definition at line 1110 of file condition.cpp.
 {
     dbl_or_var dov = get_dbl_or_var( jo, member );
     return [dov]( dialogue & d ) {
         const auto all_npcs = overmap_buffer.get_overmap_npcs();
         const size_t count = std::count_if( all_npcs.begin(),
         all_npcs.end(), []( const shared_ptr_fast<npc> &ptr ) {
             return ptr.get()->is_player_ally() && !ptr.get()->hallucination && !ptr.get()->is_dead();
         } );
         return count >= static_cast<size_t>( dov.evaluate( d ) );
     };
 }
References dbl_or_var::evaluate(), get_dbl_or_var(), overmapbuffer::get_overmap_npcs(), member, and overmap_buffer.
f_npc_available()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_available (bool is_npc)
Definition at line 1381 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return !d.actor( is_npc )->has_effect( effect_currently_busy, bodypart_str_id::NULL_ID() );
     };
 }
References effect_currently_busy, and string_id< body_part_type >::NULL_ID().
f_npc_cbm_recharge_rule()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_cbm_recharge_rule (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1167 of file condition.cpp.
 {
     str_or_var setting = get_str_or_var( jo.get_member( member ), member, true );
     return [setting, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->has_ai_rule( "cbm_recharge_rule", setting.evaluate( d ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_npc_cbm_reserve_rule()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_cbm_reserve_rule (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1158 of file condition.cpp.
 {
     str_or_var setting = get_str_or_var( jo.get_member( member ), member, true );
     return [setting, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->has_ai_rule( "cbm_reserve_rule", setting.evaluate( d ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_npc_engagement_rule()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_engagement_rule (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1149 of file condition.cpp.
 {
     str_or_var setting = get_str_or_var( jo.get_member( member ), member, true );
     return [setting, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->has_ai_rule( "engagement_rule", setting.evaluate( d ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_npc_following()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_following (bool is_npc)
Definition at line 1388 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->is_following();
     };
 }
f_npc_friend()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_friend (bool is_npc)
Definition at line 1395 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->is_friendly( get_player_character() );
     };
 }
References get_player_character().
f_npc_has_class()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_has_class (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 703 of file condition.cpp.
 {
     str_or_var class_to_check = get_str_or_var( jo.get_member( member ), member, true );
     return [class_to_check, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->is_myclass( npc_class_id( class_to_check.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_npc_hostile()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_hostile (bool is_npc)
Definition at line 1402 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->is_enemy();
     };
 }
f_npc_override()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_override (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1184 of file condition.cpp.
 {
     str_or_var rule = get_str_or_var( jo.get_member( member ), member, true );
     return [rule, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->has_ai_rule( "ally_override", rule.evaluate( d ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_npc_role_nearby()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_role_nearby (const JsonObject & jo, std::string_view member)
Definition at line 1089 of file condition.cpp.
 {
     str_or_var role = get_str_or_var( jo.get_member( member ), member, true );
     return [role]( dialogue const & d ) {
         const std::vector<npc *> available = g->get_npcs_if( [&]( const npc & guy ) {
             return d.actor( false )->posz() == guy.posz() &&
                    guy.companion_mission_role_id == role.evaluate( d ) &&
                    ( rl_dist( d.actor( false )->pos(), guy.pos() ) <= 48 );
         } );
         return !available.empty();
     };
 }
References available, npc::companion_mission_role_id, abstract_str_or_var< T >::evaluate(), g, JsonObject::get_member(), get_str_or_var(), member, Creature::pos(), Creature::posz(), and rl_dist().
f_npc_rule()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_rule (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1176 of file condition.cpp.
 {
     str_or_var rule = get_str_or_var( jo.get_member( member ), member, true );
     return [rule, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->has_ai_rule( "ally_rule", rule.evaluate( d ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_npc_service()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_service (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1372 of file condition.cpp.
 {
     dbl_or_var dov = get_dbl_or_var( jo, member );
     return [is_npc, dov]( dialogue & d ) {
         return !d.actor( is_npc )->has_effect( effect_currently_busy, bodypart_str_id::NULL_ID() ) &&
                d.actor( false )->cash() >= dov.evaluate( d );
     };
 }
References effect_currently_busy, dbl_or_var::evaluate(), get_dbl_or_var(), member, and string_id< body_part_type >::NULL_ID().
f_npc_train_skills()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_train_skills (bool is_npc)
Definition at line 1409 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return !d.actor( is_npc )->skills_offered_to( *d.actor( !is_npc ) ).empty();
     };
 }
f_npc_train_spells()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_train_spells (bool is_npc)
Definition at line 1423 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return !d.actor( is_npc )->spells_offered_to( *d.actor( !is_npc ) ).empty();
     };
 }
f_npc_train_styles()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_npc_train_styles (bool is_npc)
Definition at line 1416 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         return !d.actor( is_npc )->styles_offered_to( *d.actor( !is_npc ) ).empty();
     };
 }
f_one_in_chance()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_one_in_chance (const JsonObject & jo, std::string_view member)
Definition at line 1500 of file condition.cpp.
 {
     dbl_or_var dov = get_dbl_or_var( jo, member );
     return [dov]( dialogue & d ) {
         return one_in( dov.evaluate( d ) );
     };
 }
References dbl_or_var::evaluate(), get_dbl_or_var(), member, and one_in().
f_player_see()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_player_see (bool is_npc)
Definition at line 1294 of file condition.cpp.
 {
     return [is_npc]( dialogue const & d ) {
         const Creature *c = d.actor( is_npc )->get_creature();
         if( c ) {
             return get_player_view().sees( *c );
         } else {
             return get_player_view().sees( d.actor( is_npc )->pos() );
         }
     };
 }
References c, get_player_view(), and viewer::sees().
f_query()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_query (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1508 of file condition.cpp.
 {
     translation_or_var message = get_translation_or_var( jo.get_member( member ), member, true );
     bool default_val = jo.get_bool( "default" );
     return [message, default_val, is_npc]( dialogue const & d ) {
         const talker *actor = d.actor( is_npc );
         if( actor->get_character() && actor->get_character()->is_avatar() ) {
             std::string translated_message = message.evaluate( d );
             return query_yn( translated_message );
         } else {
             return default_val;
         }
     };
 }
References JsonObject::get_bool(), talker::get_character(), JsonObject::get_member(), get_translation_or_var(), Creature::is_avatar(), member, mapgen_defer::message, and query_yn().
f_query_tile()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1523 of file condition.cpp.
 {
     std::string type = jo.get_string( member.data() );
     var_info target_var = read_var_info( jo.get_object( "target_var" ) );
     std::string message;
     if( jo.has_member( "message" ) ) {
         message = jo.get_string( "message" );
     }
     dbl_or_var range;
     if( jo.has_member( "range" ) ) {
         range = get_dbl_or_var( jo, "range" );
     }
     bool z_level = jo.get_bool( "z_level", false );
     return [type, target_var, message, range, z_level, is_npc]( dialogue & d ) {
         std::optional<tripoint> loc;
         Character *ch = d.actor( is_npc )->get_character();
         if( ch && ch->as_avatar() ) {
             avatar *you = ch->as_avatar();
             if( type == "anywhere" ) {
                 if( !message.empty() ) {
                     static_popup popup;
                     popup.on_top( true );
                     popup.message( "%s", message );
                 }
                 tripoint center = d.actor( is_npc )->pos();
                 const look_around_params looka_params = { true, center, center, false, true, true, z_level };
                 loc = g->look_around( looka_params ).position;
             } else if( type == "line_of_sight" ) {
                 if( !message.empty() ) {
                     static_popup popup;
                     popup.on_top( true );
                     popup.message( "%s", message );
                 }
                 target_handler::trajectory traj = target_handler::mode_select_only( *you, range.evaluate( d ) );
                 if( !traj.empty() ) {
                     loc = traj.back();
                 }
             } else if( type == "around" ) {
                 if( !message.empty() ) {
                     loc = choose_adjacent( message );
                 } else {
                     loc = choose_adjacent( _( "Choose direction" ) );
                 }
             } else {
                 debugmsg( string_format( "Invalid selection type: %s", type ) );
             }
         }
         if( loc.has_value() ) {
             tripoint_abs_ms pos_global = get_map().getglobal( *loc );
             write_var_value( target_var.type, target_var.name, &d,
                              pos_global.to_string() );
         }
         return loc.has_value();
     };
 }
References _, Creature::as_avatar(), center, choose_adjacent(), debugmsg, dbl_or_var::evaluate(), g, JsonObject::get_bool(), get_dbl_or_var(), get_map(), JsonObject::get_object(), JsonObject::get_string(), map::getglobal(), JsonObject::has_member(), member, mapgen_defer::message, target_handler::mode_select_only(), abstract_var_info< T >::name, popup(), read_var_info(), string_format(), coords::coord_point_base< Point >::to_string(), abstract_var_info< T >::type, and write_var_value().
f_roll_contested()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_roll_contested (const JsonObject & jo, const std::string_view member)
Definition at line 1771 of file condition.cpp.
 {
     dbl_or_var get_check = get_dbl_or_var( jo, member );
     dbl_or_var difficulty = get_dbl_or_var( jo, "difficulty", true );
     dbl_or_var die_size = get_dbl_or_var( jo, "die_size", false, 10 );
     return [get_check, difficulty, die_size]( dialogue & d ) {
         return rng( 1, die_size.evaluate( d ) ) + get_check.evaluate( d ) >
                difficulty.evaluate( d );
     };
 }
References dbl_or_var::evaluate(), get_dbl_or_var(), member, and rng().
f_test_eoc()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_test_eoc (const JsonObject & jo, std::string_view member)
Definition at line 1708 of file condition.cpp.
 {
     str_or_var eocToTest = get_str_or_var( jo.get_member( member ), member, true );
     return [eocToTest]( dialogue & d ) {
         effect_on_condition_id tested( eocToTest.evaluate( d ) );
         if( !tested.is_valid() ) {
             debugmsg( "Invalid eoc id: %s", eocToTest.evaluate( d ) );
             return false;
         }
         return tested->condition( d );
     };
 }
References effect_on_condition::condition, debugmsg, abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), string_id< T >::is_valid(), and member.
f_u_are_owed()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_u_are_owed (const JsonObject & jo, std::string_view member)
Definition at line 1132 of file condition.cpp.
 {
     dbl_or_var dov = get_dbl_or_var( jo, member );
     return [dov]( dialogue & d ) {
         return d.actor( true )->debt() >= dov.evaluate( d );
     };
 }
References dbl_or_var::evaluate(), get_dbl_or_var(), and member.
f_u_has_camp()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_u_has_camp ()
Definition at line 1743 of file condition.cpp.
 {
     return []( dialogue const & ) {
         return !get_player_character().camps.empty();
     };
 }
References Character::camps, and get_player_character().
f_u_has_cash()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_u_has_cash (const JsonObject & jo, std::string_view member)
Definition at line 1124 of file condition.cpp.
 {
     dbl_or_var dov = get_dbl_or_var( jo, member );
     return [dov]( dialogue & d ) {
         return d.actor( false )->cash() >= dov.evaluate( d );
     };
 }
References dbl_or_var::evaluate(), get_dbl_or_var(), and member.
f_u_has_mission()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_u_has_mission (const JsonObject & jo, std::string_view member)
Definition at line 712 of file condition.cpp.
 {
     str_or_var u_mission = get_str_or_var( jo.get_member( member ), member, true );
     return [u_mission]( dialogue const & d ) {
         for( mission *miss_it : get_avatar().get_active_missions() ) {
             if( miss_it->mission_id() == mission_type_id( u_mission.evaluate( d ) ) ) {
                 return true;
             }
         }
         return false;
     };
 }
References abstract_str_or_var< T >::evaluate(), avatar::get_active_missions(), get_avatar(), JsonObject::get_member(), get_str_or_var(), and member.
f_u_know_recipe()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_u_know_recipe (const JsonObject & jo, std::string_view member)
Definition at line 1782 of file condition.cpp.
 {
     str_or_var known_recipe_id = get_str_or_var( jo.get_member( member ), member, true );
     return [known_recipe_id]( dialogue & d ) {
         const recipe &rep = recipe_id( known_recipe_id.evaluate( d ) ).obj();
         // should be a talker function but recipes aren't in Character:: yet
         return get_player_character().knows_recipe( &rep );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_player_character(), get_str_or_var(), Character::knows_recipe(), member, and string_id< T >::obj().
f_u_monsters_in_direction()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_u_monsters_in_direction (const JsonObject & jo, std::string_view member)
Definition at line 725 of file condition.cpp.
 {
     str_or_var dir = get_str_or_var( jo.get_member( member ), member, true );
     return [dir]( dialogue const & d ) {
         //This string_to_enum function is defined in widget.h. Should it be moved?
         const int card_dir = static_cast<int>( io::string_to_enum<cardinal_direction>( dir.evaluate(
                 d ) ) );
         int monster_count = get_avatar().get_mon_visible().unique_mons[card_dir].size();
         return monster_count > 0;
     };
 }
References abstract_str_or_var< T >::evaluate(), get_avatar(), JsonObject::get_member(), avatar::get_mon_visible(), get_str_or_var(), member, and monster_visible_info::unique_mons.
f_u_profession()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_u_profession (const JsonObject & jo, std::string_view member)
Definition at line 749 of file condition.cpp.
 {
     str_or_var u_profession = get_str_or_var( jo.get_member( member ), member, true );
     return [u_profession]( dialogue const & d ) {
         const profession *prof = get_player_character().get_profession();
         std::set<const profession *> hobbies = get_player_character().get_hobbies();
         if( prof->get_profession_id() == profession_id( u_profession.evaluate( d ) ) ) {
             return true;
         } else if( profession_id( u_profession.evaluate( d ) )->is_hobby() ) {
             for( const profession *hob : hobbies ) {
                 if( hob->get_profession_id() == profession_id( u_profession.evaluate( d ) ) ) {
                     return true;
                 }
                 break;
             }
             return false;
         } else {
             return false;
         }
     };
 }
References abstract_str_or_var< T >::evaluate(), Character::get_hobbies(), JsonObject::get_member(), get_player_character(), Character::get_profession(), profession::get_profession_id(), get_str_or_var(), profession::is_hobby(), and member.
f_u_safe_mode_trigger()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_u_safe_mode_trigger (const JsonObject & jo, std::string_view member)
Definition at line 738 of file condition.cpp.
 {
     str_or_var dir = get_str_or_var( jo.get_member( member ), member, true );
     return [dir]( dialogue const & d ) {
         //This string_to_enum function is defined in widget.h. Should it be moved?
         const int card_dir = static_cast<int>( io::string_to_enum<cardinal_direction>( dir.evaluate(
                 d ) ) );
         return get_avatar().get_mon_visible().dangerous[card_dir];
     };
 }
References monster_visible_info::dangerous, abstract_str_or_var< T >::evaluate(), get_avatar(), JsonObject::get_member(), avatar::get_mon_visible(), get_str_or_var(), and member.
f_using_martial_art()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_using_martial_art (const JsonObject & jo, std::string_view member, bool is_npc)
Definition at line 1905 of file condition.cpp.
 {
     str_or_var style_to_check = get_str_or_var( jo.get_member( member ), member, true );
     return [style_to_check, is_npc]( dialogue const & d ) {
         return d.actor( is_npc )->using_martial_art( matype_id( style_to_check.evaluate( d ) ) );
     };
 }
References abstract_str_or_var< T >::evaluate(), JsonObject::get_member(), get_str_or_var(), and member.
f_x_in_y_chance()
conditional_t::func conditional_fun::anonymous_namespace{condition.cpp}::f_x_in_y_chance (const JsonObject & jo, const std::string_view member)
Definition at line 1580 of file condition.cpp.
 {
     const JsonObject &var_obj = jo.get_object( member );
     dbl_or_var dovx = get_dbl_or_var( var_obj, "x" );
     dbl_or_var dovy = get_dbl_or_var( var_obj, "y" );
     return [dovx, dovy]( dialogue & d ) {
         return x_in_y( dovx.evaluate( d ),
                        dovy.evaluate( d ) );
     };
 }
References dbl_or_var::evaluate(), get_dbl_or_var(), JsonObject::get_object(), member, and x_in_y().