Cataclysm DDA: anonymous_namespace{overmap.cpp} Namespace Reference
anonymous_namespace{overmap.cpp} Namespace Reference
Variables
generic_factory< overmap_land_use_code > land_use_codes ("overmap land use codes")
generic_factory< oter_type_t > terrain_types ("overmap terrain type")
generic_factory< oter_t > terrains ("overmap terrain")
generic_factory< overmap_special > specials ("overmap special")
generic_factory< overmap_special_migration > migrations ("overmap special migration")
Variable Documentation
land_use_codes
generic_factory<overmap_land_use_code> anonymous_namespace{overmap.cpp}::land_use_codes("overmap land use codes") ("overmap land use codes")
Referenced by overmap_land_use_codes::check_consistency(), overmap_land_use_codes::finalize(), overmap_land_use_codes::get_all(), overmap_land_use_codes::load(), and overmap_land_use_codes::reset().
migrations
generic_factory<overmap_special_migration> anonymous_namespace{overmap.cpp}::migrations("overmap special migration") ("overmap special migration")
Referenced by overmap_special_migration::check(), Item_factory::clear(), Creature::load(), overmap_special_migration::load_migrations(), overmap_special_migration::migrate(), Item_factory::migrate_id(), Item_factory::migrate_item(), Item_factory::migrate_item_from_variant(), overmap_special_migration::migrated(), and overmap_special_migration::reset().
specials
generic_factory<overmap_special> anonymous_namespace{overmap.cpp}::specials("overmap special") ("overmap special")
Referenced by veh_interact::calc_overview(), overmap_specials::check_consistency(), overmap_specials::create_building_from(), overmapbuffer::create_custom_overmap(), overmap_specials::finalize(), overmap_specials::finalize_mapgen_parameters(), overmap_specials::get_all(), overmap_specials::get_default_batch(), overmap_specials::load(), overmap_special_batch::overmap_special_batch(), overmapbuffer::place_special(), and overmap_specials::reset().
terrain_types
generic_factory<oter_type_t> anonymous_namespace{overmap.cpp}::terrain_types("overmap terrain type") ("overmap terrain type")
Referenced by overmap_terrains::check_consistency(), overmap_terrains::finalize(), string_id< T >::id(), overmap_terrains::load(), int_id< T >::obj(), string_id< T >::obj(), and overmap_terrains::reset().
terrains
generic_factory<oter_t> anonymous_namespace{overmap.cpp}::terrains("overmap terrain") ("overmap terrain")
Referenced by overmap_terrains::check_consistency(), overmap_terrains::get_all(), get_changed_ids_from_update(), int_id< T >::id(), int_id< T >::is_valid(), int_id< T >::obj(), oter_type_t::register_terrain(), overmap_terrains::reset(), and mission_util::set_reveal_any().