Cataclysm DDA: liquid_handler Namespace Reference
liquid_handler Namespace Reference
Functions
void handle_all_liquid (item liquid, int radius, const item *avoid=nullptr)
Consume / handle all of the liquid.
bool consume_liquid (item &liquid, int radius=0, const item *avoid=nullptr)
Consume / handle as much of the liquid as possible in varying ways.
bool handle_liquid_from_ground (const map_stack::iterator &on_ground, const tripoint &pos, int radius=0)
Handle finite liquid from ground.
bool handle_liquid_from_container (item *in_container, item &container, int radius=0)
Handle liquid from inside a container item.
bool handle_liquid_from_container (item &container, int radius=0)
Shortcut to the above: handles the first item in the container.
static bool get_liquid_target (item &liquid, const item *const source, const int radius, const tripoint *const source_pos, const vehicle *const source_veh, const monster *const source_mon, liquid_dest_opt &target)
bool perform_liquid_transfer (item &liquid, const tripoint *const source_pos, const vehicle *const source_veh, const int part_num, const monster *const, liquid_dest_opt &target)
bool can_handle_liquid (const item &liquid)
bool handle_liquid (item &liquid, const item *source=nullptr, int radius=0, const tripoint *source_pos=nullptr, const vehicle *source_veh=nullptr, int part_num=-1, const monster *source_mon=nullptr)
This may start a player activity if either source_pos or source_veh is not null.
Function Documentation
can_handle_liquid()
bool liquid_handler::can_handle_liquid (const item & liquid)
Definition at line 444 of file handle_liquid.cpp.
 {
     if( liquid.made_of_from_type( phase_id::SOLID ) ) {
         dbg( D_ERROR ) << "game:handle_liquid: Tried to handle_liquid a non-liquid!";
         debugmsg( "Tried to handle_liquid a non-liquid!" );
         // "canceled by the user" because we *can* not handle it.
         return false;
     }
     if( !liquid.made_of( phase_id::LIQUID ) ) {
         add_msg( _( "The %s froze solid before you could finish." ), liquid.tname() );
         return false;
     }
     return true;
 }
References _, add_msg(), D_ERROR, dbg, debugmsg, LIQUID, item::made_of(), item::made_of_from_type(), SOLID, and item::tname().
Referenced by handle_all_liquid(), and handle_liquid().
consume_liquid()
bool liquid_handler::consume_liquid (item & liquid, int radius = 0, const item * avoid = nullptr)
Consume / handle as much of the liquid as possible in varying ways.
This function can be used when the action can be canceled, which implies the liquid can be put back to wherever it came from and is not lost if the player cancels the action. It returns when all liquid has been handled or if the player has explicitly canceled the action (use the charges count to distinguish).
Returns
Whether any of the liquid has been consumed. false indicates the player has declined all options to handle the liquid and no charges of the liquid have been transferred. true indicates some charges have been transferred (but not necessarily all of them).
Definition at line 117 of file handle_liquid.cpp.
 {
     const int original_charges = liquid.charges;
     while( liquid.charges > 0 && handle_liquid( liquid, avoid, radius ) ) {
         // try again with the remaining charges
     }
     return original_charges != liquid.charges;
 }
References item::charges, and handle_liquid().
Referenced by Character::activate_bionic(), and Character::add_or_drop_with_msg().
get_liquid_target()
static bool liquid_handler::get_liquid_target (item & liquid, const item *const source, const int radius, const tripoint *const source_pos, const vehicle *const source_veh, const monster *const source_mon, liquid_dest_opt & target) static
Definition at line 168 of file handle_liquid.cpp.
 {
     if( !liquid.made_of_from_type( phase_id::LIQUID ) ) {
         dbg( D_ERROR ) << "game:handle_liquid: Tried to handle_liquid a non-liquid!";
         debugmsg( "Tried to handle_liquid a non-liquid!" );
         // "canceled by the user" because we *can* not handle it.
         return false;
     }
     Character &player_character = get_player_character();
     if( test_mode ) {
         switch( test_mode_spilling_action ) {
             case test_mode_spilling_action_t::spill_all:
                 target.pos = player_character.pos();
                 target.dest_opt = LD_GROUND;
                 return true;
             case test_mode_spilling_action_t::cancel_spill:
                 return false;
         }
     }
     uilist menu;
     map &here = get_map();
     const std::string liquid_name = liquid.display_name( liquid.charges );
     if( source_pos != nullptr ) {
         //~ %1$s: liquid name, %2$s: terrain name
         menu.text = string_format( pgettext( "liquid", "What to do with the %1$s from %2$s?" ), liquid_name,
                                    here.name( *source_pos ) );
     } else if( source_veh != nullptr ) {
         //~ %1$s: liquid name, %2$s: vehicle name
         menu.text = string_format( pgettext( "liquid", "What to do with the %1$s from %2$s?" ), liquid_name,
                                    source_veh->disp_name() );
     } else if( source_mon != nullptr ) {
         //~ %1$s: liquid name, %2$s: monster name
         menu.text = string_format( pgettext( "liquid", "What to do with the %1$s from the %2$s?" ),
                                    liquid_name, source_mon->get_name() );
     } else if( source != nullptr ) {
         if( source->is_bucket_nonempty() ) {
             menu.text = string_format( pgettext( "liquid",
                                                  //~ %1$s: liquid name, %2$s: container name
                                                  "The %1$s would spill.\nWhat to do with the %2$s inside it?" ),
                                        source->display_name(), liquid_name );
         } else {
             //~ %1$s: liquid name, %2$s: container name
             menu.text = string_format( pgettext( "liquid", "What to do with the %1$s in the %2$s?" ),
                                        liquid_name, source->display_name() );
         }
     } else {
         //~ %s: liquid name
         menu.text = string_format( pgettext( "liquid", "What to do with the %s?" ), liquid_name );
     }
     std::vector<std::function<void()>> actions;
     if( player_character.can_consume_as_is( liquid ) && !source_mon && ( source_veh || source_pos ) ) {
         menu.addentry( -1, true, 'e', _( "Consume it" ) );
         actions.emplace_back( [&]() {
             target.dest_opt = LD_CONSUME;
         } );
     }
     // This handles containers found anywhere near the player, including on the map and in vehicle storage.
     menu.addentry( -1, true, 'c', _( "Pour into a container" ) );
     actions.emplace_back( [&]() {
         target.item_loc = game_menus::inv::container_for( player_character, liquid,
                           radius, /*avoid=*/source );
         item *const cont = target.item_loc.get_item();
         if( cont == nullptr || cont->is_null() ) {
             add_msg( _( "Never mind." ) );
             return;
         }
         // Sometimes the cont parameter is omitted, but the liquid is still within a container that counts
         // as valid target for the liquid. So check for that.
         if( cont == source || ( !cont->empty() && cont->has_item( liquid ) ) ) {
             add_msg( m_info, _( "That's the same container!" ) );
             return; // The user has intended to do something, but mistyped.
         }
         target.dest_opt = LD_ITEM;
     } );
     // This handles liquids stored in vehicle parts directly (e.g. tanks).
     std::set<vehicle *> opts;
     for( const tripoint &e : here.points_in_radius( player_character.pos(), 1 ) ) {
         vehicle *veh = veh_pointer_or_null( here.veh_at( e ) );
         if( veh ) {
             vehicle_part_range vpr = veh->get_all_parts();
             const auto veh_accepts_liquid = [&liquid]( const vpart_reference & pt ) {
                 return pt.part().can_reload( liquid );
             };
             if( std::any_of( vpr.begin(), vpr.end(), veh_accepts_liquid ) ) {
                 opts.insert( veh );
             }
         }
     }
     for( vehicle *veh : opts ) {
         if( veh == source_veh && veh->has_part( "FLUIDTANK", false ) ) {
             for( const vpart_reference &vp : veh->get_avail_parts( "FLUIDTANK" ) ) {
                 if( vp.part().get_base().can_reload_with( liquid, true ) ) {
                     menu.addentry( -1, true, MENU_AUTOASSIGN, _( "Fill available tank" ) );
                     actions.emplace_back( [ &, veh]() {
                         target.veh = veh;
                         target.dest_opt = LD_VEH;
                     } );
                     break;
                 }
             }
         } else {
             menu.addentry( -1, true, MENU_AUTOASSIGN, _( "Fill nearby vehicle %s" ), veh->name );
             actions.emplace_back( [ &, veh]() {
                 target.veh = veh;
                 target.dest_opt = LD_VEH;
             } );
         }
     }
     for( const tripoint &target_pos : here.points_in_radius( player_character.pos(), 1 ) ) {
         if( !iexamine::has_keg( target_pos ) ) {
             continue;
         }
         if( source_pos != nullptr && *source_pos == target_pos ) {
             continue;
         }
         const std::string dir = direction_name( direction_from( player_character.pos(), target_pos ) );
         menu.addentry( -1, true, MENU_AUTOASSIGN, _( "Pour into an adjacent keg (%s)" ), dir );
         actions.emplace_back( [ &, target_pos]() {
             target.pos = target_pos;
             target.dest_opt = LD_KEG;
         } );
     }
     menu.addentry( -1, true, 'g', _( "Pour on the ground" ) );
     actions.emplace_back( [&]() {
         // From infinite source to the ground somewhere else. The target has
         // infinite space and the liquid can not be used from there anyway.
         if( liquid.has_infinite_charges() && source_pos != nullptr ) {
             add_msg( m_info, _( "Clearing out the %s would take forever." ), here.name( *source_pos ) );
             return;
         }
         const std::string liqstr = string_format( _( "Pour %s where?" ), liquid_name );
         const std::optional<tripoint> target_pos_ = choose_adjacent( liqstr );
         if( !target_pos_ ) {
             return;
         }
         target.pos = *target_pos_;
         if( source_pos != nullptr && *source_pos == target.pos ) {
             add_msg( m_info, _( "That's where you took it from!" ) );
             return;
         }
         if( !here.can_put_items_ter_furn( target.pos ) ) {
             add_msg( m_info, _( "You can't pour there!" ) );
             return;
         }
         target.dest_opt = LD_GROUND;
     } );
     if( liquid.rotten() ) {
         // Pre-select this one as it is the most likely one for rotten liquids
         menu.selected = menu.entries.size() - 1;
     }
     if( menu.entries.empty() ) {
         return false;
     }
     while( target.dest_opt == LD_NULL ) {
         menu.query();
         if( menu.ret < 0 || static_cast<size_t>( menu.ret ) >= actions.size() ) {
             add_msg( _( "Never mind." ) );
             // Explicitly canceled all options (container, drink, pour).
             return false;
         }
         actions[menu.ret]();
     }
     return true;
 }
References _, add_msg(), uilist::addentry(), generic_vehicle_part_range< range_type >::begin(), Character::can_consume_as_is(), map::can_put_items_ter_furn(), cancel_spill, item::charges, choose_adjacent(), game_menus::inv::container_for(), D_ERROR, dbg, debugmsg, liquid_dest_opt::dest_opt, direction_from(), direction_name(), vehicle::disp_name(), item::display_name(), item::empty(), generic_vehicle_part_range< range_type >::end(), uilist::entries, vehicle::get_all_parts(), item_location::get_item(), get_map(), monster::get_name(), get_player_character(), item::has_infinite_charges(), visitable::has_item(), iexamine::has_keg(), vehicle::has_part(), item::is_bucket_nonempty(), item::is_null(), liquid_dest_opt::item_loc, LD_CONSUME, LD_GROUND, LD_ITEM, LD_KEG, LD_NULL, LD_VEH, LIQUID, m_info, item::made_of_from_type(), MENU_AUTOASSIGN, map::name(), pgettext, map::points_in_radius(), Creature::pos(), liquid_dest_opt::pos, uilist::query(), uilist::ret, item::rotten(), uilist::selected, spill_all, string_format(), test_mode, test_mode_spilling_action, uilist::text, liquid_dest_opt::veh, map::veh_at(), and veh_pointer_or_null().
Referenced by handle_liquid().
handle_all_liquid()
void liquid_handler::handle_all_liquid (item liquid, int radius, const item * avoid = nullptr)
Consume / handle all of the liquid.
The function can be used when the liquid needs to be handled and can not be put back to where it came from (e.g. when it's a newly created item from crafting). The player is forced to handle all of it, which may required them to pour it onto the ground (if they don't have enough container space available) and essentially loose the item.
Returns
Whether any of the liquid has been consumed. false indicates the player has declined all options to handle the liquid (essentially canceled the action) and no charges of the liquid have been transferred. true indicates some charges have been transferred (but not necessarily all of them).
Definition at line 107 of file handle_liquid.cpp.
 {
     while( liquid.charges > 0 && can_handle_liquid( liquid ) ) {
         // handle_liquid allows to pour onto the ground, which will handle all the liquid and
         // set charges to 0. This allows terminating the loop.
         // The result of handle_liquid is ignored, the player *has* to handle all the liquid.
         handle_liquid( liquid, avoid, radius );
     }
 }
References can_handle_liquid(), item::charges, and handle_liquid().
Referenced by butchery_drops_harvest(), Character::complete_disassemble(), drop_or_handle(), iuse::multicooker(), set_item_inventory(), and spawn_items().
handle_liquid()
bool liquid_handler::handle_liquid (item & liquid, const item * source = nullptr, int radius = 0, const tripoint * source_pos = nullptr, const vehicle * source_veh = nullptr, int part_num = -1, const monster * source_mon = nullptr)
This may start a player activity if either source_pos or source_veh is not null.
The function consumes moves of the player as needed. Supply one of the source parameters to prevent the player from pouring the liquid back into that "container". If no source parameter is given, the liquid must not be in a container at all (e.g. freshly crafted, or already removed from the container).
Parameters
liquid The actual liquid
source The container that currently contains the liquid.
radius Radius to look for liquid around pos
source_pos The source of the liquid when it's from the map.
source_veh The vehicle that currently contains the liquid in its tank.
Returns
Whether the user has handled the liquid (at least part of it). false indicates the user has rejected all possible actions. But note that true does not indicate any liquid was actually consumed, the user may have chosen an option that turned out to be invalid (chose to fill into a full/unsuitable container). Basically false indicates the user does not want to handle the liquid, true indicates they want to handle it.
Definition at line 459 of file handle_liquid.cpp.
 {
     bool success = false;
     if( !can_handle_liquid( liquid ) ) {
         return false;
     }
     struct liquid_dest_opt liquid_target;
     if( get_liquid_target( liquid, source, radius, source_pos, source_veh, source_mon,
                            liquid_target ) ) {
         success = perform_liquid_transfer( liquid, source_pos, source_veh, part_num, source_mon,
                                            liquid_target );
         if( success && ( ( liquid_target.dest_opt == LD_ITEM &&
                            liquid_target.item_loc->is_watertight_container() ) || liquid_target.dest_opt == LD_KEG ) ) {
             liquid.unset_flag( flag_id( json_flag_FROM_FROZEN_LIQUID ) );
         }
         return success;
     }
     return false;
 }
References can_handle_liquid(), liquid_dest_opt::dest_opt, flag_id, get_liquid_target(), item::is_watertight_container(), liquid_dest_opt::item_loc, json_flag_FROM_FROZEN_LIQUID, LD_ITEM, LD_KEG, perform_liquid_transfer(), and item::unset_flag().
Referenced by act_vehicle_siphon(), consume_liquid(), veh_interact::do_siphon(), milk_activity_actor::finish(), handle_all_liquid(), handle_liquid_from_container(), handle_liquid_from_ground(), item_pocket::handle_liquid_or_spill(), veh_app_interact::siphon(), and iexamine::water_source().
handle_liquid_from_container() [1/2]
bool liquid_handler::handle_liquid_from_container (item & container, int radius)
Shortcut to the above: handles the first item in the container.
Definition at line 152 of file handle_liquid.cpp.
 {
     std::vector<item *> remove;
     bool handled = false;
     for( item *contained : container.all_items_top() ) {
         if( handle_liquid_from_container( contained, container, radius ) ) {
             remove.push_back( contained );
             handled = true;
         }
     }
     for( item *contained : remove ) {
         container.remove_item( *contained );
     }
     return handled;
 }
References item::all_items_top(), handle_liquid_from_container(), remove, and visitable::remove_item().
handle_liquid_from_container() [2/2]
bool liquid_handler::handle_liquid_from_container (item * in_container, item & container, int radius = 0)
Handle liquid from inside a container item.
The function also handles consuming move points.
Parameters
in_container Iterator to the liquid. Must be valid and point to an item in the item::contents of the container.
container Container of the liquid
radius around position to handle liquid for
Returns
Whether the item has been removed (which implies it was handled completely). The iterator is invalidated in that case. Otherwise the item remains but may have fewer charges.
Definition at line 139 of file handle_liquid.cpp.
 {
     // TODO: not all code paths on handle_liquid consume move points, fix that.
     const int old_charges = in_container->charges;
     handle_liquid( *in_container, &container, radius );
     if( in_container->charges != old_charges ) {
         container.on_contents_changed();
     }
     return in_container->charges <= 0;
 }
References item::charges, handle_liquid(), and item::on_contents_changed().
Referenced by handle_liquid_from_container(), and iexamine::tree_maple_tapped().
handle_liquid_from_ground()
bool liquid_handler::handle_liquid_from_ground (const map_stack::iterator & on_ground, const tripoint & pos, int radius = 0)
Handle finite liquid from ground.
The function also handles consuming move points. This may start a player activity.
Parameters
on_ground Iterator to the item on the ground. Must be valid and point to an item in the stack at m.i_at(pos)
pos The position of the item on the map.
radius around position to handle liquid for
Returns
Whether the item has been removed (which implies it was handled completely). The iterator is invalidated in that case. Otherwise the item remains but may have fewer charges.
Definition at line 126 of file handle_liquid.cpp.
 {
     // TODO: not all code paths on handle_liquid consume move points, fix that.
     handle_liquid( *on_ground, nullptr, radius, &pos );
     if( on_ground->charges > 0 ) {
         return false;
     }
     get_map().i_at( pos ).erase( on_ground );
     return true;
 }
References map_stack::erase(), get_map(), handle_liquid(), map::i_at(), and math_opers::pos().
Referenced by iexamine::compost_empty(), iexamine::compost_full(), iexamine::finite_water_source(), iexamine::fvat_empty(), iexamine::fvat_full(), iexamine::gaspump(), and iexamine::keg().
perform_liquid_transfer()
bool liquid_handler::perform_liquid_transfer (item & liquid, const tripoint *const source_pos, const vehicle *const source_veh, const int part_num, const monster * const , liquid_dest_opt & target)
Definition at line 350 of file handle_liquid.cpp.
 {
     if( !liquid.made_of_from_type( phase_id::LIQUID ) ) {
         dbg( D_ERROR ) << "game:handle_liquid: Tried to handle_liquid a non-liquid!";
         debugmsg( "Tried to handle_liquid a non-liquid!" );
         // "canceled by the user" because we *can* not handle it.
         return false;
     }
     Character &player_character = get_player_character();
     const auto create_activity = [&]() {
         if( source_veh != nullptr ) {
             player_character.assign_activity( ACT_FILL_LIQUID );
             serialize_liquid_source( player_character.activity, *source_veh, part_num, liquid );
             return true;
         } else if( source_pos != nullptr ) {
             player_character.assign_activity( ACT_FILL_LIQUID );
             serialize_liquid_source( player_character.activity, *source_pos, liquid );
             return true;
         } else {
             return false;
         }
     };
     map &here = get_map();
     switch( target.dest_opt ) {
         case LD_CONSUME:
             player_character.assign_activity( consume_activity_actor( liquid ) );
             liquid.charges--;
             return true;
         case LD_ITEM: {
             // Currently activities can only store item position in the players inventory,
             // not on ground or similar. TODO: implement storing arbitrary container locations.
             if( target.item_loc && create_activity() ) {
                 serialize_liquid_target( player_character.activity, target.item_loc );
             } else if( player_character.pour_into( target.item_loc, liquid, true ) ) {
                 target.item_loc.make_active();
                 player_character.mod_moves( -100 );
             }
             return true;
         }
         case LD_VEH: {
             if( target.veh == nullptr ) {
                 return false;
             }
             auto sel = [&]( const vehicle_part & pt ) {
                 return pt.is_tank() && pt.can_reload( liquid );
             };
             const units::volume stack = units::legacy_volume_factor / liquid.type->stack_size;
             const std::string title = string_format( _( "Select target tank for <color_%s>%.1fL %s</color>" ),
                                       get_all_colors().get_name( liquid.color() ),
                                       round_up( to_liter( liquid.charges * stack ), 1 ),
                                       liquid.tname() );
             const std::optional<vpart_reference> vpr = veh_interact::select_part( *target.veh, sel, title );
             if( !vpr ) {
                 return false;
             }
             if( create_activity() ) {
                 serialize_liquid_target( player_character.activity, *vpr );
                 return true;
             } else if( player_character.pour_into( *vpr, liquid ) ) {
                 // this branch is used in milking and magiclysm butchery blood draining
                 player_character.mod_moves( -1000 ); // consistent with veh_interact::do_refill activity
                 return true;
             } else {
                 // unclear what can reach this branch but return false just in case
                 return false;
             }
         }
         case LD_KEG:
         case LD_GROUND:
             if( create_activity() ) {
                 serialize_liquid_target( player_character.activity, target.pos );
             } else {
                 if( target.dest_opt == LD_KEG ) {
                     iexamine::pour_into_keg( target.pos, liquid );
                 } else {
                     here.add_item_or_charges( target.pos, liquid );
                     liquid.charges = 0;
                 }
                 player_character.mod_moves( -100 );
             }
             return true;
         case LD_NULL:
         default:
             return false;
     }
 }
References _, ACT_FILL_LIQUID, Character::activity, map::add_item_or_charges(), Character::assign_activity(), item::charges, item::color(), D_ERROR, dbg, debugmsg, liquid_dest_opt::dest_opt, get_all_colors(), get_map(), get_player_character(), liquid_dest_opt::item_loc, LD_CONSUME, LD_GROUND, LD_ITEM, LD_KEG, LD_NULL, LD_VEH, units::legacy_volume_factor, LIQUID, item::made_of_from_type(), item_location::make_active(), Creature::mod_moves(), liquid_dest_opt::pos, Character::pour_into(), iexamine::pour_into_keg(), round_up(), veh_interact::select_part(), serialize_liquid_source(), serialize_liquid_target(), itype::stack_size, string_format(), music::title, item::tname(), units::to_liter(), item::type, and liquid_dest_opt::veh.
Referenced by handle_liquid().