Cataclysm DDA: std::this_thread Namespace Reference
std::this_thread Namespace Reference
Functions
thread::id get_id ()
void yield ()
template<class Rep , class Period >
void sleep_for (const std::chrono::duration< Rep, Period > &sleep_duration)
template<class Clock , class Duration >
void sleep_until (const std::chrono::time_point< Clock, Duration > &sleep_time)
Function Documentation
get_id()
thread::id std::this_thread::get_id () inline
Definition at line 124 of file mingw.thread.h.
 {
     return thread::id( GetCurrentThreadId() );
 }
References base_camps::id.
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_has_item_category(), json_talk_topic::gen_responses(), itype::is_basic_component(), wish_item_callback::refresh(), and item::stacks_with().
sleep_for()
template<class Rep , class Period > void std::this_thread::sleep_for (const std::chrono::duration< Rep, Period > & sleep_duration)
Definition at line 133 of file mingw.thread.h.
 {
     Sleep( chrono::duration_cast<chrono::milliseconds>( sleep_duration ).count() );
 }
Referenced by robot_finds_kitten::process_input(), anonymous_namespace{animation.cpp}::basic_animation::progress(), and sleep_until().
sleep_until()
template<class Clock , class Duration > void std::this_thread::sleep_until (const std::chrono::time_point< Clock, Duration > & sleep_time)
Definition at line 138 of file mingw.thread.h.
 {
     sleep_for( sleep_time - Clock::now() );
 }
References sleep_for().
yield()
void std::this_thread::yield () inline
Definition at line 128 of file mingw.thread.h.
 {
     Sleep( 0 );
 }