Cataclysm DDA: morale_mults Namespace Reference
morale_mults Namespace Reference
Variables
static const morale_mult optimist (1.2, 0.8)
static const morale_mult badtemper (0.8, 1.2)
static const morale_mult numb (0.25, 0.25)
static const morale_mult prozac (1.0, 0.25)
static const morale_mult prozac_bad (0.25, 1.0)
Variable Documentation
badtemper
const morale_mult morale_mults::badtemper(0.8, 1.2) (0. 8, 1. 2) static
Referenced by player_morale::get_temper_mult().
numb
const morale_mult morale_mults::numb(0.25, 0.25) (0. 25, 0. 25) static
Referenced by player_morale::get_temper_mult(), and Character::modify_morale().
optimist
const morale_mult morale_mults::optimist(1.2, 0.8) (1. 2, 0. 8) static
Referenced by player_morale::get_temper_mult().
prozac
const morale_mult morale_mults::prozac(1.0, 0.25) (1. 0, 0. 25) static
Referenced by player_morale::get_level().
prozac_bad
const morale_mult morale_mults::prozac_bad(0.25, 1.0) (0. 25, 1. 0) static
Referenced by player_morale::get_level().