Cataclysm DDA: cataimgui Namespace Reference
cataimgui Namespace Reference
Classes
class window_impl
class filter_box_impl
struct bounds
class client
class window
Enumerations
enum class mbox_btn { BT_OK = 0 , BT_OKCancel = 1 , BT_YesNoCancel = 2 , BT_YesNo = 3 }
enum class dialog_result {
None = 0 , OKClicked , CancelClicked , YesClicked ,
NoClicked
}
Functions
void point_to_imvec2 (point *src, ImVec2 *dest)
void imvec2_to_point (ImVec2 *src, point *dest)
void init_pair (int p, int f, int b)
void load_colors ()
Enumeration Type Documentation
dialog_result
enum cataimgui::dialog_result strong
Enumerator
None
OKClicked
CancelClicked
YesClicked
NoClicked
Definition at line 36 of file cata_imgui.h.
{
     None = 0,
     OKClicked,
     CancelClicked,
     YesClicked,
     NoClicked
 };
mbox_btn
enum cataimgui::mbox_btn strong
Enumerator
BT_OK
BT_OKCancel
BT_YesNoCancel
BT_YesNo
Definition at line 29 of file cata_imgui.h.
                     {
     BT_OK = 0,
     BT_OKCancel = 1,
     BT_YesNoCancel = 2,
     BT_YesNo = 3
 };
Function Documentation
imvec2_to_point()
void cataimgui::imvec2_to_point (ImVec2 * src, point * dest)
Definition at line 343 of file cata_imgui.cpp.
 {
     if( src != nullptr && dest != nullptr ) {
         dest->x = src->x;
         dest->y = src->y;
     }
 }
References point::x, and point::y.
Referenced by cataimgui::window::draw().
init_pair()
void cataimgui::init_pair (int p, int f, int b)
Definition at line 144 of file cata_imgui.cpp.
 {
     colorpairs[p].FG = f;
     colorpairs[p].BG = b;
 }
References b, and colorpairs.
Referenced by catacurses::init_pair(), inv_internal(), and cataimgui::client::upload_color_pair().
load_colors()
void cataimgui::load_colors ()
Definition at line 138 of file cata_imgui.cpp.
 {
     color_loader<RGBTuple>().load( rgbPalette );
 }
References color_loader< ColorType >::load(), and rgbPalette.
Referenced by cataimgui::client::client().
point_to_imvec2()
void cataimgui::point_to_imvec2 (point * src, ImVec2 * dest)
Definition at line 335 of file cata_imgui.cpp.
 {
     if( src != nullptr && dest != nullptr ) {
         dest->x = src->x;
         dest->y = src->y;
     }
 }
References point::x, and point::y.