Cataclysm DDA: anonymous_namespace{martialarts.cpp} Namespace Reference
anonymous_namespace{martialarts.cpp} Namespace Reference
Variables
generic_factory< weapon_category > weapon_category_factory ("weapon category")
generic_factory< ma_technique > ma_techniques ("martial art technique")
generic_factory< martialart > martialarts ("martial art style")
generic_factory< ma_buff > ma_buffs ("martial art buff")
Variable Documentation
ma_buffs
generic_factory<ma_buff> anonymous_namespace{martialarts.cpp}::ma_buffs("martial art buff") ("martial art buff")
Referenced by check_martialarts(), clear_techniques_and_martial_arts(), finalize_martial_arts(), and ma_buff_reader::get_next().
ma_techniques
generic_factory<ma_technique> anonymous_namespace{martialarts.cpp}::ma_techniques("martial art technique") ("martial art technique")
Referenced by check_martialarts(), clear_techniques_and_martial_arts(), and load_technique().
martialarts
generic_factory<martialart> anonymous_namespace{martialarts.cpp}::martialarts("martial art style") ("martial art style")
Referenced by all_martialart_types(), autolearn_martialart_types(), check_martialarts(), clear_techniques_and_martial_arts(), and load_martial_art().
weapon_category_factory
generic_factory<weapon_category> anonymous_namespace{martialarts.cpp}::weapon_category_factory("weapon category") ("weapon category")
Referenced by weapon_category::get_all(), weapon_category::load_weapon_categories(), weapon_category::reset(), and weapon_category::verify_weapon_categories().