Cataclysm DDA: anonymous_namespace{armor_layers.cpp} Namespace Reference
anonymous_namespace{armor_layers.cpp} Namespace Reference
Classes
struct mid_pane_status
Functions
std::string clothing_layer (const item &worn_item)
std::vector< std::string > clothing_properties (const item &worn_item, int width, const Character &, const bodypart_id &bp)
std::vector< std::string > clothing_protection (const item &worn_item, int width, const bodypart_id &bp)
std::vector< std::string > clothing_flags_description (const item &worn_item, int width)
std::string body_part_names (const std::vector< bodypart_id > &parts)
mid_pane_status draw_mid_pane (const catacurses::window &w_sort_middle, std::list< item >::const_iterator const worn_item_it, Character &c, const bodypart_id &bp, mid_pane_status &status)
void add_category_and_values (std::vector< std::string > &current_text, const int field_width, const std::string &category_name, const std::vector< std::pair< std::string, std::string >> &names_and_values)
std::vector< std::pair< std::string, std::string > > collect_protection_subvalues (const resistances &worst_res, const resistances &best_res, const resistances &median_res, const bool display_median, const damage_type_id &type)
Function Documentation
add_category_and_values()
void anonymous_namespace{armor_layers.cpp}::add_category_and_values (std::vector< std::string > & current_text, const int field_width, const std::string & category_name, const std::vector< std::pair< std::string, std::string >> & names_and_values)
Definition at line 300 of file armor_layers.cpp.
 {
     if( names_and_values.empty() ) {
         current_text.emplace_back( trim_by_length( category_name, field_width ) );
     } else {
         const std::string separator = ", ";
         const std::string spacer = " ";
         std::string assembled_value;
         for( size_t i = 0; i < names_and_values.size() ; ++i ) {
             if( i == 0 ) {
                 assembled_value += spacer;
             } else {
                 assembled_value += separator;
             }
             assembled_value += names_and_values[i].first + spacer + names_and_values[i].second;
         }
         int required_oneline_width = utf8_width( category_name + spacer + assembled_value );
         if( required_oneline_width <= field_width ) {
             current_text.emplace_back( trimmed_name_and_value( category_name, assembled_value, field_width ) );
         } else {
             current_text.emplace_back( trim_by_length( category_name, field_width ) );
             for( const std::pair<std::string, std::string> &name_and_value : names_and_values ) {
                 current_text.emplace_back( trimmed_name_and_value( spacer + name_and_value.first,
                                            name_and_value.second, field_width ) );
             }
         }
     }
 }
References trim_by_length(), trimmed_name_and_value(), and utf8_width().
Referenced by clothing_protection().
body_part_names()
std::string anonymous_namespace{armor_layers.cpp}::body_part_names (const std::vector< bodypart_id > & parts)
Definition at line 61 of file armor_layers.cpp.
 {
     if( parts.empty() ) {
         debugmsg( "Asked for names of empty list" );
         return {};
     }
     std::vector<std::string> names;
     names.reserve( parts.size() );
     for( bodypart_id part : parts ) {
         bool duplicate = false;
         bool can_be_consolidated = false;
         std::string current_part = body_part_name_accusative( part );
         std::string opposite_part = body_part_name_accusative( part->opposite_part );
         std::string part_group = body_part_name_accusative( part, 2 );
         for( const std::string &already_listed : names ) {
             if( already_listed == current_part || already_listed == part_group ) {
                 duplicate = true;
                 break;
             } else if( already_listed == opposite_part ) {
                 can_be_consolidated = true;
                 break;
             }
         }
         if( duplicate ) {
             //Do nothing
         } else if( can_be_consolidated ) {
             std::replace( names.begin(), names.end(), opposite_part, part_group );
         } else {
             names.push_back( current_part );
         }
     }
     return enumerate_as_string( names );
 }
References body_part_name_accusative(), debugmsg, enumerate_as_string(), and PATH_INFO::names().
Referenced by draw_mid_pane().
clothing_flags_description()
std::vector< std::string > anonymous_namespace{armor_layers.cpp}::clothing_flags_description (const item & worn_item, int width)
Definition at line 411 of file armor_layers.cpp.
 {
     std::vector<std::string> description_stack;
     std::vector<std::string> current_description;
     //Handle flag_FIT and flag_VARSIZE as a special case
     if( worn_item.has_flag( flag_FIT ) ) {
         current_description = foldstring( _( "It fits you well." ), width );
         description_stack.insert( description_stack.end(), current_description.begin(),
                                   current_description.end() );
     } else if( worn_item.has_flag( flag_VARSIZE ) ) {
         current_description = foldstring( _( "It could be refitted." ), width );
         description_stack.insert( description_stack.end(), current_description.begin(),
                                   current_description.end() );
     }
     //Handle all other flags:
     const std::vector<std::pair<flag_id, std::string>> flag_descriptions = {
         { flag_HOOD, translate_marker( "It has a hood." ) },
         { flag_POCKETS, translate_marker( "It has pockets." ) },
         { flag_SUN_GLASSES, translate_marker( "It keeps the sun out of your eyes." ) },
         { flag_WATERPROOF, translate_marker( "It is waterproof." ) },
         { flag_WATER_FRIENDLY, translate_marker( "It is water friendly." ) },
         { flag_FANCY, translate_marker( "It looks fancy." ) },
         { flag_SUPER_FANCY, translate_marker( "It looks really fancy." ) },
         { flag_FLOTATION, translate_marker( "You will not drown today." ) },
         { flag_OVERSIZE, translate_marker( "It is very bulky." ) },
         { flag_SWIM_GOGGLES, translate_marker( "It helps you to see clearly underwater." ) },
         { flag_SEMITANGIBLE, translate_marker( "It can occupy the same space as other things." ) }
     };
     for( const std::pair<flag_id, std::string> &flag_pair : flag_descriptions ) {
         if( worn_item.has_flag( std::get<0>( flag_pair ) ) ) {
             current_description = foldstring( _( std::get<1>( flag_pair ) ), width );
             description_stack.insert( description_stack.end(), current_description.begin(),
                                       current_description.end() );
         }
     }
     return description_stack;
 }
References _, flag_FANCY, flag_FIT, flag_FLOTATION, flag_HOOD, flag_OVERSIZE, flag_POCKETS, flag_SEMITANGIBLE, flag_SUN_GLASSES, flag_SUPER_FANCY, flag_SWIM_GOGGLES, flag_VARSIZE, flag_WATER_FRIENDLY, flag_WATERPROOF, foldstring(), item::has_flag(), and translate_marker.
Referenced by draw_mid_pane().
clothing_layer()
std::string anonymous_namespace{armor_layers.cpp}::clothing_layer (const item & worn_item)
Definition at line 221 of file armor_layers.cpp.
 {
     std::string layer;
     if( worn_item.has_flag( flag_PERSONAL ) ) {
         layer = _( "This is in your personal aura." );
     } else if( worn_item.has_flag( flag_SKINTIGHT ) ) {
         layer = _( "This is worn next to the skin." );
     } else if( worn_item.has_flag( flag_WAIST ) ) {
         layer = _( "This is worn on or around your waist." );
     } else if( worn_item.has_flag( flag_OUTER ) ) {
         layer = _( "This is worn over your other clothes." );
     } else if( worn_item.has_flag( flag_BELTED ) ) {
         layer = _( "This is strapped onto you." );
     } else if( worn_item.has_flag( flag_AURA ) ) {
         layer = _( "This is an aura around you." );
     }
     return layer;
 }
References _, flag_AURA, flag_BELTED, flag_OUTER, flag_PERSONAL, flag_SKINTIGHT, flag_WAIST, and item::has_flag().
Referenced by draw_mid_pane(), and Item_factory::finalize_post_armor().
clothing_properties()
std::vector< std::string > anonymous_namespace{armor_layers.cpp}::clothing_properties (const item & worn_item, int width, const Character & c, const bodypart_id & bp)
Definition at line 242 of file armor_layers.cpp.
 {
     std::vector<std::string> props;
     bodypart_id used_bp = bp;
     // catch all for items that aren't armor
     if( !worn_item.find_armor_data() ) {
         props.push_back( string_format( "<color_c_red>%s</color>",
                                         _( "Item provides no protection" ) ) );
         return props;
     }
     if( bp == bodypart_id( "bp_null" ) ) {
         // if the armor has no protection data
         if( worn_item.find_armor_data()->sub_data.empty() ) {
             props.push_back( string_format( "<color_c_red>%s</color>",
                                             _( "Item provides no protection" ) ) );
             return props;
         }
         // if there is only one data entry for the armor
         if( worn_item.find_armor_data()->sub_data.size() > 1 ) {
             props.push_back( string_format( "<color_c_red>%s</color>",
                                             _( "Armor is nonuniform.  Specify a limb to get armor data" ) ) );
             return props;
         } else {
             used_bp = *worn_item.get_covered_body_parts().begin();
             props.reserve( 6 );
             props.push_back( string_format( "<color_c_blue>%s</color>",
                                             _( "Each limb is uniform" ) ) );
         }
     } else {
         props.reserve( 5 );
     }
     props.push_back( string_format( "<color_c_green>[%s]</color>", _( "Properties" ) ) );
     int coverage = worn_item.get_coverage( used_bp );
     add_folded_name_and_value( props, _( "Coverage:" ), string_format( "%3d", coverage ),
                                width );
     coverage = worn_item.get_coverage( used_bp, item::cover_type::COVER_MELEE );
     add_folded_name_and_value( props, _( "Coverage (Melee):" ), string_format( "%3d",
                                coverage ), width );
     coverage = worn_item.get_coverage( used_bp, item::cover_type::COVER_RANGED );
     add_folded_name_and_value( props, _( "Coverage (Ranged):" ), string_format( "%3d",
                                coverage ), width );
     coverage = worn_item.get_coverage( used_bp, item::cover_type::COVER_VITALS );
     add_folded_name_and_value( props, _( "Coverage (Vitals):" ), string_format( "%3d",
                                coverage ), width );
     const int encumbrance = worn_item.get_encumber( c, used_bp );
     add_folded_name_and_value( props, _( "Encumbrance:" ), string_format( "%3d", encumbrance ),
                                width );
     add_folded_name_and_value( props, _( "Warmth:" ), string_format( "%3d",
                                worn_item.get_warmth() ), width );
     return props;
 }
References _, add_folded_name_and_value(), body_part_set::begin(), bp, c, item::COVER_MELEE, item::COVER_RANGED, item::COVER_VITALS, item::find_armor_data(), item::get_coverage(), item::get_covered_body_parts(), item::get_encumber(), item::get_warmth(), string_format(), and islot_armor::sub_data.
Referenced by draw_mid_pane().
clothing_protection()
std::vector< std::string > anonymous_namespace{armor_layers.cpp}::clothing_protection (const item & worn_item, int width, const bodypart_id & bp)
Definition at line 347 of file armor_layers.cpp.
 {
     std::vector<std::string> prot;
     bodypart_id used_bp = bp;
     if( !worn_item.find_armor_data() ) {
         return prot;
     }
     // if bp is null its gonna be impossible to really get good info
     if( bp == bodypart_id( "bp_null" ) ) {
         // if we have exactly one entry for armor we can use that data
         if( worn_item.find_armor_data()->sub_data.size() == 1 ) {
             used_bp = *worn_item.get_covered_body_parts().begin();
         } else {
             return prot;
         }
     }
     // prebuild and calc some values
     // the rolls are basically a perfect hit for protection and a
     // worst possible and a median hit
     resistances worst_res = resistances( worn_item, false, 99, used_bp );
     resistances best_res = resistances( worn_item, false, 0, used_bp );
     resistances median_res = resistances( worn_item, false, 50, used_bp );
     int percent_best = 100;
     int percent_worst = 0;
     const armor_portion_data *portion = worn_item.portion_for_bodypart( used_bp );
     // if there isn't a portion this is probably pet armor
     if( portion ) {
         percent_best = portion->best_protection_chance;
         percent_worst = portion->worst_protection_chance;
     }
     bool display_median = percent_best < 50 && percent_worst < 50;
     prot.push_back( string_format( "<color_c_green>[%s]</color>", _( "Protection" ) ) );
     for( const damage_type &dt : damage_type::get_all() ) {
         bool skipped_details = false;
         const std::string dtname = uppercase_first_letter( dt.name.translated() );
         damage_info_order_id dio( dt.id.c_str() );
         if( dio->info_display == damage_info_order::info_disp::DETAILED ) {
             if( percent_worst > 0 ) {
                 std::vector<std::pair<std::string, std::string>> subvalues = collect_protection_subvalues(
                             worst_res, best_res, median_res, display_median, dt.id );
                 add_category_and_values( prot, width, dtname, subvalues );
             } else {
                 skipped_details = true;
             }
         }
         if( skipped_details || dio->info_display == damage_info_order::info_disp::BASIC ) {
             add_folded_name_and_value( prot, dtname,
                                        string_format( "%.2f", best_res.type_resist( dt.id ) ), width );
         }
     }
     add_folded_name_and_value( prot, _( "Environmental:" ),
                                string_format( "%3d", worn_item.get_env_resist() ), width );
     add_folded_name_and_value( prot, _( "Breathability:" ),
                                string_format( "%3d", worn_item.breathability( used_bp ) ), width );
     return prot;
 }
References _, add_category_and_values(), add_folded_name_and_value(), damage_info_order::BASIC, body_part_set::begin(), armor_portion_data::best_protection_chance, bp, item::breathability(), collect_protection_subvalues(), damage_info_order::DETAILED, item::find_armor_data(), damage_type::get_all(), item::get_covered_body_parts(), item::get_env_resist(), damage_info_order::info_display, item::portion_for_bodypart(), string_format(), islot_armor::sub_data, resistances::type_resist(), uppercase_first_letter(), and armor_portion_data::worst_protection_chance.
Referenced by draw_mid_pane().
collect_protection_subvalues()
std::vector<std::pair<std::string, std::string> > anonymous_namespace{armor_layers.cpp}::collect_protection_subvalues (const resistances & worst_res, const resistances & best_res, const resistances & median_res, const bool display_median, const damage_type_id & type)
Definition at line 331 of file armor_layers.cpp.
 {
     std::vector<std::pair<std::string, std::string>> subvalues;
     subvalues.emplace_back( _( "Worst:" ), string_format( "%.2f",
                             worst_res.type_resist( type ) ) );
     if( display_median ) {
         subvalues.emplace_back( _( "Median:" ), string_format( "%.2f",
                                 median_res.type_resist( type ) ) );
     }
     subvalues.emplace_back( _( "Best:" ), string_format( "%.2f",
                             best_res.type_resist( type ) ) );
     return subvalues;
 }
References _, string_format(), and resistances::type_resist().
Referenced by clothing_protection().
draw_mid_pane()
mid_pane_status anonymous_namespace{armor_layers.cpp}::draw_mid_pane (const catacurses::window & w_sort_middle, std::list< item >::const_iterator const worn_item_it, Character & c, const bodypart_id & bp, mid_pane_status & status)
Definition at line 103 of file armor_layers.cpp.
 {
     const int win_width = getmaxx( w_sort_middle );
     const size_t win_height = static_cast<size_t>( getmaxy( w_sort_middle ) );
     // NOLINTNEXTLINE(cata-use-named-point-constants)
     status.header_lines = fold_and_print( w_sort_middle, point( 0, 0 ), win_width - 1, c_white,
                                           worn_item_it->type_name( 1 ) ) - 1;
     const item_penalties penalties = c.worn.get_item_penalties( worn_item_it, c, bp );
     std::vector<std::string> mid_pane_text;
     mid_pane_text.reserve(
         40 ); //Assume 10 for properties, 15 for protection, 5 for layering, 10 for encumbrance
     std::vector<std::string> temp_text;
     temp_text.reserve( 40 );
     if( !penalties.body_parts_with_stacking_penalty.empty() ) {
         std::string layer_description = [&]() -> std::string {
             std::string outstring;
             for( layer_level layer : worn_item_it->get_layer() )
             {
                 switch( layer ) {
                     case layer_level::PERSONAL:
                         outstring.append( _( "in your <color_light_blue>personal aura</color>" ) );
                         break;
                     case layer_level::SKINTIGHT:
                         outstring.append( _( "<color_light_blue>close to your skin</color>" ) );
                         break;
                     case layer_level::NORMAL:
                         outstring.append( _( "of <color_light_blue>normal</color> clothing" ) );
                         break;
                     case layer_level::WAIST:
                         outstring.append( _( "on your <color_light_blue>waist</color>" ) );
                         break;
                     case layer_level::OUTER:
                         outstring.append( _( "of <color_light_blue>outer</color> clothing" ) );
                         break;
                     case layer_level::BELTED:
                         outstring.append( _( "<color_light_blue>strapped</color> to you" ) );
                         break;
                     case layer_level::AURA:
                         outstring.append( _( "an <color_light_blue>aura</color> around you" ) );
                         break;
                     default:
                         break;
                 }
             }
             return outstring ;
         }
         ();
         std::string body_parts =
             body_part_names( penalties.body_parts_with_stacking_penalty );
         std::string message =
             string_format(
                 n_gettext( "Wearing multiple items %s on your "
                            "<color_light_red>%s</color> is adding encumbrance there.",
                            "Wearing multiple items %s on your "
                            "<color_light_red>%s</color> is adding encumbrance there.",
                            penalties.body_parts_with_stacking_penalty.size() ),
                 layer_description, body_parts
             );
         temp_text = foldstring( message, win_width );
         mid_pane_text.insert( mid_pane_text.end(), temp_text.begin(), temp_text.end() );
     }
     if( !penalties.body_parts_with_out_of_order_penalty.empty() ) {
         std::string body_parts =
             body_part_names( penalties.body_parts_with_out_of_order_penalty );
         std::string message;
         if( penalties.bad_items_within.empty() ) {
             message = string_format(
                           n_gettext( "Wearing this outside items it would normally be beneath "
                                      "is adding encumbrance to your <color_light_red>%s</color>.",
                                      "Wearing this outside items it would normally be beneath "
                                      "is adding encumbrance to your <color_light_red>%s</color>.",
                                      penalties.body_parts_with_out_of_order_penalty.size() ),
                           body_parts
                       );
         } else {
             std::string bad_item_name = *penalties.bad_items_within.begin();
             message = string_format(
                           n_gettext( "Wearing this outside your <color_light_blue>%s</color> "
                                      "is adding encumbrance to your <color_light_red>%s</color>.",
                                      "Wearing this outside your <color_light_blue>%s</color> "
                                      "is adding encumbrance to your <color_light_red>%s</color>.",
                                      penalties.body_parts_with_out_of_order_penalty.size() ),
                           bad_item_name, body_parts
                       );
         }
         temp_text = foldstring( message, win_width );
         mid_pane_text.insert( mid_pane_text.end(), temp_text.begin(), temp_text.end() );
     }
     temp_text = foldstring( clothing_layer( *worn_item_it ), win_width );
     mid_pane_text.insert( mid_pane_text.end(), temp_text.begin(), temp_text.end() );
     temp_text = clothing_flags_description( *worn_item_it, win_width );
     mid_pane_text.insert( mid_pane_text.end(), temp_text.begin(), temp_text.end() );
     temp_text = clothing_properties( *worn_item_it, win_width - 1, c, bp );
     mid_pane_text.insert( mid_pane_text.end(), temp_text.begin(), temp_text.end() );
     temp_text = clothing_protection( *worn_item_it, win_width - 1, bp );
     mid_pane_text.insert( mid_pane_text.end(), temp_text.begin(), temp_text.end() );
     status.size = mid_pane_text.size();
     nc_color color = c_light_gray;
     for( int line = status.offset; line < static_cast<int>( mid_pane_text.size() ); ++line ) {
         size_t current_line = status.header_lines + 1 + line - status.offset;
         if( current_line >= win_height ) {
             return status;
         } else {
             print_colored_text( w_sort_middle, point( 0, current_line ), color,
                                 c_light_gray,  mid_pane_text[line] );
         }
     }
     return status;
 }
References _, AURA, item_penalties::bad_items_within, BELTED, body_part_names(), item_penalties::body_parts_with_out_of_order_penalty, item_penalties::body_parts_with_stacking_penalty, bp, c, c_light_gray, c_white, clothing_flags_description(), clothing_layer(), clothing_properties(), clothing_protection(), color(), fold_and_print(), foldstring(), catacurses::getmaxx(), catacurses::getmaxy(), line(), mapgen_defer::message, n_gettext, NORMAL, OUTER, PERSONAL, print_colored_text(), SKINTIGHT, status, string_format(), WAIST, and win_width.
Referenced by outfit::sort_armor().