Cataclysm DDA: MAP_SHARING Namespace Reference
MAP_SHARING Namespace Reference
Functions
void setSharing (bool mode)
void setUsername (const std::string &name)
bool isSharing ()
std::string getUsername ()
void setCompetitive (bool mode)
bool isCompetitive ()
void setWorldmenu (bool mode)
bool isWorldmenu ()
bool isAdmin ()
void setAdmins (const std::set< std::string > &names)
void addAdmin (const std::string &name)
bool isDebugger ()
void setDebuggers (const std::set< std::string > &names)
void addDebugger (const std::string &name)
void setDefaults ()
Variables
bool sharing
std::string username
bool competitive
bool worldmenu
std::set< std::string > admins
std::set< std::string > debuggers
Function Documentation
addAdmin()
void MAP_SHARING::addAdmin (const std::string & name)
Definition at line 76 of file mapsharing.cpp.
 {
     MAP_SHARING::admins.insert( name );
     MAP_SHARING::debuggers.insert( name );
 }
References admins, debuggers, and om_direction::name().
Referenced by anonymous_namespace{main.cpp}::parse_commandline(), and setDefaults().
addDebugger()
void MAP_SHARING::addDebugger (const std::string & name)
Definition at line 92 of file mapsharing.cpp.
 {
     MAP_SHARING::debuggers.insert( name );
 }
References debuggers, and om_direction::name().
Referenced by anonymous_namespace{main.cpp}::parse_commandline().
getUsername()
std::string MAP_SHARING::getUsername ()
Definition at line 43 of file mapsharing.cpp.
 {
     return MAP_SHARING::username;
 }
References username.
Referenced by isAdmin(), isDebugger(), avatar::randomize(), and set_description().
isAdmin()
bool MAP_SHARING::isAdmin ()
Definition at line 66 of file mapsharing.cpp.
 {
     return admins.find( getUsername() ) != admins.end();
 }
References admins, and getUsername().
Referenced by options_manager::options_manager().
isCompetitive()
bool MAP_SHARING::isCompetitive ()
Definition at line 52 of file mapsharing.cpp.
 {
     return MAP_SHARING::competitive;
 }
References competitive.
Referenced by game::do_regular_action(), game::look_around(), and options_manager::options_manager().
isDebugger()
bool MAP_SHARING::isDebugger ()
Definition at line 82 of file mapsharing.cpp.
 {
     return debuggers.find( getUsername() ) != debuggers.end();
 }
References debuggers, and getUsername().
Referenced by game::do_regular_action(), and game::look_around().
isSharing()
bool MAP_SHARING::isSharing ()
Definition at line 39 of file mapsharing.cpp.
 {
     return MAP_SHARING::sharing;
 }
References sharing.
Referenced by assemble_description_help(), main_menu::init_strings(), main_menu::load_character_tab(), main_menu::opening_screen(), avatar::randomize(), and set_description().
isWorldmenu()
bool MAP_SHARING::isWorldmenu ()
Definition at line 61 of file mapsharing.cpp.
 {
     return MAP_SHARING::worldmenu;
 }
References worldmenu.
setAdmins()
void MAP_SHARING::setAdmins (const std::set< std::string > & names)
Definition at line 71 of file mapsharing.cpp.
 {
     MAP_SHARING::admins = names;
 }
References admins, and PATH_INFO::names().
setCompetitive()
void MAP_SHARING::setCompetitive (bool mode)
Definition at line 48 of file mapsharing.cpp.
 {
     MAP_SHARING::competitive = mode;
 }
References competitive.
Referenced by anonymous_namespace{main.cpp}::parse_commandline(), and setDefaults().
setDebuggers()
void MAP_SHARING::setDebuggers (const std::set< std::string > & names)
Definition at line 87 of file mapsharing.cpp.
 {
     MAP_SHARING::debuggers = names;
 }
References debuggers, and PATH_INFO::names().
setDefaults()
void MAP_SHARING::setDefaults ()
Definition at line 97 of file mapsharing.cpp.
 {
     MAP_SHARING::setSharing( false );
     MAP_SHARING::setCompetitive( false );
     MAP_SHARING::setWorldmenu( true );
     if( const char *user = getenv( "USER" ) ) {
         MAP_SHARING::setUsername( user );
     } else {
         MAP_SHARING::setUsername( "" );
     }
     MAP_SHARING::addAdmin( "admin" );
 }
References addAdmin(), setCompetitive(), setSharing(), setUsername(), and setWorldmenu().
Referenced by main().
setSharing()
void MAP_SHARING::setSharing (bool mode)
Definition at line 30 of file mapsharing.cpp.
 {
     MAP_SHARING::sharing = mode;
 }
References sharing.
Referenced by anonymous_namespace{main.cpp}::parse_commandline(), and setDefaults().
setUsername()
void MAP_SHARING::setUsername (const std::string & name)
Definition at line 34 of file mapsharing.cpp.
 {
     MAP_SHARING::username = name;
 }
References om_direction::name(), and username.
Referenced by anonymous_namespace{main.cpp}::parse_commandline(), and setDefaults().
setWorldmenu()
void MAP_SHARING::setWorldmenu (bool mode)
Definition at line 57 of file mapsharing.cpp.
 {
     MAP_SHARING::worldmenu = mode;
 }
References worldmenu.
Referenced by anonymous_namespace{main.cpp}::parse_commandline(), and setDefaults().
Variable Documentation
admins
std::set< std::string > MAP_SHARING::admins extern
Definition at line 27 of file mapsharing.cpp.
Referenced by addAdmin(), isAdmin(), and setAdmins().
competitive
bool MAP_SHARING::competitive extern
Definition at line 24 of file mapsharing.cpp.
Referenced by isCompetitive(), and setCompetitive().
debuggers
std::set< std::string > MAP_SHARING::debuggers extern
Definition at line 28 of file mapsharing.cpp.
Referenced by addAdmin(), addDebugger(), isDebugger(), and setDebuggers().
sharing
bool MAP_SHARING::sharing extern
Definition at line 23 of file mapsharing.cpp.
Referenced by isSharing(), and setSharing().
username
std::string MAP_SHARING::username extern
Definition at line 26 of file mapsharing.cpp.
Referenced by getUsername(), and setUsername().
worldmenu
bool MAP_SHARING::worldmenu extern
Definition at line 25 of file mapsharing.cpp.
Referenced by isWorldmenu(), and setWorldmenu().