Cataclysm DDA: overmap_land_use_codes Namespace Reference
overmap_land_use_codes Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void finalize ()
void check_consistency ()
void reset ()
const std::vector< overmap_land_use_code > & get_all ()
Function Documentation
check_consistency()
void overmap_land_use_codes::check_consistency ()
Definition at line 477 of file overmap.cpp.
 {
     land_use_codes.check();
 }
References anonymous_namespace{overmap.cpp}::land_use_codes.
Referenced by DynamicDataLoader::check_consistency().
finalize()
void overmap_land_use_codes::finalize ()
Definition at line 470 of file overmap.cpp.
 {
     for( const overmap_land_use_code &elem : land_use_codes.get_all() ) {
         const_cast<overmap_land_use_code &>( elem ).finalize(); // This cast is ugly, but safe.
     }
 }
References behavior::finalize(), and anonymous_namespace{overmap.cpp}::land_use_codes.
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< overmap_land_use_code > & overmap_land_use_codes::get_all ()
Definition at line 487 of file overmap.cpp.
 {
     return land_use_codes.get_all();
 }
References anonymous_namespace{overmap.cpp}::land_use_codes.
load()
void overmap_land_use_codes::load (const JsonObject & jo, const std::string & src)
Definition at line 465 of file overmap.cpp.
 {
     land_use_codes.load( jo, src );
 }
References anonymous_namespace{overmap.cpp}::land_use_codes.
Referenced by DynamicDataLoader::initialize().
reset()
void overmap_land_use_codes::reset ()
Definition at line 482 of file overmap.cpp.
 {
     land_use_codes.reset();
 }
References anonymous_namespace{overmap.cpp}::land_use_codes.
Referenced by DynamicDataLoader::unload_data().