Cataclysm DDA: anonymous_namespace{trap.cpp} Namespace Reference
anonymous_namespace{trap.cpp} Namespace Reference
Variables
generic_factory< trap > trap_factory ("trap")
Variable Documentation
trap_factory
generic_factory<trap> anonymous_namespace{trap.cpp}::trap_factory("trap") ("trap")
Referenced by trap::check_consistency(), trap::count(), trap::finalize(), int_id< T >::id(), string_id< T >::id(), string_id< T >::is_valid(), int_id< T >::is_valid(), trap::load_trap(), string_id< T >::obj(), and trap::reset().