Cataclysm DDA: overmap_specials Namespace Reference
overmap_specials Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void finalize ()
void finalize_mapgen_parameters ()
void check_consistency ()
void reset ()
const std::vector< overmap_special > & get_all ()
overmap_special_batch get_default_batch (const point_abs_om &origin)
overmap_special_id create_building_from (const string_id< oter_type_t > &base)
Generates a simple special from a building id.
Function Documentation
check_consistency()
void overmap_specials::check_consistency ()
Definition at line 518 of file overmap.cpp.
 {
     const size_t max_count = ( OMAPX / OMSPEC_FREQ ) * ( OMAPY / OMSPEC_FREQ );
     const size_t actual_count = std::accumulate( specials.get_all().begin(), specials.get_all().end(),
                                 static_cast< size_t >( 0 ),
     []( size_t sum, const overmap_special & elem ) {
         size_t min_occur = static_cast<size_t>( std::max( elem.get_constraints().occurrences.min, 0 ) );
         const bool unique = elem.has_flag( "UNIQUE" ) || elem.has_flag( "GLOBALLY_UNIQUE" );
         return sum + ( unique ? 0 : min_occur );
     } );
     if( actual_count > max_count ) {
         debugmsg( "There are too many mandatory overmap specials (%d > %d). Some of them may not be placed.",
                   actual_count, max_count );
     }
     overmap_special_migration::check();
     specials.check();
     for( const overmap_special &os : specials.get_all() ) {
         overmap_special_id new_id = overmap_special_migration::migrate( os.id );
         if( new_id.is_null() ) {
             debugmsg( "Overmap special id %s has been removed or migrated to a different type.",
                       os.id.str() );
         } else if( new_id != os.id ) {
             debugmsg( "Overmap special id %s has been migrated.  Use %s instead.", os.id.str(),
                       new_id.str() );
         }
     }
 }
References overmap_special_migration::check(), debugmsg, string_id< T >::id(), string_id< T >::is_null(), overmap_special_migration::migrate(), OMAPX, OMAPY, OMSPEC_FREQ, anonymous_namespace{overmap.cpp}::specials, and string_id< T >::str().
Referenced by DynamicDataLoader::check_consistency().
create_building_from()
overmap_special_id overmap_specials::create_building_from (const string_id< oter_type_t > & base)
Generates a simple special from a building id.
Definition at line 7352 of file overmap.cpp.
 {
     // TODO: Get rid of the hard-coded ids.
     overmap_special_terrain ter;
     ter.terrain = base.obj().get_first().id();
     ter.locations.insert( overmap_location_land );
     ter.locations.insert( overmap_location_swamp );
     overmap_special_id new_id( "FakeSpecial_" + base.str() );
     overmap_special new_special( new_id, ter );
     mod_tracker::assign_src( new_special, base->src.back().second.str() );
     return specials.insert( new_special ).id;
 }
References mod_tracker::assign_src(), oter_type_t::get_first(), int_id< T >::id(), cata::flat_set< T, Compare, Data >::insert(), overmap_special_locations::locations, string_id< T >::obj(), overmap_location_land, overmap_location_swamp, anonymous_namespace{overmap.cpp}::specials, oter_type_t::src, string_id< T >::str(), and overmap_special_terrain::terrain.
Referenced by building_bin::finalize().
finalize()
void overmap_specials::finalize ()
Definition at line 503 of file overmap.cpp.
 {
     for( const overmap_special &elem : specials.get_all() ) {
         const_cast<overmap_special &>( elem ).finalize(); // This cast is ugly, but safe.
     }
 }
References behavior::finalize(), and anonymous_namespace{overmap.cpp}::specials.
Referenced by DynamicDataLoader::finalize_loaded_data().
finalize_mapgen_parameters()
void overmap_specials::finalize_mapgen_parameters ()
Definition at line 510 of file overmap.cpp.
 {
     for( const overmap_special &elem : specials.get_all() ) {
         // This cast is ugly, but safe.
         const_cast<overmap_special &>( elem ).finalize_mapgen_parameters();
     }
 }
References anonymous_namespace{overmap.cpp}::specials.
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< overmap_special > & overmap_specials::get_all ()
Definition at line 554 of file overmap.cpp.
 {
     return specials.get_all();
 }
References anonymous_namespace{overmap.cpp}::specials.
Referenced by overmapbuffer::place_special(), and overmap_ui::place_ter_or_special().
get_default_batch()
overmap_special_batch overmap_specials::get_default_batch (const point_abs_om & origin)
Definition at line 559 of file overmap.cpp.
 {
     std::vector<const overmap_special *> res;
     res.reserve( specials.size() );
     for( const overmap_special &elem : specials.get_all() ) {
         if( elem.can_spawn() ) {
             res.push_back( &elem );
         }
     }
     return overmap_special_batch( origin, res );
 }
References anonymous_namespace{overmap.cpp}::specials.
Referenced by overmap::populate().
load()
void overmap_specials::load (const JsonObject & jo, const std::string & src)
Definition at line 492 of file overmap.cpp.
 {
     specials.load( jo, src );
 }
References anonymous_namespace{overmap.cpp}::specials.
Referenced by DynamicDataLoader::initialize(), and city_buildings::load().
reset()
void overmap_specials::reset ()
Definition at line 549 of file overmap.cpp.
 {
     specials.reset();
 }
References anonymous_namespace{overmap.cpp}::specials.
Referenced by DynamicDataLoader::unload_data().