Cataclysm DDA: anonymous_namespace{shop_cons_rate.cpp} Namespace Reference
anonymous_namespace{shop_cons_rate.cpp} Namespace Reference
Variables
generic_factory< shopkeeper_cons_rates > shop_cons_rate_factory (SHOPKEEPER_CONSUMPTION_RATES)
generic_factory< shopkeeper_blacklist > shop_blacklist_factory (SHOPKEEPER_BLACKLIST)
Variable Documentation
shop_blacklist_factory
generic_factory<shopkeeper_blacklist> anonymous_namespace{shop_cons_rate.cpp}::shop_blacklist_factory(SHOPKEEPER_BLACKLIST) (SHOPKEEPER_BLACKLIST)
Referenced by shopkeeper_blacklist::get_all(), shopkeeper_blacklist::load_blacklist(), and shopkeeper_blacklist::reset().
shop_cons_rate_factory
generic_factory<shopkeeper_cons_rates> anonymous_namespace{shop_cons_rate.cpp}::shop_cons_rate_factory(SHOPKEEPER_CONSUMPTION_RATES) (SHOPKEEPER_CONSUMPTION_RATES)
Referenced by shopkeeper_cons_rates::check_all(), shopkeeper_cons_rates::get_all(), shopkeeper_cons_rates::load_rate(), and shopkeeper_cons_rates::reset().