Cataclysm DDA: sfx Namespace Reference
sfx Namespace Reference
Enumerations
enum class channel : int {
any = -1 , daytime_outdoors_env = 0 , nighttime_outdoors_env , underground_env ,
indoors_env , indoors_rain_env , outdoors_snow_env , outdoors_flurry_env ,
outdoors_thunderstorm_env , outdoors_rainstorm_env , outdoors_rain_env , outdoors_drizzle_env ,
outdoor_blizzard , deafness_tone , danger_extreme_theme , danger_high_theme ,
danger_medium_theme , danger_low_theme , stamina_75 , stamina_50 ,
stamina_35 , idle_chainsaw , chainsaw_theme , player_activities ,
exterior_engine_sound , interior_engine_sound , radio , outdoors_portal_storm_env ,
outdoors_clear_env , outdoors_cloudy_env , outdoors_sunny_env , MAX_CHANNEL
}
enum class group : int { weather = 1 , time_of_day , context_themes , sleepiness }
Functions
void load_sound_effects (const JsonObject &jsobj)
Dummy implementations for builds without sound.
void load_sound_effect_preload (const JsonObject &jsobj)
void load_playlist (const JsonObject &jsobj)
void play_variant_sound (const std::string &id, const std::string &variant, int volume, units::angle angle, double pitch_min=-1.0, double pitch_max=-1.0)
void play_variant_sound (const std::string &id, const std::string &variant, const std::string &season, const std::optional< bool > &is_indoors, const std::optional< bool > &is_night, int volume, units::angle angle, double pitch_min=-1.0, double pitch_max=-1.0)
void play_variant_sound (const std::string &id, const std::string &variant, int volume)
void play_variant_sound (const std::string &id, const std::string &variant, const std::string &season, const std::optional< bool > &is_indoors, const std::optional< bool > &is_night, int volume)
void play_ambient_variant_sound (const std::string &id, const std::string &variant, int volume, channel channel, int fade_in_duration, double pitch=-1.0, int loops=-1)
void play_ambient_variant_sound (const std::string &id, const std::string &variant, const std::string &season, const std::optional< bool > &is_indoors, const std::optional< bool > &is_night, int volume, channel channel, int fade_in_duration, double pitch=-1.0, int loops=-1)
void play_activity_sound (const std::string &id, const std::string &variant, int volume)
void play_activity_sound (const std::string &id, const std::string &variant, const std::string &season, int volume)
void end_activity_sounds ()
void generate_gun_sound (const Character &source_arg, const item &firing)
void generate_melee_sound (const tripoint &source, const tripoint &target, bool hit, bool targ_mon=false, const std::string &material="flesh")
void do_hearing_loss (int turns=-1)
void remove_hearing_loss ()
void do_projectile_hit (const Creature &target)
int get_heard_volume (const tripoint &source)
Functions from sfx that do not use the SDL_mixer API at all.
units::angle get_heard_angle (const tripoint &source)
void do_footstep ()
void do_danger_music ()
void do_ambient ()
void do_vehicle_engine_sfx ()
void do_vehicle_exterior_engine_sfx ()
void fade_audio_group (group group, int duration)
void fade_audio_channel (channel channel, int duration)
bool is_channel_playing (channel channel)
bool has_variant_sound (const std::string &id, const std::string &variant)
bool has_variant_sound (const std::string &id, const std::string &variant, const std::string &season, const std::optional< bool > &is_indoors, const std::optional< bool > &is_night)
void stop_sound_effect_fade (channel channel, int duration)
void stop_sound_effect_timed (channel channel, int time)
int set_channel_volume (channel channel, int volume)
void do_player_death_hurt (const Character &target, bool death)
void do_sleepiness ()
void do_obstacle (const std::string &obst="")
Enumeration Type Documentation
channel
enum sfx::channel : int strong
Enumerator
any
daytime_outdoors_env
nighttime_outdoors_env
underground_env
indoors_env
indoors_rain_env
outdoors_snow_env
outdoors_flurry_env
outdoors_thunderstorm_env
outdoors_rainstorm_env
outdoors_rain_env
outdoors_drizzle_env
outdoor_blizzard
deafness_tone
danger_extreme_theme
danger_high_theme
danger_medium_theme
danger_low_theme
stamina_75
stamina_50
stamina_35
idle_chainsaw
chainsaw_theme
player_activities
exterior_engine_sound
interior_engine_sound
radio
outdoors_portal_storm_env
outdoors_clear_env
outdoors_cloudy_env
outdoors_sunny_env
MAX_CHANNEL
Definition at line 104 of file sounds.h.
                    : int {
     any = -1,                   //Finds the first available channel
     daytime_outdoors_env = 0,
     nighttime_outdoors_env,
     underground_env,
     indoors_env,
     indoors_rain_env,
     outdoors_snow_env,
     outdoors_flurry_env,
     outdoors_thunderstorm_env,
     outdoors_rainstorm_env,
     outdoors_rain_env,
     outdoors_drizzle_env,
     outdoor_blizzard,
     deafness_tone,
     danger_extreme_theme,
     danger_high_theme,
     danger_medium_theme,
     danger_low_theme,
     stamina_75,
     stamina_50,
     stamina_35,
     idle_chainsaw,
     chainsaw_theme,
     player_activities,
     exterior_engine_sound,
     interior_engine_sound,
     radio,
     outdoors_portal_storm_env,
     outdoors_clear_env,
     outdoors_cloudy_env,
     outdoors_sunny_env,
     MAX_CHANNEL                 //the last reserved channel
 };
group
enum sfx::group : int strong
Enumerator
weather
time_of_day
context_themes
sleepiness
Definition at line 140 of file sounds.h.
                  : int {
     weather = 1,    //SFX related to weather
     time_of_day,    //SFX related to time of day
     context_themes, //SFX related to context themes
     sleepiness         //SFX related to sleepiness
 };
Function Documentation
do_ambient()
void sfx::do_ambient ()
Definition at line 2016 of file sounds.cpp.
 { }
Referenced by game::on_move_effects(), and weather_manager::update_weather().
do_danger_music()
void sfx::do_danger_music ()
Definition at line 2013 of file sounds.cpp.
 { }
do_footstep()
void sfx::do_footstep ()
Definition at line 2012 of file sounds.cpp.
 { }
Referenced by Character::make_footstep_noise().
do_hearing_loss()
void sfx::do_hearing_loss (int turns = -1)
Definition at line 2009 of file sounds.cpp.
 { }
do_obstacle()
void sfx::do_obstacle (const std::string & obst = "")
Definition at line 2035 of file sounds.cpp.
 { }
Referenced by game::walk_move().
do_player_death_hurt()
void sfx::do_player_death_hurt (const Character & target, bool death)
Definition at line 2033 of file sounds.cpp.
 { }
Referenced by game::bury_screen(), suffer::from_bad_bionics(), monster::melee_attack(), and melee_actor::on_damage().
do_projectile_hit()
void sfx::do_projectile_hit (const Creature & target)
Definition at line 2011 of file sounds.cpp.
 { }
Referenced by projectile_attack().
do_sleepiness()
void sfx::do_sleepiness ()
Definition at line 2034 of file sounds.cpp.
 { }
do_vehicle_engine_sfx()
void sfx::do_vehicle_engine_sfx ()
Definition at line 2014 of file sounds.cpp.
 { }
Referenced by vehicle::install_part(), vehicle::smart_controller_handle_turn(), activity_handlers::start_engines_finish(), and vehicle::stop_engines().
do_vehicle_exterior_engine_sfx()
void sfx::do_vehicle_exterior_engine_sfx ()
Definition at line 2015 of file sounds.cpp.
 { }
end_activity_sounds()
void sfx::end_activity_sounds ()
Definition at line 2005 of file sounds.cpp.
 { }
Referenced by activity_type::call_finish(), Character::cancel_activity(), and player_activity::set_to_null().
fade_audio_channel()
void sfx::fade_audio_channel (channel channel, int duration)
Definition at line 2018 of file sounds.cpp.
 { }
Referenced by computer_session::action_radio_archive().
fade_audio_group()
void sfx::fade_audio_group (group group, int duration)
Definition at line 2017 of file sounds.cpp.
 { }
Referenced by game::bury_screen().
generate_gun_sound()
void sfx::generate_gun_sound (const Character & source_arg, const item & firing)
Definition at line 2006 of file sounds.cpp.
 { }
Referenced by Character::fire_gun().
generate_melee_sound()
void sfx::generate_melee_sound (const tripoint & source, const tripoint & target, bool hit, bool targ_mon = false, const std::string & material = "flesh")
Definition at line 2007 of file sounds.cpp.
                                                     { }
Referenced by Character::melee_attack_abstract().
get_heard_angle()
units::angle sfx::get_heard_angle (const tripoint & source)
Definition at line 2058 of file sounds.cpp.
 {
     units::angle angle = coord_to_angle( get_player_character().pos(), source ) + 90_degrees;
     //add_msg(m_warning, "angle: %i", angle);
     return angle;
 }
References coord_to_angle(), get_player_character(), and math_opers::pos().
Referenced by melee_actor::call(), cycle_action(), npc::do_reload(), melee_actor::on_damage(), and projectile_attack().
get_heard_volume()
int sfx::get_heard_volume (const tripoint & source)
Functions from sfx that do not use the SDL_mixer API at all.
They can be used in builds without sound support.
Definition at line 2045 of file sounds.cpp.
 {
     int distance = sound_distance( get_player_character().pos(), source );
     // fract = -100 / 24
     const float fract = -4.166666f;
     int heard_volume = fract * distance - 1 + 100;
     if( heard_volume <= 0 ) {
         heard_volume = 0;
     }
     heard_volume *= g_sfx_volume_multiplier;
     return heard_volume;
 }
References g_sfx_volume_multiplier, get_player_character(), math_opers::pos(), and sound_distance().
Referenced by melee_actor::call(), iexamine::chainfence(), chop_single_do_turn(), cycle_action(), npc::do_reload(), hacksaw_activity_actor::do_turn(), oxytorch_activity_actor::do_turn(), prying_activity_actor::do_turn(), construct::do_turn_shovel(), chop_tree_activity_actor::finish(), activity_handlers::jackhammer_do_turn(), reload_activity_actor::make_reload_sound(), monster::melee_attack(), mdeath::normal(), melee_actor::on_damage(), activity_handlers::pickaxe_do_turn(), sounds::process_sound_markers(), projectile_attack(), mattack::shockstorm(), mdeath::splatter(), and workout_activity_actor::start().
has_variant_sound() [1/2]
bool sfx::has_variant_sound (const std::string & id, const std::string & variant)
Definition at line 2027 of file sounds.cpp.
 {
     return false;
 }
Referenced by vehicle::start_engine(), and vehicle::stop_engines().
has_variant_sound() [2/2]
bool sfx::has_variant_sound (const std::string & id, const std::string & variant, const std::string & season, const std::optional< bool > & is_indoors, const std::optional< bool > & is_night)
is_channel_playing()
bool sfx::is_channel_playing (channel channel)
Definition at line 2019 of file sounds.cpp.
 {
     return false;
 }
Referenced by iuse::radio_tick().
load_playlist()
void sfx::load_playlist (const JsonObject & jsobj)
Definition at line 1998 of file sounds.cpp.
 { }
Referenced by DynamicDataLoader::initialize().
load_sound_effect_preload()
void sfx::load_sound_effect_preload (const JsonObject & jsobj)
Definition at line 1997 of file sounds.cpp.
 { }
Referenced by DynamicDataLoader::initialize().
load_sound_effects()
void sfx::load_sound_effects (const JsonObject & jsobj)
Dummy implementations for builds without sound.
Definition at line 1996 of file sounds.cpp.
 { }
Referenced by DynamicDataLoader::initialize().
play_activity_sound() [1/2]
void sfx::play_activity_sound (const std::string & id, const std::string & variant, const std::string & season, int volume)
play_activity_sound() [2/2]
void sfx::play_activity_sound (const std::string & id, const std::string & variant, int volume)
Definition at line 2004 of file sounds.cpp.
 { }
Referenced by chop_single_do_turn(), hacksaw_activity_actor::do_turn(), oxytorch_activity_actor::do_turn(), prying_activity_actor::do_turn(), construct::do_turn_shovel(), activity_handlers::jackhammer_do_turn(), activity_handlers::pickaxe_do_turn(), and workout_activity_actor::start().
play_ambient_variant_sound() [1/2]
void sfx::play_ambient_variant_sound (const std::string & id, const std::string & variant, const std::string & season, const std::optional< bool > & is_indoors, const std::optional< bool > & is_night, int volume, channel channel, int fade_in_duration, double pitch = -1.0, int loops = -1)
play_ambient_variant_sound() [2/2]
void sfx::play_ambient_variant_sound (const std::string & id, const std::string & variant, int volume, channel channel, int fade_in_duration, double pitch = -1.0, int loops = -1)
Definition at line 2002 of file sounds.cpp.
                                                     { }
Referenced by computer_session::action_radio_archive(), and iuse::radio_tick().
play_variant_sound() [1/4]
void sfx::play_variant_sound (const std::string & id, const std::string & variant, const std::string & season, const std::optional< bool > & is_indoors, const std::optional< bool > & is_night, int volume)
Definition at line 2036 of file sounds.cpp.
                                                                                           { }
play_variant_sound() [2/4]
void sfx::play_variant_sound (const std::string & id, const std::string & variant, const std::string & season, const std::optional< bool > & is_indoors, const std::optional< bool > & is_night, int volume, units::angle angle, double pitch_min = -1.0, double pitch_max = -1.0)
play_variant_sound() [3/4]
void sfx::play_variant_sound (const std::string & id, const std::string & variant, int volume)
Definition at line 2001 of file sounds.cpp.
 { }
play_variant_sound() [4/4]
void sfx::play_variant_sound (const std::string & id, const std::string & variant, int volume, units::angle angle, double pitch_min = -1.0, double pitch_max = -1.0)
Definition at line 1999 of file sounds.cpp.
                                        { }
Referenced by melee_actor::call(), iexamine::chainfence(), cycle_action(), npc::do_reload(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), chop_tree_activity_actor::finish(), suffer::from_bad_bionics(), reload_activity_actor::make_reload_sound(), monster::melee_attack(), mdeath::normal(), melee_actor::on_damage(), main_menu::on_error(), main_menu::on_move(), vehicle::open_or_close(), worldfactory::pick_world(), sounds::process_sound_markers(), projectile_attack(), overmap_ui::search(), mattack::shockstorm(), options_manager::show(), mdeath::splatter(), vehicle::start_engine(), vehicle::stop_engines(), and weather_sound().
remove_hearing_loss()
void sfx::remove_hearing_loss ()
Definition at line 2010 of file sounds.cpp.
 { }
set_channel_volume()
int sfx::set_channel_volume (channel channel, int volume)
Definition at line 2023 of file sounds.cpp.
 {
     return 0;
 }
stop_sound_effect_fade()
void sfx::stop_sound_effect_fade (channel channel, int duration)
Definition at line 2031 of file sounds.cpp.
 { }
stop_sound_effect_timed()
void sfx::stop_sound_effect_timed (channel channel, int time)
Definition at line 2032 of file sounds.cpp.
 { }