Cataclysm DDA: anonymous_namespace{flexbuffer_cache.cpp} Namespace Reference
anonymous_namespace{flexbuffer_cache.cpp} Namespace Reference
Functions
void try_find_and_throw_json_error (TextJsonValue &jv)
fs::file_time_type get_file_mtime_millis (const fs::path &path, std::error_code &ec)
std::vector< uint8_t > parse_json_to_flexbuffer_ (const char *buffer, const char *source_filename_opt) noexcept(false)
Function Documentation
get_file_mtime_millis()
fs::file_time_type anonymous_namespace{flexbuffer_cache.cpp}::get_file_mtime_millis (const fs::path & path, std::error_code & ec)
Definition at line 45 of file flexbuffer_cache.cpp.
 {
     fs::file_time_type ret = fs::last_write_time( path, ec );
     if( ec ) {
         return ret;
     }
     // Truncate to nearest millisecond.
     ret = fs::file_time_type( std::chrono::milliseconds(
                                   std::chrono::duration_cast<std::chrono::milliseconds>( ret.time_since_epoch() ).count() ) );
     return ret;
 }
References cata::hash64_detail::ret.
Referenced by file_flexbuffer::is_stale(), flexbuffer_disk_cache::load_flexbuffer_if_not_stale(), flexbuffer_cache::parse(), flexbuffer_cache::parse_and_cache(), and flexbuffer_disk_cache::save_to_disk().
parse_json_to_flexbuffer_()
std::vector<uint8_t> anonymous_namespace{flexbuffer_cache.cpp}::parse_json_to_flexbuffer_ (const char * buffer, const char * source_filename_opt) noexcept
Definition at line 57 of file flexbuffer_cache.cpp.
 {
     flatbuffers::IDLOptions opts;
     opts.strict_json = true;
     opts.use_flexbuffers = true;
     opts.no_warnings = true;
     flatbuffers::Parser parser{ opts };
     flexbuffers::Builder fbb;
     if( !parser.ParseFlexBuffer( buffer, source_filename_opt, &fbb ) ) {
         std::istringstream is{ buffer };
         TextJsonIn jsin{ is, source_filename_opt ? source_filename_opt : "<unknown source file>" };
         if( fbb.HasDuplicateKeys() ) {
             // The error from the parser isn't very informative. TextJsonObject can detect the
             // condition but we have to deep scan to find it.
             TextJsonValue jv = jsin.get_value();
             try_find_and_throw_json_error( jv );
             // If we didn't find and throw it, reset the stream.
             is.seekg( 0, std::ios_base::beg );
         }
         size_t line = 0;
         size_t col = 0;
         size_t error_offset = 0;
         if( ( error_offset = parser.error_.find( "EOF:" ) ) == std::string::npos ) {
             // Try to extract line and col to position TextJsonIn at an appropriate location.
             // %n modifier returns number of characters consumed by sscanf to skip the text
             // in the error that the flexbuffer parser returns, because TextJsonIn will add it.
             // Format is "(filename:)?(EOF:|line:col:) message"
             // But filename might be C:something
             int scanned_chars = 0;
             // NOLINTNEXTLINE(cert-err34-c)
             if( sscanf( parser.error_.c_str(), "%*[^:]:%*[^:]:%zu:%zu: %n", &line, &col,
                         &scanned_chars ) != 2 &&
                 // NOLINTNEXTLINE(cert-err34-c)
                 sscanf( parser.error_.c_str(), "%*[^:]:%zu:%zu: %n", &line, &col, &scanned_chars ) != 2 &&
                 // NOLINTNEXTLINE(cert-err34-c)
                 sscanf( parser.error_.c_str(), "%zu:%zu: %n", &line, &col, &scanned_chars ) != 2 ) {
                 line = 0;
                 col = 0;
             }
             error_offset = scanned_chars;
         } else {
             error_offset += 5; // skip "EOF: " because find returns the offset of the start.
         }
         constexpr const char *kErrorPrefix = "error: ";
         if( strncmp( parser.error_.c_str() + error_offset, kErrorPrefix, strlen( kErrorPrefix ) ) == 0 ) {
             error_offset += strlen( kErrorPrefix );
         }
         if( line != 0 ) {
             // Lines are 1 indexed.
             while( line > 1 ) {
                 is.ignore( std::numeric_limits<std::streamsize>::max(), '\n' );
                 --line;
             }
         } else {
             // Seek to end.
             is.seekg( 0, std::ios_base::end );
             // Force EOF state
             is.peek();
         }
         jsin.error( col ? col - 1 : 0, parser.error_.substr( error_offset ) );
     }
     return std::move( fbb ).GetBuffer();
 }
References keycode::end, line(), max(), and try_find_and_throw_json_error().
Referenced by flexbuffer_cache::parse(), flexbuffer_cache::parse_and_cache(), and flexbuffer_cache::parse_buffer().
try_find_and_throw_json_error()
void anonymous_namespace{flexbuffer_cache.cpp}::try_find_and_throw_json_error (TextJsonValue & jv)
Definition at line 30 of file flexbuffer_cache.cpp.
 {
     if( jv.test_object() ) {
         TextJsonObject jo = jv.get_object();
         for( TextJsonMember jm : jo ) {
             try_find_and_throw_json_error( jm );
         }
     } else if( jv.test_array() ) {
         TextJsonArray ja = jv.get_array();
         for( TextJsonValue jav : ja ) {
             try_find_and_throw_json_error( jav );
         }
     }
 }
References TextJsonValue::get_array(), TextJsonValue::get_object(), TextJsonValue::test_array(), and TextJsonValue::test_object().
Referenced by parse_json_to_flexbuffer_().