Cataclysm DDA: anonymous_namespace{animation.cpp} Namespace Reference
anonymous_namespace{animation.cpp} Namespace Reference
Classes
class basic_animation
class explosion_animation
class bullet_animation
Functions
bool is_point_visible (const tripoint &p, int margin=0)
bool is_radius_visible (const tripoint &center, int radius)
bool is_layer_visible (const std::map< tripoint, explosion_tile > &layer)
tripoint relative_view_pos (const avatar &u, const tripoint &p) noexcept
Get p relative to u's current position and view.
tripoint relative_view_pos (const game &g, const tripoint &p) noexcept
void draw_explosion_curses (game &g, const tripoint &center, const int r, const nc_color &col)
constexpr explosion_neighbors operator| (explosion_neighbors lhs, explosion_neighbors rhs)
constexpr explosion_neighbors operator^ (explosion_neighbors lhs, explosion_neighbors rhs)
void draw_custom_explosion_curses (game &g, const std::list< std::map< tripoint, explosion_tile > > &layers)
void draw_bullet_curses (map &m, const tripoint &t, const char bullet, const tripoint *const p)
void hit_animation (const avatar &u, const tripoint &center, nc_color cColor, const std::string &cTile)
void draw_hit_mon_curses (const tripoint &center, const monster &m, const avatar &u, const bool dead)
void draw_hit_player_curses (const game &, const Character &p, const int dam)
void draw_line_curses (game &g, const tripoint &center, const std::vector< tripoint > &ret, bool noreveal)
void draw_line_curses (game &g, const std::vector< tripoint > &points)
void draw_weather_curses (const catacurses::window &win, const weather_printable &w)
void draw_sct_curses (const game &g)
void draw_zones_curses (const catacurses::window &w, const tripoint &start, const tripoint &end, const tripoint &offset)
Function Documentation
draw_bullet_curses()
void anonymous_namespace{animation.cpp}::draw_bullet_curses (map & m, const tripoint & t, const char bullet, const tripoint *const p)
Definition at line 456 of file animation.cpp.
 {
     if( !is_point_visible( t ) ) {
         return;
     }
     avatar &player_character = get_avatar();
     const tripoint vp = player_character.pos() + player_character.view_offset;
     if( vp.z != t.z ) {
         return;
     }
     shared_ptr_fast<game::draw_callback_t> bullet_cb = make_shared_fast<game::draw_callback_t>( [&]() {
         if( p != nullptr && p->z == vp.z ) {
             m.drawsq( g->w_terrain, *p, drawsq_params().center( vp ) );
         }
         mvwputch( g->w_terrain, t.xy() - vp.xy() + point( POSX, POSY ), c_red, bullet );
     } );
     g->add_draw_callback( bullet_cb );
     bullet_animation().progress();
 }
References c_red, g, get_avatar(), is_point_visible(), mvwputch(), Creature::pos(), POSX, POSY, anonymous_namespace{animation.cpp}::basic_animation::progress(), Character::view_offset, tripoint::xy(), and tripoint::z.
Referenced by game::draw_bullet().
draw_custom_explosion_curses()
void anonymous_namespace{animation.cpp}::draw_custom_explosion_curses (game & g, const std::list< std::map< tripoint, explosion_tile > > & layers)
Definition at line 189 of file animation.cpp.
 {
     avatar &player_character = get_avatar();
     // calculate screen offset relative to player + view offset position
     const tripoint center = player_character.pos() + player_character.view_offset;
     const tripoint topleft( center.x - getmaxx( g.w_terrain ) / 2,
                             center.y - getmaxy( g.w_terrain ) / 2, 0 );
     explosion_animation anim;
     auto last_layer_it = layers.begin();
     shared_ptr_fast<game::draw_callback_t> explosion_cb =
     make_shared_fast<game::draw_callback_t>( [&]() {
         for( auto it = layers.begin(); it != std::next( last_layer_it ); ++it ) {
             for( const auto &pr : *it ) {
                 // update tripoint in relation to top left corner of curses window
                 // mvwputch already filters out of bounds coordinates
                 const tripoint p = pr.first - topleft;
                 const explosion_neighbors ngh = pr.second.neighborhood;
                 const nc_color col = pr.second.color;
                 switch( ngh ) {
                     // '^', 'v', '<', '>'
                     case N_NORTH:
                         mvwputch( g.w_terrain, p.xy(), col, '^' );
                         break;
                     case N_SOUTH:
                         mvwputch( g.w_terrain, p.xy(), col, 'v' );
                         break;
                     case N_WEST:
                         mvwputch( g.w_terrain, p.xy(), col, '<' );
                         break;
                     case N_EAST:
                         mvwputch( g.w_terrain, p.xy(), col, '>' );
                         break;
                     // '|' and '-'
                     case N_NORTH | N_SOUTH:
                     case N_NORTH | N_SOUTH | N_WEST:
                     case N_NORTH | N_SOUTH | N_EAST:
                         mvwputch( g.w_terrain, p.xy(), col, '|' );
                         break;
                     case N_WEST | N_EAST:
                     case N_WEST | N_EAST | N_NORTH:
                     case N_WEST | N_EAST | N_SOUTH:
                         mvwputch( g.w_terrain, p.xy(), col, '-' );
                         break;
                     // '/' and '\'
                     case N_NORTH | N_WEST:
                     case N_SOUTH | N_EAST:
                         mvwputch( g.w_terrain, p.xy(), col, '/' );
                         break;
                     case N_SOUTH | N_WEST:
                     case N_NORTH | N_EAST:
                         mvwputch( g.w_terrain, p.xy(), col, '\\' );
                         break;
                     case N_NO_NEIGHBORS:
                         mvwputch( g.w_terrain, p.xy(), col, '*' );
                         break;
                     case N_WEST | N_EAST | N_NORTH | N_SOUTH:
                         break;
                 }
             }
         }
     } );
     g.add_draw_callback( explosion_cb );
     for( last_layer_it = layers.begin(); last_layer_it != layers.end(); ++last_layer_it ) {
         if( is_layer_visible( *last_layer_it ) ) {
             anim.progress();
         }
     }
 }
References center, g, get_avatar(), catacurses::getmaxx(), catacurses::getmaxy(), Creature::pos(), and Character::view_offset.
Referenced by explosion_handler::draw_custom_explosion().
draw_explosion_curses()
void anonymous_namespace{animation.cpp}::draw_explosion_curses (game & g, const tripoint & center, const int r, const nc_color & col)
Definition at line 133 of file animation.cpp.
 {
     if( !is_radius_visible( center, r ) ) {
         return;
     }
     // TODO: Make it look different from above/below
     const tripoint p = relative_view_pos( get_avatar(), center );
     explosion_animation anim;
     int frame = 0;
     shared_ptr_fast<game::draw_callback_t> explosion_cb =
     make_shared_fast<game::draw_callback_t>( [&]() {
         if( r == 0 ) {
             mvwputch( g.w_terrain, point( p.y, p.x ), col, '*' );
         }
         for( int i = 1; i <= frame; ++i ) {
             // corner: top left
             mvwputch( g.w_terrain, p.xy() + point( -i, -i ), col, '/' );
             // corner: top right
             mvwputch( g.w_terrain, p.xy() + point( i, -i ), col, '\\' );
             // corner: bottom left
             mvwputch( g.w_terrain, p.xy() + point( -i, i ), col, '\\' );
             // corner: bottom right
             mvwputch( g.w_terrain, p.xy() + point( i, i ), col, '/' );
             for( int j = 1 - i; j < 0 + i; j++ ) {
                 // edge: top
                 mvwputch( g.w_terrain, p.xy() + point( j, -i ), col, '-' );
                 // edge: bottom
                 mvwputch( g.w_terrain, p.xy() + point( j, i ), col, '-' );
                 // edge: left
                 mvwputch( g.w_terrain, p.xy() + point( -i, j ), col, '|' );
                 // edge: right
                 mvwputch( g.w_terrain, p.xy() + point( i, j ), col, '|' );
             }
         }
     } );
     g.add_draw_callback( explosion_cb );
     for( frame = 1; frame <= r; ++frame ) {
         anim.progress();
     }
 }
References center, g, get_avatar(), is_radius_visible(), mvwputch(), anonymous_namespace{animation.cpp}::basic_animation::progress(), relative_view_pos(), tripoint::x, tripoint::xy(), and tripoint::y.
Referenced by explosion_handler::draw_explosion().
draw_hit_mon_curses()
void anonymous_namespace{animation.cpp}::draw_hit_mon_curses (const tripoint & center, const monster & m, const avatar & u, const bool dead)
Definition at line 554 of file animation.cpp.
 {
     hit_animation( u, center, red_background( m.type->color ), dead ? "%" : m.symbol() );
 }
References center, mtype::color, hit_animation(), red_background(), monster::symbol(), monster::type, and u.
Referenced by game::draw_hit_mon().
draw_hit_player_curses()
void anonymous_namespace{animation.cpp}::draw_hit_player_curses (const game & , const Character & p, const int dam)
Definition at line 591 of file animation.cpp.
 {
     nc_color const col = !dam ? yellow_background( p.symbol_color() ) : red_background(
                              p.symbol_color() );
     hit_animation( get_avatar(), p.pos(), col, p.symbol() );
 }
References get_avatar(), hit_animation(), Creature::pos(), red_background(), Character::symbol(), Character::symbol_color(), and yellow_background().
Referenced by game::draw_hit_player().
draw_line_curses() [1/2]
void anonymous_namespace{animation.cpp}::draw_line_curses (game & g, const std::vector< tripoint > & points)
Definition at line 707 of file animation.cpp.
 {
     avatar &player_character = get_avatar();
     map &here = get_map();
     for( const tripoint &p : points ) {
         here.drawsq( g.w_terrain, p, drawsq_params().highlight( true ) );
     }
     const tripoint p = points.empty() ? tripoint {POSX, POSY, 0} :
                        relative_view_pos( player_character, points.back() );
     mvwputch( g.w_terrain, p.xy(), c_white, 'X' );
 }
References c_white, map::drawsq(), g, get_avatar(), get_map(), mvwputch(), POSX, POSY, relative_view_pos(), and tripoint::xy().
Referenced by game::draw_line().
draw_line_curses() [2/2]
void anonymous_namespace{animation.cpp}::draw_line_curses (game & g, const tripoint & center, const std::vector< tripoint > & ret, bool noreveal)
Definition at line 637 of file animation.cpp.
 {
     avatar &player_character = get_avatar();
     map &here = get_map();
     drawsq_params params = drawsq_params().highlight( true ).center( center );
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &p : ret ) {
         const Creature *critter = creatures.creature_at( p, true );
         // NPCs and monsters get drawn with inverted colors
         if( critter && player_character.sees( *critter ) ) {
             critter->draw( g.w_terrain, center, true );
         } else if( noreveal && !player_character.sees( p ) ) {
             // Draw a meaningless symbol. Avoids revealing tile, but keeps feedback
             const char sym = '?';
             const nc_color col = c_dark_gray;
             const catacurses::window &w = g.w_terrain;
             const int k = p.x + getmaxx( w ) / 2 - center.x;
             const int j = p.y + getmaxy( w ) / 2 - center.y;
             mvwputch( w, point( k, j ), col, sym );
         } else {
             // This function reveals tile at p and writes it to the player's memory
             here.drawsq( g.w_terrain, p, params );
         }
     }
 }
References c_dark_gray, center, drawsq_params::center(), creature_tracker::creature_at(), Creature::draw(), map::drawsq(), g, get_avatar(), get_creature_tracker(), get_map(), catacurses::getmaxx(), catacurses::getmaxy(), drawsq_params::highlight(), mvwputch(), cata::hash64_detail::ret, and Character::sees().
draw_sct_curses()
void anonymous_namespace{animation.cpp}::draw_sct_curses (const game & g)
Definition at line 790 of file animation.cpp.
 {
     avatar &player_character = get_avatar();
     const tripoint off = relative_view_pos( player_character, tripoint_zero );
     for( const scrollingcombattext::cSCT &text : SCT.vSCT ) {
         const int dy = off.y + text.getPosY();
         const int dx = off.x + text.getPosX();
         if( !is_valid_in_w_terrain( point( dx, dy ) ) ) {
             continue;
         }
         const bool is_old = text.getStep() >= scrollingcombattext::iMaxSteps / 2;
         nc_color const col1 = msgtype_to_color( text.getMsgType( "first" ),  is_old );
         nc_color const col2 = msgtype_to_color( text.getMsgType( "second" ), is_old );
         mvwprintz( g.w_terrain, point( dx, dy ), col1, text.getText( "first" ) );
         wprintz( g.w_terrain, col2, text.getText( "second" ) );
     }
 }
References g, get_avatar(), scrollingcombattext::cSCT::getMsgType(), scrollingcombattext::cSCT::getPosX(), scrollingcombattext::cSCT::getPosY(), scrollingcombattext::cSCT::getStep(), scrollingcombattext::cSCT::getText(), scrollingcombattext::iMaxSteps, is_valid_in_w_terrain(), msgtype_to_color(), mvwprintz(), relative_view_pos(), SCT, tripoint_zero, scrollingcombattext::vSCT, wprintz(), tripoint::x, and tripoint::y.
Referenced by game::draw_sct().
draw_weather_curses()
void anonymous_namespace{animation.cpp}::draw_weather_curses (const catacurses::window & win, const weather_printable & w)
Definition at line 763 of file animation.cpp.
 {
     for( const auto &drop : w.vdrops ) {
         mvwputch( win, point( drop.first, drop.second ), w.colGlyph, w.get_symbol() );
     }
 }
References weather_printable::colGlyph, weather_printable::get_symbol(), mvwputch(), and weather_printable::vdrops.
Referenced by game::draw_weather().
draw_zones_curses()
void anonymous_namespace{animation.cpp}::draw_zones_curses (const catacurses::window & w, const tripoint & start, const tripoint & end, const tripoint & offset)
Definition at line 832 of file animation.cpp.
 {
     if( end.x < start.x || end.y < start.y || end.z < start.z ) {
         return;
     }
     nc_color    const col = invert_color( c_light_green );
     const std::string line( end.x - start.x + 1, '~' );
     int         const x = start.x - offset.x;
     for( int y = start.y; y <= end.y; ++y ) {
         mvwprintz( w, point( x, y - offset.y ), col, line );
     }
 }
References c_light_green, keycode::end, invert_color(), line(), mvwprintz(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by game::draw_zones().
hit_animation()
void anonymous_namespace{animation.cpp}::hit_animation (const avatar & u, const tripoint & center, nc_color cColor, const std::string & cTile)
Definition at line 531 of file animation.cpp.
 {
     const tripoint init_pos = relative_view_pos( u, center );
     // Only show animation if initially visible
     if( init_pos.z == 0 && is_valid_in_w_terrain( init_pos.xy() ) ) {
         shared_ptr_fast<game::draw_callback_t> hit_cb = make_shared_fast<game::draw_callback_t>( [&]() {
             // In case the window is resized during waiting, we always re-calculate the animation position
             const tripoint pos = relative_view_pos( u, center );
             if( pos.z == 0 && is_valid_in_w_terrain( pos.xy() ) ) {
                 mvwprintz( g->w_terrain, pos.xy(), cColor, cTile );
             }
         } );
         g->add_draw_callback( hit_cb );
         ui_manager::redraw();
         inp_mngr.set_timeout( get_option<int>( "ANIMATION_DELAY" ) );
         // Skip input (if any), because holding down a key with sleep_for can get yourself killed
         inp_mngr.get_input_event();
         inp_mngr.reset_timeout();
     }
 }
References center, g, input_manager::get_input_event(), inp_mngr, is_valid_in_w_terrain(), mvwprintz(), math_opers::pos(), ui_manager::redraw(), relative_view_pos(), input_manager::reset_timeout(), input_manager::set_timeout(), u, tripoint::xy(), and tripoint::z.
Referenced by draw_hit_mon_curses(), and draw_hit_player_curses().
is_layer_visible()
bool anonymous_namespace{animation.cpp}::is_layer_visible (const std::map< tripoint, explosion_tile > & layer)
Definition at line 113 of file animation.cpp.
 {
     return std::any_of( layer.begin(), layer.end(),
     []( const std::pair<tripoint, explosion_tile> &element ) {
         return is_point_visible( element.first );
     } );
 }
Referenced by explosion_handler::draw_custom_explosion().
is_point_visible()
bool anonymous_namespace{animation.cpp}::is_point_visible (const tripoint & p, int margin = 0)
Definition at line 103 of file animation.cpp.
 {
     return g->is_in_viewport( p, margin ) && get_player_view().sees( p );
 }
References g, get_player_view(), and viewer::sees().
Referenced by draw_bullet_curses(), and is_radius_visible().
is_radius_visible()
bool anonymous_namespace{animation.cpp}::is_radius_visible (const tripoint & center, int radius)
Definition at line 108 of file animation.cpp.
 {
     return is_point_visible( center, -radius );
 }
References center, and is_point_visible().
Referenced by draw_explosion_curses().
operator^()
constexpr explosion_neighbors anonymous_namespace{animation.cpp}::operator^ (explosion_neighbors lhs, explosion_neighbors rhs) constexpr
Definition at line 184 of file animation.cpp.
 {
     return static_cast<explosion_neighbors>( static_cast< int >( lhs ) ^ static_cast< int >( rhs ) );
 }
operator|()
constexpr explosion_neighbors anonymous_namespace{animation.cpp}::operator| (explosion_neighbors lhs, explosion_neighbors rhs) constexpr
Definition at line 179 of file animation.cpp.
 {
     return static_cast<explosion_neighbors>( static_cast< int >( lhs ) | static_cast< int >( rhs ) );
 }
relative_view_pos() [1/2]
tripoint anonymous_namespace{animation.cpp}::relative_view_pos (const avatar & u, const tripoint & p) noexcept
Get p relative to u's current position and view.
Definition at line 122 of file animation.cpp.
 {
     return p - u.view_offset + tripoint( POSX - u.posx(), POSY - u.posy(), -u.posz() );
 }
References POSX, POSY, and u.
relative_view_pos() [2/2]
tripoint anonymous_namespace{animation.cpp}::relative_view_pos (const game & g, const tripoint & p) noexcept
Definition at line 128 of file animation.cpp.
 {
     return p - g.ter_view_p + point( POSX, POSY );
 }
References g, POSX, and POSY.
Referenced by game::draw_cursor(), explosion_handler::draw_custom_explosion(), draw_explosion_curses(), draw_line_curses(), draw_sct_curses(), and hit_animation().