Cataclysm DDA: weather_types Namespace Reference
weather_types Namespace Reference
Functions
const std::vector< weather_type > & get_all ()
Get all currently loaded weather types.
void finalize_all ()
Finalize all loaded weather types.
void reset ()
Clear all loaded weather types (invalidating any pointers)
void load (const JsonObject &jo, const std::string &src)
Load weather type from JSON definition.
void check_consistency ()
Checks all loaded from JSON are valid.
Function Documentation
check_consistency()
void weather_types::check_consistency ()
Checks all loaded from JSON are valid.
Definition at line 162 of file weather_type.cpp.
 {
     if( !WEATHER_CLEAR.is_valid() ) {
         cata_fatal( "Weather type clear is required." );
     }
     if( !WEATHER_NULL.is_valid() ) {
         cata_fatal( "Weather type null is required." );
     }
     weather_type_factory.check();
 }
References cata_fatal, string_id< T >::is_valid(), WEATHER_CLEAR(), WEATHER_NULL(), and anonymous_namespace{weather_type.cpp}::weather_type_factory.
Referenced by DynamicDataLoader::check_consistency().
finalize_all()
void weather_types::finalize_all ()
Finalize all loaded weather types.
Definition at line 149 of file weather_type.cpp.
 {
     weather_type_factory.finalize();
     for( const weather_type &wt : weather_type_factory.get_all() ) {
         const_cast<weather_type &>( wt ).finalize();
     }
 }
References behavior::finalize(), and anonymous_namespace{weather_type.cpp}::weather_type_factory.
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< weather_type > & weather_types::get_all ()
Get all currently loaded weather types.
Definition at line 157 of file weather_type.cpp.
 {
     return weather_type_factory.get_all();
 }
References anonymous_namespace{weather_type.cpp}::weather_type_factory.
Referenced by weather_generator::sort_weather().
load()
void weather_types::load (const JsonObject & jo, const std::string & src)
Load weather type from JSON definition.
Definition at line 173 of file weather_type.cpp.
 {
     weather_type_factory.load( jo, src );
 }
References anonymous_namespace{weather_type.cpp}::weather_type_factory.
Referenced by DynamicDataLoader::initialize().
reset()
void weather_types::reset ()
Clear all loaded weather types (invalidating any pointers)
Definition at line 144 of file weather_type.cpp.
 {
     weather_type_factory.reset();
 }
References anonymous_namespace{weather_type.cpp}::weather_type_factory.
Referenced by DynamicDataLoader::unload_data().