Cataclysm DDA: pf::anonymous_namespace{simple_pathfinding.cpp} Namespace Reference
pf::anonymous_namespace{simple_pathfinding.cpp} Namespace Reference
Classes
struct point_node
struct node_address
struct node_address_hasher
struct scored_address
struct navigation_node
Functions
const tripoint & direction_to_tripoint (direction dir)
bool is_horizontal (direction dir)
const std::vector< direction > & enumerate_directions (bool allow_z_change)
direction reverse_direction (direction dir)
int adjust_omt_cost (int base_cost, direction dir_in, direction dir_out)
Function Documentation
adjust_omt_cost()
int pf::anonymous_namespace{simple_pathfinding.cpp}::adjust_omt_cost (int base_cost, direction dir_in, direction dir_out)
Definition at line 258 of file simple_pathfinding.cpp.
 {
     // Adjust cost for 90-degree turns. We travel from the midpoint of one edge
     // to the midpoint of an adjacent edge in a square, which is a diagonal
     // line with length = sqrt(2) / 2 for a unit square.
     if( dir_in != dir_out && is_horizontal( dir_in ) && is_horizontal( dir_out ) ) {
         // Note: sqrt(2) is approximately equal to 99 / 70.
         return base_cost * 99 / 140;
     }
     return base_cost;
 }
References is_horizontal().
Referenced by pf::find_overmap_path().
direction_to_tripoint()
const tripoint& pf::anonymous_namespace{simple_pathfinding.cpp}::direction_to_tripoint (direction dir)
Definition at line 134 of file simple_pathfinding.cpp.
 {
     switch( dir ) {
         case direction::EAST:
             return tripoint_east;
         case direction::SOUTH:
             return tripoint_south;
         case direction::WEST:
             return tripoint_west;
         case direction::NORTH:
             return tripoint_north;
         case direction::ABOVECENTER:
             return tripoint_above;
         case direction::BELOWCENTER:
             return tripoint_below;
         default:
             debugmsg( "Unexpected direction: %d", static_cast<int>( dir ) );
             return tripoint_zero;
     }
 }
References ABOVECENTER, BELOWCENTER, debugmsg, EAST, NORTH, SOUTH, tripoint_above, tripoint_below, tripoint_east, tripoint_north, tripoint_south, tripoint_west, tripoint_zero, and WEST.
Referenced by pf::anonymous_namespace{simple_pathfinding.cpp}::node_address::displace(), and reverse_direction().
enumerate_directions()
const std::vector<direction>& pf::anonymous_namespace{simple_pathfinding.cpp}::enumerate_directions (bool allow_z_change)
Definition at line 236 of file simple_pathfinding.cpp.
 {
     static const std::vector<direction> cardinal_dirs = {direction::EAST, direction::SOUTH, direction::WEST, direction::NORTH};
     static const std::vector<direction> all_dirs = [&]() {
         std::vector<direction> ret = cardinal_dirs;
         ret.push_back( direction::ABOVECENTER );
         ret.push_back( direction::BELOWCENTER );
         return ret;
     }
     ();
     if( allow_z_change ) {
         return all_dirs;
     } else {
         return cardinal_dirs;
     }
 }
References ABOVECENTER, BELOWCENTER, EAST, NORTH, cata::hash64_detail::ret, SOUTH, and WEST.
Referenced by pf::find_overmap_path().
is_horizontal()
bool pf::anonymous_namespace{simple_pathfinding.cpp}::is_horizontal (direction dir)
Definition at line 155 of file simple_pathfinding.cpp.
 {
     switch( dir ) {
         case direction::EAST:
         case direction::SOUTH:
         case direction::WEST:
         case direction::NORTH:
             return true;
         default:
             return false;
     }
 }
References EAST, NORTH, SOUTH, and WEST.
Referenced by adjust_omt_cost().
reverse_direction()
direction pf::anonymous_namespace{simple_pathfinding.cpp}::reverse_direction (direction dir)
Definition at line 253 of file simple_pathfinding.cpp.
 {
     return direction_from( -direction_to_tripoint( dir ) );
 }
References direction_from(), and direction_to_tripoint().
Referenced by pf::find_overmap_path().