Cataclysm DDA: field_types Namespace Reference
field_types Namespace Reference
Functions
void load (const JsonObject &jo, const std::string &src)
void finalize_all ()
void check_consistency ()
void reset ()
void load_immunity (const JsonObject &jid, field_immunity_data &fd)
const std::vector< field_type > & get_all ()
field_type get_field_type_by_legacy_enum (int legacy_enum_id)
Function Documentation
check_consistency()
void field_types::check_consistency ()
Definition at line 375 of file field_type.cpp.
 {
     get_all_field_types().check();
 }
References get_all_field_types().
Referenced by DynamicDataLoader::check_consistency().
finalize_all()
void field_types::finalize_all ()
Definition at line 367 of file field_type.cpp.
 {
     get_all_field_types().finalize();
     for( const field_type &fd : get_all_field_types().get_all() ) {
         const_cast<field_type &>( fd ).finalize();
     }
 }
References behavior::finalize(), ammo_effects::get_all(), and get_all_field_types().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< field_type > & field_types::get_all ()
Definition at line 407 of file field_type.cpp.
 {
     return get_all_field_types().get_all();
 }
References get_all_field_types().
get_field_type_by_legacy_enum()
field_type field_types::get_field_type_by_legacy_enum (int legacy_enum_id)
Definition at line 412 of file field_type.cpp.
 {
     for( const field_type &ft : get_all_field_types().get_all() ) {
         if( legacy_enum_id == ft.legacy_enum_id ) {
             return ft;
         }
     }
     debugmsg( "Cannot find field_type for legacy enum: %d.", legacy_enum_id );
     return field_type();
 }
References debugmsg, ammo_effects::get_all(), and get_all_field_types().
Referenced by submap::load().
load()
void field_types::load (const JsonObject & jo, const std::string & src)
Definition at line 362 of file field_type.cpp.
 {
     get_all_field_types().load( jo, src );
 }
References get_all_field_types().
Referenced by DynamicDataLoader::initialize().
load_immunity()
void field_types::load_immunity (const JsonObject & jid, field_immunity_data & fd)
Definition at line 385 of file field_type.cpp.
 {
     for( const std::string id : jid.get_array( "flags" ) ) {
         fd.immunity_data_flags.emplace_back( id );
     }
     for( JsonArray jao : jid.get_array( "body_part_env_resistance" ) ) {
         fd.immunity_data_body_part_env_resistance.emplace_back(
             io::string_to_enum<body_part_type::type>
             ( jao.get_string( 0 ) ), jao.get_int( 1 ) );
     }
     for( JsonArray jao : jid.get_array( "immunity_flags_worn" ) ) {
         fd.immunity_data_part_item_flags.emplace_back( io::string_to_enum<body_part_type::type>
                 ( jao.get_string( 0 ) ), jao.get_string( 1 ) );
     }
     for( JsonArray jao : jid.get_array( "immunity_flags_worn_any" ) ) {
         fd.immunity_data_part_item_flags_any.emplace_back(
             io::string_to_enum<body_part_type::type>
             ( jao.get_string( 0 ) ), jao.get_string( 1 ) );
     }
 }
References JsonObject::get_array(), field_immunity_data::immunity_data_body_part_env_resistance, field_immunity_data::immunity_data_flags, field_immunity_data::immunity_data_part_item_flags, and field_immunity_data::immunity_data_part_item_flags_any.
Referenced by field_type::load().
reset()
void field_types::reset ()
Definition at line 380 of file field_type.cpp.
 {
     get_all_field_types().reset();
 }
References get_all_field_types().
Referenced by DynamicDataLoader::unload_data().