Cataclysm DDA: suffer Namespace Reference
suffer Namespace Reference
Functions
static void from_sunburn (Character &you, bool severe)
static void in_sunlight (Character &you)
static void water_damage (Character &you)
static void mutation_power (Character &you, const trait_id &mut_id)
static void while_underwater (Character &you)
static void while_grabbed (Character &you)
static void from_addictions (Character &you)
static void while_awake (Character &you, int current_stim)
static void from_chemimbalance (Character &you)
static void from_asthma (Character &you, int current_stim)
static void from_item_dropping (Character &you)
static void from_other_mutations (Character &you)
static void from_radiation (Character &you)
static void from_bad_bionics (Character &you)
static void from_stimulants (Character &you, int current_stim)
static void from_exertion (Character &you)
static void without_sleep (Character &you, int sleep_deprivation)
static void from_tourniquet (Character &you)
static void from_nyctophobia (Character &you)
static void from_artifact_resonance (Character &you, int amt)
Function Documentation
from_addictions()
void suffer::from_addictions (Character & you) static
Definition at line 375 of file suffer.cpp.
 {
     time_duration timer = -6_hours;
     if( you.has_trait( trait_ADDICTIVE ) ) {
         timer = -10_hours;
     } else if( you.has_trait( trait_NONADDICTIVE ) ) {
         timer = -3_hours;
     }
     for( addiction &cur_addiction : you.addictions ) {
         if( cur_addiction.sated <= 0_turns &&
             cur_addiction.intensity >= MIN_ADDICTION_LEVEL ) {
             cur_addiction.run_effect( you );
         }
         cur_addiction.sated -= 1_turns;
         // Higher intensity addictions heal faster
         if( cur_addiction.sated - 10_minutes * cur_addiction.intensity < timer ) {
             if( cur_addiction.intensity <= 2 ) {
                 you.rem_addiction( cur_addiction.type );
                 break;
             } else {
                 cur_addiction.intensity--;
                 cur_addiction.sated = 0_turns;
             }
         }
     }
 }
References Character::addictions, Character::has_trait(), addiction::intensity, MIN_ADDICTION_LEVEL, Character::rem_addiction(), addiction::run_effect(), addiction::sated, trait_ADDICTIVE, trait_NONADDICTIVE, and addiction::type.
Referenced by Character::suffer().
from_artifact_resonance()
void suffer::from_artifact_resonance (Character & you, int amt) static
Definition at line 1549 of file suffer.cpp.
 {
     int rng_outcome;
     if( rng( 0, 3600 + std::floor( amt / 2000 ) ) > 3600 ) {
         if( amt > 12500 && one_in( 2 ) ) {
             //deadly effects from way too high resonance
             rng_outcome = rng( 1, 3 );
             if( rng_outcome == 1 ) {
                 you.add_msg_player_or_npc( m_bad, _( "You attract the attention of something horrible." ),
                                            _( "<npcname> attracts the attention of something horrible." ) );
                 map &here = get_map();
                 for( const tripoint &dest : here.points_in_radius( you.pos(), 12 ) ) {
                     if( here.is_cornerfloor( dest ) ) {
                         here.add_field( dest, fd_tindalos_rift, 3 );
                         add_msg( m_info, _( "You hear a low-pitched echoing howl." ) );
                     }
                 }
             } else if( rng_outcome == 2 ) {
                 you.add_msg_player_or_npc( m_bad, _( "Reality gives way under your feet like rotten scaffolding." ),
                                            _( "Reality gives way under <npcname>'s feet like rotten scaffolding." ) );
                 map &here = get_map();
                 here.add_field( you.pos(), fd_reality_tear, 1 );
             } else if( rng_outcome == 3 ) {
                 you.add_msg_player_or_npc( m_bad, _( "You suddenly lose all substance and corporeality." ),
                                            _( "<npcname> suddenly loses all substance and corporeality." ) );
                 you.add_effect( effect_incorporeal, 1_minutes );
             }
         } else if( amt > 7500 && one_in( 2 ) ) {
             //severe effects from very high resonance
             rng_outcome = rng( 1, 3 );
             if( rng_outcome == 1 ) {
                 you.add_msg_player_or_npc( m_bad, _( "You are suddenly beset with agonizing, unbearable pain." ),
                                            _( "<npcname> suddenly cries out in agony." ) );
                 you.mod_pain( 100 );
                 you.shout();
             } else if( rng_outcome == 2 ) {
                 you.add_msg_player_or_npc( m_bad, _( "The air folds and distorts around you." ),
                                            _( "The air folds and distorts around <npcname>." ) );
                 teleport::teleport( you );
             } else if( rng_outcome == 3 ) {
                 you.add_msg_player_or_npc( m_bad, _( "You're bombarded with radioactive energy!" ),
                                            _( "<npcname> is bombarded with radioactive energy!" ) );
                 you.irradiate( 5, true );
                 you.irradiate( 45, false );
             }
         } else if( amt > 4500 && one_in( 2 ) ) {
             //bad effects from moderately high resonance
             rng_outcome = rng( 1, 3 );
             if( rng_outcome == 1  && !you.in_vehicle ) {
                 you.add_msg_player_or_npc( m_bad, _( "You suddenly shift slightly." ),
                                            _( "<npcname> suddenly shifts slightly." ) );
                 teleport::teleport( you, 1, 1, true, false );
             } else if( rng_outcome == 2 ) {
                 you.add_msg_player_or_npc( m_bad,
                                            _( "You hear a painfully loud grinding noise from your location." ),
                                            _( "A painfully loud grinding noise suddenly blares from the location of <npcname>." ) );
                 sounds::sound( you.pos(), 5000, sounds::sound_t::movement, _( "A horribly loud grinding sound!" ),
                                true, "misc", "scraping" );
             } else if( rng_outcome == 3 ) {
                 you.add_msg_player_or_npc( m_bad,
                                            _( "The air suddenly crackles around you." ),
                                            _( "The air suddenly crackles around <npcname>." ) );
                 you.irradiate( 10, false );
             }
         } else {
             //mild effects from somewhat high resonance
             rng_outcome = rng( 1, 3 );
             if( rng_outcome == 1 ) {
                 you.add_msg_if_player( m_bad,
                                        _( "You suddenly feel a sharp, stabbing pain with no apparent source." ) );
                 you.mod_pain( 5 );
             } else if( rng_outcome == 2 ) {
                 you.add_msg_if_player( m_bad,
                                        _( "Your vision becomes blurry and you suddenly feel like you're falling." ) );
                 you.add_effect( effect_visuals, 5_minutes );
             } else if( rng_outcome == 3 ) {
                 you.add_msg_if_player( m_bad, _( "You suddenly feel very queasy." ) );
                 you.add_effect( effect_nausea, 5_minutes );
             }
         }
     }
 }
References _, Creature::add_effect(), map::add_field(), add_msg(), Character::add_msg_if_player(), Character::add_msg_player_or_npc(), effect_incorporeal, effect_nausea, effect_visuals, fd_reality_tear, fd_tindalos_rift, floor(), get_map(), Character::in_vehicle, Character::irradiate(), map::is_cornerfloor(), m_bad, m_info, Character::mod_pain(), sounds::movement, one_in(), map::points_in_radius(), Creature::pos(), rng(), Character::shout(), sounds::sound(), and teleport::teleport().
Referenced by while_awake().
from_asthma()
void suffer::from_asthma (Character & you, int current_stim) static
Definition at line 540 of file suffer.cpp.
 {
     if( you.has_effect( effect_adrenaline ) ||
         you.has_effect( effect_datura ) ||
         you.has_effect( effect_took_antiasthmatic ) ) {
         return;
     }
     //cap asthma attacks to 1 per minute (or risk instantly killing players that rely on oxygen tanks)
     if( !one_in( std::max( to_turns<int>( 1_minutes ),
                            ( to_turns<int>( 6_hours ) - current_stim * 300 ) ) *
                  ( you.has_effect( effect_sleep ) ? 10 : 1 ) ) ) {
         return;
     }
     bool auto_use = you.has_charges( itype_inhaler, 1 ) || you.has_charges( itype_oxygen_tank, 1 ) ||
                     you.has_charges( itype_smoxygen_tank, 1 );
     bool oxygenator = you.has_bionic( bio_gills ) &&
                       you.get_power_level() >= ( bio_gills->power_trigger / 8 );
     if( you.underwater ) {
         you.oxygen = you.oxygen / 2;
         auto_use = false;
     }
     you.add_msg_player_or_npc( m_bad, _( "You have an asthma attack!" ),
                                _( "<npcname> starts wheezing and coughing." ) );
     map &here = get_map();
     if( you.in_sleep_state() && !you.has_effect( effect_narcosis ) ) {
         inventory map_inv;
         map_inv.form_from_map( you.pos(), 2, &you );
         // check if an inhaler is somewhere near
         bool nearby_use = auto_use || oxygenator || map_inv.has_charges( itype_inhaler, 1 ) ||
                           map_inv.has_charges( itype_oxygen_tank, 1 ) ||
                           map_inv.has_charges( itype_smoxygen_tank, 1 );
         // check if character has an oxygenator first
         if( oxygenator ) {
             you.mod_power_level( -bio_gills->power_trigger / 8 );
             you.add_msg_if_player( m_info, _( "You use your Oxygenator to clear it up, "
                                               "then go back to sleep." ) );
         } else if( auto_use  && !you.has_bionic( bio_sleep_shutdown ) ) {
             if( you.use_charges_if_avail( itype_inhaler, 1 ) ) {
                 you.add_msg_if_player( m_info, _( "You use your inhaler and go back to sleep." ) );
                 you.add_effect( effect_took_antiasthmatic, rng( 6_hours, 12_hours ) );
             } else if( you.use_charges_if_avail( itype_oxygen_tank, 1 ) ||
                        you.use_charges_if_avail( itype_smoxygen_tank, 1 ) ) {
                 you.add_msg_if_player( m_info, _( "You take a deep breath from your oxygen tank "
                                                   "and go back to sleep." ) );
             }
         } else if( nearby_use  && !you.has_bionic( bio_sleep_shutdown ) ) {
             // create new variable to resolve a reference issue
             int amount = 1;
             if( !here.use_charges( you.pos(), 2, itype_inhaler, amount ).empty() ) {
                 you.add_msg_if_player( m_info, _( "You use your inhaler and go back to sleep." ) );
                 you.add_effect( effect_took_antiasthmatic, rng( 6_hours, 12_hours ) );
             } else if( !here.use_charges( you.pos(), 2, itype_oxygen_tank, amount ).empty() ||
                        !here.use_charges( you.pos(), 2, itype_smoxygen_tank, amount ).empty() ) {
                 you.add_msg_if_player( m_info, _( "You take a deep breath from your oxygen tank "
                                                   "and go back to sleep." ) );
             }
         } else {
             you.add_effect( effect_asthma, rng( 5_minutes, 20_minutes ) );
             if( you.has_effect( effect_sleep ) ) {
                 if( !you.has_bionic( bio_sleep_shutdown ) ) {
                     you.wake_up();
                 }
             } else {
                 if( uistate.distraction_asthma && !you.is_npc() ) {
                     g->cancel_activity_or_ignore_query( distraction_type::asthma,
                                                         _( "You can't focus while choking!" ) );
                 }
             }
         }
     } else if( auto_use ) {
         int charges = 0;
         if( you.use_charges_if_avail( itype_inhaler, 1 ) ) {
             you.mod_moves( -to_moves<int>( 1_seconds ) * 0.4 );
             charges = you.charges_of( itype_inhaler );
             if( charges == 0 ) {
                 you.add_msg_if_player( m_bad, _( "You use your last inhaler charge." ) );
             } else {
                 you.add_msg_if_player( m_info, n_gettext( "You use your inhaler; "
                                        "only %d charge left.",
                                        "You use your inhaler; "
                                        "only %d charges left.", charges ),
                                        charges );
             }
             you.add_effect( effect_took_antiasthmatic, rng( 6_hours, 12_hours ) );
         } else if( you.use_charges_if_avail( itype_oxygen_tank, 1 ) ||
                    you.use_charges_if_avail( itype_smoxygen_tank, 1 ) ) {
             you.mod_moves( -to_moves<int>( 5_seconds ) ); // synched with use action
             charges = you.charges_of( itype_oxygen_tank ) + you.charges_of( itype_smoxygen_tank );
             if( charges == 0 ) {
                 you.add_msg_if_player( m_bad, _( "You breathe in the last bit of oxygen "
                                                  "from the tank." ) );
             } else {
                 you.add_msg_if_player( m_info, n_gettext( "You take a deep breath from your oxygen "
                                        "tank; only %d charge left.",
                                        "You take a deep breath from your oxygen "
                                        "tank; only %d charges left.", charges ),
                                        charges );
             }
         }
     } else {
         you.add_effect( effect_asthma, rng( 5_minutes, 20_minutes ) );
         if( uistate.distraction_asthma && !you.is_npc() ) {
             g->cancel_activity_or_ignore_query( distraction_type::asthma,
                                                 _( "You can't focus while choking!" ) );
         }
     }
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), Character::add_msg_player_or_npc(), asthma, bio_gills, bio_sleep_shutdown, Character::charges_of(), uistatedata::distraction_asthma, effect_adrenaline, effect_asthma, effect_datura, effect_narcosis, effect_sleep, effect_took_antiasthmatic, inventory::form_from_map(), g, get_map(), Character::get_power_level(), Character::has_bionic(), read_only_visitable::has_charges(), Character::has_charges(), Creature::has_effect(), Character::in_sleep_state(), Character::is_npc(), itype_inhaler, itype_oxygen_tank, itype_smoxygen_tank, m_bad, m_info, max(), Creature::mod_moves(), Character::mod_power_level(), n_gettext, one_in(), Character::oxygen, Creature::pos(), bionic_data::power_trigger, rng(), uistate, Creature::underwater, map::use_charges(), Character::use_charges_if_avail(), and Character::wake_up().
Referenced by Character::suffer().
from_bad_bionics()
void suffer::from_bad_bionics (Character & you) static
Definition at line 1202 of file suffer.cpp.
 {
     // Negative bionics effects
     if( you.has_bionic( bio_synlungs ) && !you.has_active_bionic( bio_synlungs ) &&
         !you.has_effect( effect_narcosis ) ) {
         if( you.get_power_level() >= bio_synlungs->power_trigger ) {
             std::optional<bionic *> bio_opt = you.find_bionic_by_type( bio_synlungs );
             you.activate_bionic( **bio_opt );
         } else {
             you.mod_stamina( -2000 );
             you.add_msg_if_player( m_bad, _( "Emergency!  User's lungs are not powered!" ) );
         }
     }
     if( you.has_bionic( bio_dis_shock ) && you.get_power_level() > bio_dis_shock->power_trigger &&
         one_turn_in( 2_hours ) &&
         !you.has_effect( effect_narcosis ) ) {
         if( !you.has_flag( json_flag_PAIN_IMMUNE ) ) {
             you.add_msg_if_player( m_bad, _( "You suffer a painful electrical discharge!" ) );
             you.mod_pain( 1 );
         } else {
             you.add_msg_if_player( m_bad, _( "You experience an electrical discharge!" ) );
         }
         you.mod_moves( -to_moves<int>( 1_seconds ) * 1.5 );
         you.mod_power_level( -bio_dis_shock->power_trigger );
         item_location weapon = you.get_wielded_item();
         if( weapon && weapon->typeId() == itype_e_handcuffs && weapon->charges > 0 ) {
             weapon->charges -= rng( 1, 3 ) * 50;
             if( weapon->charges < 1 ) {
                 weapon->charges = 1;
             }
             you.add_msg_if_player( m_good, _( "The %s seems to be affected by the discharge." ),
                                    weapon->tname() );
         }
         sfx::play_variant_sound( "bionics", "elec_discharge", 100 );
     }
     if( you.has_bionic( bio_dis_acid ) && one_turn_in( 150_minutes ) ) {
         if( !you.has_flag( json_flag_PAIN_IMMUNE ) ) {
             you.add_msg_if_player( m_bad, _( "You suffer a burning acidic discharge!" ) );
         } else {
             you.add_msg_if_player( m_bad, _( "You experience an acidic discharge!" ) );
         }
         you.hurtall( 1, nullptr );
         sfx::play_variant_sound( "bionics", "acid_discharge", 100 );
         sfx::do_player_death_hurt( get_player_character(), false );
     }
     if( you.has_bionic( bio_power_weakness ) && you.has_max_power() &&
         you.get_power_level() >= you.get_max_power_level() * .75 ) {
         you.mod_str_bonus( -3 );
     }
     if( you.has_bionic( bio_radleak ) && one_turn_in( 300_minutes ) ) {
         you.add_msg_if_player( m_bad, _( "You CBM leaks radiation." ) );
         if( you.has_effect( effect_iodine ) ) {
             you.mod_rad( 2 );
         } else {
             you.mod_rad( 5 );
         }
     }
 }
References _, Character::activate_bionic(), Character::add_msg_if_player(), bio_dis_acid, bio_dis_shock, bio_power_weakness, bio_radleak, bio_synlungs, item::charges, sfx::do_player_death_hurt(), effect_iodine, effect_narcosis, Character::find_bionic_by_type(), Character::get_max_power_level(), get_player_character(), Character::get_power_level(), Character::get_wielded_item(), Character::has_active_bionic(), Character::has_bionic(), Creature::has_effect(), Character::has_flag(), Character::has_max_power(), Character::hurtall(), itype_e_handcuffs, json_flag_PAIN_IMMUNE, m_bad, m_good, Creature::mod_moves(), Character::mod_pain(), Character::mod_power_level(), Character::mod_rad(), Character::mod_stamina(), Character::mod_str_bonus(), one_turn_in(), sfx::play_variant_sound(), bionic_data::power_trigger, rng(), item::tname(), and item::typeId().
Referenced by Character::suffer().
from_chemimbalance()
void suffer::from_chemimbalance (Character & you) static
Definition at line 477 of file suffer.cpp.
 {
     if( one_turn_in( 6_hours ) && !you.has_flag( json_flag_PAIN_IMMUNE ) ) {
         you.add_msg_if_player( m_bad, _( "You suddenly feel sharp pain for no reason." ) );
         you.mod_pain( 3 * rng( 1, 3 ) );
     }
     if( one_turn_in( 6_hours ) ) {
         int pkilladd = 5 * rng( -1, 2 );
         if( pkilladd > 0 ) {
             you.add_msg_if_player( m_bad, _( "You suddenly feel numb." ) );
         } else if( ( pkilladd < 0 ) && ( !you.has_flag( json_flag_PAIN_IMMUNE ) ) ) {
             you.add_msg_if_player( m_bad, _( "You suddenly ache." ) );
         }
         you.mod_painkiller( pkilladd );
     }
     if( one_turn_in( 6_hours ) && !you.has_effect( effect_sleep ) ) {
         you.add_msg_if_player( m_bad, _( "You feel dizzy for a moment." ) );
         you.mod_moves( -to_moves<int>( 1_seconds ) * rng_float( 0.1, 0.3 ) );
     }
     if( one_turn_in( 6_hours ) ) {
         int hungadd = 5 * rng( -1, 3 );
         if( hungadd > 0 ) {
             you.add_msg_if_player( m_bad, _( "You suddenly feel hungry." ) );
         } else {
             you.add_msg_if_player( m_good, _( "You suddenly feel a little full." ) );
         }
         you.mod_hunger( hungadd );
     }
     if( one_turn_in( 6_hours ) ) {
         you.add_msg_if_player( m_bad, _( "You suddenly feel thirsty." ) );
         you.mod_thirst( 5 * rng( 1, 3 ) );
     }
     if( one_turn_in( 6_hours ) ) {
         you.add_msg_if_player( m_good, _( "You feel sleepy all of a sudden." ) );
         you.mod_sleepiness( 10 * rng( 2, 4 ) );
     }
     if( one_turn_in( 8_hours ) ) {
         if( one_in( 3 ) ) {
             you.add_morale( MORALE_FEELING_GOOD, 20, 100 );
         } else {
             you.add_morale( MORALE_FEELING_BAD, -20, -100 );
         }
     }
     if( one_turn_in( 6_hours ) ) {
         if( one_in( 3 ) ) {
             you.add_msg_if_player( m_bad, _( "You suddenly feel very cold." ) );
             you.set_all_parts_temp_cur( BODYTEMP_VERY_COLD );
         } else {
             you.add_msg_if_player( m_bad, _( "You suddenly feel cold." ) );
             you.set_all_parts_temp_cur( BODYTEMP_COLD );
         }
     }
     if( one_turn_in( 6_hours ) ) {
         if( one_in( 3 ) ) {
             you.add_msg_if_player( m_bad, _( "You suddenly feel very hot." ) );
             you.set_all_parts_temp_cur( BODYTEMP_VERY_HOT );
         } else {
             you.add_msg_if_player( m_bad, _( "You suddenly feel hot." ) );
             you.set_all_parts_temp_cur( BODYTEMP_HOT );
         }
     }
 }
References _, Character::add_morale(), Character::add_msg_if_player(), BODYTEMP_COLD, BODYTEMP_HOT, BODYTEMP_VERY_COLD, BODYTEMP_VERY_HOT, effect_sleep, Creature::has_effect(), Character::has_flag(), json_flag_PAIN_IMMUNE, m_bad, m_good, Character::mod_hunger(), Creature::mod_moves(), Character::mod_pain(), Character::mod_painkiller(), Character::mod_sleepiness(), Character::mod_thirst(), MORALE_FEELING_BAD, MORALE_FEELING_GOOD, one_in(), one_turn_in(), rng(), rng_float(), and Creature::set_all_parts_temp_cur().
Referenced by while_awake().
from_exertion()
void suffer::from_exertion (Character & you) static
Definition at line 1398 of file suffer.cpp.
 {
     int new_weary_level = you.weariness_level();
     float max_activity = you.maximum_exertion_level();
     // Only if there are changes (duh)
     if( new_weary_level != you.old_weary_level ) {
         apply_weariness( you, new_weary_level, you.old_weary_level );
     }
     // Significantly slow the rate of messaging when in an activity
     const int chance = you.activity ? to_turns<int>( 48_minutes ) : to_turns<int>( 5_minutes );
     if( !you.in_sleep_state() && you.activity_history.activity( false ) > max_activity &&
         one_in( chance ) ) {
         you.add_msg_if_player( m_bad,
                                _( "You're tiring out; continuing to work at this rate will be slower." ) );
     }
     // This must happen at the end, for hopefully obvious reasons
     you.old_weary_level = new_weary_level;
 }
References _, activity_tracker::activity(), Character::activity, Character::activity_history, Character::add_msg_if_player(), apply_weariness(), Character::in_sleep_state(), m_bad, Character::maximum_exertion_level(), Character::old_weary_level, one_in(), and Character::weariness_level().
Referenced by Character::suffer().
from_item_dropping()
void suffer::from_item_dropping (Character & you) static
Definition at line 975 of file suffer.cpp.
 {
     if( you.has_effect( effect_incorporeal ) && !you.has_flag( json_flag_ETHEREAL ) ) {
         std::vector<item *> dump = you.inv_dump();
         std::list<item> tumble_items;
         for( item *dump_item : dump ) {
             if( !dump_item->has_flag( flag_NO_UNWIELD ) && !dump_item->has_flag( flag_NO_TAKEOFF ) &&
                 !dump_item->has_flag( flag_INTEGRATED ) ) {
                 tumble_items.push_back( *dump_item );
             }
         }
         put_into_vehicle_or_drop( you, item_drop_reason::tumbling, tumble_items );
         for( item *i : dump ) {
             you.i_rem( i );
         }
     }
 }
References effect_incorporeal, flag_INTEGRATED, flag_NO_TAKEOFF, flag_NO_UNWIELD, Creature::has_effect(), Character::has_flag(), Character::i_rem(), Character::inv_dump(), json_flag_ETHEREAL, put_into_vehicle_or_drop(), and tumbling.
Referenced by Character::suffer().
from_nyctophobia()
void suffer::from_nyctophobia (Character & you) static
Definition at line 1520 of file suffer.cpp.
 {
     const float nyctophobia_threshold = LIGHT_AMBIENT_LIT - 3.0f;
     const bool in_darkness = get_map().ambient_light_at( you.pos() ) < nyctophobia_threshold;
     if( in_darkness ) {
         if( one_in( 80 ) && !you.has_effect( effect_shakes ) ) {
             you.add_msg_if_player( m_bad,
                                    _( "Your fear of the dark is so intense that your hands start shaking uncontrollably." ) );
             you.add_effect( effect_shakes, rng( 1_minutes, 3_minutes ) );
             return;
         }
         if( one_in( 80 ) ) {
             you.add_msg_if_player( m_bad,
                                    _( "Your fear of the dark is so intense that you start breathing rapidly, and you feel like your heart is ready to jump out of your chest." ) );
             you.mod_stamina( -500 * rng( 1, 3 ) );
             return;
         }
         if( one_turn_in( 5_minutes ) ) {
             you.add_msg_if_player( m_bad, _( "You feel a twinge of panic as darkness engulfs you." ) );
         }
     }
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), map::ambient_light_at(), effect_shakes, get_map(), Creature::has_effect(), LIGHT_AMBIENT_LIT, m_bad, Character::mod_stamina(), one_in(), one_turn_in(), Creature::pos(), and rng().
Referenced by while_awake().
from_other_mutations()
void suffer::from_other_mutations (Character & you) static
Definition at line 993 of file suffer.cpp.
 {
     map &here = get_map();
     const tripoint position = you.pos();
     if( you.has_trait( trait_SHARKTEETH ) && one_turn_in( 24_hours ) ) {
         you.add_msg_if_player( m_neutral, _( "You shed a tooth!" ) );
         here.spawn_item( position, "bone", 1 );
     }
     if( you.has_trait( trait_WINGS_INSECT_active ) ) {
         //~Sound of buzzing Insect Wings
         sounds::sound( position, 10, sounds::sound_t::movement, _( "BZZZZZ" ), false, "misc",
                        "insect_wings" );
     }
     if( you.has_trait( trait_SORES ) ) {
         for( const bodypart_id &bp : you.get_all_body_parts() ) {
             if( bp == bodypart_id( "head" ) ) {
                 continue;
             }
             int sores_pain = 5 + 0.4 * std::abs( you.encumb( bp ) );
             if( you.get_pain() < sores_pain ) {
                 you.set_pain( sores_pain );
             }
         }
     }
     //Web Weavers...weave web
     if( you.has_active_mutation( trait_WEB_WEAVER ) && !you.in_vehicle ) {
         // this adds intensity to if its not already there.
         here.add_field( position, fd_web, 1 );
     }
     if( you.has_active_mutation( trait_SNAIL_TRAIL ) && !you.in_vehicle ) {
         here.add_field( position, fd_sludge, 1 );
     }
     // Blind/Deaf for brief periods about once an hour,
     // and visuals about once every 30 min.
     if( you.has_trait( trait_PER_SLIME ) ) {
         if( one_turn_in( 1_hours ) && !you.has_effect( effect_deaf ) ) {
             you.add_msg_if_player( m_bad, _( "Suddenly, you can't hear anything!" ) );
             you.add_effect( effect_deaf, rng( 20_minutes, 60_minutes ) );
         }
         if( one_turn_in( 1_hours ) && !you.has_effect( effect_blind ) ) {
             you.add_msg_if_player( m_bad, _( "Suddenly, your eyes stop working!" ) );
             you.add_effect( effect_blind, rng( 2_minutes, 6_minutes ) );
         }
         // Yes, you can be blind and hallucinate at the same time.
         // Your post-human biology is truly remarkable.
         if( one_turn_in( 30_minutes ) && !you.has_effect( effect_visuals ) ) {
             you.add_msg_if_player( m_bad, _( "Your visual centers must be acting up" ) );
             you.add_effect( effect_visuals, rng( 36_minutes, 72_minutes ) );
         }
     }
     if( you.has_trait( trait_WEB_SPINNER ) && !you.in_vehicle && one_in( 3 ) ) {
         // this adds intensity to if its not already there.
         here.add_field( position, fd_web, 1 );
     }
     if( you.has_trait( trait_MUCUS_SECRETION ) && !you.in_vehicle && one_in( 2033 ) ) {
         here.add_field( position, fd_sludge, 1 );
     }
     bool should_mutate = you.has_trait( trait_UNSTABLE ) && !you.has_trait( trait_CHAOTIC_BAD ) &&
                          one_turn_in( 48_hours );
     should_mutate |= ( you.has_trait( trait_CHAOTIC ) || you.has_trait( trait_CHAOTIC_BAD ) ) &&
                      one_turn_in( 12_hours );
     if( should_mutate ) {
         you.mutate();
     }
     const bool needs_fire = !you.has_morale( MORALE_PYROMANIA_NEARFIRE ) &&
                             !you.has_morale( MORALE_PYROMANIA_STARTFIRE );
     if( you.has_trait( trait_PYROMANIA ) && needs_fire && !you.in_sleep_state() &&
         calendar::once_every( 2_hours ) ) {
         you.add_morale( MORALE_PYROMANIA_NOFIRE, -1, -30, 24_hours, 24_hours, true );
         if( calendar::once_every( 4_hours ) ) {
             const translation smokin_hot_fiyah =
                 SNIPPET.random_from_category( "pyromania_withdrawal" ).value_or( translation() );
             you.add_msg_if_player( m_bad, "%s", smokin_hot_fiyah );
         }
     }
     if( you.has_trait( trait_KILLER ) && !you.has_morale( MORALE_KILLER_HAS_KILLED ) &&
         calendar::once_every( 2_hours ) ) {
         you.add_morale( MORALE_KILLER_NEED_TO_KILL, -1, -30, 24_hours, 24_hours );
         if( calendar::once_every( 4_hours ) ) {
             const translation snip = SNIPPET.random_from_category( "killer_withdrawal" ).value_or(
                                          translation() );
             you.add_msg_if_player( m_bad, "%s", snip );
         }
     }
 }
References _, abs(), Creature::add_effect(), map::add_field(), Character::add_morale(), Character::add_msg_if_player(), bp, effect_blind, effect_deaf, effect_visuals, Character::encumb(), fd_sludge, fd_web, Creature::get_all_body_parts(), get_map(), Creature::get_pain(), Character::has_active_mutation(), Creature::has_effect(), Character::has_morale(), Character::has_trait(), Character::in_sleep_state(), Character::in_vehicle, m_bad, m_neutral, MORALE_KILLER_HAS_KILLED, MORALE_KILLER_NEED_TO_KILL, MORALE_PYROMANIA_NEARFIRE, MORALE_PYROMANIA_NOFIRE, MORALE_PYROMANIA_STARTFIRE, sounds::movement, Character::mutate(), calendar::once_every(), one_in(), one_turn_in(), Creature::pos(), snippet_library::random_from_category(), rng(), Character::set_pain(), SNIPPET, sounds::sound(), map::spawn_item(), trait_CHAOTIC, trait_CHAOTIC_BAD, trait_KILLER, trait_MUCUS_SECRETION, trait_PER_SLIME, trait_PYROMANIA, trait_SHARKTEETH, trait_SNAIL_TRAIL, trait_SORES, trait_UNSTABLE, trait_WEB_SPINNER, trait_WEB_WEAVER, and trait_WINGS_INSECT_active.
Referenced by Character::suffer().
from_radiation()
void suffer::from_radiation (Character & you) static
Definition at line 1089 of file suffer.cpp.
 {
     map &here = get_map();
     // get radioactive leak level of your inventory
     float item_radiation = you.get_leak_level();
     const int map_radiation = here.get_radiation( you.pos() );
     float rads = map_radiation / 100.0f + item_radiation / 10.0f;
     int rad_mut = 0;
     if( you.has_trait( trait_RADIOACTIVE3 ) ) {
         rad_mut = 3;
     } else if( you.has_trait( trait_RADIOACTIVE2 ) ) {
         rad_mut = 2;
     } else if( you.has_trait( trait_RADIOACTIVE1 ) ) {
         rad_mut = 1;
     }
     // Spread less radiation when sleeping (slower metabolism etc.)
     // Otherwise it can quickly get to the point where you simply can't sleep at all
     const bool rad_mut_proc = rad_mut > 0 && x_in_y( rad_mut, to_turns<int>( you.in_sleep_state() ?
                               3_hours : 30_minutes ) );
     bool has_helmet = false;
     const bool power_armored = you.is_wearing_power_armor( &has_helmet );
     const bool rad_resist = power_armored || you.worn_with_flag( flag_RAD_RESIST );
     if( rad_mut > 0 ) {
         const bool kept_in = you.is_rad_immune() || ( rad_resist && !one_in( 4 ) );
         if( kept_in ) {
             // As if standing on a map tile with radiation level equal to rad_mut
             rads += rad_mut / 100.0f;
         }
         if( rad_mut_proc && !kept_in ) {
             // Irradiate a random nearby point
             // If you can't, irradiate the player instead
             tripoint rad_point = you.pos() + point( rng( -3, 3 ), rng( -3, 3 ) );
             // TODO: Radioactive vehicles?
             if( here.get_radiation( rad_point ) < rad_mut ) {
                 here.adjust_radiation( rad_point, 1 );
             } else {
                 rads += rad_mut;
             }
         }
     }
     // Used to control vomiting from radiation to make it not-annoying
     bool radiation_increasing = you.irradiate( rads );
     if( radiation_increasing && calendar::once_every( 3_minutes ) ) {
         if( you.has_bionic( bio_geiger ) ) {
             you.add_msg_if_player( m_warning,
                                    _( "You feel an anomalous sensation coming from "
                                       "your radiation sensors." ) );
         } else if( you.has_active_mutation( trait_RADIOPHILE ) ) {
             you.add_msg_if_player( m_warning,
                                    _( "Your flesh tingles with an air of danger, "
                                       "yet it is strangely pleasurable." ) );
         }
     }
     if( calendar::once_every( 15_minutes ) ) {
         if( you.get_rad() < 0 ) {
             you.set_rad( 0 );
         } else if( you.get_rad() > 2000 ) {
             you.set_rad( 2000 );
         }
         // Linear increase in chance to mutate with irriadation level.
         // 100 rads = 1 / 10000
         // 110 rads = 10 / 10000 = 1 / 1000
         // 200 rads = 100 / 10000 = 1 / 100
         // 1000 rads = 900 / 10000 = 9 / 100 = 10% !!!
         // 2000 rads = 2000 / 10000 = 1 / 5 = 20% !!!
         if( get_option<bool>( "RAD_MUTATION" ) && rng( 100, 10000 ) < you.get_rad() ) {
             you.mutate();
         }
         if( you.get_rad() > 50 && rng( 1, 3000 ) < you.get_rad() &&
             ( you.stomach.contains() > 0_ml || radiation_increasing || !you.in_sleep_state() ) ) {
             you.vomit();
             you.mod_rad( -1 );
         }
     }
     const bool radiogenic = you.has_trait( trait_RADIOGENIC );
     if( radiogenic && calendar::once_every( 30_minutes ) && you.get_rad() > 0 ) {
         // At 200 irradiation, twice as fast as REGEN
         if( x_in_y( you.get_rad(), 200 ) ) {
             you.healall( 1 );
             if( rad_mut == 0 ) {
                 // Don't heal radiation if we're generating it naturally
                 // That would counter the main downside of radioactivity
                 you.mod_rad( -5 );
             }
         }
     }
     if( calendar::once_every( 1_days ) ) {
         if( !radiogenic && you.get_rad() > 0 ) {
             you.mod_daily_health( -you.get_rad(), -200 );
         }
     }
     if( you.get_rad() > 200 && calendar::once_every( 10_minutes ) && x_in_y( you.get_rad(), 1000 ) ) {
         you.hurtall( 1, nullptr );
         you.mod_rad( -5 );
     }
     while( you.slow_rad >= 1000 ) {
         you.mod_rad( 1 );
         you.slow_rad -= 1000;
     }
 }
References _, Character::add_msg_if_player(), map::adjust_radiation(), bio_geiger, stomach_contents::contains(), flag_RAD_RESIST, Character::get_leak_level(), get_map(), Character::get_rad(), map::get_radiation(), Character::has_active_mutation(), Character::has_bionic(), Character::has_trait(), Character::healall(), Character::hurtall(), Character::in_sleep_state(), Character::irradiate(), Character::is_rad_immune(), Character::is_wearing_power_armor(), m_warning, Character::mod_daily_health(), Character::mod_rad(), Character::mutate(), calendar::once_every(), one_in(), Creature::pos(), rng(), Character::set_rad(), Character::slow_rad, Character::stomach, trait_RADIOACTIVE1, trait_RADIOACTIVE2, trait_RADIOACTIVE3, trait_RADIOGENIC, trait_RADIOPHILE, Character::vomit(), Character::worn_with_flag(), and x_in_y().
Referenced by Character::suffer().
from_stimulants()
void suffer::from_stimulants (Character & you, int current_stim) static
Definition at line 1263 of file suffer.cpp.
 {
     // Stim +250 kills
     if( current_stim > 210 ) {
         if( one_turn_in( 2_minutes ) && !you.is_on_ground() ) {
             you.add_msg_if_player( m_bad, _( "Your muscles spasm!" ) );
             if( !you.is_on_ground() ) {
                 you.add_msg_if_player( m_bad, _( "You fall to the ground!" ) );
                 you.add_effect( effect_downed, rng( 6_turns, 20_turns ) );
             }
         }
     }
     if( current_stim > 170 ) {
         if( !you.has_effect( effect_winded ) && calendar::once_every( 10_minutes ) ) {
             you.add_msg_if_player( m_bad, _( "You feel short of breath." ) );
             you.add_effect( effect_winded, 10_minutes + 1_turns );
         }
     }
     if( current_stim > 110 ) {
         if( !you.has_effect( effect_shakes ) && calendar::once_every( 10_minutes ) ) {
             you.add_msg_if_player( _( "You shake uncontrollably." ) );
             you.add_effect( effect_shakes, 15_minutes + 1_turns );
         }
     }
     if( current_stim > 75 ) {
         if( !one_turn_in( 2_minutes ) && !you.has_effect( effect_nausea ) ) {
             you.add_msg_if_player( _( "You feel nauseous" ) );
             you.add_effect( effect_nausea, 5_minutes );
         }
     }
     //stim -200 or painkillers 240 kills
     if( current_stim < -160 || you.get_painkiller() > 200 ) {
         if( one_turn_in( 3_minutes ) && !you.in_sleep_state() ) {
             you.add_msg_if_player( m_bad, _( "You black out!" ) );
             const time_duration dur = rng( 30_minutes, 60_minutes );
             if( !you.is_on_ground() ) {
                 you.add_effect( effect_downed, dur );
             }
             you.add_effect( effect_blind, dur );
             you.fall_asleep( dur );
         }
     }
     if( current_stim < -120 || you.get_painkiller() > 160 ) {
         if( !you.has_effect( effect_winded ) && calendar::once_every( 10_minutes ) ) {
             you.add_msg_if_player( m_bad, _( "Your breathing slows down." ) );
             you.add_effect( effect_winded, 10_minutes + 1_turns );
         }
     }
     if( current_stim < -85 || you.get_painkiller() > 145 ) {
         if( one_turn_in( 15_seconds ) && !you.has_effect( effect_sleep ) ) {
             you.add_msg_if_player( m_bad, _( "You feel dizzy for a moment." ) );
             you.mod_moves( -rng( 10, 30 ) );
             if( one_in( 3 ) && !you.is_on_ground() ) {
                 you.add_msg_if_player( m_bad, _( "You stumble and fall over!" ) );
                 you.add_effect( effect_downed, rng( 3_turns, 10_turns ) );
             }
         }
     }
     if( current_stim < -60 || you.get_painkiller() > 130 ) {
         if( calendar::once_every( 10_minutes ) ) {
             you.add_msg_if_player( m_warning, _( "You feel tired" ) );
             you.mod_sleepiness( rng( 1, 2 ) );
         }
     }
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), dur, effect_blind, effect_downed, effect_nausea, effect_shakes, effect_sleep, effect_winded, Character::fall_asleep(), Character::get_painkiller(), Creature::has_effect(), Character::in_sleep_state(), Character::is_on_ground(), m_bad, m_warning, Creature::mod_moves(), Character::mod_sleepiness(), calendar::once_every(), one_in(), one_turn_in(), and rng().
Referenced by Character::suffer().
from_sunburn()
void suffer::from_sunburn (Character & you, bool severe) static
Definition at line 772 of file suffer.cpp.
 {
     // Sunburn effects and albinism/datura occur about once per minute
     if( !one_turn_in( 1_minutes ) ) {
         return;
     }
     // TODO: Could factor bodypart_exposure out of Character too
     std::map<bodypart_id, float> bp_exposure = you.bodypart_exposure();
     enum Sunburn { None, Focus_Loss, Pain, Damage };
     auto heavy_sunburn = [severe, &you]( bodypart_id bp ) {
         if( severe ) {
             // Because hands and feet share an HP pool with arms and legs, and the mouth shares
             // an HP pool with the head, those parts take an unfair share of damage in relation
             // to the torso, which only has one part.  Increase torso damage to balance this.
             if( bp == bodypart_id( "torso" ) ) {
                 you.apply_damage( nullptr, bp, 2 );
             } else {
                 you.apply_damage( nullptr, bp, 1 );
             }
             return Damage;
         } else {
             you.mod_pain( 1 );
             return Pain;
         }
     };
     auto medium_sunburn = [severe, &you] {
         if( severe )
         {
             you.mod_pain( 1 );
             return Pain;
         } else
         {
             you.mod_focus( -1 );
             return Focus_Loss;
         }
     };
     auto light_sunburn = [severe, &you] {
         if( severe )
         {
             you.mod_focus( -1 );
             return Focus_Loss;
         } else
         {
             return None;
         }
     };
     // Track body parts above the threshold
     std::map<bodypart_id, Sunburn> affected_bodyparts;
     for( auto &bp_exp : bp_exposure ) {
         bodypart_id bp = bp_exp.first;
         float exposure = bp_exp.second;
         if( bp == bodypart_id( "eyes" ) ) {
             // Sunglasses can keep the sun off the eyes.
             if( you.has_flag( json_flag_GLARE_RESIST )
                 || you.worn_with_flag( flag_SUN_GLASSES )
                 || you.worn_with_flag( flag_BLIND ) ) {
                 continue;
             }
             // If no UV-/glare-protection gear is worn the eyes should be treated as unprotected
             exposure = 1.0;
         } else if( ( you.get_wielded_item() && you.get_wielded_item()->has_flag( flag_RAIN_PROTECT ) )
                    || ( ( bp == body_part_hand_l || bp == body_part_hand_r )
                         && you.worn_with_flag( flag_POCKETS )
                         && you.can_use_pockets() )
                    || ( bp == body_part_head
                         && you.worn_with_flag( flag_HOOD )
                         && you.can_use_hood() )
                    || ( bp == body_part_mouth
                         && you.worn_with_flag( flag_COLLAR )
                         && you.can_use_collar() ) ) {
             // Eyes suffer even in the presence of the checks in this branch!
             // Umbrellas can keep the sun off all bodyparts
             // Pockets can keep the sun off your hands if you don't wield a too large item
             // Hoods can keep the sun off your unencumbered head
             // Collars can keep the sun off your unencumbered mouth
             continue;
         }
         float heavy_cumul_chance = heavy_eff_chance( exposure );
         float medium_cumul_chance = heavy_cumul_chance + medium_eff_chance( exposure );
         float light_cumul_chance = medium_cumul_chance + light_eff_chance( exposure );
         float roll = rng_float( 0.0, 1.0 );
         Sunburn eff;
         if( roll < heavy_cumul_chance ) {
             eff = heavy_sunburn( bp );
         } else if( roll < medium_cumul_chance ) {
             eff = medium_sunburn( );
         } else if( roll < light_cumul_chance ) {
             eff = light_sunburn( );
         } else {
             // Do nothing. Assert that exposure is lower than 0.05 as above that point at least light_eff should always happen
             if( exposure > 0.05 ) {
                 debugmsg( "No sunburn effect was applied although the bodypart %s is sufficiently exposed at %f exposure",
                           body_part_name( bp ), exposure );
             };
             eff = None;
         }
         affected_bodyparts.emplace( bp, eff );
     }
     std::vector<std::string> affected_part_names;
     std::unordered_set<bodypart_id> excluded_other_parts;
     if( affected_bodyparts.empty() ) {
         return;
     }
     Sunburn worst_effect = None;
     bool contains_eyes = false;
     for( const std::pair<const bodypart_id, Sunburn> &exp_bp : affected_bodyparts ) {
         const bodypart_id &bp = exp_bp.first;
         const Sunburn effect = exp_bp.second;
         if( excluded_other_parts.count( bp ) || effect < worst_effect ) {
             continue;
         }
         if( effect > worst_effect ) {
             worst_effect = effect;
             contains_eyes = false;
             excluded_other_parts.clear();
             affected_part_names.clear();
         }
         const bodypart_id &opposite_bp = bp->opposite_part;
         // If these are different, we have a left/right part like a leg or arm.
         // If same, it's a central body part with no opposite, like head or torso.
         // Used to generate a simpler message when both arms or both legs are affected.
         int count_limbs = 1;
         if( bp == bodypart_id( "eyes" ) ) {
             contains_eyes = true;
         }
         if( bp != opposite_bp ) {
             const auto found = affected_bodyparts.find( opposite_bp );
             // Is opposite part exposed to the same level?
             // If it has a lower exposure, we don't include it in the message.
             // If it has a higher exposure we can immediately skip as this bodypart won't be included in the message.
             if( found != affected_bodyparts.end() ) {
                 if( found->second > effect ) {
                     continue;
                 } else if( found->second == effect ) {
                     ++count_limbs;
                 }
                 excluded_other_parts.insert( opposite_bp );
             }
         }
         // Get singular or plural body part name; append "and other body parts" if appropriate
         std::string bp_name = body_part_name( bp, count_limbs );
         affected_part_names.push_back( bp_name );
     }
     const std::string all_parts_list = enumerate_as_string( affected_part_names );
     const int plurality = affected_part_names.size() + contains_eyes;
     auto warn_and_wake_up = [ &you, &all_parts_list]
     ( const char *message, game_message_type type ) {
         you.add_msg_if_player( type, message, all_parts_list );
         // Wake up from skin irritation/burning
         if( you.has_effect( effect_sleep ) ) {
             you.wake_up();
         }
     };
     switch( worst_effect ) {
         case Damage:
             //~ %s is a list of body parts.  The plurality integer is the total
             //~ number of body parts (eyes count as 2 body parts)
             //~ This message indicates damage to bodyparts through sunshine
             warn_and_wake_up( n_gettext( "Your %s is bathed in sunlight.  It feels like it is burning up.",
                                          "Your %s are bathed in sunlight.  They feel like they are burning up.",
                                          plurality ),
                               m_bad );
             break;
         case Pain:
             //~ %s is a list of body parts.  The plurality integer is the total
             //~ number of body parts (eyes count as 2 body parts)
             //~ This message indicates pain through sunshine
             warn_and_wake_up( n_gettext( "The sunlight burns on your %s.",
                                          "The sunlight burns on your %s.",
                                          plurality ),
                               m_bad );
             break;
         case Focus_Loss:
             //~ %s is a list of body parts.  The plurality integer is the total
             //~ number of body parts (eyes count as 2 body parts)
             //~ This message indicates focus loss through sunshine
             warn_and_wake_up( n_gettext( "The sunlight on your %s irritates you.",
                                          "The sunlight on your %s irritates you.",
                                          plurality ),
                               m_bad );
             break;
         case None:
             break;
     }
 }
References Character::add_msg_if_player(), Character::apply_damage(), body_part_hand_l, body_part_hand_r, body_part_head, body_part_mouth, body_part_name(), Character::bodypart_exposure(), bp, Character::can_use_collar(), Character::can_use_hood(), Character::can_use_pockets(), debugmsg, effect_sleep, enumerate_as_string(), flag_BLIND, flag_COLLAR, flag_HOOD, flag_POCKETS, flag_RAIN_PROTECT, flag_SUN_GLASSES, Character::get_wielded_item(), Creature::has_effect(), item::has_flag(), Character::has_flag(), heavy_eff_chance(), json_flag_GLARE_RESIST, light_eff_chance(), m_bad, medium_eff_chance(), mapgen_defer::message, Character::mod_focus(), Character::mod_pain(), n_gettext, one_turn_in(), body_part_type::opposite_part, rng_float(), Character::wake_up(), and Character::worn_with_flag().
Referenced by in_sunlight().
from_tourniquet()
void suffer::from_tourniquet (Character & you) static
Definition at line 1504 of file suffer.cpp.
 {
     // shortcut for the most common scenario.
     if( !you.worn_with_flag( flag_TOURNIQUET ) ) {
         return;
     }
     for( const bodypart_id &bp : you.get_all_body_parts( get_body_part_flags::only_main ) ) {
         if( you.worn_with_flag( flag_TOURNIQUET, bp ) && one_turn_in( 30_seconds ) ) {
             you.mod_pain( 1 );
             you.apply_damage( nullptr, bp, 1, true );
             you.add_msg_player_or_npc( m_bad, _( "Your tourniquet hurts you." ),
                                        _( "<npcname> is hurting from the tourniquet." ) );
         }
     }
 }
References _, Character::add_msg_player_or_npc(), Character::apply_damage(), bp, flag_TOURNIQUET, Creature::get_all_body_parts(), m_bad, Character::mod_pain(), one_turn_in(), only_main, and Character::worn_with_flag().
Referenced by Character::suffer().
in_sunlight()
void suffer::in_sunlight (Character & you) static
Definition at line 650 of file suffer.cpp.
 {
     const tripoint position = you.pos();
     if( !g->is_in_sunlight( position ) ) {
         return;
     }
     const bool leafy = you.has_trait( trait_LEAVES ) ||
                        you.has_trait( trait_LEAVES2 ) ||
                        you.has_trait( trait_LEAVES3 );
     int sunlight_nutrition = 0;
     if( leafy ) {
         const bool leafier = you.has_trait( trait_LEAVES2 );
         const bool leafiest = you.has_trait( trait_LEAVES3 );
         const double sleeve_factor = you.armwear_factor();
         const bool has_hat = you.wearing_something_on( bodypart_id( "head" ) );
         const float weather_factor = std::min( incident_sun_irradiance( get_weather().weather_id,
                                                calendar::turn ) / irradiance::moderate, 1.f );
         const int player_local_temp = units::to_fahrenheit( get_weather().get_temperature( position ) );
         const int flux = ( player_local_temp - 65 ) / 2;
         if( !has_hat ) {
             sunlight_nutrition += ( 100 + flux ) * weather_factor;
         }
         if( leafier || leafiest ) {
             const int rate = ( 100 * sleeve_factor + flux ) * 2;
             sunlight_nutrition += rate * ( leafiest ? 2 : 1 ) * weather_factor;
         }
         if( x_in_y( sunlight_nutrition, 18000 ) ) {
             you.vitamin_mod( vitamin_vitC, 1 );
         }
     }
     if( you.has_flag( json_flag_SUNBURN ) ) {
         suffer::from_sunburn( you, true );
     }
     // Albinism and datura have the same effects and do not stack with each other or sunburn.
     if( !you.has_flag( json_flag_SUNBURN ) &&
         ( you.has_flag( json_flag_ALBINO ) || you.has_effect( effect_datura ) ) ) {
         suffer::from_sunburn( you, false );
     }
     if( ( you.has_trait( trait_TROGLO ) || you.has_trait( trait_TROGLO2 ) ) &&
         incident_sun_irradiance( get_weather().weather_id, calendar::turn ) > irradiance::moderate ) {
         you.mod_str_bonus( -1 );
         you.mod_dex_bonus( -1 );
         you.add_miss_reason( _( "The sunlight distracts you." ), 1 );
         you.mod_int_bonus( -1 );
         you.mod_per_bonus( -1 );
     }
     if( you.has_trait( trait_TROGLO2 ) &&
         incident_sun_irradiance( get_weather().weather_id, calendar::turn ) > irradiance::low ) {
         you.mod_str_bonus( -1 );
         you.mod_dex_bonus( -1 );
         you.add_miss_reason( _( "The sunlight distracts you." ), 1 );
         you.mod_int_bonus( -1 );
         you.mod_per_bonus( -1 );
     }
     if( you.has_flag( json_flag_DAYFEAR ) ) {
         you.mod_str_bonus( -2 );
         you.mod_dex_bonus( -2 );
         you.add_miss_reason( _( "You fear the sunlight!" ), 2 );
         you.mod_int_bonus( -2 );
         you.mod_per_bonus( -2 );
     }
     if( you.has_trait( trait_TROGLO3 ) ) {
         you.mod_str_bonus( -4 );
         you.mod_dex_bonus( -4 );
         you.add_miss_reason( _( "You can't stand the sunlight!" ), 4 );
         you.mod_int_bonus( -4 );
         you.mod_per_bonus( -4 );
     }
 }
References _, Character::add_miss_reason(), Character::armwear_factor(), effect_datura, from_sunburn(), g, get_weather(), Creature::has_effect(), Character::has_flag(), Character::has_trait(), incident_sun_irradiance(), json_flag_ALBINO, json_flag_DAYFEAR, json_flag_SUNBURN, irradiance::low, min(), Character::mod_dex_bonus(), Character::mod_int_bonus(), Character::mod_per_bonus(), Character::mod_str_bonus(), irradiance::moderate, Creature::pos(), units::to_fahrenheit(), trait_LEAVES, trait_LEAVES2, trait_LEAVES3, trait_TROGLO, trait_TROGLO2, trait_TROGLO3, calendar::turn, Character::vitamin_mod(), vitamin_vitC, Character::wearing_something_on(), and x_in_y().
Referenced by Character::suffer().
mutation_power()
void suffer::mutation_power (Character & you, const trait_id & mut_id) static
Definition at line 232 of file suffer.cpp.
 {
     if( you.get_cost_timer( mut_id ) > 0_turns ) {
         // Not ready to consume cost yet, the timer ticks on
         you.mod_cost_timer( mut_id, -1_turns );
     } else {
         // Ready to consume cost: pay the power cost and reset timer
         if( mut_id->cooldown > 0_turns ) {
             you.set_cost_timer( mut_id, mut_id->cooldown - 1_turns );
         }
         if( mut_id->hunger ) {
             if( you.get_bmi_fat() < character_weight_category::underweight ) {
                 you.add_msg_if_player( m_warning,
                                        _( "You're too malnourished to keep your %s going." ),
                                        you.mutation_name( mut_id ) );
                 you.deactivate_mutation( mut_id );
             } else {
                 // does not directly modify hunger, but burns kcal
                 you.mod_stored_kcal( -mut_id->cost );
             }
         }
         if( mut_id->thirst ) {
             // Well into Dehydrated
             if( you.get_thirst() >= 260 ) {
                 you.add_msg_if_player( m_warning,
                                        _( "You're too dehydrated to keep your %s going." ),
                                        you.mutation_name( mut_id ) );
                 you.deactivate_mutation( mut_id );
             } else {
                 you.mod_thirst( mut_id->cost );
             }
         }
         if( mut_id->sleepiness ) {
             // Exhausted
             if( you.get_sleepiness() >= sleepiness_levels::EXHAUSTED ) {
                 you.add_msg_if_player( m_warning,
                                        _( "You're too exhausted to keep your %s going." ),
                                        you.mutation_name( mut_id ) );
                 you.deactivate_mutation( mut_id );
             } else {
                 you.mod_sleepiness( mut_id->cost );
             }
         }
         // if you haven't deactivated then run the EOC
         for( const effect_on_condition_id &eoc : mut_id->processed_eocs ) {
             dialogue d( get_talker_for( you ), nullptr );
             d.set_value( "npctalk_var_this", mut_id.str() );
             if( eoc->type == eoc_type::ACTIVATION ) {
                 eoc->activate( d );
             } else {
                 debugmsg( "Must use an activation eoc for a mutation process.  If you don't want the effect_on_condition to happen on its own (without the mutation being activated), remove the recurrence min and max.  Otherwise, create a non-recurring effect_on_condition for this mutation with its condition and effects, then have a recurring one queue it." );
             }
         }
     }
 }
References _, ACTIVATION, Character::add_msg_if_player(), mutation_branch::cooldown, mutation_branch::cost, Character::deactivate_mutation(), debugmsg, eoc, EXHAUSTED, Character::get_bmi_fat(), Character::get_cost_timer(), Character::get_sleepiness(), get_talker_for(), Character::get_thirst(), mutation_branch::hunger, m_warning, Character::mod_cost_timer(), Character::mod_sleepiness(), Character::mod_stored_kcal(), Character::mod_thirst(), Character::mutation_name(), mutation_branch::processed_eocs, Character::set_cost_timer(), dialogue::set_value(), mutation_branch::sleepiness, string_id< T >::str(), mutation_branch::thirst, and character_weight_category::underweight.
Referenced by Character::suffer().
water_damage()
void suffer::water_damage (Character & you) static
Definition at line 211 of file suffer.cpp.
 {
     for( const std::pair<const bodypart_str_id, bodypart> &elem : you.get_body() ) {
         const float wetness_percentage = elem.second.get_wetness_percentage();
         float dmg_float = you.enchantment_cache->modify_value( enchant_vals::mod::WEAKNESS_TO_WATER,
                           0 ) * wetness_percentage / 100;
         const int dmg = roll_remainder( dmg_float );
         if( dmg > 0 ) {
             you.apply_damage( nullptr, elem.first, dmg );
             you.add_msg_player_or_npc( m_bad, _( "Your %s is damaged by the water." ),
                                        _( "<npcname>'s %s is damaged by the water." ),
                                        body_part_name( elem.first ) );
         } else if( dmg < 0 && !elem.second.is_at_max_hp() ) {
             you.heal( elem.first, std::abs( dmg ) );
             you.add_msg_player_or_npc( m_good, _( "Your %s is healed by the water." ),
                                        _( "<npcname>'s %s is healed by the water." ),
                                        body_part_name( elem.first ) );
         }
     }
 }
References _, abs(), Character::add_msg_player_or_npc(), Character::apply_damage(), body_part_name(), Character::enchantment_cache, Creature::get_body(), Character::heal(), m_bad, m_good, roll_remainder(), and enchant_vals::WEAKNESS_TO_WATER.
Referenced by Character::suffer().
while_awake()
void suffer::while_awake (Character & you, int current_stim) static
Definition at line 402 of file suffer.cpp.
 {
     if( you.weight_carried() > 4 * you.weight_capacity() ) {
         if( you.has_effect( effect_downed ) ) {
             you.add_effect( effect_downed, 1_turns, false, 0, true );
         } else {
             you.add_effect( effect_downed, 2_turns, false, 0, true );
         }
     }
     if( you.has_flag( json_flag_NYCTOPHOBIA ) && !you.has_effect( effect_took_xanax ) ) {
         suffer::from_nyctophobia( you );
     }
     if( you.has_trait( trait_CHEMIMBALANCE ) ) {
         suffer::from_chemimbalance( you );
     }
     if( you.has_trait( trait_NARCOLEPTIC ) ) {
         if( one_turn_in( 8_hours ) ) {
             you.add_msg_if_player( m_bad,
                                    _( "You're suddenly overcome with the urge to sleep and you pass out." ) );
             you.fall_asleep( 20_minutes );
         }
     }
     int resonance = you.enchantment_cache->get_value_add( enchant_vals::mod::ARTIFACT_RESONANCE );
     if( resonance > 0 ) {
         suffer::from_artifact_resonance( you, resonance );
     }
     if( you.has_trait( trait_JITTERY ) && !you.has_effect( effect_shakes ) ) {
         if( current_stim > 50 && one_in( to_turns<int>( 30_minutes ) - ( current_stim * 6 ) ) ) {
             you.add_effect( effect_shakes, 30_minutes + 1_turns * current_stim );
         } else if( ( you.get_hunger() > 80 || you.get_kcal_percent() < 1.0f ) && you.get_hunger() > 0 &&
                    one_in( to_turns<int>( 50_minutes ) - ( you.get_hunger() * 6 ) ) ) {
             you.add_effect( effect_shakes, 40_minutes );
         }
     }
     if( you.has_trait( trait_MOODSWINGS ) && one_turn_in( 6_hours ) ) {
         if( rng( 1, 20 ) > 9 ) {
             // 55% chance
             you.add_morale( MORALE_MOODSWING, -20, -100 );
         } else {
             // 45% chance
             you.add_morale( MORALE_MOODSWING, 20, 100 );
         }
     }
     if( you.has_trait( trait_VOMITOUS ) && one_turn_in( 7_hours ) ) {
         you.vomit();
     }
     if( you.has_trait( trait_HAS_NEMESIS ) && one_turn_in( 2_minutes ) ) {
         you.signal_nemesis();
     }
     if( you.has_trait( trait_SHOUT1 ) && one_turn_in( 6_hours ) ) {
         you.shout();
     }
     if( you.has_trait( trait_SHOUT2 ) && one_turn_in( 4_hours ) ) {
         you.shout();
     }
     if( you.has_trait( trait_SHOUT3 ) && one_turn_in( 3_hours ) ) {
         you.shout();
     }
     if( you.has_trait( trait_M_SPORES ) && one_turn_in( 4_hours ) ) {
         you.spores();
     }
     if( you.has_trait( trait_M_BLOSSOMS ) && one_turn_in( 3_hours ) ) {
         you.blossoms();
     }
 }
References _, Creature::add_effect(), Character::add_morale(), Character::add_msg_if_player(), enchant_vals::ARTIFACT_RESONANCE, Character::blossoms(), effect_downed, effect_shakes, effect_took_xanax, Character::enchantment_cache, Character::fall_asleep(), from_artifact_resonance(), from_chemimbalance(), from_nyctophobia(), Character::get_hunger(), Character::get_kcal_percent(), Creature::has_effect(), Character::has_flag(), Character::has_trait(), json_flag_NYCTOPHOBIA, m_bad, MORALE_MOODSWING, one_in(), one_turn_in(), rng(), Character::shout(), Character::signal_nemesis(), Character::spores(), trait_CHEMIMBALANCE, trait_HAS_NEMESIS, trait_JITTERY, trait_M_BLOSSOMS, trait_M_SPORES, trait_MOODSWINGS, trait_NARCOLEPTIC, trait_SHOUT1, trait_SHOUT2, trait_SHOUT3, trait_VOMITOUS, Character::vomit(), Character::weight_capacity(), and Character::weight_carried().
Referenced by Character::suffer().
while_grabbed()
void suffer::while_grabbed (Character & you) static
Definition at line 316 of file suffer.cpp.
 {
     // If you're grabbed you can't move around effectively, triggering the check
     // TODO: crowd crush without grabs
     // Count the number of monsters who can shove you
     // TODO: expand the search area - use the same logic as GROUP_BASH?
     map &here = get_map();
     creature_tracker &creatures = get_creature_tracker();
     int crowd = 0;
     int impassable_ter = 0;
     for( auto&& dest : here.points_in_radius( you.pos(), 1, 0 ) ) { // *NOPAD*
         const monster *const mon = creatures.creature_at<monster>( dest );
         if( mon && mon->has_flag( mon_flag_GROUP_BASH ) ) {
             crowd++;
             add_msg_debug( debugmode::DF_CHARACTER, "Crowd pressure check: monster %s found, crowd size %d",
                            mon->name(), crowd );
         }
         if( here.impassable( dest ) ) {
             impassable_ter++;
         }
     }
     // if we aren't near two monsters with GROUP_BASH we won't suffocate
     if( crowd < 2 ) {
         return;
     }
     // Getting crushed against the wall counts as a monster
     if( impassable_ter ) {
         you.add_msg_if_player( m_bad, _( "You're crushed against the walls!" ) );
         crowd += impassable_ter;
     }
     if( crowd == 2 ) {
         // only a chance to lose breath at low grab chance, none with only a single zombie
         you.oxygen -= rng( 0, 1 );
     } else if( crowd <= 4 ) {
         you.oxygen -= 1;
     } else if( crowd <= 6 ) {
         you.oxygen -= rng( 1, 2 );
     } else if( crowd <= 8 ) {
         you.oxygen -= 2;
     }
     // a few warnings before starting to take damage
     if( you.oxygen <= 5 ) {
         you.add_msg_if_player( m_bad, _( "You're suffocating!" ) );
         if( uistate.distraction_oxygen && you.is_avatar() ) {
             g->cancel_activity_or_ignore_query( distraction_type::oxygen, _( "You're suffocating!" ) );
         }
         // your characters chest is being crushed and you are dying
         you.apply_damage( nullptr, you.get_random_body_part_of_type( body_part_type::type::torso ), rng( 1,
                           4 ) );
     } else if( you.oxygen <= 15 ) {
         you.add_msg_if_player( m_bad, _( "You can't breathe with all this weight!" ) );
     } else if( you.oxygen <= 25 ) {
         you.add_msg_if_player( m_bad, _( "You're having difficulty breathing!" ) );
     }
 }
References _, add_msg_debug, Character::add_msg_if_player(), Character::apply_damage(), creature_tracker::creature_at(), debugmode::DF_CHARACTER, uistatedata::distraction_oxygen, g, get_creature_tracker(), get_map(), Creature::get_random_body_part_of_type(), monster::has_flag(), map::impassable(), Creature::is_avatar(), m_bad, mon_flag_GROUP_BASH, monster::name(), Character::oxygen, oxygen, map::points_in_radius(), Creature::pos(), rng(), body_part_type::torso, and uistate.
Referenced by Character::suffer().
while_underwater()
void suffer::while_underwater (Character & you) static
Definition at line 289 of file suffer.cpp.
 {
     if( !you.has_flag( json_flag_GILLS ) ) {
         you.oxygen--;
     }
     if( you.oxygen < 12 && you.worn_with_flag( flag_REBREATHER ) ) {
         you.oxygen += 12;
     }
     if( you.oxygen <= 5 ) {
         if( you.has_bionic( bio_gills ) && you.get_power_level() >= bio_gills->power_trigger ) {
             you.oxygen += 5;
             you.mod_power_level( -bio_gills->power_trigger );
         } else {
             you.add_msg_if_player( m_bad, _( "You're drowning!" ) );
             you.apply_damage( nullptr, bodypart_id( "torso" ), rng( 1, 4 ) );
         }
     }
     if( you.has_trait( trait_FRESHWATEROSMOSIS ) &&
         !get_map().has_flag_ter( ter_furn_flag::TFLAG_SALT_WATER, you.pos() ) &&
         you.get_thirst() > -60 ) {
         you.mod_thirst( -1 );
     }
     if( you.has_trait( trait_UNDINE_ABSORB_WATER ) && you.get_thirst() > -60 ) {
         you.mod_thirst( -1 );
     }
 }
References _, Character::add_msg_if_player(), Character::apply_damage(), bio_gills, flag_REBREATHER, get_map(), Character::get_power_level(), Character::get_thirst(), Character::has_bionic(), Character::has_flag(), Character::has_trait(), json_flag_GILLS, m_bad, Character::mod_power_level(), Character::mod_thirst(), Character::oxygen, Creature::pos(), bionic_data::power_trigger, rng(), TFLAG_SALT_WATER, trait_FRESHWATEROSMOSIS, trait_UNDINE_ABSORB_WATER, and Character::worn_with_flag().
Referenced by Character::suffer().
without_sleep()
void suffer::without_sleep (Character & you, int sleep_deprivation) static
Definition at line 1420 of file suffer.cpp.
 {
     // redo as a snippet?
     if( sleep_deprivation >= SLEEP_DEPRIVATION_HARMLESS ) {
         if( one_turn_in( 50_minutes ) ) {
             switch( dice( 1, 4 ) ) {
                 default:
                 case 1:
                     you.add_msg_player_or_npc( m_warning, _( "You tiredly rub your eyes." ),
                                                _( "<npcname> tiredly rubs their eyes." ) );
                     break;
                 case 2:
                     you.add_msg_player_or_npc( m_warning, _( "You let out a small yawn." ),
                                                _( "<npcname> lets out a small yawn." ) );
                     break;
                 case 3:
                     you.add_msg_player_or_npc( m_warning, _( "You stretch your back." ),
                                                _( "<npcname> stretches their back." ) );
                     break;
                 case 4:
                     you.add_msg_player_or_npc( m_warning, _( "You feel mentally tired." ),
                                                _( "<npcname> lets out a huge yawn." ) );
                     break;
             }
         }
     }
     // Minor discomfort
     if( sleep_deprivation >= SLEEP_DEPRIVATION_MINOR ) {
         if( one_turn_in( 75_minutes ) ) {
             you.add_msg_if_player( m_warning, _( "You feel lightheaded for a moment." ) );
             you.mod_moves( -to_moves<int>( 1_seconds ) * 0.1 );
         }
         if( one_turn_in( 100_minutes ) ) {
             you.add_msg_if_player( m_warning, _( "Your muscles spasm uncomfortably." ) );
             you.mod_pain( 2 );
         }
         if( !you.has_effect( effect_visuals ) && one_turn_in( 150_minutes ) ) {
             you.add_msg_if_player( m_warning, _( "Your vision blurs a little." ) );
             you.add_effect( effect_visuals, rng( 1_minutes, 5_minutes ) );
         }
     }
     // Slight disability
     if( sleep_deprivation >= SLEEP_DEPRIVATION_SERIOUS ) {
         if( one_turn_in( 75_minutes ) ) {
             you.add_msg_if_player( m_bad, _( "Your mind lapses into unawareness briefly." ) );
             you.mod_moves( -to_moves<int>( 1_seconds ) * rng_float( 0.2, 0.8 ) );
         }
         if( one_turn_in( 125_minutes ) ) {
             you.add_msg_if_player( m_bad, _( "Your muscles ache in stressfully unpredictable ways." ) );
             you.mod_pain( rng( 2, 10 ) );
         }
         if( one_turn_in( 5_hours ) ) {
             you.add_msg_if_player( m_bad, _( "You have a distractingly painful headache." ) );
             you.mod_pain( rng( 10, 25 ) );
         }
     }
     // Major disability, high chance of passing out also relevant
     if( sleep_deprivation >= SLEEP_DEPRIVATION_MAJOR ) {
         if( !you.has_effect( effect_nausea ) && one_turn_in( 500_minutes ) ) {
             you.add_msg_if_player( m_bad, _( "You feel heartburn and an acid taste in your mouth." ) );
             you.mod_pain( 5 );
             you.add_effect( effect_nausea, rng( 5_minutes, 30_minutes ) );
         }
         if( one_turn_in( 5_hours ) ) {
             you.add_msg_if_player( m_bad, _( "Your mind is so tired that you feel you can't trust "
                                              "your eyes anymore." ) );
             you.add_effect( effect_hallu, rng( 5_minutes, 60_minutes ) );
         }
         if( !you.has_effect( effect_shakes ) && one_turn_in( 425_minutes ) ) {
             you.add_msg_if_player( m_bad, _( "Your muscles spasm uncontrollably, and you have "
                                              "trouble keeping your balance." ) );
             you.add_effect( effect_shakes, 15_minutes );
         } else if( you.has_effect( effect_shakes ) && one_turn_in( 75_seconds ) ) {
             you.mod_moves( -to_moves<int>( 1_seconds ) * 0.1 );
             you.add_msg_player_or_npc( m_warning, _( "Your shaking legs make you stumble." ),
                                        _( "<npcname> stumbles." ) );
             if( !you.is_on_ground() && one_in( 10 ) ) {
                 you.add_msg_player_or_npc( m_bad, _( "You fall over!" ), _( "<npcname> falls over!" ) );
                 you.add_effect( effect_downed, rng( 3_turns, 10_turns ) );
             }
         }
     }
 }
References _, Creature::add_effect(), Character::add_msg_if_player(), Character::add_msg_player_or_npc(), dice(), effect_downed, effect_hallu, effect_nausea, effect_shakes, effect_visuals, Creature::has_effect(), Character::is_on_ground(), m_bad, m_warning, Creature::mod_moves(), Character::mod_pain(), one_in(), one_turn_in(), rng(), rng_float(), SLEEP_DEPRIVATION_HARMLESS, SLEEP_DEPRIVATION_MAJOR, SLEEP_DEPRIVATION_MINOR, and SLEEP_DEPRIVATION_SERIOUS.
Referenced by Character::suffer().