Cataclysm DDA: anonymous_namespace{clzones.cpp} Namespace Reference
anonymous_namespace{clzones.cpp} Namespace Reference
Functions
void _rotate_zone (map &target_map, zone_data &zone, int turns)
cata_path _savefile (std::string const &suffix, bool player)
Variables
generic_factory< zone_type > zone_type_factory ("zone_type")
Function Documentation
_rotate_zone()
void anonymous_namespace{clzones.cpp}::_rotate_zone (map & target_map, zone_data & zone, int turns)
Definition at line 1481 of file clzones.cpp.
 {
     const point dim( SEEX * 2, SEEY * 2 );
     const tripoint a_start( 0, 0, target_map.get_abs_sub().z() );
     const tripoint a_end( SEEX * 2 - 1, SEEY * 2 - 1, a_start.z );
     const tripoint z_start = target_map.getlocal( zone.get_start_point() );
     const tripoint z_end = target_map.getlocal( zone.get_end_point() );
     const inclusive_cuboid<tripoint> boundary( a_start, a_end );
     if( boundary.contains( z_start ) && boundary.contains( z_end ) ) {
         // don't rotate centered squares
         if( z_start.x == z_start.y && z_end.x == z_end.y &&
             z_start.x + z_end.x == a_end.x ) {
             return;
         }
         point z_l_start = z_start.xy().rotate( turns, dim );
         point z_l_end = z_end.xy().rotate( turns, dim );
         tripoint_abs_ms first =
             target_map.getglobal( tripoint( std::min( z_l_start.x, z_l_end.x ),
                                             std::min( z_l_start.y, z_l_end.y ),
                                             z_start.z ) );
         tripoint_abs_ms second =
             target_map.getglobal( tripoint( std::max( z_l_start.x, z_l_end.x ),
                                             std::max( z_l_start.y, z_l_end.y ),
                                             z_end.z ) );
         zone.set_position( std::make_pair( first.raw(), second.raw() ), false );
     }
 }
References inclusive_cuboid< Tripoint, >::contains(), map::get_abs_sub(), zone_data::get_end_point(), zone_data::get_start_point(), map::getglobal(), map::getlocal(), max(), min(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), point::rotate(), second, SEEX, SEEY, zone_data::set_position(), point::x, tripoint::x, tripoint::xy(), point::y, tripoint::y, coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and tripoint::z.
Referenced by zone_manager::rotate_zones().
_savefile()
cata_path anonymous_namespace{clzones.cpp}::_savefile (std::string const & suffix, bool player)
Definition at line 1688 of file clzones.cpp.
 {
     if( player ) {
         return PATH_INFO::player_base_save_path_path() + string_format( ".zones%s.json", suffix );
     } else {
         return PATH_INFO::world_base_save_path_path() / string_format( "zones%s.json", suffix );
     }
 }
References player, PATH_INFO::player_base_save_path_path(), string_format(), and PATH_INFO::world_base_save_path_path().
Referenced by zone_manager::load_world_zones(), zone_manager::load_zones(), zone_manager::save_world_zones(), and zone_manager::save_zones().
Variable Documentation
zone_type_factory
generic_factory<zone_type> anonymous_namespace{clzones.cpp}::zone_type_factory("zone_type") ("zone_type")
Referenced by zone_type::get_all(), zone_type::load_zones(), and zone_type::reset().