Cataclysm DDA: temperatures Namespace Reference
temperatures Namespace Reference
Variables
constexpr units::temperature hot = units::from_fahrenheit(100)
constexpr units::temperature normal = units::from_fahrenheit(70)
constexpr units::temperature fridge = units::from_fahrenheit(37)
constexpr units::temperature cold = units::from_fahrenheit(40)
constexpr units::temperature freezer = units::from_celsius(-5)
constexpr units::temperature freezing = units::from_celsius(0)
constexpr units::temperature boiling = units::from_celsius(100)
Variable Documentation
boiling
constexpr units::temperature temperatures::boiling = units::from_celsius(100) constexpr
Definition at line 113 of file game_constants.h.
Referenced by item::set_temp_flags().
cold
constexpr units::temperature temperatures::cold = units::from_fahrenheit(40) constexpr
Definition at line 104 of file game_constants.h.
Referenced by activity_handlers::fill_liquid_do_turn(), iuse::multicooker_tick(), item::set_temp_flags(), and map::water_from().
freezer
constexpr units::temperature temperatures::freezer = units::from_celsius(-5) constexpr
Definition at line 107 of file game_constants.h.
Referenced by item::process_temperature_rot().
freezing
constexpr units::temperature temperatures::freezing = units::from_celsius(0) constexpr
Definition at line 110 of file game_constants.h.
Referenced by item::calc_hourly_rotpoints_at_temp().
fridge
constexpr units::temperature temperatures::fridge = units::from_fahrenheit(37) constexpr
Definition at line 101 of file game_constants.h.
Referenced by item::calc_rot(), and item::process_temperature_rot().
hot
constexpr units::temperature temperatures::hot = units::from_fahrenheit(100) constexpr
Definition at line 95 of file game_constants.h.
Referenced by item::set_temp_flags().
normal
constexpr units::temperature temperatures::normal = units::from_fahrenheit(70) constexpr
Definition at line 98 of file game_constants.h.
Referenced by player_morale::display(), item::process_temperature_rot(), and npc::vehicle_danger().