Cataclysm DDA: anonymous_namespace{harvest.cpp} Namespace Reference
anonymous_namespace{harvest.cpp} Namespace Reference
Variables
generic_factory< harvest_drop_type > harvest_drop_type_factory ("harvest_drop_type")
generic_factory< harvest_list > harvest_list_factory ("harvest_list")
Variable Documentation
harvest_drop_type_factory
generic_factory<harvest_drop_type> anonymous_namespace{harvest.cpp}::harvest_drop_type_factory("harvest_drop_type") ("harvest_drop_type")
Referenced by harvest_drop_type::get_all(), harvest_drop_type::load_harvest_drop_types(), and harvest_drop_type::reset().
harvest_list_factory
generic_factory<harvest_list> anonymous_namespace{harvest.cpp}::harvest_list_factory("harvest_list") ("harvest_list")
Referenced by harvest_list::get_all(), harvest_list::load_harvest_list(), and harvest_list::reset().