Cataclysm DDA: veh_utils Namespace Reference
veh_utils Namespace Reference
Functions
int calc_xp_gain (const vpart_info &vp, const skill_id &sk, const Character &who)
Calculates xp for interacting with given part.
vehicle_part * most_repairable_part (vehicle &veh, Character &who)
bool repair_part (vehicle &veh, vehicle_part &pt, Character &who)
Repairs a given part on a given vehicle by given character.
Function Documentation
calc_xp_gain()
int veh_utils::calc_xp_gain (const vpart_info & vp, const skill_id & sk, const Character & who)
Calculates xp for interacting with given part.
Definition at line 33 of file veh_utils.cpp.
 {
     const auto iter = vp.install_skills.find( sk );
     if( iter == vp.install_skills.end() ) {
         return 0;
     }
     // how many levels are we above the requirement?
     const int lvl = std::max( static_cast<int>( who.get_skill_level( sk ) ) - iter->second, 1 );
     // scale xp gain per hour according to relative level
     // 0-1: 60 xp /h
     //   2: 15 xp /h
     //   3:  6 xp /h
     //   4:  4 xp /h
     //   5:  3 xp /h
     //   6:  2 xp /h
     //  7+:  1 xp /h
     return std::ceil( to_moves<double>( vp.install_moves ) /
                       to_moves<int>( 1_minutes * std::pow( lvl, 2 ) ) );
 }
References ceil(), Character::get_skill_level(), vpart_info::install_moves, vpart_info::install_skills, and max().
Referenced by veh_interact::complete_vehicle(), and repair_part().
most_repairable_part()
vehicle_part * veh_utils::most_repairable_part (vehicle & veh, Character & who_arg)
Returns
a pointer to vehicle_part repairable by who_arg If no such part exists, returns a pointer to vehicle_part replaceable by whoarg If no such part exists, returns a nullptr.
Definition at line 55 of file veh_utils.cpp.
 {
     const inventory &inv = who.crafting_inventory();
     vehicle_part *vp_broken = nullptr;
     vehicle_part *vp_most_damaged = nullptr;
     int most_damage = 0;
     for( const vpart_reference &vpr : veh.get_all_parts() ) {
         vehicle_part &vp = vpr.part();
         const vpart_info &info = vpr.info();
         if( vp.removed
             || !vp.is_repairable()
             || veh.would_repair_prevent_flyable( vp, who ) ) {
             continue;
         }
         if( vp.is_broken() ) {
             if( who.meets_skill_requirements( info.install_skills ) &&
                 info.install_requirements().can_make_with_inventory( inv, is_crafting_component ) ) {
                 vp_broken = &vp;
             }
             continue;
         }
         if( who.meets_skill_requirements( info.repair_skills ) ) {
             const requirement_data reqs = info.repair_requirements() * vp.get_base().repairable_levels();
             if( reqs.can_make_with_inventory( inv, is_crafting_component ) ) {
                 const int repairable_damage = vp.get_base().damage();
                 if( repairable_damage > most_damage ) {
                     most_damage = repairable_damage;
                     vp_most_damaged = &vp;
                 }
             }
         }
     }
     return vp_most_damaged != nullptr ? vp_most_damaged : vp_broken;
 }
References requirement_data::can_make_with_inventory(), Character::crafting_inventory(), item::damage(), vehicle::get_all_parts(), vehicle_part::get_base(), vpart_info::install_requirements(), vpart_info::install_skills, vehicle_part::is_broken(), is_crafting_component(), vehicle_part::is_repairable(), Character::meets_skill_requirements(), vehicle_part::removed, vpart_info::repair_requirements(), vpart_info::repair_skills, item::repairable_levels(), and vehicle::would_repair_prevent_flyable().
Referenced by veh_interact::get_most_repairable_part().
repair_part()
bool veh_utils::repair_part (vehicle & veh, vehicle_part & pt, Character & who)
Repairs a given part on a given vehicle by given character.
Awards xp and consumes components.
Definition at line 92 of file veh_utils.cpp.
 {
     const vpart_info &vp = pt.info();
     const requirement_data reqs = pt.is_broken()
                                   ? vp.install_requirements()
                                   : vp.repair_requirements() * pt.get_base().repairable_levels();
     const inventory &inv = who.crafting_inventory( who.pos(), PICKUP_RANGE, !who.is_npc() );
     inventory map_inv;
     // allow NPCs to use welding rigs they can't see ( on the other side of a vehicle )
     // as they have the handicap of not being able to use the veh interaction menu
     // or able to drag a welding cart etc.
     map_inv.form_from_map( who.pos(), PICKUP_RANGE, &who, false, !who.is_npc() );
     if( !reqs.can_make_with_inventory( inv, is_crafting_component ) ) {
         who.add_msg_if_player( m_info, _( "You don't meet the requirements to repair the %s." ),
                                pt.name() );
         return false;
     }
     // consume items extracting any base item (which we will need if replacing broken part)
     item base( vp.base_item );
     for( const auto &e : reqs.get_components() ) {
         for( item &obj : who.consume_items( who.select_item_component( e, 1, map_inv ), 1,
                                             is_crafting_component ) ) {
             if( obj.typeId() == vp.base_item ) {
                 base = obj;
             }
         }
     }
     for( const auto &e : reqs.get_tools() ) {
         who.consume_tools( who.select_tool_component( e, 1, map_inv ), 1 );
     }
     who.invalidate_crafting_inventory();
     for( const auto &sk : pt.is_broken() ? vp.install_skills : vp.repair_skills ) {
         who.practice( sk.first, calc_xp_gain( vp, sk.first, who ) );
     }
     // If part is broken, it will be destroyed and references invalidated
     const std::string partname = pt.name( false );
     const std::string startdurability = pt.get_base().damage_indicator();
     if( pt.is_broken() ) {
         const vpart_id vpid = pt.info().id;
         const point mount = pt.mount;
         const units::angle direction = pt.direction;
         const std::string variant = pt.variant;
         get_map().spawn_items( who.pos(), pt.pieces_for_broken_part() );
         veh.remove_part( pt );
         const int partnum = veh.install_part( mount, vpid, std::move( base ) );
         if( partnum >= 0 ) {
             vehicle_part &vp = veh.part( partnum );
             vp.direction = direction;
             vp.variant = variant;
         }
         veh.part_removal_cleanup();
         who.add_msg_if_player( m_good, _( "You replace the %1$s's %2$s. (was %3$s)" ),
                                veh.name, partname, startdurability );
     } else {
         veh.set_hp( pt, pt.info().durability, true );
         who.add_msg_if_player( m_good, _( "You repair the %1$s's %2$s. (was %3$s)" ),
                                veh.name, partname, startdurability );
     }
     return true;
 }
References _, Character::add_msg_if_player(), vpart_info::base_item, calc_xp_gain(), requirement_data::can_make_with_inventory(), Character::consume_items(), Character::consume_tools(), Character::crafting_inventory(), item::damage_indicator(), vehicle_part::direction, vpart_info::durability, inventory::form_from_map(), vehicle_part::get_base(), requirement_data::get_components(), get_map(), requirement_data::get_tools(), vpart_info::id, vehicle_part::info(), vehicle::install_part(), vpart_info::install_requirements(), vpart_info::install_skills, Character::invalidate_crafting_inventory(), vehicle_part::is_broken(), is_crafting_component(), Character::is_npc(), m_good, m_info, vehicle_part::mount, vehicle_part::name(), vehicle::name, vehicle::part(), vehicle::part_removal_cleanup(), PICKUP_RANGE, vehicle_part::pieces_for_broken_part(), Creature::pos(), Character::practice(), vehicle::remove_part(), vpart_info::repair_requirements(), vpart_info::repair_skills, item::repairable_levels(), Character::select_item_component(), Character::select_tool_component(), vehicle::set_hp(), map::spawn_items(), and vehicle_part::variant.
Referenced by veh_interact::complete_vehicle().