Cataclysm DDA: anonymous_namespace{item.cpp} Namespace Reference
anonymous_namespace{item.cpp} Namespace Reference
Functions
const std::array< bodypart_str_id, 4 > & left_side_parts ()
const std::array< bodypart_str_id, 4 > & right_side_parts ()
bool _stacks_whiteblacklist (item const &lhs, item const &rhs)
bool _stacks_weapon_mods (item const &lhs, item const &rhs)
bool _stacks_location_hint (item const &lhs, item const &rhs)
bool _stacks_rot (item const &lhs, item const &rhs, bool combine_liquid)
bool _stacks_mushy_dirty (item const &lhs, item const &rhs)
bool _stacks_food_status (item const &lhs, item const &rhs)
bool _stacks_food_traits (item const &lhs, item const &rhs)
bool _stacks_food_irradiated (item const &lhs, item const &rhs)
bool _stacks_food_perishable (item const &lhs, item const &rhs, bool check_cat)
bool _stacks_clothing_size (item const &lhs, item const &rhs)
bool _stacks_wetness (item const &lhs, item const &rhs, bool precise)
bool _stacks_cbm_status (item const &lhs, item const &rhs)
bool _stacks_ethereal (item const &lhs, item const &rhs)
bool _stacks_ups (item const &lhs, item const &rhs)
bool _stacks_mods (item const &lhs, item const &rhs)
bool _stacks_variant (item const &lhs, item const &rhs)
bool _stacks_components (item const &lhs, item const &rhs, bool check_components)
template<class C >
void _aggregate (C &container, typename C::key_type const &key, item const *it, item::aggregate_t *&running_max, item::aggregate_t *&max_type, int depth, int maxdepth)
Function Documentation
_aggregate()
template<class C > void anonymous_namespace{item.cpp}::_aggregate (C & container, typename C::key_type const & key, item const * it, item::aggregate_t *& running_max, item::aggregate_t *& max_type, int depth, int maxdepth)
Definition at line 14994 of file item.cpp.
 {
     auto const [iter, emplaced] = container.emplace( key, it );
     if( emplaced && running_max == nullptr ) {
         running_max = &iter->second;
         max_type = running_max;
     } else if( !emplaced ) {
         iter->second.info.bits &=
             iter->second.header->stacks_with( *it, false, false, true, depth, maxdepth ).bits;
         ++iter->second.count;
         if constexpr( std::is_same_v<itype_id, typename C::key_type> ) {
             max_type = max_type->count < iter->second.count ? &iter->second : max_type;
         } else {
             iter->second.info.bits.reset( tname::segments::TYPE );
         }
         running_max = running_max->count < iter->second.count ? &iter->second : running_max;
     }
 }
References enum_bitset< E >::bits, stacking_info::bits, item::aggregate_t::count, item::aggregate_t::info, enum_bitset< E >::reset(), and tname::TYPE.
Referenced by item::aggregated_contents().
_stacks_cbm_status()
bool anonymous_namespace{item.cpp}::_stacks_cbm_status (item const & lhs, item const & rhs)
Definition at line 1568 of file item.cpp.
 {
     return ( !lhs.is_bionic() && !rhs.is_bionic() ) ||
            ( lhs.is_bionic() && rhs.is_bionic() &&
              lhs.has_flag( flag_NO_PACKED ) == rhs.has_flag( flag_NO_PACKED ) &&
              lhs.has_flag( flag_NO_STERILE ) == rhs.has_flag( flag_NO_STERILE ) );
 }
References flag_NO_PACKED, flag_NO_STERILE, item::has_flag(), and item::is_bionic().
Referenced by item::stacks_with().
_stacks_clothing_size()
bool anonymous_namespace{item.cpp}::_stacks_clothing_size (item const & lhs, item const & rhs)
Definition at line 1553 of file item.cpp.
 {
     avatar &u = get_avatar();
     item::sizing const u_sizing = lhs.get_sizing( u );
     return u_sizing == rhs.get_sizing( u ) &&
            ( u_sizing == item::sizing::ignore ||
              ( lhs.has_flag( flag_FIT ) == rhs.has_flag( flag_FIT ) &&
                lhs.has_flag( flag_VARSIZE ) == rhs.has_flag( flag_VARSIZE ) ) );
 }
References flag_FIT, flag_VARSIZE, get_avatar(), item::get_sizing(), item::has_flag(), item::ignore, and u.
Referenced by item::stacks_with().
_stacks_components()
bool anonymous_namespace{item.cpp}::_stacks_components (item const & lhs, item const & rhs, bool check_components)
Definition at line 1626 of file item.cpp.
 {
     return ( !check_components && !lhs.is_comestible() && !lhs.is_craft() ) ||
            // Only check if at least one item isn't using the default recipe or is comestible
            ( lhs.components.empty() && rhs.components.empty() ) ||
            ( lhs.get_uncraft_components() == rhs.get_uncraft_components() );
 }
References item::components, item_components::empty(), item::get_uncraft_components(), item::is_comestible(), and item::is_craft().
Referenced by item::stacks_with().
_stacks_ethereal()
bool anonymous_namespace{item.cpp}::_stacks_ethereal (item const & lhs, item const & rhs)
Definition at line 1576 of file item.cpp.
 {
     static const std::string varname( "ethereal" );
     return ( !lhs.ethereal && !rhs.ethereal ) ||
            ( lhs. ethereal && rhs.ethereal && lhs.get_var( varname ) == rhs.get_var( varname ) );
 }
References item::ethereal, anonymous_namespace{item_tname.cpp}::ethereal(), and item::get_var().
Referenced by item::stacks_with().
_stacks_food_irradiated()
bool anonymous_namespace{item.cpp}::_stacks_food_irradiated (item const & lhs, item const & rhs)
Definition at line 1541 of file item.cpp.
 {
     return lhs.has_flag( flag_IRRADIATED ) == rhs.has_flag( flag_IRRADIATED );
 }
References flag_IRRADIATED, and item::has_flag().
Referenced by item::stacks_with().
_stacks_food_perishable()
bool anonymous_namespace{item.cpp}::_stacks_food_perishable (item const & lhs, item const & rhs, bool check_cat)
Definition at line 1546 of file item.cpp.
 {
     return !check_cat || ( !lhs.is_food() && !rhs.is_food() ) ||
            ( lhs.is_food() && rhs.is_food() && lhs.goes_bad() == rhs.goes_bad() &&
              lhs.has_flag( flag_INEDIBLE ) == rhs.has_flag( flag_INEDIBLE ) );
 }
References flag_INEDIBLE, item::goes_bad(), item::has_flag(), and item::is_food().
Referenced by item::stacks_with().
_stacks_food_status()
bool anonymous_namespace{item.cpp}::_stacks_food_status (item const & lhs, item const & rhs)
Definition at line 1526 of file item.cpp.
 {
     return ( lhs.is_fresh() == rhs.is_fresh() || lhs.is_going_bad() == rhs.is_going_bad() ||
              lhs.rotten() == rhs.rotten() ) &&
            _stacks_mushy_dirty( lhs, rhs );
 }
References _stacks_mushy_dirty(), item::is_fresh(), item::is_going_bad(), and item::rotten().
Referenced by item::stacks_with().
_stacks_food_traits()
bool anonymous_namespace{item.cpp}::_stacks_food_traits (item const & lhs, item const & rhs)
Definition at line 1533 of file item.cpp.
 {
     return ( !lhs.is_food() && !rhs.is_food() ) ||
            ( lhs.is_food() && rhs.is_food() &&
              lhs.has_flag( flag_HIDDEN_POISON ) == rhs.has_flag( flag_HIDDEN_POISON ) &&
              lhs.has_flag( flag_HIDDEN_HALLU ) == rhs.has_flag( flag_HIDDEN_HALLU ) );
 }
References flag_HIDDEN_HALLU, flag_HIDDEN_POISON, item::has_flag(), and item::is_food().
Referenced by item::stacks_with().
_stacks_location_hint()
bool anonymous_namespace{item.cpp}::_stacks_location_hint (item const & lhs, item const & rhs)
Definition at line 1477 of file item.cpp.
 {
     static const std::string omt_loc_var = "spawn_location_omt";
     const tripoint_abs_omt this_loc( lhs.get_var( omt_loc_var, tripoint_max ) );
     const tripoint_abs_omt that_loc( rhs.get_var( omt_loc_var, tripoint_max ) );
     if( this_loc == that_loc ) {
         return true;
     } else if( this_loc.raw() != tripoint_max && that_loc.raw() != tripoint_max ) {
         const tripoint_abs_omt player_loc( ms_to_omt_copy( get_map().getabs(
                                                get_player_character().pos() ) ) );
         const int this_dist = rl_dist( player_loc, this_loc );
         const int that_dist = rl_dist( player_loc, that_loc );
         static const auto get_bucket = []( const int dist ) {
             if( dist < 1 ) {
                 return 0;
             } else if( dist < 6 ) {
                 return 1;
             } else if( dist < 30 ) {
                 return 2;
             } else {
                 return 3;
             }
         };
         return get_bucket( this_dist ) == get_bucket( that_dist );
     }
     return false;
 }
References get_map(), get_player_character(), item::get_var(), ms_to_omt_copy(), math_opers::pos(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), rl_dist(), and tripoint_max.
Referenced by item::stacks_with().
_stacks_mods()
bool anonymous_namespace{item.cpp}::_stacks_mods (item const & lhs, item const & rhs)
Definition at line 1590 of file item.cpp.
 {
     const std::vector<const item *> this_mods = lhs.mods();
     const std::vector<const item *> that_mods = rhs.mods();
     if( lhs.is_armor() && rhs.is_armor() && lhs.has_clothing_mod() != rhs.has_clothing_mod() ) {
         return false;
     }
     if( this_mods.size() != that_mods.size() ) {
         return false;
     }
     for( const item *it1 : this_mods ) {
         bool match = false;
         const bool i1_isnull = it1 == nullptr;
         for( const item *it2 : that_mods ) {
             const bool i2_isnull = it2 == nullptr;
             if( i1_isnull != i2_isnull ) {
                 continue;
             } else if( it1 == it2 || it1->typeId() == it2->typeId() ) {
                 match = true;
                 break;
             }
         }
         if( !match ) {
             return false;
         }
     }
     return true;
 }
References item::has_clothing_mod(), item::is_armor(), and item::mods().
Referenced by item::stacks_with().
_stacks_mushy_dirty()
bool anonymous_namespace{item.cpp}::_stacks_mushy_dirty (item const & lhs, item const & rhs)
Definition at line 1520 of file item.cpp.
 {
     return lhs.has_flag( flag_MUSHY ) == rhs.has_flag( flag_MUSHY ) &&
            lhs.has_own_flag( flag_DIRTY ) == rhs.has_own_flag( flag_DIRTY );
 }
References flag_DIRTY, flag_MUSHY, item::has_flag(), and item::has_own_flag().
Referenced by _stacks_food_status(), and item::stacks_with().
_stacks_rot()
bool anonymous_namespace{item.cpp}::_stacks_rot (item const & lhs, item const & rhs, bool combine_liquid)
Definition at line 1505 of file item.cpp.
 {
     // Stack items that fall into the same "bucket" of freshness.
     // Distant buckets are larger than near ones.
     std::pair<int, clipped_unit> my_clipped_time_to_rot =
         clipped_time( std::max( lhs.get_shelf_life() - lhs.get_rot(), 0_seconds ) );
     std::pair<int, clipped_unit> other_clipped_time_to_rot =
         clipped_time( std::max( rhs.get_shelf_life() - rhs.get_rot(), 0_seconds ) );
     return ( ( combine_liquid && lhs.made_of_from_type( phase_id::LIQUID ) &&
                rhs.made_of_from_type( phase_id::LIQUID ) ) ||
              my_clipped_time_to_rot == other_clipped_time_to_rot ) &&
            lhs.rotten() == rhs.rotten();
 }
References clipped_time(), item::get_rot(), item::get_shelf_life(), LIQUID, item::made_of_from_type(), max(), and item::rotten().
Referenced by item::stacks_with().
_stacks_ups()
bool anonymous_namespace{item.cpp}::_stacks_ups (item const & lhs, item const & rhs)
Definition at line 1583 of file item.cpp.
 {
     return ( !lhs.is_tool() && !rhs.is_tool() ) ||
            ( lhs.is_tool() && rhs.is_tool() &&
              lhs.has_flag( flag_USE_UPS ) == rhs.has_flag( flag_USE_UPS ) );
 }
References flag_USE_UPS, item::has_flag(), and item::is_tool().
Referenced by item::stacks_with().
_stacks_variant()
bool anonymous_namespace{item.cpp}::_stacks_variant (item const & lhs, item const & rhs)
Definition at line 1619 of file item.cpp.
 {
     return ( !lhs.has_itype_variant() && !rhs.has_itype_variant() ) ||
            ( lhs.has_itype_variant() && rhs.has_itype_variant() &&
              lhs.itype_variant().id == rhs.itype_variant().id );
 }
References item::has_itype_variant(), itype_variant_data::id, and item::itype_variant().
Referenced by item::stacks_with().
_stacks_weapon_mods()
bool anonymous_namespace{item.cpp}::_stacks_weapon_mods (item const & lhs, item const & rhs)
Definition at line 1468 of file item.cpp.
 {
     item const *const lb = lhs.is_gun() ? lhs.gunmod_find( itype_barrel_small ) : nullptr;
     item const *const rb = rhs.is_gun() ? rhs.gunmod_find( itype_barrel_small ) : nullptr;
     return ( ( lb && rb ) || ( !lb && !rb ) ) &&
            lhs.has_flag( flag_REMOVED_STOCK ) == rhs.has_flag( flag_REMOVED_STOCK ) &&
            lhs.has_flag( flag_DIAMOND ) == rhs.has_flag( flag_DIAMOND );
 }
References flag_DIAMOND, flag_REMOVED_STOCK, item::gunmod_find(), item::has_flag(), item::is_gun(), and itype_barrel_small.
Referenced by item::stacks_with().
_stacks_wetness()
bool anonymous_namespace{item.cpp}::_stacks_wetness (item const & lhs, item const & rhs, bool precise)
Definition at line 1563 of file item.cpp.
 {
     return lhs.wetness == rhs.wetness || ( !precise && ( lhs.wetness > 0 ) == ( rhs.wetness > 0 ) );
 }
References item::wetness.
Referenced by item::stacks_with().
_stacks_whiteblacklist()
bool anonymous_namespace{item.cpp}::_stacks_whiteblacklist (item const & lhs, item const & rhs)
Definition at line 1446 of file item.cpp.
 {
     bool wbl = false;
     if( lhs.get_contents().size() == rhs.get_contents().size() ) {
         std::vector<item_pocket const *> const lpkts = lhs.get_all_contained_pockets();
         std::vector<item_pocket const *> const rpkts = rhs.get_all_contained_pockets();
         if( lpkts.size() == rpkts.size() ) {
             wbl = true;
             for( std::size_t i = 0; i < lpkts.size(); i++ ) {
                 wbl &= lpkts[i]->settings.get_item_whitelist() == rpkts[i]->settings.get_item_whitelist() &&
                        lpkts[i]->settings.get_item_blacklist() == rpkts[i]->settings.get_item_blacklist() &&
                        lpkts[i]->settings.get_category_whitelist() == rpkts[i]->settings.get_category_whitelist() &&
                        lpkts[i]->settings.get_category_blacklist() == rpkts[i]->settings.get_category_blacklist();
                 if( !wbl ) {
                     break;
                 }
             }
         }
     }
     return wbl;
 }
References item::get_all_contained_pockets(), item::get_contents(), and item_contents::size().
Referenced by item::stacks_with().
left_side_parts()
const std::array<bodypart_str_id, 4>& anonymous_namespace{item.cpp}::left_side_parts ()
Definition at line 1048 of file item.cpp.
 {
     static const std::array<bodypart_str_id, 4> result{ {
             body_part_arm_l,
             body_part_hand_l,
             body_part_leg_l,
             body_part_foot_l
         } };
     return result;
 }
References body_part_arm_l, body_part_foot_l, body_part_hand_l, and body_part_leg_l.
Referenced by iterate_helper().
right_side_parts()
const std::array<bodypart_str_id, 4>& anonymous_namespace{item.cpp}::right_side_parts ()
Definition at line 1059 of file item.cpp.
 {
     static const std::array<bodypart_str_id, 4> result{ {
             body_part_arm_r,
             body_part_hand_r,
             body_part_leg_r,
             body_part_foot_r
         } };
     return result;
 }
References body_part_arm_r, body_part_foot_r, body_part_hand_r, and body_part_leg_r.
Referenced by iterate_helper().