Cataclysm DDA: anonymous_namespace{math_parser.cpp} Namespace Reference
anonymous_namespace{math_parser.cpp} Namespace Reference
Classes
struct parse_state
Functions
template<typename T , class C >
constexpr std::optional< T > _get_common (C const &cnt, std::string_view token)
constexpr std::optional< double > get_constant (std::string_view token)
std::optional< double > get_number (std::string_view token)
constexpr std::optional< pmath_func > get_function (std::string_view token)
template<class S , typename P , class C >
std::optional< S > _get_dialogue_func (C const &cnt, std::string_view token)
std::optional< scoped_diag_eval > get_dialogue_eval (std::string_view token)
std::optional< scoped_diag_ass > get_dialogue_ass (std::string_view token)
constexpr std::optional< pbin_op > get_binary_op (std::string_view token)
constexpr std::optional< punary_op > get_unary_op (std::string_view token)
bool is_function (op_t const &op)
bool is_assign_target (thingie const &thing)
std::vector< double > _eval_params (std::vector< thingie > const &params, dialogue &d)
constexpr void _validate_operand (thingie const &thing, std::string_view symbol)
void _validate_unused_kwargs (diag_kwargs const &kwargs)
Function Documentation
_eval_params()
std::vector<double> anonymous_namespace{math_parser.cpp}::_eval_params (std::vector< thingie > const & params, dialogue & d)
Definition at line 183 of file math_parser.cpp.
 {
     std::vector<double> elems( params.size() );
     std::transform( params.begin(), params.end(), elems.begin(),
     [&d]( thingie const & e ) {
         return e.eval( d );
     } );
     return elems;
 }
Referenced by func::eval(), and func_jmath::eval().
_get_common()
template<typename T , class C > constexpr std::optional<T> anonymous_namespace{math_parser.cpp}::_get_common (C const & cnt, std::string_view token) constexpr
Definition at line 35 of file math_parser.cpp.
 {
     auto const it =
     std::find_if( cnt.cbegin(), cnt.cend(), [&token]( typename C::value_type const & c ) {
         return c.symbol == token;
     } );
     if( it != cnt.end() ) {
         return { & *it };
     }
     return std::nullopt;
 }
References c.
_get_dialogue_func()
template<class S , typename P , class C > std::optional<S> anonymous_namespace{math_parser.cpp}::_get_dialogue_func (C const & cnt, std::string_view token)
Definition at line 71 of file math_parser.cpp.
 {
     char scope = 'g';
     std::string_view scoped = token;
     if( token.size() > 2 && token[1] == '_' ) {
         scope = token[0];
         scoped = token.substr( 2, token.size() - 2 );
     }
     auto df = cnt.find( scoped );
     if( df != cnt.end() ) {
         if( df->second.scopes.find( scope ) == std::string_view::npos ) {
             throw std::invalid_argument( string_format(
                                              "Scope %c is not valid for dialogue function %s() (valid scopes: %s)",
                                              scope, scoped, df->second.scopes ) );
         }
         return { { &df->second, scope } };
     }
     return std::nullopt;
 }
References string_format().
_validate_operand()
constexpr void anonymous_namespace{math_parser.cpp}::_validate_operand (thingie const & thing, std::string_view symbol) constexpr
Definition at line 193 of file math_parser.cpp.
 {
     if( std::holds_alternative<std::string>( thing.data ) ) {
         throw std::invalid_argument( string_format(
                                          R"(Operator "%s" does not support string operands)", symbol ) );
     }
     if( std::holds_alternative<array>( thing.data ) ) {
         throw std::invalid_argument( string_format(
                                          R"(Operator "%s" does not support array operands)", symbol ) );
     }
 }
References thingie::data, string_format(), and symbol().
Referenced by math_exp::math_exp_impl::new_oper(), and math_exp::math_exp_impl::new_ternary().
_validate_unused_kwargs()
void anonymous_namespace{math_parser.cpp}::_validate_unused_kwargs (diag_kwargs const & kwargs)
Definition at line 205 of file math_parser.cpp.
 {
     for( diag_kwargs::value_type const &v : kwargs ) {
         if( !v.second.was_used() ) {
             throw std::invalid_argument( string_format( R"(Unused kwarg "%s")", v.first ) );
         }
     }
 }
References string_format().
Referenced by math_exp::math_exp_impl::new_func().
get_binary_op()
constexpr std::optional<pbin_op> anonymous_namespace{math_parser.cpp}::get_binary_op (std::string_view token) constexpr
Definition at line 102 of file math_parser.cpp.
 {
     return _get_common<pbin_op>( binary_ops, token );
 }
References binary_ops.
Referenced by math_exp::math_exp_impl::_parse().
get_constant()
constexpr std::optional<double> anonymous_namespace{math_parser.cpp}::get_constant (std::string_view token) constexpr
Definition at line 48 of file math_parser.cpp.
 {
     if( std::optional<math_const const *> ret = _get_common<pmath_const>( constants, token ); ret ) {
         return ( *ret )->val;
     }
     return std::nullopt;
 }
References constants, and cata::hash64_detail::ret.
Referenced by get_number().
get_dialogue_ass()
std::optional<scoped_diag_ass> anonymous_namespace{math_parser.cpp}::get_dialogue_ass (std::string_view token)
Definition at line 97 of file math_parser.cpp.
 {
     return _get_dialogue_func<scoped_diag_ass, pdiag_func_ass>( get_all_diag_ass_funcs(), token );
 }
References get_all_diag_ass_funcs().
Referenced by math_exp::math_exp_impl::_parse().
get_dialogue_eval()
std::optional<scoped_diag_eval> anonymous_namespace{math_parser.cpp}::get_dialogue_eval (std::string_view token)
Definition at line 92 of file math_parser.cpp.
 {
     return _get_dialogue_func<scoped_diag_eval, pdiag_func_eval>( get_all_diag_eval_funcs(), token );
 }
References get_all_diag_eval_funcs().
Referenced by math_exp::math_exp_impl::_parse().
get_function()
constexpr std::optional<pmath_func> anonymous_namespace{math_parser.cpp}::get_function (std::string_view token) constexpr
Definition at line 65 of file math_parser.cpp.
 {
     return _get_common<pmath_func>( functions, token );
 }
References functions.
Referenced by math_exp::math_exp_impl::_parse().
get_number()
std::optional<double> anonymous_namespace{math_parser.cpp}::get_number (std::string_view token)
Definition at line 56 of file math_parser.cpp.
 {
     if( std::optional<double> ret = svtod( token ); ret ) {
         return *ret;
     }
     return get_constant( token );
 }
References get_constant(), cata::hash64_detail::ret, and svtod().
Referenced by math_exp::math_exp_impl::_parse().
get_unary_op()
constexpr std::optional<punary_op> anonymous_namespace{math_parser.cpp}::get_unary_op (std::string_view token) constexpr
Definition at line 107 of file math_parser.cpp.
 {
     return _get_common<punary_op>( prefix_unary_ops, token );
 }
References prefix_unary_ops.
Referenced by math_exp::math_exp_impl::_parse().
is_assign_target()
bool anonymous_namespace{math_parser.cpp}::is_assign_target (thingie const & thing)
Definition at line 177 of file math_parser.cpp.
 {
     return std::holds_alternative<var>( thing.data ) ||
            std::holds_alternative<func_diag_ass>( thing.data );
 }
References thingie::data.
Referenced by math_exp::math_exp_impl::_parse().
is_function()
bool anonymous_namespace{math_parser.cpp}::is_function (op_t const & op)
Definition at line 169 of file math_parser.cpp.
 {
     return std::holds_alternative<pmath_func>( op ) ||
            std::holds_alternative<jmath_func_id>( op ) ||
            std::holds_alternative<scoped_diag_eval>( op ) ||
            std::holds_alternative<scoped_diag_ass>( op );
 }
Referenced by math_exp::math_exp_impl::new_func(), and math_exp::math_exp_impl::parse_lparen().