Cataclysm DDA: char_creation Namespace Reference
char_creation Namespace Reference
Enumerations
enum description_selector {
NAME , GENDER , OUTFIT , HEIGHT ,
AGE , BLOOD , LOCATION
}
Functions
static void draw_name (ui_adaptor &ui, const catacurses::window &w_name, const avatar &you, const bool highlight, const bool no_name_entered)
static void draw_gender (ui_adaptor &ui, const catacurses::window &w_gender, const avatar &you, const bool highlight)
static void draw_outfit (ui_adaptor &ui, const catacurses::window &w_outfit, const bool highlight)
static void draw_height (ui_adaptor &ui, const catacurses::window &w_height, const avatar &you, const bool highlight)
static void draw_age (ui_adaptor &ui, const catacurses::window &w_age, const avatar &you, const bool highlight)
static void draw_blood (ui_adaptor &ui, const catacurses::window &w_blood, const avatar &you, const bool highlight)
static void draw_location (ui_adaptor &ui, const catacurses::window &w_location, const avatar &you, const bool highlight)
Enumeration Type Documentation
description_selector
enum char_creation::description_selector
Enumerator
NAME
GENDER
OUTFIT
HEIGHT
AGE
BLOOD
LOCATION
Definition at line 3659 of file newcharacter.cpp.
{
     NAME,
     GENDER,
     OUTFIT,
     HEIGHT,
     AGE,
     BLOOD,
     LOCATION
 };
Function Documentation
draw_age()
static void char_creation::draw_age (ui_adaptor & ui, const catacurses::window & w_age, const avatar & you, const bool highlight) static
Definition at line 3745 of file newcharacter.cpp.
 {
     werase( w_age );
     mvwprintz( w_age, point_zero, highlight ? COL_SELECT : c_light_gray, _( "Age:" ) );
     const point opt_pos( 1 + utf8_width( _( "Age:" ) ), 0 );
     if( highlight ) {
         ui.set_cursor( w_age, opt_pos );
     }
     mvwprintz( w_age, opt_pos, c_white, you.age_string( get_scenario()->start_of_game() ) );
     wnoutrefresh( w_age );
 }
References _, Character::age_string(), c_light_gray, c_white, COL_SELECT, get_scenario(), mvwprintz(), point_zero, calendar::start_of_game, utf8_width(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by set_description().
draw_blood()
static void char_creation::draw_blood (ui_adaptor & ui, const catacurses::window & w_blood, const avatar & you, const bool highlight) static
Definition at line 3758 of file newcharacter.cpp.
 {
     werase( w_blood );
     mvwprintz( w_blood, point_zero, highlight ? COL_SELECT : c_light_gray, _( "Blood type:" ) );
     const point opt_pos( 1 + utf8_width( _( "Blood type:" ) ), 0 );
     if( highlight ) {
         ui.set_cursor( w_blood, opt_pos );
     }
     mvwprintz( w_blood, opt_pos, c_white,
                io::enum_to_string( you.my_blood_type ) + ( you.blood_rh_factor ? "+" : "-" ) );
     wnoutrefresh( w_blood );
 }
References _, Character::blood_rh_factor, c_light_gray, c_white, COL_SELECT, io::enum_to_string(), mvwprintz(), Character::my_blood_type, point_zero, utf8_width(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by set_description().
draw_gender()
static void char_creation::draw_gender (ui_adaptor & ui, const catacurses::window & w_gender, const avatar & you, const bool highlight) static
Definition at line 3691 of file newcharacter.cpp.
 {
     const point male_pos( 1 + utf8_width( _( "Gender:" ) ), 0 );
     const point female_pos = male_pos + point( 2 + utf8_width( _( "Male" ) ), 0 );
     werase( w_gender );
     mvwprintz( w_gender, point_zero, highlight ? COL_SELECT : c_light_gray, _( "Gender:" ) );
     if( highlight && you.male ) {
         ui.set_cursor( w_gender, male_pos );
     }
     mvwprintz( w_gender, male_pos, ( you.male ? c_light_cyan : c_light_gray ),
                _( "Male" ) );
     if( highlight && !you.male ) {
         ui.set_cursor( w_gender, female_pos );
     }
     mvwprintz( w_gender, female_pos, ( you.male ? c_light_gray : c_pink ),
                _( "Female" ) );
     wnoutrefresh( w_gender );
 }
References _, c_light_cyan, c_light_gray, c_pink, COL_SELECT, Character::male, mvwprintz(), point_zero, utf8_width(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by set_description().
draw_height()
static void char_creation::draw_height (ui_adaptor & ui, const catacurses::window & w_height, const avatar & you, const bool highlight) static
Definition at line 3732 of file newcharacter.cpp.
 {
     werase( w_height );
     mvwprintz( w_height, point_zero, highlight ? COL_SELECT : c_light_gray, _( "Height:" ) );
     const point opt_pos( 1 + utf8_width( _( "Height:" ) ), 0 );
     if( highlight ) {
         ui.set_cursor( w_height, opt_pos );
     }
     mvwprintz( w_height, opt_pos, c_white, you.height_string() );
     wnoutrefresh( w_height );
 }
References _, c_light_gray, c_white, COL_SELECT, Character::height_string(), mvwprintz(), point_zero, utf8_width(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by set_description().
draw_location()
static void char_creation::draw_location (ui_adaptor & ui, const catacurses::window & w_location, const avatar & you, const bool highlight) static
Definition at line 3772 of file newcharacter.cpp.
 {
     std::string random_start_location_text = string_format( n_gettext(
                 "<color_red>* Random location *</color> (<color_white>%d</color> variant)",
                 "<color_red>* Random location *</color> (<color_white>%d</color> variants)",
                 get_scenario()->start_location_targets_count() ), get_scenario()->start_location_targets_count() );
     if( get_scenario()->start_location_targets_count() == 1 ) {
         random_start_location_text = get_scenario()->start_location().obj().name();
     }
     werase( w_location );
     mvwprintz( w_location, point_zero, highlight ? COL_SELECT : c_light_gray,
                _( "Starting location:" ) );
     const point opt_pos( utf8_width( _( "Starting location:" ) ) + 1, 0 );
     if( highlight ) {
         ui.set_cursor( w_location, opt_pos );
     }
     // ::find will return empty location if id was not found. Debug msg will be printed too.
     mvwprintz( w_location, opt_pos,
                you.random_start_location ? c_red : c_white,
                you.random_start_location ? remove_color_tags( random_start_location_text ) :
                string_format( n_gettext( "%s (%d variant)", "%s (%d variants)",
                                          you.start_location.obj().targets_count() ),
                               you.start_location.obj().name(), you.start_location.obj().targets_count() ) );
     wnoutrefresh( w_location );
 }
References _, c_light_gray, c_red, c_white, COL_SELECT, get_scenario(), mvwprintz(), n_gettext, start_location::name(), string_id< T >::obj(), point_zero, Character::random_start_location, remove_color_tags(), Character::start_location, scenario::start_location(), string_format(), start_location::targets_count(), utf8_width(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by set_description().
draw_name()
static void char_creation::draw_name (ui_adaptor & ui, const catacurses::window & w_name, const avatar & you, const bool highlight, const bool no_name_entered) static
Definition at line 3669 of file newcharacter.cpp.
 {
     werase( w_name );
     mvwprintz( w_name, point_zero,
                highlight ? COL_SELECT : c_light_gray, _( "Name:" ) );
     const point opt_pos( 1 + utf8_width( _( "Name:" ) ), 0 );
     if( highlight ) {
         ui.set_cursor( w_name, opt_pos );
     }
     if( no_name_entered ) {
         mvwprintz( w_name, opt_pos, COL_SELECT, _( "--- NO NAME ENTERED ---" ) );
     } else if( you.name.empty() ) {
         mvwprintz( w_name, opt_pos, c_light_gray, _( "--- RANDOM NAME ---" ) );
     } else {
         mvwprintz( w_name, opt_pos, c_white, you.name );
     }
     wnoutrefresh( w_name );
 }
References _, c_light_gray, c_white, COL_SELECT, mvwprintz(), Character::name, point_zero, utf8_width(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by set_description().
draw_outfit()
static void char_creation::draw_outfit (ui_adaptor & ui, const catacurses::window & w_outfit, const bool highlight) static
Definition at line 3712 of file newcharacter.cpp.
 {
     const point male_pos( 1 + utf8_width( _( "Outfit:" ) ), 0 );
     const point female_pos = male_pos + point( 2 + utf8_width( _( "Male" ) ), 0 );
     werase( w_outfit );
     mvwprintz( w_outfit, point_zero, highlight ? COL_SELECT : c_light_gray, _( "Outfit:" ) );
     if( highlight && outfit ) {
         ui.set_cursor( w_outfit, male_pos );
     }
     mvwprintz( w_outfit, male_pos, ( outfit ? c_light_cyan : c_light_gray ),
                _( "Male" ) );
     if( highlight && !outfit ) {
         ui.set_cursor( w_outfit, female_pos );
     }
     mvwprintz( w_outfit, female_pos, ( outfit ? c_light_gray : c_pink ),
                _( "Female" ) );
     wnoutrefresh( w_outfit );
 }
References _, c_light_cyan, c_light_gray, c_pink, COL_SELECT, mvwprintz(), point_zero, utf8_width(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by set_description().