Cataclysm DDA: explosion_handler Namespace Reference
explosion_handler Namespace Reference
Classes
struct queued_explosion
Functions
int ballistic_damage (float velocity, float mass)
static float mass_to_area (const float mass)
float gurney_spherical (const double charge, const double mass)
static void do_blast (const Creature *source, const tripoint &p, const float power, const float distance_factor, const bool fire)
static std::vector< tripoint > shrapnel (const Creature *source, const tripoint &src, int power, int casing_mass, float per_fragment_mass, int range=-1)
void explosion (const Creature *source, const tripoint &p, float power, float factor=0.8f, bool fire=false, int casing_mass=0, float frag_mass=0.05)
Queue an explosion at p of intensity (power) with (shrapnel) chunks of shrapnel.
void explosion (const Creature *source, const tripoint &p, const explosion_data &ex)
void _make_explosion (const Creature *source, const tripoint &p, const explosion_data &ex)
void flashbang (const tripoint &p, bool player_immune=false)
Triggers a flashbang explosion at p.
void shockwave (const tripoint &p, int radius, int force, int stun, int dam_mult, bool ignore_player)
void scrambler_blast (const tripoint &p)
Triggers a scrambler blast at p.
void emp_blast (const tripoint &p)
Triggers an EMP blast at p.
void nuke (const tripoint_abs_omt &p)
Nuke the area at p - global overmap terrain coordinates!
void resonance_cascade (const tripoint &p)
Triggers a resonance cascade at p.
void process_explosions ()
void draw_explosion (const tripoint &p, int radius, const nc_color &col)
void draw_custom_explosion (const tripoint &p, const std::map< tripoint, nc_color > &area, const std::optional< std::string > &tile_id=std::nullopt)
Variables
static constexpr double TYPICAL_GURNEY_CONSTANT = 2700.0
std::vector< queued_explosion > _explosions
Function Documentation
_make_explosion()
void explosion_handler::_make_explosion (const Creature * source, const tripoint & p, const explosion_data & ex)
Definition at line 506 of file explosion.cpp.
 {
     int noise = ex.power * ( ex.fire ? 2 : 10 );
     noise = ( noise > ex.max_noise ) ? ex.max_noise : noise;
     if( noise >= 30 ) {
         sounds::sound( p, noise, sounds::sound_t::combat, _( "a huge explosion!" ), false, "explosion",
                        "huge" );
     } else if( noise >= 4 ) {
         sounds::sound( p, noise, sounds::sound_t::combat, _( "an explosion!" ), false, "explosion",
                        "default" );
     } else if( noise > 0 ) {
         sounds::sound( p, 3, sounds::sound_t::combat, _( "a loud pop!" ), false, "explosion", "small" );
     }
     if( ex.distance_factor >= 1.0f ) {
         debugmsg( "called game::explosion with factor >= 1.0 (infinite size)" );
     } else if( ex.distance_factor > 0.0f && ex.power > 0.0f ) {
         // Power rescaled to mean grams of TNT equivalent, this scales it roughly back to where
         // it was before until we re-do blasting power to be based on TNT-equivalent directly.
         do_blast( source, p, ex.power / 15.0, ex.distance_factor, ex.fire );
     }
     map &here = get_map();
     const shrapnel_data &shr = ex.shrapnel;
     if( shr.casing_mass > 0 ) {
         auto shrapnel_locations = shrapnel( source, p, ex.power, shr.casing_mass, shr.fragment_mass );
         // If explosion drops shrapnel...
         if( shr.recovery > 0 && !shr.drop.is_null() ) {
             // Extract only passable tiles affected by shrapnel
             std::vector<tripoint> tiles;
             for( const tripoint &e : shrapnel_locations ) {
                 if( here.passable( e ) ) {
                     tiles.push_back( e );
                 }
             }
             const itype *fragment_drop = item_controller->find_template( shr.drop );
             int qty = shr.casing_mass * std::min( 1.0, shr.recovery / 100.0 ) /
                       to_gram( fragment_drop->weight );
             // Truncate to a random selection
             std::shuffle( tiles.begin(), tiles.end(), rng_get_engine() );
             tiles.resize( std::min( static_cast<int>( tiles.size() ), qty ) );
             for( const tripoint &e : tiles ) {
                 here.add_item_or_charges( e, item( shr.drop, calendar::turn, item::solitary_tag{} ) );
             }
         }
     }
 }
References _, map::add_item_or_charges(), shrapnel_data::casing_mass, sounds::combat, debugmsg, explosion_data::distance_factor, do_blast(), shrapnel_data::drop, explosion_data::fire, shrapnel_data::fragment_mass, get_map(), string_id< T >::is_null(), item_controller, explosion_data::max_noise, min(), map::passable(), explosion_data::power, shrapnel_data::recovery, rng_get_engine(), shrapnel(), explosion_data::shrapnel, sounds::sound(), units::to_gram(), calendar::turn, and itype::weight.
Referenced by process_explosions().
ballistic_damage()
int explosion_handler::ballistic_damage (float velocity, float mass)
Definition at line 149 of file explosion.cpp.
 {
     // Damage is square root of Joules, dividing by 2000 because it's dividing by 2 and
     // converting mass from grams to kg. The initial term is simply a scaling factor.
     return 4.0 * std::sqrt( ( velocity * velocity * mass ) / 2000.0 );
 }
References sqrt().
Referenced by shrapnel().
do_blast()
static void explosion_handler::do_blast (const Creature * source, const tripoint & p, const float power, const float distance_factor, const bool fire) static
Definition at line 175 of file explosion.cpp.
 {
     const float tile_dist = 1.0f;
     const float diag_dist = trigdist ? M_SQRT2 * tile_dist : 1.0f * tile_dist;
     const float zlev_dist = 2.0f; // Penalty for going up/down
     // 7 3 5
     // 1 . 2
     // 6 4 8
     // 9 and 10 are up and down
     static constexpr std::array<int, 10> x_offset = { -1, 1,  0, 0,  1, -1, -1, 1, 0, 0 };
     static constexpr std::array<int, 10> y_offset = { 0, 0, -1, 1, -1,  1, -1, 1, 0, 0 };
     static constexpr std::array<int, 10> z_offset = { 0, 0,  0, 0,  0,  0,  0, 0, 1, -1 };
     map &here = get_map();
     const size_t max_index = 10;
     here.bash( p, fire ? power : ( 2 * power ), true, false, false );
     std::priority_queue< std::pair<float, tripoint>, std::vector< std::pair<float, tripoint> >, pair_greater_cmp_first >
     open;
     std::set<tripoint> closed;
     std::set<tripoint> bashed{ p };
     std::map<tripoint, float> dist_map;
     open.emplace( 0.0f, p );
     dist_map[p] = 0.0f;
     // Find all points to blast
     while( !open.empty() ) {
         // Add some random factor to effective distance to make it look cooler
         const float distance = open.top().first * rng_float( 1.0f, 1.2f );
         const tripoint pt = open.top().second;
         open.pop();
         if( closed.count( pt ) != 0 ) {
             continue;
         }
         closed.insert( pt );
         const float force = power * std::pow( distance_factor, distance );
         if( force <= 1.0f ) {
             continue;
         }
         if( here.impassable( pt ) && pt != p ) {
             // Don't propagate further
             continue;
         }
         // Those will be used for making "shaped charges"
         // Don't check up/down (for now) - this will make 2D/3D balancing easier
         int empty_neighbors = 0;
         for( size_t i = 0; i < 8; i++ ) {
             tripoint dest( pt + tripoint( x_offset[i], y_offset[i], z_offset[i] ) );
             if( closed.count( dest ) == 0 && here.valid_move( pt, dest, false, true ) ) {
                 empty_neighbors++;
             }
         }
         empty_neighbors = std::max( 1, empty_neighbors );
         // Iterate over all neighbors. Bash all of them, propagate to some
         for( size_t i = 0; i < max_index; i++ ) {
             tripoint dest( pt + tripoint( x_offset[i], y_offset[i], z_offset[i] ) );
             if( closed.count( dest ) != 0 || !here.inbounds( dest ) ) {
                 continue;
             }
             if( bashed.count( dest ) == 0 ) {
                 bashed.insert( dest );
                 // Up to 200% bonus for shaped charge
                 // But not if the explosion is fiery, then only half the force and no bonus
                 const float bash_force = !fire ?
                                          force + ( 2 * force / empty_neighbors ) :
                                          force / 2;
                 if( z_offset[i] == 0 ) {
                     // Horizontal - no floor bashing
                     here.bash( dest, bash_force, true, false, false );
                 } else if( z_offset[i] > 0 ) {
                     // Should actually bash through the floor first, but that's not really possible yet
                     here.bash( dest, bash_force, true, false, true );
                 } else if( !here.valid_move( pt, dest, false, true ) ) {
                     // Only bash through floor if it doesn't exist
                     // Bash the current tile's floor, not the one's below
                     here.bash( pt, bash_force, true, false, true );
                 }
             }
             float next_dist = distance;
             next_dist += ( x_offset[i] == 0 || y_offset[i] == 0 ) ? tile_dist : diag_dist;
             if( z_offset[i] != 0 ) {
                 if( !here.valid_move( pt, dest, false, true ) ) {
                     continue;
                 }
                 next_dist += zlev_dist;
             }
             if( dist_map.count( dest ) == 0 || dist_map[dest] > next_dist ) {
                 open.emplace( next_dist, dest );
                 dist_map[dest] = next_dist;
             }
         }
     }
     // Draw the explosion
     std::map<tripoint, nc_color> explosion_colors;
     for( const tripoint &pt : closed ) {
         if( here.impassable( pt ) ) {
             continue;
         }
         const float force = power * std::pow( distance_factor, dist_map.at( pt ) );
         nc_color col = c_red;
         if( force < 10 ) {
             col = c_white;
         } else if( force < 30 ) {
             col = c_yellow;
         }
         explosion_colors[pt] = col;
     }
     draw_custom_explosion( get_player_character().pos(), explosion_colors );
     creature_tracker &creatures = get_creature_tracker();
     Creature *mutable_source = source == nullptr ? nullptr : creatures.creature_at( source->pos() );
     for( const tripoint &pt : closed ) {
         const float force = power * std::pow( distance_factor, dist_map.at( pt ) );
         if( force < 1.0f ) {
             // Too weak to matter
             continue;
         }
         if( here.has_items( pt ) ) {
             here.smash_items( pt, force, _( "force of the explosion" ) );
         }
         if( fire ) {
             int intensity = ( force > 50.0f ) + ( force > 100.0f );
             if( force > 10.0f || x_in_y( force, 10.0f ) ) {
                 intensity++;
             }
             here.add_field( pt, fd_fire, intensity );
         }
         if( const optional_vpart_position vp = here.veh_at( pt ) ) {
             // TODO: Make this weird unit used by vehicle::damage more sensible
             vp->vehicle().damage( here, vp->part_index(), force,
                                   fire ? damage_heat : damage_bash, false );
         }
         Creature *critter = creatures.creature_at( pt, true );
         if( critter == nullptr ) {
             continue;
         }
         add_msg_debug( debugmode::DF_EXPLOSION, "Blast hits %s with force %.1f", critter->disp_name(),
                        force );
         Character *pl = critter->as_character();
         if( pl == nullptr ) {
             const double dmg = std::max( force - critter->get_armor_type( damage_bash,
                                          bodypart_id( "torso" ) ) / 2.0, 0.0 );
             const int actual_dmg = rng_float( dmg * 2, dmg * 3 );
             critter->apply_damage( mutable_source, bodypart_id( "torso" ), actual_dmg );
             critter->check_dead_state();
             add_msg_debug( debugmode::DF_EXPLOSION, "Blast hits %s for %d damage", critter->disp_name(),
                            actual_dmg );
             continue;
         }
         // Print messages for all NPCs
         pl->add_msg_player_or_npc( m_bad, _( "You're caught in the explosion!" ),
                                    _( "<npcname> is caught in the explosion!" ) );
         struct blastable_part {
             bodypart_id bp;
             float low_mul = 0.0f;
             float high_mul = 0.0f;
             float armor_mul = 0.0f;
         };
         static const std::array<blastable_part, 6> blast_parts = { {
                 { bodypart_id( "torso" ), 2.0f, 3.0f, 0.5f },
                 { bodypart_id( "head" ),  2.0f, 3.0f, 0.5f },
                 // Hit limbs harder so that it hurts more without being much more deadly
                 { bodypart_id( "leg_l" ), 2.0f, 3.5f, 0.4f },
                 { bodypart_id( "leg_r" ), 2.0f, 3.5f, 0.4f },
                 { bodypart_id( "arm_l" ), 2.0f, 3.5f, 0.4f },
                 { bodypart_id( "arm_r" ), 2.0f, 3.5f, 0.4f },
             }
         };
         for( const blastable_part &blp : blast_parts ) {
             const int part_dam = rng( force * blp.low_mul, force * blp.high_mul );
             const std::string hit_part_name = body_part_name_accusative( blp.bp );
             // FIXME: Hardcoded damage type
             const damage_instance dmg_instance = damage_instance( damage_bash, part_dam, 0, blp.armor_mul );
             const dealt_damage_instance result = pl->deal_damage( mutable_source, blp.bp, dmg_instance );
             const int res_dmg = result.total_damage();
             add_msg_debug( debugmode::DF_EXPLOSION, "%s for %d raw, %d actual", hit_part_name, part_dam,
                            res_dmg );
             if( res_dmg > 0 ) {
                 pl->add_msg_if_player( m_bad, _( "Your %s is hit for %d damage!" ), hit_part_name, res_dmg );
             }
         }
     }
 }
References _, map::add_field(), add_msg_debug, Character::add_msg_if_player(), Character::add_msg_player_or_npc(), Creature::apply_damage(), Creature::as_character(), map::bash(), body_part_name_accusative(), bp, c_red, c_white, c_yellow, Creature::check_dead_state(), creature_tracker::creature_at(), damage_bash, damage_heat, Character::deal_damage(), debugmode::DF_EXPLOSION, Creature::disp_name(), draw_custom_explosion(), fd_fire, fire(), force, Creature::get_armor_type(), get_creature_tracker(), get_map(), get_player_character(), map::has_items(), map::impassable(), map::inbounds(), intensity, m_bad, M_SQRT2, max(), open(), Creature::pos(), math_opers::pos(), rng(), rng_float(), map::smash_items(), dealt_damage_instance::total_damage(), trigdist, map::valid_move(), map::veh_at(), and x_in_y().
Referenced by _make_explosion().
draw_custom_explosion()
void explosion_handler::draw_custom_explosion (const tripoint & p, const std::map< tripoint, nc_color > & area, const std::optional< std::string > & tile_id = std::nullopt)
Definition at line 309 of file animation.cpp.
 {
     if( test_mode ) {
         // avoid segfault from null tilecontext in tests
         return;
     }
     constexpr explosion_neighbors all_neighbors = N_NORTH | N_SOUTH | N_WEST | N_EAST;
     // We will "shell" the explosion area
     // Each phase will strip a single layer of points
     // A layer contains all points that have less than 4 neighbors in cardinal directions
     // Layers will first be generated, then drawn in inverse order
     // Start by getting rid of everything except current z-level
     std::map<tripoint, explosion_tile> neighbors;
     avatar &player_character = get_avatar();
 #if defined(TILES)
     if( !use_tiles ) {
         for( const auto &pr : all_area ) {
             const tripoint relative_point = relative_view_pos( player_character, pr.first );
             if( relative_point.z == 0 ) {
                 neighbors[pr.first] = explosion_tile{ N_NO_NEIGHBORS, pr.second, tile_id };
             }
         }
     } else {
         // In tiles mode, the coordinates have to be absolute
         const tripoint view_center = relative_view_pos( player_character, player_character.pos() );
         for( const auto &pr : all_area ) {
             // Relative point is only used for z level check
             const tripoint relative_point = relative_view_pos( player_character, pr.first );
             if( relative_point.z == view_center.z ) {
                 neighbors[pr.first] = explosion_tile{ N_NO_NEIGHBORS, pr.second, tile_id };
             }
         }
     }
 #else
     for( const auto &pr : all_area ) {
         const tripoint relative_point = relative_view_pos( player_character, pr.first );
         if( relative_point.z == 0 ) {
             neighbors[pr.first] = explosion_tile{ N_NO_NEIGHBORS, pr.second, tile_id };
         }
     }
 #endif
     // Searches for a neighbor, sets the neighborhood flag on current point and on the neighbor
     const auto set_neighbors = [&]( const tripoint & pos,
                                     explosion_neighbors & ngh,
                                     explosion_neighbors here,
     explosion_neighbors there ) {
         if( ( ngh & here ) == N_NO_NEIGHBORS ) {
             auto other = neighbors.find( pos );
             if( other != neighbors.end() ) {
                 ngh = ngh | here;
                 other->second.neighborhood = other->second.neighborhood | there;
             }
         }
     };
     // If the point we are about to remove has a neighbor in a given direction
     // unset that neighbor's flag that our current point is its neighbor
     const auto unset_neighbor = [&]( const tripoint & pos,
                                      const explosion_neighbors ngh,
                                      explosion_neighbors here,
     explosion_neighbors there ) {
         if( ( ngh & here ) != N_NO_NEIGHBORS ) {
             auto other = neighbors.find( pos );
             if( other != neighbors.end() ) {
                 other->second.neighborhood = ( other->second.neighborhood | there ) ^ there;
             }
         }
     };
     // Find all neighborhoods
     for( auto &pr : neighbors ) {
         const tripoint &pt = pr.first;
         explosion_neighbors &ngh = pr.second.neighborhood;
         set_neighbors( pt + point_west, ngh, N_WEST, N_EAST );
         set_neighbors( pt + point_east, ngh, N_EAST, N_WEST );
         set_neighbors( pt + point_north, ngh, N_NORTH, N_SOUTH );
         set_neighbors( pt + point_south, ngh, N_SOUTH, N_NORTH );
     }
     // We need to save the layers because we will draw them in reverse order
     std::list< std::map<tripoint, explosion_tile> > layers;
     while( !neighbors.empty() ) {
         std::map<tripoint, explosion_tile> layer;
         bool changed = false;
         // Find a layer that can be drawn
         for( const auto &pr : neighbors ) {
             if( pr.second.neighborhood != all_neighbors ) {
                 changed = true;
                 layer.insert( pr );
             }
         }
         if( !changed ) {
             // An error, but a minor one - let it slide
             return;
         }
         // Remove the layer from the area to process
         for( const auto &pr : layer ) {
             const tripoint &pt = pr.first;
             const explosion_neighbors ngh = pr.second.neighborhood;
             unset_neighbor( pt + point_west, ngh, N_WEST, N_EAST );
             unset_neighbor( pt + point_east, ngh, N_EAST, N_WEST );
             unset_neighbor( pt + point_north, ngh, N_NORTH, N_SOUTH );
             unset_neighbor( pt + point_south, ngh, N_SOUTH, N_NORTH );
             neighbors.erase( pr.first );
         }
         layers.push_front( std::move( layer ) );
     }
 #if defined(TILES)
     if( !use_tiles ) {
         draw_custom_explosion_curses( *g, layers );
         return;
     }
     explosion_animation anim;
     // We need to draw all explosions up to now
     std::map<tripoint, explosion_tile> combined_layer;
     shared_ptr_fast<game::draw_callback_t> explosion_cb =
     make_shared_fast<game::draw_callback_t>( [&]() {
         tilecontext->init_custom_explosion_layer( combined_layer );
     } );
     g->add_draw_callback( explosion_cb );
     for( const auto &layer : layers ) {
         combined_layer.insert( layer.begin(), layer.end() );
         if( is_layer_visible( layer ) ) {
             anim.progress();
         }
     }
     tilecontext->void_custom_explosion();
 #else
     draw_custom_explosion_curses( *g, layers );
 #endif
 }
References anonymous_namespace{animation.cpp}::draw_custom_explosion_curses(), g, get_avatar(), anonymous_namespace{animation.cpp}::is_layer_visible(), N_EAST, N_NO_NEIGHBORS, N_NORTH, N_SOUTH, N_WEST, other, point_east, point_north, point_south, point_west, Creature::pos(), math_opers::pos(), anonymous_namespace{animation.cpp}::relative_view_pos(), test_mode, use_tiles, and tripoint::z.
Referenced by Creature::attack_air(), do_blast(), and spell_effect_area().
draw_explosion()
void explosion_handler::draw_explosion (const tripoint & p, int radius, const nc_color & col)
Definition at line 303 of file animation.cpp.
 {
     draw_explosion_curses( *g, p, r, col );
 }
References anonymous_namespace{animation.cpp}::draw_explosion_curses(), and g.
Referenced by flashbang(), iuse::granade_act(), shockwave(), and explosion_iuse::use().
emp_blast()
void explosion_handler::emp_blast (const tripoint & p)
Triggers an EMP blast at p.
Definition at line 657 of file explosion.cpp.
 {
     Character &player_character = get_player_character();
     const bool sight = player_character.sees( p );
     map &here = get_map();
     if( here.has_flag( ter_furn_flag::TFLAG_CONSOLE, p ) ) {
         if( sight ) {
             add_msg( _( "The %s is rendered non-functional!" ), here.tername( p ) );
         }
         here.furn_set( p, furn_f_machinery_electronic );
         return;
     }
     // TODO: More terrain effects.
     if( here.ter( p ) == ter_t_card_science || here.ter( p ) == ter_t_card_military ||
         here.ter( p ) == ter_t_card_industrial ) {
         int rn = rng( 1, 100 );
         if( rn > 92 || rn < 40 ) {
             if( sight ) {
                 add_msg( _( "The card reader is rendered non-functional." ) );
             }
             here.ter_set( p, ter_t_card_reader_broken );
         }
         if( rn > 80 ) {
             if( sight ) {
                 add_msg( _( "The nearby doors slide open!" ) );
             }
             for( int i = -3; i <= 3; i++ ) {
                 for( int j = -3; j <= 3; j++ ) {
                     if( here.ter( p + tripoint( i, j, 0 ) ) == ter_t_door_metal_locked ) {
                         here.ter_set( p + tripoint( i, j, 0 ), ter_t_floor );
                     }
                 }
             }
         }
         if( rn >= 40 && rn <= 80 ) {
             if( sight ) {
                 add_msg( _( "Nothing happens." ) );
             }
         }
     }
     if( monster *const mon_ptr = get_creature_tracker().creature_at<monster>( p ) ) {
         monster &critter = *mon_ptr;
         if( critter.has_flag( mon_flag_ELECTRONIC ) ) {
             int deact_chance = 0;
             const itype_id mon_item_id = critter.type->revert_to_itype;
             switch( critter.get_size() ) {
                 case creature_size::tiny:
                     deact_chance = 6;
                     break;
                 case creature_size::small:
                     deact_chance = 3;
                     break;
                 default:
                     // Currently not used, I have no idea what chances bigger bots should have,
                     // Maybe export this to json?
                     break;
             }
             if( !mon_item_id.is_empty() && deact_chance != 0 && one_in( deact_chance ) ) {
                 if( sight ) {
                     add_msg( _( "The %s beeps erratically and deactivates!" ), critter.name() );
                 }
                 here.add_item_or_charges( p, critter.to_item() );
                 for( auto &ammodef : critter.ammo ) {
                     if( ammodef.second > 0 ) {
                         here.spawn_item( p, ammodef.first, 1, ammodef.second, calendar::turn );
                     }
                 }
                 g->remove_zombie( critter );
             } else {
                 if( sight ) {
                     add_msg( _( "The EMP blast fries the %s!" ), critter.name() );
                 }
                 int dam = dice( 10, 10 );
                 critter.apply_damage( nullptr, bodypart_id( "torso" ), dam );
                 critter.check_dead_state();
                 if( !critter.is_dead() && one_in( 6 ) ) {
                     critter.make_friendly();
                 }
             }
         } else if( critter.has_flag( mon_flag_ELECTRIC_FIELD ) ) {
             if( !critter.has_effect( effect_emp ) ) {
                 if( sight ) {
                     add_msg( m_good, _( "The %s's electrical field momentarily goes out!" ), critter.name() );
                 }
                 critter.add_effect( effect_emp, 3_minutes );
             } else if( critter.has_effect( effect_emp ) ) {
                 int dam = dice( 3, 5 );
                 if( sight ) {
                     add_msg( m_good, _( "The %s's disabled electrical field reverses polarity!" ),
                              critter.name() );
                     add_msg( m_good, _( "It takes %d damage." ), dam );
                 }
                 critter.add_effect( effect_emp, 1_minutes );
                 critter.apply_damage( nullptr, bodypart_id( "torso" ), dam );
                 critter.check_dead_state();
             }
         } else if( sight ) {
             add_msg( _( "The %s is unaffected by the EMP blast." ), critter.name() );
         }
     }
     if( player_character.posx() == p.x && player_character.posy() == p.y &&
         player_character.posz() == p.z ) {
         if( player_character.get_power_level() > 0_kJ &&
             !player_character.has_flag( json_flag_EMP_IMMUNE ) ) {
             add_msg( m_bad, _( "The EMP blast drains your power." ) );
             int max_drain = ( player_character.get_power_level() > 1000_kJ ? 1000 : units::to_kilojoule(
                                   player_character.get_power_level() ) );
             player_character.mod_power_level( units::from_kilojoule( static_cast<std::int64_t>( -rng(
                                                   1 + max_drain / 3, max_drain ) ) ) );
         }
         // TODO: More effects?
         //e-handcuffs effects
         item_location weapon = player_character.get_wielded_item();
         if( weapon && weapon->typeId() == itype_e_handcuffs && weapon->charges > 0 ) {
             weapon->unset_flag( STATIC( flag_id( "NO_UNWIELD" ) ) );
             weapon->charges = 0;
             weapon->active = false;
             add_msg( m_good, _( "The %s on your wrists spark briefly, then release your hands!" ),
                      weapon->tname() );
         }
         for( item_location &it : player_character.all_items_loc() ) {
             // Render any electronic stuff in player's possession non-functional
             if( it->has_flag( flag_ELECTRONIC ) && !it->is_broken() &&
                 get_option<bool>( "EMP_DISABLE_ELECTRONICS" ) &&
                 !player_character.has_flag( json_flag_EMP_IMMUNE ) ) {
                 add_msg( m_bad, _( "The EMP blast fries your %s!" ), it->tname() );
                 it->deactivate();
                 it->faults.insert( random_entry( fault::get_by_type( "shorted" ) ) );
             }
         }
     }
     for( item &it : here.i_at( p ) ) {
         // Render any electronic stuff on the ground non-functional
         if( it.has_flag( flag_ELECTRONIC ) && !it.is_broken() &&
             get_option<bool>( "EMP_DISABLE_ELECTRONICS" ) ) {
             if( sight ) {
                 add_msg( _( "The EMP blast fries the %s!" ), it.tname() );
             }
             it.deactivate();
             it.set_fault( random_entry( fault::get_by_type( "shorted" ) ) );
         }
     }
     // TODO: Drain NPC energy reserves
 }
References _, item::active, Creature::add_effect(), map::add_item_or_charges(), add_msg(), Character::all_items_loc(), monster::ammo, monster::apply_damage(), item::charges, Creature::check_dead_state(), dice(), effect_emp, flag_ELECTRONIC, units::from_kilojoule(), furn_f_machinery_electronic, map::furn_set(), g, fault::get_by_type(), get_creature_tracker(), get_map(), get_player_character(), Character::get_power_level(), monster::get_size(), Character::get_wielded_item(), Creature::has_effect(), Character::has_flag(), monster::has_flag(), map::has_flag(), map::i_at(), monster::is_dead(), string_id< T >::is_empty(), itype_e_handcuffs, json_flag_EMP_IMMUNE, m_bad, m_good, monster::make_friendly(), Character::mod_power_level(), mon_flag_ELECTRIC_FIELD, mon_flag_ELECTRONIC, monster::name(), one_in(), Creature::posx(), Creature::posy(), Creature::posz(), random_entry(), mtype::revert_to_itype, rng(), Character::sees(), small, map::spawn_item(), STATIC, map::ter(), map::ter_set(), ter_t_card_industrial, ter_t_card_military, ter_t_card_reader_broken, ter_t_card_science, ter_t_door_metal_locked, ter_t_floor, map::tername(), TFLAG_CONSOLE, tiny, item::tname(), monster::to_item(), units::to_kilojoule(), calendar::turn, monster::type, item::typeId(), item::unset_flag(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by Character::activate_bionic(), apply_ammo_effects(), monster::process_turn(), resonance_cascade(), and explosion_iuse::use().
explosion() [1/2]
void explosion_handler::explosion (const Creature * source, const tripoint & p, const explosion_data & ex)
Definition at line 501 of file explosion.cpp.
 {
     _explosions.emplace_back( source, get_map().getglobal( p ), ex );
 }
References _explosions, and get_map().
explosion() [2/2]
void explosion_handler::explosion (const Creature * source, const tripoint & p, float power, float factor = 0.8f, bool fire = false, int casing_mass = 0, float frag_mass = 0.05)
Queue an explosion at p of intensity (power) with (shrapnel) chunks of shrapnel.
Explosion intensity formula is roughly power*factor^distance. If factor <= 0, no blast is produced The explosion won't actually occur until process_explosions()
Definition at line 489 of file explosion.cpp.
 {
     explosion_data data;
     data.power = power;
     data.distance_factor = factor;
     data.fire = fire;
     data.shrapnel.casing_mass = casing_mass;
     data.shrapnel.fragment_mass = frag_mass;
     explosion( source, p, data );
 }
References shrapnel_data::casing_mass, explosion_data::distance_factor, explosion_data::fire, fire(), shrapnel_data::fragment_mass, explosion_data::power, and explosion_data::shrapnel.
Referenced by computer_session::action_irradiator(), computer_session::action_miss_launch(), computer_session::action_srcf_seal(), apply_ammo_effects(), map::bash_ter_furn(), item::detonate(), vehicle::explode_fuel(), spell_effect::explosion(), computer_session::failure_amigara(), computer_session::failure_pump_explode(), iuse::grenade_inc_act(), Character::handle_gun_overheat(), vehicle::handle_trap(), trapfunc::landmine(), monster::process_turn(), projectile_attack(), resonance_cascade(), teleport::teleport_to_point(), and explosion_iuse::use().
flashbang()
void explosion_handler::flashbang (const tripoint & p, bool player_immune)
Triggers a flashbang explosion at p.
Definition at line 557 of file explosion.cpp.
 {
     draw_explosion( p, 8, c_white );
     Character &player_character = get_player_character();
     int dist = rl_dist( player_character.pos(), p );
     map &here = get_map();
     if( dist <= 8 && !player_immune ) {
         if( !player_character.has_flag( STATIC( json_character_flag( "IMMUNE_HEARING_DAMAGE" ) ) ) &&
             !player_character.is_wearing( itype_rm13_armor_on ) ) {
             player_character.add_effect( effect_deaf, time_duration::from_turns( 40 - dist * 4 ) );
         }
         if( here.sees( player_character.pos(), p, 8 ) ) {
             int flash_mod = 0;
             if( player_character.has_trait( trait_PER_SLIME ) ) {
                 if( one_in( 2 ) ) {
                     flash_mod = 3; // Yay, you weren't looking!
                 }
             } else if( player_character.has_trait( trait_PER_SLIME_OK ) ) {
                 flash_mod = 8; // Just retract those and extrude fresh eyes
             } else if( player_character.has_flag( json_flag_GLARE_RESIST ) ||
                        player_character.is_wearing( itype_rm13_armor_on ) ) {
                 flash_mod = 6;
             } else if( player_character.worn_with_flag( STATIC( flag_id( "BLIND" ) ) ) ||
                        player_character.worn_with_flag( STATIC( flag_id( "FLASH_PROTECTION" ) ) ) ) {
                 flash_mod = 3; // Not really proper flash protection, but better than nothing
             }
             player_character.add_env_effect( effect_blind, bodypart_id( "eyes" ), ( 12 - flash_mod - dist ) / 2,
                                              time_duration::from_turns( 10 - dist ) );
         }
     }
     for( monster &critter : g->all_monsters() ) {
         if( critter.type->in_species( species_ROBOT ) ) {
             continue;
         }
         // TODO: can the following code be called for all types of creatures
         dist = rl_dist( critter.pos(), p );
         if( dist <= 8 ) {
             if( dist <= 4 ) {
                 critter.add_effect( effect_stunned, time_duration::from_turns( 10 - dist ) );
             }
             if( critter.has_flag( mon_flag_SEES ) && here.sees( critter.pos(), p, 8 ) ) {
                 critter.add_effect( effect_blind, time_duration::from_turns( 18 - dist ) );
             }
             if( critter.has_flag( mon_flag_HEARS ) ) {
                 critter.add_effect( effect_deaf, time_duration::from_turns( 60 - dist * 4 ) );
             }
         }
     }
     sounds::sound( p, 12, sounds::sound_t::combat, _( "a huge boom!" ), false, "misc", "flashbang" );
     // TODO: Blind/deafen NPC
 }
References _, Creature::add_effect(), Creature::add_env_effect(), c_white, sounds::combat, draw_explosion(), effect_blind, effect_deaf, effect_stunned, time_duration::from_turns(), g, get_map(), get_player_character(), Character::has_flag(), Character::has_trait(), Character::is_wearing(), itype_rm13_armor_on, json_flag_GLARE_RESIST, mon_flag_HEARS, mon_flag_SEES, one_in(), Creature::pos(), rl_dist(), map::sees(), sounds::sound(), species_ROBOT, STATIC, trait_PER_SLIME, trait_PER_SLIME_OK, and Character::worn_with_flag().
Referenced by Character::activate_bionic(), apply_ammo_effects(), spell_effect::flashbang(), trapfunc::glow(), and explosion_iuse::use().
gurney_spherical()
float explosion_handler::gurney_spherical (const double charge, const double mass)
Definition at line 168 of file explosion.cpp.
 {
     return static_cast<float>( std::pow( ( mass / charge ) + ( 3.0 / 5.0 ),
                                          -0.5 ) * TYPICAL_GURNEY_CONSTANT );
 }
References TYPICAL_GURNEY_CONSTANT.
Referenced by shrapnel().
mass_to_area()
static float explosion_handler::mass_to_area (const float mass) static
Definition at line 156 of file explosion.cpp.
 {
     // Density of steel in g/cm^3
     constexpr float steel_density = 7.85f;
     float fragment_volume = ( mass / 1000.0 ) / steel_density;
     float fragment_radius = std::cbrt( ( fragment_volume * 3.0f ) / ( 4.0f * M_PI ) );
     return fragment_radius * fragment_radius * M_PI;
 }
References M_PI.
Referenced by shrapnel().
nuke()
void explosion_handler::nuke (const tripoint_abs_omt & p)
Nuke the area at p - global overmap terrain coordinates!
Definition at line 804 of file explosion.cpp.
 {
     tinymap tmpmap;
     tmpmap.load( p, false );
     item mininuke( itype_mininuke_act );
     mininuke.set_flag( json_flag_ACTIVATE_ON_PLACE );
     tmpmap.add_item( { SEEX - 1, SEEY - 1, 0 }, mininuke );
     tmpmap.save();
 }
References tinymap::add_item(), itype_mininuke_act, json_flag_ACTIVATE_ON_PLACE, tinymap::load(), iuse::mininuke(), tinymap::save(), SEEX, and SEEY.
Referenced by computer_session::action_miss_launch().
process_explosions()
void explosion_handler::process_explosions ()
Definition at line 907 of file explosion.cpp.
 {
     for( const queued_explosion &ex : _explosions ) {
         const tripoint p = get_map().getlocal( ex.pos );
         if( p.x < 0 || p.x >= MAPSIZE_X || p.y < 0 || p.y >= MAPSIZE_Y ) {
             debugmsg( "Explosion origin (%d, %d, %d) is out-of-bounds", p.x, p.y, p.z );
             continue;
         }
         _make_explosion( ex.source, p, ex.data );
     }
     _explosions.clear();
 }
References _explosions, _make_explosion(), debugmsg, get_map(), map::getlocal(), MAPSIZE_X, MAPSIZE_Y, tripoint::x, tripoint::y, and tripoint::z.
Referenced by map::actualize().
resonance_cascade()
void explosion_handler::resonance_cascade (const tripoint & p)
Triggers a resonance cascade at p.
Definition at line 816 of file explosion.cpp.
 {
     Character &player_character = get_player_character();
     const time_duration maxglow = time_duration::from_turns( 100 - 5 * trig_dist( p,
                                   player_character.pos() ) );
     if( maxglow > 0_turns ) {
         const time_duration minglow = std::max( 0_turns, time_duration::from_turns( 60 - 5 * trig_dist( p,
                                                 player_character.pos() ) ) );
         player_character.add_effect( effect_teleglow, rng( minglow, maxglow ) * 100 );
     }
     int startx = p.x < 8 ? 0 : p.x - 8;
     int endx = p.x + 8 >= SEEX * 3 ? SEEX * 3 - 1 : p.x + 8;
     int starty = p.y < 8 ? 0 : p.y - 8;
     int endy = p.y + 8 >= SEEY * 3 ? SEEY * 3 - 1 : p.y + 8;
     tripoint dest( startx, starty, p.z );
     map &here = get_map();
     for( int &i = dest.x; i <= endx; i++ ) {
         for( int &j = dest.y; j <= endy; j++ ) {
             switch( rng( 1, 80 ) ) {
                 case 1:
                 case 2:
                     emp_blast( dest );
                     break;
                 case 3:
                 case 4:
                 case 5:
                     for( int k = i - 1; k <= i + 1; k++ ) {
                         for( int l = j - 1; l <= j + 1; l++ ) {
                             field_type_id type = fd_null;
                             switch( rng( 1, 7 ) ) {
                                 case 1:
                                     type = fd_blood;
                                     break;
                                 case 2:
                                     type = fd_bile;
                                     break;
                                 case 3:
                                 case 4:
                                     type = fd_slime;
                                     break;
                                 case 5:
                                     type = fd_fire;
                                     break;
                                 case 6:
                                 case 7:
                                     type = fd_nuke_gas;
                                     break;
                             }
                             if( !one_in( 3 ) ) {
                                 // TODO: fix point types
                                 here.add_field( tripoint_bub_ms{ k, l, p.z }, type, 3 );
                             }
                         }
                     }
                     break;
                 case  6:
                 case  7:
                 case  8:
                 case  9:
                 case 10:
                     here.trap_set( dest, tr_portal );
                     break;
                 case 11:
                 case 12:
                     here.trap_set( dest, tr_goo );
                     break;
                 case 13:
                 case 14:
                 case 15: {
                     std::vector<MonsterGroupResult> spawn_details =
                         MonsterGroupManager::GetResultFromGroup( GROUP_NETHER );
                     for( const MonsterGroupResult &mgr : spawn_details ) {
                         g->place_critter_at( mgr.name, dest );
                     }
                 }
                 break;
                 case 16:
                 case 17:
                 case 18:
                     here.destroy( dest );
                     break;
                 case 19:
                     explosion( &player_character, dest, rng( 1, 10 ), rng( 0, 1 ) * rng( 0, 6 ), one_in( 4 ) );
                     break;
                 default:
                     break;
             }
         }
     }
 }
References Creature::add_effect(), map::add_field(), map::destroy(), effect_teleglow, emp_blast(), explosion(), fd_bile, fd_blood, fd_fire, fd_nuke_gas, fd_null, fd_slime, time_duration::from_turns(), g, get_map(), get_player_character(), MonsterGroupManager::GetResultFromGroup(), GROUP_NETHER, max(), one_in(), Creature::pos(), rng(), SEEX, SEEY, tr_goo, tr_portal, map::trap_set(), trig_dist(), tripoint::x, tripoint::y, and tripoint::z.
Referenced by computer_session::action_cascade().
scrambler_blast()
void explosion_handler::scrambler_blast (const tripoint & p)
Triggers a scrambler blast at p.
Definition at line 645 of file explosion.cpp.
 {
     if( monster *const mon_ptr = get_creature_tracker().creature_at<monster>( p ) ) {
         monster &critter = *mon_ptr;
         if( critter.has_flag( mon_flag_ELECTRONIC ) ) {
             critter.make_friendly();
         }
         add_msg( m_warning, _( "The %s sparks and begins searching for a target!" ),
                  critter.name() );
     }
 }
References _, add_msg(), get_creature_tracker(), monster::has_flag(), m_warning, monster::make_friendly(), mon_flag_ELECTRONIC, and monster::name().
Referenced by explosion_iuse::use().
shockwave()
void explosion_handler::shockwave (const tripoint & p, int radius, int force, int stun, int dam_mult, bool ignore_player)
Definition at line 609 of file explosion.cpp.
 {
     draw_explosion( p, radius, c_blue );
     sounds::sound( p, force * force * dam_mult / 2, sounds::sound_t::combat, _( "Crack!" ), false,
                    "misc", "shockwave" );
     for( monster &critter : g->all_monsters() ) {
         if( critter.posz() != p.z ) {
             continue;
         }
         if( rl_dist( critter.pos(), p ) <= radius ) {
             add_msg( _( "%s is caught in the shockwave!" ), critter.name() );
             g->knockback( p, critter.pos(), force, stun, dam_mult );
         }
     }
     // TODO: combine the two loops and the case for avatar using all_creatures()
     for( npc &guy : g->all_npcs() ) {
         if( guy.posz() != p.z ) {
             continue;
         }
         if( rl_dist( guy.pos(), p ) <= radius ) {
             add_msg( _( "%s is caught in the shockwave!" ), guy.get_name() );
             g->knockback( p, guy.pos(), force, stun, dam_mult );
         }
     }
     Character &player_character = get_player_character();
     if( rl_dist( player_character.pos(), p ) <= radius && !ignore_player &&
         ( !player_character.has_trait( trait_LEG_TENT_BRACE ) ||
           !player_character.is_barefoot() ) ) {
         add_msg( m_bad, _( "You're caught in the shockwave!" ) );
         g->knockback( p, player_character.pos(), force, stun, dam_mult );
     }
 }
References _, add_msg(), c_blue, sounds::combat, draw_explosion(), force, g, get_player_character(), Character::has_trait(), Character::is_barefoot(), m_bad, Creature::pos(), rl_dist(), sounds::sound(), trait_LEG_TENT_BRACE, and tripoint::z.
Referenced by Character::activate_bionic().
shrapnel()
static std::vector<tripoint> explosion_handler::shrapnel (const Creature * source, const tripoint & src, int power, int casing_mass, float per_fragment_mass, int range = -1) static
Definition at line 384 of file explosion.cpp.
 {
     // The gurney equation wants the total mass of the casing.
     const float fragment_velocity = gurney_spherical( power, casing_mass );
     fragment_mass = per_fragment_mass;
     fragment_area = mass_to_area( fragment_mass );
     int fragment_count = casing_mass / fragment_mass;
     // Contains all tiles reached by fragments.
     std::vector<tripoint> distrib;
     projectile proj;
     proj.speed = fragment_velocity;
     proj.range = range;
     proj.proj_effects.insert( "NULL_SOURCE" );
     struct local_caches {
         cata::mdarray<fragment_cloud, point_bub_ms> obstacle_cache;
         cata::mdarray<fragment_cloud, point_bub_ms> visited_cache;
     };
     std::unique_ptr<local_caches> caches = std::make_unique<local_caches>();
     cata::mdarray<fragment_cloud, point_bub_ms> &obstacle_cache = caches->obstacle_cache;
     cata::mdarray<fragment_cloud, point_bub_ms> &visited_cache = caches->visited_cache;
     map &here = get_map();
     // TODO: Calculate range based on max effective range for projectiles.
     // Basically bisect between 0 and map diameter using shrapnel_calc().
     // Need to update shadowcasting to support limiting range without adjusting initial distance.
     const tripoint_range<tripoint> area = here.points_on_zlevel( src.z );
     here.build_obstacle_cache( area.min(), area.max() + tripoint_south_east, obstacle_cache );
     // Shadowcasting normally ignores the origin square,
     // so apply it manually to catch monsters standing on the explosive.
     // This "blocks" some fragments, but does not apply deceleration.
     fragment_cloud initial_cloud = accumulate_fragment_cloud( obstacle_cache[src.x][src.y],
     { fragment_velocity, static_cast<float>( fragment_count ) }, 1 );
     visited_cache[src.x][src.y] = initial_cloud;
     visited_cache[src.x][src.y].density = static_cast<float>( fragment_count / 2.0 );
     castLightAll<fragment_cloud, fragment_cloud, shrapnel_calc, shrapnel_check,
                  update_fragment_cloud, accumulate_fragment_cloud>
                  ( visited_cache, obstacle_cache, src.xy(), 0, initial_cloud );
     creature_tracker &creatures = get_creature_tracker();
     Creature *mutable_source = source == nullptr ? nullptr : creatures.creature_at( source->pos() );
     // Now visited_caches are populated with density and velocity of fragments.
     for( const tripoint &target : area ) {
         fragment_cloud &cloud = visited_cache[target.x][target.y];
         if( cloud.density <= MIN_FRAGMENT_DENSITY ||
             cloud.velocity <= MIN_EFFECTIVE_VELOCITY ) {
             continue;
         }
         distrib.emplace_back( target );
         int damage = ballistic_damage( cloud.velocity, fragment_mass );
         Creature *critter = creatures.creature_at( target );
         if( damage > 0 && critter && !critter->is_dead_state() ) {
             std::poisson_distribution<> d( cloud.density );
             int hits = d( rng_get_engine() );
             dealt_projectile_attack frag;
             frag.proj = proj;
             frag.proj.speed = cloud.velocity;
             frag.proj.impact = damage_instance( damage_bullet, damage );
             // dealt_dam.total_damage() == 0 means armor block
             // dealt_dam.total_damage() > 0 means took damage
             // Need to differentiate target among player, npc, and monster
             // Do we even print monster damage?
             int damage_taken = 0;
             int damaging_hits = 0;
             int non_damaging_hits = 0;
             for( int i = 0; i < hits; ++i ) {
                 frag.missed_by = rng_float( 0.05, 1.0 / critter->ranged_target_size() );
                 critter->deal_projectile_attack( mutable_source, frag, false );
                 if( frag.dealt_dam.total_damage() > 0 ) {
                     damaging_hits++;
                     damage_taken += frag.dealt_dam.total_damage();
                 } else {
                     non_damaging_hits++;
                 }
                 add_msg_debug( debugmode::DF_EXPLOSION, "Shrapnel hit %s at %d m/s at a distance of %d",
                                critter->disp_name(),
                                frag.proj.speed, rl_dist( src, target ) );
                 add_msg_debug( debugmode::DF_EXPLOSION, "Shrapnel dealt %d damage", frag.dealt_dam.total_damage() );
                 if( critter->is_dead_state() ) {
                     break;
                 }
             }
             int total_hits = damaging_hits + non_damaging_hits;
             multi_projectile_hit_message( critter, total_hits, damage_taken, n_gettext( "bomb fragment",
                                           "bomb fragments", total_hits ) );
         }
         if( here.impassable( target ) ) {
             if( optional_vpart_position vp = here.veh_at( target ) ) {
                 vp->vehicle().damage( here, vp->part_index(), damage / 10 );
             } else {
                 here.bash( target, damage / 100, true );
             }
         }
     }
     return distrib;
 }
References accumulate_fragment_cloud(), add_msg_debug, ballistic_damage(), map::bash(), map::build_obstacle_cache(), castLightAll(), damage_bullet, Creature::deal_projectile_attack(), fragment_cloud::density, debugmode::DF_EXPLOSION, Creature::disp_name(), mattack::frag(), fragment_area, fragment_mass, get_creature_tracker(), get_map(), gurney_spherical(), map::impassable(), Creature::is_dead_state(), mass_to_area(), tripoint_range< Tripoint >::max(), tripoint_range< Tripoint >::min(), MIN_EFFECTIVE_VELOCITY, MIN_FRAGMENT_DENSITY, multi_projectile_hit_message(), n_gettext, map::points_on_zlevel(), Creature::pos(), projectile::proj_effects, projectile::range, Creature::ranged_target_size(), rl_dist(), rng_float(), rng_get_engine(), shrapnel_calc(), shrapnel_check(), projectile::speed, tripoint_south_east, update_fragment_cloud(), map::veh_at(), fragment_cloud::velocity, tripoint::x, tripoint::xy(), tripoint::y, and tripoint::z.
Referenced by _make_explosion().
Variable Documentation
_explosions
std::vector<queued_explosion> explosion_handler::_explosions inline
Definition at line 70 of file explosion.h.
Referenced by explosion(), and process_explosions().
TYPICAL_GURNEY_CONSTANT
constexpr double explosion_handler::TYPICAL_GURNEY_CONSTANT = 2700.0 static constexpr
Definition at line 167 of file explosion.cpp.
Referenced by gurney_spherical().