Cataclysm DDA: units Namespace Reference
units Namespace Reference
Classes
class quantity
class volume_in_milliliter_tag
class mass_in_microgram_tag
class mass_in_milligram_tag
class specific_energy_in_joule_per_gram_tag
class temperature_in_kelvin_tag
class temperature_delta_in_kelvin_tag
class energy_in_millijoule_tag
class power_in_milliwatt_tag
class money_in_cent_tag
class length_in_millimeter_tag
class angle_in_radians_tag
Typedefs
using volume = quantity< int, volume_in_milliliter_tag >
using mass = quantity< std::int64_t, mass_in_milligram_tag >
using specific_energy = quantity< float, specific_energy_in_joule_per_gram_tag >
using temperature = quantity< float, temperature_in_kelvin_tag >
using temperature_delta = quantity< float, temperature_delta_in_kelvin_tag >
using energy = quantity< std::int64_t, energy_in_millijoule_tag >
using power = quantity< std::int64_t, power_in_milliwatt_tag >
using money = quantity< int, money_in_cent_tag >
using length = quantity< int, length_in_millimeter_tag >
using angle = quantity< double, angle_in_radians_tag >
Functions
std::string display (const units::energy &v)
std::string display (const units::power v)
units::energy operator* (const units::power &power, const time_duration &time)
units::energy operator* (const time_duration &time, const units::power &power)
units::power operator/ (const units::energy &energy, const time_duration &time)
time_duration operator/ (const units::energy &energy, const units::power &power)
units::temperature_delta operator- (const units::temperature &T1, const units::temperature &T2)
units::temperature operator+ (const units::temperature &T, const units::temperature_delta &T_delta)
units::temperature operator- (const units::temperature &T, const units::temperature_delta &T_delta)
units::temperature operator+ (const units::temperature_delta &T_delta, const units::temperature &T)
units::temperature & operator+= (units::temperature &T, const units::temperature_delta &T_delta)
template<typename V , typename U >
quantity< V, U > fabs (quantity< V, U > q)
template<typename V , typename U >
quantity< V, U > fmod (quantity< V, U > num, quantity< V, U > den)
template<typename value_type >
constexpr quantity< value_type, volume_in_milliliter_tag > from_milliliter (const value_type v)
template<typename value_type >
constexpr quantity< value_type, volume_in_milliliter_tag > from_liter (const value_type v)
template<typename value_type >
constexpr value_type to_milliliter (const quantity< value_type, volume_in_milliliter_tag > &v)
constexpr double to_liter (const volume &v)
template<typename value_type >
constexpr quantity< value_type, mass_in_milligram_tag > from_milligram (const value_type v)
template<typename value_type >
constexpr quantity< value_type, mass_in_milligram_tag > from_gram (const value_type v)
template<typename value_type >
constexpr quantity< value_type, mass_in_milligram_tag > from_kilogram (const value_type v)
template<typename value_type >
constexpr value_type to_milligram (const quantity< value_type, mass_in_milligram_tag > &v)
template<typename value_type >
constexpr value_type to_gram (const quantity< value_type, mass_in_milligram_tag > &v)
constexpr double to_kilogram (const mass &v)
template<typename value_type >
constexpr quantity< value_type, specific_energy_in_joule_per_gram_tag > from_joule_per_gram (const value_type v)
template<typename value_type >
constexpr value_type to_joule_per_gram (const quantity< value_type, specific_energy_in_joule_per_gram_tag > &v)
template<typename value_type >
constexpr quantity< units::temperature::value_type, temperature_in_kelvin_tag > from_kelvin (const value_type v)
template<typename value_type >
constexpr value_type to_kelvin (const quantity< value_type, temperature_in_kelvin_tag > &v)
template<typename value_type >
constexpr quantity< units::temperature::value_type, temperature_in_kelvin_tag > from_celsius (const value_type v)
template<typename value_type >
constexpr quantity< units::temperature::value_type, temperature_in_kelvin_tag > from_fahrenheit (const value_type v)
template<typename value_type >
constexpr value_type to_celsius (const quantity< value_type, temperature_in_kelvin_tag > &v)
template<typename value_type >
constexpr value_type to_fahrenheit (const quantity< value_type, temperature_in_kelvin_tag > &v)
constexpr units::temperature from_legacy_bodypart_temp (int temp)
template<typename value_type >
constexpr int to_legacy_bodypart_temp (const quantity< value_type, temperature_in_kelvin_tag > &v)
template<typename value_type >
constexpr quantity< units::temperature_delta::value_type, temperature_delta_in_kelvin_tag > from_kelvin_delta (const value_type v)
template<typename value_type >
constexpr value_type to_kelvin_delta (const quantity< value_type, temperature_delta_in_kelvin_tag > &v)
template<typename value_type >
constexpr quantity< units::temperature_delta::value_type, temperature_delta_in_kelvin_tag > from_celsius_delta (const value_type v)
template<typename value_type >
constexpr quantity< units::temperature_delta::value_type, temperature_delta_in_kelvin_tag > from_fahrenheit_delta (const value_type v)
template<typename value_type >
constexpr value_type to_celsius_delta (const quantity< value_type, temperature_delta_in_kelvin_tag > &v)
template<typename value_type >
constexpr value_type to_fahrenheit_delta (const quantity< value_type, temperature_delta_in_kelvin_tag > &v)
constexpr units::temperature_delta from_legacy_bodypart_temp_delta (int temp)
template<typename value_type >
constexpr int to_legacy_bodypart_temp_delta (const quantity< value_type, temperature_delta_in_kelvin_tag > &v)
template<typename value_type >
constexpr quantity< value_type, energy_in_millijoule_tag > from_millijoule (const value_type v)
template<typename value_type >
constexpr quantity< value_type, energy_in_millijoule_tag > from_joule (const value_type v)
template<typename value_type >
constexpr quantity< value_type, energy_in_millijoule_tag > from_kilojoule (const value_type v)
template<typename value_type >
constexpr value_type to_millijoule (const quantity< value_type, energy_in_millijoule_tag > &v)
template<typename value_type >
constexpr value_type to_joule (const quantity< value_type, energy_in_millijoule_tag > &v)
template<typename value_type >
constexpr value_type to_kilojoule (const quantity< value_type, energy_in_millijoule_tag > &v)
template<typename value_type >
constexpr quantity< value_type, power_in_milliwatt_tag > from_milliwatt (const value_type v)
template<typename value_type >
constexpr quantity< value_type, power_in_milliwatt_tag > from_watt (const value_type v)
template<typename value_type >
constexpr quantity< value_type, power_in_milliwatt_tag > from_kilowatt (const value_type v)
template<typename value_type >
constexpr value_type to_milliwatt (const quantity< value_type, power_in_milliwatt_tag > &v)
template<typename value_type >
constexpr value_type to_watt (const quantity< value_type, power_in_milliwatt_tag > &v)
template<typename value_type >
constexpr value_type to_kilowatt (const quantity< value_type, power_in_milliwatt_tag > &v)
template<typename value_type >
constexpr quantity< value_type, money_in_cent_tag > from_cent (const value_type v)
template<typename value_type >
constexpr quantity< value_type, money_in_cent_tag > from_usd (const value_type v)
template<typename value_type >
constexpr quantity< value_type, money_in_cent_tag > from_kusd (const value_type v)
template<typename value_type >
constexpr value_type to_cent (const quantity< value_type, money_in_cent_tag > &v)
template<typename value_type >
constexpr value_type to_usd (const quantity< value_type, money_in_cent_tag > &v)
template<typename value_type >
constexpr value_type to_kusd (const quantity< value_type, money_in_cent_tag > &v)
template<typename value_type >
constexpr quantity< value_type, length_in_millimeter_tag > from_millimeter (const value_type v)
template<typename value_type >
constexpr quantity< value_type, length_in_millimeter_tag > from_centimeter (const value_type v)
template<typename value_type >
constexpr quantity< value_type, length_in_millimeter_tag > from_meter (const value_type v)
template<typename value_type >
constexpr quantity< value_type, length_in_millimeter_tag > from_kilometer (const value_type v)
template<typename value_type >
constexpr value_type to_millimeter (const quantity< value_type, length_in_millimeter_tag > &v)
template<typename value_type >
constexpr value_type to_centimeter (const quantity< value_type, length_in_millimeter_tag > &v)
template<typename value_type >
constexpr value_type to_meter (const quantity< value_type, length_in_millimeter_tag > &v)
template<typename value_type >
constexpr value_type to_kilometer (const quantity< value_type, length_in_millimeter_tag > &v)
template<typename value_type >
constexpr quantity< value_type, angle_in_radians_tag > from_radians (const value_type v)
constexpr double to_radians (const units::angle v)
template<typename value_type >
constexpr quantity< double, angle_in_radians_tag > from_degrees (const value_type v)
constexpr double to_degrees (const units::angle v)
template<typename value_type >
constexpr quantity< double, angle_in_radians_tag > from_arcmin (const value_type v)
constexpr double to_arcmin (const units::angle v)
template<typename value_type >
constexpr quantity< value_type, length_in_millimeter_tag > default_length_from_volume (const quantity< value_type, volume_in_milliliter_tag > &v)
std::ostream & operator<< (std::ostream &o, mass_in_milligram_tag)
std::ostream & operator<< (std::ostream &o, volume_in_milliliter_tag)
std::ostream & operator<< (std::ostream &o, energy_in_millijoule_tag)
std::ostream & operator<< (std::ostream &o, power_in_milliwatt_tag)
std::ostream & operator<< (std::ostream &o, money_in_cent_tag)
std::ostream & operator<< (std::ostream &o, length_in_millimeter_tag)
std::ostream & operator<< (std::ostream &o, angle_in_radians_tag)
std::ostream & operator<< (std::ostream &o, temperature)
template<typename value_type , typename tag_type >
std::ostream & operator<< (std::ostream &o, const quantity< value_type, tag_type > &v)
template<typename value_type , typename tag_type >
std::string quantity_to_string (const quantity< value_type, tag_type > &v)
double sin (angle a)
double cos (angle a)
double tan (angle a)
double cot (angle a)
units::angle atan2 (double y, double x)
units::angle asin (double x)
units::angle acos (double x)
constexpr units::temperature_delta abs (units::temperature_delta x)
units::temperature operator+ (const units::temperature &, const units::temperature &)=delete
template<typename lvt , typename ut , typename st , typename = std::enable_if_t<std::is_arithmetic_v<st>>>
constexpr quantity< decltype(std::declval< lvt >) *std::declval< st >)), ut > operator* (const st &factor, const quantity< lvt, ut > &rhs)
Multiplication and division with scalars.
template<typename lvt , typename ut , typename st , typename = std::enable_if_t<std::is_arithmetic_v<st>>>
constexpr quantity< decltype(std::declval< st >) *std::declval< lvt >)), ut > operator* (const quantity< lvt, ut > &lhs, const st &factor)
template<typename lvt , typename ut , typename rvt , typename = std::enable_if_t<std::is_arithmetic_v<lvt>>>
void operator* (quantity< lvt, ut >, quantity< rvt, ut >)=delete
template<typename lvt , typename ut , typename st , typename = std::enable_if_t<std::is_arithmetic_v<st>>>
quantity< lvt, ut > & operator*= (quantity< lvt, ut > &lhs, const st &factor)
template<typename lvt , typename ut , typename rvt , typename = std::enable_if_t<std::is_arithmetic_v<rvt>>>
constexpr quantity< decltype(std::declval< lvt >) *std::declval< rvt >)), ut > operator/ (const quantity< lvt, ut > &lhs, const rvt &divisor)
template<typename lvt , typename ut , typename rvt , typename = std::enable_if_t<std::is_arithmetic_v<lvt>>>
void operator/ (lvt, quantity< rvt, ut >)=delete
template<typename lvt , typename ut , typename rvt >
constexpr decltype(std::declval< lvt >()/std::declval< rvt >()) operator/ (const quantity< lvt, ut > &lhs, const quantity< rvt, ut > &rhs)
template<typename lvt , typename ut , typename st , typename = std::enable_if_t<std::is_arithmetic_v<st>>>
quantity< lvt, ut > & operator/= (quantity< lvt, ut > &lhs, const st &divisor)
template<typename lvt , typename ut , typename rvt , typename = std::enable_if_t<std::is_arithmetic_v<rvt>>>
constexpr quantity< decltype(std::declval< lvt >) % std::declval< rvt >)), ut > operator% (const quantity< lvt, ut > &lhs, const rvt &divisor)
template<typename lvt , typename ut , typename rvt , typename = std::enable_if_t<std::is_arithmetic_v<lvt>>>
void operator% (lvt, quantity< rvt, ut >)=delete
template<typename lvt , typename ut , typename rvt >
constexpr quantity< decltype(std::declval< lvt >) % std::declval< rvt >)), ut > operator% (const quantity< lvt, ut > &lhs, const quantity< rvt, ut > &rhs)
template<typename lvt , typename ut , typename st , typename = std::enable_if_t<std::is_arithmetic_v<st>>>
quantity< lvt, ut > & operator%= (quantity< lvt, ut > &lhs, const st &divisor)
template<typename lvt , typename ut , typename rvt >
quantity< lvt, ut > & operator%= (quantity< lvt, ut > &lhs, const quantity< rvt, ut > &rhs)
Variables
const volume volume_min
const volume volume_max
constexpr volume legacy_volume_factor = from_milliliter(250)
const mass mass_min
const mass mass_max
const specific_energy specific_energy_min
const specific_energy specific_energy_max
const temperature temperature_min = units::temperature(0, units::temperature::unit_type{})
const temperature temperature_max
const temperature_delta temperature_delta_min
const temperature_delta temperature_delta_max
const energy energy_min
const energy energy_max
const power power_min
const power power_max
const money money_min
const money money_max
const length length_min
const length length_max
const std::vector< std::pair< std::string, energy > > energy_units
const std::vector< std::pair< std::string, power > > power_units
const std::vector< std::pair< std::string, mass > > mass_units
const std::vector< std::pair< std::string, money > > money_units
const std::vector< std::pair< std::string, volume > > volume_units
const std::vector< std::pair< std::string, length > > length_units
const std::vector< std::pair< std::string, angle > > angle_units
const std::vector< std::pair< std::string, temperature > > temperature_units
Typedef Documentation
angle
using units::angle = typedef quantity<double, angle_in_radians_tag>
Definition at line 75 of file units_fwd.h.
energy
using units::energy = typedef quantity<std::int64_t, energy_in_millijoule_tag>
Definition at line 51 of file units_fwd.h.
length
using units::length = typedef quantity<int, length_in_millimeter_tag>
Definition at line 69 of file units_fwd.h.
mass
using units::mass = typedef quantity<std::int64_t, mass_in_milligram_tag>
Definition at line 27 of file units_fwd.h.
money
using units::money = typedef quantity<int, money_in_cent_tag>
Definition at line 63 of file units_fwd.h.
power
using units::power = typedef quantity<std::int64_t, power_in_milliwatt_tag>
Definition at line 57 of file units_fwd.h.
specific_energy
using units::specific_energy = typedef quantity<float, specific_energy_in_joule_per_gram_tag>
Definition at line 33 of file units_fwd.h.
temperature
using units::temperature = typedef quantity<float, temperature_in_kelvin_tag>
Definition at line 39 of file units_fwd.h.
temperature_delta
using units::temperature_delta = typedef quantity<float, temperature_delta_in_kelvin_tag>
Definition at line 45 of file units_fwd.h.
volume
using units::volume = typedef quantity<int, volume_in_milliliter_tag>
Definition at line 17 of file units_fwd.h.
Function Documentation
abs()
constexpr units::temperature_delta units::abs (units::temperature_delta x) inline constexpr
Definition at line 1190 of file units.h.
 {
     return from_kelvin_delta( std::abs( to_kelvin_delta( x ) ) );
 }
References abs(), from_kelvin_delta(), and to_kelvin_delta().
Referenced by temp_delta(), and Character::update_bodytemp().
acos()
units::angle units::acos (double x) inline
Definition at line 1132 of file units.h.
 {
     return from_radians( std::acos( x ) );
 }
References from_radians().
Referenced by offset_to_sun_altitude(), and avatar::rebuild_aim_cache().
asin()
units::angle units::asin (double x) inline
Definition at line 1127 of file units.h.
 {
     return from_radians( std::asin( x ) );
 }
References from_radians().
Referenced by sun_azimuth_altitude(), and sun_ra_declination().
atan2()
units::angle units::atan2 (double y, double x) inline
Definition at line 1122 of file units.h.
 {
     return from_radians( std::atan2( y, x ) );
 }
References from_radians().
Referenced by atan2(), coord_to_angle(), vehicle::get_angle_from_targ(), and projectile_attack().
cos()
double units::cos (angle a) inline
Definition at line 1107 of file units.h.
 {
     return std::cos( to_radians( a ) );
 }
References a, cos(), and to_radians().
Referenced by angle_to_vec(), tileray::init(), and npc::vehicle_danger().
cot()
double units::cot (angle a) inline
Definition at line 1117 of file units.h.
 {
     return std::tan( M_PI_2 - to_radians( a ) );
 }
References a, M_PI_2, tan(), and to_radians().
default_length_from_volume()
template<typename value_type > constexpr quantity<value_type, length_in_millimeter_tag> units::default_length_from_volume (const quantity< value_type, volume_in_milliliter_tag > & v) inline constexpr
Definition at line 775 of file units.h.
 {
     return units::from_centimeter<int>(
         std::round(
             std::cbrt( units::to_milliliter( v ) ) ) );
 }
References round(), and to_milliliter().
Referenced by pocket_data::load().
display() [1/2]
std::string units::display (const units::energy & v)
Definition at line 131 of file units.cpp.
 {
     using value_type = units::energy::value_type;
     const value_type kj = units::to_kilojoule( v );
     const value_type j = units::to_joule( v );
     // at least 1 kJ and there is no fraction
     if( kj >= 1 && static_cast<double>( j ) / kj == 1000 ) {
         return std::to_string( kj ) + ' ' + pgettext( "energy unit: kilojoule", "kJ" );
     }
     const value_type mj = units::to_millijoule( v );
     // at least 1 J and there is no fraction
     if( j >= 1 && static_cast<double>( mj ) / j  == 1000 ) {
         return std::to_string( j ) + ' ' + pgettext( "energy unit: joule", "J" );
     }
     return std::to_string( mj ) + ' ' + pgettext( "energy unit: millijoule", "mJ" );
 }
References pgettext, to_joule(), to_kilojoule(), to_millijoule(), and to_string().
Referenced by Character::activate_bionic(), build_bionic_poweronly_string(), item::gun_info(), and debug_menu::wishbionics().
display() [2/2]
std::string units::display (const units::power v)
Definition at line 148 of file units.cpp.
 {
     const int kw = units::to_kilowatt( v );
     const int w = units::to_watt( v );
     // at least 1 kW and there is no fraction
     if( kw >= 1 && static_cast<float>( w ) / kw == 1000 ) {
         return std::to_string( kw ) + ' ' + pgettext( "energy unit: kilowatt", "kW" );
     }
     const int mw = units::to_milliwatt( v );
     // at least 1 W and there is no fraction
     if( w >= 1 && static_cast<float>( mw ) / w == 1000 ) {
         return std::to_string( w ) + ' ' + pgettext( "energy unit: watt", "W" );
     }
     return std::to_string( mw ) + ' ' + pgettext( "energy unit: milliwatt", "mW" );
 }
References pgettext, to_kilowatt(), to_milliwatt(), to_string(), and to_watt().
fabs()
template<typename V , typename U > quantity<V, U> units::fabs (quantity< V, U > q) inline
Definition at line 147 of file units.h.
 {
     return quantity<V, U>( std::fabs( q.value() ), U{} );
 }
References units::quantity< V, U >::value().
Referenced by Character::apply_wetness_morale(), Creature::auto_find_hostile_target(), game::calc_driving_offset(), game::draw_minimap(), display::mission_arrow_offset(), vehicle::noise_and_smoke(), vehicle::part_collision(), vehicle::possibly_recover_from_skid(), mattack::shriek_stun(), and npc::wont_hit_friend().
fmod()
template<typename V , typename U > quantity<V, U> units::fmod (quantity< V, U > num, quantity< V, U > den) inline
Definition at line 153 of file units.h.
 {
     return quantity<V, U>( std::fmod( num.value(), den.value() ), U{} );
 }
References units::quantity< V, U >::value().
Referenced by eoc_math::act(), map::apply_light_arc(), calc_ray_end(), material_type::is_valid_thickness(), vehicle::merge_rackable_vehicle(), math_opers::mod(), normalize(), and Character::practice_proficiency().
from_arcmin()
template<typename value_type > constexpr quantity<double, angle_in_radians_tag> units::from_arcmin (const value_type v) inline constexpr
Definition at line 763 of file units.h.
 {
     return from_degrees( v / 60.0 );
 }
References from_degrees().
Referenced by confidence_estimate(), operator""_arcmin(), projectile_attack(), and projectile_attack_roll().
from_celsius()
template<typename value_type > constexpr quantity<units::temperature::value_type, temperature_in_kelvin_tag> units::from_celsius (const value_type v) inline constexpr
Definition at line 418 of file units.h.
 {
     return from_kelvin( v + 273.150f );
 }
References from_kelvin().
Referenced by iuse::blood_draw(), celsius_to_kelvin(), item::cold_up(), debug_menu::debug_menu_force_temperature(), milk_activity_actor::finish(), from_legacy_bodypart_temp(), item::get_freeze_point(), item::heat_up(), tutorial_game::init(), make_mon_corpse(), operator""_C(), Character::place_corpse(), set_temp_rot(), and weather_temperature_from_common_data().
from_celsius_delta()
template<typename value_type > constexpr quantity<units::temperature_delta::value_type, temperature_delta_in_kelvin_tag> units::from_celsius_delta (const value_type v) inline constexpr
Definition at line 487 of file units.h.
 {
     return from_kelvin_delta( v );
 }
References from_kelvin_delta().
Referenced by eff_fun_sleep(), operator""_C_delta(), and Character::update_bodytemp().
from_cent()
template<typename value_type > constexpr quantity<value_type, money_in_cent_tag> units::from_cent (const value_type v) inline constexpr
Definition at line 646 of file units.h.
 {
     return quantity<value_type, money_in_cent_tag>( v, money_in_cent_tag{} );
 }
Referenced by assign(), and operator""_cent().
from_centimeter()
template<typename value_type > constexpr quantity<value_type, length_in_millimeter_tag> units::from_centimeter (const value_type v) inline constexpr
Definition at line 696 of file units.h.
 {
     return from_millimeter<value_type>( v * 10 );
 }
Referenced by operator""_cm().
from_degrees()
template<typename value_type > constexpr quantity<double, angle_in_radians_tag> units::from_degrees (const value_type v) inline constexpr
Definition at line 752 of file units.h.
 {
     return from_radians( v * M_PI / 180 );
 }
References from_radians(), and M_PI.
Referenced by Creature::auto_find_hostile_target(), vehicle_part::carried_part_data::deserialize(), vehicle_part::deserialize(), vehicle::deserialize(), mm_submap::deserialize(), from_arcmin(), item::getlight(), jmapgen_vehicle::jmapgen_vehicle(), operator""_degrees(), vehicle::part_collision(), calendar::set_location(), spell_effect_cone_range_override(), teleport::teleport_to_point(), to_angle(), and VehicleFacings::VehicleFacings().
from_fahrenheit()
template<typename value_type > constexpr quantity<units::temperature::value_type, temperature_in_kelvin_tag> units::from_fahrenheit (const value_type v) inline constexpr
Definition at line 426 of file units.h.
 {
     return from_kelvin( ( v + 459.67f ) / 1.8f );
 }
References from_kelvin().
Referenced by item::calc_hourly_rotpoints_at_temp(), debug_menu::debug_menu_force_temperature(), fahrenheit_to_kelvin(), weather_generator::get_water_temperature(), bodygraph_display::prepare_infotext(), weather_manager::unserialize_all(), and warm_enough_to_plant().
from_fahrenheit_delta()
template<typename value_type > constexpr quantity<units::temperature_delta::value_type, temperature_delta_in_kelvin_tag> units::from_fahrenheit_delta (const value_type v) inline constexpr
Definition at line 495 of file units.h.
 {
     return from_kelvin_delta( v / 1.8f );
 }
References from_kelvin_delta().
Referenced by map::draw_lab(), get_convection_temperature(), get_heat_radiation(), submap::get_temperature_mod(), item::process_temperature_rot(), and Character::update_bodytemp().
from_gram()
template<typename value_type > constexpr quantity<value_type, mass_in_milligram_tag> units::from_gram (const value_type v) inline constexpr
Definition at line 344 of file units.h.
 {
     return from_milligram( v * 1000 );
 }
References from_milligram().
Referenced by from_kilogram(), inventory_selector::get_weight_and_length_stat(), Character::masticated_volume(), operator""_gram(), item::weight(), and outfit::where_discomfort().
from_joule()
template<typename value_type > constexpr quantity<value_type, energy_in_millijoule_tag> units::from_joule (const value_type v) inline constexpr
Definition at line 545 of file units.h.
 {
     const value_type max_energy_joules = std::numeric_limits<value_type>::max() / 1000;
     // Check for overflow - if the energy provided is greater than max energy, then it
     // if overflow when converted to millijoules
     const value_type energy = v > max_energy_joules ? max_energy_joules : v;
     return from_millijoule<value_type>( energy * 1000 );
 }
References max().
Referenced by Character::burn_fuel(), operator""_J(), and debug_menu::wishbionics().
from_joule_per_gram()
template<typename value_type > constexpr quantity<value_type, specific_energy_in_joule_per_gram_tag> units::from_joule_per_gram (const value_type v) inline constexpr
Definition at line 383 of file units.h.
 {
     return quantity<value_type, specific_energy_in_joule_per_gram_tag>( v,
             specific_energy_in_joule_per_gram_tag{} );
 }
Referenced by item::calc_temp(), item::combine(), item::get_specific_energy_from_temperature(), and item::io().
from_kelvin()
template<typename value_type > constexpr quantity<units::temperature::value_type, temperature_in_kelvin_tag> units::from_kelvin (const value_type v) inline constexpr
Definition at line 404 of file units.h.
 {
     return quantity<value_type, temperature_in_kelvin_tag>( v, temperature_in_kelvin_tag{} );
 }
Referenced by iuse::blood_draw(), item::calc_temp(), celsius_from_kelvin(), debug_menu::debug_menu_force_temperature(), fahrenheit_from_kelvin(), from_celsius(), from_fahrenheit(), item::io(), operator""_K(), operator+(), operator-(), item::set_item_specific_energy(), to_celsius(), to_fahrenheit(), and anonymous_namespace{math_parser_diag.cpp}::weather_ass().
from_kelvin_delta()
template<typename value_type > constexpr quantity<units::temperature_delta::value_type, temperature_delta_in_kelvin_tag> units::from_kelvin_delta (const value_type v) inline constexpr
Definition at line 472 of file units.h.
 {
     return quantity<value_type, temperature_delta_in_kelvin_tag>( v, temperature_delta_in_kelvin_tag{} );
 }
Referenced by abs(), Character::floor_warmth(), from_celsius_delta(), from_fahrenheit_delta(), from_legacy_bodypart_temp_delta(), get_convection_temperature(), get_heat_radiation(), get_local_windchill(), map::get_temperature_mod(), operator-(), item::process_temperature_rot(), and Character::update_bodytemp().
from_kilogram()
template<typename value_type > constexpr quantity<value_type, mass_in_milligram_tag> units::from_kilogram (const value_type v) inline constexpr
Definition at line 351 of file units.h.
 {
     return from_gram( v * 1000 );
 }
References from_gram().
Referenced by Character::bodyweight_fat(), Character::bodyweight_lean(), Character::burn_move_stamina(), operator""_kilogram(), and item::weight().
from_kilojoule()
template<typename value_type > constexpr quantity<value_type, energy_in_millijoule_tag> units::from_kilojoule (const value_type v) inline constexpr
Definition at line 555 of file units.h.
 {
     const value_type max_energy_joules = std::numeric_limits<value_type>::max() / 1000;
     // This checks for value_type overflow - if the energy we are given in Joules is greater
     // than the max energy in Joules, overflow will occur when it is converted to millijoules
     // The value we are given is in kJ, multiply by 1000 to convert it to joules, for use in from_joule
     value_type energy = v * 1000 > max_energy_joules ? max_energy_joules : v * 1000;
     return from_joule<value_type>( energy );
 }
References max().
Referenced by Character::activate_bionic(), item::ammo_consume(), item_contents::ammo_consume(), Character::armor_absorb(), Character::available_ups(), npc::check_or_use_weapon_cbm(), vehicle::consume_fuel(), Character::consume_tools(), eat(), explosion_handler::emp_blast(), item::energy_consume(), item::energy_remaining(), Character::fun_for(), known_magic::has_enough_energy(), move_mode::mech_power_use(), operator""_kJ(), turret_data::query(), spell_effect::recover_energy(), activity_handlers::spellcasting_finish(), Character::update_stamina(), Character::use_charges(), monster::use_mech_power(), and debug_menu::wishbionics().
from_kilometer()
template<typename value_type > constexpr quantity<value_type, length_in_millimeter_tag> units::from_kilometer (const value_type v) inline constexpr
Definition at line 710 of file units.h.
 {
     return from_millimeter<value_type>( v * 1000000 );
 }
Referenced by operator""_km().
from_kilowatt()
template<typename value_type > constexpr quantity<value_type, power_in_milliwatt_tag> units::from_kilowatt (const value_type v) inline constexpr
Definition at line 609 of file units.h.
 {
     constexpr value_type max_power_watts = std::numeric_limits<value_type>::max() / 1000;
     // This checks for value_type overflow - if the power we are given in watts is greater
     // than the max power in watts, overflow will occur when it is converted to milliwatts
     // The value we are given is in kilowatts, multiply by 1000 to convert it to watts, for use in from_watt
     value_type power = v * 1000 > max_power_watts ? max_power_watts : v * 1000;
     return from_watt<value_type>( power );
 }
References max().
Referenced by vehicle::active_reactor_epower(), and operator""_kW().
from_kusd()
template<typename value_type > constexpr quantity<value_type, money_in_cent_tag> units::from_kusd (const value_type v) inline constexpr
Definition at line 659 of file units.h.
 {
     return from_usd<value_type>( v * 1000 );
 }
Referenced by operator""_kUSD().
from_legacy_bodypart_temp()
constexpr units::temperature units::from_legacy_bodypart_temp (int temp) inline constexpr
Definition at line 448 of file units.h.
 {
     return units::from_celsius( 37.0 + ( temp - 5000.0 ) * 0.002 );
 }
References from_celsius(), and temp.
Referenced by bodypart::deserialize().
from_legacy_bodypart_temp_delta()
constexpr units::temperature_delta units::from_legacy_bodypart_temp_delta (int temp) inline constexpr
Definition at line 517 of file units.h.
 {
     return units::from_kelvin_delta( temp * 0.002 );
 }
References from_kelvin_delta(), and temp.
Referenced by mutation_branch::load(), vpart_info::load(), ter_t::load(), furn_t::load(), body_part_type::load(), and trap::load().
from_liter()
template<typename value_type > constexpr quantity<value_type, volume_in_milliliter_tag> units::from_liter (const value_type v) inline constexpr
Definition at line 310 of file units.h.
 {
     return from_milliliter<value_type>( v * 1000 );
 }
Referenced by iexamine::compost_empty(), activity_handlers::fill_liquid_do_turn(), iexamine::fvat_empty(), and iexamine::gaspump().
from_meter()
template<typename value_type > constexpr quantity<value_type, length_in_millimeter_tag> units::from_meter (const value_type v) inline constexpr
Definition at line 703 of file units.h.
 {
     return from_millimeter<value_type>( v * 1000 );
 }
Referenced by operator""_meter().
from_milligram()
template<typename value_type > constexpr quantity<value_type, mass_in_milligram_tag> units::from_milligram (const value_type v) inline constexpr
Definition at line 337 of file units.h.
 {
     return quantity<value_type, mass_in_milligram_tag>( v, mass_in_milligram_tag{} );
 }
Referenced by from_gram(), operator""_milligram(), and item::weight().
from_millijoule()
template<typename value_type > constexpr quantity<value_type, energy_in_millijoule_tag> units::from_millijoule (const value_type v) inline constexpr
Definition at line 538 of file units.h.
 {
     return quantity<value_type, energy_in_millijoule_tag>( v, energy_in_millijoule_tag{} );
 }
Referenced by Character::burn_energy_all(), Character::burn_energy_arms(), Character::burn_energy_legs(), operator""_mJ(), operator*(), and display::power_balance_text_color().
from_milliliter()
template<typename value_type > constexpr quantity<value_type, volume_in_milliliter_tag> units::from_milliliter (const value_type v) inline constexpr
Definition at line 303 of file units.h.
 {
     return quantity<value_type, volume_in_milliliter_tag>( v, volume_in_milliliter_tag{} );
 }
Referenced by mattack::absorb_items(), Item_factory::finalize_pre(), inventory_selector::get_volume_stat(), Character::masticated_volume(), operator""_liter(), operator""_ml(), game_menus::inv::smoke_food(), and string_to_ml().
from_millimeter()
template<typename value_type > constexpr quantity<value_type, length_in_millimeter_tag> units::from_millimeter (const value_type v) inline constexpr
Definition at line 689 of file units.h.
 {
     return quantity<value_type, length_in_millimeter_tag>( v, length_in_millimeter_tag{} );
 }
Referenced by operator""_mm().
from_milliwatt()
template<typename value_type > constexpr quantity<value_type, power_in_milliwatt_tag> units::from_milliwatt (const value_type v) inline constexpr
Definition at line 592 of file units.h.
 {
     return quantity<value_type, power_in_milliwatt_tag>( v, power_in_milliwatt_tag{} );
 }
Referenced by operator""_mW(), operator/(), item::process_link(), and link_up_actor::use().
from_radians()
template<typename value_type > constexpr quantity<value_type, angle_in_radians_tag> units::from_radians (const value_type v) inline constexpr
Definition at line 741 of file units.h.
 {
     return quantity<value_type, angle_in_radians_tag>( v, angle_in_radians_tag{} );
 }
Referenced by acos(), approx_orientation(), asin(), atan2(), from_degrees(), operator""_pi_radians(), and operator""_radians().
from_usd()
template<typename value_type > constexpr quantity<value_type, money_in_cent_tag> units::from_usd (const value_type v) inline constexpr
Definition at line 653 of file units.h.
 {
     return from_cent<value_type>( v * 100 );
 }
Referenced by operator""_USD().
from_watt()
template<typename value_type > constexpr quantity<value_type, power_in_milliwatt_tag> units::from_watt (const value_type v) inline constexpr
Definition at line 599 of file units.h.
 {
     constexpr value_type max_power_watts = std::numeric_limits<value_type>::max() / 1000;
     // Check for overflow - if the power provided is greater than max power, then it
     // will overflow when converted to milliwatt
     const value_type power = v > max_power_watts ? max_power_watts : v;
     return from_milliwatt<value_type>( power * 1000 );
 }
References max().
Referenced by operator""_W(), vehicle::part_vpower_w(), and vehicle::smart_controller_handle_turn().
operator%() [1/3]
template<typename lvt , typename ut , typename rvt > constexpr quantity< decltype(std::declval<lvt>) % std::declval<rvt>)), ut > units::operator% (const quantity< lvt, ut > & lhs, const quantity< rvt, ut > & rhs) inline constexpr
Definition at line 274 of file units.h.
 {
     return { lhs.value() % rhs.value(), ut{} };
 }
References units::quantity< V, U >::value().
operator%() [2/3]
template<typename lvt , typename ut , typename rvt , typename = std::enable_if_t<std::is_arithmetic_v<rvt>>> constexpr quantity< decltype(std::declval<lvt>) % std::declval<rvt>)), ut > units::operator% (const quantity< lvt, ut > & lhs, const rvt & divisor) inline constexpr
Definition at line 262 of file units.h.
 {
     return { lhs.value() % divisor, ut{} };
 }
References units::quantity< V, U >::value().
operator%() [3/3]
template<typename lvt , typename ut , typename rvt , typename = std::enable_if_t<std::is_arithmetic_v<lvt>>> void units::operator% (lvt , quantity< rvt, ut >) inline delete
operator%=() [1/2]
template<typename lvt , typename ut , typename rvt > quantity<lvt, ut>& units::operator%= (quantity< lvt, ut > & lhs, const quantity< rvt, ut > & rhs) inline
Definition at line 289 of file units.h.
 {
     lhs = lhs % rhs;
     return lhs;
 }
operator%=() [2/2]
template<typename lvt , typename ut , typename st , typename = std::enable_if_t<std::is_arithmetic_v<st>>> quantity<lvt, ut>& units::operator%= (quantity< lvt, ut > & lhs, const st & divisor) inline
Definition at line 282 of file units.h.
 {
     lhs = lhs % divisor;
     return lhs;
 }
operator*() [1/5]
template<typename lvt , typename ut , typename st , typename = std::enable_if_t<std::is_arithmetic_v<st>>> constexpr quantity<decltype(std::declval<st>) * std::declval<lvt>)), ut> units::operator* (const quantity< lvt, ut > & lhs, const st & factor) inline constexpr
Definition at line 210 of file units.h.
 {
     return { lhs.value() *factor, ut{} };
 }
References units::quantity< V, U >::value().
operator*() [2/5]
template<typename lvt , typename ut , typename st , typename = std::enable_if_t<std::is_arithmetic_v<st>>> constexpr quantity<decltype(std::declval<lvt>) * std::declval<st>)), ut> units::operator* (const st & factor, const quantity< lvt, ut > & rhs) inline constexpr
Multiplication and division with scalars.
Result is a quantity with the same unit as the input. Functions are templated to allow scaling with different types:
quantity<int, foo> a{ 10, foo{} };
auto b = a * 4.52;
static_assert(std::is_same<decltype(b), quantity<double, foo>>::value);
Note that the result for *= and /= is calculated using the given types, but is implicitly converted back to value_type as it is stored in the operand.
quantity<int, foo> a{ 10, foo{} };
a *= 4.52;
cata_assert(a == quantity<int, foo>(10 * 4.52, foo{}));
cata_assert(a != quantity<int, foo>(10 * (int)4.52, foo{}));
cata_assert(a == quantity<int, foo>(45, foo{}));
Division of a quantity with a quantity of the same unit yields a dimensionless scalar value, with the same type as the division of the contained value_types:
quantity<int, foo> a{ 10, foo{} };
quantity<double, foo> b{ 20, foo{} };
auto proportion = a / b;
static_assert(std::is_same<decltype(proportion), double>::value);
cata_assert(proportion == 10 / 20.0);
Definition at line 202 of file units.h.
 {
     return { factor * rhs.value(), ut{} };
 }
References units::quantity< V, U >::value().
operator*() [3/5]
units::energy units::operator* (const time_duration & time, const units::power & power)
Definition at line 171 of file units.cpp.
 {
     return power * time;
 }
operator*() [4/5]
units::energy units::operator* (const units::power & power, const time_duration & time)
Definition at line 164 of file units.cpp.
 {
     const int64_t mW = units::to_milliwatt<int64_t>( power );
     const int64_t seconds = to_seconds<int64_t>( time );
     return units::from_millijoule( mW * seconds );
 }
References from_millijoule().
Referenced by monster::get_volume(), and monster::get_weight().
operator*() [5/5]
template<typename lvt , typename ut , typename rvt , typename = std::enable_if_t<std::is_arithmetic_v<lvt>>> void units::operator* (quantity< lvt, ut > , quantity< rvt, ut >) inline delete
operator*=()
template<typename lvt , typename ut , typename st , typename = std::enable_if_t<std::is_arithmetic_v<st>>> quantity<lvt, ut>& units::operator*= (quantity< lvt, ut > & lhs, const st & factor) inline
Definition at line 222 of file units.h.
 {
     lhs = lhs * factor;
     return lhs;
 }
operator+() [1/3]
units::temperature units::operator+ (const units::temperature & , const units::temperature &) delete
operator+() [2/3]
units::temperature units::operator+ (const units::temperature & T, const units::temperature_delta & T_delta)
Definition at line 195 of file units.cpp.
 {
     return from_kelvin( to_kelvin( T ) + to_kelvin_delta( T_delta ) );
 }
References from_kelvin(), to_kelvin(), and to_kelvin_delta().
operator+() [3/3]
units::temperature units::operator+ (const units::temperature_delta & T_delta, const units::temperature & T)
Definition at line 205 of file units.cpp.
 {
     return from_kelvin( to_kelvin( T ) + to_kelvin_delta( T_delta ) );
 }
References from_kelvin(), to_kelvin(), and to_kelvin_delta().
operator+=()
units::temperature & units::operator+= (units::temperature & T, const units::temperature_delta & T_delta)
Definition at line 210 of file units.cpp.
 {
     T = T + T_delta;
     return T;
 }
operator-() [1/2]
units::temperature units::operator- (const units::temperature & T, const units::temperature_delta & T_delta)
Definition at line 200 of file units.cpp.
 {
     return from_kelvin( to_kelvin( T ) - to_kelvin_delta( T_delta ) );
 }
References from_kelvin(), to_kelvin(), and to_kelvin_delta().
operator-() [2/2]
units::temperature_delta units::operator- (const units::temperature & T1, const units::temperature & T2)
Definition at line 190 of file units.cpp.
 {
     return from_kelvin_delta( to_kelvin( T1 ) - to_kelvin( T2 ) );
 }
References from_kelvin_delta(), and to_kelvin().
operator/() [1/5]
template<typename lvt , typename ut , typename rvt > constexpr decltype(std::declval<lvt>() / std::declval<rvt>()) units::operator/ (const quantity< lvt, ut > & lhs, const quantity< rvt, ut > & rhs) inline constexpr
Definition at line 244 of file units.h.
 {
     return lhs.value() / rhs.value();
 }
References units::quantity< V, U >::value().
operator/() [2/5]
template<typename lvt , typename ut , typename rvt , typename = std::enable_if_t<std::is_arithmetic_v<rvt>>> constexpr quantity<decltype(std::declval<lvt>) * std::declval<rvt>)), ut> units::operator/ (const quantity< lvt, ut > & lhs, const rvt & divisor) inline constexpr
Definition at line 232 of file units.h.
 {
     return { lhs.value() / divisor, ut{} };
 }
References units::quantity< V, U >::value().
operator/() [3/5]
units::power units::operator/ (const units::energy & energy, const time_duration & time)
Definition at line 176 of file units.cpp.
 {
     const int64_t mj = to_millijoule( energy );
     const int64_t seconds = to_seconds<int64_t>( time );
     return from_milliwatt( mj / seconds );
 }
References from_milliwatt(), and to_millijoule().
operator/() [4/5]
time_duration units::operator/ (const units::energy & energy, const units::power & power)
Definition at line 183 of file units.cpp.
 {
     const int64_t mj = to_millijoule( energy );
     const int64_t mw = to_milliwatt( power );
     return time_duration::from_seconds( mj / mw );
 }
References time_duration::from_seconds(), to_millijoule(), and to_milliwatt().
operator/() [5/5]
template<typename lvt , typename ut , typename rvt , typename = std::enable_if_t<std::is_arithmetic_v<lvt>>> void units::operator/ (lvt , quantity< rvt, ut >) inline delete
operator/=()
template<typename lvt , typename ut , typename st , typename = std::enable_if_t<std::is_arithmetic_v<st>>> quantity<lvt, ut>& units::operator/= (quantity< lvt, ut > & lhs, const st & divisor) inline
Definition at line 252 of file units.h.
 {
     lhs = lhs / divisor;
     return lhs;
 }
operator<<() [1/9]
std::ostream& units::operator<< (std::ostream & o, angle_in_radians_tag) inline
Definition at line 816 of file units.h.
 {
     return o << "rad";
 }
operator<<() [2/9]
template<typename value_type , typename tag_type > std::ostream& units::operator<< (std::ostream & o, const quantity< value_type, tag_type > & v) inline
Definition at line 827 of file units.h.
 {
     return o << v.value() << tag_type{};
 }
References units::quantity< V, U >::value().
operator<<() [3/9]
std::ostream& units::operator<< (std::ostream & o, energy_in_millijoule_tag) inline
Definition at line 796 of file units.h.
 {
     return o << "mJ";
 }
operator<<() [4/9]
std::ostream& units::operator<< (std::ostream & o, length_in_millimeter_tag) inline
Definition at line 811 of file units.h.
 {
     return o << "mm";
 }
operator<<() [5/9]
std::ostream& units::operator<< (std::ostream & o, mass_in_milligram_tag) inline
Definition at line 786 of file units.h.
 {
     return o << "mg";
 }
operator<<() [6/9]
std::ostream& units::operator<< (std::ostream & o, money_in_cent_tag) inline
Definition at line 806 of file units.h.
 {
     return o << "cent";
 }
operator<<() [7/9]
std::ostream& units::operator<< (std::ostream & o, power_in_milliwatt_tag) inline
Definition at line 801 of file units.h.
 {
     return o << "mW";
 }
operator<<() [8/9]
std::ostream& units::operator<< (std::ostream & o, temperature) inline
Definition at line 821 of file units.h.
 {
     return o << "K";
 }
operator<<() [9/9]
std::ostream& units::operator<< (std::ostream & o, volume_in_milliliter_tag) inline
Definition at line 791 of file units.h.
 {
     return o << "ml";
 }
quantity_to_string()
template<typename value_type , typename tag_type > std::string units::quantity_to_string (const quantity< value_type, tag_type > & v) inline
Definition at line 833 of file units.h.
 {
     std::ostringstream os;
     os << v;
     return os.str();
 }
Referenced by pocket_data::check_definition().
sin()
double units::sin (angle a) inline
Definition at line 1102 of file units.h.
 {
     return std::sin( to_radians( a ) );
 }
References a, sin(), and to_radians().
Referenced by angle_to_vec(), tileray::init(), vehicle::slowdown(), and npc::vehicle_danger().
tan()
double units::tan (angle a) inline
Definition at line 1112 of file units.h.
 {
     return std::tan( to_radians( a ) );
 }
References a, tan(), and to_radians().
to_arcmin()
constexpr double units::to_arcmin (const units::angle v) inline constexpr
Definition at line 768 of file units.h.
 {
     return to_degrees( v ) * 60;
 }
References to_degrees().
to_celsius()
template<typename value_type > constexpr value_type units::to_celsius (const quantity< value_type, temperature_in_kelvin_tag > & v) inline constexpr
Definition at line 433 of file units.h.
 {
     return ( v - from_kelvin( 273.150f ) ).value();
 }
References from_kelvin().
Referenced by celsius_from_kelvin(), debug_menu::debug_menu_force_temperature(), eff_fun_sleep(), get_local_windchill(), print_temperature(), to_legacy_bodypart_temp(), and Character::update_bodytemp().
to_celsius_delta()
template<typename value_type > constexpr value_type units::to_celsius_delta (const quantity< value_type, temperature_delta_in_kelvin_tag > & v) inline constexpr
Definition at line 502 of file units.h.
 {
     return v.value();
 }
References units::quantity< V, U >::value().
Referenced by Character::rest_quality().
to_cent()
template<typename value_type > constexpr value_type units::to_cent (const quantity< value_type, money_in_cent_tag > & v) inline constexpr
Definition at line 665 of file units.h.
 {
     return v / from_cent<value_type>( 1 );
 }
Referenced by anonymous_namespace{iexamine.cpp}::atm_menu::do_exchange_cash(), item::price_no_contents(), and to_usd().
to_centimeter()
template<typename value_type > constexpr value_type units::to_centimeter (const quantity< value_type, length_in_millimeter_tag > & v) inline constexpr
Definition at line 723 of file units.h.
 {
     return to_millimeter( v ) / 10.0;
 }
References to_millimeter().
to_degrees()
constexpr double units::to_degrees (const units::angle v) inline constexpr
Definition at line 757 of file units.h.
 {
     return to_radians( v ) * 180 / M_PI;
 }
References M_PI, and to_radians().
Referenced by map::add_vehicle(), map::add_vehicle_to_map(), map::apply_light_arc(), jmapgen_vehicle::check(), vehicle::precalculate_vehicle_turning(), target_ui::recalc_aim_turning_penalty(), vehicle::remove_carried_vehicle(), vehicle_part::carried_part_data::serialize(), vehicle_part::serialize(), vehicle::serialize(), iuse::sextant(), sun_light_at(), display::sundial_text_color(), to_arcmin(), to_orientation(), and tileray::to_string_azimuth_from_north().
to_fahrenheit()
template<typename value_type > constexpr value_type units::to_fahrenheit (const quantity< value_type, temperature_in_kelvin_tag > & v) inline constexpr
Definition at line 440 of file units.h.
 {
     return ( v * 1.8f - from_kelvin( 459.67f ) ).value();
 }
References from_kelvin().
Referenced by Character::apply_wetness_morale(), item::calc_hourly_rotpoints_at_temp(), Character::calc_needs_rates(), debug_menu::debug_menu_force_temperature(), vehicle::engine_cold_factor(), fahrenheit_from_kelvin(), suffer::in_sunlight(), print_temperature(), weather_manager::serialize_all(), weather_generator::test_weather(), Character::update_body_wetness(), Character::update_frostbite(), and Character::update_heartrate_index().
to_fahrenheit_delta()
template<typename value_type > constexpr value_type units::to_fahrenheit_delta (const quantity< value_type, temperature_delta_in_kelvin_tag > & v) inline constexpr
Definition at line 509 of file units.h.
 {
     return ( v * 1.8f ).value();
 }
Referenced by submap::set_temperature_mod(), and Character::update_bodytemp().
to_gram()
template<typename value_type > constexpr value_type units::to_gram (const quantity< value_type, mass_in_milligram_tag > & v) inline constexpr
Definition at line 364 of file units.h.
 {
     return v.value() / 1000.0;
 }
References units::quantity< V, U >::value().
Referenced by explosion_handler::_make_explosion(), butchery_drops_harvest(), item::calc_temp(), Character::calculate_leak_level(), item::combine(), Character::compute_effective_food_volume_ratio(), Character::consume_effects(), convert_weight(), Pickup::cost_to_move_item(), melee_actor::do_grab(), drop_or_embed_projectile(), funnel_charges_per_turn(), item::get_item_thermal_energy(), mtype::get_meat_chunks_count(), inventory_selector::get_weight_and_length_stat(), heat_item(), item::lift_strength(), Character::masticated_volume(), ebooksave_activity_actor::pages_in_book(), game::slip_down_chance(), mdeath::splatter(), and Character::throwing_dispersion().
to_joule()
template<typename value_type > constexpr value_type units::to_joule (const quantity< value_type, energy_in_millijoule_tag > & v) inline constexpr
Definition at line 572 of file units.h.
 {
     return to_millijoule( v ) / 1000.0;
 }
References to_millijoule().
Referenced by item::battery_info(), display(), item::display_name(), draw_bionics_tab(), draw_bionics_titlebar(), Character::fire_gun(), display::power_balance_text_color(), display::power_text_color(), Character::store(), and to_kilojoule().
to_joule_per_gram()
template<typename value_type > constexpr value_type units::to_joule_per_gram (const quantity< value_type, specific_energy_in_joule_per_gram_tag > & v) inline constexpr
Definition at line 390 of file units.h.
 {
     return v.value();
 }
References units::quantity< V, U >::value().
Referenced by item::calc_temp(), item::debug_info(), activity_handlers::fill_liquid_do_turn(), item::get_item_thermal_energy(), item::process_temperature_rot(), item::set_item_specific_energy(), and item::set_item_temperature().
to_kelvin()
template<typename value_type > constexpr value_type units::to_kelvin (const quantity< value_type, temperature_in_kelvin_tag > & v) inline constexpr
Definition at line 411 of file units.h.
 {
     return v.value();
 }
References units::quantity< V, U >::value().
Referenced by item::calc_temp(), celsius_to_kelvin(), debug_menu::character_edit_menu(), item::debug_info(), debug_menu::debug_menu_force_temperature(), fahrenheit_to_kelvin(), item::get_specific_energy_from_temperature(), operator+(), operator-(), print_temperature(), item::set_item_specific_energy(), item::set_item_temperature(), and anonymous_namespace{math_parser_diag.cpp}::weather_eval().
to_kelvin_delta()
template<typename value_type > constexpr value_type units::to_kelvin_delta (const quantity< value_type, temperature_delta_in_kelvin_tag > & v) inline constexpr
Definition at line 479 of file units.h.
 {
     return v.value();
 }
References units::quantity< V, U >::value().
Referenced by abs(), operator+(), operator-(), Character::rest_quality(), and to_legacy_bodypart_temp_delta().
to_kilogram()
constexpr double units::to_kilogram (const mass & v) inline constexpr
Definition at line 369 of file units.h.
 {
     return v.value() / 1000000.0;
 }
References units::quantity< V, U >::value().
Referenced by iexamine::autodoc(), vehicle::coeff_rolling_drag(), vehicle::coeff_water_drag(), Character::consume_anesth_requirement(), map::drop_items(), bionic_install_preset::get_anesth_amount(), bionic_install_preset::get_denial(), vehicle::ground_acceleration(), Character::has_enough_anesth(), vehicle::has_sufficient_rotorlift(), vehicle::k_traction(), Creature::longpull(), map::move_vehicle(), vehicle::part_collision(), shearing_entry::roll(), vehicle::rotor_acceleration(), map::shake_vehicle(), vehicle::slowdown(), map::vehicle_vehicle_collision(), and vehicle::water_acceleration().
to_kilojoule()
template<typename value_type > constexpr value_type units::to_kilojoule (const quantity< value_type, energy_in_millijoule_tag > & v) inline constexpr
Definition at line 578 of file units.h.
 {
     return to_joule( v ) / 1000.0;
 }
References to_joule().
Referenced by Character::activate_bionic(), Character::add_bionic(), item::ammo_capacity(), item::ammo_consume(), item_contents::ammo_consume(), item::ammo_remaining(), item::battery_info(), display(), draw_bionics_tab(), draw_bionics_titlebar(), explosion_handler::emp_blast(), item::energy_consume(), spell::energy_cur_string(), gunmode_checks_weapon(), Character::heat_emission(), known_magic::max_mana(), turret_data::post_fire(), display::power_balance_text_color(), display::power_text_color(), Character::store(), Character::update_stamina(), monster::use_mech_power(), and memorial_logger::write_text_memorial().
to_kilometer()
template<typename value_type > constexpr value_type units::to_kilometer (const quantity< value_type, length_in_millimeter_tag > & v) inline constexpr
Definition at line 735 of file units.h.
 {
     return to_millimeter( v ) / 1000000.0;
 }
References to_millimeter().
to_kilowatt()
template<typename value_type > constexpr value_type units::to_kilowatt (const quantity< value_type, power_in_milliwatt_tag > & v) inline constexpr
Definition at line 632 of file units.h.
 {
     return to_watt( v ) / 1000.0;
 }
References to_watt().
Referenced by veh_interact::calc_overview(), display(), and item::process_tool().
to_kusd()
template<typename value_type > constexpr value_type units::to_kusd (const quantity< value_type, money_in_cent_tag > & v) inline constexpr
Definition at line 677 of file units.h.
 {
     return to_usd( v ) / 1000.0;
 }
References to_usd().
to_legacy_bodypart_temp()
template<typename value_type > constexpr int units::to_legacy_bodypart_temp (const quantity< value_type, temperature_in_kelvin_tag > & v) inline constexpr
Definition at line 454 of file units.h.
 {
     const auto c = units::to_celsius( v );
     return static_cast<int>( ( c - 37.0 ) * 500.0 + 5000.0 );
 }
References c, and to_celsius().
Referenced by eff_fun_hot(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_part_temp(), conditional_t::get_get_dbl(), widget::get_var_value(), outfit::prepare_bodymap_info(), bodypart::serialize(), temperature_print_rescaling(), and anonymous_namespace{math_parser_diag.cpp}::warmth_eval().
to_legacy_bodypart_temp_delta()
template<typename value_type > constexpr int units::to_legacy_bodypart_temp_delta (const quantity< value_type, temperature_delta_in_kelvin_tag > & v) inline constexpr
Definition at line 523 of file units.h.
 {
     return static_cast<int>( units::to_kelvin_delta( v ) * 500.0 );
 }
References to_kelvin_delta().
Referenced by conditional_t::get_get_dbl(), vpart_info::load(), ter_t::load(), furn_t::load(), body_part_type::load(), and trap::load().
to_liter()
constexpr double units::to_liter (const volume & v) inline constexpr
Definition at line 321 of file units.h.
 {
     return v.value() / 1000.0;
 }
References units::quantity< V, U >::value().
Referenced by mattack::absorb_meat(), veh_interact::calc_overview(), Item_factory::check_definitions(), Character::compute_calories_per_effective_volume(), get_charcoal_charges(), liquid_handler::perform_liquid_transfer(), pick_part(), vehicle::print_part_list(), shearing_entry::roll(), and item::simulate_burn().
to_meter()
template<typename value_type > constexpr value_type units::to_meter (const quantity< value_type, length_in_millimeter_tag > & v) inline constexpr
Definition at line 729 of file units.h.
 {
     return to_millimeter( v ) / 1000.0;
 }
References to_millimeter().
to_milligram()
template<typename value_type > constexpr value_type units::to_milligram (const quantity< value_type, mass_in_milligram_tag > & v) inline constexpr
Definition at line 358 of file units.h.
 {
     return v.value();
 }
References units::quantity< V, U >::value().
Referenced by item::contain_monster(), vehicle::get_folded_item(), talker_character_const::get_weight(), talker_item_const::get_weight(), and talker_monster_const::get_weight().
to_millijoule()
template<typename value_type > constexpr value_type units::to_millijoule (const quantity< value_type, energy_in_millijoule_tag > & v) inline constexpr
Definition at line 566 of file units.h.
 {
     return v / from_millijoule<value_type>( 1 );
 }
Referenced by Character::activate_bionic(), item::battery_info(), item::bionic_info(), display(), draw_bionics_tab(), draw_bionics_titlebar(), anonymous_namespace{math_parser_diag.cpp}::energy_eval(), operator/(), display::power_balance_text_color(), display::power_text_color(), vehicle::power_to_energy_bat(), Character::store(), and to_joule().
to_milliliter()
template<typename value_type > constexpr value_type units::to_milliliter (const quantity< value_type, volume_in_milliliter_tag > & v) inline constexpr
Definition at line 316 of file units.h.
 {
     return v / from_milliliter<value_type>( 1 );
 }
Referenced by mattack::absorb_items(), armor_inventory_preset::armor_inventory_preset(), item::calc_temp(), Character::consume_effects(), debug_menu::debug_menu_game_state(), default_length_from_volume(), eat(), item::fuel_energy(), Character::get_consume_time(), talker_item_const::get_volume(), talker_monster_const::get_volume(), inventory_selector::get_volume_stat(), marloss_common(), Character::masticated_volume(), activity_handlers::move_cost_cart(), activity_handlers::move_cost_inv(), game_menus::inv::smoke_food(), outfit::sort_armor(), Character::throw_item(), Character::throwing_dispersion(), Character::thrown_item_total_damage_raw(), avatar::vomit(), Character::vomit(), game::water_affect_items(), and item::weight().
to_millimeter()
template<typename value_type > constexpr value_type units::to_millimeter (const quantity< value_type, length_in_millimeter_tag > & v) inline constexpr
Definition at line 717 of file units.h.
 {
     return v / from_millimeter<value_type>( 1 );
 }
Referenced by convert_length(), convert_length_cm_in(), length_units(), to_centimeter(), to_kilometer(), and to_meter().
to_milliwatt()
template<typename value_type > constexpr value_type units::to_milliwatt (const quantity< value_type, power_in_milliwatt_tag > & v) inline constexpr
Definition at line 620 of file units.h.
 {
     return v / from_milliwatt<value_type>( 1 );
 }
Referenced by display(), veh_app_interact::draw_info(), link_up_actor::info(), operator/(), item::process_tool(), and to_watt().
to_radians()
constexpr double units::to_radians (const units::angle v) inline constexpr
Definition at line 746 of file units.h.
 {
     return v.value();
 }
References units::quantity< V, U >::value().
Referenced by cos(), cot(), sin(), tan(), and to_degrees().
to_usd()
template<typename value_type > constexpr value_type units::to_usd (const quantity< value_type, money_in_cent_tag > & v) inline constexpr
Definition at line 671 of file units.h.
 {
     return to_cent( v ) / 100.0;
 }
References to_cent().
Referenced by to_kusd().
to_watt()
template<typename value_type > constexpr value_type units::to_watt (const quantity< value_type, power_in_milliwatt_tag > & v) inline constexpr
Definition at line 626 of file units.h.
 {
     return to_milliwatt( v ) / 1000.0;
 }
References to_milliwatt().
Referenced by vehicle::backfire(), veh_interact::calc_overview(), display(), veh_interact::display_details(), veh_interact::display_stats(), veh_app_interact::draw_info(), vehicle::engine_start_time(), vpart_info::format_description(), vehicle::ground_acceleration(), vehicle::lift_thrust_of_rotorcraft(), vehicle::max_ground_velocity(), vehicle::max_water_velocity(), iuse::multicooker(), vehicle::noise_and_smoke(), vehicle::power_parts(), vehicle::safe_ground_velocity(), vehicle::safe_water_velocity(), vehicle::slowdown(), to_kilowatt(), and vehicle::water_acceleration().
Variable Documentation
angle_units
const std::vector<std::pair<std::string, angle> > units::angle_units
Initial value:
= { {
        { "arcmin", 1_arcmin },
        { "", 1_degrees },
        { "rad", 1_radians },
    }
}
Definition at line 1173 of file units.h.
energy_max
const energy units::energy_max
Initial value:
= units::energy(std::numeric_limits<units::energy::value_type>::max(),
                          units::energy::unit_type{} )
Definition at line 534 of file units.h.
Referenced by Character::get_max_power_level(), Character::mod_max_power_level_modifier(), Character::set_max_power_level(), Character::set_max_power_level_modifier(), and Character::update_bionic_power_capacity().
energy_min
const energy units::energy_min
Initial value:
= units::energy(std::numeric_limits<units::energy::value_type>::min(),
                          units::energy::unit_type{} )
Definition at line 531 of file units.h.
Referenced by Character::load(), Character::mod_max_power_level_modifier(), Character::set_max_power_level(), and Character::set_max_power_level_modifier().
energy_units
const std::vector<std::pair<std::string, energy> > units::energy_units
Initial value:
= { {
        { "mJ", 1_mJ },
        { "J", 1_J },
        { "kJ", 1_kJ },
    }
}
Definition at line 1137 of file units.h.
Referenced by anonymous_namespace{math_parser_diag.cpp}::energy_eval().
legacy_volume_factor
constexpr volume units::legacy_volume_factor = from_milliliter(250) constexpr
Definition at line 328 of file units.h.
Referenced by assign(), item::burn(), veh_interact::calc_overview(), item::collapsed_volume_delta(), iexamine::cvdmachine(), item::flammable(), vehicle::get_folded_item(), legacy_volume_reader(), item::on_wield_cost(), vehicle::operate_scoop(), liquid_handler::perform_liquid_transfer(), pick_part(), vehicle::print_part_list(), item::process_corpse(), activity_handlers::pulp_do_turn(), smash(), map::smash_items(), and item::volume().
length_max
const length units::length_max
Initial value:
= units::length(std::numeric_limits<units::length::value_type>::max(),
                          units::length::unit_type{} )
Definition at line 685 of file units.h.
length_min
const length units::length_min
Initial value:
= units::length(std::numeric_limits<units::length::value_type>::min(),
                          units::length::unit_type{} )
Definition at line 682 of file units.h.
length_units
const std::vector<std::pair<std::string, length> > units::length_units
Initial value:
= { {
        { "mm", 1_mm },
        { "cm", 1_cm },
        { "meter", 1_meter },
        { "km", 1_km }
    }
}
Definition at line 1166 of file units.h.
Referenced by item::ammo_info(), assign(), item::basic_info(), item_pocket::general_info(), inventory_selector::get_weight_and_length_stat(), and item::gun_info().
mass_max
const mass units::mass_max
Initial value:
= units::mass(std::numeric_limits<units::mass::value_type>::max(),
                                   units::mass::unit_type{} )
Definition at line 333 of file units.h.
Referenced by advanced_inventory_pane::free_weight_capacity(), item_location::impl::item_on_map::weight_capacity(), item_location::impl::item_on_person::weight_capacity(), and item_location::impl::item_on_vehicle::weight_capacity().
mass_min
const mass units::mass_min
Initial value:
= units::mass(std::numeric_limits<units::mass::value_type>::min(),
                                   units::mass::unit_type{} )
Definition at line 330 of file units.h.
mass_units
const std::vector<std::pair<std::string, mass> > units::mass_units
Initial value:
= { {
        { "mg", 1_milligram },
        { "g", 1_gram },
        { "kg", 1_kilogram },
    }
}
Definition at line 1149 of file units.h.
Referenced by assign(), mass_reader::get_next(), and mass_reader::operator()().
money_max
const money units::money_max
Initial value:
= units::money(std::numeric_limits<units::money::value_type>::max(),
                                      units::money::unit_type{} )
Definition at line 642 of file units.h.
money_min
const money units::money_min
Initial value:
= units::money(std::numeric_limits<units::money::value_type>::min(),
                                      units::money::unit_type{} )
Definition at line 639 of file units.h.
money_units
const std::vector<std::pair<std::string, money> > units::money_units
Initial value:
= { {
        { "cent", 1_cent },
        { "USD", 1_USD },
        { "kUSD", 1_kUSD },
    }
}
Definition at line 1155 of file units.h.
Referenced by assign(), money_reader::get_next(), and money_reader::operator()().
power_max
const power units::power_max
Initial value:
= units::power(std::numeric_limits<units::power::value_type>::max(),
                                      units::power::unit_type{} )
Definition at line 588 of file units.h.
Referenced by conditional_t::get_get_dbl(), and debug_menu::wishbionics().
power_min
const power units::power_min
Initial value:
= units::power(std::numeric_limits<units::power::value_type>::min(),
                                      units::power::unit_type{} )
Definition at line 585 of file units.h.
power_units
const std::vector<std::pair<std::string, power> > units::power_units
Initial value:
= { {
        { "mW", 1_mW },
        { "W", 1_W },
        { "kW", 1_kW },
    }
}
Definition at line 1143 of file units.h.
specific_energy_max
const specific_energy units::specific_energy_max
Initial value:
= units::specific_energy(
            std::numeric_limits<units::specific_energy::value_type>::max(), units::specific_energy::unit_type{} )
Definition at line 378 of file units.h.
specific_energy_min
const specific_energy units::specific_energy_min
Initial value:
= units::specific_energy(
            std::numeric_limits<units::specific_energy::value_type>::min(), units::specific_energy::unit_type{} )
Definition at line 375 of file units.h.
temperature_delta_max
const temperature_delta units::temperature_delta_max
Initial value:
= units::temperature_delta(
            std::numeric_limits<units::temperature_delta::value_type>::max(),
            units::temperature_delta::unit_type{} )
Definition at line 466 of file units.h.
temperature_delta_min
const temperature_delta units::temperature_delta_min
Initial value:
= units::temperature_delta(0,
        units::temperature_delta::unit_type{} )
Definition at line 463 of file units.h.
temperature_max
const temperature units::temperature_max
Initial value:
= units::temperature(
                                        std::numeric_limits<units::temperature::value_type>::max(), units::temperature::unit_type{} )
Definition at line 400 of file units.h.
temperature_min
const temperature units::temperature_min = units::temperature(0, units::temperature::unit_type{})
Definition at line 398 of file units.h.
temperature_units
const std::vector<std::pair<std::string, temperature> > units::temperature_units
Initial value:
= { {
        { "K", 1_K }
    }
}
Definition at line 1179 of file units.h.
volume_max
const volume units::volume_max
Initial value:
= units::volume(std::numeric_limits<units::volume::value_type>::max(),
                          units::volume::unit_type{} )
Definition at line 299 of file units.h.
Referenced by item_location::impl::item_on_person::volume_capacity().
volume_min
const volume units::volume_min
Initial value:
= units::volume(std::numeric_limits<units::volume::value_type>::min(),
                          units::volume::unit_type{} )
Definition at line 296 of file units.h.
volume_units
const std::vector<std::pair<std::string, volume> > units::volume_units
Initial value:
= { {
        { "ml", 1_ml },
        { "L", 1_liter }
    }
}
Definition at line 1161 of file units.h.
Referenced by assign(), units::quantity< V, U >::deserialize(), volume_reader::get_next(), and volume_reader::operator()().