Cataclysm DDA: anonymous_namespace{profession.cpp} Namespace Reference
anonymous_namespace{profession.cpp} Namespace Reference
Variables
generic_factory< profession > all_profs ("profession")
Variable Documentation
all_profs
generic_factory<profession> anonymous_namespace{profession.cpp}::all_profs("profession") ("profession")
Referenced by profession::check_definitions(), profession::get_all(), string_id< T >::is_valid(), profession::load_profession(), string_id< T >::obj(), and profession::reset().