Cataclysm DDA: src/ncurses_def.cpp File Reference
ncurses_def.cpp File Reference
#include "input.h"
#include "point.h"
#include "translations.h"
#include "cata_imgui.h"
#include <curses.h>
#include <cstdint>
#include <cstring>
#include <iosfwd>
#include <langinfo.h>
#include <memory>
#include <stdexcept>
#include "cached_options.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "color.h"
#include "cursesdef.h"
#include "game_constants.h"
#include "game_ui.h"
#include "output.h"
#include "ui_manager.h"
Macros
#define NCURSES_NOMACROS
#define NCURSES_WIDECHAR 1
Functions
static void curses_check_result (const int result, const int expected, const char *const)
int get_window_width ()
int get_window_height ()
void refresh_display ()
Make changes made to the display visible to the user immediately.
void ensure_term_size ()
void check_encoding ()
void set_title (const std::string &)
Set the game window title.
Variables
std::unique_ptr< cataimgui::client > imclient
Macro Definition Documentation
NCURSES_NOMACROS
#define NCURSES_NOMACROS
Definition at line 12 of file ncurses_def.cpp.
NCURSES_WIDECHAR
#define NCURSES_WIDECHAR 1
Definition at line 14 of file ncurses_def.cpp.
Function Documentation
check_encoding()
void check_encoding ()
Definition at line 571 of file ncurses_def.cpp.
 {
     // Check whether LC_CTYPE supports the UTF-8 encoding
     // and show a warning if it doesn't
     if( std::strcmp( nl_langinfo( CODESET ), "UTF-8" ) != 0 ) {
         // do not use ui_adaptor here to avoid re-entry
         int key = ERR;
         do {
             const char *unicode_error_msg =
                 _( "You don't seem to have a valid Unicode locale. You may see some weird "
                    "characters (e.g. empty boxes or question marks). You have been warned." );
             catacurses::erase();
             const int maxx = getmaxx( catacurses::stdscr );
             fold_and_print( catacurses::stdscr, point_zero, maxx, c_white, unicode_error_msg );
             catacurses::refresh();
             // do not use input_manager or input_context here to avoid re-entry
             key = getch();
         } while( key == KEY_RESIZE || key == KEY_MOUSE );
     }
 }
References _, c_white, catacurses::erase(), fold_and_print(), catacurses::getmaxx(), point_zero, catacurses::refresh(), and catacurses::stdscr.
Referenced by game_ui::init_ui().
curses_check_result()
static void curses_check_result (const int result, const int expected, const char * const) static
Definition at line 41 of file ncurses_def.cpp.
 {
     if( result != expected ) {
         // TODO: debug message
     }
 }
Referenced by catacurses::clear(), catacurses::curs_set(), catacurses::doupdate(), catacurses::endwin(), catacurses::erase(), catacurses::init_pair(), catacurses::mvwaddch(), catacurses::mvwhline(), catacurses::mvwprintw(), catacurses::mvwvline(), catacurses::newwin(), catacurses::refresh(), catacurses::waddch(), catacurses::wattroff(), catacurses::wattron(), catacurses::wborder(), catacurses::wclear(), catacurses::werase(), catacurses::wmove(), catacurses::wnoutrefresh(), catacurses::wprintw(), catacurses::wredrawln(), and catacurses::wrefresh().
ensure_term_size()
void ensure_term_size ()
Definition at line 536 of file ncurses_def.cpp.
 {
     // do not use ui_adaptor here to avoid re-entry
     const int minHeight = EVEN_MINIMUM_TERM_HEIGHT;
     const int minWidth = EVEN_MINIMUM_TERM_WIDTH;
     while( TERMY < minHeight || TERMX < minWidth ) {
         catacurses::erase();
         if( TERMY < minHeight && TERMX < minWidth ) {
             fold_and_print( catacurses::stdscr, point_zero, TERMX, c_white,
                             _( "Whoa!  Your terminal is tiny!  This game requires a minimum terminal size of "
                                "%dx%d to work properly.  %dx%d just won't do.  Maybe a smaller font would help?" ),
                             minWidth, minHeight, TERMX, TERMY );
         } else if( TERMX < minWidth ) {
             fold_and_print( catacurses::stdscr, point_zero, TERMX, c_white,
                             _( "Oh!  Hey, look at that.  Your terminal is just a little too narrow.  This game "
                                "requires a minimum terminal size of %dx%d to function.  It just won't work "
                                "with only %dx%d.  Can you stretch it out sideways a bit?" ),
                             minWidth, minHeight, TERMX, TERMY );
         } else {
             fold_and_print( catacurses::stdscr, point_zero, TERMX, c_white,
                             _( "Woah, woah, we're just a little short on space here.  The game requires a "
                                "minimum terminal size of %dx%d to run.  %dx%d isn't quite enough!  Can you "
                                "make the terminal just a smidgen taller?" ),
                             minWidth, minHeight, TERMX, TERMY );
         }
         catacurses::refresh();
         // do not use input_manager or input_context here to avoid re-entry
         getch();
         TERMY = getmaxy( catacurses::stdscr );
         TERMX = getmaxx( catacurses::stdscr );
     }
 }
References _, c_white, catacurses::erase(), EVEN_MINIMUM_TERM_HEIGHT, EVEN_MINIMUM_TERM_WIDTH, fold_and_print(), catacurses::getmaxx(), catacurses::getmaxy(), point_zero, catacurses::refresh(), catacurses::stdscr, TERMX, and TERMY.
Referenced by game_ui::init_ui().
get_window_height()
int get_window_height ()
Definition at line 53 of file ncurses_def.cpp.
 {
     return TERMY;
 }
References TERMY.
get_window_width()
int get_window_width ()
Definition at line 48 of file ncurses_def.cpp.
 {
     return TERMX;
 }
References TERMX.
refresh_display()
void refresh_display ()
Make changes made to the display visible to the user immediately.
In curses mode, this is a no-op. In SDL mode, this refreshes the real display from the backing buffer immediately, rather than delaying the update until the next time we are waiting for user input.
Definition at line 186 of file ncurses_def.cpp.
 {
     catacurses::doupdate();
 }
References catacurses::doupdate().
Referenced by game::cancel_activity_or_ignore_query(), debug_menu::debug(), game::display_om_pathfinding_progress(), melee_actor::do_grab(), anonymous_namespace{animation.cpp}::basic_animation::draw(), debug_menu::draw_benchmark(), past_games_info::ensure_loaded(), game::fling_creature(), handle_key_blocking_activity(), game::portal_storm_query(), robot_finds_kitten::process_input(), game::quicksave(), mapbuffer::save(), game::setup(), loading_ui::show(), options_manager::show(), and game::start_game().
set_title()
void set_title (const std::string & title)
Set the game window title.
Implemented in stdtiles.cpp, wincurse.cpp, and ncurses_def.cpp.
Definition at line 592 of file ncurses_def.cpp.
 {
     // curses does not seem to have a portable way of setting the window title.
 }
Referenced by set_language().
Variable Documentation
imclient
std::unique_ptr<cataimgui::client> imclient
Definition at line 39 of file ncurses_def.cpp.
Referenced by anonymous_namespace{main.cpp}::exit_handler(), input_manager::get_input_event(), catacurses::init_interface(), catacurses::init_pair(), color_manager::load_default(), and ui_adaptor::redraw_invalidated().