Cataclysm DDA: src/npc_attack.cpp File Reference
npc_attack.cpp File Reference
#include "npc_attack.h"
#include "cata_utility.h"
#include "character.h"
#include "creature_tracker.h"
#include "dialogue.h"
#include "flag.h"
#include "item.h"
#include "line.h"
#include "magic.h"
#include "magic_spell_effect_helpers.h"
#include "map.h"
#include "messages.h"
#include "npc.h"
#include "point.h"
#include "projectile.h"
#include "ranged.h"
Namespaces
npc_attack_constants
Functions
static bool has_obstruction (const tripoint &from, const tripoint &to, bool check_ally=false)
static bool can_move (const npc &source)
static bool can_move_melee (const npc &source)
Variables
static const bionic_id bio_hydraulics ("bio_hydraulics")
static const json_character_flag json_flag_SUBTLE_SPELL ("SUBTLE_SPELL")
static const float npc_attack_constants::target_modifier = 1.5f
static const float npc_attack_constants::kill_modifier = 1.5f
static const int npc_attack_constants::base_time_penalty = 3
static const int npc_attack_constants::base_throw_now = 10'000
Function Documentation
can_move()
static bool can_move (const npc & source) static
Definition at line 54 of file npc_attack.cpp.
 {
     return !source.in_vehicle && source.rules.engagement != combat_engagement::NO_MOVE;
 }
References npc_follower_rules::engagement, Character::in_vehicle, NO_MOVE, and npc::rules.
Referenced by can_move_melee(), map::move_vehicle(), npc_attack_gun::use(), and npc_attack_throw::use().
can_move_melee()
static bool can_move_melee (const npc & source) static
Definition at line 59 of file npc_attack.cpp.
 {
     return can_move( source ) && source.rules.engagement != combat_engagement::FREE_FIRE &&
            source.rules.engagement != combat_engagement::NO_MOVE;
 }
References can_move(), npc_follower_rules::engagement, FREE_FIRE, NO_MOVE, and npc::rules.
Referenced by npc_attack_melee::use().
has_obstruction()
static bool has_obstruction (const tripoint & from, const tripoint & to, bool check_ally = false) static
Definition at line 39 of file npc_attack.cpp.
 {
     std::vector<tripoint> line = line_to( from, to );
     // @to is what we want to hit. we don't need to check for obstruction there.
     line.pop_back();
     const map &here = get_map();
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &line_point : line ) {
         if( here.impassable( line_point ) || ( check_ally && creatures.creature_at( line_point ) ) ) {
             return true;
         }
     }
     return false;
 }
References creature_tracker::creature_at(), get_creature_tracker(), get_map(), map::impassable(), line(), and line_to().
Referenced by npc_attack_throw::evaluate(), npc_attack_gun::evaluate_tripoint(), npc_attack_throw::evaluate_tripoint(), spell::targetable_locations(), npc_attack_gun::use(), and npc_attack_throw::use().
Variable Documentation
bio_hydraulics
const bionic_id bio_hydraulics("bio_hydraulics") ("bio_hydraulics") static
Referenced by npc_attack_melee::use().
json_flag_SUBTLE_SPELL
const json_character_flag json_flag_SUBTLE_SPELL("SUBTLE_SPELL") ("SUBTLE_SPELL") static
Referenced by npc_attack_spell::base_time_penalty(), and npc_attack_spell::use().