Cataclysm DDA: src/npc.cpp File Reference
npc.cpp File Reference
#include "npc.h"
#include <algorithm>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <functional>
#include <limits>
#include <memory>
#include <ostream>
#include "activity_type.h"
#include "activity_actor_definitions.h"
#include "auto_pickup.h"
#include "basecamp.h"
#include "bodypart.h"
#include "catacharset.h"
#include "character.h"
#include "character_id.h"
#include "character_martial_arts.h"
#include "clzones.h"
#include "coordinate_conversions.h"
#include "creature_tracker.h"
#include "cursesdef.h"
#include "damage.h"
#include "debug.h"
#include "dialogue.h"
#include "dialogue_chatbin.h"
#include "effect.h"
#include "effect_on_condition.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "faction.h"
#include "flag.h"
#include "game.h"
#include "gates.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "item.h"
#include "item_group.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "json.h"
#include "magic.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "messages.h"
#include "mission.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "mutation.h"
#include "npc_class.h"
#include "npctrade.h"
#include "npctrade_utils.h"
#include "npctalk.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "pathfinding.h"
#include "player_activity.h"
#include "ret_val.h"
#include "rng.h"
#include "skill.h"
#include "sounds.h"
#include "stomach.h"
#include "string_formatter.h"
#include "talker.h"
#include "talker_npc.h"
#include "text_snippets.h"
#include "tileray.h"
#include "trait_group.h"
#include "translations.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "viewer.h"
#include "visitable.h"
#include "vpart_position.h"
#include "vpart_range.h"
Functions
static void starting_clothes (npc &who, const npc_class_id &type, bool male)
static void starting_inv (npc &who, const npc_class_id &type)
static item random_item_from (const npc_class_id &type, const std::string &what, const item_group_id &fallback)
static item random_item_from (const npc_class_id &type, const std::string &what)
static item get_clothing_item (const npc_class_id &type, const std::string &what, bool male)
static void maybe_shift (tripoint &pos, const point &d)
std::string npc_attitude_id (npc_attitude att)
std::string npc_attitude_name (npc_attitude att)
std::ostream & operator<< (std::ostream &os, const npc_need &need)
std::unique_ptr< talker > get_talker_for (npc &guy)
std::unique_ptr< talker > get_talker_for (npc *guy)
Variables
static const efftype_id effect_bouldering ("bouldering")
static const efftype_id effect_controlled ("controlled")
static const efftype_id effect_drunk ("drunk")
static const efftype_id effect_high ("high")
static const efftype_id effect_infection ("infection")
static const efftype_id effect_mending ("mending")
static const efftype_id effect_npc_flee_player ("npc_flee_player")
static const efftype_id effect_npc_suspend ("npc_suspend")
static const efftype_id effect_pkill1_acetaminophen ("pkill1_acetaminophen")
static const efftype_id effect_pkill1_generic ("pkill1_generic")
static const efftype_id effect_pkill1_nsaid ("pkill1_nsaid")
static const efftype_id effect_pkill2 ("pkill2")
static const efftype_id effect_pkill3 ("pkill3")
static const efftype_id effect_pkill_l ("pkill_l")
static const efftype_id effect_ridden ("ridden")
static const efftype_id effect_riding ("riding")
static const efftype_id effect_sleep ("sleep")
static const faction_id faction_amf ("amf")
static const faction_id faction_no_faction ("no_faction")
static const faction_id faction_your_followers ("your_followers")
static const item_group_id Item_spawn_data_guns_pistol_common ("guns_pistol_common")
static const item_group_id Item_spawn_data_guns_rifle_common ("guns_rifle_common")
static const item_group_id Item_spawn_data_guns_shotgun_common ("guns_shotgun_common")
static const item_group_id Item_spawn_data_guns_smg_common ("guns_smg_common")
static const item_group_id Item_spawn_data_npc_eyes ("npc_eyes")
static const item_group_id Item_spawn_data_survivor_bashing ("survivor_bashing")
static const item_group_id Item_spawn_data_survivor_cutting ("survivor_cutting")
static const item_group_id Item_spawn_data_survivor_stabbing ("survivor_stabbing")
static const json_character_flag json_flag_CANNIBAL ("CANNIBAL")
static const json_character_flag json_flag_PSYCHOPATH ("PSYCHOPATH")
static const json_character_flag json_flag_SAPIOVORE ("SAPIOVORE")
static const json_character_flag json_flag_SPIRITUAL ("SPIRITUAL")
static const mfaction_str_id monfaction_bee ("bee")
static const mfaction_str_id monfaction_human ("human")
static const mfaction_str_id monfaction_player ("player")
static const overmap_location_str_id overmap_location_source_of_ammo ("source_of_ammo")
static const overmap_location_str_id overmap_location_source_of_anything ("source_of_anything")
static const overmap_location_str_id overmap_location_source_of_drink ("source_of_drink")
static const overmap_location_str_id overmap_location_source_of_food ("source_of_food")
static const overmap_location_str_id overmap_location_source_of_guns ("source_of_guns")
static const overmap_location_str_id overmap_location_source_of_safety ("source_of_safety")
static const overmap_location_str_id overmap_location_source_of_weapons ("source_of_weapons")
static const skill_id skill_archery ("archery")
static const skill_id skill_bashing ("bashing")
static const skill_id skill_cutting ("cutting")
static const skill_id skill_dodge ("dodge")
static const skill_id skill_gun ("gun")
static const skill_id skill_launcher ("launcher")
static const skill_id skill_melee ("melee")
static const skill_id skill_pistol ("pistol")
static const skill_id skill_rifle ("rifle")
static const skill_id skill_shotgun ("shotgun")
static const skill_id skill_smg ("smg")
static const skill_id skill_speech ("speech")
static const skill_id skill_stabbing ("stabbing")
static const skill_id skill_throw ("throw")
static const skill_id skill_unarmed ("unarmed")
static const trait_id trait_BEE ("BEE")
static const trait_id trait_DEBUG_MIND_CONTROL ("DEBUG_MIND_CONTROL")
static const trait_id trait_HALLUCINATION ("HALLUCINATION")
static const trait_id trait_KILLER ("KILLER")
static const trait_id trait_MUTE ("MUTE")
static const trait_id trait_NO_BASH ("NO_BASH")
static const trait_id trait_PACIFIST ("PACIFIST")
static const trait_id trait_PROF_DICEMASTER ("PROF_DICEMASTER")
static const trait_id trait_SQUEAMISH ("SQUEAMISH")
static const trait_id trait_TERRIFYING ("TERRIFYING")
static std::map< string_id< npc_template >, npc_template > npc_templates
Function Documentation
get_clothing_item()
static item get_clothing_item (const npc_class_id & type, const std::string & what, bool male) static
Definition at line 803 of file npc.cpp.
 {
     item result;
     //Check if class has gendered clothing
     //Then check if it has an ungendered version
     //Only if all that fails, grab from the default class.
     if( male ) {
         result = random_item_from( type, what + "_male", item_group_id::NULL_ID() );
     } else {
         result = random_item_from( type, what + "_female", item_group_id::NULL_ID() );
     }
     if( result.is_null() ) {
         if( male ) {
             result = random_item_from( type, what, item_group_id( "npc_" + what + "_male" ) );
         } else {
             result = random_item_from( type, what, item_group_id( "npc_" + what + "_female" ) );
         }
     }
     return result;
 }
References item::is_null(), male, string_id< Item_spawn_data >::NULL_ID(), random_item_from(), and type.
Referenced by starting_clothes().
get_talker_for() [1/2]
std::unique_ptr<talker> get_talker_for (npc & guy)
Definition at line 3814 of file npc.cpp.
 {
     return std::make_unique<talker_npc>( &guy );
 }
Referenced by npc::die().
get_talker_for() [2/2]
std::unique_ptr<talker> get_talker_for (npc * guy)
Definition at line 3818 of file npc.cpp.
 {
     return std::make_unique<talker_npc>( guy );
 }
maybe_shift()
static void maybe_shift (tripoint & pos, const point & d) static
Definition at line 2731 of file npc.cpp.
 {
     if( pos != tripoint_min ) {
         pos += d;
     }
 }
References math_opers::pos(), and tripoint_min.
Referenced by npc::shift().
npc_attitude_id()
std::string npc_attitude_id (npc_attitude att)
Definition at line 2917 of file npc.cpp.
 {
     static const std::map<npc_attitude, std::string> npc_attitude_ids = {
         { NPCATT_NULL, "NPCATT_NULL" },
         { NPCATT_TALK, "NPCATT_TALK" },
         { NPCATT_FOLLOW, "NPCATT_FOLLOW" },
         { NPCATT_LEAD, "NPCATT_LEAD" },
         { NPCATT_WAIT, "NPCATT_WAIT" },
         { NPCATT_MUG, "NPCATT_MUG" },
         { NPCATT_WAIT_FOR_LEAVE, "NPCATT_WAIT_FOR_LEAVE" },
         { NPCATT_KILL, "NPCATT_KILL" },
         { NPCATT_FLEE, "NPCATT_FLEE" },
         { NPCATT_FLEE_TEMP, "NPCATT_FLEE_TEMP" },
         { NPCATT_HEAL, "NPCATT_HEAL" },
         { NPCATT_ACTIVITY, "NPCATT_ACTIVITY" },
         { NPCATT_RECOVER_GOODS, "NPCATT_RECOVER_GOODS" },
         { NPCATT_LEGACY_1, "NPCATT_LEGACY_1" },
         { NPCATT_LEGACY_2, "NPCATT_LEGACY_2" },
         { NPCATT_LEGACY_3, "NPCATT_LEGACY_3" },
         { NPCATT_LEGACY_4, "NPCATT_LEGACY_4" },
         { NPCATT_LEGACY_5, "NPCATT_LEGACY_5" },
         { NPCATT_LEGACY_6, "NPCATT_LEGACY_6" },
     };
     const auto &iter = npc_attitude_ids.find( att );
     if( iter == npc_attitude_ids.end() ) {
         debugmsg( "Invalid attitude: %d", att );
         return "NPCATT_INVALID";
     }
     return iter->second;
 }
References debugmsg, NPCATT_ACTIVITY, NPCATT_FLEE, NPCATT_FLEE_TEMP, NPCATT_FOLLOW, NPCATT_HEAL, NPCATT_KILL, NPCATT_LEAD, NPCATT_LEGACY_1, NPCATT_LEGACY_2, NPCATT_LEGACY_3, NPCATT_LEGACY_4, NPCATT_LEGACY_5, NPCATT_LEGACY_6, NPCATT_MUG, NPCATT_NULL, NPCATT_RECOVER_GOODS, NPCATT_TALK, NPCATT_WAIT, and NPCATT_WAIT_FOR_LEAVE.
Referenced by npc::form_opinion(), and npc::set_attitude().
npc_attitude_name()
std::string npc_attitude_name (npc_attitude att)
Definition at line 2959 of file npc.cpp.
 {
     switch( att ) {
         // Don't care/ignoring player
         case NPCATT_NULL:
             return _( "Ignoring" );
         // Move to and talk to player
         case NPCATT_TALK:
             return _( "Wants to talk" );
         // Follow the player
         case NPCATT_FOLLOW:
             return _( "Following" );
         // Lead the player, wait for them if they're behind
         case NPCATT_LEAD:
             return _( "Leading" );
         // Waiting for the player
         case NPCATT_WAIT:
             return _( "Waiting for you" );
         // Mug the player
         case NPCATT_MUG:
             return _( "Mugging you" );
         // Attack the player if our patience runs out
         case NPCATT_WAIT_FOR_LEAVE:
             return _( "Waiting for you to leave" );
         // Kill the player
         case NPCATT_KILL:
             return _( "Attacking to kill" );
         // Get away from the player
         case NPCATT_FLEE:
         case NPCATT_FLEE_TEMP:
             return _( "Fleeing" );
         // Get to the player and heal them
         case NPCATT_HEAL:
             return _( "Healing you" );
         case NPCATT_ACTIVITY:
             return _( "Performing a task" );
         case NPCATT_RECOVER_GOODS:
             return _( "Trying to recover stolen goods" );
         case NPCATT_LEGACY_1:
         case NPCATT_LEGACY_2:
         case NPCATT_LEGACY_3:
         case NPCATT_LEGACY_4:
         case NPCATT_LEGACY_5:
         case NPCATT_LEGACY_6:
             return _( "NPC Legacy Attitude" );
         default:
             break;
     }
     debugmsg( "Invalid attitude: %d", att );
     return _( "Unknown attitude" );
 }
References _, debugmsg, NPCATT_ACTIVITY, NPCATT_FLEE, NPCATT_FLEE_TEMP, NPCATT_FOLLOW, NPCATT_HEAL, NPCATT_KILL, NPCATT_LEAD, NPCATT_LEGACY_1, NPCATT_LEGACY_2, NPCATT_LEGACY_3, NPCATT_LEGACY_4, NPCATT_LEGACY_5, NPCATT_LEGACY_6, NPCATT_MUG, NPCATT_NULL, NPCATT_RECOVER_GOODS, NPCATT_TALK, NPCATT_WAIT, and NPCATT_WAIT_FOR_LEAVE.
Referenced by debug_menu::character_edit_menu(), game::list_monsters(), and npc::print_info().
operator<<()
std::ostream& operator<< (std::ostream & os, const npc_need & need)
Definition at line 3258 of file npc.cpp.
 {
     return os << npc::get_need_str_id( need );
 }
References npc::get_need_str_id().
random_item_from() [1/2]
static item random_item_from (const npc_class_id & type, const std::string & what) static
Definition at line 797 of file npc.cpp.
 {
     return random_item_from( type, what, item_group_id( "npc_" + what ) );
 }
References random_item_from(), and type.
random_item_from() [2/2]
static item random_item_from (const npc_class_id & type, const std::string & what, const item_group_id & fallback) static
Definition at line 786 of file npc.cpp.
 {
     item result = item_group::item_from( item_group_id( type.str() + "_" + what ), calendar::turn );
     if( result.is_null() ) {
         result = item_group::item_from( fallback, calendar::turn );
     }
     return result;
 }
References item::is_null(), item_group::item_from(), calendar::turn, and type.
Referenced by get_clothing_item(), random_item_from(), starting_clothes(), starting_inv(), and npc::starting_weapon().
starting_clothes()
void starting_clothes (npc & who, const npc_class_id & type, bool male) static
Definition at line 825 of file npc.cpp.
 {
     std::vector<item> ret;
     if( item_group::group_is_defined( type->worn_override ) ) {
         ret = item_group::items_from( type->worn_override );
     } else {
         ret.push_back( get_clothing_item( type, "pants", male ) );
         ret.push_back( get_clothing_item( type, "shirt", male ) );
         ret.push_back( get_clothing_item( type, "underwear_top", male ) );
         ret.push_back( get_clothing_item( type, "underwear_bottom", male ) );
         ret.push_back( get_clothing_item( type, "underwear_feet", male ) );
         ret.push_back( get_clothing_item( type, "shoes", male ) );
         ret.push_back( random_item_from( type, "gloves" ) );
         ret.push_back( random_item_from( type, "coat" ) );
         ret.push_back( random_item_from( type, "vest" ) );
         ret.push_back( random_item_from( type, "masks" ) );
         // Why is the alternative group not named "npc_glasses" but "npc_eyes"?
         ret.push_back( random_item_from( type, "glasses", Item_spawn_data_npc_eyes ) );
         ret.push_back( random_item_from( type, "hat" ) );
         ret.push_back( random_item_from( type, "scarf" ) );
         ret.push_back( random_item_from( type, "storage" ) );
         ret.push_back( random_item_from( type, "holster" ) );
         ret.push_back( random_item_from( type, "belt" ) );
         ret.push_back( random_item_from( type, "wrist" ) );
         ret.push_back( random_item_from( type, "extra" ) );
     }
     who.worn.on_takeoff( who );
     who.clear_worn();
     for( item &it : ret ) {
         if( it.has_flag( flag_VARSIZE ) ) {
             it.set_flag( flag_FIT );
         }
         if( who.can_wear( it ).success() ) {
             it.on_wear( who );
             who.worn.wear_item( who, it, false, false );
             it.set_owner( who );
         }
     }
 }
References Character::can_wear(), Character::clear_worn(), flag_FIT, flag_VARSIZE, get_clothing_item(), item_group::group_is_defined(), Item_spawn_data_npc_eyes, item_group::items_from(), male, outfit::on_takeoff(), random_item_from(), cata::hash64_detail::ret, ret_val_common::success(), type, outfit::wear_item(), and Character::worn.
Referenced by npc::randomize().
starting_inv()
void starting_inv (npc & who, const npc_class_id & type) static
Definition at line 866 of file npc.cpp.
 {
     std::list<item> res;
     who.inv->clear();
     if( item_group::group_is_defined( type->carry_override ) ) {
         *who.inv += item_group::items_from( type->carry_override );
         return;
     }
     // If wielding a gun, get some additional ammo for it
     const item_location weapon = who.get_wielded_item();
     if( weapon && weapon->is_gun() ) {
         item ammo;
         if( !weapon->magazine_default().is_null() ) {
             item mag( weapon->magazine_default() );
             mag.ammo_set( mag.ammo_default() );
             ammo = item( mag.ammo_default() );
             res.push_back( mag );
         } else if( !weapon->ammo_default().is_null() ) {
             ammo = item( weapon->ammo_default() );
             // TODO: Move to npc_class
             // NC_COWBOY and NC_BOUNTY_HUNTER get 5-15 whilst all others get 3-6
             int qty = 1 + ( type == NC_COWBOY ||
                             type == NC_BOUNTY_HUNTER );
             qty = rng( qty, qty * 2 );
             while( qty-- != 0 && who.can_stash( ammo ) ) {
                 res.push_back( ammo );
             }
         }
     }
     if( type == NC_ARSONIST ) {
         res.emplace_back( "molotov" );
     }
     int qty = ( type == NC_EVAC_SHOPKEEP ||
                 type == NC_TRADER ) ? 5 : 2;
     qty = rng( qty, qty * 3 );
     while( qty-- != 0 ) {
         item tmp = random_item_from( type, "misc" ).in_its_container();
         if( !tmp.is_null() ) {
             if( !one_in( 3 ) && tmp.has_flag( flag_VARSIZE ) ) {
                 tmp.set_flag( flag_FIT );
             }
             if( who.can_pickVolume( tmp ) ) {
                 res.push_back( tmp );
             }
         }
     }
     res.erase( std::remove_if( res.begin(), res.end(), [&]( const item & e ) {
         return e.has_flag( flag_TRADER_AVOID );
     } ), res.end() );
     for( item &it : res ) {
         it.set_owner( who );
     }
     *who.inv += res;
 }
References item::ammo_default(), item::ammo_set(), Character::can_pickVolume(), Character::can_stash(), flag_FIT, flag_VARSIZE, Character::get_wielded_item(), item_group::group_is_defined(), item::has_flag(), item::in_its_container(), Character::inv, item::is_gun(), item::is_null(), string_id< T >::is_null(), item, item_group::items_from(), item::magazine_default(), NC_ARSONIST, NC_BOUNTY_HUNTER, NC_COWBOY, NC_EVAC_SHOPKEEP, NC_TRADER, one_in(), random_item_from(), rng(), item::set_flag(), item::set_owner(), and type.
Referenced by npc::randomize().
Variable Documentation
effect_bouldering
const efftype_id effect_bouldering("bouldering") ("bouldering") static
Referenced by npc::on_load().
effect_controlled
const efftype_id effect_controlled("controlled") ("controlled") static
Referenced by npc::npc_dismount().
effect_drunk
const efftype_id effect_drunk("drunk") ("drunk") static
Referenced by npc::get_opinion_values().
effect_high
const efftype_id effect_high("high") ("high") static
Referenced by npc::get_opinion_values().
effect_infection
const efftype_id effect_infection("infection") ("infection") static
Referenced by npc::is_stationary().
effect_mending
const efftype_id effect_mending("mending") ("mending") static
Referenced by npc::wear_if_wanted().
effect_npc_flee_player
const efftype_id effect_npc_flee_player("npc_flee_player") ("npc_flee_player") static
Referenced by npc::set_attitude().
effect_npc_suspend
const efftype_id effect_npc_suspend("npc_suspend") ("npc_suspend") static
Referenced by npc::reboot().
effect_pkill1_acetaminophen
const efftype_id effect_pkill1_acetaminophen("pkill1_acetaminophen") ("pkill1_acetaminophen") static
Referenced by npc::took_painkiller().
effect_pkill1_generic
const efftype_id effect_pkill1_generic("pkill1_generic") ("pkill1_generic") static
Referenced by npc::took_painkiller().
effect_pkill1_nsaid
const efftype_id effect_pkill1_nsaid("pkill1_nsaid") ("pkill1_nsaid") static
Referenced by npc::took_painkiller().
effect_pkill2
const efftype_id effect_pkill2("pkill2") ("pkill2") static
Referenced by npc::took_painkiller().
effect_pkill3
const efftype_id effect_pkill3("pkill3") ("pkill3") static
Referenced by npc::took_painkiller().
effect_pkill_l
const efftype_id effect_pkill_l("pkill_l") ("pkill_l") static
Referenced by npc::took_painkiller().
effect_ridden
const efftype_id effect_ridden("ridden") ("ridden") static
Referenced by npc::die(), and npc::npc_dismount().
effect_riding
const efftype_id effect_riding("riding") ("riding") static
Referenced by npc::npc_dismount(), and npc::on_load().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by npc::indoor_voice().
faction_amf
const faction_id faction_amf("amf") ("amf") static
Referenced by npc::make_angry(), and npc::mutiny().
faction_no_faction
const faction_id faction_no_faction("no_faction") ("no_faction") static
Referenced by npc::get_faction(), and npc::make_angry().
faction_your_followers
const faction_id faction_your_followers("your_followers") ("your_followers") static
Referenced by npc::is_ally().
Item_spawn_data_guns_pistol_common
const item_group_id Item_spawn_data_guns_pistol_common("guns_pistol_common") ("guns_pistol_common") static
Referenced by npc::starting_weapon().
Item_spawn_data_guns_rifle_common
const item_group_id Item_spawn_data_guns_rifle_common("guns_rifle_common") ("guns_rifle_common") static
Referenced by npc::starting_weapon().
Item_spawn_data_guns_shotgun_common
const item_group_id Item_spawn_data_guns_shotgun_common("guns_shotgun_common") ("guns_shotgun_common") static
Referenced by npc::starting_weapon().
Item_spawn_data_guns_smg_common
const item_group_id Item_spawn_data_guns_smg_common("guns_smg_common") ("guns_smg_common") static
Referenced by npc::starting_weapon().
Item_spawn_data_npc_eyes
const item_group_id Item_spawn_data_npc_eyes("npc_eyes") ("npc_eyes") static
Referenced by starting_clothes().
Item_spawn_data_survivor_bashing
const item_group_id Item_spawn_data_survivor_bashing("survivor_bashing") ("survivor_bashing") static
Referenced by npc::starting_weapon().
Item_spawn_data_survivor_cutting
const item_group_id Item_spawn_data_survivor_cutting("survivor_cutting") ("survivor_cutting") static
Referenced by npc::starting_weapon().
Item_spawn_data_survivor_stabbing
const item_group_id Item_spawn_data_survivor_stabbing("survivor_stabbing") ("survivor_stabbing") static
Referenced by npc::starting_weapon().
json_flag_CANNIBAL
const json_character_flag json_flag_CANNIBAL("CANNIBAL") ("CANNIBAL") static
Referenced by npc::die().
json_flag_PSYCHOPATH
const json_character_flag json_flag_PSYCHOPATH("PSYCHOPATH") ("PSYCHOPATH") static
Referenced by npc::die().
json_flag_SAPIOVORE
const json_character_flag json_flag_SAPIOVORE("SAPIOVORE") ("SAPIOVORE") static
Referenced by npc::die(), and npc::get_opinion_values().
json_flag_SPIRITUAL
const json_character_flag json_flag_SPIRITUAL("SPIRITUAL") ("SPIRITUAL") static
Referenced by npc::die().
monfaction_bee
const mfaction_str_id monfaction_bee("bee") ("bee") static
Referenced by npc::get_monster_faction().
monfaction_human
const mfaction_str_id monfaction_human("human") ("human") static
Referenced by npc::get_monster_faction().
monfaction_player
const mfaction_str_id monfaction_player("player") ("player") static
Referenced by npc::get_monster_faction().
npc_templates
std::map<string_id<npc_template>, npc_template> npc_templates static
Definition at line 291 of file npc.cpp.
Referenced by npc_template::check_consistency(), npc_template::load(), npc::load_npc_template(), and npc_template::reset().
overmap_location_source_of_ammo
const overmap_location_str_id overmap_location_source_of_ammo("source_of_ammo") ("source_of_ammo") static
overmap_location_source_of_anything
const overmap_location_str_id overmap_location_source_of_anything("source_of_anything") ("source_of_anything") static
overmap_location_source_of_drink
const overmap_location_str_id overmap_location_source_of_drink("source_of_drink") ("source_of_drink") static
overmap_location_source_of_food
const overmap_location_str_id overmap_location_source_of_food("source_of_food") ("source_of_food") static
overmap_location_source_of_guns
const overmap_location_str_id overmap_location_source_of_guns("source_of_guns") ("source_of_guns") static
overmap_location_source_of_safety
const overmap_location_str_id overmap_location_source_of_safety("source_of_safety") ("source_of_safety") static
overmap_location_source_of_weapons
const overmap_location_str_id overmap_location_source_of_weapons("source_of_weapons") ("source_of_weapons") static
skill_archery
const skill_id skill_archery("archery") ("archery") static
Referenced by npc::starting_weapon().
skill_bashing
const skill_id skill_bashing("bashing") ("bashing") static
Referenced by npc::starting_weapon().
skill_cutting
const skill_id skill_cutting("cutting") ("cutting") static
Referenced by npc::starting_weapon().
skill_dodge
const skill_id skill_dodge("dodge") ("dodge") static
Referenced by npc::best_combat_skill().
skill_gun
const skill_id skill_gun("gun") ("gun") static
Referenced by npc::best_combat_skill().
skill_launcher
const skill_id skill_launcher("launcher") ("launcher") static
Referenced by npc::best_combat_skill().
skill_melee
const skill_id skill_melee("melee") ("melee") static
Referenced by npc::best_combat_skill().
skill_pistol
const skill_id skill_pistol("pistol") ("pistol") static
Referenced by npc::starting_weapon().
skill_rifle
const skill_id skill_rifle("rifle") ("rifle") static
Referenced by npc::starting_weapon().
skill_shotgun
const skill_id skill_shotgun("shotgun") ("shotgun") static
Referenced by npc::starting_weapon().
skill_smg
const skill_id skill_smg("smg") ("smg") static
Referenced by npc::starting_weapon().
skill_speech
const skill_id skill_speech("speech") ("speech") static
Referenced by npc::randomize().
skill_stabbing
const skill_id skill_stabbing("stabbing") ("stabbing") static
Referenced by npc::best_combat_skill(), and npc::starting_weapon().
skill_throw
const skill_id skill_throw("throw") ("throw") static
Referenced by npc::starting_weapon().
skill_unarmed
const skill_id skill_unarmed("unarmed") ("unarmed") static
Referenced by npc::best_combat_skill().
trait_BEE
const trait_id trait_BEE("BEE") ("BEE") static
Referenced by npc::get_monster_faction().
trait_DEBUG_MIND_CONTROL
const trait_id trait_DEBUG_MIND_CONTROL("DEBUG_MIND_CONTROL") ("DEBUG_MIND_CONTROL") static
Referenced by npc::will_accept_from_player().
trait_HALLUCINATION
const trait_id trait_HALLUCINATION("HALLUCINATION") ("HALLUCINATION") static
Referenced by npc::on_load().
trait_KILLER
const trait_id trait_KILLER("KILLER") ("KILLER") static
Referenced by npc::die().
trait_MUTE
const trait_id trait_MUTE("MUTE") ("MUTE") static
Referenced by npc::say().
trait_NO_BASH
const trait_id trait_NO_BASH("NO_BASH") ("NO_BASH") static
Referenced by npc::get_pathfinding_settings().
trait_PACIFIST
const trait_id trait_PACIFIST("PACIFIST") ("PACIFIST") static
Referenced by npc::die().
trait_PROF_DICEMASTER
const trait_id trait_PROF_DICEMASTER("PROF_DICEMASTER") ("PROF_DICEMASTER") static
Referenced by npc::time_to_read().
trait_SQUEAMISH
const trait_id trait_SQUEAMISH("SQUEAMISH") ("SQUEAMISH") static
Referenced by npc::wants_to_buy().
trait_TERRIFYING
const trait_id trait_TERRIFYING("TERRIFYING") ("TERRIFYING") static
Referenced by npc::get_opinion_values().