Cataclysm DDA: src/npc_class.cpp File Reference
npc_class.cpp File Reference
#include "npc_class.h"
#include <algorithm>
#include <array>
#include <cstddef>
#include <iterator>
#include <list>
#include <set>
#include <string>
#include <utility>
#include "avatar.h"
#include "condition.h"
#include "debug.h"
#include "dialogue.h"
#include "generic_factory.h"
#include "item_group.h"
#include "itype.h"
#include "json.h"
#include "mutation.h"
#include "rng.h"
#include "skill.h"
#include "trait_group.h"
Functions
template<typename T >
void apply_all_to_unassigned (T &skills)
static distribution load_distribution (const JsonObject &jo)
static distribution load_distribution (const JsonObject &jo, const std::string_view name)
Variables
const npc_class_id NC_ARSONIST ("NC_ARSONIST")
const npc_class_id NC_BARTENDER ("NC_BARTENDER")
const npc_class_id NC_BOUNTY_HUNTER ("NC_BOUNTY_HUNTER")
const npc_class_id NC_COWBOY ("NC_COWBOY")
const npc_class_id NC_CYBORG ("NC_CYBORG")
const npc_class_id NC_DOCTOR ("NC_DOCTOR")
const npc_class_id NC_EVAC_SHOPKEEP ("NC_EVAC_SHOPKEEP")
const npc_class_id NC_HACKER ("NC_HACKER")
const npc_class_id NC_HALLU ("NC_HALLU")
const npc_class_id NC_HUNTER ("NC_HUNTER")
const npc_class_id NC_JUNK_SHOPKEEP ("NC_JUNK_SHOPKEEP")
const npc_class_id NC_NINJA ("NC_NINJA")
const npc_class_id NC_NONE ("NC_NONE")
const npc_class_id NC_SCAVENGER ("NC_SCAVENGER")
const npc_class_id NC_SCIENTIST ("NC_SCIENTIST")
const npc_class_id NC_SHOPKEEP ("NC_SHOPKEEP")
const npc_class_id NC_SOLDIER ("NC_SOLDIER")
const npc_class_id NC_THUG ("NC_THUG")
const npc_class_id NC_TRADER ("NC_TRADER")
static const std::array< npc_class_id, 19 > legacy_ids
static generic_factory< npc_class > npc_class_factory ("npc_class")
Function Documentation
apply_all_to_unassigned()
template<typename T > void apply_all_to_unassigned (T & skills)
Definition at line 100 of file npc_class.cpp.
 {
     auto iter = std::find_if( skills.begin(), skills.end(),
     []( decltype( *begin( skills ) ) &pr ) {
         return pr.first.str() == "ALL";
     } );
     if( iter != skills.end() ) {
         distribution dis = iter->second;
         skills.erase( iter );
         for( const Skill &sk : Skill::skills ) {
             if( skills.count( sk.ident() ) == 0 ) {
                 skills[ sk.ident() ] = dis;
             }
         }
     }
 }
References Skill::skills.
Referenced by npc_class::finalize_all().
load_distribution() [1/2]
static distribution load_distribution (const JsonObject & jo) static
Definition at line 175 of file npc_class.cpp.
 {
     if( jo.has_float( "constant" ) ) {
         return distribution::constant( jo.get_float( "constant" ) );
     }
     if( jo.has_float( "one_in" ) ) {
         return distribution::one_in( jo.get_float( "one_in" ) );
     }
     if( jo.has_array( "dice" ) ) {
         JsonArray jarr = jo.get_array( "dice" );
         return distribution::dice_roll( jarr.get_int( 0 ), jarr.get_int( 1 ) );
     }
     if( jo.has_array( "rng" ) ) {
         JsonArray jarr = jo.get_array( "rng" );
         return distribution::rng_roll( jarr.get_int( 0 ), jarr.get_int( 1 ) );
     }
     if( jo.has_array( "sum" ) ) {
         JsonArray jarr = jo.get_array( "sum" );
         distribution ret = load_distribution( jarr.next_object() );
         while( jarr.has_more() ) {
             ret = ret + load_distribution( jarr.next_object() );
         }
         return ret;
     }
     if( jo.has_array( "mul" ) ) {
         JsonArray jarr = jo.get_array( "mul" );
         distribution ret = load_distribution( jarr.next_object() );
         while( jarr.has_more() ) {
             ret = ret * load_distribution( jarr.next_object() );
         }
         return ret;
     }
     jo.throw_error( "Invalid distribution" );
 }
References distribution::constant(), distribution::dice_roll(), JsonObject::get_array(), JsonObject::get_float(), JsonArray::get_int(), JsonObject::has_array(), JsonObject::has_float(), JsonArray::has_more(), JsonArray::next_object(), distribution::one_in(), cata::hash64_detail::ret, distribution::rng_roll(), and JsonObject::throw_error().
Referenced by npc_class::load(), and load_distribution().
load_distribution() [2/2]
static distribution load_distribution (const JsonObject & jo, const std::string_view name) static
Definition at line 218 of file npc_class.cpp.
 {
     if( !jo.has_member( name ) ) {
         return distribution();
     }
     if( jo.has_float( name ) ) {
         return distribution::constant( jo.get_float( name ) );
     }
     if( jo.has_object( name ) ) {
         JsonObject obj = jo.get_object( name );
         return load_distribution( obj );
     }
     jo.throw_error_at( name, "Invalid distribution type" );
 }
References distribution::constant(), JsonObject::get_float(), JsonObject::get_object(), JsonObject::has_float(), JsonObject::has_member(), JsonObject::has_object(), load_distribution(), om_direction::name(), int_id< T >::obj(), and JsonObject::throw_error_at().
Variable Documentation
legacy_ids
const std::array<npc_class_id, 19> legacy_ids static
Initial value:
= {{
        NC_NONE,
        NC_EVAC_SHOPKEEP,
        NC_SHOPKEEP,
        NC_HACKER,
        NC_CYBORG,
        NC_DOCTOR,
        NC_TRADER,
        NC_NINJA,
        NC_COWBOY,
        NC_SCIENTIST,
        NC_BOUNTY_HUNTER,
        NC_THUG,
        NC_SCAVENGER,
        NC_ARSONIST,
        NC_HUNTER,
        NC_SOLDIER,
        NC_BARTENDER,
        NC_JUNK_SHOPKEEP,
        NC_HALLU
    }
}
Definition at line 45 of file npc_class.cpp.
Referenced by npc_class::check_consistency(), and npc_class::from_legacy_int().
NC_ARSONIST
const npc_class_id NC_ARSONIST("NC_ARSONIST") ("NC_ARSONIST")
Referenced by starting_inv().
NC_BARTENDER
const npc_class_id NC_BARTENDER("NC_BARTENDER") ("NC_BARTENDER")
NC_BOUNTY_HUNTER
const npc_class_id NC_BOUNTY_HUNTER("NC_BOUNTY_HUNTER") ("NC_BOUNTY_HUNTER")
Referenced by starting_inv(), and npc::theft_witness_compare().
NC_COWBOY
const npc_class_id NC_COWBOY("NC_COWBOY") ("NC_COWBOY")
Referenced by starting_inv().
NC_CYBORG
const npc_class_id NC_CYBORG("NC_CYBORG") ("NC_CYBORG")
NC_DOCTOR
const npc_class_id NC_DOCTOR("NC_DOCTOR") ("NC_DOCTOR")
Referenced by game::create_starting_npcs(), and mission_start::place_npc_software().
NC_EVAC_SHOPKEEP
const npc_class_id NC_EVAC_SHOPKEEP("NC_EVAC_SHOPKEEP") ("NC_EVAC_SHOPKEEP")
Referenced by starting_inv().
NC_HACKER
const npc_class_id NC_HACKER("NC_HACKER") ("NC_HACKER")
Referenced by mission_start::place_npc_software().
NC_HALLU
const npc_class_id NC_HALLU("NC_HALLU") ("NC_HALLU")
Referenced by game::spawn_hallucination().
NC_HUNTER
const npc_class_id NC_HUNTER("NC_HUNTER") ("NC_HUNTER")
NC_JUNK_SHOPKEEP
const npc_class_id NC_JUNK_SHOPKEEP("NC_JUNK_SHOPKEEP") ("NC_JUNK_SHOPKEEP")
NC_NINJA
const npc_class_id NC_NINJA("NC_NINJA") ("NC_NINJA")
NC_NONE
const npc_class_id NC_NONE("NC_NONE") ("NC_NONE")
Referenced by game::create_starting_npcs(), mission::mission(), and npc_class::random_common().
NC_SCAVENGER
const npc_class_id NC_SCAVENGER("NC_SCAVENGER") ("NC_SCAVENGER")
NC_SCIENTIST
const npc_class_id NC_SCIENTIST("NC_SCIENTIST") ("NC_SCIENTIST")
Referenced by mission_start::place_npc_software().
NC_SHOPKEEP
const npc_class_id NC_SHOPKEEP("NC_SHOPKEEP") ("NC_SHOPKEEP")
NC_SOLDIER
const npc_class_id NC_SOLDIER("NC_SOLDIER") ("NC_SOLDIER")
NC_THUG
const npc_class_id NC_THUG("NC_THUG") ("NC_THUG")
NC_TRADER
const npc_class_id NC_TRADER("NC_TRADER") ("NC_TRADER")
Referenced by starting_inv().
npc_class_factory
generic_factory<npc_class> npc_class_factory("npc_class") ("npc_class") static
Referenced by npc_class::check_consistency(), npc_class::finalize_all(), npc_class::get_all(), npc_class::load_npc_class(), npc_class::random_common(), and npc_class::reset_npc_classes().