Cataclysm DDA: src/npc.h File Reference
npc.h File Reference
#include <algorithm>
#include <array>
#include <functional>
#include <iosfwd>
#include <iterator>
#include <list>
#include <map>
#include <memory>
#include <new>
#include <optional>
#include <set>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include <vector>
#include "activity_type.h"
#include "auto_pickup.h"
#include "basecamp.h"
#include "calendar.h"
#include "character.h"
#include "color.h"
#include "coordinates.h"
#include "creature.h"
#include "dialogue_chatbin.h"
#include "enums.h"
#include "faction.h"
#include "game_constants.h"
#include "inventory.h"
#include "item.h"
#include "item_location.h"
#include "line.h"
#include "lru_cache.h"
#include "memory_fast.h"
#include "mission_companion.h"
#include "npc_attack.h"
#include "pimpl.h"
#include "point.h"
#include "sounds.h"
#include "string_formatter.h"
#include "translations.h"
#include "type_id.h"
#include "units_fwd.h"
Classes
class job_data
struct npc_companion_mission
struct npc_personality
struct npc_opinion
struct ally_rule_data
struct npc_follower_rules
struct dangerous_sound
struct healing_options
struct npc_short_term_cache
struct npc_combat_memory_cache
struct npc_need_goal_cache
class npc
class standard_npc
An NPC with standard stats.
class npc_template
Namespaces
catacurses
Contains the curses interface used by the whole game.
Macros
#define CATA_SRC_NPC_H
Typedefs
using bionic_id = string_id< bionic_data >
using npc_class_id = string_id< npc_class >
using mission_type_id = string_id< mission_type >
using mfaction_id = int_id< monfaction >
using overmap_location_str_id = string_id< overmap_location >
using drop_location = std::pair< item_location, int >
using drop_locations = std::list< drop_location >
Enumerations
enum npc_attitude : int {
NPCATT_NULL = 0 , NPCATT_TALK , NPCATT_LEGACY_1 , NPCATT_FOLLOW ,
NPCATT_LEGACY_2 , NPCATT_LEAD , NPCATT_WAIT , NPCATT_LEGACY_6 ,
NPCATT_MUG , NPCATT_WAIT_FOR_LEAVE , NPCATT_KILL , NPCATT_FLEE ,
NPCATT_LEGACY_3 , NPCATT_HEAL , NPCATT_LEGACY_4 , NPCATT_LEGACY_5 ,
NPCATT_ACTIVITY , NPCATT_FLEE_TEMP , NPCATT_RECOVER_GOODS , NPCATT_END
}
enum class attitude_group : int { neutral = 0 , hostile , fearful , friendly }
enum npc_mission : int {
NPC_MISSION_NULL = 0 , NPC_MISSION_LEGACY_1 , NPC_MISSION_SHELTER , NPC_MISSION_SHOPKEEP ,
NPC_MISSION_LEGACY_2 , NPC_MISSION_LEGACY_3 , NPC_MISSION_GUARD_ALLY , NPC_MISSION_GUARD ,
NPC_MISSION_GUARD_PATROL , NPC_MISSION_ACTIVITY , NPC_MISSION_TRAVELLING
}
enum npc_need {
need_none , need_ammo , need_weapon , need_gun ,
need_food , need_drink , need_safety , num_needs
}
enum npc_personality_type : int {
NPE_AGGRESSION , NPE_BRAVERY , NPE_COLLECTOR , NPE_ALTRUISM ,
NUM_NPE
}
enum class combat_engagement : int {
NONE = 0 , CLOSE , WEAK , HIT ,
ALL , FREE_FIRE , NO_MOVE
}
enum class combat_skills : int { ALL = 0 , NO_GENERAL , WEAPONS_ONLY }
enum class aim_rule : int { WHEN_CONVENIENT = 0 , SPRAY , PRECISE , STRICTLY_PRECISE }
enum class cbm_recharge_rule : int {
CBM_RECHARGE_ALL = 90 , CBM_RECHARGE_MOST = 75 , CBM_RECHARGE_SOME = 50 , CBM_RECHARGE_LITTLE = 25 ,
CBM_RECHARGE_NONE = 10
}
enum class cbm_reserve_rule : int {
CBM_RESERVE_ALL = 100 , CBM_RESERVE_MOST = 75 , CBM_RESERVE_SOME = 50 , CBM_RESERVE_LITTLE = 25 ,
CBM_RESERVE_NONE = 0
}
enum class ally_rule : int {
DEFAULT = 0 , use_guns = 1 , use_grenades = 2 , use_silent = 4 ,
avoid_friendly_fire = 8 , allow_pick_up = 16 , allow_bash = 32 , allow_sleep = 64 ,
allow_complain = 128 , allow_pulp = 256 , close_doors = 512 , follow_close = 1024 ,
avoid_doors = 2048 , hold_the_line = 4096 , ignore_noise = 8192 , forbid_engage = 16384 ,
follow_distance_2 = 32768 , lock_doors = 65536 , avoid_locks = 131072
}
enum talk_topic_enum {
TALK_NONE = 0 , TALK_DONE , TALK_GUARD , TALK_MISSION_LIST ,
TALK_MISSION_LIST_ASSIGNED , TALK_MISSION_START , TALK_MISSION_DESCRIBE , TALK_MISSION_OFFER ,
TALK_MISSION_ACCEPTED , TALK_MISSION_REJECTED , TALK_MISSION_ADVICE , TALK_MISSION_INQUIRE ,
TALK_MISSION_SUCCESS , TALK_MISSION_SUCCESS_LIE , TALK_MISSION_FAILURE , TALK_MISSION_END ,
TALK_MISSION_REWARD , TALK_EVAC_MERCHANT , TALK_EVAC_MERCHANT_NEW , TALK_EVAC_MERCHANT_PLANS ,
TALK_EVAC_MERCHANT_PLANS2 , TALK_EVAC_MERCHANT_PLANS3 , TALK_EVAC_MERCHANT_WORLD , TALK_EVAC_MERCHANT_HORDES ,
TALK_EVAC_MERCHANT_PRIME_LOOT , TALK_EVAC_MERCHANT_ASK_JOIN , TALK_EVAC_MERCHANT_NO , TALK_EVAC_MERCHANT_HELL_NO ,
TALK_FREE_MERCHANT_STOCKS , TALK_FREE_MERCHANT_STOCKS_NEW , TALK_FREE_MERCHANT_STOCKS_WHY , TALK_FREE_MERCHANT_STOCKS_ALL ,
TALK_FREE_MERCHANT_STOCKS_JERKY , TALK_FREE_MERCHANT_STOCKS_CORNMEAL , TALK_FREE_MERCHANT_STOCKS_FLOUR , TALK_FREE_MERCHANT_STOCKS_SUGAR ,
TALK_FREE_MERCHANT_STOCKS_WINE , TALK_FREE_MERCHANT_STOCKS_BEER , TALK_FREE_MERCHANT_STOCKS_SMMEAT , TALK_FREE_MERCHANT_STOCKS_SMFISH ,
TALK_FREE_MERCHANT_STOCKS_OIL , TALK_FREE_MERCHANT_STOCKS_DELIVERED , TALK_EVAC_GUARD1 , TALK_EVAC_GUARD1_PLACE ,
TALK_EVAC_GUARD1_GOVERNMENT , TALK_EVAC_GUARD1_TRADE , TALK_EVAC_GUARD1_JOIN , TALK_EVAC_GUARD1_JOIN2 ,
TALK_EVAC_GUARD1_JOIN3 , TALK_EVAC_GUARD1_ATTITUDE , TALK_EVAC_GUARD1_JOB , TALK_EVAC_GUARD1_OLDGUARD ,
TALK_EVAC_GUARD1_BYE , TALK_EVAC_GUARD2 , TALK_EVAC_GUARD2_NEW , TALK_EVAC_GUARD2_RULES ,
TALK_EVAC_GUARD2_RULES_BASEMENT , TALK_EVAC_GUARD2_WHO , TALK_EVAC_GUARD2_TRADE , TALK_EVAC_GUARD3 ,
TALK_EVAC_GUARD3_NEW , TALK_EVAC_GUARD3_RULES , TALK_EVAC_GUARD3_HIDE1 , TALK_EVAC_GUARD3_HIDE2 ,
TALK_EVAC_GUARD3_WASTE , TALK_EVAC_GUARD3_DEAD , TALK_EVAC_GUARD3_HOSTILE , TALK_EVAC_GUARD3_INSULT ,
TALK_EVAC_HUNTER , TALK_EVAC_HUNTER_SMELL , TALK_EVAC_HUNTER_DO , TALK_EVAC_HUNTER_LIFE ,
TALK_EVAC_HUNTER_HUNT , TALK_EVAC_HUNTER_SALE , TALK_EVAC_HUNTER_ADVICE , TALK_EVAC_HUNTER_BYE ,
TALK_OLD_GUARD_REP , TALK_OLD_GUARD_REP_NEW , TALK_OLD_GUARD_REP_NEW_DOING , TALK_OLD_GUARD_REP_NEW_DOWNSIDE ,
TALK_OLD_GUARD_REP_WORLD , TALK_OLD_GUARD_REP_WORLD_2NDFLEET , TALK_OLD_GUARD_REP_WORLD_FOOTHOLDS , TALK_OLD_GUARD_REP_ASK_JOIN ,
TALK_ARSONIST , TALK_ARSONIST_NEW , TALK_ARSONIST_DOING , TALK_ARSONIST_DOING_REBAR ,
TALK_ARSONIST_WORLD , TALK_ARSONIST_WORLD_OPTIMISTIC , TALK_ARSONIST_JOIN , TALK_ARSONIST_MUTATION ,
TALK_ARSONIST_MUTATION_INSULT , TALK_SCAVENGER_MERC , TALK_SCAVENGER_MERC_NEW , TALK_SCAVENGER_MERC_TIPS ,
TALK_SCAVENGER_MERC_HIRE , TALK_SCAVENGER_MERC_HIRE_SUCCESS , TALK_SHELTER , TALK_SHELTER_PLANS ,
TALK_SHARE_EQUIPMENT , TALK_GIVE_EQUIPMENT , TALK_DENY_EQUIPMENT , TALK_TRAIN ,
TALK_TRAIN_START , TALK_TRAIN_FORCE , TALK_SUGGEST_FOLLOW , TALK_AGREE_FOLLOW ,
TALK_DENY_FOLLOW , TALK_SHOPKEEP , TALK_LEADER , TALK_LEAVE ,
TALK_PLAYER_LEADS , TALK_LEADER_STAYS , TALK_HOW_MUCH_FURTHER , TALK_FRIEND ,
TALK_FRIEND_GUARD , TALK_DENY_GUARD , TALK_DENY_TRAIN , TALK_DENY_PERSONAL ,
TALK_FRIEND_UNCOMFORTABLE , TALK_COMBAT_COMMANDS , TALK_COMBAT_ENGAGEMENT , TALK_STRANGER_NEUTRAL ,
TALK_STRANGER_WARY , TALK_STRANGER_SCARED , TALK_STRANGER_FRIENDLY , TALK_STRANGER_AGGRESSIVE ,
TALK_MUG , TALK_DESCRIBE_MISSION , TALK_WEAPON_DROPPED , TALK_DEMAND_LEAVE ,
TALK_SIZE_UP , TALK_ASSESS_PERSON , TALK_LOOK_AT , TALK_OPINION ,
NUM_TALK_TOPICS
}
Functions
void parse_tags (std::string &phrase, const Character &u, const Character &me, const itype_id &item_type=itype_id::NULL_ID())
void parse_tags (std::string &phrase, const Character &u, const Character &me, const dialogue &d, const itype_id &item_type=itype_id::NULL_ID())
void parse_tags (std::string &phrase, const talker &u, const talker &me, const dialogue &d, const itype_id &item_type=itype_id::NULL_ID())
std::string npc_attitude_id (npc_attitude)
std::string npc_attitude_name (npc_attitude)
std::string npc_class_name (const npc_class_id &)
std::string npc_class_name_str (const npc_class_id &)
std::string convert_talk_topic (talk_topic_enum old_value)
std::ostream & operator<< (std::ostream &os, const npc_need &need)
npc * pick_follower ()
Opens a menu and allows player to select a friendly NPC.
std::unique_ptr< talker > get_talker_for (npc &guy)
std::unique_ptr< talker > get_talker_for (npc *guy)
Variables
constexpr int8_t NPC_PERSONALITY_MIN = -10
constexpr int8_t NPC_PERSONALITY_MAX = 10
constexpr float NPC_DANGER_VERY_LOW = 5.0f
constexpr float NPC_MONSTER_DANGER_MAX = 150.0f
constexpr float NPC_CHARACTER_DANGER_MAX = 250.0f
constexpr float NPC_COWARDICE_MODIFIER = 0.25f
const std::unordered_map< std::string, combat_engagement > combat_engagement_strs
const std::unordered_map< std::string, aim_rule > aim_rule_strs
const std::unordered_map< std::string, cbm_recharge_rule > cbm_recharge_strs
const std::unordered_map< std::string, cbm_reserve_rule > cbm_reserve_strs
const std::unordered_map< std::string, ally_rule_data > ally_rule_strs
constexpr std::array< direction, 8 > npc_threat_dir
Macro Definition Documentation
CATA_SRC_NPC_H
#define CATA_SRC_NPC_H
Definition at line 3 of file npc.h.
Typedef Documentation
bionic_id
using bionic_id = string_id<bionic_data>
Definition at line 79 of file npc.h.
drop_location
using drop_location = std::pair<item_location, int>
Definition at line 84 of file npc.h.
drop_locations
using drop_locations = std::list<drop_location>
Definition at line 85 of file npc.h.
mfaction_id
using mfaction_id = int_id<monfaction>
Definition at line 82 of file npc.h.
mission_type_id
using mission_type_id = string_id<mission_type>
Definition at line 81 of file npc.h.
npc_class_id
using npc_class_id = string_id<npc_class>
Definition at line 80 of file npc.h.
overmap_location_str_id
using overmap_location_str_id = string_id<overmap_location>
Definition at line 83 of file npc.h.
Enumeration Type Documentation
aim_rule
enum aim_rule : int strong
Enumerator
WHEN_CONVENIENT
SPRAY
PRECISE
STRICTLY_PRECISE
Definition at line 295 of file npc.h.
                     : int {
     // Aim some
     WHEN_CONVENIENT = 0,
     // No concern for ammo efficiency
     SPRAY,
     // Aim when possible, then shoot
     PRECISE,
     // If you can't aim, don't shoot
     STRICTLY_PRECISE
 };
ally_rule
enum ally_rule : int strong
Enumerator
DEFAULT
use_guns
use_grenades
use_silent
avoid_friendly_fire
allow_pick_up
allow_bash
allow_sleep
allow_complain
allow_pulp
close_doors
follow_close
avoid_doors
hold_the_line
ignore_noise
forbid_engage
follow_distance_2
lock_doors
avoid_locks
Definition at line 347 of file npc.h.
                      : int {
     DEFAULT = 0,
     use_guns = 1,
     use_grenades = 2,
     use_silent = 4,
     avoid_friendly_fire = 8,
     allow_pick_up = 16,
     allow_bash = 32,
     allow_sleep = 64,
     allow_complain = 128,
     allow_pulp = 256,
     close_doors = 512,
     follow_close = 1024,
     avoid_doors = 2048,
     hold_the_line = 4096,
     ignore_noise = 8192,
     forbid_engage = 16384,
     follow_distance_2 = 32768,
     lock_doors = 65536,
     avoid_locks = 131072
 };
attitude_group
enum attitude_group : int strong
Enumerator
neutral
hostile
fearful
friendly
Definition at line 134 of file npc.h.
                           : int {
     neutral = 0, // Doesn't particularly mind the player
     hostile, // Not necessarily attacking, but also mugging, exploiting etc.
     fearful, // Run
     friendly // Follow, defend, listen
 };
cbm_recharge_rule
enum cbm_recharge_rule : int strong
Enumerator
CBM_RECHARGE_ALL
CBM_RECHARGE_MOST
CBM_RECHARGE_SOME
CBM_RECHARGE_LITTLE
CBM_RECHARGE_NONE
Definition at line 314 of file npc.h.
                              : int {
     CBM_RECHARGE_ALL = 90,
     CBM_RECHARGE_MOST = 75,
     CBM_RECHARGE_SOME = 50,
     CBM_RECHARGE_LITTLE = 25,
     CBM_RECHARGE_NONE = 10
 };
cbm_reserve_rule
enum cbm_reserve_rule : int strong
Enumerator
CBM_RESERVE_ALL
CBM_RESERVE_MOST
CBM_RESERVE_SOME
CBM_RESERVE_LITTLE
CBM_RESERVE_NONE
Definition at line 331 of file npc.h.
                             : int {
     CBM_RESERVE_ALL = 100,
     CBM_RESERVE_MOST = 75,
     CBM_RESERVE_SOME = 50,
     CBM_RESERVE_LITTLE = 25,
     CBM_RESERVE_NONE = 0
 };
combat_engagement
enum combat_engagement : int strong
Enumerator
NONE
CLOSE
WEAK
HIT
ALL
FREE_FIRE
NO_MOVE
Definition at line 269 of file npc.h.
                              : int {
     NONE = 0,
     CLOSE,
     WEAK,
     HIT,
     ALL,
     FREE_FIRE,
     NO_MOVE
 };
combat_skills
enum combat_skills : int strong
Enumerator
ALL
NO_GENERAL
WEAPONS_ONLY
Definition at line 289 of file npc.h.
                          : int {
     ALL = 0,
     NO_GENERAL,
     WEAPONS_ONLY
 };
npc_attitude
enum npc_attitude : int
Enumerator
NPCATT_NULL
NPCATT_TALK
NPCATT_LEGACY_1
NPCATT_FOLLOW
NPCATT_LEGACY_2
NPCATT_LEAD
NPCATT_WAIT
NPCATT_LEGACY_6
NPCATT_MUG
NPCATT_WAIT_FOR_LEAVE
NPCATT_KILL
NPCATT_FLEE
NPCATT_LEGACY_3
NPCATT_HEAL
NPCATT_LEGACY_4
NPCATT_LEGACY_5
NPCATT_ACTIVITY
NPCATT_FLEE_TEMP
NPCATT_RECOVER_GOODS
NPCATT_END
Definition at line 106 of file npc.h.
                   : int {
     NPCATT_NULL = 0, // Don't care/ignoring player The places this is assigned is on shelter NPC generation, and when you order a NPC to stay in a location, and after talking to a NPC that wanted to talk to you.
     NPCATT_TALK,  // Move to and talk to player
     NPCATT_LEGACY_1,
     NPCATT_FOLLOW,  // Follow the player
     NPCATT_LEGACY_2,
     NPCATT_LEAD,  // Lead the player, wait for them if they're behind
     NPCATT_WAIT,  // Waiting for the player
     NPCATT_LEGACY_6,
     NPCATT_MUG,  // Mug the player
     NPCATT_WAIT_FOR_LEAVE, // Attack the player if our patience runs out
     NPCATT_KILL,  // Kill the player
     NPCATT_FLEE,  // Get away from the player; deprecated
     NPCATT_LEGACY_3,
     NPCATT_HEAL,  // Get to the player and heal them
     NPCATT_LEGACY_4,
     NPCATT_LEGACY_5,
     NPCATT_ACTIVITY, // Perform a mission activity
     NPCATT_FLEE_TEMP, // Get away from the player for a while
     NPCATT_RECOVER_GOODS, // Chase the player to demand stolen goods back
     NPCATT_END
 };
npc_mission
enum npc_mission : int
Enumerator
NPC_MISSION_NULL
NPC_MISSION_LEGACY_1
NPC_MISSION_SHELTER
NPC_MISSION_SHOPKEEP
NPC_MISSION_LEGACY_2
NPC_MISSION_LEGACY_3
NPC_MISSION_GUARD_ALLY
NPC_MISSION_GUARD
NPC_MISSION_GUARD_PATROL
NPC_MISSION_ACTIVITY
NPC_MISSION_TRAVELLING
Definition at line 171 of file npc.h.
                  : int {
     NPC_MISSION_NULL = 0, // Nothing in particular
     NPC_MISSION_LEGACY_1,
     NPC_MISSION_SHELTER, // Stay in shelter, introduce player to game
     NPC_MISSION_SHOPKEEP, // Stay still unless combat or something and sell stuff
     NPC_MISSION_LEGACY_2,
     NPC_MISSION_LEGACY_3,
     NPC_MISSION_GUARD_ALLY, // Assigns an allied NPC to guard a position
     NPC_MISSION_GUARD, // Assigns an non-allied NPC to remain in place
     NPC_MISSION_GUARD_PATROL, // Assigns a non-allied NPC to guard and investigate
     NPC_MISSION_ACTIVITY, // Perform a player_activity until it is complete
     NPC_MISSION_TRAVELLING
 };
npc_need
enum npc_need
Enumerator
need_none
need_ammo
need_weapon
need_gun
need_food
need_drink
need_safety
num_needs
Definition at line 199 of file npc.h.
               {
     need_none,
     need_ammo, need_weapon, need_gun,
     need_food, need_drink, need_safety,
     num_needs
 };
npc_personality_type
enum npc_personality_type : int
Enumerator
NPE_AGGRESSION
NPE_BRAVERY
NPE_COLLECTOR
NPE_ALTRUISM
NUM_NPE
Definition at line 207 of file npc.h.
                           : int {
     NPE_AGGRESSION,
     NPE_BRAVERY,
     NPE_COLLECTOR,
     NPE_ALTRUISM,
     NUM_NPE
 };
talk_topic_enum
enum talk_topic_enum
Enumerator
TALK_NONE
TALK_DONE
TALK_GUARD
TALK_MISSION_LIST
TALK_MISSION_LIST_ASSIGNED
TALK_MISSION_START
TALK_MISSION_DESCRIBE
TALK_MISSION_OFFER
TALK_MISSION_ACCEPTED
TALK_MISSION_REJECTED
TALK_MISSION_ADVICE
TALK_MISSION_INQUIRE
TALK_MISSION_SUCCESS
TALK_MISSION_SUCCESS_LIE
TALK_MISSION_FAILURE
TALK_MISSION_END
TALK_MISSION_REWARD
TALK_EVAC_MERCHANT
TALK_EVAC_MERCHANT_NEW
TALK_EVAC_MERCHANT_PLANS
TALK_EVAC_MERCHANT_PLANS2
TALK_EVAC_MERCHANT_PLANS3
TALK_EVAC_MERCHANT_WORLD
TALK_EVAC_MERCHANT_HORDES
TALK_EVAC_MERCHANT_PRIME_LOOT
TALK_EVAC_MERCHANT_ASK_JOIN
TALK_EVAC_MERCHANT_NO
TALK_EVAC_MERCHANT_HELL_NO
TALK_FREE_MERCHANT_STOCKS
TALK_FREE_MERCHANT_STOCKS_NEW
TALK_FREE_MERCHANT_STOCKS_WHY
TALK_FREE_MERCHANT_STOCKS_ALL
TALK_FREE_MERCHANT_STOCKS_JERKY
TALK_FREE_MERCHANT_STOCKS_CORNMEAL
TALK_FREE_MERCHANT_STOCKS_FLOUR
TALK_FREE_MERCHANT_STOCKS_SUGAR
TALK_FREE_MERCHANT_STOCKS_WINE
TALK_FREE_MERCHANT_STOCKS_BEER
TALK_FREE_MERCHANT_STOCKS_SMMEAT
TALK_FREE_MERCHANT_STOCKS_SMFISH
TALK_FREE_MERCHANT_STOCKS_OIL
TALK_FREE_MERCHANT_STOCKS_DELIVERED
TALK_EVAC_GUARD1
TALK_EVAC_GUARD1_PLACE
TALK_EVAC_GUARD1_GOVERNMENT
TALK_EVAC_GUARD1_TRADE
TALK_EVAC_GUARD1_JOIN
TALK_EVAC_GUARD1_JOIN2
TALK_EVAC_GUARD1_JOIN3
TALK_EVAC_GUARD1_ATTITUDE
TALK_EVAC_GUARD1_JOB
TALK_EVAC_GUARD1_OLDGUARD
TALK_EVAC_GUARD1_BYE
TALK_EVAC_GUARD2
TALK_EVAC_GUARD2_NEW
TALK_EVAC_GUARD2_RULES
TALK_EVAC_GUARD2_RULES_BASEMENT
TALK_EVAC_GUARD2_WHO
TALK_EVAC_GUARD2_TRADE
TALK_EVAC_GUARD3
TALK_EVAC_GUARD3_NEW
TALK_EVAC_GUARD3_RULES
TALK_EVAC_GUARD3_HIDE1
TALK_EVAC_GUARD3_HIDE2
TALK_EVAC_GUARD3_WASTE
TALK_EVAC_GUARD3_DEAD
TALK_EVAC_GUARD3_HOSTILE
TALK_EVAC_GUARD3_INSULT
TALK_EVAC_HUNTER
TALK_EVAC_HUNTER_SMELL
TALK_EVAC_HUNTER_DO
TALK_EVAC_HUNTER_LIFE
TALK_EVAC_HUNTER_HUNT
TALK_EVAC_HUNTER_SALE
TALK_EVAC_HUNTER_ADVICE
TALK_EVAC_HUNTER_BYE
TALK_OLD_GUARD_REP
TALK_OLD_GUARD_REP_NEW
TALK_OLD_GUARD_REP_NEW_DOING
TALK_OLD_GUARD_REP_NEW_DOWNSIDE
TALK_OLD_GUARD_REP_WORLD
TALK_OLD_GUARD_REP_WORLD_2NDFLEET
TALK_OLD_GUARD_REP_WORLD_FOOTHOLDS
TALK_OLD_GUARD_REP_ASK_JOIN
TALK_ARSONIST
TALK_ARSONIST_NEW
TALK_ARSONIST_DOING
TALK_ARSONIST_DOING_REBAR
TALK_ARSONIST_WORLD
TALK_ARSONIST_WORLD_OPTIMISTIC
TALK_ARSONIST_JOIN
TALK_ARSONIST_MUTATION
TALK_ARSONIST_MUTATION_INSULT
TALK_SCAVENGER_MERC
TALK_SCAVENGER_MERC_NEW
TALK_SCAVENGER_MERC_TIPS
TALK_SCAVENGER_MERC_HIRE
TALK_SCAVENGER_MERC_HIRE_SUCCESS
TALK_SHELTER
TALK_SHELTER_PLANS
TALK_SHARE_EQUIPMENT
TALK_GIVE_EQUIPMENT
TALK_DENY_EQUIPMENT
TALK_TRAIN
TALK_TRAIN_START
TALK_TRAIN_FORCE
TALK_SUGGEST_FOLLOW
TALK_AGREE_FOLLOW
TALK_DENY_FOLLOW
TALK_SHOPKEEP
TALK_LEADER
TALK_LEAVE
TALK_PLAYER_LEADS
TALK_LEADER_STAYS
TALK_HOW_MUCH_FURTHER
TALK_FRIEND
TALK_FRIEND_GUARD
TALK_DENY_GUARD
TALK_DENY_TRAIN
TALK_DENY_PERSONAL
TALK_FRIEND_UNCOMFORTABLE
TALK_COMBAT_COMMANDS
TALK_COMBAT_ENGAGEMENT
TALK_STRANGER_NEUTRAL
TALK_STRANGER_WARY
TALK_STRANGER_SCARED
TALK_STRANGER_FRIENDLY
TALK_STRANGER_AGGRESSIVE
TALK_MUG
TALK_DESCRIBE_MISSION
TALK_WEAPON_DROPPED
TALK_DEMAND_LEAVE
TALK_SIZE_UP
TALK_ASSESS_PERSON
TALK_LOOK_AT
TALK_OPINION
NUM_TALK_TOPICS
Definition at line 624 of file npc.h.
                      {
     TALK_NONE = 0, // Used to go back to last subject
     TALK_DONE, // Used to end the conversation
     TALK_GUARD, // End conversation, nothing to be said
     TALK_MISSION_LIST, // List available missions. Intentionally placed above START
     TALK_MISSION_LIST_ASSIGNED, // Same, but for assigned missions.
     TALK_MISSION_START, // NOT USED; start of mission topics
     TALK_MISSION_DESCRIBE, // Describe a mission
     TALK_MISSION_OFFER, // Offer a mission
     TALK_MISSION_ACCEPTED,
     TALK_MISSION_REJECTED,
     TALK_MISSION_ADVICE,
     TALK_MISSION_INQUIRE,
     TALK_MISSION_SUCCESS,
     TALK_MISSION_SUCCESS_LIE, // Lie caught!
     TALK_MISSION_FAILURE,
     TALK_MISSION_END, // NOT USED: end of mission topics
     TALK_MISSION_REWARD, // Intentionally placed below END
     TALK_EVAC_MERCHANT, //17, Located in Refugee Center
     TALK_EVAC_MERCHANT_NEW,
     TALK_EVAC_MERCHANT_PLANS,
     TALK_EVAC_MERCHANT_PLANS2,
     TALK_EVAC_MERCHANT_PLANS3,
     TALK_EVAC_MERCHANT_WORLD,
     TALK_EVAC_MERCHANT_HORDES,
     TALK_EVAC_MERCHANT_PRIME_LOOT,
     TALK_EVAC_MERCHANT_ASK_JOIN,
     TALK_EVAC_MERCHANT_NO,
     TALK_EVAC_MERCHANT_HELL_NO,
     TALK_FREE_MERCHANT_STOCKS,//28, Located in Refugee Center
     TALK_FREE_MERCHANT_STOCKS_NEW,
     TALK_FREE_MERCHANT_STOCKS_WHY,
     TALK_FREE_MERCHANT_STOCKS_ALL,
     TALK_FREE_MERCHANT_STOCKS_JERKY,
     TALK_FREE_MERCHANT_STOCKS_CORNMEAL,
     TALK_FREE_MERCHANT_STOCKS_FLOUR,
     TALK_FREE_MERCHANT_STOCKS_SUGAR,
     TALK_FREE_MERCHANT_STOCKS_WINE,
     TALK_FREE_MERCHANT_STOCKS_BEER,
     TALK_FREE_MERCHANT_STOCKS_SMMEAT,
     TALK_FREE_MERCHANT_STOCKS_SMFISH,
     TALK_FREE_MERCHANT_STOCKS_OIL,
     TALK_FREE_MERCHANT_STOCKS_DELIVERED,
     TALK_EVAC_GUARD1,//42, Located in Refugee Center
     TALK_EVAC_GUARD1_PLACE,
     TALK_EVAC_GUARD1_GOVERNMENT,
     TALK_EVAC_GUARD1_TRADE,
     TALK_EVAC_GUARD1_JOIN,
     TALK_EVAC_GUARD1_JOIN2,
     TALK_EVAC_GUARD1_JOIN3,
     TALK_EVAC_GUARD1_ATTITUDE,
     TALK_EVAC_GUARD1_JOB,
     TALK_EVAC_GUARD1_OLDGUARD,
     TALK_EVAC_GUARD1_BYE,
     TALK_EVAC_GUARD2,//53, Located in Refugee Center
     TALK_EVAC_GUARD2_NEW,
     TALK_EVAC_GUARD2_RULES,
     TALK_EVAC_GUARD2_RULES_BASEMENT,
     TALK_EVAC_GUARD2_WHO,
     TALK_EVAC_GUARD2_TRADE,
     TALK_EVAC_GUARD3,//59, Located in Refugee Center
     TALK_EVAC_GUARD3_NEW,
     TALK_EVAC_GUARD3_RULES,
     TALK_EVAC_GUARD3_HIDE1,
     TALK_EVAC_GUARD3_HIDE2,
     TALK_EVAC_GUARD3_WASTE,
     TALK_EVAC_GUARD3_DEAD,
     TALK_EVAC_GUARD3_HOSTILE,
     TALK_EVAC_GUARD3_INSULT,
     TALK_EVAC_HUNTER,//68, Located in Refugee Center
     TALK_EVAC_HUNTER_SMELL,
     TALK_EVAC_HUNTER_DO,
     TALK_EVAC_HUNTER_LIFE,
     TALK_EVAC_HUNTER_HUNT,
     TALK_EVAC_HUNTER_SALE,
     TALK_EVAC_HUNTER_ADVICE,
     TALK_EVAC_HUNTER_BYE,
     TALK_OLD_GUARD_REP,//76, Located in Refugee Center
     TALK_OLD_GUARD_REP_NEW,
     TALK_OLD_GUARD_REP_NEW_DOING,
     TALK_OLD_GUARD_REP_NEW_DOWNSIDE,
     TALK_OLD_GUARD_REP_WORLD,
     TALK_OLD_GUARD_REP_WORLD_2NDFLEET,
     TALK_OLD_GUARD_REP_WORLD_FOOTHOLDS,
     TALK_OLD_GUARD_REP_ASK_JOIN,
     TALK_ARSONIST,//84, Located in Refugee Center
     TALK_ARSONIST_NEW,
     TALK_ARSONIST_DOING,
     TALK_ARSONIST_DOING_REBAR,
     TALK_ARSONIST_WORLD,
     TALK_ARSONIST_WORLD_OPTIMISTIC,
     TALK_ARSONIST_JOIN,
     TALK_ARSONIST_MUTATION,
     TALK_ARSONIST_MUTATION_INSULT,
     TALK_SCAVENGER_MERC,//93, Located in Refugee Center
     TALK_SCAVENGER_MERC_NEW,
     TALK_SCAVENGER_MERC_TIPS,
     TALK_SCAVENGER_MERC_HIRE,
     TALK_SCAVENGER_MERC_HIRE_SUCCESS,
     TALK_SHELTER,
     TALK_SHELTER_PLANS,
     TALK_SHARE_EQUIPMENT,
     TALK_GIVE_EQUIPMENT,
     TALK_DENY_EQUIPMENT,
     TALK_TRAIN,
     TALK_TRAIN_START,
     TALK_TRAIN_FORCE,
     TALK_SUGGEST_FOLLOW,
     TALK_AGREE_FOLLOW,
     TALK_DENY_FOLLOW,
     TALK_SHOPKEEP,
     TALK_LEADER,
     TALK_LEAVE,
     TALK_PLAYER_LEADS,
     TALK_LEADER_STAYS,
     TALK_HOW_MUCH_FURTHER,
     TALK_FRIEND,
     TALK_FRIEND_GUARD,
     TALK_DENY_GUARD,
     TALK_DENY_TRAIN,
     TALK_DENY_PERSONAL,
     TALK_FRIEND_UNCOMFORTABLE,
     TALK_COMBAT_COMMANDS,
     TALK_COMBAT_ENGAGEMENT,
     TALK_STRANGER_NEUTRAL,
     TALK_STRANGER_WARY,
     TALK_STRANGER_SCARED,
     TALK_STRANGER_FRIENDLY,
     TALK_STRANGER_AGGRESSIVE,
     TALK_MUG,
     TALK_DESCRIBE_MISSION,
     TALK_WEAPON_DROPPED,
     TALK_DEMAND_LEAVE,
     TALK_SIZE_UP,
     TALK_ASSESS_PERSON,
     TALK_LOOK_AT,
     TALK_OPINION,
     NUM_TALK_TOPICS
 };
Function Documentation
convert_talk_topic()
std::string convert_talk_topic (talk_topic_enum old_value)
Definition at line 54 of file savegame_legacy.cpp.
 {
     static const std::unordered_map<talk_topic_enum, std::string> talk_topic_enum_mapping = { {
             // This macro creates the appropriate new names (as string) for each enum value, so one does not
             // have to repeat so much (e.g. 'WRAP(TALK_ARSONIST)' instead of '{ TALK_ARSONIST, "TALK_ARSONIST" }')
             // It also ensures that each name is exactly as the name of the enum value.
 #define WRAP(value) { value, #value }
             WRAP( TALK_NONE ),
             WRAP( TALK_DONE ),
             WRAP( TALK_GUARD ),
             WRAP( TALK_MISSION_LIST ),
             WRAP( TALK_MISSION_LIST_ASSIGNED ),
             WRAP( TALK_MISSION_DESCRIBE ),
             WRAP( TALK_MISSION_OFFER ),
             WRAP( TALK_MISSION_ACCEPTED ),
             WRAP( TALK_MISSION_REJECTED ),
             WRAP( TALK_MISSION_ADVICE ),
             WRAP( TALK_MISSION_INQUIRE ),
             WRAP( TALK_MISSION_SUCCESS ),
             WRAP( TALK_MISSION_SUCCESS_LIE ),
             WRAP( TALK_MISSION_FAILURE ),
             WRAP( TALK_MISSION_REWARD ),
             WRAP( TALK_EVAC_MERCHANT ),
             WRAP( TALK_EVAC_MERCHANT_NEW ),
             WRAP( TALK_EVAC_MERCHANT_PLANS ),
             WRAP( TALK_EVAC_MERCHANT_PLANS2 ),
             WRAP( TALK_EVAC_MERCHANT_PLANS3 ),
             WRAP( TALK_EVAC_MERCHANT_WORLD ),
             WRAP( TALK_EVAC_MERCHANT_HORDES ),
             WRAP( TALK_EVAC_MERCHANT_PRIME_LOOT ),
             WRAP( TALK_EVAC_MERCHANT_ASK_JOIN ),
             WRAP( TALK_EVAC_MERCHANT_NO ),
             WRAP( TALK_EVAC_MERCHANT_HELL_NO ),
             WRAP( TALK_FREE_MERCHANT_STOCKS ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_NEW ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_WHY ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_ALL ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_JERKY ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_CORNMEAL ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_FLOUR ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_SUGAR ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_WINE ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_BEER ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_SMMEAT ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_SMFISH ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_OIL ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_DELIVERED ),
             WRAP( TALK_EVAC_GUARD1 ),
             WRAP( TALK_EVAC_GUARD1_PLACE ),
             WRAP( TALK_EVAC_GUARD1_GOVERNMENT ),
             WRAP( TALK_EVAC_GUARD1_TRADE ),
             WRAP( TALK_EVAC_GUARD1_JOIN ),
             WRAP( TALK_EVAC_GUARD1_JOIN2 ),
             WRAP( TALK_EVAC_GUARD1_JOIN3 ),
             WRAP( TALK_EVAC_GUARD1_ATTITUDE ),
             WRAP( TALK_EVAC_GUARD1_JOB ),
             WRAP( TALK_EVAC_GUARD1_OLDGUARD ),
             WRAP( TALK_EVAC_GUARD1_BYE ),
             WRAP( TALK_EVAC_GUARD2 ),
             WRAP( TALK_EVAC_GUARD2_NEW ),
             WRAP( TALK_EVAC_GUARD2_RULES ),
             WRAP( TALK_EVAC_GUARD2_RULES_BASEMENT ),
             WRAP( TALK_EVAC_GUARD2_WHO ),
             WRAP( TALK_EVAC_GUARD2_TRADE ),
             WRAP( TALK_EVAC_GUARD3 ),
             WRAP( TALK_EVAC_GUARD3_NEW ),
             WRAP( TALK_EVAC_GUARD3_RULES ),
             WRAP( TALK_EVAC_GUARD3_HIDE1 ),
             WRAP( TALK_EVAC_GUARD3_HIDE2 ),
             WRAP( TALK_EVAC_GUARD3_WASTE ),
             WRAP( TALK_EVAC_GUARD3_DEAD ),
             WRAP( TALK_EVAC_GUARD3_HOSTILE ),
             WRAP( TALK_EVAC_GUARD3_INSULT ),
             WRAP( TALK_EVAC_HUNTER ),
             WRAP( TALK_EVAC_HUNTER_SMELL ),
             WRAP( TALK_EVAC_HUNTER_DO ),
             WRAP( TALK_EVAC_HUNTER_LIFE ),
             WRAP( TALK_EVAC_HUNTER_HUNT ),
             WRAP( TALK_EVAC_HUNTER_SALE ),
             WRAP( TALK_EVAC_HUNTER_ADVICE ),
             WRAP( TALK_EVAC_HUNTER_BYE ),
             WRAP( TALK_OLD_GUARD_REP ),
             WRAP( TALK_OLD_GUARD_REP_NEW ),
             WRAP( TALK_OLD_GUARD_REP_NEW_DOING ),
             WRAP( TALK_OLD_GUARD_REP_NEW_DOWNSIDE ),
             WRAP( TALK_OLD_GUARD_REP_WORLD ),
             WRAP( TALK_OLD_GUARD_REP_WORLD_2NDFLEET ),
             WRAP( TALK_OLD_GUARD_REP_WORLD_FOOTHOLDS ),
             WRAP( TALK_OLD_GUARD_REP_ASK_JOIN ),
             WRAP( TALK_ARSONIST ),
             WRAP( TALK_ARSONIST_NEW ),
             WRAP( TALK_ARSONIST_DOING ),
             WRAP( TALK_ARSONIST_DOING_REBAR ),
             WRAP( TALK_ARSONIST_WORLD ),
             WRAP( TALK_ARSONIST_WORLD_OPTIMISTIC ),
             WRAP( TALK_ARSONIST_JOIN ),
             WRAP( TALK_ARSONIST_MUTATION ),
             WRAP( TALK_ARSONIST_MUTATION_INSULT ),
             WRAP( TALK_SCAVENGER_MERC ),
             WRAP( TALK_SCAVENGER_MERC_NEW ),
             WRAP( TALK_SCAVENGER_MERC_TIPS ),
             WRAP( TALK_SCAVENGER_MERC_HIRE ),
             WRAP( TALK_SCAVENGER_MERC_HIRE_SUCCESS ),
             WRAP( TALK_SHELTER ),
             WRAP( TALK_SHELTER_PLANS ),
             WRAP( TALK_SHARE_EQUIPMENT ),
             WRAP( TALK_GIVE_EQUIPMENT ),
             WRAP( TALK_DENY_EQUIPMENT ),
             WRAP( TALK_TRAIN ),
             WRAP( TALK_TRAIN_START ),
             WRAP( TALK_TRAIN_FORCE ),
             WRAP( TALK_SUGGEST_FOLLOW ),
             WRAP( TALK_AGREE_FOLLOW ),
             WRAP( TALK_DENY_FOLLOW ),
             WRAP( TALK_SHOPKEEP ),
             WRAP( TALK_LEADER ),
             WRAP( TALK_LEAVE ),
             WRAP( TALK_PLAYER_LEADS ),
             WRAP( TALK_LEADER_STAYS ),
             WRAP( TALK_HOW_MUCH_FURTHER ),
             WRAP( TALK_FRIEND ),
             WRAP( TALK_FRIEND_GUARD ),
             WRAP( TALK_DENY_GUARD ),
             WRAP( TALK_DENY_TRAIN ),
             WRAP( TALK_DENY_PERSONAL ),
             WRAP( TALK_FRIEND_UNCOMFORTABLE ),
             WRAP( TALK_COMBAT_COMMANDS ),
             WRAP( TALK_COMBAT_ENGAGEMENT ),
             WRAP( TALK_STRANGER_NEUTRAL ),
             WRAP( TALK_STRANGER_WARY ),
             WRAP( TALK_STRANGER_SCARED ),
             WRAP( TALK_STRANGER_FRIENDLY ),
             WRAP( TALK_STRANGER_AGGRESSIVE ),
             WRAP( TALK_MUG ),
             WRAP( TALK_DESCRIBE_MISSION ),
             WRAP( TALK_WEAPON_DROPPED ),
             WRAP( TALK_DEMAND_LEAVE ),
             WRAP( TALK_SIZE_UP ),
             WRAP( TALK_LOOK_AT ),
             WRAP( TALK_OPINION )
         }
     };
 #undef WRAP
     const auto iter = talk_topic_enum_mapping.find( old_value );
     if( iter == talk_topic_enum_mapping.end() ) {
         debugmsg( "could not convert %d to new talk topic string", static_cast<int>( old_value ) );
         return "TALK_NONE";
     }
     return iter->second;
 }
References debugmsg, TALK_AGREE_FOLLOW, TALK_ARSONIST, TALK_ARSONIST_DOING, TALK_ARSONIST_DOING_REBAR, TALK_ARSONIST_JOIN, TALK_ARSONIST_MUTATION, TALK_ARSONIST_MUTATION_INSULT, TALK_ARSONIST_NEW, TALK_ARSONIST_WORLD, TALK_ARSONIST_WORLD_OPTIMISTIC, TALK_COMBAT_COMMANDS, TALK_COMBAT_ENGAGEMENT, TALK_DEMAND_LEAVE, TALK_DENY_EQUIPMENT, TALK_DENY_FOLLOW, TALK_DENY_GUARD, TALK_DENY_PERSONAL, TALK_DENY_TRAIN, TALK_DESCRIBE_MISSION, TALK_DONE, TALK_EVAC_GUARD1, TALK_EVAC_GUARD1_ATTITUDE, TALK_EVAC_GUARD1_BYE, TALK_EVAC_GUARD1_GOVERNMENT, TALK_EVAC_GUARD1_JOB, TALK_EVAC_GUARD1_JOIN, TALK_EVAC_GUARD1_JOIN2, TALK_EVAC_GUARD1_JOIN3, TALK_EVAC_GUARD1_OLDGUARD, TALK_EVAC_GUARD1_PLACE, TALK_EVAC_GUARD1_TRADE, TALK_EVAC_GUARD2, TALK_EVAC_GUARD2_NEW, TALK_EVAC_GUARD2_RULES, TALK_EVAC_GUARD2_RULES_BASEMENT, TALK_EVAC_GUARD2_TRADE, TALK_EVAC_GUARD2_WHO, TALK_EVAC_GUARD3, TALK_EVAC_GUARD3_DEAD, TALK_EVAC_GUARD3_HIDE1, TALK_EVAC_GUARD3_HIDE2, TALK_EVAC_GUARD3_HOSTILE, TALK_EVAC_GUARD3_INSULT, TALK_EVAC_GUARD3_NEW, TALK_EVAC_GUARD3_RULES, TALK_EVAC_GUARD3_WASTE, TALK_EVAC_HUNTER, TALK_EVAC_HUNTER_ADVICE, TALK_EVAC_HUNTER_BYE, TALK_EVAC_HUNTER_DO, TALK_EVAC_HUNTER_HUNT, TALK_EVAC_HUNTER_LIFE, TALK_EVAC_HUNTER_SALE, TALK_EVAC_HUNTER_SMELL, TALK_EVAC_MERCHANT, TALK_EVAC_MERCHANT_ASK_JOIN, TALK_EVAC_MERCHANT_HELL_NO, TALK_EVAC_MERCHANT_HORDES, TALK_EVAC_MERCHANT_NEW, TALK_EVAC_MERCHANT_NO, TALK_EVAC_MERCHANT_PLANS, TALK_EVAC_MERCHANT_PLANS2, TALK_EVAC_MERCHANT_PLANS3, TALK_EVAC_MERCHANT_PRIME_LOOT, TALK_EVAC_MERCHANT_WORLD, TALK_FREE_MERCHANT_STOCKS, TALK_FREE_MERCHANT_STOCKS_ALL, TALK_FREE_MERCHANT_STOCKS_BEER, TALK_FREE_MERCHANT_STOCKS_CORNMEAL, TALK_FREE_MERCHANT_STOCKS_DELIVERED, TALK_FREE_MERCHANT_STOCKS_FLOUR, TALK_FREE_MERCHANT_STOCKS_JERKY, TALK_FREE_MERCHANT_STOCKS_NEW, TALK_FREE_MERCHANT_STOCKS_OIL, TALK_FREE_MERCHANT_STOCKS_SMFISH, TALK_FREE_MERCHANT_STOCKS_SMMEAT, TALK_FREE_MERCHANT_STOCKS_SUGAR, TALK_FREE_MERCHANT_STOCKS_WHY, TALK_FREE_MERCHANT_STOCKS_WINE, TALK_FRIEND, TALK_FRIEND_GUARD, TALK_FRIEND_UNCOMFORTABLE, TALK_GIVE_EQUIPMENT, TALK_GUARD, TALK_HOW_MUCH_FURTHER, TALK_LEADER, TALK_LEADER_STAYS, TALK_LEAVE, TALK_LOOK_AT, TALK_MISSION_ACCEPTED, TALK_MISSION_ADVICE, TALK_MISSION_DESCRIBE, TALK_MISSION_FAILURE, TALK_MISSION_INQUIRE, TALK_MISSION_LIST, TALK_MISSION_LIST_ASSIGNED, TALK_MISSION_OFFER, TALK_MISSION_REJECTED, TALK_MISSION_REWARD, TALK_MISSION_SUCCESS, TALK_MISSION_SUCCESS_LIE, TALK_MUG, TALK_NONE, TALK_OLD_GUARD_REP, TALK_OLD_GUARD_REP_ASK_JOIN, TALK_OLD_GUARD_REP_NEW, TALK_OLD_GUARD_REP_NEW_DOING, TALK_OLD_GUARD_REP_NEW_DOWNSIDE, TALK_OLD_GUARD_REP_WORLD, TALK_OLD_GUARD_REP_WORLD_2NDFLEET, TALK_OLD_GUARD_REP_WORLD_FOOTHOLDS, TALK_OPINION, TALK_PLAYER_LEADS, TALK_SCAVENGER_MERC, TALK_SCAVENGER_MERC_HIRE, TALK_SCAVENGER_MERC_HIRE_SUCCESS, TALK_SCAVENGER_MERC_NEW, TALK_SCAVENGER_MERC_TIPS, TALK_SHARE_EQUIPMENT, TALK_SHELTER, TALK_SHELTER_PLANS, TALK_SHOPKEEP, TALK_SIZE_UP, TALK_STRANGER_AGGRESSIVE, TALK_STRANGER_FRIENDLY, TALK_STRANGER_NEUTRAL, TALK_STRANGER_SCARED, TALK_STRANGER_WARY, TALK_SUGGEST_FOLLOW, TALK_TRAIN, TALK_TRAIN_FORCE, TALK_TRAIN_START, TALK_WEAPON_DROPPED, and WRAP.
Referenced by dialogue_chatbin::deserialize().
get_talker_for() [1/2]
std::unique_ptr<talker> get_talker_for (npc & guy)
Definition at line 3814 of file npc.cpp.
 {
     return std::make_unique<talker_npc>( &guy );
 }
Referenced by npc::die().
get_talker_for() [2/2]
std::unique_ptr<talker> get_talker_for (npc * guy)
Definition at line 3818 of file npc.cpp.
 {
     return std::make_unique<talker_npc>( guy );
 }
npc_attitude_id()
std::string npc_attitude_id (npc_attitude att)
Definition at line 2917 of file npc.cpp.
 {
     static const std::map<npc_attitude, std::string> npc_attitude_ids = {
         { NPCATT_NULL, "NPCATT_NULL" },
         { NPCATT_TALK, "NPCATT_TALK" },
         { NPCATT_FOLLOW, "NPCATT_FOLLOW" },
         { NPCATT_LEAD, "NPCATT_LEAD" },
         { NPCATT_WAIT, "NPCATT_WAIT" },
         { NPCATT_MUG, "NPCATT_MUG" },
         { NPCATT_WAIT_FOR_LEAVE, "NPCATT_WAIT_FOR_LEAVE" },
         { NPCATT_KILL, "NPCATT_KILL" },
         { NPCATT_FLEE, "NPCATT_FLEE" },
         { NPCATT_FLEE_TEMP, "NPCATT_FLEE_TEMP" },
         { NPCATT_HEAL, "NPCATT_HEAL" },
         { NPCATT_ACTIVITY, "NPCATT_ACTIVITY" },
         { NPCATT_RECOVER_GOODS, "NPCATT_RECOVER_GOODS" },
         { NPCATT_LEGACY_1, "NPCATT_LEGACY_1" },
         { NPCATT_LEGACY_2, "NPCATT_LEGACY_2" },
         { NPCATT_LEGACY_3, "NPCATT_LEGACY_3" },
         { NPCATT_LEGACY_4, "NPCATT_LEGACY_4" },
         { NPCATT_LEGACY_5, "NPCATT_LEGACY_5" },
         { NPCATT_LEGACY_6, "NPCATT_LEGACY_6" },
     };
     const auto &iter = npc_attitude_ids.find( att );
     if( iter == npc_attitude_ids.end() ) {
         debugmsg( "Invalid attitude: %d", att );
         return "NPCATT_INVALID";
     }
     return iter->second;
 }
References debugmsg, NPCATT_ACTIVITY, NPCATT_FLEE, NPCATT_FLEE_TEMP, NPCATT_FOLLOW, NPCATT_HEAL, NPCATT_KILL, NPCATT_LEAD, NPCATT_LEGACY_1, NPCATT_LEGACY_2, NPCATT_LEGACY_3, NPCATT_LEGACY_4, NPCATT_LEGACY_5, NPCATT_LEGACY_6, NPCATT_MUG, NPCATT_NULL, NPCATT_RECOVER_GOODS, NPCATT_TALK, NPCATT_WAIT, and NPCATT_WAIT_FOR_LEAVE.
Referenced by npc::form_opinion(), and npc::set_attitude().
npc_attitude_name()
std::string npc_attitude_name (npc_attitude att)
Definition at line 2959 of file npc.cpp.
 {
     switch( att ) {
         // Don't care/ignoring player
         case NPCATT_NULL:
             return _( "Ignoring" );
         // Move to and talk to player
         case NPCATT_TALK:
             return _( "Wants to talk" );
         // Follow the player
         case NPCATT_FOLLOW:
             return _( "Following" );
         // Lead the player, wait for them if they're behind
         case NPCATT_LEAD:
             return _( "Leading" );
         // Waiting for the player
         case NPCATT_WAIT:
             return _( "Waiting for you" );
         // Mug the player
         case NPCATT_MUG:
             return _( "Mugging you" );
         // Attack the player if our patience runs out
         case NPCATT_WAIT_FOR_LEAVE:
             return _( "Waiting for you to leave" );
         // Kill the player
         case NPCATT_KILL:
             return _( "Attacking to kill" );
         // Get away from the player
         case NPCATT_FLEE:
         case NPCATT_FLEE_TEMP:
             return _( "Fleeing" );
         // Get to the player and heal them
         case NPCATT_HEAL:
             return _( "Healing you" );
         case NPCATT_ACTIVITY:
             return _( "Performing a task" );
         case NPCATT_RECOVER_GOODS:
             return _( "Trying to recover stolen goods" );
         case NPCATT_LEGACY_1:
         case NPCATT_LEGACY_2:
         case NPCATT_LEGACY_3:
         case NPCATT_LEGACY_4:
         case NPCATT_LEGACY_5:
         case NPCATT_LEGACY_6:
             return _( "NPC Legacy Attitude" );
         default:
             break;
     }
     debugmsg( "Invalid attitude: %d", att );
     return _( "Unknown attitude" );
 }
References _, debugmsg, NPCATT_ACTIVITY, NPCATT_FLEE, NPCATT_FLEE_TEMP, NPCATT_FOLLOW, NPCATT_HEAL, NPCATT_KILL, NPCATT_LEAD, NPCATT_LEGACY_1, NPCATT_LEGACY_2, NPCATT_LEGACY_3, NPCATT_LEGACY_4, NPCATT_LEGACY_5, NPCATT_LEGACY_6, NPCATT_MUG, NPCATT_NULL, NPCATT_RECOVER_GOODS, NPCATT_TALK, NPCATT_WAIT, and NPCATT_WAIT_FOR_LEAVE.
Referenced by debug_menu::character_edit_menu(), game::list_monsters(), and npc::print_info().
npc_class_name()
std::string npc_class_name (const npc_class_id &)
npc_class_name_str()
std::string npc_class_name_str (const npc_class_id &)
operator<<()
std::ostream& operator<< (std::ostream & os, const npc_need & need)
Definition at line 3258 of file npc.cpp.
 {
     return os << npc::get_need_str_id( need );
 }
References npc::get_need_str_id().
parse_tags() [1/3]
void parse_tags (std::string & phrase, const Character & u, const Character & me, const dialogue & d, const itype_id & item_type = itype_id::NULL_ID())
Definition at line 2063 of file npctalk.cpp.
 {
     parse_tags( phrase, *get_talker_for( u ), *get_talker_for( me ), d, item_type );
 }
References get_talker_for(), parse_tags(), and u.
parse_tags() [2/3]
void parse_tags (std::string & phrase, const Character & u, const Character & me, const itype_id & item_type = itype_id::NULL_ID())
Definition at line 2056 of file npctalk.cpp.
 {
     dialogue d( get_talker_for( u ), get_talker_for( me ) );
     parse_tags( phrase, u, me, d, item_type );
 }
References get_talker_for(), parse_tags(), and u.
Referenced by npc::complain(), talk_response::create_option_line(), mission_ui_impl::draw_selected_description(), npc::execute_action(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), npc::find_corpse_to_pulp(), talker_npc::give_item_to(), npc_temp_orders_menu(), dialogue::opt(), parse_tags(), npc::say(), widget::sym_text_cond(), widget::text_cond(), and try_consume().
parse_tags() [3/3]
void parse_tags (std::string & phrase, const talker & u, const talker & me, const dialogue & d, const itype_id & item_type = itype_id::NULL_ID())
Definition at line 2069 of file npctalk.cpp.
 {
     phrase = SNIPPET.expand( phrase );
     const Character *u_chr = u.get_character();
     const Character *me_chr = me.get_character();
     size_t fa;
     size_t fb;
     size_t fa_;
     std::string tag;
     do {
         fa = phrase.find( '<' );
         fb = phrase.find( '>' );
         // Skip the <color_XXX> and </color> tag
         while( fa != std::string::npos && ( phrase.compare( fa + 1, 6, "color_" ) == 0 ||
                                             phrase.compare( fa + 1, 7, "/color>" ) == 0 ) ) {
             if( phrase.compare( fa + 1, 6, "color_" ) == 0 ) {
                 fa = phrase.find( '<', fa + 7 );
             } else { // phrase.compare(fa + 1, 7, "/color>") == 0
                 fa = phrase.find( '<', fa + 8 );
             }
             fb = phrase.find( '>', fa );
         }
         if( fa != std::string::npos ) {
             size_t nest = 0;
             fa_ = phrase.find( '<', fa + 1 );
             while( fa_ < fb && fa_ != std::string::npos ) {
                 nest++;
                 fa_ = phrase.find( '<', fa_ + 1 );
             }
             while( nest > 0 && fb != std::string::npos ) {
                 nest--;
                 fb = phrase.find( '>', fb + 1 );
             }
         }
         int l = fb - fa + 1;
         if( fa != std::string::npos && fb != std::string::npos ) {
             tag = phrase.substr( fa, fb - fa + 1 );
         } else {
             return;
         }
         const item_location u_weapon = u_chr ? u_chr->get_wielded_item() : item_location();
         const item_location me_weapon = me_chr ? me_chr->get_wielded_item() : item_location();
         // Special, dynamic tags go here
         if( tag == "<yrwp>" ) {
             phrase.replace( fa, l, remove_color_tags( u_weapon->tname() ) );
         } else if( tag == "<mywp>" ) {
             if( me_chr && !me_chr->is_armed() ) {
                 phrase.replace( fa, l, _( "fists" ) );
             } else {
                 phrase.replace( fa, l, remove_color_tags( me_weapon->tname() ) );
             }
         } else if( tag == "<u_name>" ) {
             phrase.replace( fa, l, u.get_name() );
         } else if( tag == "<npc_name>" ) {
             phrase.replace( fa, l, me.get_name() );
         } else if( tag == "<ammo>" ) {
             if( !me_weapon || !me_weapon->is_gun() ) {
                 phrase.replace( fa, l, _( "BADAMMO" ) );
             } else {
                 phrase.replace( fa, l, me_weapon->ammo_current()->nname( 1 ) );
             }
         } else if( tag == "<current_activity>" ) {
             std::string activity_name;
             const npc *guy = dynamic_cast<const npc *>( me_chr );
             if( guy && guy->current_activity_id ) {
                 activity_name = guy->get_current_activity();
             } else {
                 activity_name = _( "doing this and that" );
             }
             phrase.replace( fa, l, activity_name );
         } else if( tag == "<punc>" ) {
             switch( rng( 0, 2 ) ) {
                 case 0:
                     phrase.replace( fa, l, pgettext( "punctuation", "." ) );
                     break;
                 case 1:
                     phrase.replace( fa, l, pgettext( "punctuation", "" ) );
                     break;
                 case 2:
                     phrase.replace( fa, l, pgettext( "punctuation", "!" ) );
                     break;
             }
         } else if( tag == "<mypronoun>" ) {
             std::string npcstr = me.is_male() ? pgettext( "npc", "He" ) : pgettext( "npc", "She" );
             phrase.replace( fa, l, npcstr );
         } else if( tag == "<mypossesivepronoun>" ) {
             std::string npcstr = me.is_male() ? pgettext( "npc", "his" ) : pgettext( "npc", "her" );
             phrase.replace( fa, l, npcstr );
         } else if( tag == "<topic_item>" ) {
             phrase.replace( fa, l, item::nname( item_type, 2 ) );
         } else if( tag == "<topic_item_price>" ) {
             item tmp( item_type );
             phrase.replace( fa, l, format_money( tmp.price( true ) ) );
         } else if( tag == "<topic_item_my_total_price>" ) {
             int price = total_price( me, item_type );
             phrase.replace( fa, l, format_money( price ) );
         } else if( tag == "<topic_item_your_total_price>" ) {
             int price = total_price( u, item_type );
             phrase.replace( fa, l, format_money( price ) );
         } else if( tag == "<interval>" ) {
             const npc *guy = dynamic_cast<const npc *>( me_chr );
             std::string restock_interval = guy ? guy->get_restock_interval() : _( "a few days" );
             phrase.replace( fa, l, restock_interval );
         } else if( tag.find( "<u_val:" ) == 0 ) {
             //adding a user variable to the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             phrase.replace( fa, l, u.get_value( "npctalk_var_" + var ) );
         } else if( tag.find( "<npc_val:" ) == 0 ) {
             //adding a npc variable to the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             phrase.replace( fa, l, me.get_value( "npctalk_var_" + var ) );
         } else if( tag.find( "<global_val:" ) == 0 ) {
             //adding a global variable to the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             global_variables &globvars = get_globals();
             phrase.replace( fa, l, globvars.get_global_value( "npctalk_var_" + var ) );
         } else if( tag.find( "<context_val:" ) == 0 ) {
             //adding a context variable to the string requires dialogue to exist
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             phrase.replace( fa, l, d.get_value( "npctalk_var_" + var ) );
         } else if( tag.find( "<item_name:" ) == 0 ) {
             //embedding an items name in the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             // attempt to cast as an item
             phrase.replace( fa, l, itype_id( var )->nname( 1 ) );
         } else if( tag.find( "<item_description:" ) == 0 ) {
             //embedding an items name in the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             // attempt to cast as an item
             phrase.replace( fa, l, itype_id( var )->description.translated() );
         } else if( tag.find( "<trait_name:" ) == 0 ) {
             //embedding an items name in the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             // attempt to cast as an item
             phrase.replace( fa, l, trait_id( var )->name() );
         } else if( tag.find( "<trait_description:" ) == 0 ) {
             //embedding an items name in the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             // attempt to cast as an item
             phrase.replace( fa, l, trait_id( var )->desc() );
         } else if( tag.find( "<spell_name:" ) == 0 ) {
             //embedding an items name in the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             // attempt to cast as an item
             phrase.replace( fa, l, spell_id( var )->name.translated() );
         } else if( tag.find( "<spell_description:" ) == 0 ) {
             //embedding an items name in the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             // attempt to cast as an item
             phrase.replace( fa, l, spell_id( var )->description.translated() );
         } else if( tag.find( "<city>" ) == 0 ) {
             std::string cityname = "nowhere";
             tripoint_abs_sm abs_sub = get_map().get_abs_sub();
             const city *c = overmap_buffer.closest_city( abs_sub ).city;
             if( c != nullptr ) {
                 cityname = c->name;
             }
             phrase.replace( fa, l, cityname );
         } else if( !tag.empty() ) {
             debugmsg( "Bad tag.  '%s' (%d - %d)", tag.c_str(), fa, fb );
             phrase.replace( fa, fb - fa + 1, "????" );
         }
     } while( fa != std::string::npos && fb != std::string::npos );
 }
References _, item::ammo_current(), c, city_reference::city, overmapbuffer::closest_city(), npc::current_activity_id, debugmsg, snippet_library::expand(), format_money(), map::get_abs_sub(), talker::get_character(), npc::get_current_activity(), global_variables::get_global_value(), get_globals(), get_map(), talker::get_name(), npc::get_restock_interval(), dialogue::get_value(), talker::get_value(), Character::get_wielded_item(), Character::is_armed(), item::is_gun(), talker::is_male(), om_direction::name(), nest, item::nname(), itype::nname(), overmap_buffer, parse_tags(), pgettext, item::price(), remove_color_tags(), rng(), SNIPPET, item::tname(), total_price(), and u.
pick_follower()
npc* pick_follower ()
Opens a menu and allows player to select a friendly NPC.
Definition at line 1219 of file npctalk_funcs.cpp.
 {
     std::vector<npc *> followers;
     std::vector<tripoint> locations;
     for( npc &guy : g->all_npcs() ) {
         if( guy.is_player_ally() && get_player_view().sees( guy ) ) {
             followers.push_back( &guy );
             locations.push_back( guy.pos() );
         }
     }
     pointmenu_cb callback( locations );
     uilist menu;
     menu.text = _( "Select a follower" );
     menu.callback = &callback;
     menu.w_y_setup = 2;
     for( const npc *p : followers ) {
         menu.addentry( -1, true, MENU_AUTOASSIGN, p->get_name() );
     }
     menu.query();
     if( menu.ret < 0 || static_cast<size_t>( menu.ret ) >= followers.size() ) {
         return nullptr;
     }
     return followers[ menu.ret ];
 }
References _, uilist::addentry(), uilist::callback, g, get_player_view(), anonymous_namespace{overmap_location.cpp}::locations, MENU_AUTOASSIGN, uilist::query(), uilist::ret, uilist::text, and uilist::w_y_setup.
Referenced by talk_function::bionic_install_allies(), talk_function::bionic_remove_allies(), and talk_function::copy_npc_rules().
Variable Documentation
aim_rule_strs
const std::unordered_map<std::string, aim_rule> aim_rule_strs
Initial value:
= { {
        { "AIM_WHEN_CONVENIENT", aim_rule::WHEN_CONVENIENT },
        { "AIM_SPRAY", aim_rule::SPRAY },
        { "AIM_PRECISE", aim_rule::PRECISE },
        { "AIM_STRICTLY_PRECISE", aim_rule::STRICTLY_PRECISE }
    }
}
Definition at line 305 of file npc.h.
Referenced by talker_npc::has_ai_rule(), and talker_npc::set_ai_rule().
ally_rule_strs
const std::unordered_map<std::string, ally_rule_data> ally_rule_strs
Definition at line 375 of file npc.h.
Referenced by talker_npc::clear_ai_rule(), npc_follower_rules::deserialize(), talker_npc::has_ai_rule(), npc_temp_orders_menu(), npc_follower_rules::serialize(), talker_npc::set_ai_rule(), and talker_npc::toggle_ai_rule().
cbm_recharge_strs
const std::unordered_map<std::string, cbm_recharge_rule> cbm_recharge_strs
Initial value:
= { {
        { "CBM_RECHARGE_ALL", cbm_recharge_rule::CBM_RECHARGE_ALL },
        { "CBM_RECHARGE_MOST", cbm_recharge_rule::CBM_RECHARGE_MOST },
        { "CBM_RECHARGE_SOME", cbm_recharge_rule::CBM_RECHARGE_SOME },
        { "CBM_RECHARGE_LITTLE", cbm_recharge_rule::CBM_RECHARGE_LITTLE },
        { "CBM_RECHARGE_NONE", cbm_recharge_rule::CBM_RECHARGE_NONE }
    }
}
Definition at line 321 of file npc.h.
Referenced by talker_npc::has_ai_rule(), and talker_npc::set_ai_rule().
cbm_reserve_strs
const std::unordered_map<std::string, cbm_reserve_rule> cbm_reserve_strs
Initial value:
= { {
        { "CBM_RESERVE_ALL", cbm_reserve_rule::CBM_RESERVE_ALL },
        { "CBM_RESERVE_MOST", cbm_reserve_rule::CBM_RESERVE_MOST },
        { "CBM_RESERVE_SOME", cbm_reserve_rule::CBM_RESERVE_SOME },
        { "CBM_RESERVE_LITTLE", cbm_reserve_rule::CBM_RESERVE_LITTLE },
        { "CBM_RESERVE_NONE", cbm_reserve_rule::CBM_RESERVE_NONE }
    }
}
Definition at line 338 of file npc.h.
Referenced by talker_npc::has_ai_rule(), and talker_npc::set_ai_rule().
combat_engagement_strs
const std::unordered_map<std::string, combat_engagement> combat_engagement_strs
Initial value:
= { {
        { "ENGAGE_NONE", combat_engagement::NONE },
        { "ENGAGE_CLOSE", combat_engagement::CLOSE },
        { "ENGAGE_WEAK", combat_engagement::WEAK },
        { "ENGAGE_HIT", combat_engagement::HIT },
        { "ENGAGE_ALL", combat_engagement::ALL },
        { "ENGAGE_FREE_FIRE", combat_engagement::FREE_FIRE },
        { "ENGAGE_NO_MOVE", combat_engagement::NO_MOVE }
    }
}
Definition at line 278 of file npc.h.
Referenced by talker_npc::has_ai_rule(), and talker_npc::set_ai_rule().
NPC_CHARACTER_DANGER_MAX
constexpr float NPC_CHARACTER_DANGER_MAX = 250.0f constexpr
Definition at line 64 of file npc.h.
Referenced by npc::evaluate_character(), and npc::evaluate_self().
NPC_COWARDICE_MODIFIER
constexpr float NPC_COWARDICE_MODIFIER = 0.25f constexpr
Definition at line 65 of file npc.h.
Referenced by npc::assess_danger().
NPC_DANGER_VERY_LOW
constexpr float NPC_DANGER_VERY_LOW = 5.0f constexpr
Definition at line 62 of file npc.h.
Referenced by npc::address_needs(), npc::assess_danger(), npc::avoid_friendly_fire(), npc::evaluate_monster(), npc::regen_ai_cache(), and npc::say().
NPC_MONSTER_DANGER_MAX
constexpr float NPC_MONSTER_DANGER_MAX = 150.0f constexpr
Definition at line 63 of file npc.h.
Referenced by npc::assess_danger(), and npc::evaluate_monster().
NPC_PERSONALITY_MAX
constexpr int8_t NPC_PERSONALITY_MAX = 10 constexpr
Definition at line 61 of file npc.h.
Referenced by npc::randomize().
NPC_PERSONALITY_MIN
constexpr int8_t NPC_PERSONALITY_MIN = -10 constexpr
Definition at line 60 of file npc.h.
Referenced by npc::randomize().
npc_threat_dir
constexpr std::array<direction, 8> npc_threat_dir constexpr
Initial value:
= {
    direction::NORTHWEST, direction::NORTH, direction::NORTHEAST, direction::EAST,
    direction::SOUTHEAST, direction::SOUTH, direction::SOUTHWEST, direction::WEST
}
Definition at line 544 of file npc.h.
Referenced by npc::assess_danger(), npc::good_escape_direction(), and npc::npc().