Cataclysm DDA: src/npcmove.cpp File Reference
npcmove.cpp File Reference
#include "npc.h"
#include <algorithm>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <iterator>
#include <memory>
#include <numeric>
#include <ostream>
#include <tuple>
#include "active_item_cache.h"
#include "activity_handlers.h"
#include "ammo.h"
#include "avatar.h"
#include "basecamp.h"
#include "bionics.h"
#include "bodypart.h"
#include "cata_algo.h"
#include "character.h"
#include "character_id.h"
#include "clzones.h"
#include "colony.h"
#include "coordinates.h"
#include "creature.h"
#include "creature_tracker.h"
#include "damage.h"
#include "debug.h"
#include "dialogue_chatbin.h"
#include "dispersion.h"
#include "effect.h"
#include "enums.h"
#include "event_bus.h"
#include "explosion.h"
#include "field.h"
#include "field_type.h"
#include "flag.h"
#include "flat_set.h"
#include "game.h"
#include "game_constants.h"
#include "gates.h"
#include "gun_mode.h"
#include "item.h"
#include "item_factory.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "material.h"
#include "messages.h"
#include "mission.h"
#include "monster.h"
#include "mtype.h"
#include "npc_attack.h"
#include "npctalk.h"
#include "omdata.h"
#include "options.h"
#include "overmap.h"
#include "overmap_location.h"
#include "overmapbuffer.h"
#include "player_activity.h"
#include "projectile.h"
#include "ranged.h"
#include "ret_val.h"
#include "rng.h"
#include "sounds.h"
#include "stomach.h"
#include "talker.h"
#include "translations.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "viewer.h"
#include "visitable.h"
#include "vehicle_selector.h"
#include "vpart_position.h"
#include "vpart_range.h"
Namespaces
anonymous_namespace{npcmove.cpp}
Enumerations
enum npc_action : int {
npc_undecided = 0 , npc_pause , npc_reload , npc_sleep ,
npc_pickup , npc_heal , npc_use_painkiller , npc_drop_items ,
npc_flee , npc_melee , npc_shoot , npc_look_for_player ,
npc_heal_player , npc_follow_player , npc_follow_embarked , npc_talk_to_player ,
npc_mug_player , npc_goto_to_this_pos , npc_goto_destination , npc_avoid_friendly_fire ,
npc_escape_explosion , npc_noop , npc_reach_attack , npc_do_attack ,
npc_aim , npc_investigate_sound , npc_return_to_guard_pos , npc_player_activity ,
npc_worker_downtime , num_npc_actions
}
Functions
bool anonymous_namespace{npcmove.cpp}::good_for_pickup (const item &it, npc &who, const tripoint &there)
static std::string npc_action_name (npc_action action)
static void print_action (const char *prepend, npc_action action)
static bool compare_sound_alert (const dangerous_sound &sound_a, const dangerous_sound &sound_b)
static bool clear_shot_reach (const tripoint &from, const tripoint &to, bool check_ally=true)
static bool too_close (const tripoint &critter_pos, const tripoint &ally_pos, const int def_radius)
static bool wants_to_reload (const npc &guy, const item &candidate)
static bool wants_to_reload_with (const item &weap, const item &ammo)
static item_location form_loc_recursive (Character *npc, item *node, item *parent)
static std::optional< tripoint > nearest_passable (const tripoint &p, const tripoint &closest_to)
template<typename T >
std::list< item > npc_pickup_from_stack (npc &who, T &items)
static void npc_throw (npc &np, item &it, const tripoint &pos)
static float rate_food (const item &it, int want_nutr, int want_quench)
static bodypart_id bp_affected (npc &who, const efftype_id &effect_type)
Variables
static const activity_id ACT_CRAFT ("ACT_CRAFT")
static const activity_id ACT_FIRSTAID ("ACT_FIRSTAID")
static const activity_id ACT_MOVE_LOOT ("ACT_MOVE_LOOT")
static const activity_id ACT_OPERATION ("ACT_OPERATION")
static const activity_id ACT_PULP ("ACT_PULP")
static const activity_id ACT_SPELLCASTING ("ACT_SPELLCASTING")
static const activity_id ACT_TIDY_UP ("ACT_TIDY_UP")
static const bionic_id bio_ads ("bio_ads")
static const bionic_id bio_blade ("bio_blade")
static const bionic_id bio_chain_lightning ("bio_chain_lightning")
static const bionic_id bio_claws ("bio_claws")
static const bionic_id bio_faraday ("bio_faraday")
static const bionic_id bio_heat_absorb ("bio_heat_absorb")
static const bionic_id bio_heatsink ("bio_heatsink")
static const bionic_id bio_hydraulics ("bio_hydraulics")
static const bionic_id bio_laser ("bio_laser")
static const bionic_id bio_leukocyte ("bio_leukocyte")
static const bionic_id bio_nanobots ("bio_nanobots")
static const bionic_id bio_ods ("bio_ods")
static const bionic_id bio_painkiller ("bio_painkiller")
static const bionic_id bio_plutfilter ("bio_plutfilter")
static const bionic_id bio_radscrubber ("bio_radscrubber")
static const bionic_id bio_shock ("bio_shock")
static const bionic_id bio_soporific ("bio_soporific")
static const damage_type_id damage_bash ("bash")
static const damage_type_id damage_bullet ("bullet")
static const damage_type_id damage_cut ("cut")
static const damage_type_id damage_stab ("stab")
static const efftype_id effect_asthma ("asthma")
static const efftype_id effect_bandaged ("bandaged")
static const efftype_id effect_bite ("bite")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_bouldering ("bouldering")
static const efftype_id effect_catch_up ("catch_up")
static const efftype_id effect_disinfected ("disinfected")
static const efftype_id effect_hit_by_player ("hit_by_player")
static const efftype_id effect_hypovolemia ("hypovolemia")
static const efftype_id effect_infected ("infected")
static const efftype_id effect_lying_down ("lying_down")
static const efftype_id effect_no_sight ("no_sight")
static const efftype_id effect_npc_fire_bad ("npc_fire_bad")
static const efftype_id effect_npc_flee_player ("npc_flee_player")
static const efftype_id effect_npc_player_still_looking ("npc_player_still_looking")
static const efftype_id effect_npc_run_away ("npc_run_away")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_psi_stunned ("psi_stunned")
static const efftype_id effect_stumbled_into_invisible ("stumbled_into_invisible")
static const efftype_id effect_stunned ("stunned")
static const field_type_str_id field_fd_last_known ("fd_last_known")
static const itype_id itype_inhaler ("inhaler")
static const itype_id itype_lsd ("lsd")
static const itype_id itype_oxygen_tank ("oxygen_tank")
static const itype_id itype_smoxygen_tank ("smoxygen_tank")
static const itype_id itype_thorazine ("thorazine")
static const npc_class_id NC_EVAC_SHOPKEEP ("NC_EVAC_SHOPKEEP")
static const skill_id skill_firstaid ("firstaid")
static const trait_id trait_IGNORE_SOUND ("IGNORE_SOUND")
static const trait_id trait_RETURN_TO_START_POS ("RETURN_TO_START_POS")
static const zone_type_id zone_type_NO_NPC_PICKUP ("NO_NPC_PICKUP")
static const zone_type_id zone_type_NPC_RETREAT ("NPC_RETREAT")
static constexpr float MAX_FLOAT = 5000000000.0f
static constexpr int NPC_THIRST_CONSUME = 40
static constexpr int NPC_THIRST_COMPLAIN = 80
static constexpr int NPC_HUNGER_CONSUME = 80
static constexpr int NPC_HUNGER_COMPLAIN = 160
const std::vector< bionic_id > anonymous_namespace{npcmove.cpp}::defense_cbms
const std::vector< bionic_id > anonymous_namespace{npcmove.cpp}::health_cbms
const std::vector< bionic_id > anonymous_namespace{npcmove.cpp}::weapon_cbms
const int anonymous_namespace{npcmove.cpp}::avoidance_vehicles_radius = 5
Enumeration Type Documentation
npc_action
enum npc_action : int
Enumerator
npc_undecided
npc_pause
npc_reload
npc_sleep
npc_pickup
npc_heal
npc_use_painkiller
npc_drop_items
npc_flee
npc_melee
npc_shoot
npc_look_for_player
npc_heal_player
npc_follow_player
npc_follow_embarked
npc_talk_to_player
npc_mug_player
npc_goto_to_this_pos
npc_goto_destination
npc_avoid_friendly_fire
npc_escape_explosion
npc_noop
npc_reach_attack
npc_do_attack
npc_aim
npc_investigate_sound
npc_return_to_guard_pos
npc_player_activity
npc_worker_downtime
num_npc_actions
Definition at line 166 of file npcmove.cpp.
                 : int {
     npc_undecided = 0,
     npc_pause,
     npc_reload, npc_sleep,
     npc_pickup,
     npc_heal, npc_use_painkiller, npc_drop_items,
     npc_flee, npc_melee, npc_shoot,
     npc_look_for_player, npc_heal_player, npc_follow_player, npc_follow_embarked,
     npc_talk_to_player, npc_mug_player,
     npc_goto_to_this_pos,
     npc_goto_destination,
     npc_avoid_friendly_fire,
     npc_escape_explosion,
     npc_noop,
     npc_reach_attack,
     npc_do_attack,
     npc_aim,
     npc_investigate_sound,
     npc_return_to_guard_pos,
     npc_player_activity,
     npc_worker_downtime,
     num_npc_actions
 };
Function Documentation
bp_affected()
static bodypart_id bp_affected (npc & who, const efftype_id & effect_type) static
Definition at line 5125 of file npcmove.cpp.
 {
     bodypart_id ret;
     int highest_intensity = INT_MIN;
     for( const bodypart_id &bp : who.get_all_body_parts() ) {
         const effect &eff = who.get_effect( effect_type, bp );
         if( !eff.is_null() && eff.get_intensity() > highest_intensity ) {
             ret = bp;
             highest_intensity = eff.get_intensity();
         }
     }
     return ret;
 }
References bp, Creature::get_all_body_parts(), Creature::get_effect(), effect::get_intensity(), effect::is_null(), and cata::hash64_detail::ret.
Referenced by npc::complain().
clear_shot_reach()
static bool clear_shot_reach (const tripoint & from, const tripoint & to, bool check_ally = true) static
Definition at line 242 of file npcmove.cpp.
 {
     std::vector<tripoint> path = line_to( from, to );
     path.pop_back();
     creature_tracker &creatures = get_creature_tracker();
     for( const tripoint &p : path ) {
         Creature *inter = creatures.creature_at( p );
         if( check_ally && inter != nullptr ) {
             return false;
         }
         if( get_map().impassable( p ) ) {
             return false;
         }
     }
     return true;
 }
References creature_tracker::creature_at(), get_creature_tracker(), get_map(), impassable, and line_to().
Referenced by npc::assess_danger().
compare_sound_alert()
bool compare_sound_alert (const dangerous_sound & sound_a, const dangerous_sound & sound_b) static
Definition at line 234 of file npcmove.cpp.
 {
     if( sound_a.type != sound_b.type ) {
         return sound_a.type < sound_b.type;
     }
     return sound_a.volume < sound_b.volume;
 }
References dangerous_sound::type, and dangerous_sound::volume.
Referenced by npc::move().
form_loc_recursive()
static item_location form_loc_recursive (Character * npc, item * node, item * parent) static
Definition at line 2099 of file npcmove.cpp.
 {
     if( parent ) {
         return item_location( form_loc_recursive( npc, parent, npc->find_parent( *parent ) ), node );
     }
     return item_location( *npc, node );
 }
References visitable::find_parent().
Referenced by npc::find_reloadable().
nearest_passable()
static std::optional<tripoint> nearest_passable (const tripoint & p, const tripoint & closest_to) static
Definition at line 3401 of file npcmove.cpp.
 {
     map &here = get_map();
     if( here.passable( p ) ) {
         return p;
     }
     // We need to path to adjacent tile, not the exact one
     // Let's pick the closest one to us that is passable
     std::vector<tripoint> candidates = closest_points_first( p, 1 );
     std::sort( candidates.begin(), candidates.end(), [ closest_to ]( const tripoint & l,
     const tripoint & r ) {
         return rl_dist( closest_to, l ) < rl_dist( closest_to, r );
     } );
     auto iter = std::find_if( candidates.begin(), candidates.end(), [&here]( const tripoint & pt ) {
         return here.passable( pt );
     } );
     if( iter != candidates.end() ) {
         return *iter;
     }
     return std::nullopt;
 }
References closest_points_first(), get_map(), and map::passable().
Referenced by npc::find_item(), and npc::pick_up_item().
npc_action_name()
std::string npc_action_name (npc_action action) static
Definition at line 5021 of file npcmove.cpp.
 {
     switch( action ) {
         case npc_undecided:
             return "Undecided";
         case npc_pause:
             return "Pause";
         case npc_worker_downtime:
             return "Relaxing";
         case npc_reload:
             return "Reload";
         case npc_investigate_sound:
             return "Investigate sound";
         case npc_return_to_guard_pos:
             return "Returning to guard position";
         case npc_sleep:
             return "Sleep";
         case npc_pickup:
             return "Pick up items";
         case npc_heal:
             return "Heal self";
         case npc_use_painkiller:
             return "Use painkillers";
         case npc_drop_items:
             return "Drop items";
         case npc_flee:
             return "Flee";
         case npc_melee:
             return "Melee";
         case npc_reach_attack:
             return "Reach attack";
         case npc_aim:
             return "Aim";
         case npc_shoot:
             return "Shoot";
         case npc_look_for_player:
             return "Look for player";
         case npc_heal_player:
             return "Heal player or ally";
         case npc_follow_player:
             return "Follow player";
         case npc_follow_embarked:
             return "Follow player (embarked)";
         case npc_talk_to_player:
             return "Talk to player";
         case npc_mug_player:
             return "Mug player";
         case npc_goto_destination:
             return "Go to destination";
         case npc_avoid_friendly_fire:
             return "Avoid friendly fire";
         case npc_escape_explosion:
             return "Escape explosion";
         case npc_player_activity:
             return "Performing activity";
         case npc_noop:
             return "Do nothing";
         case npc_do_attack:
             return "Attack";
         case npc_goto_to_this_pos:
             return "Go to position";
         case num_npc_actions:
             return "Unnamed action";
     }
     return "Unnamed action";
 }
References action, npc_aim, npc_avoid_friendly_fire, npc_do_attack, npc_drop_items, npc_escape_explosion, npc_flee, npc_follow_embarked, npc_follow_player, npc_goto_destination, npc_goto_to_this_pos, npc_heal, npc_heal_player, npc_investigate_sound, npc_look_for_player, npc_melee, npc_mug_player, npc_noop, npc_pause, npc_pickup, npc_player_activity, npc_reach_attack, npc_reload, npc_return_to_guard_pos, npc_shoot, npc_sleep, npc_talk_to_player, npc_undecided, npc_use_painkiller, npc_worker_downtime, and num_npc_actions.
Referenced by npc::execute_action(), npc::move(), and print_action().
npc_pickup_from_stack()
template<typename T > std::list<item> npc_pickup_from_stack (npc & who, T & items)
Definition at line 3771 of file npcmove.cpp.
 {
     std::list<item> picked_up;
     for( auto iter = items.begin(); iter != items.end(); ) {
         const item &it = *iter;
         if( who.can_take_that( it ) && who.wants_take_that( it ) ) {
             picked_up.push_back( it );
             iter = items.erase( iter );
         } else {
             ++iter;
         }
     }
     return picked_up;
 }
References npc::can_take_that(), and npc::wants_take_that().
Referenced by npc::pick_up_item_map(), and npc::pick_up_item_vehicle().
npc_throw()
static void npc_throw (npc & np, item & it, const tripoint & pos) static
Definition at line 4156 of file npcmove.cpp.
 {
     add_msg_if_player_sees( np, _( "%1$s throws a %2$s." ), np.get_name(), it.tname() );
     int stack_size = -1;
     if( it.count_by_charges() ) {
         stack_size = it.charges;
         it.charges = 1;
     }
     if( !np.is_hallucination() ) { // hallucinations only pretend to throw
         np.throw_item( pos, it );
     }
     // Throw a single charge of a stacking object.
     if( stack_size == -1 || stack_size == 1 ) {
         np.i_rem( &it );
     } else {
         it.charges = stack_size - 1;
     }
 }
References _, add_msg_if_player_sees(), item::charges, item::count_by_charges(), Character::get_name(), Character::i_rem(), npc::is_hallucination(), math_opers::pos(), Character::throw_item(), and item::tname().
Referenced by npc::alt_attack().
print_action()
void print_action (const char * prepend, npc_action action) static
Definition at line 5089 of file npcmove.cpp.
 {
     if( action != npc_undecided ) {
         add_msg_debug( debugmode::DF_NPC, prepend, npc_action_name( action ) );
     }
 }
References action, add_msg_debug, debugmode::DF_NPC, npc_action_name(), and npc_undecided.
Referenced by npc::move().
rate_food()
static float rate_food (const item & it, int want_nutr, int want_quench) static
Definition at line 4450 of file npcmove.cpp.
 {
     const auto &food = it.get_comestible();
     if( !food ) {
         return 0.0f;
     }
     // Don't eat it if it's filled with parasites
     if( food->parasites && !it.has_flag( flag_NO_PARASITES ) ) {
         return 0.0;
     }
     // TODO: Use the actual nutrition for this food, rather than the default?
     int nutr = food->get_default_nutr();
     int quench = food->quench;
     if( nutr <= 0 && quench <= 0 ) {
         // Not food - may be salt, drugs etc.
         return 0.0f;
     }
     if( !it.type->use_methods.empty() ) {
         // TODO: Get a good method of telling apart:
         // raw meat (parasites - don't eat unless mutant)
         // zed meat (poison - don't eat unless mutant)
         // alcohol (debuffs, health drop - supplement diet but don't bulk-consume)
         // caffeine (fine to consume, but expensive and prevents sleep)
         // hallucination mushrooms (NPCs don't hallucinate, so don't eat those)
         // honeycomb (harmless iuse)
         // royal jelly (way too expensive to eat as food)
         // mutagenic crap (don't eat, we want player to micromanage muties)
         // marloss (NPCs don't turn fungal)
         // weed brownies (small debuff)
         // seeds (too expensive)
         // For now skip all of those
         return 0.0f;
     }
     double relative_rot = it.get_relative_rot();
     // Don't eat rotten food.
     if( relative_rot >= 1.0f ) {
         // TODO: Allow sapro mutants to eat it anyway and make them prefer it
         return 0.0f;
     }
     // For non-rotten food, we have a starting weight in the range 1-10
     // The closer it is to expiring, the more we should aim to eat it.
     float weight = std::max( 1.0, 10.0 * relative_rot );
     // TODO: I feel like we should exclude *really* un-fun foods (flour, hot sauce, etc)
     //       rather than discount them. Eating cooked liver is fine, eating raw flour... :/
     //       Likewise, *fun* foods should be boosted in attractiveness.
     if( it.get_comestible_fun() < 0 ) {
         // This helps to avoid eating stuff like flour
         weight /= ( -it.get_comestible_fun() ) + 1;
     }
     // NPCs will avoid unhealthy foods.
     if( food->healthy < 0 ) {
         weight /= ( -food->healthy ) + 1;
     }
     // Avoid wasting quench values unless it's about to rot away
     if( relative_rot < 0.9f && quench > want_quench ) {
         // TODO: This can remove a food as a candidate entirely, which means
         //       an NPC could avoid eating a slightly hydrating but calorie-dense
         //       food because they're "not thirsty".
         weight -= ( 1.0f - relative_rot ) * ( quench - want_quench );
     }
     if( quench < 0 && want_quench > 0 && want_nutr < want_quench ) {
         // Avoid stuff that makes us thirsty when we're more thirsty than hungry
         weight = weight * want_nutr / want_quench;
     }
     if( nutr > want_nutr ) {
         // Discount fresh foods that are bigger than our hunger.
         if( relative_rot < 0.9f ) {
             weight /= nutr - want_nutr;
         }
     }
     // NPCs won't eat poison food unless it's only a little poisoned
     if( it.poison > 0 ) {
         weight -= it.poison;
     }
     return weight;
 }
References flag_NO_PARASITES, item::get_comestible(), item::get_comestible_fun(), item::get_relative_rot(), item::has_flag(), max(), item::poison, item::type, and itype::use_methods.
Referenced by npc::consume_food().
too_close()
static bool too_close (const tripoint & critter_pos, const tripoint & ally_pos, const int def_radius) static
Definition at line 682 of file npcmove.cpp.
 {
     return rl_dist( critter_pos, ally_pos ) <= def_radius;
 }
References rl_dist().
Referenced by npc::assess_danger().
wants_to_reload()
static bool wants_to_reload (const npc & guy, const item & candidate) static
Definition at line 2061 of file npcmove.cpp.
 {
     if( !candidate.is_reloadable() ) {
         if( !candidate.is_magazine() || !candidate.is_gun() ) {
             add_msg_debug( debugmode::DF_NPC_ITEMAI, "%s considered reloading %s, but decided it was silly.",
                            guy.name, candidate.tname() );
         } else {
             add_msg_debug( debugmode::DF_NPC_ITEMAI,
                            "%s considered reloading %s, but feels it is inappropriate.", guy.name, candidate.tname() );
         }
         return false;
     }
     if( !guy.can_reload( candidate ) ) {
         add_msg_debug( debugmode::DF_NPC_ITEMAI, "%s doesn't think they can reload %s.", guy.name,
                        candidate.tname() );
         return false;
     }
     const int required = candidate.ammo_required();
     // TODO: Add bandolier check here, once they can be reloaded
     if( required < 1 && !candidate.is_magazine() ) {
         add_msg_debug( debugmode::DF_NPC_ITEMAI, "%s couldn't find requirements to reload %s.", guy.name,
                        candidate.tname() );
         return false;
     }
     add_msg_debug( debugmode::DF_NPC_ITEMAI, "%s might try reloading %s.", guy.name,
                    candidate.tname() );
     return true;
 }
References add_msg_debug, item::ammo_required(), Character::can_reload(), debugmode::DF_NPC_ITEMAI, item::is_gun(), item::is_magazine(), item::is_reloadable(), Character::name, and item::tname().
Referenced by npc::can_reload_current(), and npc::find_reloadable().
wants_to_reload_with()
static bool wants_to_reload_with (const item & weap, const item & ammo) static
Definition at line 2093 of file npcmove.cpp.
 {
     return !ammo.is_magazine() || ammo.ammo_remaining() > weap.ammo_remaining();
 }
References item::ammo_remaining(), and item::is_magazine().
Referenced by npc::find_reloadable(), and npc::find_usable_ammo().
Variable Documentation
ACT_CRAFT
const activity_id ACT_CRAFT("ACT_CRAFT") ("ACT_CRAFT") static
Referenced by npc::do_player_activity().
ACT_FIRSTAID
const activity_id ACT_FIRSTAID("ACT_FIRSTAID") ("ACT_FIRSTAID") static
Referenced by npc::heal_player(), and npc::heal_self().
ACT_MOVE_LOOT
const activity_id ACT_MOVE_LOOT("ACT_MOVE_LOOT") ("ACT_MOVE_LOOT") static
Referenced by npc::find_job_to_perform().
ACT_OPERATION
const activity_id ACT_OPERATION("ACT_OPERATION") ("ACT_OPERATION") static
Referenced by npc::move().
ACT_PULP
const activity_id ACT_PULP("ACT_PULP") ("ACT_PULP") static
Referenced by npc::address_needs().
ACT_SPELLCASTING
const activity_id ACT_SPELLCASTING("ACT_SPELLCASTING") ("ACT_SPELLCASTING") static
Referenced by npc::move().
ACT_TIDY_UP
const activity_id ACT_TIDY_UP("ACT_TIDY_UP") ("ACT_TIDY_UP") static
Referenced by npc::do_player_activity().
bio_ads
const bionic_id bio_ads("bio_ads") ("bio_ads") static
bio_blade
const bionic_id bio_blade("bio_blade") ("bio_blade") static
bio_chain_lightning
const bionic_id bio_chain_lightning("bio_chain_lightning") ("bio_chain_lightning") static
bio_claws
const bionic_id bio_claws("bio_claws") ("bio_claws") static
bio_faraday
const bionic_id bio_faraday("bio_faraday") ("bio_faraday") static
bio_heat_absorb
const bionic_id bio_heat_absorb("bio_heat_absorb") ("bio_heat_absorb") static
bio_heatsink
const bionic_id bio_heatsink("bio_heatsink") ("bio_heatsink") static
bio_hydraulics
const bionic_id bio_hydraulics("bio_hydraulics") ("bio_hydraulics") static
Referenced by npc::deactivate_combat_cbms(), and npc::execute_action().
bio_laser
const bionic_id bio_laser("bio_laser") ("bio_laser") static
bio_leukocyte
const bionic_id bio_leukocyte("bio_leukocyte") ("bio_leukocyte") static
bio_nanobots
const bionic_id bio_nanobots("bio_nanobots") ("bio_nanobots") static
Referenced by npc::address_needs().
bio_ods
const bionic_id bio_ods("bio_ods") ("bio_ods") static
bio_painkiller
const bionic_id bio_painkiller("bio_painkiller") ("bio_painkiller") static
Referenced by npc::address_needs().
bio_plutfilter
const bionic_id bio_plutfilter("bio_plutfilter") ("bio_plutfilter") static
bio_radscrubber
const bionic_id bio_radscrubber("bio_radscrubber") ("bio_radscrubber") static
Referenced by npc::complain().
bio_shock
const bionic_id bio_shock("bio_shock") ("bio_shock") static
bio_soporific
const bionic_id bio_soporific("bio_soporific") ("bio_soporific") static
Referenced by npc::execute_action(), and npc::move_pause().
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by npc::estimate_armour().
damage_bullet
const damage_type_id damage_bullet("bullet") ("bullet") static
Referenced by npc::estimate_armour().
damage_cut
const damage_type_id damage_cut("cut") ("cut") static
Referenced by npc::estimate_armour().
damage_stab
const damage_type_id damage_stab("stab") ("stab") static
Referenced by npc::estimate_armour().
effect_asthma
const efftype_id effect_asthma("asthma") ("asthma") static
Referenced by npc::heal_self(), and npc::move().
effect_bandaged
const efftype_id effect_bandaged("bandaged") ("bandaged") static
Referenced by npc::patient_assessment().
effect_bite
const efftype_id effect_bite("bite") ("bite") static
Referenced by npc::complain(), and npc::patient_assessment().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by npc::complain(), npc::evaluate_character(), npc::evaluate_self(), and npc::patient_assessment().
effect_bouldering
const efftype_id effect_bouldering("bouldering") ("bouldering") static
Referenced by npc::move_to().
effect_catch_up
const efftype_id effect_catch_up("catch_up") ("catch_up") static
Referenced by npc::address_player().
effect_disinfected
const efftype_id effect_disinfected("disinfected") ("disinfected") static
Referenced by npc::patient_assessment().
effect_hit_by_player
const efftype_id effect_hit_by_player("hit_by_player") ("hit_by_player") static
Referenced by npc::assess_danger().
effect_hypovolemia
const efftype_id effect_hypovolemia("hypovolemia") ("hypovolemia") static
Referenced by npc::complain().
effect_infected
const efftype_id effect_infected("infected") ("infected") static
Referenced by npc::complain(), and npc::patient_assessment().
effect_lying_down
const efftype_id effect_lying_down("lying_down") ("lying_down") static
Referenced by npc::execute_action().
effect_no_sight
const efftype_id effect_no_sight("no_sight") ("no_sight") static
Referenced by npc::move_to().
effect_npc_fire_bad
const efftype_id effect_npc_fire_bad("npc_fire_bad") ("npc_fire_bad") static
Referenced by npc::act_on_danger_assessment(), npc::assess_danger(), npc::move(), and npc::regen_ai_cache().
effect_npc_flee_player
const efftype_id effect_npc_flee_player("npc_flee_player") ("npc_flee_player") static
Referenced by npc::move().
effect_npc_player_still_looking
const efftype_id effect_npc_player_still_looking("npc_player_still_looking") ("npc_player_still_looking") static
Referenced by npc::regen_ai_cache().
effect_npc_run_away
const efftype_id effect_npc_run_away("npc_run_away") ("npc_run_away") static
Referenced by npc::act_on_danger_assessment(), npc::assess_danger(), npc::evaluate_character(), npc::move(), and npc::regen_ai_cache().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by npc::move_pause().
effect_psi_stunned
const efftype_id effect_psi_stunned("psi_stunned") ("psi_stunned") static
Referenced by npc::move_to().
effect_stumbled_into_invisible
const efftype_id effect_stumbled_into_invisible("stumbled_into_invisible") ("stumbled_into_invisible") static
Referenced by npc::move_to().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by npc::move_to().
field_fd_last_known
const field_type_str_id field_fd_last_known("fd_last_known") ("fd_last_known") static
Referenced by npc::move_to().
itype_inhaler
const itype_id itype_inhaler("inhaler") ("inhaler") static
Referenced by npc::move().
itype_lsd
const itype_id itype_lsd("lsd") ("lsd") static
Referenced by npc::find_item().
itype_oxygen_tank
const itype_id itype_oxygen_tank("oxygen_tank") ("oxygen_tank") static
Referenced by npc::move().
itype_smoxygen_tank
const itype_id itype_smoxygen_tank("smoxygen_tank") ("smoxygen_tank") static
Referenced by npc::move().
itype_thorazine
const itype_id itype_thorazine("thorazine") ("thorazine") static
Referenced by npc::find_item().
MAX_FLOAT
constexpr float MAX_FLOAT = 5000000000.0f static constexpr
Definition at line 155 of file npcmove.cpp.
Referenced by npc::good_escape_direction().
NC_EVAC_SHOPKEEP
const npc_class_id NC_EVAC_SHOPKEEP("NC_EVAC_SHOPKEEP") ("NC_EVAC_SHOPKEEP") static
Referenced by npc::witness_thievery().
NPC_HUNGER_COMPLAIN
constexpr int NPC_HUNGER_COMPLAIN = 160 static constexpr
Definition at line 164 of file npcmove.cpp.
Referenced by npc::complain().
NPC_HUNGER_CONSUME
constexpr int NPC_HUNGER_CONSUME = 80 static constexpr
Definition at line 163 of file npcmove.cpp.
Referenced by npc::address_needs().
NPC_THIRST_COMPLAIN
constexpr int NPC_THIRST_COMPLAIN = 80 static constexpr
Definition at line 162 of file npcmove.cpp.
Referenced by npc::complain().
NPC_THIRST_CONSUME
constexpr int NPC_THIRST_CONSUME = 40 static constexpr
Definition at line 161 of file npcmove.cpp.
Referenced by npc::address_needs().
skill_firstaid
const skill_id skill_firstaid("firstaid") ("firstaid") static
Referenced by npc::address_needs().
trait_IGNORE_SOUND
const trait_id trait_IGNORE_SOUND("IGNORE_SOUND") ("IGNORE_SOUND") static
Referenced by npc::move(), and npc::warn_about().
trait_RETURN_TO_START_POS
const trait_id trait_RETURN_TO_START_POS("RETURN_TO_START_POS") ("RETURN_TO_START_POS") static
Referenced by npc::regen_ai_cache().
zone_type_NO_NPC_PICKUP
const zone_type_id zone_type_NO_NPC_PICKUP("NO_NPC_PICKUP") ("NO_NPC_PICKUP") static
Referenced by npc::find_item(), and npc::pick_up_item().
zone_type_NPC_RETREAT
const zone_type_id zone_type_NPC_RETREAT("NPC_RETREAT") ("NPC_RETREAT") static
Referenced by npc::good_escape_direction().