Cataclysm DDA: src/npctrade.cpp File Reference
npctrade.cpp File Reference
#include "npctrade.h"
#include <algorithm>
#include <iosfwd>
#include <iterator>
#include <list>
#include <ostream>
#include <string>
#include <vector>
#include "avatar.h"
#include "character.h"
#include "debug.h"
#include "faction.h"
#include "item.h"
#include "item_category.h"
#include "item_location.h"
#include "item_pocket.h"
#include "npc.h"
#include "npctrade_utils.h"
#include "ret_val.h"
#include "skill.h"
#include "trade_ui.h"
#include "type_id.h"
#include "units.h"
Namespaces
anonymous_namespace{npctrade.cpp}
Functions
int anonymous_namespace{npctrade.cpp}::_trading_price (Character const &buyer, Character const &seller, item_location const &it, int amount)
Variables
static const flag_id json_flag_NO_UNWIELD ("NO_UNWIELD")
static const skill_id skill_speech ("speech")
Variable Documentation
json_flag_NO_UNWIELD
const flag_id json_flag_NO_UNWIELD("NO_UNWIELD") ("NO_UNWIELD") static
Referenced by npc_trading::init_selling().
skill_speech
const skill_id skill_speech("speech") ("speech") static
Referenced by npc_trading::net_price_adjustment(), and npc_trading::trade().