Cataclysm DDA: src/npctalk.cpp File Reference
npctalk.cpp File Reference
#include "dialogue.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <iterator>
#include <list>
#include <map>
#include <memory>
#include <ostream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include "achievement.h"
#include "activity_type.h"
#include "auto_pickup.h"
#include "avatar.h"
#include "bionics.h"
#include "calendar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "character_id.h"
#include "city.h"
#include "clzones.h"
#include "color.h"
#include "computer.h"
#include "condition.h"
#include "coordinates.h"
#include "creature_tracker.h"
#include "debug.h"
#include "dialogue_helpers.h"
#include "effect_on_condition.h"
#include "enums.h"
#include "event_bus.h"
#include "faction.h"
#include "faction_camp.h"
#include "flag.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "generic_factory.h"
#include "help.h"
#include "input_context.h"
#include "item.h"
#include "item_category.h"
#include "itype.h"
#include "line.h"
#include "magic.h"
#include "map.h"
#include "mapbuffer.h"
#include "mapgen_functions.h"
#include "martialarts.h"
#include "messages.h"
#include "mission.h"
#include "mtype.h"
#include "mutation.h"
#include "npc.h"
#include "npctalk.h"
#include "npctrade.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "player_activity.h"
#include "pocket_type.h"
#include "point.h"
#include "popup.h"
#include "recipe.h"
#include "recipe_groups.h"
#include "ret_val.h"
#include "rng.h"
#include "skill.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "talker.h"
#include "talker_topic.h"
#include "teleport.h"
#include "text_snippets.h"
#include "timed_event.h"
#include "translations.h"
#include "translation_gendered.h"
#include "ui.h"
#include "ui_manager.h"
#include "uistate.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vitamin.h"
#include "vpart_position.h"
#include "vpart_range.h"
Classes
struct sub_effect_parser
struct item_search_data
struct eoc_entry
Namespaces
talk_effect_fun
talk_effect_fun::anonymous_namespace{npctalk.cpp}
Macros
#define dbg(x) DebugLog((x),D_GAME) << __FILE__ << ":" << __LINE__ << ": "
#define WRAP(value) { #value, TALK_TRIAL_##value }
#define WRAP(function) { #function, &talk_function::function }
Typedefs
using item_menu = std::function< item_location(const item_location_filter &)>
using item_menu_mul = std::function< drop_locations(const item_location_filter &)>
Enumerations
enum npc_chat_menu {
NPC_CHAT_DONE , NPC_CHAT_TALK , NPC_CHAT_YELL , NPC_CHAT_EMOTE ,
NPC_CHAT_START_SEMINAR , NPC_CHAT_SENTENCE , NPC_CHAT_GUARD , NPC_CHAT_MOVE_TO_POS ,
NPC_CHAT_FOLLOW , NPC_CHAT_AWAKE , NPC_CHAT_MOUNT , NPC_CHAT_DISMOUNT ,
NPC_CHAT_DANGER , NPC_CHAT_ORDERS , NPC_CHAT_NO_GUNS , NPC_CHAT_PULP ,
NPC_CHAT_FOLLOW_CLOSE , NPC_CHAT_MOVE_FREELY , NPC_CHAT_SLEEP , NPC_CHAT_FORBID_ENGAGE ,
NPC_CHAT_CLEAR_OVERRIDES , NPC_CHAT_ANIMAL_VEHICLE_FOLLOW , NPC_CHAT_ANIMAL_VEHICLE_STOP_FOLLOW , NPC_CHAT_COMMAND_MAGIC_VEHICLE_FOLLOW ,
NPC_CHAT_COMMAND_MAGIC_VEHICLE_STOP_FOLLOW , NPC_CHAT_ACTIVITIES , NPC_CHAT_ACTIVITIES_MOVE_LOOT , NPC_CHAT_ACTIVITIES_BUTCHERY ,
NPC_CHAT_ACTIVITIES_CHOP_PLANKS , NPC_CHAT_ACTIVITIES_CHOP_TREES , NPC_CHAT_ACTIVITIES_CONSTRUCTION , NPC_CHAT_ACTIVITIES_CRAFT ,
NPC_CHAT_ACTIVITIES_DISASSEMBLY , NPC_CHAT_ACTIVITIES_FARMING , NPC_CHAT_ACTIVITIES_FISHING , NPC_CHAT_ACTIVITIES_MINING ,
NPC_CHAT_ACTIVITIES_MOPPING , NPC_CHAT_ACTIVITIES_READ_REPEATEDLY , NPC_CHAT_ACTIVITIES_VEHICLE_DECONSTRUCTION , NPC_CHAT_ACTIVITIES_VEHICLE_REPAIR ,
NPC_CHAT_ACTIVITIES_UNASSIGN
}
Functions
static int topic_category (const talk_topic &the_topic)
static const talk_topic & special_talk (const std::string &action)
static bool friendly_teacher (const Character &student, const Character &teacher)
static void run_eoc_vector (const std::vector< effect_on_condition_id > &eocs, const dialogue &d)
static std::vector< effect_on_condition_id > load_eoc_vector (const JsonObject &jo, const std::string_view member)
static std::vector< eoc_entry > load_eoc_vector_id_and_var (const JsonObject &jo, const std::string_view member)
time_duration calc_skill_training_time_char (const Character &teacher, const Character &student, const skill_id &skill)
Time (in turns) and cost (in cent) for training:
int calc_skill_training_cost_char (const Character &teacher, const Character &student, const skill_id &skill)
time_duration calc_proficiency_training_time (const Character &, const Character &student, const proficiency_id &proficiency)
int calc_proficiency_training_cost (const Character &teacher, const Character &student, const proficiency_id &proficiency)
time_duration calc_ma_style_training_time (const Character &, const Character &, const matype_id &)
int calc_ma_style_training_cost (const Character &teacher, const Character &student, const matype_id &)
time_duration calc_spell_training_time (const Character &, const Character &student, const spell_id &id)
static int calc_spell_training_cost_gen (const bool knows, int difficulty, int level)
int calc_spell_training_cost (const Character &teacher, const Character &student, const spell_id &id)
static int npc_select_menu (const std::vector< npc * > &npc_list, const std::string &prompt, const bool everyone=true)
static int creature_select_menu (const std::vector< Creature * > &talker_list, const std::string &prompt, const bool everyone=true)
std::vector< int > npcs_select_menu (const std::vector< Character * > &npc_list, const std::string &prompt, const std::function< bool(const Character *)> &exclude_func)
static std::string training_select_menu (const Character &c, const std::string &prompt)
static void npc_batch_override_toggle (const std::vector< npc * > &npc_list, ally_rule rule, bool state)
static void npc_temp_orders_menu (const std::vector< npc * > &npc_list)
static int npc_activities_menu ()
static void tell_veh_stop_following ()
static void assign_veh_to_follow ()
static void tell_magic_veh_to_follow ()
static void tell_magic_veh_stop_following ()
static int parse_mod (const dialogue &d, const std::string &attribute, const int factor)
static int total_price (const talker &seller, const itype_id &item_type)
void parse_tags (std::string &phrase, const Character &u, const Character &me, const itype_id &item_type)
void parse_tags (std::string &phrase, const Character &u, const Character &me, const dialogue &d, const itype_id &item_type)
void parse_tags (std::string &phrase, const talker &u, const talker &me, const dialogue &d, const itype_id &item_type)
static talk_topic load_inline_topic (const JsonObject &jo)
static Character * get_character_from_id (const std::string &id_str, game *g)
static void run_item_eocs (const dialogue &d, bool is_npc, const std::vector< item_location > &items, std::string_view option, const std::vector< effect_on_condition_id > &true_eocs, const std::vector< effect_on_condition_id > &false_eocs, const std::vector< item_search_data > &data, const item_menu &f, const item_menu_mul &f_mul)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_companion_mission (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_effect (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_effect (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_trait (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate_trait (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_deactivate_trait (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_trait (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_learn_martial_art (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_forget_martial_art (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate_category (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate_towards (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_bionic (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_bionic (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_var (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_var (const JsonObject &jo, std::string_view member, bool is_npc)
void talk_effect_fun::anonymous_namespace{npctalk.cpp}::map_add_item (item &it, tripoint_abs_ms target_pos)
void talk_effect_fun::anonymous_namespace{npctalk.cpp}::receive_item (itype_id &item_name, int count, std::string_view container_name, const dialogue &d, bool use_item_group, bool suppress_message, const std::vector< std::string > &flags, bool add_talker=true, const tripoint_abs_ms &p=tripoint_abs_ms(), bool force_equip=false)
talk_effect_fun_t talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_consume_item (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_item_with (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_spend_cash (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_change_faction (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_change_class (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_change_faction_rep (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_debt (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_toggle_npc_rule (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_npc_rule (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_clear_npc_rule (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_engagement_rule (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_aim_rule (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_cbm_reserve_rule (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_cbm_recharge_rule (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable_adjust (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_line (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_place_override (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_alter_timed_events (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_goal (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_guard_pos (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_gets_item (bool to_use)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_mission (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_monster (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_learn_recipe (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_forget_recipe (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_turn_cost (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_first_topic (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_activity (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_wet (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_take_control (const JsonObject &jo, std::string_view)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_take_control_menu ()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_achievment (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mod_healthy (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_attack (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_die (bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_prevent_death (bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lightning ()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_next_weather ()
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_condition (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_mission (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_finish_mission (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_active_mission (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_offer_mission (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_flag (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_unset_flag (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_math (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_item (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eocs (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_until (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_inv_eocs (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_talker (const JsonObject &jo, std::string_view member, bool is_npc)
void talk_effect_fun::anonymous_namespace{npctalk.cpp}::process_eoc (const effect_on_condition_id &eoc, dialogue &d, time_duration time_in_future)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eocs (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eoc_with (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_weighted_list_eocs (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_if (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_switch (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_morale (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_morale (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_faction_trust (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_faction_trust (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_custom_light_level (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_equipment (const JsonObject &jo, std::string_view member)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport (const JsonObject &jo, std::string_view member, bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_wants_to_talk (bool is_npc)
talk_effect_fun_t::func talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_trigger_event (const JsonObject &jo, std::string_view member)
static std::string translate_gendered_line (const std::string &line, const std::vector< std::string > &relevant_genders, const dialogue &d)
void unload_talk_topics ()
void load_talk_topic (const JsonObject &jo)
const json_talk_topic * get_talk_topic (const std::string &id)
Variables
static const activity_id ACT_AIM ("ACT_AIM")
static const activity_id ACT_SOCIALIZE ("ACT_SOCIALIZE")
static const activity_id ACT_TRAIN ("ACT_TRAIN")
static const activity_id ACT_WAIT_NPC ("ACT_WAIT_NPC")
static const efftype_id effect_asked_to_train ("asked_to_train")
static const efftype_id effect_narcosis ("narcosis")
static const efftype_id effect_riding ("riding")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_under_operation ("under_operation")
static const itype_id fuel_type_animal ("animal")
static const itype_id itype_foodperson_mask ("foodperson_mask")
static const itype_id itype_foodperson_mask_on ("foodperson_mask_on")
static const skill_id skill_firstaid ("firstaid")
static const skill_id skill_speech ("speech")
static const trait_id trait_DEBUG_MIND_CONTROL ("DEBUG_MIND_CONTROL")
static const trait_id trait_HALLUCINATION ("HALLUCINATION")
static const trait_id trait_PROF_CHURL ("PROF_CHURL")
static const trait_id trait_PROF_FOODP ("PROF_FOODP")
static const zone_type_id zone_type_NPC_INVESTIGATE_ONLY ("NPC_INVESTIGATE_ONLY")
static const zone_type_id zone_type_NPC_NO_INVESTIGATE ("NPC_NO_INVESTIGATE")
static std::map< std::string, json_talk_topic > json_talk_topics
static const std::vector< sub_effect_parser > parsers
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x),D_GAME) << __FILE__ << ":" << __LINE__ << ": "
Definition at line 236 of file npctalk.cpp.
WRAP [1/2]
#define WRAP (function) { #function, &talk_function::function }
WRAP [2/2]
#define WRAP (value) { #value, TALK_TRIAL_##value }
Typedef Documentation
item_menu
using item_menu = std::function<item_location(const item_location_filter &)>
Definition at line 124 of file npctalk.cpp.
item_menu_mul
using item_menu_mul = std::function<drop_locations(const item_location_filter &)>
Definition at line 125 of file npctalk.cpp.
Enumeration Type Documentation
npc_chat_menu
enum npc_chat_menu
Enumerator
NPC_CHAT_DONE
NPC_CHAT_TALK
NPC_CHAT_YELL
NPC_CHAT_EMOTE
NPC_CHAT_START_SEMINAR
NPC_CHAT_SENTENCE
NPC_CHAT_GUARD
NPC_CHAT_MOVE_TO_POS
NPC_CHAT_FOLLOW
NPC_CHAT_AWAKE
NPC_CHAT_MOUNT
NPC_CHAT_DISMOUNT
NPC_CHAT_DANGER
NPC_CHAT_ORDERS
NPC_CHAT_NO_GUNS
NPC_CHAT_PULP
NPC_CHAT_FOLLOW_CLOSE
NPC_CHAT_MOVE_FREELY
NPC_CHAT_SLEEP
NPC_CHAT_FORBID_ENGAGE
NPC_CHAT_CLEAR_OVERRIDES
NPC_CHAT_ANIMAL_VEHICLE_FOLLOW
NPC_CHAT_ANIMAL_VEHICLE_STOP_FOLLOW
NPC_CHAT_COMMAND_MAGIC_VEHICLE_FOLLOW
NPC_CHAT_COMMAND_MAGIC_VEHICLE_STOP_FOLLOW
NPC_CHAT_ACTIVITIES
NPC_CHAT_ACTIVITIES_MOVE_LOOT
NPC_CHAT_ACTIVITIES_BUTCHERY
NPC_CHAT_ACTIVITIES_CHOP_PLANKS
NPC_CHAT_ACTIVITIES_CHOP_TREES
NPC_CHAT_ACTIVITIES_CONSTRUCTION
NPC_CHAT_ACTIVITIES_CRAFT
NPC_CHAT_ACTIVITIES_DISASSEMBLY
NPC_CHAT_ACTIVITIES_FARMING
NPC_CHAT_ACTIVITIES_FISHING
NPC_CHAT_ACTIVITIES_MINING
NPC_CHAT_ACTIVITIES_MOPPING
NPC_CHAT_ACTIVITIES_READ_REPEATEDLY
NPC_CHAT_ACTIVITIES_VEHICLE_DECONSTRUCTION
NPC_CHAT_ACTIVITIES_VEHICLE_REPAIR
NPC_CHAT_ACTIVITIES_UNASSIGN
Definition at line 425 of file npctalk.cpp.
                    {
     NPC_CHAT_DONE,
     NPC_CHAT_TALK,
     NPC_CHAT_YELL,
     NPC_CHAT_EMOTE,
     NPC_CHAT_START_SEMINAR,
     NPC_CHAT_SENTENCE,
     NPC_CHAT_GUARD,
     NPC_CHAT_MOVE_TO_POS,
     NPC_CHAT_FOLLOW,
     NPC_CHAT_AWAKE,
     NPC_CHAT_MOUNT,
     NPC_CHAT_DISMOUNT,
     NPC_CHAT_DANGER,
     NPC_CHAT_ORDERS,
     NPC_CHAT_NO_GUNS,
     NPC_CHAT_PULP,
     NPC_CHAT_FOLLOW_CLOSE,
     NPC_CHAT_MOVE_FREELY,
     NPC_CHAT_SLEEP,
     NPC_CHAT_FORBID_ENGAGE,
     NPC_CHAT_CLEAR_OVERRIDES,
     NPC_CHAT_ANIMAL_VEHICLE_FOLLOW,
     NPC_CHAT_ANIMAL_VEHICLE_STOP_FOLLOW,
     NPC_CHAT_COMMAND_MAGIC_VEHICLE_FOLLOW,
     NPC_CHAT_COMMAND_MAGIC_VEHICLE_STOP_FOLLOW,
     NPC_CHAT_ACTIVITIES,
     NPC_CHAT_ACTIVITIES_MOVE_LOOT,
     NPC_CHAT_ACTIVITIES_BUTCHERY,
     NPC_CHAT_ACTIVITIES_CHOP_PLANKS,
     NPC_CHAT_ACTIVITIES_CHOP_TREES,
     NPC_CHAT_ACTIVITIES_CONSTRUCTION,
     NPC_CHAT_ACTIVITIES_CRAFT,
     NPC_CHAT_ACTIVITIES_DISASSEMBLY,
     NPC_CHAT_ACTIVITIES_FARMING,
     NPC_CHAT_ACTIVITIES_FISHING,
     NPC_CHAT_ACTIVITIES_MINING,
     NPC_CHAT_ACTIVITIES_MOPPING,
     NPC_CHAT_ACTIVITIES_READ_REPEATEDLY,
     NPC_CHAT_ACTIVITIES_VEHICLE_DECONSTRUCTION,
     NPC_CHAT_ACTIVITIES_VEHICLE_REPAIR,
     NPC_CHAT_ACTIVITIES_UNASSIGN
 };
Function Documentation
assign_veh_to_follow()
static void assign_veh_to_follow () static
Definition at line 752 of file npctalk.cpp.
 {
     Character &player_character = get_player_character();
     for( wrapped_vehicle &veh : get_map().get_vehicles() ) {
         vehicle *v = veh.v;
         if( v->has_engine_type( fuel_type_animal, false ) && v->is_owned_by( player_character ) ) {
             v->activate_animal_follow();
         }
     }
 }
References vehicle::activate_animal_follow(), fuel_type_animal, get_map(), get_player_character(), vehicle::has_engine_type(), and vehicle::is_owned_by().
Referenced by game::chat().
calc_ma_style_training_cost()
int calc_ma_style_training_cost (const Character & teacher, const Character & student, const matype_id & id)
Definition at line 359 of file npctalk.cpp.
 {
     if( friendly_teacher( student, teacher ) ) {
         return 0;
     }
     return 800;
 }
References friendly_teacher().
Referenced by talk_function::start_training_gen().
calc_ma_style_training_time()
time_duration calc_ma_style_training_time (const Character & teacher, const Character & student, const matype_id & id)
Definition at line 353 of file npctalk.cpp.
 {
     return 30_minutes;
 }
Referenced by talk_function::start_training_gen().
calc_proficiency_training_cost()
int calc_proficiency_training_cost (const Character & teacher, const Character & student, const proficiency_id & proficiency)
Definition at line 341 of file npctalk.cpp.
 {
     if( friendly_teacher( student, teacher ) ) {
         return 0;
     }
     return to_seconds<int>( calc_proficiency_training_time( teacher, student, proficiency ) );
 }
References calc_proficiency_training_time(), and friendly_teacher().
Referenced by talker_character_const::proficiency_training_text(), and talk_function::start_training_gen().
calc_proficiency_training_time()
time_duration calc_proficiency_training_time (const Character & teacher, const Character & student, const proficiency_id & proficiency)
Definition at line 335 of file npctalk.cpp.
 {
     return std::min( 30_minutes, student.proficiency_training_needed( proficiency ) );
 }
References min(), and Character::proficiency_training_needed().
Referenced by calc_proficiency_training_cost(), and talk_function::start_training_gen().
calc_skill_training_cost_char()
int calc_skill_training_cost_char (const Character & teacher, const Character & student, const skill_id & skill)
Definition at line 325 of file npctalk.cpp.
 {
     if( friendly_teacher( student, teacher ) ) {
         return 0;
     }
     int skill_level = student.get_knowledge_level( skill );
     return 1000 * ( 1 + skill_level ) * ( 1 + skill_level );
 }
References friendly_teacher(), and Character::get_knowledge_level().
Referenced by talker_character_const::skill_training_text(), and talk_function::start_training_gen().
calc_skill_training_time_char()
time_duration calc_skill_training_time_char (const Character & teacher, const Character & student, const skill_id & skill)
Time (in turns) and cost (in cent) for training:
Definition at line 318 of file npctalk.cpp.
 {
     return 1_hours + 30_minutes * student.get_skill_level( skill ) -
            1_minutes * teacher.get_skill_level( skill );
 }
References Character::get_skill_level().
Referenced by talk_function::start_training_gen().
calc_spell_training_cost()
int calc_spell_training_cost (const Character & teacher, const Character & student, const spell_id & id)
Definition at line 394 of file npctalk.cpp.
 {
     if( friendly_teacher( student, teacher ) ) {
         return 0;
     }
     const spell &temp_spell = teacher.magic->get_spell( id );
     const bool knows = student.magic->knows_spell( id );
     return calc_spell_training_cost_gen( knows, temp_spell.get_difficulty( student ),
                                          temp_spell.get_level() );
 }
References calc_spell_training_cost_gen(), friendly_teacher(), spell::get_difficulty(), spell::get_level(), and Character::magic.
Referenced by talk_function::start_training_gen().
calc_spell_training_cost_gen()
static int calc_spell_training_cost_gen (const bool knows, int difficulty, int level) static
Definition at line 385 of file npctalk.cpp.
 {
     int ret = ( 100 * std::max( 1, difficulty ) * std::max( 1, level ) );
     if( !knows ) {
         ret = ret * 2;
     }
     return ret;
 }
References max(), and cata::hash64_detail::ret.
Referenced by Character::calc_spell_training_cost(), and calc_spell_training_cost().
calc_spell_training_time()
time_duration calc_spell_training_time (const Character & teacher, const Character & student, const spell_id & id)
Definition at line 374 of file npctalk.cpp.
 {
     if( student.magic->knows_spell( id ) ) {
         return 1_hours;
     } else {
         const int time_int = student.magic->time_to_learn_spell( student, id ) / 50;
         return time_duration::from_seconds( clamp( time_int, 7200, 21600 ) );
     }
 }
References clamp(), time_duration::from_seconds(), and Character::magic.
Referenced by talk_function::start_training_gen().
creature_select_menu()
static int creature_select_menu (const std::vector< Creature * > & talker_list, const std::string & prompt, const bool everyone = true) static
Definition at line 502 of file npctalk.cpp.
 {
     if( talker_list.empty() ) {
         return -1;
     }
     const int npc_count = talker_list.size();
     if( npc_count == 1 ) {
         return 0;
     } else {
         uilist nmenu;
         std::vector<tripoint> locations;
         nmenu.text = prompt;
         for( const Creature *elem : talker_list ) {
             if( elem->is_npc() ) {
                 nmenu.addentry( -1, true, MENU_AUTOASSIGN, elem->as_npc()->name_and_activity() );
             } else {
                 nmenu.addentry( -1, true, MENU_AUTOASSIGN, elem->disp_name() );
             }
             locations.emplace_back( elem->pos_bub().raw() );
         }
         if( npc_count > 1 && everyone ) {
             nmenu.addentry( -1, true, MENU_AUTOASSIGN, _( "Everyone" ) );
             locations.emplace_back( get_avatar().pos_bub().raw() );
         }
         pointmenu_cb callback( locations );
         nmenu.callback = &callback;
         nmenu.w_y_setup = 0;
         nmenu.query();
         return nmenu.ret;
     }
 }
References _, uilist::addentry(), uilist::callback, get_avatar(), anonymous_namespace{overmap_location.cpp}::locations, MENU_AUTOASSIGN, Pickup::prompt, uilist::query(), uilist::ret, uilist::text, and uilist::w_y_setup.
Referenced by game::chat().
friendly_teacher()
static bool friendly_teacher (const Character & student, const Character & teacher) static
Definition at line 242 of file npctalk.cpp.
 {
     return ( student.is_npc() && teacher.is_avatar() ) ||
            ( teacher.is_npc() && teacher.as_npc()->is_player_ally() );
 }
References Creature::as_npc(), Creature::is_avatar(), Character::is_npc(), and npc::is_player_ally().
Referenced by calc_ma_style_training_cost(), calc_proficiency_training_cost(), calc_skill_training_cost_char(), and calc_spell_training_cost().
get_character_from_id()
static Character* get_character_from_id (const std::string & id_str, game * g) static
Definition at line 2777 of file npctalk.cpp.
 {
     // Return the character with character_id, return nullptr if counldn't find the character with character_id
     Character *temp_guy = nullptr;
     character_id char_id;
     try {
         char_id = character_id( std::stoi( id_str ) );
     } catch( const std::exception & ) {
         return nullptr;
     }
     // Check Avatar
     if( char_id == get_avatar().getID() ) {
         return &get_avatar();
     }
     // Check visible NPC
     for( npc *guy : g->get_npcs_if( [char_id]( const npc & guy ) {
     return guy.getID() == char_id;
     } ) ) {
         temp_guy = guy;
     }
     // Check NPC in the OverMapBuffer
     if( temp_guy == nullptr ) {
         temp_guy = g->find_npc( char_id );
     }
     return temp_guy;
 }
References g, and get_avatar().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with().
get_talk_topic()
const json_talk_topic* get_talk_topic (const std::string & id)
Definition at line 7254 of file npctalk.cpp.
 {
     auto it = json_talk_topics.find( id );
     if( it == json_talk_topics.end() ) {
         return nullptr;
     }
     return &it->second;
 }
References json_talk_topics.
Referenced by npc_template::check_consistency().
load_eoc_vector()
static std::vector<effect_on_condition_id> load_eoc_vector (const JsonObject & jo, const std::string_view member) static
Definition at line 269 of file npctalk.cpp.
 {
     std::vector<effect_on_condition_id> eocs;
     if( jo.has_array( member ) ) {
         for( JsonValue jv : jo.get_array( member ) ) {
             eocs.push_back( effect_on_conditions::load_inline_eoc( jv, "" ) );
         }
     } else if( jo.has_member( member ) ) {
         eocs.push_back( effect_on_conditions::load_inline_eoc( jo.get_member( member ), "" ) );
     }
     return eocs;
 }
References JsonObject::get_array(), JsonObject::get_member(), JsonObject::has_array(), JsonObject::has_member(), effect_on_conditions::load_inline_eoc(), and member.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_goal(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_inv_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_take_control(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_spend_cash().
load_eoc_vector_id_and_var()
static std::vector<eoc_entry> load_eoc_vector_id_and_var (const JsonObject & jo, const std::string_view member) static
Definition at line 288 of file npctalk.cpp.
 {
     std::vector<eoc_entry> eocs_entries;
     auto process_jv = [member, &eocs_entries]( const JsonValue & jv ) {
         eoc_entry entry;
         if( jv.test_object() ) {
             JsonObject jo = jv.get_object();
             jo.allow_omitted_members();
             if( !jo.has_member( "id" ) ) {
                 entry.var = get_str_or_var( jv, member, false );
             }
         }
         if( !entry.var ) {
             entry.id = effect_on_conditions::load_inline_eoc( jv, "" );
         }
         eocs_entries.push_back( entry );
     };
     if( jo.has_array( member ) ) {
         for( JsonValue jv : jo.get_array( member ) ) {
             process_jv( jv );
         }
     } else if( jo.has_member( member ) ) {
         process_jv( jo.get_member( member ) );
     }
     return eocs_entries;
 }
References JsonObject::allow_omitted_members(), JsonObject::get_array(), JsonObject::get_member(), JsonObject::get_object(), get_str_or_var(), JsonObject::has_array(), JsonObject::has_member(), eoc_entry::id, effect_on_conditions::load_inline_eoc(), member, and eoc_entry::var.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eocs().
load_inline_topic()
static talk_topic load_inline_topic (const JsonObject & jo) static
Definition at line 2742 of file npctalk.cpp.
 {
     const std::string id = jo.get_string( "id" );
     json_talk_topics[id].load( jo );
     return talk_topic( id );
 }
References JsonObject::get_string(), int_id< T >::id(), and json_talk_topics.
Referenced by talk_effect_t::talk_effect_t(), and talk_response::talk_response().
load_talk_topic()
void load_talk_topic (const JsonObject & jo)
Definition at line 7147 of file npctalk.cpp.
 {
     if( jo.has_array( "id" ) ) {
         for( auto &id : jo.get_string_array( "id" ) ) {
             json_talk_topics[id].load( jo );
         }
     } else {
         const std::string id = jo.get_string( "id" );
         json_talk_topics[id].load( jo );
     }
 }
References JsonObject::get_string(), JsonObject::get_string_array(), JsonObject::has_array(), int_id< T >::id(), and json_talk_topics.
Referenced by DynamicDataLoader::initialize().
npc_activities_menu()
static int npc_activities_menu () static
Definition at line 711 of file npctalk.cpp.
 {
     uilist nmenu;
     nmenu.text = _( "What should be worked on?" );
     nmenu.addentry( NPC_CHAT_ACTIVITIES_MOVE_LOOT, true, 'l', _( "Organizing loot into zones" ) );
     nmenu.addentry( NPC_CHAT_ACTIVITIES_BUTCHERY, true, 'b', _( "Butchering corpses" ) );
     nmenu.addentry( NPC_CHAT_ACTIVITIES_CHOP_TREES, true, 't', _( "Chopping down trees" ) );
     nmenu.addentry( NPC_CHAT_ACTIVITIES_CHOP_PLANKS, true, 'p', _( "Chopping logs into planks" ) );
     nmenu.addentry( NPC_CHAT_ACTIVITIES_CONSTRUCTION, true, 'c', _( "Constructing blueprints" ) );
     nmenu.addentry( NPC_CHAT_ACTIVITIES_CRAFT, true, 'C', _( "Crafting item" ) );
     nmenu.addentry( NPC_CHAT_ACTIVITIES_DISASSEMBLY, true, 'd', _( "Disassembly of items" ) );
     nmenu.addentry( NPC_CHAT_ACTIVITIES_FARMING, true, 'f', _( "Farming plots" ) );
     nmenu.addentry( NPC_CHAT_ACTIVITIES_FISHING, true, 'F', _( "Fishing in a zone" ) );
     nmenu.addentry( NPC_CHAT_ACTIVITIES_MINING, true, 'M', _( "Mining out tiles" ) );
     nmenu.addentry( NPC_CHAT_ACTIVITIES_MOPPING, true, 'm', _( "Mopping up stains" ) );
     nmenu.addentry( NPC_CHAT_ACTIVITIES_READ_REPEATEDLY, true, 'R',
                     _( "Study from books you have in order" ) );
     nmenu.addentry( NPC_CHAT_ACTIVITIES_VEHICLE_DECONSTRUCTION, true, 'v',
                     _( "Deconstructing vehicles" ) );
     nmenu.addentry( NPC_CHAT_ACTIVITIES_VEHICLE_REPAIR, true, 'V', _( "Repairing vehicles" ) );
     nmenu.addentry( NPC_CHAT_ACTIVITIES_UNASSIGN, true, '-',
                     _( "Taking it easy (Stop what they are working on)" ) );
     nmenu.query();
     return nmenu.ret;
 }
References _, uilist::addentry(), NPC_CHAT_ACTIVITIES_BUTCHERY, NPC_CHAT_ACTIVITIES_CHOP_PLANKS, NPC_CHAT_ACTIVITIES_CHOP_TREES, NPC_CHAT_ACTIVITIES_CONSTRUCTION, NPC_CHAT_ACTIVITIES_CRAFT, NPC_CHAT_ACTIVITIES_DISASSEMBLY, NPC_CHAT_ACTIVITIES_FARMING, NPC_CHAT_ACTIVITIES_FISHING, NPC_CHAT_ACTIVITIES_MINING, NPC_CHAT_ACTIVITIES_MOPPING, NPC_CHAT_ACTIVITIES_MOVE_LOOT, NPC_CHAT_ACTIVITIES_READ_REPEATEDLY, NPC_CHAT_ACTIVITIES_UNASSIGN, NPC_CHAT_ACTIVITIES_VEHICLE_DECONSTRUCTION, NPC_CHAT_ACTIVITIES_VEHICLE_REPAIR, uilist::query(), uilist::ret, and uilist::text.
Referenced by game::chat().
npc_batch_override_toggle()
static void npc_batch_override_toggle (const std::vector< npc * > & npc_list, ally_rule rule, bool state) static
Definition at line 615 of file npctalk.cpp.
 {
     for( npc *p : npc_list ) {
         p->rules.toggle_specific_override_state( rule, state );
     }
 }
Referenced by npc_temp_orders_menu().
npc_select_menu()
static int npc_select_menu (const std::vector< npc * > & npc_list, const std::string & prompt, const bool everyone = true) static
Definition at line 472 of file npctalk.cpp.
 {
     if( npc_list.empty() ) {
         return -1;
     }
     const int npc_count = npc_list.size();
     if( npc_count == 1 ) {
         return 0;
     } else {
         uilist nmenu;
         std::vector<tripoint> locations;
         nmenu.text = prompt;
         for( const npc *elem : npc_list ) {
             nmenu.addentry( -1, true, MENU_AUTOASSIGN, elem->name_and_activity() );
             locations.emplace_back( elem->pos_bub().raw() );
         }
         if( npc_count > 1 && everyone ) {
             nmenu.addentry( -1, true, MENU_AUTOASSIGN, _( "Everyone" ) );
             locations.emplace_back( get_avatar().pos_bub().raw() );
         }
         pointmenu_cb callback( locations );
         nmenu.callback = &callback;
         nmenu.w_y_setup = 0;
         nmenu.query();
         return nmenu.ret;
     }
 }
References _, uilist::addentry(), uilist::callback, get_avatar(), anonymous_namespace{overmap_location.cpp}::locations, MENU_AUTOASSIGN, Pickup::prompt, uilist::query(), uilist::ret, uilist::text, and uilist::w_y_setup.
Referenced by game::chat().
npc_temp_orders_menu()
static void npc_temp_orders_menu (const std::vector< npc * > & npc_list) static
Definition at line 623 of file npctalk.cpp.
 {
     if( npc_list.empty() ) {
         return;
     }
     npc *guy = npc_list.front();
     Character &player_character = get_player_character();
     bool done = false;
     uilist nmenu;
     while( !done ) {
         int override_count = 0;
         std::string output_string = string_format( _( "%s currently has these temporary orders:" ),
                                     guy->get_name() );
         for( const auto &rule : ally_rule_strs ) {
             if( guy->rules.has_override_enable( rule.second.rule ) ) {
                 override_count++;
                 output_string += "\n  ";
                 output_string += ( guy->rules.has_override( rule.second.rule ) ? rule.second.rule_true_text :
                                    rule.second.rule_false_text );
             }
         }
         if( override_count == 0 ) {
             output_string += std::string( "\n  " ) + _( "None." ) + "\n";
         }
         if( npc_list.size() > 1 ) {
             output_string += std::string( "\n" ) +
                              _( "Other followers might have different temporary orders." );
         }
         nmenu.reset();
         nmenu.text = _( "Issue what temporary order?" );
         nmenu.desc_enabled = true;
         parse_tags( output_string, player_character, *guy );
         nmenu.footer_text = output_string;
         nmenu.addentry( NPC_CHAT_DONE, true, 'd', _( "Done issuing orders" ) );
         nmenu.addentry( NPC_CHAT_FORBID_ENGAGE, true, 'f',
                         guy->rules.has_override_enable( ally_rule::forbid_engage ) ?
                         _( "Go back to your usual engagement habits" ) : _( "Don't engage hostiles for the time being" ) );
         nmenu.addentry( NPC_CHAT_NO_GUNS, true, 'g', guy->rules.has_override_enable( ally_rule::use_guns ) ?
                         _( "Use whatever weapon you normally would" ) : _( "Don't use ranged weapons for a while" ) );
         nmenu.addentry( NPC_CHAT_PULP, true, 'p', guy->rules.has_override_enable( ally_rule::allow_pulp ) ?
                         _( "Pulp zombies if you like" ) : _( "Hold off on pulping zombies for a while" ) );
         nmenu.addentry( NPC_CHAT_FOLLOW_CLOSE, true, 'c',
                         guy->rules.has_override_enable( ally_rule::follow_close ) &&
                         guy->rules.has_override( ally_rule::follow_close ) ?
                         _( "Go back to keeping your usual distance" ) : _( "Stick close to me for now" ) );
         nmenu.addentry( NPC_CHAT_MOVE_FREELY, true, 'm',
                         guy->rules.has_override_enable( ally_rule::follow_close ) &&
                         !guy->rules.has_override( ally_rule::follow_close ) ?
                         _( "Go back to keeping your usual distance" ) : _( "Move farther from me if you need to" ) );
         nmenu.addentry( NPC_CHAT_SLEEP, true, 's',
                         guy->rules.has_override_enable( ally_rule::allow_sleep ) ?
                         _( "Go back to your usual sleeping habits" ) : _( "Take a nap if you need it" ) );
         nmenu.addentry( NPC_CHAT_CLEAR_OVERRIDES, true, 'o', _( "Let's go back to your usual behaviors" ) );
         nmenu.query();
         switch( nmenu.ret ) {
             case NPC_CHAT_FORBID_ENGAGE:
                 npc_batch_override_toggle( npc_list, ally_rule::forbid_engage, true );
                 break;
             case NPC_CHAT_NO_GUNS:
                 npc_batch_override_toggle( npc_list, ally_rule::use_guns, false );
                 break;
             case NPC_CHAT_PULP:
                 npc_batch_override_toggle( npc_list, ally_rule::allow_pulp, false );
                 break;
             case NPC_CHAT_FOLLOW_CLOSE:
                 npc_batch_override_toggle( npc_list, ally_rule::follow_close, true );
                 break;
             case NPC_CHAT_MOVE_FREELY:
                 npc_batch_override_toggle( npc_list, ally_rule::follow_close, false );
                 break;
             case NPC_CHAT_SLEEP:
                 npc_batch_override_toggle( npc_list, ally_rule::allow_sleep, true );
                 break;
             case NPC_CHAT_CLEAR_OVERRIDES:
                 for( npc *p : npc_list ) {
                     p->rules.clear_overrides();
                 }
                 break;
             default:
                 done = true;
                 break;
         }
     }
 }
References _, uilist::addentry(), allow_pulp, allow_sleep, ally_rule_strs, uilist::desc_enabled, follow_close, uilist::footer_text, forbid_engage, Character::get_name(), get_player_character(), npc_follower_rules::has_override(), npc_follower_rules::has_override_enable(), npc_batch_override_toggle(), NPC_CHAT_CLEAR_OVERRIDES, NPC_CHAT_DONE, NPC_CHAT_FOLLOW_CLOSE, NPC_CHAT_FORBID_ENGAGE, NPC_CHAT_MOVE_FREELY, NPC_CHAT_NO_GUNS, NPC_CHAT_PULP, NPC_CHAT_SLEEP, parse_tags(), uilist::query(), uilist::reset(), uilist::ret, npc::rules, string_format(), uilist::text, and use_guns.
Referenced by game::chat().
npcs_select_menu()
std::vector<int> npcs_select_menu (const std::vector< Character * > & npc_list, const std::string & prompt, const std::function< bool(const Character *)> & exclude_func)
Definition at line 536 of file npctalk.cpp.
 {
     std::vector<int> picked;
     if( npc_list.empty() ) {
         return picked;
     }
     const int npc_count = npc_list.size();
     int last_index = 0;
     do {
         uilist nmenu;
         nmenu.text = prompt;
         for( int i = 0; i < npc_count; i++ ) {
             std::string entry;
             if( std::find( picked.begin(), picked.end(), i ) != picked.end() ) {
                 entry = "* ";
             }
             bool enable = exclude_func == nullptr || !exclude_func( npc_list[i] );
             entry += npc_list[i]->name_and_maybe_activity();
             nmenu.addentry( i, enable, MENU_AUTOASSIGN, entry );
         }
         nmenu.addentry( npc_count, true, MENU_AUTOASSIGN, _( "Finish selection" ) );
         nmenu.selected = nmenu.fselected = last_index;
         nmenu.query();
         if( nmenu.ret < 0 ) {
             return std::vector<int>();
         } else if( nmenu.ret >= npc_count ) {
             break;
         }
         std::vector<int>::iterator exists = std::find( picked.begin(), picked.end(), nmenu.ret );
         if( exists != picked.end() ) {
             picked.erase( exists );
         } else {
             picked.push_back( nmenu.ret );
         }
         last_index = nmenu.fselected;
     } while( true );
     return picked;
 }
References _, uilist::addentry(), uilist::fselected, MENU_AUTOASSIGN, Pickup::prompt, uilist::query(), uilist::ret, uilist::selected, and uilist::text.
Referenced by game::chat(), and talk_function::start_training_seminar().
parse_mod()
static int parse_mod (const dialogue & d, const std::string & attribute, const int factor) static
Definition at line 1889 of file npctalk.cpp.
 {
     return d.actor( true )->parse_mod( attribute, factor ) + d.actor( false )->parse_mod( attribute,
             factor );
 }
References dialogue::actor(), and talker::parse_mod().
Referenced by talk_trial::calc_chance(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_debt(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_equipment().
parse_tags() [1/3]
void parse_tags (std::string & phrase, const Character & u, const Character & me, const dialogue & d, const itype_id & item_type)
Definition at line 2063 of file npctalk.cpp.
 {
     parse_tags( phrase, *get_talker_for( u ), *get_talker_for( me ), d, item_type );
 }
References get_talker_for(), parse_tags(), and u.
parse_tags() [2/3]
void parse_tags (std::string & phrase, const Character & u, const Character & me, const itype_id & item_type)
Definition at line 2056 of file npctalk.cpp.
 {
     dialogue d( get_talker_for( u ), get_talker_for( me ) );
     parse_tags( phrase, u, me, d, item_type );
 }
References get_talker_for(), parse_tags(), and u.
Referenced by npc::complain(), talk_response::create_option_line(), mission_ui_impl::draw_selected_description(), npc::execute_action(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), npc::find_corpse_to_pulp(), talker_npc::give_item_to(), npc_temp_orders_menu(), dialogue::opt(), parse_tags(), npc::say(), widget::sym_text_cond(), widget::text_cond(), and try_consume().
parse_tags() [3/3]
void parse_tags (std::string & phrase, const talker & u, const talker & me, const dialogue & d, const itype_id & item_type)
Definition at line 2069 of file npctalk.cpp.
 {
     phrase = SNIPPET.expand( phrase );
     const Character *u_chr = u.get_character();
     const Character *me_chr = me.get_character();
     size_t fa;
     size_t fb;
     size_t fa_;
     std::string tag;
     do {
         fa = phrase.find( '<' );
         fb = phrase.find( '>' );
         // Skip the <color_XXX> and </color> tag
         while( fa != std::string::npos && ( phrase.compare( fa + 1, 6, "color_" ) == 0 ||
                                             phrase.compare( fa + 1, 7, "/color>" ) == 0 ) ) {
             if( phrase.compare( fa + 1, 6, "color_" ) == 0 ) {
                 fa = phrase.find( '<', fa + 7 );
             } else { // phrase.compare(fa + 1, 7, "/color>") == 0
                 fa = phrase.find( '<', fa + 8 );
             }
             fb = phrase.find( '>', fa );
         }
         if( fa != std::string::npos ) {
             size_t nest = 0;
             fa_ = phrase.find( '<', fa + 1 );
             while( fa_ < fb && fa_ != std::string::npos ) {
                 nest++;
                 fa_ = phrase.find( '<', fa_ + 1 );
             }
             while( nest > 0 && fb != std::string::npos ) {
                 nest--;
                 fb = phrase.find( '>', fb + 1 );
             }
         }
         int l = fb - fa + 1;
         if( fa != std::string::npos && fb != std::string::npos ) {
             tag = phrase.substr( fa, fb - fa + 1 );
         } else {
             return;
         }
         const item_location u_weapon = u_chr ? u_chr->get_wielded_item() : item_location();
         const item_location me_weapon = me_chr ? me_chr->get_wielded_item() : item_location();
         // Special, dynamic tags go here
         if( tag == "<yrwp>" ) {
             phrase.replace( fa, l, remove_color_tags( u_weapon->tname() ) );
         } else if( tag == "<mywp>" ) {
             if( me_chr && !me_chr->is_armed() ) {
                 phrase.replace( fa, l, _( "fists" ) );
             } else {
                 phrase.replace( fa, l, remove_color_tags( me_weapon->tname() ) );
             }
         } else if( tag == "<u_name>" ) {
             phrase.replace( fa, l, u.get_name() );
         } else if( tag == "<npc_name>" ) {
             phrase.replace( fa, l, me.get_name() );
         } else if( tag == "<ammo>" ) {
             if( !me_weapon || !me_weapon->is_gun() ) {
                 phrase.replace( fa, l, _( "BADAMMO" ) );
             } else {
                 phrase.replace( fa, l, me_weapon->ammo_current()->nname( 1 ) );
             }
         } else if( tag == "<current_activity>" ) {
             std::string activity_name;
             const npc *guy = dynamic_cast<const npc *>( me_chr );
             if( guy && guy->current_activity_id ) {
                 activity_name = guy->get_current_activity();
             } else {
                 activity_name = _( "doing this and that" );
             }
             phrase.replace( fa, l, activity_name );
         } else if( tag == "<punc>" ) {
             switch( rng( 0, 2 ) ) {
                 case 0:
                     phrase.replace( fa, l, pgettext( "punctuation", "." ) );
                     break;
                 case 1:
                     phrase.replace( fa, l, pgettext( "punctuation", "" ) );
                     break;
                 case 2:
                     phrase.replace( fa, l, pgettext( "punctuation", "!" ) );
                     break;
             }
         } else if( tag == "<mypronoun>" ) {
             std::string npcstr = me.is_male() ? pgettext( "npc", "He" ) : pgettext( "npc", "She" );
             phrase.replace( fa, l, npcstr );
         } else if( tag == "<mypossesivepronoun>" ) {
             std::string npcstr = me.is_male() ? pgettext( "npc", "his" ) : pgettext( "npc", "her" );
             phrase.replace( fa, l, npcstr );
         } else if( tag == "<topic_item>" ) {
             phrase.replace( fa, l, item::nname( item_type, 2 ) );
         } else if( tag == "<topic_item_price>" ) {
             item tmp( item_type );
             phrase.replace( fa, l, format_money( tmp.price( true ) ) );
         } else if( tag == "<topic_item_my_total_price>" ) {
             int price = total_price( me, item_type );
             phrase.replace( fa, l, format_money( price ) );
         } else if( tag == "<topic_item_your_total_price>" ) {
             int price = total_price( u, item_type );
             phrase.replace( fa, l, format_money( price ) );
         } else if( tag == "<interval>" ) {
             const npc *guy = dynamic_cast<const npc *>( me_chr );
             std::string restock_interval = guy ? guy->get_restock_interval() : _( "a few days" );
             phrase.replace( fa, l, restock_interval );
         } else if( tag.find( "<u_val:" ) == 0 ) {
             //adding a user variable to the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             phrase.replace( fa, l, u.get_value( "npctalk_var_" + var ) );
         } else if( tag.find( "<npc_val:" ) == 0 ) {
             //adding a npc variable to the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             phrase.replace( fa, l, me.get_value( "npctalk_var_" + var ) );
         } else if( tag.find( "<global_val:" ) == 0 ) {
             //adding a global variable to the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             global_variables &globvars = get_globals();
             phrase.replace( fa, l, globvars.get_global_value( "npctalk_var_" + var ) );
         } else if( tag.find( "<context_val:" ) == 0 ) {
             //adding a context variable to the string requires dialogue to exist
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             phrase.replace( fa, l, d.get_value( "npctalk_var_" + var ) );
         } else if( tag.find( "<item_name:" ) == 0 ) {
             //embedding an items name in the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             // attempt to cast as an item
             phrase.replace( fa, l, itype_id( var )->nname( 1 ) );
         } else if( tag.find( "<item_description:" ) == 0 ) {
             //embedding an items name in the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             // attempt to cast as an item
             phrase.replace( fa, l, itype_id( var )->description.translated() );
         } else if( tag.find( "<trait_name:" ) == 0 ) {
             //embedding an items name in the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             // attempt to cast as an item
             phrase.replace( fa, l, trait_id( var )->name() );
         } else if( tag.find( "<trait_description:" ) == 0 ) {
             //embedding an items name in the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             // attempt to cast as an item
             phrase.replace( fa, l, trait_id( var )->desc() );
         } else if( tag.find( "<spell_name:" ) == 0 ) {
             //embedding an items name in the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             // attempt to cast as an item
             phrase.replace( fa, l, spell_id( var )->name.translated() );
         } else if( tag.find( "<spell_description:" ) == 0 ) {
             //embedding an items name in the string
             std::string var = tag.substr( tag.find( ':' ) + 1 );
             // remove the trailing >
             var.pop_back();
             // resolve nest
             parse_tags( var, u, me, d, item_type );
             // attempt to cast as an item
             phrase.replace( fa, l, spell_id( var )->description.translated() );
         } else if( tag.find( "<city>" ) == 0 ) {
             std::string cityname = "nowhere";
             tripoint_abs_sm abs_sub = get_map().get_abs_sub();
             const city *c = overmap_buffer.closest_city( abs_sub ).city;
             if( c != nullptr ) {
                 cityname = c->name;
             }
             phrase.replace( fa, l, cityname );
         } else if( !tag.empty() ) {
             debugmsg( "Bad tag.  '%s' (%d - %d)", tag.c_str(), fa, fb );
             phrase.replace( fa, fb - fa + 1, "????" );
         }
     } while( fa != std::string::npos && fb != std::string::npos );
 }
References _, item::ammo_current(), c, city_reference::city, overmapbuffer::closest_city(), npc::current_activity_id, debugmsg, snippet_library::expand(), format_money(), map::get_abs_sub(), talker::get_character(), npc::get_current_activity(), global_variables::get_global_value(), get_globals(), get_map(), talker::get_name(), npc::get_restock_interval(), dialogue::get_value(), talker::get_value(), Character::get_wielded_item(), Character::is_armed(), item::is_gun(), talker::is_male(), om_direction::name(), nest, item::nname(), itype::nname(), overmap_buffer, parse_tags(), pgettext, item::price(), remove_color_tags(), rng(), SNIPPET, item::tname(), total_price(), and u.
run_eoc_vector()
static void run_eoc_vector (const std::vector< effect_on_condition_id > & eocs, const dialogue & d) static
Definition at line 261 of file npctalk.cpp.
 {
     dialogue newDialog( d );
     for( const effect_on_condition_id &eoc : eocs ) {
         eoc->activate( newDialog );
     }
 }
References eoc.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_goal(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_take_control(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_spend_cash(), and run_item_eocs().
run_item_eocs()
static void run_item_eocs (const dialogue & d, bool is_npc, const std::vector< item_location > & items, std::string_view option, const std::vector< effect_on_condition_id > & true_eocs, const std::vector< effect_on_condition_id > & false_eocs, const std::vector< item_search_data > & data, const item_menu & f, const item_menu_mul & f_mul) static
Definition at line 2808 of file npctalk.cpp.
 {
     Character *guy = d.actor( is_npc )->get_character();
     guy = guy ? guy : &get_player_character();
     std::vector<item_location> true_items;
     for( const item_location &loc : items ) {
         // Check if item matches any search_data.
         bool true_tgt = data.empty();
         for( item_search_data datum : data ) {
             if( datum.check( guy, loc ) ) {
                 true_tgt = true;
                 break;
             }
         }
         if( true_tgt ) {
             true_items.push_back( loc );
         }
     }
     const auto run_eoc = [&d, is_npc]( item_location & loc,
     const std::vector<effect_on_condition_id> &eocs ) {
         for( const effect_on_condition_id &eoc : eocs ) {
             // Check if item is outdated.
             if( loc.get_item() ) {
                 dialogue newDialog = dialogue( d.actor( is_npc )->clone(), get_talker_for( loc ),
                                                d.get_conditionals(), d.get_context() );
                 eoc->activate( newDialog );
             }
         }
     };
     auto filter = [true_items]( const item_location & it ) {
         for( const item_location &true_it : true_items ) {
             if( true_it == it ) {
                 return true;
             }
         }
         return false;
     };
     if( option == "all" ) {
         for( item_location target : true_items ) {
             run_eoc( target, true_eocs );
         }
         if( true_items.empty() ) {
             run_eoc_vector( false_eocs, d );
         }
     } else if( option == "random" ) {
         if( !true_items.empty() ) {
             std::shuffle( true_items.begin(), true_items.end(), rng_get_engine() );
             run_eoc( true_items.back(), true_eocs );
             true_items.pop_back();
         } else {
             run_eoc_vector( false_eocs, d );
         }
     } else if( option == "manual" ) {
         item_location selected = f( filter );
         run_eoc( selected, true_eocs );
         if( selected.get_item() == nullptr ) {
             run_eoc_vector( false_eocs, d );
         }
     } else if( option == "manual_mult" ) {
         const drop_locations &selected = f_mul( filter );
         for( item_location target : true_items ) {
             bool true_eoc = false;
             for( const drop_location &dloc : selected ) {
                 if( target == dloc.first ) {
                     true_eoc = true;
                     break;
                 }
             }
             if( true_eoc ) {
                 run_eoc( target, true_eocs );
             }
         }
         if( true_items.empty() ) {
             run_eoc_vector( false_eocs, d );
         }
     }
 }
References dialogue::actor(), talker::clone(), eoc, filter, talker::get_character(), dialogue::get_conditionals(), dialogue::get_context(), item_location::get_item(), get_player_character(), get_talker_for(), rng_get_engine(), and run_eoc_vector().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_inv_eocs().
special_talk()
const talk_topic & special_talk (const std::string & action) static
Definition at line 2504 of file npctalk.cpp.
 {
     static const std::map<std::string, talk_topic> key_map = {{
             { "LOOK_AT", talk_topic( "TALK_LOOK_AT" ) },
             { "SIZE_UP_STATS", talk_topic( "TALK_SIZE_UP" ) },
             { "ASSESS_PERSONALITY", talk_topic( "TALK_ASSESS_PERSON" ) },
             { "CHECK_OPINION", talk_topic( "TALK_OPINION" ) },
             { "YELL", talk_topic( "TALK_SHOUT" ) },
         }
     };
     const auto iter = key_map.find( action );
     if( iter != key_map.end() ) {
         return iter->second;
     }
     static const talk_topic no_topic = talk_topic( "TALK_NONE" );
     return no_topic;
 }
References action.
Referenced by dialogue::opt().
tell_magic_veh_stop_following()
static void tell_magic_veh_stop_following () static
Definition at line 780 of file npctalk.cpp.
 {
     for( wrapped_vehicle &veh : get_map().get_vehicles() ) {
         vehicle *v = veh.v;
         if( v->magic ) {
             for( const vpart_reference &vp : v->get_all_parts() ) {
                 const vpart_info &vpi = vp.info();
                 if( vpi.has_flag( "MAGIC_FOLLOW" ) ) {
                     v->is_following = false;
                     v->engine_on = false;
                     break;
                 }
             }
         }
     }
 }
References vehicle::engine_on, vehicle::get_all_parts(), get_map(), vpart_info::has_flag(), vehicle::is_following, and vehicle::magic.
Referenced by game::chat().
tell_magic_veh_to_follow()
static void tell_magic_veh_to_follow () static
Definition at line 763 of file npctalk.cpp.
 {
     Character &player_character = get_player_character();
     for( wrapped_vehicle &veh : get_map().get_vehicles() ) {
         vehicle *v = veh.v;
         if( v->magic ) {
             for( const vpart_reference &vp : v->get_all_parts() ) {
                 const vpart_info &vpi = vp.info();
                 if( vpi.has_flag( "MAGIC_FOLLOW" ) && v->is_owned_by( player_character ) ) {
                     v->activate_magical_follow();
                     break;
                 }
             }
         }
     }
 }
References vehicle::activate_magical_follow(), vehicle::get_all_parts(), get_map(), get_player_character(), vpart_info::has_flag(), vehicle::is_owned_by(), and vehicle::magic.
Referenced by game::chat().
tell_veh_stop_following()
static void tell_veh_stop_following () static
Definition at line 740 of file npctalk.cpp.
 {
     Character &player_character = get_player_character();
     for( wrapped_vehicle &veh : get_map().get_vehicles() ) {
         vehicle *v = veh.v;
         if( v->has_engine_type( fuel_type_animal, false ) && v->is_owned_by( player_character ) ) {
             v->is_following = false;
             v->engine_on = false;
         }
     }
 }
References vehicle::engine_on, fuel_type_animal, get_map(), get_player_character(), vehicle::has_engine_type(), vehicle::is_following, and vehicle::is_owned_by().
Referenced by game::chat().
topic_category()
int topic_category (const talk_topic & the_topic) static
Definition at line 1972 of file npctalk.cpp.
 {
     const std::string &topic = the_topic.id;
     // TODO: ideally, this would be a property of the topic itself.
     // How this works: each category has a set of topics that belong to it, each set is checked
     // for the given topic and if a set contains, the category number is returned.
     static const std::unordered_set<std::string> topic_1 = { {
             "TALK_MISSION_START", "TALK_MISSION_DESCRIBE", "TALK_MISSION_OFFER",
             "TALK_MISSION_ACCEPTED", "TALK_MISSION_REJECTED", "TALK_MISSION_ADVICE",
             "TALK_MISSION_INQUIRE", "TALK_MISSION_SUCCESS", "TALK_MISSION_SUCCESS_LIE",
             "TALK_MISSION_FAILURE", "TALK_MISSION_REWARD", "TALK_MISSION_END",
             "TALK_MISSION_DESCRIBE_URGENT"
         }
     };
     if( topic_1.count( topic ) > 0 ) {
         return 1;
     }
     static const std::unordered_set<std::string> topic_2 = { {
             "TALK_SHARE_EQUIPMENT", "TALK_GIVE_EQUIPMENT", "TALK_DENY_EQUIPMENT"
         }
     };
     if( topic_2.count( topic ) > 0 ) {
         return 2;
     }
     static const std::unordered_set<std::string> topic_3 = { {
             "TALK_SUGGEST_FOLLOW", "TALK_AGREE_FOLLOW", "TALK_DENY_FOLLOW",
         }
     };
     if( topic_3.count( topic ) > 0 ) {
         return 3;
     }
     static const std::unordered_set<std::string> topic_4 = { {
             "TALK_COMBAT_ENGAGEMENT",
         }
     };
     if( topic_4.count( topic ) > 0 ) {
         return 4;
     }
     static const std::unordered_set<std::string> topic_5 = { {
             "TALK_COMBAT_COMMANDS",
         }
     };
     if( topic_5.count( topic ) > 0 ) {
         return 5;
     }
     static const std::unordered_set<std::string> topic_6 = { {
             "TALK_TRAIN", "TALK_TRAIN_START", "TALK_TRAIN_FORCE",
             "TALK_TRAIN_NPC_START", "TALK_TRAIN_NPC_FORCE"
         }
     };
     if( topic_6.count( topic ) > 0 ) {
         return 6;
     }
     static const std::unordered_set<std::string> topic_7 = { {
             "TALK_MISC_RULES",
         }
     };
     if( topic_7.count( topic ) > 0 ) {
         return 7;
     }
     static const std::unordered_set<std::string> topic_8 = { {
             "TALK_AIM_RULES",
         }
     };
     if( topic_8.count( topic ) > 0 ) {
         return 8;
     }
     static const std::unordered_set<std::string> topic_9 = { {
             "TALK_FRIEND", "TALK_GIVE_ITEM", "TALK_USE_ITEM",
         }
     };
     if( topic_9.count( topic ) > 0 ) {
         return 9;
     }
     static const std::unordered_set<std::string> topic_99 = { {
             "TALK_SIZE_UP", "TALK_ASSESS_PERSON", "TALK_LOOK_AT", "TALK_OPINION", "TALK_SHOUT"
         }
     };
     if( topic_99.count( topic ) > 0 ) {
         return 99;
     }
     return -1; // Not grouped with other topics
 }
References talk_topic::id.
Referenced by avatar::talk_to().
total_price()
static int total_price (const talker & seller, const itype_id & item_type) static
Definition at line 1895 of file npctalk.cpp.
 {
     int price = 0;
     item tmp( item_type );
     if( tmp.count_by_charges() ) {
         tmp.charges =  seller.charges_of( item_type );
         price = tmp.price( true );
     } else {
         std::vector<const item *> items = seller.const_items_with( [&item_type]( const item & e ) {
             return item_type == e.type->get_id();
         } );
         for( const item *it : items ) {
             price += it->price( true );
         }
     }
     return price;
 }
References item::charges, talker::charges_of(), talker::const_items_with(), item::count_by_charges(), itype::get_id(), item::price(), and item::type.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), and parse_tags().
training_select_menu()
static std::string training_select_menu (const Character & c, const std::string & prompt) static
Definition at line 577 of file npctalk.cpp.
 {
     int i = 0;
     uilist nmenu;
     nmenu.text = prompt;
     std::vector<std::string> trainlist;
     for( const std::pair<const skill_id, SkillLevel> &s : *c._skills ) {
         bool enabled = s.first->is_teachable() && s.second.level() > 0;
         std::string entry = string_format( "%s: %s (%d)", _( "Skill" ), s.first->name(), s.second.level() );
         nmenu.addentry( i, enabled, MENU_AUTOASSIGN, entry );
         trainlist.emplace_back( s.first.c_str() );
         i++;
     }
     for( const proficiency_id &p : c.known_proficiencies() ) {
         std::string entry = string_format( "%s: %s", _( "Proficiency" ), p->name() );
         nmenu.addentry( i, p->is_teachable(), MENU_AUTOASSIGN, entry );
         trainlist.emplace_back( p.c_str() );
         i++;
     }
     for( const matype_id &m : c.known_styles( true ) ) {
         std::string entry = string_format( "%s: %s", _( "Style" ), m->name.translated() );
         nmenu.addentry( i, m->teachable, MENU_AUTOASSIGN, entry );
         trainlist.emplace_back( m.c_str() );
         i++;
     }
     for( const spell_id &s : c.magic->spells() ) {
         std::string entry = string_format( "%s: %s", _( "Spell" ), s->name.translated() );
         nmenu.addentry( i, s->teachable, MENU_AUTOASSIGN, entry );
         trainlist.emplace_back( s.c_str() );
         i++;
     }
     nmenu.query();
     if( nmenu.ret > -1 && nmenu.ret < static_cast<int>( trainlist.size() ) ) {
         return trainlist[nmenu.ret];
     }
     return "";
 }
References _, uilist::addentry(), c, enabled, MENU_AUTOASSIGN, Pickup::prompt, uilist::query(), uilist::ret, string_format(), and uilist::text.
Referenced by game::chat().
translate_gendered_line()
static std::string translate_gendered_line (const std::string & line, const std::vector< std::string > & relevant_genders, const dialogue & d) static
Definition at line 6787 of file npctalk.cpp.
 {
     GenderMap gender_map;
     for( const std::string &subject : relevant_genders ) {
         if( subject == "npc" ) {
             gender_map[subject] = d.actor( true )->get_grammatical_genders();
         } else if( subject == "u" ) {
             gender_map[subject] = d.actor( false )->get_grammatical_genders();
         } else {
             debugmsg( "Unsupported subject '%s' for grammatical gender in dialogue", subject );
         }
     }
     return gettext_gendered( gender_map, line );
 }
References dialogue::actor(), debugmsg, talker::get_grammatical_genders(), gettext_gendered(), and line().
Referenced by dynamic_line_t::dynamic_line_t().
unload_talk_topics()
void unload_talk_topics ()
Definition at line 7142 of file npctalk.cpp.
 {
     json_talk_topics.clear();
 }
References json_talk_topics.
Referenced by DynamicDataLoader::unload_data().
Variable Documentation
ACT_AIM
const activity_id ACT_AIM("ACT_AIM") ("ACT_AIM") static
Referenced by avatar::talk_to().
ACT_SOCIALIZE
const activity_id ACT_SOCIALIZE("ACT_SOCIALIZE") ("ACT_SOCIALIZE") static
Referenced by avatar::talk_to().
ACT_TRAIN
const activity_id ACT_TRAIN("ACT_TRAIN") ("ACT_TRAIN") static
Referenced by dialogue::dynamic_line(), dialogue::gen_responses(), and avatar::talk_to().
ACT_WAIT_NPC
const activity_id ACT_WAIT_NPC("ACT_WAIT_NPC") ("ACT_WAIT_NPC") static
Referenced by avatar::talk_to().
effect_asked_to_train
const efftype_id effect_asked_to_train("asked_to_train") ("asked_to_train") static
Referenced by game::chat().
effect_narcosis
const efftype_id effect_narcosis("narcosis") ("narcosis") static
Referenced by dialogue::dynamic_line().
effect_riding
const efftype_id effect_riding("riding") ("riding") static
Referenced by game::chat().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect().
effect_under_operation
const efftype_id effect_under_operation("under_operation") ("under_operation") static
Referenced by avatar::talk_to().
fuel_type_animal
const itype_id fuel_type_animal("animal") ("animal") static
Referenced by assign_veh_to_follow(), game::chat(), and tell_veh_stop_following().
itype_foodperson_mask
const itype_id itype_foodperson_mask("foodperson_mask") ("foodperson_mask") static
Referenced by game::chat().
itype_foodperson_mask_on
const itype_id itype_foodperson_mask_on("foodperson_mask_on") ("foodperson_mask_on") static
Referenced by game::chat().
json_talk_topics
std::map<std::string, json_talk_topic> json_talk_topics static
Definition at line 122 of file npctalk.cpp.
Referenced by dialogue::apply_speaker_effects(), dialogue::dynamic_line(), dialogue::gen_responses(), get_talk_topic(), load_inline_topic(), load_talk_topic(), and unload_talk_topics().
parsers
const std::vector<sub_effect_parser> parsers static
Definition at line 6304 of file npctalk.cpp.
Referenced by talk_effect_t::parse_sub_effect().
skill_firstaid
const skill_id skill_firstaid("firstaid") ("firstaid") static
Referenced by dialogue::dynamic_line().
skill_speech
const skill_id skill_speech("speech") ("speech") static
Referenced by talk_trial::roll().
trait_DEBUG_MIND_CONTROL
const trait_id trait_DEBUG_MIND_CONTROL("DEBUG_MIND_CONTROL") ("DEBUG_MIND_CONTROL") static
Referenced by talk_trial::calc_chance(), dialogue::gen_responses(), talk_trial::roll(), and avatar::talk_to().
trait_HALLUCINATION
const trait_id trait_HALLUCINATION("HALLUCINATION") ("HALLUCINATION") static
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc().
trait_PROF_CHURL
const trait_id trait_PROF_CHURL("PROF_CHURL") ("PROF_CHURL") static
Referenced by dialogue::gen_responses().
trait_PROF_FOODP
const trait_id trait_PROF_FOODP("PROF_FOODP") ("PROF_FOODP") static
Referenced by game::chat().
zone_type_NPC_INVESTIGATE_ONLY
const zone_type_id zone_type_NPC_INVESTIGATE_ONLY("NPC_INVESTIGATE_ONLY") ("NPC_INVESTIGATE_ONLY") static
Referenced by npc::handle_sound().
zone_type_NPC_NO_INVESTIGATE
const zone_type_id zone_type_NPC_NO_INVESTIGATE("NPC_NO_INVESTIGATE") ("NPC_NO_INVESTIGATE") static
Referenced by npc::handle_sound().