Cataclysm DDA: src/npctrade_utils.h File Reference
npctrade_utils.h File Reference
#include <list>
Macros
#define CATA_SRC_NPCTRADE_UTILS_H
Functions
void add_fallback_zone (npc &guy)
std::list< item > distribute_items_to_npc_zones (std::list< item > &items, npc &guy)
void consume_items_in_zones (npc &guy, time_duration const &elapsed)
Variables
constexpr char const * fallback_name = "NPC Shopkeeper unsorted fallback zone"
Macro Definition Documentation
CATA_SRC_NPCTRADE_UTILS_H
#define CATA_SRC_NPCTRADE_UTILS_H
Definition at line 3 of file npctrade_utils.h.
Function Documentation
add_fallback_zone()
void add_fallback_zone (npc & guy)
Definition at line 79 of file npctrade_utils.cpp.
 {
     zone_manager &zmgr = zone_manager::get_manager();
     tripoint_abs_ms const loc = guy.get_location();
     faction_id const &fac_id = guy.get_fac_id();
     map &here = get_map();
     if( zmgr.has_near( zone_type_LOOT_UNSORTED, loc, PICKUP_RANGE, fac_id ) ) {
         return;
     }
     std::vector<tripoint_abs_ms> points;
     for( tripoint_abs_ms const &t : closest_points_first( loc, PICKUP_RANGE ) ) {
         tripoint_bub_ms const t_here = here.bub_from_abs( t );
         if( here.has_furn( t_here ) &&
             ( here.furn( t_here )->max_volume > ter_t_floor->max_volume ||
               here.furn( t_here )->has_flag( ter_furn_flag::TFLAG_CONTAINER ) ) &&
             here.can_put_items_ter_furn( t_here ) &&
             !here.route( guy.pos_bub(), t_here, guy.get_pathfinding_settings(),
                          guy.get_path_avoid() )
             .empty() ) {
             points.emplace_back( t );
         }
     }
     if( points.empty() ) {
         zmgr.add( fallback_name, zone_type_LOOT_UNSORTED, fac_id, false, true,
                   loc.raw() + tripoint_north_west, loc.raw() + tripoint_south_east );
     } else {
         for( tripoint_abs_ms const &t : points ) {
             zmgr.add( fallback_name, zone_type_LOOT_UNSORTED, fac_id, false, true, t.raw(),
                       t.raw() );
         }
     }
     DebugLog( DebugLevel::D_WARNING, DebugClass::D_GAME )
             << "Added fallack loot zones for NPC trader " << guy.name;
 }
References zone_manager::add(), map::bub_from_abs(), map::can_put_items_ter_furn(), closest_points_first(), D_GAME, D_WARNING, DebugLog(), fallback_name, map::furn(), npc::get_fac_id(), Creature::get_location(), zone_manager::get_manager(), get_map(), npc::get_path_avoid(), npc::get_pathfinding_settings(), map_data_common_t::has_flag(), map::has_furn(), zone_manager::has_near(), map_data_common_t::max_volume, Character::name, PICKUP_RANGE, Creature::pos_bub(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), map::route(), ter_t_floor, TFLAG_CONTAINER, tripoint_north_west, tripoint_south_east, and zone_type_LOOT_UNSORTED.
Referenced by npc::shop_restock(), and trade_ui::trade_ui().
consume_items_in_zones()
void consume_items_in_zones (npc & guy, time_duration const & elapsed)
Definition at line 157 of file npctrade_utils.cpp.
 {
     std::unordered_set<tripoint> const src = zone_manager::get_manager().get_point_set_loot(
                 guy.get_location(), PICKUP_RANGE, guy.get_fac_id() );
     consume_cache cache;
     map &here = get_map();
     for( tripoint const &pt : src ) {
         consume_queue consumed;
         std::list<item_location> stack =
         here.items_with( pt, [&guy]( item const & it ) {
             return it.is_owned_by( guy );
         } );
         for( item_location &elem : stack ) {
             _consume_item( elem, consumed, cache, guy, elapsed );
         }
         for( item_location &it : consumed ) {
             it.remove_item();
         }
     }
 }
References anonymous_namespace{npctrade_utils.cpp}::_consume_item(), npc::get_fac_id(), Creature::get_location(), zone_manager::get_manager(), get_map(), zone_manager::get_point_set_loot(), item::is_owned_by(), map::items_with(), PICKUP_RANGE, and visitable::remove_item().
Referenced by npc::shop_restock().
distribute_items_to_npc_zones()
std::list<item> distribute_items_to_npc_zones (std::list< item > & items, npc & guy)
Definition at line 117 of file npctrade_utils.cpp.
 {
     zone_manager &zmgr = zone_manager::get_manager();
     map &here = get_map();
     tripoint_abs_ms const loc_abs = guy.get_location();
     faction_id const &fac_id = guy.get_fac_id();
     std::list<item> leftovers;
     dest_t const fallback = _get_shuffled_point_set(
                                 zmgr.get_near( zone_type_LOOT_UNSORTED, loc_abs, PICKUP_RANGE, nullptr, fac_id ) );
     for( item const &it : items ) {
         zone_type_id const zid =
             zmgr.get_near_zone_type_for_item( it, loc_abs, PICKUP_RANGE, fac_id );
         dest_t dest = zid.is_valid() ? _get_shuffled_point_set( zmgr.get_near(
                           zid, loc_abs, PICKUP_RANGE, &it, fac_id ) )
                       : dest_t();
         std::copy( fallback.begin(), fallback.end(), std::back_inserter( dest ) );
         bool leftover = true;
         for( tripoint_abs_ms const &dpoint : dest ) {
             tripoint const dpoint_here = here.getlocal( dpoint );
             std::optional<vpart_reference> const vp = here.veh_at( dpoint_here ).cargo();
             if( vp && vp->vehicle().get_owner() == fac_id ) {
                 leftover = _to_veh( it, vp );
             } else {
                 leftover = _to_map( it, here, dpoint_here );
             }
             if( !leftover ) {
                 break;
             }
         }
         if( leftover ) {
             leftovers.emplace_back( it );
         }
     }
     return leftovers;
 }
References anonymous_namespace{npctrade_utils.cpp}::_get_shuffled_point_set(), anonymous_namespace{npctrade_utils.cpp}::_to_map(), anonymous_namespace{npctrade_utils.cpp}::_to_veh(), optional_vpart_position::cargo(), npc::get_fac_id(), Creature::get_location(), zone_manager::get_manager(), get_map(), zone_manager::get_near(), zone_manager::get_near_zone_type_for_item(), map::getlocal(), string_id< T >::is_valid(), PICKUP_RANGE, map::veh_at(), and zone_type_LOOT_UNSORTED.
Referenced by talk_function::hospital_raid_return(), talk_function::scavenging_raid_return(), npc::shop_restock(), and npc_trading::trade().
Variable Documentation
fallback_name
constexpr char const* fallback_name = "NPC Shopkeeper unsorted fallback zone" constexpr
Definition at line 10 of file npctrade_utils.h.
Referenced by add_fallback_zone(), and trade_ui::trade_ui().