Cataclysm DDA: src/npctalk_funcs.cpp File Reference
npctalk_funcs.cpp File Reference
#include "npctalk.h"
#include <algorithm>
#include <cstddef>
#include <iosfwd>
#include <list>
#include <memory>
#include <new>
#include <optional>
#include <set>
#include <string>
#include <vector>
#include "activity_actor_definitions.h"
#include <activity_handlers.h>
#include "activity_type.h"
#include "auto_pickup.h"
#include "avatar.h"
#include "basecamp.h"
#include "bionics.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "character_id.h"
#include "character_martial_arts.h"
#include "coordinates.h"
#include "creature.h"
#include "debug.h"
#include "dialogue_chatbin.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "faction.h"
#include "game.h"
#include "game_constants.h"
#include "game_inventory.h"
#include "item.h"
#include "item_location.h"
#include "line.h"
#include "magic.h"
#include "map.h"
#include "memory_fast.h"
#include "messages.h"
#include "mission.h"
#include "monster.h"
#include "morale_types.h"
#include "mutation.h"
#include "npc.h"
#include "npctrade.h"
#include "output.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "player_activity.h"
#include "point.h"
#include "rng.h"
#include "text_snippets.h"
#include "translations.h"
#include "ui.h"
#include "viewer.h"
Functions
static void spawn_animal (npc &p, const mtype_id &mon)
static void bionic_install_common (npc &p, Character &patron, Character &patient)
static void bionic_remove_common (npc &p, Character &patient)
static void generic_barber (const std::string &mut_type)
npc * pick_follower ()
Opens a menu and allows player to select a friendly NPC.
Variables
static const activity_id ACT_FIND_MOUNT ("ACT_FIND_MOUNT")
static const activity_id ACT_MOVE_LOOT ("ACT_MOVE_LOOT")
static const activity_id ACT_MULTIPLE_BUTCHER ("ACT_MULTIPLE_BUTCHER")
static const activity_id ACT_MULTIPLE_CHOP_PLANKS ("ACT_MULTIPLE_CHOP_PLANKS")
static const activity_id ACT_MULTIPLE_CHOP_TREES ("ACT_MULTIPLE_CHOP_TREES")
static const activity_id ACT_MULTIPLE_CONSTRUCTION ("ACT_MULTIPLE_CONSTRUCTION")
static const activity_id ACT_MULTIPLE_DIS ("ACT_MULTIPLE_DIS")
static const activity_id ACT_MULTIPLE_FARM ("ACT_MULTIPLE_FARM")
static const activity_id ACT_MULTIPLE_FISH ("ACT_MULTIPLE_FISH")
static const activity_id ACT_MULTIPLE_MINE ("ACT_MULTIPLE_MINE")
static const activity_id ACT_MULTIPLE_MOP ("ACT_MULTIPLE_MOP")
static const activity_id ACT_MULTIPLE_READ ("ACT_MULTIPLE_READ")
static const activity_id ACT_SOCIALIZE ("ACT_SOCIALIZE")
static const activity_id ACT_TRAIN ("ACT_TRAIN")
static const activity_id ACT_TRAIN_TEACHER ("ACT_TRAIN_TEACHER")
static const activity_id ACT_VEHICLE_DECONSTRUCTION ("ACT_VEHICLE_DECONSTRUCTION")
static const activity_id ACT_VEHICLE_REPAIR ("ACT_VEHICLE_REPAIR")
static const activity_id ACT_WAIT_NPC ("ACT_WAIT_NPC")
static const efftype_id effect_allow_sleep ("allow_sleep")
static const efftype_id effect_asked_for_item ("asked_for_item")
static const efftype_id effect_asked_personal_info ("asked_personal_info")
static const efftype_id effect_asked_to_follow ("asked_to_follow")
static const efftype_id effect_asked_to_lead ("asked_to_lead")
static const efftype_id effect_asked_to_train ("asked_to_train")
static const efftype_id effect_bite ("bite")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_currently_busy ("currently_busy")
static const efftype_id effect_infected ("infected")
static const efftype_id effect_lying_down ("lying_down")
static const efftype_id effect_npc_suspend ("npc_suspend")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_socialized_recently ("socialized_recently")
static const faction_id faction_no_faction ("no_faction")
static const faction_id faction_your_followers ("your_followers")
static const mission_type_id mission_MISSION_REACH_SAFETY ("MISSION_REACH_SAFETY")
static const mtype_id mon_chicken ("mon_chicken")
static const mtype_id mon_cow ("mon_cow")
static const mtype_id mon_horse ("mon_horse")
Function Documentation
bionic_install_common()
static void bionic_install_common (npc & p, Character & patron, Character & patient) static
Definition at line 503 of file npctalk_funcs.cpp.
 {
     item_location bionic = game_menus::inv::install_bionic( p, patron, patient, true );
     if( !bionic ) {
         return;
     }
     item *tmp = bionic.get_item();
     tmp->set_var( VAR_TRADE_IGNORE, 1 );
     const itype &it = *tmp->type;
     signed int price = npc_trading::bionic_install_price( p, patient, bionic );
     bool const ret = npc_trading::pay_npc( p, price );
     tmp->erase_var( VAR_TRADE_IGNORE );
     if( !ret ) {
         return;
     }
     //Makes the doctor awesome at installing but not perfect
     if( patient.can_install_bionics( it, p, false, 20 ) ) {
         bionic.remove_item();
         patient.install_bionics( it, p, false, 20 );
     }
 }
References npc_trading::bionic_install_price(), Character::can_install_bionics(), item::erase_var(), game_menus::inv::install_bionic(), Character::install_bionics(), npc_trading::pay_npc(), itype::price, cata::hash64_detail::ret, item::set_var(), item::type, and VAR_TRADE_IGNORE.
Referenced by talk_function::bionic_install(), and talk_function::bionic_install_allies().
bionic_remove_common()
static void bionic_remove_common (npc & p, Character & patient) static
Definition at line 544 of file npctalk_funcs.cpp.
 {
     const bionic_collection all_bio = *patient.my_bionics;
     if( all_bio.empty() ) {
         popup( _( "%s doesn't have any bionics installed…" ), patient.get_name() );
         return;
     }
     std::vector<itype_id> bionic_types;
     std::vector<std::string> bionic_names;
     std::vector<const bionic *> bionics;
     for( const bionic &bio : all_bio ) {
         if( std::find( bionic_types.begin(), bionic_types.end(),
                        bio.info().itype() ) == bionic_types.end() ) {
             bionic_types.push_back( bio.info().itype() );
             if( item::type_is_defined( bio.info().itype() ) ) {
                 item tmp = item( bio.id.str(), calendar::turn_zero );
                 bionic_names.push_back( tmp.tname() + " - " + format_money( 5000 + ( tmp.price( true ) / 4 ) ) );
             } else {
                 bionic_names.push_back( bio.id.str() + " - " + format_money( 5000 ) );
             }
             bionics.push_back( &bio );
         }
     }
     // Choose bionic if applicable
     int bionic_index = uilist( _( "Which bionic do you wish to uninstall?" ),
                                bionic_names );
     // Did we cancel?
     if( bionic_index < 0 ) {
         popup( _( "You decide to hold off…" ) );
         return;
     }
     signed int price;
     if( item::type_is_defined( bionic_types[bionic_index] ) ) {
         price = 5000 + ( item( bionic_types[bionic_index], calendar::turn_zero ).price( true ) / 4 );
     } else {
         price = 5000;
     }
     if( !npc_trading::pay_npc( p, price ) ) {
         return;
     }
     //Makes the doctor awesome at uninstalling but not perfect
     if( patient.can_uninstall_bionic( *bionics[bionic_index], p, false, 20 ) ) {
         patient.uninstall_bionic( *bionics[bionic_index], p, false, 20 );
     }
 }
References _, Character::can_uninstall_bionic(), format_money(), Character::get_name(), item, Character::my_bionics, npc_trading::pay_npc(), popup(), item::price(), itype::price, item::tname(), calendar::turn_zero, item::type_is_defined(), and Character::uninstall_bionic().
Referenced by talk_function::bionic_remove(), and talk_function::bionic_remove_allies().
generic_barber()
static void generic_barber (const std::string & mut_type) static
Definition at line 736 of file npctalk_funcs.cpp.
 {
     uilist hair_menu;
     std::string menu_text;
     if( mut_type == "hair_style" ) {
         menu_text = _( "Choose a new hairstyle" );
     } else if( mut_type == "facial_hair" ) {
         menu_text = _( "Choose a new facial hair style" );
     }
     hair_menu.text = menu_text;
     int index = 0;
     hair_menu.addentry( index, true, 'q', _( "Actually…  I've changed my mind." ) );
     std::vector<trait_and_var> hair_muts = mutations_var_in_type( mut_type );
     Character &player_character = get_player_character();
     trait_and_var cur_hair;
     for( const trait_and_var &elem : hair_muts ) {
         if( player_character.has_trait_variant( elem ) ) {
             cur_hair = elem;
         }
         index += 1;
         hair_menu.addentry( index, true, MENU_AUTOASSIGN, elem.name() );
     }
     hair_menu.query();
     int choice = hair_menu.ret;
     if( choice != 0 ) {
         if( player_character.has_trait( cur_hair.trait ) ) {
             player_character.remove_mutation( cur_hair.trait, true );
         }
         const trait_and_var &chosen = hair_muts[choice - 1];
         player_character.set_mutation( chosen.trait, chosen.trait->variant( chosen.variant ) );
         add_msg( m_info, _( "You get a trendy new cut!" ) );
     }
 }
References _, add_msg(), uilist::addentry(), get_player_character(), Character::has_trait(), Character::has_trait_variant(), m_info, MENU_AUTOASSIGN, mutations_var_in_type(), uilist::query(), Character::remove_mutation(), uilist::ret, Character::set_mutation(), uilist::text, trait_and_var::trait, trait_and_var::variant, and mutation_branch::variant().
Referenced by talk_function::barber_beard(), and talk_function::barber_hair().
pick_follower()
npc* pick_follower ()
Opens a menu and allows player to select a friendly NPC.
Definition at line 1219 of file npctalk_funcs.cpp.
 {
     std::vector<npc *> followers;
     std::vector<tripoint> locations;
     for( npc &guy : g->all_npcs() ) {
         if( guy.is_player_ally() && get_player_view().sees( guy ) ) {
             followers.push_back( &guy );
             locations.push_back( guy.pos() );
         }
     }
     pointmenu_cb callback( locations );
     uilist menu;
     menu.text = _( "Select a follower" );
     menu.callback = &callback;
     menu.w_y_setup = 2;
     for( const npc *p : followers ) {
         menu.addentry( -1, true, MENU_AUTOASSIGN, p->get_name() );
     }
     menu.query();
     if( menu.ret < 0 || static_cast<size_t>( menu.ret ) >= followers.size() ) {
         return nullptr;
     }
     return followers[ menu.ret ];
 }
References _, uilist::addentry(), uilist::callback, g, get_player_view(), anonymous_namespace{overmap_location.cpp}::locations, MENU_AUTOASSIGN, uilist::query(), uilist::ret, uilist::text, and uilist::w_y_setup.
Referenced by talk_function::bionic_install_allies(), talk_function::bionic_remove_allies(), and talk_function::copy_npc_rules().
spawn_animal()
void spawn_animal (npc & p, const mtype_id & mon) static
Definition at line 225 of file npctalk_funcs.cpp.
 {
     if( monster *const mon_ptr = g->place_critter_around( mon, p.pos(), 1 ) ) {
         mon_ptr->friendly = -1;
         mon_ptr->add_effect( effect_pet, 1_turns, true );
     } else {
         // TODO: handle this gracefully (return the money, proper in-character message from npc)
         add_msg_debug( debugmode::DF_NPC, "No space to spawn purchased pet" );
     }
 }
References add_msg_debug, debugmode::DF_NPC, effect_pet, g, and Creature::pos().
Referenced by talk_function::buy_chicken(), talk_function::buy_cow(), and talk_function::buy_horse().
Variable Documentation
ACT_FIND_MOUNT
const activity_id ACT_FIND_MOUNT("ACT_FIND_MOUNT") ("ACT_FIND_MOUNT") static
Referenced by talk_function::find_mount().
ACT_MOVE_LOOT
const activity_id ACT_MOVE_LOOT("ACT_MOVE_LOOT") ("ACT_MOVE_LOOT") static
Referenced by talk_function::sort_loot().
ACT_MULTIPLE_BUTCHER
const activity_id ACT_MULTIPLE_BUTCHER("ACT_MULTIPLE_BUTCHER") ("ACT_MULTIPLE_BUTCHER") static
Referenced by talk_function::do_butcher().
ACT_MULTIPLE_CHOP_PLANKS
const activity_id ACT_MULTIPLE_CHOP_PLANKS("ACT_MULTIPLE_CHOP_PLANKS") ("ACT_MULTIPLE_CHOP_PLANKS") static
Referenced by talk_function::do_chop_plank().
ACT_MULTIPLE_CHOP_TREES
const activity_id ACT_MULTIPLE_CHOP_TREES("ACT_MULTIPLE_CHOP_TREES") ("ACT_MULTIPLE_CHOP_TREES") static
Referenced by talk_function::do_chop_trees().
ACT_MULTIPLE_CONSTRUCTION
const activity_id ACT_MULTIPLE_CONSTRUCTION("ACT_MULTIPLE_CONSTRUCTION") ("ACT_MULTIPLE_CONSTRUCTION") static
Referenced by talk_function::do_construction().
ACT_MULTIPLE_DIS
const activity_id ACT_MULTIPLE_DIS("ACT_MULTIPLE_DIS") ("ACT_MULTIPLE_DIS") static
Referenced by talk_function::do_disassembly().
ACT_MULTIPLE_FARM
const activity_id ACT_MULTIPLE_FARM("ACT_MULTIPLE_FARM") ("ACT_MULTIPLE_FARM") static
Referenced by talk_function::do_farming().
ACT_MULTIPLE_FISH
const activity_id ACT_MULTIPLE_FISH("ACT_MULTIPLE_FISH") ("ACT_MULTIPLE_FISH") static
Referenced by talk_function::do_fishing().
ACT_MULTIPLE_MINE
const activity_id ACT_MULTIPLE_MINE("ACT_MULTIPLE_MINE") ("ACT_MULTIPLE_MINE") static
Referenced by talk_function::do_mining().
ACT_MULTIPLE_MOP
const activity_id ACT_MULTIPLE_MOP("ACT_MULTIPLE_MOP") ("ACT_MULTIPLE_MOP") static
Referenced by talk_function::do_mopping().
ACT_MULTIPLE_READ
const activity_id ACT_MULTIPLE_READ("ACT_MULTIPLE_READ") ("ACT_MULTIPLE_READ") static
Referenced by talk_function::do_read_repeatedly().
ACT_SOCIALIZE
const activity_id ACT_SOCIALIZE("ACT_SOCIALIZE") ("ACT_SOCIALIZE") static
Referenced by talk_function::morale_chat_activity().
ACT_TRAIN
const activity_id ACT_TRAIN("ACT_TRAIN") ("ACT_TRAIN") static
Referenced by talk_function::start_training_gen().
ACT_TRAIN_TEACHER
const activity_id ACT_TRAIN_TEACHER("ACT_TRAIN_TEACHER") ("ACT_TRAIN_TEACHER") static
Referenced by talk_function::start_training_gen().
ACT_VEHICLE_DECONSTRUCTION
const activity_id ACT_VEHICLE_DECONSTRUCTION("ACT_VEHICLE_DECONSTRUCTION") ("ACT_VEHICLE_DECONSTRUCTION") static
Referenced by talk_function::do_vehicle_deconstruct().
ACT_VEHICLE_REPAIR
const activity_id ACT_VEHICLE_REPAIR("ACT_VEHICLE_REPAIR") ("ACT_VEHICLE_REPAIR") static
Referenced by talk_function::do_vehicle_repair().
ACT_WAIT_NPC
const activity_id ACT_WAIT_NPC("ACT_WAIT_NPC") ("ACT_WAIT_NPC") static
Referenced by talk_function::buy_haircut(), talk_function::buy_shave(), talk_function::give_aid(), talk_function::give_all_aid(), talk_function::lesser_give_aid(), and talk_function::lesser_give_all_aid().
effect_allow_sleep
const efftype_id effect_allow_sleep("allow_sleep") ("allow_sleep") static
Referenced by talk_function::wake_up().
effect_asked_for_item
const efftype_id effect_asked_for_item("asked_for_item") ("asked_for_item") static
Referenced by talk_function::deny_equipment(), and talk_function::give_equipment_allowance().
effect_asked_personal_info
const efftype_id effect_asked_personal_info("asked_personal_info") ("asked_personal_info") static
Referenced by talk_function::deny_personal_info().
effect_asked_to_follow
const efftype_id effect_asked_to_follow("asked_to_follow") ("asked_to_follow") static
Referenced by talk_function::deny_follow().
effect_asked_to_lead
const efftype_id effect_asked_to_lead("asked_to_lead") ("asked_to_lead") static
Referenced by talk_function::deny_lead().
effect_asked_to_train
const efftype_id effect_asked_to_train("asked_to_train") ("asked_to_train") static
Referenced by talk_function::deny_train(), and talk_function::start_training_gen().
effect_bite
const efftype_id effect_bite("bite") ("bite") static
Referenced by talk_function::give_aid(), and talk_function::give_all_aid().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by talk_function::give_aid(), talk_function::give_all_aid(), talk_function::lesser_give_aid(), and talk_function::lesser_give_all_aid().
effect_currently_busy
const efftype_id effect_currently_busy("currently_busy") ("currently_busy") static
Referenced by talk_function::give_aid(), talk_function::give_all_aid(), talk_function::lesser_give_aid(), and talk_function::lesser_give_all_aid().
effect_infected
const efftype_id effect_infected("infected") ("infected") static
Referenced by talk_function::give_aid(), and talk_function::give_all_aid().
effect_lying_down
const efftype_id effect_lying_down("lying_down") ("lying_down") static
Referenced by talk_function::wake_up().
effect_npc_suspend
const efftype_id effect_npc_suspend("npc_suspend") ("npc_suspend") static
Referenced by talk_function::wake_up().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by spawn_animal().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by talk_function::wake_up().
effect_socialized_recently
const efftype_id effect_socialized_recently("socialized_recently") ("socialized_recently") static
Referenced by talk_function::morale_chat_activity().
faction_no_faction
const faction_id faction_no_faction("no_faction") ("no_faction") static
Referenced by talk_function::leave().
faction_your_followers
const faction_id faction_your_followers("your_followers") ("your_followers") static
Referenced by talk_function::follow().
mission_MISSION_REACH_SAFETY
const mission_type_id mission_MISSION_REACH_SAFETY("MISSION_REACH_SAFETY") ("MISSION_REACH_SAFETY") static
Referenced by talk_function::lead_to_safety().
mon_chicken
const mtype_id mon_chicken("mon_chicken") ("mon_chicken") static
Referenced by talk_function::buy_chicken().
mon_cow
const mtype_id mon_cow("mon_cow") ("mon_cow") static
Referenced by talk_function::buy_cow().
mon_horse
const mtype_id mon_horse("mon_horse") ("mon_horse") static
Referenced by talk_function::buy_horse().