Cataclysm DDA: src/npctalk.h File Reference
npctalk.h File Reference
#include "npc.h"
#include "type_id.h"
Classes
struct talk_function::teach_domain
Namespaces
talk_function
Macros
#define CATA_SRC_NPCTALK_H
Functions
void talk_function::nothing (npc &)
void talk_function::assign_mission (npc &)
void talk_function::mission_success (npc &)
void talk_function::mission_failure (npc &)
void talk_function::clear_mission (npc &)
void talk_function::mission_reward (npc &)
void talk_function::mission_favor (npc &)
void talk_function::give_equipment (npc &)
void talk_function::give_equipment_allowance (npc &p, int allowance)
void talk_function::lesser_give_aid (npc &)
void talk_function::lesser_give_all_aid (npc &)
void talk_function::give_aid (npc &)
void talk_function::give_all_aid (npc &)
void talk_function::buy_horse (npc &)
void talk_function::buy_cow (npc &)
void talk_function::buy_chicken (npc &)
void talk_function::bionic_install (npc &)
void talk_function::bionic_install_allies (npc &)
void talk_function::bionic_remove (npc &)
void talk_function::bionic_remove_allies (npc &)
void talk_function::dismount (npc &)
void talk_function::find_mount (npc &)
void talk_function::barber_beard (npc &)
void talk_function::barber_hair (npc &)
void talk_function::buy_haircut (npc &)
void talk_function::buy_shave (npc &)
void talk_function::morale_chat (npc &)
void talk_function::morale_chat_activity (npc &)
void talk_function::start_trade (npc &)
void talk_function::sort_loot (npc &)
void talk_function::do_construction (npc &)
void talk_function::do_mining (npc &)
void talk_function::do_mopping (npc &)
void talk_function::do_read (npc &)
void talk_function::do_eread (npc &)
void talk_function::do_read_repeatedly (npc &)
void talk_function::do_chop_plank (npc &)
void talk_function::do_vehicle_deconstruct (npc &)
void talk_function::do_vehicle_repair (npc &)
void talk_function::do_chop_trees (npc &)
void talk_function::do_fishing (npc &)
void talk_function::do_farming (npc &)
void talk_function::do_butcher (npc &)
void talk_function::revert_activity (npc &)
void talk_function::goto_location (npc &)
void talk_function::assign_base (npc &)
void talk_function::assign_guard (npc &)
void talk_function::assign_camp (npc &)
void talk_function::abandon_camp (npc &)
void talk_function::stop_guard (npc &)
void talk_function::end_conversation (npc &)
void talk_function::insult_combat (npc &)
void talk_function::reveal_stats (npc &)
void talk_function::drop_items_in_place (npc &p)
void talk_function::follow (npc &)
void talk_function::follow_only (npc &)
void talk_function::deny_follow (npc &)
void talk_function::deny_lead (npc &)
void talk_function::deny_equipment (npc &)
void talk_function::deny_train (npc &)
void talk_function::deny_personal_info (npc &)
void talk_function::hostile (npc &)
void talk_function::flee (npc &)
void talk_function::leave (npc &)
void talk_function::stop_following (npc &)
void talk_function::stranger_neutral (npc &)
bool talk_function::drop_stolen_item (item &cur_item, npc &p)
void talk_function::start_mugging (npc &)
void talk_function::player_leaving (npc &)
void talk_function::remove_stolen_status (npc &)
void talk_function::drop_weapon (npc &)
void talk_function::player_weapon_away (npc &)
void talk_function::player_weapon_drop (npc &)
void talk_function::drop_stolen_item (npc &)
void talk_function::lead_to_safety (npc &)
void talk_function::start_training (npc &)
void talk_function::start_training_npc (npc &)
void talk_function::start_training_seminar (npc &p)
void talk_function::start_training_gen (Character &teacher, std::vector< Character * > &students, teach_domain &d)
void talk_function::wake_up (npc &)
void talk_function::copy_npc_rules (npc &p)
void talk_function::set_npc_pickup (npc &p)
void talk_function::npc_thankful (npc &p)
void talk_function::clear_overrides (npc &p)
void talk_function::pick_style (npc &p)
void talk_function::do_craft (npc &)
void talk_function::do_disassembly (npc &p)
time_duration calc_skill_training_time_char (const Character &teacher, const Character &student, const skill_id &skill)
Time (in turns) and cost (in cent) for training:
int calc_skill_training_cost_char (const Character &teacher, const Character &student, const skill_id &skill)
time_duration calc_proficiency_training_time (const Character &teacher, const Character &student, const proficiency_id &proficiency)
int calc_proficiency_training_cost (const Character &teacher, const Character &student, const proficiency_id &proficiency)
time_duration calc_ma_style_training_time (const Character &teacher, const Character &student, const matype_id &id)
int calc_ma_style_training_cost (const Character &teacher, const Character &student, const matype_id &id)
time_duration calc_spell_training_time (const Character &teacher, const Character &student, const spell_id &id)
int calc_spell_training_cost (const Character &teacher, const Character &student, const spell_id &id)
const json_talk_topic * get_talk_topic (const std::string &id)
std::vector< int > npcs_select_menu (const std::vector< Character * > &npc_list, const std::string &prompt, const std::function< bool(const Character *)> &exclude_func)
Macro Definition Documentation
CATA_SRC_NPCTALK_H
#define CATA_SRC_NPCTALK_H
Definition at line 3 of file npctalk.h.
Function Documentation
calc_ma_style_training_cost()
int calc_ma_style_training_cost (const Character & teacher, const Character & student, const matype_id & id)
Definition at line 359 of file npctalk.cpp.
 {
     if( friendly_teacher( student, teacher ) ) {
         return 0;
     }
     return 800;
 }
References friendly_teacher().
Referenced by talk_function::start_training_gen().
calc_ma_style_training_time()
time_duration calc_ma_style_training_time (const Character & teacher, const Character & student, const matype_id & id)
Definition at line 353 of file npctalk.cpp.
 {
     return 30_minutes;
 }
Referenced by talk_function::start_training_gen().
calc_proficiency_training_cost()
int calc_proficiency_training_cost (const Character & teacher, const Character & student, const proficiency_id & proficiency)
Definition at line 341 of file npctalk.cpp.
 {
     if( friendly_teacher( student, teacher ) ) {
         return 0;
     }
     return to_seconds<int>( calc_proficiency_training_time( teacher, student, proficiency ) );
 }
References calc_proficiency_training_time(), and friendly_teacher().
Referenced by talker_character_const::proficiency_training_text(), and talk_function::start_training_gen().
calc_proficiency_training_time()
time_duration calc_proficiency_training_time (const Character & teacher, const Character & student, const proficiency_id & proficiency)
Definition at line 335 of file npctalk.cpp.
 {
     return std::min( 30_minutes, student.proficiency_training_needed( proficiency ) );
 }
References min(), and Character::proficiency_training_needed().
Referenced by calc_proficiency_training_cost(), and talk_function::start_training_gen().
calc_skill_training_cost_char()
int calc_skill_training_cost_char (const Character & teacher, const Character & student, const skill_id & skill)
Definition at line 325 of file npctalk.cpp.
 {
     if( friendly_teacher( student, teacher ) ) {
         return 0;
     }
     int skill_level = student.get_knowledge_level( skill );
     return 1000 * ( 1 + skill_level ) * ( 1 + skill_level );
 }
References friendly_teacher(), and Character::get_knowledge_level().
Referenced by talker_character_const::skill_training_text(), and talk_function::start_training_gen().
calc_skill_training_time_char()
time_duration calc_skill_training_time_char (const Character & teacher, const Character & student, const skill_id & skill)
Time (in turns) and cost (in cent) for training:
Definition at line 318 of file npctalk.cpp.
 {
     return 1_hours + 30_minutes * student.get_skill_level( skill ) -
            1_minutes * teacher.get_skill_level( skill );
 }
References Character::get_skill_level().
Referenced by talk_function::start_training_gen().
calc_spell_training_cost()
int calc_spell_training_cost (const Character & teacher, const Character & student, const spell_id & id)
Definition at line 394 of file npctalk.cpp.
 {
     if( friendly_teacher( student, teacher ) ) {
         return 0;
     }
     const spell &temp_spell = teacher.magic->get_spell( id );
     const bool knows = student.magic->knows_spell( id );
     return calc_spell_training_cost_gen( knows, temp_spell.get_difficulty( student ),
                                          temp_spell.get_level() );
 }
References calc_spell_training_cost_gen(), friendly_teacher(), spell::get_difficulty(), spell::get_level(), and Character::magic.
Referenced by talk_function::start_training_gen().
calc_spell_training_time()
time_duration calc_spell_training_time (const Character & teacher, const Character & student, const spell_id & id)
Definition at line 374 of file npctalk.cpp.
 {
     if( student.magic->knows_spell( id ) ) {
         return 1_hours;
     } else {
         const int time_int = student.magic->time_to_learn_spell( student, id ) / 50;
         return time_duration::from_seconds( clamp( time_int, 7200, 21600 ) );
     }
 }
References clamp(), time_duration::from_seconds(), and Character::magic.
Referenced by talk_function::start_training_gen().
get_talk_topic()
const json_talk_topic* get_talk_topic (const std::string & id)
Definition at line 7254 of file npctalk.cpp.
 {
     auto it = json_talk_topics.find( id );
     if( it == json_talk_topics.end() ) {
         return nullptr;
     }
     return &it->second;
 }
References json_talk_topics.
Referenced by npc_template::check_consistency().
npcs_select_menu()
std::vector<int> npcs_select_menu (const std::vector< Character * > & npc_list, const std::string & prompt, const std::function< bool(const Character *)> & exclude_func)
Definition at line 536 of file npctalk.cpp.
 {
     std::vector<int> picked;
     if( npc_list.empty() ) {
         return picked;
     }
     const int npc_count = npc_list.size();
     int last_index = 0;
     do {
         uilist nmenu;
         nmenu.text = prompt;
         for( int i = 0; i < npc_count; i++ ) {
             std::string entry;
             if( std::find( picked.begin(), picked.end(), i ) != picked.end() ) {
                 entry = "* ";
             }
             bool enable = exclude_func == nullptr || !exclude_func( npc_list[i] );
             entry += npc_list[i]->name_and_maybe_activity();
             nmenu.addentry( i, enable, MENU_AUTOASSIGN, entry );
         }
         nmenu.addentry( npc_count, true, MENU_AUTOASSIGN, _( "Finish selection" ) );
         nmenu.selected = nmenu.fselected = last_index;
         nmenu.query();
         if( nmenu.ret < 0 ) {
             return std::vector<int>();
         } else if( nmenu.ret >= npc_count ) {
             break;
         }
         std::vector<int>::iterator exists = std::find( picked.begin(), picked.end(), nmenu.ret );
         if( exists != picked.end() ) {
             picked.erase( exists );
         } else {
             picked.push_back( nmenu.ret );
         }
         last_index = nmenu.fselected;
     } while( true );
     return picked;
 }
References _, uilist::addentry(), uilist::fselected, MENU_AUTOASSIGN, Pickup::prompt, uilist::query(), uilist::ret, uilist::selected, and uilist::text.
Referenced by game::chat(), and talk_function::start_training_seminar().