Cataclysm DDA: src/omdata.h File Reference
omdata.h File Reference
#include <array>
#include <climits>
#include <cstddef>
#include <cstdint>
#include <iosfwd>
#include <list>
#include <new>
#include <optional>
#include <set>
#include <string>
#include <vector>
#include "assign.h"
#include "catacharset.h"
#include "color.h"
#include "common_types.h"
#include "coordinates.h"
#include "cube_direction.h"
#include "enum_bitset.h"
#include "mapgen_parameter.h"
#include "point.h"
#include "translations.h"
#include "type_id.h"
Classes
struct enum_traits< om_direction::type >
class overmap_land_use_code
struct overmap_spawns
struct overmap_static_spawns
struct enum_traits< oter_flags >
struct enum_traits< oter_travel_cost_type >
struct oter_type_t
struct oter_t
struct overmap_special_spawns
struct overmap_special_locations
struct overmap_special_terrain
struct overmap_special_connection
struct overmap_special_placement_constraints
struct enum_traits< overmap_special_subtype >
class overmap_special
struct overmap_special_migration
Namespaces
om_direction
Direction on the overmap.
overmap_terrains
overmap_land_use_codes
overmap_specials
city_buildings
Macros
#define CATA_SRC_OMDATA_H
Typedefs
using overmap_land_use_code_id = string_id< overmap_land_use_code >
Enumerations
enum class om_direction::type : int {
om_direction::invalid = -1 , om_direction::none , om_direction::north = none , om_direction::east ,
om_direction::south , om_direction::west , om_direction::last
}
Basic enum for directions.
enum class oter_flags : int {
known_down = 0 , known_up , no_rotate , should_not_spawn ,
water , river_tile , has_sidewalk , bridge ,
ignore_rotation_for_adjacency , line_drawing , subway_connection , requires_predecessor ,
lake , lake_shore , ocean , ocean_shore ,
ravine , ravine_edge , generic_loot , risk_high ,
risk_low , source_ammo , source_animals , source_books ,
source_chemistry , source_clothing , source_construction , source_cooking ,
source_drink , source_electronics , source_fabrication , source_farming ,
source_food , source_forage , source_fuel , source_gun ,
source_luxury , source_medicine , source_people , source_safety ,
source_tailoring , source_vehicles , source_weapon , num_oter_flags
}
enum class oter_travel_cost_type : int {
other , impassable , road , field ,
dirt_road , trail , forest , shore ,
swamp , water , air , last
}
enum class overmap_special_subtype { fixed , mutable_ , last }
Functions
const overmap_land_use_code_id land_use_code_forest ("forest")
const overmap_land_use_code_id land_use_code_wetland ("wetland")
const overmap_land_use_code_id land_use_code_wetland_forest ("wetland_forest")
const overmap_land_use_code_id land_use_code_wetland_saltwater ("wetland_saltwater")
std::string om_direction::name (type dir)
Get Human readable name of a direction.
point om_direction::rotate (const point &p, type dir)
Various rotations.
tripoint om_direction::rotate (const tripoint &p, type dir)
template<typename Point , coords::scale Scale>
auto om_direction::rotate (const coords::coord_point< Point, coords::origin::relative, Scale > &p, type dir) -> coords::coord_point< Point, coords::origin::relative, Scale >
uint32_t om_direction::rotate_symbol (uint32_t sym, type dir)
point om_direction::displace (type dir, int dist=1)
Returns point(0, 0) displaced in specified direction by a specified distance.
type om_direction::add (type dir1, type dir2)
Returns a sum of two numbers.
type om_direction::turn_left (type dir)
Turn by 90 degrees to the left, to the right, or randomly (either left or right).
type om_direction::turn_right (type dir)
type om_direction::turn_random (type dir)
type om_direction::opposite (type dir)
Returns an opposite direction.
type om_direction::random ()
Returns a random direction.
bool om_direction::are_parallel (type dir1, type dir2)
Whether these directions are parallel.
type om_direction::from_cube (cube_direction, const std::string &error_msg)
void overmap_terrains::load (const JsonObject &jo, const std::string &src)
void overmap_terrains::check_consistency ()
void overmap_terrains::finalize ()
void overmap_terrains::reset ()
const std::vector< oter_t > & overmap_terrains::get_all ()
void overmap_land_use_codes::load (const JsonObject &jo, const std::string &src)
void overmap_land_use_codes::finalize ()
void overmap_land_use_codes::check_consistency ()
void overmap_land_use_codes::reset ()
const std::vector< overmap_land_use_code > & overmap_land_use_codes::get_all ()
void overmap_specials::load (const JsonObject &jo, const std::string &src)
void overmap_specials::finalize ()
void overmap_specials::finalize_mapgen_parameters ()
void overmap_specials::check_consistency ()
void overmap_specials::reset ()
const std::vector< overmap_special > & overmap_specials::get_all ()
overmap_special_batch overmap_specials::get_default_batch (const point_abs_om &origin)
overmap_special_id overmap_specials::create_building_from (const string_id< oter_type_t > &base)
Generates a simple special from a building id.
void city_buildings::load (const JsonObject &jo, const std::string &src)
Variables
const std::array< type, 4 > om_direction::all = {{ type::north, type::east, type::south, type::west }}
For the purposes of iteration.
const size_t om_direction::size = all.size()
constexpr size_t om_direction::bits = static_cast<size_t>(-1) >> (CHAR_BIT *sizeof(size_t) - size)
Number of bits needed to store directions.
constexpr int OMSPEC_FREQ = 15
Macro Definition Documentation
CATA_SRC_OMDATA_H
#define CATA_SRC_OMDATA_H
Definition at line 3 of file omdata.h.
Typedef Documentation
overmap_land_use_code_id
using overmap_land_use_code_id = string_id<overmap_land_use_code>
Definition at line 34 of file omdata.h.
Enumeration Type Documentation
oter_flags
enum oter_flags : int strong
Enumerator
known_down
known_up
no_rotate
should_not_spawn
water
river_tile
has_sidewalk
bridge
ignore_rotation_for_adjacency
line_drawing
subway_connection
requires_predecessor
lake
lake_shore
ocean
ocean_shore
ravine
ravine_edge
generic_loot
risk_high
risk_low
source_ammo
source_animals
source_books
source_chemistry
source_clothing
source_construction
source_cooking
source_drink
source_electronics
source_fabrication
source_farming
source_food
source_forage
source_fuel
source_gun
source_luxury
source_medicine
source_people
source_safety
source_tailoring
source_vehicles
source_weapon
num_oter_flags
Definition at line 172 of file omdata.h.
                       : int {
     known_down = 0,
     known_up,
     no_rotate,    // this tile doesn't have four rotated versions (north, east, south, west)
     should_not_spawn,
     water,
     river_tile,
     has_sidewalk,
     bridge,
     ignore_rotation_for_adjacency,
     line_drawing, // does this tile have 8 versions, including straights, bends, tees, and a fourway?
     subway_connection,
     requires_predecessor,
     lake,
     lake_shore,
     ocean,
     ocean_shore,
     ravine,
     ravine_edge,
     generic_loot,
     risk_high,
     risk_low,
     source_ammo,
     source_animals,
     source_books,
     source_chemistry,
     source_clothing,
     source_construction,
     source_cooking,
     source_drink,
     source_electronics,
     source_fabrication,
     source_farming,
     source_food,
     source_forage,
     source_fuel,
     source_gun,
     source_luxury,
     source_medicine,
     source_people,
     source_safety,
     source_tailoring,
     source_vehicles,
     source_weapon,
     num_oter_flags
 };
oter_travel_cost_type
enum oter_travel_cost_type : int strong
Enumerator
other
impassable
road
field
dirt_road
trail
forest
shore
swamp
water
air
last
Definition at line 224 of file omdata.h.
                                  : int {
     other,
     impassable,
     road,
     field,
     dirt_road,
     trail,
     forest,
     shore,
     swamp,
     water,
     air,
     last
 };
overmap_special_subtype
enum overmap_special_subtype strong
Enumerator
fixed
mutable_
last
Definition at line 531 of file omdata.h.
{
     fixed,
     mutable_,
     last
 };
Function Documentation
land_use_code_forest()
const overmap_land_use_code_id land_use_code_forest ("forest") inline
Referenced by oter_t::is_wooded().
land_use_code_wetland()
const overmap_land_use_code_id land_use_code_wetland ("wetland") inline
Referenced by oter_t::is_wooded().
land_use_code_wetland_forest()
const overmap_land_use_code_id land_use_code_wetland_forest ("wetland_forest") inline
Referenced by oter_t::is_wooded().
land_use_code_wetland_saltwater()
const overmap_land_use_code_id land_use_code_wetland_saltwater ("wetland_saltwater") inline
Referenced by oter_t::is_wooded().
Variable Documentation
OMSPEC_FREQ
constexpr int OMSPEC_FREQ = 15 constexpr
Definition at line 465 of file omdata.h.
Referenced by overmap_specials::check_consistency(), overmapbuffer::place_special(), and overmap::place_specials().