Cataclysm DDA: src/options.h File Reference
options.h File Reference
#include <algorithm>
#include <functional>
#include <iosfwd>
#include <map>
#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "translations.h"
#include "type_id.h"
Classes
class options_manager
class options_manager::cOpt
class options_manager::Group
Option group.
class options_manager::PageItem
Single page item (entry).
class options_manager::Page
A page (or tab) to be displayed in the options UI.
struct option_slider
struct option_slider::option_slider_level
struct option_slider::option_slider_level::opt_slider_option
Macros
#define CATA_SRC_OPTIONS_H
Functions
options_manager & get_options ()
bool has_option (const std::string &name)
template<typename T >
T get_option (const std::string &name, bool convert=false)
Variables
std::map< std::string, cata_path > TILESETS
A mapping(string:string) that stores all tileset values.
std::map< std::string, cata_path > SOUNDPACKS
A mapping(string:string) that stores all soundpack values.
Macro Definition Documentation
CATA_SRC_OPTIONS_H
#define CATA_SRC_OPTIONS_H
Definition at line 3 of file options.h.
Function Documentation
get_option()
template<typename T > T get_option (const std::string & name, bool convert = false) inline
Definition at line 498 of file options.h.
 {
     return get_options().get_option( name ).value_as<T>( convert );
 }
References cata::convert(), options_manager::get_option(), get_options(), om_direction::name(), and options_manager::cOpt::value_as().
Referenced by options_manager::add_options_general(), options_manager::add_options_graphics(), game::do_regular_action(), main_menu::opening_screen(), options_manager::show(), and safemode::show().
get_options()
options_manager& get_options ()
Definition at line 59 of file options.cpp.
 {
     static options_manager single_instance;
     return single_instance;
 }
Referenced by auto_pickup::player_settings::add_rule(), safemode::add_rule(), options_manager::cOpt::checkPrerequisite(), game::do_regular_action(), regional_settings::finalize(), get_option(), has_option(), worldfactory::init(), game_ui::init_ui(), load_external_option(), WORLD::load_options(), load_world_option(), main(), anonymous_namespace{system_locale.cpp}::matchGameLanguage(), main_menu::opening_screen(), worldfactory::remove_world(), options_manager::Page::removeRepeatedEmptyLines(), game::save_achievements(), worldfactory::set_active_world(), options_manager::cOpt::setPrerequisites(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), options_manager::show(), safemode::show(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_options(), WORLD::WORLD(), and game::write_memorial_file().
has_option()
bool has_option (const std::string & name) inline
Definition at line 492 of file options.h.
 {
     return get_options().has_option( name );
 }
References get_options(), options_manager::has_option(), and om_direction::name().
Referenced by options_manager::update_options_cache().
Variable Documentation
SOUNDPACKS
std::map<std::string, cata_path> SOUNDPACKS extern
A mapping(string:string) that stores all soundpack values.
Firsts string is soundpack NAME from config. Second string is directory that contains soundpack.
Definition at line 56 of file options.cpp.
Referenced by options_manager::build_soundpacks_list().
TILESETS
std::map<std::string, cata_path> TILESETS extern
A mapping(string:string) that stores all tileset values.
Firsts string is tileset NAME from config. Second string is directory that contain tileset.
Definition at line 55 of file options.cpp.
Referenced by options_manager::build_tilesets_list().