Cataclysm DDA: src/options.cpp File Reference
options.cpp File Reference
#include "options.h"
#include <cfloat>
#include <climits>
#include <clocale>
#include <iterator>
#include <stdexcept>
#include "cached_options.h"
#include "calendar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "color.h"
#include "cursesdef.h"
#include "cursesport.h"
#include "debug.h"
#include "filesystem.h"
#include "game.h"
#include "game_constants.h"
#include "generic_factory.h"
#include "input_context.h"
#include "json.h"
#include "lang_stats.h"
#include "line.h"
#include "mapsharing.h"
#include "output.h"
#include "path_info.h"
#include "point.h"
#include "popup.h"
#include "sdltiles.h"
#include "sdlsound.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "system_locale.h"
#include "translations.h"
#include "try_parse_integer.h"
#include "ui_manager.h"
#include "worldfactory.h"
#include <algorithm>
#include <cstdlib>
#include <memory>
#include <sstream>
#include <string>
Classes
struct string_col
String with color.
Namespaces
anonymous_namespace{options.cpp}
Functions
static const std::map< std::string, std::pair< std::string, std::map< std::string, std::string > > > & get_migrated_options ()
options_manager & get_options ()
static const std::string blank_value (1, 001)
static options_manager::cOpt::COPT_VALUE_TYPE get_value_type (const std::string &sType)
template<>
std::string options_manager::cOpt::value_as< std::string > (bool convert) const
static std::vector< options_manager::id_and_option > build_resource_list (std::map< std::string, std::string > &resource_option, const std::string &operation_name, const std::string &dirname, const std::string &filename)
Fill a mapping with values.
static std::vector< options_manager::id_and_option > build_resource_list (std::map< std::string, cata_path > &resource_option, const std::string &operation_name, const cata_path &dirname, const std::string &filename)
static void refresh_tiles (bool, bool, bool)
static void draw_borders_external (const catacurses::window &w, int horizontal_level, const std::set< int > &vert_lines, const bool world_options_only)
static void draw_borders_internal (const catacurses::window &w, std::set< int > &vert_lines)
Variables
std::map< std::string, cata_path > TILESETS
A mapping(string:string) that stores all tileset values.
std::map< std::string, cata_path > SOUNDPACKS
A mapping(string:string) that stores all soundpack values.
generic_factory< option_slider > anonymous_namespace{options.cpp}::option_slider_factory ("option slider")
Function Documentation
blank_value()
static const std::string blank_value (1 , 001) static
Referenced by options_manager::add_retry(), and options_manager::enable_json().
build_resource_list() [1/2]
static std::vector<options_manager::id_and_option> build_resource_list (std::map< std::string, cata_path > & resource_option, const std::string & operation_name, const cata_path & dirname, const std::string & filename) static
Definition at line 1178 of file options.cpp.
 {
     std::vector<options_manager::id_and_option> resource_names;
     resource_option.clear();
     if( !dir_exist( dirname.get_unrelative_path() ) ) {
         return resource_names; // don't try to enumerate non-existing directories
     }
     const auto resource_dirs = get_directories_with( filename, dirname, true );
     for( const cata_path &resource_dir : resource_dirs ) {
         read_from_file( resource_dir / filename, [&]( std::istream & fin ) {
             std::string resource_name;
             std::string view_name;
             // should only have 2 values inside it, otherwise is going to only load the last 2 values
             while( !fin.eof() ) {
                 std::string sOption;
                 fin >> sOption;
                 if( sOption.empty() || sOption[0] == '#' ) {
                     getline( fin, sOption );  // Empty line or comment, chomp it
                 } else {
                     if( sOption.find( "NAME" ) != std::string::npos ) {
                         resource_name.clear();
                         getline( fin, resource_name );
                         resource_name = trim( resource_name );
                     } else if( sOption.find( "VIEW" ) != std::string::npos ) {
                         view_name.clear();
                         getline( fin, view_name );
                         view_name = trim( view_name );
                         break;
                     }
                 }
             }
             resource_names.emplace_back( resource_name,
                                          view_name.empty() ? no_translation( resource_name ) : to_translation( view_name ) );
             if( resource_option.count( resource_name ) != 0 ) {
                 debugmsg( "Found \"%s\" duplicate with name \"%s\" (new definition will be ignored)",
                           operation_name, resource_name );
             } else {
                 resource_option.insert( std::pair<std::string, cata_path>( resource_name, resource_dir ) );
             }
         } );
     }
     return resource_names;
 }
References dir_exist(), get_directories_with(), cata_path::get_unrelative_path(), no_translation(), read_from_file(), and to_translation().
build_resource_list() [2/2]
static std::vector<options_manager::id_and_option> build_resource_list (std::map< std::string, std::string > & resource_option, const std::string & operation_name, const std::string & dirname, const std::string & filename) static
Fill a mapping with values.
Scans all directories in dirname directory for a file named filename. All found values added to resource_option as name, resource_dir. Furthermore, it builds possible values list for cOpt class.
Definition at line 1130 of file options.cpp.
 {
     std::vector<options_manager::id_and_option> resource_names;
     resource_option.clear();
     const auto resource_dirs = get_directories_with( filename, dirname, true );
     const std::string slash_filename = "/" + filename;
     for( const std::string &resource_dir : resource_dirs ) {
         read_from_file( resource_dir + slash_filename, [&]( std::istream & fin ) {
             std::string resource_name;
             std::string view_name;
             // should only have 2 values inside it, otherwise is going to only load the last 2 values
             while( !fin.eof() ) {
                 std::string sOption;
                 fin >> sOption;
                 if( sOption.empty() || sOption[0] == '#' ) {
                     getline( fin, sOption );    // Empty line or comment, chomp it
                 } else {
                     if( sOption.find( "NAME" ) != std::string::npos ) {
                         resource_name.clear();
                         getline( fin, resource_name );
                         resource_name = trim( resource_name );
                     } else if( sOption.find( "VIEW" ) != std::string::npos ) {
                         view_name.clear();
                         getline( fin, view_name );
                         view_name = trim( view_name );
                         break;
                     }
                 }
             }
             resource_names.emplace_back( resource_name,
                                          view_name.empty() ? no_translation( resource_name ) : to_translation( view_name ) );
             if( resource_option.count( resource_name ) != 0 ) {
                 debugmsg( "Found \"%s\" duplicate with name \"%s\" (new definition will be ignored)",
                           operation_name, resource_name );
             } else {
                 resource_option.insert( std::pair<std::string, std::string>( resource_name, resource_dir ) );
             }
         } );
     }
     return resource_names;
 }
References get_directories_with(), no_translation(), read_from_file(), and to_translation().
Referenced by options_manager::search_resource().
draw_borders_external()
static void draw_borders_external (const catacurses::window & w, int horizontal_level, const std::set< int > & vert_lines, const bool world_options_only) static
Definition at line 3307 of file options.cpp.
 {
     if( !world_options_only ) {
         draw_border( w, BORDER_COLOR, _( "Options" ) );
     }
     // intersections
     mvwputch( w, point( 0, horizontal_level ), BORDER_COLOR, LINE_XXXO ); // |-
     mvwputch( w, point( getmaxx( w ) - 1, horizontal_level ), BORDER_COLOR, LINE_XOXX ); // -|
     for( const int &x : vert_lines ) {
         mvwputch( w, point( x + 1, getmaxy( w ) - 1 ), BORDER_COLOR, LINE_XXOX ); // _|_
     }
     wnoutrefresh( w );
 }
References _, BORDER_COLOR, draw_border(), catacurses::getmaxx(), catacurses::getmaxy(), LINE_XOXX, LINE_XXOX, LINE_XXXO, mvwputch(), point, and catacurses::wnoutrefresh().
Referenced by options_manager::show().
draw_borders_internal()
static void draw_borders_internal (const catacurses::window & w, std::set< int > & vert_lines) static
Definition at line 3323 of file options.cpp.
 {
     for( int i = 0; i < getmaxx( w ); ++i ) {
         if( vert_lines.count( i ) != 0 ) {
             // intersection
             mvwputch( w, point( i, 0 ), BORDER_COLOR, LINE_OXXX );
         } else {
             // regular line
             mvwputch( w, point( i, 0 ), BORDER_COLOR, LINE_OXOX );
         }
     }
     wnoutrefresh( w );
 }
References BORDER_COLOR, catacurses::getmaxx(), LINE_OXOX, LINE_OXXX, mvwputch(), point, and catacurses::wnoutrefresh().
Referenced by options_manager::show().
get_migrated_options()
static const std::map<std::string, std::pair<std::string, std::map<std::string, std::string> > >& get_migrated_options () static
Definition at line 195 of file options.cpp.
 {
     static const std::map<std::string, std::pair<std::string, std::map<std::string, std::string>>> opt
     = { {"DELETE_WORLD", { "WORLD_END", { {"no", "keep" }, {"yes", "delete"} } } } };
     return opt;
 }
Referenced by options_manager::migrateOptionName(), and options_manager::migrateOptionValue().
get_options()
options_manager& get_options ()
Definition at line 202 of file options.cpp.
 {
     static options_manager single_instance;
     return single_instance;
 }
Referenced by auto_pickup::player_settings::add_rule(), safemode::add_rule(), options_manager::cOpt::checkPrerequisite(), game::do_regular_action(), regional_settings::finalize(), get_option(), has_option(), worldfactory::init(), game_ui::init_ui(), load_external_option(), WORLD::load_options(), load_world_option(), main(), anonymous_namespace{system_locale.cpp}::matchGameLanguage(), main_menu::opening_screen(), worldfactory::remove_world(), options_manager::Page::removeRepeatedEmptyLines(), game::save_achievements(), worldfactory::set_active_world(), options_manager::cOpt::setPrerequisites(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), options_manager::show(), safemode::show(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_options(), WORLD::WORLD(), and game::write_memorial_file().
get_value_type()
static options_manager::cOpt::COPT_VALUE_TYPE get_value_type (const std::string & sType) static
Definition at line 292 of file options.cpp.
 {
     using CVT = options_manager::cOpt::COPT_VALUE_TYPE;
     static std::unordered_map<std::string, CVT> vt_map = {
         { "float", CVT::CVT_FLOAT },
         { "bool", CVT::CVT_BOOL },
         { "int", CVT::CVT_INT },
         { "int_map", CVT::CVT_INT },
         { "string_select", CVT::CVT_STRING },
         { "string_input", CVT::CVT_STRING },
         { "VOID", CVT::CVT_VOID }
     };
     auto result = vt_map.find( sType );
     return result != vt_map.end() ? result->second : options_manager::cOpt::CVT_UNKNOWN;
 }
References options_manager::cOpt::CVT_UNKNOWN.
Referenced by options_manager::add(), and options_manager::add_external().
options_manager::cOpt::value_as< std::string >()
template<> std::string options_manager::cOpt::value_as< std::string > (bool convert) const
Definition at line 790 of file options.cpp.
 {
     if( std::optional<std::string> ret = _convert<std::string>(); convert && ret ) {
         return *ret;
     }
     if( eType != CVT_STRING ) {
         debugmsg( "%s tried to get string value from option of type %s", sName, sType );
     }
     return sSet;
 }
References cata::convert(), debugmsg, and cata::hash64_detail::ret.
refresh_tiles()
static void refresh_tiles (bool , bool , bool) static
Definition at line 3302 of file options.cpp.
 {
 }
Referenced by options_manager::show().
Variable Documentation
SOUNDPACKS
std::map<std::string, cata_path> SOUNDPACKS
A mapping(string:string) that stores all soundpack values.
Firsts string is soundpack NAME from config. Second string is directory that contains soundpack.
Definition at line 56 of file options.cpp.
Referenced by options_manager::build_soundpacks_list().
TILESETS
std::map<std::string, cata_path> TILESETS
A mapping(string:string) that stores all tileset values.
Firsts string is tileset NAME from config. Second string is directory that contain tileset.
Definition at line 55 of file options.cpp.
Referenced by options_manager::build_tilesets_list().