Cataclysm DDA: src/ordered_static_globals.cpp File Reference
ordered_static_globals.cpp File Reference
#include "ordered_static_globals.h"
#include "ammo_effect.h"
#include "city.h"
#include "field_type.h"
Functions
void ordered_static_globals ()
Function Documentation
ordered_static_globals()
void ordered_static_globals ()
Definition at line 7 of file ordered_static_globals.cpp.
 {
     get_city_factory();
     get_all_field_types();
     get_all_ammo_effects();
 }
References get_all_ammo_effects(), get_all_field_types(), and get_city_factory().
Referenced by main().