Cataclysm DDA: src/output.cpp File Reference
output.cpp File Reference
#include "output.h"
#include <cctype>
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdarg>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <map>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <vector>
#include "cached_options.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "color.h"
#include "cursesport.h"
#include "cursesdef.h"
#include "game_constants.h"
#include "input.h"
#include "input_context.h"
#include "item.h"
#include "line.h"
#include "game.h"
#include "options.h"
#include "point.h"
#include "popup.h"
#include "rng.h"
#include "sdltiles.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "ui_manager.h"
#include "unicode.h"
#include "units_utility.h"
#include "wcwidth.h"
Classes
struct anonymous_namespace{output.cpp}::ItemFilterPrefix
Namespaces
anonymous_namespace{output.cpp}
Typedefs
using char_t = std::string::value_type
using RatingVector = std::vector< std::tuple< double, char, std::string > >
Functions
std::string string_from_int (const catacurses::chtype ch)
std::vector< std::string > foldstring (const std::string &str, int width, const char split)
Split the input text into separate lines and wrap long lines.
std::vector< std::string > split_by_color (const std::string_view s)
std::string remove_color_tags (const std::string_view s)
Removes the color tags from the input string.
color_tag_parse_result::tag_type update_color_stack (std::stack< nc_color > &color_stack, const std::string_view seg, const report_color_error color_error)
Adds the color represented by the next color tag found in the string to the top of the stack.
void print_colored_text (const catacurses::window &w, const point &p, nc_color &color, const nc_color &base_color, const std::string_view text, const report_color_error color_error)
Print text with embedded color_tags, x, y are in curses system.
void trim_and_print (const catacurses::window &w, const point &begin, const int width, const nc_color &base_color, const std::string &text, const report_color_error color_error)
Prints a single line of text.
std::string trim_by_length (const std::string &text, int width)
int print_scrollable (const catacurses::window &w, int begin_line, const std::string &text, const nc_color &base_color, const std::string &scroll_msg)
Print word wrapped text (with color_tags) into the window.
int fold_and_print (const catacurses::window &w, const point &begin, int width, const nc_color &base_color, const std::string &text, const char split)
Fold and print text in the given window.
int fold_and_print_from (const catacurses::window &w, const point &begin, int width, int begin_line, const nc_color &base_color, const std::string &text)
Like fold_and_print, but starts the output with the N-th line of the folded string.
void scrollable_text (const std::function< catacurses::window()> &init_window, const std::string &title, const std::string &text)
void add_folded_name_and_value (std::vector< std::string > &current_vector, const std::string &name, const std::string &value, const int field_width)
void add_folded_name_and_value (std::vector< std::string > &current_vector, const std::string &name, const int value, const int field_width)
std::string trimmed_name_and_value (const std::string &name, const std::string &value, const int field_width)
std::string trimmed_name_and_value (const std::string &name, int const value, const int field_width)
void center_print (const catacurses::window &w, const int y, const nc_color &FG, const std::string &text)
int right_print (const catacurses::window &w, const int line, const int right_indent, const nc_color &FG, const std::string &text)
void wputch (const catacurses::window &w, nc_color FG, int ch)
void mvwputch (const catacurses::window &w, const point &p, nc_color FG, int ch)
void mvwputch (const catacurses::window &w, const point &p, nc_color FG, const std::string &ch)
void mvwputch_inv (const catacurses::window &w, const point &p, nc_color FG, int ch)
void mvwputch_inv (const catacurses::window &w, const point &p, nc_color FG, const std::string &ch)
void mvwputch_hi (const catacurses::window &w, const point &p, nc_color FG, int ch)
void mvwputch_hi (const catacurses::window &w, const point &p, nc_color FG, const std::string &ch)
void draw_custom_border (const catacurses::window &w, const catacurses::chtype ls, const catacurses::chtype rs, const catacurses::chtype ts, const catacurses::chtype bs, const catacurses::chtype tl, const catacurses::chtype tr, const catacurses::chtype bl, const catacurses::chtype br, const nc_color &FG, const point &pos, int height, int width)
void draw_border (const catacurses::window &w, nc_color border_color, const std::string &title, nc_color title_color)
void draw_border_below_tabs (const catacurses::window &w, nc_color border_color)
bool query_yn (const std::string &text)
query_ynq_result query_ynq (const std::string &text)
bool query_int (int &result, const std::string &text)
std::vector< std::string > get_hotkeys (const std::string_view s)
int popup (const std::string &text, PopupFlags flags)
input_event draw_item_info (const int iLeft, const int iWidth, const int iTop, const int iHeight, item_info_data &data)
std::string string_replace (std::string text, const std::string &before, const std::string &after)
std::string replace_colors (std::string text)
std::string item_filter_rule_string (const item_filter_type type)
Get the tips printed by draw_item_filter_rules as a string.
void draw_item_filter_rules (const catacurses::window &win, const int starty, const int height, const item_filter_type type)
Write some tips (such as precede items with - to exclude them) onto the window.
std::string format_item_info (const std::vector< iteminfo > &vItemDisplay, const std::vector< iteminfo > &vItemCompare)
input_event draw_item_info (const catacurses::window &win, item_info_data &data)
input_event draw_item_info (const std::function< catacurses::window()> &init_window, item_info_data &data)
char rand_char ()
template<typename Predicate >
static std::string trim (std::string_view s, Predicate pred)
template<typename Prep >
std::string trim_trailing (const std::string_view s, Prep prep)
std::string trim (const std::string_view s)
std::string trim_trailing_punctuations (const std::string_view s)
std::string remove_punctuations (const std::string_view s)
std::string to_upper_case (const std::string &s)
std::vector< size_t > get_tag_positions (const std::string_view s)
std::string word_rewrap (const std::string &in, int width, const uint32_t split)
void draw_tab (const catacurses::window &w, int iOffsetX, const std::string_view sText, bool bSelected)
inclusive_rectangle< point > draw_subtab (const catacurses::window &w, int iOffsetX, const std::string &sText, bool bSelected, bool bDecorate, bool bDisabled)
std::map< size_t, inclusive_rectangle< point > > draw_tabs (const catacurses::window &w, const std::vector< std::string > &tab_texts, const size_t current_tab, const size_t offset)
std::map< std::string, inclusive_rectangle< point > > draw_tabs (const catacurses::window &w, const std::vector< std::string > &tab_texts, const std::string &current_tab)
best_fit find_best_fit_in_size (const std::vector< int > &size_of_items_to_fit, const int &selected, const int &allowed_size, const int &spacer_size, const int &continuation_marker_size)
Algorith for finding the largest subset of varied-length items that fit in allowed_size.
std::pair< std::vector< std::string >, size_t > fit_tabs_to_width (const size_t max_width, const int current_tab, const std::vector< std::string > &original_tab_list)
Produces the largest subset of a list of tabs (for draw_tabs or draw_subtab) that can be displayed within max_width.
void draw_scrollbar (const catacurses::window &window, const int iCurrentLine, const int iContentHeight, const int iNumLines, const point &offset, nc_color bar_color, const bool bDoNotScrollToEnd)
Draw a scrollbar (Legacy function, use class scrollbar instead!)
void calcStartPos (int &iStartPos, const int iCurrentLine, const int iContentHeight, const int iNumEntries)
std::string rewrite_vsnprintf (const char *msg)
void replace_city_tag (std::string &input, const std::string &name)
void replace_keybind_tag (std::string &input)
void replace_substring (std::string &input, const std::string &substring, const std::string &replacement, bool all)
std::string uppercase_first_letter (const std::string &str)
std::string lowercase_first_letter (const std::string &str)
std::string rm_prefix (std::string str, char c1, char c2)
Removes the prefix starting at the first occurrence of c1 until the first occurrence of c2.
size_t shortcut_print (const catacurses::window &w, const point &p, nc_color text_color, nc_color shortcut_color, const std::string &fmt)
size_t shortcut_print (const catacurses::window &w, nc_color text_color, nc_color shortcut_color, const std::string &fmt)
std::string shortcut_text (nc_color shortcut_color, const std::string &fmt)
std::pair< std::string, nc_color > get_bar (const float cur, const float max, const int width, const bool extra_resolution, const std::vector< nc_color > &colors)
std::pair< std::string, nc_color > get_hp_bar (const int cur_hp, const int max_hp, const bool is_mon)
std::pair< std::string, nc_color > get_stamina_bar (int cur_stam, int max_stam)
std::pair< std::string, nc_color > get_light_level (const float light)
std::pair< std::string, nc_color > rad_badge_color (const int rad)
std::string formatted_hotkey (const std::string &hotkey, const nc_color text_color)
std::string get_labeled_bar (const double val, const int width, const std::string &label, char c)
template<typename BarIterator >
std::string get_labeled_bar (const double val, const int width, const std::string &label, BarIterator begin, BarIterator end)
template std::string get_labeled_bar< RatingVector::iterator > (const double val, const int width, const std::string &label, RatingVector::iterator begin, RatingVector::iterator end, std::function< std::string(RatingVector::iterator, int)> printer)
template<typename BarIterator >
std::string get_labeled_bar (const double val, const int width, const std::string &label, BarIterator begin, BarIterator end, std::function< std::string(BarIterator, int)> printer)
void insert_table (const catacurses::window &w, int pad, int line, int columns, const nc_color &FG, const std::string &divider, bool r_align, const std::vector< std::string > &data)
Inserts a table into a window, with data right-aligned.
std::string satiety_bar (const int calpereffv)
std::string healthy_bar (const int healthy)
nc_color msgtype_to_color (const game_message_type type, const bool bOldMsg)
bool wildcard_match (const std::string &text_in, const std::string &pattern_in)
Match text containing wildcards (*)
std::string wildcard_trim_rule (const std::string &pattern_in)
int ci_find_substr (const std::string_view str1, const std::string_view str2, const std::locale &loc)
std::string format_volume (const units::volume &volume)
Convert and format volume.
std::string format_volume (const units::volume &volume, int width, bool *out_truncated, double *out_value)
Convert, clamp and format volume, taking into account the specified width (0 for unlimited space), optionally returning a flag that indicate if the value was truncated to fit the width, optionally returning the formatted value as double.
int get_terminal_width ()
Get the width in font glyphs of the drawing screen.
int get_terminal_height ()
Get the height in font glyphs of the drawing screen.
bool is_draw_tiles_mode ()
Check whether we're in tile drawing mode.
void mvwprintz (const catacurses::window &w, const point &p, const nc_color &FG, const std::string &text)
void wprintz (const catacurses::window &w, const nc_color &FG, const std::string &text)
Variables
int TERMX
int TERMY
int POSX
int POSY
int TERRAIN_WINDOW_WIDTH
int TERRAIN_WINDOW_HEIGHT
int TERRAIN_WINDOW_TERM_WIDTH
int TERRAIN_WINDOW_TERM_HEIGHT
int FULL_SCREEN_WIDTH
int FULL_SCREEN_HEIGHT
int OVERMAP_WINDOW_HEIGHT
int OVERMAP_WINDOW_WIDTH
int OVERMAP_WINDOW_TERM_WIDTH
int OVERMAP_WINDOW_TERM_HEIGHT
int OVERMAP_LEGEND_WIDTH
scrollingcombattext SCT
static const std::chrono::duration< int, std::milli > base_mouse_delay
static const std::chrono::duration< int, std::milli > scrollwheel_delay
static const std::array< translation, 3 > item_filter_rule_intros
static const std::vector< ItemFilterPrefix > item_filter_prefixes
static const translation item_filter_help_1
static const translation item_filter_help_2
Typedef Documentation
char_t
using char_t = std::string::value_type
Definition at line 1388 of file output.cpp.
RatingVector
using RatingVector = std::vector<std::tuple<double, char, std::string> >
Definition at line 2741 of file output.cpp.
Function Documentation
add_folded_name_and_value() [1/2]
void add_folded_name_and_value (std::vector< std::string > & current_vector, const std::string & name, const int value, const int field_width)
Definition at line 532 of file output.cpp.
 {
     add_folded_name_and_value( current_vector, name, string_format( "%d", value ), field_width );
 }
References add_folded_name_and_value(), om_direction::name(), and string_format().
add_folded_name_and_value() [2/2]
void add_folded_name_and_value (std::vector< std::string > & current_vector, const std::string & name, const std::string & value, const int field_width)
Definition at line 510 of file output.cpp.
 {
     const int name_width = utf8_width( name );
     const int value_width = utf8_width( value );
     if( name_width + value_width + 1 >= field_width ) {
         if( value_width >= field_width ) {
             debugmsg( "Unable to fit name (%s) and value (%s) in available space (%i)", name, value,
                       field_width );
         } else {
             std::vector<std::string> new_lines;
             new_lines = foldstring( name, field_width - value_width );
             const int spacing = field_width - utf8_width( new_lines.back() ) - value_width;
             new_lines.back() = new_lines.back() + std::string( spacing, ' ' ) + value;
             current_vector.insert( current_vector.end(), new_lines.begin(), new_lines.end() );
         }
     } else {
         const int spacing = field_width - name_width - value_width;
         current_vector.emplace_back( name + std::string( spacing, ' ' ) + value );
     }
 }
References debugmsg, foldstring(), om_direction::name(), and utf8_width().
Referenced by add_folded_name_and_value(), anonymous_namespace{armor_layers.cpp}::clothing_properties(), and anonymous_namespace{armor_layers.cpp}::clothing_protection().
calcStartPos()
void calcStartPos (int & iStartPos, const int iCurrentLine, const int iContentHeight, const int iNumEntries)
Definition at line 2278 of file output.cpp.
 {
     if( iNumEntries <= iContentHeight ) {
         iStartPos = 0;
     } else if( get_option<bool>( "MENU_SCROLL" ) ) {
         iStartPos = iCurrentLine - ( iContentHeight - 1 ) / 2;
         if( iStartPos < 0 ) {
             iStartPos = 0;
         } else if( iStartPos + iContentHeight > iNumEntries ) {
             iStartPos = iNumEntries - iContentHeight;
         }
     } else {
         if( iCurrentLine < iStartPos ) {
             iStartPos = iCurrentLine;
         } else if( iCurrentLine >= iStartPos + iContentHeight ) {
             iStartPos = 1 + iCurrentLine - iContentHeight;
         } else if( iStartPos + iContentHeight > iNumEntries ) {
             iStartPos = iNumEntries - iContentHeight;
         }
     }
 }
Referenced by debug_menu::change_spells(), talk_function::display_and_choose_opts(), worldfactory::draw_mod_list(), game::list_items(), game::list_monsters(), set_hobbies(), set_profession(), set_scenario(), set_skills(), set_traits(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), options_manager::show(), safemode::show(), uilist::show(), color_manager::show_gui(), worldfactory::show_worldgen_basic(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), and game::zones_manager().
center_print()
void center_print (const catacurses::window & w, const int y, const nc_color & FG, const std::string & text)
Definition at line 559 of file output.cpp.
 {
     int window_width = getmaxx( w );
     int string_width = utf8_width( text, true );
     int x;
     if( string_width >= window_width ) {
         x = 0;
     } else {
         x = ( window_width - string_width ) / 2;
     }
     const int available_width = std::max( 1, window_width - x );
     trim_and_print( w, point( x, y ), available_width, FG, text );
 }
References catacurses::getmaxx(), max(), trim_and_print(), and utf8_width().
Referenced by trade_ui::_draw_header(), game::bury_screen(), debug_menu::change_spells(), draw_bionics_tab(), draw_bionics_titlebar(), draw_border(), inventory_selector::draw_columns(), draw_effects_tab(), draw_encumbrance_tab(), draw_medical_titlebar(), worldfactory::draw_mod_list(), draw_proficiencies_tab(), draw_skills_tab(), draw_speed_tab(), draw_stats_tab(), draw_traits_tab(), game::look_around(), main_menu::print_menu(), live_view::show(), diary::show_diary_ui(), snake_game::snake_over(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), and editmap::update_view_with_help().
ci_find_substr()
int ci_find_substr (const std::string_view str1, const std::string_view str2, const std::locale & loc)
Definition at line 3213 of file output.cpp.
 {
     std::string_view::const_iterator it =
         std::search( str1.begin(), str1.end(), str2.begin(), str2.end(),
     [&]( const char str1_in, const char str2_in ) {
         return std::toupper( str1_in, loc ) == std::toupper( str2_in, loc );
     } );
     if( it != str1.end() ) {
         return it - str1.begin();
     } else {
         return -1;    // not found
     }
 }
References overmap_ui::search().
Referenced by Messages::dialog::do_filter(), input_context::get_desc(), auto_pickup::player_settings::has_rule(), safemode::has_rule(), auto_pickup::player_settings::remove_rule(), safemode::remove_rule(), and wildcard_match().
draw_border()
void draw_border (const catacurses::window & w, nc_color border_color, const std::string & title, nc_color title_color)
Definition at line 688 of file output.cpp.
 {
     wattron( w, border_color );
     wborder( w, LINE_XOXO, LINE_XOXO, LINE_OXOX, LINE_OXOX,
              LINE_OXXO, LINE_OOXX, LINE_XXOO, LINE_XOOX );
     wattroff( w, border_color );
     if( !title.empty() ) {
         center_print( w, 0, title_color, title );
     }
 }
References center_print(), LINE_OOXX, LINE_OXOX, LINE_OXXO, LINE_XOOX, LINE_XOXO, LINE_XXOO, music::title, catacurses::wattroff(), catacurses::wattron(), and catacurses::wborder().
Referenced by trade_ui::_draw_header(), game::bury_screen(), game_menus::inv::compare_items(), Character::conduct_blood_analysis(), exosuit_interact::create_or_get_ui_adaptor(), veh_app_interact::create_or_get_ui_adaptor(), decorate_panel(), avatar::disp_medical(), player_morale::display(), talk_function::display_and_choose_opts(), veh_interact::display_grid(), help::display_help(), main_menu::display_sub_menu(), main_menu::display_text(), string_input_popup::draw(), prof_window::draw_borders(), draw_borders_external(), inventory_selector::draw_frame(), draw_grid(), lightson_game::draw_level(), draw_medical_titlebar(), game::draw_minimap(), target_ui::draw_ui_window(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::look_around(), worldfactory::pick_world(), overmap_ui::place_ter_or_special(), avatar::power_bionics(), avatar::power_mutations(), snake_game::print_header(), dialogue_window::print_header(), anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), advanced_inventory::redraw_pane(), advanced_inventory::redraw_sidebar(), computer_session::refresh(), smart_controller_ui::refresh(), advanced_inventory::refresh_minimap(), scrollable_text(), overmap_ui::search(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), Messages::dialog::show(), robot_finds_kitten::show(), options_manager::show(), safemode::show(), live_view::show(), uilist::show(), worldfactory::show_active_world_mods(), diary::show_diary_ui(), color_manager::show_gui(), worldfactory::show_worldgen_basic(), lightson_game::start_game(), minesweeper_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), overmap_ui::update_note_preview(), editmap::update_view_with_help(), and basecamp::worker_assignment_ui().
draw_border_below_tabs()
void draw_border_below_tabs (const catacurses::window & w, nc_color border_color)
Definition at line 700 of file output.cpp.
 {
     int width = getmaxx( w );
     int height = getmaxy( w );
     for( int i = 1; i < width - 1; i++ ) {
         mvwputch( w, point( i, height - 1 ), border_color, LINE_OXOX );
     }
     for( int i = 3; i < height - 1; i++ ) {
         mvwputch( w, point( 0, i ), border_color, LINE_XOXO );
         mvwputch( w, point( width - 1, i ), border_color, LINE_XOXO );
     }
     mvwputch( w, point( 0, height - 1 ), border_color, LINE_XXOO ); // |_
     mvwputch( w, point( width - 1, height - 1 ), border_color, LINE_XOOX ); // _|
 }
References catacurses::getmaxx(), catacurses::getmaxy(), LINE_OXOX, LINE_XOOX, LINE_XOXO, LINE_XXOO, and mvwputch().
Referenced by faction_manager::display(), tab_manager::draw(), worldfactory::draw_worldgen_tabs(), show_scores_ui(), and worldfactory::show_worldgen_tab_modselection().
draw_custom_border()
void draw_custom_border (const catacurses::window & w, const catacurses::chtype ls, const catacurses::chtype rs, const catacurses::chtype ts, const catacurses::chtype bs, const catacurses::chtype tl, const catacurses::chtype tr, const catacurses::chtype bl, const catacurses::chtype br, const nc_color & FG, const point & pos, int height, int width)
Definition at line 637 of file output.cpp.
 {
     wattron( w, FG );
     height = ( height == 0 ) ? getmaxy( w ) - pos.y : height;
     width = ( width == 0 ) ? getmaxx( w ) - pos.x : width;
     for( int j = pos.y; j < height + pos.y - 1; j++ ) {
         if( ls > 0 ) {
             mvwputch( w, point( pos.x, j ), c_light_gray, ( ls > 1 ) ? ls : LINE_XOXO ); // |
         }
         if( rs > 0 ) {
             mvwputch( w, point( pos.x + width - 1, j ), c_light_gray, ( rs > 1 ) ? rs : LINE_XOXO ); // |
         }
     }
     for( int j = pos.x; j < width + pos.x - 1; j++ ) {
         if( ts > 0 ) {
             mvwputch( w, point( j, pos.y ), c_light_gray, ( ts > 1 ) ? ts : LINE_OXOX ); // --
         }
         if( bs > 0 ) {
             mvwputch( w, point( j, pos.y + height - 1 ), c_light_gray, ( bs > 1 ) ? bs : LINE_OXOX ); // --
         }
     }
     if( tl > 0 ) {
         mvwputch( w, pos, c_light_gray, ( tl > 1 ) ? tl : LINE_OXXO ); // |^
     }
     if( tr > 0 ) {
         mvwputch( w, pos + point( -1 + width, 0 ), c_light_gray, ( tr > 1 ) ? tr : LINE_OOXX ); // ^|
     }
     if( bl > 0 ) {
         mvwputch( w, pos + point( 0, -1 + height ), c_light_gray, ( bl > 1 ) ? bl : LINE_XXOO ); // |_
     }
     if( br > 0 ) {
         mvwputch( w, pos + point( -1 + width, -1 + height ), c_light_gray,
                   ( br > 1 ) ? br : LINE_XOOX ); // _|
     }
     wattroff( w, FG );
 }
References c_light_gray, catacurses::getmaxx(), catacurses::getmaxy(), LINE_OOXX, LINE_OXOX, LINE_OXXO, LINE_XOOX, LINE_XOXO, LINE_XXOO, mvwputch(), math_opers::pos(), catacurses::wattroff(), and catacurses::wattron().
Referenced by draw_item_info(), game::list_items(), game::list_monsters(), and minesweeper_game::start_game().
draw_item_filter_rules()
void draw_item_filter_rules (const catacurses::window & win, int starty, int height, item_filter_type type)
Write some tips (such as precede items with - to exclude them) onto the window.
Parameters
win Window we are drawing in
starty Where to start relative to the top of the window.
height Every row from starty to starty + height - 1 will be cleared before printing the rules.
type Filter to use when drawing
Definition at line 1096 of file output.cpp.
 {
     // Clear every row, but the leftmost/rightmost pixels intact.
     const int len = getmaxx( win ) - 2;
     for( int i = 0; i < height; i++ ) {
         mvwprintz( win, point( 1, starty + i ), c_black, std::string( len, ' ' ) );
     }
     fold_and_print( win, point( 1, starty ), len, c_white, "%s", item_filter_rule_string( type ) );
     wnoutrefresh( win );
 }
References c_black, c_white, fold_and_print(), catacurses::getmaxx(), item_filter_rule_string(), mvwprintz(), point, type, and catacurses::wnoutrefresh().
Referenced by advanced_inventory::display().
draw_item_info() [1/3]
input_event draw_item_info (const catacurses::window & win, item_info_data & data)
Definition at line 1188 of file output.cpp.
 {
     return draw_item_info( [&]() -> catacurses::window {
         return win;
     }, data );
 }
References draw_item_info().
draw_item_info() [2/3]
input_event draw_item_info (const int iLeft, const int iWidth, const int iTop, const int iHeight, item_info_data & data)
Definition at line 962 of file output.cpp.
 {
     catacurses::window win =
         catacurses::newwin( iHeight, iWidth,
                             point( iLeft, iTop ) );
 #if defined(TILES)
     clear_window_area( win );
 #endif // TILES
     wclear( win );
     wnoutrefresh( win );
     return draw_item_info( win, data );
 }
References catacurses::newwin(), point, catacurses::wclear(), and catacurses::wnoutrefresh().
Referenced by advanced_inventory::action_examine(), game_menus::inv::compare_items(), inventory_examiner::draw_item_details(), draw_item_info(), exosuit_interact::draw_iteminfo(), game::inventory_item_menu(), game::list_items(), select_crafter_and_crafting_recipe(), and iexamine::vending().
draw_item_info() [3/3]
input_event draw_item_info (const std::function< catacurses::window()> & init_window, item_info_data & data)
Definition at line 1195 of file output.cpp.
 {
     std::string buffer;
     int line_num = data.use_full_win || data.without_border ? 0 : 1;
     if( !data.get_item_name().empty() ) {
         buffer += data.get_item_name() + "\n";
     }
     // If type name is set, and not already contained in item name, output it too
     if( !data.get_type_name().empty() &&
         data.get_item_name().find( data.get_type_name() ) == std::string::npos ) {
         buffer += data.get_type_name() + "\n";
     }
     for( unsigned int i = 0; i < data.padding; i++ ) {
         buffer += "\n";
     }
     buffer += format_item_info( data.get_item_display(), data.get_item_compare() );
     const int b = data.use_full_win ? 0 : ( data.without_border ? 1 : 2 );
     catacurses::window win;
     int width = 0;
     int height = 0;
     std::vector<std::string> folded;
     scrollbar item_info_bar;
     const auto clamp_ptr_selected_scroll = [&]() {
         if( *data.ptr_selected < 0 || height < 0 ||
             folded.size() < static_cast<size_t>( height ) ) {
             *data.ptr_selected = 0;
         } else if( static_cast<size_t>( *data.ptr_selected ) + height >= folded.size() ) {
             *data.ptr_selected = static_cast<int>( folded.size() ) - height;
         }
     };
     const auto init = [&]() {
         win = init_window();
         width = getmaxx( win ) - ( data.use_full_win ? 1 : b * 2 );
         height = getmaxy( win ) - ( data.use_full_win ? 0 : 2 );
         folded = foldstring( buffer, width - 1 );
         clamp_ptr_selected_scroll();
     };
     const auto redraw = [&]() {
         werase( win );
         for( int line = 0; line < height; ++line ) {
             const int idx = *data.ptr_selected + line;
             if( idx >= 0 && static_cast<size_t>( idx ) < folded.size() ) {
                 if( folded[idx] == "--" ) {
                     for( int x = 0; x < width; x++ ) {
                         mvwputch( win, point( b + x, line_num + line ), c_dark_gray, LINE_OXOX );
                     }
                 } else {
                     trim_and_print( win, point( b, line_num + line ), width - 1, c_light_gray, folded[idx] );
                 }
             }
         }
         item_info_bar.offset_x( data.scrollbar_left ? 0 : getmaxx( win ) - 1 )
         .offset_y( data.without_border && data.use_full_win ? 0 : 1 )
         .content_size( folded.size() ).viewport_size( height )
         .viewport_pos( *data.ptr_selected )
         .scroll_to_last( false )
         .apply( win );
         if( !data.without_border ) {
             draw_custom_border( win, buffer.empty() );
         }
         wnoutrefresh( win );
     };
     if( data.without_getch ) {
         init();
         redraw();
         return input_event();
     }
     ui_adaptor ui;
     ui.on_screen_resize( [&]( ui_adaptor & ui ) {
         init();
         ui.position_from_window( win );
     } );
     ui.mark_resize();
     ui.on_redraw( [&]( const ui_adaptor & ) {
         redraw();
     } );
     input_context ctxt( "default", keyboard_mode::keychar );
     if( data.handle_scrolling ) {
         ctxt.register_action( "PAGE_UP" );
         ctxt.register_action( "PAGE_DOWN" );
         item_info_bar.set_draggable( ctxt );
     }
     ctxt.register_action( "CONFIRM" );
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     if( data.any_input ) {
         ctxt.register_action( "ANY_INPUT" );
     }
     std::string action;
     while( true ) {
         ui_manager::redraw();
         action = ctxt.handle_input();
         std::optional<point> coord = ctxt.get_coordinates_text( catacurses::stdscr );
         if( data.handle_scrolling && item_info_bar.handle_dragging( action, coord, *data.ptr_selected ) ) {
             // No action required, the scrollbar has handled it
         } else if( data.handle_scrolling && action == "PAGE_UP" ) {
             *data.ptr_selected -= height;
             clamp_ptr_selected_scroll();
         } else if( data.handle_scrolling && action == "PAGE_DOWN" ) {
             *data.ptr_selected += height;
             clamp_ptr_selected_scroll();
         } else if( action == "CONFIRM" || action == "QUIT" ||
                    ( data.any_input && action == "ANY_INPUT" &&
                      !ctxt.get_raw_input().sequence.empty() ) ) {
             break;
         }
     }
     return ctxt.get_raw_input();
 }
References action, item_info_data::any_input, scrollbar::apply(), b, c_dark_gray, c_light_gray, scrollbar::content_size(), draw_custom_border(), foldstring(), format_item_info(), input_context::get_coordinates_text(), item_info_data::get_item_compare(), item_info_data::get_item_display(), item_info_data::get_item_name(), input_context::get_raw_input(), item_info_data::get_type_name(), catacurses::getmaxx(), catacurses::getmaxy(), scrollbar::handle_dragging(), input_context::handle_input(), item_info_data::handle_scrolling, init, init_window(), keychar, line, LINE_OXOX, mvwputch(), scrollbar::offset_x(), scrollbar::offset_y(), item_info_data::padding, point, item_info_data::ptr_selected, ui_manager::redraw(), input_context::register_action(), scrollbar::scroll_to_last(), item_info_data::scrollbar_left, input_event::sequence, scrollbar::set_draggable(), catacurses::stdscr, trim_and_print(), item_info_data::use_full_win, scrollbar::viewport_pos(), scrollbar::viewport_size(), catacurses::werase(), item_info_data::without_border, item_info_data::without_getch, and catacurses::wnoutrefresh().
draw_scrollbar()
void draw_scrollbar (const catacurses::window & window, const int iCurrentLine, const int iContentHeight, const int iNumLines, const point & offset, nc_color bar_color, const bool bDoNotScrollToEnd)
Draw a scrollbar (Legacy function, use class scrollbar instead!)
Parameters
window Pointer of window to draw on
iCurrentLine The starting line or currently selected line out of the iNumLines lines
iContentHeight Height of the scrollbar
iNumLines Total number of lines
offset Point indicating drawing offset
bar_color Default line color
bDoNotScrollToEnd True if the last (iContentHeight-1) lines cannot be a start position or be selected If false, iCurrentLine can be from 0 to iNumLines - 1. If true, iCurrentLine can be at most iNumLines - iContentHeight.
Definition at line 1704 of file output.cpp.
 {
     scrollbar()
     .offset_x( offset.x )
     .offset_y( offset.y )
     .content_size( iNumLines )
     .viewport_pos( iCurrentLine )
     .viewport_size( iContentHeight )
     .slot_color( bar_color )
     .scroll_to_last( !bDoNotScrollToEnd )
     .apply( window );
 }
References scrollbar::apply(), scrollbar::content_size(), scrollbar::offset_x(), scrollbar::offset_y(), scrollbar::scroll_to_last(), scrollbar::slot_color(), scrollbar::viewport_pos(), scrollbar::viewport_size(), point::x, and point::y.
Referenced by faction_manager::display(), player_morale::display(), main_menu::display_sub_menu(), main_menu::display_text(), draw_bionics_tab(), draw_effects_tab(), worldfactory::draw_mod_list(), draw_proficiencies_tab(), draw_skills_tab(), draw_speed_tab(), draw_traits_tab(), draw_x_info(), basecamp::job_assignment_ui(), game::list_items(), game::list_monsters(), avatar::power_bionics(), avatar::power_mutations(), Character::print_encumbrance(), anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), wish_item_callback::refresh(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), safemode::show(), color_manager::show_gui(), iexamine::vending(), basecamp::worker_assignment_ui(), and game::zones_manager().
draw_subtab()
inclusive_rectangle<point> draw_subtab (const catacurses::window & w, int iOffsetX, const std::string & sText, bool bSelected, bool bDecorate, bool bDisabled)
Definition at line 1534 of file output.cpp.
 {
     int iOffsetXRight = iOffsetX + utf8_width( sText ) + 1;
     if( !bDisabled ) {
         mvwprintz( w, point( iOffsetX + 1, 0 ), bSelected ? h_white : c_light_gray, sText );
     } else {
         mvwprintz( w, point( iOffsetX + 1, 0 ), bSelected ? h_dark_gray : c_dark_gray, sText );
     }
     if( bSelected ) {
         if( !bDisabled ) {
             mvwputch( w, point( iOffsetX - bDecorate, 0 ),      h_white, '<' );
             mvwputch( w, point( iOffsetXRight + bDecorate, 0 ), h_white, '>' );
         } else {
             mvwputch( w, point( iOffsetX - bDecorate, 0 ),      h_dark_gray, '<' );
             mvwputch( w, point( iOffsetXRight + bDecorate, 0 ), h_dark_gray, '>' );
         }
         for( int i = iOffsetX + 1; bDecorate && i < iOffsetXRight; i++ ) {
             mvwputch( w, point( i, 1 ), c_black, ' ' );
         }
     }
     return inclusive_rectangle<point>( point( iOffsetX, 0 ), point( iOffsetXRight, 0 ) );
 }
References c_black, c_dark_gray, c_light_gray, h_dark_gray, h_white, mvwprintz(), mvwputch(), point, and utf8_width().
Referenced by veh_interact::display_list(), talk_function::draw_camp_tabs(), and draw_recipe_subtabs().
draw_tab()
void draw_tab (const catacurses::window & w, int iOffsetX, const std::string_view sText, bool bSelected)
Definition at line 1495 of file output.cpp.
 {
     int iOffsetXRight = iOffsetX + utf8_width( sText, true ) + 1;
     mvwputch( w, point( iOffsetX, 0 ),      c_light_gray, LINE_OXXO ); // |^
     mvwputch( w, point( iOffsetXRight, 0 ), c_light_gray, LINE_OOXX ); // ^|
     mvwputch( w, point( iOffsetX, 1 ),      c_light_gray, LINE_XOXO ); // |
     mvwputch( w, point( iOffsetXRight, 1 ), c_light_gray, LINE_XOXO ); // |
     nc_color selected = h_white;
     nc_color not_selected = c_light_gray;
     if( bSelected ) {
         print_colored_text( w, point( iOffsetX + 1, 1 ), selected, selected, sText );
     } else {
         print_colored_text( w, point( iOffsetX + 1, 1 ), not_selected, not_selected, sText );
     }
     for( int i = iOffsetX + 1; i < iOffsetXRight; i++ ) {
         mvwputch( w, point( i, 0 ), c_light_gray, LINE_OXOX );  // -
     }
     if( bSelected ) {
         mvwputch( w, point( iOffsetX - 1, 1 ),      h_white, '<' );
         mvwputch( w, point( iOffsetXRight + 1, 1 ), h_white, '>' );
         for( int i = iOffsetX + 1; i < iOffsetXRight; i++ ) {
             mvwputch( w, point( i, 2 ), c_black, ' ' );
         }
         mvwputch( w, point( iOffsetX, 2 ),      c_light_gray, LINE_XOOX ); // _|
         mvwputch( w, point( iOffsetXRight, 2 ), c_light_gray, LINE_XXOO ); // |_
     } else {
         mvwputch( w, point( iOffsetX, 2 ),      c_light_gray, LINE_XXOX ); // _|_
         mvwputch( w, point( iOffsetXRight, 2 ), c_light_gray, LINE_XXOX ); // _|_
     }
 }
References c_black, c_light_gray, h_white, LINE_OOXX, LINE_OXOX, LINE_OXXO, LINE_XOOX, LINE_XOXO, LINE_XXOO, LINE_XXOX, mvwputch(), point, print_colored_text(), and utf8_width().
Referenced by draw_recipe_tabs(), and draw_tabs().
draw_tabs() [1/2]
std::map<size_t, inclusive_rectangle<point> > draw_tabs (const catacurses::window & w, const std::vector< std::string > & tab_texts, const size_t current_tab, const size_t offset)
Definition at line 1562 of file output.cpp.
 {
     std::map<size_t, inclusive_rectangle<point>> tab_map;
     int width = getmaxx( w );
     for( int i = 1; i < width - 1; i++ ) {
         mvwputch( w, point( i, 2 ), BORDER_COLOR, LINE_OXOX );  //
     }
     mvwputch( w, point( 0, 2 ), BORDER_COLOR, LINE_OXXO );  //
     mvwputch( w, point( width - 1, 2 ), BORDER_COLOR, LINE_OOXX );  //
     const int tab_step = 3;
     int x = 2;
     for( size_t i = 0; i < tab_texts.size(); ++i ) {
         const std::string &tab_text = tab_texts[i];
         draw_tab( w, x, tab_text, i == current_tab );
         const int txt_width = utf8_width( tab_text, true );
         tab_map.emplace( i + offset, inclusive_rectangle<point>( point( x, 1 ), point( x + txt_width,
                          1 ) ) );
         x += txt_width + tab_step;
     }
     return tab_map;
 }
References BORDER_COLOR, draw_tab(), catacurses::getmaxx(), LINE_OOXX, LINE_OXOX, LINE_OXXO, mvwputch(), point, and utf8_width().
Referenced by faction_manager::display(), tab_manager::draw(), draw_bionics_tabs(), draw_medical_titlebar(), draw_recipe_tabs(), draw_tabs(), worldfactory::draw_worldgen_tabs(), and show_scores_ui().
draw_tabs() [2/2]
std::map<std::string, inclusive_rectangle<point> > draw_tabs (const catacurses::window & w, const std::vector< std::string > & tab_texts, const std::string & current_tab)
Definition at line 1590 of file output.cpp.
 {
     auto it = std::find( tab_texts.begin(), tab_texts.end(), current_tab );
     cata_assert( it != tab_texts.end() );
     std::map<size_t, inclusive_rectangle<point>> tab_map =
                 draw_tabs( w, tab_texts, it - tab_texts.begin() );
     std::map<std::string, inclusive_rectangle<point>> ret_map;
     for( size_t i = 0; i < tab_texts.size(); i++ ) {
         if( tab_map.count( i ) > 0 ) {
             ret_map.emplace( tab_texts[i], tab_map[i] );
         }
     }
     return ret_map;
 }
References cata_assert, and draw_tabs().
find_best_fit_in_size()
best_fit find_best_fit_in_size (const std::vector< int > & size_of_items_to_fit, const int & selected, const int & allowed_size, const int & spacer_size = 0, const int & continuation_marker_size = 0)
Algorith for finding the largest subset of varied-length items that fit in allowed_size.
Parameters
size_of_items_to_fit how much space the entries take up. In a vertical list, height. In a horizontal list, width.
selected the index of the currently selected item. This index will be included in the 'best-fitting' subset
allowed_size the total height/width in which the entries need to fit
spacer_size the size, if any, of the spacers between entries. In a tabbed list, tab_step or equivalent.
continuation_marker_size If a continuation marker will be added to the beginning or end (e.g. "<" or ">" in a horizontal list, the length of that marker.
Returns
best_fit.start: start index in size_of_items_to_fit for the 'best-fitting' subset
best_fit.length: number of entries in size_of_items_to_fit in the 'best-fitting' subset
Definition at line 1606 of file output.cpp.
 {
     int best_fit_length = 0;
     best_fit returnVal;
     returnVal.start = 0;
     returnVal.length = 0;
     int adjusted_allowed_size = allowed_size;
     for( int num_fitting = static_cast<int>( size_of_items_to_fit.size() ); num_fitting > 0;
          --num_fitting ) {
         //Iterate through all possible places the list can start
         for( int start_index = 0;
              start_index <= static_cast<int>( size_of_items_to_fit.size() ) - num_fitting; ++start_index ) {
             int space_required = 0;
             int cont_marker_allowance = 0;
             bool selected_response_included = false;
             for( int i = start_index; i < ( num_fitting + start_index ); ++i ) {
                 space_required += size_of_items_to_fit[i] + spacer_size;
                 if( i == selected ) {
                     selected_response_included = true;
                 }
             }
             //Check if this selection fits, accounting for an indicator that the list continues at the front if necessary
             if( start_index != 0 &&
                 start_index + num_fitting != static_cast<int>( size_of_items_to_fit.size() ) ) {
                 cont_marker_allowance = spacer_size + continuation_marker_size;
             }
             if( space_required < ( adjusted_allowed_size - cont_marker_allowance ) &&
                 selected_response_included ) {
                 if( space_required > best_fit_length ) {
                     returnVal.start = start_index;
                     returnVal.length = num_fitting;
                     best_fit_length = space_required;
                 }
             }
         }
         //If a fitting option has been found, don't move to fewer entries in the list
         if( best_fit_length > 0 ) {
             break;
             //If not everything fits, need at least one continuation indicator
         } else if( num_fitting == static_cast<int>( size_of_items_to_fit.size() ) ) {
             adjusted_allowed_size -= spacer_size + continuation_marker_size;
         }
     }
     return returnVal;
 }
References best_fit::length, and best_fit::start.
Referenced by fit_tabs_to_width().
fit_tabs_to_width()
std::pair<std::vector<std::string>, size_t> fit_tabs_to_width (size_t max_width, int current_tab, const std::vector< std::string > & original_tab_list)
Produces the largest subset of a list of tabs (for draw_tabs or draw_subtab) that can be displayed within max_width.
Set up for display of crafting recipe categories and subcategories. Provided with a list of tabs and the translated names, checks to see if they fit within max_width. If they don't, finds the largest sequential collection of tabs that fit within max_width and contain current_tab. Since the function is already handling translated tab names, the translated strings can be returned instead of the generic identifiers.
Parameters
max_width The maximum width available for display of the tabs. Currently assumes that this value includes a border.
current_tab The index of the currently selected tab
original_tab_list a list of the translated tab names to display
Returns
Return 1: A vector of tab identifiers or names that will fit within max_width and contain current_tab.
Return 2: The offset of the displayed tabs to be passed into draw_tabs
Definition at line 1653 of file output.cpp.
 {
     const int tab_step = 3; // Step between tabs, two for tab border
     size_t available_width = max_width - 1;
     std::pair<std::vector<std::string>, size_t> tab_list_and_offset;
     std::vector<int> tab_width;
     tab_width.reserve( original_tab_list.size() );
     for( const std::string &tab : original_tab_list ) {
         tab_width.emplace_back( utf8_width( tab, true ) );
     }
     best_fit tabs_to_print = find_best_fit_in_size( tab_width, current_tab,
                              available_width, tab_step, 1 );
     //Assemble list to return
     if( tabs_to_print.start != 0 ) { //Signify that the list continues left
         tab_list_and_offset.first.emplace_back( "<" );
     }
     for( int i = tabs_to_print.start; i < static_cast<int>( original_tab_list.size() ); ++i ) {
         if( i < tabs_to_print.start + tabs_to_print.length ) {
             tab_list_and_offset.first.emplace_back( original_tab_list[i] );
         }
     }
     if( tabs_to_print.start + tabs_to_print.length != static_cast<int>( original_tab_list.size() ) ) {
         //Signify that the list continues right
         tab_list_and_offset.first.emplace_back( ">" );
     }
     //Mark down offset
     if( tabs_to_print.start > 0 ) {
         tab_list_and_offset.second = tabs_to_print.start - 1;
     } else {
         tab_list_and_offset.second = tabs_to_print.start;
     }
     return tab_list_and_offset;
 }
References find_best_fit_in_size(), best_fit::length, best_fit::start, keycode::tab, and utf8_width().
Referenced by tab_manager::draw(), draw_recipe_subtabs(), and draw_recipe_tabs().
fold_and_print()
int fold_and_print (const catacurses::window & w, const point & begin, int width, const nc_color & base_color, const std::string & text, char split = ' ')
Fold and print text in the given window.
The function handles color_tags and uses them while printing.
Parameters
w Window we are printing in
begin The (row, column) index on which to start.
width The width used to fold the text (see foldstring). width + begin_y should be less than the window width, otherwise the lines will be wrapped by the curses system, which defeats the purpose of using foldstring.
base_color The initially used color. This can be overridden using color tags.
text Actual message to print
split Character after string is folded
Returns
The number of lines of the formatted text (after folding). This may be larger than the height of the window.
Definition at line 379 of file output.cpp.
 {
     nc_color color = base_color;
     std::vector<std::string> textformatted = foldstring( text, width, split );
     for( int line_num = 0; static_cast<size_t>( line_num ) < textformatted.size(); line_num++ ) {
         print_colored_text( w, begin + point( 0, line_num ), color, base_color,
                             textformatted[line_num] );
     }
     return textformatted.size();
 }
References color(), foldstring(), print_colored_text(), and mattack::split().
Referenced by check_encoding(), debug_error_prompt(), avatar::disp_medical(), faction_manager::display(), veh_interact::display_details(), veh_interact::display_stats(), draw_bionics_titlebar(), draw_center_win(), draw_description(), prof_window::draw_details(), prof_window::draw_header(), inventory_selector::draw_header(), draw_item_filter_rules(), help::draw_menu(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), worldfactory::draw_modselection_borders(), overmap_ui::draw_om_sidebar(), draw_spellbook_info(), draw_stats_info(), ensure_term_size(), mtype::faction_display(), faction::faction_display(), npc::faction_display(), fold_and_print(), target_ui::panel_spell_info(), worldfactory::pick_world(), avatar::power_bionics(), game::print_all_tile_info(), medical_column::print_column(), game::print_fields_info(), game::print_graffiti_info(), npc::print_info(), avatar::print_info(), monster::print_info(), game::print_part_con_info(), print_ranged_chance(), game::print_terrain_info(), construction::print_time(), vehicle::print_vparts_descs(), smart_controller_ui::refresh(), pocket_favorite_callback::refresh(), wish_item_callback::refresh(), overmap_ui::search(), select_crafter_and_crafting_recipe(), set_description(), set_points(), set_skills(), set_stats(), set_traits(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), robot_finds_kitten::show(), options_manager::show(), safemode::show(), uilist::show(), diary::show_diary_ui(), show_mutations_titlebar(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), outfit::sort_armor(), and lightson_game::start_game().
fold_and_print_from()
int fold_and_print_from (const catacurses::window & w, const point & begin, int width, int begin_line, const nc_color & base_color, const std::string & text)
Like fold_and_print, but starts the output with the N-th line of the folded string.
This can be used for scrolling large texts. Parameters have the same meaning as for fold_and_print, the function therefore handles color_tags correctly.
Parameters
w Window we are printing in
begin The (row,column) index on which to start.
width The width used to fold the text (see foldstring). width + begin_y should be
begin_line The index of the first line (of the folded string) that is to be printed. The function basically removes all lines before this one and prints the remaining lines with fold_and_print.
base_color The initially used color. This can be overridden using color tags.
text Actual message to print
Returns
Same as fold_and_print: the number of lines of the text (after folding). This is always the same value, regardless of begin_line, it can be used to determine the maximal value for begin_line.
Definition at line 391 of file output.cpp.
 {
     const int iWinHeight = getmaxy( w );
     std::stack<nc_color> color_stack;
     std::vector<std::string> textformatted = foldstring( text, width );
     for( int line_num = 0; static_cast<size_t>( line_num ) < textformatted.size(); line_num++ ) {
         if( line_num + begin.y - begin_line == iWinHeight ) {
             break;
         }
         if( line_num >= begin_line ) {
             wmove( w, begin + point( 0, -begin_line + line_num ) );
         }
         // split into colorable sections
         std::vector<std::string> color_segments = split_by_color( textformatted[line_num] );
         // for each section, get the color, and print it
         std::vector<std::string>::iterator it;
         for( it = color_segments.begin(); it != color_segments.end(); ++it ) {
             color_tag_parse_result::tag_type type = color_tag_parse_result::non_color_tag;
             if( !it->empty() && it->at( 0 ) == '<' ) {
                 type = update_color_stack( color_stack, *it );
             }
             if( line_num >= begin_line ) {
                 std::string l = *it;
                 if( type != color_tag_parse_result::non_color_tag ) {
                     l = rm_prefix( l );
                 }
                 if( l != "--" ) { // -- is a separation line!
                     nc_color color = color_stack.empty() ? base_color : color_stack.top();
                     wprintz( w, color, l );
                 } else {
                     for( int i = 0; i < width; i++ ) {
                         wputch( w, c_dark_gray, LINE_OXOX );
                     }
                 }
             }
         }
     }
     return textformatted.size();
 }
References c_dark_gray, color(), foldstring(), catacurses::getmaxy(), LINE_OXOX, color_tag_parse_result::non_color_tag, rm_prefix(), split_by_color(), update_color_stack(), catacurses::wmove(), wprintz(), wputch(), and point::y.
Referenced by main_menu::display_text(), game::extended_description(), fold_and_print_from(), insert_table(), ma_style_callback::key(), main_menu::print_menu(), and print_ranged_chance().
foldstring()
std::vector<std::string> foldstring (const std::string & str, int width, char split = ' ')
Split the input text into separate lines and wrap long lines.
Each resulting line is at most width console cells long. The functions handles color_tags. Color tags are added to the resulting lines so each line can be independently printed.
Returns
A vector of lines, it may contain empty strings. Each entry is at most width console cells width.
Definition at line 123 of file output.cpp.
 {
     std::vector<std::string> lines;
     if( width < 1 ) {
         lines.push_back( str );
         return lines;
     }
     std::stringstream sstr( str );
     std::string strline;
     std::vector<std::string> tags;
     while( std::getline( sstr, strline, '\n' ) ) {
         if( strline.empty() ) {
             // Special case empty lines as std::getline() sets failbit immediately
             // if the line is empty.
             lines.emplace_back();
         } else {
             std::string wrapped = word_rewrap( strline, width, split );
             std::stringstream swrapped( wrapped );
             std::string wline;
             while( std::getline( swrapped, wline, '\n' ) ) {
                 // Ensure that each line is independently color-tagged
                 // Re-add tags closed in the previous line
                 const std::string rawwline = wline;
                 if( !tags.empty() ) {
                     std::string swline;
                     for( const std::string &tag : tags ) {
                         swline += tag;
                     }
                     swline += wline;
                     wline = swline;
                 }
                 // Process the additional tags in the current line
                 const std::vector<size_t> tags_pos = get_tag_positions( rawwline );
                 for( const size_t tag_pos : tags_pos ) {
                     if( tag_pos + 1 < rawwline.size() && rawwline[tag_pos + 1] == '/' ) {
                         if( !tags.empty() ) {
                             tags.pop_back();
                         }
                     } else {
                         size_t tag_end = rawwline.find( '>', tag_pos );
                         if( tag_end != std::string::npos ) {
                             tags.emplace_back( rawwline.substr( tag_pos, tag_end + 1 - tag_pos ) );
                         }
                     }
                 }
                 // Close any unclosed tags
                 if( !tags.empty() ) {
                     std::string swline;
                     swline += wline;
                     for( auto it = tags.rbegin(); it != tags.rend(); ++it ) {
                         // currently the only closing tag is </color>
                         swline += "</color>";
                     }
                     wline = swline;
                 }
                 // The resulting line can be printed independently and have the correct color
                 lines.emplace_back( wline );
             }
         }
     }
     return lines;
 }
References get_tag_positions(), mattack::split(), anonymous_namespace{item_tname.cpp}::tags(), and word_rewrap().
Referenced by add_folded_name_and_value(), uilist::calc_data(), veh_interact::calc_lift_requirements(), anonymous_namespace{armor_layers.cpp}::clothing_flags_description(), construction_menu(), veh_interact::create_or_get_ui_adaptor(), string_input_popup::create_window(), avatar::disp_medical(), talk_function::display_and_choose_opts(), Messages::display_messages(), main_menu::display_text(), cataimgui::window::draw_colored_text(), prof_window::draw_details(), draw_item_info(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), draw_x_info(), diary::export_to_txt(), mtype::faction_display(), Messages::dialog::filter_help_text(), find_minimum_fold_width(), fold_and_print(), fold_and_print_from(), multiline_list::fold_entries(), vpart_info::format_description(), requirement_data::get_folded_list(), construction::get_folded_time_string(), Messages::dialog::init(), main_menu::init_strings(), ma_style_callback::key(), query_popup_impl::on_resized(), avatar::power_mutations(), game::print_furniture_info(), computer_session::print_indented_line(), npc::print_info(), monster::print_info(), main_menu::print_menu_items(), print_scrollable(), game::print_terrain_info(), iuse::radio_tick(), recipe_info(), smart_controller_ui::refresh(), wish_mutate_callback::refresh(), wish_item_callback::refresh(), scrollable_text(), select_crafter_and_crafting_recipe(), selection_line::selection_line(), set_description(), set_points(), set_skills(), set_stats(), scrolling_text_view::set_text(), robot_finds_kitten::show(), spellcasting_callback::spell_info_text(), anonymous_namespace{diary_ui.cpp}::text_to_list_scrollable(), and editmap::update_view_with_help().
format_item_info()
std::string format_item_info (const std::vector< iteminfo > & vItemDisplay, const std::vector< iteminfo > & vItemCompare)
Definition at line 1110 of file output.cpp.
 {
     std::string buffer;
     bool bIsNewLine = true;
     for( const iteminfo &i : vItemDisplay ) {
         if( i.sType == "DESCRIPTION" ) {
             // Always start a new line for sType == "DESCRIPTION"
             if( !bIsNewLine ) {
                 buffer += "\n";
             }
             if( i.bDrawName ) {
                 buffer += i.sName;
             }
         } else {
             if( i.bDrawName ) {
                 buffer += i.sName;
             }
             std::string sFmt = i.sFmt;
             std::string sPost;
             //A bit tricky, find %d and split the string
             size_t pos = sFmt.find( "<num>" );
             if( pos != std::string::npos ) {
                 buffer += sFmt.substr( 0, pos );
                 sPost = sFmt.substr( pos + 5 );
             } else {
                 buffer += sFmt;
             }
             if( i.sValue != "-999" ) {
                 nc_color thisColor = c_yellow;
                 for( const iteminfo &k : vItemCompare ) {
                     if( k.sValue != "-999" ) {
                         if( i.sName == k.sName && i.sType == k.sType ) {
                             double iVal = i.dValue;
                             double kVal = k.dValue;
                             if( i.sFmt != k.sFmt ) {
                                 // Different units, compare unit adjusted vals
                                 iVal = i.dUnitAdjustedVal;
                                 kVal = k.dUnitAdjustedVal;
                             }
                             if( iVal > kVal - .01 &&
                                 iVal < kVal + .01 ) {
                                 thisColor = c_light_gray;
                             } else if( iVal > kVal ) {
                                 if( i.bLowerIsBetter ) {
                                     thisColor = c_light_red;
                                 } else {
                                     thisColor = c_light_green;
                                 }
                             } else if( iVal < kVal ) {
                                 if( i.bLowerIsBetter ) {
                                     thisColor = c_light_green;
                                 } else {
                                     thisColor = c_light_red;
                                 }
                             }
                             break;
                         }
                     }
                 }
                 buffer += colorize( i.sValue, thisColor );
             }
             buffer += sPost;
         }
         // Set bIsNewLine in case the next line should always start in a new line
         if( ( bIsNewLine = i.bNewLine ) ) {
             buffer += "\n";
         }
     }
     return buffer;
 }
References c_light_gray, c_light_green, c_light_red, c_yellow, colorize(), and math_opers::pos().
Referenced by draw_item_info(), furniture_qualities_string(), item::info(), game::print_furniture_info(), and pocket_favorite_callback::refresh().
format_volume() [1/2]
std::string format_volume (const units::volume & volume)
Convert and format volume.
Definition at line 3231 of file output.cpp.
 {
     return format_volume( volume, 0, nullptr, nullptr );
 }
Referenced by iexamine::arcfurnace_empty(), game_menus::inv::container_for(), veh_interact::display_details(), veh_interact::display_stats(), inventory_selector::get_holster_stat(), inventory_selector::get_volume_stat(), talker_npc::give_item_to(), iexamine::kiln_empty(), mill_activate(), advanced_inventory::print_items(), vehicle::print_part_list(), iexamine::quern_examine(), game_menus::inv::smoke_food(), smoker_activate(), and iexamine::smoker_options().
format_volume() [2/2]
std::string format_volume (const units::volume & volume, int width, bool * out_truncated, double * out_value)
Convert, clamp and format volume, taking into account the specified width (0 for unlimited space), optionally returning a flag that indicate if the value was truncated to fit the width, optionally returning the formatted value as double.
Definition at line 3242 of file output.cpp.
 {
     // convert and get the units preferred scale
     int scale = 0;
     double value = convert_volume( volume.value(), &scale );
     // clamp to the specified width
     if( width != 0 ) {
         value = clamp_to_width( value, std::abs( width ), scale, out_truncated );
     }
     if( out_value != nullptr ) {
         *out_value = value;
     }
     // format
     if( width < 0 ) {
         // left-justify the specified width
         return string_format( "%-*.*f", std::abs( width ), scale, value );
     } else if( width > 0 ) {
         // right-justify the specified width
         return string_format( "%*.*f", width, scale, value );
     } else {
         // no width
         return string_format( "%.*f", scale, value );
     }
 }
References abs(), clamp_to_width(), convert_volume(), and string_format().
formatted_hotkey()
std::string formatted_hotkey (const std::string & hotkey, nc_color text_color)
Returns
A formatted string including the hotkey, color-tagged to stand out, and standardized surrounding text to highlight that this is a hotkey to anyone using a screen reader
Parameters
hotkey The hotkey to be formatted, without any color tags or other formatting
text_color The color of the surrounding text, so that only the hoteky stands out
Definition at line 2719 of file output.cpp.
 {
     return colorize( hotkey, ACTIVE_HOTKEY_COLOR ).append( colorize( ": ", text_color ) );
 }
References ACTIVE_HOTKEY_COLOR, and colorize().
Referenced by dialogue_window::draw(), and talk_data::get_entry().
get_bar()
std::pair<std::string, nc_color> get_bar (float cur, float max, int width = 5, bool extra_resolution = true, const std::vector< nc_color > & colors = { c_green, c_light_green, c_yellow, c_light_red, c_red })
Returns
Pair of a string containing the bar, and its color
Parameters
cur Current value being formatted
max Maximum possible value, e.g. a full bar
extra_resolution Double the resolution of displayed values with \ symbols.
colors A vector containing N colors with which to color the bar at different values
Definition at line 2624 of file output.cpp.
 {
     std::string result;
     const float status = clamp( cur / max, 0.0f, 1.0f );
     const float sw = status * width;
     nc_color col;
     if( !std::isfinite( status ) || colors.empty() ) {
         col = c_red_red;
     } else {
         int ind = std::floor( ( 1.0 - status ) * ( colors.size() - 1 ) + 0.5 );
         ind = clamp<int>( ind, 0, colors.size() - 1 );
         col = colors[ind];
     }
     if( !std::isfinite( sw ) || sw <= 0 ) {
         result.clear();
     } else {
         const int pipes = static_cast<int>( sw );
         if( pipes > 0 ) {
             result += std::string( pipes, '|' );
         }
         if( extra_resolution && sw - pipes >= 0.5 ) {
             result += "\\";
         } else if( pipes == 0 ) {
             result = ":";
         }
     }
     return std::make_pair( result, col );
 }
References c_red_red, clamp(), PATH_INFO::colors(), cata_path::empty(), floor(), max(), and status.
Referenced by get_hp_bar(), get_stamina_bar(), and satiety_bar().
get_hotkeys()
std::vector<std::string> get_hotkeys (const std::string_view s)
Definition at line 893 of file output.cpp.
 {
     std::vector<std::string> hotkeys;
     size_t start = s.find_first_of( '<' );
     size_t end = s.find_first_of( '>' );
     if( start != std::string::npos && end != std::string::npos ) {
         // hotkeys separated by '|' inside '<' and '>', for example "<e|E|?>"
         size_t lastsep = start;
         size_t sep = s.find_first_of( '|', start );
         while( sep < end ) {
             hotkeys.emplace_back( s.substr( lastsep + 1, sep - lastsep - 1 ) );
             lastsep = sep;
             sep = s.find_first_of( '|', sep + 1 );
         }
         hotkeys.emplace_back( s.substr( lastsep + 1, end - lastsep - 1 ) );
     }
     return hotkeys;
 }
References keycode::end.
Referenced by help::display_help(), and main_menu::init_strings().
get_hp_bar()
std::pair<std::string, nc_color> get_hp_bar (const int cur_hp, const int max_hp, const bool is_mon)
Definition at line 2657 of file output.cpp.
 {
     if( cur_hp == 0 ) {
         return std::make_pair( "-----", c_light_gray );
     }
     return get_bar( cur_hp, max_hp, 5, !is_mon );
 }
References c_light_gray, and get_bar().
Referenced by blood_magic(), Character::body_window(), Character::deal_damage(), draw_health_summary(), spell::energy_cost_string(), spell::energy_cur_string(), Character::extended_description(), monster::get_HP_Bar(), game::list_monsters(), player_hit_message(), bodygraph_display::prepare_infotext(), and npc::print_info().
get_labeled_bar() [1/3]
template<typename BarIterator > std::string get_labeled_bar (double val, int width, const std::string & label, BarIterator begin, BarIterator end) inline
Returns
String containing the bar. Example: "Label [****--... ]".
Parameters
val Value to display. Can be unclipped.
width Width of the entire string.
label Label before the bar. Can be empty.
begin Iterator over pairs <double p, char c> (see below).
end Iterator over pairs <double p, char c> (see below). Where: p - percentage of the entire bar which can be filled with c. c - character to fill the segment of the bar with
Definition at line 2733 of file output.cpp.
 {
     return get_labeled_bar<BarIterator>( val, width, label, begin, end, []( BarIterator it,
     int seg_width ) -> std::string {
         return std::string( seg_width, std::get<1>( *it ) );} );
 }
References keycode::end.
get_labeled_bar() [2/3]
template<typename BarIterator > std::string get_labeled_bar (double val, int width, const std::string & label, BarIterator begin, BarIterator end, std::function< std::string(BarIterator, int)> printer)
Returns
String containing the bar. Example: "Label [****--... ]".
Parameters
val Value to display. Can be unclipped.
width Width of the entire string.
label Label before the bar. Can be empty.
begin Iterator over collections with at least first two members [double p, char c] (see below).
end Iterator over collections with at least first two members [double p, char c] (see below). Where: p - percentage of the entire bar which can be filled with c. c - character to fill the segment of the bar with and the collection may have additional elements used by the following function parameter
printer Function that takes Iterator described above and number of copies of the character to repeat.
Definition at line 2749 of file output.cpp.
 {
     std::string result;
     result.reserve( width );
     if( !label.empty() ) {
         result += label;
         result += ' ';
     }
     const int bar_width = width - utf8_width( result ) - 2; // - 2 for the brackets
     result += '[';
     if( bar_width > 0 ) {
         int used_width = 0;
         for( BarIterator it( begin ); it != end; ++it ) {
             const double factor = std::min( 1.0, std::max( 0.0, std::get<0>( *it ) * val ) );
             const int seg_width = static_cast<int>( factor * bar_width ) - used_width;
             if( seg_width <= 0 ) {
                 continue;
             }
             used_width += seg_width;
             result += printer( it, seg_width );
         }
         result.insert( result.end(), bar_width - used_width, ' ' );
     }
     result += ']';
     return result;
 }
References keycode::end, anonymous_namespace{item_tname.cpp}::label(), max(), min(), and utf8_width().
get_labeled_bar() [3/3]
std::string get_labeled_bar (double val, int width, const std::string & label, char c)
Returns
String containing the bar. Example: "Label [************]".
Parameters
val Value to display. Can be unclipped.
width Width of the entire string.
label Label before the bar. Can be empty.
c Character to fill the bar with.
Definition at line 2724 of file output.cpp.
 {
     const std::array<std::pair<double, char>, 1> ratings =
     {{ std::make_pair( 1.0, c ) }};
     return get_labeled_bar( val, width, label, ratings.begin(), ratings.end() );
 }
References c.
Referenced by print_steadiness().
get_labeled_bar< RatingVector::iterator >()
template std::string get_labeled_bar< RatingVector::iterator > (const double val, const int width, const std::string & label, RatingVector::iterator begin, RatingVector::iterator end, std::function< std::string(RatingVector::iterator, int)> printer)
get_light_level()
std::pair<std::string, nc_color> get_light_level (const float light)
Definition at line 2674 of file output.cpp.
 {
     using pair_t = std::pair<std::string, nc_color>;
     static const std::array<pair_t, 6> strings {
         {
             pair_t {translate_marker( "unknown" ), c_pink},
             pair_t {translate_marker( "bright" ), c_yellow},
             pair_t {translate_marker( "cloudy" ), c_white},
             pair_t {translate_marker( "shady" ), c_light_gray},
             pair_t {translate_marker( "dark" ), c_dark_gray},
             pair_t {translate_marker( "very dark" ), c_black_white}
         }
     };
     // Avoid magic number
     static const int maximum_light_level = static_cast< int >( strings.size() ) - 1;
     const int light_level = clamp( static_cast< int >( std::ceil( light ) ), 0, maximum_light_level );
     const size_t array_index = static_cast< size_t >( light_level );
     return pair_t{ _( strings[array_index].first ), strings[array_index].second };
 }
References _, c_black_white, c_dark_gray, c_light_gray, c_pink, c_white, c_yellow, ceil(), clamp(), light, and translate_marker.
Referenced by game::print_terrain_info().
get_stamina_bar()
std::pair<std::string, nc_color> get_stamina_bar (int cur_stam, int max_stam)
Definition at line 2666 of file output.cpp.
 {
     if( cur_stam == 0 ) {
         return std::make_pair( "-----", c_light_gray );
     }
     return get_bar( cur_stam, max_stam, 5, true, { c_cyan, c_light_cyan, c_yellow, c_light_red, c_red } );
 }
References c_cyan, c_light_cyan, c_light_gray, c_light_red, c_red, c_yellow, and get_bar().
get_tag_positions()
std::vector<size_t> get_tag_positions (const std::string_view s)
Definition at line 1398 of file output.cpp.
 {
     std::vector<size_t> ret;
     size_t pos = s.find( "<color_", 0, 7 );
     while( pos != std::string::npos ) {
         ret.push_back( pos );
         pos = s.find( "<color_", pos + 1, 7 );
     }
     pos = s.find( "</color>", 0, 8 );
     while( pos != std::string::npos ) {
         ret.push_back( pos );
         pos = s.find( "</color>", pos + 1, 8 );
     }
     std::sort( ret.begin(), ret.end() );
     return ret;
 }
References math_opers::pos(), and cata::hash64_detail::ret.
Referenced by foldstring(), remove_color_tags(), split_by_color(), and word_rewrap().
get_terminal_height()
int get_terminal_height ()
Get the height in font glyphs of the drawing screen.
May differ from OPTIONS["TERMINAL_Y"], for instance in SDL FULLSCREEN mode, the user setting is overridden.
Definition at line 3278 of file output.cpp.
 {
     return get_option<int>( "TERMINAL_Y" );
 }
Referenced by game_ui::init_ui().
get_terminal_width()
int get_terminal_width ()
Get the width in font glyphs of the drawing screen.
May differ from OPTIONS["TERMINAL_X"], for instance in SDL FULLSCREEN mode, the user setting is overridden.
Definition at line 3272 of file output.cpp.
 {
     int width = get_option<int>( "TERMINAL_X" );
     return width < EVEN_MINIMUM_TERM_WIDTH ? EVEN_MINIMUM_TERM_WIDTH : width;
 }
References EVEN_MINIMUM_TERM_WIDTH.
Referenced by game_ui::init_ui().
healthy_bar()
std::string healthy_bar (const int healthy)
Definition at line 2866 of file output.cpp.
 {
     if( healthy > 3 ) {
         return "<good>+++</good>";
     } else if( healthy > 0 ) {
         return "<good>+</good>";
     } else if( healthy < -3 ) {
         return "<bad>!!!</bad>";
     } else if( healthy < 0 ) {
         return "<bad>-</bad>";
     } else {
         return "";
     }
 }
Referenced by comestible_inventory_preset::comestible_inventory_preset(), item::food_info(), and item::med_info().
insert_table()
void insert_table (const catacurses::window & w, int pad, int line, int columns, const nc_color & FG, const std::string & divider, bool r_align, const std::vector< std::string > & data)
Inserts a table into a window, with data right-aligned.
Parameters
pad Reduce table width by padding left side.
line Line to insert table.
columns Number of columns. Can be 1.
FG Default color of table text.
divider To insert a character separating table entries. Can be blank.
r_align true for right aligned, false for left aligned.
data Text data to fill. Make sure each entry of the data vector fits into one cell, including divider if any.
Definition at line 2793 of file output.cpp.
 {
     const int width = getmaxx( w );
     const int rows = getmaxy( w );
     const int col_width = ( width - pad ) / columns;
     int indent = 1;  // 1 for right window border
     if( r_align ) {
         indent = ( col_width * columns ) + 1;
     }
     int div = columns - 1;
     int offset = 0;
 #if defined(__ANDROID__)
     input_context ctxt( "INSERT_TABLE" );
 #endif
     wattron( w, FG );
     for( int i = 0; i < rows * columns; i++ ) {
         if( i + offset * columns >= static_cast<int>( data.size() ) ) {
             break;
         }
         int y = line + ( i / columns );
         if( r_align ) {
             indent -= col_width;
         }
         if( div != 0 ) {
             if( r_align ) {
                 right_print( w, y, indent - utf8_width( divider ), FG, divider );
             } else {
                 fold_and_print_from( w, point( indent + col_width - utf8_width( divider ), y ),
                                      utf8_width( divider ), 0, FG, divider );
             }
             div--;
         } else {
             div = columns - 1;
         }
         if( r_align ) {
             right_print( w, y, indent, c_white, data[i + offset * columns] );
             if( indent == 1 ) {
                 indent = ( col_width * columns ) + 1;
             }
         } else {
             fold_and_print_from( w, point( indent, y ), col_width, 0, c_white, data[i + offset * columns] );
             indent += col_width;
             if( indent == ( col_width * columns ) + 1 ) {
                 indent = 1;
             }
         }
     }
     wattroff( w, FG );
 }
References c_white, math_opers::div(), fold_and_print_from(), catacurses::getmaxx(), catacurses::getmaxy(), line(), right_print(), utf8_width(), catacurses::wattroff(), and catacurses::wattron().
Referenced by print_ranged_chance().
is_draw_tiles_mode()
bool is_draw_tiles_mode ()
Check whether we're in tile drawing mode.
The most important effect of this is that we don't need to draw to the ASCII window.
Ideally, of course, we'd have a unified tile drawing and ASCII drawing API and use polymorphy, but for the time being there will be a lot of switching around in the map drawing code.
Definition at line 3284 of file output.cpp.
 {
     return false;
 }
Referenced by map::draw(), Creature::draw(), game::draw_look_around_cursor(), and map::drawsq().
item_filter_rule_string()
std::string item_filter_rule_string (item_filter_type type)
Get the tips printed by draw_item_filter_rules as a string.
Parameters
type Filter to use when drawing
Definition at line 1058 of file output.cpp.
 {
     std::string description;
     const int tab_idx = static_cast<int>( type ) - static_cast<int>( item_filter_type::FIRST );
     description = item_filter_rule_intros[tab_idx] + "\n" + item_filter_help_1.translated();
     int max_example_length = 0;
     for( const auto &prefix : item_filter_prefixes ) {
         max_example_length = std::max( max_example_length, utf8_width( prefix.example.translated() ) );
     }
     std::string spaces( max_example_length, ' ' );
     {
         std::string example_name = _( "shirt" );
         int padding = max_example_length - utf8_width( example_name );
         description += string_format(
                            _( "  <color_white>%s</color>%.*s    %s\n" ),
                            example_name, padding, spaces,
                            _( "<color_cyan>name</color> of item" ) );
         std::string example_exclude = _( "rotten" );
         padding = max_example_length - utf8_width( example_exclude );
         description += string_format(
                            _( "  <color_yellow>-</color><color_white>%s</color>%.*s   %s\n" ),
                            example_exclude, padding, spaces,
                            _( "<color_cyan>names</color> to exclude" ) );
     }
     for( const auto &prefix : item_filter_prefixes ) {
         int padding = max_example_length - utf8_width( prefix.example.translated() );
         description += string_format(
                            _( "  <color_yellow>%c</color><color_white>:%s</color>%.*s  %s\n" ),
                            prefix.key, prefix.example, padding, spaces, prefix.description );
     }
     description += item_filter_help_2.translated();
     return description;
 }
References _, FIRST, item_filter_help_1, item_filter_help_2, item_filter_prefixes, item_filter_rule_intros, max(), prefix, string_format(), translation::translated(), type, and utf8_width().
Referenced by draw_item_filter_rules(), haul(), game::list_items(), and loot_options::query_loot().
lowercase_first_letter()
std::string lowercase_first_letter (const std::string & str)
Definition at line 2565 of file output.cpp.
 {
     std::wstring wstr = utf8_to_wstr( str );
     wstr[0] = towlower( wstr[0] );
     return wstr_to_utf8( wstr );
 }
References utf8_to_wstr(), and wstr_to_utf8().
Referenced by sew_advanced_actor::use().
msgtype_to_color()
nc_color msgtype_to_color (const game_message_type type, const bool bOldMsg)
Definition at line 3114 of file output.cpp.
 {
     static const std::map<game_message_type, std::pair<nc_color, nc_color>> colors {
         {m_good,     {c_light_green, c_green}},
         {m_bad,      {c_light_red,   c_red}},
         {m_mixed,    {c_pink,    c_magenta}},
         {m_warning,  {c_yellow,  c_brown}},
         {m_info,     {c_light_blue,  c_blue}},
         {m_neutral,  {c_white,   c_light_gray}},
         {m_debug,    {c_white,   c_light_gray}},
         {m_headshot, {c_pink,    c_magenta}},
         {m_critical, {c_yellow,  c_brown}},
         {m_grazing,  {c_light_blue,  c_blue}}
     };
     const auto it = colors.find( type );
     if( it == std::end( colors ) ) {
         return bOldMsg ? c_light_gray : c_white;
     }
     return bOldMsg ? it->second.second : it->second.first;
 }
References c_blue, c_brown, c_green, c_light_blue, c_light_gray, c_light_green, c_light_red, c_magenta, c_pink, c_red, c_white, c_yellow, PATH_INFO::colors(), keycode::end, m_bad, m_critical, m_debug, m_good, m_grazing, m_headshot, m_info, m_mixed, m_neutral, and m_warning.
Referenced by anonymous_namespace{animation.cpp}::draw_sct_curses(), Messages::dialog::filter_help_text(), anonymous_namespace{messages.cpp}::game_message::get_color(), and Messages::dialog::show().
mvwprintz()
void mvwprintz (const catacurses::window & w, const point & p, const nc_color & FG, const std::string & text)
Definition at line 3290 of file output.cpp.
 {
     wattron( w, FG );
     mvwprintw( w, p, text );
     wattroff( w, FG );
 }
References catacurses::mvwprintw(), catacurses::wattroff(), and catacurses::wattron().
Referenced by trade_ui::_draw_header(), game::bury_screen(), debug_menu::change_spells(), decorate_panel(), avatar::disp_medical(), game::disp_NPCs(), advanced_inventory::display(), faction_manager::display(), talk_function::display_and_choose_opts(), veh_interact::display_name(), veh_interact::display_stats(), veh_interact::display_veh(), scent_map::draw(), string_input_popup::draw(), char_creation::draw_age(), overmap_ui::draw_ascii(), game::draw_async_anim_curses(), game::draw_blink_curses(), char_creation::draw_blood(), overmap_ui::draw_camp_labels(), draw_center_win(), overmap_ui::draw_city_labels(), draw_connectors(), inventory_selector::draw_footer(), char_creation::draw_gender(), draw_grid(), draw_header(), char_creation::draw_height(), target_ui::draw_help_notice(), veh_app_interact::draw_info(), draw_item_filter_rules(), draw_left_win(), sokoban_game::draw_level(), char_creation::draw_location(), worldfactory::draw_mod_list(), char_creation::draw_name(), overmap_ui::draw_om_sidebar(), char_creation::draw_outfit(), game::draw_panels(), draw_points(), prof_window::draw_profs(), draw_recipe_subtabs(), draw_recipe_tabs(), draw_right_win(), anonymous_namespace{animation.cpp}::draw_sct_curses(), draw_skills_tab(), draw_speed_info(), draw_speed_tab(), draw_spellbook_info(), query_destination_callback::draw_squares(), draw_stats_tab(), draw_subtab(), draw_tip(), target_ui::draw_window_title(), anonymous_namespace{animation.cpp}::draw_zones_curses(), game::extended_description(), basecamp::faction_display(), faction::faction_display(), npc::faction_display(), anonymous_namespace{animation.cpp}::hit_animation(), basecamp::job_assignment_ui(), game::list_items(), game::list_monsters(), game::look_around(), mvwprintz(), target_ui::panel_gun_info(), target_ui::panel_spell_info(), worldfactory::pick_world(), overmap_ui::place_ter_or_special(), avatar::power_bionics(), avatar::power_mutations(), string_editor_window::print_editor(), Character::print_encumbrance(), game::print_fields_info(), vehicle::print_fuel_indicator(), vehicle::print_fuel_indicators(), game::print_furniture_info(), advanced_inventory::print_header(), dialogue_window::print_header(), npc::print_info(), monster::print_info(), advanced_inventory::print_items(), game::print_items_info(), vehicle::print_part_list(), snake_game::print_score(), sokoban_game::print_score(), vehicle::print_speed_gauge(), game::print_terrain_info(), game::print_trap_info(), game::print_vehicle_info(), game::print_visibility_info(), advanced_inventory::redraw_pane(), advanced_inventory::redraw_sidebar(), smart_controller_ui::refresh(), spellcasting_callback::refresh(), teleporter_callback::refresh(), wish_mutate_callback::refresh(), wish_monster_callback::refresh(), wish_item_callback::refresh(), advanced_inventory::refresh_minimap(), game::reset_item_list_state(), overmap_ui::search(), select_crafter_and_crafting_recipe(), set_description(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), Messages::dialog::show(), robot_finds_kitten::show(), options_manager::show(), safemode::show(), uilist::show(), color_manager::show_gui(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), snake_game::snake_over(), outfit::sort_armor(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), overmap_ui::update_note_preview(), editmap::update_view_with_help(), basecamp::worker_assignment_ui(), game::zones_manager(), and zones_manager_draw_borders().
mvwputch() [1/2]
void mvwputch (const catacurses::window & w, const point & p, nc_color FG, const std::string & ch)
Definition at line 597 of file output.cpp.
 {
     wattron( w, FG );
     mvwprintw( w, p, ch );
     wattroff( w, FG );
 }
References catacurses::mvwprintw(), catacurses::wattroff(), and catacurses::wattron().
mvwputch() [2/2]
void mvwputch (const catacurses::window & w, const point & p, nc_color FG, int ch)
Definition at line 590 of file output.cpp.
 {
     wattron( w, FG );
     mvwaddch( w, p, ch );
     wattroff( w, FG );
 }
References catacurses::mvwaddch(), catacurses::wattroff(), and catacurses::wattron().
Referenced by scrollbar::apply(), game::bury_screen(), exosuit_interact::create_or_get_ui_adaptor(), avatar::disp_medical(), faction_manager::display(), veh_interact::display_grid(), veh_interact::display_list(), veh_interact::display_veh(), tab_manager::draw(), Creature::draw(), inventory_column::draw(), scrolling_text_view::draw(), editmap_hilight::draw(), overmap_ui::draw_ascii(), draw_bionics_tabs(), draw_bionics_titlebar(), border_helper::draw_border(), draw_border_below_tabs(), prof_window::draw_borders(), draw_borders_external(), draw_borders_internal(), anonymous_namespace{animation.cpp}::draw_bullet_curses(), medical_column::draw_column(), draw_connectors(), game::draw_critter(), draw_custom_border(), draw_exam_window(), anonymous_namespace{animation.cpp}::draw_explosion_curses(), inventory_selector::draw_footer(), draw_footsteps(), draw_grid(), draw_header(), draw_hidden_amount(), bodygraph_display::draw_info(), draw_item_info(), lightson_game::draw_level(), sokoban_game::draw_level(), anonymous_namespace{animation.cpp}::draw_line_curses(), game::draw_look_around_cursor(), editmap::draw_main_ui_overlay(), draw_medical_titlebar(), advanced_inventory::draw_minimap(), game::draw_minimap(), worldfactory::draw_modselection_borders(), overmap_ui::draw_om_sidebar(), overmap_ui::draw_overmap_chunk(), game::draw_panels(), prof_window::draw_profs(), draw_recipe_subtabs(), draw_recipe_tabs(), draw_subtab(), draw_tab(), draw_tabs(), game::draw_ter(), draw_trail(), target_ui::draw_ui_window(), game::draw_veh_dir_indicator(), anonymous_namespace{animation.cpp}::draw_weather_curses(), game::extended_description(), basecamp::job_assignment_ui(), worldfactory::pick_world(), avatar::power_bionics(), avatar::power_mutations(), dialogue_window::print_header(), main_menu::print_menu(), app_uilist_handler::refresh(), spellcasting_callback::refresh(), spellbook_callback::refresh(), teleporter_callback::refresh(), game::reset_item_list_state(), select_crafter_and_crafting_recipe(), set_description(), set_hobbies(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), robot_finds_kitten::show(), options_manager::show(), safemode::show(), uilist::show(), color_manager::show_gui(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), snake_game::snake_over(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), editmap::uber_draw_ter(), overmap_ui::update_note_preview(), editmap::update_view_with_help(), basecamp::worker_assignment_ui(), and zones_manager_draw_borders().
mvwputch_hi() [1/2]
void mvwputch_hi (const catacurses::window & w, const point & p, nc_color FG, const std::string & ch)
Definition at line 629 of file output.cpp.
 {
     nc_color HC = hilite( FG );
     wattron( w, HC );
     mvwprintw( w, p, ch );
     wattroff( w, HC );
 }
References hilite(), catacurses::mvwprintw(), catacurses::wattroff(), and catacurses::wattron().
mvwputch_hi() [2/2]
void mvwputch_hi (const catacurses::window & w, const point & p, nc_color FG, int ch)
Definition at line 621 of file output.cpp.
 {
     nc_color HC = hilite( FG );
     wattron( w, HC );
     mvwaddch( w, p, ch );
     wattroff( w, HC );
 }
References hilite(), catacurses::mvwaddch(), catacurses::wattroff(), and catacurses::wattron().
Referenced by Creature::draw(), overmap_ui::draw_ascii(), game::draw_minimap(), and overmap_ui::draw_overmap_chunk().
mvwputch_inv() [1/2]
void mvwputch_inv (const catacurses::window & w, const point & p, nc_color FG, const std::string & ch)
Definition at line 612 of file output.cpp.
 {
     nc_color HC = invert_color( FG );
     wattron( w, HC );
     mvwprintw( w, p, ch );
     wattroff( w, HC );
 }
References invert_color(), catacurses::mvwprintw(), catacurses::wattroff(), and catacurses::wattron().
mvwputch_inv() [2/2]
void mvwputch_inv (const catacurses::window & w, const point & p, nc_color FG, int ch)
Definition at line 604 of file output.cpp.
 {
     nc_color HC = invert_color( FG );
     wattron( w, HC );
     mvwaddch( w, p, ch );
     wattroff( w, HC );
 }
References invert_color(), catacurses::mvwaddch(), catacurses::wattroff(), and catacurses::wattron().
Referenced by Creature::draw(), and game::draw_cursor().
popup()
int popup (const std::string & text, PopupFlags flags)
Definition at line 912 of file output.cpp.
 {
 #if defined(__ANDROID__)
     if( get_option<bool>( "ANDROID_NATIVE_UI" ) && flags == PF_NONE ) {
         JNIEnv *env = ( JNIEnv * )SDL_AndroidGetJNIEnv();
         jobject activity = ( jobject )SDL_AndroidGetActivity();
         jclass clazz( env->GetObjectClass( activity ) );
         jmethodID get_nativeui_method_id = env->GetMethodID( clazz, "getNativeUI",
                                            "()Lcom/cleverraven/cataclysmdda/NativeUI;" );
         jobject native_ui_obj = env->CallObjectMethod( activity, get_nativeui_method_id );
         jclass native_ui_cls( env->GetObjectClass( native_ui_obj ) );
         jmethodID queryYN_method_id = env->GetMethodID( native_ui_cls, "popup", "(Ljava/lang/String;)V" );
         jstring jstr = env->NewStringUTF( remove_color_tags( text ).c_str() );
         env->CallVoidMethod( native_ui_obj, queryYN_method_id, jstr );
         env->DeleteLocalRef( jstr );
         env->DeleteLocalRef( native_ui_cls );
         env->DeleteLocalRef( native_ui_obj );
         env->DeleteLocalRef( clazz );
         env->DeleteLocalRef( activity );
         return UNKNOWN_UNICODE;
     }
 #endif
     query_popup pop;
     pop.preferred_keyboard_mode( keyboard_mode::keychar );
     pop.message( "%s", text );
     if( flags & PF_GET_KEY ) {
         pop.allow_anykey( true );
     } else {
         pop.allow_cancel( true );
     }
     if( flags & PF_FULLSCREEN ) {
         pop.full_screen( true );
     } else if( flags & PF_ON_TOP ) {
         pop.on_top( true );
     }
     pop.context( "POPUP_WAIT" );
     const query_popup::result &res = pop.query();
     if( res.evt.type == input_event_t::keyboard_char ) {
         return res.evt.get_first_input();
     } else {
         return UNKNOWN_UNICODE;
     }
 }
References query_popup::allow_anykey(), query_popup::allow_cancel(), query_popup::context(), query_popup::result::evt, query_popup::full_screen(), input_event::get_first_input(), keyboard_char, keychar, query_popup::message(), query_popup::on_top(), PF_FULLSCREEN, PF_GET_KEY, PF_NONE, PF_ON_TOP, query_popup::preferred_keyboard_mode(), query_popup::query(), remove_color_tags(), input_event::type, and UNKNOWN_UNICODE.
Referenced by trade_ui::_confirm_trade(), achievement_attained(), zone_manager::add(), tutorial_game::add_message(), anonymous_namespace{main.cpp}::assure_essential_dirs_exist(), iexamine::autoclave_empty(), iexamine::autodoc(), autodoc_internal(), trade_ui::bank_balance(), bionic_remove_common(), talker_avatar::buy_monster(), melee_actor::call(), iuse::calories_intake_tracker(), iuse::camera(), Character::can_continue_craft(), Character::can_install_bionics(), Character::can_uninstall_bionic(), talk_function::caravan_depart(), talk_function::caravan_return(), talk_function::carpenter_return(), change_cleared_terrain(), debug_menu::change_spells(), debug_menu::character_edit_desc_menu(), debug_menu::character_edit_menu(), game::chat(), choose_direction(), choose_direction_rel_ms(), basecamp::choose_new_leader(), basecamp::combat_mission_return(), talk_function::companion_choose(), talk_function::companion_choose_return(), game_menus::inv::compare(), compare_recipe_with_item(), connection_direction_of(), construction_menu(), avatar::control_npc_menu(), Character::customize_appearance(), iexamine::cvdmachine(), debug_menu::debug(), debug_drop_list(), debug_menu::debug_menu_game_state(), advanced_inventory::display(), talk_function::display_and_choose_opts(), input_context::display_menu(), basecamp::distribute_food(), anonymous_namespace{iexamine.cpp}::atm_menu::do_deposit_money(), anonymous_namespace{iexamine.cpp}::atm_menu::do_exchange_cash(), veh_interact::do_main_loop(), anonymous_namespace{iexamine.cpp}::atm_menu::do_transfer_all_money(), anonymous_namespace{iexamine.cpp}::atm_menu::do_withdraw_money(), inventory_selector::drag_drop_item(), anonymous_namespace{animation.cpp}::basic_animation::draw(), debug_menu::draw_benchmark(), game_menus::inv::ebookread(), game_menus::inv::ebooksave(), edit_integer(), editmap::edit_itm(), edit_json(), iuse::einktabletpc(), iexamine::elevator(), past_games_info::ensure_loaded(), craft_command::execute(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_consume_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item(), talk_function::field_harvest(), talk_function::field_plant(), filter_entries(), game::find_or_make_stairs(), start_location::find_player_initial_location(), basecamp::finish_return(), iuse::fitness_check(), talk_function::forage_return(), debug_menu::game_report(), debug_menu::generate_effect_list(), basecamp::get_equipment(), basecamp::give_basecamp_equipment(), basecamp::give_equipment(), talk_function::give_equipment_allowance(), game_menus::inv::gunmod_to_remove(), iuse::handle_ground_graffiti(), basecamp::handle_hide_mission(), handle_player_display_action(), basecamp::handle_reveal_mission(), Character::has_enough_anesth(), Character::has_installation_requirement(), talk_function::hospital_raid_return(), debug_menu::import_folower(), talk_function::individual_mission(), exosuit_interact::insert_replace_activate_mod(), inv_internal(), inv_internal_multi(), game::item_action_menu(), inscribe_actor::item_inscription(), pocket_favorite_callback::key(), spellcasting_callback::key(), actmenu_cb::key(), wish_item_callback::key(), debug_menu::kill_area(), talk_function::labor_return(), iexamine::ledge(), main_menu::load_character_tab(), game::look_around(), Character::making_would_work(), trapfunc::map_regen(), editmap::mapgen_preview(), editmap::mapgen_veh_query(), iuse::measure_resonance(), advanced_inventory::move_all_items(), pocket_favorite_callback::move_item(), game_menus::inv::multidrop(), iuse::mycus(), iexamine::nanofab(), main_menu::new_character_tab(), anonymous_namespace{math_parser_diag.cpp}::num_input_eval(), om_target_tile(), on_customize_character(), main_menu::opening_screen(), orient_part(), monexamine::pay_bot(), iexamine::pay_gas(), game_menus::inv::pickup(), basecamp::place_results(), basecamp::player_eats_meal(), popup_player_or_npc(), popup_string(), avatar::power_bionics(), avatar::power_mutations(), tutorial_game::pre_action(), prompt_world_name(), iexamine::quern_examine(), query_int(), query_int_impl(), zone_manager::query_name(), basecamp::query_new_name(), game::quicksave(), iuse::radio_on(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::receive_item(), Character::recraft(), basecamp::recruit_return(), zone_data::refresh_display(), game::reload_tileset(), veh_app_interact::remove(), prof_window::run(), basecamp::salt_water_pipe_return(), basecamp::salt_water_pipe_swamp_return(), game::save(), mapbuffer::save(), game::save_cyborg(), game::save_maps(), talk_function::scavenging_patrol_return(), talk_function::scavenging_raid_return(), overmap_ui::search(), game_menus::inv::select_ammo(), base_camps::select_camp_option(), debug_menu::select_follower_to_export(), selection_ok(), debug_menu::set_automove(), set_description(), set_hobbies(), set_profession(), set_scenario(), basecamp::set_sort_points(), overmap_ui::set_special_args(), set_traits(), set_up_butchery(), game::setup(), options_manager::show(), show_photo_selection(), debug_menu::show_sound(), worldfactory::show_worldgen_tab_modselection(), iexamine::sign(), game_menus::inv::smoke_food(), iexamine::smoker_options(), outfit::sort_armor(), talk_function::start_camp(), basecamp::start_clearcut(), basecamp::start_combat_mission(), basecamp::start_crafting(), basecamp::start_cut_logs(), basecamp::start_fortifications(), game::start_game(), basecamp::start_menial_labor(), basecamp::start_mission(), basecamp::start_multi_mission(), basecamp::start_relay_hide_site(), basecamp::start_salt_water_pipe(), basecamp::start_setup_hide_site(), basecamp::start_upgrade(), basecamp::survey_field_return(), basecamp::survey_return(), survive_random_encounter(), zone_manager::swap(), game_menus::inv::swap_letters(), avatar_action::swim(), game::take_screenshot(), debug_menu::teleport_overmap(), safemode::test_pattern(), zone_data::toggle_display(), inventory_multiselector::toggle_entries(), Character::try_remove_grab(), game_menus::inv::unload(), basecamp::upgrade_return(), avatar::upgrade_stat_prompt(), weigh_self_actor::use(), worldfactory::valid_worldname(), debug_menu::vehicle_battery_charge(), debug_menu::vehicle_export(), iexamine::vending(), wait(), iuse::wash_items(), debug_menu::wishitem(), debug_menu::write_city_list(), debug_menu::write_global_vars(), anonymous_namespace{debug_menu.cpp}::write_min_archive(), write_to_file(), and game::zones_manager().
print_colored_text()
void print_colored_text (const catacurses::window & w, const point & p, nc_color & cur_color, const nc_color & base_color, std::string_view text, report_color_error color_error = report_color_error::yes)
Print text with embedded color_tags, x, y are in curses system.
The text is not word wrapped, but may automatically be wrapped on new line characters or when it reaches the border of the window (both is done by the curses system). If the text contains no color tags, it's equivalent to a simple mvprintz.
Parameters
w Window we are drawing in
p Curses-style coordinates to print text at.
text The text to print.
cur_color The current color (could have been set by a previously encountered color tag), change to a color according to the color tags that are in the text.
base_color Base color that is used outside of any color tag.
Definition at line 239 of file output.cpp.
 {
     if( p.y > -1 && p.x > -1 ) {
         wmove( w, p );
     }
     const auto color_segments = split_by_color( text );
     std::stack<nc_color> color_stack;
     color_stack.push( color );
     for( auto seg : color_segments ) {
         if( seg.empty() ) {
             continue;
         }
         if( seg[0] == '<' ) {
             const color_tag_parse_result::tag_type type = update_color_stack(
                         color_stack, seg, color_error );
             if( type != color_tag_parse_result::non_color_tag ) {
                 seg = rm_prefix( seg );
             }
         }
         color = color_stack.empty() ? base_color : color_stack.top();
         wprintz( w, color, seg );
     }
 }
References color(), color_tag_parse_result::non_color_tag, rm_prefix(), coords::seg, split_by_color(), update_color_stack(), catacurses::wmove(), wprintz(), point::x, and point::y.
Referenced by debug_menu::change_spells(), game_menus::inv::compare_items(), veh_interact::create_or_get_ui_adaptor(), talk_function::display_and_choose_opts(), Messages::display_messages(), veh_interact::display_mode(), inventory_column::draw(), scrolling_text_view::draw(), dialogue_window::draw(), overmap_ui::draw_ascii(), draw_bionics_tab(), target_ui::draw_controls_list(), draw_filter_and_sorting_indicators(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), draw_points(), draw_proficiencies_tab(), spellcasting_callback::draw_spell_info(), draw_spellbook_info(), draw_stats_info(), draw_tab(), fold_and_print(), target_ui::panel_cursor_info(), target_ui::panel_gun_info(), target_ui::panel_recoil(), target_ui::panel_spell_info(), target_ui::panel_turret_list(), print_confidence_rating_bar(), print_confidence_ratings(), multiline_list::print_line(), main_menu::print_menu(), print_ranged_chance(), print_scrollable(), computer_session::refresh(), scrollable_text(), select_crafter_and_crafting_recipe(), set_skills(), set_stats(), shortcut_print(), Messages::dialog::show(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), trim_and_print(), overmap_ui::update_note_preview(), and editmap::update_view_with_help().
print_scrollable()
int print_scrollable (const catacurses::window & w, int begin_line, const std::string & text, const nc_color & base_color, const std::string & scroll_msg)
Print word wrapped text (with color_tags) into the window.
Parameters
w Window we are printing in
begin_line Line in the word wrapped text that is printed first (lines before that are not printed at all).
text Text to print
base_color Color used outside of any color tags.
scroll_msg Optional, can be empty. If not empty and the text does not fit the window, the string is printed on the last line (in light green), it should show how to scroll the text.
Returns
The maximal scrollable offset ([number of lines to be printed] - [lines available in the window]). This allows the caller to restrict the begin_line number on future calls / when modified by the user.
Definition at line 351 of file output.cpp.
 {
     const size_t wwidth = getmaxx( w );
     const auto text_lines = foldstring( text, wwidth );
     size_t wheight = getmaxy( w );
     const bool print_scroll_msg = text_lines.size() > wheight;
     if( print_scroll_msg && !scroll_msg.empty() ) {
         // keep the last line free for a message to the player
         wheight--;
     }
     if( begin_line < 0 || text_lines.size() <= wheight ) {
         begin_line = 0;
     } else if( begin_line + wheight >= text_lines.size() ) {
         begin_line = text_lines.size() - wheight;
     }
     nc_color color = base_color;
     for( size_t i = 0; i + begin_line < text_lines.size() && i < wheight; ++i ) {
         print_colored_text( w, point( 0, i ), color, base_color, text_lines[i + begin_line] );
     }
     if( print_scroll_msg && !scroll_msg.empty() ) {
         color = c_white;
         print_colored_text( w, point( 0, wheight ), color, color, scroll_msg );
     }
     return std::max<int>( 0, text_lines.size() - wheight );
 }
References c_white, color(), foldstring(), catacurses::getmaxx(), catacurses::getmaxy(), and print_colored_text().
query_int()
bool query_int (int & result, const std::string & text)
Definition at line 880 of file output.cpp.
 {
     string_input_popup popup;
     popup.title( text );
     popup.text( "" ).only_digits( true );
     int temp = popup.query_int();
     if( popup.canceled() ) {
         return false;
     }
     result = temp;
     return true;
 }
References popup(), and temp.
Referenced by debug_menu::bleed_self(), iuse::c4(), debug_menu::change_spells(), debug_menu::character_edit_hp_menu(), debug_menu::character_edit_menu(), debug_menu::character_edit_needs_menu(), debug_menu::character_edit_opinion_menu(), debug_menu::character_edit_personality_menu(), debug_menu::character_edit_stats_menu(), debug_menu::damage_self(), debug_menu::debug(), game::display_scent(), debug_menu::faction_edit_larder_menu(), debug_menu::faction_edit_menu(), debug_menu::faction_edit_opinion_menu(), debug_menu::gen_sound(), iuse::mininuke(), query_int(), workout_activity_actor::query_keep_training(), unload_options::query_unload(), debug_menu::spawn_artifact(), workout_activity_actor::start(), debug_menu::wishbionics(), and debug_menu::wisheffect().
query_yn()
bool query_yn (const std::string & text)
Definition at line 811 of file output.cpp.
 {
 #if defined(__ANDROID__)
     if( get_option<bool>( "ANDROID_NATIVE_UI" ) ) {
         JNIEnv *env = ( JNIEnv * )SDL_AndroidGetJNIEnv();
         jobject activity = ( jobject )SDL_AndroidGetActivity();
         jclass clazz( env->GetObjectClass( activity ) );
         jmethodID get_nativeui_method_id = env->GetMethodID( clazz, "getNativeUI",
                                            "()Lcom/cleverraven/cataclysmdda/NativeUI;" );
         jobject native_ui_obj = env->CallObjectMethod( activity, get_nativeui_method_id );
         jclass native_ui_cls( env->GetObjectClass( native_ui_obj ) );
         jmethodID queryYN_method_id = env->GetMethodID( native_ui_cls, "queryYN", "(Ljava/lang/String;)Z" );
         jstring jstr = env->NewStringUTF( text.c_str() );
         bool result = env->CallBooleanMethod( native_ui_obj, queryYN_method_id, jstr );
         env->DeleteLocalRef( jstr );
         env->DeleteLocalRef( native_ui_cls );
         env->DeleteLocalRef( native_ui_obj );
         env->DeleteLocalRef( clazz );
         env->DeleteLocalRef( activity );
         return result;
     }
 #endif // defined(__ANDROID__)
     const bool force_uc = get_option<bool>( "FORCE_CAPITAL_YN" );
     const auto &allow_key = force_uc ? input_context::disallow_lower_case_or_non_modified_letters
                             : input_context::allow_all_keys;
     return query_popup()
            .preferred_keyboard_mode( keyboard_mode::keycode )
            .context( "YESNO" )
            .message( force_uc && !is_keycode_mode_supported() ?
                      pgettext( "query_yn", "%s (Case Sensitive)" ) :
                      pgettext( "query_yn", "%s" ), text )
            .option( "YES", allow_key )
            .option( "NO", allow_key )
            .cursor( 1 )
            .default_color( c_light_red )
            .query()
            .action == "YES";
 }
References query_popup::result::action, input_context::allow_all_keys(), c_light_red, query_popup::context(), query_popup::cursor(), query_popup::default_color(), input_context::disallow_lower_case_or_non_modified_letters(), is_keycode_mode_supported(), keycode, query_popup::message(), query_popup::option(), pgettext, query_popup::preferred_keyboard_mode(), and query_popup::query().
Referenced by trade_ui::_confirm_trade(), computer_session::action_extract_rad_source(), computer_session::action_miss_disarm(), computer_session::action_miss_launch(), advanced_inventory::action_move_item(), input_context::action_remove(), effect_on_condition::activate(), zone_manager::add(), auto_pickup::player_settings::add_rule(), safemode::add_rule(), iexamine::aggie_plant(), iexamine::arcfurnace_empty(), iexamine::attunement_altar(), iexamine::autoclave_empty(), iexamine::bars(), iuse::binder_manage_recipe(), iuse::blood_draw(), game::butcher(), appliance_convert_examine_actor::call(), cardreader_examine_actor::call(), iuse::camera(), game::cancel_activity_query(), cancel_auto_move(), iexamine::cardreader_foodplace(), iexamine::cardreader_robofac(), iexamine::chainfence(), debug_menu::character_edit_menu(), debug_menu::character_edit_needs_menu(), check_water_affect_items(), iexamine::choose_fertilizer(), choose_ma_style(), basecamp::choose_new_leader(), game::climb_down_using(), basecamp::common_salt_water_pipe_construction(), iexamine::compost_empty(), iexamine::compost_full(), target_ui::confirm_non_enemy_target(), craft_command::continue_prompt_liquids(), iexamine::controls_gate(), overmap_ui::create_note(), diary::death_entry(), debug_menu::debug(), game::disable_robot(), vehicle::disable_smart_controller_if_needed(), overmap_ui::display(), input_context::display_menu(), anonymous_namespace{iexamine.cpp}::atm_menu::do_exchange_cash(), veh_interact::do_install(), anonymous_namespace{iexamine.cpp}::atm_menu::do_purchase_card(), game::do_regular_action(), veh_interact::do_remove(), veh_interact::do_repair(), do_turn(), craft_activity_actor::do_turn(), construct::done_digormine_stair(), trap::examine(), inventory_drop_selector::execute(), craft_command::execute(), anonymous_namespace{main.cpp}::exit_handler(), conditional_fun::anonymous_namespace{condition.cpp}::f_query(), talk_function::field_harvest(), talk_function::field_plant(), advanced_inventory::fill_lists_with_pane_items(), game::find_or_make_stairs(), iexamine::fireplace(), iexamine::flower_cactus(), iexamine::flower_dahlia(), iexamine::flower_marloss(), iexamine::flower_poppy(), iexamine::fswitch(), mattack::fungus_fortify(), iexamine::fvat_empty(), iexamine::fvat_full(), iexamine::gaspump(), talker_npc::give_item_to(), grab(), iexamine::gunsafe_el(), hackveh(), tab_manager::handle_input(), iuse::heat_food(), game::is_game_over(), iexamine::keg(), overmap_ui::map_notes_callback::key(), iexamine::kiln_empty(), known_magic::learn_spell(), iexamine::ledge(), link_up_actor::link_extend_cable(), iuse::marloss_seed(), monexamine::mech_hack(), monexamine::mfriend_menu(), avatar_action::move(), advanced_inventory::move_all_items(), iuse::multicooker(), iexamine::nanofab(), main_menu::new_character_tab(), game::npc_menu(), om_target_tile(), main_menu::opening_screen(), dialogue::opt(), iexamine::part_con(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), monexamine::pet_menu(), iuse::petfood(), pick_plant(), iexamine::pit(), iexamine::pit_covered(), iuse::play_game(), iexamine::portable_structure(), firestarter_actor::prep_firestarter_use(), game::prompt_dangerous_tile(), target_ui::prompt_friendlies_in_lof(), craft_command::query_continue(), query_for_item(), ignorable_options::query_ignorable(), query_pick(), unload_options::query_unload(), query_yn(), avatar::query_yn(), veh_app_interact::remove(), input_context::resolve_conflicts(), iexamine::rubble(), iexamine::safe(), game::save_cyborg(), iuse::seed(), spell::select_target(), set_description(), set_up_butchery(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), options_manager::show(), safemode::show(), diary::show_diary_ui(), color_manager::show_gui(), worldfactory::show_worldgen_advanced(), worldfactory::show_worldgen_basic(), iexamine::shrub_wildveggies(), iexamine::sign(), smash(), smoker_activate(), outfit::sort_armor(), debug_menu::spawn_artifact(), advanced_inventory::start_activity(), basecamp::start_clearcut(), basecamp::start_combat_mission(), basecamp::start_cut_logs(), basecamp::start_fortifications(), game::start_game(), basecamp::start_relay_hide_site(), basecamp::start_setup_hide_site(), iexamine::stook_empty(), basecamp::survey_field_return(), basecamp::survey_return(), iexamine::translocator(), iexamine::tree_hickory(), overmap_ui::try_travel_to_destination(), debug_menu::unlock_all(), place_trap_actor::use(), sew_advanced_actor::use(), detach_gunmods_actor::use(), avatar_action::use_item(), salvage_actor::valid_to_cut_up(), basecamp::validate_sort_points(), game::vertical_move(), game::wield(), wield_before_use(), debug_menu::wisheffect(), iexamine::workout(), and main_menu::world_tab().
query_ynq()
query_ynq_result query_ynq (const std::string & text)
Definition at line 851 of file output.cpp.
 {
     // TODO: android native UI
     const bool force_uc = get_option<bool>( "FORCE_CAPITAL_YN" );
     const auto &allow_key = force_uc ? input_context::disallow_lower_case_or_non_modified_letters
                             : input_context::allow_all_keys;
     const std::string action =
         query_popup()
         .context( "YESNOQUIT" )
         .message( force_uc && !is_keycode_mode_supported()
                   ? pgettext( "query_yn", "%s (Case Sensitive)" )
                   : pgettext( "query_yn", "%s" ), text )
         .option( "YES", allow_key )
         .option( "NO", allow_key )
         .option( "QUIT", allow_key )
         .allow_cancel( true )
         .cursor( 2 )
         .default_color( c_light_red )
         .query()
         .action;
     if( action == "NO" ) {
         return query_ynq_result::no;
     } else if( action == "YES" ) {
         return query_ynq_result::yes;
     }
     return query_ynq_result::quit;
 }
References action, query_popup::result::action, input_context::allow_all_keys(), query_popup::allow_cancel(), c_light_red, query_popup::context(), query_popup::cursor(), query_popup::default_color(), input_context::disallow_lower_case_or_non_modified_letters(), is_keycode_mode_supported(), query_popup::message(), no, query_popup::option(), pgettext, query_popup::query(), quit, and yes.
Referenced by diary::edit_page_ui(), query_ynq(), and game::zones_manager().
rad_badge_color()
std::pair<std::string, nc_color> rad_badge_color (const int rad)
Definition at line 2694 of file output.cpp.
 {
     using pair_t = std::pair<const int, std::pair<std::string, nc_color>>;
     static const std::array<pair_t, 6> values = {{
             pair_t { 0,   { translate_marker( "green" ),  c_white_green } },
             pair_t { 30,  { translate_marker( "blue" ),   h_white       } },
             pair_t { 60,  { translate_marker( "yellow" ), i_yellow      } },
             pair_t { 120, { translate_marker( "orange" ), c_red_yellow  } },
             pair_t { 240, { translate_marker( "red" ),    c_red_red     } },
             pair_t { 500, { translate_marker( "black" ),  c_pink        } }
         }
     };
     unsigned i = 0;
     for( ; i < values.size(); i++ ) {
         if( rad <= values[i].first ) {
             break;
         }
     }
     i = i == values.size() ? i - 1 : i;
     return std::pair<std::string, nc_color>( _( values[i].second.first ), values[i].second.second );
 }
References _, c_pink, c_red_red, c_red_yellow, c_white_green, h_white, i_yellow, second, and translate_marker.
Referenced by item::armor_fit_info(), and Character::irradiate().
rand_char()
char rand_char ()
Definition at line 1318 of file output.cpp.
 {
     switch( rng( 0, 9 ) ) {
         case 0:
             return '|';
         case 1:
             return '-';
         case 2:
             return '#';
         case 3:
             return '?';
         case 4:
             return '&';
         case 5:
             return '.';
         case 6:
             return '%';
         case 7:
             return '{';
         case 8:
             return '*';
         case 9:
             return '^';
     }
     return '?';
 }
References rng().
remove_color_tags()
std::string remove_color_tags (std::string_view s)
Removes the color tags from the input string.
This might be required when the string is to be used for functions that don't handle color tags.
Definition at line 200 of file output.cpp.
 {
     std::string ret;
     std::vector<size_t> tag_positions = get_tag_positions( s );
     if( tag_positions.empty() ) {
         return std::string( s );
     }
     size_t next_pos = 0;
     for( size_t tag_position : tag_positions ) {
         ret += s.substr( next_pos, tag_position - next_pos );
         next_pos = s.find( ">", tag_position, 1 ) + 1;
     }
     ret += s.substr( next_pos, std::string::npos );
     return ret;
 }
References get_tag_positions(), and cata::hash64_detail::ret.
Referenced by inventory_selector::_uncategorize(), Character::ablative_armor_absorb(), outfit::absorb_damage(), inventory_selector::add_vehicle_items(), basic_item_filter(), uilist::calc_data(), string_input_popup::create_window(), Character::describe_damage(), Messages::display_messages(), Messages::dialog::do_filter(), inventory_column::draw(), keybindings_ui::draw_controls(), query_popup_impl::draw_controls(), char_creation::draw_location(), draw_medical_titlebar(), help::draw_menu(), draw_points(), diary::export_to_txt(), item_contents::favorite_settings_menu(), input_context::filter_strings_by_phrase(), query_popup_impl::fold_query(), anonymous_namespace{inventory_ui.cpp}::get_cached_name(), widget::layout(), game::list_items(), ascii_art::load(), display::morale_emotion(), query_popup_impl::on_resized(), parse_tags(), popup(), multiline_list::print_line(), anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), main_menu::print_menu_items(), uilist::query(), recipe_subset::search(), set_hobbies(), set_profession(), set_scenario(), shortcut_print(), uilist::show(), trim_by_length(), utf8_width(), and main_menu::world_tab().
remove_punctuations()
std::string remove_punctuations (const std::string_view s)
Definition at line 1378 of file output.cpp.
 {
     std::string result;
     std::remove_copy_if( s.begin(), s.end(), std::back_inserter( result ),
     []( unsigned char ch ) {
         return std::ispunct( ch ) && ch != '_';
     } );
     return result;
 }
replace_city_tag()
void replace_city_tag (std::string & input, const std::string & name)
Definition at line 2490 of file output.cpp.
 {
     replace_substring( input, "<city>", name, true );
 }
References om_direction::name(), and replace_substring().
Referenced by jmapgen_graffiti::apply_all_tags(), jmapgen_sign::apply_all_tags(), and iuse::radio_tick().
replace_colors()
std::string replace_colors (std::string text)
Definition at line 998 of file output.cpp.
 {
     static const std::vector<std::pair<std::string, std::string>> info_colors = {
         {"info", get_all_colors().get_name( c_cyan )},
         {"stat", get_all_colors().get_name( c_light_blue )},
         {"header", get_all_colors().get_name( c_magenta )},
         {"bold", get_all_colors().get_name( c_white )},
         {"dark", get_all_colors().get_name( c_dark_gray )},
         {"good", get_all_colors().get_name( c_green )},
         {"bad", get_all_colors().get_name( c_red )},
         {"neutral", get_all_colors().get_name( c_yellow )}
     };
     for( const auto &elem : info_colors ) {
         text = string_replace( text, "<" + elem.first + ">", "<color_" + elem.second + ">" );
         text = string_replace( text, "</" + elem.first + ">", "</color>" );
     }
     return text;
 }
References c_cyan, c_dark_gray, c_green, c_light_blue, c_magenta, c_red, c_white, c_yellow, get_all_colors(), color_manager::get_name(), and string_replace().
Referenced by Character::extended_description(), monster::extended_description(), npc::extended_description(), inventory_selector_preset::get_cell_text(), inventory_selector_preset::cell_t::get_text(), iteminfo::iteminfo(), and ma_style_callback::key().
replace_keybind_tag()
void replace_keybind_tag (std::string & input)
Definition at line 2495 of file output.cpp.
 {
     std::string keybind_tag_start = "<keybind:";
     size_t keybind_length = keybind_tag_start.length();
     std::string keybind_tag_end = ">";
     size_t pos = input.find( keybind_tag_start );
     while( pos != std::string::npos ) {
         size_t pos_end = input.find( keybind_tag_end, pos );
         if( pos_end == std::string::npos ) {
             debugmsg( "Mismatched keybind tag in string: '%s'", input );
             break;
         }
         size_t pos_keybind = pos + keybind_length;
         std::string keybind_full = input.substr( pos_keybind, pos_end - pos_keybind );
         std::string keybind = keybind_full;
         size_t pos_category_split = keybind_full.find( ':' );
         std::string category = "DEFAULTMODE";
         if( pos_category_split != std::string::npos ) {
             category = keybind_full.substr( 0, pos_category_split );
             keybind = keybind_full.substr( pos_category_split + 1 );
         }
         input_context ctxt( category );
         std::string keybind_desc;
         std::vector<input_event> keys = ctxt.keys_bound_to( keybind, -1, false, false );
         if( keys.empty() ) { // Display description for unbound keys
             keybind_desc = colorize( '<' + ctxt.get_desc( keybind ) + '>', c_red );
             if( !ctxt.is_registered_action( keybind ) ) {
                 debugmsg( "Invalid/Missing <keybind>: '%s'", keybind_full );
             }
         } else {
             keybind_desc = enumerate_as_string( keys.begin(), keys.end(), []( const input_event & k ) {
                 return colorize( '\'' + k.long_description() + '\'', c_yellow );
             }, enumeration_conjunction::or_ );
         }
         std::string to_replace = string_format( "%s%s%s", keybind_tag_start, keybind_full,
                                                 keybind_tag_end );
         replace_substring( input, to_replace, keybind_desc, true );
         pos = input.find( keybind_tag_start );
     }
 }
References c_red, anonymous_namespace{item_tname.cpp}::category(), colorize(), debugmsg, enumerate_as_string(), input_context::get_desc(), input_context::is_registered_action(), input_context::keys_bound_to(), or_, math_opers::pos(), replace_substring(), and string_format().
Referenced by tutorial_game::add_message().
replace_substring()
void replace_substring (std::string & input, const std::string & substring, const std::string & replacement, bool all)
Definition at line 2542 of file output.cpp.
 {
     std::size_t find_after = 0;
     std::size_t pos = 0;
     const std::size_t pattern_length = substring.length();
     const std::size_t replacement_length = replacement.length();
     while( ( pos = input.find( substring, find_after ) ) != std::string::npos ) {
         input.replace( pos, pattern_length, replacement );
         find_after = pos + replacement_length;
         if( !all ) {
             break;
         }
     }
 }
References om_direction::all, math_opers::pos(), and replacement.
Referenced by escape_data(), escape_property(), replace_city_tag(), replace_keybind_tag(), and Creature::replace_with_npc_name().
rewrite_vsnprintf()
std::string rewrite_vsnprintf (const char * msg)
Definition at line 2334 of file output.cpp.
 {
     bool contains_positional = false;
     const char *orig_msg = msg;
     const char *formats = "diouxXeEfFgGaAcsCSpnm";
     std::string rewritten_msg;
     std::string rewritten_msg_optimised;
     const char *ptr = nullptr;
     int next_positional_arg = 1;
     while( true ) {
         // First find next position where argument might be used
         ptr = strchr( msg, '%' );
         if( !ptr ) {
             rewritten_msg += msg;
             rewritten_msg_optimised += msg;
             break;
         }
         // Write portion of the string that was before %
         rewritten_msg += std::string( msg, ptr );
         rewritten_msg_optimised += std::string( msg, ptr );
         const char *arg_start = ptr;
         ptr++;
         // If it simply '%%', then no processing needed
         if( *ptr == '%' ) {
             rewritten_msg += "%%";
             rewritten_msg_optimised += "%%";
             msg = ptr + 1;
             continue;
         }
         // Parse possible number of positional argument
         int positional_arg = 0;
         while( isdigit( *ptr ) ) {
             positional_arg = positional_arg * 10 + *ptr - '0';
             ptr++;
         }
         // If '$' ever follows a numeral, the string has a positional arg
         if( *ptr == '$' ) {
             contains_positional = true;
         }
         // Check if it's expected argument
         if( *ptr == '$' && positional_arg == next_positional_arg ) {
             next_positional_arg++;
         } else {
             next_positional_arg = -1;
         }
         // Now find where it ends
         const char *end = strpbrk( ptr, formats );
         if( !end ) {
             // Format string error. Just bail.
             return orig_msg;
         }
         // write entire argument to rewritten_msg
         if( positional_arg < 10 ) {
             std::string argument( arg_start, end + 1 );
             rewritten_msg += argument;
         } else {
             rewritten_msg += "<formatting error>";
         }
         // write argument without position to rewritten_msg_optimised
         if( next_positional_arg > 0 ) {
             std::string argument( ptr + 1, end + 1 );
             rewritten_msg_optimised += "%" + argument;
         }
         msg = end + 1;
     }
     if( !contains_positional ) {
         return orig_msg;
     }
     if( next_positional_arg > 0 ) {
         // If all positioned arguments were in order (%1$d %2$d) then we simply
         // strip arguments
         return rewritten_msg_optimised;
     }
     return rewritten_msg;
 }
References keycode::end.
Referenced by cata::string_formatter::raw_string_format().
right_print()
int right_print (const catacurses::window & w, const int line, const int right_indent, const nc_color & FG, const std::string & text)
Definition at line 574 of file output.cpp.
 {
     const int available_width = std::max( 1, getmaxx( w ) - right_indent );
     const int x = std::max( 0, available_width - utf8_width( text, true ) );
     trim_and_print( w, point( x, line ), available_width, FG, text );
     return x;
 }
References catacurses::getmaxx(), line(), max(), trim_and_print(), and utf8_width().
Referenced by trade_ui::_draw_header(), veh_interact::calc_overview(), player_morale::display(), draw_bionics_tab(), draw_bionics_titlebar(), draw_can_craft_indicator(), draw_effects_tab(), draw_encumbrance_tab(), inventory_selector::draw_footer(), prof_window::draw_header(), inventory_selector::draw_header(), draw_hidden_amount(), draw_medical_titlebar(), draw_proficiencies_tab(), draw_skills_tab(), draw_stats_tab(), draw_tip(), draw_traits_tab(), insert_table(), game::list_monsters(), game::look_around(), print_ranged_chance(), advanced_inventory::redraw_sidebar(), set_description(), Messages::dialog::show(), and outfit::sort_armor().
rm_prefix()
std::string rm_prefix (std::string str, char c1, char c2)
Removes the prefix starting at the first occurrence of c1 until the first occurrence of c2.
Definition at line 2573 of file output.cpp.
 {
     if( !str.empty() && str[0] == c1 ) {
         size_t pos = str.find_first_of( c2 );
         if( pos != std::string::npos ) {
             str = str.substr( pos + 1 );
         }
     }
     return str;
 }
References math_opers::pos().
Referenced by cataimgui::window::draw_colored_text(), fold_and_print_from(), print_colored_text(), and trim_by_length().
satiety_bar()
std::string satiety_bar (const int calpereffv)
Definition at line 2847 of file output.cpp.
 {
     // Arbitrary max value we will cap our vague display to. Will be lower than the actual max value, but scaling fixes that.
     constexpr float max_cal_per_effective_vol = 1500.0f;
     // Scaling the values.
     const float scaled_max = std::sqrt( max_cal_per_effective_vol );
     const float scaled_cal = std::sqrt( calpereffv );
     const std::pair<std::string, nc_color> nourishment_bar = get_bar(
                 scaled_cal, scaled_max, 5, true );
     // Colorize the bar.
     std::string result = colorize( nourishment_bar.first, nourishment_bar.second );
     // Pad to 5 characters with dots.
     const int width = utf8_width( nourishment_bar.first );
     if( width < 5 ) {
         result += std::string( 5 - width, '.' );
     }
     return result;
 }
References colorize(), get_bar(), sqrt(), and utf8_width().
Referenced by comestible_inventory_preset::comestible_inventory_preset(), and item::food_info().
scrollable_text()
void scrollable_text (const std::function< catacurses::window()> & init_window, const std::string & title, const std::string & text)
Definition at line 432 of file output.cpp.
 {
     // NOLINTNEXTLINE(cata-use-named-point-constants)
     constexpr point text2( 1, 1 );
     input_context ctxt( "SCROLLABLE_TEXT" );
     ctxt.register_action( "UP" );
     ctxt.register_action( "DOWN" );
     ctxt.register_action( "PAGE_UP" );
     ctxt.register_action( "PAGE_DOWN" );
     ctxt.register_action( "CONFIRM" );
     ctxt.register_action( "QUIT" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     // mouse
     ctxt.register_action( "SCROLL_UP" );
     ctxt.register_action( "SCROLL_DOWN" );
     catacurses::window w;
     int width = 0;
     int height = 0;
     int text_w = 0;
     int text_h = 0;
     std::vector<std::string> lines;
     int beg_line = 0;
     int max_beg_line = 0;
     ui_adaptor ui;
     const auto screen_resize_cb = [&]( ui_adaptor & ui ) {
         w = init_window();
         width = getmaxx( w );
         height = getmaxy( w );
         text_w = std::max( 0, width - 2 );
         text_h = std::max( 0, height - 2 );
         lines = foldstring( text, text_w );
         max_beg_line = std::max( 0, static_cast<int>( lines.size() ) - text_h );
         ui.position_from_window( w );
     };
     screen_resize_cb( ui );
     ui.on_screen_resize( screen_resize_cb );
     ui.on_redraw( [&]( const ui_adaptor & ) {
         werase( w );
         draw_border( w, BORDER_COLOR, title );
         for( int line = beg_line, pos_y = text2.y; line < std::min<int>( beg_line + text_h, lines.size() );
              ++line, ++pos_y ) {
             nc_color dummy = c_white;
             print_colored_text( w, point( text2.x, pos_y ), dummy, dummy, lines[line] );
         }
         scrollbar().offset_x( width - 1 ).offset_y( text2.y ).content_size( lines.size() )
         .viewport_pos( std::min( beg_line, max_beg_line ) ).viewport_size( text_h ).apply( w );
         wnoutrefresh( w );
     } );
     std::string action;
     do {
         ui_manager::redraw();
         action = ctxt.handle_input();
         if( action == "UP" || action == "SCROLL_UP" || action == "DOWN" || action == "SCROLL_DOWN" ) {
             beg_line = inc_clamp( beg_line, action == "DOWN" || action == "SCROLL_DOWN", max_beg_line );
         } else if( action == "PAGE_UP" ) {
             beg_line = std::max( beg_line - text_h, 0 );
         } else if( action == "PAGE_DOWN" ) {
             // always scroll an entire page's length
             if( beg_line < max_beg_line ) {
                 beg_line += text_h;
             }
         }
     } while( action != "CONFIRM" && action != "QUIT" );
 }
References action, scrollbar::apply(), BORDER_COLOR, c_white, scrollbar::content_size(), draw_border(), foldstring(), catacurses::getmaxx(), catacurses::getmaxy(), input_context::handle_input(), inc_clamp(), init_window(), line(), max(), min(), scrollbar::offset_x(), scrollbar::offset_y(), print_colored_text(), ui_manager::redraw(), input_context::register_action(), music::title, scrollbar::viewport_pos(), scrollbar::viewport_size(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by smart_controller_ui::control(), game::disp_NPC_epilogues(), game::display_faction_epilogues(), help::display_help(), and outfit::sort_armor().
shortcut_print() [1/2]
size_t shortcut_print (const catacurses::window & w, const point & p, nc_color text_color, nc_color shortcut_color, const std::string & fmt)
Definition at line 2587 of file output.cpp.
 {
     wmove( w, p );
     return shortcut_print( w, text_color, shortcut_color, fmt );
 }
References catacurses::wmove().
Referenced by draw_header(), help::draw_menu(), game::list_monsters(), snake_game::print_header(), game::reset_item_list_state(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), safemode::show(), lightson_game::start_game(), minesweeper_game::start_game(), sokoban_game::start_game(), and zones_manager_shortcuts().
shortcut_print() [2/2]
size_t shortcut_print (const catacurses::window & w, nc_color text_color, nc_color shortcut_color, const std::string & fmt)
Definition at line 2595 of file output.cpp.
 {
     std::string text = shortcut_text( shortcut_color, fmt );
     // NOLINTNEXTLINE(cata-use-named-point-constants)
     print_colored_text( w, point( -1, -1 ), text_color, text_color, text );
     return utf8_width( remove_color_tags( text ) );
 }
References print_colored_text(), remove_color_tags(), shortcut_text(), and utf8_width().
shortcut_text()
std::string shortcut_text (nc_color shortcut_color, const std::string & fmt)
Definition at line 2606 of file output.cpp.
 {
     size_t pos = fmt.find_first_of( '<' );
     size_t pos_end = fmt.find_first_of( '>' );
     if( pos_end != std::string::npos && pos < pos_end ) {
         size_t sep = std::min( fmt.find_first_of( '|', pos ), pos_end );
         std::string prestring = fmt.substr( 0, pos );
         std::string poststring = fmt.substr( pos_end + 1, std::string::npos );
         std::string shortcut = fmt.substr( pos + 1, sep - pos - 1 );
         return prestring + colorize( shortcut, shortcut_color ) + poststring;
     }
     // no shortcut?
     return fmt;
 }
References colorize(), min(), and math_opers::pos().
Referenced by main_menu::display_sub_menu(), help::draw_menu(), main_menu::print_menu_items(), shortcut_print(), and main_menu::world_tab().
split_by_color()
std::vector<std::string> split_by_color (const std::string_view s)
Definition at line 186 of file output.cpp.
 {
     std::vector<std::string> ret;
     std::vector<size_t> tag_positions = get_tag_positions( s );
     size_t last_pos = 0;
     for( size_t tag_position : tag_positions ) {
         ret.emplace_back( s.substr( last_pos, tag_position - last_pos ) );
         last_pos = tag_position;
     }
     // and the last (or only) one
     ret.emplace_back( s.substr( last_pos, std::string::npos ) );
     return ret;
 }
References get_tag_positions(), and cata::hash64_detail::ret.
Referenced by cataimgui::window::draw_colored_text(), fold_and_print_from(), print_colored_text(), and trim_by_length().
string_from_int()
std::string string_from_int (const catacurses::chtype ch)
Definition at line 76 of file output.cpp.
 {
     catacurses::chtype charcode = ch;
     // LINE_NESW  - X for on, O for off
     switch( ch ) {
         case LINE_XOXO:
             charcode = LINE_XOXO_C;
             break;
         case LINE_OXOX:
             charcode = LINE_OXOX_C;
             break;
         case LINE_XXOO:
             charcode = LINE_XXOO_C;
             break;
         case LINE_OXXO:
             charcode = LINE_OXXO_C;
             break;
         case LINE_OOXX:
             charcode = LINE_OOXX_C;
             break;
         case LINE_XOOX:
             charcode = LINE_XOOX_C;
             break;
         case LINE_XXOX:
             charcode = LINE_XXOX_C;
             break;
         case LINE_XXXO:
             charcode = LINE_XXXO_C;
             break;
         case LINE_XOXX:
             charcode = LINE_XOXX_C;
             break;
         case LINE_OXXX:
             charcode = LINE_OXXX_C;
             break;
         case LINE_XXXX:
             charcode = LINE_XXXX_C;
             break;
         default:
             break;
     }
     // NOLINTNEXTLINE(modernize-avoid-c-arrays)
     char buffer[2] = { static_cast<char>( charcode ), '\0' };
     return buffer;
 }
References LINE_OOXX, LINE_OOXX_C, LINE_OXOX, LINE_OXOX_C, LINE_OXXO, LINE_OXXO_C, LINE_OXXX, LINE_OXXX_C, LINE_XOOX, LINE_XOOX_C, LINE_XOXO, LINE_XOXO_C, LINE_XOXX, LINE_XOXX_C, LINE_XXOO, LINE_XXOO_C, LINE_XXOX, LINE_XXOX_C, LINE_XXXO, LINE_XXXO_C, LINE_XXXX, and LINE_XXXX_C.
Referenced by unicode_codepoint_from_symbol_reader().
string_replace()
std::string string_replace (std::string text, const std::string & before, const std::string & after)
Definition at line 978 of file output.cpp.
 {
     // Check if there's something to replace (mandatory) and it's necessary (optional)
     // Second condition assumes that text is much longer than both &before and &after.
     if( before.empty() || before == after ) {
         return text;
     }
     const size_t before_len = before.length();
     const size_t after_len = after.length();
     size_t pos = 0;
     while( ( pos = text.find( before, pos ) ) != std::string::npos ) {
         text.replace( pos, before_len, after );
         pos += after_len;
     }
     return text;
 }
References math_opers::pos().
Referenced by vehicle::can_mount(), mission_ui_impl::draw_selected_description(), help::get_dir_grid(), computer::load_legacy_data(), and replace_colors().
to_upper_case()
std::string to_upper_case (const std::string & s)
Definition at line 1389 of file output.cpp.
 {
     const auto &f = std::use_facet<std::ctype<wchar_t>>( std::locale() );
     std::wstring wstr = utf8_to_wstr( s );
     f.toupper( wstr.data(), wstr.data() + wstr.size() );
     return wstr_to_utf8( wstr );
 }
References utf8_to_wstr(), and wstr_to_utf8().
Referenced by inventory_selector::_uncategorize(), inventory_selector::add_map_items(), inventory_selector::add_remote_map_items(), inventory_selector::add_vehicle_items(), armor_inventory_preset::armor_inventory_preset(), bodygraph_display::draw_borders(), draw_health_summary(), and string_to_modtype().
trim() [1/2]
std::string trim (const std::string_view s)
Definition at line 1363 of file output.cpp.
 {
     return trim( s, []( int c ) {
         return isspace( c );
     } );
 }
References c, and trim().
trim() [2/2]
template<typename Predicate > static std::string trim (std::string_view s, Predicate pred) static
Definition at line 1346 of file output.cpp.
 {
     auto wsfront = std::find_if_not( s.begin(), s.end(), pred );
     std::string_view::const_reverse_iterator wsfront_reverse( wsfront );
     auto wsend = std::find_if_not( s.crbegin(), wsfront_reverse, pred );
     return std::string( wsfront, wsend.base() );
 }
Referenced by direction_suffix(), prof_window::filter(), filter_from_string(), filter_recipes(), lru_cache< Key, Value >::insert(), select_crafter_and_crafting_recipe(), and trim().
trim_and_print()
void trim_and_print (const catacurses::window & w, const point & begin, int width, const nc_color & base_color, const std::string & text, report_color_error color_error = report_color_error::yes)
Prints a single line of text.
The text is automatically trimmed to fit into the given width. The function handles color_tags correctly. It does not handle any other tags, and does not handle line breaks.
Parameters
w Window we are printing in
begin The coordinates of line start (curses coordinates)
width Maximal width of the printed line, if the text is longer, it is cut off.
base_color The initially used color. This can be overridden using color tags.
text Actual message to print
Definition at line 268 of file output.cpp.
 {
     std::string sText = trim_by_length( text, width );
     nc_color dummy = base_color;
     print_colored_text( w, begin, dummy, base_color, sText, color_error );
 }
References print_colored_text(), and trim_by_length().
Referenced by veh_interact::calc_overview(), center_print(), Character::conduct_blood_analysis(), widget::custom_draw_multiline(), avatar::disp_medical(), faction_manager::display(), player_morale::display(), veh_interact::display_list(), veh_interact::display_overview(), main_menu::display_sub_menu(), inventory_column::draw(), string_input_popup::draw(), draw_bionics_tab(), bodygraph_display::draw_borders(), prof_window::draw_details(), draw_effects_tab(), bodygraph_display::draw_graph(), prof_window::draw_header(), inventory_selector::draw_header(), target_ui::draw_help_notice(), bodygraph_display::draw_info(), draw_item_info(), exosuit_interact::draw_menu(), worldfactory::draw_mod_list(), bodygraph_display::draw_partlist(), draw_traits_tab(), target_ui::draw_window_title(), draw_x_info(), mtype::faction_display(), basecamp::job_assignment_ui(), game::list_items(), game::list_monsters(), avatar::power_bionics(), avatar::power_mutations(), game::print_furniture_info(), npc::print_info(), advanced_inventory::print_items(), game::print_items_info(), anonymous_namespace{diary_ui.cpp}::print_list_scrollable(), main_menu::print_menu_items(), vehicle::print_part_list(), advanced_inventory::redraw_pane(), right_print(), set_description(), options_manager::show(), safemode::show(), uilist::show(), diary::show_diary_ui(), worldfactory::show_worldgen_basic(), outfit::sort_armor(), trim_and_print(), editmap::update_view_with_help(), iexamine::vending(), and basecamp::worker_assignment_ui().
trim_by_length()
std::string trim_by_length (const std::string & text, int width)
Definition at line 278 of file output.cpp.
 {
     if( width <= 0 ) {
         debugmsg( "Unable to trim string '%s' to width %d.  Returning empty string.", text, width );
         return "";
     }
     std::string sText;
     sText.reserve( width );
     if( utf8_width( remove_color_tags( text ) ) > width ) {
         int iLength = 0;
         std::string sTempText;
         sTempText.reserve( width );
         std::string sColor;
         std::string sColorClose;
         std::string sEllipsis = "\u2026";
         const std::vector<std::string> color_segments = split_by_color( text );
         for( size_t i = 0; i < color_segments.size() ; ++i ) {
             const std::string &seg = color_segments[i];
             if( seg.empty() ) {
                 // TODO: Check is required right now because, for a fully-color-tagged string, split_by_color
                 // returns an empty string first
                 continue;
             }
             sColor.clear();
             sColorClose.clear();
             if( !seg.empty() && ( seg.substr( 0, 7 ) == "<color_" || seg.substr( 0, 7 ) == "</color" ) ) {
                 sTempText = rm_prefix( seg );
                 if( seg.substr( 0, 7 ) == "<color_" ) {
                     sColor = seg.substr( 0, seg.find( '>' ) + 1 );
                     sColorClose = "</color>";
                 }
             } else {
                 sTempText = seg;
             }
             const int iTempLen = utf8_width( sTempText );
             iLength += iTempLen;
             int next_char_width = 0;
             if( i + 1 < color_segments.size() ) {
                 next_char_width = mk_wcwidth( UTF8_getch( remove_color_tags( color_segments[i + 1] ) ) );
             }
             int pos = 0;
             bool trimmed = false;
             if( iLength > width || ( iLength == width && i + 1 < color_segments.size() ) ) {
                 // This segment won't fit OR
                 // This segment just fits and there's another segment coming
                 cursorx_to_position( sTempText.c_str(), iTempLen - ( iLength - width ) - 1, &pos, -1 );
                 sTempText = sColor.append( sTempText.substr( 0, pos ) ).append( sEllipsis ).append( sColorClose );
                 trimmed = true;
             } else if( iLength + next_char_width >= width ) {
                 // This segments fits, but the next segment starts with a wide character
                 sTempText = sColor.append( sTempText ).append( sColorClose ).append( sEllipsis );
                 trimmed = true;
             }
             if( trimmed ) {
                 sText += sTempText; // Color tags were handled when the segment was trimmed
                 break;
             } else { // This segment fits, and the next one has room to start
                 sText += sColor.append( sTempText ).append( sColorClose );
             }
         }
     } else {
         sText = text;
     }
     return sText;
 }
References cursorx_to_position(), debugmsg, mk_wcwidth(), math_opers::pos(), remove_color_tags(), rm_prefix(), coords::seg, split_by_color(), UTF8_getch(), and utf8_width().
Referenced by anonymous_namespace{armor_layers.cpp}::add_category_and_values(), inventory_column::draw(), draw_bionics_tab(), bodygraph_display::draw_partlist(), draw_proficiencies_tab(), prof_window::draw_profs(), widget::layout(), ascii_art::load(), select_crafter_and_crafting_recipe(), set_description(), outfit::sort_armor(), trim_and_print(), trimmed_name_and_value(), and game::zones_manager().
trim_trailing()
template<typename Prep > std::string trim_trailing (const std::string_view s, Prep prep)
Definition at line 1355 of file output.cpp.
 {
     return std::string( s.begin(), std::find_if_not(
     s.rbegin(), s.rend(), [&prep]( int c ) {
         return prep( c );
     } ).base() );
 }
References c.
Referenced by trim_trailing_punctuations().
trim_trailing_punctuations()
std::string trim_trailing_punctuations (const std::string_view s)
Definition at line 1370 of file output.cpp.
 {
     return trim_trailing( s, []( int c ) {
         // '<' and '>' are used for tags and should not be removed
         return c == '.' || c == '!';
     } );
 }
References c, and trim_trailing().
Referenced by wear_inventory_preset::get_denial(), take_off_inventory_preset::get_denial(), activatable_inventory_preset::get_denial(), weapon_inventory_preset::get_denial(), saw_barrel_inventory_preset::get_denial(), saw_stock_inventory_preset::get_denial(), and sounds::process_sound_markers().
trimmed_name_and_value() [1/2]
std::string trimmed_name_and_value (const std::string & name, const std::string & value, const int field_width)
Definition at line 539 of file output.cpp.
 {
     const int text_width = utf8_width( name ) + utf8_width( value );
     if( text_width >= field_width ) {
         //Since it's easier to abbreviate a string than a number, try to preserve the value
         std::string trimmed_name = trim_by_length( name, field_width - utf8_width( value ) - 1 );
         return trimmed_name + " " + value;
     } else {
         const int spacing = field_width - text_width;
         return name + std::string( spacing, ' ' ) + value;
     }
 }
References om_direction::name(), trim_by_length(), and utf8_width().
Referenced by anonymous_namespace{armor_layers.cpp}::add_category_and_values(), and trimmed_name_and_value().
trimmed_name_and_value() [2/2]
std::string trimmed_name_and_value (const std::string & name, int const value, const int field_width)
Definition at line 553 of file output.cpp.
 {
     return trimmed_name_and_value( name, string_format( "%d", value ), field_width );
 }
References om_direction::name(), string_format(), and trimmed_name_and_value().
update_color_stack()
color_tag_parse_result::tag_type update_color_stack (std::stack< nc_color > & color_stack, std::string_view seg, report_color_error color_error = report_color_error::yes)
Adds the color represented by the next color tag found in the string to the top of the stack.
If color_error == report_color_error::yes a debugmsg will be shown when the tag is not valid.
Definition at line 218 of file output.cpp.
 {
     color_tag_parse_result tag = get_color_from_tag( seg, color_error );
     switch( tag.type ) {
         case color_tag_parse_result::open_color_tag:
             color_stack.push( tag.color );
             break;
         case color_tag_parse_result::close_color_tag:
             if( !color_stack.empty() ) {
                 color_stack.pop();
             }
             break;
         case color_tag_parse_result::non_color_tag:
             // Do nothing
             break;
     }
     return tag.type;
 }
References color_tag_parse_result::close_color_tag, color_tag_parse_result::color, get_color_from_tag(), color_tag_parse_result::non_color_tag, color_tag_parse_result::open_color_tag, coords::seg, and color_tag_parse_result::type.
Referenced by cataimgui::window::draw_colored_text(), fold_and_print_from(), and print_colored_text().
uppercase_first_letter()
std::string uppercase_first_letter (const std::string & str)
Definition at line 2558 of file output.cpp.
 {
     std::wstring wstr = utf8_to_wstr( str );
     wstr[0] = towupper( wstr[0] );
     return wstr_to_utf8( wstr );
 }
References utf8_to_wstr(), and wstr_to_utf8().
Referenced by item::armor_protection_info(), item::bionic_info(), anonymous_namespace{armor_layers.cpp}::clothing_protection(), item_pocket::contents_info(), draw_health_summary(), bodygraph_display::draw_partlist(), handle_action_menu(), iexamine::keg(), make_gun_sound_effect(), item::melee_combat_info(), dialogue::opt(), item::pet_armor_protection_info(), outfit::prepare_bodymap_info(), bodygraph_display::prepare_infotext(), game::print_furniture_info(), and game::print_terrain_info().
wildcard_match()
bool wildcard_match (const std::string & text_in, const std::string & pattern_in)
Match text containing wildcards (*)
Parameters
text_in Text to check
pattern_in Pattern to check text_in against Case insensitive search Possible patterns:
wooD wood* wood Wood*aRrOW wood*arrow wood*arrow *wood*hard x*y*z*arrow
Definition at line 3152 of file output.cpp.
 {
     std::string text = text_in;
     if( text.empty() ) {
         return false;
     } else if( text == "*" ) {
         return true;
     }
     std::vector<std::string> pattern = string_split( wildcard_trim_rule( pattern_in ), '*' );
     if( pattern.size() == 1 ) { // no * found
         return ( text.length() == pattern[0].length() && ci_find_substr( text, pattern[0] ) != -1 );
     }
     for( auto it = pattern.begin(); it != pattern.end(); ++it ) {
         if( it == pattern.begin() && !it->empty() ) {
             if( text.length() < it->length() ||
                 ci_find_substr( text.substr( 0, it->length() ), *it ) == -1 ) {
                 return false;
             }
             text = text.substr( it->length(), text.length() - it->length() );
         } else if( it == pattern.end() - 1 && !it->empty() ) {
             if( text.length() < it->length() ||
                 ci_find_substr( text.substr( text.length() - it->length(),
                                              it->length() ), *it ) == -1 ) {
                 return false;
             }
         } else {
             if( !( *it ).empty() ) {
                 int pos = ci_find_substr( text, *it );
                 if( pos == -1 ) {
                     return false;
                 }
                 text = text.substr( pos + static_cast<int>( it->length() ),
                                     static_cast<int>( text.length() ) - pos );
             }
         }
     }
     return true;
 }
References ci_find_substr(), math_opers::pos(), string_split(), and wildcard_trim_rule().
Referenced by auto_pickup::rule_list::create_rule(), filter_recipes(), safemode::is_sound_safe(), auto_pickup::rule_list::refresh_map_items(), safemode::set_rule(), auto_pickup::rule::test_pattern(), and safemode::test_pattern().
wildcard_trim_rule()
std::string wildcard_trim_rule (const std::string & pattern_in)
Definition at line 3198 of file output.cpp.
 {
     std::string pattern = pattern_in;
     size_t pos = pattern.find( "**" );
     //Remove all double ** in pattern
     while( pos != std::string::npos ) {
         pattern = pattern.substr( 0, pos ) + pattern.substr( pos + 1, pattern.length() - pos - 1 );
         pos = pattern.find( "**" );
     }
     return pattern;
 }
References math_opers::pos().
Referenced by auto_pickup::user_interface::show(), safemode::show(), and wildcard_match().
word_rewrap()
std::string word_rewrap (const std::string & in, int width, const uint32_t split)
Definition at line 1416 of file output.cpp.
 {
     std::string o;
     // find non-printing tags
     std::vector<size_t> tag_positions = get_tag_positions( in );
     int lastwb  = 0; //last word break
     int lastout = 0;
     const char *instr = in.c_str();
     bool skipping_tag = false;
     bool just_wrapped = false;
     for( int j = 0, x = 0; j < static_cast<int>( in.size() ); ) {
         const char *ins = instr + j;
         int len = ANY_LENGTH;
         uint32_t uc = UTF8_getch( &ins, &len );
         if( uc == '<' ) { // maybe skip non-printing tag
             std::vector<size_t>::iterator it;
             for( it = tag_positions.begin(); it != tag_positions.end(); ++it ) {
                 if( static_cast<int>( *it ) == j ) {
                     skipping_tag = true;
                     break;
                 }
             }
         }
         const int old_j = j;
         j += ANY_LENGTH - len;
         if( skipping_tag ) {
             if( uc == '>' ) {
                 skipping_tag = false;
             }
             continue;
         }
         if( just_wrapped && uc == ' ' ) { // ignore spaces after wrapping
             lastwb = lastout = j;
             continue;
         }
         x += mk_wcwidth( uc );
         if( uc == split || is_cjk_or_emoji( uc ) ) {
             if( x <= width ) {
                 lastwb = j; // break after character
             } else {
                 lastwb = old_j; // break before character
             }
         }
         if( x > width ) {
             if( lastwb == lastout ) {
                 lastwb = old_j;
             }
             // old_j may equal to lastout, this checks it and ensures there's at least one character in the line.
             if( lastwb == lastout ) {
                 lastwb = j;
             }
             for( int k = lastout; k < lastwb; k++ ) {
                 o += in[k];
             }
             o += '\n';
             x = 0;
             lastout = j = lastwb;
             just_wrapped = true;
         } else {
             just_wrapped = false;
         }
     }
     for( int k = lastout; k < static_cast<int>( in.size() ); k++ ) {
         o += in[k];
     }
     return o;
 }
References ANY_LENGTH, get_tag_positions(), is_cjk_or_emoji(), mk_wcwidth(), mattack::split(), and UTF8_getch().
Referenced by foldstring(), and Character::mend_item().
wprintz()
void wprintz (const catacurses::window & w, const nc_color & FG, const std::string & text)
Definition at line 3298 of file output.cpp.
 {
     wattron( w, FG );
     wprintw( w, text );
     wattroff( w, FG );
 }
References catacurses::wattroff(), catacurses::wattron(), and catacurses::wprintw().
Referenced by game::bury_screen(), decorate_panel(), inventory_selector::draw_footer(), target_ui::draw_help_notice(), veh_app_interact::draw_info(), map::draw_maptile(), anonymous_namespace{animation.cpp}::draw_sct_curses(), query_destination_callback::draw_squares(), target_ui::draw_window_title(), fold_and_print_from(), game::list_items(), game::list_monsters(), worldfactory::pick_world(), avatar::power_mutations(), print_colored_text(), vehicle::print_fuel_indicator(), vehicle::print_fuel_indicators(), advanced_inventory::print_header(), npc::print_info(), advanced_inventory::print_items(), vehicle::print_part_list(), game::reset_item_list_state(), set_description(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), robot_finds_kitten::show(), options_manager::show(), uilist::show(), worldfactory::show_worldgen_tab_modselection(), outfit::sort_armor(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), and wprintz().
wputch()
void wputch (const catacurses::window & w, nc_color FG, int ch)
Definition at line 583 of file output.cpp.
 {
     wattron( w, FG );
     waddch( w, ch );
     wattroff( w, FG );
 }
References catacurses::waddch(), catacurses::wattroff(), and catacurses::wattron().
Referenced by map::draw(), map::draw_from_above(), robot_finds_kitten::draw_kitten(), map::draw_maptile(), robot_finds_kitten::draw_robot(), fold_and_print_from(), worldfactory::pick_world(), set_description(), options_manager::show(), worldfactory::show_worldgen_basic(), and worldfactory::show_worldgen_tab_modselection().
Variable Documentation
base_mouse_delay
const std::chrono::duration<int, std::milli> base_mouse_delay static
Initial value:
=
    std::chrono::milliseconds( 100 )
Definition at line 71 of file output.cpp.
Referenced by multiline_list::handle_navigation(), multiline_list::set_entry_pos(), and multiline_list::set_offset_pos().
FULL_SCREEN_HEIGHT
int FULL_SCREEN_HEIGHT
Definition at line 58 of file output.cpp.
Referenced by game::bury_screen(), avatar::disp_medical(), game::disp_NPC_epilogues(), game::disp_NPCs(), faction_manager::display(), player_morale::display(), talk_function::display_and_choose_opts(), game::display_faction_epilogues(), help::display_help(), main_menu::display_text(), sokoban_game::draw_level(), game_ui::init_ui(), init_window(), main_menu::init_windows(), basecamp::job_assignment_ui(), main(), main_menu::opening_screen(), avatar::power_bionics(), avatar::power_mutations(), inventory_selector::prepare_layout(), dialogue_window::resize(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), safemode::show(), color_manager::show_gui(), outfit::sort_armor(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), iexamine::vending(), and basecamp::worker_assignment_ui().
FULL_SCREEN_WIDTH
int FULL_SCREEN_WIDTH
Definition at line 57 of file output.cpp.
Referenced by game::bury_screen(), basecamp::craft_description(), string_input_popup::create_window(), Character::disp_info(), avatar::disp_medical(), game::disp_NPC_epilogues(), game::disp_NPCs(), advanced_inventory::display(), faction_manager::display(), player_morale::display(), talk_function::display_and_choose_opts(), game::display_faction_epilogues(), help::display_help(), main_menu::display_text(), sokoban_game::draw_level(), worldfactory::draw_modselection_borders(), draw_stats_info(), draw_x_info(), main_menu::init_strings(), init_window(), main_menu::init_windows(), basecamp::job_assignment_ui(), ma_style_callback::key(), main(), basecamp::om_upgrade_description(), query_popup_impl::on_resized(), worldfactory::pick_world(), avatar::power_bionics(), avatar::power_mutations(), snake_game::print_header(), main_menu::print_menu(), query_for_template_name(), dialogue_window::resize(), select_crafter_and_crafting_recipe(), set_description(), set_points(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), options_manager::show(), safemode::show(), worldfactory::show_active_world_mods(), color_manager::show_gui(), show_scores_ui(), worldfactory::show_worldgen_advanced(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), outfit::sort_armor(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), iexamine::vending(), and basecamp::worker_assignment_ui().
item_filter_help_1
const translation item_filter_help_1 static
Initial value:
= to_translation(
            "The default is to search item names.  Some single-character prefixes "
            "can be used with a colon <color_red>:</color> to search in other ways.  Additional filters "
            "are separated by commas <color_red>,</color>.\n"
            "Example: back,flash,aid, ,band\n\n"
        )
Definition at line 1046 of file output.cpp.
Referenced by item_filter_rule_string().
item_filter_help_2
const translation item_filter_help_2 static
Initial value:
= to_translation(
            "\nPlace [<color_red>--</color>] in front to include only matching items.\n"
            "Example: steel,-chunk,--c:spare parts"
        )
Definition at line 1052 of file output.cpp.
Referenced by item_filter_rule_string().
item_filter_prefixes
const std::vector<ItemFilterPrefix> item_filter_prefixes static
Initial value:
= {
    { 'c', to_translation( "food" ), to_translation( "<color_cyan>category</color> of item" ) },
    { 'm', to_translation( "iron" ), to_translation( "<color_cyan>material</color> item is made of" ) },
    { 'q', to_translation( "hammering" ), to_translation( "<color_cyan>quality</color> provided by tool" ) },
    { 'n', to_translation( "toolshelf" ), to_translation( "<color_cyan>notes</color> written on item" ) },
    { 'f', to_translation( "freezerburn" ), to_translation( "<color_cyan>hidden flags</color> of an item" ) },
    { 's', to_translation( "devices" ), to_translation( "<color_cyan>skill</color> taught by books" ) },
    { 'd', to_translation( "pipe" ), to_translation( "<color_cyan>disassembled</color> components" ) },
    { 'v', to_translation( "hand" ), to_translation( "covers <color_cyan>body part</color>" ) },
    { 'b', to_translation( "mre;sealed" ), to_translation( "items satisfying <color_cyan>both</color> conditions" ) }
}
Definition at line 1034 of file output.cpp.
Referenced by item_filter_rule_string().
item_filter_rule_intros
const std::array<translation, 3> item_filter_rule_intros static
Initial value:
{
    to_translation( "Type part of an item's name to filter it." ),
    to_translation( "Type part of an item's name to move nearby items to the bottom." ),
    to_translation( "Type part of an item's name to move nearby items to the top." )
}
Definition at line 1019 of file output.cpp.
Referenced by item_filter_rule_string().
OVERMAP_LEGEND_WIDTH
int OVERMAP_LEGEND_WIDTH
Definition at line 65 of file output.cpp.
Referenced by overmap_ui::display(), and overmap_ui::search().
OVERMAP_WINDOW_HEIGHT
int OVERMAP_WINDOW_HEIGHT
Definition at line 60 of file output.cpp.
Referenced by overmap_ui::display(), and overmap_ui::draw_ascii().
OVERMAP_WINDOW_TERM_HEIGHT
int OVERMAP_WINDOW_TERM_HEIGHT
Definition at line 63 of file output.cpp.
Referenced by overmap_ui::display().
OVERMAP_WINDOW_TERM_WIDTH
int OVERMAP_WINDOW_TERM_WIDTH
Definition at line 62 of file output.cpp.
Referenced by overmap_ui::display().
OVERMAP_WINDOW_WIDTH
int OVERMAP_WINDOW_WIDTH
Definition at line 61 of file output.cpp.
Referenced by overmap_ui::display(), and overmap_ui::draw_ascii().
POSX
int POSX
Definition at line 51 of file output.cpp.
Referenced by centerlistview(), game::create_or_get_main_ui_adaptor(), game::draw(), game::draw_async_anim_curses(), game::draw_blink_curses(), anonymous_namespace{animation.cpp}::draw_bullet_curses(), game::draw_critter(), anonymous_namespace{animation.cpp}::draw_line_curses(), game::draw_look_around_cursor(), game::draw_ter(), draw_trail(), game::draw_veh_dir_indicator(), game::mon_info_update(), anonymous_namespace{animation.cpp}::relative_view_pos(), and debug_menu::show_sound().
POSY
int POSY
Definition at line 52 of file output.cpp.
Referenced by centerlistview(), game::create_or_get_main_ui_adaptor(), game::draw(), game::draw_async_anim_curses(), game::draw_blink_curses(), anonymous_namespace{animation.cpp}::draw_bullet_curses(), game::draw_critter(), anonymous_namespace{animation.cpp}::draw_line_curses(), game::draw_look_around_cursor(), game::draw_ter(), draw_trail(), game::draw_veh_dir_indicator(), game::mon_info_update(), anonymous_namespace{animation.cpp}::relative_view_pos(), and debug_menu::show_sound().
scrollwheel_delay
const std::chrono::duration<int, std::milli> scrollwheel_delay static
Initial value:
=
    std::chrono::milliseconds( 500 )
Definition at line 73 of file output.cpp.
Referenced by multiline_list::handle_navigation().
SCT
scrollingcombattext SCT
Definition at line 67 of file output.cpp.
Referenced by Character::ablative_armor_absorb(), outfit::absorb_damage(), Character::deal_damage(), Character::describe_damage(), anonymous_namespace{animation.cpp}::draw_sct_curses(), game::get_player_input(), player_hit_message(), and game::setup().
TERMX
int TERMX
Definition at line 49 of file output.cpp.
Referenced by anonymous_namespace{trade_ui.cpp}::_pane_orig(), anonymous_namespace{trade_ui.cpp}::_pane_size(), veh_interact::allocate_windows(), game::bury_screen(), uilist::calc_data(), debug_menu::change_spells(), game_menus::inv::compare_items(), Character::conduct_blood_analysis(), game::create_or_get_main_ui_adaptor(), string_input_popup::create_window(), diary_window_position(), avatar::disp_medical(), game::disp_NPC_epilogues(), game::disp_NPCs(), advanced_inventory::display(), faction_manager::display(), overmap_ui::display(), player_morale::display(), talk_function::display_and_choose_opts(), game::display_faction_epilogues(), veh_interact::display_grid(), help::display_help(), main_menu::display_text(), tab_manager::draw(), keybindings_ui::draw_controls(), worldfactory::draw_modselection_borders(), game::draw_panels(), edit_json(), ensure_term_size(), inventory_examiner::execute(), game::extended_description(), inventory_examiner::force_max_window_size(), demo_ui::get_bounds(), game::get_player_input(), recipe_result_info_cache::get_result_data(), get_window_width(), keybindings_ui::init(), Messages::dialog::init(), game_ui::init_ui(), bodygraph_display::init_ui_windows(), prof_window::init_ui_windows(), veh_app_interact::init_ui_windows(), init_window(), target_ui::init_window_and_input(), exosuit_interact::init_windows(), main_menu::init_windows(), game::inventory_item_menu(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_monsters(), game::look_around(), new_centered_win(), worldfactory::pick_world(), overmap_ui::place_ter_or_special(), pocket_management_menu(), avatar::power_bionics(), avatar::power_mutations(), inventory_selector::prepare_layout(), advanced_inventory::print_items(), game::reset_item_list_state(), dialogue_window::resize(), inventory_selector::resize_window(), robot_finds_kitten::robot_finds_kitten(), overmap_ui::search(), select_crafter_and_crafting_recipe(), Character::select_requirements(), known_magic::select_spell(), set_description(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), options_manager::show(), safemode::show(), live_view::show(), worldfactory::show_active_world_mods(), panel_manager::show_adm(), color_manager::show_gui(), worldfactory::show_worldgen_advanced(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), outfit::sort_armor(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), trade_ui::trade_ui(), computer_session::use(), iexamine::vending(), debug_menu::wishitem(), debug_menu::wishmonster(), debug_menu::wishmutate(), basecamp::worker_assignment_ui(), game::zones_manager(), and zones_manager_draw_borders().
TERMY
int TERMY
Definition at line 50 of file output.cpp.
Referenced by anonymous_namespace{trade_ui.cpp}::_pane_size(), computer_session::action_list_bionics(), veh_interact::allocate_windows(), game::bury_screen(), uilist::calc_data(), debug_menu::change_spells(), game_menus::inv::compare_items(), Character::conduct_blood_analysis(), game::create_or_get_main_ui_adaptor(), editmap::create_or_get_ui_adaptor(), string_input_popup::create_window(), diary_window_position(), Character::disp_info(), avatar::disp_medical(), game::disp_NPC_epilogues(), game::disp_NPCs(), advanced_inventory::display(), faction_manager::display(), overmap_ui::display(), player_morale::display(), talk_function::display_and_choose_opts(), game::display_faction_epilogues(), help::display_help(), main_menu::display_text(), worldfactory::draw_modselection_borders(), overmap_ui::draw_om_sidebar(), game::draw_panels(), editmap::edit_feature(), editmap::edit_fld(), editmap::edit_itm(), editmap::edit_mapgen(), ensure_term_size(), inventory_examiner::execute(), game::extended_description(), inventory_examiner::force_max_window_size(), keybindings_ui::get_bounds(), demo_ui::get_bounds(), game::get_player_input(), get_window_height(), Messages::dialog::init(), game_ui::init_ui(), bodygraph_display::init_ui_windows(), prof_window::init_ui_windows(), veh_app_interact::init_ui_windows(), init_window(), target_ui::init_window_and_input(), exosuit_interact::init_windows(), main_menu::init_windows(), game::inventory_item_menu(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_items(), game::list_monsters(), game::look_around(), editmap::mapgen_preview(), new_centered_win(), worldfactory::pick_world(), pocket_management_menu(), avatar::power_bionics(), avatar::power_mutations(), inventory_selector::prepare_layout(), game::reset_item_list_state(), dialogue_window::resize(), inventory_selector::resize_window(), robot_finds_kitten::robot_finds_kitten(), select_crafter_and_crafting_recipe(), known_magic::select_spell(), set_description(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_skills(), set_stats(), set_traits(), ui::omap::setup_cities_menu(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), options_manager::show(), safemode::show(), live_view::show(), worldfactory::show_active_world_mods(), panel_manager::show_adm(), color_manager::show_gui(), show_scores_ui(), worldfactory::show_worldgen_advanced(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), outfit::sort_armor(), lightson_game::start_game(), minesweeper_game::start_game(), snake_game::start_game(), sokoban_game::start_game(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), computer_session::use(), iexamine::vending(), basecamp::worker_assignment_ui(), game::zones_manager(), and zones_manager_draw_borders().
TERRAIN_WINDOW_HEIGHT
int TERRAIN_WINDOW_HEIGHT
Definition at line 54 of file output.cpp.
Referenced by centerlistview(), game::create_or_get_main_ui_adaptor(), game::get_player_input(), and is_valid_in_w_terrain().
TERRAIN_WINDOW_TERM_HEIGHT
int TERRAIN_WINDOW_TERM_HEIGHT
Definition at line 56 of file output.cpp.
Referenced by game::create_or_get_main_ui_adaptor().
TERRAIN_WINDOW_TERM_WIDTH
int TERRAIN_WINDOW_TERM_WIDTH
Definition at line 55 of file output.cpp.
Referenced by game::create_or_get_main_ui_adaptor().
TERRAIN_WINDOW_WIDTH
int TERRAIN_WINDOW_WIDTH
Definition at line 53 of file output.cpp.
Referenced by centerlistview(), game::create_or_get_main_ui_adaptor(), game::get_player_input(), and is_valid_in_w_terrain().