Cataclysm DDA: src/overlay_ordering.h File Reference
overlay_ordering.h File Reference
#include <map>
#include <string>
Macros
#define CATA_SRC_OVERLAY_ORDERING_H
Functions
void load_overlay_ordering (const JsonObject &jsobj)
void load_overlay_ordering_into_array (const JsonObject &jsobj, std::map< std::string, int > &orderarray)
int get_overlay_order_of_mutation (const std::string &mutation_id_string)
void reset_overlay_ordering ()
Variables
std::map< std::string, int > base_mutation_overlay_ordering
std::map< std::string, int > tileset_mutation_overlay_ordering
Macro Definition Documentation
CATA_SRC_OVERLAY_ORDERING_H
#define CATA_SRC_OVERLAY_ORDERING_H
Definition at line 3 of file overlay_ordering.h.
Function Documentation
get_overlay_order_of_mutation()
int get_overlay_order_of_mutation (const std::string & mutation_id_string)
Definition at line 28 of file overlay_ordering.cpp.
 {
     auto it = base_mutation_overlay_ordering.find( mutation_id_string );
     auto it2 = tileset_mutation_overlay_ordering.find( mutation_id_string );
     int value = 9999;
     if( it != base_mutation_overlay_ordering.end() ) {
         value = it->second;
     }
     if( it2 != tileset_mutation_overlay_ordering.end() ) {
         value = it2->second;
     }
     return value;
 }
References base_mutation_overlay_ordering, and tileset_mutation_overlay_ordering.
Referenced by Character::get_overlay_ids().
load_overlay_ordering()
void load_overlay_ordering (const JsonObject & jsobj)
Definition at line 12 of file overlay_ordering.cpp.
 {
     load_overlay_ordering_into_array( jsobj, base_mutation_overlay_ordering );
 }
References base_mutation_overlay_ordering, and load_overlay_ordering_into_array().
Referenced by DynamicDataLoader::initialize().
load_overlay_ordering_into_array()
void load_overlay_ordering_into_array (const JsonObject & jsobj, std::map< std::string, int > & orderarray)
Definition at line 17 of file overlay_ordering.cpp.
 {
     for( JsonObject ordering : jsobj.get_array( "overlay_ordering" ) ) {
         int order = ordering.get_int( "order" );
         for( const std::string &id : ordering.get_tags( "id" ) ) {
             orderarray[id] = order;
         }
     }
 }
References JsonObject::get_array(), and int_id< T >::id().
Referenced by load_overlay_ordering().
reset_overlay_ordering()
void reset_overlay_ordering ()
Definition at line 42 of file overlay_ordering.cpp.
 {
     // tileset specific overlays are cleared on new tileset load
     base_mutation_overlay_ordering.clear();
 }
References base_mutation_overlay_ordering.
Referenced by DynamicDataLoader::unload_data().
Variable Documentation
base_mutation_overlay_ordering
std::map<std::string, int> base_mutation_overlay_ordering extern
Definition at line 9 of file overlay_ordering.cpp.
Referenced by get_overlay_order_of_mutation(), load_overlay_ordering(), and reset_overlay_ordering().
tileset_mutation_overlay_ordering
std::map<std::string, int> tileset_mutation_overlay_ordering extern
Definition at line 10 of file overlay_ordering.cpp.
Referenced by get_overlay_order_of_mutation().