Cataclysm DDA: src/overmap.h File Reference
overmap.h File Reference
#include <algorithm>
#include <array>
#include <climits>
#include <cstdlib>
#include <functional>
#include <iosfwd>
#include <iterator>
#include <map>
#include <optional>
#include <string>
#include <string_view>
#include <unordered_map>
#include <utility>
#include <vector>
#include "basecamp.h"
#include "city.h"
#include "coordinates.h"
#include "cube_direction.h"
#include "enums.h"
#include "game_constants.h"
#include "mapgendata.h"
#include "mdarray.h"
#include "memory_fast.h"
#include "mongroup.h"
#include "overmap_types.h"
#include "point.h"
#include "rng.h"
#include "type_id.h"
Classes
struct om_note
struct om_map_extra
struct om_vehicle
struct radio_tower
struct map_layer
struct om_special_sectors
struct overmap_special_placement
class overmap_special_batch
struct pos_dir< Tripoint >
struct std::hash< pos_dir< Tripoint > >
class overmap
Namespaces
pf
Macros
#define CATA_SRC_OVERMAP_H
Typedefs
using om_pos_dir = pos_dir< tripoint_om_omt >
using rel_pos_dir = pos_dir< tripoint_rel_omt >
Enumerations
enum class radio_type : int { MESSAGE_BROADCAST , WEATHER_RADIO }
Functions
bool is_river (const oter_id &ter)
bool is_water_body (const oter_id &ter)
bool is_lake_or_river (const oter_id &ter)
bool is_ocean (const oter_id &ter)
bool is_ot_match (const std::string &name, const oter_id &oter, ot_match_type match_type)
Determine if the provided name is a match with the provided overmap terrain based on the specified match type.
om_special_sectors get_sectors (int sector_width)
Gets a collection of sectors and their width for usage in placing overmap specials.
std::string_view oter_no_dir (const oter_id &oter)
Returns the string of oter without any directional suffix.
int oter_get_rotation (const oter_id &oter)
Return 0, 1, 2, 3 respectively if the suffix is _north, _west, _south, _east Return 0 if there's no suffix.
std::string oter_get_rotation_string (const oter_id &oter)
Return the directional suffix or "" if there isn't one.
Variables
std::map< radio_type, std::string > radio_type_names
constexpr int RADIO_MIN_STRENGTH = 120
constexpr int RADIO_MAX_STRENGTH = 360
Macro Definition Documentation
CATA_SRC_OVERMAP_H
#define CATA_SRC_OVERMAP_H
Definition at line 3 of file overmap.h.
Typedef Documentation
om_pos_dir
using om_pos_dir = pos_dir<tripoint_om_omt>
Definition at line 172 of file overmap.h.
rel_pos_dir
using rel_pos_dir = pos_dir<tripoint_rel_omt>
Definition at line 173 of file overmap.h.
Enumeration Type Documentation
radio_type
enum radio_type : int strong
Enumerator
MESSAGE_BROADCAST
WEATHER_RADIO
Definition at line 67 of file overmap.h.
                       : int {
     MESSAGE_BROADCAST,
     WEATHER_RADIO
 };
Function Documentation
get_sectors()
om_special_sectors get_sectors (int sector_width)
Gets a collection of sectors and their width for usage in placing overmap specials.
Parameters
sector_width used to divide the OMAPX by OMAPY map into sectors.
Definition at line 6672 of file overmap.cpp.
 {
     std::vector<point_om_omt> res;
     res.reserve( static_cast<size_t>( OMAPX / sector_width ) * static_cast<size_t>
                  ( OMAPY / sector_width ) );
     for( int x = 0; x < OMAPX; x += sector_width ) {
         for( int y = 0; y < OMAPY; y += sector_width ) {
             res.emplace_back( x, y );
         }
     }
     std::shuffle( res.begin(), res.end(), rng_get_engine() );
     return om_special_sectors{ res, sector_width };
 }
References OMAPX, OMAPY, and rng_get_engine().
Referenced by overmapbuffer::place_special(), and overmap::place_specials().
is_lake_or_river()
bool is_lake_or_river (const oter_id & ter)
Definition at line 578 of file overmap.cpp.
 {
     return ter->is_river() || ter->is_lake() || ter->is_lake_shore();
 }
References oter_t::is_lake(), oter_t::is_lake_shore(), and oter_t::is_river().
Referenced by overmap::place_mongroups().
is_ocean()
bool is_ocean (const oter_id & ter)
Definition at line 589 of file overmap.cpp.
 {
     return ter->is_ocean() || ter->is_ocean_shore();
 }
References oter_t::is_ocean(), and oter_t::is_ocean_shore().
Referenced by mapgen_ocean_shore(), overmap::place_mongroups(), overmap::place_oceans(), and overmap::place_specials().
is_ot_match()
bool is_ot_match (const std::string & name, const oter_id & oter, ot_match_type match_type)
Determine if the provided name is a match with the provided overmap terrain based on the specified match type.
Parameters
name is the name we're looking for.
oter is the overmap terrain id we're comparing our name with.
match_type is the matching rule to use when comparing the two values.
Definition at line 594 of file overmap.cpp.
 {
     static const auto is_ot = []( const std::string & otype, const oter_id & oter ) {
         return otype == oter.id().str();
     };
     static const auto is_ot_type = []( const std::string & otype, const oter_id & oter ) {
         // Is a match if the base type is the same which will allow for handling rotations/linear features
         // but won't incorrectly match other locations that happen to contain the substring.
         return otype == oter->get_type_id().str();
     };
     static const auto is_ot_subtype = []( const std::string & otype, const oter_id & oter ) {
         // Is a match if the base type and linear subtype (end/straight/curved/tee/four_way) are the same which will allow for handling rotations of linear features
         // but won't incorrectly match other locations that happen to contain the substring.
         return otype == oter->get_mapgen_id();
     };
     static const auto is_ot_prefix = []( const std::string & otype, const oter_id & oter ) {
         const size_t oter_size = oter.id().str().size();
         const size_t compare_size = otype.size();
         if( compare_size > oter_size ) {
             return false;
         }
         const auto &oter_str = oter.id();
         if( oter_str.str().compare( 0, compare_size, otype ) != 0 ) {
             return false;
         }
         // check if it's a full match
         if( compare_size == oter_size ) {
             return true;
         }
         // only okay for partial if next char is an underscore
         return oter_str.str()[compare_size] == '_';
     };
     static const auto is_ot_contains = []( const std::string & otype, const oter_id & oter ) {
         // Checks for any partial match.
         return strstr( oter.id().c_str(), otype.c_str() );
     };
     switch( match_type ) {
         case ot_match_type::exact:
             return is_ot( name, oter );
         case ot_match_type::type:
             return is_ot_type( name, oter );
         case ot_match_type::subtype:
             return is_ot_subtype( name, oter );
         case ot_match_type::prefix:
             return is_ot_prefix( name, oter );
         case ot_match_type::contains:
             return is_ot_contains( name, oter );
         default:
             return false;
     }
 }
References string_id< T >::c_str(), contains, exact, oter_t::get_mapgen_id(), oter_t::get_type_id(), int_id< T >::id(), om_direction::name(), prefix, string_id< T >::str(), subtype, and type.
Referenced by computer_session::action_map_sewer(), computer_session::action_map_subway(), overmap::build_lab(), overmap::check_ot(), map::draw_lab(), map::draw_map(), map::draw_slimepit(), start_location::find_player_initial_location(), overmap::find_random_omt(), overmap::generate_sub(), recipe_group::get_recipes_by_id(), overmap::good_river(), mapgen_lake_shore(), mapgen_ocean_shore(), overmap::move_hordes(), overmap::move_nemesis(), om_target_tile(), overmap::place_forest_trailheads(), overmap::place_forest_trails(), mission_start::place_npc_software(), overmap::place_radios(), overmap::place_swamps(), talk_function::start_camp(), jmapgen_nested::neighbor_oter_check::test(), and jmapgen_nested::predecessor_oter_check::test().
is_river()
bool is_river (const oter_id & ter)
Definition at line 573 of file overmap.cpp.
 {
     return ter->is_river();
 }
References oter_t::is_river().
Referenced by basecamp::combat_mission_return(), companion_travel_time_calc(), overmap::place_lakes(), overmap::place_oceans(), overmap::place_railroads(), overmap::place_rivers(), overmap::place_roads(), and overmapbuffer::reveal_route().
is_water_body()
bool is_water_body (const oter_id & ter)
Definition at line 583 of file overmap.cpp.
 {
     return ter->is_river() || ter->is_lake() || ter->is_lake_shore() || ter->is_ocean() ||
            ter->is_ocean_shore();
 }
References oter_t::is_lake(), oter_t::is_lake_shore(), oter_t::is_ocean(), oter_t::is_ocean_shore(), and oter_t::is_river().
Referenced by overmap_ui::get_overmap_path_to(), overmap::good_river(), and game::perhaps_add_random_npc().
oter_get_rotation()
int oter_get_rotation (const oter_id & oter)
Return 0, 1, 2, 3 respectively if the suffix is _north, _west, _south, _east Return 0 if there's no suffix.
Definition at line 7400 of file overmap.cpp.
 {
     std::string base_oter_id = oter.id().c_str();
     for( size_t i = 0; i < suffixes.size(); ++i ) {
         if( string_ends_with( base_oter_id, suffixes[i] ) ) {
             return i;
         }
     }
     return 0;
 }
References string_id< T >::c_str(), int_id< T >::id(), string_ends_with(), and suffixes.
Referenced by overmap::generate_bridgeheads().
oter_get_rotation_string()
std::string oter_get_rotation_string (const oter_id & oter)
Return the directional suffix or "" if there isn't one.
Definition at line 7411 of file overmap.cpp.
 {
     std::string base_oter_id = oter.id().c_str();
     for( const std::string &suffix : suffixes ) {
         if( string_ends_with( base_oter_id, suffix ) ) {
             return suffix;
         }
     }
     return "";
 }
References string_id< T >::c_str(), int_id< T >::id(), string_ends_with(), and suffixes.
Referenced by basecamp::define_camp(), and overmap::generate_over().
oter_no_dir()
std::string_view oter_no_dir (const oter_id & oter)
Returns the string of oter without any directional suffix.
Definition at line 7389 of file overmap.cpp.
 {
     std::string_view base_oter_id = oter.id().str();
     for( const std::string &suffix : suffixes ) {
         if( string_ends_with( base_oter_id, suffix ) ) {
             base_oter_id = base_oter_id.substr( 0, base_oter_id.size() - suffix.size() );
         }
     }
     return base_oter_id;
 }
References int_id< T >::id(), string_id< T >::str(), string_ends_with(), and suffixes.
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_at_om_location(), and conditional_fun::anonymous_namespace{condition.cpp}::f_near_om_location().
Variable Documentation
RADIO_MAX_STRENGTH
constexpr int RADIO_MAX_STRENGTH = 360 constexpr
Definition at line 75 of file overmap.h.
Referenced by overmapbuffer::find_all_radio_stations(), overmapbuffer::find_radio_station(), and overmap::place_radios().
RADIO_MIN_STRENGTH
constexpr int RADIO_MIN_STRENGTH = 120 constexpr
Definition at line 74 of file overmap.h.
Referenced by overmap::place_radios(), and radio_static_chance().
radio_type_names
std::map<radio_type, std::string> radio_type_names extern
Definition at line 340 of file overmap.cpp.
Referenced by overmap::serialize(), and overmap::unserialize().