Cataclysm DDA: src/overmap_ui.cpp File Reference
overmap_ui.cpp File Reference
#include "overmap_ui.h"
#include <algorithm>
#include <array>
#include <chrono>
#include <cstddef>
#include <functional>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "activity_actor_definitions.h"
#include "all_enum_values.h"
#include "avatar.h"
#include "basecamp.h"
#include "calendar.h"
#include "enum_conversions.h"
#include "cata_scope_helpers.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "city.h"
#include "clzones.h"
#include "color.h"
#include "coordinates.h"
#include "cuboid_rectangle.h"
#include "cursesdef.h"
#include "display.h"
#include "game.h"
#include "game_constants.h"
#include "game_ui.h"
#include "input_context.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapbuffer.h"
#include "mission.h"
#include "mongroup.h"
#include "npc.h"
#include "omdata.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "overmap_types.h"
#include "overmapbuffer.h"
#include "point.h"
#include "regional_settings.h"
#include "rng.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "ui_manager.h"
#include "uistate.h"
#include "units.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "weather_gen.h"
#include "weather_type.h"
Classes
class overmap_ui::map_notes_callback
Namespaces
overmap_ui
Functions
static void overmap_ui::create_note (const tripoint_abs_omt &curs)
std::tuple< char, nc_color, size_t > overmap_ui::get_note_display_info (const std::string_view note)
static std::array< std::pair< nc_color, std::string >, npm_width *npm_height > overmap_ui::get_overmap_neighbors (const tripoint_abs_omt &current)
static void overmap_ui::update_note_preview (const std::string_view note, const std::array< std::pair< nc_color, std::string >, npm_width *npm_height > &map_around, const std::tuple< catacurses::window *, catacurses::window *, catacurses::window * > &preview_windows)
weather_type_id overmap_ui::get_weather_at_point (const tripoint_abs_omt &pos)
static bool overmap_ui::get_scent_glyph (const tripoint_abs_omt &pos, nc_color &ter_color, std::string &ter_sym)
static void overmap_ui::draw_city_labels (const catacurses::window &w, const tripoint_abs_omt &center)
static void overmap_ui::draw_camp_labels (const catacurses::window &w, const tripoint_abs_omt &center)
static point_abs_omt overmap_ui::draw_notes (const tripoint_abs_omt &origin)
static bool overmap_ui::get_and_assign_los (int &los, avatar &player_character, const tripoint_abs_omt &omp, const int &sight_points)
static void overmap_ui::draw_ascii (const catacurses::window &w, const tripoint_abs_omt &center, const tripoint_abs_omt &orig, bool blink, bool show_explored, bool, input_context *, const draw_data_t &data)
static void overmap_ui::draw_om_sidebar (ui_adaptor &ui, const catacurses::window &wbar, const tripoint_abs_omt &center, const tripoint_abs_omt &orig, bool, bool fast_scroll, input_context *inp_ctxt, const draw_data_t &data)
static void overmap_ui::draw (ui_adaptor &ui, const tripoint_abs_omt &center, const tripoint_abs_omt &orig, bool blink, bool show_explored, bool fast_scroll, input_context *inp_ctxt, const draw_data_t &data)
static bool overmap_ui::search (const ui_adaptor &om_ui, tripoint_abs_omt &curs, const tripoint_abs_omt &orig)
static void overmap_ui::place_ter_or_special (const ui_adaptor &om_ui, tripoint_abs_omt &curs, const std::string &om_action)
static void overmap_ui::set_special_args (tripoint_abs_omt &curs)
static std::vector< tripoint_abs_omt > overmap_ui::get_overmap_path_to (const tripoint_abs_omt &dest, bool driving)
static bool overmap_ui::try_travel_to_destination (avatar &player_character, const tripoint_abs_omt curs, const bool driving)
static tripoint_abs_omt overmap_ui::display (const tripoint_abs_omt &orig, const draw_data_t &data=draw_data_t())
Variables
static const activity_id ACT_TRAVELLING ("ACT_TRAVELLING")
static const mongroup_id GROUP_FOREST ("GROUP_FOREST")
static const mongroup_id GROUP_NEMESIS ("GROUP_NEMESIS")
static const oter_str_id oter_forest ("forest")
static const oter_str_id oter_unexplored ("unexplored")
static const oter_type_str_id oter_type_forest_trail ("forest_trail")
static const trait_id trait_DEBUG_CLAIRVOYANCE ("DEBUG_CLAIRVOYANCE")
static const trait_id trait_DEBUG_NIGHTVISION ("DEBUG_NIGHTVISION")
static constexpr int UILIST_MAP_NOTE_DELETED = -2047
static constexpr int UILIST_MAP_NOTE_EDITED = -2048
static constexpr int max_note_length = 450
static constexpr int max_note_display_length = 45
static const int npm_width = 3
Note preview map width without borders.
static const int npm_height = 3
Note preview map height without borders.
static int overmap_ui::overmap_zoom_level = DEFAULT_TILESET_ZOOM
Variable Documentation
ACT_TRAVELLING
const activity_id ACT_TRAVELLING("ACT_TRAVELLING") ("ACT_TRAVELLING") static
Referenced by overmap_ui::try_travel_to_destination().
GROUP_FOREST
const mongroup_id GROUP_FOREST("GROUP_FOREST") ("GROUP_FOREST") static
Referenced by overmap_ui::draw_ascii().
GROUP_NEMESIS
const mongroup_id GROUP_NEMESIS("GROUP_NEMESIS") ("GROUP_NEMESIS") static
Referenced by overmap_ui::draw_ascii().
max_note_display_length
constexpr int max_note_display_length = 45 static constexpr
Definition at line 96 of file overmap_ui.cpp.
Referenced by overmap_ui::create_note(), and overmap_ui::map_notes_callback::map_notes_callback().
max_note_length
constexpr int max_note_length = 450 static constexpr
Definition at line 95 of file overmap_ui.cpp.
Referenced by overmap_ui::create_note().
npm_height
const int npm_height = 3 static
Note preview map height without borders.
Odd number.
Definition at line 101 of file overmap_ui.cpp.
Referenced by overmap_ui::create_note(), overmap_ui::get_overmap_neighbors(), overmap_ui::map_notes_callback::map_notes_callback(), and overmap_ui::update_note_preview().
npm_width
const int npm_width = 3 static
Note preview map width without borders.
Odd number.
Definition at line 99 of file overmap_ui.cpp.
Referenced by overmap_ui::create_note(), overmap_ui::get_overmap_neighbors(), overmap_ui::map_notes_callback::map_notes_callback(), and overmap_ui::update_note_preview().
oter_forest
const oter_str_id oter_forest("forest") ("forest") static
Referenced by overmap_ui::draw_ascii().
oter_type_forest_trail
const oter_type_str_id oter_type_forest_trail("forest_trail") ("forest_trail") static
Referenced by overmap_ui::draw_ascii().
oter_unexplored
const oter_str_id oter_unexplored("unexplored") ("unexplored") static
Referenced by overmap_ui::draw_ascii(), overmap_ui::draw_om_sidebar(), and overmap_ui::get_overmap_neighbors().
trait_DEBUG_CLAIRVOYANCE
const trait_id trait_DEBUG_CLAIRVOYANCE("DEBUG_CLAIRVOYANCE") ("DEBUG_CLAIRVOYANCE") static
Referenced by overmap_ui::draw_ascii().
trait_DEBUG_NIGHTVISION
const trait_id trait_DEBUG_NIGHTVISION("DEBUG_NIGHTVISION") ("DEBUG_NIGHTVISION") static
Referenced by overmap_ui::draw_ascii(), overmap_ui::draw_om_sidebar(), and overmap_ui::get_overmap_neighbors().
UILIST_MAP_NOTE_DELETED
constexpr int UILIST_MAP_NOTE_DELETED = -2047 static constexpr
Definition at line 92 of file overmap_ui.cpp.
Referenced by overmap_ui::draw_notes(), and overmap_ui::map_notes_callback::key().
UILIST_MAP_NOTE_EDITED
constexpr int UILIST_MAP_NOTE_EDITED = -2048 static constexpr
Definition at line 93 of file overmap_ui.cpp.
Referenced by overmap_ui::draw_notes(), and overmap_ui::map_notes_callback::key().