Cataclysm DDA: src/overmap.cpp File Reference
overmap.cpp File Reference
#include "cube_direction.h"
#include "omdata.h"
#include "overmap.h"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <exception>
#include <memory>
#include <numeric>
#include <optional>
#include <ostream>
#include <set>
#include <unordered_set>
#include <vector>
#include "all_enum_values.h"
#include "auto_note.h"
#include "avatar.h"
#include "assign.h"
#include "cached_options.h"
#include "cata_assert.h"
#include "cata_utility.h"
#include "cata_views.h"
#include "catacharset.h"
#include "character_id.h"
#include "coordinates.h"
#include "cuboid_rectangle.h"
#include "debug.h"
#include "distribution.h"
#include "effect_on_condition.h"
#include "flood_fill.h"
#include "game.h"
#include "generic_factory.h"
#include "json.h"
#include "line.h"
#include "map_iterator.h"
#include "mapbuffer.h"
#include "mapgen.h"
#include "mapgen_functions.h"
#include "messages.h"
#include "mongroup.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "overmap_connection.h"
#include "overmap_location.h"
#include "overmap_noise.h"
#include "overmap_types.h"
#include "overmapbuffer.h"
#include "path_info.h"
#include "regional_settings.h"
#include "rng.h"
#include "rotatable_symbols.h"
#include "sets_intersect.h"
#include "simple_pathfinding.h"
#include "string_formatter.h"
#include "text_snippets.h"
#include "translations.h"
Classes
struct om_lines::type
struct special_placement_result
struct overmap_special_data
struct fixed_overmap_special_data
struct mutable_overmap_join
struct enum_traits< join_type >
struct mutable_overmap_terrain_join
struct mutable_special_connection
struct mutable_overmap_terrain
struct mutable_overmap_piece_candidate
struct mutable_overmap_placement_rule_piece
struct mutable_overmap_placement_rule
struct mutable_overmap_placement_rule_remainder
class joins_tracker
struct joins_tracker::join
struct joins_tracker::indexed_joins
struct joins_tracker::compare_iterators
struct mutable_overmap_phase_remainder
struct mutable_overmap_phase_remainder::satisfy_result
struct mutable_overmap_phase_remainder::can_place_result
struct mutable_overmap_phase
struct mutable_overmap_special_data
Namespaces
io
om_lines
anonymous_namespace{overmap.cpp}
Macros
#define dbg(x) DebugLog((x),D_MAP_GEN) << __FILE__ << ":" << __LINE__ << ": "
Typedefs
using oter_type_id = int_id< oter_type_t >
using oter_type_str_id = string_id< oter_type_t >
using join_map = std::unordered_map< cube_direction, mutable_overmap_terrain_join >
Enumerations
enum class join_type { mandatory , available , last }
Functions
template<>
std::string io::enum_to_string< overmap_special_subtype > (overmap_special_subtype data)
template<>
std::string io::enum_to_string< om_direction::type > (om_direction::type d)
template<>
std::string io::enum_to_string< cube_direction > (cube_direction data)
static constexpr size_t om_lines::rotate (size_t line, om_direction::type dir)
static constexpr size_t om_lines::set_segment (size_t line, om_direction::type dir)
static constexpr bool om_lines::has_segment (size_t line, om_direction::type dir)
static constexpr bool om_lines::is_straight (size_t line)
static size_t om_lines::from_dir (om_direction::type dir)
static void set_oter_ids ()
bool is_river (const oter_id &ter)
bool is_lake_or_river (const oter_id &ter)
bool is_water_body (const oter_id &ter)
bool is_ocean (const oter_id &ter)
bool is_ot_match (const std::string &name, const oter_id &oter, const ot_match_type match_type)
Determine if the provided name is a match with the provided overmap terrain based on the specified match type.
static void load_overmap_terrain_mapgens (const JsonObject &jo, const std::string &id_base, const std::string &suffix="")
template<>
std::string io::enum_to_string< oter_flags > (oter_flags data)
template<>
std::string io::enum_to_string< oter_travel_cost_type > (oter_travel_cost_type data)
static bool is_amongst_locations (const oter_id &oter, const cata::flat_set< string_id< overmap_location >> &locations)
cube_direction operator+ (const cube_direction l, const om_direction::type r)
cube_direction operator+ (const cube_direction d, int i)
cube_direction operator- (const cube_direction l, const om_direction::type r)
cube_direction operator- (const cube_direction d, int i)
tripoint displace (cube_direction d)
template<>
std::string io::enum_to_string< join_type > (join_type data)
static pf::directed_path< point_om_omt > straight_path (const point_om_omt &source, om_direction::type dir, size_t len)
static om_direction::type rotate_internal (om_direction::type dir, int step)
om_special_sectors get_sectors (const int sector_width)
Gets a collection of sectors and their width for usage in placing overmap specials.
template<>
std::string io::enum_to_string< ot_match_type > (ot_match_type data)
std::string_view oter_no_dir (const oter_id &oter)
Returns the string of oter without any directional suffix.
int oter_get_rotation (const oter_id &oter)
Return 0, 1, 2, 3 respectively if the suffix is _north, _west, _south, _east Return 0 if there's no suffix.
std::string oter_get_rotation_string (const oter_id &oter)
Return the directional suffix or "" if there isn't one.
Variables
static const mongroup_id GROUP_NEMESIS ("GROUP_NEMESIS")
static const mongroup_id GROUP_OCEAN_DEEP ("GROUP_OCEAN_DEEP")
static const mongroup_id GROUP_OCEAN_SHORE ("GROUP_OCEAN_SHORE")
static const mongroup_id GROUP_RIVER ("GROUP_RIVER")
static const mongroup_id GROUP_SUBWAY_CITY ("GROUP_SUBWAY_CITY")
static const mongroup_id GROUP_SWAMP ("GROUP_SWAMP")
static const mongroup_id GROUP_ZOMBIE ("GROUP_ZOMBIE")
static const oter_str_id oter_central_lab ("central_lab")
static const oter_str_id oter_central_lab_core ("central_lab_core")
static const oter_str_id oter_central_lab_train_depot ("central_lab_train_depot")
static const oter_str_id oter_empty_rock ("empty_rock")
static const oter_str_id oter_field ("field")
static const oter_str_id oter_forest ("forest")
static const oter_str_id oter_forest_thick ("forest_thick")
static const oter_str_id oter_forest_water ("forest_water")
static const oter_str_id oter_ice_lab ("ice_lab")
static const oter_str_id oter_ice_lab_core ("ice_lab_core")
static const oter_str_id oter_lab ("lab")
static const oter_str_id oter_lab_core ("lab_core")
static const oter_str_id oter_lab_escape_cells ("lab_escape_cells")
static const oter_str_id oter_lab_escape_entrance ("lab_escape_entrance")
static const oter_str_id oter_lab_train_depot ("lab_train_depot")
static const oter_str_id oter_open_air ("open_air")
static const oter_str_id oter_river_c_not_ne ("river_c_not_ne")
static const oter_str_id oter_river_c_not_nw ("river_c_not_nw")
static const oter_str_id oter_river_c_not_se ("river_c_not_se")
static const oter_str_id oter_river_c_not_sw ("river_c_not_sw")
static const oter_str_id oter_river_center ("river_center")
static const oter_str_id oter_river_east ("river_east")
static const oter_str_id oter_river_ne ("river_ne")
static const oter_str_id oter_river_north ("river_north")
static const oter_str_id oter_river_nw ("river_nw")
static const oter_str_id oter_river_se ("river_se")
static const oter_str_id oter_river_south ("river_south")
static const oter_str_id oter_river_sw ("river_sw")
static const oter_str_id oter_river_west ("river_west")
static const oter_str_id oter_road_nesw ("road_nesw")
static const oter_str_id oter_road_nesw_manhole ("road_nesw_manhole")
static const oter_str_id oter_sewer_end_north ("sewer_end_north")
static const oter_str_id oter_sewer_isolated ("sewer_isolated")
static const oter_str_id oter_sewer_sub_station ("sewer_sub_station")
static const oter_str_id oter_solid_earth ("solid_earth")
static const oter_str_id oter_subway_end_north ("subway_end_north")
static const oter_str_id oter_subway_isolated ("subway_isolated")
static const oter_str_id oter_underground_sub_station ("underground_sub_station")
static const oter_type_str_id oter_type_ants_queen ("ants_queen")
static const oter_type_str_id oter_type_bridge ("bridge")
static const oter_type_str_id oter_type_central_lab_core ("central_lab_core")
static const oter_type_str_id oter_type_central_lab_stairs ("central_lab_stairs")
static const oter_type_str_id oter_type_empty_rock ("empty_rock")
static const oter_type_str_id oter_type_field ("field")
static const oter_type_str_id oter_type_forest ("forest")
static const oter_type_str_id oter_type_forest_thick ("forest_thick")
static const oter_type_str_id oter_type_forest_water ("forest_water")
static const oter_type_str_id oter_type_ice_lab_core ("ice_lab_core")
static const oter_type_str_id oter_type_ice_lab_stairs ("ice_lab_stairs")
static const oter_type_str_id oter_type_lab_core ("lab_core")
static const oter_type_str_id oter_type_lab_stairs ("lab_stairs")
static const oter_type_str_id oter_type_microlab_sub_connector ("microlab_sub_connector")
static const oter_type_str_id oter_type_railroad_bridge ("railroad_bridge")
static const oter_type_str_id oter_type_road ("road")
static const oter_type_str_id oter_type_road_nesw_manhole ("road_nesw_manhole")
static const oter_type_str_id oter_type_sewer_connector ("sewer_connector")
static const oter_type_str_id oter_type_slimepit_bottom ("slimepit_bottom")
static const oter_type_str_id oter_type_slimepit_down ("slimepit_down")
static const oter_type_str_id oter_type_solid_earth ("solid_earth")
static const oter_type_str_id oter_type_sub_station ("sub_station")
static const overmap_location_id overmap_location_land ("land")
static const overmap_location_id overmap_location_swamp ("swamp")
static const species_id species_ZOMBIE ("ZOMBIE")
static constexpr int BUILDINGCHANCE = 4
static constexpr int MIN_GOO_SIZE = 1
static constexpr int MAX_GOO_SIZE = 2
static oter_id ot_null
static const std::array< std::string, 5 > om_lines::mapgen_suffixes
static const std::array< type, 1+om_direction::bits > om_lines::all
static const size_t om_lines::size = all.size()
static const size_t om_lines::invalid = 0
t_regional_settings_map region_settings_map
generic_factory< overmap_land_use_code > anonymous_namespace{overmap.cpp}::land_use_codes ("overmap land use codes")
generic_factory< oter_type_t > anonymous_namespace{overmap.cpp}::terrain_types ("overmap terrain type")
generic_factory< oter_t > anonymous_namespace{overmap.cpp}::terrains ("overmap terrain")
generic_factory< overmap_special > anonymous_namespace{overmap.cpp}::specials ("overmap special")
generic_factory< overmap_special_migration > anonymous_namespace{overmap.cpp}::migrations ("overmap special migration")
std::map< radio_type, std::string > radio_type_names
static std::map< std::string, std::string > oter_id_migrations
static const std::array< std::string, 4 > suffixes = {{ "_north", "_west", "_south", "_east" }}
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x),D_MAP_GEN) << __FILE__ << ":" << __LINE__ << ": "
Definition at line 140 of file overmap.cpp.
Typedef Documentation
join_map
using join_map = std::unordered_map<cube_direction, mutable_overmap_terrain_join>
Definition at line 1560 of file overmap.cpp.
oter_type_id
using oter_type_id = int_id<oter_type_t>
Definition at line 146 of file overmap.cpp.
oter_type_str_id
using oter_type_str_id = string_id<oter_type_t>
Definition at line 147 of file overmap.cpp.
Enumeration Type Documentation
join_type
enum join_type strong
Enumerator
mandatory
available
last
Definition at line 1491 of file overmap.cpp.
                      {
     mandatory,
     available,
     last
 };
Function Documentation
displace()
tripoint displace (cube_direction d)
Definition at line 1161 of file overmap.cpp.
 {
     switch( d ) {
         case cube_direction::north:
             return tripoint_north;
         case cube_direction::east:
             return tripoint_east;
         case cube_direction::south:
             return tripoint_south;
         case cube_direction::west:
             return tripoint_west;
         case cube_direction::above:
             return tripoint_above;
         case cube_direction::below:
             return tripoint_below;
         case cube_direction::last:
             break;
     }
     cata_fatal( "Invalid cube_direction" );
 }
References above, below, cata_fatal, east, last, north, south, tripoint_above, tripoint_below, tripoint_east, tripoint_north, tripoint_south, tripoint_west, and west.
Referenced by mutable_overmap_phase_remainder::can_place(), mapgendata::mapgendata(), mutable_overmap_special_data::place(), and game::vertical_move().
get_sectors()
om_special_sectors get_sectors (int sector_width)
Gets a collection of sectors and their width for usage in placing overmap specials.
Parameters
sector_width used to divide the OMAPX by OMAPY map into sectors.
Definition at line 6672 of file overmap.cpp.
 {
     std::vector<point_om_omt> res;
     res.reserve( static_cast<size_t>( OMAPX / sector_width ) * static_cast<size_t>
                  ( OMAPY / sector_width ) );
     for( int x = 0; x < OMAPX; x += sector_width ) {
         for( int y = 0; y < OMAPY; y += sector_width ) {
             res.emplace_back( x, y );
         }
     }
     std::shuffle( res.begin(), res.end(), rng_get_engine() );
     return om_special_sectors{ res, sector_width };
 }
References OMAPX, OMAPY, and rng_get_engine().
Referenced by overmapbuffer::place_special(), and overmap::place_specials().
is_amongst_locations()
static bool is_amongst_locations (const oter_id & oter, const cata::flat_set< string_id< overmap_location >> & locations) static
Definition at line 1077 of file overmap.cpp.
 {
     return std::any_of( locations.begin(), locations.end(),
     [&oter]( const string_id<overmap_location> &loc ) {
         return loc->test( oter );
     } );
 }
References anonymous_namespace{overmap_location.cpp}::locations.
Referenced by overmap_special_locations::can_be_placed_on(), and mutable_overmap_phase_remainder::can_place().
is_lake_or_river()
bool is_lake_or_river (const oter_id & ter)
Definition at line 578 of file overmap.cpp.
 {
     return ter->is_river() || ter->is_lake() || ter->is_lake_shore();
 }
References oter_t::is_lake(), oter_t::is_lake_shore(), and oter_t::is_river().
Referenced by overmap::place_mongroups().
is_ocean()
bool is_ocean (const oter_id & ter)
Definition at line 589 of file overmap.cpp.
 {
     return ter->is_ocean() || ter->is_ocean_shore();
 }
References oter_t::is_ocean(), and oter_t::is_ocean_shore().
Referenced by mapgen_ocean_shore(), overmap::place_mongroups(), overmap::place_oceans(), and overmap::place_specials().
is_ot_match()
bool is_ot_match (const std::string & name, const oter_id & oter, ot_match_type match_type)
Determine if the provided name is a match with the provided overmap terrain based on the specified match type.
Parameters
name is the name we're looking for.
oter is the overmap terrain id we're comparing our name with.
match_type is the matching rule to use when comparing the two values.
Definition at line 594 of file overmap.cpp.
 {
     static const auto is_ot = []( const std::string & otype, const oter_id & oter ) {
         return otype == oter.id().str();
     };
     static const auto is_ot_type = []( const std::string & otype, const oter_id & oter ) {
         // Is a match if the base type is the same which will allow for handling rotations/linear features
         // but won't incorrectly match other locations that happen to contain the substring.
         return otype == oter->get_type_id().str();
     };
     static const auto is_ot_subtype = []( const std::string & otype, const oter_id & oter ) {
         // Is a match if the base type and linear subtype (end/straight/curved/tee/four_way) are the same which will allow for handling rotations of linear features
         // but won't incorrectly match other locations that happen to contain the substring.
         return otype == oter->get_mapgen_id();
     };
     static const auto is_ot_prefix = []( const std::string & otype, const oter_id & oter ) {
         const size_t oter_size = oter.id().str().size();
         const size_t compare_size = otype.size();
         if( compare_size > oter_size ) {
             return false;
         }
         const auto &oter_str = oter.id();
         if( oter_str.str().compare( 0, compare_size, otype ) != 0 ) {
             return false;
         }
         // check if it's a full match
         if( compare_size == oter_size ) {
             return true;
         }
         // only okay for partial if next char is an underscore
         return oter_str.str()[compare_size] == '_';
     };
     static const auto is_ot_contains = []( const std::string & otype, const oter_id & oter ) {
         // Checks for any partial match.
         return strstr( oter.id().c_str(), otype.c_str() );
     };
     switch( match_type ) {
         case ot_match_type::exact:
             return is_ot( name, oter );
         case ot_match_type::type:
             return is_ot_type( name, oter );
         case ot_match_type::subtype:
             return is_ot_subtype( name, oter );
         case ot_match_type::prefix:
             return is_ot_prefix( name, oter );
         case ot_match_type::contains:
             return is_ot_contains( name, oter );
         default:
             return false;
     }
 }
References string_id< T >::c_str(), contains, exact, oter_t::get_mapgen_id(), oter_t::get_type_id(), int_id< T >::id(), om_direction::name(), prefix, string_id< T >::str(), subtype, and type.
Referenced by computer_session::action_map_sewer(), computer_session::action_map_subway(), overmap::build_lab(), overmap::check_ot(), map::draw_lab(), map::draw_map(), map::draw_slimepit(), start_location::find_player_initial_location(), overmap::find_random_omt(), overmap::generate_sub(), recipe_group::get_recipes_by_id(), overmap::good_river(), mapgen_lake_shore(), mapgen_ocean_shore(), overmap::move_hordes(), overmap::move_nemesis(), om_target_tile(), overmap::place_forest_trailheads(), overmap::place_forest_trails(), mission_start::place_npc_software(), overmap::place_radios(), overmap::place_swamps(), talk_function::start_camp(), jmapgen_nested::neighbor_oter_check::test(), and jmapgen_nested::predecessor_oter_check::test().
is_river()
bool is_river (const oter_id & ter)
Definition at line 573 of file overmap.cpp.
 {
     return ter->is_river();
 }
References oter_t::is_river().
Referenced by basecamp::combat_mission_return(), companion_travel_time_calc(), overmap::place_lakes(), overmap::place_oceans(), overmap::place_railroads(), overmap::place_rivers(), overmap::place_roads(), and overmapbuffer::reveal_route().
is_water_body()
bool is_water_body (const oter_id & ter)
Definition at line 583 of file overmap.cpp.
 {
     return ter->is_river() || ter->is_lake() || ter->is_lake_shore() || ter->is_ocean() ||
            ter->is_ocean_shore();
 }
References oter_t::is_lake(), oter_t::is_lake_shore(), oter_t::is_ocean(), oter_t::is_ocean_shore(), and oter_t::is_river().
Referenced by overmap_ui::get_overmap_path_to(), overmap::good_river(), and game::perhaps_add_random_npc().
load_overmap_terrain_mapgens()
static void load_overmap_terrain_mapgens (const JsonObject & jo, const std::string & id_base, const std::string & suffix = "") static
Definition at line 659 of file overmap.cpp.
 {
     const std::string fmapkey( id_base + suffix );
     const std::string jsonkey( "mapgen" + suffix );
     register_mapgen_function( fmapkey );
     if( jo.has_array( jsonkey ) ) {
         for( JsonObject jio : jo.get_array( jsonkey ) ) {
             // NOLINTNEXTLINE(cata-use-named-point-constants)
             load_and_add_mapgen_function( jio, fmapkey, point_zero, point( 1, 1 ) );
         }
     }
 }
References JsonObject::get_array(), JsonObject::has_array(), load_and_add_mapgen_function(), point_zero, and register_mapgen_function().
Referenced by oter_type_t::load().
operator+() [1/2]
cube_direction operator+ (const cube_direction d, int i)
Definition at line 1122 of file overmap.cpp.
 {
     switch( d ) {
         case cube_direction::north:
         case cube_direction::east:
         case cube_direction::south:
         case cube_direction::west:
             return static_cast<cube_direction>( ( static_cast<int>( d ) + i ) % 4 );
         case cube_direction::above:
         case cube_direction::below:
             return d;
         case cube_direction::last:
             break;
     }
     constexpr_fatal( cube_direction::last, "Invalid cube_direction" );
 }
References above, below, constexpr_fatal, east, last, north, south, and west.
operator+() [2/2]
cube_direction operator+ (const cube_direction l, const om_direction::type r)
Definition at line 1117 of file overmap.cpp.
 {
     return l + static_cast<int>( r );
 }
operator-() [1/2]
cube_direction operator- (const cube_direction d, int i)
Definition at line 1144 of file overmap.cpp.
 {
     switch( d ) {
         case cube_direction::north:
         case cube_direction::east:
         case cube_direction::south:
         case cube_direction::west:
             return static_cast<cube_direction>( ( static_cast<int>( d ) - i + 4 ) % 4 );
         case cube_direction::above:
         case cube_direction::below:
             return d;
         case cube_direction::last:
             break;
     }
     constexpr_fatal( cube_direction::last, "Invalid cube_direction" );
 }
References above, below, constexpr_fatal, east, last, north, south, and west.
operator-() [2/2]
cube_direction operator- (const cube_direction l, const om_direction::type r)
Definition at line 1139 of file overmap.cpp.
 {
     return l - static_cast<int>( r );
 }
oter_get_rotation()
int oter_get_rotation (const oter_id & oter)
Return 0, 1, 2, 3 respectively if the suffix is _north, _west, _south, _east Return 0 if there's no suffix.
Definition at line 7400 of file overmap.cpp.
 {
     std::string base_oter_id = oter.id().c_str();
     for( size_t i = 0; i < suffixes.size(); ++i ) {
         if( string_ends_with( base_oter_id, suffixes[i] ) ) {
             return i;
         }
     }
     return 0;
 }
References string_id< T >::c_str(), int_id< T >::id(), string_ends_with(), and suffixes.
Referenced by overmap::generate_bridgeheads().
oter_get_rotation_string()
std::string oter_get_rotation_string (const oter_id & oter)
Return the directional suffix or "" if there isn't one.
Definition at line 7411 of file overmap.cpp.
 {
     std::string base_oter_id = oter.id().c_str();
     for( const std::string &suffix : suffixes ) {
         if( string_ends_with( base_oter_id, suffix ) ) {
             return suffix;
         }
     }
     return "";
 }
References string_id< T >::c_str(), int_id< T >::id(), string_ends_with(), and suffixes.
Referenced by basecamp::define_camp(), and overmap::generate_over().
oter_no_dir()
std::string_view oter_no_dir (const oter_id & oter)
Returns the string of oter without any directional suffix.
Definition at line 7389 of file overmap.cpp.
 {
     std::string_view base_oter_id = oter.id().str();
     for( const std::string &suffix : suffixes ) {
         if( string_ends_with( base_oter_id, suffix ) ) {
             base_oter_id = base_oter_id.substr( 0, base_oter_id.size() - suffix.size() );
         }
     }
     return base_oter_id;
 }
References int_id< T >::id(), string_id< T >::str(), string_ends_with(), and suffixes.
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_at_om_location(), and conditional_fun::anonymous_namespace{condition.cpp}::f_near_om_location().
rotate_internal()
static om_direction::type rotate_internal (om_direction::type dir, int step) static
Definition at line 6469 of file overmap.cpp.
 {
     if( dir == om_direction::type::invalid ) {
         debugmsg( "Can't rotate an invalid overmap rotation." );
         return dir;
     }
     step = step % om_direction::size;
     return static_cast<om_direction::type>( ( static_cast<int>( dir ) + step ) % om_direction::size );
 }
References debugmsg, om_direction::invalid, and om_direction::size.
Referenced by om_direction::add(), om_direction::opposite(), om_direction::turn_left(), and om_direction::turn_right().
set_oter_ids()
static void set_oter_ids () static
Definition at line 427 of file overmap.cpp.
 {
     ot_null         = oter_str_id::NULL_ID();
 }
References string_id< oter_t >::NULL_ID(), and ot_null.
Referenced by overmap_terrains::finalize().
straight_path()
static pf::directed_path<point_om_omt> straight_path (const point_om_omt & source, om_direction::type dir, size_t len) static
Definition at line 6006 of file overmap.cpp.
 {
     pf::directed_path<point_om_omt> res;
     if( len == 0 ) {
         return res;
     }
     point_om_omt p = source;
     res.nodes.reserve( len );
     for( size_t i = 0; i + 1 < len; ++i ) {
         res.nodes.emplace_back( p, dir );
         p += om_direction::displace( dir );
     }
     res.nodes.emplace_back( p, om_direction::type::invalid );
     return res;
 }
References om_direction::displace(), om_direction::invalid, and pf::directed_path< Point >::nodes.
Referenced by overmap::lay_out_street().
Variable Documentation
BUILDINGCHANCE
constexpr int BUILDINGCHANCE = 4 static constexpr
Definition at line 142 of file overmap.cpp.
Referenced by overmap::build_city_street().
GROUP_NEMESIS
const mongroup_id GROUP_NEMESIS("GROUP_NEMESIS") ("GROUP_NEMESIS") static
Referenced by overmap::place_nemesis().
GROUP_OCEAN_DEEP
const mongroup_id GROUP_OCEAN_DEEP("GROUP_OCEAN_DEEP") ("GROUP_OCEAN_DEEP") static
Referenced by overmap::place_mongroups().
GROUP_OCEAN_SHORE
const mongroup_id GROUP_OCEAN_SHORE("GROUP_OCEAN_SHORE") ("GROUP_OCEAN_SHORE") static
Referenced by overmap::place_mongroups().
GROUP_RIVER
const mongroup_id GROUP_RIVER("GROUP_RIVER") ("GROUP_RIVER") static
Referenced by overmap::place_mongroups().
GROUP_SUBWAY_CITY
const mongroup_id GROUP_SUBWAY_CITY("GROUP_SUBWAY_CITY") ("GROUP_SUBWAY_CITY") static
Referenced by overmap::generate_sub().
GROUP_SWAMP
const mongroup_id GROUP_SWAMP("GROUP_SWAMP") ("GROUP_SWAMP") static
Referenced by overmap::place_mongroups().
GROUP_ZOMBIE
const mongroup_id GROUP_ZOMBIE("GROUP_ZOMBIE") ("GROUP_ZOMBIE") static
Referenced by overmap::move_hordes(), and overmap::place_mongroups().
MAX_GOO_SIZE
constexpr int MAX_GOO_SIZE = 2 static constexpr
Definition at line 144 of file overmap.cpp.
Referenced by overmap::generate_sub().
MIN_GOO_SIZE
constexpr int MIN_GOO_SIZE = 1 static constexpr
Definition at line 143 of file overmap.cpp.
Referenced by overmap::generate_sub().
ot_null
oter_id ot_null static
Definition at line 150 of file overmap.cpp.
Referenced by oter_type_t::get_linear(), oter_type_t::get_rotated(), set_oter_ids(), overmap::ter(), and overmapbuffer::ter_existing().
oter_central_lab
const oter_str_id oter_central_lab("central_lab") ("central_lab") static
Referenced by overmap::generate_sub().
oter_central_lab_core
const oter_str_id oter_central_lab_core("central_lab_core") ("central_lab_core") static
Referenced by overmap::generate_sub().
oter_central_lab_train_depot
const oter_str_id oter_central_lab_train_depot("central_lab_train_depot") ("central_lab_train_depot") static
Referenced by overmap::generate_sub().
oter_empty_rock
const oter_str_id oter_empty_rock("empty_rock") ("empty_rock") static
Referenced by overmap::generate_over(), and overmap::generate_sub().
oter_field
const oter_str_id oter_field("field") ("field") static
Referenced by overmap::generate_over(), and overmap::generate_sub().
oter_forest
const oter_str_id oter_forest("forest") ("forest") static
Referenced by overmap::generate_over(), overmap::move_hordes(), overmap::place_forest_trails(), and overmap::place_forests().
oter_forest_thick
const oter_str_id oter_forest_thick("forest_thick") ("forest_thick") static
Referenced by overmap::generate_over(), overmap::move_hordes(), overmap::place_forest_trails(), and overmap::place_forests().
oter_forest_water
const oter_str_id oter_forest_water("forest_water") ("forest_water") static
Referenced by overmap::generate_over(), overmap::good_river(), overmap::move_hordes(), overmap::place_forest_trails(), overmap::place_mongroups(), and overmap::place_swamps().
oter_ice_lab
const oter_str_id oter_ice_lab("ice_lab") ("ice_lab") static
Referenced by overmap::generate_sub().
oter_ice_lab_core
const oter_str_id oter_ice_lab_core("ice_lab_core") ("ice_lab_core") static
Referenced by overmap::generate_sub().
oter_id_migrations
std::map<std::string, std::string> oter_id_migrations static
Definition at line 3944 of file overmap.cpp.
Referenced by overmap::get_or_migrate_oter(), overmap::is_oter_id_obsolete(), overmap::load_oter_id_migration(), overmap::migrate_oter_ids(), overmap::reset_oter_id_migrations(), overmap::unserialize(), and overmap::unserialize_omap().
oter_lab
const oter_str_id oter_lab("lab") ("lab") static
Referenced by overmap::generate_sub().
oter_lab_core
const oter_str_id oter_lab_core("lab_core") ("lab_core") static
Referenced by overmap::generate_sub().
oter_lab_escape_cells
const oter_str_id oter_lab_escape_cells("lab_escape_cells") ("lab_escape_cells") static
Referenced by overmap::build_lab().
oter_lab_escape_entrance
const oter_str_id oter_lab_escape_entrance("lab_escape_entrance") ("lab_escape_entrance") static
Referenced by overmap::build_lab().
oter_lab_train_depot
const oter_str_id oter_lab_train_depot("lab_train_depot") ("lab_train_depot") static
Referenced by overmap::generate_sub().
oter_open_air
const oter_str_id oter_open_air("open_air") ("open_air") static
Referenced by overmap::generate_sub().
oter_river_c_not_ne
const oter_str_id oter_river_c_not_ne("river_c_not_ne") ("river_c_not_ne") static
Referenced by overmap::good_river().
oter_river_c_not_nw
const oter_str_id oter_river_c_not_nw("river_c_not_nw") ("river_c_not_nw") static
Referenced by overmap::good_river().
oter_river_c_not_se
const oter_str_id oter_river_c_not_se("river_c_not_se") ("river_c_not_se") static
Referenced by overmap::good_river().
oter_river_c_not_sw
const oter_str_id oter_river_c_not_sw("river_c_not_sw") ("river_c_not_sw") static
Referenced by overmap::good_river().
oter_river_center
const oter_str_id oter_river_center("river_center") ("river_center") static
Referenced by overmap::good_river(), overmap::move_hordes(), overmap::place_river(), and overmap::place_rivers().
oter_river_east
const oter_str_id oter_river_east("river_east") ("river_east") static
Referenced by overmap::good_river().
oter_river_ne
const oter_str_id oter_river_ne("river_ne") ("river_ne") static
Referenced by overmap::good_river().
oter_river_north
const oter_str_id oter_river_north("river_north") ("river_north") static
Referenced by overmap::good_river().
oter_river_nw
const oter_str_id oter_river_nw("river_nw") ("river_nw") static
Referenced by overmap::good_river().
oter_river_se
const oter_str_id oter_river_se("river_se") ("river_se") static
Referenced by overmap::good_river().
oter_river_south
const oter_str_id oter_river_south("river_south") ("river_south") static
Referenced by overmap::good_river().
oter_river_sw
const oter_str_id oter_river_sw("river_sw") ("river_sw") static
Referenced by overmap::good_river().
oter_river_west
const oter_str_id oter_river_west("river_west") ("river_west") static
Referenced by overmap::good_river().
oter_road_nesw
const oter_str_id oter_road_nesw("road_nesw") ("road_nesw") static
Referenced by overmap::place_cities().
oter_road_nesw_manhole
const oter_str_id oter_road_nesw_manhole("road_nesw_manhole") ("road_nesw_manhole") static
Referenced by overmap::build_city_street(), and oter_t::has_connection().
oter_sewer_end_north
const oter_str_id oter_sewer_end_north("sewer_end_north") ("sewer_end_north") static
Referenced by overmap::generate_sub().
oter_sewer_isolated
const oter_str_id oter_sewer_isolated("sewer_isolated") ("sewer_isolated") static
Referenced by overmap::generate_sub().
oter_sewer_sub_station
const oter_str_id oter_sewer_sub_station("sewer_sub_station") ("sewer_sub_station") static
Referenced by overmap::generate_sub().
oter_solid_earth
const oter_str_id oter_solid_earth("solid_earth") ("solid_earth") static
Referenced by overmap::generate_over(), and overmap::generate_sub().
oter_subway_end_north
const oter_str_id oter_subway_end_north("subway_end_north") ("subway_end_north") static
Referenced by overmap::generate_sub().
oter_subway_isolated
const oter_str_id oter_subway_isolated("subway_isolated") ("subway_isolated") static
Referenced by overmap::generate_sub().
oter_type_ants_queen
const oter_type_str_id oter_type_ants_queen("ants_queen") ("ants_queen") static
Referenced by overmap::build_lab().
oter_type_bridge
const oter_type_str_id oter_type_bridge("bridge") ("bridge") static
Referenced by overmap::generate_over().
oter_type_central_lab_core
const oter_type_str_id oter_type_central_lab_core("central_lab_core") ("central_lab_core") static
Referenced by overmap::generate_sub().
oter_type_central_lab_stairs
const oter_type_str_id oter_type_central_lab_stairs("central_lab_stairs") ("central_lab_stairs") static
Referenced by overmap::generate_sub().
oter_type_empty_rock
const oter_type_str_id oter_type_empty_rock("empty_rock") ("empty_rock") static
Referenced by overmap::generate_sub().
oter_type_field
const oter_type_str_id oter_type_field("field") ("field") static
Referenced by overmap::generate_sub().
oter_type_forest
const oter_type_str_id oter_type_forest("forest") ("forest") static
Referenced by overmap::generate_sub().
oter_type_forest_thick
const oter_type_str_id oter_type_forest_thick("forest_thick") ("forest_thick") static
Referenced by overmap::generate_sub().
oter_type_forest_water
const oter_type_str_id oter_type_forest_water("forest_water") ("forest_water") static
Referenced by overmap::generate_sub().
oter_type_ice_lab_core
const oter_type_str_id oter_type_ice_lab_core("ice_lab_core") ("ice_lab_core") static
Referenced by overmap::generate_sub().
oter_type_ice_lab_stairs
const oter_type_str_id oter_type_ice_lab_stairs("ice_lab_stairs") ("ice_lab_stairs") static
Referenced by overmap::generate_sub().
oter_type_lab_core
const oter_type_str_id oter_type_lab_core("lab_core") ("lab_core") static
Referenced by overmap::generate_sub().
oter_type_lab_stairs
const oter_type_str_id oter_type_lab_stairs("lab_stairs") ("lab_stairs") static
Referenced by overmap::generate_sub().
oter_type_microlab_sub_connector
const oter_type_str_id oter_type_microlab_sub_connector("microlab_sub_connector") ("microlab_sub_connector") static
Referenced by overmap::generate_sub().
oter_type_railroad_bridge
const oter_type_str_id oter_type_railroad_bridge("railroad_bridge") ("railroad_bridge") static
Referenced by overmap::generate_over().
oter_type_road
const oter_type_str_id oter_type_road("road") ("road") static
Referenced by overmap::lay_out_street(), and overmap::place_mongroups().
oter_type_road_nesw_manhole
const oter_type_str_id oter_type_road_nesw_manhole("road_nesw_manhole") ("road_nesw_manhole") static
Referenced by overmap::generate_sub().
oter_type_sewer_connector
const oter_type_str_id oter_type_sewer_connector("sewer_connector") ("sewer_connector") static
Referenced by overmap::generate_sub().
oter_type_slimepit_bottom
const oter_type_str_id oter_type_slimepit_bottom("slimepit_bottom") ("slimepit_bottom") static
Referenced by overmap::generate_sub().
oter_type_slimepit_down
const oter_type_str_id oter_type_slimepit_down("slimepit_down") ("slimepit_down") static
Referenced by overmap::generate_sub().
oter_type_solid_earth
const oter_type_str_id oter_type_solid_earth("solid_earth") ("solid_earth") static
Referenced by overmap::generate_sub().
oter_type_sub_station
const oter_type_str_id oter_type_sub_station("sub_station") ("sub_station") static
Referenced by overmap::generate_sub().
oter_underground_sub_station
const oter_str_id oter_underground_sub_station("underground_sub_station") ("underground_sub_station") static
Referenced by overmap::generate_sub().
overmap_location_land
const overmap_location_id overmap_location_land("land") ("land") static
Referenced by overmap_specials::create_building_from().
overmap_location_swamp
const overmap_location_id overmap_location_swamp("swamp") ("swamp") static
Referenced by overmap_specials::create_building_from().
radio_type_names
std::map<radio_type, std::string> radio_type_names
Initial value:
=
{{ {radio_type::MESSAGE_BROADCAST, "broadcast"}, {radio_type::WEATHER_RADIO, "weather"} }}
Definition at line 340 of file overmap.cpp.
Referenced by overmap::serialize(), and overmap::unserialize().
region_settings_map
t_regional_settings_map region_settings_map
Definition at line 303 of file overmap.cpp.
Referenced by check_region_settings(), MapExtras::debug_spawn_test(), overmap_terrains::finalize(), regional_settings::finalize(), map::generate(), load_region_overlay(), load_region_settings(), overmap::overmap(), reset_region_settings(), and overmap::unserialize().
species_ZOMBIE
const species_id species_ZOMBIE("ZOMBIE") ("ZOMBIE") static
Referenced by overmap::move_hordes().
suffixes
const std::array<std::string, 4> suffixes = {{ "_north", "_west", "_south", "_east" }} static
Definition at line 7387 of file overmap.cpp.
Referenced by oter_get_rotation(), oter_get_rotation_string(), and oter_no_dir().