Cataclysm DDA: src/panels.cpp File Reference
panels.cpp File Reference
#include "panels.h"
#include <algorithm>
#include <cstddef>
#include <iosfwd>
#include <iterator>
#include <memory>
#include <string>
#include <utility>
#include "avatar.h"
#include "cached_options.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "color.h"
#include "cursesdef.h"
#include "display.h"
#include "debug.h"
#include "game.h"
#include "game_constants.h"
#include "game_ui.h"
#include "input_context.h"
#include "json.h"
#include "map.h"
#include "messages.h"
#include "omdata.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "path_info.h"
#include "point.h"
#include "string_formatter.h"
#include "type_id.h"
#include "ui_manager.h"
#include "widget.h"
Functions
static std::string trunc_ellipse (const std::string &input, unsigned int trunc)
static int get_wgt_height (const widget_id &wgt)
static void decorate_panel (const std::string_view name, const catacurses::window &w)
static void draw_messages (const draw_args &args)
bool default_render ()
static std::vector< window_panel > initialize_default_custom_panels (const widget &wgt)
static std::map< std::string, panel_layout > initialize_default_panel_layouts ()
static void dummy_wgt_render (const widget_id &wid, int width)
static void draw_border_win (catacurses::window &w, const std::vector< int > &column_widths, int popup_height)
static void draw_left_win (catacurses::window &w, const std::map< size_t, size_t > &row_indices, const std::vector< window_panel > &panels, size_t source_index, size_t current_row, size_t source_row, bool cur_col, bool swapping, int width, int height, int start)
static void draw_right_win (catacurses::window &w, const std::map< std::string, panel_layout > &layouts, const std::string &current_layout_id, size_t current_row, bool cur_col)
static void draw_center_win (catacurses::window &w, int col_width, const input_context &ctxt, const widget &sidebar, const std::map< size_t, size_t > &row_indices, const std::vector< window_panel > &panels, size_t current_row, bool left_panel)
Function Documentation
decorate_panel()
static void decorate_panel (const std::string_view name, const catacurses::window & w) static
Definition at line 261 of file panels.cpp.
 {
     werase( w );
     draw_border( w );
     static const char *title_prefix = " ";
     const std::string_view title = name;
     static const char *title_suffix = " ";
     static const std::string full_title = string_format( "%s%s%s",
                                           title_prefix, title, title_suffix );
     const int start_pos = center_text_pos( full_title, 0, getmaxx( w ) - 1 );
     mvwprintz( w, point( start_pos, 0 ), c_white, title_prefix );
     wprintz( w, c_light_red, title );
     wprintz( w, c_white, title_suffix );
 }
References c_light_red, c_white, center_text_pos(), draw_border(), catacurses::getmaxx(), mvwprintz(), om_direction::name(), string_format(), music::title, catacurses::werase(), and wprintz().
Referenced by draw_border_win().
default_render()
bool default_render ()
Definition at line 303 of file panels.cpp.
 {
     return true;
 }
Referenced by initialize_default_custom_panels().
draw_border_win()
static void draw_border_win (catacurses::window & w, const std::vector< int > & column_widths, int popup_height) static
Definition at line 537 of file panels.cpp.
 {
     werase( w );
     decorate_panel( _( "Sidebar options" ), w );
     // Draw vertical separators
     mvwvline( w, point( column_widths[0] + 1, 1 ), 0, popup_height - 2 );
     mvwvline( w, point( column_widths[0] + column_widths[1] + 2, 1 ), 0, popup_height - 2 );
     wnoutrefresh( w );
 }
References _, decorate_panel(), catacurses::mvwvline(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by panel_manager::show_adm().
draw_center_win()
static void draw_center_win (catacurses::window & w, int col_width, const input_context & ctxt, const widget & sidebar, const std::map< size_t, size_t > & row_indices, const std::vector< window_panel > & panels, size_t current_row, bool left_panel) static
Definition at line 610 of file panels.cpp.
 {
     werase( w );
     // NOLINTNEXTLINE(cata-use-named-point-constants)
     mvwprintz( w, point( 1, 0 ), c_light_green, trunc_ellipse( ctxt.get_desc( "TOGGLE_PANEL" ),
                col_width - 1 ) + ":" );
     // NOLINTNEXTLINE(cata-use-named-point-constants)
     mvwprintz( w, point( 1, 1 ), c_white, _( "Toggle panels on/off" ) );
     mvwprintz( w, point( 1, 2 ), c_light_green, trunc_ellipse( ctxt.get_desc( "MOVE_PANEL" ),
                col_width - 1 ) + ":" );
     mvwprintz( w, point( 1, 3 ), c_white, _( "Change display order" ) );
     mvwprintz( w, point( 1, 4 ), c_light_green, trunc_ellipse( ctxt.get_desc( "QUIT" ),
                col_width - 1 ) + ":" );
     mvwprintz( w, point( 1, 5 ), c_white, _( "Exit" ) );
     if( left_panel ) {
         const widget_id current_widget = panels[row_indices.at( current_row )].get_widget();
         for( const widget &wgt : widget::get_all() ) {
             if( wgt.getId() == current_widget ) {
                 fold_and_print( w, point( 1, 7 ), col_width - 2, c_white, _( wgt._description ) );
                 break;
             }
         }
     } else {
         fold_and_print( w, point( 1, 7 ), col_width - 2, c_white, _( sidebar._description ) );
     }
     wnoutrefresh( w );
 }
References _, widget::_description, c_light_green, c_white, fold_and_print(), widget::get_all(), input_context::get_desc(), mvwprintz(), trunc_ellipse(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by panel_manager::show_adm().
draw_left_win()
static void draw_left_win (catacurses::window & w, const std::map< size_t, size_t > & row_indices, const std::vector< window_panel > & panels, size_t source_index, size_t current_row, size_t source_row, bool cur_col, bool swapping, int width, int height, int start) static
Definition at line 548 of file panels.cpp.
 {
     werase( w );
     for( std::pair<size_t, size_t> row_indx : row_indices ) {
         if( row_indx.first < static_cast<size_t>( start ) ) {
             continue;
         }
         const size_t row = row_indx.first - start;
         const std::string name = panels[row_indx.second].get_name();
         if( swapping && source_index == row_indx.second ) {
             mvwprintz( w, point( 4, current_row - start ), c_yellow, name );
         } else {
             int offset = 0;
             if( !swapping ) {
                 offset = 0;
             } else if( current_row > source_row && row_indx.first > source_row &&
                        row_indx.first <= current_row ) {
                 offset = -1;
             } else if( current_row < source_row && row_indx.first < source_row &&
                        row_indx.first >= current_row ) {
                 offset = 1;
             }
             const nc_color toggle_color = panels[row_indx.second].toggle ? c_white : c_dark_gray;
             mvwprintz( w, point( 3, row + offset ), toggle_color, name );
         }
     }
     if( cur_col ) {
         mvwprintz( w, point( 0, current_row - start ), c_yellow, ">>" );
     }
     scrollbar()
     .offset_x( width - 1 )
     .offset_y( 0 )
     .content_size( row_indices.size() )
     .viewport_pos( start )
     .viewport_size( height )
     .apply( w );
     wnoutrefresh( w );
 }
References scrollbar::apply(), c_dark_gray, c_white, c_yellow, scrollbar::content_size(), mvwprintz(), om_direction::name(), scrollbar::offset_x(), scrollbar::offset_y(), scrollbar::viewport_pos(), scrollbar::viewport_size(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by panel_manager::show_adm().
draw_messages()
static void draw_messages (const draw_args & args) static
Definition at line 277 of file panels.cpp.
 {
     const catacurses::window &w = args._win;
     werase( w );
     int line = getmaxy( w ) - 1;
     int maxlength = getmaxx( w );
     Messages::display_messages( w, 1, 0 /*topline*/, maxlength - 1, line );
     wnoutrefresh( w );
 }
References draw_args::_win, Messages::display_messages(), catacurses::getmaxx(), catacurses::getmaxy(), line(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by initialize_default_custom_panels().
draw_right_win()
static void draw_right_win (catacurses::window & w, const std::map< std::string, panel_layout > & layouts, const std::string & current_layout_id, size_t current_row, bool cur_col) static
Definition at line 592 of file panels.cpp.
 {
     werase( w );
     size_t i = 0;
     for( const auto &layout : layouts ) {
         mvwprintz( w, point( 3, i ), current_layout_id == layout.first ? c_light_blue : c_white,
                    layout.second.name() );
         i++;
     }
     if( cur_col ) {
         mvwprintz( w, point( 0, current_row ), c_yellow, ">>" );
     }
     wnoutrefresh( w );
 }
References c_light_blue, c_white, c_yellow, mvwprintz(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by panel_manager::show_adm().
dummy_wgt_render()
static void dummy_wgt_render (const widget_id & wid, int width) static
Definition at line 523 of file panels.cpp.
 {
     if( wid.is_null() || !wid.is_valid() ) {
         return;
     }
     if( wid->_style == "sidebar" ) {
         for( const widget_id &subw : wid->_widgets ) {
             dummy_wgt_render( subw, width );
         }
     }
     widget w = wid.obj();
     w.layout( get_avatar(), width, 0, w.has_flag( "W_NO_PADDING" ) );
 }
References widget::_style, widget::_widgets, get_avatar(), widget::has_flag(), string_id< T >::is_null(), string_id< T >::is_valid(), widget::layout(), and string_id< T >::obj().
Referenced by panel_manager::show_adm().
get_wgt_height()
static int get_wgt_height (const widget_id & wgt) static
Definition at line 84 of file panels.cpp.
 {
     if( wgt->_widgets.empty() || wgt->_arrange == "columns" || wgt->_arrange == "minimum_columns" ) {
         return wgt->_height > 0 ? wgt->_height : 1;
     }
     int h = 0;
     for( const widget_id &w : wgt->_widgets ) {
         h += get_wgt_height( w );
     }
     return h;
 }
References widget::_arrange, widget::_height, and widget::_widgets.
Referenced by window_panel::get_height().
initialize_default_custom_panels()
static std::vector<window_panel> initialize_default_custom_panels (const widget & wgt) static
Definition at line 309 of file panels.cpp.
 {
     std::vector<window_panel> ret;
     // Use defined width, or at least 16
     const int width = std::max( wgt._width, 16 );
     // Add window panel for each child widget
     for( const widget_id &row_wid : wgt._widgets ) {
         widget row_widget = row_wid.obj();
         ret.emplace_back( row_widget.get_window_panel( width ) );
     }
     // Add compass, message log, and map to fill remaining space
     // TODO: Make these into proper widgets
     ret.emplace_back( draw_messages, "Log", to_translation( "Log" ),
                       -2, width, true );
 #if defined(TILES)
     ret.emplace_back( draw_mminimap, "Map", to_translation( "Map" ),
                       -1, width, true, default_render, true );
 #endif // TILES
     return ret;
 }
References widget::_widgets, widget::_width, default_render(), draw_messages(), widget::get_window_panel(), max(), string_id< T >::obj(), cata::hash64_detail::ret, and to_translation().
Referenced by initialize_default_panel_layouts().
initialize_default_panel_layouts()
static std::map<std::string, panel_layout> initialize_default_panel_layouts () static
Definition at line 334 of file panels.cpp.
 {
     std::map<std::string, panel_layout> ret;
     // Add panel layout for each "sidebar" widget
     for( const widget &wgt : widget::get_all() ) {
         if( wgt._style == "sidebar" ) {
             ret.emplace( wgt.getId().str(),
                          panel_layout( wgt._label, initialize_default_custom_panels( wgt ) ) );
         }
     }
     return ret;
 }
References widget::get_all(), initialize_default_custom_panels(), and cata::hash64_detail::ret.
Referenced by panel_manager::init().
trunc_ellipse()
static std::string trunc_ellipse (const std::string & input, unsigned int trunc) static
Definition at line 76 of file panels.cpp.
 {
     if( utf8_width( input ) > static_cast<int>( trunc ) ) {
         return utf8_truncate( input, trunc - 1 ) + "";
     }
     return input;
 }
References trunc(), utf8_truncate(), and utf8_width().
Referenced by draw_center_win().