Cataclysm DDA: src/past_games_info.cpp File Reference
past_games_info.cpp File Reference
#include "past_games_info.h"
#include <algorithm>
#include <map>
#include <stdexcept>
#include <string>
#include <vector>
#include <unordered_set>
#include <utility>
#include "achievement.h"
#include "cata_utility.h"
#include "debug.h"
#include "event.h"
#include "filesystem.h"
#include "input.h"
#include "json_loader.h"
#include "memorial_logger.h"
#include "output.h"
#include "path_info.h"
#include "popup.h"
#include "stats_tracker.h"
#include "string_formatter.h"
#include "translations.h"
#include "ui_manager.h"
Classes
class too_old_memorial_file_error
Functions
static void no_op (const achievement *, bool)
const past_games_info & get_past_games ()
void clear_past_games ()
Variables
static past_games_info past_games
Function Documentation
clear_past_games()
void clear_past_games ()
Definition at line 188 of file past_games_info.cpp.
 {
     past_games.clear();
 }
References past_games_info::clear(), and past_games.
Referenced by memorial_logger::write_json_memorial().
get_past_games()
const past_games_info& get_past_games ()
Definition at line 182 of file past_games_info.cpp.
 {
     past_games.ensure_loaded();
     return past_games;
 }
References past_games_info::ensure_loaded(), and past_games.
Referenced by past_achievements_info::avatars_completed(), get_achievements_text(), and past_achievements_info::load().
no_op()
static void no_op (const achievement * , bool) static
Definition at line 27 of file past_games_info.cpp.
 {}
Referenced by past_game_info::past_game_info().
Variable Documentation
past_games
past_games_info past_games static
Definition at line 82 of file past_games_info.cpp.
Referenced by clear_past_games(), and get_past_games().