Cataclysm DDA: src/past_games_info.h File Reference
past_games_info.h File Reference
#include <iosfwd>
#include <memory>
#include <unordered_map>
#include <vector>
#include "achievement.h"
#include "cata_variant.h"
#include "memorial_logger.h"
#include "stats_tracker.h"
#include "type_id.h"
Classes
class past_game_info
struct achievement_completion_info
class past_games_info
Macros
#define CATA_SRC_PAST_GAMES_INFO_H
Functions
const past_games_info & get_past_games ()
void clear_past_games ()
Macro Definition Documentation
CATA_SRC_PAST_GAMES_INFO_H
#define CATA_SRC_PAST_GAMES_INFO_H
Definition at line 3 of file past_games_info.h.
Function Documentation
clear_past_games()
void clear_past_games ()
Definition at line 188 of file past_games_info.cpp.
 {
     past_games.clear();
 }
References past_games_info::clear(), and past_games.
Referenced by memorial_logger::write_json_memorial().
get_past_games()
const past_games_info& get_past_games ()
Definition at line 182 of file past_games_info.cpp.
 {
     past_games.ensure_loaded();
     return past_games;
 }
References past_games_info::ensure_loaded(), and past_games.
Referenced by past_achievements_info::avatars_completed(), get_achievements_text(), and past_achievements_info::load().