Cataclysm DDA: src/past_achievements_info.h File Reference
past_achievements_info.h File Reference
#include <map>
#include "achievement.h"
Classes
class past_achievements_info
Macros
#define CATA_SRC_PAST_ACHIEVEMENTS_INFO_H
Functions
const past_achievements_info & get_past_achievements ()
void clear_past_achievements ()
Macro Definition Documentation
CATA_SRC_PAST_ACHIEVEMENTS_INFO_H
#define CATA_SRC_PAST_ACHIEVEMENTS_INFO_H
Definition at line 3 of file past_achievements_info.h.
Function Documentation
clear_past_achievements()
void clear_past_achievements ()
Definition at line 83 of file past_achievements_info.cpp.
 {
     past_achievements.clear();
 }
References past_achievements_info::clear(), and past_achievements.
Referenced by achievements_tracker::write_json_achievements().
get_past_achievements()
const past_achievements_info& get_past_achievements ()
Definition at line 77 of file past_achievements_info.cpp.
 {
     past_achievements.load();
     return past_achievements;
 }
References past_achievements_info::load(), and past_achievements.
Referenced by achievement_attained(), profession::can_pick(), scenario::can_pick(), and achievement_tracker::ui_text().