Cataclysm DDA: src/path_info.h File Reference
path_info.h File Reference
#include "cata_path.h"
#include <string>
Namespaces
PATH_INFO
Macros
#define CATA_SRC_PATH_INFO_H
Functions
enum holiday int const std::string SAVE_MASTER ("master.gsav")
const std::string SAVE_ARTIFACTS ("artifacts.gsav")
const std::string SAVE_EXTENSION (".sav")
const std::string SAVE_EXTENSION_LOG (".log")
const std::string SAVE_EXTENSION_WEATHER (".weather")
const std::string SAVE_EXTENSION_SHORTCUTS (".shortcuts")
void PATH_INFO::init_base_path (const std::string &path)
void PATH_INFO::init_user_dir (std::string dir)
void PATH_INFO::set_standard_filenames ()
std::string PATH_INFO::base_path ()
std::string PATH_INFO::cache_dir ()
std::string PATH_INFO::config_dir ()
std::string PATH_INFO::datadir ()
std::string PATH_INFO::debug ()
std::string PATH_INFO::defaulttilejson ()
std::string PATH_INFO::defaultlayeringjson ()
std::string PATH_INFO::defaulttilepng ()
std::string PATH_INFO::fontdir ()
std::string PATH_INFO::user_font ()
std::string PATH_INFO::graveyarddir ()
std::string PATH_INFO::keymap ()
std::string PATH_INFO::memorialdir ()
std::string PATH_INFO::achievementdir ()
std::string PATH_INFO::player_base_save_path ()
std::string PATH_INFO::savedir ()
std::string PATH_INFO::sokoban ()
std::string PATH_INFO::templatedir ()
std::string PATH_INFO::user_dir ()
std::string PATH_INFO::user_moddir ()
std::string PATH_INFO::world_base_save_path ()
std::string PATH_INFO::worldoptions ()
std::string PATH_INFO::crash ()
std::string PATH_INFO::tileset_conf ()
std::string PATH_INFO::langdir ()
std::string PATH_INFO::lang_file ()
std::string PATH_INFO::soundpack_conf ()
std::string PATH_INFO::credits ()
std::string PATH_INFO::motd ()
std::string PATH_INFO::title (holiday current_holiday)
cata_path PATH_INFO::autopickup ()
cata_path PATH_INFO::autonote ()
cata_path PATH_INFO::base_colors ()
cata_path PATH_INFO::base_path_path ()
cata_path PATH_INFO::color_templates ()
cata_path PATH_INFO::color_themes ()
cata_path PATH_INFO::colors ()
cata_path PATH_INFO::config_dir_path ()
cata_path PATH_INFO::custom_colors ()
cata_path PATH_INFO::data_sound ()
cata_path PATH_INFO::datadir_path ()
cata_path PATH_INFO::defaultsounddir ()
cata_path PATH_INFO::fontdata ()
cata_path PATH_INFO::gfxdir ()
cata_path PATH_INFO::help ()
cata_path PATH_INFO::jsondir ()
cata_path PATH_INFO::keybindings ()
cata_path PATH_INFO::keybindings_vehicle ()
cata_path PATH_INFO::langdir_path ()
cata_path PATH_INFO::lastworld ()
cata_path PATH_INFO::legacy_fontdata ()
cata_path PATH_INFO::memorialdir_path ()
cata_path PATH_INFO::achievementdir_path ()
cata_path PATH_INFO::moddir ()
cata_path PATH_INFO::mods_dev_default ()
cata_path PATH_INFO::mods_user_default ()
cata_path PATH_INFO::mods_replacements ()
cata_path PATH_INFO::names ()
cata_path PATH_INFO::options ()
cata_path PATH_INFO::panel_options ()
cata_path PATH_INFO::player_base_save_path_path ()
cata_path PATH_INFO::pocket_presets ()
cata_path PATH_INFO::safemode ()
cata_path PATH_INFO::savedir_path ()
cata_path PATH_INFO::templatedir_path ()
cata_path PATH_INFO::user_dir_path ()
cata_path PATH_INFO::user_gfx ()
cata_path PATH_INFO::user_keybindings ()
cata_path PATH_INFO::user_moddir_path ()
cata_path PATH_INFO::user_sound ()
cata_path PATH_INFO::world_base_save_path_path ()
void PATH_INFO::set_datadir (const std::string &datadir)
void PATH_INFO::set_config_dir (const std::string &config_dir)
void PATH_INFO::set_savedir (const std::string &savedir)
void PATH_INFO::set_memorialdir (const std::string &memorialdir)
void PATH_INFO::set_options (const std::string &options)
void PATH_INFO::set_keymap (const std::string &keymap)
void PATH_INFO::set_autopickup (const std::string &autopickup)
void PATH_INFO::set_motd (const std::string &motd)
Macro Definition Documentation
CATA_SRC_PATH_INFO_H
#define CATA_SRC_PATH_INFO_H
Definition at line 3 of file path_info.h.
Function Documentation
SAVE_ARTIFACTS()
const std::string SAVE_ARTIFACTS ("artifacts.gsav")
SAVE_EXTENSION()
const std::string SAVE_EXTENSION (".sav")
Referenced by worldfactory::init(), game::load(), and game::save_player_data().
SAVE_EXTENSION_LOG()
const std::string SAVE_EXTENSION_LOG (".log")
Referenced by game::load(), and game::save_player_data().
SAVE_EXTENSION_SHORTCUTS()
const std::string SAVE_EXTENSION_SHORTCUTS (".shortcuts")
Referenced by game::load(), and game::save_player_data().
SAVE_EXTENSION_WEATHER()
const std::string SAVE_EXTENSION_WEATHER (".weather")
SAVE_MASTER()
enum holiday int const std::string SAVE_MASTER ("master.gsav") strong
Referenced by worldfactory::init(), game::load_master(), game::save_factions_missions_npcs(), game::serialize_master(), and game::unserialize_master().