Cataclysm DDA: src/pathfinding.cpp File Reference
pathfinding.cpp File Reference
#include "pathfinding.h"
#include <algorithm>
#include <array>
#include <cstdlib>
#include <iterator>
#include <memory>
#include <optional>
#include <queue>
#include <set>
#include <utility>
#include <vector>
#include "cata_utility.h"
#include "coordinates.h"
#include "debug.h"
#include "game.h"
#include "gates.h"
#include "line.h"
#include "map.h"
#include "mapdata.h"
#include "point.h"
#include "submap.h"
#include "trap.h"
#include "type_id.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vpart_position.h"
Classes
struct path_data_layer
struct pathfinder
Functions
static constexpr int flat_index (const point &p)
static bool vertical_move_destination (const map &m, ter_furn_flag flag, tripoint &t)
template<class Set1 , class Set2 >
static bool is_disjoint (const Set1 &set1, const Set2 &set2)
Variables
static pathfinder pf
Function Documentation
flat_index()
static constexpr int flat_index (const point & p) static constexpr
Definition at line 31 of file pathfinding.cpp.
 {
     return ( p.x * MAPSIZE_Y ) + p.y;
 }
References MAPSIZE_Y, point::x, and point::y.
Referenced by pathfinder::add_point(), pathfinder::close_point(), map::route(), pathfinder::unclose_point(), and overmap::unserialize().
is_disjoint()
template<class Set1 , class Set2 > static bool is_disjoint (const Set1 & set1, const Set2 & set2) static
Definition at line 137 of file pathfinding.cpp.
 {
     if( set1.empty() || set2.empty() ) {
         return true;
     }
     typename Set1::const_iterator it1 = set1.begin();
     typename Set1::const_iterator it1_end = set1.end();
     typename Set2::const_iterator it2 = set2.begin();
     typename Set2::const_iterator it2_end = set2.end();
     if( *set2.rbegin() < *it1 || *set1.rbegin() < *it2 ) {
         return true;
     }
     while( it1 != it1_end && it2 != it2_end ) {
         if( *it1 == *it2 ) {
             return false;
         }
         if( *it1 < *it2 ) {
             it1++;
         } else {
             it2++;
         }
     }
     return true;
 }
vertical_move_destination()
static bool vertical_move_destination (const map & m, ter_furn_flag flag, tripoint & t) static
Definition at line 121 of file pathfinding.cpp.
 {
     const pathfinding_cache &pf_cache = m.get_pathfinding_cache_ref( t.z );
     for( const point &p : closest_points_first( t.xy(), SEEX ) ) {
         if( pf_cache.special[p.x][p.y] & PF_UPDOWN ) {
             const tripoint t2( p, t.z );
             if( m.has_flag( flag, t2 ) ) {
                 t = t2;
                 return true;
             }
         }
     }
     return false;
 }
References closest_points_first(), map::get_pathfinding_cache_ref(), map::has_flag(), PF_UPDOWN, SEEX, pathfinding_cache::special, tripoint::xy(), and tripoint::z.
Referenced by map::route().
Variable Documentation
pf
pathfinder pf static
Definition at line 116 of file pathfinding.cpp.