Cataclysm DDA: src/pickup.cpp File Reference
pickup.cpp File Reference
#include "pickup.h"
#include <algorithm>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <utility>
#include <vector>
#include "activity_actor_definitions.h"
#include "auto_pickup.h"
#include "character.h"
#include "colony.h"
#include "debug.h"
#include "enums.h"
#include "game.h"
#include "input.h"
#include "input_context.h"
#include "item.h"
#include "item_location.h"
#include "item_stack.h"
#include "line.h"
#include "map.h"
#include "mapdata.h"
#include "messages.h"
#include "options.h"
#include "player_activity.h"
#include "point.h"
#include "popup.h"
#include "ret_val.h"
#include "string_formatter.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "units.h"
#include "units_utility.h"
Classes
struct pickup_count
Typedefs
using ItemCount = std::pair< item, int >
using PickupMap = std::map< std::string, ItemCount >
Enumerations
enum pickup_answer : int {
CANCEL = -1 , WIELD , SPILL , STASH ,
NUM_ANSWERS
}
Functions
static void show_pickup_message (const PickupMap &mapPickup)
static pickup_answer handle_problematic_pickup (const item &it, const std::string &explain)
static bool is_bulk_load (const Pickup::pick_info &lhs, const Pickup::pick_info &rhs)
static bool pick_one_up (item_location &loc, int quantity, bool &got_water, bool &got_gas, PickupMap &mapPickup, bool autopickup, bool &stash_successful, bool &got_frozen_liquid, Pickup::pick_info &info)
Variables
static const flag_id json_flag_SHREDDED ("SHREDDED")
static const zone_type_id zone_type_NO_AUTO_PICKUP ("NO_AUTO_PICKUP")
Typedef Documentation
ItemCount
using ItemCount = std::pair<item, int>
Definition at line 39 of file pickup.cpp.
PickupMap
using PickupMap = std::map<std::string, ItemCount>
Definition at line 40 of file pickup.cpp.
Enumeration Type Documentation
pickup_answer
enum pickup_answer : int
Enumerator
CANCEL
WIELD
SPILL
STASH
NUM_ANSWERS
Definition at line 67 of file pickup.cpp.
                    : int {
     CANCEL = -1,
     WIELD,
     SPILL,
     STASH,
     NUM_ANSWERS
 };
Function Documentation
handle_problematic_pickup()
static pickup_answer handle_problematic_pickup (const item & it, const std::string & explain) static
Definition at line 75 of file pickup.cpp.
 {
     Character &u = get_player_character();
     uilist amenu;
     amenu.text = explain;
     item empty_it( it );
     empty_it.get_contents().clear_items();
     bool can_pickup = u.can_stash( empty_it ) && u.can_pickWeight( empty_it );
     if( it.is_bucket_nonempty() ) {
         amenu.addentry( WIELD, true, 'w', _( "Wield %s" ), it.display_name() );
         amenu.addentry( SPILL, can_pickup, 's', _( "Spill contents of %s, then pick up %s" ),
                         it.tname(), it.display_name() );
     }
     amenu.query();
     int choice = amenu.ret;
     if( choice <= CANCEL || choice >= NUM_ANSWERS ) {
         return CANCEL;
     }
     return static_cast<pickup_answer>( choice );
 }
References _, uilist::addentry(), CANCEL, item_contents::clear_items(), item::display_name(), item::get_contents(), get_player_character(), item::is_bucket_nonempty(), NUM_ANSWERS, uilist::query(), uilist::ret, SPILL, uilist::text, item::tname(), u, and WIELD.
Referenced by pick_one_up().
is_bulk_load()
static bool is_bulk_load (const Pickup::pick_info & lhs, const Pickup::pick_info & rhs) static
Definition at line 146 of file pickup.cpp.
 {
     // Check if storage is the same
     if( lhs.dst && rhs.dst && lhs.dst->stacks_with( *rhs.dst ) &&
         lhs.dst.where() == item_location::type::container &&
         rhs.dst.where() == item_location::type::container &&
         lhs.dst.parent_item() == rhs.dst.parent_item() ) {
         // Check if source is the same
         if( lhs.src_type == rhs.src_type ) {
             switch( lhs.src_type ) {
                 case item_location::type::container:
                     return lhs.src_container == rhs.src_container;
                     break;
                 case item_location::type::map:
                 case item_location::type::vehicle:
                     return lhs.src_pos == rhs.src_pos;
                     break;
                 default:
                     break;
             }
         }
     }
     return false;
 }
References item_location::container, Pickup::pick_info::dst, item_location::map, item_location::parent_item(), Pickup::pick_info::src_container, Pickup::pick_info::src_pos, Pickup::pick_info::src_type, item::stacks_with(), item_location::vehicle, and item_location::where().
Referenced by pick_one_up().
pick_one_up()
static bool pick_one_up (item_location & loc, int quantity, bool & got_water, bool & got_gas, PickupMap & mapPickup, bool autopickup, bool & stash_successful, bool & got_frozen_liquid, Pickup::pick_info & info) static
Definition at line 172 of file pickup.cpp.
 {
     Character &player_character = get_player_character();
     bool picked_up = false;
     bool crushed = false;
     Pickup::pick_info pre_info( info );
     pickup_answer option = CANCEL;
     // We already checked in do_pickup if this was a nullptr
     // Make copies so the original remains untouched if we bail out
     item_location newloc = loc;
     //original item reference
     item &it = *newloc.get_item();
     //new item (copy)
     item newit = it;
     if( !newit.is_owned_by( player_character, true ) ) {
         // Has the player given input on if stealing is ok?
         if( player_character.get_value( "THIEF_MODE" ) == "THIEF_ASK" ) {
             Pickup::query_thief();
         }
         if( player_character.get_value( "THIEF_MODE" ) == "THIEF_HONEST" ) {
             return true; // Since we are honest, return no problem before picking up
         }
     }
     if( newit.invlet != '\0' &&
         player_character.invlet_to_item( newit.invlet ) != nullptr ) {
         // Existing invlet is not re-usable, remove it and let the code in player.cpp/inventory.cpp
         // add a new invlet, otherwise keep the (usable) invlet.
         newit.invlet = '\0';
     }
     // Handle charges, quantity == 0 means move all
     if( quantity != 0 && newit.count_by_charges() ) {
         if( newit.charges > quantity ) {
             newit.charges = quantity;
         }
     }
     bool did_prompt = false;
     if( newit.is_frozen_liquid() ) {
         if( newit.has_flag( json_flag_SHREDDED ) ) {
             option = STASH;
         } else {
             crushed = player_character.crush_frozen_liquid( newloc );
             if( crushed ) {
                 option = STASH;
                 newit.set_flag( json_flag_SHREDDED );
             } else {
                 got_frozen_liquid = true;
             }
         }
     } else if( newit.made_of_from_type( phase_id::LIQUID ) ) {
         got_water = true;
     } else if( newit.made_of_from_type( phase_id::GAS ) ) {
         got_gas = true;
     } else if( newit.is_bucket_nonempty() ) {
         if( !autopickup ) {
             const std::string &explain = string_format( _( "Can't stash %s while it's not empty" ),
                                          newit.display_name() );
             option = handle_problematic_pickup( newit, explain );
             did_prompt = true;
         } else {
             option = CANCEL;
         }
     } else if( !player_character.can_pickWeight_partial( newit, false ) ||
                !player_character.can_stash_partial( newit, false ) ) {
         option = CANCEL;
         stash_successful = false;
     } else {
         option = STASH;
     }
     switch( option ) {
         case NUM_ANSWERS:
             // Some other option
             break;
         case CANCEL:
             picked_up = false;
             break;
         case WIELD:
             picked_up = player_character.wield( newit );
             break;
         case SPILL:
             if( newit.is_container_empty() ) {
                 debugmsg( "Tried to spill contents from an empty container" );
                 break;
             }
             //using original item, possibly modifying it
             picked_up = it.spill_contents( player_character );
             if( !picked_up ) {
                 break;
             } else {
                 const char invlet = newit.invlet;
                 newit = it;
                 newit.invlet = invlet;
             }
         // Intentional fallthrough
         case STASH: {
             int last_charges = newit.charges;
             ret_val<item_location> ret = player_character.i_add_or_fill( newit, true, nullptr, &it,
                                          /*allow_drop=*/false, /*allow_wield=*/false, false );
             item_location added_it = ret.value();
             if( ret.success() ) {
                 if( added_it == item_location::nowhere ) {
                     newit.charges = last_charges - newit.charges;
                     newit.on_pickup( player_character );
                     if( newit.charges != 0 ) {
                         auto &entry = mapPickup[newit.tname()];
                         entry.second += newit.charges;
                         entry.first = newit;
                         picked_up = true;
                     }
                 } else if( &*added_it == &it ) {
                     // merged to the original stack, restore original charges
                     it.charges = last_charges;
                 } else {
                     // successfully added
                     auto &entry = mapPickup[newit.tname()];
                     entry.second += newit.count();
                     entry.first = newit;
                     picked_up = true;
                 }
             }
             if( picked_up ) {
                 // Update info
                 info.set_dst( added_it );
             }
             break;
         }
     }
     if( picked_up ) {
         info.set_src( loc );
         info.total_bulk_volume += loc->volume( false, false, quantity );
         if( !is_bulk_load( pre_info, info ) ) {
             // Cost to take an item from a container or map
             player_character.mod_moves( -loc.obtain_cost( player_character, quantity ) );
         } else {
             // Pure cost to handling item excluding overhead.
             player_character.mod_moves( -std::max( player_character.item_handling_cost( *loc, true, 0, quantity,
                                                    true ), 1 ) );
         }
         contents_change_handler handler;
         handler.unseal_pocket_containing( loc );
         item &orig_it = *loc.get_item();
         // Subtract moved charges instead of assigning leftover charges,
         // since the total charges of the original item may have changed
         // due to merging.
         if( orig_it.charges > newit.charges ) {
             orig_it.charges -= newit.charges;
         } else {
             loc.remove_item();
         }
         player_character.flag_encumbrance();
         player_character.invalidate_weight_carried_cache();
     }
     return picked_up || !did_prompt;
 }
References _, PATH_INFO::autopickup(), Character::can_pickWeight_partial(), Character::can_stash_partial(), CANCEL, item::charges, item::count(), item::count_by_charges(), Character::crush_frozen_liquid(), debugmsg, item::display_name(), Character::flag_encumbrance(), GAS, item_location::get_item(), get_player_character(), Creature::get_value(), handle_problematic_pickup(), item::has_flag(), Character::i_add_or_fill(), Character::invalidate_weight_carried_cache(), item::invlet, Character::invlet_to_item(), item::is_bucket_nonempty(), is_bulk_load(), item::is_container_empty(), item::is_frozen_liquid(), item::is_owned_by(), Character::item_handling_cost(), json_flag_SHREDDED, LIQUID, item::made_of_from_type(), max(), Creature::mod_moves(), item_location::nowhere, NUM_ANSWERS, item_location::obtain_cost(), item::on_pickup(), Pickup::query_thief(), item_location::remove_item(), cata::hash64_detail::ret, Pickup::pick_info::set_dst(), item::set_flag(), Pickup::pick_info::set_src(), SPILL, item::spill_contents(), STASH, string_format(), item::tname(), Pickup::pick_info::total_bulk_volume, contents_change_handler::unseal_pocket_containing(), item::volume(), Character::wield(), and WIELD.
Referenced by Pickup::do_pickup().
show_pickup_message()
static void show_pickup_message (const PickupMap & mapPickup) static
Definition at line 46 of file pickup.cpp.
 {
     for( const auto &entry : mapPickup ) {
         if( entry.second.first.invlet != 0 ) {
             add_msg( _( "You pick up: %d %s [%c]" ), entry.second.second,
                      entry.second.first.display_name( entry.second.second ), entry.second.first.invlet );
         } else if( entry.second.first.count_by_charges() ) {
             add_msg( _( "You pick up: %s" ), entry.second.first.display_name( entry.second.second ) );
         } else {
             add_msg( _( "You pick up: %d %s" ), entry.second.second,
                      entry.second.first.display_name( entry.second.second ) );
         }
     }
 }
References _, and add_msg().
Referenced by Pickup::do_pickup().
Variable Documentation
json_flag_SHREDDED
const flag_id json_flag_SHREDDED("SHREDDED") ("SHREDDED") static
Referenced by pick_one_up().
zone_type_NO_AUTO_PICKUP
const zone_type_id zone_type_NO_AUTO_PICKUP("NO_AUTO_PICKUP") ("NO_AUTO_PICKUP") static
Referenced by Pickup::autopickup().