Cataclysm DDA: src/player_difficulty.cpp File Reference
player_difficulty.cpp File Reference
#include "avatar.h"
#include "character_martial_arts.h"
#include "make_static.h"
#include "martialarts.h"
#include "mutation.h"
#include "options.h"
#include "player_difficulty.h"
#include "profession.h"
#include "skill.h"
Functions
static int get_character_skill_value (const Character &u)
Variables
static const damage_type_id damage_bash ("bash")
static const profession_id profession_unemployed ("unemployed")
Function Documentation
get_character_skill_value()
static int get_character_skill_value (const Character & u) static
Definition at line 255 of file player_difficulty.cpp.
 {
     // sum player skills and proficiencies
     int character_skills = 0;
     // every skill point is worth 1 point of value
     for( const auto &t : u.get_all_skills() ) {
         // combat skills will be handled in offence
         if( !t.first->is_combat_skill() ) {
             character_skills += t.second.level();
         }
     }
     return character_skills;
 }
References u.
Referenced by player_difficulty::get_expertise_difficulty().
Variable Documentation
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by player_difficulty::calc_armor_value().
profession_unemployed
const profession_id profession_unemployed("unemployed") ("unemployed") static
Referenced by player_difficulty::player_difficulty().