Cataclysm DDA: src/player_display.cpp File Reference
player_display.cpp File Reference
#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdlib>
#include <memory>
#include <string>
#include "addiction.h"
#include "avatar.h"
#include "bionics.h"
#include "bodygraph.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "character_modifier.h"
#include "color.h"
#include "cursesdef.h"
#include "debug.h"
#include "display.h"
#include "effect.h"
#include "flag.h"
#include "enum_conversions.h"
#include "game.h"
#include "game_inventory.h"
#include "input_context.h"
#include "itype.h"
#include "mutation.h"
#include "options.h"
#include "output.h"
#include "pimpl.h"
#include "profession.h"
#include "proficiency.h"
#include "sdltiles.h"
#include "skill.h"
#include "skill_ui.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "ui.h"
#include "ui_manager.h"
#include "units.h"
#include "units_utility.h"
#include "weather.h"
Classes
struct bionic_grouping
struct speedlist_entry
Namespaces
anonymous_namespace{player_display.cpp}
Enumerations
enum class anonymous_namespace{player_display.cpp}::player_display_tab : int {
anonymous_namespace{player_display.cpp}::stats , anonymous_namespace{player_display.cpp}::encumbrance , anonymous_namespace{player_display.cpp}::speed , anonymous_namespace{player_display.cpp}::skills ,
anonymous_namespace{player_display.cpp}::traits , anonymous_namespace{player_display.cpp}::bionics , anonymous_namespace{player_display.cpp}::effects , anonymous_namespace{player_display.cpp}::proficiencies ,
anonymous_namespace{player_display.cpp}::num_tabs
}
Functions
static int temperature_print_rescaling (units::temperature temp)
static bool should_combine_bps (const Character &p, const bodypart_id &l, const bodypart_id &r, const item *selected_clothing)
static std::vector< std::pair< bodypart_id, bool > > list_and_combine_bps (const Character &p, const item *selected_clothing)
static nc_color limb_score_current_color (float cur_score, float bp_score)
static std::string get_score_text (const std::string &sc_name, float cur_score, float bp_score)
static std::vector< std::string > get_encumbrance_description (const Character &you, const bodypart_id &bp)
static bool is_cqb_skill (const skill_id &id)
static void draw_x_info (const catacurses::window &w_info, const std::string &description, const unsigned info_line)
static void draw_proficiencies_tab (ui_adaptor &ui, const catacurses::window &win, const unsigned line, const Character &guy, const player_display_tab curtab, const input_context &ctxt)
static void draw_proficiencies_info (const catacurses::window &w_info, const unsigned line, const Character &guy, const unsigned info_line)
static void draw_stats_tab (ui_adaptor &ui, const catacurses::window &w_stats, const Character &you, const unsigned line, const player_display_tab curtab, const input_context &ctxt)
static void draw_stats_info (const catacurses::window &w_info, const Character &you, const unsigned line)
static void draw_encumbrance_tab (ui_adaptor &ui, const catacurses::window &w_encumb, const Character &you, const unsigned line, const player_display_tab curtab, const input_context &ctxt)
static void draw_encumbrance_info (const catacurses::window &w_info, const Character &you, const unsigned line, const unsigned info_line)
static void draw_traits_tab (ui_adaptor &ui, const catacurses::window &w_traits, const unsigned line, const player_display_tab curtab, const std::vector< trait_and_var > &traitslist, const input_context &ctxt)
static void draw_traits_info (const catacurses::window &w_info, const unsigned line, const std::vector< trait_and_var > &traitslist, const unsigned info_line)
static void draw_bionics_tab (ui_adaptor &ui, const catacurses::window &w_bionics, const Character &you, const unsigned line, const player_display_tab curtab, const std::vector< bionic_grouping > &bionicslist, const input_context &ctxt)
static void draw_bionics_info (const catacurses::window &w_info, const unsigned line, const std::vector< bionic_grouping > &bionicslist, const unsigned info_line)
static void draw_effects_tab (ui_adaptor &ui, const catacurses::window &w_effects, const unsigned line, const player_display_tab curtab, const std::vector< std::pair< std::string, std::string >> &effect_name_and_text, const input_context &ctxt)
static void draw_effects_info (const catacurses::window &w_info, const unsigned line, const std::vector< std::pair< std::string, std::string >> &effect_name_and_text, const unsigned info_line)
static void draw_skills_tab (ui_adaptor &ui, const catacurses::window &w_skills, Character &you, unsigned int line, const player_display_tab curtab, std::vector< HeaderSkill > &skillslist, const input_context &ctxt)
static void draw_speed_info (const catacurses::window &w_info, unsigned int line, const std::vector< speedlist_entry > &speedlist)
static void draw_skills_info (const catacurses::window &w_info, const Character &you, unsigned int line, const std::vector< HeaderSkill > &skillslist, const unsigned info_line)
static std::vector< speedlist_entry > get_speedlist_entries (const Character &you, int &move_cost, const std::map< std::string, int > &speed_effects)
static void draw_speed_tab (ui_adaptor &ui, const catacurses::window &w_speed, const unsigned line, const player_display_tab curtab, const Character &you, const std::vector< speedlist_entry > &speedlist, const int move_cost)
static void draw_info_window (const catacurses::window &w_info, const Character &you, const unsigned line, const unsigned info_line, const player_display_tab curtab, const std::vector< speedlist_entry > &speedlist, const std::vector< trait_and_var > &traitslist, const std::vector< bionic_grouping > &bionicslist, const std::vector< std::pair< std::string, std::string >> &effect_name_and_text, const std::vector< HeaderSkill > &skillslist)
static void draw_tip (const catacurses::window &w_tip, const Character &you, const std::string &race, const input_context &ctxt, bool customize_character, int &tip_btn_highlight)
static void on_customize_character (Character &you)
static void change_armor_sprite (avatar &you)
static int get_line_count (player_display_tab curtab, Character &you, const std::vector< speedlist_entry > &speedlist, std::vector< trait_and_var > &traitslist, const std::vector< bionic_grouping > &bionicslist, const std::vector< std::pair< std::string, std::string >> &effect_name_and_text, const std::vector< HeaderSkill > &skillslist)
static bool handle_player_display_action (Character &you, unsigned int &line, unsigned int &info_line, player_display_tab &curtab, input_context &ctxt, const ui_adaptor &ui_tip, const ui_adaptor &ui_info, const ui_adaptor &ui_stats, const ui_adaptor &ui_encumb, const ui_adaptor &ui_speed, const ui_adaptor &ui_traits, const ui_adaptor &ui_bionics, const ui_adaptor &ui_effects, const ui_adaptor &ui_skills, const ui_adaptor &ui_proficiencies, const std::vector< speedlist_entry > &speedlist, std::vector< trait_and_var > &traitslist, const std::vector< bionic_grouping > &bionicslist, const std::vector< std::pair< std::string, std::string >> &effect_name_and_text, const std::vector< HeaderSkill > &skillslist, bool customize_character, const std::vector< catacurses::window * > &windows, const catacurses::window &w_tip, int &tip_btn_selected)
static std::pair< unsigned, unsigned > calculate_shared_column_win_height (const unsigned available_height, unsigned first_win_size_y_max, unsigned second_win_size_y_max)
Calculate max allowed height of two windows sharing column space.
Variables
static const bionic_id bio_cqb ("bio_cqb")
static const skill_id skill_bashing ("bashing")
static const skill_id skill_cutting ("cutting")
static const skill_id skill_dodge ("dodge")
static const skill_id skill_melee ("melee")
static const skill_id skill_stabbing ("stabbing")
static const skill_id skill_unarmed ("unarmed")
static const trait_id trait_TROGLO ("TROGLO")
static const trait_id trait_TROGLO2 ("TROGLO2")
static const trait_id trait_TROGLO3 ("TROGLO3")
static const std::string title_STATS = translate_marker("STATS")
static const std::string title_ENCUMB = translate_marker("ENCUMBRANCE AND WARMTH")
static const std::string title_EFFECTS = translate_marker("EFFECTS")
static const std::string title_SPEED = translate_marker("SPEED")
static const std::string title_MOVE_COST = translate_marker("MOVE COST")
static const std::string title_SKILLS = translate_marker("SKILLS")
static const std::string title_BIONICS = translate_marker("BIONICS")
static const std::string title_TRAITS = translate_marker("TRAITS")
static const std::string title_PROFICIENCIES = translate_marker("PROFICIENCIES")
static const unsigned int grid_width = 26
Function Documentation
calculate_shared_column_win_height()
static std::pair<unsigned, unsigned> calculate_shared_column_win_height (const unsigned available_height, unsigned first_win_size_y_max, unsigned second_win_size_y_max) static
Calculate max allowed height of two windows sharing column space.
Definition at line 1510 of file player_display.cpp.
 {
     if( ( second_win_size_y_max + 1 + first_win_size_y_max ) > available_height ) {
         // maximum space for either window if they're both the same size
         unsigned max_shared_y = ( available_height - 1 ) / 2;
         if( std::min( second_win_size_y_max, first_win_size_y_max ) > max_shared_y ) {
             // both are larger than the shared size
             second_win_size_y_max = max_shared_y;
             first_win_size_y_max = available_height - 1 - second_win_size_y_max;
         } else if( first_win_size_y_max <= max_shared_y ) {
             // first window is less than the shared size, so give space to second window
             second_win_size_y_max = available_height - 1 - first_win_size_y_max;
         } else {
             // second window is less than the shared size
             first_win_size_y_max = available_height - 1 - second_win_size_y_max;
         }
     }
     return { first_win_size_y_max, second_win_size_y_max };
 }
References min().
Referenced by Character::disp_info().
change_armor_sprite()
static void change_armor_sprite (avatar & you) static
Definition at line 1155 of file player_display.cpp.
 {
     item_location target_loc;
     target_loc = game_menus::inv::change_sprite( you );
     if( target_loc && target_loc.get_item() ) {
         item *target_item = target_loc.get_item();
         uilist menu;
         menu.title = _( "Change sprite" );
         menu.addentry( 0, true, MENU_AUTOASSIGN, _( "Select sprite from items" ) );
         menu.addentry( 1, true, MENU_AUTOASSIGN, _( "Restore default sprite" ) );
         menu.addentry( 2, true, MENU_AUTOASSIGN, _( "Cancel" ) );
         menu.query();
         if( menu.ret == 0 ) {
             item_location sprite_loc;
             avatar *you = get_player_character().as_avatar();
             auto armor_filter = [&]( const item & i ) {
                 return i.is_armor();
             };
             if( you != nullptr ) {
                 sprite_loc = game_menus::inv::titled_filter_menu( armor_filter,
                              *you,
                              _( "Select appearance of this armor:" ),
                              -1,
                              _( "You have nothing to wear." ) );
             }
             if( sprite_loc && sprite_loc.get_item() ) {
                 const item *sprite_item = sprite_loc.get_item();
                 const std::string variant = sprite_item->has_itype_variant() ? sprite_item->itype_variant().id : "";
                 target_item->set_var( "sprite_override", sprite_item->typeId().str() );
                 target_item->set_var( "sprite_override_variant", variant );
             }
         } else if( menu.ret == 1 ) {
             target_item->erase_var( "sprite_override" );
             target_item->erase_var( "sprite_override_variant" );
         }
     }
 }
References _, uilist::addentry(), Creature::as_avatar(), game_menus::inv::change_sprite(), item::erase_var(), item_location::get_item(), get_player_character(), item::has_itype_variant(), itype_variant_data::id, item::itype_variant(), MENU_AUTOASSIGN, uilist::query(), uilist::ret, item::set_var(), string_id< T >::str(), uilist::title, game_menus::inv::titled_filter_menu(), and item::typeId().
Referenced by handle_player_display_action().
draw_bionics_info()
static void draw_bionics_info (const catacurses::window & w_info, const unsigned line, const std::vector< bionic_grouping > & bionicslist, const unsigned info_line) static
Definition at line 714 of file player_display.cpp.
 {
     werase( w_info );
     if( line < bionicslist.size() ) {
         draw_x_info( w_info, bionicslist[line].description.translated(), info_line );
     }
     wnoutrefresh( w_info );
 }
References draw_x_info(), line(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by draw_info_window().
draw_bionics_tab()
static void draw_bionics_tab (ui_adaptor & ui, const catacurses::window & w_bionics, const Character & you, const unsigned line, const player_display_tab curtab, const std::vector< bionic_grouping > & bionicslist, const input_context & ctxt) static
Definition at line 651 of file player_display.cpp.
 {
     werase( w_bionics );
     const bool is_current_tab = curtab == player_display_tab::bionics;
     const nc_color title_col = is_current_tab ? h_light_gray : c_light_gray;
     center_print( w_bionics, 0, title_col, _( title_BIONICS ) );
     right_print( w_bionics, 0, 0, title_col, string_format( "[<color_yellow>%s</color>]",
                  ctxt.get_desc( "SELECT_BIONICS_TAB" ) ) );
     int power_amount;
     std::string power_unit;
     if( you.get_power_level() < 1_J ) {
         power_amount = units::to_millijoule( you.get_power_level() );
         power_unit = pgettext( "energy unit: millijoule", "mJ" );
     } else if( you.get_power_level() < 1_kJ ) {
         power_amount = units::to_joule( you.get_power_level() );
         power_unit = pgettext( "energy unit: joule", "J" );
     } else {
         power_amount = units::to_kilojoule( you.get_power_level() );
         power_unit = pgettext( "energy unit: kilojoule", "kJ" );
     }
     // NOLINTNEXTLINE(cata-use-named-point-constants)
     const point pow_pos( 1, 1 );
     if( is_current_tab ) {
         ui.set_cursor( w_bionics, pow_pos );
     }
     trim_and_print( w_bionics, pow_pos, getmaxx( w_bionics ) - 1, c_white,
                     string_format( _( "Power: <color_light_blue>%1$d %2$s</color>"
                                       " / <color_light_blue>%3$d kJ</color>" ),
                                    power_amount, power_unit, units::to_kilojoule( you.get_max_power_level() ) ) );
     const int height = getmaxy( w_bionics ) - 2;  // -2 for headline and power_level
     const bool do_draw_scrollbar = height < static_cast<int>( bionicslist.size() );
     const int width = getmaxx( w_bionics ) - 1 - ( do_draw_scrollbar ? 1 : 0 );
     const auto& [i_start, i_end] = subindex_around_cursor( bionicslist.size(), height, line,
                                    is_current_tab );
     for( size_t i = i_start; i < static_cast<size_t>( i_end ); ++i ) {
         const bool highlight_line = is_current_tab && i == line;
         const point pos( 1, 2 + i - i_start );
         if( highlight_line ) {
             ui.set_cursor( w_bionics, pos );
         }
         const bionic_grouping &bio_group = bionicslist[i];
         const std::string bio_name = bio_group.name.translated( bio_group.installed_count );
         nc_color col = highlight_line ? hilite( c_white ) : c_white;
         if( bio_group.installed_count <= 1 ) {
             trim_and_print( w_bionics, pos, width - 1, col, bio_name );
         } else {
             const std::string bio_count = string_format( " (%d)", bio_group.installed_count );
             const std::string bio_trunc = trim_by_length( bio_name, width - utf8_width( bio_count ) - 1 );
             print_colored_text( w_bionics, pos, col, col, bio_trunc );
             print_colored_text( w_bionics, pos + point( utf8_width( bio_trunc ), 0 ), col, col, bio_count );
         }
     }
     if( do_draw_scrollbar ) {
         draw_scrollbar( w_bionics, i_start, height, bionicslist.size(), point( width + 1, 2 ), c_white,
                         true );
     }
     wnoutrefresh( w_bionics );
 }
References _, c_light_gray, c_white, center_print(), draw_scrollbar(), input_context::get_desc(), Character::get_max_power_level(), Character::get_power_level(), catacurses::getmaxx(), catacurses::getmaxy(), h_light_gray, hilite(), bionic_grouping::installed_count, line(), bionic_grouping::name, pgettext, math_opers::pos(), print_colored_text(), right_print(), string_format(), subindex_around_cursor(), title_BIONICS, units::to_joule(), units::to_kilojoule(), units::to_millijoule(), translation::translated(), trim_and_print(), trim_by_length(), utf8_width(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by Character::disp_info().
draw_effects_info()
static void draw_effects_info (const catacurses::window & w_info, const unsigned line, const std::vector< std::pair< std::string, std::string >> & effect_name_and_text, const unsigned info_line) static
Definition at line 760 of file player_display.cpp.
 {
     werase( w_info );
     const size_t actual_size = effect_name_and_text.size();
     if( line < actual_size ) {
         draw_x_info( w_info, effect_name_and_text[line].second, info_line );
     }
     wnoutrefresh( w_info );
 }
References draw_x_info(), line(), second, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by draw_info_window().
draw_effects_tab()
static void draw_effects_tab (ui_adaptor & ui, const catacurses::window & w_effects, const unsigned line, const player_display_tab curtab, const std::vector< std::pair< std::string, std::string >> & effect_name_and_text, const input_context & ctxt) static
Definition at line 724 of file player_display.cpp.
 {
     werase( w_effects );
     const bool is_current_tab = curtab == player_display_tab::effects;
     const nc_color title_col = is_current_tab ? h_light_gray : c_light_gray;
     if( is_current_tab ) {
         ui.set_cursor( w_effects, point_zero );
     }
     center_print( w_effects, 0, title_col, _( title_EFFECTS ) );
     right_print( w_effects, 0, 0, title_col, string_format( "[<color_yellow>%s</color>]",
                  ctxt.get_desc( "SELECT_EFFECTS_TAB" ) ) );
     const int height = getmaxy( w_effects ) - 1;
     const bool do_draw_scrollbar = height < static_cast<int>( effect_name_and_text.size() );
     const int width = getmaxx( w_effects ) - 1 - ( do_draw_scrollbar ? 1 : 0 );
     const auto& [i_start, i_end] = subindex_around_cursor( effect_name_and_text.size(), height, line,
                                    is_current_tab );
     for( size_t i = i_start; i < static_cast<size_t>( i_end ); ++i ) {
         const bool highlight_line = is_current_tab && i == line;
         const point pos( 1, 1 + i - i_start );
         if( highlight_line ) {
             ui.set_cursor( w_effects, pos );
         }
         trim_and_print( w_effects, pos, width,
                         highlight_line ? h_light_gray : c_light_gray, effect_name_and_text[i].first );
     }
     if( do_draw_scrollbar ) {
         draw_scrollbar( w_effects, i_start, height, effect_name_and_text.size(), point( width + 1, 1 ),
                         c_white, true );
     }
     wnoutrefresh( w_effects );
 }
References _, c_light_gray, c_white, center_print(), draw_scrollbar(), input_context::get_desc(), catacurses::getmaxx(), catacurses::getmaxy(), h_light_gray, line(), point_zero, math_opers::pos(), right_print(), string_format(), subindex_around_cursor(), title_EFFECTS, trim_and_print(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by Character::disp_info().
draw_encumbrance_info()
static void draw_encumbrance_info (const catacurses::window & w_info, const Character & you, const unsigned line, const unsigned info_line) static
Definition at line 578 of file player_display.cpp.
 {
     const std::vector<std::pair<bodypart_id, bool>> bps = list_and_combine_bps( you, nullptr );
     werase( w_info );
     bodypart_id bp;
     if( line < bps.size() ) {
         bp = bps[line].first;
     }
     const std::vector<std::string> s = get_encumbrance_description( you, bp );
     const std::string desc = string_join( s, "\n" );
     draw_x_info( w_info, desc, info_line );
     wnoutrefresh( w_info );
 }
References bp, draw_x_info(), get_encumbrance_description(), line(), list_and_combine_bps(), string_join(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by draw_info_window().
draw_encumbrance_tab()
static void draw_encumbrance_tab (ui_adaptor & ui, const catacurses::window & w_encumb, const Character & you, const unsigned line, const player_display_tab curtab, const input_context & ctxt) static
Definition at line 559 of file player_display.cpp.
 {
     werase( w_encumb );
     const bool is_current_tab = curtab == player_display_tab::encumbrance;
     const nc_color title_col = is_current_tab ? h_light_gray : c_light_gray;
     center_print( w_encumb, 0, title_col, _( title_ENCUMB ) );
     right_print( w_encumb, 0, 0, title_col, string_format( "[<color_yellow>%s</color>]",
                  ctxt.get_desc( "SELECT_ENCUMBRANCE_TAB" ) ) );
     if( is_current_tab ) {
         ui.set_cursor( w_encumb, point_zero );
         you.print_encumbrance( ui, w_encumb, line );
     } else {
         you.print_encumbrance( ui, w_encumb );
     }
     wnoutrefresh( w_encumb );
 }
References _, c_light_gray, center_print(), input_context::get_desc(), h_light_gray, line(), point_zero, Character::print_encumbrance(), right_print(), string_format(), title_ENCUMB, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by Character::disp_info().
draw_info_window()
static void draw_info_window (const catacurses::window & w_info, const Character & you, const unsigned line, const unsigned info_line, const player_display_tab curtab, const std::vector< speedlist_entry > & speedlist, const std::vector< trait_and_var > & traitslist, const std::vector< bionic_grouping > & bionicslist, const std::vector< std::pair< std::string, std::string >> & effect_name_and_text, const std::vector< HeaderSkill > & skillslist) static
Definition at line 1035 of file player_display.cpp.
 {
     switch( curtab ) {
         case player_display_tab::stats:
             draw_stats_info( w_info, you, line );
             break;
         case player_display_tab::encumbrance:
             draw_encumbrance_info( w_info, you, line, info_line );
             break;
         case player_display_tab::speed:
             draw_speed_info( w_info, line, speedlist );
             break;
         case player_display_tab::skills:
             draw_skills_info( w_info, you, line, skillslist, info_line );
             break;
         case player_display_tab::traits:
             draw_traits_info( w_info, line, traitslist, info_line );
             break;
         case player_display_tab::bionics:
             draw_bionics_info( w_info, line, bionicslist, info_line );
             break;
         case player_display_tab::effects:
             draw_effects_info( w_info, line, effect_name_and_text, info_line );
             break;
         case player_display_tab::proficiencies:
             draw_proficiencies_info( w_info, line, you, info_line );
             break;
         case player_display_tab::num_tabs:
             cata_fatal( "Invalid curtab" );
     }
 }
References cata_fatal, draw_bionics_info(), draw_effects_info(), draw_encumbrance_info(), draw_proficiencies_info(), draw_skills_info(), draw_speed_info(), draw_stats_info(), draw_traits_info(), and line().
Referenced by Character::disp_info().
draw_proficiencies_info()
static void draw_proficiencies_info (const catacurses::window & w_info, const unsigned line, const Character & guy, const unsigned info_line) static
Definition at line 353 of file player_display.cpp.
 {
     werase( w_info );
     const std::vector<display_proficiency> profs = guy.display_proficiencies();
     if( line < profs.size() ) {
         const display_proficiency &cur = profs[line];
         std::string progress;
         if( cur.known ) {
             progress = _( "You know this proficiency." );
         } else {
             progress = string_format( _( "You are %.2f%% of the way towards learning this proficiency." ),
                                       cur.practice * 100 );
             if( debug_mode ) {
                 progress += string_format( "\nYou have spent %s practicing this proficiency.",
                                            to_string( cur.spent ) );
             }
         }
         std::string desc = colorize( cur.id->name(), cur.color )
                            + "\n" + colorize( progress, c_cyan )
                            + "\n" + colorize( cur.id->description(), c_white );
         draw_x_info( w_info, desc, info_line );
     }
     wnoutrefresh( w_info );
 }
References _, c_cyan, c_white, display_proficiency::color, colorize(), debug_mode, proficiency::description(), Character::display_proficiencies(), draw_x_info(), display_proficiency::id, display_proficiency::known, line(), proficiency::name(), display_proficiency::practice, display_proficiency::spent, string_format(), to_string(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by draw_info_window().
draw_proficiencies_tab()
static void draw_proficiencies_tab (ui_adaptor & ui, const catacurses::window & win, const unsigned line, const Character & guy, const player_display_tab curtab, const input_context & ctxt) static
Definition at line 307 of file player_display.cpp.
 {
     werase( win );
     const std::vector<display_proficiency> profs = guy.display_proficiencies();
     const bool focused = curtab == player_display_tab::proficiencies;
     const nc_color title_color = focused ? h_light_gray : c_light_gray;
     if( focused ) {
         ui.set_cursor( win, point_zero );
     }
     center_print( win, 0, title_color, string_format( "[<color_yellow>%s</color>] %s",
                   ctxt.get_desc( "VIEW_PROFICIENCIES" ), _( title_PROFICIENCIES ) ) );
     right_print( win, 0, 0, title_color, string_format( "[<color_yellow>%s</color>]",
                  ctxt.get_desc( "SELECT_PROFICIENCIES_TAB" ) ) );
     const int height = getmaxy( win ) - 1;
     const bool do_draw_scrollbar = height < static_cast<int>( profs.size() );
     const int width = getmaxx( win ) - 1 - ( do_draw_scrollbar ? 1 : 0 );  // -1 for beginning space
     const auto& [i_start, i_end] = subindex_around_cursor( profs.size(), height, line, focused );
     for( size_t i = i_start; i < static_cast<size_t>( i_end ); ++i ) {
         std::string name;
         const display_proficiency &cur = profs[i];
         if( !cur.known && cur.id->can_learn() ) {
             name = string_format( "%s %2.0f%%",
                                   left_justify( trim_by_length( cur.id->name(), width - 4 ), width - 4 ),
                                   std::floor( cur.practice * 100 ) );
         } else {
             name = trim_by_length( cur.id->name(), width );
         }
         const bool highlight_line = focused && i == line;
         const nc_color col = highlight_line ? hilite( cur.color ) : cur.color;
         nc_color col_cur = col;  // make non const copy
         const point pos( 1, 1 + i - i_start );
         if( highlight_line ) {
             ui.set_cursor( win, pos );
         }
         print_colored_text( win, pos, col_cur, col, name );
     }
     if( do_draw_scrollbar ) {
         draw_scrollbar( win, i_start, height, profs.size(), point( width + 1, 1 ), c_white, true );
     }
     wnoutrefresh( win );
 }
References _, c_light_gray, c_white, proficiency::can_learn(), center_print(), display_proficiency::color, Character::display_proficiencies(), draw_scrollbar(), floor(), input_context::get_desc(), catacurses::getmaxx(), catacurses::getmaxy(), h_light_gray, hilite(), display_proficiency::id, display_proficiency::known, left_justify(), line(), proficiency::name(), om_direction::name(), point_zero, math_opers::pos(), display_proficiency::practice, print_colored_text(), right_print(), string_format(), subindex_around_cursor(), title_PROFICIENCIES, trim_by_length(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by Character::disp_info().
draw_skills_info()
static void draw_skills_info (const catacurses::window & w_info, const Character & you, unsigned int line, const std::vector< HeaderSkill > & skillslist, const unsigned info_line) static
Definition at line 897 of file player_display.cpp.
 {
     werase( w_info );
     const Skill *selectedSkill = nullptr;
     if( line < skillslist.size() && !skillslist[line].is_header ) {
         selectedSkill = skillslist[line].skill;
     }
     if( selectedSkill ) {
         const SkillLevel &level = you.get_skill_level_object( selectedSkill->ident() );
         std::string info_text = selectedSkill->description();
         float level_gap = 100.0f * std::max( level.knowledgeLevel(), 1 ) / std::max( level.level(), 1 );
         if( level.knowledgeLevel() == 1 && level.level() == 0 ) {
             level_gap = 150.0f;
         }
         float learning_bonus = 100.0f * std::max( ( 1.0f + you.get_int() / 40.0f ) - 0.1f *
                                level.exercise() / level.knowledgeExperience(), 1.0f );
         if( level.isRusty() ) {
             info_text = string_format( _( "%s\n\nPractical level: %d (%d%%) " ), info_text,
                                        level.level(), level.exercise() );
             if( level.knowledgeLevel() > level.level() ) {
                 info_text = string_format( _( "%s| Learning bonus: %.0f%%" ), info_text,
                                            level_gap );
             } else {
                 info_text = string_format( _( "%s| Learning bonus: %.0f%%" ), info_text,
                                            learning_bonus );
             }
             if( !level.isTraining() ) {
                 info_text = string_format( "%s | %s", info_text,
                                            _( "<color_yellow>Learning is disabled.</color>" ) );
             }
         } else {
             if( !level.isTraining() ) {
                 info_text = string_format( "%s\n\n%s", info_text,
                                            _( "<color_yellow>Learning is disabled.</color>" ) );
             }
         }
         draw_x_info( w_info, info_text, info_line );
     }
     wnoutrefresh( w_info );
 }
References _, Skill::description(), draw_x_info(), SkillLevel::exercise(), Character::get_int(), Character::get_skill_level_object(), Skill::ident(), SkillLevel::isRusty(), SkillLevel::isTraining(), SkillLevel::knowledgeExperience(), SkillLevel::knowledgeLevel(), SkillLevel::level(), line(), max(), string_format(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by draw_info_window().
draw_skills_tab()
static void draw_skills_tab (ui_adaptor & ui, const catacurses::window & w_skills, Character & you, unsigned int line, const player_display_tab curtab, std::vector< HeaderSkill > & skillslist, const input_context & ctxt) static
Definition at line 772 of file player_display.cpp.
 {
     werase( w_skills );
     const bool is_current_tab = curtab == player_display_tab::skills;
     nc_color cstatus = is_current_tab ? h_light_gray : c_light_gray;
     if( is_current_tab ) {
         ui.set_cursor( w_skills, point_zero );
     }
     center_print( w_skills, 0, cstatus, _( title_SKILLS ) );
     right_print( w_skills, 0, 0, c_light_gray, string_format( "[<color_yellow>%s</color>]",
                  ctxt.get_desc( "SELECT_SKILLS_TAB" ) ) );
     const int height = getmaxy( w_skills ) - 1;
     const bool do_draw_scrollbar = height < static_cast<int>( skillslist.size() );
     const int width = getmaxx( w_skills ) - 1 - ( do_draw_scrollbar ? 1 : 0 );
     const auto& [i_start, i_end] = subindex_around_cursor( skillslist.size(), height, line,
                                    is_current_tab );
     int y_pos = 1;
     for( int i = i_start; i < i_end; ++i, ++y_pos ) {
         const Skill *aSkill = skillslist[i].skill;
         if( skillslist[i].is_header ) {
             const SkillDisplayType t = SkillDisplayType::get_skill_type( aSkill->display_category() );
             std::string type_name = t.display_string();
             center_print( w_skills, y_pos, c_yellow, type_name );
         } else {
             const SkillLevel &level = you.get_skill_level_object( aSkill->ident() );
             int exercise = level.knowledgeExperience();
             int level_num = level.knowledgeLevel();
             const bool can_train = level.can_train();
             const bool training = level.isTraining();
             const bool skill_gap = level_num > level.level();
             const bool skill_small_gap = exercise > level.exercise();
             bool locked = false;
             if( you.has_active_bionic( bio_cqb ) && is_cqb_skill( aSkill->ident() ) ) {
                 level_num = 5;
                 exercise = 0;
                 locked = true;
             }
             level_num = you.enchantment_cache->modify_value( aSkill->ident(), level_num );
             if( is_current_tab && i == static_cast<int>( line ) ) {
                 ui.set_cursor( w_skills, point( 1, y_pos ) );
                 if( locked ) {
                     cstatus = h_yellow;
                 } else if( !can_train ) {
                     cstatus = h_white;
                 } else if( exercise >= 100 ) {
                     cstatus = training ? h_pink : h_magenta;
                 } else if( skill_gap || skill_small_gap ) {
                     cstatus = training ? h_light_cyan : h_cyan;
                 } else {
                     cstatus = training ? h_light_blue : h_blue;
                 }
             } else {
                 if( locked ) {
                     cstatus = c_yellow;
                 } else if( skill_gap || skill_small_gap ) {
                     cstatus = training ? c_light_cyan : c_cyan;
                 } else if( !can_train ) {
                     cstatus = c_white;
                 } else {
                     cstatus = training ? c_light_blue : c_blue;
                 }
             }
             mvwprintz( w_skills, point( 1, y_pos ), cstatus, "%s:", aSkill->name() );
             if( aSkill->ident() == skill_dodge ) {
                 mvwprintz( w_skills, point( width - 11, y_pos ), cstatus, "%4.1f/%-2d(%2d%%)", you.get_dodge(),
                            level_num, ( exercise < 0 ? 0 : exercise ) );
             } else {
                 mvwprintz( w_skills, point( width - 6, y_pos ), cstatus, "%-2d(%2d%%)", level_num,
                            ( exercise < 0 ? 0 : exercise ) );
             }
         }
     }
     if( do_draw_scrollbar ) {
         draw_scrollbar( w_skills, i_start, height, skillslist.size(), point( width + 1, 1 ), c_white,
                         true );
     }
     wnoutrefresh( w_skills );
 }
References _, bio_cqb, c_blue, c_cyan, c_light_blue, c_light_cyan, c_light_gray, c_white, c_yellow, SkillLevel::can_train(), center_print(), Skill::display_category(), SkillDisplayType::display_string(), draw_scrollbar(), Character::enchantment_cache, SkillLevel::exercise(), input_context::get_desc(), Character::get_dodge(), Character::get_skill_level_object(), SkillDisplayType::get_skill_type(), catacurses::getmaxx(), catacurses::getmaxy(), h_blue, h_cyan, h_light_blue, h_light_cyan, h_light_gray, h_magenta, h_pink, h_white, h_yellow, Character::has_active_bionic(), Skill::ident(), is_cqb_skill(), SkillLevel::isTraining(), SkillLevel::knowledgeExperience(), SkillLevel::knowledgeLevel(), SkillLevel::level(), line(), mvwprintz(), Skill::name(), point_zero, right_print(), skill_dodge, string_format(), subindex_around_cursor(), title_SKILLS, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by Character::disp_info().
draw_speed_info()
static void draw_speed_info (const catacurses::window & w_info, unsigned int line, const std::vector< speedlist_entry > & speedlist) static
Definition at line 864 of file player_display.cpp.
 {
     werase( w_info );
     if( line >= speedlist.size() ) {
         wnoutrefresh( w_info );
         return;
     }
     if( speedlist[line].val != 0 ) {
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         mvwprintz( w_info, point( 1, 0 ), c_light_gray,
                    //~ One of a list of reasons speed or movecost are being changed
                    _( "Cause: %s" ), speedlist[line].description );
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         mvwprintz( w_info, point( 1, 1 ), c_light_gray,
                    //~ speed or movecost reduced by a constant or percentage
                    speedlist[line].val < 0 ? _( "Effect: %1$s reduced by %2$d%3$c" ) :
                    //~ speed or movecost increased by a constant or percentage
                    _( "Effect: %1$s increased by %2$d%3$c" ),
                    speedlist[line].is_speed ? _( "Speed" ) : _( "Move Cost" ),
                    std::abs( speedlist[line].val ),
                    speedlist[line].percent ? '%' : ' ' );
     } else {
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         mvwprintz( w_info, point( 1, 0 ), c_light_gray, speedlist[line].description );
     }
     wnoutrefresh( w_info );
 }
References _, abs(), c_light_gray, line(), mvwprintz(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by draw_info_window().
draw_speed_tab()
static void draw_speed_tab (ui_adaptor & ui, const catacurses::window & w_speed, const unsigned line, const player_display_tab curtab, const Character & you, const std::vector< speedlist_entry > & speedlist, const int move_cost) static
Definition at line 978 of file player_display.cpp.
 {
     werase( w_speed );
     const bool is_current_tab = curtab == player_display_tab::speed;
     if( is_current_tab ) {
         ui.set_cursor( w_speed, point( 0, 2 ) );
     }
     const int speed = you.get_speed();
     center_print( w_speed, 0, c_light_gray, string_format( "%s: <color_%s>%d</color>",
                   _( title_SPEED ), speed >= 100 ? "light_green" : "red", speed ) );
     center_print( w_speed, 1, c_light_gray, string_format( "%s: <color_%s>%d</color>",
                   _( title_MOVE_COST ), move_cost <= 100 ? "light_green" : "red", move_cost ) );
     const int height = getmaxy( w_speed ) - 2;
     const bool do_draw_scrollbar = height < static_cast<int>( speedlist.size() );
     const int width = getmaxx( w_speed ) - 1 - ( do_draw_scrollbar ? 1 : 0 );
     const auto& [i_start, i_end] = subindex_around_cursor( speedlist.size(), height, line,
                                    is_current_tab );
     for( size_t i = i_start; i < static_cast<size_t>( i_end ); ++i ) {
         const bool highlight_line = is_current_tab && i == line;
         const point pos( 1, 2 + i - i_start );
         if( highlight_line ) {
             ui.set_cursor( w_speed, pos );
         }
         const speedlist_entry &entry = speedlist[i];
         // +speed is good, -movecost is good
         const nc_color col = entry.is_speed == ( entry.val > 0 ) ? c_light_green : c_red;
         const nc_color hcol = highlight_line ? hilite( col ) : col;
         mvwprintz( w_speed, pos, hcol, "%s", entry.description );
         //~ single character abbreviations for Speed and Move Cost
         mvwprintz( w_speed, pos + point( 18, 0 ), hcol, "%s", entry.is_speed ? _( "S" ) : _( "M" ) );
         if( entry.val != 0 ) {
             const char prefix = entry.val < 0 ? '-' : '+';
             const char suffix = entry.percent ? '%' : ' ';
             if( std::abs( entry.val ) < 1000 ) {
                 mvwprintz( w_speed, pos + point( 19, 0 ), hcol, "%c%3d%c", prefix, std::abs( entry.val ), suffix );
             } else {
                 // broken limbs or very big numbers can cause this
                 mvwprintz( w_speed, pos + point( 19, 0 ), hcol, "%c!!!%c", prefix, suffix );
             }
         }
     }
     if( do_draw_scrollbar ) {
         draw_scrollbar( w_speed, i_start, height, speedlist.size(), point( width + 1, 2 ),
                         c_white, true );
     }
     wnoutrefresh( w_speed );
 }
References _, abs(), c_light_gray, c_light_green, c_red, c_white, center_print(), speedlist_entry::description, draw_scrollbar(), Character::get_speed(), catacurses::getmaxx(), catacurses::getmaxy(), hilite(), speedlist_entry::is_speed, line(), mvwprintz(), speedlist_entry::percent, math_opers::pos(), string_format(), subindex_around_cursor(), title_MOVE_COST, title_SPEED, speedlist_entry::val, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by Character::disp_info().
draw_stats_info()
static void draw_stats_info (const catacurses::window & w_info, const Character & you, const unsigned line) static
Definition at line 470 of file player_display.cpp.
 {
     werase( w_info );
     nc_color col_temp = c_light_gray;
     if( line == 0 ) {
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_magenta,
                         _( "Strength affects your melee damage, the amount of weight you can carry, your total HP, "
                            "your resistance to many diseases, and the effectiveness of actions which require brute force." ) );
         print_colored_text( w_info, point( 1, 3 ), col_temp, c_light_gray,
                             string_format( _( "Base HP: <color_white>%d</color>" ),
                                            you.get_part_hp_max( you.get_root_body_part() ) ) );
         print_colored_text( w_info, point( 1, 4 ), col_temp, c_light_gray,
                             string_format( _( "Carry weight (%s): <color_white>%.1f</color>" ), weight_units(),
                                            convert_weight( you.weight_capacity() ) ) );
         print_colored_text( w_info, point( 1, 5 ), col_temp, c_light_gray,
                             string_format( _( "Bash damage: <color_white>%.1f</color>" ), you.bonus_damage( false ) ) );
     } else if( line == 1 ) {
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_magenta,
                         _( "Dexterity affects your chance to hit in melee combat, helps you steady your "
                            "gun for ranged combat, and enhances many actions that require finesse." ) );
         print_colored_text( w_info, point( 1, 3 ), col_temp, c_light_gray,
                             string_format( _( "Melee to-hit bonus: <color_white>%+.1lf</color>" ), you.get_melee_hit_base() ) );
         print_colored_text( w_info, point( 1, 4 ), col_temp, c_light_gray,
                             string_format( _( "Ranged penalty: <color_white>%+d</color>" ),
                                            -std::abs( you.ranged_dex_mod() ) ) );
         print_colored_text( w_info, point( 1, 5 ), col_temp, c_light_gray,
                             string_format( _( "Throwing penalty per target's dodge: <color_white>%+d</color>" ),
                                            you.throw_dispersion_per_dodge( false ) ) );
     } else if( line == 2 ) {
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_magenta,
                         _( "Intelligence is less important in most situations, but it is vital for more complex tasks like "
                            "electronics crafting.  It also affects how much skill you can pick up from reading a book." ) );
         print_colored_text( w_info, point( 1, 4 ), col_temp, c_light_gray,
                             string_format( _( "Read times: <color_white>%d%%</color>" ), you.read_speed() ) );
         print_colored_text( w_info, point( 1, 5 ), col_temp, c_light_gray,
                             string_format( _( "Crafting bonus: <color_white>%d%%</color>" ), you.get_int() ) );
     } else if( line == 3 ) {
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_magenta,
                         _( "Perception is the most important stat for ranged combat.  It's also used for "
                            "detecting traps and other things of interest." ) );
         print_colored_text( w_info, point( 1, 4 ), col_temp, c_light_gray,
                             string_format( _( "Trap detection level: <color_white>%d</color>" ), you.get_per() ) );
         if( you.ranged_per_mod() > 0 ) {
             print_colored_text( w_info, point( 1, 5 ), col_temp, c_light_gray,
                                 string_format( _( "Aiming penalty: <color_white>%+d</color>" ), -you.ranged_per_mod() ) );
         }
     } else if( line == 4 ) {
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         const int lines = fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_magenta,
                                           _( "Your weight is a general indicator of how much fat your body has stored up,"
                                              " which in turn shows how prepared you are to survive for a time without food."
                                              "  Having too much, or too little, can be unhealthy." ) );
         fold_and_print( w_info, point( 1, 1 + lines ), FULL_SCREEN_WIDTH - 2, c_light_gray,
                         display::weight_long_description( you ) );
     } else if( line == 5 ) {
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_magenta,
                         _( "How healthy you feel.  Exercise, vitamins, sleep and not ingesting poison will increase this over time." ) );
     } else if( line == 6 ) {
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         const int lines = fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_magenta,
                                           _( "Your height.  Simply how tall you are." ) );
         fold_and_print( w_info, point( 1, 1 + lines ), FULL_SCREEN_WIDTH - 2, c_light_gray,
                         you.height_string() );
     } else if( line == 7 ) {
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         const int lines = fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_magenta,
                                           _( "This is how old you are." ) );
         fold_and_print( w_info, point( 1, 1 + lines ), FULL_SCREEN_WIDTH - 2, c_light_gray,
                         you.age_string() );
     } else if( line == 8 ) {
         // NOLINTNEXTLINE(cata-use-named-point-constants)
         const int lines = fold_and_print( w_info, point( 1, 0 ), FULL_SCREEN_WIDTH - 2, c_magenta,
                                           _( "This is your blood type and Rh factor." ) );
         fold_and_print( w_info, point( 1, 1 + lines ), FULL_SCREEN_WIDTH - 2, c_light_gray,
                         string_format( _( "Blood type: %s" ), io::enum_to_string( you.my_blood_type ) ) );
         fold_and_print( w_info, point( 1, 2 + lines ), FULL_SCREEN_WIDTH - 2, c_light_gray,
                         string_format( _( "Rh factor: %s" ),
                                        you.blood_rh_factor ? _( "positive (+)" ) : _( "negative (-)" ) ) );
     }
     wnoutrefresh( w_info );
 }
References _, abs(), Character::age_string(), Character::blood_rh_factor, Character::bonus_damage(), c_light_gray, c_magenta, convert_weight(), io::enum_to_string(), fold_and_print(), FULL_SCREEN_WIDTH, Character::get_int(), Character::get_melee_hit_base(), Creature::get_part_hp_max(), Character::get_per(), Creature::get_root_body_part(), Character::height_string(), line(), Character::my_blood_type, print_colored_text(), Character::ranged_dex_mod(), Character::ranged_per_mod(), Character::read_speed(), string_format(), Character::throw_dispersion_per_dodge(), Character::weight_capacity(), display::weight_long_description(), weight_units(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by draw_info_window().
draw_stats_tab()
static void draw_stats_tab (ui_adaptor & ui, const catacurses::window & w_stats, const Character & you, const unsigned line, const player_display_tab curtab, const input_context & ctxt) static
Definition at line 379 of file player_display.cpp.
 {
     werase( w_stats );
     const bool is_current_tab = curtab == player_display_tab::stats;
     const nc_color title_col = is_current_tab ? h_light_gray : c_light_gray;
     if( is_current_tab ) {
         ui.set_cursor( w_stats, point_zero );
     }
     center_print( w_stats, 0, title_col,
                   string_format( "[<color_yellow>%s</color>] %s",
                                  ctxt.get_desc( "VIEW_BODYSTAT" ), _( title_STATS ) ) );
     right_print( w_stats, 0, 0, title_col, string_format( "[<color_yellow>%s</color>]",
                  ctxt.get_desc( "SELECT_STATS_TAB" ) ) );
     const auto highlight_line = [is_current_tab, line]( const unsigned line_to_draw ) {
         return is_current_tab && line == line_to_draw;
     };
     const auto line_color = [&highlight_line]( const unsigned line_to_draw ) {
         if( highlight_line( line_to_draw ) ) {
             return h_light_gray;
         } else {
             return c_light_gray;
         }
     };
     const auto set_highlight_cursor = [&highlight_line, &ui, &w_stats]
     ( const unsigned line_to_draw ) {
         if( highlight_line( line_to_draw ) ) {
             ui.set_cursor( w_stats, point( 1, line_to_draw + 1 ) );
         }
     };
     // Stats
     const auto display_stat = [&line_color, &set_highlight_cursor, &w_stats]
     ( const char *name, const int cur, const int max, const unsigned line_to_draw ) {
         nc_color cstatus;
         if( cur <= 0 ) {
             cstatus = c_dark_gray;
         } else if( cur < max / 2 ) {
             cstatus = c_red;
         } else if( cur < max ) {
             cstatus = c_light_red;
         } else if( cur == max ) {
             cstatus = c_white;
         } else if( cur < max * 1.5 ) {
             cstatus = c_light_green;
         } else {
             cstatus = c_green;
         }
         set_highlight_cursor( line_to_draw );
         mvwprintz( w_stats, point( 1, line_to_draw + 1 ), line_color( line_to_draw ), name );
         mvwprintz( w_stats, point( 18, line_to_draw + 1 ), cstatus, "%2d", cur );
         mvwprintz( w_stats, point( 21, line_to_draw + 1 ), c_light_gray, "(%2d)", max );
     };
     display_stat( _( "Strength:" ), you.get_str(), you.get_str_base(), 0 );
     display_stat( _( "Dexterity:" ), you.get_dex(), you.get_dex_base(), 1 );
     display_stat( _( "Intelligence:" ), you.get_int(), you.get_int_base(), 2 );
     display_stat( _( "Perception:" ), you.get_per(), you.get_per_base(), 3 );
     set_highlight_cursor( 4 );
     mvwprintz( w_stats, point( 1, 5 ), line_color( 4 ), _( "Weight:" ) );
     right_print( w_stats, 5, 1, c_light_gray, display::weight_string( you ) );
     set_highlight_cursor( 5 );
     mvwprintz( w_stats, point( 1, 6 ), line_color( 5 ), _( "Lifestyle:" ) );
     right_print( w_stats, 6, 1, c_light_gray, display::health_string( you ) );
     set_highlight_cursor( 6 );
     mvwprintz( w_stats, point( 1, 7 ), line_color( 6 ), _( "Height:" ) );
     mvwprintz( w_stats, point( 25 - utf8_width( you.height_string() ), 7 ), c_light_gray,
                you.height_string() );
     set_highlight_cursor( 7 );
     mvwprintz( w_stats, point( 1, 8 ), line_color( 7 ), _( "Age:" ) );
     mvwprintz( w_stats, point( 25 - utf8_width( you.age_string() ), 8 ), c_light_gray,
                you.age_string() );
     set_highlight_cursor( 8 );
     mvwprintz( w_stats, point( 1, 9 ), line_color( 8 ), _( "Blood type:" ) );
     mvwprintz( w_stats, point( 25 - utf8_width( io::enum_to_string( you.my_blood_type ) +
                                ( you.blood_rh_factor ? "+" : "-" ) ), 9 ),
                c_light_gray,
                io::enum_to_string( you.my_blood_type ) + ( you.blood_rh_factor ? "+" : "-" ) );
     wnoutrefresh( w_stats );
 }
References _, Character::age_string(), Character::blood_rh_factor, c_dark_gray, c_green, c_light_gray, c_light_green, c_light_red, c_red, c_white, center_print(), display_stat(), io::enum_to_string(), input_context::get_desc(), Character::get_dex(), Character::get_dex_base(), Character::get_int(), Character::get_int_base(), Character::get_per(), Character::get_per_base(), Character::get_str(), Character::get_str_base(), h_light_gray, display::health_string(), Character::height_string(), line(), max(), mvwprintz(), Character::my_blood_type, om_direction::name(), point_zero, right_print(), string_format(), title_STATS, utf8_width(), display::weight_string(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by Character::disp_info().
draw_tip()
static void draw_tip (const catacurses::window & w_tip, const Character & you, const std::string & race, const input_context & ctxt, bool customize_character, int & tip_btn_highlight) static
Definition at line 1073 of file player_display.cpp.
 {
     werase( w_tip );
     // Print name and header
     if( you.custom_profession.empty() ) {
         if( you.crossed_threshold() ) {
             //~ player info window: 1s - name, 2s - gender, 3s - Prof or Mutation name
             mvwprintz( w_tip, point_zero, c_white, _( " %1$s | %2$s | %3$s" ), you.get_name(),
                        you.male ? _( "Male" ) : _( "Female" ), race );
         } else if( you.prof == nullptr || you.prof == profession::generic() ) {
             // Regular person. Nothing interesting.
             //~ player info window: 1s - name, 2s - gender '|' - field separator.
             mvwprintz( w_tip, point_zero, c_white, _( " %1$s | %2$s" ), you.get_name(),
                        you.male ? _( "Male" ) : _( "Female" ) );
         } else {
             mvwprintz( w_tip, point_zero, c_white, _( " %1$s | %2$s | %3$s" ), you.get_name(),
                        you.male ? _( "Male" ) : _( "Female" ),
                        you.prof->gender_appropriate_name( you.male ) );
         }
     } else {
         mvwprintz( w_tip, point_zero, c_white, _( " %1$s | %2$s | %3$s" ), you.get_name(),
                    you.male ? _( "Male" ) : _( "Female" ), you.custom_profession );
     }
     const auto btn_color = [&tip_btn_highlight]( const int btn_to_draw ) {
         if( tip_btn_highlight == btn_to_draw ) {
             return h_light_gray;
         } else {
             return c_light_gray;
         }
     };
     if( customize_character ) {
         right_print( w_tip, 0, 16, btn_color( 0 ), string_format(
                          _( "[<color_yellow>%s</color>] Customize " ),
                          ctxt.get_desc( "SWITCH_GENDER" ) ) );
     }
     right_print( w_tip, 0, 6, btn_color( 1 ), string_format(
                      _( "[<color_yellow>%s</color>] Morale" ),
                      ctxt.get_desc( "morale" ) ) );
     right_print( w_tip, 0, 1, btn_color( 2 ), string_format(
                      _( "[<color_yellow>%s</color>]" ),
                      ctxt.get_desc( "HELP_KEYBINDINGS" ) ) );
     right_print( w_tip, 0, 0, c_light_gray, string_format( "%s", LINE_XOXO_S ) );
     wnoutrefresh( w_tip );
 }
References _, c_light_gray, c_white, Character::crossed_threshold(), Character::custom_profession, profession::gender_appropriate_name(), profession::generic(), input_context::get_desc(), Character::get_name(), h_light_gray, LINE_XOXO_S, Character::male, mvwprintz(), point_zero, Character::prof, right_print(), string_format(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by Character::disp_info().
draw_traits_info()
static void draw_traits_info (const catacurses::window & w_info, const unsigned line, const std::vector< trait_and_var > & traitslist, const unsigned info_line) static
Definition at line 632 of file player_display.cpp.
 {
     werase( w_info );
     if( line < traitslist.size() ) {
         const trait_and_var &cur = traitslist[line];
         const std::string desc =
             string_format( "%s: %s", colorize( cur.name(), cur.trait->get_display_color() ), cur.desc() );
         draw_x_info( w_info, desc, info_line );
     }
     wnoutrefresh( w_info );
 }
References colorize(), trait_and_var::desc(), draw_x_info(), mutation_branch::get_display_color(), line(), trait_and_var::name(), string_format(), trait_and_var::trait, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by draw_info_window().
draw_traits_tab()
static void draw_traits_tab (ui_adaptor & ui, const catacurses::window & w_traits, const unsigned line, const player_display_tab curtab, const std::vector< trait_and_var > & traitslist, const input_context & ctxt) static
Definition at line 594 of file player_display.cpp.
 {
     werase( w_traits );
     const bool is_current_tab = curtab == player_display_tab::traits;
     const nc_color title_col = is_current_tab ? h_light_gray : c_light_gray;
     if( is_current_tab ) {
         ui.set_cursor( w_traits, point_zero );
     }
     center_print( w_traits, 0, title_col, _( title_TRAITS ) );
     right_print( w_traits, 0, 0, title_col, string_format( "[<color_yellow>%s</color>]",
                  ctxt.get_desc( "SELECT_TRAITS_TAB" ) ) );
     const int height = getmaxy( w_traits ) - 1;
     const bool do_draw_scrollbar = height < static_cast<int>( traitslist.size() );
     const int width = getmaxx( w_traits ) - 1 - ( do_draw_scrollbar ? 1 : 0 );
     const auto& [i_start, i_end] = subindex_around_cursor( traitslist.size(), height, line,
                                    is_current_tab );
     for( size_t i = i_start; i < static_cast<size_t>( i_end ); ++i ) {
         const trait_and_var &cur = traitslist[i];
         const nc_color color = cur.trait->get_display_color();
         const bool highlight_line = is_current_tab && i == line;
         const point pos( 1, 1 + i - i_start );
         if( highlight_line ) {
             ui.set_cursor( w_traits, pos );
         }
         trim_and_print( w_traits, pos, width,
                         highlight_line ? hilite( color ) : color, cur.name() );
     }
     if( do_draw_scrollbar ) {
         draw_scrollbar( w_traits, i_start, height, traitslist.size(), point( width + 1, 1 ), c_white,
                         true );
     }
     wnoutrefresh( w_traits );
 }
References _, c_light_gray, c_white, center_print(), color(), draw_scrollbar(), input_context::get_desc(), mutation_branch::get_display_color(), catacurses::getmaxx(), catacurses::getmaxy(), h_light_gray, hilite(), line(), trait_and_var::name(), point_zero, math_opers::pos(), right_print(), string_format(), subindex_around_cursor(), title_TRAITS, trait_and_var::trait, trim_and_print(), catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by Character::disp_info().
draw_x_info()
static void draw_x_info (const catacurses::window & w_info, const std::string & description, const unsigned info_line) static
Definition at line 289 of file player_display.cpp.
 {
     std::vector<std::string> text_lines = foldstring( description, FULL_SCREEN_WIDTH - 3 );
     const int winh = catacurses::getmaxy( w_info );
     const bool do_scroll = text_lines.size() > static_cast<unsigned>( std::abs( winh ) );
     const int first_line = do_scroll ? info_line % ( text_lines.size() + 1 - winh ) : 0;
     const int last_line = do_scroll ? first_line + winh : text_lines.size();
     for( int i = first_line; i < last_line; i++ ) {
         trim_and_print( w_info, point( 1, i - first_line ), FULL_SCREEN_WIDTH - ( do_scroll ? 3 : 2 ),
                         c_light_gray, text_lines[i] );
     }
     if( do_scroll ) {
         draw_scrollbar( w_info, first_line, winh, text_lines.size(), point( FULL_SCREEN_WIDTH - 1, 0 ),
                         c_white, true );
     }
 }
References abs(), c_light_gray, c_white, draw_scrollbar(), foldstring(), FULL_SCREEN_WIDTH, catacurses::getmaxy(), and trim_and_print().
Referenced by draw_bionics_info(), draw_effects_info(), draw_encumbrance_info(), draw_proficiencies_info(), draw_skills_info(), and draw_traits_info().
get_encumbrance_description()
static std::vector<std::string> get_encumbrance_description (const Character & you, const bodypart_id & bp) static
Definition at line 215 of file player_display.cpp.
 {
     std::vector<std::string> s;
     const bodypart *part = you.get_part( bp );
     if( !bp->encumb_text.empty() ) {
         s.emplace_back( colorize( string_format( _( "Encumbrance effects: %s" ), bp->encumb_text ),
                                   c_magenta ) );
     }
     for( const limb_score &sc : limb_score::get_all() ) {
         if( !bp->has_limb_score( sc.getId() ) ) {
             continue;
         }
         float cur_score = part->get_limb_score( sc.getId() );
         float bp_score = bp->get_limb_score( sc.getId() );
         // Check for any global limb score modifiers
         for( const effect &eff : you.get_effects_with_flag( flag_EFFECT_LIMB_SCORE_MOD ) ) {
             cur_score *= eff.get_limb_score_mod( sc.getId(), you.resists_effect( eff ) );
         }
         // Check for local score-modifying effects only if we have any
         if( you.has_flag( flag_EFFECT_LIMB_SCORE_MOD_LOCAL ) ) {
             for( const effect &local : you.get_effects_from_bp( part->get_id() ) ) {
                 float local_mul = 1.0f;
                 if( local.has_flag( flag_EFFECT_LIMB_SCORE_MOD_LOCAL ) ) {
                     local_mul = local.get_limb_score_mod( sc.getId(), you.resists_effect( local ) );
                     cur_score *= local_mul;
                 }
             }
         }
         s.emplace_back( get_score_text( sc.name().translated(), cur_score, bp_score ) );
     }
     for( const character_modifier &mod : character_modifier::get_all() ) {
         for( const auto &sc : mod.use_limb_scores() ) {
             if( sc.second == 0.0f || sc.first.is_null() || !bp->has_limb_score( sc.first ) ) {
                 continue;
             }
             std::string desc = mod.description().translated();
             std::string valstr = colorize( string_format( "%.2f", mod.modifier( you ) ),
                                            limb_score_current_color( part->get_limb_score( sc.first ) * sc.second,
                                                    bp->get_limb_score( sc.first ) * sc.second ) );
             s.emplace_back( string_format( "%s: %s%s", desc, mod.mod_type_str(), valstr ) );
         }
     }
     return s;
 }
References _, bp, c_magenta, colorize(), translation::empty(), body_part_type::encumb_text, flag_EFFECT_LIMB_SCORE_MOD, flag_EFFECT_LIMB_SCORE_MOD_LOCAL, limb_score::get_all(), character_modifier::get_all(), Creature::get_effects_from_bp(), Creature::get_effects_with_flag(), bodypart::get_id(), body_part_type::get_limb_score(), bodypart::get_limb_score(), Creature::get_part(), get_score_text(), Character::has_flag(), body_part_type::has_limb_score(), limb_score_current_color(), Creature::resists_effect(), and string_format().
Referenced by draw_encumbrance_info().
get_line_count()
static int get_line_count (player_display_tab curtab, Character & you, const std::vector< speedlist_entry > & speedlist, std::vector< trait_and_var > & traitslist, const std::vector< bionic_grouping > & bionicslist, const std::vector< std::pair< std::string, std::string >> & effect_name_and_text, const std::vector< HeaderSkill > & skillslist) static
Definition at line 1195 of file player_display.cpp.
 {
     switch( curtab ) {
         case player_display_tab::stats:
             return 9;
         case player_display_tab::encumbrance: {
             const std::vector<std::pair<bodypart_id, bool>> bps = list_and_combine_bps( you, nullptr );
             return bps.size();
         }
         case player_display_tab::speed:
             return speedlist.size();
         case player_display_tab::traits:
             return traitslist.size();
         case player_display_tab::bionics:
             return bionicslist.size();
         case player_display_tab::effects:
             return effect_name_and_text.size();
         case player_display_tab::skills:
             return skillslist.size();
         case player_display_tab::proficiencies:
             return you.display_proficiencies().size();
         case player_display_tab::num_tabs:
             cata_fatal( "Invalid curtab" );
     }
     return 0;
 }
References cata_fatal, Character::display_proficiencies(), and list_and_combine_bps().
Referenced by handle_player_display_action().
get_score_text()
static std::string get_score_text (const std::string & sc_name, float cur_score, float bp_score) static
Definition at line 202 of file player_display.cpp.
 {
     if( std::abs( bp_score ) <= std::numeric_limits<float>::epsilon() ) {
         return std::string();
     }
     nc_color score_c = limb_score_current_color( cur_score, bp_score );
     std::string sc_txt = colorize( string_format( "%.2f (%.f%%)", cur_score,
                                    cur_score * 100.f / bp_score ), score_c );
     //~ 1$ = name of the limb score (ex: Balance), 2$ = current score value (colored)
     return string_format( _( "%1$s score: %2$s" ), sc_name, sc_txt );
 }
References _, abs(), colorize(), limb_score_current_color(), and string_format().
Referenced by get_encumbrance_description().
get_speedlist_entries()
static std::vector<speedlist_entry> get_speedlist_entries (const Character & you, int & move_cost, const std::map< std::string, int > & speed_effects) static
Definition at line 943 of file player_display.cpp.
 {
     std::vector<speedlist_entry> entries;
     for( const std::pair<const std::string, int> &speed_effect : speed_effects ) {
         if( speed_effect.second != 0 ) {
             const speedlist_entry entry { true, speed_effect.first, speed_effect.second, false };
             entries.push_back( entry );
         }
     }
     for( const speed_bonus_effect &effect : you.get_speed_bonus_effects() ) {
         if( effect.bonus != 0 && speed_effects.end() == speed_effects.find( effect.description ) ) {
             const speedlist_entry entry { true, effect.description, effect.bonus, false };
             entries.push_back( entry );
         }
     }
     float movecost = 100;
     for( const run_cost_effect &effect : you.run_cost_effects( movecost ) ) {
         const int percent = std::trunc( effect.times * 100 - 100 ); // truncate toward 0%
         const int constant = std::trunc( effect.plus ); // truncate toward 0
         if( ( effect.times != 1.0 && percent == 0 ) || ( effect.plus != 0 && constant == 0 ) ) {
             continue; // negligible effect
         }
         const speedlist_entry entry { false, effect.description, percent != 0 ? percent : constant, percent != 0 };
         entries.push_back( entry );
     }
     move_cost = static_cast<int>( movecost );
     return entries;
 }
References constant, Character::get_speed_bonus_effects(), Character::run_cost_effects(), and trunc().
Referenced by Character::disp_info().
handle_player_display_action()
static bool handle_player_display_action (Character & you, unsigned int & line, unsigned int & info_line, player_display_tab & curtab, input_context & ctxt, const ui_adaptor & ui_tip, const ui_adaptor & ui_info, const ui_adaptor & ui_stats, const ui_adaptor & ui_encumb, const ui_adaptor & ui_speed, const ui_adaptor & ui_traits, const ui_adaptor & ui_bionics, const ui_adaptor & ui_effects, const ui_adaptor & ui_skills, const ui_adaptor & ui_proficiencies, const std::vector< speedlist_entry > & speedlist, std::vector< trait_and_var > & traitslist, const std::vector< bionic_grouping > & bionicslist, const std::vector< std::pair< std::string, std::string >> & effect_name_and_text, const std::vector< HeaderSkill > & skillslist, bool customize_character, const std::vector< catacurses::window * > & windows, const catacurses::window & w_tip, int & tip_btn_selected) static
Definition at line 1229 of file player_display.cpp.
 {
     const auto invalidate_tab = [&]( const player_display_tab tab ) {
         switch( tab ) {
             case player_display_tab::stats:
                 ui_stats.invalidate_ui();
                 break;
             case player_display_tab::encumbrance:
                 ui_encumb.invalidate_ui();
                 break;
             case player_display_tab::speed:
                 ui_speed.invalidate_ui();
                 break;
             case player_display_tab::traits:
                 ui_traits.invalidate_ui();
                 break;
             case player_display_tab::bionics:
                 ui_bionics.invalidate_ui();
                 break;
             case player_display_tab::effects:
                 ui_effects.invalidate_ui();
                 break;
             case player_display_tab::skills:
                 ui_skills.invalidate_ui();
                 break;
             case player_display_tab::proficiencies:
                 ui_proficiencies.invalidate_ui();
                 break;
             case player_display_tab::num_tabs:
                 cata_fatal( "Invalid tab" );
         }
     };
     unsigned int line_count = get_line_count( curtab, you, speedlist, traitslist, bionicslist,
                               effect_name_and_text, skillslist );
     if( line_count > 0 ) {
         line = std::clamp( line, 0U, line_count - 1 );
         if( curtab == player_display_tab::skills ) {
             skip_skill_headers( skillslist, line, true );
         }
     } else {
         line = 0;
     }
     bool done = false;
     const std::string action = ctxt.handle_input();
     if( navigate_ui_list( action, line, 3, line_count, true ) ) {
         if( tip_btn_selected != -1 ) {
             tip_btn_selected = -1;
             ui_tip.invalidate_ui();
         }
         if( curtab == player_display_tab::skills ) {
             // including actios "PAGE_UP", and "HOME", because these shouldn't wrap
             const bool inc = action == "DOWN" || action == "PAGE_DOWN" || action == "PAGE_UP" ||
                              action == "SCROLL_DOWN" || action == "HOME";
             skip_skill_headers( skillslist, line, inc );
         }
         info_line = 0;
         invalidate_tab( curtab );
         ui_info.invalidate_ui();
     } else if( action == "MOUSE_MOVE" ) {
         int orig_tip_btn = tip_btn_selected;
         tip_btn_selected = -1;
         std::optional<point> p;
         for( size_t i = 0; i < windows.size(); i++ ) {
             p = ctxt.get_coordinates_text( *windows[i] );
             if( p.has_value() && window_contains_point_relative( *windows[i], p.value() ) ) {
                 invalidate_tab( curtab );
                 curtab = player_display_tab( i );
                 invalidate_tab( curtab );
                 line_count = get_line_count( curtab, you, speedlist, traitslist, bionicslist, effect_name_and_text,
                                              skillslist );
                 line = std::clamp( p.value().y - 1, 0, int( line_count ) );
                 ui_info.invalidate_ui();
                 break;
             }
         }
         p = ctxt.get_coordinates_text( w_tip );
         if( p.has_value() && window_contains_point_relative( w_tip, p.value() ) ) {
             int rightX = catacurses::getmaxx( w_tip ) - p.value().x;
             if( rightX  > 1 && rightX < 5 ) {
                 tip_btn_selected = 2;
             } else if( rightX >= 7 && rightX < 17 ) {
                 tip_btn_selected = 1;
             } else if( customize_character && rightX > 17  && rightX <= 30 ) {
                 tip_btn_selected = 0;
             }
         }
         if( orig_tip_btn != tip_btn_selected ) {
             ui_tip.invalidate_ui();
         }
     } else if( action == "LEFT" || action == "PREV_TAB" || action == "RIGHT" || action == "NEXT_TAB" ) {
         if( tip_btn_selected != -1 ) {
             tip_btn_selected = -1;
             ui_tip.invalidate_ui();
         }
         invalidate_tab( curtab );
         curtab = inc_clamp_wrap( curtab, action == "RIGHT" || action == "NEXT_TAB",
                                  player_display_tab::num_tabs );
         invalidate_tab( curtab );
         line = curtab == player_display_tab::skills ? 1 : 0; // avoid a call to skip_skill_headers
         info_line = 0;
         ui_info.invalidate_ui();
     } else if( action == "SELECT_TRAIT_VARIANT" ) {
         if( curtab == player_display_tab::traits ) {
             const mutation_variant *var = traitslist[line].trait->pick_variant_menu();
             you.set_mut_variant( traitslist[line].trait, var );
             const std::string &varid = var == nullptr ? "" : var->id;
             traitslist[line].variant = varid;
         }
     } else if( action == "QUIT" ) {
         done = true;
     } else if( action == "CONFIRM" || action == "SELECT" ) {
         bool header_clicked = false;
         if( action == "SELECT" ) {
             header_clicked = false;
             int mouse_line = -1;
             if( curtab < player_display_tab::num_tabs ) {
                 std::optional<point> p = ctxt.get_coordinates_text( *windows[int( curtab )] );
                 if( p.has_value() && window_contains_point_relative( *windows[int( curtab )], p.value() ) ) {
                     mouse_line = std::clamp( p.value().y - 1, 0, int( line_count ) );
                     header_clicked = p.value().y == 0;
                     if( curtab == player_display_tab::skills && skillslist[mouse_line].is_header ) {
                         mouse_line = -1;
                     }
                 }
             }
             if( tip_btn_selected != -1 ) {
                 switch( tip_btn_selected ) {
                     case 0:
                         if( customize_character ) {
                             on_customize_character( you );
                         }
                         break;
                     case 1:
                         if( you.is_avatar() ) {
                             you.as_avatar()->disp_morale();
                         }
                         break;
                     case 2:
                         ctxt.display_menu();
                         break;
                 }
                 return done;
             } else if( mouse_line == -1 ) {
                 return done;
             }
         }
         switch( curtab ) {
             default:
                 break;
             case player_display_tab::stats:
                 if( header_clicked ) {
                     display_bodygraph( you );
                 } else if( line < 4 && get_option<bool>( "STATS_THROUGH_KILLS" ) && you.is_avatar() ) {
                     you.as_avatar()->upgrade_stat_prompt( static_cast<character_stat>( line ) );
                 }
                 invalidate_tab( curtab );
                 break;
             case player_display_tab::skills: {
                 const Skill *selectedSkill = nullptr;
                 if( line < skillslist.size() && !skillslist[line].is_header ) {
                     selectedSkill = skillslist[line].skill;
                 }
                 if( selectedSkill ) {
                     you.get_skill_level_object( selectedSkill->ident() ).toggleTraining();
                 }
                 invalidate_tab( curtab );
                 ui_info.invalidate_ui();
                 break;
             }
             case player_display_tab::proficiencies:
                 const std::vector<display_proficiency> profs = you.display_proficiencies();
                 show_proficiencies_window( you, profs[line].id );
                 break;
         }
     } else if( action == "CHANGE_PROFESSION_NAME" ) {
         string_input_popup popup;
         popup.title( _( "Profession Name: " ) )
         .width( 25 )
         .text( "" )
         .max_length( 25 )
         .query();
         you.custom_profession = popup.text();
         ui_tip.invalidate_ui();
     } else if( action == "VIEW_PROFICIENCIES" ) {
         show_proficiencies_window( you );
     } else if( action == "morale" ) {
         if( you.is_avatar() ) {
             you.as_avatar()->disp_morale( );
         }
     } else if( action == "VIEW_BODYSTAT" ) {
         display_bodygraph( you );
     } else if( customize_character && action == "SWITCH_GENDER" ) {
         on_customize_character( you );
     } else if( action == "SCROLL_INFOBOX_UP" ) {
         if( info_line > 0 ) {
             --info_line;
             ui_info.invalidate_ui();
         }
     } else if( action == "SCROLL_INFOBOX_DOWN" ) {
         ++info_line;
         ui_info.invalidate_ui();
     } else if( action == "MEDICAL_MENU" ) {
         if( you.is_avatar() ) {
             you.as_avatar()->disp_medical();
         }
     } else if( action == "SELECT_STATS_TAB" ) {
         invalidate_tab( curtab );
         curtab = player_display_tab::stats;
         invalidate_tab( curtab );
         line = 0;
         info_line = 0;
         ui_info.invalidate_ui();
     } else if( action == "SELECT_ENCUMBRANCE_TAB" ) {
         invalidate_tab( curtab );
         curtab = player_display_tab::encumbrance;
         invalidate_tab( curtab );
         line = 0;
         info_line = 0;
         ui_info.invalidate_ui();
     } else if( action == "SELECT_SKILLS_TAB" ) {
         invalidate_tab( curtab );
         curtab = player_display_tab::skills;
         invalidate_tab( curtab );
         line = 1; // avoid a call to skip_skill_headers
         info_line = 0;
         ui_info.invalidate_ui();
     } else if( action == "SELECT_TRAITS_TAB" ) {
         invalidate_tab( curtab );
         curtab = player_display_tab::traits;
         invalidate_tab( curtab );
         line = 0;
         info_line = 0;
         ui_info.invalidate_ui();
     } else if( action == "SELECT_BIONICS_TAB" ) {
         invalidate_tab( curtab );
         curtab = player_display_tab::bionics;
         invalidate_tab( curtab );
         line = 0;
         info_line = 0;
         ui_info.invalidate_ui();
     } else if( action == "SELECT_EFFECTS_TAB" ) {
         invalidate_tab( curtab );
         curtab = player_display_tab::effects;
         invalidate_tab( curtab );
         line = 0;
         info_line = 0;
         ui_info.invalidate_ui();
     } else if( action == "SELECT_PROFICIENCIES_TAB" ) {
         invalidate_tab( curtab );
         curtab = player_display_tab::proficiencies;
         invalidate_tab( curtab );
         line = 0;
         info_line = 0;
         ui_info.invalidate_ui();
     } else if( action == "CHANGE_ARMOR_SPRITE" ) {
         if( you.as_avatar() ) {
             change_armor_sprite( *you.as_avatar() );
         }
     }
     return done;
 }
References _, action, Creature::as_avatar(), cata_fatal, change_armor_sprite(), clamp(), Character::custom_profession, avatar::disp_medical(), avatar::disp_morale(), display_bodygraph(), input_context::display_menu(), Character::display_proficiencies(), input_context::get_coordinates_text(), get_line_count(), Character::get_skill_level_object(), catacurses::getmaxx(), input_context::handle_input(), Skill::ident(), inc_clamp_wrap(), ui_adaptor::invalidate_ui(), Creature::is_avatar(), line(), navigate_ui_list(), on_customize_character(), popup(), Character::set_mut_variant(), show_proficiencies_window(), skip_skill_headers(), keycode::tab, SkillLevel::toggleTraining(), avatar::upgrade_stat_prompt(), and window_contains_point_relative().
Referenced by Character::disp_info().
is_cqb_skill()
static bool is_cqb_skill (const skill_id & id) static
Definition at line 261 of file player_display.cpp.
 {
     // TODO: this skill list here is used in other places as well. Useless redundancy and
     // dependency. Maybe change it into a flag of the skill that indicates it's a skill used
     // by the bionic?
     static const std::array<skill_id, 5> cqb_skills = { {
             skill_melee, skill_unarmed, skill_cutting,
             skill_bashing, skill_stabbing,
         }
     };
     return std::find( cqb_skills.begin(), cqb_skills.end(), id ) != cqb_skills.end();
 }
References skill_bashing, skill_cutting, skill_melee, skill_stabbing, and skill_unarmed.
Referenced by draw_skills_tab().
limb_score_current_color()
static nc_color limb_score_current_color (float cur_score, float bp_score) static
Definition at line 188 of file player_display.cpp.
 {
     if( cur_score < bp_score * 0.25 ) {
         return c_brown;
     }
     if( cur_score < bp_score * 0.5 ) {
         return c_light_red;
     }
     if( cur_score < bp_score * 0.8 ) {
         return c_yellow;
     }
     return c_white;
 }
References c_brown, c_light_red, c_white, and c_yellow.
Referenced by get_encumbrance_description(), and get_score_text().
list_and_combine_bps()
static std::vector<std::pair<bodypart_id, bool> > list_and_combine_bps (const Character & p, const item * selected_clothing) static
Definition at line 98 of file player_display.cpp.
 {
     // bool represents whether the part has been combined with its other half
     std::vector<std::pair<bodypart_id, bool>> bps;
     for( const bodypart_id &bp : p.get_all_body_parts( get_body_part_flags::sorted ) ) {
         // assuming that a body part has at most one other half
         if( should_combine_bps( p, bp, bp->opposite_part.id(), selected_clothing ) ) {
             if( std::find( bps.begin(), bps.end(), std::pair<bodypart_id, bool>( bp->opposite_part.id(),
                            true ) ) == bps.end() ) {
                 // only add one
                 bps.emplace_back( bp, true );
             }
         } else {
             bps.emplace_back( bp, false );
         }
     }
     return bps;
 }
References bp, Creature::get_all_body_parts(), string_id< T >::id(), body_part_type::opposite_part, should_combine_bps(), and sorted.
Referenced by draw_encumbrance_info(), get_line_count(), and Character::print_encumbrance().
on_customize_character()
static void on_customize_character (Character & you) static
Definition at line 1127 of file player_display.cpp.
 {
     uilist cmenu;
     cmenu.title = _( "Customize Character" );
     cmenu.addentry( 1, true, 'y', _( "Change gender" ) );
     cmenu.addentry( 2, true, 'n', _( "Change name" ) );
     cmenu.query();
     if( cmenu.ret == 1 ) {
         you.male = !you.male;
         popup( _( "Gender set to %s." ), you.male ? _( "Male" ) : _( "Female" ) );
     } else if( cmenu.ret == 2 ) {
         std::string filterstring = you.play_name.value_or( std::string() );
         string_input_popup popup;
         popup
         .title( _( "New name ( leave empty to reset ):" ) )
         .width( 85 )
         .edit( filterstring );
         if( popup.confirmed() ) {
             if( filterstring.empty() ) {
                 you.play_name.reset();
             } else {
                 you.play_name = filterstring;
             }
         }
     }
 }
References _, uilist::addentry(), Character::male, Character::play_name, popup(), uilist::query(), uilist::ret, and uilist::title.
Referenced by handle_player_display_action().
should_combine_bps()
static bool should_combine_bps (const Character & p, const bodypart_id & l, const bodypart_id & r, const item * selected_clothing) static
Definition at line 79 of file player_display.cpp.
 {
     const encumbrance_data &enc_l = p.get_part_encumbrance_data( l );
     const encumbrance_data &enc_r = p.get_part_encumbrance_data( r );
     return l != r && // are different parts
            l ==  r->opposite_part && r == l->opposite_part && // are complementary parts
            // same encumbrance & temperature
            enc_l == enc_r &&
            temperature_print_rescaling( p.get_part_temp_conv( l ) ) == temperature_print_rescaling(
                p.get_part_temp_conv( r ) ) &&
            // selected_clothing covers both or neither parts
            ( !selected_clothing || ( selected_clothing->covers( l ) == selected_clothing->covers( r ) ) ) &&
            // they have the same HP
            p.get_part_hp_cur( l ) == p.get_part_hp_cur( r );
 }
References item::covers(), Creature::get_part_encumbrance_data(), Creature::get_part_hp_cur(), Creature::get_part_temp_conv(), body_part_type::opposite_part, and temperature_print_rescaling().
Referenced by list_and_combine_bps().
temperature_print_rescaling()
static int temperature_print_rescaling (units::temperature temp) static
Definition at line 74 of file player_display.cpp.
 {
     return ( units::to_legacy_bodypart_temp( temp ) / 100.0 ) * 2 - 100;
 }
References temp, and units::to_legacy_bodypart_temp().
Referenced by Character::print_encumbrance(), and should_combine_bps().
Variable Documentation
bio_cqb
const bionic_id bio_cqb("bio_cqb") ("bio_cqb") static
Referenced by draw_skills_tab().
grid_width
const unsigned int grid_width = 26 static
Definition at line 71 of file player_display.cpp.
Referenced by Character::disp_info().
skill_bashing
const skill_id skill_bashing("bashing") ("bashing") static
Referenced by is_cqb_skill().
skill_cutting
const skill_id skill_cutting("cutting") ("cutting") static
Referenced by is_cqb_skill().
skill_dodge
const skill_id skill_dodge("dodge") ("dodge") static
Referenced by draw_skills_tab().
skill_melee
const skill_id skill_melee("melee") ("melee") static
Referenced by is_cqb_skill().
skill_stabbing
const skill_id skill_stabbing("stabbing") ("stabbing") static
Referenced by is_cqb_skill().
skill_unarmed
const skill_id skill_unarmed("unarmed") ("unarmed") static
Referenced by is_cqb_skill().
title_BIONICS
const std::string title_BIONICS = translate_marker("BIONICS") static
Definition at line 67 of file player_display.cpp.
Referenced by draw_bionics_tab().
title_EFFECTS
const std::string title_EFFECTS = translate_marker("EFFECTS") static
Definition at line 63 of file player_display.cpp.
Referenced by draw_effects_tab().
title_ENCUMB
const std::string title_ENCUMB = translate_marker("ENCUMBRANCE AND WARMTH") static
Definition at line 62 of file player_display.cpp.
Referenced by draw_encumbrance_tab().
title_MOVE_COST
const std::string title_MOVE_COST = translate_marker("MOVE COST") static
Definition at line 65 of file player_display.cpp.
Referenced by draw_speed_tab().
title_PROFICIENCIES
const std::string title_PROFICIENCIES = translate_marker("PROFICIENCIES") static
Definition at line 69 of file player_display.cpp.
Referenced by draw_proficiencies_tab().
title_SKILLS
const std::string title_SKILLS = translate_marker("SKILLS") static
Definition at line 66 of file player_display.cpp.
Referenced by draw_skills_tab().
title_SPEED
const std::string title_SPEED = translate_marker("SPEED") static
Definition at line 64 of file player_display.cpp.
Referenced by draw_speed_tab().
title_STATS
const std::string title_STATS = translate_marker("STATS") static
Definition at line 61 of file player_display.cpp.
Referenced by draw_stats_tab().
title_TRAITS
const std::string title_TRAITS = translate_marker("TRAITS") static
Definition at line 68 of file player_display.cpp.
Referenced by draw_traits_tab().
trait_TROGLO
const trait_id trait_TROGLO("TROGLO") ("TROGLO") static
Referenced by Character::disp_info().
trait_TROGLO2
const trait_id trait_TROGLO2("TROGLO2") ("TROGLO2") static
Referenced by Character::disp_info().
trait_TROGLO3
const trait_id trait_TROGLO3("TROGLO3") ("TROGLO3") static
Referenced by Character::disp_info().