Cataclysm DDA: src/player_activity.cpp File Reference
player_activity.cpp File Reference
#include "player_activity.h"
#include <algorithm>
#include <memory>
#include <new>
#include "activity_handlers.h"
#include "activity_type.h"
#include "avatar.h"
#include "calendar.h"
#include "character.h"
#include "construction.h"
#include "effect_on_condition.h"
#include "field.h"
#include "event_bus.h"
#include "game.h"
#include "item.h"
#include "itype.h"
#include "map.h"
#include "rng.h"
#include "skill.h"
#include "sounds.h"
#include "stomach.h"
#include "string_formatter.h"
#include "translations.h"
#include "ui.h"
#include "uistate.h"
#include "units.h"
#include "value_ptr.h"
Functions
template<typename T >
bool containers_equal (const T &left, const T &right)
Variables
static const activity_id ACT_ADV_INVENTORY ("ACT_ADV_INVENTORY")
static const activity_id ACT_AIM ("ACT_AIM")
static const activity_id ACT_ARMOR_LAYERS ("ACT_ARMOR_LAYERS")
static const activity_id ACT_ATM ("ACT_ATM")
static const activity_id ACT_BUILD ("ACT_BUILD")
static const activity_id ACT_CHOP_LOGS ("ACT_CHOP_LOGS")
static const activity_id ACT_CHOP_PLANKS ("ACT_CHOP_PLANKS")
static const activity_id ACT_CHOP_TREE ("ACT_CHOP_TREE")
static const activity_id ACT_CLEAR_RUBBLE ("ACT_CLEAR_RUBBLE")
static const activity_id ACT_CONSUME_DRINK_MENU ("ACT_CONSUME_DRINK_MENU")
static const activity_id ACT_CONSUME_FOOD_MENU ("ACT_CONSUME_FOOD_MENU")
static const activity_id ACT_CONSUME_MEDS_MENU ("ACT_CONSUME_MEDS_MENU")
static const activity_id ACT_EAT_MENU ("ACT_EAT_MENU")
static const activity_id ACT_HACKSAW ("ACT_HACKSAW")
static const activity_id ACT_HEATING ("ACT_HEATING")
static const activity_id ACT_INVOKE_ITEM ("ACT_INVOKE_ITEM")
static const activity_id ACT_JACKHAMMER ("ACT_JACKHAMMER")
static const activity_id ACT_MIGRATION_CANCEL ("ACT_MIGRATION_CANCEL")
static const activity_id ACT_NULL ("ACT_NULL")
static const activity_id ACT_PICKAXE ("ACT_PICKAXE")
static const activity_id ACT_PICKUP_MENU ("ACT_PICKUP_MENU")
static const activity_id ACT_READ ("ACT_READ")
static const activity_id ACT_SPELLCASTING ("ACT_SPELLCASTING")
static const activity_id ACT_TRAVELLING ("ACT_TRAVELLING")
static const activity_id ACT_VEHICLE ("ACT_VEHICLE")
static const activity_id ACT_VIEW_RECIPE ("ACT_VIEW_RECIPE")
static const activity_id ACT_WAIT_STAMINA ("ACT_WAIT_STAMINA")
static const activity_id ACT_WORKOUT_ACTIVE ("ACT_WORKOUT_ACTIVE")
static const activity_id ACT_WORKOUT_HARD ("ACT_WORKOUT_HARD")
static const activity_id ACT_WORKOUT_LIGHT ("ACT_WORKOUT_LIGHT")
static const activity_id ACT_WORKOUT_MODERATE ("ACT_WORKOUT_MODERATE")
static const efftype_id effect_nausea ("nausea")
Function Documentation
containers_equal()
template<typename T > bool containers_equal (const T & left, const T & right)
Definition at line 426 of file player_activity.cpp.
 {
     if( left.size() != right.size() ) {
         return false;
     }
     return std::equal( left.begin(), left.end(), right.begin() );
 }
References keycode::left, and keycode::right.
Variable Documentation
ACT_ADV_INVENTORY
const activity_id ACT_ADV_INVENTORY("ACT_ADV_INVENTORY") ("ACT_ADV_INVENTORY") static
Referenced by player_activity::get_progress_message().
ACT_AIM
const activity_id ACT_AIM("ACT_AIM") ("ACT_AIM") static
Referenced by player_activity::get_progress_message().
ACT_ARMOR_LAYERS
const activity_id ACT_ARMOR_LAYERS("ACT_ARMOR_LAYERS") ("ACT_ARMOR_LAYERS") static
Referenced by player_activity::get_progress_message().
ACT_ATM
const activity_id ACT_ATM("ACT_ATM") ("ACT_ATM") static
Referenced by player_activity::get_progress_message().
ACT_BUILD
const activity_id ACT_BUILD("ACT_BUILD") ("ACT_BUILD") static
Referenced by player_activity::get_progress_message().
ACT_CHOP_LOGS
const activity_id ACT_CHOP_LOGS("ACT_CHOP_LOGS") ("ACT_CHOP_LOGS") static
Referenced by player_activity::get_progress_message().
ACT_CHOP_PLANKS
const activity_id ACT_CHOP_PLANKS("ACT_CHOP_PLANKS") ("ACT_CHOP_PLANKS") static
Referenced by player_activity::get_progress_message().
ACT_CHOP_TREE
const activity_id ACT_CHOP_TREE("ACT_CHOP_TREE") ("ACT_CHOP_TREE") static
Referenced by player_activity::get_progress_message().
ACT_CLEAR_RUBBLE
const activity_id ACT_CLEAR_RUBBLE("ACT_CLEAR_RUBBLE") ("ACT_CLEAR_RUBBLE") static
Referenced by player_activity::can_resume_with().
ACT_CONSUME_DRINK_MENU
const activity_id ACT_CONSUME_DRINK_MENU("ACT_CONSUME_DRINK_MENU") ("ACT_CONSUME_DRINK_MENU") static
Referenced by player_activity::get_progress_message().
ACT_CONSUME_FOOD_MENU
const activity_id ACT_CONSUME_FOOD_MENU("ACT_CONSUME_FOOD_MENU") ("ACT_CONSUME_FOOD_MENU") static
Referenced by player_activity::get_progress_message().
ACT_CONSUME_MEDS_MENU
const activity_id ACT_CONSUME_MEDS_MENU("ACT_CONSUME_MEDS_MENU") ("ACT_CONSUME_MEDS_MENU") static
Referenced by player_activity::get_progress_message().
ACT_EAT_MENU
const activity_id ACT_EAT_MENU("ACT_EAT_MENU") ("ACT_EAT_MENU") static
Referenced by player_activity::get_progress_message().
ACT_HACKSAW
const activity_id ACT_HACKSAW("ACT_HACKSAW") ("ACT_HACKSAW") static
Referenced by player_activity::get_progress_message().
ACT_HEATING
const activity_id ACT_HEATING("ACT_HEATING") ("ACT_HEATING") static
Referenced by player_activity::get_progress_message().
ACT_INVOKE_ITEM
const activity_id ACT_INVOKE_ITEM("ACT_INVOKE_ITEM") ("ACT_INVOKE_ITEM") static
Referenced by player_activity::get_progress_message().
ACT_JACKHAMMER
const activity_id ACT_JACKHAMMER("ACT_JACKHAMMER") ("ACT_JACKHAMMER") static
Referenced by player_activity::get_progress_message().
ACT_MIGRATION_CANCEL
const activity_id ACT_MIGRATION_CANCEL("ACT_MIGRATION_CANCEL") ("ACT_MIGRATION_CANCEL") static
Referenced by player_activity::do_turn().
ACT_NULL
const activity_id ACT_NULL("ACT_NULL") ("ACT_NULL") static
Referenced by player_activity::get_progress_message(), and player_activity::player_activity().
ACT_PICKAXE
const activity_id ACT_PICKAXE("ACT_PICKAXE") ("ACT_PICKAXE") static
Referenced by player_activity::get_progress_message().
ACT_PICKUP_MENU
const activity_id ACT_PICKUP_MENU("ACT_PICKUP_MENU") ("ACT_PICKUP_MENU") static
Referenced by player_activity::get_progress_message().
ACT_READ
const activity_id ACT_READ("ACT_READ") ("ACT_READ") static
Referenced by player_activity::get_progress_message().
ACT_SPELLCASTING
const activity_id ACT_SPELLCASTING("ACT_SPELLCASTING") ("ACT_SPELLCASTING") static
Referenced by player_activity::get_progress_message().
ACT_TRAVELLING
const activity_id ACT_TRAVELLING("ACT_TRAVELLING") ("ACT_TRAVELLING") static
Referenced by player_activity::do_turn().
ACT_VEHICLE
const activity_id ACT_VEHICLE("ACT_VEHICLE") ("ACT_VEHICLE") static
Referenced by player_activity::can_resume_with(), and player_activity::get_progress_message().
ACT_VIEW_RECIPE
const activity_id ACT_VIEW_RECIPE("ACT_VIEW_RECIPE") ("ACT_VIEW_RECIPE") static
Referenced by player_activity::get_progress_message().
ACT_WAIT_STAMINA
const activity_id ACT_WAIT_STAMINA("ACT_WAIT_STAMINA") ("ACT_WAIT_STAMINA") static
Referenced by player_activity::do_turn().
ACT_WORKOUT_ACTIVE
const activity_id ACT_WORKOUT_ACTIVE("ACT_WORKOUT_ACTIVE") ("ACT_WORKOUT_ACTIVE") static
Referenced by player_activity::do_turn().
ACT_WORKOUT_HARD
const activity_id ACT_WORKOUT_HARD("ACT_WORKOUT_HARD") ("ACT_WORKOUT_HARD") static
Referenced by player_activity::do_turn().
ACT_WORKOUT_LIGHT
const activity_id ACT_WORKOUT_LIGHT("ACT_WORKOUT_LIGHT") ("ACT_WORKOUT_LIGHT") static
Referenced by player_activity::do_turn().
ACT_WORKOUT_MODERATE
const activity_id ACT_WORKOUT_MODERATE("ACT_WORKOUT_MODERATE") ("ACT_WORKOUT_MODERATE") static
Referenced by player_activity::do_turn().
effect_nausea
const efftype_id effect_nausea("nausea") ("nausea") static
Referenced by player_activity::do_turn().