Cataclysm DDA: src/point.cpp File Reference
point.cpp File Reference
#include "point.h"
#include <cmath>
#include <algorithm>
#include <sstream>
#include <string>
#include <type_traits>
#include "debug.h"
Functions
std::ostream & operator<< (std::ostream &os, const point &pos)
std::ostream & operator<< (std::ostream &os, const tripoint &pos)
std::istream & operator>> (std::istream &is, point &pos)
std::istream & operator>> (std::istream &is, tripoint &pos)
std::vector< tripoint > closest_points_first (const tripoint &center, int max_dist)
Following functions return points in a spiral pattern starting at center_x/center_y until it hits the radius.
std::vector< tripoint > closest_points_first (const tripoint &center, int min_dist, int max_dist)
std::vector< point > closest_points_first (const point &center, int max_dist)
std::vector< point > closest_points_first (const point &center, int min_dist, int max_dist)
Function Documentation
closest_points_first() [1/4]
std::vector<point> closest_points_first (const point & center, int max_dist)
Definition at line 139 of file point.cpp.
 {
     return closest_points_first( center, 0, max_dist );
 }
References center, and closest_points_first().
closest_points_first() [2/4]
std::vector<point> closest_points_first (const point & center, int min_dist, int max_dist)
Definition at line 144 of file point.cpp.
 {
     min_dist = std::max( min_dist, 0 );
     max_dist = std::max( max_dist, 0 );
     if( min_dist > max_dist ) {
         return {};
     }
     const int min_edge = min_dist * 2 + 1;
     const int max_edge = max_dist * 2 + 1;
     const int n = max_edge * max_edge - ( min_edge - 2 ) * ( min_edge - 2 );
     const bool is_center_included = min_dist == 0;
     std::vector<point> result;
     result.reserve( n + ( is_center_included ? 1 : 0 ) );
     if( is_center_included ) {
         result.push_back( center );
     }
     int x_init = std::max( min_dist, 1 );
     point p( x_init, 1 - x_init );
     point d( point_east );
     for( int i = 0; i < n; i++ ) {
         result.push_back( center + p );
         if( p.x == p.y || ( p.x < 0 && p.x == -p.y ) || ( p.x > 0 && p.x == 1 - p.y ) ) {
             std::swap( d.x, d.y );
             d.x = -d.x;
         }
         p.x += d.x;
         p.y += d.y;
     }
     return result;
 }
References center, max(), point_east, cata::swap(), point::x, and point::y.
closest_points_first() [3/4]
std::vector<tripoint> closest_points_first (const tripoint & center, int max_dist)
Following functions return points in a spiral pattern starting at center_x/center_y until it hits the radius.
Clockwise fashion. Credit to Tom J Nowell; http://stackoverflow.com/a/1555236/1269969
Definition at line 120 of file point.cpp.
 {
     return closest_points_first( center, 0, max_dist );
 }
References center.
Referenced by closest_points_first().
closest_points_first() [4/4]
std::vector<tripoint> closest_points_first (const tripoint & center, int min_dist, int max_dist)
Definition at line 125 of file point.cpp.
 {
     const std::vector<point> points = closest_points_first( center.xy(), min_dist, max_dist );
     std::vector<tripoint> result;
     result.reserve( points.size() );
     for( const point &p : points ) {
         result.emplace_back( p, center.z );
     }
     return result;
 }
References center, and closest_points_first().
operator<<() [1/2]
std::ostream& operator<< (std::ostream & os, const point & pos)
Definition at line 94 of file point.cpp.
 {
     return os << "(" << pos.x << "," << pos.y << ")";
 }
operator<<() [2/2]
std::ostream& operator<< (std::ostream & os, const tripoint & pos)
Definition at line 99 of file point.cpp.
 {
     return os << "(" << pos.x << "," << pos.y << "," << pos.z << ")";
 }
operator>>() [1/2]
std::istream& operator>> (std::istream & is, point & pos)
Definition at line 104 of file point.cpp.
 {
     char c;
     is.get( c ) &&c == '(' &&is >> pos.x &&is.get( c ) &&c == ',' &&is >> pos.y &&
                                 is.get( c ) &&c == ')';
     return is;
 }
operator>>() [2/2]
std::istream& operator>> (std::istream & is, tripoint & pos)
Definition at line 112 of file point.cpp.
 {
     char c;
     is.get( c ) &&c == '(' &&is >> pos.x &&is.get( c ) &&c == ',' &&is >> pos.y &&
                                 is.get( c ) &&c == ',' &&is >> pos.z &&is.get( c ) &&c == ')';
     return is;
 }