Cataclysm DDA: src/profession.cpp File Reference
profession.cpp File Reference
#include "profession.h"
#include <algorithm>
#include <cmath>
#include <functional>
#include <iterator>
#include <map>
#include <memory>
#include "game.h"
#include "achievement.h"
#include "addiction.h"
#include "avatar.h"
#include "calendar.h"
#include "debug.h"
#include "flag.h"
#include "generic_factory.h"
#include "item.h"
#include "item_group.h"
#include "itype.h"
#include "json.h"
#include "magic.h"
#include "mission.h"
#include "mutation.h"
#include "options.h"
#include "past_games_info.h"
#include "past_achievements_info.h"
#include "pimpl.h"
#include "translations.h"
#include "type_id.h"
#include "visitable.h"
Classes
class json_item_substitution
struct json_item_substitution::trait_requirements
struct json_item_substitution::substitution
struct json_item_substitution::substitution::info
class skilllevel_reader
class addiction_reader
class item_reader
Namespaces
anonymous_namespace{profession.cpp}
Functions
static time_point advanced_spawn_time ()
static void clear_faults (item &it)
Variables
static const achievement_id achievement_achievement_arcade_mode ("achievement_arcade_mode")
generic_factory< profession > anonymous_namespace{profession.cpp}::all_profs ("profession")
static class json_item_substitution item_substitutions
static profession_blacklist prof_blacklist
Function Documentation
advanced_spawn_time()
static time_point advanced_spawn_time () static
Definition at line 498 of file profession.cpp.
 {
     return calendar::start_of_game;
 }
References calendar::start_of_game.
Referenced by json_item_substitution::get_bonus_items(), json_item_substitution::get_substitution(), and profession::items().
clear_faults()
static void clear_faults (item & it) static
Definition at line 508 of file profession.cpp.
 {
     if( it.get_var( "dirt", 0 ) > 0 ) {
         it.set_var( "dirt", 0 );
     }
     it.faults.clear();
 }
References item::faults, item::get_var(), and item::set_var().
Referenced by profession::items().
Variable Documentation
achievement_achievement_arcade_mode
const achievement_id achievement_achievement_arcade_mode("achievement_arcade_mode") ("achievement_arcade_mode") static
Referenced by profession::can_pick().
item_substitutions
class json_item_substitution item_substitutions static
Referenced by profession::check_definitions(), profession::items(), profession::load_item_substitutions(), and profession::reset().
prof_blacklist
profession_blacklist prof_blacklist static
Definition at line 86 of file profession.cpp.
Referenced by profession::check_definitions(), profession::is_blacklisted(), profession_blacklist::load_profession_blacklist(), and profession_blacklist::reset().