Cataclysm DDA: src/ranged.cpp File Reference
ranged.cpp File Reference
#include "ranged.h"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <functional>
#include <iterator>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "activity_actor_definitions.h"
#include "avatar.h"
#include "bionics.h"
#include "ballistics.h"
#include "cached_options.h"
#include "calendar.h"
#include "cata_scope_helpers.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "color.h"
#include "creature_tracker.h"
#include "cursesdef.h"
#include "damage.h"
#include "debug.h"
#include "dispersion.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "flag.h"
#include "game.h"
#include "game_constants.h"
#include "gun_mode.h"
#include "input.h"
#include "input_context.h"
#include "item.h"
#include "item_location.h"
#include "itype.h"
#include "line.h"
#include "magic.h"
#include "map.h"
#include "math_defines.h"
#include "memory_fast.h"
#include "messages.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "panels.h"
#include "pocket_type.h"
#include "point.h"
#include "projectile.h"
#include "ret_val.h"
#include "rng.h"
#include "skill.h"
#include "sounds.h"
#include "string_formatter.h"
#include "translations.h"
#include "trap.h"
#include "try_parse_integer.h"
#include "type_id.h"
#include "ui.h"
#include "ui_manager.h"
#include "units.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "vpart_position.h"
#include "weakpoint.h"
Classes
class target_ui
struct target_ui::turret_with_lof
struct confidence_rating
struct aim_type_prediction
struct aim_type_prediction::aim_confidence
struct recoil_prediction
Typedefs
using RatingVector = std::vector< std::tuple< double, char, std::string > >
Functions
static projectile make_gun_projectile (const item &gun)
static int time_to_attack (const Character &p, const itype &firing)
static void cycle_action (item &weap, const itype_id &ammo, const tripoint &pos)
Handle spent ammo casings and linkages.
static void make_gun_sound_effect (const Character &p, bool burst, item *weapon)
double occupied_tile_fraction (creature_size target_size)
int range_with_even_chance_of_good_hit (int dispersion)
int throw_cost (const Character &c, const item &to_throw)
double calculate_aim_cap (const Character &you, const tripoint &target)
double calc_steadiness (const Character &you, const item &weapon, const tripoint &pos, double predicted_recoil)
static std::optional< int > character_throw_assist (const Character &guy)
static float throwing_skill_adjusted (const Character &guy)
void practice_archery_proficiency (Character &p, const item &relevant)
static void mod_stamina_archery (Character &you, const item &relevant)
static void do_aim (Character &you, const item &relevant, const double min_recoil)
static int print_steadiness (const catacurses::window &w, int line_number, double steadiness)
static double confidence_estimate (const Target_attributes &attributes, const dispersion_sources &dispersion)
static aim_type get_default_aim_type ()
static std::string get_colored_bar (const double val, const int width, const std::string &label, RatingVector::iterator begin, RatingVector::iterator end)
static double target_size_in_moa (int range, double size)
static recoil_prediction predict_recoil (const Character &you, const item &weapon, const Target_attributes &target, int sight_dispersion, const aim_type &aim_mode, double start_recoil)
static std::vector< aim_type_prediction > calculate_ranged_chances (const target_ui &ui, const Character &you, target_ui::TargetMode mode, const input_context &ctxt, const item &weapon, const dispersion_sources &dispersion, const std::vector< confidence_rating > &confidence_ratings, const Target_attributes &target, const tripoint &pos)
static void print_confidence_ratings (const catacurses::window &w, const std::vector< confidence_rating > &ratings, int &line_number, int width, int &column_number, nc_color col)
static void print_confidence_rating_bar (const catacurses::window &w, aim_type_prediction prediction, int &line_number, int width, nc_color col)
static int print_ranged_chance (const catacurses::window &w, int line_number, const std::vector< aim_type_prediction > &aim_chances)
static bool pl_sees (const Creature &cr)
static int print_aim (const target_ui &ui, Character &you, const catacurses::window &w, int line_number, input_context &ctxt, const item &weapon, const tripoint &pos)
static void draw_throw_aim (const target_ui &ui, const Character &you, const catacurses::window &w, int &text_y, input_context &ctxt, const item &weapon, const tripoint &target_pos, bool is_blind_throw)
static double dispersion_from_skill (double skill, double weapon_dispersion)
bool gunmode_checks_common (avatar &you, const map &m, std::vector< std::string > &messages, const gun_mode &gmode)
Common checks for gunmode (when firing a weapon / manually firing turret)
bool gunmode_checks_weapon (avatar &you, const map &m, std::vector< std::string > &messages, const gun_mode &gmode)
Various checks for gunmode when firing a weapon.
Variables
static const ammotype ammo_120mm ("120mm")
static const ammotype ammo_12mm ("12mm")
static const ammotype ammo_40x46mm ("40x46mm")
static const ammotype ammo_40x53mm ("40x53mm")
static const ammotype ammo_66mm ("66mm")
static const ammotype ammo_84x246mm ("84x246mm")
static const ammotype ammo_RPG_7 ("RPG-7")
static const ammotype ammo_arrow ("arrow")
static const ammotype ammo_atgm ("atgm")
static const ammotype ammo_atlatl ("atlatl")
static const ammotype ammo_bolt ("bolt")
static const ammotype ammo_bolt_ballista ("bolt_ballista")
static const ammotype ammo_flammable ("flammable")
static const ammotype ammo_homebrew_rocket ("homebrew_rocket")
static const ammotype ammo_m235 ("m235")
static const ammotype ammo_metal_rail ("metal_rail")
static const ammotype ammo_strange_arrow ("strange_arrow")
static const bionic_id bio_railgun ("bio_railgun")
static const character_modifier_id character_modifier_melee_thrown_move_balance_mod ("melee_thrown_move_balance_mod")
static const character_modifier_id character_modifier_melee_thrown_move_lift_mod ("melee_thrown_move_lift_mod")
static const character_modifier_id character_modifier_ranged_dispersion_manip_mod ("ranged_dispersion_manip_mod")
static const character_modifier_id character_modifier_thrown_dex_mod ("thrown_dex_mod")
static const damage_type_id damage_bash ("bash")
static const damage_type_id damage_cut ("cut")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_hit_by_player ("hit_by_player")
static const efftype_id effect_on_roof ("on_roof")
static const efftype_id effect_quadruped_full ("quadruped_full")
static const fault_id fault_gun_blackpowder ("fault_gun_blackpowder")
static const fault_id fault_gun_chamber_spent ("fault_gun_chamber_spent")
static const fault_id fault_gun_dirt ("fault_gun_dirt")
static const fault_id fault_overheat_explosion ("fault_overheat_explosion")
static const fault_id fault_overheat_melting ("fault_overheat_melting")
static const fault_id fault_overheat_safety ("fault_overheat_safety")
static const fault_id fault_overheat_venting ("fault_overheat_venting")
static const flag_id json_flag_FILTHY ("FILTHY")
static const material_id material_budget_steel ("budget_steel")
static const material_id material_case_hardened_steel ("case_hardened_steel")
static const material_id material_glass ("glass")
static const material_id material_high_steel ("high_steel")
static const material_id material_iron ("iron")
static const material_id material_low_steel ("low_steel")
static const material_id material_med_steel ("med_steel")
static const material_id material_steel ("steel")
static const material_id material_tempered_steel ("tempered_steel")
static const proficiency_id proficiency_prof_bow_basic ("prof_bow_basic")
static const proficiency_id proficiency_prof_bow_expert ("prof_bow_expert")
static const proficiency_id proficiency_prof_bow_master ("prof_bow_master")
static const skill_id skill_archery ("archery")
static const skill_id skill_dodge ("dodge")
static const skill_id skill_driving ("driving")
static const skill_id skill_gun ("gun")
static const skill_id skill_launcher ("launcher")
static const skill_id skill_swimming ("swimming")
static const skill_id skill_throw ("throw")
static const trait_id trait_BRAWLER ("BRAWLER")
static const trait_id trait_PYROMANIA ("PYROMANIA")
static const trap_str_id tr_practice_target ("tr_practice_target")
static const std::set< material_id > ferric = { material_iron, material_steel, material_budget_steel, material_case_hardened_steel, material_high_steel, material_low_steel, material_med_steel, material_tempered_steel }
static constexpr int AIF_DURATION_LIMIT = 10
Typedef Documentation
RatingVector
using RatingVector = std::vector<std::tuple<double, char, std::string> >
Definition at line 1584 of file ranged.cpp.
Function Documentation
calc_steadiness()
double calc_steadiness (const Character & you, const item & weapon, const tripoint & pos, double predicted_recoil)
Definition at line 1156 of file ranged.cpp.
 {
     const double min_recoil = calculate_aim_cap( you, pos );
     const double effective_recoil = you.most_accurate_aiming_method_limit( weapon );
     const double min_dispersion = std::max( min_recoil, effective_recoil );
     const double steadiness_range = MAX_RECOIL - min_dispersion;
     // This is a relative measure of how steady the player's aim is,
     // 0 is the best the player can do.
     const double steady_score = std::max( 0.0, predicted_recoil - min_dispersion );
     // Fairly arbitrary cap on steadiness...
     return 1.0 - ( steady_score / steadiness_range );
 }
References calculate_aim_cap(), max(), MAX_RECOIL, Character::most_accurate_aiming_method_limit(), and math_opers::pos().
Referenced by calculate_ranged_chances(), and avatar::rebuild_aim_cache().
calculate_aim_cap()
double calculate_aim_cap (const Character & you, const tripoint & target)
Definition at line 1140 of file ranged.cpp.
 {
     double min_recoil = 0.0;
     const Creature *victim = get_creature_tracker().creature_at( target, true );
     // No p.sees_with_specials() here because special senses are not precise enough
     // to give creature's exact size & position, only which tile it occupies
     if( victim == nullptr || ( !you.sees( *victim ) && !you.sees_with_infrared( *victim ) ) ) {
         const int range = rl_dist( you.pos(), target );
         // Get angle of triangle that spans the target square.
         const double angle = 2 * atan2( 0.5, range );
         // Convert from radians to arcmin.
         min_recoil = 60 * 180 * angle / M_PI;
     }
     return min_recoil;
 }
References atan2(), creature_tracker::creature_at(), get_creature_tracker(), M_PI, Creature::pos(), rl_dist(), Character::sees(), and Character::sees_with_infrared().
Referenced by target_ui::action_aim(), target_ui::action_aim_and_shoot(), and calc_steadiness().
calculate_ranged_chances()
static std::vector<aim_type_prediction> calculate_ranged_chances (const target_ui & ui, const Character & you, target_ui::TargetMode mode, const input_context & ctxt, const item & weapon, const dispersion_sources & dispersion, const std::vector< confidence_rating > & confidence_ratings, const Target_attributes & target, const tripoint & pos) static
Definition at line 1692 of file ranged.cpp.
 {
     std::vector<aim_type> aim_types { get_default_aim_type() };
     std::vector<aim_type_prediction> aim_outputs;
     if( mode != target_ui::TargetMode::Throw && mode != target_ui::TargetMode::ThrowBlind ) {
         aim_types = you.get_aim_types( weapon );
     }
     // predict how long it'll take to reach from current recoil
     // to the ui's selected default aim mode threshold.
     const recoil_prediction aim_to_selected = predict_recoil( you, weapon, target,
             ui.get_sight_dispersion(), ui.get_selected_aim_type(), you.recoil );
     const double selected_steadiness = calc_steadiness( you, weapon, pos, aim_to_selected.recoil );
     const int throw_moves = throw_cost( you, weapon );
     for( const aim_type &aim_type : aim_types ) {
         const std::vector<input_event> keys = ctxt.keys_bound_to( aim_type.action.empty() ? "FIRE" :
                                               aim_type.action, /*maximum_modifier_count=*/1 );
         aim_type_prediction prediction = {};
         prediction.name = aim_type.has_threshold ? aim_type.name : _( "Current" );
         prediction.is_default = aim_type.action.empty(); // default mode defaults to FIRE hotkey
         prediction.hotkey = ( keys.empty() ? input_event() : keys.front() ).short_description();
         if( mode == target_ui::TargetMode::Throw || mode == target_ui::TargetMode::ThrowBlind ) {
             prediction.moves = throw_moves;
         } else {
             prediction.moves = predict_recoil( you, weapon, target, ui.get_sight_dispersion(), aim_type,
                                                you.recoil ).moves + time_to_attack( you, *weapon.type );
         }
         // if the default method is "behind" the selected; e.g. you are in immediate
         // firing mode with almost close no chances of hitting, but UI has selected
         // "precise" this will "catch up" the default method adding the required moves
         // and steadiness that it will gain if player presses fire, so pressing fire
         // hotkey in this case will actually use 'precise' aim mode.
         // in case where it already surpassed the UI selected mode this should be a
         // no-op.
         if( prediction.is_default ) {
             prediction.moves += aim_to_selected.moves;
             prediction.steadiness = selected_steadiness;
         } else {
             // predict how long it'll take to reach from current recoil
             // to the current aim mode's threshold.
             const recoil_prediction aim_to_type = ( aim_type == ui.get_selected_aim_type() ) ? aim_to_selected :
                                                   predict_recoil( you, weapon, target, ui.get_sight_dispersion(), aim_type, you.recoil );
             prediction.steadiness = calc_steadiness( you, weapon, pos, aim_to_type.recoil );
         }
         // make a copy of the given dispersion, apply the aiming and calculate hit confidence
         dispersion_sources current_dispersion = dispersion;
         current_dispersion.add_range( aim_type.has_threshold ? aim_type.threshold :
                                       aim_to_selected.recoil );
         // this loop fills in the "confidence" values; the chances of great/good/graze outcomes
         prediction.confidence = confidence_estimate( target, current_dispersion );
         for( const confidence_rating &rating : confidence_ratings ) {
             const int chance = std::min<int>( 100, 100 * rating.aim_level * prediction.confidence )
                                - prediction.chance_to_hit;
             prediction.ratings.push_back( rating );
             prediction.chances.push_back( {rating.label, rating.color, chance} );
             prediction.chance_to_hit += chance;
         }
         // Adds the "miss" outcome
         prediction.chances.push_back( { _( "Miss" ), "light_gray", 100 - prediction.chance_to_hit } );
         aim_outputs.push_back( prediction );
     }
     return aim_outputs;
 }
References _, aim_type::action, dispersion_sources::add_range(), calc_steadiness(), aim_type_prediction::chance_to_hit, aim_type_prediction::chances, aim_type_prediction::confidence, confidence_estimate(), Character::get_aim_types(), get_default_aim_type(), aim_type::has_threshold, aim_type_prediction::hotkey, aim_type_prediction::is_default, input_context::keys_bound_to(), aim_type_prediction::moves, recoil_prediction::moves, aim_type::name, aim_type_prediction::name, math_opers::pos(), predict_recoil(), aim_type_prediction::ratings, Character::recoil, recoil_prediction::recoil, aim_type_prediction::steadiness, aim_type::threshold, target_ui::Throw, throw_cost(), target_ui::ThrowBlind, time_to_attack(), and item::type.
Referenced by draw_throw_aim(), and print_aim().
character_throw_assist()
static std::optional<int> character_throw_assist (const Character & guy) static
Definition at line 1229 of file ranged.cpp.
 {
     std::optional<int> throw_assist = std::nullopt;
     if( guy.is_mounted() ) {
         auto *mons = guy.mounted_creature.get();
         if( mons->mech_str_addition() != 0 ) {
             throw_assist = mons->mech_str_addition();
             mons->use_mech_power( 3_kJ );
         }
     }
     return throw_assist;
 }
References Character::is_mounted(), and Character::mounted_creature.
Referenced by Character::throw_item(), and Character::thrown_item_adjusted_damage().
confidence_estimate()
static double confidence_estimate (const Target_attributes & attributes, const dispersion_sources & dispersion) static
Definition at line 1563 of file ranged.cpp.
 {
     // This is a rough estimate of accuracy based on a linear distribution across min and max
     // dispersion.  It is highly inaccurate probability-wise, but this is intentional, the player
     // is not doing Gaussian integration in their head while aiming.  The result gives the player
     // correct relative measures of chance to hit, and corresponds with the actual distribution at
     // min, max, and mean.
     if( attributes.range == 0 ) {
         return 2 * attributes.size;
     }
     double max_lateral_offset = iso_tangent( attributes.range, units::from_arcmin( dispersion.max() ) );
     return 1 / ( max_lateral_offset / attributes.size );
 }
References units::from_arcmin(), iso_tangent(), dispersion_sources::max(), Target_attributes::range, and Target_attributes::size.
Referenced by calculate_ranged_chances().
cycle_action()
static void cycle_action (item & weap, const itype_id & ammo, const tripoint & pos) static
Handle spent ammo casings and linkages.
Parameters
weap Weapon.
ammo Ammo used.
pos Character position.
Definition at line 2116 of file ranged.cpp.
 {
     map &here = get_map();
     // eject casings and linkages in random direction avoiding walls using player position as fallback
     std::vector<tripoint> tiles = closest_points_first( pos, 1 );
     tiles.erase( tiles.begin() );
     tiles.erase( std::remove_if( tiles.begin(), tiles.end(), [&]( const tripoint & e ) {
         return !here.passable( e );
     } ), tiles.end() );
     tripoint eject = tiles.empty() ? pos : random_entry( tiles );
     // for turrets try and drop casings or linkages directly to any CARGO part on the same tile
     const std::optional<vpart_reference> ovp_cargo = weap.has_flag( flag_VEHICLE )
             ? here.veh_at( pos ).cargo()
             : std::nullopt;
     item *brass_catcher = weap.gunmod_find_by_flag( flag_BRASS_CATCHER );
     if( !!ammo->ammo->casing ) {
         item casing = item( *ammo->ammo->casing );
         // blackpowder can gum up casings too
         if( ( *ammo->ammo ).ammo_effects.count( "BLACKPOWDER" ) ) {
             casing.set_flag( json_flag_FILTHY );
         }
         if( weap.has_flag( flag_RELOAD_EJECT ) ) {
             weap.force_insert_item( casing.set_flag( flag_CASING ),
                                     pocket_type::MAGAZINE );
             weap.on_contents_changed();
         } else {
             if( brass_catcher && brass_catcher->can_contain( casing ).success() ) {
                 brass_catcher->put_in( casing, pocket_type::CONTAINER );
             } else if( ovp_cargo ) {
                 ovp_cargo->vehicle().add_item( ovp_cargo->part(), casing );
             } else {
                 here.add_item_or_charges( eject, casing );
             }
             sfx::play_variant_sound( "fire_gun", "brass_eject", sfx::get_heard_volume( eject ),
                                      sfx::get_heard_angle( eject ) );
         }
     }
     // some magazines also eject disintegrating linkages
     const item *mag = weap.magazine_current();
     if( mag && mag->type->magazine->linkage ) {
         item linkage( *mag->type->magazine->linkage, calendar::turn, 1 );
         if( !( brass_catcher &&
                brass_catcher->put_in( linkage, pocket_type::CONTAINER ).success() ) ) {
             if( ovp_cargo ) {
                 ovp_cargo->items().insert( linkage );
             } else {
                 here.add_item_or_charges( eject, linkage );
             }
         }
     }
 }
References map::add_item_or_charges(), itype::ammo, item::can_contain(), optional_vpart_position::cargo(), closest_points_first(), CONTAINER, flag_BRASS_CATCHER, flag_CASING, flag_RELOAD_EJECT, flag_VEHICLE, item::force_insert_item(), sfx::get_heard_angle(), sfx::get_heard_volume(), get_map(), item::gunmod_find_by_flag(), item::has_flag(), json_flag_FILTHY, itype::magazine, MAGAZINE, item::magazine_current(), item::on_contents_changed(), sfx::play_variant_sound(), math_opers::pos(), item::put_in(), random_entry(), item::set_flag(), ret_val_common::success(), calendar::turn, item::type, and map::veh_at().
Referenced by Character::fire_gun().
dispersion_from_skill()
static double dispersion_from_skill (double skill, double weapon_dispersion) static
Definition at line 2267 of file ranged.cpp.
 {
     if( skill >= MAX_SKILL ) {
         return 0.0;
     }
     double skill_shortfall = static_cast<double>( MAX_SKILL ) - skill;
     double dispersion_penalty = 10 * skill_shortfall;
     double skill_threshold = 5;
     if( skill >= skill_threshold ) {
         double post_threshold_skill_shortfall = static_cast<double>( MAX_SKILL ) - skill;
         // Lack of mastery multiplies the dispersion of the weapon.
         return dispersion_penalty + ( weapon_dispersion * post_threshold_skill_shortfall * 1.25 ) /
                ( static_cast<double>( MAX_SKILL ) - skill_threshold );
     }
     // Unskilled shooters suffer greater penalties, still scaling with weapon penalties.
     double pre_threshold_skill_shortfall = skill_threshold - skill;
     dispersion_penalty += weapon_dispersion *
                           ( 1.25 + pre_threshold_skill_shortfall * 10.0 / skill_threshold );
     return dispersion_penalty;
 }
References MAX_SKILL.
Referenced by Character::get_weapon_dispersion().
do_aim()
static void do_aim (Character & you, const item & relevant, const double min_recoil) static
Definition at line 1516 of file ranged.cpp.
 {
     const double aim_amount = you.aim_per_move( relevant, you.recoil );
     if( aim_amount > 0 && you.recoil > min_recoil ) {
         // Increase aim at the cost of moves
         you.mod_moves( -1 );
         you.recoil = std::max( min_recoil, you.recoil - aim_amount );
         // Train archery proficiencies if we are doing archery
         if( relevant.gun_skill() == skill_archery ) {
             practice_archery_proficiency( you, relevant );
             // Only drain stamina on initial draw
             if( you.get_moves() == 1 ) {
                 mod_stamina_archery( you, relevant );
             }
         }
     } else {
         // If aim is already maxed, we're just waiting, so pass the turn.
         you.set_moves( 0 );
     }
 }
References Character::aim_per_move(), Creature::get_moves(), item::gun_skill(), max(), Creature::mod_moves(), mod_stamina_archery(), practice_archery_proficiency(), Character::recoil, Creature::set_moves(), and skill_archery.
Referenced by target_ui::action_aim(), and target_ui::action_aim_and_shoot().
draw_throw_aim()
static void draw_throw_aim (const target_ui & ui, const Character & you, const catacurses::window & w, int & text_y, input_context & ctxt, const item & weapon, const tripoint & target_pos, bool is_blind_throw) static
Definition at line 1967 of file ranged.cpp.
 {
     Creature *target = get_creature_tracker().creature_at( target_pos, true );
     if( target != nullptr && !you.sees( *target ) ) {
         target = nullptr;
     }
     const dispersion_sources dispersion( you.throwing_dispersion( weapon, target, is_blind_throw ) );
     const double range = rl_dist( you.pos(), target_pos );
     const double target_size = target != nullptr ? target->ranged_target_size() : 1.0f;
     static const std::vector<confidence_rating> confidence_config_critter = {{
             { accuracy_critical, '*', "green", translate_marker_context( "aim_confidence", "Great" ) },
             { accuracy_standard, '+', "light_gray", translate_marker_context( "aim_confidence", "Normal" ) },
             { accuracy_grazing, '|', "magenta", translate_marker_context( "aim_confidence", "Graze" ) }
         }
     };
     static const std::vector<confidence_rating> confidence_config_object = {{
             { accuracy_grazing, '*', "white", translate_marker_context( "aim_confidence", "Hit" ) }
         }
     };
     const auto &confidence_config = target != nullptr ?
                                     confidence_config_critter : confidence_config_object;
     const target_ui::TargetMode throwing_target_mode = is_blind_throw ?
             target_ui::TargetMode::ThrowBlind :
             target_ui::TargetMode::Throw;
     Target_attributes attributes( range, target_size, get_map().ambient_light_at( target_pos ),
                                   you.sees( target_pos ) );
     const std::vector<aim_type_prediction> aim_chances = calculate_ranged_chances( ui, you,
             throwing_target_mode, ctxt, weapon, dispersion, confidence_config, attributes, target_pos );
     text_y = print_ranged_chance( w, text_y, aim_chances );
 }
References accuracy_critical, accuracy_grazing, accuracy_standard, calculate_ranged_chances(), creature_tracker::creature_at(), get_creature_tracker(), get_map(), Creature::pos(), print_ranged_chance(), Creature::ranged_target_size(), rl_dist(), Character::sees(), target_ui::Throw, target_ui::ThrowBlind, Character::throwing_dispersion(), and translate_marker_context.
Referenced by target_ui::draw_ui_window().
get_colored_bar()
static std::string get_colored_bar (const double val, const int width, const std::string & label, RatingVector::iterator begin, RatingVector::iterator end) static
Definition at line 1586 of file ranged.cpp.
 {
     return get_labeled_bar<RatingVector::iterator>( val, width, label, begin, end,
     []( RatingVector::iterator it, int seg_width ) -> std::string {
         std::string result = string_format( "<color_%s>", std::get<2>( *it ) );
         result.insert( result.end(), seg_width, std::get<1>( *it ) );
         result += "</color>";
         return result;} );
 }
References keycode::end, and string_format().
Referenced by print_confidence_rating_bar().
get_default_aim_type()
static aim_type get_default_aim_type () static
Definition at line 1578 of file ranged.cpp.
 {
     // dummy aim type for unaimed shots
     return { _( "Immediate" ), "", "", false, static_cast<int>( MAX_RECOIL ) };
 }
References _, and MAX_RECOIL.
Referenced by calculate_ranged_chances(), Character::get_aim_types(), and target_ui::get_selected_aim_type().
gunmode_checks_common()
bool gunmode_checks_common (avatar & you, const map & m, std::vector< std::string > & messages, const gun_mode & gmode)
Common checks for gunmode (when firing a weapon / manually firing turret)
Parameters
messages Used to store messages describing failed checks
Returns
True if all conditions are true
Definition at line 3975 of file ranged.cpp.
 {
     bool result = true;
     if( you.has_trait( trait_BRAWLER ) ) {
         messages.push_back( string_format( _( "Pfft.  You are a brawler; using this %s is beneath you." ),
                                            gmode->tname() ) );
         result = false;
     }
     // Check that passed gun mode is valid and we are able to use it
     if( !( gmode && you.can_use( *gmode ) ) ) {
         messages.push_back( string_format( _( "You can't currently fire your %s." ),
                                            gmode->tname() ) );
         result = false;
     }
     const optional_vpart_position vp = m.veh_at( you.pos() );
     if( vp && vp->vehicle().player_in_control( you ) && ( gmode->is_two_handed( you ) ||
             gmode->has_flag( flag_FIRE_TWOHAND ) ) ) {
         messages.push_back( string_format( _( "You can't fire your %s while driving." ),
                                            gmode->tname() ) );
         result = false;
     }
     if( gmode->has_flag( flag_FIRE_TWOHAND ) && ( !you.has_two_arms_lifting() ||
             you.worn_with_flag( flag_RESTRICT_HANDS ) ) ) {
         messages.push_back( string_format( _( "You need two free hands to fire your %s." ),
                                            gmode->tname() ) );
         result = false;
     }
     return result;
 }
References _, Character::can_use(), flag_FIRE_TWOHAND, flag_RESTRICT_HANDS, item::has_flag(), Character::has_trait(), Character::has_two_arms_lifting(), item::is_two_handed(), Creature::pos(), string_format(), item::tname(), trait_BRAWLER, map::veh_at(), and Character::worn_with_flag().
Referenced by avatar_action::can_fire_weapon(), and target_ui::update_status().
gunmode_checks_weapon()
bool gunmode_checks_weapon (avatar & you, const map & m, std::vector< std::string > & messages, const gun_mode & gmode)
Various checks for gunmode when firing a weapon.
Parameters
messages Used to store messages describing failed checks
Returns
True if all conditions are true
Definition at line 4010 of file ranged.cpp.
 {
     bool result = true;
     if( !gmode->ammo_sufficient( &you ) &&
         !gmode->has_flag( flag_RELOAD_AND_SHOOT ) ) {
         if( !gmode->ammo_remaining() ) {
             messages.push_back( string_format( _( "Your %s is empty!" ), gmode->tname() ) );
         } else {
             messages.push_back( string_format( _( "Your %s needs %i charges to fire!" ),
                                                gmode->tname(), gmode->ammo_required() ) );
         }
         result = false;
     }
     if( gmode->get_gun_energy_drain() > 0_kJ ) {
         const units::energy energy_drain = gmode->get_gun_energy_drain();
         bool is_mech_weapon = false;
         if( you.is_mounted() ) {
             monster *mons = get_player_character().mounted_creature.get();
             if( !mons->type->mech_weapon.is_empty() ) {
                 is_mech_weapon = true;
             }
         }
         if( gmode->energy_remaining( &you ) < energy_drain ) {
             result = false;
             if( is_mech_weapon ) {
                 messages.push_back( string_format( _( "Your mech has an empty battery, its %s will not fire." ),
                                                    gmode->tname() ) );
             } else if( gmode->has_flag( flag_USES_BIONIC_POWER ) ) {
                 messages.push_back( string_format(
                                         _( "You need at least %2$d kJ of bionic power to fire the %1$s!" ),
                                         gmode->tname(), units::to_kilojoule( energy_drain ) ) );
             } else if( gmode->has_flag( flag_USE_UPS ) ) {
                 messages.push_back( string_format(
                                         _( "You need a UPS with at least %2$d kJ to fire the %1$s!" ),
                                         gmode->tname(), units::to_kilojoule( energy_drain ) ) );
             }
         }
     }
     if( gmode->has_flag( flag_MOUNTED_GUN ) ) {
         const bool v_mountable = static_cast<bool>( m.veh_at( you.pos() ).part_with_feature( "MOUNTABLE",
                                  true ) );
         bool t_mountable = m.has_flag_ter_or_furn( ter_furn_flag::TFLAG_MOUNTABLE, you.pos() );
         if( !t_mountable && !v_mountable ) {
             messages.push_back( string_format(
                                     _( "You must stand near acceptable terrain or furniture to fire the %s.  A table, a mound of dirt, a broken window, etc." ),
                                     gmode->tname() ) );
             result = false;
         }
     }
     return result;
 }
References _, item::ammo_remaining(), item::ammo_required(), item::ammo_sufficient(), item::energy_remaining(), flag_MOUNTED_GUN, flag_RELOAD_AND_SHOOT, flag_USE_UPS, flag_USES_BIONIC_POWER, item::get_gun_energy_drain(), get_player_character(), item::has_flag(), map::has_flag_ter_or_furn(), string_id< T >::is_empty(), Character::is_mounted(), mtype::mech_weapon, Character::mounted_creature, optional_vpart_position::part_with_feature(), Creature::pos(), string_format(), TFLAG_MOUNTABLE, item::tname(), units::to_kilojoule(), monster::type, and map::veh_at().
Referenced by avatar_action::can_fire_weapon(), and target_ui::update_status().
make_gun_projectile()
static projectile make_gun_projectile (const item & gun) static
Definition at line 2045 of file ranged.cpp.
 {
     projectile proj;
     proj.speed  = 1000;
     proj.impact = gun.gun_damage();
     proj.shot_impact = gun.gun_damage( true, true );
     proj.range = gun.gun_range();
     proj.proj_effects = gun.ammo_effects();
     auto &fx = proj.proj_effects;
     if( ( gun.ammo_data() && gun.ammo_data()->phase == phase_id::LIQUID ) ||
         fx.count( "SHOT" ) || fx.count( "BOUNCE" ) ) {
         fx.insert( "WIDE" );
     }
     if( gun.ammo_data() ) {
         // Some projectiles have a chance of being recoverable
         bool recover = std::any_of( fx.begin(), fx.end(), []( const std::string_view e ) {
             if( !string_starts_with( e, "RECOVER_" ) ) {
                 return false;
             }
             ret_val<int> n = try_parse_integer<int>( e.substr( 8 ), false );
             if( !n.success() ) {
                 debugmsg( "Error parsing ammo RECOVER_ denominator: %s", n.str() );
                 return false;
             }
             return !one_in( n.value() );
         } );
         if( recover && !fx.count( "IGNITE" ) && !fx.count( "EXPLOSIVE" ) ) {
             item drop( gun.ammo_current(), calendar::turn, 1 );
             drop.active = fx.count( "ACT_ON_RANGED_HIT" );
             drop.set_favorite( gun.get_contents().first_ammo().is_favorite );
             proj.set_drop( drop );
         }
         const auto &ammo = gun.ammo_data()->ammo;
         proj.critical_multiplier = ammo->critical_multiplier;
         proj.count = ammo->count;
         proj.multi_projectile_effects = ammo->multi_projectile_effects;
         if( fx.count( "MULTI_EFFECTS" ) ) {
             proj.multi_projectile_effects = true;
         }
         proj.shot_spread = ammo->shot_spread * gun.gun_shot_spread_multiplier();
         if( !ammo->drop.is_null() && x_in_y( ammo->drop_chance, 1.0 ) ) {
             item drop( ammo->drop );
             if( ammo->drop_active ) {
                 drop.activate();
             }
             proj.set_drop( drop );
         }
         if( fx.count( "CUSTOM_EXPLOSION" ) > 0 ) {
             proj.set_custom_explosion( gun.ammo_data()->explosion );
         }
     }
     return proj;
 }
References item::activate(), item::active, projectile::count, projectile::critical_multiplier, gun, projectile::impact, LIQUID, projectile::multi_projectile_effects, one_in(), projectile::proj_effects, projectile::range, projectile::set_custom_explosion(), projectile::set_drop(), item::set_favorite(), projectile::shot_impact, projectile::shot_spread, projectile::speed, try_parse_integer< int >(), calendar::turn, and x_in_y().
Referenced by Character::fire_gun().
make_gun_sound_effect()
void make_gun_sound_effect (const Character & p, bool burst, item * weapon) static
Definition at line 2172 of file ranged.cpp.
 {
     const item::sound_data data = weapon->gun_noise( burst );
     if( data.volume > 0 ) {
         sounds::sound( p.pos(), data.volume, sounds::sound_t::combat,
                        data.sound.empty() ? _( "Bang!" ) : data.sound );
     }
     tname::segment_bitset segs( tname::unprefixed_tname );
     segs.set( tname::segments::CONTENTS, false );
     p.add_msg_if_player( _( "You shoot your %1$s.  %2$s" ), weapon->tname( 1, segs ),
                          uppercase_first_letter( data.sound ) );
 }
References _, Character::add_msg_if_player(), sounds::combat, tname::CONTENTS, item::gun_noise(), Creature::pos(), enum_bitset< E >::set(), item::sound_data::sound, sounds::sound(), item::tname(), tname::unprefixed_tname(), uppercase_first_letter(), and item::sound_data::volume.
Referenced by Character::fire_gun().
mod_stamina_archery()
static void mod_stamina_archery (Character & you, const item & relevant) static
Definition at line 1497 of file ranged.cpp.
 {
     // Set activity level to 10 * str_ratio, with 10 being max (EXTRA_EXERCISE)
     // This ratio should never be below 0 and above 1
     const float str_ratio = static_cast<float>( relevant.get_min_str() ) / you.str_cur;
     you.set_activity_level( 10 * str_ratio );
     // Calculate stamina drain based on archery, athletics skill, and effective bow strength ratio
     const float archery_skill = you.get_skill_level( skill_archery );
     const float athletics_skill = you.get_skill_level( skill_swimming );
     const float skill_modifier = ( 2.0f * archery_skill + athletics_skill ) / 3.0f;
     const int stamina_cost = pow( 10.0f * str_ratio + 10 - skill_modifier, 2 );
     you.mod_stamina( -stamina_cost );
     add_msg_debug( debugmode::DF_RANGED,
                    "-%i stamina: %.1f str ratio, %.1f skill mod",
                    stamina_cost, str_ratio, skill_modifier );
 }
References add_msg_debug, debugmode::DF_RANGED, item::get_min_str(), Character::get_skill_level(), Character::mod_stamina(), Character::set_activity_level(), skill_archery, skill_swimming, and Character::str_cur.
Referenced by do_aim().
occupied_tile_fraction()
double occupied_tile_fraction (creature_size target_size)
Definition at line 526 of file ranged.cpp.
 {
     switch( target_size ) {
         case creature_size::tiny:
             return 0.1;
         case creature_size::small:
             return 0.25;
         case creature_size::medium:
             return 0.5;
         case creature_size::large:
             return 0.75;
         case creature_size::huge:
             return 1.0;
         case creature_size::num_sizes:
             debugmsg( "ERROR: Invalid Creature size class." );
             break;
     }
     return 0.5;
 }
References debugmsg, huge, large, medium, num_sizes, small, and tiny.
Referenced by map::drop_items(), and Creature::ranged_target_size().
pl_sees()
static bool pl_sees (const Creature & cr) static
Definition at line 1935 of file ranged.cpp.
 {
     Character &u = get_player_character();
     return u.sees( cr ) || u.sees_with_infrared( cr ) || u.sees_with_specials( cr );
 }
References get_player_character(), and u.
Referenced by target_ui::choose_initial_target(), sounds::process_sound_markers(), target_ui::set_cursor_pos(), and target_ui::try_reacquire_target().
practice_archery_proficiency()
void practice_archery_proficiency (Character & p, const item & relevant)
Definition at line 1455 of file ranged.cpp.
 {
     // Do nothing, we are not doing archery
     if( relevant.gun_skill() != skill_archery ) {
         return;
     }
     // We are already a master, practice has no effect
     if( p.has_proficiency( proficiency_prof_bow_master ) ) {
         return;
     }
     // Only train archery in multiples of 100 moves (or 1 turn) for performance, focus, and simplifying calculations
     p.archery_aim_counter++;
     if( p.archery_aim_counter > 100 ) {
         // Reset our counter
         p.archery_aim_counter = 0;
         // Intended to train prof_bow_basic from 0 to 100% in ~200 arrows in 5 hours from max aim, or 90s/arrow.
         // Additionally, a shortbow is used as the basis for number of moves per max aim shot at ~250 moves.
         // 90s/arrow / 2.5turns/arrow = 36s/turn. It is important to note, this is 200 arrows pre-focus.
         time_duration prof_exp = 36_seconds;
         // We don't know how to handle a bow yet
         if( !p.has_proficiency( proficiency_prof_bow_basic ) ) {
             p.practice_proficiency( proficiency_prof_bow_basic, prof_exp );
             return;
         }
         // We know how to handle a bow, but we are not an expert yet
         else if( !p.has_proficiency( proficiency_prof_bow_expert ) ) {
             p.practice_proficiency( proficiency_prof_bow_expert, prof_exp );
             return;
         }
         // We are an expert, lets practice to become a master
         else {
             p.practice_proficiency( proficiency_prof_bow_master, prof_exp );
             return;
         }
     }
 }
References Creature::archery_aim_counter, item::gun_skill(), Character::has_proficiency(), Character::practice_proficiency(), proficiency_prof_bow_basic, proficiency_prof_bow_expert, proficiency_prof_bow_master, and skill_archery.
Referenced by do_aim().
predict_recoil()
static recoil_prediction predict_recoil (const Character & you, const item & weapon, const Target_attributes & target, int sight_dispersion, const aim_type & aim_mode, double start_recoil) static
Definition at line 1659 of file ranged.cpp.
 {
     if( !aim_mode.has_threshold || aim_mode.threshold > start_recoil ) {
         return { start_recoil, 0 };
     }
     double predicted_recoil = start_recoil;
     int predicted_delay = 0;
     const aim_mods_cache &aim_cache = you.gen_aim_mods_cache( weapon );
     auto aim_cache_opt = std::make_optional( std::ref( aim_cache ) );
     // next loop simulates aiming until either aim mode threshold or sight_dispersion is reached
     do {
         const double aim_amount = you.aim_per_move( weapon, predicted_recoil, target, aim_cache_opt );
         if( aim_amount <= MIN_RECOIL_IMPROVEMENT ) {
             break;
         }
         predicted_delay++;
         predicted_recoil = std::max( predicted_recoil - aim_amount, 0.0 );
     } while( predicted_recoil > aim_mode.threshold && predicted_recoil > sight_dispersion );
     return { predicted_recoil, predicted_delay };
 }
References Character::aim_per_move(), Character::gen_aim_mods_cache(), aim_type::has_threshold, max(), MIN_RECOIL_IMPROVEMENT, and aim_type::threshold.
Referenced by calculate_ranged_chances().
print_aim()
static int print_aim (const target_ui & ui, Character & you, const catacurses::window & w, int line_number, input_context & ctxt, const item & weapon, const tripoint & pos) static
Definition at line 1941 of file ranged.cpp.
 {
     // This is absolute accuracy for the player.
     // TODO: push the calculations duplicated from Creature::deal_projectile_attack() and
     // Creature::projectile_attack() into shared methods.
     // Dodge doesn't affect gun attacks
     dispersion_sources dispersion = you.get_weapon_dispersion( weapon );
     dispersion.add_range( you.recoil_vehicle() );
     // This could be extracted, to allow more/less verbose displays
     static const std::vector<confidence_rating> confidence_config = {{
             { accuracy_critical, '*', "green", translate_marker_context( "aim_confidence", "Great" ) },
             { accuracy_standard, '+', "light_gray", translate_marker_context( "aim_confidence", "Normal" ) },
             { accuracy_grazing, '|', "magenta", translate_marker_context( "aim_confidence", "Graze" ) }
         }
     };
     const std::vector<aim_type_prediction> aim_chances = calculate_ranged_chances( ui, you,
             target_ui::TargetMode::Fire, ctxt, weapon, dispersion, confidence_config,
             Target_attributes( you.pos(), pos ), pos );
     return print_ranged_chance( w, line_number, aim_chances );
 }
References accuracy_critical, accuracy_grazing, accuracy_standard, dispersion_sources::add_range(), calculate_ranged_chances(), target_ui::Fire, Character::get_weapon_dispersion(), Creature::pos(), math_opers::pos(), print_ranged_chance(), Character::recoil_vehicle(), and translate_marker_context.
Referenced by target_ui::draw_ui_window().
print_confidence_rating_bar()
static void print_confidence_rating_bar (const catacurses::window & w, aim_type_prediction prediction, int & line_number, int width, nc_color col) static
Definition at line 1789 of file ranged.cpp.
 {
     RatingVector confidence_ratings;
     std::transform( prediction.ratings.begin(), prediction.ratings.end(),
                     std::back_inserter( confidence_ratings ),
     [&]( const confidence_rating & config ) {
         return std::make_tuple( config.aim_level, config.symbol, config.color );
     } );
     const std::string &confidence_bar = get_colored_bar( prediction.confidence, width, "",
                                         confidence_ratings.begin(), confidence_ratings.end() );
     print_colored_text( w, point( 1, line_number++ ), col, col, confidence_bar );
 }
References aim_type_prediction::confidence, get_colored_bar(), print_colored_text(), and aim_type_prediction::ratings.
Referenced by print_ranged_chance().
print_confidence_ratings()
static void print_confidence_ratings (const catacurses::window & w, const std::vector< confidence_rating > & ratings, int & line_number, int width, int & column_number, nc_color col) static
Definition at line 1771 of file ranged.cpp.
 {
     for( const confidence_rating &cr : ratings ) {
         std::string label = pgettext( "aim_confidence", cr.label.c_str() );
         std::string symbols = string_format( "<color_%s>%s</color> = %s", cr.color, cr.symbol, label );
         int line_len = utf8_width( label ) + 5; // 5 for '# = ' and whitespace at end
         if( ( width - column_number ) < line_len ) {
             column_number = 1;
             line_number++;
         }
         print_colored_text( w, point( column_number, line_number ), col, col, symbols );
         column_number += line_len;
     }
     line_number++;
 }
References pgettext, print_colored_text(), string_format(), anonymous_namespace{rotatable_symbols.cpp}::symbols, and utf8_width().
Referenced by print_ranged_chance().
print_ranged_chance()
static int print_ranged_chance (const catacurses::window & w, int line_number, const std::vector< aim_type_prediction > & aim_chances) static
Definition at line 1805 of file ranged.cpp.
 {
     std::vector<aim_type_prediction> sorted = aim_chances;
     // Sort aim types so that 'current' mode is placed at the current probability it provides
     // TODO: consider removing it, but for now it demonstrates the odds changing pretty well
     std::sort( sorted.begin(), sorted.end(),
     []( const auto & lhs, const auto & rhs ) {
         return lhs.confidence <= rhs.confidence;
     } );
     int width = getmaxx( w ) - 2; // window width minus borders
     const int bars_pad = 3;
     bool display_numbers = get_option<std::string>( "ACCURACY_DISPLAY" ) == "numbers";
     std::string panel_type = panel_manager::get_manager().get_current_layout_id();
     nc_color col = c_light_gray;
     // Start printing by panel type, inside each branch whether to output numbers or "bars"
     if( panel_type == "legacy_labels_narrow_sidebar" || panel_type == "legacy_compact_sidebar" ) {
         bool narrow = panel_type == "legacy_labels_narrow_sidebar";
         // TODO: who uses this? this is broken likely since work started
         // on sidebar widgets and yet nobody complains...
         std::vector<std::string> t_aims( 4 );
         std::vector<std::string> t_confidence( 20 );
         int aim_iter = 0;
         int conf_iter = 0;
         if( !display_numbers ) {
             int column_number = 1;
             print_confidence_ratings( w, aim_chances.front().ratings, line_number, width, column_number, col );
             width -= bars_pad;
         } else {
             std::string symbols = _( " <color_green>Great</color> <color_light_gray>Normal</color>"
                                      " <color_magenta>Graze</color> <color_dark_gray>Miss</color> <color_light_blue>Moves</color>" );
             fold_and_print( w, point( 1, line_number++ ), width + bars_pad, c_dark_gray, symbols );
             int len = utf8_width( symbols ) - 121; // to subtract color codes
             if( len > width + bars_pad ) {
                 line_number++;
             }
             for( int i = 0; i < width; i++ ) {
                 mvwprintw( w, point( i + 1, line_number ), "-" );
             }
         }
         for( const aim_type_prediction &out : sorted ) {
             if( display_numbers ) {
                 t_aims[aim_iter] = string_format( "<color_dark_gray>%s:</color>", out.name );
                 t_confidence[( aim_iter * 5 ) + 4] = string_format( "<color_light_blue>%d</color>", out.moves );
             } else {
                 print_colored_text( w, point( 1, line_number ), col, col, string_format( _( "%s %s:" ), out.name,
                                     _( "Aim" ) ) );
                 right_print( w, line_number++, 1, c_light_blue, _( "Moves" ) );
                 right_print( w, line_number, 1, c_light_blue, string_format( "%d", out.moves ) );
             }
             if( display_numbers ) {
                 int last_chance = 0;
                 conf_iter = 0;
                 for( const confidence_rating &cr : narrow ? aim_chances.front().ratings : out.ratings ) {
                     int chance = std::min<int>( 100, 100.0 * ( cr.aim_level ) * out.confidence ) - last_chance;
                     last_chance += chance;
                     t_confidence[conf_iter + ( aim_iter * 5 )] = string_format( "<color_%s>%3d%%</color>", cr.color,
                             chance );
                     conf_iter++;
                     if( conf_iter == 3 ) {
                         t_confidence[conf_iter + ( aim_iter * 5 )] = string_format( "<color_%s>%3d%%</color>", "dark_gray",
                                 100 - last_chance );
                     }
                 }
                 aim_iter++;
             } else {
                 print_confidence_rating_bar( w, out, line_number, width, col );
             }
         }
         // Draw tables for compact Numbers display
         if( display_numbers ) {
             const std::string divider = "|";
             int left_pad = 8;
             int columns = 5;
             insert_table( w, left_pad, ++line_number, columns, c_light_gray, divider, true, t_confidence );
             insert_table( w, 0, line_number, 1, c_light_gray, "", false, t_aims );
             line_number = line_number + 4; // 4 to account for the tables
         }
         return line_number;
     } else { // print the "legacy classic" one
         // there's more legacy sidebars but appear to not be used
         const auto &current_steadiness_it = std::find_if( sorted.begin(),
         sorted.end(), []( const aim_type_prediction & atp ) {
             return atp.is_default;
         } );
         if( current_steadiness_it != sorted.end() ) {
             line_number = print_steadiness( w, line_number, current_steadiness_it->steadiness );
         }
         int column_number = 1;
         if( !( panel_type == "compact" || panel_type == "labels-narrow" ) ) {
             std::string label = _( "Symbols:" );
             mvwprintw( w, point( column_number, line_number ), label );
             column_number += utf8_width( label ) + 1; // 1 for whitespace after 'Symbols:'
         }
         print_confidence_ratings( w, sorted.front().ratings, line_number, width, column_number, col );
         for( const aim_type_prediction &out : sorted ) {
             std::string col_hl = out.is_default ? "light_green" : "light_gray";
             std::string desc =
                 string_format( "<color_white>[%s]</color> <color_%s>%s %s</color> | %s: <color_light_blue>%3d</color>",
                                out.hotkey, col_hl, out.name, _( "Aim" ), _( "Moves to fire" ), out.moves );
             print_colored_text( w, point( 1, line_number++ ), col, col, desc );
             if( display_numbers ) {
                 const std::string line = enumerate_as_string( out.chances.cbegin(), out.chances.cend(),
                 []( const aim_type_prediction::aim_confidence & conf ) {
                     const std::string label_loc = pgettext( "aim_confidence", conf.label.c_str() );
                     return string_format( "%s: <color_%s>%3d%%</color>", label_loc, conf.color, conf.chance );
                 }, enumeration_conjunction::none );
                 line_number += fold_and_print_from( w, point( 1, line_number ), width, 0, c_dark_gray, line );
             } else {
                 print_confidence_rating_bar( w, out, line_number, width, col );
             }
         }
         return line_number;
     }
 }
References _, c_dark_gray, c_light_blue, c_light_gray, enumerate_as_string(), fold_and_print(), fold_and_print_from(), panel_manager::get_current_layout_id(), panel_manager::get_manager(), catacurses::getmaxx(), insert_table(), line(), catacurses::mvwprintw(), none, print_colored_text(), print_confidence_rating_bar(), print_confidence_ratings(), print_steadiness(), right_print(), sorted, string_format(), anonymous_namespace{rotatable_symbols.cpp}::symbols, and utf8_width().
Referenced by draw_throw_aim(), and print_aim().
print_steadiness()
static int print_steadiness (const catacurses::window & w, int line_number, double steadiness) static
Definition at line 1546 of file ranged.cpp.
 {
     const int window_width = getmaxx( w ) - 2; // Window width minus borders.
     if( get_option<std::string>( "ACCURACY_DISPLAY" ) == "numbers" ) {
         std::string steadiness_s = string_format( "%s: %d%%", _( "Steadiness" ),
                                    static_cast<int>( 100.0 * steadiness ) );
         mvwprintw( w, point( 1, line_number++ ), steadiness_s );
     } else {
         const std::string &steadiness_bar = get_labeled_bar( steadiness, window_width,
                                             _( "Steadiness" ), '*' );
         mvwprintw( w, point( 1, line_number++ ), steadiness_bar );
     }
     return line_number;
 }
References _, get_labeled_bar(), catacurses::getmaxx(), catacurses::mvwprintw(), and string_format().
Referenced by print_ranged_chance().
range_with_even_chance_of_good_hit()
int range_with_even_chance_of_good_hit (int dispersion)
Definition at line 577 of file ranged.cpp.
 {
     int even_chance_range = 0;
     while( static_cast<unsigned>( even_chance_range ) <
            Creature::dispersion_for_even_chance_of_good_hit.size() &&
            dispersion < Creature::dispersion_for_even_chance_of_good_hit[ even_chance_range ] ) {
         even_chance_range++;
     }
     return even_chance_range;
 }
References Creature::dispersion_for_even_chance_of_good_hit, and om_direction::size.
Referenced by npc::confident_gun_mode_range(), and item::gun_info().
target_size_in_moa()
static double target_size_in_moa (int range, double size) static
Definition at line 1597 of file ranged.cpp.
 {
     return atan2( size, range ) * 60 * 180 / M_PI;
 }
References atan2(), M_PI, and om_direction::size.
Referenced by Target_attributes::Target_attributes().
throw_cost()
int throw_cost (const Character & c, const item & to_throw)
Throw increases throwing speed Dexterity increases throwing speed
Definition at line 1110 of file ranged.cpp.
 {
     // Very similar to player::attack_speed
     // TODO: Extract into a function?
     // Differences:
     // Dex is more (2x) important for throwing speed
     // At 10 skill, the cost is down to 0.75%, not 0.66%
     const int base_move_cost = to_throw.attack_time( c ) / 2;
     const float throw_skill = std::min( static_cast<float>( MAX_SKILL ),
                                         c.get_skill_level( skill_throw ) );
     ///\EFFECT_THROW increases throwing speed
     const int skill_cost = static_cast<int>( ( base_move_cost * ( 20 - throw_skill ) / 20 ) );
     ///\EFFECT_DEX increases throwing speed
     const int dexbonus = c.get_dex();
     const float stamina_ratio = static_cast<float>( c.get_stamina() ) / c.get_stamina_max();
     const float stamina_penalty = 1.0 + std::max( ( 0.25f - stamina_ratio ) * 4.0f, 0.0f );
     int move_cost = base_move_cost;
     move_cost *= c.get_modifier( character_modifier_melee_thrown_move_lift_mod );
     move_cost *= c.get_modifier( character_modifier_melee_thrown_move_balance_mod );
     // Stamina penalty only affects base/2 and encumbrance parts of the cost
     move_cost *= stamina_penalty;
     move_cost += skill_cost;
     move_cost -= dexbonus;
     move_cost = c.enchantment_cache->modify_value( enchant_vals::mod::ATTACK_SPEED, move_cost );
     return std::max( 25, move_cost );
 }
References enchant_vals::ATTACK_SPEED, item::attack_time(), c, character_modifier_melee_thrown_move_balance_mod, character_modifier_melee_thrown_move_lift_mod, max(), MAX_SKILL, min(), and skill_throw.
Referenced by calculate_ranged_chances(), npc_attack_throw::evaluate_tripoint(), and Character::throw_item().
throwing_skill_adjusted()
static float throwing_skill_adjusted (const Character & guy) static
Definition at line 1242 of file ranged.cpp.
 {
     float skill_level = std::min( static_cast<float>( MAX_SKILL ), guy.get_skill_level( skill_throw ) );
     // if you are lying on the floor, you can't really throw that well
     if( guy.has_effect( effect_downed ) ) {
         skill_level = std::max( 0.0f, skill_level - 5 );
     }
     return skill_level;
 }
References effect_downed, Character::get_skill_level(), Creature::has_effect(), max(), MAX_SKILL, min(), and skill_throw.
Referenced by Character::throw_item(), Character::thrown_item_projectile(), and Character::thrown_item_total_damage_raw().
time_to_attack()
int time_to_attack (const Character & p, const itype & firing) static
Definition at line 2107 of file ranged.cpp.
 {
     const skill_id &skill_used = firing.gun->skill_used;
     const time_info_t &info = skill_used->time_to_attack();
     return std::max( info.min_time,
                      static_cast<int>( round( info.base_time - info.time_reduction_per_level * p.get_skill_level(
                                            skill_used ) ) ) );
 }
References time_info_t::base_time, Character::get_skill_level(), itype::gun, max(), time_info_t::min_time, round(), time_info_t::time_reduction_per_level, and Skill::time_to_attack().
Referenced by calculate_ranged_chances(), Character::fire_gun(), and Character::gun_value().
Variable Documentation
AIF_DURATION_LIMIT
constexpr int AIF_DURATION_LIMIT = 10 static constexpr
Definition at line 155 of file ranged.cpp.
Referenced by target_ui::run().
ammo_120mm
const ammotype ammo_120mm("120mm") ("120mm") static
Referenced by Character::fire_gun(), and item::gun_noise().
ammo_12mm
const ammotype ammo_12mm("12mm") ("12mm") static
Referenced by item::gun_noise().
ammo_40x46mm
const ammotype ammo_40x46mm("40x46mm") ("40x46mm") static
Referenced by item::gun_noise().
ammo_40x53mm
const ammotype ammo_40x53mm("40x53mm") ("40x53mm") static
Referenced by item::gun_noise().
ammo_66mm
const ammotype ammo_66mm("66mm") ("66mm") static
Referenced by Character::fire_gun(), and item::gun_noise().
ammo_84x246mm
const ammotype ammo_84x246mm("84x246mm") ("84x246mm") static
Referenced by Character::fire_gun(), and item::gun_noise().
ammo_arrow
const ammotype ammo_arrow("arrow") ("arrow") static
Referenced by item::gun_noise().
ammo_atgm
const ammotype ammo_atgm("atgm") ("atgm") static
Referenced by Character::fire_gun(), and item::gun_noise().
ammo_atlatl
const ammotype ammo_atlatl("atlatl") ("atlatl") static
Referenced by item::gun_noise().
ammo_bolt
const ammotype ammo_bolt("bolt") ("bolt") static
Referenced by item::gun_noise().
ammo_bolt_ballista
const ammotype ammo_bolt_ballista("bolt_ballista") ("bolt_ballista") static
Referenced by item::gun_noise().
ammo_flammable
const ammotype ammo_flammable("flammable") ("flammable") static
Referenced by Character::fire_gun(), and item::gun_noise().
ammo_homebrew_rocket
const ammotype ammo_homebrew_rocket("homebrew_rocket") ("homebrew_rocket") static
Referenced by Character::fire_gun(), and item::gun_noise().
ammo_m235
const ammotype ammo_m235("m235") ("m235") static
Referenced by Character::fire_gun(), and item::gun_noise().
ammo_metal_rail
const ammotype ammo_metal_rail("metal_rail") ("metal_rail") static
Referenced by item::gun_noise().
ammo_RPG_7
const ammotype ammo_RPG_7("RPG-7") ("RPG-7") static
Referenced by Character::fire_gun(), and item::gun_noise().
ammo_strange_arrow
const ammotype ammo_strange_arrow("strange_arrow") ("strange_arrow") static
Referenced by item::gun_noise().
bio_railgun
const bionic_id bio_railgun("bio_railgun") ("bio_railgun") static
Referenced by Character::throw_item(), and Character::thrown_item_adjusted_damage().
character_modifier_melee_thrown_move_balance_mod
const character_modifier_id character_modifier_melee_thrown_move_balance_mod("melee_thrown_move_balance_mod") ("melee_thrown_move_balance_mod") static
Referenced by throw_cost().
character_modifier_melee_thrown_move_lift_mod
const character_modifier_id character_modifier_melee_thrown_move_lift_mod("melee_thrown_move_lift_mod") ("melee_thrown_move_lift_mod") static
Referenced by throw_cost().
character_modifier_ranged_dispersion_manip_mod
const character_modifier_id character_modifier_ranged_dispersion_manip_mod("ranged_dispersion_manip_mod") ("ranged_dispersion_manip_mod") static
Referenced by Character::get_weapon_dispersion().
character_modifier_thrown_dex_mod
const character_modifier_id character_modifier_thrown_dex_mod("thrown_dex_mod") ("thrown_dex_mod") static
Referenced by Character::throw_dispersion_per_dodge().
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by Character::throw_item(), and Character::thrown_item_total_damage_raw().
damage_cut
const damage_type_id damage_cut("cut") ("cut") static
Referenced by Character::throw_item(), and Character::thrown_item_total_damage_raw().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by throwing_skill_adjusted().
effect_hit_by_player
const efftype_id effect_hit_by_player("hit_by_player") ("hit_by_player") static
Referenced by target_ui::on_target_accepted().
effect_on_roof
const efftype_id effect_on_roof("on_roof") ("on_roof") static
Referenced by Character::fire_gun().
effect_quadruped_full
const efftype_id effect_quadruped_full("quadruped_full") ("quadruped_full") static
Referenced by Creature::ranged_target_size().
fault_gun_blackpowder
const fault_id fault_gun_blackpowder("fault_gun_blackpowder") ("fault_gun_blackpowder") static
Referenced by Character::handle_gun_damage().
fault_gun_chamber_spent
const fault_id fault_gun_chamber_spent("fault_gun_chamber_spent") ("fault_gun_chamber_spent") static
Referenced by Character::fire_gun(), and Character::handle_gun_damage().
fault_gun_dirt
const fault_id fault_gun_dirt("fault_gun_dirt") ("fault_gun_dirt") static
Referenced by Character::handle_gun_damage().
fault_overheat_explosion
const fault_id fault_overheat_explosion("fault_overheat_explosion") ("fault_overheat_explosion") static
Referenced by Character::handle_gun_overheat().
fault_overheat_melting
const fault_id fault_overheat_melting("fault_overheat_melting") ("fault_overheat_melting") static
Referenced by Character::handle_gun_overheat().
fault_overheat_safety
const fault_id fault_overheat_safety("fault_overheat_safety") ("fault_overheat_safety") static
Referenced by Character::handle_gun_overheat().
fault_overheat_venting
const fault_id fault_overheat_venting("fault_overheat_venting") ("fault_overheat_venting") static
Referenced by Character::handle_gun_overheat().
ferric
const std::set<material_id> ferric = { material_iron, material_steel, material_budget_steel, material_case_hardened_steel, material_high_steel, material_low_steel, material_med_steel, material_tempered_steel } static
Definition at line 152 of file ranged.cpp.
Referenced by Character::throw_item(), and Character::thrown_item_adjusted_damage().
json_flag_FILTHY
const flag_id json_flag_FILTHY("FILTHY") ("FILTHY") static
Referenced by cycle_action().
material_budget_steel
const material_id material_budget_steel("budget_steel") ("budget_steel") static
material_case_hardened_steel
const material_id material_case_hardened_steel("case_hardened_steel") ("case_hardened_steel") static
material_glass
const material_id material_glass("glass") ("glass") static
Referenced by Character::throw_item(), and Character::thrown_item_total_damage_raw().
material_high_steel
const material_id material_high_steel("high_steel") ("high_steel") static
material_iron
const material_id material_iron("iron") ("iron") static
material_low_steel
const material_id material_low_steel("low_steel") ("low_steel") static
material_med_steel
const material_id material_med_steel("med_steel") ("med_steel") static
material_steel
const material_id material_steel("steel") ("steel") static
material_tempered_steel
const material_id material_tempered_steel("tempered_steel") ("tempered_steel") static
proficiency_prof_bow_basic
const proficiency_id proficiency_prof_bow_basic("prof_bow_basic") ("prof_bow_basic") static
Referenced by practice_archery_proficiency().
proficiency_prof_bow_expert
const proficiency_id proficiency_prof_bow_expert("prof_bow_expert") ("prof_bow_expert") static
Referenced by practice_archery_proficiency().
proficiency_prof_bow_master
const proficiency_id proficiency_prof_bow_master("prof_bow_master") ("prof_bow_master") static
Referenced by practice_archery_proficiency().
skill_archery
const skill_id skill_archery("archery") ("archery") static
Referenced by do_aim(), Character::get_weapon_dispersion(), mod_stamina_archery(), and practice_archery_proficiency().
skill_dodge
const skill_id skill_dodge("dodge") ("dodge") static
Referenced by Character::gun_value().
skill_driving
const skill_id skill_driving("driving") ("driving") static
Referenced by Character::get_weapon_dispersion().
skill_gun
const skill_id skill_gun("gun") ("gun") static
Referenced by Character::fire_gun(), Character::get_weapon_dispersion(), and target_ui::recalc_aim_turning_penalty().
skill_launcher
const skill_id skill_launcher("launcher") ("launcher") static
Referenced by Character::fire_gun().
skill_swimming
const skill_id skill_swimming("swimming") ("swimming") static
Referenced by mod_stamina_archery().
skill_throw
const skill_id skill_throw("throw") ("throw") static
Referenced by throw_cost(), Character::throw_item(), Character::throwing_dispersion(), throwing_skill_adjusted(), and Character::thrown_item_adjusted_damage().
tr_practice_target
const trap_str_id tr_practice_target("tr_practice_target") ("tr_practice_target") static
trait_BRAWLER
const trait_id trait_BRAWLER("BRAWLER") ("BRAWLER") static
Referenced by gunmode_checks_common().
trait_PYROMANIA
const trait_id trait_PYROMANIA("PYROMANIA") ("PYROMANIA") static
Referenced by Character::fire_gun().