Cataclysm DDA: src/ranged.h File Reference
ranged.h File Reference
#include <iosfwd>
#include <vector>
#include "creature.h"
#include "point.h"
Classes
struct Target_attributes
Namespaces
target_handler
Macros
#define CATA_SRC_RANGED_H
Typedefs
using target_handler::trajectory = std::vector< tripoint >
Functions
trajectory target_handler::mode_select_only (avatar &you, int range)
Generic target select without fire something.
trajectory target_handler::mode_fire (avatar &you, aim_activity_actor &activity)
Firing ranged weapon.
trajectory target_handler::mode_throw (avatar &you, item &relevant, bool blind_throwing)
Throwing item.
trajectory target_handler::mode_reach (avatar &you, item_location weapon)
Reach attacking.
trajectory target_handler::mode_turret_manual (avatar &you, turret_data &turret)
Manually firing vehicle turret.
trajectory target_handler::mode_turrets (avatar &you, vehicle &veh, const std::vector< vehicle_part * > &turrets)
Selecting target for turrets (when using vehicle controls)
trajectory target_handler::mode_spell (avatar &you, spell &casting, bool no_fail, bool no_mana)
Casting a spell.
void practice_archery_proficiency (Character &p, const item &relevant)
int range_with_even_chance_of_good_hit (int dispersion)
bool gunmode_checks_common (avatar &you, const map &m, std::vector< std::string > &messages, const gun_mode &gmode)
Common checks for gunmode (when firing a weapon / manually firing turret)
bool gunmode_checks_weapon (avatar &you, const map &m, std::vector< std::string > &messages, const gun_mode &gmode)
Various checks for gunmode when firing a weapon.
int throw_cost (const Character &c, const item &to_throw)
double calc_steadiness (const Character &you, const item &weapon, const tripoint &pos, double predicted_recoil)
double calculate_aim_cap (const Character &you, const tripoint &target)
double occupied_tile_fraction (creature_size target_size)
Variables
constexpr double MIN_RECOIL_IMPROVEMENT = 0.01
Macro Definition Documentation
CATA_SRC_RANGED_H
#define CATA_SRC_RANGED_H
Definition at line 3 of file ranged.h.
Function Documentation
calc_steadiness()
double calc_steadiness (const Character & you, const item & weapon, const tripoint & pos, double predicted_recoil)
Definition at line 1156 of file ranged.cpp.
 {
     const double min_recoil = calculate_aim_cap( you, pos );
     const double effective_recoil = you.most_accurate_aiming_method_limit( weapon );
     const double min_dispersion = std::max( min_recoil, effective_recoil );
     const double steadiness_range = MAX_RECOIL - min_dispersion;
     // This is a relative measure of how steady the player's aim is,
     // 0 is the best the player can do.
     const double steady_score = std::max( 0.0, predicted_recoil - min_dispersion );
     // Fairly arbitrary cap on steadiness...
     return 1.0 - ( steady_score / steadiness_range );
 }
References calculate_aim_cap(), max(), MAX_RECOIL, Character::most_accurate_aiming_method_limit(), and math_opers::pos().
Referenced by calculate_ranged_chances(), and avatar::rebuild_aim_cache().
calculate_aim_cap()
double calculate_aim_cap (const Character & you, const tripoint & target)
Definition at line 1140 of file ranged.cpp.
 {
     double min_recoil = 0.0;
     const Creature *victim = get_creature_tracker().creature_at( target, true );
     // No p.sees_with_specials() here because special senses are not precise enough
     // to give creature's exact size & position, only which tile it occupies
     if( victim == nullptr || ( !you.sees( *victim ) && !you.sees_with_infrared( *victim ) ) ) {
         const int range = rl_dist( you.pos(), target );
         // Get angle of triangle that spans the target square.
         const double angle = 2 * atan2( 0.5, range );
         // Convert from radians to arcmin.
         min_recoil = 60 * 180 * angle / M_PI;
     }
     return min_recoil;
 }
References atan2(), creature_tracker::creature_at(), get_creature_tracker(), M_PI, Creature::pos(), rl_dist(), Character::sees(), and Character::sees_with_infrared().
Referenced by target_ui::action_aim(), target_ui::action_aim_and_shoot(), and calc_steadiness().
gunmode_checks_common()
bool gunmode_checks_common (avatar & you, const map & m, std::vector< std::string > & messages, const gun_mode & gmode)
Common checks for gunmode (when firing a weapon / manually firing turret)
Parameters
messages Used to store messages describing failed checks
Returns
True if all conditions are true
Definition at line 3975 of file ranged.cpp.
 {
     bool result = true;
     if( you.has_trait( trait_BRAWLER ) ) {
         messages.push_back( string_format( _( "Pfft.  You are a brawler; using this %s is beneath you." ),
                                            gmode->tname() ) );
         result = false;
     }
     // Check that passed gun mode is valid and we are able to use it
     if( !( gmode && you.can_use( *gmode ) ) ) {
         messages.push_back( string_format( _( "You can't currently fire your %s." ),
                                            gmode->tname() ) );
         result = false;
     }
     const optional_vpart_position vp = m.veh_at( you.pos() );
     if( vp && vp->vehicle().player_in_control( you ) && ( gmode->is_two_handed( you ) ||
             gmode->has_flag( flag_FIRE_TWOHAND ) ) ) {
         messages.push_back( string_format( _( "You can't fire your %s while driving." ),
                                            gmode->tname() ) );
         result = false;
     }
     if( gmode->has_flag( flag_FIRE_TWOHAND ) && ( !you.has_two_arms_lifting() ||
             you.worn_with_flag( flag_RESTRICT_HANDS ) ) ) {
         messages.push_back( string_format( _( "You need two free hands to fire your %s." ),
                                            gmode->tname() ) );
         result = false;
     }
     return result;
 }
References _, Character::can_use(), flag_FIRE_TWOHAND, flag_RESTRICT_HANDS, item::has_flag(), Character::has_trait(), Character::has_two_arms_lifting(), item::is_two_handed(), Creature::pos(), string_format(), item::tname(), trait_BRAWLER, map::veh_at(), and Character::worn_with_flag().
Referenced by avatar_action::can_fire_weapon(), and target_ui::update_status().
gunmode_checks_weapon()
bool gunmode_checks_weapon (avatar & you, const map & m, std::vector< std::string > & messages, const gun_mode & gmode)
Various checks for gunmode when firing a weapon.
Parameters
messages Used to store messages describing failed checks
Returns
True if all conditions are true
Definition at line 4010 of file ranged.cpp.
 {
     bool result = true;
     if( !gmode->ammo_sufficient( &you ) &&
         !gmode->has_flag( flag_RELOAD_AND_SHOOT ) ) {
         if( !gmode->ammo_remaining() ) {
             messages.push_back( string_format( _( "Your %s is empty!" ), gmode->tname() ) );
         } else {
             messages.push_back( string_format( _( "Your %s needs %i charges to fire!" ),
                                                gmode->tname(), gmode->ammo_required() ) );
         }
         result = false;
     }
     if( gmode->get_gun_energy_drain() > 0_kJ ) {
         const units::energy energy_drain = gmode->get_gun_energy_drain();
         bool is_mech_weapon = false;
         if( you.is_mounted() ) {
             monster *mons = get_player_character().mounted_creature.get();
             if( !mons->type->mech_weapon.is_empty() ) {
                 is_mech_weapon = true;
             }
         }
         if( gmode->energy_remaining( &you ) < energy_drain ) {
             result = false;
             if( is_mech_weapon ) {
                 messages.push_back( string_format( _( "Your mech has an empty battery, its %s will not fire." ),
                                                    gmode->tname() ) );
             } else if( gmode->has_flag( flag_USES_BIONIC_POWER ) ) {
                 messages.push_back( string_format(
                                         _( "You need at least %2$d kJ of bionic power to fire the %1$s!" ),
                                         gmode->tname(), units::to_kilojoule( energy_drain ) ) );
             } else if( gmode->has_flag( flag_USE_UPS ) ) {
                 messages.push_back( string_format(
                                         _( "You need a UPS with at least %2$d kJ to fire the %1$s!" ),
                                         gmode->tname(), units::to_kilojoule( energy_drain ) ) );
             }
         }
     }
     if( gmode->has_flag( flag_MOUNTED_GUN ) ) {
         const bool v_mountable = static_cast<bool>( m.veh_at( you.pos() ).part_with_feature( "MOUNTABLE",
                                  true ) );
         bool t_mountable = m.has_flag_ter_or_furn( ter_furn_flag::TFLAG_MOUNTABLE, you.pos() );
         if( !t_mountable && !v_mountable ) {
             messages.push_back( string_format(
                                     _( "You must stand near acceptable terrain or furniture to fire the %s.  A table, a mound of dirt, a broken window, etc." ),
                                     gmode->tname() ) );
             result = false;
         }
     }
     return result;
 }
References _, item::ammo_remaining(), item::ammo_required(), item::ammo_sufficient(), item::energy_remaining(), flag_MOUNTED_GUN, flag_RELOAD_AND_SHOOT, flag_USE_UPS, flag_USES_BIONIC_POWER, item::get_gun_energy_drain(), get_player_character(), item::has_flag(), map::has_flag_ter_or_furn(), string_id< T >::is_empty(), Character::is_mounted(), mtype::mech_weapon, Character::mounted_creature, optional_vpart_position::part_with_feature(), Creature::pos(), string_format(), TFLAG_MOUNTABLE, item::tname(), units::to_kilojoule(), monster::type, and map::veh_at().
Referenced by avatar_action::can_fire_weapon(), and target_ui::update_status().
occupied_tile_fraction()
double occupied_tile_fraction (creature_size target_size)
Definition at line 526 of file ranged.cpp.
 {
     switch( target_size ) {
         case creature_size::tiny:
             return 0.1;
         case creature_size::small:
             return 0.25;
         case creature_size::medium:
             return 0.5;
         case creature_size::large:
             return 0.75;
         case creature_size::huge:
             return 1.0;
         case creature_size::num_sizes:
             debugmsg( "ERROR: Invalid Creature size class." );
             break;
     }
     return 0.5;
 }
References debugmsg, huge, large, medium, num_sizes, small, and tiny.
Referenced by map::drop_items(), and Creature::ranged_target_size().
practice_archery_proficiency()
void practice_archery_proficiency (Character & p, const item & relevant)
Definition at line 1455 of file ranged.cpp.
 {
     // Do nothing, we are not doing archery
     if( relevant.gun_skill() != skill_archery ) {
         return;
     }
     // We are already a master, practice has no effect
     if( p.has_proficiency( proficiency_prof_bow_master ) ) {
         return;
     }
     // Only train archery in multiples of 100 moves (or 1 turn) for performance, focus, and simplifying calculations
     p.archery_aim_counter++;
     if( p.archery_aim_counter > 100 ) {
         // Reset our counter
         p.archery_aim_counter = 0;
         // Intended to train prof_bow_basic from 0 to 100% in ~200 arrows in 5 hours from max aim, or 90s/arrow.
         // Additionally, a shortbow is used as the basis for number of moves per max aim shot at ~250 moves.
         // 90s/arrow / 2.5turns/arrow = 36s/turn. It is important to note, this is 200 arrows pre-focus.
         time_duration prof_exp = 36_seconds;
         // We don't know how to handle a bow yet
         if( !p.has_proficiency( proficiency_prof_bow_basic ) ) {
             p.practice_proficiency( proficiency_prof_bow_basic, prof_exp );
             return;
         }
         // We know how to handle a bow, but we are not an expert yet
         else if( !p.has_proficiency( proficiency_prof_bow_expert ) ) {
             p.practice_proficiency( proficiency_prof_bow_expert, prof_exp );
             return;
         }
         // We are an expert, lets practice to become a master
         else {
             p.practice_proficiency( proficiency_prof_bow_master, prof_exp );
             return;
         }
     }
 }
References Creature::archery_aim_counter, item::gun_skill(), Character::has_proficiency(), Character::practice_proficiency(), proficiency_prof_bow_basic, proficiency_prof_bow_expert, proficiency_prof_bow_master, and skill_archery.
Referenced by do_aim().
range_with_even_chance_of_good_hit()
int range_with_even_chance_of_good_hit (int dispersion)
Definition at line 577 of file ranged.cpp.
 {
     int even_chance_range = 0;
     while( static_cast<unsigned>( even_chance_range ) <
            Creature::dispersion_for_even_chance_of_good_hit.size() &&
            dispersion < Creature::dispersion_for_even_chance_of_good_hit[ even_chance_range ] ) {
         even_chance_range++;
     }
     return even_chance_range;
 }
References Creature::dispersion_for_even_chance_of_good_hit, and om_direction::size.
Referenced by npc::confident_gun_mode_range(), and item::gun_info().
throw_cost()
int throw_cost (const Character & c, const item & to_throw)
Throw increases throwing speed Dexterity increases throwing speed
Definition at line 1110 of file ranged.cpp.
 {
     // Very similar to player::attack_speed
     // TODO: Extract into a function?
     // Differences:
     // Dex is more (2x) important for throwing speed
     // At 10 skill, the cost is down to 0.75%, not 0.66%
     const int base_move_cost = to_throw.attack_time( c ) / 2;
     const float throw_skill = std::min( static_cast<float>( MAX_SKILL ),
                                         c.get_skill_level( skill_throw ) );
     ///\EFFECT_THROW increases throwing speed
     const int skill_cost = static_cast<int>( ( base_move_cost * ( 20 - throw_skill ) / 20 ) );
     ///\EFFECT_DEX increases throwing speed
     const int dexbonus = c.get_dex();
     const float stamina_ratio = static_cast<float>( c.get_stamina() ) / c.get_stamina_max();
     const float stamina_penalty = 1.0 + std::max( ( 0.25f - stamina_ratio ) * 4.0f, 0.0f );
     int move_cost = base_move_cost;
     move_cost *= c.get_modifier( character_modifier_melee_thrown_move_lift_mod );
     move_cost *= c.get_modifier( character_modifier_melee_thrown_move_balance_mod );
     // Stamina penalty only affects base/2 and encumbrance parts of the cost
     move_cost *= stamina_penalty;
     move_cost += skill_cost;
     move_cost -= dexbonus;
     move_cost = c.enchantment_cache->modify_value( enchant_vals::mod::ATTACK_SPEED, move_cost );
     return std::max( 25, move_cost );
 }
References enchant_vals::ATTACK_SPEED, item::attack_time(), c, character_modifier_melee_thrown_move_balance_mod, character_modifier_melee_thrown_move_lift_mod, max(), MAX_SKILL, min(), and skill_throw.
Referenced by calculate_ranged_chances(), npc_attack_throw::evaluate_tripoint(), and Character::throw_item().
Variable Documentation
MIN_RECOIL_IMPROVEMENT
constexpr double MIN_RECOIL_IMPROVEMENT = 0.01 constexpr
Definition at line 24 of file ranged.h.
Referenced by Character::aim_per_move(), Character::gun_engagement_moves(), and predict_recoil().