Cataclysm DDA: src/recipe.cpp File Reference
recipe.cpp File Reference
#include "recipe.h"
#include <algorithm>
#include <cmath>
#include <limits>
#include <memory>
#include <numeric>
#include <optional>
#include <sstream>
#include "assign.h"
#include "cached_options.h"
#include "calendar.h"
#include "cartesian_product.h"
#include "cata_utility.h"
#include "character.h"
#include "color.h"
#include "debug.h"
#include "enum_traits.h"
#include "effect_on_condition.h"
#include "flag.h"
#include "game_constants.h"
#include "generic_factory.h"
#include "inventory.h"
#include "item.h"
#include "item_group.h"
#include "itype.h"
#include "json.h"
#include "mapgen_functions.h"
#include "npc.h"
#include "output.h"
#include "proficiency.h"
#include "recipe_dictionary.h"
#include "skill.h"
#include "string_formatter.h"
#include "string_id_utils.h"
#include "translations.h"
#include "type_id.h"
#include "uistate.h"
#include "units.h"
#include "value_ptr.h"
Classes
struct prof_penalty
Functions
static const std::string flag_FULL_MAGAZINE ("FULL_MAGAZINE")
static bool helpers_have_proficiencies (const Character &guy, const proficiency_id &prof)
static cata::value_ptr< parameterized_build_reqs > calculate_all_blueprint_reqs (const update_mapgen_id &id, const std::map< std::string, std::map< std::string, translation >> &bp_params)
static void set_new_comps (item &newit, int amount, item_components *used, bool is_food, bool is_cooked)
static void create_byproducts_legacy (const std::map< itype_id, int > &bplist, std::vector< item > &bps_out, int batch)
static void create_byproducts_group (const item_group_id &bplist, std::vector< item > &bps_out, int batch)
static std::string profstring (const prof_penalty &prof, std::string &color, const std::string &name_color="cyan")
static float get_aided_proficiency_level (const Character &crafter, const proficiency_id &prof)
static float proficiency_time_malus (const Character &crafter, const recipe_proficiency &prof)
static float proficiency_skill_malus (const Character &crafter, const recipe_proficiency &prof)
static std::string required_skills_as_string (const std::vector< std::pair< skill_id, int >> &skills, const Character &c)
static std::string required_skills_as_string (const std::vector< std::pair< skill_id, int >> &skills)
Variables
static const itype_id itype_atomic_coffeepot ("atomic_coffeepot")
static const itype_id itype_hotplate ("hotplate")
static const itype_id itype_null ("null")
Function Documentation
calculate_all_blueprint_reqs()
static cata::value_ptr<parameterized_build_reqs> calculate_all_blueprint_reqs (const update_mapgen_id & id, const std::map< std::string, std::map< std::string, translation >> & bp_params) static
Definition at line 473 of file recipe.cpp.
 {
     cata::value_ptr<parameterized_build_reqs> result = cata::make_value<parameterized_build_reqs>();
     const std::vector<std::unique_ptr<update_mapgen_function_json>> &funcs = id->funcs();
     if( funcs.size() != 1 ) {
         debugmsg( "update_mapgen %s used for blueprint, but has %zu versions, where it should have exactly one",
                   funcs.size() );
         return result;
     }
     // We gather the mapgen params from the mapgen function
     const update_mapgen_function_json &json_func = *funcs.front();
     const mapgen_parameters &mapgen_params = json_func.get_parameters();
     std::map<std::string, std::vector<std::string>> mapgen_param_names_and_possible_values;
     for( const std::pair<const std::string, mapgen_parameter> &mapgen_param : mapgen_params.map ) {
         mapgen_param_names_and_possible_values.emplace(
             mapgen_param.first, mapgen_param.second.all_possible_values( mapgen_params ) );
     }
     std::vector<std::string> mapgen_param_names;
     mapgen_param_names.reserve( mapgen_param_names_and_possible_values.size() );
     for( const std::pair<const std::string, std::vector<std::string>> &name_and_values :
          mapgen_param_names_and_possible_values ) {
         mapgen_param_names.push_back( name_and_values.first );
     }
     cata_assert( std::is_sorted( mapgen_param_names.begin(), mapgen_param_names.end() ) );
     // Then we gather the blueprint params from the recipe
     std::vector<std::string> bp_param_names;
     bp_param_names.reserve( bp_params.size() );
     for( const auto &bp_param : bp_params ) {
         bp_param_names.push_back( bp_param.first );
     }
     // NOLINTNEXTLINE(cata-use-localized-sorting)
     cata_assert( std::is_sorted( bp_param_names.begin(), bp_param_names.end() ) );
     // And check they match
     if( mapgen_param_names != bp_param_names ) {
         debugmsg( "parameter names listed in blueprint do not match those from corresponding "
                   "update_mapgen id %s.\nBlueprint had %s.\nupdate_mapgen had %s.",
                   id.str(),
                   enumerate_as_string( bp_param_names ),
                   enumerate_as_string( mapgen_param_names ) );
         return result;
     }
     // Furthermore, we check that, for each parameter, the set of possible
     // values in the mapgen matches the set of translated ids in the blueprint
     for( const auto &bp_param : bp_params ) {
         const std::string &name = bp_param.first;
         std::vector<std::string> &mapgen_values = mapgen_param_names_and_possible_values[name];
         // NOLINTNEXTLINE(cata-use-localized-sorting)
         std::sort( mapgen_values.begin(), mapgen_values.end() );
         std::vector<std::string> bp_values;
         bp_values.reserve( bp_param.second.size() );
         for( const std::pair<const std::string, translation> &p : bp_param.second ) {
             bp_values.push_back( p.first );
         }
         cata_assert( std::is_sorted( bp_values.begin(), bp_values.end() ) );
         if( mapgen_values != bp_values ) {
             debugmsg( "parameter values for parameter %s listed in blueprint do not match those "
                       "from corresponding update_mapgen id %s.\nBlueprint had %s.\n"
                       "update_mapgen had %s.",
                       name,
                       id.str(),
                       enumerate_as_string( bp_values ),
                       enumerate_as_string( mapgen_values ) );
             return result;
         }
     }
     // Each inner vector is a list of (param_name, param_value) pairs where
     // every param_name is the same, and each param_value is the set of
     // possible values for that param_name.  Once these lists are assembled we
     // will need to iterate over their cartesian product to get all the
     // possible options for parameter choices.
     std::vector<std::vector<std::pair<std::string, cata_variant>>> option_lists;
     for( const std::string &param_name : bp_param_names ) {
         option_lists.emplace_back();
         const mapgen_parameter &mapgen_param = mapgen_params.map.at( param_name );
         cata_variant_type param_type = mapgen_param.type();
         for( const std::pair<const std::string, translation> &p : bp_params.at( param_name ) ) {
             cata_variant param_value =
                 cata_variant::from_string( param_type, std::string( p.first ) );
             option_lists.back().emplace_back( param_name, param_value );
         }
     }
     for( const std::vector<std::pair<std::string, cata_variant>> &chosen_params :
          cata::cartesian_product( option_lists ) ) {
         result->reqs_by_parameters.emplace(
             chosen_params,
             get_build_reqs_for_furn_ter_ids(
                 get_changed_ids_from_update( id, mapgen_arguments{ chosen_params } ) ) );
     }
     return result;
 }
References cata::cartesian_product(), cata_assert, debugmsg, enumerate_as_string(), cata_variant::from_string(), get_build_reqs_for_furn_ter_ids(), get_changed_ids_from_update(), mapgen_function_json_base::get_parameters(), mapgen_parameters::map, om_direction::name(), and mapgen_parameter::type().
Referenced by recipe::finalize().
create_byproducts_group()
static void create_byproducts_group (const item_group_id & bplist, std::vector< item > & bps_out, int batch) static
Definition at line 839 of file recipe.cpp.
 {
     std::vector<item> ret = item_group::items_from( bplist, calendar::turn );
     for( item &it : ret ) {
         if( it.count_by_charges() ) {
             it.charges *= batch;
         } else {
             if( !it.craft_has_charges() ) {
                 it.charges = 0;
             }
             for( int i = 1; i < batch; ++i ) {
                 bps_out.push_back( it );
             }
         }
     }
     bps_out.insert( bps_out.end(), ret.begin(), ret.end() );
 }
References item_group::items_from(), cata::hash64_detail::ret, and calendar::turn.
Referenced by recipe::create_byproducts().
create_byproducts_legacy()
static void create_byproducts_legacy (const std::map< itype_id, int > & bplist, std::vector< item > & bps_out, int batch) static
Definition at line 817 of file recipe.cpp.
 {
     for( const auto &e : bplist ) {
         item obj( e.first, calendar::turn, item::default_charges_tag{} );
         if( obj.has_flag( flag_VARSIZE ) ) {
             obj.set_flag( flag_FIT );
         }
         if( obj.count_by_charges() ) {
             obj.charges *= e.second * batch;
             bps_out.push_back( obj );
         } else {
             if( !obj.craft_has_charges() ) {
                 obj.charges = 0;
             }
             for( int i = 0; i < e.second * batch; ++i ) {
                 bps_out.push_back( obj );
             }
         }
     }
 }
References flag_FIT, flag_VARSIZE, int_id< T >::obj(), and calendar::turn.
Referenced by recipe::create_byproducts().
flag_FULL_MAGAZINE()
static const std::string flag_FULL_MAGAZINE ("FULL_MAGAZINE") static
Referenced by recipe::create_result().
get_aided_proficiency_level()
static float get_aided_proficiency_level (const Character & crafter, const proficiency_id & prof) static
Definition at line 1029 of file recipe.cpp.
 {
     float max_prof = crafter.get_proficiency_practice( prof );
     for( const Character *helper : crafter.get_crafting_group() ) {
         max_prof = std::max( max_prof, helper->get_proficiency_practice( prof ) );
     }
     return max_prof;
 }
References Character::get_crafting_group(), Character::get_proficiency_practice(), and max().
Referenced by proficiency_skill_malus(), and proficiency_time_malus().
helpers_have_proficiencies()
static bool helpers_have_proficiencies (const Character & guy, const proficiency_id & prof) static
Definition at line 77 of file recipe.cpp.
 {
     for( Character *helper : guy.get_crafting_group() ) {
         if( helper->has_proficiency( prof ) ) {
             return true;
         }
     }
     return false;
 }
References Character::get_crafting_group().
Referenced by recipe::character_has_required_proficiencies(), recipe::missing_proficiencies_string(), proficiency_skill_malus(), proficiency_time_malus(), recipe::required_proficiencies_string(), and recipe::used_proficiencies_string().
proficiency_skill_malus()
static float proficiency_skill_malus (const Character & crafter, const recipe_proficiency & prof) static
Definition at line 1073 of file recipe.cpp.
 {
     if( !crafter.has_proficiency( prof.id )
         && !helpers_have_proficiencies( crafter, prof.id )
         && prof.skill_penalty > 0.f
       ) {
         double malus =  prof.skill_penalty;
         malus *= 1.0 - crafter.crafting_inventory().get_book_proficiency_bonuses().fail_factor( prof.id );
         double pl = get_aided_proficiency_level( crafter, prof.id );
         // The failure malus is not completely eliminated until the proficiency is mastered.
         // Most of the mitigation happens at higher pl. See #49198
         malus *= 1.0 - ( 0.75 * std::pow( pl, 3 ) );
         return static_cast<float>( malus );
     }
     return 0.0f;
 }
References Character::crafting_inventory(), book_proficiency_bonuses::fail_factor(), get_aided_proficiency_level(), inventory::get_book_proficiency_bonuses(), Character::has_proficiency(), helpers_have_proficiencies(), recipe_proficiency::id, and recipe_proficiency::skill_penalty.
Referenced by recipe::missing_proficiencies_string(), and recipe::proficiency_skill_maluses().
proficiency_time_malus()
static float proficiency_time_malus (const Character & crafter, const recipe_proficiency & prof) static
Definition at line 1038 of file recipe.cpp.
 {
     if( !crafter.has_proficiency( prof.id )
         && !helpers_have_proficiencies( crafter, prof.id )
         && prof.time_multiplier > 1.0f
       ) {
         double malus = prof.time_multiplier - 1.0;
         malus *= 1.0 - crafter.crafting_inventory().get_book_proficiency_bonuses().time_factor( prof.id );
         double pl = get_aided_proficiency_level( crafter, prof.id );
         // Sigmoid function that mitigates 100% of the time malus as pl approaches 1.0
         // but has little effect at pl < 0.5. See #49198
         malus *= 1.0 - std::pow( 0.5 - 0.5 * std::cos( pl * M_PI ), 2 );
         return static_cast<float>( 1.0 + malus );
     }
     return 1.0f;
 }
References cos(), Character::crafting_inventory(), get_aided_proficiency_level(), inventory::get_book_proficiency_bonuses(), Character::has_proficiency(), helpers_have_proficiencies(), recipe_proficiency::id, M_PI, book_proficiency_bonuses::time_factor(), and recipe_proficiency::time_multiplier.
Referenced by recipe::missing_proficiencies_string(), and recipe::proficiency_time_maluses().
profstring()
static std::string profstring (const prof_penalty & prof, std::string & color, const std::string & name_color = "cyan") static
Definition at line 935 of file recipe.cpp.
 {
     std::string mitigated_str;
     if( prof.mitigated ) {
         mitigated_str = _( " (Mitigated)" );
     }
     if( prof.time_mult == 1.0f ) {
         return string_format( _( "<color_%s>%s</color> (<color_%s>%.2f\u00a0skill bonus</color>%s)" ),
                               name_color, prof.id->name(), color, prof.skill_penalty, mitigated_str );
     } else if( prof.skill_penalty == 0.0f ) {
         return string_format( _( "<color_%s>%s</color> (<color_%s>%.2fx\u00a0time</color>%s)" ),
                               name_color, prof.id->name(), color, prof.time_mult, mitigated_str );
     }
     return string_format(
                _( "<color_%s>%s</color> (<color_%s>%.2fx\u00a0time, %.2f\u00a0skill bonus</color>%s)" ),
                name_color, prof.id->name(), color, prof.time_mult, prof.skill_penalty, mitigated_str );
 }
References _, color(), prof_penalty::id, prof_penalty::mitigated, proficiency::name(), prof_penalty::skill_penalty, string_format(), and prof_penalty::time_mult.
required_skills_as_string() [1/2]
static std::string required_skills_as_string (const std::vector< std::pair< skill_id, int >> & skills) static
Definition at line 1172 of file recipe.cpp.
 {
     if( skills.empty() ) {
         return _( "<color_cyan>none</color>" );
     }
     return enumerate_as_string( skills,
     [&]( const std::pair<skill_id, int> &skill ) {
         return string_format( "<color_white>%s (%d)</color>", skill.first->name(), skill.second );
     } );
 }
References _, enumerate_as_string(), and string_format().
required_skills_as_string() [2/2]
static std::string required_skills_as_string (const std::vector< std::pair< skill_id, int >> & skills, const Character & c) static
Definition at line 1148 of file recipe.cpp.
 {
     if( skills.empty() ) {
         return _( "<color_cyan>none</color>" );
     }
     return enumerate_as_string( skills,
     [&]( const std::pair<skill_id, int> &skill ) {
         const int player_skill = c.get_skill_level( skill.first );
         std::string difficulty_color;
         if( skill.second <= player_skill ) {
             difficulty_color = "green";
         } else if( static_cast<int>( skill.second * 0.8 ) <= player_skill ) {
             difficulty_color = "yellow";
         } else {
             difficulty_color = "red";
         }
         return string_format( "<color_cyan>%s</color> <color_%s>(%d/%d)</color>", skill.first->name(),
                               difficulty_color, player_skill, skill.second );
     } );
 }
References _, c, enumerate_as_string(), and string_format().
Referenced by recipe::primary_skill_string(), recipe::required_all_skills_string(), and recipe::required_skills_string().
set_new_comps()
static void set_new_comps (item & newit, int amount, item_components * used, bool is_food, bool is_cooked) static
Definition at line 712 of file recipe.cpp.
 {
     if( is_food ) {
         newit.components = *used;
         newit.recipe_charges = amount;
     } else {
         newit.components = used->split( amount, 0, is_cooked );
     }
 }
References item::components, item::recipe_charges, and item_components::split().
Referenced by recipe::create_result().
Variable Documentation
itype_atomic_coffeepot
const itype_id itype_atomic_coffeepot("atomic_coffeepot") ("atomic_coffeepot") static
Referenced by recipe::hot_result().
itype_hotplate
const itype_id itype_hotplate("hotplate") ("hotplate") static
Referenced by recipe::hot_result().
itype_null
const itype_id itype_null("null") ("null") static
Referenced by recipe::finalize().