Cataclysm DDA: src/regional_settings.cpp File Reference
regional_settings.cpp File Reference
#include "regional_settings.h"
#include <algorithm>
#include <map>
#include <memory>
#include <sstream>
#include <string>
#include <utility>
#include "debug.h"
#include "enum_conversions.h"
#include "generic_factory.h"
#include "json.h"
#include "map_extras.h"
#include "options.h"
#include "output.h"
#include "rng.h"
#include "string_formatter.h"
#include "translations.h"
Functions
template<typename T >
void read_and_set_or_throw (const JsonObject &jo, const std::string &member, T &target, bool required)
static void load_forest_biome_component (const JsonObject &jo, forest_biome_component &forest_biome_component, const bool overlay)
static void load_forest_biome_terrain_dependent_furniture (const JsonObject &jo, forest_biome_terrain_dependent_furniture &forest_biome_terrain_dependent_furniture, const bool overlay)
static void load_forest_biome (const JsonObject &jo, forest_biome &forest_biome, const bool overlay)
static void load_forest_mapgen_settings (const JsonObject &jo, forest_mapgen_settings &forest_mapgen_settings, const bool strict, const bool overlay)
static void load_forest_trail_settings (const JsonObject &jo, forest_trail_settings &forest_trail_settings, const bool strict, const bool overlay)
static void load_overmap_feature_flag_settings (const JsonObject &jo, overmap_feature_flag_settings &overmap_feature_flag_settings, const bool strict, const bool overlay)
static void load_overmap_forest_settings (const JsonObject &jo, overmap_forest_settings &overmap_forest_settings, const bool strict, const bool overlay)
static void load_overmap_ravine_settings (const JsonObject &jo, overmap_ravine_settings &overmap_ravine_settings, const bool strict, const bool overlay)
static void load_overmap_connection_settings (const JsonObject &jo, overmap_connection_settings &overmap_connection_settings, const bool strict, const bool overlay)
static void load_overmap_lake_settings (const JsonObject &jo, overmap_lake_settings &overmap_lake_settings, const bool strict, const bool overlay)
static void load_overmap_ocean_settings (const JsonObject &jo, overmap_ocean_settings &overmap_ocean_settings, const bool strict, const bool overlay)
static void load_region_terrain_and_furniture_settings (const JsonObject &jo, region_terrain_and_furniture_settings &region_terrain_and_furniture_settings, const bool strict, const bool overlay)
void load_region_settings (const JsonObject &jo)
void check_region_settings ()
void reset_region_settings ()
void load_region_overlay (const JsonObject &jo)
void apply_region_overlay (const JsonObject &jo, regional_settings &region)
Function Documentation
apply_region_overlay()
void apply_region_overlay (const JsonObject & jo, regional_settings & region)
Definition at line 686 of file regional_settings.cpp.
 {
     jo.read( "default_oter", region.default_oter );
     jo.read( "river_scale", region.river_scale );
     if( jo.has_array( "default_groundcover" ) ) {
         region.default_groundcover_str.reset( new weighted_int_list<ter_str_id> );
         for( JsonArray inner : jo.get_array( "default_groundcover" ) ) {
             if( region.default_groundcover_str->add( ter_str_id( inner.get_string( 0 ) ),
                     inner.get_int( 1 ) ) == nullptr ) {
                 jo.throw_error( "'default_groundcover' must be a weighted list: an array of pairs [ \"id\", weight ]" );
             }
         }
     }
     load_forest_mapgen_settings( jo, region.forest_composition, false, true );
     load_forest_trail_settings( jo, region.forest_trail, false, true );
     for( const JsonMember zone : jo.get_object( "map_extras" ) ) {
         if( zone.is_comment() ) {
             continue;
         }
         JsonObject zonejo = zone.get_object();
         map_extras &extras = region.region_extras[zone.name()];
         int tmpval = 0;
         if( zonejo.read( "chance", tmpval ) ) {
             extras.chance = tmpval;
         }
         for( const JsonMember member : zonejo.get_object( "extras" ) ) {
             if( member.is_comment() ) {
                 continue;
             }
             extras.values.add_or_replace( map_extra_id( member.name() ), member.get_int() );
         }
         // It's possible that all the entries of the weighted list have their
         // weights set to zero by this overlay.  In that case we want to reset
         // the chance to zero.
         if( !extras.values.is_valid() ) {
             extras.chance = 0;
         }
     }
     JsonObject cityjo = jo.get_object( "city" );
     cityjo.read( "shop_radius", region.city_spec.shop_radius );
     cityjo.read( "shop_sigma", region.city_spec.shop_sigma );
     cityjo.read( "park_radius", region.city_spec.park_radius );
     cityjo.read( "park_sigma", region.city_spec.park_sigma );
     const auto load_building_types = [&cityjo]( const std::string_view type, building_bin & dest ) {
         for( const JsonMember member : cityjo.get_object( type ) ) {
             if( member.is_comment() ) {
                 continue;
             }
             dest.add( overmap_special_id( member.name() ), member.get_int() );
         }
     };
     load_building_types( "houses", region.city_spec.houses );
     load_building_types( "shops", region.city_spec.shops );
     load_building_types( "parks", region.city_spec.parks );
     load_overmap_feature_flag_settings( jo, region.overmap_feature_flag, false, true );
     load_overmap_forest_settings( jo, region.overmap_forest, false, true );
     load_overmap_lake_settings( jo, region.overmap_lake, false, true );
     load_overmap_ocean_settings( jo, region.overmap_ocean, false, true );
     load_overmap_ravine_settings( jo, region.overmap_ravine, false, true );
     load_overmap_connection_settings( jo, region.overmap_connection, false, true );
     load_region_terrain_and_furniture_settings( jo, region.region_terrain_and_furniture, false, true );
 }
References regional_settings::city_spec, regional_settings::default_groundcover_str, regional_settings::default_oter, anonymous_namespace{map_extras.cpp}::extras, regional_settings::forest_composition, regional_settings::forest_trail, JsonObject::get_array(), JsonObject::get_object(), JsonObject::has_array(), city_settings::houses, load_forest_mapgen_settings(), load_forest_trail_settings(), load_overmap_connection_settings(), load_overmap_feature_flag_settings(), load_overmap_forest_settings(), load_overmap_lake_settings(), load_overmap_ocean_settings(), load_overmap_ravine_settings(), load_region_terrain_and_furniture_settings(), member, regional_settings::overmap_connection, regional_settings::overmap_feature_flag, regional_settings::overmap_forest, regional_settings::overmap_lake, regional_settings::overmap_ocean, regional_settings::overmap_ravine, city_settings::park_radius, city_settings::park_sigma, city_settings::parks, JsonObject::read(), regional_settings::region_extras, regional_settings::region_terrain_and_furniture, regional_settings::river_scale, city_settings::shop_radius, city_settings::shop_sigma, city_settings::shops, and JsonObject::throw_error().
Referenced by load_region_overlay().
check_region_settings()
void check_region_settings ()
Definition at line 617 of file regional_settings.cpp.
 {
     for( const std::pair<const std::string, regional_settings> &p : region_settings_map ) {
         const std::string &region_name = p.first;
         const regional_settings &region = p.second;
         for( const std::pair<const std::string, map_extras> &p2 : region.region_extras ) {
             const std::string extras_name = p2.first;
             const map_extras &extras = p2.second;
             if( extras.chance == 0 ) {
                 continue;
             }
             const weighted_int_list<map_extra_id> &values = extras.values;
             if( !values.is_valid() ) {
                 if( values.empty() ) {
                     debugmsg( "Invalid map extras for region \"%s\", extras \"%s\".  "
                               "Extras have nonzero chance but no extras are listed.",
                               region_name, extras_name );
                 } else {
                     std::string list_of_values =
                         enumerate_as_string( values,
                     []( const weighted_object<int, map_extra_id> &w ) {
                         return '"' + w.obj.str() + '"';
                     } );
                     debugmsg( "Invalid map extras for region \"%s\", extras \"%s\".  "
                               "Extras %s are listed, but all have zero weight.",
                               region_name, extras_name,
                               list_of_values );
                 }
             }
         }
     }
 }
References debugmsg, weighted_list< W, T >::empty(), enumerate_as_string(), anonymous_namespace{map_extras.cpp}::extras, weighted_list< W, T >::is_valid(), weighted_object< W, T >::obj, regional_settings::region_extras, and region_settings_map.
Referenced by DynamicDataLoader::check_consistency().
load_forest_biome()
static void load_forest_biome (const JsonObject & jo, forest_biome & forest_biome, const bool overlay) static
Definition at line 90 of file regional_settings.cpp.
 {
     read_and_set_or_throw<int>( jo, "sparseness_adjacency_factor",
                                 forest_biome.sparseness_adjacency_factor, !overlay );
     read_and_set_or_throw( jo, "item_group", forest_biome.item_group, !overlay );
     read_and_set_or_throw<int>( jo, "item_group_chance", forest_biome.item_group_chance, !overlay );
     read_and_set_or_throw<int>( jo, "item_spawn_iterations", forest_biome.item_spawn_iterations,
                                 !overlay );
     read_and_set_or_throw<bool>( jo, "clear_components", forest_biome.clear_components, !overlay );
     read_and_set_or_throw<bool>( jo, "clear_groundcover", forest_biome.clear_groundcover, !overlay );
     read_and_set_or_throw<bool>( jo, "clear_terrain_furniture", forest_biome.clear_terrain_furniture,
                                  !overlay );
     if( forest_biome.clear_components ) {
         forest_biome.unfinalized_biome_components.clear();
     }
     if( !jo.has_object( "components" ) ) {
         if( !overlay ) {
             jo.throw_error( "components required" );
         }
     } else {
         for( const JsonMember member : jo.get_object( "components" ) ) {
             if( member.is_comment() ) {
                 continue;
             }
             JsonObject component_jo = member.get_object();
             load_forest_biome_component( component_jo, forest_biome.unfinalized_biome_components[member.name()],
                                          overlay );
         }
     }
     if( forest_biome.clear_groundcover ) {
         forest_biome.unfinalized_groundcover.clear();
     }
     if( !jo.has_object( "groundcover" ) ) {
         if( !overlay ) {
             jo.throw_error( "groundcover required" );
         }
     } else {
         for( const JsonMember member : jo.get_object( "groundcover" ) ) {
             if( member.is_comment() ) {
                 continue;
             }
             forest_biome.unfinalized_groundcover[member.name()] = member.get_int();
         }
     }
     if( !jo.has_object( "terrain_furniture" ) ) {
         if( !overlay ) {
             jo.throw_error( "terrain_furniture required" );
         }
     } else {
         for( const JsonMember member : jo.get_object( "terrain_furniture" ) ) {
             if( member.is_comment() ) {
                 continue;
             }
             JsonObject terrain_furniture_jo = member.get_object();
             load_forest_biome_terrain_dependent_furniture( terrain_furniture_jo,
                     forest_biome.unfinalized_terrain_dependent_furniture[member.name()], overlay );
         }
     }
 }
References forest_biome::clear_components, forest_biome::clear_groundcover, forest_biome::clear_terrain_furniture, JsonObject::get_object(), JsonObject::has_object(), forest_biome::item_group, forest_biome::item_group_chance, forest_biome::item_spawn_iterations, load_forest_biome_component(), load_forest_biome_terrain_dependent_furniture(), member, read_and_set_or_throw(), forest_biome::sparseness_adjacency_factor, JsonObject::throw_error(), forest_biome::unfinalized_biome_components, forest_biome::unfinalized_groundcover, and forest_biome::unfinalized_terrain_dependent_furniture.
Referenced by load_forest_mapgen_settings().
load_forest_biome_component()
static void load_forest_biome_component (const JsonObject & jo, forest_biome_component & forest_biome_component, const bool overlay) static
Definition at line 38 of file regional_settings.cpp.
 {
     read_and_set_or_throw<int>( jo, "chance", forest_biome_component.chance, !overlay );
     read_and_set_or_throw<int>( jo, "sequence", forest_biome_component.sequence, !overlay );
     read_and_set_or_throw<bool>( jo, "clear_types", forest_biome_component.clear_types, !overlay );
     if( forest_biome_component.clear_types ) {
         forest_biome_component.unfinalized_types.clear();
     }
     if( !jo.has_object( "types" ) ) {
         if( !overlay ) {
             jo.throw_error( "types required" );
         }
     } else {
         for( const JsonMember member : jo.get_object( "types" ) ) {
             if( member.is_comment() ) {
                 continue;
             }
             forest_biome_component.unfinalized_types[member.name()] = member.get_int();
         }
     }
 }
References forest_biome_component::chance, forest_biome_component::clear_types, JsonObject::get_object(), JsonObject::has_object(), member, forest_biome_component::sequence, JsonObject::throw_error(), and forest_biome_component::unfinalized_types.
Referenced by load_forest_biome().
load_forest_biome_terrain_dependent_furniture()
static void load_forest_biome_terrain_dependent_furniture (const JsonObject & jo, forest_biome_terrain_dependent_furniture & forest_biome_terrain_dependent_furniture, const bool overlay) static
Definition at line 63 of file regional_settings.cpp.
 {
     read_and_set_or_throw<int>( jo, "chance", forest_biome_terrain_dependent_furniture.chance,
                                 !overlay );
     read_and_set_or_throw<bool>( jo, "clear_furniture",
                                  forest_biome_terrain_dependent_furniture.clear_furniture, !overlay );
     if( forest_biome_terrain_dependent_furniture.clear_furniture ) {
         forest_biome_terrain_dependent_furniture.unfinalized_furniture.clear();
     }
     if( !jo.has_object( "furniture" ) ) {
         if( !overlay ) {
             jo.throw_error( "furniture required" );
         }
     } else {
         for( const JsonMember member : jo.get_object( "furniture" ) ) {
             if( member.is_comment() ) {
                 continue;
             }
             forest_biome_terrain_dependent_furniture.unfinalized_furniture[member.name()] = member.get_int();
         }
     }
 }
References forest_biome_terrain_dependent_furniture::chance, forest_biome_terrain_dependent_furniture::clear_furniture, JsonObject::get_object(), JsonObject::has_object(), member, JsonObject::throw_error(), and forest_biome_terrain_dependent_furniture::unfinalized_furniture.
Referenced by load_forest_biome().
load_forest_mapgen_settings()
static void load_forest_mapgen_settings (const JsonObject & jo, forest_mapgen_settings & forest_mapgen_settings, const bool strict, const bool overlay) static
Definition at line 156 of file regional_settings.cpp.
 {
     if( !jo.has_object( "forest_mapgen_settings" ) ) {
         if( strict ) {
             jo.throw_error( "\"forest_mapgen_settings\": {  } required for default" );
         }
     } else {
         for( const JsonMember member : jo.get_object( "forest_mapgen_settings" ) ) {
             if( member.is_comment() ) {
                 continue;
             }
             JsonObject forest_biome_jo = member.get_object();
             if( forest_biome_jo.has_array( "terrains" ) ) {
                 JsonArray forest_biome_ter_keys = forest_biome_jo.get_array( "terrains" );
                 if( forest_biome_ter_keys.empty() ) {
                     forest_biome_jo.throw_error( "Biome is not associated with any terrains." );
                 }
                 std::string default_ter_name = member.name();
                 auto default_ter_it = forest_mapgen_settings.unfinalized_biomes.find( default_ter_name );
                 if( default_ter_it == forest_mapgen_settings.unfinalized_biomes.end() ) {
                     if( overlay ) {
                         forest_biome_jo.throw_error( "Terrain " + default_ter_name +
                                                      " is not defined, cannot be used for forest biome." );
                     }
                     default_ter_it = forest_mapgen_settings.unfinalized_biomes.emplace( default_ter_name, forest_biome{} ).first;
                 }
                 forest_biome &default_ter = default_ter_it->second;
                 load_forest_biome( forest_biome_jo, default_ter, overlay );
                 for( size_t biome_ter_idx = 0; biome_ter_idx < forest_biome_ter_keys.size(); biome_ter_idx++ ) {
                     std::string biome_ter_name = forest_biome_ter_keys.get_string( biome_ter_idx );
                     if( biome_ter_name == default_ter_name ) {
                         continue;
                     }
                     forest_mapgen_settings.unfinalized_biomes.insert( std::pair<std::string, forest_biome>
                             ( forest_biome_ter_keys.get_string( biome_ter_idx ), default_ter ) );
                 }
             } else {
                 load_forest_biome( forest_biome_jo, forest_mapgen_settings.unfinalized_biomes[member.name()],
                                    overlay );
             }
         }
     }
 }
References JsonArray::empty(), JsonObject::get_array(), JsonObject::get_object(), JsonArray::get_string(), JsonObject::has_array(), JsonObject::has_object(), load_forest_biome(), member, JsonArray::size(), strict, JsonObject::throw_error(), and forest_mapgen_settings::unfinalized_biomes.
Referenced by apply_region_overlay(), and load_region_settings().
load_forest_trail_settings()
static void load_forest_trail_settings (const JsonObject & jo, forest_trail_settings & forest_trail_settings, const bool strict, const bool overlay) static
Definition at line 203 of file regional_settings.cpp.
 {
     if( !jo.has_object( "forest_trail_settings" ) ) {
         if( strict ) {
             jo.throw_error( "\"forest_trail_settings\": {  } required for default" );
         }
     } else {
         JsonObject forest_trail_settings_jo = jo.get_object( "forest_trail_settings" );
         read_and_set_or_throw<int>( forest_trail_settings_jo, "chance", forest_trail_settings.chance,
                                     !overlay );
         read_and_set_or_throw<int>( forest_trail_settings_jo, "border_point_chance",
                                     forest_trail_settings.border_point_chance, !overlay );
         read_and_set_or_throw<int>( forest_trail_settings_jo, "minimum_forest_size",
                                     forest_trail_settings.minimum_forest_size, !overlay );
         read_and_set_or_throw<int>( forest_trail_settings_jo, "random_point_min",
                                     forest_trail_settings.random_point_min, !overlay );
         read_and_set_or_throw<int>( forest_trail_settings_jo, "random_point_max",
                                     forest_trail_settings.random_point_max, !overlay );
         read_and_set_or_throw<int>( forest_trail_settings_jo, "random_point_size_scalar",
                                     forest_trail_settings.random_point_size_scalar, !overlay );
         read_and_set_or_throw<int>( forest_trail_settings_jo, "trailhead_chance",
                                     forest_trail_settings.trailhead_chance, !overlay );
         read_and_set_or_throw<int>( forest_trail_settings_jo, "trailhead_road_distance",
                                     forest_trail_settings.trailhead_road_distance, !overlay );
         if( !forest_trail_settings_jo.has_object( "trailheads" ) ) {
             if( !overlay ) {
                 forest_trail_settings_jo.throw_error( "trailheads required" );
             }
         } else {
             for( const JsonMember member : forest_trail_settings_jo.get_object( "trailheads" ) ) {
                 if( member.is_comment() ) {
                     continue;
                 }
                 forest_trail_settings.trailheads.add( overmap_special_id( member.name() ), member.get_int() );
             }
         }
     }
 }
References building_bin::add(), forest_trail_settings::border_point_chance, forest_trail_settings::chance, JsonObject::get_object(), JsonObject::has_object(), member, forest_trail_settings::minimum_forest_size, forest_trail_settings::random_point_max, forest_trail_settings::random_point_min, forest_trail_settings::random_point_size_scalar, strict, JsonObject::throw_error(), forest_trail_settings::trailhead_chance, forest_trail_settings::trailhead_road_distance, and forest_trail_settings::trailheads.
Referenced by apply_region_overlay(), and load_region_settings().
load_overmap_connection_settings()
static void load_overmap_connection_settings (const JsonObject & jo, overmap_connection_settings & overmap_connection_settings, const bool strict, const bool overlay) static
Definition at line 336 of file regional_settings.cpp.
 {
     if( !jo.has_object( "overmap_connection_settings" ) ) {
         if( strict ) {
             jo.throw_error( "\"overmap_connection_settings\": {  } required for default" );
         }
     } else {
         JsonObject overmap_connection_settings_jo = jo.get_object( "overmap_connection_settings" );
         read_and_set_or_throw<overmap_connection_id>( overmap_connection_settings_jo, "trail_connection",
                 overmap_connection_settings.trail_connection, !overlay );
         read_and_set_or_throw<overmap_connection_id>( overmap_connection_settings_jo, "sewer_connection",
                 overmap_connection_settings.sewer_connection, !overlay );
         read_and_set_or_throw<overmap_connection_id>( overmap_connection_settings_jo, "subway_connection",
                 overmap_connection_settings.subway_connection, !overlay );
         read_and_set_or_throw<overmap_connection_id>( overmap_connection_settings_jo, "rail_connection",
                 overmap_connection_settings.rail_connection, !overlay );
         read_and_set_or_throw<overmap_connection_id>( overmap_connection_settings_jo,
                 "intra_city_road_connection",
                 overmap_connection_settings.intra_city_road_connection, !overlay );
         read_and_set_or_throw<overmap_connection_id>( overmap_connection_settings_jo,
                 "inter_city_road_connection",
                 overmap_connection_settings.inter_city_road_connection, !overlay );
     }
 }
References JsonObject::get_object(), JsonObject::has_object(), overmap_connection_settings::inter_city_road_connection, overmap_connection_settings::intra_city_road_connection, overmap_connection_settings::rail_connection, overmap_connection_settings::sewer_connection, strict, overmap_connection_settings::subway_connection, JsonObject::throw_error(), and overmap_connection_settings::trail_connection.
Referenced by apply_region_overlay(), and load_region_settings().
load_overmap_feature_flag_settings()
static void load_overmap_feature_flag_settings (const JsonObject & jo, overmap_feature_flag_settings & overmap_feature_flag_settings, const bool strict, const bool overlay) static
Definition at line 245 of file regional_settings.cpp.
 {
     if( !jo.has_object( "overmap_feature_flag_settings" ) ) {
         if( strict ) {
             jo.throw_error( "\"overmap_feature_flag_settings\": {  } required for default" );
         }
     } else {
         JsonObject overmap_feature_flag_settings_jo = jo.get_object( "overmap_feature_flag_settings" );
         read_and_set_or_throw<bool>( overmap_feature_flag_settings_jo, "clear_blacklist",
                                      overmap_feature_flag_settings.clear_blacklist, !overlay );
         read_and_set_or_throw<bool>( overmap_feature_flag_settings_jo, "clear_whitelist",
                                      overmap_feature_flag_settings.clear_whitelist, !overlay );
         if( overmap_feature_flag_settings.clear_blacklist ) {
             overmap_feature_flag_settings.blacklist.clear();
         }
         if( overmap_feature_flag_settings.clear_whitelist ) {
             overmap_feature_flag_settings.whitelist.clear();
         }
         if( !overmap_feature_flag_settings_jo.has_array( "blacklist" ) ) {
             if( !overlay ) {
                 overmap_feature_flag_settings_jo.throw_error( "blacklist required" );
             }
         } else {
             for( const std::string line : overmap_feature_flag_settings_jo.get_array( "blacklist" ) ) {
                 overmap_feature_flag_settings.blacklist.emplace( line );
             }
         }
         if( !overmap_feature_flag_settings_jo.has_array( "whitelist" ) ) {
             if( !overlay ) {
                 overmap_feature_flag_settings_jo.throw_error( "whitelist required" );
             }
         } else {
             for( const std::string line : overmap_feature_flag_settings_jo.get_array( "whitelist" ) ) {
                 overmap_feature_flag_settings.whitelist.emplace( line );
             }
         }
     }
 }
References overmap_feature_flag_settings::blacklist, overmap_feature_flag_settings::clear_blacklist, overmap_feature_flag_settings::clear_whitelist, JsonObject::get_array(), JsonObject::get_object(), JsonObject::has_array(), JsonObject::has_object(), line(), strict, JsonObject::throw_error(), and overmap_feature_flag_settings::whitelist.
Referenced by apply_region_overlay(), and load_region_settings().
load_overmap_forest_settings()
static void load_overmap_forest_settings (const JsonObject & jo, overmap_forest_settings & overmap_forest_settings, const bool strict, const bool overlay) static
Definition at line 290 of file regional_settings.cpp.
 {
     if( !jo.has_object( "overmap_forest_settings" ) ) {
         if( strict ) {
             jo.throw_error( "\"overmap_forest_settings\": {  } required for default" );
         }
     } else {
         JsonObject overmap_forest_settings_jo = jo.get_object( "overmap_forest_settings" );
         read_and_set_or_throw<double>( overmap_forest_settings_jo, "noise_threshold_forest",
                                        overmap_forest_settings.noise_threshold_forest, !overlay );
         read_and_set_or_throw<double>( overmap_forest_settings_jo, "noise_threshold_forest_thick",
                                        overmap_forest_settings.noise_threshold_forest_thick, !overlay );
         read_and_set_or_throw<double>( overmap_forest_settings_jo, "noise_threshold_swamp_adjacent_water",
                                        overmap_forest_settings.noise_threshold_swamp_adjacent_water, !overlay );
         read_and_set_or_throw<double>( overmap_forest_settings_jo, "noise_threshold_swamp_isolated",
                                        overmap_forest_settings.noise_threshold_swamp_isolated, !overlay );
         read_and_set_or_throw<int>( overmap_forest_settings_jo, "river_floodplain_buffer_distance_min",
                                     overmap_forest_settings.river_floodplain_buffer_distance_min, !overlay );
         read_and_set_or_throw<int>( overmap_forest_settings_jo, "river_floodplain_buffer_distance_max",
                                     overmap_forest_settings.river_floodplain_buffer_distance_max, !overlay );
     }
 }
References JsonObject::get_object(), JsonObject::has_object(), overmap_forest_settings::noise_threshold_forest, overmap_forest_settings::noise_threshold_forest_thick, overmap_forest_settings::noise_threshold_swamp_adjacent_water, overmap_forest_settings::noise_threshold_swamp_isolated, overmap_forest_settings::river_floodplain_buffer_distance_max, overmap_forest_settings::river_floodplain_buffer_distance_min, strict, and JsonObject::throw_error().
Referenced by apply_region_overlay(), and load_region_settings().
load_overmap_lake_settings()
static void load_overmap_lake_settings (const JsonObject & jo, overmap_lake_settings & overmap_lake_settings, const bool strict, const bool overlay) static
Definition at line 363 of file regional_settings.cpp.
 {
     if( !jo.has_object( "overmap_lake_settings" ) ) {
         if( strict ) {
             jo.throw_error( "\"overmap_lake_settings\": {  } required for default" );
         }
     } else {
         JsonObject overmap_lake_settings_jo = jo.get_object( "overmap_lake_settings" );
         read_and_set_or_throw<double>( overmap_lake_settings_jo, "noise_threshold_lake",
                                        overmap_lake_settings.noise_threshold_lake, !overlay );
         read_and_set_or_throw<int>( overmap_lake_settings_jo, "lake_size_min",
                                     overmap_lake_settings.lake_size_min, !overlay );
         read_and_set_or_throw<int>( overmap_lake_settings_jo, "lake_depth",
                                     overmap_lake_settings.lake_depth, !overlay );
         if( !overmap_lake_settings_jo.has_array( "shore_extendable_overmap_terrain" ) ) {
             if( !overlay ) {
                 overmap_lake_settings_jo.throw_error( "shore_extendable_overmap_terrain required" );
             }
         } else {
             const std::vector<std::string> from_json =
                 overmap_lake_settings_jo.get_string_array( "shore_extendable_overmap_terrain" );
             overmap_lake_settings.unfinalized_shore_extendable_overmap_terrain.insert(
                 overmap_lake_settings.unfinalized_shore_extendable_overmap_terrain.end(), from_json.begin(),
                 from_json.end() );
         }
         if( !overmap_lake_settings_jo.has_array( "shore_extendable_overmap_terrain_aliases" ) ) {
             if( !overlay ) {
                 overmap_lake_settings_jo.throw_error( "shore_extendable_overmap_terrain_aliases required" );
             }
         } else {
             for( JsonObject alias_entry :
                  overmap_lake_settings_jo.get_array( "shore_extendable_overmap_terrain_aliases" ) ) {
                 shore_extendable_overmap_terrain_alias alias;
                 alias_entry.read( "om_terrain", alias.overmap_terrain );
                 alias_entry.read( "alias", alias.alias );
                 alias.match_type = alias_entry.get_enum_value<ot_match_type>( "om_terrain_match_type",
                                    ot_match_type::contains );
                 overmap_lake_settings.shore_extendable_overmap_terrain_aliases.emplace_back( alias );
             }
         }
     }
 }
References shore_extendable_overmap_terrain_alias::alias, contains, JsonObject::get_array(), JsonObject::get_object(), JsonObject::get_string_array(), JsonObject::has_array(), JsonObject::has_object(), overmap_lake_settings::lake_depth, overmap_lake_settings::lake_size_min, shore_extendable_overmap_terrain_alias::match_type, overmap_lake_settings::noise_threshold_lake, shore_extendable_overmap_terrain_alias::overmap_terrain, overmap_lake_settings::shore_extendable_overmap_terrain_aliases, strict, JsonObject::throw_error(), and overmap_lake_settings::unfinalized_shore_extendable_overmap_terrain.
Referenced by apply_region_overlay(), and load_region_settings().
load_overmap_ocean_settings()
static void load_overmap_ocean_settings (const JsonObject & jo, overmap_ocean_settings & overmap_ocean_settings, const bool strict, const bool overlay) static
Definition at line 410 of file regional_settings.cpp.
 {
     if( !jo.has_object( "overmap_ocean_settings" ) && get_option<bool>( "OVERMAP_PLACE_OCEANS" ) ) {
         if( strict ) {
             jo.throw_error( "OVERMAP_PLACE_OCEANS set to true, but \"overmap_ocean_settings\" not defined in region_settings" );
         }
     } else {
         JsonObject overmap_ocean_settings_jo = jo.get_object( "overmap_ocean_settings" );
         read_and_set_or_throw<double>( overmap_ocean_settings_jo, "noise_threshold_ocean",
                                        overmap_ocean_settings.noise_threshold_ocean, !overlay );
         read_and_set_or_throw<int>( overmap_ocean_settings_jo, "ocean_size_min",
                                     overmap_ocean_settings.ocean_size_min, !overlay );
         read_and_set_or_throw<int>( overmap_ocean_settings_jo, "ocean_depth",
                                     overmap_ocean_settings.ocean_depth, !overlay );
         read_and_set_or_throw<int>( overmap_ocean_settings_jo, "ocean_start_north",
                                     overmap_ocean_settings.ocean_start_north, !overlay );
         read_and_set_or_throw<int>( overmap_ocean_settings_jo, "ocean_start_east",
                                     overmap_ocean_settings.ocean_start_east, !overlay );
         read_and_set_or_throw<int>( overmap_ocean_settings_jo, "ocean_start_west",
                                     overmap_ocean_settings.ocean_start_west, !overlay );
         read_and_set_or_throw<int>( overmap_ocean_settings_jo, "ocean_start_south",
                                     overmap_ocean_settings.ocean_start_south, !overlay );
         read_and_set_or_throw<int>( overmap_ocean_settings_jo, "sandy_beach_width",
                                     overmap_ocean_settings.sandy_beach_width, !overlay );
     }
 }
References JsonObject::get_object(), JsonObject::has_object(), overmap_ocean_settings::noise_threshold_ocean, overmap_ocean_settings::ocean_depth, overmap_ocean_settings::ocean_size_min, overmap_ocean_settings::ocean_start_east, overmap_ocean_settings::ocean_start_north, overmap_ocean_settings::ocean_start_south, overmap_ocean_settings::ocean_start_west, overmap_ocean_settings::sandy_beach_width, strict, and JsonObject::throw_error().
Referenced by apply_region_overlay(), and load_region_settings().
load_overmap_ravine_settings()
static void load_overmap_ravine_settings (const JsonObject & jo, overmap_ravine_settings & overmap_ravine_settings, const bool strict, const bool overlay) static
Definition at line 315 of file regional_settings.cpp.
 {
     if( !jo.has_object( "overmap_ravine_settings" ) ) {
         if( strict ) {
             jo.throw_error( "\"overmap_ravine_settings\": {  } required for default" );
         }
     } else {
         JsonObject overmap_ravine_settings_jo = jo.get_object( "overmap_ravine_settings" );
         read_and_set_or_throw<int>( overmap_ravine_settings_jo, "num_ravines",
                                     overmap_ravine_settings.num_ravines, !overlay );
         read_and_set_or_throw<int>( overmap_ravine_settings_jo, "ravine_range",
                                     overmap_ravine_settings.ravine_range, !overlay );
         read_and_set_or_throw<int>( overmap_ravine_settings_jo, "ravine_width",
                                     overmap_ravine_settings.ravine_width, !overlay );
         read_and_set_or_throw<int>( overmap_ravine_settings_jo, "ravine_depth",
                                     overmap_ravine_settings.ravine_depth, !overlay );
     }
 }
References JsonObject::get_object(), JsonObject::has_object(), overmap_ravine_settings::num_ravines, overmap_ravine_settings::ravine_depth, overmap_ravine_settings::ravine_range, overmap_ravine_settings::ravine_width, strict, and JsonObject::throw_error().
Referenced by apply_region_overlay(), and load_region_settings().
load_region_overlay()
void load_region_overlay (const JsonObject & jo)
Definition at line 659 of file regional_settings.cpp.
 {
     if( jo.has_array( "regions" ) ) {
         JsonArray regions = jo.get_array( "regions" );
         for( const std::string regionid : regions ) {
             if( regionid == "all" ) {
                 if( regions.size() != 1 ) {
                     jo.throw_error( "regions: More than one region is not allowed when \"all\" is used" );
                 }
                 for( auto &itr : region_settings_map ) {
                     apply_region_overlay( jo, itr.second );
                 }
             } else {
                 auto itr = region_settings_map.find( regionid );
                 if( itr == region_settings_map.end() ) {
                     jo.throw_error( "region: " + regionid + " not found in region_settings_map" );
                 } else {
                     apply_region_overlay( jo, itr->second );
                 }
             }
         }
     } else {
         jo.throw_error( "\"regions\" is required and must be an array" );
     }
 }
References apply_region_overlay(), JsonObject::get_array(), JsonObject::has_array(), region_settings_map, JsonArray::size(), and JsonObject::throw_error().
Referenced by DynamicDataLoader::initialize().
load_region_settings()
void load_region_settings (const JsonObject & jo)
Definition at line 492 of file regional_settings.cpp.
 {
     regional_settings new_region;
     if( !jo.read( "id", new_region.id ) ) {
         jo.throw_error( "No 'id' field." );
     }
     bool strict = new_region.id == "default";
     mandatory( jo, false, "default_oter", new_region.default_oter );
     // So the data definition goes from z = OVERMAP_HEIGHT to z = OVERMAP_DEPTH
     std::reverse( new_region.default_oter.begin(), new_region.default_oter.end() );
     if( !jo.read( "river_scale", new_region.river_scale ) && strict ) {
         jo.throw_error( "river_scale required for default" );
     }
     if( jo.has_array( "default_groundcover" ) ) {
         new_region.default_groundcover_str.reset( new weighted_int_list<ter_str_id> );
         for( JsonArray inner : jo.get_array( "default_groundcover" ) ) {
             if( new_region.default_groundcover_str->add( ter_str_id( inner.get_string( 0 ) ),
                     inner.get_int( 1 ) ) == nullptr ) {
                 jo.throw_error( "'default_groundcover' must be a weighted list: an array of pairs [ \"id\", weight ]" );
             }
         }
     } else if( strict ) {
         jo.throw_error( "Weighted list 'default_groundcover' required for 'default'" );
     }
     load_forest_mapgen_settings( jo, new_region.forest_composition, strict, false );
     load_forest_trail_settings( jo, new_region.forest_trail, strict, false );
     if( !jo.has_object( "map_extras" ) ) {
         if( strict ) {
             jo.throw_error( "\"map_extras\": {  } required for default" );
         }
     } else {
         for( const JsonMember zone : jo.get_object( "map_extras" ) ) {
             if( zone.is_comment() ) {
                 continue;
             }
             JsonObject zjo = zone.get_object();
             map_extras extras( 0 );
             if( !zjo.read( "chance", extras.chance ) && strict ) {
                 zjo.throw_error( "chance required for default" );
             }
             if( !zjo.has_object( "extras" ) ) {
                 if( strict ) {
                     zjo.throw_error( "\"extras\": {  } required for default" );
                 }
             } else {
                 for( const JsonMember member : zjo.get_object( "extras" ) ) {
                     if( member.is_comment() ) {
                         continue;
                     }
                     extras.values.add( map_extra_id( member.name() ), member.get_int() );
                 }
             }
             new_region.region_extras[zone.name()] = extras;
         }
     }
     if( !jo.has_object( "city" ) ) {
         if( strict ) {
             jo.throw_error( "\"city\": {  } required for default" );
         }
     } else {
         JsonObject cjo = jo.get_object( "city" );
         if( !cjo.read( "shop_radius", new_region.city_spec.shop_radius ) && strict ) {
             jo.throw_error( "city: shop_radius required for default" );
         }
         if( !cjo.read( "shop_sigma", new_region.city_spec.shop_sigma ) && strict ) {
             jo.throw_error( "city: shop_sigma required for default" );
         }
         if( !cjo.read( "park_radius", new_region.city_spec.park_radius ) && strict ) {
             jo.throw_error( "city: park_radius required for default" );
         }
         if( !cjo.read( "park_sigma", new_region.city_spec.park_sigma ) && strict ) {
             jo.throw_error( "city: park_sigma required for default" );
         }
         const auto load_building_types = [&jo, &cjo, strict]( const std::string & type,
         building_bin & dest ) {
             if( !cjo.has_object( type ) && strict ) {
                 jo.throw_error( "city: \"" + type + "\": {  } required for default" );
             } else {
                 for( const JsonMember member : cjo.get_object( type ) ) {
                     if( member.is_comment() ) {
                         continue;
                     }
                     dest.add( overmap_special_id( member.name() ), member.get_int() );
                 }
             }
         };
         load_building_types( "houses", new_region.city_spec.houses );
         load_building_types( "shops", new_region.city_spec.shops );
         load_building_types( "parks", new_region.city_spec.parks );
     }
     if( !jo.has_object( "weather" ) ) {
         if( strict ) {
             jo.throw_error( "\"weather\": {  } required for default" );
         }
     } else {
         JsonObject wjo = jo.get_object( "weather" );
         new_region.weather = weather_generator::load( wjo );
     }
     load_overmap_feature_flag_settings( jo, new_region.overmap_feature_flag, strict, false );
     load_overmap_forest_settings( jo, new_region.overmap_forest, strict, false );
     load_overmap_lake_settings( jo, new_region.overmap_lake, strict, false );
     load_overmap_ocean_settings( jo, new_region.overmap_ocean, strict, false );
     load_overmap_ravine_settings( jo, new_region.overmap_ravine, strict, false );
     load_overmap_connection_settings( jo, new_region.overmap_connection, strict, false );
     load_region_terrain_and_furniture_settings( jo, new_region.region_terrain_and_furniture, strict,
             false );
     region_settings_map[new_region.id] = new_region;
 }
References regional_settings::city_spec, regional_settings::default_groundcover_str, regional_settings::default_oter, anonymous_namespace{map_extras.cpp}::extras, regional_settings::forest_composition, regional_settings::forest_trail, JsonObject::get_array(), JsonObject::get_object(), JsonObject::has_array(), JsonObject::has_object(), city_settings::houses, regional_settings::id, weather_generator::load(), load_forest_mapgen_settings(), load_forest_trail_settings(), load_overmap_connection_settings(), load_overmap_feature_flag_settings(), load_overmap_forest_settings(), load_overmap_lake_settings(), load_overmap_ocean_settings(), load_overmap_ravine_settings(), load_region_terrain_and_furniture_settings(), mandatory(), member, regional_settings::overmap_connection, regional_settings::overmap_feature_flag, regional_settings::overmap_forest, regional_settings::overmap_lake, regional_settings::overmap_ocean, regional_settings::overmap_ravine, city_settings::park_radius, city_settings::park_sigma, city_settings::parks, JsonObject::read(), regional_settings::region_extras, region_settings_map, regional_settings::region_terrain_and_furniture, regional_settings::river_scale, city_settings::shop_radius, city_settings::shop_sigma, city_settings::shops, strict, JsonObject::throw_error(), and regional_settings::weather.
Referenced by DynamicDataLoader::initialize().
load_region_terrain_and_furniture_settings()
static void load_region_terrain_and_furniture_settings (const JsonObject & jo, region_terrain_and_furniture_settings & region_terrain_and_furniture_settings, const bool strict, const bool overlay) static
Definition at line 439 of file regional_settings.cpp.
 {
     if( !jo.has_object( "region_terrain_and_furniture" ) ) {
         if( strict ) {
             jo.throw_error( "\"region_terrain_and_furniture\": {  } required for default" );
         }
     } else {
         JsonObject region_terrain_and_furniture_settings_jo =
             jo.get_object( "region_terrain_and_furniture" );
         if( !region_terrain_and_furniture_settings_jo.has_object( "terrain" ) ) {
             if( !overlay ) {
                 region_terrain_and_furniture_settings_jo.throw_error( "terrain required" );
             }
         } else {
             for( const JsonMember region : region_terrain_and_furniture_settings_jo.get_object( "terrain" ) ) {
                 if( region.is_comment() ) {
                     continue;
                 }
                 for( const JsonMember terrain : region.get_object() ) {
                     if( terrain.is_comment() ) {
                         continue;
                     }
                     region_terrain_and_furniture_settings.unfinalized_terrain[region.name()][terrain.name()] =
                         terrain.get_int();
                 }
             }
         }
         if( !region_terrain_and_furniture_settings_jo.has_object( "furniture" ) ) {
             if( !overlay ) {
                 region_terrain_and_furniture_settings_jo.throw_error( "furniture required" );
             }
         } else {
             for( const JsonMember template_furniture :
                  region_terrain_and_furniture_settings_jo.get_object( "furniture" ) ) {
                 if( template_furniture.is_comment() ) {
                     continue;
                 }
                 for( const JsonMember furniture : template_furniture.get_object() ) {
                     if( furniture.is_comment() ) {
                         continue;
                     }
                     region_terrain_and_furniture_settings.unfinalized_furniture[template_furniture.name()][furniture.name()]
                         = furniture.get_int();
                 }
             }
         }
     }
 }
References furniture, JsonObject::get_object(), JsonObject::has_object(), strict, terrain, JsonObject::throw_error(), region_terrain_and_furniture_settings::unfinalized_furniture, and region_terrain_and_furniture_settings::unfinalized_terrain.
Referenced by apply_region_overlay(), and load_region_settings().
read_and_set_or_throw()
template<typename T > void read_and_set_or_throw (const JsonObject & jo, const std::string & member, T & target, bool required)
Definition at line 25 of file regional_settings.cpp.
 {
     T tmp;
     if( !jo.read( member, tmp ) ) {
         if( required ) {
             jo.throw_error( string_format( "%s required", member ) );
         }
     } else {
         target = tmp;
     }
 }
References member, JsonObject::read(), string_format(), and JsonObject::throw_error().
Referenced by load_forest_biome().
reset_region_settings()
void reset_region_settings ()
Definition at line 650 of file regional_settings.cpp.
 {
     region_settings_map.clear();
 }
References region_settings_map.
Referenced by DynamicDataLoader::unload_data().