Cataclysm DDA: src/relic.cpp File Reference
relic.cpp File Reference
#include "relic.h"
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <set>
#include <string>
#include "calendar.h"
#include "character.h"
#include "creature.h"
#include "debug.h"
#include "enums.h"
#include "generic_factory.h"
#include "json.h"
#include "magic.h"
#include "magic_enchantment.h"
#include "map.h"
#include "rng.h"
#include "string_id.h"
#include "translations.h"
#include "type_id.h"
#include "weather.h"
#include "weather_type.h"
Namespaces
io
anonymous_namespace{relic.cpp}
Functions
static bool item_can_not_load_ammo (const item &gun)
template<>
std::string io::enum_to_string< relic_procgen_data::type > (relic_procgen_data::type data)
template<>
std::string io::enum_to_string< relic_recharge_type > (relic_recharge_type type)
template<>
std::string io::enum_to_string< relic_recharge_has > (relic_recharge_has has)
static bool can_recharge_solar (const item &it, Character *carrier, const tripoint &pos)
static bool can_recharge_lunar (const item &it, Character *carrier, const tripoint &pos)
bool operator== (const relic &source_relic, const relic &target_relic)
Variables
generic_factory< relic_procgen_data > anonymous_namespace{relic.cpp}::relic_procgen_data_factory ("relic_procgen_data")
Function Documentation
can_recharge_lunar()
static bool can_recharge_lunar (const item & it, Character * carrier, const tripoint & pos) static
Definition at line 463 of file relic.cpp.
 {
     return get_map().is_outside( pos ) && is_night( calendar::turn ) &&
            ( carrier == nullptr ||
              carrier->is_worn( it ) || carrier->is_wielding( it ) );
 }
References get_map(), is_night(), map::is_outside(), Character::is_wielding(), Character::is_worn(), math_opers::pos(), and calendar::turn.
Referenced by relic::try_recharge().
can_recharge_solar()
static bool can_recharge_solar (const item & it, Character * carrier, const tripoint & pos) static
Definition at line 454 of file relic.cpp.
 {
     return get_map().is_outside( pos ) && is_day( calendar::turn ) &&
            ( carrier == nullptr ||
              carrier->is_worn( it ) || carrier->is_wielding( it ) );
 }
References get_map(), is_day(), map::is_outside(), Character::is_wielding(), Character::is_worn(), math_opers::pos(), and calendar::turn.
Referenced by relic::try_recharge().
item_can_not_load_ammo()
static bool item_can_not_load_ammo (const item & gun) static
Definition at line 30 of file relic.cpp.
 {
     return ( gun.is_magazine() && gun.remaining_ammo_capacity() == 0 ) ||
            ( !gun.is_magazine() && gun.magazine_current() == nullptr ) ||
            ( gun.magazine_current() != nullptr && gun.magazine_current()->remaining_ammo_capacity() == 0 );
 }
References gun.
Referenced by relic_charge_info::accumulate_charge(), and relic::try_recharge().
operator==()
bool operator== (const relic & source_relic, const relic & target_relic)
Definition at line 813 of file relic.cpp.
 {
     bool is_the_same = true;
     is_the_same &= ( source_relic.charges() == target_relic.charges() );
     is_the_same &= ( source_relic.charges_per_use() == target_relic.charges_per_use() );
     is_the_same &= ( source_relic.has_activation() == target_relic.has_activation() );
     is_the_same &= ( source_relic.has_recharge() == target_relic.has_recharge() );
     is_the_same &= ( source_relic.max_charges() == target_relic.max_charges() );
     is_the_same &= ( source_relic.name() == target_relic.name() );
     is_the_same &= ( source_relic.get_proc_enchantments().size() ==
                      target_relic.get_proc_enchantments().size() );
     is_the_same &= ( source_relic.get_defined_enchantments().size() ==
                      target_relic.get_defined_enchantments().size() );
     if( is_the_same ) {
         for( std::size_t i = 0; i < source_relic.get_proc_enchantments().size(); i++ ) {
             is_the_same &= source_relic.get_proc_enchantments()[i] == target_relic.get_proc_enchantments()[i];
         }
     }
     return is_the_same;
 }