Cataclysm DDA: src/requirements.cpp File Reference
requirements.cpp File Reference
#include "requirements.h"
#include <algorithm>
#include <climits>
#include <cstdlib>
#include <iterator>
#include <limits>
#include <list>
#include <memory>
#include <set>
#include <stack>
#include <unordered_map>
#include <unordered_set>
#include "cata_assert.h"
#include "cata_utility.h"
#include "character.h"
#include "color.h"
#include "debug.h"
#include "debug_menu.h"
#include "enum_traits.h"
#include "generic_factory.h"
#include "inventory.h"
#include "item.h"
#include "item_factory.h"
#include "itype.h"
#include "json.h"
#include "localized_comparator.h"
#include "make_static.h"
#include "output.h"
#include "point.h"
#include "string_formatter.h"
#include "translations.h"
#include "value_ptr.h"
#include "visitable.h"
Namespaces
anonymous_namespace{requirements.cpp}
Functions
static bool a_satisfies_b (const quality_requirement &a, const quality_requirement &b)
static bool a_satisfies_b (const std::vector< quality_requirement > &a, const std::vector< quality_requirement > &b)
template<typename T >
void inline_requirements (std::vector< std::vector< T >> &list, const std::function< const std::vector< std::vector< T >> &(const requirement_data &)> &getter)
template<typename T >
static bool apply_blacklist (std::vector< std::vector< T >> &vec, const itype_id &id)
template<typename T >
static void apply_replacements (std::vector< std::vector< T >> &vec, const std::unordered_map< itype_id, itype_id > &replacements)
template<typename T , typename Accum >
static std::vector< std::vector< T > > consolidate (std::vector< std::vector< T >> old_vec, const Accum &accum)
template<typename T >
static bool sorted_equal (std::vector< std::vector< T >> lhs, std::vector< std::vector< T >> rhs)
template<typename T >
static void dump_req_vec (const std::vector< std::vector< T >> &vec, JsonOut &jsout)
static void expand_item_in_reqs (const item_comp &leftover, requirement_data::alter_item_comp_vector req_prefix, const requirement_data::alter_item_comp_vector &to_expand, size_t orig_index, size_t index, std::vector< requirement_data::alter_item_comp_vector > &result)
Helper function for deduped_requirement_data constructor below.
Variables
static const itype_id itype_UPS ("UPS")
static const itype_id itype_char_forge ("char_forge")
static const itype_id itype_crucible ("crucible")
static const itype_id itype_fire ("fire")
static const itype_id itype_forge ("forge")
static const itype_id itype_oxy_torch ("oxy_torch")
static const itype_id itype_press ("press")
static const itype_id itype_welder ("welder")
static const itype_id itype_welder_crude ("welder_crude")
static const quality_id qual_CUT ("CUT")
static const quality_id qual_GLARE ("GLARE")
static const quality_id qual_KNIT ("KNIT")
static const quality_id qual_PULL ("PULL")
static const quality_id qual_SAW_M_FINE ("SAW_M_FINE")
static const quality_id qual_SEW ("SEW")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
static std::map< requirement_id, requirement_data > requirements_all
generic_factory< quality > anonymous_namespace{requirements.cpp}::quality_factory ("tool quality")
Function Documentation
a_satisfies_b() [1/2]
static bool a_satisfies_b (const quality_requirement & a, const quality_requirement & b) static
Definition at line 336 of file requirements.cpp.
 {
     return a.type == b.type && a.level >= b.level
            && a.requirement == b.requirement && a.count == b.count;
 }
References a, and b.
Referenced by a_satisfies_b(), and requirement_data::operator+().
a_satisfies_b() [2/2]
static bool a_satisfies_b (const std::vector< quality_requirement > & a, const std::vector< quality_requirement > & b) static
Definition at line 342 of file requirements.cpp.
 {
     // every b_x is satisfied by some a_x
     for( const quality_requirement &b_x : b ) {
         bool satisfied = false;
         for( const quality_requirement &a_x : a ) {
             if( a_satisfies_b( a_x, b_x ) ) {
                 satisfied = true;
                 break;
             }
         }
         if( !satisfied ) {
             return false;
         }
     }
     return true;
 }
References a, a_satisfies_b(), and b.
apply_blacklist()
template<typename T > static bool apply_blacklist (std::vector< std::vector< T >> & vec, const itype_id & id) static
Definition at line 1092 of file requirements.cpp.
 {
     // remove all instances of @id type from each of the options
     for( auto &opts : vec ) {
         opts.erase( std::remove_if( opts.begin(), opts.end(), [&id]( const T & e ) {
             return e.type == id;
         } ), opts.end() );
     }
     // did we remove the last instance of an option group?
     const bool blacklisted = std::any_of( vec.begin(), vec.end(), []( const std::vector<T> &e ) {
         return e.empty();
     } );
     // if an option group is left empty then it can be removed
     vec.erase( std::remove_if( vec.begin(), vec.end(), []( const std::vector<T> &e ) {
         return e.empty();
     } ), vec.end() );
     return blacklisted;
 }
Referenced by requirement_data::blacklist_item().
apply_replacements()
template<typename T > static void apply_replacements (std::vector< std::vector< T >> & vec, const std::unordered_map< itype_id, itype_id > & replacements) static
Definition at line 1121 of file requirements.cpp.
 {
     for( std::vector<T> &opts : vec ) {
         for( typename std::vector<T>::iterator iiter = opts.begin(); iiter != opts.end(); ) {
             auto riter = replacements.find( iiter->type );
             if( riter != replacements.end() ) {
                 itype_id to_id = riter->second;
                 // Replace an item or outright remove it if its replacement
                 // is already present in the vector, to prevent duplicates
                 bool has_duplicates = std::count_if( opts.cbegin(), opts.cend(), [&to_id]( const T & item ) {
                     return item.type == to_id;
                 } ) != 0;
                 if( has_duplicates ) {
                     iiter = opts.erase( iiter );
                     continue;
                 } else {
                     iiter->type = to_id;
                 }
             }
             ++iiter;
         }
     }
 }
Referenced by requirement_data::replace_items().
consolidate()
template<typename T , typename Accum > static std::vector<std::vector<T> > consolidate (std::vector< std::vector< T >> old_vec, const Accum & accum) static
Definition at line 1335 of file requirements.cpp.
 {
     const auto type_lt = []( const T & lhs, const T & rhs ) -> bool {
         //TODO change to use localized sorting
         return std::forward_as_tuple( lhs.type.str(), lhs.requirement )
         < std::forward_as_tuple( rhs.type.str(), rhs.requirement );
     };
     // in order to simplify blueprint requirements, we merge a longer requirement
     // list into a shorter requirement list whose types are a subsequence of the
     // longer list's types. However, this operation is not symmetric and depends
     // on the order of the requirement lists. Thus we sort the lists first, to
     // ensure consistent results when the order of construction requirements changes.
     for( std::vector<T> &old_inner : old_vec ) {
         std::sort( old_inner.begin(), old_inner.end(), type_lt );
     }
     std::sort( old_vec.begin(), old_vec.end(),
     [&type_lt]( const std::vector<T> &lhs, const std::vector<T> &rhs ) -> bool {
         return std::lexicographical_compare( lhs.begin(), lhs.end(), rhs.begin(), rhs.end(),
                                              type_lt );
     } );
     std::vector<std::vector<T>> new_vec;
     for( std::vector<T> &old_inner : old_vec ) {
         bool match = false;
         for( std::vector<T> &new_inner : new_vec ) {
             // in order to simplify blueprint requirements, we merge a longer
             // requirement list into a shorter requirement list whose types are
             // a subsequence of the longer list's types.
             //
             // note this actually may make a requirement stricter.
             // for example, if the item requirement was
             //   [ [ [ "a", 1 ], [ "b", 1 ], [ "c", 1 ] ],
             //     [ [ "a", 1 ], [ "b", 1 ] ] ]
             // then you could satisfy it by having one "a" and one "b", one
             // "c" and one "a", two "a", or two "b", etc.
             //
             // but after consolidation, it becomes
             //   [ [ [ "a", 2 ], [ "b", 2 ] ] ]
             // then you can only satisfy it by having either 2 "a" or 2 "b"
             if( std::includes( new_inner.begin(), new_inner.end(),
                                old_inner.begin(), old_inner.end(),
                                type_lt ) ) {
                 // old_inner is a subsequence of new_inner
                 match = true;
                 std::swap( old_inner, new_inner );
             } else if( std::includes( old_inner.begin(), old_inner.end(),
                                       new_inner.begin(), new_inner.end(),
                                       type_lt ) ) {
                 // new_inner is a subsequence of old_inner
                 match = true;
             }
             if( match ) {
                 for( auto it1 = new_inner.begin(), it2 = old_inner.begin();
                      it1 < new_inner.end(); ++it2 ) {
                     if( !type_lt( *it2, *it1 ) ) {
                         // which means *it2 and *it1 have the same type, since
                         // we know new_inner is a subsequence of old_inner
                         *it1 = accum( *it1, *it2 );
                         ++it1;
                     }
                 }
                 break;
             }
         }
         if( !match ) {
             new_vec.emplace_back( old_inner );
         }
     }
     return new_vec;
 }
References cata::swap().
dump_req_vec()
template<typename T > static void dump_req_vec (const std::vector< std::vector< T >> & vec, JsonOut & jsout) static
Definition at line 1462 of file requirements.cpp.
 {
     jsout.start_array( /*wrap=*/!vec.empty() );
     for( const auto &inner : vec ) {
         jsout.start_array();
         for( const auto &val : inner ) {
             val.dump( jsout );
         }
         jsout.end_array();
     }
     jsout.end_array();
 }
References JsonOut::end_array(), and JsonOut::start_array().
Referenced by requirement_data::dump().
expand_item_in_reqs()
static void expand_item_in_reqs (const item_comp & leftover, requirement_data::alter_item_comp_vector req_prefix, const requirement_data::alter_item_comp_vector & to_expand, size_t orig_index, size_t index, std::vector< requirement_data::alter_item_comp_vector > & result) static
Helper function for deduped_requirement_data constructor below.
The goal of this function is to consolidate a particular item_comp that would otherwise be duplicated between two requirements.
It operates recursively (increasing index with the depth of recursion), searching for another item_comp to merge leftover with. For each compatible item_comp found it performs that merger and writes out a suitably updated form of the overall requirements to result.
If it chooses not to merge with any particular item_comp, then it deletes that item_comp from the options, to avoid the duplication.
Lastly, it also outputs a version of the requirements where leftover remains where it was, and all other compatible item_comp entries have been deleted.
Parameters
leftover The item_comp needing to be dealt with.
req_prefix The requirements considered so far; more will be appended to this.
to_expand The original requirements we are working through to look for a duplicate.
orig_index The index into the alter_item_comp_vector where leftover was originally to be found. If it isn't merged with another item, then it will be re-inserted at this position.
index The position within to_expand where we will next look for duplicates of leftover to merge with.
result The finished requirements should be appended to this.
Definition at line 1528 of file requirements.cpp.
 {
     cata_assert( req_prefix.size() >= orig_index );
     cata_assert( orig_index < index );
     if( index == to_expand.size() ) {
         // We reached the end without using the leftovers.  So need to add them
         // as their own requirement, separate from everything else.
         req_prefix.insert( req_prefix.begin() + orig_index, { leftover } );
         result.push_back( req_prefix );
         return;
     }
     std::vector<item_comp> this_requirement = to_expand[index];
     auto duplicate = std::find_if( this_requirement.begin(), this_requirement.end(),
     [&]( const item_comp & c ) {
         return c.type == leftover.type;
     } );
     if( duplicate == this_requirement.end() ) {
         // No match in this one; proceed to next
         req_prefix.push_back( this_requirement );
         expand_item_in_reqs( leftover, req_prefix, to_expand, orig_index, index + 1, result );
         return;
     }
     // First option: amalgamate the leftovers into this requirement, which
     // forces us to pick that specific option:
     requirement_data::alter_item_comp_vector req = req_prefix;
     req.push_back( { item_comp( leftover.type, leftover.count + duplicate->count ) } );
     req.insert( req.end(), to_expand.begin() + index + 1, to_expand.end() );
     result.push_back( req );
     // Second option: use a separate option for this requirement, which means
     // we need to recurse further to find something into which to amalgamate
     // the original requirement
     this_requirement.erase( duplicate );
     if( !this_requirement.empty() ) {
         req_prefix.push_back( this_requirement );
         expand_item_in_reqs( leftover, req_prefix, to_expand, orig_index, index + 1, result );
     }
 }
References c, cata_assert, component::count, and component::type.
Referenced by deduped_requirement_data::deduped_requirement_data().
inline_requirements()
template<typename T > void inline_requirements (std::vector< std::vector< T >> & list, const std::function< const std::vector< std::vector< T >> &(const requirement_data &)> & getter)
Definition at line 627 of file requirements.cpp.
 {
     // add a single component to the vector. If component already exists, chooses min count
     const auto add_component = []( const T & comp, std::vector<T> &accum ) {
         auto iter = std::find_if( accum.begin(), accum.end(), [&]( const T & req ) {
             return !req.requirement && req.type == comp.type;
         } );
         if( iter == accum.end() ) {
             accum.push_back( comp ); // component doesn't exist yet, adding it
         } else {
             // this is the list of alternatives (a OR b OR c), so if there are two identical components
             // with the different counts as an alternatives, the one with the lowest count is selected
             iter->count = std::min( comp.count, iter->count );
         }
     };
     // if `comp` is a component, adds it to the `accum`
     // if it's a requirement, recursively expands it into simple components and adds them to the vector
     const auto inline_one = [&]( const T & comp, std::vector<T> &accum ) {
         std::set<requirement_id> already_nested;
         std::list<requirement_id> stack;
         std::function<void( const T &comp )> rec;
         rec = [&]( const T & comp ) {
             // add simple component to the vector
             if( !comp.requirement ) {
                 add_component( comp, accum );
                 return;
             }
             // otherwise expand component as requirement
             const requirement_id r( comp.type.str() );
             if( !r.is_valid() ) {
                 debugmsg( "Tried to inline unknown requirement %s", r.c_str() );
                 return;
             }
             // stack just holds the current path of inlining for debug purposes
             stack.push_back( r );
             if( already_nested.count( r ) ) {
                 // print debug msg and skip just this one requirement
                 debugmsg( "Tried to inline requirement %s which forms a cycle: %s",
                 r.c_str(),  debug_menu::iterable_to_string( stack, " -> ", []( const requirement_id & r ) {
                     return r.str();
                 } ) );
                 stack.pop_back();
                 return;
             }
             already_nested.insert( r );
             const requirement_data &req = r.obj();
             const requirement_data multiplied = req * comp.count;
             const std::vector<std::vector<T>> &to_inline = getter( multiplied );
             if( !to_inline.empty() ) {
                 const std::vector<T> &nested = to_inline.front();
                 for( const T &nested_comp : nested ) {
                     rec( nested_comp );
                 }
             }
             already_nested.erase( r );
             stack.pop_back();
         };
         rec( comp );
     };
     for( std::vector<T> &vec : list ) {
         const std::vector<T> vec_copy = vec;
         vec.clear();
         for( const T &comp  : vec_copy ) {
             inline_one( comp, vec );
         }
     }
 }
References string_id< T >::c_str(), debugmsg, string_id< T >::is_valid(), debug_menu::iterable_to_string(), min(), and string_id< T >::obj().
sorted_equal()
template<typename T > static bool sorted_equal (std::vector< std::vector< T >> lhs, std::vector< std::vector< T >> rhs) static
Definition at line 1439 of file requirements.cpp.
 {
     if( lhs.size() != rhs.size() ) {
         return false;
     }
     for( auto &inner : lhs ) {
         std::sort( inner.begin(), inner.end() );
     }
     for( auto &inner : rhs ) {
         std::sort( inner.begin(), inner.end() );
     }
     std::sort( lhs.begin(), lhs.end() );
     std::sort( rhs.begin(), rhs.end() );
     return lhs == rhs;
 }
Referenced by requirement_data::has_same_requirements_as().
Variable Documentation
itype_char_forge
const itype_id itype_char_forge("char_forge") ("char_forge") static
Referenced by requirement_data::disassembly_requirements().
itype_crucible
const itype_id itype_crucible("crucible") ("crucible") static
Referenced by requirement_data::disassembly_requirements().
itype_fire
const itype_id itype_fire("fire") ("fire") static
Referenced by requirement_data::disassembly_requirements().
itype_forge
const itype_id itype_forge("forge") ("forge") static
Referenced by requirement_data::disassembly_requirements().
itype_oxy_torch
const itype_id itype_oxy_torch("oxy_torch") ("oxy_torch") static
Referenced by requirement_data::disassembly_requirements().
itype_press
const itype_id itype_press("press") ("press") static
Referenced by requirement_data::disassembly_requirements().
itype_UPS
const itype_id itype_UPS("UPS") ("UPS") static
Referenced by requirement_data::has_comps().
itype_welder
const itype_id itype_welder("welder") ("welder") static
Referenced by requirement_data::disassembly_requirements().
itype_welder_crude
const itype_id itype_welder_crude("welder_crude") ("welder_crude") static
Referenced by requirement_data::disassembly_requirements().
qual_CUT
const quality_id qual_CUT("CUT") ("CUT") static
Referenced by requirement_data::disassembly_requirements().
qual_GLARE
const quality_id qual_GLARE("GLARE") ("GLARE") static
Referenced by requirement_data::disassembly_requirements().
qual_KNIT
const quality_id qual_KNIT("KNIT") ("KNIT") static
Referenced by requirement_data::disassembly_requirements().
qual_PULL
const quality_id qual_PULL("PULL") ("PULL") static
Referenced by requirement_data::disassembly_requirements().
qual_SAW_M_FINE
const quality_id qual_SAW_M_FINE("SAW_M_FINE") ("SAW_M_FINE") static
Referenced by requirement_data::disassembly_requirements().
qual_SEW
const quality_id qual_SEW("SEW") ("SEW") static
Referenced by requirement_data::disassembly_requirements().
requirements_all
std::map<requirement_id, requirement_data> requirements_all static
Definition at line 56 of file requirements.cpp.
Referenced by requirement_data::all(), requirement_data::get_all(), requirement_data::reset(), and requirement_data::save_requirement().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by requirement_data::can_make_with_inventory(), quality_requirement::get_color(), tool_comp::has(), item_comp::has(), and quality_requirement::has().