Cataclysm DDA: src/rng.cpp File Reference
rng.cpp File Reference
#include "rng.h"
#include <algorithm>
#include <chrono>
#include <cmath>
#include "calendar.h"
#include "cata_utility.h"
#include "units.h"
Functions
unsigned int rng_bits ()
int rng (int lo, int hi)
double rng_float (double lo, double hi)
units::angle random_direction ()
float normal_roll_chance (float center, float stddev, float difficulty)
double normal_roll (double mean, double stddev)
double exponential_roll (double lambda)
double chi_squared_roll (double trial_num)
double rng_exponential (double min, double mean)
bool one_in (int chance)
bool one_turn_in (const time_duration &duration)
bool x_in_y (double x, double y)
int dice (int number, int sides)
int roll_remainder (double value)
int djb2_hash (const unsigned char *input)
std::vector< int > rng_sequence (size_t count, int lo, int hi, int seed)
double rng_normal (double lo, double hi)
cata_default_random_engine::result_type rng_get_first_seed ()
cata_default_random_engine & rng_get_engine ()
void rng_set_engine_seed (unsigned int seed)
std::string random_string (size_t length)
Function Documentation
chi_squared_roll()
double chi_squared_roll (double trial_num)
Definition at line 91 of file rng.cpp.
 {
     static std::chi_squared_distribution<double> rng_chi_squared_dist;
     return rng_chi_squared_dist( rng_get_engine(),
                                  std::chi_squared_distribution<>::param_type( trial_num ) );
 }
References rng_get_engine().
Referenced by npc::randomize().
dice()
int dice (int number, int sides)
Definition at line 123 of file rng.cpp.
 {
     int ret = 0;
     for( int i = 0; i < number; i++ ) {
         ret += rng( 1, sides );
     }
     return ret;
 }
References cata::hash64_detail::ret, and rng().
Referenced by Creature::accuracy_projectile_attack(), Creature::add_env_effect(), amphetamine_effect(), Character::avoid_trap(), monster::avoid_trap(), mattack::bio_op_disarm(), npc::bravery_check(), melee_actor::call(), Character::complete_disassemble(), crack_coke_add(), salvage_actor::cut_up(), mattack::dermatik(), distribution::dice_roll(), avatar::disarm(), field_entry::do_decay(), map::draw_lab(), eff_fun_redcells_anemia(), eff_fun_sleep(), explosion_handler::emp_blast(), mattack::evolve_kill_strike(), lockpick_activity_actor::finish(), activity_handlers::fish_do_turn(), game::grabbed_veh_move(), computer_session::hack_attempt(), hackveh(), prying_activity_actor::handle_prying(), Character::hardcoded_effects(), vehicle::init_state(), monster::melee_attack(), monster::monster(), MapExtras::mx_helicopter(), Character::on_hit(), opiate_effect(), vehicle::possibly_recover_from_skid(), sounds::process_sound_markers(), npc::randomize(), vehicle::smash(), monster::stability_roll(), avatar::steal(), mattack::taze(), sew_advanced_actor::use(), and suffer::without_sleep().
djb2_hash()
int djb2_hash (const unsigned char * input)
Definition at line 149 of file rng.cpp.
 {
     unsigned int hash = 5381;
     unsigned char c = *input++;
     while( c != '\0' ) {
         hash = ( ( hash << 5 ) + hash ) + c; /* hash * 33 + c */
         c = *input++;
     }
     return hash;
 }
References c.
Referenced by translation::legacy_hash(), and anonymous_namespace{main.cpp}::parse_commandline().
exponential_roll()
double exponential_roll (double lambda)
Definition at line 84 of file rng.cpp.
 {
     static std::exponential_distribution<double> rng_exponential_dist;
     return rng_exponential_dist( rng_get_engine(),
                                  std::exponential_distribution<>::param_type( lambda ) );
 }
References rng_get_engine().
Referenced by rng_exponential().
normal_roll()
double normal_roll (double mean, double stddev)
Definition at line 78 of file rng.cpp.
 {
     static std::normal_distribution<double> rng_normal_dist;
     return rng_normal_dist( rng_get_engine(), std::normal_distribution<>::param_type( mean, stddev ) );
 }
References rng_get_engine().
Referenced by Character::crafting_failure_roll(), Character::crafting_success_roll(), trap::detect_trap(), trap::examine(), lockpick_activity_actor::finish(), chop_planks_activity_actor::finish(), hack_attempt(), monster::hear_sound(), vehicle::init_state(), mapgen_forest(), melee::melee_hit_range(), overmap::pick_random_building_to_place(), npc::randomize(), Character::randomize_height(), and rng_normal().
normal_roll_chance()
float normal_roll_chance (float center, float stddev, float difficulty)
Definition at line 48 of file rng.cpp.
 {
     cata_assert( stddev >= 0.f );
     // We're going to be using them a lot, so let's name our variables.
     // M = the given "center" of the curve
     // S = the given standard deviation of the curve
     // A = the difficulty
     // So, the equation of the normal curve is...
     // y = (1.f/(S*std::sqrt(2 * M_PI))) * exp(-(std::pow(x - M, 2))/(2 * std::pow(S, 2)))
     // Thanks to wolfram alpha, we know the integral of that from A to B to be
     // 0.5 * (erf((M-A)/(std::sqrt(2) * S)) - erf((M-B)/(std::sqrt(2) * S)))
     // And since we know B to be infinity, we can simplify that to
     // 0.5 * (erfc((A-m)/(std::sqrt(2)* S))+sgn(S)-1) (as long as S != 0)
     // Wait a second, what are erf, erfc and sgn?
     // Oh, those are the error function, complementary error function, and sign function
     // Luckily, erf() is provided to us in math.h, and erfc is just 1 - erf
     // Sign is pretty obvious x > 0 ? x == 0 ? 0 : 1 : -1;
     // Since we know S will always be > 0, that term vanishes.
     // With no standard deviation, we will always return center
     if( stddev == 0.f ) {
         return ( center > difficulty ) ? 1.f : 0.f;
     }
     float numerator = difficulty - center;
     float denominator = std::sqrt( 2 ) * stddev;
     float compl_erf = 1.f - std::erf( numerator / denominator );
     return 0.5 * compl_erf;
 }
References cata_assert, center, and sqrt().
Referenced by Creature::dodge_check(), Character::item_destruction_chance(), and Character::recipe_success_chance().
one_in()
bool one_in (int chance)
Definition at line 108 of file rng.cpp.
 {
     return chance <= 1 || rng( 0, chance - 1 ) == 0;
 }
References rng().
Referenced by mattack::acid(), mdefense::acidsplash(), npc::act_on_danger_assessment(), vehicle::act_on_map(), computer_session::action_miss_launch(), computer_session::action_radio_archive(), enchant_cache::activate_passive(), timed_event::actualize(), scrollingcombattext::add(), map::add_corpse(), Character::add_msg_player_or_say(), item::add_rain_to_container(), map::add_splash(), npc::address_needs(), npc::address_player(), vehicle::alarm(), alcohol_diazepam_add(), npc::alt_attack(), amphetamine_effect(), iuse::antibiotic(), temperature_effect::apply(), jmapgen_liquid_item::apply(), jmapgen_setmap::apply(), apply_ammo_effects(), projectile::apply_effects_damage(), npc::assess_danger(), Creature::attack_air(), iexamine::autodoc(), monster::bash_at(), trapfunc::beartrap(), mattack::bio_op_impale(), mattack::bio_op_takedown(), iuse::blood_draw(), trapfunc::board(), body_part_hit_by_plant(), overmap::build_city_street(), overmap::build_lab(), overmap::build_slimepit(), VehicleSpawnFunction::builtin_parkinglot(), Character::burn_move_stamina(), MapExtras::burned_ground_parser(), butchery_drops_harvest(), trapfunc::caltrops(), iuse::camera(), iuse::capture_monster_act(), talk_function::caravan_return(), talk_function::carpenter_return(), enchant_cache::cast_enchantment_spell(), monster::check_mech_powered(), Character::check_needs_extremes(), mattack::chickenbot(), clay_or_sand(), iuse::coin_flip(), map::collapse_at(), Character::complete_disassemble(), overmap::connect_closest_points(), Character::consume_effects(), mattack::copbot(), Character::cough(), crack_coke_add(), Character::craft_skill_gain(), map::create_anomaly(), spell::create_field(), Single_item_creator::create_single_without_container(), game::create_starting_npcs(), map::creature_in_field(), trapfunc::crossbow(), Character::crush_frozen_liquid(), Character::customize_appearance(), item::damage_armor_durability(), MapExtras::dead_vegetation_parser(), Character::deal_damage(), Creature::deal_melee_hit(), monster::deal_projectile_attack(), MapExtras::debug_spawn_test(), describe_sound(), monster::die(), monster::die_if_drowning(), iuse::dive_tank(), vehicle::do_engine_damage(), game::do_regular_action(), Character::do_skill_rust(), player_activity::do_turn(), read_activity_actor::do_turn(), try_sleep_activity_actor::do_turn(), workout_activity_actor::do_turn(), construct::do_turn_exhume(), iuse::dog_whistle(), mattack::dogthing(), construct::done_dig_grave(), construct::done_extract_maybe_revert_to_dirt(), mattack::doot(), overmap_ui::draw_ascii(), map::draw_lab(), map::draw_slimepit(), map::drop_items(), eat(), mattack::eat_crop(), eff_fun_antifungal(), eff_fun_bleed(), eff_fun_datura(), eff_fun_fake_common_cold(), eff_fun_fake_flu(), eff_fun_fungus(), eff_fun_hallu(), eff_fun_hot(), eff_fun_hypovolemia(), eff_fun_rat(), eff_fun_redcells_anemia(), eff_fun_sleep(), eff_fun_spores(), eff_fun_teleglow(), iuse::ehandcuffs_tick(), explosion_handler::emp_blast(), Character::evaluate_techniques(), vehicle::explode_fuel(), iuse::extinguisher(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), conditional_fun::anonymous_namespace{condition.cpp}::f_one_in_chance(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), Character::fall_asleep(), field_processor_fd_acid_vent(), field_processor_fd_electricity(), field_processor_fd_fungal_haze(), field_processor_fd_fungicidal_gas(), field_processor_fd_shock_vent(), field_processor_monster_spawn(), field_processor_upgrade_intensity(), fill_funnels(), oxytorch_activity_actor::finish(), disable_activity_actor::finish(), forage_activity_actor::finish(), mop_activity_actor::finish(), iuse::fish_trap_tick(), explosion_handler::flashbang(), mattack::flesh_golem(), mattack::flesh_tendril(), iexamine::flower_cactus(), iexamine::flower_poppy(), talk_function::forage_return(), Character::forced_dismount(), mattack::formblob(), mattack::frag(), suffer::from_artifact_resonance(), suffer::from_asthma(), suffer::from_chemimbalance(), suffer::from_exertion(), suffer::from_nyctophobia(), suffer::from_other_mutations(), suffer::from_radiation(), suffer::from_stimulants(), fungal_effects::fungalize(), iuse::fungicide(), mattack::fungus(), mattack::fungus_bristle(), mattack::fungus_inject(), iexamine::gaspump(), basecamp::gathering_return(), map::generate(), overmap::generate_sub(), get_music_description(), Character::get_sick(), weather_generator::get_weather(), trapfunc::glow(), trapfunc::goo(), npc::good_escape_direction(), game::grabbed_furn_move(), game::grabbed_furn_move_time(), game::grabbed_veh_move(), grass_or_dirt(), mattack::growplants(), computer_session::hack_attempt(), Character::handle_gun_damage(), Character::handle_gun_overheat(), Character::handle_melee_wear(), Character::handle_skill_warning(), Character::hardcoded_effects(), iexamine::harvest_plant(), map::hit_with_acid(), talk_function::hospital_raid_return(), mattack::howl(), iuse::inhaler(), vehicle::init_state(), game::knockback(), talk_function::labor_return(), mattack::leech_spawner(), Creature::longpull(), talk_function::loot_building(), mattack::lunge(), iuse::mace(), item::make_corpse(), make_gun_projectile(), map::make_rubble(), mapgen_forest(), mapgen_river_curved(), mapgen_river_curved_not(), mapgen_river_straight(), fungal_effects::marlossify(), monster::melee_attack(), Character::melee_attack_abstract(), Item_modifier::modify(), Character::modify_morale(), anonymous_namespace{messages.cpp}::messages_impl::modify_msg_with_exclamations(), iuse::molotov_lit(), map::monster_in_field(), iuse::mop(), talk_function::morale_chat_activity(), monster::move(), npc::move_away_from(), overmap::move_hordes(), overmap::move_nemesis(), monster::move_to(), npc::move_to(), map::move_vehicle(), npc::mug_player(), iuse::multicooker(), multicooker_hallu(), Character::mutate(), MapExtras::mx_casings(), MapExtras::mx_corpses(), MapExtras::mx_helicopter(), MapExtras::mx_jabberwock(), MapExtras::mx_looters(), MapExtras::mx_minefield(), MapExtras::mx_portal_in(), MapExtras::mx_reed(), MapExtras::mx_roadworks(), iuse::mycus(), monster::next_upgrade_time(), nicotine_effect(), vehicle::noise_and_smoke(), read_activity_actor::npc_read(), mattack::nurse_assist(), mattack::nurse_operate(), Character::on_damage_of_type(), Character::on_hit(), one_turn_in(), map::open_door(), vehicle::operate_scoop(), opiate_effect(), anonymous_namespace{do_turn.cpp}::overmap_npc_move(), mattack::parrot(), mattack::parrot_at_danger(), vehicle::part_collision(), Character::pause(), game::perhaps_add_random_npc(), iuse::petfood(), mattack::photograph(), forest_biome::pick(), trapfunc::pit_glass(), trapfunc::pit_spikes(), fixed_overmap_special_data::place(), overmap::place_cities(), overmap::place_forest_trailheads(), overmap::place_forest_trails(), MapExtras::place_fumarole(), map::place_gas_pump(), overmap::place_mongroups(), game::place_player(), overmap::place_radios(), overmap::place_river(), overmap::place_rivers(), vehicle::place_spawn_items(), map::place_spawns(), overmap::place_swamps(), map::place_vending(), monster::plan(), mattack::plant(), vehicle::play_chimes(), map::player_in_field(), read_activity_actor::player_read(), read_activity_actor::player_readma(), vehicle::pldrive(), iuse::poison(), npc::pretend_fire(), monster::process_effects(), item::process_extinguish(), item::process_litcig(), monster::process_one_effect(), sounds::process_sound_markers(), monster::process_triggers(), monster::process_turn(), process_vehicle_items(), map::produce_sap(), projectile_attack(), iuse::prozac(), activity_handlers::pulp_do_turn(), iuse::purify_smart(), anonymous_namespace{monexamine.cpp}::push(), iuse::radio_tick(), npc_class::random_common(), avatar::randomize(), npc::randomize(), avatar::randomize_cosmetics(), Character::reach_attack(), item::ready_to_revive(), firestarter_actor::resolve_firestarter_use(), explosion_handler::resonance_cascade(), mattack::resurrect(), reveal_target(), mattack::rifle(), mattack::riotbot(), activity_handlers::robot_control_finish(), Character::roll_critical_bionics_failure(), inventory::rust_iron_items(), iexamine::safe(), scatter_chunks(), talk_function::scavenging_patrol_return(), talk_function::scavenging_raid_return(), mattack::science(), science_room(), mattack::searchlight(), npc::see_item_say_smth(), set_description(), set_up_butchery(), trapfunc::shadow(), map::shake_vehicle(), mattack::shockstorm(), map::shoot(), npc::shop_restock(), trapfunc::shotgun(), mattack::shriek_stun(), spell_effect::slime_split_on_death(), mattack::slimespring(), smash(), iuse::smoking(), trapfunc::snake(), trapfunc::snare_heavy(), game::spawn_hallucination(), map::spawn_item(), map::spawn_monsters_submap(), spawn_spores(), fungal_effects::spread_fungus(), fungal_effects::spread_fungus_one_tile(), map::spread_gas(), vehicle::start_engine(), starting_inv(), monster::stumble(), survive_random_encounter(), anonymous_namespace{monexamine.cpp}::swap(), avatar_action::swim(), mattack::tankgun(), iuse::thorazine(), mattack::tindalos_teleport(), spell_effect::transform_blast(), activity_handlers::tree_communion_do_turn(), iexamine::tree_marloss(), mattack::triffid_heartbeat(), avatar::try_break_relax_gas(), Character::try_remove_grab(), monster::try_reproduce(), gun_actor::try_target(), Character::update_bodytemp(), Character::update_frostbite(), iuse_transform::use(), fireweapon_on_actor::use(), mattack::vine(), game::walk_move(), map::water_from(), weather_sound(), iuse::weed_cake(), weed_msg(), scenario::weighted_random(), scenario::weighted_random_profession(), wet_character(), suffer::while_awake(), suffer::without_sleep(), and npc::worker_downtime().
one_turn_in()
bool one_turn_in (const time_duration & duration)
Definition at line 113 of file rng.cpp.
 {
     return one_in( to_turns<int>( duration ) );
 }
References one_in().
Referenced by eff_fun_teleglow(), suffer::from_bad_bionics(), suffer::from_chemimbalance(), suffer::from_nyctophobia(), suffer::from_other_mutations(), suffer::from_stimulants(), suffer::from_sunburn(), suffer::from_tourniquet(), Character::hardcoded_effects(), suffer::while_awake(), and suffer::without_sleep().
random_direction()
units::angle random_direction ()
Definition at line 40 of file rng.cpp.
 {
     return rng_float( 0_pi_radians, 2_pi_radians );
 }
References rng_float().
Referenced by VehicleSpawnFunction::builtin_parkinglot(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), MapExtras::mx_helicopter(), MapExtras::mx_roadworks(), and weather_sound().
random_string()
std::string random_string (size_t length)
Definition at line 213 of file rng.cpp.
 {
     auto randchar = []() -> char {
         // NOLINTNEXTLINE(modernize-avoid-c-arrays)
         static constexpr char charset[] =
         "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
         "abcdefghijklmnopqrstuvwxyz";
         static constexpr size_t num_chars = sizeof( charset ) - 1;
         return charset[rng( 0, num_chars - 1 )];
     };
     std::string str( length, 0 );
     std::generate_n( str.begin(), length, randchar );
     return str;
 }
References length, and rng().
rng()
int rng (int lo, int hi)
Definition at line 18 of file rng.cpp.
 {
     static std::uniform_int_distribution<int> rng_int_dist;
     if( lo > hi ) {
         std::swap( lo, hi );
     }
     return rng_int_dist( rng_get_engine(), std::uniform_int_distribution<>::param_type( lo, hi ) );
 }
References cata::hash64_detail::lo, rng_get_engine(), and cata::swap().
Referenced by dice(), one_in(), random_entry(), random_entry_opt(), random_entry_ref(), random_entry_removed(), and random_string().
rng_bits()
unsigned int rng_bits ()
Definition at line 11 of file rng.cpp.
 {
     // Whole uint range.
     static std::uniform_int_distribution<unsigned int> rng_uint_dist;
     return rng_uint_dist( rng_get_engine() );
 }
References rng_get_engine().
Referenced by weighted_list< W, T >::pick(), snippet_library::random_from_category(), snippet_library::random_id_from_category(), and game::start_game().
rng_exponential()
double rng_exponential (double min, double mean)
Definition at line 98 of file rng.cpp.
 {
     const double adjusted_mean = mean - min;
     if( adjusted_mean <= 0.0 ) {
         return 0.0;
     }
     // lambda = 1 / mean
     return min + exponential_roll( 1.0 / adjusted_mean );
 }
References exponential_roll(), and min().
Referenced by item::handle_craft_failure(), and rng_exponential().
rng_float()
double rng_float (double lo, double hi)
Definition at line 27 of file rng.cpp.
 {
     static std::uniform_real_distribution<double> rng_real_dist;
     if( lo > hi ) {
         std::swap( lo, hi );
     }
     if( std::isfinite( lo ) && std::isfinite( hi ) ) {
         return rng_real_dist( rng_get_engine(), std::uniform_real_distribution<>::param_type( lo, hi ) );
     }
     debugmsg( "rng_float called with nan/inf" );
     return 0;
 }
References debugmsg, cata::hash64_detail::lo, rng_get_engine(), and cata::swap().
Referenced by computer_session::action_irradiator(), weakpoint_effect::apply_to(), map::bash(), map::bash_items(), Character::bonus_damage(), butchery_drops_harvest(), melee_actor::call(), talk_function::caravan_depart(), item::charge_linked_batteries(), Character::complete_disassemble(), veh_interact::complete_vehicle(), Single_item_creator::create(), item::damage_armor_transforms(), explosion_handler::do_blast(), data_handling_activity_actor::do_turn(), Character::estimate_effect_dur(), harvest_activity_actor::finish(), talk_function::forage_return(), game::forced_door_closing(), suffer::from_chemimbalance(), suffer::from_sunburn(), relic_procgen_data::generate(), iuse::granade_act(), talk_function::hospital_raid_return(), math_rng(), Character::melee_special_effects(), map::monster_in_field(), lightson_game::new_level(), Character::on_hit(), vehicle::part_collision(), map::place_items(), vehicle::place_spawn_items(), map::place_spawns(), vehicle::pldrive(), projectile_attack(), anatomy::random_body_part(), random_direction(), Character::randomize_blood(), item::randomize_rot(), repair_item_actor::repair(), rng_float(), dispersion_sources::roll(), Character::roll_bad_mutation(), roll_butchery_dissect(), roll_melee_damage_internal(), talk_function::scavenging_patrol_return(), talk_function::scavenging_raid_return(), Character::scored_crit(), Creature::select_body_part_projectile_attack(), weakpoints::select_weakpoint(), map::shake_vehicle(), npc::shop_restock(), explosion_handler::shrapnel(), vehicle::smash(), activity_handlers::spellcasting_finish(), iuse::tazer(), suffer::without_sleep(), and x_in_y().
rng_get_engine()
cata_default_random_engine& rng_get_engine ()
Definition at line 199 of file rng.cpp.
 {
     // NOLINTNEXTLINE(cata-determinism)
     static cata_default_random_engine eng( rng_get_first_seed() );
     return eng;
 }
References rng_get_first_seed().
Referenced by anonymous_namespace{npctrade_utils.cpp}::_get_shuffled_point_set(), explosion_handler::_make_explosion(), overmap::build_lab(), start_location::burn(), chi_squared_roll(), Character::evaluate_techniques(), exponential_roll(), get_sectors(), weather_generator::get_wind_direction(), field_entry::initialize_decay(), npc::learn_ma_styles_from_traits(), Character::melee_attack_abstract(), Character::mutate(), normal_roll(), overmap::place_forest_trails(), overmap::place_mongroups(), overmap::place_railroads(), overmap::place_roads(), overmap::place_special_attempt(), overmap::place_specials_pass(), put_into_container(), overmap::random_special_rotation(), rng(), rng_bits(), rng_float(), rng_set_engine_seed(), run_item_eocs(), uniform_distribution::sample(), binomial_distribution::sample(), poisson_distribution::sample(), and explosion_handler::shrapnel().
rng_get_first_seed()
cata_default_random_engine::result_type rng_get_first_seed ()
Definition at line 192 of file rng.cpp.
 {
     using rep = std::chrono::high_resolution_clock::rep;
     static rep seed = std::chrono::high_resolution_clock::now().time_since_epoch().count();
     return static_cast<cata_default_random_engine::result_type>( seed );
 }
References iuse::seed().
Referenced by rng_get_engine().
rng_normal()
double rng_normal (double lo, double hi)
Definition at line 178 of file rng.cpp.
 {
     if( lo > hi ) {
         std::swap( lo, hi );
     }
     const double range = ( hi - lo ) / 4;
     if( range == 0.0 ) {
         return hi;
     }
     double val = normal_roll( ( hi + lo ) / 2, range );
     return clamp( val, lo, hi );
 }
References clamp(), cata::hash64_detail::lo, normal_roll(), and cata::swap().
Referenced by Creature::dodge_check(), mapgen_forest(), anonymous_namespace{messages.cpp}::messages_impl::modify_msg_with_exclamations(), Character::randomize_heartrate(), rng_normal(), and dispersion_sources::roll().
rng_sequence()
std::vector<int> rng_sequence (size_t count, int lo, int hi, int seed)
Definition at line 160 of file rng.cpp.
 {
     if( lo > hi ) {
         std::swap( lo, hi );
     }
     std::vector<int> result;
     result.reserve( count );
     // NOLINTNEXTLINE(cata-determinism)
     cata_default_random_engine eng( seed );
     std::uniform_int_distribution<int> rng_int_dist;
     const std::uniform_int_distribution<int>::param_type param( lo, hi );
     for( size_t i = 0; i < count; i++ ) {
         result.push_back( rng_int_dist( eng, param ) );
     }
     return result;
 }
References cata::hash64_detail::lo, iuse::seed(), and cata::swap().
Referenced by vehicle::restore_folded_parts().
rng_set_engine_seed()
void rng_set_engine_seed (unsigned int seed)
Definition at line 206 of file rng.cpp.
 {
     if( seed != 0 ) {
         rng_get_engine().seed( seed );
     }
 }
References rng_get_engine(), and iuse::seed().
Referenced by main().
roll_remainder()
int roll_remainder (double value)
Definition at line 134 of file rng.cpp.
 {
     double integ;
     double frac = modf( value, &integ );
     if( value > 0.0 && value > integ && x_in_y( frac, 1.0 ) ) {
         integ++;
     } else if( value < 0.0 && value < integ && x_in_y( -frac, 1.0 ) ) {
         integ--;
     }
     return integ;
 }
References x_in_y().
Referenced by outfit::absorb_damage(), jmapgen_monster::apply(), jmapgen_spawn_item::apply(), Character::apply_damage(), spell_effect::banishment(), item::burn(), npc_trading::cash_to_favor(), vehicle::charge_battery(), Character::craft_skill_gain(), Creature::deal_damage_handle_type(), vehicle::discharge_battery(), map::emit_field(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), map::generate(), Character::get_miss_reason(), repair_item_actor::handle_components(), vehicle::handle_trap(), Character::irradiate(), map::item_category_spawn_rate(), magic_train(), Character::mend(), Character::mod_pain(), Character::on_damage_of_type(), monster::on_load(), overmap::place_cities(), map::place_items(), vehicle::place_spawn_items(), map::place_spawns(), vehicle::power_to_energy_bat(), map::produce_sap(), projectile_attack(), Character::regen(), retroactively_fill_from_funnel(), roll_remainder(), game::slip_down_chance(), activity_handlers::study_spell_do_turn(), start_location::surround_with_monsters(), Character::update_body_wetness(), Character::update_needs(), Character::update_stomach(), vehicle::update_time(), suffer::water_damage(), and weather_sound().
x_in_y()
bool x_in_y (double x, double y)
Definition at line 118 of file rng.cpp.
 {
     return rng_float( 0.0, 1.0 ) <= x / y;
 }
References rng_float().
Referenced by roll_remainder().