Cataclysm DDA: src/safemode_ui.cpp File Reference
safemode_ui.cpp File Reference
#include "safemode_ui.h"
#include <algorithm>
#include <map>
#include <string>
#include <utility>
#include "cata_utility.h"
#include "character.h"
#include "color.h"
#include "cursesdef.h"
#include "debug.h"
#include "filesystem.h"
#include "input_context.h"
#include "json.h"
#include "json_loader.h"
#include "monstergenerator.h"
#include "mtype.h"
#include "options.h"
#include "output.h"
#include "path_info.h"
#include "point.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "ui_manager.h"
Functions
safemode & get_safemode ()
Function Documentation
get_safemode()
safemode& get_safemode ()
Definition at line 28 of file safemode_ui.cpp.
 {
     static safemode single_instance;
     return single_instance;
 }
Referenced by game::check_safe_mode_allowed(), game::do_regular_action(), game::list_monsters(), game::load(), game::load_static_data(), game::mon_info_update(), main_menu::opening_screen(), sounds::process_sound_markers(), game::save(), and game::start_game().