Cataclysm DDA: src/safemode_ui.h File Reference
safemode_ui.h File Reference
#include <array>
#include <iosfwd>
#include <string>
#include <unordered_map>
#include <vector>
#include "creature.h"
#include "enums.h"
Classes
class safemode
class safemode::rules_class
class safemode::rule_state_class
Macros
#define CATA_SRC_SAFEMODE_UI_H
Functions
safemode & get_safemode ()
Macro Definition Documentation
CATA_SRC_SAFEMODE_UI_H
#define CATA_SRC_SAFEMODE_UI_H
Definition at line 3 of file safemode_ui.h.
Function Documentation
get_safemode()
safemode& get_safemode ()
Definition at line 28 of file safemode_ui.cpp.
 {
     static safemode single_instance;
     return single_instance;
 }
Referenced by game::check_safe_mode_allowed(), game::do_regular_action(), game::list_monsters(), game::load(), game::load_static_data(), game::mon_info_update(), main_menu::opening_screen(), sounds::process_sound_markers(), game::save(), and game::start_game().