Cataclysm DDA: src/savegame_legacy.cpp File Reference
savegame_legacy.cpp File Reference
#include <cstddef>
#include <iosfwd>
#include <unordered_map>
#include <utility>
#include <vector>
#include "activity_type.h"
#include "debug.h"
#include "npc.h"
#include "player_activity.h"
Classes
struct std::hash< talk_topic_enum >
Macros
#define WRAP(value) { value, #value }
Functions
std::string convert_talk_topic (talk_topic_enum const old_value)
Variables
static const activity_id ACT_ADV_INVENTORY ("ACT_ADV_INVENTORY")
static const activity_id ACT_AIM ("ACT_AIM")
static const activity_id ACT_ARMOR_LAYERS ("ACT_ARMOR_LAYERS")
static const activity_id ACT_ATM ("ACT_ATM")
static const activity_id ACT_BUILD ("ACT_BUILD")
static const activity_id ACT_BURROW ("ACT_BURROW")
static const activity_id ACT_BUTCHER ("ACT_BUTCHER")
static const activity_id ACT_CRACKING ("ACT_CRACKING")
static const activity_id ACT_DISASSEMBLE ("ACT_DISASSEMBLE")
static const activity_id ACT_FILL_LIQUID ("ACT_FILL_LIQUID")
static const activity_id ACT_FISH ("ACT_FISH")
static const activity_id ACT_GAME ("ACT_GAME")
static const activity_id ACT_HOTWIRE_CAR ("ACT_HOTWIRE_CAR")
static const activity_id ACT_MEDITATE ("ACT_MEDITATE")
static const activity_id ACT_MEND_ITEM ("ACT_MEND_ITEM")
static const activity_id ACT_MOVE_ITEMS ("ACT_MOVE_ITEMS")
static const activity_id ACT_OPEN_GATE ("ACT_OPEN_GATE")
static const activity_id ACT_PICKAXE ("ACT_PICKAXE")
static const activity_id ACT_PICKUP ("ACT_PICKUP")
static const activity_id ACT_PULP ("ACT_PULP")
static const activity_id ACT_RELOAD ("ACT_RELOAD")
static const activity_id ACT_REPAIR_ITEM ("ACT_REPAIR_ITEM")
static const activity_id ACT_START_ENGINES ("ACT_START_ENGINES")
static const activity_id ACT_START_FIRE ("ACT_START_FIRE")
static const activity_id ACT_TRAIN ("ACT_TRAIN")
static const activity_id ACT_VEHICLE ("ACT_VEHICLE")
static const activity_id ACT_VIBE ("ACT_VIBE")
static const activity_id ACT_WAIT ("ACT_WAIT")
static const activity_id ACT_WAIT_NPC ("ACT_WAIT_NPC")
static const activity_id ACT_WAIT_WEATHER ("ACT_WAIT_WEATHER")
Macro Definition Documentation
WRAP
#define WRAP (value) { value, #value }
Function Documentation
convert_talk_topic()
std::string convert_talk_topic (talk_topic_enum const old_value)
Definition at line 54 of file savegame_legacy.cpp.
 {
     static const std::unordered_map<talk_topic_enum, std::string> talk_topic_enum_mapping = { {
             // This macro creates the appropriate new names (as string) for each enum value, so one does not
             // have to repeat so much (e.g. 'WRAP(TALK_ARSONIST)' instead of '{ TALK_ARSONIST, "TALK_ARSONIST" }')
             // It also ensures that each name is exactly as the name of the enum value.
 #define WRAP(value) { value, #value }
             WRAP( TALK_NONE ),
             WRAP( TALK_DONE ),
             WRAP( TALK_GUARD ),
             WRAP( TALK_MISSION_LIST ),
             WRAP( TALK_MISSION_LIST_ASSIGNED ),
             WRAP( TALK_MISSION_DESCRIBE ),
             WRAP( TALK_MISSION_OFFER ),
             WRAP( TALK_MISSION_ACCEPTED ),
             WRAP( TALK_MISSION_REJECTED ),
             WRAP( TALK_MISSION_ADVICE ),
             WRAP( TALK_MISSION_INQUIRE ),
             WRAP( TALK_MISSION_SUCCESS ),
             WRAP( TALK_MISSION_SUCCESS_LIE ),
             WRAP( TALK_MISSION_FAILURE ),
             WRAP( TALK_MISSION_REWARD ),
             WRAP( TALK_EVAC_MERCHANT ),
             WRAP( TALK_EVAC_MERCHANT_NEW ),
             WRAP( TALK_EVAC_MERCHANT_PLANS ),
             WRAP( TALK_EVAC_MERCHANT_PLANS2 ),
             WRAP( TALK_EVAC_MERCHANT_PLANS3 ),
             WRAP( TALK_EVAC_MERCHANT_WORLD ),
             WRAP( TALK_EVAC_MERCHANT_HORDES ),
             WRAP( TALK_EVAC_MERCHANT_PRIME_LOOT ),
             WRAP( TALK_EVAC_MERCHANT_ASK_JOIN ),
             WRAP( TALK_EVAC_MERCHANT_NO ),
             WRAP( TALK_EVAC_MERCHANT_HELL_NO ),
             WRAP( TALK_FREE_MERCHANT_STOCKS ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_NEW ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_WHY ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_ALL ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_JERKY ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_CORNMEAL ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_FLOUR ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_SUGAR ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_WINE ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_BEER ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_SMMEAT ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_SMFISH ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_OIL ),
             WRAP( TALK_FREE_MERCHANT_STOCKS_DELIVERED ),
             WRAP( TALK_EVAC_GUARD1 ),
             WRAP( TALK_EVAC_GUARD1_PLACE ),
             WRAP( TALK_EVAC_GUARD1_GOVERNMENT ),
             WRAP( TALK_EVAC_GUARD1_TRADE ),
             WRAP( TALK_EVAC_GUARD1_JOIN ),
             WRAP( TALK_EVAC_GUARD1_JOIN2 ),
             WRAP( TALK_EVAC_GUARD1_JOIN3 ),
             WRAP( TALK_EVAC_GUARD1_ATTITUDE ),
             WRAP( TALK_EVAC_GUARD1_JOB ),
             WRAP( TALK_EVAC_GUARD1_OLDGUARD ),
             WRAP( TALK_EVAC_GUARD1_BYE ),
             WRAP( TALK_EVAC_GUARD2 ),
             WRAP( TALK_EVAC_GUARD2_NEW ),
             WRAP( TALK_EVAC_GUARD2_RULES ),
             WRAP( TALK_EVAC_GUARD2_RULES_BASEMENT ),
             WRAP( TALK_EVAC_GUARD2_WHO ),
             WRAP( TALK_EVAC_GUARD2_TRADE ),
             WRAP( TALK_EVAC_GUARD3 ),
             WRAP( TALK_EVAC_GUARD3_NEW ),
             WRAP( TALK_EVAC_GUARD3_RULES ),
             WRAP( TALK_EVAC_GUARD3_HIDE1 ),
             WRAP( TALK_EVAC_GUARD3_HIDE2 ),
             WRAP( TALK_EVAC_GUARD3_WASTE ),
             WRAP( TALK_EVAC_GUARD3_DEAD ),
             WRAP( TALK_EVAC_GUARD3_HOSTILE ),
             WRAP( TALK_EVAC_GUARD3_INSULT ),
             WRAP( TALK_EVAC_HUNTER ),
             WRAP( TALK_EVAC_HUNTER_SMELL ),
             WRAP( TALK_EVAC_HUNTER_DO ),
             WRAP( TALK_EVAC_HUNTER_LIFE ),
             WRAP( TALK_EVAC_HUNTER_HUNT ),
             WRAP( TALK_EVAC_HUNTER_SALE ),
             WRAP( TALK_EVAC_HUNTER_ADVICE ),
             WRAP( TALK_EVAC_HUNTER_BYE ),
             WRAP( TALK_OLD_GUARD_REP ),
             WRAP( TALK_OLD_GUARD_REP_NEW ),
             WRAP( TALK_OLD_GUARD_REP_NEW_DOING ),
             WRAP( TALK_OLD_GUARD_REP_NEW_DOWNSIDE ),
             WRAP( TALK_OLD_GUARD_REP_WORLD ),
             WRAP( TALK_OLD_GUARD_REP_WORLD_2NDFLEET ),
             WRAP( TALK_OLD_GUARD_REP_WORLD_FOOTHOLDS ),
             WRAP( TALK_OLD_GUARD_REP_ASK_JOIN ),
             WRAP( TALK_ARSONIST ),
             WRAP( TALK_ARSONIST_NEW ),
             WRAP( TALK_ARSONIST_DOING ),
             WRAP( TALK_ARSONIST_DOING_REBAR ),
             WRAP( TALK_ARSONIST_WORLD ),
             WRAP( TALK_ARSONIST_WORLD_OPTIMISTIC ),
             WRAP( TALK_ARSONIST_JOIN ),
             WRAP( TALK_ARSONIST_MUTATION ),
             WRAP( TALK_ARSONIST_MUTATION_INSULT ),
             WRAP( TALK_SCAVENGER_MERC ),
             WRAP( TALK_SCAVENGER_MERC_NEW ),
             WRAP( TALK_SCAVENGER_MERC_TIPS ),
             WRAP( TALK_SCAVENGER_MERC_HIRE ),
             WRAP( TALK_SCAVENGER_MERC_HIRE_SUCCESS ),
             WRAP( TALK_SHELTER ),
             WRAP( TALK_SHELTER_PLANS ),
             WRAP( TALK_SHARE_EQUIPMENT ),
             WRAP( TALK_GIVE_EQUIPMENT ),
             WRAP( TALK_DENY_EQUIPMENT ),
             WRAP( TALK_TRAIN ),
             WRAP( TALK_TRAIN_START ),
             WRAP( TALK_TRAIN_FORCE ),
             WRAP( TALK_SUGGEST_FOLLOW ),
             WRAP( TALK_AGREE_FOLLOW ),
             WRAP( TALK_DENY_FOLLOW ),
             WRAP( TALK_SHOPKEEP ),
             WRAP( TALK_LEADER ),
             WRAP( TALK_LEAVE ),
             WRAP( TALK_PLAYER_LEADS ),
             WRAP( TALK_LEADER_STAYS ),
             WRAP( TALK_HOW_MUCH_FURTHER ),
             WRAP( TALK_FRIEND ),
             WRAP( TALK_FRIEND_GUARD ),
             WRAP( TALK_DENY_GUARD ),
             WRAP( TALK_DENY_TRAIN ),
             WRAP( TALK_DENY_PERSONAL ),
             WRAP( TALK_FRIEND_UNCOMFORTABLE ),
             WRAP( TALK_COMBAT_COMMANDS ),
             WRAP( TALK_COMBAT_ENGAGEMENT ),
             WRAP( TALK_STRANGER_NEUTRAL ),
             WRAP( TALK_STRANGER_WARY ),
             WRAP( TALK_STRANGER_SCARED ),
             WRAP( TALK_STRANGER_FRIENDLY ),
             WRAP( TALK_STRANGER_AGGRESSIVE ),
             WRAP( TALK_MUG ),
             WRAP( TALK_DESCRIBE_MISSION ),
             WRAP( TALK_WEAPON_DROPPED ),
             WRAP( TALK_DEMAND_LEAVE ),
             WRAP( TALK_SIZE_UP ),
             WRAP( TALK_LOOK_AT ),
             WRAP( TALK_OPINION )
         }
     };
 #undef WRAP
     const auto iter = talk_topic_enum_mapping.find( old_value );
     if( iter == talk_topic_enum_mapping.end() ) {
         debugmsg( "could not convert %d to new talk topic string", static_cast<int>( old_value ) );
         return "TALK_NONE";
     }
     return iter->second;
 }
References debugmsg, TALK_AGREE_FOLLOW, TALK_ARSONIST, TALK_ARSONIST_DOING, TALK_ARSONIST_DOING_REBAR, TALK_ARSONIST_JOIN, TALK_ARSONIST_MUTATION, TALK_ARSONIST_MUTATION_INSULT, TALK_ARSONIST_NEW, TALK_ARSONIST_WORLD, TALK_ARSONIST_WORLD_OPTIMISTIC, TALK_COMBAT_COMMANDS, TALK_COMBAT_ENGAGEMENT, TALK_DEMAND_LEAVE, TALK_DENY_EQUIPMENT, TALK_DENY_FOLLOW, TALK_DENY_GUARD, TALK_DENY_PERSONAL, TALK_DENY_TRAIN, TALK_DESCRIBE_MISSION, TALK_DONE, TALK_EVAC_GUARD1, TALK_EVAC_GUARD1_ATTITUDE, TALK_EVAC_GUARD1_BYE, TALK_EVAC_GUARD1_GOVERNMENT, TALK_EVAC_GUARD1_JOB, TALK_EVAC_GUARD1_JOIN, TALK_EVAC_GUARD1_JOIN2, TALK_EVAC_GUARD1_JOIN3, TALK_EVAC_GUARD1_OLDGUARD, TALK_EVAC_GUARD1_PLACE, TALK_EVAC_GUARD1_TRADE, TALK_EVAC_GUARD2, TALK_EVAC_GUARD2_NEW, TALK_EVAC_GUARD2_RULES, TALK_EVAC_GUARD2_RULES_BASEMENT, TALK_EVAC_GUARD2_TRADE, TALK_EVAC_GUARD2_WHO, TALK_EVAC_GUARD3, TALK_EVAC_GUARD3_DEAD, TALK_EVAC_GUARD3_HIDE1, TALK_EVAC_GUARD3_HIDE2, TALK_EVAC_GUARD3_HOSTILE, TALK_EVAC_GUARD3_INSULT, TALK_EVAC_GUARD3_NEW, TALK_EVAC_GUARD3_RULES, TALK_EVAC_GUARD3_WASTE, TALK_EVAC_HUNTER, TALK_EVAC_HUNTER_ADVICE, TALK_EVAC_HUNTER_BYE, TALK_EVAC_HUNTER_DO, TALK_EVAC_HUNTER_HUNT, TALK_EVAC_HUNTER_LIFE, TALK_EVAC_HUNTER_SALE, TALK_EVAC_HUNTER_SMELL, TALK_EVAC_MERCHANT, TALK_EVAC_MERCHANT_ASK_JOIN, TALK_EVAC_MERCHANT_HELL_NO, TALK_EVAC_MERCHANT_HORDES, TALK_EVAC_MERCHANT_NEW, TALK_EVAC_MERCHANT_NO, TALK_EVAC_MERCHANT_PLANS, TALK_EVAC_MERCHANT_PLANS2, TALK_EVAC_MERCHANT_PLANS3, TALK_EVAC_MERCHANT_PRIME_LOOT, TALK_EVAC_MERCHANT_WORLD, TALK_FREE_MERCHANT_STOCKS, TALK_FREE_MERCHANT_STOCKS_ALL, TALK_FREE_MERCHANT_STOCKS_BEER, TALK_FREE_MERCHANT_STOCKS_CORNMEAL, TALK_FREE_MERCHANT_STOCKS_DELIVERED, TALK_FREE_MERCHANT_STOCKS_FLOUR, TALK_FREE_MERCHANT_STOCKS_JERKY, TALK_FREE_MERCHANT_STOCKS_NEW, TALK_FREE_MERCHANT_STOCKS_OIL, TALK_FREE_MERCHANT_STOCKS_SMFISH, TALK_FREE_MERCHANT_STOCKS_SMMEAT, TALK_FREE_MERCHANT_STOCKS_SUGAR, TALK_FREE_MERCHANT_STOCKS_WHY, TALK_FREE_MERCHANT_STOCKS_WINE, TALK_FRIEND, TALK_FRIEND_GUARD, TALK_FRIEND_UNCOMFORTABLE, TALK_GIVE_EQUIPMENT, TALK_GUARD, TALK_HOW_MUCH_FURTHER, TALK_LEADER, TALK_LEADER_STAYS, TALK_LEAVE, TALK_LOOK_AT, TALK_MISSION_ACCEPTED, TALK_MISSION_ADVICE, TALK_MISSION_DESCRIBE, TALK_MISSION_FAILURE, TALK_MISSION_INQUIRE, TALK_MISSION_LIST, TALK_MISSION_LIST_ASSIGNED, TALK_MISSION_OFFER, TALK_MISSION_REJECTED, TALK_MISSION_REWARD, TALK_MISSION_SUCCESS, TALK_MISSION_SUCCESS_LIE, TALK_MUG, TALK_NONE, TALK_OLD_GUARD_REP, TALK_OLD_GUARD_REP_ASK_JOIN, TALK_OLD_GUARD_REP_NEW, TALK_OLD_GUARD_REP_NEW_DOING, TALK_OLD_GUARD_REP_NEW_DOWNSIDE, TALK_OLD_GUARD_REP_WORLD, TALK_OLD_GUARD_REP_WORLD_2NDFLEET, TALK_OLD_GUARD_REP_WORLD_FOOTHOLDS, TALK_OPINION, TALK_PLAYER_LEADS, TALK_SCAVENGER_MERC, TALK_SCAVENGER_MERC_HIRE, TALK_SCAVENGER_MERC_HIRE_SUCCESS, TALK_SCAVENGER_MERC_NEW, TALK_SCAVENGER_MERC_TIPS, TALK_SHARE_EQUIPMENT, TALK_SHELTER, TALK_SHELTER_PLANS, TALK_SHOPKEEP, TALK_SIZE_UP, TALK_STRANGER_AGGRESSIVE, TALK_STRANGER_FRIENDLY, TALK_STRANGER_NEUTRAL, TALK_STRANGER_SCARED, TALK_STRANGER_WARY, TALK_SUGGEST_FOLLOW, TALK_TRAIN, TALK_TRAIN_FORCE, TALK_TRAIN_START, TALK_WEAPON_DROPPED, and WRAP.
Referenced by dialogue_chatbin::deserialize().
Variable Documentation
ACT_ADV_INVENTORY
const activity_id ACT_ADV_INVENTORY("ACT_ADV_INVENTORY") ("ACT_ADV_INVENTORY") static
Referenced by player_activity::deserialize_legacy_type().
ACT_AIM
const activity_id ACT_AIM("ACT_AIM") ("ACT_AIM") static
Referenced by player_activity::deserialize_legacy_type().
ACT_ARMOR_LAYERS
const activity_id ACT_ARMOR_LAYERS("ACT_ARMOR_LAYERS") ("ACT_ARMOR_LAYERS") static
Referenced by player_activity::deserialize_legacy_type().
ACT_ATM
const activity_id ACT_ATM("ACT_ATM") ("ACT_ATM") static
Referenced by player_activity::deserialize_legacy_type().
ACT_BUILD
const activity_id ACT_BUILD("ACT_BUILD") ("ACT_BUILD") static
Referenced by player_activity::deserialize_legacy_type().
ACT_BURROW
const activity_id ACT_BURROW("ACT_BURROW") ("ACT_BURROW") static
Referenced by player_activity::deserialize_legacy_type().
ACT_BUTCHER
const activity_id ACT_BUTCHER("ACT_BUTCHER") ("ACT_BUTCHER") static
Referenced by player_activity::deserialize_legacy_type().
ACT_CRACKING
const activity_id ACT_CRACKING("ACT_CRACKING") ("ACT_CRACKING") static
Referenced by player_activity::deserialize_legacy_type().
ACT_DISASSEMBLE
const activity_id ACT_DISASSEMBLE("ACT_DISASSEMBLE") ("ACT_DISASSEMBLE") static
Referenced by player_activity::deserialize_legacy_type().
ACT_FILL_LIQUID
const activity_id ACT_FILL_LIQUID("ACT_FILL_LIQUID") ("ACT_FILL_LIQUID") static
Referenced by player_activity::deserialize_legacy_type().
ACT_FISH
const activity_id ACT_FISH("ACT_FISH") ("ACT_FISH") static
Referenced by player_activity::deserialize_legacy_type().
ACT_GAME
const activity_id ACT_GAME("ACT_GAME") ("ACT_GAME") static
Referenced by player_activity::deserialize_legacy_type().
ACT_HOTWIRE_CAR
const activity_id ACT_HOTWIRE_CAR("ACT_HOTWIRE_CAR") ("ACT_HOTWIRE_CAR") static
Referenced by player_activity::deserialize_legacy_type().
ACT_MEDITATE
const activity_id ACT_MEDITATE("ACT_MEDITATE") ("ACT_MEDITATE") static
Referenced by player_activity::deserialize_legacy_type().
ACT_MEND_ITEM
const activity_id ACT_MEND_ITEM("ACT_MEND_ITEM") ("ACT_MEND_ITEM") static
Referenced by player_activity::deserialize_legacy_type().
ACT_MOVE_ITEMS
const activity_id ACT_MOVE_ITEMS("ACT_MOVE_ITEMS") ("ACT_MOVE_ITEMS") static
Referenced by player_activity::deserialize_legacy_type().
ACT_OPEN_GATE
const activity_id ACT_OPEN_GATE("ACT_OPEN_GATE") ("ACT_OPEN_GATE") static
Referenced by player_activity::deserialize_legacy_type().
ACT_PICKAXE
const activity_id ACT_PICKAXE("ACT_PICKAXE") ("ACT_PICKAXE") static
Referenced by player_activity::deserialize_legacy_type().
ACT_PICKUP
const activity_id ACT_PICKUP("ACT_PICKUP") ("ACT_PICKUP") static
Referenced by player_activity::deserialize_legacy_type().
ACT_PULP
const activity_id ACT_PULP("ACT_PULP") ("ACT_PULP") static
Referenced by player_activity::deserialize_legacy_type().
ACT_RELOAD
const activity_id ACT_RELOAD("ACT_RELOAD") ("ACT_RELOAD") static
Referenced by player_activity::deserialize_legacy_type().
ACT_REPAIR_ITEM
const activity_id ACT_REPAIR_ITEM("ACT_REPAIR_ITEM") ("ACT_REPAIR_ITEM") static
Referenced by player_activity::deserialize_legacy_type().
ACT_START_ENGINES
const activity_id ACT_START_ENGINES("ACT_START_ENGINES") ("ACT_START_ENGINES") static
Referenced by player_activity::deserialize_legacy_type().
ACT_START_FIRE
const activity_id ACT_START_FIRE("ACT_START_FIRE") ("ACT_START_FIRE") static
Referenced by player_activity::deserialize_legacy_type().
ACT_TRAIN
const activity_id ACT_TRAIN("ACT_TRAIN") ("ACT_TRAIN") static
Referenced by player_activity::deserialize_legacy_type().
ACT_VEHICLE
const activity_id ACT_VEHICLE("ACT_VEHICLE") ("ACT_VEHICLE") static
Referenced by player_activity::deserialize_legacy_type().
ACT_VIBE
const activity_id ACT_VIBE("ACT_VIBE") ("ACT_VIBE") static
Referenced by player_activity::deserialize_legacy_type().
ACT_WAIT
const activity_id ACT_WAIT("ACT_WAIT") ("ACT_WAIT") static
Referenced by player_activity::deserialize_legacy_type().
ACT_WAIT_NPC
const activity_id ACT_WAIT_NPC("ACT_WAIT_NPC") ("ACT_WAIT_NPC") static
Referenced by player_activity::deserialize_legacy_type().
ACT_WAIT_WEATHER
const activity_id ACT_WAIT_WEATHER("ACT_WAIT_WEATHER") ("ACT_WAIT_WEATHER") static
Referenced by player_activity::deserialize_legacy_type().