Cataclysm DDA: src/savegame.cpp File Reference
savegame.cpp File Reference
#include "game.h"
#include <algorithm>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "achievement.h"
#include "avatar.h"
#include "basecamp.h"
#include "cata_io.h"
#include "cata_path.h"
#include "city.h"
#include "creature_tracker.h"
#include "debug.h"
#include "faction.h"
#include "hash_utils.h"
#include "input.h"
#include "json.h"
#include "json_loader.h"
#include "kill_tracker.h"
#include "map.h"
#include "messages.h"
#include "mission.h"
#include "mongroup.h"
#include "monster.h"
#include "npc.h"
#include "omdata.h"
#include "options.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "overmap_types.h"
#include "path_info.h"
#include "regional_settings.h"
#include "scent_map.h"
#include "stats_tracker.h"
#include "timed_event.h"
Classes
struct mongroup_bin_eq
struct mongroup_hash
Functions
static size_t chkversion (std::istream &fin)
template<typename MdArray >
static void unserialize_array_from_compacted_sequence (JsonArray &ja, MdArray &array)
template<typename MdArray >
static void serialize_array_to_compacted_sequence (JsonOut &json, const MdArray &array)
Variables
static const oter_str_id oter_forest ("forest")
static const oter_str_id oter_forest_thick ("forest_thick")
static const oter_str_id oter_lake_bed ("lake_bed")
static const oter_str_id oter_lake_shore ("lake_shore")
static const oter_str_id oter_lake_surface ("lake_surface")
static const oter_str_id oter_lake_water_cube ("lake_water_cube")
static const oter_str_id oter_ocean_bed ("ocean_bed")
static const oter_str_id oter_ocean_shore ("ocean_shore")
static const oter_str_id oter_ocean_surface ("ocean_surface")
static const oter_str_id oter_ocean_water_cube ("ocean_water_cube")
static const oter_str_id oter_omt_obsolete ("omt_obsolete")
static const string_id< overmap_connection > overmap_connection_local_road ("local_road")
const int savegame_version = 33
int savegame_loading_version = savegame_version
Function Documentation
chkversion()
static size_t chkversion (std::istream & fin) static
Definition at line 185 of file savegame.cpp.
 {
     if( fin.peek() == '#' ) {
         std::string vline;
         getline( fin, vline );
         std::string tmphash;
         std::string tmpver;
         int savedver = -1;
         std::stringstream vliness( vline );
         vliness >> tmphash >> tmpver >> savedver;
         if( tmpver == "version" && savedver != -1 ) {
             savegame_loading_version = savedver;
         }
     }
     return fin.tellg();
 }
References savegame_loading_version.
Referenced by npc::import_and_clean(), overmap::unserialize(), game::unserialize(), game::unserialize_master(), and overmap::unserialize_view().
serialize_array_to_compacted_sequence()
template<typename MdArray > static void serialize_array_to_compacted_sequence (JsonOut & json, const MdArray & array) static
Definition at line 983 of file savegame.cpp.
 {
     static_assert( std::is_same_v<typename MdArray::value_type, bool>,
                    "This implementation assumes bool, in that the initial value of lastval has "
                    "to not be a valid value of the content" );
     int count = 0;
     int lastval = -1;
     for( size_t j = 0; j < MdArray::size_y; ++j ) {
         for( size_t i = 0; i < MdArray::size_x; ++i ) {
             const int value = array[i][j];
             if( value != lastval ) {
                 if( count ) {
                     json.write( count );
                     json.end_array();
                 }
                 lastval = value;
                 json.start_array();
                 json.write( static_cast<bool>( value ) );
                 count = 1;
             } else {
                 count++;
             }
         }
     }
     json.write( count );
     json.end_array();
 }
References JsonOut::end_array(), JsonOut::start_array(), and JsonOut::write().
Referenced by overmap::serialize_view().
unserialize_array_from_compacted_sequence()
template<typename MdArray > static void unserialize_array_from_compacted_sequence (JsonArray & ja, MdArray & array) static
Definition at line 882 of file savegame.cpp.
 {
     int count = 0;
     using Value = typename MdArray::value_type;
     Value value = Value();
     for( size_t j = 0; j < MdArray::size_y; ++j ) {
         for( size_t i = 0; i < MdArray::size_x; ++i ) {
             if( count == 0 ) {
                 JsonArray sequence = ja.next_array();
                 sequence.read_next( value );
                 sequence.read_next( count );
                 if( sequence.size() > 2 ) {
                     sequence.throw_error( "Too many values for compacted sequence" );
                 }
             }
             count--;
             array[i][j] = value;
         }
     }
 }
References JsonArray::next_array(), JsonArray::read_next(), JsonArray::size(), and JsonArray::throw_error().
Referenced by overmap::unserialize_view().
Variable Documentation
oter_forest
const oter_str_id oter_forest("forest") ("forest") static
Referenced by overmap::unserialize_omap().
oter_forest_thick
const oter_str_id oter_forest_thick("forest_thick") ("forest_thick") static
Referenced by overmap::unserialize_omap().
oter_lake_bed
const oter_str_id oter_lake_bed("lake_bed") ("lake_bed") static
Referenced by overmap::unserialize_omap().
oter_lake_shore
const oter_str_id oter_lake_shore("lake_shore") ("lake_shore") static
Referenced by overmap::unserialize_omap().
oter_lake_surface
const oter_str_id oter_lake_surface("lake_surface") ("lake_surface") static
Referenced by overmap::unserialize_omap().
oter_lake_water_cube
const oter_str_id oter_lake_water_cube("lake_water_cube") ("lake_water_cube") static
Referenced by overmap::unserialize_omap().
oter_ocean_bed
const oter_str_id oter_ocean_bed("ocean_bed") ("ocean_bed") static
Referenced by overmap::unserialize_omap().
oter_ocean_shore
const oter_str_id oter_ocean_shore("ocean_shore") ("ocean_shore") static
Referenced by overmap::unserialize_omap().
oter_ocean_surface
const oter_str_id oter_ocean_surface("ocean_surface") ("ocean_surface") static
Referenced by overmap::unserialize_omap().
oter_ocean_water_cube
const oter_str_id oter_ocean_water_cube("ocean_water_cube") ("ocean_water_cube") static
Referenced by overmap::unserialize_omap().
oter_omt_obsolete
const oter_str_id oter_omt_obsolete("omt_obsolete") ("omt_obsolete") static
Referenced by overmap::unserialize(), and overmap::unserialize_omap().
overmap_connection_local_road
const string_id<overmap_connection> overmap_connection_local_road("local_road") ("local_road") static
Referenced by overmap::unserialize().
savegame_loading_version
int savegame_loading_version = savegame_version
Definition at line 78 of file savegame.cpp.
Referenced by chkversion(), Character::load(), Creature::load(), and game::unserialize_master().
savegame_version
const int savegame_version = 33
Definition at line 71 of file savegame.cpp.
Referenced by npc::export_to(), mapbuffer::save_quad(), game::serialize(), overmap::serialize(), game::serialize_master(), and overmap::serialize_view().