Cataclysm DDA: src/savegame_json.cpp File Reference
savegame_json.cpp File Reference
#include "enums.h"
#include "npc_favor.h"
#include <algorithm>
#include <array>
#include <bitset>
#include <climits>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <functional>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <new>
#include <numeric>
#include <optional>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "active_item_cache.h"
#include "activity_actor.h"
#include "activity_actor_definitions.h"
#include "activity_type.h"
#include "addiction.h"
#include "assign.h"
#include "auto_pickup.h"
#include "avatar.h"
#include "basecamp.h"
#include "bionics.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_io.h"
#include "cata_utility.h"
#include "cata_variant.h"
#include "character.h"
#include "character_id.h"
#include "character_martial_arts.h"
#include "clone_ptr.h"
#include "clzones.h"
#include "colony.h"
#include "computer.h"
#include "construction.h"
#include "coordinates.h"
#include "craft_command.h"
#include "creature.h"
#include "creature_tracker.h"
#include "damage.h"
#include "debug.h"
#include "dialogue_chatbin.h"
#include "effect.h"
#include "effect_source.h"
#include "event.h"
#include "event_bus.h"
#include "faction.h"
#include "field.h"
#include "field_type.h"
#include "flag.h"
#include "flat_set.h"
#include "game.h"
#include "game_constants.h"
#include "inventory.h"
#include "item.h"
#include "item_contents.h"
#include "item_factory.h"
#include "item_location.h"
#include "item_pocket.h"
#include "itype.h"
#include "json.h"
#include "kill_tracker.h"
#include "lru_cache.h"
#include "magic.h"
#include "magic_teleporter_list.h"
#include "make_static.h"
#include "map.h"
#include "map_memory.h"
#include "mapdata.h"
#include "mattack_common.h"
#include "memory_fast.h"
#include "mission.h"
#include "monster.h"
#include "morale.h"
#include "morale_types.h"
#include "mtype.h"
#include "mutation.h"
#include "npc.h"
#include "npc_class.h"
#include "options.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "player_activity.h"
#include "point.h"
#include "profession.h"
#include "proficiency.h"
#include "recipe.h"
#include "recipe_dictionary.h"
#include "relic.h"
#include "requirements.h"
#include "ret_val.h"
#include "rng.h"
#include "scenario.h"
#include "skill.h"
#include "stats_tracker.h"
#include "stomach.h"
#include "submap.h"
#include "text_snippets.h"
#include "tileray.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vitamin.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "weather.h"
Namespaces
anonymous_namespace{savegame_json.cpp}
Functions
static void serialize (const weak_ptr_fast< monster > &obj, JsonOut &jsout)
static void deserialize (weak_ptr_fast< monster > &obj, const JsonObject &data)
static tripoint read_legacy_creature_pos (const JsonObject &data)
template<typename T >
static void load_legacy_craft_data (io::JsonObjectInputArchive &archive, T &value)
template<typename T >
static void load_legacy_craft_data (io::JsonObjectOutputArchive &, T &)
void load_charge_removal_blacklist (const JsonObject &jo, const std::string_view)
void load_temperature_removal_blacklist (const JsonObject &jo, const std::string_view)
void serialize (const recipe_subset &value, JsonOut &jsout)
void deserialize (recipe_subset &value, const JsonArray &ja)
static void serialize (const item_comp &value, JsonOut &jsout)
static void serialize (const tool_comp &value, JsonOut &jsout)
static void deserialize (item_comp &value, const JsonObject &jo)
static void deserialize (tool_comp &value, const JsonObject &jo)
static void serialize (const quality_requirement &value, JsonOut &jsout)
static void deserialize (quality_requirement &value, const JsonObject &jo)
void anonymous_namespace{savegame_json.cpp}::_write_rle_terrain (JsonOut &jsout, const std::string_view ter, int num)
Variables
static const activity_id ACT_FETCH_REQUIRED ("ACT_FETCH_REQUIRED")
static const activity_id ACT_MIGRATION_CANCEL ("ACT_MIGRATION_CANCEL")
static const anatomy_id anatomy_human_anatomy ("human_anatomy")
static const efftype_id effect_riding ("riding")
static const itype_id itype_internal_battery_compartment ("internal_battery_compartment")
static const itype_id itype_internal_ethanol_tank ("internal_ethanol_tank")
static const itype_id itype_internal_gasoline_tank ("internal_gasoline_tank")
static const itype_id itype_internal_oil_tank ("internal_oil_tank")
static const itype_id itype_rad_badge ("rad_badge")
static const itype_id itype_radio ("radio")
static const itype_id itype_radio_on ("radio_on")
static const itype_id itype_usb_drive ("usb_drive")
static const matype_id style_none ("style_none")
static const mfaction_str_id monfaction_factionless ("factionless")
static const mtype_id mon_breather ("mon_breather")
static const skill_id skill_chemistry ("chemistry")
static const ter_str_id ter_t_ash ("t_ash")
static const ter_str_id ter_t_dirt ("t_dirt")
static const ter_str_id ter_t_pwr_sb_support_l ("t_pwr_sb_support_l")
static const ter_str_id ter_t_pwr_sb_switchgear_l ("t_pwr_sb_switchgear_l")
static const ter_str_id ter_t_pwr_sb_switchgear_s ("t_pwr_sb_switchgear_s")
static const ter_str_id ter_t_rubble ("t_rubble")
static const ter_str_id ter_t_support_l ("t_support_l")
static const ter_str_id ter_t_switchgear_l ("t_switchgear_l")
static const ter_str_id ter_t_switchgear_s ("t_switchgear_s")
static const ter_str_id ter_t_wreckage ("t_wreckage")
static const std::array< std::string, static_cast< size_t > object_type::NUM_OBJECT_TYPES)> obj_type_name
static std::set< itype_id > charge_removal_blacklist
static std::set< itype_id > temperature_removal_blacklist
static std::unordered_map< ter_str_id, std::pair< ter_str_id, furn_str_id > > ter_migrations
static std::unordered_map< furn_str_id, std::pair< ter_str_id, furn_str_id > > furn_migrations
Function Documentation
deserialize() [1/5]
static void deserialize (item_comp & value, const JsonObject & jo) static
Definition at line 4242 of file savegame_json.cpp.
 {
     jo.allow_omitted_members();
     jo.read( "type", value.type );
     jo.read( "count", value.count );
     jo.read( "recoverable", value.recoverable );
 }
References JsonObject::allow_omitted_members(), component::count, JsonObject::read(), component::recoverable, and component::type.
deserialize() [2/5]
static void deserialize (quality_requirement & value, const JsonObject & jo) static
Definition at line 4269 of file savegame_json.cpp.
 {
     jo.allow_omitted_members();
     jo.read( "type", value.type );
     jo.read( "count", value.count );
     jo.read( "level", value.level );
 }
References JsonObject::allow_omitted_members(), quality_requirement::count, quality_requirement::level, JsonObject::read(), and quality_requirement::type.
deserialize() [3/5]
void deserialize (recipe_subset & value, const JsonArray & ja)
Definition at line 4206 of file savegame_json.cpp.
 {
     value.clear();
     for( std::string && recipe_id_string : ja ) {
         recipe_id rid( std::move( recipe_id_string ) );
         if( !rid.is_valid() ) {
             DebugLog( DebugLevel::D_WARNING, DebugClass::D_MAIN )
                     << "recipe_subset deserialized invalid recipe_id '" << rid.str() << "'";
             rid = recipe_id::NULL_ID();
         }
         value.include( &rid.obj() );
     }
 }
References recipe_subset::clear(), D_MAIN, D_WARNING, DebugLog(), recipe_subset::include(), string_id< T >::is_valid(), string_id< recipe >::NULL_ID(), string_id< T >::obj(), and string_id< T >::str().
deserialize() [4/5]
static void deserialize (tool_comp & value, const JsonObject & jo) static
Definition at line 4250 of file savegame_json.cpp.
 {
     jo.allow_omitted_members();
     jo.read( "type", value.type );
     jo.read( "count", value.count );
     jo.read( "recoverable", value.recoverable );
 }
References JsonObject::allow_omitted_members(), component::count, JsonObject::read(), component::recoverable, and component::type.
deserialize() [5/5]
static void deserialize (weak_ptr_fast< monster > & obj, const JsonObject & data) static
Definition at line 192 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     tripoint_abs_ms temp_pos;
     obj.reset();
     if( data.read( "monster_at", temp_pos ) ) {
         const auto monp = g->critter_tracker->find( temp_pos );
         if( monp == nullptr ) {
             debugmsg( "no monster found at %s", temp_pos.to_string_writable() );
             return;
         }
         obj = monp;
     }
     // TODO: if monsters/Creatures ever get unique ids,
     // look for a differently named member, e.g.
     //     data.read( "unique_id", unique_id );
     //     obj = g->id_registry->from_id( unique_id)
     //    }
 }
References JsonObject::allow_omitted_members(), debugmsg, g, int_id< T >::obj(), JsonObject::read(), and coords::coord_point_base< Point >::to_string_writable().
load_charge_removal_blacklist()
void load_charge_removal_blacklist (const JsonObject & jo, const std::string_view src)
Definition at line 2793 of file savegame_json.cpp.
 {
     jo.allow_omitted_members();
     std::set<itype_id> new_blacklist;
     jo.read( "list", new_blacklist );
     charge_removal_blacklist.insert( new_blacklist.begin(), new_blacklist.end() );
 }
References JsonObject::allow_omitted_members(), charge_removal_blacklist, and JsonObject::read().
Referenced by DynamicDataLoader::initialize().
load_legacy_craft_data() [1/2]
template<typename T > static void load_legacy_craft_data (io::JsonObjectInputArchive & archive, T & value) static
Definition at line 2776 of file savegame_json.cpp.
 {
     archive.allow_omitted_members();
     if( archive.has_member( "making" ) ) {
         value = cata::make_value<typename T::element_type>();
         value->deserialize( archive );
     }
 }
References JsonObject::allow_omitted_members(), and JsonObject::has_member().
Referenced by item::io().
load_legacy_craft_data() [2/2]
template<typename T > static void load_legacy_craft_data (io::JsonObjectOutputArchive & , T &) static
Definition at line 2787 of file savegame_json.cpp.
 {
 }
load_temperature_removal_blacklist()
void load_temperature_removal_blacklist (const JsonObject & jo, const std::string_view src)
Definition at line 2803 of file savegame_json.cpp.
 {
     jo.allow_omitted_members();
     std::set<itype_id> new_blacklist;
     jo.read( "list", new_blacklist );
     temperature_removal_blacklist.insert( new_blacklist.begin(), new_blacklist.end() );
 }
References JsonObject::allow_omitted_members(), JsonObject::read(), and temperature_removal_blacklist.
Referenced by DynamicDataLoader::initialize().
read_legacy_creature_pos()
static tripoint read_legacy_creature_pos (const JsonObject & data) static
Definition at line 216 of file savegame_json.cpp.
 {
     tripoint pos;
     if( !data.read( "posx", pos.x ) || !data.read( "posy", pos.y ) || !data.read( "posz", pos.z ) ) {
         debugmsg( R"(Bad Creature JSON: neither "location" nor "posx", "posy", "posz" found)" );
     }
     return pos;
 }
References debugmsg, math_opers::pos(), and JsonObject::read().
Referenced by avatar::load(), monster::load(), and npc::load().
serialize() [1/5]
static void serialize (const item_comp & value, JsonOut & jsout) static
Definition at line 4220 of file savegame_json.cpp.
 {
     jsout.start_object();
     jsout.member( "type", value.type );
     jsout.member( "count", value.count );
     jsout.member( "recoverable", value.recoverable );
     jsout.end_object();
 }
References component::count, JsonOut::end_object(), JsonOut::member(), component::recoverable, JsonOut::start_object(), and component::type.
serialize() [2/5]
static void serialize (const quality_requirement & value, JsonOut & jsout) static
Definition at line 4258 of file savegame_json.cpp.
 {
     jsout.start_object();
     jsout.member( "type", value.type );
     jsout.member( "count", value.count );
     jsout.member( "level", value.level );
     jsout.end_object();
 }
References quality_requirement::count, JsonOut::end_object(), quality_requirement::level, JsonOut::member(), JsonOut::start_object(), and quality_requirement::type.
serialize() [3/5]
void serialize (const recipe_subset & value, JsonOut & jsout)
Definition at line 4197 of file savegame_json.cpp.
 {
     jsout.start_array();
     for( const recipe * const &entry : value ) {
         jsout.write( entry->ident() );
     }
     jsout.end_array();
 }
References JsonOut::end_array(), JsonOut::start_array(), and JsonOut::write().
serialize() [4/5]
static void serialize (const tool_comp & value, JsonOut & jsout) static
Definition at line 4231 of file savegame_json.cpp.
 {
     jsout.start_object();
     jsout.member( "type", value.type );
     jsout.member( "count", value.count );
     jsout.member( "recoverable", value.recoverable );
     jsout.end_object();
 }
References component::count, JsonOut::end_object(), JsonOut::member(), component::recoverable, JsonOut::start_object(), and component::type.
serialize() [5/5]
static void serialize (const weak_ptr_fast< monster > & obj, JsonOut & jsout) static
Definition at line 176 of file savegame_json.cpp.
 {
     if( const auto monster_ptr = obj.lock() ) {
         jsout.start_object();
         jsout.member( "monster_at", monster_ptr->get_location() );
         // TODO: if monsters/Creatures ever get unique ids,
         // create a differently named member, e.g.
         //     jsout.member("unique_id", monster_ptr->getID());
         jsout.end_object();
     } else {
         // Monster went away. It's up the activity handler to detect this.
         jsout.write_null();
     }
 }
References JsonOut::end_object(), JsonOut::member(), int_id< T >::obj(), JsonOut::start_object(), and JsonOut::write_null().
Variable Documentation
ACT_FETCH_REQUIRED
const activity_id ACT_FETCH_REQUIRED("ACT_FETCH_REQUIRED") ("ACT_FETCH_REQUIRED") static
Referenced by Character::load(), and Character::store().
ACT_MIGRATION_CANCEL
const activity_id ACT_MIGRATION_CANCEL("ACT_MIGRATION_CANCEL") ("ACT_MIGRATION_CANCEL") static
Referenced by player_activity::deserialize().
anatomy_human_anatomy
const anatomy_id anatomy_human_anatomy("human_anatomy") ("human_anatomy") static
Referenced by Character::load().
charge_removal_blacklist
std::set<itype_id> charge_removal_blacklist static
Definition at line 2791 of file savegame_json.cpp.
Referenced by item::io(), and load_charge_removal_blacklist().
effect_riding
const efftype_id effect_riding("riding") ("riding") static
Referenced by Character::load().
furn_migrations
std::unordered_map<furn_str_id, std::pair<ter_str_id, furn_str_id> > furn_migrations static
Definition at line 4622 of file savegame_json.cpp.
Referenced by ter_furn_migrations::check(), ter_furn_migrations::load(), submap::load(), and ter_furn_migrations::reset().
itype_internal_battery_compartment
const itype_id itype_internal_battery_compartment("internal_battery_compartment") ("internal_battery_compartment") static
Referenced by Character::load().
itype_internal_ethanol_tank
const itype_id itype_internal_ethanol_tank("internal_ethanol_tank") ("internal_ethanol_tank") static
Referenced by Character::load().
itype_internal_gasoline_tank
const itype_id itype_internal_gasoline_tank("internal_gasoline_tank") ("internal_gasoline_tank") static
Referenced by Character::load().
itype_internal_oil_tank
const itype_id itype_internal_oil_tank("internal_oil_tank") ("internal_oil_tank") static
Referenced by Character::load().
itype_rad_badge
const itype_id itype_rad_badge("rad_badge") ("rad_badge") static
Referenced by item::io().
itype_radio
const itype_id itype_radio("radio") ("radio") static
Referenced by item::io().
itype_radio_on
const itype_id itype_radio_on("radio_on") ("radio_on") static
Referenced by item::io().
itype_usb_drive
const itype_id itype_usb_drive("usb_drive") ("usb_drive") static
Referenced by item::migrate_content_item().
mon_breather
const mtype_id mon_breather("mon_breather") ("mon_breather") static
Referenced by monster::load().
monfaction_factionless
const mfaction_str_id monfaction_factionless("factionless") ("factionless") static
Referenced by monster::load().
obj_type_name
const std::array<std::string, static_cast<size_t> object_type::NUM_OBJECT_TYPES)> obj_type_name static
Initial value:
= { { "OBJECT_NONE", "OBJECT_ITEM", "OBJECT_ACTOR", "OBJECT_PLAYER",
        "OBJECT_NPC", "OBJECT_MONSTER", "OBJECT_VEHICLE", "OBJECT_TRAP", "OBJECT_FIELD",
        "OBJECT_TERRAIN", "OBJECT_FURNITURE"
    }
}
Definition at line 169 of file savegame_json.cpp.
Referenced by avatar::load(), and avatar::store().
skill_chemistry
const skill_id skill_chemistry("chemistry") ("chemistry") static
Referenced by Character::load().
style_none
const matype_id style_none("style_none") ("style_none") static
Referenced by Character::load().
temperature_removal_blacklist
std::set<itype_id> temperature_removal_blacklist static
Definition at line 2801 of file savegame_json.cpp.
Referenced by item::io(), and load_temperature_removal_blacklist().
ter_migrations
std::unordered_map<ter_str_id, std::pair<ter_str_id, furn_str_id> > ter_migrations static
Definition at line 4621 of file savegame_json.cpp.
Referenced by ter_furn_migrations::check(), ter_furn_migrations::load(), submap::load(), and ter_furn_migrations::reset().
ter_t_ash
const ter_str_id ter_t_ash("t_ash") ("t_ash") static
Referenced by submap::load().
ter_t_dirt
const ter_str_id ter_t_dirt("t_dirt") ("t_dirt") static
Referenced by submap::load().
ter_t_pwr_sb_support_l
const ter_str_id ter_t_pwr_sb_support_l("t_pwr_sb_support_l") ("t_pwr_sb_support_l") static
Referenced by submap::load().
ter_t_pwr_sb_switchgear_l
const ter_str_id ter_t_pwr_sb_switchgear_l("t_pwr_sb_switchgear_l") ("t_pwr_sb_switchgear_l") static
Referenced by submap::load().
ter_t_pwr_sb_switchgear_s
const ter_str_id ter_t_pwr_sb_switchgear_s("t_pwr_sb_switchgear_s") ("t_pwr_sb_switchgear_s") static
Referenced by submap::load().
ter_t_rubble
const ter_str_id ter_t_rubble("t_rubble") ("t_rubble") static
Referenced by submap::load().
ter_t_support_l
const ter_str_id ter_t_support_l("t_support_l") ("t_support_l") static
Referenced by submap::load().
ter_t_switchgear_l
const ter_str_id ter_t_switchgear_l("t_switchgear_l") ("t_switchgear_l") static
Referenced by submap::load().
ter_t_switchgear_s
const ter_str_id ter_t_switchgear_s("t_switchgear_s") ("t_switchgear_s") static
Referenced by submap::load().
ter_t_wreckage
const ter_str_id ter_t_wreckage("t_wreckage") ("t_wreckage") static
Referenced by submap::load().