Cataclysm DDA: src/scenario.h File Reference
scenario.h File Reference
#include <iosfwd>
#include <set>
#include <string>
#include <vector>
#include "calendar.h"
#include "effect_on_condition.h"
#include "translations.h"
#include "type_id.h"
Classes
class scenario
struct scen_blacklist
Macros
#define CATA_SRC_SCENARIO_H
Functions
void reset_scenarios_blacklist ()
const scenario * get_scenario ()
void set_scenario (const scenario *new_scenario)
Macro Definition Documentation
CATA_SRC_SCENARIO_H
#define CATA_SRC_SCENARIO_H
Definition at line 3 of file scenario.h.
Function Documentation
get_scenario()
const scenario* get_scenario ()
Definition at line 156 of file game.cpp.
 {
     return g->scen;
 }
Referenced by Character::add_traits(), char_creation::draw_age(), char_creation::draw_location(), Character::get_random_trait(), avatar::initialize(), avatar::load(), effect_on_conditions::load_new_character(), main_menu::opening_screen(), avatar::randomize(), avatar::randomize_hobbies(), set_description(), set_hobbies(), set_profession(), set_scenario(), set_traits(), skill_points_used(), avatar::store(), and trait_points_used().
reset_scenarios_blacklist()
void reset_scenarios_blacklist ()
Definition at line 401 of file scenario.cpp.
 {
     sc_blacklist.scenarios.clear();
     sc_blacklist.whitelist = false;
 }
References sc_blacklist, scen_blacklist::scenarios, and scen_blacklist::whitelist.
Referenced by scen_blacklist::load(), and DynamicDataLoader::unload_data().
set_scenario()
void set_scenario (const scenario * new_scenario)
Definition at line 157 of file game.cpp.
 {
     g->scen = new_scenario;
 }
Referenced by avatar::load().