Cataclysm DDA: src/scent_map.h File Reference
scent_map.h File Reference
#include <array>
#include <iosfwd>
#include <optional>
#include <set>
#include <vector>
#include "calendar.h"
#include "enums.h"
#include "game_constants.h"
#include "point.h"
#include "type_id.h"
Classes
class scent_type
class scent_map
Namespaces
catacurses
Contains the curses interface used by the whole game.
Macros
#define CATA_SRC_SCENT_MAP_H
Functions
scent_map & get_scent ()
Variables
constexpr int SCENT_MAP_Z_REACH = 1
Macro Definition Documentation
CATA_SRC_SCENT_MAP_H
#define CATA_SRC_SCENT_MAP_H
Definition at line 3 of file scent_map.h.
Function Documentation
get_scent()
scent_map& get_scent ()
Definition at line 159 of file game.cpp.
 {
     return g->scent;
 }
Referenced by map::decay_fields_and_scent(), tutorial_game::init(), map::process_fields_in_submap(), monster::scent_move(), Character::update_type_of_scent(), editmap::update_view_with_help(), and monster::will_reach().
Variable Documentation
SCENT_MAP_Z_REACH
constexpr int SCENT_MAP_Z_REACH = 1 constexpr
Definition at line 19 of file scent_map.h.
Referenced by scent_map::inbounds(), and monster::scent_move().