Cataclysm DDA: src/scenario.cpp File Reference
scenario.cpp File Reference
#include "scenario.h"
#include <algorithm>
#include <cstdlib>
#include "achievement.h"
#include "debug.h"
#include "generic_factory.h"
#include "json.h"
#include "map_extras.h"
#include "mission.h"
#include "mutation.h"
#include "options.h"
#include "past_games_info.h"
#include "past_achievements_info.h"
#include "profession.h"
#include "rng.h"
#include "start_location.h"
#include "string_id.h"
#include "translations.h"
Namespaces
anonymous_namespace{scenario.cpp}
Functions
static void check_traits (const std::set< trait_id > &traits, const string_id< scenario > &ident)
void reset_scenarios_blacklist ()
Variables
static const achievement_id achievement_achievement_arcade_mode ("achievement_arcade_mode")
generic_factory< scenario > anonymous_namespace{scenario.cpp}::all_scenarios ("scenario")
static scen_blacklist sc_blacklist
Function Documentation
check_traits()
static void check_traits (const std::set< trait_id > & traits, const string_id< scenario > & ident) static
Definition at line 224 of file scenario.cpp.
 {
     for( const auto &t : traits ) {
         if( !t.is_valid() ) {
             debugmsg( "trait %s for scenario %s does not exist", t.c_str(), ident.c_str() );
         }
     }
 }
References string_id< T >::c_str(), and debugmsg.
Referenced by scenario::check_definition().
reset_scenarios_blacklist()
void reset_scenarios_blacklist ()
Definition at line 401 of file scenario.cpp.
 {
     sc_blacklist.scenarios.clear();
     sc_blacklist.whitelist = false;
 }
References sc_blacklist, scen_blacklist::scenarios, and scen_blacklist::whitelist.
Referenced by scen_blacklist::load(), and DynamicDataLoader::unload_data().
Variable Documentation
achievement_achievement_arcade_mode
const achievement_id achievement_achievement_arcade_mode("achievement_arcade_mode") ("achievement_arcade_mode") static
Referenced by scenario::can_pick().
sc_blacklist
scen_blacklist sc_blacklist static
Definition at line 43 of file scenario.cpp.
Referenced by scenario::finalize(), scen_blacklist::finalize(), scen_blacklist::load_scen_blacklist(), reset_scenarios_blacklist(), and scenario::scen_is_blacklisted().