Cataclysm DDA: src/sdl_utils.h File Reference
sdl_utils.h File Reference
#include <algorithm>
#include <cmath>
#include <string>
#include <unordered_map>
#include <vector>
#include "color.h"
#include "options.h"
#include "sdl_wrappers.h"
Macros
#define CATA_SRC_SDL_UTILS_H
Typedefs
using color_pixel_function_pointer = SDL_Color(*)(const SDL_Color &color)
using color_pixel_function_map = std::unordered_map< std::string, color_pixel_function_pointer >
Functions
color_pixel_function_pointer get_color_pixel_function (const std::string &name)
SDL_Color adjust_color_brightness (const SDL_Color &color, int percent)
SDL_Color mix_colors (const SDL_Color &first, const SDL_Color &second, int second_percent)
bool is_black (const SDL_Color &color)
Uint8 average_pixel_color (const SDL_Color &color)
SDL_Color color_pixel_grayscale (const SDL_Color &color)
SDL_Color color_pixel_nightvision (const SDL_Color &color)
SDL_Color color_pixel_overexposed (const SDL_Color &color)
SDL_Color color_pixel_darken (const SDL_Color &color)
SDL_Color color_pixel_mixer (const SDL_Color &color, const float &gammav, const SDL_Color &color_a, const SDL_Color &color_b)
SDL_Color color_pixel_sepia_light (const SDL_Color &color)
SDL_Color color_pixel_sepia_dark (const SDL_Color &color)
SDL_Color color_pixel_blue_dark (const SDL_Color &color)
SDL_Color color_pixel_custom (const SDL_Color &color)
SDL_Color curses_color_to_SDL (const nc_color &color)
SDL_Surface_Ptr create_surface_32 (int w, int h)
SDL_Rect fit_rect_inside (const SDL_Rect &inner, const SDL_Rect &outer)
std::vector< SDL_Color > color_linear_interpolate (const SDL_Color &start_color, const SDL_Color &end_color, unsigned additional_steps)
Linearly interpolate intermediate colors between two given colors.
Macro Definition Documentation
CATA_SRC_SDL_UTILS_H
#define CATA_SRC_SDL_UTILS_H
Definition at line 3 of file sdl_utils.h.
Typedef Documentation
color_pixel_function_map
using color_pixel_function_map = std::unordered_map<std::string, color_pixel_function_pointer>
Definition at line 16 of file sdl_utils.h.
color_pixel_function_pointer
using color_pixel_function_pointer = SDL_Color(*)(const SDL_Color &color)
Definition at line 15 of file sdl_utils.h.
Function Documentation
adjust_color_brightness()
SDL_Color adjust_color_brightness (const SDL_Color & color, int percent)
average_pixel_color()
Uint8 average_pixel_color (const SDL_Color & color) inline
Definition at line 32 of file sdl_utils.h.
 {
     return 85 * ( color.r + color.g + color.b ) >> 8; // 85/256 ~ 1/3
 }
References color().
color_linear_interpolate()
std::vector<SDL_Color> color_linear_interpolate (const SDL_Color & start_color, const SDL_Color & end_color, unsigned additional_steps)
Linearly interpolate intermediate colors between two given colors.
Parameters
start_color The color to start with.
end_color The color that ends the interpolation.
additional_steps Number of steps between the start and stop colors.
Returns
A vector of colors containing: the start color, all intermediate colors and finally the end color.
Note
start with white (r=255, g=255, b=255) and end with blue (r=0, g=0, b=255) and use 2 additional steps:
The first intermediate color is: (r=170, g=170, b=255)
The second intermediate color is: (r=85, g=85, b=255) Obviously the more intermediate steps there are, the harder it is to differentiate the intermediate colors.
color_pixel_blue_dark()
SDL_Color color_pixel_blue_dark (const SDL_Color & color) inline
Definition at line 58 of file sdl_utils.h.
 {
     const SDL_Color dark = { 19, 23, 39, color.a };
     const SDL_Color light = { 60, 66, 70, color.a };
     return color_pixel_mixer( color, 1.0f, dark, light );
 }
References color(), color_pixel_mixer(), and light.
color_pixel_custom()
SDL_Color color_pixel_custom (const SDL_Color & color) inline
Definition at line 65 of file sdl_utils.h.
 {
     const SDL_Color dark = { static_cast<Uint8>( get_option<int>( "MEMORY_RGB_DARK_RED" ) ), static_cast<Uint8>( get_option<int>( "MEMORY_RGB_DARK_GREEN" ) ), static_cast<Uint8>( get_option<int>( "MEMORY_RGB_DARK_BLUE" ) ), color.a };
     const SDL_Color light = { static_cast<Uint8>( get_option<int>( "MEMORY_RGB_BRIGHT_RED" ) ), static_cast<Uint8>( get_option<int>( "MEMORY_RGB_BRIGHT_GREEN" ) ), static_cast<Uint8>( get_option<int>( "MEMORY_RGB_BRIGHT_BLUE" ) ), color.a };
     return color_pixel_mixer( color, get_option<float>( "MEMORY_GAMMA" ), dark, light );
 }
References color(), color_pixel_mixer(), and light.
color_pixel_darken()
SDL_Color color_pixel_darken (const SDL_Color & color)
color_pixel_grayscale()
SDL_Color color_pixel_grayscale (const SDL_Color & color)
color_pixel_mixer()
SDL_Color color_pixel_mixer (const SDL_Color & color, const float & gammav, const SDL_Color & color_a, const SDL_Color & color_b)
Referenced by color_pixel_blue_dark(), color_pixel_custom(), color_pixel_sepia_dark(), and color_pixel_sepia_light().
color_pixel_nightvision()
SDL_Color color_pixel_nightvision (const SDL_Color & color)
color_pixel_overexposed()
SDL_Color color_pixel_overexposed (const SDL_Color & color)
color_pixel_sepia_dark()
SDL_Color color_pixel_sepia_dark (const SDL_Color & color) inline
Definition at line 51 of file sdl_utils.h.
 {
     const SDL_Color dark = { 39, 23, 19, color.a };
     const SDL_Color light = { 70, 66, 60, color.a };
     return color_pixel_mixer( color, 1.0f, dark, light );
 }
References color(), color_pixel_mixer(), and light.
color_pixel_sepia_light()
SDL_Color color_pixel_sepia_light (const SDL_Color & color) inline
Definition at line 44 of file sdl_utils.h.
 {
     const SDL_Color dark = { 39, 23, 19, color.a };
     const SDL_Color light = { 241, 220, 163, color.a };
     return color_pixel_mixer( color, 1.6f, dark, light );
 }
References color(), color_pixel_mixer(), and light.
create_surface_32()
SDL_Surface_Ptr create_surface_32 (int w, int h)
Exceptions
std::exception upon errors.
Returns
Always a valid pointer.
curses_color_to_SDL()
SDL_Color curses_color_to_SDL (const nc_color & color)
Referenced by cataimgui::window::draw_colored_text(), and game_ui::init_ui().
fit_rect_inside()
SDL_Rect fit_rect_inside (const SDL_Rect & inner, const SDL_Rect & outer)
get_color_pixel_function()
color_pixel_function_pointer get_color_pixel_function (const std::string & name)
is_black()
bool is_black (const SDL_Color & color) inline
Definition at line 24 of file sdl_utils.h.
 {
     return
         color.r == 0x00 &&
         color.g == 0x00 &&
         color.b == 0x00;
 }
References color().
mix_colors()
SDL_Color mix_colors (const SDL_Color & first, const SDL_Color & second, int second_percent)