Cataclysm DDA: src/sdl_wrappers.h File Reference
sdl_wrappers.h File Reference
#include <SDL.h>
#include <SDL_image.h>
#include <SDL_ttf.h>
#include <memory>
Classes
struct SDL_Renderer_deleter
struct SDL_Window_deleter
struct SDL_PixelFormat_deleter
struct SDL_Texture_deleter
struct SDL_Surface_deleter
struct TTF_Font_deleter
Macros
#define CATA_SRC_SDL_WRAPPERS_H
#define SDL_MAIN_HANDLED
Typedefs
using SDL_Renderer_Ptr = std::unique_ptr< SDL_Renderer, SDL_Renderer_deleter >
using SDL_Window_Ptr = std::unique_ptr< SDL_Window, SDL_Window_deleter >
using SDL_PixelFormat_Ptr = std::unique_ptr< SDL_PixelFormat, SDL_PixelFormat_deleter >
using SDL_Texture_Ptr = std::unique_ptr< SDL_Texture, SDL_Texture_deleter >
using SDL_Surface_Ptr = std::unique_ptr< SDL_Surface, SDL_Surface_deleter >
using TTF_Font_Ptr = std::unique_ptr< TTF_Font, TTF_Font_deleter >
Functions
bool printErrorIf (bool condition, const char *message)
If the condition is true, an error (including the given message and the output of SDL_GetError) is logged to the debug log.
void throwErrorIf (bool condition, const char *message)
If the condition is true, an exception (including the given message and the output of SDL_GetError) is thrown.
void StartTextInput ()
void StopTextInput ()
void RenderCopy (const SDL_Renderer_Ptr &renderer, const SDL_Texture_Ptr &texture, const SDL_Rect *srcrect, const SDL_Rect *dstrect)
Wrappers for SDL functions that does error reporting and that accept our wrapped pointers.
SDL_Texture_Ptr CreateTexture (const SDL_Renderer_Ptr &renderer, Uint32 format, int access, int w, int h)
SDL_Texture_Ptr CreateTextureFromSurface (const SDL_Renderer_Ptr &renderer, const SDL_Surface_Ptr &surface)
void SetRenderDrawColor (const SDL_Renderer_Ptr &renderer, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
void RenderDrawPoint (const SDL_Renderer_Ptr &renderer, const point &p)
void RenderFillRect (const SDL_Renderer_Ptr &renderer, const SDL_Rect *rect)
void FillRect (const SDL_Surface_Ptr &surface, const SDL_Rect *rect, Uint32 color)
void SetTextureBlendMode (const SDL_Texture_Ptr &texture, SDL_BlendMode blendMode)
bool SetTextureColorMod (const SDL_Texture_Ptr &texture, Uint32 r, Uint32 g, Uint32 b)
void SetRenderDrawBlendMode (const SDL_Renderer_Ptr &renderer, SDL_BlendMode blendMode)
void GetRenderDrawBlendMode (const SDL_Renderer_Ptr &renderer, SDL_BlendMode &blend_mode)
SDL_Surface_Ptr load_image (const char *path)
void SetRenderTarget (const SDL_Renderer_Ptr &renderer, const SDL_Texture_Ptr &texture)
void RenderClear (const SDL_Renderer_Ptr &renderer)
SDL_Surface_Ptr CreateRGBSurface (Uint32 flags, int width, int height, int depth, Uint32 Rmask, Uint32 Gmask, Uint32 Bmask, Uint32 Amask)
bool operator== (const SDL_Color &lhs, const SDL_Color &rhs)
Comparison operators which SDL lacks being a C-ish lib.
bool operator!= (const SDL_Color &lhs, const SDL_Color &rhs)
bool operator== (const SDL_Rect &lhs, const SDL_Rect &rhs)
bool operator!= (const SDL_Rect &lhs, const SDL_Rect &rhs)
Macro Definition Documentation
CATA_SRC_SDL_WRAPPERS_H
#define CATA_SRC_SDL_WRAPPERS_H
Definition at line 3 of file sdl_wrappers.h.
SDL_MAIN_HANDLED
#define SDL_MAIN_HANDLED
Definition at line 6 of file sdl_wrappers.h.
Typedef Documentation
SDL_PixelFormat_Ptr
using SDL_PixelFormat_Ptr = std::unique_ptr<SDL_PixelFormat, SDL_PixelFormat_deleter>
Definition at line 46 of file sdl_wrappers.h.
SDL_Renderer_Ptr
using SDL_Renderer_Ptr = std::unique_ptr<SDL_Renderer, SDL_Renderer_deleter>
Definition at line 32 of file sdl_wrappers.h.
SDL_Surface_Ptr
using SDL_Surface_Ptr = std::unique_ptr<SDL_Surface, SDL_Surface_deleter>
Definition at line 60 of file sdl_wrappers.h.
SDL_Texture_Ptr
using SDL_Texture_Ptr = std::unique_ptr<SDL_Texture, SDL_Texture_deleter>
Definition at line 53 of file sdl_wrappers.h.
SDL_Window_Ptr
using SDL_Window_Ptr = std::unique_ptr<SDL_Window, SDL_Window_deleter>
Definition at line 39 of file sdl_wrappers.h.
TTF_Font_Ptr
using TTF_Font_Ptr = std::unique_ptr<TTF_Font, TTF_Font_deleter>
Definition at line 67 of file sdl_wrappers.h.
Function Documentation
CreateRGBSurface()
SDL_Surface_Ptr CreateRGBSurface (Uint32 flags, int width, int height, int depth, Uint32 Rmask, Uint32 Gmask, Uint32 Bmask, Uint32 Amask)
CreateTexture()
SDL_Texture_Ptr CreateTexture (const SDL_Renderer_Ptr & renderer, Uint32 format, int access, int w, int h)
CreateTextureFromSurface()
SDL_Texture_Ptr CreateTextureFromSurface (const SDL_Renderer_Ptr & renderer, const SDL_Surface_Ptr & surface)
FillRect()
void FillRect (const SDL_Surface_Ptr & surface, const SDL_Rect * rect, Uint32 color)
GetRenderDrawBlendMode()
void GetRenderDrawBlendMode (const SDL_Renderer_Ptr & renderer, SDL_BlendMode & blend_mode)
load_image()
SDL_Surface_Ptr load_image (const char * path)
operator!=() [1/2]
bool operator!= (const SDL_Color & lhs, const SDL_Color & rhs) inline
Definition at line 127 of file sdl_wrappers.h.
 {
     return !operator==( lhs, rhs );
 }
References operator==().
operator!=() [2/2]
bool operator!= (const SDL_Rect & lhs, const SDL_Rect & rhs) inline
Definition at line 141 of file sdl_wrappers.h.
 {
     return !operator==( lhs, rhs );
 }
References operator==().
operator==() [1/2]
bool operator== (const SDL_Color & lhs, const SDL_Color & rhs) inline
Comparison operators which SDL lacks being a C-ish lib.
Definition at line 118 of file sdl_wrappers.h.
 {
     return
         lhs.r == rhs.r &&
         lhs.g == rhs.g &&
         lhs.b == rhs.b &&
         lhs.a == rhs.a;
 }
Referenced by operator!=().
operator==() [2/2]
bool operator== (const SDL_Rect & lhs, const SDL_Rect & rhs) inline
Definition at line 132 of file sdl_wrappers.h.
 {
     return
         lhs.x == rhs.x &&
         lhs.y == rhs.y &&
         lhs.w == rhs.w &&
         lhs.h == rhs.h;
 }
printErrorIf()
bool printErrorIf (bool condition, const char * message)
If the condition is true, an error (including the given message and the output of SDL_GetError) is logged to the debug log.
Returns
condition, in other words: return whether an error was logged.
Referenced by debug_menu::game_report().
RenderClear()
void RenderClear (const SDL_Renderer_Ptr & renderer)
RenderCopy()
void RenderCopy (const SDL_Renderer_Ptr & renderer, const SDL_Texture_Ptr & texture, const SDL_Rect * srcrect, const SDL_Rect * dstrect)
Wrappers for SDL functions that does error reporting and that accept our wrapped pointers.
Errors are reported via the usual debug log stream (exceptions are noted below).
CreateTextureFromSurface returns an empty SDL_Texture_Ptr if the function fails (the failure is also logged by the function). load_image throws if the loading fails. Its input must be a valid C-String.
RenderDrawPoint()
void RenderDrawPoint (const SDL_Renderer_Ptr & renderer, const point & p)
RenderFillRect()
void RenderFillRect (const SDL_Renderer_Ptr & renderer, const SDL_Rect * rect)
SetRenderDrawBlendMode()
void SetRenderDrawBlendMode (const SDL_Renderer_Ptr & renderer, SDL_BlendMode blendMode)
SetRenderDrawColor()
void SetRenderDrawColor (const SDL_Renderer_Ptr & renderer, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
SetRenderTarget()
void SetRenderTarget (const SDL_Renderer_Ptr & renderer, const SDL_Texture_Ptr & texture)
SetTextureBlendMode()
void SetTextureBlendMode (const SDL_Texture_Ptr & texture, SDL_BlendMode blendMode)
SetTextureColorMod()
bool SetTextureColorMod (const SDL_Texture_Ptr & texture, Uint32 r, Uint32 g, Uint32 b)
StartTextInput()
void StartTextInput ()
StopTextInput()
void StopTextInput ()
Referenced by string_editor_window::query_string(), and string_input_popup::query_string().
throwErrorIf()
void throwErrorIf (bool condition, const char * message)
If the condition is true, an exception (including the given message and the output of SDL_GetError) is thrown.