Cataclysm DDA: src/sdlsound.h File Reference
sdlsound.h File Reference
#include <string>
Macros
#define CATA_SRC_SDLSOUND_H
Functions
bool init_sound ()
void shutdown_sound ()
void play_music (const std::string &)
void update_music_volume ()
void load_soundset ()
Macro Definition Documentation
CATA_SRC_SDLSOUND_H
#define CATA_SRC_SDLSOUND_H
Definition at line 3 of file sdlsound.h.
Function Documentation
init_sound()
bool init_sound () inline
Definition at line 20 of file sdlsound.h.
 {
     return false;
 }
load_soundset()
void load_soundset () inline
Definition at line 29 of file sdlsound.h.
 { }
play_music()
void play_music (const std::string &) inline
Definition at line 25 of file sdlsound.h.
 {
 }
Referenced by iuse::epic_music(), iuse::mp3_on(), and main_menu::opening_screen().
shutdown_sound()
void shutdown_sound () inline
Definition at line 24 of file sdlsound.h.
 { }
update_music_volume()
void update_music_volume () inline
Definition at line 28 of file sdlsound.h.
 { }
Referenced by options_manager::save().