Cataclysm DDA: src/sdltiles.h File Reference
sdltiles.h File Reference
#include "point.h"
Namespaces
catacurses
Contains the curses interface used by the whole game.
Macros
#define CATA_SRC_SDLTILES_H
Functions
bool window_contains_point_relative (const catacurses::window &win, const point &p)
Macro Definition Documentation
CATA_SRC_SDLTILES_H
#define CATA_SRC_SDLTILES_H
Definition at line 3 of file sdltiles.h.
Function Documentation
window_contains_point_relative()
bool window_contains_point_relative (const catacurses::window & win, const point & p)
Definition at line 4119 of file sdltiles.cpp.
 {
     const point bound = point( catacurses::getmaxx( win ), catacurses::getmaxy( win ) );
     const half_open_rectangle<point> win_bounds( point_zero, bound );
     return win_bounds.contains( p );
 }
References half_open_rectangle< Point, >::contains(), catacurses::getmaxx(), catacurses::getmaxy(), and point_zero.
Referenced by uilist::handle_mouse(), handle_player_display_action(), and inventory_selector::process_input().