Cataclysm DDA: src/shadowcasting.h File Reference
shadowcasting.h File Reference
#include <algorithm>
#include <array>
#include <cmath>
#include <functional>
#include <iosfwd>
#include "coordinates.h"
#include "game_constants.h"
#include "lightmap.h"
#include "mdarray.h"
Classes
struct four_quadrants
Macros
#define CATA_SRC_SHADOWCASTING_H
Typedefs
template<typename T >
using array_of_grids_of = std::conditional_t< std::is_const_v< T >, std::array< const cata::mdarray< std::remove_const_t< T >, point_bub_ms > *, OVERMAP_LAYERS >, std::array< cata::mdarray< T, point_bub_ms > *, OVERMAP_LAYERS > >
Enumerations
enum class quadrant : int {
NE , SE , SW , NW ,
default_ = NE
}
enum class vertical_direction { UP , DOWN , BOTH }
Functions
float sight_calc (const float &numerator, const float &transparency, const int &distance)
bool sight_check (const float &transparency, const float &)
void update_light (float &update, const float &new_value, quadrant)
void update_light_quadrants (four_quadrants &update, const float &new_value, quadrant q)
float accumulate_transparency (const float &cumulative_transparency, const float &current_transparency, const int &distance)
template<typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate>
void castLightAll (cata::mdarray< Out, point_bub_ms > &output_cache, const cata::mdarray< T, point_bub_ms > &input_array, const point &offset, int offsetDistance=0, T numerator=1.0)
template<typename T , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, T(*)(const T &, const T &, const int &) accumulate>
void cast_zlight (const array_of_grids_of< T > &output_caches, const array_of_grids_of< const T > &input_arrays, const array_of_grids_of< const bool > &floor_caches, const tripoint &origin, int offset_distance, T numerator, vertical_direction dir=vertical_direction::BOTH)
Macro Definition Documentation
CATA_SRC_SHADOWCASTING_H
#define CATA_SRC_SHADOWCASTING_H
Definition at line 3 of file shadowcasting.h.
Typedef Documentation
array_of_grids_of
template<typename T > using array_of_grids_of = std::conditional_t < std::is_const_v<T>, std::array<const cata::mdarray<std::remove_const_t<T>, point_bub_ms>*, OVERMAP_LAYERS>, std::array<cata::mdarray<T, point_bub_ms>*, OVERMAP_LAYERS> >
Definition at line 128 of file shadowcasting.h.
Enumeration Type Documentation
quadrant
enum quadrant : int strong
Enumerator
NE
SE
SW
NW
default_
Definition at line 24 of file shadowcasting.h.
                     : int {
     NE,
     SE,
     SW,
     NW,
     default_ = NE
 };
vertical_direction
enum vertical_direction strong
Enumerator
UP
DOWN
BOTH
Definition at line 32 of file shadowcasting.h.
{
     UP,
     DOWN,
     BOTH
 };
Function Documentation
accumulate_transparency()
float accumulate_transparency (const float & cumulative_transparency, const float & current_transparency, const int & distance) inline
Definition at line 112 of file shadowcasting.h.
 {
     return ( ( distance - 1 ) * cumulative_transparency + current_transparency ) / distance;
 }
Referenced by map::apply_directional_light(), map::apply_light_arc(), and map::apply_light_source().
cast_zlight()
template<typename T , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, T(*)(const T &, const T &, const int &) accumulate> void cast_zlight (const array_of_grids_of< T > & output_caches, const array_of_grids_of< const T > & input_arrays, const array_of_grids_of< const bool > & floor_caches, const tripoint & origin, int offset_distance, T numerator, vertical_direction dir = vertical_direction::BOTH)
Definition at line 529 of file shadowcasting.cpp.
 {
     if( dir == vertical_direction::DOWN || dir == vertical_direction::BOTH ) {
         // Down lateral
         // @..
         //  ..
         //   .
         cast_horizontal_zlight_segment < 0, 1, 1, 0, -1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // @
         // ..
         // ...
         cast_horizontal_zlight_segment < 1, 0, 0, 1, -1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         //   .
         //  ..
         // @..
         cast_horizontal_zlight_segment < 0, -1, 1, 0, -1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // ...
         // ..
         // @
         cast_horizontal_zlight_segment < -1, 0, 0, 1, -1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // ..@
         // ..
         // .
         cast_horizontal_zlight_segment < 0, 1, -1, 0, -1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         //   @
         //  ..
         // ...
         cast_horizontal_zlight_segment < 1, 0, 0, -1, -1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // .
         // ..
         // ..@
         cast_horizontal_zlight_segment < 0, -1, -1, 0, -1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // ...
         //  ..
         //   @
         cast_horizontal_zlight_segment < -1, 0, 0, -1, -1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // Straight down
         // @.
         // ..
         cast_vertical_zlight_segment < 1, 1, -1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // ..
         // @.
         cast_vertical_zlight_segment < 1, -1, -1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // .@
         // ..
         cast_vertical_zlight_segment < -1, 1, -1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // ..
         // .@
         cast_vertical_zlight_segment < -1, -1, -1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
     }
     if( dir == vertical_direction::UP || dir == vertical_direction::BOTH ) {
         // Up lateral
         // @..
         //  ..
         //   .
         cast_horizontal_zlight_segment < 0, 1, 1, 0, 1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // @
         // ..
         // ...
         cast_horizontal_zlight_segment < 1, 0, 0, 1, 1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // ..@
         // ..
         // .
         cast_horizontal_zlight_segment < 0, -1, 1, 0, 1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         //   @
         //  ..
         // ...
         cast_horizontal_zlight_segment < -1, 0, 0, 1, 1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         //   .
         //  ..
         // @..
         cast_horizontal_zlight_segment < 0, 1, -1, 0, 1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // ...
         // ..
         // @
         cast_horizontal_zlight_segment < 1, 0, 0, -1, 1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // .
         // ..
         // ..@
         cast_horizontal_zlight_segment < 0, -1, -1, 0, 1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // ...
         //  ..
         //   @
         cast_horizontal_zlight_segment < -1, 0, 0, -1, 1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // Straight up
         // @.
         // ..
         cast_vertical_zlight_segment < 1, 1, 1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // ..
         // @.
         cast_vertical_zlight_segment < 1, -1, 1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // .@
         // ..
         cast_vertical_zlight_segment < -1, 1, 1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
         // ..
         // .@
         cast_vertical_zlight_segment < -1, -1, 1, T, calc, is_transparent, accumulate > (
             output_caches, input_arrays, floor_caches, origin, offset_distance, numerator );
     }
 }
References BOTH, cast_horizontal_zlight_segment(), cast_vertical_zlight_segment(), DOWN, and UP.
castLightAll()
template<typename T , typename Out , T(*)(const T &, const T &, const int &) calc, bool(*)(const T &, const T &) check, void(*)(Out &, const T &, quadrant) update_output, T(*)(const T &, const T &, const int &) accumulate> void castLightAll (cata::mdarray< Out, point_bub_ms > & output_cache, const cata::mdarray< T, point_bub_ms > & input_array, const point & offset, int offsetDistance = 0, T numerator = 1.0)
Definition at line 928 of file lightmap.cpp.
 {
     castLight<0, 1, 1, 0, T, Out, calc, check, update_output, accumulate>(
         output_cache, input_array, offset, offsetDistance, numerator );
     castLight<1, 0, 0, 1, T, Out, calc, check, update_output, accumulate>(
         output_cache, input_array, offset, offsetDistance, numerator );
     castLight < 0, -1, 1, 0, T, Out, calc, check, update_output, accumulate > (
         output_cache, input_array, offset, offsetDistance, numerator );
     castLight < -1, 0, 0, 1, T, Out, calc, check, update_output, accumulate > (
         output_cache, input_array, offset, offsetDistance, numerator );
     castLight < 0, 1, -1, 0, T, Out, calc, check, update_output, accumulate > (
         output_cache, input_array, offset, offsetDistance, numerator );
     castLight < 1, 0, 0, -1, T, Out, calc, check, update_output, accumulate > (
         output_cache, input_array, offset, offsetDistance, numerator );
     castLight < 0, -1, -1, 0, T, Out, calc, check, update_output, accumulate > (
         output_cache, input_array, offset, offsetDistance, numerator );
     castLight < -1, 0, 0, -1, T, Out, calc, check, update_output, accumulate > (
         output_cache, input_array, offset, offsetDistance, numerator );
 }
References castLight(), and check().
Referenced by explosion_handler::shrapnel().
sight_calc()
float sight_calc (const float & numerator, const float & transparency, const int & distance) inline
Definition at line 96 of file shadowcasting.h.
 {
     return numerator / std::exp( transparency * distance );
 }
sight_check()
bool sight_check (const float & transparency, const float &) inline
Definition at line 100 of file shadowcasting.h.
 {
     return transparency > LIGHT_TRANSPARENCY_SOLID;
 }
References LIGHT_TRANSPARENCY_SOLID.
update_light()
void update_light (float & update, const float & new_value, quadrant) inline
Definition at line 104 of file shadowcasting.h.
 {
     update = std::max( update, new_value );
 }
References max().
update_light_quadrants()
void update_light_quadrants (four_quadrants & update, const float & new_value, quadrant q) inline
Definition at line 108 of file shadowcasting.h.
 {
     update[q] = std::max( update[q], new_value );
 }
References max().
Referenced by map::apply_directional_light(), map::apply_light_arc(), map::apply_light_source(), and map::generate_lightmap().