Cataclysm DDA: src/skill_ui.h File Reference
skill_ui.h File Reference
#include <vector>
#include "skill.h"
Classes
struct HeaderSkill
For building list of skills including category as headers.
Macros
#define CATA_SRC_SKILL_UI
Functions
std::vector< HeaderSkill > get_HeaderSkills (const std::vector< const Skill * > &sorted_skills)
Build list of skills including category as headers.
template<typename V >
void skip_skill_headers (const std::vector< HeaderSkill > &skillslist, V &line, bool inc)
In menus with skills ensure selected line is not a header.
Macro Definition Documentation
CATA_SRC_SKILL_UI
#define CATA_SRC_SKILL_UI
Definition at line 3 of file skill_ui.h.
Function Documentation
get_HeaderSkills()
std::vector<HeaderSkill> get_HeaderSkills (const std::vector< const Skill * > & sorted_skills)
Build list of skills including category as headers.
Definition at line 6 of file skill_ui.cpp.
 {
     std::vector<HeaderSkill> skill_list;
     skill_displayType_id prev_type = skill_displayType_id::NULL_ID();
     for( const Skill * const &s : sorted_skills ) {
         if( s->display_category() != prev_type ) {
             prev_type = s->display_category();
             skill_list.emplace_back( s, true );
         }
         skill_list.emplace_back( s, false );
     }
     return skill_list;
 }
References string_id< SkillDisplayType >::NULL_ID().
Referenced by Character::disp_info(), and set_skills().
skip_skill_headers()
template<typename V > void skip_skill_headers (const std::vector< HeaderSkill > & skillslist, V & line, bool inc)
In menus with skills ensure selected line is not a header.
Definition at line 24 of file skill_ui.cpp.
 {
     const V prev_line = line;
     while( skillslist[line].is_header ) {
         line = inc_clamp_wrap( line, inc, skillslist.size() );
         if( line == prev_line ) {
             break;
         }
     }
 }
References inc_clamp_wrap(), and line().
Referenced by handle_player_display_action(), and set_skills().