Cataclysm DDA: src/skill.h File Reference
skill.h File Reference
#include <functional>
#include <iosfwd>
#include <map>
#include <set>
#include <string>
#include <unordered_map>
#include <vector>
#include "calendar.h"
#include "game_constants.h"
#include "translations.h"
#include "type_id.h"
Classes
struct time_info_t
class Skill
class SkillLevel
class SkillLevelMap
class SkillDisplayType
Macros
#define CATA_SRC_SKILL_H
Functions
double price_adjustment (int)
Macro Definition Documentation
CATA_SRC_SKILL_H
#define CATA_SRC_SKILL_H
Definition at line 3 of file skill.h.
Function Documentation
price_adjustment()
double price_adjustment (int barter_skill)
Definition at line 623 of file skill.cpp.
 {
     int const skill = std::min( 5, std::abs( barter_skill ) );
     double const val = 0.045 * std::pow( skill, 2 ) - 0.025 * skill + 1;
     return barter_skill >= 0 ? val : 1 / val;
 }
References abs(), and min().
Referenced by npc_trading::net_price_adjustment().