Cataclysm DDA: src/skill.cpp File Reference
skill.cpp File Reference
#include "skill.h"
#include <algorithm>
#include <array>
#include <cstddef>
#include <iterator>
#include <utility>
#include "cata_utility.h"
#include "debug.h"
#include "game_constants.h"
#include "item.h"
#include "json.h"
#include "options.h"
#include "recipe.h"
#include "rng.h"
#include "translations.h"
Functions
double price_adjustment (int barter_skill)
Variables
static const skill_id skill_archery ("archery")
static const skill_id skill_bashing ("bashing")
static const skill_id skill_computer ("computer")
static const skill_id skill_cooking ("cooking")
static const skill_id skill_cutting ("cutting")
static const skill_id skill_dodge ("dodge")
static const skill_id skill_driving ("driving")
static const skill_id skill_electronics ("electronics")
static const skill_id skill_firstaid ("firstaid")
static const skill_id skill_gun ("gun")
static const skill_id skill_launcher ("launcher")
static const skill_id skill_mechanics ("mechanics")
static const skill_id skill_melee ("melee")
static const skill_id skill_pistol ("pistol")
static const skill_id skill_rifle ("rifle")
static const skill_id skill_shotgun ("shotgun")
static const skill_id skill_smg ("smg")
static const skill_id skill_speech ("speech")
static const skill_id skill_stabbing ("stabbing")
static const skill_id skill_survival ("survival")
static const skill_id skill_swimming ("swimming")
static const skill_id skill_tailor ("tailor")
static const skill_id skill_throw ("throw")
static const skill_id skill_traps ("traps")
static const skill_id skill_unarmed ("unarmed")
static const Skill invalid_skill
static const SkillDisplayType invalid_skill_type
Function Documentation
price_adjustment()
double price_adjustment (int barter_skill)
Definition at line 623 of file skill.cpp.
 {
     int const skill = std::min( 5, std::abs( barter_skill ) );
     double const val = 0.045 * std::pow( skill, 2 ) - 0.025 * skill + 1;
     return barter_skill >= 0 ? val : 1 / val;
 }
References abs(), and min().
Referenced by npc_trading::net_price_adjustment().
Variable Documentation
invalid_skill
const Skill invalid_skill static
Definition at line 51 of file skill.cpp.
invalid_skill_type
const SkillDisplayType invalid_skill_type static
Definition at line 52 of file skill.cpp.
Referenced by SkillDisplayType::get_skill_type().
skill_archery
const skill_id skill_archery("archery") ("archery") static
Referenced by Skill::from_legacy_int().
skill_bashing
const skill_id skill_bashing("bashing") ("bashing") static
Referenced by Skill::from_legacy_int().
skill_computer
const skill_id skill_computer("computer") ("computer") static
Referenced by Skill::from_legacy_int().
skill_cooking
const skill_id skill_cooking("cooking") ("cooking") static
Referenced by Skill::from_legacy_int().
skill_cutting
const skill_id skill_cutting("cutting") ("cutting") static
Referenced by Skill::from_legacy_int().
skill_dodge
const skill_id skill_dodge("dodge") ("dodge") static
Referenced by Skill::from_legacy_int().
skill_driving
const skill_id skill_driving("driving") ("driving") static
Referenced by Skill::from_legacy_int().
skill_electronics
const skill_id skill_electronics("electronics") ("electronics") static
Referenced by Skill::from_legacy_int().
skill_firstaid
const skill_id skill_firstaid("firstaid") ("firstaid") static
Referenced by Skill::from_legacy_int().
skill_gun
const skill_id skill_gun("gun") ("gun") static
Referenced by Skill::from_legacy_int().
skill_launcher
const skill_id skill_launcher("launcher") ("launcher") static
Referenced by Skill::from_legacy_int().
skill_mechanics
const skill_id skill_mechanics("mechanics") ("mechanics") static
Referenced by Skill::from_legacy_int().
skill_melee
const skill_id skill_melee("melee") ("melee") static
Referenced by Skill::from_legacy_int().
skill_pistol
const skill_id skill_pistol("pistol") ("pistol") static
Referenced by Skill::from_legacy_int().
skill_rifle
const skill_id skill_rifle("rifle") ("rifle") static
Referenced by Skill::from_legacy_int().
skill_shotgun
const skill_id skill_shotgun("shotgun") ("shotgun") static
Referenced by Skill::from_legacy_int().
skill_smg
const skill_id skill_smg("smg") ("smg") static
Referenced by Skill::from_legacy_int().
skill_speech
const skill_id skill_speech("speech") ("speech") static
Referenced by Skill::from_legacy_int().
skill_stabbing
const skill_id skill_stabbing("stabbing") ("stabbing") static
Referenced by Skill::from_legacy_int().
skill_survival
const skill_id skill_survival("survival") ("survival") static
Referenced by Skill::from_legacy_int().
skill_swimming
const skill_id skill_swimming("swimming") ("swimming") static
Referenced by Skill::from_legacy_int().
skill_tailor
const skill_id skill_tailor("tailor") ("tailor") static
Referenced by Skill::from_legacy_int().
skill_throw
const skill_id skill_throw("throw") ("throw") static
Referenced by Skill::from_legacy_int().
skill_traps
const skill_id skill_traps("traps") ("traps") static
Referenced by Skill::from_legacy_int().
skill_unarmed
const skill_id skill_unarmed("unarmed") ("unarmed") static
Referenced by Skill::from_legacy_int().