Cataclysm DDA: src/smart_controller_ui.cpp File Reference
smart_controller_ui.cpp File Reference
#include "smart_controller_ui.h"
#include <algorithm>
#include <optional>
#include <string>
#include <vector>
#include "cata_utility.h"
#include "color.h"
#include "cursesdef.h"
#include "output.h"
#include "point.h"
#include "string_formatter.h"
#include "text_snippets.h"
#include "translations.h"
#include "ui_manager.h"
Functions
static catacurses::window init_window ()
Function Documentation
init_window()
static catacurses::window init_window () static
Definition at line 18 of file smart_controller_ui.cpp.
 {
     const int width = smart_controller_ui::WIDTH;
     const int height = smart_controller_ui::HEIGHT;
     const point p( std::max( 0, ( TERMX - width ) / 2 ), std::max( 0, ( TERMY - height ) / 2 ) );
     return catacurses::newwin( height, width, p );
 }
References smart_controller_ui::HEIGHT, max(), catacurses::newwin(), TERMX, TERMY, and smart_controller_ui::WIDTH.
Referenced by smart_controller_ui::control().