Cataclysm DDA: src/speech.cpp File Reference
speech.cpp File Reference
#include "speech.h"
#include <map>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "json.h"
#include "rng.h"
Functions
void load_speech (const JsonObject &jo)
void reset_speech ()
const SpeechBubble & get_speech (const std::string &label)
Variables
static std::map< std::string, std::vector< SpeechBubble > > speech
static SpeechBubble nullSpeech = { no_translation("INVALID SPEECH"), 0 }
Function Documentation
get_speech()
const SpeechBubble& get_speech (const std::string & label)
Definition at line 31 of file speech.cpp.
 {
     const std::map<std::string, std::vector<SpeechBubble> >::iterator speech_type = speech.find(
                 label );
     if( speech_type == speech.end() || speech_type->second.empty() ) {
         // Bad lookup, return a fake sound, also warn?
         return nullSpeech;
     }
     return random_entry_ref( speech_type->second );
 }
References nullSpeech, random_entry_ref(), and speech.
Referenced by mattack::check_money_left(), iuse::foodperson_voice(), parrot_common(), mattack::photograph(), and iuse::talking_doll().
load_speech()
void load_speech (const JsonObject & jo)
Definition at line 16 of file speech.cpp.
 {
     translation sound;
     jo.read( "sound", sound );
     const int volume = jo.get_int( "volume" );
     for( const std::string &label : jo.get_tags( "speaker" ) ) {
         speech[label].emplace_back( SpeechBubble{ sound, volume } );
     }
 }
References JsonObject::get_int(), JsonObject::get_tags(), anonymous_namespace{item_tname.cpp}::label(), JsonObject::read(), and speech.
Referenced by DynamicDataLoader::initialize().
reset_speech()
void reset_speech ()
Definition at line 26 of file speech.cpp.
 {
     speech.clear();
 }
References speech.
Referenced by DynamicDataLoader::unload_data().
Variable Documentation
nullSpeech
SpeechBubble nullSpeech = { no_translation("INVALID SPEECH"), 0 } static
Definition at line 14 of file speech.cpp.
Referenced by get_speech().
speech
std::map<std::string, std::vector<SpeechBubble> > speech static
Definition at line 12 of file speech.cpp.
Referenced by npc::complain(), npc::complain_about(), iuse::foodperson_voice(), get_speech(), field_type::load(), load_speech(), parrot_common(), mattack::photograph(), reset_speech(), talker_npc::say(), talker_character::shout(), iuse::talking_doll(), and npc::warn_about().