Cataclysm DDA: src/start_location.cpp File Reference
start_location.cpp File Reference
#include "start_location.h"
#include <algorithm>
#include <climits>
#include "avatar.h"
#include "bodypart.h"
#include "calendar.h"
#include "city.h"
#include "clzones.h"
#include "colony.h"
#include "coordinates.h"
#include "creature.h"
#include "debug.h"
#include "effect_source.h"
#include "enum_conversions.h"
#include "field_type.h"
#include "game_constants.h"
#include "generic_factory.h"
#include "json.h"
#include "map.h"
#include "map_extras.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "options.h"
#include "output.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "point.h"
#include "rng.h"
Namespaces
anonymous_namespace{start_location.cpp}
Functions
static void add_boardable (const tinymap &m, const tripoint &p, std::vector< tripoint > &vec)
static void board_up (tinymap &m, const tripoint_range< tripoint > &range)
static int rate_location (map &m, const tripoint &p, const bool must_be_inside, const bool accommodate_npc, const int bash_str, const int attempt, cata::mdarray< int, point_bub_ms > &checked)
Helper for place_player Flood-fills the area from a given point, then returns the area it found.
static void add_monsters (const tripoint_abs_omt &omtstart, const mongroup_id &type, float expected_points)
Variables
static const efftype_id effect_bleed ("bleed")
static const ter_str_id ter_t_curtains ("t_curtains")
static const ter_str_id ter_t_door_boarded ("t_door_boarded")
static const ter_str_id ter_t_door_c ("t_door_c")
static const ter_str_id ter_t_door_c_peep ("t_door_c_peep")
static const ter_str_id ter_t_door_locked ("t_door_locked")
static const ter_str_id ter_t_door_o ("t_door_o")
static const ter_str_id ter_t_floor ("t_floor")
static const ter_str_id ter_t_window ("t_window")
static const ter_str_id ter_t_window_boarded ("t_window_boarded")
static const ter_str_id ter_t_window_domestic ("t_window_domestic")
static const ter_str_id ter_t_window_no_curtains ("t_window_no_curtains")
static const zone_type_id zone_type_ZONE_START_POINT ("ZONE_START_POINT")
generic_factory< start_location > anonymous_namespace{start_location.cpp}::all_start_locations ("start locations")
Function Documentation
add_boardable()
static void add_boardable (const tinymap & m, const tripoint & p, std::vector< tripoint > & vec) static
Definition at line 158 of file start_location.cpp.
 {
     if( m.has_furn( p ) ) {
         // Don't need to board this up, is already occupied
         return;
     }
     if( m.ter( p ) != ter_t_floor ) {
         // Other terrain (door, wall, ...), not boarded either
         return;
     }
     if( m.is_outside( p ) ) {
         // Don't board up the outside
         return;
     }
     if( std::find( vec.begin(), vec.end(), p ) != vec.end() ) {
         // Already registered to be boarded
         return;
     }
     vec.push_back( p );
 }
References tinymap::has_furn(), tinymap::is_outside(), tinymap::ter(), and ter_t_floor.
Referenced by board_up().
add_monsters()
static void add_monsters (const tripoint_abs_omt & omtstart, const mongroup_id & type, float expected_points) static
Definition at line 589 of file start_location.cpp.
 {
     tinymap m;
     m.load( omtstart, false );
     // map::place_spawns internally multiplies density by rng(10, 50)
     const float density = expected_points / ( ( 10 + 50 ) / 2.0 );
     m.place_spawns( type, 1, point_omt_ms( point_zero ), point_omt_ms( SEEX * 2 - 1, SEEY * 2 - 1 ),
                     omtstart.z(),
                     density );
     m.save();
 }
References tinymap::load(), tinymap::place_spawns(), point_zero, tinymap::save(), SEEX, SEEY, item::type, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Referenced by start_location::surround_with_monsters().
board_up()
static void board_up (tinymap & m, const tripoint_range< tripoint > & range) static
Strength determines what furniture might be used as a starting area barricade
Definition at line 179 of file start_location.cpp.
 {
     std::vector<tripoint> furnitures1;
     std::vector<tripoint> furnitures2;
     std::vector<tripoint> boardables;
     for( const tripoint &p : range ) {
         bool must_board_around = false;
         const ter_id t = m.ter( p );
         if( t == ter_t_window_domestic || t == ter_t_window || t == ter_t_window_no_curtains ) {
             // Windows are always to the outside and must be boarded
             must_board_around = true;
             m.ter_set( p, ter_t_window_boarded );
         } else if( t == ter_t_door_c || t == ter_t_door_locked || t == ter_t_door_c_peep ) {
             // Only board up doors that lead to the outside
             if( m.is_outside( p + tripoint_north ) || m.is_outside( p + tripoint_south ) ||
                 m.is_outside( p + tripoint_east ) || m.is_outside( p + tripoint_west ) ) {
                 m.ter_set( p, ter_t_door_boarded );
                 must_board_around = true;
             } else {
                 // internal doors are opened instead
                 m.ter_set( p, ter_t_door_o );
             }
         }
         if( must_board_around ) {
             // Board up the surroundings of the door/window
             for( const tripoint &neigh : points_in_radius( p, 1 ) ) {
                 if( neigh == p ) {
                     continue;
                 }
                 add_boardable( m, neigh, boardables );
             }
         }
     }
     // Find all furniture that can be used to board up some place
     for( const tripoint &p : range ) {
         if( std::find( boardables.begin(), boardables.end(), p ) != boardables.end() ) {
             continue;
         }
         if( !m.has_furn( p ) ) {
             continue;
         }
         // If the furniture is movable and the character can move it, use it to barricade
         //  is workable here as NPCs by definition are not starting the game.  (Let's hope.)
         ///\EFFECT_STR determines what furniture might be used as a starting area barricade
         if( m.furn( p ).obj().is_movable() &&
             m.furn( p ).obj().move_str_req < get_player_character().get_str() ) {
             if( m.furn( p ).obj().movecost == 0 ) {
                 // Obstacles are better, prefer them
                 furnitures1.push_back( p );
             } else {
                 furnitures2.push_back( p );
             }
         }
     }
     while( ( !furnitures1.empty() || !furnitures2.empty() ) && !boardables.empty() ) {
         const tripoint fp = random_entry_removed( furnitures1.empty() ? furnitures2 : furnitures1 );
         const tripoint bp = random_entry_removed( boardables );
         m.furn_set( bp, m.furn( fp ) );
         m.furn_set( fp, furn_str_id::NULL_ID() );
         map_stack destination_items = m.i_at( bp );
         for( const item &moved_item : m.i_at( fp ) ) {
             destination_items.insert( moved_item );
         }
         m.i_clear( fp );
     }
 }
References add_boardable(), bp, tinymap::furn(), tinymap::furn_set(), get_player_character(), tinymap::has_furn(), tinymap::i_at(), tinymap::i_clear(), map_stack::insert(), furn_t::is_movable(), tinymap::is_outside(), furn_t::move_str_req, map_data_common_t::movecost, string_id< furn_t >::NULL_ID(), int_id< T >::obj(), points_in_radius(), random_entry_removed(), tinymap::ter(), tinymap::ter_set(), ter_t_door_boarded, ter_t_door_c, ter_t_door_c_peep, ter_t_door_locked, ter_t_door_o, ter_t_window, ter_t_window_boarded, ter_t_window_domestic, ter_t_window_no_curtains, tripoint_east, tripoint_north, tripoint_south, and tripoint_west.
Referenced by start_location::prepare_map().
rate_location()
static int rate_location (map & m, const tripoint & p, const bool must_be_inside, const bool accommodate_npc, const int bash_str, const int attempt, cata::mdarray< int, point_bub_ms > & checked) static
Helper for place_player Flood-fills the area from a given point, then returns the area it found.
Considers unpassable tiles passable if they can be bashed down or opened. Will return INT_MAX if it reaches upstairs or map edge. We can't really use map::route here, because it expects a destination Maybe TODO: Allow "picking up" items or parts of bashable furniture and using them to help with bash attempts.
Definition at line 379 of file start_location.cpp.
 {
     const auto invalid_char_pos = [&]( const tripoint & tp ) -> bool {
         return ( must_be_inside && m.is_outside( tp ) ) ||
         m.impassable( tp ) || m.is_divable( tp ) ||
         m.has_flag( ter_furn_flag::TFLAG_NO_FLOOR, tp );
     };
     if( checked[p.x][p.y] > 0 || invalid_char_pos( p ) ||
         ( accommodate_npc && invalid_char_pos( p + point_north_west ) ) ) {
         return 0;
     }
     // Vector that will be used as a stack
     std::vector<tripoint> st;
     st.reserve( MAPSIZE_X * MAPSIZE_Y );
     st.push_back( p );
     // If not checked yet and either can be moved into, can be bashed down or opened,
     // add it on the top of the stack.
     const auto maybe_add = [&]( const point & add_p, const tripoint & from ) {
         if( checked[add_p.x][add_p.y] >= attempt ) {
             return;
         }
         const tripoint pt( add_p, p.z );
         if( m.passable( pt ) ||
             m.bash_resistance( pt ) <= bash_str ||
             m.open_door( get_avatar(), pt, !m.is_outside( from ), true ) ) {
             st.push_back( pt );
         }
     };
     int area = 0;
     while( !st.empty() ) {
         area++;
         const tripoint cur = st.back();
         st.pop_back();
         checked[cur.x][cur.y] = attempt;
         if( cur.x == 0 || cur.x == MAPSIZE_X - 1 ||
             cur.y == 0 || cur.y == MAPSIZE_Y - 1 ||
             m.has_flag( ter_furn_flag::TFLAG_GOES_UP, cur ) ) {
             return INT_MAX;
         }
         maybe_add( cur.xy() + point_west, cur );
         maybe_add( cur.xy() + point_north, cur );
         maybe_add( cur.xy() + point_east, cur );
         maybe_add( cur.xy() + point_south, cur );
         maybe_add( cur.xy() + point_north_west, cur );
         maybe_add( cur.xy() + point_north_east, cur );
         maybe_add( cur.xy() + point_south_west, cur );
         maybe_add( cur.xy() + point_south_east, cur );
     }
     return area;
 }
References map::bash_resistance(), get_avatar(), map::has_flag(), map::impassable(), map::is_divable(), map::is_outside(), MAPSIZE_X, MAPSIZE_Y, map::open_door(), map::passable(), point_east, point_north, point_north_east, point_north_west, point_south, point_south_east, point_south_west, point_west, TFLAG_GOES_UP, TFLAG_NO_FLOOR, point::x, tripoint::x, tripoint::xy(), point::y, tripoint::y, and tripoint::z.
Referenced by start_location::place_player().
Variable Documentation
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by start_location::handle_heli_crash().
ter_t_curtains
const ter_str_id ter_t_curtains("t_curtains") ("t_curtains") static
Referenced by start_location::prepare_map().
ter_t_door_boarded
const ter_str_id ter_t_door_boarded("t_door_boarded") ("t_door_boarded") static
Referenced by board_up().
ter_t_door_c
const ter_str_id ter_t_door_c("t_door_c") ("t_door_c") static
Referenced by board_up().
ter_t_door_c_peep
const ter_str_id ter_t_door_c_peep("t_door_c_peep") ("t_door_c_peep") static
Referenced by board_up().
ter_t_door_locked
const ter_str_id ter_t_door_locked("t_door_locked") ("t_door_locked") static
Referenced by board_up().
ter_t_door_o
const ter_str_id ter_t_door_o("t_door_o") ("t_door_o") static
Referenced by board_up().
ter_t_floor
const ter_str_id ter_t_floor("t_floor") ("t_floor") static
Referenced by add_boardable().
ter_t_window
const ter_str_id ter_t_window("t_window") ("t_window") static
Referenced by board_up().
ter_t_window_boarded
const ter_str_id ter_t_window_boarded("t_window_boarded") ("t_window_boarded") static
Referenced by board_up().
ter_t_window_domestic
const ter_str_id ter_t_window_domestic("t_window_domestic") ("t_window_domestic") static
Referenced by board_up(), and start_location::prepare_map().
ter_t_window_no_curtains
const ter_str_id ter_t_window_no_curtains("t_window_no_curtains") ("t_window_no_curtains") static
Referenced by board_up().
zone_type_ZONE_START_POINT
const zone_type_id zone_type_ZONE_START_POINT("ZONE_START_POINT") ("ZONE_START_POINT") static
Referenced by start_location::place_player().