Cataclysm DDA: src/stomach.cpp File Reference
stomach.cpp File Reference
#include <algorithm>
#include <cmath>
#include <iosfwd>
#include <string>
#include <utility>
#include "cata_utility.h"
#include "character.h"
#include "itype.h"
#include "json.h"
#include "stomach.h"
#include "units.h"
#include "vitamin.h"
Functions
static std::string ml_to_string (const units::volume &vol)
static units::volume string_to_ml (const std::string_view str)
Function Documentation
ml_to_string()
static std::string ml_to_string (const units::volume & vol) static
Definition at line 249 of file stomach.cpp.
 {
     return std::to_string( units::to_milliliter<int>( vol ) ) + "_ml";
 }
References to_string().
Referenced by stomach_contents::serialize().
string_to_ml()
static units::volume string_to_ml (const std::string_view str) static
Definition at line 266 of file stomach.cpp.
 {
     return units::from_milliliter( svto<int>( str.substr( 0, str.size() - 3 ) ) );
 }
References units::from_milliliter(), and svto< int >().
Referenced by stomach_contents::deserialize().