Cataclysm DDA: src/string_id_utils.h File Reference
string_id_utils.h File Reference
#include "string_id.h"
#include <algorithm>
#include <vector>
Macros
#define CATA_SRC_STRING_ID_UTILS_H
Functions
template<typename Col , typename El = std::decay_t<decltype(*std::declval<const Col &>().begin())>, typename K = std::decay_t<typename El::first_type>, typename V = std::decay_t<typename El::second_type>, std::enable_if_t< std::is_same_v< K, string_id< typename K::value_type >>, int > = 0>
std::vector< std::pair< K, V > > sorted_lex (Col col)
Returns vector sorted by lexicographic order of string_id.
template<typename Col , typename El = std::decay_t<decltype(*std::declval<const Col &>().begin())>, std::enable_if_t< std::is_same_v< El, string_id< typename El::value_type >>, int > = 0>
std::vector< El > sorted_lex (Col col)
Returns vector sorted by lexicographic order of string_id.
Macro Definition Documentation
CATA_SRC_STRING_ID_UTILS_H
#define CATA_SRC_STRING_ID_UTILS_H
Definition at line 3 of file string_id_utils.h.
Function Documentation
sorted_lex() [1/2]
template<typename Col , typename El = std::decay_t<decltype(*std::declval<const Col &>().begin())>, typename K = std::decay_t<typename El::first_type>, typename V = std::decay_t<typename El::second_type>, std::enable_if_t< std::is_same_v< K, string_id< typename K::value_type >>, int > = 0> std::vector<std::pair<K, V> > sorted_lex (Col col)
Returns vector sorted by lexicographic order of string_id.
Parameters
col collection that supports iterators of std::pair<string_id<T>, V>
Returns
sorted (using string_id::LexCmp by std::pair::first) std::vector<std::pair<string_id<T>, V>>
Definition at line 22 of file string_id_utils.h.
 {
     std::vector<std::pair<K, V>> ret;
     ret.insert( ret.begin(), col.begin(), col.end() );
     std::sort( ret.begin(), ret.end(), []( const auto & a, const auto & b ) {
         return typename K::LexCmp()( a.first, b.first );
     } );
     return ret;
 }
References a, b, and cata::hash64_detail::ret.
Referenced by item::basic_info(), item::bionic_info(), item::food_info(), item::gun_info(), item::melee_combat_info(), item::properties_info(), item::qualities_info(), item::repair_info(), recipe::required_all_skills_string(), recipe::required_skills_string(), and item::tool_info().
sorted_lex() [2/2]
template<typename Col , typename El = std::decay_t<decltype(*std::declval<const Col &>().begin())>, std::enable_if_t< std::is_same_v< El, string_id< typename El::value_type >>, int > = 0> std::vector<El> sorted_lex (Col col)
Returns vector sorted by lexicographic order of string_id.
Parameters
col collection that supports iterators of string_id<T>
Returns
sorted (using string_id::LexCmp) std::vector<string_id<T>>
Definition at line 40 of file string_id_utils.h.
 {
     std::vector<El> ret;
     ret.insert( ret.begin(), col.begin(), col.end() );
     std::sort( ret.begin(), ret.end(), typename El::LexCmp() );
     return ret;
 }
References cata::hash64_detail::ret.