Cataclysm DDA: src/string_id.cpp File Reference
string_id.cpp File Reference
#include <unordered_map>
#include <vector>
#include "string_id.h"
Namespaces
anonymous_namespace{string_id.cpp}
Typedefs
using anonymous_namespace{string_id.cpp}::InternMapType = std::unordered_map< std::string, int >
using anonymous_namespace{string_id.cpp}::ReverseLookupVecType = std::vector< const std::string * >
Functions
static InternMapType & get_intern_map ()
static ReverseLookupVecType & get_reverse_lookup_vec ()
template<typename S >
static int universal_string_id_intern (S &&s)
Function Documentation
get_intern_map()
static InternMapType& get_intern_map () static
Definition at line 11 of file string_id.cpp.
 {
     static InternMapType map{};
     return map;
 }
References spell_effect::map().
Referenced by universal_string_id_intern().
get_reverse_lookup_vec()
static ReverseLookupVecType& get_reverse_lookup_vec () static
Definition at line 17 of file string_id.cpp.
 {
     static ReverseLookupVecType vec{};
     return vec;
 }
Referenced by string_identity_static::get_interned_string(), and universal_string_id_intern().
universal_string_id_intern()
template<typename S > static int universal_string_id_intern (S && s) static
Definition at line 24 of file string_id.cpp.
 {
     int next_id = get_reverse_lookup_vec().size();
     const auto &pair = get_intern_map().emplace( std::forward<S>( s ), next_id );
     if( pair.second ) { // inserted
         get_reverse_lookup_vec().push_back( &pair.first->first );
     }
     return pair.first->second;
 }
References get_intern_map(), and get_reverse_lookup_vec().
Referenced by string_identity_static::string_id_intern().