Cataclysm DDA: src/string_formatter.h File Reference
string_formatter.h File Reference
#include <cstddef>
#include <iosfwd>
#include <new>
#include <optional>
#include <string>
#include <type_traits>
#include <typeinfo>
#include "demangle.h"
Classes
class cata::string_formatter
Type-safe and undefined-behavior free wrapper over sprintf.
Namespaces
cata
Macros
#define CATA_SRC_STRING_FORMATTER_H
#define PRINTF_LIKE(a, b)
Functions
void cata::throw_error (const string_formatter &, std::string_view)
const char * cata::string_formatter_set_temp_buffer (const string_formatter &, std::string &&)
std::string cata::handle_string_format_error ()
template<typename RT , typename T >
std::enable_if_t< is_integer< RT > &&is_integer< T >, RT > cata::convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< is_integer< RT > &&std::is_enum_v< std::decay_t< T > >, RT > cata::convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< std::is_floating_point_v< RT > &&is_numeric< T > &&!is_integer< T >, RT > cata::convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< std::is_same_v< RT, void * > &&std::is_pointer_v< std::decay_t< T > >, void * > cata::convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< std::is_same_v< RT, const char * > &&is_string< T >, const char * > cata::convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< std::is_same_v< RT, const char * > &&is_string_view< T >, const char * > cata::convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< std::is_same_v< RT, const char * > &&is_cstring< T >, const char * > cata::convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< std::is_same_v< RT, const char * > &&is_translation< T >, const char * > cata::convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< std::is_same_v< RT, const char * > &&is_numeric< T > &&!is_char< T >, const char * > cata::convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
std::enable_if_t< std::is_same_v< RT, const char * > &&is_char< T >, const char * > cata::convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
RT cata::convert (RT *, const string_formatter &sf, T &&,...)
template<typename ... Args>
std::string string_format (std::string_view format, Args &&...args)
Simple wrapper over string_formatter::parse.
template<typename T , typename ... Args>
std::enable_if_t< cata::is_translation< T >, std::string > string_format (T &&format, Args &&...args)
Variables
template<typename T >
constexpr bool cata::is_numeric
template<typename T >
constexpr bool cata::is_integer
template<typename T >
constexpr bool cata::is_char = std::is_same_v<std::decay_t<T>, char>
template<typename T >
constexpr bool cata::is_string = std::is_same_v<std::decay_t<T>, std::string>
template<typename T >
constexpr bool cata::is_string_view = std::is_same_v<std::decay_t<T>, std::string_view>
template<typename T >
constexpr bool cata::is_cstring
template<typename T >
constexpr bool cata::is_translation = std::is_same_v<std::decay_t<T>, translation>
Macro Definition Documentation
CATA_SRC_STRING_FORMATTER_H
#define CATA_SRC_STRING_FORMATTER_H
Definition at line 3 of file string_formatter.h.
PRINTF_LIKE
#define PRINTF_LIKE (a, b)
Definition at line 369 of file string_formatter.h.
Function Documentation
string_format() [1/2]
template<typename ... Args> std::string string_format (std::string_view format, Args &&... args) inline
Simple wrapper over string_formatter::parse.
It catches any exceptions and returns some error string. Otherwise it just returns the formatted string.
These functions perform string formatting according to the rules of the printf function, see man 3 printf or any other documentation.
In short: the format parameter is a string with optional placeholders, which will be replaced with formatted data from the further arguments. The further arguments must have a type that matches the type expected by the placeholder. The placeholders look like this:
s expects an argument of type const char* or std::string or numeric (which is converted to a string via to_string), which is inserted as is.
d expects an argument of an integer type (int, short, ...), which is formatted as decimal number.
f expects a numeric argument (integer / floating point), which is formatted as decimal number.
There are more placeholders and options to them (see documentation of printf). Note that this wrapper (via string_formatter) automatically converts the arguments to match the given format specifier (if possible) - see Convert functions for string_formatter.
Definition at line 417 of file string_formatter.h.
 {
     try {
         cata::string_formatter formatter( format );
         formatter.parse( std::forward<Args>( args )... );
         return formatter.get_output();
     } catch( ... ) {
         return cata::handle_string_format_error();
     }
 }
References cata::string_formatter::get_output(), cata::handle_string_format_error(), and cata::string_formatter::parse().
Referenced by anonymous_namespace{math_parser_diag.cpp}::_characters_nearby_eval(), anonymous_namespace{iexamine.cpp}::_choose_elevator_destz(), anonymous_namespace{math_parser_diag_value.cpp}::_diag_value_at_parse_time(), trade_ui::_draw_header(), anonymous_namespace{math_parser.cpp}::_get_dialogue_func(), anonymous_namespace{math_parser_diag.cpp}::_monsters_nearby_eval(), anonymous_namespace{clzones.cpp}::_savefile(), anonymous_namespace{math_parser.cpp}::_validate_operand(), anonymous_namespace{math_parser.cpp}::_validate_unused_kwargs(), inventory_selector::action_examine(), advanced_inventory::action_move_item(), item::actions_info(), activatable_inventory_preset::activatable_inventory_preset(), effect_on_condition::activate(), Character::activate_bionic(), display::activity_malus_str(), memorial_logger::add(), add_disassemblables(), add_electronic_toggle(), overmap::add_extra_note(), add_folded_name_and_value(), anonymous_namespace{monexamine.cpp}::add_leash(), add_msg(), Creature::add_msg_if_npc(), Creature::add_msg_if_player(), add_msg_if_player_sees(), Creature::add_msg_player_or_npc(), Creature::add_msg_player_or_say(), pocket_favorite_callback::add_pockets(), add_salvagables(), mapgen_parameters::add_unique_parameter(), map::add_vehicle(), uilist::addentry(), Character::age_string(), item::already_used_by_player(), item::ammo_info(), item::ammo_set(), spell::aoe_string(), jmapgen_terrain::apply(), item::armor_attribute_info(), item::armor_fit_info(), item::armor_full_protection_info(), item::armor_info(), armor_inventory_preset::armor_inventory_preset(), item::armor_material_info(), item::armor_protection_info(), assemble_description_help(), assemble_hobby_details(), assemble_profession_details(), assemble_scenario_details(), assemble_skill_help(), assemble_stat_details(), assemble_stat_help(), iexamine::attunement_altar(), iexamine::autodoc(), autodoc_internal(), vehicle::automatic_fire_turret(), vehicle::backfire(), spell_effect::banishment(), item::basic_info(), recipe::batch_savings_string(), item::battery_info(), iuse::binder_add_recipe(), iuse::binder_manage_recipe(), item::bionic_info(), basecamp::board_name(), Character::body_window(), item::book_info(), vehicle::build_bike_rack_menu(), build_bionic_poweronly_string(), vehicle::build_interact_menu(), game::bury_screen(), butcher_submenu(), veh_interact::calc_lift_requirements(), veh_interact::calc_overview(), iuse::calories_intake_tracker(), camp_trip_description(), Character::can_eat(), Character::can_install_bionics(), npc::can_read(), veh_interact::can_remove_part(), iuse::can_smoke(), Character::can_uninstall_bionic(), iuse_transform::can_use(), Character::can_wear(), iuse::capture_monster_act(), display::carry_weight_text_color(), cata_fail_chance_string(), debug_menu::change_spells(), debug_menu::character_edit_desc_menu(), debug_menu::character_edit_menu(), debug_menu::character_edit_needs_menu(), game::chat(), mapgen_palette::check(), overmap_special::check(), mutable_overmap_terrain::check(), mutable_overmap_special_data::check(), jmapgen_vehicle::check(), jmapgen_sealed_item::check(), Item_factory::check_ammo_type(), mapgen_parameters::check_and_merge(), pocket_data::check_definition(), Item_factory::check_definitions(), mod_tracker::check_duplicate_entries(), check_martialarts(), outfit::check_rigid_change_side(), game::check_safe_mode_allowed(), choose_ma_style(), game::climb_down_menu_gen(), game::climb_down_using(), anonymous_namespace{armor_layers.cpp}::clothing_properties(), anonymous_namespace{armor_layers.cpp}::clothing_protection(), anonymous_namespace{armor_layers.cpp}::collect_protection_subvalues(), color_number(), display::colorized_compass_legend_text(), spell::colorized_fail_percent(), colorized_feature_description_at(), colorized_field_description_at(), colorized_ter_name_flags_at(), coloured_stat_display(), comestible_inventory_preset::comestible_inventory_preset(), game_menus::inv::common(), talk_function::companion_choose(), npc::complain(), Character::complete_disassemble(), item::component_info(), item::components_to_string(), Character::conduct_blood_analysis(), construction_menu(), item::contain_monster(), game_menus::inv::container_for(), anonymous_namespace{item_tname.cpp}::contents(), item::contents_info(), item_pocket::contents_info(), vehicle::control_doors(), vehicle::control_engines(), mod_manager::copy_mod_contents(), anonymous_namespace{item_tname.cpp}::craft(), basecamp::craft_description(), craft_success_chance_string(), overmap_ui::create_note(), talk_response::create_option_line(), Character::crush_frozen_liquid(), spell::damage_string(), display::date_string(), trap::debug_describe(), debug_drop_list(), debug_error_prompt(), item::debug_info(), debug_menu::debug_menu_force_temperature(), debug_menu::debug_menu_game_state(), item_group::debug_spawn(), trait_group::debug_spawn(), MapExtras::debug_spawn_test(), activity_tracker::debug_weary_info(), Character::debug_weary_info(), decorate_panel(), mutation_branch::desc(), item_location::impl::item_in_container::describe(), morale_type_data::describe(), describe(), harvest_list::describe(), Creature::describe_infrared(), npc::describe_mission(), fixed_distribution::description(), uniform_distribution::description(), binomial_distribution::description(), poisson_distribution::description(), score::description(), value_constraint::deserialize(), new_field::deserialize(), part_material::deserialize(), armor_portion_data::deserialize(), player_difficulty::difficulty_to_string(), direction_suffix(), Character::disassemble(), item::disassembly_info(), effect::disp_desc(), Character::disp_info(), effect::disp_name(), vehicle::disp_name(), Character::disp_name(), monster::disp_name(), map::disp_name(), faction_manager::display(), player_morale::display(), item::display_money(), veh_interact::display_name(), item::display_name(), main_menu::display_sub_menu(), Character::dispose_item(), talker_npc::distance_to_goal(), npc::do_player_activity(), veh_interact::do_refill(), veh_interact::do_repair(), data_handling_activity_actor::do_turn(), inventory_selector::drag_drop_item(), draw_bionics_tab(), draw_bionics_tabs(), draw_bionics_titlebar(), bodygraph_display::draw_borders(), draw_can_craft_indicator(), draw_connectors(), keybindings_ui::draw_controls(), target_ui::draw_controls_list(), prof_window::draw_details(), draw_effects_summary(), draw_effects_tab(), draw_encumbrance_tab(), draw_filter_and_sorting_indicators(), inventory_selector::draw_footer(), prof_window::draw_header(), draw_health_summary(), target_ui::draw_help_notice(), draw_hidden_amount(), veh_app_interact::draw_info(), char_creation::draw_location(), draw_medical_titlebar(), anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), worldfactory::draw_mod_list(), overmap_ui::draw_notes(), overmap_ui::draw_om_sidebar(), draw_proficiencies_info(), draw_proficiencies_tab(), mission_ui_impl::draw_selected_description(), draw_skills_info(), draw_skills_tab(), draw_speed_tab(), draw_spellbook_info(), draw_stats_info(), draw_stats_summary(), draw_stats_tab(), draw_tip(), draw_traits_info(), draw_traits_tab(), vehicle::drive_to_local_target(), mattack::dsa_drone_scan(), item::durability_indicator(), spell::duration_string(), dialogue::dynamic_line(), game_menus::inv::ebookread(), game_menus::inv::ebooksave(), editmap::edit(), editmap::edit_feature(), editmap::edit_fld(), editmap::edit_itm(), editmap::edit_mapgen(), eff_fun_bleed(), spell_effect::effect_on_condition(), effects_description_for_creature(), iexamine::elevator(), item::enchantment_info(), enchantment_info_helper(), enchantment_info_printer(), enumerate_lcsorted_with_limit(), enumerate_objects_around_point(), spell::enumerate_targets(), Character::enumerate_unmet_requirements(), ereader_inventory_preset::ereader_inventory_preset(), math_exp::math_exp_impl::error(), JsonObject::error_skipped_members(), anonymous_namespace{item_tname.cpp}::ethereal(), talker_npc::evaluation_by(), npc::execute_action(), spell::exp_progress(), map_data_common_t::extended_description(), Character::extended_description(), monster::extended_description(), game::extended_description(), extract_and_check_orientation_flags(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_var(), conditional_fun::anonymous_namespace{condition.cpp}::f_expects_vars(), conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), mtype::faction_display(), basecamp::faction_display(), npc::faction_display(), debug_menu::faction_edit_menu(), anonymous_namespace{math_parser_diag.cpp}::field_strength_eval(), Messages::dialog::filter_help_text(), item::final_info(), mutable_overmap_special_data::finalize(), uimenu::finalize_addentries(), overmap_special::finalize_mapgen_parameters(), npc::find_corpse_to_pulp(), find_dirname(), game::find_or_make_stairs(), find_quad_path(), find_region_path(), Item_factory::find_template(), reload_activity_actor::finish(), shearing_activity_actor::finish(), insert_item_activity_actor::finish(), outfit::fire_options(), iuse::fitness_check(), options_manager::PageItem::fmt_tooltip(), fold_and_print(), fold_and_print_from(), item::food_info(), vpart_info::format_description(), format_money(), format_object_pair(), player_difficulty::format_output(), veh_interact::format_reqs(), format_volume(), full_screen_popup(), map::furnname(), basecamp::gathering_return(), dialogue::gen_responses(), json_talk_response::gen_responses(), debug_menu::gen_sound(), item_pocket::general_info(), overmap::generate(), get_achievements_text(), activatable_inventory_preset::get_action_name(), ereader_inventory_preset::get_action_name(), bionic_install_preset::get_anesth_amount(), basecamp::get_available_missions(), basecamp::get_available_missions_by_dir(), get_bodygraph_lines(), Character::get_book_reader(), input_context::get_button_text(), inventory_selector_preset::get_caption(), selection_column_preset::get_caption(), inventory_selector_preset::get_cell_text(), get_colored_bar(), get_consume_needs_hint(), weapon_inventory_preset::get_damage_string(), armor_inventory_preset::get_decimal_string(), activatable_inventory_preset::get_denial(), gunmod_inventory_preset::get_denial(), ereader_inventory_preset::get_denial(), bionic_install_preset::get_denial(), trade_preset::get_denial(), input_context::get_desc(), bonus_container::get_description(), ma_technique::get_description(), repair_item_actor::get_description(), ma_requirements::get_description(), ma_buff::get_description(), overmapbuffer::get_description_at(), ignorable_options::get_descriptions(), unload_options::get_descriptions(), get_diary_time_since_str(), get_diary_time_str(), help::get_dir_grid(), player_activity::get_distractions(), get_encumbrance_description(), basecamp::get_equipment(), bionic_install_preset::get_failure_chance(), bionic_install_surgeon_preset::get_failure_chance(), get_fire_fuel_string(), vehicle::get_folded_item(), get_freshness_description(), conditional_t::get_get_dbl(), diary::get_head_text(), inventory_selector::get_holster_stat(), recipe_result_info_cache::get_item_header(), input_manager::get_keyname(), kill_tracker::get_kills_text(), options_manager::get_lang_options(), liquid_handler::get_liquid_target(), mapgen_factory::get_map_special_params(), typed_flag_reader< T >::get_next(), enum_flags_reader< E >::get_next(), help::get_note_colors(), armor_inventory_preset::get_number_string(), player_activity::get_progress_message(), read_activity_actor::get_progress_message(), activity_actor::get_progress_message(), item::get_remaining_capacity_for_liquid(), item::get_remaining_chapters(), get_repair_hint(), get_score_text(), conditional_t::get_set_dbl(), inventory_selector::get_stats(), vehicle_part::get_targeting_npc(), inventory_selector::get_volume_stat(), inventory_selector::get_weight_and_length_stat(), anonymous_namespace{messages.cpp}::game_message::get_with_count(), loot_options::get_zone_name_suggestion(), unload_options::get_zone_name_suggestion(), options_manager::cOpt::getDefaultText(), options_manager::cOpt::getValue(), options_manager::cOpt::getValueName(), basecamp::give_equipment(), talker_npc::give_item_to(), anonymous_namespace{game_inventory.cpp}::good_bad_none(), item::gun_info(), Character::gunmod_add(), item::gunmod_info(), gunmod_inventory_preset::gunmod_inventory_preset(), gunmod_remove_inventory_preset::gunmod_remove_inventory_preset(), gunmode_checks_common(), gunmode_checks_weapon(), game::handle_action(), handle_debug_mode(), generic_factory< T >::handle_inheritance(), Character::hardcoded_effects(), haul(), Character::height_string(), anonymous_namespace{game_inventory.cpp}::highlight_good_bad_none(), unload_selector::hint_string(), game_menus::inv::holster(), outfit::holster_opts(), hp_description(), avatar::identify(), iexamine_actor_from_jsobj(), iuse_transform::info(), explosion_iuse::info(), consume_drug_iuse::info(), deploy_furn_actor::info(), deploy_appliance_actor::info(), learn_spell_actor::info(), cast_spell_actor::info(), ammobelt_actor::info(), link_up_actor::info(), item_pocket::favorite_settings::info(), item_contents::info(), item::info(), input_manager::init_keycode_mapping(), anonymous_namespace{monexamine.cpp}::insert_battery(), game::insert_item(), exosuit_interact::insert_replace_activate_mod(), avatar::invoke_item(), item_filter_rule_string(), inscribe_actor::item_inscription(), item_save_monsters(), jmapgen_int::jmapgen_int(), basecamp::job_assignment_ui(), iexamine::keg(), pocket_favorite_callback::key(), ma_style_callback::key(), keybindings_ui::keybindings_ui(), diary::kill_changes(), creature_tracker::kill_marked_for_death(), widget::layout(), known_magic::learn_spell(), length_to_string(), item::link_name(), game::list_items(), game::list_monsters(), list_occupied_bps(), past_achievements_info::load(), mon_effect_data::load(), vpart_variant::load(), generic_factory< T >::load(), overmap_special::load(), recipe::load(), rotatable_symbols::load(), recipe_dictionary::load(), jmath_func::load(), npc_class::load(), Item_factory::load_basic_info(), main_menu::load_character_tab(), load_construction(), load_float_or_maxmovecost(), Item_factory::load_migration(), load_msg_help(), npc::load_npc_template(), mapgen_palette::load_place_mapings(), load_season_array(), Item_factory::load_sub_ref(), iexamine::locked_object(), game::look_around(), item::magazine_info(), ret_val< void >::make_failure(), ret_val< T >::make_failure(), make_group_or_throw(), ret_val< void >::make_success(), ret_val< T >::make_success(), editmap::mapgen_preview(), editmap::mapgen_retarget(), item::mark_as_used_by_player(), item::mark_chapter_as_read(), item::med_info(), item::melee_combat_info(), melee_message(), Character::melee_special_effects(), Character::mend_item(), mapgen_function_json_base::merge_non_nest_parameters_into(), query_popup::message(), monexamine::mfriend_menu(), anonymous_namespace{item_tname.cpp}::mods(), game_menus::inv::molle_attach(), game::mon_info_update(), display::move_count_and_mode_text_color(), pocket_favorite_callback::move_item(), map::move_vehicle(), moves_to_string(), multi_projectile_hit_message(), Character::mutation_attacks(), catacurses::mvwprintw(), mvwprintz(), MOD_INFORMATION::name(), vpart_info::name(), vehicle_part::name(), monster::name(), npc::name_and_activity(), basecamp::name_display_of(), monster::name_with_armor(), inventory_selector::naturalize_category(), math_exp::math_exp_impl::new_func(), minesweeper_game::new_level(), game::npc_menu(), npc_temp_orders_menu(), widget::number(), widget::number_cond(), mattack::nurse_check_up(), mattack::nurse_operate(), monster::nursebot_operate(), basecamp::om_upgrade_description(), Character::on_hurt(), one_char_symbol_reader(), outfit::one_per_layer_change_side(), npc::opinion_text(), dialogue::opt(), item::overheat_symbol(), display::overmap_position_text(), iuse::oxygen_bottle(), display::pain_text_color(), target_ui::panel_cursor_info(), target_ui::panel_gun_info(), target_ui::panel_recoil(), target_ui::panel_turret_list(), parse_vp_reqs(), past_game_info::past_game_info(), monexamine::pay_bot(), iexamine::pay_gas(), liquid_handler::perform_liquid_transfer(), item::pet_armor_protection_info(), monexamine::pet_menu(), iuse::petfood(), photo_def_for_camera_point(), mattack::photograph(), pick_one_up(), pick_part(), character_martial_arts::pick_style(), mutation_branch::pick_variant_menu(), worldfactory::pick_world(), pickup_selector::pickup_selector(), mutable_overmap_special_data::place(), place_craft_or_disassembly(), mission_start::place_npc_software(), game::place_player(), overmap::place_radios(), overmap_ui::place_ter_or_special(), play_videogame(), overmapbuffer::player_filename(), player_hit_message(), pocket_management_menu(), game::point_selection_menu(), pools_to_string(), veh_app_interact::populate_app_actions(), popup(), popup_getkey(), popup_player_or_npc(), popup_top(), iexamine::portable_structure(), avatar::power_bionics(), avatar::power_mutations(), practice_recipe_description(), outfit::prepare_bodymap_info(), bodygraph_display::prepare_infotext(), print_confidence_ratings(), computer_session::print_error(), game::print_furniture_info(), print_humidity(), computer_session::print_indented_line(), monster::print_info(), advanced_inventory::print_items(), main_menu::print_menu(), main_menu::print_menu_items(), game::print_part_con_info(), vehicle::print_part_list(), print_pressure(), print_ranged_chance(), snake_game::print_score(), print_steadiness(), print_temperature(), game::print_terrain_info(), print_time_just_hour(), vehicle::print_vparts_descs(), item::process_link(), sounds::process_sound_markers(), talker_character_const::proficiency_training_text(), profstring(), anonymous_namespace{iexamine.cpp}::atm_menu::prompt_for_amount(), prompt_for_amount(), prompt_world_name(), item::properties_info(), item::qualities_info(), iexamine::quern_examine(), advanced_inventory::query_charges(), advanced_inventory::query_destination(), query_int(), query_pick(), unload_options::query_unload(), query_yn(), Character::query_yn(), query_ynq(), computer_session::query_ynq(), iuse::radio_on(), iuse::radio_tick(), game_menus::inv::read(), avatar::read(), read_and_set_or_throw(), read_inventory_preset::read_inventory_preset(), realDebugmsg(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::receive_item(), recipe_info(), basecamp::recruit_description(), basecamp::recruit_return(), advanced_inventory::redraw_pane(), advanced_inventory::redraw_sidebar(), veh_app_interact::refill(), smart_controller_ui::refresh(), pocket_favorite_callback::refresh(), spellcasting_callback::refresh(), teleporter_callback::refresh(), wish_monster_callback::refresh(), wish_item_callback::refresh(), anonymous_namespace{item_tname.cpp}::relic_charges(), reload_furniture(), vehicle::reload_seeds(), game_menus::inv::repair(), item::repair_info(), repair_inventory_preset::repair_inventory_preset(), repair_item_finish(), replace_keybind_tag(), TextJsonObject::report_unvisited(), required_skills_as_string(), anonymous_namespace{iexamine.cpp}::atm_menu::reset(), item::rot_info(), mutable_overmap_phase_remainder::satisfy(), map_memory::save(), game_menus::inv::saw_barrel(), game_menus::inv::saw_stock(), npc::say(), overmap_ui::search(), game_menus::inv::select_ammo(), select_ammo_inventory_preset::select_ammo_inventory_preset(), select_crafter_and_crafting_recipe(), Character::select_item_component(), editmap::select_shape(), calendar_ui::select_time_point(), Character::select_tool_component(), selection_line::selection_line(), units::quantity< V, U >::serialize(), set_description(), set_language(), set_points(), set_skills(), overmap_ui::set_special_args(), set_stats(), set_traits(), item::set_var(), ui::omap::setup_cities_menu(), mapgen_function_json_base::setup_common(), mapgen_function_json_base::setup_setmap(), mattack::shocking_reveal(), auto_notes::auto_note_manager_gui::show(), auto_pickup::npc_settings::show(), diary::show_diary_ui(), color_manager::show_gui(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), diary::skill_changes(), talker_character_const::skill_seminar_text(), talker_character_const::skill_training_text(), sleep(), game_menus::inv::smoke_food(), iexamine::smoker_options(), snake_game::snake_over(), outfit::sort_armor(), diary::spell_changes(), debug_menu::spell_description(), spellcasting_callback::spell_info_text(), talker_character_const::spell_training_text(), fungal_effects::spread_fungus_one_tile(), basecamp::start_crafting(), vehicle::start_engine(), diary::stat_changes(), game_menus::inv::steal(), activity_type::stop_phrase(), diag_value::str(), string_format(), talker_character_const::style_training_text(), widget::sym_text_cond(), avatar::talk_to(), overmapbuffer::terrain_filename(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), text_for_requirement(), anonymous_namespace{math_parser_diag.cpp}::time_ass(), item::tname(), quality_requirement::to_colored_string(), container_data::to_formatted_string(), four_quadrants::to_string(), to_string(), tool_comp::to_string(), item_comp::to_string(), quality_requirement::to_string(), to_string_approx(), to_string_clipped(), to_string_time_of_day(), to_string_writable(), game::debug_hour_timer::toggle(), item::tool_info(), avatar::total_daily_calories_string(), training_select_menu(), trim_and_print(), trimmed_name_and_value(), try_consume(), try_parse_integer(), item::type_name(), achievement_tracker::ui_text(), achievement::time_bound::ui_text(), achievement_state::ui_text(), target_ui::uitext_title(), Character::unwield(), editmap::update_fmenu_entry(), veh_interact::update_part_requirements(), editmap::update_view_with_help(), weather_manager::update_weather(), computer_session::use(), place_monster_iuse::use(), inscribe_actor::use(), musical_instrument_actor::use(), holster_actor::use(), place_trap_actor::use(), deploy_tent_actor::use(), sew_advanced_actor::use(), learn_spell_actor::use(), modify_gunmods_actor::use(), link_up_actor::use(), Character::use_amount(), map::use_amount(), heal_actor::use_healing_item(), worldfactory::valid_worldname(), anonymous_namespace{math_parser.cpp}::parse_state::validate(), math_exp::math_exp_impl::validate_string(), item::variant_description(), anonymous_namespace{item_tname.cpp}::vars(), game_menus::inv::veh_tool_attach(), display::vehicle_cruise_text_color(), display::vehicle_fuel_percent_text_color(), iexamine::vending(), game::vertical_notes(), activity_handlers::view_recipe_do_turn(), faction::vitamin_stores(), vol_to_info(), vol_to_string(), wait(), query_popup::wait_message(), query_popup::wait_text(), npc::warn_about(), iuse::wash_items(), Character::weapname(), Character::weapname_ammo(), weapon_inventory_preset::weapon_inventory_preset(), anonymous_namespace{math_parser_diag.cpp}::weather_ass(), anonymous_namespace{math_parser_diag.cpp}::weather_eval(), weather_forecast(), weight_to_info(), weight_to_string(), anonymous_namespace{item_tname.cpp}::wheel_diameter(), wheel_state_description(), outfit::where_discomfort(), Character::will_eat(), debug_menu::wishbionics(), debug_menu::wisheffect(), debug_menu::wishitem(), debug_menu::wishmonster(), debug_menu::wishmutate(), debug_menu::wishproficiency(), debug_menu::wishskill(), iexamine::workbench_internal(), main_menu::world_tab(), catacurses::wprintw(), wprintz(), debug_menu::write_city_list(), game::write_memorial_file(), anonymous_namespace{debug_menu.cpp}::write_min_archive(), memorial_logger::write_text_memorial(), write_to_file(), write_var_value(), and zones_manager_shortcuts().
string_format() [2/2]
template<typename T , typename ... Args> std::enable_if_t<cata::is_translation<T>, std::string> string_format (T && format, Args &&... args) inline
Definition at line 429 of file string_formatter.h.
 {
     return string_format( format.translated(), std::forward<Args>( args )... );
 }
References string_format().