Cataclysm DDA: src/string_input_popup.cpp File Reference
string_input_popup.cpp File Reference
#include "string_input_popup.h"
#include <cctype>
#include "cata_scope_helpers.h"
#include "catacharset.h"
#include "input.h"
#include "input_context.h"
#include "output.h"
#include "point.h"
#include "translations.h"
#include "try_parse_integer.h"
#include "ui.h"
#include "ui_manager.h"
#include "uistate.h"
#include "wcwidth.h"
#include <algorithm>
#include <memory>
#include <string>
#include <vector>
Functions
template<typename T >
T query_int_impl (string_input_popup &p, const bool loop, const bool draw_only)
template<typename T >
static void edit_integer (string_input_popup &p, T &value)
Function Documentation
edit_integer()
template<typename T > static void edit_integer (string_input_popup & p, T & value) static
Definition at line 636 of file string_input_popup.cpp.
 {
     p.only_digits( true );
     while( true ) {
         p.text( std::to_string( value ) );
         p.query();
         if( p.canceled() ) {
             break;
         }
         ret_val<T> parsed_val = try_parse_integer<T>( p.text(), true );
         if( parsed_val.success() ) {
             value = parsed_val.value();
             break;
         } else {
             popup( parsed_val.str() );
         }
     }
 }
References string_input_popup::canceled(), string_input_popup::only_digits(), popup(), string_input_popup::query(), ret_val_common::str(), ret_val_common::success(), string_input_popup::text(), to_string(), and ret_val< T >::value().
query_int_impl()
template<typename T > T query_int_impl (string_input_popup & p, const bool loop, const bool draw_only)
Definition at line 345 of file string_input_popup.cpp.
 {
     do {
         ret_val<T> result = try_parse_integer<T>( p.query_string( loop, draw_only ), true );
         if( p.canceled() ) {
             return 0;
         }
         if( result.success() ) {
             return result.value();
         }
         popup( result.str() );
     } while( loop );
     return 0;
 }
References string_input_popup::canceled(), popup(), string_input_popup::query_string(), ret_val_common::str(), ret_val_common::success(), and ret_val< T >::value().