Cataclysm DDA: limb_score_effect Struct Reference
limb_score_effect Struct Reference
#include <effect.h>
Public Member Functions
void load (const JsonObject &jo)
void deserialize (const JsonObject &jo)
Public Attributes
limb_score_id score_id
float mod
float red_mod
float scaling
float red_scaling
Detailed Description
Definition at line 82 of file effect.h.
Member Function Documentation
deserialize()
void limb_score_effect::deserialize (const JsonObject & jo)
Definition at line 92 of file effect.cpp.
 {
     load( jo );
 }
References load().
load()
void limb_score_effect::load (const JsonObject & jo)
Definition at line 81 of file effect.cpp.
 {
     mandatory( jo, false, "limb_score", score_id );
     optional( jo, false, "modifier", mod, 1.0f );
     optional( jo, false, "resist_modifier", red_mod, mod );
     optional( jo, false, "scaling", scaling, 0.0f );
     optional( jo, false, "resist_scaling", red_scaling, scaling );
 }
References mandatory, mod, optional(), red_mod, red_scaling, and scaling.
Referenced by deserialize().
Member Data Documentation
mod
float limb_score_effect::mod
Definition at line 86 of file effect.h.
Referenced by load().
red_mod
float limb_score_effect::red_mod
Definition at line 87 of file effect.h.
Referenced by load().
red_scaling
float limb_score_effect::red_scaling
Definition at line 89 of file effect.h.
Referenced by load().
scaling
float limb_score_effect::scaling
Definition at line 88 of file effect.h.
Referenced by load().
score_id
limb_score_id limb_score_effect::score_id
Definition at line 84 of file effect.h.
The documentation for this struct was generated from the following files:
src/effect.h
src/effect.cpp