Cataclysm DDA: binomial_distribution Struct Reference
binomial_distribution Struct Reference
Public Member Functions
binomial_distribution (int lo, int hi, int t, double p)
int minimum () const override
int sample () override
std::string description () const override
Public Member Functions inherited from int_distribution_impl
virtual ~int_distribution_impl ()=default
Public Attributes
std::binomial_distribution< int > dist
Public Attributes inherited from int_distribution_impl
int blo = 0
int bhi = INT_MAX
Detailed Description
Definition at line 64 of file distribution.cpp.
Constructor & Destructor Documentation
binomial_distribution()
binomial_distribution::binomial_distribution (int lo, int hi, int t, double p) inline explicit
Definition at line 66 of file distribution.cpp.
         : dist( t, p ) {
         blo = lo;
         bhi = hi;
     }
References int_distribution_impl::bhi, int_distribution_impl::blo, and cata::hash64_detail::lo.
Member Function Documentation
description()
std::string binomial_distribution::description () const inline override virtual
Implements int_distribution_impl.
Definition at line 83 of file distribution.cpp.
{
         // NOLINTNEXTLINE(cata-translate-string-literal)
         return string_format( "Binomial(%d,%.0f)", dist.t(), dist.p() );
     }
References dist, and string_format().
minimum()
int binomial_distribution::minimum () const inline override virtual
Implements int_distribution_impl.
Definition at line 72 of file distribution.cpp.
{
         return 0;
     }
sample()
int binomial_distribution::sample () inline override virtual
Implements int_distribution_impl.
Definition at line 76 of file distribution.cpp.
{
         int distvalue = dist( rng_get_engine() );
         int rvalue = std::min( distvalue, bhi );
         rvalue = std::max( rvalue, blo );
         return rvalue;
     }
References int_distribution_impl::bhi, int_distribution_impl::blo, dist, max(), min(), and rng_get_engine().
Member Data Documentation
dist
std::binomial_distribution<int> binomial_distribution::dist
Definition at line 65 of file distribution.cpp.
Referenced by description(), and sample().
The documentation for this struct was generated from the following file:
src/distribution.cpp