Cataclysm DDA: islot_engine Struct Reference
islot_engine Struct Reference
#include <itype.h>
Public Member Functions
void load (const JsonObject &jo)
void deserialize (const JsonObject &jo)
Public Attributes
friend Item_factory
friend item
int displacement = 0
for combustion engines the displacement (cc)
bool was_loaded = false
Detailed Description
Definition at line 627 of file itype.h.
Member Function Documentation
deserialize()
void islot_engine::deserialize (const JsonObject & jo)
Definition at line 2729 of file item_factory.cpp.
 {
     load( jo );
 }
References load().
load()
void islot_engine::load (const JsonObject & jo)
Definition at line 2724 of file item_factory.cpp.
 {
     optional( jo, was_loaded, "displacement", displacement );
 }
References displacement, optional(), and was_loaded.
Referenced by deserialize().
Member Data Documentation
displacement
int islot_engine::displacement = 0
for combustion engines the displacement (cc)
Definition at line 633 of file itype.h.
Referenced by load().
item
friend islot_engine::item
Definition at line 629 of file itype.h.
Item_factory
friend islot_engine::Item_factory
Definition at line 628 of file itype.h.
was_loaded
bool islot_engine::was_loaded = false
Definition at line 635 of file itype.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/itype.h
src/item_factory.cpp