Cataclysm DDA: connect_group Struct Reference
connect_group Struct Reference
#include <mapdata.h>
Static Public Member Functions
static void load (const JsonObject &jo)
static void reset ()
Public Attributes
connect_group_id id
int index
std::set< ter_furn_flag > group_flags
std::set< ter_furn_flag > connects_to_flags
std::set< ter_furn_flag > rotates_to_flags
Detailed Description
Definition at line 337 of file mapdata.h.
Member Function Documentation
load()
void connect_group::load (const JsonObject & jo) static
Definition at line 288 of file mapdata.cpp.
 {
     connect_group result;
     result.id = connect_group_id( jo.get_string( "id" ) );
     result.index = ter_connects_map.find( result.id.str() ) == ter_connects_map.end() ?
                    ter_connects_map.size() : ter_connects_map[result.id.str()].index;
     // Check index overflow for bitsets
     if( result.index >= NUM_TERCONN ) {
         debugmsg( "Exceeded current maximum of %d connection groups.  Increase NUM_TERCONN to allow for more groups!",
                   NUM_TERCONN );
         return;
     }
     if( jo.has_string( "group_flags" ) || jo.has_array( "group_flags" ) ) {
         const std::vector<std::string> str_flags = jo.get_as_string_array( "group_flags" );
         for( const std::string &flag : str_flags ) {
             const ter_furn_flag f = io::string_to_enum<ter_furn_flag>( flag );
             result.group_flags.insert( f );
         }
     }
     if( jo.has_string( "connects_to_flags" ) || jo.has_array( "connects_to_flags" ) ) {
         const std::vector<std::string> str_flags = jo.get_as_string_array( "connects_to_flags" );
         for( const std::string &flag : str_flags ) {
             const ter_furn_flag f = io::string_to_enum<ter_furn_flag>( flag );
             result.connects_to_flags.insert( f );
         }
     }
     if( jo.has_string( "rotates_to_flags" ) || jo.has_array( "rotates_to_flags" ) ) {
         const std::vector<std::string> str_flags = jo.get_as_string_array( "rotates_to_flags" );
         for( const std::string &flag : str_flags ) {
             const ter_furn_flag f = io::string_to_enum<ter_furn_flag>( flag );
             result.rotates_to_flags.insert( f );
         }
     }
     ter_connects_map[ result.id.str() ] = result;
 }
References connects_to_flags, debugmsg, JsonObject::get_as_string_array(), JsonObject::get_string(), group_flags, JsonObject::has_array(), JsonObject::has_string(), id, index, NUM_TERCONN, rotates_to_flags, string_id< T >::str(), and ter_connects_map.
Referenced by DynamicDataLoader::initialize().
reset()
void connect_group::reset () static
Definition at line 330 of file mapdata.cpp.
 {
     ter_connects_map.clear();
 }
References ter_connects_map.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
connects_to_flags
std::set<ter_furn_flag> connect_group::connects_to_flags
Definition at line 342 of file mapdata.h.
Referenced by load().
group_flags
std::set<ter_furn_flag> connect_group::group_flags
Definition at line 341 of file mapdata.h.
Referenced by load().
id
connect_group_id connect_group::id
Definition at line 339 of file mapdata.h.
Referenced by load().
index
int connect_group::index
Definition at line 340 of file mapdata.h.
Referenced by load().
rotates_to_flags
std::set<ter_furn_flag> connect_group::rotates_to_flags
Definition at line 343 of file mapdata.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/mapdata.h
src/mapdata.cpp