Cataclysm DDA: event_transformation_impl::state Struct Reference
event_transformation_impl::state Struct Reference
Public Member Functions
state (const event_transformation_impl *trans, stats_tracker &stats)
void value_constraint_changed (stats_tracker &stats)
void event_added (const cata::event &e, stats_tracker &stats) override
void events_reset (const event_multiset &new_value, stats_tracker &stats) override
Public Member Functions inherited from stats_tracker_multiset_state
const cata_variant & get_value () const override
Public Member Functions inherited from stats_tracker_state
virtual ~stats_tracker_state ()=0
Public Member Functions inherited from base_watcher
base_watcher ()=default
base_watcher (const base_watcher &)=delete
base_watcher & operator= (const base_watcher &)=delete
Public Attributes
const event_transformation_impl * transformation_
event_multiset data_
std::list< updatable_value_constraint > cached_value_constraints_
Additional Inherited Members
Protected Member Functions inherited from base_watcher
virtual ~base_watcher ()
Detailed Description
Definition at line 459 of file event_statistics.cpp.
Constructor & Destructor Documentation
state()
event_transformation_impl::state::state (const event_transformation_impl * trans, stats_tracker & stats) inline
Definition at line 460 of file event_statistics.cpp.
                                                                               :
             transformation_( trans ),
             data_( trans->initialize( stats ) ),
             cached_value_constraints_( trans->make_cached_value_constraints( this, stats ) ) {
             cata_assert( cached_value_constraints_.size() == trans->constraints_.size() );
             trans->source_->add_watcher( stats, this );
         }
References event_source::add_watcher(), cached_value_constraints_, cata_assert, event_transformation_impl::constraints_, and event_transformation_impl::source_.
Member Function Documentation
event_added()
void event_transformation_impl::state::event_added (const cata::event & e, stats_tracker & stats) inline override virtual
Implements event_multiset_watcher.
Definition at line 473 of file event_statistics.cpp.
{
             EventVector transformed =
                 transformation_->match_and_transform( e.data(), cached_value_constraints_ );
             for( cata::event::data_type &d : transformed ) {
                 cata::event new_event( e.type(), e.time(), std::move( d ) );
                 data_.add( new_event );
                 stats.transformed_set_changed( transformation_->id_, new_event );
             }
         }
References event_multiset::add(), cached_value_constraints_, cata::event::data(), data_, event_transformation_impl::id_, event_transformation_impl::match_and_transform(), cata::event::time(), transformation_, and cata::event::type().
events_reset()
void event_transformation_impl::state::events_reset (const event_multiset & new_value, stats_tracker & stats) inline override virtual
Implements event_multiset_watcher.
Definition at line 483 of file event_statistics.cpp.
{
             data_ = transformation_->initialize(
                         new_value.counts(), cached_value_constraints_, stats );
             stats.transformed_set_changed( transformation_->id_, data_ );
         }
References cached_value_constraints_, event_multiset::counts(), data_, event_transformation_impl::id_, event_transformation_impl::initialize(), and transformation_.
value_constraint_changed()
void event_transformation_impl::state::value_constraint_changed (stats_tracker & stats) inline
Definition at line 468 of file event_statistics.cpp.
{
             data_ = transformation_->initialize( cached_value_constraints_, stats );
             stats.transformed_set_changed( transformation_->id_, data_ );
         }
References cached_value_constraints_, data_, event_transformation_impl::id_, event_transformation_impl::initialize(), and transformation_.
Referenced by event_transformation_impl::updatable_value_constraint::new_value().
Member Data Documentation
cached_value_constraints_
std::list<updatable_value_constraint> event_transformation_impl::state::cached_value_constraints_
Definition at line 491 of file event_statistics.cpp.
Referenced by event_added(), events_reset(), state(), and value_constraint_changed().
data_
event_multiset event_transformation_impl::state::data_
Definition at line 490 of file event_statistics.cpp.
Referenced by event_added(), events_reset(), and value_constraint_changed().
transformation_
const event_transformation_impl* event_transformation_impl::state::transformation_
Definition at line 489 of file event_statistics.cpp.
Referenced by event_added(), events_reset(), and value_constraint_changed().
The documentation for this struct was generated from the following file:
src/event_statistics.cpp