Cataclysm DDA: mutable_overmap_phase_remainder Struct Reference
mutable_overmap_phase_remainder Struct Reference
Classes
struct can_place_result
struct satisfy_result
Public Member Functions
bool all_rules_exhausted () const
std::optional< can_place_result > can_place (const overmap &om, const mutable_overmap_placement_rule_remainder &rule, const tripoint_om_omt &origin, om_direction::type dir, const joins_tracker &unresolved) const
satisfy_result satisfy (const overmap &om, const tripoint_om_omt &pos, const joins_tracker &unresolved)
Public Attributes
std::vector< mutable_overmap_placement_rule_remainder > rules
Detailed Description
Definition at line 2135 of file overmap.cpp.
Member Function Documentation
all_rules_exhausted()
bool mutable_overmap_phase_remainder::all_rules_exhausted () const inline
Definition at line 2156 of file overmap.cpp.
{
         return std::all_of( rules.begin(), rules.end(),
         []( const mutable_overmap_placement_rule_remainder & rule ) {
             return rule.is_exhausted();
         } );
     }
References rules.
Referenced by mutable_overmap_special_data::place().
can_place()
std::optional<can_place_result> mutable_overmap_phase_remainder::can_place (const overmap & om, const mutable_overmap_placement_rule_remainder & rule, const tripoint_om_omt & origin, om_direction::type dir, const joins_tracker & unresolved) const inline
Definition at line 2181 of file overmap.cpp.
             {
         int context_mandatory_joins_shortfall = 0;
         for( const mutable_overmap_piece_candidate piece : rule.pieces( origin, dir ) ) {
             if( !overmap::inbounds( piece.pos ) ) {
                 return std::nullopt;
             }
             if( !is_amongst_locations( om.ter( piece.pos ), piece.overmap->locations ) ) {
                 return std::nullopt;
             }
             if( unresolved.any_postponed_at( piece.pos ) ) {
                 return std::nullopt;
             }
             context_mandatory_joins_shortfall -= unresolved.count_unresolved_at( piece.pos );
         }
         int num_my_non_available_matched = 0;
         std::vector<om_pos_dir> suppressed_joins;
         for( const std::pair<om_pos_dir, const mutable_overmap_terrain_join *> p :
              rule.outward_joins( origin, dir ) ) {
             const om_pos_dir &pos_d = p.first;
             const mutable_overmap_terrain_join &ter_join = *p.second;
             const mutable_overmap_join &join = *ter_join.join;
             switch( unresolved.allows( pos_d, ter_join ) ) {
                 case joins_tracker::join_status::disallowed:
                     return std::nullopt;
                 case joins_tracker::join_status::matched_non_available:
                     ++context_mandatory_joins_shortfall;
                 // fallthrough
                 case joins_tracker::join_status::matched_available:
                     if( ter_join.type != join_type::available ) {
                         ++num_my_non_available_matched;
                     }
                     continue;
                 case joins_tracker::join_status::mismatched_available:
                     suppressed_joins.push_back( pos_d );
                 case joins_tracker::join_status::free:
                     break;
             }
             if( ter_join.type == join_type::available ) {
                 continue;
             }
             // Verify that the remaining joins lead to
             // suitable locations
             tripoint_om_omt neighbour = pos_d.p + displace( pos_d.dir );
             if( !overmap::inbounds( neighbour ) ) {
                 return std::nullopt;
             }
             const oter_id &neighbour_terrain = om.ter( neighbour );
             if( !is_amongst_locations( neighbour_terrain, join.into_locations ) ) {
                 return std::nullopt;
             }
         }
         return can_place_result{ context_mandatory_joins_shortfall,
                                  num_my_non_available_matched, suppressed_joins };
     }
References joins_tracker::allows(), joins_tracker::any_postponed_at(), available, joins_tracker::count_unresolved_at(), pos_dir< Tripoint >::dir, joins_tracker::disallowed, displace(), joins_tracker::free, overmap::inbounds(), mutable_overmap_join::into_locations, is_amongst_locations(), mutable_overmap_terrain_join::join, joins_tracker::matched_available, joins_tracker::matched_non_available, joins_tracker::mismatched_available, coords::om, mutable_overmap_placement_rule_remainder::outward_joins(), pos_dir< Tripoint >::p, mutable_overmap_placement_rule_remainder::pieces(), and mutable_overmap_terrain_join::type.
Referenced by satisfy().
satisfy()
satisfy_result mutable_overmap_phase_remainder::satisfy (const overmap & om, const tripoint_om_omt & pos, const joins_tracker & unresolved) inline
Definition at line 2244 of file overmap.cpp.
{
         weighted_int_list<satisfy_result> options;
         for( mutable_overmap_placement_rule_remainder &rule : rules ) {
             std::vector<satisfy_result> pos_dir_options;
             can_place_result best_result{ 0, 0, {} };
             for( om_direction::type dir : om_direction::all ) {
                 for( const tripoint_rel_omt &piece_pos : rule.positions( dir ) ) {
                     tripoint_om_omt origin = pos - piece_pos;
                     if( std::optional<can_place_result> result = can_place(
                                 om, rule, origin, dir, unresolved ) ) {
                         if( best_result < *result ) {
                             pos_dir_options.clear();
                             best_result = *result;
                         }
                         if( *result == best_result ) {
                             pos_dir_options.emplace_back( origin, dir, &rule, result.value().supressed_joins, std::string{} );
                         }
                     }
                 }
             }
             if( auto chosen_result = random_entry_opt( pos_dir_options ) ) {
                 options.add( *chosen_result, rule.get_weight() );
             }
         }
         std::string joins_s = enumerate_as_string( unresolved.all_unresolved_at( pos ),
         []( const joins_tracker::join * j ) {
             return string_format( "%s: %s", io::enum_to_string( j->where.dir ), j->join->id );
         } );
         if( satisfy_result *picked = options.pick() ) {
             om_direction::type dir = picked->dir;
             const mutable_overmap_placement_rule_remainder &rule = *picked->rule;
             picked->description =
                 string_format(
                     // NOLINTNEXTLINE(cata-translate-string-literal)
                     "At %s chose '%s' rot %d with neighbours N:%s E:%s S:%s W:%s and constraints "
                     "%s",
                     pos.to_string(), rule.description(), static_cast<int>( dir ),
                     om.ter( pos + point_north ).id().str(), om.ter( pos + point_east ).id().str(),
                     om.ter( pos + point_south ).id().str(), om.ter( pos + point_west ).id().str(),
                     joins_s );
             picked->rule->decrement();
             return *picked;
         } else {
             std::string rules_s = enumerate_as_string( rules,
             []( const mutable_overmap_placement_rule_remainder & rule ) {
                 if( rule.is_exhausted() ) {
                     return string_format( "(%s)", rule.description() );
                 } else {
                     return rule.description();
                 }
             } );
             std::string message =
                 string_format(
                     // NOLINTNEXTLINE(cata-translate-string-literal)
                     "At %s FAILED to match on terrain %s with neighbours N:%s E:%s S:%s W:%s and "
                     "constraints %s from amongst rules %s",
                     pos.to_string(), om.ter( pos ).id().str(),
                     om.ter( pos + point_north ).id().str(), om.ter( pos + point_east ).id().str(),
                     om.ter( pos + point_south ).id().str(), om.ter( pos + point_west ).id().str(),
                     joins_s, rules_s );
             return satisfy_result{ {}, om_direction::type::invalid, nullptr, std::vector<om_pos_dir>{}, std::move( message ) };
         }
     }
References om_direction::all, joins_tracker::all_unresolved_at(), can_place(), mutable_overmap_placement_rule_remainder::description(), enumerate_as_string(), om_direction::invalid, mutable_overmap_placement_rule_remainder::is_exhausted(), mapgen_defer::message, coords::om, PATH_INFO::options(), point_east, point_north, point_south, point_west, math_opers::pos(), random_entry_opt(), rules, and string_format().
Referenced by mutable_overmap_special_data::place().
Member Data Documentation
rules
std::vector<mutable_overmap_placement_rule_remainder> mutable_overmap_phase_remainder::rules
Definition at line 2136 of file overmap.cpp.
Referenced by all_rules_exhausted(), and satisfy().
The documentation for this struct was generated from the following file:
src/overmap.cpp