Cataclysm DDA: resistances Struct Reference
resistances Struct Reference
#include <damage.h>
Public Member Functions
resistances ()=default
resistances (const item &armor, bool to_self=false, int roll=0, const bodypart_id &bp=bodypart_id())
resistances (const item &armor, bool to_self, int roll, const sub_bodypart_id &bp)
resistances (monster &monster)
void set_resist (const damage_type_id &dt, float amount)
float type_resist (const damage_type_id &dt) const
float get_effective_resist (const damage_unit &du) const
resistances & operator+= (const resistances &other)
bool operator== (const resistances &other)
resistances operator* (float mod) const
resistances operator/ (float mod) const
Public Attributes
std::unordered_map< damage_type_id, float > resist_vals
Detailed Description
Definition at line 204 of file damage.h.
Constructor & Destructor Documentation
resistances() [1/4]
resistances::resistances () default
resistances() [2/4]
resistances::resistances (const item & armor, bool to_self = false, int roll = 0, const bodypart_id & bp = bodypart_id()) explicit
Definition at line 594 of file damage.cpp.
 {
     // Armors protect, but all items can resist
     if( to_self || armor.is_armor() || armor.is_pet_armor() ) {
         for( const damage_type &dam : damage_type::get_all() ) {
             set_resist( dam.id, armor.resist( dam.id, to_self, bp, roll ) );
         }
     }
 }
References bp, damage_type::get_all(), item::is_armor(), item::is_pet_armor(), and item::resist().
resistances() [3/4]
resistances::resistances (const item & armor, bool to_self, int roll, const sub_bodypart_id & bp) explicit
Definition at line 604 of file damage.cpp.
 {
     // Armors protect, but all items can resist
     if( to_self || armor.is_armor() ) {
         for( const damage_type &dam : damage_type::get_all() ) {
             set_resist( dam.id, armor.resist( dam.id, to_self, bp, roll ) );
         }
     }
 }
References bp, damage_type::get_all(), item::is_armor(), and item::resist().
resistances() [4/4]
resistances::resistances (monster & monster) explicit
Definition at line 614 of file damage.cpp.
                                            : resistances( monster.type->armor )
 {
 }
Member Function Documentation
get_effective_resist()
float resistances::get_effective_resist (const damage_unit & du) const
Definition at line 627 of file damage.cpp.
 {
     return std::max( type_resist( du.type ) - du.res_pen,
                      0.0f ) * du.res_mult * du.unconditional_res_mult;
 }
References max(), damage_unit::res_mult, damage_unit::res_pen, damage_unit::type, type_resist(), and damage_unit::unconditional_res_mult.
Referenced by monster::absorb_hit(), body_part_type::damage_resistance(), item::effective_dps(), item::mitigate_damage(), and Character::mutation_armor().
operator*()
resistances resistances::operator* (float mod) const
Definition at line 644 of file damage.cpp.
 {
     resistances ret;
     for( const auto &dam : resist_vals ) {
         ret.resist_vals[dam.first] = dam.second * mod;
     }
     return ret;
 }
References resist_vals, and cata::hash64_detail::ret.
operator+=()
resistances& resistances::operator+= (const resistances & other) inline
Definition at line 219 of file damage.h.
{
         for( const auto &dam : other.resist_vals ) {
             resist_vals[dam.first] += dam.second;
         }
         return *this;
     }
References other, and resist_vals.
operator/()
resistances resistances::operator/ (float mod) const
Definition at line 653 of file damage.cpp.
 {
     resistances ret;
     for( const auto &dam : resist_vals ) {
         ret.resist_vals[dam.first] = dam.second / mod;
     }
     return ret;
 }
References resist_vals, and cata::hash64_detail::ret.
operator==()
bool resistances::operator== (const resistances & other)
Definition at line 633 of file damage.cpp.
 {
     for( const auto &dam : other.resist_vals ) {
         if( resist_vals.count( dam.first ) <= 0 || resist_vals[dam.first] != dam.second ) {
             return false;
         }
     }
     return true;
 }
References other, and resist_vals.
set_resist()
void resistances::set_resist (const damage_type_id & dt, float amount)
Definition at line 618 of file damage.cpp.
 {
     resist_vals[dt] = amount;
 }
References resist_vals.
type_resist()
float resistances::type_resist (const damage_type_id & dt) const
Definition at line 622 of file damage.cpp.
 {
     auto iter = resist_vals.find( dt );
     return ( iter == resist_vals.end() || iter->first->no_resist ) ? 0.0f : iter->second;
 }
References resist_vals.
Referenced by item::armor_protection_info(), Character::best_part_to_smash(), anonymous_namespace{armor_layers.cpp}::clothing_protection(), anonymous_namespace{armor_layers.cpp}::collect_protection_subvalues(), body_part_type::damage_resistance(), monster::get_armor_type(), get_effective_resist(), material_type::load(), item::mitigate_damage(), Character::mutation_armor(), bodygraph_display::prepare_infotext(), and material_type::resist().
Member Data Documentation
resist_vals
std::unordered_map<damage_type_id, float> resistances::resist_vals
Definition at line 205 of file damage.h.
Referenced by weakpoint::apply_to(), item::armor_protection_info(), body_part_type::check(), material_type::check(), extend_resistances_instance(), body_part_type::finalize(), material_type::finalize_all(), MonsterGenerator::finalize_mtypes(), MonsterGenerator::generate_fake_pseudo_dormant_monster(), operator*(), operator+=(), operator/(), operator==(), set_resist(), and type_resist().
The documentation for this struct was generated from the following files:
src/damage.h
src/damage.cpp