Cataclysm DDA: achievement_state Struct Reference
achievement_state Struct Reference
#include <achievement.h>
Public Member Functions
std::string ui_text (const achievement *) const
void serialize (JsonOut &) const
void deserialize (const JsonObject &jo)
Public Attributes
achievement_completion completion
time_point last_state_change
std::vector< cata_variant > final_values
Detailed Description
Definition at line 146 of file achievement.h.
Member Function Documentation
deserialize()
void achievement_state::deserialize (const JsonObject & jo)
Definition at line 646 of file achievement.cpp.
 {
     jo.read( "completion", completion );
     jo.read( "last_state_change", last_state_change );
     jo.read( "final_values", final_values );
 }
References JsonObject::read().
serialize()
void achievement_state::serialize (JsonOut & jsout) const
Definition at line 637 of file achievement.cpp.
 {
     jsout.start_object();
     jsout.member_as_string( "completion", completion );
     jsout.member( "last_state_change", last_state_change );
     jsout.member( "final_values", final_values );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), JsonOut::member_as_string(), and JsonOut::start_object().
ui_text()
std::string achievement_state::ui_text (const achievement * ach) const
Definition at line 596 of file achievement.cpp.
 {
     // First: the achievement name and description
     nc_color c = color_from_completion( ach->is_conduct(), completion, false );
     nc_color c_title = color_from_completion( ach->is_conduct(), completion, true );
     std::string result = colorize( ach->name(), c_title ) + "\n";
     if( !ach->description().empty() ) {
         result += "  " + colorize( ach->description(), c ) + "\n";
     }
     if( completion == achievement_completion::completed ) {
         std::string message = string_format(
                                   _( "Completed %s" ), to_string( last_state_change ) );
         result += "  " + colorize( message, c ) + "\n";
     } else if( completion == achievement_completion::failed ) {
         std::string message = string_format(
                                   _( "Failed %s" ), to_string( last_state_change ) );
         result += "  " + colorize( message, c ) + "\n";
     } else {
         // Next: the time constraint
         if( ach->time_constraint() ) {
             result += "  " + ach->time_constraint()->ui_text( ach->is_conduct() ) + "\n";
         }
     }
     // Next: the requirements
     const std::vector<achievement_requirement> &reqs = ach->requirements();
     // If these two vectors are of different sizes then the definition must
     // have changed since it was completed / failed, so we don't print any
     // requirements info.
     std::vector<std::optional<std::string>> req_texts;
     if( final_values.size() == reqs.size() ) {
         for( size_t i = 0; i < final_values.size(); ++i ) {
             req_texts.push_back( text_for_requirement( reqs[i], final_values[i], completion ) );
         }
         result += format_requirements( req_texts, c );
     }
     return result;
 }
References _, c, color_from_completion(), colorize(), completed, achievement::description(), translation::empty(), failed, format_requirements(), achievement::is_conduct(), mapgen_defer::message, achievement::name(), achievement::requirements(), string_format(), text_for_requirement(), achievement::time_constraint(), and to_string().
Member Data Documentation
completion
achievement_completion achievement_state::completion
Definition at line 148 of file achievement.h.
final_values
std::vector<cata_variant> achievement_state::final_values
Definition at line 154 of file achievement.h.
last_state_change
time_point achievement_state::last_state_change
Definition at line 151 of file achievement.h.
The documentation for this struct was generated from the following files:
src/achievement.h
src/achievement.cpp