Cataclysm DDA: editmap_hilight Struct Reference
editmap_hilight Struct Reference
#include <editmap.h>
Public Member Functions
void setup ()
void draw (editmap &em, bool update=false)
Public Attributes
std::vector< bool > blink_interval
int cur_blink = 0
nc_color color
std::map< tripoint, char > points
nc_color(* getbg)(const nc_color &)
Detailed Description
Definition at line 32 of file editmap.h.
Member Function Documentation
draw()
void editmap_hilight::draw (editmap & em, bool update = false)
Definition at line 216 of file editmap.cpp.
 {
     cur_blink++;
     if( cur_blink >= static_cast<int>( blink_interval.size() ) ) {
         cur_blink = 0;
     }
     creature_tracker &creatures = get_creature_tracker();
     if( blink_interval[ cur_blink ] || update ) {
         map &here = get_map();
         for( auto &elem : points ) {
             const tripoint &p = elem.first;
             // but only if there's no vehicles/mobs/npcs on a point
             if( !here.veh_at( p ) && !creatures.creature_at( p ) ) {
                 const ter_t &terrain = here.ter( p ).obj();
                 char t_sym = terrain.symbol();
                 nc_color t_col = terrain.color();
                 if( here.furn( p ).to_i() > 0 ) {
                     const furn_t &furniture_type = here.furn( p ).obj();
                     t_sym = furniture_type.symbol();
                     t_col = furniture_type.color();
                 }
                 const field &t_field = here.field_at( p );
                 if( t_field.field_count() > 0 ) {
                     field_type_id t_ftype = t_field.displayed_field_type();
                     const field_entry *t_fld = t_field.find_field( t_ftype );
                     if( t_fld != nullptr ) {
                         t_col = t_fld->color();
                         t_sym = t_fld->symbol()[0];
                     }
                 }
                 if( blink_interval[ cur_blink ] ) {
                     t_col = getbg( t_col );
                 }
                 tripoint scrpos = em.pos2screen( p );
                 mvwputch( g->w_terrain, scrpos.xy(), t_col, t_sym );
             }
         }
     }
 }
References blink_interval, field_entry::color(), map_data_common_t::color(), creature_tracker::creature_at(), cur_blink, field::displayed_field_type(), map::field_at(), field::field_count(), field::find_field(), map::furn(), g, get_creature_tracker(), get_map(), getbg, mvwputch(), int_id< T >::obj(), points, editmap::pos2screen(), field_entry::symbol(), map_data_common_t::symbol(), map::ter(), terrain, int_id< T >::to_i(), map::veh_at(), and tripoint::xy().
setup()
void editmap_hilight::setup () inline
Definition at line 38 of file editmap.h.
                  {
         getbg = color == c_red ? &red_background :
                 color == c_magenta ? &magenta_background :
                 color == c_cyan ? &cyan_background :
                 color == c_yellow ? &yellow_background : &green_background;
     }
References c_cyan, c_magenta, c_red, c_yellow, color, cyan_background(), getbg, green_background(), magenta_background(), red_background(), and yellow_background().
Member Data Documentation
blink_interval
std::vector<bool> editmap_hilight::blink_interval
Definition at line 33 of file editmap.h.
Referenced by draw().
color
nc_color editmap_hilight::color
Definition at line 35 of file editmap.h.
Referenced by setup().
cur_blink
int editmap_hilight::cur_blink = 0
Definition at line 34 of file editmap.h.
Referenced by draw().
getbg
nc_color(* editmap_hilight::getbg) (const nc_color &)
Definition at line 37 of file editmap.h.
Referenced by draw(), and setup().
points
std::map<tripoint, char> editmap_hilight::points
Definition at line 36 of file editmap.h.
Referenced by draw().
The documentation for this struct was generated from the following files:
src/editmap.h
src/editmap.cpp