Cataclysm DDA: activity_reason_info Struct Reference
activity_reason_info Struct Reference
#include <activity_handlers.h>
Public Member Functions
activity_reason_info (do_activity_reason reason_, bool can_do_, const std::optional< construction_id > &con_idx_=std::nullopt)
activity_reason_info (do_activity_reason reason_, bool can_do_, const requirement_data &req)
Static Public Member Functions
static activity_reason_info ok (const do_activity_reason &reason_)
static activity_reason_info build (const do_activity_reason &reason_, bool can_do_, const construction_id &con_idx_)
static activity_reason_info fail (const do_activity_reason &reason_)
Public Attributes
do_activity_reason reason
bool can_do
std::optional< construction_id > con_idx
const requirement_data req
Detailed Description
Definition at line 122 of file activity_handlers.h.
Constructor & Destructor Documentation
activity_reason_info() [1/2]
activity_reason_info::activity_reason_info (do_activity_reason reason_, bool can_do_, const std::optional< construction_id > & con_idx_ = std::nullopt) inline
Definition at line 130 of file activity_handlers.h.
                                                                                       :
         reason( reason_ ),
         can_do( can_do_ ),
         con_idx( con_idx_ )
     { }
Referenced by build(), fail(), and ok().
activity_reason_info() [2/2]
activity_reason_info::activity_reason_info (do_activity_reason reason_, bool can_do_, const requirement_data & req) inline
Definition at line 136 of file activity_handlers.h.
                                                                                                  :
         reason( reason_ ),
         can_do( can_do_ ),
         req( req )
     { }
Member Function Documentation
build()
static activity_reason_info activity_reason_info::build (const do_activity_reason & reason_, bool can_do_, const construction_id & con_idx_) inline static
Definition at line 148 of file activity_handlers.h.
{
         return activity_reason_info( reason_, can_do_, con_idx_ );
     }
References activity_reason_info().
Referenced by find_base_construction().
fail()
static activity_reason_info activity_reason_info::fail (const do_activity_reason & reason_) inline static
Definition at line 153 of file activity_handlers.h.
{
         return activity_reason_info( reason_, false );
     }
References activity_reason_info().
Referenced by can_do_activity_there().
ok()
static activity_reason_info activity_reason_info::ok (const do_activity_reason & reason_) inline static
Definition at line 144 of file activity_handlers.h.
{
         return activity_reason_info( reason_, true );
     }
References activity_reason_info().
Referenced by can_do_activity_there().
Member Data Documentation
can_do
bool activity_reason_info::can_do
Definition at line 126 of file activity_handlers.h.
Referenced by generic_multi_activity_check_requirement().
con_idx
std::optional<construction_id> activity_reason_info::con_idx
Definition at line 128 of file activity_handlers.h.
Referenced by construction_activity(), and generic_multi_activity_check_requirement().
reason
do_activity_reason activity_reason_info::reason
Definition at line 124 of file activity_handlers.h.
Referenced by generic_multi_activity_check_requirement(), and generic_multi_activity_do().
req
const requirement_data activity_reason_info::req
Definition at line 142 of file activity_handlers.h.
Referenced by generic_multi_activity_check_requirement().
The documentation for this struct was generated from the following file:
src/activity_handlers.h