Cataclysm DDA: JsonPath Struct Reference
JsonPath Struct Reference
#include <flexbuffer_json.h>
Public Types
using index_type = uint32_t
Public Member Functions
JsonPath ()=default
JsonPath (const JsonPath &)=default
JsonPath (JsonPath &&)=default
JsonPath & operator= (const JsonPath &)=default
JsonPath & operator= (JsonPath &&) noexcept=default
JsonPath & push_back (size_t idx)
uint8_t size () const
void pop_back ()
index_type & last ()
index_type const * begin () const
index_type const * end () const
Private Attributes
small_literal_vector< index_type, kInlinePathSegments > path_
Static Private Attributes
static constexpr size_t kInlinePathSegments = 7
Friends
JsonPath operator+ (const JsonPath &lhs, size_t idx)
Detailed Description
Definition at line 22 of file flexbuffer_json.h.
Member Typedef Documentation
index_type
using JsonPath::index_type = uint32_t
Definition at line 31 of file flexbuffer_json.h.
Constructor & Destructor Documentation
JsonPath() [1/3]
JsonPath::JsonPath () default
JsonPath() [2/3]
JsonPath::JsonPath (const JsonPath &) default
JsonPath() [3/3]
JsonPath::JsonPath (JsonPath &&) default
Member Function Documentation
begin()
index_type const* JsonPath::begin () const inline
Definition at line 61 of file flexbuffer_json.h.
{
             return path_.begin();
         }
References small_literal_vector< T, kInlineCount, SizeT >::begin(), and path_.
end()
index_type const* JsonPath::end () const inline
Definition at line 64 of file flexbuffer_json.h.
{
             return path_.end();
         }
References small_literal_vector< T, kInlineCount, SizeT >::end(), and path_.
last()
index_type& JsonPath::last () inline
Definition at line 57 of file flexbuffer_json.h.
{
             return *path_.back();
         }
References small_literal_vector< T, kInlineCount, SizeT >::back(), and path_.
Referenced by JsonArray::next_enum_value().
operator=() [1/2]
JsonPath& JsonPath::operator= (const JsonPath &) default
operator=() [2/2]
JsonPath& JsonPath::operator= (JsonPath &&) default noexcept
pop_back()
void JsonPath::pop_back () inline
Definition at line 53 of file flexbuffer_json.h.
{
             path_.pop_back();
         }
References path_, and small_literal_vector< T, kInlineCount, SizeT >::pop_back().
push_back()
JsonPath& JsonPath::push_back (size_t idx) inline
Definition at line 40 of file flexbuffer_json.h.
{
             if( idx < std::numeric_limits<index_type>::max() ) {
                 path_.push_back( static_cast<index_type>( idx ) );
             } else {
                 throw std::runtime_error( "Json index out of range of uint32_t" );
             }
             return *this;
         }
References max(), path_, and small_literal_vector< T, kInlineCount, SizeT >::push_back().
size()
uint8_t JsonPath::size () const inline
Definition at line 49 of file flexbuffer_json.h.
{
             return path_.size();
         }
References path_, and small_literal_vector< T, kInlineCount, SizeT >::size().
Friends And Related Function Documentation
operator+
JsonPath operator+ (const JsonPath & lhs, size_t idx) friend
Definition at line 68 of file flexbuffer_json.h.
{
             JsonPath ret( lhs );
             ret.push_back( idx );
             return ret;
         }
Member Data Documentation
kInlinePathSegments
constexpr size_t JsonPath::kInlinePathSegments = 7 static constexpr private
Definition at line 75 of file flexbuffer_json.h.
path_
small_literal_vector<index_type, kInlinePathSegments> JsonPath::path_ private
Definition at line 76 of file flexbuffer_json.h.
Referenced by begin(), end(), last(), pop_back(), push_back(), and size().
The documentation for this struct was generated from the following file:
src/flexbuffer_json.h