Cataclysm DDA: dialogue_chatbin_snippets Struct Reference
dialogue_chatbin_snippets Struct Reference
#include <dialogue_chatbin.h>
Public Attributes
translation snip_camp_food_thanks = no_translation("<camp_food_thanks>")
translation snip_camp_larder_empty = no_translation("<camp_larder_empty>")
translation snip_camp_water_thanks = no_translation("<camp_water_thanks>")
translation snip_cant_flee = no_translation("<cant_flee>")
translation snip_close_distance = no_translation("<close_distance>")
translation snip_combat_noise_warning = no_translation("<combat_noise_warning>")
translation snip_danger_close_distance = no_translation("<danger_close_distance>")
translation snip_done_mugging = no_translation("<done_mugging>")
translation snip_far_distance = no_translation("<far_distance>")
translation snip_fire_bad = no_translation("<fire_bad>")
translation snip_fire_in_the_hole_h = no_translation("<fire_in_the_hole_h>")
translation snip_fire_in_the_hole = no_translation("<fire_in_the_hole>")
translation snip_general_danger_h = no_translation("<general_danger_h>")
translation snip_general_danger = no_translation("<general_danger>")
translation snip_heal_self = no_translation("<heal_self>")
translation snip_hungry = no_translation("<hungry>")
translation snip_im_leaving_you = no_translation("<im_leaving_you>")
translation snip_its_safe_h = no_translation("<its_safe_h>")
translation snip_its_safe = no_translation("<its_safe>")
translation snip_keep_up = no_translation("<keep_up>")
translation snip_kill_npc_h = no_translation("<kill_npc_h>")
translation snip_kill_npc = no_translation("<kill_npc>")
translation snip_kill_player_h = no_translation("<kill_player_h>")
translation snip_let_me_pass = no_translation("<let_me_pass>")
translation snip_lets_talk = no_translation("<lets_talk>")
translation snip_medium_distance = no_translation("<medium_distance>")
translation snip_monster_warning_h = no_translation("<monster_warning_h>")
translation snip_monster_warning = no_translation("<monster_warning>")
translation snip_movement_noise_warning = no_translation("<movement_noise_warning>")
translation snip_need_batteries = no_translation("<need_batteries>")
translation snip_need_booze = no_translation("<need_booze>")
translation snip_need_fuel = no_translation("<need_fuel>")
translation snip_no_to_thorazine = no_translation("<no_to_thorazine>")
translation snip_run_away = no_translation("<run_away>")
translation snip_speech_warning = no_translation("<speech_warning>")
translation snip_thirsty = no_translation("<thirsty>")
translation snip_wait = no_translation("<wait>")
translation snip_warn_sleep = no_translation("<warn_sleep>")
translation snip_yawn = no_translation("<yawn>")
translation snip_yes_to_lsd = no_translation("<yes_to_lsd>")
translation snip_mug_dontmove = to_translation("Don't move a <swear> muscle…")
translation snip_lost_blood = to_translation("I've lost lot of blood.")
translation snip_pulp_zombie = to_translation("Hold on, I want to pulp that %s.")
translation snip_heal_player = to_translation("Hold still %s, I'm coming to help you.")
translation snip_wound_infected = to_translation("My %s wound is infected…")
translation snip_wound_bite = to_translation("The bite wound on my %s looks bad.")
translation snip_bleeding = to_translation("My %s is bleeding!")
translation snip_bleeding_badly = to_translation("My %s is bleeding badly!")
translation snip_radiation_sickness = to_translation("I'm suffering from radiation sickness…")
translation snip_acknowledged = no_translation("<acknowledged>")
translation snip_bye = to_translation("Bye.")
translation snip_consume_cant_accept
translation snip_consume_cant_consume
translation snip_consume_rotten = to_translation("This is rotten! I won't eat that.")
translation snip_consume_eat = to_translation("Thanks, that hit the spot.")
translation snip_consume_need_item = to_translation("I need a %s to consume that!")
translation snip_consume_med = to_translation("Thanks, I feel better already.")
translation snip_consume_nocharge
translation snip_consume_use_med = to_translation("Thanks, I used it.")
translation snip_give_nope = to_translation("Nope.")
translation snip_give_to_hallucination = to_translation("No thanks, I'm good.")
translation snip_give_cancel = to_translation("Changed your mind?")
translation snip_give_dangerous = to_translation("Are you <swear> insane!?")
translation snip_give_wield = to_translation("Thanks, I'll wield that now.")
translation snip_give_weapon_weak = to_translation("My current weapon is better than this.\n")
translation snip_give_carry = to_translation("Thanks, I'll carry that now.")
translation snip_give_carry_cant = to_translation("I have no space to store it.")
translation snip_give_carry_cant_few_space = to_translation("I can only store %s %s more.")
translation snip_give_carry_cant_no_space
translation snip_give_carry_too_heavy = to_translation("It is too heavy for me to carry.")
translation snip_wear = to_translation("Thanks, I'll wear that now.")
Detailed Description
Definition at line 81 of file dialogue_chatbin.h.
Member Data Documentation
snip_acknowledged
translation dialogue_chatbin_snippets::snip_acknowledged = no_translation("<acknowledged>")
Definition at line 134 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_bleeding
translation dialogue_chatbin_snippets::snip_bleeding = to_translation("My %s is bleeding!")
Definition at line 129 of file dialogue_chatbin.h.
Referenced by npc::complain(), and npc_template::load().
snip_bleeding_badly
translation dialogue_chatbin_snippets::snip_bleeding_badly = to_translation("My %s is bleeding badly!")
Definition at line 130 of file dialogue_chatbin.h.
Referenced by npc::complain(), and npc_template::load().
snip_bye
translation dialogue_chatbin_snippets::snip_bye = to_translation("Bye.")
Definition at line 135 of file dialogue_chatbin.h.
Referenced by dialogue::dynamic_line(), npc_template::load(), and avatar::talk_to().
snip_camp_food_thanks
translation dialogue_chatbin_snippets::snip_camp_food_thanks = no_translation("<camp_food_thanks>")
Definition at line 83 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_camp_larder_empty
translation dialogue_chatbin_snippets::snip_camp_larder_empty = no_translation("<camp_larder_empty>")
Definition at line 84 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_camp_water_thanks
translation dialogue_chatbin_snippets::snip_camp_water_thanks = no_translation("<camp_water_thanks>")
Definition at line 85 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_cant_flee
translation dialogue_chatbin_snippets::snip_cant_flee = no_translation("<cant_flee>")
Definition at line 86 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_close_distance
translation dialogue_chatbin_snippets::snip_close_distance = no_translation("<close_distance>")
Definition at line 87 of file dialogue_chatbin.h.
Referenced by npc::distance_string(), and npc_template::load().
snip_combat_noise_warning
translation dialogue_chatbin_snippets::snip_combat_noise_warning = no_translation("<combat_noise_warning>")
Definition at line 88 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_consume_cant_accept
translation dialogue_chatbin_snippets::snip_consume_cant_accept
Initial value:
=
        to_translation( "I don't <swear> trust you enough to eat THIS…" )
Definition at line 138 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and try_consume().
snip_consume_cant_consume
translation dialogue_chatbin_snippets::snip_consume_cant_consume
Initial value:
=
        to_translation( "It doesn't look like a good idea to consume this…" )
Definition at line 140 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and try_consume().
snip_consume_eat
translation dialogue_chatbin_snippets::snip_consume_eat = to_translation("Thanks, that hit the spot.")
Definition at line 143 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and try_consume().
snip_consume_med
translation dialogue_chatbin_snippets::snip_consume_med = to_translation("Thanks, I feel better already.")
Definition at line 145 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and try_consume().
snip_consume_need_item
translation dialogue_chatbin_snippets::snip_consume_need_item = to_translation("I need a %s to consume that!")
Definition at line 144 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and try_consume().
snip_consume_nocharge
translation dialogue_chatbin_snippets::snip_consume_nocharge
Initial value:
=
        to_translation( "It doesn't look like a good idea to consume this…" )
Definition at line 146 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and try_consume().
snip_consume_rotten
translation dialogue_chatbin_snippets::snip_consume_rotten = to_translation("This is rotten! I won't eat that.")
Definition at line 142 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and try_consume().
snip_consume_use_med
translation dialogue_chatbin_snippets::snip_consume_use_med = to_translation("Thanks, I used it.")
Definition at line 148 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and try_consume().
snip_danger_close_distance
translation dialogue_chatbin_snippets::snip_danger_close_distance = no_translation("<danger_close_distance>")
Definition at line 89 of file dialogue_chatbin.h.
Referenced by npc::distance_string(), and npc_template::load().
snip_done_mugging
translation dialogue_chatbin_snippets::snip_done_mugging = no_translation("<done_mugging>")
Definition at line 90 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_far_distance
translation dialogue_chatbin_snippets::snip_far_distance = no_translation("<far_distance>")
Definition at line 91 of file dialogue_chatbin.h.
Referenced by npc::distance_string(), and npc_template::load().
snip_fire_bad
translation dialogue_chatbin_snippets::snip_fire_bad = no_translation("<fire_bad>")
Definition at line 92 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_fire_in_the_hole
translation dialogue_chatbin_snippets::snip_fire_in_the_hole = no_translation("<fire_in_the_hole>")
Definition at line 94 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_fire_in_the_hole_h
translation dialogue_chatbin_snippets::snip_fire_in_the_hole_h = no_translation("<fire_in_the_hole_h>")
Definition at line 93 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_general_danger
translation dialogue_chatbin_snippets::snip_general_danger = no_translation("<general_danger>")
Definition at line 96 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_general_danger_h
translation dialogue_chatbin_snippets::snip_general_danger_h = no_translation("<general_danger_h>")
Definition at line 95 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_give_cancel
translation dialogue_chatbin_snippets::snip_give_cancel = to_translation("Changed your mind?")
Definition at line 151 of file dialogue_chatbin.h.
Referenced by talker_npc::give_item_to(), and npc_template::load().
snip_give_carry
translation dialogue_chatbin_snippets::snip_give_carry = to_translation("Thanks, I'll carry that now.")
Definition at line 155 of file dialogue_chatbin.h.
Referenced by talker_npc::give_item_to(), and npc_template::load().
snip_give_carry_cant
translation dialogue_chatbin_snippets::snip_give_carry_cant = to_translation("I have no space to store it.")
Definition at line 156 of file dialogue_chatbin.h.
Referenced by talker_npc::give_item_to(), and npc_template::load().
snip_give_carry_cant_few_space
translation dialogue_chatbin_snippets::snip_give_carry_cant_few_space = to_translation("I can only store %s %s more.")
Definition at line 157 of file dialogue_chatbin.h.
Referenced by talker_npc::give_item_to(), and npc_template::load().
snip_give_carry_cant_no_space
translation dialogue_chatbin_snippets::snip_give_carry_cant_no_space
Initial value:
=
        to_translation( "…or to store anything else for that matter." )
Definition at line 158 of file dialogue_chatbin.h.
Referenced by talker_npc::give_item_to(), and npc_template::load().
snip_give_carry_too_heavy
translation dialogue_chatbin_snippets::snip_give_carry_too_heavy = to_translation("It is too heavy for me to carry.")
Definition at line 160 of file dialogue_chatbin.h.
Referenced by talker_npc::give_item_to(), and npc_template::load().
snip_give_dangerous
translation dialogue_chatbin_snippets::snip_give_dangerous = to_translation("Are you <swear> insane!?")
Definition at line 152 of file dialogue_chatbin.h.
Referenced by talker_npc::give_item_to(), and npc_template::load().
snip_give_nope
translation dialogue_chatbin_snippets::snip_give_nope = to_translation("Nope.")
Definition at line 149 of file dialogue_chatbin.h.
Referenced by talker_npc::give_item_to(), and npc_template::load().
snip_give_to_hallucination
translation dialogue_chatbin_snippets::snip_give_to_hallucination = to_translation("No thanks, I'm good.")
Definition at line 150 of file dialogue_chatbin.h.
Referenced by talker_npc::give_item_to(), and npc_template::load().
snip_give_weapon_weak
translation dialogue_chatbin_snippets::snip_give_weapon_weak = to_translation("My current weapon is better than this.\n")
Definition at line 154 of file dialogue_chatbin.h.
Referenced by talker_npc::give_item_to(), and npc_template::load().
snip_give_wield
translation dialogue_chatbin_snippets::snip_give_wield = to_translation("Thanks, I'll wield that now.")
Definition at line 153 of file dialogue_chatbin.h.
Referenced by talker_npc::give_item_to(), and npc_template::load().
snip_heal_player
translation dialogue_chatbin_snippets::snip_heal_player = to_translation("Hold still %s, I'm coming to help you.")
Definition at line 126 of file dialogue_chatbin.h.
Referenced by npc::execute_action(), and npc_template::load().
snip_heal_self
translation dialogue_chatbin_snippets::snip_heal_self = no_translation("<heal_self>")
Definition at line 97 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_hungry
translation dialogue_chatbin_snippets::snip_hungry = no_translation("<hungry>")
Definition at line 98 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_im_leaving_you
translation dialogue_chatbin_snippets::snip_im_leaving_you = no_translation("<im_leaving_you>")
Definition at line 99 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_its_safe
translation dialogue_chatbin_snippets::snip_its_safe = no_translation("<its_safe>")
Definition at line 101 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_its_safe_h
translation dialogue_chatbin_snippets::snip_its_safe_h = no_translation("<its_safe_h>")
Definition at line 100 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_keep_up
translation dialogue_chatbin_snippets::snip_keep_up = no_translation("<keep_up>")
Definition at line 102 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_kill_npc
translation dialogue_chatbin_snippets::snip_kill_npc = no_translation("<kill_npc>")
Definition at line 104 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_kill_npc_h
translation dialogue_chatbin_snippets::snip_kill_npc_h = no_translation("<kill_npc_h>")
Definition at line 103 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_kill_player_h
translation dialogue_chatbin_snippets::snip_kill_player_h = no_translation("<kill_player_h>")
Definition at line 105 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_let_me_pass
translation dialogue_chatbin_snippets::snip_let_me_pass = no_translation("<let_me_pass>")
Definition at line 106 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_lets_talk
translation dialogue_chatbin_snippets::snip_lets_talk = no_translation("<lets_talk>")
Definition at line 107 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_lost_blood
translation dialogue_chatbin_snippets::snip_lost_blood = to_translation("I've lost lot of blood.")
Definition at line 124 of file dialogue_chatbin.h.
Referenced by npc::complain(), and npc_template::load().
snip_medium_distance
translation dialogue_chatbin_snippets::snip_medium_distance = no_translation("<medium_distance>")
Definition at line 108 of file dialogue_chatbin.h.
Referenced by npc::distance_string(), and npc_template::load().
snip_monster_warning
translation dialogue_chatbin_snippets::snip_monster_warning = no_translation("<monster_warning>")
Definition at line 110 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_monster_warning_h
translation dialogue_chatbin_snippets::snip_monster_warning_h = no_translation("<monster_warning_h>")
Definition at line 109 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_movement_noise_warning
translation dialogue_chatbin_snippets::snip_movement_noise_warning = no_translation("<movement_noise_warning>")
Definition at line 111 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_mug_dontmove
translation dialogue_chatbin_snippets::snip_mug_dontmove = to_translation("Don't move a <swear> muscle…")
Definition at line 123 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_need_batteries
translation dialogue_chatbin_snippets::snip_need_batteries = no_translation("<need_batteries>")
Definition at line 112 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_need_booze
translation dialogue_chatbin_snippets::snip_need_booze = no_translation("<need_booze>")
Definition at line 113 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_need_fuel
translation dialogue_chatbin_snippets::snip_need_fuel = no_translation("<need_fuel>")
Definition at line 114 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_no_to_thorazine
translation dialogue_chatbin_snippets::snip_no_to_thorazine = no_translation("<no_to_thorazine>")
Definition at line 115 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_pulp_zombie
translation dialogue_chatbin_snippets::snip_pulp_zombie = to_translation("Hold on, I want to pulp that %s.")
Definition at line 125 of file dialogue_chatbin.h.
Referenced by npc::find_corpse_to_pulp(), and npc_template::load().
snip_radiation_sickness
translation dialogue_chatbin_snippets::snip_radiation_sickness = to_translation("I'm suffering from radiation sickness…")
Definition at line 131 of file dialogue_chatbin.h.
Referenced by npc::complain(), and npc_template::load().
snip_run_away
translation dialogue_chatbin_snippets::snip_run_away = no_translation("<run_away>")
Definition at line 116 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_speech_warning
translation dialogue_chatbin_snippets::snip_speech_warning = no_translation("<speech_warning>")
Definition at line 117 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::warn_about().
snip_thirsty
translation dialogue_chatbin_snippets::snip_thirsty = no_translation("<thirsty>")
Definition at line 118 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_wait
translation dialogue_chatbin_snippets::snip_wait = no_translation("<wait>")
Definition at line 119 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_warn_sleep
translation dialogue_chatbin_snippets::snip_warn_sleep = no_translation("<warn_sleep>")
Definition at line 120 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_wear
translation dialogue_chatbin_snippets::snip_wear = to_translation("Thanks, I'll wear that now.")
Definition at line 163 of file dialogue_chatbin.h.
Referenced by npc_template::load(), and npc::wear_if_wanted().
snip_wound_bite
translation dialogue_chatbin_snippets::snip_wound_bite = to_translation("The bite wound on my %s looks bad.")
Definition at line 128 of file dialogue_chatbin.h.
Referenced by npc::complain(), and npc_template::load().
snip_wound_infected
translation dialogue_chatbin_snippets::snip_wound_infected = to_translation("My %s wound is infected…")
Definition at line 127 of file dialogue_chatbin.h.
Referenced by npc::complain(), and npc_template::load().
snip_yawn
translation dialogue_chatbin_snippets::snip_yawn = no_translation("<yawn>")
Definition at line 121 of file dialogue_chatbin.h.
Referenced by npc_template::load().
snip_yes_to_lsd
translation dialogue_chatbin_snippets::snip_yes_to_lsd = no_translation("<yes_to_lsd>")
Definition at line 122 of file dialogue_chatbin.h.
Referenced by npc_template::load().
The documentation for this struct was generated from the following file:
src/dialogue_chatbin.h