Cataclysm DDA: queued_eocs Struct Reference
queued_eocs Struct Reference
#include <character.h>
Classes
struct eoc_compare
Public Types
using storage_iter = std::list< queued_eoc >::iterator
Public Member Functions
queued_eocs ()=default
queued_eocs (const queued_eocs &rhs)
queued_eocs (queued_eocs &&rhs) noexcept
queued_eocs & operator= (const queued_eocs &rhs)
queued_eocs & operator= (queued_eocs &&rhs) noexcept
bool empty () const
const queued_eoc & top () const
void push (const queued_eoc &eoc)
void pop ()
Public Attributes
std::priority_queue< storage_iter, std::vector< storage_iter >, eoc_compare > queue
std::list< queued_eoc > list
Detailed Description
Definition at line 310 of file character.h.
Member Typedef Documentation
storage_iter
using queued_eocs::storage_iter = std::list<queued_eoc>::iterator
Definition at line 311 of file character.h.
Constructor & Destructor Documentation
queued_eocs() [1/3]
queued_eocs::queued_eocs () default
queued_eocs() [2/3]
queued_eocs::queued_eocs (const queued_eocs & rhs) inline
Definition at line 323 of file character.h.
{
         list = rhs.list;
         for( auto it = list.begin(), end = list.end(); it != end; ++it ) {
             queue.emplace( it );
         }
     };
References keycode::end, list, and queue.
queued_eocs() [3/3]
queued_eocs::queued_eocs (queued_eocs && rhs) inline noexcept
Definition at line 329 of file character.h.
{
         queue.swap( rhs.queue );
         list.swap( rhs.list );
     }
References list, and queue.
Member Function Documentation
empty()
bool queued_eocs::empty () const inline
Definition at line 351 of file character.h.
{
         return queue.empty();
     }
References queue.
Referenced by effect_on_conditions::clear(), process_eocs(), process_new_eocs(), game::serialize(), Character::store(), and effect_on_conditions::write_eocs_to_file().
operator=() [1/2]
queued_eocs& queued_eocs::operator= (const queued_eocs & rhs) inline
Definition at line 334 of file character.h.
{
         list = rhs.list;
         // Why doesn't std::priority_queue have a clear() function.
         queue = {};
         for( auto it = list.begin(), end = list.end(); it != end; ++it ) {
             queue.emplace( it );
         }
         return *this;
     }
References keycode::end, list, and queue.
operator=() [2/2]
queued_eocs& queued_eocs::operator= (queued_eocs && rhs) inline noexcept
Definition at line 343 of file character.h.
{
         queue.swap( rhs.queue );
         list.swap( rhs.list );
         return *this;
     }
References list, and queue.
pop()
void queued_eocs::pop () inline
Definition at line 364 of file character.h.
                {
         auto it = queue.top();
         queue.pop();
         list.erase( it );
     }
References list, and queue.
Referenced by effect_on_conditions::clear(), process_new_eocs(), game::serialize(), and Character::store().
push()
void queued_eocs::push (const queued_eoc & eoc) inline
Definition at line 359 of file character.h.
{
         auto it = list.emplace( list.end(), eoc );
         queue.push( it );
     }
References eoc, list, and queue.
Referenced by effect_on_conditions::load_new_character(), process_new_eocs(), process_reactivation(), effect_on_conditions::queue_effect_on_condition(), and game::unserialize().
top()
const queued_eoc& queued_eocs::top () const inline
Definition at line 355 of file character.h.
{
         return *queue.top();
     }
References queue.
Referenced by process_eocs(), process_new_eocs(), game::serialize(), and Character::store().
Member Data Documentation
list
std::list<queued_eoc> queued_eocs::list
Definition at line 319 of file character.h.
Referenced by Character::count_queued_effects(), operator=(), pop(), process_eocs(), push(), and queued_eocs().
queue
std::priority_queue<storage_iter, std::vector<storage_iter>, eoc_compare> queued_eocs::queue
Definition at line 318 of file character.h.
Referenced by empty(), operator=(), pop(), process_eocs(), push(), queued_eocs(), and top().
The documentation for this struct was generated from the following file:
src/character.h