Cataclysm DDA: avatar::daily_calories Struct Reference
avatar::daily_calories Struct Reference
#include <avatar.h>
Public Member Functions
int total () const noexcept
daily_calories ()
void serialize (JsonOut &json) const
void deserialize (const JsonObject &data)
void save_activity (JsonOut &json) const
void read_activity (const JsonObject &data)
Public Attributes
int spent = 0
int gained = 0
int ingested = 0
std::map< float, int > activity_levels
Detailed Description
Definition at line 334 of file avatar.h.
Constructor & Destructor Documentation
daily_calories()
avatar::daily_calories::daily_calories ()
Definition at line 1638 of file avatar.cpp.
 {
     activity_levels.emplace( NO_EXERCISE, 0 );
     activity_levels.emplace( LIGHT_EXERCISE, 0 );
     activity_levels.emplace( MODERATE_EXERCISE, 0 );
     activity_levels.emplace( BRISK_EXERCISE, 0 );
     activity_levels.emplace( ACTIVE_EXERCISE, 0 );
     activity_levels.emplace( EXTRA_EXERCISE, 0 );
 }
References ACTIVE_EXERCISE, activity_levels, BRISK_EXERCISE, EXTRA_EXERCISE, LIGHT_EXERCISE, MODERATE_EXERCISE, and NO_EXERCISE.
Member Function Documentation
deserialize()
void avatar::daily_calories::deserialize (const JsonObject & data)
Definition at line 1660 of file avatar.cpp.
 {
     data.read( "spent", spent );
     data.read( "gained", gained );
     data.read( "ingested", ingested );
     if( data.has_member( "activity" ) ) {
         read_activity( data );
     }
 }
References JsonObject::has_member(), and JsonObject::read().
read_activity()
void avatar::daily_calories::read_activity (const JsonObject & data)
Definition at line 1685 of file avatar.cpp.
 {
     if( data.has_array( "activity" ) ) {
         double act_level;
         for( JsonArray ja : data.get_array( "activity" ) ) {
             act_level = ja.next_float();
             activity_levels[ act_level ] = ja.next_int();
         }
         return;
     }
     // Fallback to legacy format for backward compatibility
     JsonObject jo = data.get_object( "activity" );
     for( const std::pair<const std::string, float> &member : activity_levels_map ) {
         int times;
         if( !jo.read( member.first, times ) ) {
             continue;
         }
         activity_levels.at( member.second ) = times;
     }
 }
References activity_levels_map, JsonObject::get_array(), JsonObject::get_object(), JsonObject::has_array(), member, and JsonObject::read().
save_activity()
void avatar::daily_calories::save_activity (JsonOut & json) const
Definition at line 1670 of file avatar.cpp.
 {
     json.member( "activity" );
     json.start_array();
     for( const std::pair<const float, int> &level : activity_levels ) {
         if( level.second > 0 ) {
             json.start_array();
             json.write( level.first );
             json.write( level.second );
             json.end_array();
         }
     }
     json.end_array();
 }
References JsonOut::end_array(), JsonOut::member(), JsonOut::start_array(), and JsonOut::write().
serialize()
void avatar::daily_calories::serialize (JsonOut & json) const
Definition at line 1648 of file avatar.cpp.
 {
     json.start_object();
     json.member( "spent", spent );
     json.member( "gained", gained );
     json.member( "ingested", ingested );
     save_activity( json );
     json.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
total()
int avatar::daily_calories::total () const inline noexcept
Definition at line 338 of file avatar.h.
{
                 return gained - spent;
             }
References gained, and spent.
Member Data Documentation
activity_levels
std::map<float, int> avatar::daily_calories::activity_levels
Definition at line 341 of file avatar.h.
Referenced by daily_calories().
gained
int avatar::daily_calories::gained = 0
Definition at line 336 of file avatar.h.
Referenced by total().
ingested
int avatar::daily_calories::ingested = 0
Definition at line 337 of file avatar.h.
spent
int avatar::daily_calories::spent = 0
Definition at line 335 of file avatar.h.
Referenced by total().
The documentation for this struct was generated from the following files:
src/avatar.h
src/avatar.cpp