Cataclysm DDA: weakpoint_effect Struct Reference
weakpoint_effect Struct Reference
#include <weakpoint.h>
Public Member Functions
weakpoint_effect ()
std::string get_message () const
void apply_to (Creature &target, int total_damage, const weakpoint_attack &attack) const
void load (const JsonObject &jo)
Public Attributes
efftype_id effect
float chance
bool permanent
std::pair< int, int > duration
std::pair< int, int > intensity
std::pair< float, float > damage_required
translation message
Detailed Description
Definition at line 58 of file weakpoint.h.
Constructor & Destructor Documentation
weakpoint_effect()
weakpoint_effect::weakpoint_effect ()
Definition at line 255 of file weakpoint.cpp.
                                     :
     chance( 100.0f ),
     permanent( false ),
     duration( 1, 1 ),
     intensity( 0, 0 ),
     damage_required( 0.0f, 100.0f ) {}
Member Function Documentation
apply_to()
void weakpoint_effect::apply_to (Creature & target, int total_damage, const weakpoint_attack & attack) const
Definition at line 267 of file weakpoint.cpp.
 {
     // Check if damage is within required bounds
     float percent_hp = 100.0f * static_cast<float>( total_damage ) / target.get_hp_max();
     percent_hp = std::min( 100.0f, percent_hp );
     if( percent_hp < damage_required.first || damage_required.second < percent_hp ) {
         return;
     }
     // Roll for chance.
     if( !( rng_float( 0.0f, 100.f ) < chance ) ) {
         return;
     }
     target.add_effect( effect_source( attack.source ), effect,
                        time_duration::from_turns( rng( duration.first, duration.second ) ),
                        permanent, rng( intensity.first, intensity.second ) );
     if( !get_message().empty() && attack.source != nullptr && attack.source->is_avatar() ) {
         add_msg_if_player_sees( target, m_good, get_message(), target.get_name() );
     }
 }
References Creature::add_effect(), add_msg_if_player_sees(), spell_effect::attack(), chance, damage_required, duration, time_duration::from_turns(), Creature::get_hp_max(), get_message(), Creature::get_name(), intensity, m_good, min(), permanent, rng(), and rng_float().
get_message()
std::string weakpoint_effect::get_message () const
Definition at line 262 of file weakpoint.cpp.
 {
     return message.translated();
 }
References message, and translation::translated().
Referenced by apply_to().
load()
void weakpoint_effect::load (const JsonObject & jo)
Definition at line 289 of file weakpoint.cpp.
 {
     assign( jo, "effect", effect );
     if( jo.has_float( "chance" ) ) {
         assign( jo, "chance", chance, false, 0.0f, 100.0f );
     }
     if( jo.has_bool( "permanent" ) ) {
         assign( jo, "permanent", permanent );
     }
     if( jo.has_string( "message" ) ) {
         assign( jo, "message", message );
     }
     // Support shorthand for a single value.
     if( jo.has_int( "duration" ) ) {
         int i = jo.get_int( "duration", 0 );
         duration = {i, i};
     } else if( jo.has_array( "duration" ) ) {
         assign( jo, "duration", duration );
     }
     if( jo.has_int( "intensity" ) ) {
         int i = jo.get_int( "intensity", 0 );
         intensity = {i, i};
     } else if( jo.has_array( "intensity" ) ) {
         assign( jo, "intensity", intensity );
     }
     if( jo.has_float( "damage_required" ) ) {
         float f = jo.get_float( "damage_required", 0.0f );
         damage_required = {f, f};
     } else if( jo.has_array( "damage_required" ) ) {
         assign( jo, "damage_required", damage_required );
     }
 }
References assign(), chance, damage_required, duration, JsonObject::get_float(), JsonObject::get_int(), JsonObject::has_array(), JsonObject::has_bool(), JsonObject::has_float(), JsonObject::has_int(), JsonObject::has_string(), intensity, message, and permanent.
Member Data Documentation
chance
float weakpoint_effect::chance
Definition at line 62 of file weakpoint.h.
Referenced by apply_to(), and load().
damage_required
std::pair<float, float> weakpoint_effect::damage_required
Definition at line 70 of file weakpoint.h.
Referenced by apply_to(), and load().
duration
std::pair<int, int> weakpoint_effect::duration
Definition at line 66 of file weakpoint.h.
Referenced by apply_to(), and load().
effect
efftype_id weakpoint_effect::effect
Definition at line 60 of file weakpoint.h.
intensity
std::pair<int, int> weakpoint_effect::intensity
Definition at line 68 of file weakpoint.h.
Referenced by apply_to(), and load().
message
translation weakpoint_effect::message
Definition at line 72 of file weakpoint.h.
Referenced by get_message(), and load().
permanent
bool weakpoint_effect::permanent
Definition at line 64 of file weakpoint.h.
Referenced by apply_to(), and load().
The documentation for this struct was generated from the following files:
src/weakpoint.h
src/weakpoint.cpp