Cataclysm DDA: label Struct Reference
label Struct Reference
Struct used for storing labels (easier to json opposed to a std::map<point, std::string>)
#include <vehicle.h>
Public Member Functions
label ()=default
label (const point &p)
label (const point &p, std::string text)
void deserialize (const JsonObject &data)
void serialize (JsonOut &json) const
Public Member Functions inherited from point
constexpr point ()=default
constexpr point (int X, int Y)
constexpr point operator+ (const point &rhs) const
point & operator+= (const point &rhs)
constexpr point operator- () const
constexpr point operator- (const point &rhs) const
point & operator-= (const point &rhs)
constexpr point operator* (const int rhs) const
point & operator*= (const int rhs)
constexpr point operator/ (const int rhs) const
point abs () const
point rotate (int turns, const point &dim={ 1, 1 }) const
Rotate point clockwise.
float distance (const point &rhs) const
int distance_manhattan (const point &rhs) const
std::string to_string () const
std::string to_string_writable () const
void serialize (JsonOut &jsout) const
void deserialize (const JsonArray &jsin)
Public Attributes
std::string text
Public Attributes inherited from point
int x = 0
int y = 0
Additional Inherited Members
Static Public Member Functions inherited from point
static point from_string (const std::string &)
Static Public Attributes inherited from point
static constexpr int dimension = 2
Detailed Description
Struct used for storing labels (easier to json opposed to a std::map<point, std::string>)
Definition at line 687 of file vehicle.h.
Constructor & Destructor Documentation
label() [1/3]
label::label () default
label() [2/3]
label::label (const point & p) inline explicit
Definition at line 689 of file vehicle.h.
 : point( p ) {}
label() [3/3]
label::label (const point & p, std::string text) inline
Definition at line 690 of file vehicle.h.
 : point( p ), text( std::move( text ) ) {}
Member Function Documentation
deserialize()
void label::deserialize (const JsonObject & data)
Definition at line 3327 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     data.read( "x", x );
     data.read( "y", y );
     data.read( "text", text );
 }
References item_pocket::data.
serialize()
void label::serialize (JsonOut & json) const
Definition at line 3335 of file savegame_json.cpp.
 {
     json.start_object();
     json.member( "x", x );
     json.member( "y", y );
     json.member( "text", text );
     json.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
Member Data Documentation
text
std::string label::text
Definition at line 692 of file vehicle.h.
The documentation for this struct was generated from the following files:
src/vehicle.h
src/savegame_json.cpp