Cataclysm DDA: tool_comp Struct Reference
tool_comp Struct Reference
#include <requirements.h>
Public Member Functions
tool_comp ()=default
tool_comp (const itype_id &TYPE, int COUNT)
void load (const JsonValue &value)
void dump (JsonOut &jsout) const
bool has (const read_only_visitable &crafting_inv, const std::function< bool(const item &)> &filter, int batch=1, craft_flags=craft_flags::none, const std::function< void(int)> &visitor=std::function< void(int)>()) const
std::string to_string (int batch=1, int avail=0) const
nc_color get_color (bool has_one, const read_only_visitable &crafting_inv, const std::function< bool(const item &)> &filter, int batch=1) const
bool by_charges () const
component_type get_component_type () const
Public Member Functions inherited from component
bool operator== (const component &rhs) const
bool operator!= (const component &rhs) const
bool operator< (const component &rhs) const
component ()=default
component (const itype_id &TYPE, int COUNT)
component (const itype_id &TYPE, int COUNT, bool RECOVERABLE)
void check_consistency (const std::string &display_name) const
Additional Inherited Members
Public Attributes inherited from component
itype_id type = itype_id::NULL_ID()
int count = 0
available_status available = available_status::a_false
bool recoverable = true
bool requirement = false
Detailed Description
Definition at line 91 of file requirements.h.
Constructor & Destructor Documentation
tool_comp() [1/2]
tool_comp::tool_comp () default
tool_comp() [2/2]
tool_comp::tool_comp (const itype_id & TYPE, int COUNT) inline
Definition at line 93 of file requirements.h.
 : component( TYPE, COUNT ) { }
Member Function Documentation
by_charges()
bool tool_comp::by_charges () const
Definition at line 149 of file requirements.cpp.
 {
     return count > 0;
 }
References component::count.
Referenced by requirement_data::check_enough_materials(), has(), and to_string().
dump()
void tool_comp::dump (JsonOut & jsout) const
Definition at line 253 of file requirements.cpp.
 {
     jsout.start_array();
     jsout.write( type );
     jsout.write( count );
     if( requirement ) {
         jsout.write( "LIST" );
     }
     jsout.end_array();
 }
References component::count, JsonOut::end_array(), component::requirement, JsonOut::start_array(), component::type, and JsonOut::write().
get_color()
nc_color tool_comp::get_color (bool has_one, const read_only_visitable & crafting_inv, const std::function< bool(const item &)> & filter, int batch = 1) const
Definition at line 956 of file requirements.cpp.
 {
     if( available == available_status::a_insufficient ) {
         return c_brown;
     } else if( has( crafting_inv, filter, batch ) ) {
         return c_green;
     }
     return has_one ? c_dark_gray : c_red;
 }
References a_insufficient, component::available, c_brown, c_dark_gray, c_green, c_red, filter, and has().
get_component_type()
component_type tool_comp::get_component_type () const inline
Definition at line 105 of file requirements.h.
{
         return component_type::TOOL;
     }
References TOOL.
has()
bool tool_comp::has (const read_only_visitable & crafting_inv, const std::function< bool(const item &)> & filter, int batch = 1, craft_flags flags = craft_flags::none, const std::function< void(int)> & visitor = std::function<void(int)>()) const
Definition at line 926 of file requirements.cpp.
 {
     if( get_player_character().has_trait( trait_DEBUG_HS ) ) {
         return true;
     }
     if( !by_charges() ) {
         return crafting_inv.has_tools( type, std::abs( count ), filter );
     } else {
         int charges_required = count * batch * item::find_type( type )->charge_factor();
         // The `type->tool` check excludes items counted by charge used as tools,
         // such as water purification tablets.
         if( ( flags & craft_flags::start_only ) != craft_flags::none && type->tool ) {
             // See Character::craft_consume_tools. In theory only
             // `charges_required / 20 + charges_required % 20` charges are
             // consumed during the first 5% progress, however that equation
             // sometimes decreases when the batch size increases, so we take
             // the largest remainder value 19 to make this function return
             // false consistently for large batch sizes.
             charges_required = std::min( charges_required, charges_required / 20 + 19 );
         }
         int charges_found = crafting_inv.charges_of( type, charges_required, filter, visitor );
         return charges_found == charges_required;
     }
 }
References abs(), by_charges(), itype::charge_factor(), read_only_visitable::charges_of(), component::count, filter, item::find_type(), get_player_character(), read_only_visitable::has_tools(), min(), none, start_only, itype::tool, trait_DEBUG_HS, and component::type.
Referenced by requirement_data::check_enough_materials(), and get_color().
load()
void tool_comp::load (const JsonValue & value)
Definition at line 235 of file requirements.cpp.
 {
     if( value.test_string() ) {
         // constructions uses this format: [ "tool", ... ]
         value.read( type, true );
         count = -1;
     } else {
         JsonArray comp = value.get_array();
         comp.read( 0, type, true );
         count = comp.get_int( 1 );
         requirement = comp.size() > 2 && comp.get_string( 2 ) == "LIST";
     }
     if( count == 0 ) {
         value.throw_error( "tool count must not be 0" );
     }
     // Note: negative count means charges (of the tool) should be consumed
 }
References component::count, JsonValue::get_array(), JsonArray::get_int(), JsonArray::get_string(), JsonValue::read(), JsonArray::read(), component::requirement, JsonArray::size(), JsonValue::test_string(), JsonValue::throw_error(), and component::type.
to_string()
std::string tool_comp::to_string (int batch = 1, int avail = 0) const
Definition at line 154 of file requirements.cpp.
 {
     if( by_charges() ) {
         int charge_total = count * batch;
         //~ %1$s: tool name, %2$d: charge requirement
         return string_format( npgettext( "requirement", "%1$s (%2$d charge)", "%1$s (%2$d charges)",
                                          charge_total ),
                               item::tname( type, 1, tname::item_name ), charge_total );
     } else {
         return item::tname( type, std::abs( count ), tname::item_name );
     }
 }
References abs(), by_charges(), component::count, tname::item_name(), npgettext, string_format(), item::tname(), and component::type.
The documentation for this struct was generated from the following files:
src/requirements.h
src/requirements.cpp