Cataclysm DDA: overmap_location Struct Reference
overmap_location Struct Reference
#include <overmap_location.h>
Public Types
using TerrColType = cata::flat_set< oter_type_str_id >
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
void check () const
void finalize ()
bool test (const int_id< oter_t > &oter) const
const TerrColType & get_all_terrains () const
oter_type_id get_random_terrain () const
Public Attributes
string_id< overmap_location > id
std::vector< std::pair< string_id< overmap_location >, mod_id > > src
bool was_loaded = false
Private Attributes
TerrColType terrains
std::vector< std::string > flags
Detailed Description
Definition at line 14 of file overmap_location.h.
Member Typedef Documentation
TerrColType
using overmap_location::TerrColType = cata::flat_set<oter_type_str_id>
Definition at line 16 of file overmap_location.h.
Member Function Documentation
check()
void overmap_location::check () const
Definition at line 57 of file overmap_location.cpp.
 {
     for( const auto &element : terrains ) {
         if( !element.is_valid() ) {
             debugmsg( "In overmap location \"%s\", terrain \"%s\" is invalid.", id.c_str(), element.c_str() );
         }
     }
 }
References debugmsg, and terrains.
finalize()
void overmap_location::finalize ()
Definition at line 66 of file overmap_location.cpp.
 {
     const std::unordered_map<std::string, oter_flags> &oter_flags_map =
         io::get_enum_lookup_map<oter_flags>();
     for( const std::string &elem : flags ) {
         auto it = oter_flags_map.find( elem );
         if( it == oter_flags_map.end() ) {
             continue;
         }
         oter_flags check_flag = it->second;
         for( const oter_t &ter_elem : overmap_terrains::get_all() ) {
             if( ter_elem.has_flag( check_flag ) ) {
                 terrains.insert( ter_elem.get_type_id() );
             }
         }
     }
 }
References flags, overmap_terrains::get_all(), cata::flat_set< T, Compare, Data >::insert(), and terrains.
get_all_terrains()
const cata::flat_set< oter_type_str_id > & overmap_location::get_all_terrains () const
Definition at line 52 of file overmap_location.cpp.
 {
     return terrains;
 }
References terrains.
get_random_terrain()
oter_type_id overmap_location::get_random_terrain () const
Definition at line 38 of file overmap_location.cpp.
 {
     return random_entry( terrains );
 }
References random_entry(), and terrains.
load()
void overmap_location::load (const JsonObject & jo, std::string_view src)
Definition at line 43 of file overmap_location.cpp.
 {
     optional( jo, was_loaded, "flags", flags );
     optional( jo, was_loaded, "terrains", terrains );
     if( flags.empty() && terrains.empty() ) {
         jo.throw_error( "At least one flag or terrain must be specified." );
     }
 }
References flags, optional(), terrains, JsonObject::throw_error(), and was_loaded.
test()
bool overmap_location::test (const int_id< oter_t > & oter) const
Definition at line 33 of file overmap_location.cpp.
 {
     return terrains.count( oter->get_type_id() );
 }
References cata::flat_set< T, Compare, Data >::count(), oter_t::get_type_id(), and terrains.
Member Data Documentation
flags
std::vector<std::string> overmap_location::flags private
Definition at line 34 of file overmap_location.h.
Referenced by finalize(), and load().
id
string_id<overmap_location> overmap_location::id
Definition at line 28 of file overmap_location.h.
src
std::vector<std::pair<string_id<overmap_location>, mod_id> > overmap_location::src
Definition at line 29 of file overmap_location.h.
terrains
TerrColType overmap_location::terrains private
Definition at line 33 of file overmap_location.h.
Referenced by check(), finalize(), get_all_terrains(), get_random_terrain(), load(), and test().
was_loaded
bool overmap_location::was_loaded = false
Definition at line 30 of file overmap_location.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/overmap_location.h
src/overmap_location.cpp