Cataclysm DDA: mutable_special_connection Struct Reference
mutable_special_connection Struct Reference
Public Member Functions
void deserialize (const JsonObject &jo)
void check (const std::string &context) const
Public Attributes
string_id< overmap_connection > connection
Detailed Description
Definition at line 1562 of file overmap.cpp.
Member Function Documentation
check()
void mutable_special_connection::check (const std::string & context) const inline
Definition at line 1569 of file overmap.cpp.
{
         if( !connection.is_valid() ) {
             debugmsg( "invalid connection id %s in %s", connection.str(), context );
         }
     }
References connection, context, debugmsg, string_id< T >::is_valid(), and string_id< T >::str().
deserialize()
void mutable_special_connection::deserialize (const JsonObject & jo) inline
Definition at line 1565 of file overmap.cpp.
{
         jo.read( "connection", connection );
     }
References connection, and JsonObject::read().
Member Data Documentation
connection
string_id<overmap_connection> mutable_special_connection::connection
Definition at line 1563 of file overmap.cpp.
Referenced by check(), deserialize(), and mutable_overmap_special_data::place().
The documentation for this struct was generated from the following file:
src/overmap.cpp