Cataclysm DDA: event_transformation_event_source Struct Reference
event_transformation_event_source Struct Reference
Public Member Functions
event_transformation_event_source (const string_id< event_transformation > &t)
event_multiset get (stats_tracker &stats) const override
std::string debug_description () const override
bool is_game_start () const override
void add_watcher (stats_tracker &stats, event_multiset_watcher *watcher) const override
cata::event::fields_type fields () const override
monotonically monotonicity () const override
std::unique_ptr< event_source > clone () const override
Public Member Functions inherited from event_source
virtual ~event_source ()=default
Public Attributes
string_id< event_transformation > transformation
Additional Inherited Members
Static Public Member Functions inherited from event_source
static std::unique_ptr< event_source > load (const JsonObject &jo)
Detailed Description
Definition at line 387 of file event_statistics.cpp.
Constructor & Destructor Documentation
event_transformation_event_source()
event_transformation_event_source::event_transformation_event_source (const string_id< event_transformation > & t) inline explicit
Definition at line 388 of file event_statistics.cpp.
                                                                                            :
         transformation( t ) {}
Member Function Documentation
add_watcher()
void event_transformation_event_source::add_watcher (stats_tracker & stats, event_multiset_watcher * watcher) const inline override virtual
Implements event_source.
Definition at line 405 of file event_statistics.cpp.
{
         stats.add_watcher( transformation, watcher );
     }
References transformation.
clone()
std::unique_ptr<event_source> event_transformation_event_source::clone () const inline override virtual
Implements event_source.
Definition at line 417 of file event_statistics.cpp.
{
         return std::make_unique<event_transformation_event_source>( *this );
     }
debug_description()
std::string event_transformation_event_source::debug_description () const inline override virtual
Implements event_source.
Definition at line 397 of file event_statistics.cpp.
{
         return "event_transformation " + transformation->id.str();
     }
References event_transformation::id, string_id< T >::str(), and transformation.
fields()
cata::event::fields_type event_transformation_event_source::fields () const inline override virtual
Implements event_source.
Definition at line 409 of file event_statistics.cpp.
{
         return transformation->fields();
     }
References event_transformation::fields(), and transformation.
get()
event_multiset event_transformation_event_source::get (stats_tracker & stats) const inline override virtual
Implements event_source.
Definition at line 393 of file event_statistics.cpp.
{
         return stats.get_events( transformation );
     }
References transformation.
is_game_start()
bool event_transformation_event_source::is_game_start () const inline override virtual
Implements event_source.
Definition at line 401 of file event_statistics.cpp.
{
         return false;
     }
monotonicity()
monotonically event_transformation_event_source::monotonicity () const inline override virtual
Implements event_source.
Definition at line 413 of file event_statistics.cpp.
{
         return transformation->monotonicity();
     }
References event_transformation::monotonicity(), and transformation.
Member Data Documentation
transformation
string_id<event_transformation> event_transformation_event_source::transformation
Definition at line 391 of file event_statistics.cpp.
Referenced by add_watcher(), debug_description(), fields(), get(), and monotonicity().
The documentation for this struct was generated from the following file:
src/event_statistics.cpp