Cataclysm DDA: Pickup::pick_info Struct Reference
Pickup::pick_info Struct Reference
Pick up information reminder for bulk loading.
#include <pickup.h>
Public Member Functions
pick_info ()=default
void serialize (JsonOut &jsout) const
void deserialize (const JsonObject &jsobj)
void set_src (const item_location &src_)
void set_dst (const item_location &dst_)
Public Attributes
units::volume total_bulk_volume = 0_ml
item_location::type src_type = item_location::type::invalid
tripoint src_pos
item_location src_container
item_location dst
Detailed Description
Pick up information reminder for bulk loading.
Definition at line 17 of file pickup.h.
Constructor & Destructor Documentation
pick_info()
Pickup::pick_info::pick_info () default
Member Function Documentation
deserialize()
void Pickup::pick_info::deserialize (const JsonObject & jsobj)
Definition at line 474 of file pickup.cpp.
 {
     int src_type_ = 0;
     jsobj.read( "total_bulk_volume", total_bulk_volume );
     jsobj.read( "src_type", src_type_ );
     src_type = static_cast<item_location::type>( src_type_ );
     jsobj.read( "src_pos", src_pos );
     jsobj.read( "src_container", src_container );
     jsobj.read( "dst", dst );
 }
References JsonObject::read().
serialize()
void Pickup::pick_info::serialize (JsonOut & jsout) const
Definition at line 463 of file pickup.cpp.
 {
     jsout.start_object();
     jsout.member( "total_bulk_volume", total_bulk_volume );
     jsout.member( "src_type", static_cast<int>( src_type ) );
     jsout.member( "src_pos", src_pos );
     jsout.member( "src_container", src_container );
     jsout.member( "dst", dst );
     jsout.end_object();
 }
References dst, JsonOut::end_object(), JsonOut::member(), src_container, src_pos, src_type, JsonOut::start_object(), and total_bulk_volume.
set_dst()
void Pickup::pick_info::set_dst (const item_location & dst_)
Definition at line 493 of file pickup.cpp.
 {
     dst = dst_;
 }
Referenced by pick_one_up().
set_src()
void Pickup::pick_info::set_src (const item_location & src_)
Definition at line 485 of file pickup.cpp.
 {
     // item_location of source may become invalid after the item is moved, so save the information separately.
     src_pos = src_.position();
     src_container = src_.parent_item();
     src_type = src_.where();
 }
References item_location::parent_item(), item_location::position(), and item_location::where().
Referenced by pick_one_up().
Member Data Documentation
dst
item_location Pickup::pick_info::dst
Definition at line 28 of file pickup.h.
Referenced by is_bulk_load(), and serialize().
src_container
item_location Pickup::pick_info::src_container
Definition at line 27 of file pickup.h.
Referenced by is_bulk_load(), and serialize().
src_pos
tripoint Pickup::pick_info::src_pos
Definition at line 26 of file pickup.h.
Referenced by is_bulk_load(), and serialize().
src_type
item_location::type Pickup::pick_info::src_type = item_location::type::invalid
Definition at line 25 of file pickup.h.
Referenced by is_bulk_load(), and serialize().
total_bulk_volume
units::volume Pickup::pick_info::total_bulk_volume = 0_ml
Definition at line 24 of file pickup.h.
Referenced by Pickup::do_pickup(), pick_one_up(), and serialize().
The documentation for this struct was generated from the following files:
src/pickup.h
src/pickup.cpp