Cataclysm DDA: effect_on_condition Struct Reference
effect_on_condition Struct Reference
#include <effect_on_condition.h>
Public Member Functions
bool activate (dialogue &d, bool require_callstack_check=true) const
bool check_deactivate (dialogue &d) const
bool test_condition (dialogue &d) const
void apply_true_effects (dialogue &d) const
void load (const JsonObject &jo, std::string_view src)
void finalize ()
void check () const
effect_on_condition ()=default
Public Attributes
bool was_loaded = false
bool run_for_npcs = false
bool global = false
effect_on_condition_id id
std::vector< std::pair< effect_on_condition_id, mod_id > > src
eoc_type type
std::function< bool(dialogue &)> condition
std::function< bool(dialogue &)> deactivate_condition
talk_effect_t true_effect
talk_effect_t false_effect
bool has_deactivate_condition = false
bool has_condition = false
bool has_false_effect = false
event_type required_event
duration_or_var recurrence
Friends
class generic_factory< effect_on_condition >
Detailed Description
Definition at line 53 of file effect_on_condition.h.
Constructor & Destructor Documentation
effect_on_condition()
effect_on_condition::effect_on_condition () default
Member Function Documentation
activate()
bool effect_on_condition::activate (dialogue & d, bool require_callstack_check = true) const
Definition at line 314 of file effect_on_condition.cpp.
 {
     bool retval = false;
     if( require_callstack_check ) {
         d.amend_callstack( "EOC: " + id.str() );
         if( d.get_callstack().size() > 5000 ) {
             if( query_yn( string_format( _( "Possible infinite loop in EOC %s.  Stop execution?" ),
                                          id.str() ) ) ) {
                 return false;
             }
         }
     }
     // each version needs a copy of the dialogue to pass down
     dialogue d_eoc( d );
     if( !has_condition || condition( d_eoc ) ) {
         true_effect.apply( d_eoc );
         retval = true;
     } else if( has_false_effect ) {
         false_effect.apply( d_eoc );
     }
     // This works because if global is true then this is recurring and thus should only ever be passed containing the player
     // Thus we just need to run the npcs.
     if( global && run_for_npcs ) {
         for( npc &guy : g->all_npcs() ) {
             dialogue d_npc( get_talker_for( guy ), nullptr, d.get_conditionals(), d.get_context() );
             if( !has_condition || condition( d_npc ) ) {
                 true_effect.apply( d_npc );
             } else if( has_false_effect ) {
                 false_effect.apply( d_npc );
             }
         }
     }
     return retval;
 }
References _, dialogue::amend_callstack(), talk_effect_t::apply(), condition, false_effect, g, dialogue::get_callstack(), dialogue::get_conditionals(), dialogue::get_context(), get_talker_for(), global, has_condition, has_false_effect, query_yn(), run_for_npcs, string_format(), and true_effect.
Referenced by debug_menu::change_weather(), player_activity::do_turn(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_weighted_list_eocs(), process_eocs(), and addiction::run_effect().
apply_true_effects()
void effect_on_condition::apply_true_effects (dialogue & d) const
Definition at line 362 of file effect_on_condition.cpp.
 {
     true_effect.apply( d );
 }
References talk_effect_t::apply(), and true_effect.
Referenced by overmap_special::place().
check()
void effect_on_condition::check () const
Definition at line 493 of file effect_on_condition.cpp.
 {
 }
check_deactivate()
bool effect_on_condition::check_deactivate (dialogue & d) const
Definition at line 349 of file effect_on_condition.cpp.
 {
     if( !has_deactivate_condition || has_false_effect ) {
         return false;
     }
     return deactivate_condition( d );
 }
References deactivate_condition, has_deactivate_condition, and has_false_effect.
Referenced by process_eocs().
finalize()
void effect_on_condition::finalize ()
Definition at line 481 of file effect_on_condition.cpp.
 {
 }
load()
void effect_on_condition::load (const JsonObject & jo, std::string_view src)
Definition at line 78 of file effect_on_condition.cpp.
 {
     mandatory( jo, was_loaded, "id", id );
     optional( jo, was_loaded, "eoc_type", type, eoc_type::NUM_EOC_TYPES );
     if( jo.has_member( "recurrence" ) ) {
         if( type != eoc_type::NUM_EOC_TYPES && type != eoc_type::RECURRING ) {
             jo.throw_error( "A recurring effect_on_condition must be of type RECURRING." );
         }
         type = eoc_type::RECURRING;
         recurrence = get_duration_or_var( jo, "recurrence", false );
     }
     if( type == eoc_type::NUM_EOC_TYPES ) {
         type = eoc_type::ACTIVATION;
     }
     if( jo.has_member( "deactivate_condition" ) ) {
         read_condition( jo, "deactivate_condition", deactivate_condition, false );
         has_deactivate_condition = true;
     }
     if( jo.has_member( "condition" ) ) {
         read_condition( jo, "condition", condition, false );
         has_condition = true;
     }
     true_effect.load_effect( jo, "effect" );
     if( jo.has_member( "false_effect" ) ) {
         false_effect.load_effect( jo, "false_effect" );
         has_false_effect = true;
     }
     optional( jo, was_loaded, "run_for_npcs", run_for_npcs, false );
     optional( jo, was_loaded, "global", global, false );
     if( !global && run_for_npcs ) {
         jo.throw_error( "run_for_npcs should only be true for global effect_on_conditions." );
     }
     if( type == eoc_type::EVENT ) {
         mandatory( jo, was_loaded, "required_event", required_event );
     }
 }
References ACTIVATION, condition, deactivate_condition, EVENT, false_effect, get_duration_or_var(), global, has_condition, has_deactivate_condition, has_false_effect, JsonObject::has_member(), talk_effect_t::load_effect(), mandatory, NUM_EOC_TYPES, optional(), read_condition(), recurrence, RECURRING, required_event, run_for_npcs, JsonObject::throw_error(), true_effect, type, and was_loaded.
Referenced by effect_on_conditions::load_inline_eoc().
test_condition()
bool effect_on_condition::test_condition (dialogue & d) const
Definition at line 357 of file effect_on_condition.cpp.
 {
     return !has_condition || condition( d );
 }
References condition, and has_condition.
Referenced by overmap::can_place_special(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector().
Friends And Related Function Documentation
generic_factory< effect_on_condition >
friend class generic_factory< effect_on_condition > friend
Definition at line 50 of file effect_on_condition.h.
Member Data Documentation
condition
std::function<bool(dialogue &)> effect_on_condition::condition
Definition at line 64 of file effect_on_condition.h.
Referenced by activate(), conditional_fun::anonymous_namespace{condition.cpp}::f_test_eoc(), load(), and test_condition().
deactivate_condition
std::function<bool(dialogue &)> effect_on_condition::deactivate_condition
Definition at line 65 of file effect_on_condition.h.
Referenced by check_deactivate(), and load().
false_effect
talk_effect_t effect_on_condition::false_effect
Definition at line 67 of file effect_on_condition.h.
Referenced by activate(), and load().
global
bool effect_on_condition::global = false
Definition at line 60 of file effect_on_condition.h.
Referenced by activate(), load(), and process_new_eocs().
has_condition
bool effect_on_condition::has_condition = false
Definition at line 69 of file effect_on_condition.h.
Referenced by activate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), load(), and test_condition().
has_deactivate_condition
bool effect_on_condition::has_deactivate_condition = false
Definition at line 68 of file effect_on_condition.h.
Referenced by check_deactivate(), and load().
has_false_effect
bool effect_on_condition::has_false_effect = false
Definition at line 70 of file effect_on_condition.h.
Referenced by activate(), check_deactivate(), and load().
id
effect_on_condition_id effect_on_condition::id
Definition at line 61 of file effect_on_condition.h.
Referenced by effect_on_conditions::load_inline_eoc().
recurrence
duration_or_var effect_on_condition::recurrence
Definition at line 72 of file effect_on_condition.h.
Referenced by load().
required_event
event_type effect_on_condition::required_event
Definition at line 71 of file effect_on_condition.h.
Referenced by load().
run_for_npcs
bool effect_on_condition::run_for_npcs = false
Definition at line 58 of file effect_on_condition.h.
Referenced by activate(), and load().
src
std::vector<std::pair<effect_on_condition_id, mod_id> > effect_on_condition::src
Definition at line 62 of file effect_on_condition.h.
true_effect
talk_effect_t effect_on_condition::true_effect
Definition at line 66 of file effect_on_condition.h.
Referenced by activate(), apply_true_effects(), and load().
type
eoc_type effect_on_condition::type
Definition at line 63 of file effect_on_condition.h.
Referenced by player_activity::do_turn(), load(), and process_eocs().
was_loaded
bool effect_on_condition::was_loaded = false
Definition at line 56 of file effect_on_condition.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/effect_on_condition.h
src/effect_on_condition.cpp