Cataclysm DDA: duration_or_var_part Struct Reference
duration_or_var_part Struct Reference
#include <dialogue_helpers.h>
Public Member Functions
time_duration evaluate (dialogue &d) const
Public Attributes
std::optional< time_duration > dur_val
std::optional< var_info > var_val
std::optional< time_duration > default_val
std::optional< eoc_math > math_val
Detailed Description
Definition at line 189 of file dialogue_helpers.h.
Member Function Documentation
evaluate()
time_duration duration_or_var_part::evaluate (dialogue & d) const
Definition at line 199 of file dialogue_helpers.cpp.
 {
     if( dur_val.has_value() ) {
         return dur_val.value();
     }
     if( var_val.has_value() ) {
         std::string val = read_var_value( var_val.value(), d );
         if( !val.empty() ) {
             time_duration ret_val;
             ret_val = time_duration::from_turns( std::stof( val ) );
             return ret_val;
         }
         if( default_val.has_value() ) {
             return default_val.value();
         }
         std::string var_name = var_val.value().name;
         if( var_name.find( "npctalk_var" ) != std::string::npos ) {
             var_name = var_name.substr( 12 );
         }
         debugmsg( "No default value provided for duration_or_var_part while encountering unused "
                   "variable %s.  Add a \"default\" member to prevent this.  %s",
                   var_name, d.get_callstack() );
         return 0_seconds;
     }
     if( math_val ) {
         return time_duration::from_turns( math_val->act( d ) );
     }
     debugmsg( "No valid value for duration_or_var_part.  %s", d.get_callstack() );
     return 0_seconds;
 }
References debugmsg, default_val, dur_val, time_duration::from_turns(), dialogue::get_callstack(), math_val, read_var_value(), and var_val.
Referenced by duration_or_var::evaluate().
Member Data Documentation
default_val
std::optional<time_duration> duration_or_var_part::default_val
Definition at line 192 of file dialogue_helpers.h.
Referenced by evaluate().
dur_val
std::optional<time_duration> duration_or_var_part::dur_val
Definition at line 190 of file dialogue_helpers.h.
Referenced by evaluate().
math_val
std::optional<eoc_math> duration_or_var_part::math_val
Definition at line 193 of file dialogue_helpers.h.
Referenced by evaluate().
var_val
std::optional<var_info> duration_or_var_part::var_val
Definition at line 191 of file dialogue_helpers.h.
Referenced by evaluate().
The documentation for this struct was generated from the following files:
src/dialogue_helpers.h
src/dialogue_helpers.cpp