Cataclysm DDA: mutation_branch Struct Reference
mutation_branch Struct Reference
#include <mutation.h>
Classes
struct OverrideLook
Public Member Functions
std::string spawn_item_message () const
std::string ranged_mutation_message () const
std::string name (const std::string &variant="") const
std::string desc (const std::string &variant="") const
nc_color get_display_color () const
Returns the color to display the mutation name with.
const mutation_variant * pick_variant () const
Picks a variant out of the possibilities based on their wieghts.
const mutation_variant * variant (const std::string &id) const
Returns a pointer to the mutation variant with corresponding id, or nullptr if none exists.
const mutation_variant * pick_variant_menu () const
Have the player pick a variant out of the options available.
bool conflicts_with_item (const item &it) const
Returns true if a character with this mutation shouldn't be able to wear given item.
bool conflicts_with_item_rigid (const item &it) const
Returns true if a character with this mutation has to take off rigid items at the location.
const resistances & damage_resistance (const bodypart_id &bp) const
Returns damage resistance on a given body part granted by this mutation.
int bionic_slot_bonus (const bodypart_str_id &part) const
Returns bionic slot bonus on a given body part granted by this mutation.
void load (const JsonObject &jo, const std::string &src)
void finalize ()
Static Public Member Functions
static const std::vector< mutation_branch > & get_all ()
All known mutations.
static void reset_all ()
static void load_trait (const JsonObject &jo, const std::string &src)
static void check_consistency ()
static void load_trait_blacklist (const JsonObject &jsobj)
Load a trait blacklist specified by the given JSON object.
static bool trait_is_blacklisted (const trait_id &tid)
Check if the trait with the given ID is blacklisted.
static void load_trait_migration (const JsonObject &jo)
Load a trait migration given by JSON object.
static const trait_replacement & trait_migration (const trait_id &tid)
Give the appropriate replacement migrated trait.
static void finalize_all ()
called after all JSON has been read and performs any necessary cleanup tasks
static void finalize_trait_blacklist ()
Trait groups
Trait groups are used to generate a randomized set of traits.
You usually only need the Trait_group::traits_from function to create traits from a group.
static void load_trait_group (const JsonObject &jsobj)
Callback for the init system (DynamicDataLoader), loads a trait group definitions.
static void load_trait_group (const JsonObject &jsobj, const trait_group::Trait_group_tag &gid, const std::string &subtype)
Load a trait group from json.
static void load_trait_group (const JsonArray &entries, const trait_group::Trait_group_tag &gid, bool is_collection)
Like the above function, except this function assumes that the given array is the "entries" member of the trait group.
static void add_entry (Trait_group &tg, const JsonObject &obj)
Create a new trait group as specified by the given JSON object and register it as part of the given trait group.
static shared_ptr_fast< Trait_group > get_group (const trait_group::Trait_group_tag &gid)
Get the trait group object specified by the given ID, or null if no such group exists.
static std::vector< trait_group::Trait_group_tag > get_all_group_names ()
Return the idents of all trait groups that are known.
Public Attributes
trait_id id
std::vector< std::pair< trait_id, mod_id > > src
bool was_loaded = false
bool valid = false
bool purifiable = false
bool threshold = false
std::vector< trait_id > threshold_substitutes
bool strict_threshreq = false
bool profession = false
bool debug = false
bool player_display = true
bool vanity = false
bool dummy = false
bool mixed_effect = false
bool startingtrait = false
bool activated = false
bool starts_active = false
bool destroys_gear = false
bool allow_soft_gear = false
bool sleepiness = false
bool hunger = false
bool thirst = false
int points = 0
int vitamin_cost = 100
int visibility = 0
int ugliness = 0
int cost = 0
time_duration cooldown = 0_turns
units::temperature_delta bodytemp_min = 0_C_delta
units::temperature_delta bodytemp_max = 0_C_delta
std::optional< int > scent_intensity
int butchering_quality = 0
cata::value_ptr< mut_transform > transform
cata::value_ptr< mut_personality_score > personality_score
std::map< std::string, mutation_variant > variants
std::vector< std::vector< reflex_activation_data > > trigger_list
std::map< skill_id, int > craft_skill_bonus
Map of crafting skills modifiers, can be negative.
std::optional< scenttype_id > scent_typeid
What do you smell like.
std::map< bodypart_str_id, float > lumination
Map of glowing body parts and their glow intensity.
social_modifiers social_mods
itype_id spawn_item
The item, if any, spawned by the mutation.
std::vector< species_id > ignored_by
Species ignoring character with the mutation.
std::map< species_id, int > anger_relations
Map of angered species and there intensity.
std::set< material_id > can_only_eat
List of material required for food to be be edible.
std::set< itype_id > can_only_heal_with
List of healing items allowed.
std::set< itype_id > can_heal_with
std::set< mutation_category_id > allowed_category
List of allowed mutation category.
std::set< bodypart_str_id > no_cbm_on_bp
List of body parts locked out of bionics.
std::map< spell_id, int > spells_learned
std::optional< bool > hide_on_activated = std::nullopt
std::optional< bool > hide_on_deactivated = std::nullopt
std::map< mtype_id, int > moncams
Monster cameras added by this mutation.
std::vector< effect_on_condition_id > activated_eocs
effect_on_conditions triggered when this mutation activates
bool activated_is_setup = false
std::vector< effect_on_condition_id > processed_eocs
effect_on_conditions triggered while this mutation is active
std::vector< effect_on_condition_id > deactivated_eocs
effect_on_conditions triggered when this mutation deactivates
std::vector< enchantment_id > enchantments
mutation enchantments
std::optional< OverrideLook > override_look
ID, tile category, and variant This will make the player appear as another entity (such as a non-humanoid creature).
itype_id ranged_mutation
The fake gun, if any, spawned and fired by the ranged mutation.
std::vector< mut_attack > attacks_granted
Attacks granted by this mutation.
std::map< vitamin_id, time_duration > vitamin_rates
Mutations may adjust one or more of the default vitamin usage rates.
std::map< material_id, std::map< vitamin_id, double > > vitamin_absorb_multi
std::vector< trait_id > prereqs
std::vector< trait_id > prereqs2
std::vector< trait_id > threshreq
std::set< std::string > types
std::vector< trait_id > cancels
std::vector< trait_id > replacements
std::vector< trait_id > additions
std::vector< mutation_category_id > category
std::set< json_character_flag > flags
std::set< json_character_flag > active_flags
std::set< json_character_flag > inactive_flags
std::map< bodypart_str_id, tripoint > protection
std::map< bodypart_str_id, int > encumbrance_always
std::map< bodypart_str_id, int > encumbrance_covered
std::map< bodypart_str_id, float > encumbrance_multiplier_always
std::set< bodypart_str_id > restricts_gear
std::set< sub_bodypart_str_id > restricts_gear_subparts
std::set< bodypart_str_id > remove_rigid
std::set< sub_bodypart_str_id > remove_rigid_subparts
std::set< flag_id > allowed_items
std::unordered_map< std::pair< bool, std::string >, int, cata::tuple_hash > mods
Key pair is <active: bool, mod type: "STR">
std::map< bodypart_str_id, resistances > armor
std::vector< itype_id > integrated_armor
std::vector< matype_id > initial_ma_styles
Private Attributes
translation raw_spawn_item_message
translation raw_ranged_mutation_message
std::map< bodypart_str_id, int > bionic_slot_bonuses
translation raw_name
translation raw_desc
Detailed Description
Definition at line 172 of file mutation.h.
Member Function Documentation
add_entry()
void mutation_branch::add_entry (Trait_group & tg, const JsonObject & obj) static
Create a new trait group as specified by the given JSON object and register it as part of the given trait group.
Definition at line 1079 of file mutation_data.cpp.
 {
     std::unique_ptr<Trait_creation_data> ptr;
     int probability = obj.get_int( "prob", 100 );
     JsonArray jarr;
     if( obj.has_member( "collection" ) ) {
         ptr = std::make_unique<Trait_group_collection>( probability );
         jarr = obj.get_array( "collection" );
     } else if( obj.has_member( "distribution" ) ) {
         ptr = std::make_unique<Trait_group_distribution>( probability );
         jarr = obj.get_array( "distribution" );
     }
     if( ptr ) {
         Trait_group &tg2 = dynamic_cast<Trait_group &>( *ptr );
         for( const JsonObject job2 : jarr ) {
             add_entry( tg2, job2 );
         }
         tg.add_entry( std::move( ptr ) );
         return;
     }
     if( obj.has_member( "trait" ) ) {
         trait_id id( obj.get_string( "trait" ) );
         std::string var;
         if( obj.has_member( "variant" ) ) {
             var = obj.get_string( "variant" );
         }
         ptr = std::make_unique<Single_trait_creator>( id, var, probability );
     } else if( obj.has_member( "group" ) ) {
         ptr = std::make_unique<Trait_group_creator>( trait_group::Trait_group_tag(
                     obj.get_string( "group" ) ),
                 probability );
     }
     if( !ptr ) {
         return;
     }
     tg.add_entry( std::move( ptr ) );
 }
References Trait_group::add_entry(), JsonObject::get_array(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::has_member(), id, and var.
Referenced by load_trait_group().
bionic_slot_bonus()
int mutation_branch::bionic_slot_bonus (const bodypart_str_id & part) const
Returns bionic slot bonus on a given body part granted by this mutation.
Definition at line 559 of file mutation_data.cpp.
 {
     const auto iter = bionic_slot_bonuses.find( part );
     if( iter == bionic_slot_bonuses.end() ) {
         return 0;
     } else {
         return iter->second;
     }
 }
References bionic_slot_bonuses.
check_consistency()
void mutation_branch::check_consistency () static
Definition at line 651 of file mutation_data.cpp.
 {
     for( const mutation_branch &mdata : get_all() ) {
         const trait_id &mid = mdata.id;
         const mod_id &trait_source = mdata.src.back().second;
         const bool basegame_trait = trait_source.str() == "dda";
         const std::optional<scenttype_id> &s_id = mdata.scent_typeid;
         const std::map<species_id, int> &an_id = mdata.anger_relations;
         for( const auto &style : mdata.initial_ma_styles ) {
             if( !style.is_valid() ) {
                 debugmsg( "mutation %s refers to undefined martial art style %s", mid.c_str(), style.c_str() );
             }
         }
         for( const std::string &type : mdata.types ) {
             if( !mutation_type_exists( type ) ) {
                 debugmsg( "mutation %s refers to undefined mutation type %s", mid.c_str(), type );
             }
         }
         if( mid->transform ) {
             const trait_id tid = mid->transform->target;
             if( !tid.is_valid() ) {
                 debugmsg( "mutation %s transform uses undefined target %s", mid.c_str(), tid.c_str() );
             }
         }
         for( const std::pair<species_id, int> elem : an_id ) {
             if( !elem.first.is_valid() ) {
                 debugmsg( "mutation %s refers to undefined species id %s", mid.c_str(), elem.first.c_str() );
             }
         }
         if( s_id && !s_id.value().is_valid() ) {
             debugmsg( "mutation %s refers to undefined scent type %s", mid.c_str(), s_id.value().c_str() );
         }
         // Suppress these onload warnings for overlapping mods
         for( const trait_id &replacement : mdata.replacements ) {
             const mutation_branch &rdata = replacement.obj();
             bool suppressed = rdata.src.back().second != trait_source && !basegame_trait;
             for( const mutation_category_id &cat : rdata.category ) {
                 if( std::find( mdata.category.begin(), mdata.category.end(), cat ) == mdata.category.end() &&
                     !suppressed ) {
                     debugmsg( "mutation %s lacks category %s present in replacement mutation %s", mid.c_str(),
                               cat.c_str(), replacement.c_str() );
                 }
             }
         }
         for( const trait_id &addition : mdata.additions ) {
             if( mdata.category.empty() ) {
                 break;
             }
             const mutation_branch &adata = addition.obj();
             bool found = false;
             bool suppressed = adata.src.back().second != trait_source && !basegame_trait;
             for( const mutation_category_id &cat : adata.category ) {
                 found = found ||
                         std::find( mdata.category.begin(), mdata.category.end(), cat ) != mdata.category.end();
             }
             if( !found && !suppressed ) {
                 debugmsg( "categories in mutation %s don't match any category present in additive mutation %s",
                           mid.c_str(), addition.c_str() );
             }
         }
         for( const mutation_category_id &cat_id : mdata.category ) {
             if( !mdata.prereqs.empty() ) {
                 bool found = false;
                 bool suppressed = false;
                 for( const trait_id &prereq_id : mdata.prereqs ) {
                     const mutation_branch &prereq = prereq_id.obj();
                     suppressed = suppressed || ( prereq.src.back().second != trait_source && !basegame_trait );
                     found = found ||
                             std::find( prereq.category.begin(), prereq.category.end(), cat_id ) != prereq.category.end();
                 }
                 if( !found && !suppressed ) {
                     debugmsg( "mutation %s is in category %s but none of its slot 1 prereqs have this category",
                               mid.c_str(), cat_id.c_str() );
                 }
             }
             if( !mdata.prereqs2.empty() ) {
                 bool found = false;
                 bool suppressed = false;
                 for( const trait_id &prereq_id : mdata.prereqs2 ) {
                     const mutation_branch &prereq = prereq_id.obj();
                     suppressed = suppressed || ( prereq.src.back().second != trait_source && !basegame_trait );
                     found = found ||
                             std::find( prereq.category.begin(), prereq.category.end(), cat_id ) != prereq.category.end();
                 }
                 if( !found && !suppressed ) {
                     debugmsg( "mutation %s is in category %s but none of its slot 2 prereqs have this category",
                               mid.c_str(), cat_id.c_str() );
                 }
             }
         }
         for( const std::pair<const bodypart_str_id, resistances> &ma : mdata.armor ) {
             for( const std::pair<const damage_type_id, float> &dt : ma.second.resist_vals ) {
                 if( !dt.first.is_valid() ) {
                     debugmsg( "Invalid armor type \"%s\" for mutation %s", dt.first.c_str(), mdata.id.c_str() );
                 }
             }
         }
         for( const mut_attack &atk : mdata.attacks_granted ) {
             for( const damage_unit &dt : atk.base_damage.damage_units ) {
                 if( !dt.type.is_valid() ) {
                     debugmsg( "Invalid base_damage type \"%s\" for a mutation attack in mutation %s", dt.type.c_str(),
                               mdata.id.c_str() );
                 }
             }
             for( const damage_unit &dt : atk.strength_damage.damage_units ) {
                 if( !dt.type.is_valid() ) {
                     debugmsg( "Invalid strength_damage type \"%s\" for a mutation attack in mutation %s",
                               dt.type.c_str(), mdata.id.c_str() );
                 }
             }
         }
         // We need to display active mutations in the UI.
         if( mdata.activated && !mdata.player_display ) {
             debugmsg( "mutation %s is not displayed but set as active" );
         }
         check_has_cyclic_dependency( mid );
         ::check_consistency( mdata.prereqs, mid, "prereqs" );
         ::check_consistency( mdata.prereqs2, mid, "prereqs2" );
         ::check_consistency( mdata.threshreq, mid, "threshreq" );
         ::check_consistency( mdata.cancels, mid, "cancels" );
         ::check_consistency( mdata.replacements, mid, "replacements" );
         ::check_consistency( mdata.additions, mid, "additions" );
     }
 }
References mut_attack::base_damage, string_id< T >::c_str(), category, check_has_cyclic_dependency(), damage_instance::damage_units, debugmsg, get_all(), string_id< T >::id(), string_id< T >::is_valid(), mutation_type_exists(), string_id< T >::obj(), replacement, src, string_id< T >::str(), mut_attack::strength_damage, transform, damage_unit::type, and type.
Referenced by DynamicDataLoader::check_consistency().
conflicts_with_item()
bool mutation_branch::conflicts_with_item (const item & it) const
Returns true if a character with this mutation shouldn't be able to wear given item.
Definition at line 417 of file mutation.cpp.
 {
     if( allow_soft_gear && it.is_soft() ) {
         return false;
     }
     for( const flag_id &allowed : allowed_items ) {
         if( it.has_flag( allowed ) ) {
             return false;
         }
     }
     for( const bodypart_str_id &bp : restricts_gear ) {
         if( it.covers( bp.id() ) && ( it.is_bp_rigid( bp.id() ) || !allow_soft_gear ) ) {
             return true;
         }
     }
     for( const sub_bodypart_str_id &bp : restricts_gear_subparts ) {
         if( it.covers( bp.id() ) && ( it.is_bp_rigid( bp.id() ) || !allow_soft_gear ) ) {
             return true;
         }
     }
     return false;
 }
References allow_soft_gear, allowed_items, bp, item::covers(), item::has_flag(), int_id< T >::id(), item::is_bp_rigid(), item::is_soft(), restricts_gear, and restricts_gear_subparts.
Referenced by iuse_transform::can_use(), Character::can_wear(), and Character::mutation_effect().
conflicts_with_item_rigid()
bool mutation_branch::conflicts_with_item_rigid (const item & it) const
Returns true if a character with this mutation has to take off rigid items at the location.
Definition at line 444 of file mutation.cpp.
 {
     for( const bodypart_str_id &bp : remove_rigid ) {
         if( it.covers( bp.id() ) && it.is_bp_rigid( bp.id() ) ) {
             return true;
         }
     }
     for( const sub_bodypart_str_id &bp : remove_rigid_subparts ) {
         if( it.covers( bp.id() ) && it.is_bp_rigid( bp.id() ) ) {
             return true;
         }
     }
     // check integrated armor against the character's worn armor directly in case it wasn't specified in JSON
     // this also seems to check the armor against itself, logic should be skipped by the integrated check
     for( const itype_id &integrated : integrated_armor ) {
         if( it.has_flag( json_flag_INTEGRATED ) ) {
             // skip other integrated armor, that should be handled with other rules
             continue;
         }
         item tmparmor = item( integrated );
         for( const sub_bodypart_id &sbp : tmparmor.get_covered_sub_body_parts() ) {
             if( tmparmor.is_bp_rigid( sbp ) && it.covers( sbp ) && it.is_bp_rigid( sbp ) ) {
                 return true;
             }
         }
     }
     return false;
 }
References bp, item::covers(), item::get_covered_sub_body_parts(), item::has_flag(), int_id< T >::id(), integrated_armor, item::is_bp_rigid(), item, json_flag_INTEGRATED, remove_rigid, and remove_rigid_subparts.
Referenced by Character::mutation_effect().
damage_resistance()
const resistances & mutation_branch::damage_resistance (const bodypart_id & bp) const
Returns damage resistance on a given body part granted by this mutation.
Definition at line 477 of file mutation.cpp.
 {
     const auto iter = armor.find( bp.id() );
     if( iter == armor.end() ) {
         static const resistances nulres;
         return nulres;
     }
     return iter->second;
 }
References armor, bp, and int_id< T >::id().
desc()
std::string mutation_branch::desc (const std::string & variant = "") const
Definition at line 589 of file mutation_data.cpp.
 {
     auto variter = variants.find( variant );
     if( variant.empty() || variter == variants.end() ) {
         return raw_desc.translated();
     }
     if( variter->second.append_desc ) {
         return string_format( "%s  %s", raw_desc.translated(),
                               variter->second.alt_description.translated() );
     }
     return variter->second.alt_description.translated();
 }
References raw_desc, string_format(), translation::translated(), variant(), and variants.
Referenced by computer_session::action_list_mutations(), Character::add_bionic(), iexamine::attunement_altar(), trait_and_var::desc(), known_magic::learn_spell(), Character::mutation_desc(), pick_variant_menu(), and wish_mutate_callback::refresh().
finalize()
void mutation_branch::finalize ()
Definition at line 945 of file mutation_data.cpp.
 {
     for( auto &armr : armor ) {
         finalize_damage_map( armr.second.resist_vals );
     }
 }
References armor, and finalize_damage_map().
finalize_all()
void mutation_branch::finalize_all () static
called after all JSON has been read and performs any necessary cleanup tasks
Definition at line 952 of file mutation_data.cpp.
 {
     trait_factory.finalize();
     for( const mutation_branch &branch : get_all() ) {
         for( const mutation_category_id &cat : branch.category ) {
             mutations_category[cat].emplace_back( branch.id );
         }
         // Don't include dummy mutations for the ANY category, since they have a very specific use case
         // Otherwise, the system will prioritize them
         if( !branch.dummy ) {
             mutations_category[mutation_category_ANY].emplace_back( branch.id );
         }
     }
     finalize_trait_blacklist();
 }
References finalize_trait_blacklist(), get_all(), mutation_category_ANY, mutations_category, and anonymous_namespace{mutation_data.cpp}::trait_factory.
Referenced by DynamicDataLoader::finalize_loaded_data().
finalize_trait_blacklist()
void mutation_branch::finalize_trait_blacklist () static
Definition at line 968 of file mutation_data.cpp.
 {
     for( const auto &trait : trait_blacklist ) {
         if( !trait.is_valid() ) {
             debugmsg( "trait on blacklist %s does not exist", trait.c_str() );
         }
     }
 }
References debugmsg, and trait_blacklist.
Referenced by finalize_all().
get_all()
const std::vector< mutation_branch > & mutation_branch::get_all () static
All known mutations.
Key is the mutation id, value is the mutation_branch that you would also get by calling get.
Definition at line 849 of file mutation_data.cpp.
 {
     return trait_factory.get_all();
 }
References anonymous_namespace{mutation_data.cpp}::trait_factory.
Referenced by iexamine::attunement_altar(), check_consistency(), do_purify(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach(), finalize_all(), npc::generate_personality_traits(), get_mutations_in_type(), Character::get_random_trait(), mutations_var_in_type(), iuse::purify_smart(), wish_mutate_callback::refresh(), Character::remove_mutation(), set_traits(), and debug_menu::wishmutate().
get_all_group_names()
std::vector< trait_group::Trait_group_tag > mutation_branch::get_all_group_names () static
Return the idents of all trait groups that are known.
Definition at line 1129 of file mutation_data.cpp.
 {
     std::vector<trait_group::Trait_group_tag> rval;
     for( auto &group : trait_groups ) {
         rval.push_back( group.first );
     }
     return rval;
 }
References trait_groups.
Referenced by trait_group::debug_spawn().
get_display_color()
nc_color mutation_branch::get_display_color () const
Returns the color to display the mutation name with.
Definition at line 783 of file mutation_data.cpp.
 {
     if( flags.count( STATIC( json_character_flag( "ATTUNEMENT" ) ) ) ) {
         return c_green;
     } else if( threshold || profession ) {
         return c_white;
     } else if( debug ) {
         return c_light_cyan;
     } else if( mixed_effect ) {
         return c_pink;
     } else if( points > 0 ) {
         return c_light_green;
     } else if( points < 0 ) {
         return c_light_red;
     } else {
         return c_yellow;
     }
 }
References c_green, c_light_cyan, c_light_green, c_light_red, c_pink, c_white, c_yellow, debug, flags, mixed_effect, points, STATIC, and threshold.
Referenced by draw_traits_info(), draw_traits_tab(), set_description(), and diary::trait_changes().
get_group()
shared_ptr_fast< Trait_group > mutation_branch::get_group (const trait_group::Trait_group_tag & gid) static
Get the trait group object specified by the given ID, or null if no such group exists.
Definition at line 1122 of file mutation_data.cpp.
 {
     auto found = trait_groups.find( gid );
     return found != trait_groups.end() ? found->second : nullptr;
 }
References trait_groups.
Referenced by Trait_group_creator::create(), trait_group::group_contains_trait(), Trait_group_creator::has_trait(), Trait_group_creator::remove_trait(), and trait_group::traits_from().
load()
void mutation_branch::load (const JsonObject & jo, const std::string & src)
Definition at line 302 of file mutation_data.cpp.
 {
     mandatory( jo, was_loaded, "name", raw_name );
     mandatory( jo, was_loaded, "description", raw_desc );
     mandatory( jo, was_loaded, "points", points );
     optional( jo, was_loaded, "vitamin_cost", vitamin_cost, 100 );
     optional( jo, was_loaded, "visibility", visibility, 0 );
     optional( jo, was_loaded, "ugliness", ugliness, 0 );
     optional( jo, was_loaded, "starting_trait", startingtrait, false );
     optional( jo, was_loaded, "mixed_effect", mixed_effect, false );
     optional( jo, was_loaded, "active", activated, false );
     optional( jo, was_loaded, "starts_active", starts_active, false );
     optional( jo, was_loaded, "destroys_gear", destroys_gear, false );
     optional( jo, was_loaded, "allow_soft_gear", allow_soft_gear, false );
     optional( jo, was_loaded, "cost", cost, 0 );
     optional( jo, was_loaded, "time", cooldown, 0_turns );
     optional( jo, was_loaded, "kcal", hunger, false );
     optional( jo, was_loaded, "thirst", thirst, false );
     optional( jo, was_loaded, "sleepiness", sleepiness, false );
     optional( jo, was_loaded, "valid", valid, true );
     optional( jo, was_loaded, "purifiable", purifiable, true );
     std::vector<mutation_variant> _variants;
     optional( jo, was_loaded, "variants", _variants );
     for( mutation_variant &var : _variants ) {
         var.parent = id;
         variants.emplace( var.id, var );
     }
     if( jo.has_object( "override_look" ) ) {
         JsonObject jv = jo.get_object( "override_look" );
         std::string override_look_id;
         std::string override_look_tile_category;
         mandatory( jv, was_loaded, "id", override_look_id );
         mandatory( jv, was_loaded, "tile_category", override_look_tile_category );
         override_look.emplace( override_look_id, override_look_tile_category );
     }
     if( jo.has_object( "spawn_item" ) ) {
         JsonObject si = jo.get_object( "spawn_item" );
         optional( si, was_loaded, "type", spawn_item );
         optional( si, was_loaded, "message", raw_spawn_item_message );
     }
     if( jo.has_object( "ranged_mutation" ) ) {
         JsonObject si = jo.get_object( "ranged_mutation" );
         optional( si, was_loaded, "type", ranged_mutation );
         optional( si, was_loaded, "message", raw_ranged_mutation_message );
     }
     if( jo.has_object( "transform" ) ) {
         transform = cata::make_value<mut_transform>();
         transform->load( jo, "transform" );
     }
     if( jo.has_object( "personality_score" ) ) {
         personality_score = cata::make_value<mut_personality_score>();
         personality_score->load( jo, "personality_score" );
     }
     optional( jo, was_loaded, "triggers", trigger_list );
     optional( jo, was_loaded, "initial_ma_styles", initial_ma_styles );
     if( jo.has_array( "bodytemp_modifiers" ) ) {
         JsonArray bodytemp_array = jo.get_array( "bodytemp_modifiers" );
         bodytemp_min = units::from_legacy_bodypart_temp_delta( bodytemp_array.get_int( 0 ) );
         bodytemp_max = units::from_legacy_bodypart_temp_delta( bodytemp_array.get_int( 1 ) );
     }
     optional( jo, was_loaded, "threshold", threshold, false );
     optional( jo, was_loaded, "threshold_substitutes", threshold_substitutes );
     optional( jo, was_loaded, "strict_threshreq", strict_threshreq );
     optional( jo, was_loaded, "profession", profession, false );
     optional( jo, was_loaded, "debug", debug, false );
     optional( jo, was_loaded, "player_display", player_display, true );
     optional( jo, was_loaded, "vanity", vanity, false );
     optional( jo, was_loaded, "dummy", dummy, false );
     for( JsonArray pair : jo.get_array( "vitamin_rates" ) ) {
         vitamin_rates.emplace( vitamin_id( pair.get_string( 0 ) ),
                                time_duration::from_turns( pair.get_int( 1 ) ) );
     }
     for( JsonArray pair : jo.get_array( "vitamins_absorb_multi" ) ) {
         std::map<vitamin_id, double> vit;
         // fill the inner map with vitamins
         for( JsonArray vitamins : pair.get_array( 1 ) ) {
             vit.emplace( vitamin_id( vitamins.get_string( 0 ) ), vitamins.get_float( 1 ) );
         }
         // assign the inner vitamin map to the material_id key
         vitamin_absorb_multi.emplace( material_id( pair.get_string( 0 ) ), vit );
     }
     optional( jo, was_loaded, "scent_intensity", scent_intensity, std::nullopt );
     optional( jo, was_loaded, "scent_type", scent_typeid, std::nullopt );
     optional( jo, was_loaded, "ignored_by", ignored_by );
     optional( jo, was_loaded, "can_only_eat", can_only_eat );
     optional( jo, was_loaded, "can_only_heal_with", can_only_heal_with );
     optional( jo, was_loaded, "can_heal_with", can_heal_with );
     optional( jo, was_loaded, "butchering_quality", butchering_quality, 0 );
     optional( jo, was_loaded, "allowed_category", allowed_category );
     if( jo.has_object( "social_modifiers" ) ) {
         JsonObject sm = jo.get_object( "social_modifiers" );
         social_mods = load_mutation_social_mods( sm );
     }
     optional( jo, was_loaded, "prereqs", prereqs, trait_reader{} );
     optional( jo, was_loaded, "prereqs2", prereqs2, trait_reader{} );
     optional( jo, was_loaded, "threshreq", threshreq, trait_reader{} );
     optional( jo, was_loaded, "cancels", cancels, trait_reader{} );
     optional( jo, was_loaded, "changes_to", replacements, trait_reader{} );
     optional( jo, was_loaded, "leads_to", additions, trait_reader{} );
     optional( jo, was_loaded, "flags", flags, flag_reader{} );
     optional( jo, was_loaded, "active_flags", active_flags, flag_reader{} );
     optional( jo, was_loaded, "inactive_flags", inactive_flags, flag_reader{} );
     optional( jo, was_loaded, "types", types, string_reader{} );
     for( JsonArray pair : jo.get_array( "moncams" ) ) {
         moncams.insert( std::pair<mtype_id, int>( mtype_id( pair.get_string( 0 ) ), pair.get_int( 1 ) ) );
     }
     for( JsonValue jv : jo.get_array( "activated_eocs" ) ) {
         activated_eocs.push_back( effect_on_conditions::load_inline_eoc( jv, src ) );
     }
     for( JsonValue jv : jo.get_array( "processed_eocs" ) ) {
         processed_eocs.push_back( effect_on_conditions::load_inline_eoc( jv, src ) );
     }
     for( JsonValue jv : jo.get_array( "deactivated_eocs" ) ) {
         deactivated_eocs.push_back( effect_on_conditions::load_inline_eoc( jv, src ) );
     }
     optional( jo, was_loaded, "activated_is_setup", activated_is_setup, false );
     int enchant_num = 0;
     for( JsonValue jv : jo.get_array( "enchantments" ) ) {
         std::string enchant_name = "INLINE_ENCH_" + id.str() + "_" + std::to_string( enchant_num++ );
         enchantments.push_back( enchantment::load_inline_enchantment( jv, src, enchant_name ) );
     }
     for( const std::string s : jo.get_array( "no_cbm_on_bp" ) ) {
         no_cbm_on_bp.emplace( s );
     }
     optional( jo, was_loaded, "category", category, string_id_reader<mutation_category_trait> {} );
     for( JsonArray ja : jo.get_array( "spells_learned" ) ) {
         const spell_id sp( ja.next_string() );
         spells_learned.emplace( sp, ja.next_int() );
     }
     for( JsonArray ja : jo.get_array( "craft_skill_bonus" ) ) {
         const skill_id skid( ja.next_string() );
         if( skid.is_valid() ) {
             craft_skill_bonus.emplace( skid, ja.next_int() );
         } else {
             jo.throw_error( "invalid skill_id" );
         }
     }
     for( JsonArray ja : jo.get_array( "lumination" ) ) {
         const bodypart_str_id bp = bodypart_str_id( ja.next_string() );
         lumination.emplace( bp, static_cast<float>( ja.next_float() ) );
     }
     for( JsonArray ja : jo.get_array( "anger_relations" ) ) {
         const species_id spe = species_id( ja.next_string() );
         anger_relations.emplace( spe, ja.next_int() );
     }
     for( JsonObject wp : jo.get_array( "wet_protection" ) ) {
         int ignored = wp.get_int( "ignored", 0 );
         int neutral = wp.get_int( "neutral", 0 );
         int good = wp.get_int( "good", 0 );
         tripoint protect = tripoint( ignored, neutral, good );
         protection[bodypart_str_id( wp.get_string( "part" ) )] = protect;
     }
     for( JsonArray ea : jo.get_array( "encumbrance_always" ) ) {
         const bodypart_str_id bp = bodypart_str_id( ea.next_string() );
         const int enc = ea.next_int();
         encumbrance_always[bp] = enc;
     }
     for( JsonArray ec : jo.get_array( "encumbrance_covered" ) ) {
         const bodypart_str_id bp = bodypart_str_id( ec.next_string() );
         int enc = ec.next_int();
         encumbrance_covered[bp] = enc;
     }
     for( JsonMember ema : jo.get_object( "encumbrance_multiplier_always" ) ) {
         const bodypart_str_id &bp = bodypart_str_id( ema.name() );
         encumbrance_multiplier_always[bp] = ema.get_float();
     }
     for( const std::string line : jo.get_array( "restricts_gear" ) ) {
         bodypart_str_id bp( line );
         if( bp.is_valid() ) {
             restricts_gear.insert( bp );
         } else {
             restricts_gear_subparts.insert( sub_bodypart_str_id( line ) );
         }
     }
     for( const std::string line : jo.get_array( "remove_rigid" ) ) {
         bodypart_str_id bp( line );
         if( bp.is_valid() ) {
             remove_rigid.insert( bp );
         } else {
             remove_rigid_subparts.insert( sub_bodypart_str_id( line ) );
         }
     }
     for( const std::string line : jo.get_array( "allowed_items" ) ) {
         allowed_items.insert( flag_id( line ) );
     }
     for( JsonObject ao : jo.get_array( "armor" ) ) {
         std::set<std::string> ignored_by_resist = { "part_types", "parts" };
         const resistances res = load_resistances_instance( ao, ignored_by_resist );
         // Set damage resistances for all body parts of the specified type(s)
         for( const std::string &type_string : ao.get_tags( "part_types" ) ) {
             for( const body_part_type &bp : body_part_type::get_all() ) {
                 if( type_string == "ALL" ) {
                     armor[bp.id] += res;
                 } else if( bp.limbtypes.count( io::string_to_enum<body_part_type::type>( type_string ) ) > 0 ) {
                     armor[bp.id] += res * bp.limbtypes.at( io::string_to_enum<body_part_type::type>( type_string ) );
                 }
             }
         }
         // Set damage resistances for specific body parts
         for( const std::string &part_string : ao.get_tags( "parts" ) ) {
             armor[bodypart_str_id( part_string )] += res;
         }
     }
     for( const JsonValue jv : jo.get_array( "integrated_armor" ) ) {
         integrated_armor.emplace_back( jv );
     }
     for( JsonMember member : jo.get_object( "bionic_slot_bonuses" ) ) {
         bionic_slot_bonuses[bodypart_str_id( member.name() )] = member.get_int();
     }
     if( jo.has_array( "attacks" ) ) {
         for( JsonObject ao : jo.get_array( "attacks" ) ) {
             attacks_granted.emplace_back( load_mutation_attack( ao ) );
         }
     } else if( jo.has_object( "attacks" ) ) {
         JsonObject attack = jo.get_object( "attacks" );
         attacks_granted.emplace_back( load_mutation_attack( attack ) );
     }
 }
References activated, activated_eocs, activated_is_setup, active_flags, additions, allow_soft_gear, allowed_category, allowed_items, anger_relations, armor, spell_effect::attack(), attacks_granted, bionic_slot_bonuses, bodytemp_max, bodytemp_min, bp, butchering_quality, can_heal_with, can_only_eat, can_only_heal_with, cancels, category, cooldown, cost, craft_skill_bonus, deactivated_eocs, debug, destroys_gear, dummy, enchantments, encumbrance_always, encumbrance_covered, encumbrance_multiplier_always, flag_id, flags, units::from_legacy_bodypart_temp_delta(), time_duration::from_turns(), body_part_type::get_all(), JsonArray::get_array(), JsonObject::get_array(), JsonArray::get_int(), JsonObject::get_object(), good, JsonObject::has_array(), JsonObject::has_object(), hunger, int_id< T >::id(), id, ignored_by, inactive_flags, initial_ma_styles, integrated_armor, int_id< T >::is_valid(), string_id< T >::is_valid(), line, enchantment::load_inline_enchantment(), effect_on_conditions::load_inline_eoc(), load_mutation_attack(), load_mutation_social_mods(), load_resistances_instance(), lumination, mandatory, member, mixed_effect, moncams, mtype_id, neutral, no_cbm_on_bp, optional(), override_look, personality_score, player_display, points, prereqs, prereqs2, processed_eocs, protection, purifiable, ranged_mutation, raw_desc, raw_name, raw_ranged_mutation_message, raw_spawn_item_message, remove_rigid, remove_rigid_subparts, replacements, restricts_gear, restricts_gear_subparts, scent_intensity, scent_typeid, sleepiness, coords::sm, social_mods, spawn_item, species_id, spells_learned, src, startingtrait, starts_active, strict_threshreq, thirst, threshold, threshold_substitutes, threshreq, JsonObject::throw_error(), to_string(), transform, trigger_list, tripoint, types, ugliness, valid, vanity, variants, visibility, vitamin_absorb_multi, vitamin_cost, vitamin_rates, and was_loaded.
load_trait()
void mutation_branch::load_trait (const JsonObject & jo, const std::string & src) static
Definition at line 194 of file mutation_data.cpp.
 {
     trait_factory.load( jo, src );
 }
References src, and anonymous_namespace{mutation_data.cpp}::trait_factory.
Referenced by DynamicDataLoader::initialize().
load_trait_blacklist()
void mutation_branch::load_trait_blacklist (const JsonObject & jsobj) static
Load a trait blacklist specified by the given JSON object.
Definition at line 899 of file mutation_data.cpp.
 {
     for( const std::string line : jsobj.get_array( "traits" ) ) {
         trait_blacklist.insert( trait_id( line ) );
     }
 }
References JsonObject::get_array(), line, trait_blacklist, and trait_id.
Referenced by DynamicDataLoader::initialize().
load_trait_group() [1/3]
void mutation_branch::load_trait_group (const JsonArray & entries, const trait_group::Trait_group_tag & gid, bool is_collection) static
Like the above function, except this function assumes that the given array is the "entries" member of the trait group.
For each element in the array, mutation_branch::add_entry is called.
Assuming the input array looks like [ x, y, z ], this function loads it like the above would load this object:
{
     "subtype": "depends on is_collection parameter",
     "id": "identifier",
     "entries": [ x, y, z ]
}
Note that each entry in the array has to be a JSON object. The other function above can also load data from arrays of strings, where the strings are item or group ids.
Definition at line 1006 of file mutation_data.cpp.
 {
     Trait_group &tg = make_group_or_throw( gid, is_collection );
     for( const JsonValue entry : entries ) {
         // Backwards-compatibility with old format ["TRAIT", 100]
         if( entry.test_array() ) {
             JsonArray subarr = entry.get_array();
             trait_id id( subarr.get_string( 0 ) );
             tg.add_entry( std::make_unique<Single_trait_creator>( id, "", subarr.get_int( 1 ) ) );
             // Otherwise load new format {"trait": ... } or {"group": ...}
         } else {
             JsonObject subobj = entry.get_object();
             add_entry( tg, subobj );
         }
     }
 }
References Trait_group::add_entry(), add_entry(), JsonArray::get_array(), JsonArray::get_int(), JsonObject::get_object(), JsonArray::get_string(), id, and make_group_or_throw().
load_trait_group() [2/3]
void mutation_branch::load_trait_group (const JsonObject & jsobj) static
Callback for the init system (DynamicDataLoader), loads a trait group definitions.
Parameters
jsobj The json object to load from.
Exceptions
JsonError if the json object contains invalid data.
Definition at line 977 of file mutation_data.cpp.
 {
     const trait_group::Trait_group_tag group_id( jsobj.get_string( "id" ) );
     const std::string subtype = jsobj.get_string( "subtype", "old" );
     load_trait_group( jsobj, group_id, subtype );
 }
References JsonObject::get_string(), and subtype.
Referenced by DynamicDataLoader::initialize(), and trait_group::load_trait_group().
load_trait_group() [3/3]
void mutation_branch::load_trait_group (const JsonObject & jsobj, const trait_group::Trait_group_tag & gid, const std::string & subtype) static
Load a trait group from json.
It differs from the other load_trait_group function as it uses the group ID and subtype given as parameters, and does not look them up in the json data (i.e. the given json object does not need to have them).
This is intended for inline definitions of trait groups, e.g. in NPC class definitions: the trait group there is embedded into the class type definition.
Parameters
jsobj The json object to load from.
gid The ID of the group that is to be loaded.
subtype The type of the trait group, either "collection", "distribution" or "old" (i.e. the old list-based format, [ ["TRAIT", 100] ]).
Exceptions
JsonError if the json object contains invalid data.
Definition at line 1026 of file mutation_data.cpp.
 {
     if( subtype != "distribution" && subtype != "collection" && subtype != "old" ) {
         jsobj.throw_error_at( "subtype", "unknown trait group type" );
     }
     Trait_group &tg = make_group_or_throw( gid, subtype == "collection" || subtype == "old" );
     // TODO: (sm) Looks like this makes the new code backwards-compatible with the old format. Great if so!
     if( subtype == "old" ) {
         for( JsonArray pair : jsobj.get_array( "traits" ) ) {
             tg.add_trait_entry( trait_id( pair.get_string( 0 ) ), "", pair.get_int( 1 ) );
         }
         return;
     }
     // TODO: (sm) Taken from item_factory.cpp almost verbatim. Ensure that these work!
     if( jsobj.has_member( "entries" ) ) {
         for( JsonObject subobj : jsobj.get_array( "entries" ) ) {
             add_entry( tg, subobj );
         }
     }
     if( jsobj.has_member( "traits" ) ) {
         for( const JsonValue entry : jsobj.get_array( "traits" ) ) {
             if( entry.test_string() ) {
                 tg.add_trait_entry( trait_id( entry.get_string() ), "", 100 );
             } else if( entry.test_array() ) {
                 JsonArray subtrait = entry.get_array();
                 tg.add_trait_entry( trait_id( subtrait.get_string( 0 ) ), "", subtrait.get_int( 1 ) );
             } else {
                 JsonObject subobj = entry.get_object();
                 add_entry( tg, subobj );
             }
         }
     }
     if( jsobj.has_member( "groups" ) ) {
         for( const JsonValue entry : jsobj.get_array( "groups" ) ) {
             if( entry.test_string() ) {
                 tg.add_group_entry( trait_group::Trait_group_tag( entry.get_string() ), 100 );
             } else if( entry.test_array() ) {
                 JsonArray subtrait = entry.get_array();
                 tg.add_group_entry( trait_group::Trait_group_tag( subtrait.get_string( 0 ) ),
                                     subtrait.get_int( 1 ) );
             } else {
                 JsonObject subobj = entry.get_object();
                 add_entry( tg, subobj );
             }
         }
     }
 }
References add_entry(), Trait_group::add_group_entry(), Trait_group::add_trait_entry(), JsonArray::get_array(), JsonObject::get_array(), JsonArray::get_int(), JsonObject::get_object(), JsonArray::get_string(), JsonObject::has_member(), make_group_or_throw(), subtype, JsonObject::throw_error_at(), and trait_id.
load_trait_migration()
void mutation_branch::load_trait_migration (const JsonObject & jo) static
Load a trait migration given by JSON object.
Definition at line 911 of file mutation_data.cpp.
 {
     // First, load the target
     trait_id target;
     jo.read( "id", target );
     // Then, populate the replacement
     trait_replacement replacement;
     if( jo.has_string( "proficiency" ) ) {
         jo.read( "proficiency", replacement.prof );
     } else if( jo.has_string( "trait" ) ) {
         trait_and_var dat;
         jo.read( "trait", dat.trait );
         jo.read( "variant", dat.variant, "" );
         replacement.trait = dat;
     } else if( !jo.has_bool( "remove" ) || !jo.get_bool( "remove" ) ) {
         jo.throw_error( "Specified migration for trait " + target.str() +
                         ", but did not specify how to migrate!" );
     }
     trait_migrations.emplace( target, replacement );
 }
References JsonObject::get_bool(), JsonObject::has_bool(), JsonObject::has_string(), JsonObject::read(), replacement, string_id< T >::str(), JsonObject::throw_error(), trait_and_var::trait, trait_migrations, and trait_and_var::variant.
Referenced by DynamicDataLoader::initialize().
name()
std::string mutation_branch::name (const std::string & variant = "") const
Definition at line 579 of file mutation_data.cpp.
 {
     auto variter = variants.find( variant );
     if( variant.empty() || variter == variants.end() ) {
         return raw_name.translated();
     }
     return variter->second.alt_name.translated();
 }
References raw_name, translation::translated(), variant(), and variants.
Referenced by iexamine::attunement_altar(), Character::customize_appearance(), draw_spellbook_info(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder(), learn_spell_actor::info(), known_magic::learn_spell(), Character::mutate_towards(), Character::mutation_name(), trait_and_var::name(), pick_variant_menu(), wish_mutate_callback::refresh(), Character::remove_mutation(), and spellcasting_callback::spell_info_text().
pick_variant()
const mutation_variant * mutation_branch::pick_variant () const
Picks a variant out of the possibilities based on their wieghts.
If all have zero weights, returns nullptr
Definition at line 802 of file mutation_data.cpp.
 {
     weighted_int_list<const mutation_variant *> options;
     for( const std::pair<const std::string, mutation_variant> &cur : variants ) {
         options.add( &cur.second, cur.second.weight );
     }
     const mutation_variant **picked = options.pick();
     if( picked == nullptr ) {
         return nullptr;
     }
     return *picked;
 }
References PATH_INFO::options(), and variants.
Referenced by Character::mutate_towards(), Character::remove_mutation(), and Character::set_mutation_unsafe().
pick_variant_menu()
const mutation_variant * mutation_branch::pick_variant_menu () const
Have the player pick a variant out of the options available.
Return a pointer to the variant Returns nullptr and does not open a menu if there are no variants.
Definition at line 827 of file mutation_data.cpp.
 {
     if( variants.empty() ) {
         return nullptr;
     }
     uilist menu;
     menu.allow_cancel = false;
     menu.desc_enabled = true;
     menu.text = string_format( _( "Pick variant for: %s" ), name() );
     std::vector<const mutation_variant *> options;
     options.reserve( variants.size() );
     for( const std::pair<const std::string, mutation_variant> &var : variants ) {
         options.emplace_back( &var.second );
     }
     for( size_t i = 0; i < options.size(); ++i ) {
         menu.addentry_desc( i, true, MENU_AUTOASSIGN, name( options[i]->id ), desc( options[i]->id ) );
     }
     menu.query();
     return options[menu.ret];
 }
References _, uilist::addentry_desc(), uilist::allow_cancel, desc(), uilist::desc_enabled, MENU_AUTOASSIGN, name(), PATH_INFO::options(), uilist::query(), uilist::ret, string_format(), uilist::text, and variants.
Referenced by Character::customize_appearance().
ranged_mutation_message()
std::string mutation_branch::ranged_mutation_message () const
Definition at line 574 of file mutation_data.cpp.
 {
     return raw_ranged_mutation_message.translated();
 }
References raw_ranged_mutation_message, and translation::translated().
Referenced by Character::activate_mutation().
reset_all()
void mutation_branch::reset_all () static
Definition at line 854 of file mutation_data.cpp.
 {
     mutations_category.clear();
     trait_factory.reset();
     trait_blacklist.clear();
     trait_groups.clear();
     trait_groups.emplace( Trait_group_EMPTY_GROUP,
                           make_shared_fast<Trait_group_collection>( 100 ) );
 }
References mutations_category, trait_blacklist, anonymous_namespace{mutation_data.cpp}::trait_factory, Trait_group_EMPTY_GROUP, and trait_groups.
Referenced by DynamicDataLoader::unload_data().
spawn_item_message()
std::string mutation_branch::spawn_item_message () const
Definition at line 569 of file mutation_data.cpp.
 {
     return raw_spawn_item_message.translated();
 }
References raw_spawn_item_message, and translation::translated().
Referenced by Character::activate_mutation().
trait_is_blacklisted()
bool mutation_branch::trait_is_blacklisted (const trait_id & tid) static
Check if the trait with the given ID is blacklisted.
Definition at line 906 of file mutation_data.cpp.
 {
     return trait_blacklist.count( tid );
 }
References trait_blacklist.
Referenced by Character::mutation_ok(), and set_traits().
trait_migration()
const trait_replacement & mutation_branch::trait_migration (const trait_id & tid) static
Give the appropriate replacement migrated trait.
Definition at line 935 of file mutation_data.cpp.
 {
     auto it = trait_migrations.find( tid );
     if( it != trait_migrations.end() ) {
         return it->second;
     }
     return trait_migration_remove;
 }
References trait_migration_remove, and trait_migrations.
Referenced by Character::load().
variant()
const mutation_variant * mutation_branch::variant (const std::string & id) const
Returns a pointer to the mutation variant with corresponding id, or nullptr if none exists.
Definition at line 817 of file mutation_data.cpp.
 {
     auto iter = variants.find( id );
     if( id.empty() || iter == variants.end() ) {
         return nullptr;
     }
     return &iter->second;
 }
References variants.
Referenced by desc(), Character::trait_data::deserialize(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_trait(), generic_barber(), Character::load(), name(), npc::randomize(), set_traits(), Character::toggle_trait(), and Character::toggle_trait_deps().
Member Data Documentation
activated
bool mutation_branch::activated = false
Definition at line 199 of file mutation.h.
Referenced by Character::count_trait_flag(), Character::has_trait_flag(), load(), and avatar::power_mutations().
activated_eocs
std::vector<effect_on_condition_id> mutation_branch::activated_eocs
effect_on_conditions triggered when this mutation activates
Definition at line 279 of file mutation.h.
Referenced by Character::activate_mutation(), and load().
activated_is_setup
bool mutation_branch::activated_is_setup = false
Definition at line 281 of file mutation.h.
Referenced by Character::activate_mutation(), and load().
active_flags
std::set<json_character_flag> mutation_branch::active_flags
Definition at line 329 of file mutation.h.
Referenced by Character::count_trait_flag(), Character::has_trait_flag(), and load().
additions
std::vector<trait_id> mutation_branch::additions
Definition at line 326 of file mutation.h.
Referenced by Character::calc_mutation_levels(), Character::get_addition_traits(), load(), Character::mutate(), and wish_mutate_callback::refresh().
allow_soft_gear
bool mutation_branch::allow_soft_gear = false
Definition at line 205 of file mutation.h.
Referenced by conflicts_with_item(), and load().
allowed_category
std::set<mutation_category_id> mutation_branch::allowed_category
List of allowed mutation category.
Definition at line 265 of file mutation.h.
Referenced by load().
allowed_items
std::set<flag_id> mutation_branch::allowed_items
Definition at line 344 of file mutation.h.
Referenced by conflicts_with_item(), and load().
anger_relations
std::map<species_id, int> mutation_branch::anger_relations
Map of angered species and there intensity.
Definition at line 255 of file mutation.h.
Referenced by monster::attitude(), and load().
armor
std::map<bodypart_str_id, resistances> mutation_branch::armor
Definition at line 348 of file mutation.h.
Referenced by damage_resistance(), finalize(), and load().
attacks_granted
std::vector<mut_attack> mutation_branch::attacks_granted
Attacks granted by this mutation.
Definition at line 312 of file mutation.h.
Referenced by load(), and Character::mutation_attacks().
bionic_slot_bonuses
std::map<bodypart_str_id, int> mutation_branch::bionic_slot_bonuses private
Definition at line 353 of file mutation.h.
Referenced by bionic_slot_bonus(), and load().
bodytemp_max
units::temperature_delta mutation_branch::bodytemp_max = 0_C_delta
Definition at line 221 of file mutation.h.
Referenced by load().
bodytemp_min
units::temperature_delta mutation_branch::bodytemp_min = 0_C_delta
Definition at line 220 of file mutation.h.
Referenced by load().
butchering_quality
int mutation_branch::butchering_quality = 0
Definition at line 225 of file mutation.h.
Referenced by load().
can_heal_with
std::set<itype_id> mutation_branch::can_heal_with
Definition at line 262 of file mutation.h.
Referenced by load().
can_only_eat
std::set<material_id> mutation_branch::can_only_eat
List of material required for food to be be edible.
Definition at line 258 of file mutation.h.
Referenced by load().
can_only_heal_with
std::set<itype_id> mutation_branch::can_only_heal_with
List of healing items allowed.
Definition at line 261 of file mutation.h.
Referenced by load().
cancels
std::vector<trait_id> mutation_branch::cancels
Definition at line 324 of file mutation.h.
Referenced by computer_session::action_list_mutations(), are_opposite_traits(), Character::get_opposite_traits(), known_magic::learn_spell(), load(), Character::mutate_towards(), wish_mutate_callback::refresh(), and Character::test_crossing_threshold().
category
std::vector<mutation_category_id> mutation_branch::category
Definition at line 327 of file mutation.h.
Referenced by Character::calc_mutation_levels(), check_consistency(), Character::get_threshold_category(), load(), Character::mutate(), wish_mutate_callback::refresh(), and Character::toggle_trait_deps().
cooldown
time_duration mutation_branch::cooldown = 0_turns
Definition at line 218 of file mutation.h.
Referenced by Character::activate_mutation(), load(), suffer::mutation_power(), and avatar::power_mutations().
cost
int mutation_branch::cost = 0
Definition at line 216 of file mutation.h.
Referenced by Character::activate_mutation(), load(), suffer::mutation_power(), avatar::power_mutations(), and sleep().
craft_skill_bonus
std::map<skill_id, int> mutation_branch::craft_skill_bonus
Map of crafting skills modifiers, can be negative.
Definition at line 237 of file mutation.h.
Referenced by load().
deactivated_eocs
std::vector<effect_on_condition_id> mutation_branch::deactivated_eocs
effect_on_conditions triggered when this mutation deactivates
Definition at line 285 of file mutation.h.
Referenced by Character::deactivate_mutation(), and load().
debug
bool mutation_branch::debug = false
Definition at line 189 of file mutation.h.
Referenced by get_display_color(), and load().
destroys_gear
bool mutation_branch::destroys_gear = false
Definition at line 203 of file mutation.h.
Referenced by load().
dummy
bool mutation_branch::dummy = false
Definition at line 195 of file mutation.h.
Referenced by load(), Character::mutate(), and Character::mutate_towards().
enchantments
std::vector<enchantment_id> mutation_branch::enchantments
mutation enchantments
Definition at line 287 of file mutation.h.
Referenced by Character::activate_mutation(), Character::deactivate_mutation(), load(), and Character::mutation_loss_effect().
encumbrance_always
std::map<bodypart_str_id, int> mutation_branch::encumbrance_always
Definition at line 332 of file mutation.h.
Referenced by load().
encumbrance_covered
std::map<bodypart_str_id, int> mutation_branch::encumbrance_covered
Definition at line 334 of file mutation.h.
Referenced by load().
encumbrance_multiplier_always
std::map<bodypart_str_id, float> mutation_branch::encumbrance_multiplier_always
Definition at line 336 of file mutation.h.
Referenced by load().
flags
std::set<json_character_flag> mutation_branch::flags
Definition at line 328 of file mutation.h.
Referenced by Character::calc_mutation_levels(), Character::count_trait_flag(), get_display_color(), Character::has_trait_flag(), and load().
hide_on_activated
std::optional<bool> mutation_branch::hide_on_activated = std::nullopt
Definition at line 273 of file mutation.h.
hide_on_deactivated
std::optional<bool> mutation_branch::hide_on_deactivated = std::nullopt
Definition at line 275 of file mutation.h.
hunger
bool mutation_branch::hunger = false
Definition at line 208 of file mutation.h.
Referenced by Character::activate_mutation(), Character::can_power_mutation(), load(), suffer::mutation_power(), and avatar::power_mutations().
id
trait_id mutation_branch::id
Definition at line 173 of file mutation.h.
Referenced by add_entry(), has_cyclic_dependency(), load(), load_trait_group(), Character::mutate(), Character::mutate_towards(), avatar::power_mutations(), wish_mutate_callback::refresh(), and talker_npc::view_personality_traits().
ignored_by
std::vector<species_id> mutation_branch::ignored_by
Species ignoring character with the mutation.
Definition at line 252 of file mutation.h.
Referenced by monster::attitude(), and load().
inactive_flags
std::set<json_character_flag> mutation_branch::inactive_flags
Definition at line 330 of file mutation.h.
Referenced by Character::count_trait_flag(), Character::has_trait_flag(), and load().
initial_ma_styles
std::vector<matype_id> mutation_branch::initial_ma_styles
Definition at line 351 of file mutation.h.
Referenced by load().
integrated_armor
std::vector<itype_id> mutation_branch::integrated_armor
Definition at line 349 of file mutation.h.
Referenced by conflicts_with_item_rigid(), load(), Character::mutation_effect(), and Character::mutation_loss_effect().
lumination
std::map<bodypart_str_id, float> mutation_branch::lumination
Map of glowing body parts and their glow intensity.
Definition at line 243 of file mutation.h.
Referenced by load().
mixed_effect
bool mutation_branch::mixed_effect = false
Definition at line 197 of file mutation.h.
Referenced by get_display_color(), load(), Character::mutate_towards(), and Character::remove_mutation().
mods
std::unordered_map<std::pair<bool, std::string>, int, cata::tuple_hash> mutation_branch::mods
Key pair is <active: bool, mod type: "STR">
Definition at line 347 of file mutation.h.
Referenced by Character::get_mod().
moncams
std::map<mtype_id, int> mutation_branch::moncams
Monster cameras added by this mutation.
Definition at line 277 of file mutation.h.
Referenced by load(), and Character::mutation_loss_effect().
no_cbm_on_bp
std::set<bodypart_str_id> mutation_branch::no_cbm_on_bp
List of body parts locked out of bionics.
Definition at line 268 of file mutation.h.
Referenced by load().
override_look
std::optional<OverrideLook> mutation_branch::override_look
ID, tile category, and variant This will make the player appear as another entity (such as a non-humanoid creature).
The texture will override all other textures, including the character's body.
Definition at line 298 of file mutation.h.
Referenced by load().
personality_score
cata::value_ptr<mut_personality_score> mutation_branch::personality_score
Definition at line 229 of file mutation.h.
Referenced by load(), and talker_npc::view_personality_traits().
player_display
bool mutation_branch::player_display = true
Definition at line 191 of file mutation.h.
Referenced by Character::get_mutations(), load(), Character::mutate_towards(), and Character::remove_mutation().
points
int mutation_branch::points = 0
Definition at line 211 of file mutation.h.
Referenced by get_display_color(), get_total_nonbad_in_category(), load(), Character::mutate_towards(), Character::mutation_ok(), Character::random_bad_trait(), Character::random_good_trait(), avatar::randomize(), Character::randomize_cosmetic_trait(), wish_mutate_callback::refresh(), Character::remove_mutation(), set_traits(), and trait_points_used().
prereqs
std::vector<trait_id> mutation_branch::prereqs
Definition at line 320 of file mutation.h.
Referenced by iexamine::attunement_altar(), b_is_lower_trait_of_a(), Character::get_lower_traits(), has_attunement_spell_prereqs(), has_cyclic_dependency(), load(), Character::mutate_towards(), Character::mutation_height(), Character::mutation_selector(), wish_mutate_callback::refresh(), and Character::remove_mutation().
prereqs2
std::vector<trait_id> mutation_branch::prereqs2
Definition at line 321 of file mutation.h.
Referenced by Character::get_lower_traits(), has_cyclic_dependency(), load(), Character::mutate_towards(), Character::mutation_height(), Character::mutation_selector(), wish_mutate_callback::refresh(), and Character::remove_mutation().
processed_eocs
std::vector<effect_on_condition_id> mutation_branch::processed_eocs
effect_on_conditions triggered while this mutation is active
Definition at line 283 of file mutation.h.
Referenced by load(), and suffer::mutation_power().
profession
bool mutation_branch::profession = false
Definition at line 187 of file mutation.h.
Referenced by Character::mutate_towards(), avatar::randomize(), and debug_menu::wishmutate().
protection
std::map<bodypart_str_id, tripoint> mutation_branch::protection
Definition at line 331 of file mutation.h.
Referenced by Character::drench_mut_calc(), and load().
purifiable
bool mutation_branch::purifiable = false
Definition at line 179 of file mutation.h.
Referenced by load(), and Character::purifiable().
ranged_mutation
itype_id mutation_branch::ranged_mutation
The fake gun, if any, spawned and fired by the ranged mutation.
Definition at line 305 of file mutation.h.
Referenced by Character::activate_mutation(), and load().
raw_desc
translation mutation_branch::raw_desc private
Definition at line 355 of file mutation.h.
Referenced by desc(), and load().
raw_name
translation mutation_branch::raw_name private
Definition at line 354 of file mutation.h.
Referenced by load(), and name().
raw_ranged_mutation_message
translation mutation_branch::raw_ranged_mutation_message private
Definition at line 307 of file mutation.h.
Referenced by load(), and ranged_mutation_message().
raw_spawn_item_message
translation mutation_branch::raw_spawn_item_message private
Definition at line 300 of file mutation.h.
Referenced by load(), and spawn_item_message().
remove_rigid
std::set<bodypart_str_id> mutation_branch::remove_rigid
Definition at line 341 of file mutation.h.
Referenced by conflicts_with_item_rigid(), and load().
remove_rigid_subparts
std::set<sub_bodypart_str_id> mutation_branch::remove_rigid_subparts
Definition at line 342 of file mutation.h.
Referenced by conflicts_with_item_rigid(), and load().
replacements
std::vector<trait_id> mutation_branch::replacements
Definition at line 325 of file mutation.h.
Referenced by computer_session::action_list_mutations(), b_is_higher_trait_of_a(), Character::get_replacement_traits(), Character::has_child_flag(), load(), Character::mutate(), Character::mutate_towards(), wish_mutate_callback::refresh(), Character::remove_child_flag(), and Character::remove_mutation().
restricts_gear
std::set<bodypart_str_id> mutation_branch::restricts_gear
Definition at line 338 of file mutation.h.
Referenced by conflicts_with_item(), and load().
restricts_gear_subparts
std::set<sub_bodypart_str_id> mutation_branch::restricts_gear_subparts
Definition at line 339 of file mutation.h.
Referenced by conflicts_with_item(), and load().
scent_intensity
std::optional<int> mutation_branch::scent_intensity
Definition at line 223 of file mutation.h.
Referenced by load().
scent_typeid
std::optional<scenttype_id> mutation_branch::scent_typeid
What do you smell like.
Definition at line 240 of file mutation.h.
Referenced by load(), and Character::update_type_of_scent().
sleepiness
bool mutation_branch::sleepiness = false
Definition at line 207 of file mutation.h.
Referenced by Character::activate_mutation(), Character::can_power_mutation(), load(), suffer::mutation_power(), and avatar::power_mutations().
social_mods
social_modifiers mutation_branch::social_mods
Definition at line 246 of file mutation.h.
Referenced by load().
spawn_item
itype_id mutation_branch::spawn_item
The item, if any, spawned by the mutation.
Definition at line 249 of file mutation.h.
Referenced by Character::activate_mutation(), and load().
spells_learned
std::map<spell_id, int> mutation_branch::spells_learned
Definition at line 271 of file mutation.h.
Referenced by load(), and known_magic::on_mutation_gain().
src
std::vector<std::pair<trait_id, mod_id> > mutation_branch::src
Definition at line 174 of file mutation.h.
Referenced by check_consistency(), load(), and load_trait().
startingtrait
bool mutation_branch::startingtrait = false
Definition at line 198 of file mutation.h.
Referenced by load(), Character::toggle_trait_deps(), and scenario::traitquery().
starts_active
bool mutation_branch::starts_active = false
Definition at line 201 of file mutation.h.
Referenced by Character::initialize(), and load().
strict_threshreq
bool mutation_branch::strict_threshreq = false
Definition at line 185 of file mutation.h.
Referenced by load(), and Character::mutate_towards().
thirst
bool mutation_branch::thirst = false
Definition at line 209 of file mutation.h.
Referenced by Character::activate_mutation(), Character::can_power_mutation(), load(), suffer::mutation_power(), and avatar::power_mutations().
threshold
bool mutation_branch::threshold = false
Definition at line 181 of file mutation.h.
Referenced by Character::calc_mutation_levels(), Character::crossed_threshold(), get_display_color(), Character::get_threshold_category(), get_total_nonbad_in_category(), Character::give_all_mutations(), load(), Character::mutate_towards(), and debug_menu::wishmutate().
threshold_substitutes
std::vector<trait_id> mutation_branch::threshold_substitutes
Definition at line 183 of file mutation.h.
Referenced by load().
threshreq
std::vector<trait_id> mutation_branch::threshreq
Definition at line 322 of file mutation.h.
Referenced by load(), Character::mutate_towards(), Character::mutation_selector(), and wish_mutate_callback::refresh().
transform
cata::value_ptr<mut_transform> mutation_branch::transform
Definition at line 227 of file mutation.h.
Referenced by Character::activate_mutation(), check_consistency(), Character::deactivate_mutation(), and load().
trigger_list
std::vector<std::vector<reflex_activation_data> > mutation_branch::trigger_list
Definition at line 234 of file mutation.h.
Referenced by load(), and Character::mutation_reflex_trigger().
types
std::set<std::string> mutation_branch::types
Definition at line 323 of file mutation.h.
Referenced by are_same_type_traits(), Character::get_same_type_traits(), load(), Character::mutate_towards(), Character::randomize_cosmetic_trait(), and wish_mutate_callback::refresh().
ugliness
int mutation_branch::ugliness = 0
Definition at line 215 of file mutation.h.
Referenced by load(), and wish_mutate_callback::refresh().
valid
bool mutation_branch::valid = false
Definition at line 177 of file mutation.h.
Referenced by load(), Character::mutate(), and wish_mutate_callback::refresh().
vanity
bool mutation_branch::vanity = false
Definition at line 193 of file mutation.h.
Referenced by load(), Character::set_mutation_unsafe(), and Character::unset_mutation().
variants
std::map<std::string, mutation_variant> mutation_branch::variants
Definition at line 232 of file mutation.h.
Referenced by add_trait(), Character::customize_appearance(), desc(), load(), name(), pick_variant(), pick_variant_menu(), set_traits(), and variant().
visibility
int mutation_branch::visibility = 0
Definition at line 214 of file mutation.h.
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_has_visible_trait(), load(), and wish_mutate_callback::refresh().
vitamin_absorb_multi
std::map<material_id, std::map<vitamin_id, double> > mutation_branch::vitamin_absorb_multi
Definition at line 318 of file mutation.h.
Referenced by compute_default_effective_vitamins(), and load().
vitamin_cost
int mutation_branch::vitamin_cost = 100
Definition at line 213 of file mutation.h.
Referenced by load(), Character::mutate_towards(), and Character::test_crossing_threshold().
vitamin_rates
std::map<vitamin_id, time_duration> mutation_branch::vitamin_rates
Mutations may adjust one or more of the default vitamin usage rates.
Definition at line 315 of file mutation.h.
Referenced by load(), and Character::vitamin_rate().
was_loaded
bool mutation_branch::was_loaded = false
Definition at line 175 of file mutation.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/mutation.h
src/mutation.cpp
src/mutation_data.cpp