Cataclysm DDA: islot_brewable Struct Reference
islot_brewable Struct Reference
#include <itype.h>
Public Member Functions
void load (const JsonObject &jo)
void deserialize (const JsonObject &jo)
Public Attributes
std::map< itype_id, int > results
What are the results of fermenting this item?
time_duration time = 0_turns
How long for this brew to ferment.
bool was_loaded = false
Detailed Description
Definition at line 211 of file itype.h.
Member Function Documentation
deserialize()
void islot_brewable::deserialize (const JsonObject & jo)
Definition at line 3428 of file item_factory.cpp.
 {
     load( jo );
 }
References load().
load()
void islot_brewable::load (const JsonObject & jo)
Definition at line 3416 of file item_factory.cpp.
 {
     optional( jo, was_loaded, "time", time, 1_turns );
     if( jo.has_array( "results" ) ) {
         for( std::string entry : jo.get_string_array( "results" ) ) {
             results[itype_id( entry )] = 1;
         }
     } else {
         mandatory( jo, was_loaded, "results", results );
     }
 }
References JsonObject::get_string_array(), JsonObject::has_array(), itype_id, mandatory, optional(), results, time, and was_loaded.
Referenced by deserialize().
Member Data Documentation
results
std::map<itype_id, int> islot_brewable::results
What are the results of fermenting this item?
Definition at line 213 of file itype.h.
Referenced by load().
time
time_duration islot_brewable::time = 0_turns
How long for this brew to ferment.
Definition at line 216 of file itype.h.
Referenced by load().
was_loaded
bool islot_brewable::was_loaded = false
Definition at line 218 of file itype.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/itype.h
src/item_factory.cpp