Cataclysm DDA: weakpoint_difficulty Struct Reference
weakpoint_difficulty Struct Reference
#include <weakpoint.h>
Public Member Functions
weakpoint_difficulty (float default_value)
float of (const weakpoint_attack &attack) const
void load (const JsonObject &jo)
Public Attributes
std::array< float, static_cast< int > weakpoint_attack::attack_type::NUM)> difficulty
Detailed Description
Definition at line 82 of file weakpoint.h.
Constructor & Destructor Documentation
weakpoint_difficulty()
weakpoint_difficulty::weakpoint_difficulty (float default_value) explicit
Definition at line 213 of file weakpoint.cpp.
 {
     difficulty.fill( default_value );
 }
References difficulty.
Member Function Documentation
load()
void weakpoint_difficulty::load (const JsonObject & jo)
Definition at line 223 of file weakpoint.cpp.
 {
     using attack_type = weakpoint_attack::attack_type;
     float default_value = difficulty[static_cast<int>( attack_type::NONE )];
     float all = jo.get_float( "all", default_value );
     // Determine default values
     float bash;
     float cut;
     float stab;
     float ranged = all;
     // Support either "melee" shorthand or "broad"/"point" shorthand.
     if( jo.has_float( "melee" ) ) {
         float melee = jo.get_float( "melee", all );
         bash = melee;
         cut = melee;
         stab = melee;
     } else {
         float broad = jo.get_float( "broad", all );
         float point = jo.get_float( "point", all );
         bash = broad;
         cut = broad;
         stab = point;
         ranged = point;
     }
     // Load the values
     difficulty[static_cast<int>( attack_type::NONE )] = all;
     difficulty[static_cast<int>( attack_type::MELEE_BASH )] = jo.get_float( "bash", bash );
     difficulty[static_cast<int>( attack_type::MELEE_CUT )] = jo.get_float( "cut", cut );
     difficulty[static_cast<int>( attack_type::MELEE_STAB )] = jo.get_float( "stab", stab );
     difficulty[static_cast<int>( attack_type::PROJECTILE )] = jo.get_float( "ranged", ranged );
 }
References om_direction::all, spell_effect::bash(), difficulty, JsonObject::get_float(), JsonObject::has_float(), and point.
Referenced by weakpoint::load().
of()
float weakpoint_difficulty::of (const weakpoint_attack & attack) const
Definition at line 218 of file weakpoint.cpp.
 {
     return difficulty[static_cast<int>( attack.type )];
 }
References spell_effect::attack(), and difficulty.
Referenced by weakpoint::hit_chance().
Member Data Documentation
difficulty
std::array<float, static_cast<int> weakpoint_attack::attack_type::NUM)> weakpoint_difficulty::difficulty
Definition at line 83 of file weakpoint.h.
Referenced by load(), of(), and weakpoint_difficulty().
The documentation for this struct was generated from the following files:
src/weakpoint.h
src/weakpoint.cpp