Cataclysm DDA: shopkeeper_blacklist Struct Reference
shopkeeper_blacklist Struct Reference
#include <shop_cons_rate.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
icg_entry const * matches (item const &it, npc const &beta) const
Static Public Member Functions
static void reset ()
static const std::vector< shopkeeper_blacklist > & get_all ()
static void load_blacklist (const JsonObject &jo, std::string const &src)
Public Attributes
shopkeeper_blacklist_id id
bool was_loaded = false
std::vector< icg_entry > entries
Detailed Description
Definition at line 65 of file shop_cons_rate.h.
Member Function Documentation
get_all()
std::vector< shopkeeper_blacklist > const & shopkeeper_blacklist::get_all () static
Definition at line 54 of file shop_cons_rate.cpp.
 {
     return shop_blacklist_factory.get_all();
 }
References anonymous_namespace{shop_cons_rate.cpp}::shop_blacklist_factory.
load()
void shopkeeper_blacklist::load (const JsonObject & jo, std::string_view src)
Definition at line 133 of file shop_cons_rate.cpp.
 {
     optional( jo, was_loaded, "entries", entries, icg_entry_reader {} );
 }
References entries, optional(), and was_loaded.
load_blacklist()
void shopkeeper_blacklist::load_blacklist (const JsonObject & jo, std::string const & src) static
Definition at line 88 of file shop_cons_rate.cpp.
 {
     shop_blacklist_factory.load( jo, src );
 }
References anonymous_namespace{shop_cons_rate.cpp}::shop_blacklist_factory.
Referenced by DynamicDataLoader::initialize().
matches()
icg_entry const * shopkeeper_blacklist::matches (item const & it, npc const & beta) const
Definition at line 172 of file shop_cons_rate.cpp.
 {
     auto const el = std::find_if( entries.begin(), entries.end(),
     [&it, &beta]( icg_entry const & rit ) {
         return rit.matches( it, beta );
     } );
     if( el != entries.end() ) {
         return &*el;
     }
     return nullptr;
 }
References entries.
Referenced by npc::wants_to_buy().
reset()
void shopkeeper_blacklist::reset () static
Definition at line 49 of file shop_cons_rate.cpp.
 {
     shop_blacklist_factory.reset();
 }
References anonymous_namespace{shop_cons_rate.cpp}::shop_blacklist_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
entries
std::vector<icg_entry> shopkeeper_blacklist::entries
Definition at line 69 of file shop_cons_rate.h.
Referenced by load(), and matches().
id
shopkeeper_blacklist_id shopkeeper_blacklist::id
Definition at line 66 of file shop_cons_rate.h.
was_loaded
bool shopkeeper_blacklist::was_loaded = false
Definition at line 67 of file shop_cons_rate.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/shop_cons_rate.h
src/shop_cons_rate.cpp