Cataclysm DDA: overmap_path_params Struct Reference
overmap_path_params Struct Reference
#include <overmapbuffer.h>
Public Member Functions
void set_cost (const oter_travel_cost_type &type, int v)
int get_cost (const oter_travel_cost_type &type) const
Static Public Member Functions
static overmap_path_params for_player ()
static overmap_path_params for_npc ()
static overmap_path_params for_land_vehicle (float offroad_coeff, bool tiny, bool amphibious)
static overmap_path_params for_watercraft ()
static overmap_path_params for_aircraft ()
Public Attributes
std::map< oter_travel_cost_type, int > travel_cost_per_type
bool avoid_danger = true
bool only_known_by_player = true
Static Public Attributes
static constexpr int standard_cost = 10
Detailed Description
Definition at line 40 of file overmapbuffer.h.
Member Function Documentation
for_aircraft()
overmap_path_params overmap_path_params::for_aircraft () static
Definition at line 905 of file overmapbuffer.cpp.
 {
     overmap_path_params ret;
     ret.set_cost( oter_travel_cost_type::air, 10 );
     return ret;
 }
References air, and cata::hash64_detail::ret.
Referenced by overmap_ui::get_overmap_path_to().
for_land_vehicle()
overmap_path_params overmap_path_params::for_land_vehicle (float offroad_coeff, bool tiny, bool amphibious) static
Definition at line 878 of file overmapbuffer.cpp.
 {
     const bool can_offroad = offroad_coeff >= 0.05;
     overmap_path_params ret;
     ret.set_cost( oter_travel_cost_type::road, 10 );
     const int field_cost = can_offroad ? std::lround( 15 / std::min( 1.0f, offroad_coeff ) ) : -1;
     ret.set_cost( oter_travel_cost_type::field, field_cost );
     ret.set_cost( oter_travel_cost_type::dirt_road, field_cost );
     ret.set_cost( oter_travel_cost_type::trail,
                   ( can_offroad && tiny ) ? field_cost + 10 : -1 );
     if( amphibious ) {
         const overmap_path_params boat_params = overmap_path_params::for_watercraft();
         ret.set_cost( oter_travel_cost_type::water, boat_params.get_cost( oter_travel_cost_type::water ) );
         ret.set_cost( oter_travel_cost_type::shore, boat_params.get_cost( oter_travel_cost_type::shore ) );
     }
     return ret;
 }
References dirt_road, field, for_watercraft(), get_cost(), min(), cata::hash64_detail::ret, road, shore, tiny, trail, and water.
Referenced by overmap_ui::get_overmap_path_to().
for_npc()
overmap_path_params overmap_path_params::for_npc () static
Definition at line 870 of file overmapbuffer.cpp.
 {
     overmap_path_params ret = overmap_path_params::for_player();
     ret.only_known_by_player = false;
     ret.avoid_danger = false;
     return ret;
 }
References for_player(), and cata::hash64_detail::ret.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_goal(), talk_function::goto_location(), anonymous_namespace{do_turn.cpp}::overmap_npc_move(), and npc::set_omt_destination().
for_player()
overmap_path_params overmap_path_params::for_player () static
Definition at line 856 of file overmapbuffer.cpp.
 {
     overmap_path_params ret;
     ret.set_cost( oter_travel_cost_type::road, 10 );
     ret.set_cost( oter_travel_cost_type::dirt_road, 10 );
     ret.set_cost( oter_travel_cost_type::field, 15 );
     ret.set_cost( oter_travel_cost_type::trail, 18 );
     ret.set_cost( oter_travel_cost_type::shore, 20 );
     ret.set_cost( oter_travel_cost_type::forest, 30 );
     ret.set_cost( oter_travel_cost_type::swamp, 100 );
     ret.set_cost( oter_travel_cost_type::other, 30 );
     return ret;
 }
References dirt_road, field, forest, other, cata::hash64_detail::ret, road, shore, swamp, and trail.
Referenced by for_npc(), and overmap_ui::get_overmap_path_to().
for_watercraft()
overmap_path_params overmap_path_params::for_watercraft () static
Definition at line 897 of file overmapbuffer.cpp.
 {
     overmap_path_params ret;
     ret.set_cost( oter_travel_cost_type::water, 10 );
     ret.set_cost( oter_travel_cost_type::shore, 20 );
     return ret;
 }
References cata::hash64_detail::ret, shore, and water.
Referenced by for_land_vehicle(), and overmap_ui::get_overmap_path_to().
get_cost()
int overmap_path_params::get_cost (const oter_travel_cost_type & type) const inline
Definition at line 48 of file overmapbuffer.h.
{
         auto it = travel_cost_per_type.find( type );
         return it != travel_cost_per_type.end() ? it->second : -1;
     }
References type.
Referenced by for_land_vehicle(), and get_terrain_cost().
set_cost()
void overmap_path_params::set_cost (const oter_travel_cost_type & type, int v) inline
Definition at line 45 of file overmapbuffer.h.
{
         travel_cost_per_type.emplace( type, v );
     }
References type.
Referenced by overmap_ui::get_overmap_path_to().
Member Data Documentation
avoid_danger
bool overmap_path_params::avoid_danger = true
Definition at line 42 of file overmapbuffer.h.
Referenced by get_terrain_cost().
only_known_by_player
bool overmap_path_params::only_known_by_player = true
Definition at line 43 of file overmapbuffer.h.
Referenced by get_terrain_cost().
standard_cost
constexpr int overmap_path_params::standard_cost = 10 static constexpr
Definition at line 52 of file overmapbuffer.h.
travel_cost_per_type
std::map<oter_travel_cost_type, int> overmap_path_params::travel_cost_per_type
Definition at line 41 of file overmapbuffer.h.
The documentation for this struct was generated from the following files:
src/overmapbuffer.h
src/overmapbuffer.cpp