Cataclysm DDA: mod_tracker Struct Reference
mod_tracker Struct Reference
#include <mod_tracker.h>
Classes
struct has_src_member
Template magic to determine if the conditions above are satisfied.
struct has_src_member< T, std::void_t< decltype(std::declval< T & >().src.emplace_back(std::declval< T & >().id, mod_id()))> >
Static Public Member Functions
template<typename T , typename std::enable_if_t< !has_src_member< T >::value > * = nullptr>
static void assign_src (T &, const std::string_view)
Dummy function, for if those conditions are not satisfied.
template<typename T , typename std::enable_if_t< has_src_member< T >::value > * = nullptr>
static void assign_src (T &def, const std::string &src)
If those conditions are satisfied, keep track of where this item has been modified.
template<typename T , typename std::enable_if_t< !has_src_member< T >::value > * = nullptr>
static void check_duplicate_entries (const T &n, const T &)
Dummy function, for if those conditions are not satisfied.
template<typename T , typename std::enable_if_t< has_src_member< T >::value > * = nullptr>
static void check_duplicate_entries (const T &n, const T &o)
If those conditions are satisfied, keep track of where this item has been modified.
Detailed Description
Definition at line 34 of file mod_tracker.h.
Member Function Documentation
assign_src() [1/2]
template<typename T , typename std::enable_if_t< !has_src_member< T >::value > * = nullptr> static void mod_tracker::assign_src (T & , const std::string_view) inline static
Dummy function, for if those conditions are not satisfied.
Definition at line 45 of file mod_tracker.h.
{
     }
Referenced by overmap_specials::create_building_from(), generic_factory< T >::load(), recipe_dictionary::load(), and effect_on_conditions::load_inline_eoc().
assign_src() [2/2]
template<typename T , typename std::enable_if_t< has_src_member< T >::value > * = nullptr> static void mod_tracker::assign_src (T & def, const std::string & src) inline static
If those conditions are satisfied, keep track of where this item has been modified.
Definition at line 50 of file mod_tracker.h.
{
         // We need to make sure we're keeping where this entity has been loaded
         // If the id this was last loaded with is not this one, discard the history and start again
         if( !def.src.empty() && def.src.back().first != def.id ) {
             def.src.clear();
         }
         def.src.emplace_back( def.id, mod_id( src ) );
     }
check_duplicate_entries() [1/2]
template<typename T , typename std::enable_if_t< !has_src_member< T >::value > * = nullptr> static void mod_tracker::check_duplicate_entries (const T & n, const T &) inline static
Dummy function, for if those conditions are not satisfied.
Definition at line 61 of file mod_tracker.h.
{
         static bool reported = false;
         // We don't need to complain more than once, it's spammy.
         if( reported ) {
             return;
         }
         reported = true;
         DebugLog( D_INFO, D_MAIN ) << __FILE__ << ":" << __LINE__ << ": " << "Tried check if '" <<
                                    n.id.str() << "' had a duplicate, but type '" << demangle( typeid( T ).name() ) <<
                                    "' does not track object sources";
     }
References D_INFO, D_MAIN, DebugLog(), demangle(), and om_direction::name().
Referenced by generic_factory< T >::insert(), and Item_factory::load_basic_info().
check_duplicate_entries() [2/2]
template<typename T , typename std::enable_if_t< has_src_member< T >::value > * = nullptr> static void mod_tracker::check_duplicate_entries (const T & n, const T & o) inline static
If those conditions are satisfied, keep track of where this item has been modified.
Definition at line 75 of file mod_tracker.h.
{
         // We need to make sure we're keeping where this entity has been loaded
         // If the id this was last loaded with is not this one, discard the history and start again
         if( n.src.back() == o.src.back() ) {
             throw mod_error( string_format( "%s (%s) has two definitions from the same source (%s)!",
                                             n.id.str(), demangle( typeid( T ).name() ), n.src.back().second.str() ) );
         }
     }
References demangle(), om_direction::name(), and string_format().
The documentation for this struct was generated from the following file:
src/mod_tracker.h