Cataclysm DDA: proficiency_category Struct Reference
proficiency_category Struct Reference
#include <proficiency.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
Static Public Member Functions
static void load_proficiency_categories (const JsonObject &jo, const std::string &src)
static void reset ()
static const std::vector< proficiency_category > & get_all ()
Public Attributes
proficiency_category_id id
translation _name
translation _description
bool was_loaded = false
Detailed Description
Definition at line 51 of file proficiency.h.
Member Function Documentation
get_all()
const std::vector< proficiency_category > & proficiency_category::get_all () static
Definition at line 135 of file proficiency.cpp.
 {
     return proficiency_category_factory.get_all();
 }
References anonymous_namespace{proficiency.cpp}::proficiency_category_factory.
Referenced by prof_window::populate_categories().
load()
void proficiency_category::load (const JsonObject & jo, std::string_view src)
Definition at line 124 of file proficiency.cpp.
 {
     mandatory( jo, was_loaded, "name", _name );
     mandatory( jo, was_loaded, "description", _description );
 }
References _description, _name, mandatory, and was_loaded.
load_proficiency_categories()
void proficiency_category::load_proficiency_categories (const JsonObject & jo, const std::string & src) static
Definition at line 76 of file proficiency.cpp.
 {
     proficiency_category_factory.load( jo, src );
 }
References anonymous_namespace{proficiency.cpp}::proficiency_category_factory.
Referenced by DynamicDataLoader::initialize().
reset()
void proficiency_category::reset () static
Definition at line 93 of file proficiency.cpp.
 {
     proficiency_category_factory.reset();
 }
References anonymous_namespace{proficiency.cpp}::proficiency_category_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
_description
translation proficiency_category::_description
Definition at line 54 of file proficiency.h.
Referenced by load().
_name
translation proficiency_category::_name
Definition at line 53 of file proficiency.h.
Referenced by load().
id
proficiency_category_id proficiency_category::id
Definition at line 52 of file proficiency.h.
was_loaded
bool proficiency_category::was_loaded = false
Definition at line 55 of file proficiency.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/proficiency.h
src/proficiency.cpp