Cataclysm DDA: profession_blacklist Struct Reference
profession_blacklist Struct Reference
#include <profession.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view)
void check_consistency () const
Static Public Member Functions
static void load_profession_blacklist (const JsonObject &jo, std::string_view src)
static void reset ()
Public Attributes
std::set< string_id< profession > > professions
bool whitelist = false
Detailed Description
Definition at line 172 of file profession.h.
Member Function Documentation
check_consistency()
void profession_blacklist::check_consistency () const
Definition at line 114 of file profession.cpp.
 {
     for( const string_id<profession> &p : professions ) {
         if( !p.is_valid() ) {
             debugmsg( "Invalid profession %s in blacklist", p.str() );
         }
     }
 }
References debugmsg, and professions.
Referenced by profession::check_definitions().
load()
void profession_blacklist::load (const JsonObject & jo, std::string_view)
Definition at line 94 of file profession.cpp.
 {
     if( !professions.empty() ) {
         DebugLog( D_INFO, DC_ALL ) << "Loading profession black with one already loaded, resetting";
         profession_blacklist::reset();
     }
     const std::string type = jo.get_string( "subtype" );
     if( type == "whitelist" ) {
         whitelist = true;
     } else if( type == "blacklist" ) {
         whitelist = false;
     } else {
         jo.throw_error( "Invalid subtype %s for profession blacklist" );
     }
     mandatory( jo, false, "professions", professions );
 }
References D_INFO, DC_ALL, DebugLog(), JsonObject::get_string(), mandatory, professions, reset(), JsonObject::throw_error(), type, and whitelist.
Referenced by load_profession_blacklist().
load_profession_blacklist()
void profession_blacklist::load_profession_blacklist (const JsonObject & jo, std::string_view src) static
Definition at line 88 of file profession.cpp.
 {
     prof_blacklist.load( jo, src );
 }
References load(), and prof_blacklist.
Referenced by DynamicDataLoader::initialize().
reset()
void profession_blacklist::reset () static
Definition at line 123 of file profession.cpp.
 {
     prof_blacklist.professions.clear();
     prof_blacklist.whitelist = false;
 }
References prof_blacklist, professions, and whitelist.
Referenced by load(), and DynamicDataLoader::unload_data().
Member Data Documentation
professions
std::set<string_id<profession> > profession_blacklist::professions
Definition at line 173 of file profession.h.
Referenced by check_consistency(), profession::is_blacklisted(), load(), and reset().
whitelist
bool profession_blacklist::whitelist = false
Definition at line 174 of file profession.h.
Referenced by profession::is_blacklisted(), load(), and reset().
The documentation for this struct was generated from the following files:
src/profession.h
src/profession.cpp