Cataclysm DDA: Target_attributes Struct Reference
Target_attributes Struct Reference
#include <ranged.h>
Public Member Functions
Target_attributes ()=default
Target_attributes (tripoint src, tripoint target)
Target_attributes (int rng, double size, float l, bool can_see)
Public Attributes
int range = 1
double size = 0.5
double size_in_moa = 10800.0
float light = 0.0f
bool visible = true
Detailed Description
Definition at line 85 of file ranged.h.
Constructor & Destructor Documentation
Target_attributes() [1/3]
Target_attributes::Target_attributes () explicit default
Target_attributes() [2/3]
Target_attributes::Target_attributes (tripoint src, tripoint target) explicit
Definition at line 1602 of file ranged.cpp.
 {
     Creature *target_critter = get_creature_tracker().creature_at( target );
     Creature *shooter = get_creature_tracker().creature_at( src );
     range = rl_dist( src, target );
     size = target_critter != nullptr ?
            target_critter->ranged_target_size() :
            get_map().ranged_target_size( target );
     size_in_moa = target_size_in_moa( range, size ) ;
     light = get_map().ambient_light_at( target );
     visible = shooter->sees( target );
 }
References map::ambient_light_at(), creature_tracker::creature_at(), get_creature_tracker(), get_map(), light, range, Creature::ranged_target_size(), map::ranged_target_size(), rl_dist(), Creature::sees(), size, size_in_moa, target_size_in_moa(), and visible.
Target_attributes() [3/3]
Target_attributes::Target_attributes (int rng, double size, float l, bool can_see) explicit
Definition at line 1615 of file ranged.cpp.
 {
     range = rng;
     size = target_size;
     size_in_moa = target_size_in_moa( range, size );
     light = light_target;
     visible = can_see;
 }
References light, range, rng(), size, size_in_moa, target_size_in_moa(), and visible.
Member Data Documentation
light
float Target_attributes::light = 0.0f
Definition at line 89 of file ranged.h.
Referenced by Character::fastest_aiming_method_speed(), and Target_attributes().
range
int Target_attributes::range = 1
Definition at line 86 of file ranged.h.
Referenced by confidence_estimate(), Character::fastest_aiming_method_speed(), and Target_attributes().
size
double Target_attributes::size = 0.5
Definition at line 87 of file ranged.h.
Referenced by confidence_estimate(), and Target_attributes().
size_in_moa
double Target_attributes::size_in_moa = 10800.0
Definition at line 88 of file ranged.h.
Referenced by Character::fastest_aiming_method_speed(), and Target_attributes().
visible
bool Target_attributes::visible = true
Definition at line 90 of file ranged.h.
Referenced by Character::fastest_aiming_method_speed(), and Target_attributes().
The documentation for this struct was generated from the following files:
src/ranged.h
src/ranged.cpp