Cataclysm DDA: construction Struct Reference
construction Struct Reference
#include <construction.h>
Public Member Functions
int adjusted_time () const
int print_time (const catacurses::window &w, const point &, int width, nc_color col) const
std::vector< std::string > get_folded_time_string (int width) const
float time_scale () const
Public Attributes
construction_category_id category
construction_group_str_id group
translation pre_note
std::string pre_terrain
std::string post_terrain
std::optional< item_group_id > byproduct_item_group
std::map< std::string, bool > pre_flags
std::set< std::string > post_flags
std::map< skill_id, int > required_skills
Skill->skill level mapping.
std::vector< std::pair< requirement_id, int > > reqs_using
requirement_id requirements
construction_id id = construction_id(-1)
construction_str_id str_id = construction_str_id::NULL_ID()
int time = 0
bool vehicle_start = false
bool(* pre_special)(const tripoint_bub_ms &)
std::vector< bool(*)(const tripoint_bub_ms &)> pre_specials
void(* do_turn_special)(const tripoint_bub_ms &, Character &)
void(* post_special)(const tripoint_bub_ms &, Character &)
std::vector< void(*)(const tripoint_bub_ms &, Character &)> post_specials
void(* explain_failure)(const tripoint_bub_ms &)
bool pre_is_furniture = false
bool post_is_furniture = false
bool on_display = true
bool dark_craftable = false
bool strict = false
float activity_level = MODERATE_EXERCISE
Private Member Functions
std::string get_time_string () const
Detailed Description
Definition at line 43 of file construction.h.
Member Function Documentation
adjusted_time()
int construction::adjusted_time () const
Definition at line 2172 of file construction.cpp.
 {
     int final_time = time;
     int assistants = 0;
     for( Character *elem : get_avatar().get_crafting_helpers() ) {
         if( elem->meets_skill_requirements( *this ) ) {
             assistants++;
         }
     }
     if( assistants >= 2 ) {
         final_time *= 0.4f;
     } else if( assistants == 1 ) {
         final_time *= 0.75f;
     }
     final_time *= time_scale();
     return final_time;
 }
References get_avatar(), time, and time_scale().
Referenced by activity_handlers::build_do_turn(), and get_time_string().
get_folded_time_string()
std::vector< std::string > construction::get_folded_time_string (int width) const
Definition at line 2200 of file construction.cpp.
 {
     std::string time_text = get_time_string();
     std::vector<std::string> folded_time = foldstring( time_text, width );
     return folded_time;
 }
References foldstring(), get_time_string(), and time_text.
get_time_string()
std::string construction::get_time_string () const private
Definition at line 2194 of file construction.cpp.
 {
     const time_duration turns = time_duration::from_moves( adjusted_time() );
     return _( "Time to complete: " ) + colorize( to_string( turns ), color_data );
 }
References _, adjusted_time(), color_data, colorize(), time_duration::from_moves(), and to_string().
Referenced by get_folded_time_string(), and print_time().
print_time()
int construction::print_time (const catacurses::window & w, const point & p, int width, nc_color col) const
Definition at line 2155 of file construction.cpp.
 {
     std::string text = get_time_string();
     return fold_and_print( w, p, width, col, text );
 }
References fold_and_print(), and get_time_string().
time_scale()
float construction::time_scale () const
Definition at line 2162 of file construction.cpp.
 {
     //incorporate construction time scaling
     if( get_option<int>( "CONSTRUCTION_SCALING" ) == 0 ) {
         return calendar::season_ratio();
     } else {
         return get_option<int>( "CONSTRUCTION_SCALING" ) / 100.0;
     }
 }
References calendar::season_ratio().
Referenced by adjusted_time().
Member Data Documentation
activity_level
float construction::activity_level = MODERATE_EXERCISE
Definition at line 112 of file construction.h.
Referenced by activity_handlers::build_do_turn(), and load_construction().
byproduct_item_group
std::optional<item_group_id> construction::byproduct_item_group
Definition at line 56 of file construction.h.
Referenced by complete_construction(), and load_construction().
category
construction_category_id construction::category
Definition at line 45 of file construction.h.
Referenced by complete_construction(), and load_construction().
dark_craftable
bool construction::dark_craftable = false
Definition at line 107 of file construction.h.
Referenced by load_construction().
do_turn_special
void(* construction::do_turn_special) (const tripoint_bub_ms &, Character &)
Definition at line 85 of file construction.h.
Referenced by activity_handlers::build_do_turn(), and load_construction().
explain_failure
void(* construction::explain_failure) (const tripoint_bub_ms &)
Definition at line 90 of file construction.h.
Referenced by load_construction().
group
construction_group_str_id construction::group
Definition at line 47 of file construction.h.
Referenced by anonymous_namespace{activity_item_handling.cpp}::_find_prereq(), complete_construction(), constructions_by_group(), find_base_construction(), blueprint_options::get_final_construction(), load_construction(), iexamine::part_con(), game::print_part_con_info(), and blueprint_options::query_con().
id
construction_id construction::id = construction_id(-1)
Definition at line 72 of file construction.h.
Referenced by construction_activity(), find_base_construction(), load_construction(), iexamine::part_con(), and place_construction().
on_display
bool construction::on_display = true
Definition at line 104 of file construction.h.
Referenced by load_construction().
post_flags
std::set<std::string> construction::post_flags
Definition at line 63 of file construction.h.
Referenced by complete_construction(), and load_construction().
post_is_furniture
bool construction::post_is_furniture = false
Definition at line 94 of file construction.h.
Referenced by anonymous_namespace{activity_item_handling.cpp}::_find_prereq(), anonymous_namespace{activity_item_handling.cpp}::already_done(), can_construct(), complete_construction(), construction_menu(), and load_construction().
post_special
void(* construction::post_special) (const tripoint_bub_ms &, Character &)
Definition at line 87 of file construction.h.
Referenced by complete_construction(), and load_construction().
post_specials
std::vector<void (*)(const tripoint_bub_ms &, Character &)> construction::post_specials
Definition at line 88 of file construction.h.
Referenced by complete_construction(), and load_construction().
post_terrain
std::string construction::post_terrain
Definition at line 53 of file construction.h.
Referenced by anonymous_namespace{activity_item_handling.cpp}::_can_construct(), anonymous_namespace{activity_item_handling.cpp}::_find_prereq(), anonymous_namespace{activity_item_handling.cpp}::_get_id(), anonymous_namespace{activity_item_handling.cpp}::already_done(), can_construct(), complete_construction(), construction_menu(), blueprint_options::get_final_construction(), load_construction(), and blueprint_options::query_con().
pre_flags
std::map<std::string, bool> construction::pre_flags
Definition at line 60 of file construction.h.
Referenced by anonymous_namespace{activity_item_handling.cpp}::_find_prereq(), can_construct_furn_ter(), and load_construction().
pre_is_furniture
bool construction::pre_is_furniture = false
Definition at line 92 of file construction.h.
Referenced by has_pre_terrain(), and load_construction().
pre_note
translation construction::pre_note
Definition at line 49 of file construction.h.
Referenced by load_construction().
pre_special
bool(* construction::pre_special) (const tripoint_bub_ms &)
Definition at line 82 of file construction.h.
Referenced by can_construct(), and load_construction().
pre_specials
std::vector<bool (*)(const tripoint_bub_ms &)> construction::pre_specials
Definition at line 83 of file construction.h.
Referenced by can_construct(), and load_construction().
pre_terrain
std::string construction::pre_terrain
Definition at line 51 of file construction.h.
Referenced by anonymous_namespace{activity_item_handling.cpp}::_find_prereq(), blueprint_options::get_final_construction(), has_pre_terrain(), and load_construction().
reqs_using
std::vector<std::pair<requirement_id, int> > construction::reqs_using
Definition at line 68 of file construction.h.
Referenced by load_construction().
required_skills
std::map<skill_id, int> construction::required_skills
Skill->skill level mapping.
Can be empty.
Definition at line 66 of file construction.h.
Referenced by complete_construction(), construction_menu(), get_build_reqs_for_furn_ter_ids(), load_construction(), and Character::meets_skill_requirements().
requirements
requirement_id construction::requirements
Definition at line 69 of file construction.h.
Referenced by construction_activity(), construction_menu(), generic_multi_activity_check_requirement(), get_build_reqs_for_furn_ter_ids(), load_construction(), place_construction(), and player_can_build().
str_id
construction_str_id construction::str_id = construction_str_id::NULL_ID()
Definition at line 73 of file construction.h.
Referenced by complete_construction(), and load_construction().
strict
bool construction::strict = false
Definition at line 110 of file construction.h.
Referenced by find_base_construction(), and load_construction().
time
int construction::time = 0
Definition at line 76 of file construction.h.
Referenced by adjusted_time(), activity_handlers::build_do_turn(), complete_construction(), get_build_reqs_for_furn_ter_ids(), and load_construction().
vehicle_start
bool construction::vehicle_start = false
Definition at line 79 of file construction.h.
Referenced by load_construction().
The documentation for this struct was generated from the following files:
src/construction.h
src/construction.cpp