Cataclysm DDA: achievement_requirement Struct Reference
achievement_requirement Struct Reference
Public Member Functions
void deserialize (const JsonObject &jo)
void finalize ()
void check (const achievement_id &id) const
bool satisfied_by (const cata_variant &v) const
bool is_visible (achievement_completion ach_completed, bool req_completed) const
Public Attributes
string_id< event_statistic > statistic
achievement_comparison comparison
cata_variant target
requirement_visibility visibility = requirement_visibility::always
std::optional< translation > description
bool becomes_false = false
Detailed Description
Definition at line 162 of file achievement.cpp.
Member Function Documentation
check()
void achievement_requirement::check (const achievement_id & id) const inline
Definition at line 203 of file achievement.cpp.
{
         if( !statistic.is_valid() ) {
             debugmsg( "Achievement %s refers to invalid statistic %s", id.str(), statistic.str() );
         }
         if( target.type() != cata_variant_type::int_ && !description &&
             visibility != requirement_visibility::never &&
             comparison != achievement_comparison::anything ) {
             debugmsg( "Achievement %s has a non-integer requirement which is sometimes visible.  "
                       "Such requirements must have a description, but this one does not.",
                       id.str() );
         }
         if( !target.is_valid() ) {
             debugmsg( "Achievement %s has a requirement target %s of type %s, but that is not "
                       "a valid value of that type.",
                       id.str(), target.get_string(), io::enum_to_string( target.type() ) );
         }
         if( comparison != achievement_comparison::anything &&
             target.type() != statistic->type() ) {
             debugmsg( "Achievement %s has a requirement comparing a value of type %s to a value "
                       "of type %s.  Comparisons should be between values of the same type.",
                       id.str(), io::enum_to_string( target.type() ),
                       io::enum_to_string( statistic->type() ) );
         }
     }
References anything, comparison, debugmsg, description, io::enum_to_string(), cata_variant::get_string(), int_, cata_variant::is_valid(), string_id< T >::is_valid(), never, statistic, string_id< T >::str(), target, cata_variant::type(), event_statistic::type(), and visibility.
deserialize()
void achievement_requirement::deserialize (const JsonObject & jo) inline
Definition at line 171 of file achievement.cpp.
{
         if( !( jo.read( "event_statistic", statistic ) &&
                jo.read( "is", comparison ) &&
                ( comparison == achievement_comparison::anything ||
                  jo.read( "target", target ) ) ) ) {
             jo.throw_error( "Mandatory field missing for achievement requirement" );
         }
         jo.read( "visible", visibility, false );
         jo.read( "description", description, false );
     }
References anything, comparison, description, JsonObject::read(), statistic, target, JsonObject::throw_error(), and visibility.
finalize()
void achievement_requirement::finalize () inline
Definition at line 183 of file achievement.cpp.
                     {
         switch( comparison ) {
             case achievement_comparison::equal:
                 becomes_false = statistic->monotonicity() == monotonically::constant;
                 return;
             case achievement_comparison::less_equal:
                 becomes_false = is_increasing( statistic->monotonicity() );
                 return;
             case achievement_comparison::greater_equal:
                 becomes_false = is_decreasing( statistic->monotonicity() );
                 return;
             case achievement_comparison::anything:
                 becomes_false = true;
                 return;
             case achievement_comparison::last:
                 break;
         }
         cata_fatal( "Invalid achievement_comparison" );
     }
References anything, becomes_false, cata_fatal, comparison, constant, equal, greater_equal, is_decreasing(), is_increasing(), last, less_equal, event_statistic::monotonicity(), and statistic.
Referenced by achievement::finalize().
is_visible()
bool achievement_requirement::is_visible (achievement_completion ach_completed, bool req_completed) const inline
Definition at line 247 of file achievement.cpp.
{
         switch( visibility ) {
             case requirement_visibility::always:
                 return true;
             case requirement_visibility::when_requirement_completed:
                 return req_completed;
             case requirement_visibility::when_achievement_completed:
                 return ach_completed == achievement_completion::completed;
             case requirement_visibility::never:
                 return false;
             case requirement_visibility::last:
                 break;
         }
         cata_fatal( "Invalid requirement_visibility value" );
     }
References always, cata_fatal, completed, last, never, visibility, when_achievement_completed, and when_requirement_completed.
Referenced by text_for_requirement().
satisfied_by()
bool achievement_requirement::satisfied_by (const cata_variant & v) const inline
Definition at line 231 of file achievement.cpp.
{
         switch( comparison ) {
             case achievement_comparison::equal:
                 return v == target;
             case achievement_comparison::less_equal:
                 return v.get<int>() <= target.get<int>();
             case achievement_comparison::greater_equal:
                 return v.get<int>() >= target.get<int>();
             case achievement_comparison::anything:
                 return true;
             case achievement_comparison::last:
                 break;
         }
         cata_fatal( "Invalid achievement_requirement comparison value" );
     }
References anything, cata_fatal, comparison, equal, cata_variant::get(), greater_equal, last, less_equal, and target.
Referenced by text_for_requirement().
Member Data Documentation
becomes_false
bool achievement_requirement::becomes_false = false
Definition at line 169 of file achievement.cpp.
Referenced by finalize(), and achievement_tracker::set_requirement().
comparison
achievement_comparison achievement_requirement::comparison
Definition at line 164 of file achievement.cpp.
Referenced by check(), deserialize(), finalize(), satisfied_by(), and text_for_requirement().
description
std::optional<translation> achievement_requirement::description
Definition at line 167 of file achievement.cpp.
Referenced by check(), deserialize(), and text_for_requirement().
statistic
string_id<event_statistic> achievement_requirement::statistic
Definition at line 163 of file achievement.cpp.
Referenced by check(), deserialize(), finalize(), and text_for_requirement().
target
cata_variant achievement_requirement::target
Definition at line 165 of file achievement.cpp.
Referenced by check(), deserialize(), satisfied_by(), and text_for_requirement().
visibility
requirement_visibility achievement_requirement::visibility = requirement_visibility::always
Definition at line 166 of file achievement.cpp.
Referenced by check(), deserialize(), and is_visible().
The documentation for this struct was generated from the following file:
src/achievement.cpp