Cataclysm DDA: trait_and_var Struct Reference
trait_and_var Struct Reference
#include <mutation.h>
Public Member Functions
trait_and_var ()=default
trait_and_var (const trait_id &t, const std::string &v)
void deserialize (const JsonValue &jv)
void serialize (JsonOut &jsout) const
std::string name () const
std::string desc () const
bool operator== (const trait_and_var &other) const
Public Attributes
trait_id trait
std::string variant
Detailed Description
Definition at line 127 of file mutation.h.
Constructor & Destructor Documentation
trait_and_var() [1/2]
trait_and_var::trait_and_var () default
trait_and_var() [2/2]
trait_and_var::trait_and_var (const trait_id & t, const std::string & v) inline
Definition at line 132 of file mutation.h.
 : trait( t ), variant( v ) {}
Member Function Documentation
desc()
std::string trait_and_var::desc () const
Definition at line 282 of file mutation_data.cpp.
 {
     return trait->desc( variant );
 }
References mutation_branch::desc(), trait, and variant.
Referenced by draw_traits_info(), set_traits(), and diary::trait_changes().
deserialize()
void trait_and_var::deserialize (const JsonValue & jv)
Definition at line 256 of file mutation_data.cpp.
 {
     if( jv.test_string() ) {
         jv.read( trait );
     } else {
         JsonObject jo = jv.get_object();
         jo.read( "trait", trait );
         jo.read( "variant", variant );
     }
 }
References JsonValue::get_object(), JsonValue::read(), JsonObject::read(), JsonValue::test_string(), trait, and variant.
name()
std::string trait_and_var::name () const
Definition at line 277 of file mutation_data.cpp.
 {
     return trait->name( variant );
 }
References mutation_branch::name(), trait, and variant.
Referenced by draw_traits_info(), draw_traits_tab(), set_description(), set_traits(), and diary::trait_changes().
operator==()
bool trait_and_var::operator== (const trait_and_var & other) const inline
Definition at line 140 of file mutation.h.
{
         return trait == other.trait && variant == other.variant;
     }
References other, trait, and variant.
serialize()
void trait_and_var::serialize (JsonOut & jsout) const
Definition at line 267 of file mutation_data.cpp.
 {
     jsout.start_object();
     jsout.member( "trait", trait );
     jsout.member( "variant", variant );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), JsonOut::start_object(), trait, and variant.
Member Data Documentation
trait
trait_id trait_and_var::trait
Definition at line 128 of file mutation.h.
Referenced by desc(), deserialize(), draw_traits_info(), draw_traits_tab(), generic_barber(), Character::has_trait_variant(), mutation_branch::load_trait_migration(), name(), operator==(), serialize(), set_description(), set_traits(), and diary::trait_changes().
variant
std::string trait_and_var::variant
Definition at line 129 of file mutation.h.
Referenced by desc(), deserialize(), generic_barber(), Character::has_trait_variant(), mutation_branch::load_trait_migration(), name(), operator==(), and serialize().
The documentation for this struct was generated from the following files:
src/mutation.h
src/mutation_data.cpp