Cataclysm DDA: item_comp Struct Reference
item_comp Struct Reference
#include <requirements.h>
Public Member Functions
item_comp ()=default
item_comp (const itype_id &TYPE, int COUNT)
void load (const JsonValue &value)
void dump (JsonOut &jsout) const
bool has (const read_only_visitable &crafting_inv, const std::function< bool(const item &)> &filter, int batch=1, craft_flags=craft_flags::none, const std::function< void(int)> &visitor=std::function< void(int)>()) const
std::string to_string (int batch=1, int avail=0) const
nc_color get_color (bool has_one, const read_only_visitable &crafting_inv, const std::function< bool(const item &)> &filter, int batch=1) const
component_type get_component_type () const
Public Member Functions inherited from component
bool operator== (const component &rhs) const
bool operator!= (const component &rhs) const
bool operator< (const component &rhs) const
component ()=default
component (const itype_id &TYPE, int COUNT)
component (const itype_id &TYPE, int COUNT, bool RECOVERABLE)
void check_consistency (const std::string &display_name) const
Additional Inherited Members
Public Attributes inherited from component
itype_id type = itype_id::NULL_ID()
int count = 0
available_status available = available_status::a_false
bool recoverable = true
bool requirement = false
Detailed Description
Definition at line 110 of file requirements.h.
Constructor & Destructor Documentation
item_comp() [1/2]
item_comp::item_comp () default
item_comp() [2/2]
item_comp::item_comp (const itype_id & TYPE, int COUNT) inline
Definition at line 112 of file requirements.h.
 : component( TYPE, COUNT ) { }
Member Function Documentation
dump()
void item_comp::dump (JsonOut & jsout) const
Definition at line 283 of file requirements.cpp.
 {
     jsout.start_array();
     jsout.write( type );
     jsout.write( count );
     if( !recoverable ) {
         jsout.write( "NO_RECOVER" );
     }
     if( requirement ) {
         jsout.write( "LIST" );
     }
     jsout.end_array();
 }
References component::count, JsonOut::end_array(), component::recoverable, component::requirement, JsonOut::start_array(), component::type, and JsonOut::write().
get_color()
nc_color item_comp::get_color (bool has_one, const read_only_visitable & crafting_inv, const std::function< bool(const item &)> & filter, int batch = 1) const
Definition at line 983 of file requirements.cpp.
 {
     if( available == available_status::a_insufficient ) {
         return c_brown;
     } else if( has( crafting_inv, filter, batch ) ) {
         const inventory *inv = static_cast<const inventory *>( &crafting_inv );
         // Will use non-empty liquid container
         if( std::any_of( type->pockets.begin(), type->pockets.end(), []( const pocket_data & d ) {
         return d.type == pocket_type::CONTAINER && d.watertight;
     } ) && inv != nullptr && inv->must_use_liq_container( type, count * batch ) ) {
             return c_magenta;
         }
         if( inv != nullptr && inv->must_use_hallu_poison( type, count * batch ) ) {
             return c_magenta;
         }
         // Will use favorited component
         if( !has( crafting_inv, [&filter]( const item & it ) {
         return filter( it ) && !it.is_favorite;
         }, batch ) ) {
             return c_pink;
         }
         // Component is OK
         return c_green;
     }
     return has_one ? c_dark_gray  : c_red;
 }
References a_insufficient, component::available, c_brown, c_dark_gray, c_green, c_magenta, c_pink, c_red, component::count, filter, has(), item::is_favorite, inventory::must_use_hallu_poison(), inventory::must_use_liq_container(), itype::pockets, and component::type.
get_component_type()
component_type item_comp::get_component_type () const inline
Definition at line 123 of file requirements.h.
{
         return component_type::ITEM;
     }
References ITEM.
has()
bool item_comp::has (const read_only_visitable & crafting_inv, const std::function< bool(const item &)> & filter, int batch = 1, craft_flags = craft_flags::none, const std::function< void(int)> & visitor = std::function<void(int)>()) const
Definition at line 967 of file requirements.cpp.
 {
     if( get_player_character().has_trait( trait_DEBUG_HS ) ) {
         return true;
     }
     const int cnt = std::abs( count ) * batch;
     if( item::count_by_charges( type ) ) {
         return crafting_inv.has_charges( type, cnt, filter );
     } else {
         return crafting_inv.has_components( type, cnt, filter );
     }
 }
References abs(), component::count, item::count_by_charges(), filter, get_player_character(), read_only_visitable::has_charges(), read_only_visitable::has_components(), trait_DEBUG_HS, and component::type.
Referenced by requirement_data::check_enough_materials(), and get_color().
load()
void item_comp::load (const JsonValue & value)
Definition at line 264 of file requirements.cpp.
 {
     JsonArray comp = value.get_array();
     comp.read( 0, type, true );
     count = comp.get_int( 1 );
     size_t handled = 2;
     while( comp.size() > handled ) {
         const std::string &flag = comp.get_string( handled++ );
         if( flag == "NO_RECOVER" ) {
             recoverable = false;
         } else if( flag == "LIST" ) {
             requirement = true;
         }
     }
     if( count <= 0 ) {
         value.throw_error( "item count must be a positive number" );
     }
 }
References component::count, JsonValue::get_array(), JsonArray::get_int(), JsonArray::get_string(), JsonArray::read(), component::recoverable, component::requirement, JsonArray::size(), JsonValue::throw_error(), and component::type.
to_string()
std::string item_comp::to_string (int batch = 1, int avail = 0) const
Definition at line 167 of file requirements.cpp.
 {
     const int c = std::abs( count ) * batch;
     const item item_temp = item( type );
     if( item_temp.count_by_charges() ) {
         // Count-by-charge
         if( avail == item::INFINITE_CHARGES ) {
             //~ %1$s: item name, %2$d: charge requirement
             return string_format( npgettext( "requirement", "%2$d %1$s (have infinite)",
                                              "%2$d %1$s (have infinite)",
                                              c ),
                                   item_temp.tname( 1, tname::item_name ), c );
         } else if( avail > 0 ) {
             //~ %1$s: item name, %2$d: charge requirement, %3%d: available charges
             return string_format( npgettext( "requirement", "%2$d %1$s (have %3$d)",
                                              "%2$d %1$s (have %3$d)", c ),
                                   item_temp.tname( 1, tname::item_name ), c, avail );
         } else {
             //~ %1$s: item name, %2$d: charge requirement
             return string_format( npgettext( "requirement", "%2$d %1$s", "%2$d %1$s", c ),
                                   item_temp.tname( 1, tname::item_name ), c );
         }
     } else {
         if( avail == item::INFINITE_CHARGES ) {
             //~ %1$s: item name, %2$d: required count
             return string_format( npgettext( "requirement", "%2$d %1$s (have infinite)",
                                              "%2$d %1$s (have infinite)",
                                              c ),
                                   item_temp.tname( c, tname::item_name ), c );
         } else if( avail > 0 ) {
             //~ %1$s: item name, %2$d: required count, %3%d: available count
             return string_format( npgettext( "requirement", "%2$d %1$s (have %3$d)",
                                              "%2$d %1$s (have %3$d)", c ),
                                   item_temp.tname( c, tname::item_name ), c, avail );
         } else {
             //~ %1$s: item name, %2$d: required count
             return string_format( npgettext( "requirement", "%2$d %1$s", "%2$d %1$s", c ),
                                   item_temp.tname( c, tname::item_name ), c );
         }
     }
 }
References abs(), c, component::count, item::count_by_charges(), item::INFINITE_CHARGES, item, tname::item_name(), npgettext, string_format(), item::tname(), and component::type.
The documentation for this struct was generated from the following files:
src/requirements.h
src/requirements.cpp