Cataclysm DDA: trap Struct Reference
trap Struct Reference
Some traps aren't actually traps in the usual sense of the word.
#include <trap.h>
Public Member Functions
std::string name () const
bool is_always_invisible () const
There are special always invisible traps.
bool operator== (const trap_id &id) const
bool operator!= (const trap_id &id) const
bool has_flag (const flag_id &flag) const
bool has_memorial_msg () const
std::string memorial_msg (bool male) const
void examine (const tripoint &examp) const
Called when the player examines a tile.
update_mapgen_id map_regen_target () const
int get_avoidance () const
Whether triggering the trap can be avoid (if greater than 0) and if so, this is compared to dodge skill (with some adjustments).
bool is_benign () const
If true, this is not really a trap and there won't be any safety queries before stepping onto it (e.g.
bool easy_take_down () const
bool is_trivial_to_spot () const
bool can_not_be_disarmed () const
Some traps are part of the terrain (e.g.
bool detected_by_ground_sonar () const
Whether this kind of trap will be detected by ground sonar (e.g.
bool detected_by_echolocation () const
Whether this kind of trap will be detected by regular sonar (it is not buried and it's a solid object).
bool detect_trap (const tripoint &pos, const Character &p) const
Player has not yet seen the trap and returns the variable chance, at this moment, of whether the trap is seen or not.
bool can_see (const tripoint &pos, const Character &p) const
Can player/npc p see this kind of trap, either by their memory (they known there is the trap) or by the visibility of the trap (the trap is not hidden at all)?
bool has_trigger_msg () const
std::string get_trigger_message_u () const
Prints a trap-specific trigger message when player steps on it.
std::string get_trigger_message_npc () const
Prints a trap-specific trigger message when NPC or a monster steps on it.
void trigger (const tripoint &pos, Creature &creature) const
This applies the effects of the trap to the world and possibly to the triggering object (creature, item).
void trigger (const tripoint &pos, item &item) const
void trigger (const tripoint &pos) const
bool triggered_by_item (const item &itm) const
If the given item is throw onto the trap, does it trigger the trap?
void on_disarmed (map &m, const tripoint &p) const
Called when a trap at the given point in the map has been disarmed.
int get_trap_radius () const
This is used when defining area this trap occupies.
bool is_null () const
Whether this is the null-traps, aka no trap at all.
void load (const JsonObject &jo, std::string_view src)
Loads this specific trap.
std::string debug_describe () const
Static Public Member Functions
Initialization
Those functions are used by the DynamicDataLoader, see there.
static void load_trap (const JsonObject &jo, const std::string &src)
Loads the trap and adds it to the trapmap, and the traplist.
static void reset ()
Releases the loaded trap objects in trapmap and traplist.
static void finalize ()
Stores the actual loadid of the loaded traps in the global tr_* variables.
static void check_consistency ()
Checks internal consistency (reference to other things like item ids etc.)
static size_t count ()
Public Attributes
trap_str_id id
std::vector< std::pair< trap_str_id, mod_id > > src
trap_id loadid
bool was_loaded = false
int sym = 0
nc_color color
fake_spell spell_data
int comfort = 0
units::temperature_delta floor_bedding_warmth = 0_C_delta
vehicle_handle_trap_data vehicle_data
Private Member Functions
void trigger (const tripoint &pos, Creature *creature, item *item) const
Trigger trap effects.
Private Attributes
int visibility = 1
How easy it is to spot the trap.
int avoidance = 0
int difficulty = 0
int trap_radius = 0
bool benign = false
bool always_invisible = false
update_mapgen_id map_regen
trap_function act
translation name_
std::optional< translation > memorial_male
std::optional< translation > memorial_female
std::optional< translation > trigger_message_u
std::optional< translation > trigger_message_npc
cata::flat_set< flag_id > _flags
units::mass trigger_weight = 500_gram
If an item with this weight or more is thrown onto the trap, it triggers.
std::pair< int, int > sound_threshold = {0, 0}
Determines how much sound is needed to trigger the trap.
int funnel_radius_mm = 0
std::vector< std::tuple< itype_id, int, int > > components
Funnels
Traps can act as funnels, for this they need a trap::funnel_radius_mm > 0.
Funnels are usual not hidden at all (trap::visibility == 0), are trap::benign and can be picked up easily (trap::difficulty == 0). The funnel filling is handled in weather.cpp. is_funnel is used the check whether the funnel specific code should be run for this trap.
bool is_funnel () const
double funnel_turns_per_charge (double rain_depth_mm_per_hour) const
bool has_sound_trigger () const
bool triggered_by_sound (int vol, int dist) const
static const std::vector< const trap * > & get_funnels ()
Returns all trap objects that are actually funnels (is_funnel returns true for all of them).
static const std::vector< const trap * > & get_sound_triggered_traps ()
Detailed Description
Some traps aren't actually traps in the usual sense of the word.
We use traps to implement funnels (the main map keeps a list of traps and we iterate over that list during rain in order to fill the containers with water). Use is_benign to check for that kind of "non-dangerous" traps. Traps that are not benign are considered dangerous.
Some traps are always invisible. They are never revealed as such to the player. They can still be triggered. Use is_always_invisible to check for that.
Traps names can be empty. This usually applies to always invisible traps.
Some traps are always revealed to the player (e.g. funnels). Other traps can be spotted when the player is close (also needs perception stat).
Use map::can_see_trap_at or trap::can_see to check whether a creature knows about a given trap. Monsters / NPCs should base their behavior on that information and not on a simple check for any trap being there (e.g. don't use map::tr_at(...).is_null() - that would reveal the existence of the trap).
Definition at line 109 of file trap.h.
Member Function Documentation
can_not_be_disarmed()
bool trap::can_not_be_disarmed () const
Some traps are part of the terrain (e.g.
pits) and can therefore not be disarmed via the usual mechanics. They can be "disarmed" by changing the terrain they are part of.
Definition at line 440 of file trap.cpp.
 {
     return difficulty >= 99;
 }
References difficulty.
Referenced by examine().
can_see()
bool trap::can_see (const tripoint & pos, const Character & p) const
Can player/npc p see this kind of trap, either by their memory (they known there is the trap) or by the visibility of the trap (the trap is not hidden at all)?
Definition at line 320 of file trap.cpp.
 {
     if( is_null() ) {
         // There is no trap at all, so logically one can not see it.
         return false;
     }
     if( is_always_invisible() ) {
         return false;
     }
     return visibility < 0 || p.knows_trap( pos );
 }
References is_always_invisible(), is_null(), Character::knows_trap(), math_opers::pos(), and visibility.
Referenced by Character::adjacent_tile(), Character::avoid_trap(), map::can_see_trap_at(), colorized_trap_name_at(), map::draw_maptile(), examine(), game::get_dangerous_tile(), vehicle::handle_trap(), advanced_inv_area::init(), place_trap_actor::is_allowed(), place_and_add_as_known(), game::print_trap_info(), and Character::search_surroundings().
check_consistency()
void trap::check_consistency () static
Checks internal consistency (reference to other things like item ids etc.)
Definition at line 423 of file trap.cpp.
 {
     for( const trap &t : trap_factory.get_all() ) {
         for( const auto &i : t.components ) {
             const itype_id &item_type = std::get<0>( i );
             if( !item::type_is_defined( item_type ) ) {
                 debugmsg( "trap %s has unknown item as component %s", t.id.str(), item_type.str() );
             }
         }
     }
 }
References debugmsg, string_id< T >::str(), anonymous_namespace{trap.cpp}::trap_factory, and item::type_is_defined().
Referenced by DynamicDataLoader::check_consistency().
count()
size_t trap::count () static
Definition at line 127 of file trap.cpp.
 {
     return trap_factory.size();
 }
References anonymous_namespace{trap.cpp}::trap_factory.
Referenced by map::map().
debug_describe()
std::string trap::debug_describe () const
Definition at line 462 of file trap.cpp.
 {
     return string_format( _( "Visible: %d\nAvoidance: %d\nDifficulty: %d\nBenign: %s" ), visibility,
                           avoidance, difficulty, is_benign() ? _( "Yes" ) : _( "No" ) );
 }
References _, avoidance, difficulty, is_benign(), string_format(), and visibility.
detect_trap()
bool trap::detect_trap (const tripoint & pos, const Character & p) const
Player has not yet seen the trap and returns the variable chance, at this moment, of whether the trap is seen or not.
Definition at line 265 of file trap.cpp.
 {
     // * Buried landmines, the silent killer, have a visibility of 10.
     // Assuming no knowledge of traps or proficiencies, and average per/int (8 each),
     // most characters will get a mean_roll of 6.5 against a trap that is one tile away.
     // With a std deviation of 3, that leaves a ~12% chance of spotting a landmine when you are next to it (per turn).
     // This gets worse if you are sleep deprived, or can't see as well.
     // Obviously it rapidly gets better as your skills improve, with most of the improvement coming from proficiencies.
     // Devices skill is helpful for spotting traps
     const float traps_skill_level = p.get_skill_level( skill_traps );
     // Perception is the main stat for spotting traps, int helps a bit.
     // In this case, stats are more important than skills.
     const float weighted_stat_average = ( 4.0f * p.per_cur + p.int_cur ) / 5.0f;
     // Eye encumbrance will penalize spotting
     const float encumbrance_penalty = p.encumb( bodypart_id( "eyes" ) ) / 10.0f;
     // The further away the trap is, the harder it is to spot.
     // Subtract 1 so that we don't get an unfair penalty when not quite on top of the trap.
     const int distance_penalty = rl_dist( p.pos(), pos ) - 1;
     int proficiency_effect = -1;
     // Without at least a basic traps proficiency, your skill level is effectively three levels lower.
     if( p.has_proficiency( proficiency_prof_traps ) ) {
         proficiency_effect += 1;
         // If you have the basic traps prof, negate the above penalty
     }
     if( p.has_proficiency( proficiency_prof_spotting ) ) {
         proficiency_effect += 3;
         // If you have the spotting proficiency, add a whopping 9 effective skill levels.
     }
     if( p.has_proficiency( proficiency_prof_trapsetting ) ) {
         proficiency_effect += 1;
         // Knowing how to set effective traps gives you a considerable bonus to spotting them as well.
     }
     // For every 1000 points of sleep deprivation, reduce your roll by 1.
     // As of this writing, sleep deprivation passively increases at the rate of 1 point per minute.
     const float sleepiness_penalty = p.get_sleep_deprivation() / 1000.0f;
     const float mean_roll = weighted_stat_average + ( traps_skill_level / 3.0f ) +
                             proficiency_effect - distance_penalty - sleepiness_penalty - encumbrance_penalty;
     const int roll = std::round( normal_roll( mean_roll, 3 ) );
     add_msg_debug( debugmode::DF_CHARACTER,
                    "Character %s rolling to detect trap %s. Actual roll: %i, average roll: %f, roll required to detect: %i.",
                    p.get_name(), name(), roll, mean_roll, visibility );
     return roll > visibility;
 }
References add_msg_debug, debugmode::DF_CHARACTER, Character::encumb(), Character::get_name(), Character::get_skill_level(), Character::get_sleep_deprivation(), Character::has_proficiency(), Character::int_cur, name(), normal_roll(), Character::per_cur, Creature::pos(), math_opers::pos(), proficiency_prof_spotting, proficiency_prof_traps, proficiency_prof_trapsetting, rl_dist(), round(), skill_traps, and visibility.
Referenced by Character::search_surroundings().
detected_by_echolocation()
bool trap::detected_by_echolocation () const
Whether this kind of trap will be detected by regular sonar (it is not buried and it's a solid object).
Definition at line 260 of file trap.cpp.
 {
     return has_flag( json_flag_ECHOLOCATION_DETECTABLE );
 }
References has_flag(), and json_flag_ECHOLOCATION_DETECTABLE.
Referenced by Character::echo_pulse().
detected_by_ground_sonar()
bool trap::detected_by_ground_sonar () const
Whether this kind of trap will be detected by ground sonar (e.g.
via the bionic).
Definition at line 252 of file trap.cpp.
 {
     return has_flag( json_flag_SONAR_DETECTABLE );
 }
References has_flag(), and json_flag_SONAR_DETECTABLE.
Referenced by Character::search_surroundings().
easy_take_down()
bool trap::easy_take_down () const
Returns
True for traps that can simply be taken down without any skill check or similar. This usually applies to traps like funnels, rollmat.
Definition at line 435 of file trap.cpp.
 {
     return avoidance == 0 && difficulty == 0;
 }
References avoidance, and difficulty.
Referenced by examine().
examine()
void trap::examine (const tripoint & examp) const
Called when the player examines a tile.
This is supposed to handled all kind of interaction of the player with the trap, including removal. It also handles visibility of the trap, and it does nothing when called on the null trap.
Definition at line 4535 of file iexamine.cpp.
 {
     avatar &player_character = get_avatar();
     map &here = get_map();
     // If the player can't see the trap, they can't interact with it.
     if( !can_see( examp, player_character ) ) {
         return;
     }
     if( player_character.cant_do_mounted() ) {
         return;
     }
     if( can_not_be_disarmed() ) {
         if( id != tr_ledge ) {
             add_msg( m_info, _( "That %s looks too dangerous to mess with.  Best leave it alone." ), name() );
         }
         return;
     }
     // Some traps are not actual traps. Those should get a different query, no skill checks, and the option to grab it right away.
     // If there is a telepad and we are anchored, there is no risk involved in disarming it also.
     if( easy_take_down() || ( id == tr_telepad &&
                               player_character.worn_with_flag(
                                   flag_DIMENSIONAL_ANCHOR ) ) ) { // Separated so saying no doesn't trigger the other query.
         if( !query_yn( _( "There is a %s there.  Take down?" ), name() ) ) {
             return;
         }
         add_msg( _( "The %s is taken down." ), name() );
         on_disarmed( here, examp );
         return;
     }
     if( query_yn( _( "There is a %s there.  Disarm?" ), name() ) ) {
         const float traps_skill_level = player_character.get_skill_level( skill_traps );
         const float traps_knowledge_level = player_character.get_knowledge_level( skill_traps );
         const float weighted_stat_average = ( 2.0f * player_character.per_cur + 3.0f *
                                               player_character.dex_cur +
                                               player_character.int_cur ) / 6.0f;
         int proficiency_effect = -2;
         // Without at least a basic traps proficiency, your skill level is effectively 2 levels lower.
         if( player_character.has_proficiency( proficiency_prof_traps ) ) {
             proficiency_effect = 0;
             // If you have the basic traps prof, negate the above penalty
         }
         if( player_character.has_proficiency( proficiency_prof_disarming ) ) {
             proficiency_effect = 4;
             // If you have the disarming proficiency, your skill level is effectively 4 levels higher.
         }
         if( player_character.has_proficiency( proficiency_prof_trapsetting ) ) {
             proficiency_effect += 1;
             // Knowing how to set traps does give you a small bonus to disarming them as well, regardless of your other bonuses.
         }
         const float mean_roll = ( ( traps_skill_level + traps_knowledge_level ) / 2 ) +
                                 ( weighted_stat_average / 4.0f ) + proficiency_effect;
         int roll = std::round( normal_roll( mean_roll, 3 ) );
         add_msg_debug( debugmode::DF_IEXAMINE, "Rolled %i, mean_roll %g. difficulty %i.", roll,
                        mean_roll, difficulty );
         //Difficulty 0 traps should succeed regardless of proficiencies. (i.e caltrops and nailboards)
         if( roll >= difficulty || difficulty == 0 ) {
             add_msg( _( "You disarm the trap!" ) );
             on_disarmed( here, examp );
             if( difficulty > 1.25 * traps_skill_level ) { // failure might have set off trap
                 player_character.practice( skill_traps, 1.5 * ( difficulty - traps_skill_level ) );
             }
         } else if( roll >= ( difficulty * .8 ) ) {
             add_msg( _( "You fail to disarm the trap." ) );
             if( difficulty > 1.25 * traps_skill_level ) {
                 player_character.practice( skill_traps, 1.5 * ( difficulty - traps_skill_level ) );
             }
         } else {
             add_msg( m_bad, _( "You fail to disarm the trap, and you set it off!" ) );
             trigger( examp, player_character );
             if( difficulty - roll <= 6 ) {
                 // Give xp for failing, but not if we failed terribly (in which
                 // case the trap may not be disarmable).
                 player_character.practice( skill_traps, 2 * difficulty );
             }
         }
         //Picking up bubble wrap continuously could powerlevel trap proficiencies, with no risk involved.
         if( difficulty != 0 ) {
             player_character.practice_proficiency( proficiency_prof_traps, 5_minutes );
             // Disarming a trap gives you a token bonus to learning to set them properly.
             player_character.practice_proficiency( proficiency_prof_trapsetting, 30_seconds );
             player_character.practice_proficiency( proficiency_prof_disarming, 5_minutes );
         }
         return;
     }
 }
References _, add_msg(), add_msg_debug, can_not_be_disarmed(), can_see(), Character::cant_do_mounted(), Character::dex_cur, debugmode::DF_IEXAMINE, difficulty, easy_take_down(), flag_DIMENSIONAL_ANCHOR, get_avatar(), Character::get_knowledge_level(), get_map(), Character::get_skill_level(), Character::has_proficiency(), Character::int_cur, m_bad, m_info, name(), normal_roll(), on_disarmed(), Character::per_cur, Character::practice(), Character::practice_proficiency(), proficiency_prof_disarming, proficiency_prof_traps, proficiency_prof_trapsetting, query_yn(), round(), skill_traps, tr_ledge, tr_telepad, trigger(), and Character::worn_with_flag().
Referenced by game::examine().
finalize()
void trap::finalize () static
Stores the actual loadid of the loaded traps in the global tr_* variables.
It also sets the trap ids of the terrain types that have built-in traps. Must be called after all traps have been loaded.
Definition at line 445 of file trap.cpp.
 {
     for( const trap &t_const : trap_factory.get_all() ) {
         trap &t = const_cast<trap &>( t_const );
         // We need to set int ids manually now
         t.loadid = t.id.id();
         if( t.is_funnel() ) {
             funnel_traps.push_back( &t );
         }
         if( t.has_sound_trigger() ) {
             sound_triggered_traps.push_back( &t );
         }
     }
     tr_null = trap_str_id::NULL_ID().id();
 }
References funnel_traps, has_sound_trigger(), string_id< T >::id(), id, is_funnel(), loadid, string_id< trap >::NULL_ID(), sound_triggered_traps, tr_null, and anonymous_namespace{trap.cpp}::trap_factory.
Referenced by DynamicDataLoader::finalize_loaded_data().
get_avoidance()
int trap::get_avoidance () const inline
Whether triggering the trap can be avoid (if greater than 0) and if so, this is compared to dodge skill (with some adjustments).
Smaller values means it's easier to dodge.
Definition at line 214 of file trap.h.
{
             return avoidance;
         }
References avoidance.
Referenced by Character::avoid_trap(), and monster::avoid_trap().
get_funnels()
const std::vector< const trap * > & trap::get_funnels () static
Returns all trap objects that are actually funnels (is_funnel returns true for all of them).
Definition at line 115 of file trap.cpp.
 {
     return funnel_traps;
 }
References funnel_traps.
Referenced by fill_water_collectors().
get_sound_triggered_traps()
const std::vector< const trap * > & trap::get_sound_triggered_traps () static
Definition at line 122 of file trap.cpp.
 {
     return sound_triggered_traps;
 }
References sound_triggered_traps.
Referenced by sounds::process_sounds().
get_trap_radius()
int trap::get_trap_radius () const inline
This is used when defining area this trap occupies.
A value of 0 means trap occupies exactly 1 tile.
Definition at line 312 of file trap.h.
{
             return trap_radius;
         }
References trap_radius.
Referenced by place_trap_actor::use().
get_trigger_message_npc()
std::string trap::get_trigger_message_npc () const inline
Prints a trap-specific trigger message when NPC or a monster steps on it.
Definition at line 267 of file trap.h.
{
             return trigger_message_npc->translated();
         }
References trigger_message_npc.
Referenced by map::maybe_trigger_prox_trap(), and map::maybe_trigger_trap().
get_trigger_message_u()
std::string trap::get_trigger_message_u () const inline
Prints a trap-specific trigger message when player steps on it.
Definition at line 261 of file trap.h.
{
             return trigger_message_u->translated();
         }
References trigger_message_u.
Referenced by map::maybe_trigger_prox_trap(), and map::maybe_trigger_trap().
has_flag()
bool trap::has_flag (const flag_id & flag) const inline
Definition at line 183 of file trap.h.
{
             return _flags.count( flag );
         }
References _flags.
Referenced by trapfunc::cast_spell(), construct::check_support_below(), map::creature_on_trap(), detected_by_echolocation(), detected_by_ground_sonar(), get_convection_temperature(), map::maybe_trigger_prox_trap(), map::maybe_trigger_trap(), and ter_furn_transform::transform().
has_memorial_msg()
bool trap::has_memorial_msg () const inline
Definition at line 187 of file trap.h.
{
             return memorial_male && memorial_female;
         }
References memorial_female, and memorial_male.
Referenced by memorial_logger::notify().
has_sound_trigger()
bool trap::has_sound_trigger () const
Definition at line 381 of file trap.cpp.
 {
     const bool has_sound_thresh = sound_threshold.first > 0 && sound_threshold.second > 0;
     return !is_null() && has_sound_thresh;
 }
References is_null(), and sound_threshold.
Referenced by finalize().
has_trigger_msg()
bool trap::has_trigger_msg () const inline
Definition at line 255 of file trap.h.
{
             return trigger_message_u && trigger_message_npc;
         }
References trigger_message_npc, and trigger_message_u.
Referenced by map::maybe_trigger_prox_trap(), and map::maybe_trigger_trap().
is_always_invisible()
bool trap::is_always_invisible () const inline
There are special always invisible traps.
See player::search_surroundings
Definition at line 172 of file trap.h.
{
             return always_invisible;
         }
References always_invisible.
Referenced by can_see(), is_trivial_to_spot(), map::maybe_trigger_prox_trap(), and map::maybe_trigger_trap().
is_benign()
bool trap::is_benign () const inline
If true, this is not really a trap and there won't be any safety queries before stepping onto it (e.g.
for funnels).
Definition at line 221 of file trap.h.
{
             return benign;
         }
References benign.
Referenced by Character::adjacent_tile(), debug_describe(), game::get_dangerous_tile(), advanced_inv_area::init(), place_trap_actor::is_allowed(), monster::know_danger_at(), map::maybe_trigger_prox_trap(), map::maybe_trigger_trap(), map::route(), and map::update_pathfinding_cache().
is_funnel()
bool trap::is_funnel () const
Definition at line 376 of file trap.cpp.
 {
     return !is_null() && funnel_radius_mm > 0;
 }
References funnel_radius_mm, and is_null().
Referenced by map::fill_funnels(), finalize(), and retroactively_fill_from_funnel().
is_null()
bool trap::is_null () const
Whether this is the null-traps, aka no trap at all.
Definition at line 366 of file trap.cpp.
 {
     return loadid == tr_null;
 }
References loadid, and tr_null.
Referenced by Character::add_known_trap(), Character::base_comfort_value(), iuse::can_goo(), game::can_move_furniture(), can_see(), construct::check_empty(), construct::check_empty_lite(), construct::check_no_trap(), construct::check_support_below(), game::examine(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), Character::floor_bedding_warmth(), vehicle::handle_trap(), has_sound_trigger(), place_trap_actor::is_allowed(), is_funnel(), map::maybe_trigger_prox_trap(), map::maybe_trigger_trap(), MapExtras::mx_city_trap(), MapExtras::mx_minefield(), item::process_corpse(), Character::search_surroundings(), trigger(), triggered_by_item(), triggered_by_sound(), and editmap::update_view_with_help().
is_trivial_to_spot()
bool trap::is_trivial_to_spot () const
Definition at line 245 of file trap.cpp.
 {
     // @TODO technically the trap may not be detected even with visibility == 0, see trap::detect_trap
     return visibility <= 0 && !is_always_invisible();
 }
References is_always_invisible(), and visibility.
Referenced by Character::search_surroundings().
load()
void trap::load (const JsonObject & jo, std::string_view src)
Loads this specific trap.
Definition at line 137 of file trap.cpp.
 {
     mandatory( jo, was_loaded, "id", id );
     mandatory( jo, was_loaded, "name", name_ );
     if( !assign( jo, "color", color ) ) {
         jo.throw_error( "missing mandatory member \"color\"" );
     }
     mandatory( jo, was_loaded, "symbol", sym, one_char_symbol_reader );
     mandatory( jo, was_loaded, "visibility", visibility );
     mandatory( jo, was_loaded, "avoidance", avoidance );
     mandatory( jo, was_loaded, "difficulty", difficulty );
     optional( jo, was_loaded, "memorial_male", memorial_male );
     optional( jo, was_loaded, "memorial_female", memorial_female );
     optional( jo, was_loaded, "trigger_message_u", trigger_message_u );
     optional( jo, was_loaded, "trigger_message_npc", trigger_message_npc );
     // Require either none, or both
     if( !!memorial_male != !!memorial_female ) {
         jo.throw_error_at(
             id.str(),
             "Only one gender of memorial message specified for trap " + id.str() + ", but none "
             "or both required." );
     }
     optional( jo, was_loaded, "flags", _flags );
     optional( jo, was_loaded, "trap_radius", trap_radius, 0 );
     // TODO: Is there a generic_factory version of this?
     act = trap_function_from_string( jo.get_string( "action" ) );
     optional( jo, was_loaded, "map_regen", map_regen, update_mapgen_none );
     optional( jo, was_loaded, "benign", benign, false );
     optional( jo, was_loaded, "always_invisible", always_invisible, false );
     optional( jo, was_loaded, "funnel_radius", funnel_radius_mm, 0 );
     optional( jo, was_loaded, "comfort", comfort, 0 );
     int legacy_floor_bedding_warmth = units::to_legacy_bodypart_temp_delta( floor_bedding_warmth );
     optional( jo, was_loaded, "floor_bedding_warmth", legacy_floor_bedding_warmth, 0 );
     floor_bedding_warmth = units::from_legacy_bodypart_temp_delta( legacy_floor_bedding_warmth );
     optional( jo, was_loaded, "spell_data", spell_data );
     assign( jo, "trigger_weight", trigger_weight );
     optional( jo, was_loaded, "sound_threshold", sound_threshold );
     for( const JsonValue entry : jo.get_array( "drops" ) ) {
         itype_id item_type;
         int quantity = 0;
         int charges = 0;
         if( entry.test_object() ) {
             JsonObject jc = entry.get_object();
             jc.read( "item", item_type, true );
             quantity = jc.get_int( "quantity", 1 );
             charges = jc.get_int( "charges", 1 );
         } else {
             entry.read( item_type, true );
             quantity = 1;
             charges = 1;
         }
         if( !item_type.is_empty() && quantity > 0 && charges > 0 ) {
             components.emplace_back( item_type, quantity, charges );
         }
     }
     if( jo.has_object( "vehicle_data" ) ) {
         JsonObject jv = jo.get_object( "vehicle_data" );
         vehicle_data.remove_trap = jv.get_bool( "remove_trap", false );
         vehicle_data.do_explosion = jv.get_bool( "do_explosion", false );
         vehicle_data.is_falling = jv.get_bool( "is_falling", false );
         vehicle_data.chance = jv.get_int( "chance", 100 );
         vehicle_data.damage = jv.get_int( "damage", 0 );
         vehicle_data.shrapnel = jv.get_int( "shrapnel", 0 );
         vehicle_data.sound_volume = jv.get_int( "sound_volume", 0 );
         jv.read( "sound", vehicle_data.sound );
         vehicle_data.sound_type = jv.get_string( "sound_type", "" );
         vehicle_data.sound_variant = jv.get_string( "sound_variant", "" );
         vehicle_data.spawn_items.clear();
         if( jv.has_array( "spawn_items" ) ) {
             for( const JsonValue entry : jv.get_array( "spawn_items" ) ) {
                 if( entry.test_object() ) {
                     JsonObject joitm = entry.get_object();
                     vehicle_data.spawn_items.emplace_back(
                         itype_id( joitm.get_string( "id" ) ), joitm.get_float( "chance" ) );
                 } else {
                     vehicle_data.spawn_items.emplace_back( itype_id( entry.get_string() ), 1.0 );
                 }
             }
         }
         vehicle_data.set_trap = trap_str_id::NULL_ID();
         if( jv.read( "set_trap", vehicle_data.set_trap ) ) {
             vehicle_data.remove_trap = false;
         }
     }
 }
References _flags, act, always_invisible, assign(), avoidance, benign, vehicle_handle_trap_data::chance, color, comfort, components, vehicle_handle_trap_data::damage, difficulty, vehicle_handle_trap_data::do_explosion, floor_bedding_warmth, units::from_legacy_bodypart_temp_delta(), funnel_radius_mm, JsonObject::get_array(), JsonObject::get_bool(), JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_object(), string_id< T >::is_empty(), vehicle_handle_trap_data::is_falling, itype_id, mandatory, map_regen, memorial_female, memorial_male, name_, string_id< trap >::NULL_ID(), one_char_symbol_reader(), optional(), JsonObject::read(), vehicle_handle_trap_data::remove_trap, vehicle_handle_trap_data::set_trap, vehicle_handle_trap_data::shrapnel, vehicle_handle_trap_data::sound, sound_threshold, vehicle_handle_trap_data::sound_type, vehicle_handle_trap_data::sound_variant, vehicle_handle_trap_data::sound_volume, vehicle_handle_trap_data::spawn_items, spell_data, sym, JsonObject::throw_error(), JsonObject::throw_error_at(), units::to_legacy_bodypart_temp_delta(), trap_function_from_string(), trap_radius, trigger_message_npc, trigger_message_u, trigger_weight, update_mapgen_none, vehicle_data, visibility, and was_loaded.
load_trap()
void trap::load_trap (const JsonObject & jo, const std::string & src) static
Loads the trap and adds it to the trapmap, and the traplist.
Exceptions
JsonError if the json is invalid as usual.
Definition at line 132 of file trap.cpp.
 {
     trap_factory.load( jo, src );
 }
References src, and anonymous_namespace{trap.cpp}::trap_factory.
Referenced by DynamicDataLoader::initialize().
map_regen_target()
update_mapgen_id trap::map_regen_target () const
Definition at line 233 of file trap.cpp.
 {
     return map_regen;
 }
References map_regen.
Referenced by trapfunc::map_regen().
memorial_msg()
std::string trap::memorial_msg (bool male) const inline
Definition at line 191 of file trap.h.
{
             if( male ) {
                 return memorial_male->translated();
             }
             return memorial_female->translated();
         }
References male, memorial_female, and memorial_male.
Referenced by memorial_logger::notify().
name()
std::string trap::name () const
Definition at line 228 of file trap.cpp.
 {
     return name_.translated();
 }
References name_, and translation::translated().
Referenced by colorized_trap_name_at(), detect_trap(), Character::echo_pulse(), examine(), game::get_dangerous_tile(), vehicle::handle_trap(), place_trap_actor::is_allowed(), map::maybe_trigger_prox_trap(), map::maybe_trigger_trap(), game::print_trap_info(), Character::search_surroundings(), and editmap::update_view_with_help().
on_disarmed()
void trap::on_disarmed (map & m, const tripoint & p) const
Called when a trap at the given point in the map has been disarmed.
It should spawn trap items (if any) and remove the trap from the map via map::remove_trap.
Definition at line 406 of file trap.cpp.
 {
     for( const auto &i : components ) {
         const itype_id &item_type = std::get<0>( i );
         const int quantity = std::get<1>( i );
         const int charges = std::get<2>( i );
         m.spawn_item( p.xy(), item_type, quantity, charges );
     }
     for( const tripoint &dest : m.points_in_radius( p, trap_radius ) ) {
         m.remove_trap( dest );
     }
 }
References components, map::points_in_radius(), map::remove_trap(), map::spawn_item(), trap_radius, and tripoint::xy().
Referenced by jmapgen_terrain::apply(), and examine().
operator!=()
bool trap::operator!= (const trap_id & id) const inline
Definition at line 179 of file trap.h.
{
             return loadid != id;
         }
References id, and loadid.
operator==()
bool trap::operator== (const trap_id & id) const inline
Definition at line 176 of file trap.h.
{
             return loadid == id;
         }
References id, and loadid.
reset()
void trap::reset () static
Releases the loaded trap objects in trapmap and traplist.
Definition at line 238 of file trap.cpp.
 {
     funnel_traps.clear();
     sound_triggered_traps.clear();
     trap_factory.reset();
 }
References funnel_traps, sound_triggered_traps, and anonymous_namespace{trap.cpp}::trap_factory.
Referenced by DynamicDataLoader::unload_data().
trigger() [1/4]
void trap::trigger (const tripoint & pos) const
Definition at line 332 of file trap.cpp.
 {
     if( is_null() ) {
         return;
     }
     act( pos, nullptr, nullptr );
 }
References act, is_null(), and math_opers::pos().
trigger() [2/4]
void trap::trigger (const tripoint & pos, Creature & creature) const
This applies the effects of the trap to the world and possibly to the triggering object (creature, item).
The function assumes the caller has already checked whether the trap should be activated (e.g. the creature has had a chance to avoid the trap, but it failed).
Definition at line 340 of file trap.cpp.
 {
     return trigger( pos, &creature, nullptr );
 }
References creature, math_opers::pos(), and trigger().
trigger() [3/4]
void trap::trigger (const tripoint & pos, Creature * creature, item * item) const private
Trigger trap effects.
Parameters
creature The creature that triggered the trap, it does not necessarily have to be on the place of the trap (traps can be triggered from adjacent, e.g. when disarming them). This can also be a null pointer if the trap has been triggered by some thrown item (which must have the trigger_weight).
pos The location of the trap in the main map.
item The item that triggered the trap
Definition at line 350 of file trap.cpp.
 {
     if( is_null() ) {
         return;
     }
     const bool is_real_creature = creature != nullptr && !creature->is_hallucination();
     if( is_real_creature || item != nullptr ) {
         bool triggered = act( pos, creature, item );
         if( triggered && is_real_creature ) {
             if( Character *ch = creature->as_character() ) {
                 get_event_bus().send<event_type::character_triggers_trap>( ch->getID(), id );
             }
         }
     }
 }
References act, character_triggers_trap, creature, get_event_bus(), id, is_null(), math_opers::pos(), and event_bus::send().
Referenced by drop_or_embed_projectile(), examine(), Character::gravity_check(), place_trap_actor::is_allowed(), map::maybe_trigger_prox_trap(), map::maybe_trigger_trap(), sounds::process_sounds(), and trigger().
trigger() [4/4]
void trap::trigger (const tripoint & pos, item & item) const
Definition at line 345 of file trap.cpp.
 {
     return trigger( pos, nullptr, &item );
 }
References math_opers::pos(), and trigger().
triggered_by_item()
bool trap::triggered_by_item (const item & itm) const
If the given item is throw onto the trap, does it trigger the trap?
Definition at line 371 of file trap.cpp.
 {
     return !is_null() && itm.weight() >= trigger_weight;
 }
References is_null(), trigger_weight, and item::weight().
Referenced by drop_or_embed_projectile().
triggered_by_sound()
bool trap::triggered_by_sound (int vol, int dist) const
Definition at line 387 of file trap.cpp.
 {
     const int volume = vol - dist;
     // now determine sound threshold probabilities
     // linear model: 0% below sound_min, 25% at sound_min, 100% at sound_max
     const int sound_min = sound_threshold.first;
     const int sound_max = sound_threshold.second;
     const int sound_range = sound_max - sound_min;
     if( volume < sound_min ) {
         return false;
     }
     int sound_chance = 100;
     if( sound_range > 0 ) {
         sound_chance = 25 + ( 75 * ( volume - sound_min ) / sound_range );
     }
     //debugmsg("Sound chance: %d%%", sound_chance);
     return !is_null() && ( rng( 0, 100 ) <= sound_chance );
 }
References is_null(), rng(), and sound_threshold.
Referenced by sounds::process_sounds().
Member Data Documentation
_flags
cata::flat_set<flag_id> trap::_flags private
Definition at line 149 of file trap.h.
Referenced by has_flag(), and load().
act
trap_function trap::act private
Definition at line 140 of file trap.h.
Referenced by load(), and trigger().
always_invisible
bool trap::always_invisible = false private
Definition at line 138 of file trap.h.
Referenced by is_always_invisible(), and load().
avoidance
int trap::avoidance = 0 private
Definition at line 128 of file trap.h.
Referenced by debug_describe(), easy_take_down(), get_avoidance(), and load().
benign
bool trap::benign = false private
Definition at line 137 of file trap.h.
Referenced by is_benign(), and load().
color
nc_color trap::color
Definition at line 117 of file trap.h.
Referenced by color(), colorized_trap_name_at(), map::draw_maptile(), load(), game::print_trap_info(), and editmap::update_view_with_help().
comfort
int trap::comfort = 0
Definition at line 165 of file trap.h.
Referenced by Character::base_comfort_value(), load(), and avatar::try_to_sleep().
components
std::vector<std::tuple<itype_id, int, int> > trap::components private
Definition at line 161 of file trap.h.
Referenced by load(), and on_disarmed().
difficulty
int trap::difficulty = 0 private
Definition at line 134 of file trap.h.
Referenced by can_not_be_disarmed(), debug_describe(), easy_take_down(), examine(), and load().
floor_bedding_warmth
units::temperature_delta trap::floor_bedding_warmth = 0_C_delta
Definition at line 166 of file trap.h.
Referenced by Character::floor_bedding_warmth(), and load().
funnel_radius_mm
int trap::funnel_radius_mm = 0 private
Definition at line 159 of file trap.h.
Referenced by funnel_turns_per_charge(), is_funnel(), and load().
id
trap_str_id trap::id
Definition at line 110 of file trap.h.
Referenced by Character::add_known_trap(), jmapgen_terrain::apply(), monster::avoid_trap(), construct::check_support_below(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), finalize(), operator!=(), operator==(), tutorial_game::per_turn(), firestarter_actor::prep_firestarter_use(), and trigger().
loadid
trap_id trap::loadid
Definition at line 112 of file trap.h.
Referenced by apply< trap >(), trapfunc::cast_spell(), editmap::draw_main_ui_overlay(), feature< trap_id >(), fill_funnels(), finalize(), is_null(), operator!=(), operator==(), item::process_corpse(), and editmap::update_view_with_help().
map_regen
update_mapgen_id trap::map_regen private
Definition at line 139 of file trap.h.
Referenced by load(), and map_regen_target().
memorial_female
std::optional<translation> trap::memorial_female private
Definition at line 144 of file trap.h.
Referenced by has_memorial_msg(), load(), and memorial_msg().
memorial_male
std::optional<translation> trap::memorial_male private
Definition at line 143 of file trap.h.
Referenced by has_memorial_msg(), load(), and memorial_msg().
name_
translation trap::name_ private
Definition at line 141 of file trap.h.
Referenced by load(), and name().
sound_threshold
std::pair<int, int> trap::sound_threshold = {0, 0} private
Determines how much sound is needed to trigger the trap.
Defined as {min,max}.
Definition at line 158 of file trap.h.
Referenced by has_sound_trigger(), load(), and triggered_by_sound().
spell_data
fake_spell trap::spell_data
Definition at line 164 of file trap.h.
Referenced by trapfunc::cast_spell(), and load().
src
std::vector<std::pair<trap_str_id, mod_id> > trap::src
Definition at line 111 of file trap.h.
Referenced by load_trap().
sym
int trap::sym = 0
Definition at line 116 of file trap.h.
Referenced by map::draw_maptile(), load(), and symbol().
trap_radius
int trap::trap_radius = 0 private
Definition at line 136 of file trap.h.
Referenced by get_trap_radius(), load(), and on_disarmed().
trigger_message_npc
std::optional<translation> trap::trigger_message_npc private
Definition at line 147 of file trap.h.
Referenced by get_trigger_message_npc(), has_trigger_msg(), and load().
trigger_message_u
std::optional<translation> trap::trigger_message_u private
Definition at line 146 of file trap.h.
Referenced by get_trigger_message_u(), has_trigger_msg(), and load().
trigger_weight
units::mass trap::trigger_weight = 500_gram private
If an item with this weight or more is thrown onto the trap, it triggers.
Definition at line 154 of file trap.h.
Referenced by load(), and triggered_by_item().
vehicle_data
vehicle_handle_trap_data trap::vehicle_data
Definition at line 167 of file trap.h.
Referenced by vehicle::handle_trap(), and load().
visibility
int trap::visibility = 1 private
How easy it is to spot the trap.
Smaller values means it's easier to spot. 1 to ??, affects detection
Definition at line 126 of file trap.h.
Referenced by can_see(), debug_describe(), detect_trap(), is_trivial_to_spot(), and load().
was_loaded
bool trap::was_loaded = false
Definition at line 114 of file trap.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/trap.h
src/iexamine.cpp
src/trap.cpp
src/weather.cpp