Cataclysm DDA: event_transformation_impl::updatable_value_constraint Struct Reference
event_transformation_impl::updatable_value_constraint Struct Reference
Public Member Functions
updatable_value_constraint (const std::pair< std::string, value_constraint > &p, state *st, stats_tracker &stats)
const std::string & field_name () const
void new_value (const cata_variant &new_val, stats_tracker &stats) override
bool permits (const cata_variant &v) const
Public Member Functions inherited from base_watcher
base_watcher ()=default
base_watcher (const base_watcher &)=delete
base_watcher & operator= (const base_watcher &)=delete
Public Attributes
std::optional< cata_variant > cached_value_
const value_constraint * parent_constraint_
state * parent_state_
std::string field_name_
Additional Inherited Members
Protected Member Functions inherited from base_watcher
virtual ~base_watcher ()
Detailed Description
Definition at line 498 of file event_statistics.cpp.
Constructor & Destructor Documentation
updatable_value_constraint()
event_transformation_impl::updatable_value_constraint::updatable_value_constraint (const std::pair< std::string, value_constraint > & p, state * st, stats_tracker & stats) inline
Definition at line 499 of file event_statistics.cpp.
             : parent_constraint_( &p.second )
             , parent_state_( st )
             , field_name_( p.first ) {
             const value_constraint &val = p.second;
             if( val.equals_statistic_ ) {
                 cached_value_ = stats.value_of( *val.equals_statistic_ );
                 stats.add_watcher( *val.equals_statistic_, this );
             }
         }
References cached_value_, and value_constraint::equals_statistic_.
Member Function Documentation
field_name()
const std::string& event_transformation_impl::updatable_value_constraint::field_name () const inline
Definition at line 514 of file event_statistics.cpp.
{
             return field_name_;
         }
References field_name_.
new_value()
void event_transformation_impl::updatable_value_constraint::new_value (const cata_variant & new_val, stats_tracker & stats) inline override virtual
Implements stat_watcher.
Definition at line 518 of file event_statistics.cpp.
{
             cached_value_ = new_val;
             parent_state_->value_constraint_changed( stats );
         }
References cached_value_, parent_state_, and event_transformation_impl::state::value_constraint_changed().
permits()
bool event_transformation_impl::updatable_value_constraint::permits (const cata_variant & v) const inline
Definition at line 523 of file event_statistics.cpp.
{
             const value_constraint &p = *parent_constraint_;
             if( std::find( p.equals_any_.begin(), p.equals_any_.end(), v ) != p.equals_any_.end() ) {
                 return true;
             }
             // NOLINTNEXTLINE(readability-simplify-boolean-expr)
             if( cached_value_ ) {
                 return *cached_value_ == v;
             }
             if( p.val_comp_ ) {
                 const int v_int = v.get<int>();
                 const int c_int = p.val_comp_->second.get<int>();
                 using comparator = value_constraint::comparator;
                 switch( p.val_comp_->first ) {
                     case comparator::lt:
                         return v_int < c_int;
                     case comparator::lteq:
                         return v_int <= c_int;
                     case comparator::gteq:
                         return v_int >= c_int;
                     case comparator::gt:
                         return v_int > c_int;
                 }
             }
             return false;
         }
References cached_value_, value_constraint::equals_any_, cata_variant::get(), math_opers::gt(), math_opers::lt(), parent_constraint_, and value_constraint::val_comp_.
Member Data Documentation
cached_value_
std::optional<cata_variant> event_transformation_impl::updatable_value_constraint::cached_value_
Definition at line 550 of file event_statistics.cpp.
Referenced by new_value(), permits(), and updatable_value_constraint().
field_name_
std::string event_transformation_impl::updatable_value_constraint::field_name_
Definition at line 553 of file event_statistics.cpp.
Referenced by field_name().
parent_constraint_
const value_constraint* event_transformation_impl::updatable_value_constraint::parent_constraint_
Definition at line 551 of file event_statistics.cpp.
Referenced by permits().
parent_state_
state* event_transformation_impl::updatable_value_constraint::parent_state_
Definition at line 552 of file event_statistics.cpp.
Referenced by new_value().
The documentation for this struct was generated from the following file:
src/event_statistics.cpp