Cataclysm DDA: conditional_t Struct Reference
conditional_t Struct Reference
A condition for a response spoken by the player.
#include <condition.h>
Public Types
using func = std::function< bool(dialogue &)>
Public Member Functions
conditional_t ()=default
conditional_t (std::string_view type)
conditional_t (const JsonObject &jo)
bool operator() (dialogue &d) const
Static Public Member Functions
static std::function< std::string(const dialogue &)> get_get_string (const JsonObject &jo)
static std::function< translation(const dialogue &)> get_get_translation (const JsonObject &jo)
static std::function< double(dialogue &)> get_get_dbl (std::string_view checked_value, char scope)
static std::function< void(dialogue &, double)> get_set_dbl (std::string_view checked_value, char scope)
Private Attributes
func condition
Detailed Description
A condition for a response spoken by the player.
This struct only adds the constructors which will load the data from json into a lambda, stored in the std::function object. Invoking the function operator with a dialog reference (so the function can access the NPC) returns whether the response is allowed.
Definition at line 86 of file condition.h.
Member Typedef Documentation
func
using conditional_t::func = std::function<bool(dialogue &)>
Definition at line 88 of file condition.h.
Constructor & Destructor Documentation
conditional_t() [1/3]
conditional_t::conditional_t () default
Referenced by conditional_t().
conditional_t() [2/3]
conditional_t::conditional_t (std::string_view type) explicit
Definition at line 2601 of file condition.cpp.
 {
     bool found = false;
     for( const condition_parser &p : parsers_simple ) {
         if( p.has_beta ) {
             if( type == p.key_alpha ) {
                 condition = p.f_beta_simple( false );
                 found = true;
             } else if( type == p.key_beta ) {
                 condition = p.f_beta_simple( true );
                 found = true;
             }
         } else if( type == p.key_alpha ) {
             condition = p.f_simple();
             found = true;
         }
         if( found ) {
             break;
         }
     }
     if( !found ) {
         condition = []( dialogue const & ) {
             return false;
         };
     }
 }
References condition, parsers_simple, and type.
conditional_t() [3/3]
conditional_t::conditional_t (const JsonObject & jo) explicit
Definition at line 2507 of file condition.cpp.
 {
     // improve the clarity of NPC setter functions
     bool found_sub_member = false;
     const auto parse_array = []( const JsonObject & jo, const std::string_view type ) {
         std::vector<conditional_t> conditionals;
         for( const JsonValue entry : jo.get_array( type ) ) {
             if( entry.test_string() ) {
                 conditional_t type_condition( entry.get_string() );
                 conditionals.emplace_back( type_condition );
             } else {
                 JsonObject cond = entry.get_object();
                 conditional_t type_condition( cond );
                 conditionals.emplace_back( type_condition );
             }
         }
         return conditionals;
     };
     if( jo.has_array( "and" ) ) {
         std::vector<conditional_t> and_conditionals = parse_array( jo, "and" );
         found_sub_member = true;
         condition = [acs = std::move( and_conditionals )]( dialogue & d ) {
             return std::all_of( acs.begin(), acs.end(), [&d]( conditional_t const & cond ) {
                 return cond( d );
             } );
         };
     } else if( jo.has_array( "or" ) ) {
         std::vector<conditional_t> or_conditionals = parse_array( jo, "or" );
         found_sub_member = true;
         condition = [ocs = std::move( or_conditionals )]( dialogue & d ) {
             return std::any_of( ocs.begin(), ocs.end(), [&d]( conditional_t const & cond ) {
                 return cond( d );
             } );
         };
     } else if( jo.has_object( "not" ) ) {
         JsonObject cond = jo.get_object( "not" );
         const conditional_t sub_condition = conditional_t( cond );
         found_sub_member = true;
         condition = [sub_condition]( dialogue & d ) {
             return !sub_condition( d );
         };
     } else if( jo.has_string( "not" ) ) {
         const conditional_t sub_condition = conditional_t( jo.get_string( "not" ) );
         found_sub_member = true;
         condition = [sub_condition]( dialogue & d ) {
             return !sub_condition( d );
         };
     }
     if( !found_sub_member ) {
         for( const std::string &sub_member : dialogue_data::complex_conds() ) {
             if( jo.has_member( sub_member ) ) {
                 found_sub_member = true;
                 break;
             }
         }
     }
     bool found = false;
     for( const condition_parser &p : parsers ) {
         if( p.has_beta ) {
             if( p.check( jo ) ) {
                 condition = p.f_beta( jo, p.key_alpha, false );
                 found = true;
             } else if( p.check( jo, true ) ) {
                 condition = p.f_beta( jo, p.key_beta, true );
                 found = true;
             }
         } else if( p.check( jo ) ) {
             condition = p.f( jo, p.key_alpha );
             if( jo.has_member( "math" ) ) {
                 found_sub_member = true;
             }
             found = true;
         }
         if( found ) {
             break;
         }
     }
     if( !found ) {
         for( const std::string &sub_member : dialogue_data::simple_string_conds() ) {
             if( jo.has_string( sub_member ) ) {
                 const conditional_t sub_condition( jo.get_string( sub_member ) );
                 condition = [sub_condition]( dialogue & d ) {
                     return sub_condition( d );
                 };
                 found_sub_member = true;
                 break;
             }
         }
     }
     if( !found_sub_member ) {
         jo.throw_error( "unrecognized condition in " + jo.str() );
     }
 }
References dialogue_data::complex_conds(), condition, conditional_t(), func::f, JsonObject::get_array(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), parsers, dialogue_data::simple_string_conds(), JsonObject::str(), JsonObject::throw_error(), and type.
Member Function Documentation
get_get_dbl()
std::function< double(dialogue &)> conditional_t::get_get_dbl (std::string_view checked_value, char scope) static
Definition at line 2088 of file condition.cpp.
 {
     const bool is_npc = scope == 'n';
     if( auto iter = f_get_vals.find( checked_value ); iter != f_get_vals.end() ) {
         return [is_npc, func = iter->second ]( dialogue & d ) {
             return ( d.actor( is_npc )->*func )();
         };
     } else if( checked_value == "allies" ) {
         if( is_npc ) {
             throw std::invalid_argument( "Can't get allies count for NPCs" );
         }
         return []( dialogue const & ) {
             return static_cast<double>( g->allies().size() );
         };
     } else if( checked_value == "dodge" ) {
         return [is_npc]( dialogue const & d ) {
             return static_cast<talker const *>( d.actor( is_npc ) )->get_character()->get_dodge();
         };
     } else if( checked_value == "power_percentage" ) {
         return [is_npc]( dialogue const & d ) {
             // Energy in milijoule
             units::energy::value_type power_max = d.actor( is_npc )->power_max().value();
             if( power_max == 0 ) {
                 return 0.0; //Default value if character does not have power, avoids division with 0.
             }
             return static_cast<double>( d.actor( is_npc )->power_cur().value() * 100.0L / power_max );
         };
     } else if( checked_value == "mana_percentage" ) {
         return [is_npc]( dialogue const & d ) {
             int mana_max = d.actor( is_npc )->mana_max();
             if( mana_max == 0 ) {
                 return 0.0; //Default value if character does not have mana, avoids division with 0.
             }
             return d.actor( is_npc )->mana_cur() * 100.0 / mana_max;
         };
     } else if( checked_value == "body_temp" ) {
         return [is_npc]( dialogue const & d ) {
             return units::to_legacy_bodypart_temp( d.actor( is_npc )->get_body_temp() );
         };
     } else if( checked_value == "body_temp_delta" ) {
         return [is_npc]( dialogue const & d ) {
             return units::to_legacy_bodypart_temp_delta( d.actor( is_npc )->get_body_temp_delta() );
         };
     } else if( checked_value == "power" ) {
         return [is_npc]( dialogue const & d ) {
             // Energy in milijoule
             return static_cast<double>( d.actor( is_npc )->power_cur().value() );
         };
     } else if( checked_value == "power_max" ) {
         return [is_npc]( dialogue const & d ) {
             // Energy in milijoule
             return static_cast<double>( d.actor( is_npc )->power_max().value() );
         };
     }
     throw std::invalid_argument( string_format( R"(Invalid aspect "%s" for val())", checked_value ) );
 }
References anonymous_namespace{condition.cpp}::f_get_vals, g, units::power_max, string_format(), units::to_legacy_bodypart_temp(), units::to_legacy_bodypart_temp_delta(), and units::quantity< V, U >::value().
Referenced by anonymous_namespace{math_parser_diag.cpp}::u_val().
get_get_string()
std::function< std::string(const dialogue &)> conditional_t::get_get_string (const JsonObject & jo) static
Definition at line 2011 of file condition.cpp.
 {
     auto ret_func = get_get_str_<std::string>( jo, []( const std::string & s ) {
         return s;
     } );
     if( !ret_func ) {
         ret_func = get_get_translation_<std::string>( jo, []( const translation & t ) {
             return t.translated();
         } );
         if( !ret_func ) {
             jo.throw_error( "unrecognized string mutator in " + jo.str() );
             return []( const dialogue & ) {
                 return "INVALID";
             };
         }
     }
     return ret_func;
 }
References JsonObject::str(), JsonObject::throw_error(), and translation::translated().
Referenced by get_str_or_var().
get_get_translation()
std::function< translation(const dialogue &)> conditional_t::get_get_translation (const JsonObject & jo) static
Definition at line 1989 of file condition.cpp.
 {
     auto ret_func = get_get_str_<translation>( jo, []( const std::string & s ) {
         return no_translation( s );
     } );
     if( !ret_func ) {
         ret_func = get_get_translation_<translation>( jo, []( const translation & t ) {
             return t;
         } );
         if( !ret_func ) {
             jo.throw_error( "unrecognized string mutator in " + jo.str() );
             return []( const dialogue & ) {
                 return translation();
             };
         }
     }
     return ret_func;
 }
References no_translation(), JsonObject::str(), and JsonObject::throw_error().
Referenced by get_translation_or_var().
get_set_dbl()
std::function< void(dialogue &, double)> conditional_t::get_set_dbl (std::string_view checked_value, char scope) static
Definition at line 2183 of file condition.cpp.
 {
     const bool is_npc = scope == 'n';
     if( auto iter = f_set_vals.find( checked_value ); iter != f_set_vals.end() ) {
         return [is_npc, func = iter->second ]( dialogue & d, double input ) {
             ( d.actor( is_npc )->*func )( input );
         };
     } else if( checked_value == "owed" ) {
         return [is_npc]( dialogue & d, double input ) {
             d.actor( is_npc )->add_debt( input - d.actor( is_npc )->debt() );
         };
     } else if( checked_value == "sold" ) {
         return [is_npc]( dialogue & d, double input ) {
             d.actor( is_npc )->add_sold( input - d.actor( is_npc )->sold() );
         };
     } else if( checked_value == "pos_x" ) {
         return [is_npc]( dialogue & d, double input ) {
             tripoint const tr = d.actor( is_npc )->pos();
             d.actor( is_npc )->set_pos( tripoint( input, tr.y, tr.z ) );
         };
     } else if( checked_value == "pos_y" ) {
         return [is_npc]( dialogue & d, double input ) {
             tripoint const tr = d.actor( is_npc )->pos();
             d.actor( is_npc )->set_pos( tripoint( tr.x, input, tr.z ) );
         };
     } else if( checked_value == "pos_z" ) {
         return [is_npc]( dialogue & d, double input ) {
             tripoint const tr = d.actor( is_npc )->pos();
             d.actor( is_npc )->set_pos( tripoint( tr.xy(), input ) );
         };
     } else if( checked_value == "power" ) {
         return [is_npc]( dialogue & d, double input ) {
             // Energy in milijoule
             d.actor( is_npc )->set_power_cur( 1_mJ * input );
         };
     } else if( checked_value == "power_percentage" ) {
         return [is_npc]( dialogue & d, double input ) {
             // Energy in milijoule
             d.actor( is_npc )->set_power_cur( ( d.actor( is_npc )->power_max() * input ) / 100 );
         };
     } else if( checked_value == "focus" ) {
         return [is_npc]( dialogue & d, double input ) {
             d.actor( is_npc )->mod_focus( input - d.actor( is_npc )->focus_cur() );
         };
     } else if( checked_value == "mana_percentage" ) {
         return [is_npc]( dialogue & d, double input ) {
             d.actor( is_npc )->set_mana_cur( ( d.actor( is_npc )->mana_max() * input ) / 100 );
         };
     }
     throw std::invalid_argument( string_format( R"(Invalid aspect "%s" for val())", checked_value ) );
 }
References dialogue::actor(), talker::add_debt(), talker::add_sold(), talker::debt(), anonymous_namespace{condition.cpp}::f_set_vals, talker::focus_cur(), talker::mana_max(), talker::mod_focus(), talker::pos(), talker::power_max(), talker::set_mana_cur(), talker::set_pos(), talker::set_power_cur(), talker::sold(), string_format(), tripoint, tripoint::x, tripoint::xy(), tripoint::y, and tripoint::z.
Referenced by anonymous_namespace{math_parser_diag.cpp}::u_val_ass().
operator()()
bool conditional_t::operator() (dialogue & d) const inline
Definition at line 100 of file condition.h.
{
             if( !condition ) {
                 return false;
             }
             return condition( d );
         }
References condition.
Member Data Documentation
condition
func conditional_t::condition private
Definition at line 108 of file condition.h.
Referenced by conditional_t(), and operator()().
The documentation for this struct was generated from the following files:
src/condition.h
src/condition.cpp