Cataclysm DDA: overmap_static_spawns Struct Reference
overmap_static_spawns Struct Reference
#include <omdata.h>
Public Member Functions
bool operator== (const overmap_static_spawns &rhs) const
void deserialize (const JsonValue &jsin)
Public Member Functions inherited from overmap_spawns
overmap_spawns ()
bool operator== (const overmap_spawns &rhs) const
Public Attributes
int chance = 0
Public Attributes inherited from overmap_spawns
string_id< MonsterGroup > group
numeric_interval< int > population
Additional Inherited Members
Protected Member Functions inherited from overmap_spawns
void load (const JsonObject &jo)
Detailed Description
Definition at line 157 of file omdata.h.
Member Function Documentation
deserialize()
void overmap_static_spawns::deserialize (const JsonValue & jsin) inline
Definition at line 164 of file omdata.h.
{
         JsonObject jo = jsin.get_object();
         overmap_spawns::load( jo );
         jo.read( "chance", chance );
     }
References chance, JsonValue::get_object(), overmap_spawns::load(), and JsonObject::read().
operator==()
bool overmap_static_spawns::operator== (const overmap_static_spawns & rhs) const inline
Definition at line 160 of file omdata.h.
{
         return overmap_spawns::operator==( rhs ) && chance == rhs.chance;
     }
References chance, and overmap_spawns::operator==().
Member Data Documentation
chance
int overmap_static_spawns::chance = 0
Definition at line 158 of file omdata.h.
Referenced by deserialize(), map::generate(), and operator==().
The documentation for this struct was generated from the following file:
src/omdata.h