Cataclysm DDA: mutable_overmap_terrain_join Struct Reference
mutable_overmap_terrain_join Struct Reference
Public Member Functions
void finalize (const std::string &context, const std::unordered_map< std::string, mutable_overmap_join * > &joins)
void deserialize (const JsonValue &jin)
Public Attributes
std::string join_id
const mutable_overmap_join * join = nullptr
cata::flat_set< std::string > alternative_join_ids
cata::flat_set< const mutable_overmap_join * > alternative_joins
join_type type = join_type::mandatory
Detailed Description
Definition at line 1521 of file overmap.cpp.
Member Function Documentation
deserialize()
void mutable_overmap_terrain_join::deserialize (const JsonValue & jin) inline
Definition at line 1546 of file overmap.cpp.
{
         if( jin.test_string() ) {
             jin.read( join_id, true );
         } else if( jin.test_object() ) {
             JsonObject jo = jin.get_object();
             jo.read( "id", join_id, true );
             jo.read( "type", type, true );
             jo.read( "alternatives", alternative_join_ids, true );
         } else {
             jin.throw_error( "Expected string or object" );
         }
     }
References alternative_join_ids, JsonValue::get_object(), join_id, JsonValue::read(), JsonObject::read(), JsonValue::test_object(), JsonValue::test_string(), JsonValue::throw_error(), and type.
finalize()
void mutable_overmap_terrain_join::finalize (const std::string & context, const std::unordered_map< std::string, mutable_overmap_join * > & joins) inline
Definition at line 1528 of file overmap.cpp.
{
         auto join_it = joins.find( join_id );
         if( join_it != joins.end() ) {
             join = join_it->second;
         } else {
             debugmsg( "invalid join id %s in %s", join_id, context );
         }
         for( const std::string &alt_join_id : alternative_join_ids ) {
             auto alt_join_it = joins.find( alt_join_id );
             if( alt_join_it != joins.end() ) {
                 alternative_joins.insert( alt_join_it->second );
             } else {
                 debugmsg( "invalid join id %s in %s", alt_join_id, context );
             }
         }
     }
References alternative_join_ids, alternative_joins, context, debugmsg, cata::flat_set< T, Compare, Data >::insert(), join, and join_id.
Referenced by mutable_overmap_terrain::finalize().
Member Data Documentation
alternative_join_ids
cata::flat_set<std::string> mutable_overmap_terrain_join::alternative_join_ids
Definition at line 1524 of file overmap.cpp.
Referenced by deserialize(), and finalize().
alternative_joins
cata::flat_set<const mutable_overmap_join *> mutable_overmap_terrain_join::alternative_joins
Definition at line 1525 of file overmap.cpp.
Referenced by joins_tracker::allows(), and finalize().
join
const mutable_overmap_join* mutable_overmap_terrain_join::join = nullptr
Definition at line 1523 of file overmap.cpp.
Referenced by joins_tracker::add_joins_for(), joins_tracker::allows(), mutable_overmap_phase_remainder::can_place(), finalize(), and mutable_overmap_placement_rule::finalize().
join_id
std::string mutable_overmap_terrain_join::join_id
Definition at line 1522 of file overmap.cpp.
Referenced by deserialize(), finalize(), and mutable_overmap_placement_rule::finalize().
type
join_type mutable_overmap_terrain_join::type = join_type::mandatory
Definition at line 1526 of file overmap.cpp.
Referenced by joins_tracker::add_joins_for(), joins_tracker::allows(), mutable_overmap_phase_remainder::can_place(), and deserialize().
The documentation for this struct was generated from the following file:
src/overmap.cpp