Cataclysm DDA: overmap_special_locations Struct Reference
overmap_special_locations Struct Reference
#include <omdata.h>
Public Member Functions
bool can_be_placed_on (const oter_id &oter) const
Returns whether this terrain of the special can be placed on the specified terrain.
void deserialize (const JsonArray &ja)
Public Attributes
tripoint p
cata::flat_set< string_id< overmap_location > > locations
Detailed Description
Definition at line 483 of file omdata.h.
Member Function Documentation
can_be_placed_on()
bool overmap_special_locations::can_be_placed_on (const oter_id & oter) const
Returns whether this terrain of the special can be placed on the specified terrain.
It's true if oter meets any of locations.
Definition at line 1086 of file overmap.cpp.
 {
     return is_amongst_locations( oter, locations );
 }
References is_amongst_locations(), and locations.
deserialize()
void overmap_special_locations::deserialize (const JsonArray & ja)
Definition at line 1091 of file overmap.cpp.
 {
     if( ja.size() != 2 ) {
         ja.throw_error( "expected array of size 2" );
     }
     ja.read( 0, p, true );
     ja.read( 1, locations, true );
 }
References locations, p, JsonArray::read(), JsonArray::size(), and JsonArray::throw_error().
Member Data Documentation
locations
cata::flat_set<string_id<overmap_location> > overmap_special_locations::locations
Definition at line 485 of file omdata.h.
Referenced by can_be_placed_on(), overmap_specials::create_building_from(), deserialize(), overmap_special_terrain::deserialize(), and overmap_special::load().
p
tripoint overmap_special_locations::p
Definition at line 484 of file omdata.h.
Referenced by deserialize(), overmap_special_terrain::deserialize(), and overmap_special::load().
The documentation for this struct was generated from the following files:
src/omdata.h
src/overmap.cpp