Cataclysm DDA: mapgen_value< Id >::switch_source Struct Reference
mapgen_value< Id >::switch_source Struct Reference
Public Member Functions
switch_source (const JsonObject &jo)
Id get (const mapgendata &dat) const override
void check (const std::string &context, const mapgen_parameters &params) const override
void check_consistent_with (const value_source &o, const std::string &context) const override
std::vector< StringId > all_possible_results (const mapgen_parameters &) const override
Public Member Functions inherited from mapgen_value< Id >::value_source
virtual ~value_source ()=default
virtual const std::string * get_name_if_parameter () const
Public Attributes
std::unique_ptr< mapgen_value< std::string > > on
std::unordered_map< std::string, StringId > cases
Detailed Description
template<typename Id>
struct mapgen_value< Id >::switch_source
Definition at line 1404 of file mapgen.cpp.
Constructor & Destructor Documentation
switch_source()
template<typename Id > mapgen_value< Id >::switch_source::switch_source (const JsonObject & jo) inline explicit
Definition at line 1412 of file mapgen.cpp.
                 : on( std::make_unique<mapgen_value<std::string>>( jo.get_object( "switch" ) ) ) {
                 jo.read( "cases", cases, true );
             }
References mapgen_value< Id >::switch_source::cases, and JsonObject::read().
Member Function Documentation
all_possible_results()
template<typename Id > std::vector<StringId> mapgen_value< Id >::switch_source::all_possible_results (const mapgen_parameters &) const inline override virtual
Implements mapgen_value< Id >::value_source.
Definition at line 1476 of file mapgen.cpp.
{
                 std::vector<StringId> result;
                 result.reserve( cases.size() );
                 for( const std::pair<const std::string, StringId> &p : cases ) {
                     result.push_back( p.second );
                 }
                 return result;
             }
References mapgen_value< Id >::switch_source::cases.
check()
template<typename Id > void mapgen_value< Id >::switch_source::check (const std::string & context, const mapgen_parameters & params) const inline override virtual
Reimplemented from mapgen_value< Id >::value_source.
Definition at line 1427 of file mapgen.cpp.
{
                 on->check( context, params );
                 for( const std::pair<const std::string, StringId> &p : cases ) {
                     if( !is_valid_helper( p.second ) ) {
                         debugmsg( "mapgen '%s' uses invalid entry '%s' in switch",
                                   context, cata_variant( p.second ).get_string() );
                     }
                 }
                 std::vector<std::string> possible_values = on->all_possible_results( params );
                 for( const std::string &value : possible_values ) {
                     if( !cases.count( value ) ) {
                         debugmsg( "mapgen '%s' has switch which does not account for potential "
                                   "case '%s' of the switched-on value", context, value );
                     }
                 }
             }
References mapgen_value< Id >::switch_source::cases, context, debugmsg, cata_variant::get_string(), is_valid_helper(), and mapgen_value< Id >::switch_source::on.
check_consistent_with()
template<typename Id > void mapgen_value< Id >::switch_source::check_consistent_with (const value_source & o, const std::string & context) const inline override virtual
Implements mapgen_value< Id >::value_source.
Definition at line 1445 of file mapgen.cpp.
{
                 if( const switch_source *other = dynamic_cast<const switch_source *>( &o ) ) {
                     on->check_consistent_with( *other->on, context );
                     if( cases != other->cases ) {
                         auto dump_set = []( const std::unordered_map<std::string, StringId> &s ) {
                             bool first = true;
                             std::string result = "{ ";
                             for( const std::pair<const std::string, StringId> &p : s ) {
                                 if( first ) {
                                     first = false;
                                 } else {
                                     result += ", ";
                                 }
                                 result += p.first;
                                 result += ": ";
                                 result += cata_variant( p.second ).get_string();
                             }
                             return result;
                         };
                         const std::string my_list = dump_set( cases );
                         const std::string other_list = dump_set( other->cases );
                         debugmsg( "inconsistent switch cases for %s (%s vs %s)",
                                   context, my_list, other_list );
                     }
                 } else {
                     debugmsg( "inconsistent default types for %s", context );
                 }
             }
References mapgen_value< Id >::switch_source::cases, context, debugmsg, cata_variant::get_string(), mapgen_value< Id >::switch_source::on, and other.
get()
template<typename Id > Id mapgen_value< Id >::switch_source::get (const mapgendata & dat) const inline override virtual
Implements mapgen_value< Id >::value_source.
Definition at line 1417 of file mapgen.cpp.
{
                 std::string based_on = on->get( dat );
                 auto it = cases.find( based_on );
                 if( it == cases.end() ) {
                     debugmsg( "switch does not handle case %s", based_on );
                     return make_null_helper<Id> {}();
                 }
                 return Id( it->second );
             }
References mapgen_value< Id >::switch_source::cases, debugmsg, and mapgen_value< Id >::switch_source::on.
Member Data Documentation
cases
template<typename Id > std::unordered_map<std::string, StringId> mapgen_value< Id >::switch_source::cases
Definition at line 1410 of file mapgen.cpp.
Referenced by mapgen_value< Id >::switch_source::all_possible_results(), mapgen_value< Id >::switch_source::check(), mapgen_value< Id >::switch_source::check_consistent_with(), mapgen_value< Id >::switch_source::get(), and mapgen_value< Id >::switch_source::switch_source().
on
template<typename Id > std::unique_ptr<mapgen_value<std::string> > mapgen_value< Id >::switch_source::on
Definition at line 1409 of file mapgen.cpp.
Referenced by mapgen_value< Id >::switch_source::check(), mapgen_value< Id >::switch_source::check_consistent_with(), and mapgen_value< Id >::switch_source::get().
The documentation for this struct was generated from the following file:
src/mapgen.cpp