Cataclysm DDA: veh_menu_item Struct Reference
veh_menu_item Struct Reference
#include <veh_utils.h>
Public Member Functions
veh_menu_item & text (const std::string &text)
veh_menu_item & desc (const std::string &desc)
veh_menu_item & enable (bool enable)
veh_menu_item & skip_theft_check (bool skip_theft_check=true)
veh_menu_item & skip_locked_check (bool skip_locked_check=true)
veh_menu_item & hotkey (char hotkey_char)
veh_menu_item & hotkey (const std::string &action)
veh_menu_item & hotkey_auto ()
veh_menu_item & on_submit (const std::function< void()> &on_submit)
veh_menu_item & keep_menu_open (bool keep_menu_open=true)
veh_menu_item & location (const std::optional< tripoint > &location)
Public Attributes
std::string _text
std::string _desc
std::optional< tripoint > _location = std::nullopt
bool _enabled = true
bool _check_theft = true
bool _check_locked = true
bool _keep_menu_open = false
std::optional< char > _hotkey_char = std::nullopt
std::optional< std::string > _hotkey_action = std::nullopt
std::function< void()> _on_submit
Detailed Description
Definition at line 34 of file veh_utils.h.
Member Function Documentation
desc()
veh_menu_item & veh_menu_item::desc (const std::string & desc)
Definition at line 168 of file veh_utils.cpp.
 {
     this->_desc = desc;
     return *this;
 }
References _desc.
Referenced by vehicle::build_bike_rack_menu(), vehicle::build_interact_menu(), and vehicle::toggle_autopilot().
enable()
veh_menu_item & veh_menu_item::enable (bool enable)
Definition at line 174 of file veh_utils.cpp.
 {
     this->_enabled = enable;
     return *this;
 }
References _enabled.
Referenced by add_electronic_toggle(), vehicle::build_bike_rack_menu(), vehicle::build_electronics_menu(), and vehicle::control_engines().
hotkey() [1/2]
veh_menu_item & veh_menu_item::hotkey (char hotkey_char)
Definition at line 207 of file veh_utils.cpp.
 {
     this->_hotkey_action = std::nullopt;
     this->_hotkey_char = hotkey_char;
     return *this;
 }
References _hotkey_action, and _hotkey_char.
Referenced by add_electronic_toggle(), vehicle::build_electronics_menu(), vehicle::build_interact_menu(), and vehicle::toggle_autopilot().
hotkey() [2/2]
veh_menu_item & veh_menu_item::hotkey (const std::string & action)
Definition at line 214 of file veh_utils.cpp.
 {
     this->_hotkey_action = action;
     this->_hotkey_char = std::nullopt;
     return *this;
 }
References _hotkey_action, _hotkey_char, and action.
hotkey_auto()
veh_menu_item & veh_menu_item::hotkey_auto ()
Definition at line 221 of file veh_utils.cpp.
 {
     this->_hotkey_char = std::nullopt;
     this->_hotkey_action = std::nullopt;
     return *this;
 }
References _hotkey_action, and _hotkey_char.
Referenced by vehicle::build_bike_rack_menu(), and vehicle::control_doors().
keep_menu_open()
veh_menu_item & veh_menu_item::keep_menu_open (bool keep_menu_open = true)
Definition at line 234 of file veh_utils.cpp.
 {
     this->_keep_menu_open = keep_menu_open;
     return *this;
 }
References _keep_menu_open.
Referenced by add_electronic_toggle(), vehicle::build_electronics_menu(), vehicle::build_interact_menu(), vehicle::control_doors(), and vehicle::control_engines().
location()
veh_menu_item & veh_menu_item::location (const std::optional< tripoint > & location)
Definition at line 240 of file veh_utils.cpp.
 {
     this->_location = location;
     return *this;
 }
References _location.
Referenced by vehicle::control_doors().
on_submit()
veh_menu_item & veh_menu_item::on_submit (const std::function< void()> & on_submit)
Definition at line 228 of file veh_utils.cpp.
 {
     this->_on_submit = on_submit;
     return *this;
 }
References _on_submit.
Referenced by add_electronic_toggle(), vehicle::build_bike_rack_menu(), vehicle::build_electronics_menu(), vehicle::build_interact_menu(), vehicle::control_doors(), vehicle::control_engines(), and vehicle::toggle_autopilot().
skip_locked_check()
veh_menu_item & veh_menu_item::skip_locked_check (bool skip_locked_check = true)
Definition at line 186 of file veh_utils.cpp.
 {
     this->_check_locked = !skip_locked_check;
     return *this;
 }
References _check_locked.
Referenced by vehicle::build_bike_rack_menu(), and vehicle::build_interact_menu().
skip_theft_check()
veh_menu_item & veh_menu_item::skip_theft_check (bool skip_theft_check = true)
Definition at line 180 of file veh_utils.cpp.
 {
     this->_check_theft = !skip_theft_check;
     return *this;
 }
References _check_theft.
Referenced by vehicle::build_interact_menu().
text()
veh_menu_item & veh_menu_item::text (const std::string & text)
Definition at line 162 of file veh_utils.cpp.
 {
     this->_text = text;
     return *this;
 }
References _text.
Member Data Documentation
_check_locked
bool veh_menu_item::_check_locked = true
Definition at line 40 of file veh_utils.h.
Referenced by veh_menu::get_uilist_entries(), and skip_locked_check().
_check_theft
bool veh_menu_item::_check_theft = true
Definition at line 39 of file veh_utils.h.
Referenced by veh_menu::query(), and skip_theft_check().
_desc
std::string veh_menu_item::_desc
Definition at line 36 of file veh_utils.h.
Referenced by desc(), and veh_menu::get_uilist_entries().
_enabled
bool veh_menu_item::_enabled = true
Definition at line 38 of file veh_utils.h.
Referenced by enable(), veh_menu::get_uilist_entries(), and veh_app_interact::populate_app_actions().
_hotkey_action
std::optional<std::string> veh_menu_item::_hotkey_action = std::nullopt
Definition at line 43 of file veh_utils.h.
Referenced by veh_menu::get_uilist_entries(), hotkey(), and hotkey_auto().
_hotkey_char
std::optional<char> veh_menu_item::_hotkey_char = std::nullopt
Definition at line 42 of file veh_utils.h.
Referenced by veh_menu::get_uilist_entries(), hotkey(), and hotkey_auto().
_keep_menu_open
bool veh_menu_item::_keep_menu_open = false
Definition at line 41 of file veh_utils.h.
Referenced by keep_menu_open(), and veh_menu::query().
_location
std::optional<tripoint> veh_menu_item::_location = std::nullopt
Definition at line 37 of file veh_utils.h.
Referenced by location().
_on_submit
std::function<void()> veh_menu_item::_on_submit
Definition at line 44 of file veh_utils.h.
Referenced by on_submit(), veh_app_interact::populate_app_actions(), and veh_menu::query().
_text
std::string veh_menu_item::_text
Definition at line 35 of file veh_utils.h.
Referenced by veh_menu::get_uilist_entries(), veh_app_interact::populate_app_actions(), and text().
The documentation for this struct was generated from the following files:
src/veh_utils.h
src/veh_utils.cpp