Cataclysm DDA: anonymous_namespace{gates.cpp}::gate_data Struct Reference
anonymous_namespace{gates.cpp}::gate_data Struct Reference
Public Member Functions
gate_data ()
void load (const JsonObject &jo, std::string_view src)
void check () const
bool is_suitable_wall (const tripoint_bub_ms &pos) const
Public Attributes
gate_id id
std::vector< std::pair< gate_id, mod_id > > src
ter_str_id door
ter_str_id floor
std::vector< ter_str_id > walls
translation pull_message
translation open_message
translation close_message
translation fail_message
int moves
int bash_dmg
bool was_loaded
Detailed Description
Definition at line 47 of file gates.cpp.
Constructor & Destructor Documentation
gate_data()
anonymous_namespace{gates.cpp}::gate_data::gate_data () inline
Definition at line 49 of file gates.cpp.
                 :
         moves( 0 ),
         bash_dmg( 0 ),
         was_loaded( false ) {}
Member Function Documentation
check()
void gate_data::check () const
Definition at line 104 of file gates.cpp.
 {
     const ter_str_id winch_tid( id.str() );
     if( !winch_tid.is_valid() ) {
         debugmsg( "Gates \"%s\" have no terrain of the same name, working as a winch.", id.c_str() );
     } else if( !winch_tid->has_examine( iexamine::controls_gate ) ) {
         debugmsg( "Terrain \"%s\" can't control gates, but gates \"%s\" depend on it.",
                   winch_tid.c_str(), id.c_str() );
     }
     if( !door.is_valid() ) {
         debugmsg( "Invalid door \"%s\" in \"%s\".", door.c_str(), id.c_str() );
     }
     if( !floor.is_valid() ) {
         debugmsg( "Invalid floor \"%s\" in \"%s\".", floor.c_str(), id.c_str() );
     }
     for( const auto &elem : walls ) {
         if( !elem.is_valid() ) {
             debugmsg( "Invalid wall \"%s\" in \"%s\".", elem.c_str(), id.c_str() );
         }
     }
     if( moves < 0 ) {
         debugmsg( "Gates \"%s\" grant moves.", id.c_str() );
     }
 }
References string_id< T >::c_str(), iexamine::controls_gate(), debugmsg, floor(), map_data_common_t::has_examine(), and string_id< T >::is_valid().
is_suitable_wall()
bool gate_data::is_suitable_wall (const tripoint_bub_ms & pos) const
Definition at line 132 of file gates.cpp.
 {
     const ter_id wid = get_map().ter( pos );
     const auto iter = std::find_if( walls.begin(), walls.end(), [ wid ]( const ter_str_id & wall ) {
         return wall.id() == wid;
     } );
     return iter != walls.end();
 }
References get_map(), math_opers::pos(), and map::ter().
load()
void gate_data::load (const JsonObject & jo, std::string_view src)
Definition at line 85 of file gates.cpp.
 {
     mandatory( jo, was_loaded, "door", door );
     mandatory( jo, was_loaded, "floor", floor );
     mandatory( jo, was_loaded, "walls", walls, string_id_reader<ter_t> {} );
     if( !was_loaded || jo.has_member( "messages" ) ) {
         JsonObject messages_obj = jo.get_object( "messages" );
         optional( messages_obj, was_loaded, "pull", pull_message );
         optional( messages_obj, was_loaded, "open", open_message );
         optional( messages_obj, was_loaded, "close", close_message );
         optional( messages_obj, was_loaded, "fail", fail_message );
     }
     optional( jo, was_loaded, "moves", moves, 0 );
     optional( jo, was_loaded, "bashing_damage", bash_dmg, 0 );
 }
References floor(), JsonObject::get_object(), JsonObject::has_member(), mandatory(), and optional().
Member Data Documentation
bash_dmg
int anonymous_namespace{gates.cpp}::gate_data::bash_dmg
Definition at line 67 of file gates.cpp.
close_message
translation anonymous_namespace{gates.cpp}::gate_data::close_message
Definition at line 63 of file gates.cpp.
door
ter_str_id anonymous_namespace{gates.cpp}::gate_data::door
Definition at line 57 of file gates.cpp.
fail_message
translation anonymous_namespace{gates.cpp}::gate_data::fail_message
Definition at line 64 of file gates.cpp.
floor
ter_str_id anonymous_namespace{gates.cpp}::gate_data::floor
Definition at line 58 of file gates.cpp.
id
gate_id anonymous_namespace{gates.cpp}::gate_data::id
Definition at line 54 of file gates.cpp.
moves
int anonymous_namespace{gates.cpp}::gate_data::moves
Definition at line 66 of file gates.cpp.
open_message
translation anonymous_namespace{gates.cpp}::gate_data::open_message
Definition at line 62 of file gates.cpp.
pull_message
translation anonymous_namespace{gates.cpp}::gate_data::pull_message
Definition at line 61 of file gates.cpp.
src
std::vector<std::pair<gate_id, mod_id> > anonymous_namespace{gates.cpp}::gate_data::src
Definition at line 55 of file gates.cpp.
walls
std::vector<ter_str_id> anonymous_namespace{gates.cpp}::gate_data::walls
Definition at line 59 of file gates.cpp.
was_loaded
bool anonymous_namespace{gates.cpp}::gate_data::was_loaded
Definition at line 68 of file gates.cpp.
The documentation for this struct was generated from the following file:
src/gates.cpp