Cataclysm DDA: prof_window Struct Reference
prof_window Struct Reference
Public Member Functions
prof_window ()=delete
prof_window (prof_window &)=delete
prof_window (prof_window &&)=delete
prof_window (const Character *u)
shared_ptr_fast< ui_adaptor > create_or_get_ui_adaptor ()
void filter ()
std::vector< display_prof_deps * > & get_current_set ()
void populate_categories ()
void init_ui_windows ()
void draw_borders ()
void draw_header ()
void draw_profs ()
void draw_details ()
void run (std::optional< proficiency_id > default_selection=std::nullopt)
Public Attributes
input_context ctxt
weak_ptr_fast< ui_adaptor > ui
catacurses::window w_border
catacurses::window w_header
catacurses::window w_profs
catacurses::window w_details
const Character * u = nullptr
std::vector< const proficiency_category * > cats
std::vector< display_prof_deps > all_profs
std::vector< display_prof_deps * > filtered_profs
std::map< int, std::vector< display_prof_deps * > > profs_by_cat
std::string filter_str
int max_rows = 0
int column_width = 0
int sel_prof = 0
int top_prof = 0
int current_cat = 0
Detailed Description
Definition at line 29 of file proficiency_ui.cpp.
Constructor & Destructor Documentation
prof_window() [1/4]
prof_window::prof_window () delete
prof_window() [2/4]
prof_window::prof_window (prof_window &) delete
prof_window() [3/4]
prof_window::prof_window (prof_window &&) delete
prof_window() [4/4]
prof_window::prof_window (const Character * u) inline explicit
Definition at line 52 of file proficiency_ui.cpp.
 : u( u ) {}
Member Function Documentation
create_or_get_ui_adaptor()
shared_ptr_fast< ui_adaptor > prof_window::create_or_get_ui_adaptor ()
Definition at line 290 of file proficiency_ui.cpp.
 {
     shared_ptr_fast<ui_adaptor> current_ui = ui.lock();
     if( !current_ui ) {
         ui = current_ui = make_shared_fast<ui_adaptor>();
         current_ui->on_screen_resize( [this]( ui_adaptor & cui ) {
             init_ui_windows();
             cui.position_from_window( w_border );
         } );
         current_ui->mark_resize();
         current_ui->on_redraw( [this]( const ui_adaptor & ) {
             draw_borders();
             draw_header();
             draw_profs();
             draw_details();
         } );
     }
     return current_ui;
 }
References draw_borders(), draw_details(), draw_header(), draw_profs(), init_ui_windows(), ui_adaptor::position_from_window(), and w_border.
Referenced by run().
draw_borders()
void prof_window::draw_borders ()
Definition at line 244 of file proficiency_ui.cpp.
 {
     const int w = catacurses::getmaxx( w_border );
     const int h = catacurses::getmaxy( w_border );
     draw_border( w_border, c_white, _( "Proficiencies" ), c_yellow );
     // horizontal header separator
     for( int i = 1; i < w - 1; i++ ) {
         mvwputch( w_border, point( i, 4 ), c_white, LINE_OXOX );
     }
     mvwputch( w_border, point( 0, 4 ), c_white, LINE_XXXO );
     mvwputch( w_border, point( w - 1, 4 ), c_white, LINE_XOXX );
     // vertical column separator
     for( int i = 5; i < h - 1; i++ ) {
         mvwputch( w_border, point( column_width + 1, i ), c_white, LINE_XOXO );
     }
     mvwputch( w_border, point( column_width + 1, 4 ), c_white, LINE_OXXX );
     mvwputch( w_border, point( column_width + 1, h - 1 ), c_white, LINE_XXOX );
     scrollbar()
     .border_color( c_white )
     .offset_x( 0 )
     .offset_y( 5 )
     .content_size( get_current_set().size() )
     .viewport_pos( top_prof )
     .viewport_size( max_rows )
     .apply( w_border );
     wnoutrefresh( w_border );
 }
References _, scrollbar::apply(), scrollbar::border_color(), c_white, c_yellow, column_width, scrollbar::content_size(), draw_border(), get_current_set(), catacurses::getmaxx(), catacurses::getmaxy(), LINE_OXOX, LINE_OXXX, LINE_XOXO, LINE_XOXX, LINE_XXOX, LINE_XXXO, max_rows, mvwputch(), scrollbar::offset_x(), scrollbar::offset_y(), point, om_direction::size, top_prof, scrollbar::viewport_pos(), scrollbar::viewport_size(), w_border, and catacurses::wnoutrefresh().
Referenced by create_or_get_ui_adaptor().
draw_details()
void prof_window::draw_details ()
Definition at line 160 of file proficiency_ui.cpp.
 {
     werase( w_details );
     std::vector<display_prof_deps *> &cur_set = get_current_set();
     if( !cur_set.empty() ) {
         int y = 0;
         display_prof_deps *p = cur_set[sel_prof];
         // Time to learn
         std::string ttl = !p->first.id->can_learn() ? colorize( _( "Can't learn" ), c_dark_gray ) :
                           to_string( p->first.id->time_to_learn() );
         trim_and_print( w_details, point( 1, y++ ), column_width - 2, c_white,
                         string_format( "%s: %s", colorize( _( "Time to learn" ), c_magenta ), ttl ) );
         // Progress
         trim_and_print( w_details, point( 1, y++ ), column_width - 2, c_white,
                         string_format( "%s: %.2f%%", colorize( _( "Progress" ), c_magenta ), p->first.practice * 100.0f ) );
         // Category
         trim_and_print( w_details, point( 1, y++ ), column_width - 2, c_white,
                         string_format( "%s: %s", colorize( _( "Category" ), c_magenta ),
                                        p->first.id->prof_category()->_name.translated() ) );
         // Pre-requisites
         trim_and_print( w_details, point( 1, y++ ), column_width - 2, c_white,
                         string_format( "%s:", colorize( _( "Pre-requisites" ), c_magenta ) ) );
         std::vector<std::string> reqs =
             foldstring( enumerate_as_string( p->first.id->required_proficiencies(),
         []( const proficiency_id & pid ) {
             return colorize( pid->name(), c_yellow );
         }, enumeration_conjunction::and_ ), column_width - 2 );
         for( auto &req : reqs ) {
             trim_and_print( w_details, point( 1, y++ ), column_width - 1, c_white, req );
         }
         // Leads to
         trim_and_print( w_details, point( 1, y++ ), column_width - 2, c_white,
                         string_format( "%s:", colorize( _( "Leads to" ), c_magenta ) ) );
         std::vector<std::string> leads = foldstring( enumerate_as_string( p->second,
         []( const proficiency_id & pid ) {
             return colorize( pid->name(), c_yellow );
         }, enumeration_conjunction::and_ ), column_width - 2 );
         for( auto &lead : leads ) {
             trim_and_print( w_details, point( 1, y++ ), column_width - 1, c_white, lead );
         }
         // Description
         fold_and_print( w_details, point( 1, y ), column_width - 1, c_light_gray,
                         string_format( "%s: %s", colorize( _( "Description" ), c_magenta ), p->first.id->description() ) );
     }
     wnoutrefresh( w_details );
 }
References _, and_, c_dark_gray, c_light_gray, c_magenta, c_white, colorize(), column_width, enumerate_as_string(), fold_and_print(), foldstring(), get_current_set(), point, sel_prof, string_format(), to_string(), trim_and_print(), w_details, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by create_or_get_ui_adaptor().
draw_header()
void prof_window::draw_header ()
Definition at line 223 of file proficiency_ui.cpp.
 {
     const int w = catacurses::getmaxx( w_header );
     werase( w_header );
     std::string cat_title = !filter_str.empty() ? _( "FILTERED" ) :
                             ( current_cat == 0 ) ? _( "ALL" ) : cats[current_cat]->_name.translated();
     //NOLINTNEXTLINE(cata-use-named-point-constants)
     trim_and_print( w_header, point( 1, 0 ), w - 2, c_white, "%s:  %s %s %s", _( "Category" ),
                     colorize( "<", c_yellow ), colorize( cat_title, c_light_green ), colorize( ">", c_yellow ) );
     if( current_cat != 0 && filter_str.empty() ) {
         //NOLINTNEXTLINE(cata-use-named-point-constants)
         fold_and_print( w_header, point( 1, 1 ), w - 2, c_light_gray,
                         cats[current_cat]->_description.translated() );
     }
     std::string hint_txt = string_format( "[%s] %s   [%s] %s",
                                           colorize( ctxt.get_desc( "FILTER", 1 ), c_yellow ), _( "filter" ),
                                           colorize( ctxt.get_desc( "HELP_KEYBINDINGS", 1 ), c_yellow ), _( "help" ) );
     right_print( w_header, 0, 1, c_white, hint_txt );
     wnoutrefresh( w_header );
 }
References _, c_light_gray, c_light_green, c_white, c_yellow, cats, colorize(), ctxt, current_cat, filter_str, fold_and_print(), input_context::get_desc(), catacurses::getmaxx(), point, right_print(), string_format(), trim_and_print(), w_header, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by create_or_get_ui_adaptor().
draw_profs()
void prof_window::draw_profs ()
Definition at line 207 of file proficiency_ui.cpp.
 {
     werase( w_profs );
     std::vector<display_prof_deps *> &cur_set = get_current_set();
     for( int i = 0; i < max_rows && i + top_prof < static_cast<int>( cur_set.size() ); i++ ) {
         nc_color colr = cur_set[i + top_prof]->first.color;
         if( sel_prof == i + top_prof ) {
             colr = hilite( colr );
             mvwputch( w_profs, point( 1, i ), c_yellow, '>' );
         }
         mvwprintz( w_profs, point( 2, i ), colr,
                    trim_by_length( cur_set[i + top_prof]->first.id->name(), column_width - 2 ) );
     }
     wnoutrefresh( w_profs );
 }
References c_yellow, column_width, get_current_set(), hilite(), mvwprintz(), mvwputch(), point, sel_prof, top_prof, trim_by_length(), w_profs, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by create_or_get_ui_adaptor().
filter()
void prof_window::filter ()
Definition at line 70 of file proficiency_ui.cpp.
 {
     enum class _prof_filter_prefix {
         LEARNED,
         UNLEARNED,
         AS_PROGRESS,
         NONE
     };
     std::string qry = trim( filter_str );
     filtered_profs.clear();
     if( qry.empty() ) {
         return;
     }
     _prof_filter_prefix prefix = _prof_filter_prefix::NONE;
     if( qry.size() > 2 && qry[1] == ':' ) {
         switch( qry[0] ) {
             case 'l':
                 prefix = _prof_filter_prefix::LEARNED;
                 qry = qry.substr( 2 );
                 break;
             case 'i':
                 prefix = _prof_filter_prefix::UNLEARNED;
                 qry = qry.substr( 2 );
                 break;
             case 'p':
                 prefix = _prof_filter_prefix::AS_PROGRESS;
                 qry = qry.substr( 2 );
                 break;
             default:
                 break;
         }
     }
     float prog_val = 0.0f;
     if( prefix == _prof_filter_prefix::AS_PROGRESS ) {
         try {
             prog_val = std::stof( qry );
         } catch( const std::invalid_argument &e ) {
             // User mistyped query. Not severe enough for debugmsg.
             DebugLog( DebugLevel::D_WARNING, DebugClass::D_GAME ) <<
                     "Malformed proficiency query \"" << filter_str << "\": " << e.what();
             return;
         }
     }
     for( display_prof_deps &dp : all_profs ) {
         if( prefix == _prof_filter_prefix::AS_PROGRESS ) {
             if( prog_val < dp.first.practice * 100.0f ) {
                 filtered_profs.push_back( &dp );
             }
             continue;
         }
         if( ( prefix == _prof_filter_prefix::LEARNED && !dp.first.known ) ||
             ( prefix == _prof_filter_prefix::UNLEARNED && dp.first.known ) ) {
             continue;
         }
         if( qry == "*" || lcmatch( dp.first.id->name(), qry ) ) {
             filtered_profs.push_back( &dp );
         }
     }
 }
References all_profs, D_GAME, D_WARNING, DebugLog(), filter_str, filtered_profs, lcmatch(), NONE, prefix, and trim().
Referenced by run().
get_current_set()
std::vector< display_prof_deps * > & prof_window::get_current_set ()
Definition at line 65 of file proficiency_ui.cpp.
 {
     return filter_str.empty() ? profs_by_cat[current_cat] : filtered_profs;
 }
References current_cat, filter_str, filtered_profs, and profs_by_cat.
Referenced by draw_borders(), draw_details(), draw_profs(), and run().
init_ui_windows()
void prof_window::init_ui_windows ()
Definition at line 274 of file proficiency_ui.cpp.
 {
     const int h = std::min( 28, TERMY );
     const int w = std::min( 120, TERMX );
     const point origin( TERMX / 2 - w / 2, TERMY / 2 - h / 2 );
     const int center = w / 2;
     max_rows = h - 6;
     column_width = center - 2;
     w_border  = catacurses::newwin( h, w, origin );
     //NOLINTNEXTLINE(cata-use-named-point-constants)
     w_header  = catacurses::newwin( 3, w - 2, origin + point( 1, 1 ) );
     w_profs   = catacurses::newwin( max_rows, column_width, origin + point( 1, 5 ) );
     w_details = catacurses::newwin( max_rows, column_width, origin + point( center + 1, 5 ) );
 }
References center, column_width, max_rows, min(), catacurses::newwin(), point, TERMX, TERMY, w_border, w_details, w_header, and w_profs.
Referenced by create_or_get_ui_adaptor().
populate_categories()
void prof_window::populate_categories ()
Definition at line 130 of file proficiency_ui.cpp.
 {
     for( display_proficiency &p : u->display_proficiencies() ) {
         all_profs.push_back( { p, {} } );
     }
     for( const proficiency &p : proficiency::get_all() ) {
         for( const proficiency_id &pid : p.required_proficiencies() ) {
             auto iter = std::find_if( all_profs.begin(), all_profs.end(),
             [&pid]( const display_prof_deps & dpd ) {
                 return dpd.first.id == pid;
             } );
             if( iter != all_profs.end() ) {
                 iter->second.push_back( p.prof_id() );
             }
         }
     }
     cats.push_back( nullptr );
     for( const proficiency_category &pc : proficiency_category::get_all() ) {
         cats.push_back( &pc );
     }
     for( int i = 0; i < static_cast<int>( cats.size() ); i++ ) {
         for( display_prof_deps &dp : all_profs ) {
             if( i == 0 || dp.first.id->prof_category() == cats[i]->id ) {
                 profs_by_cat[i].push_back( &dp );
             }
         }
     }
 }
References all_profs, cats, Character::display_proficiencies(), proficiency_category::get_all(), proficiency::get_all(), profs_by_cat, and u.
Referenced by run().
run()
void prof_window::run (std::optional< proficiency_id > default_selection = std::nullopt)
Definition at line 310 of file proficiency_ui.cpp.
 {
     if( !u ) {
         return;
     }
     ctxt = input_context( "PROFICIENCY_WINDOW" );
     ctxt.register_navigate_ui_list();
     ctxt.register_leftright();
     ctxt.register_action( "PREV_TAB" );
     ctxt.register_action( "NEXT_TAB" );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     ctxt.register_action( "PREV_CATEGORY" );
     ctxt.register_action( "NEXT_CATEGORY" );
     ctxt.register_action( "FILTER" );
     ctxt.register_action( "QUIT" );
     populate_categories();
     shared_ptr_fast<ui_adaptor> current_ui = create_or_get_ui_adaptor();
     if( default_selection ) {
         std::vector<display_prof_deps *> &cur_set = get_current_set();
         for( int i = 0; i < static_cast<int>( cur_set.size() ); i++ ) {
             if( cur_set[i]->first.id == default_selection.value() ) {
                 sel_prof = i;
                 break;
             }
         }
     }
     bool done = false;
     while( !done ) {
         ui_manager::redraw();
         std::string action = ctxt.handle_input();
         std::vector<display_prof_deps *> &cur_set = get_current_set();
         if( navigate_ui_list( action, sel_prof, 10, cur_set.size(), true ) ) {
         } else if( filter_str.empty() && ( action == "LEFT" || action == "PREV_CATEGORY" ||
                                            action == "PREV_TAB" ||
                                            action == "RIGHT" || action == "NEXT_CATEGORY" || action == "NEXT_TAB" ) ) {
             current_cat = inc_clamp_wrap( current_cat,
                                           action == "RIGHT" || action == "NEXT_CATEGORY" || action == "NEXT_TAB", cats.size() );
             sel_prof = 0;
             top_prof = 0;
         } else if( action == "FILTER" ) {
             //~ Refers to single-character search prefixes, like p: or s:
             std::string desc( _( "Available prefixes:" ) );
             desc += "\n  ";
             desc += _( "<color_c_light_cyan>l:</color>  Learned proficiencies" );
             desc += "\n  ";
             desc += _( "<color_c_light_cyan>i:</color>  In-progress proficiencies" );
             desc += "\n  ";
             desc += _( "<color_c_light_cyan>p:</color>  Returns proficiencies above the given progress.  "
                        "ex: <color_c_yellow>p:95.00</color>" );
             desc += "\n\n";
             desc += _( "By default, the filter applies to proficiencies containing the given string.  "
                        "Using just a glob <color_c_yellow>*</color> matches anything.\n"
                        "ex: <color_c_yellow>l:*</color> returns all learned proficiencies." );
             desc += "\n\n";
             string_input_popup popup;
             popup
             .title( _( "Search:" ) )
             .width( 78 )
             .description( desc )
             .desc_color( c_light_gray )
             .identifier( "proficiency_filter" )
             .hist_use_uilist( false )
             .edit( filter_str );
             if( popup.confirmed() ) {
                 sel_prof = 0;
                 top_prof = 0;
                 current_cat = 0;
                 filter();
             }
         } else if( action == "QUIT" ) {
             done = true;
         }
         if( sel_prof < top_prof ) {
             top_prof = sel_prof;
         }
         if( sel_prof > top_prof + max_rows - 1 ) {
             top_prof = sel_prof - ( max_rows - 1 );
         }
         if( top_prof < 0 ) {
             top_prof = 0;
         }
     }
 }
References _, action, c_light_gray, cats, create_or_get_ui_adaptor(), ctxt, current_cat, filter(), filter_str, get_current_set(), input_context::handle_input(), inc_clamp_wrap(), max_rows, navigate_ui_list(), populate_categories(), popup(), ui_manager::redraw(), input_context::register_action(), input_context::register_leftright(), input_context::register_navigate_ui_list(), sel_prof, top_prof, and u.
Referenced by show_proficiencies_window().
Member Data Documentation
all_profs
std::vector<display_prof_deps> prof_window::all_profs
Definition at line 39 of file proficiency_ui.cpp.
Referenced by filter(), and populate_categories().
cats
std::vector<const proficiency_category *> prof_window::cats
Definition at line 38 of file proficiency_ui.cpp.
Referenced by draw_header(), populate_categories(), and run().
column_width
int prof_window::column_width = 0
Definition at line 44 of file proficiency_ui.cpp.
Referenced by draw_borders(), draw_details(), draw_profs(), and init_ui_windows().
ctxt
input_context prof_window::ctxt
Definition at line 30 of file proficiency_ui.cpp.
Referenced by draw_header(), and run().
current_cat
int prof_window::current_cat = 0
Definition at line 47 of file proficiency_ui.cpp.
Referenced by draw_header(), get_current_set(), and run().
filter_str
std::string prof_window::filter_str
Definition at line 42 of file proficiency_ui.cpp.
Referenced by draw_header(), filter(), get_current_set(), and run().
filtered_profs
std::vector<display_prof_deps *> prof_window::filtered_profs
Definition at line 40 of file proficiency_ui.cpp.
Referenced by filter(), and get_current_set().
max_rows
int prof_window::max_rows = 0
Definition at line 43 of file proficiency_ui.cpp.
Referenced by draw_borders(), init_ui_windows(), and run().
profs_by_cat
std::map<int, std::vector<display_prof_deps *> > prof_window::profs_by_cat
Definition at line 41 of file proficiency_ui.cpp.
Referenced by get_current_set(), and populate_categories().
sel_prof
int prof_window::sel_prof = 0
Definition at line 45 of file proficiency_ui.cpp.
Referenced by draw_details(), draw_profs(), and run().
top_prof
int prof_window::top_prof = 0
Definition at line 46 of file proficiency_ui.cpp.
Referenced by draw_borders(), draw_profs(), and run().
u
const Character* prof_window::u = nullptr
Definition at line 37 of file proficiency_ui.cpp.
Referenced by populate_categories(), and run().
ui
weak_ptr_fast<ui_adaptor> prof_window::ui
Definition at line 31 of file proficiency_ui.cpp.
w_border
catacurses::window prof_window::w_border
Definition at line 32 of file proficiency_ui.cpp.
Referenced by create_or_get_ui_adaptor(), draw_borders(), and init_ui_windows().
w_details
catacurses::window prof_window::w_details
Definition at line 35 of file proficiency_ui.cpp.
Referenced by draw_details(), and init_ui_windows().
w_header
catacurses::window prof_window::w_header
Definition at line 33 of file proficiency_ui.cpp.
Referenced by draw_header(), and init_ui_windows().
w_profs
catacurses::window prof_window::w_profs
Definition at line 34 of file proficiency_ui.cpp.
Referenced by draw_profs(), and init_ui_windows().
The documentation for this struct was generated from the following file:
src/proficiency_ui.cpp