Cataclysm DDA: mapgen_value< Id >::param_source Struct Reference
mapgen_value< Id >::param_source Struct Reference
Public Member Functions
param_source (const JsonObject &jo)
Id get (const mapgendata &dat) const override
void check (const std::string &context, const mapgen_parameters &parameters) const override
void check_consistent_with (const value_source &o, const std::string &context) const override
std::vector< StringId > all_possible_results (const mapgen_parameters &params) const override
const std::string * get_name_if_parameter () const override
Public Member Functions inherited from mapgen_value< Id >::value_source
virtual ~value_source ()=default
Public Attributes
std::string param_name
std::optional< StringId > fallback
Detailed Description
template<typename Id>
struct mapgen_value< Id >::param_source
Definition at line 1287 of file mapgen.cpp.
Constructor & Destructor Documentation
param_source()
template<typename Id > mapgen_value< Id >::param_source::param_source (const JsonObject & jo) inline explicit
Definition at line 1291 of file mapgen.cpp.
                 : param_name( jo.get_string( "param" ) ) {
                 jo.read( "fallback", fallback, false );
             }
References mapgen_value< Id >::param_source::fallback, and JsonObject::read().
Member Function Documentation
all_possible_results()
template<typename Id > std::vector<StringId> mapgen_value< Id >::param_source::all_possible_results (const mapgen_parameters & params) const inline override virtual
Implements mapgen_value< Id >::value_source.
Definition at line 1340 of file mapgen.cpp.
{
                 auto param_it = params.map.find( param_name );
                 if( param_it == params.map.end() ) {
                     return {};
                 } else {
                     const mapgen_parameter &param = param_it->second;
                     std::vector<StringId> result;
                     for( const std::string &s : param.all_possible_values( params ) ) {
                         result.emplace_back( s );
                     }
                     return result;
                 }
             }
References mapgen_parameter::all_possible_values(), mapgen_parameters::map, and mapgen_value< Id >::param_source::param_name.
check()
template<typename Id > void mapgen_value< Id >::param_source::check (const std::string & context, const mapgen_parameters & parameters) const inline override virtual
Reimplemented from mapgen_value< Id >::value_source.
Definition at line 1304 of file mapgen.cpp.
{
                 auto param_it = parameters.map.find( param_name );
                 if( param_it == parameters.map.end() ) {
                     debugmsg( "mapgen '%s' uses undefined parameter '%s'", context, param_name );
                 } else {
                     const mapgen_parameter &param = param_it->second;
                     constexpr cata_variant_type req_type = cata_variant_type_for<StringId>();
                     cata_variant_type param_type = param.type();
                     if( param_type != req_type && req_type != cata_variant_type::string ) {
                         debugmsg( "mapgen '%s' uses parameter '%s' of type '%s' in a context "
                                   "expecting type '%s'", context, param_name,
                                   io::enum_to_string( param_type ),
                                   io::enum_to_string( req_type ) );
                     }
                     if( param.scope() == mapgen_parameter_scope::overmap_special && !fallback ) {
                         debugmsg( "mapgen '%s' uses parameter '%s' of map_special scope without a "
                                   "fallback.  Such parameters must provide a fallback to allow "
                                   "for changes to overmap_special definitions", context,
                                   param_name );
                     }
                 }
             }
References context, debugmsg, io::enum_to_string(), mapgen_value< Id >::param_source::fallback, mapgen_parameters::map, overmap_special, mapgen_value< Id >::param_source::param_name, mapgen_parameter::scope(), string, and mapgen_parameter::type().
check_consistent_with()
template<typename Id > void mapgen_value< Id >::param_source::check_consistent_with (const value_source & o, const std::string & context) const inline override virtual
Implements mapgen_value< Id >::value_source.
Definition at line 1328 of file mapgen.cpp.
{
                 if( const param_source *other = dynamic_cast<const param_source *>( &o ) ) {
                     if( param_name != other->param_name ) {
                         debugmsg( "inconsistent default values for %s (%s vs %s)",
                                   context, param_name, other->param_name );
                     }
                 } else {
                     debugmsg( "inconsistent default types for %s", context );
                 }
             }
References context, debugmsg, other, and mapgen_value< Id >::param_source::param_name.
get()
template<typename Id > Id mapgen_value< Id >::param_source::get (const mapgendata & dat) const inline override virtual
Implements mapgen_value< Id >::value_source.
Definition at line 1296 of file mapgen.cpp.
{
                 if( fallback ) {
                     return Id( dat.get_arg_or<StringId>( param_name, *fallback ) );
                 } else {
                     return Id( dat.get_arg<StringId>( param_name ) );
                 }
             }
References mapgen_value< Id >::param_source::fallback, mapgendata::get_arg(), mapgendata::get_arg_or(), and mapgen_value< Id >::param_source::param_name.
get_name_if_parameter()
template<typename Id > const std::string* mapgen_value< Id >::param_source::get_name_if_parameter () const inline override virtual
Reimplemented from mapgen_value< Id >::value_source.
Definition at line 1355 of file mapgen.cpp.
{
                 return &param_name;
             }
References mapgen_value< Id >::param_source::param_name.
Member Data Documentation
fallback
template<typename Id > std::optional<StringId> mapgen_value< Id >::param_source::fallback
Definition at line 1289 of file mapgen.cpp.
Referenced by mapgen_value< Id >::param_source::check(), mapgen_value< Id >::param_source::get(), and mapgen_value< Id >::param_source::param_source().
param_name
template<typename Id > std::string mapgen_value< Id >::param_source::param_name
Definition at line 1288 of file mapgen.cpp.
Referenced by mapgen_value< Id >::param_source::all_possible_results(), mapgen_value< Id >::param_source::check(), mapgen_value< Id >::param_source::check_consistent_with(), mapgen_value< Id >::param_source::get(), and mapgen_value< Id >::param_source::get_name_if_parameter().
The documentation for this struct was generated from the following file:
src/mapgen.cpp