Cataclysm DDA: groundcover_extra Struct Reference
groundcover_extra Struct Reference
#include <regional_settings.h>
Public Member Functions
ter_furn_id pick (bool boosted=false) const
void finalize ()
groundcover_extra ()=default
Public Attributes
std::string default_ter_str
std::map< std::string, double > percent_str
std::map< std::string, double > boosted_percent_str
std::map< int, ter_furn_id > weightlist
std::map< int, ter_furn_id > boosted_weightlist
ter_id default_ter = t_null
int mpercent_coverage = 0
int boost_chance = 0
int boosted_mpercent_coverage = 0
int boosted_other_mpercent = 1
Detailed Description
Definition at line 93 of file regional_settings.h.
Constructor & Destructor Documentation
groundcover_extra()
groundcover_extra::groundcover_extra () default
Member Function Documentation
finalize()
void groundcover_extra::finalize ()
Definition at line 765 of file regional_settings.cpp.
 {
     default_ter = ter_id( default_ter_str );
     ter_furn_id tf_id;
     int wtotal = 0;
     int btotal = 0;
     for( std::map<std::string, double>::const_iterator it = percent_str.begin();
          it != percent_str.end(); ++it ) {
         tf_id.ter = ter_str_id::NULL_ID().id();
         tf_id.furn = furn_str_id::NULL_ID();
         if( it->second < 0.0001 ) {
             continue;
         }
         const ter_str_id tid( it->first );
         const furn_str_id fid( it->first );
         if( tid.is_valid() ) {
             tf_id.ter = tid.id();
         } else if( fid.is_valid() ) {
             tf_id.furn = fid.id();
         } else {
             debugmsg( "No clue what '%s' is!  No such terrain or furniture", it->first.c_str() );
             continue;
         }
         wtotal += static_cast<int>( it->second * 10000.0 );
         weightlist[ wtotal ] = tf_id;
     }
     for( std::map<std::string, double>::const_iterator it = boosted_percent_str.begin();
          it != boosted_percent_str.end(); ++it ) {
         tf_id.ter = ter_str_id::NULL_ID().id();
         tf_id.furn = furn_str_id::NULL_ID();
         if( it->second < 0.0001 ) {
             continue;
         }
         const ter_str_id tid( it->first );
         const furn_str_id fid( it->first );
         if( tid.is_valid() ) {
             tf_id.ter = tid.id();
         } else if( fid.is_valid() ) {
             tf_id.furn = fid.id();
         } else {
             debugmsg( "No clue what '%s' is!  No such terrain or furniture", it->first.c_str() );
             continue;
         }
         btotal += static_cast<int>( it->second * 10000.0 );
         boosted_weightlist[ btotal ] = tf_id;
     }
     if( wtotal > 1000000 ) {
         std::stringstream ss;
         for( auto it = percent_str.begin(); it != percent_str.end(); ++it ) {
             if( it != percent_str.begin() ) {
                 ss << '+';
             }
             ss << it->second;
         }
         debugmsg( "plant coverage total (%s=%de-4) exceeds 100%%", ss.str(), wtotal );
     }
     if( btotal > 1000000 ) {
         std::stringstream ss;
         for( auto it = boosted_percent_str.begin(); it != boosted_percent_str.end(); ++it ) {
             if( it != boosted_percent_str.begin() ) {
                 ss << '+';
             }
             ss << it->second;
         }
         debugmsg( "boosted plant coverage total (%s=%de-4) exceeds 100%%", ss.str(), btotal );
     }
     tf_id.furn = furn_str_id::NULL_ID();
     tf_id.ter = default_ter;
     weightlist[ 1000000 ] = tf_id;
     boosted_weightlist[ 1000000 ] = tf_id;
     percent_str.clear();
     boosted_percent_str.clear();
 }
References boosted_percent_str, boosted_weightlist, debugmsg, default_ter, default_ter_str, ter_furn_id::furn, string_id< T >::id(), string_id< T >::is_valid(), string_id< ter_t >::NULL_ID(), string_id< furn_t >::NULL_ID(), percent_str, ter_furn_id::ter, ter_id, and weightlist.
pick()
ter_furn_id groundcover_extra::pick (bool boosted = false) const
Definition at line 846 of file regional_settings.cpp.
 {
     if( boosted ) {
         return boosted_weightlist.lower_bound( rng( 0, 1000000 ) )->second;
     }
     return weightlist.lower_bound( rng( 0, 1000000 ) )->second;
 }
References boosted_weightlist, rng(), and weightlist.
Member Data Documentation
boost_chance
int groundcover_extra::boost_chance = 0
Definition at line 102 of file regional_settings.h.
boosted_mpercent_coverage
int groundcover_extra::boosted_mpercent_coverage = 0
Definition at line 103 of file regional_settings.h.
boosted_other_mpercent
int groundcover_extra::boosted_other_mpercent = 1
Definition at line 104 of file regional_settings.h.
boosted_percent_str
std::map<std::string, double> groundcover_extra::boosted_percent_str
Definition at line 97 of file regional_settings.h.
Referenced by finalize().
boosted_weightlist
std::map<int, ter_furn_id> groundcover_extra::boosted_weightlist
Definition at line 99 of file regional_settings.h.
Referenced by finalize(), and pick().
default_ter
ter_id groundcover_extra::default_ter = t_null
Definition at line 100 of file regional_settings.h.
Referenced by finalize().
default_ter_str
std::string groundcover_extra::default_ter_str
Definition at line 95 of file regional_settings.h.
Referenced by finalize().
mpercent_coverage
int groundcover_extra::mpercent_coverage = 0
Definition at line 101 of file regional_settings.h.
percent_str
std::map<std::string, double> groundcover_extra::percent_str
Definition at line 96 of file regional_settings.h.
Referenced by finalize().
weightlist
std::map<int, ter_furn_id> groundcover_extra::weightlist
Definition at line 98 of file regional_settings.h.
Referenced by finalize(), and pick().
The documentation for this struct was generated from the following files:
src/regional_settings.h
src/regional_settings.cpp