Cataclysm DDA: mm_submap Struct Reference
mm_submap Struct Reference
Represent a submap-sized chunk of tile memory.
#include <map_memory.h>
Public Member Functions
mm_submap ()=default
mm_submap (bool make_valid)
bool is_empty () const
bool is_valid () const
const memorized_tile & get_tile (const point_sm_ms &p) const
void set_tile (const point_sm_ms &p, const memorized_tile &value)
void serialize (JsonOut &jsout) const
void deserialize (int version, const JsonArray &ja)
Static Public Attributes
static const memorized_tile default_tile = {}
Private Attributes
std::vector< memorized_tile > tiles
bool valid = true
Detailed Description
Represent a submap-sized chunk of tile memory.
Definition at line 54 of file map_memory.h.
Constructor & Destructor Documentation
mm_submap() [1/2]
mm_submap::mm_submap () default
mm_submap() [2/2]
mm_submap::mm_submap (bool make_valid) explicit
Definition at line 43 of file map_memory.cpp.
 : valid( make_valid ) {}
Member Function Documentation
deserialize()
void mm_submap::deserialize (int version, const JsonArray & ja)
Definition at line 3960 of file savegame_json.cpp.
 {
     size_t submap_array_idx = 0;
     // Uses RLE for compression.
     memorized_tile tile;
     size_t remaining = 0;
     for( size_t y = 0; y < SEEY; y++ ) {
         for( size_t x = 0; x < SEEX; x++ ) {
             if( remaining > 0 ) {
                 remaining -= 1;
             } else {
                 const JsonArray ja_tile = ja.get_array( submap_array_idx++ );
                 if( version < 1 ) { // legacy, remove after 0.H comes out
                     std::string id = ja_tile.get_string( 0 );
                     if( string_starts_with( id, "t_" ) ) {
                         tile.set_ter_id( std::move( id ) );
                         tile.set_ter_subtile( ja_tile.get_int( 1 ) );
                         tile.set_ter_rotation( ja_tile.get_int( 2 ) );
                         tile.set_dec_id( "" );
                         tile.set_dec_subtile( 0 );
                         tile.set_dec_rotation( 0 );
                     } else {
                         tile.set_ter_id( "" );
                         tile.set_ter_subtile( 0 );
                         tile.set_ter_rotation( 0 );
                         tile.set_dec_id( std::move( id ) );
                         tile.set_dec_subtile( ja_tile.get_int( 1 ) );
                         const int legacy_rotation = ja_tile.get_int( 2 );
                         if( string_starts_with( tile.dec_id, "vp_" ) ) {
                             // legacy vehicle rotation needs to be converted from 0-360 degrees
                             // to 0-3 tileset rotation
                             const units::angle legacy_angle = units::from_degrees( legacy_rotation );
                             tile.set_dec_rotation( angle_to_dir4( 270_degrees - legacy_angle ) );
                         } else {
                             tile.set_dec_rotation( legacy_rotation );
                         }
                     }
                     tile.symbol = ja_tile.get_int( 3 );
                     if( ja_tile.size() > 4 ) {
                         remaining = ja_tile.get_int( 4 ) - 1;
                     }
                 } else {
                     remaining = ja_tile.get_int( 0 ) - 1;
                     tile.symbol = ja_tile.get_int( 1 );
                     tile.set_ter_id( ja_tile.get_string( 2 ) );
                     tile.ter_subtile = ja_tile.get_int( 3 );
                     tile.ter_rotation = ja_tile.get_int( 4 );
                     if( ja_tile.size() > 5 ) {
                         tile.set_dec_id( ja_tile.get_string( 5 ) );
                         tile.dec_subtile = ja_tile.get_int( 6 );
                         tile.dec_rotation = ja_tile.get_int( 7 );
                     } else {
                         tile.set_dec_id( "" );
                         tile.dec_subtile = 0;
                         tile.dec_rotation = 0;
                     }
                 }
             }
             // Try to avoid assigning to save up on memory
             if( tile != mm_submap::default_tile ) {
                 set_tile( point_sm_ms( x, y ), tile );
             }
         }
     }
 }
References angle_to_dir4(), memorized_tile::dec_id, memorized_tile::dec_rotation, memorized_tile::dec_subtile, default_tile, units::from_degrees(), JsonArray::get_array(), JsonArray::get_int(), JsonArray::get_string(), SEEX, SEEY, memorized_tile::set_dec_id(), memorized_tile::set_dec_rotation(), memorized_tile::set_dec_subtile(), memorized_tile::set_ter_id(), memorized_tile::set_ter_rotation(), memorized_tile::set_ter_subtile(), JsonArray::size(), string_starts_with(), memorized_tile::symbol, memorized_tile::ter_rotation, and memorized_tile::ter_subtile.
get_tile()
const memorized_tile & mm_submap::get_tile (const point_sm_ms & p) const
Definition at line 55 of file map_memory.cpp.
 {
     if( tiles.empty() ) {
         return default_tile;
     }
     return tiles[p.y() * SEEX + p.x()];
 }
References default_tile, SEEX, tiles, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
is_empty()
bool mm_submap::is_empty () const
Definition at line 45 of file map_memory.cpp.
 {
     return tiles.empty();
 }
References tiles.
is_valid()
bool mm_submap::is_valid () const
Definition at line 50 of file map_memory.cpp.
 {
     return valid;
 }
References valid.
serialize()
void mm_submap::serialize (JsonOut & jsout) const
Definition at line 3915 of file savegame_json.cpp.
 {
     jsout.start_array();
     // Uses RLE for compression.
     memorized_tile last;
     int num_same = 1;
     const auto write_seq = [&]() {
         jsout.start_array();
         jsout.write( num_same );
         jsout.write( last.symbol );
         jsout.write( last.ter_id );
         jsout.write( static_cast<int>( last.ter_subtile ) );
         jsout.write( static_cast<int>( last.ter_rotation ) );
         if( !last.get_dec_id().empty() ) {
             jsout.write( last.dec_id );
             jsout.write( static_cast<int>( last.dec_subtile ) );
             jsout.write( static_cast<int>( last.dec_rotation ) );
         }
         jsout.end_array();
     };
     for( size_t y = 0; y < SEEY; y++ ) {
         for( size_t x = 0; x < SEEX; x++ ) {
             const memorized_tile &elem = get_tile( point_sm_ms( x, y ) );
             if( x == 0 && y == 0 ) {
                 last = elem;
                 continue;
             }
             if( last == elem ) {
                 num_same += 1;
                 continue;
             }
             write_seq();
             num_same = 1;
             last = elem;
         }
     }
     write_seq();
     jsout.end_array();
 }
References JsonOut::end_array(), last, SEEX, SEEY, JsonOut::start_array(), and JsonOut::write().
set_tile()
void mm_submap::set_tile (const point_sm_ms & p, const memorized_tile & value)
Definition at line 63 of file map_memory.cpp.
 {
     if( tiles.empty() ) {
         // call 'reserve' first to force allocation of exact size
         tiles.reserve( SEEX * SEEY );
         tiles.resize( SEEX * SEEY, default_tile );
     }
     tiles[p.y() * SEEX + p.x()] = value;
 }
References default_tile, SEEX, SEEY, tiles, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Member Data Documentation
default_tile
const memorized_tile mm_submap::default_tile = {} static
Definition at line 56 of file map_memory.h.
Referenced by vehicle::autodrive_controller::check_drivable(), deserialize(), avatar::get_memorized_tile(), get_tile(), and set_tile().
tiles
std::vector<memorized_tile> mm_submap::tiles private
Definition at line 74 of file map_memory.h.
Referenced by get_tile(), is_empty(), and set_tile().
valid
bool mm_submap::valid = true private
Definition at line 76 of file map_memory.h.
Referenced by is_valid().
The documentation for this struct was generated from the following files:
src/map_memory.h
src/map_memory.cpp
src/savegame_json.cpp