Cataclysm DDA: map_deconstruct_info Struct Reference
map_deconstruct_info Struct Reference
#include <mapdata.h>
Public Member Functions
map_deconstruct_info ()
bool load (const JsonObject &jsobj, std::string_view member, bool is_furniture, const std::string &context)
Public Attributes
bool can_do
bool deconstruct_above
item_group_id drop_group
ter_str_id ter_set
furn_str_id furn_set
std::optional< map_deconstruct_skill > skill
Detailed Description
Definition at line 79 of file mapdata.h.
Constructor & Destructor Documentation
map_deconstruct_info()
map_deconstruct_info::map_deconstruct_info ()
Definition at line 412 of file mapdata.cpp.
                                            : can_do( false ), deconstruct_above( false ),
     ter_set( ter_str_id::NULL_ID() ), furn_set( furn_str_id::NULL_ID() ) {}
Member Function Documentation
load()
bool map_deconstruct_info::load (const JsonObject & jsobj, std::string_view member, bool is_furniture, const std::string & context)
Definition at line 415 of file mapdata.cpp.
 {
     if( !jsobj.has_object( member ) ) {
         return false;
     }
     JsonObject j = jsobj.get_object( member );
     furn_set = furn_str_id( j.get_string( "furn_set", "f_null" ) );
     if( !is_furniture ) {
         ter_set = ter_str_id( j.get_string( "ter_set" ) );
     }
     if( j.has_object( "skill" ) ) {
         JsonObject jo = j.get_object( "skill" );
         skill = { skill_id( jo.get_string( "skill" ) ), jo.get_int( "min", 0 ), jo.get_int( "max", 10 ), jo.get_float( "multiplier", 1.0 ) };
     }
     can_do = true;
     deconstruct_above = j.get_bool( "deconstruct_above", false );
     drop_group = item_group::load_item_group( j.get_member( "items" ), "collection",
                  "map_deconstruct_info for " + context );
     return true;
 }
References can_do, context, deconstruct_above, drop_group, furn_set, furn_str_id, JsonObject::get_bool(), JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_member(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_object(), item_group::load_item_group(), member, skill, skill_id, ter_set, and ter_str_id.
Referenced by ter_t::load(), and furn_t::load().
Member Data Documentation
can_do
bool map_deconstruct_info::can_do
Definition at line 81 of file mapdata.h.
Referenced by jmapgen_terrain::apply(), check_decon_items(), construct::check_deconstruct(), construct::done_deconstruct(), and load().
deconstruct_above
bool map_deconstruct_info::deconstruct_above
Definition at line 83 of file mapdata.h.
Referenced by construct::done_deconstruct(), and load().
drop_group
item_group_id map_deconstruct_info::drop_group
Definition at line 85 of file mapdata.h.
Referenced by jmapgen_terrain::apply(), check_decon_items(), construct::done_deconstruct(), and load().
furn_set
furn_str_id map_deconstruct_info::furn_set
Definition at line 87 of file mapdata.h.
Referenced by jmapgen_terrain::apply(), check_decon_items(), construct::done_deconstruct(), and load().
skill
std::optional<map_deconstruct_skill> map_deconstruct_info::skill
Definition at line 89 of file mapdata.h.
Referenced by construct::done_deconstruct(), and load().
ter_set
ter_str_id map_deconstruct_info::ter_set
Definition at line 86 of file mapdata.h.
Referenced by check_decon_items(), construct::done_deconstruct(), and load().
The documentation for this struct was generated from the following files:
src/mapdata.h
src/mapdata.cpp