Cataclysm DDA: coord_transformation Struct Reference
coord_transformation Struct Reference
Public Member Functions
point transform (const point &p) const
tripoint transform (const point &p, int z) const
orientation transform (orientation dir) const
node_address transform (const point &p, orientation dir) const
coord_transformation inverse () const
Public Attributes
point pre_offset
quad_rotation rotation
point post_offset
Detailed Description
Definition at line 248 of file vehicle_autodrive.cpp.
Member Function Documentation
inverse()
coord_transformation coord_transformation::inverse () const
Definition at line 592 of file vehicle_autodrive.cpp.
 {
     return { post_offset, -rotation, pre_offset };
 }
References post_offset, pre_offset, and rotation.
Referenced by vehicle::get_debug_overlay_data(), and auto_navigation_data::to_view().
transform() [1/4]
point coord_transformation::transform (const point & p) const
Definition at line 572 of file vehicle_autodrive.cpp.
 {
     return rotate( p - pre_offset, rotation ) + post_offset;
 }
References post_offset, pre_offset, rotate(), and rotation.
Referenced by vehicle::autodrive_controller::compute_goal_zone(), vehicle::autodrive_controller::compute_valid_positions(), vehicle::get_debug_overlay_data(), auto_navigation_data::to_view(), and transform().
transform() [2/4]
tripoint coord_transformation::transform (const point & p, int z) const
Definition at line 577 of file vehicle_autodrive.cpp.
 {
     return tripoint( transform( p ), z );
 }
References transform(), and tripoint.
transform() [3/4]
node_address coord_transformation::transform (const point & p, orientation dir) const
Definition at line 587 of file vehicle_autodrive.cpp.
 {
     return make_node_address( transform( p ), transform( dir ) );
 }
References make_node_address(), and transform().
transform() [4/4]
orientation coord_transformation::transform (orientation dir) const
Definition at line 582 of file vehicle_autodrive.cpp.
 {
     return dir + rotation;
 }
References rotation.
Member Data Documentation
post_offset
point coord_transformation::post_offset
Definition at line 251 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_coordinates(), inverse(), and transform().
pre_offset
point coord_transformation::pre_offset
Definition at line 249 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_coordinates(), inverse(), and transform().
rotation
quad_rotation coord_transformation::rotation
Definition at line 250 of file vehicle_autodrive.cpp.
Referenced by inverse(), and transform().
The documentation for this struct was generated from the following file:
src/vehicle_autodrive.cpp