Cataclysm DDA: mutable_overmap_placement_rule Struct Reference
mutable_overmap_placement_rule Struct Reference
Public Member Functions
std::string description () const
void finalize (const std::string &context, const std::unordered_map< std::string, mutable_overmap_terrain > &special_overmaps)
void check (const std::string &context) const
mutable_overmap_placement_rule_remainder realise () const
void deserialize (const JsonObject &jo)
Public Attributes
std::string name
std::vector< mutable_overmap_placement_rule_piece > pieces
std::vector< std::pair< rel_pos_dir, const mutable_overmap_terrain_join * > > outward_joins
int_distribution max = int_distribution(INT_MAX)
int weight = INT_MAX
Detailed Description
Definition at line 1651 of file overmap.cpp.
Member Function Documentation
check()
void mutable_overmap_placement_rule::check (const std::string & context) const inline
Definition at line 1729 of file overmap.cpp.
{
         if( pieces.empty() ) {
             cata_fatal( "phase of %s has chunk with zero pieces" );
         }
         int min_max = max.minimum();
         if( min_max < 0 ) {
             debugmsg( "phase of %s specifies max which might be as low as %d; this should "
                       "be a positive number", context, min_max );
         }
     }
References cata_fatal, context, debugmsg, max, int_distribution::minimum(), and pieces.
Referenced by mutable_overmap_special_data::check().
description()
std::string mutable_overmap_placement_rule::description () const inline
Definition at line 1659 of file overmap.cpp.
{
         if( !name.empty() ) {
             return name;
         }
         std::string first_om_id = pieces[0].overmap_id;
         if( pieces.size() == 1 ) {
             return first_om_id;
         } else {
             return "chunk using overmap " + first_om_id;
         }
     }
References name, and pieces.
Referenced by mutable_overmap_placement_rule_remainder::description(), and finalize().
deserialize()
void mutable_overmap_placement_rule::deserialize (const JsonObject & jo) inline
Definition at line 1742 of file overmap.cpp.
{
         jo.read( "name", name );
         if( jo.has_member( "overmap" ) ) {
             pieces.emplace_back();
             jo.read( "overmap", pieces.back().overmap_id, true );
         } else if( jo.has_member( "chunk" ) ) {
             jo.read( "chunk", pieces );
         } else {
             jo.throw_error( R"(placement rule must specify at least one of "overmap" or "chunk")" );
         }
         jo.read( "max", max );
         jo.read( "weight", weight );
         if( !jo.has_member( "max" ) && weight == INT_MAX ) {
             jo.throw_error( R"(placement rule must specify at least one of "max" or "weight")" );
         }
     }
References JsonObject::has_member(), max, name, pieces, JsonObject::read(), JsonObject::throw_error(), and weight.
finalize()
void mutable_overmap_placement_rule::finalize (const std::string & context, const std::unordered_map< std::string, mutable_overmap_terrain > & special_overmaps) inline
Definition at line 1671 of file overmap.cpp.
                    {
         std::unordered_map<tripoint_rel_omt, const mutable_overmap_placement_rule_piece *>
         pieces_by_pos;
         for( mutable_overmap_placement_rule_piece &piece : pieces ) {
             bool inserted = pieces_by_pos.emplace( piece.pos, &piece ).second;
             if( !inserted ) {
                 debugmsg( "phase of %s has chunk with duplicated position %s",
                           context, piece.pos.to_string() );
             }
             auto it = special_overmaps.find( piece.overmap_id );
             if( it == special_overmaps.end() ) {
                 cata_fatal( "phase of %s specifies overmap %s which is not defined for that "
                             "special", context, piece.overmap_id );
             } else {
                 piece.overmap = &it->second;
             }
         }
         for( const mutable_overmap_placement_rule_piece &piece : pieces ) {
             const mutable_overmap_terrain &ter = *piece.overmap;
             for( const join_map::value_type &p : ter.joins ) {
                 const cube_direction dir = p.first;
                 const mutable_overmap_terrain_join &ter_join = p.second;
                 rel_pos_dir this_side{ piece.pos, dir + piece.rot };
                 rel_pos_dir other_side = this_side.opposite();
                 auto opposite_piece = pieces_by_pos.find( other_side.p );
                 if( opposite_piece == pieces_by_pos.end() ) {
                     outward_joins.emplace_back( this_side, &ter_join );
                 } else {
                     const std::string &opposite_join = ter_join.join->opposite_id;
                     const mutable_overmap_placement_rule_piece &other_piece =
                         *opposite_piece->second;
                     const mutable_overmap_terrain &other_om = *other_piece.overmap;
                     auto opposite_om_join =
                         other_om.joins.find( other_side.dir - other_piece.rot );
                     if( opposite_om_join == other_om.joins.end() ) {
                         debugmsg( "in phase of %s, %s has adjacent pieces %s at %s and %s at "
                                   "%s where the former has a join %s pointed towards the latter, "
                                   "but the latter has no join pointed towards the former",
                                   context, description(), piece.overmap_id, piece.pos.to_string(),
                                   other_piece.overmap_id, other_piece.pos.to_string(),
                                   ter_join.join_id );
                     } else if( opposite_om_join->second.join_id != opposite_join ) {
                         debugmsg( "in phase of %s, %s has adjacent pieces %s at %s and %s at "
                                   "%s where the former has a join %s pointed towards the latter, "
                                   "expecting a matching join %s whereas the latter has the join %s "
                                   "pointed towards the former",
                                   context, description(), piece.overmap_id, piece.pos.to_string(),
                                   other_piece.overmap_id, other_piece.pos.to_string(),
                                   ter_join.join_id, opposite_join,
                                   opposite_om_join->second.join_id );
                     }
                 }
             }
         }
     }
References cata_fatal, context, debugmsg, description(), pos_dir< Tripoint >::dir, mutable_overmap_terrain_join::join, mutable_overmap_terrain_join::join_id, mutable_overmap_terrain::joins, pos_dir< Tripoint >::opposite(), mutable_overmap_join::opposite_id, outward_joins, mutable_overmap_placement_rule_piece::overmap, mutable_overmap_placement_rule_piece::overmap_id, pos_dir< Tripoint >::p, pieces, mutable_overmap_placement_rule_piece::pos, mutable_overmap_placement_rule_piece::rot, and coords::coord_point_base< Point >::to_string().
Referenced by mutable_overmap_special_data::finalize().
realise()
mutable_overmap_placement_rule_remainder mutable_overmap_placement_rule::realise () const
Definition at line 1810 of file overmap.cpp.
 {
     return mutable_overmap_placement_rule_remainder{ this, max.sample(), weight };
 }
References max, int_distribution::sample(), and weight.
Member Data Documentation
max
int_distribution mutable_overmap_placement_rule::max = int_distribution(INT_MAX)
Definition at line 1656 of file overmap.cpp.
Referenced by check(), deserialize(), and realise().
name
std::string mutable_overmap_placement_rule::name
Definition at line 1652 of file overmap.cpp.
Referenced by description(), and deserialize().
outward_joins
std::vector<std::pair<rel_pos_dir, const mutable_overmap_terrain_join *> > mutable_overmap_placement_rule::outward_joins
Definition at line 1655 of file overmap.cpp.
Referenced by finalize(), and mutable_overmap_placement_rule_remainder::outward_joins().
pieces
std::vector<mutable_overmap_placement_rule_piece> mutable_overmap_placement_rule::pieces
Definition at line 1653 of file overmap.cpp.
Referenced by check(), description(), deserialize(), finalize(), mutable_overmap_placement_rule_remainder::pieces(), and mutable_overmap_placement_rule_remainder::positions().
weight
int mutable_overmap_placement_rule::weight = INT_MAX
Definition at line 1657 of file overmap.cpp.
Referenced by deserialize(), and realise().
The documentation for this struct was generated from the following file:
src/overmap.cpp