Cataclysm DDA: mm_region Struct Reference
mm_region Struct Reference
Represents a square of mm_submaps.
#include <map_memory.h>
Public Member Functions
mm_region ()
bool is_empty () const
void serialize (JsonOut &jsout) const
void deserialize (const JsonValue &ja)
Public Attributes
cata::mdarray< shared_ptr_fast< mm_submap >, point, MM_REG_SIZE, MM_REG_SIZE > submaps
Detailed Description
Represents a square of mm_submaps.
For faster save/load, submaps are collected into regions and each region is saved in its own file.
Definition at line 84 of file map_memory.h.
Constructor & Destructor Documentation
mm_region()
mm_region::mm_region ()
Definition at line 73 of file map_memory.cpp.
 : submaps( nullptr ) {}
Member Function Documentation
deserialize()
void mm_region::deserialize (const JsonValue & ja)
Definition at line 4050 of file savegame_json.cpp.
 {
     int version;
     JsonArray region_json;
     if( ja.test_array() ) { // legacy, remove after 0.H comes out
         version = 0;
         region_json = ja;
     } else {
         JsonObject region_obj = ja;
         version = region_obj.get_int( "version" );
         region_json = region_obj.get_array( "data" );
     }
     for( size_t y = 0; y < MM_REG_SIZE; y++ ) {
         // NOLINTNEXTLINE(modernize-loop-convert)
         for( size_t x = 0; x < MM_REG_SIZE; x++ ) {
             shared_ptr_fast<mm_submap> &sm = submaps[x][y];
             sm = make_shared_fast<mm_submap>();
             const JsonValue jsin = region_json.next_value();
             if( !jsin.test_null() ) {
                 sm->deserialize( version, jsin );
             }
         }
     }
 }
References JsonObject::get_array(), JsonObject::get_int(), MM_REG_SIZE, JsonArray::next_value(), coords::sm, JsonValue::test_array(), and JsonValue::test_null().
Referenced by map_memory::load_submap().
is_empty()
bool mm_region::is_empty () const
Definition at line 75 of file map_memory.cpp.
 {
     for( size_t y = 0; y < MM_REG_SIZE; y++ ) {
         // NOLINTNEXTLINE(modernize-loop-convert)
         for( size_t x  = 0; x < MM_REG_SIZE; x++ ) {
             if( !submaps[x][y]->is_empty() ) {
                 return false;
             }
         }
     }
     return true;
 }
References MM_REG_SIZE, and submaps.
Referenced by map_memory::save().
serialize()
void mm_region::serialize (JsonOut & jsout) const
Definition at line 4028 of file savegame_json.cpp.
 {
     jsout.start_object();
     jsout.member( "version", 1 );
     jsout.write( "data" );
     jsout.write_member_separator();
     jsout.start_array();
     for( size_t y = 0; y < MM_REG_SIZE; y++ ) {
         // NOLINTNEXTLINE(modernize-loop-convert)
         for( size_t x = 0; x < MM_REG_SIZE; x++ ) {
             const shared_ptr_fast<mm_submap> &sm = submaps[x][y];
             if( sm->is_empty() ) {
                 jsout.write_null();
             } else {
                 sm->serialize( jsout );
             }
         }
     }
     jsout.end_array();
     jsout.end_object();
 }
References JsonOut::end_array(), JsonOut::end_object(), JsonOut::member(), MM_REG_SIZE, coords::sm, JsonOut::start_array(), JsonOut::start_object(), JsonOut::write(), JsonOut::write_member_separator(), and JsonOut::write_null().
Referenced by map_memory::save().
Member Data Documentation
submaps
cata::mdarray<shared_ptr_fast<mm_submap>, point, MM_REG_SIZE, MM_REG_SIZE> mm_region::submaps
Definition at line 85 of file map_memory.h.
Referenced by is_empty(), map_memory::load_submap(), and map_memory::save().
The documentation for this struct was generated from the following files:
src/map_memory.h
src/map_memory.cpp
src/savegame_json.cpp