Cataclysm DDA: furn_t Struct Reference
furn_t Struct Reference
#include <mapdata.h>
Public Member Functions
const itype * crafting_pseudo_item_type () const
std::vector< const itype * > crafting_ammo_item_types () const
furn_t ()
bool is_movable () const
void load (const JsonObject &jo, const std::string &src) override
void check () const override
Public Member Functions inherited from map_data_common_t
virtual ~map_data_common_t ()=default
bool has_curtains () const
std::string name () const
bool can_examine (const tripoint &examp) const
bool has_examine (iexamine_examine_function func) const
bool has_examine (const std::string &action) const
void set_examine (iexamine_functions func)
void examine (Character &, const tripoint &) const
void load_symbol (const JsonObject &jo, const std::string &context)
const std::set< std::string > & get_flags () const
bool has_flag (const std::string &flag) const
bool has_flag (const ter_furn_flag flag) const
void extraprocess_flags (ter_furn_flag flag)
void set_flag (const std::string &flag)
void set_flag (ter_furn_flag flag)
void set_connect_groups (const std::vector< std::string > &connect_groups_vec)
void set_connects_to (const std::vector< std::string > &connect_groups_vec)
void set_rotates_to (const std::vector< std::string > &connect_groups_vec)
void set_groups (std::bitset< NUM_TERCONN > &bits, const std::vector< std::string > &connect_groups_vec)
bool in_connect_groups (const std::bitset< NUM_TERCONN > &test_connect_group) const
int symbol () const
nc_color color () const
const harvest_id & get_harvest () const
const std::set< std::string > & get_harvest_names () const
Returns a set of names of the items that would be dropped.
std::string extended_description () const
bool is_flammable () const
Static Public Member Functions
static size_t count ()
Public Attributes
std::vector< std::pair< furn_str_id, mod_id > > src
furn_str_id id
furn_str_id open
furn_str_id close
furn_str_id lockpick_result
translation lockpick_message
itype_id crafting_pseudo_item
units::volume keg_capacity = 0_ml
std::set< emit_id > emissions
Emissions of furniture.
units::temperature_delta bonus_fire_warmth_feet = 0.6_C_delta
itype_id deployed_item
int move_str_req = 0
cata::value_ptr< activity_data_furn > boltcut
cata::value_ptr< activity_data_furn > hacksaw
cata::value_ptr< activity_data_furn > oxytorch
cata::value_ptr< activity_data_furn > prying
cata::value_ptr< furn_workbench_info > workbench
cata::value_ptr< plant_data > plant
cata::value_ptr< float > surgery_skill_multiplier
Public Attributes inherited from map_data_common_t
map_bash_info bash
map_deconstruct_info deconstruct
cata::value_ptr< map_shoot_info > shoot
ter_str_id curtain_transform
std::array< int, NUM_SEASONS > symbol_
int light_emitted = 0
int movecost = 0
int heat_radiation = 0
int coverage = 0
units::temperature_delta floor_bedding_warmth = 0_C_delta
int comfort = 0
units::volume max_volume = DEFAULT_TILE_VOLUME
translation description
std::array< nc_color, NUM_SEASONS > color_
std::string looks_like
std::array< harvest_id, NUM_SEASONS > harvest_by_season
When will this terrain/furniture get harvested and what will drop? Note: This excludes items that take extra tools to harvest.
bool transparent = false
std::bitset< NUM_TERCONN > connect_groups
std::bitset< NUM_TERCONN > connect_to_groups
std::bitset< NUM_TERCONN > rotate_to_groups
bool was_loaded = false
Additional Inherited Members
Protected Attributes inherited from map_data_common_t
translation name_
iexamine_functions examine_func
cata::clone_ptr< iexamine_actor > examine_actor
Detailed Description
Definition at line 641 of file mapdata.h.
Constructor & Destructor Documentation
furn_t()
furn_t::furn_t ()
Definition at line 1033 of file mapdata.cpp.
 : open( furn_str_id::NULL_ID() ), close( furn_str_id::NULL_ID() ) {}
Member Function Documentation
check()
void furn_t::check () const override virtual
Reimplemented from map_data_common_t.
Definition at line 1131 of file mapdata.cpp.
 {
     map_data_common_t::check();
     check_bash_items( bash, id.str(), false );
     check_decon_items( deconstruct, id.str(), false );
     if( !open.is_valid() ) {
         debugmsg( "invalid furniture %s for opening %s", open.c_str(), id.c_str() );
     }
     if( !close.is_valid() ) {
         debugmsg( "invalid furniture %s for closing %s", close.c_str(), id.c_str() );
     }
     for( const emit_id &e : emissions ) {
         if( !e.is_valid() ) {
             debugmsg( "furn %s has invalid emission %s set", id.c_str(),
                       e.str().c_str() );
         }
     }
 }
References map_data_common_t::bash, string_id< T >::c_str(), map_data_common_t::check(), check_bash_items(), check_decon_items(), close, debugmsg, map_data_common_t::deconstruct, emissions, string_id< T >::is_valid(), and open.
count()
size_t furn_t::count () static
Definition at line 1035 of file mapdata.cpp.
 {
     return furniture_data.size();
 }
References anonymous_namespace{mapdata.cpp}::furniture_data.
crafting_ammo_item_types()
std::vector< const itype * > furn_t::crafting_ammo_item_types () const
Definition at line 4684 of file iexamine.cpp.
 {
     const itype *pseudo = crafting_pseudo_item_type();
     std::vector<const itype *> output;
     if( pseudo && pseudo->tool && !pseudo->tool->ammo_id.empty() ) {
         for( const ammotype &atype : pseudo->tool->ammo_id ) {
             const itype *itype = item::find_type( atype->default_ammotype() );
             if( itype != nullptr ) {
                 output.push_back( itype );
             }
         }
     }
     return output;
 }
References crafting_pseudo_item_type(), ammunition_type::default_ammotype(), item::find_type(), and itype::tool.
Referenced by inventory::form_from_map(), reload_furniture(), iexamine::smoker_options(), and use_charges_from_furn().
crafting_pseudo_item_type()
const itype * furn_t::crafting_pseudo_item_type () const
Definition at line 4676 of file iexamine.cpp.
 {
     if( crafting_pseudo_item.is_empty() ) {
         return nullptr;
     }
     return item::find_type( crafting_pseudo_item );
 }
References crafting_pseudo_item, item::find_type(), and string_id< T >::is_empty().
Referenced by crafting_ammo_item_types(), reload_furniture(), iexamine::smoker_options(), and use_charges_from_furn().
is_movable()
bool furn_t::is_movable () const
Definition at line 1040 of file mapdata.cpp.
 {
     return move_str_req >= 0;
 }
References move_str_req.
Referenced by board_up(), map::drop_furniture(), map::furn_set(), and grab().
load()
void furn_t::load (const JsonObject & jo, const std::string & src) override virtual
Reimplemented from map_data_common_t.
Definition at line 1045 of file mapdata.cpp.
 {
     map_data_common_t::load( jo, src );
     mandatory( jo, was_loaded, "name", name_ );
     mandatory( jo, was_loaded, "move_cost_mod", movecost );
     optional( jo, was_loaded, "coverage", coverage );
     optional( jo, was_loaded, "comfort", comfort, 0 );
     int legacy_floor_bedding_warmth = units::to_legacy_bodypart_temp_delta( floor_bedding_warmth );
     optional( jo, was_loaded, "floor_bedding_warmth", legacy_floor_bedding_warmth, 0 );
     floor_bedding_warmth = units::from_legacy_bodypart_temp_delta( legacy_floor_bedding_warmth );
     optional( jo, was_loaded, "emissions", emissions );
     int legacy_bonus_fire_warmth_feet = units::to_legacy_bodypart_temp_delta( bonus_fire_warmth_feet );
     optional( jo, was_loaded, "bonus_fire_warmth_feet", legacy_bonus_fire_warmth_feet, 300 );
     bonus_fire_warmth_feet = units::from_legacy_bodypart_temp_delta( legacy_bonus_fire_warmth_feet );
     optional( jo, was_loaded, "keg_capacity", keg_capacity, legacy_volume_reader, 0_ml );
     mandatory( jo, was_loaded, "required_str", move_str_req );
     optional( jo, was_loaded, "max_volume", max_volume, volume_reader(), DEFAULT_TILE_VOLUME );
     optional( jo, was_loaded, "crafting_pseudo_item", crafting_pseudo_item, itype_id() );
     optional( jo, was_loaded, "deployed_item", deployed_item );
     load_symbol( jo, "furniture " + id.str() );
     transparent = false;
     optional( jo, was_loaded, "light_emitted", light_emitted );
     // see the comment in ter_id::load for connect_group handling
     connect_groups.reset();
     connect_to_groups.reset();
     rotate_to_groups.reset();
     for( auto &flag : jo.get_string_array( "flags" ) ) {
         set_flag( flag );
     }
     if( jo.has_member( "connect_groups" ) ) {
         set_connect_groups( jo.get_as_string_array( "connect_groups" ) );
     }
     if( jo.has_member( "connects_to" ) ) {
         set_connects_to( jo.get_as_string_array( "connects_to" ) );
     }
     if( jo.has_member( "rotates_to" ) ) {
         set_rotates_to( jo.get_as_string_array( "rotates_to" ) );
     }
     optional( jo, was_loaded, "open", open, string_id_reader<furn_t> {}, furn_str_id::NULL_ID() );
     optional( jo, was_loaded, "close", close, string_id_reader<furn_t> {}, furn_str_id::NULL_ID() );
     optional( jo, was_loaded, "lockpick_result", lockpick_result, string_id_reader<furn_t> {},
               furn_str_id::NULL_ID() );
     optional( jo, was_loaded, "lockpick_message", lockpick_message, translation() );
     oxytorch = cata::make_value<activity_data_furn>();
     if( jo.has_object( "oxytorch" ) ) {
         oxytorch->load( jo.get_object( "oxytorch" ) );
     }
     boltcut = cata::make_value<activity_data_furn>();
     if( jo.has_object( "boltcut" ) ) {
         boltcut->load( jo.get_object( "boltcut" ) );
     }
     hacksaw = cata::make_value<activity_data_furn>();
     if( jo.has_object( "hacksaw" ) ) {
         hacksaw->load( jo.get_object( "hacksaw" ) );
     }
     prying = cata::make_value<activity_data_furn>();
     if( jo.has_object( "prying" ) ) {
         prying->load( jo.get_object( "prying" ) );
     }
     bash.load( jo, "bash", map_bash_info::furniture, "furniture " + id.str() );
     deconstruct.load( jo, "deconstruct", true, "furniture " + id.str() );
     if( jo.has_object( "workbench" ) ) {
         workbench = cata::make_value<furn_workbench_info>();
         workbench->load( jo, "workbench" );
     }
     if( jo.has_object( "plant_data" ) ) {
         plant = cata::make_value<plant_data>();
         plant->load( jo, "plant_data" );
     }
     if( jo.has_float( "surgery_skill_multiplier" ) ) {
         surgery_skill_multiplier = cata::make_value<float>( jo.get_float( "surgery_skill_multiplier" ) );
     }
 }
References map_data_common_t::bash, boltcut, bonus_fire_warmth_feet, close, map_data_common_t::comfort, map_data_common_t::connect_groups, map_data_common_t::connect_to_groups, map_data_common_t::coverage, crafting_pseudo_item, map_data_common_t::deconstruct, DEFAULT_TILE_VOLUME, deployed_item, emissions, map_data_common_t::floor_bedding_warmth, units::from_legacy_bodypart_temp_delta(), map_bash_info::furniture, JsonObject::get_as_string_array(), JsonObject::get_float(), JsonObject::get_object(), JsonObject::get_string_array(), hacksaw, JsonObject::has_float(), JsonObject::has_member(), JsonObject::has_object(), itype_id, keg_capacity, legacy_volume_reader(), map_data_common_t::light_emitted, map_data_common_t::load(), map_deconstruct_info::load(), map_bash_info::load(), map_data_common_t::load_symbol(), lockpick_message, lockpick_result, mandatory, map_data_common_t::max_volume, move_str_req, map_data_common_t::movecost, map_data_common_t::name_, string_id< furn_t >::NULL_ID(), open, optional(), oxytorch, plant, prying, map_data_common_t::rotate_to_groups, map_data_common_t::set_connect_groups(), map_data_common_t::set_connects_to(), map_data_common_t::set_flag(), map_data_common_t::set_rotates_to(), src, surgery_skill_multiplier, units::to_legacy_bodypart_temp_delta(), map_data_common_t::transparent, map_data_common_t::was_loaded, and workbench.
Member Data Documentation
boltcut
cata::value_ptr<activity_data_furn> furn_t::boltcut
Definition at line 660 of file mapdata.h.
Referenced by iuse::boltcutters(), boltcutting_activity_actor::finish(), load(), and boltcutting_activity_actor::start().
bonus_fire_warmth_feet
units::temperature_delta furn_t::bonus_fire_warmth_feet = 0.6_C_delta
Definition at line 655 of file mapdata.h.
Referenced by load(), and Character::update_bodytemp().
close
furn_str_id furn_t::close
Definition at line 647 of file mapdata.h.
Referenced by check(), and load().
crafting_pseudo_item
itype_id furn_t::crafting_pseudo_item
Definition at line 650 of file mapdata.h.
Referenced by construction_menu(), crafting_pseudo_item_type(), inventory::form_from_map(), furniture_qualities_string(), deploy_furn_actor::info(), load(), game::print_furniture_info(), and basecamp::scan_pseudo_items().
deployed_item
itype_id furn_t::deployed_item
Definition at line 656 of file mapdata.h.
Referenced by iexamine::deployed_furniture(), iexamine::fireplace(), load(), and iexamine::workbench_internal().
emissions
std::set<emit_id> furn_t::emissions
Emissions of furniture.
Definition at line 653 of file mapdata.h.
Referenced by check(), map::furn_set(), and load().
hacksaw
cata::value_ptr<activity_data_furn> furn_t::hacksaw
Definition at line 661 of file mapdata.h.
Referenced by hacksaw_activity_actor::finish(), iuse::hacksaw(), load(), and hacksaw_activity_actor::start().
id
furn_str_id furn_t::id
Definition at line 645 of file mapdata.h.
Referenced by apply< furn_t >(), map::bash_ter_furn(), check_furn(), map::draw_maptile(), map::ledge_coverage(), submap::load(), ter_furn_transform::transform(), and editmap::update_view_with_help().
keg_capacity
units::volume furn_t::keg_capacity = 0_ml
Definition at line 651 of file mapdata.h.
Referenced by get_keg_capacity(), and load().
lockpick_message
translation furn_t::lockpick_message
Definition at line 649 of file mapdata.h.
Referenced by lockpick_activity_actor::finish(), and load().
lockpick_result
furn_str_id furn_t::lockpick_result
Definition at line 648 of file mapdata.h.
Referenced by lockpick_activity_actor::finish(), and load().
move_str_req
int furn_t::move_str_req = 0
Definition at line 658 of file mapdata.h.
Referenced by board_up(), map::can_move_furniture(), map::drop_furniture(), game::grabbed_furn_move(), game::grabbed_furn_move_time(), is_movable(), load(), and editmap::update_view_with_help().
open
furn_str_id furn_t::open
Definition at line 646 of file mapdata.h.
Referenced by check(), and load().
oxytorch
cata::value_ptr<activity_data_furn> furn_t::oxytorch
Definition at line 662 of file mapdata.h.
Referenced by oxytorch_activity_actor::finish(), load(), iuse::oxytorch(), and oxytorch_activity_actor::start().
plant
cata::value_ptr<plant_data> furn_t::plant
Definition at line 667 of file mapdata.h.
Referenced by iexamine::clear_overgrown(), mattack::eat_crop(), farm_action(), talk_function::field_harvest(), map::grow_plant(), iexamine::harvest_plant(), load(), and activity_handlers::plant_seed_finish().
prying
cata::value_ptr<activity_data_furn> furn_t::prying
Definition at line 663 of file mapdata.h.
Referenced by iuse::crowbar(), prying_activity_actor::handle_prying(), prying_activity_actor::handle_prying_nails(), load(), iexamine::locked_object(), and prying_activity_actor::start().
src
std::vector<std::pair<furn_str_id, mod_id> > furn_t::src
Definition at line 643 of file mapdata.h.
Referenced by game::extended_description(), and load().
surgery_skill_multiplier
cata::value_ptr<float> furn_t::surgery_skill_multiplier
Definition at line 669 of file mapdata.h.
Referenced by Character::env_surgery_bonus(), and load().
workbench
cata::value_ptr<furn_workbench_info> furn_t::workbench
Definition at line 665 of file mapdata.h.
Referenced by deploy_furn_actor::info(), load(), place_craft_or_disassembly(), route_best_workbench(), and Character::workbench_crafting_speed_multiplier().
The documentation for this struct was generated from the following files:
src/mapdata.h
src/iexamine.cpp
src/mapdata.cpp