Cataclysm DDA: mutable_overmap_special_data Struct Reference
mutable_overmap_special_data Struct Reference
Public Member Functions
mutable_overmap_special_data (const overmap_special_id &p_id)
void finalize (const std::string &context, const cata::flat_set< string_id< overmap_location >> &default_locations) override
void finalize_mapgen_parameters (mapgen_parameters &params, const std::string &context) const override
void check (const std::string &context) const override
overmap_special_terrain root_as_overmap_special_terrain () const
std::vector< overmap_special_terrain > preview_terrains () const override
std::vector< overmap_special_locations > required_locations () const override
int score_rotation_at (const overmap &, const tripoint_om_omt &, om_direction::type) const override
special_placement_result place (overmap &om, const tripoint_om_omt &origin, om_direction::type dir, bool, const city &cit, bool must_be_unexplored) const override
Public Member Functions inherited from overmap_special_data
virtual ~overmap_special_data ()=default
Public Attributes
overmap_special_id parent_id
std::vector< overmap_special_locations > check_for_locations
std::vector< overmap_special_locations > check_for_locations_area
std::vector< mutable_overmap_join > joins_vec
std::unordered_map< std::string, mutable_overmap_join * > joins
std::unordered_map< std::string, mutable_overmap_terrain > overmaps
std::string root
std::vector< mutable_overmap_phase > phases
Detailed Description
Definition at line 2388 of file overmap.cpp.
Constructor & Destructor Documentation
mutable_overmap_special_data()
mutable_overmap_special_data::mutable_overmap_special_data (const overmap_special_id & p_id) inline explicit
Definition at line 2398 of file overmap.cpp.
         : parent_id( p_id )
     {}
Member Function Documentation
check()
void mutable_overmap_special_data::check (const std::string & context) const inline override virtual
Implements overmap_special_data.
Definition at line 2449 of file overmap.cpp.
{
         if( joins_vec.size() != joins.size() ) {
             debugmsg( "duplicate join id in %s", context );
         }
         for( const mutable_overmap_join &join : joins_vec ) {
             if( join.opposite ) {
                 if( join.opposite->opposite_id != join.id ) {
                     debugmsg( "in %1$s: join id %2$s specifies its opposite to be %3$s, but "
                               "the opposite of %3$s is %4$s, when it should match the "
                               "original id %2$s",
                               context, join.id, join.opposite_id, join.opposite->opposite_id );
                 }
             } else {
                 debugmsg( "in %s: join id '%s' specified as opposite of '%s' not valid",
                           context, join.opposite_id, join.id );
             }
         }
         for( const std::pair<const std::string, mutable_overmap_terrain> &p : overmaps ) {
             const mutable_overmap_terrain &ter = p.second;
             ter.check( string_format( "overmap %s in %s", p.first, context ) );
         }
         if( !overmaps.count( root ) ) {
             debugmsg( "root %s is not amongst the defined overmaps for %s", root, context );
         }
         for( const mutable_overmap_phase &phase : phases ) {
             for( const mutable_overmap_placement_rule &rule : phase.rules ) {
                 rule.check( context );
             }
         }
     }
References mutable_overmap_terrain::check(), mutable_overmap_placement_rule::check(), context, debugmsg, and string_format().
finalize()
void mutable_overmap_special_data::finalize (const std::string & context, const cata::flat_set< string_id< overmap_location >> & default_locations) inline override virtual
Implements overmap_special_data.
Definition at line 2402 of file overmap.cpp.
{
         if( check_for_locations.empty() ) {
             check_for_locations.push_back( root_as_overmap_special_terrain() );
         }
         for( size_t i = 0; i != joins_vec.size(); ++i ) {
             mutable_overmap_join &join = joins_vec[i];
             if( join.into_locations.empty() ) {
                 join.into_locations = default_locations;
             }
             join.priority = i;
             joins.emplace( join.id, &join );
         }
         for( mutable_overmap_join &join : joins_vec ) {
             if( join.opposite_id.empty() ) {
                 join.opposite_id = join.id;
                 join.opposite = &join;
                 continue;
             }
             auto opposite_it = joins.find( join.opposite_id );
             if( opposite_it == joins.end() ) {
                 // Error reported later in check()
                 continue;
             }
             join.opposite = opposite_it->second;
         }
         for( std::pair<const std::string, mutable_overmap_terrain> &p : overmaps ) {
             mutable_overmap_terrain &ter = p.second;
             ter.finalize( string_format( "overmap %s in %s", p.first, context ), joins,
                           default_locations );
         }
         for( mutable_overmap_phase &phase : phases ) {
             for( mutable_overmap_placement_rule &rule : phase.rules ) {
                 rule.finalize( context, overmaps );
             }
         }
     }
References context, mutable_overmap_terrain::finalize(), mutable_overmap_placement_rule::finalize(), mutable_overmap_join::id, mutable_overmap_join::into_locations, mutable_overmap_join::priority, and string_format().
finalize_mapgen_parameters()
void mutable_overmap_special_data::finalize_mapgen_parameters (mapgen_parameters & params, const std::string & context) const inline override virtual
Implements overmap_special_data.
Definition at line 2440 of file overmap.cpp.
{
         for( const std::pair<const std::string, mutable_overmap_terrain> &p : overmaps ) {
             const mutable_overmap_terrain &t = p.second;
             std::string mapgen_id = t.terrain->get_mapgen_id();
             params.check_and_merge( get_map_special_params( mapgen_id ), context );
         }
     }
References mapgen_parameters::check_and_merge(), context, get_map_special_params(), oter_t::get_mapgen_id(), and mutable_overmap_terrain::terrain.
place()
special_placement_result mutable_overmap_special_data::place (overmap & om, const tripoint_om_omt & origin, om_direction::type dir, bool , const city & cit, bool must_be_unexplored) const inline override virtual
Implements overmap_special_data.
Definition at line 2507 of file overmap.cpp.
{
         // TODO: respect must_be_unexplored
         std::vector<tripoint_om_omt> result;
         auto it = overmaps.find( root );
         if( it == overmaps.end() ) {
             debugmsg( "Invalid root %s", root );
             return { result, {} };
         }
         joins_tracker unresolved;
         struct placed_connection {
             overmap_connection_id connection;
             pos_dir<tripoint_om_omt> where;
         };
         std::vector<placed_connection> connections_placed;
         // This is for debugging only, it tracks a human-readable description
         // of what happened to be put in the debugmsg in the event of failure.
         std::vector<std::string> descriptions;
         // Helper function to add a particular mutable_overmap_terrain at a
         // particular place.
         auto add_ter = [&](
                            const mutable_overmap_terrain & ter, const tripoint_om_omt & pos,
         om_direction::type rot, const std::vector<om_pos_dir> &suppressed_joins ) {
             const oter_id tid = ter.terrain->get_rotated( rot );
             om.ter_set( pos, tid );
             unresolved.add_joins_for( ter, pos, rot, suppressed_joins );
             result.push_back( pos );
             // Accumulate connections to be dealt with later
             for( const std::pair<const cube_direction, mutable_special_connection> &p :
                  ter.connections ) {
                 cube_direction base_dir = p.first;
                 const mutable_special_connection &conn = p.second;
                 cube_direction dir = base_dir + rot;
                 tripoint_om_omt conn_pos = pos + displace( dir );
                 if( overmap::inbounds( conn_pos ) ) {
                     connections_placed.push_back( { conn.connection, { conn_pos, dir } } );
                 }
             }
         };
         const mutable_overmap_terrain &root_omt = it->second;
         add_ter( root_omt, origin, dir, {} );
         auto current_phase = phases.begin();
         mutable_overmap_phase_remainder phase_remaining = current_phase->realise();
         while( unresolved.any_unresolved() ) {
             tripoint_om_omt next_pos = unresolved.pick_top_priority();
             mutable_overmap_phase_remainder::satisfy_result satisfy_result =
                 phase_remaining.satisfy( om, next_pos, unresolved );
             descriptions.push_back( std::move( satisfy_result.description ) );
             const mutable_overmap_placement_rule_remainder *rule = satisfy_result.rule;
             if( rule ) {
                 const tripoint_om_omt &satisfy_origin = satisfy_result.origin;
                 om_direction::type rot = satisfy_result.dir;
                 for( const mutable_overmap_piece_candidate piece : rule->pieces( satisfy_origin, rot ) ) {
                     const mutable_overmap_terrain &ter = *piece.overmap;
                     add_ter( ter, piece.pos, piece.rot, satisfy_result.suppressed_joins );
                 }
             } else {
                 unresolved.postpone( next_pos );
             }
             if( !unresolved.any_unresolved() || phase_remaining.all_rules_exhausted() ) {
                 ++current_phase;
                 if( current_phase == phases.end() ) {
                     break;
                 }
                 descriptions.push_back(
                     // NOLINTNEXTLINE(cata-translate-string-literal)
                     string_format( "## Entering phase %td", current_phase - phases.begin() ) );
                 phase_remaining = current_phase->realise();
                 unresolved.restore_postponed();
             }
         }
         if( unresolved.any_postponed() ) {
             // This is an error in the JSON; extract some useful info to help
             // the user debug it
             unresolved.restore_postponed();
             tripoint_om_omt p = unresolved.pick_top_priority();
             const oter_id &current_terrain = om.ter( p );
             std::string joins = enumerate_as_string( unresolved.all_unresolved_at( p ),
             []( const joins_tracker::join * dir_join ) {
                 // NOLINTNEXTLINE(cata-translate-string-literal)
                 return string_format( "%s: %s", io::enum_to_string( dir_join->where.dir ),
                                       dir_join->join->id );
             } );
             debugmsg( "Spawn of mutable special %s had unresolved joins.  Existing terrain "
                       "at %s was %s; joins were %s\nComplete record of placement follows:\n%s",
                       parent_id.str(), p.to_string(), current_terrain.id().str(), joins,
                       string_join( descriptions, "\n" ) );
             om.add_note(
                 p, string_format(
                     // NOLINTNEXTLINE(cata-translate-string-literal)
                     "U:R;DEBUG: unresolved joins %s at %s placing %s",
                     joins, p.to_string(), parent_id.str() ) );
         }
         // Deal with connections
         for( const placed_connection &elem : connections_placed ) {
             const tripoint_om_omt &pos = elem.where.p;
             cube_direction connection_dir = elem.where.dir;
             if( cit ) {
                 om.build_connection( cit.pos, pos.xy(), pos.z(), *elem.connection,
                                      must_be_unexplored, connection_dir );
             }
             // if no city present, search for nearby road within 50 tiles and make connection to it instead
             else {
                 for( const tripoint_om_omt &nearby_point : closest_points_first( pos, 50 ) ) {
                     if( om.check_ot( "road", ot_match_type::contains, nearby_point ) ) {
                         om.build_connection(
                             nearby_point.xy(), pos.xy(), pos.z(), *elem.connection,
                             must_be_unexplored, connection_dir );
                     }
                 }
             }
         }
         return { result, unresolved.all_used() };
     }
References joins_tracker::add_joins_for(), mutable_overmap_phase_remainder::all_rules_exhausted(), joins_tracker::all_unresolved_at(), joins_tracker::all_used(), joins_tracker::any_postponed(), joins_tracker::any_unresolved(), base_camps::base_dir, closest_points_first(), mutable_special_connection::connection, mutable_overmap_terrain::connections, contains, debugmsg, mutable_overmap_phase_remainder::satisfy_result::description, mutable_overmap_phase_remainder::satisfy_result::dir, displace(), enumerate_as_string(), oter_t::get_rotated(), int_id< T >::id(), overmap::inbounds(), coords::om, mutable_overmap_phase_remainder::satisfy_result::origin, joins_tracker::pick_top_priority(), mutable_overmap_placement_rule_remainder::pieces(), city::pos, math_opers::pos(), joins_tracker::postpone(), joins_tracker::restore_postponed(), mutable_overmap_phase_remainder::satisfy_result::rule, mutable_overmap_phase_remainder::satisfy(), string_id< T >::str(), string_format(), string_join(), mutable_overmap_phase_remainder::satisfy_result::suppressed_joins, mutable_overmap_terrain::terrain, and coords::coord_point_base< Point >::to_string().
preview_terrains()
std::vector<overmap_special_terrain> mutable_overmap_special_data::preview_terrains () const inline override virtual
Implements overmap_special_data.
Definition at line 2490 of file overmap.cpp.
{
         return std::vector<overmap_special_terrain> { root_as_overmap_special_terrain() };
     }
required_locations()
std::vector<overmap_special_locations> mutable_overmap_special_data::required_locations () const inline override virtual
Implements overmap_special_data.
Definition at line 2494 of file overmap.cpp.
{
         return check_for_locations;
     }
root_as_overmap_special_terrain()
overmap_special_terrain mutable_overmap_special_data::root_as_overmap_special_terrain () const inline
Definition at line 2480 of file overmap.cpp.
{
         auto it = overmaps.find( root );
         if( it == overmaps.end() ) {
             debugmsg( "root '%s' is not an overmap in this special", root );
             return {};
         }
         const mutable_overmap_terrain &root_om = it->second;
         return { tripoint_zero, root_om.terrain, root_om.locations, {} };
     }
References debugmsg, mutable_overmap_terrain::locations, mutable_overmap_terrain::terrain, and tripoint_zero.
score_rotation_at()
int mutable_overmap_special_data::score_rotation_at (const overmap & , const tripoint_om_omt & , om_direction::type) const inline override virtual
Implements overmap_special_data.
Definition at line 2498 of file overmap.cpp.
{
         // TODO: worry about connections for mutable specials
         // For now we just allow all rotations, but will be restricted by
         // can_place_special
         return 0;
     }
Member Data Documentation
check_for_locations
std::vector<overmap_special_locations> mutable_overmap_special_data::check_for_locations
Definition at line 2390 of file overmap.cpp.
check_for_locations_area
std::vector<overmap_special_locations> mutable_overmap_special_data::check_for_locations_area
Definition at line 2391 of file overmap.cpp.
joins
std::unordered_map<std::string, mutable_overmap_join *> mutable_overmap_special_data::joins
Definition at line 2393 of file overmap.cpp.
joins_vec
std::vector<mutable_overmap_join> mutable_overmap_special_data::joins_vec
Definition at line 2392 of file overmap.cpp.
overmaps
std::unordered_map<std::string, mutable_overmap_terrain> mutable_overmap_special_data::overmaps
Definition at line 2394 of file overmap.cpp.
parent_id
overmap_special_id mutable_overmap_special_data::parent_id
Definition at line 2389 of file overmap.cpp.
phases
std::vector<mutable_overmap_phase> mutable_overmap_special_data::phases
Definition at line 2396 of file overmap.cpp.
root
std::string mutable_overmap_special_data::root
Definition at line 2395 of file overmap.cpp.
The documentation for this struct was generated from the following file:
src/overmap.cpp