Cataclysm DDA: map_extras Struct Reference
map_extras Struct Reference
#include <regional_settings.h>
Public Member Functions
map_extras ()
map_extras (const unsigned int embellished)
map_extras filtered_by (const mapgendata &) const
Public Attributes
unsigned int chance
weighted_int_list< map_extra_id > values
Detailed Description
Definition at line 248 of file regional_settings.h.
Constructor & Destructor Documentation
map_extras() [1/2]
map_extras::map_extras () inline
Definition at line 252 of file regional_settings.h.
 : chance( 0 ) {}
map_extras() [2/2]
map_extras::map_extras (const unsigned int embellished) inline explicit
Definition at line 253 of file regional_settings.h.
 : chance( embellished ) {}
Member Function Documentation
filtered_by()
map_extras map_extras::filtered_by (const mapgendata & dat) const
Definition at line 968 of file regional_settings.cpp.
 {
     map_extras result( chance );
     for( const weighted_object<int, map_extra_id> &obj : values ) {
         const map_extra_id &extra_id = obj.obj;
         if( extra_id->is_valid_for( dat ) ) {
             result.values.add( extra_id, obj.weight );
         }
     }
     if( !values.empty() && result.values.empty() ) {
         // OMT is too tall / too deep for all map extras. Skip map extra generation.
         result.chance = 0;
     }
     return result;
 }
References chance, map_extra::is_valid_for(), string_id< T >::obj(), and values.
Referenced by map::generate().
Member Data Documentation
chance
unsigned int map_extras::chance
Definition at line 249 of file regional_settings.h.
Referenced by MapExtras::debug_spawn_test(), filtered_by(), and map::generate().
values
weighted_int_list<map_extra_id> map_extras::values
Definition at line 250 of file regional_settings.h.
Referenced by MapExtras::debug_spawn_test(), filtered_by(), and map::generate().
The documentation for this struct was generated from the following files:
src/regional_settings.h
src/regional_settings.cpp