Cataclysm DDA: damage_instance Struct Reference
damage_instance Struct Reference
#include <damage.h>
Public Member Functions
damage_instance ()
damage_instance (const damage_type_id &dt, float amt, float arpen=0.0f, float arpen_mult=1.0f, float dmg_mult=1.0f, float unc_arpen_mult=1.0f, float unc_dmg_mult=1.0f)
void mult_damage (double multiplier, bool pre_armor=false)
void mult_type_damage (double multiplier, const damage_type_id &dt)
float type_damage (const damage_type_id &dt) const
float type_arpen (const damage_type_id &dt) const
float total_damage () const
void clear ()
bool empty () const
void onhit_effects (Creature *source, Creature *target) const
void ondamage_effects (Creature *source, Creature *target, const damage_instance &premitigated, bodypart_str_id bp) const
damage_instance di_considering_length (units::length barrel_length) const
std::vector< damage_unit >::iterator begin ()
std::vector< damage_unit >::const_iterator begin () const
std::vector< damage_unit >::iterator end ()
std::vector< damage_unit >::const_iterator end () const
bool operator== (const damage_instance &other) const
void add_damage (const damage_type_id &dt, float amt, float arpen=0.0f, float arpen_mult=1.0f, float dmg_mult=1.0f, float unc_arpen_mult=1.0f, float unc_dmg_mult=1.0f)
Adds damage to the instance.
void add (const damage_instance &added_di)
void add (const damage_unit &added_du)
void deserialize (const JsonValue &jsin)
Public Attributes
std::vector< damage_unit > damage_units
Detailed Description
Definition at line 132 of file damage.h.
Constructor & Destructor Documentation
damage_instance() [1/2]
damage_instance::damage_instance () default
damage_instance() [2/2]
damage_instance::damage_instance (const damage_type_id & dt, float amt, float arpen = 0.0f, float arpen_mult = 1.0f, float dmg_mult = 1.0f, float unc_arpen_mult = 1.0f, float unc_dmg_mult = 1.0f)
Definition at line 310 of file damage.cpp.
 {
     add_damage( dt, amt, arpen, arpen_mult, dmg_mult, unc_arpen_mult, unc_dmg_mult );
 }
Member Function Documentation
add() [1/2]
void damage_instance::add (const damage_instance & added_di)
Definition at line 484 of file damage.cpp.
 {
     for( const damage_unit &added_du : added_di.damage_units ) {
         add( added_du );
     }
 }
References add, and damage_units.
Referenced by assign_dmg_proportional(), assign_dmg_relative(), mattack::evolve_kill_strike(), Character::gun_value(), mtype::load(), Character::modify_damage_dealt_with_enchantments(), Character::mutation_attacks(), and sting_shoot().
add() [2/2]
void damage_instance::add (const damage_unit & added_du)
Definition at line 491 of file damage.cpp.
 {
     auto iter = std::find_if( damage_units.begin(), damage_units.end(),
     [&added_du]( const damage_unit & du ) {
         return du.type == added_du.type;
     } );
     if( iter == damage_units.end() ) {
         damage_units.emplace_back( added_du );
     } else {
         damage_unit &du = *iter;
         float mult = added_du.damage_multiplier / du.damage_multiplier;
         du.amount += added_du.amount * mult;
         du.res_pen += added_du.res_pen * mult;
         // Linearly interpolate armor multiplier based on damage proportion contributed
         float t = added_du.damage_multiplier / ( added_du.damage_multiplier + du.damage_multiplier );
         du.res_mult = lerp( du.res_mult, added_du.damage_multiplier, t );
         du.unconditional_res_mult *= added_du.unconditional_res_mult;
         du.unconditional_damage_mult *= added_du.unconditional_damage_mult;
         if( added_du.barrels.empty() ) {
             if( du.barrels.empty() ) {
                 du.barrels = added_du.barrels;
             } else {
                 debugmsg( "Tried to add two sets of barrel definitions for damage together, this is not currently supported." );
             }
         }
     }
 }
References damage_unit::amount, damage_unit::barrels, damage_unit::damage_multiplier, debugmsg, lerp(), damage_unit::res_mult, damage_unit::res_pen, damage_unit::unconditional_damage_mult, and damage_unit::unconditional_res_mult.
add_damage()
void damage_instance::add_damage (const damage_type_id & dt, float amt, float arpen = 0.0f, float arpen_mult = 1.0f, float dmg_mult = 1.0f, float unc_arpen_mult = 1.0f, float unc_dmg_mult = 1.0f)
Adds damage to the instance.
If the damage type already exists in the instance, the old and new instance are normalized. The normalization means that the effective damage can actually decrease (depending on target's armor).
Definition at line 316 of file damage.cpp.
 {
     damage_unit du( dt, amt, arpen, arpen_mult, dmg_mult, unc_arpen_mult, unc_dmg_mult );
     add( du );
 }
References add.
Referenced by mattack::acid(), mattack::acid_accurate(), mdefense::acidsplash(), Character::activate_bionic(), trapfunc::beartrap(), trapfunc::blade(), Character::deal_damage(), mattack::gene_sting(), spell::get_damage_instance(), hardcoded_mutation_attack(), Character::impact(), Item_factory::load_basic_info(), melee_actor::melee_actor(), monster::melee_attack(), Character::melee_special_effects(), Character::modify_damage_dealt_with_enchantments(), Character::on_hit(), mattack::para_sting(), Character::perform_technique(), Character::roll_damage(), roll_melee_damage_internal(), trapfunc::snare_heavy(), mattack::spit_sap(), Character::thrown_item_total_damage_raw(), and mattack::vine().
begin() [1/2]
std::vector< damage_unit >::iterator damage_instance::begin ()
Definition at line 521 of file damage.cpp.
 {
     return damage_units.begin();
 }
Referenced by mtype::load(), and ondamage_effects().
begin() [2/2]
std::vector< damage_unit >::const_iterator damage_instance::begin () const
Definition at line 526 of file damage.cpp.
 {
     return damage_units.begin();
 }
clear()
void damage_instance::clear ()
Definition at line 474 of file damage.cpp.
 {
     damage_units.clear();
 }
Referenced by Item_factory::load_basic_info(), and Character::perform_technique().
deserialize()
void damage_instance::deserialize (const JsonValue & jsin)
Definition at line 546 of file damage.cpp.
 {
     // TODO: Clean up
     if( jsin.test_object() ) {
         JsonObject jo = jsin.get_object();
         damage_units = load_damage_instance( jo ).damage_units;
     } else if( jsin.test_array() ) {
         damage_units = load_damage_instance( jsin.get_array() ).damage_units;
     } else {
         jsin.throw_error( "Expected object or array for damage_instance" );
     }
 }
References damage_units, JsonValue::get_array(), JsonValue::get_object(), load_damage_instance(), JsonValue::test_array(), JsonValue::test_object(), and JsonValue::throw_error().
di_considering_length()
damage_instance damage_instance::di_considering_length (units::length barrel_length) const
Definition at line 453 of file damage.cpp.
 {
     if( barrel_length == 0_mm ) {
         return *this;
     }
     damage_instance di = damage_instance();
     di.damage_units = this->damage_units;
     for( damage_unit &du : di.damage_units ) {
         if( !du.barrels.empty() ) {
             std::vector<std::pair<float, float>> lerp_points;
             lerp_points.reserve( du.barrels.size() );
             for( const barrel_desc &b : du.barrels ) {
                 lerp_points.emplace_back( static_cast<float>( b.barrel_length.value() ), b.amount );
             }
             du.amount = multi_lerp( lerp_points, barrel_length.value() );
         }
     }
     return di;
 }
References damage_unit::amount, b, damage_unit::barrels, damage_units, multi_lerp(), and units::quantity< V, U >::value().
Referenced by item::ammo_info(), and item::gun_info().
empty()
bool damage_instance::empty () const
Definition at line 479 of file damage.cpp.
 {
     return damage_units.empty();
 }
Referenced by item::ammo_info(), get_ranged_pierce(), and Character::gun_value().
end() [1/2]
std::vector< damage_unit >::iterator damage_instance::end ()
Definition at line 531 of file damage.cpp.
 {
     return damage_units.end();
 }
Referenced by mtype::load(), and ondamage_effects().
end() [2/2]
std::vector< damage_unit >::const_iterator damage_instance::end () const
Definition at line 536 of file damage.cpp.
 {
     return damage_units.end();
 }
mult_damage()
void damage_instance::mult_damage (double multiplier, bool pre_armor = false)
Definition at line 323 of file damage.cpp.
 {
     if( multiplier <= 0.0 ) {
         clear();
     }
     if( pre_armor ) {
         for( damage_unit &elem : damage_units ) {
             elem.amount *= multiplier;
         }
     } else {
         for( damage_unit &elem : damage_units ) {
             elem.damage_multiplier *= multiplier;
         }
     }
 }
References clear.
Referenced by melee_actor::call(), mattack::evolve_kill_strike(), mtype::load(), Character::melee_attack_abstract(), Character::mutation_attacks(), and map::shoot().
mult_type_damage()
void damage_instance::mult_type_damage (double multiplier, const damage_type_id & dt)
Definition at line 340 of file damage.cpp.
 {
     for( damage_unit &elem : damage_units ) {
         if( elem.type == dt ) {
             elem.damage_multiplier *= multiplier;
         }
     }
 }
Referenced by Character::perform_technique().
ondamage_effects()
void damage_instance::ondamage_effects (Creature * source, Creature * target, const damage_instance & premitigated, bodypart_str_id bp) const
Definition at line 407 of file damage.cpp.
 {
     std::set<damage_type_id> used_types;
     for( const damage_unit &du : damage_units ) {
         if( used_types.count( du.type ) > 0 ) {
             continue;
         }
         used_types.emplace( du.type );
         // get the original damage
         auto predamageunit = std::find_if( premitigated.begin(),
         premitigated.end(), [du]( const damage_unit & dut ) {
             return dut.type == du.type;
         } );
         double premit = 0.0;
         if( predamageunit != premitigated.end() ) {
             premit = predamageunit->amount;
         }
         if( !target->is_immune_damage( du.type ) ) {
             du.type->ondamage_effects( source, target, bp, premit, du.amount );
         }
     }
 }
References begin(), bp, end(), and Creature::is_immune_damage().
Referenced by Creature::deal_damage().
onhit_effects()
void damage_instance::onhit_effects (Creature * source, Creature * target) const
Definition at line 381 of file damage.cpp.
 {
     std::set<damage_type_id> used_types;
     for( const damage_unit &du : damage_units ) {
         if( used_types.count( du.type ) > 0 ) {
             continue;
         }
         used_types.emplace( du.type );
         du.type->onhit_effects( source, target );
     }
 }
Referenced by Creature::deal_melee_hit().
operator==()
bool damage_instance::operator== (const damage_instance & other) const
Definition at line 541 of file damage.cpp.
 {
     return damage_units == other.damage_units;
 }
References other.
total_damage()
float damage_instance::total_damage () const
Definition at line 372 of file damage.cpp.
 {
     float ret = 0.0f;
     for( const damage_unit &elem : damage_units ) {
         ret += elem.amount * elem.damage_multiplier * elem.unconditional_damage_mult;
     }
     return ret;
 }
References cata::hash64_detail::ret.
Referenced by item::ammo_info(), npc_attack_melee::evaluate_critter(), npc_attack_gun::evaluate_tripoint(), MonsterGenerator::finalize_mtypes(), item::gun_info(), Character::gun_value(), monster::move_effects(), Character::mutation_attacks(), Character::perform_technique(), projectile_attack(), projectile_attack_results::projectile_attack_results(), Character::throw_item(), and weapon_inventory_preset::weapon_inventory_preset().
type_arpen()
float damage_instance::type_arpen (const damage_type_id & dt) const
Definition at line 360 of file damage.cpp.
 {
     float ret = 0.0f;
     for( const damage_unit &elem : damage_units ) {
         if( elem.type == dt ) {
             ret += elem.res_pen;
         }
     }
     return ret;
 }
References cata::hash64_detail::ret.
Referenced by body_part_type::unarmed_arpen().
type_damage()
float damage_instance::type_damage (const damage_type_id & dt) const
Definition at line 349 of file damage.cpp.
 {
     float ret = 0.0f;
     for( const damage_unit &elem : damage_units ) {
         if( elem.type == dt ) {
             ret += elem.amount * elem.damage_multiplier * elem.unconditional_damage_mult;
         }
     }
     return ret;
 }
References cata::hash64_detail::ret.
Referenced by item::melee_combat_info(), print_damage_info(), and body_part_type::unarmed_damage().
Member Data Documentation
damage_units
std::vector<damage_unit> damage_instance::damage_units
Definition at line 133 of file damage.h.
Referenced by Character::absorb_hit(), monster::absorb_hit(), add(), item::ammo_info(), weakpoint::apply_to(), assign_dmg_proportional(), assign_dmg_relative(), Character::block_hit(), body_part_type::check(), check_assigned_dmg(), mutation_branch::check_consistency(), MonsterGenerator::check_monster_definitions(), damage_targets(), Creature::deal_damage(), deserialize(), di_considering_length(), Creature::dodge_check(), item::effective_dps(), Character::fire_gun(), get_ranged_pierce(), Character::gun_value(), load_damage_instance_inherit(), load_damage_unit_inherit(), Character::perform_technique(), print_damage_info(), map::shoot(), Character::thrown_item_total_damage_raw(), and weakpoint_attack::type_of_melee_attack().
The documentation for this struct was generated from the following files:
src/damage.h
src/damage.cpp