Cataclysm DDA: dbl_or_var Struct Reference
dbl_or_var Struct Reference
#include <dialogue_helpers.h>
Public Member Functions
double evaluate (dialogue &d) const
bool is_constant () const
double constant () const
operator bool () const
dbl_or_var ()=default
template<class D , typename std::enable_if_t< std::is_arithmetic_v< D >> * = nullptr>
dbl_or_var (D d)
Public Attributes
bool pair = false
dbl_or_var_part min
dbl_or_var_part max
Detailed Description
Definition at line 165 of file dialogue_helpers.h.
Constructor & Destructor Documentation
dbl_or_var() [1/2]
dbl_or_var::dbl_or_var () default
dbl_or_var() [2/2]
template<class D , typename std::enable_if_t< std::is_arithmetic_v< D >> * = nullptr> dbl_or_var::dbl_or_var (D d) inline explicit
Definition at line 186 of file dialogue_helpers.h.
 : min( d ) {}
Member Function Documentation
constant()
double dbl_or_var::constant () const inline
Definition at line 175 of file dialogue_helpers.h.
{
         return min.constant();
     }
References dbl_or_var_part::constant(), and min.
evaluate()
double dbl_or_var::evaluate (dialogue & d) const
Definition at line 191 of file dialogue_helpers.cpp.
 {
     if( pair ) {
         return rng( min.evaluate( d ), max.evaluate( d ) );
     }
     return min.evaluate( d );
 }
References dbl_or_var_part::evaluate(), max, min, pair, and rng().
Referenced by spell::accuracy(), spell::aoe(), spell::aoe_string(), spell::casting_time(), emit::chance(), debug_menu::change_spells(), spell::create_field(), spell::damage(), spell::damage_dot(), spell::damage_string(), draw_spellbook_info(), spell::duration(), spell::duration_string(), spell::energy_cost(), npc_attack_spell::evaluate_tripoint(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_faction_trust(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_morale(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_wet(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_attack(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_change_faction_rep(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_consume_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_custom_light_level(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_dexterity(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_faction_trust(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_intelligence(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_items(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_part_temp(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_perception(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_strength(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable_adjust(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_faction_trust(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mod_healthy(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate(), conditional_fun::anonymous_namespace{condition.cpp}::f_near_om_location(), conditional_fun::anonymous_namespace{condition.cpp}::f_need(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_allies(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_allies_global(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_service(), conditional_fun::anonymous_namespace{condition.cpp}::f_one_in_chance(), conditional_fun::anonymous_namespace{condition.cpp}::f_query_tile(), conditional_fun::anonymous_namespace{condition.cpp}::f_roll_contested(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_until(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_switch(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_are_owed(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_monster(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_has_cash(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_spend_cash(), conditional_fun::anonymous_namespace{condition.cpp}::f_x_in_y_chance(), spell::field_intensity(), find_or_create_om_terrain(), spell::get_difficulty(), spell::get_max_level(), spell::in_aoe(), emit::intensity(), spell::is_max_level(), spell::min_leveled_accuracy(), spell::min_leveled_aoe(), spell::min_leveled_damage(), spell::min_leveled_dot(), spell::min_leveled_duration(), emit::qty(), spell::range(), and known_magic::time_to_learn_spell().
is_constant()
bool dbl_or_var::is_constant () const inline
Definition at line 171 of file dialogue_helpers.h.
{
         return !max && min.is_constant();
     }
References dbl_or_var_part::is_constant(), max, and min.
operator bool()
dbl_or_var::operator bool () const inline explicit
Definition at line 179 of file dialogue_helpers.h.
{
         return static_cast<bool>( min );
     }
References min.
Member Data Documentation
max
dbl_or_var_part dbl_or_var::max
Definition at line 168 of file dialogue_helpers.h.
Referenced by evaluate(), is_constant(), and enchantment::load().
min
dbl_or_var_part dbl_or_var::min
Definition at line 167 of file dialogue_helpers.h.
Referenced by constant(), evaluate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), conditional_fun::anonymous_namespace{condition.cpp}::f_need(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_weighted_list_eocs(), is_constant(), enchantment::load(), operator bool(), mission_start::reveal_refugee_center(), and spell_type::serialize().
pair
bool dbl_or_var::pair = false
Definition at line 166 of file dialogue_helpers.h.
Referenced by evaluate().
The documentation for this struct was generated from the following files:
src/dialogue_helpers.h
src/dialogue_helpers.cpp