Cataclysm DDA: book_recipe_data Struct Reference
book_recipe_data Struct Reference
#include <recipe.h>
Public Member Functions
void load (const JsonObject &jo)
void deserialize (const JsonObject &jo)
Public Attributes
int skill_req = -1
std::optional< translation > alt_name = std::nullopt
bool hidden = false
Detailed Description
Definition at line 63 of file recipe.h.
Member Function Documentation
deserialize()
void book_recipe_data::deserialize (const JsonObject & jo)
Definition at line 1567 of file recipe.cpp.
 {
     load( jo );
 }
References load().
load()
void book_recipe_data::load (const JsonObject & jo)
Definition at line 1572 of file recipe.cpp.
 {
     jo.read( "skill_level", skill_req );
     jo.read( "recipe_name", alt_name );
     jo.read( "hidden", hidden );
 }
References alt_name, hidden, JsonObject::read(), and skill_req.
Referenced by deserialize().
Member Data Documentation
alt_name
std::optional<translation> book_recipe_data::alt_name = std::nullopt
Definition at line 65 of file recipe.h.
Referenced by load().
hidden
bool book_recipe_data::hidden = false
Definition at line 66 of file recipe.h.
Referenced by load().
skill_req
int book_recipe_data::skill_req = -1
Definition at line 64 of file recipe.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/recipe.h
src/recipe.cpp