Cataclysm DDA: mapgen_value< Id >::distribution_source Struct Reference
mapgen_value< Id >::distribution_source Struct Reference
Public Member Functions
distribution_source (const JsonObject &jo)
Id get (const mapgendata &) const override
void check (const std::string &context, const mapgen_parameters &) const override
void check_consistent_with (const value_source &o, const std::string &context) const override
std::vector< StringId > all_possible_results (const mapgen_parameters &) const override
Public Member Functions inherited from mapgen_value< Id >::value_source
virtual ~value_source ()=default
virtual const std::string * get_name_if_parameter () const
Public Attributes
weighted_int_list< StringId > list
Detailed Description
template<typename Id>
struct mapgen_value< Id >::distribution_source
Definition at line 1360 of file mapgen.cpp.
Constructor & Destructor Documentation
distribution_source()
template<typename Id > mapgen_value< Id >::distribution_source::distribution_source (const JsonObject & jo) inline explicit
Definition at line 1363 of file mapgen.cpp.
{
                 load_weighted_list( jo.get_member( "distribution" ), list, 1 );
             }
References JsonObject::get_member(), mapgen_value< Id >::distribution_source::list, and load_weighted_list().
Member Function Documentation
all_possible_results()
template<typename Id > std::vector<StringId> mapgen_value< Id >::distribution_source::all_possible_results (const mapgen_parameters &) const inline override virtual
Implements mapgen_value< Id >::value_source.
Definition at line 1395 of file mapgen.cpp.
{
                 std::vector<StringId> result;
                 for( const weighted_object<int, StringId> &wo : list ) {
                     result.push_back( wo.obj );
                 }
                 return result;
             }
References mapgen_value< Id >::distribution_source::list.
check()
template<typename Id > void mapgen_value< Id >::distribution_source::check (const std::string & context, const mapgen_parameters &) const inline override virtual
Reimplemented from mapgen_value< Id >::value_source.
Definition at line 1371 of file mapgen.cpp.
{
                 for( const weighted_object<int, StringId> &wo : list ) {
                     if( !is_valid_helper( wo.obj ) ) {
                         debugmsg( "mapgen '%s' uses invalid entry '%s' in weighted list",
                                   context, cata_variant( wo.obj ).get_string() );
                     }
                 }
             }
References context, debugmsg, cata_variant::get_string(), is_valid_helper(), and mapgen_value< Id >::distribution_source::list.
check_consistent_with()
template<typename Id > void mapgen_value< Id >::distribution_source::check_consistent_with (const value_source & o, const std::string & context) const inline override virtual
Implements mapgen_value< Id >::value_source.
Definition at line 1380 of file mapgen.cpp.
{
                 if( const distribution_source *other =
                         dynamic_cast<const distribution_source *>( &o ) ) {
                     if( list != other->list ) {
                         const std::string my_list = list.to_debug_string();
                         const std::string other_list = other->list.to_debug_string();
                         debugmsg( "inconsistent default value distributions for %s (%s vs %s)",
                                   context, my_list, other_list );
                     }
                 } else {
                     debugmsg( "inconsistent default types for %s", context );
                 }
             }
References context, debugmsg, mapgen_value< Id >::distribution_source::list, other, and weighted_list< W, T >::to_debug_string().
get()
template<typename Id > Id mapgen_value< Id >::distribution_source::get (const mapgendata &) const inline override virtual
Implements mapgen_value< Id >::value_source.
Definition at line 1367 of file mapgen.cpp.
{
                 return *list.pick();
             }
References mapgen_value< Id >::distribution_source::list, and weighted_list< W, T >::pick().
Member Data Documentation
list
template<typename Id > weighted_int_list<StringId> mapgen_value< Id >::distribution_source::list
Definition at line 1361 of file mapgen.cpp.
Referenced by mapgen_value< Id >::distribution_source::all_possible_results(), mapgen_value< Id >::distribution_source::check(), mapgen_value< Id >::distribution_source::check_consistent_with(), mapgen_value< Id >::distribution_source::distribution_source(), and mapgen_value< Id >::distribution_source::get().
The documentation for this struct was generated from the following file:
src/mapgen.cpp