Cataclysm DDA: practice_recipe_data Struct Reference
practice_recipe_data Struct Reference
#include <recipe.h>
Public Member Functions
void load (const JsonObject &jo)
void deserialize (const JsonObject &jo)
Public Attributes
int min_difficulty
int max_difficulty
int skill_limit
Detailed Description
Definition at line 72 of file recipe.h.
Member Function Documentation
deserialize()
void practice_recipe_data::deserialize (const JsonObject & jo)
Definition at line 1579 of file recipe.cpp.
 {
     load( jo );
 }
References load().
load()
void practice_recipe_data::load (const JsonObject & jo)
Definition at line 1584 of file recipe.cpp.
 {
     jo.read( "min_difficulty", min_difficulty );
     if( !jo.read( "max_difficulty", max_difficulty ) ) {
         max_difficulty = MAX_SKILL - 1;
     }
     if( !jo.read( "skill_limit", skill_limit ) ) {
         skill_limit = MAX_SKILL;
     }
 }
References max_difficulty, MAX_SKILL, min_difficulty, JsonObject::read(), and skill_limit.
Referenced by deserialize().
Member Data Documentation
max_difficulty
int practice_recipe_data::max_difficulty
Definition at line 77 of file recipe.h.
Referenced by load().
min_difficulty
int practice_recipe_data::min_difficulty
Definition at line 76 of file recipe.h.
Referenced by load().
skill_limit
int practice_recipe_data::skill_limit
Definition at line 80 of file recipe.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/recipe.h
src/recipe.cpp