Cataclysm DDA: relic_charge_info Struct Reference
relic_charge_info Struct Reference
#include <relic.h>
Public Member Functions
relic_charge_info ()=default
void accumulate_charge (item &parent)
void deserialize (const JsonObject &jo)
void load (const JsonObject &jo)
void serialize (JsonOut &jsout) const
Public Attributes
bool regenerate_ammo = false
int charges = 0
int charges_per_use = 0
int max_charges = 0
relic_recharge_type type = relic_recharge_type::NUM
relic_recharge_has has = relic_recharge_has::NUM
time_duration activation_accumulator = 0_seconds
time_duration activation_time = 0_seconds
int power = 0
Detailed Description
Definition at line 174 of file relic.h.
Constructor & Destructor Documentation
relic_charge_info()
relic_charge_info::relic_charge_info () default
Member Function Documentation
accumulate_charge()
void relic_charge_info::accumulate_charge (item & parent)
Definition at line 313 of file relic.cpp.
 {
     const bool time = activation_time == 0_seconds;
     const bool regen_ammo = regenerate_ammo && item_can_not_load_ammo( parent );
     const bool has_max_charges = !regenerate_ammo && charges >= max_charges && max_charges != 0;
     if( time || regen_ammo || has_max_charges ) {
         return;
     }
     activation_accumulator += 1_seconds;
     if( activation_accumulator >= activation_time ) {
         activation_accumulator -= activation_time;
         if( regenerate_ammo ) {
             item *current_magazine = &parent;
             if( parent.magazine_current() ) {
                 current_magazine = parent.magazine_current();
             }
             const itype_id current_ammo = current_magazine->ammo_current();
             if( current_ammo == itype_id::NULL_ID() ) {
                 current_magazine->ammo_set( current_magazine->ammo_default(), 1 );
             } else {
                 current_magazine->ammo_set( current_ammo, current_magazine->ammo_remaining() + 1 );
             }
         } else {
             charges++;
         }
     }
 }
References item::ammo_current(), item::ammo_default(), item::ammo_remaining(), item::ammo_set(), item_can_not_load_ammo(), item::magazine_current(), and string_id< itype >::NULL_ID().
deserialize()
void relic_charge_info::deserialize (const JsonObject & jo)
Definition at line 282 of file relic.cpp.
 {
     load( jo );
 }
References relic_procgen_data::load().
load()
void relic_charge_info::load (const JsonObject & jo)
Definition at line 287 of file relic.cpp.
 {
     jo.read( "charges", charges );
     jo.read( "charges_per_use", charges_per_use );
     jo.read( "max_charges", max_charges );
     jo.read( "recharge_type", type );
     jo.read( "recharge_condition", has );
     jo.read( "regenerate_ammo", regenerate_ammo );
     jo.read( "activation_accumulator", activation_accumulator );
     jo.read( "time", activation_time );
 }
References JsonObject::read().
serialize()
void relic_charge_info::serialize (JsonOut & jsout) const
Definition at line 299 of file relic.cpp.
 {
     jsout.start_object();
     jsout.member( "charges", charges );
     jsout.member( "charges_per_use", charges_per_use );
     jsout.member( "max_charges", max_charges );
     jsout.member( "regenerate_ammo", regenerate_ammo );
     jsout.member( "recharge_type", type );
     jsout.member( "recharge_condition", has );
     jsout.member( "activation_accumulator", activation_accumulator );
     jsout.member( "time", activation_time );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
Member Data Documentation
activation_accumulator
time_duration relic_charge_info::activation_accumulator = 0_seconds
Definition at line 183 of file relic.h.
activation_time
time_duration relic_charge_info::activation_time = 0_seconds
Definition at line 184 of file relic.h.
charges
int relic_charge_info::charges = 0
Definition at line 177 of file relic.h.
charges_per_use
int relic_charge_info::charges_per_use = 0
Definition at line 178 of file relic.h.
has
relic_recharge_has relic_charge_info::has = relic_recharge_has::NUM
Definition at line 181 of file relic.h.
max_charges
int relic_charge_info::max_charges = 0
Definition at line 179 of file relic.h.
power
int relic_charge_info::power = 0
Definition at line 190 of file relic.h.
regenerate_ammo
bool relic_charge_info::regenerate_ammo = false
Definition at line 176 of file relic.h.
type
relic_recharge_type relic_charge_info::type = relic_recharge_type::NUM
Definition at line 180 of file relic.h.
The documentation for this struct was generated from the following files:
src/relic.h
src/relic.cpp