Cataclysm DDA: io::detail::has_archive_tag< T, E > Struct Template Reference
io::detail::has_archive_tag< T, E > Struct Template Reference
Implementation for classes that don't have an archive_type_tag defined.
#include <cata_io.h>
Static Public Member Functions
template<typename S , typename TT = T, std::enable_if_t< std::is_enum_v< TT > &&std::is_same_v< S, TT > > * = nullptr>
static void write (JsonOut &stream, const S &value)
template<typename S , typename TT = T, std::enable_if_t< !std::is_enum_v< TT > &&std::is_same_v< S, TT > > * = nullptr>
static void write (JsonOut &stream, const S &value)
static bool read (const JsonObject &obj, const std::string &key, T &value)
static bool read (JsonArray &arr, T &value)
Detailed Description
template<class T, class E = void>
struct io::detail::has_archive_tag< T, E >
Implementation for classes that don't have an archive_type_tag defined.
They use the normal json read/write interface, which is handled directly by the Json classes. Therefore the functions here simply forward to those.
Definition at line 133 of file cata_io.h.
Member Function Documentation
read() [1/2]
template<class T , class E = void> static bool io::detail::has_archive_tag< T, E >::read (const JsonObject & obj, const std::string & key, T & value) inline static
Definition at line 146 of file cata_io.h.
{
         return obj.read( key, value );
     }
References JsonObject::read().
Referenced by io::JsonObjectInputArchive::io(), and io::JsonArrayInputArchive::io().
read() [2/2]
template<class T , class E = void> static bool io::detail::has_archive_tag< T, E >::read (JsonArray & arr, T & value) inline static
Definition at line 149 of file cata_io.h.
{
         return arr.read_next( value );
     }
References JsonArray::read_next().
write() [1/2]
template<class T , class E = void> template<typename S , typename TT = T, std::enable_if_t< std::is_enum_v< TT > &&std::is_same_v< S, TT > > * = nullptr> static void io::detail::has_archive_tag< T, E >::write (JsonOut & stream, const S & value) inline static
Definition at line 136 of file cata_io.h.
{
         // TODO: When writing strings as enums is the default, this overload of
         // write can be removed
         stream.write_as_string( value );
     }
References JsonOut::write_as_string().
Referenced by io::JsonObjectOutputArchive::io(), and io::JsonArrayOutputArchive::io().
write() [2/2]
template<class T , class E = void> template<typename S , typename TT = T, std::enable_if_t< !std::is_enum_v< TT > &&std::is_same_v< S, TT > > * = nullptr> static void io::detail::has_archive_tag< T, E >::write (JsonOut & stream, const S & value) inline static
Definition at line 143 of file cata_io.h.
{
         stream.write( value );
     }
References JsonOut::write().
The documentation for this struct was generated from the following file:
src/cata_io.h