Cataclysm DDA: quality_requirement Struct Reference
quality_requirement Struct Reference
#include <requirements.h>
Public Member Functions
bool operator== (const quality_requirement &rhs) const
bool operator!= (const quality_requirement &rhs) const
bool operator< (const quality_requirement &rhs) const
quality_requirement ()=default
quality_requirement (const quality_id &TYPE, int COUNT, int LEVEL)
void load (const JsonValue &value)
void dump (JsonOut &jsout) const
bool has (const read_only_visitable &crafting_inv, const std::function< bool(const item &)> &filter, int=0, craft_flags=craft_flags::none, const std::function< void(int)> &visitor=std::function< void(int)>()) const
std::string to_string (int batch=1, int avail=0) const
std::string to_colored_string () const
void check_consistency (const std::string &display_name) const
nc_color get_color (bool has_one, const read_only_visitable &crafting_inv, const std::function< bool(const item &)> &filter, int=0) const
component_type get_component_type () const
Public Attributes
quality_id type = quality_id("UNKNOWN")
int count = 1
int level = 1
available_status available = available_status::a_false
bool requirement = false
Detailed Description
Definition at line 128 of file requirements.h.
Constructor & Destructor Documentation
quality_requirement() [1/2]
quality_requirement::quality_requirement () default
quality_requirement() [2/2]
quality_requirement::quality_requirement (const quality_id & TYPE, int COUNT, int LEVEL) inline
Definition at line 151 of file requirements.h.
                                                                         : type( TYPE ), count( COUNT ),
         level( LEVEL ) { }
Member Function Documentation
check_consistency()
void quality_requirement::check_consistency (const std::string & display_name) const
Definition at line 583 of file requirements.cpp.
 {
     if( !type.is_valid() ) {
         debugmsg( "Unknown quality %s in %s", type.c_str(), display_name );
     }
 }
References string_id< T >::c_str(), debugmsg, string_id< T >::is_valid(), and type.
dump()
void quality_requirement::dump (JsonOut & jsout) const
Definition at line 222 of file requirements.cpp.
 {
     jsout.start_object();
     jsout.member( "id", type );
     if( level != 1 ) {
         jsout.member( "level", level );
     }
     if( count != 1 ) {
         jsout.member( "amount", count );
     }
     jsout.end_object();
 }
References count, JsonOut::end_object(), level, JsonOut::member(), JsonOut::start_object(), and type.
get_color()
nc_color quality_requirement::get_color (bool has_one, const read_only_visitable & crafting_inv, const std::function< bool(const item &)> & filter, int = 0) const
Definition at line 916 of file requirements.cpp.
 {
     if( get_player_character().has_trait( trait_DEBUG_HS ) ||
         available == available_status::a_true ) {
         return c_green;
     }
     return has_one ? c_dark_gray : c_red;
 }
References a_true, available, c_dark_gray, c_green, c_red, get_player_character(), and trait_DEBUG_HS.
get_component_type()
component_type quality_requirement::get_component_type () const inline
Definition at line 165 of file requirements.h.
{
         return component_type::QUALITY;
     }
References QUALITY.
has()
bool quality_requirement::has (const read_only_visitable & crafting_inv, const std::function< bool(const item &)> & filter, int = 0, craft_flags = craft_flags::none, const std::function< void(int)> & visitor = std::function<void(int)>()) const
Definition at line 906 of file requirements.cpp.
 {
     if( get_player_character().has_trait( trait_DEBUG_HS ) ) {
         return true;
     }
     return crafting_inv.has_quality( type, level, count );
 }
References count, get_player_character(), read_only_visitable::has_quality(), level, trait_DEBUG_HS, and type.
load()
void quality_requirement::load (const JsonValue & value)
Definition at line 210 of file requirements.cpp.
 {
     const JsonObject quality_data = value.get_object();
     type = quality_id( quality_data.get_string( "id" ) );
     level = quality_data.get_int( "level", 1 );
     count = quality_data.get_int( "amount", 1 );
     if( count <= 0 ) {
         quality_data.throw_error_at( "amount", "quality amount must be a positive number" );
     }
     // Note: level is not checked, negative values and 0 are allow, see butchering quality.
 }
References count, JsonObject::get_int(), JsonValue::get_object(), JsonObject::get_string(), level, JsonObject::throw_error_at(), and type.
operator!=()
bool quality_requirement::operator!= (const quality_requirement & rhs) const inline
Definition at line 141 of file requirements.h.
{
         return !operator==( rhs );
     }
References operator==().
operator<()
bool quality_requirement::operator< (const quality_requirement & rhs) const inline
Definition at line 145 of file requirements.h.
{
         return std::forward_as_tuple( type, requirement, count, level )
                < std::forward_as_tuple( rhs.type, rhs.requirement, rhs.count, rhs.level );
     }
References count, level, requirement, and type.
operator==()
bool quality_requirement::operator== (const quality_requirement & rhs) const inline
Definition at line 137 of file requirements.h.
{
         return std::forward_as_tuple( type, requirement, count, level )
                == std::forward_as_tuple( rhs.type, rhs.requirement, rhs.count, rhs.level );
     }
References count, level, requirement, and type.
Referenced by operator!=().
to_colored_string()
std::string quality_requirement::to_colored_string () const
Definition at line 141 of file requirements.cpp.
 {
     //~ %1$d: tool count, %2$s: quality requirement name, %3$d: quality level requirement
     return string_format( n_gettext( "%1$d tool with <info>%2$s of %3$d</info> or more",
                                      "%1$d tools with <info>%2$s of %3$d</info> or more", count ),
                           count, type.obj().name, level );
 }
References count, level, n_gettext, quality::name, string_id< T >::obj(), string_format(), and type.
to_string()
std::string quality_requirement::to_string (int batch = 1, int avail = 0) const
Definition at line 133 of file requirements.cpp.
 {
     //~ %1$d: tool count, %2$s: quality requirement name, %3$d: quality level requirement
     return string_format( n_gettext( "%1$d tool with %2$s of %3$d or more.",
                                      "%1$d tools with %2$s of %3$d or more.", count ),
                           count, type.obj().name, level );
 }
References count, level, n_gettext, quality::name, string_id< T >::obj(), string_format(), and type.
Member Data Documentation
available
available_status quality_requirement::available = available_status::a_false mutable
Definition at line 132 of file requirements.h.
Referenced by get_color().
count
int quality_requirement::count = 1
Definition at line 130 of file requirements.h.
Referenced by requirement_data::check_enough_materials(), requirement_data::consolidate(), deserialize(), dump(), has(), load(), operator<(), operator==(), serialize(), to_colored_string(), and to_string().
level
int quality_requirement::level = 1
Definition at line 131 of file requirements.h.
Referenced by requirement_data::check_enough_materials(), requirement_data::consolidate(), deserialize(), dump(), has(), load(), operator<(), operator==(), serialize(), to_colored_string(), and to_string().
requirement
bool quality_requirement::requirement = false
Definition at line 133 of file requirements.h.
Referenced by operator<(), and operator==().
type
quality_id quality_requirement::type = quality_id("UNKNOWN")
Definition at line 129 of file requirements.h.
Referenced by check_consistency(), requirement_data::check_enough_materials(), deserialize(), dump(), has(), load(), operator<(), operator==(), serialize(), to_colored_string(), and to_string().
The documentation for this struct was generated from the following files:
src/requirements.h
src/requirements.cpp