Cataclysm DDA: weakpoints Struct Reference
weakpoints Struct Reference
#include <weakpoint.h>
Public Member Functions
const weakpoint * select_weakpoint (const weakpoint_attack &attack) const
void clear ()
void load (const JsonArray &ja)
void remove (const JsonArray &ja)
void finalize ()
void check () const
void load (const JsonObject &jo, std::string_view src)
void add_from_set (const weakpoints_id &set_id, bool replace_id)
void add_from_set (const weakpoints &set, bool replace_id)
void del_from_set (const weakpoints_id &set_id)
void del_from_set (const weakpoints &set)
Static Public Member Functions
static void load_weakpoint_sets (const JsonObject &jo, const std::string &src)
static void reset ()
static void finalize_all ()
static const std::vector< weakpoints > & get_all ()
Public Attributes
weakpoints_id id
std::vector< std::pair< weakpoints_id, mod_id > > src
std::vector< weakpoint > weakpoint_list
weakpoint default_weakpoint
bool was_loaded = false
Detailed Description
Definition at line 158 of file weakpoint.h.
Member Function Documentation
add_from_set() [1/2]
void weakpoints::add_from_set (const weakpoints & set, bool replace_id)
Definition at line 661 of file weakpoint.cpp.
 {
     for( const weakpoint &wp : set.weakpoint_list ) {
         auto iter = std::find_if( weakpoint_list.begin(),
         weakpoint_list.end(), [&wp]( const weakpoint & w ) {
             return w.id == wp.id && !w.id.empty();
         } );
         if( replace_id && iter != weakpoint_list.end() ) {
             weakpoint_list[iter - weakpoint_list.begin()] = wp;
         } else {
             weakpoint_list.emplace_back( wp );
         }
     }
 }
References weakpoint_list.
add_from_set() [2/2]
void weakpoints::add_from_set (const weakpoints_id & set_id, bool replace_id)
Definition at line 652 of file weakpoint.cpp.
 {
     if( !set_id.is_valid() ) {
         debugmsg( "invalid weakpoint_set id \"%s\"", set_id.c_str() );
         return;
     }
     add_from_set( set_id.obj(), replace_id );
 }
References string_id< T >::c_str(), debugmsg, string_id< T >::is_valid(), and string_id< T >::obj().
Referenced by MonsterGenerator::finalize_mtypes(), and mtype::load().
check()
void weakpoints::check () const
Definition at line 604 of file weakpoint.cpp.
 {
     for( const weakpoint &w : weakpoint_list ) {
         w.check();
     }
 }
References weakpoint_list.
clear()
void weakpoints::clear ()
Definition at line 570 of file weakpoint.cpp.
 {
     weakpoint_list.clear();
 }
References weakpoint_list.
Referenced by MonsterGenerator::finalize_mtypes(), and mtype::load().
del_from_set() [1/2]
void weakpoints::del_from_set (const weakpoints & set)
Definition at line 685 of file weakpoint.cpp.
 {
     for( const weakpoint &wp : set.weakpoint_list ) {
         auto iter = std::find_if( weakpoint_list.begin(),
         weakpoint_list.end(), [&wp]( const weakpoint & w ) {
             return w.id == wp.id && !w.id.empty();
         } );
         if( iter != weakpoint_list.end() ) {
             weakpoint_list.erase( iter );
         }
     }
 }
References weakpoint_list.
del_from_set() [2/2]
void weakpoints::del_from_set (const weakpoints_id & set_id)
Definition at line 676 of file weakpoint.cpp.
 {
     if( !set_id.is_valid() ) {
         debugmsg( "invalid weakpoint_set id \"%s\"", set_id.c_str() );
         return;
     }
     del_from_set( set_id.obj() );
 }
References string_id< T >::c_str(), debugmsg, string_id< T >::is_valid(), and string_id< T >::obj().
Referenced by mtype::load().
finalize()
void weakpoints::finalize ()
Definition at line 611 of file weakpoint.cpp.
 {
     for( weakpoint &w : weakpoint_list ) {
         finalize_damage_map( w.armor_mult, false, 1.0f );
         finalize_damage_map( w.armor_penalty, false, 0.0f );
         finalize_damage_map( w.damage_mult, false, 1.0f );
         finalize_damage_map( w.crit_mult, false, 1.0f );
     }
 }
References finalize_damage_map(), and weakpoint_list.
Referenced by MonsterGenerator::finalize_mtypes().
finalize_all()
void weakpoints::finalize_all () static
Definition at line 647 of file weakpoint.cpp.
 {
     weakpoints_factory.finalize();
 }
References anonymous_namespace{weakpoint.cpp}::weakpoints_factory.
get_all()
const std::vector< weakpoints > & weakpoints::get_all () static
Definition at line 67 of file weakpoint.cpp.
 {
     return weakpoints_factory.get_all();
 }
References anonymous_namespace{weakpoint.cpp}::weakpoints_factory.
load() [1/2]
void weakpoints::load (const JsonArray & ja)
Definition at line 575 of file weakpoint.cpp.
 {
     for( const JsonObject jo : ja ) {
         weakpoint tmp;
         tmp.load( jo );
         if( tmp.id.empty() ) {
             default_weakpoint = tmp;
             continue;
         }
         // Ensure that every weakpoint has a unique ID
         auto it = std::find_if( weakpoint_list.begin(), weakpoint_list.end(),
         [&]( const weakpoint & wp ) {
             return wp.id == tmp.id;
         } );
         if( it != weakpoint_list.end() ) {
             weakpoint_list.erase( it );
         }
         weakpoint_list.push_back( std::move( tmp ) );
     }
     // Prioritizes weakpoints based on their coverage.
     std::sort( weakpoint_list.begin(), weakpoint_list.end(),
     []( const weakpoint & a, const weakpoint & b ) {
         return a.coverage < b.coverage;
     } );
 }
References a, b, default_weakpoint, weakpoint::id, weakpoint::load(), and weakpoint_list.
Referenced by mtype::load(), and load().
load() [2/2]
void weakpoints::load (const JsonObject & jo, std::string_view src)
Definition at line 642 of file weakpoint.cpp.
 {
     load( jo.get_array( "weakpoints" ) );
 }
References JsonObject::get_array(), and load().
load_weakpoint_sets()
void weakpoints::load_weakpoint_sets (const JsonObject & jo, const std::string & src) static
Definition at line 57 of file weakpoint.cpp.
 {
     weakpoints_factory.load( jo, src );
 }
References src, and anonymous_namespace{weakpoint.cpp}::weakpoints_factory.
Referenced by DynamicDataLoader::initialize().
remove()
void weakpoints::remove (const JsonArray & ja)
Definition at line 621 of file weakpoint.cpp.
 {
     for( const JsonObject jo : ja ) {
         weakpoint tmp;
         tmp.load( jo );
         if( tmp.id.empty() ) {
             default_weakpoint = weakpoint();
             continue;
         }
         auto it = std::find_if( weakpoint_list.begin(), weakpoint_list.end(),
         [&]( const weakpoint & wp ) {
             return wp.id == tmp.id;
         } );
         if( it != weakpoint_list.end() ) {
             weakpoint_list.erase( it );
         }
     }
 }
References default_weakpoint, weakpoint::id, weakpoint::load(), and weakpoint_list.
reset()
void weakpoints::reset () static
Definition at line 62 of file weakpoint.cpp.
 {
     weakpoints_factory.reset();
 }
References anonymous_namespace{weakpoint.cpp}::weakpoints_factory.
Referenced by DynamicDataLoader::unload_data().
select_weakpoint()
const weakpoint * weakpoints::select_weakpoint (const weakpoint_attack & attack) const
Definition at line 540 of file weakpoint.cpp.
 {
     add_msg_debug( debugmode::DF_MONSTER,
                    "Weakpoint Selection: Source: %s, Weapon %s, Skill %.3f",
                    attack.source == nullptr ? "nullptr" : attack.source->get_name(),
                    attack.weapon == nullptr ? "nullptr" : attack.weapon->type_name(),
                    attack.wp_skill );
     float rolls = std::max( 1.0f, 1.0f + attack.wp_skill / 2.5f );
     // The base probability of hitting a more preferable weak point.
     float base = 0.0f;
     // The reweighed probability of hitting a more preferable weak point.
     float reweighed = 0.0f;
     float idx = rng_float( 0.0f, 100.0f );
     for( const weakpoint &weakpoint : weakpoint_list ) {
         float new_base = base + weakpoint.hit_chance( attack );
         float new_reweighed = 100.0f * reweigh( new_base / 100.0f, rolls );
         float hit_chance = new_reweighed - reweighed;
         add_msg_debug( debugmode::DF_MONSTER,
                        "Weakpoint Selection: weakpoint %s, hit_chance %.4f",
                        weakpoint.id, hit_chance );
         if( idx < hit_chance ) {
             return &weakpoint;
         }
         base = new_base;
         reweighed = new_reweighed;
         idx -= hit_chance;
     }
     return &default_weakpoint;
 }
References add_msg_debug, spell_effect::attack(), default_weakpoint, debugmode::DF_MONSTER, weakpoint::hit_chance(), weakpoint::id, max(), reweigh(), rng_float(), and weakpoint_list.
Referenced by monster::absorb_hit().
Member Data Documentation
default_weakpoint
weakpoint weakpoints::default_weakpoint
Definition at line 165 of file weakpoint.h.
Referenced by load(), remove(), and select_weakpoint().
id
weakpoints_id weakpoints::id
Definition at line 160 of file weakpoint.h.
src
std::vector<std::pair<weakpoints_id, mod_id> > weakpoints::src
Definition at line 161 of file weakpoint.h.
Referenced by load_weakpoint_sets().
was_loaded
bool weakpoints::was_loaded = false
Definition at line 167 of file weakpoint.h.
weakpoint_list
std::vector<weakpoint> weakpoints::weakpoint_list
Definition at line 163 of file weakpoint.h.
Referenced by add_from_set(), check(), clear(), del_from_set(), finalize(), MonsterGenerator::finalize_mtypes(), load(), mtype::load(), remove(), and select_weakpoint().
The documentation for this struct was generated from the following files:
src/weakpoint.h
src/weakpoint.cpp