Cataclysm DDA: relic_charge_template Struct Reference
relic_charge_template Struct Reference
#include <relic.h>
Public Member Functions
void deserialize (const JsonObject &jo)
void load (const JsonObject &jo)
relic_charge_info generate () const
Public Attributes
std::pair< int, int > max_charges
std::pair< int, int > init_charges
std::pair< int, int > charges_per_use
std::pair< time_duration, time_duration > time
relic_recharge_type type = relic_recharge_type::NUM
relic_recharge_has has = relic_recharge_has::NUM
int power_level = 0
Detailed Description
Definition at line 159 of file relic.h.
Member Function Documentation
deserialize()
void relic_charge_template::deserialize (const JsonObject & jo)
Definition at line 242 of file relic.cpp.
 {
     load( jo );
 }
References relic_procgen_data::load().
generate()
relic_charge_info relic_charge_template::generate () const
Definition at line 270 of file relic.cpp.
 {
     relic_charge_info ret;
     ret.max_charges = rng( max_charges.first, max_charges.second );
     ret.charges_per_use = rng( charges_per_use.first, charges_per_use.second );
     ret.charges = std::min( rng( init_charges.first, init_charges.second ), ret.max_charges );
     ret.activation_time = rng( time.first, time.second );
     ret.type = type;
     ret.power = power_level;
     return ret;
 }
References min(), relic_procgen_data::power_level(), cata::hash64_detail::ret, and rng().
Referenced by relic_procgen_data::generate().
load()
void relic_charge_template::load (const JsonObject & jo)
Definition at line 247 of file relic.cpp.
 {
     int tmp_power = 0;
     const JsonObject max_charge = jo.get_object( "max_charges" );
     max_charge.read( "range", max_charges );
     max_charge.read( "power", tmp_power );
     power_level += tmp_power;
     const JsonObject charge = jo.get_object( "charges" );
     charge.read( "range", init_charges );
     charge.read( "power", tmp_power );
     power_level += tmp_power;
     const JsonObject init_charge = jo.get_object( "charges_per_use" );
     init_charge.read( "range", charges_per_use );
     init_charge.read( "power", tmp_power );
     power_level += tmp_power;
     jo.read( "recharge_type", type );
     jo.read( "time", time );
 }
References JsonObject::get_object(), relic_procgen_data::power_level(), and JsonObject::read().
Referenced by relic_procgen_data::load().
Member Data Documentation
charges_per_use
std::pair<int, int> relic_charge_template::charges_per_use
Definition at line 162 of file relic.h.
has
relic_recharge_has relic_charge_template::has = relic_recharge_has::NUM
Definition at line 165 of file relic.h.
init_charges
std::pair<int, int> relic_charge_template::init_charges
Definition at line 161 of file relic.h.
max_charges
std::pair<int, int> relic_charge_template::max_charges
Definition at line 160 of file relic.h.
power_level
int relic_charge_template::power_level = 0
Definition at line 167 of file relic.h.
time
std::pair<time_duration, time_duration> relic_charge_template::time
Definition at line 163 of file relic.h.
type
relic_recharge_type relic_charge_template::type = relic_recharge_type::NUM
Definition at line 164 of file relic.h.
The documentation for this struct was generated from the following files:
src/relic.h
src/relic.cpp