Cataclysm DDA: ter_t Struct Reference
ter_t Struct Reference
#include <mapdata.h>
Public Member Functions
ter_t ()
bool is_null () const
void load (const JsonObject &jo, const std::string &src) override
void check () const override
Public Member Functions inherited from map_data_common_t
virtual ~map_data_common_t ()=default
bool has_curtains () const
std::string name () const
bool can_examine (const tripoint &examp) const
bool has_examine (iexamine_examine_function func) const
bool has_examine (const std::string &action) const
void set_examine (iexamine_functions func)
void examine (Character &, const tripoint &) const
void load_symbol (const JsonObject &jo, const std::string &context)
const std::set< std::string > & get_flags () const
bool has_flag (const std::string &flag) const
bool has_flag (const ter_furn_flag flag) const
void extraprocess_flags (ter_furn_flag flag)
void set_flag (const std::string &flag)
void set_flag (ter_furn_flag flag)
void set_connect_groups (const std::vector< std::string > &connect_groups_vec)
void set_connects_to (const std::vector< std::string > &connect_groups_vec)
void set_rotates_to (const std::vector< std::string > &connect_groups_vec)
void set_groups (std::bitset< NUM_TERCONN > &bits, const std::vector< std::string > &connect_groups_vec)
bool in_connect_groups (const std::bitset< NUM_TERCONN > &test_connect_group) const
int symbol () const
nc_color color () const
const harvest_id & get_harvest () const
const std::set< std::string > & get_harvest_names () const
Returns a set of names of the items that would be dropped.
std::string extended_description () const
bool is_flammable () const
Static Public Member Functions
static size_t count ()
Public Attributes
std::vector< std::pair< ter_str_id, mod_id > > src
ter_str_id id
ter_str_id open
ter_str_id close
ter_str_id lockpick_result
translation lockpick_message
cata::value_ptr< activity_data_ter > boltcut
cata::value_ptr< activity_data_ter > hacksaw
cata::value_ptr< activity_data_ter > oxytorch
cata::value_ptr< activity_data_ter > prying
std::string trap_id_str
ter_str_id transforms_into
ter_str_id roof
trap_id trap
std::set< emit_id > emissions
std::set< itype_id > allowed_template_id
Public Attributes inherited from map_data_common_t
map_bash_info bash
map_deconstruct_info deconstruct
cata::value_ptr< map_shoot_info > shoot
ter_str_id curtain_transform
std::array< int, NUM_SEASONS > symbol_
int light_emitted = 0
int movecost = 0
int heat_radiation = 0
int coverage = 0
units::temperature_delta floor_bedding_warmth = 0_C_delta
int comfort = 0
units::volume max_volume = DEFAULT_TILE_VOLUME
translation description
std::array< nc_color, NUM_SEASONS > color_
std::string looks_like
std::array< harvest_id, NUM_SEASONS > harvest_by_season
When will this terrain/furniture get harvested and what will drop? Note: This excludes items that take extra tools to harvest.
bool transparent = false
std::bitset< NUM_TERCONN > connect_groups
std::bitset< NUM_TERCONN > connect_to_groups
std::bitset< NUM_TERCONN > rotate_to_groups
bool was_loaded = false
Additional Inherited Members
Protected Attributes inherited from map_data_common_t
translation name_
iexamine_functions examine_func
cata::clone_ptr< iexamine_actor > examine_actor
Detailed Description
Definition at line 598 of file mapdata.h.
Constructor & Destructor Documentation
ter_t()
ter_t::ter_t ()
Definition at line 511 of file mapdata.cpp.
              : open( ter_str_id::NULL_ID() ), close( ter_str_id::NULL_ID() ),
     transforms_into( ter_str_id::NULL_ID() ),
     roof( ter_str_id::NULL_ID() ), trap( tr_null ) {}
Member Function Documentation
check()
void ter_t::check () const override virtual
Reimplemented from map_data_common_t.
Definition at line 984 of file mapdata.cpp.
 {
     map_data_common_t::check();
     check_bash_items( bash, id.str(), true );
     check_decon_items( deconstruct, id.str(), true );
     if( !transforms_into.is_valid() ) {
         debugmsg( "invalid transforms_into %s for %s", transforms_into.c_str(), id.c_str() );
     }
     // Validate open/close transforms
     if( !open.is_valid() ) {
         debugmsg( "invalid terrain %s for opening %s", open.c_str(), id.c_str() );
     }
     if( !close.is_valid() ) {
         debugmsg( "invalid terrain %s for closing %s", close.c_str(), id.c_str() );
     }
     // Check transition consistency for opening/closing terrain. Has an obvious
     // exception for locked terrains - those aren't expected to be locked again
     if( open && open->close && open->close != id && !has_flag( ter_furn_flag::TFLAG_LOCKED ) ) {
         debugmsg( "opening terrain %s for %s doesn't reciprocate", open.c_str(), id.c_str() );
     }
     if( close && close->open && close->open != id && !has_flag( ter_furn_flag::TFLAG_LOCKED ) ) {
         debugmsg( "closing terrain %s for %s doesn't reciprocate", close.c_str(), id.c_str() );
     }
     // Validate curtain transforms
     if( has_examine( iexamine::curtains ) && !has_curtains() ) {
         debugmsg( "%s is a curtain, but has no curtain_transform", id.c_str() );
     }
     if( !has_examine( iexamine::curtains ) && has_curtains() ) {
         debugmsg( "%s is not a curtain, but has curtain_transform", id.c_str() );
     }
     if( !curtain_transform.is_empty() && !curtain_transform.is_valid() ) {
         debugmsg( "%s has invalid curtain transform target %s", id.c_str(), curtain_transform.c_str() );
     }
     // Validate generic transforms
     if( transforms_into && transforms_into == id ) {
         debugmsg( "%s transforms_into itself", id.c_str() );
     }
     for( const emit_id &e : emissions ) {
         if( !e.is_valid() ) {
             debugmsg( "ter %s has invalid emission %s set", id.c_str(), e.str().c_str() );
         }
     }
 }
References map_data_common_t::bash, string_id< T >::c_str(), map_data_common_t::check(), check_bash_items(), check_decon_items(), close, map_data_common_t::curtain_transform, iexamine::curtains(), debugmsg, map_data_common_t::deconstruct, emissions, map_data_common_t::has_curtains(), map_data_common_t::has_examine(), map_data_common_t::has_flag(), string_id< T >::is_empty(), string_id< T >::is_valid(), open, TFLAG_LOCKED, and transforms_into.
count()
size_t ter_t::count () static
Definition at line 775 of file mapdata.cpp.
 {
     return terrain_data.size();
 }
References anonymous_namespace{mapdata.cpp}::terrain_data.
is_null()
bool ter_t::is_null () const
Definition at line 864 of file mapdata.cpp.
 {
     return id == ter_str_id::NULL_ID();
 }
References string_id< ter_t >::NULL_ID().
Referenced by iuse::boltcutters(), iuse::crowbar(), hacksaw_activity_actor::finish(), boltcutting_activity_actor::finish(), oxytorch_activity_actor::finish(), iuse::hacksaw(), prying_activity_actor::handle_prying(), prying_activity_actor::handle_prying_nails(), iuse::oxytorch(), boltcutting_activity_actor::start(), hacksaw_activity_actor::start(), oxytorch_activity_actor::start(), and prying_activity_actor::start().
load()
void ter_t::load (const JsonObject & jo, const std::string & src) override virtual
Reimplemented from map_data_common_t.
Definition at line 869 of file mapdata.cpp.
 {
     map_data_common_t::load( jo, src );
     mandatory( jo, was_loaded, "name", name_ );
     mandatory( jo, was_loaded, "move_cost", movecost );
     optional( jo, was_loaded, "coverage", coverage );
     assign( jo, "max_volume", max_volume, src == "dda" );
     optional( jo, was_loaded, "trap", trap_id_str );
     optional( jo, was_loaded, "heat_radiation", heat_radiation );
     optional( jo, was_loaded, "light_emitted", light_emitted );
     int legacy_floor_bedding_warmth = units::to_legacy_bodypart_temp_delta( floor_bedding_warmth );
     optional( jo, was_loaded, "floor_bedding_warmth", legacy_floor_bedding_warmth, 0 );
     floor_bedding_warmth = units::from_legacy_bodypart_temp_delta( legacy_floor_bedding_warmth );
     optional( jo, was_loaded, "comfort", comfort, 0 );
     load_symbol( jo, "terrain " + id.str() );
     trap = tr_null;
     transparent = false;
     connect_groups.reset();
     connect_to_groups.reset();
     rotate_to_groups.reset();
     for( auto &flag : jo.get_string_array( "flags" ) ) {
         set_flag( flag );
     }
     // connect_to_groups is initialized to none, then terrain flags are set, then finally
     // connections from JSON are set. This is so that wall flags can set wall connections
     // but can be overridden by explicit connections in JSON.
     if( jo.has_member( "connect_groups" ) ) {
         set_connect_groups( jo.get_as_string_array( "connect_groups" ) );
     }
     if( jo.has_member( "connects_to" ) ) {
         set_connects_to( jo.get_as_string_array( "connects_to" ) );
     }
     if( jo.has_member( "rotates_to" ) ) {
         set_rotates_to( jo.get_as_string_array( "rotates_to" ) );
     }
     optional( jo, was_loaded, "allowed_template_ids", allowed_template_id );
     optional( jo, was_loaded, "open", open, ter_str_id::NULL_ID() );
     optional( jo, was_loaded, "close", close, ter_str_id::NULL_ID() );
     optional( jo, was_loaded, "transforms_into", transforms_into, ter_str_id::NULL_ID() );
     optional( jo, was_loaded, "roof", roof, ter_str_id::NULL_ID() );
     optional( jo, was_loaded, "lockpick_result", lockpick_result, ter_str_id::NULL_ID() );
     optional( jo, was_loaded, "lockpick_message", lockpick_message, translation() );
     oxytorch = cata::make_value<activity_data_ter>();
     if( jo.has_object( "oxytorch" ) ) {
         oxytorch->load( jo.get_object( "oxytorch" ) );
     }
     boltcut = cata::make_value<activity_data_ter>();
     if( jo.has_object( "boltcut" ) ) {
         boltcut->load( jo.get_object( "boltcut" ) );
     }
     hacksaw = cata::make_value<activity_data_ter>();
     if( jo.has_object( "hacksaw" ) ) {
         hacksaw->load( jo.get_object( "hacksaw" ) );
     }
     prying = cata::make_value<activity_data_ter>();
     if( jo.has_object( "prying" ) ) {
         prying->load( jo.get_object( "prying" ) );
     }
     optional( jo, was_loaded, "emissions", emissions );
     bash.load( jo, "bash", map_bash_info::terrain, "terrain " + id.str() );
     deconstruct.load( jo, "deconstruct", false, "terrain " + id.str() );
 }
References allowed_template_id, assign(), map_data_common_t::bash, boltcut, close, map_data_common_t::comfort, map_data_common_t::connect_groups, map_data_common_t::connect_to_groups, map_data_common_t::coverage, map_data_common_t::deconstruct, emissions, map_data_common_t::floor_bedding_warmth, units::from_legacy_bodypart_temp_delta(), JsonObject::get_as_string_array(), JsonObject::get_object(), JsonObject::get_string_array(), hacksaw, JsonObject::has_member(), JsonObject::has_object(), map_data_common_t::heat_radiation, map_data_common_t::light_emitted, map_data_common_t::load(), map_deconstruct_info::load(), map_bash_info::load(), map_data_common_t::load_symbol(), lockpick_message, lockpick_result, mandatory, map_data_common_t::max_volume, map_data_common_t::movecost, map_data_common_t::name_, string_id< ter_t >::NULL_ID(), open, optional(), oxytorch, prying, roof, map_data_common_t::rotate_to_groups, map_data_common_t::set_connect_groups(), map_data_common_t::set_connects_to(), map_data_common_t::set_flag(), map_data_common_t::set_rotates_to(), src, map_bash_info::terrain, units::to_legacy_bodypart_temp_delta(), tr_null, transforms_into, map_data_common_t::transparent, trap_id_str, and map_data_common_t::was_loaded.
Member Data Documentation
allowed_template_id
std::set<itype_id> ter_t::allowed_template_id
Definition at line 621 of file mapdata.h.
Referenced by load(), and iexamine::nanofab().
boltcut
cata::value_ptr<activity_data_ter> ter_t::boltcut
Definition at line 609 of file mapdata.h.
Referenced by iuse::boltcutters(), boltcutting_activity_actor::finish(), load(), and boltcutting_activity_actor::start().
close
ter_str_id ter_t::close
Definition at line 604 of file mapdata.h.
Referenced by check(), iexamine::curtains(), load(), and open().
emissions
std::set<emit_id> ter_t::emissions
Definition at line 620 of file mapdata.h.
Referenced by map::actualize(), check(), load(), and map::ter_set().
hacksaw
cata::value_ptr<activity_data_ter> ter_t::hacksaw
Definition at line 610 of file mapdata.h.
Referenced by hacksaw_activity_actor::finish(), iuse::hacksaw(), load(), and hacksaw_activity_actor::start().
id
ter_str_id ter_t::id
Definition at line 602 of file mapdata.h.
Referenced by apply< ter_t >(), map::bash_ter_furn(), colorized_ter_name_flags_at(), get_alt_ter(), ter_furn_transform::transform(), editmap::update_view_with_help(), and map::valid_move().
lockpick_message
translation ter_t::lockpick_message
Definition at line 607 of file mapdata.h.
Referenced by lockpick_activity_actor::finish(), and load().
lockpick_result
ter_str_id ter_t::lockpick_result
Definition at line 606 of file mapdata.h.
Referenced by lockpick_activity_actor::finish(), and load().
open
ter_str_id ter_t::open
Definition at line 603 of file mapdata.h.
Referenced by check(), colorized_ter_name_flags_at(), and load().
oxytorch
cata::value_ptr<activity_data_ter> ter_t::oxytorch
Definition at line 611 of file mapdata.h.
Referenced by oxytorch_activity_actor::finish(), load(), iuse::oxytorch(), and oxytorch_activity_actor::start().
prying
cata::value_ptr<activity_data_ter> ter_t::prying
Definition at line 612 of file mapdata.h.
Referenced by iuse::crowbar(), prying_activity_actor::handle_prying(), prying_activity_actor::handle_prying_nails(), load(), iexamine::locked_object(), and prying_activity_actor::start().
roof
ter_str_id ter_t::roof
Definition at line 616 of file mapdata.h.
Referenced by construct::add_roof(), map::add_roofs(), complete_construction(), map::get_roof(), and load().
src
std::vector<std::pair<ter_str_id, mod_id> > ter_t::src
Definition at line 600 of file mapdata.h.
Referenced by game::extended_description(), and load().
transforms_into
ter_str_id ter_t::transforms_into
Definition at line 615 of file mapdata.h.
Referenced by check(), map::get_ter_transforms_into(), and load().
trap
trap_id ter_t::trap
Definition at line 618 of file mapdata.h.
Referenced by jmapgen_terrain::apply(), submap::is_open_air(), iexamine::ledge(), MapExtras::place_trap_if_clear(), set_ter_ids(), map::ter_set(), and map::tr_at().
trap_id_str
std::string ter_t::trap_id_str
Definition at line 614 of file mapdata.h.
Referenced by load(), and set_ter_ids().
The documentation for this struct was generated from the following files:
src/mapdata.h
src/mapdata.cpp