Cataclysm DDA: poisson_distribution Struct Reference
poisson_distribution Struct Reference
Public Member Functions
poisson_distribution (int lo, int hi, double mean)
int minimum () const override
int sample () override
std::string description () const override
Public Member Functions inherited from int_distribution_impl
virtual ~int_distribution_impl ()=default
Public Attributes
std::poisson_distribution< int > dist
Public Attributes inherited from int_distribution_impl
int blo = 0
int bhi = INT_MAX
Detailed Description
Definition at line 89 of file distribution.cpp.
Constructor & Destructor Documentation
poisson_distribution()
poisson_distribution::poisson_distribution (int lo, int hi, double mean) inline explicit
Definition at line 92 of file distribution.cpp.
         : dist( mean ) {
         blo = lo;
         bhi = hi;
     }
References int_distribution_impl::bhi, int_distribution_impl::blo, and cata::hash64_detail::lo.
Member Function Documentation
description()
std::string poisson_distribution::description () const inline override virtual
Implements int_distribution_impl.
Definition at line 108 of file distribution.cpp.
{
         // NOLINTNEXTLINE(cata-translate-string-literal)
         return string_format( "Poisson(%.0f)", dist.mean() );
     }
References dist, and string_format().
minimum()
int poisson_distribution::minimum () const inline override virtual
Implements int_distribution_impl.
Definition at line 98 of file distribution.cpp.
{
         return 0;
     }
sample()
int poisson_distribution::sample () inline override virtual
Implements int_distribution_impl.
Definition at line 102 of file distribution.cpp.
{
         int rvalue = std::min( dist( rng_get_engine() ), bhi );
         rvalue = std::max( rvalue, blo );
         return rvalue;
     }
References int_distribution_impl::bhi, int_distribution_impl::blo, dist, max(), min(), and rng_get_engine().
Member Data Documentation
dist
std::poisson_distribution<int> poisson_distribution::dist
Definition at line 90 of file distribution.cpp.
Referenced by description(), and sample().
The documentation for this struct was generated from the following file:
src/distribution.cpp