Cataclysm DDA: WORLD Struct Reference
WORLD Struct Reference
#include <worldfactory.h>
Public Member Functions
std::string folder_path () const
cata_path folder_path_path () const
WORLD ()
WORLD (const std::string &name)
void COPY_WORLD (const WORLD *world_to_copy)
bool save_exists (const save_t &name) const
void add_save (const save_t &name)
bool save (bool is_conversion=false) const
void load_options (const JsonArray &options_json)
bool load_options ()
Public Attributes
std::string world_name
options_manager::options_container WORLD_OPTIONS
std::vector< save_t > world_saves
std::vector< mod_id > active_mod_order
A (possibly empty) list of (idents of) mods that should be loaded for this world.
Detailed Description
Definition at line 52 of file worldfactory.h.
Constructor & Destructor Documentation
WORLD() [1/2]
WORLD::WORLD ()
Definition at line 71 of file worldfactory.cpp.
 {
     world_name = get_next_valid_worldname();
     WORLD_OPTIONS = get_options().get_world_defaults();
     world_saves.clear();
     active_mod_order = world_generator->get_mod_manager().get_default_mods();
 }
References active_mod_order, get_next_valid_worldname(), get_options(), options_manager::get_world_defaults(), world_generator, world_name, WORLD_OPTIONS, and world_saves.
WORLD() [2/2]
WORLD::WORLD (const std::string & name) explicit
Definition at line 80 of file worldfactory.cpp.
 {
     world_name = name;
     WORLD_OPTIONS = get_options().get_world_defaults();
     world_saves.clear();
     active_mod_order = world_generator->get_mod_manager().get_default_mods();
 }
References active_mod_order, get_options(), options_manager::get_world_defaults(), om_direction::name(), world_generator, world_name, WORLD_OPTIONS, and world_saves.
Member Function Documentation
add_save()
void WORLD::add_save (const save_t & name)
Definition at line 111 of file worldfactory.cpp.
 {
     if( !save_exists( name ) ) {
         world_saves.push_back( name );
     }
 }
References om_direction::name(), save_exists(), and world_saves.
COPY_WORLD()
void WORLD::COPY_WORLD (const WORLD * world_to_copy)
Definition at line 89 of file worldfactory.cpp.
 {
     world_name = world_to_copy->world_name + "_copy";
     WORLD_OPTIONS = world_to_copy->WORLD_OPTIONS;
     active_mod_order = world_to_copy->active_mod_order;
 }
References active_mod_order, world_name, and WORLD_OPTIONS.
folder_path()
std::string WORLD::folder_path () const
Returns
A path to a folder in the file system that should contain all the world specific files. It depends on world_name, changing that will also change the result of this function.
Definition at line 96 of file worldfactory.cpp.
 {
     return PATH_INFO::savedir() + world_name;
 }
References PATH_INFO::savedir(), and world_name.
Referenced by worldfactory::delete_world(), worldfactory::init(), and save().
folder_path_path()
cata_path WORLD::folder_path_path () const
Definition at line 101 of file worldfactory.cpp.
 {
     return PATH_INFO::savedir_path() / world_name;
 }
References PATH_INFO::savedir_path(), and world_name.
Referenced by mod_manager::get_mods_list_file(), get_playtime_from_save(), and load_options().
load_options() [1/2]
bool WORLD::load_options ()
Definition at line 1985 of file worldfactory.cpp.
 {
     WORLD_OPTIONS = get_options().get_world_defaults();
     const cata_path path = folder_path_path() / PATH_INFO::worldoptions();
     return read_from_file_optional_json( path, [this]( const JsonValue & jsin ) {
         this->load_options( jsin );
     } );
 }
References folder_path_path(), get_options(), options_manager::get_world_defaults(), read_from_file_optional_json(), WORLD_OPTIONS, and PATH_INFO::worldoptions().
load_options() [2/2]
void WORLD::load_options (const JsonArray & options_json)
Definition at line 1965 of file worldfactory.cpp.
 {
     options_manager &opts = get_options();
     for( JsonObject jo : options_json ) {
         jo.allow_omitted_members();
         const std::string name = opts.migrateOptionName( jo.get_string( "name" ) );
         const std::string value = opts.migrateOptionValue( jo.get_string( "name" ),
                                   jo.get_string( "value" ) );
         if( opts.has_option( name ) && opts.get_option( name ).getPage() == "world_default" ) {
             WORLD_OPTIONS[ name ].setValue( value );
         }
     }
     // for legacy saves, try to simulate old city_size based density
     if( WORLD_OPTIONS.count( "CITY_SPACING" ) == 0 ) {
         WORLD_OPTIONS["CITY_SPACING"].setValue( 5 - get_option<int>( "CITY_SIZE" ) / 3 );
     }
 }
References options_manager::get_option(), get_options(), options_manager::cOpt::getPage(), options_manager::has_option(), options_manager::migrateOptionName(), options_manager::migrateOptionValue(), om_direction::name(), and WORLD_OPTIONS.
save()
bool WORLD::save (bool is_conversion = false) const
Definition at line 293 of file worldfactory.cpp.
 {
     if( !assure_dir_exist( folder_path() ) ) {
         debugmsg( "Unable to create or open world[%s] directory for saving", world_name );
         DebugLog( D_ERROR, DC_ALL ) << "Unable to create or open world[" << world_name <<
                                     "] directory for saving";
         return false;
     }
     if( !is_conversion ) {
         const auto savefile = folder_path() + "/" + PATH_INFO::worldoptions();
         const bool saved = write_to_file( savefile, [&]( std::ostream & fout ) {
             JsonOut jout( fout );
             jout.start_array();
             for( const auto &elem : WORLD_OPTIONS ) {
                 // Skip hidden option because it is set by mod and should not be saved
                 if( !elem.second.getDefaultText().empty() ) {
                     jout.start_object();
                     jout.member( "info", elem.second.getTooltip() );
                     jout.member( "default", elem.second.getDefaultText( false ) );
                     jout.member( "name", elem.first );
                     jout.member( "value", elem.second.getValue( true ) );
                     jout.end_object();
                 }
             }
             jout.end_array();
         }, _( "world data" ) );
         if( !saved ) {
             return false;
         }
     }
     world_generator->get_mod_manager().save_mods_list( this );
     return true;
 }
References _, assure_dir_exist(), D_ERROR, DC_ALL, DebugLog(), debugmsg, JsonOut::end_array(), JsonOut::end_object(), folder_path(), JsonOut::member(), JsonOut::start_array(), JsonOut::start_object(), world_generator, world_name, WORLD_OPTIONS, PATH_INFO::worldoptions(), and write_to_file().
save_exists()
bool WORLD::save_exists (const save_t & name) const
Definition at line 106 of file worldfactory.cpp.
 {
     return std::find( world_saves.begin(), world_saves.end(), name ) != world_saves.end();
 }
References om_direction::name(), and world_saves.
Referenced by add_save(), and game::quickload().
Member Data Documentation
active_mod_order
std::vector<mod_id> WORLD::active_mod_order
A (possibly empty) list of (idents of) mods that should be loaded for this world.
Definition at line 69 of file worldfactory.h.
Referenced by COPY_WORLD(), mod_manager::load_mods_list(), main_menu::opening_screen(), mod_manager::save_mods_list(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), and WORLD().
world_name
std::string WORLD::world_name
Definition at line 62 of file worldfactory.h.
Referenced by COPY_WORLD(), folder_path(), folder_path_path(), main_menu::load_game(), game::quickload(), save(), worldfactory::show_worldgen_advanced(), worldfactory::show_worldgen_basic(), WORLD(), and main_menu::world_tab().
WORLD_OPTIONS
options_manager::options_container WORLD::WORLD_OPTIONS
Definition at line 63 of file worldfactory.h.
Referenced by COPY_WORLD(), worldfactory::init(), load_options(), save(), worldfactory::set_active_world(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_options(), and WORLD().
world_saves
std::vector<save_t> WORLD::world_saves
Definition at line 64 of file worldfactory.h.
Referenced by add_save(), worldfactory::delete_world(), worldfactory::init(), game::load(), main_menu::load_character_tab(), worldfactory::pick_world(), save_exists(), worldfactory::show_worldgen_basic(), and WORLD().
The documentation for this struct was generated from the following files:
src/worldfactory.h
src/worldfactory.cpp