Cataclysm DDA: inventory_selector_save_state Struct Reference
inventory_selector_save_state Struct Reference
#include <inventory_ui.h>
Public Member Functions
void serialize (JsonOut &json) const
void deserialize (JsonObject const &jo)
Public Attributes
inventory_selector::uimode uimode = inventory_selector::uimode::categories
Detailed Description
Definition at line 1154 of file inventory_ui.h.
Member Function Documentation
deserialize()
void inventory_selector_save_state::deserialize (JsonObject const & jo)
Definition at line 298 of file inventory_ui.cpp.
 {
     jo.read( "uimode", uimode );
 }
References JsonObject::read(), and uimode.
serialize()
void inventory_selector_save_state::serialize (JsonOut & json) const
Definition at line 292 of file inventory_ui.cpp.
 {
     json.start_object();
     json.member( "uimode", uimode );
     json.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), JsonOut::start_object(), and uimode.
Member Data Documentation
uimode
inventory_selector::uimode inventory_selector_save_state::uimode = inventory_selector::uimode::categories
Definition at line 1156 of file inventory_ui.h.
Referenced by deserialize(), serialize(), and inventory_selector::~inventory_selector().
The documentation for this struct was generated from the following files:
src/inventory_ui.h
src/inventory_ui.cpp