Cataclysm DDA: inclusive_rectangle< Point, > Struct Template Reference
inclusive_rectangle< Point, > Struct Template Reference
#include <cuboid_rectangle.h>
Public Types
using base = rectangle< Point >
Public Member Functions
constexpr bool contains (const Point &p) const
constexpr bool overlaps (const rectangle< Point > &r) const
Public Member Functions inherited from rectangle< Point, >
constexpr rectangle ()=default
constexpr rectangle (const Point &P_MIN, const Point &P_MAX)
Public Attributes
Point p_min
Point p_max
Public Attributes inherited from rectangle< Point, >
Point p_min
Point p_max
Detailed Description
template<typename Point, decltype(std::declval< rectangle< Point >>(), int()) = 0>
struct inclusive_rectangle< Point, >
Definition at line 48 of file cuboid_rectangle.h.
Member Typedef Documentation
base
template<typename Point , decltype(std::declval< rectangle< Point >>(), int()) = 0> using inclusive_rectangle< Point, >::base = rectangle<Point>
Definition at line 49 of file cuboid_rectangle.h.
Member Function Documentation
contains()
template<typename Point , decltype(std::declval< rectangle< Point >>(), int()) = 0> constexpr bool inclusive_rectangle< Point, >::contains (const Point & p) const inline constexpr
Definition at line 54 of file cuboid_rectangle.h.
{
         using Traits = point_traits<Point>;
         return Traits::x( p ) >= Traits::x( p_min ) && Traits::x( p ) <= Traits::x( p_max ) &&
                Traits::y( p ) >= Traits::y( p_min ) && Traits::y( p ) <= Traits::y( p_max );
     }
References inclusive_rectangle< Point, >::p_max, and inclusive_rectangle< Point, >::p_min.
Referenced by vehicle::balanced_wheel_config(), scrollbar::handle_dragging(), scrolling_text_view::handle_navigation(), multiline_list::handle_navigation(), mouse_in_window(), map_memory::prepare_region(), and map::scent_blockers().
overlaps()
template<typename Point , decltype(std::declval< rectangle< Point >>(), int()) = 0> constexpr bool inclusive_rectangle< Point, >::overlaps (const rectangle< Point > & r) const inline constexpr
Definition at line 59 of file cuboid_rectangle.h.
{
         using Traits = point_traits<Point>;
         return !( Traits::x( r.p_min ) > Traits::x( p_max ) ||
                   Traits::y( r.p_min ) > Traits::y( p_max ) ||
                   Traits::x( p_min ) > Traits::x( r.p_max ) ||
                   Traits::y( p_min ) > Traits::y( r.p_max ) );
     }
References rectangle< Point, >::p_max, inclusive_rectangle< Point, >::p_max, rectangle< Point, >::p_min, and inclusive_rectangle< Point, >::p_min.
Referenced by zone_data::toggle_display().
Member Data Documentation
p_max
template<typename Point , decltype(std::declval< rectangle< Point >>(), int()) = 0> Point rectangle< Point, >::p_max
Definition at line 20 of file cuboid_rectangle.h.
Referenced by jmapgen_vehicle::check(), clamp(), inclusive_rectangle< Point, >::contains(), scrollbar::handle_dragging(), midpoint(), and inclusive_rectangle< Point, >::overlaps().
p_min
template<typename Point , decltype(std::declval< rectangle< Point >>(), int()) = 0> Point rectangle< Point, >::p_min
Definition at line 19 of file cuboid_rectangle.h.
Referenced by jmapgen_vehicle::check(), clamp(), inclusive_rectangle< Point, >::contains(), scrollbar::handle_dragging(), midpoint(), and inclusive_rectangle< Point, >::overlaps().
The documentation for this struct was generated from the following file:
src/cuboid_rectangle.h