Cataclysm DDA: shopkeeper_cons_rates Struct Reference
shopkeeper_cons_rates Struct Reference
#include <shop_cons_rate.h>
Public Member Functions
shopkeeper_cons_rates ()=default
void load (const JsonObject &jo, std::string_view src)
void check () const
int get_rate (item const &it, npc const &beta) const
bool matches (item const &it, npc const &beta) const
Static Public Member Functions
static void reset ()
static const std::vector< shopkeeper_cons_rates > & get_all ()
static void load_rate (const JsonObject &jo, std::string const &src)
static void check_all ()
Public Attributes
shopkeeper_cons_rates_id id
bool was_loaded = false
int default_rate = -1
units::money junk_threshold = 1_cent
std::vector< shopkeeper_cons_rate_entry > rates
Detailed Description
Definition at line 44 of file shop_cons_rate.h.
Constructor & Destructor Documentation
shopkeeper_cons_rates()
shopkeeper_cons_rates::shopkeeper_cons_rates () default
Member Function Documentation
check()
void shopkeeper_cons_rates::check () const
Definition at line 145 of file shop_cons_rate.cpp.
 {
     for( const shopkeeper_cons_rate_entry &rate : rates ) {
         if( !rate.itype.is_empty() &&
             ( !rate.category.is_empty() || !rate.item_group.is_empty() ) ) {
             debugmsg( "category/item_group filters are redundant when itype is specified in %s.",
                       id.c_str() );
         }
         if( rate.itype.is_empty() && rate.category.is_empty() && rate.item_group.is_empty() ) {
             debugmsg( "empty shop rate filter in %s.", id.c_str() );
         }
     }
 }
References debugmsg, and rates.
check_all()
void shopkeeper_cons_rates::check_all () static
Definition at line 93 of file shop_cons_rate.cpp.
 {
     shop_cons_rate_factory.check();
 }
References anonymous_namespace{shop_cons_rate.cpp}::shop_cons_rate_factory.
Referenced by DynamicDataLoader::check_consistency().
get_all()
std::vector< shopkeeper_cons_rates > const & shopkeeper_cons_rates::get_all () static
Definition at line 78 of file shop_cons_rate.cpp.
 {
     return shop_cons_rate_factory.get_all();
 }
References anonymous_namespace{shop_cons_rate.cpp}::shop_cons_rate_factory.
get_rate()
int shopkeeper_cons_rates::get_rate (item const & it, npc const & beta) const
Definition at line 159 of file shop_cons_rate.cpp.
 {
     if( it.type->price_post < junk_threshold ) {
         return -1;
     }
     for( auto rit = rates.crbegin(); rit != rates.crend(); ++rit ) {
         if( rit->matches( it, beta ) ) {
             return rit->rate;
         }
     }
     return default_rate;
 }
References default_rate, junk_threshold, itype::price_post, rates, and item::type.
Referenced by anonymous_namespace{npctrade_utils.cpp}::_consume_item().
load()
void shopkeeper_cons_rates::load (const JsonObject & jo, std::string_view src)
Definition at line 138 of file shop_cons_rate.cpp.
 {
     optional( jo, was_loaded, "default_rate", default_rate );
     optional( jo, was_loaded, "junk_threshold", junk_threshold, money_reader {}, 1_cent );
     optional( jo, was_loaded, "rates", rates, shopkeeper_cons_rates_reader {} );
 }
References default_rate, junk_threshold, optional(), rates, and was_loaded.
load_rate()
void shopkeeper_cons_rates::load_rate (const JsonObject & jo, std::string const & src) static
Definition at line 83 of file shop_cons_rate.cpp.
 {
     shop_cons_rate_factory.load( jo, src );
 }
References anonymous_namespace{shop_cons_rate.cpp}::shop_cons_rate_factory.
Referenced by DynamicDataLoader::initialize().
matches()
bool shopkeeper_cons_rates::matches (item const & it, npc const & beta) const
Definition at line 185 of file shop_cons_rate.cpp.
 {
     return it.type->price_post < junk_threshold ||
            std::any_of( rates.begin(), rates.end(),
     [&it, &beta]( shopkeeper_cons_rate_entry const & rit ) {
         return rit.matches( it, beta );
     } );
 }
References junk_threshold, itype::price_post, rates, and item::type.
reset()
void shopkeeper_cons_rates::reset () static
Definition at line 73 of file shop_cons_rate.cpp.
 {
     shop_cons_rate_factory.reset();
 }
References anonymous_namespace{shop_cons_rate.cpp}::shop_cons_rate_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
default_rate
int shopkeeper_cons_rates::default_rate = -1
Definition at line 48 of file shop_cons_rate.h.
Referenced by get_rate(), and load().
id
shopkeeper_cons_rates_id shopkeeper_cons_rates::id
Definition at line 45 of file shop_cons_rate.h.
junk_threshold
units::money shopkeeper_cons_rates::junk_threshold = 1_cent
Definition at line 49 of file shop_cons_rate.h.
Referenced by get_rate(), load(), and matches().
rates
std::vector<shopkeeper_cons_rate_entry> shopkeeper_cons_rates::rates
Definition at line 50 of file shop_cons_rate.h.
Referenced by check(), get_rate(), load(), and matches().
was_loaded
bool shopkeeper_cons_rates::was_loaded = false
Definition at line 46 of file shop_cons_rate.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/shop_cons_rate.h
src/shop_cons_rate.cpp