Cataclysm DDA: vehicle_prototype Struct Reference
vehicle_prototype Struct Reference
Prototype of a vehicle.
#include <veh_type.h>
Classes
struct part_def
struct zone_def
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
Static Public Member Functions
static void save_vehicle_as_prototype (const vehicle &veh, JsonOut &json)
Public Attributes
vproto_id id
translation name
std::vector< part_def > parts
std::vector< vehicle_item_spawn > item_spawns
std::vector< zone_def > zone_defs
shared_ptr_fast< vehicle > blueprint
Private Attributes
bool was_loaded = false
std::vector< std::pair< vproto_id, mod_id > > src
Friends
class generic_factory< vehicle_prototype >
struct mod_tracker
Detailed Description
Prototype of a vehicle.
The blueprint member is filled in during the finalizing, before that it is a nullptr. Creating a new vehicle copies the blueprint vehicle.
Definition at line 483 of file veh_type.h.
Member Function Documentation
load()
void vehicle_prototype::load (const JsonObject & jo, std::string_view src)
Definition at line 1266 of file veh_type.cpp.
 {
     vgroups[vgroup_id( id.str() )].add_vehicle( id, 100 );
     optional( jo, was_loaded, "name", name );
     const auto add_part_obj = [&]( const JsonObject & part, point pos ) {
         const auto [id, variant] = get_vpart_str_variant( part.get_string( "part" ) );
         part_def pt;
         pt.part = vpart_id( id );
         pt.variant = variant;
         pt.pos = pos;
         assign( part, "ammo", pt.with_ammo, true, 0, 100 );
         assign( part, "ammo_types", pt.ammo_types, true );
         assign( part, "ammo_qty", pt.ammo_qty, true, 0 );
         assign( part, "fuel", pt.fuel, true );
         assign( part, "tools", pt.tools, true );
         parts.emplace_back( pt );
     };
     const auto add_part_string = [&]( const std::string & part, point pos ) {
         const auto [id, variant] = get_vpart_str_variant( part );
         part_def pt;
         pt.part = vpart_id( id );
         pt.variant = variant;
         pt.pos = pos;
         parts.emplace_back( pt );
     };
     if( jo.has_member( "blueprint" ) ) {
         // currently unused, read to suppress unvisited members warning
         jo.get_array( "blueprint" );
     }
     for( JsonObject part : jo.get_array( "parts" ) ) {
         point pos = point( part.get_int( "x" ), part.get_int( "y" ) );
         if( part.has_string( "part" ) ) {
             add_part_obj( part, pos );
             debugmsg( "vehicle prototype '%s' uses deprecated string definition for part"
                       " '%s', use 'parts' array instead", id.str(), part.get_string( "part" ) );
         } else if( part.has_array( "parts" ) ) {
             for( const JsonValue entry : part.get_array( "parts" ) ) {
                 if( entry.test_string() ) {
                     std::string part_name = entry.get_string();
                     add_part_string( part_name, pos );
                 } else {
                     JsonObject subpart = entry.get_object();
                     add_part_obj( subpart, pos );
                 }
             }
         }
     }
     for( JsonObject spawn_info : jo.get_array( "items" ) ) {
         vehicle_item_spawn next_spawn;
         next_spawn.pos.x = spawn_info.get_int( "x" );
         next_spawn.pos.y = spawn_info.get_int( "y" );
         next_spawn.chance = spawn_info.get_int( "chance" );
         if( next_spawn.chance <= 0 || next_spawn.chance > 100 ) {
             debugmsg( "Invalid spawn chance in %s (%d, %d): %d%%",
                       name, next_spawn.pos.x, next_spawn.pos.y, next_spawn.chance );
         }
         // constrain both with_magazine and with_ammo to [0-100]
         next_spawn.with_magazine = std::max( std::min( spawn_info.get_int( "magazine",
                                              next_spawn.with_magazine ), 100 ), 0 );
         next_spawn.with_ammo = std::max( std::min( spawn_info.get_int( "ammo",
                                          next_spawn.with_ammo ), 100 ), 0 );
         if( spawn_info.has_array( "items" ) ) {
             //Array of items that all spawn together (i.e. jack+tire)
             spawn_info.read( "items", next_spawn.item_ids, true );
         } else if( spawn_info.has_string( "items" ) ) {
             //Treat single item as array
             // And read the gun variant (if it exists)
             if( spawn_info.has_string( "variant" ) ) {
                 const std::string variant = spawn_info.get_string( "variant" );
                 next_spawn.variant_ids.emplace_back( itype_id( spawn_info.get_string( "items" ) ), variant );
             } else {
                 next_spawn.item_ids.emplace_back( spawn_info.get_string( "items" ) );
             }
         }
         if( spawn_info.has_array( "item_groups" ) ) {
             //Pick from a group of items, just like map::place_items
             for( const std::string line : spawn_info.get_array( "item_groups" ) ) {
                 next_spawn.item_groups.emplace_back( line );
             }
         } else if( spawn_info.has_string( "item_groups" ) ) {
             next_spawn.item_groups.emplace_back( spawn_info.get_string( "item_groups" ) );
         }
         item_spawns.push_back( std::move( next_spawn ) );
     }
     for( JsonObject jzi : jo.get_array( "zones" ) ) {
         zone_type_id zone_type( jzi.get_member( "type" ).get_string() );
         std::string name;
         std::string filter;
         point pt( jzi.get_member( "x" ).get_int(), jzi.get_member( "y" ).get_int() );
         if( jzi.has_string( "name" ) ) {
             name = jzi.get_string( "name" );
         }
         if( jzi.has_string( "filter" ) ) {
             filter = jzi.get_string( "filter" );
         }
         zone_defs.emplace_back( zone_def{ zone_type, name, filter, pt } );
     }
 }
References vehicle_prototype::part_def::ammo_qty, vehicle_prototype::part_def::ammo_types, assign(), vehicle_item_spawn::chance, debugmsg, filter, vehicle_prototype::part_def::fuel, JsonObject::get_array(), JsonObject::get_int(), JsonObject::get_object(), JsonObject::get_string(), get_vpart_str_variant(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_string(), id, vehicle_item_spawn::item_groups, vehicle_item_spawn::item_ids, item_spawns, itype_id, line, max(), min(), name, optional(), vehicle_prototype::part_def::part, parts, point, math_opers::pos(), vehicle_item_spawn::pos, vehicle_prototype::part_def::pos, vehicle_prototype::part_def::tools, vehicle_prototype::part_def::variant, vehicle_item_spawn::variant_ids, vgroup_id, vgroups, was_loaded, vehicle_item_spawn::with_ammo, vehicle_prototype::part_def::with_ammo, vehicle_item_spawn::with_magazine, point::x, point::y, and zone_defs.
save_vehicle_as_prototype()
void vehicle_prototype::save_vehicle_as_prototype (const vehicle & veh, JsonOut & json) static
Definition at line 1378 of file veh_type.cpp.
 {
     static const std::string part_location_structure( "structure" );
     json.start_object();
     // Add some notes to the exported file.
     json.member( "//1",
                  "Although this vehicle can be readily spawned in game without further tweaking," );
     json.member( "//2",
                  "this is auto-generated by program, so please check against it before proceeding." );
     json.member( "//3",
                  "Only simple top-level items can be exported by this function.  Do not rely on this for exporting comestibles, containers, etc." );
     // Begin of the vehicle.
     json.member( "id", "/TO_BE_REPLACED/" );
     json.member( "type", "vehicle" );
     json.member( "name", "/TO_BE_REPLACED/" );
     std::map<point, std::list<const vehicle_part *>> vp_map;
     int mount_min_y = 123;
     int mount_max_y = -123;
     // Form a map of existing real parts
     // Structural parts first
     for( const vpart_reference &vpr : veh.get_all_parts() ) {
         const vehicle_part &p = vpr.part();
         if( p.is_fake ) {
             continue;
         }
         if( p.info().location == part_location_structure ) {
             vp_map[p.mount].push_front( &p );
             continue;
         }
         mount_max_y = mount_max_y < p.mount.y ? p.mount.y : mount_max_y;
         mount_min_y = mount_min_y > p.mount.y ? p.mount.y : mount_min_y;
         vp_map[p.mount].push_back( &p );
     }
     int mount_min_x = vp_map.begin()->first.x;
     int mount_max_x = vp_map.rbegin()->first.x;
     // print the vehicle's blueprint.
     json.member( "blueprint" );
     json.start_array();
     // let's start from the front of the vehicle, scanning by row.
     for( int x = mount_max_x; x >= mount_min_x; x-- ) {
         std::string row;
         for( int y = mount_min_y; y <= mount_max_y; y++ ) {
             if( veh.part_displayed_at( point( x, y ), false, true, true ) == -1 ) {
                 row += " ";
                 continue;
             }
             const vpart_display &c = veh.get_display_of_tile( point( x, y ), false, false, true, true );
             row += utf32_to_utf8( c.symbol );
         }
         json.write( row );
     }
     json.end_array();
     json.member( "parts" );
     json.start_array();
     // Used to flexibly print vehicle parts with possible non-default variants
     auto print_vp_with_variant = [&json]( const vehicle_part & vp ) {
         const vpart_info &vpi = vp.info();
         if( vp.variant == vpi.variant_default ) {
             json.write( vpi.id.str() );
             return;
         }
         std::string name_with_variant = vpi.id.str() + "#" + vp.variant;
         json.write( name_with_variant );
         return;
     };
     for( auto &vp_pos : vp_map ) {
         auto fake = make_shared_fast<vehicle>( vproto_id() );
         vehicle &fakev = *fake;
         auto iter = vp_pos.second.begin();
         // Ensure that the entries in the list can be installed in order.
         // Might be a infinite loop if debug hammerspace created improper parts combination.
         // So add a iteration limit to avoid this.
         int iteration = 0;
         for( ; iter != vp_pos.second.end(); ) {
             vehicle_part g = **iter;
             if( fakev.can_mount( point_zero, g.info() ).success() ) {
                 fakev.install_part( point_zero, std::move( g ) );
                 iter++;
                 continue;
             }
             iteration++;
             auto iter2 = std::next( iter, 1 );
             vp_pos.second.splice( vp_pos.second.end(), vp_pos.second, iter );
             iter = iter2;
             // It's impossible to hit this limit when a single mount point has fewer than 50 parts.
             // So we can assume only infinite loop hits this limit.
             if( iteration > 1250 ) {
                 debugmsg( "Error exporting vehicle: mount point (%d,%d) has illegal vehicle part sequence.",
                           vp_pos.first.x, vp_pos.first.y );
                 return;
             }
         }
         json.start_object();
         json.member( "x", vp_pos.first.x );
         json.member( "y", vp_pos.first.y );
         json.member( "parts" );
         json.start_array();
         for( const vehicle_part *vp : vp_pos.second ) {
             if( vp->is_tank() && vp->ammo_remaining() ) {
                 json.start_object();
                 json.member( "part" );
                 print_vp_with_variant( *vp );
                 json.member( "fuel", vp->ammo_current().str() );
                 json.end_object();
                 continue;
             } else if( vp->is_turret() && vp->ammo_remaining() ) {
                 json.start_object();
                 json.member( "part" );
                 print_vp_with_variant( *vp );
                 json.member( "ammo", 100 );
                 json.member( "ammo_types", vp->ammo_current().str() );
                 json.member( "ammo_qty" );
                 json.start_array();
                 int ammo_qty = vp->ammo_remaining();
                 json.write( ammo_qty );
                 json.write( ammo_qty );
                 json.end_array();
                 json.end_object();
                 continue;
             } else if( !veh.get_tools( *vp ).empty() ) {
                 json.start_object();
                 json.member( "part" );
                 print_vp_with_variant( *vp );
                 json.member( "tools" );
                 json.start_array();
                 for( const item &it : veh.get_tools( *vp ) ) {
                     json.write_as_string( it.typeId().str() );
                 }
                 json.end_array();
                 json.end_object();
             } else {
                 print_vp_with_variant( *vp );
             }
         }
         json.end_array();
         json.end_object();
     }
     json.end_array();
     // print top-level items ( contents are ignored )
     // For more complicated spawning of items, use itemgroup instead.
     json.member( "items" );
     json.start_array();
     for( const vpart_reference &vp : veh.get_any_parts( "CARGO" ) ) {
         if( vp.part().is_fake ) {
             continue;
         }
         const vehicle_stack &stack = veh.get_items( vp.part() );
         if( !stack.empty() ) {
             json.start_object();
             json.member( "x", vp.mount().x );
             json.member( "y", vp.mount().y );
             json.member( "chance", 100 );
             json.member( "items" );
             json.start_array();
             for( const item &it : stack ) {
                 json.write( it.typeId().str() );
             }
             json.end_array();
             json.end_object();
         }
     }
     json.end_array();
     json.member( "zones" );
     json.start_array();
     for( auto const &z : veh.loot_zones ) {
         json.start_object();
         json.member( "x", z.first.x );
         json.member( "y", z.first.y );
         json.member( "type", z.second.get_type().str() );
         json.end_object();
     }
     json.end_array();
     json.end_object();
 }
References vehicle_part::ammo_current(), vehicle_part::ammo_remaining(), c, vehicle::can_mount(), debugmsg, item_stack::empty(), JsonOut::end_array(), JsonOut::end_object(), Creature::fake, g, vehicle::get_all_parts(), vehicle::get_any_parts(), vehicle::get_display_of_tile(), vehicle::get_items(), vehicle::get_tools(), vpart_info::id, vehicle_part::info(), vehicle::install_part(), vehicle_part::is_fake, vehicle_part::is_tank(), vehicle_part::is_turret(), vpart_info::location, vehicle::loot_zones, JsonOut::member(), vehicle_part::mount, vehicle::part_displayed_at(), part_location_structure(), point, point_zero, JsonOut::start_array(), JsonOut::start_object(), string_id< T >::str(), ret_val_common::success(), utf32_to_utf8(), vpart_info::variant_default, JsonOut::write(), JsonOut::write_as_string(), and point::y.
Referenced by debug_menu::vehicle_export().
Friends And Related Function Documentation
generic_factory< vehicle_prototype >
friend class generic_factory< vehicle_prototype > friend
Definition at line 515 of file veh_type.h.
mod_tracker
friend struct mod_tracker friend
Definition at line 517 of file veh_type.h.
Member Data Documentation
blueprint
shared_ptr_fast<vehicle> vehicle_prototype::blueprint
Definition at line 509 of file veh_type.h.
Referenced by vehicles::finalize_prototypes(), and vehicle::vehicle().
id
vproto_id vehicle_prototype::id
Definition at line 503 of file veh_type.h.
Referenced by vehicles::finalize_prototypes(), and load().
item_spawns
std::vector<vehicle_item_spawn> vehicle_prototype::item_spawns
Definition at line 506 of file veh_type.h.
Referenced by Item_factory::finalize_item_blacklist(), vehicles::finalize_prototypes(), load(), and vehicle::place_spawn_items().
name
translation vehicle_prototype::name
Definition at line 504 of file veh_type.h.
Referenced by assemble_profession_details(), assemble_scenario_details(), vehicles::finalize_prototypes(), load(), set_description(), and vehicle::vehicle().
parts
std::vector<part_def> vehicle_prototype::parts
Definition at line 505 of file veh_type.h.
Referenced by vehicles::finalize_prototypes(), load(), vehicle::place_spawn_items(), and vehicle_bounds().
src
std::vector<std::pair<vproto_id, mod_id> > vehicle_prototype::src private
Definition at line 515 of file veh_type.h.
was_loaded
bool vehicle_prototype::was_loaded = false private
Definition at line 514 of file veh_type.h.
Referenced by load().
zone_defs
std::vector<zone_def> vehicle_prototype::zone_defs
Definition at line 507 of file veh_type.h.
Referenced by load(), and vehicle::place_zones().
The documentation for this struct was generated from the following files:
src/veh_type.h
src/veh_type.cpp