Cataclysm DDA: overmap_special_migration Struct Reference
overmap_special_migration Struct Reference
#include <omdata.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
Static Public Member Functions
static void load_migrations (const JsonObject &jo, const std::string &src)
static void reset ()
static void check ()
static bool migrated (const overmap_special_id &os_id)
static overmap_special_id migrate (const overmap_special_id &old_id)
Private Attributes
bool was_loaded = false
overmap_special_migration_id id
std::vector< std::pair< overmap_special_migration_id, mod_id > > src
overmap_special_id new_id
friend generic_factory< overmap_special_migration >
Friends
struct mod_tracker
Detailed Description
Definition at line 627 of file omdata.h.
Member Function Documentation
check()
void overmap_special_migration::check () static
Definition at line 7438 of file overmap.cpp.
 {
     for( const overmap_special_migration &mig : migrations.get_all() ) {
         if( !mig.new_id.is_null() && !mig.new_id.is_valid() ) {
             debugmsg( "Invalid new_id \"%s\" for overmap special migration \"%s\"", mig.new_id.c_str(),
                       mig.id.c_str() );
         }
     }
 }
References debugmsg, and anonymous_namespace{overmap.cpp}::migrations.
Referenced by overmap_specials::check_consistency().
load()
void overmap_special_migration::load (const JsonObject & jo, std::string_view src)
Definition at line 7432 of file overmap.cpp.
 {
     mandatory( jo, was_loaded, "id", id );
     optional( jo, was_loaded, "new_id", new_id, overmap_special_id() );
 }
References mandatory, new_id, optional(), overmap_special_id, and was_loaded.
load_migrations()
void overmap_special_migration::load_migrations (const JsonObject & jo, const std::string & src) static
Definition at line 7422 of file overmap.cpp.
 {
     migrations.load( jo, src );
 }
References anonymous_namespace{overmap.cpp}::migrations, and src.
Referenced by DynamicDataLoader::initialize().
migrate()
overmap_special_id overmap_special_migration::migrate (const overmap_special_id & old_id) static
Definition at line 7456 of file overmap.cpp.
 {
     for( const overmap_special_migration &mig : migrations.get_all() ) {
         if( overmap_special_id( mig.id.str() ) == old_id ) {
             return mig.new_id;
         }
     }
     return old_id;
 }
References anonymous_namespace{overmap.cpp}::migrations, and overmap_special_id.
Referenced by overmap_specials::check_consistency(), and overmap::unserialize().
migrated()
bool overmap_special_migration::migrated (const overmap_special_id & os_id) static
Definition at line 7448 of file overmap.cpp.
 {
     std::vector<overmap_special_migration> migs = migrations.get_all();
     return std::find_if( migs.begin(), migs.end(), [&os_id]( overmap_special_migration & m ) {
         return os_id == overmap_special_id( m.id.str() );
     } ) != migs.end();
 }
References anonymous_namespace{overmap.cpp}::migrations.
reset()
void overmap_special_migration::reset () static
Definition at line 7427 of file overmap.cpp.
 {
     migrations.reset();
 }
References anonymous_namespace{overmap.cpp}::migrations.
Referenced by DynamicDataLoader::unload_data().
Friends And Related Function Documentation
mod_tracker
friend struct mod_tracker friend
Definition at line 645 of file omdata.h.
Member Data Documentation
generic_factory< overmap_special_migration >
friend overmap_special_migration::generic_factory< overmap_special_migration > private
Definition at line 644 of file omdata.h.
id
overmap_special_migration_id overmap_special_migration::id private
Definition at line 641 of file omdata.h.
new_id
overmap_special_id overmap_special_migration::new_id private
Definition at line 643 of file omdata.h.
Referenced by load().
src
std::vector<std::pair<overmap_special_migration_id, mod_id> > overmap_special_migration::src private
Definition at line 642 of file omdata.h.
Referenced by load_migrations().
was_loaded
bool overmap_special_migration::was_loaded = false private
Definition at line 640 of file omdata.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/omdata.h
src/overmap.cpp