Cataclysm DDA: pet_food_data Struct Reference
pet_food_data Struct Reference
Pet food data.
#include <mtype.h>
Public Member Functions
void load (const JsonObject &jo)
void deserialize (const JsonObject &data)
Public Attributes
std::set< std::string > food
std::string pet
std::string feed
bool was_loaded = false
Detailed Description
Pet food data.
Definition at line 230 of file mtype.h.
Member Function Documentation
deserialize()
void pet_food_data::deserialize (const JsonObject & data)
Definition at line 1833 of file monstergenerator.cpp.
 {
     load( data );
 }
References load().
load()
void pet_food_data::load (const JsonObject & jo)
Definition at line 1826 of file monstergenerator.cpp.
 {
     mandatory( jo, was_loaded, "food", food );
     optional( jo, was_loaded, "feed", feed );
     optional( jo, was_loaded, "pet", pet );
 }
References feed, food, mandatory, optional(), pet, and was_loaded.
Referenced by deserialize().
Member Data Documentation
feed
std::string pet_food_data::feed
Definition at line 233 of file mtype.h.
Referenced by load().
food
std::set<std::string> pet_food_data::food
Definition at line 231 of file mtype.h.
Referenced by load().
pet
std::string pet_food_data::pet
Definition at line 232 of file mtype.h.
Referenced by load(), and anonymous_namespace{monexamine.cpp}::play_with().
was_loaded
bool pet_food_data::was_loaded = false
Definition at line 235 of file mtype.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/mtype.h
src/monstergenerator.cpp