Cataclysm DDA: islot_wheel Struct Reference
islot_wheel Struct Reference
#include <itype.h>
Public Member Functions
void load (const JsonObject &jo)
void deserialize (const JsonObject &jo)
Public Attributes
int diameter = 0
diameter of wheel (inches)
int width = 0
width of wheel (inches)
bool was_loaded = false
Detailed Description
Definition at line 641 of file itype.h.
Member Function Documentation
deserialize()
void islot_wheel::deserialize (const JsonObject & jo)
Definition at line 2759 of file item_factory.cpp.
 {
     load( jo );
 }
References load().
load()
void islot_wheel::load (const JsonObject & jo)
Definition at line 2753 of file item_factory.cpp.
 {
     optional( jo, was_loaded, "diameter", diameter );
     optional( jo, was_loaded, "width", width );
 }
References diameter, optional(), was_loaded, and width.
Referenced by deserialize().
Member Data Documentation
diameter
int islot_wheel::diameter = 0
diameter of wheel (inches)
Definition at line 644 of file itype.h.
Referenced by load().
was_loaded
bool islot_wheel::was_loaded = false
Definition at line 649 of file itype.h.
Referenced by load().
width
int islot_wheel::width = 0
width of wheel (inches)
Definition at line 647 of file itype.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/itype.h
src/item_factory.cpp