Cataclysm DDA: event_statistic_maximum Struct Reference
event_statistic_maximum Struct Reference
Classes
struct state
Public Member Functions
cata_variant value (stats_tracker &stats) const override
std::unique_ptr< stats_tracker_state > watch (stats_tracker &stats) const override
monotonically monotonicity () const override
std::unique_ptr< impl > clone () const override
event_statistic_field_summary (const string_id< event_statistic > &i, std::unique_ptr< event_source > s, const std::string &f)
Public Member Functions inherited from event_statistic_field_summary< true >
event_statistic_field_summary (const string_id< event_statistic > &i, std::unique_ptr< event_source > s, const std::string &f)
void check (const std::string &name) const override
cata_variant_type type () const override
Public Member Functions inherited from event_statistic::impl
virtual ~impl ()=default
Additional Inherited Members
Public Attributes inherited from event_statistic_field_summary< true >
string_id< event_statistic > id
cata::clone_ptr< event_source > source
std::string field
Detailed Description
Definition at line 895 of file event_statistics.cpp.
Member Function Documentation
clone()
std::unique_ptr<impl> event_statistic_maximum::clone () const inline override virtual
Implements event_statistic::impl.
Definition at line 943 of file event_statistics.cpp.
{
         return std::make_unique<event_statistic_maximum>( *this );
     }
event_statistic_field_summary()
event_statistic_field_summary< IntField >::event_statistic_field_summary inline
Definition at line 801 of file event_statistics.cpp.
       : id( i ), source( std::move( s ) ), field( f )
     {}
monotonicity()
monotonically event_statistic_maximum::monotonicity () const inline override virtual
Implements event_statistic::impl.
Definition at line 939 of file event_statistics.cpp.
{
         return source->monotonicity();
     }
References event_source::monotonicity(), and event_statistic_field_summary< true >::source.
value()
cata_variant event_statistic_maximum::value (stats_tracker & stats) const inline override virtual
Implements event_statistic::impl.
Definition at line 898 of file event_statistics.cpp.
{
         int maximum = source->get( stats ).maximum( field );
         return cata_variant::make<cata_variant_type::int_>( maximum );
     }
References event_source::get(), event_multiset::maximum(), and event_statistic_field_summary< true >::source.
watch()
std::unique_ptr<stats_tracker_state> event_statistic_maximum::watch (stats_tracker & stats) const inline override virtual
Implements event_statistic::impl.
Definition at line 935 of file event_statistics.cpp.
{
         return std::make_unique<state>( this, stats );
     }
The documentation for this struct was generated from the following file:
src/event_statistics.cpp