Cataclysm DDA: scen_blacklist Struct Reference
scen_blacklist Struct Reference
#include <scenario.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view)
void finalize ()
Static Public Member Functions
static void load_scen_blacklist (const JsonObject &jo, std::string_view src)
Public Attributes
std::set< string_id< scenario > > scenarios
bool whitelist = false
Detailed Description
Definition at line 161 of file scenario.h.
Member Function Documentation
finalize()
void scen_blacklist::finalize ()
Definition at line 373 of file scenario.cpp.
 {
     std::vector<string_id<scenario>> all_scens;
     for( const scenario &scen : scenario::get_all() ) {
         all_scens.emplace_back( scen.ident() );
     }
     for( const string_id<scenario> &sc : sc_blacklist.scenarios ) {
         if( std::find( all_scens.begin(), all_scens.end(), sc ) == all_scens.end() ) {
             debugmsg( "Scenario blacklist contains invalid scenario" );
         }
     }
     if( sc_blacklist.whitelist ) {
         std::set<string_id<scenario>> listed_scenarios = sc_blacklist.scenarios;
         sc_blacklist.scenarios.clear();
         for( const scenario &scen : scenario::get_all() ) {
             sc_blacklist.scenarios.insert( scen.ident() );
         }
         for( auto i = sc_blacklist.scenarios.begin(); i != sc_blacklist.scenarios.end(); ) {
             if( listed_scenarios.count( *i ) != 0 ) {
                 i = sc_blacklist.scenarios.erase( i );
             } else {
                 ++i;
             }
         }
     }
 }
References debugmsg, scenario::get_all(), sc_blacklist, scenarios, and whitelist.
Referenced by scenario::finalize().
load()
void scen_blacklist::load (const JsonObject & jo, std::string_view)
Definition at line 350 of file scenario.cpp.
 {
     if( !scenarios.empty() ) {
         DebugLog( D_INFO, DC_ALL ) <<
                                    "Attempted to load scenario blacklist with an existing scenario blacklist, resetting blacklist info";
         reset_scenarios_blacklist();
     }
     const std::string bl_stype = jo.get_string( "subtype" );
     if( bl_stype == "whitelist" ) {
         whitelist = true;
     } else if( bl_stype == "blacklist" ) {
         whitelist = false;
     } else {
         jo.throw_error( "Blacklist subtype is not a valid subtype." );
     }
     for( const std::string line : jo.get_array( "scenarios" ) ) {
         scenarios.emplace( line );
     }
 }
References D_INFO, DC_ALL, DebugLog(), JsonObject::get_array(), JsonObject::get_string(), line, reset_scenarios_blacklist(), scenarios, JsonObject::throw_error(), and whitelist.
Referenced by load_scen_blacklist().
load_scen_blacklist()
void scen_blacklist::load_scen_blacklist (const JsonObject & jo, std::string_view src) static
Definition at line 345 of file scenario.cpp.
 {
     sc_blacklist.load( jo, src );
 }
References load(), and sc_blacklist.
Referenced by DynamicDataLoader::initialize().
Member Data Documentation
scenarios
std::set<string_id<scenario> > scen_blacklist::scenarios
Definition at line 162 of file scenario.h.
Referenced by finalize(), load(), reset_scenarios_blacklist(), and scenario::scen_is_blacklisted().
whitelist
bool scen_blacklist::whitelist = false
Definition at line 163 of file scenario.h.
Referenced by finalize(), load(), and reset_scenarios_blacklist().
The documentation for this struct was generated from the following files:
src/scenario.h
src/scenario.cpp