Cataclysm DDA: half_open_rectangle< Point, > Struct Template Reference
half_open_rectangle< Point, > Struct Template Reference
#include <cuboid_rectangle.h>
Public Types
using base = rectangle< Point >
Public Member Functions
constexpr bool contains (const Point &p) const
constexpr bool overlaps (const rectangle< Point > &r) const
Public Member Functions inherited from rectangle< Point, >
constexpr rectangle ()=default
constexpr rectangle (const Point &P_MIN, const Point &P_MAX)
Public Attributes
Point p_min
Point p_max
Public Attributes inherited from rectangle< Point, >
Point p_min
Point p_max
Detailed Description
template<typename Point, decltype(std::declval< rectangle< Point >>(), int()) = 0>
struct half_open_rectangle< Point, >
Definition at line 27 of file cuboid_rectangle.h.
Member Typedef Documentation
base
template<typename Point , decltype(std::declval< rectangle< Point >>(), int()) = 0> using half_open_rectangle< Point, >::base = rectangle<Point>
Definition at line 28 of file cuboid_rectangle.h.
Member Function Documentation
contains()
template<typename Point , decltype(std::declval< rectangle< Point >>(), int()) = 0> constexpr bool half_open_rectangle< Point, >::contains (const Point & p) const inline constexpr
Definition at line 33 of file cuboid_rectangle.h.
{
         using Traits = point_traits<Point>;
         return Traits::x( p ) >= Traits::x( p_min ) && Traits::x( p ) < Traits::x( p_max ) &&
                Traits::y( p ) >= Traits::y( p_min ) && Traits::y( p ) < Traits::y( p_max );
     }
References half_open_rectangle< Point, >::p_max, and half_open_rectangle< Point, >::p_min.
Referenced by auto_navigation_data::adjust_z(), map::apparent_light_helper(), map::apply_light_ray(), cast_horizontal_zlight_segment(), common_check_bounds(), overmap_ui::draw_ascii(), map::generate_lightmap(), input_context::get_coordinates(), game::load_npcs(), and window_contains_point_relative().
overlaps()
template<typename Point , decltype(std::declval< rectangle< Point >>(), int()) = 0> constexpr bool half_open_rectangle< Point, >::overlaps (const rectangle< Point > & r) const inline constexpr
Definition at line 38 of file cuboid_rectangle.h.
{
         using Traits = point_traits<Point>;
         return !( Traits::x( r.p_min ) >= Traits::x( p_max ) ||
                   Traits::y( r.p_min ) >= Traits::y( p_max ) ||
                   Traits::x( p_min ) >= Traits::x( r.p_max ) ||
                   Traits::y( p_min ) >= Traits::y( r.p_max ) );
     }
References rectangle< Point, >::p_max, half_open_rectangle< Point, >::p_max, rectangle< Point, >::p_min, and half_open_rectangle< Point, >::p_min.
Referenced by map_memory::save().
Member Data Documentation
p_max
template<typename Point , decltype(std::declval< rectangle< Point >>(), int()) = 0> Point rectangle< Point, >::p_max
Definition at line 20 of file cuboid_rectangle.h.
Referenced by clamp(), half_open_rectangle< Point, >::contains(), midpoint(), and half_open_rectangle< Point, >::overlaps().
p_min
template<typename Point , decltype(std::declval< rectangle< Point >>(), int()) = 0> Point rectangle< Point, >::p_min
Definition at line 19 of file cuboid_rectangle.h.
Referenced by clamp(), half_open_rectangle< Point, >::contains(), midpoint(), and half_open_rectangle< Point, >::overlaps().
The documentation for this struct was generated from the following file:
src/cuboid_rectangle.h