Cataclysm DDA: event_statistic_unique_value::state Struct Reference
event_statistic_unique_value::state Struct Reference
Public Member Functions
state (const event_statistic_unique_value *s, stats_tracker &stats)
void init (stats_tracker &stats)
void event_added (const cata::event &e, stats_tracker &stats) override
void events_reset (const event_multiset &, stats_tracker &stats) override
const cata_variant & get_value () const override
Public Member Functions inherited from stats_tracker_state
virtual ~stats_tracker_state ()=0
Public Member Functions inherited from base_watcher
base_watcher ()=default
base_watcher (const base_watcher &)=delete
base_watcher & operator= (const base_watcher &)=delete
Public Attributes
const event_statistic_unique_value * stat
int count = 0
cata_variant value
Additional Inherited Members
Protected Member Functions inherited from base_watcher
virtual ~base_watcher ()
Detailed Description
Definition at line 1024 of file event_statistics.cpp.
Constructor & Destructor Documentation
state()
event_statistic_unique_value::state::state (const event_statistic_unique_value * s, stats_tracker & stats) inline
Definition at line 1025 of file event_statistics.cpp.
                                                                              :
             stat( s ) {
             init( stats );
             stat->source->add_watcher( stats, this );
         }
References event_source::add_watcher(), init(), event_statistic_field_summary< IntField >::source, and stat.
Member Function Documentation
event_added()
void event_statistic_unique_value::state::event_added (const cata::event & e, stats_tracker & stats) inline override virtual
Implements event_multiset_watcher.
Definition at line 1036 of file event_statistics.cpp.
{
             ++count;
             if( count == 1 ) {
                 value = e.get_variant_or_void( stat->field );
             } else if( count == 2 ) {
                 value = cata_variant();
             } else {
                 return;
             }
             stats.stat_value_changed( stat->id, value );
         }
References count, event_statistic_field_summary< IntField >::field, cata::event::get_variant_or_void(), event_statistic_field_summary< IntField >::id, stat, and value.
events_reset()
void event_statistic_unique_value::state::events_reset (const event_multiset & , stats_tracker & stats) inline override virtual
Implements event_multiset_watcher.
Definition at line 1048 of file event_statistics.cpp.
{
             init( stats );
             stats.stat_value_changed( stat->id, value );
         }
References event_statistic_field_summary< IntField >::id, init(), stat, and value.
get_value()
const cata_variant& event_statistic_unique_value::state::get_value () const inline override virtual
Implements stats_tracker_state.
Definition at line 1053 of file event_statistics.cpp.
{
             return value;
         }
References value.
init()
void event_statistic_unique_value::state::init (stats_tracker & stats) inline
Definition at line 1031 of file event_statistics.cpp.
{
             count = stat->source->get( stats ).count();
             value = stat->value( stats );
         }
References count, event_multiset::count(), event_source::get(), event_statistic_field_summary< IntField >::source, stat, event_statistic_unique_value::value(), and value.
Referenced by events_reset(), and state().
Member Data Documentation
count
int event_statistic_unique_value::state::count = 0
Definition at line 1058 of file event_statistics.cpp.
Referenced by event_added(), and init().
stat
const event_statistic_unique_value* event_statistic_unique_value::state::stat
Definition at line 1057 of file event_statistics.cpp.
Referenced by event_added(), events_reset(), init(), and state().
value
cata_variant event_statistic_unique_value::state::value
Definition at line 1059 of file event_statistics.cpp.
Referenced by event_added(), events_reset(), get_value(), and init().
The documentation for this struct was generated from the following file:
src/event_statistics.cpp