Cataclysm DDA: map_data_common_t Struct Reference
map_data_common_t Struct Reference
#include <mapdata.h>
Public Member Functions
virtual ~map_data_common_t ()=default
bool has_curtains () const
std::string name () const
bool can_examine (const tripoint &examp) const
bool has_examine (iexamine_examine_function func) const
bool has_examine (const std::string &action) const
void set_examine (iexamine_functions func)
void examine (Character &, const tripoint &) const
void load_symbol (const JsonObject &jo, const std::string &context)
const std::set< std::string > & get_flags () const
bool has_flag (const std::string &flag) const
bool has_flag (const ter_furn_flag flag) const
void extraprocess_flags (ter_furn_flag flag)
void set_flag (const std::string &flag)
void set_flag (ter_furn_flag flag)
void set_connect_groups (const std::vector< std::string > &connect_groups_vec)
void set_connects_to (const std::vector< std::string > &connect_groups_vec)
void set_rotates_to (const std::vector< std::string > &connect_groups_vec)
void set_groups (std::bitset< NUM_TERCONN > &bits, const std::vector< std::string > &connect_groups_vec)
bool in_connect_groups (const std::bitset< NUM_TERCONN > &test_connect_group) const
int symbol () const
nc_color color () const
const harvest_id & get_harvest () const
const std::set< std::string > & get_harvest_names () const
Returns a set of names of the items that would be dropped.
std::string extended_description () const
bool is_flammable () const
virtual void load (const JsonObject &jo, const std::string &)
virtual void check () const
Public Attributes
map_bash_info bash
map_deconstruct_info deconstruct
cata::value_ptr< map_shoot_info > shoot
ter_str_id curtain_transform
std::array< int, NUM_SEASONS > symbol_
int light_emitted = 0
int movecost = 0
int heat_radiation = 0
int coverage = 0
units::temperature_delta floor_bedding_warmth = 0_C_delta
int comfort = 0
units::volume max_volume = DEFAULT_TILE_VOLUME
translation description
std::array< nc_color, NUM_SEASONS > color_
std::string looks_like
std::array< harvest_id, NUM_SEASONS > harvest_by_season
When will this terrain/furniture get harvested and what will drop? Note: This excludes items that take extra tools to harvest.
bool transparent = false
std::bitset< NUM_TERCONN > connect_groups
std::bitset< NUM_TERCONN > connect_to_groups
std::bitset< NUM_TERCONN > rotate_to_groups
bool was_loaded = false
Protected Attributes
translation name_
iexamine_functions examine_func
cata::clone_ptr< iexamine_actor > examine_actor
Private Attributes
std::set< std::string > flags
enum_bitset< ter_furn_flag > bitflags
Friends
furn_t null_furniture_t ()
ter_t null_terrain_t ()
Detailed Description
Definition at line 452 of file mapdata.h.
Constructor & Destructor Documentation
~map_data_common_t()
virtual map_data_common_t::~map_data_common_t () virtual default
Member Function Documentation
can_examine()
bool map_data_common_t::can_examine (const tripoint & examp) const
Definition at line 568 of file mapdata.cpp.
 {
     return examine_actor || examine_func.can_examine( examp );
 }
References iexamine_functions::can_examine, examine_actor, and examine_func.
Referenced by can_examine_at(), map::examine(), game::examine(), map::get_harvest_names(), and game::place_player().
check()
virtual void map_data_common_t::check () const inline virtual
Reimplemented in furn_t, and ter_t.
Definition at line 591 of file mapdata.h.
 {};
Referenced by ter_t::check(), and furn_t::check().
color()
nc_color map_data_common_t::color () const
Definition at line 636 of file mapdata.cpp.
 {
     return color_[season_of_year( calendar::turn )];
 }
References color_, season_of_year(), and calendar::turn.
Referenced by color(), colorized_ter_name_flags_at(), editmap_hilight::draw(), map::draw_from_above(), editmap::draw_main_ui_overlay(), map::draw_maptile(), and editmap::update_view_with_help().
examine()
void map_data_common_t::examine (Character & you, const tripoint & examp) const
Definition at line 588 of file mapdata.cpp.
 {
     if( !examine_actor ) {
         examine_func.examine( you, examp );
         return;
     }
     examine_actor->call( you, examp );
 }
References iexamine_actor::call(), iexamine_functions::examine, examine_actor, and examine_func.
Referenced by map::examine(), game::examine(), iexamine::ledge(), and game::place_player().
extended_description()
std::string map_data_common_t::extended_description () const
Definition at line 174 of file descriptions.cpp.
 {
     std::stringstream ss;
     ss << "<header>" << string_format( _( "That is a %s." ), name() ) << "</header>" << '\n';
     ss << description << std::endl;
     bool has_any_harvest = std::any_of( harvest_by_season.begin(), harvest_by_season.end(),
     []( const harvest_id & hv ) {
         return !hv.obj().empty();
     } );
     if( has_any_harvest ) {
         ss << "--" << std::endl;
         int player_skill = get_player_character().get_greater_skill_or_knowledge_level( skill_survival );
         ss << _( "You could harvest the following things from it:" ) << std::endl;
         // Group them by identical ids to avoid repeating same blocks of data
         // First, invert the mapping: season->id to id->seasons
         std::multimap<harvest_id, season_type> identical_harvest;
         for( size_t season = SPRING; season <= WINTER; season++ ) {
             const auto &hv = harvest_by_season[ season ];
             if( hv.obj().empty() ) {
                 continue;
             }
             identical_harvest.insert( std::make_pair( hv, static_cast<season_type>( season ) ) );
         }
         // Now print them in order of seasons
         // TODO: Highlight current season
         for( size_t season = SPRING; season <= WINTER; season++ ) {
             const auto range = identical_harvest.equal_range( harvest_by_season[ season ] );
             if( range.first == range.second ) {
                 continue;
             }
             // List the seasons first
             ss << enumerate_as_string( range.first, range.second,
             []( const std::pair<harvest_id, season_type> &pr ) {
                 if( pr.second == season_of_year( calendar::turn ) ) {
                     return "<good>" + calendar::name_season( pr.second ) + "</good>";
                 }
                 return "<dark>" + calendar::name_season( pr.second ) + "</dark>";
             } );
             ss << ":" << std::endl;
             // List the drops
             // They actually describe what player can get from it now, so it isn't spoily
             // TODO: Allow spoily listing of everything
             ss << range.first->first.obj().describe( player_skill ) << std::endl;
             // Remove the range from the multimap so that it isn't listed twice
             identical_harvest.erase( range.first, range.second );
         }
         ss << std::endl;
     }
     return replace_colors( ss.str() );
 }
References _, description, harvest_list::empty(), enumerate_as_string(), Character::get_greater_skill_or_knowledge_level(), get_player_character(), harvest_by_season, name(), calendar::name_season(), string_id< T >::obj(), season, skill_survival, SPRING, string_format(), and WINTER.
Referenced by game::extended_description().
extraprocess_flags()
void map_data_common_t::extraprocess_flags (ter_furn_flag flag)
Definition at line 669 of file mapdata.cpp.
 {
     if( !transparent && flag == ter_furn_flag::TFLAG_TRANSPARENT ) {
         transparent = true;
     }
     for( std::pair<const std::string, connect_group> &item : ter_connects_map ) {
         if( item.second.group_flags.find( flag ) != item.second.group_flags.end() ) {
             set_connect_groups( { item.second.id.str() } );
         }
         if( item.second.connects_to_flags.find( flag ) != item.second.connects_to_flags.end() ) {
             set_connects_to( { item.second.id.str() } );
         }
         if( item.second.rotates_to_flags.find( flag ) != item.second.rotates_to_flags.end() ) {
             set_rotates_to( { item.second.id.str() } );
         }
     }
 }
References set_connect_groups(), set_connects_to(), set_rotates_to(), ter_connects_map, TFLAG_TRANSPARENT, and transparent.
Referenced by set_flag().
get_flags()
const std::set<std::string>& map_data_common_t::get_flags () const inline
Definition at line 530 of file mapdata.h.
{
             return flags;
         }
References flags.
get_harvest()
const harvest_id & map_data_common_t::get_harvest () const
Definition at line 641 of file mapdata.cpp.
 {
     return harvest_by_season[season_of_year( calendar::turn )];
 }
References harvest_by_season, season_of_year(), and calendar::turn.
Referenced by map::get_harvest(), and get_harvest_names().
get_harvest_names()
const std::set< std::string > & map_data_common_t::get_harvest_names () const
Returns a set of names of the items that would be dropped.
Used for NPC whitelist checking.
Definition at line 646 of file mapdata.cpp.
 {
     static const std::set<std::string> null_names = {};
     const harvest_id &hid = get_harvest();
     return hid.is_null() ? null_names : hid->names();
 }
References get_harvest(), string_id< T >::is_null(), and harvest_list::names().
Referenced by map::get_harvest_names().
has_curtains()
bool map_data_common_t::has_curtains () const inline
Definition at line 479 of file mapdata.h.
{
             return !( curtain_transform.is_empty() || curtain_transform.is_null() );
         }
References curtain_transform, string_id< T >::is_empty(), and string_id< T >::is_null().
Referenced by ter_t::check(), and iexamine::curtains().
has_examine() [1/2]
bool map_data_common_t::has_examine (const std::string & action) const
Definition at line 578 of file mapdata.cpp.
 {
     return examine_actor && examine_actor->type == action;
 }
References action, examine_actor, and iexamine_actor::type.
has_examine() [2/2]
bool map_data_common_t::has_examine (iexamine_examine_function func) const
Definition at line 573 of file mapdata.cpp.
 {
     return examine_func.examine == func;
 }
References iexamine_functions::examine, and examine_func.
Referenced by anonymous_namespace{iexamine.cpp}::_choose_elevator_destz(), anonymous_namespace{gates.cpp}::gate_data::check(), ter_t::check(), colorized_ter_name_flags_at(), game::examine(), inventory::form_from_map(), get_hack_type(), game::place_player(), harvest_activity_actor::start(), and map::water_from().
has_flag() [1/2]
bool map_data_common_t::has_flag (const std::string & flag) const inline
Definition at line 534 of file mapdata.h.
{
             return flags.count( flag ) > 0;
         }
References flags.
Referenced by add_fallback_zone(), jmapgen_terrain::apply(), map::bash_ter_furn(), map::build_outside_cache(), MapExtras::burned_ground_parser(), veh_interact::calc_lift_requirements(), ter_t::check(), jmapgen_sealed_item::check(), vehicle::autodrive_controller::check_drivable(), check_furn(), colorized_feature_description_at(), colorized_ter_name_flags_at(), complete_construction(), MapExtras::dead_vegetation_parser(), construct::done_deconstruct(), map::draw_from_above(), editmap::draw_main_ui_overlay(), map::draw_maptile(), map::drop_furniture(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_on_terrain_with_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_with_flag(), farm_action(), field_processor_fd_fungicidal_gas(), field_processor_underwater_dissipation(), inventory::form_from_map(), furn_is_supported(), map::furn_set(), map::furnname(), generic_multi_activity_locations(), map::get_harvest(), map::get_harvest_names(), game::grabbed_furn_move(), game::grabbed_furn_move_time(), map::has_flag_furn(), map::has_flag_ter(), map::has_flag_ter_or_furn(), deploy_furn_actor::info(), Creature::is_adjacent(), is_flammable(), is_swimming_terrain(), jmapgen_sign::jmapgen_sign(), MapExtras::mx_helicopter(), om_cutdown_trees(), map::rad_scorch(), reload_furniture(), map::route(), iexamine::sign(), ter_furn_has_flag(), map::ter_set(), ter_furn_transform::transform(), use_charges_from_furn(), map::valid_move(), map::vehicle_wheel_traction(), game::vertical_move(), and map::water_from().
has_flag() [2/2]
bool map_data_common_t::has_flag (const ter_furn_flag flag) const inline
Definition at line 538 of file mapdata.h.
{
             return bitflags[flag];
         }
References bitflags.
in_connect_groups()
bool map_data_common_t::in_connect_groups (const std::bitset< NUM_TERCONN > & test_connect_group) const inline
Definition at line 566 of file mapdata.h.
{
             return ( connect_groups & test_connect_group ).any();
         }
References connect_groups.
Referenced by map::get_known_connections(), map::get_known_rotates_to(), and map::get_known_rotates_to_f().
is_flammable()
bool map_data_common_t::is_flammable () const inline
Definition at line 584 of file mapdata.h.
{
             return has_flag( ter_furn_flag::TFLAG_FLAMMABLE ) ||
                    has_flag( ter_furn_flag::TFLAG_FLAMMABLE_ASH ) ||
                    has_flag( ter_furn_flag::TFLAG_FLAMMABLE_HARD );
         }
References has_flag(), TFLAG_FLAMMABLE, TFLAG_FLAMMABLE_ASH, and TFLAG_FLAMMABLE_HARD.
load()
void map_data_common_t::load (const JsonObject & jo, const std::string &) virtual
Reimplemented in furn_t, and ter_t.
Definition at line 824 of file mapdata.cpp.
 {
     if( jo.has_string( "examine_action" ) ) {
         examine_actor = nullptr;
         examine_func = iexamine_functions_from_string( jo.get_string( "examine_action" ) );
     } else if( jo.has_object( "examine_action" ) ) {
         JsonObject data = jo.get_object( "examine_action" );
         examine_actor = iexamine_actor_from_jsobj( data );
         examine_actor->load( data );
         examine_func = iexamine_functions_from_string( "invalid" );
     } else if( !was_loaded ) {
         examine_actor = nullptr;
         examine_func = iexamine_functions_from_string( "none" );
     }
     if( jo.has_array( "harvest_by_season" ) ) {
         for( JsonObject harvest_jo : jo.get_array( "harvest_by_season" ) ) {
             auto season_strings = harvest_jo.get_tags( "seasons" );
             std::set<season_type> seasons;
             std::transform( season_strings.begin(), season_strings.end(), std::inserter( seasons,
                             seasons.begin() ), io::string_to_enum<season_type> );
             harvest_id hl;
             harvest_jo.read( "id", hl );
             for( season_type s : seasons ) {
                 harvest_by_season[ s ] = hl;
             }
         }
     }
     mandatory( jo, was_loaded, "description", description );
     optional( jo, was_loaded, "curtain_transform", curtain_transform );
     if( jo.has_object( "shoot" ) ) {
         shoot = cata::make_value<map_shoot_info>();
         shoot->load( jo, "shoot", was_loaded );
     }
 }
References curtain_transform, description, examine_actor, examine_func, JsonObject::get_array(), JsonObject::get_object(), JsonObject::get_string(), harvest_by_season, JsonObject::has_array(), JsonObject::has_object(), JsonObject::has_string(), iexamine_actor_from_jsobj(), iexamine_functions_from_string(), iexamine_actor::load(), mandatory, optional(), shoot, and was_loaded.
Referenced by ter_t::load(), and furn_t::load().
load_symbol()
void map_data_common_t::load_symbol (const JsonObject & jo, const std::string & context)
Definition at line 597 of file mapdata.cpp.
 {
     if( jo.has_member( "copy-from" ) && looks_like.empty() ) {
         looks_like = jo.get_string( "copy-from" );
     }
     jo.read( "looks_like", looks_like );
     load_season_array( jo, "symbol", context, symbol_, [&jo]( const std::string & str ) {
         if( str == "LINE_XOXO" ) {
             return LINE_XOXO;
         } else if( str == "LINE_OXOX" ) {
             return LINE_OXOX;
         } else if( str.length() != 1 ) {
             jo.throw_error_at( "symbol", "Symbol string must be exactly 1 character long." );
         }
         return static_cast<int>( str[0] );
     } );
     const bool has_color = jo.has_member( "color" );
     const bool has_bgcolor = jo.has_member( "bgcolor" );
     if( has_color && has_bgcolor ) {
         jo.throw_error( "Found both color and bgcolor, only one of these is allowed." );
     } else if( has_color ) {
         load_season_array( jo, "color", context, color_, []( const std::string_view str ) {
             // has to use a lambda because of default params
             return color_from_string( str );
         } );
     } else if( has_bgcolor ) {
         load_season_array( jo, "bgcolor", context, color_, bgcolor_from_string );
     } else {
         jo.throw_error( R"(Missing member: one of: "color", "bgcolor" must exist.)" );
     }
 }
References bgcolor_from_string(), color_, color_from_string(), context, JsonObject::get_string(), JsonObject::has_member(), LINE_OXOX, LINE_XOXO, load_season_array(), looks_like, JsonObject::read(), symbol_, and JsonObject::throw_error().
Referenced by ter_t::load(), and furn_t::load().
name()
std::string map_data_common_t::name () const
Definition at line 563 of file mapdata.cpp.
 {
     return name_.translated();
 }
References name_, and translation::translated().
Referenced by iuse::afs_translocator(), colorized_feature_description_at(), colorized_ter_name_flags_at(), construction_menu(), iexamine::deployed_furniture(), construct::done_deconstruct(), map::drop_furniture(), avatar_action::eat_here(), extended_description(), game::forced_door_closing(), map::furn_set(), map::furnname(), game::grabbed_furn_move(), deploy_furn_actor::info(), place_trap_actor::is_allowed(), iexamine::ledge(), photo_def_for_camera_point(), reload_furniture(), map::tername(), map::translate(), map::translate_radius(), avatar::try_to_sleep(), and iexamine::workbench_internal().
set_connect_groups()
void map_data_common_t::set_connect_groups (const std::vector< std::string > & connect_groups_vec)
Definition at line 705 of file mapdata.cpp.
 {
     set_groups( connect_groups, connect_groups_vec );
 }
References connect_groups, and set_groups().
Referenced by extraprocess_flags(), ter_t::load(), and furn_t::load().
set_connects_to()
void map_data_common_t::set_connects_to (const std::vector< std::string > & connect_groups_vec)
Definition at line 711 of file mapdata.cpp.
 {
     set_groups( connect_to_groups, connect_groups_vec );
 }
References connect_to_groups, and set_groups().
Referenced by extraprocess_flags(), ter_t::load(), and furn_t::load().
set_examine()
void map_data_common_t::set_examine (iexamine_functions func)
Definition at line 583 of file mapdata.cpp.
 {
     examine_func = func;
 }
References examine_func.
set_flag() [1/2]
void map_data_common_t::set_flag (const std::string & flag)
Definition at line 688 of file mapdata.cpp.
 {
     flags.insert( flag );
     std::optional<ter_furn_flag> f = io::string_to_enum_optional<ter_furn_flag>( flag );
     if( f.has_value() ) {
         bitflags.set( f.value() );
         extraprocess_flags( f.value() );
     }
 }
References bitflags, extraprocess_flags(), flags, and enum_bitset< E >::set().
Referenced by ter_t::load(), and furn_t::load().
set_flag() [2/2]
void map_data_common_t::set_flag (ter_furn_flag flag)
Definition at line 698 of file mapdata.cpp.
 {
     flags.insert( io::enum_to_string<ter_furn_flag>( flag ) );
     bitflags.set( flag );
     extraprocess_flags( flag );
 }
References bitflags, io::enum_to_string< ter_furn_flag >(), extraprocess_flags(), flags, and enum_bitset< E >::set().
set_groups()
void map_data_common_t::set_groups (std::bitset< NUM_TERCONN > & bits, const std::vector< std::string > & connect_groups_vec)
Definition at line 721 of file mapdata.cpp.
 {
     for( const std::string &group : connect_groups_vec ) {
         if( group.empty() ) {
             debugmsg( "Can't use empty string for terrain groups" );
             continue;
         }
         std::string grp = group;
         bool remove = false;
         if( grp.at( 0 ) == '~' ) {
             grp = grp.substr( 1 );
             remove = true;
         }
         const auto it = ter_connects_map.find( grp );
         if( it != ter_connects_map.end() ) {
             if( remove ) {
                 bits.reset( it->second.index );
             } else {
                 bits.set( it->second.index );
             }
         } else {
             debugmsg( "can't find terrain group %s", group.c_str() );
         }
     }
 }
References om_direction::bits, debugmsg, remove, and ter_connects_map.
Referenced by set_connect_groups(), set_connects_to(), and set_rotates_to().
set_rotates_to()
void map_data_common_t::set_rotates_to (const std::vector< std::string > & connect_groups_vec)
Definition at line 716 of file mapdata.cpp.
 {
     set_groups( rotate_to_groups, connect_groups_vec );
 }
References rotate_to_groups, and set_groups().
Referenced by extraprocess_flags(), ter_t::load(), and furn_t::load().
symbol()
int map_data_common_t::symbol () const
Definition at line 631 of file mapdata.cpp.
 {
     return symbol_[season_of_year( calendar::turn )];
 }
References season_of_year(), symbol_, and calendar::turn.
Referenced by apply< ter_t >(), map::determine_wall_corner(), editmap_hilight::draw(), map::draw_from_above(), editmap::draw_main_ui_overlay(), map::draw_maptile(), symbol(), and editmap::update_view_with_help().
Friends And Related Function Documentation
null_furniture_t
furn_t null_furniture_t () friend
Definition at line 494 of file mapdata.cpp.
 {
     furn_t new_furniture;
     new_furniture.id = furn_str_id::NULL_ID();
     new_furniture.name_ = to_translation( "nothing" );
     new_furniture.symbol_.fill( ' ' );
     new_furniture.color_.fill( c_white );
     new_furniture.light_emitted = 0;
     new_furniture.movecost = 0;
     new_furniture.move_str_req = -1;
     new_furniture.transparent = true;
     new_furniture.set_flag( ter_furn_flag::TFLAG_TRANSPARENT );
     new_furniture.examine_func = iexamine_functions_from_string( "none" );
     new_furniture.max_volume = DEFAULT_TILE_VOLUME;
     return new_furniture;
 }
null_terrain_t
ter_t null_terrain_t () friend
Definition at line 515 of file mapdata.cpp.
 {
     ter_t new_terrain;
     new_terrain.id = ter_str_id::NULL_ID();
     new_terrain.name_ = to_translation( "nothing" );
     new_terrain.symbol_.fill( ' ' );
     new_terrain.color_.fill( c_white );
     new_terrain.light_emitted = 0;
     new_terrain.movecost = 0;
     new_terrain.transparent = true;
     new_terrain.set_flag( ter_furn_flag::TFLAG_TRANSPARENT );
     new_terrain.set_flag( ter_furn_flag::TFLAG_DIGGABLE );
     new_terrain.examine_func = iexamine_functions_from_string( "none" );
     new_terrain.max_volume = DEFAULT_TILE_VOLUME;
     return new_terrain;
 }
Member Data Documentation
bash
map_bash_info map_data_common_t::bash
Definition at line 453 of file mapdata.h.
Referenced by jmapgen_terrain::apply(), map::bash_resistance(), map::bash_strength(), map::bash_ter_furn(), ter_t::check(), furn_t::check(), vehicle::autodrive_controller::check_drivable(), complete_construction(), map::is_bashable(), map::is_bashable_furn(), map::is_bashable_ter(), ter_t::load(), furn_t::load(), talk_function::loot_building(), om_harvest_ter(), iexamine::portable_structure(), and smash().
bitflags
enum_bitset<ter_furn_flag> map_data_common_t::bitflags private
Definition at line 474 of file mapdata.h.
Referenced by has_flag(), and set_flag().
color_
std::array<nc_color, NUM_SEASONS> map_data_common_t::color_
Definition at line 514 of file mapdata.h.
Referenced by color(), and load_symbol().
comfort
int map_data_common_t::comfort = 0
Definition at line 507 of file mapdata.h.
Referenced by Character::base_comfort_value(), ter_t::load(), furn_t::load(), and avatar::try_to_sleep().
connect_groups
std::bitset<NUM_TERCONN> map_data_common_t::connect_groups
Definition at line 549 of file mapdata.h.
Referenced by in_connect_groups(), ter_t::load(), furn_t::load(), and set_connect_groups().
connect_to_groups
std::bitset<NUM_TERCONN> map_data_common_t::connect_to_groups
Definition at line 551 of file mapdata.h.
Referenced by map::determine_wall_corner(), ter_t::load(), furn_t::load(), and set_connects_to().
coverage
int map_data_common_t::coverage = 0
Definition at line 504 of file mapdata.h.
Referenced by map::coverage(), map::ledge_coverage(), ter_t::load(), furn_t::load(), and map::obstacle_coverage().
curtain_transform
ter_str_id map_data_common_t::curtain_transform
Definition at line 477 of file mapdata.h.
Referenced by ter_t::check(), iexamine::curtains(), has_curtains(), and load().
deconstruct
map_deconstruct_info map_data_common_t::deconstruct
Definition at line 454 of file mapdata.h.
Referenced by jmapgen_terrain::apply(), ter_t::check(), furn_t::check(), construct::check_deconstruct(), construct::done_deconstruct(), ter_t::load(), and furn_t::load().
description
translation map_data_common_t::description
Definition at line 511 of file mapdata.h.
Referenced by construction_menu(), extended_description(), load(), photo_def_for_camera_point(), game::print_furniture_info(), and game::print_terrain_info().
examine_actor
cata::clone_ptr<iexamine_actor> map_data_common_t::examine_actor protected
Definition at line 470 of file mapdata.h.
Referenced by can_examine(), examine(), has_examine(), and load().
examine_func
iexamine_functions map_data_common_t::examine_func protected
Definition at line 467 of file mapdata.h.
Referenced by can_examine(), examine(), has_examine(), load(), and set_examine().
flags
std::set<std::string> map_data_common_t::flags private
Definition at line 473 of file mapdata.h.
Referenced by get_flags(), has_flag(), and set_flag().
floor_bedding_warmth
units::temperature_delta map_data_common_t::floor_bedding_warmth = 0_C_delta
Definition at line 506 of file mapdata.h.
Referenced by Character::floor_bedding_warmth(), ter_t::load(), and furn_t::load().
harvest_by_season
std::array<harvest_id, NUM_SEASONS> map_data_common_t::harvest_by_season
Initial value:
= {{
                harvest_id::NULL_ID(), harvest_id::NULL_ID(), harvest_id::NULL_ID(), harvest_id::NULL_ID()
            }
        }
When will this terrain/furniture get harvested and what will drop? Note: This excludes items that take extra tools to harvest.
Definition at line 523 of file mapdata.h.
Referenced by extended_description(), get_harvest(), and load().
heat_radiation
int map_data_common_t::heat_radiation = 0
Definition at line 502 of file mapdata.h.
Referenced by get_best_fire(), get_heat_radiation(), and ter_t::load().
light_emitted
int map_data_common_t::light_emitted = 0
Definition at line 499 of file mapdata.h.
Referenced by ter_t::load(), and furn_t::load().
looks_like
std::string map_data_common_t::looks_like
Definition at line 517 of file mapdata.h.
Referenced by load_symbol().
max_volume
units::volume map_data_common_t::max_volume = DEFAULT_TILE_VOLUME
Definition at line 509 of file mapdata.h.
Referenced by add_fallback_zone(), ter_t::load(), furn_t::load(), and map_stack::max_volume().
movecost
int map_data_common_t::movecost = 0
Definition at line 501 of file mapdata.h.
Referenced by board_up(), map::build_obstacle_cache(), vehicle::autodrive_controller::check_drivable(), map::draw_from_above(), map::furn_set(), ter_t::load(), furn_t::load(), map::move_cost_ter_furn(), fungal_effects::spread_fungus_one_tile(), map::supports_above(), ter_furn_movecost(), map::ter_set(), avatar::try_to_sleep(), editmap::update_view_with_help(), map::valid_move(), and game::walk_move().
name_
translation map_data_common_t::name_ protected
Definition at line 464 of file mapdata.h.
Referenced by ter_t::load(), furn_t::load(), and name().
rotate_to_groups
std::bitset<NUM_TERCONN> map_data_common_t::rotate_to_groups
Definition at line 553 of file mapdata.h.
Referenced by ter_t::load(), furn_t::load(), and set_rotates_to().
shoot
cata::value_ptr<map_shoot_info> map_data_common_t::shoot
Definition at line 455 of file mapdata.h.
Referenced by load().
symbol_
std::array<int, NUM_SEASONS> map_data_common_t::symbol_
Definition at line 491 of file mapdata.h.
Referenced by load_symbol(), and symbol().
transparent
bool map_data_common_t::transparent = false
Definition at line 528 of file mapdata.h.
Referenced by map::build_transparency_cache(), extraprocess_flags(), map::furn_set(), ter_t::load(), furn_t::load(), and map::ter_set().
was_loaded
bool map_data_common_t::was_loaded = false
Definition at line 582 of file mapdata.h.
Referenced by load(), ter_t::load(), and furn_t::load().
The documentation for this struct was generated from the following files:
src/mapdata.h
src/descriptions.cpp
src/mapdata.cpp