Cataclysm DDA: species_type Struct Reference
species_type Struct Reference
#include <monstergenerator.h>
Public Member Functions
std::string get_footsteps () const
species_type ()
void load (const JsonObject &jo, std::string_view src)
Public Attributes
species_id id
std::vector< std::pair< species_id, mod_id > > src
bool was_loaded = false
translation description
translation footsteps
std::set< mon_flag_str_id > flags
enum_bitset< mon_trigger > anger
enum_bitset< mon_trigger > fear
enum_bitset< mon_trigger > placate
field_type_str_id bleeds
Detailed Description
Definition at line 30 of file monstergenerator.h.
Constructor & Destructor Documentation
species_type()
species_type::species_type () inline
Definition at line 45 of file monstergenerator.h.
                   : id( species_id::NULL_ID() ) {
     }
Member Function Documentation
get_footsteps()
std::string species_type::get_footsteps () const inline
Definition at line 41 of file monstergenerator.h.
{
         return footsteps.translated();
     }
References footsteps, and translation::translated().
load()
void species_type::load (const JsonObject & jo, std::string_view src)
Definition at line 1291 of file monstergenerator.cpp.
 {
     optional( jo, was_loaded, "description", description );
     optional( jo, was_loaded, "footsteps", footsteps, to_translation( "footsteps." ) );
     if( jo.has_member( "flags" ) ) {
         flags.clear();
         if( jo.has_string( "flags" ) ) {
             flags.emplace( jo.get_string( "flags" ) );
         } else {
             for( JsonValue jval : jo.get_array( "flags" ) ) {
                 flags.emplace( jval.get_string() );
             }
         }
     } else {
         if( jo.has_member( "extend" ) ) {
             JsonObject exjo = jo.get_object( "extend" );
             exjo.allow_omitted_members();
             if( exjo.has_member( "flags" ) ) {
                 if( exjo.has_string( "flags" ) ) {
                     flags.emplace( exjo.get_string( "flags" ) );
                 } else {
                     for( JsonValue jval : exjo.get_array( "flags" ) ) {
                         flags.emplace( jval.get_string() );
                     }
                 }
             }
         }
         if( jo.has_member( "delete" ) ) {
             JsonObject deljo = jo.get_object( "delete" );
             deljo.allow_omitted_members();
             if( deljo.has_member( "flags" ) ) {
                 if( deljo.has_string( "flags" ) ) {
                     auto iter = flags.find( mon_flag_str_id( deljo.get_string( "flags" ) ) );
                     if( iter != flags.end() ) {
                         flags.erase( iter );
                     }
                 } else {
                     for( JsonValue jval : deljo.get_array( "flags" ) ) {
                         auto iter = flags.find( mon_flag_str_id( jval.get_string() ) );
                         if( iter != flags.end() ) {
                             flags.erase( iter );
                         }
                     }
                 }
             }
         }
     }
     const auto trigger_reader = enum_flags_reader<mon_trigger> { "monster trigger" };
     optional( jo, was_loaded, "anger_triggers", anger, trigger_reader );
     optional( jo, was_loaded, "placate_triggers", placate, trigger_reader );
     optional( jo, was_loaded, "fear_triggers", fear, trigger_reader );
     optional( jo, was_loaded, "bleeds", bleeds, string_id_reader<::field_type> {}, fd_null );
 }
References JsonObject::allow_omitted_members(), anger, bleeds, description, fd_null, fear, flags, footsteps, JsonObject::get_array(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_member(), JsonObject::has_string(), optional(), placate, to_translation(), and was_loaded.
Member Data Documentation
anger
enum_bitset<mon_trigger> species_type::anger
Definition at line 37 of file monstergenerator.h.
Referenced by MonsterGenerator::apply_species_attributes(), and load().
bleeds
field_type_str_id species_type::bleeds
Definition at line 40 of file monstergenerator.h.
Referenced by load().
description
translation species_type::description
Definition at line 34 of file monstergenerator.h.
Referenced by load().
fear
enum_bitset<mon_trigger> species_type::fear
Definition at line 38 of file monstergenerator.h.
Referenced by MonsterGenerator::apply_species_attributes(), and load().
flags
std::set<mon_flag_str_id> species_type::flags
Definition at line 36 of file monstergenerator.h.
Referenced by MonsterGenerator::apply_species_attributes(), and load().
footsteps
translation species_type::footsteps
Definition at line 35 of file monstergenerator.h.
Referenced by get_footsteps(), and load().
id
species_id species_type::id
Definition at line 31 of file monstergenerator.h.
placate
enum_bitset<mon_trigger> species_type::placate
Definition at line 39 of file monstergenerator.h.
Referenced by MonsterGenerator::apply_species_attributes(), and load().
src
std::vector<std::pair<species_id, mod_id> > species_type::src
Definition at line 32 of file monstergenerator.h.
was_loaded
bool species_type::was_loaded = false
Definition at line 33 of file monstergenerator.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/monstergenerator.h
src/monstergenerator.cpp