Cataclysm DDA: mapgen_parameters Struct Reference
mapgen_parameters Struct Reference
#include <mapgen_parameter.h>
Public Types
using iterator = std::unordered_map< std::string, mapgen_parameter >::const_iterator
Public Member Functions
iterator add_unique_parameter (const std::string &prefix, const mapgen_value< std::string > &def, cata_variant_type, mapgen_parameter_scope)
mapgen_parameters params_for_scope (mapgen_parameter_scope scope) const
mapgen_arguments get_args (const mapgendata &, mapgen_parameter_scope scope) const
void check_and_merge (const mapgen_parameters &, const std::string &context, mapgen_parameter_scope up_to_scope=mapgen_parameter_scope::last)
Public Attributes
std::unordered_map< std::string, mapgen_parameter > map
Detailed Description
Definition at line 56 of file mapgen_parameter.h.
Member Typedef Documentation
iterator
using mapgen_parameters::iterator = std::unordered_map<std::string, mapgen_parameter>::const_iterator
Definition at line 58 of file mapgen_parameter.h.
Member Function Documentation
add_unique_parameter()
auto mapgen_parameters::add_unique_parameter (const std::string & prefix, const mapgen_value< std::string > & def, cata_variant_type type, mapgen_parameter_scope scope)
Definition at line 1675 of file mapgen.cpp.
 {
     uint64_t i = 0;
     std::string candidate_name;
     while( true ) {
         candidate_name = string_format( "%s%d", prefix, i );
         if( map.find( candidate_name ) == map.end() ) {
             break;
         }
         ++i;
     }
     return map.emplace( candidate_name, mapgen_parameter( def, type, scope ) ).first;
 }
References string_format().
check_and_merge()
void mapgen_parameters::check_and_merge (const mapgen_parameters & other, const std::string & context, mapgen_parameter_scope up_to_scope = mapgen_parameter_scope::last)
Definition at line 1719 of file mapgen.cpp.
 {
     for( const std::pair<const std::string, mapgen_parameter> &p : other.map ) {
         const mapgen_parameter &other_param = p.second;
         if( other_param.scope() >= up_to_scope ) {
             continue;
         }
         auto insert_result = map.insert( p );
         if( !insert_result.second ) {
             const std::string &name = p.first;
             const mapgen_parameter &this_param = insert_result.first->second;
             this_param.check_consistent_with(
                 // NOLINTNEXTLINE(cata-translate-string-literal)
                 other_param, string_format( "parameter %s in %s", name, context ) );
         }
     }
 }
References mapgen_parameter::check_consistent_with(), context, om_direction::name(), other, mapgen_parameter::scope(), and string_format().
Referenced by mapgen_palette::add(), fixed_overmap_special_data::finalize_mapgen_parameters(), mutable_overmap_special_data::finalize_mapgen_parameters(), mapgen_basic_container::get_mapgen_params(), and mapgen_function_json_base::merge_non_nest_parameters_into().
get_args()
mapgen_arguments mapgen_parameters::get_args (const mapgendata & md, mapgen_parameter_scope scope) const
Definition at line 1704 of file mapgen.cpp.
 {
     std::unordered_map<std::string, cata_variant> result;
     for( const std::pair<const std::string, mapgen_parameter> &p : map ) {
         const std::string &param_name = p.first;
         const mapgen_parameter &param = p.second;
         if( param.scope() == scope ) {
             cata_variant value = md.get_arg_or( param_name, param.get( md ) );
             result.emplace( param_name, value );
         }
     }
     return mapgen_arguments{ result };
 }
References mapgen_parameter::get(), mapgendata::get_arg_or(), and mapgen_parameter::scope().
Referenced by overmap_special::get_args(), and mapgen_function_json_base::get_args().
params_for_scope()
mapgen_parameters mapgen_parameters::params_for_scope (mapgen_parameter_scope scope) const
Definition at line 1692 of file mapgen.cpp.
 {
     mapgen_parameters result;
     for( const std::pair<const std::string, mapgen_parameter> &p : map ) {
         const mapgen_parameter &param = p.second;
         if( param.scope() == scope ) {
             result.map.insert( p );
         }
     }
     return result;
 }
References map, and mapgen_parameter::scope().
Referenced by mapgen_function_json::get_mapgen_params().
Member Data Documentation
map
std::unordered_map<std::string, mapgen_parameter> mapgen_parameters::map
Definition at line 57 of file mapgen_parameter.h.
Referenced by mapgen_value< Id >::param_source::all_possible_results(), calculate_all_blueprint_reqs(), mapgen_palette::check(), mapgen_value< Id >::param_source::check(), mapgen_palette::load_internal(), params_for_scope(), start_location::set_parameters(), and overmap_ui::set_special_args().
The documentation for this struct was generated from the following files:
src/mapgen_parameter.h
src/mapgen.cpp