Cataclysm DDA: talk_topic Struct Reference
talk_topic Struct Reference
#include <dialogue.h>
Public Member Functions
talk_topic (std::string i, itype_id const &it=itype_id::NULL_ID(), std::string r={})
Public Attributes
std::string id
itype_id item_type = itype_id::NULL_ID()
If we're talking about an item, this should be its type.
std::string reason
Reason for denying a request.
Detailed Description
Definition at line 83 of file dialogue.h.
Constructor & Destructor Documentation
talk_topic()
talk_topic::talk_topic (std::string i, itype_id const & it = itype_id::NULL_ID(), std::string r = {}) inline explicit
Definition at line 84 of file dialogue.h.
                                        {} )
         : id( std::move( i ) ), item_type( it ), reason( std::move( r ) ) {
     }
Member Data Documentation
id
std::string talk_topic::id
Definition at line 89 of file dialogue.h.
Referenced by dialogue::add_topic(), dialogue::apply_speaker_effects(), dialogue::dynamic_line(), dialogue::gen_responses(), dialogue::get_best_quit_response(), json_talk_topic::get_directly_reachable_topics(), dialogue::opt(), avatar::talk_to(), and topic_category().
item_type
itype_id talk_topic::item_type = itype_id::NULL_ID()
If we're talking about an item, this should be its type.
Definition at line 91 of file dialogue.h.
Referenced by dialogue::add_response(), dialogue::add_topic(), talk_response::create_option_line(), dialogue::dynamic_line(), json_talk_response::gen_repeat_response(), and dialogue::opt().
reason
std::string talk_topic::reason
Reason for denying a request.
Definition at line 93 of file dialogue.h.
Referenced by dialogue::add_topic().
The documentation for this struct was generated from the following file:
src/dialogue.h