Cataclysm DDA: Character::trait_data Struct Reference
Character::trait_data Struct Reference
#include <character.h>
Public Member Functions
void serialize (JsonOut &json) const
void deserialize (const JsonObject &data)
trait_data ()=default
trait_data (const mutation_variant *chosen)
Public Attributes
bool powered = false
Whether the mutation is activated.
char key = ' '
Key to select the mutation in the UI.
time_duration charge = 0_turns
Time (in turns) until the mutation increase hunger/thirst/sleepiness according to its cost (mutation_branch::cost).
bool show_sprite = true
const mutation_variant * variant = nullptr
A trait variant if it has one, or nullptr.
Detailed Description
Definition at line 3829 of file character.h.
Constructor & Destructor Documentation
trait_data() [1/2]
Character::trait_data::trait_data () default
trait_data() [2/2]
Character::trait_data::trait_data (const mutation_variant * chosen) inline explicit
Definition at line 3850 of file character.h.
 : variant( chosen ) {}
Member Function Documentation
deserialize()
void Character::trait_data::deserialize (const JsonObject & data)
Definition at line 549 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     data.read( "key", key );
     //Remove after 0.G
     if( data.has_int( "charge" ) ) {
         charge = time_duration::from_turns( data.get_int( "charge" ) );
     } else {
         data.read( "charge", charge );
     }
     data.read( "powered", powered );
     data.read( "show_sprite", show_sprite );
     if( data.has_member( "variant-parent" ) ) {
         trait_id parent;
         std::string variant_id;
         data.read( "variant-parent", parent );
         data.read( "variant-id", variant_id );
         // No parent == nowhere to look up this variant. It's effectively lost
         if( !parent.is_valid() ) {
             return;
         }
         variant = parent->variant( variant_id );
     }
 }
References item_pocket::data, time_duration::from_turns(), string_id< T >::is_valid(), and mutation_branch::variant().
serialize()
void Character::trait_data::serialize (JsonOut & json) const
Definition at line 535 of file savegame_json.cpp.
 {
     json.start_object();
     json.member( "key", key );
     json.member( "charge", charge );
     json.member( "powered", powered );
     json.member( "show_sprite", show_sprite );
     if( variant != nullptr ) {
         json.member( "variant-parent", variant->parent );
         json.member( "variant-id", variant->id );
     }
     json.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
Member Data Documentation
charge
time_duration Character::trait_data::charge = 0_turns
Time (in turns) until the mutation increase hunger/thirst/sleepiness according to its cost (mutation_branch::cost).
When those costs have been paid, this is reset to mutation_branch::cooldown.
Definition at line 3839 of file character.h.
Referenced by Character::activate_mutation().
key
char Character::trait_data::key = ' '
Key to select the mutation in the UI.
Definition at line 3833 of file character.h.
Referenced by avatar::power_mutations().
powered
bool Character::trait_data::powered = false
Whether the mutation is activated.
Definition at line 3831 of file character.h.
Referenced by Character::activate_mutation(), and avatar::power_mutations().
show_sprite
bool Character::trait_data::show_sprite = true
Definition at line 3841 of file character.h.
Referenced by avatar::power_mutations().
variant
const mutation_variant* Character::trait_data::variant = nullptr
A trait variant if it has one, or nullptr.
Definition at line 3844 of file character.h.
The documentation for this struct was generated from the following files:
src/character.h
src/savegame_json.cpp