Cataclysm DDA: jmapgen_setmap Struct Reference
jmapgen_setmap Struct Reference
#include <mapgen.h>
Public Member Functions
jmapgen_setmap (jmapgen_int ix, jmapgen_int iy, jmapgen_int iz, jmapgen_int ix2, jmapgen_int iy2, jmapgen_setmap_op iop, jmapgen_int ival, int ione_in=1, jmapgen_int irepeat=jmapgen_int(1, 1), int irotation=0, int ifuel=-1, int istatus=-1, std::string istring_val="")
mapgen_phase phase () const
bool apply (const mapgendata &dat, const tripoint_rel_ms &offset) const
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &offset) const
checks if applying these objects to data would cause cause a collision with vehicles on the same map
Public Attributes
jmapgen_int x
jmapgen_int y
jmapgen_int z
jmapgen_int x2
jmapgen_int y2
jmapgen_setmap_op op
jmapgen_int val
int chance
jmapgen_int repeat
int rotation
int fuel
int status
std::string string_val
Detailed Description
Definition at line 162 of file mapgen.h.
Constructor & Destructor Documentation
jmapgen_setmap()
jmapgen_setmap::jmapgen_setmap (jmapgen_int ix, jmapgen_int iy, jmapgen_int iz, jmapgen_int ix2, jmapgen_int iy2, jmapgen_setmap_op iop, jmapgen_int ival, int ione_in = 1, jmapgen_int irepeat = jmapgen_int(1, 1), int irotation = 0, int ifuel = -1, int istatus = -1, std::string istring_val = "") inline
Definition at line 176 of file mapgen.h.
       :
         x( ix ), y( iy ), z( iz ), x2( ix2 ), y2( iy2 ), op( iop ), val( ival ), chance( ione_in ),
         repeat( irepeat ), rotation( irotation ),
         fuel( ifuel ), status( istatus ), string_val( std::move( istring_val ) ) {}
Member Function Documentation
apply()
bool jmapgen_setmap::apply (const mapgendata & dat, const tripoint_rel_ms & offset) const
Definition at line 4861 of file mapgen.cpp.
 {
     if( chance != 1 && !one_in( chance ) ) {
         return true;
     }
     static const auto get = []( const jmapgen_int & v, int offset ) {
         return v.get() + offset;
     };
     const auto x_get = [this, &offset]() {
         return get( x, offset.x() );
     };
     const auto y_get = [this, &offset]() {
         return get( y, offset.y() );
     };
     const auto z_get = [this, &offset]() {
         return get( z, offset.z() );
     };
     const auto x2_get = [this, &offset]() {
         return get( x2, offset.x() );
     };
     const auto y2_get = [this, &offset]() {
         return get( y2, offset.y() );
     };
     map &m = dat.m;
     const int trepeat = repeat.get();
     const tripoint_bub_ms target_pos( x_get(), y_get(), dat.zlevel() + z_get() );
     const int z_level = dat.zlevel() + z_get();
     for( int i = 0; i < trepeat; i++ ) {
         switch( op ) {
             case JMAPGEN_SETMAP_TER: {
                 // TODO: the ter_id should be stored separately and not be wrapped in an jmapgen_int
                 m.ter_set( target_pos, ter_id( val.get() ),
                            dat.has_flag( jmapgen_flags::avoid_creatures ) );
             }
             break;
             case JMAPGEN_SETMAP_FURN: {
                 // TODO: the furn_id should be stored separately and not be wrapped in an jmapgen_int
                 m.furn_set( target_pos, furn_id( val.get() ),
                             dat.has_flag( jmapgen_flags::avoid_creatures ) );
             }
             break;
             case JMAPGEN_SETMAP_TRAP: {
                 // TODO: the trap_id should be stored separately and not be wrapped in an jmapgen_int
                 mtrap_set( &m, target_pos, trap_id( val.get() ),
                            dat.has_flag( jmapgen_flags::avoid_creatures ) );
             }
             break;
             case JMAPGEN_SETMAP_RADIATION: {
                 m.set_radiation( target_pos.raw(), val.get() );
             }
             break;
             case JMAPGEN_SETMAP_TRAP_REMOVE: {
                 mremove_trap( &m, target_pos, trap_id( val.get() ).id() );
             }
             break;
             case JMAPGEN_SETMAP_CREATURE_REMOVE: {
                 Creature *tmp_critter = get_creature_tracker().creature_at( tripoint_abs_ms( m.getabs(
                                             target_pos ) ), true );
                 if( tmp_critter && !tmp_critter->is_avatar() ) {
                     tmp_critter->die( nullptr );
                 }
             }
             break;
             case JMAPGEN_SETMAP_ITEM_REMOVE: {
                 m.i_clear( target_pos );
             }
             break;
             case JMAPGEN_SETMAP_FIELD_REMOVE: {
                 mremove_fields( &m, target_pos );
             }
             break;
             case JMAPGEN_SETMAP_BASH: {
                 m.bash( target_pos.raw(), 9999 );
             }
             break;
             case JMAPGEN_SETMAP_VARIABLE: {
                 queued_points[string_val] = m.getglobal( target_pos );
             }
             break;
             case JMAPGEN_SETMAP_LINE_TER: {
                 // TODO: the ter_id should be stored separately and not be wrapped in an jmapgen_int
                 m.draw_line_ter( ter_id( val.get() ), point( x_get(), y_get() ), point( x2_get(), y2_get() ),
                                  z_level,
                                  dat.has_flag( jmapgen_flags::avoid_creatures ) );
             }
             break;
             case JMAPGEN_SETMAP_LINE_FURN: {
                 // TODO: the furn_id should be stored separately and not be wrapped in an jmapgen_int
                 m.draw_line_furn( furn_id( val.get() ), point( x_get(), y_get() ), point( x2_get(), y2_get() ),
                                   z_level,
                                   dat.has_flag( jmapgen_flags::avoid_creatures ) );
             }
             break;
             case JMAPGEN_SETMAP_LINE_TRAP: {
                 const std::vector<point> line = line_to( point( x_get(), y_get() ), point( x2_get(), y2_get() ),
                                                 0 );
                 for( const point &i : line ) {
                     // TODO: the trap_id should be stored separately and not be wrapped in an jmapgen_int
                     mtrap_set( &m, tripoint_bub_ms( i.x, i.y, z_level ), trap_id( val.get() ),
                                dat.has_flag( jmapgen_flags::avoid_creatures ) );
                 }
             }
             break;
             case JMAPGEN_SETMAP_LINE_TRAP_REMOVE: {
                 const std::vector<point> line = line_to( point( x_get(), y_get() ), point( x2_get(), y2_get() ),
                                                 0 );
                 for( const point &i : line ) {
                     // TODO: the trap_id should be stored separately and not be wrapped in an jmapgen_int
                     mremove_trap( &m, tripoint_bub_ms( i.x, i.y, z_level ), trap_id( val.get() ).id() );
                 }
             }
             break;
             case JMAPGEN_SETMAP_LINE_CREATURE_REMOVE: {
                 const std::vector<point> line = line_to( point( x_get(), y_get() ), point( x2_get(), y2_get() ),
                                                 0 );
                 for( const point &i : line ) {
                     Creature *tmp_critter = get_creature_tracker().creature_at( tripoint_abs_ms( m.getabs( tripoint( i,
                                             z_level ) ) ), true );
                     if( tmp_critter && !tmp_critter->is_avatar() ) {
                         tmp_critter->die( nullptr );
                     }
                 }
             }
             break;
             case JMAPGEN_SETMAP_LINE_ITEM_REMOVE: {
                 const std::vector<point> line = line_to( point( x_get(), y_get() ), point( x2_get(), y2_get() ),
                                                 0 );
                 for( const point &i : line ) {
                     m.i_clear( tripoint_bub_ms( i.x, i.y, z_level ) );
                 }
             }
             break;
             case JMAPGEN_SETMAP_LINE_FIELD_REMOVE: {
                 const std::vector<point> line = line_to( point( x_get(), y_get() ), point( x2_get(), y2_get() ),
                                                 0 );
                 for( const point &i : line ) {
                     mremove_fields( &m, tripoint_bub_ms( i.x, i.y, z_level ) );
                 }
             }
             break;
             case JMAPGEN_SETMAP_LINE_RADIATION: {
                 const std::vector<point> line = line_to( point( x_get(), y_get() ), point( x2_get(), y2_get() ),
                                                 0 );
                 for( const point &i : line ) {
                     m.set_radiation( tripoint( i, z_level ), static_cast<int>( val.get() ) );
                 }
             }
             break;
             case JMAPGEN_SETMAP_SQUARE_TER: {
                 // TODO: the ter_id should be stored separately and not be wrapped in an jmapgen_int
                 m.draw_square_ter( ter_id( val.get() ), point( x_get(), y_get() ), point( x2_get(), y2_get() ),
                                    z_level,
                                    dat.has_flag( jmapgen_flags::avoid_creatures ) );
             }
             break;
             case JMAPGEN_SETMAP_SQUARE_FURN: {
                 // TODO: the furn_id should be stored separately and not be wrapped in an jmapgen_int
                 m.draw_square_furn( furn_id( val.get() ), point( x_get(), y_get() ), point( x2_get(), y2_get() ),
                                     z_level,
                                     dat.has_flag( jmapgen_flags::avoid_creatures ) );
             }
             break;
             case JMAPGEN_SETMAP_SQUARE_TRAP: {
                 const point c( x_get(), y_get() );
                 const int cx2 = x2_get();
                 const int cy2 = y2_get();
                 for( int tx = c.x; tx <= cx2; tx++ ) {
                     for( int ty = c.y; ty <= cy2; ty++ ) {
                         // TODO: the trap_id should be stored separately and not be wrapped in an jmapgen_int
                         mtrap_set( &m, tripoint_bub_ms( tx, ty, z_level ), trap_id( val.get() ),
                                    dat.has_flag( jmapgen_flags::avoid_creatures ) );
                     }
                 }
             }
             break;
             case JMAPGEN_SETMAP_SQUARE_TRAP_REMOVE: {
                 const point c( x_get(), y_get() );
                 const int cx2 = x2_get();
                 const int cy2 = y2_get();
                 for( int tx = c.x; tx <= cx2; tx++ ) {
                     for( int ty = c.y; ty <= cy2; ty++ ) {
                         // TODO: the trap_id should be stored separately and not be wrapped in an jmapgen_int
                         mremove_trap( &m, tripoint_bub_ms( tx, ty, z_level ), trap_id( val.get() ).id() );
                     }
                 }
             }
             break;
             case JMAPGEN_SETMAP_SQUARE_CREATURE_REMOVE: {
                 const point c( x_get(), y_get() );
                 const int cx2 = x2_get();
                 const int cy2 = y2_get();
                 for( int tx = c.x; tx <= cx2; tx++ ) {
                     for( int ty = c.y; ty <= cy2; ty++ ) {
                         Creature *tmp_critter = get_creature_tracker().creature_at( tripoint_abs_ms( m.getabs( tripoint( tx,
                                                 ty, z_level ) ) ), true );
                         if( tmp_critter && !tmp_critter->is_avatar() ) {
                             tmp_critter->die( nullptr );
                         }
                     }
                 }
             }
             break;
             case JMAPGEN_SETMAP_SQUARE_ITEM_REMOVE: {
                 const point c( x_get(), y_get() );
                 const int cx2 = x2_get();
                 const int cy2 = y2_get();
                 for( int tx = c.x; tx <= cx2; tx++ ) {
                     for( int ty = c.y; ty <= cy2; ty++ ) {
                         m.i_clear( tripoint_bub_ms( tx, ty, z_level ) );
                     }
                 }
             }
             break;
             case JMAPGEN_SETMAP_SQUARE_FIELD_REMOVE: {
                 const point c( x_get(), y_get() );
                 const int cx2 = x2_get();
                 const int cy2 = y2_get();
                 for( int tx = c.x; tx <= cx2; tx++ ) {
                     for( int ty = c.y; ty <= cy2; ty++ ) {
                         mremove_fields( &m, tripoint_bub_ms( tx, ty, z_level ) );
                     }
                 }
             }
             break;
             case JMAPGEN_SETMAP_SQUARE_RADIATION: {
                 const point c2( x_get(), y_get() );
                 const int cx2 = x2_get();
                 const int cy2 = y2_get();
                 for( int tx = c2.x; tx <= cx2; tx++ ) {
                     for( int ty = c2.y; ty <= cy2; ty++ ) {
                         m.set_radiation( tripoint( tx, ty, z_level ), static_cast<int>( val.get() ) );
                     }
                 }
             }
             break;
             default:
                 //Suppress warnings
                 break;
         }
     }
     return true;
 }
References avoid_creatures, map::bash(), c, creature_tracker::creature_at(), Creature::die(), map::draw_line_furn(), map::draw_line_ter(), map::draw_square_furn(), map::draw_square_ter(), furn_id, map::furn_set(), jmapgen_int::get(), mapgen_palette::get(), get_creature_tracker(), map::getabs(), map::getglobal(), mapgendata::has_flag(), map::i_clear(), int_id< T >::id(), Creature::is_avatar(), JMAPGEN_SETMAP_BASH, JMAPGEN_SETMAP_CREATURE_REMOVE, JMAPGEN_SETMAP_FIELD_REMOVE, JMAPGEN_SETMAP_FURN, JMAPGEN_SETMAP_ITEM_REMOVE, JMAPGEN_SETMAP_LINE_CREATURE_REMOVE, JMAPGEN_SETMAP_LINE_FIELD_REMOVE, JMAPGEN_SETMAP_LINE_FURN, JMAPGEN_SETMAP_LINE_ITEM_REMOVE, JMAPGEN_SETMAP_LINE_RADIATION, JMAPGEN_SETMAP_LINE_TER, JMAPGEN_SETMAP_LINE_TRAP, JMAPGEN_SETMAP_LINE_TRAP_REMOVE, JMAPGEN_SETMAP_RADIATION, JMAPGEN_SETMAP_SQUARE_CREATURE_REMOVE, JMAPGEN_SETMAP_SQUARE_FIELD_REMOVE, JMAPGEN_SETMAP_SQUARE_FURN, JMAPGEN_SETMAP_SQUARE_ITEM_REMOVE, JMAPGEN_SETMAP_SQUARE_RADIATION, JMAPGEN_SETMAP_SQUARE_TER, JMAPGEN_SETMAP_SQUARE_TRAP, JMAPGEN_SETMAP_SQUARE_TRAP_REMOVE, JMAPGEN_SETMAP_TER, JMAPGEN_SETMAP_TRAP, JMAPGEN_SETMAP_TRAP_REMOVE, JMAPGEN_SETMAP_VARIABLE, line, line_to(), mapgendata::m, mremove_fields(), mremove_trap(), mtrap_set(), one_in(), point, queued_points, coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), map::set_radiation(), ter_id, map::ter_set(), trap_id, tripoint, coords::coord_point_mut< Point, Subpoint, InBounds >::x(), point::x, coords::coord_point_mut< Point, Subpoint, InBounds >::y(), point::y, coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and mapgendata::zlevel().
Referenced by apply_mapgen_in_phases().
has_vehicle_collision()
bool jmapgen_setmap::has_vehicle_collision (const mapgendata & dat, const tripoint_rel_ms & offset) const
checks if applying these objects to data would cause cause a collision with vehicles on the same map
Definition at line 5108 of file mapgen.cpp.
 {
     static const auto get = []( const jmapgen_int & v, int v_offset ) {
         return v.get() + v_offset;
     };
     const auto x_get = [this, &offset]() {
         return get( x, offset.x() );
     };
     const auto y_get = [this, &offset]() {
         return get( y, offset.y() );
     };
     const auto z_get = [this, &offset]() {
         return get( z, offset.z() );
     };
     const auto x2_get = [this, &offset]() {
         return get( x2, offset.x() );
     };
     const auto y2_get = [this, &offset]() {
         return get( y2, offset.y() );
     };
     const tripoint_rel_ms start = tripoint_rel_ms( x_get(), y_get(), dat.zlevel() + z_get() );
     tripoint_rel_ms end = start;
     switch( op ) {
         case JMAPGEN_SETMAP_TER:
         case JMAPGEN_SETMAP_FURN:
         case JMAPGEN_SETMAP_TRAP:
             break;
         /* lines and squares are the same thing for this purpose */
         case JMAPGEN_SETMAP_LINE_TER:
         case JMAPGEN_SETMAP_LINE_FURN:
         case JMAPGEN_SETMAP_LINE_TRAP:
         case JMAPGEN_SETMAP_LINE_TRAP_REMOVE:
         case JMAPGEN_SETMAP_LINE_ITEM_REMOVE:
         case JMAPGEN_SETMAP_SQUARE_TER:
         case JMAPGEN_SETMAP_SQUARE_FURN:
         case JMAPGEN_SETMAP_SQUARE_TRAP:
         case JMAPGEN_SETMAP_SQUARE_TRAP_REMOVE:
         case JMAPGEN_SETMAP_SQUARE_ITEM_REMOVE:
             end.x() = x2_get();
             end.y() = y2_get();
             break;
         /* if it's not a terrain, furniture, or trap, it can't collide */
         default:
             return false;
     }
     for( const tripoint &p : dat.m.points_in_rectangle( start.raw(), end.raw() ) ) {
         if( dat.m.veh_at( p ) ) {
             return true;
         }
     }
     return false;
 }
References keycode::end, jmapgen_int::get(), mapgen_palette::get(), JMAPGEN_SETMAP_FURN, JMAPGEN_SETMAP_LINE_FURN, JMAPGEN_SETMAP_LINE_ITEM_REMOVE, JMAPGEN_SETMAP_LINE_TER, JMAPGEN_SETMAP_LINE_TRAP, JMAPGEN_SETMAP_LINE_TRAP_REMOVE, JMAPGEN_SETMAP_SQUARE_FURN, JMAPGEN_SETMAP_SQUARE_ITEM_REMOVE, JMAPGEN_SETMAP_SQUARE_TER, JMAPGEN_SETMAP_SQUARE_TRAP, JMAPGEN_SETMAP_SQUARE_TRAP_REMOVE, JMAPGEN_SETMAP_TER, JMAPGEN_SETMAP_TRAP, mapgendata::m, map::points_in_rectangle(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), map::veh_at(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), coords::coord_point_mut< Point, Subpoint, InBounds >::y(), coords::coord_point_mut< Point, Subpoint, InBounds >::z(), and mapgendata::zlevel().
Referenced by apply_mapgen_in_phases().
phase()
mapgen_phase jmapgen_setmap::phase () const
Definition at line 4815 of file mapgen.cpp.
 {
     switch( op ) {
         case JMAPGEN_SETMAP_TER:
         case JMAPGEN_SETMAP_LINE_TER:
         case JMAPGEN_SETMAP_SQUARE_TER:
             return mapgen_phase::terrain;
         case JMAPGEN_SETMAP_FURN:
         case JMAPGEN_SETMAP_LINE_FURN:
         case JMAPGEN_SETMAP_SQUARE_FURN:
             return mapgen_phase::furniture;
         case JMAPGEN_SETMAP_TRAP:
         case JMAPGEN_SETMAP_TRAP_REMOVE:
         case JMAPGEN_SETMAP_CREATURE_REMOVE:
         case JMAPGEN_SETMAP_ITEM_REMOVE:
         case JMAPGEN_SETMAP_FIELD_REMOVE:
         case JMAPGEN_SETMAP_LINE_TRAP:
         case JMAPGEN_SETMAP_LINE_TRAP_REMOVE:
         case JMAPGEN_SETMAP_LINE_CREATURE_REMOVE:
         case JMAPGEN_SETMAP_LINE_ITEM_REMOVE:
         case JMAPGEN_SETMAP_LINE_FIELD_REMOVE:
         case JMAPGEN_SETMAP_SQUARE_TRAP:
         case JMAPGEN_SETMAP_SQUARE_TRAP_REMOVE:
         case JMAPGEN_SETMAP_SQUARE_CREATURE_REMOVE:
         case JMAPGEN_SETMAP_SQUARE_ITEM_REMOVE:
         case JMAPGEN_SETMAP_SQUARE_FIELD_REMOVE:
             return mapgen_phase::default_;
         case JMAPGEN_SETMAP_RADIATION:
         case JMAPGEN_SETMAP_BASH:
         case JMAPGEN_SETMAP_VARIABLE:
         case JMAPGEN_SETMAP_LINE_RADIATION:
         case JMAPGEN_SETMAP_SQUARE_RADIATION:
             return mapgen_phase::transform;
         case JMAPGEN_SETMAP_OPTYPE_POINT:
         case JMAPGEN_SETMAP_OPTYPE_LINE:
         case JMAPGEN_SETMAP_OPTYPE_SQUARE:
             break;
     }
     debugmsg( "Invalid jmapgen_setmap::op %d", static_cast<int>( op ) );
     return mapgen_phase::default_;
 }
References debugmsg, default_, furniture, JMAPGEN_SETMAP_BASH, JMAPGEN_SETMAP_CREATURE_REMOVE, JMAPGEN_SETMAP_FIELD_REMOVE, JMAPGEN_SETMAP_FURN, JMAPGEN_SETMAP_ITEM_REMOVE, JMAPGEN_SETMAP_LINE_CREATURE_REMOVE, JMAPGEN_SETMAP_LINE_FIELD_REMOVE, JMAPGEN_SETMAP_LINE_FURN, JMAPGEN_SETMAP_LINE_ITEM_REMOVE, JMAPGEN_SETMAP_LINE_RADIATION, JMAPGEN_SETMAP_LINE_TER, JMAPGEN_SETMAP_LINE_TRAP, JMAPGEN_SETMAP_LINE_TRAP_REMOVE, JMAPGEN_SETMAP_OPTYPE_LINE, JMAPGEN_SETMAP_OPTYPE_POINT, JMAPGEN_SETMAP_OPTYPE_SQUARE, JMAPGEN_SETMAP_RADIATION, JMAPGEN_SETMAP_SQUARE_CREATURE_REMOVE, JMAPGEN_SETMAP_SQUARE_FIELD_REMOVE, JMAPGEN_SETMAP_SQUARE_FURN, JMAPGEN_SETMAP_SQUARE_ITEM_REMOVE, JMAPGEN_SETMAP_SQUARE_RADIATION, JMAPGEN_SETMAP_SQUARE_TER, JMAPGEN_SETMAP_SQUARE_TRAP, JMAPGEN_SETMAP_SQUARE_TRAP_REMOVE, JMAPGEN_SETMAP_TER, JMAPGEN_SETMAP_TRAP, JMAPGEN_SETMAP_TRAP_REMOVE, JMAPGEN_SETMAP_VARIABLE, terrain, and transform.
Referenced by apply_mapgen_in_phases(), and phase_comparator::get_phase().
Member Data Documentation
chance
int jmapgen_setmap::chance
Definition at line 170 of file mapgen.h.
fuel
int jmapgen_setmap::fuel
Definition at line 173 of file mapgen.h.
op
jmapgen_setmap_op jmapgen_setmap::op
Definition at line 168 of file mapgen.h.
repeat
jmapgen_int jmapgen_setmap::repeat
Definition at line 171 of file mapgen.h.
rotation
int jmapgen_setmap::rotation
Definition at line 172 of file mapgen.h.
status
int jmapgen_setmap::status
Definition at line 174 of file mapgen.h.
string_val
std::string jmapgen_setmap::string_val
Definition at line 175 of file mapgen.h.
val
jmapgen_int jmapgen_setmap::val
Definition at line 169 of file mapgen.h.
x
jmapgen_int jmapgen_setmap::x
Definition at line 163 of file mapgen.h.
x2
jmapgen_int jmapgen_setmap::x2
Definition at line 166 of file mapgen.h.
y
jmapgen_int jmapgen_setmap::y
Definition at line 164 of file mapgen.h.
y2
jmapgen_int jmapgen_setmap::y2
Definition at line 167 of file mapgen.h.
z
jmapgen_int jmapgen_setmap::z
Definition at line 165 of file mapgen.h.
The documentation for this struct was generated from the following files:
src/mapgen.h
src/mapgen.cpp