Cataclysm DDA: new_field Struct Reference
new_field Struct Reference
Public Member Functions
void deserialize (const JsonObject &jo)
void check (const std::string &context_name, const cata::event::fields_type &input_fields) const
std::vector< cata::event::data_type > transform (const cata::event::data_type &data, const std::string &new_field_name) const
cata_variant_type type (const cata::event::fields_type &) const
Public Attributes
event_field_transformation transformation
std::string input_field
Detailed Description
Definition at line 269 of file event_statistics.cpp.
Member Function Documentation
check()
void new_field::check (const std::string & context_name, const cata::event::fields_type & input_fields) const inline
Definition at line 290 of file event_statistics.cpp.
{
         auto it = input_fields.find( input_field );
         if( it == input_fields.end() ) {
             debugmsg( "event_transformation %s specifies transformation on field %s but no such "
                       "field exists on the input", context_name, input_field );
             return;
         }
         if( transformation.argument_types.size() != 1 ) {
             debugmsg( "event_field_transformations of arity not 1 not supported" );
             return;
         }
         if( it->second != transformation.argument_types[0] ) {
             debugmsg( "event_transformation %s specifies transformation on field %s of incorrect "
                       "type.  Transformation expects %s; field was %s.", context_name, input_field,
                       io::enum_to_string( transformation.argument_types[0] ),
                       io::enum_to_string( it->second ) );
         }
     }
References event_field_transformation::argument_types, debugmsg, io::enum_to_string(), input_field, and transformation.
deserialize()
void new_field::deserialize (const JsonObject & jo) inline
Definition at line 273 of file event_statistics.cpp.
{
         if( jo.size() != 1 ) {
             jo.throw_error( "new field specifications must have exactly one entry" );
         }
         for( const JsonMember m : jo ) {
             const std::string &transformation_name = m.name();
             auto it = event_field_transformations.find( transformation_name );
             if( it == event_field_transformations.end() ) {
                 m.throw_error(
                     string_format( "unknown event field transformation '%s'", transformation_name )
                 );
             }
             transformation = it->second;
             input_field = m.get_string();
         }
     }
References event_field_transformations, input_field, JsonObject::size(), string_format(), JsonObject::throw_error(), and transformation.
transform()
std::vector<cata::event::data_type> new_field::transform (const cata::event::data_type & data, const std::string & new_field_name) const inline
Definition at line 310 of file event_statistics.cpp.
{
         std::vector<cata::event::data_type> result;
         auto it = data.find( input_field );
         if( it == data.end() ) {
             // Field missing, probably due to stale data.  Reporting an error
             // would spam, so we rely on the fact that it should already have
             // been reported at startup time.
             return result;
         }
         if( !it->second.get_string().empty() && !it->second.is_valid() ) {
             // Field value is non-empty and invalid; event_transformation_functions are not
             // required to handle invalid values, so just skip it
             return result;
         }
         for( const cata_variant &v : transformation.function( it->second ) ) {
             result.push_back( data );
             result.back().emplace( new_field_name, v );
         }
         return result;
     }
References event_field_transformation::function, input_field, and transformation.
type()
cata_variant_type new_field::type (const cata::event::fields_type &) const inline
Definition at line 332 of file event_statistics.cpp.
{
         return transformation.return_type;
     }
References event_field_transformation::return_type, and transformation.
Member Data Documentation
input_field
std::string new_field::input_field
Definition at line 271 of file event_statistics.cpp.
Referenced by check(), deserialize(), and transform().
transformation
event_field_transformation new_field::transformation
Definition at line 270 of file event_statistics.cpp.
Referenced by check(), deserialize(), transform(), and type().
The documentation for this struct was generated from the following file:
src/event_statistics.cpp