Cataclysm DDA: talk_function::teach_domain Struct Reference
talk_function::teach_domain Struct Reference
#include <npctalk.h>
Public Attributes
skill_id skill = skill_id()
matype_id style = matype_id()
spell_id spell = spell_id()
proficiency_id prof = proficiency_id()
Detailed Description
Definition at line 16 of file npctalk.h.
Member Data Documentation
prof
proficiency_id talk_function::teach_domain::prof = proficiency_id()
Definition at line 20 of file npctalk.h.
Referenced by game::chat(), talk_function::start_training(), talk_function::start_training_gen(), talk_function::start_training_npc(), and talk_function::start_training_seminar().
skill
skill_id talk_function::teach_domain::skill = skill_id()
Definition at line 17 of file npctalk.h.
Referenced by game::chat(), talk_function::start_training(), talk_function::start_training_gen(), talk_function::start_training_npc(), and talk_function::start_training_seminar().
spell
spell_id talk_function::teach_domain::spell = spell_id()
Definition at line 19 of file npctalk.h.
Referenced by game::chat(), talk_function::start_training(), talk_function::start_training_gen(), talk_function::start_training_npc(), and talk_function::start_training_seminar().
style
matype_id talk_function::teach_domain::style = matype_id()
Definition at line 18 of file npctalk.h.
Referenced by game::chat(), talk_function::start_training(), talk_function::start_training_gen(), talk_function::start_training_npc(), and talk_function::start_training_seminar().
The documentation for this struct was generated from the following file:
src/npctalk.h