Cataclysm DDA: tiny_bitset::bit_setter< set > Struct Template Reference
tiny_bitset::bit_setter< set > Struct Template Reference
Public Member Functions
void operator() (block_t &bits)
void operator() (block_t &partial, block_t mask)
Detailed Description
template<bool set>
struct tiny_bitset::bit_setter< set >
Definition at line 222 of file cata_bitset.h.
Member Function Documentation
operator()() [1/2]
template<bool set> void tiny_bitset::bit_setter< set >::operator() (block_t & bits) inline
Definition at line 223 of file cata_bitset.h.
{
                 if( set ) {
                     bits = ~0;
                 } else {
                     bits = 0;
                 }
             }
References tiny_bitset::bits(), and tiny_bitset::set().
operator()() [2/2]
template<bool set> void tiny_bitset::bit_setter< set >::operator() (block_t & partial, block_t mask) inline
Definition at line 231 of file cata_bitset.h.
{
                 if( set ) {
                     partial |= ~mask;
                 } else {
                     partial &= mask;
                 }
             }
References tiny_bitset::set().
The documentation for this struct was generated from the following file:
src/cata_bitset.h