Cataclysm DDA: vehicle_part::carried_part_data Struct Reference
vehicle_part::carried_part_data Struct Reference
#include <vehicle.h>
Public Member Functions
void deserialize (const JsonObject &data)
void serialize (JsonOut &json) const
Public Attributes
tripoint mount
units::angle face_dir
std::string veh_name
Detailed Description
Definition at line 293 of file vehicle.h.
Member Function Documentation
deserialize()
void vehicle_part::carried_part_data::deserialize (const JsonObject & data)
Definition at line 3304 of file savegame_json.cpp.
 {
     data.read( "veh_name", veh_name );
     face_dir = units::from_degrees( data.get_int( "face_dir" ) );
     data.read( "mount_x", mount.x );
     data.read( "mount_y", mount.y );
     data.read( "mount_z", mount.z );
 }
References item_pocket::data, and units::from_degrees().
serialize()
void vehicle_part::carried_part_data::serialize (JsonOut & json) const
Definition at line 3313 of file savegame_json.cpp.
 {
     json.start_object();
     json.member( "veh_name", veh_name );
     json.member( "face_dir", std::lround( to_degrees( face_dir ) ) );
     json.member( "mount_x", mount.x );
     json.member( "mount_y", mount.y );
     json.member( "mount_z", mount.z );
     json.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), JsonOut::start_object(), and units::to_degrees().
Member Data Documentation
face_dir
units::angle vehicle_part::carried_part_data::face_dir
Definition at line 295 of file vehicle.h.
mount
tripoint vehicle_part::carried_part_data::mount
Definition at line 294 of file vehicle.h.
veh_name
std::string vehicle_part::carried_part_data::veh_name
Definition at line 296 of file vehicle.h.
The documentation for this struct was generated from the following files:
src/vehicle.h
src/savegame_json.cpp