Cataclysm DDA: event_statistic_minimum Struct Reference
event_statistic_minimum Struct Reference
Classes
struct state
Public Member Functions
cata_variant value (stats_tracker &stats) const override
std::unique_ptr< stats_tracker_state > watch (stats_tracker &stats) const override
monotonically monotonicity () const override
std::unique_ptr< impl > clone () const override
event_statistic_field_summary (const string_id< event_statistic > &i, std::unique_ptr< event_source > s, const std::string &f)
Public Member Functions inherited from event_statistic_field_summary< true >
event_statistic_field_summary (const string_id< event_statistic > &i, std::unique_ptr< event_source > s, const std::string &f)
void check (const std::string &name) const override
cata_variant_type type () const override
Public Member Functions inherited from event_statistic::impl
virtual ~impl ()=default
Additional Inherited Members
Public Attributes inherited from event_statistic_field_summary< true >
string_id< event_statistic > id
cata::clone_ptr< event_source > source
std::string field
Detailed Description
Definition at line 948 of file event_statistics.cpp.
Member Function Documentation
clone()
std::unique_ptr<impl> event_statistic_minimum::clone () const inline override virtual
Implements event_statistic::impl.
Definition at line 1002 of file event_statistics.cpp.
{
         return std::make_unique<event_statistic_minimum>( *this );
     }
event_statistic_field_summary()
event_statistic_field_summary< IntField >::event_statistic_field_summary inline
Definition at line 801 of file event_statistics.cpp.
       : id( i ), source( std::move( s ) ), field( f )
     {}
monotonicity()
monotonically event_statistic_minimum::monotonicity () const inline override virtual
Implements event_statistic::impl.
Definition at line 992 of file event_statistics.cpp.
{
         // If the source is increasing (adding more events)
         if( is_increasing( source->monotonicity() ) ) {
             // Then the minimum value will be decreasing
             return monotonically::decreasing;
         } else {
             return monotonically::unknown;
         }
     }
References decreasing, is_increasing(), event_source::monotonicity(), event_statistic_field_summary< true >::source, and unknown.
value()
cata_variant event_statistic_minimum::value (stats_tracker & stats) const inline override virtual
Implements event_statistic::impl.
Definition at line 951 of file event_statistics.cpp.
{
         int minimum = source->get( stats ).minimum( field );
         return cata_variant::make<cata_variant_type::int_>( minimum );
     }
References event_source::get(), event_multiset::minimum(), and event_statistic_field_summary< true >::source.
watch()
std::unique_ptr<stats_tracker_state> event_statistic_minimum::watch (stats_tracker & stats) const inline override virtual
Implements event_statistic::impl.
Definition at line 988 of file event_statistics.cpp.
{
         return std::make_unique<state>( this, stats );
     }
The documentation for this struct was generated from the following file:
src/event_statistics.cpp