Cataclysm DDA: shopkeeper_item_group Struct Reference
shopkeeper_item_group Struct Reference
#include <npc_class.h>
Public Member Functions
shopkeeper_item_group ()=default
shopkeeper_item_group (const std::string &id, int trust, bool strict, bool rigid=false)
bool can_sell (npc const &guy) const
bool can_restock (npc const &guy) const
std::string get_refusal () const
void deserialize (const JsonObject &jo)
Public Attributes
item_group_id id = item_group_id("EMPTY_GROUP")
int trust = 0
bool strict = false
translation refusal
std::function< bool(dialogue &)> condition
bool rigid = false
Detailed Description
Definition at line 50 of file npc_class.h.
Constructor & Destructor Documentation
shopkeeper_item_group() [1/2]
shopkeeper_item_group::shopkeeper_item_group () default
shopkeeper_item_group() [2/2]
shopkeeper_item_group::shopkeeper_item_group (const std::string & id, int trust, bool strict, bool rigid = false) inline
Definition at line 61 of file npc_class.h.
                                                                                              :
         id( item_group_id( id ) ), trust( trust ), strict( strict ), rigid( rigid ) {}
Member Function Documentation
can_restock()
bool shopkeeper_item_group::can_restock (npc const & guy) const
Definition at line 245 of file npc_class.cpp.
 {
     return !strict || can_sell( guy );
 }
References can_sell(), and strict.
can_sell()
bool shopkeeper_item_group::can_sell (npc const & guy) const
Definition at line 236 of file npc_class.cpp.
 {
     dialogue temp( get_talker_for( get_avatar() ), get_talker_for( guy ) );
     faction *const fac = guy.get_faction();
     return ( fac == nullptr || trust <= guy.get_faction()->trusts_u ) &&
            ( !condition || condition( temp ) );
 }
References condition, get_avatar(), npc::get_faction(), get_talker_for(), temp, trust, and faction_template::trusts_u.
Referenced by can_restock().
deserialize()
void shopkeeper_item_group::deserialize (const JsonObject & jo)
Definition at line 259 of file npc_class.cpp.
 {
     mandatory( jo, false, "group", id );
     optional( jo, false, "trust", trust, 0 );
     optional( jo, false, "strict", strict, false );
     optional( jo, false, "rigid", rigid, false );
     optional( jo, false, "refusal", refusal );
     if( jo.has_member( "condition" ) ) {
         read_condition( jo, "condition", condition, false );
     }
 }
References condition, JsonObject::has_member(), mandatory, optional(), read_condition(), refusal, rigid, strict, and trust.
get_refusal()
std::string shopkeeper_item_group::get_refusal () const
Definition at line 250 of file npc_class.cpp.
 {
     if( refusal.empty() ) {
         return _( "<npcname> does not trust you enough" );
     }
     return refusal.translated();
 }
References _, translation::empty(), refusal, and translation::translated().
Member Data Documentation
condition
std::function<bool(dialogue &)> shopkeeper_item_group::condition
Definition at line 55 of file npc_class.h.
Referenced by can_sell(), and deserialize().
id
item_group_id shopkeeper_item_group::id = item_group_id("EMPTY_GROUP")
Definition at line 51 of file npc_class.h.
Referenced by npc_class::check_consistency().
refusal
translation shopkeeper_item_group::refusal
Definition at line 54 of file npc_class.h.
Referenced by deserialize(), and get_refusal().
rigid
bool shopkeeper_item_group::rigid = false
Definition at line 58 of file npc_class.h.
Referenced by deserialize().
strict
bool shopkeeper_item_group::strict = false
Definition at line 53 of file npc_class.h.
Referenced by can_restock(), and deserialize().
trust
int shopkeeper_item_group::trust = 0
Definition at line 52 of file npc_class.h.
Referenced by can_sell(), and deserialize().
The documentation for this struct was generated from the following files:
src/npc_class.h
src/npc_class.cpp