Cataclysm DDA: dialogue Struct Reference
dialogue Struct Reference
#include <dialogue.h>
Public Member Functions
talk_topic opt (dialogue_window &d_win, const talk_topic &topic)
dialogue ()=default
dialogue (const dialogue &d)
dialogue (dialogue &&)=default
dialogue & operator= (const dialogue &)
dialogue & operator= (dialogue &&)=default
dialogue (std::unique_ptr< talker > alpha_in, std::unique_ptr< talker > beta_in)
dialogue (std::unique_ptr< talker > alpha_in, std::unique_ptr< talker > beta_in, const std::unordered_map< std::string, std::function< bool(dialogue &)>> &cond)
dialogue (std::unique_ptr< talker > alpha_in, std::unique_ptr< talker > beta_in, const std::unordered_map< std::string, std::function< bool(dialogue &)>> &cond, const std::unordered_map< std::string, std::string > &ctx)
talker * actor (bool is_beta) const
std::string dynamic_line (const talk_topic &topic)
void apply_speaker_effects (const talk_topic &the_topic)
void gen_responses (const talk_topic &topic)
void add_topic (const std::string &topic)
void add_topic (const talk_topic &topic)
void set_value (const std::string &key, const std::string &value)
void remove_value (const std::string &key)
std::string get_value (const std::string &key) const
std::optional< std::string > maybe_get_value (const std::string &key) const
void set_conditional (const std::string &key, const std::function< bool(dialogue &)> &value)
bool evaluate_conditional (const std::string &key, dialogue &d)
const std::unordered_map< std::string, std::string > & get_context () const
const std::unordered_map< std::string, std::function< bool(dialogue &)> > & get_conditionals () const
void amend_callstack (const std::string &value)
std::string get_callstack () const
Public Attributes
bool done = false
If true, we are done talking and the dialog ends.
std::vector< talk_topic > topic_stack
std::vector< mission * > missions_assigned
Missions that have been assigned by this npc to the player they currently speak to.
itype_id cur_item
std::string reason
bool by_radio = false
This dialogue is happening over a radio.
std::vector< talk_response > responses
Possible responses from the player character, filled in gen_responses.
bool has_beta
bool has_alpha
Private Member Functions
talk_response & add_response (const std::string &text, const std::string &r, bool first=false)
Add a simple response that switches the topic to the new one.
talk_response & add_response_done (const std::string &text)
Add a response with the result TALK_DONE.
talk_response & add_response_none (const std::string &text)
Add a response with the result TALK_NONE.
talk_response & add_response (const std::string &text, const std::string &r, const dialogue_fun_ptr &effect_success, bool first=false)
Add a simple response that switches the topic to the new one and executes the given action.
talk_response & add_response (const std::string &text, const std::string &r, const std::function< void(npc &)> &effect_success, dialogue_consequence consequence, bool first=false)
Add a simple response that switches the topic to the new one and executes the given action.
talk_response & add_response (const std::string &text, const std::string &r, mission *miss, bool first=false)
Add a simple response that switches the topic to the new one and sets the currently talked about mission to the given one.
talk_response & add_response (const std::string &text, const std::string &r, const skill_id &skill, bool first=false)
Add a simple response that switches the topic to the new one and sets the currently talked about skill to the given one.
talk_response & add_response (const std::string &text, const std::string &r, const proficiency_id &proficiency, bool first=false)
Add a simple response that switches the topic to the new one and sets the currently talked about proficiency to the given one.
talk_response & add_response (const std::string &text, const std::string &r, const spell_id &sp, bool first=false)
Add a simple response that switches the topic to the new one and sets the currently talked about magic spell to the given one.
talk_response & add_response (const std::string &text, const std::string &r, const martialart &style, bool first=false)
Add a simple response that switches the topic to the new one and sets the currently talked about martial art style to the given one.
talk_response & add_response (const std::string &text, const std::string &r, const itype_id &item_type, bool first=false)
Add a simple response that switches the topic to the new one and sets the currently talked about item type to the given one.
int get_best_quit_response ()
Finds the best response to use when the player is trying to quit.
Private Attributes
std::unique_ptr< talker > alpha
The talker that speaks (almost certainly representing the avatar, ie get_avatar())
std::unique_ptr< talker > beta
The talker responded to alpha, usually a talker_npc.
lazy< std::unordered_map< std::string, std::string > > context
std::string callstack
lazy< std::unordered_map< std::string, std::function< bool(dialogue &)> > > conditionals
Detailed Description
Definition at line 184 of file dialogue.h.
Constructor & Destructor Documentation
dialogue() [1/6]
dialogue::dialogue () default
dialogue() [2/6]
dialogue::dialogue (const dialogue & d)
Definition at line 2379 of file npctalk.cpp.
                                       : has_beta( d.has_beta ), has_alpha( d.has_alpha )
 {
     if( has_alpha ) {
         alpha = d.actor( false )->clone();
     }
     if( has_beta ) {
         beta = d.actor( true )->clone();
     }
     if( !has_alpha && !has_beta ) {
         debugmsg( "Constructed a dialogue with no actors!  %s", get_callstack() );
     }
     if( d.context.has_value() ) {
         context = *d.context;
     }
     if( d.conditionals.has_value() ) {
         conditionals = *d.conditionals;
     }
     callstack = d.callstack;
 }
References actor(), alpha, beta, callstack, talker::clone(), conditionals, context, debugmsg, get_callstack(), has_alpha, has_beta, and lazy< T, typename >::has_value().
dialogue() [3/6]
dialogue::dialogue (dialogue &&) default
dialogue() [4/6]
dialogue::dialogue (std::unique_ptr< talker > alpha_in, std::unique_ptr< talker > beta_in)
Definition at line 2399 of file npctalk.cpp.
                                                     : alpha( std::move( alpha_in ) ), beta( std::move( beta_in ) )
 {
     has_alpha = alpha != nullptr;
     has_beta = beta != nullptr;
     if( !has_alpha && !has_beta ) {
         debugmsg( "Constructed a dialogue with no actors!  %s", get_callstack() );
     }
 }
References alpha, beta, debugmsg, get_callstack(), has_alpha, and has_beta.
dialogue() [5/6]
dialogue::dialogue (std::unique_ptr< talker > alpha_in, std::unique_ptr< talker > beta_in, const std::unordered_map< std::string, std::function< bool(dialogue &)>> & cond)
Definition at line 2409 of file npctalk.cpp.
                                                                                                : alpha( std::move(
                                     alpha_in ) ), beta( std::move( beta_in ) ), conditionals( cond )
 {
     has_alpha = alpha != nullptr;
     has_beta = beta != nullptr;
     if( !has_alpha && !has_beta ) {
         debugmsg( "Constructed a dialogue with no actors!  %s", get_callstack() );
     }
 }
References alpha, beta, debugmsg, get_callstack(), has_alpha, and has_beta.
dialogue() [6/6]
dialogue::dialogue (std::unique_ptr< talker > alpha_in, std::unique_ptr< talker > beta_in, const std::unordered_map< std::string, std::function< bool(dialogue &)>> & cond, const std::unordered_map< std::string, std::string > & ctx)
Definition at line 2421 of file npctalk.cpp.
                                                                         : alpha( std::move( alpha_in ) ),
     beta( std::move( beta_in ) ), context( ctx ), conditionals( cond )
 {
     has_alpha = alpha != nullptr;
     has_beta = beta != nullptr;
     if( !has_alpha && !has_beta ) {
         debugmsg( "Constructed a dialogue with no actors!  %s", get_callstack() );
     }
 }
References alpha, beta, context, debugmsg, get_callstack(), has_alpha, and has_beta.
Member Function Documentation
actor()
talker * dialogue::actor (bool is_beta) const
Definition at line 2357 of file npctalk.cpp.
 {
     if( !has_beta && !has_alpha ) {
         debugmsg( "Attempted to use a dialogue with no actors!  %s", get_callstack() );
     }
     if( is_beta && !has_beta ) {
         debugmsg( "Tried to use an invalid beta talker.  %s", get_callstack() );
         // Try to avoid a crash by using the alpha if it exists
         if( has_alpha ) {
             return alpha.get();
         }
     }
     if( !is_beta && !has_alpha ) {
         debugmsg( "Tried to use an invalid alpha talker.  %s", get_callstack() );
         // Try to avoid a crash by using the beta if it exists
         if( has_beta ) {
             return beta.get();
         }
     }
     return ( is_beta ? beta : alpha ).get();
 }
References alpha, beta, debugmsg, get_callstack(), has_alpha, has_beta, and anonymous_namespace{math_parser_diag.cpp}::is_beta().
Referenced by add_topic(), talk_effect_t::apply(), talk_trial::calc_chance(), talk_response::create_option_line(), dialogue(), dynamic_line(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_debt(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_faction_trust(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_morale(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_wet(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_activity(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_attack(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_change_faction_rep(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_clear_npc_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_consume_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_die(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_forget_recipe(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_equipment(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_guard_pos(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_learn_recipe(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_location_variable(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_faction_trust(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_morale(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mod_healthy(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_aim_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_cbm_recharge_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_cbm_reserve_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_change_class(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_change_faction(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_engagement_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_first_topic(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_gets_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_goal(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_offer_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_prevent_death(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_item_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_inv_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_flag(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_npc_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_talker(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_take_control(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_toggle_npc_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_turn_cost(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_sell_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_spend_cash(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_unset_flag(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_wants_to_talk(), gen_responses(), json_talk_topic::gen_responses(), talk_effect_t::get_consequence(), conditional_t::get_set_dbl(), get_tripoint_from_var(), json_dynamic_line_effect::json_dynamic_line_effect(), maybe_read_var_value(), opt(), parse_mod(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::process_eoc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::receive_item(), talk_trial::roll(), run_item_eocs(), translate_gendered_line(), talk_effect_t::update_missions(), and write_var_value().
add_response() [1/9]
talk_response & dialogue::add_response (const std::string & text, const std::string & r, bool first = false) private
Add a simple response that switches the topic to the new one.
If first == true, force this topic to the front of the responses.
Definition at line 1592 of file npctalk.cpp.
 {
     talk_response result = talk_response();
     result.truetext = no_translation( text );
     result.truefalse_condition = []( const dialogue & ) {
         return true;
     };
     result.success.next_topic = talk_topic( r );
     if( first ) {
         responses.insert( responses.begin(), result );
         return responses.front();
     } else {
         responses.push_back( result );
         return responses.back();
     }
 }
References talk_effect_t::next_topic, no_translation(), responses, talk_response::success, talk_response::truefalse_condition, and talk_response::truetext.
Referenced by add_response(), add_response_done(), add_response_none(), and gen_responses().
add_response() [2/9]
talk_response & dialogue::add_response (const std::string & text, const std::string & r, const dialogue_fun_ptr & effect_success, bool first = false) private
Add a simple response that switches the topic to the new one and executes the given action.
The response always succeeds. Consequence is based on function used.
Definition at line 1620 of file npctalk.cpp.
 {
     talk_response &result = add_response( text, r, first );
     result.success.set_effect( effect_success );
     return result;
 }
References add_response(), talk_effect_t::set_effect(), and talk_response::success.
add_response() [3/9]
talk_response & dialogue::add_response (const std::string & text, const std::string & r, const itype_id & item_type, bool first = false) private
Add a simple response that switches the topic to the new one and sets the currently talked about item type to the given one.
Definition at line 1680 of file npctalk.cpp.
 {
     if( item_type.is_null() ) {
         debugmsg( "explicitly specified null item" );
     }
     talk_response &result = add_response( text, r, first );
     result.success.next_topic.item_type = item_type;
     return result;
 }
References add_response(), debugmsg, string_id< T >::is_null(), talk_topic::item_type, talk_effect_t::next_topic, and talk_response::success.
add_response() [4/9]
talk_response & dialogue::add_response (const std::string & text, const std::string & r, const martialart & style, bool first = false) private
Add a simple response that switches the topic to the new one and sets the currently talked about martial art style to the given one.
Definition at line 1672 of file npctalk.cpp.
 {
     talk_response &result = add_response( text, r, first );
     result.style = style.id;
     return result;
 }
References add_response(), martialart::id, and talk_response::style.
add_response() [5/9]
talk_response & dialogue::add_response (const std::string & text, const std::string & r, const proficiency_id & proficiency, bool first = false) private
Add a simple response that switches the topic to the new one and sets the currently talked about proficiency to the given one.
Definition at line 1656 of file npctalk.cpp.
 {
     talk_response &result = add_response( text, r, first );
     result.proficiency = proficiency;
     return result;
 }
References add_response(), and talk_response::proficiency.
add_response() [6/9]
talk_response & dialogue::add_response (const std::string & text, const std::string & r, const skill_id & skill, bool first = false) private
Add a simple response that switches the topic to the new one and sets the currently talked about skill to the given one.
Definition at line 1648 of file npctalk.cpp.
 {
     talk_response &result = add_response( text, r, first );
     result.skill = skill;
     return result;
 }
References add_response(), and talk_response::skill.
add_response() [7/9]
talk_response & dialogue::add_response (const std::string & text, const std::string & r, const spell_id & sp, bool first = false) private
Add a simple response that switches the topic to the new one and sets the currently talked about magic spell to the given one.
Definition at line 1664 of file npctalk.cpp.
 {
     talk_response &result = add_response( text, r, first );
     result.dialogue_spell = sp;
     return result;
 }
References add_response(), and talk_response::dialogue_spell.
add_response() [8/9]
talk_response & dialogue::add_response (const std::string & text, const std::string & r, const std::function< void(npc &)> & effect_success, dialogue_consequence consequence, bool first = false) private
Add a simple response that switches the topic to the new one and executes the given action.
The response always succeeds. Consequence must be explicitly specified.
Definition at line 1628 of file npctalk.cpp.
 {
     talk_response &result = add_response( text, r, first );
     result.success.set_effect_consequence( effect_success, consequence );
     return result;
 }
References add_response(), talk_effect_t::set_effect_consequence(), and talk_response::success.
add_response() [9/9]
talk_response & dialogue::add_response (const std::string & text, const std::string & r, mission * miss, bool first = false) private
Add a simple response that switches the topic to the new one and sets the currently talked about mission to the given one.
The mission pointer must be valid.
Definition at line 1637 of file npctalk.cpp.
 {
     if( miss == nullptr ) {
         debugmsg( "tried to select null mission" );
     }
     talk_response &result = add_response( text, r, first );
     result.mission_selected = miss;
     return result;
 }
References add_response(), debugmsg, and talk_response::mission_selected.
add_response_done()
talk_response & dialogue::add_response_done (const std::string & text) private
Add a response with the result TALK_DONE.
Definition at line 1610 of file npctalk.cpp.
 {
     return add_response( text, "TALK_DONE" );
 }
References add_response().
Referenced by gen_responses().
add_response_none()
talk_response & dialogue::add_response_none (const std::string & text) private
Add a response with the result TALK_NONE.
Definition at line 1615 of file npctalk.cpp.
 {
     return add_response( text, "TALK_NONE" );
 }
References add_response().
Referenced by gen_responses().
add_topic() [1/2]
void dialogue::add_topic (const std::string & topic)
Definition at line 2277 of file npctalk.cpp.
 {
     if( actor( true )->get_npc() ) {
         topic_stack.emplace_back( actor( true )->get_npc()->get_specified_talk_topic( topic_id ) );
     } else {
         topic_stack.emplace_back( topic_id );
     }
 }
References actor(), and topic_stack.
add_topic() [2/2]
void dialogue::add_topic (const talk_topic & topic)
Definition at line 2286 of file npctalk.cpp.
 {
     if( actor( true )->get_npc() ) {
         std::string const &newid = actor( true )->get_npc()->get_specified_talk_topic( topic.id );
         topic_stack.emplace_back( newid, topic.item_type, topic.reason );
     } else {
         topic_stack.push_back( topic );
     }
 }
References actor(), talker::get_npc(), npc::get_specified_talk_topic(), talk_topic::id, talk_topic::item_type, talk_topic::reason, and topic_stack.
amend_callstack()
void dialogue::amend_callstack (const std::string & value)
Definition at line 2340 of file npctalk.cpp.
 {
     if( !callstack.empty() ) {
         callstack += " \\ " + value;
     } else {
         callstack = value;
     }
 }
References callstack.
Referenced by effect_on_condition::activate(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_until().
apply_speaker_effects()
void dialogue::apply_speaker_effects (const talk_topic & the_topic)
Definition at line 1578 of file npctalk.cpp.
 {
     const std::string &topic = the_topic.id;
     const auto iter = json_talk_topics.find( topic );
     if( iter == json_talk_topics.end() ) {
         return;
     }
     for( json_dynamic_line_effect &npc_effect : iter->second.get_speaker_effects() ) {
         if( npc_effect.test_condition( *this ) ) {
             npc_effect.apply( *this );
         }
     }
 }
References talk_topic::id, and json_talk_topics.
Referenced by opt().
dynamic_line()
std::string dialogue::dynamic_line (const talk_topic & topic)
Definition at line 1420 of file npctalk.cpp.
 {
     if( !the_topic.item_type.is_null() ) {
         cur_item = the_topic.item_type;
     }
     // For compatibility
     const std::string &topic = the_topic.id;
     const auto iter = json_talk_topics.find( topic );
     if( iter != json_talk_topics.end() ) {
         std::string line = iter->second.get_dynamic_line( *this );
         if( !line.empty() ) {
             return line;
         }
     }
     if( topic == "TALK_NPC_NOFACE" ) {
         return string_format( _( "&%s stays silent." ), actor( true )->disp_name() );
     }
     if( topic == "TALK_NOFACE" ) {
         return _( "&You can't talk without your face." );
     } else if( topic == "TALK_DEAF" ) {
         return _( "&You are deaf and can't talk." );
     } else if( topic == "TALK_DEAF_ANGRY" ) {
         return string_format(
                    _( "&You are deaf and can't talk.  When you don't respond, %s becomes angry!" ),
                    actor( true )->disp_name() );
     } else if( topic == "TALK_MUTE" ) {
         return _( "&You are mute and can't talk." );
     } else if( topic == "TALK_MUTE_ANGRY" ) {
         return string_format(
                    _( "&You are mute and can't talk.  When you don't respond, %s becomes angry!" ),
                    actor( true )->disp_name() );
     } else if( topic == "TALK_CHURL" ) {
         return string_format(
                    _( "&Thou art but a lowley churl and ye know not this newe tongue.  %s seems unable to understand what you're saying." ),
                    actor( true )->disp_name() );
     } else if( topic == "TALK_CHURL_ANGRY" ) {
         return string_format(
                    _( "&Thou art but a lowley churl and ye know not this newe tongue.  Unable to understand your dialect, %s becomes angry!" ),
                    actor( true )->disp_name() );
     } else if( topic == "TALK_CHURL_TRADE" ) {
         return string_format(
                    _( "&Thou art but a lowley churl wyth litel understonding of this newe langage, yet %s can understand you and seems willing to trade!" ),
                    actor( true )->disp_name() );
     }
     avatar &player_character = get_avatar();
     if( topic == "TALK_SEDATED" ) {
         return string_format( _( "%1$s is sedated and can't be moved or woken up until the "
                                  "medication or sedation wears off.\nYou estimate it will wear "
                                  "off in %2$s." ),
                               actor( true )->disp_name(),
                               to_string_approx( player_character.estimate_effect_dur( skill_firstaid,
                                                 effect_narcosis, 90_minutes, 60_minutes, 6,
                                                 *actor( true )->get_npc() ) ) );
     }
     // Those topics are handled by the mission system, see there.
     static const std::unordered_set<std::string> mission_topics = { {
             "TALK_MISSION_DESCRIBE", "TALK_MISSION_DESCRIBE_URGENT",
             "TALK_MISSION_OFFER", "TALK_MISSION_ACCEPTED",
             "TALK_MISSION_REJECTED", "TALK_MISSION_ADVICE", "TALK_MISSION_INQUIRE",
             "TALK_MISSION_SUCCESS", "TALK_MISSION_SUCCESS_LIE", "TALK_MISSION_FAILURE"
         }
     };
     if( mission_topics.count( topic ) > 0 ) {
         mission *miss = actor( true )->selected_mission();
         if( miss == nullptr ) {
             return "mission_selected == nullptr; BUG!  (npctalk.cpp:dynamic_line)";
         }
         const mission_type &type = miss->get_type();
         // TODO: make it a member of the mission class, maybe at mission instance specific data
         const std::string &ret = miss->dialogue_for_topic( topic );
         if( ret.empty() ) {
             debugmsg( "Bug in npctalk.cpp:dynamic_line.  Wrong mission_id(%s) or topic(%s)",
                       type.id.c_str(), topic.c_str() );
             return "";
         }
         if( topic == "TALK_MISSION_SUCCESS" && miss->has_follow_up() ) {
             switch( rng( 1, 3 ) ) {
                 case 1:
                     return ret + _( "  And I have more I'd like you to do." );
                 case 2:
                     return ret + _( "  I could use a hand with something else if you are interested." );
                 case 3:
                     return ret + _( "  If you are interested, I have another job for you." );
             }
         }
         return ret;
     }
     if( topic == "TALK_NONE" || topic == "TALK_DONE" ) {
         return actor( true )->get_npc()->chat_snippets().snip_bye.translated();
     } else if( topic == "TALK_TRAIN" ) {
         if( !player_character.backlog.empty() && player_character.backlog.front().id() == ACT_TRAIN ) {
             return _( "Shall we resume?" );
         } else if( actor( true )->skills_offered_to( *actor( false ) ).empty() &&
                    actor( true )->styles_offered_to( *actor( false ) ).empty() &&
                    actor( true )->spells_offered_to( *actor( false ) ).empty() &&
                    actor( true )->proficiencies_offered_to( *actor( false ) ).empty() ) {
             return _( "Sorry, but it doesn't seem I have anything to teach you." );
         } else {
             return _( "Here's what I can teach you" );
         }
     } else if( topic == "TALK_TRAIN_NPC" ) {
         if( actor( false )->skills_offered_to( *actor( true ) ).empty() &&
             actor( false )->styles_offered_to( *actor( true ) ).empty() &&
             actor( false )->spells_offered_to( *actor( true ) ).empty() &&
             actor( false )->proficiencies_offered_to( *actor( true ) ).empty() ) {
             return _( "Sorry, there's nothing I can learn from you." );
         } else {
             return _( "Sure, I'm all ears." );
         }
     } else if( topic == "TALK_TRAIN_SEMINAR" ) {
         return _( "What do you want me to teach?" );
     } else if( topic == "TALK_HOW_MUCH_FURTHER" ) {
         return actor( true )->distance_to_goal();
     } else if( topic == "TALK_DESCRIBE_MISSION" ) {
         return actor( true )->get_job_description();
     } else if( topic == "TALK_SHOUT" ) {
         actor( false )->shout();
         if( actor( false )->is_deaf() ) {
             return _( "&You yell, but can't hear yourself." );
         } else {
             if( actor( false )->is_mute() ) {
                 return _( "&You yell, but can't form words." );
             } else {
                 return _( "&You yell." );
             }
         }
     } else if( topic == "TALK_SIZE_UP" ) {
         return actor( true )->evaluation_by( *actor( false ) );
     } else if( topic == "TALK_ASSESS_PERSON" ) {
         return actor( true )->view_personality_traits();
     } else if( topic == "TALK_LOOK_AT" ) {
         if( actor( false )->can_see() ) {
             return "&" + actor( true )->short_description();
         } else {
             return string_format( _( "&You're blind and can't look at %s." ), actor( true )->disp_name() );
         }
     } else if( topic == "TALK_OPINION" ) {
         return "&" + actor( true )->opinion_text();
     } else if( topic == "TALK_MIND_CONTROL" ) {
         if( actor( true )->enslave_mind() ) {
             return _( "YES, MASTER!" );
         }
     }
     debugmsg( "I don't know what to say for %s. (BUG (npctalk.cpp:dynamic_line))", topic );
     return "";
 }
References _, ACT_TRAIN, actor(), Character::backlog, npc::chat_snippets(), cur_item, debugmsg, mission::dialogue_for_topic(), talker::distance_to_goal(), effect_narcosis, Character::estimate_effect_dur(), talker::evaluation_by(), get_avatar(), talker::get_job_description(), talker::get_npc(), mission::get_type(), mission::has_follow_up(), talk_topic::id, string_id< T >::is_null(), talk_topic::item_type, json_talk_topics, line, talker::opinion_text(), cata::hash64_detail::ret, rng(), talker::selected_mission(), talker::short_description(), talker::shout(), skill_firstaid, dialogue_chatbin_snippets::snip_bye, string_format(), to_string_approx(), translation::translated(), type, and talker::view_personality_traits().
Referenced by opt().
evaluate_conditional()
bool dialogue::evaluate_conditional (const std::string & key, dialogue & d)
Definition at line 2323 of file npctalk.cpp.
 {
     auto it = conditionals->find( key );
     return ( it == conditionals->end() ) ? false : it->second( d );
 }
References conditionals.
gen_responses()
void dialogue::gen_responses (const talk_topic & topic)
Definition at line 1692 of file npctalk.cpp.
 {
     responses.clear();
     const auto iter = json_talk_topics.find( the_topic.id );
     if( iter != json_talk_topics.end() ) {
         json_talk_topic &jtt = iter->second;
         if( jtt.gen_responses( *this ) ) {
             return;
         }
     }
     Character &player_character = get_player_character();
     if( the_topic.id == "TALK_MISSION_LIST" ) {
         if( actor( true )->available_missions().size() == 1 ) {
             add_response( _( "Tell me about it." ), "TALK_MISSION_OFFER",
                           actor( true )->available_missions().front(), true );
         } else {
             for( mission *&mission : actor( true )->available_missions() ) {
                 add_response( mission->get_type().tname(), "TALK_MISSION_OFFER", mission, true );
             }
         }
     } else if( the_topic.id == "TALK_MISSION_LIST_ASSIGNED" ) {
         if( missions_assigned.size() == 1 ) {
             add_response( _( "I have news." ), "TALK_MISSION_INQUIRE", missions_assigned.front() );
         } else {
             for( mission *&miss_it : missions_assigned ) {
                 add_response( miss_it->get_type().tname(), "TALK_MISSION_INQUIRE", miss_it );
             }
         }
     } else if( the_topic.id == "TALK_TRAIN_NPC" ) {
         const std::vector<matype_id> &styles = actor( false )->styles_offered_to( *actor( true ) );
         const std::vector<skill_id> &skills = actor( false )->skills_offered_to( *actor( true ) );
         const std::vector<spell_id> &spells = actor( false )->spells_offered_to( *actor( true ) );
         const std::vector<proficiency_id> &profs =
             actor( false )->proficiencies_offered_to( *actor( true ) );
         if( skills.empty() && styles.empty() && spells.empty() && profs.empty() ) {
             add_response_none( _( "Oh, okay." ) );
             return;
         }
         for( const spell_id &sp : spells ) {
             const std::string &text =
                 string_format( "%s: %s", _( "Spell" ), actor( false )->spell_training_text( *actor( true ), sp ) );
             if( !text.empty() ) {
                 add_response( text, "TALK_TRAIN_NPC_START", sp );
             }
         }
         for( const matype_id &ma : styles ) {
             const std::string &text =
                 string_format( "%s: %s", _( "Style" ), actor( false )->style_training_text( *actor( true ), ma ) );
             if( !text.empty() ) {
                 add_response( text, "TALK_TRAIN_NPC_START", ma.obj() );
             }
         }
         for( const skill_id &sk : skills ) {
             const std::string &text =
                 string_format( "%s: %s", _( "Skill" ), actor( false )->skill_training_text( *actor( true ), sk ) );
             if( !text.empty() && !sk->obsolete() ) {
                 add_response( text, "TALK_TRAIN_NPC_START", sk );
             }
         }
         for( const proficiency_id &pr : profs ) {
             const std::string &text =
                 string_format( "%s: %s", _( "Proficiency" ),
                                actor( false )->proficiency_training_text( *actor( true ), pr ) );
             if( !text.empty() ) {
                 add_response( text, "TALK_TRAIN_NPC_START", pr );
             }
         }
         add_response_none( _( "Eh, never mind." ) );
     } else if( the_topic.id == "TALK_TRAIN_SEMINAR" ) {
         const std::vector<skill_id> &sklist = actor( true )->skills_teacheable();
         const std::vector<proficiency_id> &prlist = actor( true )->proficiencies_teacheable();
         const std::vector<matype_id> &malist = actor( true )->styles_teacheable();
         const std::vector<spell_id> &splist = actor( true )->spells_teacheable();
         if( sklist.empty() && prlist.empty() && malist.empty() && splist.empty() ) {
             add_response_none( _( "Oh, okay." ) );
             return;
         }
         for( const skill_id &sk : sklist ) {
             if( sk->obsolete() ) {
                 continue;
             }
             const std::string &text =
                 string_format( "%s: %s", _( "Skill" ), actor( true )->skill_seminar_text( sk ) );
             add_response( text, "TALK_TRAIN_SEMINAR_START", sk );
         }
         for( const proficiency_id &pr : prlist ) {
             const std::string &text =
                 string_format( "%s: %s", _( "Proficiency" ), actor( true )->proficiency_seminar_text( pr ) );
             add_response( text, "TALK_TRAIN_SEMINAR_START", pr );
         }
         for( const matype_id &ma : malist ) {
             const std::string &text =
                 string_format( "%s: %s", _( "Style" ), actor( true )->style_seminar_text( ma ) );
             add_response( text, "TALK_TRAIN_SEMINAR_START", ma.obj() );
         }
         for( const spell_id &sp : splist ) {
             const std::string &text =
                 string_format( "%s: %s", _( "Spell" ), actor( true )->spell_seminar_text( sp ) );
             add_response( text, "TALK_TRAIN_SEMINAR_START", sp );
         }
         add_response_none( _( "Eh, never mind." ) );
     } else if( the_topic.id == "TALK_TRAIN" ) {
         if( !player_character.backlog.empty() && player_character.backlog.front().id() == ACT_TRAIN &&
             player_character.backlog.front().index == actor( true )->getID().get_value() ) {
             player_activity &backlog = player_character.backlog.front();
             const skill_id skillt( backlog.name );
             // TODO: This is potentially dangerous. A skill and a martial art
             // could have the same ident!
             if( !skillt.is_valid() ) {
                 const matype_id styleid = matype_id( backlog.name );
                 if( !styleid.is_valid() ) {
                     const proficiency_id profid = proficiency_id( backlog.name );
                     if( !profid.is_valid() ) {
                         const spell_id &sp_id = spell_id( backlog.name );
                         if( actor( true )->knows_spell( sp_id ) ) {
                             add_response( string_format( _( "Yes, let's resume training %s" ),
                                                          sp_id->name ), "TALK_TRAIN_START", sp_id );
                         }
                     } else {
                         add_response( string_format( _( "Yes, let's resume training %s" ),
                                                      profid->name() ), "TALK_TRAIN_START", profid );
                     }
                 } else {
                     const martialart &style = styleid.obj();
                     add_response( string_format( _( "Yes, let's resume training %s" ),
                                                  style.name ), "TALK_TRAIN_START", style );
                 }
             } else {
                 add_response( string_format( _( "Yes, let's resume training %s" ), skillt->name() ),
                               "TALK_TRAIN_START", skillt );
             }
         }
         const std::vector<matype_id> &styles = actor( true )->styles_offered_to( *actor( false ) );
         const std::vector<skill_id> &trainable = actor( true )->skills_offered_to( *actor( false ) );
         const std::vector<spell_id> &teachable = actor( true )->spells_offered_to( *actor( false ) );
         const std::vector<proficiency_id> &proficiencies = actor( true )->proficiencies_offered_to( *actor(
                     false ) );
         if( trainable.empty() && styles.empty() && teachable.empty() && proficiencies.empty() ) {
             add_response_none( _( "Oh, okay." ) );
             return;
         }
         for( const spell_id &sp : teachable ) {
             const std::string &text =
                 string_format( "%s: %s", _( "Spell" ), actor( true )->spell_training_text( *actor( false ), sp ) );
             if( !text.empty() ) {
                 add_response( text, "TALK_TRAIN_START", sp );
             }
         }
         for( const matype_id &style_id : styles ) {
             const std::string &text =
                 string_format( "%s: %s", _( "Style" ),
                                actor( true )->style_training_text( *actor( false ), style_id ) );
             if( !text.empty() ) {
                 add_response( text, "TALK_TRAIN_START", style_id.obj() );
             }
         }
         for( const skill_id &trained : trainable ) {
             const std::string &text =
                 string_format( "%s: %s", _( "Skill" ),
                                actor( true )->skill_training_text( *actor( false ), trained ) );
             if( !text.empty() && !trained->obsolete() ) {
                 add_response( text, "TALK_TRAIN_START", trained );
             }
         }
         for( const proficiency_id &trained : proficiencies ) {
             const std::string &text =
                 string_format( "%s: %s", _( "Proficiency" ),
                                actor( true )->proficiency_training_text( *actor( false ), trained ) );
             if( !text.empty() ) {
                 add_response( text, "TALK_TRAIN_START", trained );
             }
         }
         add_response_none( _( "Eh, never mind." ) );
     } else if( the_topic.id == "TALK_HOW_MUCH_FURTHER" ) {
         add_response_none( _( "Okay, thanks." ) );
         add_response_done( _( "Let's keep moving." ) );
     }
     if( actor( false )->has_trait( trait_DEBUG_MIND_CONTROL ) && !actor( true )->is_player_ally() ) {
         add_response( _( "OBEY ME!" ), "TALK_MIND_CONTROL" );
         add_response_done( _( "Bye." ) );
     }
     if( player_character.has_trait( trait_PROF_CHURL ) && ( actor( true )->get_npc_trust() >= 0 ) &&
         ( actor( true )->get_npc_anger() <= 0 ) && ( actor( true )->int_cur() >= 9 ) &&
         !( the_topic.id == "TALK_CHURL_FRIENDLY" ) ) {
         add_response( _( "Ho there, otherwyrldly devyl!  Have yow ware for to chaffare?" ),
                       "TALK_CHURL_FRIENDLY" );
         add_response_done( _( "Farewell!" ) );
     }
     if( responses.empty() ) {
         add_response_done( _( "Bye." ) );
     }
 }
References _, ACT_TRAIN, actor(), add_response(), add_response_done(), add_response_none(), Character::backlog, json_talk_topic::gen_responses(), get_player_character(), mission::get_type(), get_value(), Character::has_trait(), talk_topic::id, string_id< T >::is_valid(), json_talk_topics, matype_id, missions_assigned, spell_type::name, martialart::name, player_activity::name, proficiency::name(), Skill::name(), string_id< T >::obj(), talker::proficiencies_offered_to(), talker::proficiencies_teacheable(), proficiency_id, responses, om_direction::size, talker::skills_offered_to(), talker::skills_teacheable(), spell_id, talker::spells_offered_to(), talker::spells_teacheable(), string_format(), talker::styles_offered_to(), talker::styles_teacheable(), mission_type::tname(), trait_DEBUG_MIND_CONTROL, and trait_PROF_CHURL.
Referenced by opt().
get_best_quit_response()
int dialogue::get_best_quit_response () private
Finds the best response to use when the player is trying to quit.
Returns the index into the response list.
Definition at line 2671 of file npctalk.cpp.
 {
     if( responses.size() == 1 ) {
         // Only one response. Use it. Consequences will be prompted for by the caller.
         return 0;
     }
     // Find relevant responses
     for( size_t i = 0; i < responses.size(); ++i ) {
         const talk_response &response = responses[i];
         if( response.trial.calc_chance( *this ) < 100 ) {
             // Don't pick anything with a chance to fail.
             continue;
         }
         if( !response.success.effects.empty() ) {
             // Don't pick anything with side effects
             continue;
         }
         // Unfortunately, while we'd like to be able to go "back" from nested dialogue trees, the
         // topic stack doesn't always shrink. Returning to the previous topic is sometimes done
         // with TALK_NONE, or sometimes by referencing the topic id directly. No solution really
         // gives us something that feels right in all cases, so we only support completely leaving
         // the conversation via the quit key.
         if( response.success.next_topic.id == "TALK_DONE" ) {
             return i;
         }
     }
     return responses.size(); // Didn't find a good option
 }
References talk_trial::calc_chance(), talk_effect_t::effects, talk_topic::id, talk_effect_t::next_topic, responses, talk_response::success, and talk_response::trial.
Referenced by opt().
get_callstack()
std::string dialogue::get_callstack () const
Definition at line 2349 of file npctalk.cpp.
 {
     if( !callstack.empty() ) {
         return "Callstack: " + callstack;
     }
     return "";
 }
References callstack.
Referenced by eoc_math::act(), effect_on_condition::activate(), actor(), dialogue(), dbl_or_var_part::evaluate(), duration_or_var_part::evaluate(), abstract_str_or_var< T >::evaluate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_roll_remainder(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), maybe_read_var_value(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::process_eoc(), and write_var_value().
get_conditionals()
const std::unordered_map< std::string, std::function< bool(dialogue &)> > & dialogue::get_conditionals () const
Definition at line 2335 of file npctalk.cpp.
 {
     return conditionals;
 }
References conditionals.
Referenced by effect_on_condition::activate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), and run_item_eocs().
get_context()
const std::unordered_map< std::string, std::string > & dialogue::get_context () const
Definition at line 2329 of file npctalk.cpp.
 {
     return context;
 }
References context.
Referenced by effect_on_condition::activate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_monster_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_npc_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::process_eoc(), process_reactivation(), and run_item_eocs().
get_value()
std::string dialogue::get_value (const std::string & key) const
Definition at line 2306 of file npctalk.cpp.
 {
     return maybe_get_value( key ).value_or( std::string{} );
 }
References maybe_get_value().
Referenced by gen_responses(), parse_tags(), and write_var_value().
maybe_get_value()
std::optional< std::string > dialogue::maybe_get_value (const std::string & key) const
Definition at line 2311 of file npctalk.cpp.
 {
     auto it = context->find( key );
     return it == context->end() ? std::nullopt : std::optional<std::string> { it->second };
 }
References context.
Referenced by get_value(), and maybe_read_var_value().
operator=() [1/2]
dialogue& dialogue::operator= (const dialogue &)
operator=() [2/2]
dialogue& dialogue::operator= (dialogue &&) default
opt()
talk_topic dialogue::opt (dialogue_window & d_win, const talk_topic & topic)
Definition at line 2524 of file npctalk.cpp.
 {
     d_win.add_history_separator();
     ui_adaptor ui;
     const auto resize_cb = [&]( ui_adaptor & ui ) {
         d_win.resize( ui );
     };
     ui.on_screen_resize( resize_cb );
     resize_cb( ui );
     // Construct full line
     std::string challenge = dynamic_line( topic );
     gen_responses( topic );
     // Put quotes around challenge (unless it's an action)
     if( challenge[0] != '*' && challenge[0] != '&' ) {
         challenge = string_format( _( "\"%s\"" ), challenge );
     }
     // Parse any tags in challenge
     if( actor( true )->get_npc() ) {
         parse_tags( challenge, *actor( false )->get_character(), *actor( true )->get_npc(), *this,
                     topic.item_type );
     } else {
         parse_tags( challenge, *actor( false )->get_character(), *actor( false )->get_character(), *this,
                     topic.item_type );
     }
     challenge = uppercase_first_letter( challenge );
     d_win.clear_history_highlights();
     if( challenge[0] == '&' ) {
         // No name prepended!
         challenge = challenge.substr( 1 );
         d_win.add_to_history( challenge );
     } else if( challenge[0] == '*' ) {
         // Prepend name
         challenge = string_format( pgettext( "npc does something", "%s %s" ), actor( true )->disp_name(),
                                    challenge.substr( 1 ) );
         d_win.add_to_history( challenge );
     } else {
         npc *npc_actor = actor( true )->get_npc();
         d_win.add_to_history( challenge, d_win.is_not_conversation ? "" : actor( true )->disp_name(),
                               npc_actor ? npc_actor->basic_symbol_color() : c_red );
     }
     apply_speaker_effects( topic );
     if( responses.empty() ) {
         debugmsg( "No dialogue responses" );
         return talk_topic( "TALK_NONE" );
     }
     input_context ctxt( "DIALOGUE_CHOOSE_RESPONSE" );
     d_win.set_up_scrolling( ctxt );
     ctxt.register_action( "HELP_KEYBINDINGS" );
     ctxt.register_action( "CONFIRM" );
     ctxt.register_action( "ANY_INPUT" );
     ctxt.register_action( "QUIT" );
     std::vector<talk_data> response_lines;
     std::vector<input_event> response_hotkeys;
     const auto generate_response_lines = [&]() {
 #if defined(__ANDROID__)
         ctxt.get_registered_manual_keys().clear();
 #endif
         const hotkey_queue &queue = hotkey_queue::alphabets();
         response_lines.clear();
         response_hotkeys.clear();
         input_event evt = ctxt.first_unassigned_hotkey( queue );
         for( talk_response &response : responses ) {
             const talk_data &td = response.create_option_line( *this, evt, d_win.is_computer );
             response_lines.emplace_back( td );
             response_hotkeys.emplace_back( evt );
 #if defined(__ANDROID__)
             ctxt.register_manual_key( evt.get_first_input(), td.text );
 #endif
             evt = ctxt.next_unassigned_hotkey( queue, evt );
         }
         d_win.set_responses( response_lines );
     };
     generate_response_lines();
     ui.on_redraw( [&]( const ui_adaptor & ) {
         d_win.draw( d_win.is_not_conversation ? "" : actor( true )->disp_name() );
     } );
     size_t response_ind = response_hotkeys.size();
     bool okay;
     do {
         std::string action;
         do {
             ui_manager::redraw();
             input_event evt;
             action = ctxt.handle_input();
             evt = ctxt.get_raw_input();
             d_win.handle_scrolling( action, ctxt );
             talk_topic st = special_talk( action );
             if( st.id != "TALK_NONE" ) {
                 return st;
             }
             if( action == "HELP_KEYBINDINGS" ) {
                 // Reallocate hotkeys as keybindings may have changed
                 generate_response_lines();
             } else if( action == "CONFIRM" ) {
                 response_ind = d_win.sel_response;
             } else if( action == "ANY_INPUT" ) {
                 // Check real hotkeys
                 const auto hotkey_it = std::find( response_hotkeys.begin(),
                                                   response_hotkeys.end(), evt );
                 response_ind = std::distance( response_hotkeys.begin(), hotkey_it );
             } else if( action == "QUIT" ) {
                 response_ind = get_best_quit_response();
             }
         } while( response_ind >= response_hotkeys.size() ||
                  ( action != "ANY_INPUT" && action != "QUIT" && action != "CONFIRM" ) );
         okay = true;
         std::set<dialogue_consequence> consequences = responses[response_ind].get_consequences( *this );
         if( consequences.count( dialogue_consequence::hostile ) > 0 ) {
             okay = query_yn( _( "You may be attacked!  Proceed?" ) );
         } else if( consequences.count( dialogue_consequence::helpless ) > 0 ) {
             okay = query_yn( _( "You'll be helpless!  Proceed?" ) );
         }
     } while( !okay );
     d_win.add_history_separator();
     d_win.add_to_history( response_lines[response_ind].text, _( "You" ), c_light_blue );
     talk_response chosen = responses[response_ind];
     if( chosen.mission_selected != nullptr ) {
         actor( true )->select_mission( chosen.mission_selected );
     }
     // We can't set both skill and style or training will bug out
     // TODO: Allow setting both skill and style
     actor( true )->store_chosen_training( chosen.skill, chosen.style, chosen.dialogue_spell,
                                           chosen.proficiency );
     const bool success = chosen.trial.roll( *this );
     talk_effect_t const &effects = success ? chosen.success : chosen.failure;
     talk_topic ret_topic =  effects.apply( *this );
     talk_effect_t::update_missions( *this );
     return ret_topic;
 }
References _, action, actor(), dialogue_window::add_history_separator(), dialogue_window::add_to_history(), hotkey_queue::alphabets(), apply_speaker_effects(), npc::basic_symbol_color(), c_light_blue, c_red, dialogue_window::clear_history_highlights(), debugmsg, talk_response::dialogue_spell, dialogue_window::draw(), dynamic_line(), talk_response::failure, input_context::first_unassigned_hotkey(), gen_responses(), get_best_quit_response(), input_event::get_first_input(), talker::get_npc(), input_context::get_raw_input(), input_context::handle_input(), dialogue_window::handle_scrolling(), helpless, hostile, talk_topic::id, dialogue_window::is_computer, dialogue_window::is_not_conversation, talk_topic::item_type, talk_response::mission_selected, input_context::next_unassigned_hotkey(), okay, parse_tags(), pgettext, talk_response::proficiency, query_yn(), ui_manager::redraw(), input_context::register_action(), dialogue_window::resize(), responses, talk_trial::roll(), dialogue_window::sel_response, talker::select_mission(), dialogue_window::set_responses(), dialogue_window::set_up_scrolling(), talk_response::skill, special_talk(), talker::store_chosen_training(), string_format(), talk_response::style, talk_response::success, talk_data::text, talk_response::trial, talk_effect_t::update_missions(), and uppercase_first_letter().
remove_value()
void dialogue::remove_value (const std::string & key)
Definition at line 2301 of file npctalk.cpp.
 {
     context->erase( key );
 }
References context.
set_conditional()
void dialogue::set_conditional (const std::string & key, const std::function< bool(dialogue &)> & value)
Definition at line 2317 of file npctalk.cpp.
 {
     conditionals[key] = value;
 }
References conditionals.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_condition().
set_value()
void dialogue::set_value (const std::string & key, const std::string & value)
Definition at line 2296 of file npctalk.cpp.
 {
     context[key] = value;
 }
References context.
Referenced by Character::activate_mutation(), eoc_examine_actor::call(), Character::deactivate_mutation(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), suffer::mutation_power(), damage_type::ondamage_effects(), process_eocs(), and write_var_value().
Member Data Documentation
alpha
std::unique_ptr<talker> dialogue::alpha private
The talker that speaks (almost certainly representing the avatar, ie get_avatar())
Definition at line 244 of file dialogue.h.
Referenced by actor(), and dialogue().
beta
std::unique_ptr<talker> dialogue::beta private
The talker responded to alpha, usually a talker_npc.
Definition at line 248 of file dialogue.h.
Referenced by actor(), and dialogue().
by_radio
bool dialogue::by_radio = false
This dialogue is happening over a radio.
Definition at line 215 of file dialogue.h.
Referenced by avatar::talk_to().
callstack
std::string dialogue::callstack private
Definition at line 253 of file dialogue.h.
Referenced by amend_callstack(), dialogue(), and get_callstack().
conditionals
lazy<std::unordered_map<std::string, std::function<bool(dialogue &)> > > dialogue::conditionals private
Definition at line 256 of file dialogue.h.
Referenced by dialogue(), evaluate_conditional(), get_conditionals(), and set_conditional().
context
lazy<std::unordered_map<std::string, std::string> > dialogue::context private
Definition at line 251 of file dialogue.h.
Referenced by dialogue(), get_context(), maybe_get_value(), remove_value(), and set_value().
cur_item
itype_id dialogue::cur_item mutable
Definition at line 208 of file dialogue.h.
Referenced by dynamic_line(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_bulk_trade_accept().
done
bool dialogue::done = false
If true, we are done talking and the dialog ends.
Definition at line 188 of file dialogue.h.
has_alpha
bool dialogue::has_alpha
Definition at line 225 of file dialogue.h.
Referenced by actor(), dialogue(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::process_eoc(), and write_var_value().
has_beta
bool dialogue::has_beta
Definition at line 224 of file dialogue.h.
Referenced by actor(), talk_effect_t::apply(), dialogue(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_offer_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_string_var(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::receive_item(), talk_effect_t::update_missions(), and write_var_value().
missions_assigned
std::vector<mission *> dialogue::missions_assigned
Missions that have been assigned by this npc to the player they currently speak to.
Definition at line 192 of file dialogue.h.
Referenced by gen_responses(), mission::is_complete(), and talk_effect_t::update_missions().
reason
std::string dialogue::reason mutable
Definition at line 209 of file dialogue.h.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_gets_item(), and widget_clause::meets_condition().
responses
std::vector<talk_response> dialogue::responses
Possible responses from the player character, filled in gen_responses.
Definition at line 219 of file dialogue.h.
Referenced by add_response(), json_talk_response::gen_repeat_response(), gen_responses(), json_talk_topic::gen_responses(), json_talk_response::gen_responses(), get_best_quit_response(), and opt().
topic_stack
std::vector<talk_topic> dialogue::topic_stack
Definition at line 189 of file dialogue.h.
Referenced by add_topic().
The documentation for this struct was generated from the following files:
src/dialogue.h
src/npctalk.cpp