Cataclysm DDA: mutation_variant Struct Reference
mutation_variant Struct Reference
#include <mutation.h>
Public Member Functions
void deserialize (const JsonObject &jo)
void load (const JsonObject &jo)
Public Attributes
std::string id
translation alt_name
translation alt_description
bool append_desc = false
int weight = 0
trait_id parent
Detailed Description
Definition at line 151 of file mutation.h.
Member Function Documentation
deserialize()
void mutation_variant::deserialize (const JsonObject & jo)
Definition at line 297 of file mutation_data.cpp.
 {
     load( jo );
 }
References load().
load()
void mutation_variant::load (const JsonObject & jo)
Definition at line 287 of file mutation_data.cpp.
 {
     mandatory( jo, false, "id", id );
     mandatory( jo, false, "name", alt_name );
     mandatory( jo, false, "description", alt_description );
     optional( jo, false, "append_desc", append_desc );
     optional( jo, false, "weight", weight );
 }
References alt_description, alt_name, append_desc, mandatory, optional(), and weight.
Referenced by deserialize().
Member Data Documentation
alt_description
translation mutation_variant::alt_description
Definition at line 155 of file mutation.h.
Referenced by load().
alt_name
translation mutation_variant::alt_name
Definition at line 154 of file mutation.h.
Referenced by load().
append_desc
bool mutation_variant::append_desc = false
Definition at line 158 of file mutation.h.
Referenced by load().
id
std::string mutation_variant::id
Definition at line 152 of file mutation.h.
Referenced by Character::mutate_towards(), and Character::remove_mutation().
parent
trait_id mutation_variant::parent
Definition at line 166 of file mutation.h.
weight
int mutation_variant::weight = 0
Definition at line 162 of file mutation.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/mutation.h
src/mutation_data.cpp