Cataclysm DDA: stat_hp_mods Struct Reference
stat_hp_mods Struct Reference
#include <bodypart.h>
Public Member Functions
void load (const JsonObject &jsobj)
void deserialize (const JsonObject &jo)
Public Attributes
float str_mod = 3.0f
float dex_mod = 0.0f
float int_mod = 0.0f
float per_mod = 0.0f
float health_mod = 0.0f
bool was_loaded = false
Detailed Description
Definition at line 93 of file bodypart.h.
Member Function Documentation
deserialize()
void stat_hp_mods::deserialize (const JsonObject & jo)
Definition at line 1233 of file bodypart.cpp.
 {
     load( jo );
 }
References load().
load()
void stat_hp_mods::load (const JsonObject & jsobj)
Definition at line 1223 of file bodypart.cpp.
 {
     optional( jsobj, was_loaded, "str_mod", str_mod, 3.0f );
     optional( jsobj, was_loaded, "dex_mod", dex_mod, 0.0f );
     optional( jsobj, was_loaded, "int_mod", int_mod, 0.0f );
     optional( jsobj, was_loaded, "per_mod", per_mod, 0.0f );
     optional( jsobj, was_loaded, "health_mod", health_mod, 0.0f );
 }
References dex_mod, health_mod, int_mod, optional(), per_mod, str_mod, and was_loaded.
Referenced by deserialize().
Member Data Documentation
dex_mod
float stat_hp_mods::dex_mod = 0.0f
Definition at line 96 of file bodypart.h.
Referenced by load().
health_mod
float stat_hp_mods::health_mod = 0.0f
Definition at line 100 of file bodypart.h.
Referenced by load().
int_mod
float stat_hp_mods::int_mod = 0.0f
Definition at line 97 of file bodypart.h.
Referenced by load().
per_mod
float stat_hp_mods::per_mod = 0.0f
Definition at line 98 of file bodypart.h.
Referenced by load().
str_mod
float stat_hp_mods::str_mod = 3.0f
Definition at line 95 of file bodypart.h.
Referenced by load().
was_loaded
bool stat_hp_mods::was_loaded = false
Definition at line 102 of file bodypart.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/bodypart.h
src/bodypart.cpp