Cataclysm DDA: damage_type Struct Reference
damage_type Struct Reference
#include <damage.h>
Public Member Functions
void onhit_effects (Creature *source, Creature *target) const
void ondamage_effects (Creature *source, Creature *target, bodypart_str_id bp, double total_damage=0.0, double damage_taken=0.0) const
void load (const JsonObject &jo, std::string_view)
Static Public Member Functions
static void load_damage_types (const JsonObject &jo, const std::string &src)
static void reset ()
static void check ()
static const std::vector< damage_type > & get_all ()
Public Attributes
damage_type_id id
translation name
std::vector< effect_on_condition_id > onhit_eocs
std::vector< effect_on_condition_id > ondamage_eocs
skill_id skill = skill_id::NULL_ID()
std::pair< damage_type_id, float > derived_from = { damage_type_id(), 0.0f }
cata::flat_set< std::string > immune_flags
cata::flat_set< std::string > mon_immune_flags
nc_color magic_color
bool melee_only = false
bool physical = false
bool mon_difficulty = false
bool no_resist = false
bool edged = false
bool env = false
bool material_required = false
bool was_loaded = false
Detailed Description
Definition at line 28 of file damage.h.
Member Function Documentation
check()
void damage_type::check () static
Definition at line 162 of file damage.cpp.
 {
     for( const damage_type &dt : damage_type::get_all() ) {
         const std::vector<damage_info_order> &dio_list = damage_info_order::get_all();
         auto iter = std::find_if( dio_list.begin(), dio_list.end(),
         [&dt]( const damage_info_order & dio ) {
             return dt.id == dio.dmg_type;
         } );
         if( iter == dio_list.end() ) {
             debugmsg( "damage type %s has no associated damage_info_order type.", dt.id.c_str() );
         }
     }
 }
References debugmsg, get_all(), and damage_info_order::get_all().
Referenced by DynamicDataLoader::check_consistency().
get_all()
const std::vector< damage_type > & damage_type::get_all () static
Definition at line 78 of file damage.cpp.
 {
     return damage_type_factory.get_all();
 }
References anonymous_namespace{damage.cpp}::damage_type_factory.
Referenced by weakpoint::apply_to(), armor_inventory_preset::armor_inventory_preset(), item::base_damage_melee(), blank_damage_instance(), check(), material_type::check(), anonymous_namespace{armor_layers.cpp}::clothing_protection(), weapon_inventory_preset::deals_melee_damage(), dealt_damage_instance::dealt_damage_instance(), finalize_damage_map(), item::has_edged_damage(), Character::intimidation(), item::is_melee(), Character::melee_attack_abstract(), item::melee_combat_info(), anonymous_namespace{math_parser_diag.cpp}::melee_damage_eval(), melee_message(), item::melee_skill(), melee_train(), Character::modify_damage_dealt_with_enchantments(), Character::perform_technique(), Character::power_rating(), bodygraph_display::prepare_infotext(), resistances::resistances(), and Character::roll_all_damage().
load()
void damage_type::load (const JsonObject & jo, std::string_view)
Definition at line 115 of file damage.cpp.
 {
     mandatory( jo, was_loaded, "name", name );
     optional( jo, was_loaded, "skill", skill, skill_id::NULL_ID() );
     optional( jo, was_loaded, "physical", physical );
     optional( jo, was_loaded, "melee_only", melee_only );
     optional( jo, was_loaded, "edged", edged );
     optional( jo, was_loaded, "environmental", env );
     optional( jo, was_loaded, "material_required", material_required );
     optional( jo, was_loaded, "mon_difficulty", mon_difficulty );
     optional( jo, was_loaded, "no_resist", no_resist );
     if( jo.has_object( "immune_flags" ) ) {
         JsonObject jsobj = jo.get_object( "immune_flags" );
         if( jsobj.has_array( "monster" ) ) {
             mon_immune_flags.clear();
             for( const std::string flg : jsobj.get_array( "monster" ) ) {
                 mon_immune_flags.insert( flg );
             }
         }
         if( jsobj.has_array( "character" ) ) {
             immune_flags.clear();
             for( const std::string flg : jsobj.get_array( "character" ) ) {
                 immune_flags.insert( flg );
             }
         }
     }
     if( !was_loaded || jo.has_string( "magic_color" ) ) {
         std::string color_str;
         optional( jo, was_loaded, "magic_color", color_str, "black" );
         magic_color = color_from_string( color_str );
     }
     if( jo.has_array( "derived_from" ) ) {
         JsonArray ja = jo.get_array( "derived_from" );
         derived_from = { damage_type_id( ja.get_string( 0 ) ), static_cast<float>( ja.get_float( 1 ) ) };
     }
     for( JsonValue jv : jo.get_array( "onhit_eocs" ) ) {
         onhit_eocs.push_back( effect_on_conditions::load_inline_eoc( jv, "" ) );
     }
     for( JsonValue jv : jo.get_array( "ondamage_eocs" ) ) {
         ondamage_eocs.push_back( effect_on_conditions::load_inline_eoc( jv, "" ) );
     }
 }
References color_from_string(), derived_from, edged, env, JsonObject::get_array(), JsonArray::get_float(), JsonObject::get_object(), JsonArray::get_string(), JsonObject::has_array(), JsonObject::has_object(), JsonObject::has_string(), immune_flags, cata::flat_set< T, Compare, Data >::insert(), effect_on_conditions::load_inline_eoc(), magic_color, mandatory, material_required, melee_only, mon_difficulty, mon_immune_flags, name, no_resist, string_id< Skill >::NULL_ID(), ondamage_eocs, onhit_eocs, optional(), physical, skill, and was_loaded.
load_damage_types()
void damage_type::load_damage_types (const JsonObject & jo, const std::string & src) static
Definition at line 68 of file damage.cpp.
 {
     damage_type_factory.load( jo, src );
 }
References anonymous_namespace{damage.cpp}::damage_type_factory.
Referenced by DynamicDataLoader::initialize().
ondamage_effects()
void damage_type::ondamage_effects (Creature * source, Creature * target, bodypart_str_id bp, double total_damage = 0.0, double damage_taken = 0.0) const
Definition at line 433 of file damage.cpp.
 {
     for( const effect_on_condition_id &eoc : ondamage_eocs ) {
         dialogue d( source == nullptr ? nullptr : get_talker_for( source ),
                     target == nullptr ? nullptr : get_talker_for( target ) );
         d.set_value( "npctalk_var_damage_taken", std::to_string( damage_taken ) );
         d.set_value( "npctalk_var_total_damage", std::to_string( total_damage ) );
         d.set_value( "npctalk_var_bp", bp.str() );
         if( eoc->type == eoc_type::ACTIVATION ) {
             eoc->activate( d );
         } else {
             debugmsg( "Must use an activation eoc for a damage type effect.  If you don't want the effect_on_condition to happen on its own (without the damage type effect being activated), remove the recurrence min and max.  Otherwise, create a non-recurring effect_on_condition for this damage type with its condition and effects, then have a recurring one queue it." );
         }
     }
 }
References ACTIVATION, bp, debugmsg, eoc, get_talker_for(), dialogue::set_value(), and to_string().
onhit_effects()
void damage_type::onhit_effects (Creature * source, Creature * target) const
Definition at line 393 of file damage.cpp.
 {
     for( const effect_on_condition_id &eoc : onhit_eocs ) {
         dialogue d( source == nullptr ? nullptr : get_talker_for( source ),
                     target == nullptr ? nullptr : get_talker_for( target ) );
         if( eoc->type == eoc_type::ACTIVATION ) {
             eoc->activate( d );
         } else {
             debugmsg( "Must use an activation eoc for a damage type effect.  If you don't want the effect_on_condition to happen on its own (without the damage type effect being activated), remove the recurrence min and max.  Otherwise, create a non-recurring effect_on_condition for this damage type with its condition and effects, then have a recurring one queue it." );
         }
     }
 }
References ACTIVATION, debugmsg, eoc, and get_talker_for().
reset()
void damage_type::reset () static
Definition at line 73 of file damage.cpp.
 {
     damage_type_factory.reset();
 }
References anonymous_namespace{damage.cpp}::damage_type_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
derived_from
std::pair<damage_type_id, float> damage_type::derived_from = { damage_type_id(), 0.0f }
Definition at line 34 of file damage.h.
Referenced by item::_environmental_resist(), item::_resist(), and load().
edged
bool damage_type::edged = false
Definition at line 42 of file damage.h.
Referenced by item::damage_melee(), monster::deal_damage_handle_type(), and load().
env
bool damage_type::env = false
Definition at line 43 of file damage.h.
Referenced by item::_resist(), and load().
id
damage_type_id damage_type::id
Definition at line 29 of file damage.h.
immune_flags
cata::flat_set<std::string> damage_type::immune_flags
Definition at line 35 of file damage.h.
Referenced by Character::is_immune_damage(), and load().
magic_color
nc_color damage_type::magic_color
Definition at line 37 of file damage.h.
Referenced by spell::damage_type_color(), and load().
material_required
bool damage_type::material_required = false
Definition at line 44 of file damage.h.
Referenced by load().
melee_only
bool damage_type::melee_only = false
Definition at line 38 of file damage.h.
Referenced by Character::block_hit(), load(), and Character::roll_damage().
mon_difficulty
bool damage_type::mon_difficulty = false
Definition at line 40 of file damage.h.
Referenced by load().
mon_immune_flags
cata::flat_set<std::string> damage_type::mon_immune_flags
Definition at line 36 of file damage.h.
Referenced by monster::is_immune_damage(), and load().
name
translation damage_type::name
Definition at line 30 of file damage.h.
Referenced by spell::damage_type_string(), damage_info_order::finalize(), bonus_container::get_description(), load(), Character::on_damage_of_type(), and print_damage_info().
no_resist
bool damage_type::no_resist = false
Definition at line 41 of file damage.h.
Referenced by Character::block_hit(), Character::get_armor_type(), and load().
ondamage_eocs
std::vector<effect_on_condition_id> damage_type::ondamage_eocs
Definition at line 32 of file damage.h.
Referenced by load().
onhit_eocs
std::vector<effect_on_condition_id> damage_type::onhit_eocs
Definition at line 31 of file damage.h.
Referenced by load().
physical
bool damage_type::physical = false
Definition at line 39 of file damage.h.
Referenced by Character::block_hit(), item::damage_type_can_damage_items(), and load().
skill
skill_id damage_type::skill = skill_id::NULL_ID()
Definition at line 33 of file damage.h.
Referenced by load(), and roll_melee_damage_internal().
was_loaded
bool damage_type::was_loaded = false
Definition at line 45 of file damage.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/damage.h
src/damage.cpp