Cataclysm DDA: diag_value Struct Reference
diag_value Struct Reference
#include <math_parser_diag_value.h>
Public Types
using impl_t = std::variant< double, std::string, var_info, math_exp, diag_array >
Public Member Functions
diag_value ()=default
template<class U >
diag_value (U u)
template<class T , class... Args>
diag_value (std::in_place_type_t< T >, Args &&...args)
bool is_dbl () const
double dbl () const
bool is_str () const
std::string_view str () const
bool is_var () const
var_info var () const
bool is_array () const
diag_array const & array () const
double dbl (dialogue const &d) const
std::string str (dialogue const &d) const
diag_array const & array (dialogue const &) const
Public Attributes
impl_t data
Detailed Description
Definition at line 18 of file math_parser_diag_value.h.
Member Typedef Documentation
impl_t
using diag_value::impl_t = std::variant<double, std::string, var_info, math_exp, diag_array>
Definition at line 42 of file math_parser_diag_value.h.
Constructor & Destructor Documentation
diag_value() [1/3]
diag_value::diag_value () default
diag_value() [2/3]
template<class U > diag_value::diag_value (U u) inline explicit
Definition at line 21 of file math_parser_diag_value.h.
 : data( std::in_place_type<U>, std::forward<U>( u ) ) {}
diag_value() [3/3]
template<class T , class... Args> diag_value::diag_value (std::in_place_type_t< T > , Args &&... args) inline explicit
Definition at line 23 of file math_parser_diag_value.h.
         : data( std::in_place_type<T>, std::forward<Args>( args )... ) {}
Member Function Documentation
array() [1/2]
diag_array const & diag_value::array () const
Definition at line 162 of file math_parser_diag_value.cpp.
 {
     return _diag_value_at_parse_time<diag_array, diag_array const &>( data );
 }
References data.
Referenced by anonymous_namespace{math_parser_diag.cpp}::_test_add(), and anonymous_namespace{math_parser_diag.cpp}::_test_len().
array() [2/2]
diag_array const & diag_value::array (dialogue const &) const
Definition at line 167 of file math_parser_diag_value.cpp.
 {
     return _diag_value_at_parse_time<diag_array, diag_array const &, true>( data );
 }
References data.
dbl() [1/2]
double diag_value::dbl () const
Definition at line 64 of file math_parser_diag_value.cpp.
 {
     return _diag_value_at_parse_time<double>( data );
 }
References data.
Referenced by anonymous_namespace{math_parser_diag.cpp}::_characters_nearby_eval(), anonymous_namespace{math_parser_diag.cpp}::_monsters_nearby_eval(), anonymous_namespace{math_parser_diag.cpp}::_test_add(), and anonymous_namespace{math_parser_diag.cpp}::value_or_eval().
dbl() [2/2]
double diag_value::dbl (dialogue const & d) const
Definition at line 69 of file math_parser_diag_value.cpp.
 {
     return std::visit( overloaded{
         []( double v )
         {
             return v;
         },
         []( std::string const & v )
         {
             if( std::optional<double> ret = svtod( v ); ret ) {
                 return *ret;
             }
             debugmsg( R"(Could not convert string "%s" to double)", v );
             return 0.0;
         },
         [&d]( var_info const & v )
         {
             std::string const val = read_var_value( v, d );
             if( std::optional<double> ret = svtod( val ); ret ) {
                 return *ret;
             }
             debugmsg( R"(Could not convert variable "%s" with value "%s" to double)", v.name, val );
             return 0.0;
         },
         [&d]( math_exp const & v )
         {
             // FIXME: maybe re-constify eval paths?
             return v.eval( const_cast<dialogue &>( d ) );
         },
         []( diag_array const & )
         {
             debugmsg( R"(Cannot directly convert array to doubles)" );
             return 0.0;
         },
     },
     data );
 }
References data, debugmsg, read_var_value(), cata::hash64_detail::ret, and svtod().
is_array()
bool diag_value::is_array () const
Definition at line 157 of file math_parser_diag_value.cpp.
 {
     return std::holds_alternative<diag_array>( data );
 }
References data.
Referenced by anonymous_namespace{math_parser_diag.cpp}::_test_add().
is_dbl()
bool diag_value::is_dbl () const
Definition at line 59 of file math_parser_diag_value.cpp.
 {
     return std::holds_alternative<double>( data );
 }
References data.
is_str()
bool diag_value::is_str () const
Definition at line 107 of file math_parser_diag_value.cpp.
 {
     return std::holds_alternative<std::string>( data );
 }
References data.
is_var()
bool diag_value::is_var () const
Definition at line 147 of file math_parser_diag_value.cpp.
 {
     return std::holds_alternative<var_info>( data );
 }
References data.
str() [1/2]
std::string_view diag_value::str () const
Definition at line 112 of file math_parser_diag_value.cpp.
 {
     return _diag_value_at_parse_time<std::string, std::string_view>( data );
 }
References data.
Referenced by anonymous_namespace{math_parser_diag.cpp}::calories_eval(), anonymous_namespace{math_parser_diag.cpp}::effect_intensity_eval(), anonymous_namespace{math_parser_diag.cpp}::pain_eval(), anonymous_namespace{math_parser_diag.cpp}::skill_exp_ass(), anonymous_namespace{math_parser_diag.cpp}::skill_exp_eval(), anonymous_namespace{math_parser_diag.cpp}::spell_count_eval(), and anonymous_namespace{math_parser_diag.cpp}::time_eval().
str() [2/2]
std::string diag_value::str (dialogue const & d) const
Definition at line 117 of file math_parser_diag_value.cpp.
 {
     return std::visit( overloaded{
         []( double v )
         {
             // NOLINTNEXTLINE(cata-translate-string-literal)
             return string_format( "%g", v );
         },
         []( std::string const & v )
         {
             return v;
         },
         [&d]( var_info const & v )
         {
             return read_var_value( v, d );
         },
         [&d]( math_exp const & v )
         {
             // NOLINTNEXTLINE(cata-translate-string-literal)
             return string_format( "%g", v.eval( const_cast<dialogue &>( d ) ) );
         },
         []( diag_array const & )
         {
             debugmsg( R"(Cannot directly convert array to strings)" );
             return std::string{};
         },
     },
     data );
 }
References data, debugmsg, read_var_value(), and string_format().
var()
var_info diag_value::var () const
Definition at line 152 of file math_parser_diag_value.cpp.
 {
     return _diag_value_at_parse_time<var_info>( data );
 }
References data.
Referenced by anonymous_namespace{math_parser_diag.cpp}::_characters_nearby_eval(), and anonymous_namespace{math_parser_diag.cpp}::_monsters_nearby_eval().
Member Data Documentation
data
impl_t diag_value::data
Definition at line 43 of file math_parser_diag_value.h.
Referenced by math_exp::math_exp_impl::_get_diag_value(), array(), dbl(), is_array(), is_dbl(), is_str(), is_var(), operator==(), str(), and var().
The documentation for this struct was generated from the following files:
src/math_parser_diag_value.h
src/math_parser_diag_value.cpp