Cataclysm DDA: weakpoint_families Struct Reference
weakpoint_families Struct Reference
#include <weakpoint.h>
Public Member Functions
bool practice (Character &learner, const time_duration &amount) const
bool practice_hit (Character &learner) const
bool practice_kill (Character &learner) const
bool practice_dissect (Character &learner) const
float modifier (const Character &attacker) const
void clear ()
void load (const JsonArray &ja)
void remove (const JsonArray &ja)
Public Attributes
std::vector< weakpoint_family > families
Detailed Description
Definition at line 104 of file weakpoint.h.
Member Function Documentation
clear()
void weakpoint_families::clear ()
Definition at line 174 of file weakpoint.cpp.
 {
     families.clear();
 }
References families.
Referenced by mtype::load().
load()
void weakpoint_families::load (const JsonArray & ja)
Definition at line 179 of file weakpoint.cpp.
 {
     for( const JsonValue jsin : ja ) {
         weakpoint_family tmp;
         tmp.load( jsin );
         auto it = std::find_if( families.begin(), families.end(),
         [&]( const weakpoint_family & wf ) {
             return wf.id == tmp.id;
         } );
         if( it != families.end() ) {
             families.erase( it );
         }
         families.push_back( std::move( tmp ) );
     }
 }
References families, and weakpoint_family::load().
Referenced by mtype::load().
modifier()
float weakpoint_families::modifier (const Character & attacker) const
Definition at line 165 of file weakpoint.cpp.
 {
     float total = 0.0f;
     for( const weakpoint_family &family : families ) {
         total += family.modifier( attacker );
     }
     return total;
 }
References families.
Referenced by weakpoint_attack::compute_wp_skill().
practice()
bool weakpoint_families::practice (Character & learner, const time_duration & amount) const
Definition at line 127 of file weakpoint.cpp.
 {
     bool learned = false;
     for( const weakpoint_family &family : families ) {
         float before = learner.get_proficiency_practice( family.proficiency );
         learner.practice_proficiency( family.proficiency, amount );
         float after = learner.get_proficiency_practice( family.proficiency );
         if( before < after ) {
             learned = true;
         }
     }
     return learned;
 }
References families, Character::get_proficiency_practice(), and Character::practice_proficiency().
Referenced by practice_dissect(), practice_hit(), and practice_kill().
practice_dissect()
bool weakpoint_families::practice_dissect (Character & learner) const
Definition at line 151 of file weakpoint.cpp.
 {
     // Proficiency experience is capped at 1000 seconds (~16 minutes), so we split it into two
     // instances. This should be refactored when butchering becomes an `activity_actor`.
     bool p1 = practice( learner, time_duration::from_minutes( 15 ) );
     bool p2 = practice( learner, time_duration::from_minutes( 15 ) );
     bool learned = p1 || p2;
     if( learned ) {
         learner.add_msg_if_player(
             m_good, _( "You carefully record the creature's vulnerabilities." ) );
     }
     return learned;
 }
References _, Character::add_msg_if_player(), time_duration::from_minutes(), m_good, and practice().
Referenced by butchery_drops_harvest().
practice_hit()
bool weakpoint_families::practice_hit (Character & learner) const
Definition at line 141 of file weakpoint.cpp.
 {
     return practice( learner, time_duration::from_seconds( 2 ) );
 }
References time_duration::from_seconds(), and practice().
Referenced by monster::on_hit().
practice_kill()
bool weakpoint_families::practice_kill (Character & learner) const
Definition at line 146 of file weakpoint.cpp.
 {
     return practice( learner, time_duration::from_minutes( 1 ) );
 }
References time_duration::from_minutes(), and practice().
Referenced by kill_tracker::notify().
remove()
void weakpoint_families::remove (const JsonArray & ja)
Definition at line 197 of file weakpoint.cpp.
 {
     for( const JsonValue jsin : ja ) {
         weakpoint_family tmp;
         tmp.load( jsin );
         auto it = std::find_if( families.begin(), families.end(),
         [&]( const weakpoint_family & wf ) {
             return wf.id == tmp.id;
         } );
         if( it != families.end() ) {
             families.erase( it );
         }
     }
 }
References families, and weakpoint_family::load().
Referenced by mtype::load().
Member Data Documentation
families
std::vector<weakpoint_family> weakpoint_families::families
Definition at line 106 of file weakpoint.h.
Referenced by butcher_submenu(), clear(), load(), modifier(), practice(), and remove().
The documentation for this struct was generated from the following files:
src/weakpoint.h
src/weakpoint.cpp