Cataclysm DDA: construction_group Struct Reference
construction_group Struct Reference
#include <construction_group.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
std::string name () const
Static Public Member Functions
static size_t count ()
Public Attributes
construction_group_str_id id
std::vector< std::pair< construction_group_str_id, mod_id > > src
bool was_loaded = false
Private Attributes
translation _name
Detailed Description
Definition at line 16 of file construction_group.h.
Member Function Documentation
count()
size_t construction_group::count () static
Definition at line 66 of file construction_group.cpp.
 {
     return all_construction_groups.size();
 }
References anonymous_namespace{construction_group.cpp}::all_construction_groups.
load()
void construction_group::load (const JsonObject & jo, std::string_view src)
Definition at line 56 of file construction_group.cpp.
 {
     mandatory( jo, was_loaded, "name", _name );
 }
References _name, mandatory, and was_loaded.
name()
std::string construction_group::name () const
Definition at line 61 of file construction_group.cpp.
 {
     return _name.translated();
 }
References _name, and translation::translated().
Referenced by complete_construction(), blueprint_options::get_descriptions(), blueprint_options::get_zone_name_suggestion(), iexamine::part_con(), and game::print_part_con_info().
Member Data Documentation
_name
translation construction_group::_name private
Definition at line 28 of file construction_group.h.
Referenced by load(), and name().
id
construction_group_str_id construction_group::id
Definition at line 19 of file construction_group.h.
src
std::vector<std::pair<construction_group_str_id, mod_id> > construction_group::src
Definition at line 20 of file construction_group.h.
was_loaded
bool construction_group::was_loaded = false
Definition at line 21 of file construction_group.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/construction_group.h
src/construction_group.cpp