Cataclysm DDA: bionic Struct Reference
bionic Struct Reference
#include <bionics.h>
Public Types
using bionic_uid = unsigned int
Public Member Functions
bionic ()
bionic (bionic_id pid, char pinvlet, bionic_uid pbionic_uid, bionic_uid pparent_uid=0)
const bionic_data & info () const
void set_flag (const std::string &flag)
void remove_flag (const std::string &flag)
bool has_flag (const std::string &flag) const
int get_quality (const quality_id &quality) const
item get_weapon () const
void set_weapon (const item &new_weapon)
bool install_weapon (const item &new_weapon, bool skip_checks=false)
std::optional< item > uninstall_weapon ()
bool has_weapon () const
bool can_install_weapon () const
bool can_install_weapon (const item &new_weapon) const
unsigned int get_uid () const
void set_uid (bionic_uid new_uid)
bool is_included () const
bionic_uid get_parent_uid () const
void set_parent_uid (bionic_uid new_uid)
std::vector< const item * > get_available_pseudo_items (bool include_weapon=true) const
bool is_this_fuel_powered (const material_id &this_fuel) const
void toggle_safe_fuel_mod ()
void set_safe_fuel_thresh (float val)
float get_safe_fuel_thresh () const
bool is_safe_fuel_on () const
bool activate_spell (Character &caster) const
void serialize (JsonOut &json) const
void deserialize (const JsonObject &jo)
Public Attributes
bionic_id id
time_duration charge_timer = 0_turns
char invlet = 'a'
bool powered = false
bool show_sprite = true
time_duration incapacitated_time
Private Member Functions
void initialize_pseudo_items (bool create_weapon=false)
void update_weapon_flags ()
Private Attributes
cata::flat_set< std::string > bionic_tags
float safe_fuel_threshold = 1.0f
item weapon
std::vector< item > toggled_pseudo_items
std::vector< item > passive_pseudo_items
bionic_uid uid
bionic_uid parent_uid
Detailed Description
Definition at line 198 of file bionics.h.
Member Typedef Documentation
bionic_uid
using bionic::bionic_uid = unsigned int
Definition at line 200 of file bionics.h.
Constructor & Destructor Documentation
bionic() [1/2]
bionic::bionic () inline
Definition at line 210 of file bionics.h.
 : bionic( bionic_id( "bio_batteries" ), 'a', 0 ) { }
bionic() [2/2]
bionic::bionic (bionic_id pid, char pinvlet, bionic_uid pbionic_uid, bionic_uid pparent_uid = 0) inline
Definition at line 211 of file bionics.h.
                                              : id( pid ), invlet( pinvlet ),
             incapacitated_time( 0_turns ), uid( pbionic_uid ), parent_uid( pparent_uid ) {
             initialize_pseudo_items( true );
         }
References initialize_pseudo_items().
Member Function Documentation
activate_spell()
bool bionic::activate_spell (Character & caster) const
Definition at line 1832 of file handle_action.cpp.
 {
     if( !caster.is_avatar() || !id->spell_on_activate ) {
         // the return value tells us if the spell fails. if it has no spell it can't fail
         return true;
     }
     spell sp = id->spell_on_activate->get_spell( caster );
     return caster.cast_spell( sp, true );
 }
References Character::cast_spell(), id, Creature::is_avatar(), and bionic_data::spell_on_activate.
Referenced by Character::activate_bionic().
can_install_weapon() [1/2]
bool bionic::can_install_weapon () const
Definition at line 2936 of file bionics.cpp.
 {
     return !id->installable_weapon_flags.empty();
 }
Referenced by install_weapon(), and avatar::power_bionics().
can_install_weapon() [2/2]
bool bionic::can_install_weapon (const item & new_weapon) const
Definition at line 2941 of file bionics.cpp.
 {
     return !id->installable_weapon_flags.empty() &&
            new_weapon.has_any_flag( id->installable_weapon_flags );
 }
References item::has_any_flag(), id, and bionic_data::installable_weapon_flags.
deserialize()
void bionic::deserialize (const JsonObject & jo)
Definition at line 3139 of file bionics.cpp.
 {
     id = migrate_bionic_id( bionic_id( jo.get_string( "id" ) ) );
     if( !id.is_valid() ) {
         debugmsg( "deserialized bionic id '%s' doesn't exist and has no migration", id.str() );
         id = bionic_id::NULL_ID(); // remove it
     }
     if( id.is_null() ) {
         jo.allow_omitted_members();
         return; // obsoleted bionics migrated to bionic_id::NULL_ID ids
     }
     invlet = jo.get_int( "invlet" );
     powered = jo.get_bool( "powered" );
     //Remove After 0.G
     if( jo.has_int( "charge" ) ) {
         charge_timer = time_duration::from_turns( jo.get_int( "charge" ) );
     } else {
         jo.read( "charge_timer", charge_timer );
     }
     if( jo.has_int( "incapacitated_time" ) ) {
         incapacitated_time = 1_turns * jo.get_int( "incapacitated_time" );
     }
     if( jo.has_float( "safe_fuel_threshold" ) ) {
         safe_fuel_threshold = jo.get_float( "safe_fuel_threshold" );
     }
     if( jo.has_bool( "show_sprite" ) ) {
         show_sprite = jo.get_bool( "show_sprite" );
     }
     if( jo.has_array( "bionic_tags" ) ) {
         for( const std::string line : jo.get_array( "bionic_tags" ) ) {
             bionic_tags.insert( line );
         }
     }
     if( jo.has_int( "bionic_uid" ) ) {
         uid = jo.get_int( "bionic_uid" );
     }
     if( jo.has_int( "parent_uid" ) ) {
         parent_uid = jo.get_int( "parent_uid" );
     }
     if( jo.has_member( "weapon" ) ) {
         jo.read( "weapon", weapon, true );
     }
     // Suppress errors when loading old games
     // TODO: add old ammo to new weapon?
     if( jo.has_string( "ammo_loaded" ) ) {
         jo.get_string( "ammo_loaded" );
     }
     if( jo.has_int( "ammo_count" ) ) {
         jo.get_int( "ammo_count" );
     }
     initialize_pseudo_items();
 }
References JsonObject::allow_omitted_members(), bionic_id, bionic_tags, charge_timer, debugmsg, time_duration::from_turns(), JsonObject::get_array(), JsonObject::get_bool(), JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_bool(), JsonObject::has_float(), JsonObject::has_int(), JsonObject::has_member(), JsonObject::has_string(), incapacitated_time, initialize_pseudo_items(), cata::flat_set< T, Compare, Data >::insert(), invlet, line, migrate_bionic_id(), string_id< bionic_data >::NULL_ID(), parent_uid, powered, JsonObject::read(), safe_fuel_threshold, show_sprite, uid, and weapon.
get_available_pseudo_items()
std::vector< const item * > bionic::get_available_pseudo_items (bool include_weapon = true) const
Definition at line 3009 of file bionics.cpp.
 {
     std::vector<const item *> ret;
     ret.reserve( passive_pseudo_items.size() );
     for( const item &pseudo : passive_pseudo_items ) {
         ret.push_back( &pseudo );
     }
     if( powered && info().has_flag( flag_BIONIC_TOGGLED ) ) {
         for( const item &pseudo : toggled_pseudo_items ) {
             ret.push_back( &pseudo );
         }
         if( include_weapon && has_weapon() ) {
             ret.push_back( &weapon );
         }
     }
     return ret;
 }
References flag_BIONIC_TOGGLED, has_flag(), has_weapon(), info(), passive_pseudo_items, powered, cata::hash64_detail::ret, toggled_pseudo_items, and weapon.
get_parent_uid()
bionic_uid bionic::get_parent_uid () const
Definition at line 3478 of file bionics.cpp.
 {
     return parent_uid;
 }
References parent_uid.
Referenced by monster::nursebot_operate().
get_quality()
int bionic::get_quality (const quality_id & quality) const
Definition at line 2922 of file bionics.cpp.
 {
     if( weapon.typeId().is_empty() ) {
         return INT_MIN;
     }
     return weapon.get_quality( quality );
 }
References item::get_quality(), string_id< T >::is_empty(), item::typeId(), and weapon.
get_safe_fuel_thresh()
float bionic::get_safe_fuel_thresh () const
Definition at line 3078 of file bionics.cpp.
 {
     return safe_fuel_threshold;
 }
References safe_fuel_threshold.
Referenced by build_bionic_poweronly_string(), Character::burn_fuel(), and is_safe_fuel_on().
get_uid()
bionic_uid bionic::get_uid () const
Definition at line 3463 of file bionics.cpp.
 {
     return uid;
 }
References uid.
Referenced by Character::activate_bionic(), npc::check_or_use_weapon_cbm(), Character::deactivate_bionic(), Character::perform_uninstall(), Character::process_bionic(), Character::remove_bionic(), and Character::uninstall_bionic().
get_weapon()
item bionic::get_weapon () const
Definition at line 2947 of file bionics.cpp.
 {
     return weapon;
 }
References weapon.
Referenced by Character::activate_bionic(), build_bionic_poweronly_string(), npc::check_or_use_weapon_cbm(), draw_description(), Character::handle_melee_wear(), avatar::power_bionics(), Character::process_bionic(), and uninstall_weapon().
has_flag()
bool bionic::has_flag (const std::string & flag) const
Definition at line 2917 of file bionics.cpp.
 {
     return bionic_tags.find( flag ) != bionic_tags.end();
 }
References bionic_tags, cata::flat_set< T, Compare, Data >::end(), and cata::flat_set< T, Compare, Data >::find().
Referenced by get_available_pseudo_items().
has_weapon()
bool bionic::has_weapon () const
Definition at line 2931 of file bionics.cpp.
 {
     return !weapon.typeId().is_empty() && !weapon.typeId().is_null();
 }
References string_id< T >::is_empty(), string_id< T >::is_null(), item::typeId(), and weapon.
Referenced by Character::activate_bionic(), npc::check_or_use_weapon_cbm(), Character::deactivate_bionic(), draw_description(), get_available_pseudo_items(), install_weapon(), avatar::power_bionics(), serialize(), uninstall_weapon(), and update_weapon_flags().
info()
const bionic_data& bionic::info () const inline
Definition at line 217 of file bionics.h.
{
             return *id;
         }
References id.
Referenced by Character::activate_bionic(), attempt_recharge(), Character::bionic_fuel_check(), Character::burn_fuel(), Character::can_deactivate_bionic(), npc::check_or_use_weapon_cbm(), Character::deactivate_bionic(), npc::deactivate_or_discharge_bionic_weapon(), get_available_pseudo_items(), Character::get_effective_efficiency(), Character::heat_emission(), initialize_pseudo_items(), is_safe_fuel_on(), is_this_fuel_powered(), anonymous_namespace{bionics_ui.cpp}::bionic_sort_less::operator()(), avatar::power_bionics(), Character::process_bionic(), sleep(), toggle_safe_fuel_mod(), and Character::uninstall_bionic().
initialize_pseudo_items()
void bionic::initialize_pseudo_items (bool create_weapon = false) private
Definition at line 192 of file bionics.cpp.
 {
     bionic_data bid( info() );
     bool inherit_use_bionic_power = bid.has_flag( flag_USES_BIONIC_POWER );
     toggled_pseudo_items.clear();
     passive_pseudo_items.clear();
     if( bid.has_flag( json_flag_BIONIC_GUN ) || bid.has_flag( json_flag_BIONIC_WEAPON ) ) {
         if( create_weapon && !id->fake_weapon.is_empty() && id->fake_weapon.is_valid() ) {
             item new_weapon = item( id->fake_weapon );
             install_weapon( new_weapon, true );
         } else {
             update_weapon_flags();
         }
     } else if( bid.has_flag( json_flag_BIONIC_TOGGLED ) ) {
         for( const itype_id &id : bid.toggled_pseudo_items ) {
             if( !id.is_empty() && id.is_valid() ) {
                 toggled_pseudo_items.emplace_back( id );
             }
         }
     }
     //integrated armor uses pseudo item structure to be convenient but these should be visible in inventory
     for( const itype_id &id : bid.passive_pseudo_items ) {
         if( !id.is_empty() && id.is_valid() ) {
             item pseudo( id );
             if( !pseudo.has_flag( flag_INTEGRATED ) ) {
                 pseudo.set_flag( flag_PSEUDO );
             }
             passive_pseudo_items.emplace_back( pseudo );
         }
     }
     if( inherit_use_bionic_power ) {
         for( item &pseudo : passive_pseudo_items ) {
             pseudo.set_flag( flag_USES_BIONIC_POWER );
         }
         for( item &pseudo : toggled_pseudo_items ) {
             pseudo.set_flag( flag_USES_BIONIC_POWER );
         }
     }
 }
References bionic_data::fake_weapon, flag_INTEGRATED, flag_PSEUDO, flag_USES_BIONIC_POWER, item::has_flag(), bionic_data::has_flag(), id, info(), install_weapon(), string_id< T >::is_empty(), string_id< T >::is_valid(), item, json_flag_BIONIC_GUN, json_flag_BIONIC_TOGGLED, json_flag_BIONIC_WEAPON, bionic_data::passive_pseudo_items, passive_pseudo_items, item::set_flag(), bionic_data::toggled_pseudo_items, toggled_pseudo_items, and update_weapon_flags().
Referenced by bionic(), and deserialize().
install_weapon()
bool bionic::install_weapon (const item & new_weapon, bool skip_checks = false)
Definition at line 2958 of file bionics.cpp.
 {
     if( powered ) {
         debugmsg( "Tried to install a weapon on powered bionic \"%s\" with UID %i.",
                   id.str(), uid );
         return false;
     }
     if( !skip_checks ) {
         if( !can_install_weapon( new_weapon ) ) {
             debugmsg( "Tried to install a weapon with incompatible flags on bionic \"%s\" with UID %i.",
                       id.str(), uid );
             return false;
         }
         if( has_weapon() ) {
             debugmsg( "Tried to install a weapon on bionic \"%s\" with UID %i that already has a weapon installed.",
                       id.str(), uid );
             return false;
         }
     }
     set_weapon( new_weapon );
     return true;
 }
References can_install_weapon(), debugmsg, has_weapon(), powered, set_weapon(), and uid.
Referenced by initialize_pseudo_items(), and avatar::power_bionics().
is_included()
bool bionic::is_included () const
Definition at line 3473 of file bionics.cpp.
 {
     return !!parent_uid;
 }
References parent_uid.
Referenced by Character::can_uninstall_bionic(), and monster::nursebot_operate().
is_safe_fuel_on()
bool bionic::is_safe_fuel_on () const
Definition at line 3083 of file bionics.cpp.
 {
     return info().has_flag( json_flag_BIONIC_POWER_SOURCE ) && get_safe_fuel_thresh() > -1.f;
 }
References get_safe_fuel_thresh(), bionic_data::has_flag(), info(), and json_flag_BIONIC_POWER_SOURCE.
Referenced by build_bionic_poweronly_string(), Character::burn_fuel(), and serialize().
is_this_fuel_powered()
bool bionic::is_this_fuel_powered (const material_id & this_fuel) const
Definition at line 3030 of file bionics.cpp.
 {
     const std::vector<material_id> fuel_op = info().fuel_opts;
     return std::find( fuel_op.begin(), fuel_op.end(), this_fuel ) != fuel_op.end();
 }
References bionic_data::fuel_opts, and info().
remove_flag()
void bionic::remove_flag (const std::string & flag)
Definition at line 2912 of file bionics.cpp.
 {
     bionic_tags.erase( flag );
 }
References bionic_tags, and cata::flat_set< T, Compare, Data >::erase().
serialize()
void bionic::serialize (JsonOut & json) const
Definition at line 3093 of file bionics.cpp.
 {
     json.start_object();
     json.member( "id", id );
     json.member( "invlet", static_cast<int>( invlet ) );
     json.member( "powered", powered );
     json.member( "charge", charge_timer );
     json.member( "bionic_tags", bionic_tags );
     json.member( "bionic_uid", uid );
     json.member( "parent_uid", parent_uid );
     if( incapacitated_time > 0_turns ) {
         json.member( "incapacitated_time", incapacitated_time );
     }
     if( is_safe_fuel_on() ) {
         json.member( "safe_fuel_threshold", safe_fuel_threshold );
     }
     json.member( "show_sprite", show_sprite );
     if( has_weapon() ) {
         json.member( "weapon", weapon );
     }
     json.end_object();
 }
References bionic_tags, charge_timer, JsonOut::end_object(), has_weapon(), incapacitated_time, invlet, is_safe_fuel_on(), JsonOut::member(), parent_uid, powered, safe_fuel_threshold, show_sprite, JsonOut::start_object(), uid, and weapon.
set_flag()
void bionic::set_flag (const std::string & flag)
Definition at line 2907 of file bionics.cpp.
 {
     bionic_tags.insert( flag );
 }
References bionic_tags, and cata::flat_set< T, Compare, Data >::insert().
set_parent_uid()
void bionic::set_parent_uid (bionic_uid new_uid)
Definition at line 3483 of file bionics.cpp.
 {
     parent_uid = new_uid;
 }
References parent_uid.
set_safe_fuel_thresh()
void bionic::set_safe_fuel_thresh (float val)
Definition at line 3088 of file bionics.cpp.
 {
     safe_fuel_threshold = val;
 }
References safe_fuel_threshold.
Referenced by toggle_safe_fuel_mod().
set_uid()
void bionic::set_uid (bionic_uid new_uid)
Definition at line 3468 of file bionics.cpp.
 {
     uid = new_uid;
 }
References uid.
set_weapon()
void bionic::set_weapon (const item & new_weapon)
Definition at line 2952 of file bionics.cpp.
 {
     weapon = new_weapon;
     update_weapon_flags();
 }
References update_weapon_flags(), and weapon.
Referenced by Character::deactivate_bionic(), Character::handle_melee_wear(), and install_weapon().
toggle_safe_fuel_mod()
void bionic::toggle_safe_fuel_mod ()
Definition at line 3036 of file bionics.cpp.
 {
     if( !info().fuel_opts.empty() || info().is_remote_fueled ) {
         uilist tmenu;
         tmenu.text = _( "Stop power generation at" );
         tmenu.addentry( 1, true, '1', _( "100 %%" ) );
         tmenu.addentry( 2, true, '2', _( "90 %%" ) );
         tmenu.addentry( 3, true, '3', _( "70 %%" ) );
         tmenu.addentry( 4, true, '4', _( "50 %%" ) );
         tmenu.addentry( 5, true, '5', _( "30 %%" ) );
         tmenu.addentry( 6, true, '6', _( "10 %%" ) );
         tmenu.addentry( 7, true, 'd', _( "Disabled" ) );
         tmenu.query();
         switch( tmenu.ret ) {
             case 1:
                 set_safe_fuel_thresh( 1.0f );
                 break;
             case 2:
                 set_safe_fuel_thresh( 0.90f );
                 break;
             case 3:
                 set_safe_fuel_thresh( 0.70f );
                 break;
             case 4:
                 set_safe_fuel_thresh( 0.50f );
                 break;
             case 5:
                 set_safe_fuel_thresh( 0.30f );
                 break;
             case 6:
                 set_safe_fuel_thresh( 0.10f );
                 break;
             case 7:
                 set_safe_fuel_thresh( -1.0f );
                 break;
             default:
                 break;
         }
     }
 }
References _, uilist::addentry(), info(), uilist::query(), uilist::ret, set_safe_fuel_thresh(), and uilist::text.
Referenced by avatar::power_bionics().
uninstall_weapon()
std::optional< item > bionic::uninstall_weapon ()
Definition at line 2985 of file bionics.cpp.
 {
     if( !has_weapon() ) {
         debugmsg( "Tried to uninstall a weapon on bionic \"%s\" with UID %i that doesn't have a weapon installed.",
                   id.str(), uid );
         return std::nullopt;
     }
     if( id->installable_weapon_flags.empty() ) {
         debugmsg( "Tried to uinstall a weapon from non-dynamic bionic \"%s\" with UID %i.", id.str(),
                   uid );
         return std::nullopt;
     }
     std::optional<item> old_item = get_weapon();
     weapon = item();
     if( old_item && !old_item->is_null() ) {
         old_item->unset_flag( flag_USES_BIONIC_POWER );
         old_item->unset_flag( flag_NO_UNWIELD );
     }
     return old_item;
 }
References debugmsg, flag_NO_UNWIELD, flag_USES_BIONIC_POWER, get_weapon(), has_weapon(), id, bionic_data::installable_weapon_flags, item, uid, and weapon.
Referenced by avatar::power_bionics().
update_weapon_flags()
void bionic::update_weapon_flags () private
Definition at line 236 of file bionics.cpp.
 {
     if( has_weapon() ) {
         if( id->has_flag( flag_USES_BIONIC_POWER ) ) {
             weapon.set_flag( flag_USES_BIONIC_POWER );
         }
         weapon.set_flag( flag_NO_UNWIELD );
     }
 }
References flag_NO_UNWIELD, flag_USES_BIONIC_POWER, bionic_data::has_flag(), has_weapon(), id, item::set_flag(), and weapon.
Referenced by initialize_pseudo_items(), and set_weapon().
Member Data Documentation
bionic_tags
cata::flat_set<std::string> bionic::bionic_tags private
Definition at line 253 of file bionics.h.
Referenced by deserialize(), has_flag(), remove_flag(), serialize(), and set_flag().
charge_timer
time_duration bionic::charge_timer = 0_turns
Definition at line 203 of file bionics.h.
Referenced by Character::activate_bionic(), attempt_recharge(), deserialize(), Character::process_bionic(), and serialize().
id
bionic_id bionic::id
Definition at line 202 of file bionics.h.
Referenced by Character::activate_bionic(), activate_spell(), Character::add_bionic(), Character::bionic_fuel_check(), build_bionic_powerdesc_string(), build_bionic_poweronly_string(), Character::burn_fuel(), can_install_weapon(), Character::can_uninstall_bionic(), Character::deactivate_bionic(), debug_menu::debug(), draw_bionics_titlebar(), draw_description(), get_bionic_text_color(), info(), initialize_pseudo_items(), Character::perform_uninstall(), character_martial_arts::pick_style(), avatar::power_bionics(), Character::process_bionic(), Character::remove_bionic(), Character::uninstall_bionic(), uninstall_weapon(), update_weapon_flags(), and debug_menu::wishbionics().
incapacitated_time
time_duration bionic::incapacitated_time
Definition at line 208 of file bionics.h.
Referenced by Character::activate_bionic(), build_bionic_poweronly_string(), Character::can_deactivate_bionic(), deserialize(), Character::force_bionic_deactivation(), and serialize().
invlet
char bionic::invlet = 'a'
Definition at line 204 of file bionics.h.
Referenced by deserialize(), anonymous_namespace{bionics_ui.cpp}::bionic_sort_less::operator()(), avatar::power_bionics(), and serialize().
parent_uid
bionic_uid bionic::parent_uid private
Definition at line 259 of file bionics.h.
Referenced by deserialize(), get_parent_uid(), is_included(), serialize(), and set_parent_uid().
passive_pseudo_items
std::vector<item> bionic::passive_pseudo_items private
Definition at line 257 of file bionics.h.
Referenced by get_available_pseudo_items(), and initialize_pseudo_items().
powered
bool bionic::powered = false
Definition at line 205 of file bionics.h.
Referenced by Character::activate_bionic(), Character::bionic_fuel_check(), build_bionic_poweronly_string(), Character::burn_fuel(), Character::can_deactivate_bionic(), npc::check_or_use_weapon_cbm(), Character::deactivate_bionic(), npc::deactivate_or_discharge_bionic_weapon(), deserialize(), Character::force_bionic_deactivation(), get_available_pseudo_items(), get_bionic_text_color(), install_weapon(), avatar::power_bionics(), Character::process_bionic(), serialize(), sleep(), and Character::uninstall_bionic().
safe_fuel_threshold
float bionic::safe_fuel_threshold = 1.0f private
Definition at line 254 of file bionics.h.
Referenced by deserialize(), get_safe_fuel_thresh(), serialize(), and set_safe_fuel_thresh().
show_sprite
bool bionic::show_sprite = true
Definition at line 206 of file bionics.h.
Referenced by build_bionic_poweronly_string(), deserialize(), avatar::power_bionics(), and serialize().
toggled_pseudo_items
std::vector<item> bionic::toggled_pseudo_items private
Definition at line 256 of file bionics.h.
Referenced by get_available_pseudo_items(), and initialize_pseudo_items().
uid
bionic_uid bionic::uid private
Definition at line 258 of file bionics.h.
Referenced by deserialize(), get_uid(), install_weapon(), serialize(), set_uid(), and uninstall_weapon().
weapon
item bionic::weapon private
Definition at line 255 of file bionics.h.
Referenced by deserialize(), get_available_pseudo_items(), get_quality(), get_weapon(), has_weapon(), serialize(), set_weapon(), uninstall_weapon(), and update_weapon_flags().
The documentation for this struct was generated from the following files:
src/bionics.h
src/bionics.cpp
src/handle_action.cpp