Cataclysm DDA: smart_controller_config Struct Reference
smart_controller_config Struct Reference
#include <vehicle.h>
Public Member Functions
void deserialize (const JsonObject &data)
void serialize (JsonOut &json) const
Public Attributes
int battery_lo = 25
int battery_hi = 90
Detailed Description
Definition at line 130 of file vehicle.h.
Member Function Documentation
deserialize()
void smart_controller_config::deserialize (const JsonObject & data)
Definition at line 3344 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     data.read( "bat_lo", battery_lo );
     data.read( "bat_hi", battery_hi );
 }
References item_pocket::data.
serialize()
void smart_controller_config::serialize (JsonOut & json) const
Definition at line 3351 of file savegame_json.cpp.
 {
     json.start_object();
     json.member( "bat_lo", battery_lo );
     json.member( "bat_hi", battery_hi );
     json.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
Member Data Documentation
battery_hi
int smart_controller_config::battery_hi = 90
Definition at line 132 of file vehicle.h.
Referenced by vehicle::smart_controller_handle_turn().
battery_lo
int smart_controller_config::battery_lo = 25
Definition at line 131 of file vehicle.h.
Referenced by vehicle::smart_controller_handle_turn().
The documentation for this struct was generated from the following files:
src/vehicle.h
src/savegame_json.cpp