Cataclysm DDA: limb_score Struct Reference
limb_score Struct Reference
#include <bodypart.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
const limb_score_id & getId () const
const translation & name () const
bool affected_by_wounds () const
bool affected_by_encumb () const
Static Public Member Functions
static void load_limb_scores (const JsonObject &jo, const std::string &src)
static void reset ()
static const std::vector< limb_score > & get_all ()
Private Attributes
limb_score_id id
std::vector< std::pair< limb_score_id, mod_id > > src
translation _name
bool wound_affect = true
bool encumb_affect = true
bool was_loaded = false
Friends
class generic_factory< limb_score >
struct mod_tracker
Detailed Description
Definition at line 107 of file bodypart.h.
Member Function Documentation
affected_by_encumb()
bool limb_score::affected_by_encumb () const inline
Definition at line 123 of file bodypart.h.
{
             return encumb_affect;
         }
References encumb_affect.
affected_by_wounds()
bool limb_score::affected_by_wounds () const inline
Definition at line 120 of file bodypart.h.
{
             return wound_affect;
         }
References wound_affect.
get_all()
const std::vector< limb_score > & limb_score::get_all () static
Definition at line 158 of file bodypart.cpp.
 {
     return limb_score_factory.get_all();
 }
References anonymous_namespace{bodypart.cpp}::limb_score_factory.
Referenced by draw_health_summary(), and get_encumbrance_description().
getId()
const limb_score_id& limb_score::getId () const inline
Definition at line 114 of file bodypart.h.
{
             return id;
         }
References id.
load()
void limb_score::load (const JsonObject & jo, std::string_view src)
Definition at line 163 of file bodypart.cpp.
 {
     mandatory( jo, was_loaded, "id", id );
     mandatory( jo, was_loaded, "name", _name );
     optional( jo, was_loaded, "affected_by_wounds", wound_affect, true );
     optional( jo, was_loaded, "affected_by_encumb", encumb_affect, true );
 }
References _name, encumb_affect, mandatory, optional(), was_loaded, and wound_affect.
load_limb_scores()
void limb_score::load_limb_scores (const JsonObject & jo, const std::string & src) static
Definition at line 148 of file bodypart.cpp.
 {
     limb_score_factory.load( jo, src );
 }
References anonymous_namespace{bodypart.cpp}::limb_score_factory, and src.
Referenced by DynamicDataLoader::initialize().
name()
const translation& limb_score::name () const inline
Definition at line 117 of file bodypart.h.
{
             return _name;
         }
References _name.
reset()
void limb_score::reset () static
Definition at line 153 of file bodypart.cpp.
 {
     limb_score_factory.reset();
 }
References anonymous_namespace{bodypart.cpp}::limb_score_factory.
Referenced by DynamicDataLoader::unload_data().
Friends And Related Function Documentation
generic_factory< limb_score >
friend class generic_factory< limb_score > friend
Definition at line 132 of file bodypart.h.
mod_tracker
friend struct mod_tracker friend
Definition at line 134 of file bodypart.h.
Member Data Documentation
_name
translation limb_score::_name private
Definition at line 129 of file bodypart.h.
Referenced by load(), and name().
encumb_affect
bool limb_score::encumb_affect = true private
Definition at line 131 of file bodypart.h.
Referenced by affected_by_encumb(), and load().
id
limb_score_id limb_score::id private
Definition at line 127 of file bodypart.h.
Referenced by getId().
src
std::vector<std::pair<limb_score_id, mod_id> > limb_score::src private
Definition at line 128 of file bodypart.h.
Referenced by load_limb_scores().
was_loaded
bool limb_score::was_loaded = false private
Definition at line 132 of file bodypart.h.
Referenced by load().
wound_affect
bool limb_score::wound_affect = true private
Definition at line 130 of file bodypart.h.
Referenced by affected_by_wounds(), and load().
The documentation for this struct was generated from the following files:
src/bodypart.h
src/bodypart.cpp