Cataclysm DDA: VehiclePlacement Struct Reference
VehiclePlacement Struct Reference
A list of vehicle locations which are valid for spawning new vehicles.
#include <vehicle_group.h>
Public Types
using LocationMap = std::vector< VehicleLocation >
Public Member Functions
VehiclePlacement ()=default
void add (const jmapgen_int &x, const jmapgen_int &y, const VehicleFacings &facings)
const VehicleLocation * pick () const
Static Public Member Functions
static void load (const JsonObject &jo)
static void reset ()
Public Attributes
LocationMap locations
Detailed Description
A list of vehicle locations which are valid for spawning new vehicles.
Definition at line 84 of file vehicle_group.h.
Member Typedef Documentation
LocationMap
using VehiclePlacement::LocationMap = std::vector<VehicleLocation>
Definition at line 95 of file vehicle_group.h.
Constructor & Destructor Documentation
VehiclePlacement()
VehiclePlacement::VehiclePlacement () default
Member Function Documentation
add()
void VehiclePlacement::add (const jmapgen_int & x, const jmapgen_int & y, const VehicleFacings & facings) inline
Definition at line 87 of file vehicle_group.h.
{
         locations.emplace_back( x, y, facings );
     }
References locations.
Referenced by load().
load()
void VehiclePlacement::load (const JsonObject & jo) static
Definition at line 105 of file vehicle_group.cpp.
 {
     VehiclePlacement &placement = vplacements[vplacement_id( jo.get_string( "id" ) )];
     for( JsonObject jloc : jo.get_array( "locations" ) ) {
         placement.add( jmapgen_int( jloc, "x" ), jmapgen_int( jloc, "y" ),
                        VehicleFacings( jloc, "facing" ) );
     }
 }
References add(), JsonObject::get_array(), JsonObject::get_string(), and vplacements.
Referenced by DynamicDataLoader::initialize().
pick()
const VehicleLocation * VehiclePlacement::pick () const
Definition at line 120 of file vehicle_group.cpp.
 {
     if( const auto chosen = random_entry_opt( locations ) ) {
         return &chosen->get();
     }
     debugmsg( "vehicleplacement has no locations" );
     return nullptr;
 }
References debugmsg, locations, and random_entry_opt().
reset()
void VehiclePlacement::reset () static
Definition at line 115 of file vehicle_group.cpp.
 {
     vplacements.clear();
 }
References vplacements.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
locations
LocationMap VehiclePlacement::locations
Definition at line 96 of file vehicle_group.h.
Referenced by add(), and pick().
The documentation for this struct was generated from the following files:
src/vehicle_group.h
src/vehicle_group.cpp