Cataclysm DDA: nutrients Struct Reference
nutrients Struct Reference
#include <stomach.h>
Public Member Functions
void min_in_place (const nutrients &r)
Replace the values here with the minimum (or maximum) of themselves and the corresponding values taken from r.
void max_in_place (const nutrients &r)
std::map< vitamin_id, int > vitamins () const
void set_vitamin (const vitamin_id &, vitamin_units::mass mass)
void add_vitamin (const vitamin_id &, vitamin_units::mass mass)
void set_vitamin (const vitamin_id &, int units)
void add_vitamin (const vitamin_id &, int units)
void remove_vitamin (const vitamin_id &)
int get_vitamin (const vitamin_id &) const
int kcal () const
void finalize_vitamins ()
bool operator== (const nutrients &r) const
bool operator!= (const nutrients &r) const
nutrients & operator+= (const nutrients &r)
nutrients & operator-= (const nutrients &r)
nutrients & operator*= (int r)
nutrients & operator*= (double r)
nutrients & operator/= (int r)
void serialize (JsonOut &) const
void deserialize (const JsonObject &jo)
Public Attributes
int64_t calories = 0
amount of calories (1/1000s of kcal) this food has
bool finalized = true
Private Attributes
std::map< vitamin_id, std::variant< int, vitamin_units::mass > > vitamins_
vitamins potentially provided by this comestible (if any)
Friends
nutrients operator* (nutrients l, int r)
nutrients operator/ (nutrients l, int r)
Detailed Description
Definition at line 36 of file stomach.h.
Member Function Documentation
add_vitamin() [1/2]
void nutrients::add_vitamin (const vitamin_id & vit, int units)
Definition at line 90 of file stomach.cpp.
 {
     auto iter = vitamins_.emplace( vit, 0 ).first;
     if( std::holds_alternative<vitamin_units::mass>( iter->second ) ) {
         debugmsg( "Tried to add mass vitamin to units vitamin before vitamins were finalized!" );
         return;
     }
     iter->second = std::get<int>( iter->second ) + units;
 }
References debugmsg, and vitamins_.
add_vitamin() [2/2]
void nutrients::add_vitamin (const vitamin_id & vit, vitamin_units::mass mass)
Definition at line 70 of file stomach.cpp.
 {
     if( finalized ) {
         add_vitamin( vit, vit->units_from_mass( mass ) );
         return;
     }
     auto iter = vitamins_.emplace( vit, vitamin_units::mass( 0, {} ) ).first;
     if( !std::holds_alternative<vitamin_units::mass>( iter->second ) ) {
         debugmsg( "Tried to add mass vitamin to units vitamin before vitamins were finalized!" );
         return;
     }
     iter->second = std::get<vitamin_units::mass>( iter->second ) + mass;
 }
References debugmsg, finalized, vitamin::units_from_mass(), and vitamins_.
Referenced by Item_factory::load().
deserialize()
void nutrients::deserialize (const JsonObject & jo)
Definition at line 229 of file stomach.cpp.
 {
     jo.read( "calories", calories );
     std::map<vitamin_id, int> vit_map;
     jo.read( "vitamins", vit_map );
     for( auto &vit : vit_map ) {
         //rebuild vitamins_
         set_vitamin( vit.first, vit.second );
     }
 }
References calories, JsonObject::read(), and set_vitamin().
finalize_vitamins()
void nutrients::finalize_vitamins ()
Definition at line 123 of file stomach.cpp.
 {
     for( std::pair<const vitamin_id, std::variant<int, vitamin_units::mass> > &vit : vitamins_ ) {
         if( std::holds_alternative<vitamin_units::mass>( vit.second ) ) {
             vit.second = vit.first->units_from_mass( std::get<vitamin_units::mass>( vit.second ) );
         }
         if( std::holds_alternative<vitamin_units::mass>( vit.second ) ) {
             debugmsg( "Error occured during vitamin finalization!" );
         }
     }
     finalized = true;
 }
References debugmsg, finalized, and vitamins_.
get_vitamin()
int nutrients::get_vitamin (const vitamin_id & vit) const
Definition at line 105 of file stomach.cpp.
 {
     auto it = vitamins_.find( vit );
     if( it == vitamins_.end() ) {
         return 0;
     }
     if( !finalized && std::holds_alternative<vitamin_units::mass>( it->second ) ) {
         debugmsg( "Called get_vitamin on a mass vitamin before vitamins were finalized!" );
         return 0;
     }
     return std::get<int>( it->second );
 }
References debugmsg, finalized, and vitamins_.
Referenced by debug_menu::faction_edit_larder_menu(), item::food_info(), max_in_place(), min_in_place(), and operator==().
kcal()
int nutrients::kcal () const
Definition at line 118 of file stomach.cpp.
 {
     return calories / 1000;
 }
References calories.
Referenced by anonymous_namespace{math_parser_diag.cpp}::calories_eval(), basecamp::camp_food_supply(), basecamp::camp_food_supply_days(), item_search_data::check(), comestible_inventory_preset::comestible_inventory_preset(), Character::compute_calories_per_effective_volume(), Character::compute_effective_food_volume_ratio(), Character::consume_effects(), npc::consume_food_from_camp(), stomach_contents::digest(), basecamp::distribute_food(), basecamp::faction_display(), debug_menu::faction_edit_larder_menu(), debug_menu::faction_edit_menu(), item::food_info(), faction::food_supply_color(), faction::food_supply_text(), get_auto_consume_moves(), basecamp::get_available_missions_by_dir(), stomach_contents::get_calories(), islot_comestible::get_default_nutr(), kcal_range_of_internal(), basecamp::make_fake_food(), stomach_contents::mod_calories(), Character::nutrition_for(), operator==(), basecamp::player_eats_meal(), Character::update_stomach(), and faction::vitamin_stores().
max_in_place()
void nutrients::max_in_place (const nutrients & r)
Definition at line 33 of file stomach.cpp.
 {
     calories = std::max( calories, r.calories );
     for( const std::pair<const vitamin_id, vitamin> &vit_pair : vitamin::all() ) {
         const vitamin_id &vit = vit_pair.first;
         int other = r.get_vitamin( vit );
         if( other != 0 ) {
             std::variant<int, vitamin_units::mass> &val = vitamins_[vit];
             // We must be finalized because we're calling vitamin::all()
             val = std::max( std::get<int>( val ), other );
         }
     }
 }
References vitamin::all(), calories, get_vitamin(), max(), other, and vitamins_.
Referenced by Character::compute_nutrient_range().
min_in_place()
void nutrients::min_in_place (const nutrients & r)
Replace the values here with the minimum (or maximum) of themselves and the corresponding values taken from r.
Definition at line 15 of file stomach.cpp.
 {
     calories = std::min( calories, r.calories );
     for( const std::pair<const vitamin_id, vitamin> &vit_pair : vitamin::all() ) {
         const vitamin_id &vit = vit_pair.first;
         int other = r.get_vitamin( vit );
         if( other == 0 ) {
             vitamins_.erase( vit );
         } else {
             auto our_vit = vitamins_.find( vit );
             if( our_vit != vitamins_.end() ) {
                 // We must be finalized because we're calling vitamin::all()
                 our_vit->second = std::min( std::get<int>( our_vit->second ), other );
             }
         }
     }
 }
References vitamin::all(), calories, get_vitamin(), min(), other, and vitamins_.
Referenced by Character::compute_nutrient_range().
operator!=()
bool nutrients::operator!= (const nutrients & r) const inline
Definition at line 66 of file stomach.h.
{
             return !( *this == r );
         }
operator*=() [1/2]
nutrients & nutrients::operator*= (double r)
Definition at line 194 of file stomach.cpp.
 {
     if( !finalized ) {
         debugmsg( "Nutrients not finalized when *= called!" );
     }
     calories *= r;
     for( const std::pair<const vitamin_id, std::variant<int, vitamin_units::mass>> &vit : vitamins_ ) {
         std::variant<int, vitamin_units::mass> &here = vitamins_[vit.first];
         // Note well: This truncates the result!
         here = static_cast<int>( std::get<int>( here ) * r );
     }
     return *this;
 }
References calories, debugmsg, finalized, and vitamins_.
operator*=() [2/2]
nutrients & nutrients::operator*= (int r)
Definition at line 181 of file stomach.cpp.
 {
     if( !finalized ) {
         debugmsg( "Nutrients not finalized when *= called!" );
     }
     calories *= r;
     for( const std::pair<const vitamin_id, std::variant<int, vitamin_units::mass>> &vit : vitamins_ ) {
         std::variant<int, vitamin_units::mass> &here = vitamins_[vit.first];
         here = std::get<int>( here ) * r;
     }
     return *this;
 }
References calories, debugmsg, finalized, and vitamins_.
operator+=()
nutrients & nutrients::operator+= (const nutrients & r)
Definition at line 153 of file stomach.cpp.
 {
     if( !finalized || !r.finalized ) {
         debugmsg( "Nutrients not finalized when += called!" );
     }
     calories += r.calories;
     for( const std::pair<const vitamin_id, std::variant<int, vitamin_units::mass>> &vit :
          r.vitamins_ ) {
         std::variant<int, vitamin_units::mass> &here = vitamins_[vit.first];
         here = std::get<int>( here ) + std::get<int>( vit.second );
     }
     return *this;
 }
References calories, debugmsg, finalized, and vitamins_.
operator-=()
nutrients & nutrients::operator-= (const nutrients & r)
Definition at line 167 of file stomach.cpp.
 {
     if( !finalized || !r.finalized ) {
         debugmsg( "Nutrients not finalized when -= called!" );
     }
     calories -= r.calories;
     for( const std::pair<const vitamin_id, std::variant<int, vitamin_units::mass>> &vit :
          r.vitamins_ ) {
         std::variant<int, vitamin_units::mass> &here = vitamins_[vit.first];
         here = std::get<int>( here ) - std::get<int>( vit.second );
     }
     return *this;
 }
References calories, debugmsg, finalized, and vitamins_.
operator/=()
nutrients & nutrients::operator/= (int r)
Definition at line 208 of file stomach.cpp.
 {
     if( !finalized ) {
         debugmsg( "Nutrients not finalized when -= called!" );
     }
     calories = divide_round_up<int64_t>( calories, r );
     for( const std::pair<const vitamin_id, std::variant<int, vitamin_units::mass>> &vit : vitamins_ ) {
         std::variant<int, vitamin_units::mass> &here = vitamins_[vit.first];
         here = divide_round_up( std::get<int>( here ), r );
     }
     return *this;
 }
References calories, debugmsg, divide_round_up(), finalized, and vitamins_.
operator==()
bool nutrients::operator== (const nutrients & r) const
Definition at line 137 of file stomach.cpp.
 {
     if( kcal() != r.kcal() ) {
         return false;
     }
     // Can't just use vitamins == r.vitamins, because there might be zero
     // entries in the map, which need to compare equal to missing entries.
     for( const std::pair<const vitamin_id, vitamin> &vit_pair : vitamin::all() ) {
         const vitamin_id &vit = vit_pair.first;
         if( get_vitamin( vit ) != r.get_vitamin( vit ) ) {
             return false;
         }
     }
     return true;
 }
References vitamin::all(), get_vitamin(), and kcal().
remove_vitamin()
void nutrients::remove_vitamin (const vitamin_id & vit)
Definition at line 100 of file stomach.cpp.
 {
     vitamins_.erase( vit );
 }
References vitamins_.
Referenced by stomach_contents::deserialize().
serialize()
void nutrients::serialize (JsonOut & jsout) const
Definition at line 221 of file stomach.cpp.
 {
     jsout.start_object();
     jsout.member( "calories", calories );
     jsout.member( "vitamins", vitamins() );
     jsout.end_object();
 }
References calories, JsonOut::end_object(), JsonOut::member(), JsonOut::start_object(), and vitamins().
set_vitamin() [1/2]
void nutrients::set_vitamin (const vitamin_id & vit, int units)
Definition at line 84 of file stomach.cpp.
 {
     auto iter = vitamins_.emplace( vit, 0 ).first;
     iter->second = units;
 }
References vitamins_.
set_vitamin() [2/2]
void nutrients::set_vitamin (const vitamin_id & vit, vitamin_units::mass mass)
Definition at line 61 of file stomach.cpp.
 {
     if( finalized ) {
         set_vitamin( vit, vit->units_from_mass( mass ) );
         return;
     }
     vitamins_[vit] = mass;
 }
References finalized, vitamin::units_from_mass(), and vitamins_.
Referenced by deserialize(), stomach_contents::deserialize(), stomach_contents::digest(), debug_menu::faction_edit_larder_menu(), and Item_factory::load().
vitamins()
std::map< vitamin_id, int > nutrients::vitamins () const
Definition at line 47 of file stomach.cpp.
 {
     if( !finalized ) {
         debugmsg( "Called nutrients::vitamins() before they were finalized!" );
         return std::map<vitamin_id, int>();
     }
     std::map<vitamin_id, int> ret;
     for( const std::pair<const vitamin_id, std::variant<int, vitamin_units::mass>> &vit : vitamins_ ) {
         ret.emplace( vit.first, std::get<int>( vit.second ) );
     }
     return ret;
 }
References debugmsg, finalized, cata::hash64_detail::ret, and vitamins_.
Referenced by basecamp::camp_food_supply(), stomach_contents::deserialize(), stomach_contents::digest(), item::food_info(), item::has_vitamin(), serialize(), stomach_contents::serialize(), Character::update_stomach(), and faction::vitamin_stores().
Friends And Related Function Documentation
operator*
nutrients operator* (nutrients l, int r) friend
Definition at line 76 of file stomach.h.
{
             l *= r;
             return l;
         }
operator/
nutrients operator/ (nutrients l, int r) friend
Definition at line 81 of file stomach.h.
{
             l /= r;
             return l;
         }
Member Data Documentation
calories
int64_t nutrients::calories = 0
amount of calories (1/1000s of kcal) this food has
Definition at line 38 of file stomach.h.
Referenced by basecamp::camp_food_supply(), deserialize(), stomach_contents::deserialize(), stomach_contents::digest(), debug_menu::faction_edit_larder_menu(), faction_template::faction_template(), islot_comestible::has_calories(), kcal(), Item_factory::load(), max_in_place(), min_in_place(), stomach_contents::mod_calories(), operator*=(), operator+=(), operator-=(), operator/=(), serialize(), and stomach_contents::serialize().
finalized
bool nutrients::finalized = true
Definition at line 89 of file stomach.h.
Referenced by add_vitamin(), finalize_vitamins(), get_vitamin(), Item_factory::load(), operator*=(), operator+=(), operator-=(), operator/=(), set_vitamin(), and vitamins().
vitamins_
std::map<vitamin_id, std::variant<int, vitamin_units::mass> > nutrients::vitamins_ private
vitamins potentially provided by this comestible (if any)
Definition at line 96 of file stomach.h.
Referenced by add_vitamin(), finalize_vitamins(), get_vitamin(), max_in_place(), min_in_place(), operator*=(), operator+=(), operator-=(), operator/=(), remove_vitamin(), set_vitamin(), and vitamins().
The documentation for this struct was generated from the following files:
src/stomach.h
src/stomach.cpp