Cataclysm DDA: event_transformation_impl Struct Reference
event_transformation_impl Struct Reference
Classes
struct state
struct updatable_value_constraint
Public Types
using EventVector = std::vector< cata::event::data_type >
Public Member Functions
template<typename NewFields , typename Constraints , typename DropFields >
event_transformation_impl (const string_id< event_transformation > &id, std::unique_ptr< event_source > source, const NewFields &new_fields, const Constraints &constraints, const DropFields &drop_fields)
EventVector match_and_transform (const cata::event::data_type &input_data, const std::list< updatable_value_constraint > &cached_value_constraints) const
std::list< updatable_value_constraint > make_cached_value_constraints (state *st, stats_tracker &stats) const
event_multiset initialize (const event_multiset::summaries_type &input, const std::list< updatable_value_constraint > &cached_value_constraints, stats_tracker &) const
event_multiset initialize (const std::list< updatable_value_constraint > &cached_value_constraints, stats_tracker &stats) const
event_multiset initialize (stats_tracker &stats) const override
void check (const std::string &name) const override
std::unique_ptr< stats_tracker_state > watch (stats_tracker &stats) const override
cata::event::fields_type fields () const override
monotonically monotonicity () const override
std::unique_ptr< impl > clone () const override
Public Member Functions inherited from event_transformation::impl
virtual ~impl ()=default
Public Attributes
string_id< event_transformation > id_
cata::clone_ptr< event_source > source_
std::vector< std::pair< std::string, new_field > > new_fields_
std::vector< std::pair< std::string, value_constraint > > constraints_
std::vector< std::string > drop_fields_
Detailed Description
Definition at line 438 of file event_statistics.cpp.
Member Typedef Documentation
EventVector
using event_transformation_impl::EventVector = std::vector<cata::event::data_type>
Definition at line 556 of file event_statistics.cpp.
Constructor & Destructor Documentation
event_transformation_impl()
template<typename NewFields , typename Constraints , typename DropFields > event_transformation_impl::event_transformation_impl (const string_id< event_transformation > & id, std::unique_ptr< event_source > source, const NewFields & new_fields, const Constraints & constraints, const DropFields & drop_fields) inline
Definition at line 440 of file event_statistics.cpp.
                                                                :
         id_( id ),
         source_( std::move( source ) ),
         new_fields_( new_fields.begin(), new_fields.end() ),
         constraints_( constraints.begin(), constraints.end() ),
         drop_fields_( drop_fields.begin(), drop_fields.end() )
     {}
Member Function Documentation
check()
void event_transformation_impl::check (const std::string & name) const inline override virtual
Reimplemented from event_transformation::impl.
Definition at line 633 of file event_statistics.cpp.
{
         const cata::event::fields_type input_fields = source_->fields();
         for( const std::pair<std::string, new_field> &p : new_fields_ ) {
             if( input_fields.count( p.first ) ) {
                 debugmsg( "event_transformation %s tries to add field with name %s but a field "
                           "with that name already exists", name, p.first );
             }
             p.second.check( name, input_fields );
         }
         for( const std::pair<std::string, value_constraint> &p : constraints_ ) {
             auto it = input_fields.find( p.first );
             if( it == input_fields.end() ) {
                 debugmsg( "event_transformation %s applies constraint to field %s, but no field "
                           "with that name exists in the input", name, p.first );
             } else {
                 p.second.check( name, it->second );
             }
         }
         for( const std::string &drop_field_name : drop_fields_ ) {
             if( input_fields.find( drop_field_name ) == input_fields.end() ) {
                 debugmsg( "event_transformation %s lists field %s to be dropped, but no field "
                           "with that name exists in the input", name, drop_field_name );
             }
         }
     }
References constraints_, debugmsg, drop_fields_, event_source::fields(), om_direction::name(), new_fields_, and source_.
clone()
std::unique_ptr<impl> event_transformation_impl::clone () const inline override virtual
Implements event_transformation::impl.
Definition at line 689 of file event_statistics.cpp.
{
         return std::make_unique<event_transformation_impl>( *this );
     }
fields()
cata::event::fields_type event_transformation_impl::fields () const inline override virtual
Implements event_transformation::impl.
Definition at line 666 of file event_statistics.cpp.
{
         cata::event::fields_type result = source_->fields();
         for( const std::pair<std::string, new_field> &p : new_fields_ ) {
             result.emplace( p.first, p.second.type( result ) );
         }
         for( const std::string &drop_field_name : drop_fields_ ) {
             result.erase( drop_field_name );
         }
         return result;
     }
References drop_fields_, event_source::fields(), new_fields_, and source_.
initialize() [1/3]
event_multiset event_transformation_impl::initialize (const event_multiset::summaries_type & input, const std::list< updatable_value_constraint > & cached_value_constraints, stats_tracker &) const inline
Definition at line 607 of file event_statistics.cpp.
{
         event_multiset result;
         for( const std::pair<const cata::event::data_type, event_summary> &p : input ) {
             cata::event::data_type event_data = p.first;
             EventVector transformed = match_and_transform( event_data, cached_value_constraints );
             for( cata::event::data_type &d : transformed ) {
                 result.add( { d, p.second } );
             }
         }
         return result;
     }
References event_multiset::add(), event_multiset::first(), and match_and_transform().
Referenced by event_transformation_impl::state::events_reset(), initialize(), and event_transformation_impl::state::value_constraint_changed().
initialize() [2/3]
event_multiset event_transformation_impl::initialize (const std::list< updatable_value_constraint > & cached_value_constraints, stats_tracker & stats) const inline
Definition at line 623 of file event_statistics.cpp.
{
         return initialize( source_->get( stats ).counts(), cached_value_constraints, stats );
     }
References event_multiset::counts(), event_source::get(), initialize(), and source_.
initialize() [3/3]
event_multiset event_transformation_impl::initialize (stats_tracker & stats) const inline override virtual
Implements event_transformation::impl.
Definition at line 629 of file event_statistics.cpp.
{
         return initialize( make_cached_value_constraints( nullptr, stats ), stats );
     }
References initialize(), and make_cached_value_constraints().
make_cached_value_constraints()
std::list<updatable_value_constraint> event_transformation_impl::make_cached_value_constraints (state * st, stats_tracker & stats) const inline
Definition at line 596 of file event_statistics.cpp.
{
         // Need to use list here rather than vector because
         // updatable_value_constraint is not movable.
         std::list<updatable_value_constraint> result;
         for( const auto &p : constraints_ ) {
             result.emplace_back( p, st, stats );
         }
         return result;
     }
References constraints_.
Referenced by initialize().
match_and_transform()
EventVector event_transformation_impl::match_and_transform (const cata::event::data_type & input_data, const std::list< updatable_value_constraint > & cached_value_constraints) const inline
Definition at line 558 of file event_statistics.cpp.
{
         cata_assert( cached_value_constraints.size() == constraints_.size() );
         EventVector result = { input_data };
         for( const std::pair<std::string, new_field> &p : new_fields_ ) {
             EventVector before_this_pass = std::move( result );
             result.clear();
             for( const cata::event::data_type &data : before_this_pass ) {
                 EventVector from_this_event = p.second.transform( data, p.first );
                 result.insert( result.end(), from_this_event.begin(), from_this_event.end() );
             }
         }
         auto violates_constraints = [&]( const cata::event::data_type & data ) {
             for( const updatable_value_constraint &constraint : cached_value_constraints ) {
                 const std::string &field = constraint.field_name();
                 const auto it = data.find( field );
                 if( it == data.end() || !constraint.permits( it->second ) ) {
                     return true;
                 }
             }
             return false;
         };
         result.erase( std::remove_if( result.begin(), result.end(), violates_constraints ),
                       result.end() );
         for( cata::event::data_type &data : result ) {
             for( const std::string &drop_field_name : drop_fields_ ) {
                 data.erase( drop_field_name );
             }
         }
         return result;
     }
References cata_assert, constraints_, drop_fields_, and new_fields_.
Referenced by event_transformation_impl::state::event_added(), and initialize().
monotonicity()
monotonically event_transformation_impl::monotonicity () const inline override virtual
Implements event_transformation::impl.
Definition at line 680 of file event_statistics.cpp.
{
         for( const std::pair<std::string, value_constraint> &constraint : constraints_ ) {
             if( !constraint.second.is_constant() ) {
                 return monotonically::unknown;
             }
         }
         return monotonically::increasing;
     }
References constraints_, increasing, and unknown.
watch()
std::unique_ptr<stats_tracker_state> event_transformation_impl::watch (stats_tracker & stats) const inline override virtual
Implements event_transformation::impl.
Definition at line 662 of file event_statistics.cpp.
{
         return std::make_unique<state>( this, stats );
     }
Member Data Documentation
constraints_
std::vector<std::pair<std::string, value_constraint> > event_transformation_impl::constraints_
Definition at line 454 of file event_statistics.cpp.
Referenced by check(), make_cached_value_constraints(), match_and_transform(), monotonicity(), and event_transformation_impl::state::state().
drop_fields_
std::vector<std::string> event_transformation_impl::drop_fields_
Definition at line 455 of file event_statistics.cpp.
Referenced by check(), fields(), and match_and_transform().
id_
string_id<event_transformation> event_transformation_impl::id_
Definition at line 451 of file event_statistics.cpp.
Referenced by event_transformation_impl::state::event_added(), event_transformation_impl::state::events_reset(), and event_transformation_impl::state::value_constraint_changed().
new_fields_
std::vector<std::pair<std::string, new_field> > event_transformation_impl::new_fields_
Definition at line 453 of file event_statistics.cpp.
Referenced by check(), fields(), and match_and_transform().
source_
cata::clone_ptr<event_source> event_transformation_impl::source_
Definition at line 452 of file event_statistics.cpp.
Referenced by check(), fields(), initialize(), and event_transformation_impl::state::state().
The documentation for this struct was generated from the following file:
src/event_statistics.cpp