Cataclysm DDA: weakpoint Struct Reference
weakpoint Struct Reference
#include <weakpoint.h>
Public Member Functions
weakpoint ()
std::string get_name () const
void apply_to (resistances &resistances) const
void apply_to (damage_instance &damage, bool is_crit) const
void apply_effects (Creature &target, int total_damage, const weakpoint_attack &attack) const
float hit_chance (const weakpoint_attack &attack) const
void load (const JsonObject &jo)
void check () const
Public Attributes
std::string id
translation name
float coverage = 100.0f
std::unordered_map< damage_type_id, float > armor_mult
std::unordered_map< damage_type_id, float > armor_penalty
std::unordered_map< damage_type_id, float > damage_mult
std::unordered_map< damage_type_id, float > crit_mult
std::vector< efftype_id > required_effects
std::vector< weakpoint_effect > effects
weakpoint_difficulty coverage_mult
weakpoint_difficulty difficulty
Detailed Description
Definition at line 120 of file weakpoint.h.
Constructor & Destructor Documentation
weakpoint()
weakpoint::weakpoint ()
Definition at line 395 of file weakpoint.cpp.
                      : coverage_mult( 1.0f ), difficulty( -100.0f )
 {
 }
Member Function Documentation
apply_effects()
void weakpoint::apply_effects (Creature & target, int total_damage, const weakpoint_attack & attack) const
Definition at line 500 of file weakpoint.cpp.
 {
     for( const weakpoint_effect &effect : effects ) {
         effect.apply_to( target, total_damage, attack );
     }
 }
References spell_effect::attack(), and effects.
Referenced by Creature::deal_damage().
apply_to() [1/2]
void weakpoint::apply_to (damage_instance & damage, bool is_crit) const
Definition at line 487 of file weakpoint.cpp.
 {
     for( damage_unit &elem : damage.damage_units ) {
         if( is_crit ) {
             if( crit_mult.count( elem.type ) > 0 ) {
                 elem.damage_multiplier *= crit_mult.at( elem.type );
             }
         } else if( damage_mult.count( elem.type ) > 0 ) {
             elem.damage_multiplier *= damage_mult.at( elem.type );
         }
     }
 }
References crit_mult, damage_mult, damage_unit::damage_multiplier, damage_instance::damage_units, and damage_unit::type.
apply_to() [2/2]
void weakpoint::apply_to (resistances & resistances) const
Definition at line 472 of file weakpoint.cpp.
 {
     for( const damage_type &dt : damage_type::get_all() ) {
         if( resistances.resist_vals.count( dt.id ) <= 0 ) {
             resistances.resist_vals[dt.id] = 0.0f;
         }
         if( armor_mult.count( dt.id ) > 0 ) {
             resistances.resist_vals[dt.id] *= armor_mult.at( dt.id );
         }
         if( armor_penalty.count( dt.id ) > 0 ) {
             resistances.resist_vals[dt.id] -= armor_penalty.at( dt.id );
         }
     }
 }
References armor_mult, armor_penalty, damage_type::get_all(), and resistances::resist_vals.
Referenced by monster::absorb_hit().
check()
void weakpoint::check () const
Definition at line 443 of file weakpoint.cpp.
 {
     for( const std::pair<const damage_type_id, float> &dt : armor_mult ) {
         if( !dt.first.is_valid() ) {
             debugmsg( "Invalid armor_mult type \"%s\" for weakpoint %s", dt.first.c_str(), id );
         }
     }
     for( const std::pair<const damage_type_id, float> &dt : armor_penalty ) {
         if( !dt.first.is_valid() ) {
             debugmsg( "Invalid armor_penalty type \"%s\" for weakpoint %s", dt.first.c_str(), id );
         }
     }
     for( const std::pair<const damage_type_id, float> &dt : damage_mult ) {
         if( !dt.first.is_valid() ) {
             debugmsg( "Invalid damage_mult type \"%s\" for weakpoint %s", dt.first.c_str(), id );
         }
     }
     for( const std::pair<const damage_type_id, float> &dt : crit_mult ) {
         if( !dt.first.is_valid() ) {
             debugmsg( "Invalid crit_mult type \"%s\" for weakpoint %s", dt.first.c_str(), id );
         }
     }
 }
References armor_mult, armor_penalty, crit_mult, damage_mult, and debugmsg.
get_name()
std::string weakpoint::get_name () const
Definition at line 467 of file weakpoint.cpp.
 {
     return name.translated();
 }
References name, and translation::translated().
Referenced by Creature::deal_damage().
hit_chance()
float weakpoint::hit_chance (const weakpoint_attack & attack) const
Definition at line 508 of file weakpoint.cpp.
 {
     // Check for required effects
     for( const auto &effect : required_effects ) {
         if( !attack.target->has_effect( effect ) ) {
             return 0.0f;
         }
     }
     // Retrieve multipliers.
     float constant_mult = coverage_mult.of( attack );
     // Probability of a sample from a normal distribution centered on `skill` with `SD = 2`
     // exceeding the difficulty.
     float diff = attack.wp_skill - difficulty.of( attack );
     float difficulty_mult = 0.5f * ( 1.0f + erf( diff / ( 2.0f * sqrt( 2.0f ) ) ) );
     // Compute the total value
     return constant_mult * difficulty_mult * coverage;
 }
References spell_effect::attack(), coverage, coverage_mult, difficulty, weakpoint_difficulty::of(), required_effects, and sqrt().
Referenced by weakpoints::select_weakpoint().
load()
void weakpoint::load (const JsonObject & jo)
Definition at line 400 of file weakpoint.cpp.
 {
     assign( jo, "id", id );
     assign( jo, "name", name );
     assign( jo, "coverage", coverage, false, 0.0f, 100.0f );
     if( jo.has_object( "armor_mult" ) ) {
         armor_mult = load_damage_map( jo.get_object( "armor_mult" ) );
     }
     if( jo.has_object( "armor_penalty" ) ) {
         armor_penalty = load_damage_map( jo.get_object( "armor_penalty" ) );
     }
     if( jo.has_object( "damage_mult" ) ) {
         damage_mult = load_damage_map( jo.get_object( "damage_mult" ) );
     }
     if( jo.has_object( "crit_mult" ) ) {
         crit_mult = load_damage_map( jo.get_object( "crit_mult" ) );
     } else {
         // Default to damage multiplier, if crit multipler is not specified.
         crit_mult = damage_mult;
     }
     if( jo.has_array( "required_effects" ) ) {
         assign( jo, "required_effects", required_effects );
     }
     if( jo.has_array( "effects" ) ) {
         for( const JsonObject effect_jo : jo.get_array( "effects" ) ) {
             weakpoint_effect effect;
             effect.load( effect_jo );
             effects.push_back( std::move( effect ) );
         }
     }
     if( jo.has_object( "coverage_mult" ) ) {
         coverage_mult.load( jo.get_object( "coverage_mult" ) );
     }
     if( jo.has_object( "difficulty" ) ) {
         difficulty.load( jo.get_object( "difficulty" ) );
     }
     // Set the ID to the name, if not provided.
     if( !jo.has_string( "id" ) ) {
         assign( jo, "name", id );
     }
 }
References armor_mult, armor_penalty, assign(), coverage, coverage_mult, crit_mult, damage_mult, difficulty, effects, JsonObject::get_array(), JsonObject::get_object(), JsonObject::has_array(), JsonObject::has_object(), JsonObject::has_string(), weakpoint_difficulty::load(), load_damage_map(), name, and required_effects.
Referenced by weakpoints::load(), and weakpoints::remove().
Member Data Documentation
armor_mult
std::unordered_map<damage_type_id, float> weakpoint::armor_mult
Definition at line 128 of file weakpoint.h.
Referenced by monster::absorb_hit(), apply_to(), check(), and load().
armor_penalty
std::unordered_map<damage_type_id, float> weakpoint::armor_penalty
Definition at line 130 of file weakpoint.h.
Referenced by monster::absorb_hit(), apply_to(), check(), and load().
coverage
float weakpoint::coverage = 100.0f
Definition at line 126 of file weakpoint.h.
Referenced by hit_chance(), and load().
coverage_mult
weakpoint_difficulty weakpoint::coverage_mult
Definition at line 140 of file weakpoint.h.
Referenced by hit_chance(), and load().
crit_mult
std::unordered_map<damage_type_id, float> weakpoint::crit_mult
Definition at line 134 of file weakpoint.h.
Referenced by apply_to(), check(), and load().
damage_mult
std::unordered_map<damage_type_id, float> weakpoint::damage_mult
Definition at line 132 of file weakpoint.h.
Referenced by apply_to(), check(), and load().
difficulty
weakpoint_difficulty weakpoint::difficulty
Definition at line 142 of file weakpoint.h.
Referenced by hit_chance(), and load().
effects
std::vector<weakpoint_effect> weakpoint::effects
Definition at line 138 of file weakpoint.h.
Referenced by apply_effects(), and load().
id
std::string weakpoint::id
Definition at line 122 of file weakpoint.h.
Referenced by monster::absorb_hit(), weakpoints::load(), mtype::load(), weakpoints::remove(), and weakpoints::select_weakpoint().
name
translation weakpoint::name
Definition at line 124 of file weakpoint.h.
Referenced by get_name(), and load().
required_effects
std::vector<efftype_id> weakpoint::required_effects
Definition at line 136 of file weakpoint.h.
Referenced by hit_chance(), and load().
The documentation for this struct was generated from the following files:
src/weakpoint.h
src/weakpoint.cpp