Cataclysm DDA: lazy< T, typename > Struct Template Reference
lazy< T, typename > Struct Template Reference
A wrapper for a type that lazily initializes the underlying type as needed.
#include <cata_lazy.h>
Public Member Functions
lazy ()=default
bool has_value () const
template<typename Arg , typename ... Args>
lazy (Arg &&arg, Args &&...args)
template<typename U >
T & operator= (U &&u)
operator T& ()
operator T const & () const
T & operator* ()
const T & operator* () const
T * operator-> ()
const T * operator-> () const
template<typename Arg >
auto && operator[] (Arg &&arg)
Private Member Functions
T & get () const
Private Attributes
std::optional< T > actual
Detailed Description
template<typename T, typename = std::enable_if_t<std::is_default_constructible_v<T>>>
struct lazy< T, typename >
A wrapper for a type that lazily initializes the underlying type as needed.
Use to save unnecessary allocation costs for eg. std containers in transiently allocated types.
T must be default initializable.
Definition at line 15 of file cata_lazy.h.
Constructor & Destructor Documentation
lazy() [1/2]
template<typename T , typename = std::enable_if_t<std::is_default_constructible_v<T>>> lazy< T, typename >::lazy () default
lazy() [2/2]
template<typename T , typename = std::enable_if_t<std::is_default_constructible_v<T>>> template<typename Arg , typename ... Args> lazy< T, typename >::lazy (Arg && arg, Args &&... args) inline
Definition at line 28 of file cata_lazy.h.
 : actual{std::in_place, std::forward<Arg>( arg ), std::forward<Args>( args )...} {}
Member Function Documentation
get()
template<typename T , typename = std::enable_if_t<std::is_default_constructible_v<T>>> T& lazy< T, typename >::get () const inline private
Definition at line 70 of file cata_lazy.h.
                    {
         if( !actual.has_value() ) {
             actual.emplace();
         }
         return actual.value();
     }
References lazy< T, typename >::actual.
Referenced by lazy< safe_reference_anchor >::operator safe_reference_anchor &(), lazy< safe_reference_anchor >::operator safe_reference_anchor const &(), lazy< T, typename >::operator*(), lazy< T, typename >::operator->(), lazy< T, typename >::operator=(), and lazy< T, typename >::operator[]().
has_value()
template<typename T , typename = std::enable_if_t<std::is_default_constructible_v<T>>> bool lazy< T, typename >::has_value () const inline
Definition at line 20 of file cata_lazy.h.
{
         return actual.has_value();
     }
References lazy< T, typename >::actual.
Referenced by dialogue::dialogue().
operator T const &()
template<typename T , typename = std::enable_if_t<std::is_default_constructible_v<T>>> lazy< T, typename >::operator T const & () const inline
Definition at line 43 of file cata_lazy.h.
{
         return get();
     }
operator T&()
template<typename T , typename = std::enable_if_t<std::is_default_constructible_v<T>>> lazy< T, typename >::operator T& () inline
Definition at line 38 of file cata_lazy.h.
                    {
         return get();
     }
operator*() [1/2]
template<typename T , typename = std::enable_if_t<std::is_default_constructible_v<T>>> T& lazy< T, typename >::operator* () inline
Definition at line 47 of file cata_lazy.h.
                    {
         return get();
     }
References lazy< T, typename >::get().
operator*() [2/2]
template<typename T , typename = std::enable_if_t<std::is_default_constructible_v<T>>> const T& lazy< T, typename >::operator* () const inline
Definition at line 51 of file cata_lazy.h.
{
         return get();
     }
References lazy< T, typename >::get().
operator->() [1/2]
template<typename T , typename = std::enable_if_t<std::is_default_constructible_v<T>>> T* lazy< T, typename >::operator-> () inline
Definition at line 55 of file cata_lazy.h.
                     {
         return &get();
     }
References lazy< T, typename >::get().
operator->() [2/2]
template<typename T , typename = std::enable_if_t<std::is_default_constructible_v<T>>> const T* lazy< T, typename >::operator-> () const inline
Definition at line 59 of file cata_lazy.h.
{
         return &get();
     }
References lazy< T, typename >::get().
operator=()
template<typename T , typename = std::enable_if_t<std::is_default_constructible_v<T>>> template<typename U > T& lazy< T, typename >::operator= (U && u) inline
Definition at line 32 of file cata_lazy.h.
{
         get() = std::forward<U>( u );
         return get();
     }
References lazy< T, typename >::get(), and u.
operator[]()
template<typename T , typename = std::enable_if_t<std::is_default_constructible_v<T>>> template<typename Arg > auto&& lazy< T, typename >::operator[] (Arg && arg) inline
Definition at line 64 of file cata_lazy.h.
{
         return get()[std::forward<Arg>( arg )];
     }
References lazy< T, typename >::get().
Member Data Documentation
actual
template<typename T , typename = std::enable_if_t<std::is_default_constructible_v<T>>> std::optional<T> lazy< T, typename >::actual mutable private
Definition at line 77 of file cata_lazy.h.
Referenced by lazy< T, typename >::get(), and lazy< T, typename >::has_value().
The documentation for this struct was generated from the following file:
src/cata_lazy.h