Cataclysm DDA: numeric_interval< T, typename > Struct Template Reference
numeric_interval< T, typename > Struct Template Reference
An interval of numeric values between min and max (including both).
#include <common_types.h>
Public Member Functions
numeric_interval ()=default
numeric_interval (T min, T max)
numeric_interval (T middle, T lower_margin, T upper_margin)
bool operator== (const numeric_interval< T > &rhs) const
bool contains (T val) const
bool empty () const
void deserialize (const JsonValue &jsin)
Public Attributes
T min = static_cast<T>(0)
T max = static_cast<T>(0)
Detailed Description
template<typename T, typename = std::enable_if_t<std::is_arithmetic_v<T>, T>>
struct numeric_interval< T, typename >
An interval of numeric values between min and max (including both).
By default it's [0, 0].
Definition at line 13 of file common_types.h.
Constructor & Destructor Documentation
numeric_interval() [1/3]
template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>, T>> numeric_interval< T, typename >::numeric_interval () default
numeric_interval() [2/3]
template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>, T>> numeric_interval< T, typename >::numeric_interval (T min, T max) inline
Definition at line 18 of file common_types.h.
 : min( min ), max( max ) { }
numeric_interval() [3/3]
template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>, T>> numeric_interval< T, typename >::numeric_interval (T middle, T lower_margin, T upper_margin) inline
Definition at line 19 of file common_types.h.
                                                                  :
         min( middle - lower_margin ), max( middle + upper_margin ) {
     }
Member Function Documentation
contains()
template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>, T>> bool numeric_interval< T, typename >::contains (T val) const inline
Definition at line 27 of file common_types.h.
{
         return val >= min && val <= max;
     }
References numeric_interval< T, typename >::max, and numeric_interval< T, typename >::min.
Referenced by overmap_special::can_belong_to_city(), and start_location::can_belong_to_city().
deserialize()
template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>, T>> void numeric_interval< T, typename >::deserialize (const JsonValue & jsin) inline
Definition at line 35 of file common_types.h.
{
         JsonArray ja = jsin.get_array();
         if( ja.size() != 2 ) {
             ja.throw_error( "Intervals should be in format [min, max]." );
         }
         ja.read_next( min );
         ja.read_next( max );
         if( max < min ) {
             max = std::numeric_limits<T>::max();
         }
     }
References JsonValue::get_array(), numeric_interval< T, typename >::max, max(), numeric_interval< T, typename >::min, JsonArray::read_next(), JsonArray::size(), and JsonArray::throw_error().
empty()
template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>, T>> bool numeric_interval< T, typename >::empty () const inline
Definition at line 31 of file common_types.h.
{
         return max == 0 || min > max;
     }
References numeric_interval< T, typename >::max, and numeric_interval< T, typename >::min.
operator==()
template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>, T>> bool numeric_interval< T, typename >::operator== (const numeric_interval< T > & rhs) const inline
Definition at line 23 of file common_types.h.
{
         return min == rhs.min && max == rhs.max;
     }
References numeric_interval< T, typename >::max, and numeric_interval< T, typename >::min.
Member Data Documentation
max
template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>, T>> T numeric_interval< T, typename >::max = static_cast<T>(0)
Definition at line 15 of file common_types.h.
Referenced by numeric_interval< T, typename >::contains(), numeric_interval< T, typename >::deserialize(), numeric_interval< T, typename >::empty(), start_location::find_player_initial_location(), overmap_special::force_one_occurrence(), map::generate(), numeric_interval< T, typename >::operator==(), overmap::place_special(), overmap::place_special_attempt(), overmap::place_specials(), overmap_special::requires_city(), and start_location::requires_city().
min
template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>, T>> T numeric_interval< T, typename >::min = static_cast<T>(0)
Definition at line 14 of file common_types.h.
Referenced by overmap_special::can_spawn(), numeric_interval< T, typename >::contains(), numeric_interval< T, typename >::deserialize(), numeric_interval< T, typename >::empty(), start_location::find_player_initial_location(), overmap_special::force_one_occurrence(), map::generate(), numeric_interval< T, typename >::operator==(), overmap::place_special(), overmap::place_special_attempt(), overmap::place_specials(), overmap_special::requires_city(), and start_location::requires_city().
The documentation for this struct was generated from the following file:
src/common_types.h