Cataclysm DDA: city Struct Reference
city Struct Reference
#include <city.h>
Public Member Functions
void load (const JsonObject &, std::string_view)
void check () const
city (const point_om_omt &P=point_om_omt(), int S=-1)
operator bool () const
bool operator== (const city &rhs) const
int get_distance_from (const tripoint_om_omt &p) const
Static Public Member Functions
static void load_city (const JsonObject &, const std::string &)
static void finalize ()
static void check_consistency ()
static const std::vector< city > & get_all ()
static void reset ()
Public Attributes
city_id id
bool was_loaded = false
int database_id = 0
point_abs_om pos_om
point_om_omt pos
int population = 0
int size = -1
std::string name
Detailed Description
Definition at line 15 of file city.h.
Constructor & Destructor Documentation
city()
city::city (const point_om_omt & P = point_om_omt(), int S = -1) explicit
Definition at line 93 of file city.cpp.
     : pos( P )
     , size( S )
     , name( SNIPPET.expand( "<city_name>" ) )
 {
 }
Member Function Documentation
check()
void city::check () const
Definition at line 86 of file city.cpp.
 {
     if( get_option<bool>( "SELECT_STARTING_CITY" ) && city::get_all().empty() ) {
         debugmsg( "Overmap cities need to be defined when `SELECT_STARTING_CITY` option is set to `true`!" );
     }
 }
References debugmsg, and get_all().
check_consistency()
void city::check_consistency () static
Definition at line 59 of file city.cpp.
 {
     get_city_factory().check();
 }
References get_city_factory().
Referenced by DynamicDataLoader::check_consistency().
finalize()
void city::finalize () static
Definition at line 44 of file city.cpp.
 {
     for( city &c : const_cast<std::vector<city>&>( city::get_all() ) ) {
         if( c.name.empty() ) {
             c.name = SNIPPET.expand( "<city_name>" );
         }
         if( c.population == 0 ) {
             c.population = rng( 1, INT_MAX );
         }
         if( c.size == -1 ) {
             c.size = rng( 1, 16 );
         }
     }
 }
References c, snippet_library::expand(), get_all(), rng(), and SNIPPET.
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< city > & city::get_all () static
Definition at line 64 of file city.cpp.
 {
     return get_city_factory().get_all();
 }
References get_city_factory().
Referenced by check(), finalize(), overmap::place_cities(), set_description(), game::start_game(), and debug_menu::teleport_city().
get_distance_from()
int city::get_distance_from (const tripoint_om_omt & p) const
Definition at line 100 of file city.cpp.
 {
     return std::max( static_cast<int>( trig_dist( p, tripoint_om_omt{ pos, 0 } ) ) - size, 0 );
 }
References max(), pos, size, and trig_dist().
Referenced by overmap_special::can_belong_to_city(), start_location::can_belong_to_city(), and overmap::get_nearest_city().
load()
void city::load (const JsonObject & jo, std::string_view)
Definition at line 74 of file city.cpp.
 {
     mandatory( jo, was_loaded, "id", id );
     mandatory( jo, was_loaded, "database_id", database_id );
     optional( jo, was_loaded, "name", name );
     optional( jo, was_loaded, "population", population );
     optional( jo, was_loaded, "size", size );
     mandatory( jo, was_loaded, "pos_om", pos_om );
     mandatory( jo, was_loaded, "pos", pos );
 }
References database_id, mandatory, name, optional(), population, pos, pos_om, size, and was_loaded.
load_city()
void city::load_city (const JsonObject & jo, const std::string & src) static
Definition at line 39 of file city.cpp.
 {
     get_city_factory().load( jo, src );
 }
References get_city_factory().
Referenced by DynamicDataLoader::initialize().
operator bool()
city::operator bool () const inline explicit
Definition at line 39 of file city.h.
{
         return size >= 0;
     }
References size.
operator==()
bool city::operator== (const city & rhs) const inline
Definition at line 43 of file city.h.
{
         return id == rhs.id ||
                database_id == rhs.database_id ||
                ( pos_om == rhs.pos_om && pos == rhs.pos ) ;
     }
References database_id, id, pos, and pos_om.
reset()
void city::reset () static
Definition at line 69 of file city.cpp.
 {
     get_city_factory().reset();
 }
References get_city_factory().
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
database_id
int city::database_id = 0
Definition at line 27 of file city.h.
Referenced by load(), operator==(), and overmap::unserialize().
id
city_id city::id
Definition at line 24 of file city.h.
Referenced by operator==(), and overmap::unserialize().
name
std::string city::name
Definition at line 35 of file city.h.
Referenced by load(), overmap::unserialize(), and weather_forecast().
population
int city::population = 0
Definition at line 33 of file city.h.
Referenced by load(), and overmap::unserialize().
pos
point_om_omt city::pos
Definition at line 31 of file city.h.
Referenced by get_distance_from(), load(), operator==(), fixed_overmap_special_data::place(), mutable_overmap_special_data::place(), overmap::place_building(), overmap::place_cities(), overmap::unserialize(), and mongroup::wander().
pos_om
point_abs_om city::pos_om
Definition at line 29 of file city.h.
Referenced by load(), operator==(), overmap::place_cities(), and overmap::unserialize().
size
int city::size = -1
Definition at line 34 of file city.h.
Referenced by overmap_special::can_belong_to_city(), start_location::can_belong_to_city(), overmapbuffer::get_description_at(), get_distance_from(), city_reference::get_distance_from_bounds(), load(), mission_place::near_town(), operator bool(), overmap::place_building(), overmap::place_cities(), random_house_in_city(), overmap::unserialize(), and mongroup::wander().
was_loaded
bool city::was_loaded = false
Definition at line 25 of file city.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/city.h
src/city.cpp