Cataclysm DDA: area_expander Struct Reference
area_expander Struct Reference
#include <magic.h>
Classes
struct area_node_comparator
struct node
Public Member Functions
area_expander ()
int contains (const tripoint &pt) const
bool enqueue (const tripoint &from, const tripoint &to, float cost)
int run (const tripoint &center)
void sort_ascending ()
void sort_descending ()
Public Attributes
int max_range = -1
int max_expand = -1
std::vector< node > area
std::map< tripoint, int > area_search
std::priority_queue< int, std::vector< int >, area_node_comparator > frontier
Detailed Description
Definition at line 871 of file magic.h.
Constructor & Destructor Documentation
area_expander()
area_expander::area_expander ()
Definition at line 654 of file magic_spell_effect.cpp.
                              : frontier( area_node_comparator( area ) )
 {
 }
Member Function Documentation
contains()
int area_expander::contains (const tripoint & pt) const
Definition at line 659 of file magic_spell_effect.cpp.
 {
     return area_search.count( pt ) > 0;
 }
References area_search.
Referenced by enqueue(), and run().
enqueue()
bool area_expander::enqueue (const tripoint & from, const tripoint & to, float cost)
Definition at line 665 of file magic_spell_effect.cpp.
 {
     if( contains( to ) ) {
         // We will modify existing node if its cost is lower.
         int index = area_search[to];
         node &node = area[index];
         if( cost < node.cost ) {
             node.from = from;
             node.cost = cost;
         }
         return false;
     }
     int index = area.size();
     area.push_back( {to, from, cost} );
     frontier.push( index );
     area_search[to] = index;
     return true;
 }
References area, area_search, contains(), area_expander::node::cost, area_expander::node::from, and frontier.
Referenced by run().
run()
int area_expander::run (const tripoint & center)
Definition at line 685 of file magic_spell_effect.cpp.
 {
     enqueue( center, center, 0.0 );
     static constexpr std::array<int, 8> x_offset = {{ -1, 1,  0, 0,  1, -1, -1, 1  }};
     static constexpr std::array<int, 8> y_offset = {{  0, 0, -1, 1, -1,  1, -1, 1  }};
     // Number of nodes expanded.
     int expanded = 0;
     map &here = get_map();
     while( !frontier.empty() ) {
         int best_index = frontier.top();
         frontier.pop();
         for( size_t i = 0; i < 8; i++ ) {
             node &best = area[best_index];
             const tripoint &pt = best.position + point( x_offset[ i ], y_offset[ i ] );
             if( here.impassable( pt ) ) {
                 continue;
             }
             float center_range = static_cast<float>( rl_dist( center, pt ) );
             if( max_range > 0 && center_range > max_range ) {
                 continue;
             }
             if( max_expand > 0 && expanded > max_expand && contains( pt ) ) {
                 continue;
             }
             float delta_range = trig_dist( best.position, pt );
             if( enqueue( best.position, pt, best.cost + delta_range ) ) {
                 expanded++;
             }
         }
     }
     return expanded;
 }
References area, center, contains(), area_expander::node::cost, enqueue(), frontier, get_map(), map::impassable(), max_expand, max_range, point, area_expander::node::position, rl_dist(), and trig_dist().
Referenced by spell_effect::area_pull(), spell_effect::area_push(), and spell_remove_field().
sort_ascending()
void area_expander::sort_ascending ()
Definition at line 728 of file magic_spell_effect.cpp.
 {
     // Since internal caches like 'area_search' and 'frontier' use indexes inside 'area',
     // these caches will be invalidated.
     std::sort( area.begin(), area.end(),
     []( const node & a, const node & b )  -> bool {
         return a.cost < b.cost;
     } );
 }
References a, area, and b.
Referenced by spell_effect::area_pull(), and spell_remove_field().
sort_descending()
void area_expander::sort_descending ()
Definition at line 738 of file magic_spell_effect.cpp.
 {
     // Since internal caches like 'area_search' and 'frontier' use indexes inside 'area',
     // these caches will be invalidated.
     std::sort( area.begin(), area.end(),
     []( const node & a, const node & b ) -> bool {
         return a.cost > b.cost;
     } );
 }
References a, area, and b.
Referenced by spell_effect::area_push().
Member Data Documentation
area
std::vector<node> area_expander::area
Definition at line 886 of file magic.h.
Referenced by spell_effect::area_pull(), spell_effect::area_push(), enqueue(), run(), sort_ascending(), sort_descending(), and spell_remove_field().
area_search
std::map<tripoint, int> area_expander::area_search
Definition at line 889 of file magic.h.
Referenced by contains(), and enqueue().
frontier
std::priority_queue<int, std::vector<int>, area_node_comparator> area_expander::frontier
Definition at line 902 of file magic.h.
Referenced by enqueue(), and run().
max_expand
int area_expander::max_expand = -1
Definition at line 883 of file magic.h.
Referenced by run().
max_range
int area_expander::max_range = -1
Definition at line 882 of file magic.h.
Referenced by spell_effect::area_pull(), spell_effect::area_push(), run(), and spell_remove_field().
The documentation for this struct was generated from the following files:
src/magic.h
src/magic_spell_effect.cpp