Cataclysm DDA: sub_effect_parser Struct Reference
sub_effect_parser Struct Reference
Public Types
using f_t = talk_effect_fun_t::func(*)(const JsonObject &, std::string_view)
using f_t_beta = talk_effect_fun_t::func(*)(const JsonObject &, std::string_view, bool)
using f_t_effect = talk_effect_fun_t(*)(const JsonObject &, std::string_view)
using f_t_beta_effect = talk_effect_fun_t(*)(const JsonObject &, std::string_view, bool)
Public Member Functions
sub_effect_parser (std::string_view key_alpha_, jarg arg_, f_t f_)
sub_effect_parser (std::string_view key_alpha_, std::string_view key_beta_, jarg arg_, f_t_beta f_)
sub_effect_parser (std::string_view key_alpha_, jarg arg_, f_t_effect f_)
bool check (const JsonObject &jo, bool beta=false) const
Public Attributes
bool has_beta = false
std::string_view key_alpha
std::string_view key_beta
jarg arg
std::function< talk_effect_fun_t(const JsonObject &, std::string_view, bool)> f
Detailed Description
Definition at line 127 of file npctalk.cpp.
Member Typedef Documentation
f_t
using sub_effect_parser::f_t = talk_effect_fun_t::func(*)(const JsonObject &, std::string_view)
Definition at line 128 of file npctalk.cpp.
f_t_beta
using sub_effect_parser::f_t_beta = talk_effect_fun_t::func(*)(const JsonObject &, std::string_view, bool)
Definition at line 129 of file npctalk.cpp.
f_t_beta_effect
using sub_effect_parser::f_t_beta_effect = talk_effect_fun_t (*)(const JsonObject &, std::string_view, bool)
Definition at line 131 of file npctalk.cpp.
f_t_effect
using sub_effect_parser::f_t_effect = talk_effect_fun_t (*)(const JsonObject &, std::string_view)
Definition at line 130 of file npctalk.cpp.
Constructor & Destructor Documentation
sub_effect_parser() [1/3]
sub_effect_parser::sub_effect_parser (std::string_view key_alpha_, jarg arg_, f_t f_) inline
Definition at line 133 of file npctalk.cpp.
                                                                       : key_alpha( key_alpha_ ),
         arg( arg_ ) {
         f = [f_]( const JsonObject & jo, std::string_view key, bool ) {
             return talk_effect_fun_t( f_( jo, key ) );
         };
     }
References f.
sub_effect_parser() [2/3]
sub_effect_parser::sub_effect_parser (std::string_view key_alpha_, std::string_view key_beta_, jarg arg_, f_t_beta f_) inline
Definition at line 139 of file npctalk.cpp.
                                      : key_alpha( key_alpha_ ), key_beta( key_beta_ ), arg( arg_ ) {
         f = [f_]( const JsonObject & jo, std::string_view key, bool beta ) {
             return talk_effect_fun_t( f_( jo, key, beta ) );
         };
         has_beta = true;
     }
References f, and has_beta.
sub_effect_parser() [3/3]
sub_effect_parser::sub_effect_parser (std::string_view key_alpha_, jarg arg_, f_t_effect f_) inline
Definition at line 146 of file npctalk.cpp.
         : key_alpha( key_alpha_ ), arg( arg_ ) {
         f = [f_]( const JsonObject & jo, std::string_view key, bool ) {
             return f_( jo, key );
         };
     }
References f.
Member Function Documentation
check()
bool sub_effect_parser::check (const JsonObject & jo, bool beta = false) const inline
Definition at line 154 of file npctalk.cpp.
{
         std::string_view key = beta ? key_beta : key_alpha;
         if( ( ( arg & jarg::member ) && jo.has_member( key ) ) ||
             ( ( arg & jarg::object ) && jo.has_object( key ) ) ||
             ( ( arg & jarg::string ) && jo.has_string( key ) ) ||
             ( ( arg & jarg::array ) && jo.has_array( key ) ) ) {
             return true;
         }
         return false;
     }
References arg, array, JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), key_alpha, key_beta, member, object, and string.
Member Data Documentation
arg
jarg sub_effect_parser::arg
Definition at line 168 of file npctalk.cpp.
Referenced by check().
f
std::function<talk_effect_fun_t(const JsonObject &, std::string_view, bool)> sub_effect_parser::f
Definition at line 169 of file npctalk.cpp.
Referenced by sub_effect_parser().
has_beta
bool sub_effect_parser::has_beta = false
Definition at line 165 of file npctalk.cpp.
Referenced by sub_effect_parser().
key_alpha
std::string_view sub_effect_parser::key_alpha
Definition at line 166 of file npctalk.cpp.
Referenced by check().
key_beta
std::string_view sub_effect_parser::key_beta
Definition at line 167 of file npctalk.cpp.
Referenced by check().
The documentation for this struct was generated from the following file:
src/npctalk.cpp