Cataclysm DDA: anonymous_namespace{bionics_ui.cpp}::bionic_sort_less Struct Reference
anonymous_namespace{bionics_ui.cpp}::bionic_sort_less Struct Reference
Public Member Functions
bool operator() (const bionic *lhs, const bionic *rhs) const
Detailed Description
Definition at line 95 of file bionics_ui.cpp.
Member Function Documentation
operator()()
bool anonymous_namespace{bionics_ui.cpp}::bionic_sort_less::operator() (const bionic * lhs, const bionic * rhs) const inline
Definition at line 96 of file bionics_ui.cpp.
{
         const bionic_data &lbd = lhs->info();
         const bionic_data &rbd = rhs->info();
         switch( uistate.bionic_sort_mode ) {
             case bionic_ui_sort_mode::nsort:
             case bionic_ui_sort_mode::NONE:
                 //use installation order
                 return true;
             case bionic_ui_sort_mode::INVLET:
                 return lhs->invlet < rhs->invlet;
             case bionic_ui_sort_mode::POWER: {
                 units::energy lbd_sort_power = bionic_sort_power( lbd );
                 units::energy rbd_sort_power = bionic_sort_power( rbd );
                 if( lbd_sort_power != rbd_sort_power ) {
                     return lbd_sort_power < rbd_sort_power;
                 }
             }
             /* fallthrough */
             case bionic_ui_sort_mode::NAME:
                 return localized_compare( lbd.name.translated(), rbd.name.translated() );
         }
         return false;
     }
References uistatedata::bionic_sort_mode, anonymous_namespace{bionics_ui.cpp}::bionic_sort_power(), bionic::info(), bionic::invlet, INVLET, localized_compare, bionic_data::name, NAME, NONE, nsort, POWER, translation::translated(), and uistate.
The documentation for this struct was generated from the following file:
src/bionics_ui.cpp