Cataclysm DDA: cata::heap< T > Struct Template Reference
cata::heap< T > Struct Template Reference
This class is essentially a copyable unique pointer, like value_ptr, except it hides the fact it is a unique_ptr.
#include <value_ptr.h>
Public Member Functions
template<typename ... Args>
heap (Args &&...args)
heap (heap &&) noexcept=default
heap & operator= (heap &&other) noexcept=default
heap (heap const &rhs)
heap & operator= (heap const &rhs)
heap & operator= (T const &t)
heap & operator= (T &&t)
operator T& () &
operator T const & () const &
operator T () &&
T & operator* () &
T const & operator* () const &
T operator* () &&
auto operator== (heap const &rhs) const -> decltype(val()==val())
auto operator!= (heap const &rhs) const -> decltype(val() !=val())
template<typename U >
auto operator[] (U &&u) -> decltype(val()[std::forward< U >(u)])
template<typename Stream = JsonOut>
void serialize (Stream &jsout) const
template<typename Value = JsonValue, std::enable_if_t< std::is_same_v< std::decay_t< Value >, JsonValue >> * = nullptr>
void deserialize (const Value &jsin)
Private Member Functions
T & val ()
T const & val () const
Private Attributes
std::unique_ptr< T > heaped_
Detailed Description
template<class T>
struct cata::heap< T >
This class is essentially a copyable unique pointer, like value_ptr, except it hides the fact it is a unique_ptr.
It is intended for helping make types noexcept movable by moving non-noexcept-movable types to the heap.
Contractually speaking, should never be empty. However for performance reasons in eg. item, moved-from heap<> objects do not automatically reset with a new copy of the wrapped data.
Definition at line 74 of file value_ptr.h.
Constructor & Destructor Documentation
heap() [1/3]
template<class T > template<typename ... Args> cata::heap< T >::heap (Args &&... args) inline
Definition at line 81 of file value_ptr.h.
 : heaped_{ new T{ std::forward<Args>( args )... } } {}
heap() [2/3]
template<class T > cata::heap< T >::heap (heap< T > &&) default noexcept
heap() [3/3]
template<class T > cata::heap< T >::heap (heap< T > const & rhs) inline
Definition at line 89 of file value_ptr.h.
{
             *this = rhs;
         }
Member Function Documentation
deserialize()
template<class T > template<typename Value = JsonValue, std::enable_if_t< std::is_same_v< std::decay_t< Value >, JsonValue >> * = nullptr> void cata::heap< T >::deserialize (const Value & jsin) inline
Definition at line 215 of file value_ptr.h.
{
             jsin.read( val() );
         }
References cata::heap< T >::val().
operator T()
template<class T > cata::heap< T >::operator T () && inline
Definition at line 123 of file value_ptr.h.
                         { // *NOPAD*
             return std::move( *heaped_ );
         }
operator T const &()
template<class T > cata::heap< T >::operator T const & () const & inline
Definition at line 118 of file value_ptr.h.
                                      { // *NOPAD*
             return *heaped_;
         }
operator T&()
template<class T > cata::heap< T >::operator T& () & inline
Definition at line 114 of file value_ptr.h.
                          { // *NOPAD*
             return *heaped_;
         }
operator!=()
template<class T > auto cata::heap< T >::operator!= (heap< T > const & rhs) const -> decltype(val() != val()) inline
Definition at line 175 of file value_ptr.h.
{
             const T *lhsp = heaped_.get();
             const T *rhsp = rhs.heaped_.get();
             return rhsp && lhsp && *rhsp != *lhsp;
         }
References cata::heap< T >::heaped_.
operator*() [1/3]
template<class T > T& cata::heap< T >::operator* () & inline
Definition at line 132 of file value_ptr.h.
                          { // *NOPAD*
             return *heaped_;
         }
References cata::heap< T >::heaped_.
operator*() [2/3]
template<class T > T cata::heap< T >::operator* () && inline
Definition at line 139 of file value_ptr.h.
                          { // *NOPAD*
             return std::move( *heaped_ );
         }
References cata::heap< T >::heaped_.
operator*() [3/3]
template<class T > T const& cata::heap< T >::operator* () const & inline
Definition at line 135 of file value_ptr.h.
                                      { // *NOPAD*
             return *heaped_;
         }
References cata::heap< T >::heaped_.
operator=() [1/4]
template<class T > heap& cata::heap< T >::operator= (heap< T > && other) default noexcept
operator=() [2/4]
template<class T > heap& cata::heap< T >::operator= (heap< T > const & rhs) inline
Definition at line 92 of file value_ptr.h.
{
             // This should always be true, however, sanity says do the right thing.
             if( rhs.heaped_ ) {
                 heaped_.reset( new T{ *rhs.heaped_ } );
             } else {
                 heaped_.reset( new T{} );
             }
             return *this;
         }
References cata::heap< T >::heaped_.
operator=() [3/4]
template<class T > heap& cata::heap< T >::operator= (T && t) inline
Definition at line 107 of file value_ptr.h.
{
             heaped_.reset( new T{ std::move( t ) } );
             return *this;
         }
References cata::heap< T >::heaped_.
operator=() [4/4]
template<class T > heap& cata::heap< T >::operator= (T const & t) inline
Definition at line 102 of file value_ptr.h.
{
             heaped_.reset( new T{ t } );
             return *this;
         }
References cata::heap< T >::heaped_.
operator==()
template<class T > auto cata::heap< T >::operator== (heap< T > const & rhs) const -> decltype(val() == val()) inline
Definition at line 168 of file value_ptr.h.
{
             const T *lhsp = heaped_.get();
             const T *rhsp = rhs.heaped_.get();
             return rhsp && lhsp && *rhsp == *lhsp;
         }
References cata::heap< T >::heaped_.
operator[]()
template<class T > template<typename U > auto cata::heap< T >::operator[] (U && u) -> decltype(val()[std::forward<U>(u)]) inline
Definition at line 197 of file value_ptr.h.
{
             return val()[std::forward<U>( u )];
         }
References u, and cata::heap< T >::val().
serialize()
template<class T > template<typename Stream = JsonOut> void cata::heap< T >::serialize (Stream & jsout) const inline
Definition at line 210 of file value_ptr.h.
{
             jsout.write( val() );
         }
References cata::heap< T >::val().
val() [1/2]
template<class T > T& cata::heap< T >::val () inline private
Definition at line 145 of file value_ptr.h.
                  {
             return *heaped_;
         }
References cata::heap< T >::heaped_.
Referenced by cata::heap< T >::deserialize(), cata::heap< T >::operator[](), and cata::heap< T >::serialize().
val() [2/2]
template<class T > T const& cata::heap< T >::val () const inline private
Definition at line 148 of file value_ptr.h.
{
             return *heaped_;
         }
References cata::heap< T >::heaped_.
Member Data Documentation
heaped_
template<class T > std::unique_ptr<T> cata::heap< T >::heaped_ private
Definition at line 76 of file value_ptr.h.
Referenced by cata::heap< FlagsSetType >::operator FlagsSetType(), cata::heap< FlagsSetType >::operator FlagsSetType &(), cata::heap< FlagsSetType >::operator FlagsSetType const &(), cata::heap< T >::operator!=(), cata::heap< T >::operator*(), cata::heap< T >::operator=(), cata::heap< T >::operator==(), and cata::heap< T >::val().
The documentation for this struct was generated from the following file:
src/value_ptr.h