Cataclysm DDA: bodygraph Struct Reference
bodygraph Struct Reference
#include <bodygraph.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
void finalize ()
void check () const
Static Public Member Functions
static void load_bodygraphs (const JsonObject &jo, const std::string &src)
static void finalize_all ()
static void check_all ()
static void reset ()
static const std::vector< bodygraph > & get_all ()
Public Attributes
bodygraph_id id
std::optional< bodypart_id > parent_bp
std::optional< bodygraph_id > mirror
std::vector< std::vector< std::string > > rows
std::vector< std::vector< std::string > > fill_rows
std::map< std::string, bodygraph_part > parts
std::string fill_sym
nc_color fill_color = c_white
bool was_loaded = false
Detailed Description
Definition at line 52 of file bodygraph.h.
Member Function Documentation
check()
void bodygraph::check () const
Definition at line 206 of file bodygraph.cpp.
 {
     if( parts.empty() ) {
         debugmsg( "body_graph \"%s\" defined without parts.", id.c_str() );
     }
     for( const auto &bgp : parts ) {
         if( utf8_width( bgp.first ) > 1 ) {
             debugmsg( "part \"%s\" in body_graph \"%s\" is more than 1 character.", bgp.first, id.c_str() );
         }
         if( bgp.second.bodyparts.empty() && bgp.second.sub_bodyparts.empty() ) {
             debugmsg( "part \"%s\" in body_graph \"%s\" contains no body_parts or sub_body_parts definitions.",
                       bgp.first, id.c_str() );
         }
     }
 }
References debugmsg, parts, and utf8_width().
check_all()
void bodygraph::check_all () static
Definition at line 85 of file bodygraph.cpp.
 {
     bodygraph_factory.check();
 }
References anonymous_namespace{bodygraph.cpp}::bodygraph_factory.
Referenced by DynamicDataLoader::check_consistency().
finalize()
void bodygraph::finalize ()
Definition at line 142 of file bodygraph.cpp.
 {
     if( rows.size() > BPGRAPH_MAXROWS ) {
         debugmsg( "body_graph \"%s\" defines more rows than the maximum (%d).", id.c_str(),
                   BPGRAPH_MAXROWS );
     }
     if( !fill_rows.empty() &&  fill_rows.size() != rows.size() ) {
         debugmsg( "body_graph \"%s\" defines a different number of fill_rows than rows (%d vs. %d).",
                   id.c_str(),
                   fill_rows.size(), rows.size() );
     }
     int width = -1;
     bool w_warned = false;
     for( size_t i = 0; i < rows.size(); i++ ) {
         std::vector<std::string> &r = rows[i];
         int w = r.size();
         if( width == -1 ) {
             width = w;
         } else if( !w_warned && width != w ) {
             debugmsg( "body_graph \"%s\" defines rows with different widths.", id.c_str() );
             w_warned = true;
         } else if( !w_warned && w > BPGRAPH_MAXCOLS ) {
             debugmsg( "body_graph \"%s\" defines rows with more columns than the maximum (%d).", id.c_str(),
                       BPGRAPH_MAXCOLS );
             w_warned = true;
         }
         r.insert( r.begin(), ( BPGRAPH_MAXCOLS - w ) / 2, " " );
         r.insert( r.end(), BPGRAPH_MAXCOLS - r.size(), " " );
         if( ! fill_rows.empty() ) {
             std::vector<std::string> &fr = fill_rows[i];
             if( fr.size() != r.size() ) {
                 debugmsg( "body_graph \"%s\" defines a different number of columns in fill_rows than in rows (%d vs. %d).",
                           id.c_str(),
                           fr.size(), w );
             }
             fr.insert( fr.begin(), ( BPGRAPH_MAXCOLS - w ) / 2, " " );
             fr.insert( fr.end(), BPGRAPH_MAXCOLS - fr.size(), " " );
         }
     }
     for( std::vector<std::vector<std::string>> temp_rows : {
              rows, fill_rows
          } ) {
         if( !temp_rows.empty() ) {
             for( int i = ( BPGRAPH_MAXROWS - temp_rows.size() ) / 2; i > 0; i-- ) {
                 std::vector<std::string> r;
                 r.insert( r.begin(), BPGRAPH_MAXCOLS, " " );
                 temp_rows.insert( temp_rows.begin(), r );
             }
             for( int i = temp_rows.size(); i <= BPGRAPH_MAXROWS; i++ ) {
                 std::vector<std::string> r;
                 r.insert( r.begin(), BPGRAPH_MAXCOLS, " " );
                 temp_rows.emplace_back( r );
             }
         }
     }
 }
References BPGRAPH_MAXCOLS, BPGRAPH_MAXROWS, debugmsg, fill_rows, and rows.
finalize_all()
void bodygraph::finalize_all () static
Definition at line 80 of file bodygraph.cpp.
 {
     bodygraph_factory.finalize();
 }
References anonymous_namespace{bodygraph.cpp}::bodygraph_factory.
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< bodygraph > & bodygraph::get_all () static
Definition at line 75 of file bodygraph.cpp.
 {
     return bodygraph_factory.get_all();
 }
References anonymous_namespace{bodygraph.cpp}::bodygraph_factory.
load()
void bodygraph::load (const JsonObject & jo, std::string_view src)
Definition at line 90 of file bodygraph.cpp.
 {
     optional( jo, was_loaded, "parent_bodypart", parent_bp );
     optional( jo, was_loaded, "fill_sym", fill_sym );
     if( jo.has_string( "fill_color" ) ) {
         fill_color = color_from_string( jo.get_string( "fill_color" ) );
     }
     if( jo.has_string( "mirror" ) ) {
         mirror.reset();
         mandatory( jo, false, "mirror", mirror );
     } else if( !was_loaded || jo.has_array( "rows" ) ) {
         rows.clear();
         fill_rows.clear();
         for( const JsonValue jval : jo.get_array( "rows" ) ) {
             if( !jval.test_string() ) {
                 jval.throw_error( "\"rows\" array must contain string values." );
             } else {
                 rows.emplace_back( utf8_display_split( jval.get_string() ) );
             }
         }
         if( jo.has_array( "fill_rows" ) ) {
             for( const JsonValue jval : jo.get_array( "fill_rows" ) ) {
                 if( !jval.test_string() ) {
                     jval.throw_error( "\"rows\" array must contain string values." );
                 } else {
                     fill_rows.emplace_back( utf8_display_split( jval.get_string() ) );
                 }
             }
         }
     }
     if( !was_loaded || jo.has_object( "parts" ) ) {
         parts.clear();
         for( const JsonMember memb : jo.get_object( "parts" ) ) {
             const std::string &sym = memb.name();
             JsonObject mobj = memb.get_object();
             bodygraph_part bpg;
             optional( mobj, false, "body_parts", bpg.bodyparts );
             optional( mobj, false, "sub_body_parts", bpg.sub_bodyparts );
             optional( mobj, false, "sym", bpg.sym, fill_sym );
             if( mobj.has_string( "select_color" ) ) {
                 bpg.sel_color = color_from_string( mobj.get_string( "select_color" ) );
             } else {
                 bpg.sel_color = fill_color;
             }
             optional( mobj, false, "nested_graph", bpg.nested_graph );
             parts.emplace( sym, bpg );
         }
     }
 }
References bodygraph_part::bodyparts, color_from_string(), fill_color, fill_rows, fill_sym, JsonObject::get_array(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_object(), JsonObject::has_string(), mandatory, mirror, bodygraph_part::nested_graph, optional(), parent_bp, parts, rows, bodygraph_part::sel_color, bodygraph_part::sub_bodyparts, bodygraph_part::sym, utf8_display_split(), and was_loaded.
load_bodygraphs()
void bodygraph::load_bodygraphs (const JsonObject & jo, const std::string & src) static
Definition at line 65 of file bodygraph.cpp.
 {
     bodygraph_factory.load( jo, src );
 }
References anonymous_namespace{bodygraph.cpp}::bodygraph_factory.
Referenced by DynamicDataLoader::initialize().
reset()
void bodygraph::reset () static
Definition at line 70 of file bodygraph.cpp.
 {
     bodygraph_factory.reset();
 }
References anonymous_namespace{bodygraph.cpp}::bodygraph_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
fill_color
nc_color bodygraph::fill_color = c_white
Definition at line 60 of file bodygraph.h.
Referenced by item::armor_info(), bodygraph_display::draw_graph(), and load().
fill_rows
std::vector<std::vector<std::string> > bodygraph::fill_rows
Definition at line 57 of file bodygraph.h.
Referenced by finalize(), and load().
fill_sym
std::string bodygraph::fill_sym
Definition at line 59 of file bodygraph.h.
Referenced by load().
id
bodygraph_id bodygraph::id
Definition at line 53 of file bodygraph.h.
mirror
std::optional<bodygraph_id> bodygraph::mirror
Definition at line 55 of file bodygraph.h.
Referenced by get_bg_rows(), and load().
parent_bp
std::optional<bodypart_id> bodygraph::parent_bp
Definition at line 54 of file bodygraph.h.
Referenced by bodygraph_display::draw_borders(), and load().
parts
std::map<std::string, bodygraph_part> bodygraph::parts
Definition at line 58 of file bodygraph.h.
Referenced by check(), load(), and bodygraph_display::prepare_partlist().
rows
std::vector<std::vector<std::string> > bodygraph::rows
Definition at line 56 of file bodygraph.h.
Referenced by display::colorized_bodygraph_text(), finalize(), get_bodygraph_lines(), and load().
was_loaded
bool bodygraph::was_loaded = false
Definition at line 61 of file bodygraph.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/bodygraph.h
src/bodygraph.cpp