Cataclysm DDA: small_literal_vector< T, kInlineCount, SizeT > Struct Template Reference
small_literal_vector< T, kInlineCount, SizeT > Struct Template Reference
A vector type that is specialized for storing trivial types in contiguous storage with a statically predetermined amount of inline storage.
#include <cata_small_literal_vector.h>
Classes
union alignas
Public Member Functions
small_literal_vector ()
small_literal_vector (const small_literal_vector &other)
small_literal_vector & operator= (const small_literal_vector &rhs)
small_literal_vector (small_literal_vector &&other) noexcept
small_literal_vector & operator= (small_literal_vector &&rhs) noexcept
~small_literal_vector ()
T * begin ()
T * back ()
T * end ()
const T * begin () const
const T * back () const
const T * end () const
T * data ()
const T * data () const
SizeT size () const
void push_back (const T &t)
template<typename ... US, std::enable_if_t< std::is_constructible_v< T, US... >> * = 0>
void push_back (US &&...us)
void pop_back ()
void ensure_capacity_for (size_t count)
void resize (size_t count)
Private Member Functions
void check_capacity (size_t count) const
void reserve_exact (size_t new_capacity)
void copy_init (const small_literal_vector &other)
void steal_init (small_literal_vector &&other) noexcept
bool on_heap () const
Private Attributes
SizeT capacity_
SizeT len_
Detailed Description
template<typename T, size_t kInlineCount = 4, typename SizeT = uint8_t>
struct small_literal_vector< T, kInlineCount, SizeT >
A vector type that is specialized for storing trivial types in contiguous storage with a statically predetermined amount of inline storage.
Because this is intended to be small, the internal capacity and size variables default to uint8_t for minimal overhead over the inline storage.
Definition at line 21 of file cata_small_literal_vector.h.
Constructor & Destructor Documentation
small_literal_vector() [1/3]
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> small_literal_vector< T, kInlineCount, SizeT >::small_literal_vector () inline
Definition at line 29 of file cata_small_literal_vector.h.
 : heap_( nullptr ), capacity_( kInlineCount ), len_( 0 ) {}
small_literal_vector() [2/3]
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> small_literal_vector< T, kInlineCount, SizeT >::small_literal_vector (const small_literal_vector< T, kInlineCount, SizeT > & other) inline
Definition at line 30 of file cata_small_literal_vector.h.
                                                               : capacity_( kInlineCount ), len_( 0 ) {
         copy_init( other );
     }
References small_literal_vector< T, kInlineCount, SizeT >::copy_init(), and other.
small_literal_vector() [3/3]
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> small_literal_vector< T, kInlineCount, SizeT >::small_literal_vector (small_literal_vector< T, kInlineCount, SizeT > && other) inline noexcept
Definition at line 38 of file cata_small_literal_vector.h.
{
         steal_init( std::move( other ) );
     }
References other, and small_literal_vector< T, kInlineCount, SizeT >::steal_init().
~small_literal_vector()
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> small_literal_vector< T, kInlineCount, SizeT >::~small_literal_vector () inline
Definition at line 46 of file cata_small_literal_vector.h.
{
         if( on_heap() ) {
             free( heap_ );
         }
     }
References small_literal_vector< T, kInlineCount, SizeT >::on_heap().
Member Function Documentation
back() [1/2]
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> T* small_literal_vector< T, kInlineCount, SizeT >::back () inline
Definition at line 56 of file cata_small_literal_vector.h.
               {
         return data() + size() - 1;
     }
References small_literal_vector< T, kInlineCount, SizeT >::data(), and small_literal_vector< T, kInlineCount, SizeT >::size().
Referenced by JsonPath::last().
back() [2/2]
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> const T* small_literal_vector< T, kInlineCount, SizeT >::back () const inline
Definition at line 68 of file cata_small_literal_vector.h.
{
         return data() + size() - 1;
     }
References small_literal_vector< T, kInlineCount, SizeT >::data(), and small_literal_vector< T, kInlineCount, SizeT >::size().
begin() [1/2]
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> T* small_literal_vector< T, kInlineCount, SizeT >::begin () inline
Definition at line 52 of file cata_small_literal_vector.h.
                {
         return data();
     }
References small_literal_vector< T, kInlineCount, SizeT >::data().
Referenced by JsonPath::begin().
begin() [2/2]
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> const T* small_literal_vector< T, kInlineCount, SizeT >::begin () const inline
Definition at line 64 of file cata_small_literal_vector.h.
{
         return data();
     }
References small_literal_vector< T, kInlineCount, SizeT >::data().
check_capacity()
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> void small_literal_vector< T, kInlineCount, SizeT >::check_capacity (size_t count) const inline private
Definition at line 138 of file cata_small_literal_vector.h.
{
         if( count > std::numeric_limits<SizeT>::max() ) {
             throw std::runtime_error(
                 "Attempted to use small_literal_vector for " +
                 std::to_string( count ) +
                 " elements items when there is only tracking space for " +
                 std::to_string( std::numeric_limits<SizeT>::max() ) );
         }
     }
References max(), and to_string().
Referenced by small_literal_vector< T, kInlineCount, SizeT >::ensure_capacity_for(), and small_literal_vector< T, kInlineCount, SizeT >::resize().
copy_init()
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> void small_literal_vector< T, kInlineCount, SizeT >::copy_init (const small_literal_vector< T, kInlineCount, SizeT > & other) inline private
Definition at line 181 of file cata_small_literal_vector.h.
{
         if( this != &other ) {
             ensure_capacity_for( other.capacity_ );
             len_ = other.size();
             std::uninitialized_copy_n( other.data(), len_, data() );
         }
     }
References small_literal_vector< T, kInlineCount, SizeT >::data(), small_literal_vector< T, kInlineCount, SizeT >::ensure_capacity_for(), small_literal_vector< T, kInlineCount, SizeT >::len_, and other.
Referenced by small_literal_vector< T, kInlineCount, SizeT >::operator=(), and small_literal_vector< T, kInlineCount, SizeT >::small_literal_vector().
data() [1/2]
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> T* small_literal_vector< T, kInlineCount, SizeT >::data () inline
Definition at line 76 of file cata_small_literal_vector.h.
               {
         return on_heap() ? heap_ : inline_;
     }
References small_literal_vector< T, kInlineCount, SizeT >::on_heap().
Referenced by small_literal_vector< T, kInlineCount, SizeT >::back(), small_literal_vector< T, kInlineCount, SizeT >::begin(), small_literal_vector< T, kInlineCount, SizeT >::copy_init(), and small_literal_vector< T, kInlineCount, SizeT >::end().
data() [2/2]
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> const T* small_literal_vector< T, kInlineCount, SizeT >::data () const inline
Definition at line 80 of file cata_small_literal_vector.h.
{
         return on_heap() ? heap_ : inline_;
     }
References small_literal_vector< T, kInlineCount, SizeT >::on_heap().
end() [1/2]
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> T* small_literal_vector< T, kInlineCount, SizeT >::end () inline
Definition at line 60 of file cata_small_literal_vector.h.
              {
         return data() + size();
     }
References small_literal_vector< T, kInlineCount, SizeT >::data(), and small_literal_vector< T, kInlineCount, SizeT >::size().
Referenced by JsonPath::end(), and small_literal_vector< T, kInlineCount, SizeT >::push_back().
end() [2/2]
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> const T* small_literal_vector< T, kInlineCount, SizeT >::end () const inline
Definition at line 72 of file cata_small_literal_vector.h.
{
         return data() + size();
     }
References small_literal_vector< T, kInlineCount, SizeT >::data(), and small_literal_vector< T, kInlineCount, SizeT >::size().
ensure_capacity_for()
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> void small_literal_vector< T, kInlineCount, SizeT >::ensure_capacity_for (size_t count) inline
Definition at line 108 of file cata_small_literal_vector.h.
{
         check_capacity( count );
         if( count <= capacity_ ) {
             return;
         }
         // 1.5x resize factor allows for reuse of earlier allocations at larger sizes.
         // That works best if we tracked explicit capacity, but it's better than nothing.
         // https://stackoverflow.com/a/1100426
         size_t new_capacity = capacity_;
         size_t next_capacity = capacity_ * 1.5;
         // Prevent overflow by testing before multiplying
         while( next_capacity > new_capacity && next_capacity < count ) {
             new_capacity = next_capacity;
             next_capacity *= 1.5;
         }
         if( new_capacity < count ) {
             new_capacity = std::numeric_limits<SizeT>::max();
         }
         reserve_exact( new_capacity );
     }
References small_literal_vector< T, kInlineCount, SizeT >::capacity_, small_literal_vector< T, kInlineCount, SizeT >::check_capacity(), max(), and small_literal_vector< T, kInlineCount, SizeT >::reserve_exact().
Referenced by small_literal_vector< T, kInlineCount, SizeT >::copy_init(), and small_literal_vector< T, kInlineCount, SizeT >::push_back().
on_heap()
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> bool small_literal_vector< T, kInlineCount, SizeT >::on_heap () const inline private
Definition at line 207 of file cata_small_literal_vector.h.
{
         return capacity_ > kInlineCount;
     }
References small_literal_vector< T, kInlineCount, SizeT >::capacity_.
Referenced by small_literal_vector< T, kInlineCount, SizeT >::data(), and small_literal_vector< T, kInlineCount, SizeT >::~small_literal_vector().
operator=() [1/2]
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> small_literal_vector& small_literal_vector< T, kInlineCount, SizeT >::operator= (const small_literal_vector< T, kInlineCount, SizeT > & rhs) inline
Definition at line 33 of file cata_small_literal_vector.h.
{
         copy_init( rhs );
         return *this;
     }
References small_literal_vector< T, kInlineCount, SizeT >::copy_init().
operator=() [2/2]
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> small_literal_vector& small_literal_vector< T, kInlineCount, SizeT >::operator= (small_literal_vector< T, kInlineCount, SizeT > && rhs) inline noexcept
Definition at line 41 of file cata_small_literal_vector.h.
{
         steal_init( std::move( rhs ) );
         return *this;
     }
References small_literal_vector< T, kInlineCount, SizeT >::steal_init().
pop_back()
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> void small_literal_vector< T, kInlineCount, SizeT >::pop_back () inline
Definition at line 100 of file cata_small_literal_vector.h.
                     {
         if( len_ == 0 ) {
             throw std::runtime_error( "Popping an empty vector." );
         }
         len_ -= 1;
     }
References small_literal_vector< T, kInlineCount, SizeT >::len_.
Referenced by JsonPath::pop_back().
push_back() [1/2]
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> void small_literal_vector< T, kInlineCount, SizeT >::push_back (const T & t) inline
Definition at line 88 of file cata_small_literal_vector.h.
{
         ensure_capacity_for( size() + 1 );
         *end() = t;
         len_ += 1;
     }
References small_literal_vector< T, kInlineCount, SizeT >::end(), small_literal_vector< T, kInlineCount, SizeT >::ensure_capacity_for(), small_literal_vector< T, kInlineCount, SizeT >::len_, and small_literal_vector< T, kInlineCount, SizeT >::size().
Referenced by JsonPath::push_back().
push_back() [2/2]
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> template<typename ... US, std::enable_if_t< std::is_constructible_v< T, US... >> * = 0> void small_literal_vector< T, kInlineCount, SizeT >::push_back (US &&... us) inline
Definition at line 94 of file cata_small_literal_vector.h.
{
         ensure_capacity_for( size() + 1 );
         *end() = T( std::forward < US && > ( us )... );
         len_ += 1;
     }
References small_literal_vector< T, kInlineCount, SizeT >::end(), small_literal_vector< T, kInlineCount, SizeT >::ensure_capacity_for(), small_literal_vector< T, kInlineCount, SizeT >::len_, and small_literal_vector< T, kInlineCount, SizeT >::size().
reserve_exact()
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> void small_literal_vector< T, kInlineCount, SizeT >::reserve_exact (size_t new_capacity) inline private
Definition at line 149 of file cata_small_literal_vector.h.
{
         T *heap = nullptr;
         if( capacity_ <= kInlineCount ) {
             if( new_capacity <= kInlineCount ) {
                 return;
             }
             on_out_of_scope heap_guard( [&heap] { free( heap ); } );
             heap = static_cast<T *>( std::malloc( sizeof( T ) * new_capacity ) );
             std::uninitialized_copy_n( inline_, size(), heap );
             heap_ = heap;
             heap_guard.cancel();
         } else {
             // Don't bother 'unheapifying', but do shrink allocation.
             // GCC incorrectly tags heap_ as possibly uninitialized in the copy_init path.
 #if defined(__GNUC__) && !defined(__clang__)
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
 #endif
             heap = static_cast<T *>( std::realloc( heap_, sizeof( T ) * new_capacity ) );
 #if defined(__GNUC__) && !defined(__clang__)
 #pragma GCC diagnostic pop
 #endif
             if( heap ) {
                 heap_ = heap;
             } else {
                 throw std::runtime_error( "realloc failed." );
             }
         }
         capacity_ = new_capacity;
     }
References small_literal_vector< T, kInlineCount, SizeT >::capacity_, and small_literal_vector< T, kInlineCount, SizeT >::size().
Referenced by small_literal_vector< T, kInlineCount, SizeT >::ensure_capacity_for(), and small_literal_vector< T, kInlineCount, SizeT >::resize().
resize()
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> void small_literal_vector< T, kInlineCount, SizeT >::resize (size_t count) inline
Definition at line 131 of file cata_small_literal_vector.h.
{
         check_capacity( count );
         reserve_exact( count );
         len_ = count;
     }
References small_literal_vector< T, kInlineCount, SizeT >::check_capacity(), small_literal_vector< T, kInlineCount, SizeT >::len_, and small_literal_vector< T, kInlineCount, SizeT >::reserve_exact().
size()
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> SizeT small_literal_vector< T, kInlineCount, SizeT >::size () const inline
Definition at line 84 of file cata_small_literal_vector.h.
{
         return len_;
     }
References small_literal_vector< T, kInlineCount, SizeT >::len_.
Referenced by small_literal_vector< T, kInlineCount, SizeT >::back(), small_literal_vector< T, kInlineCount, SizeT >::end(), small_literal_vector< T, kInlineCount, SizeT >::push_back(), small_literal_vector< T, kInlineCount, SizeT >::reserve_exact(), and JsonPath::size().
steal_init()
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> void small_literal_vector< T, kInlineCount, SizeT >::steal_init (small_literal_vector< T, kInlineCount, SizeT > && other) inline private noexcept
Definition at line 189 of file cata_small_literal_vector.h.
{
         if( this != &other ) {
             if( other.on_heap() ) {
                 // Optimization: steal the heap pointer.
                 heap_ = other.heap_;
                 capacity_ = other.capacity_;
                 other.heap_ = nullptr;
                 other.capacity_ = kInlineCount;
             } else {
                 // Skip the ensure_capacity_for call cause we know it has to be inline.
                 std::uninitialized_copy_n( other.inline_, other.len_, inline_ );
                 capacity_ = kInlineCount;
             }
             len_ = other.len_;
             other.len_ = 0;
         }
     }
References small_literal_vector< T, kInlineCount, SizeT >::capacity_, small_literal_vector< T, kInlineCount, SizeT >::len_, and other.
Referenced by small_literal_vector< T, kInlineCount, SizeT >::operator=(), and small_literal_vector< T, kInlineCount, SizeT >::small_literal_vector().
Member Data Documentation
capacity_
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> SizeT small_literal_vector< T, kInlineCount, SizeT >::capacity_ private
Definition at line 225 of file cata_small_literal_vector.h.
Referenced by small_literal_vector< T, kInlineCount, SizeT >::ensure_capacity_for(), small_literal_vector< T, kInlineCount, SizeT >::on_heap(), small_literal_vector< T, kInlineCount, SizeT >::reserve_exact(), and small_literal_vector< T, kInlineCount, SizeT >::steal_init().
len_
template<typename T , size_t kInlineCount = 4, typename SizeT = uint8_t> SizeT small_literal_vector< T, kInlineCount, SizeT >::len_ private
Definition at line 226 of file cata_small_literal_vector.h.
Referenced by small_literal_vector< T, kInlineCount, SizeT >::copy_init(), small_literal_vector< T, kInlineCount, SizeT >::pop_back(), small_literal_vector< T, kInlineCount, SizeT >::push_back(), small_literal_vector< T, kInlineCount, SizeT >::resize(), small_literal_vector< T, kInlineCount, SizeT >::size(), and small_literal_vector< T, kInlineCount, SizeT >::steal_init().
The documentation for this struct was generated from the following file:
src/cata_small_literal_vector.h