Cataclysm DDA: mission_start Struct Reference
mission_start Struct Reference
#include <mission.h>
Static Public Member Functions
static void standard (mission *)
static void kill_nemesis (mission *)
static void place_npc_software (mission *)
static void place_deposit_box (mission *)
static void find_safety (mission *)
static void place_book (mission *)
static void reveal_refugee_center (mission *)
static void create_lab_console (mission *)
static void create_hidden_lab_console (mission *)
static void create_ice_lab_console (mission *)
Detailed Description
Definition at line 102 of file mission.h.
Member Function Documentation
create_hidden_lab_console()
void mission_start::create_hidden_lab_console (mission * miss) static
Definition at line 383 of file mission_start.cpp.
 {
     Character &player_character = get_player_character();
     // Pick a hidden lab entrance.
     tripoint_abs_omt loc = player_character.global_omt_location();
     loc.z() = -1;
     tripoint_abs_omt place = overmap_buffer.find_closest( loc, "basement_hidden_lab_stairs", 0, false );
     place.z() = -2;  // then go down 1 z-level to place consoles.
     create_lab_consoles( miss, place, "lab", 3, _( "Workstation" ),
                          _( "Download Encryption Routines" ) );
     // Target the lab entrance.
     const tripoint_abs_omt target = mission_util::target_closest_lab_entrance( place, 2, miss );
     mission_util::reveal_road( player_character.global_omt_location(), target, overmap_buffer );
 }
References _, create_lab_consoles(), overmapbuffer::find_closest(), get_player_character(), Creature::global_omt_location(), overmap_buffer, mission_util::reveal_road(), mission_util::target_closest_lab_entrance(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
create_ice_lab_console()
void mission_start::create_ice_lab_console (mission * miss) static
Definition at line 400 of file mission_start.cpp.
 {
     Character &player_character = get_player_character();
     // Pick an ice lab with spaces on z = -4.
     tripoint_abs_omt loc = player_character.global_omt_location();
     loc.z() = -4;
     const tripoint_abs_omt place = overmap_buffer.find_closest( loc, "ice_lab", 0, false );
     create_lab_consoles( miss, place, "ice_lab", 3, _( "Durable Storage Archive" ),
                          _( "Download Archives" ) );
     // Target the lab entrance.
     const tripoint_abs_omt target = mission_util::target_closest_lab_entrance( place, 2, miss );
     mission_util::reveal_road( player_character.global_omt_location(), target, overmap_buffer );
 }
References _, create_lab_consoles(), overmapbuffer::find_closest(), get_player_character(), Creature::global_omt_location(), overmap_buffer, mission_util::reveal_road(), mission_util::target_closest_lab_entrance(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
create_lab_console()
void mission_start::create_lab_console (mission * miss) static
Definition at line 367 of file mission_start.cpp.
 {
     Character &player_character = get_player_character();
     // Pick a lab that has spaces on z = -1: e.g., in hidden labs.
     tripoint_abs_omt loc = player_character.global_omt_location();
     loc.z() = -1;
     const tripoint_abs_omt place = overmap_buffer.find_closest( loc, "lab", 0, false );
     create_lab_consoles( miss, place, "lab", 2, _( "Workstation" ),
                          _( "Download Memory Contents" ) );
     // Target the lab entrance.
     const tripoint_abs_omt target = mission_util::target_closest_lab_entrance( place, 2, miss );
     mission_util::reveal_road( player_character.global_omt_location(), target, overmap_buffer );
 }
References _, create_lab_consoles(), overmapbuffer::find_closest(), get_player_character(), Creature::global_omt_location(), overmap_buffer, mission_util::reveal_road(), mission_util::target_closest_lab_entrance(), and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
find_safety()
void mission_start::find_safety (mission * miss) static
Definition at line 235 of file mission_start.cpp.
 {
     const tripoint_abs_omt place = get_player_character().global_omt_location();
     for( int radius = 0; radius <= 20; radius++ ) {
         for( int dist = 0 - radius; dist <= radius; dist++ ) {
             int offset = rng( 0, 3 ); // Randomizes the direction we check first
             for( int i = 0; i <= 3; i++ ) { // Which direction?
                 tripoint_abs_omt check = place;
                 switch( ( offset + i ) % 4 ) {
                     case 0:
                         check.x() += dist;
                         check.y() -= radius;
                         break;
                     case 1:
                         check.x() += dist;
                         check.y() += radius;
                         break;
                     case 2:
                         check.y() += dist;
                         check.x() -= radius;
                         break;
                     case 3:
                         check.y() += dist;
                         check.x() += radius;
                         break;
                 }
                 if( overmap_buffer.is_safe( check ) ) {
                     miss->target = check;
                     return;
                 }
             }
         }
     }
     // Couldn't find safety; so just set the target to far away
     switch( rng( 0, 3 ) ) {
         case 0:
             miss->target = place + point( -20, -20 );
             break;
         case 1:
             miss->target = place + point( -20, 20 );
             break;
         case 2:
             miss->target = place + point( 20, -20 );
             break;
         case 3:
             miss->target = place + point( 20, 20 );
             break;
     }
 }
References check(), get_player_character(), Creature::global_omt_location(), overmapbuffer::is_safe(), overmap_buffer, point, rng(), and mission::target.
kill_nemesis()
void mission_start::kill_nemesis (mission *) static
Definition at line 58 of file mission_start.cpp.
 {
     // Pick an area for the nemesis to spawn
     // Force z = 0 for overmapbuffer::find_random. (spawning on a rooftop is valid!)
     const tripoint_abs_omt center = { get_player_character().global_omt_location().xy(), 0 };
     tripoint_abs_omt site = overmap::invalid_tripoint;
     static const std::array<float, 3> attempts_multipliers {1.0f, 1.5f, 2.f};
     size_t attempt = 0;
     do {
         if( attempt++ >= attempts_multipliers.size() ) {
             debugmsg( "Failed adding a nemesis mission" );
             return;
         }
         int range = rng( 40, 80 ) * attempts_multipliers[attempt - 1];
         site = overmap_buffer.find_random( center, "field", range, false );
     } while( site == overmap::invalid_tripoint );
     overmap_buffer.add_nemesis( site );
 }
References overmapbuffer::add_nemesis(), center, debugmsg, overmapbuffer::find_random(), get_player_character(), Creature::global_omt_location(), overmap::invalid_tripoint, overmap_buffer, rng(), and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
Referenced by mission::on_creature_death().
place_book()
void mission_start::place_book (mission *) static
Definition at line 285 of file mission_start.cpp.
 {
 }
place_deposit_box()
void mission_start::place_deposit_box (mission * miss) static
Definition at line 193 of file mission_start.cpp.
 {
     npc *p = g->find_npc( miss->npc_id );
     if( p == nullptr ) {
         debugmsg( "could not find mission NPC %d", miss->npc_id.get_value() );
         return;
     }
     // Npc joins you
     p->set_attitude( NPCATT_FOLLOW );
     tripoint_abs_omt site =
         overmap_buffer.find_closest( p->global_omt_location(), "bank", 0, false );
     if( site == overmap::invalid_tripoint ) {
         site = overmap_buffer.find_closest( p->global_omt_location(), "office_tower_1", 0, false );
     }
     if( site == overmap::invalid_tripoint ) {
         site = p->global_omt_location();
         debugmsg( "Couldn't find a place for deposit box" );
     }
     miss->target = site;
     overmap_buffer.reveal( site, 2 );
     tinymap compmap;
     compmap.load( site, false );
     std::vector<tripoint> valid;
     for( const tripoint &p : compmap.points_on_zlevel() ) {
         if( compmap.ter( p ) == ter_t_floor ) {
             for( const tripoint &p2 : compmap.points_in_radius( p, 1 ) ) {
                 if( compmap.ter( p2 ) == ter_t_wall_metal ) {
                     valid.push_back( p );
                     break;
                 }
             }
         }
     }
     const tripoint fallback( rng( 6, SEEX * 2 - 7 ), rng( 6, SEEY * 2 - 7 ), site.z() );
     const tripoint comppoint = random_entry( valid, fallback );
     compmap.spawn_item( comppoint, "safe_box" );
     compmap.save();
 }
References debugmsg, overmapbuffer::find_closest(), g, character_id::get_value(), Creature::global_omt_location(), overmap::invalid_tripoint, tinymap::load(), mission::npc_id, NPCATT_FOLLOW, overmap_buffer, tinymap::points_in_radius(), tinymap::points_on_zlevel(), random_entry(), overmapbuffer::reveal(), rng(), tinymap::save(), SEEX, SEEY, npc::set_attitude(), tinymap::spawn_item(), mission::target, tinymap::ter(), ter_t_floor, ter_t_wall_metal, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
place_npc_software()
void mission_start::place_npc_software (mission * miss) static
Definition at line 140 of file mission_start.cpp.
 {
     npc *dev = g->find_npc( miss->npc_id );
     if( dev == nullptr ) {
         debugmsg( "Couldn't find NPC!  %d", miss->npc_id.get_value() );
         return;
     }
     get_player_character().i_add( item( "usb_drive", calendar::turn_zero ) );
     add_msg( _( "%s gave you a USB drive." ), dev->get_name() );
     std::string type = "house";
     if( dev->myclass == NC_HACKER ) {
         miss->item_id = itype_software_hacking;
     } else if( dev->myclass == NC_DOCTOR ) {
         miss->item_id = itype_software_medical;
         static const std::set<std::string> pharmacies = { "s_pharm", "s_pharm_1" };
         type = random_entry( pharmacies );
         miss->follow_up = mission_MISSION_GET_ZOMBIE_BLOOD_ANAL;
     } else if( dev->myclass == NC_SCIENTIST ) {
         miss->item_id = itype_software_math;
     } else {
         miss->item_id = itype_software_useless;
     }
     tripoint_abs_omt place;
     if( type == "house" ) {
         place = mission_util::random_house_in_closest_city();
     } else {
         place = overmap_buffer.find_closest( dev->global_omt_location(), type, 0, false );
     }
     miss->target = place;
     overmap_buffer.reveal( place, 6 );
     tinymap compmap;
     compmap.load( place, false );
     tripoint comppoint;
     oter_id oter = overmap_buffer.ter( place );
     if( is_ot_match( "house", oter, ot_match_type::prefix ) ||
         is_ot_match( "s_pharm", oter, ot_match_type::prefix ) || oter.id().is_empty() ) {
         comppoint = find_potential_computer_point( compmap );
     }
     compmap.i_clear( comppoint );
     compmap.furn_set( comppoint, furn_f_console );
     computer *tmpcomp = compmap.add_computer( comppoint, string_format( _( "%s's Terminal" ),
                         dev->get_name() ), 0 );
     tmpcomp->set_mission( miss->get_id() );
     tmpcomp->add_option( _( "Download Software" ), COMPACT_DOWNLOAD_SOFTWARE, 0 );
     compmap.save();
 }
References _, tinymap::add_computer(), add_msg(), computer::add_option(), COMPACT_DOWNLOAD_SOFTWARE, debugmsg, overmapbuffer::find_closest(), find_potential_computer_point(), mission::follow_up, furn_f_console, tinymap::furn_set(), g, mission::get_id(), Character::get_name(), get_player_character(), character_id::get_value(), Creature::global_omt_location(), Character::i_add(), tinymap::i_clear(), int_id< T >::id(), string_id< T >::is_empty(), is_ot_match(), item, mission::item_id, itype_software_hacking, itype_software_math, itype_software_medical, itype_software_useless, tinymap::load(), mission_MISSION_GET_ZOMBIE_BLOOD_ANAL, npc::myclass, NC_DOCTOR, NC_HACKER, NC_SCIENTIST, mission::npc_id, overmap_buffer, prefix, random_entry(), mission_util::random_house_in_closest_city(), overmapbuffer::reveal(), tinymap::save(), computer::set_mission(), string_format(), mission::target, overmapbuffer::ter(), calendar::turn_zero, and type.
reveal_refugee_center()
void mission_start::reveal_refugee_center (mission * miss) static
Definition at line 289 of file mission_start.cpp.
 {
     mission_target_params t;
     str_or_var overmap_terrain;
     overmap_terrain.str_val = "refctr_S3e";
     t.overmap_terrain = overmap_terrain;
     str_or_var overmap_special;
     overmap_special.str_val = "evac_center";
     t.overmap_special = overmap_special;
     t.mission_pointer = miss;
     dbl_or_var search_range;
     search_range.min.dbl_val = 0;
     t.search_range = search_range;
     dbl_or_var reveal_radius;
     reveal_radius.min.dbl_val = 1;
     t.reveal_radius = reveal_radius;
     dbl_or_var min_distance;
     min_distance.min.dbl_val = 0;
     t.min_distance = min_distance;
     dialogue d( get_talker_for( get_avatar() ), nullptr );
     std::optional<tripoint_abs_omt> target_pos = mission_util::assign_mission_target( t, d );
     if( !target_pos ) {
         add_msg( _( "You don't know where the address could be" ) );
         return;
     }
     const tripoint_abs_omt source_road = overmap_buffer.find_closest(
             get_player_character().global_omt_location(), "road",
             3, false );
     const tripoint_abs_omt dest_road = overmap_buffer.find_closest( *target_pos, "road", 3, false );
     if( overmap_buffer.reveal_route( source_road, dest_road, 1, true ) ) {
         //reset the mission target to the refugee center entrance and reveal path from the road
         str_or_var overmap_terrain;
         overmap_terrain.str_val = "refctr_S3e";
         t.overmap_terrain = overmap_terrain;
         dbl_or_var reveal_radius;
         reveal_radius.min.dbl_val = 3;
         t.reveal_radius = reveal_radius;
         target_pos = mission_util::assign_mission_target( t, d );
         const tripoint_abs_omt dest_refugee_center = overmap_buffer.find_closest( *target_pos,
                 "evac_center_18", 1, false );
         overmap_buffer.reveal_route( dest_road, dest_refugee_center, 1, false );
         add_msg( _( "You mark the refugee center and the road that leads to it" ) );
     } else {
         add_msg( _( "You mark the refugee center, but you have no idea how to get there by road" ) );
     }
 }
References _, add_msg(), mission_util::assign_mission_target(), dbl_or_var_part::dbl_val, overmapbuffer::find_closest(), get_avatar(), get_player_character(), get_talker_for(), dbl_or_var::min, mission_target_params::min_distance, mission_target_params::mission_pointer, overmap_buffer, overmap_special, mission_target_params::overmap_special, mission_target_params::overmap_terrain, mission_target_params::reveal_radius, overmapbuffer::reveal_route(), and mission_target_params::search_range.
standard()
void mission_start::standard (mission *) static
Definition at line 54 of file mission_start.cpp.
 {
 }
The documentation for this struct was generated from the following files:
src/mission.h
src/mission_start.cpp