Cataclysm DDA: use_function Struct Reference
use_function Struct Reference
#include <iuse.h>
Public Member Functions
use_function ()=default
use_function (const std::string &type, use_function_pointer f)
use_function (std::unique_ptr< iuse_actor > f)
std::optional< int > call (Character *, item &, const tripoint &) const
ret_val< void > can_call (const Character &, const item &, const tripoint &pos) const
iuse_actor * get_actor_ptr ()
const iuse_actor * get_actor_ptr () const
operator bool () const
std::string get_type () const
std::string get_name () const
std::string get_description () const
void dump_info (const item &, std::vector< iteminfo > &) const
Protected Attributes
cata::clone_ptr< iuse_actor > actor
Detailed Description
Definition at line 302 of file iuse.h.
Constructor & Destructor Documentation
use_function() [1/3]
use_function::use_function () default
use_function() [2/3]
use_function::use_function (const std::string & type, use_function_pointer f)
Definition at line 1676 of file item_factory.cpp.
     : use_function( std::make_unique<iuse_function_wrapper>( type, f ) ) {}
use_function() [3/3]
use_function::use_function (std::unique_ptr< iuse_actor > f) inline explicit
Definition at line 309 of file iuse.h.
 : actor( std::move( f ) ) {}
Member Function Documentation
call()
std::optional< int > use_function::call (Character * p, item & it, const tripoint & pos) const
Definition at line 8922 of file iuse.cpp.
 {
     return actor->use( p, it, pos );
 }
References math_opers::pos().
Referenced by iuse::ebookread(), iuse::einktabletpc(), npc::heal_self(), item::on_drop(), veh_app_interact::plug(), item::process_internal(), read(), and avatar::read().
can_call()
ret_val< void > use_function::can_call (const Character & p, const item & it, const tripoint & pos) const
Definition at line 8908 of file iuse.cpp.
 {
     if( actor == nullptr ) {
         return ret_val<void>::make_failure( _( "You can't do anything interesting with your %s." ),
                                             it.tname() );
     } else if( it.is_broken() ) {
         return ret_val<void>::make_failure( _( "Your %s is broken and won't activate." ),
                                             it.tname() );
     }
     return actor->can_use( p, it, pos );
 }
References _, item::is_broken(), ret_val< T >::make_failure(), math_opers::pos(), and item::tname().
dump_info()
void use_function::dump_info (const item & it, std::vector< iteminfo > & dump) const
Returns
Used by item::info to get description of the actor
Definition at line 8901 of file iuse.cpp.
 {
     if( actor != nullptr ) {
         actor->info( it, dump );
     }
 }
get_actor_ptr() [1/2]
iuse_actor* use_function::get_actor_ptr () inline
Definition at line 314 of file iuse.h.
{
             return actor.get();
         }
References actor, and cata::clone_ptr< T >::get().
Referenced by add_firestarter(), map::add_item(), game::butcher(), Character::can_eat(), item::can_holster(), item::final_info(), Item_factory::finalize_pre(), firstaid_activity_actor::finish(), longsalvage_activity_actor::finish(), iexamine::fireplace(), Character::get_consume_time(), activatable_inventory_preset::get_denial(), grenade_helper(), iuse_transform::info(), mattack::kamikaze(), item::link_to(), game_menus::inv::molle_attach(), game::npc_menu(), repair_item_finish(), game_menus::inv::saw_barrel(), game_menus::inv::saw_stock(), activity_handlers::start_fire_do_turn(), activity_handlers::start_fire_finish(), item::update_link_traits(), and Item_factory::usage_from_object().
get_actor_ptr() [2/2]
const iuse_actor* use_function::get_actor_ptr () const inline
Definition at line 318 of file iuse.h.
{
             return actor.get();
         }
References actor, and cata::clone_ptr< T >::get().
get_description()
std::string use_function::get_description () const
Returns
See iuse_actor::get_description
Definition at line 421 of file item_action.cpp.
 {
     if( actor ) {
         return actor->get_description();
     } else {
         return errstring;
     }
 }
References actor, errstring(), and iuse_actor::get_description().
get_name()
std::string use_function::get_name () const
Returns
See iuse_actor::get_name
Definition at line 412 of file item_action.cpp.
 {
     if( actor ) {
         return actor->get_name();
     } else {
         return errstring;
     }
 }
References actor, errstring(), and iuse_actor::get_name().
get_type()
std::string use_function::get_type () const
Returns
See iuse_actor::type
Definition at line 383 of file item_action.cpp.
 {
     if( actor ) {
         return actor->type;
     } else {
         return errstring;
     }
 }
References actor, errstring(), and iuse_actor::type.
operator bool()
use_function::operator bool () const inline explicit
Definition at line 322 of file iuse.h.
{
             return actor != nullptr;
         }
References actor.
Member Data Documentation
actor
cata::clone_ptr<iuse_actor> use_function::actor protected
Definition at line 304 of file iuse.h.
Referenced by get_actor_ptr(), get_description(), get_name(), get_type(), and operator bool().
The documentation for this struct was generated from the following files:
src/iuse.h
src/item_action.cpp
src/item_factory.cpp
src/iuse.cpp