Cataclysm DDA: effect_scaling Struct Reference
effect_scaling Struct Reference
#include <bonuses.h>
Public Member Functions
float get (const Character &u) const
effect_scaling (const JsonObject &obj)
Public Attributes
scaling_stat stat
float scale
Detailed Description
Definition at line 80 of file bonuses.h.
Constructor & Destructor Documentation
effect_scaling()
effect_scaling::effect_scaling (const JsonObject & obj) explicit
Definition at line 158 of file bonuses.cpp.
 {
     if( obj.has_string( "scaling-stat" ) ) {
         stat = scaling_stat_from_string( obj.get_string( "scaling-stat" ) );
     } else {
         stat = STAT_NULL;
     }
     scale = obj.get_float( "scale" );
 }
References JsonObject::get_float(), JsonObject::get_string(), JsonObject::has_string(), scale, scaling_stat_from_string(), stat, and STAT_NULL.
Member Function Documentation
get()
float effect_scaling::get (const Character & u) const
Definition at line 320 of file bonuses.cpp.
 {
     float bonus = 0.0f;
     switch( stat ) {
         case STAT_STR:
             bonus = scale * u.get_str();
             break;
         case STAT_DEX:
             bonus = scale * u.get_dex();
             break;
         case STAT_INT:
             bonus = scale * u.get_int();
             break;
         case STAT_PER:
             bonus = scale * u.get_per();
             break;
         case SKILL_BASHING:
             bonus = scale * u.get_skill_level( skill_bashing );
             break;
         case SKILL_CUTTING:
             bonus = scale * u.get_skill_level( skill_cutting );
             break;
         case SKILL_DODGE:
             bonus = scale * u.get_skill_level( skill_dodge );
             break;
         case SKILL_MELEE:
             bonus = scale * u.get_skill_level( skill_melee );
             break;
         case SKILL_STABBING:
             bonus = scale * u.get_skill_level( skill_stabbing );
             break;
         case SKILL_SWIMMING:
             bonus = scale * u.get_skill_level( skill_swimming );
             break;
         case SKILL_UNARMED:
             bonus = scale * u.get_skill_level( skill_unarmed );
             break;
         case SKILL_GUN:
             bonus = scale * u.get_skill_level( skill_gun );
             break;
         case SKILL_PISTOL:
             bonus = scale * u.get_skill_level( skill_pistol );
             break;
         case SKILL_RIFLE:
             bonus = scale * u.get_skill_level( skill_rifle );
             break;
         case SKILL_SHOTGUN:
             bonus = scale * u.get_skill_level( skill_shotgun );
             break;
         case SKILL_SMG:
             bonus = scale * u.get_skill_level( skill_smg );
             break;
         case SKILL_ARCHERY:
             bonus = scale * u.get_skill_level( skill_archery );
             break;
         case SKILL_THROW:
             bonus = scale * u.get_skill_level( skill_throw );
             break;
         case SKILL_LAUNCHER:
             bonus = scale * u.get_skill_level( skill_launcher );
             break;
         case SKILL_DRIVE:
             bonus = scale * u.get_skill_level( skill_drive );
             break;
         case SKILL_FIRSTAID:
             bonus = scale * u.get_skill_level( skill_firstaid );
             break;
         case SKILL_SPELLCRAFT:
             bonus = scale * u.get_skill_level( skill_spellcraft );
             break;
         case STAT_NULL:
             bonus = scale;
         case NUM_STATS:
             break;
     }
     return bonus;
 }
References NUM_STATS, scale, skill_archery, SKILL_ARCHERY, skill_bashing, SKILL_BASHING, skill_cutting, SKILL_CUTTING, skill_dodge, SKILL_DODGE, skill_drive, SKILL_DRIVE, skill_firstaid, SKILL_FIRSTAID, skill_gun, SKILL_GUN, skill_launcher, SKILL_LAUNCHER, skill_melee, SKILL_MELEE, skill_pistol, SKILL_PISTOL, skill_rifle, SKILL_RIFLE, skill_shotgun, SKILL_SHOTGUN, skill_smg, SKILL_SMG, skill_spellcraft, SKILL_SPELLCRAFT, skill_stabbing, SKILL_STABBING, skill_swimming, SKILL_SWIMMING, skill_throw, SKILL_THROW, skill_unarmed, SKILL_UNARMED, stat, STAT_DEX, STAT_INT, STAT_NULL, STAT_PER, STAT_STR, and u.
Referenced by bonus_container::get_flat(), and bonus_container::get_mult().
Member Data Documentation
scale
float effect_scaling::scale
Definition at line 82 of file bonuses.h.
Referenced by effect_scaling(), get(), and bonus_container::get_description().
stat
scaling_stat effect_scaling::stat
Definition at line 81 of file bonuses.h.
Referenced by effect_scaling(), get(), and bonus_container::get_description().
The documentation for this struct was generated from the following files:
src/bonuses.h
src/bonuses.cpp