Cataclysm DDA: mission_type Struct Reference
mission_type Struct Reference
#include <mission.h>
Public Member Functions
mission_type ()=default
mission create (const character_id &npc_id) const
bool test_goal_condition (struct dialogue &d) const
bool parse_funcs (const JsonObject &jo, std::function< void(mission *)> &phase_func)
void load (const JsonObject &jo, const std::string &src)
std::string tname () const
Returns the translated name.
Static Public Member Functions
static const mission_type * get (const mission_type_id &id)
Get the mission_type object of the given id.
static mission_type_id from_legacy (int old_id)
Converts the legacy int id to a string_id.
static mission_type_id get_random_id (mission_origin origin, const tripoint_abs_omt &p)
Returns a random id of a mission type that can be started at the defined origin around tripoint p, see mission_start.
static const std::vector< mission_type > & get_all ()
Get all mission types at once.
static void reset ()
static void load_mission_type (const JsonObject &jo, const std::string &src)
static void finalize ()
static void check_consistency ()
Public Attributes
mission_type_id id = mission_type_id("MISSION_NULL")
std::vector< std::pair< mission_type_id, mod_id > > src
bool was_loaded = false
translation description
mission_goal goal = mission_goal::MGOAL_NULL
int difficulty = 0
int value = 0
time_duration deadline_low = 0_turns
time_duration deadline_high = 0_turns
bool urgent = false
bool has_generic_rewards = true
talk_effect_fun_t::likely_rewards_t likely_rewards
std::vector< mission_origin > origins
itype_id item_id = itype_id::NULL_ID()
item_group_id group_id = item_group_id::NULL_ID()
itype_id container_id = itype_id::NULL_ID()
bool remove_container = false
bool invisible_on_complete = false
itype_id empty_container = itype_id::NULL_ID()
int item_count = 1
npc_class_id recruit_class = npc_class_id("NC_NONE")
character_id target_npc_id
mtype_id monster_type = mtype_id::NULL_ID()
species_id monster_species
int monster_kill_goal = -1
string_id< oter_type_t > target_id
mission_type_id follow_up = mission_type_id("MISSION_NULL")
std::function< bool(const tripoint_abs_omt &)> place = mission_place::always
std::function< void(mission *)> start = mission_start::standard
std::function< void(mission *)> end = mission_end::standard
std::function< void(mission *)> fail = mission_fail::standard
std::map< std::string, translation > dialogue
std::function< bool(struct dialogue &)> goal_condition
Private Attributes
translation name = to_translation("Bugged mission type")
Detailed Description
Definition at line 178 of file mission.h.
Constructor & Destructor Documentation
mission_type()
mission_type::mission_type () default
Member Function Documentation
check_consistency()
void mission_type::check_consistency () static
Definition at line 427 of file missiondef.cpp.
 {
     for( const mission_type &m : get_all() ) {
         if( !m.item_id.is_empty() && !item::type_is_defined( m.item_id ) ) {
             debugmsg( "Mission %s has undefined item id %s", m.id.c_str(), m.item_id.c_str() );
         }
     }
 }
References debugmsg, get_all(), and item::type_is_defined().
Referenced by DynamicDataLoader::check_consistency().
create()
mission mission_type::create (const character_id & npc_id) const
Definition at line 49 of file mission.cpp.
 {
     mission ret;
     ret.uid = g->assign_mission_id();
     ret.type = this;
     ret.npc_id = npc_id;
     ret.item_id = item_id;
     ret.item_count = item_count;
     ret.value = value;
     ret.follow_up = follow_up;
     ret.monster_species = monster_species;
     ret.monster_type = monster_type;
     ret.monster_kill_goal = monster_kill_goal;
     if( deadline_low != 0_turns || deadline_high != 0_turns ) {
         ret.deadline = calendar::turn + rng( deadline_low, deadline_high );
     } else {
         ret.deadline = calendar::turn_zero;
     }
     return ret;
 }
References deadline_high, deadline_low, follow_up, g, item_count, item_id, monster_kill_goal, monster_species, monster_type, cata::hash64_detail::ret, rng(), calendar::turn, calendar::turn_zero, and value.
Referenced by mission::reserve_new().
finalize()
void mission_type::finalize () static
Definition at line 422 of file missiondef.cpp.
 {
     DynamicDataLoader::get_instance().load_deferred( deferred );
 }
References deferred, DynamicDataLoader::get_instance(), and DynamicDataLoader::load_deferred().
Referenced by DynamicDataLoader::finalize_loaded_data().
from_legacy()
mission_type_id mission_type::from_legacy (int old_id) static
Converts the legacy int id to a string_id.
Definition at line 436 of file missiondef.cpp.
 {
     static const std::vector<mission_type_id> old_id_vec = {{
             mission_MISSION_NULL,
             mission_MISSION_GET_ANTIBIOTICS,
             mission_MISSION_GET_SOFTWARE,
             mission_MISSION_GET_ZOMBIE_BLOOD_ANAL,
             mission_MISSION_RESCUE_DOG,
             mission_MISSION_KILL_ZOMBIE_MOM,
             mission_MISSION_REACH_SAFETY,
             mission_MISSION_GET_FLAG,
             mission_MISSION_GET_BLACK_BOX,
             mission_MISSION_GET_BLACK_BOX_TRANSCRIPT,
             mission_MISSION_EXPLORE_SARCOPHAGUS,
             mission_MISSION_GET_RELIC,
             mission_MISSION_RECOVER_PRIEST_DIARY,
             mission_MISSION_INVESTIGATE_CULT,
             mission_MISSION_INVESTIGATE_PRISON_VISIONARY,
             mission_MISSION_GET_RECORD_WEATHER,
             mission_MISSION_GET_RECORD_PATIENT,
             mission_MISSION_REACH_FEMA_CAMP,
             mission_MISSION_REACH_FARM_HOUSE,
             mission_MISSION_GET_RECORD_ACCOUNTING,
             mission_MISSION_GET_SAFE_BOX,
             mission_MISSION_GET_DEPUTY_BADGE,
             mission_MISSION_KILL_JABBERWOCK,
             mission_MISSION_KILL_100_Z,
             mission_MISSION_KILL_HORDE_MASTER,
             mission_MISSION_KILL_NEMESIS,
             mission_MISSION_RECRUIT_TRACKER,
             mission_MISSION_JOIN_TRACKER,
             mission_MISSION_FREE_MERCHANTS_EVAC_1,
             mission_MISSION_FREE_MERCHANTS_EVAC_2,
             mission_MISSION_FREE_MERCHANTS_EVAC_4,
             mission_MISSION_OLD_GUARD_REP_1,
             mission_MISSION_OLD_GUARD_REP_2,
             mission_MISSION_OLD_GUARD_REP_3,
             mission_MISSION_OLD_GUARD_REP_4,
             mission_MISSION_OLD_GUARD_NEC_1,
             mission_MISSION_OLD_GUARD_NEC_2,
             mission_MISSION_OLD_GUARD_NEC_COMMO_1,
             mission_MISSION_OLD_GUARD_NEC_COMMO_2,
             mission_MISSION_OLD_GUARD_NEC_COMMO_3,
             mission_MISSION_OLD_GUARD_NEC_COMMO_4,
             mission_MISSION_RANCH_FOREMAN_1,
             mission_MISSION_RANCH_FOREMAN_2,
             mission_MISSION_RANCH_FOREMAN_3,
             mission_MISSION_RANCH_FOREMAN_4,
             mission_MISSION_RANCH_FOREMAN_5,
             mission_MISSION_RANCH_FOREMAN_6,
             mission_MISSION_RANCH_FOREMAN_7,
             mission_MISSION_RANCH_FOREMAN_8,
             mission_MISSION_RANCH_FOREMAN_9,
             mission_MISSION_RANCH_FOREMAN_10,
             mission_MISSION_RANCH_FOREMAN_11,
             mission_MISSION_RANCH_FOREMAN_12,
             mission_MISSION_RANCH_FOREMAN_13,
             mission_MISSION_RANCH_FOREMAN_14,
             mission_MISSION_RANCH_FOREMAN_15,
             mission_MISSION_RANCH_FOREMAN_16,
             mission_MISSION_RANCH_FOREMAN_17,
             mission_MISSION_RANCH_NURSE_1,
             mission_MISSION_RANCH_NURSE_2,
             mission_MISSION_RANCH_NURSE_3,
             mission_MISSION_RANCH_NURSE_4,
             mission_MISSION_RANCH_NURSE_5,
             mission_MISSION_RANCH_NURSE_6,
             mission_MISSION_RANCH_NURSE_7,
             mission_MISSION_RANCH_NURSE_8,
             mission_MISSION_RANCH_NURSE_9,
             mission_MISSION_RANCH_NURSE_10,
             mission_MISSION_RANCH_NURSE_11,
             mission_MISSION_RANCH_SCAVENGER_1,
             mission_MISSION_RANCH_SCAVENGER_2,
             mission_MISSION_RANCH_SCAVENGER_3,
             mission_MISSION_RANCH_SCAVENGER_4,
             mission_MISSION_RANCH_BARTENDER_1,
             mission_MISSION_RANCH_BARTENDER_2,
             mission_MISSION_RANCH_BARTENDER_3,
             mission_MISSION_RANCH_BARTENDER_4,
             mission_MISSION_RANCH_BARTENDER_5,
             mission_MISSION_FREE_MERCHANTS_EVAC_3,
             // This is to help with the bugged find book mission
             mission_MISSION_NULL
         }
     };
     if( old_id >= 0 && old_id < static_cast<int>( old_id_vec.size() ) ) {
         return old_id_vec[ old_id ];
     }
     debugmsg( "Invalid legacy mission id: %d", old_id );
     return mission_MISSION_NULL;
 }
References debugmsg, mission_MISSION_EXPLORE_SARCOPHAGUS, mission_MISSION_FREE_MERCHANTS_EVAC_1, mission_MISSION_FREE_MERCHANTS_EVAC_2, mission_MISSION_FREE_MERCHANTS_EVAC_3, mission_MISSION_FREE_MERCHANTS_EVAC_4, mission_MISSION_GET_ANTIBIOTICS, mission_MISSION_GET_BLACK_BOX, mission_MISSION_GET_BLACK_BOX_TRANSCRIPT, mission_MISSION_GET_DEPUTY_BADGE, mission_MISSION_GET_FLAG, mission_MISSION_GET_RECORD_ACCOUNTING, mission_MISSION_GET_RECORD_PATIENT, mission_MISSION_GET_RECORD_WEATHER, mission_MISSION_GET_RELIC, mission_MISSION_GET_SAFE_BOX, mission_MISSION_GET_SOFTWARE, mission_MISSION_GET_ZOMBIE_BLOOD_ANAL, mission_MISSION_INVESTIGATE_CULT, mission_MISSION_INVESTIGATE_PRISON_VISIONARY, mission_MISSION_JOIN_TRACKER, mission_MISSION_KILL_100_Z, mission_MISSION_KILL_HORDE_MASTER, mission_MISSION_KILL_JABBERWOCK, mission_MISSION_KILL_NEMESIS, mission_MISSION_KILL_ZOMBIE_MOM, mission_MISSION_NULL, mission_MISSION_OLD_GUARD_NEC_1, mission_MISSION_OLD_GUARD_NEC_2, mission_MISSION_OLD_GUARD_NEC_COMMO_1, mission_MISSION_OLD_GUARD_NEC_COMMO_2, mission_MISSION_OLD_GUARD_NEC_COMMO_3, mission_MISSION_OLD_GUARD_NEC_COMMO_4, mission_MISSION_OLD_GUARD_REP_1, mission_MISSION_OLD_GUARD_REP_2, mission_MISSION_OLD_GUARD_REP_3, mission_MISSION_OLD_GUARD_REP_4, mission_MISSION_RANCH_BARTENDER_1, mission_MISSION_RANCH_BARTENDER_2, mission_MISSION_RANCH_BARTENDER_3, mission_MISSION_RANCH_BARTENDER_4, mission_MISSION_RANCH_BARTENDER_5, mission_MISSION_RANCH_FOREMAN_1, mission_MISSION_RANCH_FOREMAN_10, mission_MISSION_RANCH_FOREMAN_11, mission_MISSION_RANCH_FOREMAN_12, mission_MISSION_RANCH_FOREMAN_13, mission_MISSION_RANCH_FOREMAN_14, mission_MISSION_RANCH_FOREMAN_15, mission_MISSION_RANCH_FOREMAN_16, mission_MISSION_RANCH_FOREMAN_17, mission_MISSION_RANCH_FOREMAN_2, mission_MISSION_RANCH_FOREMAN_3, mission_MISSION_RANCH_FOREMAN_4, mission_MISSION_RANCH_FOREMAN_5, mission_MISSION_RANCH_FOREMAN_6, mission_MISSION_RANCH_FOREMAN_7, mission_MISSION_RANCH_FOREMAN_8, mission_MISSION_RANCH_FOREMAN_9, mission_MISSION_RANCH_NURSE_1, mission_MISSION_RANCH_NURSE_10, mission_MISSION_RANCH_NURSE_11, mission_MISSION_RANCH_NURSE_2, mission_MISSION_RANCH_NURSE_3, mission_MISSION_RANCH_NURSE_4, mission_MISSION_RANCH_NURSE_5, mission_MISSION_RANCH_NURSE_6, mission_MISSION_RANCH_NURSE_7, mission_MISSION_RANCH_NURSE_8, mission_MISSION_RANCH_NURSE_9, mission_MISSION_RANCH_SCAVENGER_1, mission_MISSION_RANCH_SCAVENGER_2, mission_MISSION_RANCH_SCAVENGER_3, mission_MISSION_RANCH_SCAVENGER_4, mission_MISSION_REACH_FARM_HOUSE, mission_MISSION_REACH_FEMA_CAMP, mission_MISSION_REACH_SAFETY, mission_MISSION_RECOVER_PRIEST_DIARY, mission_MISSION_RECRUIT_TRACKER, and mission_MISSION_RESCUE_DOG.
Referenced by mission::deserialize().
get()
const mission_type * mission_type::get (const mission_type_id & id) static
Get the mission_type object of the given id.
Returns null if the input is invalid!
Definition at line 531 of file missiondef.cpp.
 {
     if( id.is_null() ) {
         return nullptr;
     }
     return &id.obj();
 }
Referenced by assemble_hobby_details(), assemble_profession_details(), assemble_scenario_details(), and mission::reserve_new().
get_all()
const std::vector< mission_type > & mission_type::get_all () static
Get all mission types at once.
Definition at line 540 of file missiondef.cpp.
 {
     return mission_type_factory.get_all();
 }
References mission_type_factory.
Referenced by debug_menu::character_edit_menu(), check_consistency(), mission::deserialize(), get_random_id(), and mission::get_type().
get_random_id()
mission_type_id mission_type::get_random_id (mission_origin origin, const tripoint_abs_omt & p) static
Returns a random id of a mission type that can be started at the defined origin around tripoint p, see mission_start.
Returns MISSION_NULL if no suitable type could be found.
Definition at line 545 of file missiondef.cpp.
 {
     std::vector<mission_type_id> valid;
     for( const mission_type &t : get_all() ) {
         if( std::find( t.origins.begin(), t.origins.end(), origin ) == t.origins.end() ) {
             continue;
         }
         if( t.place( p ) ) {
             valid.push_back( t.id );
         }
     }
     return random_entry( valid, mission_type_id::NULL_ID() );
 }
References get_all(), string_id< mission_type >::NULL_ID(), and random_entry().
Referenced by mission::reserve_random().
load()
void mission_type::load (const JsonObject & jo, const std::string & src)
Definition at line 316 of file missiondef.cpp.
 {
     const bool strict = src == "dda";
     mandatory( jo, was_loaded, "name", name );
     mandatory( jo, was_loaded, "difficulty", difficulty );
     mandatory( jo, was_loaded, "value", value );
     if( jo.has_member( "origins" ) ) {
         origins.clear();
         for( const std::string &m : jo.get_tags( "origins" ) ) {
             origins.emplace_back( io::string_to_enum<mission_origin>( m ) );
         }
     }
     if( std::any_of( origins.begin(), origins.end(), []( mission_origin origin ) {
     return origin == ORIGIN_ANY_NPC || origin == ORIGIN_OPENER_NPC || origin == ORIGIN_SECONDARY;
 } ) ) {
         JsonObject djo = jo.get_object( "dialogue" );
         // TODO: There should be a cleaner way to do it
         mandatory( djo, was_loaded, "describe", dialogue[ "describe" ] );
         mandatory( djo, was_loaded, "offer", dialogue[ "offer" ] );
         mandatory( djo, was_loaded, "accepted", dialogue[ "accepted" ] );
         mandatory( djo, was_loaded, "rejected", dialogue[ "rejected" ] );
         mandatory( djo, was_loaded, "advice", dialogue[ "advice" ] );
         mandatory( djo, was_loaded, "inquire", dialogue[ "inquire" ] );
         mandatory( djo, was_loaded, "success", dialogue[ "success" ] );
         mandatory( djo, was_loaded, "success_lie", dialogue[ "success_lie" ] );
         mandatory( djo, was_loaded, "failure", dialogue[ "failure" ] );
     }
     optional( jo, was_loaded, "description", description );
     optional( jo, was_loaded, "urgent", urgent );
     optional( jo, was_loaded, "item", item_id );
     optional( jo, was_loaded, "item_group", group_id );
     optional( jo, was_loaded, "count", item_count, 1 );
     optional( jo, was_loaded, "required_container", container_id );
     optional( jo, was_loaded, "remove_container", remove_container );
     //intended for situations where closed and open container are different
     optional( jo, was_loaded, "empty_container", empty_container );
     optional( jo, was_loaded, "has_generic_rewards", has_generic_rewards, true );
     goal = jo.get_enum_value<decltype( goal )>( "goal" );
     assign_function( jo, "place", place, tripoint_function_map );
     const auto parse_phase = [&]( const std::string & phase,
     std::function<void( mission * )> &phase_func ) {
         if( jo.has_string( phase ) ) {
             assign_function( jo, phase, phase_func, mission_function_map );
         } else if( jo.has_member( phase ) ) {
             JsonObject j_start = jo.get_object( phase );
             if( !parse_funcs( j_start, phase_func ) ) {
                 deferred.emplace_back( jo, src );
                 jo.allow_omitted_members();
                 j_start.allow_omitted_members();
                 return false;
             }
         }
         return true;
     };
     if( !parse_phase( "start", start ) ) {
         return;
     }
     if( !parse_phase( "end", end ) ) {
         return;
     }
     if( !parse_phase( "fail", fail ) ) {
         return;
     }
     assign( jo, "deadline_low", deadline_low, false, 1_days );
     assign( jo, "deadline_high", deadline_high, false, 1_days );
     if( jo.has_member( "followup" ) ) {
         follow_up = mission_type_id( jo.get_string( "followup" ) );
     }
     if( jo.has_member( "monster_species" ) ) {
         monster_species = species_id( jo.get_string( "monster_species" ) );
     }
     if( jo.has_member( "monster_type" ) ) {
         monster_type = mtype_id( jo.get_string( "monster_type" ) );
     }
     if( jo.has_member( "monster_kill_goal" ) ) {
         monster_kill_goal = jo.get_int( "monster_kill_goal" );
     }
     assign( jo, "destination", target_id, strict );
     if( jo.has_member( "goal_condition" ) ) {
         read_condition( jo, "goal_condition", goal_condition, true );
     }
     optional( jo, was_loaded, "invisible_on_complete", invisible_on_complete, false );
 }
References JsonObject::allow_omitted_members(), assign(), assign_function(), container_id, deadline_high, deadline_low, deferred, description, difficulty, empty_container, end, fail, follow_up, JsonObject::get_enum_value(), JsonObject::get_int(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::get_tags(), goal, goal_condition, group_id, has_generic_rewards, JsonObject::has_member(), JsonObject::has_string(), invisible_on_complete, item_count, item_id, mandatory, mission_function_map, monster_kill_goal, monster_species, monster_type, mtype_id, name, optional(), origins, parse_funcs(), place, read_condition(), remove_container, species_id, src, start, strict, target_id, tripoint_function_map, urgent, value, and was_loaded.
load_mission_type()
void mission_type::load_mission_type (const JsonObject & jo, const std::string & src) static
Definition at line 286 of file missiondef.cpp.
 {
     mission_type_factory.load( jo, src );
 }
References mission_type_factory, and src.
Referenced by DynamicDataLoader::initialize().
parse_funcs()
bool mission_type::parse_funcs (const JsonObject & jo, std::function< void(mission *)> & phase_func)
Definition at line 529 of file mission_util.cpp.
 {
     std::vector<std::function<void( mission *miss )>> funcs;
     if( !mission_util::load_funcs( jo, funcs ) ) {
         return false;
     }
     /* this is a kind of gross hijack of the dialogue responses effect system, but I don't want to
      * write that code in two places so here it goes.
      */
     talk_effect_t talk_effects;
     talk_effects.load_effect( jo, "effect" );
     phase_func = [ funcs, talk_effects ]( mission * miss ) {
         npc *beta_npc = g->find_npc( miss->get_npc_id() );
         ::dialogue d( get_talker_for( get_avatar() ),
                       beta_npc == nullptr ? nullptr : get_talker_for( beta_npc ) );
         for( const talk_effect_fun_t &effect : talk_effects.effects ) {
             effect( d );
         }
         for( const auto &mission_function : funcs ) {
             mission_function( miss );
         }
     };
     for( talk_effect_fun_t &effect : talk_effects.effects ) {
         talk_effect_fun_t::likely_rewards_t rewards = effect.get_likely_rewards();
         if( !rewards.empty() ) {
             likely_rewards.insert( likely_rewards.end(), rewards.begin(), rewards.end() );
         }
     }
     return true;
 }
References talk_effect_t::effects, g, get_avatar(), mission::get_npc_id(), get_talker_for(), likely_rewards, talk_effect_t::load_effect(), and mission_util::load_funcs().
Referenced by load().
reset()
void mission_type::reset () static
Definition at line 293 of file missiondef.cpp.
 {
     mission_type_factory.reset();
     for( std::pair<JsonObject, std::string> &deferred_json : deferred ) {
         deferred_json.first.allow_omitted_members();
     }
     deferred.clear();
 }
References deferred, and mission_type_factory.
Referenced by DynamicDataLoader::unload_data().
test_goal_condition()
bool mission_type::test_goal_condition (struct dialogue & d) const
Definition at line 414 of file missiondef.cpp.
 {
     if( goal_condition ) {
         return goal_condition( d );
     }
     return true;
 }
References goal_condition.
Referenced by mission::is_complete().
tname()
std::string mission_type::tname () const
Returns the translated name.
Definition at line 72 of file mission.cpp.
 {
     return name.translated();
 }
References name, and translation::translated().
Referenced by assemble_hobby_details(), assemble_profession_details(), assemble_scenario_details(), dialogue::gen_responses(), and mission::name().
Member Data Documentation
container_id
itype_id mission_type::container_id = itype_id::NULL_ID()
Definition at line 210 of file mission.h.
Referenced by mission::is_complete(), load(), and mission::wrap_up().
deadline_high
time_duration mission_type::deadline_high = 0_turns
Definition at line 197 of file mission.h.
Referenced by mission::assign(), create(), and load().
deadline_low
time_duration mission_type::deadline_low = 0_turns
Definition at line 196 of file mission.h.
Referenced by mission::assign(), create(), and load().
description
translation mission_type::description
Definition at line 188 of file mission.h.
Referenced by mission::get_description(), and load().
dialogue
std::map<std::string, translation> mission_type::dialogue
Definition at line 228 of file mission.h.
Referenced by mission::dialogue_for_topic().
difficulty
int mission_type::difficulty = 0
Definition at line 192 of file mission.h.
Referenced by load().
empty_container
itype_id mission_type::empty_container = itype_id::NULL_ID()
Definition at line 213 of file mission.h.
Referenced by load(), and mission::wrap_up().
end
std::function<void(mission *)> mission_type::end = mission_end::standard
Definition at line 225 of file mission.h.
Referenced by load(), and mission::wrap_up().
fail
std::function<void(mission *)> mission_type::fail = mission_fail::standard
Definition at line 226 of file mission.h.
Referenced by mission::fail(), and load().
follow_up
mission_type_id mission_type::follow_up = mission_type_id("MISSION_NULL")
Definition at line 221 of file mission.h.
Referenced by create(), and load().
goal
mission_goal mission_type::goal = mission_goal::MGOAL_NULL
Definition at line 190 of file mission.h.
Referenced by mission::assign(), conditional_fun::anonymous_namespace{condition.cpp}::f_mission_goal(), mission::is_complete(), load(), mission::on_creature_death(), mission::on_creature_fusion(), mission::on_talk_with_npc(), npc::regen_ai_cache(), map::spawn_monsters_submap(), mission::step_complete(), and mission::wrap_up().
goal_condition
std::function<bool(struct dialogue &)> mission_type::goal_condition
Definition at line 231 of file mission.h.
Referenced by load(), and test_goal_condition().
group_id
item_group_id mission_type::group_id = item_group_id::NULL_ID()
Definition at line 209 of file mission.h.
Referenced by mission::is_complete(), load(), and mission::wrap_up().
has_generic_rewards
bool mission_type::has_generic_rewards = true
Definition at line 201 of file mission.h.
Referenced by mission::has_generic_rewards(), and load().
id
mission_type_id mission_type::id = mission_type_id("MISSION_NULL")
Definition at line 181 of file mission.h.
Referenced by computer_session::action_emerg_ref_center(), debug_menu::mission_debug::describe(), mission::dialogue_for_topic(), debug_menu::mission_debug::edit_npc(), debug_menu::mission_debug::edit_player(), mission::is_complete(), and mission::mission_id().
invisible_on_complete
bool mission_type::invisible_on_complete = false
Definition at line 212 of file mission.h.
Referenced by load(), and avatar::on_mission_finished().
item_count
int mission_type::item_count = 1
Definition at line 214 of file mission.h.
Referenced by create(), mission::is_complete(), load(), and mission::wrap_up().
item_id
itype_id mission_type::item_id = itype_id::NULL_ID()
Definition at line 208 of file mission.h.
Referenced by create(), mission::is_complete(), load(), and mission::wrap_up().
likely_rewards
talk_effect_fun_t::likely_rewards_t mission_type::likely_rewards
Definition at line 204 of file mission.h.
Referenced by mission::get_likely_rewards(), and parse_funcs().
monster_kill_goal
int mission_type::monster_kill_goal = -1
Definition at line 219 of file mission.h.
Referenced by create(), load(), and mission::on_creature_death().
monster_species
species_id mission_type::monster_species
Definition at line 218 of file mission.h.
Referenced by create(), and load().
monster_type
mtype_id mission_type::monster_type = mtype_id::NULL_ID()
Definition at line 217 of file mission.h.
Referenced by create(), and load().
name
translation mission_type::name = to_translation("Bugged mission type") private
Definition at line 186 of file mission.h.
Referenced by load(), and tname().
origins
std::vector<mission_origin> mission_type::origins
Definition at line 207 of file mission.h.
Referenced by mission::is_complete(), and load().
place
std::function<bool(const tripoint_abs_omt &)> mission_type::place = mission_place::always
Definition at line 223 of file mission.h.
Referenced by load().
recruit_class
npc_class_id mission_type::recruit_class = npc_class_id("NC_NONE")
Definition at line 215 of file mission.h.
remove_container
bool mission_type::remove_container = false
Definition at line 211 of file mission.h.
Referenced by load(), and mission::wrap_up().
src
std::vector<std::pair<mission_type_id, mod_id> > mission_type::src
Definition at line 182 of file mission.h.
Referenced by load(), and load_mission_type().
start
std::function<void(mission *)> mission_type::start = mission_start::standard
Definition at line 224 of file mission.h.
Referenced by mission::assign(), and load().
target_id
string_id<oter_type_t> mission_type::target_id
Definition at line 220 of file mission.h.
Referenced by mission::is_complete(), and load().
target_npc_id
character_id mission_type::target_npc_id
Definition at line 216 of file mission.h.
urgent
bool mission_type::urgent = false
Definition at line 199 of file mission.h.
Referenced by load().
value
int mission_type::value = 0
Definition at line 194 of file mission.h.
Referenced by create(), and load().
was_loaded
bool mission_type::was_loaded = false
Definition at line 183 of file mission.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/mission.h
src/mission.cpp
src/mission_util.cpp
src/missiondef.cpp