Cataclysm DDA: activity_byproduct Struct Reference
activity_byproduct Struct Reference
#include <mapdata.h>
Public Member Functions
int roll () const
void load (const JsonObject &jo)
void deserialize (const JsonObject &jo)
Public Attributes
itype_id item
int count = 0
int random_min = 0
int random_max = 0
bool was_loaded = false
Detailed Description
Definition at line 349 of file mapdata.h.
Member Function Documentation
deserialize()
void activity_byproduct::deserialize (const JsonObject & jo)
Definition at line 1173 of file mapdata.cpp.
 {
     load( jo );
 }
References load().
load()
void activity_byproduct::load (const JsonObject & jo)
Definition at line 1156 of file mapdata.cpp.
 {
     mandatory( jo, was_loaded, "item", item );
     if( jo.has_int( "count" ) ) {
         mandatory( jo, was_loaded, "count", count );
         count = std::max( 0, count );
     } else if( jo.has_array( "count" ) ) {
         std::vector<int> count_random = jo.get_int_array( "count" );
         random_min = std::max( 0, count_random[0] );
         random_max = std::max( 0, count_random[1] );
         if( random_min > random_max ) {
             std::swap( random_min, random_max );
         }
     }
 }
References count, JsonObject::get_int_array(), JsonObject::has_array(), JsonObject::has_int(), mandatory, max(), random_max, random_min, cata::swap(), and was_loaded.
Referenced by deserialize().
roll()
int activity_byproduct::roll () const
Definition at line 1151 of file mapdata.cpp.
 {
     return count + rng( random_min, random_max );
 }
References count, random_max, random_min, and rng().
Member Data Documentation
count
int activity_byproduct::count = 0
Definition at line 351 of file mapdata.h.
Referenced by load(), and roll().
item
itype_id activity_byproduct::item
Definition at line 350 of file mapdata.h.
random_max
int activity_byproduct::random_max = 0
Definition at line 353 of file mapdata.h.
Referenced by load(), and roll().
random_min
int activity_byproduct::random_min = 0
Definition at line 352 of file mapdata.h.
Referenced by load(), and roll().
was_loaded
bool activity_byproduct::was_loaded = false
Definition at line 357 of file mapdata.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/mapdata.h
src/mapdata.cpp