Cataclysm DDA: event_summary Struct Reference
event_summary Struct Reference
#include <stats_tracker.h>
Public Member Functions
event_summary ()
event_summary (int c, time_point f, time_point l)
void add (const cata::event &)
void add (const event_summary &)
void serialize (JsonOut &) const
void deserialize (const JsonObject &jo)
Public Attributes
int count
time_point first
time_point last
Detailed Description
Definition at line 42 of file stats_tracker.h.
Constructor & Destructor Documentation
event_summary() [1/2]
event_summary::event_summary ()
Definition at line 28 of file stats_tracker.cpp.
                              :
     count( 0 ),
     first( calendar::before_time_starts ),
     last( calendar::before_time_starts )
 {
 }
event_summary() [2/2]
event_summary::event_summary (int c, time_point f, time_point l)
Definition at line 35 of file stats_tracker.cpp.
                                                                 :
     count( c ),
     first( f ),
     last( l )
 {
 }
Member Function Documentation
add() [1/2]
void event_summary::add (const cata::event & e)
Definition at line 42 of file stats_tracker.cpp.
 {
     if( count == 0 ) {
         first = last = e.time();
     } else {
         last = std::max( last, e.time() );
     }
     ++count;
 }
References count, first, last, max(), and cata::event::time().
add() [2/2]
void event_summary::add (const event_summary & s)
Definition at line 52 of file stats_tracker.cpp.
 {
     if( count == 0 ) {
         *this = s;
     } else {
         count += s.count;
         first = std::min( first, s.first );
         last = std::max( last, s.last );
     }
 }
References count, first, last, max(), and min().
deserialize()
void event_summary::deserialize (const JsonObject & jo)
Definition at line 72 of file stats_tracker.cpp.
 {
     jo.read( "count", count, true );
     jo.read( "first", first, true );
     jo.read( "last", last, true );
 }
References count, first, last, and JsonObject::read().
serialize()
void event_summary::serialize (JsonOut & jsout) const
Definition at line 63 of file stats_tracker.cpp.
 {
     jsout.start_object();
     jsout.member( "count", count );
     jsout.member( "first", first );
     jsout.member( "last", last );
     jsout.end_object();
 }
References count, JsonOut::end_object(), first, last, JsonOut::member(), and JsonOut::start_object().
Member Data Documentation
count
int event_summary::count
Definition at line 46 of file stats_tracker.h.
Referenced by add(), deserialize(), and serialize().
first
time_point event_summary::first
Definition at line 47 of file stats_tracker.h.
Referenced by add(), deserialize(), and serialize().
last
time_point event_summary::last
Definition at line 48 of file stats_tracker.h.
Referenced by add(), deserialize(), and serialize().
The documentation for this struct was generated from the following files:
src/stats_tracker.h
src/stats_tracker.cpp