Cataclysm DDA: var Struct Reference
var Struct Reference
#include <math_parser_impl.h>
Public Member Functions
template<class... Args>
var (Args &&... args)
double eval (dialogue &d) const
Public Attributes
var_info varinfo
Detailed Description
Definition at line 109 of file math_parser_impl.h.
Constructor & Destructor Documentation
var()
template<class... Args> var::var (Args &&... args) inline explicit
Definition at line 111 of file math_parser_impl.h.
 : varinfo( std::forward<Args>( args )... ) {}
Referenced by anonymous_namespace{math_parser_diag.cpp}::has_var_eval(), and anonymous_namespace{math_parser_diag.cpp}::value_or_eval().
Member Function Documentation
eval()
double var::eval (dialogue & d) const
Definition at line 232 of file math_parser.cpp.
 {
     std::string const str = read_var_value( varinfo, d );
     if( str.empty() ) {
         return 0;
     }
     if( std::optional<double> ret = svtod( str ); ret ) {
         return *ret;
     }
     debugmsg( R"(failed to convert variable "%s" with value "%s" to a number)", varinfo.name, str );
     return 0;
 }
References debugmsg, abstract_var_info< T >::name, read_var_value(), cata::hash64_detail::ret, svtod(), and varinfo.
Member Data Documentation
varinfo
var_info var::varinfo
Definition at line 115 of file math_parser_impl.h.
Referenced by eval().
The documentation for this struct was generated from the following files:
src/math_parser_impl.h
src/math_parser.cpp