Cataclysm DDA: widget_clause Struct Reference
widget_clause Struct Reference
#include <widget.h>
Public Member Functions
void load (const JsonObject &jo)
Static Public Member Functions
static int get_val_for_id (const std::string &clause_id, const widget_id &wgt, bool skip_condition=false)
Static accessors:
static const translation & get_text_for_id (const std::string &clause_id, const widget_id &wgt, bool skip_condition=false)
static const std::string & get_sym_for_id (const std::string &clause_id, const widget_id &wgt, bool skip_condition=false)
static nc_color get_color_for_id (const std::string &clause_id, const widget_id &wgt, bool skip_condition=false)
Private Member Functions
bool meets_condition (const std::string &opt_var="") const
bool meets_condition (const std::set< bodypart_id > &bps) const
Static Private Member Functions
static const widget_clause * get_clause_for_id (const std::string &clause_id, const widget_id &wgt, int thresh_val=INT_MIN, bool skip_condition=false)
Private Attributes
std::string id
std::string sym
translation text
nc_color color = c_unset
int value = INT_MIN
std::vector< widget_id > widgets
bool has_condition = false
bool should_parse_tags = false
std::function< bool(dialogue &)> condition
Friends
class widget
Detailed Description
Definition at line 157 of file widget.h.
Member Function Documentation
get_clause_for_id()
const widget_clause * widget_clause::get_clause_for_id (const std::string & clause_id, const widget_id & wgt, int thresh_val = INT_MIN, bool skip_condition = false) static private
Definition at line 325 of file widget.cpp.
 {
     std::map<int, const widget_clause *> vals;
     for( const widget_clause &wp : wgt->_clauses ) {
         if( clause_id != wp.id || ( !skip_condition && !wp.meets_condition( wgt->_bps ) ) ) {
             continue;
         }
         if( thresh_val == INT_MIN || !skip_condition ) {
             return &wp;
         }
         vals.emplace( wp.value, &wp );
     }
     if( vals.empty() ) {
         return nullptr;
     }
     int key = INT_MIN;
     for( const auto &v : vals ) {
         if( v.first == thresh_val ) {
             return v.second;
         } else if( v.first > thresh_val ) {
             break;
         }
         key = v.first;
     }
     return key == INT_MIN ? nullptr : vals[key];
 }
References widget::_bps, widget::_clauses, id, meets_condition(), and value.
Referenced by get_color_for_id(), get_sym_for_id(), get_text_for_id(), and get_val_for_id().
get_color_for_id()
nc_color widget_clause::get_color_for_id (const std::string & clause_id, const widget_id & wgt, bool skip_condition = false) static
Definition at line 380 of file widget.cpp.
 {
     const widget_clause *wp = widget_clause::get_clause_for_id( clause_id, wgt, INT_MIN,
                               skip_condition );
     return wp == nullptr ? c_white : wp->color;
 }
References c_white, color, and get_clause_for_id().
get_sym_for_id()
const std::string & widget_clause::get_sym_for_id (const std::string & clause_id, const widget_id & wgt, bool skip_condition = false) static
Definition at line 371 of file widget.cpp.
 {
     static const std::string none;
     const widget_clause *wp = widget_clause::get_clause_for_id( clause_id, wgt, INT_MIN,
                               skip_condition );
     return wp == nullptr ? none : wp->sym;
 }
References get_clause_for_id(), none, and sym.
get_text_for_id()
const translation & widget_clause::get_text_for_id (const std::string & clause_id, const widget_id & wgt, bool skip_condition = false) static
Definition at line 362 of file widget.cpp.
 {
     static const translation none;
     const widget_clause *wp = widget_clause::get_clause_for_id( clause_id, wgt, INT_MIN,
                               skip_condition );
     return wp == nullptr ? none : wp->text;
 }
References get_clause_for_id(), none, and text.
get_val_for_id()
int widget_clause::get_val_for_id (const std::string & clause_id, const widget_id & wgt, bool skip_condition = false) static
Static accessors:
Returns the requested variable for the specified requirement, or a default value if the requirements aren't met. Here are the default values for each field: id => "" sym => "" text => translation() color => c_white value => INT_MIN
If multiple entries meet the requirement, you can specify a threshold value to get the entry with the highest value below that threshold.
If a clause also has a "condition" field, that condition must also return true in order for that clause to be usable.
Definition at line 354 of file widget.cpp.
 {
     const widget_clause *wp = widget_clause::get_clause_for_id( clause_id, wgt, INT_MIN,
                               skip_condition );
     return wp == nullptr ? INT_MIN : wp->value;
 }
References get_clause_for_id(), and value.
load()
void widget_clause::load (const JsonObject & jo)
Definition at line 282 of file widget.cpp.
 {
     optional( jo, false, "id", id );
     optional( jo, false, "text", text );
     optional( jo, false, "sym", sym );
     optional( jo, false, "value", value, INT_MIN );
     std::string clr;
     optional( jo, false, "color", clr, "" );
     color = color_from_string( clr );
     if( jo.has_member( "condition" ) ) {
         read_condition( jo, "condition", condition, false );
         has_condition = true;
     }
     if( jo.has_bool( "parse_tags" ) ) {
         should_parse_tags = jo.get_bool( "parse_tags" );
     }
     optional( jo, false, "widgets", widgets, string_id_reader<::widget> {} );
 }
References color, color_from_string(), condition, JsonObject::get_bool(), JsonObject::has_bool(), has_condition, JsonObject::has_member(), optional(), read_condition(), should_parse_tags, sym, text, value, and widgets.
Referenced by widget::load().
meets_condition() [1/2]
bool widget_clause::meets_condition (const std::set< bodypart_id > & bps) const private
Definition at line 312 of file widget.cpp.
 {
     if( bps.empty() ) {
         return meets_condition();
     }
     for( const bodypart_id &bid : bps ) {
         if( meets_condition( bid.id().str() ) ) {
             return true;
         }
     }
     return false;
 }
References meets_condition().
meets_condition() [2/2]
bool widget_clause::meets_condition (const std::string & opt_var = "") const private
Definition at line 304 of file widget.cpp.
 {
     dialogue d( get_talker_for( get_avatar() ), nullptr );
     d.reason = opt_var; // TODO: remove since it's replaced by context var
     write_var_value( var_type::context, "npctalk_var_widget", &d, opt_var );
     return !has_condition || condition( d );
 }
References condition, context, get_avatar(), get_talker_for(), has_condition, dialogue::reason, and write_var_value().
Referenced by get_clause_for_id(), and meets_condition().
Friends And Related Function Documentation
widget
friend class widget friend
Definition at line 159 of file widget.h.
Member Data Documentation
color
nc_color widget_clause::color = c_unset private
Definition at line 163 of file widget.h.
Referenced by get_color_for_id(), load(), widget::number_cond(), widget::sym_cond(), widget::sym_text_cond(), and widget::text_cond().
condition
std::function<bool(dialogue &)> widget_clause::condition private
Definition at line 171 of file widget.h.
Referenced by load(), and meets_condition().
has_condition
bool widget_clause::has_condition = false private
Definition at line 168 of file widget.h.
Referenced by load(), and meets_condition().
id
std::string widget_clause::id private
Definition at line 160 of file widget.h.
Referenced by get_clause_for_id().
should_parse_tags
bool widget_clause::should_parse_tags = false private
Definition at line 170 of file widget.h.
Referenced by load().
sym
std::string widget_clause::sym private
Definition at line 161 of file widget.h.
Referenced by get_sym_for_id(), load(), widget::sym_cond(), and widget::sym_text_cond().
text
translation widget_clause::text private
Definition at line 162 of file widget.h.
Referenced by get_text_for_id(), load(), widget::sym_text_cond(), and widget::text_cond().
value
int widget_clause::value = INT_MIN private
Definition at line 164 of file widget.h.
Referenced by get_clause_for_id(), get_val_for_id(), load(), and widget::number_cond().
widgets
std::vector<widget_id> widget_clause::widgets private
Definition at line 165 of file widget.h.
Referenced by widget::finalize_inherited_fields_recursive(), load(), and widget::widgets_cond().
The documentation for this struct was generated from the following files:
src/widget.h
src/widget.cpp