Cataclysm DDA: body_part_type Struct Reference
body_part_type Struct Reference
#include <bodypart.h>
Public Types
enum class type {
head , torso , sensor , mouth ,
arm , hand , leg , foot ,
wing , tail , other , num_types
}
the different types of body parts there are.
Public Member Functions
bool has_flag (const json_character_flag &flag) const
body_part_type::type primary_limb_type () const
bool has_type (const body_part_type::type &type) const
sub_bodypart_id random_sub_part (bool secondary) const
void load (const JsonObject &jo, std::string_view src)
void finalize ()
void check () const
float get_limb_score (const limb_score_id &id) const
float get_limb_score_max (const limb_score_id &id) const
bool has_limb_score (const limb_score_id &id) const
int bionic_slots () const
float unarmed_damage (const damage_type_id &dt) const
float unarmed_arpen (const damage_type_id &dt) const
float damage_resistance (const damage_type_id &dt) const
float damage_resistance (const damage_unit &du) const
Static Public Member Functions
static void load_bp (const JsonObject &jo, const std::string &src)
static const std::vector< body_part_type > & get_all ()
static void reset ()
static void finalize_all ()
static void check_consistency ()
static std::set< translation, localized_comparator > consolidate (std::vector< sub_bodypart_id > &covered)
static std::set< translation, localized_comparator > consolidate (std::vector< bodypart_id > &covered)
Public Attributes
std::vector< std::pair< bodypart_str_id, mod_id > > src
std::vector< sub_bodypart_str_id > sub_parts
Sub-location of the body part used for encumberance, coverage and determining protection.
std::map< units::mass, int > encumbrance_per_weight
cata::flat_set< json_character_flag > flags
cata::flat_set< json_character_flag > conditional_flags
bodypart_str_id id
std::string legacy_id
bodypart_str_id main_part
bodypart_str_id connected_to
bodypart_str_id opposite_part
std::map< body_part_type::type, float > limbtypes
std::set< matec_id > techniques
efftype_id windage_effect
efftype_id no_power_effect
std::vector< bp_onhit_effect > effects_on_hit
translation name
translation name_multiple
translation accusative
translation accusative_multiple
translation name_as_heading
translation name_as_heading_multiple
translation smash_message
translation hp_bar_ui_text
translation encumb_text
body_part token = num_bp
float hit_size = 0.0f
Size of the body part for melee targeting.
float hit_difficulty = 0.0f
How hard is it to hit a given body part, assuming "owner" is hit.
side part_side = side::BOTH
int encumbrance_threshold = 0
int encumbrance_limit = 0
int health_limit = 0
int bmi_encumbrance_threshold = 999
float bmi_encumbrance_scalar = 0
float smash_efficiency = 0.5f
float hot_morale_mod = 0.0f
float cold_morale_mod = 0.0f
float stylish_bonus = 0.0f
int squeamish_penalty = 0
bool feels_discomfort = true
units::temperature_delta fire_warmth_bonus = 0_C_delta
int env_protection = 0
int base_hp = 60
int heal_bonus = 0
float mend_rate = 1.0f
int ugliness = 0
int ugliness_mandatory = 0
units::temperature_delta temp_min = 0_C_delta
units::temperature_delta temp_max = 0_C_delta
int drench_max = 0
int drench_increment = 2
float drying_rate = 1.0f
int wet_morale = 0
int technique_enc_limit = 50
int power_efficiency = 0
std::vector< bodypart_str_id > similar_bodyparts
stat_hp_mods hp_mods
bool unarmed_bonus = false
bool is_vital = false
bool is_limb = false
bool was_loaded = false
Private Attributes
std::map< limb_score_id, bp_limb_score > limb_scores
damage_instance damage
int bionic_slots_ = 0
body_part_type::type _primary_limb_type = body_part_type::type::num_types
resistances armor
Detailed Description
Definition at line 173 of file bodypart.h.
Member Enumeration Documentation
type
enum body_part_type::type strong
the different types of body parts there are.
this allows for the ability to group limbs or determine a limb of a certain type
Enumerator
head
torso
sensor
mouth
arm
hand
leg
foot
wing
tail
other
num_types
Definition at line 179 of file bodypart.h.
{
             // this is where helmets go, and is a vital part.
             head,
             // the torso is generally the center of mass of a creature
             torso,
             // provides sight
             sensor,
             // you eat and scream with this
             mouth,
             // may manipulate objects to some degree, is a main part
             arm,
             // manipulates objects. usually is not a main part.
             hand,
             // provides motive power
             leg,
             // helps with balance. usually is not a main part
             foot,
             // may reduce fall damage
             wing,
             // may provide balance or manipulation
             tail,
             // more of a general purpose limb, such as horns.
             other,
             num_types
         };
Member Function Documentation
bionic_slots()
int body_part_type::bionic_slots () const inline
Definition at line 366 of file bodypart.h.
{
             return bionic_slots_;
         }
References bionic_slots_.
Referenced by Character::get_total_bionics_slots().
check()
void body_part_type::check () const
Definition at line 527 of file bodypart.cpp.
 {
     const body_part_type &under_token = convert_bp( token ).obj();
     if( this != &under_token && token != body_part::num_bp ) {
         debugmsg( "Body part %s has duplicate token %d, mapped to %s", id.c_str(), token,
                   under_token.id.c_str() );
     }
     if( !id.is_null() && main_part.is_null() ) {
         debugmsg( "Body part %s has unset main part", id.c_str() );
     }
     if( !id.is_null() && opposite_part.is_null() ) {
         debugmsg( "Body part %s has unset opposite part", id.c_str() );
     }
     if( !main_part.is_valid() ) {
         debugmsg( "Body part %s has invalid main part %s.", id.c_str(), main_part.c_str() );
     }
     if( !opposite_part.is_valid() ) {
         debugmsg( "Body part %s has invalid opposite part %s.", id.c_str(), opposite_part.c_str() );
     } else if( opposite_part->opposite_part != id ) {
         debugmsg( "Bodypart %s has inconsistent opposite part!", id.str() );
     }
     for( const std::pair<const limb_score_id, bp_limb_score> &bpls : limb_scores ) {
         if( !bpls.first.is_valid() ) {
             debugmsg( "Body part %s has invalid limb score %s.", id.str(), bpls.first.str() );
         }
         if( bpls.second.score > bpls.second.max ) {
             debugmsg( "Body part %s has higher %s score than max.", id.str(), bpls.first.str() );
         }
     }
     for( const std::pair<const damage_type_id, float> &dt : armor.resist_vals ) {
         if( !dt.first.is_valid() ) {
             debugmsg( "Invalid armor type \"%s\" for body part %s", dt.first.c_str(), id.c_str() );
         }
     }
     for( const damage_unit &dt : damage.damage_units ) {
         if( !dt.type.is_valid() ) {
             debugmsg( "Invalid unarmed_damage type \"%s\" for body part %s", dt.type.c_str(), id.c_str() );
         }
     }
     // Check that connected_to leads eventually to the root bodypart (currently always head),
     // without any loops
     std::unordered_set<bodypart_str_id> visited = { id };
     bodypart_str_id next = connected_to;
     while( !visited.count( next ) ) {
         visited.insert( next );
         next = next->connected_to;
     }
     if( next != next->connected_to ) {
         debugmsg( "Loop in body part connectedness starting from %s", id.str() );
     }
 }
References armor, string_id< T >::c_str(), connected_to, convert_bp(), damage, damage_instance::damage_units, debugmsg, id, string_id< T >::is_null(), string_id< T >::is_valid(), limb_scores, main_part, num_bp, string_id< T >::obj(), opposite_part, resistances::resist_vals, and token.
check_consistency()
void body_part_type::check_consistency () static
Definition at line 515 of file bodypart.cpp.
 {
     for( const body_part bp : all_body_parts ) {
         const bodypart_str_id &legacy_bp = convert_bp( bp );
         if( !legacy_bp.is_valid() ) {
             debugmsg( "Mandatory body part %s was not loaded", legacy_bp.c_str() );
         }
     }
     body_part_factory.check();
 }
References all_body_parts, anonymous_namespace{bodypart.cpp}::body_part_factory, bp, string_id< T >::c_str(), convert_bp(), debugmsg, and string_id< T >::is_valid().
Referenced by DynamicDataLoader::check_consistency().
consolidate() [1/2]
std::set< translation, localized_comparator > body_part_type::consolidate (std::vector< bodypart_id > & covered) static
Definition at line 726 of file bodypart.cpp.
 {
     std::set<translation, localized_comparator> to_return;
     // now try and compress together matching limbs
     for( size_t i = 0; i < covered.size(); i++ ) {
         const bodypart_id &bp = covered[i];
         if( bp == bodypart_str_id::NULL_ID().id() ) {
             //its already been covered
             continue;
         }
         // bodyparts with no opposite are their own opposite
         if( bp->opposite_part.id() == bp ) {
             // if no opposite don't look for one
             to_return.insert( bp->name_as_heading );
             continue;
         }
         auto bp_itt = std::find( covered.begin(), covered.end(), bp->opposite_part );
         if( bp_itt == covered.end() ) {
             // if we didn't find the match just add the limb we were just looking at
             to_return.insert( bp->name_as_heading );
             continue;
         }
         *bp_itt = bodypart_str_id::NULL_ID().id();
         to_return.insert( bp->name_as_heading_multiple );
     }
     return to_return;
 }
References bp, string_id< T >::id(), name_as_heading, name_as_heading_multiple, string_id< body_part_type >::NULL_ID(), and opposite_part.
consolidate() [2/2]
std::set< translation, localized_comparator > body_part_type::consolidate (std::vector< sub_bodypart_id > & covered) static
Definition at line 625 of file bodypart.cpp.
 {
     std::set<translation, localized_comparator> to_return;
     std::vector<bodypart_id> full_bps;
     //first try to compress sets of sub body parts together into a full limb
     for( size_t i = 0; i < covered.size(); i++ ) {
         const sub_bodypart_id &sbp = covered[i];
         if( sbp == sub_body_part_sub_limb_debug ) {
             // if we have already covered this continue
             continue;
         }
         // try to find all matching sublimbs from the parent
         bool found_all = true;
         for( const sub_bodypart_str_id &searching : sbp->parent->sub_parts ) {
             //skip secondary locations for this
             if( !searching->secondary ) {
                 found_all = std::find( covered.begin(), covered.end(), searching.id() ) != covered.end() &&
                             found_all;
             }
         }
         // if found all consolidate all the limb bits together
         // TODO: shouldn't need so many loops to do this
         if( found_all ) {
             full_bps.emplace_back( sbp->parent );
             // set the initial to a skipped value
             for( const sub_bodypart_str_id &searching : sbp->parent->sub_parts ) {
                 if( !searching->secondary ) {
                     auto sbp_it = std::find( covered.begin(), covered.end(), searching.id() );
                     *sbp_it = sub_body_part_sub_limb_debug;
                 }
             }
         }
     }
     // now try and compress together matching limbs
     for( size_t i = 0; i < full_bps.size(); i++ ) {
         const bodypart_id &bp = full_bps[i];
         if( bp == bodypart_str_id::NULL_ID().id() ) {
             //its already been covered
             continue;
         }
         // bodyparts with no opposite are their own opposite
         if( bp->opposite_part.id() == bp ) {
             // if no opposite don't look for one
             to_return.insert( bp->name_as_heading );
             continue;
         }
         auto bp_itt = std::find( full_bps.begin(), full_bps.end(), bp->opposite_part );
         if( bp_itt == full_bps.end() ) {
             // if we didn't find the match just add the limb we were just looking at
             to_return.insert( bp->name_as_heading );
             continue;
         }
         *bp_itt = bodypart_str_id::NULL_ID().id();
         to_return.insert( bp->name_as_heading_multiple );
     }
     for( size_t i = 0; i < covered.size(); i++ ) {
         const sub_bodypart_id &sbp = covered[i];
         if( sbp == sub_body_part_sub_limb_debug ) {
             // if we have already covered this value as a pair continue
             continue;
         }
         sub_bodypart_id temp;
         // if our sub part has an opposite
         if( sbp->opposite != sub_body_part_sub_limb_debug ) {
             temp = sbp->opposite;
         } else {
             // if it doesn't have an opposite add it to the return vector alone and continue
             to_return.insert( sbp->name );
             continue;
         }
         bool found = false;
         for( sub_bodypart_id &sbp_it : covered ) {
             // go through each body part and test if its partner is there as well
             if( temp == sbp_it ) {
                 // add the multiple name not the single
                 to_return.insert( sbp->name_multiple );
                 found = true;
                 // set the found part to a null value
                 sbp_it = sub_body_part_sub_limb_debug;
                 break;
             }
         }
         // if we didn't find its pair print it normally
         if( !found ) {
             to_return.insert( sbp->name );
         }
     }
     return to_return;
 }
References bp, string_id< T >::id(), name_as_heading, name_as_heading_multiple, string_id< body_part_type >::NULL_ID(), opposite_part, sub_body_part_type::secondary, sub_body_part_sub_limb_debug, and temp.
Referenced by item::armor_full_protection_info(), item::armor_info(), and item_pocket::general_info().
damage_resistance() [1/2]
float body_part_type::damage_resistance (const damage_type_id & dt) const
Definition at line 615 of file bodypart.cpp.
 {
     return armor.type_resist( dt );
 }
References armor, and resistances::type_resist().
Referenced by Character::get_armor_type(), and Character::passive_absorb_hit().
damage_resistance() [2/2]
float body_part_type::damage_resistance (const damage_unit & du) const
Definition at line 620 of file bodypart.cpp.
 {
     return armor.get_effective_resist( du );
 }
References armor, and resistances::get_effective_resist().
finalize()
void body_part_type::finalize ()
Definition at line 510 of file bodypart.cpp.
 {
     finalize_damage_map( armor.resist_vals );
 }
References armor, finalize_damage_map(), and resistances::resist_vals.
finalize_all()
void body_part_type::finalize_all () static
Definition at line 505 of file bodypart.cpp.
 {
     body_part_factory.finalize();
 }
References anonymous_namespace{bodypart.cpp}::body_part_factory.
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< body_part_type > & body_part_type::get_all () static
Definition at line 285 of file bodypart.cpp.
 {
     return body_part_factory.get_all();
 }
References anonymous_namespace{bodypart.cpp}::body_part_factory.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_foreach(), and mutation_branch::load().
get_limb_score()
float body_part_type::get_limb_score (const limb_score_id & id) const
Definition at line 588 of file bodypart.cpp.
 {
     const auto it = limb_scores.find( id );
     return it == limb_scores.end() ? 0.0f : it->second.score;
 }
References limb_scores.
Referenced by draw_health_summary(), get_encumbrance_description(), and anatomy::select_blocking_part().
get_limb_score_max()
float body_part_type::get_limb_score_max (const limb_score_id & id) const
Definition at line 594 of file bodypart.cpp.
 {
     const auto it = limb_scores.find( id );
     return it == limb_scores.end() ? 0.0f : it->second.max;
 }
References limb_scores.
has_flag()
bool body_part_type::has_flag (const json_character_flag & flag) const
Definition at line 257 of file bodypart.cpp.
 {
     return flags.count( flag ) > 0;
 }
References flags.
Referenced by Creature::add_effect(), Character::apply_damage(), melee_actor::call(), character_martial_arts::can_arm_block(), character_martial_arts::can_leg_block(), Character::count_bodypart_with_flag(), Character::deal_damage(), Creature::deal_damage(), mattack::dermatik(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), anatomy::get_all_eligable_parts(), anatomy::get_organic_size_sum(), Character::heal(), monster::melee_attack(), Character::mend(), melee_actor::on_damage(), bite_actor::on_damage(), pick_part_to_heal(), Character::recalc_limb_energy_usage(), anatomy::select_blocking_part(), anatomy::select_body_part(), sting_shoot(), Character::update_body_wetness(), and Character::update_bodytemp().
has_limb_score()
bool body_part_type::has_limb_score (const limb_score_id & id) const
Definition at line 600 of file bodypart.cpp.
 {
     return limb_scores.count( id );
 }
References limb_scores.
Referenced by effect::disp_desc(), and get_encumbrance_description().
has_type()
bool body_part_type::has_type (const body_part_type::type & type) const
Definition at line 252 of file bodypart.cpp.
 {
     return limbtypes.count( type ) > 0;
 }
References limbtypes.
Referenced by Character::most_staunchable_bp(), and anatomy::select_blocking_part().
load()
void body_part_type::load (const JsonObject & jo, std::string_view src)
Definition at line 290 of file bodypart.cpp.
 {
     mandatory( jo, was_loaded, "id", id );
     mandatory( jo, was_loaded, "name", name );
     // This is NOT the plural of `name`; it's a name referring to the pair of
     // bodyparts which this bodypart belongs to, and thus should not be implemented
     // using "n_gettext" or "translation::make_plural". Otherwise, in languages
     // without plural forms, translation of this string would indicate it
     // to be a left or right part, while it is not.
     optional( jo, was_loaded, "name_multiple", name_multiple );
     mandatory( jo, was_loaded, "accusative", accusative );
     // same as the above comment
     optional( jo, was_loaded, "accusative_multiple", accusative_multiple );
     mandatory( jo, was_loaded, "heading", name_as_heading );
     // Same as the above comment
     mandatory( jo, was_loaded, "heading_multiple", name_as_heading_multiple );
     optional( jo, was_loaded, "hp_bar_ui_text", hp_bar_ui_text );
     mandatory( jo, was_loaded, "encumbrance_text", encumb_text );
     mandatory( jo, was_loaded, "hit_size", hit_size );
     mandatory( jo, was_loaded, "hit_difficulty", hit_difficulty );
     mandatory( jo, was_loaded, "base_hp", base_hp );
     optional( jo, was_loaded, "stat_hp_mods", hp_mods );
     optional( jo, was_loaded, "heal_bonus", heal_bonus, 0 );
     optional( jo, was_loaded, "mend_rate", mend_rate, 1.0f );
     mandatory( jo, was_loaded, "drench_capacity", drench_max );
     optional( jo, was_loaded, "drench_increment", drench_increment, 2 );
     optional( jo, was_loaded, "drying_rate", drying_rate, 1.0f );
     optional( jo, was_loaded, "wet_morale", wet_morale, 0 );
     optional( jo, was_loaded, "ugliness", ugliness, 0 );
     optional( jo, was_loaded, "ugliness_mandatory", ugliness_mandatory, 0 );
     optional( jo, was_loaded, "is_limb", is_limb, false );
     optional( jo, was_loaded, "is_vital", is_vital, false );
     if( jo.has_array( "limb_types" ) ) {
         limbtypes.clear();
         body_part_type::type first_type = body_part_type::type::num_types;
         bool set_first_type = true;
         for( JsonValue jval : jo.get_array( "limb_types" ) ) {
             float weight = 1.0f;
             body_part_type::type limb_type;
             if( jval.test_array() ) {
                 JsonArray jarr = jval.get_array();
                 limb_type = io::string_to_enum<body_part_type::type>( jarr.get_string( 0 ) );
                 weight = jarr.get_float( 1 );
                 set_first_type = false;
             } else {
                 limb_type = io::string_to_enum<body_part_type::type>( jval.get_string() );
             }
             limbtypes.emplace( limb_type, weight );
             if( first_type == body_part_type::type::num_types ) {
                 first_type = limb_type;
             }
         }
         // set cached primary type if no weights specified
         if( set_first_type ) {
             _primary_limb_type = first_type;
         }
     } else {
         limbtypes.clear();
         body_part_type::type limb_type = {};
         mandatory( jo, was_loaded, "limb_type", limb_type );
         limbtypes.emplace( limb_type, 1.0f );
     }
     if( _primary_limb_type == body_part_type::type::num_types ) {
         float high = 0.f;
         for( auto &bp_type : limbtypes ) {
             if( high < bp_type.second ) {
                 high = bp_type.second;
                 _primary_limb_type = bp_type.first;
             }
         }
     }
     // tokens are actually legacy code that should be on their way out.
     if( !was_loaded ) {
         optional( jo, was_loaded, "legacy_id", legacy_id, "BP_NULL" );
         if( legacy_id != "BP_NULL" ) {
             token = legacy_id_to_enum( legacy_id );
         }
     } else {
         // we need to clear this because any bodypart using copy-from will not be a legacy part.
         legacy_id = "BP_NULL";
         token = body_part::num_bp;
     }
     optional( jo, was_loaded, "env_protection", env_protection, 0 );
     int legacy_fire_warmth_bonus = units::to_legacy_bodypart_temp_delta( fire_warmth_bonus );
     optional( jo, was_loaded, "fire_warmth_bonus", legacy_fire_warmth_bonus, 0 );
     fire_warmth_bonus = units::from_legacy_bodypart_temp_delta( legacy_fire_warmth_bonus );
     mandatory( jo, was_loaded, "main_part", main_part );
     if( main_part == id ) {
         mandatory( jo, was_loaded, "connected_to", connected_to );
     } else {
         connected_to = main_part;
     }
     mandatory( jo, was_loaded, "opposite_part", opposite_part );
     optional( jo, was_loaded, "windage_effect", windage_effect, efftype_id::NULL_ID() );
     optional( jo, was_loaded, "no_power_effect", no_power_effect, efftype_id::NULL_ID() );
     optional( jo, was_loaded, "smash_message", smash_message );
     optional( jo, was_loaded, "smash_efficiency", smash_efficiency, 0.5f );
     optional( jo, was_loaded, "hot_morale_mod", hot_morale_mod, 0.0 );
     optional( jo, was_loaded, "cold_morale_mod", cold_morale_mod, 0.0 );
     optional( jo, was_loaded, "feels_discomfort", feels_discomfort, true );
     optional( jo, was_loaded, "stylish_bonus", stylish_bonus, 0 );
     optional( jo, was_loaded, "squeamish_penalty", squeamish_penalty, 0 );
     optional( jo, was_loaded, "bionic_slots", bionic_slots_, 0 );
     optional( jo, was_loaded, "flags", flags );
     optional( jo, was_loaded, "conditional_flags", conditional_flags );
     optional( jo, was_loaded, "encumbrance_threshold", encumbrance_threshold, 0 );
     optional( jo, was_loaded, "encumbrance_limit", encumbrance_limit, 100 );
     optional( jo, was_loaded, "health_limit", health_limit, 1 );
     optional( jo, was_loaded, "techniques", techniques );
     optional( jo, was_loaded, "technique_encumbrance_limit", technique_enc_limit, 50 );
     optional( jo, was_loaded, "bmi_encumbrance_threshold", bmi_encumbrance_threshold, 999 );
     optional( jo, was_loaded, "bmi_encumbrance_scalar", bmi_encumbrance_scalar, 0 );
     optional( jo, was_loaded, "power_efficiency", power_efficiency, 0 );
     optional( jo, was_loaded, "similar_bodyparts", similar_bodyparts );
     if( jo.has_member( "limb_scores" ) ) {
         limb_scores.clear();
         const JsonArray &jarr = jo.get_array( "limb_scores" );
         for( const JsonValue jval : jarr ) {
             bp_limb_score bpls;
             const limb_score_id id = limb_score_id( jval.get_array().get_string( 0 ) );
             bpls.score = jval.get_array().get_float( 1 );
             bpls.max = jval.get_array().size() > 2 ? jval.get_array().get_float( 2 ) : bpls.score;
             limb_scores[id] = bpls;
         }
     }
     if( jo.has_array( "effects_on_hit" ) ) {
         effects_on_hit.clear();
         for( const JsonObject effect_jo : jo.get_array( "effects_on_hit" ) ) {
             bp_onhit_effect eff;
             eff.load( effect_jo );
             effects_on_hit.push_back( eff );
         }
     }
     if( jo.has_array( "temp_mod" ) ) {
         JsonArray temp_array = jo.get_array( "temp_mod" );
         temp_min = units::from_legacy_bodypart_temp_delta( temp_array.get_int( 0 ) );
         temp_max = units::from_legacy_bodypart_temp_delta( temp_array.get_int( 1 ) );
     }
     if( jo.has_array( "unarmed_damage" ) ) {
         unarmed_bonus = true;
         damage = damage_instance();
         damage = load_damage_instance( jo.get_array( "unarmed_damage" ) );
     }
     if( jo.has_object( "armor" ) ) {
         armor = resistances();
         armor = load_resistances_instance( jo.get_object( "armor" ) );
     }
     mandatory( jo, was_loaded, "side", part_side );
     mandatory( jo, was_loaded, "sub_parts", sub_parts );
     if( jo.has_array( "encumbrance_per_weight" ) ) {
         const JsonArray &jarr = jo.get_array( "encumbrance_per_weight" );
         for( const JsonObject jval : jarr ) {
             units::mass weight = 0_gram;
             int encumbrance = 0;
             assign( jval, "weight", weight, true );
             mandatory( jval, was_loaded, "encumbrance", encumbrance );
             encumbrance_per_weight.insert( std::pair<units::mass, int>( weight, encumbrance ) );
         }
     }
 }
References _primary_limb_type, accusative, accusative_multiple, armor, assign(), base_hp, bionic_slots_, bmi_encumbrance_scalar, bmi_encumbrance_threshold, cold_morale_mod, conditional_flags, connected_to, damage, drench_increment, drench_max, drying_rate, effects_on_hit, encumb_text, encumbrance_limit, encumbrance_per_weight, encumbrance_threshold, env_protection, feels_discomfort, fire_warmth_bonus, flags, units::from_legacy_bodypart_temp_delta(), JsonArray::get_array(), JsonObject::get_array(), JsonArray::get_float(), JsonArray::get_int(), JsonObject::get_object(), JsonArray::get_string(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_object(), heal_bonus, health_limit, irradiance::high, hit_difficulty, hit_size, hot_morale_mod, hp_bar_ui_text, hp_mods, id, is_limb, is_vital, legacy_id, legacy_id_to_enum(), limb_scores, limbtypes, bp_onhit_effect::load(), load_damage_instance(), load_resistances_instance(), main_part, mandatory, bp_limb_score::max, mend_rate, name, name_as_heading, name_as_heading_multiple, name_multiple, no_power_effect, string_id< effect_type >::NULL_ID(), num_bp, num_types, opposite_part, optional(), part_side, power_efficiency, bp_limb_score::score, similar_bodyparts, smash_efficiency, smash_message, squeamish_penalty, stylish_bonus, sub_parts, technique_enc_limit, techniques, temp_max, temp_min, units::to_legacy_bodypart_temp_delta(), token, ugliness, ugliness_mandatory, unarmed_bonus, was_loaded, wet_morale, and windage_effect.
load_bp()
void body_part_type::load_bp (const JsonObject & jo, const std::string & src) static
Definition at line 242 of file bodypart.cpp.
 {
     body_part_factory.load( jo, src );
 }
References anonymous_namespace{bodypart.cpp}::body_part_factory, and src.
Referenced by DynamicDataLoader::initialize().
primary_limb_type()
body_part_type::type body_part_type::primary_limb_type () const
Definition at line 247 of file bodypart.cpp.
 {
     return _primary_limb_type;
 }
References _primary_limb_type.
Referenced by Creature::get_part_id().
random_sub_part()
sub_bodypart_id body_part_type::random_sub_part (bool secondary) const
Definition at line 262 of file bodypart.cpp.
 {
     int total_weight = 0;
     for( const sub_bodypart_str_id &bp : sub_parts ) {
         // filter for secondary sub locations
         if( secondary == bp->secondary ) {
             total_weight += bp->max_coverage;
         }
     }
     int roll = rng( 1, total_weight );
     for( const sub_bodypart_str_id &bp : sub_parts ) {
         // filter for secondary sub locations
         if( secondary == bp->secondary ) {
             if( roll <= bp->max_coverage ) {
                 return bp.id();
             }
             roll = roll - bp->max_coverage;
         }
     }
     // should never get here
     return sub_bodypart_id();
 }
References bp, int_id< T >::id(), rng(), and sub_parts.
Referenced by outfit::absorb_damage().
reset()
void body_part_type::reset () static
Definition at line 500 of file bodypart.cpp.
 {
     body_part_factory.reset();
 }
References anonymous_namespace{bodypart.cpp}::body_part_factory.
Referenced by DynamicDataLoader::unload_data().
unarmed_arpen()
float body_part_type::unarmed_arpen (const damage_type_id & dt) const
Definition at line 610 of file bodypart.cpp.
 {
     return damage.type_arpen( dt );
 }
References damage, and damage_instance::type_arpen().
Referenced by Character::roll_damage(), and roll_melee_damage_internal().
unarmed_damage()
float body_part_type::unarmed_damage (const damage_type_id & dt) const
Definition at line 605 of file bodypart.cpp.
 {
     return damage.type_damage( dt );
 }
References damage, and damage_instance::type_damage().
Referenced by Character::roll_damage(), and roll_melee_damage_internal().
Member Data Documentation
_primary_limb_type
body_part_type::type body_part_type::_primary_limb_type = body_part_type::type::num_types private
Definition at line 327 of file bodypart.h.
Referenced by load(), and primary_limb_type().
accusative
translation body_part_type::accusative
Definition at line 250 of file bodypart.h.
Referenced by body_part_name_accusative(), map::drop_items(), and load().
accusative_multiple
translation body_part_type::accusative_multiple
Definition at line 251 of file bodypart.h.
Referenced by body_part_name_accusative(), and load().
armor
resistances body_part_type::armor private
Definition at line 329 of file bodypart.h.
Referenced by check(), damage_resistance(), finalize(), and load().
base_hp
int body_part_type::base_hp = 60
Definition at line 297 of file bodypart.h.
Referenced by load().
bionic_slots_
int body_part_type::bionic_slots_ = 0 private
Definition at line 326 of file bodypart.h.
Referenced by bionic_slots(), and load().
bmi_encumbrance_scalar
float body_part_type::bmi_encumbrance_scalar = 0
Definition at line 282 of file bodypart.h.
Referenced by load().
bmi_encumbrance_threshold
int body_part_type::bmi_encumbrance_threshold = 999
Definition at line 280 of file bodypart.h.
Referenced by load().
cold_morale_mod
float body_part_type::cold_morale_mod = 0.0f
Definition at line 287 of file bodypart.h.
Referenced by load(), and player_morale::update_bodytemp_penalty().
conditional_flags
cata::flat_set<json_character_flag> body_part_type::conditional_flags
Definition at line 214 of file bodypart.h.
Referenced by load().
connected_to
bodypart_str_id body_part_type::connected_to
Definition at line 229 of file bodypart.h.
Referenced by anatomy::check(), check(), load(), anatomy::select_body_part_projectile_attack(), sort_body_parts(), and Character::update_bodytemp().
damage
damage_instance body_part_type::damage private
Definition at line 219 of file bodypart.h.
Referenced by check(), load(), unarmed_arpen(), and unarmed_damage().
drench_increment
int body_part_type::drench_increment = 2
Definition at line 312 of file bodypart.h.
Referenced by Character::drench(), and load().
drench_max
int body_part_type::drench_max = 0
Definition at line 311 of file bodypart.h.
Referenced by bodypart::get_wetness_percentage(), and load().
drying_rate
float body_part_type::drying_rate = 1.0f
Definition at line 313 of file bodypart.h.
Referenced by load(), and Character::update_body_wetness().
effects_on_hit
std::vector<bp_onhit_effect> body_part_type::effects_on_hit
Definition at line 245 of file bodypart.h.
Referenced by bodypart::get_onhit_effects(), and load().
encumb_text
translation body_part_type::encumb_text
Definition at line 256 of file bodypart.h.
Referenced by encumb_text(), get_encumbrance_description(), and load().
encumbrance_limit
int body_part_type::encumbrance_limit = 0
Definition at line 275 of file bodypart.h.
Referenced by load().
encumbrance_per_weight
std::map<units::mass, int> body_part_type::encumbrance_per_weight
Definition at line 211 of file bodypart.h.
Referenced by armor_portion_data::calc_encumbrance(), and load().
encumbrance_threshold
int body_part_type::encumbrance_threshold = 0
Definition at line 273 of file bodypart.h.
Referenced by load().
env_protection
int body_part_type::env_protection = 0
Definition at line 295 of file bodypart.h.
Referenced by load().
feels_discomfort
bool body_part_type::feels_discomfort = true
Definition at line 290 of file bodypart.h.
Referenced by Character::calc_discomfort(), and load().
fire_warmth_bonus
units::temperature_delta body_part_type::fire_warmth_bonus = 0_C_delta
Definition at line 292 of file bodypart.h.
Referenced by load(), and Character::update_bodytemp().
flags
cata::flat_set<json_character_flag> body_part_type::flags
Definition at line 213 of file bodypart.h.
Referenced by has_flag(), and load().
heal_bonus
int body_part_type::heal_bonus = 0
Definition at line 299 of file bodypart.h.
Referenced by Character::heal(), and load().
health_limit
int body_part_type::health_limit = 0
Definition at line 277 of file bodypart.h.
Referenced by bodypart::get_limb_techs(), and load().
hit_difficulty
float body_part_type::hit_difficulty = 0.0f
How hard is it to hit a given body part, assuming "owner" is hit.
Higher number means good hits will veer towards this part, lower means this part is unlikely to be hit by inaccurate attacks. Formula is chance *= pow(hit_roll, hit_difficulty)
Definition at line 267 of file bodypart.h.
Referenced by load(), and anatomy::select_body_part().
hit_size
float body_part_type::hit_size = 0.0f
Size of the body part for melee targeting.
Definition at line 260 of file bodypart.h.
Referenced by anatomy::add_body_part(), anatomy::get_all_eligable_parts(), anatomy::get_hit_size_sum(), anatomy::get_organic_size_sum(), load(), anatomy::select_body_part(), and anatomy::select_body_part_projectile_attack().
hot_morale_mod
float body_part_type::hot_morale_mod = 0.0f
Definition at line 286 of file bodypart.h.
Referenced by load(), and player_morale::update_bodytemp_penalty().
hp_bar_ui_text
translation body_part_type::hp_bar_ui_text
Definition at line 255 of file bodypart.h.
Referenced by body_part_hp_bar_ui_text(), and load().
hp_mods
stat_hp_mods body_part_type::hp_mods
Definition at line 332 of file bodypart.h.
Referenced by load().
id
bodypart_str_id body_part_type::id
Definition at line 222 of file bodypart.h.
Referenced by basic_item_filter(), check(), load(), armor_portion_data::max_coverage(), Character::on_damage_of_type(), and debug_menu::wisheffect().
is_limb
bool body_part_type::is_limb = false
Definition at line 336 of file bodypart.h.
Referenced by load().
is_vital
bool body_part_type::is_vital = false
Definition at line 335 of file bodypart.h.
Referenced by Character::is_dead_state(), load(), and Character::prevent_death().
legacy_id
std::string body_part_type::legacy_id
Definition at line 224 of file bodypart.h.
Referenced by load().
limb_scores
std::map<limb_score_id, bp_limb_score> body_part_type::limb_scores private
Definition at line 218 of file bodypart.h.
Referenced by check(), get_limb_score(), get_limb_score_max(), has_limb_score(), and load().
limbtypes
std::map<body_part_type::type, float> body_part_type::limbtypes
Definition at line 234 of file bodypart.h.
Referenced by character_martial_arts::can_arm_block(), character_martial_arts::can_leg_block(), Creature::get_part_id(), has_type(), and load().
main_part
bodypart_str_id body_part_type::main_part
Definition at line 226 of file bodypart.h.
Referenced by Creature::add_effect(), Character::apply_damage(), Character::bionics_install_failure(), Character::bionics_uninstall_failure(), anatomy::check(), check(), Creature::get_random_body_part(), load(), Character::on_damage_of_type(), Creature::random_body_part(), Character::roll_critical_bionics_failure(), and Character::update_bodytemp().
mend_rate
float body_part_type::mend_rate = 1.0f
Definition at line 300 of file bodypart.h.
Referenced by load(), and Character::mend().
name
translation body_part_type::name
Definition at line 248 of file bodypart.h.
Referenced by body_part_name(), melee_actor::call(), debug_menu::character_edit_menu(), melee_actor::do_grab(), load(), Character::most_staunchable_bp(), bite_actor::on_damage(), Character::on_damage_of_type(), outfit::prepare_bodymap_info(), and sort_body_parts().
name_as_heading
translation body_part_type::name_as_heading
Definition at line 252 of file bodypart.h.
Referenced by body_part_name_as_heading(), consolidate(), and load().
name_as_heading_multiple
translation body_part_type::name_as_heading_multiple
Definition at line 253 of file bodypart.h.
Referenced by body_part_name_as_heading(), consolidate(), and load().
name_multiple
translation body_part_type::name_multiple
Definition at line 249 of file bodypart.h.
Referenced by body_part_name(), and load().
no_power_effect
efftype_id body_part_type::no_power_effect
Definition at line 242 of file bodypart.h.
Referenced by load(), and Character::mod_power_level().
opposite_part
bodypart_str_id body_part_type::opposite_part
Definition at line 231 of file bodypart.h.
Referenced by check(), consolidate(), suffer::from_sunburn(), list_and_combine_bps(), load(), should_combine_bps(), and sort_body_parts().
part_side
side body_part_type::part_side = side::BOTH
Definition at line 270 of file bodypart.h.
Referenced by Creature::get_part_id(), outfit::is_wearing_shoes(), and load().
power_efficiency
int body_part_type::power_efficiency = 0
Definition at line 319 of file bodypart.h.
Referenced by load(), and Character::recalc_limb_energy_usage().
similar_bodyparts
std::vector<bodypart_str_id> body_part_type::similar_bodyparts
Definition at line 323 of file bodypart.h.
Referenced by Item_factory::finalize_post_armor(), and load().
smash_efficiency
float body_part_type::smash_efficiency = 0.5f
Definition at line 283 of file bodypart.h.
Referenced by load().
smash_message
translation body_part_type::smash_message
Definition at line 254 of file bodypart.h.
Referenced by load().
squeamish_penalty
int body_part_type::squeamish_penalty = 0
Definition at line 289 of file bodypart.h.
Referenced by load().
src
std::vector<std::pair<bodypart_str_id, mod_id> > body_part_type::src
Definition at line 205 of file bodypart.h.
Referenced by load_bp().
stylish_bonus
float body_part_type::stylish_bonus = 0.0f
Definition at line 288 of file bodypart.h.
Referenced by load().
sub_parts
std::vector<sub_bodypart_str_id> body_part_type::sub_parts
Sub-location of the body part used for encumberance, coverage and determining protection.
Definition at line 209 of file bodypart.h.
Referenced by outfit::absorb_damage(), item::armor_info(), basic_item_filter(), Item_factory::finalize_post_armor(), outfit::get_item_penalties(), item::get_warmth(), layer_item(), load(), armor_portion_data::max_coverage(), bodygraph_display::prepare_infolist(), and random_sub_part().
technique_enc_limit
int body_part_type::technique_enc_limit = 50
Definition at line 316 of file bodypart.h.
Referenced by bodypart::get_limb_techs(), and load().
techniques
std::set<matec_id> body_part_type::techniques
Definition at line 237 of file bodypart.h.
Referenced by bodypart::get_limb_techs(), and load().
temp_max
units::temperature_delta body_part_type::temp_max = 0_C_delta
Definition at line 310 of file bodypart.h.
Referenced by load(), and Character::update_bodytemp().
temp_min
units::temperature_delta body_part_type::temp_min = 0_C_delta
Definition at line 308 of file bodypart.h.
Referenced by load(), and Character::update_bodytemp().
token
body_part body_part_type::token = num_bp
Definition at line 258 of file bodypart.h.
Referenced by check(), and load().
ugliness
int body_part_type::ugliness = 0
Definition at line 303 of file bodypart.h.
Referenced by npc::get_opinion_values(), and load().
ugliness_mandatory
int body_part_type::ugliness_mandatory = 0
Definition at line 305 of file bodypart.h.
Referenced by npc::get_opinion_values(), and load().
unarmed_bonus
bool body_part_type::unarmed_bonus = false
Definition at line 333 of file bodypart.h.
Referenced by load(), Character::roll_damage(), and roll_melee_damage_internal().
was_loaded
bool body_part_type::was_loaded = false
Definition at line 338 of file bodypart.h.
Referenced by load().
wet_morale
int body_part_type::wet_morale = 0
Definition at line 315 of file bodypart.h.
Referenced by Character::apply_wetness_morale(), and load().
windage_effect
efftype_id body_part_type::windage_effect
Definition at line 240 of file bodypart.h.
Referenced by load(), and Character::mod_stamina().
The documentation for this struct was generated from the following files:
src/bodypart.h
src/bodypart.cpp