Cataclysm DDA: oter_type_t Struct Reference
oter_type_t Struct Reference
#include <omdata.h>
Public Member Functions
std::string get_symbol () const
oter_type_t ()=default
oter_id get_first () const
oter_id get_rotated (om_direction::type dir) const
oter_id get_linear (size_t n) const
bool has_flag (oter_flags flag) const
void set_flag (oter_flags flag, bool value=true)
void load (const JsonObject &jo, const std::string &src)
void check () const
void finalize ()
bool is_rotatable () const
bool is_linear () const
bool has_connections () const
bool connects_to (const oter_type_id &other) const
Public Attributes
string_id< oter_type_t > id
std::vector< std::pair< string_id< oter_type_t >, mod_id > > src
translation name
uint32_t symbol = 0
nc_color color = c_black
overmap_land_use_code_id land_use_code = overmap_land_use_code_id::NULL_ID()
std::vector< std::string > looks_like
unsigned char see_cost = 0
oter_travel_cost_type travel_cost_type
std::string extras = "none"
int mondensity = 0
effect_on_condition_id entry_EOC
effect_on_condition_id exit_EOC
overmap_static_spawns static_spawns
bool was_loaded = false
Static Public Attributes
static const oter_type_t null_type {}
Private Member Functions
void register_terrain (const oter_t &peer, size_t n, size_t max_n)
Private Attributes
enum_bitset< oter_flags > flags
std::vector< oter_id > directional_peers
std::string connect_group
Detailed Description
Definition at line 244 of file omdata.h.
Constructor & Destructor Documentation
oter_type_t()
oter_type_t::oter_type_t () default
Member Function Documentation
check()
void oter_type_t::check () const
Definition at line 827 of file overmap.cpp.
 {
 }
connects_to()
bool oter_type_t::connects_to (const oter_type_id & other) const inline
Definition at line 298 of file omdata.h.
{
             return has_connections() && connect_group == other->connect_group;
         }
References has_connections(), and other.
finalize()
void oter_type_t::finalize ()
Definition at line 832 of file overmap.cpp.
 {
     directional_peers.clear();  // In case of a second finalization.
     if( is_rotatable() ) {
         for( om_direction::type dir : om_direction::all ) {
             register_terrain( oter_t( *this, dir ), static_cast<size_t>( dir ), om_direction::size );
         }
     } else if( has_flag( oter_flags::line_drawing ) ) {
         for( size_t i = 0; i < om_lines::size; ++i ) {
             register_terrain( oter_t( *this, i ), i, om_lines::size );
         }
     } else {
         register_terrain( oter_t( *this ), 0, 1 );
     }
 }
References om_direction::all, directional_peers, has_flag(), is_rotatable(), line_drawing, register_terrain(), om_direction::size, and om_lines::size.
get_first()
oter_id oter_type_t::get_first () const
Definition at line 864 of file overmap.cpp.
 {
     cata_assert( !directional_peers.empty() );
     return directional_peers.front();
 }
References cata_assert, and directional_peers.
Referenced by overmap_specials::create_building_from().
get_linear()
oter_id oter_type_t::get_linear (size_t n) const
Definition at line 882 of file overmap.cpp.
 {
     if( !has_flag( oter_flags::line_drawing ) ) {
         debugmsg( "Overmap terrain \"%s \" isn't drawn with lines.", id.c_str() );
         return ot_null;
     }
     if( n >= om_lines::size ) {
         debugmsg( "Invalid overmap line (%d) was asked from overmap terrain \"%s\".", n, id.c_str() );
         return ot_null;
     }
     cata_assert( directional_peers.size() == om_lines::size );
     return directional_peers[n];
 }
References cata_assert, debugmsg, directional_peers, has_flag(), line_drawing, ot_null, and om_lines::size.
Referenced by overmap::build_connection(), and oter_t::get_rotated().
get_rotated()
oter_id oter_type_t::get_rotated (om_direction::type dir) const
Definition at line 870 of file overmap.cpp.
 {
     if( dir == om_direction::type::invalid ) {
         debugmsg( "Invalid rotation was asked from overmap terrain \"%s\".", id.c_str() );
         return ot_null;
     } else if( dir == om_direction::type::none || !is_rotatable() ) {
         return directional_peers.front();
     }
     cata_assert( directional_peers.size() == om_direction::size );
     return directional_peers[static_cast<size_t>( dir )];
 }
References cata_assert, debugmsg, directional_peers, om_direction::invalid, is_rotatable(), om_direction::none, ot_null, and om_direction::size.
Referenced by oter_t::get_rotated().
get_symbol()
std::string oter_type_t::get_symbol () const
Definition at line 732 of file overmap.cpp.
 {
     return utf32_to_utf8( symbol );
 }
References symbol, and utf32_to_utf8().
has_connections()
bool oter_type_t::has_connections () const inline
Definition at line 294 of file omdata.h.
{
             return !connect_group.empty();
         }
Referenced by connects_to().
has_flag()
bool oter_type_t::has_flag (oter_flags flag) const inline
Definition at line 274 of file omdata.h.
{
             return flags[flag];
         }
References flags.
Referenced by finalize(), get_linear(), oter_t::get_mapgen_id(), oter_t::get_rotated(), oter_t::has_flag(), item::io(), oter_t::is_lake(), oter_t::is_lake_shore(), is_linear(), oter_t::is_ocean(), oter_t::is_ocean_shore(), oter_t::is_ravine(), oter_t::is_ravine_edge(), oter_t::is_river(), is_rotatable(), oter_t::is_water(), load(), and npc_follower_rules::serialize().
is_linear()
bool oter_type_t::is_linear () const inline
Definition at line 290 of file omdata.h.
{
             return has_flag( oter_flags::line_drawing );
         }
References has_flag(), and line_drawing.
Referenced by overmap_connection::subtype::allows_turns(), and oter_t::is_linear().
is_rotatable()
bool oter_type_t::is_rotatable () const inline
Definition at line 286 of file omdata.h.
{
             return !has_flag( oter_flags::no_rotate ) && !has_flag( oter_flags::line_drawing );
         }
References has_flag(), line_drawing, and no_rotate.
Referenced by finalize(), get_rotated(), and oter_t::is_rotatable().
load()
void oter_type_t::load (const JsonObject & jo, const std::string & src)
Definition at line 763 of file overmap.cpp.
 {
     const bool strict = src == "dda";
     optional( jo, was_loaded, "sym", symbol, unicode_codepoint_from_symbol_reader, NULL_UNICODE );
     assign( jo, "name", name, strict );
     assign( jo, "see_cost", see_cost, strict );
     assign( jo, "extras", extras, strict );
     assign( jo, "mondensity", mondensity, strict );
     assign( jo, "entry_eoc", entry_EOC, strict );
     assign( jo, "exit_eoc", exit_EOC, strict );
     assign( jo, "spawns", static_spawns, strict );
     assign( jo, "color", color );
     assign( jo, "land_use_code", land_use_code, strict );
     if( jo.has_member( "looks_like" ) ) {
         std::vector<std::string> ll;
         if( jo.has_array( "looks_like" ) ) {
             jo.read( "looks_like", ll );
         } else if( jo.has_string( "looks_like" ) ) {
             const std::string one_look = jo.get_string( "looks_like" );
             ll.push_back( one_look );
         }
         looks_like = ll;
     } else if( jo.has_member( "copy-from" ) ) {
         looks_like.insert( looks_like.begin(), jo.get_string( "copy-from" ) );
     }
     const auto flag_reader = typed_flag_reader<oter_flags>( "overmap terrain flag" );
     optional( jo, was_loaded, "flags", flags, flag_reader );
     optional( jo, was_loaded, "connect_group", connect_group, string_reader{} );
     optional( jo, was_loaded, "travel_cost_type", travel_cost_type, oter_travel_cost_type::other );
     if( has_flag( oter_flags::line_drawing ) ) {
         if( has_flag( oter_flags::no_rotate ) ) {
             jo.throw_error( R"(Mutually exclusive flags: "NO_ROTATE" and "LINEAR".)" );
         }
         for( const auto &elem : om_lines::mapgen_suffixes ) {
             load_overmap_terrain_mapgens( jo, id.str(), elem );
         }
         if( symbol == NULL_UNICODE ) {
             // Default the sym for linear terrains to a specific value which
             // has special behaviour when using fallback ASCII tiles so as to
             // cause it to draw using the box drawing characters (see
             // load_ascii_set).
             symbol = LINE_XOXO_C;
         }
     } else {
         if( symbol == NULL_UNICODE && !jo.has_string( "abstract" ) ) {
             DebugLog( D_ERROR, D_MAP_GEN ) << "sym is not defined for overmap_terrain: "
                                            << id.c_str() << " (" << name << ")";
         }
         if( !jo.has_string( "sym" ) && jo.has_number( "sym" ) ) {
             debugmsg( "sym is defined as number instead of string for overmap_terrain %s (%s)", id.c_str(),
                       name );
         }
         load_overmap_terrain_mapgens( jo, id.str() );
     }
 }
References assign(), color, D_ERROR, D_MAP_GEN, DebugLog(), debugmsg, entry_EOC, exit_EOC, extras, flags, JsonObject::get_string(), JsonObject::has_array(), has_flag(), JsonObject::has_member(), JsonObject::has_number(), JsonObject::has_string(), land_use_code, line_drawing, LINE_XOXO_C, load_overmap_terrain_mapgens(), looks_like, om_lines::mapgen_suffixes, mondensity, name, no_rotate, NULL_UNICODE, optional(), other, JsonObject::read(), see_cost, src, static_spawns, strict, symbol, JsonObject::throw_error(), travel_cost_type, unicode_codepoint_from_symbol_reader(), and was_loaded.
register_terrain()
void oter_type_t::register_terrain (const oter_t & peer, size_t n, size_t max_n) private
Definition at line 849 of file overmap.cpp.
 {
     cata_assert( n < max_n );
     cata_assert( peer.type_is( *this ) );
     directional_peers.resize( max_n );
     if( peer.id.is_valid() ) {
         directional_peers[n] = peer.id.id();
         debugmsg( "Can't register the new overmap terrain \"%s\". It already exists.", peer.id.c_str() );
     } else {
         directional_peers[n] = terrains.insert( peer ).id.id();
     }
 }
References string_id< T >::c_str(), cata_assert, debugmsg, directional_peers, oter_t::id, string_id< T >::id(), string_id< T >::is_valid(), anonymous_namespace{overmap.cpp}::terrains, and oter_t::type_is().
Referenced by finalize().
set_flag()
void oter_type_t::set_flag (oter_flags flag, bool value = true) inline
Definition at line 278 of file omdata.h.
{
             flags.set( flag, value );
         }
References flags, and enum_bitset< E >::set().
Referenced by npc_follower_rules::deserialize().
Member Data Documentation
color
nc_color oter_type_t::color = c_black
Definition at line 252 of file omdata.h.
Referenced by oter_t::get_color(), and load().
connect_group
std::string oter_type_t::connect_group private
Definition at line 305 of file omdata.h.
directional_peers
std::vector<oter_id> oter_type_t::directional_peers private
Definition at line 304 of file omdata.h.
Referenced by finalize(), get_first(), get_linear(), get_rotated(), and register_terrain().
entry_EOC
effect_on_condition_id oter_type_t::entry_EOC
Definition at line 260 of file omdata.h.
Referenced by oter_t::get_entry_EOC(), and load().
exit_EOC
effect_on_condition_id oter_type_t::exit_EOC
Definition at line 261 of file omdata.h.
Referenced by oter_t::get_exit_EOC(), and load().
extras
std::string oter_type_t::extras = "none"
Definition at line 258 of file omdata.h.
Referenced by oter_t::get_extras(), and load().
flags
enum_bitset<oter_flags> oter_type_t::flags private
Definition at line 303 of file omdata.h.
Referenced by vehicle_part::deserialize(), has_flag(), load(), vehicle_part::serialize(), and set_flag().
id
string_id<oter_type_t> oter_type_t::id
Definition at line 248 of file omdata.h.
Referenced by oter_t::get_mapgen_id(), oter_t::get_type_id(), and oter_t::type_is().
land_use_code
overmap_land_use_code_id oter_type_t::land_use_code = overmap_land_use_code_id::NULL_ID()
Definition at line 253 of file omdata.h.
Referenced by oter_t::get_color(), oter_t::get_land_use_code(), oter_t::is_wooded(), and load().
looks_like
std::vector<std::string> oter_type_t::looks_like
Definition at line 254 of file omdata.h.
Referenced by load().
mondensity
int oter_type_t::mondensity = 0
Definition at line 259 of file omdata.h.
Referenced by oter_t::get_mondensity(), and load().
name
translation oter_type_t::name
Definition at line 250 of file omdata.h.
Referenced by oter_t::get_name(), and load().
null_type
const oter_type_t oter_type_t::null_type {} static
Definition at line 246 of file omdata.h.
see_cost
unsigned char oter_type_t::see_cost = 0
Definition at line 255 of file omdata.h.
Referenced by oter_t::get_see_cost(), and load().
src
std::vector<std::pair<string_id<oter_type_t>, mod_id> > oter_type_t::src
Definition at line 249 of file omdata.h.
Referenced by overmap_specials::create_building_from(), overmapbuffer::get_description_at(), and load().
static_spawns
overmap_static_spawns oter_type_t::static_spawns
Definition at line 263 of file omdata.h.
Referenced by oter_t::get_static_spawns(), and load().
symbol
uint32_t oter_type_t::symbol = 0
Definition at line 251 of file omdata.h.
Referenced by get_symbol(), and load().
travel_cost_type
oter_travel_cost_type oter_type_t::travel_cost_type
Initial value:
=
            oter_travel_cost_type::other
Definition at line 256 of file omdata.h.
Referenced by oter_t::get_travel_cost_type(), and load().
was_loaded
bool oter_type_t::was_loaded = false
Definition at line 264 of file omdata.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/omdata.h
src/overmap.cpp