Cataclysm DDA: mapgen_value< Id >::id_source Struct Reference
mapgen_value< Id >::id_source Struct Reference
Public Member Functions
id_source (const std::string &s)
id_source (const Id_unless_string &s)
Id get (const mapgendata &) const override
void check (const std::string &context, const mapgen_parameters &) const override
void check_consistent_with (const value_source &o, const std::string &context) const override
std::vector< StringId > all_possible_results (const mapgen_parameters &) const override
Public Member Functions inherited from mapgen_value< Id >::value_source
virtual ~value_source ()=default
virtual const std::string * get_name_if_parameter () const
Public Attributes
Id id
Detailed Description
template<typename Id>
struct mapgen_value< Id >::id_source
Definition at line 1247 of file mapgen.cpp.
Constructor & Destructor Documentation
id_source() [1/2]
template<typename Id > mapgen_value< Id >::id_source::id_source (const std::string & s) inline explicit
Definition at line 1250 of file mapgen.cpp.
                                                      :
                 id( s ) {
             }
id_source() [2/2]
template<typename Id > mapgen_value< Id >::id_source::id_source (const Id_unless_string & s) inline explicit
Definition at line 1254 of file mapgen.cpp.
                                                             :
                 id( s ) {
             }
Member Function Documentation
all_possible_results()
template<typename Id > std::vector<StringId> mapgen_value< Id >::id_source::all_possible_results (const mapgen_parameters &) const inline override virtual
Implements mapgen_value< Id >::value_source.
Definition at line 1282 of file mapgen.cpp.
{
                 return { to_string_id_helper( id ) };
             }
References to_string_id_helper().
check()
template<typename Id > void mapgen_value< Id >::id_source::check (const std::string & context, const mapgen_parameters &) const inline override virtual
Reimplemented from mapgen_value< Id >::value_source.
Definition at line 1262 of file mapgen.cpp.
{
                 if( !is_valid_helper( id ) ) {
                     debugmsg( "mapgen '%s' uses invalid entry '%s'",
                               context, cata_variant( id ).get_string() );
                 }
             }
References context, debugmsg, and is_valid_helper().
check_consistent_with()
template<typename Id > void mapgen_value< Id >::id_source::check_consistent_with (const value_source & o, const std::string & context) const inline override virtual
Implements mapgen_value< Id >::value_source.
Definition at line 1269 of file mapgen.cpp.
{
                 if( const id_source *other = dynamic_cast<const id_source *>( &o ) ) {
                     if( id != other->id ) {
                         debugmsg( "inconsistent default values for %s (%s vs %s)",
                                   context, cata_variant( id ).get_string(),
                                   cata_variant( other->id ).get_string() );
                     }
                 } else {
                     debugmsg( "inconsistent default types for %s", context );
                 }
             }
References context, debugmsg, cata_variant::get_string(), and other.
get()
template<typename Id > Id mapgen_value< Id >::id_source::get (const mapgendata &) const inline override virtual
Implements mapgen_value< Id >::value_source.
Definition at line 1258 of file mapgen.cpp.
{
                 return id;
             }
References mapgen_value< Id >::id_source::id.
Member Data Documentation
id
template<typename Id > Id mapgen_value< Id >::id_source::id
Definition at line 1248 of file mapgen.cpp.
Referenced by mapgen_value< Id >::id_source::get().
The documentation for this struct was generated from the following file:
src/mapgen.cpp