Cataclysm DDA: repetition_folder Struct Reference
repetition_folder Struct Reference
Public Member Functions
bool test (const char *filename, const char *line, const char *funcname, const std::string &text) const
void set_time ()
void set (const char *filename, const char *line, const char *funcname, const std::string &text)
void increment_count ()
void reset ()
bool timed_out () const
Public Attributes
const char * m_filename = nullptr
const char * m_line = nullptr
const char * m_funcname = nullptr
std::string m_text
time_info m_time
int repeat_count = 0
Static Public Attributes
static constexpr time_info timeout = { 0, 0, 0, 100 }
static constexpr int repetition_threshold = 10000
Detailed Description
Definition at line 439 of file debug.cpp.
Member Function Documentation
increment_count()
void repetition_folder::increment_count () inline
Definition at line 472 of file debug.cpp.
{
         ++repeat_count;
         set_time();
     }
Referenced by realDebugmsg().
reset()
void repetition_folder::reset () inline
Definition at line 476 of file debug.cpp.
                  {
         m_filename = nullptr;
         m_line = nullptr;
         m_funcname = nullptr;
         m_time = time_info{0, 0, 0, 0};
         repeat_count = 0;
     }
Referenced by output_repetitions().
set()
void repetition_folder::set (const char * filename, const char * line, const char * funcname, const std::string & text) inline
Definition at line 462 of file debug.cpp.
{
         m_filename = filename;
         m_line = line;
         m_funcname = funcname;
         m_text = text;
         set_time();
         repeat_count = 0;
     }
References line().
Referenced by realDebugmsg().
set_time()
void repetition_folder::set_time () inline
Definition at line 459 of file debug.cpp.
                     {
         m_time = get_time();
     }
References get_time().
Referenced by realDebugmsg().
test()
bool repetition_folder::test (const char * filename, const char * line, const char * funcname, const std::string & text) const inline
Definition at line 451 of file debug.cpp.
{
         return m_filename == filename &&
                m_line == line &&
                m_funcname == funcname &&
                m_text == text &&
                !timed_out();
     }
References line().
Referenced by realDebugmsg().
timed_out()
bool repetition_folder::timed_out () const inline
Definition at line 486 of file debug.cpp.
{
         const time_info now = get_time();
         const int now_raw = now.mseconds + 1000 * now.seconds + 60000 * now.minutes + 3600000 * now.hours;
         const int old_raw = m_time.mseconds + 1000 * m_time.seconds + 60000 * m_time.minutes + 3600000 *
                             m_time.hours;
         const int timeout_raw = timeout.mseconds + 1000 * timeout.seconds + 60000 * timeout.minutes +
                                 3600000 * timeout.hours;
         return ( now_raw - old_raw ) > timeout_raw;
     }
References get_time(), time_info::hours, time_info::minutes, time_info::mseconds, time_info::seconds, and timeout.
Member Data Documentation
m_filename
const char* repetition_folder::m_filename = nullptr
Definition at line 440 of file debug.cpp.
Referenced by output_repetitions().
m_funcname
const char* repetition_folder::m_funcname = nullptr
Definition at line 442 of file debug.cpp.
Referenced by output_repetitions().
m_line
const char* repetition_folder::m_line = nullptr
Definition at line 441 of file debug.cpp.
Referenced by output_repetitions().
m_text
std::string repetition_folder::m_text
Definition at line 443 of file debug.cpp.
Referenced by output_repetitions().
m_time
time_info repetition_folder::m_time
Definition at line 444 of file debug.cpp.
Referenced by output_repetitions().
repeat_count
int repetition_folder::repeat_count = 0
Definition at line 449 of file debug.cpp.
Referenced by output_repetitions(), and realDebugmsg().
repetition_threshold
constexpr int repetition_folder::repetition_threshold = 10000 static constexpr
Definition at line 447 of file debug.cpp.
Referenced by realDebugmsg().
timeout
constexpr time_info repetition_folder::timeout = { 0, 0, 0, 100 } static constexpr
Definition at line 446 of file debug.cpp.
The documentation for this struct was generated from the following file:
src/debug.cpp