Cataclysm DDA: add_type Struct Reference
add_type Struct Reference
#include <addiction.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
const translation & get_name () const
const translation & get_type_name () const
Returns the name of an addiction.
const translation & get_description () const
const morale_type & get_craving_morale () const
const effect_on_condition_id & get_effect () const
const std::string & get_builtin () const
Static Public Member Functions
static void load_add_types (const JsonObject &jo, const std::string &src)
static void reset ()
static void check_add_types ()
static const std::vector< add_type > & get_all ()
Public Attributes
addiction_id id
bool was_loaded = false
Private Attributes
translation _type_name
translation _name
translation _desc
morale_type _craving_morale
effect_on_condition_id _effect
std::string _builtin
Detailed Description
Definition at line 17 of file addiction.h.
Member Function Documentation
check_add_types()
void add_type::check_add_types () static
Definition at line 367 of file addiction.cpp.
 {
     for( const add_type &add : add_type::get_all() ) {
         if( add._effect.is_null() == add._builtin.empty() ) {
             debugmsg( "addiction_type \"%s\" defines %s effect_on_condition %s builtin.  Addictions must define either field, but not both.",
                       add.id.c_str(), add._builtin.empty() ? "neither" : "both", add._builtin.empty() ? "or" : "and" );
         }
         if( !add._builtin.empty() && builtin_map.find( add._builtin ) == builtin_map.end() ) {
             debugmsg( "invalid builtin \"%s\" for addiction_type \"%s\"", add._builtin, add.id.c_str() );
         }
     }
 }
References add, builtin_map, debugmsg, and get_all().
Referenced by DynamicDataLoader::check_consistency().
get_all()
const std::vector< add_type > & add_type::get_all () static
Definition at line 63 of file addiction.cpp.
 {
     return add_type_factory.get_all();
 }
References anonymous_namespace{addiction.cpp}::add_type_factory.
Referenced by check_add_types().
get_builtin()
const std::string& add_type::get_builtin () const inline
Definition at line 53 of file addiction.h.
{
             return _builtin;
         }
References _builtin.
Referenced by addiction::run_effect().
get_craving_morale()
const morale_type& add_type::get_craving_morale () const inline
Definition at line 47 of file addiction.h.
{
             return _craving_morale;
         }
References _craving_morale.
get_description()
const translation& add_type::get_description () const inline
Definition at line 44 of file addiction.h.
{
             return _desc;
         }
References _desc.
Referenced by draw_effects_summary().
get_effect()
const effect_on_condition_id& add_type::get_effect () const inline
Definition at line 50 of file addiction.h.
{
             return _effect;
         }
References _effect.
Referenced by addiction::run_effect().
get_name()
const translation& add_type::get_name () const inline
Definition at line 34 of file addiction.h.
{
             return _name;
         }
References _name.
Referenced by draw_effects_summary().
get_type_name()
const translation& add_type::get_type_name () const inline
Returns the name of an addiction.
It should be able to finish the sentence "Became addicted to ______".
Definition at line 41 of file addiction.h.
{
             return _type_name;
         }
References _type_name.
load()
void add_type::load (const JsonObject & jo, std::string_view src)
Definition at line 357 of file addiction.cpp.
 {
     mandatory( jo, was_loaded, "name", _name );
     mandatory( jo, was_loaded, "type_name", _type_name );
     mandatory( jo, was_loaded, "description", _desc );
     optional( jo, was_loaded, "craving_morale", _craving_morale, MORALE_NULL );
     optional( jo, was_loaded, "effect_on_condition", _effect );
     optional( jo, was_loaded, "builtin", _builtin );
 }
References _builtin, _craving_morale, _desc, _effect, _name, _type_name, mandatory, MORALE_NULL, optional(), and was_loaded.
load_add_types()
void add_type::load_add_types (const JsonObject & jo, const std::string & src) static
Definition at line 53 of file addiction.cpp.
 {
     add_type_factory.load( jo, src );
 }
References anonymous_namespace{addiction.cpp}::add_type_factory.
Referenced by DynamicDataLoader::initialize().
reset()
void add_type::reset () static
Definition at line 58 of file addiction.cpp.
 {
     add_type_factory.reset();
 }
References anonymous_namespace{addiction.cpp}::add_type_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
_builtin
std::string add_type::_builtin private
Definition at line 24 of file addiction.h.
Referenced by get_builtin(), and load().
_craving_morale
morale_type add_type::_craving_morale private
Definition at line 22 of file addiction.h.
Referenced by get_craving_morale(), and load().
_desc
translation add_type::_desc private
Definition at line 21 of file addiction.h.
Referenced by get_description(), and load().
_effect
effect_on_condition_id add_type::_effect private
Definition at line 23 of file addiction.h.
Referenced by get_effect(), and load().
_name
translation add_type::_name private
Definition at line 20 of file addiction.h.
Referenced by get_name(), and load().
_type_name
translation add_type::_type_name private
Definition at line 19 of file addiction.h.
Referenced by get_type_name(), and load().
id
addiction_id add_type::id
Definition at line 26 of file addiction.h.
was_loaded
bool add_type::was_loaded = false
Definition at line 27 of file addiction.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/addiction.h
src/addiction.cpp