Cataclysm DDA: region_terrain_and_furniture_settings Struct Reference
region_terrain_and_furniture_settings Struct Reference
#include <regional_settings.h>
Public Member Functions
void finalize ()
ter_id resolve (const ter_id &) const
furn_id resolve (const furn_id &) const
region_terrain_and_furniture_settings ()=default
Public Attributes
std::map< std::string, std::map< std::string, int > > unfinalized_terrain
std::map< std::string, std::map< std::string, int > > unfinalized_furniture
std::map< ter_id, weighted_int_list< ter_id > > terrain
std::map< furn_id, weighted_int_list< furn_id > > furniture
Detailed Description
Definition at line 258 of file regional_settings.h.
Constructor & Destructor Documentation
region_terrain_and_furniture_settings()
region_terrain_and_furniture_settings::region_terrain_and_furniture_settings () default
Member Function Documentation
finalize()
void region_terrain_and_furniture_settings::finalize ()
Definition at line 984 of file regional_settings.cpp.
 {
     for( auto const &template_pr : unfinalized_terrain ) {
         const ter_str_id template_tid( template_pr.first );
         if( !template_tid.is_valid() ) {
             debugmsg( "Tried to add invalid regional template terrain %s to region_terrain_and_furniture terrain.",
                       template_tid.c_str() );
             continue;
         }
         for( auto const &actual_pr : template_pr.second ) {
             const ter_str_id tid( actual_pr.first );
             if( !tid.is_valid() ) {
                 debugmsg( "Tried to add invalid regional terrain %s to region_terrain_and_furniture terrain template %s.",
                           tid.c_str(), template_tid.c_str() );
                 continue;
             }
             terrain[template_tid.id()].add( tid.id(), actual_pr.second );
         }
     }
     for( auto const &template_pr : unfinalized_furniture ) {
         const furn_str_id template_fid( template_pr.first );
         if( !template_fid.is_valid() ) {
             debugmsg( "Tried to add invalid regional template furniture %s to region_terrain_and_furniture furniture.",
                       template_fid.c_str() );
             continue;
         }
         for( auto const &actual_pr : template_pr.second ) {
             const furn_str_id fid( actual_pr.first );
             if( !fid.is_valid() ) {
                 debugmsg( "Tried to add invalid regional furniture %s to region_terrain_and_furniture furniture template %s.",
                           fid.c_str(), template_fid.c_str() );
                 continue;
             }
             furniture[template_fid.id()].add( fid.id(), actual_pr.second );
         }
     }
 }
References string_id< T >::c_str(), debugmsg, furniture, string_id< T >::id(), string_id< T >::is_valid(), terrain, unfinalized_furniture, and unfinalized_terrain.
Referenced by regional_settings::finalize().
resolve() [1/2]
furn_id region_terrain_and_furniture_settings::resolve (const furn_id & fid) const
Definition at line 1034 of file regional_settings.cpp.
 {
     furn_id result = fid;
     auto region_list = furniture.find( result );
     while( region_list != furniture.end() ) {
         result = *region_list->second.pick();
         region_list = furniture.find( result );
     }
     return result;
 }
References furniture.
resolve() [2/2]
ter_id region_terrain_and_furniture_settings::resolve (const ter_id & tid) const
Definition at line 1023 of file regional_settings.cpp.
 {
     ter_id result = tid;
     auto region_list = terrain.find( result );
     while( region_list != terrain.end() ) {
         result = *region_list->second.pick();
         region_list = terrain.find( result );
     }
     return result;
 }
References terrain.
Referenced by resolve_regional_terrain_and_furniture().
Member Data Documentation
furniture
std::map<furn_id, weighted_int_list<furn_id> > region_terrain_and_furniture_settings::furniture
Definition at line 262 of file regional_settings.h.
Referenced by finalize(), and resolve().
terrain
std::map<ter_id, weighted_int_list<ter_id> > region_terrain_and_furniture_settings::terrain
Definition at line 261 of file regional_settings.h.
Referenced by finalize(), and resolve().
unfinalized_furniture
std::map<std::string, std::map<std::string, int> > region_terrain_and_furniture_settings::unfinalized_furniture
Definition at line 260 of file regional_settings.h.
Referenced by finalize(), and load_region_terrain_and_furniture_settings().
unfinalized_terrain
std::map<std::string, std::map<std::string, int> > region_terrain_and_furniture_settings::unfinalized_terrain
Definition at line 259 of file regional_settings.h.
Referenced by complete_construction(), finalize(), and load_region_terrain_and_furniture_settings().
The documentation for this struct was generated from the following files:
src/regional_settings.h
src/regional_settings.cpp