Cataclysm DDA: joins_tracker::indexed_joins Struct Reference
joins_tracker::indexed_joins Struct Reference
Public Member Functions
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
bool count (const om_pos_dir &p) const
const join * find (const om_pos_dir &p) const
bool any_at (const tripoint_om_omt &pos) const
std::vector< iterator > all_at (const tripoint_om_omt &pos) const
std::size_t count_at (const tripoint_om_omt &pos) const
iterator add (const om_pos_dir &p, const mutable_overmap_join *j)
iterator add (const join &j)
void erase (const iterator it)
void clear ()
Public Attributes
std::list< join > joins
std::unordered_map< om_pos_dir, iterator > position_index
Detailed Description
Definition at line 2005 of file overmap.cpp.
Member Function Documentation
add() [1/2]
iterator joins_tracker::indexed_joins::add (const join & j) inline
Definition at line 2076 of file overmap.cpp.
{
                 joins.push_front( j );
                 auto it = joins.begin();
                 [[maybe_unused]] const bool inserted = position_index.emplace( j.where, it ).second;
                 cata_assert( inserted );
                 return it;
             }
References cata_assert, joins, position_index, and joins_tracker::join::where.
add() [2/2]
iterator joins_tracker::indexed_joins::add (const om_pos_dir & p, const mutable_overmap_join * j) inline
Definition at line 2072 of file overmap.cpp.
{
                 return add( { p, j } );
             }
Referenced by joins_tracker::add_joins_for(), joins_tracker::add_unresolved(), and joins_tracker::postpone().
all_at()
std::vector<iterator> joins_tracker::indexed_joins::all_at (const tripoint_om_omt & pos) const inline
Definition at line 2050 of file overmap.cpp.
{
                 std::vector<iterator> result;
                 for( cube_direction dir : all_enum_values<cube_direction>() ) {
                     om_pos_dir key{ pos, dir };
                     auto pos_it = position_index.find( key );
                     if( pos_it != position_index.end() ) {
                         result.push_back( pos_it->second );
                     }
                 }
                 return result;
             }
References math_opers::pos(), and position_index.
Referenced by joins_tracker::all_unresolved_at(), joins_tracker::consistency_check(), joins_tracker::postpone(), and joins_tracker::restore_postponed_at().
any_at()
bool joins_tracker::indexed_joins::any_at (const tripoint_om_omt & pos) const inline
Definition at line 2041 of file overmap.cpp.
{
                 for( cube_direction dir : all_enum_values<cube_direction>() ) {
                     if( count( om_pos_dir{ pos, dir } ) ) {
                         return true;
                     }
                 }
                 return false;
             }
References count(), and math_opers::pos().
Referenced by joins_tracker::any_postponed_at(), joins_tracker::consistency_check(), and joins_tracker::pick_top_priority().
begin() [1/2]
iterator joins_tracker::indexed_joins::begin () inline
Definition at line 2009 of file overmap.cpp.
{
                 return joins.begin();
             }
References joins.
begin() [2/2]
const_iterator joins_tracker::indexed_joins::begin () const inline
Definition at line 2017 of file overmap.cpp.
{
                 return joins.begin();
             }
References joins.
clear()
void joins_tracker::indexed_joins::clear () inline
Definition at line 2090 of file overmap.cpp.
{
                 joins.clear();
                 position_index.clear();
             }
References joins, and position_index.
Referenced by joins_tracker::restore_postponed().
count()
bool joins_tracker::indexed_joins::count (const om_pos_dir & p) const inline
Definition at line 2029 of file overmap.cpp.
{
                 return position_index.count( p );
             }
References position_index.
Referenced by joins_tracker::allows(), and any_at().
count_at()
std::size_t joins_tracker::indexed_joins::count_at (const tripoint_om_omt & pos) const inline
Definition at line 2062 of file overmap.cpp.
{
                 std::size_t result = 0;
                 for( cube_direction dir : all_enum_values<cube_direction>() ) {
                     if( position_index.find( { pos, dir } ) != position_index.end() ) {
                         ++result;
                     }
                 }
                 return result;
             }
References position_index.
Referenced by joins_tracker::count_unresolved_at().
empty()
bool joins_tracker::indexed_joins::empty () const inline
Definition at line 2025 of file overmap.cpp.
{
                 return joins.empty();
             }
References joins.
Referenced by joins_tracker::any_postponed(), and joins_tracker::any_unresolved().
end() [1/2]
iterator joins_tracker::indexed_joins::end () inline
Definition at line 2013 of file overmap.cpp.
{
                 return joins.end();
             }
References joins.
end() [2/2]
const_iterator joins_tracker::indexed_joins::end () const inline
Definition at line 2021 of file overmap.cpp.
{
                 return joins.end();
             }
References joins.
erase()
void joins_tracker::indexed_joins::erase (const iterator it) inline
Definition at line 2084 of file overmap.cpp.
{
                 [[maybe_unused]] const size_t erased = position_index.erase( it->where );
                 cata_assert( erased );
                 joins.erase( it );
             }
References cata_assert, joins, and position_index.
Referenced by joins_tracker::erase_unresolved(), and joins_tracker::restore_postponed_at().
find()
const join* joins_tracker::indexed_joins::find (const om_pos_dir & p) const inline
Definition at line 2033 of file overmap.cpp.
{
                 auto it = position_index.find( p );
                 if( it == position_index.end() ) {
                     return nullptr;
                 }
                 return &*it->second;
             }
References position_index.
Referenced by joins_tracker::add_joins_for(), and joins_tracker::allows().
Member Data Documentation
joins
std::list<join> joins_tracker::indexed_joins::joins
Definition at line 2006 of file overmap.cpp.
Referenced by add(), begin(), clear(), empty(), end(), and erase().
position_index
std::unordered_map<om_pos_dir, iterator> joins_tracker::indexed_joins::position_index
Definition at line 2007 of file overmap.cpp.
Referenced by add(), all_at(), clear(), count(), count_at(), erase(), joins_tracker::erase_unresolved(), and find().
The documentation for this struct was generated from the following file:
src/overmap.cpp