Cataclysm DDA: fixed_overmap_special_data Struct Reference
fixed_overmap_special_data Struct Reference
Public Member Functions
fixed_overmap_special_data ()=default
fixed_overmap_special_data (const overmap_special_terrain &ter)
void finalize (const std::string &, const cata::flat_set< string_id< overmap_location >> &default_locations) override
void finalize_mapgen_parameters (mapgen_parameters &params, const std::string &context) const override
void check (const std::string &context) const override
const overmap_special_terrain & get_terrain_at (const tripoint &p) const
std::vector< overmap_special_terrain > preview_terrains () const override
std::vector< overmap_special_locations > required_locations () const override
int score_rotation_at (const overmap &om, const tripoint_om_omt &p, om_direction::type r) const override
special_placement_result place (overmap &om, const tripoint_om_omt &origin, om_direction::type dir, bool blob, const city &cit, bool must_be_unexplored) const override
Public Member Functions inherited from overmap_special_data
virtual ~overmap_special_data ()=default
Public Attributes
std::vector< overmap_special_terrain > terrains
std::vector< overmap_special_connection > connections
Detailed Description
Definition at line 1204 of file overmap.cpp.
Constructor & Destructor Documentation
fixed_overmap_special_data() [1/2]
fixed_overmap_special_data::fixed_overmap_special_data () default
fixed_overmap_special_data() [2/2]
fixed_overmap_special_data::fixed_overmap_special_data (const overmap_special_terrain & ter) inline explicit
Definition at line 1206 of file overmap.cpp.
         : terrains{ ter }
     {}
Member Function Documentation
check()
void fixed_overmap_special_data::check (const std::string & context) const inline override virtual
Implements overmap_special_data.
Definition at line 1283 of file overmap.cpp.
{
         std::set<oter_str_id> invalid_terrains;
         std::set<tripoint> points;
         for( const overmap_special_terrain &elem : terrains ) {
             const oter_str_id &oter = elem.terrain;
             if( !oter.is_valid() ) {
                 if( !invalid_terrains.count( oter ) ) {
                     // Not a huge fan of the the direct id manipulation here, but I don't know
                     // how else to do this
                     // Because we try to access all the terrains in the finalization,
                     // this is a little redundant, but whatever
                     oter_str_id invalid( oter.str() + "_north" );
                     if( invalid.is_valid() ) {
                         debugmsg( "In %s, terrain \"%s\" rotates, but is specified without a "
                                   "rotation.", context, oter.str() );
                     } else  {
                         debugmsg( "In %s, terrain \"%s\" is invalid.", context, oter.str() );
                     }
                     invalid_terrains.insert( oter );
                 }
             }
             const tripoint &pos = elem.p;
             if( points.count( pos ) > 0 ) {
                 debugmsg( "In %s, point %s is duplicated.", context, pos.to_string() );
             } else {
                 points.insert( pos );
             }
             if( elem.locations.empty() ) {
                 debugmsg( "In %s, no location is defined for point %s or the "
                           "overall special.", context, pos.to_string() );
             }
             for( const auto &l : elem.locations ) {
                 if( !l.is_valid() ) {
                     debugmsg( "In %s, point %s, location \"%s\" is invalid.",
                               context, pos.to_string(), l.c_str() );
                 }
             }
         }
         for( const overmap_special_connection &elem : connections ) {
             const overmap_special_terrain &oter = get_terrain_at( elem.p );
             if( !elem.terrain ) {
                 debugmsg( "In %s, connection %s doesn't have a terrain.",
                           context, elem.p.to_string() );
             } else if( !elem.existing && !elem.terrain->has_flag( oter_flags::line_drawing ) ) {
                 debugmsg( "In %s, connection %s \"%s\" isn't drawn with lines.",
                           context, elem.p.to_string(), elem.terrain.c_str() );
             } else if( !elem.existing && oter.terrain && !oter.terrain->type_is( elem.terrain ) ) {
                 debugmsg( "In %s, connection %s overwrites \"%s\".",
                           context, elem.p.to_string(), oter.terrain.c_str() );
             }
             if( elem.from ) {
                 // The only supported directions are north/east/south/west
                 // as those are the four directions that overmap connections
                 // can be made in. If the direction we figured out wasn't
                 // one of those, warn the user/developer.
                 const direction calculated_direction = direction_from( *elem.from, elem.p );
                 switch( calculated_direction ) {
                     case direction::NORTH:
                     case direction::EAST:
                     case direction::SOUTH:
                     case direction::WEST:
                         continue;
                     default:
                         debugmsg( "In %s, connection %s is not directly north, "
                                   "east, south or west of the defined \"from\" %s.",
                                   context, elem.p.to_string(), elem.from->to_string() );
                         break;
                 }
             }
         }
     }
References string_id< T >::c_str(), connections, context, debugmsg, direction_from(), EAST, get_terrain_at(), om_lines::invalid, string_id< T >::is_valid(), line_drawing, NORTH, math_opers::pos(), SOUTH, string_id< T >::str(), overmap_special_terrain::terrain, terrains, oter_t::type_is(), and WEST.
finalize()
void fixed_overmap_special_data::finalize (const std::string & , const cata::flat_set< string_id< overmap_location >> & default_locations) inline override virtual
Implements overmap_special_data.
Definition at line 1210 of file overmap.cpp.
{
         // If the special has default locations, then add those to the locations
         // of each of the terrains IF the terrain has no locations already.
         for( overmap_special_terrain &t : terrains ) {
             if( t.locations.empty() ) {
                 t.locations = default_locations;
             }
         }
         for( overmap_special_connection &elem : connections ) {
             const overmap_special_terrain &oter = get_terrain_at( elem.p );
             if( !elem.terrain && oter.terrain ) {
                 elem.terrain = oter.terrain->get_type_id();    // Defaulted.
             }
             // If the connection type hasn't been specified, we'll guess for them.
             // The guess isn't always right (hence guessing) in the case where
             // multiple connections types can be made on a single location type,
             // e.g. both roads and forest trails can be placed on "forest" locations.
             if( elem.connection.is_null() ) {
                 elem.connection = overmap_connections::guess_for( elem.terrain );
             }
             // If the connection has a "from" hint specified, then figure out what the
             // resulting direction from the hinted location to the connection point is,
             // and use that as the initial direction to be passed off to the connection
             // building code.
             if( elem.from ) {
                 const direction calculated_direction = direction_from( *elem.from, elem.p );
                 switch( calculated_direction ) {
                     case direction::NORTH:
                         elem.initial_dir = cube_direction::north;
                         break;
                     case direction::EAST:
                         elem.initial_dir = cube_direction::east;
                         break;
                     case direction::SOUTH:
                         elem.initial_dir = cube_direction::south;
                         break;
                     case direction::WEST:
                         elem.initial_dir = cube_direction::west;
                         break;
                     default:
                         // The only supported directions are north/east/south/west
                         // as those are the four directions that overmap connections
                         // can be made in. If the direction we figured out wasn't
                         // one of those, just set this as invalid. We'll provide
                         // a warning to the user/developer in overmap_special::check().
                         elem.initial_dir = cube_direction::last;
                         break;
                 }
             }
         }
     }
References connections, direction_from(), east, EAST, get_terrain_at(), oter_t::get_type_id(), overmap_connections::guess_for(), last, north, NORTH, south, SOUTH, overmap_special_terrain::terrain, terrains, west, and WEST.
finalize_mapgen_parameters()
void fixed_overmap_special_data::finalize_mapgen_parameters (mapgen_parameters & params, const std::string & context) const inline override virtual
Implements overmap_special_data.
Definition at line 1267 of file overmap.cpp.
{
         for( const overmap_special_terrain &t : terrains ) {
             if( !t.terrain.is_valid() ) {
                 if( oter_str_id( t.terrain.str() + "_north" ).is_valid() ) {
                     debugmsg( "In %s, terrain \"%s\" rotates, but is specified without a "
                               "rotation.", context, t.terrain.str() );
                 } else {
                     debugmsg( "In %s, terrain \"%s\" is invalid.", context, t.terrain.str() );
                 }
             }
             std::string mapgen_id = t.terrain->get_mapgen_id();
             params.check_and_merge( get_map_special_params( mapgen_id ), context );
         }
     }
References mapgen_parameters::check_and_merge(), context, debugmsg, get_map_special_params(), string_id< T >::is_valid(), and terrains.
get_terrain_at()
const overmap_special_terrain& fixed_overmap_special_data::get_terrain_at (const tripoint & p) const inline
Definition at line 1363 of file overmap.cpp.
{
         const auto iter = std::find_if( terrains.begin(), terrains.end(),
         [ &p ]( const overmap_special_terrain & elem ) {
             return elem.p == p;
         } );
         if( iter == terrains.end() ) {
             static const overmap_special_terrain null_terrain{};
             return null_terrain;
         }
         return *iter;
     }
References terrains.
Referenced by check(), and finalize().
place()
special_placement_result fixed_overmap_special_data::place (overmap & om, const tripoint_om_omt & origin, om_direction::type dir, bool blob, const city & cit, bool must_be_unexplored) const inline override virtual
Implements overmap_special_data.
Definition at line 1410 of file overmap.cpp.
{
         special_placement_result result;
         for( const overmap_special_terrain &elem : terrains ) {
             const tripoint_om_omt location = origin + om_direction::rotate( elem.p, dir );
             if( !( elem.terrain == oter_str_id::NULL_ID() ) ) {
                 result.omts_used.push_back( location );
                 const oter_id tid = elem.terrain->get_rotated( dir );
                 om.ter_set( location, tid );
                 if( blob ) {
                     for( int x = -2; x <= 2; x++ ) {
                         for( int y = -2; y <= 2; y++ ) {
                             const tripoint_om_omt nearby_pos = location + point( x, y );
                             if( !overmap::inbounds( nearby_pos ) ) {
                                 continue;
                             }
                             if( one_in( 1 + std::abs( x ) + std::abs( y ) ) &&
                                 elem.can_be_placed_on( om.ter( nearby_pos ) ) ) {
                                 om.ter_set( nearby_pos, tid );
                             }
                         }
                     }
                 }
             }
         }
         // Make connections.
         for( const overmap_special_connection &elem : connections ) {
             if( elem.connection ) {
                 const tripoint_om_omt rp = origin + om_direction::rotate( elem.p, dir );
                 cube_direction initial_dir = elem.initial_dir;
                 if( initial_dir != cube_direction::last ) {
                     initial_dir = initial_dir + dir;
                 }
                 if( cit ) {
                     om.build_connection( cit.pos, rp.xy(), elem.p.z, *elem.connection,
                                          must_be_unexplored, initial_dir );
                 }
                 // if no city present, search for nearby road within 50 tiles and make
                 // connection to it instead
                 else {
                     for( const tripoint_om_omt &nearby_point : closest_points_first( rp, 50 ) ) {
                         if( om.check_ot( "road", ot_match_type::contains, nearby_point ) ) {
                             om.build_connection(
                                 nearby_point.xy(), rp.xy(), elem.p.z, *elem.connection,
                                 must_be_unexplored, initial_dir );
                             break;
                         }
                     }
                 }
             }
         }
         return result;
     }
References abs(), closest_points_first(), connections, contains, oter_t::get_rotated(), overmap::inbounds(), last, location, string_id< oter_t >::NULL_ID(), coords::om, special_placement_result::omts_used, one_in(), point, city::pos, om_direction::rotate(), terrains, and coords::coord_point< Point, Origin, Scale, InBounds >::xy().
preview_terrains()
std::vector<overmap_special_terrain> fixed_overmap_special_data::preview_terrains () const inline override virtual
Implements overmap_special_data.
Definition at line 1375 of file overmap.cpp.
{
         std::vector<overmap_special_terrain> result;
         std::copy_if( terrains.begin(), terrains.end(), std::back_inserter( result ),
         []( const overmap_special_terrain & terrain ) {
             return terrain.p.z == 0;
         } );
         return result;
     }
References terrain, and terrains.
required_locations()
std::vector<overmap_special_locations> fixed_overmap_special_data::required_locations () const inline override virtual
Implements overmap_special_data.
Definition at line 1384 of file overmap.cpp.
{
         std::vector<overmap_special_locations> result;
         result.reserve( terrains.size() );
         std::copy( terrains.begin(), terrains.end(), std::back_inserter( result ) );
         return result;
     }
References terrains.
score_rotation_at()
int fixed_overmap_special_data::score_rotation_at (const overmap & om, const tripoint_om_omt & p, om_direction::type r) const inline override virtual
Implements overmap_special_data.
Definition at line 1391 of file overmap.cpp.
{
         int score = 0;
         for( const overmap_special_connection &con : connections ) {
             const tripoint_om_omt rp = p + om_direction::rotate( con.p, r );
             if( !overmap::inbounds( rp ) ) {
                 return -1;
             }
             const oter_id &oter = om.ter( rp );
             if( ( oter->get_type_id() == oter_type_str_id( con.terrain.str() ) ) ) {
                 ++score; // Found another one satisfied connection.
             } else if( !oter || con.existing || !con.connection->pick_subtype_for( oter ) ) {
                 return -1;
             }
         }
         return score;
     }
References connections, oter_t::get_type_id(), overmap::inbounds(), coords::om, and om_direction::rotate().
Member Data Documentation
connections
std::vector<overmap_special_connection> fixed_overmap_special_data::connections
Definition at line 1469 of file overmap.cpp.
Referenced by check(), finalize(), place(), and score_rotation_at().
terrains
std::vector<overmap_special_terrain> fixed_overmap_special_data::terrains
Definition at line 1468 of file overmap.cpp.
Referenced by check(), finalize(), finalize_mapgen_parameters(), get_terrain_at(), place(), preview_terrains(), and required_locations().
The documentation for this struct was generated from the following file:
src/overmap.cpp