Cataclysm DDA: weakpoint_attack Struct Reference
weakpoint_attack Struct Reference
#include <weakpoint.h>
Public Types
enum class attack_type : int {
NONE , MELEE_BASH , MELEE_CUT , MELEE_STAB ,
PROJECTILE , NUM
}
Public Member Functions
weakpoint_attack ()
void compute_wp_skill ()
Static Public Member Functions
static attack_type type_of_melee_attack (const damage_instance &damage)
Public Attributes
const Creature * source
const Creature * target
const item * weapon
attack_type type
bool is_thrown
bool is_crit
float wp_skill
Detailed Description
Definition at line 24 of file weakpoint.h.
Member Enumeration Documentation
attack_type
enum weakpoint_attack::attack_type : int strong
Enumerator
NONE
MELEE_BASH
MELEE_CUT
MELEE_STAB
PROJECTILE
NUM
Definition at line 25 of file weakpoint.h.
                            : int {
         NONE, // Unusual damage instances, such as falls, spells, and effects.
         MELEE_BASH, // Melee bludgeoning attacks
         MELEE_CUT, // Melee slashing attacks
         MELEE_STAB, // Melee piercing attacks
         PROJECTILE, // Ranged projectile attacks, including throwing weapons and guns
         NUM,
     };
Constructor & Destructor Documentation
weakpoint_attack()
weakpoint_attack::weakpoint_attack ()
Definition at line 324 of file weakpoint.cpp.
                                     :
     source( nullptr ),
     target( nullptr ),
     weapon( &null_item_reference() ),
     type( attack_type::NONE ),
     is_thrown( false ),
     is_crit( false ),
     wp_skill( 0.0f ) {}
Member Function Documentation
compute_wp_skill()
void weakpoint_attack::compute_wp_skill ()
Definition at line 355 of file weakpoint.cpp.
 {
     // Check if there's no source.
     if( source == nullptr ) {
         wp_skill = 0.0f;
         return;
     }
     // Compute the base attacker skill.
     float attacker_skill = 0.0f;
     const monster *mon_att = source->as_monster();
     const Character *chr_att = source->as_character();
     if( mon_att != nullptr ) {
         attacker_skill = mon_att->weakpoint_skill();
     } else if( chr_att != nullptr ) {
         switch( type ) {
             case attack_type::MELEE_BASH:
             case attack_type::MELEE_CUT:
             case attack_type::MELEE_STAB:
                 attacker_skill = chr_att->melee_weakpoint_skill( *weapon );
                 break;
             case attack_type::PROJECTILE:
                 attacker_skill = is_thrown
                                  ? chr_att->throw_weakpoint_skill()
                                  : chr_att->ranged_weakpoint_skill( *weapon );
                 break;
             default:
                 attacker_skill = 0.0f;
                 break;
         }
     }
     // Compute the proficiency skill.
     float proficiency_skill = 0.0f;
     const monster *mon_tar = target->as_monster();
     if( chr_att != nullptr && mon_tar != nullptr ) {
         proficiency_skill = mon_tar->type->families.modifier( *chr_att );
     }
     // Combine attacker skill and proficiency boni.
     wp_skill = attacker_skill + proficiency_skill;
 }
References Creature::as_character(), Creature::as_monster(), mtype::families, is_thrown, MELEE_BASH, MELEE_CUT, MELEE_STAB, Character::melee_weakpoint_skill(), weakpoint_families::modifier(), PROJECTILE, Character::ranged_weakpoint_skill(), source, target, Character::throw_weakpoint_skill(), monster::type, type, monster::weakpoint_skill(), weapon, and wp_skill.
Referenced by Creature::deal_damage().
type_of_melee_attack()
weakpoint_attack::attack_type weakpoint_attack::type_of_melee_attack (const damage_instance & damage) static
Definition at line 334 of file weakpoint.cpp.
 {
     damage_type_id primary = damage_type_id::NULL_ID();
     int primary_amount = 0;
     for( const damage_unit &du : damage.damage_units ) {
         if( du.amount > primary_amount ) {
             primary = du.type;
             primary_amount = du.amount;
         }
     }
     // FIXME: Hardcoded damage types
     if( primary == STATIC( damage_type_id( "bash" ) ) ) {
         return attack_type::MELEE_BASH;
     } else if( primary == STATIC( damage_type_id( "cut" ) ) ) {
         return attack_type::MELEE_CUT;
     } else if( primary == STATIC( damage_type_id( "stab" ) ) ) {
         return attack_type::MELEE_STAB;
     }
     return attack_type::NONE;
 }
References damage_unit::amount, damage_instance::damage_units, MELEE_BASH, MELEE_CUT, MELEE_STAB, NONE, string_id< damage_type >::NULL_ID(), STATIC, and damage_unit::type.
Referenced by Creature::deal_melee_hit().
Member Data Documentation
is_crit
bool weakpoint_attack::is_crit
Definition at line 46 of file weakpoint.h.
Referenced by Character::add_msg_player_or_say(), and Creature::deal_melee_hit().
is_thrown
bool weakpoint_attack::is_thrown
Definition at line 44 of file weakpoint.h.
Referenced by compute_wp_skill(), and Character::throw_item().
source
const Creature* weakpoint_attack::source
Definition at line 36 of file weakpoint.h.
Referenced by compute_wp_skill(), and Creature::deal_damage().
target
const Creature* weakpoint_attack::target
Definition at line 38 of file weakpoint.h.
Referenced by compute_wp_skill(), and Creature::deal_damage().
type
attack_type weakpoint_attack::type
Definition at line 42 of file weakpoint.h.
Referenced by Character::add_msg_player_or_say(), compute_wp_skill(), and Creature::deal_melee_hit().
weapon
const item* weakpoint_attack::weapon
Definition at line 40 of file weakpoint.h.
Referenced by compute_wp_skill(), Character::fire_gun(), and Character::throw_item().
wp_skill
float weakpoint_attack::wp_skill
Definition at line 48 of file weakpoint.h.
Referenced by compute_wp_skill().
The documentation for this struct was generated from the following files:
src/weakpoint.h
src/weakpoint.cpp