Cataclysm DDA: item_search_data Struct Reference
item_search_data Struct Reference
Public Member Functions
item_search_data (const JsonObject &jo)
bool check (const Character *guy, const item_location &loc)
Public Attributes
itype_id id
item_category_id category
material_id material
int calories = 0
std::vector< flag_id > flags
std::vector< flag_id > excluded_flags
bool worn_only
bool wielded_only
Detailed Description
Definition at line 172 of file npctalk.cpp.
Constructor & Destructor Documentation
item_search_data()
item_search_data::item_search_data (const JsonObject & jo) inline explicit
Definition at line 182 of file npctalk.cpp.
{
         id = itype_id( jo.get_string( "id", "" ) );
         category = item_category_id( jo.get_string( "category", "" ) );
         material = material_id( jo.get_string( "material", "" ) );
         if( jo.has_int( "calories" ) ) {
             calories = jo.get_int( "calories" );
         }
         for( std::string flag : jo.get_string_array( "flags" ) ) {
             flags.emplace_back( flag );
         }
         for( std::string flag : jo.get_string_array( "excluded_flags" ) ) {
             excluded_flags.emplace_back( flag );
         }
         worn_only = jo.get_bool( "worn_only", false );
         wielded_only = jo.get_bool( "wielded_only", false );
     }
References calories, category, excluded_flags, flags, JsonObject::get_bool(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::get_string_array(), JsonObject::has_int(), itype_id, material, wielded_only, and worn_only.
Member Function Documentation
check()
bool item_search_data::check (const Character * guy, const item_location & loc) inline
Definition at line 199 of file npctalk.cpp.
{
         if( !id.is_empty() && id != loc->typeId() ) {
             return false;
         }
         if( !category.is_empty() && category != loc->get_category_shallow().id ) {
             return false;
         }
         if( !material.is_empty() && loc->made_of( material ) == 0 ) {
             return false;
         }
         if( calories > 0 ) {
             // This is very stupid but we need a dummy to calculate nutrients
             npc dummy;
             if( dummy.compute_effective_nutrients( *loc.get_item() ).kcal() < calories ) {
                 return false;
             }
         }
         for( flag_id flag : flags ) {
             if( !loc->has_flag( flag ) ) {
                 return false;
             }
         }
         for( flag_id flag : excluded_flags ) {
             if( loc->has_flag( flag ) ) {
                 return false;
             }
         }
         if( worn_only && !guy->is_worn( *loc ) ) {
             return false;
         }
         if( wielded_only && !guy->is_wielding( *loc ) ) {
             return false;
         }
         return true;
     }
References calories, category, Character::compute_effective_nutrients(), excluded_flags, flags, item::get_category_shallow(), item_location::get_item(), item::has_flag(), item_category::id, string_id< T >::is_empty(), Character::is_wielding(), Character::is_worn(), nutrients::kcal(), item::made_of(), material, item::typeId(), wielded_only, and worn_only.
Member Data Documentation
calories
int item_search_data::calories = 0
Definition at line 176 of file npctalk.cpp.
Referenced by check(), and item_search_data().
category
item_category_id item_search_data::category
Definition at line 174 of file npctalk.cpp.
Referenced by check(), and item_search_data().
excluded_flags
std::vector<flag_id> item_search_data::excluded_flags
Definition at line 178 of file npctalk.cpp.
Referenced by check(), and item_search_data().
flags
std::vector<flag_id> item_search_data::flags
Definition at line 177 of file npctalk.cpp.
Referenced by check(), and item_search_data().
id
itype_id item_search_data::id
Definition at line 173 of file npctalk.cpp.
material
material_id item_search_data::material
Definition at line 175 of file npctalk.cpp.
Referenced by check(), and item_search_data().
wielded_only
bool item_search_data::wielded_only
Definition at line 180 of file npctalk.cpp.
Referenced by check(), and item_search_data().
worn_only
bool item_search_data::worn_only
Definition at line 179 of file npctalk.cpp.
Referenced by check(), and item_search_data().
The documentation for this struct was generated from the following file:
src/npctalk.cpp