Cataclysm DDA: VehicleFacings Struct Reference
VehicleFacings Struct Reference
The location and facing data needed to place a vehicle onto the map.
#include <vehicle_group.h>
Public Member Functions
VehicleFacings (const JsonObject &jo, std::string_view key)
units::angle pick () const
Public Attributes
std::vector< units::angle > values
Detailed Description
The location and facing data needed to place a vehicle onto the map.
Definition at line 56 of file vehicle_group.h.
Constructor & Destructor Documentation
VehicleFacings()
VehicleFacings::VehicleFacings (const JsonObject & jo, std::string_view key)
Definition at line 94 of file vehicle_group.cpp.
 {
     if( jo.has_array( key ) ) {
         for( const int i : jo.get_array( key ) ) {
             values.push_back( units::from_degrees( i ) );
         }
     } else {
         values.push_back( units::from_degrees( jo.get_int( key ) ) );
     }
 }
References units::from_degrees(), JsonObject::get_array(), JsonObject::get_int(), JsonObject::has_array(), and values.
Member Function Documentation
pick()
units::angle VehicleFacings::pick () const inline
Definition at line 59 of file vehicle_group.h.
{
         return random_entry( values );
     }
References random_entry(), and values.
Referenced by VehicleLocation::pick_facing().
Member Data Documentation
values
std::vector<units::angle> VehicleFacings::values
Definition at line 63 of file vehicle_group.h.
Referenced by pick(), and VehicleFacings().
The documentation for this struct was generated from the following files:
src/vehicle_group.h
src/vehicle_group.cpp