Cataclysm DDA: fake_spell Struct Reference
fake_spell Struct Reference
#include <magic.h>
Public Member Functions
fake_spell ()=default
fake_spell (const spell_id &sp_id, bool hit_self=false, const std::optional< int > &max_level=std::nullopt)
bool operator== (const fake_spell &rhs) const
spell get_spell (const Creature &caster, int min_level_override=0) const
spell get_spell () const
bool is_valid () const
void load (const JsonObject &jo)
void serialize (JsonOut &json) const
void deserialize (const JsonObject &data)
Public Attributes
spell_id id
std::optional< int > max_level
int level = level_default
bool self = self_default
int trigger_once_in = trigger_once_in_default
translation trigger_message
translation npc_trigger_message
Static Public Attributes
static const std::optional< int > max_level_default = std::nullopt
static const int level_default = 0
static const bool self_default = false
static const int trigger_once_in_default = 1
Detailed Description
Definition at line 141 of file magic.h.
Constructor & Destructor Documentation
fake_spell() [1/2]
fake_spell::fake_spell () default
fake_spell() [2/2]
fake_spell::fake_spell (const spell_id & sp_id, bool hit_self = false, const std::optional< int > & max_level = std::nullopt) inline explicit
Definition at line 166 of file magic.h.
                                                                           : id( sp_id ),
         max_level( max_level ), self( hit_self ) {}
Member Function Documentation
deserialize()
void fake_spell::deserialize (const JsonObject & data)
Definition at line 3018 of file magic.cpp.
 {
     load( data );
 }
References load().
get_spell() [1/2]
spell fake_spell::get_spell () const
Definition at line 3053 of file magic.cpp.
 {
     spell sp( id );
     return sp;
 }
get_spell() [2/2]
spell fake_spell::get_spell (const Creature & caster, int min_level_override = 0) const
Definition at line 3023 of file magic.cpp.
 {
     spell sp( id );
     // the max level this spell will be. can be optionally limited
     int spell_max_level = sp.get_max_level( caster );
     int spell_limiter = max_level ? *max_level : spell_max_level;
     // level is the minimum level the fake_spell will output
     min_level_override = std::max( min_level_override, level );
     if( min_level_override > spell_limiter ) {
         // this override is for min level, and does not override max level
         if( spell_limiter <= 0 ) {
             spell_limiter = min_level_override;
         } else {
             min_level_override = spell_limiter;
         }
     }
     // make sure max level is not lower then min level
     spell_limiter = std::max( min_level_override, spell_limiter );
     // the "level" of the fake spell is the goal, but needs to be clamped to min and max
     int level_of_spell = clamp( level, min_level_override, spell_limiter );
     if( level > spell_limiter ) {
         debugmsg( "ERROR: fake spell %s has higher min_level than max_level", id.c_str() );
         return sp;
     }
     sp.set_exp( sp.exp_for_level( level_of_spell ) );
     return sp;
 }
References clamp(), debugmsg, spell::exp_for_level(), spell::get_max_level(), level, max(), max_level, and spell::set_exp().
Referenced by enchant_cache::activate_passive(), timed_event::actualize(), mon_spellcasting_actor::call(), enchant_cache::cast_enchantment_spell(), spell::cast_extra_spell_effects(), trapfunc::cast_spell(), monster::die(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell().
is_valid()
bool fake_spell::is_valid () const
Definition at line 2981 of file magic.cpp.
 {
     return id.is_valid() && !id.is_empty();
 }
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), and monster_death_effect::load().
load()
void fake_spell::load (const JsonObject & jo)
Definition at line 2986 of file magic.cpp.
 {
     mandatory( jo, false, "id", id );
     optional( jo, false, "hit_self", self, self_default );
     optional( jo, false, "once_in", trigger_once_in, trigger_once_in_default );
     optional( jo, false, "message", trigger_message );
     optional( jo, false, "npc_message", npc_trigger_message );
     int max_level_int;
     optional( jo, false, "max_level", max_level_int, -1 );
     if( max_level_int == -1 ) {
         max_level = std::nullopt;
     } else {
         max_level = max_level_int;
     }
     optional( jo, false, "min_level", level, level_default );
     if( jo.has_string( "level" ) ) {
         debugmsg( "level member for fake_spell was renamed to min_level.  id: %s", id.c_str() );
     }
 }
References debugmsg, JsonObject::has_string(), level, level_default, mandatory, max_level, npc_trigger_message, optional(), self_default, trigger_message, trigger_once_in, and trigger_once_in_default.
Referenced by deserialize(), relic::load(), and enchantment::load().
operator==()
bool fake_spell::operator== (const fake_spell & rhs) const inline
Definition at line 170 of file magic.h.
{
         return id == rhs.id &&
                max_level == rhs.max_level &&
                level == rhs.level &&
                self == rhs.self &&
                trigger_once_in == rhs.trigger_once_in &&
                trigger_message == rhs.trigger_message &&
                npc_trigger_message == rhs.npc_trigger_message;
     }
References id, level, max_level, npc_trigger_message, self, trigger_message, and trigger_once_in.
serialize()
void fake_spell::serialize (JsonOut & json) const
Definition at line 3007 of file magic.cpp.
 {
     json.start_object();
     json.member( "id", id );
     json.member( "hit_self", self, self_default );
     json.member( "once_in", trigger_once_in, trigger_once_in_default );
     json.member( "max_level", max_level, max_level_default );
     json.member( "min_level", level, level_default );
     json.end_object();
 }
References JsonOut::end_object(), level, level_default, max_level, max_level_default, JsonOut::member(), self_default, JsonOut::start_object(), trigger_once_in, and trigger_once_in_default.
Member Data Documentation
id
spell_id fake_spell::id
Definition at line 142 of file magic.h.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), relic_procgen_data::generate(), operator==(), relic_procgen_data::power_level(), and spell_infinite_loop_check().
level
int fake_spell::level = level_default
Definition at line 151 of file magic.h.
Referenced by enchant_cache::cast_enchantment_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), relic_procgen_data::generate(), get_spell(), load(), operator==(), relic_procgen_data::power_level(), and serialize().
level_default
const int fake_spell::level_default = 0 static
Definition at line 149 of file magic.h.
Referenced by load(), and serialize().
max_level
std::optional<int> fake_spell::max_level
Definition at line 147 of file magic.h.
Referenced by get_spell(), load(), operator==(), and serialize().
max_level_default
const std::optional< int > fake_spell::max_level_default = std::nullopt static
Definition at line 144 of file magic.h.
Referenced by serialize().
npc_trigger_message
translation fake_spell::npc_trigger_message
Definition at line 163 of file magic.h.
Referenced by enchant_cache::cast_enchantment_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), load(), and operator==().
self
bool fake_spell::self = self_default
Definition at line 155 of file magic.h.
Referenced by mon_spellcasting_actor::call(), enchant_cache::cast_enchantment_spell(), spell::cast_extra_spell_effects(), monster::die(), and operator==().
self_default
const bool fake_spell::self_default = false static
Definition at line 153 of file magic.h.
Referenced by load(), and serialize().
trigger_message
translation fake_spell::trigger_message
Definition at line 161 of file magic.h.
Referenced by mon_spellcasting_actor::call(), enchant_cache::cast_enchantment_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), load(), mon_spellcasting_actor::load_internal(), and operator==().
trigger_once_in
int fake_spell::trigger_once_in = trigger_once_in_default
Definition at line 159 of file magic.h.
Referenced by enchant_cache::cast_enchantment_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), load(), operator==(), and serialize().
trigger_once_in_default
const int fake_spell::trigger_once_in_default = 1 static
Definition at line 157 of file magic.h.
Referenced by load(), and serialize().
The documentation for this struct was generated from the following files:
src/magic.h
src/magic.cpp