Cataclysm DDA: tutorial_game Struct Reference
tutorial_game Struct Reference
#include <gamemode_tutorial.h>
Public Member Functions
special_game_type id () override
bool init () override
void per_turn () override
void pre_action (action_id &act) override
void post_action (action_id act) override
void game_over () override
Public Member Functions inherited from special_game
virtual ~special_game ()=default
Private Member Functions
void add_message (tut_lesson lesson)
Private Attributes
std::map< tut_lesson, bool > tutorials_seen
Detailed Description
Definition at line 60 of file gamemode_tutorial.h.
Member Function Documentation
add_message()
void tutorial_game::add_message (tut_lesson lesson) private
Definition at line 383 of file gamemode_tutorial.cpp.
 {
     if( tutorials_seen[lesson] ) {
         return;
     }
     tutorials_seen[lesson] = true;
     g->invalidate_main_ui_adaptor();
     std::string translated_lesson = SNIPPET.get_snippet_by_id( snippet_id(
                                         io::enum_to_string<tut_lesson>( lesson ) ) ).value_or( translation() ).translated();
     replace_keybind_tag( translated_lesson );
     popup( translated_lesson, PF_ON_TOP );
 }
References io::enum_to_string< tut_lesson >(), g, snippet_library::get_snippet_by_id(), PF_ON_TOP, popup(), replace_keybind_tag(), SNIPPET, and tutorials_seen.
Referenced by per_turn(), and post_action().
game_over()
void tutorial_game::game_over () inline override virtual
Reimplemented from special_game.
Definition at line 68 of file gamemode_tutorial.h.
 { }
id()
special_game_type tutorial_game::id () inline override virtual
Reimplemented from special_game.
Definition at line 61 of file gamemode_tutorial.h.
{
             return special_game_type::TUTORIAL;
         }
References TUTORIAL.
init()
bool tutorial_game::init () override virtual
Reimplemented from special_game.
Definition at line 133 of file gamemode_tutorial.cpp.
 {
     // TODO: clean up old tutorial
     // Start at noon at the end of the spring and set a fixed temperature of 20 degrees to prevent freezing
     calendar::turn = calendar::start_of_cataclysm + 8_weeks + 12_hours;
     get_weather().forced_temperature = units::from_celsius( 20 );
     tutorials_seen.clear();
     get_scent().reset();
     // We use a Z-factor of 10 so that we don't plop down tutorial rooms in the
     // middle of the "real" game world
     avatar &player_character = get_avatar();
     player_character.normalize();
     player_character.str_cur = player_character.str_max;
     player_character.per_cur = player_character.per_max;
     player_character.int_cur = player_character.int_max;
     player_character.dex_cur = player_character.dex_max;
     player_character.set_all_parts_hp_to_max();
     //~ default name for the tutorial
     player_character.name = _( "John Smith" );
     player_character.prof = profession::generic();
     // overmap terrain coordinates
     const tripoint_om_omt lp( 50, 50, 0 );
     // Assume overmap zero
     const tripoint_abs_omt lp_abs = project_combine( point_abs_om(), lp );
     overmap &starting_om = overmap_buffer.get( point_abs_om() );
     starting_om.place_special_forced( overmap_special_tutorial, lp, om_direction::type::north );
     starting_om.clear_mon_groups();
     player_character.wear_item( item( "boxer_shorts" ), false );
     player_character.wear_item( item( "jeans" ), false );
     player_character.wear_item( item( "longshirt" ), false );
     player_character.wear_item( item( "socks" ), false );
     player_character.wear_item( item( "sneakers" ), false );
     player_character.set_skill_level( skill_gun, 5 );
     player_character.set_skill_level( skill_melee, 5 );
     player_character.set_skill_level( skill_throwing, 5 );
     g->load_map( project_to<coords::sm>( lp_abs ) );
     player_character.move_to( project_to<coords::ms>( lp_abs ) + point( 2, 2 ) );
     // This shifts the view to center the players pos
     g->update_map( player_character );
     return true;
 }
References _, overmap::clear_mon_groups(), Character::dex_cur, Character::dex_max, weather_manager::forced_temperature, units::from_celsius(), g, profession::generic(), overmapbuffer::get(), get_avatar(), get_scent(), get_weather(), Character::int_cur, Character::int_max, item, Creature::move_to(), Character::name, Character::normalize(), om_direction::north, overmap_buffer, overmap_special_tutorial, Character::per_cur, Character::per_max, overmap::place_special_forced(), point, Character::prof, coords::project_combine(), scent_map::reset(), Creature::set_all_parts_hp_to_max(), Character::set_skill_level(), skill_gun, skill_melee, skill_throwing, calendar::start_of_cataclysm, Character::str_cur, Character::str_max, calendar::turn, tutorials_seen, and Character::wear_item().
per_turn()
void tutorial_game::per_turn () override virtual
Reimplemented from special_game.
Definition at line 182 of file gamemode_tutorial.cpp.
 {
     // note that add_message does nothing if the message was already shown
     add_message( tut_lesson::LESSON_INTRO );
     add_message( tut_lesson::LESSON_MOVE );
     Character &player_character = get_player_character();
     if( g->light_level( player_character.posz() ) == 1 ) {
         if( player_character.has_amount( itype_flashlight, 1 ) ||
             player_character.has_amount( itype_flashlight_on, 1 ) ) {
             add_message( tut_lesson::LESSON_DARK );
         } else {
             add_message( tut_lesson::LESSON_DARK_NO_FLASH );
         }
     }
     if( player_character.get_wielded_item() &&
         player_character.get_wielded_item()->ammo_remaining( &player_character ) > 0 ) {
         add_message( tut_lesson::LESSON_GUN_FIRE );
     }
     if( player_character.get_pain() > 0 ) {
         add_message( tut_lesson::LESSON_PAIN );
     }
     if( player_character.get_stamina() <= 8000 ) {
         add_message( tut_lesson::LESSON_RESTORE_STAMINA );
     }
     map &here = get_map();
     if( !tutorials_seen[tut_lesson::LESSON_BUTCHER] ) {
         for( const item &it : here.i_at( player_character.pos().xy() ) ) {
             if( it.is_corpse() ) {
                 add_message( tut_lesson::LESSON_BUTCHER );
                 break;
             }
         }
     }
     for( const tripoint &p : here.points_in_radius( player_character.pos(), 1 ) ) {
         if( here.ter( p ) == ter_t_door_c ) {
             add_message( tut_lesson::LESSON_OPEN );
             break;
         } else if( here.ter( p ) == ter_t_door_o ) {
             add_message( tut_lesson::LESSON_CLOSE );
             break;
         } else if( here.ter( p ) == ter_t_door_locked_interior ) {
             add_message( tut_lesson::LESSON_LOCKED_DOOR );
             break;
         } else if( here.ter( p ) == ter_t_window ) {
             add_message( tut_lesson::LESSON_WINDOW );
             break;
         } else if( here.furn( p ) == furn_f_rack ) {
             add_message( tut_lesson::LESSON_EXAMINE );
             break;
         } else if( here.ter( p ) == ter_t_stairs_down ) {
             add_message( tut_lesson::LESSON_STAIRS );
             break;
         } else if( here.ter( p ) == ter_t_water_dispenser ) {
             add_message( tut_lesson::LESSON_PICKUP_WATER );
             break;
         } else if( here.tr_at( p ).id == tr_bubblewrap ) {
             add_message( tut_lesson::LESSON_ACT_BUBBLEWRAP );
             break;
         }
     }
     if( !here.i_at( point( player_character.posx(), player_character.posy() ) ).empty() ) {
         add_message( tut_lesson::LESSON_PICKUP );
     }
     if( here.tr_at( player_character.pos() ) == tr_tutorial_1 ) {
         add_message( tut_lesson::LESSON_LOOK );
     } else if( here.tr_at( player_character.pos() ) == tr_tutorial_2 ) {
         add_message( tut_lesson::LESSON_MOVEMENT_MODES );
     } else if( here.tr_at( player_character.pos() ) == tr_tutorial_3 ) {
         add_message( tut_lesson::LESSON_MONSTER_SIGHTED );
     } else if( here.tr_at( player_character.pos() ) == tr_tutorial_4 ) {
         add_message( tut_lesson::LESSON_REACH_ATTACK );
     } else if( here.tr_at( player_character.pos() ) == tr_tutorial_5 ) {
         add_message( tut_lesson::LESSON_HOLSTERS_WEAR );
     } else if( here.tr_at( player_character.pos() ) == tr_tutorial_6 ) {
         add_message( tut_lesson::LESSON_GUN_LOAD );
     } else if( here.tr_at( player_character.pos() ) == tr_tutorial_7 ) {
         add_message( tut_lesson::LESSON_INVENTORY );
     } else if( here.tr_at( player_character.pos() ) == tr_tutorial_8 ) {
         add_message( tut_lesson::LESSON_FLASHLIGHT );
     } else if( here.tr_at( player_character.pos() ) == tr_tutorial_9 ) {
         add_message( tut_lesson::LESSON_INTERACT );
     } else if( here.tr_at( player_character.pos() ) == tr_tutorial_10 ) {
         add_message( tut_lesson::LESSON_REMOTE_USE );
     } else if( here.tr_at( player_character.pos() ) == tr_tutorial_11 ) {
         player_character.set_hunger( 100 );
         player_character.stomach.empty();
         add_message( tut_lesson::LESSON_CRAFTING_FOOD );
     } else if( here.tr_at( player_character.pos() ) == tr_tutorial_12 ) {
         add_message( tut_lesson::LESSON_CONSTRUCTION );
     } else if( here.tr_at( player_character.pos() ) == tr_tutorial_13 ) {
         player_character.set_pain( 20 );
     } else if( here.tr_at( player_character.pos() ) == tr_tutorial_14 ) {
         add_message( tut_lesson::LESSON_THROWING );
     } else if( here.tr_at( player_character.pos() ) == tr_tutorial_15 ) {
         add_message( tut_lesson::LESSON_FINALE );
     }
 }
References add_message(), item::ammo_remaining(), stomach_contents::empty(), item_stack::empty(), map::furn(), furn_f_rack, g, get_map(), Creature::get_pain(), get_player_character(), Character::get_stamina(), Character::get_wielded_item(), visitable::has_amount(), map::i_at(), trap::id, itype_flashlight, itype_flashlight_on, LESSON_ACT_BUBBLEWRAP, LESSON_BUTCHER, LESSON_CLOSE, LESSON_CONSTRUCTION, LESSON_CRAFTING_FOOD, LESSON_DARK, LESSON_DARK_NO_FLASH, LESSON_EXAMINE, LESSON_FINALE, LESSON_FLASHLIGHT, LESSON_GUN_FIRE, LESSON_GUN_LOAD, LESSON_HOLSTERS_WEAR, LESSON_INTERACT, LESSON_INTRO, LESSON_INVENTORY, LESSON_LOCKED_DOOR, LESSON_LOOK, LESSON_MONSTER_SIGHTED, LESSON_MOVE, LESSON_MOVEMENT_MODES, LESSON_OPEN, LESSON_PAIN, LESSON_PICKUP, LESSON_PICKUP_WATER, LESSON_REACH_ATTACK, LESSON_REMOTE_USE, LESSON_RESTORE_STAMINA, LESSON_STAIRS, LESSON_THROWING, LESSON_WINDOW, map::points_in_radius(), Creature::pos(), Creature::posx(), Creature::posy(), Creature::posz(), Character::set_hunger(), Character::set_pain(), Character::stomach, map::ter(), ter_t_door_c, ter_t_door_locked_interior, ter_t_door_o, ter_t_stairs_down, ter_t_water_dispenser, ter_t_window, map::tr_at(), tr_bubblewrap, tr_tutorial_1, tr_tutorial_10, tr_tutorial_11, tr_tutorial_12, tr_tutorial_13, tr_tutorial_14, tr_tutorial_15, tr_tutorial_2, tr_tutorial_3, tr_tutorial_4, tr_tutorial_5, tr_tutorial_6, tr_tutorial_7, tr_tutorial_8, tr_tutorial_9, tutorials_seen, and tripoint::xy().
post_action()
void tutorial_game::post_action (action_id act) override virtual
Reimplemented from special_game.
Definition at line 302 of file gamemode_tutorial.cpp.
 {
     Character &player_character = get_player_character();
     switch( act ) {
         case ACTION_OPEN:
             add_message( tut_lesson::LESSON_CLOSE );
             break;
         case ACTION_FIRE:
             if( player_character.get_wielded_item() && player_character.get_wielded_item()->is_gun() ) {
                 add_message( tut_lesson::LESSON_RECOIL );
             }
             break;
         case ACTION_CLOSE:
             add_message( tut_lesson::LESSON_SMASH );
             break;
         case ACTION_USE: {
             if( player_character.has_amount( itype_grenade_act, 1 ) ) {
                 add_message( tut_lesson::LESSON_ACT_GRENADE );
             }
             if( player_character.last_item == itype_codeine ) {
                 add_message( tut_lesson::LESSON_TOOK_PAINKILLER );
             }
         }
         break;
         case ACTION_EAT:
             if( player_character.last_item == itype_cig ) {
                 add_message( tut_lesson::LESSON_TOOK_CIG );
             } else if( player_character.last_item == itype_water_clean ) {
                 add_message( tut_lesson::LESSON_DRANK_WATER );
             }
             break;
         case ACTION_WEAR: {
             item it( player_character.last_item, calendar::turn_zero );
             if( it.is_holster() ) {
                 add_message( tut_lesson::LESSON_HOLSTERS_ACTIVATE );
             } else if( it.has_pocket_type( pocket_type::CONTAINER ) ) {
                 add_message( tut_lesson::LESSON_WORE_STORAGE );
             } else if( it.is_armor() ) {
                 if( it.get_env_resist() >= 2 ) {
                     add_message( tut_lesson::LESSON_WORE_MASK );
                 } else if( it.get_avg_coverage() >= 2 || it.get_thickness() >= 2 ) {
                     add_message( tut_lesson::LESSON_WORE_ARMOR );
                 }
             }
         }
         break;
         /* fallthrough */
         case ACTION_PICKUP: {
             item it( player_character.last_item, calendar::turn_zero );
             if( it.is_armor() ) {
                 add_message( tut_lesson::LESSON_GOT_ARMOR );
             } else if( it.is_gun() ) {
                 add_message( tut_lesson::LESSON_GOT_GUN );
             } else if( it.is_ammo() ) {
                 add_message( tut_lesson::LESSON_GOT_AMMO );
             } else if( it.is_tool() ) {
                 add_message( tut_lesson::LESSON_GOT_TOOL );
             } else if( it.is_food() ) {
                 add_message( tut_lesson::LESSON_GOT_FOOD );
             } else if( it.is_melee() ) {
                 add_message( tut_lesson::LESSON_GOT_WEAPON );
             }
         }
         break;
         default:
             // TODO: add more actions here
             break;
     }
 }
References act, ACTION_CLOSE, ACTION_EAT, ACTION_FIRE, ACTION_OPEN, ACTION_PICKUP, ACTION_USE, ACTION_WEAR, add_message(), CONTAINER, item::get_avg_coverage(), item::get_env_resist(), get_player_character(), item::get_thickness(), Character::get_wielded_item(), visitable::has_amount(), item::has_pocket_type(), item::is_ammo(), item::is_armor(), item::is_food(), item::is_gun(), item::is_holster(), item::is_melee(), item::is_tool(), itype_cig, itype_codeine, itype_grenade_act, itype_water_clean, Character::last_item, LESSON_ACT_GRENADE, LESSON_CLOSE, LESSON_DRANK_WATER, LESSON_GOT_AMMO, LESSON_GOT_ARMOR, LESSON_GOT_FOOD, LESSON_GOT_GUN, LESSON_GOT_TOOL, LESSON_GOT_WEAPON, LESSON_HOLSTERS_ACTIVATE, LESSON_RECOIL, LESSON_SMASH, LESSON_TOOK_CIG, LESSON_TOOK_PAINKILLER, LESSON_WORE_ARMOR, LESSON_WORE_MASK, LESSON_WORE_STORAGE, and calendar::turn_zero.
pre_action()
void tutorial_game::pre_action (action_id & act) override virtual
Reimplemented from special_game.
Definition at line 288 of file gamemode_tutorial.cpp.
 {
     switch( act ) {
         case ACTION_SAVE:
         case ACTION_QUICKSAVE:
             popup( _( "You're saving a tutorial - the tutorial world lacks certain features of normal worlds.  "
                       "Weird things might happen when you load this save.  You have been warned." ) );
             break;
         default:
             // Other actions are fine.
             break;
     }
 }
References _, act, ACTION_QUICKSAVE, ACTION_SAVE, and popup().
Member Data Documentation
tutorials_seen
std::map<tut_lesson, bool> tutorial_game::tutorials_seen private
Definition at line 73 of file gamemode_tutorial.h.
Referenced by add_message(), init(), and per_turn().
The documentation for this struct was generated from the following files:
src/gamemode_tutorial.h
src/gamemode_tutorial.cpp