Cataclysm DDA: advanced_inv_sorter Struct Reference
advanced_inv_sorter Struct Reference
Public Member Functions
advanced_inv_sorter (advanced_inv_sortby sort)
bool operator() (const advanced_inv_listitem &d1, const advanced_inv_listitem &d2) const
Public Attributes
advanced_inv_sortby sortby
Detailed Description
Definition at line 555 of file advanced_inv.cpp.
Constructor & Destructor Documentation
advanced_inv_sorter()
advanced_inv_sorter::advanced_inv_sorter (advanced_inv_sortby sort) inline explicit
Definition at line 557 of file advanced_inv.cpp.
{
         sortby = sort;
     }
References sortby.
Member Function Documentation
operator()()
bool advanced_inv_sorter::operator() (const advanced_inv_listitem & d1, const advanced_inv_listitem & d2) const inline
Definition at line 560 of file advanced_inv.cpp.
{
         // Note: the item pointer can only be null on sort by category, otherwise it is always valid.
         switch( sortby ) {
             case SORTBY_NONE:
                 if( d1.idx != d2.idx ) {
                     return d1.idx < d2.idx;
                 }
                 break;
             case SORTBY_NAME:
                 // Fall through to code below the switch
                 break;
             case SORTBY_WEIGHT:
                 if( d1.weight != d2.weight ) {
                     return d1.weight > d2.weight;
                 }
                 break;
             case SORTBY_VOLUME:
                 if( d1.volume != d2.volume ) {
                     return d1.volume > d2.volume;
                 }
                 break;
             case SORTBY_DENSITY: {
                 const double density1 = static_cast<double>( d1.weight.value() ) /
                                         static_cast<double>( std::max( 1, d1.volume.value() ) );
                 const double density2 = static_cast<double>( d2.weight.value() ) /
                                         static_cast<double>( std::max( 1, d2.volume.value() ) );
                 if( density1 != density2 ) {
                     return density1 > density2;
                 }
                 break;
             }
             case SORTBY_CHARGES:
                 if( d1.items.front()->charges != d2.items.front()->charges ) {
                     return d1.items.front()->charges > d2.items.front()->charges;
                 }
                 break;
             case SORTBY_CATEGORY:
                 if( d1.cat != d2.cat ) {
                     return d1.cat < d2.cat;
                 }
                 break;
             case SORTBY_DAMAGE: {
                 const double dam1 = d1.items.front()->average_dps( get_player_character() );
                 const double dam2 = d2.items.front()->average_dps( get_player_character() );
                 if( dam1 != dam2 ) {
                     return dam1 > dam2;
                 }
                 break;
             }
             case SORTBY_AMMO: {
                 const std::string a1 = d1.items.front()->ammo_sort_name();
                 const std::string a2 = d2.items.front()->ammo_sort_name();
                 // There are many items with "false" ammo types (e.g.
                 // scrap metal has "components") that actually is not
                 // used as ammo, so we consider them as non-ammo.
                 const bool ammoish1 = !a1.empty() && a1 != "components" && a1 != "none" && a1 != "NULL";
                 const bool ammoish2 = !a2.empty() && a2 != "components" && a2 != "none" && a2 != "NULL";
                 if( ammoish1 != ammoish2 ) {
                     return ammoish1;
                 } else if( ammoish1 && ammoish2 ) {
                     if( a1 == a2 ) {
                         // For items with the same ammo type, we sort:
                         // guns > tools > magazines > ammunition
                         if( d1.items.front()->is_gun() && !d2.items.front()->is_gun() ) {
                             return true;
                         }
                         if( !d1.items.front()->is_gun() && d2.items.front()->is_gun() ) {
                             return false;
                         }
                         if( d1.items.front()->is_tool() && !d2.items.front()->is_tool() ) {
                             return true;
                         }
                         if( !d1.items.front()->is_tool() && d2.items.front()->is_tool() ) {
                             return false;
                         }
                         if( d1.items.front()->is_magazine() && d2.items.front()->is_ammo() ) {
                             return true;
                         }
                         if( d2.items.front()->is_magazine() && d1.items.front()->is_ammo() ) {
                             return false;
                         }
                     }
                     return localized_compare( a1, a2 );
                 }
             }
             break;
             case SORTBY_SPOILAGE:
                 if( d1.items.front()->spoilage_sort_order() != d2.items.front()->spoilage_sort_order() ) {
                     return d1.items.front()->spoilage_sort_order() < d2.items.front()->spoilage_sort_order();
                 }
                 break;
             case SORTBY_PRICE:
                 if( d1.items.front()->price( true ) != d2.items.front()->price( true ) ) {
                     return d1.items.front()->price( true ) > d2.items.front()->price( true );
                 }
                 break;
         }
         // secondary sort by name and link length
         auto const sort_key = []( advanced_inv_listitem const & d ) {
             return std::make_tuple( d.name_without_prefix, d.contents_count, d.name,
                                     d.items.front()->link_sort_key() );
         };
         return localized_compare( sort_key( d1 ), sort_key( d2 ) );
     }
References advanced_inv_listitem::cat, get_player_character(), advanced_inv_listitem::idx, advanced_inv_listitem::items, localized_compare, max(), sortby, SORTBY_AMMO, SORTBY_CATEGORY, SORTBY_CHARGES, SORTBY_DAMAGE, SORTBY_DENSITY, SORTBY_NAME, SORTBY_NONE, SORTBY_PRICE, SORTBY_SPOILAGE, SORTBY_VOLUME, SORTBY_WEIGHT, units::quantity< V, U >::value(), advanced_inv_listitem::volume, and advanced_inv_listitem::weight.
Member Data Documentation
sortby
advanced_inv_sortby advanced_inv_sorter::sortby
Definition at line 556 of file advanced_inv.cpp.
Referenced by advanced_inv_sorter(), and operator()().
The documentation for this struct was generated from the following file:
src/advanced_inv.cpp