Cataclysm DDA: pathfinder Struct Reference
pathfinder Struct Reference
Public Types
using queue_type = std::priority_queue< std::pair< int, tripoint >, std::vector< std::pair< int, tripoint > >, pair_greater_cmp_first >
Public Member Functions
path_data_layer & get_layer (const int z)
void reset (int minz, int maxz)
bool empty () const
tripoint get_next ()
void add_point (const int gscore, const int score, const tripoint &from, const tripoint &to)
void close_point (const tripoint &p)
void unclose_point (const tripoint &p)
Public Attributes
queue_type open
std::array< std::unique_ptr< path_data_layer >, OVERMAP_LAYERS > path_data
Detailed Description
Definition at line 51 of file pathfinding.cpp.
Member Typedef Documentation
queue_type
using pathfinder::queue_type = std::priority_queue< std::pair<int, tripoint>, std::vector< std::pair<int, tripoint> >, pair_greater_cmp_first >
Definition at line 52 of file pathfinding.cpp.
Member Function Documentation
add_point()
void pathfinder::add_point (const int gscore, const int score, const tripoint & from, const tripoint & to) inline
Definition at line 86 of file pathfinding.cpp.
{
         path_data_layer &layer = get_layer( to.z );
         const int index = flat_index( to.xy() );
         if( layer.closed[index] ) {
             return;
         }
         if( layer.open[index] && gscore >= layer.gscore[index] ) {
             return;
         }
         layer.open[index] = true;
         layer.gscore[index] = gscore;
         layer.parent[index] = from;
         layer.score [index] = score;
         open.emplace( score, to );
     }
References path_data_layer::closed, flat_index(), get_layer(), path_data_layer::gscore, path_data_layer::open, open, path_data_layer::parent, path_data_layer::score, tripoint::xy(), and tripoint::z.
close_point()
void pathfinder::close_point (const tripoint & p) inline
Definition at line 103 of file pathfinding.cpp.
{
         path_data_layer &layer = get_layer( p.z );
         const int index = flat_index( p.xy() );
         layer.closed[index] = true;
     }
References path_data_layer::closed, flat_index(), get_layer(), tripoint::xy(), and tripoint::z.
empty()
bool pathfinder::empty () const inline
Definition at line 76 of file pathfinding.cpp.
{
         return open.empty();
     }
References open.
get_layer()
path_data_layer& pathfinder::get_layer (const int z) inline
Definition at line 57 of file pathfinding.cpp.
{
         std::unique_ptr< path_data_layer > &ptr = path_data[z + OVERMAP_DEPTH];
         if( ptr != nullptr ) {
             return *ptr;
         }
         ptr = std::make_unique<path_data_layer>();
         return *ptr;
     }
References OVERMAP_DEPTH, and path_data.
Referenced by add_point(), close_point(), and unclose_point().
get_next()
tripoint pathfinder::get_next () inline
Definition at line 80 of file pathfinding.cpp.
{
         const auto pt = open.top();
         open.pop();
         return pt.second;
     }
References open.
reset()
void pathfinder::reset (int minz, int maxz) inline
Definition at line 66 of file pathfinding.cpp.
{
         for( int i = minz; i <= maxz; ++i ) {
             std::unique_ptr< path_data_layer > &ptr = path_data[i + OVERMAP_DEPTH];
             if( ptr != nullptr ) {
                 path_data[i + OVERMAP_DEPTH]->reset();
             }
         }
         open = queue_type();
     }
References open, OVERMAP_DEPTH, and path_data.
unclose_point()
void pathfinder::unclose_point (const tripoint & p) inline
Definition at line 109 of file pathfinding.cpp.
{
         path_data_layer &layer = get_layer( p.z );
         const int index = flat_index( p.xy() );
         layer.closed[index] = false;
     }
References path_data_layer::closed, flat_index(), get_layer(), tripoint::xy(), and tripoint::z.
Member Data Documentation
open
queue_type pathfinder::open
Definition at line 54 of file pathfinding.cpp.
Referenced by add_point(), empty(), get_next(), and reset().
path_data
std::array< std::unique_ptr< path_data_layer >, OVERMAP_LAYERS > pathfinder::path_data
Definition at line 55 of file pathfinding.cpp.
Referenced by get_layer(), and reset().
The documentation for this struct was generated from the following file:
src/pathfinding.cpp