Cataclysm DDA: option_slider Struct Reference
option_slider Struct Reference
#include <options.h>
Classes
struct option_slider_level
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
void check () const
void reorder_opts ()
const translation & name () const
const std::string & context () const
int default_level () const
int count () const
void apply_opts (int level, options_manager::options_container &OPTIONS) const
const translation & level_name (int level) const
const translation & level_desc (int level) const
int random_level () const
Static Public Member Functions
static void load_option_sliders (const JsonObject &jo, const std::string &src)
static void reset ()
static void finalize_all ()
static void check_consistency ()
static const std::vector< option_slider > & get_all ()
Public Attributes
option_slider_id id
bool was_loaded = false
Private Attributes
translation _name
std::vector< option_slider_level > _levels
std::string _context
int _default_level = 0
Detailed Description
Definition at line 372 of file options.h.
Member Function Documentation
apply_opts()
void option_slider::apply_opts (int level, options_manager::options_container & OPTIONS) const inline
Definition at line 454 of file options.h.
{
             if( level >= 0 && level < static_cast<int>( _levels.size() ) ) {
                 _levels[level].apply_opts( OPTIONS );
             }
         }
References _levels.
check()
void option_slider::check () const
Definition at line 139 of file options.cpp.
 {
     std::set<int> lvls;
     for( const option_slider_level &lvl : _levels ) {
         if( lvl.level() < 0 || lvl.level() >= static_cast<int>( _levels.size() ) ) {
             debugmsg( "Option slider level \"%s\" (from option slider \"%s\") has a numeric "
                       "level of %d, but must be between 0 and %d (total number of levels minus 1)",
                       lvl.name().translated().c_str(), id.c_str(), lvl.level(),
                       static_cast<int>( _levels.size() ) - 1 );
         }
         lvls.emplace( lvl.level() );
     }
     if( lvls.size() != _levels.size() ) {
         debugmsg( "Option slider \"%s\" has duplicate slider levels.  Each slider level must "
                   "be unique, from 0 (zero) to %d (total number of levels minus 1)",
                   id.c_str(), static_cast<int>( _levels.size() ) - 1 );
     }
     if( lvls.count( _default_level ) == 0 ) {
         debugmsg( "Default slider level (%d) for option slider \"%s\" does not match any of the "
                   "defined levels", _default_level, id.c_str() );
     }
 }
References _default_level, _levels, and debugmsg.
check_consistency()
void option_slider::check_consistency () static
Definition at line 102 of file options.cpp.
 {
     for( const option_slider &opt : option_slider::get_all() ) {
         opt.check();
     }
 }
References get_all().
Referenced by DynamicDataLoader::check_consistency().
context()
const std::string& option_slider::context () const inline
Definition at line 442 of file options.h.
{
             return _context;
         }
References _context.
count()
int option_slider::count () const inline
Definition at line 450 of file options.h.
{
             return _levels.size();
         }
References _levels.
default_level()
int option_slider::default_level () const inline
Definition at line 446 of file options.h.
{
             return _default_level;
         }
References _default_level.
finalize_all()
void option_slider::finalize_all () static
Definition at line 94 of file options.cpp.
 {
     for( const option_slider &opt : option_slider::get_all() ) {
         option_slider &o = const_cast<option_slider &>( opt );
         o.reorder_opts();
     }
 }
References get_all(), and reorder_opts().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< option_slider > & option_slider::get_all () static
Definition at line 84 of file options.cpp.
 {
     return option_slider_factory.get_all();
 }
References anonymous_namespace{options.cpp}::option_slider_factory.
Referenced by check_consistency(), finalize_all(), and worldfactory::show_worldgen_basic().
level_desc()
const translation& option_slider::level_desc (int level) const inline
Definition at line 468 of file options.h.
{
             static const translation none;
             if( level >= 0 && level < static_cast<int>( _levels.size() ) ) {
                 return _levels[level].desc();
             }
             return none;
         }
References _levels, and none.
level_name()
const translation& option_slider::level_name (int level) const inline
Definition at line 460 of file options.h.
{
             static const translation none;
             if( level >= 0 && level < static_cast<int>( _levels.size() ) ) {
                 return _levels[level].name();
             }
             return none;
         }
References _levels, and none.
load()
void option_slider::load (const JsonObject & jo, std::string_view src)
Definition at line 109 of file options.cpp.
 {
     mandatory( jo, was_loaded, "name", _name );
     optional( jo, was_loaded, "default", _default_level, 0 );
     optional( jo, was_loaded, "context", _context );
     mandatory( jo, was_loaded, "levels", _levels );
 }
References _context, _default_level, _levels, _name, mandatory, optional(), and was_loaded.
load_option_sliders()
void option_slider::load_option_sliders (const JsonObject & jo, const std::string & src) static
Definition at line 89 of file options.cpp.
 {
     option_slider_factory.load( jo, src );
 }
References anonymous_namespace{options.cpp}::option_slider_factory.
Referenced by DynamicDataLoader::initialize().
name()
const translation& option_slider::name () const inline
Definition at line 438 of file options.h.
{
             return _name;
         }
References _name.
Referenced by options_manager::addOptionToPage(), options_manager::deserialize(), options_manager::get_lang_options(), options_manager::get_option(), options_manager::has_option(), options_manager::migrateOptionName(), options_manager::migrateOptionValue(), options_manager::search_resource(), and options_manager::show().
random_level()
int option_slider::random_level () const
Definition at line 187 of file options.cpp.
 {
     return rng( 0, _levels.size() - 1 );
 }
References _levels, and rng().
reorder_opts()
void option_slider::reorder_opts () inline
Definition at line 431 of file options.h.
{
             std::sort( _levels.begin(), _levels.end(),
             []( const option_slider_level & a, const option_slider_level & b ) {
                 return a.level() < b.level();
             } );
         }
References _levels, a, and b.
Referenced by finalize_all().
reset()
void option_slider::reset () static
Definition at line 79 of file options.cpp.
 {
     option_slider_factory.reset();
 }
References anonymous_namespace{options.cpp}::option_slider_factory.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
_context
std::string option_slider::_context private
Definition at line 416 of file options.h.
Referenced by context(), and load().
_default_level
int option_slider::_default_level = 0 private
Definition at line 417 of file options.h.
Referenced by check(), default_level(), and load().
_levels
std::vector<option_slider_level> option_slider::_levels private
Definition at line 415 of file options.h.
Referenced by apply_opts(), check(), count(), level_desc(), level_name(), load(), random_level(), and reorder_opts().
_name
translation option_slider::_name private
Definition at line 414 of file options.h.
Referenced by load(), and name().
id
option_slider_id option_slider::id
Definition at line 420 of file options.h.
was_loaded
bool option_slider::was_loaded = false
Definition at line 421 of file options.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/options.h
src/options.cpp