Cataclysm DDA: mutable_overmap_terrain Struct Reference
mutable_overmap_terrain Struct Reference
Public Member Functions
void finalize (const std::string &context, const std::unordered_map< std::string, mutable_overmap_join * > &special_joins, const cata::flat_set< string_id< overmap_location >> &default_locations)
void check (const std::string &context) const
void deserialize (const JsonObject &jo)
Public Attributes
oter_str_id terrain
cata::flat_set< string_id< overmap_location > > locations
join_map joins
std::map< cube_direction, mutable_special_connection > connections
Detailed Description
Definition at line 1576 of file overmap.cpp.
Member Function Documentation
check()
void mutable_overmap_terrain::check (const std::string & context) const inline
Definition at line 1594 of file overmap.cpp.
{
         if( !terrain.is_valid() ) {
             debugmsg( "invalid overmap terrain id %s in %s", terrain.str(), context );
         }
         if( locations.empty() ) {
             debugmsg( "In %s, no locations are defined", context );
         }
         for( const string_id<overmap_location> &loc : locations ) {
             if( !loc.is_valid() ) {
                 debugmsg( "invalid overmap location id %s in %s", loc.str(), context );
             }
         }
         for( const std::pair<const cube_direction, mutable_special_connection> &p :
              connections ) {
             p.second.check( string_format( "connection %s in %s", io::enum_to_string( p.first ),
                                            context ) );
         }
     }
References connections, context, debugmsg, io::enum_to_string(), string_id< T >::is_valid(), locations, string_id< T >::str(), string_format(), and terrain.
Referenced by mutable_overmap_special_data::check().
deserialize()
void mutable_overmap_terrain::deserialize (const JsonObject & jo) inline
Definition at line 1616 of file overmap.cpp.
{
         jo.read( "overmap", terrain, true );
         jo.read( "locations", locations );
         for( int i = 0; i != static_cast<int>( cube_direction::last ); ++i ) {
             cube_direction dir = static_cast<cube_direction>( i );
             std::string dir_s = io::enum_to_string( dir );
             if( jo.has_member( dir_s ) ) {
                 jo.read( dir_s, joins[dir], true );
             }
         }
         jo.read( "connections", connections );
     }
References connections, io::enum_to_string(), JsonObject::has_member(), joins, last, locations, JsonObject::read(), and terrain.
finalize()
void mutable_overmap_terrain::finalize (const std::string & context, const std::unordered_map< std::string, mutable_overmap_join * > & special_joins, const cata::flat_set< string_id< overmap_location >> & default_locations) inline
Definition at line 1582 of file overmap.cpp.
{
         if( locations.empty() ) {
             locations = default_locations;
         }
         for( join_map::value_type &p : joins ) {
             mutable_overmap_terrain_join &ter_join = p.second;
             ter_join.finalize( context, special_joins );
         }
     }
References context, mutable_overmap_terrain_join::finalize(), joins, and locations.
Referenced by mutable_overmap_special_data::finalize().
Member Data Documentation
connections
std::map<cube_direction, mutable_special_connection> mutable_overmap_terrain::connections
Definition at line 1580 of file overmap.cpp.
Referenced by check(), deserialize(), and mutable_overmap_special_data::place().
joins
join_map mutable_overmap_terrain::joins
Definition at line 1579 of file overmap.cpp.
Referenced by joins_tracker::add_joins_for(), deserialize(), finalize(), and mutable_overmap_placement_rule::finalize().
locations
cata::flat_set<string_id<overmap_location> > mutable_overmap_terrain::locations
Definition at line 1578 of file overmap.cpp.
Referenced by check(), deserialize(), finalize(), and mutable_overmap_special_data::root_as_overmap_special_terrain().
terrain
oter_str_id mutable_overmap_terrain::terrain
Definition at line 1577 of file overmap.cpp.
Referenced by check(), deserialize(), mutable_overmap_special_data::finalize_mapgen_parameters(), mutable_overmap_special_data::place(), and mutable_overmap_special_data::root_as_overmap_special_terrain().
The documentation for this struct was generated from the following file:
src/overmap.cpp