Cataclysm DDA: mut_transform Struct Reference
mut_transform Struct Reference
#include <mutation.h>
Public Member Functions
mut_transform ()
bool load (const JsonObject &jsobj, std::string_view member)
Public Attributes
trait_id target
translation msg_transform
displayed if player sees transformation with s replaced by mutation name
bool active = false
used to set the active property of the transformed target
int moves = 0
subtracted from Creature::moves when transformation is successful
bool safe = false
Detailed Description
Definition at line 81 of file mutation.h.
Constructor & Destructor Documentation
mut_transform()
mut_transform::mut_transform () default
Member Function Documentation
load()
bool mut_transform::load (const JsonObject & jsobj, std::string_view member)
Definition at line 201 of file mutation_data.cpp.
 {
     JsonObject j = jsobj.get_object( member );
     assign( j, "target", target );
     assign( j, "msg_transform", msg_transform );
     assign( j, "active", active );
     optional( j, false, "safe", safe, false );
     assign( j, "moves", moves );
     return true;
 }
References active, assign(), JsonObject::get_object(), member, moves, msg_transform, optional(), safe, and target.
Member Data Documentation
active
bool mut_transform::active = false
used to set the active property of the transformed target
Definition at line 88 of file mutation.h.
Referenced by load().
moves
int mut_transform::moves = 0
subtracted from Creature::moves when transformation is successful
Definition at line 90 of file mutation.h.
Referenced by load().
msg_transform
translation mut_transform::msg_transform
displayed if player sees transformation with s replaced by mutation name
Definition at line 86 of file mutation.h.
Referenced by load().
safe
bool mut_transform::safe = false
Definition at line 92 of file mutation.h.
Referenced by load().
target
trait_id mut_transform::target
Definition at line 83 of file mutation.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/mutation.h
src/mutation_data.cpp