Cataclysm DDA: dealt_damage_instance Struct Reference
dealt_damage_instance Struct Reference
#include <damage.h>
Public Member Functions
dealt_damage_instance ()
void set_damage (const damage_type_id &dt, int amount)
int type_damage (const damage_type_id &dt) const
int total_damage () const
Public Attributes
std::map< damage_type_id, int > dealt_dams
bodypart_id bp_hit
std::string wp_hit
Detailed Description
Definition at line 193 of file damage.h.
Constructor & Destructor Documentation
dealt_damage_instance()
dealt_damage_instance::dealt_damage_instance ()
Definition at line 559 of file damage.cpp.
 {
     dealt_dams.clear();
     for( const damage_type &dt : damage_type::get_all() ) {
         dealt_dams.emplace( dt.id, 0 );
     }
     bp_hit  = bodypart_id( "torso" );
 }
References damage_type::get_all().
Member Function Documentation
set_damage()
void dealt_damage_instance::set_damage (const damage_type_id & dt, int amount)
Definition at line 568 of file damage.cpp.
 {
     if( !dt.is_valid() ) {
         debugmsg( "Tried to set invalid damage type %s.", dt.c_str() );
         return;
     }
     dealt_dams[dt] = amount;
 }
References string_id< T >::c_str(), debugmsg, and string_id< T >::is_valid().
Referenced by spell::get_dealt_damage_instance().
total_damage()
int dealt_damage_instance::total_damage () const
Definition at line 586 of file damage.cpp.
 {
     return std::accumulate( dealt_dams.begin(), dealt_dams.end(), 0,
     []( int acc, const std::pair<const damage_type_id, int> &dmg ) {
         return acc + dmg.second;
     } );
 }
Referenced by mattack::acid_barf(), mdefense::acidsplash(), Character::add_msg_player_or_say(), mattack::bio_op_impale(), map::burn_body_part(), melee_actor::call(), Character::deal_damage(), explosion_handler::do_blast(), item::effective_dps(), mattack::evolve_kill_strike(), Character::fire_gun(), mattack::flesh_golem(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_inject(), Character::hitall(), Character::impact(), mattack::lunge(), monster::melee_attack(), Character::melee_attack_abstract(), Character::perform_special_attacks(), map::player_in_field(), mdefense::return_fire(), sting_shoot(), mattack::stretch_attack(), and mattack::taze().
type_damage()
int dealt_damage_instance::type_damage (const damage_type_id & dt) const
Definition at line 577 of file damage.cpp.
 {
     auto iter = dealt_dams.find( dt );
     if( iter != dealt_dams.end() ) {
         return iter->second;
     }
     return 0;
 }
Referenced by trapfunc::beartrap(), trapfunc::board(), trapfunc::caltrops(), Character::deal_damage(), monster::melee_attack(), Character::melee_attack_abstract(), melee_message(), trapfunc::pit_glass(), trapfunc::pit_spikes(), and map::player_in_field().
Member Data Documentation
bp_hit
bodypart_id dealt_damage_instance::bp_hit
Definition at line 195 of file damage.h.
Referenced by Character::add_msg_player_or_say(), projectile::apply_effects_damage(), melee_actor::call(), Creature::deal_melee_hit(), monster::melee_attack(), melee_actor::on_damage(), bite_actor::on_damage(), and sting_shoot().
dealt_dams
std::map<damage_type_id, int> dealt_damage_instance::dealt_dams
Definition at line 194 of file damage.h.
Referenced by Creature::deal_damage(), and item::effective_dps().
wp_hit
std::string dealt_damage_instance::wp_hit
Definition at line 196 of file damage.h.
Referenced by Character::add_msg_player_or_say(), Creature::deal_damage(), Character::melee_attack_abstract(), and melee_message().
The documentation for this struct was generated from the following files:
src/damage.h
src/damage.cpp