Cataclysm DDA: overmap_spawns Struct Reference
overmap_spawns Struct Reference
#include <omdata.h>
Public Member Functions
overmap_spawns ()
bool operator== (const overmap_spawns &rhs) const
Public Attributes
string_id< MonsterGroup > group
numeric_interval< int > population
Protected Member Functions
void load (const JsonObject &jo)
Detailed Description
Definition at line 140 of file omdata.h.
Constructor & Destructor Documentation
overmap_spawns()
overmap_spawns::overmap_spawns () inline
Definition at line 141 of file omdata.h.
 : group( mongroup_id::NULL_ID() ) {}
Member Function Documentation
load()
void overmap_spawns::load (const JsonObject & jo) inline protected
Definition at line 151 of file omdata.h.
{
             jo.read( "group", group );
             jo.read( "population", population );
         }
References group, population, and JsonObject::read().
Referenced by overmap_static_spawns::deserialize(), and overmap_special_spawns::deserialize().
operator==()
bool overmap_spawns::operator== (const overmap_spawns & rhs) const inline
Definition at line 146 of file omdata.h.
{
             return group == rhs.group && population == rhs.population;
         }
References group, and population.
Referenced by overmap_special_spawns::operator==(), and overmap_static_spawns::operator==().
Member Data Documentation
group
string_id<MonsterGroup> overmap_spawns::group
Definition at line 143 of file omdata.h.
Referenced by map::generate(), load(), operator==(), overmap::place_special(), and game::spawn_hallucination().
population
numeric_interval<int> overmap_spawns::population
Definition at line 144 of file omdata.h.
Referenced by map::generate(), load(), operator==(), and overmap::place_special().
The documentation for this struct was generated from the following file:
src/omdata.h