Cataclysm DDA: requirement_data Struct Reference
requirement_data Struct Reference
The *_vector members represent list of alternatives requirements: alter_tool_comp_vector = { * { { a, b }, { c, d } } That means: the player needs (requirement a or b) and (requirement c or d).
#include <requirements.h>
Public Types
using alter_tool_comp_vector = std::vector< std::vector< tool_comp > >
using alter_quali_req_vector = std::vector< std::vector< quality_requirement > >
using alter_item_comp_vector = std::vector< std::vector< item_comp > >
Public Member Functions
requirement_data ()=default
requirement_data (const alter_tool_comp_vector &tools, const alter_quali_req_vector &qualities, const alter_item_comp_vector &components)
template<typename Container , typename = std::enable_if_t < std::is_same_v < typename Container::value_type, std::pair<requirement_id, int >> || std::is_same_v < typename Container::value_type, std::pair<const requirement_id, int >> >>
requirement_data (const Container &cont)
const requirement_id & id () const
bool is_null () const
null requirements are always empty (were never initialized)
bool is_empty () const
empty requirements are not necessary null
bool is_blacklisted () const
requirement_data operator* (unsigned scalar) const
Scales tool and component requirements leaving qualities unaffected.
requirement_data operator+ (const requirement_data &rhs) const
Combines two sets of requirements.
requirement_data operator+ (const std::pair< const requirement_id, int > &rhs) const
Incorporate data from an id and integer.
requirement_data operator+ (const std::pair< requirement_id, int > &rhs) const
void serialize (JsonOut &json) const
Serialize custom created requirement objects for fetch activities.
void deserialize (const JsonObject &data)
std::string list_all () const
Returns a list of components/tools/qualities that are required, nicely formatted for popup window or similar.
std::string list_missing () const
Returns a list of components/tools/qualities that are not available, nicely formatted for popup window or similar.
void blacklist_item (const itype_id &id)
Remove tools or components of given type leaving qualities unchanged.
void replace_items (const std::unordered_map< itype_id, itype_id > &replacements)
Replace tools or components using a provided replacement map.
const alter_tool_comp_vector & get_tools () const
const alter_quali_req_vector & get_qualities () const
const alter_item_comp_vector & get_components () const
alter_item_comp_vector & get_components ()
bool can_make_with_inventory (const read_only_visitable &crafting_inv, const std::function< bool(const item &)> &filter, int batch=1, craft_flags=craft_flags::none) const
Returns true if the requirements are fulfilled by the filtered inventory.
std::vector< std::string > get_folded_components_list (int width, nc_color col, const read_only_visitable &crafting_inv, const std::function< bool(const item &)> &filter, int batch=1, std::string_view hilite={}, requirement_display_flags=requirement_display_flags::none) const
std::vector< std::string > get_folded_tools_list (int width, nc_color col, const read_only_visitable &crafting_inv, int batch=1) const
requirement_data disassembly_requirements () const
Gets a variant of this recipe with crafting-only tools replaced by their disassembly equivalents.
void consolidate ()
Merge similar quality/tool/component lists.
bool has_same_requirements_as (const requirement_data &that) const
Compares if two requirement_data are the same, but does not compare the requirement ids.
void dump (JsonOut &jsout) const
Dump to json in inline requirements format.
uint64_t make_hash () const
Static Public Member Functions
static void load_requirement (const JsonObject &jsobj, const requirement_id &id=requirement_id::NULL_ID(), bool check_extend=false)
Load tools, qualities and components from the json object.
static void save_requirement (const requirement_data &req, const requirement_id &id=requirement_id::NULL_ID(), const requirement_data *extend=nullptr)
Store requirement data for future lookup.
static std::vector< requirement_data > get_all ()
static const std::map< requirement_id, requirement_data > & all ()
Get all currently loaded requirements.
static void finalize ()
Finalizes requirements, must be called AFTER finalizing items, but before recipes!
static void check_consistency ()
Check consistency of all loaded requirements.
static void reset ()
Clear all loaded requirements (invalidating any pointers)
static requirement_data continue_requirements (const std::vector< item_comp > &required_comps, const item_components &remaining_comps)
Returns the item requirements to continue an in progress craft with the passed components.
Private Member Functions
bool check_enough_materials (const read_only_visitable &crafting_inv, const std::function< bool(const item &)> &filter, int batch=1) const
bool check_enough_materials (const item_comp &comp, const read_only_visitable &crafting_inv, const std::function< bool(const item &)> &filter, int batch=1) const
template<typename T >
std::vector< std::string > get_folded_list (int width, const read_only_visitable &crafting_inv, const std::function< bool(const item &)> &filter, const std::vector< std::vector< T > > &objs, int batch=1, std::string_view hilite={}, requirement_display_flags=requirement_display_flags::none) const
Static Private Member Functions
template<typename T >
static void check_consistency (const std::vector< std::vector< T > > &vec, const std::string &display_name)
template<typename T >
static void finalize (std::vector< std::vector< T > > &vec)
template<typename T >
static std::string print_all_objs (const std::string &header, const std::vector< std::vector< T > > &objs)
template<typename T >
static std::string print_missing_objs (const std::string &header, const std::vector< std::vector< T > > &objs)
template<typename T >
static bool has_comps (const read_only_visitable &crafting_inv, const std::vector< std::vector< T > > &vec, const std::function< bool(const item &)> &filter, int batch=1, craft_flags=craft_flags::none)
template<typename T >
static bool any_marked_available (const std::vector< T > &comps)
template<typename T >
static void load_obj_list (const JsonArray &jsarr, std::vector< std::vector< T > > &objs)
template<typename T , typename ID >
static const T * find_by_type (const std::vector< std::vector< T > > &vec, const ID &type)
Private Attributes
alter_tool_comp_vector tools
alter_quali_req_vector qualities
alter_item_comp_vector components
requirement_id id_ = requirement_id::NULL_ID()
bool blacklisted = false
Friends
class vpart_info
Detailed Description
The *_vector members represent list of alternatives requirements: alter_tool_comp_vector = { * { { a, b }, { c, d } } That means: the player needs (requirement a or b) and (requirement c or d).
Some functions in this struct use template arguments so they can be applied to all three *_vector members. For example: check_consistency iterates over all entries in the supplied vector and calls check_consistency on each entry. If called as check_consistency(tools) this will actually call tool_comp::check_consistency. If called as check_consistency(qualities) it will call quality_requirement:check_consistency.
Requirements (item_comp, tool_comp, quality_requirement) must have those functions: Load from an entry of a json array: void load(const JsonValue &value); Check whether the player has fulfills the requirement with this crafting inventory (or by mutation): bool has(const inventory &crafting_inv) const; A textual representation of the requirement: std::string to_string() const; Consistency check: void check_consistency(const std::string &display_name) const; Color to be used for displaying the requirement. has_one is true of the player fulfills an alternative requirement: nc_color get_color(bool has_one, const inventory &crafting_inv) const;
Definition at line 209 of file requirements.h.
Member Typedef Documentation
alter_item_comp_vector
using requirement_data::alter_item_comp_vector = std::vector<std::vector<item_comp> >
Definition at line 217 of file requirements.h.
alter_quali_req_vector
using requirement_data::alter_quali_req_vector = std::vector<std::vector<quality_requirement> >
Definition at line 216 of file requirements.h.
alter_tool_comp_vector
using requirement_data::alter_tool_comp_vector = std::vector<std::vector<tool_comp> >
Definition at line 215 of file requirements.h.
Constructor & Destructor Documentation
requirement_data() [1/3]
requirement_data::requirement_data () default
requirement_data() [2/3]
requirement_data::requirement_data (const alter_tool_comp_vector & tools, const alter_quali_req_vector & qualities, const alter_item_comp_vector & components) inline
Definition at line 227 of file requirements.h.
                                                                      : tools( tools ), qualities( qualities ),
             components( components ) {}
requirement_data() [3/3]
template<typename Container , typename = std::enable_if_t < std::is_same_v < typename Container::value_type, std::pair<requirement_id, int >> || std::is_same_v < typename Container::value_type, std::pair<const requirement_id, int >> >> requirement_data::requirement_data (const Container & cont) inline explicit
Definition at line 240 of file requirements.h.
                                                            :
             requirement_data(
                 std::accumulate(
                     cont.begin(), cont.end(), requirement_data() ) )
         {}
Member Function Documentation
all()
const std::map< requirement_id, requirement_data > & requirement_data::all () static
Get all currently loaded requirements.
Definition at line 612 of file requirements.cpp.
 {
     return requirements_all;
 }
References requirements_all.
Referenced by check_consistency(), finalize(), Item_factory::finalize_item_blacklist(), and generic_multi_activity_check_requirement().
any_marked_available()
template<typename T > bool requirement_data::any_marked_available (const std::vector< T > & comps) static private
Definition at line 505 of file requirements.cpp.
 {
     for( const auto &comp : comps ) {
         if( comp.available == available_status::a_true ) {
             return true;
         }
     }
     return false;
 }
References a_true.
Referenced by get_folded_list(), and print_missing_objs().
blacklist_item()
void requirement_data::blacklist_item (const itype_id & id)
Remove tools or components of given type leaving qualities unchanged.
Note
if the last available component of a grouping is removed the recipe will be marked as blacklisted
Definition at line 1114 of file requirements.cpp.
 {
     blacklisted |= apply_blacklist( tools, id );
     blacklisted |= apply_blacklist( components, id );
 }
References apply_blacklist(), blacklisted, components, and tools.
can_make_with_inventory()
bool requirement_data::can_make_with_inventory (const read_only_visitable & crafting_inv, const std::function< bool(const item &)> & filter, int batch = 1, craft_flags flags = craft_flags::none) const
Returns true if the requirements are fulfilled by the filtered inventory.
Parameters
filter should be recipe::get_component_filter() if used with a recipe or is_crafting_component otherwise.
Definition at line 840 of file requirements.cpp.
 {
     if( get_player_character().has_trait( trait_DEBUG_HS ) ) {
         return true;
     }
     bool retval = true;
     // All functions must be called to update the available settings in the components.
     if( !has_comps( crafting_inv, qualities, return_true<item> ) ) {
         retval = false;
     }
     if( !has_comps( crafting_inv, tools, return_true<item>, batch, flags ) ) {
         retval = false;
     }
     if( !has_comps( crafting_inv, components, filter, batch ) ) {
         retval = false;
     }
     if( !check_enough_materials( crafting_inv, filter, batch ) ) {
         retval = false;
     }
     return retval;
 }
References check_enough_materials(), components, filter, get_player_character(), has_comps(), qualities, tools, and trait_DEBUG_HS.
Referenced by are_requirements_nearby(), iexamine::autoclave_empty(), anonymous_namespace{crafting_gui.cpp}::availability::availability(), basecamp::available_upgrades(), spell::can_cast(), Character::can_continue_craft(), can_do_activity_there(), veh_interact::can_potentially_install(), spell::check_if_component_in_hand(), veh_interact::complete_vehicle(), construction_menu(), iexamine::cvdmachine(), veh_interact::format_reqs(), get_folded_list(), Character::has_enough_anesth(), Character::has_installation_requirement(), Character::mend_item(), activity_handlers::mend_item_finish(), veh_utils::most_repairable_part(), iexamine::nanofab(), player_can_build(), veh_app_interact::remove(), veh_utils::repair_part(), set_up_butchery(), and basecamp::start_upgrade().
check_consistency() [1/2]
void requirement_data::check_consistency () static
Check consistency of all loaded requirements.
Definition at line 617 of file requirements.cpp.
 {
     for( const auto &r : all() ) {
         check_consistency( r.second.tools, r.first.str() );
         check_consistency( r.second.components, r.first.str() );
         check_consistency( r.second.qualities, r.first.str() );
     }
 }
References all().
Referenced by DynamicDataLoader::check_consistency().
check_consistency() [2/2]
template<typename T > void requirement_data::check_consistency (const std::vector< std::vector< T > > & vec, const std::string & display_name) static private
Definition at line 598 of file requirements.cpp.
 {
     for( const auto &list : vec ) {
         for( const auto &comp : list ) {
             if( comp.requirement ) {
                 debugmsg( "Finalization failed to inline %s in %s", comp.type.c_str(), display_name );
             }
             comp.check_consistency( display_name );
         }
     }
 }
References debugmsg.
check_enough_materials() [1/2]
bool requirement_data::check_enough_materials (const item_comp & comp, const read_only_visitable & crafting_inv, const std::function< bool(const item &)> & filter, int batch = 1) const private
Definition at line 1043 of file requirements.cpp.
 {
     if( comp.available != available_status::a_true ) {
         return false;
     }
     const int cnt = std::abs( comp.count ) * batch;
     const tool_comp *tq = find_by_type( tools, comp.type );
     if( tq != nullptr && tq->available == available_status::a_true ) {
         // The very same item type is also needed as tool!
         // Use charges of it, or use it by count?
         const int tc = tq->by_charges() ? 1 : std::abs( tq->count );
         // Check for components + tool count. Check item amount (excludes
         // pseudo items) and tool amount (includes pseudo items)
         // Imagine: required = 1 welder (component) + 1 welder (tool),
         // available = 1 welder (real item), 1 welding rig (creates
         // a pseudo welder item). has_components(welder,2) returns false
         // as there is only one real welder available, but has_tools(welder,2)
         // returns true.
         // Keep in mind that both requirements (tool+component) are checked
         // before this. That assures that one real item is actually available,
         // two welding rigs (and no real welder) would make this component
         // non-available even before this function is called.
         // Only ammo and (some) food is counted by charges, both are unlikely
         // to appear as tool, but it's possible /-:
         const item_comp i_tmp( comp.type, cnt + tc );
         const tool_comp t_tmp( comp.type, -( cnt + tc ) ); // not by charges!
         // batch factor is explicitly 1, because it's already included in the count.
         if( !i_tmp.has( crafting_inv, filter, 1 ) && !t_tmp.has( crafting_inv, filter, 1 ) ) {
             comp.available = available_status::a_insufficient;
         }
     }
     const itype *it = item::find_type( comp.type );
     for( const auto &ql : it->qualities ) {
         const quality_requirement *qr = find_by_type( qualities, ql.first );
         if( qr == nullptr || qr->level > ql.second ) {
             continue;
         }
         // This item can be used for the quality requirement, same as above for specific
         // tools applies.
         if( !crafting_inv.has_quality( qr->type, qr->level, qr->count + std::abs( comp.count ) ) ) {
             comp.available = available_status::a_insufficient;
         }
     }
     return comp.available == available_status::a_true;
 }
References a_insufficient, a_true, abs(), component::available, tool_comp::by_charges(), component::count, quality_requirement::count, filter, find_by_type(), item::find_type(), tool_comp::has(), item_comp::has(), read_only_visitable::has_quality(), quality_requirement::level, itype::qualities, qualities, tools, component::type, and quality_requirement::type.
check_enough_materials() [2/2]
bool requirement_data::check_enough_materials (const read_only_visitable & crafting_inv, const std::function< bool(const item &)> & filter, int batch = 1) const private
Definition at line 1025 of file requirements.cpp.
 {
     bool retval = true;
     for( const auto &component_choices : components ) {
         bool atleast_one_available = false;
         for( const item_comp &comp : component_choices ) {
             if( check_enough_materials( comp, crafting_inv, filter, batch ) ) {
                 atleast_one_available = true;
             }
         }
         if( !atleast_one_available ) {
             retval = false;
         }
     }
     return retval;
 }
References components, and filter.
Referenced by can_make_with_inventory().
consolidate()
void requirement_data::consolidate ()
Merge similar quality/tool/component lists.
This simplifies the requirement but may make the requirement stricter.
Definition at line 1407 of file requirements.cpp.
 {
     qualities = ::consolidate( qualities,
     []( const quality_requirement & lhs, const quality_requirement & rhs ) {
         quality_requirement ret = lhs;
         ret.count = std::max( ret.count, rhs.count );
         ret.level = std::max( ret.level, rhs.level );
         return ret;
     } );
     tools = ::consolidate( tools,
     []( const tool_comp & lhs, const tool_comp & rhs ) {
         tool_comp ret = lhs;
         if( ret.count < 0 && rhs.count < 0 ) {
             ret.count = std::min( ret.count, rhs.count );
         } else if( ret.count > 0 && rhs.count > 0 ) {
             ret.count += rhs.count;
         } else {
             debugmsg( "required counts of the same tool have different signs" );
         }
         return ret;
     } );
     components = ::consolidate( components,
     []( const item_comp & lhs, const item_comp & rhs ) {
         item_comp ret = lhs;
         ret.count += rhs.count;
         return ret;
     } );
 }
References components, quality_requirement::count, quality_requirement::level, max(), qualities, cata::hash64_detail::ret, and tools.
Referenced by recipe::check_blueprint_requirements(), and build_reqs::consolidate().
continue_requirements()
requirement_data requirement_data::continue_requirements (const std::vector< item_comp > & required_comps, const item_components & remaining_comps) static
Returns the item requirements to continue an in progress craft with the passed components.
Returned requirement_data is for all batches at once.
Definition at line 1282 of file requirements.cpp.
 {
     // Create an empty requirement_data
     requirement_data ret;
     // For items we can't change what alternative we selected half way through
     for( const item_comp &it : required_comps ) {
         ret.components.emplace_back( std::vector<item_comp>( {it} ) );
     }
     inventory craft_components;
     craft_components += remaining_comps;
     // Remove requirements that are completely fulfilled by current craft components
     // For each requirement that isn't completely fulfilled, reduce the requirement by the amount
     // that we still have
     // We also need to consume whatever charges we use in case two requirements share a common type
     ret.components.erase( std::remove_if( ret.components.begin(), ret.components.end(),
     [&craft_components]( std::vector<item_comp> &comps ) {
         item_comp &comp = comps.front();
         if( item::count_by_charges( comp.type ) && comp.count > 0 ) {
             int qty = craft_components.charges_of( comp.type, comp.count );
             comp.count -= qty;
             // This is terrible but inventory doesn't have a use_charges() function so...
             std::vector<item *> del;
             craft_components.visit_items( [&comp, &qty, &del]( item * e, item * ) {
                 std::list<item> used;
                 if( e->use_charges( comp.type, qty, used, tripoint_zero ) ) {
                     del.push_back( e );
                 }
                 return qty > 0 ? VisitResponse::SKIP : VisitResponse::ABORT;
             } );
             craft_components.remove_items_with( [&del]( const item & e ) {
                 for( const item *it : del ) {
                     if( it == &e ) {
                         return true;
                     }
                 }
                 return false;
             } );
         } else {
             int amount = craft_components.amount_of( comp.type, comp.count );
             comp.count -= amount;
             craft_components.use_amount( comp.type, amount );
         }
         return comp.count <= 0;
     } ), ret.components.end() );
     return ret;
 }
References cata::hash64_detail::ret.
Referenced by item::get_continue_reqs().
deserialize()
void requirement_data::deserialize (const JsonObject & data)
Definition at line 441 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     data.read( "blacklisted", blacklisted );
     data.read( "req_comps_total", components );
     data.read( "tool_comps_total", tools );
     data.read( "quality_comps_total", qualities );
 }
References item_pocket::data.
disassembly_requirements()
requirement_data requirement_data::disassembly_requirements () const
Gets a variant of this recipe with crafting-only tools replaced by their disassembly equivalents.
Definition at line 1172 of file requirements.cpp.
 {
     // TODO:
     // Allow jsonizing those tool replacements
     // Make a copy
     // Maybe TODO: Cache it somewhere and return a reference instead
     requirement_data ret = *this;
     auto new_qualities = std::vector<quality_requirement>();
     bool remove_fire = false;
     for( auto &it : ret.tools ) {
         bool replaced = false;
         for( const tool_comp &tool : it ) {
             const itype_id &type = tool.type;
             // If crafting required a welder or forge then disassembly requires metal sawing
             if( type == itype_welder || type == itype_welder_crude || type == itype_oxy_torch ||
                 type == itype_forge || type == itype_char_forge ) {
                 new_qualities.emplace_back( qual_SAW_M_FINE, 1, 1 );
                 replaced = true;
                 break;
             }
             if( type == itype_crucible ) {
                 replaced = true;
                 break;
             }
             //This ensures that you don't need a hand press to break down reloaded ammo.
             if( type == itype_press ) {
                 replaced = true;
                 remove_fire = true;
                 new_qualities.emplace_back( qual_PULL, 1, 1 );
                 break;
             }
             if( type == itype_fire && remove_fire ) {
                 replaced = true;
                 break;
             }
         }
         if( replaced ) {
             // Replace the entire block of variants
             // This avoids the pesky integrated toolset
             it.clear();
         }
     }
     // Warning: This depends on the fact that tool qualities
     // are all mandatory (don't use variants)
     // If that ever changes, this will be wrong!
     if( ret.qualities.empty() ) {
         ret.qualities.resize( 1 );
     } else {
         //If the required quality level is not empty, iterate through and replace or remove
         //qualities with deconstruction equivalents
         for( auto &it : ret.qualities ) {
             bool replaced = false;
             for( const quality_requirement &quality : it ) {
                 if( quality.type == qual_SEW ) {
                     replaced = true;
                     new_qualities.emplace_back( qual_CUT, 1, quality.level );
                     break;
                 }
                 if( quality.type == qual_GLARE ) {
                     replaced = true;
                     //Just remove the glare protection requirement from deconstruction
                     //This only happens in case of a reversible recipe, an explicit
                     //deconstruction recipe can still specify glare protection
                     break;
                 }
                 if( quality.type == qual_KNIT ) {
                     replaced = true;
                     //Ditto for knitting needles
                     break;
                 }
             }
             if( replaced ) {
                 it.clear();
             }
         }
     }
     auto &qualities = ret.qualities[0];
     qualities.insert( qualities.end(), new_qualities.begin(), new_qualities.end() );
     // Remove duplicate qualities
     {
         const auto itr = std::unique( qualities.begin(), qualities.end(),
         []( const quality_requirement & a, const quality_requirement & b ) {
             return a.type == b.type;
         } );
         qualities.resize( std::distance( qualities.begin(), itr ) );
     }
     // Remove empty variant sections
     ret.tools.erase( std::remove_if( ret.tools.begin(), ret.tools.end(),
     []( const std::vector<tool_comp> &tcv ) {
         return tcv.empty();
     } ), ret.tools.end() );
     // Remove unrecoverable components
     ret.components.erase( std::remove_if( ret.components.begin(), ret.components.end(),
     []( std::vector<item_comp> &cov ) {
         cov.erase( std::remove_if( cov.begin(), cov.end(),
         []( const item_comp & comp ) {
             return !comp.recoverable || item( comp.type ).has_flag( STATIC( flag_id( "UNRECOVERABLE" ) ) );
         } ), cov.end() );
         return cov.empty();
     } ), ret.components.end() );
     return ret;
 }
References a, b, itype_char_forge, itype_crucible, itype_fire, itype_forge, itype_oxy_torch, itype_press, itype_welder, itype_welder_crude, qual_CUT, qual_GLARE, qual_KNIT, qual_PULL, qual_SAW_M_FINE, qual_SEW, qualities, cata::hash64_detail::ret, and type.
Referenced by recipe::disassembly_requirements().
dump()
void requirement_data::dump (JsonOut & jsout) const
Dump to json in inline requirements format.
Definition at line 1475 of file requirements.cpp.
 {
     jsout.start_object( /*wrap=*/true );
     jsout.member( "tools" );
     dump_req_vec( tools, jsout );
     jsout.member( "qualities" );
     dump_req_vec( qualities, jsout );
     jsout.member( "components" );
     dump_req_vec( components, jsout );
     jsout.end_object();
 }
References components, dump_req_vec(), JsonOut::end_object(), JsonOut::member(), qualities, JsonOut::start_object(), and tools.
Referenced by recipe::check_blueprint_requirements(), and make_hash().
finalize() [1/2]
void requirement_data::finalize () static
Finalizes requirements, must be called AFTER finalizing items, but before recipes!
Definition at line 702 of file requirements.cpp.
 {
     for( auto &r : const_cast<std::map<requirement_id, requirement_data> &>( all() ) ) {
         inline_requirements<tool_comp>( r.second.tools, []( const requirement_data & d ) -> const auto & {
             return d.get_tools();
         } );
         inline_requirements<item_comp>( r.second.components,
         []( const requirement_data & d ) -> const auto & {
             return d.get_components();
         } );
         requirement_data::alter_tool_comp_vector &vec = r.second.tools;
         for( auto &list : vec ) {
             std::vector<tool_comp> new_list;
             for( tool_comp &comp : list ) {
                 const auto replacements = item_controller->subtype_replacement( comp.type );
                 for( const auto &replaced_type : replacements ) {
                     new_list.emplace_back( replaced_type, comp.count );
                 }
             }
             list = new_list;
         }
     }
 }
References all(), and item_controller.
Referenced by DynamicDataLoader::finalize_loaded_data().
finalize() [2/2]
template<typename T > static void requirement_data::finalize (std::vector< std::vector< T > > & vec) static private
find_by_type()
template<typename T , typename ID > const T * requirement_data::find_by_type (const std::vector< std::vector< T > > & vec, const ID & type) static private
Definition at line 1012 of file requirements.cpp.
 {
     for( const auto &list : vec ) {
         for( const auto &comp : list ) {
             if( comp.type == type ) {
                 return &comp;
             }
         }
     }
     return nullptr;
 }
References type.
Referenced by check_enough_materials().
get_all()
std::vector< requirement_data > requirement_data::get_all () static
Definition at line 82 of file requirements.cpp.
 {
     std::vector<requirement_data> ret;
     ret.reserve( requirements_all.size() );
     for( const std::pair<const requirement_id, requirement_data> &pair : requirements_all ) {
         ret.push_back( pair.second );
     }
     return ret;
 }
References requirements_all, and cata::hash64_detail::ret.
get_components() [1/2]
requirement_data::alter_item_comp_vector & requirement_data::get_components ()
Definition at line 1167 of file requirements.cpp.
 {
     return components;
 }
References components.
get_components() [2/2]
const requirement_data::alter_item_comp_vector & requirement_data::get_components () const
Definition at line 1162 of file requirements.cpp.
 {
     return components;
 }
References components.
Referenced by iexamine::autoclave_empty(), iexamine::autodoc(), Character::can_continue_craft(), can_do_activity_there(), basecamp_action_components::choose_components(), Character::complete_disassemble(), veh_interact::complete_vehicle(), Character::compute_nutrient_range(), construction_activity(), Character::consume_anesth_requirement(), Character::consume_installation_requirement(), salvage_actor::cut_up(), iexamine::cvdmachine(), deduped_requirement_data::deduped_requirement_data(), item::disassembly_info(), craft_command::execute(), item::final_info(), recipe_dictionary::find_items_on_loops(), generic_multi_activity_check_requirement(), recipe_result_info_cache::get_item_header(), vehicle_part::get_salvageable(), item::get_uncraft_components(), recipe_subset::include(), activity_handlers::mend_item_finish(), mill_activate(), iexamine::mill_finalize(), iuse::multicooker(), iexamine::nanofab(), peek_related_recipe(), place_construction(), veh_utils::repair_part(), requirements_map(), debug_menu::spell_description(), spellcasting_callback::spell_info_text(), and spell::use_components().
get_folded_components_list()
std::vector< std::string > requirement_data::get_folded_components_list (int width, nc_color col, const read_only_visitable & crafting_inv, const std::function< bool(const item &)> & filter, int batch = 1, std::string_view hilite = {}, requirement_display_flags flags = requirement_display_flags::none) const
Parameters
filter see can_make_with_inventory
Definition at line 732 of file requirements.cpp.
 {
     std::vector<std::string> out_buffer;
     if( components.empty() ) {
         return out_buffer;
     }
     out_buffer.push_back( colorize( _( "Components required:" ), col ) );
     std::vector<std::string> folded_buffer =
         get_folded_list( width, crafting_inv, filter, components, batch, hilite, flags );
     out_buffer.insert( out_buffer.end(), folded_buffer.begin(), folded_buffer.end() );
     return out_buffer;
 }
References _, colorize(), components, filter, get_folded_list(), and hilite().
Referenced by basecamp::craft_description(), veh_interact::format_reqs(), Character::mend_item(), basecamp::om_upgrade_description(), recipe_info(), set_up_butchery(), debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
get_folded_list()
template<typename T > std::vector< std::string > requirement_data::get_folded_list (int width, const read_only_visitable & crafting_inv, const std::function< bool(const item &)> & filter, const std::vector< std::vector< T > > & objs, int batch = 1, std::string_view hilite = {}, requirement_display_flags flags = requirement_display_flags::none) const private
Definition at line 751 of file requirements.cpp.
 {
     // hack: ensure 'cached' availability is up to date
     can_make_with_inventory( crafting_inv, filter );
     const bool no_unavailable =
         static_cast<bool>( flags & requirement_display_flags::no_unavailable );
     std::vector<std::string> out_buffer;
     for( const auto &comp_list : objs ) {
         const bool has_one = any_marked_available( comp_list );
         std::vector<std::string> list_as_string;
         std::vector<std::string> list_as_string_unavailable;
         std::vector<std::string> buffer_has;
         for( const T &component : comp_list ) {
             nc_color color = component.get_color( has_one, crafting_inv, filter, batch );
             const std::string color_tag = get_tag_from_color( color );
             int qty = 0;
             if( component.get_component_type() == component_type::ITEM ) {
                 const itype_id item_id = itype_id( component.type.str() );
                 if( item::count_by_charges( item_id ) ) {
                     qty = crafting_inv.charges_of( item_id, INT_MAX, filter );
                 } else {
                     qty = crafting_inv.amount_of( item_id, false, INT_MAX, filter );
                 }
             }
             const std::string text = component.to_string( batch, qty );
             if( std::find( buffer_has.begin(), buffer_has.end(), text + color_tag ) != buffer_has.end() ) {
                 continue;
             }
             if( !hilite.empty() && lcmatch( text, hilite ) ) {
                 color = yellow_background( color );
             }
             if( component.has( crafting_inv, filter, batch ) ) {
                 list_as_string.push_back( colorize( text, color ) );
             } else if( !no_unavailable ) {
                 list_as_string_unavailable.push_back( colorize( text, color ) );
             }
             buffer_has.push_back( text + color_tag );
         }
         std::sort( list_as_string.begin(), list_as_string.end(), localized_compare );
         std::sort( list_as_string_unavailable.begin(), list_as_string_unavailable.end(),
                    localized_compare );
         list_as_string.insert( list_as_string.end(), list_as_string_unavailable.begin(),
                                list_as_string_unavailable.end() );
         const std::string separator = colorize( _( " OR " ), c_white );
         const std::string unfolded = string_join( list_as_string, separator );
         std::vector<std::string> folded = foldstring( unfolded, width - 2 );
         for( size_t i = 0; i < folded.size(); i++ ) {
             if( i == 0 ) {
                 out_buffer.push_back( std::string( "> " ).append( folded[i] ) );
             } else {
                 out_buffer.push_back( std::string( "  " ).append( folded[i] ) );
             }
         }
     }
     return out_buffer;
 }
References _, read_only_visitable::amount_of(), any_marked_available(), c_white, can_make_with_inventory(), read_only_visitable::charges_of(), color(), colorize(), item::count_by_charges(), filter, foldstring(), get_tag_from_color(), hilite(), ITEM, itype_id, lcmatch(), localized_compare, no_unavailable, string_id< T >::str(), string_join(), component::type, and yellow_background().
Referenced by get_folded_components_list(), and get_folded_tools_list().
get_folded_tools_list()
std::vector< std::string > requirement_data::get_folded_tools_list (int width, nc_color col, const read_only_visitable & crafting_inv, int batch = 1) const
Definition at line 819 of file requirements.cpp.
 {
     std::vector<std::string> output_buffer;
     output_buffer.push_back( colorize( _( "Tools required:" ), col ) );
     if( tools.empty() && qualities.empty() ) {
         output_buffer.push_back( colorize( "> ", col ) + colorize( _( "NONE" ), c_green ) );
         return output_buffer;
     }
     std::vector<std::string> folded_qualities = get_folded_list( width, crafting_inv, return_true<item>,
             qualities );
     output_buffer.insert( output_buffer.end(), folded_qualities.begin(), folded_qualities.end() );
     std::vector<std::string> folded_tools = get_folded_list( width, crafting_inv, return_true<item>,
                                             tools,
                                             batch );
     output_buffer.insert( output_buffer.end(), folded_tools.begin(), folded_tools.end() );
     return output_buffer;
 }
References _, c_green, colorize(), get_folded_list(), qualities, and tools.
Referenced by basecamp::craft_description(), veh_interact::format_reqs(), Character::mend_item(), basecamp::om_upgrade_description(), recipe_info(), set_up_butchery(), debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
get_qualities()
const requirement_data::alter_quali_req_vector & requirement_data::get_qualities () const
Definition at line 1157 of file requirements.cpp.
 {
     return qualities;
 }
References qualities.
Referenced by Character::can_disassemble(), can_do_activity_there(), deduped_requirement_data::deduped_requirement_data(), item::disassembly_info(), generic_multi_activity_check_requirement(), requirements_map(), debug_menu::spell_description(), and spellcasting_callback::spell_info_text().
get_tools()
const requirement_data::alter_tool_comp_vector & requirement_data::get_tools () const
Definition at line 1152 of file requirements.cpp.
 {
     return tools;
 }
References tools.
Referenced by iexamine::autoclave_empty(), iexamine::autodoc(), Character::can_continue_craft(), Character::can_disassemble(), can_do_activity_there(), basecamp_action_components::choose_components(), Character::complete_disassemble(), veh_interact::complete_vehicle(), construction_activity(), Character::consume_anesth_requirement(), Character::consume_installation_requirement(), iexamine::cvdmachine(), deduped_requirement_data::deduped_requirement_data(), item::disassembly_info(), craft_command::execute(), generic_multi_activity_check_requirement(), bionic_install_preset::get_anesth_amount(), bionic_install_preset::get_denial(), recipe::hot_result(), activity_handlers::mend_item_finish(), iexamine::nanofab(), place_construction(), veh_utils::repair_part(), requirements_map(), debug_menu::spell_description(), spellcasting_callback::spell_info_text(), and spell::use_components().
has_comps()
template<typename T > bool requirement_data::has_comps (const read_only_visitable & crafting_inv, const std::vector< std::vector< T > > & vec, const std::function< bool(const item &)> & filter, int batch = 1, craft_flags flags = craft_flags::none) static private
Definition at line 865 of file requirements.cpp.
 {
     bool retval = true;
     int total_UPS_charges_used = 0;
     for( const std::vector<T> &set_of_tools : vec ) {
         bool has_tool_in_set = false;
         int UPS_charges_used = std::numeric_limits<int>::max();
         const std::function<void( int )> use_ups = [ &UPS_charges_used ]( int charges ) {
             UPS_charges_used = std::min( UPS_charges_used, charges );
         };
         for( const T &tool : set_of_tools ) {
             if( tool.has( crafting_inv, filter, batch, flags, use_ups ) ) {
                 tool.available = available_status::a_true;
             } else {
                 // Trying to track down why the crafting tests are failing?
                 // Uncomment the below to see the group of requirements that are lacking satisfaction
                 // Add a printf("\n") to the loop above this to separate different groups onto a separate line
                 // printf( "T: %s ", tool.type.str().c_str() );
                 tool.available = available_status::a_false;
             }
             has_tool_in_set = has_tool_in_set || tool.available == available_status::a_true;
         }
         if( !has_tool_in_set ) {
             retval = false;
         }
         if( UPS_charges_used != std::numeric_limits<int>::max() ) {
             total_UPS_charges_used += UPS_charges_used;
         }
     }
     if( total_UPS_charges_used > 0 &&
         total_UPS_charges_used > crafting_inv.charges_of( itype_UPS ) ) {
         return false;
     }
     return retval;
 }
References a_false, a_true, read_only_visitable::charges_of(), filter, itype_UPS, max(), and min().
Referenced by can_make_with_inventory().
has_same_requirements_as()
bool requirement_data::has_same_requirements_as (const requirement_data & that) const
Compares if two requirement_data are the same, but does not compare the requirement ids.
The order inside requirement vectors does not matter.
Definition at line 1455 of file requirements.cpp.
 {
     return sorted_equal( tools, that.tools ) && sorted_equal( qualities, that.qualities )
            && sorted_equal( components, that.components );
 }
References components, qualities, sorted_equal(), and tools.
Referenced by recipe::check_blueprint_requirements().
id()
const requirement_id& requirement_data::id () const inline
Definition at line 246 of file requirements.h.
{
             return id_;
         }
References id_.
Referenced by load_requirement(), requirements_map(), and save_requirement().
is_blacklisted()
bool requirement_data::is_blacklisted () const inline
Definition at line 260 of file requirements.h.
{
             return blacklisted;
         }
References blacklisted.
Referenced by recipe::is_blacklisted(), and recipe::will_be_blacklisted().
is_empty()
bool requirement_data::is_empty () const inline
empty requirements are not necessary null
Definition at line 256 of file requirements.h.
{
             return tools.empty() && components.empty() && qualities.empty();
         }
References components, qualities, and tools.
Referenced by Character::can_continue_craft(), disassemble_inventory_preset::disassemble_inventory_preset(), item::disassembly_info(), and vpart_info::is_repairable().
is_null()
bool requirement_data::is_null () const inline
null requirements are always empty (were never initialized)
Definition at line 251 of file requirements.h.
{
             return id_.is_null();
         }
References id_, and string_id< T >::is_null().
Referenced by load_requirement(), and save_requirement().
list_all()
std::string requirement_data::list_all () const
Returns a list of components/tools/qualities that are required, nicely formatted for popup window or similar.
Definition at line 538 of file requirements.cpp.
 {
     std::string buffer;
     buffer += print_all_objs( _( "These tools are required:" ), tools );
     buffer += print_all_objs( _( "These tools are required:" ), qualities );
     buffer += print_all_objs( _( "These components are required:" ), components );
     return buffer;
 }
References _, components, print_all_objs(), qualities, and tools.
Referenced by Character::can_continue_craft().
list_missing()
std::string requirement_data::list_missing () const
Returns a list of components/tools/qualities that are not available, nicely formatted for popup window or similar.
Definition at line 574 of file requirements.cpp.
 {
     std::string buffer;
     buffer += print_missing_objs( _( "These tools are missing:" ), tools );
     buffer += print_missing_objs( _( "These tools are missing:" ), qualities );
     buffer += print_missing_objs( _( "These components are missing:" ), components );
     return buffer;
 }
References _, components, print_missing_objs(), qualities, and tools.
Referenced by iexamine::autoclave_empty(), Character::can_continue_craft(), iexamine::cvdmachine(), Character::has_enough_anesth(), Character::has_installation_requirement(), Character::making_would_work(), iexamine::nanofab(), and veh_app_interact::remove().
load_obj_list()
template<typename T > void requirement_data::load_obj_list (const JsonArray & jsarr, std::vector< std::vector< T > > & objs) static private
Definition at line 298 of file requirements.cpp.
 {
     for( const JsonValue entry : jsarr ) {
         if( entry.test_array() ) {
             std::vector<T> choices;
             for( const JsonValue subentry : entry.get_array() ) {
                 choices.push_back( T() );
                 choices.back().load( subentry );
             }
             if( !choices.empty() ) {
                 objs.push_back( choices );
             }
         } else {
             // tool qualities don't normally use a list of alternatives
             // each quality is mandatory.
             objs.push_back( std::vector<T>( 1 ) );
             objs.back().back().load( entry );
         }
     }
 }
References JsonValue::get_array().
Referenced by load_requirement().
load_requirement()
void requirement_data::load_requirement (const JsonObject & jsobj, const requirement_id & id = requirement_id::NULL_ID(), bool check_extend = false) static
Load tools, qualities and components from the json object.
Assumes them to be in sub-objects.
Parameters
jsobj Object to load data from
id provide (or override) unique id for this instance
Definition at line 423 of file requirements.cpp.
 {
     requirement_data req;
     requirement_data ext;
     if( check_extend && jsobj.has_object( "extend" ) ) {
         JsonObject jext = jsobj.get_object( "extend" );
         if( jext.has_member( "components" ) ) {
             load_obj_list( jext.get_array( "components" ), ext.components );
         }
         if( jext.has_member( "qualities" ) ) {
             load_obj_list( jext.get_array( "qualities" ), ext.qualities );
         }
         if( jext.has_member( "tools" ) ) {
             load_obj_list( jext.get_array( "tools" ), ext.tools );
         }
     }
     if( ext.components.empty() || jsobj.has_member( "components" ) ) {
         load_obj_list( jsobj.get_array( "components" ), req.components );
     }
     if( ext.qualities.empty() || jsobj.has_member( "qualities" ) ) {
         load_obj_list( jsobj.get_array( "qualities" ), req.qualities );
     }
     if( ext.tools.empty() || jsobj.has_member( "tools" ) ) {
         load_obj_list( jsobj.get_array( "tools" ), req.tools );
     }
     if( !id.is_null() ) {
         req.id_ = id;
     } else if( jsobj.has_string( "id" ) ) {
         req.id_ = requirement_id( jsobj.get_string( "id" ) );
     } else {
         jsobj.throw_error( "id was not specified for requirement" );
     }
     save_requirement( req, string_id<requirement_data>::NULL_ID(), &ext );
 }
References components, JsonObject::get_array(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), id(), id_, is_null(), load_obj_list(), qualities, save_requirement(), JsonObject::throw_error(), and tools.
Referenced by DynamicDataLoader::initialize(), fault_fix::load(), recipe::load(), load_construction(), and parse_vp_reqs().
make_hash()
uint64_t requirement_data::make_hash () const
Definition at line 1491 of file requirements.cpp.
 {
     std::ostringstream stream;
     JsonOut json( stream );
     dump( json );
     std::hash<std::string> hasher;
     return hasher( stream.str() );
 }
References dump().
Referenced by generic_multi_activity_check_requirement().
operator*()
requirement_data requirement_data::operator* (unsigned scalar) const
Scales tool and component requirements leaving qualities unaffected.
Definition at line 319 of file requirements.cpp.
 {
     requirement_data res = *this;
     for( auto &group : res.components ) {
         for( item_comp &e : group ) {
             e.count = std::max( e.count * static_cast<int>( scalar ), -1 );
         }
     }
     for( auto &group : res.tools ) {
         for( tool_comp &e : group ) {
             e.count = std::max( e.count * static_cast<int>( scalar ), -1 );
         }
     }
     return res;
 }
References components, max(), and tools.
operator+() [1/3]
requirement_data requirement_data::operator+ (const requirement_data & rhs) const
Combines two sets of requirements.
Definition at line 362 of file requirements.cpp.
 {
     requirement_data res = *this;
     res.components.insert( res.components.end(), rhs.components.begin(), rhs.components.end() );
     res.tools.insert( res.tools.end(), rhs.tools.begin(), rhs.tools.end() );
     /*
     TODO: what is / isn't implemented:
     I will represent type by letter and level by number, always true: count = 1 && requirement = false
     A1 then has type A with level 1, (count = 1, requirement = false)
     X) [implemented ? "x" else " "] What's required -> How should it be displayed
     1) [x] A1 && A1 -> A1
     2) [x] A1 && A2 -> A2
     3) [x] (A1 || B1) && A1 -> A1
     4) [ ] A1 || A2 -> A1
     5) [ ] (A1 || B1) && A2 -> A2
     6) [ ] (A1 || B1 || C1) || (A1 || B1) -> A1 || B1 || C1
     Note: (1) covers most cases, (2) probably the rest, (3..6) probably isn't anywhere?
     It all takes O(n^2), but that's acceptable since n is very small.
     @Brambor
     */
     for( const std::vector<quality_requirement> &new_quality : rhs.qualities ) {
         bool add = true;
         for( std::vector<quality_requirement> &old_quality : res.qualities ) {
             if( a_satisfies_b( new_quality, old_quality ) ) {
                 add = false;
                 old_quality = new_quality;
                 break;
             } else if( a_satisfies_b( old_quality, new_quality ) ) {
                 add = false;
                 break;
             }
         }
         if( add ) {
             res.qualities.emplace_back( new_quality );
         }
     }
     // combined result is temporary which caller could store via @ref save_requirement
     res.id_ = requirement_id::NULL_ID();
     // TODO: combine other requirements
     // if either operand was blacklisted then their summation should also be
     res.blacklisted |= rhs.blacklisted;
     return res;
 }
References a_satisfies_b(), add, blacklisted, components, id_, string_id< requirement_data >::NULL_ID(), qualities, and tools.
operator+() [2/3]
requirement_data requirement_data::operator+ (const std::pair< const requirement_id, int > & rhs) const
Incorporate data from an id and integer.
This is helpful when building requirement_data objects from maps loaded from JSON
Definition at line 412 of file requirements.cpp.
 {
     return *this + *rhs.first * rhs.second;
 }
operator+() [3/3]
requirement_data requirement_data::operator+ (const std::pair< requirement_id, int > & rhs) const
Definition at line 418 of file requirements.cpp.
 {
     return *this + *rhs.first * rhs.second;
 }
print_all_objs()
template<typename T > std::string requirement_data::print_all_objs (const std::string & header, const std::vector< std::vector< T > > & objs) static private
Definition at line 516 of file requirements.cpp.
 {
     std::string buffer;
     for( const auto &list : objs ) {
         if( !buffer.empty() ) {
             buffer += std::string( "\n" ) + _( "and " );
         }
         std::vector<std::string> alternatives;
         std::transform( list.begin(), list.end(), std::back_inserter( alternatives ),
         []( const T & t ) {
             return t.to_string();
         } );
         std::sort( alternatives.begin(), alternatives.end(), localized_compare );
         buffer += string_join( alternatives, _( " or " ) );
     }
     if( buffer.empty() ) {
         return std::string();
     }
     return header + "\n" + buffer + "\n";
 }
References _, localized_compare, and string_join().
Referenced by list_all().
print_missing_objs()
template<typename T > std::string requirement_data::print_missing_objs (const std::string & header, const std::vector< std::vector< T > > & objs) static private
Definition at line 548 of file requirements.cpp.
 {
     std::string separator_and = _( "and " );
     std::string separator_or = _( " or " );
     std::string buffer;
     for( const auto &list : objs ) {
         if( any_marked_available( list ) ) {
             continue;
         }
         if( !buffer.empty() ) {
             buffer += std::string( "\n" ) + separator_and;
         }
         for( auto it = list.begin(); it != list.end(); ++it ) {
             if( it != list.begin() ) {
                 buffer += separator_or;
             }
             buffer += it->to_string();
         }
     }
     if( buffer.empty() ) {
         return std::string();
     }
     return header + "\n" + buffer + "\n";
 }
References _, and any_marked_available().
Referenced by list_missing().
replace_items()
void requirement_data::replace_items (const std::unordered_map< itype_id, itype_id > & replacements)
Replace tools or components using a provided replacement map.
Definition at line 1146 of file requirements.cpp.
 {
     apply_replacements( tools, replacements );
     apply_replacements( components, replacements );
 }
References apply_replacements(), components, and tools.
reset()
void requirement_data::reset () static
Clear all loaded requirements (invalidating any pointers)
Definition at line 727 of file requirements.cpp.
 {
     requirements_all.clear();
 }
References requirements_all.
Referenced by DynamicDataLoader::unload_data().
save_requirement()
void requirement_data::save_requirement (const requirement_data & req, const requirement_id & id = requirement_id::NULL_ID(), const requirement_data * extend = nullptr) static
Store requirement data for future lookup.
Parameters
req Data to save
id provide (or override) unique id for this instance
Definition at line 463 of file requirements.cpp.
 {
     requirement_data dup = req;
     if( !id.is_null() ) {
         dup.id_ = id;
     }
     if( requirements_all.count( dup.id_ ) == 0 ) {
         requirements_all[ dup.id_ ] = dup;
     }
     requirement_data &r = requirements_all[ dup.id_ ];
     if( !dup.components.empty() ) {
         r.components.clear();
         r.components.insert( r.components.end(), dup.components.begin(), dup.components.end() );
     }
     if( !dup.tools.empty() ) {
         r.tools.clear();
         r.tools.insert( r.tools.end(), dup.tools.begin(), dup.tools.end() );
     }
     if( !dup.qualities.empty() ) {
         r.qualities.clear();
         r.qualities.insert( r.qualities.end(), dup.qualities.begin(), dup.qualities.end() );
     }
     if( !!extend ) {
         for( unsigned i = 0; i < r.components.size() && i < extend->components.size(); i++ ) {
             r.components[i].insert( r.components[i].end(), extend->components[i].begin(),
                                     extend->components[i].end() );
         }
         for( unsigned i = 0; i < r.tools.size() && i < extend->tools.size(); i++ ) {
             r.tools[i].insert( r.tools[i].end(), extend->tools[i].begin(), extend->tools[i].end() );
         }
         for( unsigned i = 0; i < r.qualities.size() && i < extend->qualities.size(); i++ ) {
             r.qualities[i].insert( r.qualities[i].end(), extend->qualities[i].begin(),
                                    extend->qualities[i].end() );
         }
     }
 }
References components, id(), id_, is_null(), qualities, requirements_all, and tools.
Referenced by vpart_info::finalize(), finalize_constructions(), generic_multi_activity_check_requirement(), Character::load(), and load_requirement().
serialize()
void requirement_data::serialize (JsonOut & json) const
Serialize custom created requirement objects for fetch activities.
Definition at line 428 of file savegame_json.cpp.
 {
     json.start_object();
     if( !is_null() ) {
         json.member( "blacklisted", blacklisted );
         json.member( "req_comps_total", components );
         json.member( "tool_comps_total", tools );
         json.member( "quality_comps_total", qualities );
     }
     json.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
Friends And Related Function Documentation
vpart_info
friend class vpart_info friend
Definition at line 213 of file requirements.h.
Member Data Documentation
blacklisted
bool requirement_data::blacklisted = false private
Definition at line 393 of file requirements.h.
Referenced by blacklist_item(), is_blacklisted(), and operator+().
components
alter_item_comp_vector requirement_data::components private
Definition at line 222 of file requirements.h.
Referenced by blacklist_item(), can_make_with_inventory(), check_enough_materials(), consolidate(), dump(), vpart_info::finalize(), get_components(), get_folded_components_list(), has_same_requirements_as(), is_empty(), list_all(), list_missing(), load_requirement(), operator*(), operator+(), replace_items(), and save_requirement().
id_
requirement_id requirement_data::id_ = requirement_id::NULL_ID() private
Definition at line 391 of file requirements.h.
Referenced by id(), is_null(), load_requirement(), operator+(), and save_requirement().
qualities
alter_quali_req_vector requirement_data::qualities private
Definition at line 221 of file requirements.h.
Referenced by can_make_with_inventory(), check_enough_materials(), consolidate(), disassembly_requirements(), dump(), get_folded_tools_list(), get_qualities(), has_same_requirements_as(), is_empty(), list_all(), list_missing(), load_requirement(), operator+(), and save_requirement().
tools
alter_tool_comp_vector requirement_data::tools private
Definition at line 220 of file requirements.h.
Referenced by blacklist_item(), can_make_with_inventory(), check_enough_materials(), consolidate(), dump(), get_folded_tools_list(), get_tools(), has_same_requirements_as(), is_empty(), list_all(), list_missing(), load_requirement(), operator*(), operator+(), replace_items(), and save_requirement().
The documentation for this struct was generated from the following files:
src/requirements.h
src/requirements.cpp
src/savegame_json.cpp