Cataclysm DDA: tiny_bitset::and_mapper Struct Reference
tiny_bitset::and_mapper Struct Reference
Public Member Functions
void operator() (block_t &bits)
void operator() (block_t &partial, block_t mask)
Public Attributes
block_t value = ~(block_t(0))
Detailed Description
Definition at line 197 of file cata_bitset.h.
Member Function Documentation
operator()() [1/2]
void tiny_bitset::and_mapper::operator() (block_t & bits) inline
Definition at line 199 of file cata_bitset.h.
{
                 value &= bits;
             }
References tiny_bitset::bits(), and value.
operator()() [2/2]
void tiny_bitset::and_mapper::operator() (block_t & partial, block_t mask) inline
Definition at line 203 of file cata_bitset.h.
{
                 // Mask indicates bits in v which not 'part of the value'.
                 value &= ( partial | mask );
             }
References value.
Member Data Documentation
value
block_t tiny_bitset::and_mapper::value = ~(block_t(0))
Definition at line 198 of file cata_bitset.h.
Referenced by tiny_bitset::all(), and operator()().
The documentation for this struct was generated from the following file:
src/cata_bitset.h