Cataclysm DDA: rectangle< Point, > Struct Template Reference
rectangle< Point, > Struct Template Reference
#include <cuboid_rectangle.h>
Public Member Functions
constexpr rectangle ()=default
constexpr rectangle (const Point &P_MIN, const Point &P_MAX)
Public Attributes
Point p_min
Point p_max
Detailed Description
template<typename Point, decltype(std::declval< decltype(Point::dimension)>(), int()) = 0>
struct rectangle< Point, >
Definition at line 16 of file cuboid_rectangle.h.
Constructor & Destructor Documentation
rectangle() [1/2]
template<typename Point , decltype(std::declval< decltype(Point::dimension)>(), int()) = 0> constexpr rectangle< Point, >::rectangle () constexpr default
rectangle() [2/2]
template<typename Point , decltype(std::declval< decltype(Point::dimension)>(), int()) = 0> constexpr rectangle< Point, >::rectangle (const Point & P_MIN, const Point & P_MAX) inline constexpr
Definition at line 22 of file cuboid_rectangle.h.
                                                                   :
         p_min( P_MIN ), p_max( P_MAX ) {}
Member Data Documentation
p_max
template<typename Point , decltype(std::declval< decltype(Point::dimension)>(), int()) = 0> Point rectangle< Point, >::p_max
Definition at line 20 of file cuboid_rectangle.h.
Referenced by contains(), ui_adaptor::invalidate(), overlap(), half_open_rectangle< Point, >::overlaps(), inclusive_rectangle< Point, >::overlaps(), and map_memory::save().
p_min
template<typename Point , decltype(std::declval< decltype(Point::dimension)>(), int()) = 0> Point rectangle< Point, >::p_min
Definition at line 19 of file cuboid_rectangle.h.
Referenced by contains(), ui_adaptor::invalidate(), overlap(), half_open_rectangle< Point, >::overlaps(), inclusive_rectangle< Point, >::overlaps(), and map_memory::save().
The documentation for this struct was generated from the following file:
src/cuboid_rectangle.h