Cataclysm DDA: DebugFile Struct Reference
DebugFile Struct Reference
Public Member Functions
DebugFile ()
~DebugFile ()
void init (DebugOutput, const std::string &filename)
void deinit ()
std::ostream & get_file ()
Public Attributes
std::shared_ptr< std::ostream > file
std::string filename
Detailed Description
Definition at line 632 of file debug.cpp.
Constructor & Destructor Documentation
DebugFile()
DebugFile::DebugFile () default
~DebugFile()
DebugFile::~DebugFile ()
Definition at line 661 of file debug.cpp.
 {
     deinit();
 }
References deinit().
Member Function Documentation
deinit()
void DebugFile::deinit ()
Definition at line 666 of file debug.cpp.
 {
     if( file && file.get() != &std::cerr ) {
         output_repetitions( *file );
         *file << "\n";
         *file << get_time() << " : Log shutdown.\n";
         *file << "-----------------------------------------\n\n";
     }
     file.reset();
 }
References file, get_time(), and output_repetitions().
Referenced by deinitDebug(), and ~DebugFile().
get_file()
std::ostream & DebugFile::get_file ()
Definition at line 677 of file debug.cpp.
 {
     if( !file ) {
         file = std::make_shared<std::ostringstream>();
     }
     return *file;
 }
References file.
Referenced by DebugLog().
init()
void DebugFile::init (DebugOutput output_mode, const std::string & filename)
Definition at line 685 of file debug.cpp.
 {
     std::shared_ptr<std::ostringstream> str_buffer = std::dynamic_pointer_cast<std::ostringstream>
             ( file );
     switch( output_mode ) {
         case DebugOutput::std_err:
             file = std::shared_ptr<std::ostream>( &std::cerr, null_deleter() );
             break;
         case DebugOutput::file: {
             this->filename = filename;
             const std::string oldfile = filename + ".prev";
             bool rename_failed = false;
             struct stat buffer;
             if( stat( filename.c_str(), &buffer ) == 0 ) {
                 // Continue with the old log file if it's smaller than 1 MiB
                 if( buffer.st_size >= 1024 * 1024 ) {
                     rename_failed = !rename_file( filename, oldfile );
                 }
             }
             file = std::make_shared<std::ofstream>(
                        fs::u8path( filename ), std::ios::out | std::ios::app );
             *file << "\n\n-----------------------------------------\n";
             *file << get_time() << " : Starting log.";
             DebugLog( D_INFO, D_MAIN ) << "Cataclysm DDA version " << getVersionString();
             if( rename_failed ) {
                 DebugLog( D_ERROR, DC_ALL ) << "Moving the previous log file to "
                                             << oldfile << " failed.\n"
                                             << "Check the file permissions.  This "
                                             "program will continue to use the "
                                             "previous log file.";
             }
         }
         break;
         default:
             std::cerr << "Unexpected debug output mode " << static_cast<int>( output_mode )
                       << std::endl;
             return;
     }
     if( str_buffer && file ) {
         *file << str_buffer->str();
     }
 }
References D_ERROR, D_INFO, D_MAIN, DC_ALL, DebugLog(), file, file, filename, get_time(), getVersionString(), rename_file(), and std_err.
Referenced by setupDebug().
Member Data Documentation
file
std::shared_ptr<std::ostream> DebugFile::file
Definition at line 641 of file debug.cpp.
Referenced by deinit(), get_file(), and init().
filename
std::string DebugFile::filename
Definition at line 642 of file debug.cpp.
Referenced by init().
The documentation for this struct was generated from the following file:
src/debug.cpp