Cataclysm DDA: overmap_special_spawns Struct Reference
overmap_special_spawns Struct Reference
#include <omdata.h>
Public Member Functions
bool operator== (const overmap_special_spawns &rhs) const
void deserialize (const JsonValue &jsin)
Public Member Functions inherited from overmap_spawns
overmap_spawns ()
bool operator== (const overmap_spawns &rhs) const
Public Attributes
numeric_interval< int > radius
Public Attributes inherited from overmap_spawns
string_id< MonsterGroup > group
numeric_interval< int > population
Additional Inherited Members
Protected Member Functions inherited from overmap_spawns
void load (const JsonObject &jo)
Detailed Description
Definition at line 467 of file omdata.h.
Member Function Documentation
deserialize()
void overmap_special_spawns::deserialize (const JsonValue & jsin) inline
Definition at line 474 of file omdata.h.
{
         JsonObject jo = jsin.get_object();
         overmap_spawns::load( jo );
         jo.read( "radius", radius );
     }
References JsonValue::get_object(), overmap_spawns::load(), radius, and JsonObject::read().
operator==()
bool overmap_special_spawns::operator== (const overmap_special_spawns & rhs) const inline
Definition at line 470 of file omdata.h.
{
         return overmap_spawns::operator==( rhs ) && radius == rhs.radius;
     }
References overmap_spawns::operator==(), and radius.
Member Data Documentation
radius
numeric_interval<int> overmap_special_spawns::radius
Definition at line 468 of file omdata.h.
Referenced by deserialize(), operator==(), and overmap::place_special().
The documentation for this struct was generated from the following file:
src/omdata.h