Cataclysm DDA: weldrig_hack Struct Reference
weldrig_hack Struct Reference
Public Member Functions
weldrig_hack ()
bool init (const player_activity &act)
item & get_item ()
void clean_up ()
~weldrig_hack ()
Public Attributes
std::optional< vpart_reference > part
item pseudo
Detailed Description
Definition at line 2313 of file activity_handlers.cpp.
Constructor & Destructor Documentation
weldrig_hack()
weldrig_hack::weldrig_hack () inline
Definition at line 2317 of file activity_handlers.cpp.
 : part( std::nullopt ) { }
~weldrig_hack()
weldrig_hack::~weldrig_hack () inline
Definition at line 2375 of file activity_handlers.cpp.
                     {
         clean_up();
     }
References clean_up().
Member Function Documentation
clean_up()
void weldrig_hack::clean_up () inline
Definition at line 2366 of file activity_handlers.cpp.
                     {
         if( !part ) {
             return;
         }
         part->vehicle().charge_battery( pseudo.ammo_remaining(),
                                         false ); // return unused charges without cable loss
     }
References item::ammo_remaining(), part, and pseudo.
Referenced by ~weldrig_hack().
get_item()
item& weldrig_hack::get_item () inline
Definition at line 2335 of file activity_handlers.cpp.
                      {
         if( !part ) {
             // null item should be handled just fine
             return null_item_reference();
         }
         pseudo.set_flag( STATIC( flag_id( "PSEUDO" ) ) );
         item mag_mod( "pseudo_magazine_mod" );
         mag_mod.set_flag( STATIC( flag_id( "IRREMOVABLE" ) ) );
         if( !pseudo.put_in( mag_mod, pocket_type::MOD ).success() ) {
             debugmsg( "tool %s has no space for a %s, this is likely a bug",
                       pseudo.typeId().str(), mag_mod.type->nname( 1 ) );
         }
         itype_id mag_type;
         if( pseudo.can_link_up() ) {
             mag_type = itype_pseudo_magazine;
         } else {
             mag_type = pseudo.magazine_default();
         }
         item mag( mag_type );
         mag.clear_items(); // no initial ammo
         if( !pseudo.put_in( mag, pocket_type::MAGAZINE_WELL ).success() ) {
             debugmsg( "inserting %s into %s's MAGAZINE_WELL pocket failed",
                       mag.typeId().str(), pseudo.typeId().str() );
             return null_item_reference();
         }
         pseudo.ammo_set( itype_battery, part->vehicle().drain( itype_battery,
                          pseudo.ammo_capacity( ammo_battery ),
                          return_true< vehicle_part &>, false ) ); // no cable loss since all of this is virtual
         return pseudo;
     }
References ammo_battery, item::ammo_capacity(), item::ammo_set(), item::can_link_up(), item::clear_items(), debugmsg, flag_id, itype_battery, itype_pseudo_magazine, item::magazine_default(), MAGAZINE_WELL, MOD, itype::nname(), null_item_reference(), part, pseudo, item::put_in(), item::set_flag(), STATIC, string_id< T >::str(), ret_val_common::success(), item::type, and item::typeId().
Referenced by repair_item_finish().
init()
bool weldrig_hack::init (const player_activity & act) inline
Definition at line 2319 of file activity_handlers.cpp.
{
         if( act.coords.empty() || act.str_values.size() < 2 ) {
             return false;
         }
         const optional_vpart_position vp = get_map().veh_at( act.coords[0] );
         if( !vp ) {
             return false;
         }
         itype_id tool_id( act.get_str_value( 1, "" ) );
         pseudo = item( tool_id, calendar::turn );
         part = vp->part_with_tool( tool_id );
         return part.has_value();
     }
References act, get_map(), item, part, optional_vpart_position::part_with_tool(), pseudo, calendar::turn, and map::veh_at().
Referenced by repair_item_finish().
Member Data Documentation
part
std::optional<vpart_reference> weldrig_hack::part
Definition at line 2314 of file activity_handlers.cpp.
Referenced by clean_up(), get_item(), and init().
pseudo
item weldrig_hack::pseudo
Definition at line 2315 of file activity_handlers.cpp.
Referenced by clean_up(), get_item(), and init().
The documentation for this struct was generated from the following file:
src/activity_handlers.cpp