Cataclysm DDA: item_demographic_test_data Struct Reference
item_demographic_test_data Struct Reference
#include <test_data.h>
Public Member Functions
void deserialize (const JsonObject &jo)
Public Attributes
std::map< itype_id, int > item_weights
std::map< std::string, std::pair< int, std::map< itype_id, int > > > groups
std::set< std::string > tests
std::unordered_set< itype_id > ignored_items
Detailed Description
Definition at line 91 of file test_data.h.
Member Function Documentation
deserialize()
void item_demographic_test_data::deserialize (const JsonObject & jo)
Definition at line 86 of file test_data.cpp.
 {
     if( !jo.has_member( "type" ) ) {
         for( const JsonMember &member : jo ) {
             std::string name = member.name();
             itype_id itm_id = itype_id( name );
             int item_weight = member.get_int();
             item_weights[itm_id] = item_weight;
         }
         return;
     }
     std::string type;
     jo.read( "type", type );
     groups[type].first = jo.get_int( "weight" );
     JsonObject demo_list = jo.get_object( "items" );
     for( const JsonMember &member : demo_list ) {
         std::string name = member.name();
         itype_id itm_id = itype_id( name );
         int item_weight = member.get_int();
         item_weights[itm_id] = item_weight;
         groups[type].second[itm_id] = item_weight;
     }
 }
References JsonObject::get_int(), JsonObject::get_object(), groups, JsonObject::has_member(), item_weights, itype_id, member, om_direction::name(), JsonObject::read(), and type.
Member Data Documentation
groups
std::map<std::string, std::pair<int, std::map<itype_id, int> > > item_demographic_test_data::groups
Definition at line 93 of file test_data.h.
Referenced by deserialize().
ignored_items
std::unordered_set<itype_id> item_demographic_test_data::ignored_items
Definition at line 95 of file test_data.h.
Referenced by test_data::load().
item_weights
std::map<itype_id, int> item_demographic_test_data::item_weights
Definition at line 92 of file test_data.h.
Referenced by deserialize().
tests
std::set<std::string> item_demographic_test_data::tests
Definition at line 94 of file test_data.h.
Referenced by test_data::load().
The documentation for this struct was generated from the following files:
src/test_data.h
src/test_data.cpp