Cataclysm DDA: dynamic_line_t Struct Reference
dynamic_line_t Struct Reference
A dynamically generated line, spoken by the NPC.
#include <dialogue.h>
Public Member Functions
dynamic_line_t ()=default
dynamic_line_t (const translation &line)
dynamic_line_t (const JsonObject &jo)
dynamic_line_t (const JsonArray &ja)
std::string operator() (dialogue &d) const
Static Public Member Functions
static dynamic_line_t from_member (const JsonObject &jo, std::string_view member_name)
Private Attributes
std::function< std::string(dialogue &)> function
Detailed Description
A dynamically generated line, spoken by the NPC.
This struct only adds the constructors which will load the data from json into a lambda, stored in the std::function object. Invoking the function operator with a dialog reference (so the function can access the NPC) returns the actual line.
Definition at line 334 of file dialogue.h.
Constructor & Destructor Documentation
dynamic_line_t() [1/4]
dynamic_line_t::dynamic_line_t () default
Referenced by from_member().
dynamic_line_t() [2/4]
dynamic_line_t::dynamic_line_t (const translation & line) explicit
Definition at line 6830 of file npctalk.cpp.
 {
     function = [line]( const dialogue & ) {
         return line.translated();
     };
 }
References line.
dynamic_line_t() [3/4]
dynamic_line_t::dynamic_line_t (const JsonObject & jo) explicit
Definition at line 6837 of file npctalk.cpp.
 {
     if( jo.has_member( "concatenate" ) ) {
         std::vector<dynamic_line_t> lines;
         for( const JsonValue entry : jo.get_array( "concatenate" ) ) {
             if( entry.test_string() ) {
                 translation line;
                 entry.read( line );
                 lines.emplace_back( line );
             } else if( entry.test_array() ) {
                 lines.emplace_back( entry.get_array() );
             } else if( entry.test_object() ) {
                 JsonObject dl = entry.get_object();
                 if( dl.has_member( "str" ) ) {
                     dl.allow_omitted_members();
                     translation line;
                     entry.read( line );
                     lines.emplace_back( line );
                 } else {
                     lines.emplace_back( dl );
                 }
             } else {
                 entry.throw_error( "invalid format: must be string, array or object" );
             }
         }
         function = [lines]( dialogue & d ) {
             std::string all_lines;
             for( const dynamic_line_t &line : lines ) {
                 all_lines += line( d );
             }
             return all_lines;
         };
     } else if( jo.get_bool( "give_hint", false ) ) {
         function = [&]( const dialogue & ) {
             return get_hint();
         };
     } else if( jo.get_bool( "use_reason", false ) ) {
         function = [&]( const dialogue & d ) {
             std::string tmp = d.reason;
             d.reason.clear();
             return tmp;
         };
     } else if( jo.get_bool( "list_faction_camp_sites", false ) ) {
         function = [&]( const dialogue & ) {
             const auto &sites = recipe_group::get_recipes_by_id( "all_faction_base_types" );
             if( sites.empty() ) {
                 return std::string( _( "I can't think of a single place I can build a camp." ) );
             }
             std::string tmp = "I can start a new camp as a ";
             tmp += enumerate_as_string( sites.begin(), sites.end(),
             []( const std::pair<recipe_id, translation> &site ) {
                 return site.second.translated();
             },
             enumeration_conjunction::or_ );
             return tmp;
         };
     } else if( jo.has_string( "gendered_line" ) ) {
         std::string line;
         mandatory( jo, false, "gendered_line", line, text_style_check_reader() );
         if( !jo.has_array( "relevant_genders" ) ) {
             jo.throw_error(
                 R"(dynamic line with "gendered_line" must also have "relevant_genders")" );
         }
         std::vector<std::string> relevant_genders;
         for( const std::string gender : jo.get_array( "relevant_genders" ) ) {
             relevant_genders.push_back( gender );
             if( gender != "npc" && gender != "u" ) {
                 jo.throw_error( "Unexpected subject in relevant_genders; expected 'npc' or 'u'" );
             }
         }
         function = [line, relevant_genders]( const dialogue & d ) {
             return translate_gendered_line( line, relevant_genders, d );
         };
     } else {
         conditional_t dcondition;
         const dynamic_line_t yes = from_member( jo, "yes" );
         const dynamic_line_t no = from_member( jo, "no" );
         for( const std::string &sub_member : dialogue_data::simple_string_conds() ) {
             if( jo.has_bool( sub_member ) ) {
                 // This also marks the member as visited.
                 if( !jo.get_bool( sub_member ) ) {
                     jo.throw_error_at( sub_member, "value must be true" );
                 }
                 dcondition = conditional_t( sub_member );
                 function = [dcondition, yes, no]( dialogue & d ) {
                     return ( dcondition( d ) ? yes : no )( d );
                 };
                 return;
             } else if( jo.has_member( sub_member ) ) {
                 dcondition = conditional_t( sub_member );
                 const dynamic_line_t yes_member = from_member( jo, sub_member );
                 function = [dcondition, yes_member, no]( dialogue & d ) {
                     return ( dcondition( d ) ? yes_member : no )( d );
                 };
                 return;
             }
         }
         for( const std::string &sub_member : dialogue_data::complex_conds() ) {
             if( jo.has_member( sub_member ) ) {
                 dcondition = conditional_t( jo );
                 function = [dcondition, yes, no]( dialogue & d ) {
                     return ( dcondition( d ) ? yes : no )( d );
                 };
                 return;
             }
         }
         jo.throw_error( "dynamic line not supported" );
     }
 }
References _, JsonObject::allow_omitted_members(), dialogue_data::complex_conds(), enumerate_as_string(), from_member(), JsonObject::get_array(), JsonObject::get_bool(), get_hint(), JsonObject::get_object(), recipe_group::get_recipes_by_id(), JsonObject::has_array(), JsonObject::has_bool(), JsonObject::has_member(), JsonObject::has_string(), line, mandatory, no, or_, dialogue_data::simple_string_conds(), JsonObject::throw_error(), JsonObject::throw_error_at(), translate_gendered_line(), and yes.
dynamic_line_t() [4/4]
dynamic_line_t::dynamic_line_t (const JsonArray & ja) explicit
Definition at line 6947 of file npctalk.cpp.
 {
     std::vector<dynamic_line_t> lines;
     for( const JsonValue entry : ja ) {
         if( entry.test_string() ) {
             translation line;
             entry.read( line );
             lines.emplace_back( line );
         } else if( entry.test_array() ) {
             lines.emplace_back( entry.get_array() );
         } else if( entry.test_object() ) {
             JsonObject dl = entry.get_object();
             if( dl.has_member( "str" ) ) {
                 dl.allow_omitted_members();
                 translation line;
                 entry.read( line );
                 lines.emplace_back( line );
             } else {
                 lines.emplace_back( dl );
             }
         } else {
             entry.throw_error( "invalid format: must be string, array or object" );
         }
     }
     function = [lines]( dialogue & d ) {
         const dynamic_line_t &line = random_entry_ref( lines );
         return line( d );
     };
 }
References JsonObject::allow_omitted_members(), JsonObject::get_object(), JsonObject::has_member(), line, and random_entry_ref().
Member Function Documentation
from_member()
dynamic_line_t dynamic_line_t::from_member (const JsonObject & jo, std::string_view member_name) static
Definition at line 6806 of file npctalk.cpp.
 {
     if( jo.has_array( member_name ) ) {
         return dynamic_line_t( jo.get_array( member_name ) );
     } else if( jo.has_object( member_name ) ) {
         JsonObject dl = jo.get_object( member_name );
         if( dl.has_member( "str" ) ) {
             dl.allow_omitted_members();
             translation line;
             jo.read( member_name, line );
             return dynamic_line_t( line );
         } else {
             return dynamic_line_t( dl );
         }
     } else if( jo.has_string( member_name ) ) {
         translation line;
         jo.read( member_name, line );
         return dynamic_line_t( line );
     } else {
         return dynamic_line_t{};
     }
 }
References JsonObject::allow_omitted_members(), dynamic_line_t(), JsonObject::get_array(), JsonObject::get_object(), JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), line, and JsonObject::read().
Referenced by dynamic_line_t(), and json_talk_topic::load().
operator()()
std::string dynamic_line_t::operator() (dialogue & d) const inline
Definition at line 345 of file dialogue.h.
{
             if( !function ) {
                 return std::string{};
             }
             return function( d );
         }
Member Data Documentation
function
std::function<std::string(dialogue &)> dynamic_line_t::function private
Definition at line 336 of file dialogue.h.
The documentation for this struct was generated from the following files:
src/dialogue.h
src/npctalk.cpp