Cataclysm DDA: learning_proficiency Struct Reference
learning_proficiency Struct Reference
#include <proficiency.h>
Public Member Functions
learning_proficiency ()=default
learning_proficiency (const proficiency_id &id, const time_duration &practiced)
void serialize (JsonOut &jsout) const
void deserialize (const JsonObject &jo)
Public Attributes
proficiency_id id
time_duration practiced
float remainder = 0.f
Detailed Description
Definition at line 161 of file proficiency.h.
Constructor & Destructor Documentation
learning_proficiency() [1/2]
learning_proficiency::learning_proficiency () default
learning_proficiency() [2/2]
learning_proficiency::learning_proficiency (const proficiency_id & id, const time_duration & practiced) inline
Definition at line 170 of file proficiency.h.
                                                                                      : id( id ),
         practiced( practiced ) {}
Member Function Documentation
deserialize()
void learning_proficiency::deserialize (const JsonObject & jo)
Definition at line 569 of file proficiency.cpp.
 {
     jo.read( "id", id );
     jo.read( "practiced", practiced );
     jo.read( "remainder", remainder, 0.f );
 }
References practiced, JsonObject::read(), and remainder.
serialize()
void learning_proficiency::serialize (JsonOut & jsout) const
Definition at line 558 of file proficiency.cpp.
 {
     jsout.start_object();
     jsout.member( "id", id );
     jsout.member( "practiced", practiced );
     jsout.member( "remainder", remainder );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), practiced, remainder, and JsonOut::start_object().
Member Data Documentation
id
proficiency_id learning_proficiency::id
Definition at line 162 of file proficiency.h.
practiced
time_duration learning_proficiency::practiced
Definition at line 165 of file proficiency.h.
Referenced by deserialize(), proficiency_set::practice(), serialize(), and proficiency_set::set_time_practiced().
remainder
float learning_proficiency::remainder = 0.f
Definition at line 167 of file proficiency.h.
Referenced by deserialize(), proficiency_set::practice(), and serialize().
The documentation for this struct was generated from the following files:
src/proficiency.h
src/proficiency.cpp