Cataclysm DDA: weighted_list< W, T > Struct Template Reference
weighted_list< W, T > Struct Template Reference abstract
#include <weighted_list.h>
Public Member Functions
weighted_list ()
weighted_list (const weighted_list &)=default
weighted_list (weighted_list &&) noexcept=default
weighted_list & operator= (const weighted_list &)=default
weighted_list & operator= (weighted_list &&) noexcept=default
virtual ~weighted_list ()=default
T * add (const T &obj, const W &weight)
This will add a new object to the weighted list.
void remove (const T &obj)
T * add_or_replace (const T &obj, const W &weight)
This will check to see if the given object is already in the weighted list.
void apply (std::function< void(const T &)> func) const
This will call the given callback function once for every object in the weighted list.
void apply (std::function< void(T &)> func)
This will call the given callback function once for every object in the weighted list.
const T * pick (unsigned int randi) const
This will return a pointer to an object from the list randomly selected and biased by weight.
const T * pick () const
T * pick (unsigned int randi)
This will return a pointer to an object from the list randomly selected and biased by weight.
T * pick ()
void clear ()
This will remove all objects from the list.
W get_specific_weight (const T &obj) const
This will return the weight of a specific object.
W get_weight () const
This will return the sum of all the object's weights in the list.
bool is_valid () const
std::vector< weighted_object< W, T > >::iterator begin ()
std::vector< weighted_object< W, T > >::iterator end ()
std::vector< weighted_object< W, T > >::const_iterator begin () const
std::vector< weighted_object< W, T > >::const_iterator end () const
std::vector< weighted_object< W, T > >::iterator erase (typename std::vector< weighted_object< W, T > >::iterator first, typename std::vector< weighted_object< W, T > >::iterator last)
size_t size () const noexcept
bool empty () const noexcept
std::string to_debug_string () const
Protected Member Functions
virtual size_t pick_ent (unsigned int) const =0
virtual void invalidate_precalc ()
Protected Attributes
W total_weight
std::vector< weighted_object< W, T > > objects
Friends
bool operator== (const weighted_list &l, const weighted_list &r)
bool operator!= (const weighted_list &l, const weighted_list &r)
Detailed Description
template<typename W, typename T>
struct weighted_list< W, T >
Definition at line 25 of file weighted_list.h.
Constructor & Destructor Documentation
weighted_list() [1/3]
template<typename W , typename T > weighted_list< W, T >::weighted_list () inline
Definition at line 26 of file weighted_list.h.
 : total_weight( 0 ) { }
weighted_list() [2/3]
template<typename W , typename T > weighted_list< W, T >::weighted_list (const weighted_list< W, T > &) default
weighted_list() [3/3]
template<typename W , typename T > weighted_list< W, T >::weighted_list (weighted_list< W, T > &&) default noexcept
~weighted_list()
template<typename W , typename T > virtual weighted_list< W, T >::~weighted_list () virtual default
Member Function Documentation
add()
template<typename W , typename T > T* weighted_list< W, T >::add (const T & obj, const W & weight) inline
This will add a new object to the weighted list.
Returns a pointer to the added object, or NULL if weight was zero.
Parameters
obj The object that will be added to the list.
weight The weight of the object.
Definition at line 40 of file weighted_list.h.
{
             if( weight >= 0 ) {
                 objects.emplace_back( obj, weight );
                 total_weight += weight;
                 invalidate_precalc();
                 return &( objects[objects.size() - 1].obj );
             }
             return nullptr;
         }
References weighted_list< W, T >::invalidate_precalc(), weighted_list< W, T >::objects, and weighted_list< W, T >::total_weight.
Referenced by VehicleSpawn::add(), nested_mapgen::add(), Character::add_miss_reason(), weighted_list< W, T >::add_or_replace(), talk_function::companion_skill_trainer(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_weighted_list_eocs(), forest_biome_component::finalize(), Character::get_vitamin_weighted_categories(), grenade_helper(), relic_procgen_data::load(), load_transform_results(), load_weighted_list(), mapgen_forest(), MapExtras::mx_reed(), MapExtras::mx_roadworks(), targeting_graph< T, Wrapper >::select(), anatomy::select_blocking_part(), anatomy::select_body_part(), item::select_itype_variant(), and mapgen_basic_container::setup().
add_or_replace()
template<typename W , typename T > T* weighted_list< W, T >::add_or_replace (const T & obj, const W & weight) inline
This will check to see if the given object is already in the weighted list.
If it is, we update its weight with the new weight value. If it is not, we add it normally. Returns a pointer to the added or updated object, or NULL if weight was zero.
Parameters
obj The object that will be updated or added to the list.
weight The new weight of the object.
Definition at line 70 of file weighted_list.h.
{
             if( weight >= 0 ) {
                 invalidate_precalc();
                 for( auto &itr : objects ) {
                     if( itr.obj == obj ) {
                         total_weight += ( weight - itr.weight );
                         itr.weight = weight;
                         return &( itr.obj );
                     }
                 }
                 // if not found, add to end of list
                 return add( obj, weight );
             }
             return nullptr;
         }
References weighted_list< W, T >::add(), weighted_list< W, T >::invalidate_precalc(), weighted_list< W, T >::objects, and weighted_list< W, T >::total_weight.
Referenced by mapgen_basic_container::generate(), and Character::mutate().
apply() [1/2]
template<typename W , typename T > void weighted_list< W, T >::apply (std::function< void(const T &)> func) const inline
This will call the given callback function once for every object in the weighted list.
Parameters
func The callback function.
Definition at line 91 of file weighted_list.h.
{
             for( auto &itr : objects ) {
                 func( itr.obj );
             }
         }
References weighted_list< W, T >::objects.
apply() [2/2]
template<typename W , typename T > void weighted_list< W, T >::apply (std::function< void(T &)> func) inline
This will call the given callback function once for every object in the weighted list.
This is the non-const version.
Parameters
func The callback function.
Definition at line 102 of file weighted_list.h.
{
             for( auto &itr : objects ) {
                 func( itr.obj );
             }
         }
References weighted_list< W, T >::objects.
begin() [1/2]
template<typename W , typename T > std::vector<weighted_object<W, T> >::iterator weighted_list< W, T >::begin () inline
Definition at line 174 of file weighted_list.h.
{
             return objects.begin();
         }
References weighted_list< W, T >::objects.
begin() [2/2]
template<typename W , typename T > std::vector<weighted_object<W, T> >::const_iterator weighted_list< W, T >::begin () const inline
Definition at line 180 of file weighted_list.h.
{
             return objects.begin();
         }
References weighted_list< W, T >::objects.
clear()
template<typename W , typename T > void weighted_list< W, T >::clear () inline
This will remove all objects from the list.
Definition at line 144 of file weighted_list.h.
                      {
             total_weight = 0;
             objects.clear();
             invalidate_precalc();
         }
References weighted_list< W, T >::invalidate_precalc(), weighted_list< W, T >::objects, and weighted_list< W, T >::total_weight.
Referenced by Character::clear_miss_reasons().
empty()
template<typename W , typename T > bool weighted_list< W, T >::empty () const inline noexcept
Definition at line 195 of file weighted_list.h.
{
             return objects.empty();
         }
References weighted_list< W, T >::objects.
Referenced by check_region_settings(), talk_function::companion_skill_trainer(), and jmapgen_nested::has_vehicle_collision().
end() [1/2]
template<typename W , typename T > std::vector<weighted_object<W, T> >::iterator weighted_list< W, T >::end () inline
Definition at line 177 of file weighted_list.h.
{
             return objects.end();
         }
References weighted_list< W, T >::objects.
end() [2/2]
template<typename W , typename T > std::vector<weighted_object<W, T> >::const_iterator weighted_list< W, T >::end () const inline
Definition at line 183 of file weighted_list.h.
{
             return objects.end();
         }
References weighted_list< W, T >::objects.
erase()
template<typename W , typename T > std::vector<weighted_object<W, T> >::iterator weighted_list< W, T >::erase (typename std::vector< weighted_object< W, T > >::iterator first, typename std::vector< weighted_object< W, T > >::iterator last) inline
Definition at line 186 of file weighted_list.h.
{
             invalidate_precalc();
             return objects.erase( first, last );
         }
References weighted_list< W, T >::invalidate_precalc(), last, and weighted_list< W, T >::objects.
get_specific_weight()
template<typename W , typename T > W weighted_list< W, T >::get_specific_weight (const T & obj) const inline
This will return the weight of a specific object.
If the object is not in the weighted list it will return 0.
Definition at line 154 of file weighted_list.h.
{
             for( auto &itr : objects ) {
                 if( itr.obj == obj ) {
                     return itr.weight;
                 }
             }
             return 0;
         }
References weighted_list< W, T >::objects.
get_weight()
template<typename W , typename T > W weighted_list< W, T >::get_weight () const inline
This will return the sum of all the object's weights in the list.
Definition at line 166 of file weighted_list.h.
{
             return total_weight;
         }
References weighted_list< W, T >::total_weight.
Referenced by eff_fun_sleep(), mapgen_basic_container::generate(), weighted_list< W, T >::is_valid(), and Character::mutate().
invalidate_precalc()
template<typename W , typename T > virtual void weighted_list< W, T >::invalidate_precalc () inline protected virtual
Reimplemented in weighted_int_list< T >, weighted_int_list< std::vector< int > >, weighted_int_list< relic_procgen_data::enchantment_active >, weighted_int_list< ter_furn_id >, weighted_int_list< std::string >, weighted_int_list< string_id >, weighted_int_list< relic_procgen_data::enchantment_value_passive< float > >, weighted_int_list< mapgen_value< string_id > >, weighted_int_list< type >, weighted_int_list< std::shared_ptr< mapgen_function_json_nested > >, weighted_int_list< StringId >, weighted_int_list< relic_procgen_data::enchantment_value_passive< int > >, weighted_int_list< int_id >, weighted_int_list< std::shared_ptr< mapgen_function > >, and weighted_int_list< relic_charge_template >.
Definition at line 222 of file weighted_list.h.
 {}
Referenced by weighted_list< W, T >::add(), weighted_list< W, T >::add_or_replace(), weighted_list< W, T >::clear(), weighted_list< W, T >::erase(), and weighted_list< W, T >::remove().
is_valid()
template<typename W , typename T > bool weighted_list< W, T >::is_valid () const inline
Definition at line 170 of file weighted_list.h.
{
             return get_weight() > 0;
         }
References weighted_list< W, T >::get_weight().
Referenced by check_region_settings().
operator=() [1/2]
template<typename W , typename T > weighted_list& weighted_list< W, T >::operator= (const weighted_list< W, T > &) default
operator=() [2/2]
template<typename W , typename T > weighted_list& weighted_list< W, T >::operator= (weighted_list< W, T > &&) default noexcept
pick() [1/4]
template<typename W , typename T > T* weighted_list< W, T >::pick () inline
Definition at line 137 of file weighted_list.h.
                   {
             return pick( rng_bits() );
         }
References weighted_list< W, T >::pick(), and rng_bits().
pick() [2/4]
template<typename W , typename T > const T* weighted_list< W, T >::pick () const inline
Definition at line 120 of file weighted_list.h.
{
             return pick( rng_bits() );
         }
References rng_bits().
Referenced by weighted_list< W, T >::pick().
pick() [3/4]
template<typename W , typename T > T* weighted_list< W, T >::pick (unsigned int randi) inline
This will return a pointer to an object from the list randomly selected and biased by weight.
If the weighted list is empty or all items in it have a weight of zero, it will return a NULL pointer. This is the non-const version so that the returned result may be modified.
Definition at line 130 of file weighted_list.h.
{
             if( total_weight > 0 ) {
                 return &( objects[pick_ent( randi )].obj );
             } else {
                 return nullptr;
             }
         }
References weighted_list< W, T >::objects, weighted_list< W, T >::pick_ent(), and weighted_list< W, T >::total_weight.
pick() [4/4]
template<typename W , typename T > const T* weighted_list< W, T >::pick (unsigned int randi) const inline
This will return a pointer to an object from the list randomly selected and biased by weight.
If the weighted list is empty or all items in it have a weight of zero, it will return a NULL pointer.
Definition at line 113 of file weighted_list.h.
{
             if( total_weight > 0 ) {
                 return &( objects[pick_ent( randi )].obj );
             } else {
                 return nullptr;
             }
         }
References weighted_list< W, T >::objects, weighted_list< W, T >::pick_ent(), and weighted_list< W, T >::total_weight.
Referenced by VehicleSpawn::apply(), talk_function::companion_skill_trainer(), map::draw_square_ter(), eff_fun_sleep(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_weighted_list_eocs(), relic_procgen_data::generate(), mapgen_basic_container::generate(), mapgen_value< Id >::distribution_source::get(), Character::get_miss_reason(), grenade_helper(), mapgen_forest(), Character::mutate(), MapExtras::mx_reed(), targeting_graph< T, Wrapper >::select(), anatomy::select_blocking_part(), anatomy::select_body_part(), and item::select_itype_variant().
pick_ent()
template<typename W , typename T > virtual size_t weighted_list< W, T >::pick_ent (unsigned int) const protected pure virtual
Implemented in weighted_float_list< T >, weighted_float_list< shared_ptr_fast< VehicleFunction > >, weighted_float_list< string_id >, weighted_int_list< T >, weighted_int_list< std::vector< int > >, weighted_int_list< relic_procgen_data::enchantment_active >, weighted_int_list< ter_furn_id >, weighted_int_list< std::string >, weighted_int_list< string_id >, weighted_int_list< relic_procgen_data::enchantment_value_passive< float > >, weighted_int_list< mapgen_value< string_id > >, weighted_int_list< type >, weighted_int_list< std::shared_ptr< mapgen_function_json_nested > >, weighted_int_list< StringId >, weighted_int_list< relic_procgen_data::enchantment_value_passive< int > >, weighted_int_list< int_id >, weighted_int_list< std::shared_ptr< mapgen_function > >, and weighted_int_list< relic_charge_template >.
Referenced by weighted_list< W, T >::pick().
remove()
template<typename W , typename T > void weighted_list< W, T >::remove (const T & obj) inline
Definition at line 50 of file weighted_list.h.
{
             auto itr_end = std::remove_if( objects.begin(),
             objects.end(), [&obj]( typename decltype( objects )::value_type const & itr ) {
                 return itr.obj == obj;
             } );
             for( decltype( itr_end ) removed = itr_end; removed != objects.end(); ++removed ) {
                 total_weight -= removed->weight;
             }
             objects.erase( itr_end, objects.end() );
             invalidate_precalc();
         }
References weighted_list< W, T >::invalidate_precalc(), weighted_list< W, T >::objects, and weighted_list< W, T >::total_weight.
Referenced by mapgen_basic_container::generate().
size()
template<typename W , typename T > size_t weighted_list< W, T >::size () const inline noexcept
Definition at line 192 of file weighted_list.h.
{
             return objects.size();
         }
References weighted_list< W, T >::objects.
to_debug_string()
template<typename W , typename T > std::string weighted_list< W, T >::to_debug_string () const inline
Definition at line 199 of file weighted_list.h.
{
             std::ostringstream os;
             os << "[ ";
             for( const weighted_object<W, T> &o : objects ) {
                 os << o.obj << ":" << o.weight << ", ";
             }
             os << "]";
             return os.str();
         }
References weighted_list< W, T >::objects.
Referenced by mapgen_value< Id >::distribution_source::check_consistent_with().
Friends And Related Function Documentation
operator!=
template<typename W , typename T > bool operator!= (const weighted_list< W, T > & l, const weighted_list< W, T > & r) friend
Definition at line 213 of file weighted_list.h.
{
             return !( l == r );
         }
operator==
template<typename W , typename T > bool operator== (const weighted_list< W, T > & l, const weighted_list< W, T > & r) friend
Definition at line 209 of file weighted_list.h.
{
             return l.objects == r.objects;
         }
Member Data Documentation
objects
template<typename W , typename T > std::vector<weighted_object<W, T> > weighted_list< W, T >::objects protected
Definition at line 219 of file weighted_list.h.
Referenced by weighted_list< W, T >::add(), weighted_list< W, T >::add_or_replace(), weighted_list< W, T >::apply(), weighted_list< W, T >::begin(), weighted_list< W, T >::clear(), weighted_list< W, T >::empty(), weighted_list< W, T >::end(), weighted_list< W, T >::erase(), weighted_list< W, T >::get_specific_weight(), weighted_list< W, T >::pick(), weighted_list< W, T >::remove(), weighted_list< W, T >::size(), and weighted_list< W, T >::to_debug_string().
total_weight
template<typename W , typename T > W weighted_list< W, T >::total_weight protected
Definition at line 218 of file weighted_list.h.
Referenced by weighted_list< W, T >::add(), weighted_list< W, T >::add_or_replace(), weighted_list< W, T >::clear(), weighted_list< W, T >::get_weight(), weighted_list< W, T >::pick(), and weighted_list< W, T >::remove().
The documentation for this struct was generated from the following file:
src/weighted_list.h