Cataclysm DDA: jmath_func Struct Reference
jmath_func Struct Reference
#include <math_parser_jmath.h>
Public Member Functions
double eval (dialogue &d) const
double eval (dialogue &d, std::vector< double > const &params) const
void load (const JsonObject &jo, std::string_view src)
Static Public Member Functions
static void load_func (const JsonObject &jo, std::string const &src)
static void finalize ()
static void reset ()
static const std::vector< jmath_func > & get_all ()
Public Attributes
jmath_func_id id
std::vector< std::pair< jmath_func_id, mod_id > > src
bool was_loaded = false
int num_params {}
std::string _str
math_exp _exp
Detailed Description
Definition at line 15 of file math_parser_jmath.h.
Member Function Documentation
eval() [1/2]
double jmath_func::eval (dialogue & d) const
Definition at line 72 of file math_parser_jmath.cpp.
 {
     return _exp.eval( d );
 }
References _exp, and math_exp::eval().
Referenced by eval().
eval() [2/2]
double jmath_func::eval (dialogue & d, std::vector< double > const & params) const
Definition at line 77 of file math_parser_jmath.cpp.
 {
     dialogue d_next( d );
     for( std::vector<double>::size_type i = 0; i < params.size(); i++ ) {
         write_var_value( var_type::context, "npctalk_var_" + std::to_string( i ), &d_next, params[i] );
     }
     return eval( d_next );
 }
References context, eval(), to_string(), and write_var_value().
finalize()
void jmath_func::finalize () static
Definition at line 64 of file math_parser_jmath.cpp.
 {
     for( jmath_func const &jmf : jmath_func::get_all() ) {
         jmf._exp.parse( jmf._str );
         jmf._str.clear();
     }
 }
References get_all().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
std::vector< jmath_func > const & jmath_func::get_all () static
Definition at line 40 of file math_parser_jmath.cpp.
 {
     return get_all_jmath_func().get_all();
 }
References anonymous_namespace{math_parser_jmath.cpp}::get_all_jmath_func().
Referenced by finalize().
load()
void jmath_func::load (const JsonObject & jo, std::string_view src)
Definition at line 50 of file math_parser_jmath.cpp.
 {
     optional( jo, was_loaded, "num_args", num_params );
     optional( jo, was_loaded, "return", _str );
     for( auto const &iter : get_all_diag_eval_funcs() ) {
         if( std::string const idstr = id.str(); iter.first == idstr ) {
             jo.throw_error( string_format(
                                 R"(jmath function "%s" shadows a built-in function with the same name.  You must rename it.)",
                                 idstr ) );
         }
     }
 }
References _str, get_all_diag_eval_funcs(), num_params, optional(), string_format(), JsonObject::throw_error(), and was_loaded.
load_func()
void jmath_func::load_func (const JsonObject & jo, std::string const & src) static
Definition at line 45 of file math_parser_jmath.cpp.
 {
     get_all_jmath_func().load( jo, src );
 }
References anonymous_namespace{math_parser_jmath.cpp}::get_all_jmath_func(), and src.
Referenced by DynamicDataLoader::initialize().
reset()
void jmath_func::reset () static
Definition at line 35 of file math_parser_jmath.cpp.
 {
     get_all_jmath_func().reset();
 }
References anonymous_namespace{math_parser_jmath.cpp}::get_all_jmath_func().
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
_exp
math_exp jmath_func::_exp mutable
Definition at line 31 of file math_parser_jmath.h.
Referenced by eval().
_str
std::string jmath_func::_str mutable
Definition at line 30 of file math_parser_jmath.h.
Referenced by load().
id
jmath_func_id jmath_func::id
Definition at line 16 of file math_parser_jmath.h.
num_params
int jmath_func::num_params {}
Definition at line 19 of file math_parser_jmath.h.
Referenced by load().
src
std::vector<std::pair<jmath_func_id, mod_id> > jmath_func::src
Definition at line 17 of file math_parser_jmath.h.
Referenced by load_func().
was_loaded
bool jmath_func::was_loaded = false
Definition at line 18 of file math_parser_jmath.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/math_parser_jmath.h
src/math_parser_jmath.cpp