Cataclysm DDA: vehicle_part Struct Reference
vehicle_part Struct Reference
Structure, describing vehicle part (i.e., wheel, seat)
#include <vehicle.h>
Classes
struct carried_part_data
Public Member Functions
vehicle_part ()
vehicle_part (const vpart_id &type, item &&base)
vehicle_part (const vpart_id &type, item &&base, std::vector< item > &installed_with)
const item & get_base () const
std::vector< item > get_salvageable () const
void set_base (item &&new_base)
bool has_flag (const vp_flag flag) const noexcept
void set_flag (const vp_flag flag) noexcept
void remove_flag (const vp_flag flag) noexcept
std::string name (bool with_prefix=true) const
Translated name of a part inclusive of any current status effects with_prefix as true indicates the durability symbol should be prepended.
itype_id ammo_current () const
Specific type of fuel, charges or ammunition currently contained by a part.
int ammo_capacity (const ammotype &ammo) const
Maximum amount of fuel, charges or ammunition that can be contained by a part.
int item_capacity (const itype_id &stuffing_id) const
Maximum amount of fuel, charges or ammunition that can be contained by a part.
int ammo_remaining () const
Amount of fuel, charges or ammunition currently contained by a part.
int remaining_ammo_capacity () const
itype_id fuel_current () const
Type of fuel used by an engine.
bool fuel_set (const itype_id &fuel)
Set an engine to use a different type of fuel.
int ammo_set (const itype_id &ammo, int qty=-1)
Set fuel, charges or ammunition for this part removing any existing ammo.
void ammo_unset ()
Remove all fuel, charges or ammunition (if any) from this part.
int ammo_consume (int qty, const tripoint &pos)
Consume fuel, charges or ammunition (if available)
units::energy consume_energy (const itype_id &ftype, units::energy wanted_energy)
Consume fuel by energy content.
bool can_reload (const item &obj=item()) const
void process_contents (map &here, const tripoint &pos, bool e_heater)
If this part is capable of wholly containing something, process the items in there.
bool fill_with (item &liquid, int qty=INT_MAX)
Try adding.
const std::set< fault_id > & faults () const
Current faults affecting this part (if any)
bool has_fault_flag (const std::string &searched_flag) const
Does this vehicle part have a fault with this flag.
std::set< fault_id > faults_potential () const
Faults which could potentially occur with this part (if any)
bool fault_set (const fault_id &f)
Try to set fault returning false if specified fault cannot occur with this item.
npc * crew () const
Get NPC currently assigned to this part (seat, turret etc)?
bool set_crew (const npc &who)
Set crew member for this part (seat, turret etc) who must be a player ally)
void unset_crew ()
Remove any currently assigned crew member for this part.
void reset_target (const tripoint &pos)
Reset the target for this part.
Public Attributes
friend vehicle
friend item_location
std::stack< carried_part_data > carried_stack
turret_cpu cpu
Friends
class veh_interact
class vehicle_cursor
class vehicle_stack
class turret_data
Part capabilities
A part can provide zero or more capabilities.
Some capabilities are mutually exclusive, for example a part cannot be both a fuel tank and battery
point mount
mount point: x is on the forward/backward axis, y is on the left/right axis
std::array< tripoint, 2 > precalc = { { tripoint(-1, -1, 0), tripoint(-1, -1, 0) } }
mount translated to face.dir [0] and turn_dir [1]
int blood = 0
how much blood covers part (in turns).
bool inside = false
if tile provides cover.
bool removed = false
true if this part is removed.
bool enabled = true
character_id passenger_id
ID of player passenger.
bool open = false
door is open
bool locked = false
door is locked
units::angle direction = 0_degrees
direction the part is facing
std::pair< tripoint, tripoint > target = { tripoint_min, tripoint_min }
Coordinates for some kind of target; jumper cables and turrets use this Two coordinate pairs are stored: actual target point, and target vehicle center.
std::string variant
If it's a part with variants, which variant it is.
time_point last_disconnected = calendar::before_time_starts
bool is_fake = false
bool is_active_fake = false
int fake_part_to = -1
int fake_protrusion_on = -1
bool has_fake = false
int fake_part_at = -1
const vpart_info * info_
uint32_t flags = 0
item base
std::vector< item > tools
cata::colony< item > items
std::vector< item > salvageable
itype_id ammo_pref = itype_id::NULL_ID()
Preferred ammo type when multiple are available.
character_id crew_id
What NPC (if any) is assigned to this part (seat, turret etc)?
bool is_engine () const
Can this part provide power or propulsion?
bool is_light () const
Is this any type of vehicle light?
bool is_fuel_store (bool skip_broke=true) const
Can this part store fuel of any type @skip_broke exclude broken parts.
bool is_tank () const
Can this part contain liquid fuels?
bool contains_liquid () const
Does this part currently contain some liquid?
bool is_battery () const
Can this part store electrical charge?
bool is_reactor () const
Is this part a reactor?
bool is_leaking () const
is this part currently unable to retain to fluid/charge? this doesn't take into account whether or not the part has any contents remaining to leak
bool is_turret () const
Can this part function as a turret?
bool is_seat () const
Can a player or NPC use this part as a seat?
std::string carried_name () const
int hp () const
current part health with range [0,durability]
int damage () const
Current part damage in same units as item::damage.
int degradation () const
Current part degradation of part base.
int max_damage () const
max damage of part base
int damage_level () const
damage level of part base
bool is_repairable () const
double damage_percent () const
Current part damage as a percentage of maximum, with 0.0 being perfect condition.
double health_percent () const
Current part health as a percentage of maximum, with 1.0 being perfect condition.
double floating_leak_threshold () const
The leaking thresold for the boat hull.
bool is_broken () const
parts are considered broken at zero health
bool is_cleaner_on () const
Is this an enabled autoclave, dishwasher, or washing machine?
bool is_unavailable (bool carried=true) const
parts are unavailable if broken or if carried is true, if they have the CARRIED flag
bool is_available (bool carried=true) const
parts are available if they aren't unavailable
npc & get_targeting_npc (vehicle &veh)
const vpart_info & info () const
Get part definition common to all parts of this type.
void serialize (JsonOut &json) const
void deserialize (const JsonObject &data)
item_group::ItemList pieces_for_broken_part () const
Returns an ItemList of the pieces that should arise from breaking this part.
bool is_real_or_active_fake () const
Detailed Description
Structure, describing vehicle part (i.e., wheel, seat)
Definition at line 254 of file vehicle.h.
Constructor & Destructor Documentation
vehicle_part() [1/3]
vehicle_part::vehicle_part ()
Definition at line 44 of file vehicle_part.cpp.
     : vehicle_part( vpart_id::NULL_ID(), item( vpart_id::NULL_ID()->base_item ) ) { }
vehicle_part() [2/3]
vehicle_part::vehicle_part (const vpart_id & type, item && base)
Definition at line 47 of file vehicle_part.cpp.
     : info_( &type.obj() )
 {
     set_base( std::move( base ) );
     variant = info_->variant_default;
 }
References base, info_, set_base(), variant, and vpart_info::variant_default.
vehicle_part() [3/3]
vehicle_part::vehicle_part (const vpart_id & type, item && base, std::vector< item > & installed_with)
Definition at line 54 of file vehicle_part.cpp.
     : info_( &type.obj() )
 {
     set_base( std::move( base ) );
     variant = info_->variant_default;
     for( item &it : installed_with ) {
         if( !it.has_flag( flag_UNRECOVERABLE ) ) {
             salvageable.push_back( it );
         }
     }
 }
References base, flag_UNRECOVERABLE, info_, salvageable, set_base(), variant, and vpart_info::variant_default.
Member Function Documentation
ammo_capacity()
int vehicle_part::ammo_capacity (const ammotype & ammo) const
Maximum amount of fuel, charges or ammunition that can be contained by a part.
Definition at line 261 of file vehicle_part.cpp.
 {
     if( is_tank() ) {
         const itype *ammo_type = item::find_type( ammo->default_ammotype() );
         const int max_charges_volume = ammo_type->charges_per_volume( base.get_total_capacity() );
         const int max_charges_weight = ammo_type->weight == 0_gram ? INT_MAX :
                                        static_cast<int>( base.get_total_weight_capacity() / ammo_type->weight );
         return std::min( max_charges_volume, max_charges_weight );
     }
     if( is_fuel_store( false ) || is_turret() ) {
         return base.ammo_capacity( ammo );
     }
     return 0;
 }
References item::ammo_capacity(), base, itype::charges_per_volume(), ammunition_type::default_ammotype(), item::find_type(), item::get_total_capacity(), item::get_total_weight_capacity(), is_fuel_store(), is_tank(), is_turret(), min(), and itype::weight.
Referenced by ammo_set(), veh_interact::calc_overview(), can_reload(), vehicle::charge_battery(), veh_interact::complete_vehicle(), vehicle::discharge_battery(), distribute_charge_evenly(), fill_with(), vehicles::finalize_prototypes(), vehicle::fuel_capacity(), item_capacity(), vehicle::print_part_list(), and weighted_power_loss().
ammo_consume()
int vehicle_part::ammo_consume (int qty, const tripoint & pos)
Consume fuel, charges or ammunition (if available)
Parameters
qty maximum amount of ammo that should be consumed
pos current global location of part from which ammo is being consumed
Returns
amount consumed which will be between 0 and specified qty
Definition at line 363 of file vehicle_part.cpp.
 {
     if( is_tank() && !base.empty() ) {
         const int res = std::min( ammo_remaining(), qty );
         item &liquid = base.legacy_front();
         liquid.charges -= res;
         if( liquid.charges == 0 ) {
             base.clear_items();
         }
         return res;
     }
     return base.ammo_consume( qty, pos, nullptr );
 }
References item::ammo_consume(), ammo_remaining(), base, item::charges, item::clear_items(), item::empty(), is_tank(), item::legacy_front(), min(), and math_opers::pos().
Referenced by vehicle::drain(), vehicle::leak_fuel(), vehicle::power_parts(), and vehicle::slow_leak().
ammo_current()
itype_id vehicle_part::ammo_current () const
Specific type of fuel, charges or ammunition currently contained by a part.
Definition at line 244 of file vehicle_part.cpp.
 {
     if( is_battery() ) {
         return itype_battery;
     }
     if( is_tank() && !base.empty() ) {
         return base.legacy_front().typeId();
     }
     if( is_fuel_store( false ) || is_turret() ) {
         return base.ammo_current() != itype_id::NULL_ID() ? base.ammo_current() : base.ammo_default();
     }
     return itype_id::NULL_ID();
 }
References item::ammo_current(), item::ammo_default(), base, item::empty(), is_battery(), is_fuel_store(), is_tank(), is_turret(), itype_battery, item::legacy_front(), string_id< itype >::NULL_ID(), and item::typeId().
Referenced by vehicle::basic_consumption(), veh_interact::calc_overview(), can_reload(), vehicle::drain(), fill_with(), vehicle::fuel_left(), vehicle::get_printable_fuel_types(), vehicle::init_state(), vehicle::is_engine_type(), vehicle::leak_fuel(), vehicle::print_part_list(), vehicle_prototype::save_vehicle_as_prototype(), and vehicle::slow_leak().
ammo_remaining()
int vehicle_part::ammo_remaining () const
Amount of fuel, charges or ammunition currently contained by a part.
Definition at line 298 of file vehicle_part.cpp.
 {
     if( is_tank() ) {
         return base.empty() ? 0 : base.legacy_front().charges;
     }
     if( is_fuel_store( false ) || is_turret() ) {
         return base.ammo_remaining();
     }
     return 0;
 }
References item::ammo_remaining(), base, item::charges, item::empty(), is_fuel_store(), is_tank(), is_turret(), and item::legacy_front().
Referenced by vehicle::active_reactor_epower(), ammo_consume(), vehicle::battery_left(), veh_interact::calc_overview(), can_reload(), vehicle::charge_battery(), veh_interact::complete_vehicle(), vehicle::discharge_battery(), distribute_charge_evenly(), vehicle::drain(), vehicle::explode_fuel(), activity_handlers::fill_liquid_do_turn(), fill_with(), vehicle::fuel_left(), vehicle::leak_fuel(), vehicle::power_parts(), vehicle::print_part_list(), vehicle_prototype::save_vehicle_as_prototype(), and vehicle::slow_leak().
ammo_set()
int vehicle_part::ammo_set (const itype_id & ammo, int qty = -1)
Set fuel, charges or ammunition for this part removing any existing ammo.
Parameters
ammo specific type of ammo (must be compatible with vehicle part)
qty maximum ammo (capped by part capacity) or negative to fill to capacity
Returns
amount of ammo actually set or negative on failure
Definition at line 315 of file vehicle_part.cpp.
 {
     // We often check if ammo is set to see if tank is empty, if qty == 0 don't set ammo
     if( is_tank() && qty != 0 ) {
         const itype *ammo_itype = item::find_type( ammo );
         if( ammo_itype && ammo_itype->phase >= phase_id::LIQUID ) {
             base.clear_items();
             const int limit = item_capacity( ammo );
             // assuming "ammo" isn't really going into a magazine as this is a vehicle part
             const int amount = qty > 0 ? std::min( qty, limit ) : limit;
             base.put_in( item( ammo, calendar::turn, amount ), pocket_type::CONTAINER );
             return amount;
         }
     }
     if( is_turret() ) {
         if( base.is_magazine() ) {
             return base.ammo_set( ammo, qty ).ammo_remaining();
         }
         itype_id mag_type = base.magazine_default();
         if( mag_type ) {
             item mag( mag_type );
             mag.ammo_set( ammo, qty );
             base.put_in( mag, pocket_type::MAGAZINE_WELL );
             return base.ammo_remaining();
         }
     }
     if( is_fuel_store() ) {
         const itype *ammo_itype = item::find_type( ammo );
         if( ammo_itype && ammo_itype->ammo ) {
             base.ammo_set( ammo, qty >= 0 ? qty : ammo_capacity( ammo_itype->ammo->type ) );
             return base.ammo_remaining();
         }
     }
     return -1;
 }
References itype::ammo, ammo_capacity(), item::ammo_remaining(), item::ammo_set(), base, item::clear_items(), CONTAINER, item::find_type(), is_fuel_store(), item::is_magazine(), is_tank(), is_turret(), item, item_capacity(), LIQUID, item::magazine_default(), MAGAZINE_WELL, min(), itype::phase, item::put_in(), and calendar::turn.
Referenced by distribute_charge_evenly(), and vehicles::finalize_prototypes().
ammo_unset()
void vehicle_part::ammo_unset ()
Remove all fuel, charges or ammunition (if any) from this part.
Definition at line 354 of file vehicle_part.cpp.
 {
     if( is_tank() ) {
         base.clear_items();
     } else if( is_fuel_store() ) {
         base.ammo_unset();
     }
 }
References item::ammo_unset(), base, item::clear_items(), is_fuel_store(), and is_tank().
Referenced by vehicle::explode_fuel(), vehicle::init_state(), vehicle::leak_fuel(), and vehicle::smash().
can_reload()
bool vehicle_part::can_reload (const item & obj = item()) const
Definition at line 400 of file vehicle_part.cpp.
 {
     // first check part is not destroyed and can contain ammo
     if( !is_fuel_store() ) {
         return false;
     }
     if( is_battery() ) {
         return false;
     }
     if( !obj.is_null() ) {
         const itype_id obj_type = obj.typeId();
         if( is_reactor() ) {
             return base.can_reload_with( obj, true );
         }
         // forbid filling tanks with solids or non-material things
         if( is_tank() && ( obj.made_of( phase_id::SOLID ) || obj.made_of( phase_id::PNULL ) ) ) {
             return false;
         }
         // forbid putting liquids, gasses, and plasma in things that aren't tanks
         if( !obj.made_of( phase_id::SOLID ) && !is_tank() ) {
             return false;
         }
         // prevent mixing of different ammo
         if( !ammo_current().is_null() && ammo_current() != obj_type ) {
             return false;
         }
         // For storage with set type, prevent filling with different types
         if( info().fuel_type != fuel_type_none && info().fuel_type != obj_type ) {
             return false;
         }
         // don't fill magazines with inappropriate fuel
         if( !is_tank() && !base.can_reload_with( obj, true ) ) {
             return false;
         }
     }
     if( base.is_gun() ) {
         return false;
     }
     if( is_reactor() ) {
         return true;
     }
     if( ammo_current().is_null() ) {
         return true; // empty tank
     }
     // Despite checking for an empty tank, item::find_type can still turn up with an empty ammo pointer
     if( cata::value_ptr<islot_ammo> a_val = item::find_type( ammo_current() )->ammo ) {
         return ammo_remaining() < ammo_capacity( a_val->type );
     }
     // Nothing in tank
     return ammo_capacity( obj.ammo_type() ) > 0;
 }
References ammo_capacity(), ammo_current(), ammo_remaining(), item::ammo_type(), base, item::can_reload_with(), item::find_type(), fuel_type_none, info(), is_battery(), is_fuel_store(), item::is_gun(), item::is_null(), is_reactor(), is_tank(), item::made_of(), PNULL, SOLID, and item::typeId().
Referenced by fill_with(), and veh_app_interact::refill().
carried_name()
std::string vehicle_part::carried_name () const
Definition at line 717 of file vehicle_part.cpp.
 {
     return carried_stack.empty()
            ? std::string()
            : carried_stack.top().veh_name;
 }
References carried_stack.
Referenced by vehicle::find_vehicles_to_unrack(), and vehicle::print_vparts_descs().
consume_energy()
units::energy vehicle_part::consume_energy (const itype_id & ftype, units::energy wanted_energy)
Consume fuel by energy content.
Parameters
ftype Type of fuel to consume
wanted_energy Energy to consume
Returns
Energy actually consumed
Definition at line 377 of file vehicle_part.cpp.
 {
     if( !is_fuel_store() ) {
         return 0_J;
     }
     for( item *const fuel : base.all_items_top() ) {
         if( fuel->typeId() != ftype || !fuel->is_fuel() ) {
             continue;
         }
         const units::energy energy_per_charge = fuel->fuel_energy();
         const int charges_wanted = static_cast<int>( wanted_energy / energy_per_charge );
         const int charges_to_use = std::min( charges_wanted, fuel->charges );
         fuel->charges -= charges_to_use;
         if( fuel->charges == 0 ) {
             base.remove_item( *fuel );
         }
         return charges_to_use * energy_per_charge;
     }
     return 0_J;
 }
References item::all_items_top(), base, is_fuel_store(), min(), and visitable::remove_item().
contains_liquid()
bool vehicle_part::contains_liquid () const
Does this part currently contain some liquid?
Definition at line 591 of file vehicle_part.cpp.
 {
     return is_tank() && !base.empty() &&
            base.only_item().made_of( phase_id::LIQUID );
 }
References base, item::empty(), is_tank(), LIQUID, item::made_of(), and item::only_item().
crew()
npc * vehicle_part::crew () const
Get NPC currently assigned to this part (seat, turret etc)?
Note
checks crew member is alive and currently allied to the player
Returns
nullptr if no valid crew member is currently assigned
Definition at line 525 of file vehicle_part.cpp.
 {
     if( is_broken() || !crew_id.is_valid() ) {
         return nullptr;
     }
     npc *const res = g->critter_by_id<npc>( crew_id );
     if( !res ) {
         return nullptr;
     }
     return res->is_player_ally() ? res : nullptr;
 }
References crew_id, g, is_broken(), npc::is_player_ally(), and character_id::is_valid().
Referenced by veh_interact::calc_overview(), and npc::execute_action().
damage()
int vehicle_part::damage () const
Current part damage in same units as item::damage.
Definition at line 159 of file vehicle_part.cpp.
 {
     return base.damage();
 }
References base, and item::damage().
Referenced by damage_percent(), and vehicle_activity().
damage_level()
int vehicle_part::damage_level () const
damage level of part base
Definition at line 174 of file vehicle_part.cpp.
 {
     return base.damage_level();
 }
References base, and item::damage_level().
Referenced by veh_interact::complete_vehicle().
damage_percent()
double vehicle_part::damage_percent () const
Current part damage as a percentage of maximum, with 0.0 being perfect condition.
Definition at line 194 of file vehicle_part.cpp.
 {
     return static_cast<double>( damage() ) / max_damage();
 }
References damage(), and max_damage().
Referenced by veh_interact::display_stats(), vehicle::engine_start_time(), health_percent(), hp(), and vehicle::start_engine().
degradation()
int vehicle_part::degradation () const
Current part degradation of part base.
Definition at line 164 of file vehicle_part.cpp.
 {
     return base.degradation();
 }
References base, and item::degradation().
Referenced by vehicle_activity().
deserialize()
void vehicle_part::deserialize (const JsonObject & data)
Definition at line 3172 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     vpart_id pid;
     data.read( "id", pid );
     data.read( "variant", variant );
     const vpart_migration *migration = vpart_migration::find_migration( pid );
     if( migration != nullptr ) {
         const std::string &new_variant = migration->variant
                                          ? migration->variant.value()
                                          : migration->part_id_new->variant_default;
         DebugLog( D_WARNING, D_MAIN ) << "vehicle_part::deserialize migrating " <<
                                       "vpid '" << pid.str() << "' to '" << migration->part_id_new.str() << "' "
                                       "variant '" << variant << "' to '" << new_variant << "'";
         pid = migration->part_id_new;
         variant = new_variant;
     }
     if( !pid.is_valid() ) {
         data.throw_error_at( "id", "bad vehicle part" );
     }
     info_ = &pid.obj();
     if( migration != nullptr ) { // migration overrides the base item
         data.get_member( "base" ); // mark member as visited
         base = item( migration->part_id_new->base_item, calendar::turn );
     } else {
         data.read( "base", base );
     }
     if( info().variants.count( variant ) <= 0 ) {
         variant = info().variant_default;
     }
     data.read( "mount_dx", mount.x );
     data.read( "mount_dy", mount.y );
     data.read( "open", open );
     int direction_int;
     data.read( "direction", direction_int );
     direction = units::from_degrees( direction_int );
     data.read( "blood", blood );
     data.read( "enabled", enabled );
     data.read( "flags", flags );
     data.read( "passenger_id", passenger_id );
     if( data.has_int( "z_offset" ) ) {
         int z_offset = data.get_int( "z_offset" );
         if( std::abs( z_offset ) > 10 ) {
             data.throw_error_at( "z_offset", "z_offset out of range" );
         }
         precalc[0].z = z_offset;
         precalc[1].z = z_offset;
     }
     JsonArray ja_carried = data.get_array( "carried_stack" );
     // count down from size - 1, then stop after unsigned long 0 - 1 becomes MAX_INT
     for( size_t index = ja_carried.size() - 1; index < ja_carried.size(); index-- ) {
         vehicle_part::carried_part_data it;
         ja_carried.read( index, it );
         carried_stack.push( it );
     }
     data.read( "crew_id", crew_id );
     data.read( "items", items );
     data.read( "tools", tools );
     data.read( "salvageable", salvageable );
     data.read( "target_first_x", target.first.x );
     data.read( "target_first_y", target.first.y );
     data.read( "target_first_z", target.first.z );
     data.read( "target_second_x", target.second.x );
     data.read( "target_second_y", target.second.y );
     data.read( "target_second_z", target.second.z );
     data.read( "ammo_pref", ammo_pref );
     data.read( "locked", locked );
     data.read( "last_disconnected", last_disconnected );
     if( migration != nullptr ) {
         for( const itype_id &it : migration->add_veh_tools ) {
             tools.emplace_back( it, calendar::turn );
         }
     }
 }
References abs(), D_MAIN, D_WARNING, item_pocket::data, DebugLog(), enabled, vpart_migration::find_migration(), oter_type_t::flags, units::from_degrees(), string_id< T >::is_valid(), item, string_id< T >::obj(), open(), JsonArray::read(), JsonArray::size(), string_id< T >::str(), calendar::turn, and migration::variant.
fault_set()
bool vehicle_part::fault_set (const fault_id & f)
Try to set fault returning false if specified fault cannot occur with this item.
Definition at line 516 of file vehicle_part.cpp.
 {
     if( !faults_potential().count( f ) ) {
         return false;
     }
     base.faults.insert( f );
     return true;
 }
References base, item::faults, and faults_potential().
Referenced by vehicle::init_state().
faults()
const std::set< fault_id > & vehicle_part::faults () const
Current faults affecting this part (if any)
Definition at line 501 of file vehicle_part.cpp.
 {
     return base.faults;
 }
References base, and item::faults.
Referenced by veh_interact::calc_overview().
faults_potential()
std::set< fault_id > vehicle_part::faults_potential () const
Faults which could potentially occur with this part (if any)
Definition at line 511 of file vehicle_part.cpp.
 {
     return base.faults_potential();
 }
References base, and item::faults_potential().
Referenced by fault_set(), vehicle::init_state(), and vehicle::start_engine().
fill_with()
bool vehicle_part::fill_with (item & liquid, int qty = INT_MAX)
Try adding.
Parameters
liquid to tank optionally limited by
qty
Returns
whether any of the liquid was consumed (which may be less than qty)
Definition at line 477 of file vehicle_part.cpp.
 {
     if( ( is_tank() && !liquid.made_of( phase_id::LIQUID ) ) || !can_reload( liquid ) ) {
         return false;
     }
     int charges_max = 0;
     if( cata::value_ptr<islot_ammo> a_val = item::find_type( ammo_current() )->ammo ) {
         charges_max = ammo_capacity( a_val->type ) - ammo_remaining();
     } else {
         // Nothing in tank
         charges_max = ammo_capacity( liquid.ammo_type() );
     }
     qty = qty < liquid.charges ? qty : liquid.charges;
     if( charges_max < liquid.charges ) {
         qty = charges_max;
     }
     liquid.charges -= base.fill_with( liquid, qty );
     return true;
 }
References ammo_capacity(), ammo_current(), ammo_remaining(), item::ammo_type(), base, can_reload(), item::charges, item::fill_with(), item::find_type(), is_tank(), LIQUID, and item::made_of().
Referenced by Character::pour_into().
floating_leak_threshold()
double vehicle_part::floating_leak_threshold () const
The leaking thresold for the boat hull.
Definition at line 189 of file vehicle_part.cpp.
 {
     return 0.5;
 }
Referenced by name().
fuel_current()
itype_id vehicle_part::fuel_current () const
Type of fuel used by an engine.
Definition at line 223 of file vehicle_part.cpp.
 {
     if( !ammo_pref.is_null() ) {
         return ammo_pref;
     }
     return info().fuel_type;
 }
References ammo_pref, vpart_info::fuel_type, info(), and string_id< T >::is_null().
Referenced by veh_interact::calc_overview(), vehicle::control_engines(), vehicle::engine_fuel_left(), vehicle::fuel_usage(), vehicle::is_alternator_on(), vehicle::is_engine_type(), vehicle::print_fuel_indicators(), and display::vehicle_fuel_percent_text_color().
fuel_set()
bool vehicle_part::fuel_set (const itype_id & fuel)
Set an engine to use a different type of fuel.
Definition at line 231 of file vehicle_part.cpp.
 {
     if( is_engine() ) {
         for( const itype_id &avail : info().engine_info->fuel_opts ) {
             if( fuel == avail ) {
                 ammo_pref = fuel;
                 return true;
             }
         }
     }
     return false;
 }
References ammo_pref, info(), and is_engine().
Referenced by vehicle::auto_select_fuel().
get_base()
const item & vehicle_part::get_base () const
Definition at line 66 of file vehicle_part.cpp.
 {
     return base;
 }
References base.
Referenced by get_targeting_npc(), veh_utils::most_repairable_part(), veh_app_interact::refill(), vehicle::remove_part(), veh_utils::repair_part(), vehicle::shed_loose_parts(), veh_app_interact::siphon(), and vehicle::unlink_cables().
get_salvageable()
std::vector< item > vehicle_part::get_salvageable () const
Definition at line 71 of file vehicle_part.cpp.
 {
     std::vector<item> tmp;
     if( has_flag( vp_flag::unsalvageable_flag ) ) {
         return tmp;
     }
     if( !salvageable.empty() ) {
         return salvageable;
     }
     // Get default install component
     const requirement_data reqs = info().install_requirements();
     for( const auto &altercomps : reqs.get_components() ) {
         const item_comp &comp = altercomps.front();
         item newit( comp.type, calendar::turn );
         if( base.typeId() != comp.type && !newit.has_flag( flag_UNRECOVERABLE ) ) {
             int compcount = comp.count;
             const bool is_liquid = newit.made_of( phase_id::LIQUID );
             if( newit.count_by_charges() || is_liquid ) {
                 newit.charges = compcount;
                 compcount = 1;
             } else if( !newit.craft_has_charges() && newit.charges > 0 ) {
                 newit.charges = 0;
             }
             for( ; compcount > 0; compcount-- ) {
                 tmp.push_back( newit );
             }
         }
     }
     return tmp;
 }
References base, item::charges, component::count, item::count_by_charges(), item::craft_has_charges(), flag_UNRECOVERABLE, requirement_data::get_components(), item::has_flag(), has_flag(), info(), vpart_info::install_requirements(), LIQUID, item::made_of(), salvageable, calendar::turn, component::type, item::typeId(), and unsalvageable_flag.
Referenced by veh_interact::can_remove_part(), and veh_interact::complete_vehicle().
get_targeting_npc()
npc & vehicle_part::get_targeting_npc (vehicle & veh)
Definition at line 547 of file turret.cpp.
 {
     // Make a fake NPC to represent the targeting system
     if( !cpu.brain ) {
         cpu.brain = std::make_unique<npc>();
         npc &brain = *cpu.brain;
         brain.set_body();
         brain.set_fake( true );
         // turrets are subject only to recoil_vehicle()
         brain.recoil = 0;
         // These might all be affected by vehicle part damage, weather effects, etc.
         brain.str_cur = 16;
         brain.dex_cur = 8;
         brain.per_cur = 12;
         // Assume vehicle turrets are friendly to the player.
         brain.set_attitude( NPCATT_FOLLOW );
         brain.set_fac( veh.get_owner() );
         brain.set_skill_level( skill_gun, 4 );
         brain.name = string_format( _( "The %s turret" ), get_base().tname( 1 ) );
         brain.set_skill_level( get_base().gun_skill(), 8 );
     }
     cpu.brain->setpos( veh.global_part_pos3( *this ) );
     cpu.brain->recalc_sight_limits();
     return *cpu.brain;
 }
References _, turret_cpu::brain, cpu, Character::dex_cur, get_base(), vehicle::get_owner(), vehicle::global_part_pos3(), Character::name, NPCATT_FOLLOW, Character::per_cur, Character::recoil, npc::set_attitude(), Creature::set_body(), npc::set_fac(), Creature::set_fake(), Character::set_skill_level(), skill_gun, Character::str_cur, and string_format().
Referenced by vehicle::automatic_fire_turret().
has_fault_flag()
bool vehicle_part::has_fault_flag (const std::string & searched_flag) const
Does this vehicle part have a fault with this flag.
Definition at line 506 of file vehicle_part.cpp.
 {
     return base.has_fault_flag( searched_flag );
 }
References base, and item::has_fault_flag().
Referenced by vehicle::basic_consumption(), vehicle::engine_cold_factor(), vehicle::engine_fuel_usage(), vehicle::is_alternator_on(), vehicle::noise_and_smoke(), vehicle::start_engine(), and vehicle::total_power().
has_flag()
bool vehicle_part::has_flag (const vp_flag flag) const inline noexcept
Definition at line 276 of file vehicle.h.
{
             const uint32_t flag_as_uint32 = static_cast<uint32_t>( flag );
             return ( flags & flag_as_uint32 ) == flag_as_uint32;
         }
References flags.
Referenced by veh_app_interact::can_disconnect(), vehicle::can_unmount(), vehicle::coeff_water_drag(), veh_interact::do_repair(), vehicle::find_vehicles_to_unrack(), vehicle::get_printable_fuel_types(), get_salvageable(), vehicle::has_structural_part(), vehicle::is_connected(), is_unavailable(), vehicle::merge_rackable_vehicle(), name(), vehicle::print_vparts_descs(), process_contents(), vehicle::remove_carried_vehicle(), vehicle::remove_part(), and vehicle::unlink_cables().
health_percent()
double vehicle_part::health_percent () const
Current part health as a percentage of maximum, with 1.0 being perfect condition.
Definition at line 184 of file vehicle_part.cpp.
 {
     return 1.0 - damage_percent();
 }
References damage_percent().
Referenced by vehicle::get_exhaust_part(), is_leaking(), name(), vehicle::noise_and_smoke(), vehicle::part_epower(), vehicle::part_vpower_w(), and vehicle::slow_leak().
hp()
int vehicle_part::hp () const
current part health with range [0,durability]
Definition at line 149 of file vehicle_part.cpp.
 {
     const int dur = info().durability;
     if( base.max_damage() > 0 ) {
         return dur - dur * damage_percent();
     } else {
         return dur;
     }
 }
References base, damage_percent(), dur, vpart_info::durability, info(), and item::max_damage().
Referenced by map::build_seen_cache(), vehicle::damage_direct(), vehicle::explode_fuel(), map::route(), and vehicle::smash().
info()
const vpart_info & vehicle_part::info () const
Get part definition common to all parts of this type.
Definition at line 623 of file vehicle_part.cpp.
 {
     return *info_;
 }
References info_.
Referenced by vehicle::activate_animal_follow(), vehicle::active_reactor_epower(), turret_data::ammo_current(), vehicle::auto_select_fuel(), vehicle::avail_linkable_part(), vehicle::average_offroad_rating(), vehicle::break_off(), map::build_seen_cache(), veh_app_interact::can_disconnect(), vehicle::can_enable(), vehicle::can_mount(), can_reload(), veh_interact::can_remove_part(), vehicle::can_unmount(), vehicle::close(), vehicle::coeff_air_drag(), vehicle::coeff_water_drag(), vehicle::collision(), veh_interact::complete_vehicle(), vehicle::autodrive_controller::compute_profile(), vehicle::control_doors(), vehicle::control_engines(), vehicle::damage(), vehicle::damage_all(), vehicle::damage_direct(), do_change_shape_menu(), veh_interact::do_repair(), vehicle::engine_cold_factor(), vehicle::engine_fuel_usage(), vehicle::engine_start_time(), vehicle::explode_fuel(), vehicles::finalize_prototypes(), vehicle::find_and_split_vehicles(), vehicle::find_lines_of_parts(), vehicle::folding_time(), fuel_current(), vehicle::fuel_left(), fuel_set(), generic_multi_activity_check_requirement(), vehicle::get_connected_vehicles(), vehicle::get_display_of_tile(), vehicle::get_exhaust_part(), vehicle::get_harnessed_animal(), get_salvageable(), vehicle::handle_trap(), vehicle::has_engine_conflict(), has_quality_from_vpart(), vehicle::has_security_working(), vehicle::has_structural_part(), hp(), vehicle::idle(), vpart_reference::info(), vehicle::init_state(), is_battery(), is_cleaner_on(), vehicle::is_connected(), is_engine(), vehicle::is_engine_type_combustion(), is_light(), vehicle::is_perpetual_type(), is_reactor(), is_repairable(), is_seat(), vehicle::lock(), vehicle_part_with_feature_range< feature_type >::matches(), max_quality_from_vpart(), vehicle_stack::max_volume(), vehicle::merge_vehicle_parts(), vehicle::mod_hp(), map::move_vehicle(), name(), vehicle::next_part_to_close(), vehicle::next_part_to_lock(), vehicle::next_part_to_open(), vehicle::next_part_to_unlock(), vehicle::noise_and_smoke(), vehicle::open(), vehicle::open_all_at(), vehicle::part_collision(), vehicle::part_displayed_at(), vehicle::part_epower(), vehicle::part_has_lock(), vehicle::part_vpower_w(), vehicle::part_with_feature(), pieces_for_broken_part(), veh_app_interact::populate_app_actions(), vehicle::power_parts(), vehicle::prepare_tools(), vehicle::print_part_list(), vehicle::print_vparts_descs(), process_contents(), map::process_items_in_vehicle(), process_vehicle_items(), put_into_vehicle(), veh_app_interact::refill(), vehicle::refresh(), vehicle::refresh_insides(), vehicle::refresh_pivot(), veh_app_interact::remove(), vehicle::remove_part(), DefaultRemovePartHandler::removed(), vehicle::removed_part(), veh_utils::repair_part(), vehicle::roof_at_part(), map::route(), vehicle_prototype::save_vehicle_as_prototype(), vehicle::search_connected_vehicles(), set_base(), vehicle::set_hp(), map::shake_vehicle(), vehicle::shed_loose_parts(), vehicle::smash(), vehicle::smash_security_system(), vehicle::split_vehicles(), vehicle::start_engine(), vehicle::steering_effectiveness(), vehicle::stop_engines(), vehicle::thrust(), vehicle::total_accessory_epower(), vehicle::total_power(), vehicle::unfolding_time(), vehicle::unlink_cables(), vehicle::unlock(), vehicle::update_active_fakes(), vehicle::update_alternator_load(), veh_interact::update_part_requirements(), vehicle::update_time(), vehicle::use_harness(), turret_data::uses_vehicle_tanks_or_batteries(), vehicle_activity(), map::vehicle_vehicle_collision(), map::vehicle_wheel_traction(), vehicle::would_removal_prevent_flyable(), and vehicle::would_repair_prevent_flyable().
is_available()
bool vehicle_part::is_available (bool carried = true) const
parts are available if they aren't unavailable
Definition at line 218 of file vehicle_part.cpp.
 {
     return !is_unavailable( carried );
 }
References is_unavailable().
Referenced by vehicle::active_reactor_epower(), vehicle::auto_select_fuel(), vehicle::coeff_air_drag(), vehicle::control_engines(), vehicle::has_available_electric_engine(), vehicle::has_security_working(), vehicle::init_state(), vehicle::is_alternator_on(), vehicle::is_engine_on(), vehicle_part_with_feature_range< feature_type >::matches(), vehicle::next_part_to_close(), vehicle::next_part_to_lock(), vehicle::next_part_to_open(), vehicle::next_part_to_unlock(), vehicle::part_has_lock(), vehicle::refresh_insides(), vehicle::smart_controller_handle_turn(), and vehicle::steering_effectiveness().
is_battery()
bool vehicle_part::is_battery () const
Can this part store electrical charge?
Definition at line 597 of file vehicle_part.cpp.
 {
     return info().has_flag( VPFLAG_BATTERY ) ||
            ( base.is_magazine() && base.ammo_types().count( ammo_battery ) );
 }
References ammo_battery, item::ammo_types(), base, vpart_info::has_flag(), info(), item::is_magazine(), and VPFLAG_BATTERY.
Referenced by ammo_current(), can_reload(), vehicle::init_state(), and is_leaking().
is_broken()
bool vehicle_part::is_broken () const
parts are considered broken at zero health
Definition at line 200 of file vehicle_part.cpp.
 {
     return base.damage() >= base.max_damage();
 }
References base, item::damage(), and item::max_damage().
Referenced by vehicle::add_item(), vehicle::avail_linkable_part(), vehicle::break_off(), vehicle::can_enable(), veh_interact::can_remove_part(), veh_interact::complete_vehicle(), crew(), vehicle::damage_direct(), veh_interact::do_repair(), vehicle::explode_fuel(), vehicle::get_display_of_tile(), vpart_position::get_tools(), has_quality_from_vpart(), is_fuel_store(), is_repairable(), is_unavailable(), vehicle_part_with_feature_range< feature_type >::matches(), max_quality_from_vpart(), vehicle_stack::max_volume(), veh_utils::most_repairable_part(), veh_interact::move_cursor(), vehicle::part_with_feature(), vpart_position::part_with_tool(), vehicle::place_spawn_items(), vehicle::print_vparts_descs(), vehicle::refresh_pivot(), vehicle::remove_carried_vehicle(), veh_utils::repair_part(), set_crew(), vehicle::smash(), vehicle::smash_security_system(), vehicle::start_engines(), vehicle::turret_query(), vehicle::turrets(), and vehicle_caching_internal().
is_cleaner_on()
bool vehicle_part::is_cleaner_on () const
Is this an enabled autoclave, dishwasher, or washing machine?
Definition at line 205 of file vehicle_part.cpp.
 {
     const bool is_cleaner = info().has_flag( VPFLAG_AUTOCLAVE ) ||
                             info().has_flag( VPFLAG_DISHWASHER ) ||
                             info().has_flag( VPFLAG_WASHING_MACHINE );
     return is_cleaner && enabled;
 }
References enabled, vpart_info::has_flag(), info(), VPFLAG_AUTOCLAVE, VPFLAG_DISHWASHER, and VPFLAG_WASHING_MACHINE.
Referenced by advanced_inv_area::can_store_in_vehicle().
is_engine()
bool vehicle_part::is_engine () const
Can this part provide power or propulsion?
Definition at line 561 of file vehicle_part.cpp.
 {
     return info().has_flag( VPFLAG_ENGINE );
 }
References vpart_info::has_flag(), info(), and VPFLAG_ENGINE.
Referenced by vehicle::auto_select_fuel(), and fuel_set().
is_fuel_store()
bool vehicle_part::is_fuel_store (bool skip_broke = true) const
Can this part store fuel of any type @skip_broke exclude broken parts.
Definition at line 578 of file vehicle_part.cpp.
 {
     if( skip_broke && is_broken() ) {
         return false;
     }
     return is_tank() || base.is_magazine() || is_reactor();
 }
References base, is_broken(), item::is_magazine(), is_reactor(), and is_tank().
Referenced by ammo_capacity(), ammo_current(), ammo_remaining(), ammo_set(), ammo_unset(), can_reload(), veh_interact::complete_vehicle(), consume_energy(), vehicle::damage_direct(), vehicle::get_printable_fuel_types(), vehicle::init_state(), vehicle::print_part_list(), and veh_app_interact::refill().
is_leaking()
bool vehicle_part::is_leaking () const
is this part currently unable to retain to fluid/charge? this doesn't take into account whether or not the part has any contents remaining to leak
Definition at line 608 of file vehicle_part.cpp.
 {
     return  health_percent() <= 0.5 && ( is_tank() || is_battery() || is_reactor() );
 }
References health_percent(), is_battery(), is_reactor(), and is_tank().
Referenced by veh_interact::calc_overview(), activity_handlers::fill_liquid_do_turn(), name(), and vehicle::slow_leak().
is_light()
bool vehicle_part::is_light () const
Is this any type of vehicle light?
Definition at line 566 of file vehicle_part.cpp.
 {
     const vpart_info &vp = info();
     return vp.has_flag( VPFLAG_CONE_LIGHT ) ||
            vp.has_flag( VPFLAG_WIDE_CONE_LIGHT ) ||
            vp.has_flag( VPFLAG_HALF_CIRCLE_LIGHT ) ||
            vp.has_flag( VPFLAG_CIRCLE_LIGHT ) ||
            vp.has_flag( VPFLAG_AISLE_LIGHT ) ||
            vp.has_flag( VPFLAG_DOME_LIGHT ) ||
            vp.has_flag( VPFLAG_ATOMIC_LIGHT );
 }
References vpart_info::has_flag(), info(), VPFLAG_AISLE_LIGHT, VPFLAG_ATOMIC_LIGHT, VPFLAG_CIRCLE_LIGHT, VPFLAG_CONE_LIGHT, VPFLAG_DOME_LIGHT, VPFLAG_HALF_CIRCLE_LIGHT, and VPFLAG_WIDE_CONE_LIGHT.
is_reactor()
bool vehicle_part::is_reactor () const
Is this part a reactor?
Definition at line 603 of file vehicle_part.cpp.
 {
     return info().has_flag( VPFLAG_REACTOR );
 }
References vpart_info::has_flag(), info(), and VPFLAG_REACTOR.
Referenced by can_reload(), vehicle::init_state(), is_fuel_store(), and is_leaking().
is_real_or_active_fake()
bool vehicle_part::is_real_or_active_fake () const inline
Definition at line 578 of file vehicle.h.
{
             return !is_fake || is_active_fake;
         }
References is_active_fake, and is_fake.
Referenced by vehicle::collision(), vehicle::do_remove_part_actual(), vehicle_part_with_fakes_range::matches(), vehicle::part_displayed_at(), and vehicle::print_part_list().
is_repairable()
bool vehicle_part::is_repairable () const
Definition at line 179 of file vehicle_part.cpp.
 {
     return !is_broken() && base.repairable_levels() > 0 && info().is_repairable();
 }
References base, info(), is_broken(), vpart_info::is_repairable(), and item::repairable_levels().
Referenced by veh_interact::do_repair(), veh_utils::most_repairable_part(), and veh_interact::move_cursor().
is_seat()
bool vehicle_part::is_seat () const
Can a player or NPC use this part as a seat?
Definition at line 618 of file vehicle_part.cpp.
 {
     return info().has_flag( "SEAT" );
 }
References vpart_info::has_flag(), and info().
Referenced by vehicle::assign_seat(), and set_crew().
is_tank()
bool vehicle_part::is_tank () const
Can this part contain liquid fuels?
Definition at line 586 of file vehicle_part.cpp.
 {
     return base.is_watertight_container();
 }
References base, and item::is_watertight_container().
Referenced by ammo_capacity(), ammo_consume(), ammo_current(), ammo_remaining(), ammo_set(), ammo_unset(), can_reload(), veh_interact::complete_vehicle(), contains_liquid(), vehicle::drain(), fill_with(), vehicle::fuel_left(), vehicle::init_state(), is_fuel_store(), is_leaking(), vehicle::leak_fuel(), veh_app_interact::refill(), and vehicle_prototype::save_vehicle_as_prototype().
is_turret()
bool vehicle_part::is_turret () const
Can this part function as a turret?
Definition at line 613 of file vehicle_part.cpp.
 {
     return base.is_gun();
 }
References base, and item::is_gun().
Referenced by ammo_capacity(), ammo_current(), ammo_remaining(), ammo_set(), vehicle_prototype::save_vehicle_as_prototype(), set_crew(), vehicle::turret_query(), and vehicle::turrets().
is_unavailable()
bool vehicle_part::is_unavailable (bool carried = true) const
parts are unavailable if broken or if carried is true, if they have the CARRIED flag
Definition at line 213 of file vehicle_part.cpp.
 {
     return is_broken() || ( has_flag( vp_flag::carried_flag ) && carried );
 }
References carried_flag, has_flag(), and is_broken().
Referenced by vehicle::find_lines_of_parts(), vehicle::idle(), vehicle::is_alternator_on(), is_available(), vehicle::power_parts(), vehicle::total_solar_epower(), vehicle::total_water_wheel_epower(), vehicle::total_wind_epower(), vehicle::update_time(), and vehicle::use_harness().
item_capacity()
int vehicle_part::item_capacity (const itype_id & stuffing_id) const
Maximum amount of fuel, charges or ammunition that can be contained by a part.
Definition at line 278 of file vehicle_part.cpp.
 {
     const itype *stuffing = item::find_type( stuffing_id );
     if( stuffing->ammo ) {
         return ammo_capacity( stuffing->ammo->type );
     }
     int max_amount_volume = 0;
     int max_amount_weight = stuffing->weight == 0_gram ? INT_MAX :
                             static_cast<int>( base.get_total_weight_capacity() / stuffing->weight );
     if( stuffing->count_by_charges() ) {
         max_amount_volume = stuffing->charges_per_volume( base.get_total_capacity() );
     } else {
         max_amount_volume = base.get_total_capacity() / stuffing->volume;
     }
     return std::min( max_amount_volume, max_amount_weight );
 }
References itype::ammo, ammo_capacity(), base, itype::charges_per_volume(), itype::count_by_charges(), item::find_type(), item::get_total_capacity(), item::get_total_weight_capacity(), min(), itype::volume, and itype::weight.
Referenced by ammo_set(), and vehicles::finalize_prototypes().
max_damage()
int vehicle_part::max_damage () const
max damage of part base
Definition at line 169 of file vehicle_part.cpp.
 {
     return base.max_damage();
 }
References base, and item::max_damage().
Referenced by damage_percent(), and vehicle_activity().
name()
std::string vehicle_part::name (bool with_prefix = true) const
Translated name of a part inclusive of any current status effects with_prefix as true indicates the durability symbol should be prepended.
Definition at line 113 of file vehicle_part.cpp.
 {
     std::string res;
     if( with_prefix ) {
         res += base.damage_indicator() + base.degradation_symbol() + " ";
         if( !base.type->degrade_increments() ) {
             res += " "; // aligns names when printing degrading and non-degrading parts with prefixes
         }
     }
     if( base.is_wheel() ) {
         res += string_format( _( "%d\" " ), base.type->wheel->diameter );
     }
     res += info().name();
     if( base.has_var( "contained_name" ) ) {
         res += string_format( _( " holding %s" ), base.get_var( "contained_name" ) );
     }
     for( const fault_id &f : base.faults ) {
         const std::string prefix = f->item_prefix();
         if( !prefix.empty() ) {
             res += " (" + prefix + ")";
             break;
         }
     }
     if( health_percent() < floating_leak_threshold() && info().has_flag( VPFLAG_FLOATS ) &&
         !info().has_flag( VPFLAG_NO_LEAK ) ) {
         res += _( " (leaking)" );
     }
     if( is_leaking() ) {
         res += _( " (draining)" );
     }
     if( debug_mode ) {
         res += "{" + variant + "}";
     }
     return res;
 }
References _, base, item::damage_indicator(), debug_mode, item::degradation_symbol(), itype::degrade_increments(), item::faults, floating_leak_threshold(), item::get_var(), has_flag(), item::has_var(), health_percent(), info(), is_leaking(), item::is_wheel(), fault::item_prefix(), vpart_info::name(), prefix, string_format(), item::type, variant, VPFLAG_FLOATS, VPFLAG_NO_LEAK, and itype::wheel.
Referenced by inventory_selector::add_vehicle_items(), vehicle::automatic_fire_turret(), vehicle::backfire(), vehicle::break_off(), vehicle::can_enable(), veh_interact::can_remove_part(), vehicle::can_unmount(), vehicle::close(), doors::close_door(), veh_interact::complete_vehicle(), vehicle::control_doors(), vehicle::control_engines(), vehicle::damage_direct(), veh_interact::display_overview(), vehicle::drain(), optional_vpart_position::extended_description(), vehicle::handle_trap(), vehicle::lock(), doors::lock_door(), avatar_action::move(), turret_data::name(), open(), vehicle::open(), vehicle::part_collision(), Character::pour_into(), vehicle::print_part_list(), vehicle::print_vparts_descs(), process_vehicle_items(), veh_app_interact::refill(), vehicle::remove_carried_vehicle(), veh_utils::repair_part(), vehicle::restore_folded_parts(), vehicle::separate_from_grid(), vehicle::shed_loose_parts(), vehicle::start_engine(), vehicle::unlink_cables(), vehicle::unlock(), and doors::unlock_door().
pieces_for_broken_part()
item_group::ItemList vehicle_part::pieces_for_broken_part () const
Returns an ItemList of the pieces that should arise from breaking this part.
Definition at line 2558 of file vehicle.cpp.
 {
     const item_group_id &group = info().breaks_into_group;
     // TODO: make it optional? Or use id of empty item group?
     if( group.is_empty() ) {
         return {};
     }
     return item_group::items_from( group, calendar::turn );
 }
References vpart_info::breaks_into_group, info(), item_group::items_from(), and calendar::turn.
Referenced by veh_interact::can_remove_part(), veh_interact::complete_vehicle(), and veh_utils::repair_part().
process_contents()
void vehicle_part::process_contents (map & here, const tripoint & pos, bool e_heater)
If this part is capable of wholly containing something, process the items in there.
Parameters
pos Position of this part for item::process
e_heater Engine has a heater and is on
Definition at line 459 of file vehicle_part.cpp.
 {
     // for now we only care about processing food containers since things like
     // fuel don't care about temperature yet
     temperature_flag flag = temperature_flag::NORMAL;
     if( e_heater ) {
         flag = temperature_flag::HEATER;
     }
     if( enabled && info().has_flag( VPFLAG_FRIDGE ) ) {
         flag = temperature_flag::FRIDGE;
     } else if( enabled && info().has_flag( VPFLAG_FREEZER ) ) {
         flag = temperature_flag::FREEZER;
     } else if( enabled && info().has_flag( VPFLAG_HEATED_TANK ) ) {
         flag = temperature_flag::HEATER;
     }
     base.process( here, nullptr, pos, 1, flag );
 }
References base, enabled, FREEZER, FRIDGE, has_flag(), HEATER, info(), NORMAL, math_opers::pos(), item::process(), VPFLAG_FREEZER, VPFLAG_FRIDGE, and VPFLAG_HEATED_TANK.
remaining_ammo_capacity()
int vehicle_part::remaining_ammo_capacity () const
Definition at line 310 of file vehicle_part.cpp.
 {
     return base.remaining_ammo_capacity();
 }
References base, and item::remaining_ammo_capacity().
remove_flag()
void vehicle_part::remove_flag (const vp_flag flag) inline noexcept
Definition at line 283 of file vehicle.h.
{
             flags &= ~static_cast<uint32_t>( flag );
         }
References flags.
Referenced by map::displace_vehicle(), vehicle::init_state(), vehicle::merge_rackable_vehicle(), vehicle::remove_carried_vehicle(), vehicle::remove_part(), item::reset_link(), map::shake_vehicle(), vehicle::split_vehicles(), map::unboard_vehicle(), and vehicle::unlink_cables().
reset_target()
void vehicle_part::reset_target (const tripoint & pos)
Reset the target for this part.
Definition at line 555 of file vehicle_part.cpp.
 {
     target.first = pos;
     target.second = pos;
 }
References math_opers::pos(), and target.
Referenced by vehicle::automatic_fire_turret().
serialize()
void vehicle_part::serialize (JsonOut & json) const
Definition at line 3255 of file savegame_json.cpp.
 {
     json.start_object();
     json.member( "id", info_->id.str() );
     if( !variant.empty() ) {
         json.member( "variant", variant );
     }
     json.member( "base", base );
     json.member( "mount_dx", mount.x );
     json.member( "mount_dy", mount.y );
     json.member( "open", open );
     json.member( "direction", std::lround( to_degrees( direction ) ) );
     json.member( "blood", blood );
     json.member( "enabled", enabled );
     json.member( "flags", flags );
     if( !carried_stack.empty() ) {
         std::stack<vehicle_part::carried_part_data> carried_copy = carried_stack;
         json.member( "carried_stack" );
         json.start_array();
         while( !carried_copy.empty() ) {
             json.write( carried_copy.top() );
             carried_copy.pop();
         }
         json.end_array();
     }
     json.member( "passenger_id", passenger_id );
     json.member( "crew_id", crew_id );
     if( precalc[0].z ) {
         json.member( "z_offset", precalc[0].z );
     }
     json.member( "items", items );
     json.member( "tools", tools );
     json.member( "salvageable", salvageable );
     if( target.first != tripoint_min ) {
         json.member( "target_first_x", target.first.x );
         json.member( "target_first_y", target.first.y );
         json.member( "target_first_z", target.first.z );
     }
     if( target.second != tripoint_min ) {
         json.member( "target_second_x", target.second.x );
         json.member( "target_second_y", target.second.y );
         json.member( "target_second_z", target.second.z );
     }
     json.member( "ammo_pref", ammo_pref );
     json.member( "locked", locked );
     json.member( "last_disconnected", last_disconnected );
     json.end_object();
 }
References enabled, JsonOut::end_array(), JsonOut::end_object(), oter_type_t::flags, JsonOut::member(), open(), JsonOut::start_array(), JsonOut::start_object(), units::to_degrees(), tripoint_min, and JsonOut::write().
set_base()
void vehicle_part::set_base (item && new_base)
Definition at line 102 of file vehicle_part.cpp.
 {
     if( new_base.typeId() != info().base_item ) {
         debugmsg( "new base '%s' doesn't match part type '%s', this is a bug",
                   new_base.typeId().str(), info().id.str() );
         return;
     }
     base = std::move( new_base );
     base.set_flag( flag_VEHICLE );
 }
References base, debugmsg, flag_VEHICLE, info(), and item::set_flag().
Referenced by vehicle::remove_part(), and vehicle_part().
set_crew()
bool vehicle_part::set_crew (const npc & who)
Set crew member for this part (seat, turret etc) who must be a player ally)
Returns
true if part can have crew members and passed npc was suitable
Definition at line 538 of file vehicle_part.cpp.
 {
     if( who.is_dead_state() || !( who.is_walking_with() || who.is_player_ally() ) ) {
         return false;
     }
     if( is_broken() || ( !is_seat() && !is_turret() ) ) {
         return false;
     }
     crew_id = who.getID();
     return true;
 }
References crew_id, Character::getID(), is_broken(), Character::is_dead_state(), npc::is_player_ally(), is_seat(), is_turret(), and npc::is_walking_with().
Referenced by vehicle::assign_seat().
set_flag()
void vehicle_part::set_flag (const vp_flag flag) inline noexcept
Definition at line 280 of file vehicle.h.
{
             flags |= static_cast<uint32_t>( flag );
         }
References flags.
Referenced by construct::done_vehicle(), vehicle::merge_rackable_vehicle(), and item::process_link().
unset_crew()
void vehicle_part::unset_crew ()
Remove any currently assigned crew member for this part.
Definition at line 550 of file vehicle_part.cpp.
 {
     crew_id = character_id();
 }
References character_id, and crew_id.
Friends And Related Function Documentation
turret_data
friend class turret_data friend
Definition at line 260 of file vehicle.h.
veh_interact
friend class veh_interact friend
Definition at line 256 of file vehicle.h.
vehicle_cursor
friend class vehicle_cursor friend
Definition at line 257 of file vehicle.h.
vehicle_stack
friend class vehicle_stack friend
Definition at line 258 of file vehicle.h.
Member Data Documentation
ammo_pref
itype_id vehicle_part::ammo_pref = itype_id::NULL_ID() private
Preferred ammo type when multiple are available.
Definition at line 550 of file vehicle.h.
Referenced by turret_data::ammo_current(), turret_data::ammo_select(), fuel_current(), and fuel_set().
base
item vehicle_part::base private
Definition at line 541 of file vehicle.h.
Referenced by vehicle::add_item(), ammo_capacity(), turret_data::ammo_capacity(), ammo_consume(), ammo_current(), turret_data::ammo_current(), turret_data::ammo_data(), turret_data::ammo_effects(), turret_data::ammo_options(), ammo_remaining(), turret_data::ammo_remaining(), ammo_set(), ammo_unset(), turret_data::base(), veh_interact::calc_overview(), turret_data::can_reload(), can_reload(), turret_data::can_unload(), veh_interact::complete_vehicle(), consume_energy(), contains_liquid(), damage(), damage_level(), degradation(), veh_interact::do_repair(), fault_set(), faults(), faults_potential(), fill_with(), vehicle::fuel_left(), get_base(), get_salvageable(), has_fault_flag(), hp(), is_battery(), is_broken(), is_fuel_store(), is_repairable(), is_tank(), is_turret(), item_capacity(), max_damage(), vehicle::mod_hp(), name(), vehicle::part_collision(), vehicle::part_to_item(), process_contents(), turret_data::query(), turret_data::range(), remaining_ammo_capacity(), item_location::impl::item_on_vehicle::remove_item(), vehicle::restore_folded_parts(), item_location::impl::item_on_vehicle::serialize(), set_base(), vehicle::set_hp(), item_location::impl::item_on_vehicle::unpack(), and vehicle_part().
blood
int vehicle_part::blood = 0
how much blood covers part (in turns).
Definition at line 494 of file vehicle.h.
Referenced by map::add_splatter(), vehicle::get_display_of_tile(), vehicle::init_state(), map::mop_spills(), vehicle::part_collision(), and map::terrain_moppable().
carried_stack
std::stack<carried_part_data> vehicle_part::carried_stack
Definition at line 303 of file vehicle.h.
Referenced by carried_name(), item::link_to(), vehicle::merge_rackable_vehicle(), and vehicle::remove_carried_vehicle().
cpu
turret_cpu vehicle_part::cpu
Definition at line 353 of file vehicle.h.
Referenced by get_targeting_npc().
crew_id
character_id vehicle_part::crew_id private
What NPC (if any) is assigned to this part (seat, turret etc)?
See also
vehicle_part::crew() accessor which excludes dead and non-allied NPC's
Definition at line 556 of file vehicle.h.
Referenced by crew(), set_crew(), and unset_crew().
direction
units::angle vehicle_part::direction = 0_degrees
direction the part is facing
Definition at line 519 of file vehicle.h.
Referenced by orient_part(), and veh_utils::repair_part().
enabled
bool vehicle_part::enabled = true
Definition at line 507 of file vehicle.h.
Referenced by vehicle::activate_animal_follow(), vehicle::active_reactor_epower(), add_electronic_toggle(), veh_interact::calc_overview(), vehicle::control_engines(), vehicle::fuel_left(), vehicle::has_available_electric_engine(), vehicle::idle(), vehicle::init_state(), vehicle::install_part(), vehicle::is_alternator_on(), is_cleaner_on(), vehicle::is_engine_on(), vehicle_part_with_feature_range< feature_type >::matches(), vehicle::max_reactor_epower(), vehicle::merge_rackable_vehicle(), vehicle::power_parts(), process_contents(), map::process_items_in_vehicle(), process_vehicle_items(), vehicle::remove_carried_vehicle(), vehicle::remove_part(), vehicle::smart_controller_handle_turn(), vehicle::start_engine(), vehicle::start_engines(), vehicle::total_accessory_epower(), vehicle::turrets_set_targeting(), vehicle::use_autoclave(), vehicle::use_dishwasher(), and vehicle::use_washing_machine().
fake_part_at
int vehicle_part::fake_part_at = -1
Definition at line 576 of file vehicle.h.
Referenced by vehicle::lock_or_unlock(), vehicle::open_or_close(), vehicle::refresh(), vehicle::remove_fake_parts(), and vehicle::remove_part().
fake_part_to
int vehicle_part::fake_part_to = -1
Definition at line 573 of file vehicle.h.
Referenced by vehicle::do_remove_part_actual(), vehicle::get_non_fake_part(), vehicle::lock_or_unlock(), vehicle::open_or_close(), vehicle::refresh(), vehicle::remove_fake_parts(), and vehicle::update_active_fakes().
fake_protrusion_on
int vehicle_part::fake_protrusion_on = -1
Definition at line 574 of file vehicle.h.
Referenced by vehicle::refresh(), and vehicle::update_active_fakes().
flags
uint32_t vehicle_part::flags = 0 private
Definition at line 539 of file vehicle.h.
Referenced by has_flag(), remove_flag(), and set_flag().
has_fake
bool vehicle_part::has_fake = false
Definition at line 575 of file vehicle.h.
Referenced by vehicle::lock_or_unlock(), vehicle::open_or_close(), vehicle::refresh(), vehicle::remove_fake_parts(), and vehicle::remove_part().
info_
const vpart_info* vehicle_part::info_ private
Definition at line 537 of file vehicle.h.
Referenced by info(), and vehicle_part().
inside
bool vehicle_part::inside = false
if tile provides cover.
WARNING: do not read it directly, use vpart_position::is_inside() instead
Definition at line 500 of file vehicle.h.
Referenced by vpart_position::is_inside(), and vehicle::refresh_insides().
is_active_fake
bool vehicle_part::is_active_fake = false
Definition at line 572 of file vehicle.h.
Referenced by is_real_or_active_fake(), and vehicle::update_active_fakes().
is_fake
bool vehicle_part::is_fake = false
Definition at line 571 of file vehicle.h.
Referenced by vehicle::collision(), vehicle::do_remove_part_actual(), vehicle::get_non_fake_part(), vehicle::get_points(), is_real_or_active_fake(), vehicle::lock_or_unlock(), vehicle_part_with_feature_range< feature_type >::matches(), vehicle_part_range::matches(), vehicle::merge_vehicle_parts(), vehicle::open_or_close(), vehicle::refresh(), vehicle::restore_folded_parts(), vehicle_prototype::save_vehicle_as_prototype(), vehicle::search_connected_batteries(), and vehicle::smash().
item_location
friend vehicle_part::item_location
Definition at line 259 of file vehicle.h.
items
cata::colony<item> vehicle_part::items private
Definition at line 545 of file vehicle.h.
Referenced by vehicle::add_item(), vehicle::damage_direct(), vehicle::decrement_summon_timer(), and vehicle::remove_item().
last_disconnected
time_point vehicle_part::last_disconnected = calendar::before_time_starts
Definition at line 531 of file vehicle.h.
Referenced by vehicle::unlink_cables().
locked
bool vehicle_part::locked = false
door is locked
Definition at line 516 of file vehicle.h.
Referenced by vehicle::control_doors(), vehicle::lock_or_unlock(), vehicle::next_part_to_lock(), vehicle::next_part_to_open(), vehicle::next_part_to_unlock(), and vehicle::open_or_close().
mount
point vehicle_part::mount
mount point: x is on the forward/backward axis, y is on the left/right axis
Definition at line 447 of file vehicle.h.
Referenced by vehicle::add_item(), vehicle::break_off(), vehicle::can_unmount(), veh_interact::complete_vehicle(), vehicle::autodrive_controller::compute_profile(), vehicle::damage(), vehicle::damage_all(), veh_interact::display_veh(), veh_interact::do_repair(), map::draw_maptile(), vehicle::find_lines_of_parts(), vehicle::find_vehicles_to_unrack(), has_quality_from_vpart(), vehicle::install_part(), vehicle::invalidate_towing(), vehicle::is_alternator_on(), vehicle::is_connected(), vehicle::make_active(), max_quality_from_vpart(), vehicle::merge_rackable_vehicle(), vehicle::merge_vehicle_parts(), vpart_position::mount(), veh_interact::move_cursor(), map::move_vehicle(), vehicle::part_collision(), vehicle::part_with_feature(), pldrive(), item::process_link(), veh_app_interact::refill(), vehicle::refresh(), vehicle::refresh_insides(), vehicle::refresh_pivot(), vehicle::remove_carried_vehicle(), vehicle::remove_part(), DefaultRemovePartHandler::removed(), veh_utils::repair_part(), item::reset_link(), vehicle_prototype::save_vehicle_as_prototype(), veh_interact::serialize_activity(), vehicle::slow_leak(), vehicle::smash(), vehicle::smash_security_system(), vehicle::split_vehicles(), vehicle::turrets_set_targeting(), vehicle::update_active_fakes(), veh_interact::update_part_requirements(), npc::vehicle_danger(), and map::vehicle_vehicle_collision().
open
bool vehicle_part::open = false
door is open
Definition at line 513 of file vehicle.h.
Referenced by vehicle::control_doors(), vehicle::damage(), vehicle::get_display_of_tile(), vehicle::init_state(), vehicle::lock(), avatar_action::move(), vehicle::next_part_to_close(), vehicle::next_part_to_lock(), vehicle::next_part_to_open(), vehicle::open_or_close(), and vehicle::refresh_insides().
passenger_id
character_id vehicle_part::passenger_id
ID of player passenger.
Definition at line 510 of file vehicle.h.
Referenced by veh_interact::calc_overview(), vehicle::merge_rackable_vehicle(), and vehicle::split_vehicles().
precalc
std::array<tripoint, 2> vehicle_part::precalc = { { tripoint(-1, -1, 0), tripoint(-1, -1, 0) } }
mount translated to face.dir [0] and turn_dir [1]
Definition at line 451 of file vehicle.h.
Referenced by vehicle::bub_part_pos(), vehicle::collision(), map::displace_vehicle(), vehicle::global_part_pos3(), game::grabbed_veh_move(), item::process_link(), vehicle::shed_loose_parts(), vehicle::smash(), and vehicle::update_active_fakes().
removed
bool vehicle_part::removed = false
true if this part is removed.
The part won't disappear until the end of the turn so our indices can remain consistent.
Definition at line 506 of file vehicle.h.
Referenced by vehicle::can_enable(), vehicle::collision(), vehicle::autodrive_controller::compute_profile(), vehicle::damage_direct(), vehicle::do_remove_part_actual(), vehicle::find_and_split_vehicles(), veh_interact::get_most_damaged_part(), vehicle::index_of_part(), vehicle_part_with_feature_range< feature_type >::matches(), vehicle::merge_vehicle_parts(), veh_utils::most_repairable_part(), process_vehicle_items(), vehicle::refresh_insides(), vehicle::remove_fake_parts(), vehicle::remove_part(), vehicle::restore_folded_parts(), vehicle::smash(), vehicle::smash_security_system(), vehicle::split_vehicles(), vehicle::turret_query(), vehicle::update_active_fakes(), and vehicle::use_harness().
salvageable
std::vector<item> vehicle_part::salvageable private
Definition at line 547 of file vehicle.h.
Referenced by get_salvageable(), and vehicle_part().
target
std::pair<tripoint, tripoint> vehicle_part::target = { tripoint_min, tripoint_min }
Coordinates for some kind of target; jumper cables and turrets use this Two coordinate pairs are stored: actual target point, and target vehicle center.
Both cases use absolute coordinates (relative to world origin)
Definition at line 526 of file vehicle.h.
Referenced by vehicle::automatic_fire_turret(), vehicle::get_connected_vehicles(), vehicle::get_remote_part(), item::link_to(), vehicle::part_to_item(), reset_target(), vehicle::search_connected_vehicles(), and vehicle::shed_loose_parts().
tools
std::vector<item> vehicle_part::tools private
Definition at line 543 of file vehicle.h.
Referenced by vehicle::get_tools(), vehicle::prepare_tools(), and vehicle::remove_part().
variant
std::string vehicle_part::variant
If it's a part with variants, which variant it is.
Definition at line 529 of file vehicle.h.
Referenced by do_change_shape_menu(), vehicles::finalize_prototypes(), vehicle::get_display_of_tile(), name(), veh_utils::repair_part(), vehicle_activity(), and vehicle_part().
vehicle
friend vehicle_part::vehicle
Definition at line 255 of file vehicle.h.
Referenced by vehicle::remove_remote_part().
The documentation for this struct was generated from the following files:
src/vehicle.h
src/savegame_json.cpp
src/turret.cpp
src/vehicle.cpp
src/vehicle_part.cpp