Cataclysm DDA: damage_info_order::damage_info_order_entry Struct Reference
damage_info_order::damage_info_order_entry Struct Reference
#include <damage.h>
Public Member Functions
void load (const JsonObject &jo, std::string_view member)
Public Attributes
int order = -1
bool show_type = false
Detailed Description
Definition at line 76 of file damage.h.
Member Function Documentation
load()
void damage_info_order::damage_info_order_entry::load (const JsonObject & jo, std::string_view member)
Definition at line 176 of file damage.cpp.
 {
     if( jo.has_object( member ) || jo.has_int( member ) ) {
         if( jo.has_int( member ) ) {
             show_type = true;
             order = jo.get_int( member );
         } else {
             JsonObject jsobj = jo.get_object( member );
             mandatory( jsobj, false, "order", order );
             optional( jsobj, false, "show_type", show_type, true );
         }
     }
 }
References JsonObject::get_int(), JsonObject::get_object(), JsonObject::has_int(), JsonObject::has_object(), mandatory, member, optional(), order, and show_type.
Referenced by damage_info_order::load().
Member Data Documentation
order
int damage_info_order::damage_info_order_entry::order = -1
Definition at line 77 of file damage.h.
Referenced by load().
show_type
bool damage_info_order::damage_info_order_entry::show_type = false
Definition at line 78 of file damage.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/damage.h
src/damage.cpp