Cataclysm DDA: damage_info_order Struct Reference
damage_info_order Struct Reference
#include <damage.h>
Classes
struct damage_info_order_entry
Public Types
enum class info_disp : int { NONE , BASIC , DETAILED }
enum class info_type : int {
NONE = 0 , BIO , PROT , PET ,
MELEE , ABLATE
}
Public Member Functions
void finalize ()
void load (const JsonObject &jo, std::string_view src)
Static Public Member Functions
static void load_damage_info_orders (const JsonObject &jo, const std::string &src)
static void reset ()
static void finalize_all ()
static const std::vector< damage_info_order > & get_all ()
static const std::vector< damage_info_order > & get_all (info_type sort_by)
Public Attributes
damage_info_order_id id
damage_type_id dmg_type = damage_type_id::NULL_ID()
info_disp info_display = info_disp::DETAILED
translation verb
damage_info_order_entry bionic_info
damage_info_order_entry protection_info
damage_info_order_entry pet_prot_info
damage_info_order_entry melee_combat_info
damage_info_order_entry ablative_info
bool was_loaded = false
Detailed Description
Definition at line 62 of file damage.h.
Member Enumeration Documentation
info_disp
enum damage_info_order::info_disp : int strong
Enumerator
NONE
BASIC
DETAILED
Definition at line 63 of file damage.h.
                          : int {
         NONE,
         BASIC,
         DETAILED
     };
info_type
enum damage_info_order::info_type : int strong
Enumerator
NONE
BIO
PROT
PET
MELEE
ABLATE
Definition at line 68 of file damage.h.
                          : int {
         NONE = 0,
         BIO,
         PROT,
         PET,
         MELEE,
         ABLATE
     };
Member Function Documentation
finalize()
void damage_info_order::finalize ()
Definition at line 290 of file damage.cpp.
 {
     if( verb.empty() ) {
         verb = dmg_type->name;
     }
 }
References dmg_type, translation::empty(), damage_type::name, and verb.
finalize_all()
void damage_info_order::finalize_all () static
Definition at line 273 of file damage.cpp.
 {
     damage_info_order_factory.finalize();
     sorted_order_lists.emplace( info_type::NONE, damage_info_order_factory.get_all() );
     sorted_order_lists.emplace( info_type::BIO, damage_info_order_factory.get_all() );
     sorted_order_lists.emplace( info_type::PROT, damage_info_order_factory.get_all() );
     sorted_order_lists.emplace( info_type::PET, damage_info_order_factory.get_all() );
     sorted_order_lists.emplace( info_type::MELEE, damage_info_order_factory.get_all() );
     sorted_order_lists.emplace( info_type::ABLATE, damage_info_order_factory.get_all() );
     prepare_sorted_lists( sorted_order_lists[info_type::NONE], info_type::NONE );
     prepare_sorted_lists( sorted_order_lists[info_type::BIO], info_type::BIO );
     prepare_sorted_lists( sorted_order_lists[info_type::PROT], info_type::PROT );
     prepare_sorted_lists( sorted_order_lists[info_type::PET], info_type::PET );
     prepare_sorted_lists( sorted_order_lists[info_type::MELEE], info_type::MELEE );
     prepare_sorted_lists( sorted_order_lists[info_type::ABLATE], info_type::ABLATE );
 }
References ABLATE, BIO, anonymous_namespace{damage.cpp}::damage_info_order_factory, MELEE, NONE, PET, prepare_sorted_lists(), PROT, and sorted_order_lists.
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all() [1/2]
const std::vector< damage_info_order > & damage_info_order::get_all () static
Definition at line 94 of file damage.cpp.
 {
     return damage_info_order_factory.get_all();
 }
References anonymous_namespace{damage.cpp}::damage_info_order_factory.
Referenced by item::armor_protection_info(), item::bionic_info(), damage_type::check(), item_pocket::contents_info(), item::melee_combat_info(), and item::pet_armor_protection_info().
get_all() [2/2]
const std::vector< damage_info_order > & damage_info_order::get_all (info_type sort_by) static
Definition at line 99 of file damage.cpp.
 {
     return sorted_order_lists.at( sort_by );
 }
References sorted_order_lists.
load()
void damage_info_order::load (const JsonObject & jo, std::string_view src)
Definition at line 191 of file damage.cpp.
 {
     dmg_type = damage_type_id( id.c_str() );
     bionic_info.load( jo, "bionic_info" );
     protection_info.load( jo, "protection_info" );
     pet_prot_info.load( jo, "pet_prot_info" );
     melee_combat_info.load( jo, "melee_combat_info" );
     ablative_info.load( jo, "ablative_info" );
     optional( jo, was_loaded, "verb", verb );
     if( !was_loaded || jo.has_string( "info_display" ) ) {
         std::string info_str = info_display == info_disp::DETAILED ? "detailed" :
                                info_display == info_disp::BASIC ? "basic" : "none";
         optional( jo, was_loaded, "info_display", info_str, "none" );
         info_display = read_info_disp( info_str );
     }
 }
References ablative_info, BASIC, bionic_info, DETAILED, dmg_type, JsonObject::has_string(), info_display, damage_info_order::damage_info_order_entry::load(), melee_combat_info, optional(), pet_prot_info, protection_info, read_info_disp(), verb, and was_loaded.
load_damage_info_orders()
void damage_info_order::load_damage_info_orders (const JsonObject & jo, const std::string & src) static
Definition at line 83 of file damage.cpp.
 {
     damage_info_order_factory.load( jo, src );
 }
References anonymous_namespace{damage.cpp}::damage_info_order_factory.
Referenced by DynamicDataLoader::initialize().
reset()
void damage_info_order::reset () static
Definition at line 88 of file damage.cpp.
 {
     damage_info_order_factory.reset();
     sorted_order_lists.clear();
 }
References anonymous_namespace{damage.cpp}::damage_info_order_factory, and sorted_order_lists.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
ablative_info
damage_info_order_entry damage_info_order::ablative_info
Definition at line 89 of file damage.h.
Referenced by load().
bionic_info
damage_info_order_entry damage_info_order::bionic_info
Definition at line 85 of file damage.h.
Referenced by load().
dmg_type
damage_type_id damage_info_order::dmg_type = damage_type_id::NULL_ID()
Definition at line 82 of file damage.h.
Referenced by finalize(), and load().
id
damage_info_order_id damage_info_order::id
Definition at line 81 of file damage.h.
info_display
info_disp damage_info_order::info_display = info_disp::DETAILED
Definition at line 83 of file damage.h.
Referenced by anonymous_namespace{armor_layers.cpp}::clothing_protection(), and load().
melee_combat_info
damage_info_order_entry damage_info_order::melee_combat_info
Definition at line 88 of file damage.h.
Referenced by load().
pet_prot_info
damage_info_order_entry damage_info_order::pet_prot_info
Definition at line 87 of file damage.h.
Referenced by load().
protection_info
damage_info_order_entry damage_info_order::protection_info
Definition at line 86 of file damage.h.
Referenced by load().
verb
translation damage_info_order::verb
Definition at line 84 of file damage.h.
Referenced by finalize(), and load().
was_loaded
bool damage_info_order::was_loaded = false
Definition at line 90 of file damage.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/damage.h
src/damage.cpp