Cataclysm DDA: value_constraint Struct Reference
value_constraint Struct Reference
Public Types
enum comparator { lt , lteq , gteq , gt }
Public Member Functions
void deserialize (const JsonObject &jo)
void check (const std::string &name, const cata_variant_type input_type) const
bool is_constant () const
Public Attributes
std::vector< cata_variant > equals_any_
std::optional< string_id< event_statistic > > equals_statistic_
std::optional< std::pair< comparator, cata_variant > > val_comp_
Detailed Description
Definition at line 175 of file event_statistics.cpp.
Member Enumeration Documentation
comparator
enum value_constraint::comparator
Enumerator
lt
lteq
gteq
gt
Definition at line 176 of file event_statistics.cpp.
 { lt, lteq, gteq, gt };
Member Function Documentation
check()
void value_constraint::check (const std::string & name, const cata_variant_type input_type) const inline
Definition at line 222 of file event_statistics.cpp.
{
         if( equals_statistic_ ) {
             if( !equals_statistic_->is_valid() ) {
                 debugmsg( "constraint for event_transformation %s refers to invalid statistic %s",
                           name, equals_statistic_->str() );
                 return;
             }
             cata_variant_type stat_type = ( *equals_statistic_ )->type();
             if( stat_type != input_type ) {
                 debugmsg( "constraint for event_transformation %s matches statistic %s of "
                           "different type.  Statistic has type %s but value compared with it has "
                           "type %s",
                           name, equals_statistic_->str(), io::enum_to_string( stat_type ),
                           io::enum_to_string( input_type ) );
             }
         }
         const auto check_one = [&]( const cata_variant & e ) -> void {
             if( input_type != e.type() ) {
                 debugmsg( "constraint for event_transformation %s matches constant of type %s "
                           "but value compared with it has type %s",
                           name, io::enum_to_string( e.type() ),
                           io::enum_to_string( input_type ) );
             }
             if( !e.is_valid() ) {
                 debugmsg( "constraint for event_transformation %s matches constant %s of type %s "
                           "but that is not a valid value of that type",
                           name, e.get_string(), io::enum_to_string( e.type() ) );
             }
         };
         for( const cata_variant &e : equals_any_ ) {
             check_one( e );
         }
         if( val_comp_ ) {
             check_one( ( *val_comp_ ).second );
         }
     }
References debugmsg, io::enum_to_string(), equals_any_, equals_statistic_, om_direction::name(), and val_comp_.
deserialize()
void value_constraint::deserialize (const JsonObject & jo) inline
Definition at line 181 of file event_statistics.cpp.
{
         cata_variant single_val;
         const auto check_comp_int = [&]( const std::string & comp ) -> bool {
             bool ret = single_val.type() == cata_variant_type::int_;
             if( !ret ) {
                 jo.throw_error( string_format( "The value constraint \"%s\" may only be used with int type!",
                                                comp ) );
             }
             return ret;
         };
         if( jo.read( "equals", single_val, false ) ) {
             equals_any_ = { single_val };
         } else if( jo.read( "lt", single_val, false ) && check_comp_int( "lt" ) ) {
             val_comp_ = std::pair<comparator, cata_variant>( comparator::lt, single_val );
         } else if( jo.read( "lteq", single_val, false ) && check_comp_int( "lteq" ) ) {
             val_comp_ = std::pair<comparator, cata_variant>( comparator::lteq, single_val );
         } else if( jo.read( "gteq", single_val, false ) && check_comp_int( "gteq" ) ) {
             val_comp_ = std::pair<comparator, cata_variant>( comparator::gteq, single_val );
         } else if( jo.read( "gt", single_val, false ) && check_comp_int( "gt" ) ) {
             val_comp_ = std::pair<comparator, cata_variant>( comparator::gt, single_val );
         }
         std::pair<cata_variant_type, std::vector<std::string>> equals_any;
         if( jo.read( "equals_any", equals_any ) ) {
             equals_any_.reserve( equals_any.second.size() );
             for( std::string &s : equals_any.second ) {
                 equals_any_.push_back(
                     cata_variant::from_string( equals_any.first, std::move( s ) ) );
             }
         }
         string_id<event_statistic> stat;
         if( jo.read( "equals_statistic", stat ) ) {
             equals_statistic_ = stat;
         }
         if( equals_any_.empty() && !equals_statistic_ && !val_comp_ ) {
             jo.throw_error( "No valid value constraint found" );
         }
     }
References equals_any_, equals_statistic_, cata_variant::from_string(), math_opers::gt(), int_, math_opers::lt(), JsonObject::read(), cata::hash64_detail::ret, string_format(), JsonObject::throw_error(), cata_variant::type(), and val_comp_.
is_constant()
bool value_constraint::is_constant () const inline
Definition at line 263 of file event_statistics.cpp.
{
         return !equals_statistic_ ||
                ( *equals_statistic_ )->monotonicity() == monotonically::constant;
     }
References constant, and equals_statistic_.
Member Data Documentation
equals_any_
std::vector<cata_variant> value_constraint::equals_any_
Definition at line 177 of file event_statistics.cpp.
Referenced by check(), deserialize(), and event_transformation_impl::updatable_value_constraint::permits().
equals_statistic_
std::optional<string_id<event_statistic> > value_constraint::equals_statistic_
Definition at line 178 of file event_statistics.cpp.
Referenced by check(), deserialize(), is_constant(), and event_transformation_impl::updatable_value_constraint::updatable_value_constraint().
val_comp_
std::optional<std::pair<comparator, cata_variant> > value_constraint::val_comp_
Definition at line 179 of file event_statistics.cpp.
Referenced by check(), deserialize(), and event_transformation_impl::updatable_value_constraint::permits().
The documentation for this struct was generated from the following file:
src/event_statistics.cpp