Cataclysm DDA: component Struct Reference
component Struct Reference
#include <requirements.h>
Public Member Functions
bool operator== (const component &rhs) const
bool operator!= (const component &rhs) const
bool operator< (const component &rhs) const
component ()=default
component (const itype_id &TYPE, int COUNT)
component (const itype_id &TYPE, int COUNT, bool RECOVERABLE)
void check_consistency (const std::string &display_name) const
Public Attributes
itype_id type = itype_id::NULL_ID()
int count = 0
available_status available = available_status::a_false
bool recoverable = true
bool requirement = false
Detailed Description
Definition at line 58 of file requirements.h.
Constructor & Destructor Documentation
component() [1/3]
component::component () default
component() [2/3]
component::component (const itype_id & TYPE, int COUNT) inline
Definition at line 85 of file requirements.h.
 : type( TYPE ), count( COUNT ) { }
component() [3/3]
component::component (const itype_id & TYPE, int COUNT, bool RECOVERABLE) inline
Definition at line 86 of file requirements.h.
                                                                    :
         type( TYPE ), count( COUNT ), recoverable( RECOVERABLE ) { }
Member Function Documentation
check_consistency()
void component::check_consistency (const std::string & display_name) const
Definition at line 590 of file requirements.cpp.
 {
     if( !item::type_is_defined( type ) ) {
         debugmsg( "%s in %s is not a valid item template", type.c_str(), display_name );
     }
 }
References string_id< T >::c_str(), debugmsg, type, and item::type_is_defined().
operator!=()
bool component::operator!= (const component & rhs) const inline
Definition at line 74 of file requirements.h.
{
         return !operator==( rhs );
     }
References operator==().
operator<()
bool component::operator< (const component & rhs) const inline
Definition at line 78 of file requirements.h.
{
         //TODO change to use localized sorting
         return std::forward_as_tuple( type.str(), requirement, count, recoverable )
                < std::forward_as_tuple( rhs.type.str(), rhs.requirement, rhs.count, rhs.recoverable );
     }
References count, recoverable, requirement, string_id< T >::str(), and type.
operator==()
bool component::operator== (const component & rhs) const inline
Definition at line 70 of file requirements.h.
{
         return std::forward_as_tuple( type, requirement, count, recoverable )
                == std::forward_as_tuple( rhs.type, rhs.requirement, rhs.count, rhs.recoverable );
     }
References count, recoverable, requirement, and type.
Referenced by operator!=().
Member Data Documentation
available
available_status component::available = available_status::a_false mutable
Definition at line 63 of file requirements.h.
Referenced by requirement_data::check_enough_materials(), tool_comp::get_color(), and item_comp::get_color().
count
int component::count = 0
Definition at line 60 of file requirements.h.
Referenced by tool_comp::by_charges(), Character::can_continue_craft(), Character::can_disassemble(), requirement_data::check_enough_materials(), craft_command::check_item_components_missing(), Character::complete_disassemble(), Character::consume_items(), Character::consume_tools(), Character::craft_consume_tools(), craft_command::create_in_progress_craft(), salvage_actor::cut_up(), deserialize(), tool_comp::dump(), item_comp::dump(), expand_item_in_reqs(), item_comp::get_color(), item::get_recursive_disassemble_moves(), vehicle_part::get_salvageable(), item::get_uncraft_components(), tool_comp::has(), item_comp::has(), tool_comp::load(), item_comp::load(), operator<(), operator==(), sane_consume_items(), Character::select_item_component(), Character::select_tool_component(), serialize(), tool_comp::to_string(), and item_comp::to_string().
recoverable
bool component::recoverable = true
Definition at line 64 of file requirements.h.
Referenced by deserialize(), item_comp::dump(), item_comp::load(), operator<(), operator==(), and serialize().
requirement
bool component::requirement = false
Definition at line 66 of file requirements.h.
Referenced by tool_comp::dump(), item_comp::dump(), tool_comp::load(), item_comp::load(), operator<(), and operator==().
type
itype_id component::type = itype_id::NULL_ID()
Definition at line 59 of file requirements.h.
Referenced by Character::can_disassemble(), check_consistency(), requirement_data::check_enough_materials(), Character::complete_disassemble(), Character::consume_items(), Character::consume_tools(), salvage_actor::cut_up(), deserialize(), tool_comp::dump(), item_comp::dump(), expand_item_in_reqs(), item_comp::get_color(), recipe::get_component_filter(), requirement_data::get_folded_list(), recipe_result_info_cache::get_item_header(), item::get_recursive_disassemble_moves(), vehicle_part::get_salvageable(), tool_comp::has(), item_comp::has(), item::item(), tool_comp::load(), item_comp::load(), operator<(), operator==(), sane_consume_items(), Character::select_item_component(), Character::select_tool_component(), serialize(), tool_comp::to_string(), and item_comp::to_string().
The documentation for this struct was generated from the following files:
src/requirements.h
src/requirements.cpp