Cataclysm DDA: reader_detail::handler< enum_bitset< E > > Struct Template Reference
reader_detail::handler< enum_bitset< E > > Struct Template Reference
#include <generic_factory.h>
Public Member Functions
void clear (enum_bitset< E > &container) const
template<typename T >
void insert (enum_bitset< E > &container, const T &data) const
template<typename T >
void erase (enum_bitset< E > &container, const T &data) const
Static Public Attributes
static constexpr bool is_container = true
Detailed Description
template<typename E>
struct reader_detail::handler< enum_bitset< E > >
Definition at line 937 of file generic_factory.h.
Member Function Documentation
clear()
template<typename E > void reader_detail::handler< enum_bitset< E > >::clear (enum_bitset< E > & container) const inline
Definition at line 938 of file generic_factory.h.
{
         container.reset();
     }
References enum_bitset< E >::reset().
erase()
template<typename E > template<typename T > void reader_detail::handler< enum_bitset< E > >::erase (enum_bitset< E > & container, const T & data) const inline
Definition at line 946 of file generic_factory.h.
{
         container.reset( data );
     }
References enum_bitset< E >::reset().
insert()
template<typename E > template<typename T > void reader_detail::handler< enum_bitset< E > >::insert (enum_bitset< E > & container, const T & data) const inline
Definition at line 942 of file generic_factory.h.
{
         container.set( data );
     }
References enum_bitset< E >::set().
Member Data Documentation
is_container
template<typename E > constexpr bool reader_detail::handler< enum_bitset< E > >::is_container = true static constexpr
Definition at line 949 of file generic_factory.h.
The documentation for this struct was generated from the following file:
src/generic_factory.h