Cataclysm DDA: event_statistic_unique_value Struct Reference
event_statistic_unique_value Struct Reference
Classes
struct state
Public Member Functions
cata_variant value (stats_tracker &stats) const override
std::unique_ptr< stats_tracker_state > watch (stats_tracker &stats) const override
monotonically monotonicity () const override
std::unique_ptr< impl > clone () const override
event_statistic_field_summary (const string_id< event_statistic > &i, std::unique_ptr< event_source > s, const std::string &f)
Public Member Functions inherited from event_statistic_field_summary< false >
event_statistic_field_summary (const string_id< event_statistic > &i, std::unique_ptr< event_source > s, const std::string &f)
void check (const std::string &name) const override
cata_variant_type type () const override
Public Member Functions inherited from event_statistic::impl
virtual ~impl ()=default
Additional Inherited Members
Public Attributes inherited from event_statistic_field_summary< false >
string_id< event_statistic > id
cata::clone_ptr< event_source > source
std::string field
Detailed Description
Definition at line 1007 of file event_statistics.cpp.
Member Function Documentation
clone()
std::unique_ptr<impl> event_statistic_unique_value::clone () const inline override virtual
Implements event_statistic::impl.
Definition at line 1074 of file event_statistics.cpp.
{
         return std::make_unique<event_statistic_unique_value>( *this );
     }
event_statistic_field_summary()
event_statistic_field_summary< IntField >::event_statistic_field_summary inline
Definition at line 801 of file event_statistics.cpp.
       : id( i ), source( std::move( s ) ), field( f )
     {}
monotonicity()
monotonically event_statistic_unique_value::monotonicity () const inline override virtual
Implements event_statistic::impl.
Definition at line 1066 of file event_statistics.cpp.
{
         if( source->is_game_start() ) {
             return monotonically::constant;
         } else {
             return monotonically::unknown;
         }
     }
References constant, event_source::is_game_start(), event_statistic_field_summary< false >::source, and unknown.
value()
cata_variant event_statistic_unique_value::value (stats_tracker & stats) const inline override virtual
Implements event_statistic::impl.
Definition at line 1010 of file event_statistics.cpp.
{
         const event_multiset::summaries_type summaries = source->get( stats ).counts();
         if( summaries.size() != 1 ) {
             return cata_variant();
         }
         const cata::event::data_type &d = summaries.begin()->first;
         auto it = d.find( field );
         if( it == d.end() ) {
             return cata_variant();
         }
         return it->second;
     }
References event_multiset::counts(), event_source::get(), and event_statistic_field_summary< false >::source.
Referenced by event_statistic_unique_value::state::init().
watch()
std::unique_ptr<stats_tracker_state> event_statistic_unique_value::watch (stats_tracker & stats) const inline override virtual
Implements event_statistic::impl.
Definition at line 1062 of file event_statistics.cpp.
{
         return std::make_unique<state>( this, stats );
     }
The documentation for this struct was generated from the following file:
src/event_statistics.cpp