Cataclysm DDA: talk_response Struct Reference
talk_response Struct Reference
This defines possible responses from the player character.
#include <dialogue.h>
Public Member Functions
talk_data create_option_line (dialogue &d, const input_event &hotkey, bool is_computer=false)
std::set< dialogue_consequence > get_consequences (dialogue &d) const
talk_response ()
talk_response (const JsonObject &)
Public Attributes
std::string text
What the player character says (literally).
translation truetext
translation falsetext
std::function< bool(dialogue &)> truefalse_condition
talk_trial trial
mission * mission_selected = nullptr
The following values are forwarded to the chatbin of the NPC (see npc_chatbin).
skill_id skill = skill_id()
matype_id style = matype_id()
spell_id dialogue_spell = spell_id()
proficiency_id proficiency = proficiency_id()
talk_effect_t success
talk_effect_t failure
Detailed Description
This defines possible responses from the player character.
Definition at line 150 of file dialogue.h.
Constructor & Destructor Documentation
talk_response() [1/2]
talk_response::talk_response ()
Definition at line 6629 of file npctalk.cpp.
 {
     truefalse_condition = []( const dialogue & ) {
         return true;
     };
     mission_selected = nullptr;
     // Why aren't these null ids? Well, it turns out most responses give
     // empty ids, so things like the training code check for these empty ids
     // and when it's given a null id, it breaks
     // FIXME: Use null ids
     skill = skill_id();
     style = matype_id();
     proficiency = proficiency_id();
     dialogue_spell = spell_id();
 }
References dialogue_spell, matype_id, mission_selected, proficiency_id, skill, skill_id, spell_id, style, and truefalse_condition.
talk_response() [2/2]
talk_response::talk_response (const JsonObject & jo) explicit
Definition at line 6645 of file npctalk.cpp.
 {
     if( jo.has_member( "truefalsetext" ) ) {
         JsonObject truefalse_jo = jo.get_object( "truefalsetext" );
         read_condition( truefalse_jo, "condition", truefalse_condition, true );
         truefalse_jo.read( "true", truetext );
         truefalse_jo.read( "false", falsetext );
     } else {
         jo.read( "text", truetext );
         truefalse_condition = []( const dialogue & ) {
             return true;
         };
     }
     if( jo.has_member( "trial" ) ) {
         JsonObject trial_obj = jo.get_object( "trial" );
         trial = talk_trial( trial_obj );
     }
     if( jo.has_member( "success" ) ) {
         JsonObject success_obj = jo.get_object( "success" );
         success = talk_effect_t( success_obj, "effect" );
     } else if( jo.has_string( "topic" ) ) {
         // This is for simple topic switching without a possible failure
         success.next_topic = talk_topic( jo.get_string( "topic" ) );
         success.load_effect( jo, "effect" );
     } else if( jo.has_object( "topic" ) ) {
         success.next_topic = load_inline_topic( jo.get_object( "topic" ) );
     }
     if( trial && !jo.has_member( "failure" ) ) {
         jo.throw_error( "the failure effect is mandatory if a talk_trial has been defined" );
     }
     if( jo.has_member( "failure" ) ) {
         JsonObject failure_obj = jo.get_object( "failure" );
         failure = talk_effect_t( failure_obj, "effect" );
     }
     // TODO: mission_selected
     // TODO: skill
     // TODO: style
 }
References failure, falsetext, JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), talk_effect_t::load_effect(), load_inline_topic(), talk_effect_t::next_topic, JsonObject::read(), read_condition(), success, JsonObject::throw_error(), trial, truefalse_condition, and truetext.
Member Function Documentation
create_option_line()
talk_data talk_response::create_option_line (dialogue & d, const input_event & hotkey, bool is_computer = false)
Definition at line 2435 of file npctalk.cpp.
 {
     std::string ftext;
     text = ( truefalse_condition( d ) ? truetext : falsetext ).translated();
     if( trial.type == TALK_TRIAL_NONE || trial.type == TALK_TRIAL_CONDITION ) {
         // regular dialogue
         ftext = text;
     } else if( trial.type == TALK_TRIAL_SKILL_CHECK ) {
         const Skill &req_skill = skill_id( trial.skill_required ).obj();
         ftext = string_format( pgettext( "talk option", "[%1$s %2$d/%3$d] %4$s" ),
                                req_skill.name(),
                                std::min( d.actor( false )->get_skill_level( req_skill.ident() ),
                                          trial.difficulty ),
                                trial.difficulty,
                                text );
     } else {
         // dialogue w/ a % chance to work
         //~ %1$s is translated trial type, %2$d is a number, and %3$s is the translated response text
         ftext = string_format( pgettext( "talk option", "[%1$s %2$d%%] %3$s" ),
                                trial.name(), trial.calc_chance( d ), text );
     }
     if( d.actor( true )->get_npc() ) {
         parse_tags( ftext, *d.actor( false )->get_character(), *d.actor( true )->get_npc(), d,
                     success.next_topic.item_type );
     } else {
         parse_tags( ftext, *d.actor( false )->get_character(), *d.actor( false )->get_character(), d,
                     success.next_topic.item_type );
     }
     nc_color color;
     std::set<dialogue_consequence> consequences = get_consequences( d );
     if( consequences.count( dialogue_consequence::hostile ) > 0 ) {
         color = c_red;
     } else if( text[0] == '*' || consequences.count( dialogue_consequence::helpless ) > 0 ) {
         color = c_light_red;
     } else if( text[0] == '&' || consequences.count( dialogue_consequence::action ) > 0 ||
                is_computer ) {
         color = c_green;
     } else {
         color = c_white;
     }
     talk_data results;
     results.color = color;
     results.hotkey_desc = right_justify( hotkey.short_description(), 2 );
     results.text = ftext;
     return results;
 }
References action, dialogue::actor(), c_green, c_light_red, c_red, c_white, talk_trial::calc_chance(), talk_data::color, color(), talk_trial::difficulty, falsetext, talker::get_character(), get_consequences(), talker::get_npc(), talker::get_skill_level(), helpless, hostile, talk_data::hotkey_desc, Skill::ident(), talk_topic::item_type, min(), talk_trial::name(), Skill::name(), talk_effect_t::next_topic, parse_tags(), pgettext, right_justify(), input_event::short_description(), skill_id, talk_trial::skill_required, string_format(), success, TALK_TRIAL_CONDITION, TALK_TRIAL_NONE, TALK_TRIAL_SKILL_CHECK, text, talk_data::text, trial, truefalse_condition, truetext, and talk_trial::type.
get_consequences()
std::set< dialogue_consequence > talk_response::get_consequences (dialogue & d) const
Definition at line 2484 of file npctalk.cpp.
 {
     int chance = trial.calc_chance( d );
     if( chance >= 100 ) {
         return { success.get_consequence( d ) };
     } else if( chance <= 0 ) {
         return { failure.get_consequence( d ) };
     }
     return {{ success.get_consequence( d ), failure.get_consequence( d ) }};
 }
References talk_trial::calc_chance(), failure, talk_effect_t::get_consequence(), success, and trial.
Referenced by create_option_line().
Member Data Documentation
dialogue_spell
spell_id talk_response::dialogue_spell = spell_id()
Definition at line 170 of file dialogue.h.
Referenced by dialogue::add_response(), dialogue::opt(), and talk_response().
failure
talk_effect_t talk_response::failure
Definition at line 174 of file dialogue.h.
Referenced by json_talk_response::gen_repeat_response(), get_consequences(), json_talk_topic::get_directly_reachable_topics(), dialogue::opt(), and talk_response().
falsetext
translation talk_response::falsetext
Definition at line 160 of file dialogue.h.
Referenced by create_option_line(), and talk_response().
mission_selected
mission* talk_response::mission_selected = nullptr
The following values are forwarded to the chatbin of the NPC (see npc_chatbin).
Definition at line 167 of file dialogue.h.
Referenced by dialogue::add_response(), dialogue::opt(), and talk_response().
proficiency
proficiency_id talk_response::proficiency = proficiency_id()
Definition at line 171 of file dialogue.h.
Referenced by dialogue::add_response(), and dialogue::opt().
skill
skill_id talk_response::skill = skill_id()
Definition at line 168 of file dialogue.h.
Referenced by dialogue::add_response(), dialogue::opt(), and talk_response().
style
matype_id talk_response::style = matype_id()
Definition at line 169 of file dialogue.h.
Referenced by dialogue::add_response(), dialogue::opt(), and talk_response().
success
talk_effect_t talk_response::success
Definition at line 173 of file dialogue.h.
Referenced by dialogue::add_response(), create_option_line(), json_talk_response::gen_repeat_response(), json_talk_response::gen_responses(), dialogue::get_best_quit_response(), get_consequences(), json_talk_topic::get_directly_reachable_topics(), dialogue::opt(), and talk_response().
text
std::string talk_response::text
What the player character says (literally).
Should already be translated and will be displayed.
Definition at line 155 of file dialogue.h.
Referenced by create_option_line().
trial
talk_trial talk_response::trial
Definition at line 163 of file dialogue.h.
Referenced by create_option_line(), dialogue::get_best_quit_response(), get_consequences(), dialogue::opt(), and talk_response().
truefalse_condition
std::function<bool(dialogue &)> talk_response::truefalse_condition
Definition at line 161 of file dialogue.h.
Referenced by dialogue::add_response(), create_option_line(), and talk_response().
truetext
translation talk_response::truetext
Definition at line 159 of file dialogue.h.
Referenced by dialogue::add_response(), create_option_line(), json_talk_response::gen_responses(), and talk_response().
The documentation for this struct was generated from the following files:
src/dialogue.h
src/npctalk.cpp