Cataclysm DDA: shearing_entry Struct Reference
shearing_entry Struct Reference
#include <shearing.h>
Public Member Functions
shearing_roll roll (const monster &mon) const
void load (const JsonObject &jo)
Public Attributes
itype_id result
int amount = 0
int random_min = 0
int random_max = 0
float ratio_mass = 0.0f
float ratio_volume = 0.0f
bool was_loaded = false
Detailed Description
Definition at line 18 of file shearing.h.
Member Function Documentation
load()
void shearing_entry::load (const JsonObject & jo)
Definition at line 34 of file shearing.cpp.
 {
     mandatory( jo, was_loaded, "result", result );
     optional( jo, was_loaded, "ratio_mass", ratio_mass );
     ratio_mass = std::max( 0.00f, ratio_mass );
     optional( jo, was_loaded, "ratio_volume", ratio_volume );
     ratio_volume = std::max( 0.00f, ratio_volume );
     if( jo.has_int( "amount" ) ) {
         mandatory( jo, was_loaded, "amount", amount );
         amount = std::max( 0, amount );
     } else if( jo.has_array( "amount" ) ) {
         std::vector<int> amount_random = jo.get_int_array( "amount" );
         random_min = std::max( 0, amount_random[0] );
         random_max = std::max( 0, amount_random[1] );
         if( random_min > random_max ) {
             std::swap( random_min, random_max );
         }
     }
 }
References amount, JsonObject::get_int_array(), JsonObject::has_array(), JsonObject::has_int(), mandatory, max(), optional(), random_max, random_min, ratio_mass, ratio_volume, result, cata::swap(), and was_loaded.
Referenced by mtype::load().
roll()
shearing_roll shearing_entry::roll (const monster & mon) const
Definition at line 10 of file shearing.cpp.
 {
     shearing_roll roll;
     roll.result = result;
     roll.amount += amount;
     if( random_max ) {
         roll.amount += rng( random_min, random_max );
     }
     if( ratio_mass ) {
         float weight = units::to_kilogram( mon.get_weight() );
         roll.amount += static_cast<int>( ratio_mass * weight );
     }
     if( ratio_volume ) {
         float volume = units::to_liter( mon.get_volume() );
         roll.amount += static_cast<int>( ratio_volume * volume );
     }
     return roll;
 }
References shearing_roll::amount, amount, monster::get_volume(), monster::get_weight(), random_max, random_min, ratio_mass, ratio_volume, shearing_roll::result, result, rng(), units::to_kilogram(), and units::to_liter().
Member Data Documentation
amount
int shearing_entry::amount = 0
Definition at line 20 of file shearing.h.
Referenced by load(), and roll().
random_max
int shearing_entry::random_max = 0
Definition at line 22 of file shearing.h.
Referenced by load(), and roll().
random_min
int shearing_entry::random_min = 0
Definition at line 21 of file shearing.h.
Referenced by load(), and roll().
ratio_mass
float shearing_entry::ratio_mass = 0.0f
Definition at line 23 of file shearing.h.
Referenced by load(), and roll().
ratio_volume
float shearing_entry::ratio_volume = 0.0f
Definition at line 24 of file shearing.h.
Referenced by load(), and roll().
result
itype_id shearing_entry::result
Definition at line 19 of file shearing.h.
Referenced by load(), and roll().
was_loaded
bool shearing_entry::was_loaded = false
Definition at line 28 of file shearing.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/shearing.h
src/shearing.cpp