Cataclysm DDA: npc_follower_rules Struct Reference
npc_follower_rules Struct Reference
#include <npc.h>
Public Member Functions
npc_follower_rules ()
void serialize (JsonOut &json) const
void deserialize (const JsonObject &data)
bool has_flag (ally_rule test, bool check_override=true) const
void set_flag (ally_rule setit)
void clear_flag (ally_rule clearit)
void toggle_flag (ally_rule toggle)
void set_specific_override_state (ally_rule, bool state)
void toggle_specific_override_state (ally_rule rule, bool state)
bool has_override_enable (ally_rule test) const
void enable_override (ally_rule setit)
void disable_override (ally_rule clearit)
bool has_override (ally_rule test) const
void set_override (ally_rule setit)
void clear_override (ally_rule clearit)
void set_danger_overrides ()
void clear_overrides ()
Public Attributes
combat_engagement engagement
aim_rule aim = aim_rule::WHEN_CONVENIENT
cbm_recharge_rule cbm_recharge = cbm_recharge_rule::CBM_RECHARGE_SOME
cbm_reserve_rule cbm_reserve = cbm_reserve_rule::CBM_RESERVE_SOME
ally_rule flags = ally_rule::DEFAULT
ally_rule override_enable = ally_rule::DEFAULT
ally_rule overrides = ally_rule::DEFAULT
pimpl< auto_pickup::npc_settings > pickup_whitelist
Detailed Description
Definition at line 505 of file npc.h.
Constructor & Destructor Documentation
npc_follower_rules()
npc_follower_rules::npc_follower_rules ()
Definition at line 3608 of file npc.cpp.
 {
     engagement = combat_engagement::CLOSE;
     aim = aim_rule::WHEN_CONVENIENT;
     overrides = ally_rule::DEFAULT;
     override_enable = ally_rule::DEFAULT;
     set_flag( ally_rule::use_guns );
     clear_flag( ally_rule::use_grenades );
     set_flag( ally_rule::use_silent );
     set_flag( ally_rule::avoid_friendly_fire );
     clear_flag( ally_rule::allow_pick_up );
     clear_flag( ally_rule::allow_bash );
     clear_flag( ally_rule::allow_sleep );
     set_flag( ally_rule::allow_complain );
     set_flag( ally_rule::allow_pulp );
     set_flag( ally_rule::close_doors );
     set_flag( ally_rule::follow_close );
     clear_flag( ally_rule::avoid_doors );
     clear_flag( ally_rule::hold_the_line );
     set_flag( ally_rule::ignore_noise );
     clear_flag( ally_rule::forbid_engage );
     clear_flag( ally_rule::follow_distance_2 );
 }
References aim, allow_bash, allow_complain, allow_pick_up, allow_pulp, allow_sleep, avoid_doors, avoid_friendly_fire, clear_flag(), CLOSE, close_doors, DEFAULT, engagement, follow_close, follow_distance_2, forbid_engage, hold_the_line, ignore_noise, override_enable, overrides, set_flag(), use_grenades, use_guns, use_silent, and WHEN_CONVENIENT.
Member Function Documentation
clear_flag()
void npc_follower_rules::clear_flag (ally_rule clearit)
Definition at line 3653 of file npc.cpp.
 {
     flags = static_cast<ally_rule>( static_cast<int>( flags ) & ~static_cast<int>( clearit ) );
 }
References flags.
Referenced by talker_npc::clear_ai_rule(), npc_follower_rules(), and toggle_flag().
clear_override()
void npc_follower_rules::clear_override (ally_rule clearit)
Definition at line 3714 of file npc.cpp.
 {
     overrides = static_cast<ally_rule>( static_cast<int>( overrides ) &
                                         ~static_cast<int>( clearit ) );
 }
References overrides.
Referenced by set_specific_override_state(), toggle_specific_override_state(), and talk_function::wake_up().
clear_overrides()
void npc_follower_rules::clear_overrides ()
Definition at line 3734 of file npc.cpp.
 {
     overrides = ally_rule::DEFAULT;
     override_enable = ally_rule::DEFAULT;
 }
References DEFAULT, override_enable, and overrides.
Referenced by talk_function::clear_overrides().
deserialize()
void npc_follower_rules::deserialize (const JsonObject & data)
Definition at line 1791 of file savegame_json.cpp.
 {
     data.allow_omitted_members();
     int tmpeng = 0;
     data.read( "engagement", tmpeng );
     engagement = static_cast<combat_engagement>( tmpeng );
     int tmpaim = 0;
     data.read( "aim", tmpaim );
     aim = static_cast<aim_rule>( tmpaim );
     int tmpreserve = 50;
     data.read( "cbm_reserve", tmpreserve );
     cbm_reserve = static_cast<cbm_reserve_rule>( tmpreserve );
     int tmprecharge = 50;
     data.read( "cbm_recharge", tmprecharge );
     cbm_recharge = static_cast<cbm_recharge_rule>( tmprecharge );
     // deserialize the flags so they can be changed between save games
     for( const auto &rule : ally_rule_strs ) {
         bool tmpflag = false;
         // legacy to handle rules that were saved before overrides
         data.read( rule.first, tmpflag );
         if( tmpflag ) {
             set_flag( rule.second.rule );
         } else {
             clear_flag( rule.second.rule );
         }
         data.read( "rule_" + rule.first, tmpflag );
         if( tmpflag ) {
             set_flag( rule.second.rule );
         } else {
             clear_flag( rule.second.rule );
         }
         data.read( "override_enable_" + rule.first, tmpflag );
         if( tmpflag ) {
             enable_override( rule.second.rule );
         } else {
             disable_override( rule.second.rule );
         }
         data.read( "override_" + rule.first, tmpflag );
         if( tmpflag ) {
             set_override( rule.second.rule );
         } else {
             clear_override( rule.second.rule );
         }
         // This and the following two entries are for legacy save game handling.
         // "avoid_combat" was renamed "follow_close" to better reflect behavior.
         if( data.has_member( "rule_avoid_combat" ) ) {
             data.read( "rule_avoid_combat", tmpflag );
             if( tmpflag ) {
                 set_flag( ally_rule::follow_close );
             } else {
                 clear_flag( ally_rule::follow_close );
             }
         }
         if( data.has_member( "override_enable_avoid_combat" ) ) {
             data.read( "override_enable_avoid_combat", tmpflag );
             if( tmpflag ) {
                 enable_override( ally_rule::follow_close );
             } else {
                 disable_override( ally_rule::follow_close );
             }
         }
         if( data.has_member( "override_avoid_combat" ) ) {
             data.read( "override_avoid_combat", tmpflag );
             if( tmpflag ) {
                 set_override( ally_rule::follow_close );
             } else {
                 clear_override( ally_rule::follow_close );
             }
         }
     }
     data.read( "pickup_whitelist", *pickup_whitelist );
 }
References ally_rule_strs, item_pocket::data, follow_close, and oter_type_t::set_flag().
disable_override()
void npc_follower_rules::disable_override (ally_rule clearit)
Definition at line 3698 of file npc.cpp.
 {
     override_enable = static_cast<ally_rule>( static_cast<int>( override_enable ) &
                       ~static_cast<int>( clearit ) );
 }
References override_enable.
Referenced by toggle_specific_override_state().
enable_override()
void npc_follower_rules::enable_override (ally_rule setit)
Definition at line 3692 of file npc.cpp.
 {
     override_enable = static_cast<ally_rule>( static_cast<int>( override_enable ) |
                       static_cast<int>( setit ) );
 }
References override_enable.
Referenced by set_danger_overrides(), set_specific_override_state(), and talk_function::wake_up().
has_flag()
bool npc_follower_rules::has_flag (ally_rule test, bool check_override = true) const
Definition at line 3634 of file npc.cpp.
 {
     if( check_override && ( static_cast<int>( test ) & static_cast<int>( override_enable ) ) ) {
         // if the override is set and false, return false
         if( static_cast<int>( test ) & ~static_cast<int>( overrides ) ) {
             return false;
             // if the override is set and true, return true
         } else if( static_cast<int>( test ) & static_cast<int>( overrides ) ) {
             return true;
         }
     }
     return static_cast<int>( test ) & static_cast<int>( flags );
 }
References flags, override_enable, and overrides.
Referenced by npc::address_needs(), npc::alt_attack(), npc::assess_danger(), npc::can_open_door(), npc_attack_spell::can_use(), npc_attack_throw::can_use(), npc_attack_activate_item::can_use(), npc::check_or_use_weapon_cbm(), npc::complain_about(), npc_attack_throw::evaluate(), npc::evaluate_best_attack(), npc::evaluate_best_weapon(), npc_attack_spell::evaluate_tripoint(), npc_attack_gun::evaluate_tripoint(), npc_attack_throw::evaluate_tripoint(), npc::find_corpse_to_pulp(), npc::find_item(), npc::follow_distance(), npc::get_path_avoid(), npc::good_escape_direction(), npc::handle_sound(), talker_npc::has_ai_rule(), npc::move(), npc::move_to(), npc::pick_up_item(), npc::smash_ability(), toggle_flag(), npc_attack_gun::use(), npc_attack_throw::use(), and npc::wield_better_weapon().
has_override()
bool npc_follower_rules::has_override (ally_rule test) const
Definition at line 3704 of file npc.cpp.
 {
     return static_cast<int>( test ) & static_cast<int>( overrides );
 }
References overrides.
Referenced by npc_temp_orders_menu(), and toggle_specific_override_state().
has_override_enable()
bool npc_follower_rules::has_override_enable (ally_rule test) const
Definition at line 3687 of file npc.cpp.
 {
     return static_cast<int>( test ) & static_cast<int>( override_enable );
 }
References override_enable.
Referenced by talker_npc::has_ai_rule(), npc_temp_orders_menu(), and toggle_specific_override_state().
serialize()
void npc_follower_rules::serialize (JsonOut & json) const
Definition at line 1767 of file savegame_json.cpp.
 {
     json.start_object();
     json.member( "engagement", static_cast<int>( engagement ) );
     json.member( "aim", static_cast<int>( aim ) );
     json.member( "cbm_reserve", static_cast<int>( cbm_reserve ) );
     json.member( "cbm_recharge", static_cast<int>( cbm_recharge ) );
     // serialize the flags so they can be changed between save games
     for( const auto &rule : ally_rule_strs ) {
         json.member( "rule_" + rule.first, has_flag( rule.second.rule, false ) );
     }
     for( const auto &rule : ally_rule_strs ) {
         json.member( "override_enable_" + rule.first, has_override_enable( rule.second.rule ) );
     }
     for( const auto &rule : ally_rule_strs ) {
         json.member( "override_" + rule.first, has_override( rule.second.rule ) );
     }
     json.member( "pickup_whitelist", *pickup_whitelist );
     json.end_object();
 }
References ally_rule_strs, JsonOut::end_object(), oter_type_t::has_flag(), JsonOut::member(), and JsonOut::start_object().
set_danger_overrides()
void npc_follower_rules::set_danger_overrides ()
Definition at line 3720 of file npc.cpp.
 {
     overrides = ally_rule::DEFAULT;
     override_enable = ally_rule::DEFAULT;
     set_override( ally_rule::follow_close );
     set_override( ally_rule::avoid_doors );
     set_override( ally_rule::hold_the_line );
     enable_override( ally_rule::follow_close );
     enable_override( ally_rule::allow_sleep );
     enable_override( ally_rule::close_doors );
     enable_override( ally_rule::avoid_doors );
     enable_override( ally_rule::hold_the_line );
 }
References allow_sleep, avoid_doors, close_doors, DEFAULT, enable_override(), follow_close, hold_the_line, override_enable, overrides, and set_override().
set_flag()
void npc_follower_rules::set_flag (ally_rule setit)
Definition at line 3648 of file npc.cpp.
 {
     flags = static_cast<ally_rule>( static_cast<int>( flags ) | static_cast<int>( setit ) );
 }
References flags.
Referenced by npc_follower_rules(), talker_npc::set_ai_rule(), and toggle_flag().
set_override()
void npc_follower_rules::set_override (ally_rule setit)
Definition at line 3709 of file npc.cpp.
 {
     overrides = static_cast<ally_rule>( static_cast<int>( overrides ) | static_cast<int>( setit ) );
 }
References overrides.
Referenced by set_danger_overrides(), and set_specific_override_state().
set_specific_override_state()
void npc_follower_rules::set_specific_override_state (ally_rule rule, bool state)
Definition at line 3667 of file npc.cpp.
 {
     if( state ) {
         set_override( rule );
     } else {
         clear_override( rule );
     }
     enable_override( rule );
 }
References clear_override(), enable_override(), and set_override().
Referenced by toggle_specific_override_state().
toggle_flag()
void npc_follower_rules::toggle_flag (ally_rule toggle)
Definition at line 3658 of file npc.cpp.
 {
     if( has_flag( toggle ) ) {
         clear_flag( toggle );
     } else {
         set_flag( toggle );
     }
 }
References clear_flag(), has_flag(), and set_flag().
Referenced by talker_npc::toggle_ai_rule().
toggle_specific_override_state()
void npc_follower_rules::toggle_specific_override_state (ally_rule rule, bool state)
Definition at line 3677 of file npc.cpp.
 {
     if( has_override_enable( rule ) && has_override( rule ) == state ) {
         clear_override( rule );
         disable_override( rule );
     } else {
         set_specific_override_state( rule, state );
     }
 }
References clear_override(), disable_override(), has_override(), has_override_enable(), and set_specific_override_state().
Member Data Documentation
aim
aim_rule npc_follower_rules::aim = aim_rule::WHEN_CONVENIENT
Definition at line 507 of file npc.h.
Referenced by npc::confidence_mult(), talker_npc::has_ai_rule(), npc_follower_rules(), and talker_npc::set_ai_rule().
cbm_recharge
cbm_recharge_rule npc_follower_rules::cbm_recharge = cbm_recharge_rule::CBM_RECHARGE_SOME
Definition at line 508 of file npc.h.
Referenced by talker_npc::has_ai_rule(), talker_npc::set_ai_rule(), and npc::wants_to_recharge_cbm().
cbm_reserve
cbm_reserve_rule npc_follower_rules::cbm_reserve = cbm_reserve_rule::CBM_RESERVE_SOME
Definition at line 509 of file npc.h.
Referenced by npc::can_use_offensive_cbm(), npc::check_or_use_weapon_cbm(), talker_npc::has_ai_rule(), and talker_npc::set_ai_rule().
engagement
combat_engagement npc_follower_rules::engagement
Definition at line 506 of file npc.h.
Referenced by npc::assess_danger(), can_move(), can_move_melee(), talker_npc::has_ai_rule(), npc_follower_rules(), and talker_npc::set_ai_rule().
flags
ally_rule npc_follower_rules::flags = ally_rule::DEFAULT
Definition at line 510 of file npc.h.
Referenced by clear_flag(), has_flag(), and set_flag().
override_enable
ally_rule npc_follower_rules::override_enable = ally_rule::DEFAULT
Definition at line 511 of file npc.h.
Referenced by clear_overrides(), disable_override(), enable_override(), has_flag(), has_override_enable(), npc_follower_rules(), and set_danger_overrides().
overrides
ally_rule npc_follower_rules::overrides = ally_rule::DEFAULT
Definition at line 512 of file npc.h.
Referenced by clear_override(), clear_overrides(), has_flag(), has_override(), npc_follower_rules(), set_danger_overrides(), and set_override().
pickup_whitelist
pimpl<auto_pickup::npc_settings> npc_follower_rules::pickup_whitelist
Definition at line 514 of file npc.h.
Referenced by talker_npc::has_ai_rule(), npc::has_item_whitelist(), npc::item_name_whitelisted(), and talk_function::set_npc_pickup().
The documentation for this struct was generated from the following files:
src/npc.h
src/npc.cpp
src/savegame_json.cpp