Cataclysm DDA: item_penalties Struct Reference
item_penalties Struct Reference
#include <character_attire.h>
Public Member Functions
int badness () const
nc_color color_for_stacking_badness () const
Public Attributes
std::vector< bodypart_id > body_parts_with_stacking_penalty
std::vector< bodypart_id > body_parts_with_out_of_order_penalty
std::set< std::string > bad_items_within
Detailed Description
Definition at line 44 of file character_attire.h.
Member Function Documentation
badness()
int item_penalties::badness () const inline
Definition at line 49 of file character_attire.h.
{
         return !body_parts_with_stacking_penalty.empty() +
                !body_parts_with_out_of_order_penalty.empty();
     }
References body_parts_with_out_of_order_penalty, and body_parts_with_stacking_penalty.
Referenced by color_for_stacking_badness(), and layering_item_info::operator==().
color_for_stacking_badness()
nc_color item_penalties::color_for_stacking_badness () const
Definition at line 82 of file character_attire.cpp.
 {
     switch( badness() ) {
         case 0:
             return c_light_gray;
         case 1:
             return c_yellow;
         case 2:
             return c_light_red;
     }
     debugmsg( "Unexpected badness %d", badness() );
     return c_light_gray;
 }
References badness(), c_light_gray, c_light_red, c_yellow, and debugmsg.
Referenced by outfit::sort_armor().
Member Data Documentation
bad_items_within
std::set<std::string> item_penalties::bad_items_within
Definition at line 47 of file character_attire.h.
Referenced by anonymous_namespace{armor_layers.cpp}::draw_mid_pane().
body_parts_with_out_of_order_penalty
std::vector<bodypart_id> item_penalties::body_parts_with_out_of_order_penalty
Definition at line 46 of file character_attire.h.
Referenced by badness(), and anonymous_namespace{armor_layers.cpp}::draw_mid_pane().
body_parts_with_stacking_penalty
std::vector<bodypart_id> item_penalties::body_parts_with_stacking_penalty
Definition at line 45 of file character_attire.h.
Referenced by badness(), and anonymous_namespace{armor_layers.cpp}::draw_mid_pane().
The documentation for this struct was generated from the following files:
src/character_attire.h
src/character_attire.cpp