Cataclysm DDA: character_modifier Struct Reference
character_modifier Struct Reference
#include <character_modifier.h>
Public Types
enum mod_type { NONE , ADD , MULT }
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
float modifier (const Character &c, const skill_id &skill=skill_id::NULL_ID()) const
const character_modifier_id & getId () const
const translation & description () const
const mod_type & modifier_type () const
std::string mod_type_str () const
bool is_builtin () const
const std::map< limb_score_id, float > & use_limb_scores () const
Static Public Member Functions
static void load_character_modifiers (const JsonObject &jo, const std::string &src)
static void reset ()
static const std::vector< character_modifier > & get_all ()
Private Attributes
character_modifier_id id = character_modifier_id::NULL_ID()
std::map< limb_score_id, float > limbscores
mod_type limbscore_modop = MULT
std::vector< std::pair< character_modifier_id, mod_id > > src
body_part_type::type limbtype = body_part_type::type::num_types
translation desc = translation()
mod_type modtype = mod_type::NONE
float max_val = 0.0f
float min_val = 0.0f
float nominator = 0.0f
float denominator = 1.0f
float subtractor = 0.0f
int override_encumb = -1
int override_wounds = -1
std::string builtin
bool was_loaded = false
Friends
class generic_factory< character_modifier >
struct mod_tracker
Detailed Description
Definition at line 19 of file character_modifier.h.
Member Enumeration Documentation
mod_type
enum character_modifier::mod_type
Enumerator
NONE
ADD
MULT
Definition at line 21 of file character_modifier.h.
                       {
             NONE,
             ADD,
             MULT
         };
Member Function Documentation
description()
const translation& character_modifier::description () const inline
Definition at line 39 of file character_modifier.h.
{
             return desc;
         }
References desc.
get_all()
const std::vector< character_modifier > & character_modifier::get_all () static
Definition at line 67 of file character_modifier.cpp.
 {
     return character_modifier_factory.get_all();
 }
References anonymous_namespace{character_modifier.cpp}::character_modifier_factory.
Referenced by draw_health_summary(), and get_encumbrance_description().
getId()
const character_modifier_id& character_modifier::getId () const inline
Definition at line 35 of file character_modifier.h.
{
             return id;
         }
References id.
is_builtin()
bool character_modifier::is_builtin () const inline
Definition at line 49 of file character_modifier.h.
{
             return !builtin.empty();
         }
References builtin.
load()
void character_modifier::load (const JsonObject & jo, std::string_view src)
Definition at line 107 of file character_modifier.cpp.
 {
     mandatory( jo, was_loaded, "id", id );
     mandatory( jo, was_loaded, "description", desc );
     std::string modtypestr;
     optional( jo, was_loaded, "mod_type", modtypestr, "" );
     modtype = string_to_modtype( modtypestr );
     const JsonObject &jobj = jo.get_object( "value" );
     optional( jobj, was_loaded, "builtin", builtin, "" );
     if( builtin.empty() ) {
         limbscores.clear();
         if( jobj.has_array( "limb_score" ) ) {
             for( JsonValue jval : jobj.get_array( "limb_score" ) ) {
                 if( jval.test_array() ) {
                     JsonArray jsc = jval.get_array();
                     limbscores.emplace( limb_score_id( jsc.get_string( 0 ) ),
                                         static_cast<float>( jsc.get_float( 1 ) ) );
                 } else {
                     limbscores.emplace( limb_score_id( jval.get_string() ), 1.0f );
                 }
             }
         } else {
             limb_score_id ls;
             mandatory( jobj, was_loaded, "limb_score", ls );
             limbscores.emplace( ls, 1.0f );
         }
         std::string lsop;
         optional( jobj, was_loaded, "limb_score_op", lsop, "*" );
         limbscore_modop = string_to_modtype( lsop );
         optional( jobj, was_loaded, "limb_type", limbtype, body_part_type::type::num_types );
         if( jobj.has_member( "override_encumb" ) ) {
             bool over;
             mandatory( jobj, was_loaded, "override_encumb", over );
             override_encumb = over ? 1 : 0;
         }
         if( jobj.has_member( "override_wounds" ) ) {
             bool over;
             mandatory( jobj, was_loaded, "override_wounds", over );
             override_wounds = over ? 1 : 0;
         }
         min_val = load_float_or_maxmovecost( jobj, "min" );
         max_val = load_float_or_maxmovecost( jobj, "max" );
         optional( jobj, was_loaded, "nominator", nominator, 0.0f );
         optional( jobj, was_loaded, "denominator", denominator, 1.0f );
         if( std::abs( denominator ) < std::numeric_limits<float>::epsilon() ) {
             denominator = 1.0f;
             jobj.throw_error( "denominator cannot be set to 0" );
         }
         optional( jobj, was_loaded, "subtract", subtractor, 0.0f );
     }
 }
References abs(), builtin, denominator, desc, JsonArray::get_array(), JsonObject::get_array(), JsonArray::get_float(), JsonObject::get_object(), JsonArray::get_string(), JsonObject::has_array(), JsonObject::has_member(), limbscore_modop, limbscores, limbtype, load_float_or_maxmovecost(), mandatory, max_val, min_val, modtype, nominator, body_part_type::num_types, optional(), override_encumb, override_wounds, string_to_modtype(), subtractor, JsonObject::throw_error(), and was_loaded.
load_character_modifiers()
void character_modifier::load_character_modifiers (const JsonObject & jo, const std::string & src) static
Definition at line 57 of file character_modifier.cpp.
 {
     character_modifier_factory.load( jo, src );
 }
References anonymous_namespace{character_modifier.cpp}::character_modifier_factory, and src.
Referenced by DynamicDataLoader::initialize().
mod_type_str()
std::string character_modifier::mod_type_str () const
Definition at line 387 of file character_modifier.cpp.
 {
     switch( modtype ) {
         case ADD:
             return "+";
         case MULT:
             return "x";
         case NONE:
         default:
             break;
     }
     return std::string();
 }
References ADD, modtype, MULT, and NONE.
modifier()
float character_modifier::modifier (const Character & c, const skill_id & skill = skill_id::NULL_ID()) const
Definition at line 335 of file character_modifier.cpp.
 {
     // use builtin to calculate modifier
     if( !builtin.empty() ) {
         return call_builtin( builtin, c, skill );
     }
     float score = 0.0f;
     bool sc_assigned = false;
     for( const auto &sc : limbscores ) {
         float mod_sc = c.get_limb_score( sc.first, limbtype, override_encumb, override_wounds );
         mod_sc = limbscore_modop == MULT ? pow( mod_sc, sc.second ) : mod_sc * sc.second;
         if( !sc_assigned ) {
             score = mod_sc;
             sc_assigned = true;
             continue;
         }
         switch( limbscore_modop ) {
             case ADD:
                 score += mod_sc;
                 break;
             case NONE:
                 score = mod_sc;
                 break;
             case MULT:
             default:
                 score *= mod_sc;
         }
     }
     // score == 0
     if( score < std::numeric_limits<float>::epsilon() ) {
         return min_val > std::numeric_limits<float>::epsilon() ? min_val :
                max_val > std::numeric_limits<float>::epsilon() ? max_val : 0.0f;
     }
     if( nominator > std::numeric_limits<float>::epsilon() ) {
         score = ( nominator / denominator ) / score;
     } else {
         score /= denominator;
     }
     if( subtractor > std::numeric_limits<float>::epsilon() ) {
         score -= subtractor;
     }
     if( max_val > std::numeric_limits<float>::epsilon() ) {
         score = std::min( max_val, score );
     }
     if( min_val > std::numeric_limits<float>::epsilon() ) {
         score = std::max( min_val, score );
     }
     return score;
 }
References ADD, builtin, c, call_builtin(), denominator, limbscore_modop, limbscores, limbtype, max(), max_val, min(), min_val, MULT, nominator, NONE, override_encumb, override_wounds, and subtractor.
Referenced by limb_run_cost_modifier().
modifier_type()
const mod_type& character_modifier::modifier_type () const inline
Definition at line 43 of file character_modifier.h.
{
             return modtype;
         }
References modtype.
reset()
void character_modifier::reset () static
Definition at line 62 of file character_modifier.cpp.
 {
     character_modifier_factory.reset();
 }
References anonymous_namespace{character_modifier.cpp}::character_modifier_factory.
Referenced by DynamicDataLoader::unload_data().
use_limb_scores()
const std::map<limb_score_id, float>& character_modifier::use_limb_scores () const inline
Definition at line 53 of file character_modifier.h.
{
             return limbscores;
         }
References limbscores.
Friends And Related Function Documentation
generic_factory< character_modifier >
friend class generic_factory< character_modifier > friend
Definition at line 73 of file character_modifier.h.
mod_tracker
friend struct mod_tracker friend
Definition at line 75 of file character_modifier.h.
Member Data Documentation
builtin
std::string character_modifier::builtin private
Definition at line 72 of file character_modifier.h.
Referenced by is_builtin(), load(), and modifier().
denominator
float character_modifier::denominator = 1.0f private
Definition at line 68 of file character_modifier.h.
Referenced by load(), and modifier().
desc
translation character_modifier::desc = translation() private
Definition at line 63 of file character_modifier.h.
Referenced by description(), and load().
id
character_modifier_id character_modifier::id = character_modifier_id::NULL_ID() private
Definition at line 58 of file character_modifier.h.
Referenced by getId().
limbscore_modop
mod_type character_modifier::limbscore_modop = MULT private
Definition at line 60 of file character_modifier.h.
Referenced by load(), and modifier().
limbscores
std::map<limb_score_id, float> character_modifier::limbscores private
Definition at line 59 of file character_modifier.h.
Referenced by load(), modifier(), and use_limb_scores().
limbtype
body_part_type::type character_modifier::limbtype = body_part_type::type::num_types private
Definition at line 62 of file character_modifier.h.
Referenced by load(), and modifier().
max_val
float character_modifier::max_val = 0.0f private
Definition at line 65 of file character_modifier.h.
Referenced by load(), and modifier().
min_val
float character_modifier::min_val = 0.0f private
Definition at line 66 of file character_modifier.h.
Referenced by load(), and modifier().
modtype
mod_type character_modifier::modtype = mod_type::NONE private
Definition at line 64 of file character_modifier.h.
Referenced by load(), mod_type_str(), and modifier_type().
nominator
float character_modifier::nominator = 0.0f private
Definition at line 67 of file character_modifier.h.
Referenced by load(), and modifier().
override_encumb
int character_modifier::override_encumb = -1 private
Definition at line 70 of file character_modifier.h.
Referenced by load(), and modifier().
override_wounds
int character_modifier::override_wounds = -1 private
Definition at line 71 of file character_modifier.h.
Referenced by load(), and modifier().
src
std::vector<std::pair<character_modifier_id, mod_id> > character_modifier::src private
Definition at line 61 of file character_modifier.h.
Referenced by load_character_modifiers().
subtractor
float character_modifier::subtractor = 0.0f private
Definition at line 69 of file character_modifier.h.
Referenced by load(), and modifier().
was_loaded
bool character_modifier::was_loaded = false private
Definition at line 73 of file character_modifier.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/character_modifier.h
src/character_modifier.cpp