Cataclysm DDA: timed_event Struct Reference
timed_event Struct Reference
#include <timed_event.h>
Public Member Functions
timed_event (timed_event_type e_t, const time_point &w, int f_id, tripoint_abs_ms p, int s, std::string key)
timed_event (timed_event_type e_t, const time_point &w, int f_id, tripoint_abs_ms p, int s, std::string s_id, std::string key)
timed_event (timed_event_type e_t, const time_point &w, int f_id, tripoint_abs_ms p, int s, std::string s_id, submap sr, std::string key)
void actualize ()
void per_turn ()
Public Attributes
timed_event_type type = timed_event_type::NONE
time_point when = calendar::turn_zero
On which turn event should be happening.
int faction_id = -1
Which faction is responsible for handling this event.
tripoint_abs_sm map_point = tripoint_abs_sm(tripoint_min)
Where the event happens, in global submap coordinates.
tripoint_abs_ms map_square = tripoint_abs_ms(tripoint_min)
Where the event happens, in global map coordinates.
int strength = -1
How powerful the effect is.
std::string string_id
type of applied effect
std::string key
key to alter this event later
submap revert
Detailed Description
Definition at line 34 of file timed_event.h.
Constructor & Destructor Documentation
timed_event() [1/3]
timed_event::timed_event (timed_event_type e_t, const time_point & w, int f_id, tripoint_abs_ms p, int s, std::string key)
Definition at line 63 of file timed_event.cpp.
     : type( e_t )
     , when( w )
     , faction_id( f_id )
     , map_square( p )
     , strength( s )
     , key( std::move( key ) )
 {
     map_point = project_to<coords::sm>( map_square );
 }
References map_point, map_square, and strength.
timed_event() [2/3]
timed_event::timed_event (timed_event_type e_t, const time_point & w, int f_id, tripoint_abs_ms p, int s, std::string s_id, std::string key)
Definition at line 75 of file timed_event.cpp.
     : type( e_t )
     , when( w )
     , faction_id( f_id )
     , map_square( p )
     , strength( s )
     , string_id( std::move( s_id ) )
     , key( std::move( key ) )
 {
     map_point = project_to<coords::sm>( map_square );
 }
References map_point, map_square, and strength.
timed_event() [3/3]
timed_event::timed_event (timed_event_type e_t, const time_point & w, int f_id, tripoint_abs_ms p, int s, std::string s_id, submap sr, std::string key)
Definition at line 88 of file timed_event.cpp.
     : type( e_t )
     , when( w )
     , faction_id( f_id )
     , map_square( p )
     , strength( s )
     , string_id( std::move( s_id ) )
     , key( std::move( key ) )
     , revert( std::move( sr ) )
 {
     map_point = project_to<coords::sm>( map_square );
 }
References map_point, map_square, and strength.
Member Function Documentation
actualize()
void timed_event::actualize ()
Definition at line 102 of file timed_event.cpp.
 {
     avatar &player_character = get_avatar();
     map &here = get_map();
     switch( type ) {
         case timed_event_type::HELP:
             debugmsg( "Currently disabled while NPC and monster factions are being rewritten." );
             break;
         case timed_event_type::SPAWN_WYRMS: {
             if( here.get_abs_sub().z() >= 0 ) {
                 return;
             }
             get_memorial().add(
                 pgettext( "memorial_male", "Drew the attention of more dark wyrms!" ),
                 pgettext( "memorial_female", "Drew the attention of more dark wyrms!" ) );
             // 50% chance to spawn a dark wyrm near every orifice on the level.
             for( const tripoint &p : here.points_on_zlevel() ) {
                 if( here.ter( p ) == ter_id( "t_orifice" ) ) {
                     g->place_critter_around( mon_dark_wyrm, p, 1 );
                 }
             }
             // You could drop the flag, you know.
             if( player_character.has_amount( itype_petrified_eye, 1 ) ) {
                 sounds::sound( player_character.pos(), 60, sounds::sound_t::alert, _( "a tortured scream!" ), false,
                                "shout",
                                "scream_tortured" );
                 if( !player_character.is_deaf() ) {
                     add_msg( _( "The eye you're carrying lets out a tortured scream!" ) );
                     player_character.add_morale( MORALE_SCREAM, -15, 0, 30_minutes, 30_seconds );
                 }
             }
         }
         break;
         case timed_event_type::AMIGARA: {
             get_event_bus().send<event_type::angers_amigara_horrors>();
             int num_horrors = rng( 3, 5 );
             std::optional<tripoint> fault_point;
             bool horizontal = false;
             for( const tripoint &p : here.points_on_zlevel() ) {
                 if( here.ter( p ) == ter_t_fault ) {
                     fault_point = p;
                     horizontal = here.ter( p + tripoint_east ) == ter_t_fault ||
                                  here.ter( p + tripoint_west ) == ter_t_fault;
                     break;
                 }
             }
             for( int i = 0; fault_point && i < num_horrors; i++ ) {
                 for( int tries = 0; tries < 10; ++tries ) {
                     tripoint monp = player_character.pos();
                     if( horizontal ) {
                         monp.x = rng( fault_point->x, fault_point->x + 2 * SEEX - 8 );
                         for( int n = -1; n <= 1; n++ ) {
                             if( here.ter( point( monp.x, fault_point->y + n ) ) == ter_t_rock_floor ) {
                                 monp.y = fault_point->y + n;
                             }
                         }
                     } else {
                         // Vertical fault
                         monp.y = rng( fault_point->y, fault_point->y + 2 * SEEY - 8 );
                         for( int n = -1; n <= 1; n++ ) {
                             if( here.ter( point( fault_point->x + n, monp.y ) ) == ter_t_rock_floor ) {
                                 monp.x = fault_point->x + n;
                             }
                         }
                     }
                     if( g->place_critter_at( mon_amigara_horror, monp ) ) {
                         break;
                     }
                 }
             }
         }
         break;
         case timed_event_type::ROOTS_DIE:
             get_event_bus().send<event_type::destroys_triffid_grove>();
             for( const tripoint &p : here.points_on_zlevel() ) {
                 if( here.ter( p ) == ter_t_root_wall && one_in( 3 ) ) {
                     here.ter_set( p, ter_t_underbrush );
                 }
             }
             break;
         case timed_event_type::TEMPLE_OPEN: {
             get_event_bus().send<event_type::opens_temple>();
             bool saw_grate = false;
             for( const tripoint &p : here.points_on_zlevel() ) {
                 if( here.ter( p ) == ter_t_grate ) {
                     here.ter_set( p, ter_t_stairs_down );
                     if( !saw_grate && player_character.sees( p ) ) {
                         saw_grate = true;
                     }
                 }
             }
             if( saw_grate ) {
                 add_msg( _( "The nearby grates open to reveal a staircase!" ) );
             }
         }
         break;
         case timed_event_type::TEMPLE_FLOOD: {
             bool flooded = false;
             cata::mdarray<ter_id, point_bub_ms> flood_buf;
             for( const tripoint &p : here.points_on_zlevel() ) {
                 flood_buf[p.x][p.y] = here.ter( p );
             }
             for( const tripoint &p : here.points_on_zlevel() ) {
                 if( here.ter( p ) == ter_t_water_sh ) {
                     bool deepen = false;
                     for( const tripoint &w : points_in_radius( p, 1 ) ) {
                         if( here.ter( w ) == ter_t_water_dp ) {
                             deepen = true;
                             break;
                         }
                     }
                     if( deepen ) {
                         flood_buf[p.x][p.y] = ter_t_water_dp;
                         flooded = true;
                     }
                 } else if( here.ter( p ) == ter_t_rock_floor ) {
                     bool flood = false;
                     for( const tripoint &w : points_in_radius( p, 1 ) ) {
                         if( here.ter( w ) == ter_t_water_dp || here.ter( w ) == ter_t_water_sh ) {
                             flood = true;
                             break;
                         }
                     }
                     if( flood ) {
                         flood_buf[p.x][p.y] = ter_t_water_sh;
                         flooded = true;
                     }
                 }
             }
             if( !flooded ) {
                 // We finished flooding the entire chamber!
                 return;
             }
             // Check if we should print a message
             if( flood_buf[player_character.posx()][player_character.posy()] != here.ter(
                     player_character.pos() ) ) {
                 if( flood_buf[player_character.posx()][player_character.posy()] == ter_t_water_sh ) {
                     add_msg( m_warning, _( "Water quickly floods up to your knees." ) );
                     get_memorial().add(
                         pgettext( "memorial_male", "Water level reached knees." ),
                         pgettext( "memorial_female", "Water level reached knees." ) );
                 } else {
                     // Must be deep water!
                     add_msg( m_warning, _( "Water fills nearly to the ceiling!" ) );
                     get_memorial().add(
                         pgettext( "memorial_male", "Water level reached the ceiling." ),
                         pgettext( "memorial_female", "Water level reached the ceiling." ) );
                     avatar_action::swim( here, player_character, player_character.pos() );
                 }
             }
             // flood_buf is filled with correct tiles; now copy them back to here
             for( const tripoint &p : here.points_on_zlevel() ) {
                 here.ter_set( p, flood_buf[p.x][p.y] );
             }
             get_timed_events().add( timed_event_type::TEMPLE_FLOOD,
                                     calendar::turn + rng( 2_turns, 3_turns ) );
         }
         break;
         case timed_event_type::TEMPLE_SPAWN: {
             static const std::array<mtype_id, 4> temple_monsters = { {
                     mon_sewer_snake, mon_dermatik, mon_spider_widow_giant, mon_spider_cellar_giant
                 }
             };
             const mtype_id &montype = random_entry( temple_monsters );
             g->place_critter_around( montype, player_character.pos(), 2 );
         }
         break;
         case timed_event_type::DSA_ALRP_SUMMON: {
             const tripoint_abs_sm u_pos = player_character.global_sm_location();
             if( rl_dist( u_pos, map_point ) <= 4 ) {
                 const tripoint spot = here.getlocal( project_to<coords::ms>( map_point ).raw() );
                 monster dispatcher( mon_dsa_alien_dispatch );
                 fake_spell summoning( spell_dks_summon_alrp, true, 12 );
                 summoning.get_spell( player_character ).cast_all_effects( dispatcher, spot );
             } else {
                 const tripoint_abs_omt omt_point = project_to<coords::omt>( map_point );
                 tinymap mx_map;
                 mx_map.load( omt_point, false );
                 MapExtras::apply_function( map_extra_mx_dsa_alrp, mx_map, omt_point );
                 g->load_npcs();
                 here.invalidate_map_cache( map_point.z() );
             }
         }
         break;
         case timed_event_type::TRANSFORM_RADIUS: {
             map tm;
             tm.load( project_to<coords::sm>( map_square - point{ strength, strength} ), false );
             tm.transform_radius( ter_furn_transform_id( string_id ), strength,
                                  map_square );
             break;
         }
         case timed_event_type::UPDATE_MAPGEN:
             run_mapgen_update_func(
                 update_mapgen_id( string_id ), project_to<coords::omt>( map_point ), {}, nullptr );
             set_queued_points();
             get_map().invalidate_map_cache( map_point.z() );
             break;
         case timed_event_type::REVERT_SUBMAP: {
             submap *sm = MAPBUFFER.lookup_submap( map_point );
             sm->revert_submap( revert );
             get_map().invalidate_map_cache( map_point.z() );
             break;
         }
         default:
             // Nothing happens for other events
             break;
     }
 }
References _, memorial_logger::add(), timed_event_manager::add(), Character::add_morale(), add_msg(), sounds::alert, AMIGARA, angers_amigara_horrors, MapExtras::apply_function(), spell::cast_all_effects(), debugmsg, destroys_triffid_grove, DSA_ALRP_SUMMON, g, map::get_abs_sub(), get_avatar(), get_event_bus(), get_map(), get_memorial(), fake_spell::get_spell(), get_timed_events(), map::getlocal(), Creature::global_sm_location(), visitable::has_amount(), HELP, map::invalidate_map_cache(), Character::is_deaf(), itype_petrified_eye, tinymap::load(), map::load(), mapbuffer::lookup_submap(), m_warning, map_extra_mx_dsa_alrp, map_point, map_square, MAPBUFFER, mon_amigara_horror, mon_dark_wyrm, mon_dermatik, mon_dsa_alien_dispatch, mon_sewer_snake, mon_spider_cellar_giant, mon_spider_widow_giant, MORALE_SCREAM, one_in(), opens_temple, pgettext, points_in_radius(), map::points_on_zlevel(), Creature::pos(), Creature::posx(), Creature::posy(), random_entry(), revert, REVERT_SUBMAP, rl_dist(), rng(), ROOTS_DIE, run_mapgen_update_func(), Character::sees(), SEEX, SEEY, event_bus::send(), set_queued_points(), coords::sm, sounds::sound(), SPAWN_WYRMS, spell_dks_summon_alrp, strength, avatar_action::swim(), TEMPLE_FLOOD, TEMPLE_OPEN, TEMPLE_SPAWN, map::ter(), ter_furn_transform_id, map::ter_set(), ter_t_fault, ter_t_grate, ter_t_rock_floor, ter_t_root_wall, ter_t_stairs_down, ter_t_underbrush, ter_t_water_dp, ter_t_water_sh, map::transform_radius(), TRANSFORM_RADIUS, tripoint_east, tripoint_west, calendar::turn, type, UPDATE_MAPGEN, tripoint::x, tripoint::y, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
per_turn()
void timed_event::per_turn ()
Definition at line 325 of file timed_event.cpp.
 {
     Character &player_character = get_player_character();
     map &here = get_map();
     switch( type ) {
         case timed_event_type::SPAWN_WYRMS:
             if( here.get_abs_sub().z() >= 0 ) {
                 when -= 1_turns;
                 return;
             }
             if( calendar::once_every( time_duration::from_seconds( rng( 2, 3 ) ) ) &&
                 !player_character.is_deaf() ) {
                 add_msg( m_warning, _( "You hear screeches from the rock above and around you!" ) );
             }
             break;
         case timed_event_type::AMIGARA:
             if( calendar::once_every( time_duration::from_seconds( rng( 2, 3 ) ) ) ) {
                 add_msg( m_warning, _( "The entire cavern shakes!" ) );
             }
             break;
         case timed_event_type::AMIGARA_WHISPERS: {
             bool faults = false;
             for( const tripoint &p : here.points_on_zlevel() ) {
                 if( here.ter( p ) == ter_t_fault ) {
                     faults = true;
                     break;
                 }
             }
             if( calendar::once_every( time_duration::from_seconds( 10 ) ) && faults ) {
                 add_msg( m_info, _( "You hear someone whispering \"%s\"" ),
                          SNIPPET.random_from_category( "amigara_whispers" ).value_or( translation() ) );
             }
         }
         break;
         case timed_event_type::TEMPLE_OPEN:
             if( calendar::once_every( time_duration::from_seconds( rng( 2, 3 ) ) ) ) {
                 add_msg( m_warning, _( "The earth rumbles." ) );
             }
             break;
         default:
             // Nothing happens for other events
             break;
     }
 }
References _, add_msg(), AMIGARA, AMIGARA_WHISPERS, anonymous_namespace{item_tname.cpp}::faults(), time_duration::from_seconds(), map::get_abs_sub(), get_map(), get_player_character(), Character::is_deaf(), m_info, m_warning, calendar::once_every(), map::points_on_zlevel(), snippet_library::random_from_category(), rng(), SNIPPET, SPAWN_WYRMS, TEMPLE_OPEN, map::ter(), ter_t_fault, type, when, and coords::coord_point_mut< Point, Subpoint, InBounds >::z().
Member Data Documentation
faction_id
int timed_event::faction_id = -1
Which faction is responsible for handling this event.
Definition at line 39 of file timed_event.h.
key
std::string timed_event::key
key to alter this event later
Definition at line 49 of file timed_event.h.
map_point
tripoint_abs_sm timed_event::map_point = tripoint_abs_sm(tripoint_min)
Where the event happens, in global submap coordinates.
Definition at line 41 of file timed_event.h.
Referenced by actualize(), and timed_event().
map_square
tripoint_abs_ms timed_event::map_square = tripoint_abs_ms(tripoint_min)
Where the event happens, in global map coordinates.
Definition at line 43 of file timed_event.h.
Referenced by actualize(), and timed_event().
revert
submap timed_event::revert
Definition at line 51 of file timed_event.h.
Referenced by actualize().
strength
int timed_event::strength = -1
How powerful the effect is.
Definition at line 45 of file timed_event.h.
Referenced by actualize().
string_id
std::string timed_event::string_id
type of applied effect
Definition at line 47 of file timed_event.h.
type
timed_event_type timed_event::type = timed_event_type::NONE
Definition at line 35 of file timed_event.h.
Referenced by actualize(), and per_turn().
when
time_point timed_event::when = calendar::turn_zero
On which turn event should be happening.
Definition at line 37 of file timed_event.h.
Referenced by per_turn().
The documentation for this struct was generated from the following files:
src/timed_event.h
src/timed_event.cpp