Cataclysm DDA: forest_biome_component Struct Reference
forest_biome_component Struct Reference
#include <regional_settings.h>
Public Member Functions
void finalize ()
forest_biome_component ()=default
Public Attributes
std::map< std::string, int > unfinalized_types
weighted_int_list< ter_furn_id > types
int sequence = 0
int chance = 0
bool clear_types = false
Detailed Description
Definition at line 111 of file regional_settings.h.
Constructor & Destructor Documentation
forest_biome_component()
forest_biome_component::forest_biome_component () default
Member Function Documentation
finalize()
void forest_biome_component::finalize ()
Definition at line 854 of file regional_settings.cpp.
 {
     for( const std::pair<const std::string, int> &pr : unfinalized_types ) {
         ter_furn_id tf_id;
         tf_id.ter = ter_str_id::NULL_ID().id();
         tf_id.furn = furn_str_id::NULL_ID();
         const ter_str_id tid( pr.first );
         const furn_str_id fid( pr.first );
         if( tid.is_valid() ) {
             tf_id.ter = tid.id();
         } else if( fid.is_valid() ) {
             tf_id.furn = fid.id();
         } else {
             continue;
         }
         types.add( tf_id, pr.second );
     }
 }
References weighted_list< W, T >::add(), ter_furn_id::furn, string_id< T >::id(), string_id< T >::is_valid(), string_id< furn_t >::NULL_ID(), string_id< ter_t >::NULL_ID(), ter_furn_id::ter, types, and unfinalized_types.
Member Data Documentation
chance
int forest_biome_component::chance = 0
Definition at line 115 of file regional_settings.h.
Referenced by load_forest_biome_component().
clear_types
bool forest_biome_component::clear_types = false
Definition at line 116 of file regional_settings.h.
Referenced by load_forest_biome_component().
sequence
int forest_biome_component::sequence = 0
Definition at line 114 of file regional_settings.h.
Referenced by load_forest_biome_component().
types
weighted_int_list<ter_furn_id> forest_biome_component::types
Definition at line 113 of file regional_settings.h.
Referenced by finalize().
unfinalized_types
std::map<std::string, int> forest_biome_component::unfinalized_types
Definition at line 112 of file regional_settings.h.
Referenced by finalize(), and load_forest_biome_component().
The documentation for this struct was generated from the following files:
src/regional_settings.h
src/regional_settings.cpp