Cataclysm DDA: item::extended_photo_def Struct Reference
item::extended_photo_def Struct Reference
#include <item.h>
Public Member Functions
void deserialize (const JsonObject &obj)
void serialize (JsonOut &jsout) const
Public Attributes
int quality = 0
std::string name
std::string description
Detailed Description
Definition at line 1924 of file item.h.
Member Function Documentation
deserialize()
void item::extended_photo_def::deserialize (const JsonObject & obj)
Definition at line 5469 of file iuse.cpp.
 {
     quality = obj.get_int( "quality" );
     name = obj.get_string( "name" );
     description = obj.get_string( "description" );
 }
References description, JsonObject::get_int(), JsonObject::get_string(), and name.
serialize()
void item::extended_photo_def::serialize (JsonOut & jsout) const
Definition at line 5476 of file iuse.cpp.
 {
     jsout.start_object();
     jsout.member( "quality", quality );
     jsout.member( "name", name );
     jsout.member( "description", description );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), om_direction::name(), and JsonOut::start_object().
Member Data Documentation
description
std::string item::extended_photo_def::description
Definition at line 1927 of file item.h.
Referenced by deserialize(), and photo_def_for_camera_point().
name
std::string item::extended_photo_def::name
Definition at line 1926 of file item.h.
Referenced by iuse::camera(), deserialize(), and photo_def_for_camera_point().
quality
int item::extended_photo_def::quality = 0
Definition at line 1925 of file item.h.
Referenced by iuse::camera().
The documentation for this struct was generated from the following files:
src/item.h
src/iuse.cpp