Cataclysm DDA: mutation_category_trait Struct Reference
mutation_category_trait Struct Reference
#include <mutation.h>
Public Member Functions
std::string name () const
std::string mutagen_message () const
std::string memorial_message_male () const
std::string memorial_message_female () const
Static Public Member Functions
static const std::map< mutation_category_id, mutation_category_trait > & get_all ()
static const mutation_category_trait & get_category (const mutation_category_id &category_id)
static void reset ()
static void check_consistency ()
static void load (const JsonObject &jsobj)
Public Attributes
bool wip = false
bool skip_test = false
mutation_category_id id
trait_id threshold_mut
int threshold_min = 2200
vitamin_id vitamin
int base_removal_chance = 100
float base_removal_cost_mul = 3.0f
Private Attributes
translation raw_name
translation raw_mutagen_message
std::string raw_memorial_message
Detailed Description
Definition at line 505 of file mutation.h.
Member Function Documentation
check_consistency()
void mutation_category_trait::check_consistency () static
Definition at line 128 of file mutation_data.cpp.
 {
     for( const auto &pr : mutation_category_traits ) {
         const mutation_category_trait &cat = pr.second;
         if( !cat.threshold_mut.is_empty() && !cat.threshold_mut.is_valid() ) {
             debugmsg( "Mutation category %s has threshold mutation %s, which does not exist",
                       cat.id.c_str(), cat.threshold_mut.c_str() );
         }
     }
 }
References string_id< T >::c_str(), debugmsg, id, string_id< T >::is_empty(), string_id< T >::is_valid(), mutation_category_traits, and threshold_mut.
Referenced by DynamicDataLoader::check_consistency().
get_all()
const std::map< mutation_category_id, mutation_category_trait > & mutation_category_trait::get_all () static
Definition at line 112 of file mutation_data.cpp.
 {
     return mutation_category_traits;
 }
References mutation_category_traits.
Referenced by Character::get_vitamin_weighted_categories(), and npc_class::load().
get_category()
const mutation_category_trait & mutation_category_trait::get_category (const mutation_category_id & category_id) static
Definition at line 117 of file mutation_data.cpp.
 {
     return mutation_category_traits.find( category_id )->second;
 }
References mutation_category_traits.
Referenced by computer_session::action_list_mutations(), debug_menu::character_edit_menu(), Character::mutate(), Character::mutate_category(), Character::mutate_towards(), Character::mutation_selector(), memorial_logger::notify(), and Character::test_crossing_threshold().
load()
void mutation_category_trait::load (const JsonObject & jsobj) static
Definition at line 70 of file mutation_data.cpp.
 {
     mutation_category_trait new_category;
     jsobj.read( "id", new_category.id, true );
     jsobj.get_member( "name" ).read( new_category.raw_name );
     new_category.threshold_mut = trait_id( jsobj.get_string( "threshold_mut" ) );
     jsobj.get_member( "mutagen_message" ).read( new_category.raw_mutagen_message );
     new_category.wip = jsobj.get_bool( "wip", false );
     new_category.skip_test = jsobj.get_bool( "skip_test", false );
     static_cast<void>( translate_marker_context( "memorial_male", "Crossed a threshold" ) );
     static_cast<void>( translate_marker_context( "memorial_female", "Crossed a threshold" ) );
     optional( jsobj, false, "memorial_message", new_category.raw_memorial_message,
               text_style_check_reader(), "Crossed a threshold" );
     new_category.vitamin = vitamin_id( jsobj.get_string( "vitamin", "null" ) );
     optional( jsobj, false, "threshold_min", new_category.threshold_min, 2200 );
     optional( jsobj, false, "base_removal_chance", new_category.base_removal_chance, 100 );
     optional( jsobj, false, "base_removal_cost_mul", new_category.base_removal_cost_mul, 3.0f );
     mutation_category_traits[new_category.id] = new_category;
 }
References base_removal_chance, base_removal_cost_mul, JsonObject::get_bool(), JsonObject::get_member(), JsonObject::get_string(), id, mutation_category_traits, optional(), raw_memorial_message, raw_mutagen_message, raw_name, JsonValue::read(), JsonObject::read(), skip_test, threshold_min, threshold_mut, trait_id, translate_marker_context, vitamin, and wip.
Referenced by DynamicDataLoader::initialize().
memorial_message_female()
std::string mutation_category_trait::memorial_message_female () const
Definition at line 107 of file mutation_data.cpp.
 {
     return pgettext( "memorial_female", raw_memorial_message.c_str() );
 }
References pgettext, and raw_memorial_message.
memorial_message_male()
std::string mutation_category_trait::memorial_message_male () const
Definition at line 102 of file mutation_data.cpp.
 {
     return pgettext( "memorial_male", raw_memorial_message.c_str() );
 }
References pgettext, and raw_memorial_message.
mutagen_message()
std::string mutation_category_trait::mutagen_message () const
Definition at line 97 of file mutation_data.cpp.
 {
     return raw_mutagen_message.translated();
 }
References raw_mutagen_message, and translation::translated().
name()
std::string mutation_category_trait::name () const
Definition at line 92 of file mutation_data.cpp.
 {
     return raw_name.translated();
 }
References raw_name, and translation::translated().
reset()
void mutation_category_trait::reset () static
Definition at line 123 of file mutation_data.cpp.
 {
     mutation_category_traits.clear();
 }
References mutation_category_traits.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
base_removal_chance
int mutation_category_trait::base_removal_chance = 100
Definition at line 532 of file mutation.h.
Referenced by load().
base_removal_cost_mul
float mutation_category_trait::base_removal_cost_mul = 3.0f
Definition at line 534 of file mutation.h.
Referenced by load().
id
mutation_category_id mutation_category_trait::id
Definition at line 524 of file mutation.h.
Referenced by check_consistency(), load(), and Character::test_crossing_threshold().
raw_memorial_message
std::string mutation_category_trait::raw_memorial_message private
Definition at line 511 of file mutation.h.
Referenced by load(), memorial_message_female(), and memorial_message_male().
raw_mutagen_message
translation mutation_category_trait::raw_mutagen_message private
Definition at line 509 of file mutation.h.
Referenced by load(), and mutagen_message().
raw_name
translation mutation_category_trait::raw_name private
Definition at line 507 of file mutation.h.
Referenced by load(), and name().
skip_test
bool mutation_category_trait::skip_test = false
Definition at line 522 of file mutation.h.
Referenced by load().
threshold_min
int mutation_category_trait::threshold_min = 2200
Definition at line 528 of file mutation.h.
Referenced by load().
threshold_mut
trait_id mutation_category_trait::threshold_mut
Definition at line 526 of file mutation.h.
Referenced by check_consistency(), load(), and Character::test_crossing_threshold().
vitamin
vitamin_id mutation_category_trait::vitamin
Definition at line 530 of file mutation.h.
Referenced by load(), Character::mutate(), Character::mutate_category(), and Character::test_crossing_threshold().
wip
bool mutation_category_trait::wip = false
Definition at line 520 of file mutation.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/mutation.h
src/mutation_data.cpp