Cataclysm DDA: bodygraph_display Struct Reference
bodygraph_display Struct Reference
Public Member Functions
bodygraph_display ()=delete
bodygraph_display (const bodygraph_display &)=delete
bodygraph_display (const bodygraph_display &&)=delete
bodygraph_display (const Character *u, const bodygraph_id &id)
shared_ptr_fast< ui_adaptor > create_or_get_ui_adaptor ()
void prepare_partlist ()
void prepare_infolist ()
void prepare_infotext (bool reset_pos)
void init_ui_windows ()
void draw_borders ()
void draw_partlist ()
void draw_graph ()
void draw_info ()
void display ()
Public Attributes
const Character * u
bodygraph_id id
input_context ctxt
weak_ptr_fast< ui_adaptor > ui
border_helper bh_borders
catacurses::window w_border
catacurses::window w_partlist
catacurses::window w_graph
catacurses::window w_info
std::vector< part_tuple > partlist
bodygraph_info info
std::vector< std::string > info_txt
int all_height = 0
int all_width = 0
int partlist_width = 0
int info_width = 0
int sel_part = 0
int top_part = 0
int top_info = 0
Detailed Description
Definition at line 243 of file bodygraph.cpp.
Constructor & Destructor Documentation
bodygraph_display() [1/4]
bodygraph_display::bodygraph_display () delete
bodygraph_display() [2/4]
bodygraph_display::bodygraph_display (const bodygraph_display &) delete
bodygraph_display() [3/4]
bodygraph_display::bodygraph_display (const bodygraph_display &&) delete
bodygraph_display() [4/4]
bodygraph_display::bodygraph_display (const Character * u, const bodygraph_id & id) explicit
Definition at line 286 of file bodygraph.cpp.
                                                                                  :
     u( u ), id( id ), ctxt( "BODYGRAPH" )
 {
     if( id.is_null() ) {
         this->id = bodygraph_full_body;
     }
     ctxt.register_navigate_ui_list();
     ctxt.register_leftright();
     ctxt.register_action( "SCROLL_INFOBOX_UP" );
     ctxt.register_action( "SCROLL_INFOBOX_DOWN" );
     ctxt.register_action( "PAGE_UP" );
     ctxt.register_action( "PAGE_DOWN" );
     ctxt.register_action( "CONFIRM" );
     ctxt.register_action( "QUIT" );
 }
References bodygraph_full_body, ctxt, input_context::register_action(), input_context::register_leftright(), input_context::register_navigate_ui_list(), and u.
Member Function Documentation
create_or_get_ui_adaptor()
shared_ptr_fast< ui_adaptor > bodygraph_display::create_or_get_ui_adaptor ()
Definition at line 581 of file bodygraph.cpp.
 {
     shared_ptr_fast<ui_adaptor> current_ui = ui.lock();
     if( !current_ui ) {
         ui = current_ui = make_shared_fast<ui_adaptor>();
         current_ui->on_screen_resize( [this]( ui_adaptor & cui ) {
             init_ui_windows();
             info_txt.clear();
             if( !partlist.empty() && std::get<3>( partlist[sel_part] ) ) {
                 prepare_infotext( false );
             }
             cui.position_from_window( w_border );
         } );
         current_ui->mark_resize();
         current_ui->on_redraw( [this]( const ui_adaptor & ) {
             draw_borders();
             draw_partlist();
             draw_graph();
             draw_info();
         } );
     }
     return current_ui;
 }
References draw_borders(), draw_graph(), draw_info(), draw_partlist(), info_txt, init_ui_windows(), partlist, ui_adaptor::position_from_window(), prepare_infotext(), sel_part, and w_border.
Referenced by display().
display()
void bodygraph_display::display ()
Definition at line 605 of file bodygraph.cpp.
 {
     shared_ptr_fast<ui_adaptor> current_ui = create_or_get_ui_adaptor();
     prepare_partlist();
     prepare_infolist();
     bool done = false;
     while( !done ) {
         ui_manager::redraw();
         std::string action = ctxt.handle_input();
         if( action == "QUIT" || ( action == "LEFT" && id != bodygraph_full_body ) ) {
             done = true;
         } else if( action == "CONFIRM" || action == "RIGHT" ) {
             if( !!std::get<2>( partlist[sel_part] ) ) {
                 bodygraph_id nextgraph = std::get<2>( partlist[sel_part] )->nested_graph;
                 if( !nextgraph.is_null() ) {
                     display_bodygraph( *u, nextgraph );
                     prepare_infolist();
                 }
             }
         } else if( action == "SCROLL_INFOBOX_UP" || action == "PAGE_UP" ) {
             top_info--;
         } else if( action == "SCROLL_INFOBOX_DOWN" || action == "PAGE_DOWN" ) {
             top_info++;
         } else if( navigate_ui_list( action, sel_part, 3, partlist.size(), true ) ) {
             prepare_infolist();
         }
         if( static_cast<int>( info_txt.size() ) >= all_height - 2 ) {
             top_info = clamp( top_info, 0, static_cast<int>( info_txt.size() ) - ( all_height - 2 ) );
         } else {
             top_info = 0;
         }
         if( sel_part < top_part ) {
             top_part = sel_part;
         } else if( sel_part >= top_part + ( all_height - 2 ) ) {
             top_part = sel_part - ( all_height - 3 );
         }
     }
 }
References action, all_height, bodygraph_full_body, clamp(), create_or_get_ui_adaptor(), ctxt, display_bodygraph(), input_context::handle_input(), info_txt, string_id< T >::is_null(), navigate_ui_list(), partlist, prepare_infolist(), prepare_partlist(), ui_manager::redraw(), sel_part, top_info, top_part, and u.
Referenced by display_bodygraph().
draw_borders()
void bodygraph_display::draw_borders ()
Definition at line 336 of file bodygraph.cpp.
 {
     bh_borders.draw_border( w_border, c_white );
     const int first_win_width = partlist_width;
     auto center_txt_start = [&first_win_width]( const std::string_view txt ) {
         return 2 + first_win_width + ( BPGRAPH_MAXCOLS / 2 - utf8_width( txt, true ) / 2 );
     };
     // window title
     const std::string title_txt = string_format( "< %s >", colorize( _( "Body status" ), c_yellow ) );
     trim_and_print( w_border, point( center_txt_start( title_txt ), 0 ),
                     BPGRAPH_MAXCOLS, c_white, title_txt );
     // body part subtitle
     if( id->parent_bp.has_value() ) {
         const std::string bpname = string_format( "\\_ %s _/",
                                    colorize( to_upper_case( id->parent_bp.value()->name.translated() ), c_yellow ) );
         trim_and_print( w_border, point( center_txt_start( bpname ), 1 ),
                         BPGRAPH_MAXCOLS, c_white, bpname );
     }
     scrollbar()
     .border_color( c_white )
     .offset_x( 0 )
     .offset_y( 1 )
     .content_size( partlist.size() )
     .viewport_pos( top_part )
     .viewport_size( all_height - 2 )
     .apply( w_border );
     scrollbar()
     .border_color( c_white )
     .offset_x( all_width - 1 )
     .offset_y( 1 )
     .content_size( info_txt.size() )
     .viewport_pos( top_info )
     .viewport_size( all_height - 2 )
     .apply( w_border );
     wnoutrefresh( w_border );
 }
References _, all_height, all_width, scrollbar::apply(), bh_borders, scrollbar::border_color(), BPGRAPH_MAXCOLS, c_white, c_yellow, colorize(), scrollbar::content_size(), border_helper::draw_border(), id, info_txt, scrollbar::offset_x(), scrollbar::offset_y(), bodygraph::parent_bp, partlist, partlist_width, point, string_format(), to_upper_case(), top_info, top_part, trim_and_print(), utf8_width(), scrollbar::viewport_pos(), scrollbar::viewport_size(), w_border, and catacurses::wnoutrefresh().
Referenced by create_or_get_ui_adaptor().
draw_graph()
void bodygraph_display::draw_graph ()
Definition at line 408 of file bodygraph.cpp.
 {
     werase( w_graph );
     const bodygraph_part *selected_graph = std::get<2>( partlist[sel_part] );
     auto process_sym = [&]( const bodygraph_part * bgp, const std::string & sym ) {
         return colorize( sym, bgp != nullptr && selected_graph == bgp ?
                          selected_graph->sel_color : id->fill_color );
     };
     std::vector<std::string> rows = get_bodygraph_lines( *u, process_sym, id );
     for( int y = 0; static_cast<size_t>( y ) < rows.size(); y++ ) {
         trim_and_print( w_graph, point( 0, y ), BPGRAPH_MAXCOLS, c_white, rows[y] );
     }
     wnoutrefresh( w_graph );
 }
References BPGRAPH_MAXCOLS, c_white, colorize(), bodygraph::fill_color, get_bodygraph_lines(), id, partlist, point, bodygraph_part::sel_color, sel_part, trim_and_print(), u, w_graph, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by create_or_get_ui_adaptor().
draw_info()
void bodygraph_display::draw_info ()
Definition at line 425 of file bodygraph.cpp.
 {
     werase( w_info );
     if( std::get<3>( partlist[sel_part] ) ) {
         int y = 0;
         for( unsigned i = top_info; i < info_txt.size() && y < all_height - 2; i++, y++ ) {
             if( info_txt[i] == "--" ) {
                 for( int x = 1; x < info_width - 2; x++ ) {
                     mvwputch( w_info, point( x, y ), c_dark_gray, LINE_OXOX );
                 }
             } else {
                 trim_and_print( w_info, point( 1, y ), info_width - 2, c_white, info_txt[i] );
             }
         }
     }
     wnoutrefresh( w_info );
 }
References all_height, c_dark_gray, c_white, info_txt, info_width, LINE_OXOX, mvwputch(), partlist, point, sel_part, top_info, trim_and_print(), w_info, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by create_or_get_ui_adaptor().
draw_partlist()
void bodygraph_display::draw_partlist ()
Definition at line 379 of file bodygraph.cpp.
 {
     werase( w_partlist );
     int y = 0;
     for( int i = top_part; y < all_height - 2 && i < static_cast<int>( partlist.size() ); i++ ) {
         const auto bgt = partlist[i];
         std::string txt = !std::get<1>( bgt ) ?
                           std::get<0>( bgt )->name.translated() :
                           std::get<1>( bgt )->name.translated();
         txt = trim_by_length( uppercase_first_letter( txt ), partlist_width - 2 );
         txt = left_justify( txt, partlist_width - 2, true );
         txt.insert( 0, colorize( i == sel_part ? ">" : " ", c_yellow ) );
         txt.append( !std::get<2>( bgt )->nested_graph.is_null() ?
                     colorize( ">", i == sel_part ? hilite( c_light_green ) : c_light_green ) : " " );
         nc_color clr = std::get<3>( bgt ) ? c_white : c_dark_gray;
         trim_and_print( w_partlist, point( 0, y++ ), partlist_width,
                         i == sel_part ? hilite( clr ) : clr, txt );
     }
     wnoutrefresh( w_partlist );
 }
References all_height, c_dark_gray, c_light_green, c_white, c_yellow, colorize(), hilite(), left_justify(), partlist, partlist_width, point, sel_part, top_part, trim_and_print(), trim_by_length(), uppercase_first_letter(), w_partlist, catacurses::werase(), and catacurses::wnoutrefresh().
Referenced by create_or_get_ui_adaptor().
init_ui_windows()
void bodygraph_display::init_ui_windows ()
Definition at line 303 of file bodygraph.cpp.
 {
     partlist_width = 18;
     info_width = 18;
     all_height = clamp( BPGRAPH_MAXROWS + 24, 0, TERMY );
     int base_width = BPGRAPH_MAXCOLS + partlist_width + info_width + 4;
     all_width = clamp( base_width + 40, 0, TERMX );
     // distribute extra horizontal space to the parts/info columns
     for( int i = base_width; i < all_width; i++ ) {
         if( i % 4 == 0 ) {
             partlist_width++;
         } else {
             info_width++;
         }
     }
     point top_left( TERMX / 2 - all_width / 2, TERMY / 2 - all_height / 2 );
     w_border = catacurses::newwin( all_height, all_width, top_left );
     //NOLINTNEXTLINE(cata-use-named-point-constants)
     w_partlist = catacurses::newwin( all_height - 2, partlist_width, top_left + point( 1, 1 ) );
     int graph_vpad = clamp<int>( ( ( all_height - 3 ) - BPGRAPH_MAXROWS ) / 2, 0, all_height );
     w_graph = catacurses::newwin( BPGRAPH_MAXROWS, BPGRAPH_MAXCOLS,
                                   top_left + point( 2 + partlist_width, graph_vpad + 2 ) );
     w_info = catacurses::newwin( all_height - 2, info_width,
                                  top_left + point( 3 + partlist_width + BPGRAPH_MAXCOLS, 1 ) );
     bh_borders = border_helper();
     bh_borders.add_border().set( top_left, { all_width, all_height } );
     bh_borders.add_border().set( top_left + point( partlist_width + 1, 0 ), { BPGRAPH_MAXCOLS + 2, all_height } );
 }
References border_helper::add_border(), all_height, all_width, bh_borders, BPGRAPH_MAXCOLS, BPGRAPH_MAXROWS, clamp(), info_width, catacurses::newwin(), partlist_width, point, border_helper::border_info::set(), TERMX, TERMY, w_border, w_graph, w_info, and w_partlist.
Referenced by create_or_get_ui_adaptor().
prepare_infolist()
void bodygraph_display::prepare_infolist ()
Definition at line 471 of file bodygraph.cpp.
 {
     // reset info for a new read
     info = bodygraph_info();
     info_txt.clear();
     // if character doesn't have this part, don't generate info
     if( !std::get<3>( partlist[sel_part] ) ) {
         return;
     }
     const bodypart_id &bp = std::get<0>( partlist[sel_part] );
     // sbps will either be a group for a body part and we'll need to do averages OR a single sub part
     std::set<sub_bodypart_id> sub_parts;
     // this might be null need to test for nullbp as this all continues
     if( std::get<1>( partlist[sel_part] ) != nullptr ) {
         sub_parts.emplace( std::get<1>( partlist[sel_part] )->id );
     } else {
         for( const sub_bodypart_str_id &sbp : bp->sub_parts ) {
             // don't worry about secondary sub parts would just make things confusing
             if( !sbp->secondary ) {
                 sub_parts.emplace( sbp.id() );
             }
         }
     }
     u->worn.prepare_bodymap_info( info, bp, sub_parts, *u );
     // update info text cache
     prepare_infotext( true );
 }
References bp, string_id< T >::id(), info, info_txt, partlist, outfit::prepare_bodymap_info(), prepare_infotext(), sub_body_part_type::secondary, sel_part, body_part_type::sub_parts, u, and Character::worn.
Referenced by display().
prepare_infotext()
void bodygraph_display::prepare_infotext (bool reset_pos)
Definition at line 505 of file bodygraph.cpp.
 {
     top_info = reset_pos ? 0 : top_info;
     if( info.specific_sublimb ) {
         // parent part
         info_txt.emplace_back( string_format( "%s: %s", colorize( _( "Sub part of" ), c_magenta ),
                                               info.parent_bp_name ) );
     }
     // part health
     std::pair<std::string, nc_color> hpbar = get_hp_bar( info.part_hp_cur, info.part_hp_max );
     info_txt.emplace_back( string_format( "%s: %s", colorize( _( "Health" ), c_magenta ),
                                           colorize( hpbar.first, hpbar.second ) ) );
     // part wetness
     info_txt.emplace_back( string_format( "%s: %d%%", colorize( _( "Wetness" ), c_magenta ),
                                           static_cast<int>( info.wetness * 100.0f ) ) );
     // part temperature
     const bool temp_precise = u->cache_has_item_with( STATIC( flag_id( "THERMOMETER" ) ) ) ||
                               u->has_flag( STATIC( json_character_flag( "THERMOMETER" ) ) );
     const units::temperature temp = units::from_fahrenheit( info.temperature.first / 50.0 );
     info_txt.emplace_back( string_format( "%s: %s", colorize( _( "Body temp" ), c_magenta ),
                                           temp_precise ? colorize( print_temperature( temp ),
                                                   info.temperature.second ) : info.temp_approx ) );
     info_txt.emplace_back( "--" );
     // part effects
     info_txt.emplace_back( string_format( "%s:", colorize( _( "Effects" ), c_magenta ) ) );
     for( const effect &eff : info.effects ) {
         if( eff.get_id()->is_show_in_info() ) {
             game_message_type rt = eff.get_id()->get_rating( eff.get_intensity() );
             info_txt.emplace_back( string_format( "  %s", colorize( eff.disp_name(),
                                                   rt == m_good ? c_green : rt == m_bad ? c_red : c_yellow ) ) );
         }
     }
     info_txt.emplace_back( "--" );
     // worn armor
     info_txt.emplace_back( string_format( "%s:", colorize( _( "Worn" ), c_magenta ) ) );
     for( const std::string &worn : info.worn_names ) {
         info_txt.emplace_back( string_format( "  %s", worn ) );
     }
     info_txt.emplace_back( "--" );
     // coverage
     info_txt.emplace_back( string_format( "%s: %d%%",
                                           colorize( info.specific_sublimb ? _( "Coverage" ) : _( "Coverage (Avg.)" ), c_magenta ),
                                           info.avg_coverage ) );
     info_txt.emplace_back( "--" );
     // encumbrance
     info_txt.emplace_back( string_format( "%s: %d", colorize( _( "Encumbrance" ), c_magenta ),
                                           info.total_encumbrance ) );
     info_txt.emplace_back( "--" );
     // protection
     info_txt.emplace_back( string_format( "%s:",
                                           colorize( info.specific_sublimb ? _( "Protection" ) : _( "Protection (Avg.)" ), c_magenta ) ) );
     std::string prot_legend = string_format( "%s %s %s", colorize( _( "worst" ), c_red ),
                               colorize( _( "median" ), c_yellow ), colorize( _( "best" ), c_light_green ) );
     int wavail = clamp( ( info_width - 2 ) - utf8_width( prot_legend, true ), 0, info_width - 2 );
     prot_legend.insert( prot_legend.begin(), wavail > 4 ? 4 : wavail, ' ' );
     info_txt.emplace_back( prot_legend );
     auto get_res_str = [&]( const damage_type_id & dt ) -> std::string {
         const std::string wval = string_format( info_width <= 18 ? "%4.1f" : "%5.2f", info.worst_case.type_resist( dt ) );
         const std::string mval = string_format( info_width <= 18 ? "%4.1f" : "%5.2f", info.median_case.type_resist( dt ) );
         const std::string bval = string_format( info_width <= 18 ? "%4.1f" : "%5.2f", info.best_case.type_resist( dt ) );
         std::string txt = string_format( "%s %s %s", colorize( wval, c_red ), colorize( mval, c_yellow ), colorize( bval, c_light_green ) );
         int res_avail = clamp( ( info_width - 2 ) - utf8_width( txt, true ), 0, info_width - 2 );
         txt.insert( txt.begin(), res_avail > 4 ? 4 : res_avail, ' ' );
         return txt;
     };
     auto get_env_str = [&]( const damage_type_id & dt ) -> std::string {
         return colorize( string_format( "    %5.2f", info.best_case.type_resist( dt ) ), c_white );
     };
     for( const damage_type &dt : damage_type::get_all() ) {
         if( info.best_case.type_resist( dt.id ) > 1 ) {
             info_txt.emplace_back( string_format( "  %s:", uppercase_first_letter( dt.name.translated() ) ) );
             info_txt.emplace_back( dt.env ? get_env_str( dt.id ) : get_res_str( dt.id ) );
         }
     }
 }
References _, bodygraph_info::avg_coverage, bodygraph_info::best_case, c_green, c_light_green, c_magenta, c_red, c_white, c_yellow, Character::cache_has_item_with(), clamp(), colorize(), effect::disp_name(), bodygraph_info::effects, flag_id, units::from_fahrenheit(), damage_type::get_all(), get_hp_bar(), effect::get_id(), effect::get_intensity(), effect_type::get_rating(), Character::has_flag(), info, info_txt, info_width, effect_type::is_show_in_info(), m_bad, m_good, bodygraph_info::median_case, bodygraph_info::parent_bp_name, bodygraph_info::part_hp_cur, bodygraph_info::part_hp_max, print_temperature(), bodygraph_info::specific_sublimb, STATIC, string_format(), temp, bodygraph_info::temp_approx, bodygraph_info::temperature, top_info, bodygraph_info::total_encumbrance, resistances::type_resist(), u, uppercase_first_letter(), utf8_width(), bodygraph_info::wetness, bodygraph_info::worn_names, and bodygraph_info::worst_case.
Referenced by create_or_get_ui_adaptor(), and prepare_infolist().
prepare_partlist()
void bodygraph_display::prepare_partlist ()
Definition at line 443 of file bodygraph.cpp.
 {
     partlist.clear();
     for( const auto &bgp : id->parts ) {
         for( const bodypart_id &bid : bgp.second.bodyparts ) {
             partlist.emplace_back( bid, static_cast<const sub_body_part_type *>( nullptr ),
                                    &bgp.second, u->has_part( bid, body_part_filter::equivalent ) );
         }
         for( const sub_bodypart_id &sid : bgp.second.sub_bodyparts ) {
             const bodypart_id bid = sid->parent.id();
             partlist.emplace_back( bid, &*sid, &bgp.second, u->has_part( bid, body_part_filter::equivalent ) );
         }
     }
     std::sort( partlist.begin(), partlist.end(),
     []( const part_tuple & a, const part_tuple & b ) {
         if( !!std::get<1>( a ) && !!std::get<1>( b ) ) {
             return std::get<1>( a )->name.translated_lt( std::get<1>( b )->name );
         }
         if( std::get<0>( a )->name.translated_ne( std::get<0>( b )->name ) ) {
             return std::get<0>( a )->name.translated_lt( std::get<0>( b )->name );
         }
         if( !std::get<1>( a ) != !std::get<1>( b ) ) {
             return !std::get<1>( a );
         }
         return a != b;
     } );
 }
References a, b, equivalent, Creature::has_part(), id, int_id< T >::id(), partlist, bodygraph::parts, and u.
Referenced by display().
Member Data Documentation
all_height
int bodygraph_display::all_height = 0
Definition at line 261 of file bodygraph.cpp.
Referenced by display(), draw_borders(), draw_info(), draw_partlist(), and init_ui_windows().
all_width
int bodygraph_display::all_width = 0
Definition at line 262 of file bodygraph.cpp.
Referenced by draw_borders(), and init_ui_windows().
bh_borders
border_helper bodygraph_display::bh_borders
Definition at line 248 of file bodygraph.cpp.
Referenced by draw_borders(), and init_ui_windows().
ctxt
input_context bodygraph_display::ctxt
Definition at line 246 of file bodygraph.cpp.
Referenced by bodygraph_display(), and display().
id
bodygraph_id bodygraph_display::id
Definition at line 245 of file bodygraph.cpp.
Referenced by draw_borders(), draw_graph(), and prepare_partlist().
info
bodygraph_info bodygraph_display::info
Definition at line 259 of file bodygraph.cpp.
Referenced by prepare_infolist(), and prepare_infotext().
info_txt
std::vector<std::string> bodygraph_display::info_txt
Definition at line 260 of file bodygraph.cpp.
Referenced by create_or_get_ui_adaptor(), display(), draw_borders(), draw_info(), prepare_infolist(), and prepare_infotext().
info_width
int bodygraph_display::info_width = 0
Definition at line 264 of file bodygraph.cpp.
Referenced by draw_info(), init_ui_windows(), and prepare_infotext().
partlist
std::vector<part_tuple> bodygraph_display::partlist
Definition at line 258 of file bodygraph.cpp.
Referenced by create_or_get_ui_adaptor(), display(), draw_borders(), draw_graph(), draw_info(), draw_partlist(), prepare_infolist(), and prepare_partlist().
partlist_width
int bodygraph_display::partlist_width = 0
Definition at line 263 of file bodygraph.cpp.
Referenced by draw_borders(), draw_partlist(), and init_ui_windows().
sel_part
int bodygraph_display::sel_part = 0
Definition at line 265 of file bodygraph.cpp.
Referenced by create_or_get_ui_adaptor(), display(), draw_graph(), draw_info(), draw_partlist(), and prepare_infolist().
top_info
int bodygraph_display::top_info = 0
Definition at line 267 of file bodygraph.cpp.
Referenced by display(), draw_borders(), draw_info(), and prepare_infotext().
top_part
int bodygraph_display::top_part = 0
Definition at line 266 of file bodygraph.cpp.
Referenced by display(), draw_borders(), and draw_partlist().
u
const Character* bodygraph_display::u
Definition at line 244 of file bodygraph.cpp.
Referenced by display(), draw_graph(), prepare_infolist(), prepare_infotext(), and prepare_partlist().
ui
weak_ptr_fast<ui_adaptor> bodygraph_display::ui
Definition at line 247 of file bodygraph.cpp.
w_border
catacurses::window bodygraph_display::w_border
Definition at line 249 of file bodygraph.cpp.
Referenced by create_or_get_ui_adaptor(), draw_borders(), and init_ui_windows().
w_graph
catacurses::window bodygraph_display::w_graph
Definition at line 251 of file bodygraph.cpp.
Referenced by draw_graph(), and init_ui_windows().
w_info
catacurses::window bodygraph_display::w_info
Definition at line 252 of file bodygraph.cpp.
Referenced by draw_info(), and init_ui_windows().
w_partlist
catacurses::window bodygraph_display::w_partlist
Definition at line 250 of file bodygraph.cpp.
Referenced by draw_partlist(), and init_ui_windows().
The documentation for this struct was generated from the following file:
src/bodygraph.cpp