Cataclysm DDA: mutable_overmap_placement_rule_remainder Struct Reference
mutable_overmap_placement_rule_remainder Struct Reference
Public Member Functions
std::string description () const
int get_weight () const
bool is_exhausted () const
void decrement ()
std::vector< tripoint_rel_omt > positions (om_direction::type rot) const
auto pieces (const tripoint_om_omt &origin, om_direction::type rot) const
auto outward_joins (const tripoint_om_omt &origin, om_direction::type rot) const
Public Attributes
const mutable_overmap_placement_rule * parent
int max = INT_MAX
int weight = INT_MAX
Detailed Description
Definition at line 1760 of file overmap.cpp.
Member Function Documentation
decrement()
void mutable_overmap_placement_rule_remainder::decrement () inline
Definition at line 1777 of file overmap.cpp.
                      {
         --max;
     }
References max.
description()
std::string mutable_overmap_placement_rule_remainder::description () const inline
Definition at line 1765 of file overmap.cpp.
{
         return parent->description();
     }
References mutable_overmap_placement_rule::description(), and parent.
Referenced by mutable_overmap_phase_remainder::satisfy().
get_weight()
int mutable_overmap_placement_rule_remainder::get_weight () const inline
Definition at line 1769 of file overmap.cpp.
{
         return std::min( max, weight );
     }
References max, min(), and weight.
Referenced by is_exhausted().
is_exhausted()
bool mutable_overmap_placement_rule_remainder::is_exhausted () const inline
Definition at line 1773 of file overmap.cpp.
{
         return get_weight() == 0;
     }
References get_weight().
Referenced by mutable_overmap_phase_remainder::satisfy().
outward_joins()
auto mutable_overmap_placement_rule_remainder::outward_joins (const tripoint_om_omt & origin, om_direction::type rot) const inline
Definition at line 1798 of file overmap.cpp.
{
         using orig_t = std::pair<rel_pos_dir, const mutable_overmap_terrain_join *>;
         using dest_t = std::pair<om_pos_dir, const mutable_overmap_terrain_join *>;
         return cata::views::transform < decltype( parent->outward_joins ), dest_t > ( parent->outward_joins,
         [origin, rot]( const orig_t &p ) -> dest_t {
             tripoint_rel_omt rotated_offset = rotate( p.first.p, rot );
             om_pos_dir p_d{ origin + rotated_offset, p.first.dir + rot };
             return { p_d, p.second };
         } );
     }
References mutable_overmap_placement_rule::outward_joins, parent, and rotate().
Referenced by mutable_overmap_phase_remainder::can_place().
pieces()
auto mutable_overmap_placement_rule_remainder::pieces (const tripoint_om_omt & origin, om_direction::type rot) const inline
Definition at line 1789 of file overmap.cpp.
{
         using orig_t = mutable_overmap_placement_rule_piece;
         using dest_t = mutable_overmap_piece_candidate;
         return cata::views::transform < decltype( parent->pieces ), dest_t > ( parent->pieces,
         [origin, rot]( const orig_t &piece ) -> dest_t {
             tripoint_rel_omt rotated_offset = rotate( piece.pos, rot );
             return { piece.overmap, origin + rotated_offset, add( rot, piece.rot ) };
         } );
     }
References add, parent, mutable_overmap_placement_rule::pieces, and rotate().
Referenced by mutable_overmap_phase_remainder::can_place(), and mutable_overmap_special_data::place().
positions()
std::vector<tripoint_rel_omt> mutable_overmap_placement_rule_remainder::positions (om_direction::type rot) const inline
Definition at line 1781 of file overmap.cpp.
{
         std::vector<tripoint_rel_omt> result;
         result.reserve( parent->pieces.size() );
         for( const mutable_overmap_placement_rule_piece &piece : parent->pieces ) {
             result.push_back( rotate( piece.pos, rot ) );
         }
         return result;
     }
References parent, mutable_overmap_placement_rule::pieces, mutable_overmap_placement_rule_piece::pos, and rotate().
Member Data Documentation
max
int mutable_overmap_placement_rule_remainder::max = INT_MAX
Definition at line 1762 of file overmap.cpp.
Referenced by decrement(), and get_weight().
parent
const mutable_overmap_placement_rule* mutable_overmap_placement_rule_remainder::parent
Definition at line 1761 of file overmap.cpp.
Referenced by description(), outward_joins(), pieces(), and positions().
weight
int mutable_overmap_placement_rule_remainder::weight = INT_MAX
Definition at line 1763 of file overmap.cpp.
Referenced by get_weight().
The documentation for this struct was generated from the following file:
src/overmap.cpp