Cataclysm DDA: item_contents::item_contents_helper Struct Reference
item_contents::item_contents_helper Struct Reference
Public Types
template<typename ItemContents >
using item_pocket_type = std::conditional_t< std::is_const_v< ItemContents >, const item_pocket, item_pocket >
Static Public Member Functions
template<typename ItemContents >
static ret_val< item_pocket_type< ItemContents > * > find_pocket_for (ItemContents &contents, const item &it, pocket_type pk_type)
Detailed Description
Definition at line 768 of file item_contents.cpp.
Member Typedef Documentation
item_pocket_type
template<typename ItemContents > using item_contents::item_contents_helper::item_pocket_type = std::conditional_t < std::is_const_v<ItemContents>, const item_pocket, item_pocket >
Definition at line 772 of file item_contents.cpp.
Member Function Documentation
find_pocket_for()
template<typename ItemContents > static ret_val<item_pocket_type<ItemContents>*> item_contents::item_contents_helper::find_pocket_for (ItemContents & contents, const item & it, pocket_type pk_type) inline static
Definition at line 779 of file item_contents.cpp.
{
         using my_pocket_type = item_pocket_type<ItemContents>;
         static constexpr item_pocket *null_pocket = nullptr;
         std::vector<std::string> failure_messages;
         int num_pockets_of_type = 0;
         for( my_pocket_type &pocket : contents.contents ) {
             if( !pocket.is_type( pk_type ) ) {
                 continue;
             }
             if( pk_type != pocket_type::CONTAINER &&
                 pk_type != pocket_type::MAGAZINE &&
                 pk_type != pocket_type::MAGAZINE_WELL &&
                 pocket.is_type( pk_type ) ) {
                 return ret_val<my_pocket_type *>::make_success(
                            &pocket, "special pocket type override" );
             }
             ++num_pockets_of_type;
             ret_val<item_pocket::contain_code> ret_contain = pocket.can_contain( it );
             if( ret_contain.success() ) {
                 return ret_val<my_pocket_type *>::make_success( &pocket, ret_contain.str() );
             } else {
                 failure_messages.push_back( ret_contain.str() );
             }
         }
         if( failure_messages.empty() ) {
             return ret_val<my_pocket_type *>::make_failure( null_pocket, _( "pocket with type (%s) not found" ),
                     io::enum_to_string( pk_type ) );
         }
         std::sort( failure_messages.begin(), failure_messages.end(), localized_compare );
         failure_messages.erase(
             std::unique( failure_messages.begin(), failure_messages.end() ),
             failure_messages.end() );
         return ret_val<my_pocket_type *>::make_failure(
                    null_pocket,
                    n_gettext( "pocket unacceptable because %s", "pockets unacceptable because %s",
                               num_pockets_of_type ),
                    enumerate_as_string( failure_messages, enumeration_conjunction::or_ ) );
     }
References _, CONTAINER, item_contents::contents, io::enum_to_string(), enumerate_as_string(), localized_compare, MAGAZINE, MAGAZINE_WELL, ret_val< T >::make_failure(), ret_val< T >::make_success(), n_gettext, or_, ret_val_common::str(), and ret_val_common::success().
Referenced by item_contents::find_pocket_for().
The documentation for this struct was generated from the following file:
src/item_contents.cpp