Cataclysm DDA: eoc_math Struct Reference
eoc_math Struct Reference
#include <dialogue_helpers.h>
Public Types
enum class oper : int {
ret = 0 , assign , plus_assign , minus_assign ,
mult_assign , div_assign , mod_assign , increase ,
decrease , equal , not_equal , less ,
equal_or_less , greater , equal_or_greater , invalid
}
enum class type_t : int { ret = 0 , compare , assign }
Public Member Functions
void from_json (const JsonObject &jo, std::string_view member, type_t type_)
double act (dialogue &d) const
void _validate_type (JsonArray const &objects, type_t type_) const
Public Attributes
std::shared_ptr< math_exp > lhs
std::shared_ptr< math_exp > mhs
std::shared_ptr< math_exp > rhs
eoc_math::oper action = oper::invalid
Detailed Description
Definition at line 98 of file dialogue_helpers.h.
Member Enumeration Documentation
oper
enum eoc_math::oper : int strong
Enumerator
ret
assign
plus_assign
minus_assign
mult_assign
div_assign
mod_assign
increase
decrease
equal
not_equal
less
equal_or_less
greater
equal_or_greater
invalid
Definition at line 99 of file dialogue_helpers.h.
                     : int {
         ret = 0,
         assign,
         // these need mhs
         plus_assign,
         minus_assign,
         mult_assign,
         div_assign,
         mod_assign,
         increase,
         decrease,
         equal,
         not_equal,
         less,
         equal_or_less,
         greater,
         equal_or_greater,
         invalid,
     };
type_t
enum eoc_math::type_t : int strong
Enumerator
ret
compare
assign
Definition at line 121 of file dialogue_helpers.h.
                       : int {
         ret = 0,
         compare,
         assign,
     };
Member Function Documentation
_validate_type()
void eoc_math::_validate_type (JsonArray const & objects, type_t type_) const
Definition at line 2237 of file condition.cpp.
 {
     if( type_ != type_t::compare && action >= oper::equal ) {
         objects.throw_error( "Comparison operators can only be used in conditional statements" );
     } else if( type_ == type_t::compare && action < oper::equal ) {
         if( action == oper::assign ) {
             objects.throw_error(
                 R"(Assignment operator "=" can't be used in a conditional statement.  Did you mean to use "=="? )" );
         } else if( action != oper::ret ) {
             objects.throw_error( "Only comparison operators can be used in conditional statements" );
         }
     } else if( type_ == type_t::ret && action > oper::ret ) {
         objects.throw_error( "Only return expressions are allowed in this context" );
     } else if( type_ != type_t::ret && action == oper::ret ) {
         objects.throw_error( "Return expression in assignment context has no effect" );
     }
 }
References action, assign, compare, equal, ret, and JsonArray::throw_error().
Referenced by from_json().
act()
double eoc_math::act (dialogue & d) const
Definition at line 2315 of file condition.cpp.
 {
     switch( action ) {
         case oper::ret:
             return lhs->eval( d );
         case oper::assign:
             lhs->assign( d, rhs->eval( d ) );
             break;
         case oper::plus_assign:
             lhs->assign( d, mhs->eval( d ) + rhs->eval( d ) );
             break;
         case oper::minus_assign:
             lhs->assign( d, mhs->eval( d ) - rhs->eval( d ) );
             break;
         case oper::mult_assign:
             lhs->assign( d, mhs->eval( d ) * rhs->eval( d ) );
             break;
         case oper::div_assign:
             lhs->assign( d, mhs->eval( d ) / rhs->eval( d ) );
             break;
         case oper::mod_assign:
             lhs->assign( d, std::fmod( mhs->eval( d ), rhs->eval( d ) ) );
             break;
         case oper::increase:
             lhs->assign( d, mhs->eval( d ) + 1 );
             break;
         case oper::decrease:
             lhs->assign( d, mhs->eval( d ) - 1 );
             break;
         case oper::equal:
             return static_cast<double>( float_equals( lhs->eval( d ), rhs->eval( d ) ) );
         case oper::not_equal:
             return static_cast<double>( !float_equals( lhs->eval( d ), rhs->eval( d ) ) );
         case oper::less:
             return lhs->eval( d ) < rhs->eval( d );
         case oper::equal_or_less:
             return lhs->eval( d ) <= rhs->eval( d );
         case oper::greater:
             return lhs->eval( d ) > rhs->eval( d );
         case oper::equal_or_greater:
             return lhs->eval( d ) >= rhs->eval( d );
         case oper::invalid:
         default:
             debugmsg( "unknown eoc math operator %d %s", action, d.get_callstack() );
     }
     return 0;
 }
References action, assign, debugmsg, decrease, div_assign, equal, equal_or_greater, equal_or_less, float_equals(), units::fmod(), dialogue::get_callstack(), greater, increase, invalid, less, lhs, mhs, minus_assign, mod_assign, mult_assign, not_equal, plus_assign, ret, and rhs.
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_math(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_math().
from_json()
void eoc_math::from_json (const JsonObject & jo, std::string_view member, type_t type_)
Definition at line 2255 of file condition.cpp.
 {
     JsonArray const objects = jo.get_array( member );
     if( objects.size() > 3 ) {
         jo.throw_error( "Invalid number of args in " + jo.str() );
         return;
     }
     std::string const oper = objects.size() >= 2 ? objects.get_string( 1 ) : std::string{};
     if( objects.size() == 1 ) {
         action = oper::ret;
     } else if( objects.size() == 2 ) {
         if( oper == "++" ) {
             action = oper::increase;
         } else if( oper == "--" ) {
             action = oper::decrease;
         } else {
             jo.throw_error( "Invalid unary operator in " + jo.str() );
             return;
         }
     } else if( objects.size() == 3 ) {
         rhs = defer_math( objects.get_string( 2 ), false );
         if( oper == "=" ) {
             action = oper::assign;
         } else if( oper == "+=" ) {
             action = oper::plus_assign;
         } else if( oper == "-=" ) {
             action = oper::minus_assign;
         } else if( oper == "*=" ) {
             action = oper::mult_assign;
         } else if( oper == "/=" ) {
             action = oper::div_assign;
         } else if( oper == "%=" ) {
             action = oper::mod_assign;
         } else if( oper == "==" ) {
             action = oper::equal;
         } else if( oper == "!=" ) {
             action = oper::not_equal;
         } else if( oper == "<" ) {
             action = oper::less;
         } else if( oper == "<=" ) {
             action = oper::equal_or_less;
         } else if( oper == ">" ) {
             action = oper::greater;
         } else if( oper == ">=" ) {
             action = oper::equal_or_greater;
         } else {
             jo.throw_error( "Invalid binary operator in " + jo.str() );
             return;
         }
     }
     _validate_type( objects, type_ );
     bool const lhs_assign = action >= oper::assign && action <= oper::decrease;
     lhs = defer_math( objects.get_string( 0 ), lhs_assign );
     if( action >= oper::plus_assign && action <= oper::decrease ) {
         mhs = defer_math( objects.get_string( 0 ), false );
     }
 }
References _validate_type(), action, assign, decrease, anonymous_namespace{condition.cpp}::defer_math(), div_assign, equal, equal_or_greater, equal_or_less, JsonObject::get_array(), JsonArray::get_string(), greater, increase, less, lhs, member, mhs, minus_assign, mod_assign, mult_assign, not_equal, plus_assign, ret, rhs, JsonArray::size(), JsonObject::str(), and JsonObject::throw_error().
Referenced by conditional_fun::anonymous_namespace{condition.cpp}::f_math(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_math().
Member Data Documentation
action
eoc_math::oper eoc_math::action = oper::invalid
Definition at line 129 of file dialogue_helpers.h.
Referenced by _validate_type(), act(), and from_json().
lhs
std::shared_ptr<math_exp> eoc_math::lhs
Definition at line 126 of file dialogue_helpers.h.
Referenced by act(), and from_json().
mhs
std::shared_ptr<math_exp> eoc_math::mhs
Definition at line 127 of file dialogue_helpers.h.
Referenced by act(), and from_json().
rhs
std::shared_ptr<math_exp> eoc_math::rhs
Definition at line 128 of file dialogue_helpers.h.
Referenced by act(), and from_json().
The documentation for this struct was generated from the following files:
src/dialogue_helpers.h
src/condition.cpp