Cataclysm DDA: event_statistic_maximum::state Struct Reference
event_statistic_maximum::state Struct Reference
Public Member Functions
state (const event_statistic_maximum *s, stats_tracker &stats)
void event_added (const cata::event &e, stats_tracker &stats) override
void events_reset (const event_multiset &new_set, stats_tracker &stats) override
const cata_variant & get_value () const override
Public Member Functions inherited from stats_tracker_state
virtual ~stats_tracker_state ()=0
Public Member Functions inherited from base_watcher
base_watcher ()=default
base_watcher (const base_watcher &)=delete
base_watcher & operator= (const base_watcher &)=delete
Public Attributes
const event_statistic_maximum * stat
cata_variant value
int value_int
Additional Inherited Members
Protected Member Functions inherited from base_watcher
virtual ~base_watcher ()
Detailed Description
Definition at line 903 of file event_statistics.cpp.
Constructor & Destructor Documentation
state()
event_statistic_maximum::state::state (const event_statistic_maximum * s, stats_tracker & stats) inline
Definition at line 904 of file event_statistics.cpp.
                                                                         :
             stat( s ),
             value( s->value( stats ) ),
             value_int( value.get<int>() ) {
             stat->source->add_watcher( stats, this );
         }
References event_source::add_watcher(), event_statistic_field_summary< IntField >::source, and stat.
Member Function Documentation
event_added()
void event_statistic_maximum::state::event_added (const cata::event & e, stats_tracker & stats) inline override virtual
Implements event_multiset_watcher.
Definition at line 911 of file event_statistics.cpp.
{
             const int new_value = std::max( e.get<int>( stat->field ), value_int );
             if( new_value != value_int ) {
                 value_int = new_value;
                 value = cata_variant( value_int );
                 stats.stat_value_changed( stat->id, cata_variant( value ) );
             }
         }
References event_statistic_field_summary< IntField >::field, cata::event::get(), event_statistic_field_summary< IntField >::id, max(), stat, value, and value_int.
events_reset()
void event_statistic_maximum::state::events_reset (const event_multiset & new_set, stats_tracker & stats) inline override virtual
Implements event_multiset_watcher.
Definition at line 920 of file event_statistics.cpp.
{
             value_int = new_set.maximum( stat->field );
             value = cata_variant( value_int );
             stats.stat_value_changed( stat->id, cata_variant( value ) );
         }
References event_statistic_field_summary< IntField >::field, event_statistic_field_summary< IntField >::id, event_multiset::maximum(), stat, value, and value_int.
get_value()
const cata_variant& event_statistic_maximum::state::get_value () const inline override virtual
Implements stats_tracker_state.
Definition at line 926 of file event_statistics.cpp.
{
             return value;
         }
References value.
Member Data Documentation
stat
const event_statistic_maximum* event_statistic_maximum::state::stat
Definition at line 930 of file event_statistics.cpp.
Referenced by event_added(), events_reset(), and state().
value
cata_variant event_statistic_maximum::state::value
Definition at line 931 of file event_statistics.cpp.
Referenced by event_added(), events_reset(), and get_value().
value_int
int event_statistic_maximum::state::value_int
Definition at line 932 of file event_statistics.cpp.
Referenced by event_added(), and events_reset().
The documentation for this struct was generated from the following file:
src/event_statistics.cpp