Cataclysm DDA: jmapgen_objects Struct Reference
jmapgen_objects Struct Reference
#include <mapgen.h>
Public Member Functions
jmapgen_objects (const tripoint_rel_ms &offset, const point &mapsize, const point &tot_size)
bool check_bounds (const jmapgen_place &place, const JsonObject &jso)
void add (const jmapgen_place &place, const shared_ptr_fast< const jmapgen_piece > &piece)
template<typename PieceType >
void load_objects (const JsonArray &parray, std::string_view context)
PieceType must be inheriting from jmapgen_piece.
template<typename PieceType >
void load_objects (const JsonObject &jsi, const std::string &member_name, const std::string &context)
Loads the mapgen objects from the array inside of jsi.
void finalize ()
void check (const std::string &context, const mapgen_parameters &) const
void merge_parameters_into (mapgen_parameters &, const std::string &outer_context) const
void add_placement_coords_to (std::unordered_set< point > &) const
void apply (const mapgendata &dat, mapgen_phase, const std::string &context) const
void apply (const mapgendata &dat, mapgen_phase, const tripoint_rel_ms &offset, const std::string &context) const
bool has_vehicle_collision (const mapgendata &dat, const tripoint_rel_ms &offset) const
checks if applying these objects to data would cause cause a collision with vehicles on the same map
template<>
void load_objects (const JsonArray &parray, const std::string_view)
Private Types
using jmapgen_obj = std::pair< jmapgen_place, shared_ptr_fast< const jmapgen_piece > >
Combination of where to place something and what to place.
Private Attributes
std::vector< jmapgen_obj > objects
tripoint_rel_ms m_offset
point mapgensize
point total_size
Detailed Description
Definition at line 390 of file mapgen.h.
Member Typedef Documentation
jmapgen_obj
using jmapgen_objects::jmapgen_obj = std::pair<jmapgen_place, shared_ptr_fast<const jmapgen_piece> > private
Combination of where to place something and what to place.
Definition at line 435 of file mapgen.h.
Constructor & Destructor Documentation
jmapgen_objects()
jmapgen_objects::jmapgen_objects (const tripoint_rel_ms & offset, const point & mapsize, const point & tot_size)
Definition at line 3919 of file mapgen.cpp.
     : m_offset( offset )
     , mapgensize( mapsize )
     , total_size( tot_size )
 {}
Member Function Documentation
add()
void jmapgen_objects::add (const jmapgen_place & place, const shared_ptr_fast< const jmapgen_piece > & piece)
Definition at line 3931 of file mapgen.cpp.
 {
     objects.emplace_back( place, piece );
 }
References objects.
Referenced by load_objects().
add_placement_coords_to()
void jmapgen_objects::add_placement_coords_to (std::unordered_set< point > & result) const
Definition at line 4799 of file mapgen.cpp.
 {
     for( const jmapgen_obj &obj : objects ) {
         const jmapgen_place &where = obj.first;
         for( int x = where.x.val; x <= where.x.valmax; ++x ) {
             for( int y = where.y.val; y <= where.y.valmax; ++y ) {
                 result.emplace( x, y );
             }
         }
     }
 }
References jmapgen_int::val, jmapgen_int::valmax, jmapgen_place::x, and jmapgen_place::y.
apply() [1/2]
void jmapgen_objects::apply (const mapgendata & dat, mapgen_phase phase, const std::string & context) const
Definition at line 5299 of file mapgen.cpp.
 {
     apply( dat, phase, tripoint_rel_ms( tripoint_zero ), context );
 }
References apply(), context, and tripoint_zero.
Referenced by apply_mapgen_in_phases().
apply() [2/2]
void jmapgen_objects::apply (const mapgendata & dat, mapgen_phase phase, const tripoint_rel_ms & offset, const std::string & context) const
Definition at line 5305 of file mapgen.cpp.
 {
     bool terrain_resolved = false;
     auto range_at_phase = std::equal_range( objects.begin(), objects.end(), phase, compare_phases );
     for( auto it = range_at_phase.first; it != range_at_phase.second; ++it ) {
         const jmapgen_obj &obj = *it;
         jmapgen_place where = obj.first;
         where.offset( tripoint_rel_ms( -offset.raw() ) );
         const jmapgen_piece &what = *obj.second;
         cata_assert( what.phase() == phase );
         if( !terrain_resolved && typeid( what ) == typeid( jmapgen_vehicle ) ) {
             // In order to determine collisions between vehicles and local "terrain" the terrain has to be resolved
             // This code is based on two assumptions:
             // 1. The terrain part of a definition is always placed first.
             // 2. Only vehicles require the terrain to be resolved. The general solution is to use a virtual function.
             resolve_regional_terrain_and_furniture( dat );
             terrain_resolved = true;
         }
         // The user will only specify repeat once in JSON, but it may get loaded both
         // into the what and where in some cases--we just need the greater value of the two.
         const int repeat = std::max( where.repeat.get(), what.repeat.get() );
         for( int i = 0; i < repeat; i++ ) {
             what.apply( dat, where.x, where.y, where.z, context );
         }
     }
 }
References jmapgen_piece::apply(), cata_assert, compare_phases, context, jmapgen_int::get(), max(), jmapgen_place::offset(), jmapgen_piece::phase(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), jmapgen_piece::repeat, jmapgen_place::repeat, resolve_regional_terrain_and_furniture(), jmapgen_place::x, jmapgen_place::y, and jmapgen_place::z.
check()
void jmapgen_objects::check (const std::string & context, const mapgen_parameters & parameters) const
Definition at line 4782 of file mapgen.cpp.
 {
     for( const jmapgen_obj &obj : objects ) {
         const jmapgen_place &where = obj.first;
         const jmapgen_piece &what = *obj.second;
         what.check( context, parameters, where.x, where.y, where.z );
     }
 }
References jmapgen_piece::check(), context, mapgen_palette::parameters, jmapgen_place::x, jmapgen_place::y, and jmapgen_place::z.
check_bounds()
bool jmapgen_objects::check_bounds (const jmapgen_place & place, const JsonObject & jso)
Definition at line 3926 of file mapgen.cpp.
 {
     return common_check_bounds( place.x, place.y, place.z, mapgensize, jso );
 }
References common_check_bounds(), mapgensize, jmapgen_place::x, jmapgen_place::y, and jmapgen_place::z.
Referenced by load_objects().
finalize()
void jmapgen_objects::finalize ()
Definition at line 4776 of file mapgen.cpp.
 {
     std::stable_sort( objects.begin(), objects.end(), compare_phases );
     objects.shrink_to_fit();
 }
References compare_phases.
has_vehicle_collision()
bool jmapgen_objects::has_vehicle_collision (const mapgendata & dat, const tripoint_rel_ms & offset) const
checks if applying these objects to data would cause cause a collision with vehicles on the same map
Definition at line 5339 of file mapgen.cpp.
 {
     for( const jmapgen_obj &obj : objects ) {
         jmapgen_place where = obj.first;
         where.offset( tripoint_rel_ms( - offset.raw() ) );
         const auto &what = *obj.second;
         if( what.has_vehicle_collision( dat, tripoint_rel_ms( where.x.get(), where.y.get(),
                                         where.z.get() ) ) ) {
             return true;
         }
     }
     return false;
 }
References jmapgen_int::get(), jmapgen_place::offset(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), jmapgen_place::x, jmapgen_place::y, and jmapgen_place::z.
Referenced by apply_mapgen_in_phases().
load_objects() [1/3]
template<> void jmapgen_objects::load_objects (const JsonArray & parray, const std::string_view)
Definition at line 3953 of file mapgen.cpp.
 {
     for( JsonObject jsi : parray ) {
         jmapgen_place where( jsi );
         where.offset( m_offset );
         if( !check_bounds( where, jsi ) ) {
             jsi.allow_omitted_members();
             continue;
         }
         auto loot = make_shared_fast<jmapgen_loot>( jsi );
         // spawn rates < 1 are handled in item_group
         const float rate = std::max( get_option<float>( "ITEM_SPAWNRATE" ), 1.0f );
         if( where.repeat.valmax != 1 ) {
             // if loot can repeat scale according to rate
             where.repeat.val = std::max( static_cast<int>( where.repeat.val * rate ), 1 );
             where.repeat.valmax = std::max( static_cast<int>( where.repeat.valmax * rate ), 1 );
         } else if( loot->chance != 100 ) {
             // otherwise except where chance is 100% scale probability
             loot->chance = std::max( std::min( static_cast<int>( loot->chance * rate ), 100 ), 1 );
         }
         add( where, loot );
     }
 }
References add(), JsonObject::allow_omitted_members(), check_bounds(), mapgen_defer::jsi, loot(), m_offset, max(), min(), jmapgen_place::offset(), jmapgen_place::repeat, jmapgen_int::val, and jmapgen_int::valmax.
load_objects() [2/3]
template<typename PieceType > void jmapgen_objects::load_objects (const JsonArray & parray, std::string_view context)
PieceType must be inheriting from jmapgen_piece.
It must have constructor that accepts a const JsonObject &as parameter. The function loads all objects from the json array and stores them in objects.
Definition at line 3938 of file mapgen.cpp.
 {
     for( JsonObject jsi : parray ) {
         jmapgen_place where( jsi );
         where.offset( m_offset );
         if( check_bounds( where, jsi ) ) {
             add( where, make_shared_fast<PieceType>( jsi, context ) );
         } else {
             jsi.allow_omitted_members();
         }
     }
 }
References add(), JsonObject::allow_omitted_members(), check_bounds(), context, mapgen_defer::jsi, m_offset, and jmapgen_place::offset().
load_objects() [3/3]
template<typename PieceType > void jmapgen_objects::load_objects (const JsonObject & jsi, const std::string & member_name, const std::string & context)
Loads the mapgen objects from the array inside of jsi.
If jsi has no member of that name, nothing is loaded and the function just returns.
Definition at line 3984 of file mapgen.cpp.
 {
     if( !jsi.has_member( member_name ) ) {
         return;
     }
     load_objects<PieceType>( jsi.get_array( member_name ), member_name + " in " + context );
 }
References context, JsonObject::get_array(), JsonObject::has_member(), and mapgen_defer::jsi.
merge_parameters_into()
void jmapgen_objects::merge_parameters_into (mapgen_parameters & params, const std::string & outer_context) const
Definition at line 4791 of file mapgen.cpp.
 {
     for( const jmapgen_obj &obj : objects ) {
         obj.second->merge_parameters_into( params, outer_context );
     }
 }
Referenced by mapgen_function_json_base::finalize_parameters_common().
Member Data Documentation
m_offset
tripoint_rel_ms jmapgen_objects::m_offset private
Definition at line 437 of file mapgen.h.
Referenced by load_objects().
mapgensize
point jmapgen_objects::mapgensize private
Definition at line 438 of file mapgen.h.
Referenced by check_bounds().
objects
std::vector<jmapgen_obj> jmapgen_objects::objects private
Definition at line 436 of file mapgen.h.
Referenced by add().
total_size
point jmapgen_objects::total_size private
Definition at line 439 of file mapgen.h.
The documentation for this struct was generated from the following files:
src/mapgen.h
src/mapgen.cpp