Cataclysm DDA: jmapgen_int Struct Reference
jmapgen_int Struct Reference
#include <mapgen.h>
Public Member Functions
jmapgen_int (int v)
jmapgen_int (int v, int v2)
jmapgen_int (point p)
jmapgen_int (const JsonObject &jo, std::string_view tag)
Throws as usually if the json is invalid or missing.
jmapgen_int (const JsonObject &jo, std::string_view tag, const int &def_val, const int &def_valmax)
Throws if the json is malformed (e.g.
int get () const
Public Attributes
int16_t val
int16_t valmax
Detailed Description
Definition at line 81 of file mapgen.h.
Constructor & Destructor Documentation
jmapgen_int() [1/5]
jmapgen_int::jmapgen_int (int v) inline explicit
Definition at line 84 of file mapgen.h.
                                   : val( v ), valmax( v ) {
         cata_assert( v <= std::numeric_limits<int16_t>::max() );
     }
References cata_assert, and max().
jmapgen_int() [2/5]
jmapgen_int::jmapgen_int (int v, int v2) inline
Definition at line 87 of file mapgen.h.
                                  : val( v ), valmax( v2 ) {
         cata_assert( v <= std::numeric_limits<int16_t>::max() );
         cata_assert( v2 <= std::numeric_limits<int16_t>::max() );
     }
References cata_assert, and max().
jmapgen_int() [3/5]
jmapgen_int::jmapgen_int (point p) explicit
Definition at line 882 of file mapgen.cpp.
                                   : val( p.x ), valmax( p.y )
 {
     cata_assert( p.x <= std::numeric_limits<int16_t>::max() );
     cata_assert( p.y <= std::numeric_limits<int16_t>::max() );
 }
References cata_assert, max(), point::x, and point::y.
jmapgen_int() [4/5]
jmapgen_int::jmapgen_int (const JsonObject & jo, std::string_view tag)
Throws as usually if the json is invalid or missing.
Definition at line 888 of file mapgen.cpp.
 {
     if( jo.has_array( tag ) ) {
         JsonArray sparray = jo.get_array( tag );
         if( sparray.empty() || sparray.size() > 2 ) {
             jo.throw_error_at( tag, "invalid data: must be an array of 1 or 2 values" );
         }
         int tmpval = sparray.get_int( 0 );
         if( tmpval >= std::numeric_limits<int16_t>::max() ) {
             jo.throw_error_at( tag, string_format( "Value %d too large", tmpval ) );
         }
         val = tmpval;
         if( sparray.size() == 2 ) {
             int tmpvalmax = sparray.get_int( 1 );
             if( tmpvalmax >= std::numeric_limits<int16_t>::max() ) {
                 jo.throw_error_at( tag, string_format( "Value %d too large", tmpvalmax ) );
             }
             valmax = tmpvalmax;
         } else {
             valmax = val;
         }
     } else {
         val = valmax = jo.get_int( tag );
     }
 }
References JsonArray::empty(), JsonObject::get_array(), JsonArray::get_int(), JsonObject::get_int(), JsonObject::has_array(), max(), JsonArray::size(), string_format(), JsonObject::throw_error_at(), val, and valmax.
jmapgen_int() [5/5]
jmapgen_int::jmapgen_int (const JsonObject & jo, std::string_view tag, const int & def_val, const int & def_valmax)
Throws if the json is malformed (e.g.
a string not an integer, but does not throw if the member is just missing (the default values are used instead).
Definition at line 914 of file mapgen.cpp.
     : val( def_val )
     , valmax( def_valmax )
 {
     if( jo.has_array( tag ) ) {
         JsonArray sparray = jo.get_array( tag );
         if( sparray.size() > 2 ) {
             jo.throw_error_at( tag, "invalid data: must be an array of 1 or 2 values" );
         }
         if( !sparray.empty() ) {
             int tmpval = sparray.get_int( 0 );
             if( tmpval >= std::numeric_limits<int16_t>::max() ) {
                 jo.throw_error_at( tag, string_format( "Value %d too large", tmpval ) );
             }
             val = tmpval;
         }
         if( sparray.size() >= 2 ) {
             int tmpvalmax = sparray.get_int( 1 );
             if( tmpvalmax >= std::numeric_limits<int16_t>::max() ) {
                 jo.throw_error_at( tag, string_format( "Value %d too large", tmpvalmax ) );
             }
             valmax = tmpvalmax;
         }
     } else if( jo.has_member( tag ) ) {
         int tmpval = jo.get_int( tag );
         if( tmpval >= std::numeric_limits<int16_t>::max() ) {
             jo.throw_error_at( tag, string_format( "Value %d too large", tmpval ) );
         }
         val = valmax = tmpval;
     }
 }
References JsonArray::empty(), JsonObject::get_array(), JsonArray::get_int(), JsonObject::get_int(), JsonObject::has_array(), JsonObject::has_member(), max(), JsonArray::size(), string_format(), JsonObject::throw_error_at(), val, and valmax.
Member Function Documentation
get()
int jmapgen_int::get () const
Definition at line 947 of file mapgen.cpp.
 {
     return val == valmax ? val : rng( val, valmax );
 }
References rng(), val, and valmax.
Referenced by jmapgen_remove_npcs::apply(), jmapgen_field::apply(), jmapgen_npc::apply(), jmapgen_sign::apply(), jmapgen_graffiti::apply(), jmapgen_vending_machine::apply(), jmapgen_toilet::apply(), jmapgen_gaspump::apply(), jmapgen_liquid_item::apply(), jmapgen_corpse::apply(), jmapgen_item_group::apply(), jmapgen_loot::apply(), jmapgen_monster_group::apply(), jmapgen_monster::apply(), jmapgen_vehicle::apply(), jmapgen_spawn_item::apply(), jmapgen_trap::apply(), jmapgen_ter_furn_transform::apply(), jmapgen_make_rubble::apply(), jmapgen_computer::apply(), jmapgen_zone::apply(), jmapgen_variable::apply(), jmapgen_remove_vehicles::apply(), jmapgen_remove_all::apply(), jmapgen_furniture::apply(), jmapgen_terrain::apply(), jmapgen_sealed_item::apply(), jmapgen_nested::apply(), jmapgen_setmap::apply(), jmapgen_objects::apply(), VehicleFunction_json::apply(), jmapgen_setmap::has_vehicle_collision(), jmapgen_objects::has_vehicle_collision(), jmapgen_monster::jmapgen_monster(), and VehicleLocation::pick_point().
Member Data Documentation
val
int16_t jmapgen_int::val
Definition at line 82 of file mapgen.h.
Referenced by jmapgen_objects::add_placement_coords_to(), jmapgen_faction::apply(), jmapgen_liquid_item::apply(), jmapgen_item_group::apply(), jmapgen_loot::apply(), jmapgen_monster_group::apply(), jmapgen_ter_furn_transform::apply(), jmapgen_zone::apply(), jmapgen_variable::apply(), jmapgen_remove_vehicles::apply(), jmapgen_remove_all::apply(), jmapgen_vehicle::check(), jmapgen_nested::check(), common_check_bounds(), get(), jmapgen_int(), jmapgen_objects::load_objects(), jmapgen_place::offset(), and mapgen_function_json_base::setup_setmap().
valmax
int16_t jmapgen_int::valmax
Definition at line 83 of file mapgen.h.
Referenced by jmapgen_objects::add_placement_coords_to(), jmapgen_faction::apply(), jmapgen_liquid_item::apply(), jmapgen_item_group::apply(), jmapgen_loot::apply(), jmapgen_monster_group::apply(), jmapgen_ter_furn_transform::apply(), jmapgen_zone::apply(), jmapgen_remove_vehicles::apply(), jmapgen_remove_all::apply(), jmapgen_vehicle::check(), jmapgen_nested::check(), common_check_bounds(), get(), jmapgen_int(), jmapgen_objects::load_objects(), jmapgen_place::offset(), and mapgen_function_json_base::setup_setmap().
The documentation for this struct was generated from the following files:
src/mapgen.h
src/mapgen.cpp