Cataclysm DDA: event_source Struct Reference
event_source Struct Reference abstract
Public Member Functions
virtual ~event_source ()=default
virtual event_multiset get (stats_tracker &stats) const =0
virtual std::string debug_description () const =0
virtual bool is_game_start () const =0
virtual void add_watcher (stats_tracker &stats, event_multiset_watcher *watcher) const =0
virtual cata::event::fields_type fields () const =0
virtual monotonically monotonicity () const =0
virtual std::unique_ptr< event_source > clone () const =0
Static Public Member Functions
static std::unique_ptr< event_source > load (const JsonObject &jo)
Detailed Description
Definition at line 339 of file event_statistics.cpp.
Constructor & Destructor Documentation
~event_source()
virtual event_source::~event_source () virtual default
Member Function Documentation
add_watcher()
virtual void event_source::add_watcher (stats_tracker & stats, event_multiset_watcher * watcher) const pure virtual
Implemented in event_transformation_event_source, and event_type_event_source.
Referenced by event_statistic_count::state::state(), event_statistic_first_value::state::state(), event_statistic_last_value::state::state(), event_statistic_maximum::state::state(), event_statistic_minimum::state::state(), event_statistic_total::state::state(), event_statistic_unique_value::state::state(), and event_transformation_impl::state::state().
clone()
virtual std::unique_ptr<event_source> event_source::clone () const pure virtual
Implemented in event_transformation_event_source, and event_type_event_source.
debug_description()
virtual std::string event_source::debug_description () const pure virtual
Implemented in event_transformation_event_source, and event_type_event_source.
Referenced by event_statistic_field_summary< IntField >::check().
fields()
virtual cata::event::fields_type event_source::fields () const pure virtual
Implemented in event_transformation_event_source, and event_type_event_source.
Referenced by event_transformation_impl::check(), event_statistic_field_summary< IntField >::check(), event_transformation_impl::fields(), and event_statistic_field_summary< IntField >::type().
get()
virtual event_multiset event_source::get (stats_tracker & stats) const pure virtual
Implemented in event_transformation_event_source, and event_type_event_source.
Referenced by event_statistic_unique_value::state::init(), event_statistic_first_value::state::init(), event_transformation_impl::initialize(), event_statistic_count::value(), event_statistic_total::value(), event_statistic_maximum::value(), event_statistic_minimum::value(), event_statistic_unique_value::value(), event_statistic_first_value::value(), and event_statistic_last_value::value().
is_game_start()
virtual bool event_source::is_game_start () const pure virtual
Implemented in event_transformation_event_source, and event_type_event_source.
Referenced by event_statistic_unique_value::monotonicity(), event_statistic_first_value::monotonicity(), and event_statistic_last_value::monotonicity().
load()
std::unique_ptr< event_source > event_source::load (const JsonObject & jo) static
Definition at line 422 of file event_statistics.cpp.
 {
     if( jo.has_member( "event_type" ) == jo.has_member( "event_transformation" ) ) {
         jo.throw_error( "Must specify exactly one of 'event_type' or 'event_transformation'" );
     }
     if( jo.has_member( "event_type" ) ) {
         event_type type = event_type::num_event_types;
         jo.read( "event_type", type, true );
         return std::make_unique<event_type_event_source>( type );
     } else {
         string_id<event_transformation> transformation;
         jo.read( "event_transformation", transformation, true );
         return std::make_unique<event_transformation_event_source>( transformation );
     }
 }
References JsonObject::has_member(), num_event_types, JsonObject::read(), JsonObject::throw_error(), and type.
Referenced by event_transformation::load(), and event_statistic::load().
monotonicity()
virtual monotonically event_source::monotonicity () const pure virtual
Implemented in event_transformation_event_source, and event_type_event_source.
Referenced by event_statistic_total::monotonicity(), event_statistic_maximum::monotonicity(), and event_statistic_minimum::monotonicity().
The documentation for this struct was generated from the following file:
src/event_statistics.cpp