Cataclysm DDA: overmap_special_connection Struct Reference
overmap_special_connection Struct Reference
#include <omdata.h>
Public Member Functions
void deserialize (const JsonValue &jsin)
Public Attributes
tripoint p
std::optional< tripoint > from
cube_direction initial_dir = cube_direction::last
string_id< oter_type_t > terrain
string_id< overmap_connection > connection
bool existing = false
Detailed Description
Definition at line 506 of file omdata.h.
Member Function Documentation
deserialize()
void overmap_special_connection::deserialize (const JsonValue & jsin) inline
Definition at line 515 of file omdata.h.
{
         JsonObject jo = jsin.get_object();
         jo.read( "point", p );
         jo.read( "terrain", terrain );
         jo.read( "existing", existing );
         jo.read( "connection", connection );
         assign( jo, "from", from );
     }
References assign(), connection, existing, from, JsonValue::get_object(), p, JsonObject::read(), and terrain.
Member Data Documentation
connection
string_id<overmap_connection> overmap_special_connection::connection
Definition at line 512 of file omdata.h.
Referenced by deserialize().
existing
bool overmap_special_connection::existing = false
Definition at line 513 of file omdata.h.
Referenced by deserialize().
from
std::optional<tripoint> overmap_special_connection::from
Definition at line 508 of file omdata.h.
Referenced by deserialize().
initial_dir
cube_direction overmap_special_connection::initial_dir = cube_direction::last
Definition at line 509 of file omdata.h.
p
tripoint overmap_special_connection::p
Definition at line 507 of file omdata.h.
Referenced by deserialize().
terrain
string_id<oter_type_t> overmap_special_connection::terrain
Definition at line 511 of file omdata.h.
Referenced by deserialize().
The documentation for this struct was generated from the following file:
src/omdata.h