Cataclysm DDA: profession_group Struct Reference
profession_group Struct Reference
#include <profession_group.h>
Public Member Functions
void load (const JsonObject &jo, const std::string_view &)
std::vector< profession_id > get_professions () const
profession_group_id get_id () const
Static Public Member Functions
static void load_profession_group (const JsonObject &jo, const std::string &src)
static const std::vector< profession_group > & get_all ()
static void check_profession_group_consistency ()
Public Attributes
bool was_loaded = false
profession_group_id id
Private Attributes
std::vector< profession_id > profession_list
Detailed Description
Definition at line 8 of file profession_group.h.
Member Function Documentation
check_profession_group_consistency()
void profession_group::check_profession_group_consistency () static
Definition at line 40 of file profession_group.cpp.
 {
     for( const profession_group &prof_grp : get_all() ) {
         for( const profession_id prof : prof_grp.profession_list ) {
             if( !prof.is_valid() ) {
                 debugmsg( "profession_group %s contains invalid profession_id %s", prof_grp.id.c_str(),
                           prof.c_str() );
             }
         }
     }
 }
References string_id< T >::c_str(), debugmsg, get_all(), and string_id< T >::is_valid().
Referenced by DynamicDataLoader::check_consistency().
get_all()
const std::vector< profession_group > & profession_group::get_all () static
Definition at line 35 of file profession_group.cpp.
 {
     return profession_group_factory.get_all();
 }
References anonymous_namespace{profession_group.cpp}::profession_group_factory.
Referenced by Character::add_default_background(), and check_profession_group_consistency().
get_id()
profession_group_id profession_group::get_id () const
Definition at line 57 of file profession_group.cpp.
 {
     return id;
 }
References id.
get_professions()
std::vector< profession_id > profession_group::get_professions () const
Definition at line 52 of file profession_group.cpp.
 {
     return profession_list;
 }
References profession_list.
load()
void profession_group::load (const JsonObject & jo, const std::string_view &)
Definition at line 28 of file profession_group.cpp.
 {
     assign( jo, "id", id );
     assign( jo, "professions", profession_list );
 }
References assign(), and profession_list.
load_profession_group()
void profession_group::load_profession_group (const JsonObject & jo, const std::string & src) static
Definition at line 23 of file profession_group.cpp.
 {
     profession_group_factory.load( jo, src );
 }
References anonymous_namespace{profession_group.cpp}::profession_group_factory.
Referenced by DynamicDataLoader::initialize().
Member Data Documentation
id
profession_group_id profession_group::id
Definition at line 19 of file profession_group.h.
Referenced by get_id().
profession_list
std::vector<profession_id> profession_group::profession_list private
Definition at line 22 of file profession_group.h.
Referenced by get_professions(), and load().
was_loaded
bool profession_group::was_loaded = false
Definition at line 14 of file profession_group.h.
The documentation for this struct was generated from the following files:
src/profession_group.h
src/profession_group.cpp