Cataclysm DDA: reflex_activation_data Struct Reference
reflex_activation_data Struct Reference
#include <mutation.h>
Public Member Functions
bool is_trigger_true (Character &guy) const
void load (const JsonObject &jsobj)
void deserialize (const JsonObject &jo)
Public Attributes
std::function< bool(dialogue &)> trigger
What variable controls the activation.
std::pair< translation, game_message_type > msg_on
std::pair< translation, game_message_type > msg_off
bool was_loaded = false
Detailed Description
Definition at line 112 of file mutation.h.
Member Function Documentation
deserialize()
void reflex_activation_data::deserialize (const JsonObject & jo)
Definition at line 251 of file mutation_data.cpp.
 {
     load( jo );
 }
References load().
is_trigger_true()
bool reflex_activation_data::is_trigger_true (Character & guy) const
Definition at line 385 of file mutation.cpp.
 {
     dialogue d( get_talker_for( guy ), nullptr );
     return trigger( d );
 }
References get_talker_for(), and trigger.
load()
void reflex_activation_data::load (const JsonObject & jsobj)
Definition at line 232 of file mutation_data.cpp.
 {
     read_condition( jsobj, "condition", trigger, false );
     if( jsobj.has_object( "msg_on" ) ) {
         JsonObject jo = jsobj.get_object( "msg_on" );
         optional( jo, was_loaded, "text", msg_on.first );
         std::string tmp_rating;
         optional( jo, was_loaded, "rating", tmp_rating, "neutral" );
         msg_on.second = io::string_to_enum<game_message_type>( tmp_rating );
     }
     if( jsobj.has_object( "msg_off" ) ) {
         JsonObject jo = jsobj.get_object( "msg_off" );
         optional( jo, was_loaded, "text", msg_off.first );
         std::string tmp_rating;
         optional( jo, was_loaded, "rating", tmp_rating, "neutral" );
         msg_off.second = io::string_to_enum<game_message_type>( tmp_rating );
     }
 }
References JsonObject::get_object(), JsonObject::has_object(), msg_off, msg_on, optional(), read_condition(), trigger, and was_loaded.
Referenced by deserialize().
Member Data Documentation
msg_off
std::pair<translation, game_message_type> reflex_activation_data::msg_off
Definition at line 118 of file mutation.h.
Referenced by load().
msg_on
std::pair<translation, game_message_type> reflex_activation_data::msg_on
Definition at line 117 of file mutation.h.
Referenced by load().
trigger
std::function<bool(dialogue &)> reflex_activation_data::trigger
What variable controls the activation.
Definition at line 115 of file mutation.h.
Referenced by is_trigger_true(), and load().
was_loaded
bool reflex_activation_data::was_loaded = false
Definition at line 122 of file mutation.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/mutation.h
src/mutation.cpp
src/mutation_data.cpp