Cataclysm DDA: relic_procgen_data::enchantment_value_passive< T > Struct Template Reference
relic_procgen_data::enchantment_value_passive< T > Struct Template Reference
#include <relic.h>
Public Member Functions
int calc_power (T level) const
void load (const JsonObject &jo)
void deserialize (const JsonObject &jo)
Public Attributes
enchant_vals::mod type
int power_per_increment = 1
T increment = 1
T min_value = 0
T max_value = 0
enchantment::has ench_has
bool was_loaded = false
Detailed Description
template<typename T = int>
struct relic_procgen_data::enchantment_value_passive< T >
Definition at line 41 of file relic.h.
Member Function Documentation
calc_power()
template<typename T = int> int relic_procgen_data::enchantment_value_passive< T >::calc_power (T level) const inline
Definition at line 52 of file relic.h.
{
                 return std::round( level * static_cast<float>( power_per_increment ) /
                                    static_cast<float>( increment ) );
             }
References relic_procgen_data::enchantment_value_passive< T >::increment, relic_procgen_data::enchantment_value_passive< T >::power_per_increment, and round().
deserialize()
template<typename T = int> void relic_procgen_data::enchantment_value_passive< T >::deserialize (const JsonObject & jo)
Definition at line 141 of file relic.cpp.
 {
     load( jo );
 }
References ammo_effects::load().
load()
template<typename T = int> void relic_procgen_data::enchantment_value_passive< T >::load (const JsonObject & jo)
Definition at line 130 of file relic.cpp.
 {
     mandatory( jo, was_loaded, "type", type );
     optional( jo, was_loaded, "power_per_increment", power_per_increment, 1 );
     optional( jo, was_loaded, "increment", increment, 1 );
     optional( jo, was_loaded, "min_value", min_value, 0 );
     optional( jo, was_loaded, "max_value", max_value, 0 );
     optional( jo, was_loaded, "ench_has", ench_has );
 }
References mandatory(), and optional().
Referenced by relic_procgen_data::load().
Member Data Documentation
ench_has
template<typename T = int> enchantment::has relic_procgen_data::enchantment_value_passive< T >::ench_has
Definition at line 50 of file relic.h.
Referenced by relic_procgen_data::generate().
increment
template<typename T = int> T relic_procgen_data::enchantment_value_passive< T >::increment = 1
Definition at line 47 of file relic.h.
Referenced by relic_procgen_data::enchantment_value_passive< T >::calc_power().
max_value
template<typename T = int> T relic_procgen_data::enchantment_value_passive< T >::max_value = 0
Definition at line 49 of file relic.h.
Referenced by relic_procgen_data::generate().
min_value
template<typename T = int> T relic_procgen_data::enchantment_value_passive< T >::min_value = 0
Definition at line 48 of file relic.h.
Referenced by relic_procgen_data::generate().
power_per_increment
template<typename T = int> int relic_procgen_data::enchantment_value_passive< T >::power_per_increment = 1
Definition at line 44 of file relic.h.
Referenced by relic_procgen_data::enchantment_value_passive< T >::calc_power().
type
template<typename T = int> enchant_vals::mod relic_procgen_data::enchantment_value_passive< T >::type
Definition at line 42 of file relic.h.
Referenced by relic_procgen_data::generate().
was_loaded
template<typename T = int> bool relic_procgen_data::enchantment_value_passive< T >::was_loaded = false
Definition at line 57 of file relic.h.
The documentation for this struct was generated from the following files:
src/relic.h
src/relic.cpp