Cataclysm DDA: json_item_substitution::substitution::info Struct Reference
json_item_substitution::substitution::info Struct Reference
Public Member Functions
info (const JsonValue &value)
info ()=default
Public Attributes
itype_id new_item
double ratio = 1.0
Detailed Description
Definition at line 57 of file profession.cpp.
Constructor & Destructor Documentation
info() [1/2]
json_item_substitution::substitution::info::info (const JsonValue & value) explicit
Definition at line 736 of file profession.cpp.
 {
     if( value.test_string() ) {
         value.read( new_item, true );
     } else {
         const JsonObject jo = value.get_object();
         jo.read( "item", new_item, true );
         ratio = jo.get_float( "ratio" );
         if( ratio <= 0.0 ) {
             jo.throw_error_at( "ratio", "Ratio must be positive" );
         }
     }
 }
References JsonObject::get_float(), JsonValue::get_object(), new_item, ratio, JsonValue::read(), JsonObject::read(), JsonValue::test_string(), and JsonObject::throw_error_at().
info() [2/2]
json_item_substitution::substitution::info::info () default
Member Data Documentation
new_item
itype_id json_item_substitution::substitution::info::new_item
Definition at line 60 of file profession.cpp.
Referenced by json_item_substitution::check_consistency(), json_item_substitution::get_substitution(), and info().
ratio
double json_item_substitution::substitution::info::ratio = 1.0
Definition at line 61 of file profession.cpp.
Referenced by json_item_substitution::get_substitution(), and info().
The documentation for this struct was generated from the following file:
src/profession.cpp