Cataclysm DDA: abstract_str_or_var< T > Struct Template Reference
abstract_str_or_var< T > Struct Template Reference
#include <dialogue_helpers.h>
Public Member Functions
std::string evaluate (dialogue const &) const
Public Attributes
std::optional< T > str_val
std::optional< abstract_var_info< T > > var_val
std::optional< T > default_val
std::optional< std::function< T(const dialogue &)> > function
Detailed Description
template<class T>
struct abstract_str_or_var< T >
Definition at line 48 of file dialogue_helpers.h.
Member Function Documentation
evaluate()
std::string translation_or_var::evaluate (dialogue const & d) const
Definition at line 126 of file dialogue_helpers.cpp.
 {
     if( function.has_value() ) {
         return function.value()( d ).translated();
     }
     if( str_val.has_value() ) {
         return str_val.value().translated();
     }
     if( var_val.has_value() ) {
         std::string val = read_var_value( var_val.value(), d );
         if( !val.empty() ) {
             return val;
         }
         if( default_val.has_value() ) {
             return default_val.value().translated();
         }
         std::string var_name = var_val.value().name;
         if( var_name.find( "npctalk_var" ) != std::string::npos ) {
             var_name = var_name.substr( 12 );
         }
         debugmsg( "No default value provided for str_or_var_part while encountering unused "
                   "variable %s.  Add a \"default_str\" member to prevent this.  %s",
                   var_name, d.get_callstack() );
         return "";
     }
     debugmsg( "No valid value for str_or_var_part.  %s", d.get_callstack() );
     return "";
 }
References debugmsg, abstract_str_or_var< T >::default_val, dialogue::get_callstack(), read_var_value(), abstract_str_or_var< T >::str_val, and abstract_str_or_var< T >::var_val.
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_activate_trait(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_bionic(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_morale(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_trait(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_alter_timed_events(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_attack(), conditional_fun::anonymous_namespace{condition.cpp}::f_bodytype(), conditional_fun::anonymous_namespace{condition.cpp}::f_can_see_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_clear_npc_rule(), conditional_fun::anonymous_namespace{condition.cpp}::f_compare_string(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_custom_light_level(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_deactivate_trait(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_finish_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_forget_martial_art(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_forget_recipe(), conditional_fun::anonymous_namespace{condition.cpp}::f_get_condition(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_give_achievment(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_bionics(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_effect(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_item(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_item_category(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_item_with_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_items(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_martial_art(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_move_mode(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_proficiency(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_species(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_trait(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_visible_trait(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_wielded_with_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_wielded_with_weapon_category(), conditional_fun::anonymous_namespace{condition.cpp}::f_has_worn_with_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_on_terrain(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_on_terrain_with_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_season(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_wearing(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_learn_martial_art(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_learn_recipe(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_bionic(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lose_morale(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_make_sound(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_in_city(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_map_run_item_eocs(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_id(), conditional_fun::anonymous_namespace{condition.cpp}::f_map_ter_furn_with_flag(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), conditional_fun::anonymous_namespace{condition.cpp}::f_mission_goal(), conditional_fun::anonymous_namespace{condition.cpp}::f_mod_is_loaded(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate_category(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate_towards(), conditional_fun::anonymous_namespace{condition.cpp}::f_need(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_aim_rule(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_aim_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_cbm_recharge_rule(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_cbm_recharge_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_cbm_reserve_rule(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_cbm_reserve_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_change_class(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_change_faction(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_engagement_rule(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_engagement_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_npc_first_topic(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_has_class(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_override(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_role_nearby(), conditional_fun::anonymous_namespace{condition.cpp}::f_npc_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_open_dialogue(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_place_override(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_active_mission(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_trait(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_inv_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_condition(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_flag(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_set_npc_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_sound_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport(), conditional_fun::anonymous_namespace{condition.cpp}::f_test_eoc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_toggle_npc_rule(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_monster(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_has_mission(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_know_recipe(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_monsters_in_direction(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_profession(), conditional_fun::anonymous_namespace{condition.cpp}::f_u_safe_mode_trigger(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_unset_flag(), conditional_fun::anonymous_namespace{condition.cpp}::f_using_martial_art(), emit::field(), find_or_create_om_terrain(), get_get_str_(), get_get_translation_(), and mission_util::get_om_terrain_pos().
Member Data Documentation
default_val
template<class T > std::optional<T> abstract_str_or_var< T >::default_val
Definition at line 51 of file dialogue_helpers.h.
Referenced by abstract_str_or_var< T >::evaluate(), and mission_util::get_om_terrain_pos().
function
template<class T > std::optional<std::function<T(const dialogue &)> > abstract_str_or_var< T >::function
Definition at line 52 of file dialogue_helpers.h.
str_val
template<class T > std::optional<T> abstract_str_or_var< T >::str_val
Definition at line 49 of file dialogue_helpers.h.
Referenced by abstract_str_or_var< T >::evaluate(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_trait(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), conditional_fun::anonymous_namespace{condition.cpp}::f_compare_string(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_custom_light_level(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_message(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mutate_towards(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_place_override(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_remove_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_item(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_teleport(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_item(), and mission_util::get_om_terrain_pos().
var_val
template<class T > std::optional<abstract_var_info<T> > abstract_str_or_var< T >::var_val
Definition at line 50 of file dialogue_helpers.h.
Referenced by abstract_str_or_var< T >::evaluate(), and mission_util::get_om_terrain_pos().
The documentation for this struct was generated from the following files:
src/dialogue_helpers.h
src/dialogue_helpers.cpp