Cataclysm DDA: anonymous_namespace{recipe_groups.cpp}::recipe_group_data Struct Reference
anonymous_namespace{recipe_groups.cpp}::recipe_group_data Struct Reference
Public Member Functions
void load (const JsonObject &jo, std::string_view src)
void check () const
Public Attributes
group_id id
std::vector< std::pair< group_id, mod_id > > src
std::string building_type = "NONE"
std::map< recipe_id, translation > recipes
std::map< recipe_id, std::vector< omt_types_parameters > > om_terrains
bool was_loaded = false
Detailed Description
Definition at line 30 of file recipe_groups.cpp.
Member Function Documentation
check()
void recipe_group_data::check () const
Definition at line 76 of file recipe_groups.cpp.
 {
     for( const auto &a : recipes ) {
         if( !a.first.is_valid() ) {
             debugmsg( "%s is not a valid recipe", a.first.c_str() );
         }
     }
 }
References a, and debugmsg.
load()
void recipe_group_data::load (const JsonObject & jo, std::string_view src)
Definition at line 46 of file recipe_groups.cpp.
 {
     building_type = jo.get_string( "building_type" );
     for( JsonObject ordering : jo.get_array( "recipes" ) ) {
         recipe_id name_id;
         ordering.read( "id", name_id );
         translation desc;
         ordering.read( "description", desc );
         recipes.emplace( name_id, desc );
         for( const JsonValue jv : ordering.get_array( "om_terrains" ) ) {
             std::string ter;
             ot_match_type ter_match_type = ot_match_type::type;
             std::unordered_map<std::string, std::unordered_set<std::string>> parameter_map;
             if( jv.test_string() ) {
                 ter = jv.get_string();
             } else {
                 JsonObject jo = jv.get_object();
                 ter = jo.get_string( "om_terrain" );
                 if( jo.has_string( "om_terrain_match_type" ) ) {
                     ter_match_type = jo.get_enum_value<ot_match_type>( "om_terrain_match_type", ter_match_type );
                 }
                 if( jo.has_object( "parameters" ) ) {
                     jo.read( "parameters", parameter_map );
                 }
             }
             om_terrains[name_id].emplace_back( omt_types_parameters{ ter, ter_match_type, parameter_map } );
         }
     }
 }
References JsonValue::get_array(), JsonObject::get_array(), JsonObject::get_enum_value(), JsonObject::get_object(), JsonObject::get_string(), JsonObject::has_object(), JsonObject::has_string(), JsonObject::read(), and type.
Member Data Documentation
building_type
std::string anonymous_namespace{recipe_groups.cpp}::recipe_group_data::building_type = "NONE"
Definition at line 33 of file recipe_groups.cpp.
id
group_id anonymous_namespace{recipe_groups.cpp}::recipe_group_data::id
Definition at line 31 of file recipe_groups.cpp.
om_terrains
std::map<recipe_id, std::vector<omt_types_parameters> > anonymous_namespace{recipe_groups.cpp}::recipe_group_data::om_terrains
Definition at line 35 of file recipe_groups.cpp.
recipes
std::map<recipe_id, translation> anonymous_namespace{recipe_groups.cpp}::recipe_group_data::recipes
Definition at line 34 of file recipe_groups.cpp.
src
std::vector<std::pair<group_id, mod_id> > anonymous_namespace{recipe_groups.cpp}::recipe_group_data::src
Definition at line 32 of file recipe_groups.cpp.
was_loaded
bool anonymous_namespace{recipe_groups.cpp}::recipe_group_data::was_loaded = false
Definition at line 36 of file recipe_groups.cpp.
The documentation for this struct was generated from the following file:
src/recipe_groups.cpp