Cataclysm DDA: pointmenu_cb::impl_t Struct Reference
pointmenu_cb::impl_t Struct Reference
Public Member Functions
impl_t (const std::vector< tripoint > &pts)
~impl_t ()
void select (uilist *menu)
Public Attributes
const std::vector< tripoint > & points
int last
tripoint last_view
shared_ptr_fast< game::draw_callback_t > terrain_draw_cb
Detailed Description
Definition at line 1349 of file ui.cpp.
Constructor & Destructor Documentation
impl_t()
pointmenu_cb::impl_t::impl_t (const std::vector< tripoint > & pts) explicit
Definition at line 1361 of file ui.cpp.
                                                            : points( pts )
 {
     last = INT_MIN;
     avatar &player_character = get_avatar();
     last_view = player_character.view_offset;
     terrain_draw_cb = make_shared_fast<game::draw_callback_t>( [this, &player_character]() {
         if( last >= 0 && static_cast<size_t>( last ) < points.size() ) {
             g->draw_trail_to_square( player_character.view_offset, true );
         }
     } );
     g->add_draw_callback( terrain_draw_cb );
 }
References g, get_avatar(), last, last_view, points, terrain_draw_cb, and Character::view_offset.
~impl_t()
pointmenu_cb::impl_t::~impl_t ()
Definition at line 1374 of file ui.cpp.
 {
     get_avatar().view_offset = last_view;
 }
References get_avatar(), and Character::view_offset.
Member Function Documentation
select()
void pointmenu_cb::impl_t::select (uilist * menu)
Definition at line 1379 of file ui.cpp.
 {
     if( last == menu->selected ) {
         return;
     }
     last = menu->selected;
     avatar &player_character = get_avatar();
     if( menu->selected < 0 || menu->selected >= static_cast<int>( points.size() ) ) {
         player_character.view_offset = tripoint_zero;
     } else {
         const tripoint &center = points[menu->selected];
         player_character.view_offset = center - player_character.pos();
         // TODO: Remove this line when it's safe
         player_character.view_offset.z = 0;
     }
     g->invalidate_main_ui_adaptor();
 }
References center, g, get_avatar(), last, Creature::pos(), uilist::selected, tripoint_zero, Character::view_offset, and tripoint::z.
Member Data Documentation
last
int pointmenu_cb::impl_t::last
Definition at line 1351 of file ui.cpp.
Referenced by impl_t().
last_view
tripoint pointmenu_cb::impl_t::last_view
Definition at line 1352 of file ui.cpp.
Referenced by impl_t().
points
const std::vector< tripoint >& pointmenu_cb::impl_t::points
Definition at line 1350 of file ui.cpp.
Referenced by impl_t().
terrain_draw_cb
shared_ptr_fast<game::draw_callback_t> pointmenu_cb::impl_t::terrain_draw_cb
Definition at line 1353 of file ui.cpp.
Referenced by impl_t().
The documentation for this struct was generated from the following file:
src/ui.cpp