Cataclysm DDA: anonymous_namespace{crafting_gui.cpp}::availability Struct Reference
anonymous_namespace{crafting_gui.cpp}::availability Struct Reference
Public Member Functions
availability (Character &_crafter, const recipe *r, int batch_size=1)
float get_proficiency_time_maluses () const
float get_max_proficiency_time_maluses () const
float get_proficiency_skill_maluses () const
float get_max_proficiency_skill_maluses () const
nc_color selected_color () const
nc_color color (bool ignore_missing_skills=false) const
Static Public Member Functions
static bool check_can_craft_nested (Character &_crafter, const recipe &r)
Public Attributes
Character & crafter
bool can_craft
bool crafter_has_primary_skill
bool would_use_rotten
bool would_use_favorite
bool useless_practice
bool apparently_craftable
bool has_proficiencies
bool has_all_skills
bool is_nested_category
Private Attributes
const recipe * rec
float proficiency_time_maluses = -1.0f
float max_proficiency_time_maluses = -1.0f
float proficiency_skill_maluses = -1.0f
float max_proficiency_skill_maluses = -1.0f
Detailed Description
Definition at line 193 of file crafting_gui.cpp.
Constructor & Destructor Documentation
availability()
anonymous_namespace{crafting_gui.cpp}::availability::availability (Character & _crafter, const recipe * r, int batch_size = 1) inline explicit
Definition at line 194 of file crafting_gui.cpp.
                                                                                           :
             crafter( _crafter ) {
             rec = r;
             const inventory &inv = crafter.crafting_inventory();
             auto all_items_filter = r->get_component_filter( recipe_filter_flags::none );
             auto no_rotten_filter = r->get_component_filter( recipe_filter_flags::no_rotten );
             auto no_favorite_filter = r->get_component_filter( recipe_filter_flags::no_favorite );
             const deduped_requirement_data &req = r->deduped_requirements();
             has_all_skills = r->skill_used.is_null() ||
                              crafter.get_skill_level( r->skill_used ) >= r->get_difficulty( crafter );
             crafter_has_primary_skill = r->skill_used.is_null()
                                         || crafter.get_knowledge_level( rec->skill_used )
                                         >= static_cast<int>( rec->get_difficulty( crafter ) * 0.8f );
             has_proficiencies = r->character_has_required_proficiencies( crafter );
             std::string reason;
             if( crafter.is_npc() && !r->npc_can_craft( reason ) ) {
                 can_craft = false;
             } else if( r->is_nested() ) {
                 can_craft = check_can_craft_nested( _crafter, *r );
             } else {
                 can_craft = ( !r->is_practice() || has_all_skills ) && has_proficiencies &&
                             req.can_make_with_inventory( inv, all_items_filter, batch_size, craft_flags::start_only );
             }
             would_use_rotten = !req.can_make_with_inventory( inv, no_rotten_filter, batch_size,
                                craft_flags::start_only );
             would_use_favorite = !req.can_make_with_inventory( inv, no_favorite_filter, batch_size,
                                  craft_flags::start_only );
             useless_practice = r->is_practice() && cannot_gain_skill_or_prof( crafter, *r );
             is_nested_category = r->is_nested();
             const requirement_data &simple_req = r->simple_requirements();
             apparently_craftable = ( !r->is_practice() || has_all_skills ) && has_proficiencies &&
                                    simple_req.can_make_with_inventory( inv, all_items_filter, batch_size, craft_flags::start_only );
             for( const auto& [skill, skill_lvl] : r->required_skills ) {
                 if( crafter.get_skill_level( skill ) < skill_lvl ) {
                     has_all_skills = false;
                     break;
                 }
             }
         }
References requirement_data::can_make_with_inventory(), deduped_requirement_data::can_make_with_inventory(), cannot_gain_skill_or_prof(), recipe::character_has_required_proficiencies(), recipe::deduped_requirements(), recipe::get_component_filter(), recipe::get_difficulty(), recipe::is_nested(), string_id< T >::is_null(), recipe::is_practice(), no_favorite, no_rotten, none, recipe::npc_can_craft(), recipe::required_skills, recipe::simple_requirements(), recipe::skill_used, and start_only.
Member Function Documentation
check_can_craft_nested()
static bool anonymous_namespace{crafting_gui.cpp}::availability::check_can_craft_nested (Character & _crafter, const recipe & r) inline static
Definition at line 320 of file crafting_gui.cpp.
{
             // recursively check if you can craft anything in the nest
             for( const recipe_id &nested_r : r.nested_category_data ) {
                 if( availability( _crafter, &nested_r.obj() ).can_craft ) {
                     return true;
                 }
             }
             return false;
         }
References can_craft, recipe::nested_category_data, and string_id< T >::obj().
color()
nc_color anonymous_namespace{crafting_gui.cpp}::availability::color (bool ignore_missing_skills = false) const inline
Definition at line 300 of file crafting_gui.cpp.
{
             if( !can_craft && is_nested_category ) {
                 return c_blue;
             } else if( !can_craft ) {
                 return c_dark_gray;
             } else if( !crafter_has_primary_skill && is_nested_category ) {
                 return c_magenta;
             } else if( !crafter_has_primary_skill ) {
                 return c_light_red;
             } else if( is_nested_category ) {
                 return c_light_blue;
             } else if( would_use_rotten || useless_practice ) {
                 return has_all_skills || ignore_missing_skills ? c_brown : c_red;
             } else if( would_use_favorite ) {
                 return has_all_skills ? c_pink : c_red;
             } else {
                 return has_all_skills || ignore_missing_skills ? c_white : c_yellow;
             }
         }
References c_blue, c_brown, c_dark_gray, c_light_blue, c_light_red, c_magenta, c_pink, c_red, c_white, and c_yellow.
get_max_proficiency_skill_maluses()
float anonymous_namespace{crafting_gui.cpp}::availability::get_max_proficiency_skill_maluses () const inline
Definition at line 272 of file crafting_gui.cpp.
{
             if( max_proficiency_skill_maluses < 0 ) {
                 max_proficiency_skill_maluses = rec->max_proficiency_skill_maluses( crafter );
             }
             return max_proficiency_skill_maluses;
         }
References recipe::max_proficiency_skill_maluses().
get_max_proficiency_time_maluses()
float anonymous_namespace{crafting_gui.cpp}::availability::get_max_proficiency_time_maluses () const inline
Definition at line 258 of file crafting_gui.cpp.
{
             if( max_proficiency_time_maluses < 0 ) {
                 max_proficiency_time_maluses = rec->max_proficiency_time_maluses( crafter );
             }
             return max_proficiency_time_maluses;
         }
References recipe::max_proficiency_time_maluses().
get_proficiency_skill_maluses()
float anonymous_namespace{crafting_gui.cpp}::availability::get_proficiency_skill_maluses () const inline
Definition at line 265 of file crafting_gui.cpp.
{
             if( proficiency_skill_maluses < 0 ) {
                 proficiency_skill_maluses = rec->proficiency_skill_maluses( crafter );
             }
             return proficiency_skill_maluses;
         }
References recipe::proficiency_skill_maluses().
get_proficiency_time_maluses()
float anonymous_namespace{crafting_gui.cpp}::availability::get_proficiency_time_maluses () const inline
Definition at line 251 of file crafting_gui.cpp.
{
             if( proficiency_time_maluses < 0 ) {
                 proficiency_time_maluses = rec->proficiency_time_maluses( crafter );
             }
             return proficiency_time_maluses;
         }
References recipe::proficiency_time_maluses().
selected_color()
nc_color anonymous_namespace{crafting_gui.cpp}::availability::selected_color () const inline
Definition at line 280 of file crafting_gui.cpp.
{
             if( !can_craft && is_nested_category ) {
                 return h_blue;
             } else if( !can_craft ) {
                 return h_dark_gray;
             } else if( !crafter_has_primary_skill && is_nested_category ) {
                 return h_magenta;
             } else if( !crafter_has_primary_skill ) {
                 return h_light_red;
             } else if( is_nested_category ) {
                 return h_light_blue;
             }  else if( would_use_rotten || useless_practice ) {
                 return has_all_skills ? h_brown : h_red;
             } else if( would_use_favorite ) {
                 return has_all_skills ? h_pink : h_red;
             } else {
                 return has_all_skills ? h_white : h_yellow;
             }
         }
References h_blue, h_brown, h_dark_gray, h_light_blue, h_light_red, h_magenta, h_pink, h_red, h_white, and h_yellow.
Member Data Documentation
apparently_craftable
bool anonymous_namespace{crafting_gui.cpp}::availability::apparently_craftable
Definition at line 240 of file crafting_gui.cpp.
can_craft
bool anonymous_namespace{crafting_gui.cpp}::availability::can_craft
Definition at line 234 of file crafting_gui.cpp.
Referenced by check_can_craft_nested().
crafter
Character& anonymous_namespace{crafting_gui.cpp}::availability::crafter
Definition at line 233 of file crafting_gui.cpp.
crafter_has_primary_skill
bool anonymous_namespace{crafting_gui.cpp}::availability::crafter_has_primary_skill
Definition at line 236 of file crafting_gui.cpp.
has_all_skills
bool anonymous_namespace{crafting_gui.cpp}::availability::has_all_skills
Definition at line 242 of file crafting_gui.cpp.
has_proficiencies
bool anonymous_namespace{crafting_gui.cpp}::availability::has_proficiencies
Definition at line 241 of file crafting_gui.cpp.
is_nested_category
bool anonymous_namespace{crafting_gui.cpp}::availability::is_nested_category
Definition at line 243 of file crafting_gui.cpp.
max_proficiency_skill_maluses
float anonymous_namespace{crafting_gui.cpp}::availability::max_proficiency_skill_maluses = -1.0f mutable private
Definition at line 249 of file crafting_gui.cpp.
max_proficiency_time_maluses
float anonymous_namespace{crafting_gui.cpp}::availability::max_proficiency_time_maluses = -1.0f mutable private
Definition at line 247 of file crafting_gui.cpp.
proficiency_skill_maluses
float anonymous_namespace{crafting_gui.cpp}::availability::proficiency_skill_maluses = -1.0f mutable private
Definition at line 248 of file crafting_gui.cpp.
proficiency_time_maluses
float anonymous_namespace{crafting_gui.cpp}::availability::proficiency_time_maluses = -1.0f mutable private
Definition at line 246 of file crafting_gui.cpp.
rec
const recipe* anonymous_namespace{crafting_gui.cpp}::availability::rec private
Definition at line 245 of file crafting_gui.cpp.
useless_practice
bool anonymous_namespace{crafting_gui.cpp}::availability::useless_practice
Definition at line 239 of file crafting_gui.cpp.
would_use_favorite
bool anonymous_namespace{crafting_gui.cpp}::availability::would_use_favorite
Definition at line 238 of file crafting_gui.cpp.
would_use_rotten
bool anonymous_namespace{crafting_gui.cpp}::availability::would_use_rotten
Definition at line 237 of file crafting_gui.cpp.
The documentation for this struct was generated from the following file:
src/crafting_gui.cpp