Cataclysm DDA: auto_navigation_data Struct Reference
auto_navigation_data Struct Reference
Data structure that caches all the data needed in order to navigate from one OMT to the next OMT along the path to destination.
Public Member Functions
void clear ()
vehicle_profile & profile (orientation dir)
const vehicle_profile & profile (orientation dir) const
bool & valid_position (orientation dir, point p)
bool valid_position (orientation dir, point p) const
bool valid_position (const node_address &addr) const
point to_view (const tripoint_abs_ms &p) const
point to_view (const tripoint_bub_ms &p) const
template<typename Tripoint >
Tripoint adjust_z (const Tripoint &p) const
Public Attributes
tripoint_abs_omt current_omt
tripoint_abs_omt next_omt
tripoint_abs_omt next_next_omt
half_open_rectangle< point > view_bounds
half_open_rectangle< point > nav_bounds
half_open_rectangle< point > next_omt_bounds
coord_transformation nav_to_map
coord_transformation view_to_map
coord_transformation nav_to_view
bool land_ok
bool water_ok
bool air_ok
int max_speed_tps
std::vector< int > acceleration
int max_steer
std::array< vehicle_profile, NUM_ORIENTATIONS > profiles
cata::mdarray< bool, point, NAV_VIEW_SIZE_X, NAV_VIEW_SIZE_Y > is_obstacle
cata::mdarray< int, point, NAV_VIEW_SIZE_X, NAV_VIEW_SIZE_Y > ground_z
std::array< cata::mdarray< bool, point, NAV_VIEW_SIZE_X, NAV_VIEW_SIZE_Y >, NUM_ORIENTATIONS > valid_positions
std::unordered_set< node_address, node_address_hasher > goal_zone
std::array< point, NAV_MAP_NUM_OMT > goal_points
std::vector< navigation_step > path
Detailed Description
Data structure that caches all the data needed in order to navigate from one OMT to the next OMT along the path to destination.
Main components:
the view map (precomputed obstacle positions)
the nav map (valid positions and orientations where the vehicle pivot may be placed)
the navigation path found by A* search
Definition at line 282 of file vehicle_autodrive.cpp.
Member Function Documentation
adjust_z()
template<typename Tripoint > Tripoint auto_navigation_data::adjust_z (const Tripoint & p) const
Definition at line 603 of file vehicle_autodrive.cpp.
 {
     if( !land_ok ) {
         return p;
     }
     const point pt_view = to_view( p );
     if( !view_bounds.contains( pt_view ) ) {
         debugmsg( "Autodrive tried to adjust zlevel on out-of-bounds point p=%s", p.to_string() );
         return p; // shouldn't happen, but who knows.
     }
     return { p.xy(), ground_z[pt_view] };
 }
References half_open_rectangle< Point, >::contains(), debugmsg, ground_z, land_ok, to_view(), and view_bounds.
clear()
void auto_navigation_data::clear () inline
Definition at line 327 of file vehicle_autodrive.cpp.
                  {
         current_omt = { 0, 0, -100 };
         path.clear();
     }
References current_omt, and path.
Referenced by vehicle::autodrive_controller::autodrive_controller().
profile() [1/2]
vehicle_profile& auto_navigation_data::profile (orientation dir) inline
Definition at line 331 of file vehicle_autodrive.cpp.
{
         return profiles.at( static_cast<int>( dir ) );
     }
References profiles.
Referenced by vehicle::get_debug_overlay_data().
profile() [2/2]
const vehicle_profile& auto_navigation_data::profile (orientation dir) const inline
Definition at line 334 of file vehicle_autodrive.cpp.
{
         return profiles.at( static_cast<int>( dir ) );
     }
References profiles.
to_view() [1/2]
point auto_navigation_data::to_view (const tripoint_abs_ms & p) const inline
Definition at line 347 of file vehicle_autodrive.cpp.
{
         return view_to_map.inverse().transform( p.raw().xy() );
     }
References coord_transformation::inverse(), coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), coord_transformation::transform(), and view_to_map.
Referenced by adjust_z(), and to_view().
to_view() [2/2]
point auto_navigation_data::to_view (const tripoint_bub_ms & p) const inline
Definition at line 351 of file vehicle_autodrive.cpp.
{
         return to_view( get_map().getglobal( p ) );
     }
References get_map(), and to_view().
valid_position() [1/3]
bool auto_navigation_data::valid_position (const node_address & addr) const inline
Definition at line 343 of file vehicle_autodrive.cpp.
{
         return valid_position( addr.facing_dir, point( addr.x, addr.y ) );
     }
References node_address::facing_dir, valid_position(), node_address::x, and node_address::y.
valid_position() [2/3]
bool& auto_navigation_data::valid_position (orientation dir, point p) inline
Definition at line 337 of file vehicle_autodrive.cpp.
{
         return valid_positions[static_cast<int>( dir )][p.x][p.y];
     }
References valid_positions, point::x, and point::y.
Referenced by vehicle::get_debug_overlay_data(), and valid_position().
valid_position() [3/3]
bool auto_navigation_data::valid_position (orientation dir, point p) const inline
Definition at line 340 of file vehicle_autodrive.cpp.
{
         return valid_positions[static_cast<int>( dir )][p.x][p.y];
     }
References valid_positions, point::x, and point::y.
Member Data Documentation
acceleration
std::vector<int> auto_navigation_data::acceleration
Definition at line 306 of file vehicle_autodrive.cpp.
air_ok
bool auto_navigation_data::air_ok
Definition at line 302 of file vehicle_autodrive.cpp.
current_omt
tripoint_abs_omt auto_navigation_data::current_omt
Definition at line 283 of file vehicle_autodrive.cpp.
Referenced by clear(), vehicle::autodrive_controller::compute_coordinates(), and vehicle::get_debug_overlay_data().
goal_points
std::array<point, NAV_MAP_NUM_OMT> auto_navigation_data::goal_points
Definition at line 322 of file vehicle_autodrive.cpp.
Referenced by vehicle::get_debug_overlay_data().
goal_zone
std::unordered_set<node_address, node_address_hasher> auto_navigation_data::goal_zone
Definition at line 320 of file vehicle_autodrive.cpp.
Referenced by vehicle::get_debug_overlay_data().
ground_z
cata::mdarray<int, point, NAV_VIEW_SIZE_X, NAV_VIEW_SIZE_Y> auto_navigation_data::ground_z
Definition at line 315 of file vehicle_autodrive.cpp.
Referenced by adjust_z().
is_obstacle
cata::mdarray<bool, point, NAV_VIEW_SIZE_X, NAV_VIEW_SIZE_Y> auto_navigation_data::is_obstacle
Definition at line 312 of file vehicle_autodrive.cpp.
Referenced by vehicle::get_debug_overlay_data().
land_ok
bool auto_navigation_data::land_ok
Definition at line 300 of file vehicle_autodrive.cpp.
Referenced by adjust_z().
max_speed_tps
int auto_navigation_data::max_speed_tps
Definition at line 304 of file vehicle_autodrive.cpp.
max_steer
int auto_navigation_data::max_steer
Definition at line 308 of file vehicle_autodrive.cpp.
nav_bounds
half_open_rectangle<point> auto_navigation_data::nav_bounds
Definition at line 290 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_coordinates().
nav_to_map
coord_transformation auto_navigation_data::nav_to_map
Definition at line 294 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_coordinates(), and vehicle::get_debug_overlay_data().
nav_to_view
coord_transformation auto_navigation_data::nav_to_view
Definition at line 298 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_coordinates().
next_next_omt
tripoint_abs_omt auto_navigation_data::next_next_omt
Definition at line 285 of file vehicle_autodrive.cpp.
next_omt
tripoint_abs_omt auto_navigation_data::next_omt
Definition at line 284 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_coordinates().
next_omt_bounds
half_open_rectangle<point> auto_navigation_data::next_omt_bounds
Definition at line 292 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_coordinates().
path
std::vector<navigation_step> auto_navigation_data::path
Definition at line 325 of file vehicle_autodrive.cpp.
Referenced by clear(), and vehicle::get_debug_overlay_data().
profiles
std::array<vehicle_profile, NUM_ORIENTATIONS> auto_navigation_data::profiles
Definition at line 310 of file vehicle_autodrive.cpp.
Referenced by profile().
valid_positions
std::array<cata::mdarray<bool, point, NAV_VIEW_SIZE_X, NAV_VIEW_SIZE_Y>, NUM_ORIENTATIONS> auto_navigation_data::valid_positions
Definition at line 318 of file vehicle_autodrive.cpp.
Referenced by valid_position().
view_bounds
half_open_rectangle<point> auto_navigation_data::view_bounds
Definition at line 288 of file vehicle_autodrive.cpp.
Referenced by adjust_z(), and vehicle::autodrive_controller::compute_coordinates().
view_to_map
coord_transformation auto_navigation_data::view_to_map
Definition at line 296 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_coordinates(), vehicle::get_debug_overlay_data(), and to_view().
water_ok
bool auto_navigation_data::water_ok
Definition at line 301 of file vehicle_autodrive.cpp.
The documentation for this struct was generated from the following file:
src/vehicle_autodrive.cpp