Cataclysm DDA: duration_or_var Struct Reference
duration_or_var Struct Reference
#include <dialogue_helpers.h>
Public Member Functions
time_duration evaluate (dialogue &d) const
Public Attributes
bool pair = false
duration_or_var_part min
duration_or_var_part max
Detailed Description
Definition at line 197 of file dialogue_helpers.h.
Member Function Documentation
evaluate()
time_duration duration_or_var::evaluate (dialogue & d) const
Definition at line 230 of file dialogue_helpers.cpp.
 {
     if( pair ) {
         return rng( min.evaluate( d ), max.evaluate( d ) );
     }
     return min.evaluate( d );
 }
References duration_or_var_part::evaluate(), max, min, pair, and rng().
Referenced by talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_effect(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_add_morale(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_alter_timed_events(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_assign_activity(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_custom_light_level(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_field(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_place_override(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eoc_with(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_queue_eocs(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_monster(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_spawn_npc(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), and talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_turn_cost().
Member Data Documentation
max
duration_or_var_part duration_or_var::max
Definition at line 200 of file dialogue_helpers.h.
Referenced by evaluate().
min
duration_or_var_part duration_or_var::min
Definition at line 199 of file dialogue_helpers.h.
Referenced by evaluate().
pair
bool duration_or_var::pair = false
Definition at line 198 of file dialogue_helpers.h.
Referenced by evaluate().
The documentation for this struct was generated from the following files:
src/dialogue_helpers.h
src/dialogue_helpers.cpp