Cataclysm DDA: drawsq_params Struct Reference
drawsq_params Struct Reference
Draw parameters used by map::drawsq() and similar methods.
#include <map.h>
Public Member Functions
constexpr drawsq_params ()=default
constexpr drawsq_params & highlight (bool v)
Highlight the tile.
constexpr bool highlight () const
constexpr drawsq_params & show_items (bool v)
Whether to draw items on the tile.
constexpr bool show_items () const
constexpr drawsq_params & low_light (bool v)
Whether tile is low light, and should be drawn with muted color.
constexpr bool low_light () const
constexpr drawsq_params & bright_light (bool v)
Whether tile is in bright light.
constexpr bool bright_light () const
constexpr drawsq_params & memorize (bool v)
Whether the tile should be memorized.
constexpr bool memorize () const
constexpr drawsq_params & output (bool v)
HACK: Whether the tile should be printed.
constexpr bool output () const
constexpr drawsq_params & center (const tripoint &p)
Set view center.
constexpr drawsq_params & center_at_avatar ()
tripoint center () const
Private Attributes
tripoint view_center = tripoint_min
bool do_highlight = false
bool do_show_items = true
bool do_low_light = false
bool do_bright_light = false
bool do_memorize = false
bool do_output = true
Detailed Description
Draw parameters used by map::drawsq() and similar methods.
Definition at line 168 of file map.h.
Constructor & Destructor Documentation
drawsq_params()
constexpr drawsq_params::drawsq_params () constexpr default
Member Function Documentation
bright_light() [1/2]
constexpr bool drawsq_params::bright_light () const inline constexpr
Definition at line 232 of file map.h.
{
             return do_bright_light;
         }
References do_bright_light.
bright_light() [2/2]
constexpr drawsq_params& drawsq_params::bright_light (bool v) inline constexpr
Whether tile is in bright light.
Affects NV overlay, and nothing else. Default: false;
Definition at line 228 of file map.h.
{
             do_bright_light = v;
             return *this;
         }
References do_bright_light.
Referenced by map::draw(), map::draw_from_above(), and map::draw_maptile().
center() [1/2]
tripoint drawsq_params::center () const
Definition at line 10549 of file map.cpp.
 {
     if( view_center == tripoint_min ) {
         avatar &player_character = get_avatar();
         return player_character.pos() + player_character.view_offset;
     } else {
         return view_center;
     }
 }
References get_avatar(), Creature::pos(), tripoint_min, view_center, and Character::view_offset.
center() [2/2]
constexpr drawsq_params& drawsq_params::center (const tripoint & p) inline constexpr
Set view center.
Default: uses avatar's current view center.
Definition at line 271 of file map.h.
{
             view_center = p;
             return *this;
         }
References view_center.
Referenced by anonymous_namespace{animation.cpp}::draw_line_curses(), editmap::draw_main_ui_overlay(), target_ui::draw_terrain_overlay(), map::drawsq(), and editmap::uber_draw_ter().
center_at_avatar()
constexpr drawsq_params& drawsq_params::center_at_avatar () inline constexpr
Definition at line 275 of file map.h.
{
             view_center = tripoint_min;
             return *this;
         }
References tripoint_min, and view_center.
highlight() [1/2]
constexpr bool drawsq_params::highlight () const inline constexpr
Definition at line 190 of file map.h.
{
             return do_highlight;
         }
References do_highlight.
highlight() [2/2]
constexpr drawsq_params& drawsq_params::highlight (bool v) inline constexpr
Highlight the tile.
On TILES, draws an overlay; on CURSES, inverts color. Default: false.
Definition at line 186 of file map.h.
{
             do_highlight = v;
             return *this;
         }
References do_highlight.
Referenced by map::draw_from_above(), anonymous_namespace{animation.cpp}::draw_line_curses(), map::draw_maptile(), target_ui::draw_terrain_overlay(), and map::drawsq().
low_light() [1/2]
constexpr bool drawsq_params::low_light () const inline constexpr
Definition at line 218 of file map.h.
{
             return do_low_light;
         }
References do_low_light.
low_light() [2/2]
constexpr drawsq_params& drawsq_params::low_light (bool v) inline constexpr
Whether tile is low light, and should be drawn with muted color.
Default: false.
Definition at line 214 of file map.h.
{
             do_low_light = v;
             return *this;
         }
References do_low_light.
Referenced by map::draw(), map::draw_from_above(), and map::draw_maptile().
memorize() [1/2]
constexpr bool drawsq_params::memorize () const inline constexpr
Definition at line 246 of file map.h.
{
             return do_memorize;
         }
References do_memorize.
memorize() [2/2]
constexpr drawsq_params& drawsq_params::memorize (bool v) inline constexpr
Whether the tile should be memorized.
Used only in map::draw(). Default: false.
Definition at line 242 of file map.h.
{
             do_memorize = v;
             return *this;
         }
References do_memorize.
Referenced by map::draw(), and map::draw_maptile().
output() [1/2]
constexpr bool drawsq_params::output () const inline constexpr
Definition at line 261 of file map.h.
{
             return do_output;
         }
References do_output.
output() [2/2]
constexpr drawsq_params& drawsq_params::output (bool v) inline constexpr
HACK: Whether the tile should be printed.
Used only in map::draw() as a hack for memorizing off-screen tiles. Default: true.
Definition at line 257 of file map.h.
{
             do_output = v;
             return *this;
         }
References do_output.
Referenced by map::draw(), map::draw_from_above(), and map::draw_maptile().
show_items() [1/2]
constexpr bool drawsq_params::show_items () const inline constexpr
Definition at line 204 of file map.h.
{
             return do_show_items;
         }
References do_show_items.
show_items() [2/2]
constexpr drawsq_params& drawsq_params::show_items (bool v) inline constexpr
Whether to draw items on the tile.
Default: true.
Definition at line 200 of file map.h.
{
             do_show_items = v;
             return *this;
         }
References do_show_items.
Referenced by map::draw_maptile().
Member Data Documentation
do_bright_light
bool drawsq_params::do_bright_light = false private
Definition at line 174 of file map.h.
Referenced by bright_light().
do_highlight
bool drawsq_params::do_highlight = false private
Definition at line 171 of file map.h.
Referenced by highlight().
do_low_light
bool drawsq_params::do_low_light = false private
Definition at line 173 of file map.h.
Referenced by low_light().
do_memorize
bool drawsq_params::do_memorize = false private
Definition at line 175 of file map.h.
Referenced by memorize().
do_output
bool drawsq_params::do_output = true private
Definition at line 176 of file map.h.
Referenced by output().
do_show_items
bool drawsq_params::do_show_items = true private
Definition at line 172 of file map.h.
Referenced by show_items().
view_center
tripoint drawsq_params::view_center = tripoint_min private
Definition at line 170 of file map.h.
Referenced by center(), and center_at_avatar().
The documentation for this struct was generated from the following files:
src/map.h
src/map.cpp