Cataclysm DDA: localized_comparator Struct Reference
localized_comparator Struct Reference
#include <localized_comparator.h>
Public Member Functions
template<typename T , typename U >
bool operator() (const std::pair< T, U > &l, const std::pair< T, U > &r) const
template<typename Head , typename... Tail>
bool operator() (const std::tuple< Head, Tail... > &l, const std::tuple< Head, Tail... > &r) const
template<typename T >
bool operator() (const T &l, const T &r) const
bool operator() (const std::string &, const std::string &) const
bool operator() (const std::wstring &, const std::wstring &) const
bool operator() (const translation &, const translation &) const
template<typename Head , typename... Tail, size_t... Ints>
auto tie_tail (const std::tuple< Head, Tail... > &t, std::index_sequence< Ints... >) const
Detailed Description
Definition at line 14 of file localized_comparator.h.
Member Function Documentation
operator()() [1/6]
template<typename T , typename U > bool localized_comparator::operator() (const std::pair< T, U > & l, const std::pair< T, U > & r) const inline
Definition at line 16 of file localized_comparator.h.
{
         if( ( *this )( l.first, r.first ) ) {
             return true;
         }
         if( ( *this )( r.first, l.first ) ) {
             return false;
         }
         return ( *this )( l.second, r.second );
     }
operator()() [2/6]
bool localized_comparator::operator() (const std::string & l, const std::string & r) const
Definition at line 11 of file localized_comparator.cpp.
 {
     // We need different implementations on each platform.  MacOS seems to not
     // support localized comparison of strings via the standard library at all,
     // so resort to MacOS-specific solution.  Windows cannot be expected to be
     // using a UTF-8 locale (whereas our strings are always UTF-8) and so we
     // must convert to wstring for comparison there.  Linux seems to work as
     // expected on regular strings; no workarounds needed.
     // See https://github.com/CleverRaven/Cataclysm-DDA/pull/40041 for further
     // discussion.
 #if defined(__APPLE__) // macOS and iOS
     CFStringRef lr = CFStringCreateWithCStringNoCopy( kCFAllocatorDefault, l.c_str(),
                      kCFStringEncodingUTF8, kCFAllocatorNull );
     CFStringRef rr = CFStringCreateWithCStringNoCopy( kCFAllocatorDefault, r.c_str(),
                      kCFStringEncodingUTF8, kCFAllocatorNull );
     bool result = CFStringCompare( lr, rr, kCFCompareLocalized ) < 0;
     CFRelease( lr );
     CFRelease( rr );
     return result;
 #elif defined(_WIN32)
     return ( *this )( utf8_to_wstr( l ), utf8_to_wstr( r ) );
 #else
     return std::locale()( l, r );
 #endif
 }
References utf8_to_wstr().
operator()() [3/6]
template<typename Head , typename... Tail> bool localized_comparator::operator() (const std::tuple< Head, Tail... > & l, const std::tuple< Head, Tail... > & r) const inline
Definition at line 27 of file localized_comparator.h.
{
         if( ( *this )( std::get<0>( l ), std::get<0>( r ) ) ) {
             return true;
         }
         if( ( *this )( std::get<0>( r ), std::get<0>( l ) ) ) {
             return false;
         }
         constexpr std::make_index_sequence<sizeof...( Tail )> Ints{};
         return ( *this )( tie_tail( l, Ints ), tie_tail( r, Ints ) );
     }
References tie_tail().
operator()() [4/6]
bool localized_comparator::operator() (const std::wstring & l, const std::wstring & r) const
Definition at line 37 of file localized_comparator.cpp.
 {
 #if defined(__APPLE__) // macOS and iOS
     return ( *this )( wstr_to_utf8( l ), wstr_to_utf8( r ) );
 #else
     return std::locale()( l, r );
 #endif
 }
References wstr_to_utf8().
operator()() [5/6]
template<typename T > bool localized_comparator::operator() (const T & l, const T & r) const inline
Definition at line 40 of file localized_comparator.h.
{
         return l < r;
     }
operator()() [6/6]
bool localized_comparator::operator() (const translation & l, const translation & r) const
Definition at line 46 of file localized_comparator.cpp.
 {
     return l.translated_lt( r );
 }
References translation::translated_lt().
tie_tail()
template<typename Head , typename... Tail, size_t... Ints> auto localized_comparator::tie_tail (const std::tuple< Head, Tail... > & t, std::index_sequence< Ints... >) const inline
Definition at line 49 of file localized_comparator.h.
{
         return std::tie( std::get < Ints + 1 > ( t )... );
     }
Referenced by operator()().
The documentation for this struct was generated from the following files:
src/localized_comparator.h
src/localized_comparator.cpp