Cataclysm DDA: icg_entry Struct Reference
icg_entry Struct Reference
#include <shop_cons_rate.h>
Public Member Functions
bool operator== (icg_entry const &rhs) const
bool matches (item const &it, npc const &beta) const
Public Attributes
itype_id itype
item_category_id category
item_group_id item_group
translation message
std::function< bool(dialogue &)> condition
Detailed Description
Definition at line 16 of file shop_cons_rate.h.
Member Function Documentation
matches()
bool icg_entry::matches (item const & it, npc const & beta) const
Definition at line 25 of file shop_cons_rate.cpp.
 {
     dialogue temp( get_talker_for( get_avatar() ), get_talker_for( beta ) );
     return ( !condition || condition( temp ) ) &&
            ( itype.is_empty() || it.typeId() == itype ) &&
            ( category.is_empty() || it.get_category_shallow().id == category ) &&
            ( item_group.is_empty() ||
              item_group::group_contains_item( item_group, it.typeId() ) );
 }
References category, condition, get_avatar(), item::get_category_shallow(), get_talker_for(), item_group::group_contains_item(), item_category::id, string_id< T >::is_empty(), itype, temp, and item::typeId().
operator==()
bool icg_entry::operator== (icg_entry const & rhs) const
Definition at line 20 of file shop_cons_rate.cpp.
 {
     return itype == rhs.itype && category == rhs.category && item_group == rhs.item_group;
 }
References category, item_group, and itype.
Referenced by shopkeeper_cons_rate_entry::operator==().
Member Data Documentation
category
item_category_id icg_entry::category
Definition at line 18 of file shop_cons_rate.h.
Referenced by matches(), and operator==().
condition
std::function<bool(dialogue &)> icg_entry::condition
Definition at line 22 of file shop_cons_rate.h.
Referenced by matches().
item_group
item_group_id icg_entry::item_group
Definition at line 19 of file shop_cons_rate.h.
Referenced by operator==().
itype
itype_id icg_entry::itype
Definition at line 17 of file shop_cons_rate.h.
Referenced by matches(), and operator==().
message
translation icg_entry::message
Definition at line 20 of file shop_cons_rate.h.
Referenced by npc::wants_to_buy().
The documentation for this struct was generated from the following files:
src/shop_cons_rate.h
src/shop_cons_rate.cpp