Cataclysm DDA: weakpoint_family Struct Reference
weakpoint_family Struct Reference
#include <weakpoint.h>
Public Member Functions
float modifier (const Character &attacker) const
void load (const JsonValue &jsin)
Public Attributes
std::string id
proficiency_id proficiency
std::optional< float > bonus
std::optional< float > penalty
Detailed Description
Definition at line 90 of file weakpoint.h.
Member Function Documentation
load()
void weakpoint_family::load (const JsonValue & jsin)
Definition at line 110 of file weakpoint.cpp.
 {
     if( jsin.test_string() ) {
         id = jsin.get_string();
         proficiency = proficiency_id( id );
     } else {
         JsonObject jo = jsin.get_object();
         assign( jo, "id", id );
         assign( jo, "proficiency", proficiency );
         assign( jo, "bonus", bonus );
         assign( jo, "penalty", penalty );
         if( !jo.has_string( "id" ) ) {
             id = static_cast<std::string>( proficiency );
         }
     }
 }
References assign(), bonus, JsonValue::get_object(), JsonValue::get_string(), JsonObject::has_string(), penalty, proficiency, proficiency_id, and JsonValue::test_string().
Referenced by weakpoint_families::load(), and weakpoint_families::remove().
modifier()
float weakpoint_family::modifier (const Character & attacker) const
Definition at line 103 of file weakpoint.cpp.
 {
     return attacker.has_proficiency( proficiency )
            ? bonus.value_or( proficiency.obj().default_weakpoint_bonus() )
            : penalty.value_or( proficiency.obj().default_weakpoint_penalty() );
 }
References bonus, proficiency::default_weakpoint_bonus(), proficiency::default_weakpoint_penalty(), Character::has_proficiency(), and penalty.
Member Data Documentation
bonus
std::optional<float> weakpoint_family::bonus
Definition at line 96 of file weakpoint.h.
Referenced by load(), and modifier().
id
std::string weakpoint_family::id
Definition at line 92 of file weakpoint.h.
penalty
std::optional<float> weakpoint_family::penalty
Definition at line 98 of file weakpoint.h.
Referenced by load(), and modifier().
proficiency
proficiency_id weakpoint_family::proficiency
Definition at line 94 of file weakpoint.h.
Referenced by butcher_submenu(), and load().
The documentation for this struct was generated from the following files:
src/weakpoint.h
src/weakpoint.cpp