Cataclysm DDA: islot_book::recipe_with_description_t Struct Reference
islot_book::recipe_with_description_t Struct Reference
What recipes can be learned from this book.
#include <itype.h>
Public Member Functions
bool operator< (const recipe_with_description_t &rhs) const
bool is_hidden () const
std::string name () const
Public Attributes
const class recipe * recipe
The recipe that can be learned (never null).
int skill_level
The skill level required to learn the recipe.
std::optional< translation > optional_name
The name for the recipe as it appears in the book.
bool hidden
Hidden means it does not show up in the description of the book.
Detailed Description
What recipes can be learned from this book.
Definition at line 544 of file itype.h.
Member Function Documentation
is_hidden()
bool islot_book::recipe_with_description_t::is_hidden () const inline
Definition at line 564 of file itype.h.
{
             return hidden;
         }
References hidden.
Referenced by item::book_info(), avatar::identify(), and item::tool_info().
name()
std::string islot_book::recipe_with_description_t::name () const
Definition at line 24 of file itype.cpp.
 {
     if( optional_name ) {
         return optional_name->translated();
     } else {
         return recipe->result_name( /*decorated=*/true );
     }
 }
References optional_name, and recipe::result_name().
Referenced by item::book_info(), avatar::identify(), and item::tool_info().
operator<()
bool islot_book::recipe_with_description_t::operator< (const recipe_with_description_t & rhs) const inline
Definition at line 561 of file itype.h.
{
             return recipe < rhs.recipe;
         }
References recipe.
Member Data Documentation
hidden
bool islot_book::recipe_with_description_t::hidden
Hidden means it does not show up in the description of the book.
Definition at line 560 of file itype.h.
Referenced by is_hidden().
optional_name
std::optional<translation> islot_book::recipe_with_description_t::optional_name
The name for the recipe as it appears in the book.
Definition at line 556 of file itype.h.
Referenced by name().
recipe
const class recipe* islot_book::recipe_with_description_t::recipe
The recipe that can be learned (never null).
Definition at line 548 of file itype.h.
Referenced by item::book_info(), item::get_available_recipes(), read_inventory_preset::get_known_recipes(), avatar::identify(), operator<(), Character::studied_all_recipes(), and item::tool_info().
skill_level
int islot_book::recipe_with_description_t::skill_level
The skill level required to learn the recipe.
Definition at line 552 of file itype.h.
Referenced by item::book_info(), item::get_available_recipes(), and item::tool_info().
The documentation for this struct was generated from the following files:
src/itype.h
src/itype.cpp