Cataclysm DDA: anonymous_namespace{condition.cpp}::condition_parser Struct Reference
anonymous_namespace{condition.cpp}::condition_parser Struct Reference
Public Types
using condition_func = conditional_t::func
using f_t = condition_func(*)(const JsonObject &, std::string_view)
using f_t_beta = condition_func(*)(const JsonObject &, std::string_view, bool)
using f_t_simple = condition_func(*)()
using f_t_beta_simple = condition_func(*)(bool)
Public Member Functions
condition_parser (std::string_view key_alpha_, jarg arg_, f_t f_)
condition_parser (std::string_view key_alpha_, std::string_view key_beta_, jarg arg_, f_t_beta f_)
condition_parser (std::string_view key_alpha_, f_t_simple f_)
condition_parser (std::string_view key_alpha_, std::string_view key_beta_, f_t_beta_simple f_)
bool check (const JsonObject &jo, bool beta=false) const
Public Attributes
bool has_beta = false
std::string_view key_alpha
std::string_view key_beta
jarg arg
f_t f
f_t_beta f_beta
f_t_simple f_simple
f_t_beta_simple f_beta_simple
Detailed Description
Definition at line 102 of file condition.cpp.
Member Typedef Documentation
condition_func
using anonymous_namespace{condition.cpp}::condition_parser::condition_func = conditional_t::func
Definition at line 103 of file condition.cpp.
f_t
using anonymous_namespace{condition.cpp}::condition_parser::f_t = condition_func(*)(const JsonObject &, std::string_view)
Definition at line 104 of file condition.cpp.
f_t_beta
using anonymous_namespace{condition.cpp}::condition_parser::f_t_beta = condition_func(*)(const JsonObject &, std::string_view, bool)
Definition at line 105 of file condition.cpp.
f_t_beta_simple
using anonymous_namespace{condition.cpp}::condition_parser::f_t_beta_simple = condition_func(*)(bool)
Definition at line 107 of file condition.cpp.
f_t_simple
using anonymous_namespace{condition.cpp}::condition_parser::f_t_simple = condition_func(*)()
Definition at line 106 of file condition.cpp.
Constructor & Destructor Documentation
condition_parser() [1/4]
anonymous_namespace{condition.cpp}::condition_parser::condition_parser (std::string_view key_alpha_, jarg arg_, f_t f_) inline
Definition at line 109 of file condition.cpp.
                                                                      : key_alpha( key_alpha_ ),
         arg( arg_ ), f( f_ ) {}
condition_parser() [2/4]
anonymous_namespace{condition.cpp}::condition_parser::condition_parser (std::string_view key_alpha_, std::string_view key_beta_, jarg arg_, f_t_beta f_) inline
Definition at line 111 of file condition.cpp.
                                     : key_alpha( key_alpha_ ), key_beta( key_beta_ ), arg( arg_ ), f_beta( f_ ) {
         has_beta = true;
     }
condition_parser() [3/4]
anonymous_namespace{condition.cpp}::condition_parser::condition_parser (std::string_view key_alpha_, f_t_simple f_) inline
Definition at line 115 of file condition.cpp.
                                                                  : key_alpha( key_alpha_ ),
         f_simple( f_ ) {}
condition_parser() [4/4]
anonymous_namespace{condition.cpp}::condition_parser::condition_parser (std::string_view key_alpha_, std::string_view key_beta_, f_t_beta_simple f_) inline
Definition at line 117 of file condition.cpp.
                                            : key_alpha( key_alpha_ ), key_beta( key_beta_ ), f_beta_simple( f_ ) {
         has_beta = true;
     }
Member Function Documentation
check()
bool anonymous_namespace{condition.cpp}::condition_parser::check (const JsonObject & jo, bool beta = false) const inline
Definition at line 122 of file condition.cpp.
{
         std::string_view key = beta ? key_beta : key_alpha;
         if( ( ( arg & jarg::member ) && jo.has_member( key ) ) ||
             ( ( arg & jarg::object ) && jo.has_object( key ) ) ||
             ( ( arg & jarg::string ) && jo.has_string( key ) ) ||
             ( ( arg & jarg::array ) && jo.has_array( key ) ) ) {
             return true;
         }
         return false;
     }
References array, JsonObject::has_array(), JsonObject::has_member(), JsonObject::has_object(), JsonObject::has_string(), member, object, and string.
Member Data Documentation
arg
jarg anonymous_namespace{condition.cpp}::condition_parser::arg
Definition at line 136 of file condition.cpp.
f
f_t anonymous_namespace{condition.cpp}::condition_parser::f
Definition at line 137 of file condition.cpp.
f_beta
f_t_beta anonymous_namespace{condition.cpp}::condition_parser::f_beta
Definition at line 138 of file condition.cpp.
f_beta_simple
f_t_beta_simple anonymous_namespace{condition.cpp}::condition_parser::f_beta_simple
Definition at line 140 of file condition.cpp.
f_simple
f_t_simple anonymous_namespace{condition.cpp}::condition_parser::f_simple
Definition at line 139 of file condition.cpp.
has_beta
bool anonymous_namespace{condition.cpp}::condition_parser::has_beta = false
Definition at line 133 of file condition.cpp.
key_alpha
std::string_view anonymous_namespace{condition.cpp}::condition_parser::key_alpha
Definition at line 134 of file condition.cpp.
key_beta
std::string_view anonymous_namespace{condition.cpp}::condition_parser::key_beta
Definition at line 135 of file condition.cpp.
The documentation for this struct was generated from the following file:
src/condition.cpp