Cataclysm DDA: mapgen_arguments Struct Reference
mapgen_arguments Struct Reference
#include <mapgendata.h>
Public Member Functions
mapgen_arguments ()=default
template<typename InputRange , std::enable_if_t< std::is_same_v< typename InputRange::value_type, std::pair< std::string, cata_variant > >||std::is_same_v< typename InputRange::value_type, std::pair< const std::string, cata_variant > > > * = nullptr>
mapgen_arguments (const InputRange &map_)
bool operator== (const mapgen_arguments &other) const
void merge (const mapgen_arguments &)
void serialize (JsonOut &) const
void deserialize (const JsonValue &ji)
Public Attributes
std::unordered_map< std::string, cata_variant > map
Detailed Description
Definition at line 26 of file mapgendata.h.
Constructor & Destructor Documentation
mapgen_arguments() [1/2]
mapgen_arguments::mapgen_arguments () default
mapgen_arguments() [2/2]
template<typename InputRange , std::enable_if_t< std::is_same_v< typename InputRange::value_type, std::pair< std::string, cata_variant > >||std::is_same_v< typename InputRange::value_type, std::pair< const std::string, cata_variant > > > * = nullptr> mapgen_arguments::mapgen_arguments (const InputRange & map_) inline explicit
Definition at line 39 of file mapgendata.h.
         : map( map_.begin(), map_.end() )
     {}
Member Function Documentation
deserialize()
void mapgen_arguments::deserialize (const JsonValue & ji)
Definition at line 26 of file mapgendata.cpp.
 {
     ji.read( map, true );
 }
References JsonValue::read().
merge()
void mapgen_arguments::merge (const mapgen_arguments & other)
Definition at line 14 of file mapgendata.cpp.
 {
     for( const std::pair<const std::string, cata_variant> &p : other.map ) {
         map[p.first] = p.second;
     }
 }
References other.
Referenced by mapgendata::mapgendata().
operator==()
bool mapgen_arguments::operator== (const mapgen_arguments & other) const inline
Definition at line 45 of file mapgendata.h.
{
         return map == other.map;
     }
References other.
serialize()
void mapgen_arguments::serialize (JsonOut & jo) const
Definition at line 21 of file mapgendata.cpp.
 {
     jo.write( map );
 }
References JsonOut::write().
Member Data Documentation
map
std::unordered_map<std::string, cata_variant> mapgen_arguments::map
Definition at line 43 of file mapgendata.h.
Referenced by mapgendata::get_arg(), mapgendata::get_arg_or(), mapgendata::mapgendata(), basecamp::name_display_of(), start_location::set_parameters(), and overmap_ui::set_special_args().
The documentation for this struct was generated from the following files:
src/mapgendata.h
src/mapgendata.cpp