Cataclysm DDA: container_data Struct Reference
container_data Struct Reference
Public Member Functions
std::string to_formatted_string (const bool compact=true) const
Public Attributes
units::volume actual_capacity
units::volume total_capacity
units::mass actual_capacity_weight
units::mass total_capacity_weight
units::length max_containable_length
Detailed Description
Definition at line 223 of file inventory_ui.cpp.
Member Function Documentation
to_formatted_string()
std::string container_data::to_formatted_string (const bool compact = true) const inline
Definition at line 230 of file inventory_ui.cpp.
{
         std::string string_to_format;
         if( compact ) {
             string_to_format = _( "%s/%s : %s/%s : max %s" );
         } else {
             string_to_format = _( "(remains %s, %s) max length %s" );
         }
         return string_format( string_to_format,
                               unit_to_string( total_capacity - actual_capacity, true, true ),
                               unit_to_string( total_capacity_weight - actual_capacity_weight, true, true ),
                               unit_to_string( max_containable_length, true ) );
     }
References _, actual_capacity, actual_capacity_weight, compact, max_containable_length, string_format(), total_capacity, total_capacity_weight, and unit_to_string().
Referenced by inventory_selector_preset::get_cell_text().
Member Data Documentation
actual_capacity
units::volume container_data::actual_capacity
Definition at line 224 of file inventory_ui.cpp.
Referenced by to_formatted_string().
actual_capacity_weight
units::mass container_data::actual_capacity_weight
Definition at line 226 of file inventory_ui.cpp.
Referenced by to_formatted_string().
max_containable_length
units::length container_data::max_containable_length
Definition at line 228 of file inventory_ui.cpp.
Referenced by to_formatted_string().
total_capacity
units::volume container_data::total_capacity
Definition at line 225 of file inventory_ui.cpp.
Referenced by to_formatted_string().
total_capacity_weight
units::mass container_data::total_capacity_weight
Definition at line 227 of file inventory_ui.cpp.
Referenced by to_formatted_string().
The documentation for this struct was generated from the following file:
src/inventory_ui.cpp