Cataclysm DDA: enchantment::bodypart_changes Struct Reference
enchantment::bodypart_changes Struct Reference
#include <magic_enchantment.h>
Public Member Functions
void serialize (JsonOut &jsout) const
void deserialize (const JsonObject &jo)
void load (const JsonObject &jo)
Public Attributes
bodypart_str_id gain
bodypart_str_id lose
bool was_loaded = false
Detailed Description
Definition at line 239 of file magic_enchantment.h.
Member Function Documentation
deserialize()
void enchantment::bodypart_changes::deserialize (const JsonObject & jo)
Definition at line 368 of file magic_enchantment.cpp.
 {
     load( jo );
 }
References enchantment::load().
load()
void enchantment::bodypart_changes::load (const JsonObject & jo)
Definition at line 362 of file magic_enchantment.cpp.
 {
     optional( jo, was_loaded, "gain", gain );
     optional( jo, was_loaded, "lose", lose );
 }
References gain, lose, optional(), and was_loaded.
serialize()
void enchantment::bodypart_changes::serialize (JsonOut & jsout) const
Definition at line 373 of file magic_enchantment.cpp.
 {
     jsout.start_object();
     jsout.member( "gain", gain );
     jsout.member( "lose", lose );
     jsout.end_object();
 }
References JsonOut::end_object(), JsonOut::member(), and JsonOut::start_object().
Member Data Documentation
gain
bodypart_str_id enchantment::bodypart_changes::gain
Definition at line 240 of file magic_enchantment.h.
Referenced by load().
lose
bodypart_str_id enchantment::bodypart_changes::lose
Definition at line 241 of file magic_enchantment.h.
Referenced by load().
was_loaded
bool enchantment::bodypart_changes::was_loaded = false
Definition at line 242 of file magic_enchantment.h.
Referenced by load().
The documentation for this struct was generated from the following files:
src/magic_enchantment.h
src/magic_enchantment.cpp