Cataclysm DDA: src/submap.cpp File Reference
submap.cpp File Reference
#include "submap.h"
#include <algorithm>
#include <array>
#include <iterator>
#include <memory>
#include <utility>
#include "basecamp.h"
#include "mapdata.h"
#include "tileray.h"
#include "trap.h"
#include "units.h"
#include "vehicle.h"
Classes
struct cosmetic_find_result
Functions
static const std::string COSMETICS_GRAFFITI ("GRAFFITI")
static const std::string COSMETICS_SIGNAGE ("SIGNAGE")
static cosmetic_find_result make_result (bool b, int ndx)
static cosmetic_find_result find_cosmetic (const std::vector< submap::cosmetic_t > &cosmetics, const point &p, const std::string &type)
Variables
static const std::string STRING_EMPTY
Function Documentation
COSMETICS_GRAFFITI()
static const std::string COSMETICS_GRAFFITI ("GRAFFITI") static
Referenced by submap::delete_graffiti(), submap::get_graffiti(), submap::has_graffiti(), and submap::set_graffiti().
COSMETICS_SIGNAGE()
static const std::string COSMETICS_SIGNAGE ("SIGNAGE") static
Referenced by submap::delete_signage(), submap::get_signage(), submap::has_signage(), and submap::set_signage().
find_cosmetic()
static cosmetic_find_result find_cosmetic (const std::vector< submap::cosmetic_t > & cosmetics, const point & p, const std::string & type) static
Definition at line 55 of file submap.cpp.
 {
     for( size_t i = 0; i < cosmetics.size(); ++i ) {
         if( cosmetics[i].pos == p && cosmetics[i].type == type ) {
             return make_result( true, i );
         }
     }
     return make_result( false, -1 );
 }
References make_result(), and math_opers::pos().
Referenced by submap::delete_graffiti(), submap::delete_signage(), submap::get_graffiti(), submap::get_signage(), submap::has_graffiti(), submap::has_signage(), submap::set_graffiti(), and submap::set_signage().
make_result()
static cosmetic_find_result make_result (bool b, int ndx) static
Definition at line 48 of file submap.cpp.
 {
     cosmetic_find_result result;
     result.result = b;
     result.ndx = ndx;
     return result;
 }
References b, cosmetic_find_result::ndx, and cosmetic_find_result::result.
Referenced by find_cosmetic(), and to_string_approx().
Variable Documentation
STRING_EMPTY
const std::string STRING_EMPTY static
Definition at line 42 of file submap.cpp.
Referenced by submap::get_graffiti(), and submap::get_signage().