Cataclysm DDA: src/suffer.cpp File Reference
suffer.cpp File Reference
#include <cctype>
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdlib>
#include <iosfwd>
#include <list>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "activity_handlers.h"
#include "addiction.h"
#include "bionics.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "creature.h"
#include "creature_tracker.h"
#include "debug.h"
#include "display.h"
#include "effect.h"
#include "effect_on_condition.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "field_type.h"
#include "flag.h"
#include "game.h"
#include "game_constants.h"
#include "inventory.h"
#include "item.h"
#include "item_location.h"
#include "magic_enchantment.h"
#include "map.h"
#include "memory_fast.h"
#include "messages.h"
#include "monster.h"
#include "morale_types.h"
#include "mtype.h"
#include "mutation.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "player_activity.h"
#include "point.h"
#include "rng.h"
#include "skill.h"
#include "sounds.h"
#include "stomach.h"
#include "string_formatter.h"
#include "teleport.h"
#include "text_snippets.h"
#include "translations.h"
#include "type_id.h"
#include "uistate.h"
#include "units.h"
#include "weather.h"
#include "weather_type.h"
Namespaces
suffer
Functions
static void suffer::from_sunburn (Character &you, bool severe)
static void suffer::in_sunlight (Character &you)
static void suffer::water_damage (Character &you)
static void suffer::mutation_power (Character &you, const trait_id &mut_id)
static void suffer::while_underwater (Character &you)
static void suffer::while_grabbed (Character &you)
static void suffer::from_addictions (Character &you)
static void suffer::while_awake (Character &you, int current_stim)
static void suffer::from_chemimbalance (Character &you)
static void suffer::from_asthma (Character &you, int current_stim)
static void suffer::from_item_dropping (Character &you)
static void suffer::from_other_mutations (Character &you)
static void suffer::from_radiation (Character &you)
static void suffer::from_bad_bionics (Character &you)
static void suffer::from_stimulants (Character &you, int current_stim)
static void suffer::from_exertion (Character &you)
static void suffer::without_sleep (Character &you, int sleep_deprivation)
static void suffer::from_tourniquet (Character &you)
static void suffer::from_nyctophobia (Character &you)
static void suffer::from_artifact_resonance (Character &you, int amt)
static float addiction_scaling (float at_min, float at_max, float add_lvl)
static float linear_interpolation (float x_start, float y_start, float x_end, float y_end, float x)
static float light_eff_chance (float exp)
static float medium_eff_chance (float exp)
static float heavy_eff_chance (float exp)
static void apply_weary_message (const Character &you, int level, int old)
static void apply_weariness (Character &you, int level, int old)
Variables
static const addiction_id addiction_alcohol ("alcohol")
static const addiction_id addiction_nicotine ("nicotine")
static const bionic_id bio_dis_acid ("bio_dis_acid")
static const bionic_id bio_dis_shock ("bio_dis_shock")
static const bionic_id bio_geiger ("bio_geiger")
static const bionic_id bio_gills ("bio_gills")
static const bionic_id bio_power_weakness ("bio_power_weakness")
static const bionic_id bio_radleak ("bio_radleak")
static const bionic_id bio_sleep_shutdown ("bio_sleep_shutdown")
static const bionic_id bio_synlungs ("bio_synlungs")
static const efftype_id effect_adrenaline ("adrenaline")
static const efftype_id effect_asthma ("asthma")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_cig ("cig")
static const efftype_id effect_datura ("datura")
static const efftype_id effect_deaf ("deaf")
static const efftype_id effect_disabled ("disabled")
static const efftype_id effect_downed ("downed")
static const efftype_id effect_drunk ("drunk")
static const efftype_id effect_hallu ("hallu")
static const efftype_id effect_incorporeal ("incorporeal")
static const efftype_id effect_iodine ("iodine")
static const efftype_id effect_masked_scent ("masked_scent")
static const efftype_id effect_mending ("mending")
static const efftype_id effect_narcosis ("narcosis")
static const efftype_id effect_nausea ("nausea")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_shakes ("shakes")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_took_antiasthmatic ("took_antiasthmatic")
static const efftype_id effect_took_xanax ("took_xanax")
static const efftype_id effect_visuals ("visuals")
static const efftype_id effect_weary_0 ("weary_0")
static const efftype_id effect_weary_1 ("weary_1")
static const efftype_id effect_weary_2 ("weary_2")
static const efftype_id effect_weary_3 ("weary_3")
static const efftype_id effect_weary_4 ("weary_4")
static const efftype_id effect_weary_5 ("weary_5")
static const efftype_id effect_weary_6 ("weary_6")
static const efftype_id effect_weary_7 ("weary_7")
static const efftype_id effect_weary_8 ("weary_8")
static const efftype_id effect_winded ("winded")
static const itype_id itype_e_handcuffs ("e_handcuffs")
static const itype_id itype_inhaler ("inhaler")
static const itype_id itype_oxygen_tank ("oxygen_tank")
static const itype_id itype_smoxygen_tank ("smoxygen_tank")
static const json_character_flag json_flag_ALBINO ("ALBINO")
static const json_character_flag json_flag_DAYFEAR ("DAYFEAR")
static const json_character_flag json_flag_ETHEREAL ("ETHEREAL")
static const json_character_flag json_flag_GILLS ("GILLS")
static const json_character_flag json_flag_GLARE_RESIST ("GLARE_RESIST")
static const json_character_flag json_flag_GRAB ("GRAB")
static const json_character_flag json_flag_MEND_ALL ("MEND_ALL")
static const json_character_flag json_flag_MEND_LIMB ("MEND_LIMB")
static const json_character_flag json_flag_NYCTOPHOBIA ("NYCTOPHOBIA")
static const json_character_flag json_flag_PAIN_IMMUNE ("PAIN_IMMUNE")
static const json_character_flag json_flag_RAD_DETECT ("RAD_DETECT")
static const json_character_flag json_flag_SUNBURN ("SUNBURN")
static const trait_id trait_ADDICTIVE ("ADDICTIVE")
static const trait_id trait_ASTHMA ("ASTHMA")
static const trait_id trait_CHAOTIC ("CHAOTIC")
static const trait_id trait_CHAOTIC_BAD ("CHAOTIC_BAD")
static const trait_id trait_CHEMIMBALANCE ("CHEMIMBALANCE")
static const trait_id trait_DEBUG_NOTEMP ("DEBUG_NOTEMP")
static const trait_id trait_FRESHWATEROSMOSIS ("FRESHWATEROSMOSIS")
static const trait_id trait_HAS_NEMESIS ("HAS_NEMESIS")
static const trait_id trait_JITTERY ("JITTERY")
static const trait_id trait_KILLER ("KILLER")
static const trait_id trait_LEAVES ("LEAVES")
static const trait_id trait_LEAVES2 ("LEAVES2")
static const trait_id trait_LEAVES3 ("LEAVES3")
static const trait_id trait_MOODSWINGS ("MOODSWINGS")
static const trait_id trait_MUCUS_SECRETION ("MUCUS_SECRETION")
static const trait_id trait_M_BLOSSOMS ("M_BLOSSOMS")
static const trait_id trait_M_SPORES ("M_SPORES")
static const trait_id trait_NARCOLEPTIC ("NARCOLEPTIC")
static const trait_id trait_NONADDICTIVE ("NONADDICTIVE")
static const trait_id trait_PER_SLIME ("PER_SLIME")
static const trait_id trait_PYROMANIA ("PYROMANIA")
static const trait_id trait_RADIOACTIVE1 ("RADIOACTIVE1")
static const trait_id trait_RADIOACTIVE2 ("RADIOACTIVE2")
static const trait_id trait_RADIOACTIVE3 ("RADIOACTIVE3")
static const trait_id trait_RADIOGENIC ("RADIOGENIC")
static const trait_id trait_RADIOPHILE ("RADIOPHILE")
static const trait_id trait_SHARKTEETH ("SHARKTEETH")
static const trait_id trait_SHELL2 ("SHELL2")
static const trait_id trait_SHELL3 ("SHELL3")
static const trait_id trait_SHOUT1 ("SHOUT1")
static const trait_id trait_SHOUT2 ("SHOUT2")
static const trait_id trait_SHOUT3 ("SHOUT3")
static const trait_id trait_SNAIL_TRAIL ("SNAIL_TRAIL")
static const trait_id trait_SORES ("SORES")
static const trait_id trait_TROGLO ("TROGLO")
static const trait_id trait_TROGLO2 ("TROGLO2")
static const trait_id trait_TROGLO3 ("TROGLO3")
static const trait_id trait_UNDINE_ABSORB_WATER ("UNDINE_ABSORB_WATER")
static const trait_id trait_UNSTABLE ("UNSTABLE")
static const trait_id trait_VOMITOUS ("VOMITOUS")
static const trait_id trait_WEB_SPINNER ("WEB_SPINNER")
static const trait_id trait_WEB_WEAVER ("WEB_WEAVER")
static const trait_id trait_WINGS_INSECT_active ("WINGS_INSECT_active")
static const vitamin_id vitamin_vitC ("vitC")
Function Documentation
addiction_scaling()
static float addiction_scaling (float at_min, float at_max, float add_lvl) static
Definition at line 201 of file suffer.cpp.
 {
     // Not addicted
     if( add_lvl < MIN_ADDICTION_LEVEL ) {
         return 1.0f;
     }
     return lerp( at_min, at_max, ( add_lvl - MIN_ADDICTION_LEVEL ) / MAX_ADDICTION_LEVEL );
 }
References lerp(), MAX_ADDICTION_LEVEL, and MIN_ADDICTION_LEVEL.
Referenced by Character::mend().
apply_weariness()
static void apply_weariness (Character & you, int level, int old) static
Definition at line 1358 of file suffer.cpp.
 {
     // Exertion cannot be negative!
     if( level < 0 || old < 0 ) {
         debugmsg( "Attempted to apply weariness to character with negative ( new: %d old: %d ) weariness",
                   level, old );
     }
     // A mapping of weariness level to the effect to be applied
     static const std::array<efftype_id, 9> weary_effects { {
             effect_weary_0,
             effect_weary_1,
             effect_weary_2,
             effect_weary_3,
             effect_weary_4,
             effect_weary_5,
             effect_weary_6,
             effect_weary_7,
             effect_weary_8,
         }};
     // If we're going above level 8, we're seriously messed up
     // So just stick to level 8
     if( level > 8 ) {
         level = 8;
     }
     if( old > 8 ) {
         old = 8;
     }
     /*
      * It's possible that old == level, but we need to make sure we're removing
      * the old effect when that's not true It's simple enough to just remove
      * the old effect then apply the new, effect, because no change will happen
      * if they're equal
      */
     you.remove_effect( weary_effects[old] );
     you.add_effect( weary_effects[level], 1_turns, true );
     apply_weary_message( you, level, old );
 }
References Creature::add_effect(), apply_weary_message(), debugmsg, effect_weary_0, effect_weary_1, effect_weary_2, effect_weary_3, effect_weary_4, effect_weary_5, effect_weary_6, effect_weary_7, effect_weary_8, and Creature::remove_effect().
Referenced by suffer::from_exertion().
apply_weary_message()
static void apply_weary_message (const Character & you, int level, int old) static
Definition at line 1330 of file suffer.cpp.
 {
     if( level - old > 0 ) {
         std::string msg;
         switch( level ) {
             case 1:
                 msg = _( "You're beginning to feel like you've exerted yourself a bit." );
                 break;
             case 2:
                 msg = _( "You're tiring out mildly, and slowing down as a result." );
                 break;
             case 3:
                 msg = _( "The day's labors are taking their toll, and slowing you down." );
                 break;
             case 4:
                 msg = _( "You're getting very tired from all this hard work." );
                 break;
             case 5:
             default:
                 msg = _( "You're exhausted." );
                 break;
         }
         you.add_msg_if_player( m_info, msg );
     } else {
         you.add_msg_if_player( m_good, _( "You're feeling a bit better rested from your exertions." ) );
     }
 }
References _, Character::add_msg_if_player(), m_good, and m_info.
Referenced by apply_weariness().
heavy_eff_chance()
static float heavy_eff_chance (float exp) static
Definition at line 766 of file suffer.cpp.
 {
     // Starts at 15%, increases to 0.1 at 100%
     return linear_interpolation( 0.15, 0.0, 1.0, 0.1, exp );
 }
References linear_interpolation().
Referenced by suffer::from_sunburn().
light_eff_chance()
static float light_eff_chance (float exp) static
Definition at line 754 of file suffer.cpp.
 {
     // Sharp increase until 5%
     return linear_interpolation( 0.01, 0.0, 0.05, 1.0, exp );
 }
References linear_interpolation().
Referenced by suffer::from_sunburn().
linear_interpolation()
static float linear_interpolation (float x_start, float y_start, float x_end, float y_end, float x) static
Definition at line 741 of file suffer.cpp.
 {
     if( x < x_start ) {
         return y_start;
     }
     if( x > x_end ) {
         return y_end;
     }
     float interval = x_end - x_start;
     float perc_to_end = ( x - x_start ) / interval;
     return ( 1 - perc_to_end ) * y_start + perc_to_end * y_end;
 }
Referenced by heavy_eff_chance(), light_eff_chance(), and medium_eff_chance().
medium_eff_chance()
static float medium_eff_chance (float exp) static
Definition at line 760 of file suffer.cpp.
 {
     // Starts at 5%, peaks at 30%
     return linear_interpolation( 0.05, 0.0, 0.55, 0.25, exp );
 }
References linear_interpolation().
Referenced by suffer::from_sunburn().
Variable Documentation
addiction_alcohol
const addiction_id addiction_alcohol("alcohol") ("alcohol") static
Referenced by Character::mend().
addiction_nicotine
const addiction_id addiction_nicotine("nicotine") ("nicotine") static
Referenced by Character::mend().
bio_dis_acid
const bionic_id bio_dis_acid("bio_dis_acid") ("bio_dis_acid") static
Referenced by suffer::from_bad_bionics().
bio_dis_shock
const bionic_id bio_dis_shock("bio_dis_shock") ("bio_dis_shock") static
Referenced by suffer::from_bad_bionics().
bio_geiger
const bionic_id bio_geiger("bio_geiger") ("bio_geiger") static
Referenced by suffer::from_radiation().
bio_gills
const bionic_id bio_gills("bio_gills") ("bio_gills") static
Referenced by suffer::from_asthma(), and suffer::while_underwater().
bio_power_weakness
const bionic_id bio_power_weakness("bio_power_weakness") ("bio_power_weakness") static
Referenced by suffer::from_bad_bionics().
bio_radleak
const bionic_id bio_radleak("bio_radleak") ("bio_radleak") static
Referenced by suffer::from_bad_bionics().
bio_sleep_shutdown
const bionic_id bio_sleep_shutdown("bio_sleep_shutdown") ("bio_sleep_shutdown") static
Referenced by suffer::from_asthma().
bio_synlungs
const bionic_id bio_synlungs("bio_synlungs") ("bio_synlungs") static
Referenced by suffer::from_bad_bionics().
effect_adrenaline
const efftype_id effect_adrenaline("adrenaline") ("adrenaline") static
Referenced by suffer::from_asthma().
effect_asthma
const efftype_id effect_asthma("asthma") ("asthma") static
Referenced by suffer::from_asthma().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
Referenced by suffer::from_other_mutations(), and suffer::from_stimulants().
effect_cig
const efftype_id effect_cig("cig") ("cig") static
Referenced by Character::mend().
effect_datura
const efftype_id effect_datura("datura") ("datura") static
Referenced by suffer::from_asthma(), and suffer::in_sunlight().
effect_deaf
const efftype_id effect_deaf("deaf") ("deaf") static
Referenced by suffer::from_other_mutations().
effect_disabled
const efftype_id effect_disabled("disabled") ("disabled") static
Referenced by Character::suffer().
effect_downed
const efftype_id effect_downed("downed") ("downed") static
Referenced by suffer::from_stimulants(), suffer::while_awake(), and suffer::without_sleep().
effect_drunk
const efftype_id effect_drunk("drunk") ("drunk") static
Referenced by Character::mend().
effect_hallu
const efftype_id effect_hallu("hallu") ("hallu") static
Referenced by suffer::without_sleep().
effect_incorporeal
const efftype_id effect_incorporeal("incorporeal") ("incorporeal") static
Referenced by suffer::from_artifact_resonance(), and suffer::from_item_dropping().
effect_iodine
const efftype_id effect_iodine("iodine") ("iodine") static
Referenced by suffer::from_bad_bionics(), and Character::irradiate().
effect_masked_scent
const efftype_id effect_masked_scent("masked_scent") ("masked_scent") static
Referenced by Character::drench().
effect_mending
const efftype_id effect_mending("mending") ("mending") static
Referenced by Character::mend().
effect_narcosis
const efftype_id effect_narcosis("narcosis") ("narcosis") static
Referenced by suffer::from_asthma(), and suffer::from_bad_bionics().
effect_nausea
const efftype_id effect_nausea("nausea") ("nausea") static
Referenced by suffer::from_artifact_resonance(), suffer::from_stimulants(), and suffer::without_sleep().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by Character::drench().
effect_shakes
const efftype_id effect_shakes("shakes") ("shakes") static
Referenced by suffer::from_nyctophobia(), suffer::from_stimulants(), suffer::while_awake(), and suffer::without_sleep().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by suffer::from_asthma(), suffer::from_chemimbalance(), suffer::from_stimulants(), suffer::from_sunburn(), and Character::mend().
effect_took_antiasthmatic
const efftype_id effect_took_antiasthmatic("took_antiasthmatic") ("took_antiasthmatic") static
Referenced by suffer::from_asthma().
effect_took_xanax
const efftype_id effect_took_xanax("took_xanax") ("took_xanax") static
Referenced by suffer::while_awake().
effect_visuals
const efftype_id effect_visuals("visuals") ("visuals") static
Referenced by suffer::from_artifact_resonance(), suffer::from_other_mutations(), and suffer::without_sleep().
effect_weary_0
const efftype_id effect_weary_0("weary_0") ("weary_0") static
Referenced by apply_weariness().
effect_weary_1
const efftype_id effect_weary_1("weary_1") ("weary_1") static
Referenced by apply_weariness().
effect_weary_2
const efftype_id effect_weary_2("weary_2") ("weary_2") static
Referenced by apply_weariness().
effect_weary_3
const efftype_id effect_weary_3("weary_3") ("weary_3") static
Referenced by apply_weariness().
effect_weary_4
const efftype_id effect_weary_4("weary_4") ("weary_4") static
Referenced by apply_weariness().
effect_weary_5
const efftype_id effect_weary_5("weary_5") ("weary_5") static
Referenced by apply_weariness().
effect_weary_6
const efftype_id effect_weary_6("weary_6") ("weary_6") static
Referenced by apply_weariness().
effect_weary_7
const efftype_id effect_weary_7("weary_7") ("weary_7") static
Referenced by apply_weariness().
effect_weary_8
const efftype_id effect_weary_8("weary_8") ("weary_8") static
Referenced by apply_weariness().
effect_winded
const efftype_id effect_winded("winded") ("winded") static
Referenced by suffer::from_stimulants().
itype_e_handcuffs
const itype_id itype_e_handcuffs("e_handcuffs") ("e_handcuffs") static
Referenced by suffer::from_bad_bionics().
itype_inhaler
const itype_id itype_inhaler("inhaler") ("inhaler") static
Referenced by suffer::from_asthma().
itype_oxygen_tank
const itype_id itype_oxygen_tank("oxygen_tank") ("oxygen_tank") static
Referenced by suffer::from_asthma().
itype_smoxygen_tank
const itype_id itype_smoxygen_tank("smoxygen_tank") ("smoxygen_tank") static
Referenced by suffer::from_asthma().
json_flag_ALBINO
const json_character_flag json_flag_ALBINO("ALBINO") ("ALBINO") static
Referenced by suffer::in_sunlight().
json_flag_DAYFEAR
const json_character_flag json_flag_DAYFEAR("DAYFEAR") ("DAYFEAR") static
Referenced by suffer::in_sunlight().
json_flag_ETHEREAL
const json_character_flag json_flag_ETHEREAL("ETHEREAL") ("ETHEREAL") static
Referenced by suffer::from_item_dropping().
json_flag_GILLS
const json_character_flag json_flag_GILLS("GILLS") ("GILLS") static
Referenced by suffer::while_underwater().
json_flag_GLARE_RESIST
const json_character_flag json_flag_GLARE_RESIST("GLARE_RESIST") ("GLARE_RESIST") static
Referenced by suffer::from_sunburn().
json_flag_GRAB
const json_character_flag json_flag_GRAB("GRAB") ("GRAB") static
Referenced by Character::suffer().
json_flag_MEND_ALL
const json_character_flag json_flag_MEND_ALL("MEND_ALL") ("MEND_ALL") static
Referenced by Character::mend().
json_flag_MEND_LIMB
const json_character_flag json_flag_MEND_LIMB("MEND_LIMB") ("MEND_LIMB") static
Referenced by Character::mend().
json_flag_NYCTOPHOBIA
const json_character_flag json_flag_NYCTOPHOBIA("NYCTOPHOBIA") ("NYCTOPHOBIA") static
Referenced by suffer::while_awake().
json_flag_PAIN_IMMUNE
const json_character_flag json_flag_PAIN_IMMUNE("PAIN_IMMUNE") ("PAIN_IMMUNE") static
Referenced by suffer::from_bad_bionics(), and suffer::from_chemimbalance().
json_flag_RAD_DETECT
const json_character_flag json_flag_RAD_DETECT("RAD_DETECT") ("RAD_DETECT") static
Referenced by Character::irradiate().
json_flag_SUNBURN
const json_character_flag json_flag_SUNBURN("SUNBURN") ("SUNBURN") static
Referenced by suffer::in_sunlight().
trait_ADDICTIVE
const trait_id trait_ADDICTIVE("ADDICTIVE") ("ADDICTIVE") static
Referenced by Character::add_addiction(), and suffer::from_addictions().
trait_ASTHMA
const trait_id trait_ASTHMA("ASTHMA") ("ASTHMA") static
Referenced by Character::suffer().
trait_CHAOTIC
const trait_id trait_CHAOTIC("CHAOTIC") ("CHAOTIC") static
Referenced by suffer::from_other_mutations().
trait_CHAOTIC_BAD
const trait_id trait_CHAOTIC_BAD("CHAOTIC_BAD") ("CHAOTIC_BAD") static
Referenced by suffer::from_other_mutations().
trait_CHEMIMBALANCE
const trait_id trait_CHEMIMBALANCE("CHEMIMBALANCE") ("CHEMIMBALANCE") static
Referenced by suffer::while_awake().
trait_DEBUG_NOTEMP
const trait_id trait_DEBUG_NOTEMP("DEBUG_NOTEMP") ("DEBUG_NOTEMP") static
Referenced by Character::drench().
trait_FRESHWATEROSMOSIS
const trait_id trait_FRESHWATEROSMOSIS("FRESHWATEROSMOSIS") ("FRESHWATEROSMOSIS") static
Referenced by suffer::while_underwater().
trait_HAS_NEMESIS
const trait_id trait_HAS_NEMESIS("HAS_NEMESIS") ("HAS_NEMESIS") static
Referenced by suffer::while_awake().
trait_JITTERY
const trait_id trait_JITTERY("JITTERY") ("JITTERY") static
Referenced by suffer::while_awake().
trait_KILLER
const trait_id trait_KILLER("KILLER") ("KILLER") static
Referenced by suffer::from_other_mutations().
trait_LEAVES
const trait_id trait_LEAVES("LEAVES") ("LEAVES") static
Referenced by suffer::in_sunlight().
trait_LEAVES2
const trait_id trait_LEAVES2("LEAVES2") ("LEAVES2") static
Referenced by suffer::in_sunlight().
trait_LEAVES3
const trait_id trait_LEAVES3("LEAVES3") ("LEAVES3") static
Referenced by suffer::in_sunlight().
trait_M_BLOSSOMS
const trait_id trait_M_BLOSSOMS("M_BLOSSOMS") ("M_BLOSSOMS") static
Referenced by suffer::while_awake().
trait_M_SPORES
const trait_id trait_M_SPORES("M_SPORES") ("M_SPORES") static
Referenced by suffer::while_awake().
trait_MOODSWINGS
const trait_id trait_MOODSWINGS("MOODSWINGS") ("MOODSWINGS") static
Referenced by suffer::while_awake().
trait_MUCUS_SECRETION
const trait_id trait_MUCUS_SECRETION("MUCUS_SECRETION") ("MUCUS_SECRETION") static
Referenced by suffer::from_other_mutations().
trait_NARCOLEPTIC
const trait_id trait_NARCOLEPTIC("NARCOLEPTIC") ("NARCOLEPTIC") static
Referenced by suffer::while_awake().
trait_NONADDICTIVE
const trait_id trait_NONADDICTIVE("NONADDICTIVE") ("NONADDICTIVE") static
Referenced by Character::add_addiction(), and suffer::from_addictions().
trait_PER_SLIME
const trait_id trait_PER_SLIME("PER_SLIME") ("PER_SLIME") static
Referenced by suffer::from_other_mutations().
trait_PYROMANIA
const trait_id trait_PYROMANIA("PYROMANIA") ("PYROMANIA") static
Referenced by suffer::from_other_mutations().
trait_RADIOACTIVE1
const trait_id trait_RADIOACTIVE1("RADIOACTIVE1") ("RADIOACTIVE1") static
Referenced by suffer::from_radiation(), and Character::irradiate().
trait_RADIOACTIVE2
const trait_id trait_RADIOACTIVE2("RADIOACTIVE2") ("RADIOACTIVE2") static
Referenced by suffer::from_radiation(), and Character::irradiate().
trait_RADIOACTIVE3
const trait_id trait_RADIOACTIVE3("RADIOACTIVE3") ("RADIOACTIVE3") static
Referenced by suffer::from_radiation(), and Character::irradiate().
trait_RADIOGENIC
const trait_id trait_RADIOGENIC("RADIOGENIC") ("RADIOGENIC") static
Referenced by suffer::from_radiation(), and Character::mend().
trait_RADIOPHILE
const trait_id trait_RADIOPHILE("RADIOPHILE") ("RADIOPHILE") static
Referenced by suffer::from_radiation().
trait_SHARKTEETH
const trait_id trait_SHARKTEETH("SHARKTEETH") ("SHARKTEETH") static
Referenced by suffer::from_other_mutations().
trait_SHELL2
const trait_id trait_SHELL2("SHELL2") ("SHELL2") static
Referenced by Character::drench().
trait_SHELL3
const trait_id trait_SHELL3("SHELL3") ("SHELL3") static
Referenced by Character::drench().
trait_SHOUT1
const trait_id trait_SHOUT1("SHOUT1") ("SHOUT1") static
Referenced by suffer::while_awake().
trait_SHOUT2
const trait_id trait_SHOUT2("SHOUT2") ("SHOUT2") static
Referenced by suffer::while_awake().
trait_SHOUT3
const trait_id trait_SHOUT3("SHOUT3") ("SHOUT3") static
Referenced by suffer::while_awake().
trait_SNAIL_TRAIL
const trait_id trait_SNAIL_TRAIL("SNAIL_TRAIL") ("SNAIL_TRAIL") static
Referenced by suffer::from_other_mutations().
trait_SORES
const trait_id trait_SORES("SORES") ("SORES") static
Referenced by suffer::from_other_mutations().
trait_TROGLO
const trait_id trait_TROGLO("TROGLO") ("TROGLO") static
Referenced by suffer::in_sunlight().
trait_TROGLO2
const trait_id trait_TROGLO2("TROGLO2") ("TROGLO2") static
Referenced by suffer::in_sunlight().
trait_TROGLO3
const trait_id trait_TROGLO3("TROGLO3") ("TROGLO3") static
Referenced by suffer::in_sunlight().
trait_UNDINE_ABSORB_WATER
const trait_id trait_UNDINE_ABSORB_WATER("UNDINE_ABSORB_WATER") ("UNDINE_ABSORB_WATER") static
Referenced by suffer::while_underwater().
trait_UNSTABLE
const trait_id trait_UNSTABLE("UNSTABLE") ("UNSTABLE") static
Referenced by suffer::from_other_mutations().
trait_VOMITOUS
const trait_id trait_VOMITOUS("VOMITOUS") ("VOMITOUS") static
Referenced by suffer::while_awake().
trait_WEB_SPINNER
const trait_id trait_WEB_SPINNER("WEB_SPINNER") ("WEB_SPINNER") static
Referenced by suffer::from_other_mutations().
trait_WEB_WEAVER
const trait_id trait_WEB_WEAVER("WEB_WEAVER") ("WEB_WEAVER") static
Referenced by suffer::from_other_mutations().
trait_WINGS_INSECT_active
const trait_id trait_WINGS_INSECT_active("WINGS_INSECT_active") ("WINGS_INSECT_active") static
Referenced by suffer::from_other_mutations().
vitamin_vitC
const vitamin_id vitamin_vitC("vitC") ("vitC") static
Referenced by suffer::in_sunlight().