Cataclysm DDA: src/talker_avatar.cpp File Reference
talker_avatar.cpp File Reference
#include <memory>
#include <string>
#include "avatar.h"
#include "calendar.h"
#include "character.h"
#include "game.h"
#include "messages.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "npctrade.h"
#include "output.h"
#include "skill.h"
#include "talker.h"
#include "talker_avatar.h"
#include "translations.h"
Variables
static const efftype_id effect_pacified ("pacified")
static const efftype_id effect_pet ("pet")
static const itype_id itype_foodperson_mask ("foodperson_mask")
static const itype_id itype_foodperson_mask_on ("foodperson_mask_on")
static const trait_id trait_PROF_FOODP ("PROF_FOODP")
Variable Documentation
effect_pacified
const efftype_id effect_pacified("pacified") ("pacified") static
Referenced by talker_avatar::buy_monster().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by talker_avatar::buy_monster().
itype_foodperson_mask
const itype_id itype_foodperson_mask("foodperson_mask") ("foodperson_mask") static
Referenced by talker_avatar::get_topics().
itype_foodperson_mask_on
const itype_id itype_foodperson_mask_on("foodperson_mask_on") ("foodperson_mask_on") static
Referenced by talker_avatar::get_topics().
trait_PROF_FOODP
const trait_id trait_PROF_FOODP("PROF_FOODP") ("PROF_FOODP") static
Referenced by talker_avatar::get_topics().