Cataclysm DDA: src/talker_npc.cpp File Reference
talker_npc.cpp File Reference
#include <algorithm>
#include <memory>
#include <set>
#include <string>
#include <unordered_map>
#include <utility>
#include "auto_pickup.h"
#include "avatar.h"
#include "calendar.h"
#include "character.h"
#include "character_id.h"
#include "coordinates.h"
#include "debug.h"
#include "dialogue_chatbin.h"
#include "game.h"
#include "game_inventory.h"
#include "item.h"
#include "item_location.h"
#include "itype.h"
#include "magic.h"
#include "make_static.h"
#include "martialarts.h"
#include "messages.h"
#include "mission.h"
#include "mission_companion.h"
#include "mutation.h"
#include "npc.h"
#include "npctalk.h"
#include "npctrade.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "player_activity.h"
#include "proficiency.h"
#include "ret_val.h"
#include "skill.h"
#include "string_formatter.h"
#include "talker.h"
#include "talker_npc.h"
#include "translations.h"
#include "units.h"
#include "units_utility.h"
#include "value_ptr.h"
Enumerations
enum consumption_result { REFUSED = 0 , CONSUMED_SOME , CONSUMED_ALL }
Functions
static consumption_result try_consume (npc &p, item &it, std::string &reason)
Variables
static const efftype_id effect_lying_down ("lying_down")
static const efftype_id effect_narcosis ("narcosis")
static const efftype_id effect_npc_suspend ("npc_suspend")
static const efftype_id effect_sleep ("sleep")
static const faction_id faction_no_faction ("no_faction")
static const itype_id itype_foodperson_mask ("foodperson_mask")
static const itype_id itype_foodperson_mask_on ("foodperson_mask_on")
static const trait_id trait_DEBUG_MIND_CONTROL ("DEBUG_MIND_CONTROL")
static const trait_id trait_PROF_CHURL ("PROF_CHURL")
static const trait_id trait_PROF_FOODP ("PROF_FOODP")
static const trait_id trait_SAPROVORE ("SAPROVORE")
static constexpr int OWED_VAL = 1000
Enumeration Type Documentation
consumption_result
enum consumption_result
Enumerator
REFUSED
CONSUMED_SOME
CONSUMED_ALL
Definition at line 326 of file talker_npc.cpp.
{
     REFUSED = 0,
     CONSUMED_SOME, // Consumption didn't fail, but don't delete the item
     CONSUMED_ALL   // Consumption succeeded, delete the item
 };
Function Documentation
try_consume()
static consumption_result try_consume (npc & p, item & it, std::string & reason) static
Definition at line 334 of file talker_npc.cpp.
 {
     // TODO: Unify this with 'player::consume_item()'
     item &to_eat = it;
     if( to_eat.is_null() ) {
         debugmsg( "Null item to try_consume." );
         return REFUSED;
     }
     const auto &comest = to_eat.get_comestible();
     if( !comest ) {
         // Don't inform the player that we don't want to eat the lighter
         return REFUSED;
     }
     if( !p.will_accept_from_player( it ) ) {
         reason = p.chat_snippets().snip_consume_cant_accept.translated();
         return REFUSED;
     }
     // TODO: Make it not a copy+paste from player::consume_item
     int amount_used = 1;
     if( to_eat.is_food() ) {
         if( !p.can_consume_as_is( to_eat ) ) {
             reason = p.chat_snippets().snip_consume_cant_consume.translated();
             return REFUSED;
         } else {
             if( to_eat.rotten() && !p.as_character()->has_trait( trait_SAPROVORE ) ) {
                 //TODO: once npc needs are operational again check npc hunger state and allow eating if desperate
                 reason = p.chat_snippets().snip_consume_rotten.translated();
                 return REFUSED;
             }
             const time_duration &consume_time = p.get_consume_time( to_eat );
             p.mod_moves( -to_moves<int>( consume_time ) );
             p.consume( to_eat );
             reason = p.chat_snippets().snip_consume_eat.translated();
         }
     } else if( to_eat.is_medication() ) {
         if( !comest->tool.is_null() ) {
             bool has = p.has_amount( comest->tool, 1 );
             if( item::count_by_charges( comest->tool ) ) {
                 has = p.has_charges( comest->tool, 1 );
             }
             if( !has ) {
                 std::string talktag = p.chat_snippets().snip_consume_need_item.translated();
                 parse_tags( talktag, get_player_character(), p );
                 reason = string_format( _( talktag ), item::nname( comest->tool ) );
                 return REFUSED;
             }
             p.use_charges( comest->tool, 1 );
             reason = p.chat_snippets().snip_consume_med.translated();
         }
         if( to_eat.type->has_use() ) {
             amount_used = to_eat.type->invoke( &p, to_eat, p.pos() ).value_or( 0 );
             if( amount_used <= 0 ) {
                 reason = p.chat_snippets().snip_consume_nocharge.translated();
                 return REFUSED;
             }
             reason = p.chat_snippets().snip_consume_use_med.translated();
         }
         p.consume_effects( to_eat );
         to_eat.charges -= amount_used;
         p.mod_moves( -to_moves<int>( 1_seconds ) * 2.5 );
     } else {
         debugmsg( "Unknown comestible type of item: %s\n", to_eat.tname() );
     }
     if( to_eat.charges > 0 ) {
         return CONSUMED_SOME;
     }
     // If not consuming contents and charge <= 0, we just ate the last charge from the stack
     return CONSUMED_ALL;
 }
References _, Character::as_character(), Character::can_consume_as_is(), item::charges, npc::chat_snippets(), Character::consume(), Character::consume_effects(), CONSUMED_ALL, CONSUMED_SOME, item::count_by_charges(), debugmsg, item::get_comestible(), Character::get_consume_time(), get_player_character(), visitable::has_amount(), Character::has_charges(), Character::has_trait(), itype::has_use(), itype::invoke(), item::is_food(), item::is_medication(), item::is_null(), Creature::mod_moves(), item::nname(), parse_tags(), Creature::pos(), REFUSED, item::rotten(), dialogue_chatbin_snippets::snip_consume_cant_accept, dialogue_chatbin_snippets::snip_consume_cant_consume, dialogue_chatbin_snippets::snip_consume_eat, dialogue_chatbin_snippets::snip_consume_med, dialogue_chatbin_snippets::snip_consume_need_item, dialogue_chatbin_snippets::snip_consume_nocharge, dialogue_chatbin_snippets::snip_consume_rotten, dialogue_chatbin_snippets::snip_consume_use_med, string_format(), item::tname(), trait_SAPROVORE, translation::translated(), item::type, Character::use_charges(), and npc::will_accept_from_player().
Referenced by talker_npc::give_item_to().
Variable Documentation
effect_lying_down
const efftype_id effect_lying_down("lying_down") ("lying_down") static
Referenced by talker_npc::get_topics().
effect_narcosis
const efftype_id effect_narcosis("narcosis") ("narcosis") static
Referenced by talker_npc::get_topics().
effect_npc_suspend
const efftype_id effect_npc_suspend("npc_suspend") ("npc_suspend") static
Referenced by talker_npc::get_topics().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by talker_npc::get_topics().
faction_no_faction
const faction_id faction_no_faction("no_faction") ("no_faction") static
Referenced by talker_npc::add_faction_rep().
itype_foodperson_mask
const itype_id itype_foodperson_mask("foodperson_mask") ("foodperson_mask") static
Referenced by talker_npc::get_topics().
itype_foodperson_mask_on
const itype_id itype_foodperson_mask_on("foodperson_mask_on") ("foodperson_mask_on") static
Referenced by talker_npc::get_topics().
OWED_VAL
constexpr int OWED_VAL = 1000 static constexpr
Definition at line 240 of file talker_npc.cpp.
Referenced by talker_npc::parse_mod().
trait_DEBUG_MIND_CONTROL
const trait_id trait_DEBUG_MIND_CONTROL("DEBUG_MIND_CONTROL") ("DEBUG_MIND_CONTROL") static
Referenced by talker_npc::give_item_to().
trait_PROF_CHURL
const trait_id trait_PROF_CHURL("PROF_CHURL") ("PROF_CHURL") static
Referenced by talker_npc::get_topics().
trait_PROF_FOODP
const trait_id trait_PROF_FOODP("PROF_FOODP") ("PROF_FOODP") static
Referenced by talker_npc::get_topics().
trait_SAPROVORE
const trait_id trait_SAPROVORE("SAPROVORE") ("SAPROVORE") static
Referenced by try_consume().