Cataclysm DDA: src/talker_character.cpp File Reference
talker_character.cpp File Reference
#include <memory>
#include "character_id.h"
#include "character_martial_arts.h"
#include "effect.h"
#include "item.h"
#include "itype.h"
#include "magic.h"
#include "npc.h"
#include "npctalk.h"
#include "pimpl.h"
#include "player_activity.h"
#include "point.h"
#include "skill.h"
#include "talker_character.h"
#include "vehicle.h"
#include "weather.h"
Functions
static std::pair< bodypart_id, bodypart_id > temp_delta (const Character *u)
Variables
static const flag_id json_flag_FIT ("FIT")
static const json_character_flag json_flag_SEESLEEP ("SEESLEEP")
Function Documentation
temp_delta()
static std::pair<bodypart_id, bodypart_id> temp_delta (const Character * u) static
Definition at line 968 of file talker_character.cpp.
 {
     bodypart_id current_bp_extreme = u->get_all_body_parts().front();
     bodypart_id conv_bp_extreme = current_bp_extreme;
     for( const bodypart_id &bp : u->get_all_body_parts() ) {
         if( units::abs( u->get_part_temp_cur( bp ) - BODYTEMP_NORM ) >
             units::abs( u->get_part_temp_cur( current_bp_extreme ) - BODYTEMP_NORM ) ) {
             current_bp_extreme = bp;
         }
         if( units::abs( u->get_part_temp_conv( bp ) - BODYTEMP_NORM ) >
             units::abs( u->get_part_temp_conv( conv_bp_extreme ) - BODYTEMP_NORM ) ) {
             conv_bp_extreme = bp;
         }
     }
     return std::make_pair( current_bp_extreme, conv_bp_extreme );
 }
References units::abs(), BODYTEMP_NORM, bp, and u.
Referenced by talker_character_const::get_body_temp(), and talker_character_const::get_body_temp_delta().
Variable Documentation
json_flag_FIT
const flag_id json_flag_FIT("FIT") ("FIT") static
Referenced by talker_character::i_add_or_drop().
json_flag_SEESLEEP
const json_character_flag json_flag_SEESLEEP("SEESLEEP") ("SEESLEEP") static
Referenced by talker_character_const::can_see().