Cataclysm DDA: src/teleport.cpp File Reference
teleport.cpp File Reference
#include "teleport.h"
#include <cmath>
#include <memory>
#include <string>
#include "avatar.h"
#include "calendar.h"
#include "character.h"
#include "creature.h"
#include "creature_tracker.h"
#include "debug.h"
#include "effect.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "explosion.h"
#include "game.h"
#include "map.h"
#include "messages.h"
#include "point.h"
#include "rng.h"
#include "translations.h"
#include "type_id.h"
#include "viewer.h"
#include "map_iterator.h"
Variables
static const efftype_id effect_teleglow ("teleglow")
static const flag_id json_flag_DIMENSIONAL_ANCHOR ("DIMENSIONAL_ANCHOR")
static const flag_id json_flag_GRAB ("GRAB")
static const flag_id json_flag_TELEPORT_LOCK ("TELEPORT_LOCK")
Variable Documentation
effect_teleglow
const efftype_id effect_teleglow("teleglow") ("teleglow") static
Referenced by teleport::teleport_to_point().
json_flag_DIMENSIONAL_ANCHOR
const flag_id json_flag_DIMENSIONAL_ANCHOR("DIMENSIONAL_ANCHOR") ("DIMENSIONAL_ANCHOR") static
Referenced by teleport::teleport_to_point().
json_flag_GRAB
const flag_id json_flag_GRAB("GRAB") ("GRAB") static
Referenced by teleport::teleport_to_point().
json_flag_TELEPORT_LOCK
const flag_id json_flag_TELEPORT_LOCK("TELEPORT_LOCK") ("TELEPORT_LOCK") static
Referenced by teleport::teleport_to_point().