Cataclysm DDA: src/timed_event.h File Reference
timed_event.h File Reference
#include <list>
#include "calendar.h"
#include "coordinates.h"
#include "submap.h"
Classes
struct timed_event
class timed_event_manager
Macros
#define CATA_SRC_TIMED_EVENT_H
Enumerations
enum class timed_event_type : int {
NONE , HELP , WANTED , ROBOT_ATTACK ,
SPAWN_WYRMS , AMIGARA , AMIGARA_WHISPERS , ROOTS_DIE ,
TEMPLE_OPEN , TEMPLE_FLOOD , TEMPLE_SPAWN , DIM ,
ARTIFACT_LIGHT , DSA_ALRP_SUMMON , CUSTOM_LIGHT_LEVEL , TRANSFORM_RADIUS ,
UPDATE_MAPGEN , REVERT_SUBMAP , OVERRIDE_PLACE , NUM_TIMED_EVENT_TYPES
}
Functions
timed_event_manager & get_timed_events ()
Macro Definition Documentation
CATA_SRC_TIMED_EVENT_H
#define CATA_SRC_TIMED_EVENT_H
Definition at line 3 of file timed_event.h.
Enumeration Type Documentation
timed_event_type
enum timed_event_type : int strong
Enumerator
NONE
HELP
WANTED
ROBOT_ATTACK
SPAWN_WYRMS
AMIGARA
AMIGARA_WHISPERS
ROOTS_DIE
TEMPLE_OPEN
TEMPLE_FLOOD
TEMPLE_SPAWN
DIM
ARTIFACT_LIGHT
DSA_ALRP_SUMMON
CUSTOM_LIGHT_LEVEL
TRANSFORM_RADIUS
UPDATE_MAPGEN
REVERT_SUBMAP
OVERRIDE_PLACE
NUM_TIMED_EVENT_TYPES
Definition at line 11 of file timed_event.h.
                             : int {
     NONE,
     HELP,
     WANTED,
     ROBOT_ATTACK,
     SPAWN_WYRMS,
     AMIGARA,
     AMIGARA_WHISPERS,
     ROOTS_DIE,
     TEMPLE_OPEN,
     TEMPLE_FLOOD,
     TEMPLE_SPAWN,
     DIM,
     ARTIFACT_LIGHT,
     DSA_ALRP_SUMMON,
     CUSTOM_LIGHT_LEVEL,
     TRANSFORM_RADIUS,
     UPDATE_MAPGEN,
     REVERT_SUBMAP,
     OVERRIDE_PLACE,
     NUM_TIMED_EVENT_TYPES
 };
Function Documentation
get_timed_events()
timed_event_manager& get_timed_events ()
Definition at line 160 of file game.cpp.
 {
     return g->timed_events;
 }
Referenced by computer_session::action_amigara_log(), computer_session::action_amigara_start(), timed_event::actualize(), display::current_position_text(), debug_menu::debug(), mattack::dsa_drone_scan(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_alter_timed_events(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_custom_light_level(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_mapgen_update(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_place_override(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_revert_location(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_transform_radius(), computer_session::failure_amigara(), iexamine::fswitch(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), mattack::photograph(), timed_event_manager::serialize_all(), avatar::should_show_map_memory(), trapfunc::temple_flood(), spell_effect::timed_event(), and timed_event_manager::unserialize_all().