Cataclysm DDA: src/trade_ui.cpp File Reference
trade_ui.cpp File Reference
#include "trade_ui.h"
#include <cmath>
#include <cstdlib>
#include <memory>
#include "character.h"
#include "clzones.h"
#include "color.h"
#include "enums.h"
#include "game_constants.h"
#include "inventory_ui.h"
#include "item.h"
#include "npc.h"
#include "npctrade.h"
#include "npctrade_utils.h"
#include "options.h"
#include "output.h"
#include "point.h"
#include "string_formatter.h"
#include "type_id.h"
Namespaces
anonymous_namespace{trade_ui.cpp}
Functions
point anonymous_namespace{trade_ui.cpp}::_pane_orig (int side)
point anonymous_namespace{trade_ui.cpp}::_pane_size ()
Variables
static const flag_id json_flag_NO_UNWIELD ("NO_UNWIELD")
static const item_category_id item_category_ITEMS_WORN ("ITEMS_WORN")
static const item_category_id item_category_WEAPON_HELD ("WEAPON_HELD")
Variable Documentation
item_category_ITEMS_WORN
const item_category_id item_category_ITEMS_WORN("ITEMS_WORN") ("ITEMS_WORN") static
Referenced by trade_preset::cat_sort_compare().
item_category_WEAPON_HELD
const item_category_id item_category_WEAPON_HELD("WEAPON_HELD") ("WEAPON_HELD") static
Referenced by trade_preset::cat_sort_compare().
json_flag_NO_UNWIELD
const flag_id json_flag_NO_UNWIELD("NO_UNWIELD") ("NO_UNWIELD") static
Referenced by trade_preset::is_shown().