Cataclysm DDA: src/trait_group.cpp File Reference
trait_group.cpp File Reference
#include "trait_group.h"
#include <algorithm>
#include <cstddef>
#include <map>
#include <string>
#include <type_traits>
#include <utility>
#include "cata_assert.h"
#include "debug.h"
#include "json.h"
#include "mutation.h"
#include "rng.h"
#include "string_formatter.h"
#include "translations.h"
#include "ui.h"
Functions
static Trait_group_tag get_unique_trait_group_id ()
Function Documentation
get_unique_trait_group_id()
static Trait_group_tag get_unique_trait_group_id () static
Definition at line 38 of file trait_group.cpp.
 {
     // This is just a hint what id to use next. Overflow of it is defined and if the group
     // name is already used, we simply go the next id.
     static unsigned int next_id = 0;
     // Prefixing with a character outside the ASCII range, so it is hopefully unique and
     // (if actually printed somewhere) stands out. Theoretically those auto-generated group
     // names should not be seen anywhere.
     static const std::string unique_prefix = "\u01F7 ";
     while( true ) {
         Trait_group_tag new_group( unique_prefix + std::to_string( next_id++ ) );
         if( !new_group.is_valid() ) {
             return new_group;
         }
     }
 }
References string_id< T >::is_valid(), and to_string().
Referenced by trait_group::load_trait_group().