Cataclysm DDA: src/translations.h File Reference
translations.h File Reference
#include <locale>
#include "translation.h"
Macros
#define CATA_SRC_TRANSLATIONS_H
#define translate_marker(x) x
Marks a string literal to be extracted for translation.
#define translate_marker_context(c, x) x
Same as translate_marker, but also provides a context (string literal).
#define _(STRING) (STRING)
#define n_gettext(STRING1, STRING2, COUNT) ((COUNT) == 1 ? _(STRING1) : _(STRING2))
#define pgettext(STRING1, STRING2) _(STRING2)
#define npgettext(STRING0, STRING1, STRING2, COUNT) n_gettext(STRING1, STRING2, COUNT)
Functions
char * gettext (const char *msgid)
char * ngettext (const char *msgid, const char *msgid2, unsigned long int n)
std::string locale_dir ()
void set_language_from_options ()
void set_language (const std::string &lang)
Macro Definition Documentation
_
#define _ (STRING) (STRING)
Definition at line 89 of file translations.h.
CATA_SRC_TRANSLATIONS_H
#define CATA_SRC_TRANSLATIONS_H
Definition at line 3 of file translations.h.
n_gettext
#define n_gettext (STRING1, STRING2, COUNT) ((COUNT) == 1 ? _(STRING1) : _(STRING2))
Definition at line 91 of file translations.h.
npgettext
#define npgettext (STRING0, STRING1, STRING2, COUNT) n_gettext(STRING1, STRING2, COUNT)
Definition at line 93 of file translations.h.
pgettext
#define pgettext (STRING1, STRING2) _(STRING2)
Definition at line 92 of file translations.h.
translate_marker
#define translate_marker (x) x
Marks a string literal to be extracted for translation.
This is only for running xgettext via "lang/update_pot.sh". Use _ to extract and translate at run time. The macro itself does not do anything, the argument is passed through it without any changes.
Definition at line 17 of file translations.h.
translate_marker_context
#define translate_marker_context (c, x) x
Same as translate_marker, but also provides a context (string literal).
This is similar to pgettext, but it does not translate at run time. Like translate_marker it just passes the second argument through.
Definition at line 25 of file translations.h.
Function Documentation
gettext()
char* gettext (const char * msgid)
locale_dir()
std::string locale_dir ()
Definition at line 46 of file translations.cpp.
 {
     std::string loc_dir = PATH_INFO::langdir();
 #if defined(LOCALIZE)
 #if (defined(__DragonFly__) || defined(__FreeBSD__) || defined(__NetBSD__) || defined(__OpenBSD__)) && !defined(CATA_IS_ON_BSD)
 #define CATA_IS_ON_BSD
 #endif
 #if !defined(__ANDROID__) && ((defined(__linux__) || defined(CATA_IS_ON_BSD) || (defined(MACOSX) && !defined(TILES))))
     if( !PATH_INFO::base_path().empty() ) {
         loc_dir = PATH_INFO::base_path() + "share/locale";
     } else {
         loc_dir = PATH_INFO::langdir();
     }
 #endif
 #endif // LOCALIZE
     return loc_dir;
 }
References PATH_INFO::base_path(), and PATH_INFO::langdir().
Referenced by options_manager::get_langs_with_translation_files().
ngettext()
char* ngettext (const char * msgid, const char * msgid2, unsigned long int n)
set_language()
void set_language (const std::string & lang)
Definition at line 78 of file translations.cpp.
 {
 #if defined(LOCALIZE)
     DebugLog( D_INFO, D_MAIN ) << "Setting language to: '" << lang << '\'';
     TranslationManager::GetInstance().SetLanguage( lang );
 #if defined(_WIN32)
     // Use the ANSI code page 1252 to work around some language output bugs. (#8665)
     if( setlocale( LC_ALL, ".1252" ) == nullptr ) {
         DebugLog( D_WARNING, D_MAIN ) << "Error while setlocale(LC_ALL, '.1252').";
     }
 #endif
     reset_sanity_check_genders();
     // increment version to invalidate translation cache
     do {
         current_language_version++;
     } while( current_language_version == INVALID_LANGUAGE_VERSION );
 #else
     // Silence unused var warning
     ( void ) lang;
 #endif // LOCALIZE
     // Names depend on the language settings. They are loaded from different files
     // based on the currently used language. If that changes, we have to reload the
     // names.
     SNIPPET.reload_names( PATH_INFO::names() );
     set_title( string_format( _( "Cataclysm: Dark Days Ahead - %s" ), getVersionString() ) );
 }
References _, current_language_version, D_INFO, D_MAIN, D_WARNING, DebugLog(), getVersionString(), INVALID_LANGUAGE_VERSION, PATH_INFO::names(), snippet_library::reload_names(), reset_sanity_check_genders(), set_title(), SNIPPET, and string_format().
Referenced by set_language_from_options(), and game::toggle_language_to_en().
set_language_from_options()
void set_language_from_options ()
Definition at line 66 of file translations.cpp.
 {
 #if defined(LOCALIZE)
     const std::string system_lang = SystemLocale::Language().value_or( "en" );
     std::string lang_opt = get_option<std::string>( "USE_LANG" ).empty() ? system_lang :
                            get_option<std::string>( "USE_LANG" );
     set_language( lang_opt );
 #else
     set_language( "en" );
 #endif
 }
References SystemLocale::Language(), and set_language().
Referenced by main(), and options_manager::show().