Cataclysm DDA: src/translation.h File Reference
translation.h File Reference
#include <optional>
#include <string>
#include "translation_cache.h"
#include "value_ptr.h"
Classes
class translation
Class for storing translation context and raw string for deferred translation.
struct translation::plural_tag
struct translation::no_translation_tag
class translated_less
Function objects for comparing translations by their translated strings (singular form).
class translated_greater
class translated_less_equal
class translated_greater_equal
class translated_equal_to
class translated_not_equal_to
Macros
#define CATA_SRC_TRANSLATION_H
Functions
translation to_translation (const std::string &raw)
Shorthands for translation::to_translation.
translation to_translation (const std::string &ctxt, const std::string &raw)
translation pl_translation (const std::string &raw, const std::string &raw_pl)
Shorthands for translation::pl_translation.
translation pl_translation (const std::string &ctxt, const std::string &raw, const std::string &raw_pl)
translation no_translation (const std::string &str)
Shorthand for translation::no_translation.
std::ostream & operator<< (std::ostream &out, const translation &t)
Stream output and concatenation of translations.
std::string operator+ (const translation &lhs, const std::string &rhs)
std::string operator+ (const std::string &lhs, const translation &rhs)
std::string operator+ (const translation &lhs, const translation &rhs)
Macro Definition Documentation
CATA_SRC_TRANSLATION_H
#define CATA_SRC_TRANSLATION_H
Definition at line 3 of file translation.h.
Function Documentation
no_translation()
translation no_translation (const std::string & str)
Shorthand for translation::no_translation.
Definition at line 441 of file translation.cpp.
 {
     return translation::no_translation( str );
 }
References translation::no_translation().
Referenced by inventory_selector::_uncategorize(), inventory_selector::add_map_items(), inventory_selector::add_remote_map_items(), dialogue::add_response(), inventory_selector::add_vehicle_items(), build_resource_list(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_cast_spell(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_u_buy_monster(), regional_settings::finalize(), Item_factory::find_template(), json_talk_response::gen_responses(), input_manager::get_default_action_name(), conditional_t::get_get_translation(), options_manager::get_lang_options(), item_action_generator::load_item_action(), ma_buff_effect_type::ma_buff_effect_type(), and inventory_selector::naturalize_category().
operator+() [1/3]
std::string operator+ (const std::string & lhs, const translation & rhs)
Definition at line 456 of file translation.cpp.
 {
     return lhs + rhs.translated();
 }
References translation::translated().
operator+() [2/3]
std::string operator+ (const translation & lhs, const std::string & rhs)
Definition at line 451 of file translation.cpp.
 {
     return lhs.translated() + rhs;
 }
References translation::translated().
operator+() [3/3]
std::string operator+ (const translation & lhs, const translation & rhs)
Definition at line 461 of file translation.cpp.
 {
     return lhs.translated() + rhs.translated();
 }
References translation::translated().
operator<<()
std::ostream& operator<< (std::ostream & out, const translation & t)
Stream output and concatenation of translations.
Singular forms are used.
Definition at line 446 of file translation.cpp.
 {
     return out << t.translated();
 }
References translation::translated().
pl_translation() [1/2]
translation pl_translation (const std::string & ctxt, const std::string & raw, const std::string & raw_pl)
Definition at line 435 of file translation.cpp.
 {
     return translation::pl_translation( ctxt, raw, raw_pl );
 }
References translation::pl_translation().
pl_translation() [2/2]
translation pl_translation (const std::string & raw, const std::string & raw_pl)
Shorthands for translation::pl_translation.
Definition at line 430 of file translation.cpp.
 {
     return translation::pl_translation( raw, raw_pl );
 }
References translation::pl_translation().
Referenced by mtype::mtype().
to_translation() [1/2]
translation to_translation (const std::string & ctxt, const std::string & raw)
Definition at line 425 of file translation.cpp.
 {
     return translation::to_translation( ctxt, raw );
 }
References translation::to_translation().
to_translation() [2/2]
translation to_translation (const std::string & raw)
Shorthands for translation::to_translation.
Definition at line 420 of file translation.cpp.
 {
     return translation::to_translation( raw );
 }
References translation::to_translation().
Referenced by computer_session::action_research(), display::activity_level_str(), options_manager::add_options_android(), options_manager::add_options_debug(), options_manager::add_options_general(), options_manager::add_options_graphics(), options_manager::add_options_interface(), options_manager::add_options_world_default(), recipe::blueprint_parameter_ui_string(), build_resource_list(), options_manager::build_soundpacks_list(), options_manager::build_tilesets_list(), uilist::create_filter_input_context(), uilist::create_main_input_context(), Character::disp_info(), avatar::disp_medical(), talk_function::display_and_choose_opts(), mission_ui::draw_mission_ui(), eff_fun_bleed(), eff_fun_cold(), eff_fun_frostbite(), eff_fun_hot(), effects_description_for_creature(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_run_eoc_selector(), climbing_aid::finalize(), Item_factory::finalize_pre(), Creature::get_attitude_ui_data(), get_default_mode_input_context(), input_context::get_desc(), vpart_variant::get_label(), options_manager::get_lang_options(), get_mod_list_categories(), get_mod_list_tabs(), inventory_selector::get_navigation_data(), game::get_player_input(), Item_factory::init(), Messages::dialog::init(), init_colors(), initialize_default_custom_panels(), inventory_multiselector::inventory_multiselector(), inventory_selector::inventory_selector(), game::list_items(), monster_death_effect::load(), species_type::load(), move_mode::load(), profession::load(), scenario::load(), map_bash_info::load(), iuse_transform::load(), grab::load_grab(), leap_actor::load_internal(), mon_spellcasting_actor::load_internal(), melee_actor::load_internal(), gun_actor::load_internal(), make_crafting_context(), material_type::material_type(), options_manager::options_manager(), input_context::register_navigate_ui_list(), overmap_ui::search(), calendar_ui::select_time_point(), set_skills(), set_stats(), auto_notes::auto_note_manager_gui::show(), options_manager::show(), worldfactory::show_worldgen_tab_modselection(), target_ui::uitext_fire(), veh_act_desc(), display::weariness_text_color(), and debug_menu::wishskill().