Cataclysm DDA: src/trap.cpp File Reference
trap.cpp File Reference
#include "trap.h"
#include <algorithm>
#include <cmath>
#include <set>
#include <vector>
#include "assign.h"
#include "character.h"
#include "creature.h"
#include "debug.h"
#include "event.h"
#include "event_bus.h"
#include "generic_factory.h"
#include "item.h"
#include "json.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "messages.h"
#include "point.h"
#include "rng.h"
#include "string_formatter.h"
Namespaces
anonymous_namespace{trap.cpp}
Variables
static const flag_id json_flag_ECHOLOCATION_DETECTABLE ("ECHOLOCATION_DETECTABLE")
static const flag_id json_flag_SONAR_DETECTABLE ("SONAR_DETECTABLE")
static const proficiency_id proficiency_prof_spotting ("prof_spotting")
static const proficiency_id proficiency_prof_traps ("prof_traps")
static const proficiency_id proficiency_prof_trapsetting ("prof_trapsetting")
static const skill_id skill_traps ("traps")
const trap_str_id tr_beartrap_buried ("tr_beartrap_buried")
const trap_str_id tr_blade ("tr_blade")
const trap_str_id tr_dissector ("tr_dissector")
const trap_str_id tr_drain ("tr_drain")
const trap_str_id tr_glow ("tr_glow")
const trap_str_id tr_goo ("tr_goo")
const trap_str_id tr_hum ("tr_hum")
const trap_str_id tr_landmine ("tr_landmine")
const trap_str_id tr_landmine_buried ("tr_landmine_buried")
const trap_str_id tr_lava ("tr_lava")
const trap_str_id tr_ledge ("tr_ledge")
const trap_str_id tr_pit ("tr_pit")
const trap_str_id tr_portal ("tr_portal")
const trap_str_id tr_shadow ("tr_shadow")
const trap_str_id tr_shotgun_1 ("tr_shotgun_1")
const trap_str_id tr_shotgun_2 ("tr_shotgun_2")
const trap_str_id tr_sinkhole ("tr_sinkhole")
const trap_str_id tr_snake ("tr_snake")
const trap_str_id tr_telepad ("tr_telepad")
const trap_str_id tr_temple_flood ("tr_temple_flood")
const trap_str_id tr_temple_toggle ("tr_temple_toggle")
static const update_mapgen_id update_mapgen_none ("none")
generic_factory< trap > anonymous_namespace{trap.cpp}::trap_factory ("trap")
static std::vector< const trap * > funnel_traps
static std::vector< const trap * > sound_triggered_traps
trap_id tr_null
Variable Documentation
funnel_traps
std::vector<const trap *> funnel_traps static
Definition at line 113 of file trap.cpp.
Referenced by trap::finalize(), trap::get_funnels(), and trap::reset().
json_flag_ECHOLOCATION_DETECTABLE
const flag_id json_flag_ECHOLOCATION_DETECTABLE("ECHOLOCATION_DETECTABLE") ("ECHOLOCATION_DETECTABLE") static
Referenced by trap::detected_by_echolocation().
json_flag_SONAR_DETECTABLE
const flag_id json_flag_SONAR_DETECTABLE("SONAR_DETECTABLE") ("SONAR_DETECTABLE") static
Referenced by trap::detected_by_ground_sonar().
proficiency_prof_spotting
const proficiency_id proficiency_prof_spotting("prof_spotting") ("prof_spotting") static
Referenced by trap::detect_trap().
proficiency_prof_traps
const proficiency_id proficiency_prof_traps("prof_traps") ("prof_traps") static
Referenced by trap::detect_trap().
proficiency_prof_trapsetting
const proficiency_id proficiency_prof_trapsetting("prof_trapsetting") ("prof_trapsetting") static
Referenced by trap::detect_trap().
skill_traps
const skill_id skill_traps("traps") ("traps") static
Referenced by trap::detect_trap().
sound_triggered_traps
std::vector<const trap *> sound_triggered_traps static
Definition at line 120 of file trap.cpp.
Referenced by trap::finalize(), trap::get_sound_triggered_traps(), and trap::reset().
tr_beartrap_buried
const trap_str_id tr_beartrap_buried("tr_beartrap_buried") ("tr_beartrap_buried")
tr_blade
const trap_str_id tr_blade("tr_blade") ("tr_blade")
Referenced by MapExtras::mx_city_trap().
tr_dissector
const trap_str_id tr_dissector("tr_dissector") ("tr_dissector")
Referenced by map::draw_lab(), and science_room().
tr_drain
const trap_str_id tr_drain("tr_drain") ("tr_drain")
Referenced by map::create_anomaly().
tr_glow
const trap_str_id tr_glow("tr_glow") ("tr_glow")
Referenced by map::create_anomaly().
tr_goo
const trap_str_id tr_goo("tr_goo") ("tr_goo")
Referenced by iuse::can_goo(), explosion_handler::resonance_cascade(), and science_room().
tr_hum
const trap_str_id tr_hum("tr_hum") ("tr_hum")
Referenced by map::create_anomaly().
tr_landmine
const trap_str_id tr_landmine("tr_landmine") ("tr_landmine")
Referenced by MapExtras::mx_minefield().
tr_landmine_buried
const trap_str_id tr_landmine_buried("tr_landmine_buried") ("tr_landmine_buried")
Referenced by MapExtras::mx_minefield().
tr_lava
const trap_str_id tr_lava("tr_lava") ("tr_lava")
tr_ledge
const trap_str_id tr_ledge("tr_ledge") ("tr_ledge")
Referenced by map::actualize(), construct::check_support_below(), glide_activity_actor::do_turn(), trap::examine(), game::find_or_make_stairs(), game::fling_creature(), game::get_dangerous_tile(), Character::gravity_check(), submap::is_open_air(), iexamine::ledge(), map::maybe_trigger_prox_trap(), map::maybe_trigger_trap(), game::prompt_dangerous_tile(), map::ter_set(), map::valid_move(), and game::vertical_move().
tr_null
trap_id tr_null
Definition at line 421 of file trap.cpp.
Referenced by map::actualize(), spell_effect::add_trap(), map::clear_traps(), submap::ensure_nonuniform(), fake_map::fake_map(), trap::finalize(), submap::get_trap(), string_id< T >::id(), trap::is_null(), ter_t::load(), mremove_trap(), MapExtras::place_trap_if_clear(), map::remove_trap(), science_room(), set_ter_ids(), map::ter_set(), map::tr_at(), and map::trap_set().
tr_pit
const trap_str_id tr_pit("tr_pit") ("tr_pit")
Referenced by sinkhole_safety_roll().
tr_portal
const trap_str_id tr_portal("tr_portal") ("tr_portal")
Referenced by computer_session::action_portal(), map::draw_lab(), iuse::portal(), and explosion_handler::resonance_cascade().
tr_shadow
const trap_str_id tr_shadow("tr_shadow") ("tr_shadow")
Referenced by map::create_anomaly().
tr_shotgun_1
const trap_str_id tr_shotgun_1("tr_shotgun_1") ("tr_shotgun_1")
Referenced by trapfunc::shotgun().
tr_shotgun_2
const trap_str_id tr_shotgun_2("tr_shotgun_2") ("tr_shotgun_2")
Referenced by trapfunc::shotgun().
tr_sinkhole
const trap_str_id tr_sinkhole("tr_sinkhole") ("tr_sinkhole")
tr_snake
const trap_str_id tr_snake("tr_snake") ("tr_snake")
Referenced by map::create_anomaly().
tr_telepad
const trap_str_id tr_telepad("tr_telepad") ("tr_telepad")
Referenced by trap::examine(), and science_room().
tr_temple_flood
const trap_str_id tr_temple_flood("tr_temple_flood") ("tr_temple_flood")
Referenced by trapfunc::temple_flood().
tr_temple_toggle
const trap_str_id tr_temple_toggle("tr_temple_toggle") ("tr_temple_toggle")
update_mapgen_none
const update_mapgen_id update_mapgen_none("none") ("none") static
Referenced by trap::load().