Cataclysm DDA: src/trapfunc.cpp File Reference
trapfunc.cpp File Reference
#include "trap.h"
#include <algorithm>
#include <memory>
#include <string>
#include <unordered_map>
#include <utility>
#include "avatar.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_assert.h"
#include "character.h"
#include "colony.h"
#include "coordinates.h"
#include "creature.h"
#include "creature_tracker.h"
#include "damage.h"
#include "debug.h"
#include "enums.h"
#include "explosion.h"
#include "game.h"
#include "game_constants.h"
#include "item.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "mapgen_functions.h"
#include "messages.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "output.h"
#include "point.h"
#include "rng.h"
#include "sounds.h"
#include "teleport.h"
#include "timed_event.h"
#include "translations.h"
#include "units.h"
#include "viewer.h"
Functions
static float pit_effectiveness (const tripoint &p)
static bool query_for_item (const Character *pl, const itype_id &itemname, const char *que)
static tripoint random_neighbor (tripoint center)
static bool sinkhole_safety_roll (Character &you, const itype_id &itemname, const int diff)
const trap_function & trap_function_from_string (const std::string &function_name)
Takes the name of a trap function and returns a function pointer to it.
Variables
static const bionic_id bio_shock_absorber ("bio_shock_absorber")
static const damage_type_id damage_acid ("acid")
static const damage_type_id damage_bash ("bash")
static const damage_type_id damage_bullet ("bullet")
static const damage_type_id damage_cut ("cut")
static const damage_type_id damage_heat ("heat")
static const damage_type_id damage_pure ("pure")
static const efftype_id effect_beartrap ("beartrap")
static const efftype_id effect_heavysnare ("heavysnare")
static const efftype_id effect_in_pit ("in_pit")
static const efftype_id effect_lightsnare ("lightsnare")
static const efftype_id effect_ridden ("ridden")
static const efftype_id effect_slimed ("slimed")
static const efftype_id effect_slow_descent ("slow_descent")
static const efftype_id effect_strengthened_gravity ("strengthened_gravity")
static const efftype_id effect_tetanus ("tetanus")
static const efftype_id effect_weakened_gravity ("weakened_gravity")
static const flag_id json_flag_LEVITATION ("LEVITATION")
static const flag_id json_flag_PROXIMITY ("PROXIMITY")
static const flag_id json_flag_UNCONSUMED ("UNCONSUMED")
static const itype_id itype_bullwhip ("bullwhip")
static const itype_id itype_grapnel ("grapnel")
static const itype_id itype_grenade_act ("grenade_act")
static const itype_id itype_rope_30 ("rope_30")
static const json_character_flag json_flag_INFECTION_IMMUNE ("INFECTION_IMMUNE")
static const json_character_flag json_flag_WALL_CLING ("WALL_CLING")
static const material_id material_kevlar ("kevlar")
static const material_id material_steel ("steel")
static const material_id material_stone ("stone")
static const material_id material_veggy ("veggy")
static const mtype_id mon_blob ("mon_blob")
static const mtype_id mon_shadow ("mon_shadow")
static const mtype_id mon_shadow_snake ("mon_shadow_snake")
static const skill_id skill_throw ("throw")
static const species_id species_ROBOT ("ROBOT")
static const ter_str_id ter_t_floor_blue ("t_floor_blue")
static const ter_str_id ter_t_floor_green ("t_floor_green")
static const ter_str_id ter_t_floor_red ("t_floor_red")
static const ter_str_id ter_t_pit ("t_pit")
static const ter_str_id ter_t_rock_blue ("t_rock_blue")
static const ter_str_id ter_t_rock_green ("t_rock_green")
static const ter_str_id ter_t_rock_red ("t_rock_red")
static const trait_id trait_INFRESIST ("INFRESIST")
Function Documentation
pit_effectiveness()
static float pit_effectiveness (const tripoint & p) static
Definition at line 100 of file trapfunc.cpp.
 {
     units::volume corpse_volume = 0_ml;
     for( item &pit_content : get_map().i_at( p ) ) {
         if( pit_content.is_corpse() ) {
             corpse_volume += pit_content.volume();
         }
     }
     // 10 zombies; see item::volume
     const units::volume filled_volume = 10 * units::from_milliliter<float>( 62500 );
     return std::max( 0.0f, 1.0f - corpse_volume / filled_volume );
 }
References get_map(), and max().
Referenced by trapfunc::pit(), trapfunc::pit_glass(), and trapfunc::pit_spikes().
query_for_item()
static bool query_for_item (const Character * pl, const itype_id & itemname, const char * que) static
Definition at line 1103 of file trapfunc.cpp.
 {
     return pl->has_amount( itemname, 1 ) && ( !pl->is_avatar() || query_yn( que ) );
 }
References visitable::has_amount(), Creature::is_avatar(), and query_yn().
Referenced by trapfunc::sinkhole().
random_neighbor()
static tripoint random_neighbor (tripoint center) static
Definition at line 1108 of file trapfunc.cpp.
 {
     center.x += rng( -1, 1 );
     center.y += rng( -1, 1 );
     return center;
 }
References center, and rng().
Referenced by sinkhole_safety_roll().
sinkhole_safety_roll()
static bool sinkhole_safety_roll (Character & you, const itype_id & itemname, const int diff) static
Strength increases chance to attach grapnel, bullwhip, or rope when falling into a sinkhole Dexterity increases chance to attach grapnel, bullwhip, or rope when falling into a sinkhole Throw increases chance to attach grapnel, bullwhip, or rope when falling into a sinkhole
Definition at line 1115 of file trapfunc.cpp.
 {
     ///\EFFECT_STR increases chance to attach grapnel, bullwhip, or rope when falling into a sinkhole
     ///\EFFECT_DEX increases chance to attach grapnel, bullwhip, or rope when falling into a sinkhole
     ///\EFFECT_THROW increases chance to attach grapnel, bullwhip, or rope when falling into a sinkhole
     const int throwing_skill_level = round( you.get_skill_level( skill_throw ) );
     const int roll = rng( throwing_skill_level, throwing_skill_level + you.str_cur + you.dex_cur );
     map &here = get_map();
     if( roll < diff ) {
         you.add_msg_if_player( m_bad, _( "You fail to attach it…" ) );
         you.use_amount( itemname, 1 );
         here.spawn_item( random_neighbor( you.pos() ), itemname );
         return false;
     }
     std::vector<tripoint> safe;
     for( const tripoint &tmp : here.points_in_radius( you.pos(), 1 ) ) {
         if( here.passable( tmp ) && here.tr_at( tmp ) != tr_pit ) {
             safe.push_back( tmp );
         }
     }
     if( safe.empty() ) {
         you.add_msg_if_player( m_bad, _( "There's nowhere to pull yourself to, and you sink!" ) );
         you.use_amount( itemname, 1 );
         here.spawn_item( random_neighbor( you.pos() ), itemname );
         return false;
     } else {
         you.add_msg_player_or_npc( m_good, _( "You pull yourself to safety!" ),
                                    _( "<npcname> steps on a sinkhole, but manages to pull themselves to safety." ) );
         you.setpos( random_entry( safe ) );
         if( you.is_avatar() ) {
             g->update_map( you );
         }
         return true;
     }
 }
References _, Character::add_msg_if_player(), Character::add_msg_player_or_npc(), Character::dex_cur, g, get_map(), Character::get_skill_level(), Creature::is_avatar(), m_bad, m_good, map::passable(), map::points_in_radius(), Creature::pos(), random_entry(), random_neighbor(), rng(), round(), iexamine::safe(), Creature::setpos(), skill_throw, map::spawn_item(), Character::str_cur, map::tr_at(), tr_pit, and Character::use_amount().
Referenced by trapfunc::sinkhole().
trap_function_from_string()
const trap_function& trap_function_from_string (const std::string & function_name)
Takes the name of a trap function and returns a function pointer to it.
Parameters
function_name The name of the trapfunc function to find.
Returns
A function object with a pointer to the matched function, or to trapfunc::none if there is no match.
Definition at line 1655 of file trapfunc.cpp.
 {
     static const std::unordered_map<std::string, trap_function> funmap = {{
             { "none", trapfunc::none },
             { "bubble", trapfunc::bubble },
             { "glass", trapfunc::glass },
             { "cot", trapfunc::cot },
             { "beartrap", trapfunc::beartrap },
             { "board", trapfunc::board },
             { "caltrops", trapfunc::caltrops },
             { "caltrops_glass", trapfunc::caltrops_glass },
             { "tripwire", trapfunc::tripwire },
             { "crossbow", trapfunc::crossbow },
             { "shotgun", trapfunc::shotgun },
             { "blade", trapfunc::blade },
             { "snare_light", trapfunc::snare_light },
             { "snare_heavy", trapfunc::snare_heavy },
             { "landmine", trapfunc::landmine },
             { "telepad", trapfunc::telepad },
             { "goo", trapfunc::goo },
             { "dissector", trapfunc::dissector },
             { "sinkhole", trapfunc::sinkhole },
             { "pit", trapfunc::pit },
             { "pit_spikes", trapfunc::pit_spikes },
             { "pit_glass", trapfunc::pit_glass },
             { "lava", trapfunc::lava },
             { "portal", trapfunc::portal },
             { "ledge", trapfunc::ledge },
             { "boobytrap", trapfunc::boobytrap },
             { "temple_flood", trapfunc::temple_flood },
             { "temple_toggle", trapfunc::temple_toggle },
             { "glow", trapfunc::glow },
             { "hum", trapfunc::hum },
             { "shadow", trapfunc::shadow },
             { "map_regen", trapfunc::map_regen },
             { "drain", trapfunc::drain },
             { "spell", trapfunc::cast_spell },
             { "snake", trapfunc::snake },
             { "sound_detect", trapfunc::sound_detect }
         }
     };
     const auto iter = funmap.find( function_name );
     if( iter != funmap.end() ) {
         return iter->second;
     }
     debugmsg( "Could not find a trapfunc function matching '%s'!", function_name );
     static const trap_function null_fun = trapfunc::none;
     return null_fun;
 }
References trapfunc::beartrap(), trapfunc::blade(), trapfunc::board(), trapfunc::boobytrap(), trapfunc::bubble(), trapfunc::caltrops(), trapfunc::caltrops_glass(), trapfunc::cast_spell(), trapfunc::cot(), trapfunc::crossbow(), debugmsg, trapfunc::dissector(), trapfunc::drain(), trapfunc::glass(), trapfunc::glow(), trapfunc::goo(), trapfunc::hum(), trapfunc::landmine(), trapfunc::lava(), trapfunc::ledge(), trapfunc::map_regen(), trapfunc::none(), trapfunc::pit(), trapfunc::pit_glass(), trapfunc::pit_spikes(), trapfunc::portal(), trapfunc::shadow(), trapfunc::shotgun(), trapfunc::sinkhole(), trapfunc::snake(), trapfunc::snare_heavy(), trapfunc::snare_light(), trapfunc::sound_detect(), trapfunc::telepad(), trapfunc::temple_flood(), trapfunc::temple_toggle(), and trapfunc::tripwire().
Referenced by trap::load().
Variable Documentation
bio_shock_absorber
const bionic_id bio_shock_absorber("bio_shock_absorber") ("bio_shock_absorber") static
Referenced by trapfunc::ledge(), trapfunc::pit(), trapfunc::pit_glass(), and trapfunc::pit_spikes().
damage_acid
const damage_type_id damage_acid("acid") ("acid") static
Referenced by trapfunc::glow().
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by trapfunc::beartrap(), trapfunc::blade(), trapfunc::pit(), and trapfunc::snare_heavy().
damage_bullet
const damage_type_id damage_bullet("bullet") ("bullet") static
Referenced by trapfunc::shotgun().
damage_cut
const damage_type_id damage_cut("cut") ("cut") static
Referenced by trapfunc::beartrap(), trapfunc::blade(), trapfunc::board(), trapfunc::caltrops(), trapfunc::caltrops_glass(), trapfunc::crossbow(), trapfunc::dissector(), trapfunc::glass(), trapfunc::goo(), trapfunc::pit_glass(), and trapfunc::pit_spikes().
damage_heat
const damage_type_id damage_heat("heat") ("heat") static
Referenced by trapfunc::lava().
damage_pure
const damage_type_id damage_pure("pure") ("pure") static
Referenced by trapfunc::drain(), and trapfunc::tripwire().
effect_beartrap
const efftype_id effect_beartrap("beartrap") ("beartrap") static
Referenced by trapfunc::beartrap().
effect_heavysnare
const efftype_id effect_heavysnare("heavysnare") ("heavysnare") static
Referenced by trapfunc::snare_heavy().
effect_in_pit
const efftype_id effect_in_pit("in_pit") ("in_pit") static
Referenced by trapfunc::pit(), trapfunc::pit_glass(), and trapfunc::pit_spikes().
effect_lightsnare
const efftype_id effect_lightsnare("lightsnare") ("lightsnare") static
Referenced by trapfunc::snare_light().
effect_ridden
const efftype_id effect_ridden("ridden") ("ridden") static
Referenced by trapfunc::beartrap(), trapfunc::blade(), trapfunc::board(), trapfunc::bubble(), trapfunc::caltrops(), trapfunc::crossbow(), trapfunc::dissector(), trapfunc::glow(), trapfunc::goo(), trapfunc::lava(), trapfunc::pit(), trapfunc::pit_glass(), trapfunc::pit_spikes(), trapfunc::shotgun(), trapfunc::sinkhole(), trapfunc::snare_heavy(), trapfunc::snare_light(), and trapfunc::tripwire().
effect_slimed
const efftype_id effect_slimed("slimed") ("slimed") static
Referenced by trapfunc::goo().
effect_slow_descent
const efftype_id effect_slow_descent("slow_descent") ("slow_descent") static
Referenced by trapfunc::ledge().
effect_strengthened_gravity
const efftype_id effect_strengthened_gravity("strengthened_gravity") ("strengthened_gravity") static
Referenced by trapfunc::ledge().
effect_tetanus
const efftype_id effect_tetanus("tetanus") ("tetanus") static
Referenced by trapfunc::beartrap(), trapfunc::board(), trapfunc::caltrops(), trapfunc::pit_glass(), and trapfunc::pit_spikes().
effect_weakened_gravity
const efftype_id effect_weakened_gravity("weakened_gravity") ("weakened_gravity") static
Referenced by trapfunc::ledge().
itype_bullwhip
const itype_id itype_bullwhip("bullwhip") ("bullwhip") static
Referenced by trapfunc::sinkhole().
itype_grapnel
const itype_id itype_grapnel("grapnel") ("grapnel") static
Referenced by trapfunc::sinkhole().
itype_grenade_act
const itype_id itype_grenade_act("grenade_act") ("grenade_act") static
Referenced by trapfunc::boobytrap().
itype_rope_30
const itype_id itype_rope_30("rope_30") ("rope_30") static
Referenced by trapfunc::sinkhole().
json_flag_INFECTION_IMMUNE
const json_character_flag json_flag_INFECTION_IMMUNE("INFECTION_IMMUNE") ("INFECTION_IMMUNE") static
Referenced by trapfunc::beartrap(), trapfunc::board(), trapfunc::caltrops(), trapfunc::pit_glass(), and trapfunc::pit_spikes().
json_flag_LEVITATION
const flag_id json_flag_LEVITATION("LEVITATION") ("LEVITATION") static
Referenced by trapfunc::ledge().
json_flag_PROXIMITY
const flag_id json_flag_PROXIMITY("PROXIMITY") ("PROXIMITY") static
Referenced by trapfunc::cast_spell().
json_flag_UNCONSUMED
const flag_id json_flag_UNCONSUMED("UNCONSUMED") ("UNCONSUMED") static
Referenced by trapfunc::cast_spell().
json_flag_WALL_CLING
const json_character_flag json_flag_WALL_CLING("WALL_CLING") ("WALL_CLING") static
Referenced by trapfunc::ledge().
material_kevlar
const material_id material_kevlar("kevlar") ("kevlar") static
Referenced by trapfunc::lava().
material_steel
const material_id material_steel("steel") ("steel") static
Referenced by trapfunc::lava().
material_stone
const material_id material_stone("stone") ("stone") static
Referenced by trapfunc::lava().
material_veggy
const material_id material_veggy("veggy") ("veggy") static
Referenced by trapfunc::lava().
mon_blob
const mtype_id mon_blob("mon_blob") ("mon_blob") static
Referenced by trapfunc::goo().
mon_shadow
const mtype_id mon_shadow("mon_shadow") ("mon_shadow") static
Referenced by trapfunc::shadow().
mon_shadow_snake
const mtype_id mon_shadow_snake("mon_shadow_snake") ("mon_shadow_snake") static
Referenced by trapfunc::snake().
skill_throw
const skill_id skill_throw("throw") ("throw") static
Referenced by sinkhole_safety_roll().
species_ROBOT
const species_id species_ROBOT("ROBOT") ("ROBOT") static
Referenced by trapfunc::dissector(), and trapfunc::goo().
ter_t_floor_blue
const ter_str_id ter_t_floor_blue("t_floor_blue") ("t_floor_blue") static
Referenced by trapfunc::temple_toggle().
ter_t_floor_green
const ter_str_id ter_t_floor_green("t_floor_green") ("t_floor_green") static
Referenced by trapfunc::temple_toggle().
ter_t_floor_red
const ter_str_id ter_t_floor_red("t_floor_red") ("t_floor_red") static
Referenced by trapfunc::temple_toggle().
ter_t_pit
const ter_str_id ter_t_pit("t_pit") ("t_pit") static
Referenced by trapfunc::pit_glass(), trapfunc::pit_spikes(), and trapfunc::sinkhole().
ter_t_rock_blue
const ter_str_id ter_t_rock_blue("t_rock_blue") ("t_rock_blue") static
Referenced by trapfunc::temple_toggle().
ter_t_rock_green
const ter_str_id ter_t_rock_green("t_rock_green") ("t_rock_green") static
Referenced by trapfunc::temple_toggle().
ter_t_rock_red
const ter_str_id ter_t_rock_red("t_rock_red") ("t_rock_red") static
Referenced by trapfunc::temple_toggle().
trait_INFRESIST
const trait_id trait_INFRESIST("INFRESIST") ("INFRESIST") static
Referenced by trapfunc::beartrap(), trapfunc::board(), trapfunc::caltrops(), trapfunc::pit_glass(), and trapfunc::pit_spikes().