Cataclysm DDA: src/trap.h File Reference
trap.h File Reference
#include <cstddef>
#include <functional>
#include <iosfwd>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "color.h"
#include "flat_set.h"
#include "magic.h"
#include "translations.h"
#include "type_id.h"
#include "units.h"
Classes
struct vehicle_handle_trap_data
struct trap
Some traps aren't actually traps in the usual sense of the word.
Namespaces
trapfunc
Macros
#define CATA_SRC_TRAP_H
Typedefs
using trap_function = std::function< bool(const tripoint &, Creature *, item *)>
Functions
bool trapfunc::none (const tripoint &, Creature *, item *)
bool trapfunc::bubble (const tripoint &p, Creature *c, item *i)
bool trapfunc::glass (const tripoint &p, Creature *c, item *i)
bool trapfunc::cot (const tripoint &p, Creature *c, item *i)
bool trapfunc::beartrap (const tripoint &p, Creature *c, item *i)
bool trapfunc::snare_light (const tripoint &p, Creature *c, item *i)
bool trapfunc::snare_heavy (const tripoint &p, Creature *c, item *i)
bool trapfunc::board (const tripoint &p, Creature *c, item *i)
bool trapfunc::caltrops (const tripoint &p, Creature *c, item *i)
bool trapfunc::caltrops_glass (const tripoint &p, Creature *c, item *i)
bool trapfunc::tripwire (const tripoint &p, Creature *c, item *i)
bool trapfunc::crossbow (const tripoint &p, Creature *c, item *i)
bool trapfunc::shotgun (const tripoint &p, Creature *c, item *i)
bool trapfunc::blade (const tripoint &p, Creature *c, item *i)
bool trapfunc::landmine (const tripoint &p, Creature *c, item *i)
bool trapfunc::telepad (const tripoint &p, Creature *c, item *i)
bool trapfunc::goo (const tripoint &p, Creature *c, item *i)
bool trapfunc::dissector (const tripoint &p, Creature *c, item *i)
bool trapfunc::sinkhole (const tripoint &p, Creature *c, item *i)
bool trapfunc::pit (const tripoint &p, Creature *c, item *i)
bool trapfunc::pit_spikes (const tripoint &p, Creature *c, item *i)
bool trapfunc::pit_glass (const tripoint &p, Creature *c, item *i)
bool trapfunc::lava (const tripoint &p, Creature *c, item *i)
bool trapfunc::portal (const tripoint &p, Creature *c, item *i)
bool trapfunc::ledge (const tripoint &p, Creature *c, item *i)
bool trapfunc::boobytrap (const tripoint &p, Creature *c, item *i)
bool trapfunc::temple_flood (const tripoint &p, Creature *c, item *i)
bool trapfunc::temple_toggle (const tripoint &p, Creature *c, item *i)
bool trapfunc::glow (const tripoint &p, Creature *c, item *i)
bool trapfunc::hum (const tripoint &p, Creature *c, item *i)
bool trapfunc::shadow (const tripoint &p, Creature *c, item *i)
bool trapfunc::map_regen (const tripoint &p, Creature *c, item *i)
bool trapfunc::drain (const tripoint &p, Creature *c, item *i)
bool trapfunc::snake (const tripoint &p, Creature *c, item *i)
bool trapfunc::cast_spell (const tripoint &p, Creature *critter, item *)
bool trapfunc::sound_detect (const tripoint &p, Creature *, item *)
Made to test sound-triggered traps.
const trap_function & trap_function_from_string (const std::string &function_name)
Takes the name of a trap function and returns a function pointer to it.
Variables
trap_id tr_null
const trap_str_id tr_beartrap_buried
const trap_str_id tr_shotgun_2
const trap_str_id tr_shotgun_1
const trap_str_id tr_blade
const trap_str_id tr_landmine
const trap_str_id tr_landmine_buried
const trap_str_id tr_telepad
const trap_str_id tr_goo
const trap_str_id tr_dissector
const trap_str_id tr_sinkhole
const trap_str_id tr_pit
const trap_str_id tr_lava
const trap_str_id tr_portal
const trap_str_id tr_ledge
const trap_str_id tr_temple_flood
const trap_str_id tr_temple_toggle
const trap_str_id tr_glow
const trap_str_id tr_hum
const trap_str_id tr_shadow
const trap_str_id tr_drain
const trap_str_id tr_snake
Macro Definition Documentation
CATA_SRC_TRAP_H
#define CATA_SRC_TRAP_H
Definition at line 3 of file trap.h.
Typedef Documentation
trap_function
using trap_function = std::function<bool(const tripoint &, Creature *, item *)>
Definition at line 87 of file trap.h.
Function Documentation
trap_function_from_string()
const trap_function& trap_function_from_string (const std::string & function_name)
Takes the name of a trap function and returns a function pointer to it.
Parameters
function_name The name of the trapfunc function to find.
Returns
A function object with a pointer to the matched function, or to trapfunc::none if there is no match.
Definition at line 1655 of file trapfunc.cpp.
 {
     static const std::unordered_map<std::string, trap_function> funmap = {{
             { "none", trapfunc::none },
             { "bubble", trapfunc::bubble },
             { "glass", trapfunc::glass },
             { "cot", trapfunc::cot },
             { "beartrap", trapfunc::beartrap },
             { "board", trapfunc::board },
             { "caltrops", trapfunc::caltrops },
             { "caltrops_glass", trapfunc::caltrops_glass },
             { "tripwire", trapfunc::tripwire },
             { "crossbow", trapfunc::crossbow },
             { "shotgun", trapfunc::shotgun },
             { "blade", trapfunc::blade },
             { "snare_light", trapfunc::snare_light },
             { "snare_heavy", trapfunc::snare_heavy },
             { "landmine", trapfunc::landmine },
             { "telepad", trapfunc::telepad },
             { "goo", trapfunc::goo },
             { "dissector", trapfunc::dissector },
             { "sinkhole", trapfunc::sinkhole },
             { "pit", trapfunc::pit },
             { "pit_spikes", trapfunc::pit_spikes },
             { "pit_glass", trapfunc::pit_glass },
             { "lava", trapfunc::lava },
             { "portal", trapfunc::portal },
             { "ledge", trapfunc::ledge },
             { "boobytrap", trapfunc::boobytrap },
             { "temple_flood", trapfunc::temple_flood },
             { "temple_toggle", trapfunc::temple_toggle },
             { "glow", trapfunc::glow },
             { "hum", trapfunc::hum },
             { "shadow", trapfunc::shadow },
             { "map_regen", trapfunc::map_regen },
             { "drain", trapfunc::drain },
             { "spell", trapfunc::cast_spell },
             { "snake", trapfunc::snake },
             { "sound_detect", trapfunc::sound_detect }
         }
     };
     const auto iter = funmap.find( function_name );
     if( iter != funmap.end() ) {
         return iter->second;
     }
     debugmsg( "Could not find a trapfunc function matching '%s'!", function_name );
     static const trap_function null_fun = trapfunc::none;
     return null_fun;
 }
References trapfunc::beartrap(), trapfunc::blade(), trapfunc::board(), trapfunc::boobytrap(), trapfunc::bubble(), trapfunc::caltrops(), trapfunc::caltrops_glass(), trapfunc::cast_spell(), trapfunc::cot(), trapfunc::crossbow(), debugmsg, trapfunc::dissector(), trapfunc::drain(), trapfunc::glass(), trapfunc::glow(), trapfunc::goo(), trapfunc::hum(), trapfunc::landmine(), trapfunc::lava(), trapfunc::ledge(), trapfunc::map_regen(), trapfunc::none(), trapfunc::pit(), trapfunc::pit_glass(), trapfunc::pit_spikes(), trapfunc::portal(), trapfunc::shadow(), trapfunc::shotgun(), trapfunc::sinkhole(), trapfunc::snake(), trapfunc::snare_heavy(), trapfunc::snare_light(), trapfunc::sound_detect(), trapfunc::telepad(), trapfunc::temple_flood(), trapfunc::temple_toggle(), and trapfunc::tripwire().
Referenced by trap::load().
Variable Documentation
tr_beartrap_buried
const trap_str_id tr_beartrap_buried extern
tr_blade
const trap_str_id tr_blade extern
tr_dissector
const trap_str_id tr_dissector extern
tr_drain
const trap_str_id tr_drain extern
tr_glow
const trap_str_id tr_glow extern
tr_goo
const trap_str_id tr_goo extern
tr_hum
const trap_str_id tr_hum extern
tr_landmine
const trap_str_id tr_landmine extern
tr_landmine_buried
const trap_str_id tr_landmine_buried extern
tr_lava
const trap_str_id tr_lava extern
tr_ledge
const trap_str_id tr_ledge extern
tr_null
trap_id tr_null extern
Definition at line 421 of file trap.cpp.
Referenced by map::actualize(), spell_effect::add_trap(), map::clear_traps(), submap::ensure_nonuniform(), fake_map::fake_map(), trap::finalize(), submap::get_trap(), string_id< T >::id(), trap::is_null(), ter_t::load(), mremove_trap(), MapExtras::place_trap_if_clear(), map::remove_trap(), science_room(), set_ter_ids(), map::ter_set(), map::tr_at(), and map::trap_set().
tr_pit
const trap_str_id tr_pit extern
tr_portal
const trap_str_id tr_portal extern
tr_shadow
const trap_str_id tr_shadow extern
tr_shotgun_1
const trap_str_id tr_shotgun_1 extern
tr_shotgun_2
const trap_str_id tr_shotgun_2 extern
tr_sinkhole
const trap_str_id tr_sinkhole extern
tr_snake
const trap_str_id tr_snake extern
tr_telepad
const trap_str_id tr_telepad extern
tr_temple_flood
const trap_str_id tr_temple_flood extern
tr_temple_toggle
const trap_str_id tr_temple_toggle extern