Cataclysm DDA: src/try_parse_integer.cpp File Reference
try_parse_integer.cpp File Reference
#include "try_parse_integer.h"
#include <sstream>
#include "translations.h"
Functions
template<typename T >
ret_val< T > try_parse_integer (const std::string_view s, bool use_locale)
Convert a string to an integer or provide an error message indicating what went wrong in trying to do so.
template ret_val< int > try_parse_integer< int > (const std::string_view, bool use_locale)
template ret_val< long > try_parse_integer< long > (const std::string_view, bool use_locale)
template ret_val< long long > try_parse_integer< long long > (const std::string_view, bool use_locale)
Function Documentation
try_parse_integer()
template<typename T > ret_val<T> try_parse_integer (std::string_view s, bool use_locale)
Convert a string to an integer or provide an error message indicating what went wrong in trying to do so.
Parameters
use_locale Whether to use a number-parsing function that might permit formats specific to the user's locale. Generally would be true for player-input values, and false for values from e.g. game data files.
Definition at line 8 of file try_parse_integer.cpp.
 {
     // Using stringstream-based parsing because that's the only one in the
     // standard library for which it's possible to turn off the
     // locale-dependency.  Once we're using C++17 we could use a combination of
     // std::from_chars and std::strto* functions, but this should be fine so
     // long as the code is not performance-critical.
     std::istringstream buffer{ std::string( s ) };
 #ifdef __APPLE__
     // On Apple platforms we always use the classic locale, because the other
     // locales seem to behave strangely.  See
     // https://github.com/CleverRaven/Cataclysm-DDA/pull/48431 for more
     // discussion.
     static_cast<void>( use_locale );
     buffer.imbue( std::locale::classic() );
 #else
     if( !use_locale ) {
         buffer.imbue( std::locale::classic() );
     }
 #endif
     T result;
     buffer >> result;
     if( !buffer ) {
         return ret_val<T>::make_failure(
                    0, string_format( _( "Could not convert '%s' to an integer" ), s ) );
     }
     char c;
     buffer >> c;
     if( buffer ) {
         return ret_val<T>::make_failure(
                    0, string_format( _( "Stray characters after integer in '%s'" ), s ) );
     }
     return ret_val<T>::make_success( result );
 }
References _, c, ret_val< T >::make_failure(), ret_val< T >::make_success(), and string_format().
try_parse_integer< int >()
template ret_val<int> try_parse_integer< int > (const std::string_view , bool use_locale)
Referenced by item::ammo_info(), Item_factory::finalize_pre(), get_quality_from_string(), item::get_var(), getGasDiscountCardQuality(), make_gun_projectile(), options_manager::cOpt::setValue(), and debug_menu::teleport_overmap().
try_parse_integer< long >()
template ret_val<long> try_parse_integer< long > (const std::string_view , bool use_locale)
try_parse_integer< long long >()
template ret_val<long long> try_parse_integer< long long > (const std::string_view , bool use_locale)