Cataclysm DDA: src/turret.cpp File Reference
turret.cpp File Reference
#include "vehicle.h"
#include <algorithm>
#include <memory>
#include <string>
#include "avatar.h"
#include "character.h"
#include "creature.h"
#include "debug.h"
#include "enums.h"
#include "gun_mode.h"
#include "item.h"
#include "itype.h"
#include "messages.h"
#include "npc.h"
#include "projectile.h"
#include "ranged.h"
#include "string_formatter.h"
#include "translations.h"
#include "ui.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle_selector.h"
#include "vpart_position.h"
#include "vpart_range.h"
Variables
static const efftype_id effect_on_roof ("on_roof")
static const itype_id fuel_type_battery ("battery")
static const skill_id skill_gun ("gun")
static const trait_id trait_BRAWLER ("BRAWLER")
Variable Documentation
effect_on_roof
const efftype_id effect_on_roof("on_roof") ("on_roof") static
Referenced by turret_data::post_fire(), and turret_data::prepare_fire().
fuel_type_battery
const itype_id fuel_type_battery("battery") ("battery") static
Referenced by turret_data::post_fire(), and turret_data::query().
skill_gun
const skill_id skill_gun("gun") ("gun") static
Referenced by vehicle_part::get_targeting_npc().
trait_BRAWLER
const trait_id trait_BRAWLER("BRAWLER") ("BRAWLER") static
Referenced by vehicle::turrets_aim().