Cataclysm DDA: src/ui.h File Reference
ui.h File Reference
#include <functional>
#include <initializer_list>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>
#include "cata_assert.h"
#include "color.h"
#include "cuboid_rectangle.h"
#include "cursesdef.h"
#include "input_context.h"
#include "memory_fast.h"
#include "pimpl.h"
#include "point.h"
#include "string_formatter.h"
Classes
struct mvwzstr
mvwzstr: line of text with horizontal offset and color
struct uilist_entry
uilist_entry: entry line for uilist
class uilist_callback
uilist::query() handles most input events first, and then passes the event to the callback if it can't handle it.
class uilist
uilist: scrolling vertical list menu
class uilist::size_scalar
struct uilist::size_scalar::auto_assign
class uilist::pos_scalar
struct uilist::pos_scalar::auto_assign
class uimenu
Hack ui list to behave as a multi column menu.
struct uimenu::col
class pointmenu_cb
Callback for uilist that pairs menu entries with points When an entry is selected, view will be centered on the paired point.
Macros
#define CATA_SRC_UI_H
Functions
catacurses::window new_centered_win (int nlines, int ncols)
void kill_advanced_inv ()
void temp_hide_advanced_inv ()
template<typename V , typename S >
std::enable_if_t< !std::is_enum_v< V >, V > inc_clamp_wrap (V val, int delta, S size)
Helper for typical UI list navigation with wrap-around Add delta to val.
template<typename V , typename S >
std::enable_if_t< !std::is_enum_v< V >, V > inc_clamp_wrap (V val, bool inc, S size)
Helper for typical arrow key UI list navigation with wrap-around Add 1/-1 to val, then wrap to the range [0,size)
template<typename T , typename I >
std::enable_if_t< std::is_enum_v< T >, T > inc_clamp_wrap (T val, I inc, T size)
Helper for typical arrow key UI list navigation with wrap-around Specialized for enum values Add 1/-1 to val, then wrap to the range [0,size)
template<typename V , typename S >
std::enable_if_t< !std::is_enum_v< V >, V > inc_clamp (V val, int delta, S min, S max)
Helper for typical UI list navigation without wrap-around Add delta to val, then clamp to the range [min,max].
template<typename V , typename S >
std::enable_if_t< !std::is_enum_v< V >, V > inc_clamp (V val, bool inc, S max)
Helper for typical arrow key UI list navigation without wrap-around Add 1/-1 to val, then clamp to the range [0,max].
template<typename V , typename S >
std::enable_if_t< !std::is_enum_v< V >, V > inc_clamp (V val, int delta, S max)
Helper for typical UI list navigation without wrap-around Add delta to val, then clamp to the range [0,max].
template<typename V , typename S >
std::enable_if_t< !std::is_enum_v< V >, V > inc_clamp (V val, bool inc, S min, S max)
Helper for typical arrow key UI list navigation without wrap-around Add 1/-1 to val, then clamp to the range [min,max].
template<typename T , typename I >
std::enable_if_t< std::is_enum_v< T >, T > inc_clamp (T val, I inc, T size)
Helper for typical arrow key UI list navigation without wrap-around Specialized for enum values Add 1/-1 to val, then clamp to the range [0,max].
template<typename V , typename S >
bool navigate_ui_list (const std::string &action, V &val, int page_delta, S size, bool wrap)
Helper for typical UI list navigation with wrap-around Handles up, down, scroll_up and _down, page_up and _down, home, and end Returns true if an action/input was handled.
std::pair< int, int > subindex_around_cursor (int num_entries, int available_space, int cursor_pos, bool focused=true)
Return indexes [start, end) that should be displayed from list long num_entries, given that cursor is at position cursor_pos and we have available_space spaces.
Variables
const int UILIST_ERROR = -1024
uilist constants
const int UILIST_WAIT_INPUT = -1025
const int UILIST_UNBOUND = -1026
const int UILIST_CANCEL = -1027
const int UILIST_TIMEOUT = -1028
const int UILIST_ADDITIONAL = -1029
const int MENU_AUTOASSIGN = -1
Macro Definition Documentation
CATA_SRC_UI_H
#define CATA_SRC_UI_H
Definition at line 3 of file ui.h.
Function Documentation
inc_clamp() [1/5]
template<typename T , typename I > std::enable_if_t<std::is_enum_v<T>, T> inc_clamp (T val, I inc, T size) inline
Helper for typical arrow key UI list navigation without wrap-around Specialized for enum values Add 1/-1 to val, then clamp to the range [0,max].
Definition at line 697 of file ui.h.
 {
     return static_cast<T>( inc_clamp( static_cast<int>( val ), inc, static_cast<int>( size ) ) );
 }
References inc_clamp(), and om_direction::size.
inc_clamp() [2/5]
template<typename V , typename S > std::enable_if_t< !std::is_enum_v<V>, V > inc_clamp (V val, bool inc, S max) inline
Helper for typical arrow key UI list navigation without wrap-around Add 1/-1 to val, then clamp to the range [0,max].
Definition at line 661 of file ui.h.
 {
     // NOLINTNEXTLINE(cata-no-long)
     return inc_clamp( val, inc ? 1 : -1, static_cast<S>( 0 ), max );
 }
References inc_clamp(), and max().
inc_clamp() [3/5]
template<typename V , typename S > std::enable_if_t< !std::is_enum_v<V>, V > inc_clamp (V val, bool inc, S min, S max) inline
Helper for typical arrow key UI list navigation without wrap-around Add 1/-1 to val, then clamp to the range [min,max].
Definition at line 685 of file ui.h.
 {
     return inc_clamp( val, inc ? 1 : -1, min, max );
 }
References inc_clamp(), max(), and min().
inc_clamp() [4/5]
template<typename V , typename S > std::enable_if_t< !std::is_enum_v<V>, V > inc_clamp (V val, int delta, S max) inline
Helper for typical UI list navigation without wrap-around Add delta to val, then clamp to the range [0,max].
Definition at line 673 of file ui.h.
 {
     // NOLINTNEXTLINE(cata-no-long)
     return inc_clamp( val, delta, static_cast<S>( 0 ), max );
 }
References inc_clamp(), and max().
inc_clamp() [5/5]
template<typename V , typename S > std::enable_if_t< !std::is_enum_v<V>, V > inc_clamp (V val, int delta, S min, S max) inline
Helper for typical UI list navigation without wrap-around Add delta to val, then clamp to the range [min,max].
Definition at line 643 of file ui.h.
 {
     // Templating of existing `unsigned int` triggers linter rules against `unsigned long`
     if constexpr( std::is_unsigned_v<V> ) {
         // NOLINTNEXTLINE(cata-no-long)
         if( delta < 0 && val <= static_cast<V>( -delta ) ) {
             return min;
         }
     }
     return std::clamp<V>( val + delta, min, max );
 }
References max(), and min().
Referenced by inc_clamp(), navigate_ui_list(), and scrollable_text().
inc_clamp_wrap() [1/3]
template<typename T , typename I > std::enable_if_t<std::is_enum_v<T>, T> inc_clamp_wrap (T val, I inc, T size) inline
Helper for typical arrow key UI list navigation with wrap-around Specialized for enum values Add 1/-1 to val, then wrap to the range [0,size)
Definition at line 632 of file ui.h.
 {
     return static_cast<T>( inc_clamp_wrap( static_cast<int>( val ), inc, static_cast<int>( size ) ) );
 }
References inc_clamp_wrap(), and om_direction::size.
inc_clamp_wrap() [2/3]
template<typename V , typename S > std::enable_if_t< !std::is_enum_v<V>, V > inc_clamp_wrap (V val, bool inc, S size) inline
Helper for typical arrow key UI list navigation with wrap-around Add 1/-1 to val, then wrap to the range [0,size)
Definition at line 620 of file ui.h.
 {
     return inc_clamp_wrap( val, static_cast<int>( inc ? 1 : -1 ), size );
 }
References inc_clamp_wrap(), and om_direction::size.
inc_clamp_wrap() [3/3]
template<typename V , typename S > std::enable_if_t< !std::is_enum_v<V>, V > inc_clamp_wrap (V val, int delta, S size) inline
Helper for typical UI list navigation with wrap-around Add delta to val.
If on bounds, wrap to other bound, otherwise clamp to the range [0,size)
Definition at line 596 of file ui.h.
 {
     if( size == 0 ) {
         return 0;
     }
     // wrap to last
     if( val <= 0 && delta < 0 ) {
         return size - 1;
     }
     // wrap to first
     // Templating of existing `unsigned int` triggers linter rules against `unsigned long`
     // NOLINTNEXTLINE(cata-no-long)
     if( val >= static_cast<V>( size ) - 1 && delta > 0 ) {
         return 0;
     }
     return std::clamp<V>( val + delta, 0, size - 1 );
 }
References om_direction::size.
Referenced by smart_controller_ui::control(), faction_manager::display(), talk_function::display_and_choose_opts(), handle_player_display_action(), inc_clamp_wrap(), navigate_ui_list(), main_menu::opening_screen(), prof_window::run(), safemode::show(), diary::show_diary_ui(), color_manager::show_gui(), show_scores_ui(), worldfactory::show_worldgen_tab_modselection(), skip_skill_headers(), and outfit::sort_armor().
kill_advanced_inv()
void kill_advanced_inv ()
Definition at line 131 of file advanced_inv.cpp.
 {
     advinv.reset();
     cancel_aim_processing();
 }
References anonymous_namespace{advanced_inv.cpp}::advinv, and cancel_aim_processing().
Referenced by create_advanced_inv().
navigate_ui_list()
template<typename V , typename S > bool navigate_ui_list (const std::string & action, V & val, int page_delta, S size, bool wrap)
Helper for typical UI list navigation with wrap-around Handles up, down, scroll_up and _down, page_up and _down, home, and end Returns true if an action/input was handled.
Definition at line 1421 of file ui.cpp.
 {
     if( action == "UP" || action == "SCROLL_UP" || action == "DOWN" || action == "SCROLL_DOWN" ) {
         if( wrap ) {
             // NOLINTNEXTLINE(cata-no-long)
             val = inc_clamp_wrap( val, action == "DOWN" || action == "SCROLL_DOWN", static_cast<V>( size ) );
         } else {
             val = inc_clamp( val, action == "DOWN" || action == "SCROLL_DOWN",
                              // NOLINTNEXTLINE(cata-no-long)
                              static_cast<V>( size ? size - 1 : 0 ) );
         }
     } else if( ( action == "PAGE_UP" || action == "PAGE_DOWN" ) && page_delta ) {
         // page navigation never wraps
         val = inc_clamp( val, action == "PAGE_UP" ? -page_delta : page_delta,
                          // NOLINTNEXTLINE(cata-no-long)
                          static_cast<V>( size ? size - 1 : 0 ) );
     } else if( action == "HOME" ) {
         // NOLINTNEXTLINE(cata-no-long)
         val = static_cast<V>( 0 );
     } else if( action == "END" ) {
         // NOLINTNEXTLINE(cata-no-long)
         val = static_cast<V>( size ? size - 1 : 0 );
     } else {
         return false;
     }
     return true;
 }
References action, inc_clamp(), inc_clamp_wrap(), and om_direction::size.
Referenced by debug_menu::change_spells(), bodygraph_display::display(), faction_manager::display(), handle_player_display_action(), exosuit_interact::interact_loop(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_monsters(), worldfactory::pick_world(), prof_window::run(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_skills(), set_traits(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), safemode::show(), worldfactory::show_active_world_mods(), diary::show_diary_ui(), color_manager::show_gui(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), iexamine::vending(), basecamp::worker_assignment_ui(), and game::zones_manager().
new_centered_win()
catacurses::window new_centered_win (int nlines, int ncols)
Definition at line 32 of file ui.cpp.
 {
     int height = std::min( nlines, TERMY );
     int width = std::min( ncols, TERMX );
     point pos( ( TERMX - width ) / 2, ( TERMY - height ) / 2 );
     return catacurses::newwin( height, width, pos );
 }
References min(), catacurses::newwin(), math_opers::pos(), TERMX, and TERMY.
Referenced by show_scores_ui().
subindex_around_cursor()
std::pair<int, int> subindex_around_cursor (int num_entries, int available_space, int cursor_pos, bool focused = true)
Return indexes [start, end) that should be displayed from list long num_entries, given that cursor is at position cursor_pos and we have available_space spaces.
Parameters
focused if false, behave as if cursor_pos = 0, useful when other menu is displayed and this should show the beggining
Example: num_entries = 6, available_space = 3, cursor_pos = 2, focused = true; so choose 3 from indexes [0, 1, 2, 3, 4, 5] return {1, 4}
Definition at line 1449 of file ui.cpp.
 {
     if( !focused || num_entries <= available_space ) {
         return { 0, std::min( available_space, num_entries ) };
     }
     int slice_start = std::min( std::max( 0, cursor_pos - available_space / 2 ),
                                 num_entries - available_space );
     return {slice_start, slice_start + available_space };
 }
References max(), and min().
Referenced by draw_bionics_tab(), draw_effects_tab(), draw_proficiencies_tab(), draw_skills_tab(), draw_speed_tab(), draw_traits_tab(), and select_crafter_and_crafting_recipe().
temp_hide_advanced_inv()
void temp_hide_advanced_inv ()
Definition at line 137 of file advanced_inv.cpp.
 {
     if( advinv ) {
         advinv->temp_hide();
     }
 }
References anonymous_namespace{advanced_inv.cpp}::advinv.
Referenced by choose_direction(), and choose_direction_rel_ms().
Variable Documentation
MENU_AUTOASSIGN
const int MENU_AUTOASSIGN = -1
Definition at line 38 of file ui.h.
Referenced by anonymous_namespace{iexamine.cpp}::_choose_elevator_destz(), computer_session::action_list_mutations(), target_ui::action_switch_mode(), anonymous_namespace{monexamine.cpp}::add_leash(), Character::body_window(), iexamine::change_appearance(), change_armor_sprite(), debug_menu::change_weather(), debug_menu::character_edit_menu(), iexamine::compost_empty(), avatar::control_npc_menu(), creature_select_menu(), Character::customize_appearance(), debug_menu::debug_menu_force_temperature(), debug_menu::debug_menu_spawn_vehicle(), game::display_lighting(), game::display_visibility(), debug_menu::mission_debug::edit_npc(), debug_menu::mission_debug::edit_player(), haircut_activity_actor::finish(), iexamine::fvat_empty(), generic_barber(), liquid_handler::get_liquid_target(), talk_function::goto_location(), hotkey_from_char(), debug_menu::import_folower(), uilist::init(), anonymous_namespace{monexamine.cpp}::insert_battery(), exosuit_interact::insert_replace_activate_mod(), avatar::invoke_item(), basecamp::job_assignment_ui(), iexamine::keg(), main_menu::load_character_tab(), Character::mutation_selector(), main_menu::new_character_tab(), npc_select_menu(), npcs_select_menu(), pick_follower(), mutation_branch::pick_variant_menu(), pickveh(), game::point_selection_menu(), avatar::power_bionics(), iexamine::query_seed(), zone_manager::query_type(), iuse::radio_on(), iuse::robotcontrol(), debug_menu::select_faction(), debug_menu::select_follower_to_export(), debug_menu::spawn_artifact(), training_select_menu(), iexamine::tree_maple_tapped(), vehicle::turrets_set_mode(), vehicle::turrets_set_targeting(), computer_session::use(), inscribe_actor::use(), sew_advanced_actor::use(), debug_menu::wind_direction(), debug_menu::wind_speed(), and debug_menu::wishbionics().
UILIST_ADDITIONAL
const int UILIST_ADDITIONAL = -1029
Definition at line 37 of file ui.h.
Referenced by editmap::edit_feature(), editmap::edit_fld(), editmap::edit_mapgen(), editmap::mapgen_preview(), uilist::query(), editmap::select_shape(), and calendar_ui::select_time_point().
UILIST_CANCEL
const int UILIST_CANCEL = -1027
Definition at line 35 of file ui.h.
Referenced by anonymous_namespace{monexamine.cpp}::add_leash(), iexamine::attunement_altar(), game::disable_robot(), player_activity::do_turn(), editmap::edit_feature(), editmap::edit_fld(), editmap::edit_itm(), editmap::edit_mapgen(), handle_debug_mode(), anonymous_namespace{monexamine.cpp}::insert_battery(), basecamp::job_assignment_ui(), wish_item_callback::key(), editmap::mapgen_preview(), open_movement_mode_menu(), peek_related_recipe(), place_craft_or_disassembly(), uilist::query(), workout_activity_actor::query_keep_training(), try_sleep_activity_actor::query_keep_trying(), avatar::read(), ui::omap::select_city(), editmap::select_shape(), calendar_ui::select_time_point(), workout_activity_actor::start(), vehicle::use_washing_machine(), wait(), debug_menu::wisheffect(), debug_menu::wishproficiency(), debug_menu::wishskill(), and iexamine::workbench_internal().
UILIST_ERROR
const int UILIST_ERROR = -1024
uilist constants
Definition at line 32 of file ui.h.
Referenced by uilist::query().
UILIST_TIMEOUT
const int UILIST_TIMEOUT = -1028
Definition at line 36 of file ui.h.
Referenced by editmap::edit_feature(), editmap::edit_fld(), editmap::mapgen_preview(), and uilist::query().
UILIST_UNBOUND
const int UILIST_UNBOUND = -1026
Definition at line 34 of file ui.h.
Referenced by game::inventory_item_menu(), uilist::query(), string_input_popup::show_history(), and debug_menu::wishskill().
UILIST_WAIT_INPUT
const int UILIST_WAIT_INPUT = -1025
Definition at line 33 of file ui.h.
Referenced by uilist::init(), game::inventory_item_menu(), and uilist::query().