Cataclysm DDA: src/ui.cpp File Reference
ui.cpp File Reference
#include "ui.h"
#include <cctype>
#include <algorithm>
#include <climits>
#include <cstdlib>
#include <iterator>
#include <memory>
#include <set>
#include "avatar.h"
#include "cached_options.h"
#include "cata_assert.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "game.h"
#include "input.h"
#include "memory_fast.h"
#include "output.h"
#include "sdltiles.h"
#include "string_input_popup.h"
#include "translations.h"
#include "ui_manager.h"
Classes
struct pointmenu_cb::impl_t
Functions
catacurses::window new_centered_win (int nlines, int ncols)
static std::optional< input_event > hotkey_from_char (const int ch)
static int find_minimum_fold_width (const std::string &str, int max_lines, int min_width, int max_width)
Find the minimum width between max(min_width, 1) and max(max_width, min_width, 1) to fold the string to no more than max_lines, or no more than the minimum number of lines possible, assuming that foldstring(width).size() decreases monotonously with width.
template bool navigate_ui_list< int, int > (const std::string &action, int &val, int page_delta, int size, bool wrap)
template bool navigate_ui_list< int, size_t > (const std::string &action, int &val, int page_delta, size_t size, bool wrap)
template bool navigate_ui_list< size_t, size_t > (const std::string &action, size_t &val, int page_delta, size_t size, bool wrap)
template bool navigate_ui_list< unsigned int, unsigned int > (const std::string &action, unsigned int &val, int page_delta, unsigned int size, bool wrap)
template<typename V , typename S >
bool navigate_ui_list (const std::string &action, V &val, int page_delta, S size, bool wrap)
Helper for typical UI list navigation with wrap-around Handles up, down, scroll_up and _down, page_up and _down, home, and end Returns true if an action/input was handled.
std::pair< int, int > subindex_around_cursor (int num_entries, int available_space, int cursor_pos, bool focused)
Return indexes [start, end) that should be displayed from list long num_entries, given that cursor is at position cursor_pos and we have available_space spaces.
Function Documentation
navigate_ui_list()
template<typename V , typename S > bool navigate_ui_list (const std::string & action, V & val, int page_delta, S size, bool wrap)
Helper for typical UI list navigation with wrap-around Handles up, down, scroll_up and _down, page_up and _down, home, and end Returns true if an action/input was handled.
Definition at line 1421 of file ui.cpp.
 {
     if( action == "UP" || action == "SCROLL_UP" || action == "DOWN" || action == "SCROLL_DOWN" ) {
         if( wrap ) {
             // NOLINTNEXTLINE(cata-no-long)
             val = inc_clamp_wrap( val, action == "DOWN" || action == "SCROLL_DOWN", static_cast<V>( size ) );
         } else {
             val = inc_clamp( val, action == "DOWN" || action == "SCROLL_DOWN",
                              // NOLINTNEXTLINE(cata-no-long)
                              static_cast<V>( size ? size - 1 : 0 ) );
         }
     } else if( ( action == "PAGE_UP" || action == "PAGE_DOWN" ) && page_delta ) {
         // page navigation never wraps
         val = inc_clamp( val, action == "PAGE_UP" ? -page_delta : page_delta,
                          // NOLINTNEXTLINE(cata-no-long)
                          static_cast<V>( size ? size - 1 : 0 ) );
     } else if( action == "HOME" ) {
         // NOLINTNEXTLINE(cata-no-long)
         val = static_cast<V>( 0 );
     } else if( action == "END" ) {
         // NOLINTNEXTLINE(cata-no-long)
         val = static_cast<V>( size ? size - 1 : 0 );
     } else {
         return false;
     }
     return true;
 }
References action, inc_clamp(), inc_clamp_wrap(), and om_direction::size.
Referenced by debug_menu::change_spells(), bodygraph_display::display(), faction_manager::display(), handle_player_display_action(), exosuit_interact::interact_loop(), basecamp::job_assignment_ui(), ma_style_callback::key(), game::list_monsters(), worldfactory::pick_world(), prof_window::run(), set_hobbies(), set_points(), set_profession(), set_scenario(), set_skills(), set_traits(), auto_notes::auto_note_manager_gui::show(), auto_pickup::user_interface::show(), distraction_manager::distraction_manager_gui::show(), safemode::show(), worldfactory::show_active_world_mods(), diary::show_diary_ui(), color_manager::show_gui(), worldfactory::show_worldgen_basic(), worldfactory::show_worldgen_tab_modselection(), auto_pickup::rule::test_pattern(), safemode::test_pattern(), iexamine::vending(), basecamp::worker_assignment_ui(), and game::zones_manager().
navigate_ui_list< int, int >()
template bool navigate_ui_list< int, int > (const std::string & action, int & val, int page_delta, int size, bool wrap)
navigate_ui_list< int, size_t >()
template bool navigate_ui_list< int, size_t > (const std::string & action, int & val, int page_delta, size_t size, bool wrap)
navigate_ui_list< size_t, size_t >()
template bool navigate_ui_list< size_t, size_t > (const std::string & action, size_t & val, int page_delta, size_t size, bool wrap)
navigate_ui_list< unsigned int, unsigned int >()
template bool navigate_ui_list< unsigned int, unsigned int > (const std::string & action, unsigned int & val, int page_delta, unsigned int size, bool wrap)
new_centered_win()
catacurses::window new_centered_win (int nlines, int ncols)
Definition at line 32 of file ui.cpp.
 {
     int height = std::min( nlines, TERMY );
     int width = std::min( ncols, TERMX );
     point pos( ( TERMX - width ) / 2, ( TERMY - height ) / 2 );
     return catacurses::newwin( height, width, pos );
 }
References min(), catacurses::newwin(), math_opers::pos(), TERMX, and TERMY.
Referenced by show_scores_ui().
subindex_around_cursor()
std::pair<int, int> subindex_around_cursor (int num_entries, int available_space, int cursor_pos, bool focused = true)
Return indexes [start, end) that should be displayed from list long num_entries, given that cursor is at position cursor_pos and we have available_space spaces.
Parameters
focused if false, behave as if cursor_pos = 0, useful when other menu is displayed and this should show the beggining
Example: num_entries = 6, available_space = 3, cursor_pos = 2, focused = true; so choose 3 from indexes [0, 1, 2, 3, 4, 5] return {1, 4}
Definition at line 1449 of file ui.cpp.
 {
     if( !focused || num_entries <= available_space ) {
         return { 0, std::min( available_space, num_entries ) };
     }
     int slice_start = std::min( std::max( 0, cursor_pos - available_space / 2 ),
                                 num_entries - available_space );
     return {slice_start, slice_start + available_space };
 }
References max(), and min().
Referenced by draw_bionics_tab(), draw_effects_tab(), draw_proficiencies_tab(), draw_skills_tab(), draw_speed_tab(), draw_traits_tab(), and select_crafter_and_crafting_recipe().