Cataclysm DDA: src/units_utility.cpp File Reference
units_utility.cpp File Reference
#include "units_utility.h"
#include <string>
#include "cata_utility.h"
#include "options.h"
#include "string_formatter.h"
#include "translations.h"
Functions
units::angle normalize (units::angle a, units::angle mod)
Given an angle, add or subtract multiples of 360_degrees until it's in the range [0, 360_degrees).
units::angle angle_delta (units::angle a, units::angle b)
int angle_to_dir4 (const units::angle direction)
int angle_to_dir8 (const units::angle direction)
const char * weight_units ()
Create a units label for a weight value.
const char * volume_units_abbr ()
Create an abbreviated units label for a volume value.
const char * volume_units_long ()
Create a units label for a volume value.
double convert_velocity (int velocity, const units_type vel_units)
Convert internal velocity units to units defined by user.
double convert_weight (const units::mass &weight)
Convert weight in grams to units defined by user (kg or lbs)
double convert_length_cm_in (const units::length &length)
Convert length to inches or cm.
int convert_length (const units::length &length)
converts length to largest unit available 1000 mm = 1 meter for example assumed to be used in conjunction with unit string functions also works for imperial units
std::string length_units (const units::length &length)
std::string length_to_string (const units::length &length, const bool compact)
std::string weight_to_string (const units::mass &weight, const bool compact, const bool remove_trailing_zeroes)
convert a mass unit to a string readable by a human
std::pair< std::string, std::string > weight_to_string (const units::quantity< int, units::mass_in_microgram_tag > &weight)
Convert high-definition weight/mass to readable format Always metric units.
double convert_volume (int volume)
Convert volume from ml to units defined by user.
double convert_volume (int volume, int *out_scale)
Convert volume from ml to units defined by user, optionally returning the units preferred scale.
std::string vol_to_string (const units::volume &vol, const bool compact, const bool remove_trailing_zeroes)
convert a volume unit to a string readable by a human
std::string unit_to_string (const units::volume &unit, const bool compact, const bool remove_trailing_zeroes)
convert any type of unit to a string readable by a human
std::string unit_to_string (const units::mass &unit, const bool compact, const bool remove_trailing_zeroes)
std::string unit_to_string (const units::length &unit, const bool compact)
double round_with_places (double value, int decimal_places)
round a float @value, with int @decimal_places limitation
Function Documentation
angle_delta()
units::angle angle_delta (units::angle a, units::angle b)
Definition at line 19 of file units_utility.cpp.
 {
     const units::angle delta = normalize( a - b );
     return delta > 180_degrees ? 360_degrees - delta : delta;
 }
References a, b, and normalize().
angle_to_dir4()
int angle_to_dir4 (const units::angle direction)
Definition at line 25 of file units_utility.cpp.
 {
     const int dir8 = angle_to_dir8( direction );
     // direction is snapped to 8 directions in angle_to_dir8, then we need to further snap it
     // to just 4 directions, used for tilesets; for consistent visuals NE/NW diagonals snap to north
     // and SE/SW diagonals snap to south
     // NOLINTBEGIN(bugprone-branch-clone)
     switch( dir8 ) {
         // *INDENT-OFF*
         case 0:  return 0; // north
         case 1:  return 0; // north <- north west
         case 2:  return 1; // west
         case 3:  return 2; // south <- south west
         case 4:  return 2; // south
         case 5:  return 2; // south <- south east
         case 6:  return 3; // east
         case 7:  return 0; // north <- north east
         default: return 0;
         // *INDENT-ON*
     }
     // NOLINTEND(bugprone-branch-clone)
 }
References angle_to_dir8().
Referenced by mm_submap::deserialize().
angle_to_dir8()
int angle_to_dir8 (const units::angle direction)
Definition at line 49 of file units_utility.cpp.
 {
     // Direction is snapped to "notches" of 15-degrees on a circle, we bump direction towards the
     // middle of each notch, and lookup the 8-way direction. Cardinal directions get 5 "notches", diagonals
     // get 1 at the boundary of each 2 cardinals. This can be shorter but this way is easier to read,
     // the compilers will optimize into lookup table. This is mostly used in curses mode.
     constexpr units::angle bump = 15_degrees / 2.0;
     const int snap = normalize( direction - bump ) / 15_degrees + 1;
     // NOLINTBEGIN(bugprone-branch-clone)
     switch( snap ) {
         // *INDENT-OFF*
         case 22: return 0; // north
         case 23: return 0; // north
         case 24: return 0; // north      (   0 degrees )
         case 1:  return 0; // north
         case 2:  return 0; // north
         case 3:  return 1; // north-west (  45 degrees )
         case 4:  return 2; // west
         case 5:  return 2; // west
         case 6:  return 2; // west       (  90 degrees )
         case 7:  return 2; // west
         case 8:  return 2; // west
         case 9:  return 3; // south-west ( 135 degrees )
         case 10: return 4; // south
         case 11: return 4; // south
         case 12: return 4; // south      ( 180 degrees )
         case 13: return 4; // south
         case 14: return 4; // south
         case 15: return 5; // south-east ( 225 degrees )
         case 16: return 6; // east
         case 17: return 6; // east
         case 18: return 6; // east       ( 270 degrees )
         case 19: return 6; // east
         case 20: return 6; // east
         case 21: return 7; // north-east ( 315 degrees )
         default: return 0; // other values can't happen
         // *INDENT-ON*
     }
     // NOLINTEND(bugprone-branch-clone)
 }
References normalize().
Referenced by angle_to_dir4(), and vpart_variant::get_symbol().
convert_length()
int convert_length (const units::length & length)
converts length to largest unit available 1000 mm = 1 meter for example assumed to be used in conjunction with unit string functions also works for imperial units
Definition at line 169 of file units_utility.cpp.
 {
     int ret = to_millimeter( length );
     const bool metric = get_option<std::string>( "DISTANCE_UNITS" ) == "metric";
     if( metric ) {
         if( ret % 1'000'000 == 0 ) {
             // kilometers
             ret /= 1'000'000;
         } else if( ret % 1'000 == 0 ) {
             // meters
             ret /= 1'000;
         } else if( ret % 10 == 0 ) {
             // centimeters
             ret /= 10;
         }
     } else {
         // imperial's a doozy, we can only try to approximate
         // so first we convert it to inches which are the smallest unit
         ret /= 25.4;
         if( ret % 63360 == 0 ) {
             ret /= 63360;
         } else if( ret % 36 == 0 ) {
             ret /= 36;
         } else if( ret % 12 == 0 ) {
             ret /= 12;
         }
     }
     return ret;
 }
References length, cata::hash64_detail::ret, and units::to_millimeter().
Referenced by item::ammo_info(), item::basic_info(), item_pocket::general_info(), inventory_selector::get_weight_and_length_stat(), item::gun_info(), and length_to_string().
convert_length_cm_in()
double convert_length_cm_in (const units::length & length)
Convert length to inches or cm.
Used in pickup UI
Definition at line 154 of file units_utility.cpp.
 {
     double ret = to_millimeter( length );
     const bool metric = get_option<std::string>( "DISTANCE_UNITS" ) == "metric";
     if( metric ) {
         ret /= 10;
     } else {
         // imperial's a doozy, we can only try to approximate
         // so first we convert it to inches which are the smallest unit
         ret /= 25.4;
     }
     return ret;
 }
References length, cata::hash64_detail::ret, and units::to_millimeter().
convert_velocity()
double convert_velocity (int velocity, units_type vel_units)
Convert internal velocity units to units defined by user.
Parameters
velocity A velocity value in internal units.
vel_units General type of item this velocity is for (e.g. vehicles or wind)
Returns
Velocity in the user selected measurement system and in appropriate units for the object being measured.
Definition at line 120 of file units_utility.cpp.
 {
     const std::string type = get_option<std::string>( "USE_METRIC_SPEEDS" );
     // internal units to mph conversion
     double ret = static_cast<double>( velocity ) / 100;
     if( type == "km/h" ) {
         switch( vel_units ) {
             case VU_VEHICLE:
                 // mph to km/h conversion
                 ret *= 1.609f;
                 break;
             case VU_WIND:
                 // mph to m/s conversion
                 ret *= 0.447f;
                 break;
         }
     } else if( type == "t/t" ) {
         ret /= 4;
     }
     return ret;
 }
References cata::hash64_detail::ret, VU_VEHICLE, and VU_WIND.
Referenced by Character::activate_bionic(), veh_interact::display_stats(), vehicle::print_speed_gauge(), display::vehicle_cruise_text_color(), and iuse::weather_tool().
convert_volume() [1/2]
double convert_volume (int volume)
Convert volume from ml to units defined by user.
Definition at line 275 of file units_utility.cpp.
 {
     return convert_volume( volume, nullptr );
 }
Referenced by armor_inventory_preset::armor_inventory_preset(), comestible_inventory_preset::comestible_inventory_preset(), format_volume(), item_pocket::general_info(), outfit::sort_armor(), vol_to_info(), and vol_to_string().
convert_volume() [2/2]
double convert_volume (int volume, int * out_scale)
Convert volume from ml to units defined by user, optionally returning the units preferred scale.
Definition at line 280 of file units_utility.cpp.
 {
     double ret = volume;
     int scale = 0;
     const std::string vol_units = get_option<std::string>( "VOLUME_UNITS" );
     if( vol_units == "c" ) {
         ret *= 0.004;
         scale = 1;
     } else if( vol_units == "l" ) {
         ret *= 0.001;
         scale = 2;
     } else {
         ret *= 0.00105669;
         scale = 2;
     }
     if( out_scale != nullptr ) {
         *out_scale = scale;
     }
     return ret;
 }
References cata::hash64_detail::ret.
convert_weight()
double convert_weight (const units::mass & weight)
Convert weight in grams to units defined by user (kg or lbs)
Parameters
weight to be converted.
Returns
Weight converted to user selected unit
Definition at line 143 of file units_utility.cpp.
 {
     double ret = to_gram( weight );
     if( get_option<std::string>( "USE_METRIC_WEIGHTS" ) == "kg" ) {
         ret /= 1000;
     } else {
         ret /= 453.6;
     }
     return ret;
 }
References cata::hash64_detail::ret, and units::to_gram().
Referenced by assemble_stat_details(), veh_interact::display_details(), veh_interact::display_stats(), draw_stats_info(), vpart_info::format_description(), inventory_selector::get_weight_and_length_stat(), advanced_inventory::print_items(), item::qualities_info(), weigh_self_actor::use(), weight_to_info(), and weight_to_string().
length_to_string()
std::string length_to_string (const units::length & length, const bool compact)
Definition at line 241 of file units_utility.cpp.
 {
     const int converted_length = convert_length( length );
     std::string string_to_format = "%u%s%s";
     return string_format( string_to_format, converted_length, compact ? "" : " ",
                           length_units( length ) );
 }
References compact, convert_length(), length, length_units(), and string_format().
Referenced by unit_to_string().
length_units()
std::string length_units (const units::length & length)
Definition at line 199 of file units_utility.cpp.
 {
     int length_mm = to_millimeter( length );
     const bool metric = get_option<std::string>( "DISTANCE_UNITS" ) == "metric";
     if( metric ) {
         if( length_mm % 1'000'000 == 0 ) {
             //~ kilometers
             return _( "km" );
         } else if( length_mm % 1'000 == 0 ) {
             //~ meters
             return _( "m" );
         } else if( length_mm % 10 == 0 ) {
             //~ centimeters
             return _( "cm" );
         } else {
             //~ millimeters
             return _( "mm" );
         }
     } else {
         // imperial's a doozy, we can only try to approximate
         // so first we convert it to inches which are the smallest unit
         length_mm /= 25.4;
         if( length_mm == 0 ) {
             //~ inches
             return _( "in." );
         }
         if( length_mm % 63360 == 0 ) {
             //~ miles
             return _( "mi" );
         } else if( length_mm % 36 == 0 ) {
             //~ yards (length)
             return _( "yd" );
         } else if( length_mm % 12 == 0 ) {
             //~ feet (length)
             return _( "ft" );
         } else {
             //~ inches
             return _( "in." );
         }
     }
 }
References _, length, and units::to_millimeter().
Referenced by length_to_string().
normalize()
units::angle normalize (units::angle a, units::angle mod = 360_degrees)
Given an angle, add or subtract multiples of 360_degrees until it's in the range [0, 360_degrees).
With a second argument, can use a different maximum.
Definition at line 10 of file units_utility.cpp.
 {
     a = units::fmod( a, mod );
     if( a < 0_degrees ) {
         a += mod;
     }
     return a;
 }
References a, and units::fmod().
Referenced by angle_delta(), angle_to_dir8(), get_corrected_turn_dir(), game::grabbed_veh_move(), vehicle::immediate_path(), tileray::init(), vehicle::merge_rackable_vehicle(), offset_to_sun_altitude(), orient_part(), target_ui::recalc_aim_turning_penalty(), vehicle::remove_carried_vehicle(), sun_azimuth_altitude(), display::sundial_text_color(), and vehicle::turn().
round_with_places()
double round_with_places (double value, int decimal_places)
round a float @value, with int @decimal_places limitation
utility function to round with specified decimal places
Definition at line 332 of file units_utility.cpp.
 {
     const double multiplier = std::pow( 10.0, decimal_places );
     return std::round( value * multiplier ) / multiplier;
 }
References round().
Referenced by vol_to_string(), and weight_to_string().
unit_to_string() [1/3]
std::string unit_to_string (const units::length & unit, const bool compact)
Definition at line 324 of file units_utility.cpp.
 {
     return length_to_string( unit, compact );
 }
References compact, and length_to_string().
unit_to_string() [2/3]
std::string unit_to_string (const units::mass & unit, const bool compact, const bool remove_trailing_zeroes)
Definition at line 319 of file units_utility.cpp.
 {
     return weight_to_string( unit, compact, remove_trailing_zeroes );
 }
References compact, and weight_to_string().
unit_to_string() [3/3]
std::string unit_to_string (const units::volume & unit, const bool compact, const bool remove_trailing_zeroes)
convert any type of unit to a string readable by a human
Definition at line 314 of file units_utility.cpp.
 {
     return vol_to_string( unit, compact, remove_trailing_zeroes );
 }
References compact, and vol_to_string().
Referenced by container_data::to_formatted_string().
vol_to_string()
std::string vol_to_string (const units::volume & vol, const bool compact, const bool remove_trailing_zeroes)
convert a volume unit to a string readable by a human
Definition at line 301 of file units_utility.cpp.
 {
     int converted_volume_scale = 0;
     const int default_decimal_places = 3;
     const double converted_volume =
         round_with_places( convert_volume( vol.value(),
                                            &converted_volume_scale ), default_decimal_places );
     std::string string_to_format = remove_trailing_zeroes ? "%g%s%s" : "%." +
                                    std::to_string( default_decimal_places ) + "f%s%s";
     return string_format( string_to_format, converted_volume, compact ? "" : " ", volume_units_abbr() );
 }
References compact, convert_volume(), round_with_places(), string_format(), to_string(), units::quantity< V, U >::value(), and volume_units_abbr().
Referenced by debug_menu::character_edit_needs_menu(), iexamine::keg(), and unit_to_string().
volume_units_abbr()
const char* volume_units_abbr ()
Create an abbreviated units label for a volume value.
Returns the abbreviated name for the volume unit for the user selected unit system, i.e. "c", "L", or "qt". Used to add unit labels to the output of convert_volume.
Returns
name of unit.
Definition at line 96 of file units_utility.cpp.
 {
     const std::string vol_units = get_option<std::string>( "VOLUME_UNITS" );
     if( vol_units == "c" ) {
         return pgettext( "Volume unit", "c" );
     } else if( vol_units == "l" ) {
         return pgettext( "Volume unit", "L" );
     } else {
         return pgettext( "Volume unit", "qt" );
     }
 }
References pgettext.
Referenced by iexamine::arcfurnace_empty(), armor_inventory_preset::armor_inventory_preset(), comestible_inventory_preset::comestible_inventory_preset(), game_menus::inv::container_for(), veh_interact::display_details(), veh_interact::display_stats(), item_pocket::general_info(), inventory_selector::get_holster_stat(), inventory_selector::get_volume_stat(), iexamine::kiln_empty(), advanced_inventory::print_items(), vehicle::print_part_list(), iexamine::quern_examine(), game_menus::inv::smoke_food(), iexamine::smoker_options(), outfit::sort_armor(), vol_to_info(), and vol_to_string().
volume_units_long()
const char* volume_units_long ()
Create a units label for a volume value.
Returns the abbreviated name for the volume unit for the user selected unit system, ie "cup", "liter", or "quart". Used to add unit labels to the output of convert_volume.
Returns
name of unit.
Definition at line 108 of file units_utility.cpp.
 {
     const std::string vol_units = get_option<std::string>( "VOLUME_UNITS" );
     if( vol_units == "c" ) {
         return _( "cup" );
     } else if( vol_units == "l" ) {
         return _( "liter" );
     } else {
         return _( "quart" );
     }
 }
References _.
Referenced by talker_npc::give_item_to(), mill_activate(), smoker_activate(), and iexamine::smoker_options().
weight_to_string() [1/2]
std::string weight_to_string (const units::mass & weight, const bool compact, const bool remove_trailing_zeroes)
convert a mass unit to a string readable by a human
Definition at line 249 of file units_utility.cpp.
 {
     const int default_decimal_places = 2;
     const double converted_weight = round_with_places( convert_weight( weight ),
                                     default_decimal_places );
     std::string string_to_format = remove_trailing_zeroes ? "%g%s%s" : "%." +
                                    std::to_string( default_decimal_places ) + "f%s%s";
     return string_format( string_to_format, converted_weight, compact ? "" : " ", weight_units() );
 }
References compact, convert_weight(), round_with_places(), string_format(), to_string(), and weight_units().
Referenced by vitamin::mass_str_from_units(), and unit_to_string().
weight_to_string() [2/2]
std::pair<std::string, std::string> weight_to_string (const units::quantity< int, units::mass_in_microgram_tag > & weight)
Convert high-definition weight/mass to readable format Always metric units.
First is value as string, second is unit
Definition at line 260 of file units_utility.cpp.
 {
     using high_res_mass = units::quantity<int, units::mass_in_microgram_tag>;
     static const high_res_mass gram = high_res_mass( 1'000'000, {} );
     static const high_res_mass milligram = high_res_mass( 1'000, {} );
     if( weight > gram ) {
         return {string_format( "%.0f", weight.value() / 1'000'000.f ), "g"};
     } else if( weight > milligram ) {
         return {string_format( "%.0f", weight.value() / 1'000.f ), "mg"};
     }
     return {string_format( "%d", weight.value() ), "g"};
 }
References vitamin_units::gram, vitamin_units::milligram, string_format(), and units::quantity< V, U >::value().
weight_units()
const char* weight_units ()
Create a units label for a weight value.
Gives the name of the weight unit in the user selected unit system, either "kgs" or "lbs". Used to add unit labels to the output of convert_weight.
Returns
name of unit
Definition at line 91 of file units_utility.cpp.
 {
     return get_option<std::string>( "USE_METRIC_WEIGHTS" ) == "lbs" ? _( "lbs" ) : _( "kg" );
 }
References _.
Referenced by assemble_stat_details(), veh_interact::display_details(), veh_interact::display_stats(), draw_stats_info(), vpart_info::format_description(), inventory_selector::get_weight_and_length_stat(), advanced_inventory::print_items(), item::qualities_info(), weigh_self_actor::use(), weight_to_info(), and weight_to_string().