Cataclysm DDA: src/units.h File Reference
units.h File Reference
#include <cctype>
#include <algorithm>
#include <cmath>
#include <cstddef>
#include <limits>
#include <map>
#include <sstream>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>
#include "json.h"
#include "math_defines.h"
#include "translations.h"
#include "units_fwd.h"
Classes
class units::quantity< V, U >
Namespaces
units
detail
Macros
#define CATA_SRC_UNITS_H
Functions
template<typename V , typename U >
quantity< V, U > units::fabs (quantity< V, U > q)
template<typename V , typename U >
quantity< V, U > units::fmod (quantity< V, U > num, quantity< V, U > den)
template<typename value_type >
constexpr quantity< value_type, volume_in_milliliter_tag > units::from_milliliter (const value_type v)
template<typename value_type >
constexpr quantity< value_type, volume_in_milliliter_tag > units::from_liter (const value_type v)
template<typename value_type >
constexpr value_type units::to_milliliter (const quantity< value_type, volume_in_milliliter_tag > &v)
constexpr double units::to_liter (const volume &v)
template<typename value_type >
constexpr quantity< value_type, mass_in_milligram_tag > units::from_milligram (const value_type v)
template<typename value_type >
constexpr quantity< value_type, mass_in_milligram_tag > units::from_gram (const value_type v)
template<typename value_type >
constexpr quantity< value_type, mass_in_milligram_tag > units::from_kilogram (const value_type v)
template<typename value_type >
constexpr value_type units::to_milligram (const quantity< value_type, mass_in_milligram_tag > &v)
template<typename value_type >
constexpr value_type units::to_gram (const quantity< value_type, mass_in_milligram_tag > &v)
constexpr double units::to_kilogram (const mass &v)
template<typename value_type >
constexpr quantity< value_type, specific_energy_in_joule_per_gram_tag > units::from_joule_per_gram (const value_type v)
template<typename value_type >
constexpr value_type units::to_joule_per_gram (const quantity< value_type, specific_energy_in_joule_per_gram_tag > &v)
template<typename value_type >
constexpr quantity< units::temperature::value_type, temperature_in_kelvin_tag > units::from_kelvin (const value_type v)
template<typename value_type >
constexpr value_type units::to_kelvin (const quantity< value_type, temperature_in_kelvin_tag > &v)
template<typename value_type >
constexpr quantity< units::temperature::value_type, temperature_in_kelvin_tag > units::from_celsius (const value_type v)
template<typename value_type >
constexpr quantity< units::temperature::value_type, temperature_in_kelvin_tag > units::from_fahrenheit (const value_type v)
template<typename value_type >
constexpr value_type units::to_celsius (const quantity< value_type, temperature_in_kelvin_tag > &v)
template<typename value_type >
constexpr value_type units::to_fahrenheit (const quantity< value_type, temperature_in_kelvin_tag > &v)
constexpr units::temperature units::from_legacy_bodypart_temp (int temp)
template<typename value_type >
constexpr int units::to_legacy_bodypart_temp (const quantity< value_type, temperature_in_kelvin_tag > &v)
template<typename value_type >
constexpr quantity< units::temperature_delta::value_type, temperature_delta_in_kelvin_tag > units::from_kelvin_delta (const value_type v)
template<typename value_type >
constexpr value_type units::to_kelvin_delta (const quantity< value_type, temperature_delta_in_kelvin_tag > &v)
template<typename value_type >
constexpr quantity< units::temperature_delta::value_type, temperature_delta_in_kelvin_tag > units::from_celsius_delta (const value_type v)
template<typename value_type >
constexpr quantity< units::temperature_delta::value_type, temperature_delta_in_kelvin_tag > units::from_fahrenheit_delta (const value_type v)
template<typename value_type >
constexpr value_type units::to_celsius_delta (const quantity< value_type, temperature_delta_in_kelvin_tag > &v)
template<typename value_type >
constexpr value_type units::to_fahrenheit_delta (const quantity< value_type, temperature_delta_in_kelvin_tag > &v)
constexpr units::temperature_delta units::from_legacy_bodypart_temp_delta (int temp)
template<typename value_type >
constexpr int units::to_legacy_bodypart_temp_delta (const quantity< value_type, temperature_delta_in_kelvin_tag > &v)
template<typename value_type >
constexpr quantity< value_type, energy_in_millijoule_tag > units::from_millijoule (const value_type v)
template<typename value_type >
constexpr quantity< value_type, energy_in_millijoule_tag > units::from_joule (const value_type v)
template<typename value_type >
constexpr quantity< value_type, energy_in_millijoule_tag > units::from_kilojoule (const value_type v)
template<typename value_type >
constexpr value_type units::to_millijoule (const quantity< value_type, energy_in_millijoule_tag > &v)
template<typename value_type >
constexpr value_type units::to_joule (const quantity< value_type, energy_in_millijoule_tag > &v)
template<typename value_type >
constexpr value_type units::to_kilojoule (const quantity< value_type, energy_in_millijoule_tag > &v)
template<typename value_type >
constexpr quantity< value_type, power_in_milliwatt_tag > units::from_milliwatt (const value_type v)
template<typename value_type >
constexpr quantity< value_type, power_in_milliwatt_tag > units::from_watt (const value_type v)
template<typename value_type >
constexpr quantity< value_type, power_in_milliwatt_tag > units::from_kilowatt (const value_type v)
template<typename value_type >
constexpr value_type units::to_milliwatt (const quantity< value_type, power_in_milliwatt_tag > &v)
template<typename value_type >
constexpr value_type units::to_watt (const quantity< value_type, power_in_milliwatt_tag > &v)
template<typename value_type >
constexpr value_type units::to_kilowatt (const quantity< value_type, power_in_milliwatt_tag > &v)
template<typename value_type >
constexpr quantity< value_type, money_in_cent_tag > units::from_cent (const value_type v)
template<typename value_type >
constexpr quantity< value_type, money_in_cent_tag > units::from_usd (const value_type v)
template<typename value_type >
constexpr quantity< value_type, money_in_cent_tag > units::from_kusd (const value_type v)
template<typename value_type >
constexpr value_type units::to_cent (const quantity< value_type, money_in_cent_tag > &v)
template<typename value_type >
constexpr value_type units::to_usd (const quantity< value_type, money_in_cent_tag > &v)
template<typename value_type >
constexpr value_type units::to_kusd (const quantity< value_type, money_in_cent_tag > &v)
template<typename value_type >
constexpr quantity< value_type, length_in_millimeter_tag > units::from_millimeter (const value_type v)
template<typename value_type >
constexpr quantity< value_type, length_in_millimeter_tag > units::from_centimeter (const value_type v)
template<typename value_type >
constexpr quantity< value_type, length_in_millimeter_tag > units::from_meter (const value_type v)
template<typename value_type >
constexpr quantity< value_type, length_in_millimeter_tag > units::from_kilometer (const value_type v)
template<typename value_type >
constexpr value_type units::to_millimeter (const quantity< value_type, length_in_millimeter_tag > &v)
template<typename value_type >
constexpr value_type units::to_centimeter (const quantity< value_type, length_in_millimeter_tag > &v)
template<typename value_type >
constexpr value_type units::to_meter (const quantity< value_type, length_in_millimeter_tag > &v)
template<typename value_type >
constexpr value_type units::to_kilometer (const quantity< value_type, length_in_millimeter_tag > &v)
template<typename value_type >
constexpr quantity< value_type, angle_in_radians_tag > units::from_radians (const value_type v)
constexpr double units::to_radians (const units::angle v)
template<typename value_type >
constexpr quantity< double, angle_in_radians_tag > units::from_degrees (const value_type v)
constexpr double units::to_degrees (const units::angle v)
template<typename value_type >
constexpr quantity< double, angle_in_radians_tag > units::from_arcmin (const value_type v)
constexpr double units::to_arcmin (const units::angle v)
template<typename value_type >
constexpr quantity< value_type, length_in_millimeter_tag > units::default_length_from_volume (const quantity< value_type, volume_in_milliliter_tag > &v)
std::ostream & units::operator<< (std::ostream &o, mass_in_milligram_tag)
std::ostream & units::operator<< (std::ostream &o, volume_in_milliliter_tag)
std::ostream & units::operator<< (std::ostream &o, energy_in_millijoule_tag)
std::ostream & units::operator<< (std::ostream &o, power_in_milliwatt_tag)
std::ostream & units::operator<< (std::ostream &o, money_in_cent_tag)
std::ostream & units::operator<< (std::ostream &o, length_in_millimeter_tag)
std::ostream & units::operator<< (std::ostream &o, angle_in_radians_tag)
std::ostream & units::operator<< (std::ostream &o, temperature)
template<typename value_type , typename tag_type >
std::ostream & units::operator<< (std::ostream &o, const quantity< value_type, tag_type > &v)
template<typename value_type , typename tag_type >
std::string units::quantity_to_string (const quantity< value_type, tag_type > &v)
std::string units::display (const units::energy &v)
std::string units::display (const units::power v)
constexpr units::volume operator""_ml (const unsigned long long v)
constexpr units::quantity< double, units::volume_in_milliliter_tag > operator""_ml (const long double v)
constexpr units::volume operator""_liter (const unsigned long long v)
constexpr units::quantity< double, units::volume_in_milliliter_tag > operator""_liter (const long double v)
constexpr units::mass operator""_milligram (const unsigned long long v)
constexpr units::mass operator""_gram (const unsigned long long v)
constexpr units::mass operator""_kilogram (const unsigned long long v)
constexpr units::quantity< double, units::mass_in_milligram_tag > operator""_milligram (const long double v)
constexpr units::quantity< double, units::mass_in_milligram_tag > operator""_gram (const long double v)
constexpr units::quantity< double, units::mass_in_milligram_tag > operator""_kilogram (const long double v)
constexpr units::temperature operator""_K (const unsigned long long v)
constexpr units::temperature operator""_C (const unsigned long long v)
constexpr units::temperature_delta operator""_C_delta (const unsigned long long v)
constexpr units::quantity< double, units::temperature_in_kelvin_tag > operator""_K (const long double v)
constexpr units::temperature operator""_C (const long double v)
constexpr units::temperature_delta operator""_C_delta (const long double v)
constexpr units::energy operator""_mJ (const unsigned long long v)
constexpr units::quantity< double, units::energy_in_millijoule_tag > operator""_mJ (const long double v)
constexpr units::energy operator""_J (const unsigned long long v)
constexpr units::quantity< double, units::energy_in_millijoule_tag > operator""_J (const long double v)
constexpr units::energy operator""_kJ (const unsigned long long v)
constexpr units::quantity< double, units::energy_in_millijoule_tag > operator""_kJ (const long double v)
constexpr units::power operator""_mW (const unsigned long long v)
constexpr units::power operator""_W (const unsigned long long v)
constexpr units::power operator""_kW (const unsigned long long v)
constexpr units::money operator""_cent (const unsigned long long v)
constexpr units::quantity< double, units::money_in_cent_tag > operator""_cent (const long double v)
constexpr units::money operator""_USD (const unsigned long long v)
constexpr units::quantity< double, units::money_in_cent_tag > operator""_USD (const long double v)
constexpr units::money operator""_kUSD (const unsigned long long v)
constexpr units::quantity< double, units::money_in_cent_tag > operator""_kUSD (const long double v)
constexpr units::quantity< double, units::length_in_millimeter_tag > operator""_mm (const long double v)
constexpr units::length operator""_mm (const unsigned long long v)
constexpr units::quantity< double, units::length_in_millimeter_tag > operator""_cm (const long double v)
constexpr units::length operator""_cm (const unsigned long long v)
constexpr units::quantity< double, units::length_in_millimeter_tag > operator""_meter (const long double v)
constexpr units::length operator""_meter (const unsigned long long v)
constexpr units::quantity< double, units::length_in_millimeter_tag > operator""_km (const long double v)
constexpr units::length operator""_km (const unsigned long long v)
constexpr units::angle operator""_radians (const long double v)
constexpr units::angle operator""_radians (const unsigned long long v)
constexpr units::angle operator""_pi_radians (const long double v)
constexpr units::angle operator""_pi_radians (const unsigned long long v)
constexpr units::angle operator""_degrees (const long double v)
constexpr units::angle operator""_degrees (const unsigned long long v)
constexpr units::angle operator""_arcmin (const long double v)
constexpr units::angle operator""_arcmin (const unsigned long long v)
double units::sin (angle a)
double units::cos (angle a)
double units::tan (angle a)
double units::cot (angle a)
units::angle units::atan2 (double y, double x)
units::angle units::asin (double x)
units::angle units::acos (double x)
units::energy units::operator* (const units::power &power, const time_duration &time)
units::energy units::operator* (const time_duration &time, const units::power &power)
units::power units::operator/ (const units::energy &energy, const time_duration &time)
time_duration units::operator/ (const units::energy &energy, const units::power &power)
constexpr units::temperature_delta units::abs (units::temperature_delta x)
units::temperature_delta units::operator- (const units::temperature &T1, const units::temperature &T2)
units::temperature units::operator+ (const units::temperature &T, const units::temperature_delta &T_delta)
units::temperature units::operator- (const units::temperature &T, const units::temperature_delta &T_delta)
units::temperature units::operator+ (const units::temperature_delta &T_delta, const units::temperature &T)
units::temperature units::operator+ (const units::temperature &, const units::temperature &)=delete
units::temperature & units::operator+= (units::temperature &T, const units::temperature_delta &T_delta)
template<typename T , typename Error >
T detail::read_from_json_string_common (const std::string_view s, const std::vector< std::pair< std::string, T >> &units, Error &&error)
template<typename T >
T read_from_json_string (const JsonValue &jv, const std::vector< std::pair< std::string, T >> &units)
template<typename T >
void dump_to_json_string (T t, JsonOut &jsout, const std::vector< std::pair< std::string, T >> &units)
template<typename lvt , typename ut , typename st , typename = std::enable_if_t<std::is_arithmetic_v<st>>>
constexpr quantity< decltype(std::declval< lvt >) *std::declval< st >)), ut > units::operator* (const st &factor, const quantity< lvt, ut > &rhs)
Multiplication and division with scalars.
template<typename lvt , typename ut , typename st , typename = std::enable_if_t<std::is_arithmetic_v<st>>>
constexpr quantity< decltype(std::declval< st >) *std::declval< lvt >)), ut > units::operator* (const quantity< lvt, ut > &lhs, const st &factor)
template<typename lvt , typename ut , typename rvt , typename = std::enable_if_t<std::is_arithmetic_v<lvt>>>
void units::operator* (quantity< lvt, ut >, quantity< rvt, ut >)=delete
template<typename lvt , typename ut , typename st , typename = std::enable_if_t<std::is_arithmetic_v<st>>>
quantity< lvt, ut > & units::operator*= (quantity< lvt, ut > &lhs, const st &factor)
template<typename lvt , typename ut , typename rvt , typename = std::enable_if_t<std::is_arithmetic_v<rvt>>>
constexpr quantity< decltype(std::declval< lvt >) *std::declval< rvt >)), ut > units::operator/ (const quantity< lvt, ut > &lhs, const rvt &divisor)
template<typename lvt , typename ut , typename rvt , typename = std::enable_if_t<std::is_arithmetic_v<lvt>>>
void units::operator/ (lvt, quantity< rvt, ut >)=delete
template<typename lvt , typename ut , typename rvt >
constexpr decltype(std::declval< lvt >()/std::declval< rvt >()) units::operator/ (const quantity< lvt, ut > &lhs, const quantity< rvt, ut > &rhs)
template<typename lvt , typename ut , typename st , typename = std::enable_if_t<std::is_arithmetic_v<st>>>
quantity< lvt, ut > & units::operator/= (quantity< lvt, ut > &lhs, const st &divisor)
template<typename lvt , typename ut , typename rvt , typename = std::enable_if_t<std::is_arithmetic_v<rvt>>>
constexpr quantity< decltype(std::declval< lvt >) % std::declval< rvt >)), ut > units::operator% (const quantity< lvt, ut > &lhs, const rvt &divisor)
template<typename lvt , typename ut , typename rvt , typename = std::enable_if_t<std::is_arithmetic_v<lvt>>>
void units::operator% (lvt, quantity< rvt, ut >)=delete
template<typename lvt , typename ut , typename rvt >
constexpr quantity< decltype(std::declval< lvt >) % std::declval< rvt >)), ut > units::operator% (const quantity< lvt, ut > &lhs, const quantity< rvt, ut > &rhs)
template<typename lvt , typename ut , typename st , typename = std::enable_if_t<std::is_arithmetic_v<st>>>
quantity< lvt, ut > & units::operator%= (quantity< lvt, ut > &lhs, const st &divisor)
template<typename lvt , typename ut , typename rvt >
quantity< lvt, ut > & units::operator%= (quantity< lvt, ut > &lhs, const quantity< rvt, ut > &rhs)
Variables
const volume units::volume_min
const volume units::volume_max
constexpr volume units::legacy_volume_factor = from_milliliter(250)
const mass units::mass_min
const mass units::mass_max
const specific_energy units::specific_energy_min
const specific_energy units::specific_energy_max
const temperature units::temperature_min = units::temperature(0, units::temperature::unit_type{})
const temperature units::temperature_max
const temperature_delta units::temperature_delta_min
const temperature_delta units::temperature_delta_max
const energy units::energy_min
const energy units::energy_max
const power units::power_min
const power units::power_max
const money units::money_min
const money units::money_max
const length units::length_min
const length units::length_max
const std::vector< std::pair< std::string, energy > > units::energy_units
const std::vector< std::pair< std::string, power > > units::power_units
const std::vector< std::pair< std::string, mass > > units::mass_units
const std::vector< std::pair< std::string, money > > units::money_units
const std::vector< std::pair< std::string, volume > > units::volume_units
const std::vector< std::pair< std::string, length > > units::length_units
const std::vector< std::pair< std::string, angle > > units::angle_units
const std::vector< std::pair< std::string, temperature > > units::temperature_units
Macro Definition Documentation
CATA_SRC_UNITS_H
#define CATA_SRC_UNITS_H
Definition at line 3 of file units.h.
Function Documentation
dump_to_json_string()
template<typename T > void dump_to_json_string (T t, JsonOut & jsout, const std::vector< std::pair< std::string, T >> & units)
Definition at line 1283 of file units.h.
 {
     // deduplicate unit strings and choose the shortest representations
     std::map<T, std::string> sorted_units;
     for( const std::pair<std::string, T> &p : units ) {
         const auto it = sorted_units.find( p.second );
         if( it != sorted_units.end() ) {
             if( p.first.length() < it->second.length() ) {
                 it->second = p.first;
             }
         } else {
             sorted_units.emplace( p.second, p.first );
         }
     }
     std::string str;
     bool written = false;
     for( auto it = sorted_units.rbegin(); it != sorted_units.rend(); ++it ) {
         const int val = static_cast<int>( t / it->first );
         if( val != 0 ) {
             if( written ) {
                 str += ' ';
             }
             int tmp = val;
             if( tmp < 0 ) {
                 str += '-';
                 tmp = -tmp;
             }
             const size_t val_beg = str.size();
             while( tmp != 0 ) {
                 str += static_cast<char>( '0' + tmp % 10 );
                 tmp /= 10;
             }
             std::reverse( str.begin() + val_beg, str.end() );
             str += ' ';
             str += it->second;
             written = true;
             t -= it->first * val;
         }
     }
     if( str.empty() ) {
         str = "0 " + sorted_units.begin()->second;
     }
     jsout.write( str );
 }
References JsonOut::write().
Referenced by recipe::check_blueprint_requirements().
operator""_arcmin() [1/2]
constexpr units::angle operator""_arcmin (const long double v) inline constexpr
Definition at line 1089 of file units.h.
 {
     return units::from_arcmin( v );
 }
References units::from_arcmin().
operator""_arcmin() [2/2]
constexpr units::angle operator""_arcmin (const unsigned long long v) inline constexpr
Definition at line 1094 of file units.h.
 {
     return units::from_arcmin( v );
 }
References units::from_arcmin().
operator""_C() [1/2]
constexpr units::temperature operator""_C (const long double v) inline constexpr
Definition at line 924 of file units.h.
 {
     return units::from_celsius( v );
 }
References units::from_celsius().
operator""_C() [2/2]
constexpr units::temperature operator""_C (const unsigned long long v) inline constexpr
Definition at line 908 of file units.h.
 {
     return units::from_celsius( v );
 }
References units::from_celsius().
operator""_C_delta() [1/2]
constexpr units::temperature_delta operator""_C_delta (const long double v) inline constexpr
Definition at line 929 of file units.h.
 {
     return units::from_celsius_delta( v );
 }
References units::from_celsius_delta().
operator""_C_delta() [2/2]
constexpr units::temperature_delta operator""_C_delta (const unsigned long long v) inline constexpr
Definition at line 913 of file units.h.
 {
     return units::from_celsius_delta( v );
 }
References units::from_celsius_delta().
operator""_cent() [1/2]
constexpr units::quantity<double, units::money_in_cent_tag> operator""_cent (const long double v) inline constexpr
Definition at line 987 of file units.h.
 {
     return units::from_cent( v );
 }
References units::from_cent().
operator""_cent() [2/2]
constexpr units::money operator""_cent (const unsigned long long v) inline constexpr
Definition at line 982 of file units.h.
 {
     return units::from_cent( v );
 }
References units::from_cent().
operator""_cm() [1/2]
constexpr units::quantity<double, units::length_in_millimeter_tag> operator""_cm (const long double v) inline constexpr
Definition at line 1026 of file units.h.
 {
     return units::from_centimeter( v );
 }
References units::from_centimeter().
operator""_cm() [2/2]
constexpr units::length operator""_cm (const unsigned long long v) inline constexpr
Definition at line 1032 of file units.h.
 {
     return units::from_centimeter( v );
 }
References units::from_centimeter().
operator""_degrees() [1/2]
constexpr units::angle operator""_degrees (const long double v) inline constexpr
Definition at line 1079 of file units.h.
 {
     return units::from_degrees( v );
 }
References units::from_degrees().
operator""_degrees() [2/2]
constexpr units::angle operator""_degrees (const unsigned long long v) inline constexpr
Definition at line 1084 of file units.h.
 {
     return units::from_degrees( v );
 }
References units::from_degrees().
operator""_gram() [1/2]
constexpr units::quantity<double, units::mass_in_milligram_tag> operator""_gram (const long double v) inline constexpr
Definition at line 891 of file units.h.
 {
     return units::from_gram( v );
 }
References units::from_gram().
operator""_gram() [2/2]
constexpr units::mass operator""_gram (const unsigned long long v) inline constexpr
Definition at line 875 of file units.h.
 {
     return units::from_gram( v );
 }
References units::from_gram().
operator""_J() [1/2]
constexpr units::quantity<double, units::energy_in_millijoule_tag> operator""_J (const long double v) inline constexpr
Definition at line 950 of file units.h.
 {
     return units::from_joule( v );
 }
References units::from_joule().
operator""_J() [2/2]
constexpr units::energy operator""_J (const unsigned long long v) inline constexpr
Definition at line 945 of file units.h.
 {
     return units::from_joule( v );
 }
References units::from_joule().
operator""_K() [1/2]
constexpr units::quantity<double, units::temperature_in_kelvin_tag> operator""_K (const long double v) inline constexpr
Definition at line 918 of file units.h.
 {
     return units::from_kelvin( v );
 }
References units::from_kelvin().
operator""_K() [2/2]
constexpr units::temperature operator""_K (const unsigned long long v) inline constexpr
Definition at line 903 of file units.h.
 {
     return units::from_kelvin( v );
 }
References units::from_kelvin().
operator""_kilogram() [1/2]
constexpr units::quantity<double, units::mass_in_milligram_tag> operator""_kilogram (const long double v) inline constexpr
Definition at line 897 of file units.h.
 {
     return units::from_kilogram( v );
 }
References units::from_kilogram().
operator""_kilogram() [2/2]
constexpr units::mass operator""_kilogram (const unsigned long long v) inline constexpr
Definition at line 880 of file units.h.
 {
     return units::from_kilogram( v );
 }
References units::from_kilogram().
operator""_kJ() [1/2]
constexpr units::quantity<double, units::energy_in_millijoule_tag> operator""_kJ (const long double v) inline constexpr
Definition at line 961 of file units.h.
 {
     return units::from_kilojoule( v );
 }
References units::from_kilojoule().
operator""_kJ() [2/2]
constexpr units::energy operator""_kJ (const unsigned long long v) inline constexpr
Definition at line 956 of file units.h.
 {
     return units::from_kilojoule( v );
 }
References units::from_kilojoule().
operator""_km() [1/2]
constexpr units::quantity<double, units::length_in_millimeter_tag> operator""_km (const long double v) inline constexpr
Definition at line 1048 of file units.h.
 {
     return units::from_kilometer( v );
 }
References units::from_kilometer().
operator""_km() [2/2]
constexpr units::length operator""_km (const unsigned long long v) inline constexpr
Definition at line 1054 of file units.h.
 {
     return units::from_kilometer( v );
 }
References units::from_kilometer().
operator""_kUSD() [1/2]
constexpr units::quantity<double, units::money_in_cent_tag> operator""_kUSD (const long double v) inline constexpr
Definition at line 1009 of file units.h.
 {
     return units::from_kusd( v );
 }
References units::from_kusd().
operator""_kUSD() [2/2]
constexpr units::money operator""_kUSD (const unsigned long long v) inline constexpr
Definition at line 1004 of file units.h.
 {
     return units::from_kusd( v );
 }
References units::from_kusd().
operator""_kW()
constexpr units::power operator""_kW (const unsigned long long v) inline constexpr
Definition at line 977 of file units.h.
 {
     return units::from_kilowatt( v );
 }
References units::from_kilowatt().
operator""_liter() [1/2]
constexpr units::quantity<double, units::volume_in_milliliter_tag> operator""_liter (const long double v) inline constexpr
Definition at line 864 of file units.h.
 {
     return units::from_milliliter( v * 1000 );
 }
References units::from_milliliter().
operator""_liter() [2/2]
constexpr units::volume operator""_liter (const unsigned long long v) inline constexpr
Definition at line 859 of file units.h.
 {
     return units::from_milliliter( v * 1000 );
 }
References units::from_milliliter().
operator""_meter() [1/2]
constexpr units::quantity<double, units::length_in_millimeter_tag> operator""_meter (const long double v) inline constexpr
Definition at line 1037 of file units.h.
 {
     return units::from_meter( v );
 }
References units::from_meter().
operator""_meter() [2/2]
constexpr units::length operator""_meter (const unsigned long long v) inline constexpr
Definition at line 1043 of file units.h.
 {
     return units::from_meter( v );
 }
References units::from_meter().
operator""_milligram() [1/2]
constexpr units::quantity<double, units::mass_in_milligram_tag> operator""_milligram (const long double v) inline constexpr
Definition at line 885 of file units.h.
 {
     return units::from_milligram( v );
 }
References units::from_milligram().
operator""_milligram() [2/2]
constexpr units::mass operator""_milligram (const unsigned long long v) inline constexpr
Definition at line 871 of file units.h.
 {
     return units::from_milligram( v );
 }
References units::from_milligram().
operator""_mJ() [1/2]
constexpr units::quantity<double, units::energy_in_millijoule_tag> operator""_mJ (const long double v) inline constexpr
Definition at line 939 of file units.h.
 {
     return units::from_millijoule( v );
 }
References units::from_millijoule().
operator""_mJ() [2/2]
constexpr units::energy operator""_mJ (const unsigned long long v) inline constexpr
Definition at line 934 of file units.h.
 {
     return units::from_millijoule( v );
 }
References units::from_millijoule().
operator""_ml() [1/2]
constexpr units::quantity<double, units::volume_in_milliliter_tag> operator""_ml (const long double v) inline constexpr
Definition at line 852 of file units.h.
 {
     return units::from_milliliter( v );
 }
References units::from_milliliter().
operator""_ml() [2/2]
constexpr units::volume operator""_ml (const unsigned long long v) inline constexpr
Definition at line 847 of file units.h.
 {
     return units::from_milliliter( v );
 }
References units::from_milliliter().
operator""_mm() [1/2]
constexpr units::quantity<double, units::length_in_millimeter_tag> operator""_mm (const long double v) inline constexpr
Definition at line 1015 of file units.h.
 {
     return units::from_millimeter( v );
 }
References units::from_millimeter().
operator""_mm() [2/2]
constexpr units::length operator""_mm (const unsigned long long v) inline constexpr
Definition at line 1021 of file units.h.
 {
     return units::from_millimeter( v );
 }
References units::from_millimeter().
operator""_mW()
constexpr units::power operator""_mW (const unsigned long long v) inline constexpr
Definition at line 967 of file units.h.
 {
     return units::from_milliwatt( v );
 }
References units::from_milliwatt().
operator""_pi_radians() [1/2]
constexpr units::angle operator""_pi_radians (const long double v) inline constexpr
Definition at line 1069 of file units.h.
 {
     return units::from_radians( v * M_PI );
 }
References units::from_radians(), and M_PI.
operator""_pi_radians() [2/2]
constexpr units::angle operator""_pi_radians (const unsigned long long v) inline constexpr
Definition at line 1074 of file units.h.
 {
     return units::from_radians( v * M_PI );
 }
References units::from_radians(), and M_PI.
operator""_radians() [1/2]
constexpr units::angle operator""_radians (const long double v) inline constexpr
Definition at line 1059 of file units.h.
 {
     return units::from_radians( v );
 }
References units::from_radians().
operator""_radians() [2/2]
constexpr units::angle operator""_radians (const unsigned long long v) inline constexpr
Definition at line 1064 of file units.h.
 {
     return units::from_radians( v );
 }
References units::from_radians().
operator""_USD() [1/2]
constexpr units::quantity<double, units::money_in_cent_tag> operator""_USD (const long double v) inline constexpr
Definition at line 998 of file units.h.
 {
     return units::from_usd( v );
 }
References units::from_usd().
operator""_USD() [2/2]
constexpr units::money operator""_USD (const unsigned long long v) inline constexpr
Definition at line 993 of file units.h.
 {
     return units::from_usd( v );
 }
References units::from_usd().
operator""_W()
constexpr units::power operator""_W (const unsigned long long v) inline constexpr
Definition at line 972 of file units.h.
 {
     return units::from_watt( v );
 }
References units::from_watt().
read_from_json_string()
template<typename T > T read_from_json_string (const JsonValue & jv, const std::vector< std::pair< std::string, T >> & units)
Definition at line 1271 of file units.h.
 {
     const auto error = [&]( const char *const msg, size_t offset ) {
         jv.throw_error( offset, msg );
     };
     const std::string s = jv;
     return detail::read_from_json_string_common<T>( s, units, error );
 }
References error, and JsonValue::throw_error().
Referenced by units::quantity< V, U >::deserialize(), Item_factory::load(), and vitamin::load_vitamin().