Cataclysm DDA: src/veh_type.cpp File Reference
veh_type.cpp File Reference
#include "veh_type.h"
#include <algorithm>
#include <cstddef>
#include <limits>
#include <memory>
#include <numeric>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include "ammo.h"
#include "assign.h"
#include "cata_assert.h"
#include "character.h"
#include "color.h"
#include "debug.h"
#include "flag.h"
#include "game_constants.h"
#include "generic_factory.h"
#include "init.h"
#include "item.h"
#include "item_factory.h"
#include "item_group.h"
#include "itype.h"
#include "json.h"
#include "output.h"
#include "pocket_type.h"
#include "requirements.h"
#include "ret_val.h"
#include "string_formatter.h"
#include "translations.h"
#include "units.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "vehicle.h"
#include "vehicle_group.h"
#include "wcwidth.h"
Namespaces
anonymous_namespace{veh_type.cpp}
Functions
static void parse_vp_reqs (const JsonObject &obj, const vpart_id &id, const std::string &key, std::vector< std::pair< requirement_id, int >> &reqs, std::map< skill_id, int > &skills, time_duration &time)
static void parse_vp_control_reqs (const JsonObject &obj, const vpart_id &id, const std::string_view &key, vp_control_req &req)
static bool mountable_gun_filter (const itype &guntype)
static bool gun_uses_liquid_ammo (const itype &guntype)
static int gun_battery_mags_drain (const itype &guntype)
static std::string get_looks_like (const vpart_info &vpi, const itype &it)
static time_duration scale_time (const std::map< skill_id, int > &sk, time_duration mv, const Character &you)
static int utf32_to_ncurses_ACS (char32_t sym)
static std::pair< std::string, std::string > get_vpart_str_variant (const std::string &vpid)
Variables
generic_factory< vehicle_prototype > anonymous_namespace{veh_type.cpp}::vehicle_prototype_factory ("vehicle", "id")
generic_factory< vpart_info > anonymous_namespace{veh_type.cpp}::vpart_info_factory ("vehicle_part", "id")
static const ammotype ammo_battery ("battery")
static const itype_id fuel_type_animal ("animal")
static const itype_id itype_null ("null")
static const quality_id qual_JACK ("JACK")
static const quality_id qual_LIFT ("LIFT")
static const quality_id qual_PISTOL ("PISTOL")
static const quality_id qual_SMG ("SMG")
static const skill_id skill_launcher ("launcher")
static const vpart_id vpart_turret_generic ("turret_generic")
static const std::unordered_map< std::string, vpart_bitflags > vpart_bitflag_map
static std::map< vpart_id, vpart_migration > vpart_migrations
static std::vector< vpart_category > vpart_categories_all
Function Documentation
get_looks_like()
static std::string get_looks_like (const vpart_info & vpi, const itype & it) static
Definition at line 521 of file veh_type.cpp.
 {
     static const auto has_light_ammo = []( const std::set<ammotype> &ats ) {
         for( const ammotype &at : ats ) {
             if( !at->default_ammotype() ) {
                 continue;
             }
             const units::mass at_weight = at->default_ammotype()->weight;
             if( 15_gram > at_weight && at_weight > 3_gram ) {
                 return true; // detects g80 and coil gun
             }
         }
         return false;
     };
     if( it.gun->energy_drain > 0_kJ && has_light_ammo( it.gun->ammo ) ) {
         return "mounted_hk_g80"; // railguns
     } else if( vpi.has_flag( "USE_BATTERIES" ) || it.gun->energy_drain > 0_kJ ) {
         return "laser_rifle"; // generic energy weapons
     } else if( vpi.has_flag( "USE_TANKS" ) ) {
         return "watercannon"; // liquid sprayers (flamethrower, foam gun etc)
     } else if( it.gun->skill_used == skill_launcher ) {
         return "tow_launcher"; // launchers
     } else {
         return "m249"; // machine guns and also default for any unknown
     }
 }
References itype::gun, vpart_info::has_flag(), and skill_launcher.
Referenced by vehicles::parts::finalize().
get_vpart_str_variant()
static std::pair<std::string, std::string> get_vpart_str_variant (const std::string & vpid) static
Definition at line 1258 of file veh_type.cpp.
 {
     const size_t loc = vpid.rfind( vehicles::variant_separator );
     return loc == std::string::npos
            ? std::make_pair( vpid, "" )
            : std::make_pair( vpid.substr( 0, loc ), vpid.substr( loc + 1 ) );
 }
References vehicles::variant_separator.
Referenced by vehicle_prototype::load().
gun_battery_mags_drain()
static int gun_battery_mags_drain (const itype & guntype) static
Definition at line 501 of file veh_type.cpp.
 {
     int charges_used = 0;
     for( const pocket_data &maybe_mag_well : guntype.pockets ) {
         for( const itype_id &restricted_type : maybe_mag_well.item_id_restriction ) {
             for( const pocket_data &maybe_mag : restricted_type.obj().pockets ) {
                 for( const std::pair<const ammotype, int> &res : maybe_mag.ammo_restriction ) {
                     if( res.first == ammo_battery ) {
                         charges_used = std::max( charges_used, guntype.gun->ammo_to_fire );
                     }
                 }
             }
         }
     }
     if( guntype.gun->energy_drain > 0_kJ && charges_used > 0 ) {
         debugmsg( "%s uses both energy and battery magazines", guntype.nname( 1 ) );
     }
     return charges_used;
 }
References ammo_battery, debugmsg, itype::gun, pocket_data::item_id_restriction, max(), itype::nname(), string_id< T >::obj(), and itype::pockets.
Referenced by vehicles::parts::finalize().
gun_uses_liquid_ammo()
static bool gun_uses_liquid_ammo (const itype & guntype) static
Definition at line 479 of file veh_type.cpp.
 {
     for( const ammotype &at : guntype.gun->ammo ) {
         if( at->default_ammotype()->phase == phase_id::LIQUID ) {
             return true;
         }
     }
     for( const pocket_data &maybe_magwell : guntype.pockets ) {
         for( const itype_id &restricted_types : maybe_magwell.item_id_restriction ) {
             for( const pocket_data &maybe_mag : restricted_types.obj().pockets ) {
                 for( const std::pair<const ammotype, int> &res : maybe_mag.ammo_restriction ) {
                     if( res.first->default_ammotype()->phase == phase_id::LIQUID ) {
                         return true;
                     }
                 }
             }
         }
     }
     return false;
 }
References ammunition_type::default_ammotype(), itype::gun, pocket_data::item_id_restriction, LIQUID, string_id< T >::obj(), itype::phase, and itype::pockets.
Referenced by vehicles::parts::finalize().
mountable_gun_filter()
static bool mountable_gun_filter (const itype & guntype) static
Definition at line 458 of file veh_type.cpp.
 {
     static const std::vector<flag_id> bad_flags {
         flag_BIONIC_WEAPON,
         flag_NO_TURRET,
         flag_NO_UNWIELD,
         flag_PSEUDO,
         flag_RELOAD_AND_SHOOT,
         flag_STR_DRAW,
     };
     if( !guntype.gun || guntype.gunmod ) {
         return false;
     }
     return std::none_of( bad_flags.cbegin(), bad_flags.cend(), [&guntype]( const flag_id & flag ) {
         return guntype.has_flag( flag );
     } );
 }
References flag_BIONIC_WEAPON, flag_NO_TURRET, flag_NO_UNWIELD, flag_PSEUDO, flag_RELOAD_AND_SHOOT, flag_STR_DRAW, itype::gun, and itype::gunmod.
Referenced by vehicles::parts::finalize().
parse_vp_control_reqs()
static void parse_vp_control_reqs (const JsonObject & obj, const vpart_id & id, const std::string_view & key, vp_control_req & req) static
Definition at line 212 of file veh_type.cpp.
 {
     if( !obj.has_object( key ) ) {
         return;
     }
     JsonObject src = obj.get_object( key );
     JsonArray sk = src.get_array( "skills" );
     if( !sk.empty() ) {
         req.skills.clear();
         for( JsonArray cur : sk ) {
             if( cur.size() != 2 ) {
                 debugmsg( "vpart '%s' has requirement with invalid skill entry", id.str() );
                 continue;
             }
             req.skills.emplace( skill_id( cur.get_string( 0 ) ), cur.get_int( 1 ) );
         }
     }
     optional( src, false, "proficiencies", req.proficiencies );
 }
References debugmsg, JsonArray::empty(), JsonObject::get_array(), int_id< T >::obj(), optional(), vp_control_req::proficiencies, and vp_control_req::skills.
Referenced by vpart_info::load().
parse_vp_reqs()
static void parse_vp_reqs (const JsonObject & obj, const vpart_id & id, const std::string & key, std::vector< std::pair< requirement_id, int >> & reqs, std::map< skill_id, int > & skills, time_duration & time) static
Definition at line 165 of file veh_type.cpp.
 {
     if( !obj.has_object( key ) ) {
         return;
     }
     JsonObject src = obj.get_object( key );
     JsonArray sk = src.get_array( "skills" );
     if( !sk.empty() ) {
         skills.clear();
         for( JsonArray cur : sk ) {
             if( cur.size() != 2 ) {
                 debugmsg( "vpart '%s' has requirement with invalid skill entry", id.str() );
                 continue;
             }
             skills.emplace( skill_id( cur.get_string( 0 ) ), cur.get_int( 1 ) );
         }
     }
     if( src.has_string( "time" ) ) {
         assign( src, "time", time, /* strict = */ false );
     } else if( src.has_int( "time" ) ) { // remove in 0.H
         time = time_duration::from_moves( src.get_int( "time" ) );
         debugmsg( "vpart '%s' defines requirement time as integer, use time units string", id.str() );
     }
     if( src.has_string( "using" ) ) {
         reqs = { { requirement_id( src.get_string( "using" ) ), 1 } };
     } else if( src.has_array( "using" ) ) {
         reqs.clear();
         for( JsonArray cur : src.get_array( "using" ) ) {
             reqs.emplace_back( requirement_id( cur.get_string( 0 ) ), cur.get_int( 1 ) );
         }
     } else {
         reqs.clear();
         // Construct a requirement to capture "components", "qualities", and
         // "tools" that might be listed.
         // NOLINTNEXTLINE(cata-translate-string-literal)
         const requirement_id req_id( string_format( "inline_%s_%s", key.c_str(), id.c_str() ) );
         requirement_data::load_requirement( src, req_id );
         reqs.emplace_back( req_id, 1 );
     }
 }
References assign(), debugmsg, JsonArray::empty(), time_duration::from_moves(), JsonObject::get_array(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_int(), JsonObject::has_string(), requirement_data::load_requirement(), int_id< T >::obj(), and string_format().
Referenced by vpart_info::load().
scale_time()
static time_duration scale_time (const std::map< skill_id, int > & sk, time_duration mv, const Character & you) static
Definition at line 1092 of file veh_type.cpp.
 {
     if( sk.empty() ) {
         return mv;
     }
     const int lvl = std::accumulate( sk.begin(), sk.end(), 0, [&you]( int lhs,
     const std::pair<skill_id, int> &rhs ) {
         return lhs + std::max( std::min( static_cast<int>( you.get_skill_level( rhs.first ) ),
                                          MAX_SKILL ) - rhs.second, 0 );
     } );
     // 10% per excess level (reduced proportionally if >1 skill required) with max 50% reduction
     // 10% reduction per assisting Character
     const int helpersize = you.get_num_crafting_helpers( 3 );
     return mv * ( 1.0 - std::min( static_cast<double>( lvl ) / sk.size() / 10.0,
                                   0.5 ) ) * ( 1 - ( helpersize / 10.0 ) );
 }
References Character::get_num_crafting_helpers(), and min().
Referenced by vpart_info::install_time(), vpart_info::removal_time(), and vpart_info::repair_time().
utf32_to_ncurses_ACS()
static int utf32_to_ncurses_ACS (char32_t sym) static
Definition at line 1173 of file veh_type.cpp.
 {
     switch( sym ) {
         // *INDENT-OFF*
         case 0x2500: return LINE_OXOX; // horizontal line
         case 0x2501: return '=';       // horizontal line (heavy) no acs equivalent
         case 0x2502: return LINE_XOXO; // vertical line
         case 0x2503: return 'H';       // vertical line (heavy) no acs equivalent
         case 0x253C: return LINE_XXXX; // cross/plus
         case 0x250C: return LINE_OXXO; // upper left corner
         case 0x2510: return LINE_OOXX; // upper right corner
         case 0x2518: return LINE_XOOX; // lower right corner
         case 0x2514: return LINE_XXOO; // lower left corner
         default:     return static_cast<int>(sym);
         // *INDENT-ON*
     }
 }
References LINE_OOXX, LINE_OXOX, LINE_OXXO, LINE_XOOX, LINE_XOXO, LINE_XXOO, and LINE_XXXX.
Referenced by vpart_variant::get_symbol_curses().
Variable Documentation
ammo_battery
const ammotype ammo_battery("battery") ("battery") static
Referenced by gun_battery_mags_drain().
fuel_type_animal
const itype_id fuel_type_animal("animal") ("animal") static
Referenced by vpart_info::check().
itype_null
const itype_id itype_null("null") ("null") static
Referenced by vpart_info::finalize().
qual_JACK
const quality_id qual_JACK("JACK") ("JACK") static
Referenced by vpart_info::format_description().
qual_LIFT
const quality_id qual_LIFT("LIFT") ("LIFT") static
Referenced by vpart_info::format_description().
qual_PISTOL
const quality_id qual_PISTOL("PISTOL") ("PISTOL") static
Referenced by vehicles::parts::finalize().
qual_SMG
const quality_id qual_SMG("SMG") ("SMG") static
Referenced by vehicles::parts::finalize().
skill_launcher
const skill_id skill_launcher("launcher") ("launcher") static
Referenced by get_looks_like().
vpart_bitflag_map
const std::unordered_map<std::string, vpart_bitflags> vpart_bitflag_map static
Definition at line 86 of file veh_type.cpp.
Referenced by vpart_info::finalize(), and vpart_info::set_flag().
vpart_categories_all
std::vector<vpart_category> vpart_categories_all static
Definition at line 1700 of file veh_type.cpp.
Referenced by vpart_category::all(), vpart_category::finalize(), vpart_category::load(), and vpart_category::reset().
vpart_migrations
std::map<vpart_id, vpart_migration> vpart_migrations static
Definition at line 149 of file veh_type.cpp.
Referenced by vpart_migration::check(), vpart_migration::finalize(), vpart_migration::find_migration(), vpart_migration::load(), and vpart_migration::reset().
vpart_turret_generic
const vpart_id vpart_turret_generic("turret_generic") ("turret_generic") static
Referenced by vehicles::parts::finalize().