Cataclysm DDA: src/veh_appliance.cpp File Reference
veh_appliance.cpp File Reference
#include "game.h"
#include "handle_liquid.h"
#include "inventory.h"
#include "itype.h"
#include "map_iterator.h"
#include "action.h"
#include "messages.h"
#include "output.h"
#include "overmapbuffer.h"
#include "player_activity.h"
#include "skill.h"
#include "string_input_popup.h"
#include "ui.h"
#include "ui_manager.h"
#include "units.h"
#include "veh_appliance.h"
#include "veh_interact.h"
#include "veh_type.h"
#include "veh_utils.h"
#include "vehicle.h"
#include "vpart_range.h"
Classes
class app_uilist_handler
Functions
static const std::string flag_APPLIANCE ("APPLIANCE")
static const std::string flag_WIRING ("WIRING")
static const std::string flag_HALF_CIRCLE_LIGHT ("HALF_CIRCLE_LIGHT")
vpart_id vpart_appliance_from_item (const itype_id &item_id)
void place_appliance (const tripoint &p, const vpart_id &vpart, const std::optional< item > &base)
static bool has_battery_in_grid (vehicle *veh)
static vehicle_part * pick_part (const std::vector< vehicle_part * > &parts, const std::string &query_msg)
Variables
static const activity_id ACT_VEHICLE ("ACT_VEHICLE")
static const itype_id fuel_type_battery ("battery")
static const itype_id itype_wall_wiring ("wall_wiring")
static const quality_id qual_HOSE ("HOSE")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
static const vpart_id vpart_ap_standing_lamp ("ap_standing_lamp")
static const vproto_id vehicle_prototype_none ("none")
static const int win_width = 60
static app_uilist_handler app_callback
Function Documentation
flag_APPLIANCE()
static const std::string flag_APPLIANCE ("APPLIANCE") static
Referenced by place_appliance(), and vpart_appliance_from_item().
flag_HALF_CIRCLE_LIGHT()
static const std::string flag_HALF_CIRCLE_LIGHT ("HALF_CIRCLE_LIGHT") static
Referenced by place_appliance().
flag_WIRING()
static const std::string flag_WIRING ("WIRING") static
Referenced by place_appliance().
has_battery_in_grid()
static bool has_battery_in_grid (vehicle * veh) static
Definition at line 152 of file veh_appliance.cpp.
 {
     return !veh->search_connected_batteries().empty();
 }
References vehicle::search_connected_batteries().
Referenced by veh_app_interact::draw_info(), and veh_app_interact::init_ui_windows().
pick_part()
static vehicle_part* pick_part (const std::vector< vehicle_part * > & parts, const std::string & query_msg) static
Definition at line 328 of file veh_appliance.cpp.
 {
     if( parts.empty() ) {
         return nullptr;
     }
     vehicle_part *pt = parts.front();
     if( parts.size() > 1 ) {
         uilist pt_sel( query_msg, {} );
         for( const vehicle_part *vpr : parts ) {
             std::string enttxt;
             std::string vname = vpr->name();
             if( !vpr->ammo_current().is_null() && vpr->ammo_current() != fuel_type_battery &&
                 !vpr->get_base().empty() ) {
                 units::volume mult = units::legacy_volume_factor / item::find_type(
                                          vpr->ammo_current() )->stack_size;
                 double vcur = to_liter( vpr->ammo_remaining() * mult );
                 double vmax = to_liter( vpr->ammo_capacity( vpr->get_base().only_item().ammo_type() ) * mult );
                 //~ Vehicle part name, capacity (current/max L) and name of contents
                 enttxt = string_format( _( "%1$s (%2$.1f/%3$.1fL %4$s)" ), vname, round_up( vcur, 1 ),
                                         round_up( vmax, 1 ), item::nname( vpr->ammo_current() ) );
             } else {
                 enttxt = vname;
             }
             pt_sel.addentry( enttxt );
         }
         pt_sel.query();
         int sel = pt_sel.ret;
         if( sel < 0 || static_cast<size_t>( sel ) >= parts.size() ) {
             return nullptr;
         }
         pt = parts[sel];
     }
     return pt;
 }
References _, item::find_type(), fuel_type_battery, units::legacy_volume_factor, item::nname(), round_up(), itype::stack_size, string_format(), and units::to_liter().
Referenced by veh_app_interact::refill(), and veh_app_interact::siphon().
place_appliance()
void place_appliance (const tripoint & p, const vpart_id & vpart, const std::optional< item > & base)
Definition at line 56 of file veh_appliance.cpp.
 {
     const vpart_info &vpinfo = vpart.obj();
     map &here = get_map();
     vehicle *veh = here.add_vehicle( vehicle_prototype_none, p, 0_degrees, 0, 0 );
     if( !veh ) {
         debugmsg( "error constructing vehicle" );
         return;
     }
     veh->add_tag( flag_APPLIANCE );
     int partnum = -1;
     if( base ) {
         item copied = *base;
         partnum = veh->install_part( point_zero, vpart, std::move( copied ) );
     } else {
         partnum = veh->install_part( point_zero, vpart );
     }
     veh->name = vpart->name();
     veh->last_update = calendar::turn;
     if( vpinfo.base_item == itype_wall_wiring ) {
         veh->add_tag( flag_WIRING );
     }
     // Update the vehicle cache immediately,
     // or the appliance will be invisible for the first couple of turns.
     here.add_vehicle_to_cache( veh );
     // Connect to any neighbouring appliances or wires once
     std::unordered_set<const vehicle *> connected_vehicles;
     for( const tripoint &trip : here.points_in_radius( p, 1 ) ) {
         const optional_vpart_position vp = here.veh_at( trip );
         if( !vp ) {
             continue;
         }
         vehicle &veh_target = vp->vehicle();
         if( veh_target.has_tag( flag_APPLIANCE ) ) {
             if( veh->is_powergrid() && veh_target.is_powergrid() &&
                 veh->merge_appliance_into_grid( veh_target ) ) {
                 add_msg( _( "You merge it into the adjacent power grid." ) );
                 continue;
             }
             if( connected_vehicles.find( &veh_target ) == connected_vehicles.end() ) {
                 veh->connect( p, trip );
                 connected_vehicles.insert( &veh_target );
             }
         }
     }
     veh->part_removal_cleanup();
     // Make some lighting appliances directed
     if( vpinfo.has_flag( flag_HALF_CIRCLE_LIGHT ) && partnum != -1 ) {
         orient_part( veh, vpinfo, partnum );
     }
 }
References _, add_msg(), vehicle::add_tag(), map::add_vehicle(), map::add_vehicle_to_cache(), vpart_info::base_item, vehicle::connect(), debugmsg, flag_APPLIANCE(), flag_HALF_CIRCLE_LIGHT(), flag_WIRING(), get_map(), vpart_info::has_flag(), vehicle::has_tag(), vehicle::install_part(), vehicle::is_powergrid(), itype_wall_wiring, vehicle::last_update, vehicle::merge_appliance_into_grid(), vpart_info::name(), vehicle::name, string_id< T >::obj(), orient_part(), vehicle::part_removal_cleanup(), point_zero, map::points_in_radius(), calendar::turn, map::veh_at(), and vehicle_prototype_none.
Referenced by appliance_convert_examine_actor::call(), construct::done_appliance(), construct::done_wiring(), and deploy_appliance_actor::use().
vpart_appliance_from_item()
vpart_id vpart_appliance_from_item (const itype_id & item_id)
Definition at line 45 of file veh_appliance.cpp.
 {
     for( const vpart_info &vpi : vehicles::parts::get_all() ) {
         if( vpi.base_item == item_id && vpi.has_flag( flag_APPLIANCE ) ) {
             return vpi.id;
         }
     }
     debugmsg( "item %s is not base item of any appliance!", item_id.c_str() );
     return vpart_ap_standing_lamp;
 }
References string_id< T >::c_str(), debugmsg, flag_APPLIANCE(), vehicles::parts::get_all(), string_id< T >::id(), and vpart_ap_standing_lamp.
Referenced by appliance_convert_examine_actor::call(), construct::done_appliance(), appliance_convert_examine_actor::finalize(), deploy_appliance_actor::info(), and deploy_appliance_actor::use().
Variable Documentation
ACT_VEHICLE
const activity_id ACT_VEHICLE("ACT_VEHICLE") ("ACT_VEHICLE") static
Referenced by veh_app_interact::refill(), and veh_app_interact::remove().
app_callback
app_uilist_handler app_callback static
Definition at line 129 of file veh_appliance.cpp.
Referenced by veh_app_interact::init_ui_windows().
fuel_type_battery
const itype_id fuel_type_battery("battery") ("battery") static
Referenced by pick_part().
itype_wall_wiring
const itype_id itype_wall_wiring("wall_wiring") ("wall_wiring") static
Referenced by place_appliance().
qual_HOSE
const quality_id qual_HOSE("HOSE") ("HOSE") static
Referenced by veh_app_interact::can_siphon().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by veh_app_interact::remove().
vehicle_prototype_none
const vproto_id vehicle_prototype_none("none") ("none") static
Referenced by place_appliance().
vpart_ap_standing_lamp
const vpart_id vpart_ap_standing_lamp("ap_standing_lamp") ("ap_standing_lamp") static
Referenced by vpart_appliance_from_item().
win_width
const int win_width = 60 static
Definition at line 43 of file veh_appliance.cpp.
Referenced by anonymous_namespace{armor_layers.cpp}::draw_mid_pane(), veh_app_interact::init_ui_windows(), inventory_selector::prepare_layout(), app_uilist_handler::refresh(), and worldfactory::show_worldgen_basic().