Cataclysm DDA: src/veh_interact.cpp File Reference
veh_interact.cpp File Reference
#include "veh_interact.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdlib>
#include <functional>
#include <iostream>
#include <iterator>
#include <list>
#include <memory>
#include <new>
#include <numeric>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <type_traits>
#include <unordered_set>
#include <utility>
#include "activity_handlers.h"
#include "activity_type.h"
#include "avatar.h"
#include "calendar.h"
#include "cata_scope_helpers.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "character.h"
#include "character_id.h"
#include "clzones.h"
#include "colony.h"
#include "contents_change_handler.h"
#include "creature_tracker.h"
#include "debug.h"
#include "enums.h"
#include "faction.h"
#include "fault.h"
#include "flag.h"
#include "game.h"
#include "game_constants.h"
#include "handle_liquid.h"
#include "item.h"
#include "item_group.h"
#include "itype.h"
#include "line.h"
#include "localized_comparator.h"
#include "map.h"
#include "map_selector.h"
#include "mapdata.h"
#include "memory_fast.h"
#include "messages.h"
#include "monster.h"
#include "npc.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "point.h"
#include "requirements.h"
#include "skill.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "tileray.h"
#include "translations.h"
#include "ui.h"
#include "ui_manager.h"
#include "units.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "veh_utils.h"
#include "vehicle.h"
#include "vehicle_selector.h"
#include "vpart_position.h"
#include "vpart_range.h"
Classes
struct veh_interact::install_info_t
struct veh_interact::remove_info_t
Functions
static std::string status_color (bool status)
static std::string health_color (bool status)
static double jack_quality (const vehicle &veh)
static void act_vehicle_unload_fuel (vehicle *veh)
void orient_part (vehicle *veh, const vpart_info &vpinfo, int partnum, const std::optional< point > &part_placement)
static void sort_uilist_entries_by_line_drawing (std::vector< uilist_entry > &shape_ui_entries)
static void do_change_shape_menu (vehicle_part &vp)
static std::string wheel_state_description (const vehicle &veh)
static std::string veh_act_desc (const input_context &ctxt, const std::string &id, const std::string &desc, const task_reason reason)
void act_vehicle_siphon (vehicle *veh)
Variables
static const activity_id ACT_VEHICLE ("ACT_VEHICLE")
static const ammotype ammo_battery ("battery")
static const faction_id faction_no_faction ("no_faction")
static const itype_id fuel_type_battery ("battery")
static const itype_id itype_battery ("battery")
static const itype_id itype_plut_cell ("plut_cell")
static const proficiency_id proficiency_prof_aircraft_mechanic ("prof_aircraft_mechanic")
static const quality_id qual_HOSE ("HOSE")
static const quality_id qual_JACK ("JACK")
static const quality_id qual_LIFT ("LIFT")
static const quality_id qual_SELF_JACK ("SELF_JACK")
static const skill_id skill_mechanics ("mechanics")
static const trait_id trait_BADBACK ("BADBACK")
static const trait_id trait_DEBUG_HS ("DEBUG_HS")
static const trait_id trait_STRONGBACK ("STRONGBACK")
static const vpart_id vpart_ap_wall_wiring ("ap_wall_wiring")
static constexpr units::mass JACK_LIMIT = 8500_kilogram
static auto can_refill
Can part currently be reloaded with anything?
Function Documentation
act_vehicle_siphon()
void act_vehicle_siphon (vehicle * veh)
Definition at line 2999 of file veh_interact.cpp.
 {
     std::vector<itype_id> fuels;
     bool has_liquid = false;
     // Check all tanks on this vehicle to see if they contain any liquid
     for( const vpart_reference &vp : veh->get_any_parts( VPFLAG_FLUIDTANK ) ) {
         if( vp.part().contains_liquid() ) {
             has_liquid = true;
             break;
         }
     }
     if( !has_liquid ) {
         add_msg( m_info, _( "The vehicle has no liquid fuel left to siphon." ) );
         return;
     }
     std::string title = _( "Select tank to siphon:" );
     auto sel = []( const vehicle_part & pt ) {
         return pt.contains_liquid();
     };
     if( const std::optional<vpart_reference> tank = veh_interact::select_part( *veh, sel, title ) ) {
         item liquid( tank->part().get_base().only_item() );
         const int liq_charges = liquid.charges;
         if( liquid_handler::handle_liquid( liquid, nullptr, 1, nullptr, veh, tank->part_index() ) ) {
             veh->drain( tank->part_index(), liq_charges - liquid.charges );
             veh->invalidate_mass();
         }
     }
 }
References _, add_msg(), item::charges, vehicle::drain(), vehicle::get_any_parts(), liquid_handler::handle_liquid(), vehicle::invalidate_mass(), m_info, veh_interact::select_part(), music::title, and VPFLAG_FLUIDTANK.
Referenced by iuse::siphon().
act_vehicle_unload_fuel()
void act_vehicle_unload_fuel (vehicle * veh) static
Definition at line 3029 of file veh_interact.cpp.
 {
     std::vector<itype_id> fuels;
     for( auto &e : veh->fuels_left() ) {
         const itype *type = item::find_type( e.first );
         if( e.first == fuel_type_battery || type->phase != phase_id::SOLID ) {
             // This skips battery and plutonium cells
             continue;
         }
         fuels.push_back( e.first );
     }
     if( fuels.empty() ) {
         add_msg( m_info, _( "The vehicle has no solid fuel left to remove." ) );
         return;
     }
     itype_id fuel;
     if( fuels.size() > 1 ) {
         uilist smenu;
         smenu.text = _( "Remove what?" );
         for( auto &fuel : fuels ) {
             if( fuel == itype_plut_cell && veh->fuel_left( fuel ) < PLUTONIUM_CHARGES ) {
                 continue;
             }
             smenu.addentry( item::nname( fuel ) );
         }
         smenu.query();
         if( smenu.ret < 0 || static_cast<size_t>( smenu.ret ) >= fuels.size() ) {
             add_msg( m_info, _( "Never mind." ) );
             return;
         }
         fuel = fuels[smenu.ret];
     } else {
         fuel = fuels.front();
     }
     Character &player_character = get_player_character();
     int qty = veh->fuel_left( fuel );
     if( fuel == itype_plut_cell ) {
         if( qty / PLUTONIUM_CHARGES == 0 ) {
             add_msg( m_info, _( "The vehicle has no charged plutonium cells." ) );
             return;
         }
         item plutonium( fuel, calendar::turn, qty / PLUTONIUM_CHARGES );
         player_character.i_add( plutonium );
         veh->drain( fuel, qty - ( qty % PLUTONIUM_CHARGES ) );
     } else {
         item solid_fuel( fuel, calendar::turn, qty );
         player_character.i_add( solid_fuel );
         veh->drain( fuel, qty );
     }
 }
References _, add_msg(), uilist::addentry(), vehicle::drain(), item::find_type(), vehicle::fuel_left(), fuel_type_battery, vehicle::fuels_left(), get_player_character(), Character::i_add(), itype_plut_cell, m_info, item::nname(), PLUTONIUM_CHARGES, uilist::query(), uilist::ret, SOLID, uilist::text, and calendar::turn.
Referenced by veh_interact::do_unload().
do_change_shape_menu()
static void do_change_shape_menu (vehicle_part & vp) static
Definition at line 1949 of file veh_interact.cpp.
 {
     const vpart_info &vpi = vp.info();
     uilist smenu;
     smenu.text = _( "Choose cosmetic variant:" );
     int ret_code = 0;
     int default_selection = 0;
     std::vector<std::string> variants;
     for( const auto& [variant_id, vv] : vpi.variants ) {
         if( variant_id == vp.variant ) {
             default_selection = ret_code;
         }
         uilist_entry entry( vv.get_label() );
         entry.txt = entry.txt.empty() ? _( "Default" ) : entry.txt;
         entry.retval = ret_code++;
         entry.extratxt.left = 1;
         entry.extratxt.sym = vv.get_symbol_curses( 0_degrees, false );
         entry.extratxt.color = vpi.color;
         variants.emplace_back( variant_id );
         smenu.entries.emplace_back( entry );
     }
     sort_uilist_entries_by_line_drawing( smenu.entries );
     // get default selection after sorting
     for( std::size_t i = 0; i < smenu.entries.size(); ++i ) {
         if( smenu.entries[i].retval == default_selection ) {
             default_selection = i;
             break;
         }
     }
     smenu.selected = default_selection;
     smenu.query();
     if( smenu.ret >= 0 ) {
         vp.variant = variants[smenu.ret];
     }
 }
References _, mvwzstr::color, vpart_info::color, uilist::entries, uilist_entry::extratxt, vehicle_part::info(), mvwzstr::left, uilist::query(), uilist::ret, uilist_entry::retval, uilist::selected, sort_uilist_entries_by_line_drawing(), mvwzstr::sym, uilist::text, uilist_entry::txt, vehicle_part::variant, and vpart_info::variants.
Referenced by veh_interact::complete_vehicle(), and veh_interact::do_change_shape().
health_color()
static std::string health_color (bool status) static
Definition at line 106 of file veh_interact.cpp.
 {
     return status ? "<color_light_green>" : "<color_light_red>";
 }
References status.
Referenced by veh_interact::calc_overview(), and display::health_text_color().
jack_quality()
static double jack_quality (const vehicle & veh) static
Definition at line 115 of file veh_interact.cpp.
 {
     const units::quantity<double, units::mass::unit_type> mass = std::min( veh.total_mass(),
             JACK_LIMIT );
     return std::ceil( mass / lifting_quality_to_mass( 1 ) );
 }
References ceil(), JACK_LIMIT, lifting_quality_to_mass(), min(), and vehicle::total_mass().
Referenced by veh_interact::calc_lift_requirements(), and veh_interact::can_self_jack().
orient_part()
void orient_part (vehicle * veh, const vpart_info & vpinfo, int partnum, const std::optional< point > & part_placement)
Definition at line 187 of file veh_interact.cpp.
 {
     avatar &player_character = get_avatar();
     // Stash offset and set it to the location of the part so look_around will
     // start there.
     const tripoint old_view_offset = player_character.view_offset;
     tripoint offset = veh->global_pos3();
     // Appliances are one tile so the part placement there is always point_zero
     if( part_placement ) {
         point copied_placement = *part_placement ;
         offset += copied_placement ;
     }
     player_character.view_offset = offset - player_character.pos();
     point delta;
     do {
         popup( _( "Press space, choose a facing direction for the new %s and "
                   "confirm with enter." ),
                vpinfo.name() );
         const std::optional<tripoint> chosen = g->look_around();
         if( !chosen ) {
             continue;
         }
         delta = ( *chosen - offset ).xy();
         // atan2 only gives reasonable values when delta is not all zero
     } while( delta == point_zero );
     // Restore previous view offsets.
     player_character.view_offset = old_view_offset;
     units::angle dir = normalize( atan2( delta ) - veh->face.dir() );
     veh->part( partnum ).direction = dir;
 }
References _, atan2(), tileray::dir(), vehicle_part::direction, vehicle::face, g, get_avatar(), vehicle::global_pos3(), vpart_info::name(), normalize(), vehicle::part(), point_zero, popup(), Creature::pos(), and Character::view_offset.
Referenced by veh_interact::complete_vehicle(), and place_appliance().
sort_uilist_entries_by_line_drawing()
static void sort_uilist_entries_by_line_drawing (std::vector< uilist_entry > & shape_ui_entries) static
Definition at line 928 of file veh_interact.cpp.
 {
     // An ordering of the line drawing symbols that does not result in
     // connecting when placed adjacent to each other vertically.
     const static std::map<int, int> symbol_order = {
         { LINE_XOXO, 0 }, { LINE_OXOX, 1 },
         { LINE_XOOX, 2 }, { LINE_XXOO, 3 },
         { LINE_XXXX, 4 }, { LINE_OXXO, 5 },
         { LINE_OOXX, 6 }
     };
     std::sort( shape_ui_entries.begin(), shape_ui_entries.end(),
     []( const uilist_entry & a, const uilist_entry & b ) {
         auto a_iter = symbol_order.find( a.extratxt.sym );
         auto b_iter = symbol_order.find( b.extratxt.sym );
         if( a_iter != symbol_order.end() ) {
             if( b_iter != symbol_order.end() ) {
                 return a_iter->second < b_iter->second;
             } else {
                 return true;
             }
         } else if( b_iter != symbol_order.end() ) {
             return false;
         } else {
             return a.extratxt.sym < b.extratxt.sym;
         }
     } );
 }
References a, b, LINE_OOXX, LINE_OXOX, LINE_OXXO, LINE_XOOX, LINE_XOXO, LINE_XXOO, and LINE_XXXX.
Referenced by do_change_shape_menu().
status_color()
static std::string status_color (bool status) static
Definition at line 102 of file veh_interact.cpp.
 {
     return status ? "<color_green>" : "<color_red>";
 }
References status.
Referenced by veh_interact::can_remove_part(), veh_interact::format_reqs(), distraction_manager::distraction_manager_gui::show(), and veh_interact::update_part_requirements().
veh_act_desc()
static std::string veh_act_desc (const input_context & ctxt, const std::string & id, const std::string & desc, const task_reason reason) static
Definition at line 2686 of file veh_interact.cpp.
 {
     static const translation inline_fmt_enabled = to_translation(
                 "keybinding", "<color_light_gray>%1$s<color_light_green>%2$s</color>%3$s</color>" );
     static const translation inline_fmt_disabled = to_translation(
                 "keybinding", "<color_dark_gray>%1$s<color_green>%2$s</color>%3$s</color>" );
     static const translation separate_fmt_enabled = to_translation(
                 "keybinding", "<color_light_gray><color_light_green>%1$s</color>-%2$s</color>" );
     static const translation separate_fmt_disabled = to_translation(
                 "keybinding", "<color_dark_gray><color_green>%1$s</color>-%2$s</color>" );
     if( reason == task_reason::CAN_DO ) {
         return ctxt.get_desc( id, desc, input_context::allow_all_keys,
                               inline_fmt_enabled, separate_fmt_enabled );
     } else {
         return ctxt.get_desc( id, desc, input_context::allow_all_keys,
                               inline_fmt_disabled, separate_fmt_disabled );
     }
 }
References input_context::allow_all_keys(), CAN_DO, input_context::get_desc(), and to_translation().
Referenced by veh_interact::display_mode().
wheel_state_description()
static std::string wheel_state_description (const vehicle & veh) static
Definition at line 2415 of file veh_interact.cpp.
 {
     bool is_boat = !veh.floating.empty();
     bool is_land = !veh.wheelcache.empty() || !is_boat;
     bool suf_land = veh.sufficient_wheel_config();
     bool bal_land = veh.balanced_wheel_config();
     bool suf_boat = veh.can_float();
     float steer = veh.steering_effectiveness();
     std::string wheel_status;
     if( !suf_land && is_boat ) {
         wheel_status = _( "<color_light_red>disabled</color>" );
     } else if( !suf_land ) {
         wheel_status = _( "<color_light_red>lack</color>" );
     } else if( !bal_land ) {
         wheel_status = _( "<color_light_red>unbalanced</color>" );
     } else if( steer < 0 ) {
         wheel_status = _( "<color_light_red>no steering</color>" );
     } else if( steer < 0.033 ) {
         wheel_status = _( "<color_light_red>broken steering</color>" );
     } else if( steer < 0.5 ) {
         wheel_status = _( "<color_light_red>poor steering</color>" );
     } else {
         wheel_status = _( "<color_light_green>enough</color>" );
     }
     std::string boat_status;
     if( !suf_boat ) {
         boat_status = _( "<color_light_red>sinks</color>" );
     } else {
         boat_status = _( "<color_light_blue>floats</color>" );
     }
     if( is_boat && is_land ) {
         return string_format( _( "Wheels/boat: %s/%s" ), wheel_status, boat_status );
     }
     if( is_boat ) {
         return string_format( _( "Boat: %s" ), boat_status );
     }
     return string_format( _( "Wheels: %s" ), wheel_status );
 }
References _, vehicle::balanced_wheel_config(), vehicle::can_float(), vehicle::floating, vehicle::steering_effectiveness(), string_format(), vehicle::sufficient_wheel_config(), and vehicle::wheelcache.
Referenced by veh_interact::display_stats().
Variable Documentation
ACT_VEHICLE
const activity_id ACT_VEHICLE("ACT_VEHICLE") ("ACT_VEHICLE") static
Referenced by veh_interact::serialize_activity().
ammo_battery
const ammotype ammo_battery("battery") ("battery") static
Referenced by veh_interact::calc_overview().
can_refill
auto can_refill static
Initial value:
= [](const vehicle_part &pt)
{
    return pt.can_reload();
}
Can part currently be reloaded with anything?
Definition at line 123 of file veh_interact.cpp.
Referenced by veh_interact::do_refill().
faction_no_faction
const faction_id faction_no_faction("no_faction") ("no_faction") static
Referenced by veh_interact::do_main_loop().
fuel_type_battery
const itype_id fuel_type_battery("battery") ("battery") static
Referenced by act_vehicle_unload_fuel(), and veh_interact::cant_do().
itype_battery
const itype_id itype_battery("battery") ("battery") static
Referenced by veh_interact::display_details().
itype_plut_cell
const itype_id itype_plut_cell("plut_cell") ("plut_cell") static
Referenced by act_vehicle_unload_fuel().
JACK_LIMIT
constexpr units::mass JACK_LIMIT = 8500_kilogram static constexpr
Definition at line 112 of file veh_interact.cpp.
Referenced by jack_quality().
proficiency_prof_aircraft_mechanic
const proficiency_id proficiency_prof_aircraft_mechanic("prof_aircraft_mechanic") ("prof_aircraft_mechanic") static
Referenced by veh_interact::do_repair().
qual_HOSE
const quality_id qual_HOSE("HOSE") ("HOSE") static
Referenced by veh_interact::cant_do().
qual_JACK
const quality_id qual_JACK("JACK") ("JACK") static
Referenced by veh_interact::cache_tool_availability(), and veh_interact::calc_lift_requirements().
qual_LIFT
const quality_id qual_LIFT("LIFT") ("LIFT") static
Referenced by veh_interact::calc_lift_requirements().
qual_SELF_JACK
const quality_id qual_SELF_JACK("SELF_JACK") ("SELF_JACK") static
Referenced by veh_interact::can_self_jack().
skill_mechanics
const skill_id skill_mechanics("mechanics") ("mechanics") static
Referenced by veh_interact::update_part_requirements().
trait_BADBACK
const trait_id trait_BADBACK("BADBACK") ("BADBACK") static
Referenced by veh_interact::calc_lift_requirements().
trait_DEBUG_HS
const trait_id trait_DEBUG_HS("DEBUG_HS") ("DEBUG_HS") static
Referenced by veh_interact::can_potentially_install(), veh_interact::can_remove_part(), veh_interact::cant_do(), veh_interact::complete_vehicle(), veh_interact::do_mend(), veh_interact::serialize_activity(), and veh_interact::update_part_requirements().
trait_STRONGBACK
const trait_id trait_STRONGBACK("STRONGBACK") ("STRONGBACK") static
Referenced by veh_interact::calc_lift_requirements().
vpart_ap_wall_wiring
const vpart_id vpart_ap_wall_wiring("ap_wall_wiring") ("ap_wall_wiring") static
Referenced by veh_interact::complete_vehicle().