Cataclysm DDA: src/veh_interact.h File Reference
veh_interact.h File Reference
#include <cstddef>
#include <functional>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <utility>
#include <vector>
#include "color.h"
#include "cursesdef.h"
#include "input_context.h"
#include "item_location.h"
#include "mapdata.h"
#include "player_activity.h"
#include "point.h"
#include "type_id.h"
#include "units_fwd.h"
Classes
class veh_interact
struct veh_interact::part_option
Macros
#define CATA_SRC_VEH_INTERACT_H
Enumerations
enum class task_reason : int {
UNKNOWN_TASK = -1 , CAN_DO , INVALID_TARGET , LACK_TOOLS ,
NOT_FREE , LACK_SKILL , MOVING_VEHICLE , LOW_MORALE ,
LOW_LIGHT
}
Represents possible return values from the cant_do function.
Functions
void act_vehicle_siphon (vehicle *veh)
void orient_part (vehicle *veh, const vpart_info &vpinfo, int partnum, const std::optional< point > &part_placement=std::nullopt)
Variables
const std::string leak_marker = "<color_red>*</color>"
Macro Definition Documentation
CATA_SRC_VEH_INTERACT_H
#define CATA_SRC_VEH_INTERACT_H
Definition at line 3 of file veh_interact.h.
Enumeration Type Documentation
task_reason
enum task_reason : int strong
Represents possible return values from the cant_do function.
Enumerator
UNKNOWN_TASK
CAN_DO
INVALID_TARGET
LACK_TOOLS
NOT_FREE
LACK_SKILL
MOVING_VEHICLE
LOW_MORALE
LOW_LIGHT
Definition at line 30 of file veh_interact.h.
                        : int {
     UNKNOWN_TASK = -1, //No such task
     CAN_DO, //Task can be done
     INVALID_TARGET, //No valid target i.e. can't "change tire" if no tire present
     LACK_TOOLS, //Player doesn't have all the tools they need
     NOT_FREE, //Part is attached to something else and can't be unmounted
     LACK_SKILL, //Player doesn't have high enough mechanics skill
     MOVING_VEHICLE, // vehicle is moving, no modifications allowed
     LOW_MORALE, // Player has too low morale (for operations that require it)
     LOW_LIGHT // Player cannot see enough to work (for operations that require it)
 };
Function Documentation
act_vehicle_siphon()
void act_vehicle_siphon (vehicle * veh)
Definition at line 2999 of file veh_interact.cpp.
 {
     std::vector<itype_id> fuels;
     bool has_liquid = false;
     // Check all tanks on this vehicle to see if they contain any liquid
     for( const vpart_reference &vp : veh->get_any_parts( VPFLAG_FLUIDTANK ) ) {
         if( vp.part().contains_liquid() ) {
             has_liquid = true;
             break;
         }
     }
     if( !has_liquid ) {
         add_msg( m_info, _( "The vehicle has no liquid fuel left to siphon." ) );
         return;
     }
     std::string title = _( "Select tank to siphon:" );
     auto sel = []( const vehicle_part & pt ) {
         return pt.contains_liquid();
     };
     if( const std::optional<vpart_reference> tank = veh_interact::select_part( *veh, sel, title ) ) {
         item liquid( tank->part().get_base().only_item() );
         const int liq_charges = liquid.charges;
         if( liquid_handler::handle_liquid( liquid, nullptr, 1, nullptr, veh, tank->part_index() ) ) {
             veh->drain( tank->part_index(), liq_charges - liquid.charges );
             veh->invalidate_mass();
         }
     }
 }
References _, add_msg(), item::charges, vehicle::drain(), vehicle::get_any_parts(), liquid_handler::handle_liquid(), vehicle::invalidate_mass(), m_info, veh_interact::select_part(), music::title, and VPFLAG_FLUIDTANK.
Referenced by iuse::siphon().
orient_part()
void orient_part (vehicle * veh, const vpart_info & vpinfo, int partnum, const std::optional< point > & part_placement = std::nullopt)
Definition at line 187 of file veh_interact.cpp.
 {
     avatar &player_character = get_avatar();
     // Stash offset and set it to the location of the part so look_around will
     // start there.
     const tripoint old_view_offset = player_character.view_offset;
     tripoint offset = veh->global_pos3();
     // Appliances are one tile so the part placement there is always point_zero
     if( part_placement ) {
         point copied_placement = *part_placement ;
         offset += copied_placement ;
     }
     player_character.view_offset = offset - player_character.pos();
     point delta;
     do {
         popup( _( "Press space, choose a facing direction for the new %s and "
                   "confirm with enter." ),
                vpinfo.name() );
         const std::optional<tripoint> chosen = g->look_around();
         if( !chosen ) {
             continue;
         }
         delta = ( *chosen - offset ).xy();
         // atan2 only gives reasonable values when delta is not all zero
     } while( delta == point_zero );
     // Restore previous view offsets.
     player_character.view_offset = old_view_offset;
     units::angle dir = normalize( atan2( delta ) - veh->face.dir() );
     veh->part( partnum ).direction = dir;
 }
References _, atan2(), tileray::dir(), vehicle_part::direction, vehicle::face, g, get_avatar(), vehicle::global_pos3(), vpart_info::name(), normalize(), vehicle::part(), point_zero, popup(), Creature::pos(), and Character::view_offset.
Referenced by veh_interact::complete_vehicle(), and place_appliance().
Variable Documentation
leak_marker
const std::string leak_marker = "<color_red>*</color>"
Definition at line 47 of file veh_interact.h.
Referenced by veh_interact::calc_overview().