Cataclysm DDA: src/veh_appliance.h File Reference
veh_appliance.h File Reference
#include "input_context.h"
#include "player_activity.h"
Classes
class veh_app_interact
Appliance interaction UI.
Macros
#define CATA_SRC_VEH_APPLIANCE_H
Functions
vpart_id vpart_appliance_from_item (const itype_id &item_id)
void place_appliance (const tripoint &p, const vpart_id &vpart, const std::optional< item > &base=std::nullopt)
Macro Definition Documentation
CATA_SRC_VEH_APPLIANCE_H
#define CATA_SRC_VEH_APPLIANCE_H
Definition at line 3 of file veh_appliance.h.
Function Documentation
place_appliance()
void place_appliance (const tripoint & p, const vpart_id & vpart, const std::optional< item > & base = std::nullopt)
Definition at line 56 of file veh_appliance.cpp.
 {
     const vpart_info &vpinfo = vpart.obj();
     map &here = get_map();
     vehicle *veh = here.add_vehicle( vehicle_prototype_none, p, 0_degrees, 0, 0 );
     if( !veh ) {
         debugmsg( "error constructing vehicle" );
         return;
     }
     veh->add_tag( flag_APPLIANCE );
     int partnum = -1;
     if( base ) {
         item copied = *base;
         partnum = veh->install_part( point_zero, vpart, std::move( copied ) );
     } else {
         partnum = veh->install_part( point_zero, vpart );
     }
     veh->name = vpart->name();
     veh->last_update = calendar::turn;
     if( vpinfo.base_item == itype_wall_wiring ) {
         veh->add_tag( flag_WIRING );
     }
     // Update the vehicle cache immediately,
     // or the appliance will be invisible for the first couple of turns.
     here.add_vehicle_to_cache( veh );
     // Connect to any neighbouring appliances or wires once
     std::unordered_set<const vehicle *> connected_vehicles;
     for( const tripoint &trip : here.points_in_radius( p, 1 ) ) {
         const optional_vpart_position vp = here.veh_at( trip );
         if( !vp ) {
             continue;
         }
         vehicle &veh_target = vp->vehicle();
         if( veh_target.has_tag( flag_APPLIANCE ) ) {
             if( veh->is_powergrid() && veh_target.is_powergrid() &&
                 veh->merge_appliance_into_grid( veh_target ) ) {
                 add_msg( _( "You merge it into the adjacent power grid." ) );
                 continue;
             }
             if( connected_vehicles.find( &veh_target ) == connected_vehicles.end() ) {
                 veh->connect( p, trip );
                 connected_vehicles.insert( &veh_target );
             }
         }
     }
     veh->part_removal_cleanup();
     // Make some lighting appliances directed
     if( vpinfo.has_flag( flag_HALF_CIRCLE_LIGHT ) && partnum != -1 ) {
         orient_part( veh, vpinfo, partnum );
     }
 }
References _, add_msg(), vehicle::add_tag(), map::add_vehicle(), map::add_vehicle_to_cache(), vpart_info::base_item, vehicle::connect(), debugmsg, flag_APPLIANCE(), flag_HALF_CIRCLE_LIGHT(), flag_WIRING(), get_map(), vpart_info::has_flag(), vehicle::has_tag(), vehicle::install_part(), vehicle::is_powergrid(), itype_wall_wiring, vehicle::last_update, vehicle::merge_appliance_into_grid(), vpart_info::name(), vehicle::name, string_id< T >::obj(), orient_part(), vehicle::part_removal_cleanup(), point_zero, map::points_in_radius(), calendar::turn, map::veh_at(), and vehicle_prototype_none.
Referenced by appliance_convert_examine_actor::call(), construct::done_appliance(), construct::done_wiring(), and deploy_appliance_actor::use().
vpart_appliance_from_item()
vpart_id vpart_appliance_from_item (const itype_id & item_id)
Definition at line 45 of file veh_appliance.cpp.
 {
     for( const vpart_info &vpi : vehicles::parts::get_all() ) {
         if( vpi.base_item == item_id && vpi.has_flag( flag_APPLIANCE ) ) {
             return vpi.id;
         }
     }
     debugmsg( "item %s is not base item of any appliance!", item_id.c_str() );
     return vpart_ap_standing_lamp;
 }
References string_id< T >::c_str(), debugmsg, flag_APPLIANCE(), vehicles::parts::get_all(), string_id< T >::id(), and vpart_ap_standing_lamp.
Referenced by appliance_convert_examine_actor::call(), construct::done_appliance(), appliance_convert_examine_actor::finalize(), deploy_appliance_actor::info(), and deploy_appliance_actor::use().