Cataclysm DDA: src/vehicle_use.cpp File Reference
vehicle_use.cpp File Reference
#include "vehicle.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdlib>
#include <list>
#include <memory>
#include <string>
#include <tuple>
#include "action.h"
#include "activity_actor_definitions.h"
#include "activity_handlers.h"
#include "activity_type.h"
#include "avatar.h"
#include "character.h"
#include "clzones.h"
#include "color.h"
#include "creature.h"
#include "creature_tracker.h"
#include "debug.h"
#include "enums.h"
#include "game.h"
#include "gates.h"
#include "iexamine.h"
#include "inventory.h"
#include "item.h"
#include "itype.h"
#include "iuse.h"
#include "game_inventory.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "messages.h"
#include "monster.h"
#include "mtype.h"
#include "overmapbuffer.h"
#include "player_activity.h"
#include "pocket_type.h"
#include "requirements.h"
#include "ret_val.h"
#include "rng.h"
#include "smart_controller_ui.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "translations.h"
#include "ui.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_interact.h"
#include "veh_type.h"
#include "veh_utils.h"
#include "vehicle_selector.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include "weather.h"
Functions
void handbrake ()
static void add_electronic_toggle (vehicle &veh, veh_menu &menu, const std::string &name, const std::string &action, const std::string &flag)
Variables
static const activity_id ACT_REPAIR_ITEM ("ACT_REPAIR_ITEM")
static const activity_id ACT_START_ENGINES ("ACT_START_ENGINES")
static const ammotype ammo_battery ("battery")
static const damage_type_id damage_bash ("bash")
static const efftype_id effect_harnessed ("harnessed")
static const efftype_id effect_tied ("tied")
static const fault_id fault_engine_starter ("fault_engine_starter")
static const flag_id json_flag_FILTHY ("FILTHY")
static const furn_str_id furn_f_plant_harvest ("f_plant_harvest")
static const furn_str_id furn_f_plant_seed ("f_plant_seed")
static const itype_id fuel_type_battery ("battery")
static const itype_id fuel_type_muscle ("muscle")
static const itype_id fuel_type_none ("null")
static const itype_id fuel_type_wind ("wind")
static const itype_id itype_battery ("battery")
static const itype_id itype_detergent ("detergent")
static const itype_id itype_fungal_seeds ("fungal_seeds")
static const itype_id itype_large_repairkit ("large_repairkit")
static const itype_id itype_marloss_seed ("marloss_seed")
static const itype_id itype_null ("null")
static const itype_id itype_pseudo_magazine ("pseudo_magazine")
static const itype_id itype_small_repairkit ("small_repairkit")
static const itype_id itype_soldering_iron ("soldering_iron")
static const itype_id itype_water ("water")
static const itype_id itype_water_clean ("water_clean")
static const itype_id itype_water_faucet ("water_faucet")
static const itype_id itype_water_purifier ("water_purifier")
static const itype_id itype_welder ("welder")
static const itype_id itype_welder_crude ("welder_crude")
static const itype_id itype_welding_kit ("welding_kit")
static const quality_id qual_SCREW ("SCREW")
static const skill_id skill_mechanics ("mechanics")
static const ter_str_id ter_t_dirt ("t_dirt")
static const ter_str_id ter_t_dirtmound ("t_dirtmound")
static const vpart_id vpart_horn_bicycle ("horn_bicycle")
static const zone_type_id zone_type_VEHICLE_PATROL ("VEHICLE_PATROL")
Function Documentation
add_electronic_toggle()
static void add_electronic_toggle (vehicle & veh, veh_menu & menu, const std::string & name, const std::string & action, const std::string & flag) static
Definition at line 247 of file vehicle_use.cpp.
 {
     // fetch matching parts and abort early if none found
     const auto found = veh.get_avail_parts( flag );
     if( empty( found ) ) {
         return;
     }
     // determine target state - currently parts of similar type are all switched concurrently
     bool state = std::none_of( found.begin(), found.end(), []( const vpart_reference & vp ) {
         return vp.part().enabled;
     } );
     // can this menu option be selected by the user?
     // if toggled part potentially usable check if could be enabled now (sufficient fuel etc.)
     bool allow = !state || std::any_of( found.begin(), found.end(), []( const vpart_reference & vp ) {
         return vp.vehicle().can_enable( vp.part() );
     } );
     const std::string msg = state ? _( "Turn on %s" ) : colorize( _( "Turn off %s" ), c_pink );
     menu.add( string_format( msg, name ) )
     .enable( allow )
     .hotkey( action )
     .keep_menu_open()
     .on_submit( [found, state] {
         for( const vpart_reference &vp : found )
         {
             vehicle_part &e = vp.part();
             if( e.enabled != state ) {
                 add_msg( state ? _( "Turned on %s." ) : _( "Turned off %s." ), e.name() );
                 e.enabled = state;
             }
         }
     } );
 }
References _, action, veh_menu::add(), c_pink, colorize(), veh_menu_item::enable(), vehicle_part::enabled, vehicle::get_avail_parts(), veh_menu_item::hotkey(), veh_menu_item::keep_menu_open(), om_direction::name(), veh_menu_item::on_submit(), vpart_reference::part(), and string_format().
Referenced by vehicle::build_electronics_menu().
handbrake()
void handbrake ()
Definition at line 110 of file vehicle_use.cpp.
 {
     Character &player_character = get_player_character();
     const optional_vpart_position vp = get_map().veh_at( player_character.pos() );
     if( !vp ) {
         return;
     }
     vehicle *const veh = &vp->vehicle();
     add_msg( _( "You pull a handbrake." ) );
     veh->cruise_velocity = 0;
     if( veh->last_turn != 0_degrees && rng( 15, 60 ) * 100 < std::abs( veh->velocity ) ) {
         veh->skidding = true;
         add_msg( m_warning, _( "You lose control of %s." ), veh->name );
         veh->turn( veh->last_turn > 0_degrees ? 60_degrees : -60_degrees );
     } else {
         int braking_power = std::abs( veh->velocity ) / 2 + 10 * 100;
         if( std::abs( veh->velocity ) < braking_power ) {
             veh->stop();
         } else {
             int sgn = veh->velocity > 0 ? 1 : -1;
             veh->velocity = sgn * ( std::abs( veh->velocity ) - braking_power );
         }
     }
     player_character.set_moves( 0 );
 }
References _, abs(), add_msg(), vehicle::cruise_velocity, get_map(), get_player_character(), vehicle::last_turn, m_warning, vehicle::name, Creature::pos(), rng(), Creature::set_moves(), sgn(), vehicle::skidding, vehicle::stop(), vehicle::turn(), map::veh_at(), and vehicle::velocity.
Referenced by vehicle::build_interact_menu(), and game::do_regular_action().
Variable Documentation
ACT_REPAIR_ITEM
const activity_id ACT_REPAIR_ITEM("ACT_REPAIR_ITEM") ("ACT_REPAIR_ITEM") static
Referenced by vehicle::use_vehicle_tool().
ACT_START_ENGINES
const activity_id ACT_START_ENGINES("ACT_START_ENGINES") ("ACT_START_ENGINES") static
Referenced by vehicle::start_engines().
ammo_battery
const ammotype ammo_battery("battery") ("battery") static
Referenced by vehicle::tool_ammo_available(), and vehicle::use_vehicle_tool().
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by vehicle::operate_planter(), and vehicle::transform_terrain().
effect_harnessed
const efftype_id effect_harnessed("harnessed") ("harnessed") static
Referenced by vehicle::use_harness().
effect_tied
const efftype_id effect_tied("tied") ("tied") static
Referenced by vehicle::use_harness().
fault_engine_starter
const fault_id fault_engine_starter("fault_engine_starter") ("fault_engine_starter") static
Referenced by vehicle::start_engine().
fuel_type_battery
const itype_id fuel_type_battery("battery") ("battery") static
Referenced by vehicle::beeper_sound(), vehicle::build_electronics_menu(), vehicle::honk_horn(), vehicle::start_engine(), and vehicle::stop_engines().
fuel_type_muscle
const itype_id fuel_type_muscle("muscle") ("muscle") static
Referenced by vehicle::build_interact_menu(), vehicle::start_engine(), and vehicle::stop_engines().
fuel_type_none
const itype_id fuel_type_none("null") ("null") static
Referenced by vehicle::auto_select_fuel().
fuel_type_wind
const itype_id fuel_type_wind("wind") ("wind") static
Referenced by vehicle::start_engine(), and vehicle::stop_engines().
furn_f_plant_harvest
const furn_str_id furn_f_plant_harvest("f_plant_harvest") ("f_plant_harvest") static
Referenced by vehicle::operate_reaper().
furn_f_plant_seed
const furn_str_id furn_f_plant_seed("f_plant_seed") ("f_plant_seed") static
Referenced by vehicle::operate_planter().
itype_battery
const itype_id itype_battery("battery") ("battery") static
itype_detergent
const itype_id itype_detergent("detergent") ("detergent") static
Referenced by vehicle::use_dishwasher().
itype_fungal_seeds
const itype_id itype_fungal_seeds("fungal_seeds") ("fungal_seeds") static
Referenced by vehicle::operate_reaper().
itype_large_repairkit
const itype_id itype_large_repairkit("large_repairkit") ("large_repairkit") static
Referenced by vehicle::use_vehicle_tool().
itype_marloss_seed
const itype_id itype_marloss_seed("marloss_seed") ("marloss_seed") static
Referenced by vehicle::operate_reaper().
itype_null
const itype_id itype_null("null") ("null") static
Referenced by vehicle::reload_seeds().
itype_pseudo_magazine
const itype_id itype_pseudo_magazine("pseudo_magazine") ("pseudo_magazine") static
Referenced by vehicle::prepare_tool().
itype_small_repairkit
const itype_id itype_small_repairkit("small_repairkit") ("small_repairkit") static
Referenced by vehicle::use_vehicle_tool().
itype_soldering_iron
const itype_id itype_soldering_iron("soldering_iron") ("soldering_iron") static
Referenced by vehicle::use_vehicle_tool().
itype_water
const itype_id itype_water("water") ("water") static
Referenced by vehicle::use_autoclave(), vehicle::use_dishwasher(), and vehicle::use_washing_machine().
itype_water_clean
const itype_id itype_water_clean("water_clean") ("water_clean") static
Referenced by vehicle::use_autoclave(), vehicle::use_dishwasher(), and vehicle::use_washing_machine().
itype_water_faucet
const itype_id itype_water_faucet("water_faucet") ("water_faucet") static
Referenced by vpart_position::form_inventory().
itype_water_purifier
const itype_id itype_water_purifier("water_purifier") ("water_purifier") static
itype_welder
const itype_id itype_welder("welder") ("welder") static
Referenced by vehicle::use_vehicle_tool().
itype_welder_crude
const itype_id itype_welder_crude("welder_crude") ("welder_crude") static
Referenced by vehicle::use_vehicle_tool().
itype_welding_kit
const itype_id itype_welding_kit("welding_kit") ("welding_kit") static
Referenced by vehicle::use_vehicle_tool().
json_flag_FILTHY
const flag_id json_flag_FILTHY("FILTHY") ("FILTHY") static
qual_SCREW
const quality_id qual_SCREW("SCREW") ("SCREW") static
Referenced by vehicle::build_interact_menu().
skill_mechanics
const skill_id skill_mechanics("mechanics") ("mechanics") static
Referenced by vehicle::build_interact_menu(), and vehicle::smash_security_system().
ter_t_dirt
const ter_str_id ter_t_dirt("t_dirt") ("t_dirt") static
Referenced by vehicle::operate_planter().
ter_t_dirtmound
const ter_str_id ter_t_dirtmound("t_dirtmound") ("t_dirtmound") static
Referenced by vehicle::operate_planter().
vpart_horn_bicycle
const vpart_id vpart_horn_bicycle("horn_bicycle") ("horn_bicycle") static
Referenced by vehicle::honk_horn().
zone_type_VEHICLE_PATROL
const zone_type_id zone_type_VEHICLE_PATROL("VEHICLE_PATROL") ("VEHICLE_PATROL") static
Referenced by vehicle::autopilot_patrol_check().