Cataclysm DDA: src/vehicle_autodrive.cpp File Reference
vehicle_autodrive.cpp File Reference
#include "vehicle.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <map>
#include <memory>
#include <optional>
#include <queue>
#include <string>
#include <unordered_set>
#include <utility>
#include <vector>
#include "avatar.h"
#include "character.h"
#include "coordinates.h"
#include "creature_tracker.h"
#include "cuboid_rectangle.h"
#include "debug.h"
#include "enums.h"
#include "flood_fill.h"
#include "hash_utils.h"
#include "map.h"
#include "map_iterator.h"
#include "map_memory.h"
#include "mapdata.h"
#include "messages.h"
#include "point.h"
#include "tileray.h"
#include "translations.h"
#include "type_id.h"
#include "veh_type.h"
#include "vpart_position.h"
Classes
struct vehicle_profile
Data type representing the convex hull of a vehicle under a particular rotation.
struct navigation_step
Data type describing how what driving actions to perform at a given location in order to follow the current path to destination.
struct node_address
The address of a navigation node, i.e.
struct node_address_hasher
struct scored_address
struct navigation_node
struct coord_transformation
struct point_queue
struct auto_navigation_data
Data structure that caches all the data needed in order to navigate from one OMT to the next OMT along the path to destination.
class vehicle::autodrive_controller
Enumerations
enum class orientation : int8_t { d0 = 0 }
Data type representing a vehicle orientation, which corresponds to an angle that is a multiple of TURNING_INCREMENT degrees, measured from the x axis.
enum class quad_rotation : int { d0 = 0 , d90 , d180 , d270 }
enum class collision_check_result : int { ok , no_visibility , close_obstacle , slow_down }
Functions
static const std::array< orientation, NUM_ORIENTATIONS > & all_orientations ()
static orientation normalize_orientation (int steering_turns)
static orientation to_orientation (units::angle angle)
static std::string to_string (orientation dir)
static orientation operator- (const orientation &dir)
static orientation operator+ (const orientation &dir1, const orientation &dir2)
static orientation operator- (const orientation &dir1, const orientation &dir2)
static orientation operator+ (const orientation &dir, int steering_turns)
static quad_rotation operator- (const quad_rotation &rot)
static quad_rotation operator+ (const quad_rotation &rot1, const quad_rotation &rot2)
static quad_rotation operator- (const quad_rotation &rot1, const quad_rotation &rot2)
static orientation operator+ (const orientation &dir, const quad_rotation &rot)
static orientation & operator+= (orientation &dir, const quad_rotation &rot)
static units::angle to_angle (const orientation &dir)
static int orientation_diff (const orientation &dir1, const orientation &dir2)
static quad_rotation to_quad_rotation (const point &pt)
static node_address make_node_address (point pos, orientation dir)
static orientation approx_orientation (int dx, int dy)
static point rotate (point p, quad_rotation rotation)
static int signum (int val)
static navigation_node make_start_node (const node_address &start, const vehicle &driven_veh)
Variables
static const ter_str_id ter_t_open_air ("t_open_air")
static constexpr int OMT_SIZE = coords::map_squares_per(coords::omt)
static constexpr int NAV_MAP_NUM_OMT = 2
static constexpr int NAV_MAP_SIZE_X = NAV_MAP_NUM_OMT * OMT_SIZE
static constexpr int NAV_MAP_SIZE_Y = OMT_SIZE
static constexpr int NAV_VIEW_PADDING = OMT_SIZE
static constexpr int NAV_VIEW_SIZE_X = NAV_MAP_SIZE_X + 2 * NAV_VIEW_PADDING
static constexpr int NAV_VIEW_SIZE_Y = NAV_MAP_SIZE_Y + 2 * NAV_VIEW_PADDING
static constexpr int TURNING_INCREMENT = 15
static constexpr int NUM_ORIENTATIONS = 360 / TURNING_INCREMENT
static constexpr int MIN_SPEED_TPS = 1
static constexpr int MAX_SPEED_TPS = 3
static constexpr int VMIPH_PER_TPS = static_cast<int>(vehicles::vmiph_per_tile)
Enumeration Type Documentation
collision_check_result
enum collision_check_result : int strong
Enumerator
ok
no_visibility
close_obstacle
slow_down
Definition at line 359 of file vehicle_autodrive.cpp.
                                   : int {
     ok,
     no_visibility,
     close_obstacle,
     slow_down
 };
orientation
enum orientation : int8_t strong
Data type representing a vehicle orientation, which corresponds to an angle that is a multiple of TURNING_INCREMENT degrees, measured from the x axis.
Range: [0, NUM_ORIENTATIONS)
Enumerator
d0
Definition at line 161 of file vehicle_autodrive.cpp.
                        : int8_t {
     d0 = 0,
 };
quad_rotation
enum quad_rotation : int strong
Enumerator
d0
d90
d180
d270
Definition at line 168 of file vehicle_autodrive.cpp.
                          : int {
     d0 = 0, d90, d180, d270,
 };
Function Documentation
all_orientations()
static const std::array<orientation, NUM_ORIENTATIONS>& all_orientations () static
Definition at line 402 of file vehicle_autodrive.cpp.
 {
     static const auto orientations_array = [] {
         std::array<orientation, NUM_ORIENTATIONS> ret;
         for( int i = 0; i < NUM_ORIENTATIONS; i++ )
         {
             ret[i] = static_cast<orientation>( i );
         }
         return ret;
     }();
     return orientations_array;
 }
References NUM_ORIENTATIONS, and cata::hash64_detail::ret.
Referenced by vehicle::autodrive_controller::compute_valid_positions(), and vehicle::autodrive_controller::precompute_data().
approx_orientation()
static orientation approx_orientation (int dx, int dy) static
Definition at line 526 of file vehicle_autodrive.cpp.
 {
     orientation ret = orientation::d0;
     if( dy < 0 ) {
         dx *= -1;
         dy *= -1;
         ret += quad_rotation::d180;
     }
     if( dx < 0 ) {
         std::swap( dx, dy );
         dy *= -1;
         ret += quad_rotation::d90;
     }
     if( dy > dx ) {
         ret = ret + quad_rotation::d90 - approx_orientation( dy, dx );
     } else if( dy > 0 ) {
         static const auto atan_table = [] {
             constexpr int table_size = 101;
             std::array<orientation, table_size> table;
             for( int i = 0; i <  table_size; i++ )
             {
                 table[i] = to_orientation( units::from_radians( std::atan( 1.0 * i /
                                            ( table_size - 1 ) ) ) );
             }
             return table;
         }();
         ret = ret + atan_table[ dy * 100 / dx ];
     }
     return ret;
 }
References d0, d180, d90, units::from_radians(), cata::hash64_detail::ret, cata::swap(), and to_orientation().
Referenced by vehicle::autodrive_controller::compute_node_score().
make_node_address()
static node_address make_node_address (point pos, orientation dir) static
Definition at line 516 of file vehicle_autodrive.cpp.
 {
     return { static_cast<int16_t>( pos.x ), static_cast<int16_t>( pos.y ), dir };
 }
References math_opers::pos().
Referenced by coord_transformation::transform().
make_start_node()
static navigation_node make_start_node (const node_address & start, const vehicle & driven_veh) static
Definition at line 952 of file vehicle_autodrive.cpp.
 {
     navigation_node ret;
     ret.prev = start;
     ret.cost = 0;
     ret.tileray_steps = driven_veh.face.get_steps();
     ret.speed = driven_veh.velocity;
     ret.target_speed_tps = 0;
     ret.is_goal = false;
     return ret;
 }
References vehicle::face, tileray::get_steps(), cata::hash64_detail::ret, and vehicle::velocity.
Referenced by vehicle::autodrive_controller::compute_path().
normalize_orientation()
static orientation normalize_orientation (int steering_turns) static
Definition at line 418 of file vehicle_autodrive.cpp.
 {
     steering_turns %= NUM_ORIENTATIONS;
     // beware that x % N < 0 when x < 0
     if( steering_turns < 0 ) {
         steering_turns += NUM_ORIENTATIONS;
     }
     return static_cast<orientation>( steering_turns );
 }
References NUM_ORIENTATIONS.
Referenced by operator+(), and to_orientation().
operator+() [1/4]
static orientation operator+ (const orientation & dir, const quad_rotation & rot) static
Definition at line 476 of file vehicle_autodrive.cpp.
 {
     return dir + static_cast<orientation>( static_cast<int>( rot ) *  NUM_ORIENTATIONS / 4 );
 }
References NUM_ORIENTATIONS.
operator+() [2/4]
static orientation operator+ (const orientation & dir, int steering_turns) static
Definition at line 456 of file vehicle_autodrive.cpp.
 {
     return dir + normalize_orientation( steering_turns );
 }
References normalize_orientation().
operator+() [3/4]
static orientation operator+ (const orientation & dir1, const orientation & dir2) static
Definition at line 445 of file vehicle_autodrive.cpp.
 {
     return static_cast<orientation>( ( static_cast<int>( dir1 ) + static_cast<int>
                                        ( dir2 ) ) % NUM_ORIENTATIONS );
 }
References NUM_ORIENTATIONS.
operator+() [4/4]
static quad_rotation operator+ (const quad_rotation & rot1, const quad_rotation & rot2) static
Definition at line 466 of file vehicle_autodrive.cpp.
 {
     return static_cast<quad_rotation>( ( static_cast<int>( rot1 ) + static_cast<int>( rot2 ) ) % 4 );
 }
operator+=()
static orientation& operator+= (orientation & dir, const quad_rotation & rot) static
Definition at line 481 of file vehicle_autodrive.cpp.
 {
     return dir = dir + rot;
 }
operator-() [1/4]
static orientation operator- (const orientation & dir) static
Definition at line 439 of file vehicle_autodrive.cpp.
 {
     return static_cast<orientation>( ( NUM_ORIENTATIONS - static_cast<int>
                                        ( dir ) ) % NUM_ORIENTATIONS );
 }
References NUM_ORIENTATIONS.
operator-() [2/4]
static orientation operator- (const orientation & dir1, const orientation & dir2) static
Definition at line 451 of file vehicle_autodrive.cpp.
 {
     return dir1 + -dir2;
 }
operator-() [3/4]
static quad_rotation operator- (const quad_rotation & rot) static
Definition at line 461 of file vehicle_autodrive.cpp.
 {
     return static_cast<quad_rotation>( ( 4 - static_cast<int>( rot ) ) % 4 );
 }
operator-() [4/4]
static quad_rotation operator- (const quad_rotation & rot1, const quad_rotation & rot2) static
Definition at line 471 of file vehicle_autodrive.cpp.
 {
     return rot1 + -rot2;
 }
orientation_diff()
static int orientation_diff (const orientation & dir1, const orientation & dir2) static
Definition at line 495 of file vehicle_autodrive.cpp.
 {
     return static_cast<int>( dir1 - dir2 + quad_rotation::d180 ) - NUM_ORIENTATIONS / 2;
 }
References d180, and NUM_ORIENTATIONS.
Referenced by vehicle::autodrive_controller::compute_node_score(), and vehicle::do_autodrive().
rotate()
static point rotate (point p, quad_rotation rotation) static
Definition at line 557 of file vehicle_autodrive.cpp.
 {
     switch( rotation ) {
         case quad_rotation::d0:
             return p;
         case quad_rotation::d90:
             return { -p.y - 1, p.x };
         case quad_rotation::d180:
             return { -p.x - 1, -p.y - 1 };  // NOLINT(cata-use-point-arithmetic)
         case quad_rotation::d270:
             return { p.y, -p.x - 1 };
     }
     return p;
 }
References d0, d180, d270, d90, point::x, and point::y.
Referenced by om_direction::displace(), veh_interact::display_veh(), map::draw_lab(), input_context::get_direction(), input_context::get_direction_rel_ms(), vehicle::get_display_of_tile(), vehicle::immediate_path(), mapgendata::mapgendata(), mutable_overmap_placement_rule_remainder::outward_joins(), mutable_overmap_placement_rule_remainder::pieces(), mutable_overmap_placement_rule_remainder::positions(), om_direction::rotate(), science_room(), and coord_transformation::transform().
signum()
static int signum (int val) static
Definition at line 597 of file vehicle_autodrive.cpp.
 {
     return ( 0 < val ) - ( val < 0 );
 }
Referenced by vehicle::autodrive_controller::compute_profile(), and vehicle::do_autodrive().
to_angle()
static units::angle to_angle (const orientation & dir) static
Definition at line 486 of file vehicle_autodrive.cpp.
 {
     return units::from_degrees( static_cast<int>( dir ) * TURNING_INCREMENT );
 }
References units::from_degrees(), and TURNING_INCREMENT.
Referenced by vehicle::autodrive_controller::compute_profile().
to_orientation()
static orientation to_orientation (units::angle angle) static
Definition at line 428 of file vehicle_autodrive.cpp.
 {
     return normalize_orientation( std::lround( units::to_degrees(
                                       angle ) / TURNING_INCREMENT ) );
 }
References normalize_orientation(), units::to_degrees(), and TURNING_INCREMENT.
Referenced by approx_orientation(), vehicle::autodrive_controller::check_collision_zone(), vehicle::autodrive_controller::compute_path(), vehicle::do_autodrive(), and vehicle::get_debug_overlay_data().
to_quad_rotation()
static quad_rotation to_quad_rotation (const point & pt) static
Definition at line 503 of file vehicle_autodrive.cpp.
 {
     if( pt.x > 0 ) {
         return quad_rotation::d0;
     } else if( pt.x < 0 ) {
         return quad_rotation::d180;
     } else if( pt.y > 0 ) {
         return quad_rotation::d90;
     } else {
         return quad_rotation::d270;
     }
 }
References d0, d180, d270, d90, point::x, and point::y.
Referenced by vehicle::autodrive_controller::compute_coordinates(), and vehicle::autodrive_controller::compute_goal_zone().
to_string()
static std::string to_string (orientation dir) static
Definition at line 434 of file vehicle_autodrive.cpp.
 {
     return std::to_string( static_cast<int>( dir ) );
 }
Referenced by vehicle::get_debug_overlay_data().
Variable Documentation
MAX_SPEED_TPS
constexpr int MAX_SPEED_TPS = 3 static constexpr
Definition at line 153 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::precompute_data().
MIN_SPEED_TPS
constexpr int MIN_SPEED_TPS = 1 static constexpr
Definition at line 152 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_next_step(), and vehicle::autodrive_controller::reduce_speed().
NAV_MAP_NUM_OMT
constexpr int NAV_MAP_NUM_OMT = 2 static constexpr
Definition at line 143 of file vehicle_autodrive.cpp.
NAV_MAP_SIZE_X
constexpr int NAV_MAP_SIZE_X = NAV_MAP_NUM_OMT * OMT_SIZE static constexpr
Definition at line 144 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_coordinates(), vehicle::autodrive_controller::compute_valid_positions(), and vehicle::get_debug_overlay_data().
NAV_MAP_SIZE_Y
constexpr int NAV_MAP_SIZE_Y = OMT_SIZE static constexpr
Definition at line 145 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_coordinates(), vehicle::autodrive_controller::compute_goal_zone(), vehicle::autodrive_controller::compute_valid_positions(), and vehicle::get_debug_overlay_data().
NAV_VIEW_PADDING
constexpr int NAV_VIEW_PADDING = OMT_SIZE static constexpr
Definition at line 146 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_coordinates().
NAV_VIEW_SIZE_X
constexpr int NAV_VIEW_SIZE_X = NAV_MAP_SIZE_X + 2 * NAV_VIEW_PADDING static constexpr
Definition at line 147 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_coordinates(), vehicle::autodrive_controller::compute_obstacles(), and vehicle::get_debug_overlay_data().
NAV_VIEW_SIZE_Y
constexpr int NAV_VIEW_SIZE_Y = NAV_MAP_SIZE_Y + 2 * NAV_VIEW_PADDING static constexpr
Definition at line 148 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_coordinates(), vehicle::autodrive_controller::compute_obstacles(), and vehicle::get_debug_overlay_data().
NUM_ORIENTATIONS
constexpr int NUM_ORIENTATIONS = 360 / TURNING_INCREMENT static constexpr
Definition at line 150 of file vehicle_autodrive.cpp.
Referenced by all_orientations(), vehicle::autodrive_controller::compute_goal_zone(), normalize_orientation(), operator+(), operator-(), and orientation_diff().
OMT_SIZE
constexpr int OMT_SIZE = coords::map_squares_per(coords::omt) static constexpr
Definition at line 142 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::compute_coordinates(), vehicle::autodrive_controller::compute_goal_zone(), vehicle::autodrive_controller::compute_next_nodes(), vehicle::autodrive_controller::compute_node_score(), and vehicle::get_debug_overlay_data().
ter_t_open_air
const ter_str_id ter_t_open_air("t_open_air") ("t_open_air") static
Referenced by vehicle::autodrive_controller::check_drivable().
TURNING_INCREMENT
constexpr int TURNING_INCREMENT = 15 static constexpr
Definition at line 149 of file vehicle_autodrive.cpp.
Referenced by to_angle(), and to_orientation().
VMIPH_PER_TPS
constexpr int VMIPH_PER_TPS = static_cast<int>(vehicles::vmiph_per_tile) static constexpr
Definition at line 154 of file vehicle_autodrive.cpp.
Referenced by vehicle::autodrive_controller::check_collision_zone(), vehicle::autodrive_controller::check_safe_speed(), vehicle::autodrive_controller::compute_next_nodes(), vehicle::do_autodrive(), and vehicle::autodrive_controller::precompute_data().