Cataclysm DDA: src/vehicle.h File Reference
vehicle.h File Reference
#include <array>
#include <climits>
#include <cstddef>
#include <functional>
#include <iosfwd>
#include <list>
#include <map>
#include <new>
#include <optional>
#include <set>
#include <stack>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include <vector>
#include "active_item_cache.h"
#include "calendar.h"
#include "character_id.h"
#include "clzones.h"
#include "colony.h"
#include "coordinates.h"
#include "damage.h"
#include "game_constants.h"
#include "item.h"
#include "item_group.h"
#include "item_location.h"
#include "item_stack.h"
#include "line.h"
#include "map.h"
#include "point.h"
#include "tileray.h"
#include "type_id.h"
#include "units.h"
#include "vpart_range.h"
Classes
struct rider_data
struct enum_traits< part_status_flag >
struct smart_controller_cache
struct smart_controller_config
struct veh_collision
struct vpart_edge_info
class vehicle_stack
class towing_data
struct bounding_box
class turret_cpu
struct vehicle_part
Structure, describing vehicle part (i.e., wheel, seat)
struct vehicle_part::carried_part_data
class turret_data
struct label
Struct used for storing labels (easier to json opposed to a std::map<point, std::string>)
class vpart_display
class vehicle
A vehicle as a whole with all its components.
struct vehicle::rackable_vehicle
struct vehicle::unrackable_vehicle
class RemovePartHandler
class DefaultRemovePartHandler
class MapgenRemovePartHandler
Namespaces
catacurses
Contains the curses interface used by the whole game.
vehicles
Macros
#define CATA_SRC_VEHICLE_H
Enumerations
enum class part_status_flag : int { any = 0 , working = 1 << 0 , available = 1 << 1 , enabled = 1 << 2 }
enum veh_coll_type : int {
veh_coll_nothing , veh_coll_body , veh_coll_veh , veh_coll_bashable ,
veh_coll_other , num_veh_coll_types
}
enum towing_point_side : int { TOW_FRONT , TOW_SIDE , TOW_BACK , NUM_TOW_TYPES }
enum class vp_flag : uint32_t {
none = 0 , passenger_flag = 1 , animal_flag = 2 , carried_flag = 4 ,
carrying_flag = 8 , tracked_flag = 16 , linked_flag = 32 , unsalvageable_flag = 64
}
enum class autodrive_result : int { ok , abort , finished }
Functions
void handbrake ()
void practice_athletic_proficiency (Character &p)
void practice_pilot_proficiencies (Character &p, bool &boating)
float get_collision_factor (float delta_v)
int mps_to_vmiph (double mps)
double vmiph_to_mps (int vmiph)
int cmps_to_vmiph (int cmps)
int vmiph_to_cmps (int vmiph)
Variables
constexpr double vehicles::rolling_constant_to_variable = 33.33
constexpr float vehicles::vmiph_per_tile = 400.0f
constexpr units::angle vehicles::steer_increment = 15_degrees
constexpr int SCATTER_DISTANCE = 3
constexpr int k_mvel = 200
constexpr float accel_g = 9.81f
Macro Definition Documentation
CATA_SRC_VEHICLE_H
#define CATA_SRC_VEHICLE_H
Definition at line 3 of file vehicle.h.
Enumeration Type Documentation
autodrive_result
enum autodrive_result : int strong
Enumerator
ok
abort
finished
Definition at line 698 of file vehicle.h.
                             : int {
     // the driver successfully performed course correction or simply did nothing
     // in order to keep going forward
     ok,
     // something bad happened (navigation error, crash, loss of visibility, or just
     // couldn't find a way around obstacles) and autodrive cannot continue
     abort,
     // arrived at the destination
     finished
 };
part_status_flag
enum part_status_flag : int strong
Enumerator
any
working
available
enabled
Definition at line 99 of file vehicle.h.
                             : int {
     any = 0,
     working = 1 << 0,
     available = 1 << 1,
     enabled = 1 << 2
 };
towing_point_side
enum towing_point_side : int
Enumerator
TOW_FRONT
TOW_SIDE
TOW_BACK
NUM_TOW_TYPES
Definition at line 186 of file vehicle.h.
                        : int {
     TOW_FRONT,
     TOW_SIDE,
     TOW_BACK,
     NUM_TOW_TYPES
 };
veh_coll_type
enum veh_coll_type : int
Enumerator
veh_coll_nothing
veh_coll_body
veh_coll_veh
veh_coll_bashable
veh_coll_other
num_veh_coll_types
Definition at line 111 of file vehicle.h.
                    : int {
     veh_coll_nothing,  // 0 - nothing,
     veh_coll_body,     // 1 - monster/player/npc
     veh_coll_veh,      // 2 - vehicle
     veh_coll_bashable, // 3 - bashable
     veh_coll_other,    // 4 - other
     num_veh_coll_types
 };
vp_flag
enum vp_flag : uint32_t strong
Enumerator
none
passenger_flag
animal_flag
carried_flag
carrying_flag
tracked_flag
linked_flag
unsalvageable_flag
Definition at line 228 of file vehicle.h.
                    : uint32_t {
     none = 0,
     passenger_flag = 1,
     animal_flag = 2,
     carried_flag = 4,
     carrying_flag = 8,
     tracked_flag = 16, //carried vehicle part with tracking enabled
     linked_flag = 32, //a cable is attached to this
     unsalvageable_flag = 64 //install components are unsalvageable
 };
Function Documentation
cmps_to_vmiph()
int cmps_to_vmiph (int cmps)
Definition at line 97 of file vehicle_move.cpp.
 {
     return cmps * mps_to_miph;
 }
References mps_to_miph.
Referenced by vehicle::ground_acceleration(), vehicle::rotor_acceleration(), and vehicle::water_acceleration().
get_collision_factor()
float get_collision_factor (float delta_v)
Definition at line 1623 of file vehicle_move.cpp.
 {
     if( std::abs( delta_v ) <= 31 ) {
         return 1 - ( 0.9 * std::abs( delta_v ) ) / 31;
     } else {
         return 0.1;
     }
 }
References abs().
Referenced by map::vehicle_vehicle_collision().
handbrake()
void handbrake ()
Definition at line 110 of file vehicle_use.cpp.
 {
     Character &player_character = get_player_character();
     const optional_vpart_position vp = get_map().veh_at( player_character.pos() );
     if( !vp ) {
         return;
     }
     vehicle *const veh = &vp->vehicle();
     add_msg( _( "You pull a handbrake." ) );
     veh->cruise_velocity = 0;
     if( veh->last_turn != 0_degrees && rng( 15, 60 ) * 100 < std::abs( veh->velocity ) ) {
         veh->skidding = true;
         add_msg( m_warning, _( "You lose control of %s." ), veh->name );
         veh->turn( veh->last_turn > 0_degrees ? 60_degrees : -60_degrees );
     } else {
         int braking_power = std::abs( veh->velocity ) / 2 + 10 * 100;
         if( std::abs( veh->velocity ) < braking_power ) {
             veh->stop();
         } else {
             int sgn = veh->velocity > 0 ? 1 : -1;
             veh->velocity = sgn * ( std::abs( veh->velocity ) - braking_power );
         }
     }
     player_character.set_moves( 0 );
 }
References _, abs(), add_msg(), vehicle::cruise_velocity, get_map(), get_player_character(), vehicle::last_turn, m_warning, vehicle::name, Creature::pos(), rng(), Creature::set_moves(), sgn(), vehicle::skidding, vehicle::stop(), vehicle::turn(), map::veh_at(), and vehicle::velocity.
Referenced by vehicle::build_interact_menu(), and game::do_regular_action().
mps_to_vmiph()
int mps_to_vmiph (double mps)
Definition at line 86 of file vehicle_move.cpp.
 {
     return mps * mps_to_miph * mi_to_vmi;
 }
References mi_to_vmi, and mps_to_miph.
Referenced by vehicle::act_on_map(), vehicle::max_ground_velocity(), vehicle::max_rotor_velocity(), vehicle::max_water_velocity(), vehicle::safe_ground_velocity(), vehicle::safe_rotor_velocity(), vehicle::safe_water_velocity(), and vehicle::slowdown().
practice_athletic_proficiency()
void practice_athletic_proficiency (Character & p)
Definition at line 4960 of file vehicle.cpp.
 {
     // Perform athletics practice
     p.practice( skill_swimming, 1 );
     // We are already a master athlete, practice has no effect
     if( p.has_proficiency( proficiency_prof_athlete_master ) ) {
         return;
     }
     // We have no athletic experience
     if( !p.has_proficiency( proficiency_prof_athlete_basic ) ) {
         p.practice_proficiency( proficiency_prof_athlete_basic, 1_seconds );
         return;
     }
     // We know athletics, but aren't an expert yet
     else if( !p.has_proficiency( proficiency_prof_athlete_expert ) ) {
         p.practice_proficiency( proficiency_prof_athlete_expert, 1_seconds );
         return;
     }
     // We're an expert, so lets practice to become a master athlete
     else {
         p.practice_proficiency( proficiency_prof_athlete_master, 1_seconds );
         return;
     }
 }
References Character::has_proficiency(), Character::practice(), Character::practice_proficiency(), proficiency_prof_athlete_basic, proficiency_prof_athlete_expert, proficiency_prof_athlete_master, and skill_swimming.
Referenced by vehicle::consume_fuel().
practice_pilot_proficiencies()
void practice_pilot_proficiencies (Character & p, bool & boating)
Definition at line 4950 of file vehicle.cpp.
 {
     if( !p.has_proficiency( proficiency_prof_driver ) && !boating ) {
         p.practice_proficiency( proficiency_prof_driver, 1_seconds );
     }
     if( !p.has_proficiency( proficiency_prof_boat_pilot ) && boating ) {
         p.practice_proficiency( proficiency_prof_boat_pilot, 1_seconds );
     }
 }
References Character::has_proficiency(), Character::practice_proficiency(), proficiency_prof_boat_pilot, and proficiency_prof_driver.
Referenced by vehicle::consume_fuel().
vmiph_to_cmps()
int vmiph_to_cmps (int vmiph)
Definition at line 102 of file vehicle_move.cpp.
 {
     return vmiph / mps_to_miph;
 }
References mps_to_miph.
Referenced by vehicle::ground_acceleration(), and vehicle::water_acceleration().
vmiph_to_mps()
double vmiph_to_mps (int vmiph)
Definition at line 92 of file vehicle_move.cpp.
 {
     return vmiph / mps_to_miph / mi_to_vmi;
 }
References mi_to_vmi, and mps_to_miph.
Referenced by vehicle::act_on_map(), and vehicle::slowdown().
Variable Documentation
accel_g
constexpr float accel_g = 9.81f constexpr
Definition at line 226 of file vehicle.h.
Referenced by vehicle::coeff_rolling_drag().
k_mvel
constexpr int k_mvel = 200 constexpr
Definition at line 97 of file vehicle.h.
SCATTER_DISTANCE
constexpr int SCATTER_DISTANCE = 3 constexpr
Definition at line 95 of file vehicle.h.
Referenced by vehicle::break_off().