Cataclysm DDA: src/vehicle_display.cpp File Reference
vehicle_display.cpp File Reference
#include "vehicle.h"
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <optional>
#include <set>
#include <string>
#include "calendar.h"
#include "cata_utility.h"
#include "catacharset.h"
#include "color.h"
#include "cursesdef.h"
#include "debug.h"
#include "itype.h"
#include "options.h"
#include "output.h"
#include "string_formatter.h"
#include "translations.h"
#include "units.h"
#include "units_utility.h"
#include "veh_type.h"
#include "vpart_position.h"
Functions
static const std::string part_location_structure ("structure")
Variables
static const ammotype ammo_battery ("battery")
static const itype_id fuel_type_muscle ("muscle")
static const itype_id itype_battery ("battery")
Function Documentation
part_location_structure()
static const std::string part_location_structure ("structure") static
Referenced by vehicle::print_part_list().
Variable Documentation
ammo_battery
const ammotype ammo_battery("battery") ("battery") static
Referenced by vehicle::print_part_list().
fuel_type_muscle
const itype_id fuel_type_muscle("muscle") ("muscle") static
Referenced by vehicle::print_fuel_indicators().
itype_battery
const itype_id itype_battery("battery") ("battery") static
Referenced by vehicle::print_fuel_indicator(), and vehicle::print_part_list().