Cataclysm DDA: src/vehicle.cpp File Reference
vehicle.cpp File Reference
#include "vehicle.h"
#include "vpart_position.h"
#include "vpart_range.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <complex>
#include <cstdint>
#include <cstdlib>
#include <list>
#include <memory>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include "activity_handlers.h"
#include "activity_type.h"
#include "avatar.h"
#include "bionics.h"
#include "cata_assert.h"
#include "cata_utility.h"
#include "character.h"
#include "clzones.h"
#include "colony.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "creature.h"
#include "creature_tracker.h"
#include "cuboid_rectangle.h"
#include "debug.h"
#include "enum_traits.h"
#include "enums.h"
#include "event.h"
#include "event_bus.h"
#include "explosion.h"
#include "faction.h"
#include "field_type.h"
#include "flag.h"
#include "game.h"
#include "item.h"
#include "item_group.h"
#include "itype.h"
#include "json.h"
#include "json_loader.h"
#include "make_static.h"
#include "map.h"
#include "map_iterator.h"
#include "mapbuffer.h"
#include "mapdata.h"
#include "material.h"
#include "math_defines.h"
#include "messages.h"
#include "monster.h"
#include "move_mode.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "overmapbuffer.h"
#include "pimpl.h"
#include "player_activity.h"
#include "pocket_type.h"
#include "ret_val.h"
#include "rng.h"
#include "sounds.h"
#include "string_formatter.h"
#include "submap.h"
#include "translations.h"
#include "units_utility.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle_selector.h"
#include "weather.h"
#include "weather_gen.h"
#include "weather_type.h"
Classes
struct drag_column
Functions
static const std::string part_location_structure ("structure")
static const std::string part_location_center ("center")
static const std::string part_location_onroof ("on_roof")
static const std::string flag_E_COMBUSTION ("E_COMBUSTION")
static const std::string flag_APPLIANCE ("APPLIANCE")
static const std::string flag_WIRING ("WIRING")
static bool is_sm_tile_outside (const tripoint &real_global_pos)
static bool is_sm_tile_over_water (const tripoint &real_global_pos)
static int get_turn_from_angle (const units::angle &angle, const tripoint &vehpos, const tripoint &target, bool reverse=false)
static double simple_cubic_solution (double a, double b, double c, double d)
static double tile_to_width (int tiles)
void practice_pilot_proficiencies (Character &p, bool &boating)
void practice_athletic_proficiency (Character &p)
static double weighted_power_loss (const std::map< vpart_reference, float > &batteries)
static void distribute_charge_evenly (const std::map< vpart_reference, float > &batteries, int64_t charge_kj, int64_t total_capacity_kj)
Variables
static const activity_id ACT_VEHICLE ("ACT_VEHICLE")
static const ammotype ammo_battery ("battery")
static const bionic_id bio_jointservo ("bio_jointservo")
static const damage_type_id damage_heat ("heat")
static const damage_type_id damage_pure ("pure")
static const efftype_id effect_harnessed ("harnessed")
static const efftype_id effect_winded ("winded")
static const fault_id fault_engine_immobiliser ("fault_engine_immobiliser")
static const itype_id fuel_type_animal ("animal")
static const itype_id fuel_type_battery ("battery")
static const itype_id fuel_type_mana ("mana")
static const itype_id fuel_type_muscle ("muscle")
static const itype_id fuel_type_plutonium_cell ("plut_cell")
static const itype_id fuel_type_wind ("wind")
static const itype_id itype_battery ("battery")
static const itype_id itype_plut_cell ("plut_cell")
static const itype_id itype_wall_wiring ("wall_wiring")
static const itype_id itype_water ("water")
static const itype_id itype_water_clean ("water_clean")
static const itype_id itype_water_faucet ("water_faucet")
static const itype_id itype_water_purifier ("water_purifier")
static const json_character_flag json_flag_MUSCLE_VEH_BOOST ("MUSCLE_VEH_BOOST")
static const proficiency_id proficiency_prof_aircraft_mechanic ("prof_aircraft_mechanic")
static const proficiency_id proficiency_prof_athlete_basic ("prof_athlete_basic")
static const proficiency_id proficiency_prof_athlete_expert ("prof_athlete_expert")
static const proficiency_id proficiency_prof_athlete_master ("prof_athlete_master")
static const proficiency_id proficiency_prof_boat_pilot ("prof_boat_pilot")
static const proficiency_id proficiency_prof_driver ("prof_driver")
static const skill_id skill_swimming ("swimming")
static const vpart_id vpart_power_cord ("power_cord")
static const vproto_id vehicle_prototype_none ("none")
static const zone_type_id zone_type_VEHICLE_PATROL ("VEHICLE_PATROL")
static const translation power_grid_name = to_translation("power grid")
static const int MAX_WIRE_VEHICLE_SIZE = 24
static constexpr int minrow = -122
static constexpr int maxrow = 122
Function Documentation
distribute_charge_evenly()
static void distribute_charge_evenly (const std::map< vpart_reference, float > & batteries, int64_t charge_kj, int64_t total_capacity_kj) static
Definition at line 5477 of file vehicle.cpp.
 {
     int64_t distributed = 0;
     for( const std::pair<const vpart_reference, float> &pair : batteries ) {
         vehicle_part &vp = pair.first.part();
         const int bat_capacity = vp.ammo_capacity( ammo_battery );
         const float fraction = static_cast<float>( bat_capacity ) / total_capacity_kj;
         const int portion = charge_kj * fraction;
         vp.ammo_set( fuel_type_battery, portion );
         distributed += portion;
     }
     if( distributed < charge_kj ) { // dump indivisible remainder sequentially
         for( const std::pair<const vpart_reference, float> &pair : batteries ) {
             vehicle_part &vp = pair.first.part();
             const int64_t bat_charge = vp.ammo_remaining();
             const int64_t bat_capacity = vp.ammo_capacity( ammo_battery );
             const int chargeable = std::min( charge_kj - distributed, bat_capacity - bat_charge );
             vp.ammo_set( fuel_type_battery, bat_charge + chargeable );
             distributed += chargeable;
             if( distributed >= charge_kj ) {
                 break;
             }
         }
     }
     if( distributed < charge_kj ) { // safeguard, this shouldn't happen
         debugmsg( "no capacity to distribute distribute %d kJ", charge_kj - distributed );
     }
 }
References ammo_battery, vehicle_part::ammo_capacity(), vehicle_part::ammo_remaining(), vehicle_part::ammo_set(), debugmsg, fuel_type_battery, and min().
Referenced by vehicle::charge_battery(), and vehicle::discharge_battery().
flag_APPLIANCE()
static const std::string flag_APPLIANCE ("APPLIANCE") static
Referenced by vehicle::find_and_split_vehicles(), vehicle::is_appliance(), vehicle::is_powergrid(), and vehicle::split_vehicles().
flag_E_COMBUSTION()
static const std::string flag_E_COMBUSTION ("E_COMBUSTION") static
Referenced by vehicle::is_engine_type_combustion().
flag_WIRING()
static const std::string flag_WIRING ("WIRING") static
Referenced by vehicle::is_powergrid(), vehicle::merge_appliance_into_grid(), and vehicle::split_vehicles().
get_turn_from_angle()
static int get_turn_from_angle (const units::angle & angle, const tripoint & vehpos, const tripoint & target, bool reverse = false) static
Definition at line 707 of file vehicle.cpp.
 {
     if( angle > 10.0_degrees && angle <= 45.0_degrees ) {
         return reverse ? 4 : 1;
     } else if( angle > 45.0_degrees && angle <= 90.0_degrees ) {
         return 3;
     } else if( angle > 90.0_degrees && angle < 180.0_degrees ) {
         return reverse ? 1 : 4;
     } else if( angle < -10.0_degrees && angle >= -45.0_degrees ) {
         return reverse ? -4 : -1;
     } else if( angle < -45.0_degrees && angle >= -90.0_degrees ) {
         return -3;
     } else if( angle < -90.0_degrees && angle > -180.0_degrees ) {
         return reverse ? -1 : -4;
         // edge case of being exactly on the button for the target.
         // just keep driving, the next path point will be picked up.
     } else if( ( angle == 180_degrees || angle == -180_degrees ) && vehpos == target ) {
         return 0;
     }
     return 0;
 }
Referenced by vehicle::do_towing_move(), and vehicle::drive_to_local_target().
is_sm_tile_outside()
static bool is_sm_tile_outside (const tripoint & real_global_pos) static
Definition at line 7854 of file vehicle.cpp.
 {
     tripoint_abs_sm smp;
     point_sm_ms_ib p;
     // TODO: fix point types
     std::tie( smp, p ) = project_remain<coords::sm>( tripoint_abs_ms( real_global_pos ) );
     const submap *sm = MAPBUFFER.lookup_submap( smp );
     if( sm == nullptr ) {
         debugmsg( "is_sm_tile_outside(): couldn't find submap %s", smp.to_string() );
         return false;
     }
     if( p.x() < 0 || p.x() >= SEEX || p.y() < 0 || p.y() >= SEEY ) {
         debugmsg( "err %s", p.to_string() );
         return false;
     }
     // TODO: fix point types
     return !( sm->get_ter( p.raw() ).obj().has_flag( ter_furn_flag::TFLAG_INDOORS ) ||
               sm->get_furn( p.raw() ).obj().has_flag( ter_furn_flag::TFLAG_INDOORS ) );
 }
References debugmsg, mapbuffer::lookup_submap(), MAPBUFFER, coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), SEEX, SEEY, coords::sm, TFLAG_INDOORS, coords::coord_point_base< Point >::to_string(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Referenced by vehicle::total_solar_epower(), vehicle::total_wind_epower(), and vehicle::update_time().
is_sm_tile_over_water()
static bool is_sm_tile_over_water (const tripoint & real_global_pos) static
Definition at line 7832 of file vehicle.cpp.
 {
     tripoint_abs_sm smp;
     point_sm_ms_ib p;
     // TODO: fix point types
     std::tie( smp, p ) = project_remain<coords::sm>( tripoint_abs_ms( real_global_pos ) );
     const submap *sm = MAPBUFFER.lookup_submap( smp );
     if( sm == nullptr ) {
         debugmsg( "is_sm_tile_over_water(): couldn't find submap %s", smp.to_string() );
         return false;
     }
     if( p.x() < 0 || p.x() >= SEEX || p.y() < 0 || p.y() >= SEEY ) {
         debugmsg( "err %s", p.to_string() );
         return false;
     }
     // TODO: fix point types
     return ( sm->get_ter( p.raw() ).obj().has_flag( ter_furn_flag::TFLAG_CURRENT ) ||
              sm->get_furn( p.raw() ).obj().has_flag( ter_furn_flag::TFLAG_CURRENT ) );
 }
References debugmsg, mapbuffer::lookup_submap(), MAPBUFFER, coords::coord_point_mut< Point, Subpoint, InBounds >::raw(), SEEX, SEEY, coords::sm, TFLAG_CURRENT, coords::coord_point_base< Point >::to_string(), coords::coord_point_mut< Point, Subpoint, InBounds >::x(), and coords::coord_point_mut< Point, Subpoint, InBounds >::y().
Referenced by vehicle::total_water_wheel_epower().
part_location_center()
static const std::string part_location_center ("center") static
Referenced by vehicle::coeff_air_drag().
part_location_onroof()
static const std::string part_location_onroof ("on_roof") static
Referenced by vehicle::coeff_air_drag().
part_location_structure()
static const std::string part_location_structure ("structure") static
Referenced by vehicle::break_off(), vehicle::can_mount(), vehicle::can_unmount(), vehicle::coeff_air_drag(), vehicle::coeff_water_drag(), vehicle::damage_all(), vehicle::find_and_split_vehicles(), vehicle::has_structural_part(), vehicle::is_connected(), vehicle::is_structural_part_removed(), vehicle::merge_rackable_vehicle(), vehicle_prototype::save_vehicle_as_prototype(), vehicle::smash(), vehicle::split_vehicles(), and vehicle::sufficient_wheel_config().
practice_athletic_proficiency()
void practice_athletic_proficiency (Character & p)
Definition at line 4960 of file vehicle.cpp.
 {
     // Perform athletics practice
     p.practice( skill_swimming, 1 );
     // We are already a master athlete, practice has no effect
     if( p.has_proficiency( proficiency_prof_athlete_master ) ) {
         return;
     }
     // We have no athletic experience
     if( !p.has_proficiency( proficiency_prof_athlete_basic ) ) {
         p.practice_proficiency( proficiency_prof_athlete_basic, 1_seconds );
         return;
     }
     // We know athletics, but aren't an expert yet
     else if( !p.has_proficiency( proficiency_prof_athlete_expert ) ) {
         p.practice_proficiency( proficiency_prof_athlete_expert, 1_seconds );
         return;
     }
     // We're an expert, so lets practice to become a master athlete
     else {
         p.practice_proficiency( proficiency_prof_athlete_master, 1_seconds );
         return;
     }
 }
References Character::has_proficiency(), Character::practice(), Character::practice_proficiency(), proficiency_prof_athlete_basic, proficiency_prof_athlete_expert, proficiency_prof_athlete_master, and skill_swimming.
Referenced by vehicle::consume_fuel().
practice_pilot_proficiencies()
void practice_pilot_proficiencies (Character & p, bool & boating)
Definition at line 4950 of file vehicle.cpp.
 {
     if( !p.has_proficiency( proficiency_prof_driver ) && !boating ) {
         p.practice_proficiency( proficiency_prof_driver, 1_seconds );
     }
     if( !p.has_proficiency( proficiency_prof_boat_pilot ) && boating ) {
         p.practice_proficiency( proficiency_prof_boat_pilot, 1_seconds );
     }
 }
References Character::has_proficiency(), Character::practice_proficiency(), proficiency_prof_boat_pilot, and proficiency_prof_driver.
Referenced by vehicle::consume_fuel().
simple_cubic_solution()
static double simple_cubic_solution (double a, double b, double c, double d) static
Definition at line 3808 of file vehicle.cpp.
 {
     double p = -b / ( 3 * a );
     double q = p * p * p + ( b * c - 3 * a * d ) / ( 6 * a * a );
     double r = c / ( 3 * a );
     double t = r - p * p;
     double tricky_bit = q * q + t * t * t;
     if( tricky_bit < 0 ) {
         double cr = 1.0 / 3.0; // approximate the cube root of a complex number
         std::complex<double> q_complex( q );
         std::complex<double> tricky_complex( std::sqrt( std::complex<double>( tricky_bit ) ) );
         std::complex<double> term1( std::pow( q_complex + tricky_complex, cr ) );
         std::complex<double> term2( std::pow( q_complex - tricky_complex, cr ) );
         std::complex<double> term_sum( term1 + term2 );
         if( imag( term_sum ) < 2 ) {
             return p + real( term_sum );
         } else {
             debugmsg( "cubic solution returned imaginary values" );
             return 0;
         }
     } else {
         double tricky_final = std::sqrt( tricky_bit );
         double term1_part = q + tricky_final;
         double term2_part = q - tricky_final;
         double term1 = std::cbrt( term1_part );
         double term2 = std::cbrt( term2_part );
         return p + term1 + term2;
     }
 }
References a, b, c, debugmsg, and sqrt().
Referenced by vehicle::max_ground_velocity(), and vehicle::safe_ground_velocity().
tile_to_width()
static double tile_to_width (int tiles) static
Definition at line 4128 of file vehicle.cpp.
 {
     if( tiles < 1 ) {
         return 0.1;
     } else if( tiles < 6 ) {
         return 0.5 + 0.4 * tiles;
     } else {
         return 2.5 + 0.15 * ( tiles - 5 );
     }
 }
Referenced by vehicle::coeff_air_drag(), and vehicle::coeff_water_drag().
weighted_power_loss()
static double weighted_power_loss (const std::map< vpart_reference, float > & batteries) static
Definition at line 5462 of file vehicle.cpp.
 {
     double res = 0.0; // sum of power losses
     int64_t total_capacity = 0; // sum of capacity of all batteries
     for( const std::pair<const vpart_reference, float> &pair : batteries ) {
         vehicle_part &vp = pair.first.part();
         const int capacity = vp.ammo_capacity( ammo_battery );
         total_capacity += capacity;
         res += pair.second * capacity;
     }
     return res / total_capacity;
 }
References ammo_battery, and vehicle_part::ammo_capacity().
Referenced by vehicle::charge_battery(), and vehicle::discharge_battery().
Variable Documentation
ACT_VEHICLE
const activity_id ACT_VEHICLE("ACT_VEHICLE") ("ACT_VEHICLE") static
Referenced by DefaultRemovePartHandler::removed().
ammo_battery
const ammotype ammo_battery("battery") ("battery") static
Referenced by vehicle::battery_power_level(), vehicle::charge_battery(), vehicle::discharge_battery(), distribute_charge_evenly(), and weighted_power_loss().
bio_jointservo
const bionic_id bio_jointservo("bio_jointservo") ("bio_jointservo") static
Referenced by vehicle::consume_fuel().
damage_heat
const damage_type_id damage_heat("heat") ("heat") static
Referenced by vehicle::damage_direct(), and vehicle::explode_fuel().
damage_pure
const damage_type_id damage_pure("pure") ("pure") static
Referenced by vehicle::damage_direct().
effect_harnessed
const efftype_id effect_harnessed("harnessed") ("harnessed") static
Referenced by vehicle::activate_animal_follow(), vehicle::damage_direct(), and vehicle::part_vpower_w().
effect_winded
const efftype_id effect_winded("winded") ("winded") static
Referenced by vehicle::consume_fuel().
fault_engine_immobiliser
const fault_id fault_engine_immobiliser("fault_engine_immobiliser") ("fault_engine_immobiliser") static
Referenced by vehicle::init_state(), and vehicle::unlock().
fuel_type_animal
const itype_id fuel_type_animal("animal") ("animal") static
Referenced by vehicle::activate_animal_follow(), vehicle::idle(), vehicle::part_vpower_w(), vehicle::player_in_control(), and vehicle::steering_effectiveness().
fuel_type_battery
const itype_id fuel_type_battery("battery") ("battery") static
Referenced by vehicle::basic_consumption(), vehicle::consume_fuel(), distribute_charge_evenly(), vehicle::drain(), vehicle::fuel_capacity(), vehicle::fuel_left(), vehicle::has_available_electric_engine(), vehicle::has_security_working(), vehicle::install_part(), vehicle::max_reverse_velocity(), and vehicle::slow_leak().
fuel_type_mana
const itype_id fuel_type_mana("mana") ("mana") static
Referenced by vehicle::activate_magical_follow(), and vehicle::idle().
fuel_type_muscle
const itype_id fuel_type_muscle("muscle") ("muscle") static
Referenced by vehicle::consume_fuel(), vehicle::fuel_left(), vehicle::idle(), vehicle::init_state(), and vehicle::part_vpower_w().
fuel_type_plutonium_cell
const itype_id fuel_type_plutonium_cell("plut_cell") ("plut_cell") static
Referenced by vehicle::slow_leak().
fuel_type_wind
const itype_id fuel_type_wind("wind") ("wind") static
Referenced by vehicle::idle(), and vehicle::part_vpower_w().
itype_battery
const itype_id itype_battery("battery") ("battery") static
Referenced by vehicle::init_state(), and vehicle::update_time().
itype_plut_cell
const itype_id itype_plut_cell("plut_cell") ("plut_cell") static
Referenced by vehicle::init_state().
itype_wall_wiring
const itype_id itype_wall_wiring("wall_wiring") ("wall_wiring") static
Referenced by vehicle::split_vehicles().
itype_water
const itype_id itype_water("water") ("water") static
Referenced by vehicle::update_time().
itype_water_clean
const itype_id itype_water_clean("water_clean") ("water_clean") static
Referenced by vehicle::update_time().
itype_water_faucet
const itype_id itype_water_faucet("water_faucet") ("water_faucet") static
Referenced by vehicle::use_charges().
itype_water_purifier
const itype_id itype_water_purifier("water_purifier") ("water_purifier") static
Referenced by vehicle::update_time().
json_flag_MUSCLE_VEH_BOOST
const json_character_flag json_flag_MUSCLE_VEH_BOOST("MUSCLE_VEH_BOOST") ("MUSCLE_VEH_BOOST") static
Referenced by vehicle::part_vpower_w().
MAX_WIRE_VEHICLE_SIZE
const int MAX_WIRE_VEHICLE_SIZE = 24 static
Definition at line 146 of file vehicle.cpp.
Referenced by vehicle::merge_appliance_into_grid().
maxrow
constexpr int maxrow = 122 static constexpr
Definition at line 4140 of file vehicle.cpp.
Referenced by vehicle::coeff_air_drag().
minrow
constexpr int minrow = -122 static constexpr
Definition at line 4139 of file vehicle.cpp.
Referenced by vehicle::coeff_air_drag().
power_grid_name
const translation power_grid_name = to_translation("power grid") static
Definition at line 141 of file vehicle.cpp.
Referenced by vehicle::merge_appliance_into_grid(), and vehicle::part_removal_cleanup().
proficiency_prof_aircraft_mechanic
const proficiency_id proficiency_prof_aircraft_mechanic("prof_aircraft_mechanic") ("prof_aircraft_mechanic") static
Referenced by vehicle::would_install_prevent_flyable(), vehicle::would_removal_prevent_flyable(), and vehicle::would_repair_prevent_flyable().
proficiency_prof_athlete_basic
const proficiency_id proficiency_prof_athlete_basic("prof_athlete_basic") ("prof_athlete_basic") static
Referenced by practice_athletic_proficiency().
proficiency_prof_athlete_expert
const proficiency_id proficiency_prof_athlete_expert("prof_athlete_expert") ("prof_athlete_expert") static
Referenced by practice_athletic_proficiency().
proficiency_prof_athlete_master
const proficiency_id proficiency_prof_athlete_master("prof_athlete_master") ("prof_athlete_master") static
Referenced by practice_athletic_proficiency().
proficiency_prof_boat_pilot
const proficiency_id proficiency_prof_boat_pilot("prof_boat_pilot") ("prof_boat_pilot") static
Referenced by practice_pilot_proficiencies().
proficiency_prof_driver
const proficiency_id proficiency_prof_driver("prof_driver") ("prof_driver") static
Referenced by practice_pilot_proficiencies().
skill_swimming
const skill_id skill_swimming("swimming") ("swimming") static
Referenced by practice_athletic_proficiency().
vehicle_prototype_none
const vproto_id vehicle_prototype_none("none") ("none") static
Referenced by vehicle::remove_carried_vehicle(), and vehicle::split_vehicles().
vpart_power_cord
const vpart_id vpart_power_cord("power_cord") ("power_cord") static
Referenced by vehicle::merge_vehicle_parts().
zone_type_VEHICLE_PATROL
const zone_type_id zone_type_VEHICLE_PATROL("VEHICLE_PATROL") ("VEHICLE_PATROL") static
Referenced by vehicle::autopilot_patrol().