Cataclysm DDA: src/vehicle_move.cpp File Reference
vehicle_move.cpp File Reference
#include "vehicle.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdlib>
#include <memory>
#include <optional>
#include <ostream>
#include <set>
#include <tuple>
#include "avatar.h"
#include "bodypart.h"
#include "cata_assert.h"
#include "cata_utility.h"
#include "character.h"
#include "creature.h"
#include "creature_tracker.h"
#include "debug.h"
#include "enums.h"
#include "explosion.h"
#include "game.h"
#include "item.h"
#include "itype.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "material.h"
#include "messages.h"
#include "monster.h"
#include "options.h"
#include "rng.h"
#include "sounds.h"
#include "translations.h"
#include "trap.h"
#include "units.h"
#include "units_utility.h"
#include "veh_type.h"
#include "vpart_position.h"
#include "vpart_range.h"
Macros
#define dbg(x) DebugLog((x),D_MAP) << __FILE__ << ":" << __LINE__ << ": "
Functions
static const std::string part_location_structure ("structure")
int mps_to_vmiph (double mps)
double vmiph_to_mps (int vmiph)
int cmps_to_vmiph (int cmps)
int vmiph_to_cmps (int vmiph)
static void terrain_collision_data (const tripoint &p, bool bash_floor, float &mass, float &density, float &elastic)
static rl_vec2d angle_to_vec (const units::angle &angle)
float get_collision_factor (const float delta_v)
static units::angle get_corrected_turn_dir (const units::angle &turn_dir, const units::angle &face_dir)
Variables
static const damage_type_id damage_bash ("bash")
static const damage_type_id damage_cut ("cut")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_harnessed ("harnessed")
static const efftype_id effect_pet ("pet")
static const efftype_id effect_stunned ("stunned")
static const itype_id fuel_type_animal ("animal")
static const itype_id fuel_type_battery ("battery")
static const itype_id fuel_type_muscle ("muscle")
static const proficiency_id proficiency_prof_boat_pilot ("prof_boat_pilot")
static const proficiency_id proficiency_prof_driver ("prof_driver")
static const skill_id skill_driving ("driving")
static const ter_str_id ter_t_railroad_track ("t_railroad_track")
static const ter_str_id ter_t_railroad_track_d ("t_railroad_track_d")
static const ter_str_id ter_t_railroad_track_d1 ("t_railroad_track_d1")
static const ter_str_id ter_t_railroad_track_d2 ("t_railroad_track_d2")
static const ter_str_id ter_t_railroad_track_d_on_tie ("t_railroad_track_d_on_tie")
static const ter_str_id ter_t_railroad_track_h ("t_railroad_track_h")
static const ter_str_id ter_t_railroad_track_h_on_tie ("t_railroad_track_h_on_tie")
static const ter_str_id ter_t_railroad_track_on_tie ("t_railroad_track_on_tie")
static const ter_str_id ter_t_railroad_track_v ("t_railroad_track_v")
static const ter_str_id ter_t_railroad_track_v_on_tie ("t_railroad_track_v_on_tie")
static const trait_id trait_DEFT ("DEFT")
static const trait_id trait_PROF_SKATER ("PROF_SKATER")
static const float tile_height = 4.0f
static const int mi_to_vmi = 100
static const float mps_to_miph = 2.23694f
Macro Definition Documentation
dbg
#define dbg (x) DebugLog((x),D_MAP) << __FILE__ << ":" << __LINE__ << ": "
Definition at line 43 of file vehicle_move.cpp.
Function Documentation
angle_to_vec()
static rl_vec2d angle_to_vec (const units::angle & angle) static
Definition at line 1601 of file vehicle_move.cpp.
 {
     return rl_vec2d( units::cos( angle ), units::sin( angle ) );
 }
References units::cos(), and units::sin().
Referenced by vehicle::dir_vec(), vehicle::face_vec(), and vehicle::move_vec().
cmps_to_vmiph()
int cmps_to_vmiph (int cmps)
Definition at line 97 of file vehicle_move.cpp.
 {
     return cmps * mps_to_miph;
 }
References mps_to_miph.
Referenced by vehicle::ground_acceleration(), vehicle::rotor_acceleration(), and vehicle::water_acceleration().
get_collision_factor()
float get_collision_factor (const float delta_v)
Definition at line 1623 of file vehicle_move.cpp.
 {
     if( std::abs( delta_v ) <= 31 ) {
         return 1 - ( 0.9 * std::abs( delta_v ) ) / 31;
     } else {
         return 0.1;
     }
 }
References abs().
Referenced by map::vehicle_vehicle_collision().
get_corrected_turn_dir()
static units::angle get_corrected_turn_dir (const units::angle & turn_dir, const units::angle & face_dir) static
Definition at line 1724 of file vehicle_move.cpp.
 {
     units::angle corrected_turn_dir = 0_degrees;
     // Driver turned vehicle, round angle to 45 deg
     if( turn_dir > face_dir && turn_dir < face_dir + 180_degrees ) {
         corrected_turn_dir = face_dir + 45_degrees;
     } else if( turn_dir < face_dir || turn_dir > 270_degrees ) {
         corrected_turn_dir = face_dir - 45_degrees;
     }
     return normalize( corrected_turn_dir );
 }
References normalize().
Referenced by vehicle::allow_auto_turn_on_rails(), and vehicle::allow_manual_turn_on_rails().
mps_to_vmiph()
int mps_to_vmiph (double mps)
Definition at line 86 of file vehicle_move.cpp.
 {
     return mps * mps_to_miph * mi_to_vmi;
 }
References mi_to_vmi, and mps_to_miph.
Referenced by vehicle::act_on_map(), vehicle::max_ground_velocity(), vehicle::max_rotor_velocity(), vehicle::max_water_velocity(), vehicle::safe_ground_velocity(), vehicle::safe_rotor_velocity(), vehicle::safe_water_velocity(), and vehicle::slowdown().
part_location_structure()
static const std::string part_location_structure ("structure") static
Referenced by vehicle::collision(), and vehicle::level_vehicle().
terrain_collision_data()
static void terrain_collision_data (const tripoint & p, bool bash_floor, float & mass, float & density, float & elastic) static
Definition at line 820 of file vehicle_move.cpp.
 {
     elastic = 0.30;
     map &here = get_map();
     // Just a rough rescale for now to obtain approximately equal numbers
     const int bash_min = here.bash_resistance( p, bash_floor );
     const int bash_max = here.bash_strength( p, bash_floor );
     mass = ( bash_min + bash_max ) / 2.0;
     density = bash_min;
 }
References map::bash_resistance(), map::bash_strength(), and get_map().
Referenced by vehicle::part_collision().
vmiph_to_cmps()
int vmiph_to_cmps (int vmiph)
Definition at line 102 of file vehicle_move.cpp.
 {
     return vmiph / mps_to_miph;
 }
References mps_to_miph.
Referenced by vehicle::ground_acceleration(), and vehicle::water_acceleration().
vmiph_to_mps()
double vmiph_to_mps (int vmiph)
Definition at line 92 of file vehicle_move.cpp.
 {
     return vmiph / mps_to_miph / mi_to_vmi;
 }
References mi_to_vmi, and mps_to_miph.
Referenced by vehicle::act_on_map(), and vehicle::slowdown().
Variable Documentation
damage_bash
const damage_type_id damage_bash("bash") ("bash") static
Referenced by vehicle::part_collision(), and map::shake_vehicle().
damage_cut
const damage_type_id damage_cut("cut") ("cut") static
Referenced by vehicle::part_collision().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by vehicle::part_collision().
effect_harnessed
const efftype_id effect_harnessed("harnessed") ("harnessed") static
Referenced by vehicle::get_harnessed_animal(), and vehicle::thrust().
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by vehicle::get_harnessed_animal().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by vehicle::part_collision().
fuel_type_animal
const itype_id fuel_type_animal("animal") ("animal") static
Referenced by vehicle::get_harnessed_animal(), and vehicle::thrust().
fuel_type_battery
const itype_id fuel_type_battery("battery") ("battery") static
Referenced by vehicle::smart_controller_handle_turn(), and vehicle::thrust().
fuel_type_muscle
const itype_id fuel_type_muscle("muscle") ("muscle") static
Referenced by vehicle::thrust().
mi_to_vmi
const int mi_to_vmi = 100 static
Definition at line 81 of file vehicle_move.cpp.
Referenced by mps_to_vmiph(), and vmiph_to_mps().
mps_to_miph
const float mps_to_miph = 2.23694f static
Definition at line 83 of file vehicle_move.cpp.
Referenced by cmps_to_vmiph(), mps_to_vmiph(), vmiph_to_cmps(), and vmiph_to_mps().
proficiency_prof_boat_pilot
const proficiency_id proficiency_prof_boat_pilot("prof_boat_pilot") ("prof_boat_pilot") static
Referenced by vehicle::pldrive().
proficiency_prof_driver
const proficiency_id proficiency_prof_driver("prof_driver") ("prof_driver") static
Referenced by vehicle::pldrive().
skill_driving
const skill_id skill_driving("driving") ("driving") static
Referenced by vehicle::act_on_map(), vehicle::pldrive(), and map::shake_vehicle().
ter_t_railroad_track
const ter_str_id ter_t_railroad_track("t_railroad_track") ("t_railroad_track") static
Referenced by vehicle::precalculate_vehicle_turning().
ter_t_railroad_track_d
const ter_str_id ter_t_railroad_track_d("t_railroad_track_d") ("t_railroad_track_d") static
Referenced by vehicle::precalculate_vehicle_turning().
ter_t_railroad_track_d1
const ter_str_id ter_t_railroad_track_d1("t_railroad_track_d1") ("t_railroad_track_d1") static
Referenced by vehicle::precalculate_vehicle_turning().
ter_t_railroad_track_d2
const ter_str_id ter_t_railroad_track_d2("t_railroad_track_d2") ("t_railroad_track_d2") static
Referenced by vehicle::precalculate_vehicle_turning().
ter_t_railroad_track_d_on_tie
const ter_str_id ter_t_railroad_track_d_on_tie("t_railroad_track_d_on_tie") ("t_railroad_track_d_on_tie") static
Referenced by vehicle::precalculate_vehicle_turning().
ter_t_railroad_track_h
const ter_str_id ter_t_railroad_track_h("t_railroad_track_h") ("t_railroad_track_h") static
Referenced by vehicle::precalculate_vehicle_turning().
ter_t_railroad_track_h_on_tie
const ter_str_id ter_t_railroad_track_h_on_tie("t_railroad_track_h_on_tie") ("t_railroad_track_h_on_tie") static
Referenced by vehicle::precalculate_vehicle_turning().
ter_t_railroad_track_on_tie
const ter_str_id ter_t_railroad_track_on_tie("t_railroad_track_on_tie") ("t_railroad_track_on_tie") static
Referenced by vehicle::precalculate_vehicle_turning().
ter_t_railroad_track_v
const ter_str_id ter_t_railroad_track_v("t_railroad_track_v") ("t_railroad_track_v") static
Referenced by vehicle::precalculate_vehicle_turning().
ter_t_railroad_track_v_on_tie
const ter_str_id ter_t_railroad_track_v_on_tie("t_railroad_track_v_on_tie") ("t_railroad_track_v_on_tie") static
Referenced by vehicle::precalculate_vehicle_turning().
tile_height
const float tile_height = 4.0f static
Definition at line 79 of file vehicle_move.cpp.
Referenced by vehicle::act_on_map().
trait_DEFT
const trait_id trait_DEFT("DEFT") ("DEFT") static
Referenced by map::shake_vehicle().
trait_PROF_SKATER
const trait_id trait_PROF_SKATER("PROF_SKATER") ("PROF_SKATER") static
Referenced by map::shake_vehicle().