Cataclysm DDA: src/version.cpp File Reference
version.cpp File Reference
#include "get_version.h"
#include "version.h"
Functions
const char * getVersionString ()
Function Documentation
getVersionString()
const char* getVersionString ()
Definition at line 15 of file version.cpp.
 {
     return VERSION;
 }
Referenced by debug_error_prompt(), game_info::game_version(), DebugFile::init(), game::load(), main(), main_menu::print_menu(), anonymous_namespace{main.cpp}::printVersionMessage(), set_language(), game::start_game(), and memorial_logger::write_text_memorial().