Cataclysm DDA: src/viewer.h File Reference
viewer.h File Reference
#include "coordinates.h"
Classes
class viewer
Macros
#define CATA_SRC_VIEWER_H
Functions
viewer & get_player_view ()
Macro Definition Documentation
CATA_SRC_VIEWER_H
#define CATA_SRC_VIEWER_H
Definition at line 3 of file viewer.h.
Function Documentation
get_player_view()
viewer& get_player_view ()
Definition at line 154 of file game.cpp.
 {
     return g->u;
 }
Referenced by Character::ablative_armor_absorb(), outfit::absorb_damage(), mdefense::acidsplash(), add_msg_if_player_sees(), npc::add_msg_player_or_npc(), Character::add_msg_player_or_say(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), leap_actor::call(), trapfunc::caltrops_glass(), npc::complain(), trapfunc::crossbow(), mattack::dance(), Character::deactivate_bionic(), Character::deal_damage(), trapfunc::dissector(), npc::do_reload(), iuse::dog_whistle(), mattack::dogthing(), iuse::extinguisher(), conditional_fun::anonymous_namespace{condition.cpp}::f_player_see(), mattack::fungus_big_blossom(), mattack::fungus_corporate(), grenade_helper(), npc::heal_player(), anonymous_namespace{animation.cpp}::is_point_visible(), monster::knock_back_to(), mattack::leech_spawner(), mattack::lunge(), iuse::mace(), Creature::messaging_projectile_attack(), monster::move_effects(), npc::mutiny(), mattack::nurse_assist(), Character::on_hit(), gates::open_gate(), pick_follower(), npc::pick_up_item(), map::rotten_item_spawn(), seen_critter(), npc::set_attitude(), map::shoot(), trapfunc::shotgun(), npc::stow_item(), teleport::teleport_to_point(), Character::uncanny_dodge(), Character::uninstall_bionic(), mattack::upgrade(), outfit::wear_item(), npc::wield(), npc::would_take_that(), and mdefense::zapback().