Cataclysm DDA: src/visitable.cpp File Reference
visitable.cpp File Reference
#include "visitable.h"
#include <algorithm>
#include <climits>
#include <iosfwd>
#include <limits>
#include <map>
#include <memory>
#include <string>
#include <unordered_map>
#include <utility>
#include "active_item_cache.h"
#include "bionics.h"
#include "character.h"
#include "colony.h"
#include "debug.h"
#include "flag.h"
#include "inventory.h"
#include "item.h"
#include "item_contents.h"
#include "item_pocket.h"
#include "make_static.h"
#include "map.h"
#include "map_selector.h"
#include "memory_fast.h"
#include "monster.h"
#include "mtype.h"
#include "mutation.h"
#include "pimpl.h"
#include "point.h"
#include "submap.h"
#include "temp_crafting_inventory.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "vehicle_selector.h"
Functions
template<typename T >
static T sum_no_wrap (T a, T b)
Sums the two terms, being careful to not trigger overflow.
template<typename T >
static int has_quality_internal (const T &self, const quality_id &qual, int level, int limit)
static int has_quality_from_vpart (const vehicle &veh, int part, const quality_id &qual, int level, int limit)
template<typename T >
static int max_quality_internal (const T &self, const quality_id &qual)
static int max_quality_from_vpart (const vehicle &veh, int part, const quality_id &qual)
template<typename T , typename V >
static std::vector< T > items_with_internal (V &self, const std::function< bool(const item &)> &filter)
static VisitResponse visit_internal (const std::function< VisitResponse(item *, item *)> &func, const item *node, item *parent=nullptr)
template<typename T , typename M >
static int charges_of_internal (const T &self, const M &main, const itype_id &id, int limit, const std::function< bool(const item &)> &filter, const std::function< void(int)> &visitor, bool in_tools)
template<typename T >
static std::pair< int, int > kcal_range_of_internal (const T &self, const itype_id &id, const std::function< bool(const item &)> &filter, Character &player_character)
template<typename T >
static int amount_of_internal (const T &self, const itype_id &id, bool pseudo, int limit, const std::function< bool(const item &)> &filter)
Variables
static const bionic_id bio_ups ("bio_ups")
static const itype_id itype_UPS ("UPS")
static const itype_id itype_apparatus ("apparatus")
static const quality_id qual_BUTCHER ("BUTCHER")
static const quality_id qual_SMOKE_PIPE ("SMOKE_PIPE")
Function Documentation
amount_of_internal()
template<typename T > static int amount_of_internal (const T & self, const itype_id & id, bool pseudo, int limit, const std::function< bool(const item &)> & filter) static
Definition at line 943 of file visitable.cpp.
 {
     int qty = 0;
     self.visit_items( [&qty, &id, &pseudo, &limit, &filter]( const item * e, item * ) {
         if( !e->has_flag( STATIC( flag_id( "ITEM_BROKEN" ) ) ) &&
             ( id == STATIC( itype_id( "any" ) ) || e->typeId() == id ) && filter( *e ) &&
             ( pseudo || !e->has_flag( STATIC( flag_id( "PSEUDO" ) ) ) ) ) {
             qty = sum_no_wrap( qty, 1 );
         }
         return qty != limit ? VisitResponse::NEXT : VisitResponse::ABORT;
     } );
     return qty;
 }
References ABORT, filter, item::has_flag(), NEXT, STATIC, sum_no_wrap(), and item::typeId().
Referenced by visitable::amount_of().
charges_of_internal()
template<typename T , typename M > static int charges_of_internal (const T & self, const M & main, const itype_id & id, int limit, const std::function< bool(const item &)> & filter, const std::function< void(int)> & visitor, bool in_tools) static
Definition at line 800 of file visitable.cpp.
 {
     int qty = 0;
     bool found_tool_with_UPS = false;
     bool found_bionic_tool = false;
     self.visit_items( [&]( const item * e, item * ) {
         if( filter( *e ) &&
             ( id == e->typeId() || ( in_tools && id == e->ammo_current() ) ||
               ( id == itype_UPS && e->has_flag( flag_IS_UPS ) ) ) &&
             !e->is_broken() ) {
             if( id != itype_UPS ) {
                 if( e->count_by_charges() ) {
                     qty = sum_no_wrap( qty, e->charges );
                 } else {
                     qty = sum_no_wrap( qty, e->ammo_remaining( nullptr, true ) );
                 }
                 if( e->has_flag( STATIC( flag_id( "USE_UPS" ) ) ) ) {
                     found_tool_with_UPS = true;
                 } else if( e->has_flag( STATIC( flag_id( "USES_BIONIC_POWER" ) ) ) ) {
                     found_bionic_tool = true;
                 }
             } else if( id == itype_UPS && e->has_flag( flag_IS_UPS ) ) {
                 qty = sum_no_wrap( qty, e->ammo_remaining( nullptr, true ) );
             }
         }
         if( qty >= limit ) {
             return VisitResponse::ABORT;
         }
         // recurse through nested containers if any
         return e->is_container() ? VisitResponse::NEXT : VisitResponse::SKIP;
     } );
     if( found_tool_with_UPS && qty < limit && get_player_character().has_active_bionic( bio_ups ) ) {
         qty = sum_no_wrap( qty, static_cast<int>( units::to_kilojoule(
                                get_player_character().get_power_level() ) ) );
     }
     if( found_bionic_tool ) {
         qty = sum_no_wrap( qty, static_cast<int>( units::to_kilojoule(
                                get_player_character().get_power_level() ) ) );
     }
     if( qty < limit && found_tool_with_UPS ) {
         int used_ups = main.charges_of( itype_UPS, limit - qty );
         qty += used_ups;
         if( visitor ) {
             visitor( used_ups );
         }
     }
     return std::min( qty, limit );
 }
References ABORT, item::ammo_current(), filter, flag_IS_UPS, item::has_flag(), item::is_broken(), item::is_container(), itype_UPS, NEXT, SKIP, and item::typeId().
Referenced by visitable::charges_of().
has_quality_from_vpart()
static int has_quality_from_vpart (const vehicle & veh, int part, const quality_id & qual, int level, int limit) static
Definition at line 125 of file visitable.cpp.
 {
     int qty = 0;
     point pos = veh.part( part ).mount;
     for( const int n : veh.parts_at_relative( pos, true ) ) {
         const vehicle_part &vp = veh.part( n );
         // only unbroken parts can provide tool qualities
         if( !vp.is_broken() ) {
             auto tq = vp.info().qualities;
             auto iter = tq.find( qual );
             // does the part provide this quality?
             if( iter != tq.end() && iter->second >= level ) {
                 qty = sum_no_wrap( qty, 1 );
             }
         }
     }
     return std::min( qty, limit );
 }
References vehicle_part::info(), vehicle_part::is_broken(), min(), vehicle_part::mount, vehicle::part(), vehicle::parts_at_relative(), math_opers::pos(), vpart_info::qualities, and sum_no_wrap().
has_quality_internal()
template<typename T > static int has_quality_internal (const T & self, const quality_id & qual, int level, int limit) static
Definition at line 108 of file visitable.cpp.
 {
     int qty = 0;
     self.visit_items( [&qual, level, &limit, &qty]( item * e, item * ) {
         if( e->get_quality( qual ) >= level ) {
             qty = sum_no_wrap( qty, static_cast<int>( e->count() ) );
             if( qty >= limit ) {
                 // found sufficient items
                 return VisitResponse::ABORT;
             }
         }
         return VisitResponse::NEXT;
     } );
     return std::min( qty, limit );
 }
References item::get_quality(), and NEXT.
Referenced by visitable::has_quality(), and read_only_visitable::has_quality().
items_with_internal()
template<typename T , typename V > static std::vector<T> items_with_internal (V & self, const std::function< bool(const item &)> & filter) inline static
Definition at line 316 of file visitable.cpp.
 {
     std::vector<T> res;
     self.visit_items( [&res, &filter]( const item * node, item * ) {
         if( filter( *node ) ) {
             res.push_back( const_cast<T>( node ) );
         }
         return VisitResponse::NEXT;
     } );
     return res;
 }
References filter, and NEXT.
kcal_range_of_internal()
template<typename T > static std::pair<int, int> kcal_range_of_internal (const T & self, const itype_id & id, const std::function< bool(const item &)> & filter, Character & player_character) static
Definition at line 857 of file visitable.cpp.
 {
     std::pair<int, int> result( INT_MAX, INT_MIN );
     self.visit_items( [&result, &id, &filter, &player_character]( const item * e, item * ) {
         if( e->typeId() == id && filter( *e ) ) {
             int kcal = player_character.compute_effective_nutrients( *e ).kcal();
             if( kcal < result.first ) {
                 result.first = kcal;
             }
             if( kcal > result.second ) {
                 result.second = kcal;
             }
         }
         return VisitResponse::NEXT;
     } );
     return result;
 }
References Character::compute_effective_nutrients(), filter, nutrients::kcal(), NEXT, and item::typeId().
Referenced by Character::kcal_range(), inventory::kcal_range(), and read_only_visitable::kcal_range().
max_quality_from_vpart()
static int max_quality_from_vpart (const vehicle & veh, int part, const quality_id & qual) static
Definition at line 240 of file visitable.cpp.
 {
     int res = INT_MIN;
     point pos = veh.part( part ).mount;
     for( const int &n : veh.parts_at_relative( pos, true ) ) {
         const vehicle_part &vp = veh.part( n );
         // only unbroken parts can provide tool qualities
         if( !vp.is_broken() ) {
             auto tq = vp.info().qualities;
             auto iter = tq.find( qual );
             // does the part provide this quality?
             if( iter != tq.end() ) {
                 res = std::max( res, iter->second );
             }
         }
     }
     return res;
 }
References vehicle_part::info(), vehicle_part::is_broken(), max(), vehicle_part::mount, vehicle::part(), vehicle::parts_at_relative(), math_opers::pos(), and vpart_info::qualities.
max_quality_internal()
template<typename T > static int max_quality_internal (const T & self, const quality_id & qual) static
Definition at line 230 of file visitable.cpp.
 {
     int res = INT_MIN;
     self.visit_items( [&res, &qual]( item * e, item * ) {
         res = std::max( res, e->get_quality( qual ) );
         return VisitResponse::NEXT;
     } );
     return res;
 }
References item::get_quality(), max(), and NEXT.
Referenced by visitable::max_quality(), and read_only_visitable::max_quality().
sum_no_wrap()
template<typename T > static T sum_no_wrap (T a, T b) static
Sums the two terms, being careful to not trigger overflow.
Doesn't handle underflow.
Parameters
a The first addend.
b The second addend.
Returns
the sum of the addends, but truncated to std::numeric_limits<int>::max().
Definition at line 98 of file visitable.cpp.
 {
     if( a > std::numeric_limits<T>::max() - b ||
         b > std::numeric_limits<T>::max() - a ) {
         return std::numeric_limits<T>::max();
     }
     return a + b;
 }
References a, b, and max().
Referenced by amount_of_internal(), and has_quality_from_vpart().
visit_internal()
static VisitResponse visit_internal (const std::function< VisitResponse(item *, item *)> & func, const item * node, item * parent = nullptr) static
Definition at line 342 of file visitable.cpp.
 {
     // hack to avoid repetition
     item *m_node = const_cast<item *>( node );
     switch( func( m_node, parent ) ) {
         case VisitResponse::ABORT:
             return VisitResponse::ABORT;
         case VisitResponse::NEXT:
             if( m_node->visit_contents( func, m_node ) == VisitResponse::ABORT ) {
                 return VisitResponse::ABORT;
             }
         /* intentional fallthrough */
         case VisitResponse::SKIP:
             return VisitResponse::NEXT;
     }
     /* never reached but suppresses GCC warning */
     return VisitResponse::ABORT;
 }
References ABORT, NEXT, SKIP, and item::visit_contents().
Referenced by item_pocket::visit_contents(), outfit::visit_items(), and visitable::visit_items().
Variable Documentation
bio_ups
const bionic_id bio_ups("bio_ups") ("bio_ups") static
itype_apparatus
const itype_id itype_apparatus("apparatus") ("apparatus") static
itype_UPS
const itype_id itype_UPS("UPS") ("UPS") static
Referenced by charges_of_internal().
qual_BUTCHER
const quality_id qual_BUTCHER("BUTCHER") ("BUTCHER") static
Referenced by visitable::max_quality().
qual_SMOKE_PIPE
const quality_id qual_SMOKE_PIPE("SMOKE_PIPE") ("SMOKE_PIPE") static