Cataclysm DDA: src/weakpoint.cpp File Reference
weakpoint.cpp File Reference
#include "weakpoint.h"
#include <algorithm>
#include <cmath>
#include <string>
#include <utility>
#include "assign.h"
#include "calendar.h"
#include "character.h"
#include "creature.h"
#include "damage.h"
#include "debug.h"
#include "effect_source.h"
#include "enums.h"
#include "generic_factory.h"
#include "item.h"
#include "make_static.h"
#include "messages.h"
#include "monster.h"
#include "mtype.h"
#include "rng.h"
#include "translations.h"
Namespaces
anonymous_namespace{weakpoint.cpp}
Functions
static float reweigh (float base, float rolls)
Variables
static const limb_score_id limb_score_reaction ("reaction")
static const limb_score_id limb_score_vision ("vision")
static const skill_id skill_gun ("gun")
static const skill_id skill_melee ("melee")
static const skill_id skill_throw ("throw")
static const skill_id skill_unarmed ("unarmed")
generic_factory< weakpoints > anonymous_namespace{weakpoint.cpp}::weakpoints_factory ("weakpoint sets")
Function Documentation
reweigh()
static float reweigh (float base, float rolls) static
Definition at line 535 of file weakpoint.cpp.
 {
     return 1.0f - pow( 1.0f - base, rolls );
 }
Referenced by weakpoints::select_weakpoint().
Variable Documentation
limb_score_reaction
const limb_score_id limb_score_reaction("reaction") ("reaction") static
Referenced by Character::melee_weakpoint_skill().
limb_score_vision
const limb_score_id limb_score_vision("vision") ("vision") static
Referenced by Character::melee_weakpoint_skill(), Character::ranged_weakpoint_skill(), and Character::throw_weakpoint_skill().
skill_gun
const skill_id skill_gun("gun") ("gun") static
Referenced by Character::ranged_weakpoint_skill().
skill_melee
const skill_id skill_melee("melee") ("melee") static
Referenced by Character::melee_weakpoint_skill().
skill_throw
const skill_id skill_throw("throw") ("throw") static
Referenced by Character::throw_weakpoint_skill().
skill_unarmed
const skill_id skill_unarmed("unarmed") ("unarmed") static
Referenced by Character::melee_weakpoint_skill().