Cataclysm DDA: src/weather_type.h File Reference
weather_type.h File Reference
#include <climits>
#include <cstdint>
#include <iosfwd>
#include <new>
#include <optional>
#include <string>
#include <vector>
#include "calendar.h"
#include "catacharset.h"
#include "color.h"
#include "damage.h"
#include "translations.h"
#include "type_id.h"
Classes
struct enum_traits< precip_class >
struct enum_traits< weather_sound_category >
struct weather_animation_t
Weather animation class.
struct weather_type
Namespaces
weather_types
Macros
#define CATA_SRC_WEATHER_TYPE_H
Enumerations
enum class precip_class : int {
none , very_light , light , heavy ,
last
}
enum weather_sound_category : int {
silent , drizzle , rainy , rainstorm ,
thunder , flurries , snowstorm , snow ,
portal_storm , clear , sunny , cloudy ,
last , last
}
Functions
const weather_type_id WEATHER_NULL ("null")
const weather_type_id WEATHER_CLEAR ("clear")
const std::vector< weather_type > & weather_types::get_all ()
Get all currently loaded weather types.
void weather_types::finalize_all ()
Finalize all loaded weather types.
void weather_types::reset ()
Clear all loaded weather types (invalidating any pointers)
void weather_types::load (const JsonObject &jo, const std::string &src)
Load weather type from JSON definition.
void weather_types::check_consistency ()
Checks all loaded from JSON are valid.
Macro Definition Documentation
CATA_SRC_WEATHER_TYPE_H
#define CATA_SRC_WEATHER_TYPE_H
Definition at line 3 of file weather_type.h.
Enumeration Type Documentation
precip_class
enum precip_class : int strong
Enumerator
none
very_light
light
heavy
last
Definition at line 29 of file weather_type.h.
                         : int {
     none,
     very_light,
     light,
     heavy,
     last
 };
weather_sound_category
enum weather_sound_category : int
Enumerator
silent
drizzle
rainy
rainstorm
thunder
flurries
snowstorm
snow
portal_storm
clear
sunny
cloudy
last
last
Definition at line 41 of file weather_type.h.
                             : int {
     silent,
     drizzle,
     rainy,
     rainstorm,
     thunder,
     flurries,
     snowstorm,
     snow,
     portal_storm,
     clear,
     sunny,
     cloudy,
     last
 };
Function Documentation
WEATHER_CLEAR()
const weather_type_id WEATHER_CLEAR ("clear")
Referenced by weather_types::check_consistency(), weather_generator::get_weather_conditions(), game::setup(), weather_generator::sort_weather(), and weather_manager::weather_manager().
WEATHER_NULL()
const weather_type_id WEATHER_NULL ("null")
Referenced by debug_menu::change_weather(), weather_types::check_consistency(), current_weather(), get_bad_weather(), game::setup(), weather_manager::update_weather(), weather_forecast(), and weather_manager::weather_manager().