Cataclysm DDA: src/weather.h File Reference
weather.h File Reference
#include <optional>
#include "calendar.h"
#include "catacharset.h"
#include "color.h"
#include "coordinates.h"
#include "pimpl.h"
#include "point.h"
#include "type_id.h"
#include "units.h"
#include "weather_gen.h"
#include "weather_type.h"
#include <cstdint>
#include <iosfwd>
#include <map>
#include <unordered_map>
#include <utility>
#include <vector>
Classes
struct weather_printable
Weather drawing tracking.
struct weather_sum
class weather_manager
Namespaces
irradiance
Macros
#define CATA_SRC_WEATHER_H
Functions
double precip_mm_per_hour (precip_class p)
void handle_weather_effects (const weather_type_id &w)
bool is_creature_outside (const Creature &target)
void wet_character (Character &target, int amount)
Main routine for wet effects caused by weather.
weather_type_id get_bad_weather ()
std::string get_shortdirstring (int angle)
std::string get_dirstring (int angle)
std::string weather_forecast (const point_abs_sm &abs_sm_pos)
Generate textual weather forecast for the specified radio tower.
std::string print_temperature (units::temperature temperature, int decimals=0)
Print temperature (and convert to Celsius if Celsius display is enabled.)
std::string print_humidity (double humidity, int decimals=0)
Print relative humidity (no conversions.)
std::string print_pressure (double pressure, int decimals=0)
Print pressure (no conversions.)
units::temperature_delta get_local_windchill (units::temperature temperature, double humidity, double wind_mph)
int get_local_humidity (double humidity, const weather_type_id &weather, bool sheltered=false)
int get_local_windpower (int windpower, const oter_id &omter, const tripoint_abs_ms &location, const int &winddirection, bool sheltered=false)
weather_sum sum_conditions (const time_point &start, const time_point &end, const tripoint_abs_ms &location)
void retroactively_fill_from_funnel (item &it, const trap &tr, const time_point &start, const time_point &end, const tripoint_abs_ms &pos)
Determine what a funnel has filled out of game, using funnelcontainer.bday as a starting point.
double funnel_charges_per_turn (double surface_area_mm2, double rain_depth_mm_per_hour)
rl_vec2d convert_wind_to_coord (int angle)
std::string get_wind_arrow (int)
std::string get_wind_desc (double)
nc_color get_wind_color (double)
bool warm_enough_to_plant (const tripoint &pos)
Is it warm enough to plant seeds?
bool warm_enough_to_plant (const tripoint_abs_omt &pos)
bool is_wind_blocker (const tripoint_bub_ms &location)
weather_type_id current_weather (const tripoint_abs_ms &location, const time_point &t=calendar::turn)
void glare (const weather_type_id &w)
Glare.
float incident_sunlight (const weather_type_id &wtype, const time_point &t=calendar::turn)
Amount of sunlight incident at the ground, taking weather and time of day into account.
float incident_sun_irradiance (const weather_type_id &wtype, const time_point &t=calendar::turn)
void weather_sound (const translation &sound_message, const std::string &sound_effect)
weather_manager & get_weather ()
const weather_manager & get_weather_const ()
Variables
constexpr float BODYWET_PERCENT_WET = 0.3f
constexpr float BODYWET_PERCENT_SOAKED = 0.6f
constexpr float irradiance::minimal = 87
constexpr float irradiance::low = 422
constexpr float irradiance::moderate = 573
constexpr float irradiance::high = 707
constexpr float irradiance::very_high = 866
constexpr float irradiance::extreme = 906
BODYTEMP
Body temperature.
Most values can be changed with no impact on calculations. Maximum heat cannot pass 57 C (the player will die of heatstroke)
constexpr units::temperature BODYTEMP_FREEZING = 28_C
This value means frostbite occurs at the warmest temperature of 1C. If changed, the temp_conv calculation should be reexamined.
constexpr units::temperature BODYTEMP_VERY_COLD = 31_C
Frostbite timer will not improve while below this point.
constexpr units::temperature BODYTEMP_COLD = 34_C
Normal body temperature.
constexpr units::temperature BODYTEMP_NORM = 37_C
Level 1 hotness.
constexpr units::temperature BODYTEMP_HOT = 40_C
Level 2 hotness.
constexpr units::temperature BODYTEMP_VERY_HOT = 43_C
Level 3 hotness.
constexpr units::temperature BODYTEMP_SCORCHING = 46_C
Additional Threshold before speed is impacted by heat.
constexpr units::temperature_delta BODYTEMP_THRESHOLD = 1_C_delta
Macro Definition Documentation
CATA_SRC_WEATHER_H
#define CATA_SRC_WEATHER_H
Definition at line 3 of file weather.h.
Function Documentation
get_weather()
weather_manager& get_weather ()
Definition at line 155 of file game.cpp.
 {
     return g->weather;
 }
Referenced by Character::activate_bionic(), map::build_sunlight_cache(), map::build_transparency_cache(), Character::burn_fuel(), Character::calc_needs_rates(), Character::can_hear(), debug_menu::change_weather(), Character::complete_disassemble(), current_weather(), debug_menu::debug(), debug_menu::debug_menu_force_temperature(), Character::disp_info(), vehicle::do_environmental_effects(), draw_effects_summary(), eff_fun_sleep(), iuse::emf_passive_on(), vehicle::engine_cold_factor(), conditional_fun::anonymous_namespace{condition.cpp}::f_is_weather(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_lightning(), talk_effect_fun::anonymous_namespace{npctalk.cpp}::f_next_weather(), activity_handlers::fill_liquid_do_turn(), get_bad_weather(), get_signal_for_hordes(), display::get_temp(), get_weather_const(), iexamine_helper::handle_harvest(), handle_weather_effects(), suffer::in_sunlight(), tutorial_game::init(), iexamine::ledge(), firestarter_actor::light_mod(), iuse::multicooker_tick(), vehicle::part_vpower_w(), photo_def_for_camera_point(), Character::process_bionic(), item::process_extinguish(), sounds::process_sound_markers(), sounds::process_sounds(), item::process_temperature_rot(), monster::process_turn(), map::produce_sap(), weather_manager::serialize_all(), map::spread_gas(), sum_conditions(), vehicle::total_wind_epower(), relic::try_recharge(), weather_manager::unserialize_all(), Character::update_bodytemp(), Character::update_frostbite(), Character::update_heartrate_index(), warm_enough_to_plant(), map::water_from(), anonymous_namespace{math_parser_diag.cpp}::weather_ass(), anonymous_namespace{math_parser_diag.cpp}::weather_eval(), weather_forecast(), display::weather_text_color(), iuse::weather_tool(), debug_menu::wind_direction(), debug_menu::wind_speed(), and display::wind_text_color().
Variable Documentation
BODYTEMP_COLD
constexpr units::temperature BODYTEMP_COLD = 34_C constexpr
Normal body temperature.
Definition at line 34 of file weather.h.
Referenced by Character::apply_wetness_morale(), display::bodytemp_color(), Character::calc_sleep_recovery_rate(), suffer::from_chemimbalance(), display::temp_text_color(), Character::update_body_wetness(), Character::update_bodytemp(), and Character::update_frostbite().
BODYTEMP_FREEZING
constexpr units::temperature BODYTEMP_FREEZING = 28_C constexpr
This value means frostbite occurs at the warmest temperature of 1C. If changed, the temp_conv calculation should be reexamined.
More aggressive cold effects.
Definition at line 30 of file weather.h.
Referenced by display::bodytemp_color(), eff_fun_sleep(), display::temp_text_color(), and Character::update_bodytemp().
BODYTEMP_HOT
constexpr units::temperature BODYTEMP_HOT = 40_C constexpr
Level 2 hotness.
Definition at line 38 of file weather.h.
Referenced by Character::apply_wetness_morale(), display::bodytemp_color(), suffer::from_chemimbalance(), display::temp_text_color(), Character::update_body_wetness(), and Character::update_bodytemp().
BODYTEMP_NORM
constexpr units::temperature BODYTEMP_NORM = 37_C constexpr
Level 1 hotness.
Definition at line 36 of file weather.h.
Referenced by Character::load(), Character::normalize(), Character::temp_corrected_by_climate_control(), temp_delta(), and Character::update_bodytemp().
BODYTEMP_SCORCHING
constexpr units::temperature BODYTEMP_SCORCHING = 46_C constexpr
Additional Threshold before speed is impacted by heat.
Definition at line 42 of file weather.h.
Referenced by display::bodytemp_color(), eff_fun_sleep(), display::temp_text_color(), Character::update_body_wetness(), and Character::update_bodytemp().
BODYTEMP_THRESHOLD
constexpr units::temperature_delta BODYTEMP_THRESHOLD = 1_C_delta constexpr
Definition at line 45 of file weather.h.
Referenced by Character::update_bodytemp().
BODYTEMP_VERY_COLD
constexpr units::temperature BODYTEMP_VERY_COLD = 31_C constexpr
Frostbite timer will not improve while below this point.
Definition at line 32 of file weather.h.
Referenced by display::bodytemp_color(), eff_fun_sleep(), suffer::from_chemimbalance(), player_activity::get_distractions(), behavior::character_oracle_t::needs_warmth_badly(), display::temp_text_color(), and Character::update_bodytemp().
BODYTEMP_VERY_HOT
constexpr units::temperature BODYTEMP_VERY_HOT = 43_C constexpr
Level 3 hotness.
Definition at line 40 of file weather.h.
Referenced by display::bodytemp_color(), eff_fun_sleep(), suffer::from_chemimbalance(), player_activity::get_distractions(), display::temp_text_color(), Character::update_body_wetness(), and Character::update_bodytemp().
BODYWET_PERCENT_SOAKED
constexpr float BODYWET_PERCENT_SOAKED = 0.6f constexpr
Definition at line 53 of file weather.h.
Referenced by display::get_bodygraph_bp_color(), and Character::update_body_wetness().
BODYWET_PERCENT_WET
constexpr float BODYWET_PERCENT_WET = 0.3f constexpr
Definition at line 51 of file weather.h.
Referenced by display::get_bodygraph_bp_color(), and Character::update_body_wetness().