Cataclysm DDA: src/weather.cpp File Reference
weather.cpp File Reference
#include "weather.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <functional>
#include <memory>
#include <set>
#include <string>
#include <vector>
#include "activity_type.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "character.h"
#include "city.h"
#include "colony.h"
#include "coordinate_conversions.h"
#include "coordinates.h"
#include "creature.h"
#include "debug.h"
#include "effect_on_condition.h"
#include "enums.h"
#include "game.h"
#include "game_constants.h"
#include "item.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "math_defines.h"
#include "messages.h"
#include "monster.h"
#include "mtype.h"
#include "options.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "pocket_type.h"
#include "regional_settings.h"
#include "ret_val.h"
#include "rng.h"
#include "sounds.h"
#include "string_formatter.h"
#include "translations.h"
#include "trap.h"
#include "uistate.h"
#include "units.h"
#include "weather_gen.h"
Functions
bool is_creature_outside (const Creature &target)
weather_type_id get_bad_weather ()
void glare (const weather_type_id &w)
Glare.
float incident_sunlight (const weather_type_id &wtype, const time_point &t)
Amount of sunlight incident at the ground, taking weather and time of day into account.
float incident_sun_irradiance (const weather_type_id &wtype, const time_point &t)
static void proc_weather_sum (const weather_type_id &wtype, weather_sum &data, const time_point &t, const time_duration &tick_size)
weather_type_id current_weather (const tripoint_abs_ms &location, const time_point &t)
weather_sum sum_conditions (const time_point &start, const time_point &end, const tripoint_abs_ms &location)
void retroactively_fill_from_funnel (item &it, const trap &tr, const time_point &start, const time_point &end, const tripoint_abs_ms &pos)
Determine what a funnel has filled out of game, using funnelcontainer.bday as a starting point.
double funnel_charges_per_turn (const double surface_area_mm2, const double rain_depth_mm_per_hour)
static void fill_funnels (int rain_depth_mm_per_hour, const trap &tr)
Main routine for filling funnels from weather effects.
static void fill_water_collectors (int mmPerHour)
Fill funnels and makeshift funnels from weather effects.
void wet_character (Character &target, int amount)
Main routine for wet effects caused by weather.
void weather_sound (const translation &sound_message, const std::string &sound_effect)
double precip_mm_per_hour (precip_class const p)
void handle_weather_effects (const weather_type_id &w)
static std::string to_string (const weekdays &d)
static std::string print_time_just_hour (const time_point &p)
std::string weather_forecast (const point_abs_sm &abs_sm_pos)
Generate textual weather forecast for the specified radio tower.
std::string print_temperature (units::temperature temperature, int decimals)
Print temperature (and convert to Celsius if Celsius display is enabled.)
std::string print_humidity (double humidity, int decimals)
Print relative humidity (no conversions.)
std::string print_pressure (double pressure, int decimals)
Print pressure (no conversions.)
units::temperature_delta get_local_windchill (units::temperature temperature, double humidity, double wind_mph)
nc_color get_wind_color (double windpower)
std::string get_shortdirstring (int angle)
std::string get_dirstring (int angle)
std::string get_wind_arrow (int dirangle)
int get_local_humidity (double humidity, const weather_type_id &weather, bool sheltered)
int get_local_windpower (int windpower, const oter_id &omter, const tripoint_abs_ms &location, const int &winddirection, bool sheltered)
bool is_wind_blocker (const tripoint_bub_ms &location)
std::string get_wind_desc (double windpower)
rl_vec2d convert_wind_to_coord (const int angle)
bool warm_enough_to_plant (const tripoint &pos)
Is it warm enough to plant seeds?
bool warm_enough_to_plant (const tripoint_abs_omt &pos)
const weather_manager & get_weather_const ()
Variables
static const activity_id ACT_WAIT_WEATHER ("ACT_WAIT_WEATHER")
static const efftype_id effect_glare ("glare")
static const efftype_id effect_sleep ("sleep")
static const efftype_id effect_snow_glare ("snow_glare")
static const flag_id json_flag_RAINPROOF ("RAINPROOF")
static const flag_id json_flag_RAIN_PROTECT ("RAIN_PROTECT")
static const flag_id json_flag_SUN_GLASSES ("SUN_GLASSES")
static const itype_id itype_water ("water")
static const json_character_flag json_flag_GLARE_RESIST ("GLARE_RESIST")
static const oter_type_str_id oter_type_forest ("forest")
static const oter_type_str_id oter_type_forest_water ("forest_water")
static const trait_id trait_CEPH_VISION ("CEPH_VISION")
static const trait_id trait_FEATHERS ("FEATHERS")
Variable Documentation
ACT_WAIT_WEATHER
const activity_id ACT_WAIT_WEATHER("ACT_WAIT_WEATHER") ("ACT_WAIT_WEATHER") static
Referenced by weather_manager::update_weather().
effect_glare
const efftype_id effect_glare("glare") ("glare") static
Referenced by glare().
effect_sleep
const efftype_id effect_sleep("sleep") ("sleep") static
Referenced by weather_sound().
effect_snow_glare
const efftype_id effect_snow_glare("snow_glare") ("snow_glare") static
Referenced by glare().
itype_water
const itype_id itype_water("water") ("water") static
Referenced by item::add_rain_to_container().
json_flag_GLARE_RESIST
const json_character_flag json_flag_GLARE_RESIST("GLARE_RESIST") ("GLARE_RESIST") static
Referenced by glare().
json_flag_RAIN_PROTECT
const flag_id json_flag_RAIN_PROTECT("RAIN_PROTECT") ("RAIN_PROTECT") static
Referenced by wet_character().
json_flag_RAINPROOF
const flag_id json_flag_RAINPROOF("RAINPROOF") ("RAINPROOF") static
Referenced by wet_character().
json_flag_SUN_GLASSES
const flag_id json_flag_SUN_GLASSES("SUN_GLASSES") ("SUN_GLASSES") static
Referenced by glare().
oter_type_forest
const oter_type_str_id oter_type_forest("forest") ("forest") static
Referenced by get_local_windpower().
oter_type_forest_water
const oter_type_str_id oter_type_forest_water("forest_water") ("forest_water") static
Referenced by get_local_windpower().
trait_CEPH_VISION
const trait_id trait_CEPH_VISION("CEPH_VISION") ("CEPH_VISION") static
Referenced by glare().
trait_FEATHERS
const trait_id trait_FEATHERS("FEATHERS") ("FEATHERS") static
Referenced by wet_character().