Cataclysm DDA: src/weather_gen.cpp File Reference
weather_gen.cpp File Reference
#include "weather_gen.h"
#include <algorithm>
#include <cmath>
#include <functional>
#include <ostream>
#include <random>
#include <string>
#include <utility>
#include "avatar.h"
#include "cata_utility.h"
#include "condition.h"
#include "dialogue.h"
#include "game_constants.h"
#include "json.h"
#include "math_defines.h"
#include "point.h"
#include "rng.h"
#include "simplexnoise.h"
#include "translations.h"
#include "weather.h"
#include "weather_type.h"
Classes
struct weather_gen_common
Namespaces
anonymous_namespace{weather_gen.cpp}
Functions
static weather_gen_common get_common_data (const tripoint &location, const time_point &real_t, unsigned seed)
static units::temperature weather_temperature_from_common_data (const weather_generator &wg, const weather_gen_common &common, const season_effective_time &t)
Variables
constexpr double anonymous_namespace{weather_gen.cpp}::tau = 2 * M_PI
constexpr double anonymous_namespace{weather_gen.cpp}::coldest_hour = 5
constexpr double anonymous_namespace{weather_gen.cpp}::daily_magnitude_K = 5
constexpr double anonymous_namespace{weather_gen.cpp}::seasonality_magnitude_K = 15
constexpr double anonymous_namespace{weather_gen.cpp}::noise_magnitude_K = 8
Function Documentation
get_common_data()
static weather_gen_common get_common_data (const tripoint & location, const time_point & real_t, unsigned seed) static
Definition at line 50 of file weather_gen.cpp.
 {
     season_effective_time t( real_t );
     weather_gen_common result;
     // Integer x position / widening factor of the Perlin function.
     result.x = location.x / 2000.0;
     // Integer y position / widening factor of the Perlin function.
     result.y = location.y / 2000.0;
     // Integer turn / widening factor of the Perlin function.
     result.z = to_days<double>( real_t - calendar::turn_zero );
     // Limit the random seed during noise calculation, a large value flattens the noise generator to zero
     // Windows has a rand limit of 32768, other operating systems can have higher limits
     result.modSEED = seed % SIMPLEX_NOISE_RANDOM_SEED_LIMIT;
     const double year_fraction( time_past_new_year( t.t ) /
                                 calendar::year_length() ); // [0,1)
     result.cyf = std::cos( tau * ( year_fraction + .125 ) ); // [-1, 1]
     // We add one-eighth to line up `cyf` so that 1 is at
     // midwinter and -1 at midsummer. (Cataclsym DDA years
     // start when spring starts. Gregorian years start when
     // winter starts.)
     result.season = season_of_year( t.t );
     return result;
 }
References cos(), weather_gen_common::cyf, location, weather_gen_common::modSEED, weather_gen_common::season, season_of_year(), iuse::seed(), SIMPLEX_NOISE_RANDOM_SEED_LIMIT, season_effective_time::t, anonymous_namespace{weather_gen.cpp}::tau, time_past_new_year(), calendar::turn_zero, weather_gen_common::x, weather_gen_common::y, calendar::year_length(), and weather_gen_common::z.
Referenced by weather_generator::get_weather(), and weather_generator::get_weather_temperature().
weather_temperature_from_common_data()
static units::temperature weather_temperature_from_common_data (const weather_generator & wg, const weather_gen_common & common, const season_effective_time & t) static
Definition at line 77 of file weather_gen.cpp.
 {
     const double x( common.x );
     const double y( common.y );
     const double z( common.z );
     const unsigned modSEED = common.modSEED;
     const double seasonality = -common.cyf;
     // -1 in midwinter, +1 in midsummer
     const season_type season = common.season;
     const double dayFraction = time_past_midnight( t.t ) / 1_days;
     const double dayv = std::cos( tau * ( dayFraction + .5 - coldest_hour / 24 ) );
     // -1 at coldest_hour, +1 twelve hours later
     // manually specified seasonal temp variation from region_settings.json
     const std::array<int, 4> seasonal_temp_mod = {
         wg.spring_temp_manual_mod, wg.summer_temp_manual_mod, wg.autumn_temp_manual_mod,
         wg.winter_temp_manual_mod
     };
     const double baseline(
         wg.base_temperature +
         seasonal_temp_mod[season] +
         dayv * daily_magnitude_K +
         seasonality * seasonality_magnitude_K );
     const double T = baseline + raw_noise_4d( x, y, z, modSEED ) * noise_magnitude_K;
     return units::from_celsius( T );
 }
References weather_generator::autumn_temp_manual_mod, weather_generator::base_temperature, anonymous_namespace{weather_gen.cpp}::coldest_hour, game_menus::inv::common(), cos(), anonymous_namespace{weather_gen.cpp}::daily_magnitude_K, units::from_celsius(), anonymous_namespace{weather_gen.cpp}::noise_magnitude_K, raw_noise_4d(), season, anonymous_namespace{weather_gen.cpp}::seasonality_magnitude_K, weather_generator::spring_temp_manual_mod, weather_generator::summer_temp_manual_mod, season_effective_time::t, anonymous_namespace{weather_gen.cpp}::tau, time_past_midnight(), and weather_generator::winter_temp_manual_mod.
Referenced by weather_generator::get_weather(), and weather_generator::get_weather_temperature().