Cataclysm DDA: src/weighted_list.h File Reference
weighted_list.h File Reference
#include "json.h"
#include "rng.h"
#include <climits>
#include <cstdlib>
#include <functional>
#include <sstream>
#include <vector>
Classes
struct weighted_object< W, T >
struct weighted_list< W, T >
struct weighted_int_list< T >
struct weighted_float_list< T >
Macros
#define CATA_SRC_WEIGHTED_LIST_H
Functions
template<typename W , typename T >
void load_weighted_list (const JsonValue &jsv, weighted_list< W, T > &list, W default_weight)
Macro Definition Documentation
CATA_SRC_WEIGHTED_LIST_H
#define CATA_SRC_WEIGHTED_LIST_H
Definition at line 3 of file weighted_list.h.
Function Documentation
load_weighted_list()
template<typename W , typename T > void load_weighted_list (const JsonValue & jsv, weighted_list< W, T > & list, W default_weight)
Definition at line 293 of file weighted_list.h.
 {
     for( const JsonValue entry : jsv.get_array() ) {
         if( entry.test_array() ) {
             std::pair<T, W> p;
             entry.read( p, true );
             list.add( p.first, p.second );
         } else {
             T val;
             entry.read( val );
             list.add( val, default_weight );
         }
     }
 }
References weighted_list< W, T >::add(), and JsonValue::get_array().
Referenced by mapgen_value< Id >::distribution_source::distribution_source(), jmapgen_monster::jmapgen_monster(), jmapgen_nested::jmapgen_nested(), and load_transform_results().