Cataclysm DDA: src/widget.h File Reference
widget.h File Reference
#include <string>
#include <vector>
#include "avatar.h"
#include "enum_traits.h"
#include "generic_factory.h"
#include "panels.h"
#include "string_id.h"
#include "translations.h"
#include "type_id.h"
Classes
struct enum_traits< widget_var >
struct enum_traits< cardinal_direction >
struct enum_traits< bodypart_status >
struct enum_traits< widget_alignment >
struct widget_clause
class widget
Macros
#define CATA_SRC_WIDGET_H
Enumerations
enum class widget_var : int {
focus , move , move_remainder , move_cost ,
pain , sound , speed , stamina ,
sleepiness , health , mana , max_mana ,
power_percentage , log_power_balance , morale_level , weariness_level ,
weary_transition_level , stat_str , stat_dex , stat_int ,
stat_per , bp_hp , bp_encumb , bp_warmth ,
bp_wetness , mood , cardio_fit , cardio_acc ,
carry_weight , activity_text , body_graph , body_graph_temp ,
body_graph_encumb , body_graph_status , body_graph_wet , bp_armor_outer_text ,
carry_weight_text , compass_text , compass_legend_text , date_text ,
env_temp_text , mood_text , move_count_mode_text , overmap_loc_text ,
overmap_text , pain_text , place_text , power_text ,
power_balance_text , safe_mode_text , safe_mode_classic_text , style_text ,
sundial_text , sundial_time_text , time_text , veh_azimuth_text ,
veh_cruise_text , veh_fuel_text , weariness_text , weary_malus_text ,
weather_text , wielding_text , wielding_simple_text , wielding_mode_text ,
wielding_ammo_text , wind_text , last
}
enum class cardinal_direction : int {
NORTH = 0 , NORTHEAST = 1 , EAST = 2 , SOUTHEAST = 3 ,
SOUTH = 4 , SOUTHWEST = 5 , WEST = 6 , NORTHWEST = 7 ,
LOCAL = 8 , num_cardinal_directions
}
enum class bodypart_status : int {
BITTEN , INFECTED , BROKEN , SPLINTED ,
BANDAGED , DISINFECTED , BLEEDING , num_bodypart_status
}
enum class widget_alignment : int { LEFT , CENTER , RIGHT , num_widget_alignments }
Functions
std::string format_widget_multiline (const std::vector< std::string > &keys, int max_height, int width, int &height, bool join=false)
Macro Definition Documentation
CATA_SRC_WIDGET_H
#define CATA_SRC_WIDGET_H
Definition at line 3 of file widget.h.
Enumeration Type Documentation
bodypart_status
enum bodypart_status : int strong
Enumerator
BITTEN
INFECTED
BROKEN
SPLINTED
BANDAGED
DISINFECTED
BLEEDING
num_bodypart_status
Definition at line 119 of file widget.h.
                            : int {
     BITTEN,
     INFECTED,
     BROKEN,
     SPLINTED,
     BANDAGED,
     DISINFECTED,
     BLEEDING,
     num_bodypart_status
 };
cardinal_direction
enum cardinal_direction : int strong
Enumerator
NORTH
NORTHEAST
EAST
SOUTHEAST
SOUTH
SOUTHWEST
WEST
NORTHWEST
LOCAL
num_cardinal_directions
Definition at line 98 of file widget.h.
                               : int {
     NORTH = 0,
     NORTHEAST = 1,
     EAST = 2,
     SOUTHEAST = 3,
     SOUTH = 4,
     SOUTHWEST = 5,
     WEST = 6,
     NORTHWEST = 7,
     LOCAL = 8,
     num_cardinal_directions
 };
widget_alignment
enum widget_alignment : int strong
Enumerator
LEFT
CENTER
RIGHT
num_widget_alignments
Definition at line 136 of file widget.h.
                             : int {
     LEFT,
     CENTER,
     RIGHT,
     num_widget_alignments
 };
widget_var
enum widget_var : int strong
Enumerator
focus
move
move_remainder
move_cost
pain
sound
speed
stamina
sleepiness
health
mana
max_mana
power_percentage
log_power_balance
morale_level
weariness_level
weary_transition_level
stat_str
stat_dex
stat_int
stat_per
bp_hp
bp_encumb
bp_warmth
bp_wetness
mood
cardio_fit
cardio_acc
carry_weight
activity_text
body_graph
body_graph_temp
body_graph_encumb
body_graph_status
body_graph_wet
bp_armor_outer_text
carry_weight_text
compass_text
compass_legend_text
date_text
env_temp_text
mood_text
move_count_mode_text
overmap_loc_text
overmap_text
pain_text
place_text
power_text
power_balance_text
safe_mode_text
safe_mode_classic_text
style_text
sundial_text
sundial_time_text
time_text
veh_azimuth_text
veh_cruise_text
veh_fuel_text
weariness_text
weary_malus_text
weather_text
wielding_text
wielding_simple_text
wielding_mode_text
wielding_ammo_text
wind_text
last
Definition at line 18 of file widget.h.
                       : int {
     focus,          // Current focus, integer
     move,           // Current move counter, integer
     move_remainder, // Current remaining moves, integer
     move_cost,      // Modified base movement cost, integer (from run_cost)
     pain,           // Current perceived pain, integer
     sound,          // Current sound level, integer
     speed,          // Current speed, integer
     stamina,        // Current stamina 0-10000, greater being fuller stamina reserves
     sleepiness,        // Current sleepiness, integer
     health,         // Current hidden health value, -200 to +200
     mana,           // Current available mana, integer
     max_mana,       // Current maximum mana, integer
     power_percentage, // Bionic power, relative to capacity
     log_power_balance, // Logarithm of bionic power balance
     morale_level,   // Current morale level, integer (may be negative)
     weariness_level, // Current weariness level, integer
     weary_transition_level, // Current weariness level, integer
     stat_str,       // Base STR (strength) stat, integer
     stat_dex,       // Base DEX (dexterity) stat, integer
     stat_int,       // Base INT (intelligence) stat, integer
     stat_per,       // Base PER (perception) stat, integer
     bp_hp,          // Current hit points of given "bodypart", integer
     bp_encumb,      // Current encumbrance of given "bodypart", integer
     bp_warmth,      // Current warmth of given "bodypart", integer
     bp_wetness,     // Current wetness of given "bodypart", integer
     mood,           // TODO
     cardio_fit,     // Cardio fitness, integer near BMR
     cardio_acc,     // Cardio accumulator, integer
     carry_weight,   // Weight carried, relative to capacity, in % (0 - >100)
     // Text vars
     activity_text,  // Activity level text, color string
     body_graph,     // Body graph showing color-coded body part health
     body_graph_temp,     // Body graph showing color-coded body part temperature
     body_graph_encumb,     // Body graph showing color-coded body part encumbrance
     body_graph_status,     // Body graph showing color-coded body part status (bite, bleeding, ...)
     body_graph_wet,        // Body graph showing color-coded body part wetness
     bp_armor_outer_text, // Outermost armor on body part, with color/damage bars
     carry_weight_text,   // Weight carried, relative to capacity, in %
     compass_text,   // Compass / visible threats by cardinal direction
     compass_legend_text, // Names of visible creatures that appear on the compass
     date_text,      // Current date, in terms of day within season
     env_temp_text,  // Environment temperature, if character has thermometer
     mood_text,      // Mood as a text emote, color string
     move_count_mode_text, // Movement counter and mode letter like "50(R)", color string
     overmap_loc_text,// Local overmap position, pseudo latitude/longitude with Z-level
     overmap_text,   // Local overmap and mission marker, multi-line color string
     pain_text,      // Pain description text, color string
     place_text,     // Place name in world where character is
     power_text,     // Remaining power from bionics, color string
     power_balance_text, // Power balance during the last turn
     safe_mode_text, // Safe mode text, color string
     safe_mode_classic_text, // Safe mode text, classic mode color string.
     style_text,     // Active martial arts style name
     sundial_text,   // Sundial representing the time of day
     sundial_time_text,   // Current time - exact if character has a watch, sundial otherwise
     time_text,      // Current time - exact if character has a watch, approximate otherwise
     veh_azimuth_text, // Azimuth or heading in degrees, string
     veh_cruise_text, // Current/target cruising speed in vehicle, color string
     veh_fuel_text,  // Current/total fuel for active vehicle engine, color string
     weariness_text, // Weariness description text, color string
     weary_malus_text, // Weariness malus or penalty
     weather_text,   // Weather/sky conditions (if visible), color string
     wielding_text,  // Currently wielded weapon or item name
     wielding_simple_text,  // Currently wielded weapon or item name, without mode and ammo
     wielding_mode_text,  // Currently wielded weapon's firing mode
     wielding_ammo_text,  // Currently wielded weapon's ammo
     wind_text,      // Wind level and direction, color string
     last // END OF ENUMS
 };
Function Documentation
format_widget_multiline()
std::string format_widget_multiline (const std::vector< std::string > & keys, int max_height, int width, int & height, bool join = false)
Definition at line 1870 of file widget.cpp.
 {
     std::string ret;
     height = 0;
     // For single-line text, just lay everything on the same line
     if( width <= 0 && max_height == 1 ) {
         width = INT_MAX;
     }
     const int h_max = max_height == 0 ? INT_MAX : max_height;
     const int nsize = keys.size();
     for( int row = 0, nidx = 0; row < h_max && nidx < nsize; row++ ) {
         int wavail = width;
         int nwidth = utf8_width( keys[nidx], true );
         bool startofline = true;
         while( nidx < nsize && ( wavail > nwidth || startofline ) ) {
             startofline = false;
             wavail -= nwidth;
             ret += keys[nidx];
             nidx++;
             if( nidx < nsize ) {
                 nwidth = utf8_width( keys[nidx], true );
                 if( wavail > nwidth ) {
                     ret += join ? ", " : "  ";
                     wavail -= 2;
                 }
             }
         }
         // Newline, if not the last row
         if( row < h_max - 1 ) {
             ret += "\n";
         }
         height++;
     }
     return ret;
 }
References cata::hash64_detail::ret, and utf8_width().
Referenced by display::colorized_compass_legend_text(), widget::sym_text_cond(), and widget::text_cond().