Cataclysm DDA: src/widget.cpp File Reference
widget.cpp File Reference
#include "widget.h"
#include "character_martial_arts.h"
#include "color.h"
#include "condition.h"
#include "display.h"
#include "generic_factory.h"
#include "json.h"
#include "output.h"
#include "overmapbuffer.h"
#include "npctalk.h"
Namespaces
anonymous_namespace{widget.cpp}
io
Functions
template<>
std::string io::enum_to_string< widget_var > (widget_var data)
template<>
std::string io::enum_to_string< cardinal_direction > (cardinal_direction dir)
template<>
std::string io::enum_to_string< bodypart_status > (bodypart_status stat)
template<>
std::string io::enum_to_string< widget_alignment > (widget_alignment align)
static int custom_draw_func (const draw_args &args)
static void set_height_for_widget (const widget_id &id, int height)
static std::string append_line (const std::string &line, bool first_row, int max_width, const translation &label, int label_width, const std::string &_separator, widget_alignment text_align, widget_alignment label_align, bool skip_pad)
std::string format_widget_multiline (const std::vector< std::string > &keys, int max_height, int width, int &height, bool join)
Variables
static const flag_id json_flag_W_DISABLED_BY_DEFAULT ("W_DISABLED_BY_DEFAULT")
static const flag_id json_flag_W_DISABLED_WHEN_EMPTY ("W_DISABLED_WHEN_EMPTY")
static const flag_id json_flag_W_DYNAMIC_HEIGHT ("W_DYNAMIC_HEIGHT")
static const flag_id json_flag_W_LABEL_NONE ("W_LABEL_NONE")
static const flag_id json_flag_W_NO_PADDING ("W_NO_PADDING")
static const std::string default_separator = ": "
generic_factory< widget > anonymous_namespace{widget.cpp}::widget_factory ("widgets")
Function Documentation
append_line()
static std::string append_line (const std::string & line, bool first_row, int max_width, const translation & label, int label_width, const std::string & _separator, widget_alignment text_align, widget_alignment label_align, bool skip_pad) static
Definition at line 1605 of file widget.cpp.
 {
     // utf8_width subtracts 1 for each newline; add it back for multiline widgets
     const int newline_fix = !line.empty() && line.back() == '\n' ? 1 : 0;
     // Prepare label
     int lbl_w = 0;
     std::string lbl;
     if( first_row && !label.empty() ) {
         lbl = label.translated();
         lbl_w = utf8_width( lbl, true );
         lbl.append( _separator );
     }
     // Don't process label width if label_width = 0 for empty labels
     if( !skip_pad && ( label_width > 0 || !label.empty() ) ) {
         lbl_w += _separator.length();
         label_width += _separator.length();
         // Use empty spaces in place of label if none exist
         if( label.empty() ) {
             lbl.append( label_width, ' ' );
             lbl_w = label_width;
         }
     }
     // Prepare text
     int txt_w = 0;
     std::string txt;
     if( !line.empty() ) {
         txt = line;
         txt_w = utf8_width( txt, true ) + newline_fix;
         if( line.back() == '\n' ) {
             txt.pop_back();
         }
     }
     // Label padding
     if( !skip_pad && label_width > lbl_w ) {
         const int lpad = label_width - lbl_w;
         // Left side
         int padding = 0;
         if( label_align != widget_alignment::LEFT ) {
             padding = label_align == widget_alignment::RIGHT ? lpad : ( lpad / 2 ) + lpad % 2;
         }
         lbl.insert( 0, padding, ' ' );
         lbl_w += padding;
         // Right side
         padding = 0;
         if( label_align != widget_alignment::RIGHT ) {
             padding = label_align == widget_alignment::LEFT ? lpad : lpad / 2;
         }
         lbl.append( padding, ' ' );
         lbl_w += padding;
     }
     // If the text is too long, start eating the free space next to the label.
     // This only works because labels are not colorized (no color tags).
     if( txt_w + lbl_w > max_width ) {
         std::wstring tmplbl = utf8_to_wstr( lbl );
         for( int i = tmplbl.size() - 1; txt_w + lbl_w > max_width && i > 0 && tmplbl[i] == ' ' &&
              tmplbl[i - 1] != ':'; i-- ) {
             tmplbl.pop_back();
             lbl_w--;
         }
         lbl = wstr_to_utf8( tmplbl );
     }
     // Text padding
     if( !skip_pad && max_width - lbl_w > txt_w ) {
         const int tpad = ( max_width - lbl_w ) - txt_w;
         // Left side
         int padding = 0;
         if( text_align != widget_alignment::LEFT &&
             // Don't pad left if the label is also right-aligned
             ( text_align == widget_alignment::CENTER || label_align != widget_alignment::RIGHT ) ) {
             padding = text_align == widget_alignment::RIGHT ? tpad : ( tpad / 2 ) + tpad % 2;
         }
         txt.insert( 0, padding, ' ' );
         txt_w += padding;
         // Right side
         padding = 0;
         if( text_align != widget_alignment::RIGHT ) {
             padding = text_align == widget_alignment::LEFT ? tpad : tpad / 2;
         }
         txt.append( padding, ' ' );
         txt_w += padding;
     }
     // Final assembly
     std::string ret = lbl + txt;
     if( !skip_pad && text_align == widget_alignment::RIGHT ) {
         const int leftover = max_width - ( lbl_w + txt_w );
         if( leftover > 0 ) {
             ret.insert( 0, leftover, ' ' );
         }
     }
     if( newline_fix == 1 ) {
         ret.append( 1, '\n' );
     }
     return ret;
 }
References CENTER, LEFT, line(), cata::hash64_detail::ret, RIGHT, utf8_to_wstr(), utf8_width(), and wstr_to_utf8().
Referenced by widget::layout().
custom_draw_func()
static int custom_draw_func (const draw_args & args) static
Definition at line 914 of file widget.cpp.
 {
     const avatar &u = args._ava;
     const catacurses::window &w = args._win;
     widget *wgt = args.get_widget();
     // Get full window width
     const int width = catacurses::getmaxx( w );
     // Leave 1 character space for margin on left and right
     const int margin = 1;
     const int widt = width - 2 * margin;
     // Whether to subtract height lines from the drawn panel space
     const bool disable_empty = wgt->has_flag( json_flag_W_DISABLED_WHEN_EMPTY );
     // Quit if there is nothing to draw or no space to draw it
     if( wgt == nullptr || width <= 0 ) {
         return 0;
     }
     int height_diff = 0;
     const bool skip_pad = wgt->has_flag( json_flag_W_NO_PADDING );
     werase( w );
     if( wgt->_style == "sidebar" ) {
         // noop
     } else if( wgt->_style == "layout" ) {
         if( wgt->_arrange == "rows" ) {
             // Layout widgets in rows
             std::vector<string_id<widget>> widgets = wgt->widgets( !wgt->_clauses.empty() );
             int row_num = 0;
             for( const widget_id &row_wid : widgets ) {
                 widget row_widget = row_wid.obj();
                 const std::string txt = row_widget.layout( u, widt, wgt->_label_width,
                                         skip_pad || row_wid->has_flag( json_flag_W_NO_PADDING ) );
                 if( row_wid->has_flag( json_flag_W_DISABLED_WHEN_EMPTY ) && txt.empty() ) {
                     // reclaim the skipped height in the sidebar
                     height_diff -= row_widget._height;
                 } else {
                     // draw normally
                     row_num = widget::custom_draw_multiline( txt, w, margin, widt, row_num );
                 }
             }
             if( wgt->has_flag( json_flag_W_DYNAMIC_HEIGHT ) ) {
                 wgt->_height = row_num;
             }
             if( disable_empty && widgets.empty() ) {
                 // reclaim the skipped height in the sidebar
                 height_diff -= wgt->_height;
             }
         } else {
             // Layout widgets in columns
             // For now, this is the default when calling layout()
             // So, just layout self on a single line
             const std::string txt = wgt->layout( u, widt, wgt->_label_width, skip_pad );
             if( disable_empty && txt.empty() ) {
                 // reclaim the skipped height in the sidebar
                 height_diff -= wgt->_height;
             } else {
                 // draw normally
                 widget::custom_draw_multiline( txt, w, margin, widt, 0 );
             }
         }
     } else {
         // No layout, just a widget
         const std::string txt = wgt->layout( u, widt, 0, skip_pad );
         if( disable_empty && txt.empty() ) {
             // reclaim the skipped height in the sidebar
             height_diff -= wgt->_height;
         } else {
             // draw normally
             widget::custom_draw_multiline( txt, w, margin, widt, 0 );
         }
     }
     wnoutrefresh( w );
     return height_diff;
 }
References widget::_arrange, draw_args::_ava, widget::_clauses, widget::_height, widget::_label_width, widget::_style, draw_args::_win, widget::custom_draw_multiline(), draw_args::get_widget(), catacurses::getmaxx(), widget::has_flag(), json_flag_W_DISABLED_WHEN_EMPTY, json_flag_W_DYNAMIC_HEIGHT, json_flag_W_NO_PADDING, widget::layout(), u, catacurses::werase(), widget::widgets(), and catacurses::wnoutrefresh().
Referenced by widget::get_window_panel().
format_widget_multiline()
std::string format_widget_multiline (const std::vector< std::string > & keys, int max_height, int width, int & height, bool join)
Definition at line 1870 of file widget.cpp.
 {
     std::string ret;
     height = 0;
     // For single-line text, just lay everything on the same line
     if( width <= 0 && max_height == 1 ) {
         width = INT_MAX;
     }
     const int h_max = max_height == 0 ? INT_MAX : max_height;
     const int nsize = keys.size();
     for( int row = 0, nidx = 0; row < h_max && nidx < nsize; row++ ) {
         int wavail = width;
         int nwidth = utf8_width( keys[nidx], true );
         bool startofline = true;
         while( nidx < nsize && ( wavail > nwidth || startofline ) ) {
             startofline = false;
             wavail -= nwidth;
             ret += keys[nidx];
             nidx++;
             if( nidx < nsize ) {
                 nwidth = utf8_width( keys[nidx], true );
                 if( wavail > nwidth ) {
                     ret += join ? ", " : "  ";
                     wavail -= 2;
                 }
             }
         }
         // Newline, if not the last row
         if( row < h_max - 1 ) {
             ret += "\n";
         }
         height++;
     }
     return ret;
 }
References cata::hash64_detail::ret, and utf8_width().
Referenced by display::colorized_compass_legend_text(), widget::sym_text_cond(), and widget::text_cond().
set_height_for_widget()
static void set_height_for_widget (const widget_id & id, int height) static
Definition at line 1076 of file widget.cpp.
 {
     const std::vector<widget> &wlist = widget::get_all();
     auto iter = std::find_if( wlist.begin(), wlist.end(), [&id]( const widget & w ) {
         return w.getId() == id;
     } );
     if( iter != wlist.end() ) {
         const_cast<widget *>( &*iter )->_height = height;
     }
 }
References widget::get_all().
Referenced by widget::color_text_function_string(), widget::layout(), widget::sym_text_cond(), and widget::text_cond().
Variable Documentation
default_separator
const std::string default_separator = ": " static
Definition at line 20 of file widget.cpp.
Referenced by widget::load().
json_flag_W_DISABLED_BY_DEFAULT
const flag_id json_flag_W_DISABLED_BY_DEFAULT("W_DISABLED_BY_DEFAULT") ("W_DISABLED_BY_DEFAULT") static
Referenced by widget::get_window_panel().
json_flag_W_DISABLED_WHEN_EMPTY
const flag_id json_flag_W_DISABLED_WHEN_EMPTY("W_DISABLED_WHEN_EMPTY") ("W_DISABLED_WHEN_EMPTY") static
Referenced by custom_draw_func(), and widget::layout().
json_flag_W_DYNAMIC_HEIGHT
const flag_id json_flag_W_DYNAMIC_HEIGHT("W_DYNAMIC_HEIGHT") ("W_DYNAMIC_HEIGHT") static
Referenced by widget::color_text_function_string(), custom_draw_func(), widget::layout(), widget::sym_text_cond(), and widget::text_cond().
json_flag_W_LABEL_NONE
const flag_id json_flag_W_LABEL_NONE("W_LABEL_NONE") ("W_LABEL_NONE") static
Referenced by widget::finalize_label_width_recursive(), widget::layout(), and widget::load().
json_flag_W_NO_PADDING
const flag_id json_flag_W_NO_PADDING("W_NO_PADDING") ("W_NO_PADDING") static
Referenced by custom_draw_func(), and widget::layout().