Cataclysm DDA: src/wish.cpp File Reference
wish.cpp File Reference
#include "debug_menu.h"
#include <algorithm>
#include <cstddef>
#include <iterator>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <utility>
#include <vector>
#include "bionics.h"
#include "calendar.h"
#include "catacharset.h"
#include "character.h"
#include "color.h"
#include "cursesdef.h"
#include "debug.h"
#include "effect.h"
#include "enums.h"
#include "game.h"
#include "input.h"
#include "input_context.h"
#include "item.h"
#include "item_factory.h"
#include "itype.h"
#include "localized_comparator.h"
#include "map.h"
#include "monster.h"
#include "monstergenerator.h"
#include "mtype.h"
#include "mutation.h"
#include "output.h"
#include "point.h"
#include "proficiency.h"
#include "skill.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "text_snippets.h"
#include "translations.h"
#include "type_id.h"
#include "ui.h"
#include "uistate.h"
#include "units.h"
Classes
class wish_mutate_callback
class wish_monster_callback
class wish_item_callback
Functions
static item wishitem_produce (const itype &type, std::string &flags, bool incontainer)
Variables
static const efftype_id effect_pet ("pet")
Function Documentation
wishitem_produce()
static item wishitem_produce (const itype & type, std::string & flags, bool incontainer) static
Definition at line 784 of file wish.cpp.
 {
     item granted( &type, calendar::turn );
     granted.unset_flags();
     for( const auto &tag : debug_menu::string_to_iterable<std::vector<std::string>>( flags, " " ) ) {
         const flag_id flag( tag );
         if( flag.is_valid() ) {
             granted.set_flag( flag_id( tag ) );
         }
     }
     if( incontainer ) {
         granted = granted.in_its_container();
     }
     // If the item has an ammunition, this loads it to capacity, including magazines.
     if( !granted.ammo_default().is_null() ) {
         granted.ammo_set( granted.ammo_default(), -1 );
     }
     return granted;
 }
References item::ammo_default(), item::ammo_set(), item::in_its_container(), string_id< T >::is_null(), string_id< T >::is_valid(), item::set_flag(), debug_menu::string_to_iterable(), calendar::turn, and item::unset_flags().
Referenced by wish_item_callback::refresh(), and debug_menu::wishitem().
Variable Documentation
effect_pet
const efftype_id effect_pet("pet") ("pet") static
Referenced by debug_menu::wishmonster().