Cataclysm DDA: src/worldfactory.cpp File Reference
worldfactory.cpp File Reference
#include "worldfactory.h"
#include <algorithm>
#include <array>
#include <exception>
#include <iterator>
#include <memory>
#include <set>
#include <unordered_map>
#include <utility>
#include "cata_utility.h"
#include "catacharset.h"
#include "char_validity_check.h"
#include "color.h"
#include "cursesdef.h"
#include "debug.h"
#include "enums.h"
#include "filesystem.h"
#include "input_context.h"
#include "json.h"
#include "json_loader.h"
#include "mod_manager.h"
#include "output.h"
#include "path_info.h"
#include "point.h"
#include "sounds.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "text_snippets.h"
#include "translations.h"
#include "ui.h"
#include "ui_manager.h"
Functions
static std::string get_next_valid_worldname ()
static std::optional< std::string > prompt_world_name (const std::string &title, const std::string &cur_worldname)
static std::string get_opt_slider (int width, int current, int max, bool no_color, bool no_selector=false)
void load_world_option (const JsonObject &jo)
void load_external_option (const JsonObject &jo)
static bool isForbidden (const std::string_view candidate)
Variables
std::unique_ptr< worldfactory > world_generator
static const int max_worldname_len = 32
Max utf-8 character worldname length.
Function Documentation
get_next_valid_worldname()
static std::string get_next_valid_worldname () static
Definition at line 66 of file worldfactory.cpp.
 {
     return SNIPPET.expand( "<world_name>" );
 }
References snippet_library::expand(), and SNIPPET.
Referenced by worldfactory::init(), worldfactory::pick_random_name(), prompt_world_name(), and WORLD::WORLD().
get_opt_slider()
static std::string get_opt_slider (int width, int current, int max, bool no_color, bool no_selector = false) static
Definition at line 1466 of file worldfactory.cpp.
 {
     int new_cur = clamp<int>( std::round( ( width * current ) / static_cast<float>( max ) ),
                               0, width - 1 );
     if( no_selector ) {
         new_cur = -2;
     }
     std::string ret;
     for( int i = 0; i < width; i++ ) {
         char ch = '-';
         if( i == new_cur - 1 ) {
             ch = '<';
         } else if( i == new_cur + 1 ) {
             ch = '>';
         } else if( i == new_cur ) {
             ch = '|';
         }
         if( !no_color && ch != '-' ) {
             ret.append( colorize( std::string( 1, ch ), c_yellow ) );
         } else {
             ret.append( 1, ch );
         }
     }
     return ret;
 }
References c_yellow, colorize(), max(), cata::hash64_detail::ret, and round().
Referenced by worldfactory::show_worldgen_basic().
isForbidden()
static bool isForbidden (const std::string_view candidate) static
Definition at line 2080 of file worldfactory.cpp.
 {
     return candidate.find( PATH_INFO::worldoptions() ) != std::string::npos ||
            candidate.find( "mods.json" ) != std::string::npos;
 }
References PATH_INFO::worldoptions().
Referenced by worldfactory::delete_world().
load_external_option()
void load_external_option (const JsonObject & jo)
Definition at line 2007 of file worldfactory.cpp.
 {
     std::string name = jo.get_string( "name" );
     std::string stype = jo.get_string( "stype" );
     options_manager &opts = get_options();
     if( !opts.has_option( name ) ) {
         translation sinfo;
         jo.get_member( "info" ).read( sinfo );
         opts.add_external( name, "external_options", stype, sinfo, sinfo );
     }
     options_manager::cOpt &opt = opts.get_option( name );
     if( stype == "float" ) {
         opt.setValue( static_cast<float>( jo.get_float( "value" ) ) );
     } else if( stype == "int" ) {
         opt.setValue( jo.get_int( "value" ) );
     } else if( stype == "bool" ) {
         if( jo.get_bool( "value" ) ) {
             opt.setValue( "true" );
         } else {
             opt.setValue( "false" );
         }
     } else if( stype == "string" || stype == "string_input" ) {
         opt.setValue( jo.get_string( "value" ) );
     } else {
         jo.throw_error_at( "stype", "Unknown or unsupported stype for external option" );
     }
     // Just visit this member if it exists
     if( jo.has_member( "info" ) ) {
         jo.get_string( "info" );
     }
     options_manager::update_options_cache();
 }
References options_manager::add_external(), JsonObject::get_bool(), JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_member(), options_manager::get_option(), get_options(), JsonObject::get_string(), JsonObject::has_member(), options_manager::has_option(), om_direction::name(), JsonValue::read(), options_manager::cOpt::setValue(), JsonObject::throw_error_at(), and options_manager::update_options_cache().
Referenced by DynamicDataLoader::initialize().
load_world_option()
void load_world_option (const JsonObject & jo)
Definition at line 1995 of file worldfactory.cpp.
 {
     JsonArray arr = jo.get_array( "options" );
     if( arr.empty() ) {
         jo.throw_error_at( "options", "no options specified" );
     }
     for( const std::string line : arr ) {
         get_options().get_option( line ).setValue( "true" );
     }
 }
References JsonArray::empty(), JsonObject::get_array(), options_manager::get_option(), get_options(), line(), options_manager::cOpt::setValue(), and JsonObject::throw_error_at().
Referenced by DynamicDataLoader::initialize().
prompt_world_name()
static std::optional<std::string> prompt_world_name (const std::string & title, const std::string & cur_worldname) static
Definition at line 182 of file worldfactory.cpp.
 {
     string_input_popup popup;
     popup.max_length( max_worldname_len ).title( title ).text( cur_worldname );
     input_context ctxt( "STRING_INPUT" );
     popup.description( string_format(
                            _( "Press [<color_c_yellow>%s</color>] to randomize the world name." ),
                            ctxt.get_desc( "PICK_RANDOM_WORLDNAME", 1U ) ) );
     popup.custom_actions.emplace_back( "PICK_RANDOM_WORLDNAME", translation() );
     popup.add_callback( "PICK_RANDOM_WORLDNAME", [&popup]() {
         popup.text( get_next_valid_worldname() );
         return true;
     } );
     std::string message = popup.query_string();
     return !popup.canceled() ? std::optional<std::string>( message ) : std::optional<std::string>();
 }
References _, input_context::get_desc(), get_next_valid_worldname(), max_worldname_len, mapgen_defer::message, popup(), string_format(), and music::title.
Referenced by worldfactory::show_worldgen_advanced(), and worldfactory::show_worldgen_basic().
Variable Documentation
max_worldname_len
const int max_worldname_len = 32 static
Max utf-8 character worldname length.
0 index is inclusive.
Definition at line 42 of file worldfactory.cpp.
Referenced by prompt_world_name().
world_generator
std::unique_ptr<worldfactory> world_generator
Definition at line 36 of file worldfactory.cpp.
Referenced by game::check_mod_data(), avatar::create(), main_menu::display_sub_menu(), game::do_regular_action(), conditional_fun::anonymous_namespace{condition.cpp}::f_mod_is_loaded(), game::game(), debug_menu::is_debug_character(), game::list_active_saves(), game::load(), main_menu::load_character_tab(), main_menu::load_game(), game::load_world_modfiles(), worldfactory::make_new_world(), anonymous_namespace{math_parser_diag.cpp}::mod_order_eval(), game_info::mods_loaded(), main_menu::new_character_tab(), main_menu::opening_screen(), game::quickload(), avatar::randomize(), game::save(), WORLD::save(), worldfactory::set_active_world(), set_scenario(), options_manager::show(), worldfactory::show_worldgen_basic(), WORLD::WORLD(), PATH_INFO::world_base_save_path(), PATH_INFO::world_base_save_path_path(), main_menu::world_tab(), and game::write_memorial_file().