Cataclysm DDA: src/worldfactory.h File Reference
worldfactory.h File Reference
#include <cstddef>
#include <functional>
#include <iosfwd>
#include <map>
#include <memory>
#include <vector>
#include <string>
#include "cuboid_rectangle.h"
#include "options.h"
#include "pimpl.h"
#include "type_id.h"
Classes
class save_t
struct WORLD
class worldfactory
Namespaces
catacurses
Contains the curses interface used by the whole game.
Macros
#define CATA_SRC_WORLDFACTORY_H
Functions
void load_world_option (const JsonObject &jo)
void load_external_option (const JsonObject &jo)
Variables
std::unique_ptr< worldfactory > world_generator
Macro Definition Documentation
CATA_SRC_WORLDFACTORY_H
#define CATA_SRC_WORLDFACTORY_H
Definition at line 3 of file worldfactory.h.
Function Documentation
load_external_option()
void load_external_option (const JsonObject & jo)
Definition at line 2007 of file worldfactory.cpp.
 {
     std::string name = jo.get_string( "name" );
     std::string stype = jo.get_string( "stype" );
     options_manager &opts = get_options();
     if( !opts.has_option( name ) ) {
         translation sinfo;
         jo.get_member( "info" ).read( sinfo );
         opts.add_external( name, "external_options", stype, sinfo, sinfo );
     }
     options_manager::cOpt &opt = opts.get_option( name );
     if( stype == "float" ) {
         opt.setValue( static_cast<float>( jo.get_float( "value" ) ) );
     } else if( stype == "int" ) {
         opt.setValue( jo.get_int( "value" ) );
     } else if( stype == "bool" ) {
         if( jo.get_bool( "value" ) ) {
             opt.setValue( "true" );
         } else {
             opt.setValue( "false" );
         }
     } else if( stype == "string" || stype == "string_input" ) {
         opt.setValue( jo.get_string( "value" ) );
     } else {
         jo.throw_error_at( "stype", "Unknown or unsupported stype for external option" );
     }
     // Just visit this member if it exists
     if( jo.has_member( "info" ) ) {
         jo.get_string( "info" );
     }
     options_manager::update_options_cache();
 }
References options_manager::add_external(), JsonObject::get_bool(), JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_member(), options_manager::get_option(), get_options(), JsonObject::get_string(), JsonObject::has_member(), options_manager::has_option(), om_direction::name(), JsonValue::read(), options_manager::cOpt::setValue(), JsonObject::throw_error_at(), and options_manager::update_options_cache().
Referenced by DynamicDataLoader::initialize().
load_world_option()
void load_world_option (const JsonObject & jo)
Definition at line 1995 of file worldfactory.cpp.
 {
     JsonArray arr = jo.get_array( "options" );
     if( arr.empty() ) {
         jo.throw_error_at( "options", "no options specified" );
     }
     for( const std::string line : arr ) {
         get_options().get_option( line ).setValue( "true" );
     }
 }
References JsonArray::empty(), JsonObject::get_array(), options_manager::get_option(), get_options(), line(), options_manager::cOpt::setValue(), and JsonObject::throw_error_at().
Referenced by DynamicDataLoader::initialize().
Variable Documentation
world_generator
std::unique_ptr<worldfactory> world_generator extern
Definition at line 36 of file worldfactory.cpp.
Referenced by game::check_mod_data(), avatar::create(), main_menu::display_sub_menu(), game::do_regular_action(), conditional_fun::anonymous_namespace{condition.cpp}::f_mod_is_loaded(), game::game(), debug_menu::is_debug_character(), game::list_active_saves(), game::load(), main_menu::load_character_tab(), main_menu::load_game(), game::load_world_modfiles(), worldfactory::make_new_world(), anonymous_namespace{math_parser_diag.cpp}::mod_order_eval(), game_info::mods_loaded(), main_menu::new_character_tab(), main_menu::opening_screen(), game::quickload(), avatar::randomize(), game::save(), WORLD::save(), worldfactory::set_active_world(), set_scenario(), options_manager::show(), worldfactory::show_worldgen_basic(), WORLD::WORLD(), PATH_INFO::world_base_save_path(), PATH_INFO::world_base_save_path_path(), main_menu::world_tab(), and game::write_memorial_file().