var searchData=
[
  ['cache_29585',['cache',['../classauto__pickup_1_1cache.html',1,'auto_pickup::cache'],['../structovermap__connection_1_1cache.html',1,'overmap_connection::cache']]],
  ['cached_5fstreams_29586',['cached_streams',['../structDynamicDataLoader_1_1cached__streams.html',1,'DynamicDataLoader']]],
  ['camp_5freference_29587',['camp_reference',['../structcamp__reference.html',1,'']]],
  ['can_5fplace_5fresult_29588',['can_place_result',['../structmutable__overmap__phase__remainder_1_1can__place__result.html',1,'mutable_overmap_phase_remainder']]],
  ['capture_5fdebugmsg_29589',['capture_debugmsg',['../classcapture__debugmsg.html',1,'']]],
  ['cardreader_5fexamine_5factor_29590',['cardreader_examine_actor',['../classcardreader__examine__actor.html',1,'']]],
  ['carried_5fpart_5fdata_29591',['carried_part_data',['../structvehicle__part_1_1carried__part__data.html',1,'vehicle_part']]],
  ['cast_5fspell_5factor_29592',['cast_spell_actor',['../classcast__spell__actor.html',1,'']]],
  ['cat_5fcache_29593',['cat_cache',['../structitem_1_1cat__cache.html',1,'item']]],
  ['cata_5fpath_29594',['cata_path',['../classcata__path.html',1,'']]],
  ['cata_5ftiles_29595',['cata_tiles',['../classcata__tiles.html',1,'']]],
  ['cata_5fvariant_29596',['cata_variant',['../classcata__variant.html',1,'']]],
  ['category_5fsnippets_29597',['category_snippets',['../structsnippet__library_1_1category__snippets.html',1,'snippet_library']]],
  ['cell_5ft_29598',['cell_t',['../structinventory__column_1_1cell__t.html',1,'inventory_column::cell_t'],['../classinventory__selector__preset_1_1cell__t.html',1,'inventory_selector_preset::cell_t']]],
  ['centroid_29599',['centroid',['../structcentroid.html',1,'']]],
  ['change_5fscent_5fiuse_29600',['change_scent_iuse',['../classchange__scent__iuse.html',1,'']]],
  ['change_5fsprite_5finventory_5fpreset_29601',['change_sprite_inventory_preset',['../classchange__sprite__inventory__preset.html',1,'']]],
  ['character_29602',['Character',['../classCharacter.html',1,'']]],
  ['character_5fid_29603',['character_id',['../classcharacter__id.html',1,'']]],
  ['character_5fmartial_5farts_29604',['character_martial_arts',['../classcharacter__martial__arts.html',1,'']]],
  ['character_5fmodifier_29605',['character_modifier',['../structcharacter__modifier.html',1,'']]],
  ['character_5foracle_5ft_29606',['character_oracle_t',['../classbehavior_1_1character__oracle__t.html',1,'behavior']]],
  ['choose_29607',['choose',['../structcata_1_1colony_1_1choose.html',1,'cata::colony&lt; element_type, element_allocator_type, element_skipfield_type &gt;::choose&lt; flag, is_true, is_false &gt;'],['../structcata_1_1list_1_1choose.html',1,'cata::list&lt; element_type, element_allocator_type &gt;::choose&lt; flag, IsTrue, IsFalse &gt;']]],
  ['choose_3c_20false_2c_20is_5ftrue_2c_20is_5ffalse_20_3e_29608',['choose&lt; false, is_true, is_false &gt;',['../structcata_1_1colony_1_1choose_3_01false_00_01is__true_00_01is__false_01_4.html',1,'cata::colony']]],
  ['choose_3c_20false_2c_20istrue_2c_20isfalse_20_3e_29609',['choose&lt; false, IsTrue, IsFalse &gt;',['../structcata_1_1list_1_1choose_3_01false_00_01IsTrue_00_01IsFalse_01_4.html',1,'cata::list']]],
  ['choose_3c_20true_2c_20is_5ftrue_2c_20is_5ffalse_20_3e_29610',['choose&lt; true, is_true, is_false &gt;',['../structcata_1_1colony_1_1choose_3_01true_00_01is__true_00_01is__false_01_4.html',1,'cata::colony']]],
  ['choose_3c_20true_2c_20istrue_2c_20isfalse_20_3e_29611',['choose&lt; true, IsTrue, IsFalse &gt;',['../structcata_1_1list_1_1choose_3_01true_00_01IsTrue_00_01IsFalse_01_4.html',1,'cata::list']]],
  ['chop_5flogs_5factivity_5factor_29612',['chop_logs_activity_actor',['../classchop__logs__activity__actor.html',1,'']]],
  ['chop_5fplanks_5factivity_5factor_29613',['chop_planks_activity_actor',['../classchop__planks__activity__actor.html',1,'']]],
  ['chop_5ftree_5factivity_5factor_29614',['chop_tree_activity_actor',['../classchop__tree__activity__actor.html',1,'']]],
  ['churn_5factivity_5factor_29615',['churn_activity_actor',['../classchurn__activity__actor.html',1,'']]],
  ['city_29616',['city',['../structcity.html',1,'']]],
  ['city_5freference_29617',['city_reference',['../structcity__reference.html',1,'']]],
  ['city_5fsettings_29618',['city_settings',['../structcity__settings.html',1,'']]],
  ['clear_5frubble_5factivity_5factor_29619',['clear_rubble_activity_actor',['../classclear__rubble__activity__actor.html',1,'']]],
  ['cli_5fopts_29620',['cli_opts',['../structanonymous__namespace_02main_8cpp_03_1_1cli__opts.html',1,'anonymous_namespace{main.cpp}']]],
  ['client_29621',['client',['../classcataimgui_1_1client.html',1,'cataimgui']]],
  ['climb_5fcost_29622',['climb_cost',['../structclimbing__aid_1_1climb__cost.html',1,'climbing_aid']]],
  ['climbing_5faid_29623',['climbing_aid',['../classclimbing__aid.html',1,'']]],
  ['clone_5fptr_29624',['clone_ptr',['../classcata_1_1clone__ptr.html',1,'cata']]],
  ['clone_5fptr_3c_20activity_5factor_20_3e_29625',['clone_ptr&lt; activity_actor &gt;',['../classcata_1_1clone__ptr.html',1,'cata']]],
  ['clone_5fptr_3c_20event_5fsource_20_3e_29626',['clone_ptr&lt; event_source &gt;',['../classcata_1_1clone__ptr.html',1,'cata']]],
  ['clone_5fptr_3c_20event_5fstatistic_3a_3aimpl_20_3e_29627',['clone_ptr&lt; event_statistic::impl &gt;',['../classcata_1_1clone__ptr.html',1,'cata']]],
  ['clone_5fptr_3c_20event_5ftransformation_3a_3aimpl_20_3e_29628',['clone_ptr&lt; event_transformation::impl &gt;',['../classcata_1_1clone__ptr.html',1,'cata']]],
  ['clone_5fptr_3c_20iexamine_5factor_20_3e_29629',['clone_ptr&lt; iexamine_actor &gt;',['../classcata_1_1clone__ptr.html',1,'cata']]],
  ['clone_5fptr_3c_20iuse_5factor_20_3e_29630',['clone_ptr&lt; iuse_actor &gt;',['../classcata_1_1clone__ptr.html',1,'cata']]],
  ['clone_5fptr_3c_20mattack_5factor_20_3e_29631',['clone_ptr&lt; mattack_actor &gt;',['../classcata_1_1clone__ptr.html',1,'cata']]],
  ['clothing_5fmod_29632',['clothing_mod',['../structclothing__mod.html',1,'']]],
  ['col_29633',['col',['../structuimenu_1_1col.html',1,'uimenu']]],
  ['collation_5fmeta_5ft_29634',['collation_meta_t',['../structcollation__meta__t.html',1,'']]],
  ['colony_29635',['colony',['../classcata_1_1colony.html',1,'cata']]],
  ['colony_3c_20item_20_2a_20_3e_29636',['colony&lt; item * &gt;',['../classcata_1_1colony.html',1,'cata']]],
  ['colony_3c_20item_20_3e_29637',['colony&lt; item &gt;',['../classcata_1_1colony.html',1,'cata']]],
  ['colony_3c_20std_3a_3aoptional_3c_20mapgen_5farguments_20_3e_20_3e_29638',['colony&lt; std::optional&lt; mapgen_arguments &gt; &gt;',['../classcata_1_1colony.html',1,'cata']]],
  ['colony_5fiterator_29639',['colony_iterator',['../classcata_1_1colony_1_1colony__iterator.html',1,'cata::colony']]],
  ['colony_5fiterator_3c_20false_20_3e_29640',['colony_iterator&lt; false &gt;',['../classcata_1_1colony_1_1colony__iterator.html',1,'cata::colony']]],
  ['colony_5freverse_5fiterator_29641',['colony_reverse_iterator',['../classcata_1_1colony_1_1colony__reverse__iterator.html',1,'cata::colony']]],
  ['color_5floader_29642',['color_loader',['../classcolor__loader.html',1,'']]],
  ['color_5fmanager_29643',['color_manager',['../classcolor__manager.html',1,'']]],
  ['color_5fstruct_29644',['color_struct',['../structcolor__manager_1_1color__struct.html',1,'color_manager']]],
  ['color_5ftag_5fparse_5fresult_29645',['color_tag_parse_result',['../structcolor__tag__parse__result.html',1,'']]],
  ['comestible_5ffiltered_5finventory_5fpreset_29646',['comestible_filtered_inventory_preset',['../classcomestible__filtered__inventory__preset.html',1,'']]],
  ['comestible_5finventory_5fpreset_29647',['comestible_inventory_preset',['../classcomestible__inventory__preset.html',1,'']]],
  ['comfort_5fresponse_5ft_29648',['comfort_response_t',['../structCharacter_1_1comfort__response__t.html',1,'Character']]],
  ['common_29649',['common',['../structtile__render__info_1_1common.html',1,'tile_render_info']]],
  ['common_5franged_5fdata_29650',['common_ranged_data',['../structcommon__ranged__data.html',1,'']]],
  ['comp_5frank_29651',['comp_rank',['../structcomp__rank.html',1,'']]],
  ['comp_5fselection_29652',['comp_selection',['../structcomp__selection.html',1,'']]],
  ['comp_5fselection_3c_20item_5fcomp_20_3e_29653',['comp_selection&lt; item_comp &gt;',['../structcomp__selection.html',1,'']]],
  ['comp_5fselection_3c_20tool_5fcomp_20_3e_29654',['comp_selection&lt; tool_comp &gt;',['../structcomp__selection.html',1,'']]],
  ['compare_5fiterators_29655',['compare_iterators',['../structjoins__tracker_1_1compare__iterators.html',1,'joins_tracker']]],
  ['compare_5ftimes_29656',['compare_times',['../structcompare__times.html',1,'']]],
  ['component_29657',['component',['../structcomponent.html',1,'']]],
  ['computer_29658',['computer',['../classcomputer.html',1,'']]],
  ['computer_5ffailure_29659',['computer_failure',['../structcomputer__failure.html',1,'']]],
  ['computer_5foption_29660',['computer_option',['../structcomputer__option.html',1,'']]],
  ['computer_5fsession_29661',['computer_session',['../classcomputer__session.html',1,'']]],
  ['condition_29662',['condition',['../structclimbing__aid_1_1condition.html',1,'climbing_aid']]],
  ['condition_5fparser_29663',['condition_parser',['../structanonymous__namespace_02condition_8cpp_03_1_1condition__parser.html',1,'anonymous_namespace{condition.cpp}']]],
  ['conditional_5fname_29664',['conditional_name',['../structconditional__name.html',1,'']]],
  ['conditional_5ft_29665',['conditional_t',['../structconditional__t.html',1,'']]],
  ['confidence_5frating_29666',['confidence_rating',['../structconfidence__rating.html',1,'']]],
  ['configurable_5fdistraction_29667',['configurable_distraction',['../structdistraction__manager_1_1configurable__distraction.html',1,'distraction_manager']]],
  ['connect_5fgroup_29668',['connect_group',['../structconnect__group.html',1,'']]],
  ['const_5fiterator_29669',['const_iterator',['../classJsonArray_1_1const__iterator.html',1,'JsonArray::const_iterator'],['../classJsonObject_1_1const__iterator.html',1,'JsonObject::const_iterator'],['../classTextJsonArray_1_1const__iterator.html',1,'TextJsonArray::const_iterator'],['../classTextJsonObject_1_1const__iterator.html',1,'TextJsonObject::const_iterator']]],
  ['construction_29670',['construction',['../structconstruction.html',1,'']]],
  ['construction_5fcategory_29671',['construction_category',['../structconstruction__category.html',1,'']]],
  ['construction_5fgroup_29672',['construction_group',['../structconstruction__group.html',1,'']]],
  ['consume_5factivity_5factor_29673',['consume_activity_actor',['../classconsume__activity__actor.html',1,'']]],
  ['consume_5fdrug_5fiuse_29674',['consume_drug_iuse',['../classconsume__drug__iuse.html',1,'']]],
  ['consumption_5fevent_29675',['consumption_event',['../structconsumption__event.html',1,'']]],
  ['container_5fdata_29676',['container_data',['../structcontainer__data.html',1,'']]],
  ['container_5finventory_5fselector_29677',['container_inventory_selector',['../classcontainer__inventory__selector.html',1,'']]],
  ['container_5fspawn_5ftest_5fdata_29678',['container_spawn_test_data',['../structcontainer__spawn__test__data.html',1,'']]],
  ['containspredicate_29679',['ContainsPredicate',['../structContainsPredicate.html',1,'']]],
  ['content_29680',['content',['../classmigration_1_1content.html',1,'migration']]],
  ['contents_5fchange_5fhandler_29681',['contents_change_handler',['../classcontents__change__handler.html',1,'']]],
  ['convert_29682',['convert',['../structcata__variant__detail_1_1convert.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3aachievement_5fid_20_3e_29683',['convert&lt; cata_variant_type::achievement_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1achievement__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3aactivity_5fid_20_3e_29684',['convert&lt; cata_variant_type::activity_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1activity__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3aaddiction_5fid_20_3e_29685',['convert&lt; cata_variant_type::addiction_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1addiction__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3abionic_5fid_20_3e_29686',['convert&lt; cata_variant_type::bionic_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1bionic__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3abody_5fpart_20_3e_29687',['convert&lt; cata_variant_type::body_part &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1body__part_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3abool_5f_20_3e_29688',['convert&lt; cata_variant_type::bool_ &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1bool___01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3acharacter_5fid_20_3e_29689',['convert&lt; cata_variant_type::character_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1character__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3achrono_5fseconds_20_3e_29690',['convert&lt; cata_variant_type::chrono_seconds &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1chrono__seconds_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3adebug_5fmenu_5findex_20_3e_29691',['convert&lt; cata_variant_type::debug_menu_index &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1debug__menu__index_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3aefftype_5fid_20_3e_29692',['convert&lt; cata_variant_type::efftype_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1efftype__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3afaction_5fid_20_3e_29693',['convert&lt; cata_variant_type::faction_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1faction__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3afield_5ftype_5fid_20_3e_29694',['convert&lt; cata_variant_type::field_type_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1field__type__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3afield_5ftype_5fstr_5fid_20_3e_29695',['convert&lt; cata_variant_type::field_type_str_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1field__type__str__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3aflag_5fid_20_3e_29696',['convert&lt; cata_variant_type::flag_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1flag__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3afurn_5fid_20_3e_29697',['convert&lt; cata_variant_type::furn_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1furn__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3afurn_5fstr_5fid_20_3e_29698',['convert&lt; cata_variant_type::furn_str_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1furn__str__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3aint_5f_20_3e_29699',['convert&lt; cata_variant_type::int_ &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1int___01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3aitem_5fgroup_5fid_20_3e_29700',['convert&lt; cata_variant_type::item_group_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1item__group__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3aitype_5fid_20_3e_29701',['convert&lt; cata_variant_type::itype_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1itype__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3amatype_5fid_20_3e_29702',['convert&lt; cata_variant_type::matype_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1matype__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3amongroup_5fid_20_3e_29703',['convert&lt; cata_variant_type::mongroup_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1mongroup__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3amove_5fmode_5fid_20_3e_29704',['convert&lt; cata_variant_type::move_mode_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1move__mode__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3amtype_5fid_20_3e_29705',['convert&lt; cata_variant_type::mtype_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1mtype__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3amutagen_5ftechnique_20_3e_29706',['convert&lt; cata_variant_type::mutagen_technique &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1mutagen__technique_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3amutation_5fcategory_5fid_20_3e_29707',['convert&lt; cata_variant_type::mutation_category_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1mutation__category__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3anested_5fmapgen_5fid_20_3e_29708',['convert&lt; cata_variant_type::nested_mapgen_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1nested__mapgen__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3anpc_5ftemplate_5fid_20_3e_29709',['convert&lt; cata_variant_type::npc_template_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1npc__template__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3aoter_5fid_20_3e_29710',['convert&lt; cata_variant_type::oter_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1oter__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3aoter_5ftype_5fstr_5fid_20_3e_29711',['convert&lt; cata_variant_type::oter_type_str_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1oter__type__str__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3aovermap_5fspecial_5fid_20_3e_29712',['convert&lt; cata_variant_type::overmap_special_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1overmap__special__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3apalette_5fid_20_3e_29713',['convert&lt; cata_variant_type::palette_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1palette__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3apoint_20_3e_29714',['convert&lt; cata_variant_type::point &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1point_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3aprofession_5fid_20_3e_29715',['convert&lt; cata_variant_type::profession_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1profession__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3aproficiency_5fid_20_3e_29716',['convert&lt; cata_variant_type::proficiency_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1proficiency__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3askill_5fid_20_3e_29717',['convert&lt; cata_variant_type::skill_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1skill__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3aspecies_5fid_20_3e_29718',['convert&lt; cata_variant_type::species_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1species__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3aspell_5fid_20_3e_29719',['convert&lt; cata_variant_type::spell_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1spell__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3astring_20_3e_29720',['convert&lt; cata_variant_type::string &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1string_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3ater_5ffurn_5ftransform_5fid_20_3e_29721',['convert&lt; cata_variant_type::ter_furn_transform_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1ter__furn__transform__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3ater_5fid_20_3e_29722',['convert&lt; cata_variant_type::ter_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1ter__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3ater_5fstr_5fid_20_3e_29723',['convert&lt; cata_variant_type::ter_str_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1ter__str__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3atrait_5fid_20_3e_29724',['convert&lt; cata_variant_type::trait_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1trait__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3atrap_5fid_20_3e_29725',['convert&lt; cata_variant_type::trap_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1trap__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3atrap_5fstr_5fid_20_3e_29726',['convert&lt; cata_variant_type::trap_str_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1trap__str__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3atripoint_20_3e_29727',['convert&lt; cata_variant_type::tripoint &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1tripoint_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3avgroup_5fid_20_3e_29728',['convert&lt; cata_variant_type::vgroup_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1vgroup__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3avoid_5f_20_3e_29729',['convert&lt; cata_variant_type::void_ &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1void___01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3awidget_5fid_20_3e_29730',['convert&lt; cata_variant_type::widget_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1widget__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_3c_20cata_5fvariant_5ftype_3a_3azone_5ftype_5fid_20_3e_29731',['convert&lt; cata_variant_type::zone_type_id &gt;',['../structcata__variant__detail_1_1convert_3_01cata__variant__type_1_1zone__type__id_01_4.html',1,'cata_variant_detail']]],
  ['convert_5fenum_29732',['convert_enum',['../structcata__variant__detail_1_1convert__enum.html',1,'cata_variant_detail']]],
  ['convert_5fenum_3c_20debug_5fmenu_3a_3adebug_5fmenu_5findex_20_3e_29733',['convert_enum&lt; debug_menu::debug_menu_index &gt;',['../structcata__variant__detail_1_1convert__enum.html',1,'cata_variant_detail']]],
  ['convert_5fenum_3c_20mutagen_5ftechnique_20_3e_29734',['convert_enum&lt; mutagen_technique &gt;',['../structcata__variant__detail_1_1convert__enum.html',1,'cata_variant_detail']]],
  ['convert_5fint_5fid_29735',['convert_int_id',['../structcata__variant__detail_1_1convert__int__id.html',1,'cata_variant_detail']]],
  ['convert_5fint_5fid_3c_20bodypart_5fid_20_3e_29736',['convert_int_id&lt; bodypart_id &gt;',['../structcata__variant__detail_1_1convert__int__id.html',1,'cata_variant_detail']]],
  ['convert_5fint_5fid_3c_20field_5ftype_5fid_20_3e_29737',['convert_int_id&lt; field_type_id &gt;',['../structcata__variant__detail_1_1convert__int__id.html',1,'cata_variant_detail']]],
  ['convert_5fint_5fid_3c_20furn_5fid_20_3e_29738',['convert_int_id&lt; furn_id &gt;',['../structcata__variant__detail_1_1convert__int__id.html',1,'cata_variant_detail']]],
  ['convert_5fint_5fid_3c_20oter_5fid_20_3e_29739',['convert_int_id&lt; oter_id &gt;',['../structcata__variant__detail_1_1convert__int__id.html',1,'cata_variant_detail']]],
  ['convert_5fint_5fid_3c_20ter_5fid_20_3e_29740',['convert_int_id&lt; ter_id &gt;',['../structcata__variant__detail_1_1convert__int__id.html',1,'cata_variant_detail']]],
  ['convert_5fint_5fid_3c_20trap_5fid_20_3e_29741',['convert_int_id&lt; trap_id &gt;',['../structcata__variant__detail_1_1convert__int__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_29742',['convert_string',['../structcata__variant__detail_1_1convert__string.html',1,'cata_variant_detail']]],
  ['convert_5fstring_3c_20std_3a_3astring_20_3e_29743',['convert_string&lt; std::string &gt;',['../structcata__variant__detail_1_1convert__string.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_29744',['convert_string_id',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20achievement_5fid_20_3e_29745',['convert_string_id&lt; achievement_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20activity_5fid_20_3e_29746',['convert_string_id&lt; activity_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20addiction_5fid_20_3e_29747',['convert_string_id&lt; addiction_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20bionic_5fid_20_3e_29748',['convert_string_id&lt; bionic_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20efftype_5fid_20_3e_29749',['convert_string_id&lt; efftype_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20faction_5fid_20_3e_29750',['convert_string_id&lt; faction_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20field_5ftype_5fstr_5fid_20_3e_29751',['convert_string_id&lt; field_type_str_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20flag_5fid_20_3e_29752',['convert_string_id&lt; flag_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20furn_5fstr_5fid_20_3e_29753',['convert_string_id&lt; furn_str_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20item_5fgroup_5fid_20_3e_29754',['convert_string_id&lt; item_group_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20itype_5fid_20_3e_29755',['convert_string_id&lt; itype_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20matype_5fid_20_3e_29756',['convert_string_id&lt; matype_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20mongroup_5fid_20_3e_29757',['convert_string_id&lt; mongroup_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20move_5fmode_5fid_20_3e_29758',['convert_string_id&lt; move_mode_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20mtype_5fid_20_3e_29759',['convert_string_id&lt; mtype_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20mutation_5fcategory_5fid_20_3e_29760',['convert_string_id&lt; mutation_category_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20nested_5fmapgen_5fid_20_3e_29761',['convert_string_id&lt; nested_mapgen_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20npc_5ftemplate_5fid_20_3e_29762',['convert_string_id&lt; npc_template_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20oter_5ftype_5fstr_5fid_20_3e_29763',['convert_string_id&lt; oter_type_str_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20overmap_5fspecial_5fid_20_3e_29764',['convert_string_id&lt; overmap_special_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20palette_5fid_20_3e_29765',['convert_string_id&lt; palette_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20profession_5fid_20_3e_29766',['convert_string_id&lt; profession_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20proficiency_5fid_20_3e_29767',['convert_string_id&lt; proficiency_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20skill_5fid_20_3e_29768',['convert_string_id&lt; skill_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20species_5fid_20_3e_29769',['convert_string_id&lt; species_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20spell_5fid_20_3e_29770',['convert_string_id&lt; spell_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20ter_5ffurn_5ftransform_5fid_20_3e_29771',['convert_string_id&lt; ter_furn_transform_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20ter_5fstr_5fid_20_3e_29772',['convert_string_id&lt; ter_str_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20trait_5fid_20_3e_29773',['convert_string_id&lt; trait_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20trap_5fstr_5fid_20_3e_29774',['convert_string_id&lt; trap_str_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20vgroup_5fid_20_3e_29775',['convert_string_id&lt; vgroup_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20widget_5fid_20_3e_29776',['convert_string_id&lt; widget_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['convert_5fstring_5fid_3c_20zone_5ftype_5fid_20_3e_29777',['convert_string_id&lt; zone_type_id &gt;',['../structcata__variant__detail_1_1convert__string__id.html',1,'cata_variant_detail']]],
  ['coord_5fpair_29778',['coord_pair',['../structmap__memory_1_1coord__pair.html',1,'map_memory']]],
  ['coord_5fpoint_29779',['coord_point',['../classcoords_1_1coord__point.html',1,'coords']]],
  ['coord_5fpoint_3c_20point_2c_20coords_3a_3aorigin_3a_3aabs_2c_20coords_3a_3aom_20_3e_29780',['coord_point&lt; point, coords::origin::abs, coords::om &gt;',['../classcoords_1_1coord__point.html',1,'coords']]],
  ['coord_5fpoint_3c_20point_2c_20coords_3a_3aorigin_3a_3aabs_2c_20coords_3a_3aomt_20_3e_29781',['coord_point&lt; point, coords::origin::abs, coords::omt &gt;',['../classcoords_1_1coord__point.html',1,'coords']]],
  ['coord_5fpoint_3c_20point_2c_20coords_3a_3aorigin_3a_3aabs_2c_20coords_3a_3asm_20_3e_29782',['coord_point&lt; point, coords::origin::abs, coords::sm &gt;',['../classcoords_1_1coord__point.html',1,'coords']]],
  ['coord_5fpoint_3c_20point_2c_20coords_3a_3aorigin_3a_3aovermap_2c_20coords_3a_3aomt_20_3e_29783',['coord_point&lt; point, coords::origin::overmap, coords::omt &gt;',['../classcoords_1_1coord__point.html',1,'coords']]],
  ['coord_5fpoint_3c_20point_2c_20coords_3a_3aorigin_3a_3aovermap_2c_20coords_3a_3asm_20_3e_29784',['coord_point&lt; point, coords::origin::overmap, coords::sm &gt;',['../classcoords_1_1coord__point.html',1,'coords']]],
  ['coord_5fpoint_3c_20point_2c_20coords_3a_3aorigin_3a_3asubmap_2c_20coords_3a_3ams_20_3e_29785',['coord_point&lt; point, coords::origin::submap, coords::ms &gt;',['../classcoords_1_1coord__point.html',1,'coords']]],
  ['coord_5fpoint_3c_20tripoint_2c_20coords_3a_3aorigin_3a_3aabs_2c_20coords_3a_3ams_20_3e_29786',['coord_point&lt; tripoint, coords::origin::abs, coords::ms &gt;',['../classcoords_1_1coord__point.html',1,'coords']]],
  ['coord_5fpoint_3c_20tripoint_2c_20coords_3a_3aorigin_3a_3aabs_2c_20coords_3a_3aomt_20_3e_29787',['coord_point&lt; tripoint, coords::origin::abs, coords::omt &gt;',['../classcoords_1_1coord__point.html',1,'coords']]],
  ['coord_5fpoint_3c_20tripoint_2c_20coords_3a_3aorigin_3a_3aabs_2c_20coords_3a_3asm_20_3e_29788',['coord_point&lt; tripoint, coords::origin::abs, coords::sm &gt;',['../classcoords_1_1coord__point.html',1,'coords']]],
  ['coord_5fpoint_3c_20tripoint_2c_20coords_3a_3aorigin_3a_3aovermap_2c_20coords_3a_3aomt_20_3e_29789',['coord_point&lt; tripoint, coords::origin::overmap, coords::omt &gt;',['../classcoords_1_1coord__point.html',1,'coords']]],
  ['coord_5fpoint_3c_20tripoint_2c_20coords_3a_3aorigin_3a_3areality_5fbubble_2c_20coords_3a_3ams_20_3e_29790',['coord_point&lt; tripoint, coords::origin::reality_bubble, coords::ms &gt;',['../classcoords_1_1coord__point.html',1,'coords']]],
  ['coord_5fpoint_3c_20tripoint_2c_20coords_3a_3aorigin_3a_3arelative_2c_20coords_3a_3ams_20_3e_29791',['coord_point&lt; tripoint, coords::origin::relative, coords::ms &gt;',['../classcoords_1_1coord__point.html',1,'coords']]],
  ['coord_5fpoint_3c_20tripoint_2c_20coords_3a_3aorigin_3a_3arelative_2c_20coords_3a_3aomt_20_3e_29792',['coord_point&lt; tripoint, coords::origin::relative, coords::omt &gt;',['../classcoords_1_1coord__point.html',1,'coords']]],
  ['coord_5fpoint_5fbase_29793',['coord_point_base',['../classcoords_1_1coord__point__base.html',1,'coords']]],
  ['coord_5fpoint_5fmut_29794',['coord_point_mut',['../classcoords_1_1coord__point__mut.html',1,'coords']]],
  ['coord_5fpoint_5fmut_3c_20point_2c_20coord_5fpoint_3c_20point_2c_20origin_2c_20scale_2c_20false_20_3e_2c_20false_20_3e_29795',['coord_point_mut&lt; Point, coord_point&lt; point, Origin, Scale, false &gt;, false &gt;',['../classcoords_1_1coord__point__mut.html',1,'coords']]],
  ['coord_5fpoint_5fmut_3c_20point_2c_20subpoint_2c_20true_20_3e_29796',['coord_point_mut&lt; Point, Subpoint, true &gt;',['../classcoords_1_1coord__point__mut_3_01Point_00_01Subpoint_00_01true_01_4.html',1,'coords']]],
  ['coord_5ftransformation_29797',['coord_transformation',['../structcoord__transformation.html',1,'']]],
  ['copt_29798',['cOpt',['../classoptions__manager_1_1cOpt.html',1,'options_manager']]],
  ['correct_5fz_5flevel_5fcheck_29799',['correct_z_level_check',['../classjmapgen__nested_1_1correct__z__level__check.html',1,'jmapgen_nested']]],
  ['cosmetic_5ffind_5fresult_29800',['cosmetic_find_result',['../structcosmetic__find__result.html',1,'']]],
  ['cosmetic_5ft_29801',['cosmetic_t',['../structsubmap_1_1cosmetic__t.html',1,'submap']]],
  ['craft_5factivity_5factor_29802',['craft_activity_actor',['../classcraft__activity__actor.html',1,'']]],
  ['craft_5fcommand_29803',['craft_command',['../classcraft__command.html',1,'']]],
  ['craft_5fdata_29804',['craft_data',['../classitem_1_1craft__data.html',1,'item']]],
  ['craft_5froll_5fdata_29805',['craft_roll_data',['../structCharacter_1_1craft__roll__data.html',1,'Character']]],
  ['crafting_5fcache_5ftype_29806',['crafting_cache_type',['../structCharacter_1_1crafting__cache__type.html',1,'Character']]],
  ['creature_29807',['Creature',['../classCreature.html',1,'']]],
  ['creature_5frange_29808',['Creature_range',['../classgame_1_1Creature__range.html',1,'game']]],
  ['creature_5ftracker_29809',['creature_tracker',['../classcreature__tracker.html',1,'']]],
  ['csct_29810',['cSCT',['../classscrollingcombattext_1_1cSCT.html',1,'scrollingcombattext']]],
  ['cuboid_29811',['cuboid',['../structcuboid.html',1,'']]],
  ['cundo_29812',['cUndo',['../classsokoban__game_1_1cUndo.html',1,'sokoban_game']]],
  ['custom_5fsymbol_29813',['custom_symbol',['../classauto__notes_1_1custom__symbol.html',1,'auto_notes']]]
];
